### ISSUE TITLE
Datepicker with different locale doesn't work on Stackblitz

### ISSUE THREAD

**Issue by WizardPC** [angular/components#10086]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Having "Datepicker with different locale" working like the example.

#### What is the current behavior?

Error in the console (Chrome) :
Unhandled Promise rejection: Cannot read property 'firstDayOfWeek' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'firstDayOfWeek' of null

#### What are the steps to reproduce?

Just go to [https://stackblitz.com/angular/rddbnyegnqe?file=app%2Fdatepicker-locale-example.ts](https://stackblitz.com/angular/rddbnyegnqe?file=app%2Fdatepicker-locale-example.ts)

#### Is there anything else we should know?

I tried to use it myself without looking at the example and i'm not able to change the locale of the datepicker, unless i set "providers: [{ provide: LOCALE_ID, useValue: 'fr-FR' }]" inside @NgModule. But with or without MomentJS, i can't set a new locale to the datepicker inside my component.

Perhaps it's linked to [https://angular.io/guide/i18n#setting-up-the-locale-of-your-app](https://angular.io/guide/i18n#setting-up-the-locale-of-your-app) ??

**Comment by julianobrasil** [comment]
That's because in stackblitz you don't have the locale files (and you usually have them locally inside `@angular/common/locales`).

You can copy the desired locale from your local folder to stackblitz and do the steps in the guide you've posted.

**Comment by WizardPC** [comment]
But why it's working here [https://stackblitz.com/edit/angular-gduxoq?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-gduxoq?file=app%2Fapp.component.ts) ?

**Comment by julianobrasil** [comment]
You're right. For some reason, the date adapter is not being injected.

**Comment by mmalerba** [comment]
Related to #9780

**Comment by akshaybhat30** [comment]
HI any update on the same i have tried everything but the MAT_DATE_LOCALE is still not working in this demo
https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fdatepicker-locale-example.ts

**Comment by mmalerba** [comment]
I think this is the same issue that seems to happen only on stackblitz tracked here https://github.com/angular/components/issues/9780
