### ISSUE TITLE
[MatPaginator] Extracting the OF preposition out of getRangeLabel for easier I18n

### ISSUE THREAD

**Issue by dushkostanoeski** [angular/components#10109]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
To be able to provide a class that only replaces the string values and not the whole `getRangeLabel` function. The code:

```
...
 /** A label for the preposition. */
  prepositionLabel: string = 'of';

  /** A label for the range of items within the current page and the length of the whole list. */
  getRangeLabel = (page: number, pageSize: number, length: number) => {
    if (length == 0 || pageSize == 0) { return `0 ${this.prepositionLabel} ${length}`; }

    length = Math.max(length, 0);

    const startIndex = page * pageSize;

    // If the start index exceeds the list length, do not try and fix the end index to the end.
    const endIndex = startIndex < length ?
        Math.min(startIndex + pageSize, length) :
        startIndex + pageSize;

    return `${startIndex + 1} - ${endIndex} ${this.prepositionLabel} ${length}`;
  }
...
```
#### What is the current behavior?
I don't know how often people replace the way the range label is generated, but I am guessing most just copy/paste the code and only translate the preposition to their language. 

#### What is the use-case or motivation for changing an existing behavior?
If there are changes in the logic behind `getRangeLabel`, they won't be reflected if you are providing translations. Most languages work the same way (the preposition is between the `endIndex` and `length`) so extracting the preposition would be much more convenient.

**Comment by crisbeto** [comment]
> Most languages work the same way (the preposition is between the endIndex and length)

While this might be the case for _most_ languages, it definitely isn't for all of them. If we did this, we're opening ourselves up to having to deal with a bunch of edge cases that'll start showing up.

**Comment by dushkostanoeski** [comment]
That is why I'm not saying to completely hide the `getRangeLabel` property. 

If you're working with a language where only the preposition needs to be translated, you provide only the preposition property, but if the whole label needs to be changed, you can skip the preposition and provide the label because the preposition is only used in the label.

**Comment by crisbeto** [comment]
As mentioned above, moving out only the preposition isn't the correct way of supporting different locales. The proper way of doing it would be through something like `$localize` and placeholder expressions.
