### ISSUE TITLE
Stackblitz example not working

### ISSUE THREAD

**Issue by GoNode5** [angular/components#10106]
https://stackblitz.com/angular/plqrqqvmaak?file=app%2Fform-field-custom-control-example.ts
Chrome Version Version 64.0.3282.186 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/2210672/36595938-49864562-18a4-11e8-9d1f-c2915d0fd975.png)

**Comment by jelbourn** [comment]
Confirmed the example is throwing an error.

**Comment by mmalerba** [comment]
It looks like the content of the HTML file are missing on stackblitz. If I copy/paste the HTML that it shows on the docs site the example works fine. I wonder if the stackblitz writer is not escaping `&`. There's some `&ndash;` in the html
