### ISSUE TITLE
dataSource.filter to accept objects or arrays other than string

### ISSUE THREAD

**Issue by Abenezer** [angular/components#10178]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
dataSource.filter should accept any object so that filterPredicate function is more flexable. for example one should be able to pass an array then use it on filterPredicate to filter multiple columns.

#### What is the current behavior?
currently dataSource filter support only String. so we have to contacate and split on predicateFunction

**Comment by tinayuangao** [comment]
@Abenezer I think you can create your own `DataSource` and make the `filter` supports objects/arrays.

@andrewseguin Is this something we plan to do?

**Comment by Abenezer** [comment]
your right you can extened the `DataSource` but you have to overide `perdicateFunction` also as it's filter parameter is typed 'String' . but it would be realy nice if it support object/arrays in the first place.

**Comment by Bradenb25** [comment]
One thing I've done is pass in a string and convert it to a JavaScript Object. Kind of hacky, but saves you the time of extending DataSource

**Comment by PaulSec** [comment]
Do you know if there's any updates on this one? Have a good day you all!

**Comment by andrewseguin** [comment]
Our intention with the `MatTableDataSource` is to help start the basic use cases and not get too much functionality. We encourage users to develop their own `DataSource` that matches their needs, using the `MatTableDataSource` as an inspiration. This would give clients full control over what they need from the data source without adding opinions to the basic `MatTableDataSource` which might not fit others needs
