### ISSUE TITLE
Directionality is not implemented for dir="auto"

### ISSUE THREAD

**Issue by philip-firstorder** [angular/components#10186]
#### Bug, feature request, or proposal:
Need to implement auto directionality so that the direction can be determined by the text language.
![screen shot 2018-02-28 at 12 18 32](https://user-images.githubusercontent.com/30979663/36785260-8a136088-1c82-11e8-9750-9b4a06a5db34.png)

#### What is the expected behavior?
- `sushi` text should be aligned to the left because dir="auto is used on the input
- `Leave a comment` placeholder should align to the left because dir="auto" was used on its entire form-field, which would include labels, errors, hints, icon etc.

#### What is the current behavior?
All controls and values inherit the dir="rtl" value from the container form.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pvwfjq?file=app/input-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
To implement native dir="auto".

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "^5.2.3",
"@angular/material": "^5.2.3",

**Comment by crisbeto** [comment]
We've got a TODO for it [here](https://github.com/angular/material2/blob/master/src/cdk/bidi/directionality.ts#L46). The issue is that in order for us to know what the value is, we have to do a `getComputedStyle` call which can be expensive.

**Comment by johankvint** [comment]
Is there a workaround to get this to work?
I only want specific inputs to be dir="auto", the rest of the page should be "ltr", which seems impossible now if the dir is not passed through from the input
