### ISSUE TITLE
Feature Request (mat-selection-list) : Allow single item selection

### ISSUE THREAD

**Issue by seedy** [angular/components#10213]
#### Feature request, or proposal:
Allow single item selection in selection lists as is in button-toggle-group
#### What is the expected behavior?
Cousin of button-toggle-group, radiobutton and select.

List items change color when hovered, focused or clicked
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

#### What is the use-case or motivation for changing an existing behavior?
Allow choice in a list of always visible values.
Values would range from 5 to a wide scrollable number of items.

**Comment by devversion** [comment]
Thanks @sdsanders. Closing this in favor of https://github.com/angular/components/issues/7157.
