### ISSUE TITLE
[Sort] Display sort direction indicator when no sort direction is defined.

### ISSUE THREAD

**Issue by fljmayer** [angular/components#10238]
#### Bug, feature request, or proposal:
I would like to change the sort direction indicator to display something when no sort direction is selected. This would identify sortable columns without having to hover the mouse over them.

#### What is the expected behavior?
Display a special indicator when no sort direction is defined for a columns.

#### What is the current behavior?
Nothing is displayed unless I move the mouse over the column.

#### What are the steps to reproduce?
This is just the standard behavior of the mat-sort-header.

#### What is the use-case or motivation for changing an existing behavior?
I would like the user to see at a glance which columns are sortable.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All Angular Material 2 versions.

**Comment by jelbourn** [comment]
Closing since I don't think this is something we would do because it's not captured in the Material Design spec
