### ISSUE TITLE
[Sort] If header contains checkbox, not clickable in IE

### ISSUE THREAD

**Issue by dacbreakpoint** [angular/components#10273]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The material-checkbox in the table-header should be clickable even if the mat-sort-header is dynamicly disabled. 
(works/tested with Chrome, Edge)

#### What is the current behavior?
In InternetExplorer (Version: 11) I can't click the checkbox.

#### What are the steps to reproduce?
Visit this StackBlitz project with IE 11 and try to click the checkbox in the table header: https://stackblitz.com/edit/angular-ixnbyz<br/>

#### What is the use-case or motivation for changing an existing behavior?
Make IE 11 users have the same user experience

**Comment by molidestroyer** [comment]
Hi,

I'm having the same issue, any patch for this?

**Comment by albert-asin** [comment]
try this

          <th mat-header-cell *matHeaderCellDef>
              <mat-checkbox color="primary"></mat-checkbox>
            <span mat-sort-header [disabled]="!column.sortable">
              {{ column.header }}
            </span>
          </th>

Summary: put the attribute mat-sort-header in a span instead of in the th definition
cheers

**Comment by molidestroyer** [comment]
Thanks @albert-asin it works for me!

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
