### ISSUE TITLE
provide api to keep cdkConnectedOverlay open

### ISSUE THREAD

**Issue by vthinkxie** [angular/components#10337]
#### Bug, feature request, or proposal:
request

#### What is the expected behavior?

Provide a new API to keep cdkConnectedOverlay open.

#### What is the current behavior?
When set `[cdkConnectedOverlayOpen]="true"` and press esc, the cdkConnectedOverlay was closed, I have tried to find method to keep cdkConnectedOverlay open and ignore the esc press event, but there is no api provided yet.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-hjejas?file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
the component in cdkConnectedOverlay needs to keep communication with the components outside cdkConnectedOverlay, I want to set the cdkConnectedOverlay style to hidden instead destroy it.

**Comment by crisbeto** [comment]
Closing using the escape key can be disabled using the `cdkConnectedOverlayDisableClose` input.
