### ISSUE TITLE
Documentation : mat-stepper with components for each step

### ISSUE THREAD

**Issue by WizardPC** [angular/components#10365]
#### Bug, feature request, or proposal:

Documentation

#### What is the expected behavior?

Having a working example with a mat-stepper using "outside" components and their forms for each step.

#### What is the current behavior?

I just find an example with forms groups inside the component using "mat-stepper" itself.

#### Is there anything else we should know?

Find two answers, one on StackOverFlow not working...
and another on Reddit with a working stackblitz ! [https://stackblitz.com/edit/angular-vpoj5j](https://stackblitz.com/edit/angular-vpoj5j) 

If it's the good practice, can you add it to the official documentation ?

**Comment by x1c0** [comment]
Hi @josephperrott why was this closed? I can't find any proper docs for this scenario.. there is any good practice on how to achieve this?

**Comment by lt37** [comment]
I'm also wondering if this is a good practice, and am looking for a way to remove duplication in the parent component (every component with a stepper will have all these @ViewChild and getters)

**Comment by yannicklerestif** [comment]
I'm also interested in the answer. Specifically I would rather have had the individual steps create their own forms, as opposed to all forms being created in the stepper component.

**Comment by zarend** [comment]
Closing because #10537 resolves this issue.
