### ISSUE TITLE
MatSelectionList with Radiogroup

### ISSUE THREAD

**Issue by Frozen-byte** [angular/components#10480]
#### What is the expected behavior?
I would like to have a new option for MatSelectionList Component to only make one choice at a time possible.
If this option is true, the Checkboxes should become Radiocontrols.

#### What is the current behavior?
There is no option to make only one choice exclusive.

#### What are the steps to reproduce?
https://material.angular.io/components/list/overview#selection-lists
You are able to tick every single option.

#### What is the use-case or motivation for changing an existing behavior?
Sometimes you would like to indicate all possible variants but the User is only able to chose one of them. In a Poll with only one valid choice for Example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest stable

#### Is there anything else we should know?
I currently fake the exclusive choice by unticking the whole selectionList and only tick the selected Item; The Checkboxes annoy the user as they indicate a multiple-choice-option.

**Comment by WizardPC** [comment]
You can do the same with an ngFor and classic radio input no ?

**Comment by Frozen-byte** [comment]
Indeed, @WizardPC this also applies to Checkboxes: I can use default Checkbox Component and ngFor them.

A ngFor Radiogroup would not have the native design like a MaterialList and there would be a lot effort to copycat the MaterialSelectionList CSS-Rules into the handcrafted Radiogroup.

**Comment by andresbm05** [comment]
I think it should also be possible to hide the checkbox or the radiobutton. If you want a single select list that forwards you to somewhere or pops a modal to edit the item you don't want any kind of selection marker.

**Comment by IlCallo** [comment]
Duplicate #10213 #7157
I'm interested in this as well

**Comment by Hhpon** [comment]
Can't the attribute RadioGroup of matRadioButton associate radio-button with radio-group?
![image](https://user-images.githubusercontent.com/33001067/86895611-4e586780-c137-11ea-859b-98c52e8b73e2.png)

**Comment by crisbeto** [comment]
Closing as a duplicate of https://github.com/angular/components/issues/7157.
