### ISSUE TITLE
Autcomplete problematic behaviour (iPad)

### ISSUE THREAD

**Issue by LMalorgio** [angular/components#10491]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Autocomplete panel floating either up or down the search bar (iPad)

#### What is the current behavior?

Autocomplete panel floats above search bar on scroll

#### What are the steps to reproduce?

Link to home-made repository: https://github.com/LMalorgio/material-autocomplete-malfunction
Some examples come from AM's website itself: https://material.angular.io/components/autocomplete/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material": "^5.2.4"
Chrome 65.0.3325.152

## Full description of the issues are provided in my repository

/cc @davinkevin @Neonox31

**Comment by julianobrasil** [comment]
Not directly related to your issu, but as you're sharing a repo, it's possible to run github public angular repos directly at stacklitz. In this case: https://stackblitz.com/github/LMalorgio/material-autocomplete-malfunction

**Comment by jelbourn** [comment]
I think this is a duplicate of #16004, but feel free to comment if that's not the case
