### ISSUE TITLE
Disable all animations with NoopAnimationsModule

### ISSUE THREAD

**Issue by calebegg** [angular/components#10590]
For e2e/screenshot tests, it's nice to be able to disable animations. However, even when installing `NoopAnimationsModule`, some material animations still run e.g. the loading spinner, the focus animation on text fields.

This is a feature request to have `NoopAnimationsModule` disable all animations in Material.

**Comment by josephperrott** [comment]
First step towards this being possible is being added in https://github.com/angular/angular/pull/23075

**Comment by benb7760** [comment]
@crisbeto I think that dialog needs to be done also, I can't see a PR for that

**Comment by crisbeto** [comment]
@benb7760 all the dialog animations are done through Angular which means that the `NoopAnimationsModule` works automatically already.

**Comment by leolanese** [comment]
Still displaying animation after importing 'NoopAnimationsModule', any solution/alternative could be very welcome.
