### ISSUE TITLE
Ability to change $subscript-font-scale

### ISSUE THREAD

**Issue by trashhead** [angular/components#10595]
#### Bug, feature request, or proposal:
feature request.
To be able to change the variable $subscript-font-scale: 0.75;

#### What is the expected behavior?
Bigger subscripted font scale in mat-field (when text is animated above the field)

#### What is the current behavior?
The placeholder that goes above the field when selecting field is too small

#### What are the steps to reproduce?
Select text field. Text animates above field.
Text is very tiny. 
https://material.angular.io/components/form-field/overview

#### What is the use-case or motivation for changing an existing behavior?
People that doesnt have 20/20 vision are having problems reading

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least current version: 5.2.x
All browsers

**Comment by jscti** [comment]
+1 that

**Comment by DanieleAlessandra** [comment]
+1

**Comment by devversion** [comment]
Thanks for this issue. Closing this in favor of https://github.com/angular/components/issues/17878 that talks about these variables more in general.
