### ISSUE TITLE
Hide years superior to max date in datepicker

### ISSUE THREAD

**Issue by WizardPC** [angular/components#10646]
#### Bug, feature request, or proposal:

Proposal, change the view years if a maxdate is set.

#### What is the expected behavior?

If i set the maxdate as today (in 2018) i don't expect to see 2019, 2020, 2021... in the years view.

#### What is the current behavior?

All the years are visible but 2019, 2020, 2021... are disabled.
![issue_date](https://user-images.githubusercontent.com/11718892/38165842-669b919c-351a-11e8-8c52-98ef671c8326.PNG)

#### What is the use-case or motivation for changing an existing behavior?

I set a max date to limit the possibilities, i'm not (and the user) interrested in years that i can't select.
The extreme is if i set 2016, i can choose only this one among 24 differents years...

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest 

#### Is there anything else we should know?

I think the right disabled arrow if enough for understand that you can't go further in years.

**Comment by raygervais** [comment]
I'd like to try working this, adding the feature if @josephperrott you agree it's a nice to have. Thoughts?  😄

**Comment by josephperrott** [comment]
I will defer to @mmalerba for if its something that he would like to have included in datepicker as he is the component owner.

**Comment by mmalerba** [comment]
I think it was originally done this way because the component responsible for rendering the cells didn't actually know what the `min` and `max` were. I believe it was refactored at some point and it should now be possible to do this.

@raygervais sure I would appreciate if you're willing to take a stab at it and send me a PR.

**Comment by WizardPC** [comment]
@raygervais : i think it's in the `datepicker/multi-year-view.ts`, in the `init()` function we need to change the `let activeOffset = activeYear % yearsPerPage;.`

Actually the years view is build like that :
2018 % 24 = 2 so 2018 - 2 = 2016,2017,2018...
2039 % 24 = 23 so 2039 - 23 = 2016,2017,2018...

For the new behavior, if `maxDate` is not null, `activeOffset = yearsPerPage - 1`.
What do you think ?

@mmalerba 
From my point of view, this will end with four differents "years" view :
1. No min or max date => Actual behavior
2. Only the min date => `activeOffset = 0`
3. Only the max date => `activeOffset = yearsPerPage - 1`
4. Both min and max date =>  I propose `activeOffset = yearsPerPage - 1` too. Because it's seems prettier to display disabled past date than disabled future date.

Or for the fourth item, we can make `minDate`having the same behavior but with impacts :
1. `activeOffset < minDate < maxDate` There will be only one page with less than 24 years.
2. `minDate < activeOffset` The first page of calendar will display less than 24 years too.

**Comment by raygervais** [comment]
Thanks for the explanation @WizardPC, I'll get to that very soon. Apologies for the delay, just wrapping up loose ends during the final days of the school semester and preparing for a new job. If I got a WIP PR going, would you be able to guide if in the case I stray from the agreed upon logic?

**Comment by WizardPC** [comment]
@raygervais i'm not an expert but i can try :)

**Comment by labyed** [comment]
Hi guys, any update on this ?

**Comment by raygervais** [comment]
Sorry for the delay, I intend to get back to it this weekend. Currently adjusting to new job / location and getting everything set up.

**Comment by UmutAkkaya** [comment]
Hi, any update on this. It was updated almost a year ago

**Comment by mmalerba** [comment]
I had an intern who was working on it at one point, but it never got finished

**Comment by UmutAkkaya** [comment]
@mmalerba can it be reassigned to someone? As it is, I believe its a really bad UX

**Comment by mmalerba** [comment]
I don't think anyone on the team has time to take it on right now, but if someone wants to contribute a PR I'll review it

**Comment by comc49** [comment]
I believe this website is using the angular material date picker and it seems like you can control the input.
https://my.questforhealth.com/mobile/info/contact-us
Anyone know what's a quick hack to enable this?

**Comment by jysoo** [comment]
@mmalerba  Seems like currently there's no one working on a PR for this? May I give it a go?

**Comment by mmalerba** [comment]
@jysoo You're welcome to give it a go. Please also make sure that the keyboard shortcuts work in addition to looking right visually.
