### ISSUE TITLE
tabs: tab content doesn't show up after dialog close / open

### ISSUE THREAD

**Issue by fxck** [angular/components#10652]
repro https://stackblitz.com/edit/materia2-tabs-dialog-problem?file=app%2Fapp.component.html

steps: 

- open dialog
- close dialog
- open dialog
- **go to the second tab** (content **doesn't** show up)
- go to the first tab
- go to the second tab (content does show up)

same thing happens to stepper as well btw

cc @mmalerba cc @andrewseguin

**Comment by julianobrasil** [comment]
I works with lazy loading the tab content (`matTabContent` directive). The drawback it that it removes and recreates all of the content every time you switch back and forth to the lazy content tab.

**Comment by fxck** [comment]
I don't think ii works with `matTabContent` either @julianobrasil

**Comment by fxck** [comment]
Yes. Exactly. It doesn't work. :) 

![](https://media.giphy.com/media/xViA6uDSHX3f0sxV7Q/giphy.gif)

**Comment by julianobrasil** [comment]
Ok, I've done some more tests over here. It has to do with the view port size and resizing (that's odd!!):

![image](https://media.giphy.com/media/2vkkrs0bBrTmB82wpA/giphy.gif)

**Comment by julianobrasil** [comment]
In fact, over here (windows 10 + chrome) the problem just occurs when I resize the window.

**Comment by julianobrasil** [comment]
The funny part is that the problem is not happening in my real project in production... maybe something with `ng build --prod`?

**Comment by fxck** [comment]
My guess is that it has something to do with the way I'm using dialog service to create a dumb dialog component.

**Comment by mmalerba** [comment]
Confirmed that this is working in v15: https://stackblitz.com/edit/angular-56dgpe
