### ISSUE TITLE
MatNativeDateAdapter: First day of the week [discussing, proposal]

### ISSUE THREAD

**Issue by SaturnTeam** [angular/components#10778]
#### Bug, feature request, or proposal:
feature

#### What is the expected behavior?
First day of the week depends of choosen locale

#### What is the current behavior?
Week always starts with Sunday

#### What is the use-case or motivation for changing an existing behavior?
Doesn't seem diffucult

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
any

#### Is there anything else we should know?
NativeDateAdapter always shows first day of the week is Sunday, due to it is hard-coded here: https://github.com/angular/material2/blob/master/src/lib/core/datetime/native-date-adapter.ts#L138

I want to pull these changes + write one more test: https://github.com/SaturnTeam/saturn-datepicker/commit/cd7fcf270a7bedc623c8ba9acf648a46278bdf8f
I parsed moment.js locales to determine in which locale first day is Monday or Saturday https://github.com/moment/moment/tree/develop/src/locale

I summon @mmalerba for this issue.

**Comment by mmalerba** [comment]
@SaturnTeam I was planning to integrate with the i18n API that came out with Angular 5 for this and other locale info in the `NativeDateAdapter` (see https://github.com/angular/material2/issues/8100). Olivier actually posted a working example at one point, though it probably needs to be updated now. Would you be interested in picking that up and sending a PR?

**Comment by SaturnTeam** [comment]
@mmalerba It's interesting. I'll make up my mind on a next week

**Comment by SaturnTeam** [comment]
As I can see, related issues is not closed. I'm interested in closing them all.

**Comment by jlaine** [comment]
In my code I've worked around this by using a simple custom date adapter:

```
@Injectable()
export class LocaleDateAdapter extends NativeDateAdapter {
    getFirstDayOfWeek() {
        return getLocaleFirstDayOfWeek(this.locale);
    }
}
```

**Comment by razorch** [comment]
> In my code I've worked around this by using a simple custom date adapter:
> 
> ```js
> @Injectable()
> export class LocaleDateAdapter extends NativeDateAdapter {
>     getFirstDayOfWeek() {
>         return getLocaleFirstDayOfWeek(this.locale);
>     }
> }
> ```

It does not work, unfortunately. I see this example everywhere but nothing changes when i'm implementing it. Any help?

**Comment by SaturnTeam** [comment]
> > In my code I've worked around this by using a simple custom date adapter:
> > ```js
> > @Injectable()
> > export class LocaleDateAdapter extends NativeDateAdapter {
> >     getFirstDayOfWeek() {
> >         return getLocaleFirstDayOfWeek(this.locale);
> >     }
> > }
> > ```
> 
> It does not work, unfortunately. I see this example everywhere but nothing changes when i'm implementing it. Any help?

1) `getLocaleFirstDayOfWeek` should contain a code. Example https://github.com/SaturnTeam/saturn-datepicker/blob/master/saturn-datepicker/src/datetime/native-date-adapter.ts#L151 
2) You need to prodive new LocaleDateAdapter instead of NativeDateAdapter (you can see example in official documentation of datepicker)

**Comment by crisbeto** [comment]
It seems like the author resolved their issue and there hasn't been any activity in a while. Closing.
