### ISSUE TITLE
Need a way to prevent being able to tab to content behind a dialog

### ISSUE THREAD

**Issue by rowlandc79** [angular/components#10782]
#### Bug, feature request, or proposal:
When a dialog is open, we don't want to be able to tab to the form items behind the modal. Can't seem to find a way to prevent this.

#### What is the expected behavior?
To be able to prevent tabbing out of the modal.

#### What is the current behavior?
Am able to tab out of the modal.

#### What are the steps to reproduce?
https://dialog-example-khap4o.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Bad user experience. The items behind the modal are out of context and not relevant to what the user is currently doing.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers. Material 2, Angular 5.

#### Is there anything else we should know?
Nope

**Comment by WizardPC** [comment]
Can you change your link so we can access the source ?

**Comment by rowlandc79** [comment]
Hi, you can see the code from the following link:
https://stackblitz.com/edit/dialog-example?file=app%2Fapp.component.ts

**Comment by WizardPC** [comment]
What's the purpose of your `tabindex` ??

> A tabindex="-1" value removes the element from the default navigation flow (i.e., a user cannot tab to it), but it allows it to receive programmatic focus, meaning focus can be set to it from a link or with scripting.** This can be very useful for elements that should not be tabbed to, but that may need to have focus set to them.

You have changed the native focus behavior with tabindex. Juste remove it and it's works as expected.

**Comment by crisbeto** [comment]
This seems to be handled by the focus trap in the latest version. Closing.
