### ISSUE TITLE
Auto select suggestion in auto-complete

### ISSUE THREAD

**Issue by vimalraj-a** [angular/components#10834]
#### feature request:
Need option or default action for auto select the suggestion value in auto complete suggestion list

#### What is the expected behavior?
Provide option to auto select mat-option. If formControl value matches the option's value field then mat-option should be selected / active.

#### What is the current behavior?
First or no mat-option active.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-autocomplete-default-selected-value?file=app%2Fautocomplete-overview-example.ts

#### What is the use-case or motivation for changing an existing behavior?
Without default value option we cannot use this control in our forms.

Currently we achieving default selection  by below code on focus of input
```javascript
      const val = this.employeeForm.get('reportingManager').value;
      const idx = this.approvers.findIndex(v => v.name === val);
      this.reportingAuto._keyManager.setActiveItem(idx);
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "5.2.4",
"typescript": "~2.5.3"

**Comment by atifsaddique211f** [comment]
Until there is no solution provided by Angular material, the above solution works well with just one more thing, the selected item should be scrolled into view. I have done it like below.

```
// @ts-ignore
this.matAutocomplete._keyManager.setActiveItem(index);
this.matAutocomplete._keyManager.activeItem._element.nativeElement.scrollIntoView();
```

**Comment by crisbeto** [comment]
Should be covered by https://github.com/angular/components/issues/17246.
