### ISSUE TITLE
Date Picker positioning in iframe on iOS Safari, Chrome and Firefox

### ISSUE THREAD

**Issue by djindjic** [angular/components#10873]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Date picker on page which is shown in iframe should behave same as without iframe "parent"

#### What is the current behavior?
Date picker does not appear in correct position and page scrolls unexpectedly

#### What are the steps to reproduce?
https://stackblitz.com/edit/datapicker-iframe-ios?file=index.html
It's juts iframe pointing to date-picker examples page in docs

#### What is the use-case or motivation for changing an existing behavior?
Angular app is hosted in iframe as part of an bigger app.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 5.2.0
OS: iOS 11.3
Browser: iOS Safari, Chrome and Firefox

**Comment by mmalerba** [comment]
This is happening because the cdk/overlay based datepicker popup detects when it would be partially off-screen and changes its position accordingly. Since you're placing it in an iframe "off-screen" in this case means outside of the iframe. So I consider this to be WAI
