### ISSUE TITLE
UI of required component in reactive way and template-driven way is different

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/components#10896]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

I expect that reactive control (created via FormControl) with required validator will behave as required control in template driven form.

#### What is the current behavior?

In template-driven forms when component has required attribute some star in the form field appears. When field is invalid by required criteria star is red. In reactive forms (when we pass validator to form control) there is no star.

I expect that if I create control like this: 
```
this.myControl = new FormControl('Dog', [Validators.required]);
```
control will get correct validation state (red/not-red) and UI state will be appropriate (star will be in the form field).

Now it is not enough. I also have to add required attribute in the HTML. 

Difference in pictures:

without required attr:
![](https://i.imgur.com/cSl9S9q.png)

with required attr:
![](https://i.imgur.com/GHZHLWY.png)

So I have to mix reactive/template-driven ways.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

Here is stackblitz example: https://stackblitz.com/edit/angular-material2-issue-k8cd1w

1. Open both select's and select `--` option.
2. You will see that one of controls has red star, another does not have it.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

5.x.x and more.

**Comment by sharikovvladislav** [comment]
Look there: https://github.com/angular/material2/blob/5.2.4/src/lib/select/select.ts#L352
This works only in template-driven way. So if that setter was not called, then _required is false. Thats why this `*ngIf` hides the star: https://github.com/angular/material2/blob/5.2.4/src/lib/form-field/form-field.html#L43. 

So everything works as code says. It is planned.

What is correct use case? What should I do? Should I create custom validator function and pass it to the control (when I create it) and also pass this function as `[required]` expression?

**Comment by mmalerba** [comment]
This is a dup of https://github.com/angular/components/issues/2574
