### ISSUE TITLE
RadioGroup with long lists inside MatCard with fixed height breaks the page.

### ISSUE THREAD

**Issue by Joaovtrc** [angular/components#10923]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I select a radio-button, the page should remain the same.

#### What is the current behavior?
When I select a radio-button that is inside a scrollable <mat-card-content> and down at the bottom of the List the page goes up.

#### What are the steps to reproduce?
Select some radio-button down in the list.
StackBlitz: https://stackblitz.com/edit/angular-z4qcni?file=app%2Fcard-overview-example.html<br/>
With mat-selection-list it works just fine.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on 5.2.4 and 5.2.5 in Chrome.

**Comment by rbudnar** [comment]
I've noticed the same problem with the `mat-radio-button` with a long list of radio buttons. When I scroll down and select an option from the bottom of the list, the page jumps up.

I'm not sure if this is the best way to fix it, but this override in my global styles appears to resolve the issue for me:
```
.mat-radio-label .cdk-visually-hidden {
  position: relative;
}
```

**Comment by jelbourn** [comment]
Doesn't seem to happen with the latest version: https://stackblitz.com/edit/angular-z4qcni-wrmuuo?file=main.ts
