### ISSUE TITLE
[@angular/cdk] feature request. Native inputs wrappers

### ISSUE THREAD

**Issue by evgeniyefimov** [angular/components#10930]
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behavior?
Quite often devs need to create custom checkboxes, radios etc. with own styles. Angular material has own wrappers for native inputs, it allows to customize it, add animation, have accessibility and so on. I think many devs create own custom form controls for this, and this is really exhausting.
I had own wrappers but it was difficult to make it work like native input, so I downloaded @angular/material and extended my wrappers with material's form controls, but with own templates and styles. It gave me my own customized form controls which support API from material. But it requires to have installed @angular/material and some redundant dependencies into my code like material animation etc. So I completly removed angular/material, copied only needed code from the material's form controls without any animation, utilized only @angular/cdk and it works fine, with full API and accessibility.
Can we have some generic input wrappers, which will allow devs to easily customize it? So devs won't have headache when develop custom form controls for native inputs, like preventing DOM events, accessibility etc. which is common

#### What is the current behavior?
To create own wrapper for native form control with accessibility and events, devs have to write almost the same code as in the angular material's wrappers.

**Comment by mmalerba** [comment]
It sounds like something I would like to do, but I probably won't have time to work on it for a while

**Comment by mmalerba** [comment]
Closing as a dup of https://github.com/angular/components/issues/7891 which has a lot of discussion on the topic
