### ISSUE TITLE
Mat-hint and mat-error wrong behavior

### ISSUE THREAD

**Issue by havart** [angular/components#10932]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Will expect see hint or error

#### What is the current behavior?
The behavior is strange:
I try to build dynamic form by special config file.
See https://angular-material2-issue-vysbqe.stackblitz.io/

1. If You uncomment block inside **1. mat-error without ngFor START**. **<mat-error>The error</mat-error>** in this block. You'll not see mat-error

2. If You uncomment block inside **2. mat-error in ngFor START**, you'll see strange behavior of mat-error. The error message will be inside the input field

3. If You uncomment block inside **3.  mat-hint without ngFor START**, everything will be good.

4. If You uncomment block inside **4. mat-hint in ngFor START**, you'll see strange behavior of mat-hint. The error message will be inside the input field.

I have array of validation rules. I try to build dynamic validation section like below:
<ng-container *ngFor="let validator of input?.validators">
<mat-hint>{{validator.hint}}</mat-hint>
<mat-error *ngIf="
form.controls[field.target_component].controls[input.name].hasError(validator.name)">{{validator.error}}
</mat-error>
</ng-container>

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

How to reproduce it, I described earlier in the section **What is the current behavior**
Works example:
https://angular-material2-issue-vysbqe.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?
I think it need for build dynamic reactive form with validation rules.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm not sure this info help you. It easy reproduce in https://angular-material2-issue-vysbqe.stackblitz.io/
Angular: 5.2.0
Material: 5.2.4
OS: 10.13.1 
TypeScript: 2.8.1
browsers all

#### Is there anything else we should know?
This works on my other projects without material library. Also, it works if I create custom **div** element with custom css.

**Comment by mmalerba** [comment]
I think the issue is just the use of `<ng-container>` to wrap `<mat-error>` in your example. That causes the error message to be content projected into the wrong slot. Instead just leave it off: https://stackblitz.com/edit/components-issue-4vs5v4?file=src/app/example-component.html

**Comment by mmalerba** [comment]
I've opened an issue on angular/angular about the content behavior being confusing with `<ng-container>` https://github.com/angular/angular/issues/37328
