### ISSUE TITLE
[Sort] Transcluded content is showing T instead of the arrow

### ISSUE THREAD

**Issue by greenGoby** [angular/components#10937]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I would expect the table header sort icon to paint properly.  (No icon instead of a T)

#### What is the current behavior?
The table paints a T instead of an arrow, and the T is visible immediately.

#### What are the steps to reproduce?
It is recreated at this stackblitz:
https://stackblitz.com/edit/angular-vcmq2p

If you remove either the setTimeout from app.component.ts OR you get rid of the transclusion it works fine.  

My investigation seems to point to some of the animations at startup to rotate the angles of the arrow and set opacity are not firing when transclusion is mixed with a delayed *ngIf.  You can see a working version without transclusion at this stackblitz:
https://stackblitz.com/edit/angular-vcmq2p-8dpzaa

#### What is the use-case or motivation for changing an existing behavior?
It is a bug and causes our sorted tables to all have Ts on them.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
We are using Angular 5.2.10, and material 5.2.4.  All browsers.

**Comment by renato-rjps** [comment]
I have the same problem in my project

**Comment by czeckd** [comment]
As a temporary work around I added this to the app's styles.scss:
```scss
.mat-sort-header-arrow {
  opacity: 0;
}
```
It prevents the T from always showing when the transcluded mat-table is first displayed. It still is there, of course, if the cursor hovers over the sort, but only for the initial state. Once the sort is used, it seems okay.

**Comment by andrewseguin** [comment]
I believe this has been resolved
