### ISSUE TITLE
Tabbing into first input in custom form field control doesn't cause the control to be focused properly. Doesn't happen until tabbing to the second input

### ISSUE THREAD

**Issue by petsmatt** [angular/components#10998]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tabbing into the first element of the custom form field control should cause the control to gain focus and display the child input fields.

#### What is the current behavior?
Tabbing into the first element places the cursor over the placeholder text only and doesn't open up the input properly

#### What are the steps to reproduce?

This can be seen in the current documentation with the example provided on (https://material.angular.io/guide/creating-a-custom-form-field-control)  tabbing into the custom phone number field doesn't cause the first part of the custom phone number to gain focus

#### What is the use-case or motivation for changing an existing behavior?
User experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
^5.2.4

**Comment by WizardPC** [comment]
Reproductible :+1: 

![issue_10998](https://user-images.githubusercontent.com/11718892/39245584-7af6d9ac-4894-11e8-82db-2d92fb3f8d7a.png)

**Comment by mmalerba** [comment]
I think this is a side-effect from the fact that the `FocusMonitor` doesn't re-enter the zone before emitting. https://github.com/angular/material2/pull/10549 will probably fix it.

**Comment by mmalerba** [comment]
confirmed that this is fixed now
