### ISSUE TITLE
create `matElevation` directive

### ISSUE THREAD

**Issue by odahcam** [angular/components#11076]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Being able to change the element's elevation through the Material spec without any extra knowledge and programmatically. The directive would automatically apply any elevation styles, such as the SCSS classes.

#### What is the current behavior?
Have to use attribute classes that may be hard to manage or find in docs; `mat-elevation-z*`.

#### What is the use-case or motivation for changing an existing behavior?
This doesn't changes any behavior, but adds a common way to manipulate elevation.

**Comment by jelbourn** [comment]
Closing since I think we'll stick with CSS classes for elevation as to not incur extra directive overhead
