### ISSUE TITLE
create `matCardImageSize="<named-size>"` directive

### ISSUE THREAD

**Issue by odahcam** [angular/components#11082]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Being able to change the element's size through the Material spec without any extra knowledge and programmatically. The directive would automatically apply any sizing and positioning styles, such as the SCSS classes.

#### What is the current behavior?
Have to use attributes to size the image element, they cannot be changed at runtime to change the size.

#### What is the use-case or motivation for changing an existing behavior?
There's no docs for the `mat-card[-<named-size>]-image` directive nor SCSS classes, one directive which accepts different sizes would be easier to centralize and documentate.

**Comment by jelbourn** [comment]
Closing since we don't have any plans to add a feature like this
