### ISSUE TITLE
Paginator.lastPage() not updating

### ISSUE THREAD

**Issue by reuvainlevin** [angular/components#11130]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior
Adding a row which adds a new page and then calling  `paginator.lastPage()` should navigate to this new page.

#### What is the current behavior?
Navigates to second to last page - which was the last page before the new row was added.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Is there anything else we should know?
when i wrap  `paginator.lastPage()` in a `setTimeout()` it takes care of the problem 
but i was hoping for a bettor solution.

**Comment by josephperrott** [comment]
@reuvainlevin  Can you please provide a reproduction stackblitz?
