### ISSUE TITLE
Overlay "display:flex" breaks overlay's size config properties

### ISSUE THREAD

**Issue by danzrou** [angular/components#11174]
#### Bug, feature request, or proposal:
Bug but not sure.

#### What is the expected behavior?
Overlay should open according to it's OverlayConfig properties.

#### What is the current behavior?
After updating to v6.0 (both angular and material), minWidth and minHeight (and maybe others, did not test yet) are not applied to the component inside overlay.
I guess it is because display of cdk-overlay-pane is now "flex"

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

```

**Comment by crisbeto** [comment]
We've got [unit tests](https://github.com/angular/material2/blob/master/src/cdk/overlay/overlay.spec.ts#L398) that are passing and it seems to work from my testing. Can you post an example of the code that's breaking?

**Comment by danzrou** [comment]
Before the update, the dialogs would open according to minWidth and minHeight properties (in 'DEFAULT_OVERLAY_CONFIG').
Of course if I set the panel class with "display:block" it keeps the size properties.

`export const DEFAULT_OVERLAY_CONFIG: CustomOverlayConfig = {
  hasBackdrop: true,
  backdropClass: 'dark-backdrop',
  panelClass: 'overlay-panel',
  minWidth: 400,
  minHeight: 250
};

@Injectable()
export class OverlayService {

  constructor(private overlay: Overlay,
              private injector: Injector) {
  }

  private getOverlayConfig(config: CustomOverlayConfig, pos: 'global' | 'connectedTo', posConfig: { elRef?, originPos?: OriginConnectionPosition, overlayPos?: OverlayConnectionPosition } = {}) {
    const scrollStrategy = this.overlay.scrollStrategies.block();
    const posStrategy = pos === 'global' ?
      this.overlay.position().global().centerHorizontally().centerVertically():
      this.overlay.position().flexibleConnectedTo(posConfig.elRef/*, posConfig.originPos, posConfig.overlayPos*/);

    const overlayConfig = new OverlayConfig({
      hasBackdrop: config.hasBackdrop,
      backdropClass: config.backdropClass,
      panelClass: config.panelClass,
      width: config.width,
      height: config.height,
      minWidth: config.minWidth,
      minHeight: config.minHeight,
      maxWidth: config.maxWidth,
      maxHeight: config.maxHeight,
      positionStrategy: posStrategy,
      scrollStrategy: scrollStrategy
    });

    return overlayConfig;
  }

  private createOverlay(config: CustomOverlayConfig, pos: 'global' | 'connectedTo', posConfig: { elRef?, originPos?, overlayPos? } = {}) {
    const cfg = this.getOverlayConfig(config, pos, posConfig);

    return this.overlay.create(cfg);
  }

  private createInjector(config: CustomOverlayConfig, dialogRef: DialogRef) {
    const injectionTokens = new WeakMap();

    injectionTokens.set(DialogRef, dialogRef);
    injectionTokens.set(DIALOG_DATA_TOKEN, config.data);

    return new PortalInjector(this.injector, injectionTokens);
  }

  private attachDialogContainer(overlayRef: OverlayRef, config: CustomOverlayConfig, dialogRef: DialogRef, component: ComponentType<any>) {
    const injector = this.createInjector(config, dialogRef);

    const containerPortal = new ComponentPortal(component, null, injector);
    const containerRef: ComponentRef<any> = overlayRef.attach(containerPortal);

    return containerRef.instance;
  }

  open(config: CustomOverlayConfig = {}, component: ComponentType<any>, pos: 'global' | 'connectedTo', posConfig: { elRef?, originPos?: OriginConnectionPosition, overlayPos?: OverlayConnectionPosition } = {}): DialogRef {
    const dialogConfig = {...DEFAULT_OVERLAY_CONFIG, ...config};

    const overlayRef = this.createOverlay(dialogConfig, pos, posConfig);

    const dialogRef = new DialogRef(overlayRef);

    const overlayComponent = this.attachDialogContainer(overlayRef, dialogConfig, dialogRef, component);

    dialogRef.componentInstance = overlayComponent;

    if(config.closeOnBackdropClick)
      overlayRef.backdropClick().subscribe(mouseEvent => {
        if(isAnimationOverlay(dialogRef.componentInstance)){
          // console.log(`Instance of AnimatedOverlay!`, dialogRef.componentInstance);
          dialogRef.componentInstance.closeDialog(OverlayActions.CLOSE);
        }
        else
          dialogRef.backdropClose();
      });

    return dialogRef;
  }


}
`

**Comment by crisbeto** [comment]
@danzrou I see, I thought you were talking about the connected overlays. The `minWidth` and `minHeight` definitely still work for global overlays, but you may have to tweak your own styling to account for the new DOM structure in 6.0.

**Comment by crisbeto** [comment]
Closing since this seems like an issue with custom code on top of the CDK and there hasn't been any activity in a long time.
