### ISSUE TITLE
Sidenav Miscalculates the content width when there is a vertical scrollbar

### ISSUE THREAD

**Issue by vbourdeix** [angular/components#11176]
#### Bug, feature request, or proposal:
**Bug**

#### What is the expected behavior?
The content should always fit inside the main content area even if there is a scrollbar

#### What is the current behavior?
When you open the sidenav and the content has a lot of text, the main content width doesn't seem to be calculated properly as the right end of the text gets hidden behind the vertical scrollbar.

#### What are the steps to reproduce?
You can try it here https://angular-zlgxip.stackblitz.io/
And see the code here (taken right from a documentation example) : 
https://stackblitz.com/edit/angular-zlgxip?file=app/sidenav-responsive-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Based on the stackblitz, Angular is in version 6, same for @angular/material. Tested on Chrome 65 Windows

#### Is there anything else we should know?
When you resize the window, the size is calculated again and fixes the issue. If you close and open the sidenav, it appears again.

**Comment by crisbeto** [comment]
Your first link doesn't seem to work @vbourdeix (looks like an issue with Stackblitz). Can try to recreate it or to post a link to the code?

**Comment by vbourdeix** [comment]
I've forked and edited the links in my initial post

**Comment by pfeigl** [comment]
Just looked into this, content area width is not actually calculated. The drawer (sidenav) only adds margins to the content to accomodate for the sidenav when it's visible.

Browser doesn't seem to recalculate properly. Firefox actually works as expected, Chrome doesn't.
