### ISSUE TITLE
Can not tab out of chips with input example

### ISSUE THREAD

**Issue by dalemanthei** [angular/components#11206]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

User can forward tab out of a chip list with input.

#### What is the current behavior?

If you focus a chip-list with input in chrome, you can continue tabbing to the next components on the page.

On Firefox, once you tab into the chip-list, pressing tab move between the chips and the input.

#### What are the steps to reproduce?

1. Go to chips overview at https://material.angular.io/components/chips/overview
2. Scroll to the `Chips with input` example.
3. Click the input to focus and press tab.

Focus will go to the Lemon chip. Pressing tab repeatedly switches focus between the first chip and the input.

If the chip list is empty, the tab key will focus the next item on the page.

Chrome does not have this problem.

#### What is the use-case or motivation for changing an existing behavior?

Keyboard navigation accessibility 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I assume the demo site is at 6.0.0 per page header so I think all latest. The same problem exists on `5.2.4` as well.

#### Is there anything else we should know?

This issue appears to have been fixed at one time under #4605 a long time ago but appears to have returned.

**Comment by CurtisDS** [comment]
hmmm... so, if you add tabindex to the input tag. And also add tabindex to another tag below the chip list... it lets you escape.

https://stackblitz.com/edit/angular-matchiplist-tab-escape?file=app/chips-input-example.html

Not sure about the full ramifications of doing that in a bigger project, but it works for this example.

**Comment by crisbeto** [comment]
I wasn't able to reproduce it. Closing the issue, assuming that it has been resolved, given that there hasn't been any activity in a while.
