### ISSUE TITLE
virtual-scroll: re-examine how trackBy works

### ISSUE THREAD

**Issue by mmalerba** [angular/components#11274]
It seems like since we're recycling items anyways, maybe the default trackBy should just be rendered index? That would result in less detaches and attaches. We should give it a try and see if it helps improve performance

**Comment by amcdnl** [comment]
Track by seems to be working fine for me.

**Comment by mmalerba** [comment]
This has been out for a while and I haven't seen any reports of performance issues related to `trackBy`, therefore closing
