### ISSUE TITLE
Tree with checkboxes

### ISSUE THREAD

**Issue by mateuszroszczyk** [angular/components#11281]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Check state of a node should corelate with its children check states.

#### What is the current behavior?
There is a case where parent node is checked while all of his children are unchecked.

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/angular/rookgvjqrqv?file=app%2Ftree-checklist-example.ts
1. Tick 'Reminders'.
2. Untick 'Cook dinner'.
3. Click on Reminders' checkbox again.

Now 'Reminders' is checked but its children are not.

#### Is there anything else we should know?
I've found out that even though the nodes are being rendered with invalid check state, their states inside SelectionModel are actually correct.

**Comment by 513205785Xie** [comment]
The reason I found this problem is that the isSelected method of SelectionModel does not occasionally return the correct value when clicking on the parent node.I get the state of the parent node by getting the className of the parent node's selected state, and then the problem is solved.

**Comment by mateuszroszczyk** [comment]
The issue no longer exists.
I don't know when it was fixed exactly but it doesn't occur in examples for v7.3.7.
