### ISSUE TITLE
Sticky Header Mat Sort Bug on scroll

### ISSUE THREAD

**Issue by Necromancerx** [angular/components#11301]
#### What is the expected behavior?
Sort should be working on sticky header after scrolling

#### What is the current behavior?
Sort is not working on sticky header after scrolling

#### What are the steps to reproduce?
1. Click sort on any column header 
2. Scroll table
3. Hover to header (sort is not working anymore)
https://stackblitz.com/edit/angular-1vg9gn-trp98z?file=app%2Ftable-basic-example.html

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 5.2.6
Angular Material: 5.2.2
OS: Mac OS High Sierra 10.13.4
Browser: Chrome, Safari (Sort is Not Working on Firefox)

**Comment by tinayuangao** [comment]
@Necromancerx You should add `.sort` to your data source. Sort is not working on your table even before scrolling.

Here's a working example: https://stackblitz.com/edit/angular-1vg9gn-5ve3hj?file=app/table-basic-example.ts

**Comment by Necromancerx** [comment]
Sorry for the late reply.
@tinayuangao Sort is working on my end even before scrolling. Don't know why it's not working on Firefox.

OS: Mac OS High Sierra 10.13.4
Browser: Chrome, Safari (Not Working on Firefox)

**Comment by tatsujb** [comment]
@tinayuangao in the stackblitz you linked the table scrolls down to the bottom as you play around with different column's sort buttons, why is this happening?
