### ISSUE TITLE
[Feature] Selection CDK Directive

### ISSUE THREAD

**Issue by amcdnl** [angular/components#11309]
# Selection Directive
A directive that abstracts selection of elements like checkbox, buttons, etc into a higher order directive. This directive could abstract the item list selection component and be used in components like the tree and grid.

[Example demo](https://stackblitz.com/edit/selection)

### Features

- Selection strategies such as single, multiple, multiple ctrl click
- Handles ctrl / shift click selection
- Select all ability
- Work on checkboxes, buttons, etc
- Strategies like prevent clear selection

### API

It would have 3 different directives:

#### Selection
Parent controller directive.

##### Inputs

- Datasource: Datasource of all models to be selected
- Selections: All currently selected elements
- Track By: Track by function to identify items
- Strategy: Single, Multi, Multi Click
- Clearable: Whether the selection can be cleared or not
- Disabled: Disable selections

##### Outputs

- Selection Change: A event that would output: the item that was just clicked and the list of all selections

#### Checkbox/Item
MatCheckbox and button/div/etc bindings.

##### Inputs

- Model: The model of the item to be selected. Should handle single or array of items.
- Disabled: Whether the item selection is disabled

#### Example
```html
<div [matSelections]="datasource" (selectionsChange)="onChange($event)">
   <mat-checkbox [matSelection]="datasource">Select All</mat-checkbox>
   <mat-checkbox [matSelection]="model">Check me</mat-checkbox>
</div>
```

### Considerations

- Select all ability for items not yet loaded

**Comment by anilarya** [comment]
Replace selectionsChange to selectionChange

**Comment by amcdnl** [comment]
## Proposed API

### Markup
The component will act similar to how the `MatSort` component works. The `cdkSelectionToggle` will inject the `cdkSelection` component and subscribe to changes and update appropriately. When a `cdkSelectionToggle` selection occurs it will invoke `select(this)` on the `cdkSelection` parent and handle the selection logic there.

```html
<some-selection-control cdkSelection=”selections” (selectionChange)=”onSelectionChange($event)”>
  <some-option cdkSelectionToggle=”model” role=”option” tabindex=”-1” aria-selected=”true/false">
    Whatever
  </some-option>
</some-selection-control>
```

The `mat-selection-list` will inherently use this under the hood.

```html
<mat-selection-list> <!-- Acts like cdkSelectionState -->
  <mat-option>Whatever</mat-option> <!-- Acts like a cdkSelectionToggle -->
</>
```

### `CdkSelection` Interface
```ts
class CdkSelection<T> {
  /** List of all active selections. */
  selections: SelectionModel<T>;

  /** Source of all selections. Required for select between. */
  datasource: SelectionModel<T>;

  /**
   * Different selection strategies to apply.
   * Single: Only one item can be selected at a time.
   * Multiple: Multiple items can be selected.
   * Modifier Multiple: Multiple items can be selected using modifier keys such as ctrl or shift */
  strategy: ‘single’ | ‘multiple’ | ‘modifierMultiple’;

  /** Track by used for selection matching. */
  trackBy: (index, model) => string;

  /** Whether the selections can be cleared after selection. */
  clearable: boolean;

  /** The max number of selections that can be selected */
  maxSelections: number;

  /** Whether the control is disabled or not. */
  disabled: boolean;

  /** Event fired when a selection/deselection occurs. */
  selectionChange: EventEmitter<CdkSelectionChange>;
}
```

### `CdkSelectionChange` Interface
```ts
interface CdkSelectionChange<T> {
   /** The item that was actually clicked/tapped/etc. In modifier scenario this would be the item that was last clicked.
   selection: T;

  /** All of the selections. */
  selections: T[];

  /** The action that was taken on the selection items */
  type: ‘selected’ | ‘deselected’;
}
```

### `CdkSelectionOption` Interface
```ts
interface CdkSelectionOption<T> {
  /** The model to be bound to the selection. */
  model: T;

  /** Whether the selection is disabled or not. */
  disabled: boolean;
}
```

**Comment by amcdnl** [comment]
A few API changes but here is a first cut demo - https://stackblitz.com/edit/cdk-selection

**Comment by jelbourn** [comment]
cc @crisbeto you might be interested in this

**Comment by crisbeto** [comment]
I think we discussed this one a while ago on Slack. I'm not sure how much of the boilerplate we'll be able to reduce, compared to just using `SelectionModel` directly, by doing this since we still need to proxy a bunch of calls to the underlying model.

**Comment by amcdnl** [comment]
@crisbeto - Think of this as directive bindings for the selection model class.

**Comment by IlCallo** [comment]
Really interesting feature, expecially given the fact that MatCheckbox `change` event does not expose the original click event which holds information about ctl, shift etc being pressed or not.
