### ISSUE TITLE
CDK  displayed as material in "ng update" dialog

### ISSUE THREAD

**Issue by georgiee** [angular/components#11316]
#### Bug, feature request, or proposal:
Display bug with `ng update`

#### What is the expected behavior?
When using `@angular/cdk` I expect no material related update messages when running `ng update`. 

#### What is the current behavior?
I run `ng update` and get the following message. In addition when running ng update `@angular/material` (as mistakenly proposed)  I get of course the message *Package not installed: "@angular/material". Skipping.*
```
We analyzed your package.json, there are some packages to update:

Name                               Version                  Command to update
--------------------------------------------------------------------------------
@angular/material                  5.2.4 -> 6.0.1           ng update @angular/material	
```

#### What are the steps to reproduce?
To reproduce run `ng update` in a CDK-only project.

#### What is the use-case or motivation for changing an existing behavior?
I deliberately chose CDK over Material. This display error suggests it is pulling in Material again. But it's only a wrong message leading to errors when following.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I just tested an upgrade to Angular 6 and run into this issue.

#### Is there anything else we should know?
Seems to be caused by this:
https://github.com/angular/material2/blob/e6f306225e3ac4b18073a8342dfbc12822a2af28/src/cdk/package.json#L32-L38

As stated by the devkit
> A list of npm packages that are to be grouped together. When running the update schematic it will automatically include all packages as part of the packageGroup in the update (if the user also installed 

it will use the first packageName in the list for the `ng update` dialog. Maybe it's easy as providing a packageName value for ng-update?

```
 "ng-update": { 
   "packageGroupName":"@angular/cdk" 
   "packageGroup": [ 
     "@angular/material", 
     "@angular/cdk", 
     "@angular/material-moment-adapter" 
   ] 
 }, 
```

Thanks.

**Comment by jelbourn** [comment]
I think this is obsolete; currently cdk and material have their own schematics.
