### ISSUE TITLE
Slider Handler disappears on Safari while input value

### ISSUE THREAD

**Issue by frmtlp** [angular/components#11367]
**Bug, feature request, or proposal:**
Bug, just in Safari

**What is the expected behavior?**
Display the handler in a correct way

**What is the current behavior?**
Just appears on input of a value, the handler disappears for a short time

**What are the steps to reproduce?**
https://stackblitz.com/edit/angular-tkusmk-nrugj8
Make the window smaller, about 600px width and hit increase faster
the handler disappears

![bug](https://user-images.githubusercontent.com/39339830/40128767-c006d7d2-5932-11e8-9eed-e2796ad6fab4.gif)

**What is the use-case or motivation for changing an existing behavior?**

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
MacOS 10.13, iOS 11.3
Safari

"@angular/core": "^6.0.0", "@angular/cli": "~6.0.1", "@angular/material": "^6.0.2", "@angular/cdk": "^6.0.2"

**Comment by matulkum** [comment]
Hey, any update not this? What does the *P3* Label mean, btw ;)

**Comment by cbaueratwork** [comment]
Confirmed that this is still happening as of 12.0.4

https://stackblitz.com/edit/angular-gsvc4t
