### ISSUE TITLE
[FR] Make sliders printable

### ISSUE THREAD

**Issue by tmburnell** [angular/components#11364]
#### Bug, feature request, or proposal:
I am not going to call this a Bug, but a feature request. 
Can we find a way to make sliders printable? 

#### What is the expected behavior?
I would like to be able to see both the line and the selector.

#### What is the current behavior?
Using the base slider example:

- Unchanged it will only print the circle selector with no line.
- Changed will print nothing (neither the line or the selector)

My assumption is this is due to background colors do not print.  
One possible fix is use box-shadow (because i believe these are printable) 

#### What are the steps to reproduce?
https://mndnjgqbrvd.angular.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?
I have documentation pages where the slider is a completion level.  
So it would be nice to be able to print the page. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by mmalerba** [comment]
This would be nice to have but I don't think the core team will have time to work on it. It might be a good fix for someone to contribute

**Comment by felhag** [comment]
@crisbeto I guess this issue can be closed as well since pr #22300 is merged.
