### ISSUE TITLE
MatInput small placeholder text blurry on Edge

### ISSUE THREAD

**Issue by jspieker** [angular/components#11378]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After one enters text into a MatInput, the placeholder resizes and moves above the input field. The placeholder text should be clear and legible.

#### What is the current behavior?
The small placeholder has blurry text while the ErrorState is clear and legible. See the following example:

![unbenannt](https://user-images.githubusercontent.com/12713821/40162408-3769b656-59b4-11e8-94a0-2e958bb4960b.png)

#### What are the steps to reproduce?
Visit [the Material Docs](https://material.angular.io/components/input/examples) on Microsoft Edge and enter text in an input field.

#### What is the use-case or motivation for changing an existing behavior?
For accessibility reasons the text should be legible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.3 & 6.0.0
Material: 5.1.1. & 6.0.0
OS: Windows 10
TypeScript: 2.6.2
Browser: Most recent Microsoft Edge

**Comment by mandree95** [comment]
I just got this issue in a project right now. Any idea how to fix this?

**Comment by mandree95** [comment]
@jspieker @mmalerba

**Comment by mmalerba** [comment]
@jspieker @mandree95 can either of you confirm if it happens with just the legacy appearance or the standard one as well? you can see both appearances here: https://stackblitz.com/edit/angular-djd1j4?file=src/app/input-errors-example.ts

**Comment by mandree95** [comment]
@mmalerba @jspieker This only happens with the legacy appearance (the first MatInput)
![image](https://user-images.githubusercontent.com/35333559/84592451-1b77c800-ae46-11ea-9bb9-d43a43a90107.png)
Microsoft Edge 44.18362.449.0

**Comment by mmalerba** [comment]
We intend to remove the legacy appearance anyways, it was only intended as a temporary thing to allow people some time to move to the new appearances.
