### ISSUE TITLE
Custom theme breaks after upgrading to 5.2.x to 6.0.x

### ISSUE THREAD

**Issue by ezzygemini** [angular/components#11386]
#### What is the expected behavior?
A custom-built theme should be backwards compatible and show the same styles when built with versions 6.x and above. Or, new instructions on how to build new themes in 6.x should be updated in a readme file.

#### What is the current behavior?
When the dependency is updated, many of the basic styles are broken. 

##### Before:
![screen shot 2018-05-17 at 6 00 54 am](https://user-images.githubusercontent.com/639025/40179021-0315c046-5998-11e8-85ed-07888cd36f16.png)

##### After:
![screen shot 2018-05-17 at 6 01 41 am](https://user-images.githubusercontent.com/639025/40179030-098d87a6-5998-11e8-86f5-9a7095e33a1a.png)

#### What are the steps to reproduce?
Using an existing custom theme using version 5.x, upgrade the material dependency to 6.x and see the results. Many of the basic styles are broken (at least inside form components).

#### What is the use-case or motivation for changing an existing behavior?
To make styles backwards compatible or at least to notify users on how to change the implementation of using custom theming.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 6.0.1

**Comment by mmalerba** [comment]
By custom themes are you referring to https://material.angular.io/guide/theming or CSS styles targeted at Angular Material class names?

If you're referring to official theme support, I would expect that to still work. However if you're referring to CSS styles targeted at Angular Material class names, that is not something we can feasibly make backwards compatible between major releases.

**Comment by ezzygemini** [comment]
Yes, it’s following the official custom theme support. I had built a custom theme using the steps for sass, and upgrading the library breaks the native components’ look and feel. 

I didn’t even try using css classes, I simply used out-of-the box components.

**Comment by mmalerba** [comment]
@ezzygemini can you create a stackblitz showing the custom theme you created so I can look into it? It looks like something form-field related, but I can't tell without more info

**Comment by devversion** [comment]
I don't think this is an issue anymore. Please open a new issue if it's still an issue.
