### ISSUE TITLE
Request: one-sided shadows

### ISSUE THREAD

**Issue by xkxx** [angular/components#11454]
#### Bug, feature request, or proposal:

Proposal

#### What is the current behavior?

Currently, angular-material supports elevation levels through `elevation-z` classes, which adds shadow around the element. However, sometimes it's useful to have shadow only one one-side of an element.

#### What is the use-case or motivation for changing an existing behavior?

It helps in cases where we want to create components that encapsulates logic rather than presentation. For example, we currently have a component that renders both a `<nav mat-tab-nav-bar>` and the tabs underneath it, so that we only need to have the logic for computing these tabs in one component and it only needs to compute once. We also want the `<nav>` element to have shadow at the bottom, but not on the top, because the `<nav>` should belong visually with other UI elements. This is currently not possible with the `elevation-z` classes in Angular Material.

**Comment by jelbourn** [comment]
Closing since I don't think we'll do this at this stage
