### ISSUE TITLE
IE11 Table rows sticked on the top ?

### ISSUE THREAD

**Issue by kevincaradant** [angular/components#11470]
Hi  everyone
as suggested by @crisbeto, after to try your last version of Ng I still get the following issue
BTW: I don't have this issue here: https://material.angular.io/components/table/overview

#### Bug, feature request, or proposal:
Bug since Angular / Material 6.0.0

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/6093175/40234096-c007905e-5aa5-11e8-93cc-584d58658288.png)

#### What is the current behavior?
IE 11
![image](https://user-images.githubusercontent.com/6093175/40233862-e1f25ace-5aa4-11e8-9635-5d9c519cacc3.png)

chrome:
![image](https://user-images.githubusercontent.com/6093175/40234096-c007905e-5aa5-11e8-93cc-584d58658288.png)

#### What are the steps to reproduce?
In 6.0.0
https://stackblitz.com/edit/angular-material2-issue-gd2jqa?file=app%2Fapp.component.html

In 6.0.3
https://angular-material2-issue-7ugtae.stackblitz.io

I can see under IE that we have a problem of style with row:
(Text is sticked at the top of the row)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material: 6.0.3
CDK: 6.1.0
OS: Windows 7 64 bits pro
TypeScript: 2.7.2
Browser affected: IE 11

**Comment by pfeigl** [comment]
Removing `min-height: inherit;` from the mat-cell seems to fix the problem. Doesn't also have any bad influence in other browsers.

Probably this: https://github.com/philipwalton/flexbugs#flexbug-3

**Comment by gagandeepbal** [comment]
So, is this issue resolved? cause it's still happening on latest version.

**Comment by b-mi** [comment]
I solved this problem with this style for IE. Work texts with badges too.

```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  /* IE10+ CSS styles go here */
  .mat-header-row, .mat-row {
    -ms-flex-align: stretch;
  }
}
```

**Comment by jestersimpps** [comment]
please merge

**Comment by adamdport** [comment]
@b-mi works great thanks. don't forget `.mat-footer-row` if you're using it

**Comment by macjohnny** [comment]
the issue seems to be present (again) with the latest material `7.2.1`:
![image](https://user-images.githubusercontent.com/5589029/51261380-66bb4c00-19b0-11e9-8a70-af83a88359c0.png)

Somehow the changes of @crisbeto in https://github.com/angular/material2/commit/b296523276c7e6732d60d3c1bbcd3175f3bec8cd#diff-8ba7f84c84d5b5139955359c65e64b9aR75 are not present anymore: https://github.com/angular/material2/blob/master/src/lib/table/table.scss#L66

**Comment by harshadray** [comment]
> @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
>   /* IE10+ CSS styles go here */
>   .mat-header-row, .mat-row {
>     -ms-flex-align: stretch;
>   }
> }

Can we have any working sample please?

**Comment by arodr967** [comment]
Resetting min-height does the trick:
```
.mat-cell,
.mat-header-cell,
.mat-footer-cell {
  min-height: 0; // Reset min-height.
}
```

Works on IE11, Edge, Firefox (latest), Safari, and Chrome.

**Comment by nkukehenry** [comment]
In case someone gets this issue again, i fixed it using this:

```
.mat-cell {
  display: flex;
  align-items: center;
}
```
As you may know align-items will center vertically the contents of the target flex element

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
