### ISSUE TITLE
feature request for creating formdata object from mat-select directive

### ISSUE THREAD

**Issue by lucasgao** [angular/components#11514]
#### Bug, feature request, or proposal:
feature request for creating formdata object from mat-select directive

#### What is the expected behavior?
same as the native select HTML can be simply created by
new Formdata(form-contains-select)

#### What is the current behavior?
new Formdata( form-contains-mat-select) do not append the selected mat-select value

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

when submitting a form, The web services may accept the formdata object instead of JSON object.
For now it has to for loop the mat-select values and using formdata.append() each selected value.

#### Is there anything else we should know?

may create a CSS class or Attribute directive to apply the native select HTML. Like the mat-button apply to button.

**Comment by crisbeto** [comment]
Closing, because from what I can tell, there isn't a way we can do this since `mat-select` is a custom element.
