### ISSUE TITLE
Align form field variants with latest version of the spec

### ISSUE THREAD

**Issue by nicolashenry** [angular/components#11513]
#### Bug, feature request, or proposal:
Outline text field value is not centered vertically like in the specs.

#### What is the expected behavior?
[Specs](https://material.io/design/components/text-fields.html#usage) :
![image](https://user-images.githubusercontent.com/139160/40549498-e5fcb2c0-6037-11e8-8039-cbf2badda1cf.png)

#### What is the current behavior?
[In angular material examples](https://material.angular.io/components/form-field/overview) :
![image](https://user-images.githubusercontent.com/139160/40549468-cd25d9de-6037-11e8-8560-efa8dfca0ac9.png)

#### What are the steps to reproduce?
Just go to [angular material examples](https://material.angular.io/components/form-field/overview) and type some text in outlined text field.

#### What is the use-case or motivation for changing an existing behavior?
Have outlined text field aligned with the specs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.1.0

#### Is there anything else we should know?
Left padding seems too small too.

**Comment by mmalerba** [comment]
We should do a pass comparing what we have for each of the appearance modes against the spec. Our implementation is currently based on the non-final version of the spec before it was released.

**Comment by adappter** [comment]
Screenshots of misaligned outlined mat-form-field without floating label 
![screen shot 2018-07-17 at 08 01 55](https://user-images.githubusercontent.com/20188615/42799337-c91811ac-8997-11e8-818c-d8c48c40c7c8.png)
![screen shot 2018-07-17 at 08 02 03](https://user-images.githubusercontent.com/20188615/42799338-c930e3d0-8997-11e8-9de3-bb03d7ed0dc4.png)

**Comment by Nodarii** [comment]
Any chance to have this fixed soon?

**Comment by amysorto** [comment]
The MDC form field has more left padding and is vertically aligned properly.
