### ISSUE TITLE
[doc] Data table HTTP example is evil

### ISSUE THREAD

**Issue by iget-master** [angular/components#11547]
#### Bug, feature request, or proposal:

BUG

#### What is the expected behavior?

After failing, fetching HTTP results, it should try again

#### What is the current behavior?

Currently it breaks the execution.

#### What are the steps to reproduce?

Using stackblitz available on `data-table` docs: https://stackblitz.com/angular/gqydprydpbn?file=app%2Ftable-http-example.ts click quickly a few times on next page, until you get rate limited.

After it, changing the page doesn't triggers the http request anymore.

#### What is the use-case or motivation for changing an existing behavior?

The example causes users that follow it blindly to get stuck on this kind of errors.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The latest one

#### Is there anything else we should know?

No

**Comment by andrewseguin** [comment]
Just checked the source and couldn't spot any evil.

Would be happy to review and pull requests that help to improve the example.
