### ISSUE TITLE
[mat-select] infinite scroll.

### ISSUE THREAD

**Issue by amaneer94** [angular/components#11578]
feature request, or proposal:
There should be a way to detect mat-select options list is about to reach bottom so that next page data call could be made to load more options.

#### What is the expected behavior?
There should be event emitter kind of thing to detect current position of scroll (or trigger when scroll is about to reach bottom)

#### What is the current behavior?
There is no way to detect scroll position of mat-options list in mat-select.

#### What is the use-case or motivation for changing an existing behavior?
I have situation where I dont have to search among options (there is no need to use mat-autocomplete), just a set of values that should be loaded automatically when scrolls down (not all at once).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.1",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.1",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
}
![screenshot from 2018-05-30 18-10-16](https://user-images.githubusercontent.com/16270049/40722064-bb92d3d8-6434-11e8-8ceb-e495d04673cc.png)

**Comment by HaidarZ** [comment]
I've written a simple library to implement infinite scroll for mat-select component
Have a look  at [ng-mat-select-infinite-scroll](https://github.com/HaidarZ/ng-mat-select-infinite-scroll) .

**Comment by amaneer94** [comment]
Appreciated @HaidarZ , Is this compatible with angular 5, I am using:

> "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.2.0",

**Comment by HaidarZ** [comment]
I've tested it with the current version of angular v7, not sure if it's going to work with v5. Anyways, we can work on that to make it backward compatible and future proof if applicable.

**Comment by crisbeto** [comment]
Should be covered by https://github.com/angular/components/issues/10122.
