### ISSUE TITLE
Data table with selection and sort header shows up flashing checkmarks

### ISSUE THREAD

**Issue by ValentinBossi** [angular/components#11584]
#### What is the expected behavior?
no flashing checkmarks

#### What is the current behavior?
when the table contains changing data and its sorted by this data and selected respectively again unselected, the checkmark is flashing in the checkbox.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-xgbret

#### What is the use-case or motivation for changing an existing behavior?
if an other background color is used in the row as the checkmark has, the flashing checkmark causes bad user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.0, chrome

#### Is there anything else we should know?
the whole material components are amazing! very very cool work!

**Comment by avechuche** [comment]
This error I reported a few months ago, they had solved it, but I do not know if they uploaded it to the main branch
