### ISSUE TITLE
Make Overlay service tree shakable

### ISSUE THREAD

**Issue by mertdeg2** [angular/components#11581]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Overlay service is tree shakable

#### What is the current behavior?
Overlay service is NOT tree shakable

#### What is the use-case or motivation for changing an existing behavior?
This is preventing us from making our services that depend on Overlay service tree shakable.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/18944.
