### ISSUE TITLE
Unable to set focus on dropdown placed in mat-autocomplete tag. 

### ISSUE THREAD

**Issue by harjit-neo** [angular/components#11590]
#### Bug, feature request, or proposal:
If we place HTML element inside  autocomplete panel so that user can select option to get the more filtered results but when we click of down arrow key dropdown do not get focus and we unable to select the value. 
We want the functionality like https://www.airbnb.co.in/s/Edinburgh--United-Kingdom/experiences?refinement_paths%5B%5D=%2Fexperiences&place_id=ChIJIyaYpQC4h0gRJxfnfHsU8mQ&query=Edinburgh%2C%20United%20Kingdom search functionality

#### What is the expected behavior?

Focus need to be set at first element that is placed under mat-autocomplete tag

#### What is the current behavior?

Focus is not setting at element at we place under mat-autocomplete

#### What are the steps to reproduce?

`
export class MatrialAutoComponent implements OnInit {
  myControl: FormControl = new FormControl();
  options = [
    'One',
    'Two',
    'Three'
   ];
  constructor() { }
  ngOnInit() {
  }

}
`
```
<form class="example-form">
            <mat-form-field class="example-full-width">
              <input type="text" placeholder="Pick one" aria-label="Number" matInput [formControl]="myControl" [matAutocomplete]="auto">
              <mat-autocomplete #auto="matAutocomplete">
                <div>
                    <select tabindex="-1" class="form-control" id="genre">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                      </select>
                </div>
                <mat-option *ngFor="let option of options; let i = index" [value]="option">
                  {{ option }}
                </mat-option>
              </mat-autocomplete>
            </mat-form-field>
          </form>
```

When we press dropdown key to select the search result it does not set focus on "genre" select dropdown.

**Comment by crisbeto** [comment]
This isn't something we support. `mat-autocomplete` is meant primarily to contain `mat-option` and `mat-optgroup`.
