### ISSUE TITLE
[mat-tree]: Nested nodes example fails partially with large number of data (Maximum call stack size exceeded error)

### ISSUE THREAD

**Issue by bampakoa** [angular/components#11602]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The error should be caught with a friendly message and the erroneous nodes should not be rendered.

#### What is the current behavior?
When the data of the tree is greater than a large value (e.g. 200), the application throws  `RangeError: Maximum call stack size exceeded` error and all nodes up to that point are rendered with no content.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-2qc1cr?file=app/tree-nested-overview-example.ts 

1. Lower the limit to 100 or remove the `child` property.
2. The tree is rendered correctly and the error is gone.

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Angular Material: 6.2.0

#### Is there anything else we should know?
No

**Comment by djleonskennedy** [comment]
we have same issue

**Comment by bampakoa** [comment]
I attended [this](https://youtu.be/s0Vy3sLbeyA?t=4m18s) talk from **ng-conf** that suggests to use a **flat tree** for large amount of data. And it actually worked in my case. So, I am not sure if this is actually a bug or the documentation should be written properly when to use each type of tree.

**Comment by cmbkla** [comment]
Encountering this problem as well, with hundreds of `cdk-nested-tree-node`s nested in hundreds of the same. It hangs Chrome as well.

**Comment by mancej** [comment]
Also encountering this very, very frustrating issue.

**Comment by davegadsby** [comment]
We are also experiencing this problem, I can't find any official documentation about what the actual/recommended limit should be.

**Comment by hpzudo** [comment]
It's very frustrating having to refactor the whole tree to (probably) a flat tree because of this performance issue ... :(
