### ISSUE TITLE
Date Picker Reading Incorrect type in Value

### ISSUE THREAD

**Issue by michaeldev6** [angular/components#11620]
#### Bug, feature request, or proposal:
Typing into the datepicker has the value be read as 1 day less. So 2018-05-31 will be converted to 2018-05-30. 
It seems to be only with this particular format. 

#### What is the expected behavior?
That the date be the same.

#### What is the current behavior?
![date-picker](https://user-images.githubusercontent.com/26576302/40858395-2a9c5682-65ac-11e8-8b94-7623fef5f573.gif)

#### What are the steps to reproduce?
go to the example site and type in 2018-05-31 into the "Datepicker selected value" section. https://material.angular.io/components/datepicker/examples

#### What is the use-case or motivation for changing an existing behavior?
So that what is typed in is the actual value

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Existing one.

**Comment by mmalerba** [comment]
The `NativeDateAdapter` only supports dates in `mm/dd/yyyy` format due to the limitations of JavaScript's `Date` parsing. I'd suggest using a different date adapter that supports other formats (e.g. https://www.npmjs.com/package/@angular/material-moment-adapter)
