### ISSUE TITLE
Menu sub-options do not show up when used on a table

### ISSUE THREAD

**Issue by nuno-mrks** [angular/components#11645]
#### Bug, feature request, or proposal:
Sub-menu options (inside a table row) are not displayed on some scenarios.
For more specific details, please check the referred StackBlitz below: if the `<br>` are commented, the sub-menu options of any random row are displayed as intended, but when the `<br>` are uncommented, only the last row of the table displays them. For any other row, they are not displayed (as a matter of fact, I don't think they are even generated on the `cdk-overlay-container` element).

#### What is the expected behavior?
Menu sub-options should be displayed in any scenario.

#### What is the current behavior?
On some scenarios, the mat-menu submenu would not trigger, as intended.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-vqiopr-u9zdyk
(Comment and uncomment the `<br>` at the beginning of `table-basic-template.html` to test both scenarios)

#### What is the use-case or motivation for changing an existing behavior?
--

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.1.0 (both Angular and Angular-Material)

#### Is there anything else we should know?
I made this StackBlitz in order to figure out why my mat-menu options (when used on table rows) would grow out of the browsers window height (for some reasone, it's still happening to me on version 6.1.0 of Angular Material), and ended up finding this other scenario.

**Comment by andrewseguin** [comment]
Um, yup - that's weird. Good catch on finding this issue. Will need some investigation to see what is going on.

**Comment by crisbeto** [comment]
Just gave it a quick try. It looks like https://github.com/angular/material2/pull/11628 will go a ways towards fixing it, but it won't sort it out completely. Once it gets in, the menu position will work correctly, but some of the bottom menu items won't be visible.

**Comment by andrewseguin** [comment]
This seems to have been fixed by #11628
