### ISSUE TITLE
mat-datepicker-toggle too big when used with filled mat-form-field, inconsistent between browsers

### ISSUE THREAD

**Issue by sir-boformer** [angular/components#11663]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A mat-form-field (appearance=fill) with a mat-datepicker-toggle should have the same height as a regular form field. Generally, the icon seems to be too big.

#### What is the current behavior?
Firefox:
![grafik](https://user-images.githubusercontent.com/22688477/40947436-f857a8fc-6862-11e8-9fe0-81788867d47c.png)

Edge:
![grafik](https://user-images.githubusercontent.com/22688477/40947498-43da51c6-6863-11e8-8284-6e77ee476df6.png)

Chrome (still few pixels larger):
![grafik](https://user-images.githubusercontent.com/22688477/40947506-54e70f5e-6863-11e8-9fd7-25bb14668354.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ixzgdt?file=app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.2.0
Angular 6.0.3
Windows 10
tested in Chrome, Firefox, Edge

**Comment by CDDelta** [comment]
Related #11449

**Comment by Polyterative** [comment]
Happened to me too
Here is my context

my library, HTML
```HTML
<mat-form-field fxFlex
>
    [...]

    <ng-container *ngIf='(type===types.DATE)'> // true 
        <input matInput
               [formControl]='control'
               [matDatepicker]='picker'
        >
        <mat-datepicker-toggle matSuffix
                               [for]='picker'
        >
            <!--<mat-icon matDatepickerToggleIcon>keyboard_arrow_down</mat-icon>-->
        </mat-datepicker-toggle>
        <mat-datepicker #picker></mat-datepicker>
    </ng-container>
    
    [...]

</mat-form-field>
```

Since `<mat-datepicker-toggle>` uses `width: 1em;` from this CSS class group 
```
.mat-form-field-appearance-legacy .mat-form-field-prefix .mat-datepicker-toggle-default-icon, .mat-form-field-appearance-legacy .mat-form-field-suffix .mat-datepicker-toggle-default-icon
```

the class 'transcludes' only when `<mat-datepicker-toggle>` is a direct child of `<mat-form-field>`


I don't even know if this is possible at this point. The result is, I can't use a datepicker in a library with a `ngIf` because the style breaks.


___
![Source](https://i.imgur.com/P86Cjlz.png)

**Comment by Polyterative** [comment]
"""Solved"""" for now by deleting the middle-ngIf in my HTML...

```html
<mat-form-field fxFlex
                *ngIf='(type===types.DATE)'
>
    <input matInput
           [formControl]='control'
           [matDatepicker]='picker'
           [placeholder]='placeholder'
    >
    <mat-datepicker-toggle matSuffix
                           [for]='picker'
                           style='width: 1em'
    >
        <!--<mat-icon matDatepickerToggleIcon>keyboard_arrow_down</mat-icon>-->
    </mat-datepicker-toggle>
    <mat-datepicker #picker></mat-datepicker>
</mat-form-field>

```

**Comment by MotassemJa** [comment]
@Polyterative I don't have any ngIf in my code and still got the problem. Any other idea how to fix this?

**Comment by Polyterative** [comment]
Check the rendering order of the inner/outer layers. Check if it's linear with no skips from inner to outer

**Comment by buurtteam** [comment]
I have the same problem. I have set for the class .mat-form-field-flex{  align-items: unset !important }
now the problem is solved in FireFox, but the other fields, then icon is not centered. I think i should apply this only to the mat-datepicker form field and not to all the mat-form-field-flex.

**Comment by awhitehouseWS** [comment]
any update on this? appears way off on firefox

**Comment by mmalerba** [comment]
The toggle is bigger in the standard, outline, and fill variants than the legacy one - that is intentional. Legacy appearance should be avoided, it will be removed eventually.

The element with `matSuffix` also needs to be directly inside of the `<mat-form-field>` to be content projected correctly. Wrapping it in an extra `<ng-container>` will break it

**Comment by mmalerba** [comment]
I've file an issue on angular/angular about the confusing behavior when using `ng-container` https://github.com/angular/angular/issues/37328
