### ISSUE TITLE
mat-form-field look taller

### ISSUE THREAD

**Issue by seekr** [angular/components#11675]
#### Bug, feature request, or proposal:

Bug: mat-form-field look taller (and larger fonts/icon) between a vanilla deployment and what is shown on material.angular.io

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/2786460/40982932-dcaea3e2-68b4-11e8-9b11-a10174150aab.png)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome, Angular 6

**Comment by mmalerba** [comment]
I don't think this is an issue with the component, some things that could possibly explain the difference are:
- Different typography theme settings being used in your app vs the material.angular.io website
- Different version of @angular/material installed on your app vs the material.angular.io website

**Comment by Totati** [comment]
This could be caused by usage of `.mat-typography` class. It messes up quite a lot of things.
