### ISSUE TITLE
Menu slows down rendering of the view with a reactive form on mobile

### ISSUE THREAD

**Issue by PVermeer** [angular/components#11747]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
Menu component should not (continuously) interfere with the rendering of a page.

#### What is the current behavior?
Opening and closing a menu on a page with a mildly sized reactive form slows down the rendering of that page until the the routing is changed or the app is refreshed. This is not noticeable/existent in a desktop browser but extremely noticeable on a (android) browser when scrolling after the menu is used. If the menu is not used the page runs smoothly.

#### What are the steps to reproduce?
[StackBlitz app](https://angular-menu-bug.stackblitz.io)

[StackBlitz with code](https://stackblitz.com/edit/angular-menu-bug?file=src%2Fapp%2F_modules%2Fcontent%2Fcontent-management%2Fcontent-management.component.ts)

- Open on a mobile device (tested in multiple browsers).
- Scroll: all is fine.
- Use menu on the top right: view becomes laggy and this does not go away.
- Refresh app and use the dialog button (laggy because of the 200 items): after closing page is smooth.

I've recreated the necessary parts of my app with current structure to debug the issue but could not find a solution. The form in the StackBlitz is not the actual form that I use but I've created a form with 200 controls to demonstrate the issue. My form has a lot less controls but reacts about the same.
The number of items can be changed in the mockApi.ts file.

I've added a ChangeDetectionStrategy.OnPush to no avail.

#### What is the use-case or motivation for changing an existing behavior?
I don't think this is expected behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I've had this since the latest version of Angular v5 with the latest Material2 for it. I hoped this went away with v6. Now using Angular v6.0.4.

Tested in the android Chrome, Firefox and edge browsers.

#### Is there anything else we should know?
I hope this is the correct place for this issue.

**Comment by PVermeer** [comment]
After some more testing yesterday its seems that when I use a fixed toolbar on the top of the page this issue occurs. I've tried several different ways to a fix a toolbar and every method results in this issue.

**Comment by fetters5** [comment]
I also have the same issue with laggy menu and fixed toolbar, latest libs

**Comment by jelbourn** [comment]
Revisiting this (going back and triaging older issues), it looks like the StackBlitz has expired. Going to close for now since it may be obsolete, but feel free to file a new issue if there are still problems.
