### ISSUE TITLE
Docs site is not working sometimes

### ISSUE THREAD

**Issue by anjmao** [angular/components#11745]
#### Bug, feature request, or proposal:
Hi, I noticed what Docs Site is not working properly some times. I'm not sure if it as an issue of firebase cache or ServiceWorkers, after I terminate registered service workers it works just fine but hard refresh ctrl + F5 doesn't help.

<img width="1094" alt="material-site-404" src="https://user-images.githubusercontent.com/3028012/41230677-611a12aa-6d89-11e8-8f24-3a6c2d3579ec.png">

**Comment by amcdnl** [comment]
That looks more like service workers. Can you reproduce it consistently?

**Comment by guschnwg** [comment]
Sometimes I enter the website and a blank page appears.
If I ctrl+F5 the page it works normally.

**Comment by jotatoledo** [comment]
Same experience as @guschnwg
Sometimes not even hard refreshs work for me

**Comment by amcdnl** [comment]
Perhaps we should log a bug on angular/angular for this if you are seeing it too?

**Comment by m-henderson** [comment]
it is because of the service worker

**Comment by amcdnl** [comment]
I have made a PR to material docs site that should resolve the issue.

**Comment by m-henderson** [comment]
@amcdnl could you link to the PR?

**Comment by jotatoledo** [comment]
Any updates on this? This issue is ridiculously annoying.

**Comment by alex7egli** [comment]
+1 same issue

**Comment by crisbeto** [comment]
It looks like this has been resolved. Closing.
