### ISSUE TITLE
Opening Mat-dialog on iOS Safari causes the hidden browser 'chrome' to reappear

### ISSUE THREAD

**Issue by simeyla** [angular/components#11754]
#### Bug, feature request, or proposal:
Opening a mat-dialog on iOS Safari when the browser chrome has 'auto-hidden' causes the URL bar and bottom bars to reappear which has a very jarring feel.

#### What is the expected behavior?
The dialog should open but the browser chrome should not change unless you scroll back up the page.

#### What is the current behavior?
- Browser nav bar appears
- Browser bottom toolbar appears
- Area available to the dialog is reduced unnecesarily
- Bad and jarring user experience
- The opening dialog animation competes with the browser resizing the viewport.
- If you initiated the dialog by clicking on a button then that button jumps down the screen because it is pushed by the browser's top navbar.

#### What are the steps to reproduce?
No stackblitz provided. It's a pretty simple concept to understand. 
The change occurs in Safari due to the combination of css properties applied.

#### What is the use-case or motivation for changing an existing behavior?
Bad user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material latest. iOS Safari. Android Chrome browser is not affected.

#### Is there anything else we should know?
This only occurs if the browser chrome has been hidden after scrolling down the page. If you initiate the dialog when the browser chrome hasn't auto-hidden then behavior is fine.

**Comment by simeyla** [comment]
Looks like this can be solved by disabling the scroll strategy (which prevents the 'offending' class being added to `html`).

    // Get reference to Overlay in the component/service that triggers the dialog
    constructor(private overlay: Overlay ....)  

    // when you open the dialog
    dialog.open(MyComponent, { ...,             
                                                    scrollStrategy: this.overlay.scrollStrategies.noop()
                                                  });

**Comment by crisbeto** [comment]
As far as I can tell, this happens because the page detects that it has been "scrolled to the top" once we block scrolling. I don't think we can do much about it while keeping scroll blocking turned on, because it is controlled at the OS level. As mentioned above, it can be worked around by disabling scroll blocking.
