### ISSUE TITLE
IE/Edge performance (recalculate style)

### ISSUE THREAD

**Issue by ghost** [angular/components#11758]
#### Bug:
When I use mat-form-field IE / Edge starts to recalculate styles for many elements.

I checked the cause of the problems. Everything points to the selector ~ in css.

This is 
[https://drive.google.com/file/d/1vuI5KHv-HEpRXWpLznTz33pAuIV5tdJb/view?usp=sharing](url)

This is the profiling session at [https://material.angular.io/components/input/examples](url) - just click / move the mouse over an element.

When I removed the following style, the material on IE significantly accelerated.

```
.mat-form-field-appearance-fill:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-underline .mat-form-field-ripple {
    opacity: 1;
    transform: none;
    transition: opacity .6s cubic-bezier(.25, .8, .25, 1)
}

.mat-form-field-appearance-fill._mat-animation-noopable:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-underline .mat-form-field-ripple {
    transition: none
}

mat-form-field-appearance-outline:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-outline {
    opacity: 0;
    transition: opacity .6s cubic-bezier(.25, .8, .25, 1)
}

.mat-form-field-appearance-outline:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-outline-thick {
    opacity: 1
}

.mat-form-field-appearance-outline._mat-animation-noopable:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-outline {
    transition: none
}

.mat-form-field-appearance-standard:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-underline .mat-form-field-ripple {
    opacity: 1;
    transform: none;
    transition: opacity .6s cubic-bezier(.25, .8, .25, 1)
}

.mat-form-field-appearance-standard._mat-animation-noopable:not(.mat-form-field-disabled) .mat-form-field-flex:hover~.mat-form-field-underline .mat-form-field-ripple {
    transition: none
}
```

#### What is the expected behavior?
No style calculation for all elements on the page

#### What is the current behavior?
Recalculate all styles

#### What are the steps to reproduce?
[https://material.angular.io/components/input/examples](url)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.0.4
Material: 6.2.1
IE 11

**Comment by mmalerba** [comment]
It should be fairly easy to apply a class to the host element when `.mat-form-field-flex` is hovered and use that to do the styling instead of `~`. Would anyone like to take a stab at a PR?

**Comment by KamilGammert** [comment]
This is not possible, the only solution is to overwrite styles for mat-form-field-flex (remove instances ~ in css) or delete this class and replace it (on each mat-form-field).
IE / Edge will recalculate styles even if you don't mouse over the mat-form-field, just move it somewhere on the page (even on the body element).

This should definitely be changed inside the material.

**Comment by mmalerba** [comment]
@KamilGammert That's what I'm saying, that it should be easy to change inside Angular Material. If you would like to send a PR changing from `:hover ~` to a CSS class based approach I would be happy to review and merge it

**Comment by macjohnny** [comment]
with the current [master](https://github.com/angular/material2/commit/e739e61bc3a3d40e469ebabd2315711904d967c1) removing the [styles](https://github.com/angular/material2/issues/11758#issue-331451350) does not help anymore. it seems that there are more css rules that cause a repaint. see also https://github.com/angular/material2/issues/8606

**Comment by crisbeto** [comment]
Closing since this is referring to the legacy components and we no longer support IE.
