### ISSUE TITLE
Project content in matCellDef

### ISSUE THREAD

**Issue by catlabs** [angular/components#11783]
#### Bug
I have use the wrapper from the demo app to create my own table around MatTable (https://github.com/angular/material2/tree/master/src/demo-app/table/custom-table)

I would like to create a simple syntax for the end user where they can define the content of the cell  in the template, it will look like this

```
<wrapper-table [dataSource]="wrapperTableDataSource" [columns]="columnsToDisplay">
    <simple-column name="name">
      <td mat-cell *matCellDef="let data"> 
        {{data.name}} 
        <button mat-raised-button color="primary">Action</button>		
      </td>
    </simple-column>
</wrapper-table>
```
This doesn't work, I guess it is because of ng-content so what I tried is to get the MatCellDef from the transclusion and then associate it to the MatColumnDef

#### What is the current behavior?
I get this error:
ERROR
Error: StaticInjectorError(AppModule)[MatHeaderCell -> CdkColumnDef]: 
StaticInjectorError(Platform: core)[MatHeaderCell -> CdkColumnDef]: 
NullInjectorError: No provider for CdkColumnDef!

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/transclusion-columndef<br/>

**Comment by andrewseguin** [comment]
We now support a simple column - you can check out its code to see how it was accomplished

https://github.com/angular/components/blob/master/src/cdk/table/text-column.ts
