### ISSUE TITLE
Tabs emit the (selectedTabChange) in CD cycle

### ISSUE THREAD

**Issue by achervatiuk-softheme** [angular/components#11822]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
Event (selectedTabChange) should be emitted when content has been already attached, using animation callback, not in change detection cycle?

#### What is the current behavior?
Event (selectedTabChange) is emitted in change detection cycle, so we can not use it to change templates.
And there is no event before the dynamic content of the selected tab is attached, so we can not select the new tab with the context, we need (fetch server data, etc).

#### What is the use-case or motivation for changing an existing behavior?
Make our life better pls)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.2.1

**Comment by devversion** [comment]
Hello! We landed a change in August 2018 that deferred the event so that it runs a tick after the content has been checked. That might have improved the situation.

Please let us know if this still an issue. We are happy to look into it. Thanks!
