### ISSUE TITLE
mat-icon-button hover area bug

### ISSUE THREAD

**Issue by nicholasfoden** [angular/components#11826]
#### Bug:
when using mat-icon button, the area which triggers the button extends beyond the element.
![one](https://user-images.githubusercontent.com/23345512/41544787-833ae6b0-7311-11e8-9701-fd8d4de9d950.PNG)
![two](https://user-images.githubusercontent.com/23345512/41544812-8e20d954-7311-11e8-9cbe-ba8d6935e915.png)

#### What is the expected behavior?
the hover area is contained within the element.

#### What is the current behaviour?
the area extends beyond the element, possibly related to the text within the element which is replaced inside <mat-icon>

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://stackblitz.com/edit/angular-material2-issue-1ydtyw?file=app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome 66 & maybe others...

#### Is there anything else we should know?

setting `overflow: hidden` on mat-icon-button rectifies the issue

**Comment by josephperrott** [comment]
Note: It looks like this doesn't happen with all icons.  For instance, in the repro if you replace `add_box_outline` with `add` it works as expected.

**Comment by nicholasfoden** [comment]
It seems to only be an issue on outlined 
e.g. `add_outline` has the issue, where `add` does not
