### ISSUE TITLE
Select overlay displayed in wrong place

### ISSUE THREAD

**Issue by mfilar** [angular/components#11841]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Transition of opening mat-select should be smooth and not distorted

#### What is the current behavior?
When mat-select is nested inside mat-card it is affected by _font-size_ styling applied to card. Visually it looks fine, but when a user clicks on a select an overlay is placed a few pixels below and interface looks jumpy.

#### What are the steps to reproduce?
Put mat-select inside mat-card and try open it
https://stackblitz.com/edit/angular-material2-issue-oyexyr

#### What is the use-case or motivation for changing an existing behavior?
Polishing an interface

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome, Safari (probably more of them)

#### Is there anything else we should know?
--

**Comment by crisbeto** [comment]
I wasn't able to reproduce it with the latest version. Closing.

**Comment by mfilar** [comment]
there is still a little shift on material v9.2.4...
See this https://stackblitz.com/edit/components-issue-9c7ddi?file=src%2Fstyles.scss
Compare opening the select overlay when you have selected value (like Apple) and then uncomment a line #21 in styles.scss - then the overlay text fits perfectly over the one inside the select input

**Comment by crisbeto** [comment]
I see what you mean, but unfortunately it's very difficult to guarantee that the panel will be 100% aligned with the text, especially when dealing with smaller fonts. We may also remove this behavior altogether in the future since, from what I remember, it's not in the Material design spec anymore.

**Comment by mfilar** [comment]
understood, for my use case, I can fix with this single line of style as we have a fixed font size. Thanks for your reply
