### ISSUE TITLE
Fixed height of mat-form-field even without mat-label or mat-hint 

### ISSUE THREAD

**Issue by tfalvo** [angular/components#11845]
#### Bug, feature request, or proposal:

Fixed height of mat-form-field even without mat-label or mat-hint 

#### What is the expected behavior?

Without any mat-label or mat-hint defined inside mat-form-field with appearance standard, fill or outline,
mat-form-field's height should be reduced and content should be centered.  

#### What is the current behavior?

Height of mat-form-field is not changed. Label is just hidden at the reserved place. Same thing for mat-hint.
<img width="425" alt="capture d ecran 2018-06-19 a 18 10 14" src="https://user-images.githubusercontent.com/3669131/41609885-12cfa8f8-73ec-11e8-9f41-afa37ed6862a.png">

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-urvaf8-4b9lc1<br/>

#### What is the use-case or motivation for changing an existing behavior?

New fill appearance is used by Google on new product like Google Agenda. No floating label, and height of component is reduced.

<img width="752" alt="capture d ecran 2018-06-19 a 18 03 31" src="https://user-images.githubusercontent.com/3669131/41609733-cf55c92c-73eb-11e8-8911-2e982b1dc230.png">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All

#### Is there anything else we should know?

Thanks a lot. Hope this report will help.

**Comment by crisbeto** [comment]
The issue with doing this is that if you placed a form field with a hint and one without next to each other, they wouldn't align anymore.

**Comment by julianobrasil** [comment]
Would it be too much if we had some more attributes like `nolabel` `nohint`? I kind of understand @tfalvo's fustration (I haven't have a situation like his, but this flexibility would be welcome).

**Comment by tfalvo** [comment]
Thank you for your reply! 
I understand completely the problem. 
However, as a developer, it's our responsibility to ensure the coherence of design, and so to be sure to respect same height/same appearance for each form field of the same group/page. 
What do you think about it?

But I know also that material design spec doesn't mention this "compact" appearance. But Google doesn't respect itself the spec, and use a lot of this new appearance, in addition to this, with a leading icon at the left (and not inside the box)... I like this new layout... what a pity this is not officially mentioned in spec.

<img width="493" alt="capture d ecran 2018-06-25 a 11 38 37" src="https://user-images.githubusercontent.com/3669131/41842895-5809e300-786c-11e8-876e-e917ee0f7420.png">

**Comment by CAspeling** [comment]
I concur with this, especially because the non-compact version does not fit nicely into a mat-toolbar. 

In my case I am trying to use:

```<mat-form-field appearance="outline">```

**Comment by CAspeling** [comment]
If anyone wants something like an input that is smaller (but not perfect), then see my code below. Sorry don't have time to make a demo.

```
<mat-toolbar [color]="themeService.toolBarColor" class="mat-elevation-z2">
  <mat-form-field appearance="outline" fxFlex>

    <button mat-button fxFlex>
      <input matInput placeholder="P" [matAutocomplete]="autop" [(value)]="selectedP.name"
[formControl]="pControl"
        matTooltip="Search available P">
      <mat-icon [matMenuTriggerFor]="pMenu">arrow_drop_down</mat-icon>
    </button>
    <mat-menu #pMenu="matMenu" xPosition="after">
      <ng-template matMenuContent>
        <ng-container *ngFor="let outer of nestedArray">
          <ng-container *ngFor="let inner of outer.p">
            <button mat-menu-item (focus)="true" (click)="onClick();">
              {{inner.name}}
            </button>
          </ng-container>
        </ng-container>
      </ng-template>
    </mat-menu>


    <mat-autocomplete #autop="matAutocomplete" [displayWith]="displayFn">
      <mat-option *ngFor="let item of filteredOptionsP | async" [value]="item" matTooltip="{{item}}"
        (onSelectionChange)="doSomething()">
        {{item}}
      </mat-option>
    </mat-autocomplete>

  </mat-form-field>
</mat-toolbar>
```

In the css file:
```
mat-form-field { /* Changes the input styling to just about nothing so that button styling can take over */
  font-size: 1px;
}

/* ::ng-deep .mat-form-field-appearance-outline .mat-form-field-outline {
  color: transparent !important; //remove border if needed 
} */

.mat-button { 
  padding: 0 30px; /* Changes position of dropdown icons */
}
```

With some tweaking, this allows me to still follow the Material Design Spec (https://material.io/design/navigation/search.html#usage) for a component that does not exist in the available angular material library.

**Comment by sl3dg3hamm3r** [comment]
I also support this idea. We also have separate labels (not in the input element), and in most places, no hint or error text. Therefore it takes way too much space, and it seems to be difficult or feels like a hack to overcome that.
Additionally, it might be a nice idea if the space is only taken in error-case (configuration).

**Comment by adrogon** [comment]
According to https://material.io/components/text-fields/#outlined-text-field, the height stays the same even when there's no label. This part could be improved by adding a "dense" attribute, but shrinking should not be the default behavior.

On the other hand, the vertical alignment is clearly an issue and should be fixed.

**Comment by adrogon** [comment]
Here is a quick fix applied to the global CSS:
```
.mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
  border-top-width: 0;
}
```
It might not cover all the use cases, especially with prefix/suffix icons, but I hope this helps.

**Comment by gedclack** [comment]
I think the current padding (which is 1em) in the `mat-form-field-infix` class does not follow the spec : [https://material.io/components/text-fields/#outlined-text-field](url).
Did anyone noticed it ?

**Comment by chadbr** [comment]
@adrogon fix + wrapper setting below made the input box "normal" for me...

```css
.mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
  border-top-width: 0;
}

.mat-form-field-wrapper {
  padding-bottom: 0px;
  margin-bottom: 0px;
  margin-top: 0px;
}
```

Thanks!

**Comment by jelbourn** [comment]
Related to #5227

**Comment by JamieMcI** [comment]
Using @adrogon solution, I adjusted the top of the infix slightly and have nice alignment with matPrefix and matSuffix:

```
.mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
   top: -0.2em;
}
```

**Comment by mujahid-akbar** [comment]
according to material spec https://material.io/components/text-fields both filled and outlined text field can have dense spacing, when this will be supported in angular material?

![material io_components_text-fields](https://user-images.githubusercontent.com/51745086/91022248-5482a480-e60e-11ea-835d-9b859c0cff9c.png)

**Comment by JMainol** [comment]
> Here is a quick fix applied to the global CSS:
> 
> ```css
> .mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
>   border-top-width: 0;
> }
> ```
> 
> It might not cover all the use cases, especially with prefix/suffix icons, but I hope this helps.

I worked for me but adding the prefix ::ng-deep

**Comment by jason-rowe** [comment]
Based on the comments in this thread and my own testing, I think it's important we get an update for this. It doesn't seem like it's possible to implement even a basic search field without a label and achieve symmetric vertical spacing without custom css. That seems like a major flaw in this implementation of the material design spec.

**Comment by davidecampello** [comment]
Any update on this? I think dense text fields can be very interesting

**Comment by vnovikovaa** [comment]
Please add `dense`. It will be very helpful

**Comment by AdrianSima** [comment]
The availability of a **dense** setting would save so much time and headaches.

**Comment by eminvegan** [comment]
Hello, is there any update regardig this issue?

**Comment by csisy** [comment]
Another viable use-case would be to use mat-form-field for styling an input but using the input as a text filter for a list/table.

**Comment by sonphnt** [comment]
any updates on this?

**Comment by mmalerba** [comment]
This is possible with the new MDC-based form-field. There are a few things you need to do:
1. Apply the density setting for the size form-field you want, e.g. `@include mat.form-field-density(-5);`
2. Add a `placeholder` to your `<input>`
3. Don't put a `mat-label` on your form-field, instead specify the label via `aria-label` on the `<input>`. This ensures that the placeholder will be shown

Example: https://stackblitz.com/edit/angular-u9e74t-m8y9m8?file=src%2Fapp%2Finput-form-example.html,src%2Ftheme.scss
