### ISSUE TITLE
mat-tab with ng-template matTabContent shows on top of each other on safari ios

### ISSUE THREAD

**Issue by mbarbuscio** [angular/components#11866]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-tab content shouldnt overlap with other tab content

#### What is the current behavior?
when switching between tabs, tab content is shown on top of other tab content. Only happens on iPhone Safari (note: this happens only in browser. I was able to install it as a PWA and when opening the "app" version it doenst reproduce)

#### What are the steps to reproduce?
Template: https://github.com/mbarbuscio/news-hawker/blob/master/src/app/shared/settings/settings.component.html

Issue can be seen on https://news-hawker.com . Open it on safari, tap to open the bottom drawer and move through the tabs.

#### What is the use-case or motivation for changing an existing behavior?
Clearly a bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material2 6.2.1
OS iOs 11.4
Browser Safari (mobile)

#### Is there anything else we should know?
heres a picture of the tabs on top of each other
![tabs](https://user-images.githubusercontent.com/13088755/41681393-dd44cd7a-74aa-11e8-87d2-6859b1e793a0.png)

**Comment by devversion** [comment]
Hello! sorry for us taking so long to get to that issue. I was trying a basic tab group in Safari but wasn't able to reproduce this. It might have been fixed already on our end or in Safari. Safari had a lot of these rendering quirks the last time I dealt with it, but that might be fixed now. Please resubmit an issue if you still can see this. Thanks!
