### ISSUE TITLE
Support additional colors outside primary, accent, warn

### ISSUE THREAD

**Issue by AMNY49** [angular/components#11888]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Allow additional color pallets 

#### What is the current behavior?
Only 3 color pallets

#### What is the use-case or motivation for changing an existing behavior?
Material design specifications no longer call for the use of three color states, instead offering the following recommendation 

- Primary color

- Secondary color

- Surface, background, and error colors
 
- Alternative Colors: The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Apps can use alternative colors to establish themes that distinguish different sections.

https://material.io/design/color/the-color-system.html#color-theme-creation

**Comment by gtranter** [comment]
This would be extremely valuable in applications where a brand color is used for specific components such as the main app bar but is not the primary color. When the brand color is red for example, using it as the primary theme color is problematic, since primary colored input fields look like they are in error. But a red toolbar on the other hand does not suggest an error.

**Comment by merlosy** [comment]
As regards as Material Theming, alternative colors *should* be supported: https://material.io/design/color/the-color-system.html#color-theme-creation (scroll down to alternative colors).

**Comment by tqle** [comment]
If you need to add alternative or custom colors, just add a class on the control itself in your template and override the color with what you need. If you are using brand colors or have some other color, just create re-usable sass variables and create custom css for your custom application. You can have multiple css classes on any control, just have to make sure you have the correct specificity. Remember, material ui is built upon html and css, so nothing is preventing you from adding custom inline style or css classes to a control to fit your needs. Also you are not limited by the material color system, so you can use any color you want - hex, rbga, hsla combinations...

**Comment by gtranter** [comment]
@tqle thanks for the suggestion, but I think the point of this issue is _theming_ support for additional colors as well as having the base components support additional colors. Knowing how to use CSS to implement whatever colors we want in our own components is not the problem.

**Comment by odahcam** [comment]
Possibly related: 11390

**Comment by andreElrico** [comment]
we need a success color (likely green), esp for form validations and stuff. Im fine if the material team doesnt want to use a success color design wise, but many users need a green - success color sometimes somewhere in there angular/material app. So they could implement a success color for those who need it.

**Comment by odahcam** [comment]
Sometimes we want a different thing inside our application, sometimes we need to create social media butons, in which have their own color specification, _et cetera_.

**Comment by vishnu-dev** [comment]
@smnbbrv Any updates on this?

**Comment by JanneHarju** [comment]
I figure out how I can make success color in Angular Material way. 

1. Fisrt make your own palette
2. merge it to theme
3. make corresponding mat-class
4. use color="foo"

Here is example

```
$custom-collection: (
    warning :  #FFC116,
    success :  #0a630f,
    danger:    #c00000,
    contrast: (
        warning :  #000000,
        success :  #FFFFFF,
        danger:    #FFFFFF,
    )
);

$my-app-custom: mat-palette($custom-collection, custom);
$my-app-theme: mat-light-theme($my-app-primary, $my-app-accent, $my-app-warn); // this row your should have already in your code where you select palettes for primary, accent and warn
$my-app-theme: map_merge($my-app-theme, (custom: $my-app-custom));
$custom: map-get($my-app-theme, custom);
```

Then you can use $custom in your component like this
```
background-color: mat-color($custom, success);
color: mat-color($custom, success-contrast);
```

But better solution is to make mat-success-class like this

```
.mat-success {
    background-color: mat-color($custom, success);
    color: mat-color($custom, success-contrast);
  }
```
Then you can use color directive like this

`<button mat-flat-button color="success" >Success</button>`

This works because color="foo" generates class="mat-foo" for element.

**Comment by ccarns** [comment]
@JanneHarju Thanks for that workaround.

Also if you are just wanting to overwrite styles for 1 component (in my case SlideToggle) you can do so without adding the code above. Just add the mat-{your name} to the stylesheet.

 Example for **mat-postive**:

```
.mat-slide-toggle.mat-positive.mat-checked:not(.mat-disabled) .mat-slide-toggle-thumb {
  background-color: #55cc00;
}

.mat-slide-toggle.mat-positive.mat-checked:not(.mat-disabled) .mat-slide-toggle-bar {
  background-color: white;
}
```
then use it like this:
```
<mat-slide-toggle color="positive"> Edit Multiple
      </mat-slide-toggle>
```

**Comment by notbear** [comment]
@ccarns 
The comment in _theming.scss (@angular/material@11.2.0) says:
>  // If the theme has been constructed through the legacy theming API, we use the theme object
>  // as color configuration instead of the dedicated `color` property. We do this because for
>  // backwards compatibility, we copied the color configuration from `$theme.color` to `$theme`.
>  // Hence developers could customize the colors at top-level and want to respect these changes
>  // TODO: Remove when legacy theming API is removed.

So instead of simple merge
```
$my-app-theme: map_merge($my-app-theme, (custom: $my-app-custom));
```
i had to replicate the definition under a 'color' property then use deep merge to make all stuff working properly (eg mat-get-color-config() function)
```
@use "sass:map";

$custom-collection: (
    warning :  #FFC116,
    success :  #0a630f,
    danger:    #c00000,
    contrast: (
        warning :  #000000,
        success :  #FFFFFF,
        danger:    #FFFFFF,
    )
);

$my-app-custom: mat-palette($custom-collection);
$my-app-theme: mat-light-theme($my-app-primary, $my-app-accent, $my-app-warn); // this row your should have already in your code where you select palettes for primary, accent and warn
$my-app-theme: map.deep-merge(
  $my-app-theme, 
  (
    custom: $my-app-custom,
    color: (
      custom: $my-app-custom  
    )
  )
);
$custom: map-get($my-app-theme, custom);
```

**Comment by JanneHarju** [comment]
Thank you for sharing that @notbear . Is that documented somewhere and should it be documented? I mean somewhere else than in code. For example in Angular Material documentation and in Angular Update Guide https://update.angular.io/ .

**Comment by aersosi** [comment]
I have tried the above solutions, but find them too hacky and too much of a workaround. I try a straight-forward solution by doing this:

```
:root {
  --color-passive: #{$passive};
  --color-passive-contrast: #{$passive-contrast};
  --color-success: #{$success};
  --color-success-contrast: #{$success-contrast};
  --color-danger: #{$danger};
  --color-danger-contrast: #{$danger-contrast};
}
```

```
.mat-flat-button,
.mat-raised-button,
.mat-fab,
.mat-mini-fab {
  &.mat-passive {
    background-color: var(--color-passive);
    color: var(--color-passive-contrast);
  }

  &.mat-success {
    background-color: var(--color-success);
    color: var(--color-success-contrast);
  }

  &.mat-danger {
    background-color: var(--color-danger);
    color: var(--color-danger-contrast);
  }
}
```

Now I can simply:
```
<button mat-flat-button color="passive">test</button>
<button mat-flat-button color="success">test</button>
<button mat-flat-button color="danger">test</button>
```

Works so far for most components. `<mat-badge>` was more of a workaround because `matBadgeColor` only accepts 'primary', 'accent and 'warn':

```
.badge-passive .mat-badge-content {
  background: var(--color-passive);
  color: var(--color-passive-contrast);
}
.badge-success .mat-badge-content {
  background: var(--color-success);
}
.badge-danger .mat-badge-content {
  background: var(--color-danger);
}
```

```
<span matBadge="4" class="badge-passive">Badge</span>
<span matBadge="4" class="badge-success">Badge</span>
<span matBadge="4" class="badge-danger">Badge</span>
```

What do you think about it?

**Comment by notbear** [comment]
@aersosi IMO it's perfectly fine if you don't need themes in your app and/or you accept the fact that custom palette would need a custom approach.

But if you wanted to use scss functions from Material theme module or worked on an extendable design system with consistent api, you'd probably need to define a custom palette the same way as the original ones are done.

**Comment by aersosi** [comment]
@notbear 

I'm actually using a custom theme with custom color palettes and material pallettes.
In addition to the standard color palettes, I added this:
```
$avo-status-palette: (
  passive : hsl(0, 0%, 73%),
  passive-num : #{0, 0%, 73%},
  success : hsl(125, 40%, 50%),
  success-num : #{125, 40%, 50%},
  caution: hsl(45, 100%, 55%),
  caution-num: #{45, 100%, 55%},
  contrast: (
    passive : white,
    success : white,
    caution: black,
  )
);
```
```
@use '~@avo/styles/colors' as avo_palettes;
@use 'sass:map';

$passive: map.get(avo_palettes.$avo-status-palette, passive);
$passive-num: map.get(avo_palettes.$avo-status-palette, passive-num);
$passive-contrast: map.get(avo_palettes.$avo-status-palette, contrast, passive);
$success: map.get(avo_palettes.$avo-status-palette, success);
$success-num: map.get(avo_palettes.$avo-status-palette, success-num);
$success-contrast: map.get(avo_palettes.$avo-status-palette, contrast, success);
$caution: map.get(avo_palettes.$avo-status-palette, caution);
$caution-num: map.get(avo_palettes.$avo-status-palette, caution-num);
$caution-contrast: map.get(avo_palettes.$avo-status-palette, contrast, caution);

:root {
  --color-passive: #{$passive};
  --color-passive-num: #{$passive-num};
  --color-passive-contrast: #{$passive-contrast};
  --color-success: #{$success};
  --color-success-num: #{$success-num};
  --color-success-contrast: #{$success-contrast};
  --color-caution: #{$caution};
  --color-caution-num: #{$caution-num};
  --color-caution-contrast: #{$caution-contrast};
}
```

Maybe that is not the best solution, but in this way I'm not interfering with material, I'm just extending it. With the custom palettes, I also have a single source of truth. If I'm changing `success` in my `$avo-status-palette` everything is still fine.

**Comment by RichardBoyder** [comment]
Any proper solution to this Material Designers ? OR at least an answer why it isn't standard in angular material to enable us to add more palettes?

**Comment by aersosi** [comment]
@RichardBoyder 

Just as angular is opinionated, material design is an opinionated design philosophy. There is no official statement in the documentation on material.io, but from a design point of view it is logical to leave out as many unnecessary elements as possible. Of course, many will now say that a success color is essential, but that is exactly what is debatable. Colors attract attention and distract from the essential, like the content. But an error color is essential because when things go wrong, the user really has to pay attention. A success color is rather "nice to have". 

Angular Material only takes over the requirements of material design. And because material design does not specify a success color, angular material does not have it either.

At least that's how I explain it to myself.

**Comment by ju-sys** [comment]
@aersosi 
> Just as angular is opinionated, material design is an opinionated design philosophy. There is no official statement in the documentation on material.io

Taken directly from https://material.io/design/color/the-color-system.html#color-theme-creation 

> Alternative colors
>
>The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Alternative colors can be used to distinguish different sections of a UI.

>Additional colors for data visualization
>
>Apps can use additional colors to convey categories that are outside of your main color theme. They are still a part of your full color...
>
>Apps can use additional colors to convey categories that are outside of your main color theme. They are still a part of your full color palette.

**Comment by RichardBoyder** [comment]
I do understand @aersosi  what you mean. For sure. Just wish they gave us the ability to easily add if we want.. I get they are opinionated. But in todays World of Development and design... we cannot be opinionated any more , especially if they provide material as a open source product for all to use... Often clients want specific colors... And i find it just limiting , which development and design should never ever be limiting.... 

But as you say i do understand their reasoning, i just dont like it.. Having to find a decent hack to get a success or any other color i want in is a pain... having only 3 palletes .... its bizare.

**Comment by aersosi** [comment]
@ju-sys 

By alternative colors, they mean brand-specific colors. With brand specific, I mean something like, Microsoft Word is blue, and Microsoft Excel is green. This is important to be able to distinguish products from each other in a uniform design system. But this has nothing to do with signal colors like green/yellow/red.

**Comment by aersosi** [comment]
@RichardBoyder 

I would also like to have more flexibility without hacky, bulcky code. Everybody is opinionated, especially nowadays. Just look at politics or social media, it's bonkers. We don't live in the times of enlightenment anymore.

But we can choose. Hopefully nobody forces you to use material, and if so: You probably are a developer - so develop something. In the meantime, keep on complaining until they can't stand it anymore and add optional colors.

We'll see what the implementation of Material MDC will give us. And generally it's not too bad to have a solid opinion about something if you have good reasons for.

**Comment by aersosi** [comment]
@RichardBoyder 

I figured many (but not all) components take `color='whatever'`without complaining.
So I did:

```
@use './colors';

@each $key in map-keys(colors.$custom-palette-keys) {
  .mat-flat-button,
  .mat-raised-button,
  .mat-fab,
  .mat-mini-fab {
    &.mat-#{$key} {
      background-color: map-get(colors.$custom-palette, $key);
      color: map-get(colors.$custom-palette, contrast, $key);
    }
  }
}
```

In my imported colors.scss I have:
```
$custom-palette: (
  passive : hsl(0, 0%, 73%),
  success : hsl(140 , 40%, 50%),
  whatever: hsl(45, 100%, 50%),
  contrast: (
    passive : black,
    success : white,
    whatever: black,
  )
);

$custom-palette: mat.define-palette($custom-palette);
$custom-palette-keys: map-remove($custom-palette, contrast);
```

Now you just have to add a new color and contrast color to your custom palette and after compile you can use it. Of course, you have to write the loops for each component. And I guess this solution has to be rewritten when MDC is ready.

**Comment by ju-sys** [comment]
@aersosi 

> By alternative colors, they mean brand-specific colors. With brand specific, I mean something like, Microsoft Word is blue, and Microsoft Excel is green

Which is the description of this bug ticket. I'm not seeing the argument about the opinionated design philosophy having no official statement/documentation on material.io, or the logic behind leaving out as many unnecessary elements as possible.

Material Design states clearly in the documentation that alternative and additional colors are supported which has been quoted a few times in these comments. 

There was a time when material design only supported 3 color pallets, but that was literally 5 years ago at this point.

**Comment by aersosi** [comment]
@ju-sys 

https://material.io/design/color/the-color-system.html#color-theme-creation

**Comment by schankam** [comment]
Any news about this ? It's been 3 years....

**Comment by aersosi** [comment]
> Any news about this ? It's been 3 years....

I have a solution that will go open source. I don't know when exactly, because my company needs some time to go open-source.

**Comment by AMNY49** [comment]
> @ju-sys
> 
> Let's say you have 12 T-shirts, 5 of which you really, really like. How many of these 5 will you wear today? I guess only one because you only have one torso, right?
> 
> Material has three torsos. The first one is called primary, the second one is accent and the third one is called warn. Back in the day they only had three t-shirts (like you explained) nowadays they have many more. How many of these many more shirts can they wear? Have they grown more torsos? Obviously not, but that's what everybody in this thread is asking for.
> 
> Besides that: Do you understand the difference between alternative colors and additional colors? Have you read the headline of this thread? I mean the headline saying we want "additional colors". Sorry for being so straight forward, but that's kind of obvious. At least for me it is.

At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. Stop liking your own posts lol. 

Alternative colors (not currently supported)
The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Alternative colors can be used to distinguish different sections of a UI.

Additional colors for data visualization (not currently supported)
Apps can use additional colors to convey categories that are outside of your main color theme. They are still a part of your full color palette.

Torsos
... missed this section.

**Comment by gtranter** [comment]
> > Any news about this ? It's been 3 years....
> 
> I have a solution that will go open source. I don't know when exactly, because my company needs some time to go open-source.

Please be sure to keep us posted! I can hardly wait.

**Comment by aersosi** [comment]
> > @ju-sys
> > Let's say you have 12 T-shirts, 5 of which you really, really like. How many of these 5 will you wear today? I guess only one because you only have one torso, right?
> > Material has three torsos. The first one is called primary, the second one is accent and the third one is called warn. Back in the day they only had three t-shirts (like you explained) nowadays they have many more. How many of these many more shirts can they wear? Have they grown more torsos? Obviously not, but that's what everybody in this thread is asking for.
> > Besides that: Do you understand the difference between alternative colors and additional colors? Have you read the headline of this thread? I mean the headline saying we want "additional colors". Sorry for being so straight forward, but that's kind of obvious. At least for me it is.
> 
> At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. Stop liking your own posts lol.
> 
> Alternative colors (not currently supported) The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Alternative colors can be used to distinguish different sections of a UI.
> 
> Additional colors for data visualization (not currently supported) Apps can use additional colors to convey categories that are outside of your main color theme. They are still a part of your full color palette.
> 
> Torsos ... missed this section.



Hey there, good morning and thanks for the entertaining reply. I just woke up and it already made my day! :D

Of course, you know that I can do whatever I like, so I keep liking my posts if I feel like it. But maybe you want me to like your posts too? Is that what you're about? You want people to like your posts?

The alternative colors part of tour reply:
Bla, whatever. I haven't even read that. That's 1024% opinionated.
I can't agree with you, not even when you scream and stand on your head.

It's pretty obvious that you've moved away from rational discourse and are just blowing emotional garbage onto the internet. I would advise you to talk more with your friends about your feelings. Unfortunately, I can't help you there. And I'm not particularly interested in it either.

So have a good day, I guess?
XOXO

**Comment by aersosi** [comment]
> > @ju-sys
> > Let's say you have 12 T-shirts, 5 of which you really, really like. How many of these 5 will you wear today? I guess only one because you only have one torso, right?
> > Material has three torsos. The first one is called primary, the second one is accent and the third one is called warn. Back in the day they only had three t-shirts (like you explained) nowadays they have many more. How many of these many more shirts can they wear? Have they grown more torsos? Obviously not, but that's what everybody in this thread is asking for.
> > Besides that: Do you understand the difference between alternative colors and additional colors? Have you read the headline of this thread? I mean the headline saying we want "additional colors". Sorry for being so straight forward, but that's kind of obvious. At least for me it is.
> 
> At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. Stop liking your own posts lol.
> 
> Alternative colors (not currently supported) The Material Design color system supports alternative colors, which are colors used as alternatives to your brand’s primary and secondary colors (they constitute additional colors to your theme). Alternative colors can be used to distinguish different sections of a UI.
> 
> Additional colors for data visualization (not currently supported) Apps can use additional colors to convey categories that are outside of your main color theme. They are still a part of your full color palette.
> 
> Torsos ... missed this section.

And yes you're kind of right. Now, some time later, it's also hard for me to understand the comparison I made there. 
So, what now? Should I feel bad about it?

**Comment by jelbourn** [comment]
I've deleted the last few comments and locked this issue for the time being. Please see Angular's [Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md).

**Comment by amysorto** [comment]
Closing this issue since there is now support for custom colors. Please see the [theming guide](https://material.angular.io/guide/theming) for more details.
