### ISSUE TITLE
[mat-tree]: Tree node with checkbox does not wrap its content in case it has large width

### ISSUE THREAD

**Issue by bampakoa** [angular/components#11889]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A tree node with checkbox should wrap its content accordingly.

#### What is the current behavior?
The content of the node expands over the parent container width.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-uvm4pc

* Expand the first node that is called **Reminders**
* Notice the width of its first child node.

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Angular Material: 6.3.0
OS: Windows 10 Enterprise 1803
Typescript: 2.9.1
Browsers: Chrome  67.0.3396.87, Firefox 60.0.2, Edge 42.17134.1.0

#### Is there anything else we should know?
This is not applicable in tree nodes without checkboxes

**Comment by bampakoa** [comment]
If that helps, I noticed that `white-space: nowrap;` in `mat-checkbox-layout` class is responsible for this behavior.

**Comment by zarend** [comment]
This looks like an issue with the checkbox component, and not with the tree itself.

**Comment by zarend** [comment]
Closing as a duplicate of #8416
