### ISSUE TITLE
CdkContentObserver - Universal - this._contentObserver.observe is not a function

### ISSUE THREAD

**Issue by justinappler** [angular/components#11894]
#### Bug, feature request, or proposal:
CdkContentObserver sometimes triggers an exception when the _subscribe function is called in ngAfterContentInit. I can't reproduce this locally, but I'm seeing this on my production servers quite frequently. The issue does not appear to happen on the browser, only on the server.

#### What is the expected behavior?
The _contentObserver dependency is injected and available, and observe function exists.

#### What is the current behavior?
The _contentObserver dependency is sometimes not injected.

#### What are the steps to reproduce?
It seems to only to occur when using the build/server mode (when running in Node, doesn't seem to reproduce in the browser).

Stack trace is as follows:
@angular/cdk/bundles/cdk-observers.umd.js in CdkObserveContent._subscribe at line 253:61
@angular/cdk/bundles/cdk-observers.umd.js in CdkObserveContent.ngAfterContentInit at line 232:18
@angular/core/bundles/core.umd.js in callProviderLifecycles at line 9339:18
@angular/core/bundles/core.umd.js in callElementProvidersLifecycles at line 9320:13
@angular/core/bundles/core.umd.js in callLifecycleHooksChildrenFirst at line 9310:29

#### What is the use-case or motivation for changing an existing behavior?
n/a - bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI 6.0.8, Angular 6.0.4, Angular Material/CDK 6.2.1, Node 8.9.4, TS 2.7.2

**Comment by crisbeto** [comment]
It seems like we have a server-side rendering check in the `MutationObserverFactory` which should prevent this. I'm closing it since it hasn't had any activity in a while.
