### ISSUE TITLE
bug(form-field): floating label conflicts with outline when label is dynamically set

### ISSUE THREAD

**Issue by TheCom3di4n** [angular/components#11919]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
The gap in the outline should be recalculated when the label is dynamically changed.

#### What is the current behavior?
The floating label conflicts with the outline when the label is dynamically changed.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-xwjzqp

#### What is the use-case or motivation for changing an existing behavior?
\-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
<= Angular 6.3.0

#### Is there anything else we should know?
This is a standalone issue for [this](https://github.com/angular/material2/issues/11653#issuecomment-396038914) comment.

**Comment by mmalerba** [comment]
This has been fixed, here's an updated version of the stackblitz demonstrating it: https://stackblitz.com/edit/angular-material2-issue-9lex7l?file=app%2Fapp.module.ts
