### ISSUE TITLE
mat-datepicker yearSelected/monthSelected with input min/max passes unexpected value

### ISSUE THREAD

**Issue by IgorWolbers** [angular/components#11914]
#### Bug
`mat-datepicker` - `yearSelected`/`monthSelected` with input and `min` and/or `max` passes unexpected value when selecting a date outside of the allowable range. This is in combination with the supplied example [Watching the views for changes on selected years and months][1]. 

#### Expected behavior?
When using the `min` and `max` values the calendar picker correctly "grays" out years and months before the passed in `min` value and also those after the passed in `max` value. These years in the year selection and months in the months selection show a gray value if the date is outside the bounds of the passed in `min` or `max` value. (*up until this part it works as expected*).
When the user clicks on any gray (non selectable) date the calendar should **not** change and any subscribed events including `yearSelected` and `monthSelected` should **not** fire.

#### What is the current behavior?
On the Multi-Year view the calendar changes to the month selection even when a year was selected that was outside of the enabled year range. The calendar will then display as if the closest enabled year was selected. Example: if `min` was set to `2018-01-01` and the user selects `2016` then the calendar displays that `2018` was selected.
Both the `yearSelected` and `monthSelected` still fire when a non-selectable year/month/date is selected but the value of the `$event` is the actual date normalized date selected and not the same one that the calendar now displays. So, in the previous example, the value `2016` would have been assigned to `$event`.

#### What are the steps to reproduce?

[https://stackblitz.com/edit/angular-iqo3x4](https://stackblitz.com/edit/angular-iqo3x4)

Please also fix the original [stackblitz][2] in the documentation. 

    import {DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE} from '@angular/material/core';

should be

    import {DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE} from '@angular/material';

This causes the code to fail at runtime as a javascript `date` is passed in instead of a `moment` object as the value of `$event` in the events `yearSelected` and `monthSelected`.

#### What is the use-case or motivation for changing an existing behavior?
No change, just a bug fix.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
What I am running.

	Angular CLI: 6.0.8
	Node: 10.4.1
	OS: win32 x64
	Angular: 6.0.5
	... animations, common, compiler, compiler-cli, core, forms
	... http, language-service, platform-browser
	... platform-browser-dynamic, router

	Package                            Version
	------------------------------------------------------------
	@angular-devkit/architect          0.6.8
	@angular-devkit/build-angular      0.6.8
	@angular-devkit/build-optimizer    0.6.8
	@angular-devkit/core               0.6.8
	@angular-devkit/schematics         0.6.8
	@angular/cdk                       6.3.0
	@angular/cli                       6.0.8
	@angular/material                  6.3.0
	@angular/material-moment-adapter   6.3.0
	@ngtools/webpack                   6.0.8
	@schematics/angular                0.6.8
	@schematics/update                 0.6.8
	rxjs                               6.2.1
	typescript                         2.7.2
	webpack                            4.8.3

#### Is there anything else we should know?
I can't think of anything but please let me know if there is something else I can clarify or pass along.

Thank you for all the awesomeness and work that went into angular and angular material, it is an awesome platform!

[1]:https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months
[2]:https://stackblitz.com/angular/lkppenjajev?file=app%2Fdatepicker-views-selection-example.ts

**Comment by mmalerba** [comment]
This appears to have been fixed: https://stackblitz.com/edit/angular-vmtmfr?file=src/app/datepicker-min-max-example.html
