### ISSUE TITLE
Sticky Header should render properly in Edge

### ISSUE THREAD

**Issue by jrood** [angular/components#11921]
#### Bug, feature request, or proposal:
Labels in the sticky header should render properly in Microsoft Edge.

#### What is the expected behavior?
I would expect that the sticky header would be rendered in Edge roughly the same as it is in Chrome.

#### What is the current behavior?
In Edge it looks somewhat broken and the labels are half out of the extent of the header.
<img width="1391" alt="screen shot 2018-06-25 at 10 26 47 am" src="https://user-images.githubusercontent.com/6615558/41859833-b0ec97a6-7862-11e8-9d83-05f143af45c9.png">

#### What are the steps to reproduce?
Go to [the documentation on the table component](https://material.angular.io/components/table/overview) in Edge and scroll down to the section on sticky headers.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.3.0 in Edge as it is compiled for the docs.

**Comment by JWess** [comment]
Is this a bug in the Edge browser itself? Can it be worked around?

**Comment by konrad-garus** [comment]
Still an issue with 8.1.4 and Edge 42.17134.1.0.

**Comment by tutkusilavuraleyovge** [comment]
Still an issue with Edge 44.17763.1.0.

**Comment by andrewseguin** [comment]
I expect this is no longer an issue with Edge Chromium
