### ISSUE TITLE
[Table] Possible race condition between checkbox styling and sticky offset calculation

### ISSUE THREAD

**Issue by IlCallo** [angular/components#11942]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Set selectable column as sticky and everything works fine

#### What is the current behavior?
![immaginesmile](https://user-images.githubusercontent.com/10036108/41940123-06528e54-7998-11e8-80a7-956325b7aa1e.png)

#### What are the steps to reproduce?
I made a demo trying to do so and show the use case, but I cannot reproduce it in StackBlitz
https://stackblitz.com/edit/angular-bec7xd

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0
Material 6.3.1
Browsers: Chrome and Mozilla, in Edge it seems to be fine

#### Is there anything else we should know?
The space between the select column and action columns is exactly 8px.
If I disable the `margin-right: 0` rule on `.mat-checkbox-inner-container-no-side-margin` class, the checkbox gets a 8px margin but the white space disappears.

That class is added via a binding on checkbox template.
My idea is that when some computational pressure is put on the component (some get and filtering stuff), the cell width calculation is performed **before** `.mat-checkbox-inner-container-no-side-margin` being applied, thus including the 8px margin which almost immediatelly disappear leaving the system with a wrong measurement of the select cell which influences the computation of all cells at it's right.

If I remove the actions and leave only the select column with other fields, the space is not present, possibly because it skips some lodash `map` iterations maybe?
If I sort by a column, the space disappears, I guess because the table it's forced to recompute the sticky value.
If I don't show the select column, there is no white space (aka it seems to do this only with the checkbox).
If I show two columns with checkboxes before actions columns, two whitespace of 8px each appears after those columns.
If I set `flex: 0 0 20px` instead of `flex: 0 0 auto` on the select cells, the space is not present, obviously because the getBoundingClientRect uses the predefined flex-basis instead of calculating it taking the checkbox right margin into account (currently my workaround fix to the problem).

I don't know enough about Angular to pin-point exactly the problem and unfortunately I cannot share the code.
If someone have some random ideas to try out about how I can debug further the problem, I'll be happy to listen and try your suggestions :)

Edit: when putting two columns of selects but no actions columns, only the first select column shows the whitespace, can't understand why.

**Comment by andrewseguin** [comment]
I wish we could provide some assistance but without a reproduction, we are shooting in the dark. Have you tried asking on StackOverflow?

**Comment by IlCallo** [comment]
No problem, I guess that after 2 years and no answers, the problem was related to something particular of my usage
