### ISSUE TITLE
tabs: nested mat-tab with matTabContent directive does not work

### ISSUE THREAD

**Issue by MurhafSousli** [angular/components#11941]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Nested `mat-tab` with `<ng-template matTabContent>`  to work

#### What is the current behavior?

Nested `mat-tab` with `<ng-template matTabContent>`  do not work

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-aqmcu4?file=app/app.component.html

Use `<ng-template matTabContent>` in both the outer and the inner `mat-tab` and the issue will occur

```html
<mat-tab-group>

  <mat-tab label="tab1">
    <ng-template matTabContent>
      
      <mat-tab-group>
        <mat-tab label="child tab1">
          <ng-template matTabContent>
            <p>Test Test Test Test Test Test Test Test Test Test Test Test</p>
          </ng-template>
        </mat-tab>

        <mat-tab label="child tab2">
          <ng-template matTabContent>
            <p>Test Test Test Test Test Test Test Test Test Test Test Test</p>
          </ng-template>
        </mat-tab>
      </mat-tab-group>

    </ng-template>
  </mat-tab>

  <mat-tab label="tab2">
    <ng-template matTabContent>
      <p>Test Test Test Test Test Test Test Test Test Test Test Test</p>
    </ng-template>
  </mat-tab>

  <mat-tab label="tab3">
    <ng-template matTabContent>
      <p>Test Test Test Test Test Test Test Test Test Test Test Test</p>
    </ng-template>
  </mat-tab>

</mat-tab-group>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.0.0
Material 6.3.0

#### Is there anything else we should know?

If  `<ng-template matTabContent>` is removed from the inner `mat-tab`, it works

**Comment by khalid-elabbadi** [comment]
me too can make it work. i got this:
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Unexpected closing tag "mat-tab". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
                </form>
            </div>
        [ERROR ->]</mat-tab>
    </mat-tab-group>
</div>"): ng:///UsersModule/UsersComponent.html@266:8
Unexpected closing tag "mat-tab-group". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
            </div>
        </mat-tab>
    [ERROR ->]</mat-tab-group>
</div>"): ng:///UsersModule/UsersComponent.html@267:4
Error: Template parse errors:
Unexpected closing tag "mat-tab". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
                </form>
            </div>
        [ERROR ->]</mat-tab>

**Comment by EBMike** [comment]
@robertmazzo nesting a mat-tab-group inside a mat-tab still breaks it.... using your example, but updating the dynamic tabs with this will break
```
<mat-tab label="Dynamic Preferences">
	<ng-template matTabContent>
		<mat-tab-group>
			<!-- <mat-tab *ngFor="let tab of asyncTabs | async"> -->
			<mat-tab *ngFor="let tab of prefTabs" label="{{tab.label}}">
      <ng-template matTabContent>
				  {{tab.content}}
      </ng-template>
			</mat-tab>
		</mat-tab-group>
	</ng-template>
</mat-tab>
```

**Comment by VenkateshVoona** [comment]
how to customize mat-label ? I tried like below snippet but didn't work 

`<mat-tab-group mat-stretch-tabs>
    <ng-template mat-tab-label>
       Tab 1
      </ng-template>
</mat-tab-group>`

**Comment by AsimKarel** [comment]
Is there any update on this?
I am also facing the same issue.
**matTabContent** not working in nested tabs

**Comment by VishalCodingNinja** [comment]
Any Update.. Please help ...
![image](https://user-images.githubusercontent.com/37198555/89731005-4d319780-da61-11ea-885a-0a0b04cb6d4d.png)

**Comment by Splaktar** [comment]
From the [tabs platement docs](https://material.io/components/tabs#placement):

> **Caution** Avoid nesting a tab within another tab.

**Comment by Splaktar** [comment]
This appears to be working with 11.0.3: [demo](https://stackblitz.com/edit/nested-mat-tabs-with-mat-content?file=app/app.component.html)
