### ISSUE TITLE
[Table] Add conditionally displayed rows with custom structure

### ISSUE THREAD

**Issue by IlCallo** [angular/components#11978]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
It would be nice to be able to add rows with a custom structure which could be among other rows given a condition based on rows generated by the data source or metadata (before first row, after last row, before every row with a given property).

#### What is the current behavior?
You can add header rows and footer rows and work with that, but the interface it's not really user friendly and pretty limited (or poorly documented).
Also, it seems there is no build-in way to show/hide header-footer rows based on some variable: you can filter out rows generated by datasource, but cannot dynamically *ngIf header or footer rows (which seems evaluated only at render time but I may be very wrong on this, I recall reading about an `renderRows()` method somewhere).

#### What is the use-case or motivation for changing an existing behavior?
Rows with given condition: add an expandable panel only to items with a certain property.
Rows with given condition: show titles/dividers for groups of homogeneous rows.
Rows placed after last item: show spinner when implementing endless scrolling pagination technique.

**Comment by shusson** [comment]
+1 
We would like to conditionally show a row with a progress bar when the table is loading data and it's unclear from the docs how/if this is possible.

**Comment by andrewseguin** [comment]
You can use the row's `when` predicate as a function of whether a particular row template should be rendered.
