### ISSUE TITLE
Installing Angular Material and Angular CDK (v. 5.2.4) is not working properly 

### ISSUE THREAD

**Issue by szEvEz** [angular/components#12001]
#### Bug, feature request, or proposal:

The installation of Angular material as suggested in (https://v5.material.angular.io/guide/getting-started) via `npm install --save @angular/material @angular/cdk` installs version 6.3.1 of @angular/cdk and @angular/material which is not working with the following installed version of Angular, Angular CLI and Node:

Angular CLI: 1.7.4
Node: 6.11.0
OS: win32 x64
Angular: 5.2.11

#### What is the expected behavior?

The [installation guide](https://v5.material.angular.io/guide/getting-started) should have the right command to install the proper material version.

#### What is the current behavior?

A version is installed which breaks the app.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 1.7.4
Node: 6.11.0
OS: win32 x64
Angular: 5.2.11

**Comment by hakimio** [comment]
Angular Material 6 requires Angular 6.

**Comment by szEvEz** [comment]
@hakimio I am pretty aware of that fact. But if you're executing the steps given by the [guide](https://v5.material.angular.io/guide/getting-started) for version 5  - it is installing the wrong version and therefore breaks the application.

**Comment by hakimio** [comment]
@szEvEz Ok, I see the issue with the documentation now. You are right.

**Comment by freelancersunil** [comment]
@angular/material@6.3.1 requires a peer of @angular/cdk@6.3.1 but none is installed. You must install peer dependencies yourself.

anyone, is this the same issue? cannot proceed now?

**Comment by hakimio** [comment]
@freelancersunil No, that's different. You can proceed by manually installing "@angular/cdk".

**Comment by jelbourn** [comment]
I agree it would be good if the v5 site specified the version. FYI, in case you weren't aware, you want to specify the version in your `npm install` command:
```sh
npm i @angular/material@5 @angular/cdk@5
```

**Comment by ArqamRafay** [comment]
> Angular Material 6 requires Angular 6.

Thanks
