### ISSUE TITLE
[Mat Action Row] Missing left margin for buttons other than mat-button

### ISSUE THREAD

**Issue by IlCallo** [angular/components#12011]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
All buttons types should have a 8px margin left when in a mat-action-row, except for the first one in the row (`mat-action-row>button:first-of-type` or something like that)

#### What is the current behavior?
Only mat-button have it, which is set with this rule; `.mat-action-row button.mat-button`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Material 6.3.1

#### Is there anything else we should know?
Maybe something like `mat-button-base` shall become the general class added to all buttons and manage styling which must be applied to all buttons regardless of the appearance, like this one. instead of repeating all mat-buttons selectors

**Comment by crisbeto** [comment]
There's https://github.com/angular/material2/pull/11961 which adds `mat-button-base`, but it hasn't been merged yet. After it's in we should be able to use it for the action row.

**Comment by aeslinger0** [comment]
I'm seeing this with code like this:

        <mat-action-row>
          <button type="submit" mat-raised-button color="primary">Apply Filters</button>
          <button type="button" mat-raised-button (click)="clearFilters()">Clear Filters</button>
        </mat-action-row>

It looks like I can work around it by adding `mat-button` like this:

        <mat-action-row>
          <button type="submit" mat-button mat-raised-button color="primary">Apply Filters</button>
          <button type="button" mat-button mat-raised-button (click)="clearFilters()">Clear Filters</button>
        </mat-action-row>

Is it safe to do this or could it cause problems mixing `mat-button` and `mat-raised-button`?

**Comment by devversion** [comment]
This has been fixed with https://github.com/angular/components/commit/6a21d947f67dac472cecef02ba49996b2cc81047. Thanks for the issue report!
