### ISSUE TITLE
Add the possibility to not select an option in mat-select when a mat-option is clicked.

### ISSUE THREAD

**Issue by flemgs** [angular/components#12013]
#### Bug, feature request, or proposal:
When a mat-select contains a list of mat-option elements, and a user clicks on one one of the option, the option clicked shall not be selected in the HTML if mat-select has been given the possibility to not do so.

#### What is the expected behavior?
N/A.

#### What is the current behavior?
The option clicked is always selected. See  "private _onSelect(option: MatOption, isUserInput: boolean): void" method in https://github.com/angular/material2/blob/master/src/lib/select/select.ts. 
Maybe surrounds the line "option.selected ? this._selectionModel.select(option) : this._selectionModel.deselect(option);" in a if(selectable) statement ? Where 'selectable' would be a mat-select input ?

#### What are the steps to reproduce?
Basic example of a mat-select containing mat-options.

#### What is the use-case or motivation for changing an existing behavior?
It would be useful when you need a back-end to perform checks on the value clicked before returning a model to the front-end telling it if the value shall be selected in the HTML or not.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.2.1

**Comment by crisbeto** [comment]
This sounds very counter-intuitive. Why not do your checks after the element is selected and revert the value if it isn't supposed to be?

**Comment by flemgs** [comment]
Maybe you are right. I do not make the specifications for our software though, I'll ask my project owner. 
Historically we used to have our front-end components to behave like so.
