### ISSUE TITLE
Sticky option has no permanent effect on iOS devices

### ISSUE THREAD

**Issue by juliensie** [angular/components#12044]
#### Bug, feature request, or proposal:
mat-table's sticky attribute as a temporary effect on ios

#### What is the expected behavior?
should be fixed

#### What is the current behavior?
the header row is fixed but after few seconds it scrolls

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.8
Node: 8.11.3
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.3.1
@angular/cli                       6.0.8
@angular/material                  6.3.1
@angular/material-moment-adapter   6.3.1
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
rxjs                               6.2.1
typescript                         2.7.2
webpack                            4.8.3

all browsers running on ios are affected
![angular_material_sticky_row_ios_scrolling_480p](https://user-images.githubusercontent.com/19473981/42235998-cc2e03d6-7ef9-11e8-88d5-ba8cb5b825d8.gif)

**Comment by Rimhollow** [comment]
Is there any progress on this? I'm working on a warehouse data display webapp for a client, and they've already bought a crate of iPads; this bug is causing us some trouble. Thanks for your time!
