### ISSUE TITLE
mat-hint spacing looks wrong when appearance === "fill"

### ISSUE THREAD

**Issue by hblieb** [angular/components#12046]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Should have comfortable vertical spacing between form field inputs.

#### What is the current behavior?
mat-hint is too close to the input below

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://stackblitz.com/edit/angular-material2-issue-hmzwhb

#### What is the use-case or motivation for changing an existing behavior?
Common form layouts should look great.

**Comment by tearforfear007** [comment]
@hblieb Hi, I think I found the problem. Check the demo below.
[https://stackblitz.com/edit/angular-material2-issue-mxpgdq](https://stackblitz.com/edit/angular-material2-issue-mxpgdq)
It seem to be the `mat-form-field-wrapper` in appearance **fill** losing its margin.
It fixed when I add this css into styles.css.
```css
.mat-form-field-wrapper{
  margin: 4px 0;
}
```
### Fill
![image](https://user-images.githubusercontent.com/16658429/54258931-1c64de80-459f-11e9-8b44-ea458730a005.png)

### Outline
![image](https://user-images.githubusercontent.com/16658429/54258885-fd664c80-459e-11e9-94e4-bdb72021aff8.png)

Best wished.

**Comment by mmalerba** [comment]
We intentionally leave the margin up to the user to apply. If we were to specify a margin and someone wanted a smaller one they would have to override our styles, so its easier to have it take up the minimum space in the layout by default
