### ISSUE TITLE
mat-chip should also append on mat-select multiple - feature request

### ISSUE THREAD

**Issue by malikfaizanhaider** [angular/components#12055]
#### Feature request:
I'm using `<mat-select>` with multiple selections.

#### What is the expected behavior?
If user select all multiple options, then selected values should also append in `<mat-chip-lis>`.

#### What is the current behavior?
Currently on multiple selections just an span appended on selected values. 

![c intel](https://user-images.githubusercontent.com/4697658/42265748-e43a9388-7f8d-11e8-8744-f8f210ab9ed4.jpg)

**Comment by mmalerba** [comment]
What you're describing sounds like it would be some kind of custom component. There are no plans to add support for chips in mat-select
