### ISSUE TITLE
Bug Datepicker: manual input doesn't work after patching value when using MAT_DATE_LOCALE

### ISSUE THREAD

**Issue by Bielik20** [angular/components#12064]
#### What is the expected behavior?

Manual input to be reflected in the form value.

#### What is the current behavior?

After patching value of the form, any manual change to the form results in empty value.

#### What are the steps to reproduce?

I have made [StackBlitz example](https://stackblitz.com/edit/angular-datepicker-bug) but setting locale doesn't work there (https://github.com/angular/material2/issues/10086) so the issue is NOT present. To test it, it has to work with foreign locale eg. "pl-PL". 

Steps to reproduce:
1. Click "Patch Value"
2. Manually change date (just a year for example)
3. Form value should be now empty

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular: 6.0.7
- Material: 6.3.2

#### Is there anything else we should know?

Possibly related: https://github.com/angular/material2/issues/11936

**Comment by mmalerba** [comment]
It looks like this has been fixed, following the repro steps with the stackblitz example given, the value was not empty (both when I changed via the calendar and via typing)
