### ISSUE TITLE
Wrong placeholder scroll behavior in dialog on firefox mobile

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/components#12085]
#### Bug, feature request, or proposal:
Bug report

#### What is the expected behavior?
Placeholder of an input in a dialog should scroll same as the input itself.

#### What is the current behavior?
The placeholder scrolls further then the rest of the dialog content.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-sexkpn

open the stackblitz link above on an android phone with the firefox browser, open the dialog, focus one of the inputs, then start scrolling.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest (61.0) firefox mobile browser on android (7.0)

#### Is there anything else we should know?
It seems to be only happening during the scrolling (placeholder gets prepositioned correctly after scroll) and only if a input had a focus (scrolling right after opening the dialog the scrolling seems to be working fine).

**Comment by crisbeto** [comment]
I wasn't able to reproduce this. Given that we haven't had any more similar reports since this issue was posted, I'm assuming that it has been resolved.
