### ISSUE TITLE
MatTable : MatSort : variety of bugs

### ISSUE THREAD

**Issue by tatsujb** [angular/components#12087]
#### Bug, feature request, or proposal:

MatSort from Material Table bugs

#### What is the expected behavior?

sorting the column. In ascending descending or original.

#### What is the current behavior?

Variety of bugs,

- if one of the items in the column to sort is a `/` sort will fail and result in a column where items are in disorder : 

|unsorted :   |asc :   | desc :  |
|:-:|:-:|:-:|
|![image](https://user-images.githubusercontent.com/5132359/42379361-b169d52e-812a-11e8-8ceb-8d9659747d13.png)   |![image](https://user-images.githubusercontent.com/5132359/42379397-d4ef316a-812a-11e8-8b2f-d14859f88f97.png)   |![image](https://user-images.githubusercontent.com/5132359/42379407-df0d6b3a-812a-11e8-9987-dd0ad819d0ec.png)  |

- if items contain preceding zeroes even if the passed var was a string these are ignored
(and this ...regardless of context should be regarded as unintended behavior, it makes more sence for the Angular user to have to add "skip preceding zeroes" himself then to have to add "sort including preceding zeroes" himself. to have this sort of behavior my strings must have been parsed. something that would make sense to me if there was, for example, a "typeOf" directive in `<mat-header-cell>` or something of the like, but parsing my values without my specific demand should not be standard-issue) : 

|unsorted :   |asc :   |desc :   |
|:-:|:-:|:-:|
|![image](https://user-images.githubusercontent.com/5132359/42380624-da7fcbb8-812e-11e8-956c-2255980345e6.png)   | ![image](https://user-images.githubusercontent.com/5132359/42380636-e6ac31b0-812e-11e8-9072-382b082ace8e.png)  |![image](https://user-images.githubusercontent.com/5132359/42380661-f5f56f38-812e-11e8-95a1-b089c315a2b6.png)   |

- now... I understand if you see this one as intended behavior, although to be fair it's pretty shocking to your John Doe ...MatSort places :

1. Numers first 0 - 9
2. Uppercases second A - Z
3. LoweCases third a - z

my beef with that is of course the unmerged lower and uppercases. 

...This results in (asc sorted) : 44684, 7545, 9, Barbarra, Xavier, Yvonne, Zachary, arnold, barbarra
which is a pretty useless sort-type to have displayed in a table.

a simple `.toLowerCase()` costs nothing to you and saves the guy implementing mat-table, who wants a very basic and quick setup a lot of time. (and is just good practice)

|unsorted :   |asc :   |desc :   |
|:-:|:-:|:-:|
|![image](https://user-images.githubusercontent.com/5132359/42381159-8bb4b366-8130-11e8-938e-c379f2382150.png)   |![image](https://user-images.githubusercontent.com/5132359/42381173-96d149e4-8130-11e8-8970-eae2d11451e9.png)   |![image](https://user-images.githubusercontent.com/5132359/42381214-b2570afa-8130-11e8-908e-1dda247b94d8.png)   |

**Comment by crisbeto** [comment]
I wasn't able to reproduce the first issue just by adding a slash in some of the data. Can you post a Stackblitz that shows the issue?

**Comment by tatsujb** [comment]
@crisbeto I'll try, I can't find the base mat table stackblitz without async data reload on sort. I just want a static data const I replace to test it.

**Comment by crisbeto** [comment]
You can use this one which has a static array of data: https://stackblitz.com/angular/lyvjkxvjqvm.

**Comment by tatsujb** [comment]
@crisbeto you're right : `/<something>` works, `/` doesn't though.

**Comment by crisbeto** [comment]
Can you fork the link from above to show it breaking? I tried changing some of the names to `/`, but I couldn't get it to break.

**Comment by tatsujb** [comment]
here : thanks for the stackblitz btw 🙂 . it's going to be very handy to me btw! : 

https://stackblitz.com/edit/angular-xuksqd?file=app/table-sorting-example.ts

**Comment by RodEsV** [comment]
+1

**Comment by tatsujb** [comment]
the reason why mat-table's sort is giving me so much pains is that it's making a shift-select impossible to implement because the sorted data is 100% obscured from us the dev. 

I dunno where but deep within mat-table's npm package code is buried the actual sort method  that mat table uses to read the table instead of simply reading `this.dataSource.data`.

no member of `this.dataSource` contains the sorted array.

this may have performance benefits but it's ruining the dev's life.

instead (I deduce that) mat table reads `this.dataSource.data`, reads `this.dataSource.sort.direction` to get the current sorting direction and see if sorting is on, reads `this.dataSource.sort.active` to get the sorted column and this variable is returned on the fly to mat table for display and never stored anywhere, which I deplore.

My first instinct was to call : 

```
<mat-table
        matSort
        [dataSource]="dataSource"
        (matSortChange)="sortData($event.active, $event.direction)"
      >
```
`matSortChange` to superimpose what happens with sort. as it turns out this method doesn't do that. (and you can't just remove `matSort` but keep the sorting header arrows and events either)

`matSortChange`  just executes some code before `matSort` but no matter what you replace `this.dataSource.data` with, that array will be re-sorted by `matSort` anyways. so you don't get to have the final word.

I thought that maybe I could at least recreate this object myself so as to get correct index count and iteration as a means to accomplish my shift-select : 

```
addToSelection(event, checkbox){
    const copy = [...this.dataSource.data];
    if(this.dataSource.sort.direction !== ''){
      let [v1, v2] = (this.dataSource.sort.direction === 'asc') ? [-1, 1] : [1, -1];
      copy.sort((a,b) => b[this.dataSource.sort.active] > a[this.dataSource.sort.active] ? v1 : v2);
    }
    const indexOf = copy.indexOf(row);
    console.log(indexOf, copy); // <-- sorted but not the same.
    

    const tog = (i) => {
      if(this.selected.indexOf(i) !== -1) this.selected = _.without(this.selected, i);
      else this.selected.push(i);
    };
    if(event.shiftKey && this.previous !== -1 && this.previous !== indexOf) {
      const currentSet = [];
      copy.forEach((o, i) => currentSet.push(i));
      if(currentSet.indexOf(this.previous) !== -1){
        if(this.previous < indexOf){
          const toToggle = currentSet.slice(currentSet.indexOf(this.previous) + 1, currentSet.indexOf(indexOf) + 1);
          toToggle.forEach(x => tog(x));
        }else{
          const toToggle = currentSet.slice(currentSet.indexOf(indexOf), currentSet.indexOf(this.previous));
          toToggle.forEach(x => tog(x));
        }
      }
    } else if(event.ctrlKey || checkbox) {
      tog(indexOf);
    } else {
      if(this.selected.length === 1 && this.selected[0] === indexOf) {
        this.selected = [];
      } else {
        this.selected = [];
        this.selected.push(indexOf);
      }
    }
    this.previous = indexOf;
  }
```

but my log (`console.log(indexOf, copy);`), after a sort and select returns : 
![image](https://user-images.githubusercontent.com/5132359/42683827-b918373e-868e-11e8-8d58-66b12c457240.png)  

whereas my mat table is showing : 

![image](https://user-images.githubusercontent.com/5132359/42683941-07651a6a-868f-11e8-9384-5c4e1b9b9917.png)

So the index of finds our row at the 4th position at the 21st position because that's where it's at in the sorted array we created which has the same results visually (same numbers from position 4, all the way down to position 26, for example) but doesn't order them the same way. 

it's interesting to note that these results (for sorting a === b) aren't random... they're the same every time.

If I repeat the experiment n times, that is : 

1.  load the page
2.  sort the `nCommande` column 

(I already have an identical sort as last time and I know it's not only visual because the row numbers I created are in the same sequence as I saw before (and that you see in the above screenshot) : "2, 1, 3, 4, 20, 22, 19, 7...")

3. (counting from 0) click on the line 4, (the one with my row number 20), my console log still says the index of is 21 when it should be 4.

**Comment by andrewseguin** [comment]
The issue here is that the sort function does not know whether the user is trying to sort numbers or strings. It simply compares two values at a time. This causes some issues if the array contains both.

To fix this, provide a sort data accessor that does not try to coerce numbers from a string. Just make the data accessor return the value directly: 

```ts
  constructor() {
    this.dataSource.sortingDataAccessor = (data: any, key: string) => data[key];
  }
```

https://stackblitz.com/edit/angular-y8pwh9?file=src/app/table-sorting-example.ts
