### ISSUE TITLE
[mat-tab mat-stepper mat-tree] Render perf after migrate angular and angular material 5 to 6

### ISSUE THREAD

**Issue by mcailleaux** [angular/components#12117]
#### Bug, feature request, or proposal:
After migrating angular 5 to 6 the render performence of mat-tab, mat-tree and mat-stepper take a lot of time (4 or 5 times more)
My tabs contains a lot of small component
The bug appear just after the migration with no other modification

#### What is the expected behavior?
To have the same render perf than angular and material 5

#### What is the current behavior?
mat-table render fast but changing tab take a lot of time to render
mat-stepper and mat-tree take a lot of time to first render but change is fast

#### What are the steps to reproduce?
Create one of this component with other sub component containing mat-card, mat-list and form control
(i reproduce with a component that contain 4 mat-card with 10 form control each)

#### What is the use-case or motivation for changing an existing behavior?
I want to continu with angular 6 and benefit the new component like mat-badge and other

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular : 6.0.6
Angular material 6.3.2
OS : Ubuntu 18.04 LTS
Typescript : 2.7.2
Browsers : Chrome 66.0.3359.181, Firfox 61.0

#### Is there anything else we should know?
Thank you for the help

**Comment by crisbeto** [comment]
Sorry, but this isn't a lot of information to go on. Can you post an example of your setup?

**Comment by mcailleaux** [comment]
What do you need?

package.json? angular.json? other?

**Comment by mcailleaux** [comment]
After a first test in prod mod, the problem is only in dev mode

**Comment by jelbourn** [comment]
Without actual measurements from a performance tool or a running application, there's not really anything we can investigate.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a StackBlitz or GitHub reproduction of the issue. 

Please file a new issue that follows the template and includes a reproduction. This gives the team the information needed to investigate the bug or prioritize the enhancement.
