### ISSUE TITLE
Docs: Tree with nested node examples do not work and crash

### ISSUE THREAD

**Issue by mabdullahsari** [angular/components#12131]
#### What is the expected behavior?
The examples for trees with nested nodes should work

#### What is the current behavior?
The docs app throws uncaught errors in the console, visit the section and look for yourself.

#### What are the steps to reproduce?
https://material.angular.io/components/tree/overview
https://material.angular.io/components/tree/examples
Visit these

#### What is the use-case or motivation for changing an existing behavior?
It speaks for itself

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'd assume the latest ng and mat versions
Using Chrome 67

#### Is there anything else we should know?
Nope.

**Comment by troyspencer** [comment]
Fix found here: https://github.com/angular/material2/blob/master/src/material-examples/cdk-tree-nested/cdk-tree-nested-example.ts

This works on the nested example and the checkbox example which is also currently broken.

Change this line: 
```
private _getChildren = (node: FileNode) => node.children;
```
to this: 
```
private _getChildren = (node: FileNode) => observableOf(node.children);
```

Change this import:
```
import {BehaviorSubject} from 'rxjs';
```
to this:
```
import {BehaviorSubject, of as observableOf} from 'rxjs';
```

**Comment by amysorto** [comment]
The errors in the console for the examples don't appear anymore
