### ISSUE TITLE
Show ripple focus indicators in high contrast

### ISSUE THREAD

**Issue by devversion** [angular/components#12169]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ripple focus indicators are necessary in order to guarantee keyboard navigation and good accessibility. 

In high contrast it's right to hide all transient ripples, but persistent ripples should stay visible but not obstruct the content.

#### What is the current behavior?

Right now, every type of ripple element is made invisible in high contrast mode. 

(Even the host element: See #12168)

#### What is the use-case or motivation for changing an existing behavior?

Accessibility

cc. @jelbourn for feedback on a11y.

**Comment by jelbourn** [comment]
Yeah, this one is tricky, I'm not sure what the best approach would be.

**Comment by DevVersion** [comment]
Yeah I agree. I already have an idea that makes ripple look pretty reasonable in high contrast. Will continue playing with some ideas, but it's good to see that there needs to be some solution.

**Comment by devversion** [comment]
We removed ripples in high-contrast, but added alternate focus indicators that work in high-contrast. While verifying this, it came to mind that the checkbox currently has broken high-contrast styles. Created https://github.com/angular/components/issues/19443 for tracking.
