### ISSUE TITLE
Add pagination feature to Mat Stepper Header like Mat Tab Header

### ISSUE THREAD

**Issue by k-d-andani** [angular/components#12166]
#### Bug, feature request, or proposal:
Request to enable mat stepper header pagination like mat tab header pagination

Currently, In Mat Stepper would not see good in mobile window if steps are very.
So, i would like to request for add pagination feature for Material Stepper Header, which is also available for Material Tab Header.

Thanks,
Kaushik Andani

**Comment by r2b2l** [comment]
+1

**Comment by akvaliya** [comment]
Any progress on this. I have more then 11 steps in my project & really need some responsive support

**Comment by alejosaur** [comment]
Any progress on this?

**Comment by amysorto** [comment]
Since #20692 was closed, closing this issue as well
