### ISSUE TITLE
Create Exposed dropdown menu 

### ISSUE THREAD

**Issue by hijamoya** [angular/components#12172]
#### Bug, feature request, or proposal:
According to 
https://material.io/design/components/menus.html#exposed-dropdown-menu

Text field dropdown menus look like text fields and display the currently selected item above the menu.

On desktop, a text field dropdown menu appears below the element triggering the dropdown.

#### What is the expected behavior?
A text field dropdown menu appears below the element triggering the dropdown.

#### What is the current behavior?
A text field dropdown menu overlays the element itself.

#### What are the steps to reproduce?
https://material.angular.io/components/select/overview

**Comment by crisbeto** [comment]
Closing since this seems like it's covered by `mat-select`.
