### ISSUE TITLE
mat-select custom icon

### ISSUE THREAD

**Issue by SnehalBhavsar** [angular/components#12190]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
does mat-select control allow us to change icon. similar to how datepicker allows it. as shown below. 
https://github.com/angular/material2/tree/master/src/material-examples/datepicker-custom-icon

#### What is the current behavior?
we are not able to change icon which appears in mat-select

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
this would help in customize as per page theme. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5

#### Is there anything else we should know?
N/A

**Comment by karlmnz** [comment]
.mat-select-arrow { display: none; } doesn't help in A7 as with reactive form control it somehow hide the select value also.  Can click to get dropdown but the value is never displayed.

**Comment by Koziuk-S** [comment]
I use **visibility: hidden;**.

`.mat-select-arrow {
      visibility: hidden;
}`

**Comment by paulpinto88** [comment]
i am not able to change the down arrow icon for the mat-select

**Comment by amysorto** [comment]
Since our material components are based on the material spec, we are using the icon they use and it isn't something that is supposed to be customizable.
