### ISSUE TITLE
Tooltips do not reliably appear when using NoopAnimationModule

### ISSUE THREAD

**Issue by jonrimmer** [angular/components#12191]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Tooltips should reliably appear when using NoopAnimationModule.

#### What is the current behavior?

Tooltips sometimes fail to appear.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pnwltn?file=app%2Ftooltip-overview-example.html

The two segments the donut chart each has a `mat-tooltip` on it, but only the left segment's tooltip appears reliably. If you mouse over and out of the right segment, you should see that its tooltip only occasionally appears.

This bug goes away if you replace NoopAnimationModule with BrowserAnimationModule in the main module.

#### What is the use-case or motivation for changing an existing behavior?

N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6
Material: 6
OS: macOS High Sierra
TypeScript: 2.7
Browsers: Chrome 67.0.3396.99

It seems to work OK in Firefox Dev Edition.

**Comment by FallenRiteMonk** [comment]
I have the same problem. I have tracked it down to be very buggy on chrome mobile.
https://stackblitz.com/edit/angular-n5k3du
the tooltip on this button works fine on a desktop (in my case linux) chrome and firefox (both latest) and even on the latest firefox for android, but it does not work at all with chrome android.
The bug can be fixed the same way as in @jonrimmer's example by importing BrowserAnimationModule.

**Comment by obirider** [comment]
Any update on this?

**Comment by devversion** [comment]
Hello! I was trying the OP stackblitz and updated it to the latest version. I'm not able to see the issue: https://stackblitz.com/edit/comp-12191?file=main.ts. I also tried the StackBlitz provided by @FallenRiteMonk, but I was not see any unexpected behavior.

Can someone please provide more context on whether this is still an issue, and on how one can see the issue? I've tried with `Android 8 Chrome 80` and Desktop Chrome 83.

**Comment by FallenRiteMonk** [comment]
@devversion I had a look and I was no longer capable or reproducing the issue.

**Comment by devversion** [comment]
Awesome. Thanks for getting back to me so quickly. I'm closing this, but happy to re-open if you ever come across this again!
