### ISSUE TITLE
feature: extended FAB (Floating Action Button)

### ISSUE THREAD

**Issue by donroyco** [angular/components#12246]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
To have the Extended FAB (Floating Action Button) as a Material component, as designed in the [Google Material Design](https://material.io/design/components/buttons-floating-action-button.html#extended-fab).

![Google Material Design preview - Extended FAB](https://material.io/design/assets/1P8peBxVujhfPIPwolj6hPeiSiAZUiKnw/extended-fab-01.png)
See for more examples the [Google Material Design documentation](https://material.io/design/components/buttons-floating-action-button.html#extended-fab).

#### What is the current behavior?
There's currently no (extended) FAB to use when you can't explain an action with only an icon (as the FAB itself is designed for).

#### What is the use-case or motivation for changing an existing behavior?
To follow the Google Material Design and its components. There's now no component to provide the kind of interaction a FAB has plus a text label. 

#### Is there anything else we should know?
It was already mentioned before in #11534, but it was closed due to not following the issue template.

**Comment by JaxonWright** [comment]
This would be a great addition. Really, anything introduced in Material Design 2.0 would be amazing if added.

**Comment by kill33** [comment]
That's a great addition.
And there is some implemention and discussion in #860 md-fab-speed-dial.

**Comment by JWess** [comment]
Workaround that looks pretty close:

```
<button class="extended-fab-button" mat-fab color="primary" (click)="this.showNotesDialog()">
  <mat-icon>speaker_notes</mat-icon>
  <span class="extended-fab-button__text">Notes</span>
</button>
```
```
.extended-fab-button {
  width: unset;
  padding: 0 26px;
  border-radius: 29px;

  .mat-icon {
    margin-right: 10px;
  }

  .extended-fab-button__text {
    font-weight: 300;
    letter-spacing: .1em;
    text-transform: uppercase;
  }
}
```

![image](https://user-images.githubusercontent.com/8697891/53919216-58e08980-4037-11e9-9e45-7d43a08406d8.png)

**Comment by dshukertjr** [comment]
Is this feature not coming?

**Comment by BobDankert** [comment]
Any updates on this? Are there any particular challenges with this issue?

**Comment by guss77** [comment]
Workaround works well, but I would love to see this supported by the `MatButton` component itself. What happened with #15645? looks like a lot of good work?

**Comment by evilangelmd** [comment]
any information about #15645 @josephperrott , @jelbourn ?

**Comment by JaxonWright** [comment]
@JWess in order for your workaround to work in IE11, you need to change `width` from `unset` to `auto`, which is the default value.

**Comment by crisbeto** [comment]
This is supported in the MDC version of the FAB which will become the default eventually. If you want to start using it now, you can import the `MatButtonModule` from `@angular/material-experimental/mdc-button` and use an extended FAB like this:

```html
<button mat-fab extended>
  <mat-icon>check</mat-icon>
  Search
</button>
```
