### ISSUE TITLE
Class names could cause confusion between breakpoints and sizing

### ISSUE THREAD

**Issue by bsteffl** [angular/components#12265]
#### Bug, feature request, or proposal:
Proposal, Have separate naming schemes for sizing vs. breakpoints

#### What is the expected behavior?
Class names between breakpoints and sizing class names should be discernibly different so consumers know the difference.

#### What is the current behavior?
When using the small badge you get a class name `mat-badge-small`. When using mat-bottom-sheet you get classes relating to breakpoints `mat-bottom-sheet-container-medium` and may cause confusion understanding if this is a class for sizing vs. class for breakpoints when overriding styles.
![image](https://user-images.githubusercontent.com/10760551/42892425-6bd48044-8a77-11e8-94fb-e567b363ccd7.png)    
![image](https://user-images.githubusercontent.com/10760551/42892487-903dcc92-8a77-11e8-8bbd-b133d0817c4b.png)  

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
To have a clear and concise class naming system.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.3.3

#### Is there anything else we should know?
I realize this is a very minuscule detail and maybe isn't a concern, but thought I should mention it.

**Comment by josephperrott** [comment]
I can see how this could be confusing at first glance.

Do you have any thoughts on what naming scheme we could use?  Also worth noting that this would be a breaking change and have to happen over time.

**Comment by bsteffl** [comment]
You could separate your classes out using the BEM method and anything relating to size as a modifier. I liked that you were also using `-size` in some instances in the code and thought that helped clarify. I don't have any concrete ideas on naming specific to breakpoints.

Here is one example:
`mat-badge--small-size`

**Comment by jelbourn** [comment]
Closing this since we consider our CSS classes to be internal/implementation details. Despite that, changing the class names at this point would cause unnecessarily churn for people that override the CSS anyway.
