### ISSUE TITLE
prependchild function

### ISSUE THREAD

**Issue by bishu40010961** [angular/components#12278]
#### Bug, feature request, or proposal:
after opening modal dialog , if we start tabbing from url bar, focus shifts to background of modal dialog.

#### What is the expected behavior?
focus should not go in background, it should be shifted to dialog and remain confined in it.

#### What is the current behavior?
focus shifts to background of modal dialog if we start tabbing from url bar.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
1. open a dialog.
2. click on url bar.
3. press tab 
4. focus goes behind overlay(which should not happen)

#### What is the use-case or motivation for changing an existing behavior?
when dialog opens focus should not go behind the overlay. this can lead to opening of multiple instance of same dialog, as target button is accessible in background. 

** screenshots from https://v5.material.angular.io/components/dialog/overview **
![twodialogs](https://user-images.githubusercontent.com/13434166/42935798-331df4b4-8b68-11e8-80f9-72d083209cb8.JPG)
![inputx](https://user-images.githubusercontent.com/13434166/42935757-189386fe-8b68-11e8-8e98-9aa3d8707757.JPG)
![dialog](https://user-images.githubusercontent.com/13434166/42935762-18ce9c6c-8b68-11e8-8c3e-0740033d47b8.JPG)
*in developer console multiple instance  of same dialog is visible.
* in first image width of upper dialog is manipulated to show lower dialog.
 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all 

#### Is there anything else we should know?
if we prepend the popup to the body , rather than appending it, it can solve the problem. as dialog will be first focussable elment and focus will be confined within it.

**Comment by crisbeto** [comment]
This is relatively easy to implement on our end, but it won't solve the root issue, because the overlays inside the overlay container are inserted in the order they were opened, which means that if the user had two open dialogs at the same time, they'd tab into the bottom one. A more robust solution would be to listen to the `focus` event on the `window` and pull focus back into the focus trap, but I'm not completely sure what the API would look like since we don't want all focus traps to compete for focus at the same time. What do you think @jelbourn?

**Comment by jelbourn** [comment]
We've needed to redo `focus-trap` for a while now. Part of that would be disabling everything outside of the trapped area, which should address this.

**Comment by crisbeto** [comment]
We're already adding `aria-disabled` to everything outside of dialogs, but that doesn't help when you're tabbing in from the URL bar.

**Comment by jelbourn** [comment]
Yeah, I mean using real `disabled` (and probably `tabindex="-1"` too)

**Comment by bishu40010961** [comment]
Is there any fix in sight??

**Comment by crisbeto** [comment]
Should be resolved by the new focus trap.
