### ISSUE TITLE
mat-menu button does not display dropdown in android webview

### ISSUE THREAD

**Issue by jarrhead777** [angular/components#12288]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Menu does not display when clicking the button.

#### What is the expected behavior?
Work like it should

#### What are the steps to reproduce?
Add a site to the webview with the Angular Material mat-menu. It simply does not work. I have tested in chrome,firefox,IE, and edge on mobile and they seem to work fine. The button shows the ripple effect but never displays the menu.

I can embedded the current Angular Material site into the webview and the mat-menu reproduces the same result.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.1.1
Material: 5.1.1
OS: Android 8.1.0 - Pixel 2 XL
Typescript: 2.7.1

#### Is there anything else we should know?
I have also tried this on a Samsung Note 8 and Samsung Galaxy Tab 3 same results.

**Comment by jarrhead777** [comment]
Furthermore, I updated to the latest version of angular and material and still getting the same results.

**Comment by mmalerba** [comment]
This works for me, opened material.angular.io and menus worked as expected

Android 10, Pixel 3
Angular 10
