### ISSUE TITLE
Scrollbars appearing with Mat-Expansion-Panel in Mat-Tab with Edge/IE.

### ISSUE THREAD

**Issue by flipZomb** [angular/components#12319]
#### Bug, feature request, or proposal:
Bug, I presume

#### What is the expected behavior?
no "rogue" scrollbars.

#### What is the current behavior?
"rogue" scrollbar is appearing with Expansion Panel in Tabs. Happens with  Edge and IE 11, seems ok in Chrome.

I hope the screenshots explain the issue sufficiently.

![image](https://user-images.githubusercontent.com/33517613/43049291-732b49fa-8df5-11e8-999b-57cb4ff21d68.png)

![image](https://user-images.githubusercontent.com/33517613/43049306-91df46da-8df5-11e8-9ef1-9a67d183ebf4.png)

![image](https://user-images.githubusercontent.com/33517613/43049315-ac4c3578-8df5-11e8-819b-405170db35fb.png)

Resize the Window and this happens
![image](https://user-images.githubusercontent.com/33517613/43049326-e51f5560-8df5-11e8-8f11-7000abc68b61.png)

But switching the tabs back and forth makes the scrollbar go away. Also minizing and then restoring ithe window makes the scrollbar go away. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-r5vupv?file=app/expansion-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.3.3
Angular 6.0.9
Edge / IE11

#### Is there anything else we should know?
Works fine in Chrome

**Comment by crisbeto** [comment]
Closing since IE11 hasn't been supported for a long time now.
