### ISSUE TITLE
[Datepicker] MatLuxonDateAdapter

### ISSUE THREAD

**Issue by FrankiePo** [angular/components#12321]
#### Bug, feature request, or proposal:
Feature request
#### What is the expected behavior?
Luxon Date Adapter for datepicker, like the moment one.

#### What is the current behavior?
There is no built-in support for luxon date library.

#### What is the use-case or motivation for changing an existing behavior?
The use case is to have built-in Luxon support for datepicker

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.9, Newest Material, etc
#### Is there anything else we should know?

**Comment by babeal** [comment]
I think we are going to build this for our project.  Is this something that the material team would like contributed back?

**Comment by alexxxxOG** [comment]
This is a duplicate of #10427.

**Comment by kdrvn** [comment]
What is the status on this feature? Is it still being considered?
I wrote an implementation with proper testing for a project, I could wrap it in a PR.

**Comment by mmalerba** [comment]
This has been implemented and is waiting to be merged: #14681

**Comment by jelbourn** [comment]
Tracking this in #20599 going forward
