### ISSUE TITLE
MatSlideToggle processing state

### ISSUE THREAD

**Issue by Nodarii** [angular/components#12340]
#### Feature request:
new state for `mat-slide-toggle` that would represent _processing_ status

##### Display processing status
Because a switch shows the actual status of something, sometimes there is a delay in its change of state. In such cases, a processing status animation can be used.

A processing status is an animation on the thumb of the switch. For example, it can be used when a switch that controls a hardware feature experiences a delay before its final status can be confirmed.

https://material.io/design/components/selection-controls.html#switches

#### proposed interfase

`<mat-slide-toggle [resolve]="slideMeResolver">Slide me!</mat-slide-toggle>`

where slideMeResolver is function like:

`declare function slideMeResolver<T>(state: MatSlideToggleChange): Observable<T>;`

**Comment by DevVersion** [comment]
That's a good request. I just have the feeling that it's wrong to let the `MatSlideToggleModule` depend on the progress spinners module.

**Comment by devversion** [comment]
This is something we can support when the MDC equivalent slide-toggle implementation does. Closing this as we don't have any plans in adding this to the existing non-MDC slide-toggle.
