### ISSUE TITLE
Add MatBadge to Tab's label

### ISSUE THREAD

**Issue by Londeren** [angular/components#12358]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
<img width="756" alt="screen shot 2018-07-25 at 10 16 42" src="https://user-images.githubusercontent.com/757427/43185298-28c111dc-8ff4-11e8-89f9-af7dc356bb03.png">

#### What is the current behavior?
There is no way to add a badge to tab's label

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by donroyco** [comment]
Please use [the issue template](https://github.com/angular/material2/blob/master/.github/ISSUE_TEMPLATE.md) to prevent your issue from getting closed.

**Comment by MathiasHusum** [comment]
I've got the same issue, matBadge doesn't seem to be part of the tab when i'm inspecting it in the browser

**Comment by Gaiidenn** [comment]
I have no problem to add a badge into my tab label. Did you try this :
<mat-tab>
    <ng-template matTabLabel>
        <span matBadge="5" matBadgeOverlap="false">My header</span>
    </ng-template>
    Your tab content goes here
</mat-tab>

It works on my project actually !

**Comment by manjunathd** [comment]
> I have no problem to add a badge into my tab label. Did you try this :
> 
> ```
> <mat-tab>
>     <ng-template matTabLabel>
>         <span matBadge="5" matBadgeOverlap="false">My header</span>
>     </ng-template>
>     Your tab content goes here
> </mat-tab>
> ```
> It works on my project actually !

Doesnt work for me either. Tried with Angular & Material 7.2.1.
Here is the stackblitz link - [Stackblitz Link](https://stackblitz.com/edit/angular-hkubg3)

**Comment by jrouss915** [comment]
I had the same issue.  I solved it by importing the MatBadgeModule

**Comment by anouar1991** [comment]
> I have no problem to add a badge into my tab label. Did you try this :
> 
> ```
> <mat-tab>
>     <ng-template matTabLabel>
>         <span matBadge="5" matBadgeOverlap="false">My header</span>
>     </ng-template>
>     Your tab content goes here
> </mat-tab>
> ```
> 
> It works on my project actually !

this actually works! @Gaiidenn can you explain the solution please <3

**Comment by jelbourn** [comment]
Closed since this seems to be working as intended.
