### ISSUE TITLE
mat-form-field with outline appearance doesn't resize border when label content change dynamicaly

### ISSUE THREAD

**Issue by jcadiba** [angular/components#12353]
#### Bug :
mat-form-field with outline appearance doesn't resize border when label content change dynamicaly

#### What is the expected behavior?
Borders must resize themselves automatically to take into account the dynamic changes of the label

#### What is the current behavior?
The borders take into account the initial value of the label but after if this value changes and it is longer than the initial value, the borders do not adapt to this change thus leaving a border overlapping the label

#### What are the steps to reproduce?
from this stackblitz, first when the form launch the label of the outline form field have the value **"initial"** and after write in first form field that is bind to the second form field mat-label  the value **"Long dynamic label"** you will see the border will overlap  the label
https://angular-axyjeg.stackblitz.io (https://stackblitz.com/edit/angular-axyjeg)

**Before**
![2018-07-25 2](https://user-images.githubusercontent.com/32568095/43195305-3257cfce-8ff4-11e8-87ec-ccf1cb256877.png)

**After**
![2018-07-25 3](https://user-images.githubusercontent.com/32568095/43195320-42ad79c8-8ff4-11e8-982e-720b1f7e2f45.png)

**Comment by mcailleaux** [comment]
Same problem when use ngx translate with label, the gap is calculed with the translate key 

```
<mat-form-field appearance="outline">
    <mat-label translate="ea6.design.menu.header.search"></mat-label>
    <input matInput [(ngModel)]="searchText"
           (ngModelChange)="searchChange()">
    <mat-icon matSuffix>search</mat-icon>
</mat-form-field>
```
![image](https://user-images.githubusercontent.com/18030833/43191498-96d3bc72-8ffb-11e8-8708-d659105d020c.png)

**Comment by taboo09** [comment]
I don't know if it helps but had the same problem and discovered in my stylesheet file a `.hidden` class applied to a `form `element with `display: none;` content.
It can be something else, so you need to check your css file.
