### ISSUE TITLE
Angular Material Datepicker Reactive Forms Preselected Date with MomentDateAdapter

### ISSUE THREAD

**Issue by sweetyv** [angular/components#12368]
#### What is the expected behavior?
To show preselected date from API on load of the page. 

#### What is the current behavior?
I am using Angular Material Datepicker with reactive forms with MomentDateAdapter(to customise the date format) and I am able to get the date from API, but not able to show it on the input field and on datepicker when user lands on the page.
```html
<input _ngcontent-c3="" class="mat-input-element mat-form-field-autofill-control ng-untouched ng-pristine ng-invalid" formcontrolname="FED" matinput="" placeholder="Flight End Date" ng-reflect-mat-datepicker="[object Object]" ng-reflect-value="Jul 27, 2018" ng-reflect-name="FED" ng-reflect-placeholder="Flight End Date" aria-haspopup="true" id="mat-input-2" aria-invalid="false" aria-required="false">
```
The above console source code shows how the date is reflected in the ng-reflect-value but not in ng-reflect-mat-datepicker.

#### HTML Code
```html
 <mat-form-field class="datepickerInput">
          <input formControlName="FED" matInput [matDatepicker]="picker1" placeholder="Flight End Date" value={{fedVal}}>
          <mat-datepicker-toggle matSuffix [for]="picker1"></mat-datepicker-toggle>
          <mat-datepicker touchUi="true" #picker1></mat-datepicker>
          <mat-error>
          <div *ngIf="submitted && f.FED.errors || !usForm.get('FED').valid && usForm.get('FED').touched" class="invalid-feedback">
            <div *ngIf="f.FED.errors.required">Please select a date</div>
          </div>
        </mat-error>
        </mat-form-field>
```

TS Code
```ts
  ngOnInit() { 
      this._testService.getSettingData()
      .subscribe(data => {
        this.fedVal = data['universalSetting']['flightEnd'];
        this.fsdVal = data['universalSetting']['flightStart'];

this.usForm = this.fb.group({
            'FSD': [this.universalSetting['flightStart'], Validators.required],
            'FED': [this.universalSetting['flightEnd'], Validators.required],
          });

   this.finalSettingVal = $.param({
            flightEnd: moment(this.usForm.value.FED, 'MMM-DD-YYYY').format('MMM DD, YYYY'),
            flightStart: moment(this.usForm.value.FSD, 'MMM-DD-YYYY').format('MMM DD, YYYY'),
          });
});
 }
}
```

#### What is the use-case or motivation for changing an existing behavior?
I want to use custom date format as per the project requirement. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5 
Material 2
Mac OS High Sierra
Working on latest chrome broswer

Any idea where I have gone wrong? This is urgent, please help.

**Comment by wagnermaciel** [comment]
@sweetyv I tried to reproduce this with stackblitz but was unable to. Here's a link to what I tried. If you could provide a stackblitz with an example of this issue, that would be very helpful. Thanks!

https://stackblitz.com/edit/angular-svkid5?file=src%2Fapp%2Fdatepicker-formats-example.ts
