### ISSUE TITLE
Material placeholder are disappeared when try to print in Chrome browser only

### ISSUE THREAD

**Issue by subin1010** [angular/components#12371]
angular material place holder text are disappeared when to print in chrome browser only, firefox is ok and ie.

**Comment by subin1010** [comment]
![image](https://user-images.githubusercontent.com/26795663/43223254-5811e2be-9007-11e8-8c40-d519d94f021d.png)

**Comment by subin1010** [comment]
Material input placeholders issues when they are printed in Chrome, it works for Firefox.

**Comment by wags1999** [comment]
We're seeing the same behavior in Chrome 67.  Also, the placeholders still show up if I set the Dev Tools CSS media emulation = Print, but not in a Print Preview window.  Not sure why we haven't noticed this before - maybe a recent Chrome update broke this?

**Comment by crisbeto** [comment]
Closing since I can't reproduce it with the latest version.
