### ISSUE TITLE
MatBadge is cropped when used in a material list item line

### ISSUE THREAD

**Issue by tsiage** [angular/components#12384]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A text with a badge icon should be fully visible in a material list item line

#### What is the current behavior?
The badge icon is cropped when used in a material list item line

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-zbpp9i

#### What is the use-case or motivation for changing an existing behavior?
--

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6, Material 6.3.0

#### Is there anything else we should know?
--

**Comment by alexberkut** [comment]
I found possible workaround. Use overflow: visible; on parent component. But it doesn't solve the problem when content should be cropped :(

**Comment by paesku** [comment]
face similar issue with badges in combination with chips.
https://stackblitz.com/edit/angular-zaepf5 sure there are several workarounds, nevertheless it would be great if this would work out of the box with chips.

**Comment by NikitaChernykh** [comment]
![image](https://user-images.githubusercontent.com/4335713/57544718-3d8b4680-7326-11e9-8667-0ae7144ced84.png)
Same problem. Overflow hidden creates another problem with ripple going outside of chip borders.

**Comment by MRMokwa** [comment]
Still happening with version 8.2.3

**Comment by andreElrico** [comment]
mat-chip design needs to be optimised in ordner to have

+ a badge with no problem
+ to be used as standalone (without mat-chip-list)

Its a little toooo lightweight design for its use cases.

**Comment by jelbourn** [comment]
I don't see us changing anything for this- implementing the badge as an overlay in order to avoid clipping would be major overkill for such a simple component. It also isn't practical to add extra space in places where badges might appear. We also wouldn't want the badge to affect the layout of the element it's augmenting. Based on that, it comes down to the app adding padding to the augmented element to accommodate the badge.
