### ISSUE TITLE
Search Keyup Event not compatible with latest Data-Table-Source Schematics

### ISSUE THREAD

**Issue by JoshWilliams92** [angular/components#12424]
#### Method 1
```ts
applyFilter(filterValue: string) {
  this.dataSource.filter = filterValue.trim().toLowerCase();
}
```
Error = `Property 'filter' does not exist on type DataTableDataSource`
#### Method 2
```ts
applyFilter(filterValue: string) {
  this.dataSource.data.filter = filterValue.trim().toLowerCase();
}
```
Error = `Type '{ <S extends DataTableItem>(callbackfn: (value: DataTableItem, index: number; array: DataTableItem is not assignable to type 'string' (parameter) value: string`

#### What is the expected behavior?
Data should be filtered through search bar as expected through data table filter example on main docs

#### What is the current behavior?
Errors thrown in the class but the app loads without search functionality through the keyup method.
#### What is the use-case or motivation for changing an existing behavior?
Apply search filter mechanism with latest table schematics when used with data-source file.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Windows 10 64 bit OS, Angular Version 6, Material Version 6.4.1, Typescript Version 2.7.2

**Comment by Splaktar** [comment]
Can you please provide a Stackblitz demo of this issue?

**Comment by manklu** [comment]
Have a look at the filter example from the documentation.

https://material.angular.io/components/table/examples
https://stackblitz.com/angular/rnmrpyxdvoe?file=app%2Ftable-filtering-example.ts

**Comment by Splaktar** [comment]
@manklu I tried out your Stackblitz but it doesn't throw the error mentioned in Method 1 of the OP.

**Comment by Splaktar** [comment]
@JoshWilliams92 Can you please provide a reproduction via Stackblitz and reproduction steps?

**Comment by jelbourn** [comment]
Closing for lack of reproduction
