### ISSUE TITLE
Website documentation: reference Angular Flex Layout project

### ISSUE THREAD

**Issue by jorluiseptor** [angular/components#12489]
#### Bug, feature request, or proposal:
While building my current app and after spending hours reading through the documentation, I couldn't find references to layouts, e.g. grid layout, columns, responsive design breakpoints. After asking in a couple of Slack and Gitter channels, I was pointed to https://github.com/angular/flex-layout/wiki. I guessed that Angular Material didn't want to reinvent the wheel because of it. If _in fact_ Angular Material doesn't plan to create its own grid layout API, I propose referencing the Angular Flex-layout project from the Material website so that users like me don't go crazy trying to figure this out.

#### What is the expected behavior?

I suggest adding a link for Responsive Layout (or better name) that explains how Material can be used with the Angular Flex Layout project and link to it (https://github.com/angular/flex-layout/wiki). 

#### What is the current behavior?

There's no reference to this, or if there is, it is not presented well. I almost discard Material altogether for Bootstrap or another.

**Comment by D2KX** [comment]
I have seen this way too on reddit and elsewhere not to support this idea. People really, really struggle to find Flex-Layout (which btw. now also has a CSS Grid Module - which even fewer people will know).

**Comment by shamilovtim** [comment]
Hello,

The docs are still confusing on this. Do I need to install flex layout separately? It's not clear.

**Comment by blyndcide** [comment]
I would rather go the other way.  Only mention angular/flex-layout with a note explaining it's a weird side project that's still in beta for some reason.  Remove the note once it follows the release cadence with the rest of angular's projects.

**Comment by crisbeto** [comment]
I believe that this will be covered on a more general level by the "Modern CSS" point in the roadmap: https://angular.io/guide/roadmap#modern-css. I'm closing this issue since this isn't the repository for flex-layout either.
