### ISSUE TITLE
[mat-select] Maximum call stack size exceeded in select with 1000+ options

### ISSUE THREAD

**Issue by diegomaninetti** [angular/components#12504]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Select works without errors

#### What is the current behavior?
Select throws "ERROR RangeError: Maximum call stack size exceeded" when populated with 1000+ options

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-b2afph
Just open page and see error in console.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.1.1
angular/material 6.4.2
chrome 68 on windows.

**Comment by epotyomkin** [comment]
Any updates on this issue?

**Comment by aymenftiti** [comment]
it is reproductive for me with 400+ options !! is there any updates ?

**Comment by osipenkom** [comment]
Guys, any updates on this?

**Comment by sAng20** [comment]
hello guys, any fix or workaround on this? Thanks.

**Comment by barthinator** [comment]
This is an issue for me as well. Trying to add 4000 items in a patchValue call and just get a maximum stack size error...

**Comment by poonamsaroj** [comment]
Hey guys, any updates for this bug, I am also getting this issue of "RangeError: Maximum call stack size exceeded".
