### ISSUE TITLE
Doc missing on mat form input 

### ISSUE THREAD

**Issue by tatsujb** [angular/components#12508]
#### Bug, feature request, or proposal:

Documentation missing 

#### What is the current behavior?

over here : https://material.angular.io/components/form-field/overview

there is no mention of how to programatically set/edit/prefill a mat-input-field from the Typescript side.

and since you're deprecating  `ngModel` the user has no idea how to do that nowadays. https://next.angular.io/api/forms/FormControlName#use-with-ngmodel

I had no idea how to do that.

I found this : https://toddmotto.com/angular-2-form-controls-patch-value-set-value#formcontrol-patchvalue--setvalue

and it works : 

```
this.options.controls['porStatus'].setValue(this.selection['porStatus']);
this.options.controls['poCollabPromDt'].setValue(this.datePipe.transform(new Date(this.selection['poCollabPromDt']), 'yyyy-MM-dd', 'fr'));
this.options.controls['poCollabPromQty'].setValue(this.selection['poCollabPromQty']);
this.options.controls['poSupAckNumber'].setValue(this.selection['poSupAckNumber']);
this.options.controls['poCollabComment'].setValue(this.selection['poCollabComment']);
```

perhaps consider updating your doc to include an example of setValue use.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6

**Comment by mmalerba** [comment]
The Angular Material documentation assumes familiarity with the Angular Framework documentation (or that people will consult it for information on the relevant parts). In this case, that should be covered by the [Angular Forms documentation](https://angular.io/start/start-forms)
