### ISSUE TITLE
fix(mat-selection-list): do not allow ctrl + a when mat-selection-list is disabled

### ISSUE THREAD

**Issue by steve-todorov** [angular/components#12542]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When a `mat-selection-list` element is `[disabled]=true`, it should not be possible to use `ctlr + a` to select/deselect options.

#### What is the current behavior?
If you click on an option and then press `ctrl + a` it selects/deselects all disabled elements.

#### What are the steps to reproduce?
[Demo](https://stackblitz.com/edit/mat-selection-list-bug-5gy5au?file=app/app.component.html)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: `6.0.8`
Material: `<= 6.4.2`
Chrome: 68

**Comment by crisbeto** [comment]
Should've been resolved by https://github.com/angular/components/pull/18885.
