### ISSUE TITLE
Mat-Checkboxes in CDK-Table rendering differently in various browsers

### ISSUE THREAD

**Issue by flipZomb** [angular/components#12565]
#### Bug, feature request, or proposal
Think this might be a bug

#### What is the current behavior?
Have a cdk-table with mat-checkboxes as a select colum, that is rendering differently in the various browsers (see linked StackBlitz).

EDGE and IE are ok when using this workaround

.mat-checkbox{
  display: inline-flex;
}

![image](https://user-images.githubusercontent.com/33517613/43790834-1877b8e6-9a74-11e8-93a3-e798fd59dee1.png)

In Firefox 61.0.1 (64-Bit) the checkbox is missaligned vertically (i.e. a bit lower on line that it should be).
![image](https://user-images.githubusercontent.com/33517613/43790897-40b31fb2-9a74-11e8-8c74-b89101cc3409.png)

In Chrome Version 68.0.3440.84 it is missaligned and also displaces verticaly when clicked. The latter seems to be associated with this css

cdk-header-cell, cdk-cell {
    flex: 1;
    overflow: hidden;
    word-wrap: break-word;
}  

This workaround, which I found here does not solve the issue in chrome, altought it does solve a slighter displacement issue in EDGE.

.mat-checkbox{
  display: inline-flex;
}

![image](https://user-images.githubusercontent.com/33517613/43791068-c55e43cc-9a74-11e8-84b9-82c7e4f92722.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-8g96hx?file=app%2Fcdk-table-basic-example.css

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 6.4.2
angular 6.1.1

**Comment by flipZomb** [comment]
Seems putting the checkboxes in a div (class = sel) and using this css sort of makes it a bit better.

.sel{
   display: flex;
   justify-content: center;
}

.mat-checkbox{
  display: inline-flex;
  margin: 1px;
}

**Comment by egozavr** [comment]
I've noticed strange step of bottom line on [mat-table doc page](https://material.angular.io/components/table/overview#selection).

![image](https://user-images.githubusercontent.com/2705355/68219544-399b6100-fff7-11e9-8eae-41ab0501b9e4.png)

Chrome devtools show that `td` with checkbox is a bit higher than without one:
![image](https://user-images.githubusercontent.com/2705355/68219859-c0e8d480-fff7-11e9-930a-f495a51731d5.png)
![image](https://user-images.githubusercontent.com/2705355/68219900-ce05c380-fff7-11e9-8043-f93453081ed9.png)

**Comment by andrewseguin** [comment]
Seems this is a CSS issue that can be resolved. I dont foresee us being able to make any changes to the cells to accommodate this case. 

W.R.T. to the checkbox causing weird height issues, Im not currently seeing that but if it remains an issue on your side, please open an issue so we can look into it
