### ISSUE TITLE
For text-fields with required attribute, remove space before asterisks (required text indicator)

### ISSUE THREAD

**Issue by fmax32** [angular/components#12721]
#### Bug, feature request, or proposal:
Based on Material Design guidelines, there should be no space after placeholder. Guidelines here: https://material.io/design/components/text-fields.html#anatomy

#### What is the expected behavior?
Expected to not have space between "email" and the asterisk "`*`", like this: "`email*`"

#### What is the current behavior?
There is a space after placeholder and before asterisk 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://angular-v6uj63.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Following Material Design guidelines: https://material.io/design/components/text-fields.html#anatomy

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.*
Material: 6.*
OS: any
Browser: any

#### Is there anything else we should know?
-

**Comment by amysorto** [comment]
There is no space before the asterisk anymore in the MDC based form field coming soon in v15.
