### ISSUE TITLE
feat: Make dialog position strategy configurable through MatDialogConfig

### ISSUE THREAD

**Issue by fmavdb** [angular/components#12744]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Pass an extra property to MatDialogConfig containing an Overlay Position Strategy class and use it.

#### What is the current behavior?
The position strategy always defaults to: this._overlay.position().global(). See https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts

#### What is the use-case or motivation for changing an existing behavior?
I would like to attach a dialog to an element using the FlexibleConnectedPositionStrategy. Example behaviour we could achieve: https://material.io/design/components/data-tables.html#behavior 
Small edit dialog / large edit dialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by crisbeto** [comment]
If we did this, the `position` property from the `DialogConfig` won't work anymore.

**Comment by crisbeto** [comment]
The issue is that top/bottom/left/right options are all tightly coupled to the `GlobalPositionStrategy` and we won't be able to map them to whatever other strategy you provide. Another issue is that everything else is set up for the dialog to be a global overlay (focus behavior, animations etc.).

**Comment by fmavdb** [comment]
Do you perhaps have any other suggestions to achieve the desired effect on https://material.io/design/components/data-tables.html#behavior with small/large edit dialogs? Perhaps inheriting `MatDialog` could be a possible solution, however most methods are private :/ 
I experimented with basic `Overlays` and `FlexiblePositionStrategy` which seems to work fine, except with dialog style/logic missing.

**Comment by devversion** [comment]
Seems like this is working as intended and there are limitations around supporting arbitrary position strategies for the dialog. For other use-cases, as @crisbeto pointed out, the CDK overlay could be used.
