### ISSUE TITLE
[Mat-form-field] Input-text jumps in IE11 when setting line-height inside mat-form-field

### ISSUE THREAD

**Issue by maidi29** [angular/components#12769]
The line-height of mat-form-field is initially set to 1.125. When overwriting it with a higher value (e.g. 1.5) it leads to jumping effects in the nested input-element inside the mat-form-field. On focus/blur the text jumps up and down.

#### What is the expected behavior?
The input text inside mat-form-field should not jump on higher line-height values in Internet Explorer.

#### What is the current behavior?
The input text inside mat-form-field jumps on higher line-height values than the initial in IE11.

#### What are the steps to reproduce?
Open this stackblitz in Internet Explorer and type something in the input field. On each blur/focus the input text jumps:
[https://stackblitz.com/edit/angular-z1efak](https://stackblitz.com/edit/angular-z1efak)
When you remove the line-height-property it will not jump.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Version 6, Angular Material Version 6.4.0

**Comment by tobias74** [comment]
Does this article help in any way? [http://joshnh.com/weblog/line-height-doesnt-work-as-expected-on-inputs/](http://joshnh.com/weblog/line-height-doesnt-work-as-expected-on-inputs/)

**Comment by Splaktar** [comment]
@maidi29 does Tobias74's solution work for you? Is this still a problem that you are seeing?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
