### ISSUE TITLE
MatChipList selected to Observable

### ISSUE THREAD

**Issue by Bored-Bohr** [angular/components#12792]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
convert MatChipList's `selected` to be an Observable.

#### What is the current behavior?
MatChipList's `selected` is just a `MatChip[] | MatChip`

#### What are the steps to reproduce?
Use MatChipList's `selected`

#### What is the use-case or motivation for changing an existing behavior?
The user should not maintain when the value is changed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.5
@angular/cli                      6.0.8
@angular/material                 6.4.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because:
1. Changing it to be an observable will be a breaking change with no clear benefit.
2. We already have a `change` observable.
