### ISSUE TITLE
Add options to default color properties

### ISSUE THREAD

**Issue by jelbourn** [angular/components#12815]
For components that support a `color` property, we should ensure that the options provider for that component allows setting the default color.

**Comment by wmay1991** [comment]
I'll pick it up

**Comment by rossgardt** [comment]
Should this be covered by the `mixinColor` function? ([link](https://github.com/angular/material2/blob/master/src/lib/core/common-behaviors/color.ts#L30))

The function is already used in several places.

**Comment by jelbourn** [comment]
The feature here is to add an options injectable ([example](https://github.com/angular/material2/blob/a7df1d0a3bca5bb0905f9ec5ed466e91ea770cbf/src/lib/menu/menu-directive.ts#L42-L61)) that sets a global default for the radio buttons.

**Comment by jerome-nelson** [comment]
Is anyone still working on this? If not I'm ok to pick it up

**Comment by jelbourn** [comment]
Probably safe to grab

**Comment by jerome-nelson** [comment]
Ok done so. Thanks

**Comment by jerome-nelson** [comment]
So I have some sample code here:
https://github.com/angular/material2/compare/master...jerome-nelson:default-options-to-color-inputs?expand=1

**Questions**
1. Is this only for `RadioButton`? There are other components like `matFormField` which also have color inputs.
2. Should this be extended to cover all override-able options? (I'm not entirely clear if this is a valid question)
3. How should the provider override affect the component input? i.e `<mat-radio-button [color]="warn"></mat-radio-button>`

**Comment by jelbourn** [comment]
It would be for any component that has a `color` input, but the PRs should be one component at a time. I wouldn't expand to other settings at this stage.

An explicit input binding should always override the default coming from the provider.
