### ISSUE TITLE
Feature request: emoji picker

### ISSUE THREAD

**Issue by narthur157** [angular/components#12853]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Some way to input emojis on laptop/desktop

#### What is the current behavior?
It's especially hard to make emoji input work with Angular material. 
Unicode emojis don't really work on desktop (lots of squares, at least on my W7 machine)

The most popular solution looks like this https://stackoverflow.com/a/29611863/1340046
The approach is to give a `div` the `contenteditable` attribute and then put img tags alongside text to make the emojis. 

It would not be too hard to make this work, all we need is a material input which is not a "real" input element. Then, material could use or fork an emoji picker like this one https://github.com/typectrl/ngx-emoji-mart which I've tested and generally works. It doesn't include the toggle switch, however, to open the emoji picker popup.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
n/a

#### What is the use-case or motivation for changing an existing behavior?
Emojis are quite popular, and this requires a lot of hacks to do currently

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All currently

**Comment by wynfred** [comment]
Now you can use this [directive](https://github.com/wynfred/mat-contenteditable). It implements MatFormFieldControl to make `contenteditable` compatible with MatFormField.

**Comment by jelbourn** [comment]
Closing this since I don't realistically see us prioritizing less widely used components like this for the foreseeable future.
