### ISSUE TITLE
Tooltip doesn't disappear on touch screens and android mobile. 

### ISSUE THREAD

**Issue by HarelM** [angular/components#12924]
#### What is the expected behavior?
Tooltip should disapear

#### What is the current behavior?
Tooltip stays when using touch

#### What are the steps to reproduce?
the api example of tooltip
https://stackblitz.com/edit/angular-tooltip-statyon?file=app%2Ftooltip-modified-defaults-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest - see stack blitz

#### Is there anything else we should know?
The tooltip instance is still null when the `hide` function gets called on touchend...
![image](https://user-images.githubusercontent.com/3269297/44902825-a6d8a580-ad13-11e8-972f-7e3ddfdeb0c9.png)

**Comment by HarelM** [comment]
Any updates on this? this is kinda production stopper for us...

**Comment by adarshaj** [comment]
Same issue, vanilla angular material's tooltip won't go away on touch screens. any eta on this one? or workarounds?

**Comment by UmutAkkaya** [comment]
Any update on this?

**Comment by a616101** [comment]
Same issue...
use 8.0.2

**Comment by HarelM** [comment]
I'm guessing this issue can be closed as it doesn't reproduce on latest versions.
