### ISSUE TITLE
Angular Material typography sizing is inconsistent w/ Material spec

### ISSUE THREAD

**Issue by takamori** [angular/components#12974]
#### Bug, feature request, or proposal:
Angular Material does not use the same typography size ranking as the Material spec.
https://material.io/design/typography/the-type-system.html#type-scale clearly shows Body 1 as larger and darker than Body 2.
https://material.angular.io/guide/typography indicates that body-2 is darker than body-1.

This can be seen in the source code as well. https://github.com/angular/material2/blob/master/src/lib/core/typography/_typography.scss#L24
Similar issues apply to other types of font.

#### What is the expected behavior?

That it would be consistent w/ spec.

#### What is the current behavior?

It is ranked in inverse order.

#### What are the steps to reproduce?
1. View the documentation for the Material spec.
2. View the Angular Material docs.
3. View the corresponding source code.

#### What is the use-case or motivation for changing an existing behavior?
Consistency.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

**Comment by crisbeto** [comment]
The current typography scale is based on the previous iteration of the Material Design spec.

**Comment by jfcere** [comment]
I am not an expert in that field but I think the `font-size` and `letter-spacing` are also wrong according to Material Design Spec: https://material.io/design/typography/the-type-system.html#type-scale

For example, `mat-display-1` has a font-size of 112px while according to MD spec it should be 96px.

Am I wrong?

**Comment by PapaNappa** [comment]
Is there any plan or strategy on aligning Angular Material's theming with the Material spec?
I find the current spec more intuitive, esp. from a web development perspective.

Is this potentially also part of the larger refactoring mentioned in https://github.com/angular/components/issues/15580#issuecomment-477755555?

**Comment by jelbourn** [comment]
Yes, this should be included in our larger refactoring to base most of the components on top of MDC web

**Comment by kennydifiore** [comment]
It's also missing the "overline" style completely.

**Comment by Maximaximum** [comment]
I really hope that Angular material will move to the latest Material design spec. Working with 2014 spec is extremely, extremely confusing. Especially given that Angular material docs don't even mention that they're using the outdated spec

**Comment by crisbeto** [comment]
@mmalerba should this issue be closed by your recent typography changes?

**Comment by jelbourn** [comment]
The recent changes are only in material-experimental right now. We can look at moving them into stable decoupled from MDC component rollout in a minor release post v12. #22366 does update the docs to explicitly say that we're still on the 2014-era levels.

**Comment by kaltepeter** [comment]
It's really helpful to see the documentation reflect which Material design standard is used, now stating 2018. It's still a bit of a challenge being out of date with the Material design spec.

A use case: My company is using micro frontends with more than just angular as a framework and it would be really nice to adopt a consistent baseline across @angular/material and MUI. We have leaned on the material design spec assuming this would do that.

For example, if angular adopted the v2 spec https://m2.material.io/design/typography/the-type-system.html#type-scale we would get alignment until the v3 becomes standard and frameworks adopt it. 

A question that may help is, what's the roadmap for adopting newer versions of the material design spec?

**Comment by amysorto** [comment]
Closing since components have M3 support as of 17.2
