### ISSUE TITLE
matTooltip not working with ngComponentOutlet and custom injector

### ISSUE THREAD

**Issue by g2timo** [angular/components#12990]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The tooltip is shown on hover.

#### What is the current behavior?
The tooltip is not shown.

#### What are the steps to reproduce?
When I use matTooltip in my application is works just fine. I can also use it in a component I render with *ngComponentOutlet. But once I add an injector form the ComponentOutlet, the tooltip stops working.
https://stackblitz.com/edit/angular-material2-issue-gw5dd5

#### What is the use-case or motivation for changing an existing behavior?
This seems to be a bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Noticed it in Angular 5, but I can reproduce the bug with latest versions used in the template stackblitz. 
Using Chrome.

**Comment by crisbeto** [comment]
The problem is that since you're returning it in a function, each change detection will return a brand new injector. Here's a example that works by reusing the injector. https://stackblitz.com/edit/angular-material2-issue-io8tn6
