### ISSUE TITLE
checkbox ripple doesn't overflow anymore under v.6.2.1

### ISSUE THREAD

**Issue by tatsujb** [angular/components#13005]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

![image](https://user-images.githubusercontent.com/5132359/45167914-72288a80-b1fa-11e8-8012-174b284c0886.png)

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/5132359/45167949-7fde1000-b1fa-11e8-97ea-c1d857ae4955.png)

As you can see above, the ripple is cut off by the following line in the table and this is WITH the fix that was suggested for ripple : 
https://github.com/angular/material2/issues/8600#issuecomment-358895611

`mat-cell.mat-cell, mat-header-cell.mat-header-cell { overflow: visible; }`

which used to fix it but doesn't in  v.6.2.1

not only that but this "fix", this will now also break horizontal alignment of the texts in each row of the table (so I don't use it) : 

![image](https://user-images.githubusercontent.com/5132359/45169431-e4e73500-b1fd-11e8-9f2d-4767bae151ae.png)

UPDATE : I've worked out that this doesn't occur with the new `<td>` tags I mentioned in this issue : https://github.com/angular/material2/issues/12753

but that's a real problem for me, I need help switching from one to the other as so far every attempt I've made has failed.

#### What are the steps to reproduce?

StackBlitz : https://stackblitz.com/edit/angular-material2-issue-6jyqu4

you'll notice this stackblitz contains the checkbox offset bug mentioned in the first thread I linked but I don't personally have this. my checkboxes don't move they just fail to overflow their ripple onto the line below.

#### What is the use-case or motivation for changing an existing behavior?

the ripple effect of the checkbox is pretty and is an important part of material's visual identity

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

material v.6.2.1

**Comment by egalitarian11** [comment]
Have you found any workarounds for this issue?

**Comment by tatsujb** [comment]
I upgraded versions.

**Comment by crisbeto** [comment]
The last comment sounds like the issue was resolved. Closing.
