### ISSUE TITLE
Proposal: Given examples on styling the Angular Material. And put it on material.angular.io

### ISSUE THREAD

**Issue by Nyconing** [angular/components#13049]
Proposal on Examples on styling the Angular Material

When we are new to this platform/ series. We needs **working project example** that to get rid of doubts.

As I can see, `material.angular.io` is given working project example on every components. I hope those examples will having on Styling section, **too**. Because styling is the most important part on design isnt?

The guides on Styling Angular Material currently on website is kind of **unclear**.

For my case, I spend 2 days to figure out how SASS(but actually SCSS) work, googling, asking... implementing, testing...... and failed. 〒▽〒 I ended up by overriding `.mat-form-field-appearance-legacy .mat-input-element`. And you can actually found **a lot of unsolved questions** asking about styling in StackOverflow.

I think this will **take only few couple of minutes** on creating example project for those who already mastering Angular Material. So please.

**Comment by twerske** [comment]
Closing as we're revamped our guides to provide more examples of theming here: https://material.angular.io/guide/theming
