### ISSUE TITLE
Improve typography documentation

### ISSUE THREAD

**Issue by mischkl** [angular/components#13075]
#### Bug, feature request, or proposal:
Documentation feature request

#### What is the expected behavior?
The description of the typography should match up with the Material Design spec docs that it links to. A table showing previews of what the various typography classes look like along with their font size and weight (at a minimum) should be available. See https://material.io/design/typography/#type-scale for an example of what this could look like.

Even something as simple as this: https://stackblitz.com/edit/angular-material-typography-demo would be a great help.

I did find an already existing demo page, but for some reason it doesn't seem to be linked from anywhere else in the docs, so the rendered version of it isn't viewable anywhere. Also it doesn't list the font size/weight. Still, even just including this file in the current docs would be a great improvement over the current state. https://github.com/angular/material2/blob/master/src/demo-app/typography/typography-demo.html

#### What is the current behavior?
There is just a list of classes, with no previews or info about font size/weight, and descriptions that don't match up to the linked Material Design spec docs.

#### What are the steps to reproduce?
Look at https://material.angular.io/guide/typography

#### What is the use-case or motivation for changing an existing behavior?
It is totally opaque what the outcome of using any of the typography classes will be. The current version of the linked Material Design spec docs doesn't match up to the current state of Angular Material in terms of naming and descriptions, so is basically useless.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by jelbourn** [comment]
Closing since the typography guide was rewritten for Angular v12 with updated information
