### ISSUE TITLE
Spacing between icon and text in mat-list-item

### ISSUE THREAD

**Issue by calebegg** [angular/components#13085]
For a single-line mat-list-item, the spacing between the icon and the text of the item is incorrect

Acutal:
![image](https://user-images.githubusercontent.com/782920/45387504-3ae42000-b5e4-11e8-8555-ff8058aa2ed4.png)

Expected:
https://material.io/design/components/lists.html#specs (32 px)

**Comment by crisbeto** [comment]
How are you providing the icon to the list item? In order for it to be picked up correctly by the list, you have to set the `mat-list-icon` attribute on it. Here's an example from our demo app that shows it with the proper margin:

![angular_material_-_google_chrome_2018-09-12_21-41-33](https://user-images.githubusercontent.com/4450522/45449212-cfc64680-b6d4-11e8-9815-54bd619775c5.png)

**Comment by calebegg** [comment]
(I got an email about a comment that hasn't appeared here yet for some reason)

Yes, I'm using mat-list-icon. Here's a stackblitz repro:

https://stackblitz.com/edit/angular-eyxegu?file=app/list-overview-example.html

**Comment by calebegg** [comment]
Friendly ping @josephperrott @crisbeto

**Comment by devversion** [comment]
Yeah, I double-checked and this is fixed with the MDC-based implementation of the list: #16255

Here is an example: https://mmalerba-demo.firebaseapp.com/mdc-list.

**Comment by amysorto** [comment]
The spacing between the icon and text is correct in the MDC based list component coming soon in v15.
