### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError thrown when switching between two mat-menus with matMenuTriggerDatadifferent 

### ISSUE THREAD

**Issue by RokiFoki** [angular/components#13165]
#### What is the expected behavior?
ExpressionChangedAfterItHasBeenCheckedError should not be thrown on switching between submenues that are using the same mat-menu element with different matMenuTriggerData.
![repro](https://user-images.githubusercontent.com/9476596/45622491-779c9500-ba84-11e8-90af-c44907a27f97.gif)

#### What is the current behavior?
The error is thrown

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-nevxe3-cafesh?file=app/nested-menu-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
![image](https://user-images.githubusercontent.com/9476596/45622530-a1ee5280-ba84-11e8-8a70-f34238351397.png)

#### Is there anything else we should know?
It is regression of #12194

**Comment by crisbeto** [comment]
I wasn't able to reproduce it against the latest code in master. Closing.
