### ISSUE TITLE
Uncessary vertical scrollbar in a textarea inside a MatFormField.

### ISSUE THREAD

**Issue by tofesath** [angular/components#13161]
#### Bug, feature request, or proposal:
The vertical scrollbar is displayed, when count of rows does not reach `maxRows`.

#### What is the expected behavior?
The vertical scrollbar is displayed only if count of rows is more than max `maxRows`.

#### What is the current behavior?
The vertical scrollbar is visible, when count of rows is between `minRows` and `maxRows`.

#### What are the steps to reproduce?
Min rows sets to 2.
Max rows sets to 5.
Add some text in a 3 rows, everything is correct. 
The vertical scrollbar is visible on a 4th  row (something wrong) but on 5th row is invisible. (correct).
https://stackblitz.com/edit/angular-v6bw5l

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular - 6.0.1, material - 6.2.0, browser - chrome

**Comment by crisbeto** [comment]
I wasn't able to reproduce it. Here's what a textarea with 4 rows looks like for me:
![angular-v6bw5l_-_stackblitz_-_google_chrome_2018-09-17_19-29-20](https://user-images.githubusercontent.com/4450522/45639495-73866c80-bab0-11e8-9d95-dea6a69be188.png)

**Comment by tofesath** [comment]
Well, it seems that I found where might be the problem. The issue seems to depend on the text size set in the Windows  (`Control Panel` ->  `Appearance and Personalization` -> `Display` on Windows 7). When I set this to `Smaller - 100%`, the issue does not appear; when I set the text size in Windows to `Medium - 125%` (which is the default option), the issue occurs:

![multi-line-bug](https://user-images.githubusercontent.com/33834653/45671912-0d88fc00-bb27-11e8-97b4-397cff202459.PNG)

**Comment by manklu** [comment]
It's enough to zoom in the browser.

At 110% Zoom

![image](https://user-images.githubusercontent.com/22273143/45716326-e2d68c00-bb96-11e8-9f4c-f1c09b5d762e.png)

Looks like a rounding problem to me.

**Comment by danielronnkvist** [comment]
Seems to be caused by the fix for #10376 as pointed out by @jkruse [here](https://github.com/angular/material2/issues/10376#issuecomment-414571739).

**Comment by Mike--S** [comment]
Guys seems like I figured out what the problem... Just try to set box-sizing: content-box to textarea element and everything goes well then. Recalculation doesn't take into account box-sizing: border-box.

**Comment by tbunique** [comment]
@Mike--S that fix doesn't work for me.

I'll just hide the overflow until the problem is fixed.

**Comment by Mike--S** [comment]
> @Mike--S that fix doesn't work for me.
> 
> I'll just hide the overflow until the problem is fixed.
As for box-sizing - it was a specific problem on my project, because every element has default style box-sizing: border box. I think this is very frequent case.
As for you, I guess you have increased font scaling on operating system level. I can reproduce this bug on stackblitz with 125% font size, but when I apply 100% font size bug is not reproduced with latest chrome, win 10.

**Comment by rtsdgim** [comment]
```css
textarea.mat-input-element {
    padding: 0;
    margin: 0;
}

.mat-form-field {
    line-height: normal;
}
```

**Comment by sergiubologa** [comment]
The workaround that works for me is to set a different top and bottom padding on the textarea:

the default is
```css
textarea.mat-input-element {
    padding: 2px 0;
}
```

and I've changed it to
```css
textarea.mat-input-element {
    padding: 3px 0;
}
```

**Comment by teoeter** [comment]
For me the issue was that i had a global
/* Box-sizing border-box */
* {
    box-sizing: border-box;
}

after setting it to initial the component worked as intended.

**Comment by mmalerba** [comment]
Marking this as P5 because we've had a lot of changes trying to get this to work on every combination of browser and zoom level. What we have now is working pretty well in most cases

**Comment by Smip** [comment]
A possible solution to the problem is to set `line-height` in pixels. E.g.: line-height: 16px;

**Comment by mmalerba** [comment]
I just checked this again with the latest Angular Components version, zoom levels 100% - 150% and cannot reproduce it. Therefore closing
