### ISSUE TITLE
Mat select- problem in selecting all duplicate values upon loading

### ISSUE THREAD

**Issue by harshabada** [angular/components#13179]
#### What is the expected behavior?
mat-select: duplicate values should be selected upon loading

#### What is the current behavior?
mat-select: duplicate values is not  selected upon loading

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

Angular 5, mateiral 5.*.*

#### Is there anything else we should know?
if there are three duplicate values only one of the value selected and the rest two values are not selected

**Comment by harshabada** [comment]
https://angular-brthnz-who7mp.stackblitz.io

**Comment by macjohnny** [comment]
@harshabada I suggest you to use different `value` attributes if you want to show the same item multiple times in the list

**Comment by crisbeto** [comment]
This definitely isn't being handled correctly at the moment. It'll be fixed by #13361.
