### ISSUE TITLE
Add Event Before Changing Page or PageSize

### ISSUE THREAD

**Issue by randalvance** [angular/components#13193]
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behavior?
Please add an event that will emit just before the page index and page size is changed.

#### What is the current behavior?
Although I was able to prevent the user from changing the current displayed data, I can still interact with the paginator and change the page and pagesize, they will simply be ignored and data displayed will remain the same.

#### What is the use-case or motivation for changing an existing behavior?
This will be an opportunity to do something before changing the page, such as showing a message box when there are invalid controls displayed by the table. The user then cannot change the page and page size.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular-devkit/architect 0.7.5
@angular-devkit/build-angular 0.7.5
@angular-devkit/build-optimizer 0.7.5
@angular-devkit/build-webpack 0.7.5
@angular-devkit/core 0.7.5
@angular-devkit/schematics 0.7.5
@angular/cdk 6.4.7
@angular/cli 6.1.5
@angular/material 6.4.7
@ngtools/webpack 6.1.5
@schematics/angular 0.7.5
@schematics/update 0.7.5
rxjs 6.3.1
typescript 2.9.2
webpack 4.9.2

**Comment by crisbeto** [comment]
There's a pending PR for allowing the paginator to be disabled (see https://github.com/angular/material2/pull/13146) which could be an alternate way of handling your use case.
