### ISSUE TITLE
Spacing between button and title in toolbar

### ISSUE THREAD

**Issue by calebegg** [angular/components#13225]
There should be 24px of spacing between icon buttons, and 32px between an icon button and the title.

https://material.io/design/components/app-bars-top.html#specs

Right now, there's no default spacing.

**Comment by calebegg** [comment]
I guess as much as possible, I'd like the framework to take care of instances where I'd otherwise just have to look up the spec and blindly apply it (like I did here). I generally file bugs like this when I've come up with a global override that takes care of the issue and could thus be upstreamed and take care of the issue for more people.

To me, this seems similar to the spacing in a mat-list-item with an avatar, where it was so nice that I could just stick mat-avatar on my img and it's just magically right.

Maybe there could be a mat-toolbar-action class or selector for adding the appropriate spacing?

```
.mat-toolbar-action:not(:last-child) {
  margin-right: 24px;
}
.mat-toolbar-action + h1 {
  margin-left: 12px;
}
```

It's totally up to you though, of course. You've got way more knowledge of what has/hasn't worked in the past, and if you think this isn't worth pursuing I'm fine with that.

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Going to close this since we're not going to do much more with `mat-toolbar` going forward since the Material Design spec moved away from it. We might do something different for a separate "top app-bar", but TBD on that front.
