### ISSUE TITLE
StandardFromField and FillFormField Underline flicker on MS-Edge

### ISSUE THREAD

**Issue by wuchtig** [angular/components#13276]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
StandardFromField and FillFormField Underline flicker on mouseover/mouseout on MS-Edge

#### What are the steps to reproduce?
https://material.angular.io/components/form-field/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6
Typescript: 2.7.7
Windows 10
MS-Edge 42.17134.1.0

**Comment by crisbeto** [comment]
I don't see it. Can you elaborate?

![demo2](https://user-images.githubusercontent.com/4450522/45927334-fafd3100-bf31-11e8-89de-ab291a6bd462.gif)

**Comment by andrewseguin** [comment]
Closing since this likely affected pre-Chromium edge. Feel free to reopen issue if the problem still exists
