### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by anderflash** [angular/components#1331]
#### Bug, feature request, or proposal:

Feature request
#### What is the expected behavior?

[Range Slider](https://jqueryui.com/slider/#range)
#### What is the current behavior?

We manipulate a single value.
#### What are the steps to reproduce?

Not applicable
#### What is the use-case or motivation for changing an existing behavior?

For input a range (start and end) besides just one value. Currency, date, time... several motivations.
#### Which versions of Angular, Material, OS, browsers are affected?

Latest
#### Is there anything else we should know?

I think JQuery UI also could be a good source of new UI features for material2.

**Comment by razvanmitre** [comment]
any news on this?

**Comment by mmalerba** [comment]
I don't think this is a priority for us since its not part of the material spec

**Comment by anderflash** [comment]
I understand. It would be considered a future enhancement. I see [Ionic Range](https://ionicframework.com/docs/v2/api/components/range/Range/) could be a good inspiration (there is an example - see _structure_ field). And it's on top of Angular 2.

**Comment by BamiGorengo** [comment]
i realy realy hope that they implement it, i know people who use ionic, only because in material is no range slider...

**Comment by arkhamvm** [comment]
Any news? Really nice to have.

**Comment by runov001** [comment]
+1

**Comment by mmoravcik** [comment]
+1

**Comment by CramericaIndustries** [comment]
+1

**Comment by talentedandrew** [comment]
+1

**Comment by ubarsaiyan** [comment]
+1

**Comment by Tiedye** [comment]
+1 this is really important for a lot of applications

**Comment by shyamal890** [comment]
+1

**Comment by mladilav** [comment]
Any news?

**Comment by chicojunior** [comment]
News about?

**Comment by troelssiggaard** [comment]
+1

**Comment by ghal** [comment]
+1

**Comment by alexlevy0** [comment]
+ 1

**Comment by KKHAN1991** [comment]
+1

**Comment by hatem20** [comment]
+1

**Comment by dniadzelka** [comment]
+1

**Comment by franckie20** [comment]
+1

**Comment by odahcam** [comment]
Good inspiration: https://github.com/leongersen/noUiSlider

**Comment by Chan4077** [comment]
@troelssiggaard @ghal @alexlevy0 @KKHAN1991 @hatem20 @dniadzelka @franckie20 Please don't spam others who have subscribed to this repository with +1s. Just click on the thumbs up emoji on the top post.

**Comment by Raphyyy** [comment]
Hi and sorry for the flood
Any news on this ? It would be really nice to have, for many apps

**Comment by AndyInfin** [comment]
After 1,5 years of this issue opened, MD2 still don't have it? Really?
Maybe someone have a custom realisation of this component (CDK, huh)?

**Comment by Spawnrad** [comment]
I use primeng for the slider range. Hope material add it

**Comment by krag-123** [comment]
Any news?

**Comment by odahcam** [comment]
This is not cool and not usual at all:

![image](https://user-images.githubusercontent.com/3942006/40510867-544bef30-5f74-11e8-8c5c-cf368b7bb596.png)

😞

**Comment by krag-123** [comment]
like this
https://material.io/design/components/sliders.html#usage

**Comment by odahcam** [comment]
Finaly it's on Material spec! 🎉

Ref: https://material.io/design/components/sliders.html?image=https%3A%2F%2Fmaterial.io%2Fdesign%2Fassets%2F10jWM9HrDzPYk8tVVERXuodNy1I6obMf_%2Fsliders-spec-discrete-range.png#implementation

**Comment by mmalerba** [comment]
Bumping the priority since this is part of the spec now. FYI to everyone watching this thread: you may want to follow https://github.com/angular/material2/issues/10774 as well, as it's a pre-req to making the material version

**Comment by shivarajnaidu** [comment]
When we can expect range slider in angular material guys..?

**Comment by GeoffMahugu** [comment]
This feature is very important. Having 2 slides for max and min value is not a user experience i would want

**Comment by kevupton** [comment]
👍 🥇

**Comment by Kiennyo** [comment]
As alternative I've found this component:
https://www.primefaces.org/primeng/#/slider

**Comment by ankitminglani** [comment]
@Kiennyo but the styling is a struggle! were you able to make it look like angular material one or at least ionic?

**Comment by Dzivo** [comment]
Any news on this i see they have no plans for this in the docs

**Comment by PhilippS93** [comment]
Are there any news? Would love this feature.

**Comment by kluevandrew** [comment]
+1

**Comment by greggalbreath** [comment]
+1

**Comment by Dzivo** [comment]
+1

**Comment by jonigl** [comment]
any news?

**Comment by odahcam** [comment]
Maybe you should see #13324

**Comment by PonayMort** [comment]
Thanks @odahcam for your redirection 👍

**Comment by odahcam** [comment]
You're welcome.

**Comment by VagrantAI-c** [comment]
Seems like another concept passed through
https://material.io/design/components/buttons-floating-action-button.html#extended-fab

**Comment by dinukasaminda** [comment]
use my range slider its based on angular material slider and its modifed, with sample angular application
https://github.com/dinukasaminda/angular-material-range-slider

![Capture](https://user-images.githubusercontent.com/16361266/54098022-bcbcd680-43d8-11e9-934f-f1d0be71bfe3.PNG)

**Comment by jelbourn** [comment]
(I'm going through the highest voted issues today an commenting on their status)

We still consider this something that we want to add, but it's still one of the lower-priority features in the backlog (compared to things like virtual scrolling for table, density theming, improving CDK documentation, etc.). As I mentioned in my recent [ng-conf talk](https://youtu.be/4EXQKP-Sihw?t=901), we're doing some work now to integrate [MDC Web](https://github.com/material-components/material-components-web) into our components, so we don't want to rework our slider to support range selections  knowing that the MDC implementation also doesn't support this yet.

**Comment by odahcam** [comment]
Good to see MDC is comming, I hope this change to reduce the amount of work for you guys, so you can create more awesome stuff.

**Comment by AdditionAddict** [comment]
Is there a way to add in Material-UI component to angular?
https://material-ui.com/components/slider/
![image](https://user-images.githubusercontent.com/48436581/60662217-ad640c00-9e53-11e9-87af-611a9a0a1260.png)

**Comment by oktav777** [comment]
@AdditionAddict  unfortunately no :(
I need it so bad too...

**Comment by kirill-chirkov-at-clouty** [comment]
Seems like even Flutter now got range slider. I wonder if this would bump range slider dev priority.
https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf
https://github.com/flutter/flutter/pull/31681?source=post_page---------------------------

**Comment by djabif** [comment]
I solved this issue by using the `ion-range` component from [Ionic Framework](https://ionicframework.com/docs/api/range).
It's super easy to integrate to an angular project.

![Screen Shot 2019-07-30 at 2 39 20 PM](https://user-images.githubusercontent.com/1735814/62151987-efa82e00-b2d7-11e9-8df9-73b545bceda1.png)

**Comment by SvenBudak** [comment]
Read the comment from the guy above me... Did you guys remember what i wrote before 2 years?
https://github.com/angular/components/issues/1331#issuecomment-275187044

**Comment by odahcam** [comment]
Our best hope is try to help https://github.com/angular/components/pull/13324

**Comment by PetrSchmeister** [comment]
I found this: https://stackblitz.com/edit/angular-material-range-slider-kxqxmq

**Comment by chriszrc** [comment]
@PetrSchmeister yes, it uses:

https://angular-slider.github.io/ng5-slider/

This looks like the way to go for now! Thanks!

**Comment by chriszrc** [comment]
> I solved this issue by using the `ion-range` component from [Ionic Framework](https://ionicframework.com/docs/api/range).
> It's super easy to integrate to an angular project.
> 
> ![Screen Shot 2019-07-30 at 2 39 20 PM](https://user-images.githubusercontent.com/1735814/62151987-efa82e00-b2d7-11e9-8df9-73b545bceda1.png)

@djabif I actually am not finding it easy to just integrate a single component from ionic into an already existing angular project, do you have any tutorials or instructions for that?

**Comment by andreElrico** [comment]
+ [working stackblitz mat-range-slider](https://stackblitz.com/edit/angular-qbqwl3?file=src%2Fapp%2Fslider-configurable-example.html)
+ material only
+ same API surface as `mat-slider`
+ I want to wrap it in a library when I find time.

**Comment by chriszrc** [comment]
I ended up using this one:

https://www.primefaces.org/primeng/showcase/#/slider

It was easy to just add that one component, but it's also a bit broken with reactive forms :(

**Comment by francovp** [comment]
Can't believe Flutter Material already got this before Angular that is now in the 10th version.

**Comment by francovp** [comment]
Any milestone when this can be included? Maybe for 10.1 or 11?
Flutter Material got this already, before Angular Material that is now in version 10 :/

**Comment by francovp** [comment]
Flutter gets a [new updated Range Slider today](https://medium.com/flutter/announcing-flutter-1-20-2aaf68c89c75) :)

**Comment by Volftsun** [comment]
any updates? We are waiting for a range slider :)

**Comment by kuatek** [comment]
+1

**Comment by M1Joe** [comment]
@wagnermaciel super excited to see this get assigned to you! Any chance that means you're working this?

**Comment by jelbourn** [comment]
This is being added as part of the MDC-based slider that's currently in progress.

**Comment by patrickacioli** [comment]
+1

**Comment by patrickacioli** [comment]
Waiting for range slider. :)

**Comment by moshtaba** [comment]
jeeeeeeeez it is 2021. after five years still no range slider?

**Comment by crisbeto** [comment]
This is supported now with the slider in the `@angular/material-experimental/mdc-slider` package.

**Comment by NurGuz** [comment]
+1 for Angular 8 here?

**Comment by crisbeto** [comment]
We generally don't port features back to older releases, only fixes high-priority bugs and security issues.

**Comment by GrandSchtroumpf** [comment]
@crisbeto when installing `@angular/material-experimental@latest` the template is still 
```html
<!-- TODO: to be implemented as a part of the new MDC slider -->
```
I've got version ^12.0.2 which seems to be the newest at the time of this comment according to [npm](https://www.npmjs.com/package/@angular/material-experimental). Is there a way to use the version currently on master ? 

![image](https://user-images.githubusercontent.com/8143464/119987429-50344f00-bfc5-11eb-9da9-4cc1995356be.png)

**Comment by crisbeto** [comment]
Sorry, it looks like PRs were actually targeting the next `minor` release which will be 12.1.0. You can either wait for it or install one of the master builds from https://github.com/angular/material-experimental-builds.

**Comment by GrandSchtroumpf** [comment]
I see thanks. Any broad idea when the next minor should be ship ?

**Comment by MattiaMalandrone** [comment]
Any news?

**Comment by crisbeto** [comment]
The range slider is currently available in `@angular/material-experimental/mdc-slider`.

**Comment by nzbin** [comment]
I have written a range slider in the [Angular Material extensions library](https://github.com/ng-matero/extensions).
https://ng-matero.github.io/extensions/components/slider/overview

**Comment by Phil-DS** [comment]
Is this coming to the main distribution at any point, or is it still stuck on MDC?

**Comment by wagnermaciel** [comment]
@Phil-DS The range slider is still considered experimental at this time

**Comment by narendrasinghrathore** [comment]
Any update, is this part of material.angular.io, please update?
@andrewseguin

**Comment by wagnermaciel** [comment]
@narendrasinghrathore No major update yet. The range slider is still considered experimental and is available for preview in the `@angular/material-experimental/mdc-slider` package. You can follow our progress on the `main` branch

**Comment by wagnermaciel** [comment]
@SvenBudak There's no in progress % but you can track our progress by viewing our PRs
https://github.com/angular/components/pulls?q=is%3Apr+%22feat%22+%22switch%22+%22implementation+to+use+MDC%22+created%3A%3E2022-01-01+

I wouldn't recommend using the mdc-slider just yet because there are still major changes happening which will change some behavior, but the API will be identical so it doesn't matter _that_ much

**Comment by SvenBudak** [comment]
@wagnermaciel ok thanks for the info! Can you roughly estimate when mdc could be ready to be released for prod? i am fully aware that any of your statements can be + or - 10 years off. however, i would be interested in a rough estimate as i can't figure it out based on the issues. don't worry no one is going to nail you down on this statement. it's enough to know if it's more like months or more like 3 years. :)

**Comment by wagnermaciel** [comment]
We're planning on releasing them over the next few major releases, of which there are typically two annually. We're not sure if we'll be able to land all of them in one go so it might be over the course of the next 1-2 releases (maybe 3 depending on how tough things get, but that seems like a worst case scenario).

So long story short, worst case scenario I'd estimate 1.5 years until the new components are released for prod

**Comment by jelbourn** [comment]
Next major update (v15)

**Comment by amysorto** [comment]
Closing this since this is going to be available in v15 really soon! For a sneak peak you can look here: https://rc.material.angular.io/components/slider/examples#slider-range
