### ISSUE TITLE
mat-form-field must contain a MatFormFieldControl error shows for dynamic MatFormField load with ProjectableNodes

### ISSUE THREAD

**Issue by sir-captainmorgan21** [angular/components#13313]
#### What is the expected behavior?
The MatFormField component should render properly, as I am passing an input node with the "matInput" attribute in as a ProjectableNode

#### What is the current behavior?
The MatFormField component throws the `mat-form-field must contain a MatFormFieldControl
` error
#### What are the steps to reproduce?
I have a directive with the following.
```
import { Directive, TemplateRef, ViewContainerRef, OnInit, ComponentFactoryResolver, ComponentRef, Injector } from '@angular/core';
import { MatFormField } from '@angular/material/form-field';

@Directive({
  selector: '[appAddAttribute]'
})
export class AddAttributeDirective implements OnInit {

  private matFormFieldComponent: ComponentRef<MatFormField>;

  constructor(
    private templateRef: TemplateRef<any>,
    private viewContainerRef: ViewContainerRef,
    private componentFactoryResolver: ComponentFactoryResolver,
    private injector: Injector
  ) { }

  ngOnInit(): void {
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(MatFormField);
    const viewRef = this.templateRef.createEmbeddedView(null);
    this.matFormFieldComponent = this.viewContainerRef
      .createComponent(componentFactory, 0, undefined, [[], viewRef.rootNodes]);
  }

}
```
And the component template has the following to trigger the directive.
```
<h1>Directive Sandbox</h1>
<input matInput placeholder="test input" *appAddAttribute>
```

I know the MatFormField component is being dynamically loaded because it throws the error in the console, and the resulting DOM looks like so. Im not sure why the component is complaining, as you can see even in the resulting dom the matinput attribute is there.

```
<body>
   <app-root _nghost-c0="" ng-version="6.1.8">
      <h1 _ngcontent-c0="">Directive Sandbox</h1>
      <!---->
      <mat-form-field class="mat-form-field ng-tns-c1-0 mat-primary ng-star-inserted">
         <div class="mat-form-field-wrapper">
            <div class="mat-form-field-flex">
               <!----><!---->
               <div class="mat-form-field-infix">
                  <input _ngcontent-c0="" class="mat-input-element mat-form-field-autofill-control ng-tns-c1-0" matinput placeholder="test input">
                  <span class="mat-form-field-label-wrapper">
                     <!---->
                  </span>
               </div>
               <!---->
            </div>
            <!---->
            <div class="mat-form-field-subscript-wrapper">
               <!----><!---->
            </div>
         </div>
      </mat-form-field>
   </app-root>
   <script type="text/javascript" src="runtime.js"></script><script type="text/javascript" src="polyfills.js"></script><script type="text/javascript" src="styles.js"></script><script type="text/javascript" src="vendor.js"></script><script type="text/javascript" src="main.js"></script>
</body>
```

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to dyamically load a mat-form-field component and pass in the input node I want inside via the ProjectableNodes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.0
Material 6.4.7

**Comment by mmalerba** [comment]
I don't think this is an issue with the form field itself, but rather the directive being used here. This stackblitz demonstrates that it works if you add `*ngIf="true"` to the element instead: https://stackblitz.com/edit/components-issue-pxyfmf?file=src/app/example-component.html
