### ISSUE TITLE
Paginator - Datatable - Issue on data property update - blanck table

### ISSUE THREAD

**Issue by elvince** [angular/components#13316]
#### Bug, feature request, or proposal:
Bug: Datable not refresh correctly on edge case.

#### What is the expected behavior?
when the page index changes, the data should be refreshed

#### What is the current behavior?
It stay on an empty page.

#### What are the steps to reproduce?
You have a 6 elements in your datasource and set your paginator to 5 elements per page.
go on page 2 (1 element visible)
remove that element from the source and call this.datasource.data = [you array of 5 elements]
The paginator update, set the count to "1 - 5 on 5" and arrows are disabled - Perfect
But the datatable is visually not updated (empty) and you can't go anymore on page 0.

Reason:
The paginator is updated via the pageIndex property via _updatePaginator.
The issue is that _updatePaginator set the new page index after _pageData is called, so it is not taken into account. it is due to the face that it is in a promise (Async call).
As a result, data.slice().splice(startIndex, this.paginator.pageSize) do not return the appropriate values to render.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material 6.4.7

**Comment by cnqiuxue** [comment]
+1

**Comment by andrewseguin** [comment]
We intentionally made it so that the paginator does not automatically change its page index, since it cannot know for sure what page you are intending it to go to.
