### ISSUE TITLE
Allow cdkDrag item that is not associated with a CdkDrop container to be moved into any CdkDrop container

### ISSUE THREAD

**Issue by josephperrott** [angular/components#13339]
Currently if a `cdkDrag` item, which does not start as a child of a `CdkDrop` element, is dragged into a `CdkDrop` element no events are fired by either the `cdkDrag` item or the `CdkDrop` element it moves into.

Unassociated `cdkDrag` items should be able to move into any `CdkDrop` element unless they fail the `CdkDrop`'s `enterPredicate`.

[Stackblitz repro](https://stackblitz.com/edit/angular-material2-issue-s51d7l?file=app%2Fapp.component.html)

**Comment by crisbeto** [comment]
Should be covered by https://github.com/angular/components/issues/13340.
