### ISSUE TITLE
mat-table popup menu of each row closes when observable data source is been updated

### ISSUE THREAD

**Issue by patolax** [angular/components#13370]
#### Bug, feature request, or proposal:
When we setup menu to open on each row of MatTable that is updated frequently using observable data source, if user has opened the menu, it disappears when an update occurs. This means under frequent updates user cannot use the menu at all. 

#### What is the expected behavior?
User should be able to use the menu under data updates of the table.

#### What is the current behavior?
Menu closes when data source of Mattable is updated. 

#### What are the steps to reproduce?
This is the example of the template. Each show has a button to open a menu with matMenuTriggerFor. Data table is updated using observable data source when back end data has been updated. 

    <ng-container matColumnDef="actions">
      <mat-header-cell *matHeaderCellDef></mat-header-cell>
      <mat-cell *matCellDef="let row">
        <button mat-icon-button (click)="editcar(row)" routerLink="/carmanagement/caredit/{{row.id}}" routerLinkActive="active" title="Edit">
          <mat-icon color="primary">mode_edit</mat-icon>
        </button>
          <button mat-icon-button (click)="deletecar(row)" title="Delete">
              <mat-icon color="primary">delete</mat-icon>
          </button>

        **<button mat-icon-button [matMenuTriggerFor]="appMenu" title="Menu">
          <mat-icon>more_vert</mat-icon>
        </button>**
      </mat-cell>
    </ng-container>

```
.......

<mat-menu #appMenu="matMenu">
  <button mat-menu-item routerLink="/carmanagement/car-event-history" routerLinkActive="active">
    <mat-icon>event_note</mat-icon>Event history
  </button>
  <button mat-menu-item routerLink="/carmanagement/car-state-history" routerLinkActive="active">
    <mat-icon>history</mat-icon>State history
  </button>
</mat-menu>
```

**Comment by andrewseguin** [comment]
Are you using a trackBy function to preserve rows for each data item

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
