### ISSUE TITLE
Datepicker calendar breaks down in firefox

### ISSUE THREAD

**Issue by eslammahgoub** [angular/components#13386]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Datepicker calendar should works in firefox.

#### What is the current behavior?
Datepicker calendar breaks on firefox when it opens

#### What are the steps to reproduce?
1- Go to the https://material.angular.io/components/datepicker/examples in firefox and open browser console
2- Open datepicker.
2- ERROR Error: "Invalid date "1" for month with index "9".". in console

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Firefox Quantum 61.0.1 (64-bit)
Ubuntu canonical - 1.0

![screenshot from 2018-10-02 12-05-50](https://user-images.githubusercontent.com/5474280/46343007-b150cc80-c63c-11e8-9096-09ba5245fc30.png)

**Comment by manklu** [comment]
Works with Firefox 62.0.2 (64-Bit) on Windows 10

**Comment by crisbeto** [comment]
I wasn't able to reproduce it either. What is your computer's locale?

**Comment by eslammahgoub** [comment]
Locale from the terminal:

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

**Comment by josephperrott** [comment]
@eslammahgoub It looks like this is working in Firefox Quantum 63.  Can you confirm that you are still seeing this in the latest versions?

**Comment by eslammahgoub** [comment]
yes still not working ERROR Error: "Invalid date "1" for month with index "10"."
![screenshot from 2018-11-29 13-33-04](https://user-images.githubusercontent.com/5474280/49219358-a9629e00-f3db-11e8-8f06-83a08017981e.png)

**Comment by pasevin** [comment]
@eslammahgoub have you figured it out?

**Comment by eslammahgoub** [comment]
it's working now I think it something relates to firefox
