### ISSUE TITLE
Use stable sort for table's sort

### ISSUE THREAD

**Issue by jeff-a-andersen** [angular/components#13414]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When sorting a column, other column data should not sort.

#### What is the current behavior?
If there are more than 10 rows, other column data is randomly sorted

#### What are the steps to reproduce?

I was able to reproduce the problem by taking the example from Material (https://stackblitz.com/angular/ygkamyrvqvr?file=app%2Ftable-sorting-example.ts):

1.	Change the position value to be all “1”:

![image](https://user-images.githubusercontent.com/20786498/46435996-aa918a80-c70c-11e8-9cc8-384bee7d2310.png)
 

2.	Now, if I sort on the “No.” column, the “Name” column stays exactly the same (as you would expect because you aren’t sorting on it):

 
![image](https://user-images.githubusercontent.com/20786498/46436033-c85eef80-c70c-11e8-8f20-164171ab988e.png)

3.	Now, if we add an 11th row:

 
![image](https://user-images.githubusercontent.com/20786498/46436044-ceed6700-c70c-11e8-98ff-b3bbde4ff015.png)

4.	And then sort on the “No.” column, the “Name” column is randomly sorting:

 
![image](https://user-images.githubusercontent.com/20786498/46436051-d3b21b00-c70c-11e8-9bd7-0bde6bbea9a7.png)

#### What is the use-case or motivation for changing an existing behavior?
I believe this to be incorrect behaviour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "^6.4.7",
"@angular/cli": "~6.1.5",
"@angular/compiler-cli": "^6.1.0",
"typescript": "~2.7.2"

OS: Windows 10 Version 1703 (OS Build 15063.1324)
Browser: Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Comment by jelbourn** [comment]
What you're requesting is a **stable sort**

**Comment by jeff-a-andersen** [comment]
What is strange is that appears to be stable up to 10 rows of data and then it becomes unstable after that.  Perhaps it's using a different sort algorithm when there are more than 10 rows.

**Comment by crisbeto** [comment]
The table uses `Array.prototype.sort` which was unstable on earlier versions of Chrome. This should have been resolved at the browser level by now. See https://twitter.com/mathias/status/1036626116654637057.
