### ISSUE TITLE
Hiding Angular Material Paginator's "length" property

### ISSUE THREAD

**Issue by anelad** [angular/components#13427]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
mat-paginator component should allow the option to hide the length property.

#### What is the current behavior?
According to [Angular Material docs](https://material.angular.io/components/paginator/api) mat-paginator does not have a **hideLength** (or a different named) property.

#### What are the steps to reproduce?
There is nothing to reproduce.

#### What is the use-case or motivation for changing an existing behavior?
I'm using Firebase Firestore. As you know Firestore cannot count stored items directly. But I will not create Firestore listeners to observe database CRUD operations in Cloud Functions -at least not in this project since I'm not gonna get paid for it-. So I am not able to set a length property and I should hide it.

I'm sure there might be similar use cases.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.6

#### Is there anything else we should know?
Nope.

**Comment by Tirabuchi** [comment]
Agreed. In my case, i get already paginated results from the server. Anyone found a workaround?

**Comment by jelbourn** [comment]
From an i18n standpoint, we wouldn't be able to introduce a field to disable display of the length, since we'd have no idea where it is in the text. Instead, you can use a custom `MatPaginatorIntl` to change the page display however suits the application.
