### ISSUE TITLE
Table sticky headers/footer scrollbar position

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/components#13450]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
Show scrollbar for table body.

#### What is the current behavior?
Scrollbar showed for table with header and footer.
![111](https://user-images.githubusercontent.com/11072464/46562446-c65f8100-c904-11e8-8616-abb699cc4c30.jpg)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-kzamgk?file=app%2Ftable-sticky-header-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.7

**Comment by jelbourn** [comment]
@Knoxvillekm it's not clear what you're referring to here

**Comment by RudolfFrederiksen** [comment]
One problem, when the scroll bar is located in the content only, is that the header of the table gets offset and you have to add some additional js to detect the overflow and correct the header width to fit the table width.

Depending on how you implement it, you might have some problems with the header's columns width  not matching the columns of the table's content.
This effect varies depending on the width constrains and overflow rules you might apply.

In my opinion, it implies a big overhead for a very small benefit.
I admit I think it would looks a tiny little bit better,
but again I think it's fine as it is and I would prefer to avoid additional js bindings.

**Comment by manju-reddys** [comment]
@RudolfFrederiksen https://codepen.io/manju-reddys/pen/YRQNVO no script used.

**Comment by RudolfFrederiksen** [comment]
@manju-reddys The table headers are  not aligned anymore with the content, that's what a script is needed for: to detect if you have a scrollbar or not, and adjust the header accordingly.

**Comment by andrewseguin** [comment]
We use the browser's native sticky positioning, so changing the appearance is out of our control
