### ISSUE TITLE
[Feature Request] (Datepicker) should update selected date on input change 

### ISSUE THREAD

**Issue by hiepxanh** [angular/components#13486]
#### Bug, feature request, or proposal: 
feature request

#### What is the expected behavior?
update the highlight date every input change while the calendar open
(or we can create some method like: `selectedDate` method to update it, or `updateDate` method to trigger change detection)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/16970990/46588876-11c48b80-cacd-11e8-8719-10b4d0b4607e.png)
If I press next day button (update the input value) while the calendar open but still not update the highlight date. only I close and reopen datepicker, it will update value.

#### What are the steps to reproduce?
I think it simple and clear to understand. tell me if you need example repository.

#### What is the use-case or motivation for changing an existing behavior?
I have next day, and previous day button, with today button. I want to change date manually but the selected date not update

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6
material 6
typescript 3
chrome 60

#### Is there anything else we should know?
no

**Comment by jelbourn** [comment]
Your screenshot isn't showing an Angular Material datepicker, so I don't think you have the right library.

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/47071885-e9503600-d21e-11e8-949c-89e5e674887e.png) 
@jelbourn are you kidding me? why you close my issues and concluded hurriedly?

**Comment by hiepxanh** [comment]
I already try everything, event use changeDetectionRef.detectchanges() to update after have value but nothing happen, If only I close and reopen that calendar, the highlight position will be update

**Comment by hiepxanh** [comment]
thank you sir, thank you very much @jelbourn

**Comment by DmitryEfimenko** [comment]
The `MatDatepicker` has a method `select(date)`, but it looks like it does not trigger change detection in the calendar

**Comment by mmalerba** [comment]
This use case is outside the scope of what we support

**Comment by DmitryEfimenko** [comment]
better UX is out of scope? The reason given really says nothing.

**Comment by peternixey** [comment]
It really would be awesome to have a `dateChange` event which emits the selected date. I'm hoping for the same functionality in order to reduce clicks for someone using the datepicker to jump between dates. 

Demo of the required behaviour:

https://www.loom.com/share/be92484311c24c439f23c1ac73de1064
