### ISSUE TITLE
looping using tab with mat-chip-list in firefox

### ISSUE THREAD

**Issue by eduardoDigifred** [angular/components#13514]
#### Bug, feature request, or proposal:
Using the firefox browser and the tab key to change the focus between the components I noticed that in the mat-chip-list there is a looping inside of itself, not changing the focus to another component. In other browsers it works normally.

#### What is the expected behavior?

the certain thing is that, when using the tab key, after navigating between the chips, exit the mat-chip-list and go to another component

#### What is the current behavior?
Using the firefox browser and the tab key to change the focus between the components I noticed that in the mat-chip-list there is a looping inside of itself, not changing the focus to another component. In other browsers it works normally.

#### What are the steps to reproduce?
this behavior can be reproduced on the page itself from the angular material matchip list using the firefox browser and use the tab inside the component.

#### What is the use-case or motivation for changing an existing behavior?
some people usually use the keyboard more than the mouse and this causes situations like this to occur.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.4.7

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

I attempted to see this reproduction in our docs site as mentioned but did not see this issue occurring as described.

**Comment by jnoga** [comment]
I also have the same problem. I can reproduce it with the official doc example [Chips with input](https://material.angular.io/components/chips/overview#chip-input): https://stackblitz.com/angular/gxkenpgblbd?file=app%2Fchips-input-example.ts

Tested in Firefox 60.3.0esr and 63.0.3 versions

**Comment by huiaic** [comment]
We have the same problem with the latest version (65.01) of FIrefox as well. Is there a workaround? This is a blocker for us because it makes our app non a11y compliant.

**Comment by EverettZ** [comment]
Any updates on this?

**Comment by yuankunluo** [comment]
still open

**Comment by Wloclawek** [comment]
mat-chap-list has "tabindex = 0 '. This causes a problem. It can't be easily overwritten.

The error still occurs in Firefox 70.0.1

**Comment by crisbeto** [comment]
This doesn't seem to be an issue anymore. Here's a Stackblitz running the latest version https://stackblitz.com/angular/oalmroannoy?file=src%2Fapp%2Fchips-input-example.ts.
