### ISSUE TITLE
Tooltips on Android w/long press

### ISSUE THREAD

**Issue by mlabieniec** [angular/components#13593]
#### Bug, feature request, or proposal:
Potentially a Bug 

#### What is the expected behavior?
Tooltip on Android/Chrome doesn't show on long press when using as a matPrefix to an input

#### What is the current behavior?
When trying to long press, the input is usually focused instead of the <a> that is wrapping the icon i have for a (?) icon in the input. If you position it JUST right you can sort of get it to show. 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://angular-material2-issue-zuu2pi.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
No change, just trying to use the default.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0, Angular Material 6.4.7, Mac OS 10.14, Typescript 2.9.2 

#### Is there anything else we should know?
Long press works fine on iOS safari. It looks like maybe it highlights the entire containing element when doing so, but on Chrome/Android it seems to give focus pretty immediately to the input instead or something.

**Comment by andrewseguin** [comment]
Seems to be working okay right now - tried it on my device and it was able to successfully show the tooltip consistently
