### ISSUE TITLE
material2 tooltip position issue while ios browser hide address / status bar

### ISSUE THREAD

**Issue by adamzhu-xs** [angular/components#13615]
#### Bug:
material2 tooltip show at wrong position on ios browser while user scroll down (address / status bar hidden).

#### What is the expected behavior?

![expected png](https://user-images.githubusercontent.com/22661765/46940645-c8130c80-d09b-11e8-8d27-81fc93af3ed5.jpg)

#### What is the current behavior?

![current png](https://user-images.githubusercontent.com/22661765/46940656-ce08ed80-d09b-11e8-81b0-9b20fd2d5787.jpg)

#### What are the steps to reproduce?
1. use iphone safari open https://material.angular.io/components/tooltip/examples
2. change tooltip position to "above"
3. scroll down till browser hide address / status bar
4. long press btn to show tooltip

#### What is the use-case or motivation for changing an existing behavior?
user will not able to view tooltip properly on ios.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.11 + material2 5.2.5
Latest material2 site also having same issue

#### Is there anything else we should know?
No

**Comment by lares83** [comment]
any update on this issue? Do you have any workaround for it?

**Comment by zarend** [comment]
Hello,

I cannot reproduce this issue, and I believe it has already been fixed. If the issue persists, please provide reproduction steps or file a new issue report.

![image](https://github.com/angular/components/assets/7720245/e0ed6dbd-48b4-4515-bf9b-06ddd7c3d445)
![image](https://github.com/angular/components/assets/7720245/85713234-7de6-4780-b36c-14286da6187d)

 - iOS 16.6.1
 - iPhone 13 mini
 - https://material.angular.io/components/tooltip/examples#tooltip-auto-hide

Best regards,

Zach
