### ISSUE TITLE
Feature for mat-paginator; [disableOptionCentering]

### ISSUE THREAD

**Issue by mibrezovec** [angular/components#13646]
#### Bug, feature request, or proposal:
As any mat-select, mat-select inside the mat-paginator should be able to use [disableOptionCentering].

#### What is the expected behavior?
Something on the lines of 
`            <mat-paginator [disableOptionCentering]="true"
                    [length]="pageLength"
            </mat-paginator>
`

Adding the [disableOptionCentering] should be possible and working as intended (like with any other mat-select). See [mat-select API](https://material.angular.io/components/select/api) for detailed explanation.

#### What is the current behavior?
It's not possible.  [mat-paginator API](https://material.angular.io/components/paginator/api)

#### What are the steps to reproduce?
[https://material.angular.io/components/paginator/overview](https://material.angular.io/components/paginator/overview)

Select options from the "Items per page", the chosen option will be in the "dropdown" center.

#### What is the use-case or motivation for changing an existing behavior?
It should be posibble to use [disableOptionCentering] with any mat-selects, even if in a paginator.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All that support mat-paginators I guess.

#### Is there anything else we should know?
Nope.

**Comment by krivkoo** [comment]
Hello, 
Is this issue still free unassigned ? I'd like to take this on me 

Best regards 

Matthew

**Comment by mibrezovec** [comment]
Afaik, not assigned atm, you can take it @krivkoo 
Thank you!

**Comment by krivkoo** [comment]
Will you assign it to me or will I do it?

**Comment by mibrezovec** [comment]
Please feel free to do it yourself, I am new here and uncertain if I can assign you if I'm not an admin. @krivkoo
