### ISSUE TITLE
matAutocomplete: selecting an option with the enter key does not work right

### ISSUE THREAD

**Issue by notBald** [angular/components#13660]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using enter to select values should work the same way as using the mouse

#### What is the current behavior?
When selecting values with the enter button, it does something odd. When you delete text afterwads, the model may remain unchanged. It does not happen every time.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material-autocomplete-async2?file=src%2Fapp%2Fapp.component.html

Method one:
(1) Type into the text input, for instance the letter "b"
(2) Select an option by using the enter key
(3) Put the cursor in the input
(4) Press the backspace one time to make the dropdown reopen
(5) Use the enter key to select an option. 
(6) Repeat step 4
Notice how the dropdown does not always open, and how the model sometimes does not change.

Method two
(1) Type into the text input, for instance the letter "b"
(2) Select an option by using the enter key
(3) Mark all the text in the input, then delete it all at once
 (The dropdown should now open)
(4) Repeat step 2
Notice that sometimes the drop down will not open. There will be no text in the input but the model displayed next to the input shows the previous value.

#### What is the use-case or motivation for changing an existing behavior?
A user can delete the text in a textbox, then leave thinking the text is deleted when it isn't.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.9
Material: 6.2.1 / 6.4.7 / 7.0 RC.2
OS: Windows 10
Typescript: 2.9.2
Browsers: Chrome, Firefox, 

#### Is there anything else we should know?
The stackblitz example features a loading indicator, but removing it has no impact. The example is also an older version of Material (6.2.1), but the issue is present on version 7.0

**Comment by mmalerba** [comment]
I updated this example to v15 and it seems to be working fine using enter: https://stackblitz.com/edit/angular-6gsfel
