### ISSUE TITLE
Stepper cannot progress past first step after being reset

### ISSUE THREAD

**Issue by buddamus** [angular/components#13736]
#### Bug, feature request, or proposal:
bug

#### What are the steps to reproduce?
Code : https://stackblitz.com/edit/angular-ffmhcf
App : https://angular-ffmhcf.stackblitz.io

1. Complete "step one" (provide two inputs and click "Next")
2. Complete "step two" (select a radio option and click "Next")
3. Complete "step three" (click "Confirm")
4. Arrive back at step one
5. Click "Next"

#### What is the expected behavior?
The enduser can progress to "step two"

#### What is the current behavior?
The enduser is stuck on "step one"

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
JS Versions
"@angular/animations": "^6.0.9",
    "@angular/cdk": "^6.2.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/material": "^6.4.0",
    "@angular/material-moment-adapter": "^6.4.0",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",

Firefox (developer edition) 64.0b2 (64-bit), Chrome Version 70.0.3538.67 (Official Build) beta (64-bit)

**Comment by Splaktar** [comment]
I updated the [Stackblitz](https://stackblitz.com/edit/angular-wxphcx?file=src%2Fapp%2Fapp.component.ts) to v7, wrapped the stepper in a `form`, and tried a few other things, but I'm still able to reproduce your problem. I haven't had time to dig into it more, but it seems like the custom logic and ContextService may be causing this, especially since I don't see any kind of exception when the "Next" button is clicked and does nothing.

**Comment by Splaktar** [comment]
Note that I have a stepper implementation in one of my apps that calls `reset()` and it works perfectly with going through the steps again.

**Comment by buddamus** [comment]
@Splaktar I initially had the code using @Input and @Output instead of ContextService and experienced the same thing. I changed the code to use the service in hopes that i might have a work around.

I should mention that I can get it working with a hack:  nulling and resetting the value that the stepper uses as "complete" : 

`let hackFix = this.inputTwo;
    this.context.setInputTwo(null);
    this.stepper.reset();
    setTimeout(()=>{
      this.context.setInputTwo(hackFix);
    });`

Hack here: https://stackblitz.com/edit/angular-3rx4ws

**Comment by buddamus** [comment]
@Splaktar there's an issue with your solution. The user can now jump directly to step 2 using the "Step Two" header link. Any thoughts?

**Comment by buddamus** [comment]
@Splaktar I was able to get this [working](https://stackblitz.com/edit/angular-lyje2k) using a form group.. but the issue is that the stepper.reset() clears the values. I would like "inputOne" and "inputTwo" to never lose their value.

**Comment by Splaktar** [comment]
@buddamus `stepper.reset()` clearing the form values is working as designed. You can easily cache/store a subset of the values (or all values) and re-populate them if desired. 

I do this in one of my apps to restore the age and gender fields. I grab those values from a Service in the constructor of the component used in each step. That way the MyStepperComponent (or AppComponent in your example) doesn't need to try to restore the values in the `confirm()` method.

I am glad that you got this working.
