### ISSUE TITLE
docs: breaking changes to elevation need to be documented in guides

### ISSUE THREAD

**Issue by Splaktar** [angular/components#13752]
#### Bug, feature request, or proposal:
Proposal/Bug

#### What is the expected behavior?
New behaviors and breaking changes should include changes/updates to the existing guides, Elevation and Theming in this case.

#### What is the current behavior?
From the CHANGELOG:
### Breaking Changes

* **elevation:** Because `mat-elevation` usages have been moved out of component stylesheets, users who have
not invoked a theme mixin will not see any elevation shadows on Material components.
However, users that have created a custom theme which lacks the `elevation` property will
still see the default black shadows.

Additionally, users who want to use themed elevations in their custom components can create
their own shorthand mixin:

```sass
@import '~@angular/material/theming';

$myTheme: ...

@mixin my-elevation($zValue) {
  @include mat-theme-elevation($zValue, $myTheme);
}
```
and then invoke `angular-material-theme` with the `$myTheme` variable.

#### What are the steps to reproduce?
1. Have an Angular Material project with a custom theme based on v6
1. Upgrade to v7
1.  It's not clear how to add the `elevation` property to a custom theme and it is not documented in [Defining a custom theme](https://material.angular.io/guide/theming#defining-a-custom-theme)
1. Try to learn more about `mat-theme-elevation` but it's not documented in the [Elevation Guide](https://material.angular.io/guide/elevation)

#### What is the use-case or motivation for changing an existing behavior?
The guides and docs should describe the new behavior and configuration. It shouldn't be required for new users to read the changelog to find out about `mat-theme-elevation`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6->7
Angular Material 6->7
TypeScript 2.7.2->3.1.x
All browsers

#### Is there anything else we should know?
This came from a question on [Gitter](https://gitter.im/angular/material?at=5bcda7a9ab17df2631d02857).

**Comment by yusijs** [comment]
This info is also not present at https://update.angular.io, and having it there would simplify the migration. Or just a quick reminder when there are breaking changes, with a link to the changelog. While most of us naturally goes to the changelog before upgrading (or after seeing something off in our layout), I think having the info directly in the update-context would be good as well.

**Comment by jelbourn** [comment]
Closing this since the transition was 4.5 major versions ago
