### ISSUE TITLE
fr(datepicker): add `viewChanged` output to calendar

### ISSUE THREAD

**Issue by harryy2510** [angular/components#13759]
#### Feature request:
1. It is a great datepicker but I think there should be a few features like monthChange, yearChange , viewChange events.
2. Also manually rerendering the calendar dates to filter dates.

#### What is the current behavior?
1. Currently I have to create a custom header template and use a service for listening to month change event.
2. In terms of rerendering calendar, there is nothing yet.

#### What is the use-case or motivation for changing an existing behavior?
I have to make an api call to check whether dates are available or not to be filtered on calendar.
In that case, if a user changes the month on calendar, I make an api call to get available dates and then need to rerender datepicker so as to show the available dates.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.0
Angular Material 7.0.0
macOS Mohave
Typescript 3.1
Chrome 70

**Comment by mmalerba** [comment]
Most of these features exist already, though there is no output for when the view changes. I'd be happy to accept a community contribution for this
