### ISSUE TITLE
Prevent autoscroll on check action in multiple select

### ISSUE THREAD

**Issue by cityowl** [angular/components#13788]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Add option "disable autoscroll on check in multiple select" 

#### What is the current behavior?
Autoscroll runs on checkbox item select

#### What are the steps to reproduce?
- Open multiple selectbox with a lot of items
- Check item closely to bottom of pane

#### What is the use-case or motivation for changing an existing behavior?
The position is lost in sight of the eye

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.0.0, material 7.0.1

**Comment by crisbeto** [comment]
Closing this since the automatic scrolling is an accessibility feature.
