### ISSUE TITLE
mat-datepicker-popup behaves incorrectly on IOS (both Chrome and Safari)

### ISSUE THREAD

**Issue by kompelia** [angular/components#13789]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

When clicking on the calendar icon, the calendar is correctly positioned.

#### What is the current behavior?
Clicking on the calendar icon on the datepicker (after being in the input field) pushes the calendar popup to the bottom of the screen instead of to the bottom of the input field (as it is supposed to happen).
If user scrolls up or down the calendar popup jumps to the bottom of the input field.
[Angular mat datepicker screen recording.zip](https://github.com/angular/material2/files/2510911/Angular.mat.datepicker.screen.recording.zip)

Short video reproducing the bug is attached.

#### What are the steps to reproduce?

1. Navigate to https://material.angular.io/components/datepicker/overview with iPhone (Safari or Chrome)
2. Click inside the input fiels (Choose a date)
3. Click on the calendar icon
4. Optionally scroll up or down to observe the popup behaviour

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 6.4.1
iOS
Chrome & Safari

**Comment by msidlo** [comment]
I'm experiencing the same behavior.

**Comment by oky1** [comment]
Same problem (Angular Material 7.0 / Safari).
Actual Result: calendar starts moving around the page and goes outside the screen.
Expected Result: calendar is fully shown on the screen and opened just under the Drop Date field.

**Comment by yaroslav1988** [comment]
still relevant
mat-datepicker popup is basically unusable on iOS
any progress on that?

**Comment by mmalerba** [comment]
Have you tried enabling the touchUi for iOS? that should work better on mobile devices https://stackblitz.com/edit/angular-dpccqm?file=src/app/datepicker-overview-example.html

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
