### ISSUE TITLE
(Bug)Scroll with touchpad is not working in EDGE on a drag and drop list

### ISSUE THREAD

**Issue by bajzat** [angular/components#13809]
#### Bug:
In EDGE, the scrolling is not working if the user is using a touchpad in a drag and drop list. 

#### What are the steps to reproduce?

StackBlitz: https://stackblitz.com/edit/angular-2rf4m5

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.1
Angular CDK: 7.0.1

**Comment by crisbeto** [comment]
It seems to work for me. Do you mean scrolling while dragging?

**Comment by bajzat** [comment]
Nope, general scroll in the list. I have multi-gesture dell touchpad and it seems it sends a touch event instead of scroll event and it never reaches the scrollbar in EDGE. Chrome is fine

**Comment by crisbeto** [comment]
Hmm, that's interesting, because we don't really prevent anything unless you've started dragging (e.g. via `mousedown` or `touchstart`). I'm able to scroll it using a gesture on an HP laptop.

**Comment by bajzat** [comment]
yes, I've checked the source code as well. It's a really weird issue. If I disable the pointer-actions on the div which has the cdkDropList then the scroll will start work. (but ofc this disable the drag and drop :) ). Anyway, I could not test that with other notebooks from different manufacturers we have dell branded notebooks.

**Comment by bajzat** [comment]
I've just tested with my macbook using bootcamp and the scroll works and it looks that issue affects the dell touchpads only. That means the problem can be the touchpad driver or the edge itself or a combination of them :( .

**Comment by crisbeto** [comment]
Closing since it doesn't look like we can do much about this issue.
