### ISSUE TITLE
disableRipple not working in checkbox with custom theme

### ISSUE THREAD

**Issue by bampakoa** [angular/components#13904]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The ripple effect should not be visible when `disableRipple` attribute is set to true on a checkbox.

#### What is the current behavior?
The ripple effect is still shown when `disableRipple` attribute is set to true on a checkbox.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-clzfgv

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.3
Node: 8.12.0
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

#### Is there anything else we should know?
If we do not use a custom theme, `disableRipple` is working as expected.

**Comment by crisbeto** [comment]
The `disableRipple` is working in your example. What you're seeing is the focus and hover indication.

**Comment by bampakoa** [comment]
Thanks @crisbeto for clearing that. Are these also supposed to be hidden when `disableRipple` is true?

**Comment by crisbeto** [comment]
I don't think so, because they're also there for accessibility.

**Comment by bampakoa** [comment]
The strange thing is that they are not visible when `disableRipple` is true and there is no custom theme. Why is that?

**Comment by bitflower** [comment]
Any news on this? Is somebody investigating? We have a custom theme as well and have the sticky circle after clicking the component.

**Comment by dana-cohen** [comment]
I'm also waiting for this disableRipple issue to be investigated, it used to work up to a couple of months ago and stopped working. not using a custom theme.. any news?

**Comment by dana-cohen** [comment]
OK, just upgraded to material 7.3.4 and it solved the issue for me.. :)

**Comment by devversion** [comment]
This is actually the same for non-custom themes too: https://stackblitz.com/edit/comp-13904?file=.angular-cli.json.

It's working as expected as those are accessibility focus indicators which aren't affected by `disableRipple`. If you want to remove them, you could use CSS overrides, though we don't recommend disabling focus indication.
