### ISSUE TITLE
Custom Form Field Control Rendering Issue in Edge 42.17134.1.0

### ISSUE THREAD

**Issue by sjai013** [angular/components#13967]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Custom form field control and standard Material form controls render with proper alignment:
![expected](https://user-images.githubusercontent.com/8345675/47959951-ce622c00-e03c-11e8-9116-e03982ffdd2a.png)

#### What is the current behavior?
Custom form field control is misaligned with standardMaterial form controls.
![current](https://user-images.githubusercontent.com/8345675/47959994-b4751900-e03d-11e8-8aa0-ebc753184e08.png)

#### What are the steps to reproduce?
Taken from https://material.angular.io/guide/creating-a-custom-form-field-control and modified to include a matInput control.
https://stackblitz.com/edit/angular-jfxs2u?embed=1&file=app/form-field-custom-control-example.html

#### What is the use-case or motivation for changing an existing behavior?
Rendering is inconsistent between browsers

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 7, Material 7, Windows 10, TS3.1, Edge 42.17314.1.0 (64 bit), Chrome 70.0.3538.77 (64 bit), and Firefox 63.0.1 (64 bit)

#### Is there anything else we should know?
N/A

**Comment by crisbeto** [comment]
Closing since this is referring to a really old version of Edge.
