### ISSUE TITLE
feat(mat-menu): Height menu is reducing when the page is scrolling

### ISSUE THREAD

**Issue by lfdantoni** [angular/components#13988]
#### Bug, feature request, or proposal:
When the menu is opened and scrolling it, the height menu is reducing.

#### What is the expected behavior?
The height menu shouldn't change.

#### What is the current behavior?
The height menu is reducing

#### What are the steps to reproduce?
- Open menu
- Scroll page

![menu-issue](https://user-images.githubusercontent.com/1294324/48009314-45112f00-e0fa-11e8-8cec-4ff66272ec5c.gif)

https://stackblitz.com/edit/angular-material-menu-issue

#### What is the use-case or motivation for changing an existing behavior?
Better user experience 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version 7

#### Is there anything else we should know?
I found It is happening in the menu overlay, when page is scrolling, the overlay height is reducing but, if the user scrolls to oposite way, this heigh is not recovering its height that it had before.

**Comment by Rem1te** [comment]
+1
still no any idea?

**Comment by 1clique** [comment]
any solution?

**Comment by allddarrass** [comment]
This issue might be resolved (at least partially) by setting `height: fit-content;` on the panel element:

**example.component.scss**
`
<mat-menu class="example-class" ... >
...
</mat-menu>
`

**example.component.scss**
`
::ng-deep .example-class {
  height: fit-content;
}
`
