### ISSUE TITLE
Drag-drop nested droplists that are also draggable throws getBoundingClientRect error.

### ISSUE THREAD

**Issue by DaGLiMiOuX** [angular/components#13995]
#### Bug, feature request, or proposal:
Bug/Feature request

#### What is the expected behavior?
Having nested draggable droplists to allow moving droplists and its child elements.

#### What is the current behavior?
Currently, having a `cdkDrag` with a `cdkDropList` in the same element works without errors. You can move the drop list inside it's parent drop list, but a child element implementing a `cdkDrag` causes `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined` when trying to move the child draggable element.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-p2vqvj-484lmj

The example provided is took from docs about DropList.

#### What is the use-case or motivation for changing an existing behavior?
In the provided example, you can move elements and the list of elements, which is a draggable too. When you attempt to drag the draggables in the list (list items), an unexpected error is thrown when calling `getBoundingClientRect`.

My use case for this is to allow me to reorder "sublists" of elements and store them in the backend. Altough, would be nice that these droppable lists became "unlimited". For example, 5 levels deep of elements. In my case is not needed, but could be usefull for someone else that needs a nested droppable.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI 7.0.3
CDK 7.0.2
Material 7.0.2
Google Chrome 69.0.3497.100

#### Is there anything else we should know?
When I use `@ViewChild(CdkDrag)` to get the list draggables and log it `onInit`, the DropList container information is referenced okay. I think it has more to do with ngZone than any missing properties, but I'm not sure.

**Comment by VernonG07** [comment]
I was interested in this too, can you check this out to see if this is what you are trying to accomplish?
https://stackblitz.com/edit/angular-p2vqvj-ofoudc

**Comment by IlCallo** [comment]
Interest in this as well.
Use case: re-ordering options and nested options of sidenav.
I want to re-order all first-level options among themselves, while being able to also re-order suboptions contained in some of the first-level options (let's call them "nested options") and only between those suboptions (cannot transfer in another group of suboptions).

**Comment by crisbeto** [comment]
I wasn't able to get it to throw the error, but this sounds like the issue that will be fixed by https://github.com/angular/material2/pull/13820 in the next release.

**Comment by IlCallo** [comment]
> I wasn't able to get it to throw the error, but this sounds like the issue that will be fixed by #13820 in the next release.

This seems like one of the problems I'm facing 🤞

**Comment by jonathan-casarrubias** [comment]
Did you guys manage to make this work? I'm trying to achieve nested drop lists, but when I try to drop an element into a nested list, that list reorders within the main list, popping up and down while trying to drag something inside, like its trying to re-order inside the main list.

Instead what I'm achieving is that the second element which I'm trying to drop inside the nested list, is ordered at the same level of the nested list


MAIN LIST []
-----------------------------
|   NESTED LIST []
|-----------------------------
|  ELEMENT
------------------------------

So when I try to drop the element inside the nested list, I can only get it on top or on the bottom of the nested list.

Any ideas?

**Comment by crisbeto** [comment]
Closing since the related PR has merged a while ago.
