### ISSUE TITLE
mat-form-field  <ng-content> problem

### ISSUE THREAD

**Issue by abadakhshan** [angular/components#14009]
#### Bug, feature request, or proposal:
Bug or  feature request

#### What is the expected behavior?
I wrap mat-form-field  in my component and inside it I put a `<ng-content></ng-content>`
for example my component is like this:

```
@Component({
  selector: "my-input",
  template: `<mat-form-field>
                            <input matInput [placeholder]="placeHolder" >
                             <ng-content></ng-content>
                  </mat-form-field>`
})

```
when I use my component ,I expect whatever is inside <ng-content> does like is inside 
mat-form-field  but it dosn't!

for example if i use my component like this:

```
<my-input>
<mat-hint align="end">hint text</mat-hint>
</my-input>
```
hit wouldn't display correct.
#### What is the current behavior?
Every content inside my component does like it is inside `<mat-form-field>`

**Comment by MRMokwa** [comment]
Did you find any workaround for this meanwhile?

**Comment by johnluetke** [comment]
My workaround has been including `mat-form-field` and any `mat-hints` inside the component template, and controlling them with input flags. It certainly reduces the reusability of the component, but I have yet to come across a better solution.

**Comment by mark-langer** [comment]
@vivian-hu Have you heard anything from the core team if this will be addressed any time soon? This would be a neat feature for Angular.

**Comment by mmalerba** [comment]
This is a limitation of Angular's content projection. https://github.com/angular/angular/issues/37319 has been filed to hopefully improve some of the short-comings
