### ISSUE TITLE
@HostBinding attributes are not respected by MatFormField

### ISSUE THREAD

**Issue by klemenoslaj** [angular/components#14024]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Adding a `readonly` attribute via `HostBinding` to `matInput` host element should put `input` element to the read-only state, the same way as `readonly="true"` does when directly added to an element.

#### What is the current behavior?
HTML5 input element is correctly in readonly state, however, `matFormField` is still triggering focus animation

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ty6kkd

First input field is what I expect second field should work like as well.
The difference is on the first field I use `readonly="true"`, while on the second I use `@HostBinding() readonly = true`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: ^7
Material: ^7
TypeScript: ^3

**Comment by aitboudad** [comment]
not only `readonly` but also `placeholder` and `id` attrs, hoping this will be considered!

**Comment by crisbeto** [comment]
Closing since host bindings set values directly on the DOM node, they don't set inputs so there isn't a way for Material to respond to those changes.
