### ISSUE TITLE
<mat-grid-list> scrollTo

### ISSUE THREAD

**Issue by Zacknero** [angular/components#14058]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
the scrollTo or up with <mat-grid-list>

#### What is the current behavior?
I don't have a solution for scroll up

#### What is the use-case or motivation for changing an existing behavior?
I have list and this is dinamic. When i update the list this ti be scroll up

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 or 7, Material 7.0.3

**Comment by prabhpahul** [comment]
Hello, do we have any update on this.?

**Comment by Zacknero** [comment]
> Hello, do we have any update on this.?

No because i don't find the solution :(

**Comment by jelbourn** [comment]
Closing this because we are pretty unlikely to add new features to `MatGridList` going forward now that CSS Grid provides a significantly more robust tool for creating this style of layout.
