### ISSUE TITLE
BUG: CdkDropList drop position after scroll is wrong

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/components#14098]
#### Reopening #13823 as it was closed as duplicate of #13588 but it is not.
#13588 is about implementing automatic scrolling after drag overshoot

I have already implemented a automatic scrolling (it is a very specific solution for our use case).
When item is dropped after automatic scroll , drop receiver is miscalculated. 

#### Bug
`CdkDropList`: Drop position is wrong after scrolling
#### What is the expected behavior?
Drop target should match element under mouse pointer after scroll

#### What is the current behavior?
Scrolling is not taken into consideration while calculating drop element 

#### What are the steps to reproduce?
https://stackblitz.com/edit/cdk-drop-list-scroll

Steps: 

1.Start dragging top most element
2. Drag past container towards down
3. Wait till everything is scrolled down
4. now drag element back into container
5. Drop the element 

#### More info
https://github.com/angular/material2/blob/26c73e04350fa9a159a8e0319b9d4837df04ea5b/src/cdk/drag-drop/drop-list.ts#L388

`_cachePositions` need to be called again whenever drag is active and scroll container is scrolled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.0.3
Node: 10.12.0
OS: win32 x64
Angular: 7.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**Comment by abdulkareemnalband** [comment]
@aidvb 
Can you elaborate what you mean by **adding difference**

**Comment by aidvb** [comment]
> @aidvb
> Can you elaborate what you mean by **adding difference**

I am not sure about that but that was my first thought: https://postimg.cc/gallery/eldp5f9k/

**Comment by abdulkareemnalband** [comment]
@aidvb
that's why this bug reort

**Comment by aidvb** [comment]
@abdulkareemnalband How's it going to solve the problem?

**Comment by techy2493** [comment]
My temporary work-around for  #13588 experiences the same. I'm looking into a code work-around right now. This will be a concept that will need to be addressed in  #13588. However it is obvious that this could occur in any case where the scroll position of the container is changed whether through dragging or some other means.

**Comment by abdulkareemnalband** [comment]
@techy2493 can you show your solution, may be on stackblitz 
thanks in advance

**Comment by techy2493** [comment]
@abdulkareemnalband I will try to link something this afternoon. My changes were to the library itself, so I may just create a diff and make it available.

**Comment by abdulkareemnalband** [comment]
@techy2493 thanks
I will try this later today

**Comment by codeweazel** [comment]
any news on this one?

**Comment by varminas** [comment]
I'm also very eager to get updated on this ticket.

**Comment by amaksimovich2** [comment]
I tried to apply code from @techy2493 and faced with needing to possibility to define scrolling container element for offset calculation. I have scrolling container with droplist elements each of which contains another droplist.

**Comment by techy2493** [comment]
@amaksimovich2 So something like a cdkScrollableParent would be useful to you as an override to using the CDK's own element to get the offset from? 

Or would you need to *additionally* use that parent's offsets? 

If the latter it may be that the calculation for drop needs to be more dynamic and less tied to the start position because calculating N number of offsets would be difficult, and might not perform well.

**Comment by techy2493** [comment]
@amaksimovich2 Have you tried setting the root element with cdkDragRootElement to see if that provides the behavior you are looking for cdkDragRootElement?

**Comment by Musuel** [comment]
Hello,

I developped a directive allowing a drop list to automatically scroll horizontally/vertically and refresh drop positions. Simply put the **dropListScroller** directive on the CdkDropList.
_Note that I had to use a private property of DropListRef: \_itemPositions._

Here is the stackblitz: [drop-list-scroller](https://stackblitz.com/edit/angular-9oeppz?embed=1&file=src/index.html)

Let me know if it fit your needs.

@crisbeto Do you think it would be possible to make _itemPositions public in DropListRef ? What do you think about this kind of directive ?

It may be related to #13588.

**Comment by arora-kushal** [comment]
@Musuel - This works fine when you have very less items say 10. But it is giving same problem when you have a large list, say you have 500 items..  I just tested it by adding 400 items in your solution and it is giving the same problem.

Eagrly waiting for this solution to be fixed.

**Comment by chandujindham1756** [comment]
I'm also very eager to get updated on this ticket.

**Comment by chandujindham1756** [comment]
Is there any update on this issue?

**Comment by arora-kushal** [comment]
We have developed a workaround

private scroll($event: CdkDragMove): void {
    this.cancelScroll();

    const { x, y } = $event.pointerPosition;
    const speed = 20;

    const scrollContainer = this.scrollEl.nativeElement;
    const scrollTop = scrollContainer.scrollTop;
    const scrollLeft = scrollContainer.scrollLeft;
    const scrollHeight = scrollContainer.scrollHeight;
    const scrollWidth = scrollContainer.scrollWidth;
    const clientRect = scrollContainer.getBoundingClientRect();
    let scrollx = 0;
    let scrolly = 0;

    if (x < clientRect.left && scrollLeft !== 0) {
      scrollx = -Math.trunc(speed * Math.exp((clientRect.left - x) / 50));

      // ensure left scroll boundary isn't crossed
      if (scrollLeft + scrollx < 0) {
        scrollx = -scrollLeft;
      }
    } else if (x > clientRect.right && scrollLeft <= scrollWidth - clientRect.width) {
      scrollx = Math.trunc(speed * Math.exp((x - clientRect.right) / 50));

      // ensure right scroll boundary isn't crossed
      if (scrollLeft + scrollx > scrollWidth - clientRect.width) {
        scrollx = scrollWidth - clientRect.width - scrollLeft;
      }
    }

    if (y < clientRect.top && scrollTop !== 0) {
      scrolly = -Math.trunc(speed * Math.exp((clientRect.top - y) / 50));

      // ensure top scroll boundary isn't crossed
      if (scrollTop + scrolly < 0) {
        scrolly = -scrollTop;
      }
    } else if (y > clientRect.bottom && scrollTop <= scrollHeight - clientRect.height) {
      scrolly = Math.trunc(speed * Math.exp((y - clientRect.bottom) / 50));

      // ensure right scroll boundary isn't crossed
      if (scrollTop + scrolly > scrollHeight - clientRect.height) {
        scrolly = scrollHeight - clientRect.height - scrollTop;
      }
    }

    if (scrollx !== 0 || scrolly !== 0) {
      this.scrollEl.nativeElement.scrollLeft += scrollx;
      this.scrollEl.nativeElement.scrollTop += scrolly;

      this.adjustItemPositions({ x: scrollx, y: scrolly });

      this.animationFrame = requestAnimationFrame(() =>
        this.scroll($event)
      );
    }
  }

**Comment by Musuel** [comment]
Hello Arora,
Sorry for the late reply, I didn’t have any time to give an eye on the issue you complained about.
I’m glad you found a workaround based on the solution I provided.
Don not hesitate to share a stackblitz with the working workaround for others :)
(And me)

**Comment by chandujindham1756** [comment]
Hello @arora-kushal ,

Can you please share your developed workaround solution link in stackblitz.

**Comment by arora-kushal** [comment]
Sorry Guys... The above workaround was not working properly... so I deleted it..

**Comment by Anzil-Aufait** [comment]
> Hello,
> 
> I developped a directive allowing a drop list to automatically scroll horizontally/vertically and refresh drop positions. Simply put the **dropListScroller** directive on the CdkDropList.
> _Note that I had to use a private property of DropListRef: _itemPositions._
> 
> Here is the stackblitz: [drop-list-scroller](https://stackblitz.com/edit/angular-9oeppz?embed=1&file=src/index.html)
> 
> Let me know if it fit your needs.
> 
> @crisbeto Do you think it would be possible to make _itemPositions public in DropListRef ? What do you think about this kind of directive ?
> 
> It may be related to #13588.

Hello , do you know how to add this in a mat tree. like [this](https://stackblitz.com/edit/mat-tree-with-drag-and-drop?file=app%2Ftree-flat-overview-example.ts) . 
Anyway thanks for your demo.

**Comment by Musuel** [comment]
Hello,
I’ll try to have a look asap but no guaranty, I’m in a rush for now.

**Comment by MiszczProgramowania** [comment]
I think a lot of projects are waiting for it. How far this is on roadmap ?

**Comment by RadimFornusek** [comment]
For regular cases the drop position when scrolling (with scrolled element being parent of the drop list) was sorted in Angular CDK version 9.1 which allows to set a different scrolling elements for `DropListRef ` using `withScrollableParents` method.

See my example here. Usage of the method is in `ngAfterViewInit`.
https://stackblitz.com/edit/drag-drop-scroll 

Difference from the original reported example is that Angular here handles the scrolling itself, there is no custom code for it. So it doesn't allow the big "overshoot" of drag outside of the element, you need to keep the element close to bottom or to drag (or scroll using a mouse wheel).

**Comment by amaksimovich2** [comment]
> `withScrollableParents`

This approach is not working from 9.2.1 CDK version.

**Comment by crisbeto** [comment]
All the positioning issues after scrolling should be resolved in the latest version. As for marking which containers can be scrollable, @amaksimovich2 is correct that `cdkScrollable` should be used.
