### ISSUE TITLE
Textareas in overflown containers aren't scrolling to bottom in Mozilla

### ISSUE THREAD

**Issue by ghost** [angular/components#14150]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

When I type in a textarea that is taller than it's container, I want to see what I type.

#### What is the current behavior?

The textarea doesn't scroll to bottom on keystrokes

#### What are the steps to reproduce?

(I had issues with Mozilla and stackblitz, if you can't see the output in live editing, try the other link)

Live editing : https://stackblitz.com/edit/angular-dsscz4-xas344?file=app/text-field-autosize-textarea-example.html

Result : https://angular-dsscz4-xas344.stackblitz.io/

#### What is the use-case or motivation for changing an existing behavior?

A user typing text he can not see isn't really user-friendly

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

See stackblitz

#### Is there anything else we should know?

If it can be of any help, I have stumbled upon this SOF question : https://stackoverflow.com/questions/12105440/why-is-typing-in-a-textarea-in-firefox-causing-the-screen-to-scroll

**Comment by trichetriche** [comment]
Hello, I am digging this up because I got no answer in 5 days, hope you see this !

**Comment by crisbeto** [comment]
I spent some time looking into it and I don't think we can do much about it. This is down the browsers not setting the scroll position consistently: e.g. Chrome scrolls the container so the text cursor is in the view, whereas Firefox scrolls it so the top of the input is visible. It can be worked around for this one case by calling `textarea.scrollIntoView(false)` however doing so will move the user's scroll position unnecessarily in most other cases. We could've used[ `scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded), but it isn't support on Firefox.

**Comment by zarend** [comment]
> I spent some time looking into it and I don't think we can do much about it. This is down to browsers not setting the scroll position consistently: e.g. Chrome scrolls the container so the text cursor is in the view, whereas Firefox scrolls it so the top of the input is visible. It can be worked around for this one case by calling `textarea.scrollIntoView(false)` however doing so will move the user's scroll position unnecessarily in most other cases. We could've used[ `scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded), but it isn't supported on Firefox.

Closing this issues as "won't fix" for above reasons.
