### ISSUE TITLE
bug: Disabled button consuming mouse events on parent

### ISSUE THREAD

**Issue by Chifilly** [angular/components#14196]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
When you interact with a disabled button, it doesn't 'eat' the mouse events of its parent.

#### What is the current behavior?
When you interact with a disabled button with the mouse, the `mat-button` completely consumes all the mouse events until you hit `.mat-button-wrapper`. The button itself causes the parent to not trigger `mousemove`, `mouseover` etc. and in turn triggers `mouseout`.

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-disabled-button)

When you slowly hover over the disabled button from top to bottom or left to right starting outside the container (highlighted with the green border), you will see `mouseover` initially triggers because you're hovering over the parent, then it stops being triggered because you've entered the button and it triggers `mouseout`, then you trigger `mouseover` again when you hit `.mat-button-wrapper` and then back to `false` and then `true` again. Compare this to the enabled button and it's `true` the entire time.

#### What is the use-case or motivation for changing an existing behavior?
In my use case, I have video player controls that appear on hover (needing to be handled by Angular, since CSS doesn't provide all the functionality I need), but if you hover over a disabled button inside the container it triggers the parent `mouseout` event and starts hiding the controls.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Angular:** 7.0.4  
**Material:** 7.0.4  
**OS:** Windows 10 Pro  
**TypeScript:** 3.1.6  
**Browsers:** Chrome and Edge (Firefox seems unaffected)

#### Is there anything else we should know?
A side-effect of this is that tooltips don't show either, however they do on Firefox. I'm also not sure if this is a Material issue or a Browser issue, and I don't have much time to test it myself at the moment

**Comment by crisbeto** [comment]
Material doesn't do much to buttons, besides styling. This is more of a browser issue where different browsers decide to handle events on disabled buttons differently.

**Comment by josephperrott** [comment]
We actually should be able to prevent `pointer-events` on the wrapped text so that the mouse always hits the button instead of the internal wrapper element.  We already rely on the bubbling from the wrapper element to the button for clicks.  This actually would just make clicks occur directly on the button.
