### ISSUE TITLE
Jasmine exception when using mat-tabs

### ISSUE THREAD

**Issue by nhuurnink** [angular/components#14210]
#### Bug, feature request, or proposal:
Jasmine throws an error with below code: 
PhantomJS 2.1.1 (Windows 8 0.0.0) MyComponent should create FAILED
TypeError: undefined is not an object (evaluating 'getAnimationStyle(element, '').trim') (line 3963)
applyKeyframeAnimation

The same error occurs when testing with chrome.
```
        <mat-tab-group>

          <mat-tab label="Account">
            <div class="tab-content p-24">
              Account content 1
            </div>
          </mat-tab>

          <mat-tab label="Subscriptions">
            <div class="tab-content p-24">
              Subscriptions content 2
            </div>
          </mat-tab>
</mat-tab-group>
```

#### What is the expected behavior?
Succesful unit testing

#### What is the current behavior?
Error on unit testing

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular 6, Angular Material 6.4.6 on Windows with Typescript.

**Comment by arucar** [comment]
i have the same issue, i try to upgrade to angular 7 and material 7 but issue stay exist

**Comment by Noppey** [comment]
I ended up switching to chrome headless instead of phantomjs because multiple issues were not a problem there, including this one.

**Comment by arucar** [comment]
yeah... but for me it's a project at work... i can't choice... i must use PhantomJs :/, and i have only problem with Mat-tab

**Comment by arucar** [comment]
i have found a solution here : [https://github.com/angular/angular/issues/24094](url)
add NoopAnimationsModule in your TU and it will disable animations. after that the test work with phantomJS.

**Comment by asmith2306** [comment]
> i have found a solution here : [https://github.com/angular/angular/issues/24094](url)
> add NoopAnimationsModule in your TU and it will disable animations. after that the test work with phantomJS.

Worked for me on Angular 7 and Material 7, swapped out BrowserAnimationsModule for NoopAnimationsModule.  Cheers!

**Comment by crisbeto** [comment]
Given that there are some solutions and above and that there hasn't been any activity in a long time, I'm closing the issue.
