### ISSUE TITLE
Allow to configure typography margin css

### ISSUE THREAD

**Issue by galki** [angular/components#14240]
This is a feature request/proposal.

#### What is the expected behavior?
I'd like to be able to specify margin values for [typography classes](https://github.com/angular/material2/blob/8050f633b56b6c048fc72dad2ab79304afdfad19/src/lib/core/typography/_typography.scss) such as `mat-display-1`.

#### What is the current behavior?
Right now the margin values are arbitrarily hard-coded. For example `mat-display-1` is set to `margin: 0 0 64px;`

#### What is the use-case or motivation for changing an existing behavior?
The fact that only the margin is hard-coded is:
1. opinionated and a cause for inconvenience
2. inconsistent with all other properties such as font-size, line-height, font-family, and letter-spacing being configurable

**Comment by crisbeto** [comment]
It should be too big of an issue to add it to the config, but there are some ambiguous cases like the margin on paragraphs.

**Comment by orlaqp** [comment]
I agree with @galki I think we should be able to set the margin we want to apply. In addition, I think the current default is a little too big,  64px for the bottom margin on a mat-display-1?

**Comment by jelbourn** [comment]
@crisbeto do we use these ourselves anywhere?

**Comment by crisbeto** [comment]
We only use it in the utility classes @jelbourn (e.g. h1, h2, h3).

**Comment by jelbourn** [comment]
If that's the case, is there any advantage to including margins in the API vs. consumers defining custom margins directly?

**Comment by crisbeto** [comment]
The only advantage would be slightly less generated CSS and not having to deal with specificity if people want to to override the margins.

**Comment by kuncevic** [comment]
You can do `style="margin: 0"` or better use this [css utility thing](https://gist.github.com/jacurtis/30da4bf9a6c9b9b5cc0aebac512ca7c9#gistcomment-2592042) so you can just do e.g `class="mat-headline m0"`

**Comment by hiepxanh** [comment]
I think this is a nice option. right now I have to use `!important` flag to overide that margin, which is not convenient

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Going forward we'll be basing our typography off of MDC Web, so we probably won't be adding new API surfaces for now.

**Comment by hiepxanh** [comment]
So sad :( I really love this
