### ISSUE TITLE
Drag-and-drop is offset inside dialog if page is scrolled before opening dialog

### ISSUE THREAD

**Issue by pmilic021** [angular/components#14280]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
After scrolling the page and then opening dialog, any drag-and-drop list in the dialog component should work properly.

#### What is the current behavior?
The drag-and-drop list's drop placeholder is offset aprox by the amount scrolled before opening the dialog. 

#### What are the steps to reproduce?
I came across an example of this while looking for possible solution prior to making this issue:
@cisasteelersfan made it in one other ticket (that issue is not the same as this one!)
https://github.com/angular/material2/issues/13508#issuecomment-432428242

#### What is the use-case or motivation for changing an existing behavior?
It is pretty common use case to have drag-and-drop in a dialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0.2

**Comment by belerofont** [comment]
I have the same issue in 7.1.1 Angular Material.

**Comment by kernyden** [comment]
@crisbeto hi,  it would be nice to hear something, it is very important, thx

**Comment by pmilic021** [comment]
@kernyden If it helps you, as a temporary workaround, I forced `top` to be 0 (usually it is set to the -scrollOffset before opening dialog):

```
.cdk-global-scrollblock {
    top: 0 !important;
}
```

This way there wont be no offset in drag and drop, but opening a dialog will look a bit ugly.

**Comment by kernyden** [comment]
@pmilic021 no, it hasn't helped me, this thing reproduces not only on modal, it happens with lists have scroll.

**Comment by radzix23** [comment]
@pmilic021 try to add something like this in your global styles:
```
.cdk-global-scrollblock {
   position: initial !important;
   overflow: hidden !important;
}
```

**Comment by kernyden** [comment]
in actual version of cdk dnd we cant scroll with an active dnd effect :( - https://github.com/angular/material2/issues/13588

**Comment by linjie0928** [comment]
I have the same issue in ^7.3.7 Angular Material.

**Comment by hijamoya** [comment]
Any update on this issue?

**Comment by BlindDespair** [comment]
In Angular material 10 this is still an issue... Will it be fixed?

**Comment by Art2058** [comment]
Same issue,
Angular material 10

**Comment by BrettKessler** [comment]
This is still an issue for me and none of the workarounds seem to work for me, any solution to this?

**Comment by tameyer1** [comment]
We just ran into this bug.  Same symptoms - drag n drop in a dialog. Offsets are way off when dragging if page has been scrolled.  Works correctly if page is not scrolled.

This does **not** work: .cdk-global-scrollblock { top: 0 !important; }
This works but will be deprecated and against our internal policy.
::ng-deep html.cdk-global-scrollblock {
    top: 0px !important;
}

After 2 years and multiple reports is anyone reviewing?

**Comment by condericson** [comment]
Also having this issue. 

Made a stackblitz for reference: https://stackblitz.com/edit/drag-and-drop-inside-modal-bug

Using `.cdk-global-scrollblock { top: 0 !important; }` in my project's global styling worked for me.

**Comment by condericson** [comment]
Hey all, I'm also having this issue.

Made a stackblitz for reference: https://stackblitz.com/edit/drag-and-drop-inside-modal-bug

Using `.cdk-global-scrollblock { top: 0 !important; }` in my project's global styling worked for me.
