### ISSUE TITLE
Docs need a simple tree example

### ISSUE THREAD

**Issue by adamdport** [angular/components#14297]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Docs show the most simple example, and builds on it progressively to be more featureful. I want to see what the data needs to look like in its most minimal basic form. [The examples for mat-table](https://material.angular.io/components/table/examples) do this very well, with the first example being the simplest (34 lines of typescript).

#### What is the current behavior?
There aren't any simple trees in the docs. They're all nested, have injectable recursive functions to massage data, checkboxes, lazy/dynamic loading, etc. The first example has 139 lines of ts. This is difficult to digest.

#### What is the use-case or motivation for changing an existing behavior?
Reduced learning curve

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.0.3

**Comment by jelbourn** [comment]
Closing this since it looks like we now have examples for both cdk/mat for relatively simple usages
