### ISSUE TITLE
mat-tree documentation examples do not follow best practices

### ISSUE THREAD

**Issue by adamdport** [angular/components#14323]
#### Bug, feature request, or proposal:
proposal?

#### What is the expected behavior?
Angular Material components "will serve as an example of how to write Angular code following best practices".

#### What is the current behavior?
The "Tree with checkboxes" example on the [Material Tree examples page](https://material.angular.io/components/tree/examples) has the following: 

```
<mat-checkbox [checked]="descendantsAllSelected(node)"
                  [indeterminate]="descendantsPartiallySelected(node)"
                  (change)="todoItemSelectionToggle(node)">{{node.item}}</mat-checkbox>
```

and 

```
/** Whether all the descendants of the node are selected. */
  descendantsAllSelected(node: CheckpointFlatNode): boolean {
    const descendants = this.treeControl.getDescendants(node);
    const descAllSelected = descendants.every(child =>
      this.checklistSelection.isSelected(child)
    );
    return descAllSelected;
  }

  /** Whether part of the descendants are selected */
  descendantsPartiallySelected(node: CheckpointFlatNode): boolean {
    const descendants = this.treeControl.getDescendants(node);
    const result = descendants.some(child => this.checklistSelection.isSelected(child));
    return result && !this.descendantsAllSelected(node);
  }
```

It's my understanding that Angular will execute these loops (`every` and `some`) during every change detection. In fact, `descendantsAllSelected` will even get called twice as it's called again from `descendantsPartiallySelected`. Isn't this bad practice? Shouldn't we be [caching these values](https://angular.io/guide/template-syntax#quick-execution) when something is checked/unchecked? It seems like the problem will get worse and worse as the tree gets bigger.

#### What is the use-case or motivation for changing an existing behavior?
Material is supposed to set an example of best practices. This seems like it's encouraging a bad habit.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.1.0

**Comment by manklu** [comment]
> Shouldn't we be caching these values when something is checked/unchecked?

Which makes the code harder to read and unterstand for newcomers.

But perhaps it should be documented that it serves only demonstration purposes and that it's not necessarily suitable for production.

**Comment by jelbourn** [comment]
Closing this since, in this case, the extra overhead of running these loops is not significant with the small number of items.
