### ISSUE TITLE
bug(form-field): outline is not recalculated when label font-size is dynamically set

### ISSUE THREAD

**Issue by Shira16** [angular/components#14336]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Font size of label is different when form-field is focused/filled and when form-field is not focused/empty.  Outline of form field should be recalculated when label change its position.

#### What is the current behavior?
Outline of form field is on label after dynamically set font-size.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-8roea8

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "^7.1.1",
    "@angular/material": "^7.1.0",

#### Is there anything else we should know?
Might be related: https://github.com/angular/material2/issues/11919

**Comment by mmalerba** [comment]
Updated the stackblitz, still seems to be an issue: https://stackblitz.com/edit/angular-material2-issue-t86pgu?file=app/app.component.html
