### ISSUE TITLE
MatProgressBar and conditional rendering

### ISSUE THREAD

**Issue by galki** [angular/components#14357]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I expect the progress bar to work as expected even with an if condition:
```
<mat-progress-bar
   *ngIf="(fileUploadPercent$ | async) > 0"
   mode="determinate"
   value="{{ fileUploadPercent$ | async }}"
></mat-progress-bar>
```

#### What is the current behavior?
It shows 0 progress even though the value of `fileUploadPercent$` goes to 100.

**Comment by josephperrott** [comment]
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by galki** [comment]
[This](https://stackblitz.com/edit/angular-material2-issue-yaqza2) should be it but I couldn't reproduce the issue myself... it still persists on my local machine :/

**Comment by galki** [comment]
I did notice that on my local machine it does work if the file size is large (and upload time over a second or two)

**Comment by andrewseguin** [comment]
It looks to me that you need to write `[value]=` rather than `value=...`. If you still see the error, please open an issue with a reproduction. Thanks!
