### ISSUE TITLE
MatDialog scroll entire dialog

### ISSUE THREAD

**Issue by eyalhakim** [angular/components#14377]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
An ability to scroll the entire dialog and not just the content. Meaning - the dialog should have the full height of its content and scrolling will happen "outside" the dialog. The dialog would expand beyond the boundaries of the view.

#### What is the current behavior?
Scrolling can only happen inside the dialog. This creates a confusing UX where users don't have an indication that there is more content under scroll.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by mmalerba** [comment]
I don't think this really makes sense for the dialog. The dialog is supposed to be a modal popup that blocks interaction with the rest of the page, including scrolling. You might be able to make something for your use case using the CDK overlay which the dialog is based on
