### ISSUE TITLE
Add (invisible) close button to datepicker overlay

### ISSUE THREAD

**Issue by jelbourn** [angular/components#14379]
The datepicker presents itself as a modal dialog. On mobile devices, scree-reader users don't have an escape button to press and obviously would have a hard time tapping on the backdrop. We can add a close button with `cdk-visually-hidden` to help work around this. The label for this would also have to be added to `MatDatepickerIntl`.

**Comment by nigel5** [comment]
Hello, I would like to work on this as my first issue. Just to clarify, should the invisible close button be the entire backdrop such that when the user taps outside of the date picker then it would close?

**Comment by nigel5** [comment]
Ok I'm on it. Can you assign this issue to me please.

**Comment by jelbourn** [comment]
Unfortunately github only allows issues to be assigned to team members

**Comment by Panda-313** [comment]
Hello, I can see that there is already a pr for that, but it's inactive. Does it mean that I can work on this issue?
