### ISSUE TITLE
Angular Material Getting Started should mention ng add as primary installation option

### ISSUE THREAD

**Issue by beeman** [angular/components#14380]
#### Bug, feature request, or proposal:

Today I went with a beginner in Angular over adding Material Design and she started running the installation manually as she read in the [getting started](https://material.angular.io/guide/getting-started) guide.

I think it makes most sense to have the first step in Getting Started being the `ng add` option. 

#### What is the expected behavior?

Developers should be advised to use `ng add @angular/material`.

#### What is the current behavior?

Developers are currently advised to manually install the dependencies, then the snapshots, and after that the `ng add` option. 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?

It should be as easy as possible for people starting with Angular to add Angular Material.

#### Is there anything else we should know?
	

I would love to make the changes to the docs if the maintainers agree it should be addressed. Basically creating this issue to spark a conversation around it, if you agree I'll submit a PR 👍

**Comment by Pashozator** [comment]
Would be cool a change.

**Comment by jelbourn** [comment]
FYI @vivian-hu, @beeman is working on this himself

**Comment by Splaktar** [comment]
I don't think that a PR for this was ever submitted. This is now being worked on as part of https://github.com/angular/components/issues/16426.

**Comment by Splaktar** [comment]
This was done in PR https://github.com/angular/components/pull/16654.

These changes will go live on material.angular.io once `8.2.0` is published to the docs site (hopefully next week).
