### ISSUE TITLE
No way to see full text of overflowing mat-option within mat-autocomplete

### ISSUE THREAD

**Issue by operskaas** [angular/components#14409]
#### What is the expected behavior?
To be able to see the full text of mat-option within a mat-autocomplete, without selecting the option. Perhaps a tooltip on hover or keyboard nav. 

#### What is the current behavior?
Overflowing text has an ellipsis, with no tooltip.

#### What are the steps to reproduce?
1.) Have a mat-option with long text within a mat-autocomplete 
2.) Click in the corresponding input to bring up the mat-autocomplete
3.) Hover over the mat-option within the mat-autocomplete

https://stackblitz.com/edit/angular-material2-issue-czk7em

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Not sure. At least what we are using on Pantheon and what is used in the stackblitz above. 

#### Is there anything else we should know?
This is blocking a customer issue on Cloud Datastore. Implemented a workaround but it is not ideal.

**Comment by jelbourn** [comment]
@crisbeto we should see why `matTooltip` doesn't work on `mat-option`

**Comment by crisbeto** [comment]
`matTooltip` [does work](https://stackblitz.com/edit/angular-material2-issue-w459sy?file=app/app.component.html) on `mat-option` @jelbourn. The only issue is that if the user closes the overlay while the tooltip is open by pressing escape, the tooltip won't close until the next click somewhere on the body. I'm not sure whether we can do much about it, aside from checking whether the trigger is still in the DOM on each change detection, which won't be very fast.

**Comment by operskaas** [comment]
`matTooltip` does work on `mat-option`, but the bug, as I see it, is that there is no way to have a tooltip show up _only_ when the option text is overflowing. Also, have the tooltip show up when navigating to the option via keyboard, as one often does in an autocomplete dropdown.

**Comment by jelbourn** [comment]
@operskaas ah, I didn't realize you wanted that extra condition. As @crisbeto said, computing that would be rather costly. You could try using the length of the text as a proxy. It won't be perfect, of course, but might be good enough most of the time.

**Comment by halm0291** [comment]
> `matTooltip` does work on `mat-option`, but the bug, as I see it, is that there is no way to have a tooltip show up _only_ when the option text is overflowing. Also, have the tooltip show up when navigating to the option via keyboard, as one often does in an autocomplete dropdown.

You can choose when to disable the tooltip
[matTooltipDisabled]="disableTooltip(titleElement)"

and then check when the text its bigger thant the control width   
disableTooltip(titleElement: HTMLElement) {
    return titleElement.scrollWidth === titleElement.clientWidth;
  }

**Comment by shameera91** [comment]
> > `matTooltip` does work on `mat-option`, but the bug, as I see it, is that there is no way to have a tooltip show up _only_ when the option text is overflowing. Also, have the tooltip show up when navigating to the option via keyboard, as one often does in an autocomplete dropdown.
> 
> You can choose when to disable the tooltip
> [matTooltipDisabled]="disableTooltip(titleElement)"
> 
> and then check when the text its bigger thant the control width
> disableTooltip(titleElement: HTMLElement) {
> return titleElement.scrollWidth === titleElement.clientWidth;
> }

this is what i was looking for. thanks

**Comment by KelseySheely** [comment]
> 
> You can choose when to disable the tooltip
> [matTooltipDisabled]="disableTooltip(titleElement)"
> 
> and then check when the text its bigger thant the control width
> disableTooltip(titleElement: HTMLElement) {
> return titleElement.scrollWidth === titleElement.clientWidth;
> }

It is not all that clear what the titleElement actually is this example. If you put a reference on the mat-option like:

`<mat-option #optionElement [matTooltip]="'Your Tooltip'" [matTooltipDisabled]="disableTooltip(optionElement)>Your Option Label</mat-option>`

then you need to get the child object in order to actually have access to the scrollWidth and clientWidth properties, ie.

```
disableTooltip(element: MatOption) {
    return element._getHostElement().firstElementChild.scrollWidth === element._getHostElement().firstElementChild.clientWidth;
}
```

This seems a little hacky to me since they may change the structure in the future, but that was my workaround.

**Comment by GEMI** [comment]
Are there any proper solutions for this?

**Comment by crisbeto** [comment]
We have an alternate implementation of `mat-autocomplete` coming up which allows text to wrap. It looks slightly different, but the API is exactly the same. You can try it out using `import {MatAutocompleteModule} from '@angular/material-experimental/mdc-autocomplete';`.

**Comment by amysorto** [comment]
Closing this issue since text wrapping is the default behaviour in the MDC based component which will be available in v15.
