### ISSUE TITLE
[IE Only] Previously focused element is scrolled to top when restored after MatDialog closing

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/components#14443]
#### What is the expected behavior?
Scroll is prevented on element restore focus

#### What is the current behavior?
Element's parent is scrolled to top in IE

#### What are the steps to reproduce?
1. Open https://stackblitz.com/edit/angular-aewevn
2. Press on Click me! button
3. Close dialog by Esc
BUG: button's parent is scrolled to top

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.2
Browsers: IE Only

#### Is there anything else we should know?
method MatDialogContainer._restoreFocus contains:
`            toFocus.focus();`
proposed fix:
```
   if (toFocus.setActive) {
        toFocus.setActive(); // IE/Edge
    } else {
        toFocus.focus(); // All other browsers
    }
```

**Comment by crisbeto** [comment]
Browsers usually try to scroll the focused element into the view so this works as expected. If you want to handle the focus restoration yourself, you can open the dialog with the `restoreFocus = false` option.
