### ISSUE TITLE
Tabs does not work when usage matTabContent and mat-tab-label

### ISSUE THREAD

**Issue by splincode** [angular/components#14484]
#### What is the expected behavior?

```html
<mat-tab-group>
  <mat-tab> 
    <ng-template matTabContent>
      <ng-template mat-tab-label>First</ng-template>
      Content 1
    </ng-template>
  </mat-tab>

  <mat-tab> 
    <ng-template matTabContent>
      <ng-template mat-tab-label>Second</ng-template>
      Content 2
    </ng-template>
  </mat-tab>

  <mat-tab>
    <ng-template matTabContent>
      <ng-template mat-tab-label>Third</ng-template>
      Content 3
    </ng-template>
  </mat-tab>
</mat-tab-group>
```

![](https://habrastorage.org/webt/ee/zw/xd/eezwxdcfu4mukeov66cbayaowjy.gif)

https://stackblitz.com/edit/angular-mat-custom-label?file=app/tab-group-basic-example.html

#### What is the current behavior?

```html
<mat-tab-group>
  <mat-tab label="First"> 
    <ng-template matTabContent>
    Content 1 
    </ng-template>
  </mat-tab>
  <mat-tab label="Second"> 
    <ng-template matTabContent>
    Content 2 
    </ng-template>
  </mat-tab>

  <mat-tab label="Third">
    <ng-template matTabContent>
    Content 3
    </ng-template>
  </mat-tab>
</mat-tab-group>
```

![image](https://user-images.githubusercontent.com/12021443/49853567-a498e380-fdf8-11e8-9b83-a4c0d8e23f65.png)

**Comment by crisbeto** [comment]
I don't think we can do much about it. Since the label is inside an `ng-template`, it doesn't really exist until the template is attached.

**Comment by andrewseguin** [comment]
If we wanted to support this, we'd have to have a way to define the label template apart from the content template. Marking this as a potential feature

**Comment by totszwai** [comment]
label should never be part of the content. as of right now there is no way to customize both or lazy load the content unless you are forced to use regular label. please raise the priority if possible. <3

**Comment by pasupuletiswamy** [comment]
My Solution :

<mat-tab-group>
  <mat-tab>
    <ng-template mat-tab-label>
      First
    </ng-template>
    <ng-template matTabContent>
      Content 1
    </ng-template>
  </mat-tab>
  <mat-tab>
    <ng-template mat-tab-label>
      Second
    </ng-template>
    <ng-template matTabContent>
      Content 2
    </ng-template>
  </mat-tab>
  <mat-tab>
    <ng-template mat-tab-label>
      Three
    </ng-template>
    <ng-template matTabContent>
      Content 3
    </ng-template>
  </mat-tab>
</mat-tab-group>

**Comment by faradoxuzb** [comment]
@pasupuletiswamy it does not if content is component

**Comment by crisbeto** [comment]
As mentioned above, this isn't working because the markup is written incorrectly. The label can't be inside the content element.
