### ISSUE TITLE
IE11 input underline is invisible

### ISSUE THREAD

**Issue by Mainpat** [angular/components#14500]
#### What is the expected behavior?
The underline of input are visible

#### What is the current behavior?
The underline of input are invisible sometimes.

![grafik](https://user-images.githubusercontent.com/29457881/49946429-46026100-feef-11e8-9d1d-2f6056d9543c.png)

#### What are the steps to reproduce?
Open Site with IE11
https://material.angular.io/components/form-field/examples
Zoom out step by step at some zoom point the lines are invisible

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.1.1
IE11

#### Is there anything else we should know?
I think the problem is the browser but maybe we have luck and you can do something to fix this behaivior.

**Comment by devversion** [comment]
Hello! I think this issue no longer surfaces. Also we are working on a new form-field that is based on MDC. If this is still an issue for you (I wasn't able to see it), then most likely the MDC implementation will solve that.

I'm closing that in the meanwhile, but happy to re-open if you can point me to something. I'm using IE11.836.18362.0
