### ISSUE TITLE
Create component test harnesses

### ISSUE THREAD

**Issue by jelbourn** [angular/components#14510]
This is a tracking issue for adding test harnesses for components. A test harness is a class that you can interact with in unit/e2e tests rather than checking the DOM and directive instances directly. The benefit is that the library code can change things like DOM structure without breaking tests by also updating the harness internals.

**Comment by devversion** [comment]
@jelbourn I think we have the majority of harnesses implemented and the rest is tracked within JIRA. Should we consider closing this issue or update it to reflect the current state?

**Comment by jelbourn** [comment]
Yes this can be closed.
