### ISSUE TITLE
Sidenav autosize behaving inconsistently between browsers

### ISSUE THREAD

**Issue by flipZomb** [angular/components#14518]
#### What is the expected behavior?
Would expect the sidenav to have the same autoresize behaviour in all browsers.

#### What is the current behavior?
Have a long list of entries in the sidenav. All the same length, except for a one longer one right at the buttom, outside of the visible area.

In Chrome the resize is nice and how I would expect.

In EDGE/IE I get this horizontal scrollbar.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ewgduj?file=app%2Fsidenav-autosize-example.html

In Chome: 

![image](https://user-images.githubusercontent.com/33517613/50001379-f9755f00-ff9c-11e8-9a0e-93b66de155da.png)

In EDGE: 

![image](https://user-images.githubusercontent.com/33517613/50001363-ee223380-ff9c-11e8-9fbd-7710994ca35b.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.1.1
Angular 7.1.3
Microsoft Edge 41.16299.785.0
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
