### ISSUE TITLE
bug(mat-table) table stops rendering updates if cells tracked by ngFor are replaced with a clone

### ISSUE THREAD

**Issue by defernan** [angular/components#14552]
#### What is the expected behavior?
Table should be updated as the data source gets updated.

#### What is the current behavior?
The rendered rows stop updating after the columns are replaced and the template function calls stop firing as well.

#### What are the steps to reproduce?
See stackblitz. 
https://stackblitz.com/edit/dynamic-columns-mat-table-lkn45t

Relevant code.....
dynamic column html

```
<mat-table #table [dataSource]="dataSource" [trackBy]="trackByName">
    <ng-container *ngFor="let column of columns" [matColumnDef]="column.columnDef">
       <mat-header-cell *cdkHeaderCellDef>{{ column.header }}</mat-header-cell>
       <mat-cell *cdkCellDef="let row">{{ column.cell(row) }}</mat-cell>
    </ng-container>
    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
</mat-table>
```

component code
```
  ngOnInit() {
    // THIS BREAKS TABLE
    setTimeout(() => {
      this.columns = cloneDeep(this.columns);
    }, 4000);

    this.initData();
  }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.x, Material 6.x, Chrome 70

#### Is there anything else we should know?
If a column is added or removed the table starts updating, if the MatTableDataSource is newed, the table will also start updating.

#### Use Case
Column definitions get decorated at runtime based on user events, project definitions, and hardware limitations.

**Comment by defernan** [comment]
think this may be the same issue as #8361, although i am curious if the trackByFnc matters if its by idx or some identifying property?

**Comment by andrewseguin** [comment]
Hey, seems like your link to the Stackblitz is broken. Can you provide a working link so we can investigate into what's happening here? Thanks!

**Comment by wagnermaciel** [comment]
Closing because no clarification was provided.
