### ISSUE TITLE
virtual-scroll with expanding mat-chip-list hides input in Chrome

### ISSUE THREAD

**Issue by twjacobsen** [angular/components#14555]
#### What is the expected behavior?
I expect, that I can get to see the expanded list of chips, as well as the input for adding new chips

#### What is the current behavior?
The chip-list expands, but the scrollable area in the list does not.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dbdojd

See, that it is possible to add 5-[index-of-list-item] items to the chip list, before the input gets out of the view port.

In firefox, this "works better", since Firefox haven't enabled the `content` CSS property per default yet. So, in Firefox, it'll expand the list, allowing the user to scroll to the input.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions of Angular and Material, all OS'es (tested on Windows, MacOS and Ubuntu) in Chrome (latest version)

#### Is there anything else we should know?
Generally, it seems like there is no easy way for having content "overflow" the list. Ideally, I'd like my chip-list to just expand outside the scrollable view-port, but I've tried-and-failed at that.

**Comment by mmalerba** [comment]
The fixed size virtual scroll is not meant to handle items with a dynamic size. There is an autosize strategy in cdk-experimental (though as the name suggests, its experimental so use with caution).
