### ISSUE TITLE
[mat-slider] - flickering of mouse cursor during grabbing

### ISSUE THREAD

**Issue by zhongdeliu** [angular/components#14568]
#### Bug, feature request, or proposal:
Given I have a slider with "big steps" between the ticks the cursor flickers between default and grabbing state when I try to drag the slider thumb along.

#### What is the expected behavior?
Cursor should stay in grabbing state during dragging.

#### What is the current behavior?
Cursor flickers/alternates between grabbing and default state.

#### What are the steps to reproduce?
- Goto to the material examples page and set MaxValue to 3 (for example) https://material.angular.io/components/slider/examples
- Drag the slider left/right
- Observe the cursor state

#### What is the use-case or motivation for changing an existing behavior?
From a user perspective this creates distortion and irritation. The cursor should stay the same during this interaction.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all
For info: my system/setup currently is: Angular 6.1.10, Material: 6.4.7, MacOS High Sierra, TS: 2.7, Chrome 71

#### Is there anything else we should know?
No

**Comment by nigel5** [comment]
spec for reference: https://drafts.csswg.org/css-ui-3/#valdef-cursor-grabbing

Also, in Safari 12 the cursor stays as "text" while dragging with small ticks (e.g. MaxValue = 100)

**Comment by crisbeto** [comment]
The slider had a large refactor a while ago to remove its dependency on Hammer.js and it seems like this issue was resolved as well. Closing.
