### ISSUE TITLE
MatFormField style does not match reference implementation

### ISSUE THREAD

**Issue by Tiedye** [angular/components#14577]
#### What is the expected behavior?
For it to match the reference implementation https://github.com/material-components/material-components-web (and thus the spec)

A few of the issues are:
left padding b\w outline and text should be 14px (is 12px)
top padding b\w outline and text should be 16px (is about 21px)
padding on right of floated label should be 4 px (is 6px)

#### What is the current behavior?
It's not even close

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-jnxndm?file=index.html

#### Additional Info
https://material.io/design/components/text-fields.html#spec

**Comment by Tiedye** [comment]
For a library that's been around for so long, this is surprising.  I was intending to use Angular and this Angular Material library for a large project at my workplace but the pervasiveness of these simple issues is the implementation of the spec may change that.

**Comment by Tiedye** [comment]
After having a quick look at the stackblitz I posted, a few of the issues are:
left padding b\w outline and text should be 14px (is 12px)
top padding b\w outline and text should be 16px (is about 21px)
padding on right of floated label should be 4 px (is 6px)

There are quite a few possible states for this component, so this list is _not_ exhaustive.

**Comment by Tiedye** [comment]
Any updates on this?

**Comment by Tiedye** [comment]
Still an issue in 8.2.3

**Comment by devversion** [comment]
Thanks for this issue! This will be fixed by our upcoming MDC-based version of the form-field. The current implementation is already available in `@angular/material-experimental`, but we're still working on polishing it (e.g. in terms of bundle size).

**Comment by amysorto** [comment]
Closing this issue since the MDC based form-field is available in v15 and when comparing the form field with the material spec it looks correct now.
