### ISSUE TITLE
TemplatePortal class signature: possible typo

### ISSUE THREAD

**Issue by william-lohan** [angular/components#14584]
It seems like the `TemplatePortal` class signature

https://github.com/angular/material2/blob/fe7f95ec10acd9e660f7037be8d006c9e264a57b/src/cdk/portal/portal.ts#L119 

should actually be 

```ts
    export class TemplatePortal<C = any> extends Portal<EmbeddedViewRef<C>> {
```

and

https://github.com/angular/material2/blob/fe7f95ec10acd9e660f7037be8d006c9e264a57b/src/cdk/portal/portal.ts#L145

should be

```ts
    attach(host: PortalOutlet, context: C | undefined = this.context): EmbeddedViewRef<C> {
```

The generic parameter for `Portal` is for the type that the `attach(host: PortalOutlet): T` method returns. That returns what `PortalOutlet` 's `attach(portal: Portal<any>): any;` returns. _Note: This could be `attach<T>(portal: Portal<T>): T;` couldn't it_ If you look at the implementation of `PortalOutlet`, `BasePortalOutlet`, it's overload for `attach()` when passing a `TemplatePortal` is `attach<T>(portal: TemplatePortal<T>): EmbeddedViewRef<T>;` not `attach<T>(portal: TemplatePortal<T>): T;` like you'd expect based on the `TemplatePortal` class signature.

**Comment by jelbourn** [comment]
@gatimus you're right, that is a mistake. Open for PRs if you're interested.

**Comment by gatimus** [comment]
Yes, I'll work on that now, just wanted to make sure I saw it right.
