### ISSUE TITLE
Input with emoji cut off

### ISSUE THREAD

**Issue by tjaussoin-luna** [angular/components#14588]
#### What is the expected behavior?

Emoji are not cut off in the input field.

#### What is the current behavior?

The emoji is cut off.

![screenshot 2018-12-20 at 10 29 27](https://user-images.githubusercontent.com/4771436/50276402-282e8200-0442-11e9-97a7-a8d952508f21.png)

#### What are the steps to reproduce?
Insert an emoji (it was on Chrome Mac here), for instance here:
https://stackblitz.com/angular/xkgqladjeej?file=app%2Fform-field-appearance-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

 "dependencies": {
    "@angular/animations": "7.1.4",
    "@angular/cdk": "~7.2.0",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/flex-layout": "~7.0.0-beta.19",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/material": "~7.2.0",
    "@angular/material-moment-adapter": "~7.2.0",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/router": "7.1.4",
    "@fortawesome/fontawesome-free": "^5.5.0",
    "angularx-qrcode": "^1.5.1",
    "core-js": "^2.6.0",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "ng-lottie": "^0.3.2",
    "ngx-material-file-input": "^0.3.1",
    "ngx-moment": "^3.2.0",
    "parse": "^2.1.0",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  }

#### Is there anything else we should know?

No

**Comment by geromegrignon** [comment]
The stackblitz link is broken.

**Comment by tjaussoin-luna** [comment]
> The stackblitz link is broken.

fixed.
https://stackblitz.com/angular/xkgqladjeej?file=app%2Fform-field-appearance-example.ts

**Comment by julianobrasil** [comment]
@tjaussoin-luna, there's a discussion involving cropping over here: https://github.com/angular/material2/pull/10108

**Comment by crisbeto** [comment]
As far as I can tell, this isn't an issue in the latest version. Closing.
