### ISSUE TITLE
mat-typography specificity

### ISSUE THREAD

**Issue by captaincaius** [angular/components#14597]
#### Please describe the feature you would like to request.

Currently, if you apply mat-typography, the tag rules will be more specific than the class rules.  I'm proposing we make the class rules more specific when the mat-typography class is applied.  This way, you have your cake (sensible defaults on tags) and eat it too (control over typography based on your style guide).

#### What is the use-case or motivation for this proposal?

```
<body class="mat-typography">
<h1 class="mat-subheading-1">Title</h1>
</body>

```

This way, I can say that this is semantically an h1, but I can style it as a mat-subheading-1.

#### Is there anything else we should know?

There are two simple fixes for this, both of which I doubt would impact anyone negatively:

1. something like this at the end of _typography.scss

```
.mat-typography {
  @include mat-base-typography($app-typography, ".mat-typography-tags-override-classes");
}

```
2. for each class, add additional selectors to each rule with #{$selector} as an ancestor, like changing:

```
  .mat-h1, .mat-headline, #{$selector} h1, #{$selector} .mat-h1, #{$selector} .mat-headline  {
    @include mat-typography-level-to-styles($config, headline);
    margin: 0 0 16px;
  }

```
to:

```
  .mat-h1, .mat-headline, #{$selector} h1, #{$selector} .mat-h1, #{$selector} .mat-headline  {
    @include mat-typography-level-to-styles($config, headline);
    margin: 0 0 16px;
  }

```

**Comment by jelbourn** [comment]
cc @crisbeto 

I believe this is intentional as designed. If you want your overrides to be more specific than the optional element selectors, you would augment them with an additional class specific to your application, e.g.
```scss
.my-custom-typography {
  @include mat-base-typography(...);
}
```

**Comment by captaincaius** [comment]
thanks for the quick reply.

Right - that's exactly what I'm doing.

But it's not obvious that it's not by default, and even after you realize it, it's not clear how to make the tag rules overridable by the class rules without finding the right place in the sources.

I would think it should be by default.  But if it's by design, at least a quick sentence in the typography guide would help.  I hope a PR for that would be welcome.

**Comment by crisbeto** [comment]
Actually I think that this is a bug. The intention with the class rules was to be able to overwrite the tag rules if necessary.

**Comment by tkeenoy** [comment]
Is this issue still open?

**Comment by captaincaius** [comment]
looks like the PR was never merged.  I'm still using a workaround like https://github.com/angular/components/issues/14597#issuecomment-449149385
