### ISSUE TITLE
getRtlScrollAxisType detects incorrect RtlScrollAxisType for safari

### ISSUE THREAD

**Issue by kimjuan** [angular/components#14609]
#### What is the expected behavior?

In safari,

`getRtlScrollAxisType() === RtlScrollAxisType.NEGATED`

#### What is the current behavior?

`getRtlScrollAxisType()` returns `RtlScrollAxisType.INVERTED`

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular/Angular Material 7.0.4
- macOS 10.13.6
- Safari version 12.0.2 (13606.3.4.1.4)

#### Is there anything else we should know?

Problem unlikely to do with safari and os. Other libraries detected it correctly using feature detection technique

**Comment by devversion** [comment]
Hello, on my end the RTL scroll axis type is set to `NEGATED` in Safari (as expected). Can you please provide a reproduction if this is still an issue? Thank you!  

This is the demo I used: https://stackblitz.com/edit/angular-yehn5j?file=src/app/cdk-platform-overview-example.ts

**Comment by jbchr** [comment]
Hey, I can reproduce the issue using the above Stackblitz.

![rtlScrollAxisType_safari_bug](https://user-images.githubusercontent.com/23141806/86258550-3888f680-bbbb-11ea-968a-2182a1162e46.png)

MacOs: 10.14.6 (18G2022)
Safari: 13.1.1 (14609.2.9.1.3)

Let me know if I can help anywhere.
