### ISSUE TITLE
position mat-menu in right side of the trigger

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/components#14621]
#### Please describe the feature you would like to request.
I would like to have option to open mat-menu in right side of the trigger.

It should look like below 

![image](https://user-images.githubusercontent.com/7831299/50396301-4d4b2980-078f-11e9-8dc5-645f511546e4.png)

while as per current design it is looking like as below 
![image](https://user-images.githubusercontent.com/7831299/50396319-6653da80-078f-11e9-952c-b93ec27f7868.png)

#### What is the use-case or motivation for this proposal?
I want to create overlay which should not overlap other menuitems in sidemenu and should render in right side of the trigger.

#### Is there anything else we should know?

Here is sample stackblitz 
https://stackblitz.com/edit/angular-wurasp

I also tried with custom overlay but in that also there are only three options

for Xposition start, center and end
for Yposition top, center, bottom

I tried with xPosition end and Yposition center but not able to get what I want.

**Comment by lokeshdaiya** [comment]
Any update on this ?

**Comment by jpzwarte** [comment]
In order for this to work, you have to change the way the `setPosition` method of the `MatMenuTrigger` works. Something like this:

```
  private setPosition(positionStrategy: FlexibleConnectedPositionStrategy) {
    let [originX, originFallbackX]: HorizontalConnectionPos[] = this.menu.xPosition === 'left' ? ['start', 'end'] : ['end', 'start'];
    let [originY, originFallbackY]: VerticalConnectionPos[] = this.menu.yPosition === 'top' ? ['top', 'bottom'] : ['bottom', 'top'];

    let [overlayX, overlayFallbackX]: HorizontalConnectionPos[] = ['start', 'end'];
    let [overlayY, overlayFallbackY]: VerticalConnectionPos[] = this.menu.yPosition === 'top' ? ['top', 'bottom'] : ['bottom', 'top'];

    let offsetY = 0;

    if (this.triggersSubmenu()) {
      // When the menu is a sub-menu, it should always align itself
      // to the edges of the trigger, instead of overlapping it.
      overlayFallbackX = originX = 'end';
      originFallbackX = overlayX = 'start';
      originFallbackY = overlayY = overlayFallbackY = originY = 'top';
      offsetY = -MENU_PANEL_TOP_PADDING;
    } else if (!this.menu.overlapTrigger && originY === 'bottom') {
      overlayY = 'top';
      originFallbackY = 'bottom';
    }

    positionStrategy.withPositions([
      { originX, originY, overlayX, overlayY, offsetY },
      { originX: originFallbackX, originY, overlayX: overlayFallbackX, overlayY, offsetY },
      {
        originX,
        originY: originFallbackY,
        overlayX,
        overlayY: overlayFallbackY,
        offsetY: -offsetY
      },
      {
        originX: originFallbackX,
        originY: originFallbackY,
        overlayX: overlayFallbackX,
        overlayY: overlayFallbackY,
        offsetY: -offsetY
      }
    ]);
  }
```

Also:

```
export type MenuPositionX = 'left' | 'right';
export type MenuPositionY = 'top' | 'bottom';
```

This way, the menu by default will still open the same as before, but if you use `xPosition="right" yPosition="top"`, it will open to the right of the trigger.
![screenshot 2019-03-01 at 15 46 03](https://user-images.githubusercontent.com/3968/53645429-27338100-3c39-11e9-8016-335321fcf04b.png)

**Comment by lokeshdaiya** [comment]
Thanks @jpzwarte. I saw this method but was not able to override as its private method. Did you find any way to override it?

**Comment by jpzwarte** [comment]
The more i think about it the more i think the API needs to be different something like: `[position]="['right', 'top']"` where the first position is the primary position and the second the secondary, so:

- right, top: right side of the trigger, align to top of trigger
- top, right: top side of the trigger, align to right of trigger
- bottom, left: bottom side of the trigger align to left of trigger
etc.

@lokeshdaiya i'm working on a custom menu component (not OSS). So using material as inspiration.

**Comment by jpzwarte** [comment]
I've written the code that implements the behavior in my previous comment: https://gist.github.com/jpzwarte/5b6f848a8cbc1488779181894382f306

Feel free to use the code however you see fit (cc @crisbeto)

**Comment by AngeloETH** [comment]
@jpzwarte Have some stackblitz example? I tried to use your API but something got wrong.

**Comment by Jimit09** [comment]
Any update on this feature? I see this lacking in angular mat-menu which is very common usecase and need.

**Comment by filthyslider** [comment]
This would be a nice feature

**Comment by okeydoky** [comment]
Until the material team up the priority for this feature and actually implements it, here is an example that emulates the behavior using the existing API...

[https://stackblitz.com/edit/material-menu-right-position](url)

You may want to add some css and codes to fine tune its appearance and behavior. For example, automatically expand the nested submenu when parent menu is clicked, etc. 

Hope this helps.

**Comment by rafaelss95** [comment]
> [https://stackblitz.com/edit/material-menu-right-position](url)

@okeydoky Your url appears to be incorrect, it points to the repo issues page.

**Comment by okeydoky** [comment]
@rafaelss95  Thanks for noticing. I updated the url.

**Comment by nzbin** [comment]
You can use `matMenuTrigger` and `matMenuTriggerFor` to achieve this.

[https://stackblitz.com/edit/angular-material-menu-position-aside](https://stackblitz.com/edit/angular-material-menu-position-aside?file=src%2Fapp%2Fmenu-overview-example.html)

**Comment by gaborari** [comment]
@nzbin 
Come up with the same idea, but when the element is at the bottom of the page, the menu will open above the trigger

**Comment by jelbourn** [comment]
Tracking this via #22493 now
