### ISSUE TITLE
Datepicker out of viewport

### ISSUE THREAD

**Issue by gultyaev** [angular/components#14631]
#### What is the expected behavior?
Datepicker should be inside of the viewport and be fully rendered

#### What is the current behavior?
Sometimes it's out of viewport so that user is unable to do anything. Also it's impossible to scroll to that part that is "invisible". Moreover, sometimes datepicker is in viewport, however it's back rendered till last line and 31 Dec is out of datepicker.

#### What are the steps to reproduce?
It could be reproduced in any project that uses datepicker. The idea is to make datepicker field from the end of viewport/page on about 4/5 of datepicker calendar size. Thus, we get this 1/5 out of available space.

To reproduce the second screenshot you will need to make your window height as narrow as about 300px

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^6.1.10"
"@angular/material": "^7.2.0"
"typescript": "~2.9.2"
MacOS, Ubuntu
Chrome

#### Is there anything else we should know?
![screen shot 2018-12-25 at 10 43 05](https://user-images.githubusercontent.com/22374911/50418046-1a0da680-0832-11e9-8865-5aa9b303c32b.png)
It's bottom of the page in Chrome on macOS.
The same behaviour was observed in Chrome on Ubuntu.
![image](https://user-images.githubusercontent.com/22374911/50418310-61486700-0833-11e9-85bd-a41c507c2a05.png)

**Comment by oky1** [comment]
Same problem...

**Comment by oky1** [comment]
Any progress? Datepicker looks horrible.

**Comment by mmalerba** [comment]
If you enable the touch UI it displays as a dialog instead of popup and scrolls when it gets too small: https://oavkmmxbyma.angular.stackblitz.io/
