### ISSUE TITLE
No examples of pre-built website templates using Material for Angular

### ISSUE THREAD

**Issue by ksurendra** [angular/components#14680]
#### Please describe the feature you would like to request.
Adding examples of pre-built full website templates built with Material for Angular would be a great help for companies (especially startups and small companies) to get started with the project. For example a blog site, portfolio, simple website for a small business, etc.  

#### What is the use-case or motivation for this proposal?

- I'm a developer with little knowledge on website designing. When learning about Angular and trying to build a quick website, i could not find many examples. The main [Angular Material website](https://material.angular.io/) does not have any such examples.

- Most examples were more about "apps" and little focus on websites being built with Material. 

- We cannot build website quickly on Angular with Material without these examples. We have to build the site on Material then translate (into components) that design to Angular project. Developers need to spend a lot of time on this.

#### Is there anything else we should know?
1.  Material site has a tutorial of a full website but again we need to translate (as components) that into angular project - https://codelabs.developers.google.com/codelabs/mdc-102-web/#0

**Comment by jelbourn** [comment]
Closing this since, for the time being, we don't have any plans to create a whole-app template/seed ourselves. However, https://www.npmjs.com/package/@herodevs/fortnightly is a schematic starter for one of the Material Design app studies.
