### ISSUE TITLE
MatAutocompleteTrigger optionSelections Observable stops working

### ISSUE THREAD

**Issue by l10rdev** [angular/components#14777]
#### What is the expected behavior?
The AutocompleteTrigger.optionSelections Observable emits the value of the selected Element (and the counter increases). 

#### What is the current behavior?
The AutocompleteTrigger.optionSelections Observable does not emit a new value.

#### What are the steps to reproduce?
https://stackblitz.com/edit/autocomplete-force-selection-4cyhez?file=app%2Fapp.component.ts
1. Type 'Material' in the autocomplete field
2. Delete it.
3. Type 'Ma'
4. Select 'Mary'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular Material: 7.21, 5,2,5 .

#### Is there anything else we should know?
This is also true for other AutocompleteTrigger Observables like panelClosingActions.

**Comment by mmalerba** [comment]
I don't think it's a bug with autocomplete, you just need to add `markForCheck()` after to trigger change detection to update the counter element: https://stackblitz.com/edit/autocomplete-force-selection-pv5wgb?file=app/app.component.ts

**Comment by dliechti** [comment]
That does not solve the issue. Follow the steps I provided. If you type in 'Google' so there are no suggestions for autocomplete then delete everything again an chose an available option the counter does not increase.

**Comment by mmalerba** [comment]
Ah I see, yes I am able to reproduce it. I will re-open this issue

**Comment by turulb** [comment]
I've run into this problem after upgrading angular/material to v9. Is there any news on this issue when will this be released?

**Comment by reyazucar** [comment]
+1
