### ISSUE TITLE
Plain text as matSuffix misaligned in appearance=outline

### ISSUE THREAD

**Issue by andreasrueedlinger** [angular/components#14784]
#### What is the expected behavior?
Text as prefix/suffix is aligned with the input in a mat-form-field

#### What is the current behavior?
Text as prefix/suffix is not aligned with the input in a mat-form-field

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-matsuffix-text

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular, Material 7
Browsers: at least Chrome and FF, no others tested

#### Is there anything else we should know?
I think the misalignment comes from a workaround to align icons as prefix/suffix. It would be nice if both icons and text are aligned correctly!!

**Comment by CNicolas** [comment]
Same problem with the `fill` appearance, because the input is also vertically centered

**Comment by safwaan-menk** [comment]
Having this issue also. Is there any update on a resolution?

**Comment by mmalerba** [comment]
will post an update on #12803
