### ISSUE TITLE
MatFormField documentation should prefer outline/fill style

### ISSUE THREAD

**Issue by jelbourn** [angular/components#14792]
In the most recent Material Design update, the "standard" / "legacy" style is now omitted from the spec with only the outline and fill styles remaining. We should update our own documentation and examples to reflect this update.

**Comment by jelbourn** [comment]
This issue is just about the documentation preferring one setting over the other. Feel free to send a PR!

**Comment by MainaWycliffe** [comment]
Will do

**Comment by karismann** [comment]
I found the link to the doc if it can help : https://material.io/design/components/text-fields.html#usage
What's the default appearance for the form-field now ?  `outline` or `filled   `?

I think this default affectation of [appearance ](https://github.com/angular/material2/blob/88601fa51d581f538468a9b63890b0e285e519cb/src/lib/form-field/form-field.ts#L166)in the `MatFormField `class is also impacted, am I right ?

**Comment by mainawycliffe** [comment]
I am providing an example for both in the overview (basic) example, then using mainly outline over filled, assuming once you see the overview example you get the basic idea. The material spec isn't clear on which is the default appearance of a text field. I will send a PR tonight.

**Comment by Suresh918** [comment]
Hi jelbourn, It would be helpful if you provide the default appearance so that we can avoid further changes in the future.

**Comment by jelbourn** [comment]
@mmalerba do you have any input on this?

**Comment by mmalerba** [comment]
Yeah, we should update the docs to show outline or fill form-fields, unless the example is specifically trying to demonstrate something about one of the other appearances.

If people are looking to change the default in their app, they can do that with this injection token: https://github.com/angular/material2/blob/master/src/lib/form-field/form-field.ts#L93

**Comment by mainawycliffe** [comment]
https://github.com/angular/material2/pull/14884

**Comment by manklu** [comment]
@mainawycliffe

I think unless they are deprecated and removed they should stay in the documentation.

**Comment by Orodan** [comment]
So is that the final decision to keep the "standard" and "legacy" style in the doc ? And if that's the case is there any point in keeping the issue open :) ?

**Comment by Splaktar** [comment]
@Orodan yes there is still a point as the examples need to be updated to use filled or outline by default. The legacy/standard should only be used in the section describing the 4 different appearances. Currently only the appearance example includes fill or outline appearances. All other examples use legacy and need to be updated to fill or outline.

@mmalerba what will be the default in the future (maybe v10?) fill?

**Comment by mmalerba** [comment]
I'm fine with either fill or outline being the new default. I don't think its important which one, but its nice to have the concept of a default since that can be overridden globally with a provider to change the whole app at once.

**Comment by Splaktar** [comment]
- PR https://github.com/angular/components/pull/18222 changes the `MatFormField` examples.
- PR https://github.com/angular/components/pull/18252 changes the `ExamplesModule` to default to the `fill` appearance for all `MatFormField`s.
