### ISSUE TITLE
Custom snackbar doesn`t work with timer

### ISSUE THREAD

**Issue by VladymyrVr** [angular/components#14796]
#### What is the expected behavior?
timer work in custom snackbar teamplate

#### What is the current behavior?
timer doesn`t work in custom snackbar teamplate
http://prntscr.com/m5v285
when i change browser tab and then change tab to app i see snack with frezze timer
http://prntscr.com/m5v1k5

teamplate
<span>{{ data.body }}</span>
<countdown-timer class="timer" [end]="'2019-01-12 00:00:00'"></countdown-timer>

component 
import { Component, Inject, OnInit } from '@angular/core';
import { MAT_SNACK_BAR_DATA } from '@angular/material';

@Component({
  selector: 'app-notification-snack-bar',
  templateUrl: './notification-snack-bar.component.html',
  styleUrls: ['./notification-snack-bar.component.scss']
})

export class NotificationSnackBarComponent implements OnInit {
    constructor(@Inject(MAT_SNACK_BAR_DATA) public data: any) {}

    ngOnInit() {

    }
}

component where i call snackbar
     this.ws.connect({}, () => {
            that.ws.subscribe('/topic/notifications', (message) => {
                if (message.body) {
                    this.snackBar.openFromComponent(NotificationSnackBarComponent, {
                        data: message,
                        verticalPosition: 'top',
                        duration: 35000
                    });
                }
            });
        }, (error) => {
            error.log(error);
        });

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Closing as this is working as expected because the websocket is not calling `openFromComponent` from within the Angular zone.  While its a slightly different use case, you can see [this comment](https://github.com/angular/components/issues/7233#issuecomment-331564364) for more about what is happening.
