### ISSUE TITLE
Dynamic change in label of mat-option gives ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by alexw10** [angular/components#14793]
#### What is the expected behavior?
Error should not occur for this scenario.

#### What is the current behavior?
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null:  '. Current value: 'null: Change to localized version'.

#### What are the steps to reproduce?
**[StackBlitz](https://stackblitz.com/edit/angular-qdpdx7)**

Essentially I mimicked a similar thing that I am seeing with this stackblitz.
In the real world we have pipe that goes to a service to retrieve a localized version of a string.
What happens is we call this pipe and it goes to a service that file does a http get for a json and finds a string that is in the proper language.

Our form field select is like so:
```
<mat-form-field>
  <mat-select
    id="clinicPrefReportsDropdown"
    class="select-reports"
    [disabled]="!isButtonEnabled"
    (selectionChange)="SelectReportsChanged($event)"
    [value]="SelectedReport"
  >
      <mat-option value="ClinicPreferredReports">{{
        'ClinicPreferredReports' | localize: localizationSection
      }}</mat-option>
       <mat-option value="MyPreferredReports">{{
        'MyPreferredReports' | localize: localizationSection
      }}</mat-option>
       <mat-option value="CustomReports">{{
          'CustomReports' | localize: localizationSection
      }}</mat-option>
  </mat-select>
</mat-form-field>
```

What happens is those labels start off as null and when the service comes back with the proper string it changes it and this is where the expressed changed error comes into play. So my stackblitz simulates this with having option1 as a variable in OnInit I put a setTimeout for 2 seconds to change the string and there error comes up.

I guess I am wondering if this is truly a bug or if I need to do something different to not allow this to happen. I did get this to work by manually calling a change detection after the localize variable we have gets populated (and take the pipe out of the equation) but this is a workaround to the problem I feel like.

Any thoughts?

**Comment by alexw10** [comment]
Is this going to be checked in any time soon?

**Comment by mregni** [comment]
I could use this fix as well in my projects. Any idea if someone can check the PR?

**Comment by alexw10** [comment]
Anyone... :(?

**Comment by vmuresanu** [comment]
I had the following scenario:
```
      <mat-form-field fxFlex *ngIf="!shouldDisplaySelectSwitcher()">
          <mat-label>Amount</mat-label>
          <input formControlName="value_1" matInput [errorStateMatcher]="matcher" (input)="onValueChange($event)/>
        </mat-form-field>
        <mat-form-field fxFlex *ngIf="shouldDisplaySelectSwitcher()">
          <mat-label>Amount</mat-label>
            <mat-select formControlName="value_1" [errorStateMatcher]="matcher" (selectionChange)="onValueChange($event)">
              <mat-option *ngFor="let nr of oneToTenArray; let i = index" [value] = i+1>
                {{nr}} min
              </mat-option>
            </mat-select>
        </mat-form-field>
```
Depending on a condition I had to either display an input field or a select field. And form field was transforming into select, but when chosing an option, ExpressionChangedAfterItHasBeenCheckedError appeared always, also when converting back to input field, firing key event resulted in the same error. So I lost some time investigating the issue, and this article helped me to understand the root of the problem -> https://blog.angular-university.io/angular-debugging/. But the real solution I found on stackoverflow (sorry can't find original link), but basically
I've injected `private cdr: ChangeDetectorRef` in component's constructor and in the method:
``` 
onValueChange() { 
        this.cdr.detectChanges();
}
 ```

**Comment by 0xorial** [comment]
This is really messing with error reporting in our app. Could anyone provide a workaround?

**Comment by diosney** [comment]
Something similar happens with `mat-selection-list`, which triggers:

`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'aria-selected: true'. Current value: 'aria-selected: false'`

I fixed too by running `this.changeDetectorRef.detectChanges();` after the variable used as source for the items got updated.

**Comment by aponski** [comment]
I have the same problem in my app. I use mat-select as list filters. mat-option label has count shown. When new item is added to listy count changes and ExpressionChangedAfterItHasBeenCheckedError  is shown.

**Comment by alexw10** [comment]
Is there a way I can get this in I have enough changeDetectorRef() calls to now make me concerned and this issue is the main cause of this.

**Comment by bogacg** [comment]
I had the same error with a different localisation lib. Seeing errors like these make me sad. 😒

**Comment by alogim** [comment]
I have this same issue using `ngx-translate` on a `mat-option` object.

**Comment by candelachris** [comment]
@alogim I have the same issue with ngx-translate.

Were you able to find a workaround ?

**Comment by alogim** [comment]
@candelachris Yes, just put the function where you change your `mat-select` inside a `setTimeout` and the issue should go away.

**Comment by bohdanzhylavskyi** [comment]
> I have this same issue using `ngx-translate` on a `mat-option` object.

![image](https://user-images.githubusercontent.com/12056012/84176004-7053c100-aa89-11ea-85ee-ea428400475f.png)

**Comment by alogim** [comment]
I would like to let you know that this has been solved for me with Angular 10. @candelachris

**Comment by literalpie** [comment]
I've also run into this issue. It would be great if the linked pull request could be merged!

**Comment by deepak-codemax** [comment]
I am facing the same issue in v11

**Comment by fgoulet** [comment]
Me too, same issue in v11.

**Comment by literalpie** [comment]
[here](https://stackblitz.com/edit/mat-select-expression-changed-35uisg?file=src%2Fapp%2Fselect-exp-bug-example.html) is an updated reproduction, showing this bug in Material 12.1.4
