### ISSUE TITLE
Ripple Effect is lost for child controls if [backgroundColor] Property is set as primary for a mat-tab-group

### ISSUE THREAD

**Issue by pradeepbetty** [angular/components#14819]
#### What is the expected behavior?
Button should ripple

#### What is the current behavior?
Button Loses Ripple

#### What are the steps to reproduce?
```
https://stackblitz.com/edit/angular-material-ripple-problem?file=app%2Fripple-overview-example.html
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 7

#### Is there anything else we should know?
remove the [backgroundColor]="'primary'" of the <mat-tab-group> and the button regains its ripple

**Comment by pradeepbetty** [comment]
Check this stackblitz To see the issue:
[https://stackblitz.com/edit/angular-material-ripple-problem?file=app%2Fripple-overview-example.html](url)

**Comment by henrikcomes** [comment]
Is there any chance that this issue is getting fixed in the near future?
Looks like [this pull request](https://github.com/angular/components/pull/14857) is the solution.
