### ISSUE TITLE
mixin override for mat-slider-theme doesn't work

### ISSUE THREAD

**Issue by hags033** [angular/components#14822]
#### Bug, feature request, or proposal:
I have used mixin overrides for styling of material elements for awhile, recently the mixin for mat-slider-theme() stopped overriding base styles. I did just remove @mixin mat-slider-theme() {} and just left my class overrides in my global stylesheet and this now works. I do have other mixins in the stylesheet that work for other material elements. 

#### What is the expected behavior?
I would expect mixins to still work. 

#### What is the current behavior?
style overrides wrapped in mixin braces do not work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.1 Material 7.2.1

**Comment by mmalerba** [comment]
It looks like its working for me, here's a stackblitz: https://stackblitz.com/edit/components-issue-kgqwke?file=src/styles.scss
