### ISSUE TITLE
Which moment the datanodes of a projectTree are loaded?

### ISSUE THREAD

**Issue by TauanMatos** [angular/components#14851]
I'm trying to expand the first node of the tree. I've tried it on ngAfterViewInit and ngAfterViewChecked but the dataNode array is empty.

`ngAfterViewChecked() {
    this.treeControl.expand(this.treeControl.dataNodes[0]);
  }`

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
