### ISSUE TITLE
mat-select and mat-autocomplete options have different font sizes with custom typography

### ISSUE THREAD

**Issue by nuno-m** [angular/components#14915]
#### What is the expected behavior?
`mat-select` and `mat-autocomplete` options should have the same font size (and consequently same height), when a custom `$input` value is set via the `mat-typography-config()` function.

#### What is the current behavior?
When setting a custom `$input` value with the `mat-typography-config()`, `mat-select` options change their font-size accordingly, but the `mat-autocomplete` options ignore it, and use 16px instead (default).

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-nzfhqa?file=theme-styles.scss
On `theme-styles.scss` file, try commenting line 4, to use theme default values, or switch the `mat-typography-level` function first argument to any another value (other than 16px), and observe the changes on the `mat-select` and `mat-autocomplete` options font size.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Currently testing on Angular 7.2.1 and Material 7.2.1.

**Comment by TheBeardedLlama** [comment]
I am also encountering this issue.

I have spent quite some time looking through docs and google search, but couldn't find anything.

Could you please confirm if this is a bug and if so, any possible workarounds?

@nuno-mrks did you ever figure this out?

**Comment by nuno-mrks** [comment]
@TheBeardedLlama no, I have not. I even forked my example and update the dependencies for Angular Material 8, and this behavior still persists.
I don't think there's much we can do from the outside.

**Comment by TheBeardedLlama** [comment]
oh that's disappointing!

it's been so long now and two major versions without a fix

**Comment by msio** [comment]
any progress ?

**Comment by richardsengers** [comment]
This is still an issue

**Comment by amysorto** [comment]
There is no $input value in mat.define-typography-config anymore for the new MDC based components (available in v15). Changes were made to reflect changes to the Material Design spec. This bug should not be applicable anymore.
