### ISSUE TITLE
mat-expansion-panel re-renders multiple times in a very simple case (no animation, OnPush).

### ISSUE THREAD

**Issue by mfursov** [angular/components#14952]
#### What is the expected behavior?
mat-expansion-panel updates (renders) exactly once when there is no reason to do it multiple times.

#### What is the current behavior?
mat-expansion-panel renders at least 2 times ([@.disabled]="true"+ ChangeDetectionStrategy.OnPush)
or even more times if animation is enabled (default) and change detection mode is Default.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-rj4nhe?file=app%2Fexpansion-overview-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.2.1, Chrome 71

#### Is there anything else we should know?
It is very important not to have "unexpected" behavior (multiple rendering) because it affects performance metrics. If multiple rendering is "expected" I would suggest to mention about it in docs.

**Comment by josephperrott** [comment]
It looks like the expansion panel does not rerender entirely multiple times, though change detection seems to be run multiple times unnecessarily.

**Comment by snibbo** [comment]
Is there any workaround? My panel is jumping up and down :(
