### ISSUE TITLE
mat-grid-tile-header/footer not showing on iOS Safari

### ISSUE THREAD

**Issue by JcDenton86** [angular/components#14954]
#### What is the expected behavior?
I have a grid list which shows as it should on Safari browser on MacOs but not showing up on the mobile version. The expected behavior which works on Safari for Mac.
<img width="508" alt="expected" src="https://user-images.githubusercontent.com/1433320/51738745-8f220500-2098-11e9-8a2f-e7ebefa112db.png">

#### What is the current behavior?
<img width="413" alt="missing header" src="https://user-images.githubusercontent.com/1433320/51738757-9517e600-2098-11e9-9a6f-2296ff14c2bb.png">

However the bar is there but not showing because I have placed action buttons and when I click on them they trigger the actions. In the screenshot below, there is a button (not showing) which opens a menu with selections. 

<img width="381" alt="action" src="https://user-images.githubusercontent.com/1433320/51738191-3736ce80-2097-11e9-9c06-28fd6e5f836e.png">

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz: https://stackblitz.com/edit/angular-material2-issue<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Version: 
- Angular 6, 
- Angular Material 6.4.6, 
- iOS 12.1, 
- TypeScript 2.7.2, 
- Safari iOS

**Comment by crisbeto** [comment]
It's difficult to reproduce based on your screenshot. Can you post your markup?

**Comment by JcDenton86** [comment]
Hi, 
I am using Fuse template (built with Angular material). There is no any custom markup for this component

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template, which includes a StackBlitz or GItHub repo reproduction of the problem. 

Please file a new issue that follows the template and includes a reproduction. This gives the team the information needed to investigate the bug or prioritize the enhancement.
