### ISSUE TITLE
CDK: Add lazy-load of images

### ISSUE THREAD

**Issue by moniuch** [angular/components#15012]
#### Please describe the feature you would like to request.
I would like to see fully-fledged lazy-load support for images

#### What is the use-case or motivation for this proposal?
Applications need to lazy load many resources, it is a very basic need nowadays, and lazy-loading images seems to be the most typical scenario.

#### Is there anything else we should know?
By full-fledged I mean it should have the following features:

- handle img, srcset and background-images
- export directive so that other elements can link to current status (such as skeleton components could be removed when image has loaded, for instance)
- apply user-provided classes for loading and loaded states
- be compatible with SSR
- be based on IntersectionObserver
- provide clear documentation as per necessity of installing, importing IntersectionObserver (and possibly other observers) polyfills

There are a couple of libraries out there for Angular (such as `ngx-lazy-load-images` - very nice simple API), none of them delivers a complete feature set, some are no longer maintained.

**Comment by crisbeto** [comment]
This should be covered by the upcoming image component in `@angular/common` https://github.com/angular/angular/tree/1314b1cc62488a0b17b1e57afc9c4d5e21408c2d/packages/common/src/directives/ng_optimized_image.
