### ISSUE TITLE
Input autocomplete styling doesn't fill entire form field

### ISSUE THREAD

**Issue by terrybrash** [angular/components#15025]
#### What is the expected behavior?
When using autocomplete in `matInput`, the browser's autocomplete styling should fill the entire form field.
![image](https://user-images.githubusercontent.com/47312/50874350-bb2b5e00-13e9-11e9-8ff8-7c63c8266c07.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/530129/52014762-6477e800-24ae-11e9-8907-79550e8de1aa.png)

#### What are the steps to reproduce?
https://angular-material2-issue-on2neb.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 7.2.1
@angular/material: 7.3.0
typescript: 3.2.2
OS: Windows 10
Browser: Google Chrome 71

#### Is there anything else we should know?
[material-components-web](https://github.com/material-components/material-components-web) had some [similar issues with autocomplete styling](https://github.com/material-components/material-components-web/issues/2802) which were fixed in [this pull request](https://github.com/material-components/material-components-web/pull/4232).

**Comment by mmalerba** [comment]
I don't actually see anything in the [spec](https://material.io/design/components/text-fields.html) that mentions what the autofill state should be, but we do have some [CDK utilities](https://material.angular.io/cdk/text-field/overview) that can help with detecting autofill and applying custom styles

**Comment by LeonardoRochaInacio** [comment]
I had the same problem, what I did to solve was insert 

input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
  transition: background-color 5000s;
  -webkit-text-fill-color: #fff !important;
}

on my variables.scss. it will make your auto fill background transparent.

hope this can help u
