### ISSUE TITLE
Only the first svgIcon appears when registered with MatIconRegistry

### ISSUE THREAD

**Issue by aliasbody** [angular/components#15045]
#### What is the expected behavior?
When we register 2 or more icons with MatIconRegistry we should, when called, see them all

#### What is the current behavior?
Only the first one appears

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Register two icons on app.module or in a parent component (like app.component)
``` 
 constructor(
    public matIconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    this.matIconRegistry.addSvgIcon('svg-google', sanitizer.bypassSecurityTrustResourceUrl('/assets/logos/svg-google.svg'));
    this.matIconRegistry.addSvgIcon('svg-asana', sanitizer.bypassSecurityTrustResourceUrl('/assets/logos/svg-asana.svg'));
  }
```

And then in the HTML component simply call them one after the other
```
<mat-icon svgIcon="svg-google"></mat-icon>
<mat-icon svgIcon="svg-asana"></mat-icon>
```

The result is this:
![imagem](https://user-images.githubusercontent.com/9455122/52089368-4ab9cc00-25a6-11e9-9f13-188009c289f6.png)
![imagem](https://user-images.githubusercontent.com/9455122/52089374-4ee5e980-25a6-11e9-9496-9835f2f1b29d.png)

If we invert the order like this:
```
<mat-icon svgIcon="svg-asana"></mat-icon>
<mat-icon svgIcon="svg-google"></mat-icon>
```

The result is this:
![imagem](https://user-images.githubusercontent.com/9455122/52089450-76d54d00-25a6-11e9-964e-e591bd02a78d.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.1
Material 7.2.1
TypeScript 3.1.6
Browsers (Chrome and Firefox, latest)

**Comment by aliasbody** [comment]
@crisbeto Here is the example:
https://material2-issue-15045.stackblitz.io

It's having exactly the same issue, you can see it by reordering the icons on the app.component.html, the first one appears and the second one won't.

**Comment by clundberg1** [comment]
I can confirm the same thing happened to me. I was only able to register a single svg. Once I registered multiple ones, all the mat-icon components rendering svgs would render the exact same svg, usually the second registered one. Checking the network tab, they were making correct requests, so I'm not sure what the problem was. I had to go back to use material icons.

**Comment by jelbourn** [comment]
@aliasbody looking at the stackblitz, the icon is indeed being put in the DOM. It seems like it might be a problem with the SVG itself?

**Comment by aliasbody** [comment]
@jelbourn 

Here is the result: https://material2-issue-15045.stackblitz.io/

- The first line is the same svg (from inkscape) but loaded with **img** as you can see, both are visible. 
- The second line is the same svg (from inkscape) but loaded with mat-icon and svgIcon (don't load all)
- The third line is a "simplified" svg from Inkscape (to ressemble a little bit more the ones I've found in the internet, but loaded with svgIcon, same issue
- The fourth line is icons I've found in the internet and that seem to load correctly.

This seems to be a bug in mat-icon since the img one work perfectly.

**Comment by crisbeto** [comment]
@aliasbody the issue might be due to some of your icons having duplicate IDs. E.g. both the Google and Asana logos have a gradient with an `id === 'a'`. This isn't an issue when loading through an `img` tag, because the SVG elements aren't added to the DOM.

**Comment by forssri** [comment]
Faced the same issue today, and found infact the id references in the svgs were the problem. We need to ensure the id and path references inside each of the svg is unique.

**Comment by jelbourn** [comment]
@aliasbody could you check that the duplicate IDs are the issue?

**Comment by ZumelzuR** [comment]
I have the same issue and I can confirm that the problem was the duplicate ID, yo have to be sure that the <path> id, <mask> id are different so my two svg are like 

`...
    <defs>
        <path id="a" d="M3.."/>
    </defs>
    <g fill="none" fill-rule="evenodd" transform="translate(13 33)">
        <mask id="b" fill="#fff">
            <use xlink:href="#a"/>
        </mask>
        <g fill="#303030" mask="url(#b)">
         ...
        </g>
    </g>
</svg>
`
and I changed it to
`
<defs>
        <path `**id="g"**` d="M3.."/>
    </defs>
    <g fill="none" fill-rule="evenodd" transform="translate(13 33)">
        <mask `**id="h"**` fill="#fff">
            <use xlink:href="`**#g**`"/>
        </mask>
        <g fill="#303030" mask="`**url(#h)**`">
         ...
        </g>
    </g>
</svg>
`
and works for me. (I bolded the changes).

Hope that helps you

**Comment by HiranyaKireety28** [comment]
Hi All, 

I am facing the same issue and I changed the svg ids. It didn't help. Can someone please help

**Comment by ZumelzuR** [comment]
Can you copy the code? Maybe you are missing something.

**Comment by aliasbody** [comment]
Changing the ID's didn't solved it for me.
