### ISSUE TITLE
Table Documentation includes nonfunctional/incomplete 'viewChange' feature

### ISSUE THREAD

**Issue by tdietrich513** [angular/components#15059]
The [documentation](https://material.angular.io/components/table/api#MatTable) for the MatTable component includes information about a 'viewChange' subject that will emit the currently visible top and bottom row numbers, but the functionality is [not implemented](https://github.com/angular/material2/blob/master/src/cdk/table/table.ts#L349). 

#### What is the expected behavior?
The functionality of the component should match the documentation.

#### What is the current behavior?
The functionality of the component does not match the documentation.

#### What are the steps to reproduce?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All of them.

#### Is there anything else we should know?
Keep being awesome.

**Comment by literalpie** [comment]
Closed in #15068

**Comment by crisbeto** [comment]
Closing since it was addressed in #15068.
