### ISSUE TITLE
Drag And Drop Wrong Index Bug

### ISSUE THREAD

**Issue by ozanturhan** [angular/components#15054]
Hi, i am using drag and drop on regular table and hide some columns with css (display:none). At start drop event giving correct indexes. But if i hide any column drop event giving wrong indexes.

#### What is the expected behavior?
İf i want to move a column to start of the table drop event must give 0 for index number. 

#### What is the current behavior?
After hide any column İf i want to move a column to start of the table drop event giving greater then 0 for index number. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material-table-drag-drop-bug

![table-bug](https://user-images.githubusercontent.com/5039606/52112836-c94f5180-2618-11e9-8d6a-7d26d475dafe.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
{
  ...
  "dependencies": {
    "rxjs": "6.4.0",
    "moment": "2.24.0",
    "core-js": "2.6.3",
    "zone.js": "0.8.29",
    "hammerjs": "2.0.8",
    "@angular/cdk": "7.3.0",
    "@angular/core": "7.2.3",
    "@angular/http": "7.2.3",
    "@angular/forms": "7.2.3",
    "@angular/common": "7.2.3",
    "@angular/router": "7.2.3",
    "@angular/compiler": "7.2.3",
    "@angular/material": "7.3.0",
    "web-animations-js": "2.3.1",
    "@angular/animations": "7.2.3",
    "@angular/platform-browser": "7.2.3",
    "angular-in-memory-web-api": "0.5.4",
    "@angular/material-moment-adapter": "7.3.0",
    "@angular/platform-browser-dynamic": "7.2.3"
  },
  ...
}

**Comment by RavindraGp** [comment]
Even I am facing the same issue. Is there any workaround for this?

**Comment by kcebula** [comment]
If you are hiding it just by using hidden, then item still exists in array, so the index is calculated accordingly to all items as if hidden item was there.
[stackblitz](https://stackblitz.com/edit/angular-material-table-drag-drop-bug-epkjpb)

**Comment by mozanturhan** [comment]
I don't want to remove from array. The problem is here.

**Comment by kcebula** [comment]
Then, I guess, you cannot expect indexes provided in event to be correct (since they are based on provided array). You can still calculate indexes on your own

**Comment by Jonatino** [comment]
@ozanturhan did you ever find a fix for this? Experiencing the same thing right now when using [hidden] to hide some dom elements.

**Comment by hlawuleka** [comment]
> Then, I guess, you cannot expect indexes provided in event to be correct (since they are based on provided array). You can still calculate indexes on your own

I think this is cheap, how would you calculate those indexes when you cannot programmatically track the source and destination elements?

**Comment by mrvini** [comment]
This issue still exists almost more than 6 months later. I have a similar situation with draggable table rows
```
 <mat-table #table [dataSource]="dataSource.items" [cdkDropListData]="dataSource.items" matSort 
          cdkDropList (cdkDropListDropped)="drop($event)">
     <!-- more columns here -->
    <mat-header-row *matHeaderRowDef="displayedColumns; sticky: true"></mat-header-row>
            <mat-row *matRowDef="let row; columns: displayedColumns;"
            [class.hidden]="showHideRow(row)"
            cdkDrag [cdkDragData]="row"></mat-row>
</mat-table
```

when some of the rows are hidden and reorder of the rows in the table happen, the indexes that I get are completely off, it's almost like all hidden rows are moved to the top and visible rows are appended at the end of the data source array, any potential fix or approach? because indexes are completely off, its much harder to reorder things, defeats the purpose of this great drag / drop component, are there any updates on resolving this issue?

**Comment by ozanturhan** [comment]
@mrvini 
I decided not to drag and drop the sorting process in the table header. I added settings dialog for the table. I'm doing the sorting process in this dialog.
