### ISSUE TITLE
MatTabNav unexpected bahavior

### ISSUE THREAD

**Issue by madmurl0c** [angular/components#15071]
#### What is the expected behavior?
I expect the MatTabNavBar element to show the scroll indicators on the left/right side once it becomes too wide for the current view as the normal MatTabGroup does

#### What is the current behavior?
The labels are getting pushed together until they disappear

#### What are the steps to reproduce?
I modified the original tab example to show what I mean, just resize it and see how it reacts.

https://stackblitz.com/edit/angular-n3nlp2

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.3
Material: 7.3.0
Typescript: 3.2.4

Debian (testing):
Chromium: 71.0.3578.98
Firefox: 65.0

Windows (10 / 1709):
Firefox: 60.5.0 ESR

![image](https://user-images.githubusercontent.com/42262826/52201872-19beed00-286d-11e9-9e45-4f242f65504a.png)

**Comment by onlyanup** [comment]
Any update on this one?

**Comment by madmurl0c** [comment]
@onlyanup It has been fixed with one of the more recent versions.

Here is an example with v8.2.1 where the issue is fixed https://stackblitz.com/edit/angular-n3nlp2-vv1nve

**Comment by madmurl0c** [comment]
@onlyanup It has been fixed with one of the more recent versions.

Here is an example with v8.2.1 where the issue is fixed https://stackblitz.com/edit/angular-n3nlp2-vv1nve
