### ISSUE TITLE
Can't save local date with datepicker.

### ISSUE THREAD

**Issue by aspramsh** [angular/components#15104]

**Comment by aspramsh** [comment]
I am using material's datepicker. When I select date, everything is ok, but after passing it to the server I get the previous day, that is 4 hours before, my time zone is UTC + 4. How can I make it not to subtract 4 hours?

**Comment by mehmetkarpuz** [comment]
Try using string instead of datetime in backend

**Comment by ZhiyueYi** [comment]
I have the same problem and I found a solution from here: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

I added the following code to the module providers and then it works.

`
providers: [
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } }
]
`

**Comment by mmalerba** [comment]
The datepicker returns `Date` instances (or `Moment` instances if using the moment date adapter). It's up to you to decide how these are stringified and stored in your backend.
