### ISSUE TITLE
feat(chips): support outlined chips

### ISSUE THREAD

**Issue by amitport** [angular/components#15156]
#### Please describe the feature you would like to request.
please implement outlined chips as specified in https://material.io/design/components/chips.html#specs
(action and input variants would be nice, there is some difference in behavior. For instance, outlined action chips are not elevated when pressed)

#### What is the use-case or motivation for this proposal?
they look nice and are part of the spec

#### Is there anything else we should know?
thank you!

**Comment by Nodarii** [comment]
As workaround we can use `<mat-basic-chip>`, but I would expect angular-material to have components that described in specification by default, without any customization from consumer side

**Comment by amitport** [comment]
Could you please not close this without explaining why the angular component team does not plan on supporting the spec in this regard.

**Comment by amysorto** [comment]
Closing this issue since chips have an outline in M3
