### ISSUE TITLE
Pinch event does no longer work when MatTooltipModule is imported

### ISSUE THREAD

**Issue by ClemensSchneider** [angular/components#15162]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Pinch event should work.

Importing MatTooltipModule should have no impact on events that are specified in `@angular/platform-browser`.

#### What is the current behavior?
pinch events are no longer fired.

#### What are the steps to reproduce?
https://angular-vcghq7.stackblitz.io/ (use a touch-enabled device to test pinching)

Removing the `MatTooltipModule` import from `app.module.ts` makes pinching work again.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least @angular/material@^7

#### Is there anything else we should know?
Seems like the following commit introduced a provider for `HAMMER_GESTURE_CONFIG` that does not register `pinch` events: https://github.com/angular/material2/pull/12941/commits/866c1418c6bb5058433acd8225d942e201cf5958

Also, this provider seems to alter the way hammer-js related gestures are interpreted for the complete application.

See https://github.com/angular/material2/blob/master/src/lib/core/gestures/gesture-config.ts

**Comment by ClemensSchneider** [comment]
Workaround for this issue is to register a custom `HAMMER_GESTURE_CONFIG` instance which is based on the material one.

```
import { GestureConfig, HammerInstance } from '@angular/material';
import * as hammer from 'hammerjs';

/**
 * This gesture config adds the missing pinch recognizer to the material GestureConfig.
 * See https://github.com/angular/material2/issues/15162
 */
export class PatchedGestureConfig extends GestureConfig {

  buildHammer (element: HTMLElement): HammerInstance {
    const mc = <HammerManager> super.buildHammer(element);

    const pinch = new hammer.Pinch();
    mc.add(pinch);

    return <HammerInstance> mc;
  }
}
```

Provide it in your module via
```
import { HAMMER_GESTURE_CONFIG } from '@angular/platform-browser';
.....
      providers: [
        {
          provide: HAMMER_GESTURE_CONFIG,
          useClass: PatchedGestureConfig
        }
      ]
```

**Comment by ClemensSchneider** [comment]
No reaction at all? As it is totally unexpected to loose pinch-events when using material tooltips, it should be addressed...

**Comment by jelbourn** [comment]
FWIW we plan on removing our use of HammerJS by Angular v9

**Comment by eltharynd** [comment]
The exact same behaviour happens when importing
MatSlideToggleModule

just lost 2 hours T_T

**Comment by crisbeto** [comment]
Closing since this shouldn't be an issue anymore, because we've stopped using Hammer completely.
