### ISSUE TITLE
Autocomplete: https://material.angular.io/components/autocomplete/overview weird behavior with simple autocomplete

### ISSUE THREAD

**Issue by sirkhin** [angular/components#15177]
#### What is the expected behavior?
Ideally you should be given a choice: what should be the behavior when you click on autocomplete. But current behavior at least looks pretty unfriendly to user (from my point of view).

#### What is the current behavior?
Currently you're only able to open autocomplete again if you eith focus any other control and then focus autocomplete again; or remove the character from the selected option

#### What are the steps to reproduce?
https://material.angular.io/components/autocomplete/overview

1) go to https://material.angular.io/components/autocomplete/overview#simple-autocomplete
2) select any value
3) try to open autocomplete again

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I believe the latest version of Angular

**Comment by crisbeto** [comment]
For what it's worth, you can also reopen it by pressing the up or down arrow keys.

**Comment by viaches** [comment]
Shame on me... Not sure if this ticket is still actual then. But just to clarify: Is it possible to review my option (declare the behavior of autocomplete when we click on while some option is selected) ? Or it's quite complicated and not an option here?

**Comment by crisbeto** [comment]
It shouldn't be complicated and comparing the UX to the autocomplete on the Google Search, it also reopens when you click on it again. @jelbourn should we try to match the UX from Google Search?

**Comment by jelbourn** [comment]
@crisbeto I don't quite follow- are the steps
1. Type something
2. Select an option with the keyboard
3. Click the input again
?

**Comment by crisbeto** [comment]
Yes. our autocomplete won't reopen when you click on it while it still has focus since we depend on the `focus` event.

**Comment by jelbourn** [comment]
That seems reasonable, though I don't think it's the highest priority change
