### ISSUE TITLE
Stepper step from data is not unique for each step when used *ngfor

### ISSUE THREAD

**Issue by vijam** [angular/components#15172]
#### What is the expected behavior?
each step should be having unique form data of step.

#### What is the current behavior?
all the steps is with single step data 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material-stepper212?file=app%2Fstepper-overview-example.html

#### Is there anything else we should know?
nope

**Comment by josephperrott** [comment]
After reading through the issue, I am not quite sure the issue you are seeing?  Can you expand a bit on the issue and what you are seeing vs what you expect to see?

**Comment by josephperrott** [comment]
Closing as this issue seems a bit outdated and we aren't really able to take any action on the current information.  If you are still having an issue feel free to open another issue in the repo.
