### ISSUE TITLE
Simple List of supported colors in docs

### ISSUE THREAD

**Issue by tayambamwanza** [angular/components#15188]
#### Please describe the feature you would like to request.

I would like to have a reference of supported color options for Angular Material themes on the official Angular Material Docs.

#### What is the use-case or motivation for this proposal?

This will make it easier to identify what colors are available and also make comparisons.

It's frustrating digging into the node modules folder to see what colors are supported.

#### Is there anything else we should know?

The layout of the list could have something like: 

**Color Name** - Hex Code - Color Chip (Demonstrating what the primary color looks like)

e.g

*All colors are 500 shade*

**$mat-red** - #F44336 - Square Color chip

**Comment by jelbourn** [comment]
The recent rewrite of the theming guide for Angular v12 should make this more explicit. While the colors are directly listed, we link out to their definition on the Material Design site.
