### ISSUE TITLE
[form-field] rounded corners

### ISSUE THREAD

**Issue by Nodarii** [angular/components#15189]
#### Please describe the feature you would like to request.
Allow to round corners in form-field component.

#### What is the use-case or motivation for this proposal?
Material design specification - https://material.io/design/components/text-fields.html#theming

#### screenshot 1
![image](https://user-images.githubusercontent.com/1251685/52788133-b13fef00-3068-11e9-95c1-da0aed2a393f.png)

#### screenshot 2
![image](https://user-images.githubusercontent.com/1251685/52788202-e5b3ab00-3068-11e9-8c6e-fed870bd9eca.png)

**Comment by andrewseguin** [comment]
You can use CSS overrides to round the corners more than 4px if you want: https://stackblitz.com/edit/angular-ukuhn6?file=app/form-field-appearance-example.css

**Comment by Nodarii** [comment]
@andrewseguin, 
It is ok as temporary solution, but is not ok as permanent (as it not gonna work with native view encapsulation). 
PS: ::ng-deep and /deep/ are deprecated - https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep. I can not rely on it
