### ISSUE TITLE
Developer guide (e2e test) is broken

### ISSUE THREAD

**Issue by volago** [angular/components#15198]
#### What is the expected behavior?
`gulp e2e` runs e2e tests or provide new instructions (for bazel?)

#### What is the current behavior?
Acording to Developer guide (https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md) one can run e2e tests by command `gulp e2e`.

Unfortunately I've got error:
`[14:20:12] Using gulpfile C:\git\material2\gulpfile.js`
`[14:20:12] Task 'e2e' is not in your gulpfile`
`[14:20:12] Please check the documentation for proper gulpfile formatting`

In fact there is not e2e task in source code.

**Comment by devversion** [comment]
@volago Thanks for the issue. Yeah we've removed most parts of the gulp setup. I will try to update the instructions soon.

**Comment by volago** [comment]
@devversion Could you provide a fast draft how to run e2e tests?

**Comment by devversion** [comment]
@volago Sure.

1) Install Bazel
2) Go into project directory
3) Run `bazel test e2e/...` (this will be slower initially; but Bazel builds are incremental afterwards)

**Comment by devversion** [comment]
This should be fixed now. We use `yarn e2e` and Bazel comes installed within the node modules.
