### ISSUE TITLE
bottom-sheet add disabledNavigationOnOpened feature

### ISSUE THREAD

**Issue by yuxingz** [angular/components#15193]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When the navigation is back or forwarded, only the bottom-sheet is closed and the navigation does not change.

#### What is the current behavior?
The bottom sheet is closed, but the navigation has changed.

#### What is the use-case or motivation for changing an existing behavior?
Let the bottom sheet add a more user-friendly configuration.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 7.0.0
Material - 7.1.1
OS: Windows 10
Typescript: 3.1.1
Browsers - All

#### Is there anything else we should know?
I am trying to add canDeactived guard to the route.but cannot be perfectly controlled bottom sheet. After closing the bottom sheet, there is a problem opening it again.

**Comment by jelbourn** [comment]
Closing this since I don't think it's something we can actually do at the component level- this would require hooking up to the router to accomplish.
