### ISSUE TITLE
Customize the size of the slide thumb

### ISSUE THREAD

**Issue by UmutAkkaya** [angular/components#15202]
#### Please describe the feature you would like to request.
The size of the thumb should be cuztomizable to be able to present more information. Right now when displaying 6 digit numbers it glitches out. Even shortening it as 26.5k i.e. looks bad without proper padding. Please refer to the image below.
![image](https://user-images.githubusercontent.com/10002102/52876426-2f61cb80-3125-11e9-91f7-0e5d43108f1b.png)

I have tried playing with the styles to fix the problem, but the animation and the placement of the thumb is broken when styles are changed: 
![image](https://user-images.githubusercontent.com/10002102/52876278-c8441700-3124-11e9-868e-128385563e3c.png)

#### What is the use-case or motivation for this proposal?
To display the exact value and to add customizability.

**Comment by jelbourn** [comment]
Closing this since I don't see us adding support for the feature unless it's added to the material design spec.
