### ISSUE TITLE
[Tabs] Hidden tabs, expansion panels closed up directly after open

### ISSUE THREAD

**Issue by AhmedQerem** [angular/components#15223]
**What is the expected behavior?**
User should be able to open the expansion panels in the hidden tabs.

**What is the current behavior?**
Expansion panels in hidden tabs expand and close up directly after click.
 
**What are the steps to reproduce?**
1- Create tab group with multiple tabs.
2- Add accordion and data table to each tab.
3- Navigate to a hidden tab.
4- Click to expand the accordion.
5- Accordion will expand and close directly (should be still open). 

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
Angular Material: 7.3.1
Angular: 7.3.1

**Comment by josephperrott** [comment]
Closing as this should be corrected in the latest version with changes to how the initial animations are handled for expansion panels
