### ISSUE TITLE
cdkVirtualFor does not work in ng-content

### ISSUE THREAD

**Issue by vthinkxie** [angular/components#15277]
#### What is the expected behavior?

when `*cdkVirtualFor` in ng-content, and `cdk-virtual-scroll-viewport` in parent component, everything works fine.

#### What is the current behavior?

when `*cdkVirtualFor` in ng-content, and `cdk-virtual-scroll-viewport` in parent component, error happend
```
ERROR
Error: StaticInjectorError(AppModule)[CdkScrollable -> CdkVirtualScrollViewport]: 
StaticInjectorError(Platform: core)[CdkScrollable -> CdkVirtualScrollViewport]: 
NullInjectorError: No provider for CdkVirtualScrollViewport!
```

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>

https://stackblitz.com/edit/angular-oqcthb?file=src/app/app.component.html

**Comment by vigpatrick** [comment]
Any news on this ?

**Comment by gigalala** [comment]
Yea any news?

**Comment by nutrimax1987** [comment]
Any News ??

**Comment by xpleria** [comment]
Same issue

**Comment by slarrieu** [comment]
Any news?

**Comment by WaffleBuffer** [comment]
Any news ?

**Comment by MiroKov** [comment]
any news?

**Comment by jeetparikh** [comment]
Any updates? Same issue..

**Comment by mmalerba** [comment]
This is a limitation of Angular's content projection. https://github.com/angular/angular/issues/37319 has been filed to hopefully improve some of the short-comings

**Comment by eddietisma** [comment]
Here is a working example of the above provided stackblitz. It's not 100% but should provide a somewhat feasable strategy.

- The `VirtualForDirective` provides the template used for stamping out items.
- The `VirtualForDirective` provides a reference (viewContainerRef), later used to replace content.
- The `VirtualScrollViewportComponent` providers a wrapper containing the real CDK scrolling.
- The `HelloComponent` uses `AfterContentInit `to connect get a hold of `VirtualForDirective` and attach it to the viewport.

https://stackblitz.com/edit/angular-yq1gya
