### ISSUE TITLE
Mat-toolbar issue when using component selector as placeholder for mat-toolbar-row

### ISSUE THREAD

**Issue by willmcf** [angular/components#15278]
#### What is the expected behavior?
The `mat-toolbar` should either:
-  render each `mat-toolbar-row`, even if it's within a separate component.
-  raise an error when a `mat-toolbar-row` is within a `router-outlet`.

#### What is the current behavior?
In both of the above use cases, the toolbar rows are "jumbled" and, for issue-1 the now familiar console error regarding "mixed toolbar modes" is raised. However, no errors are raised when a `router-outlet` is used in lieu of a component selector. This was my original problem and the lack of error reporting was unhelpful. I eventually distilled the problem to its simplest use case.

#### What are the steps to reproduce?
[Here in Stackblitz](https://stackblitz.com/edit/angular-dhw5fp)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.2
Node: 10.13.0
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cdk                      7.3.3
@angular/cli                      7.3.2
@angular/material                 7.3.3
@ngtools/webpack                  7.3.2
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by jelbourn** [comment]
This is not something we're directly support in a component, but you can use `ngProjectAs` to project custom content in the place of an expected API. 

https://angular.io/guide/content-projection#projecting-content-in-more-complex-environments
