### ISSUE TITLE
trying to upgrade stackblitz bug repro starter to 7.3.3 causes error

### ISSUE THREAD

**Issue by mtaran-google** [angular/components#15304]
changed the version number in the stackblitz starter (https://goo.gl/wwnhMV) to 7.3.3 (https://stackblitz.com/edit/angular-material2-issue-hetfrx?file=package.json), got error:

```
Error in /turbo_modules/@angular/material@7.3.3/bundles/material.umd.js (38:5)
Object prototype may only be an Object or null: undefined
```

**Comment by manklu** [comment]
You should update the cdk too.

**Comment by mtaran-google** [comment]
I tried that before and it causes a different error. My higher level request here is: please update the stackblitz link so that it actually points to the most recent version of the library, since that's (hopefully) what people should be making repros against.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
