### ISSUE TITLE
Make BottomSheet more generic and reusable

### ISSUE THREAD

**Issue by DaSchTour** [angular/components#15314]
#### Please describe the feature you would like to request.
It would be great if BottomSheet would be more generic. I think it could be useful to have something like an abstract sheet module that contains the base behavior and that can be extended to implement different variations of this pattern.

#### What is the use-case or motivation for this proposal?

I need the same kind of behavior but would like to have it displayed as a full-viewport-height side-modal from the right.
For now I'll copy the BottomSheet module and will have to change just a few things I guess.

**Comment by supruniuk** [comment]
I've been waiting for a side sheet for a long time.

**Comment by DaSchTour** [comment]
Well, I guess the problem is, that they haven't used material for custom app development. There are enough cases were sidenav isn't the right solution, as it should be just created and opened on demand just like an overlay or the bottom sheet. So I don't want to have a sidenav all the time and just create it on demand in the context I currently need.

**Comment by andrewseguin** [comment]
Re-opening the feature request #13070 and marking this as a dupe
