### ISSUE TITLE
Change color of slider ticks partially

### ISSUE THREAD

**Issue by pycraft114** [angular/components#15323]
#### Please describe the feature you would like to request.

a feature that can change color of the slider ticks partially. For example, there is a slider ranged 1 to 100, and I would like to change the color of the tick starting 4 to 20. 

#### What is the use-case or motivation for this proposal?

Im mapping a sequential images with material slider and I want to show users that an image is modified by coloring its slider tick

#### Is there anything else we should know?

is it already possible to do this?

**Comment by jelbourn** [comment]
Closing this since we don't plan on supporting this feature. In our upcoming MDC-based slider, the ticks take on a different appearance more aligned with recent updated to the material design spec.
