### ISSUE TITLE
Documentation navbar selectbox show wrong version

### ISSUE THREAD

**Issue by surfer19** [angular/components#15321]
https://material.angular.io/

#### What is the expected behavior?
Option 7.2.0 in navbar select is replaced by 7.3.1

#### What is the current behavior?
Select show 7.2.0 that doesn't exist.
After click at select in navbar, show version 7.2.0 
When I click to 7.2.0 it set active item to 7.3.1

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, Google Chrome 72.0.3626.119

#### Is there anything else we should know?
No

**Comment by josephperrott** [comment]
Closing as obsolete
