### ISSUE TITLE
Expansion panel indicator / chevron misalignment when panel is opened & closed

### ISSUE THREAD

**Issue by mcenkar** [angular/components#15326]
#### What is the expected behavior?
Chevron/Expansion trigger should be correctly vertically aligned with expansion panel title.

#### What is the current behavior?
https://angular-8f8etn.stackblitz.io/

Too low when closed
![image](https://user-images.githubusercontent.com/11230749/53491353-8016e400-3a96-11e9-9c63-175fb3be7db3.png)

Too high when opened
![image](https://user-images.githubusercontent.com/11230749/53491382-8efd9680-3a96-11e9-8995-94792b1a8056.png)

#### What are the steps to reproduce?
https://angular-8f8etn.stackblitz.io/

Resize browser window

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7

**Comment by crisbeto** [comment]
Should be sorted out by https://github.com/angular/material2/pull/10503.

**Comment by YoungCatChen** [comment]
Hi – may I know the status of this issue? It seems the chevron misalignment issue persists in the newest version and the fix #10503 wasn't merged.

**Comment by MikeJerred** [comment]
I am currently using this workaround in my `styles.scss` for all projects that use angular material:
```scss
.mat-expansion-indicator::after {
  transform: translateY(-3px) rotate(45deg);
}
```

**Comment by crisbeto** [comment]
Closing since this was fixed in the M3 version of the expansion panel.
