### ISSUE TITLE
MatCalendar component is missing documentation

### ISSUE THREAD

**Issue by brunovinicius** [angular/components#15353]
Please provide proper documentation for MatCalendar. Today it is possible to inline a calendar but theres no mention of this on the official docs.

#### What is the use-case or motivation for this proposal?
Wider knowledge about the component and how it works.

#### Is there anything else we should know?
Nope.

**Comment by andrewseguin** [comment]
Thanks for the feature request to improve our docs. We'd be happy to have any pull request contributions that help us

**Comment by dwilches** [comment]
It's been almost 2 years and there are no docs about this, even though multiple users have asked for it: 15353 (this), 20931, and 20031.
I think Angular's Team answer should not be to rely indefinitely in a community PR but to document it (it's been 2 years waiting for a PR).

Nonetheless, if you can point me in the right direction I can write that PR so other people don't need to spend time reading the source code to figure out how to use this component. Do you have an example of another PR that added documentation?

Thanks.
