### ISSUE TITLE
package.json doesn't allow installation of Angular version 8 prerelease

### ISSUE THREAD

**Issue by StephenFluin** [angular/components#15376]
Steps:
Take a 7.x project with Material installed.
ng update @angular/core @angular/cli --next

#### What is the expected behavior?
Angular is updated and Material is left at 7.x

#### What is the current behavior?
```
ng update @angular/cli @angular/core --next
                  Package "@angular/material" has an incompatible peer dependency to "@angular/animations" (requires ">=7.0.0", would install "8.0.0-beta.6").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0", would install "8.0.0-beta.6").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0", would install "8.0.0-beta.6").
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.x

#### Is there anything else we should know?
https://jubianchi.github.io/semver-check/#/%3E7.0.0/8.0.0-beta.0
The comparison in package.json to >7.0.0 doesn't match 8.0.0-beta.0 of Angular :(

**Comment by StephenFluin** [comment]
I know it's wonky, but maybe `^7.0.0 ^8.0.0-0 ^9.0.0-0`might match the versions we want?

**Comment by djleonskennedy** [comment]
@StephenFluin could you explain, why is it is a bug ?

**Comment by StephenFluin** [comment]
I feel this is a bug because developers who want to try out Angular 8.0.0-beta via `ng update` are prevented from doing so by the mismatched package versioning if they use material.

**Comment by djleonskennedy** [comment]
@StephenFluin I believe that `ng update` have to be used to update old version to latest not for update to "beta, alpha etc", You can check available versions here for update https://update.angular.io/

**Comment by josephperrott** [comment]
Closing as this state is out of date and we have updated how we define our `package.json` going forward

**Comment by mackelito** [comment]
Hmm.. I was about to do some updates and face similar issues...
```
Fetching dependency metadata from registry...
                  Package "@angular/material" has an incompatible peer dependency to "@angular/animations" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-next.2").
                  Package "@angular/material" has an incompatible peer dependency to "@angular/forms" (requires "^8.0.0 || ^9.0.0-0" (extended), would install "8.2.0-next.2").
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/core" (requires ">=8.0.0-rc.5", would install "8.2.0-next.2").
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/common" (requires ">=8.0.0-rc.5", would install "8.2.0-next.2").
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=8.0.0-rc.5", would install "8.2.0-next.2").
```

Regression ?
