### ISSUE TITLE
improve support for readonly controls OR improve how to subscribe to form changes with disabled controls

### ISSUE THREAD

**Issue by sarora2073** [angular/components#15399]
#### Please describe the feature you would like to request.
Suggest there be a clean way to either a) get data from disabled controls or alternately b) improve support for readonly controls. Solution is requested in terms of best practices and/or feature enhancements.

#### What is the use-case or motivation for this proposal?
When using a custom component with a form, the form changes need to be watched and emitted to the parent. If the form has values that ought to be readonly, til now I've used the disabled flag *as a workaround* because a) readonly fields have poor visual appearance -- they are not greyed out b) formbuilder supports initializing as disabled, but not initializing as readonly (as shown here https://angular.io/api/forms/FormBuilder#control).

However, when using the workaround, it becomes difficult to watch and emit changes "cleanly" for disabled fields e.g. subscribing to form.valueChanges doesn't get disabled fields, necessitating a duplicative call to getRawValue() after subscribing to changes, to get all the form field data.

#### Is there anything else we should know?
Potential solutions:
a) advise if using readonly attribute is the best practice, rather than using 'disabled' to prevent data entry. If so, hoping there can be some improvements on styling of readonly controls (e.g. they should be greyed out), and also formbuilder should be able to initialize them as readonly. 

b) if angular doesn't intend to support readonly atribute, and instead rely on 'disabled' attribute, then ideally there would be something similar to form.valueChanges that actually gets all form values including disabled controls. 

If (b) is the solution path, then it's low priority admittedly, since it just avoids a little code duplication. I think the core question though is whether there ought to be better support for readonly controls, and if the angular framework intends to maintain a distinction between 'disabled' vs. 'readonly'. 

For my purposes, I mainly disable controls in order to achieve the readonly effect, and then I make a point to getRawValue data so i get all the data. From my research on stackoverflow etc. it appears others do similar workarounds.

**Comment by djleonskennedy** [comment]
@sarora2073  Api clear and working fine, we're using: 
```
form.valueChanges
  .pipe(mapTo(form.getRawValue()))
  subscribe(console.log) // raw form
```

Don't understand why is it problem ?

**Comment by sarora2073** [comment]
Right..as i said, if the framework doesn't intend to support readonly attribute better, then what you said works, albeit duplicative (you're getting the values, then retrieving them again). Not a biggie.

I do think supporting readonly is important for various use cases though. I remembered that another reason I use 'disabled' instead of readonly in forms is because mat-select doesn't support the readonly property, you have to use 'disabled'..and from reading extensively for solutions it appears i'm not the only one using disabled attribute as an all purpose workaround for lack of good 'readonly' support in the framework.

That said, it might be appropriate to close out this report as there are related reports:
https://github.com/angular/angular/issues/11447 (this one speaks to the same need, but lacks traction)
https://github.com/angular/material2/issues/3395 (mat-select issue)

**Comment by andrewseguin** [comment]
This seems to be a feature request targeting forms rather than Material. Feel free to move your request to https://github.com/angular/angular
