### ISSUE TITLE
Mat Stepper error state

### ISSUE THREAD

**Issue by AnandMani1** [angular/components#15396]
#### Bug, feature request, or proposal:
icon should hide

#### What is the expected behavior?
in error state of horizontal stepper the warning sign should not come. just step and in red color is enough.  
#### What is the current behavior?
its coming with warning icon. with error message
<img width="707" alt="screenshot 2019-03-06 at 3 59 02 pm" src="https://user-images.githubusercontent.com/29225413/53874621-ccc76580-4028-11e9-988c-46833a5e9cf4.png">
<img width="707" alt="screenshot 2019-03-06 at 3 59 02 pm" src="https://user-images.githubusercontent.com/29225413/53874637-d3ee7380-4028-11e9-8ed2-237d2d64dc03.png">
<img width="707" alt="screenshot 2019-03-06 at 3 59 02 pm" src="https://user-images.githubusercontent.com/29225413/53874655-dcdf4500-4028-11e9-98cf-6b0e0d882f9d.png">

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by josephperrott** [comment]
Closing as this is in intentional as it is defined directly by the spec to include this iconography.
