### ISSUE TITLE
Setting the locale does not change the displayed date.

### ISSUE THREAD

**Issue by carlo-nomes** [angular/components#15419]
#### What is the expected behavior?
That the displayed date changes when the locale is updated.

#### What is the current behavior?
Changing the locale does not affect the displayed value of the DatePicker component.

#### What are the steps to reproduce?
https://stackblitz.com/angular/bayaoxeekbm?file=app%2Fdatepicker-locale-example.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions

**Comment by michael-letcher** [comment]
I have the same issue, seems the date picker is stuck on UTC

**Comment by crisbeto** [comment]
It seems to work for me when I move the example into our local dev app. The issue might be due to the Moment locale data not being included for the locale you're switching to.

**Comment by michael-letcher** [comment]
@crisbeto I'm not using Moment locales in our app and we're setting LOCALE_ID in the Webapp, which it should be picking up.

**Comment by christophercr** [comment]
Even the [Stackblitz](https://stackblitz.com/angular/akodblgjone?file=app%2Fdatepicker-locale-example.ts) opened via the [Angular Material website about internationalization in the Date Picker](https://material.angular.io/components/datepicker/overview#internationalization) is not working

**Comment by christophercr** [comment]
Interestingly enough, the issue happens only when the logic is implemented in the AppModule. When this this logic is implemented in a different module (i.e. SharedModule or even in a service) it does work 😕

**Comment by michael-letcher** [comment]
Any news on when this will be fixed. It's very annoying!

**Comment by michael-letcher** [comment]
@christophercr What do you mean bu the logic? Do you mean setting of the LOCAL_ID in a different module other than app?

**Comment by mmalerba** [comment]
This looks like a dup of https://github.com/angular/components/issues/9780 which seems to only affect stackblitz examples
