### ISSUE TITLE
Angular Material official site is NOT RESPONSIVE on small devices.

### ISSUE THREAD

**Issue by tuanbs** [angular/components#15435]
#### What is the expected behavior?
Responsive on small devices.

#### What is the current behavior?
Not responsive on small devices.

#### What are the steps to reproduce?
I use Chrome Dev Tool to check if the site responsive on small devices, but it's not.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular, Material, TypeScript: latest version.
- OS: MacOs.
- Browser: Chrome.

#### Is there anything else we should know?
<img width="338" alt="AngularMaterial_Not_Reponsive_2" src="https://user-images.githubusercontent.com/4801395/54093585-85a4f000-43ed-11e9-8afe-3edc8cb92d19.png">
<img width="340" alt="AngularMaterial_Not_Reponsive" src="https://user-images.githubusercontent.com/4801395/54093586-863d8680-43ed-11e9-80e0-33df4d98f45e.png">

**Comment by davidmcdougs** [comment]
Looks like some pages, namely component documentation, stop responding at about 450 px when using emulation mode in development tools. When I pulled up the same pages on my OG pixel, Which is about 400px, The issue did not occur. Can anyone confirm that this issue occurs on mobile devices, and not just in emulation mode?

**Comment by jelbourn** [comment]
I tried testing this and everything seems to work as expected on small screens. I'm guessing that the issue popped up from _changing_ mobile screen sizes while the app was loaded (which could break the layout, since real devices never change screen size). Feel free to open a new issue if you have further details.
