### ISSUE TITLE
mat-drawer-backdrop not covering the whole screen? use position:fixed instead?

### ISSUE THREAD

**Issue by tobias74** [angular/components#15448]
#### What is the expected behavior?
Backdrop should cover the complete screen when opening menu

#### What is the current behavior?
Backdrop only covers part of the screen, depending on parents height being 100% or less

#### Is there anything else we should know?
in the file _material2/src/lib/sidenav/drawer.scss_ there is a css-class called "mat-drawer-backdrop"
which  
`@includes mat-fill();` 
and therefore has a 
`position:absolute;`
along with
```
top:0;
left:0;
bottom:0;
right:0;
```
For me setting 
`position:fixed`
resolved the issue and the backdrop now completely covers the whole screen.

**Question:** Is this a solution or did I break something else by setting the backdrop to position:fixed?

**Comment by danieldanielecki** [comment]
+1, had the same problem. Thank you for the solution, I decided not to dig into the library code, as it'll break on update, rather than overwritten it in my global **styles.scss** like so:

```
.mat-drawer-backdrop {
  position: fixed !important;
}
```

**Comment by josephperrott** [comment]
Closing as this is done intentionally as the drawer backdrop should cover the entire area the drawer is contained in which is not always the entire screen.  When placed at the top of the DOM tree this results in being the entire screen though the component needs to cover both cases.

For the case of using the drawer for the whole screen, `position: fixed` should work as you expect.
