### ISSUE TITLE
Drag And Drop Problem after adding ScrollingModule

### ISSUE THREAD

**Issue by RmilaWeb** [angular/components#15457]
#### What is the expected behavior?
drag and drop must be still working after adding the ScrollDispatchModule

#### What is the current behavior?
Not working

#### What are the steps to reproduce?
this is my example code 
StackBlitz starter: https://stackblitz.com/edit/angular-material2-issue-djuhga<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3

**Comment by RmilaWeb** [comment]
Anyone has idea why not worked ?

the problem caused when i change the *ngFor to  *cdkVirtualFor

**Comment by crisbeto** [comment]
Closing since this falls under https://github.com/angular/components/issues/10122.
