### ISSUE TITLE
[cdk-drag-drop] Support snap effect.

### ISSUE THREAD

**Issue by Flashunt** [angular/components#15471]
#### Please describe the feature you would like to request.
https://codepen.io/dlouise/pen/NPZMjo , http://jqueryui.com/draggable/#snap-to in this example, the draggable element has snapping effect when dragged. Please support this effect, with some @input.

#### What is the use-case or motivation for this proposal?
I has more standalone draggable element, and need this snapping effect, that the user will can drop the elements exactly next to each other. And without this effect is so hard. But with this effect he can drag the elements with 4 or 8 or (n pixels) distance only.

#### Is there anything else we should know?

I made a little research, and i think this isn't a hard thing:
With an @input value can overwrite the function _**getTransform**_ like this:

```
private _initialSnapEffect?: number;

function getTransform(x: number, y: number): string {
  // Round the transforms since some browsers will
  // blur the elements for sub-pixel transforms.
  // Need this Round before calculate the snap effect.
  x = Math.round(x);
  y = Math.round(y);
  // If have initialSnapEffect, then the translate effect only will change if the input x and y can 
  // divided with this._initialSnapEffect number and no remainder.
  if (this._initialSnapEffect) {
     if (x % this._initialSnapEffect !== 0) {
        x = (x - (x % this._initialSnapEffect));
     }
     if (y % this._initialSnapEffect !== 0) {
        y = (y - (y % this._initialSnapEffect));
     }
  }
  return `translate3d(${x}px, ${y}px, 0)`;
}

```

**Comment by Flashunt** [comment]
Hi!
Some news?

**Comment by kylecannon** [comment]
@Flashunt - This was added in #15137.

**Comment by crisbeto** [comment]
Closing since this should've been covered by #15137.
