### ISSUE TITLE
Add "Unknown" State to Slider + Always Show Tick Marks + Permanent Labels

### ISSUE THREAD

**Issue by hisham** [angular/components#15487]
#### Please describe the feature you would like to request.
- An "unknown" state so that we know if user picked an option on slider (no value defaults)
- Permanently show tick marks rather on just hover so that user knows the slider is discrete
- Labels at bottom and top of slider under/above each tick mark

I have gone ahead and implemented this myself using a combination of custom directives and components around MatSlider - screenshot: 

<img width="489" src="https://user-images.githubusercontent.com/81853/54393971-3bcc3c00-4671-11e9-8de4-14e790e02c09.png">

#### What is the use-case or motivation for this proposal?

Need to ask users questions where options are on a range, and this being in a form, need to have validation that user in fact entered an answer.

**Comment by andrewseguin** [comment]
Thanks for the feature request but unfortunately this would not fit the Material spec, since the slider should represent a range of selectable values and does not provide an affordance for an unknown state.
