### ISSUE TITLE
mat-form-field required asterisk has preceding &nbsp; that fails to collapse with prior whitespace

### ISSUE THREAD

**Issue by stevenyxu** [angular/components#15489]
#### What is the expected behavior?
When a `<mat-label>` has trailing whitespace (e.g., due to a formatter putting `</mat-label>` on a new line and the template compiler not collapsing whitespace) and the field is required, there should be one space between the label and the asterisk.

![84zLDOjNjAY](https://user-images.githubusercontent.com/304874/54396314-c90e9100-466f-11e9-8ee7-c9017468e139.png)

#### What is the current behavior?
There are two spaces.

![stackblitz
](https://user-images.githubusercontent.com/304874/54396289-b431fd80-466f-11e9-9727-917bc9f6a3b3.png)

https://stackblitz.com/edit/angular-h3fng3?file=app/form-field-label-example.html

`mat-form-field` adds `&nbsp;*` to the label when the field is required. 

https://github.com/angular/material2/blob/master/src/lib/form-field/form-field.html#L55

The surrounding `.mat-form-field-label` already has `white-space: nowrap` so `&nbsp;` doesn't serve any additional nowrapping function I know of.

https://github.com/angular/material2/blob/master/src/lib/form-field/form-field.scss#L98

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-h3fng3?file=app/form-field-label-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current, since at least d6fec3573cb. All browsers in theory, though I haven't tested.

#### Is there anything else we should know?
I'll send a PR to see how it integrates. It'll likely trivially break many screendiff tests.

**Comment by josephperrott** [comment]
Closed by #15490
