### ISSUE TITLE
Disabled radio button gets focus

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/components#15493]
#### What is the expected behavior?

Radio button should not receive focus when it is disabled.

#### What is the current behavior?

When radio button is disabled and you click on it, it receives focus.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-rrgrk2?file=app

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material 7.3.4, tested on Chrome only.

#### Is there anything else we should know?

Work without any problemd in the previous versions. Here is the same example on 6.4.7 Material: https://stackblitz.com/edit/angular-vrzwqu?file=app

**Comment by crisbeto** [comment]
Closing the issue, because it shouldn't be a problem anymore. Some time ago we removed the `tabindex` from the root radio button node.
