### ISSUE TITLE
Optional Scrollbar in Sidenav

### ISSUE THREAD

**Issue by tobias74** [angular/components#15528]
#### Please describe the feature you would like to request.
**Current behaviour:** In case there are a lot of items in the mat-sidenav and just little content in mat-sidenav-content a scroll-bar occurs. This scrollbar enables the user to scroll through the items in the left-side menu. 
**Desired behaviour:** I would like to have the option to let the mat-sidenav extend the page to the bottom without introducing a scrollbar. 

#### What is the use-case or motivation for this proposal?
In my use-case it is just not very elegant having a scrollbar in the middle of the screen. The navigation and the content should just scroll together.

#### Is there anything else we should know?
mat-sidenav is positioned absolutely with top and bottom set to zero. The content on the right side of the page (mat-sidenav-content) is positioned relatively with a dynamically calculated inline-style of margin-left: xxx px; (xxx being the width of mat-sidenav). Question: Couldn't this be done with two flex-boxes without any javascript calculation?

**Comment by andrewseguin** [comment]
It sounds like you may benefit more from just using a custom layout with flexbox rather than using the sidenav. The sidenav template is written such that it can handle multiple modes like `over` and `side` where you would want independent scrollbars.

If you go with a custom layout approach, are you concerned about missing any particular features of the sidenav?

**Comment by tobias74** [comment]
@andrewseguin Thanks for your reply! In the end I actually did use a custom layout with flexbox. I am not missing any particular feature of the sidenav, I just miss the sidenav in itself! With sidenav everything fell into place and I did not have to worry about any layout :-)
