### ISSUE TITLE
mat-bottom-sheet scroll strategy

### ISSUE THREAD

**Issue by danischlingi** [angular/components#15533]
#### Please describe the feature you would like to request.
Configure the scroll strategy to like its implemented for mat-dialog.

#### What is the use-case or motivation for this proposal?
The current scroll strategy is buggy with my background-image.

**Comment by kenyerman** [comment]
in styles.scss this worked for me (for NoopScrollStrategy)

```
.cdk-global-scrollblock {
    position: static;
    overflow-y: hidden;
}
```
