### ISSUE TITLE
mat-button cant be clicked on mat-cell

### ISSUE THREAD

**Issue by rhyre** [angular/components#15532]
#### What is the expected behavior?
Button can be clicked in mat-cell

#### What is the current behavior?
Button cannot be clicked obviously 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome, FF
Latest Angular/Material 7.3.5

#### Is there anything else we should know?
It was possible before Angular6 in other project. Right now when 
```html
  <ng-container matColumnDef="edit">
    <th mat-header-cell *matHeaderCellDef> Edit </th>
    <td mat-cell *matCellDef="let element">
      <div><button mat-icon-button (click)="onClick()"><mat-icon>clear</mat-icon></button></div>
    </td>
  </ng-container>
```
Button does not react at all. 
without mat-*-button everything is working fine

Edit: I've figured this happens only when I pass data through function/ getter

**Comment by jelbourn** [comment]
@rhyre can you share a reproduction?

**Comment by rhyre** [comment]
wow it was so long ago, I forgot what is was about. Probably got a workaround. 
Can be closed.
