### ISSUE TITLE
SideNav has strange style properties

### ISSUE THREAD

**Issue by mucbits** [angular/components#15546]
#### What is the expected behavior?
Not to have any invalid style properties

#### What is the current behavior?
SideNav has some strange style properties:
![image](https://user-images.githubusercontent.com/38226656/54679254-22ab0b80-4b07-11e9-9655-8cc9a66c61cc.png)

#### What are the steps to reproduce?
[Stackblitz from the examples](https://stackblitz.com/angular/vrnoxkjxomm)
-> Inspect the mat-sidenav

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: 7.3.5
Chrome

**Comment by crisbeto** [comment]
I believe this was due to an issue in `@angular/animations` which should've been resolved by now.
