### ISSUE TITLE
Adjust the width of a mat stepper at every step

### ISSUE THREAD

**Issue by prabhat112** [angular/components#15559]
#### Please describe the feature you would like to request.
Adjust the width of the  horizaontal mat stepper at every step

#### What is the use-case or motivation for this proposal?
At every step of a horizontal mat stepper, the components change. So the mat stepper should  adjust not only for height but also the width. 

#### Is there anything else we should know?
Currently I am pushing an event on every step label click to the parent and controlling the width of the div or the mat-dialog ( where the mat-stepper is placed).
Can we make this process any simpler?

**Comment by andrewseguin** [comment]
Can you provide a use case or reproduction showing the width change you wish to see? It's not as common to need dynamic widths so an example would help us understand the use case.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
