### ISSUE TITLE
IE11 form field input placeholders

### ISSUE THREAD

**Issue by OvidijusStukas** [angular/components#15560]
#### What is the expected behavior?
Input placeholder to be visible in IE11

#### What is the current behavior?
Input placeholder is never visible when input field is active

#### What are the steps to reproduce?
Open current material website with IE11 and focus any of example form fields
https://material.angular.io/components/form-field/overview#form-field-appearance-variants

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
OS: Windows 10 x64
Material: 7.3.5
Browser: IE11

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
