### ISSUE TITLE
Impossible to use in Web Components

### ISSUE THREAD

**Issue by vadjs** [angular/components#15563]
#### What is the expected behavior?
Overlay containers, styles, etc must be generated in application root: body or shadowRoot.

#### What is the current behavior?
Overlay containers, styles, etc currently generating in `body` element.
It's not normal behavior when you using angular application as Web Component.

#### What are the steps to reproduce?
- Add angular elements to the project
- Compile to the custom element with Material
- All overlay containers and styles will be generated in document body.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by jelbourn** [comment]
We don't have any current plans to change these behaviors, but we will revisit in 2020 when we plan to stop supporting IE11.
