### ISSUE TITLE
datepicker-locale-example doesn't work on StackBlitz

### ISSUE THREAD

**Issue by SimoneVizzuso** [angular/components#15564]
#### What is the expected behavior?
Datepicker with different locale.

#### What is the current behavior?
The example works well, but the StackBlitz model is broken. It doesn't show the japanese datepicker and if you click on "Dynamically switch to French" button, it doesn't work.

#### What are the steps to reproduce?
Click on datepicker (it's not in jap)
Click on button

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?

**Comment by jelbourn** [comment]
Confirmed that this works fine on the docs site and doesn't work on StackBlitz

**Comment by mmalerba** [comment]
Dup of #21724 should be fixed by #22784
