### ISSUE TITLE
Provide custom overlay container

### ISSUE THREAD

**Issue by vlio20** [angular/components#15571]
#### Please describe the feature you would like to request.
Add an option to provide a container to the overlay host

#### What is the use-case or motivation for this proposal?
There are scenarios when you don't want to attach the host container to the document body, by providing an option to supply a custom container the overlay service will attache the overlay element to the custom container.

### Suggestion:
Add optional container property to OverlayConfig:
```
{
  ....
    container?: HTMLElement;
  ....
}
```

if container is present no need to bring the host from the `overlayContainer`:
```
  private _createHostElement(containerElement?: HTMLElement): HTMLElement {
    const container = containerElement ? containerElement :
      this._overlayContainer.getContainerElement();
    const host = this._document.createElement('div');
    container.appendChild(host);
    return host;
  }
```

Already suggested in #4612 

**I will be submitting a PR**

**Comment by andrewseguin** [comment]
Thanks for the request and starting work on a PR - it'll be easier if we keep track of this with the original issue and have the discussion there
