### ISSUE TITLE
matTooltip is not presented inside a button in IE11

### ISSUE THREAD

**Issue by VladislavLobakh** [angular/components#15575]
#### What is the expected behavior?
The tooltip is presented, when the mouse has hovered on the element

#### What is the current behavior?
Tooltip is absent

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-hnwdue?file=app/app.component.html
https://angular-material2-issue-hnwdue.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It's reproducing in IE11 (Windows 8.1, Windows 10)

**Comment by romain-im** [comment]
any chance that this bug will be fixed?

**Comment by mkonars** [comment]
I think this is a bug with hover of span element placed inside button in IE11. It is also visible if instead of the _matTooltip_, you use the _title_ attribute. It also won't show up.

It will work if you place _matTooltip_ directly on the button, not on the span element.

**Comment by romain-im** [comment]
yes, _matTooltip directly on the button_ do the trick
thanks !

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
