### ISSUE TITLE
Autocomplete with header doesn't scroll to option properly

### ISSUE THREAD

**Issue by BobobUnicorn** [angular/components#15629]
#### Bug, feature request, or proposal:
If there is additional content in the autocomplete panel, scrolling to an option by navigating with arrow keys won't scroll to the correct option.

#### What is the expected behavior?
(See provided stackblitz)
Option 5 should be visible when it is selected by arrow key navigation.

#### What is the current behavior?
Option 5 is scrolled off the panel element.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-absrke

1. Focus input element
2. Hit down arrow until Option 5 is selected.
3. Note that Option 5 is still invisibile.

#### What is the use-case or motivation for changing an existing behavior?
Allows customizability of the autocomplete panel to add additional information.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Most recent.

**Comment by jelbourn** [comment]
This is currently working as expected. The autocomplete doesn't actually support arbitrary content, so it doesn't know where to scroll. While we don't currently have plans to add this, feel free to open a feature-request issue and we might revisit it down the line.
