### ISSUE TITLE
Table examples contain "static: true" for queries

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#15632]
The table examples on our docs site is showing `{static: true"}` for the view queries. Somehow the docs site went out with the latest examples rather than off the patch branch

**Comment by crisbeto** [comment]
Related issue https://github.com/angular/material2/issues/15621.

**Comment by mugenulnar** [comment]
Instead of do:
@ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;
@ViewChild(MatSort, { static: true }) sort: MatSort;
Try:
@ViewChild(MatSort) sort: MatSort;
@ViewChild(MatPaginator) paginator: MatPaginator;    

It works for me

**Comment by jelbourn** [comment]
This should be resolved now.

**Comment by jaideepghosh** [comment]
PR [30948](https://github.com/angular/angular/pull/30948) should be the solution for your problem.

**Comment by Atticus29** [comment]
@mugenulnar that fix works for me, but there's compiler error with version 8 now, so you HAVE to have that second argument in there... :-/
