### ISSUE TITLE
Control Autocomplete options position

### ISSUE THREAD

**Issue by jschmuecking** [angular/components#15640]
#### Please describe the feature you would like to request.
I'd like to be able to control the position of the autocomplete options. For example via an additional input to autocomplete with options:

- auto: Current behavior
- bottom: force to always show below the input field
- top: force to always show above the input field

Or like with scroll strategy make it possible to inject a custom positionStrategy.

#### What is the use-case or motivation for this proposal?
Right now the options decide whether to position above the trigger element or below the element dependent on the space in the viewport. Sometimes I'd like to force the autocomplete to display the options always below, e.g. when some importent UI-elements are above the trigger element that would be hidden by displaying the auto complete options above and leaving these elements visible is more importent thant forcing the user to scroll such that the auto complete options are fully in the viewport again.

#### Is there anything else we should know?
Related requests are: https://github.com/angular/material2/issues/5205, https://github.com/angular/material2/issues/8540 and https://github.com/angular/material2/issues/11492

**Comment by ymongo** [comment]
Hello all,

@crisbeto  I've seen your commit, is there a way to implement it as an override on angular mat 7 autocomplete component? I can't move to version 8 right now... I'm trying to force autocomplete to open always down witout success so far....
