### ISSUE TITLE
mat-select's selection not updated when a selected option is removed

### ISSUE THREAD

**Issue by iarspider** [angular/components#15676]
#### What is the expected behavior?
Removing an item from list bound to `value` of `mat-select` should update the selection

#### What is the current behavior?
The selection is not updated, and the array is overwritten when updating the `mat-select`.

#### What are the steps to reproduce?
https://angular-d12gnb.stackblitz.io

Select any topping(s) and use `mat-chips` to remove them.

**Comment by iarspider** [comment]
A simpler example: https://stackblitz.com/edit/angular-material2-issue-6svxse

**Comment by iarspider** [comment]
I can change the selection using reactive forms: https://stackblitz.com/edit/angular-material2-issue-fqee8h?file=app%2Fapp.component.ts

**Comment by iarspider** [comment]
Probably the same bug: https://stackblitz.com/edit/angular-material2-issue-br132y?file=app%2Fapp.component.ts
Changing selected toppings using mat-chips doesn't update the div

**Comment by rafaelss95** [comment]
There's nothing wrong with `mat-select`. It's working how it's supposed to work.

> https://angular-d12gnb.stackblitz.io

**R**: You're trying to mutate the array directly, using `splice` method. Instead, you have to assign the array to a new value to make it work, as you "_partially_" did in 3rd. and 4th. examples. Also don't use `formControl(Name)`/`ngModel` together with `value`. Choose one.

**Working demo**: https://stackblitz.com/edit/angular-xhakq2

<hr>

> A simpler example: https://stackblitz.com/edit/angular-material2-issue-6svxse

**R**: The same thing: you're using `push` and `splice` methods.

**Working demo**: https://stackblitz.com/edit/angular-tsmwmg

<hr>

@jelbourn I guess this issue could be closed.

**Comment by iarspider** [comment]
I see. Thanks a lot for the explanation.
