### ISSUE TITLE
Not animating out

### ISSUE THREAD

**Issue by iamstiil** [angular/components#15681]
#### What is the expected behavior?
The undeline should animate in and out.

#### What is the current behavior?
The underline is not animating out when the mouse is not hovering anymore.

#### Is there anything else we should know?
The transition should be moved up the hierarchy.
https://github.com/angular/material2/blob/bcf4c9f26b60ccd5aa5de089bed63049721bd38b/src/lib/form-field/form-field-standard.scss#L58

**Comment by jelbourn** [comment]
It's not clear what you're referring to. mat-form-field's underline doesn't have a hover treatment

**Comment by mmalerba** [comment]
The underline version of the form-field is no longer in the spec, closing
