### ISSUE TITLE
mat-selection-list: selectAll and deselectAll methods should trigger selectionChange event

### ISSUE THREAD

**Issue by danww** [angular/components#15696]
`selectAll()` and `deselectAll()` methods on `MatSelectionList` should automatically trigger the `selectionChange` event.

#### What is the use-case or motivation for this proposal?
Select some documents from a list.

The `MatListOption`s have `[value]` populated with an object containing a number of properties of the document (name, file size, last edited date, expiry date, etc.).
You want to communicate a warning to the user that specifies the number of expired documents in their current selection.
It's easy enough to calculate the number of expired documents in the current selection when the `selectionChange` event is fired, but if the user decides to `selectAll`, this event is not triggered, so additional workarounds need to be made to cover this case.

**Comment by crisbeto** [comment]
I believe the intention with `selectionChange` is that it emits only if the option changed as a result of a user interaction and `selectAll`/`deselectAll` are programmatic changes.

**Comment by danww** [comment]
@crisbeto: Thanks, I see your point.
If this is the case, then I'd want to update the documentation to make this explicitly clear.

**Comment by crisbeto** [comment]
Sure, feel free to send in a PR to update the docs.

**Comment by despian** [comment]
What if you have a user interaction wired up to `selectAll`/`deselectAll`?

I think it would be nice to have the option to trigger this event without having to write extra code.

How about an optional extra parameter to the `selectAll` and `deselectAll` methods which would fire the event?

E.g.

```ts
selectAll(fireSelectionChange: boolean = false): void {
  ...
}
```

**Comment by AndreasHald** [comment]
Was puzzled by this aswell, we expose `select all` / `deselect all` buttons to the user
![Screenshot 2019-11-28 at 11 43 44](https://user-images.githubusercontent.com/8914722/69799871-65fc6480-11d4-11ea-905b-48b4e58052ab.png)

would be nice with an option to fire the change event from these.

**Comment by jelbourn** [comment]
Seeing this now- I believe we should emit the event when the change comes from the user pressing Ctrl + A to trigger the select-all / deselect-all.
