### ISSUE TITLE
mat-tree flat nodes are not visible when we create deeper child structure inside a container with fixed height & width.

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#15698]
#### What is the expected behavior?
mat-tree nodes are should visible when we create deeper child structure inside a container with fixed height & width.

#### What is the current behavior?
mat-tree nodes are notvisible when we create deeper child structure inside a container with fixed height & width.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-yvnr9g

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular@7.2.3, @material@7.3.0, Windows-7, typescript@3.1.3, Chrome Version 73.0.3683.86
![mat-flat-tree -ssue](https://user-images.githubusercontent.com/31273891/55477926-f7acd580-5637-11e9-80ed-f4af665b2258.png)

**Comment by josephperrott** [comment]
Closing as this is working as expected as the container needs to have enough space to contain the tree's width.  The tree expands its width at a constant expected rate.
