### ISSUE TITLE
Component CSS loads before angular material CSS

### ISSUE THREAD

**Issue by qmarquez** [angular/components#15702]
#### What is the expected behavior?
the CSS rules defined on component CSS have to have more priority than material rules

#### What is the current behavior?
Material CSS rules override component CSS rules

#### What are the steps to reproduce?
Using material, icons for example, declared CSS rule don't override the material CSS

Result
![image](https://user-images.githubusercontent.com/18141238/55448233-5f621280-559d-11e9-86af-c9f7acdbfb81.png)

Component CSS
![image](https://user-images.githubusercontent.com/18141238/55448243-65f08a00-559d-11e9-8894-6fa804d8bb28.png)

To fix it i need to declare the CSS rules as `!important`
![image](https://user-images.githubusercontent.com/18141238/55448276-8fa9b100-559d-11e9-8818-8e5f671a4c64.png)
![image](https://user-images.githubusercontent.com/18141238/55448289-9d5f3680-559d-11e9-8ec9-7aab8bbe6d9a.png)

when a CSS rule it's declared on the component CSS it wont must be priority over anothers CSS rules?

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.7
Node: 10.13.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/material                 7.3.6
@angular/pwa                      0.13.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by jelbourn** [comment]
The Angular Material components only style elements that the library owns. Typography styles are only applied to existing elements if you _explicitly_ include the `mat-typography` class. Aside from that it's not clear what you're referring to.

**Comment by qmarquez** [comment]
Okey, i found a clearer situation
matLine on a mat-list-itemF
![image](https://user-images.githubusercontent.com/18141238/55627803-6f3c4b00-5785-11e9-8159-d5faef73c682.png)

 i want to put gasto.gasto and gasto.valor on a same line, it supose with this class can be done
![image](https://user-images.githubusercontent.com/18141238/55627887-9eeb5300-5785-11e9-936e-45162f1c980c.png)

but the mat-line class loads before my css component class
![image](https://user-images.githubusercontent.com/18141238/55627979-e540b200-5785-11e9-9085-4c9ae4aa99c6.png)
overwriting my .gastoDetalle class

fixing it **just with CSS** the only way its ´!important´ing my CSS class
![image](https://user-images.githubusercontent.com/18141238/55628151-4ec0c080-5786-11e9-86e3-b08fcf9fc149.png)

**OR adding more HTML (the thing i want to avoid)**
![image](https://user-images.githubusercontent.com/18141238/55628281-b1b25780-5786-11e9-8476-90e936ec11ad.png)
---
![image](https://user-images.githubusercontent.com/18141238/55628312-c1ca3700-5786-11e9-991c-9ef1aff61196.png)

the thing is... my CSS class don't have to be more priority over material classes? in other words, the material classes don't have to load after CSS clases defined on my HTML?

Please, if i doing a really bad thing, maybe i thing that is posible but it don't, tellme, maybe the REAL solution it's doing the things well (Adding more HTML but i'm don't knowing)

i hope to be more clear this time

**Comment by jelbourn** [comment]
Your own component's ViewEncapsulation is your issue. See https://material.angular.io/guide/customizing-component-styles
