### ISSUE TITLE
mat-select in mobile skips focus if user navigates using next in mobile keyboard

### ISSUE THREAD

**Issue by ronjb04** [angular/components#15719]
in mobile, when user navigates using the next button, the mat-select gets skip and not being focus.

Example:
first name [input]
last name [input]
country [mat-select]
age [input]

user is able to focus from first name to last name using next button in mobile screen keyboard. however after clicking next from the last name, it skips country and jump focus to age. this issue happens on both android and iphone

I check on desktop and TAB works and focus the select. this only happens in mobile

you can check here in any of your mobile
https://angular-56dg1z.stackblitz.io

**Comment by crisbeto** [comment]
Unfortunately I don't think there's much we can do about it. As far as I know, iOS will look for the next native input/select element, however `mat-select` is a custom element.

**Comment by jelbourn** [comment]
Closing since AFIAK there's nothing we can do about this WRT custom controls.

**Comment by inthegarage** [comment]
@ronjb04  This is actually possible and you should do something like the following:

First of all, along with your select element, make a hidden input element:

`<input style="width:0;height:0;opacity: 0;position: absolute;" (focus)="fireFocus('my-id')"/>`

This should go directly after the mat-select and NOT inside it. Also do NOT use type="hidden".
Make sure "my-id" in the call is the same as your select id. In your mat-select then add a pseudo wrapper tag:

`<mat-select #measselect
`

Declare a viewchildren for that:
```
  @ViewChildren('measselect')
  components : QueryList<MatSelect>;
```


Then finally act on firefocus:

```
  fireFocus(item) {
    let ele = document.getElementById(item);
    if (ele) {
      ele.focus();
      let arr = this.components.toArray();
      for (let i = 0; i < arr.length; i++) {
        if ((<MatSelect>arr[i]).id === item) {
          (<MatSelect>arr[i]).open();
          break;
        }
      }
    }
  }
```
@jelbourn Perhaps you might consider something similar as a natural solution in A.M.
