### ISSUE TITLE
[MatSort] sort function bug

### ISSUE THREAD

**Issue by vadjs** [angular/components#15714]
#### What is the expected behavior?
Sorting by `sort` function with same value as argument must have same result every time.

#### What is the current behavior?
If you will call `sort function several times with same value you will get different results.

#### What are the steps to reproduce?
Example: `.sort({id: 'name', start: 'asc', disableClear: undefined})` first time you will get `'asc'` sorting, second time will be `'desc'`, third time will be `''`.
Live example: https://stackblitz.com/edit/angular-cfcugl

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
Edit: looks lie it's not a bug, it's expected behavior.
Current `sort` function code contains these conditions:
```
if (this.active != sortable.id) {
  this.active = sortable.id;
  this.direction = sortable.start ? sortable.start : this.start;
} else {
  this.direction = this.getNextSortDirection(sortable);
}
```
The problem of this behavior that here are no way to set sort value to exactly needed value.

**Comment by jelbourn** [comment]
Closing since, since this issue was posted, the native `Array.prototype.sort` function has become a stable sort.
