### ISSUE TITLE
Drag and Drop. multiple dynamic lists

### ISSUE THREAD

**Issue by DannyBoyNg** [angular/components#15717]
#### Bug, feature request, or proposal:
Question or feature request for (Drag and Drop)

#### What is the expected behavior?
When I have multiple lists. Each list contained in its own component. I also can dynamically generate as many lists I want. How can I drag an item from one list and drop it into another list. I found a directive cdkDropListGroup but that only seems to work when all the lists are in the same component.

Is what I am asking even possible? So what I'm asking is can I do inter component drag and drop.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2
Material 7.2
TypeScript 3.3

**Comment by jelbourn** [comment]
You can use string references with `cdkDropListConnectedTo`
