### ISSUE TITLE
CDK textfield example has too much vertical space

### ISSUE THREAD

**Issue by J3remyD** [angular/components#15729]
#### What is the expected behavior?
Focused textfield should display the content input by user properly

#### What is the current behavior?
There's an issue when positioning the input text content

#### What are the steps to reproduce?
Open that page [https://material.angular.io/cdk/text-field/overview](https://material.angular.io/cdk/text-field/overview) gain focus on the first textfield and input text , the rendering is not good

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It's in the current angular demo

**Comment by jelbourn** [comment]
The example has too much vertical space for some reason, so the floating label looks weird:
![image](https://user-images.githubusercontent.com/838736/57559498-f6598180-7336-11e9-82a3-5d910027b986.png)

**Comment by jonathanRinciari** [comment]
So the vertical space is because of  `cdkAutosizeMinRows="2"` which determines the minimum height of the text-area. If you were to set this value to 1 it would allow for a single row and would look like a regular input field that would be able to expand to show the value of `cdkAutosizeMaxRows`

**Comment by jelbourn** [comment]
We can probably set the example to `1` so that it doesn't look weird at first glance

**Comment by outofgamut** [comment]
https://github.com/angular/components/pull/16021
