### ISSUE TITLE
table-expandable-rows-example text is unreadable on hover with a dark theme

### ISSUE THREAD

**Issue by nikolalukovic** [angular/components#15735]
#### What is the expected behavior?
Hover background color on dark themes shouldn't be the same as text color

#### What is the current behavior?
With hover background color and text color cannot be discerned.

#### What are the steps to reproduce?
You can check the table example here https://material.angular.io/components/table/examples

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: >= 6.4.7

**Comment by jelbourn** [comment]
There's not quite enough information here. Is this just in the one table example with a hover treatment, or are there more places?

**Comment by nikolalukovic** [comment]
I only found this problem with table hover

**Comment by wnvko** [comment]
In the sample's CSS [here](https://github.com/angular/components/blob/eef132b02d4c66412670fa2339e70e464ff112ed/src/material-examples/table-expandable-rows/table-expandable-rows-example.css#L10) is specified the hover color. It is too dark for the dark theme. Should we change this to something like #aaa or #bbb?
@jelbourn

**Comment by jelbourn** [comment]
@wnvko I'm fine to changing it to anything that looks decent in both
