### ISSUE TITLE
mat-list with prefix and suffix icons features not available 

### ISSUE THREAD

**Issue by bhumin3i** [angular/components#15730]
i want to make list view like below image but in mat-list there is nothing for display navigation right arrow default property!!!

![Screen Shot 2019-04-05 at 4 40 09 PM](https://user-images.githubusercontent.com/25737987/55623904-ee4f7480-57c1-11e9-9cc7-ec7c873e2e78.png)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
