### ISSUE TITLE
Cannot Print Overlay in IE 11 with BlockScrollStrategy

### ISSUE THREAD

**Issue by tuckergordon** [angular/components#15759]
#### What is the expected behavior?

In modern browsers (e.g. Chrome, Firefox, and Safari), when using an Overlay with `BlockScrollStrategy` and printing the page (via `window.print` or just `ctrl-p`), the overlay will appear in front of the `body` content as expected.

#### What is the current behavior?

In IE 11, the overlay does not appear on the printed page when `BlockScrollStrategy` is used.

#### What are the steps to reproduce?

This stackblitz illustrates the issue: https://stackblitz.com/edit/scroll-strategy-block-eh5hrg

Printing the page in a modern browser works as expected, but in IE the overlay will not appear on the printed page.

**Comment by jjsiman** [comment]
Workaround found for now.

In `@media print`, added the line `.cdk-global-scrollblock { position: relative; }`

`.cdk-global-scrollblock` is normally `position: fixed;` and it shifts the html position behind to mimic the scroll position on overlay generation. Not sure if IE was still trying to capture from (0, 0) or what but this hack works.

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
