### ISSUE TITLE
Grid to resize based on content

### ISSUE THREAD

**Issue by georgeedwards** [angular/components#1576]
#### Bug, feature request, or proposal:

Feature Request
#### What is the expected behavior?

An "auto" option for the grid row height option, so the grid's row will automatically size to accomodate the tallest element in that row. 
#### What is the current behavior?

You must specify an exact height, or fill, so if you are embedding a component in a grid cell (where you may not know how large it will be) and the page may extend beyond one screen (i.e. scroll), then it is not currently possible to ensure the grid's contents get displayed properly.
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by zealitude** [comment]
I am looking forward to this feature too.
In addition, is it possible to have a tile level height setting rather than grid-list level only?

**Comment by jelbourn** [comment]
Closing this because we are pretty unlikely to add new features to MatGridList going forward now that CSS Grid provides a significantly more robust tool for creating this style of layout.
