### ISSUE TITLE
Deliberately and manually trigger resize of drawer / sidenav

### ISSUE THREAD

**Issue by andreElrico** [angular/components#15777]
I know there is `autosize`. But autosize is not good enough because it runs on every changeDetection. The docs warn about the use of `autosize`.

> Note that you should use this option at your own risk, because it could cause performance issues.

Here in this [Stackblitz](https://stackblitz.com/edit/angular-detyqg) I use PRIVATE!  `_updateContentMargins()` https://github.com/angular/material2/blob/833d428fa423d40f276cd93ebb1cf83c73b64a88/src/lib/sidenav/drawer.ts#L719 which I found while looking at the source.

However this function is private and as far as I know it should be prevented to use private API's.

#### What is the use-case or motivation for this proposal?
In my usecases I know what will trigger a change in the width of the drawer. (In the example its a button click/ ... might be a loader finishing or what ever ...) 
So I want to trigger resize for those few occasions.

How can I use something public to trigger the resize as needed? Can we make something like `_updateContentMargins()` public?

**Comment by Airblader** [comment]
Using `cdkObserveContent` to determine when to trigger the recalculation seems to be working, and shouldn't have the same downsides as the current `autosize` implementation. Example: https://stackblitz.com/edit/angular-detyqg-gaby4i

Of course the example still relies on the internal API, but instead of exposing this API I wonder if we could just extend the drawer to use `cdkObserveContent` to also trigger the recalculation?

**Comment by Airblader** [comment]
@crisbeto @jelbourn I have to say I'm somewhat disappointed that everyone is ignoring my comments both here and in the PR. Not very encouraging for contributors...

**Comment by jelbourn** [comment]
@Airblader generally that's something we don't build into the components themselves, instead surfacing APIs that give people more flexibility

**Comment by Airblader** [comment]
@jelbourn But autosize has been implemented, and even knowingly as a "bad" solution. This would be a chance to turn it into a better solution.

In any case, at least I have gotten a response now. Thank you for your time.
