### ISSUE TITLE
autocomplete placed inside the chip-list  not preventing dummy type text

### ISSUE THREAD

**Issue by bhumin3i** [angular/components#15790]
#### What is the expected behavior?
select only available option 

#### What is the current behavior?
when i type anything and click anywhere in the page it will show me new chip added but it is wrong because chip option only allow available array items also allow me to select option multiple time

#### What are the steps to reproduce?
> http://recordit.co/8vNqjawYKp

GIF
![8vNqjawYKp](https://user-images.githubusercontent.com/25737987/55954402-3e27b300-5c7c-11e9-834d-5a035f13cd9e.gif)

**Comment by boicualexandru** [comment]
I don't think that your expected behaviour should be the default behaviour.

On the Material Angular documentation, the "Chips with input" component doesn't have any unique constraints and I don't think that it should.
The autocomplete feature that is applied to this component, still shouldn't change its behaviour.

**Comment by bhumin3i** [comment]
@boicualexandru  thanks for your idea, can you suggest me best example regarding my question.

**Comment by dzsofa** [comment]
hi!
I had the same issue, the thing I did was that contrary to the example with chips autocomplete on the official documentation (https://material.angular.io/components/chips/examples) I completely got rid off the add function, so that only the MatAutocompleteSelectedEvent adds items to the list.

**Comment by bhumin3i** [comment]
my goal was achieved thanks everyone!!!

![Kapture 2019-06-24 at 14 41 35](https://user-images.githubusercontent.com/25737987/60006685-8efd5400-968e-11e9-9c92-121389c1eb94.gif)

**Comment by bhumin3i** [comment]
![Kapture 2019-06-24 at 14 41 35](https://user-images.githubusercontent.com/25737987/60006774-b6542100-968e-11e9-8e95-981d61f2662c.gif)

**Comment by dzsofa** [comment]
cool! :)
