### ISSUE TITLE
Allow title on mat-badge

### ISSUE THREAD

**Issue by mmmatthew** [angular/components#15801]
#### Please describe the feature you would like to request.
Include an @Input('matTitle') property that provides simple tooltip functionality to mat-badge.

#### What is the use-case or motivation for this proposal?
We use the badge to indicate that there is an issue with the data displayed. We could use the badge title to provide more information about the issue.

#### Is there anything else we should know?
This request is related but not identical to #12969

**Comment by Airblader** [comment]
If you want to display a tooltip, why not use `matTooltip`?

**Comment by mmmatthew** [comment]
- Because the tooltip for the object itself is already used to provide information about the object. A badge tooltip would provide more information about the badge.
- The object tooltip disappears when you mouse-over the badge.

**Comment by Airblader** [comment]
Perhaps an idea would be to allow passing a template for the badge, and then users are free to use title or matTooltip for that template somehow.

**Comment by FIRSTNIGHTINTHEWOODS** [comment]
mb this will help u https://stackblitz.com/edit/cdk-overlays
I mean `cdkConnectedOverlay` can bind to any element some template

**Comment by mmmatthew** [comment]
Thanks, that would be a good workaround if this feature doesn't make sense within Angular Material.

**Comment by crisbeto** [comment]
This might be a bit too specific of a use case to have a dedicated API. What we could do instead is expose the badge element as a property on `MatBadge` and you can set the title yourself. Also it's worth noting that even if there was a title on the badge, right now it won't show up because the badge element has `pointer-events: none`.

**Comment by mmmatthew** [comment]
Thanks @crisbeto for the counter - proposal. Do we collect other use cases before making a new issue for the element property and closing this, or what is the best way to proceed?
