### ISSUE TITLE
How use  matBadge in mat-panel-title

### ISSUE THREAD

**Issue by PiotrFr** [angular/components#15816]
#### What is the expected behavior?
matBadge should be whole visible.

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/13883511/56091711-73b5e180-5eb2-11e9-96a1-68a2a595609d.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-njzcbx?embed=1&file=src/app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.2.12
material 7.3.7

**Comment by Airblader** [comment]
As a workaround you can use

```
::ng-deep .mat-content {
  overflow: visible !important;
}
```

**Comment by PiotrFr** [comment]
😊 Thank you

**Comment by thorek** [comment]
+1

**Comment by Airblader** [comment]
@thorek Please use the issue reactions for that, not comments. There's no need to notify all subscribers via email for that.

**Comment by thorek** [comment]
@Airblader is there some feedback to the original issue?

**Comment by jelbourn** [comment]
Closing this since I don't see us changing this behavior; you should be able to add padding on the content that has a badge
