### ISSUE TITLE
Expansion panel

### ISSUE THREAD

**Issue by krishnasaikumarraju** [angular/components#15821]
#### What is the expected behavior?
https://screenshots.firefox.com/O3sRlUPyEIUxmlf4/app.zeplin.io
I was expecting the above behavior ( i.e once the user clicks on create the post button, The respective button should get disappear and the expansion panel data alone should highlight ) below screenshots will give you the picture of current behavior.
#### What is the current behavior?
https://screenshots.firefox.com/otRRfJduqoK3PTB0/localhost
When the user clicks on the above-mentioned button ( i.e create the post ) the panel expansion takes place.
https://screenshots.firefox.com/fkXIWy9nRHVgVsoG/localhost
The above-mentioned screen gives you the picture of the panel expansion.
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version: 6 plus
Angular Material: 6 plus
OS: Linux ( 16.04 )_
TypeScript: 2.9
browsers: chrome, firefox
#### Is there anything else we should know?
Please team give me some sort of suggestions to overcome expected behavior.

**Comment by andrewseguin** [comment]
Your screenshots are no longer loading, can you update them?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
