### ISSUE TITLE
[MatIcon] can not be embedded in SVGs

### ISSUE THREAD

**Issue by J5** [angular/components#15854]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatIcon or equivalent should be able to be embedded via an ng-container tag so that SVG
icons render only SVG tags.

#### What is the current behavior?

Mat icons are always surrounded by a <mat-icon> tag which prevents svgIcons from rendering
when embedded in an svg.

#### What are the steps to reproduce?

https://material2-issue-15045-ijytdc.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?

We are building a SVG based visualization library in Angular and I would rather not create my
own icon component. SVG icons should be embeddable in an SVG.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All

#### Is there anything else we should know?

Th example has an inherited svg-icon component that I created. Because of some of the
internals of mat-icon I would rather material provide a fix instead of my app having to deal with breaking changes.

**Comment by jelbourn** [comment]
Closing this since the functionality you'd want would come as part of extracting the `MatIcon` SVG-handling code into a `cdk/svg` module, tracked in #5188.
