### ISSUE TITLE
mat progress bar. Add the ability to combine different modes

### ISSUE THREAD

**Issue by andreElrico** [angular/components#15904]
#### Please describe the feature you would like to request.

Add the ability to combine different modes.

#### What is the use-case or motivation for this proposal?

Lets say your progress is jumpy and goes from 0 to 50 to 100. It would be nice to still have some animations going.

[HERE!](https://stackblitz.com/edit/angular-wdejz1?file=app%2Fprogress-bar-indeterminate-example.html) I hacked my solution by layering two progress bars.

So

## 1
```
@Input()
mode: 'determinate' | 'indeterminate' | 'buffer' | 'query'
```

could be extended with new inputs: `'detIndeterminate' | 'detBuffer' | 'detQuery'` or

## 2
a new `@Input() addDetermination` could be introduced to combine determination with animation.

## 3
`mode: 'indeterminate' | 'buffer' | 'query'` and the occurence of `value` could yield to the desired behaviour, but could possibly "break/alter" current UX.

#### Is there anything else we should know?

I would like to know how you like the idea?

**Comment by jelbourn** [comment]
This isn't something we plan on adding to the component directly; the app can always stretch out the values it hands to the progress-bar itself.

**Comment by andreElrico** [comment]
@jelbourn I tried to make something work, but no success yet. Lets say my `mode="indeterminate"` and my `value="50"`. What do I have to stretch out where? Can't make it work to make a solid progressbar to 50%.
