### ISSUE TITLE
angular drag and drop cdk. I want to know, how to get the index value of all items in the drag and drop on event cdkDropListDropped.

### ISSUE THREAD

**Issue by digish777** [angular/components#15900]
angular drag and drop cdk. I want to know, how to get the index value of all items in the drag and drop on event cdkDropListDropped.

Or is there any event, which I can rely on. I want to know the index value of all items in the list once the item in the list of moved to new location.

**Comment by Airblader** [comment]
What for? You get the previous and current index in the drop event. Once you use moveItemInArray you have the final array and as a result you also know all indices.

**Comment by crisbeto** [comment]
@Airblader is correct. Once you know the previous and current index in the drag event, you can move the item into its new position in the array.

**Comment by digish777** [comment]
I get the index of the moved element alone. not all the items in the dropped div. I want all updated indexes of the items in the dropped div.

**Comment by crisbeto** [comment]
Wouldn't the indexes of all items just be between 0 and the length of the items in the list?

**Comment by digish777** [comment]
I want the exact indexes of the all the items in the list after moving. I need the update another list where I maintain the indexes of all items in the list. is there any way to do that?. Once I move an item. I need updated indexes or positional index of all items in the dropped container.

**Comment by Airblader** [comment]
You use `moveItemInArray` (provided by CDK) to update the array of your items (or a copy of it if you prefer). Now you have an array that reflects the exact order of all items, so the indices of items within this array are all updated.

**Comment by mohamedsamy680** [comment]
@Airblader  thank you very much you inspired me with great idea after i was stuck.

**Comment by mohamedsamy680** [comment]
@Airblader  thank you very much you inspired me with great idea after i was stuck.

**Comment by mohamedsamy680** [comment]
@Airblader  thank you very much you inspired me with great idea after i was stuck.
