### ISSUE TITLE
mat-input field lagging in displaying text.

### ISSUE THREAD

**Issue by kishoreRedd** [angular/components#15901]
#### What is the expected behavior?
while enter the text it will visible with in milliseconds.

#### What is the current behavior?
lagging display text it take 2 to 3 seconds to visible in mat-input field

#### What are the steps to reproduce?

steppers  in the particular step put mat-input this problem coming 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular - 5.2.0,
Material - 5.2.4,
typescript - "2.4.2"

**Comment by andrewseguin** [comment]
Please provide steps to reproduce your issue.
