### ISSUE TITLE
Autocomplete selection with mouse focusing body

### ISSUE THREAD

**Issue by fyidev** [angular/components#15914]
#### What is the expected behavior?

When I select an option via mouse click, it should focus the input element. This works correctly when navigating to correct option with arrow keys and pressing enter.

The issue is that if I present the autocomplete within a dropdown or dialog element that closes when a click/focus is detected outside of itself, the drop down/dialog will close everytime a mat autocomplete option is selected via mouse.

#### What is the current behavior?
after a mouse selection behave the same way as a keyboard/enter selection. Dont focus the body just send focus back to input.

#### What are the steps to reproduce?

styling is shit obviously but start typing a city in the drop down, if you key down and press enter you'll notice the drop down doesn't close. but if you use mouse to select it does close.

https://stackblitz.com/edit/create-shvowk?file=app%2Fapp.component.ts
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 7.3.3

**Comment by andrewseguin** [comment]
The issue seems to be that bootstrap sees a click outside of its popup which is a signal to close. I don't believe there is anything we can do to circumvent their logic nor should we. You may want to file an issue with bootstrap to request a feature to prevent closing the popup when the click occurs outside of it.

**Comment by fyidev** [comment]
When using native selects, bootstrap doesn't recognize a click outside. Which lead me to believe it was on the material side.

**Comment by felipeands** [comment]
I fix it using ngZone inside the `place_changed` listener.
Like this
``` 
autoComplete.addListener('place_changed', () => {
  this.ngZone.run(() => {
    // code
  });
});
```
