### ISSUE TITLE
CDK Virtual scroller with multiple columns

### ISSUE THREAD

**Issue by MaximumRGB** [angular/components#15913]
Hello. 
Such a feature as CDK Virtual scrolling with multiple columns seems to be usefull, in my own opinion. 
In one of my projects i need to display the virtual scroller with a custom data source and multiple columns. But it seems, that CDK Virtualscroll doesn't support multi column view.
Thank you in advance.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
