### ISSUE TITLE
In mat-select, make the multiple value separator configurable

### ISSUE THREAD

**Issue by karlgoldstein** [angular/components#15915]
#### Please describe the feature you would like to request.

The mat-select is currently hard-coded to use a comma as the delimiter for displaying multiple values:

https://github.com/angular/components/blob/058ed0f66c80bd21f254d825946cde9bdb6db2e6/src/material/select/select.ts#L687

Please add a configurable property for the delimiter.

#### What is the use-case or motivation for this proposal?

Localization, as well as semantics, i.e. ability to use AND or OR as the separator.

#### Is there anything else we should know?

Nope.

**Comment by Airblader** [comment]
Not sure this is still needed, there is already a way to customize the trigger value: https://material.angular.io/components/select/overview#customizing-the-trigger-label

**Comment by karlgoldstein** [comment]
@Airblader I missed that, it is even better than delimiter configuration.  Agreed that the delimiter is not necessary.  Thanks!
