### ISSUE TITLE
angular universal  not working 

### ISSUE THREAD

**Issue by sreeragnair** [angular/components#15918]
#### What is the expected behavior?

It should serve universal application without getting any error.

#### What is the current behavior?

Node Express server listening on http://localhost:4000
Warning: Flex Layout loaded on the server without FlexLayoutServerModule
/home//app/dist/server.js:344
                        throw error;
                        ^
ReferenceError: requestAnimationFrame is not defined
    at AnimationFrameAction.requestAsyncId (/home/antso-lap3/app/oclient/dist/server.js:30505:40)
    at AnimationFrameAction.AsyncAction.schedule (/home/antso-lap3/app/oclient/dist/server.js:29678:35)
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/antso-lap3/.npm/_logs/2019-04-27T06_08_26_778Z-debug.log

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7

#### Is there anything else we should know?
i have only used Material inside my app,No further Animation installed or used directly

**Comment by crisbeto** [comment]
The issue should be posted in the flex layout repo. https://github.com/angular/flex-layout/issues
