### ISSUE TITLE
MatInput outline issue with hidden input / div

### ISSUE THREAD

**Issue by therawk** [angular/components#15912]
#### What is the expected behavior?
The outline gap should be on the correct side

#### What is the current behavior?
After a flip animation the outline gap is on the wrong side

#### What are the steps to reproduce?
[https://stackblitz.com/edit/angular-6qsn2k](https://stackblitz.com/edit/angular-6qsn2k)
-> Click on "Forgot PW" and then focus the input field

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.14, Material 7.3.7, error occurs in Chrome, Firefox, TypeScript version 3.2.2

**Comment by crisbeto** [comment]
This looks like an issue with a third-party library (`ngx-flip`). We generally don't fix issues like this, because supporting all the libraries that are out there would impractical.
