### ISSUE TITLE
Spinner going back of the mat dialog

### ISSUE THREAD

**Issue by tirupathi471** [angular/components#15911]
#### 
We are using progress spinner for every API call.  And we registered spinner at the app module level. **When we want spinner on dialog the spinner hiding back of the popup**.

To fix this we are adding spinner tag in every dialog component HTML. even z index also not working here.  we have tried mat progress spinner and other spinners as well but no use. 

Can we have a solution for this issue?

**Comment by tirupathi471** [comment]
This is the stack stackblitz example for my problem 
[](https://stackblitz.com/edit/angular-co9fxw)

**Comment by crisbeto** [comment]
I couldn't see an obvious problem in the Stackblitz. Can you elaborate?

**Comment by andrewseguin** [comment]
You are adding the spinner outside of the context of Angular. The app is bootstrapped within `dialog-overview-example`, anything outside of that will not be touched by Angular.
