### ISSUE TITLE
tabindex on Sort header

### ISSUE THREAD

**Issue by ryboucher** [angular/components#15926]
#### Please describe the feature you would like to request.
When specifying a tabindex of -1 on the mat-sort-header th, and focus is on an element right before the mat table,when tab is pressed, the focus should skip the mat-sort-header and focus on the next focusable element. (As per https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)

#### What is the use-case or motivation for this proposal?
I have a search table with clickable elements. I want to be able to type in a search, then tab to a specific element in the table and select. Right now, I have to tab through all of the mat headers before I can get to my results.

#### Is there anything else we should know?
https://stackblitz.com/edit/angular-zqjrcn

I put a tabindex of -1 on the first header, expecting it to be skipped on tab, since the tabindex does not follow to the mat-sort-header-button, it still has focus.

**Comment by andrewseguin** [comment]
If you remove the ability to tab to the sort button, then you are excluding users with screen-readers who rely on the ability to navigate the page with keyboard interaction. It seems that you may be better suited to just remove your sort functionality or put it in another interaction pattern (e.g, a separate sort function that lets you decide what column is sorted).

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
