### ISSUE TITLE
Drag and Drop works intermittently when in ngFor 

### ISSUE THREAD

**Issue by tmburnell** [angular/components#15941]
#### What is the expected behavior?
I have been trying to use the drag and drop feature in conjunction with a ngFor.  It seem very random when the drag and drop works and when it does not.

#### What is the current behavior?
You can watch the placeholder before you drop, and sometimes it does not move ... and the times it does not is when the drop fires on the container it was currently in. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/looped-drag-and-drop?file=src/app/app.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by tmburnell** [comment]
I believe i might have fix my example to work more consistently ... 
The issue seems to be when the selector extends past the edge of the collection zone.  So if you select the portion that was outside the collection zone; it would drag but not effectually drop into the next collection.

So my fix was to widen the collection zone, and add a second element that was smaller.  Therefore you are always selecting the selector width-in the collection zone. 

Therefore I am fine to close the ticket, but leaving it open if someone wants to research why selecting outside the drop-zone causes drag to not work.

**Comment by andrewseguin** [comment]
Sorry but I could not reproduce the issue in the provided reproduction. If you have further problems feel free to reopen this with more information or open another issue

**Comment by tmburnell** [comment]
click the top of the circle and drag it, and most of the time it does not work.  but if you grab the bottom half it almost always works

**Comment by andrewseguin** [comment]
Ah great, thanks - I was able to reproduce the issue. Dragging from the top will show the placeholder but does not drag. Haven't looked into it further but it does look like there's an issue

**Comment by crisbeto** [comment]
This is working as expected. @tmburnell your issue comes from the fact that the drop list is pretty small. The CDK is set up so that it only sorts if your cursor is inside the drop zone or within a certain number of pixels around it (currently it's at 5% of the width and height). Here's a fork of your example that has some red boxes showing where the user will be able to scroll. https://stackblitz.com/edit/looped-drag-and-drop-ydegdf?file=src/app/app.component.html
