### ISSUE TITLE
angular/components should use github labels

### ISSUE THREAD

**Issue by FritzHerbers** [angular/components#15958]
#### Please describe the feature you would like to request.

Add github labels for the components.

#### What is the use-case or motivation for this proposal?

- Find related issues/fixes quicker for a component.

- Speeding up resolution of issues/better issue/PR handling
when making a PR for a component, check if there exists similar issues, and maybe one which can be fixed in the same PR. Close resolved (related) issues, instead that they stay open unnoticed.

#### Is there anything else we should know?

As an example see: https://github.com/ng-bootstrap/ng-bootstrap/labels

**Comment by andrewseguin** [comment]
We've been talking about doing this and agree that this could help, especially for us to get a better sense on the priorities at a per-component level. Thanks for the suggestion, it helps to signal to us that it would help not only us, but also the community.

Closing this out since its not directly an issue/feature request but thanks again for the feedback

**Comment by FritzHerbers** [comment]
@andrewseguin 
Still after 5 months I sent you my proposal no component labels exist.

Exactly a year ago I looked into the stepper component . Till now they it is missing some simple functionality to do a "beforeSelectionChange" (https://github.com/angular/components/issues/9733). The issue itself exists since 1.5 year. During my observations several other fixes for the stepper component were made, but this issue has never been looked at.

With component labels, developers can search much easier. Fixing can be done on a component level and not on single issues.

In the last 2 days, 4 new issues drag-and-drop issues where opened, from which 2 have already reported many months ago.

The number of issues are continuously growing and are getting out of control. A year ago it were some 1200. Pull requests were some 200.

I don't want to bash here, I appreciate all work done. But hope some more control over issues can speed up development.
