### ISSUE TITLE
Height inconsistancy of icon-button and button

### ISSUE THREAD

**Issue by DaSchTour** [angular/components#15953]
#### What is the expected behavior?

icon-button and button to have the same height

#### What is the current behavior?

buttons have a height of 36px
icon-button has a height of 40px

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.8
Node: 8.10.0
OS: darwin x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/.DS_Store         <error>
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.8
@angular/.DS_Store                <error>
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@ngtools/.DS_Store                <error>
@ngtools/webpack                  7.3.7
@schematics/.DS_Store             <error>
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

#### Is there anything else we should know?

I've seen menu button and icon-button along to each other on google drive. This looks quite nice.

<img width="127" alt="iOS Location – Google Drive 2019-05-04 18-59-08" src="https://user-images.githubusercontent.com/1907266/57182406-dfcaaa80-6e9e-11e9-8415-4ce1c83fa7ce.png">

I wanted to build something similar with angular material. But because icon-buttons are somehow bigger the result is very ugly.

<img width="99" alt="footage one 2019-05-04 18-59-22" src="https://user-images.githubusercontent.com/1907266/57182405-dfcaaa80-6e9e-11e9-8554-5d7149a2212c.png">

**Comment by jonathanRinciari** [comment]
I just want to double check that you are talking about a height inconsistency with the mat-button and the icon-button, because in your stackblitz it appears to be a mat-button and mat-slide-toggle. If you could provide clarification on the scope of the issue that would be great!

**Comment by DaSchTour** [comment]
Ignore the stackblitz. It's from the issue template and I haven't seen it while creating the issue.
I'm talking about icon-button and button.

**Comment by andrewseguin** [comment]
Are you referring to the font-size of the icon being larger, or that the ripple extends to be larger than the button next to it? Since the text in both buttons are vertically centered, I'm not sure why putting them side-by-side is ugly.

https://stackblitz.com/edit/angular-fvhjtf?file=app/button-overview-example.html

**Comment by DaSchTour** [comment]
Okay. Looks like it works better with material icons. It's hell to get custom icons positioned inside mat-icon. I'll recheck after I figured out how to get them aligned correctly.

**Comment by jonathanRinciari** [comment]
If you want to add the custom icon you are using I don't mind taking a look as well. I use custom icons and haven't  had too much issue with positioning. Let me know!

**Comment by jelbourn** [comment]
This is working as intended; the spec calls for buttons to be 36px tall and icon buttons to be 44px. Even in our MDC-based components, these will be different sizes.
