### ISSUE TITLE
Possibility to update and validate FormControl on change, if form updateOn: set as 'blur'

### ISSUE THREAD

**Issue by Maks-Yaremenko** [angular/components#15952]
#### Bug, feature request, or proposal:
When I set the form ``` { updateOn: 'blur' } ```, and then change any of the inputs, formControl validate and update value triggered only after blur.

#### What is the use-case or motivation for this proposal?
Sometimes it's necessary to get updated form value and validate it on change, but emit form update only after input blur.
Mat-autocomplete does not work properly with updateOn: 'blur'.

#### What is the expected behavior?
formControl should be validated and updated on every change, the form should emit update on input blur

#### What is the current behavior?
Form emit updates on blur, formControl validated and the value updated only after blur

#### What are the steps to reproduce?
Link to stackblitz: https://stackblitz.com/edit/angular-bnns8s?file=app/form-field-overview-example.ts
Form set to be updated on blur, and both fields are required, but user able to remove text without getting any errors.

Another example! mat-autocomple don't work properly due to formControl not updated:
https://stackblitz.com/edit/angular-bnns8s-es6ttf?file=app/form-field-overview-example.ts

#### Is there anything else we should know?
If I set input updateOn: 'change' but form updateOn: 'blur' form emit updates as default on every input change.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

**Comment by Airblader** [comment]
"Sometimes it's necessary" doesn't much sound like a use-case to me. This sounds like a way to create inconsistent state between a control and the form it belongs to.

**Comment by Maks-Yaremenko** [comment]
I suggest to add submitOn: 'blur' | 'change' | 'submit' to the form config or smth like that.

For me use case of purpose reported is obvious when the user works with the field, validation should be applied immediately, but config setting updateOn: 'blur' should allow emitting form value only after blurring of the field.

**Comment by Airblader** [comment]
> ... but config setting updateOn: 'blur' should allow emitting form value only after blurring of the field.

But *why*? You're only saying that you need it, not what for. The use-case of updateOn blur is that validations can be heavy in complex forms and therefore cause performance issues, for example. So what's the benefit we gain from the feature you suggest? What do you need it for? 

By the way, you opened this feature request in the wrong repository. This affects @amgular/forms, not Material/CDK, so you need to open it in angular/angular.

**Comment by Maks-Yaremenko** [comment]
okay, I'll create an issue for angular forms.

> But why? You're only saying that you need it, not what for. 
I need to get possible to emit form value on input blur, but keep fields updated (value + validation) on change.

PS: I already described the issue: if we use mat-autocomplete for example, it won't trigger autocomplete options, because form control not being updated

**Comment by Airblader** [comment]
> I need to get possible to emit form value on input blur, but keep fields updated (value + validation) on change.

Again, that isn't a use-case or motivation. That's just the description of the *what* you want, not the *why*.

> PS: I already described the issue: if we use mat-autocomplete for example, it won't trigger autocomplete options, because form control not being updated

Yeah, it seems you've added that to the issue after(!) my comments. 

Perhaps you should file an issue here against Material describing *this* problem, rather than insisting on a specific solution in the core framework. Perhaps the team has also other ideas on how to deal with this issue?

**Comment by Maks-Yaremenko** [comment]
> Yeah, it seems you've added that to the issue after(!) my comments.

thx. yes, I added it after we started the discussion.

> At least this is finally the actual use-case I was asking for. :-)

I faced a few issues, after starting using this option and remember some of them.

an additional issue with toggle, when you toggle toggler it stay in focus(not so obvious) and not trigger the value.

**Comment by andrewseguin** [comment]
It seems that this is an issue you have with forms themselves, so we'll close this out. It looks like we can't apply any workarounds for this on our end.
