### ISSUE TITLE
Typo in versions menu

### ISSUE THREAD

**Issue by opirci** [angular/components#15961]
On the top right menu of main url https://material.angular.io/ there is typo. It is written the latest version 7.3.7 but the options in the combo are 5.2.5, 6.4.7 and 7.2.0. If you try to select 7.2.0, 7.3.7 appears as the selection.

**Comment by macjohnny** [comment]
this issue is fixed with https://github.com/angular/material.angular.io/pull/603

**Comment by josephperrott** [comment]
Closing as this is fixed in the latest release of the Angular Material documentation
