### ISSUE TITLE
build-angular: styles for Angular Element are not applied when using extractCss: false

### ISSUE THREAD

**Issue by turbolego** [angular/components#15968]
#### What is the expected behavior?
That the styles.scss file is not ignored when running the custom element (angular elements) by itself.

#### What is the current behavior?
If i use the custom element in an Angular Component, the styling works with extractCss either true or false. If i run the custom element by itself, the styling works only when extractCss is false.

_Under "production" in the angular.json file:_
`"extractCss": false,`

#### What are the steps to reproduce?
Create two angular projects, deploy one as custom element and use it in the other one like this:

_index.html of the component using the custom element:_

```
<body>
<custom-element-name></custom-element-name>
</body>
```
In my case I'm running the component using the custom element on localhost:4200 and the custom element itself on localhost:4004.
If i take a look at the custom element itself on localhost:4004 the .scss file is ignored, but on localhost:4200 it works fine.

<img alt="Screenshot_257" src="https://user-images.githubusercontent.com/2650749/57278097-eecf7980-70a5-11e9-8bb8-ed5948883435.png"><img alt="Screenshot_258" src="https://user-images.githubusercontent.com/2650749/57278100-f131d380-70a5-11e9-86b0-d15171b397ab.png">
The code looks the same too, even tho the text looks different. 😕 
<img width="650" alt="Screenshot_263" src="https://user-images.githubusercontent.com/2650749/57281601-9dc28400-70ab-11e9-91cd-491c7a7afb5e.png">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular CLI: 7.3.6
Node: 10.15.2
OS: win32 x64
Angular: 7.2.10
@angular/material 7.3.5
typescript 3.1.1
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

#### Is there anything else we should know?

This guy had the same issue, and his solution ("extractCss": false,) was the only thing working for me. Would love to be able to extract tho.

[Mat-dialog not displaying properly when used in custom elements](https://stackoverflow.com/questions/53953154/mat-dialog-not-displaying-properly-when-used-in-custom-elements#comment94746642_53953154)

**Comment by Splaktar** [comment]
Can you please post a GitHub repo and/or StackBlitz which reproduces this issue?

**Comment by Splaktar** [comment]
`extractCss` is a feature of the Angular CLI.

You mention that the `styles.scss` is "ignored". Are you sure that it is even in your production bundle? Can you check to see if those styles are included when you do `ng build --prod`?

This looks like an issue that we should transfer to Angular CLI. Is there any reason why this is a bug with Angular Material instead and should be addressed here?
