### ISSUE TITLE
Using keyboard to select chip breaks mat-chip when using Set.has().

### ISSUE THREAD

**Issue by Buttars** [angular/components#15980]
#### What is the expected behavior?
The `selected` attribute should be able to use the `.has` method on a `Set`.

#### What is the current behavior?
It throws `ERROR TypeError: _co.chips.has is not a function` when using keyboard selection. Although, it works fine when using a click to select the chip.

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-chip-selected-with-set-bug

1. Create a `formControl` with a `new Set()` as its initial value.
2. Hook up a `mat-chip-list` and `mat-chip` to the form control
3. In the `selected` attribute pass it the `formControl.value.has`
4. Use keyboard space/enter to try to select a chip    

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular/Material: 7+

#### Is there anything else we should know?
After selecting the chip via the keyboard it breaks mouse selection too.

**Comment by andrewseguin** [comment]
The chip list does not support form control and it looks like it is incorrectly hooking into some of the chip list APIs. If you remove the binding, you should be good to go: https://stackblitz.com/edit/mat-chip-selected-with-set-bug-lmuuab?file=app/app.component.html

**Comment by cbejensen** [comment]
In the example given, if you use the keyboard and press spacebar on a chip, it will appear to be selected, but it doesn't actually get added to the set. [Here's my fix.](https://stackblitz.com/edit/mat-chip-selected-with-set-bug-bhd5ue)
