### ISSUE TITLE
Global option for defaulting button type

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#15989]
#### Please describe the feature you would like to request.

Should be an injectable option config to default button to a particular type, e.g. "button"

#### What is the use-case or motivation for this proposal?

Buttons currently default to type "submit" if not specified. It is very common to want type button by default.

#### Is there anything else we should know?

We use an injectable option config in autocomplete, which is the pattern we want to use for this feature:
https://github.com/angular/components/blob/master/src/material/autocomplete/autocomplete.ts#L61

**Comment by ramarivera** [comment]
Is someone working on this? If not, could I take it? Thanks!

**Comment by klemenoslaj** [comment]
This issue is stuck here since May.

@andrewseguin I am willing to take this one, I think it's a nice addition to the api.

**Comment by rafaelss95** [comment]
@simon-mathewson do you pretend to send a PR with your changes?

**Comment by andrewseguin** [comment]
This will be closed since the team decided we would prefer not to add an API that changes browser defaults. It would be best for users to keep the habit of explicitly typing their buttons and understanding that it is something browsers handle.
