### ISSUE TITLE
matBadge should indicate a change of value with an animation;

### ISSUE THREAD

**Issue by andreElrico** [angular/components#15986]
#### Please describe the feature you would like to request.

When the badge-Value changes any sort of animation should occour in order to provide feedback and a better userexperience. This could be a wiggle, inflation-deflation or as I have tried a mat-ripple. (Is it possible to make a shrinking mat ripple that shrinks into the badge?)

#### What is the use-case or motivation for this proposal?

Better UX

#### Is there anything else we should know?

[STACKBLITZ](https://stackblitz.com/edit/angular-pmbehc?file=app%2Fbadge-overview-example.html)

**Comment by jelbourn** [comment]
Closing since I don't see us adding built-in animations for the badge
