### ISSUE TITLE
[Tooltip]: ChangeDetection is triggered to often

### ISSUE THREAD

**Issue by dmkorol** [angular/components#15990]
#### What is the expected behavior?
Change detection runs once when component is shown or become hidden

#### What is the current behavior?
When move mouse over button ChangeDetection is run a lot of times in short period of time

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-2g1mvi<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "@angular/material": "7.3.7",

**Comment by jelbourn** [comment]
@dmkorol can you provide more information? How many times are you seeing change detection run? On which application were you measuring? How were you measuring?

**Comment by dmkorol** [comment]
>can you provide more information? 
>How many times are you seeing change detection run? 
There is online reproduction(link above): https://stackblitz.com/edit/angular-2g1mvi
Please open the console to see results during moving on the button(it reproduce on all browsers)
For example, got 19 execution when I moved the cursor on the button

>How were you measuring?
I add a function on the view `{{val()}}` that write to console each time when it is run (when change detection is triggered on the view)
 
>On which application were you measuring?
In the real application, there is a lot of places where the tooltips were put, most of the component is a dummy and don't use change any custom change detection strategies. In some cases, there are a lot of information and tables. 
Desired behavior that tooltip should run change detection only once onShow or onHide.

**Comment by noririco** [comment]
> > can you provide more information?
> > How many times are you seeing change detection run?
> 
> There is online reproduction: https://stackblitz.com/edit/angular-2g1mvi
> Please open the console to see results during moving on the button(it reproduce on all browsers)
> For example, I got 19 executions of val(), when I moved the cursor on the button.
> 
> > How were you measuring?
> > On which application were you measuring?
> 
> I add a function on the view `{{val()}}` that write to console each time when it is run (when change detection is triggered on the view)
> 
> Desired behavior the tooltip should run change detection only once onShow or onHide.

This is raping my app !
look
![matMouseMovePerformance](https://user-images.githubusercontent.com/13832666/58011915-ef333000-7afb-11e9-963e-84581c78ee79.JPG)
![matNoMat](https://user-images.githubusercontent.com/13832666/58011916-ef333000-7afb-11e9-8286-d48267cef5f5.JPG)

**Comment by yakimko** [comment]
I found out if remove the second param from ComponentPortal https://github.com/angular/components/blob/5284a57b2f24319359d0528522feeca9c1393751/src/material/tooltip/tooltip.ts#L336

a problem will disappear.

do we really need to set it?

**Comment by crisbeto** [comment]
A lot of this comes from the fact that we have Angular animation events for when an animation starts and when it finishes. There's an in-progress PR (#19432) that decouples the tooltip from the Angular's change detection cycle and should resolve this issue.
