### ISSUE TITLE
Mat-Autocomplete options go under the screen on iOS

### ISSUE THREAD

**Issue by dadebulba** [angular/components#16004]
#### What is the expected behavior?
The option dropdown should appear over the input field

#### What is the current behavior?
The option dropdown goes under the virtual keyboard outside the screen 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-vyeusp

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material: 7.3.7
OS: iOS 12.2
Typescript: 3.1.1
Browser: Chrome 74

#### Is there anything else we should know?
The issue is present when the keyboard is active

**Comment by dadebulba** [comment]
May someone help me?

**Comment by leighannewarner** [comment]
I'm seeing this issue as well on a few different versions of iOS, I think it is due to the way iOS counts the screen under the keyboard as usable real estate, so the dropdown thinks it has space to go down instead of up.

**Comment by AbuHani** [comment]
is there any update on this issue ?

**Comment by zarend** [comment]
Hello @dadebulba ,

Thank you for reporting this. I'm not sure I can reproduce this issue, and it may have already been fixed.

When I test the examples on https://material.angular.io/components/autocomplete/examples, sometimes part of the options go offscreen, but that's only where there is not enough space on screen to display all the options.

Are you able to provide a screenshot of this issue?

Best regards,

Zach
