### ISSUE TITLE
input type="number" default value

### ISSUE THREAD

**Issue by aquaductape** [angular/components#16001]
I expect the `value` attribute to work on input number type, so that it is set to 5.
```html
<mat-form-field>
          <input type="number" matInput placeholder="Increase by..." value="5" ngModel name="stepAmount" />
</mat-form-field>
```
Instead it's just empty

**Comment by jelbourn** [comment]
This happens because you're setting both `value` and `ngModel` at the same time, and `ngModel` is taking precedence
