### ISSUE TITLE
Mat-Slider customization

### ISSUE THREAD

**Issue by sureshkona** [angular/components#16006]
1. Changing the thumb label color dynamically
2. track-fill color change dynamically
3. show thumb label and ticks continuously
4. increase the size of slider and ticks

Requirement 

![image](https://user-images.githubusercontent.com/9035286/57578241-c7ade900-74a5-11e9-988a-f7512687b00e.png)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
