### ISSUE TITLE
Can't select content when matTooltip is set in container

### ISSUE THREAD

**Issue by markus-heinisch** [angular/components#16012]
#### What is the expected behavior?
As user I want to select the content of a HTML element.

#### What is the current behavior?
When I use a matTooltip in a html container like div or span, the user can not select the content for copy/paste:
```<span matTooltip="Can't select text">A text to select, but can not select</span>```

#### What are the steps to reproduce?
https://angular-material2-issue-cef8r3.stackblitz.io
OR:
Just copy the code snippet from above into your HTML page....

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.8
Node: 10.8.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.6
@angular/cli                      7.3.8
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.6
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

#### Is there anything else we should know?
I have read the docs but I can't find any hint about selection.

**Comment by andrewseguin** [comment]
I believe this is due to our use of HammerJS, which helps us implement gesture support. In this case, I think its because of our `longpress` event handler.

**Comment by markus-heinisch** [comment]
Thanks @andrewseguin.
Is there anything that can I test or change on my side? 
e.g. uninstall HammerJS (app does not need mobile support, yet)

**Comment by paulferaud** [comment]
Any update on this? Anything we can do or change on our side? This is really disruptive to our users, that want to copy paste our data:
![SFOurmEiA6B](https://user-images.githubusercontent.com/43784631/65064391-61067380-d94e-11e9-9064-77d09d86b689.png)
```text
ed: , , , , , , , , , , , and 
```

**Comment by crisbeto** [comment]
Since 9.0.0-next.0 it possible to disable the touch getstures on tooltips using the `matTooltipTouchGestures` input. Disabling touch gestures will allow for text for be selected.
