### ISSUE TITLE
matMenuTriggerFor siblings of the same menu do not open

### ISSUE THREAD

**Issue by wiaterb** [angular/components#16011]
#### What is the expected behavior?
Every submenu opens up and is visible while mouse hovers menu entry.

#### What is the current behavior?
While moving mouse over menu entries, submenus show up only when the previous opened submenu was not of the same kind. https://stackblitz.com/edit/angular-zqmhjp?file=package.json

#### What are the steps to reproduce?
Angular 5: https://stackblitz.com/edit/angular-zqmhjp?file=package.json
Apparently it works as expected with Angular 7: https://stackblitz.com/edit/angular-material2-issue?file=app%2Fapp.component.html

Gif shows that some of _Vertebrates_ buttons do not trigger it's submenu to be open.
![ezgif-1-80b73452e091](https://user-images.githubusercontent.com/8410435/57618843-bc7dba80-7584-11e9-9229-85fd012a5c0a.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/core": "5.2.11",
"@angular/material": "5.2.5",
"typescript": "~3.1.1"
Chrome 73.0.3683.103
Windows  10

**Comment by crisbeto** [comment]
Closing since it appears to work on newer versions. In general we don't backport fixes to older versions, unless it's something very severe like a security vulnerability.
