### ISSUE TITLE
Components need to be compatible with stricter Ivy type checking

### ISSUE THREAD

**Issue by devversion** [angular/components#16028]
Eventually we need to go through our components and ensure that they still pass with Ivy's better/stricter type-checking. This can be done once type-checking is complete.

Type-checking progress is tracked with FW-1004.

**Comment by IanDesouza** [comment]
I believe this is the same issue (Angular 8)..

core.js:7187 ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at ViewContainerRef_.createEmbeddedView (core.js:20114)
    at DomPortalOutlet.attachTemplatePortal (portal.js:343)
    at DomPortalOutlet.attach (portal.js:225)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1184)
    at MatMenuTrigger.toggleMenu (menu.js:1166)
    at MatMenuTrigger._handleClick (menu.js:1511)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1575)
    at executeListenerWithErrorHandling (core.js:16053)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16088)

**Comment by devversion** [comment]
@IanDesouza That is a different issue and has been solved with https://github.com/angular/angular/commit/2b4d5c75486534decef4030d4166806878929e4c. This should be released soon as part of a new beta for the Ivy opt-in.

**Comment by icecoldfire** [comment]
When will this be fixed? I have the same issue as #16287.

```
core.js:7187 ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at ViewContainerRef_.createEmbeddedView (core.js:20128)
    at DomPortalOutlet.attachTemplatePortal (portal.js:343)
    at DomPortalOutlet.attach (portal.js:225)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1184)
    at MatMenuTrigger.toggleMenu (menu.js:1166)
    at MatMenuTrigger._handleClick (menu.js:1511)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1575)
    at executeListenerWithErrorHandling (core.js:16028)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16063)
```

with the following package file:

```
{
  "name": "client",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.0.3",
    "@angular/cdk": "8.0.1",
    "@angular/common": "8.0.3",
    "@angular/compiler": "8.0.3",
    "@angular/core": "8.0.3",
    "@angular/forms": "8.0.3",
    "@angular/material": "8.0.1",
    "@angular/platform-browser": "8.0.3",
    "@angular/platform-browser-dynamic": "8.0.3",
    "@angular/router": "8.0.3",
    "rxjs": "6.4.0",
    "tslib": "1.10.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.6",
    "@angular/cli": "8.0.4",
    "@angular/compiler-cli": "8.0.3",
    "@angular/language-service": "8.0.3",
    "@types/node": "8.9.4",
    "@types/jasmine": "3.3.8",
    "@types/jasminewd2": "2.0.3",
    "codelyzer": "5.0.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "protractor": "5.4.0",
    "ts-node": "7.0.0",
    "tslint": "5.15.0",
    "typescript": "3.4.3"
  }
}
```

**Comment by Splaktar** [comment]
FW-1004 seems to be specific to template type checking.

We already have fairly strict compiler flags in https://github.com/angular/components/blob/master/tsconfig.json. Are there plans to change those flags?

**Comment by rkirov** [comment]
random ping here, as this is a good flag to have.

**Comment by Splaktar** [comment]
FW-1004 has been resolved.

https://github.com/angular/components/blob/master/src/bazel-tsconfig-build.json has some, but not all strict flags enabled. Are there plans to change these to be more strict? 

Should we enable? I'm not sure how much value these bring.
```json
    "noUnusedParameters": false,
    "noUnusedLocals": false,
```

Should we also enable `"strictBindCallApply": true`?

What's the next step here as this is no longer blocked?

**Comment by Splaktar** [comment]
There is now documentation on the options for Ivy Template Type Checking:
https://next.angular.io/guide/template-typecheck

Related: https://github.com/angular/angular/issues/33452

**Comment by Splaktar** [comment]
Our Ivy Template Type Checking options are configured here
https://github.com/angular/components/blob/3f6a1fda916c0e490a5a38708222116dac3aa52f/tools/bazel/postinstall-patches.js#L107-L112

As mentioned there, they are in a postinstall patch due to https://github.com/angular/angular/issues/33452.

We'd like to enable `strictAttributeTypes` and resolve issues (like `NgModel#disabled` conflicting with other `disabled` inputs) related to it.

`strictDomLocalRefTypes` and `strictDomEventTypes` is also something that we would like to enable but we've seen cases where events on an `<input>` produce the `HTMLElement` type rather than `HTMLInputElement`. This needs further investigation and an issue report may need to be made.

**Comment by devversion** [comment]
This has been resolved.
