### ISSUE TITLE
Material Tabs should use `<a>` tag instead of `div` to improve websites SEO 

### ISSUE THREAD

**Issue by m98** [angular/components#16025]
#### Please describe the feature you would like to request.
Currently the tab is using `div` tags instead of `a` tag. Google webmaster team recently uploaded video series on JavaScript SEO, and in [this video ](https://www.youtube.com/watch?v=nwGY-9lwTF4&list=PLKoqnv2vTMUPOalM1zuWDP9OQl851WMM9&index=4 )he says:

> Make sure to include useful link anchorText and use the HTML anchor tag (...) do not rely on other HTML elements.

#### What is the use-case or motivation for this proposal?
Improve users wbsites SEO performance

**Comment by jelbourn** [comment]
Tabs that do navigation should use `MatTabNav`, which does use anchor elements. `MatTabGroup` uses the `role="tablist"` pattern which does not include navigation.
