### ISSUE TITLE
[cdkDragDrop] CopyArrayItem: items somehow connected

### ISSUE THREAD

**Issue by justAnormalUser00** [angular/components#16027]
I dont now if i am stupid or this is a bug... i asked several people and no one seems to know the answer.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-yr8ej6

1.) drag one item to the right container
2.) click on test button

#### What is the expected behavior?
click on test button should only change the value of the item in the right container on position 0 of the array

#### What is the current behavior?

click on test button changes both values

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.8
@angular/cdk                      7.3.7

**Comment by crisbeto** [comment]
It's because `copyArrayItem` only adds a reference to the new array, it doesn't actually do a deep copy of the object.

**Comment by justAnormalUser00** [comment]
thanks for the answer, is there a simple way to make a real copy?

**Comment by crisbeto** [comment]
The CDK doesn't provide a copying function out-of-the-box, but there are lots of solutions out there. E.g. something like this should do the trick in lodash:

```js
import {cloneDeep} from 'lodash';


onTalkDrop(event: CdkDragDrop<Element[]>) {
  if (event.previousContainer !== event.container){
    // Clone the item that was dropped.
    const clone = cloneDeep(event.previousContainer.data[event.previousIndex]);

    // Add the clone to the new array.
    event.container.data.splice(event.currentIndex, 0, clone);
  }
  else{
    moveItemInArray(
      event.container.data,
      event.previousIndex,
      event.currentIndex
    );
  }
}
```

**Comment by justAnormalUser00** [comment]
THANKS a lot :D works like a charm.
