### ISSUE TITLE
Bring back <span flex></span> for easy spacing in mat-card-actions, mat-dialog-actions, mat-toolbar etc

### ISSUE THREAD

**Issue by jpike88** [angular/components#16029]
`<span style="flex: 1 1 auto;"></span>` or
`<span class="some-flex-spacing-class"></span>` shouldn't be necessary.

One is a pain to remember and the other encourages the use of global styles.

It would be good to have a standard flex attribute like like the old angular had. I understand angular/flex-layout takes care of layout now, but this is such a common use case I think it should be built in. Besides there's no clear way of how to achieve this with angular/flex-layout anyway.

**Comment by andrewseguin** [comment]
When I first moved from AnguarJS to Angular, I felt the same way. I really enjoyed how easy it was to layout my elements but none of my learned knowledge transfered to Angular.

I forced myself to learn flexbox and the learning curve was a bit rough, but once I got used to it, I actually preferred it over AngularJS layout. Even better, now that I knew flexbox, I had gained skill that was framework agnostic so I could use it anywhere.

I strongly encourage you to give flexbox another shot. Here's a great site that I used to learn flexbox, and you might like it too: https://flexboxfroggy.com/
