### ISSUE TITLE
checkbox is buggy

### ISSUE THREAD

**Issue by vivek-daffodill** [angular/components#16022]
Hi, Please tell if there is any fix on that.

while I click on mat-checkbox it first checked and then if I unchecked it pop-up 2 times and at last unchecked.

sometimes I click on the checkbox and then have to wait to make it checked, if not checked then I have to scroll or do something on the screen then it gots checked.

I am using Macbook pro.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
