### ISSUE TITLE
Material import update schematics use wrong quotes

### ISSUE THREAD

**Issue by StephenFluin** [angular/components#16035]
#### What is the expected behavior?
When I update from 7.x to 8.0 and schematics are applied to update my imports, it should use the quote types I originally used.

#### What is the current behavior?
Double quotes are always used.

#### What are the steps to reproduce?
import {MatButtonModule} from '@angular/material';

And then run the 7->8.0-rc update of @angular/material

**Comment by jelbourn** [comment]
Closing this because AFAIK we have no control over the style of quotes the `ts` compiler APIs output. This is something that would be better done at the CLI-level.
