### ISSUE TITLE
Docs site footer should link to full license

### ISSUE THREAD

**Issue by mamichels** [angular/components#16039]
#### What is the expected behavior?
The applicable license shall match on all references to a specific piece of software.

#### What is the current behavior?
While on github it clearly states the repo is publicized under MIT-licence the website material.angular.io states the following:
Code licensed under an MIT-style License.

While the github repo has the full licence text by default, there is no link to the full licence text on the website. Stating that it is licenced under an MIT-**style** licence will create confusion about any potential change that could have been made to the agreement.

#### What are the steps to reproduce?
Trivial just visit: https://material.angular.io/ and scroll to the bottom

**Comment by jelbourn** [comment]
That bit should be a link to the full license like it is on angular.io
