### ISSUE TITLE
angular material paginator is not working properly when changeDetectionRef is detached. 

### ISSUE THREAD

**Issue by hsnklcrsln** [angular/components#16032]
I am using mat-table. 
And I am trying to create a grid-view to manage my data.
I have single and multi selection mode in my grid.
I have also render function for column like below

<ba-gridview [(ngModel)]="State.Selected2" [columns]="goalsGridViewColumns" [dataSource]="goals" selectionMode="Single" [displayPaginator]="false"></ba-gridview>

 goalsGridViewColumns: IGridViewColumn[] = [
        { title: "Goal Name", data: "GoalName" },
        { title: "Start Date", data: "StartDate"},
        { title: "End Date", data: "EndDate" },
        { title: "Target Amount", data: "TargetAmount",render: amountFormatter },
        { title: "Remaining Amount", data: "RemainingAmount" }
    ];

render(element: any, column: any) {
        if (_.isFunction(column.render)) {
            return column.render(element[column.data]);
        }
        else {
            return element[column.data];
        }
    }
ChangeDetectionStrategy is OnPush but render method is working Default mode.

My idea is "if I detach change detection , render function will work once."
I am calling detectChanges function only if item is selected.

The issue is paginator is not working if I detach.
I guess you need to add a callback after click paginator selection.
I will call a function to open change detection.
(page=>output) is not working as expected. 

![image](https://user-images.githubusercontent.com/7337804/57783450-cc3d0080-7736-11e9-901d-e03d31629ae0.png)

I cannot click if I detach. Is there any help?

**Comment by andrewseguin** [comment]
Hey, we'd love to help. Please re-open an issue that follows the issue template, and be sure to include a reproduction in StackBlitz so that we can look into what is happening. If you suspect that it is not an issue, but you are only looking for help troubleshooting, please feel free to ask a question to our community on StackOverflow
