### ISSUE TITLE
Add a way to better identify clicked elements

### ISSUE THREAD

**Issue by mackelito** [angular/components#16031]
#### Please describe the feature you would like to request.
Add a way to identify the element that has been clicked

#### What is the use-case or motivation for this proposal?
Currently we are using Sentry for error reporting.
In the breadcrumbs this is what we see:
<img width="1055" alt="Screenshot 2019-05-15 at 10 31 03" src="https://user-images.githubusercontent.com/598463/57760787-93803580-76fc-11e9-863e-344efaad9535.png">

`div.mat-form-field-wrapper > div.mat-form-field-flex`

This does not really provide us with any good info about what element was clicked. Perhaps we also could have some more into about the element's context?

**Comment by andrewseguin** [comment]
It's not clear what you are asking for us to provide. We do not integrate with Sentry. It sounds like whatever tool you are using needs to be able to provide more context about the event's target element stack
