### ISSUE TITLE
[Datepicker] - Prevent autocomplete functionality

### ISSUE THREAD

**Issue by Qocotzxin** [angular/components#16048]
#### Please describe the feature you would like to request.
Add the option to prevent Datepicker from auto filling a date.

#### What is the use-case or motivation for this proposal?
Currently Datepicker does not autocomplete a date when 'Moment' considers the current input value as an invalid date. Since I need to change the business rule for the autocomplete feature (client requirement for years specifically), it would be great if I can stop the autofill in any case (not only when date is invalid) and create my own logic in a kind of middleware and send manually the new value I want to display.

#### Is there anything else we should know?
Current version:
    "@angular/material": "^7.3.4",
    "@angular/material-moment-adapter": "7.3.4",

I was finally able to solve the issue by creating a custom adapter, but I still feel that this would be a great feature to have in order to avoid creating an adapter just to return always null (which prevents autocomplete).

**Comment by crisbeto** [comment]
It's not really autocompleting the date, it just tries to parse the current input that's the date it arrived at. I don't think we can make assumptions about when the user is done typing. Closing since this is one of the use cases for a custom date adapter.
