### ISSUE TITLE
Second loadmore button doesn't trigger

### ISSUE THREAD

**Issue by philip-firstorder** [angular/components#16043]
#### What is the expected behavior?
When we have multiple loadmore buttons they should trigger to load their respective children.

#### What is the current behavior?
Only the first loadmore button triggers a load, the next will not load their children anymore.

#### What are the steps to reproduce?
I just set the `batchNumber = 2;` to get multiple loadmore buttons.<br/>
StackBlitz https://stackblitz.com/edit/angular-m5vayy?file=app/tree-loadmore-example.ts<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 7.3.7

#### Is there anything else we should know?
Will open a pull request if I find a fix.

**Comment by philip-firstorder** [comment]
I found a fix for this and opened a pull request,  you can close after merging.

**Comment by crisbeto** [comment]
Closing this since the tree is in the process of being revamped.
