### ISSUE TITLE
multiTemplateDataRows property not working when ivy is enabled

### ISSUE THREAD

**Issue by Hendrik212** [angular/components#16044]
#### What is the expected behavior?

No error

#### What is the current behavior?

Property multiTemplateDataRows fails when ivy is enabled with the following errors:
ng serve:

`ERROR TypeError: Cannot read property 'viewContainer' of undefined
    at MatTable.set multiTemplateDataRows [as multiTemplateDataRows] (table.js:1328)
    at setInputsFromAttrs (core.js:12995)
    at postProcessDirective (core.js:12784)
    at instantiateAllDirectives (core.js:12678)
    at createDirectivesAndLocals (core.js:12097)
    at ΔelementStart (core.js:15361)
    at AppComponent_Template (template.html:1)
    at executeTemplate (core.js:12019)
    at checkView (core.js:13370)
    at componentRefresh (core.js:13134)`

#### What are the steps to reproduce?

1. ng new myApp --enable-ivy
2. cd myApp
3. ng add @angular/material@next
4. use code from Angular Material Docs Example "Table with expandable rows" [Stackblitz link](https://stackblitz.com/angular/drlaxdpogep?file=app%2Ftable-expandable-rows-example.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using the latest release candidates of angular 8:

Angular CLI: 8.0.0-rc.4
Node: 10.13.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.1
@angular/material                 8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

#### Is there anything else we should know?

The viewChild "_rowOutlet" seems to be undefined when the following function is called in table.js, leading to the error:

`set multiTemplateDataRows(v) {
        this._multiTemplateDataRows = coerceBooleanProperty(v);
        if (this._rowOutlet.viewContainer.length) {
            this._forceRenderDataRows();
        }
    }
`

If I remove the multiTemplateDataRows property and the second detail row in the example, the table renders correctly but without the expanding rows functionality.

**Comment by jloosli** [comment]
Until the fix is pushed out, I was able to get around this by changing

``` <table multiTemplateDataRows>```

to 

``` <table [multiTemplateDataRows]='true'>```
