### ISSUE TITLE
angular material date picker numeric keypad enable

### ISSUE THREAD

**Issue by pushpass** [angular/components#16046]
#### What is the expected behavior?
Only numeric keypad to be shown. The date format we are using is dd.mm.yyyy and no other format are allowed. 

#### What is the current behavior?
In mobile devices onclick of text input for the date picker, numeric keypad is not shown (normal text keypad is shown)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material vaersion : 7.3.0

#### Is there anything else we should know?
 The date format we are using is dd.mm.yyyy and no other format are allowed.

**Comment by jelbourn** [comment]
The text input is totally under your control; you can add any `type` to want to the element that has`matDatepicker`

**Comment by pushpass** [comment]
Thank you for the response. If we give type:number for the input, we cannot select the date from calender.

**Comment by jelbourn** [comment]
Is your `DateAdapter` formatting to an output that would be accepted by `type="number"`?

**Comment by jelbourn** [comment]
Actually yeah, `input type="number"` doesn't support setting the value to something that's not a `number`.

Other than setting that, I don't know how else you would signal the OS to show the number keypad.

**Comment by jelbourn** [comment]
https://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input
