### ISSUE TITLE
MatExpansionPanel animates header height when first rendered

### ISSUE THREAD

**Issue by chemass** [angular/components#16067]
#### What is the expected behavior?
Given an expansion panel with a header `<mat-expansion-panel-header collapsedHeight="10rem" expandedHeight="10rem">` it should be initially rendered at the specified height.

#### What is the current behavior?
The header is rendered at it's standard height, then animates to the specified height

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-48ryox?embed=1&file=app/expansion-overview-example.html)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7x, Material 7x

**Comment by chemass** [comment]
Obviously the size I've provided is silly (we actually want a fixed 2rem header), but it shows the issue!
Problem is that we have several vertically stacked panels, so on every render it creates a very noticable shrinking animation.

**Comment by meepou** [comment]
I was about to post the same issue when I saw yours, I had a stackblitz as well : https://stackblitz.com/edit/angular-p6rpru-nrrbxk (just refresh the preview and you see accordions jump)

I can't find a css workaroud as it happens so fast, if someone has a temporary solution ...
