### ISSUE TITLE
mat-select multiple should support user provided toggle inputs instead of default checkbox

### ISSUE THREAD

**Issue by Suresh918** [angular/components#16068]
#### Mat-select multiple is having checkbox as default toggle input in the options as shown below
![image](https://user-images.githubusercontent.com/6056573/58030284-e6fae500-7b3b-11e9-9127-c0d878c24c80.png)

But it's good to give option to the user for configuring toggle input so that he can config what ever toggle input he wants such as toggle button, slide toggle etc. It gives more flexibility to the user.

**Comment by crisbeto** [comment]
If we did that, there would be no nice way for Material to make it checked automatically when the option is toggled.

**Comment by Suresh918** [comment]
shall we add toggle button and slide toggle besides checkbox and expose one input to configure the type of toggle input so that user can select toggle input among those.

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because of the problems mentioned in the comments above and the fact that there hasn't been any traction on issue for a long time.
