### ISSUE TITLE
IOS/Mobile Scrolling not smooth on Scrolling Dialog Content

### ISSUE THREAD

**Issue by Oliverq755** [angular/components#16061]
#### What is the expected behavior?
The scroll of Dialog content should be smoother like the component scroll.

#### What is the current behavior?
The dialog content scrolls slowly (like step by step).

#### What are the steps to reproduce?
1. Create a component with some form fields in it.
2. Create a service and open that component is a dialog component. For instance 
`const dialogRef2 = this.dialog.open(userFromComponent, windowFit).afterClosed().subscribe(result => {
             this.staticData.preventScroll = false;
                 if (data && data['typeofEvent'] == 'Meet') {
                     if (this.checkStatus('Call')) {
                         this.updateStatusActivites(this.staticData.StatusData['My_Status'], 'Meet')
                     }
                     this._statusColorFill('Meet');
                     this.updateStatus('Meet');
                 }`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.3.8
Material: 7.3.7
Device: iPad 11 Pro
OS: iOS 
iOS Version: 12.3
Browsers: Safari

**Comment by Oliverq755** [comment]
It cannot be reproduced on desktop, It's only reproducible from the iOS devices.

**Comment by crisbeto** [comment]
I was testing it on an iPhone.

**Comment by josephperrott** [comment]
@Oliverq755 Can you provide a [link to a stackblitz](https://stackblitz.com/fork/components-issue) with a reproduction we can test with?

**Comment by Oliverq755** [comment]
cannot reproduce
