### ISSUE TITLE
mat badge gets cut off when utilized in a navigation material list

### ISSUE THREAD

**Issue by alexw10** [angular/components#16076]
#### What is the expected behavior?
The badge should be fully visible.

#### What is the current behavior?
The badge gets cut off

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-qyyavd

**Comment by wnvko** [comment]
You should not put the badge into the link as it is position relative.
You can make the anchor tag list item and put inside it a `div` with the text and badge like this:

```
<mat-nav-list>
  <a mat-list-item *ngFor="let link of links" href="...">
    <div matBadge="15" matBadgeOverlap="false">
      {{ link }}
    </div>
 </a>
</mat-nav-list>
```

You can remove `matBadgeOverlap` if you do not need it and consider setting `matBadgePossition` if you need it

**Comment by alexw10** [comment]
Thanks  @wnvko that was helpful, I think it solves this issue going to close.
