### ISSUE TITLE
Tooltips: Should not overlap

### ISSUE THREAD

**Issue by bsteffl** [angular/components#16072]
#### What is the expected behavior?
I'm not sure if this is a bug or expected behavior. I'm proposing that tooltips don't overlap if you happen to have your mouse positioned onscreen and use keyboard to activate tooltip.

#### What is the current behavior?
Currently you can get tooltips to overlap by using a mouse to set focus and the keyboard focus at the same time. Example is shown with buttons.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-c5w9uu . 

![image](https://user-images.githubusercontent.com/10760551/58049688-0f221e00-7b13-11e9-9526-ba0c6d3033d6.png)  
Set your mouse on one of the move buttons, then use keyboard to tab through buttons. Notice the tooltips overlap.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.15
Material 7.3.7

#### Is there anything else we should know?
This may or may not be a bug.

**Comment by jelbourn** [comment]
While it would be nice for this not to happen, addressing it isn't straightforward; we'd either have to only show one tooltip at a time or make the tooltips avoid each other (super complex). Based on the cost-to-fix vs. how often it happens, I feel comfortable saying we won't be able to do anything about this one.

**Comment by bsteffl** [comment]
Thanks for taking a look.
