### ISSUE TITLE
[Docs] Tests with MatButton failing after migration to v8 RC1

### ISSUE THREAD

**Issue by gund** [angular/components#16078]
#### Please describe the feature you would like to request.

Document in changelog about [moving disabled input form props to attributes](https://github.com/angular/components/pull/15308) as it may impact unit tests.

#### What is the use-case or motivation for this proposal?

While upgrading material from v7 => v8 RC1 everything worked but few unit tests started to fail where disabled property was probed on material buttons.

It was tested via Angular's `DebugElement.properties.disabled` API and since mat-button now set's it as attribute that is no longer the case and it's now in `DebugElement.attributes.disabled`.

#### Is there anything else we should know?

From the final functional perspective this may be not a breaking change since disabled property and attribute are synchronised but while testing via `DebugElement` API this will impact test cases.

So it will be good idea to note this in the changelog.

**Comment by jelbourn** [comment]
I added this to the breaking changes for v8.0.0
