### ISSUE TITLE
[Migration] Error when using MatChipInputEvent

### ISSUE THREAD

**Issue by gund** [angular/components#16070]
#### What is the expected behavior?

Migration should properly locate the module from where to import `MatChipInputEvent`.

#### What is the current behavior?

Shows error during migration when encounters `MatChipInputEvent` and does not migrate other imports in same file:
```
ERROR: /my-project/src/app/shared/modules/modals/search-profile/component/search-profile-modal/search-profile-modal.component.ts:8:3 - MatChipInputEvent was not found in the Material library.
```

#### What are the steps to reproduce?

1. `ng new test-app` (with angular v7)
2. `ng add @angular/material`
3. Import anywhere in component code `import {MatChipInputEvent} from '@angular/material';`
4. ng update --next @angular/cli @angular/core @angular/material

And wait until material migrations will complete. Then check logs output and the import will not be migrated in file with `MatChipInputEvent`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular v8 RC4
Material v8 RC1

**Comment by josephperrott** [comment]
Closing as this issue looks to be out of date.

**Comment by gund** [comment]
Looks like fixed now. This is the diff after migrations:
![image](https://user-images.githubusercontent.com/3644678/58959113-abe7eb00-87a4-11e9-8aca-5853fcc104bc.png)
