### ISSUE TITLE
mat-form-field suffix buttons not in alignment with a preceding suffix element

### ISSUE THREAD

**Issue by kakins** [angular/components#16083]
#### What is the expected behavior?
matSuffix buttons should appear in alignment with matSuffix <span> elements in outlined form fields.

#### What is the current behavior?
A matSuffix button is placed awkwardly to the bottom right of a preceding suffix element.

#### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/14915247/58125730-d8154080-7bd6-11e9-98cb-04a1d51ef0b5.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular & Material 7

**Comment by josephperrott** [comment]
Closing, as it appears to be working as expected in the current release based on [this repro](https://stackblitz.com/edit/angular-1gmmlm?file=app/input-prefix-suffix-example.html)
