### ISSUE TITLE
Support single selection in MatSelectionList

### ISSUE THREAD

**Issue by Angelinsky7** [angular/components#16097]
#### Reproduction

https://stackblitz.com/edit/selection-list-model-odaxyp?file=app/list-selection-example.ts

Steps to reproduce:
1. Try to click on some choices
2. After a while no choice are working anymore (to be sure try to quickly selected and deselect differrent/the same item)
  
#### Expected Behavior

Only one checkbox should be activated at the same time
The component should remain functional after using it.

#### Actual Behavior

Mullitple checkboxes are activated but the multiple settings is set to false
The component stops working and it's impossible to select something

#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): Firefox

**Comment by jelbourn** [comment]
The `MatSelectionList` doesn't support single-selection currently.

**Comment by Angelinsky7** [comment]
@jelbourn Ok, but this is strange because the api permits it, and this is partially working.
Should we no use the SelectionModel<> for options ?

**Comment by jelbourn** [comment]
The `MatSelectionList` just currently assumes it's always in multi-selection mode. It would take some extra logic to enforce single selection. Plus, the toggles should be rendered as radio-buttons in that case.

**Comment by Angelinsky7** [comment]
Or not rendered at all

**Comment by crisbeto** [comment]
Closing since this is supported now.
