### ISSUE TITLE
input: floating label does not work on IE using Angular Elements

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#16095]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Create angular component that uses mat-input with floating label on and packaged this component using custom angular elements as given here https://angular.io/guide/elements.

2. Now run application in IE 11 and see. floating label does not float. 
 
 
#### Expected Behavior
mat input label should float in IE 11
What behavior were you expecting to see?

#### Actual Behavior
mat-input floating label does not work on IE using angular elements
What behavior did you actually see?
mat-input floating label does not work on IE using angular elements

#### Environment

- Angular: 7.2.0
- CDK/Material: 7.2.0
- Browser(s): IE 11
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
We run our dev app with Angular Elements and the floating labels work there. Can you post a Stackblitz that shows your issue?

**Comment by sandeeppatidar30** [comment]
This is the sample demo i have created -
https://stackblitz.com/edit/angular7-elements-aqf4ax?file=src/app/button/button.module.ts
