### ISSUE TITLE
Regression mat-slide-toggle keeps visual focus after click

### ISSUE THREAD

**Issue by FritzHerbers** [angular/components#16109]
#### Reproduction

In material2 v7.3.7 the focus of the mat-slide-toggle persists after clicking.
In material2 v6 the focus was removed

[https://stackblitz.com/edit/dynamic-nested-topnav-menu-sbbms3 v7](https://stackblitz.com/edit/dynamic-nested-topnav-menu-sbbms3?file=app/app.component.html)

[https://stackblitz.com/edit/dynamic-nested-topnav-menu-yr1qec v6](https://stackblitz.com/edit/dynamic-nested-topnav-menu-yr1qec?file=app%2Fapp.component.html)

Steps to reproduce:
1. Press toggle
2. (Move mouse away and) look if the focus visually remains
 
 
#### Expected Behavior

After clicking the toggle the visual focus should be removed.

#### Actual Behavior

In material2 v7 the visual focus remains.

#### Environment
Desktop

**Comment by devversion** [comment]
We actually fixed that now https://github.com/angular/components/commit/917a52e03cca1b3568d29094bbf430846ba1c3c9. Thanks for submitting this issue. Fix will be available with version 8 of Angular Material.
