### ISSUE TITLE
Dismissing mat-dialog using escape key exits macOS fullscreen

### ISSUE THREAD

**Issue by chriskinzel** [angular/components#16105]
#### Reproduction

StackBlitz: https://angular-6wurmg.stackblitz.io

Steps to reproduce:
1. In Safari browser, open mat-dialog with default config (or any config that allows close on escape key)
2. Fullscreen Safari browser window on macOS
2. Press escape key
 
 
#### Expected Behavior

Dialog closes, fullscreen unchanged.

#### Actual Behavior

Browser window exits fullscreen, then dialog closes.

#### Environment

- Angular: 7.2.12
- CDK/Material: 7.3.7
- Browser(s): Safari 12.1.1
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This happens in Chrome as well. I don't think we can do much about it though, because the browser doesn't allow for the escape key to be blocked in fullscreen mode since it'll prevent the user from exiting it.

**Comment by chriskinzel** [comment]
Just for clarification, I'm talking about the windowed fullscreen mode on macOS not making the webpage fullscreen. In windowed fullscreen I don't see this behaviour on Chrome, just Safari. It must be possible to prevent the escape key from performing the default action is this mode because this problem doesn't occur with bootstrap modals https://getbootstrap.com/docs/4.0/components/modal/ (opening modal on page and pushing escape when in windowed fullscreen mode does not exit fullscreen in Safari, just closes the modal as expected).

**Comment by crisbeto** [comment]
I see what you mean now. It looks like we can `preventDefault` the behavior, but I'm not sure whether we want to be blocking OS-level interactions like this. On the other hand, keeping it does look very jarring. What do you think about this @jelbourn?

**Comment by jelbourn** [comment]
I reproduced it and it is pretty weird. Do you see any downside to using `preventDefault`?
