### ISSUE TITLE
Support new dark theme properties from official Material documentation

### ISSUE THREAD

**Issue by frankvdb7** [angular/components#16107]
#### Feature Description

Update the theme style sheets to conform the new Dark Theme specifications in:
https://material.io/design/color/dark-theme.html#properties

#### Use Case

As an user I want to the library to conform to the standards described in the official material docs.

**Comment by devversion** [comment]
I haven't been looking specifically in our themes, but it would be great if we'd capture a few individual things that do not match up with the Material Design specification. Definitely something we should look into though.

**Comment by amysorto** [comment]
Closing this issue since you can create dark themes that adhere to M3 now: https://material.angular.io/guide/material-3#how-to-use-material-3-in-your-app
