### ISSUE TITLE
ERROR multiple event matches matInput / matAutocomplete / FormControl

### ISSUE THREAD

**Issue by BasHamer** [angular/components#16121]
Opening this to create a google hit for others and collect information in case it comes back.

I've found 2 encounters with "ERROR multiple event matches"
**Second encounter; not fixed**
code snippet:

```
      <mat-form-field class="example-full-width">
        <span matPrefix>has been &nbsp;</span>
        <input matInput placeholder="State name" value="State" required
               [formControl]="stateFormControl"
               (focus)="focused = true"
               (focusout)="focused = false"
               [matAutocomplete]="autoState">

        <mat-error *ngIf="stateFormControl.hasError('required')">
          State name is <strong>required</strong>
        </mat-error>

        <mat-hint align="start" *ngIf="focused">
          <p><b>Given</b> the {{domainObject.name}} has been {{eventState.state.name}}</p>
        </mat-hint>
      </mat-form-field>
    </ng-container>

    <mat-autocomplete #autoEvent="matAutocomplete">
      <mat-option *ngFor="let option of domainObject.events" [value]="option.name">
        {{option.name}}
      </mat-option>
    </mat-autocomplete>
```

the call stack is attached in a log
[localhost-1558808464055.log](https://github.com/angular/components/files/3219606/localhost-1558808464055.log) nothing removed, but a pretty short session. I'm not worried about any private information in the log.

[package.json.txt](https://github.com/angular/components/files/3219607/package.json.txt)

The error line from the stack trace is "<mat-option *ngFor="let option of domainObject.events" [value]="option.name">"

The result is that some of the valueChanges events work, some don't fire. I was unable to reproduce it. 

**First encounter; fixed**
I did have this error message show up one other time, that was my bad with a form control that had the following:
```
[formControl]="nameFormControl"
(ngModelChange)="setEvent($event)"
```

Changing to using valueChanges observable on the FormControl solved that. The error also pointed clearly to my code with an error on the input, not the autocomplete.

**Comment by Airblader** [comment]
formControl binds a reactive form control, ngModelChange is a non-reactive forms event. You're mixing template driven and reactive forms. 
Angular supported this to an extent until Angular 8, but it has been removed entirely and will then simply error because ngModelChange will not exist on the host without the ngModel directive anymore. See https://angular.io/api/forms/FormControlDirective#use-with-ngmodel (it says removed in Angular 7, but that didn't happen) 

It has nothing to do with Angular Material, though, and also isn't an issue and should therfore be closed.

**Comment by BasHamer** [comment]
yup that was the First Encounter, the first one does not have that event and does not reproduce easily. I put it in as they both had the same error message. 

The second one (with the code up top) does not have that going on. I'll update the ticket to clarify.

**Comment by BasHamer** [comment]
Found it, this error happens if you have duplicate key/value entries in your autocomplete list and you select one of them.

**Comment by BasHamer** [comment]
look like my code had that identical error message in it. might have all been a false alarm.
