### ISSUE TITLE
Angular Dynamic Menu using Material design

### ISSUE THREAD

**Issue by tt0686** [angular/components#16120]
I want to create a dynamic menu, the data is get from database for instance. Here is the https://stackblitz.com/edit/angular-dmenu project 

In the dynamic-menu.component.html in the StackBlitz project there are the dynamic solution and the static solution(that is commented). 

The static solution should be how the dynamic solution will be rendered after executes. 
If i just run with the static solution(uncomment and commented the dynamic) everything runs as expected, but if i try with the dynamic solution the menu does not work as expected (the main buttons stays on top of each other and the submenus do not display and work properly). 
Is this related with how ng-template affect the CSS styles ? 
Looking through Chrome developer tools i am able to see that the class="mat-menu-item ng-star-inserted" attribute in the dynamic version is added to the button for instance and this does not happen in the static version. I have try everything but i can not get it why is this happening. And how can i fix this. I am new to Angular but i want really understands how the frameworks works 

Thanks in advance 

Best regards

**Comment by andrewseguin** [comment]
Check out this StackOverflow answer - it may point you in the right direction: https://stackoverflow.com/questions/48146171/dynamic-nested-material-menu-from-json-object-in-angular-5

In particular, I think you want the answer provided by Datum Geek where you have an arbitrary amount of nesting. His approach was to create a component named `MenuItemComponent` that rendered a button and items, but could possible contain itself for nested menu buttons
