### ISSUE TITLE
Mat nav list item border radius does not affect ripple

### ISSUE THREAD

**Issue by paweljur** [angular/components#16124]
(This is my first ever public issue, bug report etc.)
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When defining border radius for mat-list-item the ripple should have the same border radius as the mat-list-item.

#### What is the current behavior?
Ripple is unaffected by mat-list-item's border radius (it does work with mat-button).

#### What are the steps to reproduce?
https://stackblitz.com/edit/mat-nav-item-ripple-bug?file=app/app.component.html

Mat-button has defined border radius and it's ripple is correct.
Mat-list-item inside mat-nav-list with the same style has incorrect ripple even tho the borders are changed.

#### What is the use-case or motivation for changing an existing behavior?
Current behavior is inconsistent with other components and requires bad practices to work around to work as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Core: 7.2.15
CDK/Material: 7.3.7
Browser: Chrome 74.0.3729.169
OS: Windows 10

#### Is there anything else we should know?
After closer inspection in chromes dev tools i was able to determine that: 
- in case of mat-button, mat-ripple is first child of mat-button, and has border-radius set to inherit
- in case of mat-nav-item, mat-ripple is inside mat-nav-item-content and none of them has defined border-radius
- applying border-radius as inherit with chromes dev tools for both mat-nav-item-content and mat-ripple fixes the ripple

**Comment by crisbeto** [comment]
We tried making a fix for this, but it ends up breaking other use cases. You can apply the same changes to your code fix it for yourself. https://github.com/angular/components/pull/16181
