### ISSUE TITLE
[Menu] Dropdown menu pane crashes when you scroll

### ISSUE THREAD

**Issue by talipcr** [angular/components#16128]
#### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/menu/overview#nested-menu
2. Click on menu and scroll

#### Actual Behavior

![chrome-capture](https://user-images.githubusercontent.com/15056752/58464453-02668100-8136-11e9-8ef4-77663b6ecfe0.gif)

#### Environment

- CDK/Material: 7.3.7
- Browser(s): Chrome 74.0.3729.169
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Should be fixed in 8.0 by https://github.com/angular/components/pull/15454.
