### ISSUE TITLE
Tab example interferes with the table of contents

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#16132]
#### Documentation Feedback

The tabs table of contents contains some header text that is in one of the example snippets.

**Affected documentation page:** https://material.angular.io/components/tabs/overview#

![eOHMuQ9TMAG](https://user-images.githubusercontent.com/22898577/58507230-19ad6a80-8146-11e9-8f3c-a1c662e7a1b7.png)

**Comment by crisbeto** [comment]
I can't reproduce this anymore. It likely got fixed when the example rendering was being reworked.
