### ISSUE TITLE
Move npm login check before building in publish-release

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16141]
I accidentally failed `npm login` twice today and had to wait through the whole build again.

**Comment by jelbourn** [comment]
Also it pushed the tag to upstream and subsequent publish failed because the tag already exists

**Comment by devversion** [comment]
@jelbourn Fair point with the `npm login` thing. Thinking about the tag issue you also mentioned. We actually have logic that should use the existing remote/local tag if it refers to the proper SHA.

Do you remember the output of the release staging tool? Was it complaining about the tag existing locally or remotely?
