### ISSUE TITLE
Horizontal virtual scroll example is broken in IE11

### ISSUE THREAD

**Issue by zealitude** [angular/components#16144]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

Horizontal virtual scroll example is broken in IE11
https://material.angular.io/cdk/scrolling/overview

**Comment by jelbourn** [comment]
Confirmed that this example is broken in IE11

**Comment by jelbourn** [comment]
Since Angular deprecated IE11 support in v12 and plans to remove it in v13, I don't think we're realistically going to fix this.
