### ISSUE TITLE
Paginator -> can i have a option to remove the tooltip for last/next button ?

### ISSUE THREAD

**Issue by ChenSaizhong** [angular/components#16158]
#### Feature description:

 I want to disable the tooltip for last/next button. But it seem have no this option.

![WX20190530-162416](https://user-images.githubusercontent.com/38367612/58624026-d39d0600-8301-11e9-9717-d555ef694ba8.png)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)

**Comment by andrewseguin** [comment]
You can use the internationalization class provider to supply an empty string for those tooltips, which will cause them to not appear.

https://stackblitz.com/edit/angular-htqibs-1bj57p?file=app/paginator-overview-example.ts
