### ISSUE TITLE
allow for connected overlay to be positioned relative to a rectangle

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#16160]
#### Feature Description

I would like to see something like the following interface added to FlexibleConnectedPositionStrategyOrigin:
```
interface ClientRectSource {
  getBoundingClientRect(): ClientRect;
}
```
#### Use Case

I need to position around a rectangle instead of an Element.  This is to position an overlay around a word in a textarea.  Currently I am doing this by creating an ElementRef, but would prefer something officially supported (my previous version was casting to an HTMLElement and was broken when support for more origin types was added).

e.g. 
```
new ElementRef({
  getBoundingClientRect() {
    //Calculate rectangle of word within textarea
  }
}),
```
The existing point option is not enough since it doesn't have height (I need to position below or above the word depending on available space).  Besides, a fixed point wouldn't allow for scrolling (although I think in my case most means of scrolling would close the overlay anyway).

**Comment by crisbeto** [comment]
That's an interesting use case that I hadn't though of. We already support positioning it relative to a point so expanding it to a rectangle should be easy.
