### ISSUE TITLE
Angular Elements with outlined input label

### ISSUE THREAD

**Issue by tmburnell** [angular/components#16168]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Create an Angular Element that contains an input with appearance of outline set and has a label provided.
2. After it is built and and used it looks fine before you touch it. 
3. When you select the input the label will animate up, however does not cause the outline behind the label to hide. 

I have this stack blitz that has my built js and css files, but cant quite figure out how to get it to render in stackblitz (so you can copy them and run them locally).
https://stackblitz.com/edit/angular-element-outline-input
 
 
#### Expected Behavior

What behavior were you expecting to see?
The outline should black out behind the label as it does when not using angular elements.

#### Actual Behavior

What behavior did you actually see?
The outline should black out behind the label as it does when not using angular elements.

#### Environment

- Angular: Angular 8
- CDK/Material: material 8 (have not verified earlier versions because was having a build conflict)
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macos

**Comment by tmburnell** [comment]
I have determined in an angular app 
```mat-form-field-outline-gap``` as inline style applied to it that matches the width of the label.  However in the Angular Element it is not getting this line style .... so it appears the line goes through the floated label.

I will do more research and see if i can figure out how this is set and why it does not in this case.

**Comment by tmburnell** [comment]
This merge: https://github.com/angular/components/pull/12782/commits/457847f79752d4df0acd36a89b38a54cc6663990
added this: 
```
    if (!document.documentElement.contains(this._elementRef.nativeElement)) {
      this._outlineGapCalculationNeeded = true;
      return;
    }
```
The issue is ... i had to turn ```encapsulation: ViewEncapsulation.ShadowDom``` on because Angular Elements would not apply style correctly without it.  But the function can not find the element in the DOM because it is in the Shadow Dom.  

Does a new function need to be created to see if an element is in the DOM or ShadowDom?  Or is there a better fix?

**Comment by tmburnell** [comment]
https://github.com/angular/components/issues/13837

**Comment by tmburnell** [comment]
Might be related to: https://github.com/angular/components/issues/13837

**Comment by tmburnell** [comment]
I changed to ``encapsulation: ViewEncapsulation.NONE`` and it seems to be more stable.  I just need to make sure all my custom css has component selectors on them.

**Comment by Splaktar** [comment]
Correct, as mentioned in https://github.com/angular/components/issues/13837, `ViewEncapsulation.ShadowDom` is not supported at this time. 

`ViewEncapsulation.NONE` and using Sass (SCSS) to make sure that your styles are scoped to components is recommended at this time.
