### ISSUE TITLE
--prod flag ommit styles

### ISSUE THREAD

**Issue by ParseThisCode** [angular/components#16179]
#### Bug, feature request, or proposal:
ng serve/build --prod ommit material styles

#### What is the expected behavior?
colors, etc

#### What is the current behavior?
prod app is white, unstyled with glitches

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 8

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction.

(this is a canned response)
