### ISSUE TITLE
First lazy loaded mat-tab content change detection not working

### ISSUE THREAD

**Issue by yasinallana** [angular/components#16186]
#### Reproduction
Cannot reproduce as stackblitz is using angular 7 and updates to its dependencies causes a 
"core-js" not found error

![Screen Shot 2019-06-03 at 2 16 44 PM](https://user-images.githubusercontent.com/12084947/58789470-d5b9da00-860b-11e9-969b-3b06fd15497b.png)

#### Problem
In the previous angular version (v7) the change detection in the first tab that is lazy loaded in mat-tab would properly work, however after the update to angular (v8) and enabling of ivy via "enableIvy" : true, the change detection doesn't work for the first lazy loaded tab. I have a spinner that is shown until data is fetched, this would work in angular (v7) but since angular (v8) it no longer hides due to change detection not working

#### Expected behaviour

Change detection should work for the first lazy loaded tab.

#### Actual Behavior

Change detection does not take effect until the tab is switched to another lazy loaded tab

#### Environment

```
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 12.2.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

Browsers: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by yasinallana** [comment]
A workaround for now is to switch from lazy loading to eagerly loading the first tab

**Comment by josephperrott** [comment]
Can you provide a reproduction either using [version 7](https://stackblitz.com/edit/angular-material2-issue-mo4yqz?file=app/app.component.ts) or [version 8 (without ivy)](https://stackblitz.com/edit/angular-material2-issue)

**Comment by yasinallana** [comment]
@josephperrott it works with version 7 and disabling of ivy, only upon enabling ivy does the problem occur

**Comment by jimmykane** [comment]
Same here. 

When I wrap this: 

```
 <ng-template matTabContent>

        <app-event-card-map
          [selectedActivities]="selectedActivities"
          [targetUserID]="targetUserID"
          [user]="currentUser"
          [event]="event"
          [showLaps]="showMapLaps"
          [lapTypes]="mapLapTypes"
          [showArrows]="showMapArrows"
          [strokeWidth]="mapStrokeWidth"
          [theme]="mapTheme">
        </app-event-card-map>
        </ng-template>
```
And add matTabContent attrib then the ngChange does not file for any of the parents elements changes on the eg map component. 

So for example `showMapArrows` changes  but `app-event-card-map` does not trigger anything. Looks like dead. 

@josephperrott

**Comment by jimmykane** [comment]
Hi @josephperrott  do you need more info on this? This is very easy to reproduce

**Comment by jerkovicl** [comment]
having the same issue as well components inside lazy loaded tab are not getting input changes

**Comment by rcaceiro** [comment]
I have the same issue!

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

We aren't able to reproduce this; feel free to open a new issue with a reproduction on the latest version.
