### ISSUE TITLE
matSubheader  has no effect in a mat-nav-list

### ISSUE THREAD

**Issue by jpike88** [angular/components#16183]
#### Reproduction

Steps to reproduce:
1. have a mat-nav-list
2. put a subheader item like this into it:

```<h3 matSubheader>Subheading</h3>```
 
 
#### Expected Behavior

Subheader row should not have ripple on click, and should have some sort of styling that indicates that it's not a link (like a grey background or something).

#### Actual Behavior

It has ripple, and looks like a button despite the matSubheader attribute.

#### Environment

Angular 8, macOS, safari/chrome

**Comment by josephperrott** [comment]
Can you provide a reproduction, as it appears to be working as expected in [this reproduction](https://stackblitz.com/edit/angular-xsosas?file=app/list-sections-example.html)

**Comment by jpike88** [comment]
I'm a dumbass
