### ISSUE TITLE
MatDialog - set focus on dialog itself

### ISSUE THREAD

**Issue by VVKot** [angular/components#16190]
#### Bug, feature request, or proposal:
I have MatDialog which is used for confirming deleting the element.  I want to place focus initially on the dialog itself.
Is there a proper way to do it? Meaning that "tab loop" would be like so:
1) Dialog -> No button  -> Yes button -> Dialog
or, ideally, after jumping to buttons focus will be trapped there:
2) Dialog -> No button  -> Yes button -> No button -> Yes button

#### What is the use-case or motivation for changing an existing behavior?
Because of our app not having "trash bin" functionality as of now, deleting is permanent. So, I don't want to place focus on the "Yes" button.

Alternatively, I can place focus on the "No" button. But this would interfere with a highlight on the "Yes" button - I want to highlight intended action in the dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "~7.1.0",
"@angular/material": "~7.1.0",

**Comment by jelbourn** [comment]
@crisbeto doesn't setting `autoFocus: false` do this now?

**Comment by crisbeto** [comment]
Yes, the only thing that `autoFocus` controls is [whether to move focus to the first focusable element](https://github.com/angular/components/blob/master/src/material/dialog/dialog-container.ts#L143). If it's turned off, focus should just stay on the dialog.

**Comment by jelbourn** [comment]
@crisbeto we should probably make that more clear in the JsDoc, but closing this issue since that's the solution.

**Comment by VVKot** [comment]
Thanks, @jelbourn @crisbeto, I figured out why `autoFocus` was not working for me. I am opening dialog from one of the options in MatMenu. When the menu closes, it sets focus on itself, away from a dialog. You can check the small demo here:
https://stackblitz.com/edit/angular-d3atgj
https://angular-d3atgj.stackblitz.io/

Should we reopen this issue? Or it is better to discuss in a separate one?

**Comment by jelbourn** [comment]
Yeah, that sounds like a separate bug
