### ISSUE TITLE
Angular Material Dialog stackblitz example doesn't work 

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#16194]
#### Documentation Feedback

[Stackblitz example](https://stackblitz.com/angular/kooxgxjajmag?file=app%2Fdialog-overview-example.ts) for [Angular Material Dialog](https://material.angular.io/components/dialog/overview) doesn't render

**Affected documentation page: ** https://material.angular.io/components/dialog/overview 
![image](https://user-images.githubusercontent.com/48334588/58832705-8381b480-861d-11e9-96bb-65696cd43e51.png)

**Comment by wakang27** [comment]
You should use 
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material';
instead of
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material/dialog';

**Comment by HoushCE29** [comment]
Seems to be fixed, has the correct `material-module.ts` file now.

**Comment by dota2Pro** [comment]
> Seems to be fixed, has the correct `material-module.ts` file now.

What is the link you are using ?

**Comment by HoushCE29** [comment]
It _was_ working yesterday (with the update material module pointing at the correct imports) as I was toying around with it for a couple hours for a defect that my company has with it... now it's broken again, worse this time.

It's just displaying `{"error":"UNSATISFIED_RANGE","data":{"name":"@angular/cdk","range":"8.0.1"}}` in plain text now, without the editor.

It'd be nice to be able to use that again..

**Comment by HoushCE29** [comment]
Now it's working again for v8 as of now (https://stackblitz.com/angular/lpbqqoqxkxr?file=app%2Fdialog-overview-example.ts). Someone must've been editing it.

**Comment by mmalerba** [comment]
I believe this was temporarily broken due to https://github.com/angular/components/issues/16267 but should be working now
