### ISSUE TITLE
Material menu should not close on left arrow click

### ISSUE THREAD

**Issue by AbdulAziz2612** [angular/components#16192]
Hi Team,

### Current Behavior:
When open any menu and click left arrow key from keyboard then menu gets closed.

### Expected Behavior:
When we click left arrow key from keyboard then menu should get closed.

**Comment by jelbourn** [comment]
As far as I can tell everything is working as intended here.

**Comment by AbdulAziz2612** [comment]
Sorry I have put this wrong. I wanted a hook where if I press left arrow key of keyboard then menu should not get close.
