### ISSUE TITLE
When clicking on the check box at the edge, there is a case that it becomes a drag state.

### ISSUE THREAD

**Issue by wakang27** [angular/components#16207]
If you click the check box after select box selection or screen transition at the edge, it will be in the drag state.
Not only check boxes but also radio buttons and toggles.

#### Reproduction
1. After selecting the value in the select box by the edge, click the check box, it will be in the drag state.
https://stackblitz.com/edit/angular-selectcheckbox
2. After the screen transition at the edge, click the check box, it will be in the drag state.
https://stackblitz.com/edit/angular-material-router
 
#### Expected Behavior
When the check box is pressed, it does not become dragged.

#### Actual Behavior
When the check box is pressed, it does become dragged.

#### Environment
- Angular:7.2.13
- CDK/Material:7.3.7
- Browser(s):
  - [ ] Chrome (desktop)
  - [ ] Safari (ipad)
  - [X] Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mgiannelli** [comment]
I have the same issue in 

**Environment** 

* Angular: 9.2.1
* CDK/Material: 9.1.2
* Browser(s):
   **Only with Edge**
* Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment]
This is likely fixed in Chromium-based Edge - please re-open the issue if the problem still exists
