### ISSUE TITLE
ng update from 7.3.7 to 8.0 throws custom rule error

### ISSUE THREAD

**Issue by CRACKISH** [angular/components#16208]
#### Reproduction

When running `ng update @angular/material`, there are errors:

```Could not find custom rule directory: ./attribute-selectors/```

Angular was upgraded successful from 7.2.15 to 8.0.

My other simple project was upgraded successful (angular and material).

Error similar to [13913](https://github.com/angular/components/issues/13913)
 
 
#### Expected Behavior

Run migration without errors

#### Environment

- Angular: 8.0
- CDK/Material: 8.0
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows\macOS

**Comment by josephperrott** [comment]
@devversion Any chance you could take a look at this if @CRACKISH is able to provide additional information at your request?

**Comment by CRACKISH** [comment]
> @devversion Any chance you could take a look at this if @CRACKISH is able to provide additional information at your request?

I will provide any necessary information.

**Comment by kEpEx** [comment]
Trying to run material or cdk gives me this error

The command you asked in the closed thread seems to show the folder but there should be a issue with the path


ss/src on  feature/angular8 is 📦 v1.0.0 via ⬢ v12.4.0 
➜  ls ./node_modules/\@angular/cdk/schematics/ng-update/upgrade-rules
attribute-selectors             index.d.ts                      output-names                    signature-check
class-inheritance               index.js                        project-tsconfig-paths.d.ts     tslint-config.d.ts
class-names                     index.js.map                    project-tsconfig-paths.js       tslint-config.js
css-selectors                   input-names                     project-tsconfig-paths.js.map   tslint-config.js.map
element-selectors               misc-checks                     property-names

**Comment by fat23cat** [comment]
> @devversion Any chance you could take a look at this if @CRACKISH is able to provide additional information at your request?

I'm also getting `Could not find custom rule directory: ./attribute-selectors/` when running `ng update @angular/material`, I will provide any necessary information too if you need.

**Comment by wildgarden** [comment]
The problem stems from the `node-glob`-package. Both `@angular\material\schematics\ng-update\index.js` and `\@angular\cdk\schematics\ng-update\upgrade-rules\tslint-config.js`  call something like `glob_1.sync('./**/', { cwd: __dirname, absolute: true })` which is expected to return an absolute path. But is doesn't. At least on Windows 10. It seems node-glob had some issues with absolute paths in the past. But currently there is no open issue. 
As a workaround one could change `absolute` to the `realpath` option or add another option `root: __dirname` and adapt the glob-pattern accordingly.

**Comment by devversion** [comment]
Sorry about the slow response. I've been focused on migration work for Angular core and this didn't seem like a huge priority for now since version 8 of Angular Material has already been released.

Unless someone else is already putting in more investigation work, I'll try to take a look at it as soon as possible. Thanks!

**Comment by devversion** [comment]
@wildgarden I've submitted a PR that switches us away from `node-glob`, but I wasn't able to reproduce the windows issues on my machine. Can someone provide the version of `glob` in `node_modules`?

In any case it definitely looks like the path returned is not absolute according to the tslint failure message... so we should be good switching away from `node-glob`. Thanks!

**Comment by fat23cat** [comment]
> Can someone provide the version of glob in node_modules?

I've run `npm list glob` in project's directory:
```
+-- @angular-devkit/build-angular@0.800.4
| +-- copy-webpack-plugin@5.0.2
| | +-- cacache@11.3.3
| | | `-- glob@7.1.4
| | `-- globby@7.1.1
| |   `-- glob@7.1.4
| +-- glob@7.1.3
| +-- stylus@0.54.5
| | `-- glob@7.0.6
| `-- webpack-dev-server@3.3.1
|   `-- del@4.1.1
|     `-- globby@6.1.0
|       `-- glob@7.1.4
+-- @angular/cli@8.0.4
| +-- pacote@9.5.0
| | `-- glob@7.1.4
| `-- read-package-tree@5.2.2
|   `-- read-package-json@2.0.13
|     `-- glob@7.1.4
+-- @angular/compiler-cli@8.0.2
| +-- chokidar@2.1.6
| | `-- UNMET OPTIONAL DEPENDENCY fsevents@1.2.9
| |   `-- UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.12.0
| |     `-- UNMET OPTIONAL DEPENDENCY rimraf@2.6.3
| |       `-- UNMET OPTIONAL DEPENDENCY glob@7.1.3
| `-- shelljs@0.8.3
|   `-- glob@7.1.4
+-- karma@4.1.0
| +-- glob@7.1.4
| `-- rimraf@2.6.3
|   `-- glob@7.1.4
+-- karma-coverage-istanbul-reporter@2.0.1
| `-- istanbul-api@1.3.7
|   `-- fileset@2.0.3
|     `-- glob@7.1.4
+-- ng-packagr@5.3.0
| `-- glob@7.1.4
+-- npm-sass@2.2.1
| +-- glob@6.0.4
| `-- node-sass@4.12.0
|   +-- gaze@1.1.3
|   | `-- globule@1.2.1
|   |   `-- glob@7.1.4
|   +-- glob@7.1.4
|   +-- node-gyp@3.8.0
|   | `-- glob@7.1.4
|   +-- sass-graph@2.2.4
|   | `-- glob@7.1.4
|   `-- true-case-path@1.0.3
|     `-- glob@7.1.4
+-- protractor@5.4.0
| +-- glob@7.1.4
| +-- jasmine@2.8.0
| | `-- glob@7.1.4
| `-- webdriver-manager@12.1.5
|   +-- del@2.2.2
|   | `-- globby@5.0.0
|   |   `-- glob@7.1.4  deduped
|   `-- glob@7.1.4  deduped
`-- tslint@5.11.0
  `-- glob@7.1.4
```

**Comment by CRACKISH** [comment]
I updated successful. Can close issue. Thanks.

**Comment by devversion** [comment]
@CRACKISH Thanks for verifying that it's fixed! 💯 Also we just reworked our `ng update` implementation to no longer use TSLint.

Thanks all for actively providing information on this issue! 🥇
