### ISSUE TITLE
Adding support for rendering template into the tooltip component

### ISSUE THREAD

**Issue by TKul6** [angular/components#16216]
#### Feature Description

I'd like to provide a `ng-template` to the tooltip component to render complex / hierarchical data into the tooltip.

#### Use Case
There are some cases I'd like to add a custom icon along with the tooltip text. for example:
 - When I display an hierarchy of components.
 - Sometimes I need to redder the user's avatar into the tooltip along with his username.
 - Sometimes I need to render a list to the tooltip ( a short list), and so I need to use `<ul>` and `<li>` inside the tooltip.

Thanks a lot

**Comment by crisbeto** [comment]
If I remember correctly, there was something in the spec that says that only text should be shown in the tooltip. Furthermore, I don't think our current accessibility setup will work when passing in the content as a template.

**Comment by djleonskennedy** [comment]
@TKul6 you can implement it by using `cdk overlay` easily

**Comment by TKul6** [comment]
Thanks, I guess I can implement it over the `cdk overlay` I just think it's a common use case many developers might use once it's available.

**Comment by andrewseguin** [comment]
Showing a custom popover template is wanted, but very difficult to implement with good accessibility. For that reason, we do not have plans to add custom templates to our tooltips
