### ISSUE TITLE
Mat Menu overlaps toolbar when scrolled

### ISSUE THREAD

**Issue by surajpoddar16** [angular/components#16214]
I have a custom menu implementation that uses flexible connected position strategy. It listens to positionChanges and closes the menu if isOverlayClipped is true. I want the menu to have flexible dimensions relative to the nearest scrollable ancestor otherwise, the menu will grow relative to viewport and start overlapping other parts of the page.

#### Reproduction

Steps to reproduce:
1. In http://material.angular.io goto docs for menu component
2. Scroll down with an example menu opened
 
 
#### Expected Behavior

Overlay with flexible connected position strategy should calculate flexible dimensions relative to the nearest scrollable parent so that it can fit correctly inside the parent.

#### Actual Behavior

Menu overlaps the toolbar. With flexible connected position strategy the flexible dimensions are calculated relative to the viewport, and thus for a very long menu isOverlayClipped is always fired.

**Comment by jelbourn** [comment]
@surajpoddar16 I don't quite follow. You said you have a custom menu implementation, but also that it's reproducible on material.angular.io?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
