### ISSUE TITLE
drag-drop: Drag delay does not allow scrolling on mobile devices

### ISSUE THREAD

**Issue by Aboisier** [angular/components#16224]
#### Reproduction

StackBlitz: https://angular-wls93x.stackblitz.io

Steps to reproduce:
1. Create a draggable element with a start delay (cdkDragStartDelay) of 1 second
2. Try scrolling by pressing on the draggable element as the start point and dragging immediately
 

#### Expected Behavior

Since the drag start delay was not elapsed when the scroll intention, I was expecting 
1. The drag to be cancelled
2. To be able to scroll

#### Actual Behavior

1. I was not able to scroll
2. The drag element was teleported to my finger after the delay was elapsed (one second)

#### Environment

- Angular:  8.0.1
- CDK/Material: 8.0.0
- Browser(s): Chrome (74.0.3729.169)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Aboisier** [comment]
So it seems like there is still an issue with this. The native drag interactions are not toggled when the drag sequence is ended, which makes scrolling impossible after the item has been dragged once. Also, it does not work at all on iOS. I made another PR to fix this.

**Comment by tommyc38** [comment]
Sorry guys, I tried for a while to get the my container to scroll while moving an item across an X axis but couldn't.  I tried the dray-start-delay and it didn't help.  On my iPhone Chrome/Safari browser it completely disabled scrolling (even with the delay) all together.  Can you please provide a working example?  Perhaps your docs (or me) are missing something important.  Thanks!
