### ISSUE TITLE
Using Virtual Scrolling on Flat Tree Component

### ISSUE THREAD

**Issue by izyte** [angular/components#16225]
Hi,

I have been looking for implementation of Virtual Scrolling on Material Tree (flat tree version) all over the internet but I could not find one. The tree component I use for my project tend to display lots of nodes (could probably reach 2000+ nodes), especially when the "Expand All" feature is invoked and the application of Virtual Scrolling can significantly improve the rendering time in the DOM.

I suggest a detailed example of the implementation of Virtual Scroll on Material Tree be included in Angular Material documentation.

Thank you very much,.

**Comment by jelbourn** [comment]
Duplicate of #10122
