### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by zzj0402** [angular/components#16237]
#### Documentation Feedback

A glossary like https://angular.io/guide/glossary but for material design.

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/ should have a side nav
then a page of glossary.

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

I don't think we'll add something like this; I think that each component's name is mostly self-explanatory.
