### ISSUE TITLE
Sidenav startup animation when using two sidenavs and router

### ISSUE THREAD

**Issue by Harpush** [angular/components#16236]
#### Reproduction

this is the stackblitz - https://stackblitz.com/edit/angular-material-sidenav-issue

In order to see the working as expected example jump between about and home - the sidenav is opened with no animation to the sidenav and no animation to the content.

Steps to reproduce the problem:
1. click toggle sidenav - the main sidenav will open with animation
2. go to about - the inner sidenav will appear without animation to the sidenav itself but the content will animate (you can see it through the scroll bar).
 
#### Expected Behavior

The same as the working example - even when the main sidenav is opened the inner sidenav should render opened with no animation for the content.

#### Actual Behavior

The sidenav content didn't animate as expected - it animated although it shouldn't have.

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome 74
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Harpush** [comment]
The problem might still happen even without router in between... I think a sidenav inside another in different components cause the issue too

**Comment by depyronick** [comment]
+1

**Comment by depyronick** [comment]
I don't know if its going to have some side effects, but this can be used as a workaround for now.

```
.mat-drawer-transition .mat-drawer-content {
	transition-duration: 0s !important;
	transition-timing-function: unset !important;
	transition-property: unset !important;
 }
```

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

@Harpush I don't really really follow what your intended behavior is here. Looking at the StackBlitz, everything is working how I would expect it to. Feel free to open a new issue that outlines how you expect this to work if you're still having an issue.
