### ISSUE TITLE
Cannot use *ngIf on Datepicker. <mat-datepicker *ngIf="true"> does not open.

### ISSUE THREAD

**Issue by MartinJaskulla** [angular/components#16239]
#### Reproduction

https://stackblitz.com/edit/angular-drdwxq-th8kkk

Steps to reproduce:

1. Add `*ngIf` to datepicker: `<mat-datepicker *ngIf="true" #picker>`
 
#### Expected Behavior

If the condition is true, the datepicker should open like normal

#### Actual Behavior

The datepicker stops working and cannot be opened

#### Environment

- Angular:
- CDK/Material:
- Browser(s): Chrome
- Operating System: Windows

#### Reason

- I need to create a generalized input component that can be used to render all possible inputs like this:
```html
<app-input type="datepicker">
<app-input type="creditCard">
<app-input type="lotsOfOtherCustomTypes">
```

- I want to hide `<mat-datepicker #picker>` for all other inputs like my custom creditCard input conditionally.
- *ngIf works on `<mat-datepicker-toggle>` like it should
- This is how I would like to use it:
```html
<input
    matInput
    [formControl]="formControl"
    [errorStateMatcher]="matcher"
    [matDatepicker]="type === 'datepicker' ? myDatepicker : null"
  />
<mat-datepicker-toggle
    *ngIf="type === 'datepicker'"
    [for]="myDatepicker"
    matSuffix
></mat-datepicker-toggle>
<mat-datepicker
    *ngIf="type === 'datepicker'"
    #myDatepicker
></mat-datepicker>
```

**Comment by crisbeto** [comment]
It looks like this works by design. The template reference won't propagate outside of the `ngIf`. See https://github.com/angular/angular/issues/6179#issuecomment-233374700.
