### ISSUE TITLE
@angular/cdk/drag-drop wrong indexes on drag and drop with structural directives *ngIf

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/components#16265]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/cdk-drag-and-drop-z4fuke?file=app/drag-drop-example.ts

ToDo list has elements limited by `*ngIf="item.name"`.

 Steps to reproduce:

1. Drag and drop element after element elements removed by *ngIf (Part of item name is incremented string to see missing elements) first element has nr83
2. Alert displays current and previous element index.

 
#### Expected Behavior

Correct indexes passed to transfer functions to manipulate element positions, containers (Same behaviour with cdkDragDropGroup between many lists)

#### Actual Behavior

if there is *ngIf implemented wrong indexes are passed. It is like removed elements with ngIf are not respected in count and hidden elements indexes are used.
There is 82 elements in array before first element displayed in cause of ngIf and first displayed on drag drop has index 0 which is not true it should be 82 it causes manipulation of elements in bacground that are limited by `*ngIf` and not displayed so We can't see anything 

#### Environment
[SAME BEHAVIOUR IN STACKBLITZ ON LOWER VERSIONS]
- Angular: in project 7.2.15 / in stackblitz 6.1.3
- CDK/Material: in project 7.3.7 / in stackblitz 6.4.5,
- Browser(s): Chrome 74.0.3729.169 (64bit)
- Operating System: Windows 10

**Comment by crisbeto** [comment]
The CDK calculates the index based on whatever is in the DOM. As far as the CDK is concerned the items that are removed with the `ngIf` don't exist.

**Comment by Adam-Michalski** [comment]
Ok, thanks. When I change `*ngIf' to style 

```
      height: 0;
      visibility: hidden;
      z-index: -1;
```

everything works as expected
