### ISSUE TITLE
Proposing new features to Datepicker

### ISSUE THREAD

**Issue by SandorSzilard** [angular/components#16263]
Header customization for Datepicker:
How about making the Datepicker more customizable, using simple methods, like modifying the css. I mean to change the datepicker design in an easy way. Or edit the header color/ layout more easyliy.

Adding Timepicker to Datepicker:
How about activating a functions when a user can add the time too after he selected the date. It would be very useful and it would be more comfortable to use only materials rather then combining with other components/libraries.

**Comment by mmalerba** [comment]
The date-picker has an option to customize the header with a custom component. There are currently no plans to add additional customization of the CSS, as the goal of this library is to follow the Material Design spec.

There is an open issue for a time picker here: https://github.com/angular/components/issues/5648

**Comment by SandorSzilard** [comment]
Yes, I had to use the custom component, but it is not so practical when you want to send aditional data to the header (like title from another component). It is a bit hard to use and if you make the header to big, the calendar body will "crash" (the css data is not meant to have a header and the elements will slip) => I had to make my custom material css, because the themes provided had a few things.
