### ISSUE TITLE
Datepicker custom header not working (example on stackblitz)

### ISSUE THREAD

**Issue by SandorSzilard** [angular/components#16261]
I tried to open the datepicker custom header example on stackblitz, but when I click the calendar icon, it displays a blank calendar (no dates, no header, only a white page). 

I try to make a material design calendar, but Angular Material Datepicker seems a bit to limited (it looks like the AngularJS version had more features, or the older versions). How about expanding the examples page? (for example: how to add buttons on the bottom of the calendar, how to make more complex header designs, how to add a "time picker" )

![image](https://user-images.githubusercontent.com/34717583/59248489-38722d80-8c2b-11e9-89e8-59971ba69bc8.png)

**Comment by mmalerba** [comment]
I believe this was broken due to https://github.com/angular/components/issues/16267 but should be fixed now
