### ISSUE TITLE
[Paginator] Allow for "appearance" attribute

### ISSUE THREAD

**Issue by adrogon** [angular/components#16266]
#### Feature Description

The `mat-form-field` components can currently be styled app wide with `MAT_FORM_FIELD_DEFAULT_OPTIONS`.

On a per case basis, you can also override that default, using the `appearance` attribute.

`mat-paginator` also holds a `mat-form-field`, but it is currently not possible to alter that field's appearance.

#### Use Case

For the same reason you might want to change a particular `mat-form-field`'s appearance, you might want to alter the appearance of the `mat-form-field` contained inside a `mat-paginator`.

To be fair, it is also because `mat-paginator` with a default `fill` appearance looks pretty broken now, and being able to set it to `standard` would be a good workaround to this issue.

**Comment by Suresh918** [comment]
@jelbourn / @mmalerba when will the discussion happen on this. Is there a way to be part of that discussion ?

**Comment by andreElrico** [comment]
Im suggesting to make a InjectionToken `MAT_PAGINATOR_DEFAULT_OPTIONS` where
`appearance` and `DEFAULT_PAGE_SIZE` can be provided.

**Comment by BobDankert** [comment]
Does anyone have any workarounds for this, while we wait for a solution? (Other than the obvious "don't use MAT_FORM_FIELD_DEFAULT_OPTIONS")

**Comment by MatthiasKunnen** [comment]
I would be willing to implement this if there is consensus on the approach. 

Proposals:
 - Add `MAT_PAGINATOR_DEFAULT_OPTIONS` injection token with `{formFieldAppearance: MatFormFieldAppearance}` as type (as suggested by  @andreElrico)
- Add `formFieldAppearance` as input on `mat-paginator`
