### ISSUE TITLE
Prevent multiple dialog overlays from blacking out the background

### ISSUE THREAD

**Issue by HoushCE29** [angular/components#16278]
#### Feature Description
Prevent dark background when multiple dialogs are open.

If you open multiple dialogs without closing them, the background progressively gets darker. While you can configure the backdrop class for when the dialog opens, you can't do much as the dialogs close.

Either add on some sort of `addBackdropClass()` function for `DialogRef`, or manage the overlay internally for all of the open dialogs (leaving only the top dialog with a visible overlay).

#### Use Case
Multiple dialog pop-ups 

(yes, although it's unlikely (and bad UX) that 10 dialogs would open, that doesn't mean that 2 or 3 can't open up. The user should still be able to see what's in the background without it getting darker.)

**Comment by crisbeto** [comment]
This might be possible already using CSS sibling selectors since all the backdrops are siblings of each other. The problem with doing is that what if the dialogs aren't right on top of each other? There won't be a way to tell which dialog is behind which.

**Comment by HoushCE29** [comment]
Yea that's true, I hadn't considered the side-by-side case. I'll close this, I did find and have been using a CSS workaround where I make the overlay invisible that comes with the dialog, but just control my own tinted overlay underneath the most recently opened dialog, and close it with the dialog as well.
