### ISSUE TITLE
moveItemInArray event returning wrong current index 

### ISSUE THREAD

**Issue by ankitg1602** [angular/components#16285]
#### Bug, feature request, or proposal:
In drop div, I have too many long text button in the 2-3 line. If I want to move long text button from 2nd line to 1st line. I am getting the wrong index.
![image (1)](https://user-images.githubusercontent.com/5072167/59407177-1369f000-8dce-11e9-9449-f2b258cb553f.png)

In the above snapshot, in 2nd line 2nd element want to move in the first line in 3rd position but getting index 4.

Please suggest me how to overcome this problem

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

**Comment by FritzHerbers** [comment]
@ankitg1602 
Can you please share a StackBlitz sample.

**Comment by crisbeto** [comment]
Needs more information before we can investigate.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
