### ISSUE TITLE
[Angular Material] Getting started NO Background color with purplr/green theme.

### ISSUE THREAD

**Issue by JoeCodeswell** [angular/components#16288]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.  Following [[Angular Material] Getting started](https://material.angular.io/guide/getting-started) 
2.  add @angular/material [Alternative 2: Angular Devkit 6+](https://material.angular.io/guide/getting-started#alternative-2-angular-devkit-6-)
3. `> ng serve -o`
 
#### Expected Behavior

What behavior were you expecting to see?
Angular App == Welcome to pitow-calendar!
STYLED with purple/green theme

#### Actual Behavior
What behavior did you actually see?
Welcome to pitow-calendar!
styled with white background

#### Environment

Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Comment by adrogon** [comment]
> Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

This link does not seem correct, can you please provide a link showing the issue?
