### ISSUE TITLE
.ng-animating not removed in mat-select in webkit

### ISSUE THREAD

**Issue by pburkindine** [angular/components#16295]
There is an issue in webkit browsers with the `mat-select`.  `.ng-animating` is never removed from the panel element.

#### Reproduction

https://github.com/pburkindine/webkit-ng-animating

In this repro, a `mat-select` and a `mat-autocomplete` are included for comparison, with `.ng-animating` set `display: none` to illustrate the issue

Steps to reproduce:
1. Run the app in Chrome and in Safari (issue also exists on all iOS mobile webkit-based browsers, iOS Chrome and Safari both display the problem)
2. Attempt to open mat-select and mat-autocomplete elements
3. Inspect the DOM and view the classlist on the `.mat-select-panel` element to see if `.ng-animating` is removed after animations complete
 
 
#### Expected Behavior

Both elements should appear to open even though `.ng-animating` is styled `display: none`

#### Actual Behavior

mat-select and mat-autocomplete will both open fine on Chrome, but only mat-autocomplete will appear to open in Safari

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.1
- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): 
OSX High Sierra, iOS

#### Screenshots

Chrome:
![SS 2019-06-14 at 9 37 44 AM](https://user-images.githubusercontent.com/20215564/59516995-2640fb00-8e88-11e9-92f1-456bff3813b6.png)

Safari:
![SS 2019-06-14 at 9 35 06 AM](https://user-images.githubusercontent.com/20215564/59517007-2e009f80-8e88-11e9-85ac-c376bba4a751.png)

**Comment by jelbourn** [comment]
I just tried this with Angular v9 in Safari. I added the CSS rule:
```scss
.ng-animating {
  outline: 10px solid pink;
}
```

The pink outline does correctly appear and disappear when the select opens and closes, so this may have been fixed in Angular v9.
