### ISSUE TITLE
There is no directive with "exportAs" set to "cdkDrag"

### ISSUE THREAD

**Issue by admir86** [angular/components#16294]
#### Reproduction

See stackblitz:
https://stackblitz.com/edit/angular-mhi8sg?file=app%2Fcdk-drag-drop-overview-example.html
 
 
#### Expected Behavior

As described in the [API docs](https://material.angular.io/cdk/drag-drop/api#CdkDrag) the directive should be exported as cdkDrag.

#### Actual Behavior

If I add the hashtag, to be able to reference the directive in my typescript class. Angular shows error:

```
Template parse errors:
There is no directive with "exportAs" set to "cdkDrag"
```

DragDropModule is imported!

#### Environment

- Angular: 8.0.1
- CDK/Material: 8.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Win10

**Comment by Airblader** [comment]
In your example you're not using the directive.

**Comment by crisbeto** [comment]
You have to set the `cdkDrag` attribute on your element.
