### ISSUE TITLE
Angular material is not or improperly applied after changing route

### ISSUE THREAD

**Issue by maarten-wachters** [angular/components#16298]
#### What are you trying to do?
Apply material styling to my table

#### What troubleshooting steps have you tried?
1. Been browsing SO for weeks trying to find a similar issue
2. Downgraded & upgraded my @angular/material package

What are you seeing that does not match your expectations? 
When rerouting, all applied material styling is not how one would expect when you reroute back to the table

Before routing

![Screenshot_2](https://user-images.githubusercontent.com/9095821/59527999-6d0d1000-8edd-11e9-9aff-ec2f09c62334.png)

After switching routes & coming back

![Screenshot_3](https://user-images.githubusercontent.com/9095821/59528033-86ae5780-8edd-11e9-90e8-e745bf7aaa73.png)

#### Reproduction

Rerouting to any component after opening the table page 

  
#### Environment

- Angular: 7.2.14
- CDK/Material: 7.3.7
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by andrewseguin** [comment]
Any chance you can reproduce this is Stackblitz so we can look into it? It seems odd that the CSS is loaded into the browser but not being applied to the table. Can you confirm that the styling is not being overridden by other styles?
