### ISSUE TITLE
docs(chips): provide docs and demo for using a label with outline appearance

### ISSUE THREAD

**Issue by KevinJue** [angular/components#16292]
## Bug, enhancement request, or proposal:
In mat-form-field with outline appearance you can insert a mat-chip-list inside the form-field but the label doesn't go above the input
it's look like a bug, because if we insert the mat-chip-list outside or if we change the appearance everything look good

![Capture d’écran 2019-06-13 à 11 20 54](https://user-images.githubusercontent.com/1983788/59420552-65f6dc80-8dcd-11e9-841c-6ddec7858ab6.png)

# CodePen and steps to reproduce the issue:
Stackblitz to see what i mean
https://stackblitz.com/edit/angular-dydyib

### What is the expected behavior?
The label should go above the input like that
![Capture d’écran 2019-06-13 à 11 28 29](https://user-images.githubusercontent.com/1983788/59421124-62178a00-8dce-11e9-80d0-a6689c33d0e9.png)

### What is the current behavior?
The label stay in the input

### Which versions of AngularJS, Material, OS, and browsers are affected?

- "@angular/material": "^6.3.2"

- OS: MacOS Mojave
- Browsers: Chrome Version 74.0.3729.169

**Comment by KevinJue** [comment]
Hello, 

@Splaktar don't know if is a bug actually, because it's work fine if the mat-label is outside the mat-chip-list.

this work
```JS
<mat-form-field>
    <mat-label></mat-label>
    <mat-chip-list>
        <mat-chip></mat-chip>
        <input>
    </mat-chip-list>
    <mat-autocomplete>
    </mat-autocomplete>
</mat-form-field>
```

but if we move the mat-label inside like that, the label don't have the correct render
```JS
<mat-form-field>
    
    <mat-chip-list>
        <mat-chip></mat-chip>
        <mat-label></mat-label>
        <input>
    </mat-chip-list>
    <mat-autocomplete>
    </mat-autocomplete>
</mat-form-field>
```

**Comment by Splaktar** [comment]
This is certainly a hole in our documentation. As you found, the `mat-label` needs to be in the `mat-form-field` and not within the `mat-chip-list`. Here's a working [StackBlitz](https://stackblitz.com/edit/angular-dydyib-lcftdt?file=app%2Fchips-autocomplete-example.html).

Thank you for pointing this out.

**Comment by mkonars** [comment]
#16578

**Comment by zarend** [comment]
Closing this because the [Chips Autocomplete example](https://material.angular.io/components/chips/overview#chips-autocomplete) in the Angular Material Docs uses a label inside the form field.
