### ISSUE TITLE
Mat Dialog animation while resizing

### ISSUE THREAD

**Issue by lashisu** [angular/components#16299]
#### Expected Behavior

The dialog should animate while resizing.

#### Actual Behavior
The dialog does not animate while resizing.

`this.dialogref.updatesize` I am usnig this.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
We don't have any plans to implement this as a feature.
