### ISSUE TITLE
Datatable sorting doesn't work with mixed datatypes wihtin a strings

### ISSUE THREAD

**Issue by Rockstaa** [angular/components#16303]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-an1uqc

Steps to reproduce:
1.  Click on the Column description to sort the values ascending
 
#### Expected Behavior

The table column should be sorted as follows:
Ascending:
1. Empty Strings
2. Strings
3. Numbers

#### Actual Behavior

When the table column description is sorted ascending there is no sorting recognizable

#### Environment

- Angular: 8.0.1
- CDK/Material: 8.0.1
- Browser(s): Firefox Quantum 67.0.2, Chrome 74
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment]
The default sort function in `MatTableDataSource` is string-based. You can provide a different `sortData` function for alternate behavior.

**Comment by Soeren86n** [comment]
String-based would be ok, but i didn't recognize any sorting. 
Here is a new example with some more Data -> https://stackblitz.com/edit/angular-an1uqc-mqsvv7

The Description Column ascending Sorting Result is
g 0 a d 1 2 c e f z 3

I would expect 
0 1 2 3 a c d e f g z

**Comment by jsCommander** [comment]
Hello, I had same problem with sorting array of string and numbers. To solve this problem i extend MatTableDataSource class and provide my own implementation of sortData function. 

```javascript
import { MatTableDataSource, MatSort } from "@angular/material";

export class CustomMatTableDataSource<T> extends MatTableDataSource<T> {
  constructor(initialData: T[] = []) {
    super(initialData);
  }

  sortData: (data: T[], sort: MatSort) => T[] = (
    data: T[],
    sort: MatSort
  ): T[] => {
    const active = sort.active;
    const direction = sort.direction;
    if (!active || direction === "") {
      return data;
    }

    return data.sort((a, b) => {
      const valueA = this.sortingDataAccessor(a, active);
      const valueB = this.sortingDataAccessor(b, active);

      let comparatorResult = 0;

      if (valueA != null && valueB != null) {
        if (typeof valueA === "number" && typeof valueB === "number") {
          comparatorResult = valueA - valueB;
        } else if (typeof valueA === "string" && typeof valueB === "string") {
          comparatorResult =
            valueA.toLowerCase() > valueB.toLowerCase() ? 1 : -1;
        } else {
          comparatorResult = typeof valueA === "string" ? 1 : -1;
        }
      } else if (valueA != null) {
        comparatorResult = 1;
      } else if (valueB != null) {
        comparatorResult = -1;
      }

      return comparatorResult * (direction === "asc" ? 1 : -1);
    });
  };
}
```
