### ISSUE TITLE
Default behaviour for inputmode="numeric"

### ISSUE THREAD

**Issue by DibyodyutiMondal** [angular/components#16300]
#### Feature Description

Inputmode="numeric" works as intended everywhere. Except that on a browser, if anyone tries to type text into a input with inputmode="numeric", that is allowed. On android, this is offset by the fact that the qwerty keyboard is not shown, only the numeric keyboard is shown.

I use the following directive right now, but I would like to have it included in angular as a 'default' behaviour

```
@Directive({
    selector: 'input[inputmode=numeric]'
})
export class StringNumberDirective {
    constructor(private el: ElementRef<HTMLInputElement>) {
    }
    get input(): HTMLInputElement {
        return this.el.nativeElement
    }

    @HostListener('input') onInput() {
        const re: RegExp = new RegExp('[^0-9]');
        this.input.value = this.input.value.replace(re, '');
    }
}
```

#### Use Case
Every data model that requires a number as a string, instead of a quantity. For example numeric roll numbers for an exam, or telephone number without dashes. 
Also, if you need to have a max-length (not max-value. Ex: string roll number number with max 10 digits) for the numerical string, that won't work with 'type=number', because html type=number does not support the max-length attribute. 
However, using this directive with max-length helps natively have a string number with a limited size

**Comment by Airblader** [comment]
> On android, this is offset by the fact that the qwerty keyboard is not shown, only the numeric keyboard is shown.

That's irrelevant, as text input is still not prevented that way (think pasting).

> I would like to have it included in angular as a 'default' behaviour

This repository is for Angular Material, not the framework. 

For the framework such a change is way too opinionated, and for Material IMHO this still seems like something I wouldn't include. 

The inputmode, as per specification, is a *hint*, not an enforced validation. If you want to validate data, you should do so using the appropriate mechanisms from the Forms API etc.

**Comment by DibyodyutiMondal** [comment]
You are right about it being opinionated. 
I am validating the data and it's all very fine, but it's just that, I want to enforce some properties of text input while some properties of number input, but they aren't compatible till I use this.
Also, I think I may have misunderstood the purpose of 'inputmode' earlier. Thank you for the insight. I'll leave it to you guys to include or close this feature as you see fit, then.

**Comment by Airblader** [comment]
> I'll leave it to you guys to include or close this feature as you see fit, then.

(Note that I am not part of the Angular team at all, I was just giving my 2c to this topic)

**Comment by crisbeto** [comment]
Closing since Angular Material aims to provide the styling and UX, we don't deal with the behavior of inputs.
