### ISSUE TITLE
Table: rowDefs added or removed from content projection are not recognized 

### ISSUE THREAD

**Issue by literalpie** [angular/components#16306]
#### Reproduction

[stackblitz](https://stackblitz.com/edit/cdk-table-changing-rows?file=src/app/app.component.ts)

Steps to reproduce:
1. comment out lines 36-40 in the app.component.ts file
2. click the "extra row on/off" button. No changes will be made
 
 
#### Expected Behavior

Changes to the content projected `matRowDef`s should be reflected in the table.

#### Actual Behavior

In order for the table to recognize changes to projected `matRowDef`s, I must call certain extra functions in the table (that were intended for other things) - `removeColumnDef` and `renderRows`.

#### Environment
- Angular: 7.2
- CDK/Material: 7.3
- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

#### Other Info
There is conversation around this in #13030, but I think this issue is different than the original purpose of that issue.

**Comment by jelbourn** [comment]
This is working as intended currently; the table only supports static row templates. If you want to switch between row templates, you can use the `when` predicate as part of `MatRowDef`
