### ISSUE TITLE
[mat-datepicker] show in the content

### ISSUE THREAD

**Issue by mohammadjalili** [angular/components#16313]
#### Feature Description

`mat-datepicker` show on top of the content you are currently viewing/interacting with.

#### Use Case

Is it possible to show in the content? Why is it in popup?

**Comment by Airblader** [comment]
> Why is it in popup?

Because the [Material Design specification](https://material.io/archive/guidelines/components/pickers.html#pickers-time-pickers) says so.

For reasons I don't know, the currently published specs no longer talk about pickers at all, the above is an archived version.

**Comment by mmalerba** [comment]
It is possible to use the `<mat-calendar>` separately from the `<mat-datepicker>` which might help you accomplish your goal. However it's currently not well documented and there might be some rough edges. (See https://github.com/angular/components/issues/8812)
