### ISSUE TITLE
(feature): CDK Drag and Drop keep style of element when dropping it into another container

### ISSUE THREAD

**Issue by duck74** [angular/components#16311]
#### Feature Description

When moving an item from one container into another, it takes over the style of the item in the new container. In some cases this is not desirable so an option where you can choose either to keep the original style or not would be nice.

#### Use Case

I made a stackblitz of a use case, where I have a timeline (kind of a gantt chart) where you move items from one row to another and want to keep the style of the element dragged.
https://stackblitz.com/edit/angular-opuyuk

**Comment by crisbeto** [comment]
I don't think there's a practical way to do this in the CDK. We only emit where the item should go, we don't actually move any elements around. It should be easier to handle on your end since you know which item was dropped in what it should be represented as.
