### ISSUE TITLE
adapter.setLocale does not seem to work

### ISSUE THREAD

**Issue by Zamiel** [angular/components#16318]
#### What are you trying to do?
Set the locale of a DatePicker.

#### What troubleshooting steps have you tried?
The adapter.setLocale (lang) does not seem to work.

#### Reproduction
https://stackblitz.com/edit/components-issue-9kivfa

#### Environment

- Angular: ~8.0.1
- CDK/Material: ~8.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by jelbourn** [comment]
You need to import `MatMomentDateAdter` _after_` MatDatepickerModule`
