### ISSUE TITLE
[MatPaginatorIntl]: Can't override the values of firstPageLabel nor lastPageLabel

### ISSUE THREAD

**Issue by clundberg1** [angular/components#16310]
#### Reproduction

Created a custom class which extends from MatPaginatorIntl:

import { MatPaginatorIntl } from '@angular/material/paginator';

```
export class CustomMatPaginatorIntl extends MatPaginatorIntl {
    firstPageLabel: 'Primera página';

    lastPageLabel: 'Última página';

    itemsPerPageLabel = 'Por página';

    nextPageLabel = 'Siguiente';

    previousPageLabel = 'Anterior';

    getRangeLabel = (page: number, pageSize: number, length: number) => {
        if (length == 0 || pageSize == 0) {
            return `0 de ${length}`;
        }
        length = Math.max(length, 0);
        const startIndex = page * pageSize;
        const endIndex =
            startIndex < length
                ? Math.min(startIndex + pageSize, length)
                : startIndex + pageSize;
        return `${startIndex + 1} - ${endIndex} de ${length}`;
    };
}
```
 
In the template enable the first and last buttons:

```
<mat-paginator
            [showFirstLastButtons]="true"
            ...
></mat-paginator>
```

The first and last button's tooltip is still displaying the default english text:

![image](https://user-images.githubusercontent.com/29963339/59639304-7a660c80-9120-11e9-8c28-f9ee4ac3723b.png)

Even injecting the instance of MatPaginatorIntl into a component and logging it shows this:

![image](https://user-images.githubusercontent.com/29963339/59639387-be591180-9120-11e9-8eee-2c960e403e27.png)

#### Expected Behavior

It should display the text specified in the CustomMatPaginatorIntl.

#### Actual Behavior

It displays the default english text.

#### Environment

Angular CLI: 8.0.1
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/cli                      8.0.1
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.0
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

**Comment by jelbourn** [comment]
Can you share a reproduction in StackBlitz?

**Comment by clundberg1** [comment]
@jelbourn 
Here you go: https://stackblitz.com/edit/angular-nfpe6j

**Comment by jelbourn** [comment]
I see; you accidentally used a colon instead of an equals sign in your custom `Intl`:
![image](https://user-images.githubusercontent.com/838736/59714658-00d52980-91c7-11e9-903d-a797163efdfa.png)
