### ISSUE TITLE
Bug - Dropdown panel won't close after extending mat-select

### ISSUE THREAD

**Issue by codler** [angular/components#16312]
#### Reproduction

https://stackblitz.com/edit/angular-vdyjcy?file=src%2Fapp%2Fapp.component.html

I want to extend mat-select like this

app.component.ts
```
<app-select>
  <mat-option>Value1</mat-option>
  <mat-option>Value2</mat-option>
  <mat-option>Value3</mat-option>
  <mat-option>Value4</mat-option>
</app-select>
```

select.component.ts
```
<mat-form-field>
  <mat-select>
    <mat-option>
      None
    </mat-option>
    <ng-content></ng-content>
  </mat-select>
</mat-form-field>
```

Steps to reproduce:
1. Click on the dropdown to open the panel.
2. Click on a value in the dropdown panel.
 
 
#### Expected Behavior

The dropdown panel should close after choosing a value

#### Actual Behavior

The dropdown panel is still open and nothing happens.

#### Environment

- Angular: 8.0.1, same bug in 7
- CDK/Material: 8.0.1/8.0.1, same bug in 7
- Browser(s): Chrome/Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
Extending the components isn't something we _actively_ support (though we don't do anything to prevent people from doing it).

**Comment by codler** [comment]
😮okey sad to hear, ill try here then https://stackoverflow.com/questions/56675020/how-can-i-extend-mat-select-component-in-material-angular-8
