### ISSUE TITLE
bug: Dialog is updating the table

### ISSUE THREAD

**Issue by indraraj26** [angular/components#16328]
#### Reproduction

Repo: https://github.com/indraraj26/todo-angular-material

Steps to reproduce:
1. https://indraraj26.github.io/todo-angular-material
2. Don't enter anything just hit submit
3. Go to user tab then edit ronny data from the table
4. Edit his name and detail
5. You will see it is updating instantly, instead it should update afterClosed()
 
#### Expected Behavior

What behavior were you expecting to see?
It should update after i closed the dialog

#### Actual Behavior

What behavior did you actually see?
It is updating instantly.

#### Environment

- Angular: 7.2.0
- CDK/Material: 7.3.7
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by macjohnny** [comment]
this is not a problem of angular material, but rather your object being referenced instead of creating a copy, so
https://github.com/indraraj26/todo-angular-material/blob/f7b377495109aa882bca9e08654676bfd9c1f357/src/app/user/add/add.component.ts#L20
needs to be changed to
```typescript
this.addUser = Object.assign({}, data);
```

**Comment by indraraj26** [comment]
i never thought that would take as a reference, As dialog component has it own scope.  
Thank you @macjohnny 

#closing
