### ISSUE TITLE
Drag and Drop resets components being moved

### ISSUE THREAD

**Issue by swirlsky** [angular/components#16326]
#### What are you seeing that does not match your expectations?

Components being drag-and-dropped lose their state.

#### Reproduction

[StackBlitz](https://stackblitz.com/edit/angular-ljpjhv)

Steps to reproduce:

There are six rectangles you can drag-and-drop between the two drop zones. One of them contains a component.

1. Click on the word foo (component property with value foo).
2. It has changed to bar (see source).
3. Grab the rectangle containing the component and move to somewhere else.
4. The component is reset, bar changes back to foo.

How to prevent CDK Drag and Drop from resetting components?

**Comment by andrewseguin** [comment]
When you drag an item from one list to another, it is only changing the data, not the DOM elements. When you move an item, you are effectively destroying the component in the DOM and re-creating it in another place.

In your case, if you want to maintain the state then you will need to store that somewhere outside of the subcomponent.
