### ISSUE TITLE
Drag and Drop Issue : seems Mouse is loosing control of the elements after few drags

### ISSUE THREAD

**Issue by NidhiBisaria** [angular/components#16332]
Steps to reproduce:
1. Drag an element and try to overlap it with other elements.

 Used StackBlitz to reproduce my issue: https://stackblitz.com/edit/angular-djnf6u
 
#### Expected Behavior

What behavior were you expecting to see?
On every overlapping it should move back to its last original position. 

#### Actual Behavior

What behavior did you actually see?
After first few overlaps it looses the mouse control.

#### Environment

- Angular: v8
- CDK/Material: CDK
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Should be covered by https://github.com/angular/components/issues/13372.
