### ISSUE TITLE
Implementing Angular-Gridster2 Drag feature : not able to see complete grid

### ISSUE THREAD

**Issue by NidhiBisaria** [angular/components#16333]
#### Reproduction

Steps to reproduce:
1. Used StackBlitz to reproduce my issue: https://stackblitz.com/edit/angular-it2vl4

 
 
#### Expected Behavior

What behavior were you expecting to see?

Want to see complete grid.
#### Actual Behavior

What behavior did you actually see?

Complete Grid is not showing 
#### Environment

- Angular: angular 8
- CDK/Material: Material
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Angular-Gridster2 isn't a part of this repository.
