### ISSUE TITLE
Material selection list hovering/clicking changing the component when disabled.

### ISSUE THREAD

**Issue by alexw10** [angular/components#16348]
#### Reproduction

https://angular-yqqk5c.stackblitz.io
 
 
#### Expected Behavior

What behavior were you expecting to see?
When hovering a disabled material option selection list it should not change color.
When clicking a disabled material option selection list it should not have a blue outline.

#### Actual Behavior

What behavior did you actually see?
When hovering it changes background color.
When clicking it has blue outline.

If this is on purpose for some reason let me know but it does not seem right.

**Comment by crisbeto** [comment]
Looks like this is fixed in master.
