### ISSUE TITLE
Bottom Sheet with TemplateRef

### ISSUE THREAD

**Issue by benneq** [angular/components#16340]
#### Feature Description

Bottom Sheet should be able to display a TemplateRef. Basically the same as with MatDialog.

#### Use Case

I want to build a "responsive" menu component, which displays a MatMenu on desktop and a MatBottomSheet on mobile.

**Comment by crisbeto** [comment]
This is supported already. You can pass in a `TemplateRef` into `MatBottomSheet.open`.

**Comment by benneq** [comment]
You're right. I overlooked the _"(+1 overload)"_ in VSCode.

Then maybe align the Type Definitions of Bottom Sheet and Dialog?

Dialog:
```
open<T, D = any, R = any>(componentOrTemplateRef: ComponentType<T> | TemplateRef<T>, config?: MatDialogConfig<D>): MatDialogRef<T, R>;
```

Bottom Sheet:
```
open<T, D = any, R = any>(component: ComponentType<T>, config?: MatBottomSheetConfig<D>): MatBottomSheetRef<T, R>;
open<T, D = any, R = any>(template: TemplateRef<T>, config?: MatBottomSheetConfig<D>): MatBottomSheetRef<T, R>;
```

**Comment by crisbeto** [comment]
There's been a PR for `MatDialog` for a while now, but it ended up breaking some people. https://github.com/angular/components/pull/11731
