### ISSUE TITLE
Support Two labels for slide toggle

### ISSUE THREAD

**Issue by yaseen-nadaf** [angular/components#16341]
#### Feature Description

Please support two labels for slide toggle, one on left side and one on right side of toggle button.

An attribute via which it will support two labels or single label on either side at a time.

#### Use Case

Currently if we click on slide toggle's label which is on right side, the button will work fine, but if we have label on it's left side and use "for" attribute along with "id" attribute to implement the same click as of right side label, then left label click won't toggle the button.

**Comment by Airblader** [comment]
It is actually possible to provide an external label like this:

```
<mat-slide-toggle #toggle="matSlideToggle"></mat-slide-toggle>

<label [attr.for]="toggle.inputId">I am an external label</label>
```

**Comment by jelbourn** [comment]
We have no plans to add a feature like this directly in the component.
