### ISSUE TITLE
Zoom on overlay mat-components

### ISSUE THREAD

**Issue by Hartaxfr** [angular/components#16342]
#### What are you trying to do?

I would like to use zoom css for accessibility. I use custom directive to do that.

#### What troubleshooting steps have you tried?

I use a custom directive to manage zoom on my application layout to bind my user zoom settings. But, mat-select/mat-dialog/mat-menu overlay is out of body element, so overlay don't get css zoom. I have to use [panelClass] input to override size with static css class.

I don't want to set panelClass attribute every time I need to use "mat-overlay-component". 

Maybe there is a better way to do that ?

Same issue with mat-dialog

#### Reproduction

https://stackblitz.com/edit/angular-material-example-4wem1y
  
#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): chrome 75.0
- Operating System: Windows

**Comment by jelbourn** [comment]
Do you want this to apply to _every_ overlay? If so, you could add custom CSS for `.cdk-overlay`
