### ISSUE TITLE
Angular Material Chips appearing as rectangle instead of being Rounded  inside a sidenav

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#16354]
#### Reproduction

https://stackblitz.com/edit/angular-i1v6xt?file=app/sidenav-responsive-example.html

Steps to reproduce:
1.  Go to above Stackblitz
2.  Open sidenav
 
 Stackover flow --> https://stackoverflow.com/q/56707626/5724889
#### Expected Behavior

Chip should be Round as it is everywhere

#### Actual Behavior

Chip is rectangular

#### Environment

- Angular: 8.0.1 
- CDK/Material: 8.0.1
- Browser(s): Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by dota2Pro** [comment]
It would be helpful if it is mentioned in  documentation that 
`<mat-chip>` should always be in a `<mat-chip-list>`

**Comment by Airblader** [comment]
@dota2Pro Also see https://github.com/angular/components/issues/9964
