### ISSUE TITLE
Use <abbr> element for datepicker headers

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16355]
The datepicker uses abbreviations for day-of-the-week headers. We should wrap these in an [`<abbr>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) with a title attribute that contains the full name of the day. 

(from #16317)

**Comment by jerome-nelson** [comment]
Can I take this?

**Comment by jelbourn** [comment]
Closing this since we tried using `<abbr>` and testing showed that it did not make any difference.
