### ISSUE TITLE
How to add dynamically generated component into entrycomponents [ ]

### ISSUE THREAD

**Issue by NidhiLive** [angular/components#16351]
I'm trying to create component dynamically which not existing on any modules. And am facing an error  which says mention the component in entrycomponents [ ].  How to add dynamically generated component into entrycomponents [ ]? Can anyone help me on this?

    protected _createComponentFactory(component:any, data:any){
    const compFactory = this.ComponentFactoryResolver.resolveComponentFactory(component);

    const compRef = compFactory.create(this.Injector);
    
    const compInstance: any = compRef.instance;
    
    compInstance.data = data;
    
    this.ApplicationRef.attachView(compRef.hostView);
    
    const compElement = (compRef.hostView as EmbeddedViewRef<any>).rootNodes[0] as HTMLElement;
    
    console.log(compElement);}

`

     protected _createNewComponent (tmpl:string, selector:string) {
      @Component({
          selector: selector,
          template: tmpl,
      })
      class CustomDynamicComponent  implements OnInit {
          @Input()  public data: any;
          ngOnInit(){}
      };
      
      return CustomDynamicComponent;
    }

`

`
`   

    let Component_template = '<h1>Sample Heading</h1>';
    let Component_selector = '.heading';
    this._createComponentFactory(
                                  this._createNewComponent(
                                                              Component_template, 
                                                              Component_selector
                                                          ),
                                '');
`

`

**Comment by Airblader** [comment]
You cannot create a component dynamically like that, there's no way for the AoT compiler to handle this.

Also, this is purely a framework question (this is the Angular Material repository) and since it's a support question, you should ask it on StackOverflow.

**Comment by NidhiLive** [comment]
Thanks for your valuable comment @Airblader .
I will ask the same on StackOverflow.
