### ISSUE TITLE
Material Dialog not able to emit event to parent when this.dialogRef.close() getting called from inside asynchronus block. 

### ISSUE THREAD

**Issue by alokkarma** [angular/components#16357]
I have asked a question on stackoverflow:
https://stackoverflow.com/questions/56672025/angular-material-modal-dialog-not-able-to-pass-event-to-parent 
can any one please help me on this. 
I have a component which has one child component. Child component has a button which will open a material dialog Box.
In dialog we have form, username and passwrod and submit button. When I submit i am calling backend REST api. 

this is getting called in child component: 

    dialogRef.afterClosed().subscribe(result => {
          console.log("result", result);
          this.onModalClosePassData.emit(result);//emit to parent
        });

which is sending event to parent. **updateComment()** is getting called and I can see the data in console.

But when I fill the form and click on submit. It calls submitForm method	which is asynchronus call and I am closing dialog after successful login.But then event is not emmiting. updateComment() is not getting called.

See the full code:

    parent component.html
    
    <ng-template #showTextOnly>
            <child-component [branch]="releaseBranch" [date]="dateString"
                      (onModalClosePassData)="updateComment($event)">
            </child-component>
    </ng-template>

    parent component.ts

    //This method is getting called when i click on backDrop, 
but If i logged in successfully this is not getting called
 `updateComment(event:any){
    		consile.log(event);
    }`
child-component.html

    <button class="btn btn-default" (click)="openDialog()">Login</button>
    
    child-component.ts

    export class ChildComponent implements OnInit {
    	@Output() onModalClosePassData = new EventEmitter();
    	constructor(public dialog: MatDialog) { }
    	openDialog(): void {
        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = false;
        dialogConfig.autoFocus = false;
        dialogConfig.hasBackdrop= true;
        dialogConfig.autoFocus=true;
        const dialogRef = this.dialog.open(LoginDialog, dialogConfig);
    
        dialogRef.afterClosed().subscribe(result => {
          console.log("result", result); //result is getting called in both cases
          this.onModalClosePassData.emit(result);
        });
     }
    }
    
    LoginDialog.component.ts

    import {MatDialogRef, MAT_DIALOG_DATA} from '@angular/material/dialog';
    export class LoginDialog implements OnInit{
    	constructor(private loginService: LoginService, public dialogRef: MatDialogRef<LoginDialog>,
          @Inject(MAT_DIALOG_DATA) public data: any) {}
    	  public submitForm = (formValue: any) => {
          if (this.noteForm.valid) {
            this.loginService.login(formValue)
             .subscribe((response:any)=>{
                 if(response.STATUS === "PASS")
                  this.dialogRef.close(response);
                 }
            })
          }
        }
    }
    LoginDialog.component.html

    <form [formGroup]="noteForm" autocomplete="off" novalidate (ngSubmit)="submitForm(noteForm.value)">
    .
    .
    </form>
### Expected
when I successfully login. child component should emit event and pass the response and should call the UpdateComment() method

**Comment by andrewseguin** [comment]
Please provide a link to StackBlitz so we can see what is happening. Otherwise it's a lot of work to get it set up the same way you implemented

**Comment by devversion** [comment]
Closing as no reproduction has been provided. Feel free to send a new issue w/ StackBlitz if you want us to have a look. Thanks!
