### ISSUE TITLE
Import Scrollmodule instead of deprecated ScrollDispatchModule

### ISSUE THREAD

**Issue by solkaz** [angular/components#16353]
#### Documentation Feedback

The Scrolling CDK documentation has the following snippet to use the scrolling module:

```ts
import {ScrollDispatchModule} from '@angular/cdk/scrolling';
```

However, it was deprecated, and `ScrollModule` should be imported instead.

![Screenshot 2019-06-21 09 48 49](https://user-images.githubusercontent.com/10211603/59931092-d9ba6a00-9409-11e9-8560-7d2963ffa511.png)

**Affected documentation page:** https://material.angular.io/cdk/scrolling/api

**Comment by crisbeto** [comment]
Seems like that part of the docs is auto-generated so something is picking it up incorrectly in the docs script. @devversion could it be because we've got two modules in the same and only the deprecated one has a doc string?
