### ISSUE TITLE
cdkDragFreeDragPosition 

### ISSUE THREAD

**Issue by abaradia1978** [angular/components#16364]
#### Feature Description

Provide a brief summary of the feature you would like to see.

cdkDragFreeDragPosition should accept x,y in relative units such as vw & vh

#### Use Case

Describe the use case(s) that the proposed feature would enable.

cdkDragFreeDragPosition allows to persist & restore drag position - however it takes only numeric values as px. This affects the responsive webpages and controls do not show up as expected because the transform:translate is set as px values. Currently, it has to be handled manually while loading pages to change the dragposition values based on screen width/height

**Comment by crisbeto** [comment]
This won't be practical because we use pixels for everything inside the CDK drag&drop. Adding more units probably won't be consistent with what the browser is doing and will add a ton more complexity.
