### ISSUE TITLE
Form field outline gap not calculated when the host element is in a shadow-root

### ISSUE THREAD

**Issue by ztan** [angular/components#16368]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-567ut9

Steps to reproduce:
1. Create a component with view encapsulation set to ShadowDom
2. Use a outline form field in the component's template
 
 
#### Expected Behavior

What behavior were you expecting to see?
Outline gap is calculated correctly based on the width of the label

#### Actual Behavior

What behavior did you actually see?
No outline gap.

#### Environment

- Angular: 6 ~ 8
- CDK/Material: 6 ~ 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by pigeonvictor** [comment]
Exact same problem for me with angular 8

**Comment by mmalerba** [comment]
This has been fixed, here's an updated version of the stackblitz https://stackblitz.com/edit/components-issue-3qa5cp?file=app/app.module.ts
