### ISSUE TITLE
mat-expansion-panel doesn't scroll to the header in safari IOS

### ISSUE THREAD

**Issue by PreethiSagana** [angular/components#16378]
mat-expansion-panel doesn't scroll to the header when the next and previous actions are performed from the mat-action-row in Safari IOS. It works perfectly fine in Chrome.

Is there a workaround to support safari browser. Thanks in advance

#### Reproduction
Here is the link to reproduce the issue https://angular-expansion-panel-safari-scroll-issue.stackblitz.io/

#### Steps to reproduce:
1. Open the link in safari browser
2. Click on next you'll see the panel scrolls to the middle of the next panel, this is not the case with chrome

#### Environment

- Angular: 8.0.0
- Browser(s): Safari - v12.1.1
- Operating System: macOS - v10.14.5

**Comment by mastermsd** [comment]
For me the same in all browsers.

**Environment**

- Angular: 10.2.1
- Browser(s): All
- Operating System: macOS - v10.15.7
-

**Comment by crisbeto** [comment]
This isn't something we even handle in the expansion panel since it wasn't built with forms in mind specifically. You should be able to implement a similar form using `mat-stepper` which is better suited for such use cases.
