### ISSUE TITLE
Edit single Cell without rendering the whole row

### ISSUE THREAD

**Issue by noririco** [angular/components#16377]
#### Feature Description

A way to update a single cell 

#### Use Case

I have a table with data that changes every sec.
most of the columns are not changing, but 1 column particular is changing frequently .

when I update the column, the whole row is rerendring.

**Comment by andrewseguin** [comment]
This issue is lacking a reproduction. I suspect you are updating the data directly, and the table has no way of knowing that the cells should be re-rendered. Instead, the data source data should change and emit to the table
