### ISSUE TITLE
mat-tab-group ignores parent width when inside fxLayout row

### ISSUE THREAD

**Issue by n0daft** [angular/components#16371]
#### Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-qube6g)

Steps to reproduce:
1. Add `mat-tab-group` inside div container having `fxFlexLayout="row"`
2. Add more `mat-tab` elements than the parent container width can display
 
 
#### Expected Behavior

The tab header should provide the usual left and right arrow indicating that there are more tabs than the current view shows (as it does if inside a fxLayout="column")

#### Actual Behavior

The tab-group grows in width and actually renders alls tabs even if there is no space. There are no arrows.

#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.1
- Browser(s): Chrome 75.0.3770.100
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by akshay-kale** [comment]
add import in styles.scss

@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';

**Comment by andrewseguin** [comment]
This seems to be an issue with the flex layout, not Angular Components. Perhaps its related to how the view is rendered after the flex layout determines some logic? You should open an issue there to see if they can identify the problem
