### ISSUE TITLE
MatSelect- "Open Down Always"

### ISSUE THREAD

**Issue by pburkindine** [angular/components#16383]
#### Feature Description

The logic in the select to figure out whether to open up or down is great, but if we don't want this behavior there's no easy way to get around it.  If we just want the autocomplete to open downward all the time, even if it goes off the screen, or upwards, there should be a way to indicate this.

`@Input positioning: FLEXIBLE | UP | DOWN`

Same concept as `matAutocompletePosition` for Autocomplete

#### Use Case

Client does not want flexible positioning, UI requires the overlay to open "like a drawer" downward at all times

**Comment by pburkindine** [comment]
More generally, it is causing us a lot of problems that the overlays for the select and autocomplete do not behave the same way.  We want both to behave the way the autocomplete does.

**Comment by crisbeto** [comment]
This should be possible now with the `disableOptionCentering` input.
