### ISSUE TITLE
Overlay positionStrategy ignores height and viewport settings

### ISSUE THREAD

**Issue by JarekToro** [angular/components#16385]
#### Reproduction

Stack Blitz
https://components-issue-g892zv.stackblitz.io/

Steps to reproduce:
1. Click on 'Click Here'
 
 
#### Expected Behavior

What behavior were you expecting to see?
The overlay should fit inside the specified height of the overlay with scrolling on overflow.

#### Actual Behavior

What behavior did you actually see?
The component in the overlay ignores the height and viewport settings

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Mac

Might be related to
 https://github.com/angular/components/issues/9715#issuecomment-442406887 
and
https://github.com/angular/components/issues/15946

**Comment by crisbeto** [comment]
You need to put a `max-height: 100%` on your element.
