### ISSUE TITLE
change mat-sidenav content dynamically from any component

### ISSUE THREAD

**Issue by mujahid-akbar** [angular/components#16392]
#### What are you trying to do?

I am trying to load different components in mat-sidenav from different routed components based on some action like button click?

#### What troubleshooting steps have you tried?

I have created a singleton service 'SidenavService' to get reference to mat-sidenav using @ViewChild,  this way I can control (like open, close, toggle etc.) sidenav from anywhere in the app.

I have also created a ng-container in mat-sidenav and stored its ViewConteinerRef in SidenavService, now in any component in component hierarchy, I can inject the SidenavService and I can use ViewConteinerRef  to created embedded view.

#### What are you seeing that does not match your expectations? 

Is there a better way to achieve this? loading different components in mat-sidenav from anywhere in the app.

#### Reproduction

stackblitz link
https://stackblitz.com/edit/angular-material-sidenav-dynamic-content

Steps to reproduce:
1. demoed in stackblitz
  
#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.1
- Browser(s): Chrome, any
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by mujahid-akbar** [comment]
Closing it as it is related to issue [#14324](https://github.com/angular/angular/issues/14324)

**Comment by svassr** [comment]
@mujahid-akbar did you end up changing your strategy ?
