### ISSUE TITLE
Chip autocomplete doesn't support showing error colour and message

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/components#16393]
#### Reproduction

https://stackblitz.com/edit/angular-n6tpca?file=app/chips-autocomplete-example.ts

Steps to reproduce:
1. select a fruit, and then remove it. The boolean display TRUE (invalid) all the time because we set the input formControl to null. The input is invalid, but the invalid class is not projected to the mat-form-field. 

 
 
#### Expected Behavior

When removing all chips, I expect to see a red border and red label, and the mat-error tag should display.

#### Actual Behavior

No error behaviour is displayed.
It could be that this is happening since the input tag is nested in the `mat-chip-list`, and can't find the parent element to apply the styles to.

Manually adding `ng-invalid && mat-form-field-invalid` via the ngClass directive does work.

#### Environment

- Angular: 8,0.2
- CDK/Material:8.01
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS Mojave

**Comment by LeanHer94** [comment]
the two solutions that I've just seen and that are supposed to work are awful solutions. 

In the first one you have to manage the chip state by yourself 
`@ViewChild('chipList') chipList;
  this.chipList.errorState = true;`

In the second one you have to set the directive formControlName to both chip list and input: 
`<mat-chip-list formControlName='newFruit'>
	<input formControlName='newFruit'>`

I haven't tested it yet (still researching about better solutions) but there're both supposed to work

**Comment by mattiLeBlanc** [comment]
Thanks, I will have a look at those solutions.

**Comment by jl91** [comment]
some news? i'm having same problem here in my component based on mat-chip-list

**Comment by y3rt** [comment]
Update? `<mat-error>` would be nice to use

**Comment by HoplaGeiss** [comment]
Any updates?

**Comment by mmalerba** [comment]
I think the `[formControl]` is just on the wrong element here, it should be on the chip list not the input https://stackblitz.com/edit/angular-n6tpca-yuxxza?file=app/chips-autocomplete-example.html
