### ISSUE TITLE
Striped tables.

### ISSUE THREAD

**Issue by jarrettj** [angular/components#16391]
#### Feature Description
Allow tables to display as striped.

Provide a brief summary of the feature you would like to see.
Have an option to display as striped, like mat-table-stripe.

#### Use Case
Makes reading the table much easier.

Describe the use case(s) that the proposed feature would enable.
Better viewing experience.

**Comment by Airblader** [comment]
Why not just add a class to each even or add row?

**Comment by jelbourn** [comment]
We don't plan to add this directly; instead you can add a normal class binding to the row based on whether the index is even/odd

**Comment by jarrettj** [comment]
Cool thanks for the reply guys. Will do it that way then. Regards.


________________________________
