### ISSUE TITLE
Getting error in month and year datepicker

### ISSUE THREAD

**Issue by smartHasmukh** [angular/components#16390]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-kumvgc

Steps to reproduce:
1. Open Stackblitz link then open inspect element
2. I have used `date = new FormControl()` instead of `date = new FormControl(moment())` because default date-picker value should be empty   
3. Getting error when selecting any year and month
 
#### Expected Behavior

1. Datepicker is an empty value
2. When select year and month of date-picker then it will be work

OR

There should be not getting any error while select year and month when first time selecting an empty date-picker value

#### Actual Behavior
 It's getting any while first time selecting year and month of empty date-picker value

What behavior did you actually see?
I have attached screenshots please check it

#### Environment
- Angular: 8.0.1
- CDK/Material: 8.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

![1](https://user-images.githubusercontent.com/8941195/60172920-50e96700-982b-11e9-8481-2fe2c00dfecd.png)

![2](https://user-images.githubusercontent.com/8941195/60172940-5e065600-982b-11e9-8d62-ae6c05285c35.png)

![3](https://user-images.githubusercontent.com/8941195/60172943-62cb0a00-982b-11e9-903e-aa24b61c2fa5.png)

**Comment by mmalerba** [comment]
This is not an Angular Material issue, your code is just not accounting for the fact that `ctrlValue` can be `null` (like it is initially)

**Comment by mmalerba** [comment]
Ah I just realized that maybe this code is a slightly modified version of the "Datepicker emulating a Year and month picker" from https://material.angular.io/components/datepicker/examples

While that code is just an example and intended as a starting point, not production ready code, I would be fine if someone wants to send a PR to change the example code so it can handle `null` dates
