### ISSUE TITLE
build fails of libary importing a library importing matRippleModule

### ISSUE THREAD

**Issue by remkoboschker** [angular/components#16398]
#### Reproduction

Create a standard angular cli library that imports MatRippleModule, build it, import the built library in another library and try to build that.
 
 
#### Expected Behavior

I expect the library to build

#### Actual Behavior

compiler throws 
```
Illegal state: Could not load the summary for directive Dir in [...]/node_modules/@angular/cdk/bidi/typings/index.d.ts.
```

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.1 and 7.3.7
- Browser(s): NA
- Operating System (e.g. Windows, macOS, Ubuntu): Windows / node 10.16

**Comment by jrandall1737** [comment]
I'm seeing the exact same issue (trying to consume a library that imports another library that imports MatRippleModule). 
Angular: 7.3.8
CDK: 7.3.7
Windows, node 10.11

**Comment by devversion** [comment]
Thanks for submitting that issue. I tried to reproduce this issue by creating a new CLI application. Running `ng g library test` and another one called `consumer`. The "test" library exports a module that imports `MatRippleModule` from `@angular/core`. The module from the "test" library is then imported as part of the "consumer" library.

Building the consumer library after the setup seems to work for me. Do I miss something? please try to provide a reproduction repository if I didn't do anything wrong :smile: Thanks!

**Comment by jrandall1737** [comment]
I can build my library successfully, I only see the error when I then try to consume the library in an app. So if you import then import your `test` library to an app, I believe you'll get the error. I also have aot enabled.

**Comment by remkoboschker** [comment]
Thank you for trying to reproduce. I will try to setup a repro first thing Monday.

**Comment by remkoboschker** [comment]
I did not manage to reproduce the issue exactly, but I did manage to get a, I think, related error. If you run `ng build tester` on this repo https://github.com/remkoboschker/repro-for-angular-components-issue-16398, you get the following error: 
```
BUILD ERROR
@angular\material\core\typings\index.ts(19,30): Error during template compile of 'MatRippleModule'
  Could not resolve @angular/cdk/platform relative to [object Object]..
@angular\material\core\typings\index.ts(32,13): Error during template compile of 'MatCommonModule'
  Could not resolve @angular/cdk/bidi relative to [object Object]..
@angular\material\core\typings\index.ts(33,13): Error during template compile of 'MatCommonModule'
  Could not resolve @angular/cdk/bidi relative to [object Object]..
@angular\material\core\typings\index.ts(23,13): Error during template compile of 'NativeDateModule'
  Could not resolve @angular/cdk/platform relative to [object Object]..
: Can't resolve all parameters for NativeDateAdapter in C:/Users/Remko/pgit/nx-repro/node_modules/@angular/material/core/typings/index.d.ts: ([object Object], ?).
: Can't resolve all parameters for MatRipple in C:/Users/Remko/pgit/nx-repro/node_modules/@angular/material/core/typings/index.d.ts: ([object Object], [object Object], ?, [object Object], [object Object]).
```
I have realised that the issue is probably specific to using ng-packagr.

**Comment by jrandall1737** [comment]
My issue was that I had a dependency in my library that was importing Angular components that must have been a different version of the components imported by my main app. 
Take a look in the `node_modules` in your Angular library output directory, and see if you're getting CDK that's the wrong version.
I removed the dependencies from my Angular library and I no longer have the issue.

**Comment by remkoboschker** [comment]
Thanks
