### ISSUE TITLE
The material.angular.io website tries to get an image that does not exist

### ISSUE THREAD

**Issue by eyeshield210** [angular/components#16408]
#### Documentation Feedback

Very good documentation, keep on

**Affected documentation page:** Insert a link to the affected page on material.angular.io

https://material.angular.io/components/button-toggle/overview

When you inspect the page you can see that a 404 error occured, the website tried to get that resource, which has been removed.

https://material.angular.io/android-chrome-144x144.png

**Comment by EdricChan03** [comment]
This has been reported in the angular/material.angular.io repository: angular/material.angular.io#599

**Comment by rsivan** [comment]
I have not been able to reproduce it.

**Comment by wagnermaciel** [comment]
This issue has been resolved by [PR #601](https://github.com/angular/material.angular.io/pull/601)
