### ISSUE TITLE
Display Two Values in Same Column

### ISSUE THREAD

**Issue by Harshanika** [angular/components#16403]
Any idea of how to add two rows in one column?

How to handle "matColumnDef" with this scenario?

![Browse_PO_Page](https://user-images.githubusercontent.com/15604113/60339181-afe2e380-99c5-11e9-857d-5dcfd771e1b6.png)

**Comment by andrewseguin** [comment]
You can apply a `rowspan` on the cell to stretch it across multiple rows. If you do this, you should `display: none` the following cells so they don't interfere with the spanned cell

**Comment by andrewseguin** [comment]
Here's a link of an example: https://stackblitz.com/edit/angular-rzfbsj?file=app/table-basic-example.html
