### ISSUE TITLE
Tabs selected index 

### ISSUE THREAD

**Issue by olegdunkan** [angular/components#16414]
#### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/angular-dj4jrm
2. click on tab with label "..."
3. add new tab
#### Expected Behavior

What behavior were you expecting to see?
I expected that active tab won't change. 

#### Actual Behavior

What behavior did you actually see?

The active tab are changed and getting with the label "...", but selectedIndex aren't changed.
We see inconsistent state - active tab with index that is not the same as selectedIndex.

**Comment by ssahu123** [comment]
Use two way binding for selectedIndex like this -
>  [(selectedIndex)]="selected.value"

**Comment by olegdunkan** [comment]
For clarity, I can solve these problem using only one an pair of open-closing tags `mat-tab` inside. 
```
tabs = ["A", "B", "..."]; //last element inside tabs will be boilerplate 

<mat-tab-group>
    <mat-tab *ngFor="let tab of tabs" label="{{tab}}"></mat-tab>
</mat-tab-group>
```
The best way is:
```
tabs = ["A", "B"]; //no artificial last element inside tabs 

<mat-tab-group>
    <mat-tab *ngFor="let tab of tabs" label="{{tab}}"></mat-tab>
    <mat-tab label="..."></mat-tab>
</mat-tab-group>
```
But in the second case we loose consistency between what user see at the screen (activated tab) and `selectedIndex` if we click on tab with label "..." and then dynamically add new tab inside code.

**Comment by jelbourn** [comment]
For now this is working as expected; we don't currently support treating a tab like a button that can support an arbitrary action. However, you can create your own tab label that stops event propagation and performs some custom action so that the tab component doesn't know a click ever happened in the first place.
