### ISSUE TITLE
possibility to use FreeDragPosition with cdkDragConstrainPosition

### ISSUE THREAD

**Issue by vincentbouillart** [angular/components#16425]
#### Feature Description

Is it possible to add the  free dragpostion  to the cdkDragConstrainPosition method.
Now the mouse pointer is given.

#### Use Case

I want to make it possible that the user only can drag the div per X pixels in a raster

**Comment by crisbeto** [comment]
Exposing just the free drag position won't be very useful when the item is inside a list. We could expose the `DragRef` which contains the free drag position, as well as bunch of other info. I've opened #16465 that adds it as a second parameter.
