### ISSUE TITLE
mat-select in the mat-card with flex layout, alignment of the options is outside of the card and way above the dropdown(not anywhere near to dropdown)

### ISSUE THREAD

**Issue by anilgiri2010a** [angular/components#16422]
#### Bug, feature request, or proposal:
mat-select options are displayed outside the mat-card and not anywhere near the mat-select.

Below is the screenshot. I have clicked on dropdown at 13 and menu option is displayed above the dropdown 9. ("Desig 1", "Desig 2", "Desig 3" and "Protocol Deviation" are the options in select list)
![image](https://user-images.githubusercontent.com/41872704/60512695-e89af980-9cf2-11e9-8252-48d2aaae3cd7.png)

NOTE: Make sure you have that select list near the bottom of screen. (Screen size should not be very large which will accommodate all the option without scroll)
1. Select first option 
2. then select the last option in the list
3. Then click on dropdown observe the issue 

#### What is the expected behavior?
Option list should rendered correctly (i.e. on/above/below the dropdown) after clicking select dropdown list.

#### What is the current behavior?
When mat-select option is selected for the first time. After selecting it for second time its render properly on the dropdown. 
Observe the element.style 
it has bottom: 278.1px; when rendered outside of the mat-card.
but, element.style has top: 426.3px; when rendered correctly on dropdown.

This happens only when dropdown is at the bottom of screen 
if its in the middle of the screen then everything works correctly.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
Below is the StackBlitz  URL
StackBlitz starter: https://stackblitz.com/edit/angular-c19hvo <br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "5.2.0"
"@angular/material": "5.2.5" 
"@angular/flex-layout": "2.0.0-beta.12"

#### Is there anything else we should know?
I know in angular 6 we have disableOptionCentering attribute which will stop that transition effect. But, we are not upgrading it right now. So need something similar to it and which will work on angular 5.

**Comment by crisbeto** [comment]
This is a very old version of Material and in general we don't backport bug fixes. I wasn't able to reproduce it against the latest version.

**Comment by vuongnguyen-agilityio** [comment]
I am using "@angular/material": "7.1.0"
I got this issue also.
:| God doesn't work today. Please give me a live :))
