### ISSUE TITLE
Input form example's source code doesn't work

### ISSUE THREAD

**Issue by TianrenWang** [angular/components#16427]
#### Reproduction

Steps to reproduce:
1. Download the source code from https://stackblitz.com/angular/maxldbagbxe?file=app%2Finput-overview-example.ts
2. npm install, ng build, and ng serve --open
3. Open browser to observe that the HTML cannot generate the same style as displayed in the original example
 
 
#### Expected Behavior

The page shows the same style as the original example on https://material.angular.io/components/input/overview

#### Actual Behavior

![image](https://user-images.githubusercontent.com/23157077/60546858-395b2400-9cec-11e9-97ae-da859b13fce9.png)

This is what you actually see.

#### Environment

- Angular: 8.0.3
- CDK/Material: 8.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by jelbourn** [comment]
Looks like your app is missing a theme. See https://material.angular.io/guide/theming
