### ISSUE TITLE
Rewrite Getting Started Guide

### ISSUE THREAD

**Issue by Splaktar** [angular/components#16426]
#### Documentation Feedback
I think that we should do more in our docs to highlight the happy path that is `ng add @angular/material` and the prompts / options we offer. Currently, we mention it only as a sub-bullet alternative (https://material.angular.io/guide/getting-started#alternative-2-angular-devkit-6-) and then continue on with telling the developer how to manually configure everything.

We cover `ng add` a bit better in https://material.angular.io/guide/schematics#install-schematics, but a new user is going to look at the “Getting Started Guide” first.

This was also reported in https://github.com/angular/components/issues/14380.

How would we want to solve this?
- [ ] Linking from Getting Started to the Schematics Guide?
- [x] Or totally re-writing the Getting Started Guide to highlight `ng add` and move the manual config to alternative steps at the end?

**Affected documentation page:** https://material.angular.io/guide/getting-started

Jeremy mentioned that @manughub has already started working on this but that there was no issue to track it.

**Comment by manughub** [comment]
On it. Expect to have a PR out this week.

**Comment by IgorMinar** [comment]
I just came to open an issue for this, I'm glad to see that one already exists. We should totally put focus on `ng add` and highlight all of the `ng generate` schematics available and documented at https://material.angular.io/guide/schematics

**Comment by manughub** [comment]
Update:
I've rewritten the getting started guide and reviewed with @jelbourn. Working on the PR and expect to have it out for review this week.

**Comment by Splaktar** [comment]
It seems like a separate "Getting Started with the CDK" guide would be useful as well. Should I open a separate issue for that? We have a number of projects that use the CDK that we could link to in addition to some useful videos for getting started.

**Comment by manughub** [comment]
Yes that's fine.

I have the PR ready to go for getting started with Material and it will be
out for review shortly.

-Manu
