### ISSUE TITLE
[MatTree]: Tree with nested nodes example used display: none instead of ngIf for matTreeNodeOutlet

### ISSUE THREAD

**Issue by WalterSheng** [angular/components#16421]
#### The tree is rendered much faster if use `*ngIf` instead of display: none when tree data is large, is there a reason that we use display: none?

    <ul [class.example-tree-invisible]="!nestedTreeControl.isExpanded(node)">
      <ng-container matTreeNodeOutlet></ng-container>
    </ul>

    .example-tree-invisible {
      display: none;
    }

**Comment by jelbourn** [comment]
I don't think there's a reason, that example just happened to use `display: none`.
