### ISSUE TITLE
isHandset$ should be a shared observable

### ISSUE THREAD

**Issue by arturhun** [angular/components#16434]
`ng add @angular/materia:material-nav` creates `isHandset$` observable which is used in multiple places in the corresponding HTML template. In this case I would suggest adding `share()` operator to the pipe to prevent multiple unnecessary subscriptions.

```
    "@angular/common": "~7.2.0",
    "@angular/cdk": "~7.3.7",
    "@angular/material": "7.3.7",
    "@angular/cli": "~7.3.8",
```

**Comment by jerome-nelson** [comment]
Hey @arturhun 

To clarify you mean the `ng generate @angular/material:material-nav` command yes? Added a small PR ..if this gets picked up it will be placed in version 8.0+ of components so you will have to update to angular 8 to get the changes.

**Comment by arturhun** [comment]
Hi @jerome-nelson 
yes, correct this is the schematics I have used. Now I noticed my typo. Sorry. And thanks for the PR!
