### ISSUE TITLE
bug: cdk-virtual-scroll-viewport inside trackByFn public variables are undefined.

### ISSUE THREAD

**Issue by ctfrancia** [angular/components#16439]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
[stack blitz example](https://stackblitz.com/edit/components-issue-casdct?file=app%2Fapp.component.ts)
Steps to reproduce:
1.  loop over array
2. inside trackByFn change value of public variable
 
 
#### Expected Behavior

What behavior were you expecting to see?
To see the public variable be updated. consistently 

#### Actual Behavior

What behavior did you actually see?
public variable cannot be updated as it is undefined unless the trackByFn is an Arrow function. Following changing to an Arrow function values of the public variable will change.

this is fixed when changing the `trackByFn` to an arrow function
```typescript
  public trackByFn = (index: number, item: string[]): number => {
    this.header = item[0];
    return index;
  }
```

however, there is a further error changing the value of `this.header` based on a condition
then the values of `this.header` will change
```typescript
  public trackByFn = (index: number, item: string[]): number => {
    if (index % 2  === 0) {
      this.header = 'even'
    } else {
      this.header = 'odd'
    }
    this.header = item[0];
    return index;
  }
```
#### Environment

- Angular: 7.2.1
- CDK/Material: 7.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOs

**Comment by jelbourn** [comment]
This is working as expected and is the nature of JavaScript. When you take a function off of an object, the `this` context is lost, e.g.
```ts
const someFn = myObject.someFn;

someFn(); // When invoking this function, there is no `this` context
```

When you bind a property in Angular (such as `trackBy`), you're just assigning the value to that property, same as above.

**Comment by ctfrancia** [comment]
Does that also explain why the value of `this.header` changes when scrolling?
