### ISSUE TITLE
mat-input user-select mark text not working with google fonts on touchscreen

### ISSUE THREAD

**Issue by anified** [angular/components#16432]
Hi guys

mat-input user-select to mark text do not work with google fonts on touchscreen.
Using Open Sans does not work:
`$custom-typography: mat-typography-config( 
  $font-family: 'Open Sans'
); `
![Error](https://user-images.githubusercontent.com/22592394/60558853-3c522500-9d7d-11e9-81aa-3d96ad94da49.PNG)

However, Arial does work:
`$custom-typography: mat-typography-config( 
  $font-family: 'Arial'
); `
![Correct](https://user-images.githubusercontent.com/22592394/60558838-31979000-9d7d-11e9-9627-847f7a5a4159.png)

Last tested with other Google fonts, seems that Roboto and Lato works. Those fonts with spacing do not work. Also, Poppins, which is a single word, does not work too. Thus, I do not know what is causing this bug.
  
#### Environment

- Angular: 7.3.9
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

@anified it's not super clear what you mean by "does not work" here. Closing this for now, feel free to open a fresh issue with further details.
