### ISSUE TITLE
MatPaginator server paging does not work with v8

### ISSUE THREAD

**Issue by Petitt88** [angular/components#16442]
#### Reproduction

Steps to reproduce:
1. Create a mat-table 
2. Use a pageSize smaller than the total amount of items: for example 5
3. Set MatPaginator's length to the total count: 10
 
 
#### Expected Behavior

What behavior were you expecting to see?

Paging works as it does in v7.

#### Actual Behavior

What behavior did you actually see?

MatPaginator show that there is only 1 page and paging is disable, meanwhile there should be 2 pages because of: that MatTableDataSource.data holds 5 items and matPaginator.length is set to 10.

#### Environment

- Angular: v8.0.2
- CDK/Material: v8.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Petitt88** [comment]
Okay, found the issue:

I assigned the paginator to the mat-table and that was a mistake. If I do not do it, it works. Sorry for the noise.

**Comment by manavalan** [comment]
Mat-table available with this feature ?

https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html

Pagination not getting updated based one scrolling

Demo
https://stackblitz.com/edit/angular-mat-table-infinite-scroll-with-sort?file=src%2Fapp%2Fapp.component.ts
