### ISSUE TITLE
Add backgroundColor to progress-spinner

### ISSUE THREAD

**Issue by lukasmatta** [angular/components#16450]
#### Feature Description

Feature that would allow setting progress-spinner's background color. 

#### Use Case

When using a progress-spinner for example as an indicator of stepper, it would look definitely better with colored background.

See spinner [without background](http://prntscr.com/oair3q) vs. [with background](http://prntscr.com/oaiqfz).

**Comment by HelenRankin** [comment]
A few considerations on this:

- The spinner background should be transparent by default, to keep appearance the same between versions
- It would be good to offer three choices for background: transparent (default), greyscale, color. Greyscale will be as you proposed and color will use a translucent version of the spinner color (see https://material.angular.io/components/progress-bar/examples for how this looks)
 - Need to decide on how the color will be set via the api, as there isn't a precedent for background options
 - I'm not a Material expert, but this doesn't seem to fit with the rest of Angular Material - I can't see any components that let you customise backgrounds like this

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because the Material Design specification doesn't explicitly allow background colors on spinners.

**Comment by mgameover** [comment]
Hi everyone, 
Hi @crisbeto,
I still can see a value of adding that "invisible, circular track". It is quite confusing when the process is stuck (lets say at 0-10%):
![image](https://user-images.githubusercontent.com/62712576/177851789-4abb0497-dbcf-44ed-be3e-59032871c44b.png)

Implementation wise, there is no much effort - just to add another circle. 
Our team had to implement a directive for that. It injects another circle with the same radius and strokeWidth then checks for it's changes on ngDoCheck:
![image](https://user-images.githubusercontent.com/62712576/177852716-89d0dbea-2cc9-407c-8a4d-0828d588eba8.png)

It would be great to have this feature out of the box.
