### ISSUE TITLE
how to disable weekend and how to start from monday in angular 7

### ISSUE THREAD

**Issue by shafqatsiddiqui** [angular/components#16458]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. https://stackblitz.com/angular/gxqrbdmbkkj
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?
I want to disable weekend and should start form monday

#### Actual Behavior

What behavior did you actually see?
bydefault it is starting from sunday

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 
Angular 7 
<input matInput [min]="minDate" [matDatepicker]="picker"
            placeholder="{{'checkout.summary.placeholder' | translate}}" [(ngModel)]="data['returnDate']">
        <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
        <mat-datepicker #picker></mat-datepicker>

**Comment by manklu** [comment]
> I want to disable weekend

Have a look at the datepicker examples
https://v7.material.angular.io/components/datepicker/examples
"Datepicker with filter validation"

> and should start form monday

The start day is determined by the locale.

**Comment by Flashunt** [comment]
https://stackblitz.com/edit/angular-dateadapter-example-stackoverflow1-oarzsz?file=app/datepicker-overview-example.ts
You can simply add a CustomDateAdapter, and which one return the getFirstDayOfWeek(), and you can user a filter method which one can disable the weekend days.

**Comment by shafqatsiddiqui** [comment]
Thanks @Flashunt  @manklu  its works
