### ISSUE TITLE
[mat-menu] panelClass input doesn`t work

### ISSUE THREAD

**Issue by Flashunt** [angular/components#16454]
#### Reproduction
https://stackblitz.com/edit/angular-kzveua?file=app/menu-overview-example.html
 
#### Expected Behavior

Applied class on menu panel.

#### Actual Behavior

The panelClass directive doesn`t work. Or how to add a custom class to the panel ?

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.2 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): WIN 10

**Comment by crisbeto** [comment]
The input is called `class`, not `panelClass`. You can use it like this `<mat-menu class="my-custom-class">`.
