### ISSUE TITLE
Regression: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by acalvo** [angular/components#16459]
#### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/edit/components-issue-9tex6j
 
 
#### Expected Behavior

Not to show any errors in the console. That was what happened with @angular/cdk 8.0.1 ( see https://stackblitz.com/edit/components-issue-y7g1rb )

#### Actual Behavior

The following error is shown:
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '@transform: void'. Current value: '@transform: open'.
```

#### Environment

- Angular: >= 8.0.0
- CDK/Material: 8.0.2 (not happening in 8.0.1)
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by tomicarsk6** [comment]
I added to your example rxjs pipe delay(0). [Here](https://stackblitz.com/edit/components-issue-6b4y3g) you can see the whole code. More about this error, and the solutions how to fix it you can see [here](https://blog.angular-university.io/angular-debugging/).

**Comment by devversion** [comment]
I think @tomicarsk6 is correct. This is actually how change detection has been designed and in the past this just worked by accident since the initial breakpoint observer emit was delayed.

Happy to chat more about this if desired.
