### ISSUE TITLE
Expansion Panel has fixed height even when using long titles

### ISSUE THREAD

**Issue by Adam8234** [angular/components#16476]
#### Reproduction

https://stackblitz.com/edit/components-issue-qv8ybj

Steps to reproduce:
1. Use a long title or use a title too long for the width of your device for an expansion panel
2. Height wont grow to text wrap

![image](https://user-images.githubusercontent.com/5498618/60830219-4fe5fd00-a17c-11e9-87f1-956d4fc0c442.png)

#### Expected Behavior

**What behavior were you expecting to see?**

The expansion panel initial height will grow and wrap title text appropriately when the title is too long for the device width

#### Actual Behavior

**What behavior did you actually see?** Title clipping and with fixed height for expansion panel title.

#### Environment

- Angular: ^8.1.0
- CDK/Material: ^8.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by benjamincharity** [comment]
This may be an actual feature request for new functionality, but just in case you are unaware, you can set a custom height for the collapsed panel using the `collapsedHeight` input: https://material.angular.io/components/expansion/api#MatExpansionPanelHeader

So it could be set ahead of time (via `MatExpansionPanelDefaultOptions`) if you know the correct height, or dynamically (via `@Input`) to fit the content.

**Comment by benjamincharity** [comment]
It also seems you can use the `@Input` to set the height to `auto`:

```html
    <mat-expansion-panel-header [collapsedHeight]="'auto'" [expandedHeight]="'auto'">
      <mat-panel-title>
        Personal datakl sjdfj sdkflsdjlfk sdfj dklfsljfklsdflsj lfsdjf dsf sf sdk d js d lsfdsj l slksdj lfk sdlf lskfjsldj flsdj fsljd flksdj flksdj flksdj flksdj flsdkj fskjfd sldkfj sdlkjf sldkjf dlkjf slkj f
      </mat-panel-title>
      <mat-panel-description>
        Type your name and age
      </mat-panel-description>
    </mat-expansion-panel-header>
```

[StackBlitz Example](https://stackblitz.com/edit/angular-v5gmyk?file=app/expansion-overview-example.html)
[StackOverflow Question](https://stackoverflow.com/a/56166817/722367)

**Comment by Adam8234** [comment]
Thanks @benjamincharity! Nice catch! I don't really understand why 'auto' isn't the default behavior. 

For future reference for everyone:

Adding `[collapsedHeight]="'auto'"` and adding a margin to the title does what I expected with the expansion panel being responsive.
