### ISSUE TITLE
mat-menu does not position correctly after horizontal scroll

### ISSUE THREAD

**Issue by nzacca** [angular/components#16488]
#### Reproduction

See demo of issue here: https://stackblitz.com/edit/angular-5tzbtq?file=src/app/app.component.html
 
#### Expected Behavior

What behavior were you expecting to see?
After scrolling horizontally, the menu should appear below the anchor element.

#### Actual Behavior

What behavior did you actually see?
Menu appears to the left of the anchor element.

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.2
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/components/pull/16235.

**Comment by nzacca** [comment]
@crisbeto Thank you! I apologize for missing that.
