### ISSUE TITLE
Provide list of keyboard codes

### ISSUE THREAD

**Issue by moniuch** [angular/components#16482]
#### Feature Description

I was nicely surprised to see that `@angular/cdk/keycodes` export the table of `keyCode`s for use in apps, which is a great helper. I would vote to provide also a list of `code`s, as - as per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) - `KeyboardEvent#keyCode` is a deprecated property. 

#### Use Case

it should be possible to say:

```ts
  import { Codes } from '@angular/cdk/keycodes'; // or /codes

  @HostListener('document:keydown', ['$event.code'])
  handleKeyDown(code) {
    if(code === Codes.ESCAPE){
      this.popoverRef.cancel()
    }
  }

```

The list could export a namespaced list:

```
  import { Codes } from '@angular/cdk/keycodes';
  // use: Codes.ESCAPE, Codes.TAB, etc
```

or individual constants

```
  import { ESCAPE, TAB } from '@angular/cdk/keycodes';
  // use: ESCAPE, TAB, etc.
```

to be decided by the team.

**Comment by jelbourn** [comment]
You can do this:
```ts
import * as KeyCodes from '@angular/cdk/keycodes';

someFn(KeyCodes.ESCAPE);
```

It's important for these to _not_ be all on one object by default so that optimizers can remove the symbols you're not using.
