### ISSUE TITLE
MatIcon `svgIcon` demo doesn't work on Stackblitz

### ISSUE THREAD

**Issue by benelliott** [angular/components#16484]
#### Documentation Feedback

Asset fails to load when you open the demo in StackBlitz.

https://run.stackblitz.com/api/angular/v1?file=app%2Ficon-svg-example.ts

**Affected documentation page:** Insert a link to the affected page on material.angular.io

https://material.angular.io/components/icon/examples

**Comment by MexicanAce** [comment]
This issue is blocked by a problem within StackBlitz itself: https://github.com/stackblitz/core/issues/72
