### ISSUE TITLE
In the cdk stepper, how can i attach an angular animation for smoothing the transition between steps

### ISSUE THREAD

**Issue by ledrago** [angular/components#16481]
I'm building a stepper with the angular cdk and im trying to attach an angular animation for smoothing the transition between the steps, but i cannot find how to do it. How can it be done ?

**Comment by crisbeto** [comment]
The Angular Material stepper uses the CDK stepper and adds some animations to it. You can take a look at it for an example: https://github.com/angular/components/tree/master/src/material/stepper.
