### ISSUE TITLE
Touch UI mode for select component

### ISSUE THREAD

**Issue by Rodrigo54** [angular/components#16485]
#### Feature Description

create a touch ui for the select component just as there is a touch ui for the datepicker component 

#### Use Case
makes it easy to use on smartphones and smaller screens

![DigitalWellbeing_Blog](https://user-images.githubusercontent.com/8932920/60908383-1e3f6580-a252-11e9-993f-be9b93ca1562.png)

**Comment by jelbourn** [comment]
This isn't something we plan on adding to the `MatSelect` directly. However, if you use the native `<select>` in `MatFormField`, you will get this style of interaction on mobile.
