### ISSUE TITLE
@angular/material entry-point causes very slow builds with Ivy

### ISSUE THREAD

**Issue by IgorMinar** [angular/components#16495]
#### Reproduction

Steps to reproduce:
```
yarn global add @angular-cli@next
ng new foo --enable-ivy
ng add @angular/material
ng generate @angular/material:nav my-navbar
ng build
``` 
 
 
#### Expected Behavior

What behavior were you expecting to see?

`ngcc` will compile just a handful of entrypoints needed for the navbar. This should take just a few seconds.

#### Actual Behavior

What behavior did you actually see?

`ngcc` compiles all entrypoints within the @angular/material package as well as some/all entry-points within @angular/cdk package.

This delays the initial build by as much as 2 minutes.

#### Environment

- Angular: 8.1.0-next.0
- CDK/Material: 8.0.2
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 

#### Proposed solution

- update schematics to use deep secondary entry-points instead of the main entry point
  `import { MatToolbarModule, MatButtonModule, MatSidenavModule, MatIconModule, MatListModule } from '@angular/material';`
- execute migration to secondary entry-points and remove the @angular/material entry-point

**Comment by devversion** [comment]
The schematics have been already updated to use the secondary entry-points. For reference: https://github.com/angular/components/commit/b823dbd8b66db47e5f7d0a646020e9f77e87c270

**Comment by IgorMinar** [comment]
that's great! do we have a plan for migrating all of the existing code to these entry-points?

**Comment by devversion** [comment]
The current state is that nothing in the `components` repository uses the primary entry-point anymore. 

With the deprecation of the primary entry-point in version 8, we also provided a migration schematic that updates existing CLI projects to the new imports. 

The plan is to remove the primary entry-point in version 9 (according to the changelog. see [here](https://github.com/angular/components/blob/master/CHANGELOG.md#deprecations))

**Comment by Splaktar** [comment]
The related [deprecation guidelines](https://angular.io/guide/releases#deprecation-practices) were discussed in today's sync.

> Deprecation period: When an API or a feature is deprecated, it will still be present in the next two major releases. After that, deprecated APIs and features will be candidates for removal. 

Perhaps since these are not changes to the APIs and only changes to the paths of the imports, this may not require 2 majors before removal?

**Comment by devversion** [comment]
Yeah it's quite ambiguous as the changelog says that we'll do it in version 9. I don't see any problem with doing that in version 9 as we deprecated in version 8 and provided a migration schematic.

Regardless of the deprecation guideline, this would definitely also help with Ivy and version 9. Doing it  in version 10 (as the deprecation guideline proposes) will probably result in bad experience w/ Ivy.

**Comment by jelbourn** [comment]
Closing this because the schematics and examples have already been changed, the top-level entry-point is deprecated as of version 8, and we can't remove it sooner while respecting Angular's breaking change policy (which you authored :wink:). 

Might be worth seeing if someone wants to add a lint check for codelyzer for it separately.
