### ISSUE TITLE
Basic native select to have material styling/look and fill

### ISSUE THREAD

**Issue by nikhil4326** [angular/components#16497]
#### Feature Description

To have Material look and fill to basic native select component with complete accessibility support

#### Use Case

Consider page has material component except select component with native styles. Looks and fill complete page impacted because of native select component. Do we have that ability to apply material styles to native element.

or

Is there any way to apply css styles to native select component to have material look and fill.

**Comment by jelbourn** [comment]
It's impossible to style the pop-up of a native select because it's rendered by the operating system and is not part of the DOM.

**Comment by nikhil4326** [comment]
Can we have mat-select component with accessibility support in near future?
