### ISSUE TITLE
Email validation not working properly

### ISSUE THREAD

**Issue by sagar2071995** [angular/components#16492]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior
email validation should display error for example@example   this mail id

#### Actual Behavior
but not showing an error

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by sagar2071995** [comment]
please solve the email validation validation it take invalid email as valid .ex   example@example

**Comment by tomicarsk6** [comment]
I think that this is a wrong stackblitz example.

**Comment by crisbeto** [comment]
Angular Material doesn't deal with email validation.
