### ISSUE TITLE
Issue with Menu typings when building with Ivy

### ISSUE THREAD

**Issue by phillipCouto** [angular/components#16509]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-rdulwq

Steps to reproduce:
1. Create new Angular application with Ivy enabled
2. Add a material menu component
3. Run `ng build`
 
 
#### Expected Behavior

What behavior were you expecting to see?

A clean build.

#### Actual Behavior

What behavior did you actually see?

Build fails with the following error message:

```
ERROR in node_modules/@angular/material/menu/typings/menu.d.ts:161:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

161     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
```

#### Environment

- Angular: 8.1.1
- CDK/Material: 8.0.2
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**I know Ivy isn't fully released but I figured I would mention this in case it hasn't been identified already.**

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/angular/commit/eb6281f5b471e55d5c761065e17ab2a293690d29.
