### ISSUE TITLE
mat-option keyboard events - unable to override

### ISSUE THREAD

**Issue by cbejensen** [angular/components#16505]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-cdy9uu?file=app/select-overview-example.ts

Steps to reproduce:
1. Bind a custom function to an `enter` or `space` keypress event on a `mat-option` element within `mat-select`.
2. Try pressing `enter` or `space` on one of the select options and observe that your function is not called.
 
 
#### Expected Behavior
The custom function should be called, just like `click` (which works).

#### Actual Behavior
The custom function bound to the keyboard event does not get called and seems to have no effect.

#### Environment

- Angular: 8.1.1
- CDK/Material: 8.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

#### Notes
I see a similar situation [here](https://github.com/angular/components/issues/11654), but the solution seems pretty hacky with this direct manipulation of the DOM, and I'd like to see if there's a better way or something simple I am missing.

**Comment by crisbeto** [comment]
Your keyboard events aren't firing, because focus isn't actually on the options, it stays on the trigger of the `mat-select` element. The events will fire if you put them on the `mat-select` element or one of its parents.
