### ISSUE TITLE
feat: CDK "is loading?" service

### ISSUE THREAD

**Issue by thefliik** [angular/components#16516]
#### Feature Description

I'd like Angular CDK to include a service to simplify the (common) process of displaying loading indicators. The service would help an app answer the following questions:

- Should I (the app) display the "page loading" indicator?
- Should I display the "creating a new user" indicator?
- Should I display the "users loading" indicator?
- etc

The service's API would be simple: it has an `isLoadingService#isLoading$()` method which returns an observable that emits `true` when loading is occurring and `false` when loading isn't occurring. This observable can be subscribed to in a template using the `async` pipe and used to display loading indicators with `ngIf`. In order to allow the tracking of multiple things at the same time, you can pass a `key?: string | symbol | object` argument to `isLoading$()` which customizes the returned observable to only track the loading of "loading things" also associated with that key.

For example:

```ts
// get Observable<boolean> to track loading associated with the "create-user" key
const loadingObservable = this.isLoadingService.isLoading$({key: 'create-user'})
// => loadingObservable initially emits false

isLoadingService.add({key: 'create-user'})
// => loadingObservable emits true

isLoadingService.remove({key: 'create-user'})
// => loadingObservable emits false

isLoadingService.add(subscription, {key: 'create-user'})
// => loadingObservable emits true and then emits false when `subscription` closes

isLoadingService.add(promise, {key: 'create-user'})
// => loadingObservable emits true and then emits false when `promise` resolves

isLoadingService.add({key: 'create-user'})
// => loadingObservable emits true
isLoadingService.add({key: 'create-user'})
isLoadingService.remove({key: 'create-user'})
isLoadingService.remove({key: 'create-user'})
// => loadingObservable emits false

// etc
```

By adding a service like this one to `@angular/cdk`, a follow up PR could also add a directive which integrates with the service and which simplifies the process of, say, styling or disabling a button while loading requests are in flight.

For example, today to accomplish the process of styling/disabling a button you would need to manage a separate `creatingUser` variable in a template. For example:

```ts
@Component({
  template: `
  <button
    id="create-user-form-button"
    mat-button
    [ngClass]="{'cdk-is-loading': createUser}"
    [disabled]="creatingUser"
  >
    Submit form
  </button>
  `
})
export MyComponent {
  creatingUser = false;

  async submit(data: any) {
    this.creatingUser = true;
    await this.userService.createUser(data);
    this.creatingUser = false;
  }
}
```

But a service + directive like this could simply the component down to:

```ts
@Component({
  template: `
<button
  id="create-user-form-button"
  mat-button
  cdkIsLoading="create-user"
>
  Submit form
</button>
  `
})
export MyComponent {
  submit(data: any) {
    const promise = this.userService.createUser(data);

    this.isLoadingService.add(promise, {key: 'create-user'})
  }
}
```

#### Use Case

Displaying loading indicators is a common need but surprisingly tricky to get right. The issue is that you want an action to trigger a specific type of loading. e.g. "create-user" loading or "page-navigation" loading. You can also have multiple requests in flight and associated with the same "create-user" loading indicator. If multiple "create-user" requests are happening, you want the loading indicator to continue displaying until they are all done.

Most async requests associated with loading will provide an observable or promise value. You want the ability to automatically indicate that loading has stopped when that observable / promise completes.

Other loading instances are more complex, and you want the ability to manually indicate that loading has started or stopped. For example:

```typescript
this.router.events
      .pipe(
        filter(
          event =>
            event instanceof NavigationStart ||
            event instanceof NavigationEnd ||
            event instanceof NavigationCancel ||
            event instanceof NavigationError,
        ),
      )
      .subscribe(event => {
        if (event instanceof NavigationStart) {
          this.isLoadingService.add();
          return;
        }

        this.isLoadingService.remove();
      });
```

#### Implementation example

I created a library which implements an API like this: https://gitlab.com/service-work/is-loading. I think it would be valuable if a service like this were simply included in Angular CDK because:

1. This is addressing a very common need in a generic way.
2. It would be easier for 3rd party libraries to integrate with the service as a peer dependency if it is part of `@angular/cdk`.
3. It would make adoption easier for developers.

**Comment by jelbourn** [comment]
Thanks! I think this concept is just a bit too specific to be a good general fit for the cdk.

**Comment by thefliik** [comment]
Fair enough 👍
