### ISSUE TITLE
MatBadge Error in IE and Edge

### ISSUE THREAD

**Issue by germanl19921** [angular/components#16510]
#### Expected Behavior

When use IE or Edge Browser, the component MatBadge give to me an error becouse the method _clearExistingBadges use a function call "contains()". This Function is not supporter in IE 11 and Edge Browser. 

#### Actual Behavior

What behavior did you actually see?
![image](https://user-images.githubusercontent.com/52840155/61160724-f90f5900-a4d6-11e9-9fba-87b10e201ed7.png)

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The only place where we call a method called `contains` in `MatBadge` is here: https://github.com/angular/components/blob/master/src/material/badge/badge.ts#L262. The `classList.contains` [is supported in both IE11 and Edge](https://caniuse.com/#search=classlist). It looks like it might be an issue in your setup.

**Comment by jelbourn** [comment]
@germanl19921 can you share a full reproduction?

**Comment by germanl19921** [comment]
@jelbourn @crisbeto I'm sorry, I thought the problem was in the 'contains' function but it was my mistake.
From what I could read in this documentation that you sent [here](https://caniuse.com/#search=classlist)  the property 'classList' in IE11 does not have support for SVG elements. This is my case, because I use the 'matbadge' component in conjunction with the 'matIcon' component.

Solve the problem by creating a 'div' element that encapsulates the matIcon component and on that component I use the matBadge, that way I did not get the error.

![image](https://user-images.githubusercontent.com/52840155/61316679-e13a1c80-a7d7-11e9-96f4-e3da0fedf83e.png)

![image](https://user-images.githubusercontent.com/52840155/61317009-7b9a6000-a7d8-11e9-8888-b3ef257bd926.png)
