### ISSUE TITLE
NullInjection Error for modular Angular Material Sidenav

### ISSUE THREAD

**Issue by jd12** [angular/components#16524]
Building a sidenav using angular-material. Wanted to make it more modular so made the sidenav bar and the main toolbar different components. This caused a `NullInjectorError: No provider for MatSidenavContainer!` in our main toolbar test cases even though the MaterialModule/MatSidenavModule is available to the tests.

Tried adding MaterialModule (which contains modules for AngularMaterial) to the imports in the test suite. Also tried adding the other components (NavbarComponent and AppComponent) to the test suite. Also tried adding the modules separately into the file (e.g. `import { MatSidenavModule } from '@angular/material/sidenav`). Still throwing the error.  

Setup <br>
Angular 8 <br>
Angular Material 8 <br>
Jasmine: 3.4 <br>
Karma: 4.1

To reproduce error:
Clone repository https://github.com/ChadwickSchool/Weight-Lifting-App/tree/sidenav-test-error
From inside directory
```
git checkout sidenav-test-error
npm install
ng test
```

This is how the sidenav is set up 
app.component.html 
```html
<mat-sidenav-container>
  <mat-sidenav #sidenav role="navigation">
    <wla-sidenav></wla-sidenav>
  </mat-sidenav>
  <mat-sidenav-content>
      <wla-navbar (toggleSidenav)="sidenav.toggle()"></wla-navbar>
      <router-outlet></router-outlet>
  </mat-sidenav-content>
</mat-sidenav-container>
```

Here goes the test case throwing the error:
```
describe('NavbarComponent', () => {
  let component: NavbarComponent;
  let fixture: ComponentFixture<any>;

  const authServiceStub = {
    user$: of(null),

    async googleSignin() {
      this.user$ = of(TestUtils.getTestUser());
    },

    async signOut() {
      this.user$ = of(null);
    }
  };

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [NavbarComponent],
      imports: [
        MatSidenavModule,
        MatIconModule,
        MatToolbarModule,
        NoopAnimationsModule,
        AngularFireModule.initializeApp(environment.firebaseConfig),
        AngularFirestoreModule,
        AngularFireAuthModule
      ],
      providers: [
        {
          provide: AuthService,
          useValue: authServiceStub
        }
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(NavbarComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

Github repository
https://github.com/ChadwickSchool/Weight-Lifting-App/tree/sidenav-test-error

[full error message][1]

  [1]: https://i.stack.imgur.com/vbAiL.png

**Comment by andrewseguin** [comment]
This seems to make sense to me, since you are testing the `NavbarComponent` which does not have a `<mat-sidenav-container>` in its template. The `MatSidenavContent` will complain that this is missing.

Since your `app.component.html` has the sidenav content tag containing the navbar, it's not clear to me why you are also including `mat-sidenav-content` in `navbar.component.html`.

There doesn't seem to be an error or bug here

**Comment by jd12** [comment]
Thank you @andrewseguin. Removing `mat-sidenav-content` from `navbar.component.html` fixed the error.
