### ISSUE TITLE
MatBottomSheet with EventEmitter

### ISSUE THREAD

**Issue by aleksander351** [angular/components#16521]
#### Feature Description

I want to be able to call a function of the Component the Bottom Sheet was called from.

For example, Ionic has methods as parameters of a Modal Instance:

    `
        openModal(item) {
            const modal = this.modalCtrl.create(ModalComponent, {
              someModalMethod: (parameter) => {
                this.someComponentFunction();
              },
              someData: this.someComponentData
            });
            modal.present();
          }
    `

#### Use Case

If the Bottom Sheet has some action, which can be useful for the component, from which the Bottom Sheet was opened.

**Comment by jelbourn** [comment]
`MatBottomSheetRef` has an `afterOpened` stream for this.

**Comment by aleksander351** [comment]
Dear Angular Team!

From the docs:
**afterOpened**
Gets an observable that is notified when the bottom sheet has opened and appeared.

That doesn't really show how it works, now, does it?
Of what use is an api if there is no implementation example in the docs?

I don't see how afterOpened can enable me calling a function of the Component from which the Bottom Sheet was called.

Ok, I found it here:
https://github.com/angular/components/issues/3593#issuecomment-286397115

    `
      const sub = bottomSheet.instance.onSelect.subscribe((val) => {
         console.log(val);
      });

       etc...
    `
