### ISSUE TITLE
mat-slide-toggle labelPossition

### ISSUE THREAD

**Issue by emiber** [angular/components#16523]
#### Reproduction
Steps to reproduce:
1. Insert a mat-slide-toggle in a page.
2. Set the property labelPosition="before"
3. Set the property labelPosition="after"
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expect the label to change the position.

#### Actual Behavior

What behavior did you actually see?
I expect the label do not change the position.

#### Environment

- Angular: 8.0.4
- CDK/Material: 8.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
How are you setting the property? Can you post an example?

**Comment by emiber** [comment]
<mat-slide-toggle *ngIf="fieldType==='checkbox'" matInput [checked]="checkboxValue" [required]="required"
        [aria-label]="column.columnComment" [color]="warn" [labelPosition]="before" (change)="changeValue($event);">
        {{column.columnComment}}
    </mat-slide-toggle>

**Comment by crisbeto** [comment]
`[labelPosition]="before"` is looking for a property called `before` on your component. If it isn't supposed to change, you can just use `labelPosition="before"`.
