### ISSUE TITLE
Focus out is not reflected on select's arrow

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/components#16522]
#### Reproduction

The issue can be reproduced in [Material documentation](https://material.angular.io/components/select/overview) right away.

Steps to reproduce:
1. Open options list and select an item
2. Focus out (click somewhere outside the select)
3. Look at the select's arrow. It still has the focus color.
 
#### Expected Behavior

The arrow should change the color after focusing out same as the underline or placeholder.

#### Actual Behavior

The arrow still has the focus color after focusing out.

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.2
- Browser(s):  Safari/Mac, Safari/iPad
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/components/pull/15281.
