### ISSUE TITLE
Mat-tab-group arrows

### ISSUE THREAD

**Issue by RunfastCoder** [angular/components#16531]
There is a problem with Mat-tab-group arrows and virtual keyboard (when using it on phone)
The arrows are not showing after the virtual keyboard is open.

Any idea how to fix it ?

Thanks.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
