### ISSUE TITLE
Material Pagination - Count of records/items not updated on length change

### ISSUE THREAD

**Issue by sameerthekhans** [angular/components#16532]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-wfaqgx?file=app/paginator-configurable-example.html

Steps to reproduce:
1. Goto some "X" page, Eg. **Page 3** and change length
 
 
#### Expected Behavior

Records available in the list should be updated and Previous/Next button too

#### Actual Behavior

Count and Previous/Next button not updated

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
This is an intentional side effect of the `MatPaginator`, you can see the explanation why here: https://github.com/angular/components/issues/5812#issuecomment-315779232
