### ISSUE TITLE
proposal : datepicker add popup position in horizontal big input (Input 100%)

### ISSUE THREAD

**Issue by mkumar-01** [angular/components#16550]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-xax8rg?file=styles.css

Steps to reproduce:
1. .mat-form-field-infix{
  width:100% !important;
}
2. .mat-form-field{
  display:block !important;
}
 
 
#### Expected Behavior

What behavior were you expecting to see?
The calendar should open at the position where the user had clicked at arrow icon.

#### Actual Behavior

What behavior did you actually see?
When the width of the input is 100% to make it responsive, calendar opened at the left.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by SERGEES** [comment]
It would be realy cool to have controll over https://github.com/angular/components/blob/master/src/material/datepicker/datepicker.ts#L479
