### ISSUE TITLE
[MatDialog] Can MatDialog has "afterDismiss" handle to handle the cancel click?

### ISSUE THREAD

**Issue by niudai** [angular/components#16558]
#### Feature Description

I only see "afterClosed()" handle for matDialogRef, but I think it would be better to have another handle called "afterDismissed()" to handle user cancel click.

#### Use Case

I always use mat-dialog to handle **confirm or cancel**  interaction, so the thing would behave differently between **confirm** and **cancel**.

In ngbootstrap (bootstrap for angular), dialog model has two handle which deals with **confirm** and **cancel**, but in angular, there seems only exists a "afterClosed()" handle to deals with user close action.

Of course I could implement these methods in the dialog component, but this makes the component dependent of my method. Everytime I made a dialog, I should created a new dialog component to implement my customed method.

If "afterDismissed()" and "afterClosed()" both are implemented, I could reuse one component to handle many different situation.

**Comment by the-avid-engineer** [comment]
It doesn't seem to be documented, but `MatDialogRef.close` does have an optional argument, and it is passed to subscribers of `afterClosed` (as well as `beforeClosed`)

```
this.dialog_ref.beforeClosed().subscribe((affirmative) => {
    if (affirmative === true) {
        if (this.on_ok) {
            this.on_ok();
        }
    } else {
        if (this.on_cancel) {
            this.on_cancel();
        }
    }
}),
```

The value is undefined if the user clicks on the backdrop or uses the escape key.

**Comment by niudai** [comment]
Sorry I still could not find this "optional argument" in Angular Documentation from the link you gave.

**Comment by Totati** [comment]
> Sorry I still could not find this "optional argument" in Angular Documentation from the link you gave.

https://material.angular.io/components/dialog/api#MatDialogRef Methods -> Close. You can see it has a parameter called dialogResult?:R. The type of beforeClosed and afterClosed is Observable<R | undefined>, so there's a option to return some value from the dialog. You can call dialogRef.close(true) to be affirmative.
