### ISSUE TITLE
Docs examples are pointing to the wrong version of CDK/Material

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#16569]
#### Documentation Feedback

The examples on the docs site are loading in StackBlitz with version 8.0.2 instead of version 8.1.1. This caused an issue where a new input on the `MatAccordian` was not working on an example from StackBlitz,

Discovered in issue #16567 

**Affected documentation page:** https://material.angular.io/components/expansion/api

**Comment by andrewseguin** [comment]
Looks like the [stackblitz-writer.ts](https://github.com/angular/material.angular.io/blob/1c793cd316fb11e3eb4fb14d1c9a6c8f447b9e36/src/app/shared/stackblitz/stackblitz-writer.ts#L37) will [use the version](https://github.com/angular/material.angular.io/blob/1c793cd316fb11e3eb4fb14d1c9a6c8f447b9e36/src/app/shared/version/version.ts) from the installed material from its [package.json](https://github.com/angular/material.angular.io/blob/1c793cd316fb11e3eb4fb14d1c9a6c8f447b9e36/package.json).

Looks like we need to make sure we keep the docs site package.json better up to date when we publish minors. I'll add this into the internal docs for publishing new versions

**Comment by andrewseguin** [comment]
Root cause seems to be due to a mistake made in deploying out the docs and will be fixed with the next minor docs pushed (8.1.1)

**Comment by jelbourn** [comment]
Resolved
