### ISSUE TITLE
Custom icons for sorting

### ISSUE THREAD

**Issue by CameronEzraJones** [angular/components#16560]
#### Feature Description

Allow for the customization of the arrow with sorting

#### Use Case

Currently, sort headers have a little arrow indicating the direction of the sort:
![image](https://user-images.githubusercontent.com/4868872/61473239-3e061600-a943-11e9-9cc0-a7a3cefbf9c2.png)
Looking through the source code, I noticed that the icon isn't really an icon, but a collection of divs that are styled to look like an arrow (in src/material/sort/sort-header.html):

```
<div class="mat-sort-header-arrow"
       *ngIf="_renderArrow()"
       [@arrowOpacity]="_getArrowViewState()"
       [@arrowPosition]="_getArrowViewState()"
       [@allowChildren]="_getArrowDirectionState()"
       (@arrowPosition.start)="_disableViewStateAnimation = true"
       (@arrowPosition.done)="_disableViewStateAnimation = false">
    <div class="mat-sort-header-stem"></div>
    <div class="mat-sort-header-indicator" [@indicator]="_getArrowDirectionState()">
      <div class="mat-sort-header-pointer-left" [@leftPointer]="_getArrowDirectionState()"></div>
      <div class="mat-sort-header-pointer-right" [@rightPointer]="_getArrowDirectionState()"></div>
      <div class="mat-sort-header-pointer-middle"></div>
    </div>
  </div>
```

As a developer that wants to build a theme based off Material, I would like to be able to

1. Specify a custom icon such as a carat or chevron
2. Allow for the disabling of sort animations.

**Comment by jelbourn** [comment]
This isn't a feature we plan on implementing since the Material Design spec is pretty prescriptive about the arrow appearance. However, we do plan on moving the sort logic to the CDK so it will be much easier for people to build custom sort headers that aren't tied to Material Design.
