### ISSUE TITLE
matAccordion and MatExpansionPanel  togglePosition not working

### ISSUE THREAD

**Issue by trixrabbit** [angular/components#16567]
I'm trying to put the toggle indicator before the title but @input() togglePosition doesn't seen to work.

Steps to reproduce:
1. Go to stackblitz of the basic expansion panel : https://material.angular.io/components/expansion/examples
2. Add togglePosition="before" tot he mat-accordion, nothing changes. 
3. Add [togglePosition]="'before'" and you get : Can't bind to 'togglePosition' since it isn't a known property of 'mat-accordion'.
 
 
#### Expected Behavior

The toggle indicator placed before the title

#### Actual Behavior

The togglePosition input is not recognized

#### Environment

- Angular (the version from the stackblitz)
- browser 60.7.1esr (32-bit)

Couldn't get it to work locally either

Sidenotes:  The documentation for matExpansionPanel is wrong for togglePosition (looks like a copy/paste from hideToggle)

**Comment by andrewseguin** [comment]
The `togglePosition` input was added in version 8.1.0 and the docs example defaults to 8.0.2.

Here's an example using that input with the latest version: https://stackblitz.com/edit/angular-nipwqn?file=app/expansion-overview-example.html

We'll need to look at updating the versions used on the docs site
