### ISSUE TITLE
Support "cloning" items on drag rather than "moving"

### ISSUE THREAD

**Issue by egd-flaine** [angular/components#16585]
Hello everyone,

#### Feature Description

I would greatly appreciate it if we could define the type of DragNDrop we want among the following choices: copy, move, link.

This could be a directive to be put in the CdkDropList.

#### Use Case

In my case, there is the app logo in the menu bar. I want to be able to take it and move it to my sidebar to save the current url as a shortcut.
But when I grab the logo, it disappears from my bar because it is a DragNDrop move by default.

In advance, thanks a lot.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/13906.
