### ISSUE TITLE
Schemantic nav did not work as expected

### ISSUE THREAD

**Issue by vrapalis** [angular/components#16582]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-yye2gy?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Install angular material 8.1.1
2. Generate schemantic nav
 
 
#### Expected Behavior

What behavior were you expecting to see?
Navbar left

#### Actual Behavior
No navbar on the left site

What behavior did you actually see?
Only header without navbar on the left site

#### Environment

- Angular: 8.1.2
- CDK/Material: 8.1.1
- Browser(s): chrome 75
- Operating System (e.g. Windows, macOS, Ubuntu): macOc

**Comment by A7xSV** [comment]
I get the same thing on load. It is only after resizing the window that the navbar appears.

**Comment by feedmei** [comment]
I wonder if the share() function is supposed to be shareReplay() ?

**Comment by vrapalis** [comment]
> I get the same thing on load. It is only after resizing the window that the navbar appears.
> 
> I am not sure if that is the desired behaviour but you can remove the share() function from the isHandset$ property in your Typescript file to make it work the way it used to.
> 
> ```
> isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
>     .pipe(map(result => result.matches),
>         share() // ** Remove this **
> );
> ```

Many thanks!

**Comment by crisbeto** [comment]
Seems like the issue was resolved. Closing.
