### ISSUE TITLE
If not currently possible, it'd be create if we could connect 2 Drag-n-Drop components by a line

### ISSUE THREAD

**Issue by willkara** [angular/components#16589]
#### Feature Description

While the drag-and-drop components allow a multitude of options, it'd be great if we could relate/connect them together using a line.

![Something like this](https://user-images.githubusercontent.com/3278887/61760199-c861d600-ad98-11e9-80a3-7f3a61964171.png)

It'd use smart pathing/routing to find a route to the next object.

#### Use Case
Easy way to show relationships between objects.

**Comment by crisbeto** [comment]
The `cdkDrag` directive has an input called `cdkDragConstrainPosition` which should allow you to do this. You can give it a function that decides how the item should move while it's being dragged. We use the same code path when constraining the position along the x or y axis.

**Comment by willkara** [comment]
Hey @crisbeto , I guess I'm having a hard time figuring out how that would allow the line to be drawn between the objects.

Would that function somehow paint it and then move with the objects?

**Comment by crisbeto** [comment]
`constrainPosition` works by accepting a function that will be called with the user's pointer position and has to return the coordinates at which the drop item should be rendered. You can use this to make the item follow the lines that are shown in your diagram.

**Comment by crisbeto** [comment]
Closing since there hasn't been any new information in a while.
