### ISSUE TITLE
mat-select doesn't close when you click outside of dropdown in case of dialog

### ISSUE THREAD

**Issue by abdullahqudeer** [angular/components#16586]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ddfuf7

GUI of above example is not good as i am not FE developer.

Steps to reproduce:
1. add mat multi select drop-down in mat dialog 
2. open drop-down options and select some options 
3. click outside of drop-down in dialog 
4. drop-down option will not close. 
 
 
#### Expected Behavior

click outside of drop-down in dialog should close option panel of drop-down

#### Actual Behavior

click outside of drop-down in dialog , drop-down option panel is not closing. 

#### Environment

- Angular: 8 
- Material: Material Design 
- Browser(s): Chrome 
- Operating System : Windows

**Comment by crisbeto** [comment]
The example above is missing their structural styles. There's a warning about it in the console. You have to add a theme: https://material.angular.io/guide/getting-started#step-4-include-a-theme.
