### ISSUE TITLE
Provide CDKScrollable as a service as well

### ISSUE THREAD

**Issue by MurhafSousli** [angular/components#16580]
#### Feature Description

It would be very useful if there is a service e.g. `CDKScrollableManager` that returns a `CDKScrollable` reference for the given scrollable element

#### Use Case

In my case, I have a custom scrollbar library, the `CDKScrollable` directive is used in the default viewport element, however, the problem occurred when I wanted to make it possible for users to use their own custom scroll viewport.

This is very important for integrating other libraries like `ngx-infinite-scroll` or `CDKVirtualScroll` along with the custom scrollbar library

_Example of integrating_

```html
<lib-component>
  <div infiniteScroll libCustomViewPort>
     content...
  </div>
</lib-component>

OR

<lib-component>
  <cdk-virtual-scroll-viewport libCustomViewPort>
     content...
  </div>
</lib-component>
```

In the custom scrollbar library, the component template has something like this

```html
<div class="ng-scroll-viewport-wrapper">
   <div #viewport>
       <ng-content></ng-content>
   </div>
</div>
<scrollbar-control *ngIf="verticalScrollbarUsed" ..>
<scrollbar-control *ngIf="horizontalScrollbarUsed" ..>
```
In the component code I want to be able to set the `CDKScrollable` on a projected content element if user used the library's custom viewport directive

```ts
export class LibComponent {

  @ViewChild('viewport', { static: true }) defaultViewport: ElementRef;
  @ContentChild(LibCustomViewPort, { static: true }) customViewport: LibCustomViewPort;
  scrollableRef: CDKScrollable;

  // Assume this service exists
  constructor(private manager: CDKScrollableManager) {
  }

  ngOnInit() {
     if (this.customViewPort) {
         // If user used the custom viewport directive
         this.scrollableRef = this.manager.getCDKScrollable(this.customViewport.nativeElement);
     } else {
         this.scrollableRef = this.manager.getCDKScrollable(this.defaultViewport.nativeElement);
     }
  }
}
```

But since this `CDKScrollable` is only provided as a directive, users of my library who want to use a custom viewport will have to import the `ScrollingModule` and also add the `CDKScrollable` directive along with `libCustomViewPort` directive, which kinda ruins the library's goal to ease the usage.

**Comment by crisbeto** [comment]
All of the scrollables register themselves with the `ScrollDispatcher`. You should be able to get a hold of the ones you need through there.

**Comment by MurhafSousli** [comment]
@crisbeto Please have another look at my use case

The `CDKScrollable` should be a generic class that can be created through a directive or a service. the directive should act as a wrapper only.

With the current implementation, the `ScrollDispatcher` does not help unless you've already used `CDKScrollable` on the element, which is exactly what I am trying to avoid.

**Comment by crisbeto** [comment]
Closing since we have an API for this already (`ScrollDispatcher`).
