### ISSUE TITLE
set the pageIndex property not work correctly

### ISSUE THREAD

**Issue by hyq2015** [angular/components#16590]
#### Expected Behavior

the tableData's length is 100 (pageSize=10), when I turn to page 2, and then choose a filter to search newData, newData's length is 9, then I set the pageIndex to 0, the pagination should show 1-9 of 9

#### Actual Behavior

11-20 of 9
it seems [pageIndex]=0 dosent's work, however, the funny thing happens when I set the pageIndex to string "0", it worked! infact, we can see the type of pageIndex is number, not string.

**Comment by crisbeto** [comment]
We have some logic to ensure that setting either a string or a number will work. Can you post what your code looks like?

**Comment by hyq2015** [comment]
@crisbeto 
html:
<mat-paginator [length]="tableData.length"
              [pageSize]="pageSize"
              [pageIndex]="pageIndex"
              >
</mat-paginator>

ts:
tableData = [.......];
pageIndex = 0;
onSearch() {
......
this.tableData = [....];
this.pageIndex = 0; //not work
this.pageIndex = '0'; // worked! but the type is not correct
}

**Comment by mmalerba** [comment]
It seems to be working for me, here's an example: https://stackblitz.com/edit/angular-3penjx?file=src/app/paginator-overview-example.ts
