### ISSUE TITLE
Compile error with fullTemplateTypeCheck and strictInjectionParameters

### ISSUE THREAD

**Issue by GlauberF** [angular/components#16594]
## Environment

Angular CLI: 8.1.2
Node: 10.15.3
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.1
@angular/material-moment-adapter   8.1.1
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

## Bug

with the option below active
`
"angularCompilerOptions": {
        "fullTemplateTypeCheck": true,
        "strictInjectionParameters": true
    }
`

Running the command to deploy or start returns the problem mentioned in the attached text and image

```
node_modules/@angular/material/menu/typings/menu.d.ts:166:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

166     static ngBaseDef: ɵngcc0.ɵɵBaseDef;

```

![61736564-bf531380-ad5c-11e9-8a5f-74e0a12c3e8d](https://user-images.githubusercontent.com/11314585/61792442-228f8500-adf3-11e9-87fd-a2e3aee8d8da.png)

**Comment by thejeff77** [comment]
I'm also seeing this on 8.1.0:

Commented with details here: https://github.com/angular/flex-layout/issues/1105

**Comment by crisbeto** [comment]
This should've been resolved back in v9.

**Comment by GlauberF** [comment]
for me solved in v9
