### ISSUE TITLE
cdk drag-drop - event.previousContainer always equals to event.container

### ISSUE THREAD

**Issue by ranbuch** [angular/components#16595]
#### Reproduction

Steps to reproduce:
1. Implement one of the drag and drop examples from [here](https://material.angular.io/cdk/drag-drop/overview) but use [expansion panel](https://material.angular.io/components/expansion/overview) as the `cdkDropList` container.
2. On the `drop` function that looks like this:
```javascript
drop(event: CdkDragDrop<Array<ProductSubCategory>>) {
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    } else {
      transferArrayItem(event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex);
    }
  }
```
the `event.previousContainer` is always equals to `event.container`.
 
 
#### Expected Behavior

`cdk drag-drop` should support dynamic `cdkDropList`.

#### Actual Behavior

`cdk drag-drop` doesn't support dynamic `cdkDropList` on my case.

I've solved this problem by changing the `[cdkDropListData]` dynamically instead of creating the `cdkDropList` element dynamically.

#### Environment

- Angular:
8.0.1
- CDK/Material:
8.0.1
- Browser(s):
Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows

**Comment by crisbeto** [comment]
Can you post the code that you're using?

**Comment by ranbuch** [comment]
Thank you for responding.
I've already changed my code and it's a part of a much bigger application but I can tel you that:
```javascript
event.previousContainer.id == event.container.id == "cdk-drop-list-2"
```
I'll understand if you want to close this issue, just wanted to report.

**Comment by crisbeto** [comment]
Closing since this isn't a lot of info to go on. Generally the `event.container` gets updated once the item enters the new container (e.g. you see the `.cdk-drag-placeholder` in it). If that's not happening, you might want to double-check that the drop lists you're dragging between are connected properly.
