### ISSUE TITLE
Mat-sort-table first arrow column is not working properly inside modal

### ISSUE THREAD

**Issue by dluque92** [angular/components#16592]
#### Reproduction

Use StackBlitz to reproduce your issue: 

https://stackblitz.com/edit/angular-dluque

Steps to reproduce:
1. Open modal
2. Move the mouse hover column-header
3. See the difference between first, and other columns
 
 
#### Expected Behavior

What behavior were you expecting to see?
Arrow trigger works fine and as the same as all other columns

#### Actual Behavior

What behavior did you actually see?
The arrow is not showed

#### Environment

- Angular: 8.1.2
- CDK/Material: 8.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by yakimko** [comment]
any updates?

**Comment by pro100skm** [comment]
Guys, anything??

**Comment by gmiguel14** [comment]
updates?

**Comment by weilinzung** [comment]
Any updates? same here, when using dialog the first column header sorting arrow is not showing.

**Comment by pro100skm** [comment]
> Any updates? same here, when using dialog the first column header sorting arrow is not showing.

i think that we will never know the answer =D

**Comment by jackmparker** [comment]
I'm seeing this behavior in a mat-expansion-panel as well. Any updates?

**Comment by limedot** [comment]
@jackmparker . Guys. You can solve it if you change initial focus in mat dialog. Use cdkFocusInitial.

**Comment by Yossri21** [comment]
> Use cdkFocusInitia

how ?

**Comment by ccjmne** [comment]
Using the `cdkFocusInitial` directive does fix the issue.

Here's the [forked Stackblitz](https://stackblitz.com/edit/angular-dluque-u4wyrp).

Here's the gist of it:
```diff
 <table
   class="mat-elevation-z8"
   mat-table
   matSort
+  cdkFocusInitial
   [dataSource]="dataSource">
```

**Comment by weilinzung** [comment]
@ccjmne that works. Thank you so much!

**Comment by dluque92** [comment]
@ccjmne works fine to me! Thanks!
