### ISSUE TITLE
Mat-tooltip is not working in mobile with slide toggle and also in div tag

### ISSUE THREAD

**Issue by nidhi42** [angular/components#16591]
#### Reproduction

reproduce my issue is here: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. apply mat-tooltip on your component
2. show in mobile devices 
 
 
#### Expected Behavior

tooltip should be display on longpress or touch 

#### Actual Behavior

tooltip is not displayed in mobile device

#### Environment
Mobile Device/Touch Device

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by gabrieltaets** [comment]
I have this also.
Checking the event listeners, I noticed that on desktop we have mouseouver/mouseout listeners, but on responsive/mobile those aren't registered. Longpress event listener should work but it's not. Manually registering mouseover to the same callback as longpress seemingly solves the issue.

**Comment by andrewseguin** [comment]
Just tried this on my device by going to material.angular.io - the tooltip appeared with a longpress
