### ISSUE TITLE
stepper: Type 'FormGroup' is not assignable to type 'FormControlLike'

### ISSUE THREAD

**Issue by kKen94** [angular/components#16606]
Is it normal?
![image](https://user-images.githubusercontent.com/46461611/61887235-899b5f80-af01-11e9-84db-5f723bbf0e97.png)

**Comment by andrewseguin** [comment]
Which versions of Angular and Material are you using?

**Comment by kKen94** [comment]
With the 8.2.0 update this error disappear but now i have this 
![image](https://user-images.githubusercontent.com/46461611/62276456-606c5900-b444-11e9-8283-376041f71aee.png)

**Comment by andrewseguin** [comment]
Without having access to your code, it's really difficult to diagnose this. Is the error being thrown from one of your components?

**Comment by Splaktar** [comment]
I'm seeing this when building the dev-app with Ivy as well:
```ts
ERROR: /Users/splaktar/Git/angular/material2/src/dev-app/stepper/BUILD.bazel:5:1: Couldn't build file src/dev-app/stepper/stepper-demo-module.ngfactory.js: Compiling Angular templates (ngtsc - devmode) //src/dev-app/stepper:stepper failed (Exit 1)
src/dev-app/stepper/stepper-demo.html(8,33): error TS2322: Type 'AbstractControl | undefined' is not assignable to type 'FormControlLike | undefined'.
  Type 'AbstractControl' is missing the following properties from type 'FormControlLike': registerOnChange, registerOnDisabledChange
src/dev-app/stepper/stepper-demo.html(26,33): error TS2322: Type 'AbstractControl | undefined' is not assignable to type 'FormControlLike | undefined'.
  Type 'AbstractControl' is not assignable to type 'FormControlLike'.
src/dev-app/stepper/stepper-demo.html(56,13): error TS2739: Type 'FormGroup' is missing the following properties from type 'FormControlLike': registerOnChange, registerOnDisabledChange
src/dev-app/stepper/stepper-demo.html(75,13): error TS2322: Type 'FormGroup' is not assignable to type 'FormControlLike'.
```

**Comment by Splaktar** [comment]
It looks like PR https://github.com/angular/components/pull/16373 has a fix for this.

**Comment by Splaktar** [comment]
@devversion I think that the `FormControlLike` to `AbstractControlLike` changes in PR https://github.com/angular/components/pull/16373 will solve this. I will pull those changes into PR #17392.
