### ISSUE TITLE
MatRipple.launch() coordinates are relative to viewport and not host element, contradicting the documentation.

### ISSUE THREAD

**Issue by simon-mathewson** [angular/components#16613]
#### Documentation Feedback

The description for `MatRipple.launch()` is as follows: 
> Launches a manual ripple at the specified coordinates **within the element**.

However, the coordinates passed are interpreted as relative to the viewport, [as demonstrated here](https://rx0lq.csb.app/). It took me a long time to figure this out, but of course this behavior is intuitive, since in most cases you just pass coordinates from a mouse click event.

Suggested replacement:
> Launches a manual ripple at the specified coordinates **relative to the viewport**.

**Affected documentation page:** [https://material.angular.io/components/ripple/api](https://material.angular.io/components/ripple/api)

**Comment by devversion** [comment]
We should clarify this behavior. The coordinates are not relative to the viewport either. Coordinates are absolute based on the closest parent that has a relative position (based on the stacking context)

**Comment by devversion** [comment]
@simon-mathewson Created a PR to clarify this. I was wrong with my comment above as I assumed (without looking at the code) that we do not offset the ripple container position (which has `position: relative`).

**Comment by simon-mathewson** [comment]
👍
