### ISSUE TITLE
virtual-scroll: get/set scroll position

### ISSUE THREAD

**Issue by Ploppy3** [angular/components#16612]
#### Feature Description

Possibility to get and set the scroll position of the virtual scroll component

#### Use Case

I could restore the scroll position when the user gets back to the page.

**Comment by shanehsu** [comment]
Hi, If you use `CdkVirtualScrollViewport`, I believe there are methods for that:

`measureScrollOffset` and `scrollTo`

https://material.angular.io/cdk/scrolling/api#CdkScrollable
https://material.angular.io/cdk/scrolling/api#CdkVirtualScrollViewport

**Comment by Ploppy3** [comment]
@shanehsu is that new? I'm pretty sure I checked this. I will confirm if it works next week.

**Comment by shanehsu** [comment]
@Ploppy3 I am not sure about whether they are new. But scroll strategies use these methods in order to calculate what range to render in the viewport, I have worked on a custom strategy for my app, I’m pretty sure they work fine!

Hope it helps :)

**Comment by Ploppy3** [comment]
@shanehsu It works, thank you.
