### ISSUE TITLE
virtual scroll mat-radio or input type radio selecting multiple radio buttons, need to select only one

### ISSUE THREAD

**Issue by gauravkhare1783** [angular/components#16626]
#### Reproduction

https://stackblitz.com/angular/dlaykeobbkd?file=app%2Fcdk-virtual-scroll-overview-example.ts

Sorry i am new to git and stackblitz so not able to put exact code in stackblitz. Problem is that i am trying to use radio button inside virtual scrolling but more then 1 radio button is getting selected i dont know why. i need to select 1 radio button at a time. can any one help
Steps to reproduce:
1. I have given stackblitz link above. Please open it and put code "input type radio" with same name  inside cdk-virtual-scroll-overview-example.html file. inside CDKForLoop
2. then select 1 radio button and scroll. You will see multiple radio buttons are selected. 
 
 
#### Expected Behavior

Only 1 radio button should be selected at a time .

#### Actual Behavior

Multiple radio buttons are getting selected i dont know why

#### Environment

- Angular:
- CDK/Material:  angular 7/material
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows
@jelbourn Can you please help on this

**Comment by andrewseguin** [comment]
Can you try creating the example in stackblitz and saving the result so we can diagnose

**Comment by gauravkhare1783** [comment]
I got the solution templatecachesize :0 works for me thanks
