### ISSUE TITLE
Navigation schematic the sidenav is always hidden

### ISSUE THREAD

**Issue by assimhabeek** [angular/components#16628]
#### Reproduction
```
ng generate @angular/material:nav <component-name>

```
 
 
#### Expected Behavior

When the component load first time in a device that doesn't match Handset the sidenav should be opened .

#### Actual Behavior

The sidenav stays closed until we resize the page to match HandSet, only after that the sidenav returns to the expected behavior. 

#### Troubleshooting
component.html
```
// this should return true or false but it is returning null 
(isHandset$ | async) 

```
component.ts

```
   isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
    .pipe(
      map(result => result.matches),
     // we should replace share() with shareReplay(1) to let the new subscribers get the old value.
      share()
    );

```
#### Environment
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "~8.1.1",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.1.2",
    "@angular/material": "^8.1.1",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "angular-webstorage-service": "^1.0.2",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"

**Comment by 4val0v** [comment]
**Similar problem** 🥺

<details>
  <summary>My dependencies:</summary>

```JSON
"dependencies": {
    "@angular/animations": "^8.1.3",
    "@angular/cdk": "^8.1.2",
    "@angular/common": "~8.1.3",
    "@angular/compiler": "~8.1.3",
    "@angular/core": "~8.1.3",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.1.3",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "~8.1.3",
    "@angular/platform-browser-dynamic": "~8.1.3",
    "@angular/router": "~8.1.3",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  }
```
</details>

**Comment by bigozzi-inspect** [comment]
I have the same problem

**Comment by UnDer-7** [comment]
I have the same problem.

**Comment by inkolin** [comment]
**instead of share() use shareReplay()**
`  isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
    .pipe(
      map(result => result.matches),
      shareReplay()
    );`

**Comment by crisbeto** [comment]
Should've been fixed by https://github.com/angular/components/pull/16788.
