### ISSUE TITLE
Slider Component border radius not displaying in safari browser

### ISSUE THREAD

**Issue by dhanarajp** [angular/components#16633]
### Overview
I am trying to apply custom style [Stack  Overflow](https://stackoverflow.com/questions/52339591/style-the-angular-material-slider-so-that-it-is-thicker-taller).

i) Slider component border radius not displaying in **ios** safari browser, 
ii) And first time try to change the slider value, but colour is not continue in the slider. 

This two issue reproducing in safari browser 

**border radius issue**
![slider-issue](https://user-images.githubusercontent.com/22543749/62043603-67b21d80-b21e-11e9-8760-6941d8cd175b.png)

**slider colour not displaying when first time trying to slider**
![slider-issue-1](https://user-images.githubusercontent.com/22543749/62044085-b2806500-b21f-11e9-8d92-dbcb6e028bd9.png)

### Reproduction steps
 -i am trying this customizing the slider

```
.mat-slider.mat-slider-horizontal .mat-slider-wrapper {
  top: 18px;
}
.mat-slider.mat-slider-horizontal .mat-slider-track-wrapper {
  height: 12px;
  border-radius: 10px
}
.mat-slider.mat-slider-horizontal .mat-slider-track-background,
.mat-slider.mat-slider-horizontal .mat-slider-track-fill {
  height: 100%;
}
.mat-slider.mat-slider-horizontal .mat-slider-track-fill {
  background-color: blue;
}
.mat-accent .mat-slider-thumb {
  height: 30px;
  width: 30px;
  background-color: white;
  border: solid 2px gray;
  bottom: -20px;
  right: -20px;
}
.mat-slider-min-value:not(.mat-slider-thumb-label-showing) .mat-slider-thumb {
  background-color: white;
}
```
Example:
for sample reference [[Stackblitz](https://stackblitz.com/edit/angular-cbtsy3?file=styles.css)]

### Version number
     "@angular/material": "^7.0.4",
      "@angular/cli": "~7.0.5",

### Operating system and device
      MAC 10.14.11 Safari version 12.1.1
      Mobile IOS 13 , safari browser

**Comment by crisbeto** [comment]
Since you're applying your own styles on top of ours, it's up to you make it work everywhere. It looks like you probably need to add a `transform: translateZ(0)` to the element that has the border radius.

**Comment by dhanarajp** [comment]
#crisbeto  Agreed i was written on own style for border radius. But in element level dynamically injected the transform properties for applying the colour. so i just added the colors in css level. For your reference, i have attached the video of chrome and safari browser behavior.
So, please advice me, where i have to add transform style properties and how to solve this issue.

![480gif](https://user-images.githubusercontent.com/22543749/62215331-61f63c80-b3c4-11e9-8171-74054f69537e.gif)
