### ISSUE TITLE
cdkDropList has wrong container after scrolling

### ISSUE THREAD

**Issue by janaukema** [angular/components#16648]
#### Reproduction

When there are multiple cdkDropLists on a page and an item from the droplist is dropped on a target container that is only visible after scrolling it into view. The container that is referenced as the target container is not the correct container.

Here is an example in on stackblitz.
https://stackblitz.com/edit/angular-xoxgw2 

Steps to reproduce:
1. Drag an item from a visible container.
2. Scroll to a container that was not visible before.
3. drop the item on the container

 
 
#### Expected Behavior
The target should be dropped on the correct container

#### Environment

- Angular: 8.1.3
- CDK/Material: 8.1.3

**Comment by crisbeto** [comment]
Should've been resolved by https://github.com/angular/components/pull/16681.
