### ISSUE TITLE
Angular drag and drop cdk is not scrolling container when dragging

### ISSUE THREAD

**Issue by fatmaE19** [angular/components#16649]
<!--------

The Angular team can't provide general troubleshooting help. However, the extended community of
users can provide more help: 
I am developping a frontend app in which i am using angular 7.I am using angular cdk for dragging and dropping elements but the problem is when i make a drag the div container is not scrolling.So is there any sollution for that.

this is my html

<div class="col_container" >
  <div class="column" cdkDrag>
    box
  </div>
</div>
this is my css

.col_container {
  height: 300px;
  width: 10%;
  margin: 0 auto;
  padding: 10px;
  background-color: yellow;
  overflow-x: auto;
  overflow-y: auto;
  border-style: solid;
  border-width: 0.1px;
  border-color: black;
}
.column {

  color: blue;
  background-color: azure;
  border-style: solid;
  border-width: 0.1px;
  border-color: black;
  display: inline-block;
  width: 30px;
  margin: 0 6px;
  vertical-align:top;

}
this is my component

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'scrollTestForDragAndDrop';
}
the expected behaviour is when i drag the box to the border the yellow div must scroll

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
