### ISSUE TITLE
Auto hide for toolbar-row

### ISSUE THREAD

**Issue by SvenBudak** [angular/components#16659]
In basicly every WebApp we have a toolbar, and in alot of them we need a "scroll out" effect for single `mat-toolbar-rows`.

I found this tutorial: https://osvaldas.info/examples/auto-hide-sticky-header/?lazy-plus but i was not able to implement this in a clean working way. also the bar feels not smooth here.

it is very important that people can handle it on single toolbar rows not on the whole mat-toolbar.

**Comment by SvenBudak** [comment]
We found a solution that will help maybe some people. Demo: https://header-autohide.netlify.com/home

Here the Code: https://github.com/MurhafSousli/scroll-direction-directive/blob/master/src/app/scroll-direction.directive.ts

I still hope for a better working solution that works on the fly inside material. Because this solution require some manually adding of CSS etc...

**Comment by jelbourn** [comment]
Closing this since we don't plan any really expanding mat-toolbar with further features at this point. We may eventually create a new app-bar component that supersedes the toolbar, but have no immediate plans for it.
