### ISSUE TITLE
cdkDragConstrainPosition throws exception

### ISSUE THREAD

**Issue by PBarnard** [angular/components#16666]
I'm getting the following error when using the cdkDragConstrainPosition directive:

"this.constrainPosition is not a function"

Are there any examples of how to use this directive correctly? I can't find any help with it anywhere.

**Comment by crisbeto** [comment]
Can you post what you have at the moment? The idea is that you pass a function into it.

**Comment by PBarnard** [comment]
I think that's what I need an example of. I don't know what the syntax is for passing a function to a directive :(

**Comment by crisbeto** [comment]
Here's an example from our unit tests https://github.com/angular/components/blob/master/src/cdk/drag-drop/directives/drag.spec.ts#L3994.

**Comment by PBarnard** [comment]
@crisbeto Brilliant, that's what I needed, many thanks :)

**Comment by crisbeto** [comment]
Closing since the input seems to be working as expected.
