### ISSUE TITLE
when MatDialog open a TemplateRef, can support to pass a context?

### ISSUE THREAD

**Issue by rorry121** [angular/components#16665]
#### Feature Description

when MatDialog open a TemplateRef, how to pass data to a template, can support to pass a context?

### code: 
```
  dialogRef: MatDialogRef<any>;
  list = [{
    name: 'banana',
    parent_id: 'fruit'
  },{
    name: 'pumpkin',
    parent_id: 'vegetables'
  },{
    name: 'monkey',
    parent_id: 'Animal'
  }];
  @ViewChild('dialogTemplate') dialogTemplate: TemplateRef<any>;

  constructor(
    private matDialog: MatDialog,
  ) {
  }

  show(item) {
    //   how to pass the item to this.dialogTemplate ?
    this.dialogRef = this.matDialog.open(this.dialogTemplate);
  }
```
```
<ul>
  <li *ngFor="let item of list" (click)="show(item)"></li>
</ul>

<ng-template #dialogTemplate let-item>
  <section class="confirm-dialog">
    <article mat-dialog-title class="mat-dialog-title">
      <span class="text">Tips</span>
      <button mat-dialog-close class="no-padding">
        <i class="dialog-close ico-delete"></i>
      </button>
    </article>
    <article mat-dialog-content>
      <div>I like {{item.name}}</div>
    </article>
    <article mat-dialog-actions>
      <button mat-button class="mat-button" >confirm</button>
      <button mat-button class="mat-button" mat-dialog-close >cancel</button>
    </article>
  </section>
</ng-template>
```
### Now I want to open a Dialog, and pass the item (I clicked ) as a context to the dialogTemplate.
```
overlayRef.attach(new TemplatePortal(templateRef, viewContainerRef, context));
```

**Comment by Airblader** [comment]
This is documented already: https://material.angular.io/components/dialog/overview#sharing-data-with-the-dialog-component-

**Comment by rorry121** [comment]
> This is documented already: https://material.angular.io/components/dialog/overview#sharing-data-with-the-dialog-component-

sorry, this link shows how to share data with a component, and didn't show how to share data with a templateRef.

**Comment by Airblader** [comment]
Ah, sorry, I must've misunderstood.

**Comment by crisbeto** [comment]
The `data` from the dialog config is exposed as the `$implicit` in the template ref:

```html
<ng-template let-yourData">{{yourData}}</ng-template>
```

**Comment by Airblader** [comment]
@crisbeto I think it's a fair point to ask to add this to the documentation, though.

**Comment by rorry121** [comment]
> @crisbeto I think it's a fair point to ask to add this to the documentation, though.

agree！I get it
