### ISSUE TITLE
Documentation is not easy to understand graphicomponents and is poor in examples

### ISSUE THREAD

**Issue by Provoo** [angular/components#16664]
#### Documentation Feedback

Please try to put more examples of the components and how to work around with different layouts, I have been trying two hours to make a floating fab button, in ionic is very easy to set up, but here I'm totally confuse, how to work around with your directives
**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
