### ISSUE TITLE
MatButtonSheet overlay not placed into the specified ViewContainerRef

### ISSUE THREAD

**Issue by matheo** [angular/components#16663]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/bottom-sheet-issue

Steps to reproduce:
1. Use the `MatBottomSheet.open` specifying a `viewContainerRef`.
2. The BottomSheet overlay is not placed into it, but into the document body.
 
#### Expected Behavior

Bottom Sheet overlay placed into the specified `ViewContainerRef`.

#### Actual Behavior

Bottom Sheet overlay placed into the document body.

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2
- Browser(s): Chrome
- Operating System: Ubuntu

**Comment by crisbeto** [comment]
The `ViewContainerRef` only determines where the overlay will be placed in Angular's logical tree. All overlays are still placed in the overlay container.
