### ISSUE TITLE
Nav-list keeps ripple after drag & drop

### ISSUE THREAD

**Issue by LeonSchaffert** [angular/components#16684]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-alpur8

Steps to reproduce:
1. Click and hold on one list item to start drag & drop
2. Move Item anywhere in the list
3. Release while keeping the cursor above the item
4. Repeat 1-3 with the same Item while keeping the cursor above it

 
 
#### Expected Behavior

Item appearance should be the same as before the drag & drop. 

#### Actual Behavior

The ripple stays active after drag & drop. The nav-list item keeps getting darker with each repitition of steps 1-3.

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.1.2
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
I don't think we can do much on our end, because the default preview and placeholder are clones of the original element, which means that they'll have any ripples that were there when the dragging started. You can work around it in your case by hiding the ripples inside a preview or placeholder:

```css
.cdk-drag-placeholder .mat-ripple-element,
.cdk-drag-preview .mat-ripple-element {
  display: none;
}
```
