### ISSUE TITLE
Drag and Drop in case of different size of div 

### ISSUE THREAD

**Issue by manhar-developer** [angular/components#16683]
#### Reproduction

https://stackblitz.com/angular/eqvkdbapyor?file=app%2Fcdk-drag-drop-sorting-example.ts
As per this current example div are being populated from array.

<div cdkDropList class="example-list" (cdkDropListDropped)="drop($event)">
  <div class="example-box" *ngFor="let movie of movies" cdkDrag>{{movie}}</div>
</div>

Is it possible to apply drag and drop on the div (which are angular components indide a div using bootstrap) and not generated through array. 

eg 
<div id="div 1" class="col-md-12"> 
<div id="div 3" class="col-md-10"><div id="div 3" class="col-md-2">  

Or if both div are of same size but not generated using ngFor through array 
like <div id="div 1" class="col-md-12"> 
<div id="div 2" class="col-md-12"> 
 
 
#### Expected Behavior

Apply drag and drop on the separate div not generated/populated through array

#### Actual Behavior
Example (Attached url of stackblitz) shows only for div populated from array using ngFor

#### Environment

- Angular: 8.1.2
- CDK/Material: 8.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows 10

**Comment by crisbeto** [comment]
There's nothing stopping you from doing something like this:

```html
<div cdkDropList class="example-list" (cdkDropListDropped)="drop($event)">
  <div class="example-box" cdkDrag>One</div>
  <div class="example-box" cdkDrag>Two</div>
</div>
```

However you should keep in mind that once it's dropped, it'll be up to you to move the elements around in the DOM, otherwise they'll revert to their initial positions.

**Comment by manhar-developer** [comment]
hi @crisbeto 
As per the example drop function includes array , curr index and prev index. 
As mentioned earlier as well that there is no array of the div as there are angular components. 
So what should I insert in the following function :

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.movies, event.previousIndex, event.currentIndex);
  }
