### ISSUE TITLE
Overriding mat-option font-size breaks the position of mat-select-panel opened by the mat-paginator pagination dropdown

### ISSUE THREAD

**Issue by JesusCarm** [angular/components#16685]
#### Reproduction

https://stackblitz.com/edit/components-issue-nwfm1h

Steps to reproduce:
1. Change mat-option font-size
2. Click the paginator dropdown, select 20
3. Click the paginator dropdown again
 
 
#### Expected Behavior

The options should be close to the select input

#### Actual Behavior

The options position is wrong

![image](https://user-images.githubusercontent.com/10048564/62445013-1ee6f100-b757-11e9-8c6f-81b3d581a5a2.png)

#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
You cannot change the font-size of the options independently of the font-size of the trigger. If you want to change the font-size it should be changed on the containing form field, like this: https://stackblitz.com/edit/angular-ngbgf6?file=src/app/select-custom-trigger-example.html
