### ISSUE TITLE
Creating a custom form field control is overcomplicated

### ISSUE THREAD

**Issue by akopchinskiy** [angular/components#16699]
This documentation describes the topic: https://material.angular.io/guide/creating-a-custom-form-field-control

This:
```ts
@Component({
  ...
  providers: [{provide: MatFormFieldControl, useExisting: MyTelInput}],
})
class MyTelInput implements MatFormFieldControl<MyTel> {
  ...
}
```
Should be:
```ts
@Component({
  ...
})
class MyTelInput extends MatFormFieldControl<MyTel> {
  ...
}
```

This:
```ts
@Input()
get placeholder() {
  return this._placeholder;
}
set placeholder(plh) {
  this._placeholder = plh;
  this.stateChanges.next();
}
private _placeholder: string;
```
```html
<input [placeholder]="_placeholder">
```
Should be:
```ts
@Input() placeholder: string
```
```html
<input [placeholder]="placeholder">
```

And so on...

**Comment by mmalerba** [comment]
I think the specific example you listed does need the setter, so it can emit on the `stateChanges` observable. There are other ways that could be handled (i.e. do it in `ngOnChanges`), but the code is not there for no reason.

That said if someone wants to take a stab at simplifying this guide I'd be happy to take a look

**Comment by dario-collavini** [comment]
The documentation also seems to refer to an old codebase, for example:
`stateChanges = new Subject<void>();`  

But for 9.2.4 stateChanges is reported as an Observable:
`readonly stateChanges: Observable<void>;`

**Comment by akopchinskiy** [comment]
@dario-collavini 
> The documentation also seems to refer to an old codebase
Oh, really? Look at the original post's date.

**Comment by dario-collavini** [comment]
> @dario-collavini
> 
> > The documentation also seems to refer to an old codebase
> 
> Oh, really? Look at the original post's date.

Is your reply supposed to be of help? I just wanted to highlight that on the REFERENCE doc site material.angular.io v9.2.4 the documentation is not only cumbersome as you stated, but also out of date, so it is not just a matter of syntax refactoring.

**Comment by mmalerba** [comment]
you can assign `Subject<void>` to `readonly Observable<void>`, `Subject` implements the `Observable` interface

**Comment by nthornton2010** [comment]
I'm attempting to follow the out-of-date guide now and feel that the MatFormFieldControl abstract class should either be switched back to an interface or the properties in the class all be made abstract as well. Them not being abstract implies that they would "just work" as is, but based on the guide, that's not true for most of them as they need to do things like triggering the stateChanges observable, etc. The only benefit to it being a class would be if the logic that we need to manually write were to be moved into the class (like the special setters or the instance of stateChanges, etc) but that's not currently done.

Also (and not sure if it being an interface would fix this) but if you try to override the existing properties with getters/setters results in VS Code showing an error. Here's the error I get when doing this with the value input: "'value' is defined as a property in class 'MatFormFieldControl<Number>', but is overridden here in 'CustomInputComponent' as an accessor.ts(2611)" - adding //@ts-ignore does get around this, however devs shouldn't need to add that everytime they implement/extend this.

Overall, I agree that creating a custom form field is over-complicated.

**Comment by mmalerba** [comment]
Closing this issue as all of the specific examples pointed to above are not over-complication, but are in fact necessary for the example to work properly
