### ISSUE TITLE
Menu: Click at the beginning or the end of the disabled menu item does not close the menu

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/components#16694]
#### Reproduction

Reproducible right in the [documentation](https://material.angular.io/components/menu/examples) in  _Menu with icons_ example

Steps to reproduce:
1. Open a menu with disabled item and click at the edge of such item (green areas in the attached picture)
2. See that the menu doesn't close

![menudisableditemclick](https://user-images.githubusercontent.com/33349795/62517188-1fe75380-b827-11e9-8f4e-572b6ccb1173.PNG)
 
#### Expected Behavior

When one clicks at the edge of disabled menu item, the menu should close same as it closes when one clicks in the middle of disabled menu item.

#### Actual Behavior

The menu doesn't close when someone clicks at the edge of disabled menu item

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): tested on Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): tested on Win10

**Comment by Totati** [comment]
It will close when you exactly click on text or icon. Above, below, between won't close it either.
