### ISSUE TITLE
Drag drop on top of list item

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#16702]
#### Feature Description

Use `cdkDropList` to drop an item on top of another `cdkDropList` item, rather than sorting a way to add it. It can be thought of as `cdkDropListMode='switch|over`.

#### Use Case

This enables pairing one list item(s) to a second list specific item, a behaviour different from the default sorting of `cdkDropList`.
In current way things work, setting `cdkDropListSortingDisabled` will prevent droping on to of a `cdkDrop` item, and event index will always be zero.

The new 'over' option of the `cdkDropListMode` can return the item being targeting index on `cdkDropListDropped` event.
It is useful in cases where drag and drop is used to assign an item with some options (demo below).

In addition, it makes sense that in such scenario, the item will be cloned, rather than being moved. This can be thought of as `cdkDragClone` on `cdkDrag` item.

Thanks

**Comment by zehavibarak** [comment]
This is an email-like app, showing items and custom tags.
![image](https://user-images.githubusercontent.com/2478096/62568715-6b851600-b896-11e9-9e65-20ded81c8e28.png)
I need to be able to know on which `target` _item_ the user dragged a _tag_.

**Comment by LanderBeeuwsaert** [comment]
I have almost exactly the same feature request, where I would want to be able to drop items from list A in between the items from list B (so the existing behaviour) BUT when drag/dropping items from list B into list A, it should drag/drop the listItem on TOP of a listItem in list A.

The logic is that list A is a list with a fixed schedule, each listItem there is a time-duration.
Each listItem/time-duration of list A can be filled with a person/group.
So the moment you're drag/dropping from list A to list B, you're 'unassigning' a person from that time-duration and putting the person in a waiting area.
Later you're going to want to re-assign a person out of list B to a certain duration in List A.

At the moment I can have a cdkDropListConnectedTo between the two lists but that will enable the animation but let me fire the correct dropEvents
OR
I can remove the cdkDropListConnectedTo. That will disable the animation, but when I drop, it will animate like it's going back to list B and the dropEvent will have the targetContainer & targetIndex from that list.
It should also be possible to re-arrange the persons in list A (so basically reassign people to different time-durations) so when dragging a listItem from list A, it should animate the list A.

In essence it would mean that the sorting/between animation should be disabled when drag/dropping from list B to list A & should fire a cdkDragDropEvent when dropping the item + in the event say on which index in list A it was dropped.
So this means that the delta with what exists today would be to be able to disable the animation in a list based on certain conditions but still keep the event firing working.

Voilà, long-winded explanation (apologies), hope it is clear :)

**Comment by crisbeto** [comment]
Sorry for the (very) delayed response. I'm not sure I totally understand what the request is here. Is it to add information about what item the user was hovering over when they dropped something? As for cloning support, it should be covered by https://github.com/angular/components/issues/13906.

**Comment by julianobrasil** [comment]
@zehavibarak, have you tried to achieve this effect by setting the cdkDropList element (the list container) with `position="relative"` and the placeholder with `position="absolute"; top: 0`? I remember doing that somewhere together with some `opacity` setting and if I remember it right it was an acceptable workaround.

**Comment by crisbeto** [comment]
Closing since there haven't been any responses to the clarifying question in a long time.

**Comment by julianobrasil** [comment]
@crisbeto, I think this is a pretty common case. Can we keep this opened?
