### ISSUE TITLE
MatSort is not working inside MatTabs lazyload tabs content

### ISSUE THREAD

**Issue by Manivannandurairaj** [angular/components#16705]
## Angular Material MatSort is not working inside MatTabs Lazy Load content:

# Sample project stackblitz url
#### Detailed Reproduction Steps: 
1. Run the app and sort the give table content
1. 

### What is the expected behavior?
Sort Need to be work inside tabs layload tabs content

### What is the current behavior?
MatSort is not working inside layload tabs content

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 8.2.0.
- Angular Material: 8.1.2.
- OS: Windows
- Browsers: Chrome

**Comment by andrewseguin** [comment]
If you debug your ngOnInit, youll see that you are not passing the MatSort to the datasource. This is because the ViewChild incorrectly marks it as static. Youll want to change it so that the MatSort is set after the view is initialized and you are sure the table is in the view
