### ISSUE TITLE
Drag and Drop in case of angular component not generated through array or not using ngFor

### ISSUE THREAD

**Issue by rizzhaider** [angular/components#16714]
Is it possible to apply drag and drop on the div (which are angular components inside a div using bootstrap) and not generated through array. Or if both div are of same size but not generated using ngFor through array.

Expected Behavior
Apply drag and drop on the separate div not generated/populated through array. 
i am able to drag but facing an issue while drop.
i am not able to drop.

i am doing this...
   <div cdkDropList class="example-list" (cdkDropListDropped)="drop($event)">
              <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 example-box"  cdkDrag ">                 
                      <app-one-component></app-one-component>                  
              </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 example-box" cdkDrag>             
                     <app-two-component></app-two-component>        
             </div>

          </div>

**Comment by crisbeto** [comment]
Yes, you can put `cdkDrag` and `cdkDrop`, even if you aren't using `ngFor`, however in the dropped event it'll be up to you to swap the places of the DOM nodes.
