### ISSUE TITLE
Datepicker: how to get current format

### ISSUE THREAD

**Issue by DannyBoyNg** [angular/components#16716]
#### Feature Description or Question

How to get current date format the datepicker is using? for example:  mm/dd/yyyy

#### Use Case

I would like to show the user the date format in or next to the input box. I know how to import another Locale and the datepicker automatically uses the right date format, but I would also like to display this date format to the user.

So if I changed the Locale to localeNl, I want the date format that is displayed to the user to show dd-mm-yyyy instead of mm/dd/yyyy. Sometimes a user doesn't use the datepicker and manually enters the date. I just want the user to know which format to use.

**Comment by mmalerba** [comment]
You can get the current `MatDateFormats` object by injecting it, that won't necessarily be in human readable format though (e.g. https://stackblitz.com/edit/angular-kgtnrw?file=src/app/datepicker-overview-example.html).

Converting it to human readable format isn't a feature we plan to add. It's outside the scope of Angular Material as it depends on the particular `Date` implementation you're using and the kind of formats that implementation deals with
