### ISSUE TITLE
cdkDropListEnterPredicate access 'this'

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#16718]
#### Feature Description

`cdkDropListEnterPredicate` should be able to access _this_.
Issue repeats for `displayWith` of `MatAutoComplete`.

#### Use Case

Calling this functions should the send the component scope, so function can access local variables of the component to determine return value.

**Comment by zehavibarak** [comment]
Optionaly, it should return an Observable for async result.

**Comment by crisbeto** [comment]
You can define your predicate as an arrow function:

```
class AppComponent {
  predicate = (drag: DragRef, drop: DropListRef) => {
    // do things with `this` and return a boolean
  }
```
