### ISSUE TITLE
Use drag and drop to switch items between arrays

### ISSUE THREAD

**Issue by prom00** [angular/components#16711]
Hello all,

I was hoping someone could help us with fixing our visual issue.

#### What are you trying to do?
We have a grid based screen, for example 8x6 cells.
While dragging we want to switch positions from the dragged from and dropped to position.

Example:
1.2 = (row 1 column 2)
2.3 = (row 2 column 3)

If we drag 1.2 to 2.3, all items in row 2 after column 3 are shifted to the right. After a drop detected with (cdkDropListDropped) on the cdkDropList element, we detect if the item is dropped inside the current row, or a new row.
Then we use either moveItemInArray or transferArrayItem to recreate the arrays. 

The problem with this, is while you are dragging, the items move to the right. This causes the grid (normally 6 width) to be 7 width for a moment. We want to prevent this. 

If we use cdkDropListExited and cdkDropListEntered, we can see which item is being dragged to where and remove an item from the array. This doesn't work, as it stops dragging while changing the array. This makes us only able to move an item to 1 row below or above at a time.

So we don't want the default behaviour where you move an item to another array, but we want to "trade" items, where they replace eachother. The trading is already arranged after dropping, but we want the user to feel the same way while dragging the item.

Thanks in advance for your help!

JSON data used to generate the grid:
`{
    "layout": [
        {
            "id": 1,
            "column": [
                {
                    "id": 1,
                    "pluId": 2401,
                    "color": 12,
                    "text": "<br><br>2401"
                },
                {
                    "id": 2,
                    "pluId": 2402,
                    "color": 12,
                    "text": "<br><br>2402"
                },
                {
                    "id": 3,
                    "pluId": 2403,
                    "color": 12,
                    "text": "<br><br>2403"
                },
                {
                    "id": 4,
                    "pluId": 2404,
                    "color": 12,
                    "text": "<br><br>2404"
                },
                {
                    "id": 5,
                    "pluId": 2405,
                    "color": 12,
                    "text": "<br><br>2405"
                },
                {
                    "id": 6,
                    "pluId": 2406,
                    "color": 12,
                    "text": "<br><br>2406"
                }
            ]
        },
        {
            "id": 2,
            "column": [
                {
                    "id": 7,
                    "pluId": 2407,
                    "color": 20,
                    "text": "<br><br>2407"
                },
                {
                    "id": 8,
                    "pluId": 2408,
                    "color": 20,
                    "text": "<br><br>2408"
                },
                {
                    "id": 9,
                    "pluId": 2409,
                    "color": 20,
                    "text": "<br><br>2409"
                },
                {
                    "id": 10,
                    "pluId": 2410,
                    "color": 20,
                    "text": "<br><br>2410"
                },
                {
                    "id": 11,
                    "pluId": 2411,
                    "color": 20,
                    "text": "<br><br>2411"
                },
                {
                    "id": 12,
                    "pluId": 2412,
                    "color": 20,
                    "text": "<br><br>2412"
                }
            ]
        },
        {
            "id": 3,
            "column": [
                {
                    "id": 13,
                    "pluId": 2413,
                    "color": 5,
                    "text": "<br><br>2413"
                },
                {
                    "id": 14,
                    "pluId": 2414,
                    "color": 5,
                    "text": "<br><br>2414"
                },
                {
                    "id": 15,
                    "pluId": 2415,
                    "color": 5,
                    "text": "<br><br>2415"
                },
                {
                    "id": 16,
                    "pluId": 2416,
                    "color": 5,
                    "text": "<br><br>2416"
                },
                {
                    "id": 17,
                    "pluId": 2417,
                    "color": 5,
                    "text": "<br><br>2417"
                },
                {
                    "id": 18,
                    "pluId": 2418,
                    "color": 5,
                    "text": "<br><br>2418"
                }
            ]
        },
        {
            "id": 4,
            "column": [
                {
                    "id": 19,
                    "pluId": 2419,
                    "color": 19,
                    "text": "<br><br>2419"
                },
                {
                    "id": 20,
                    "pluId": 2420,
                    "color": 19,
                    "text": "<br><br>2420"
                },
                {
                    "id": 21,
                    "pluId": 2421,
                    "color": 19,
                    "text": "<br><br>2421"
                },
                {
                    "id": 22,
                    "pluId": 2422,
                    "color": 19,
                    "text": "<br><br>2422"
                },
                {
                    "id": 23,
                    "pluId": 2423,
                    "color": 19,
                    "text": "<br><br>2423"
                },
                {
                    "id": 24,
                    "pluId": 2424,
                    "color": 19,
                    "text": "<br><br>2424"
                }
            ]
        },
        {
            "id": 5,
            "column": [
                {
                    "id": 25,
                    "pluId": 2425,
                    "color": 19,
                    "text": "<br><br>2425"
                },
                {
                    "id": 26,
                    "pluId": 2426,
                    "color": 19,
                    "text": "<br><br>2426"
                },
                {
                    "id": 27,
                    "pluId": 2427,
                    "color": 19,
                    "text": "<br><br>2427"
                },
                {
                    "id": 28,
                    "pluId": 2428,
                    "color": 19,
                    "text": "<br><br>2428"
                },
                {
                    "id": 29,
                    "pluId": 2429,
                    "color": 19,
                    "text": "<br><br>2429"
                },
                {
                    "id": 30,
                    "pluId": 2430,
                    "color": 19,
                    "text": "<br><br>2430"
                }
            ]
        },
        {
            "id": 6,
            "column": [
                {
                    "id": 31,
                    "pluId": 2431,
                    "color": 9,
                    "text": "<br><br>2431"
                },
                {
                    "id": 32,
                    "pluId": 2432,
                    "color": 9,
                    "text": "<br><br>2432"
                },
                {
                    "id": 33,
                    "pluId": 2433,
                    "color": 9,
                    "text": "<br><br>2433"
                },
                {
                    "id": 34,
                    "pluId": 2434,
                    "color": 9,
                    "text": "<br><br>2434"
                },
                {
                    "id": 35,
                    "pluId": 2435,
                    "color": 9,
                    "text": "<br><br>2435"
                },
                {
                    "id": 36,
                    "pluId": 2436,
                    "color": 9,
                    "text": "<br><br>2436"
                }
            ]
        },
        {
            "id": 7,
            "column": [
                {
                    "id": 37,
                    "pluId": 2437,
                    "color": 9,
                    "text": "<br><br>2437"
                },
                {
                    "id": 38,
                    "pluId": 2438,
                    "color": 9,
                    "text": "<br><br>2438"
                },
                {
                    "id": 39,
                    "pluId": 2439,
                    "color": 9,
                    "text": "<br><br>2439"
                },
                {
                    "id": 40,
                    "pluId": 2440,
                    "color": 9,
                    "text": "<br><br>2440"
                },
                {
                    "id": 41,
                    "pluId": 2441,
                    "color": 9,
                    "text": "<br><br>2441"
                },
                {
                    "id": 42,
                    "pluId": null,
                    "color": 9,
                    "text": ""
                }
            ]
        },
        {
            "id": 8,
            "column": [
                {
                    "id": 43,
                    "pluId": 2443,
                    "color": 9,
                    "text": "<br><br>2443"
                },
                {
                    "id": 44,
                    "pluId": 2444,
                    "color": 9,
                    "text": "<br><br>2444"
                },
                {
                    "id": 45,
                    "pluId": 2445,
                    "color": 9,
                    "text": "<br><br>2445"
                },
                {
                    "id": 46,
                    "pluId": 2446,
                    "color": 9,
                    "text": "<br><br>2446"
                },
                {
                    "id": 47,
                    "pluId": 2447,
                    "color": 9,
                    "text": "<br><br>2447"
                },
                {
                    "id": 48,
                    "pluId": null,
                    "color": 9,
                    "text": ""
                }
            ]
        }
    ]
}`

  
#### Environment

- Angular: Latest
- CDK/Material: Latest
- Browser(s): Chrome

**Comment by crisbeto** [comment]
@prom00 I'm not exactly sure what the issue is here. Can you post an example of the code that you're using?

**Comment by prom00** [comment]
Hi @crisbeto. Thank you for your time reading this.

I've summed up some parts below. Hope this clears it up a bit.

**Before dragging**
![screen](https://user-images.githubusercontent.com/46184489/63323239-9440ed00-c325-11e9-8255-765ed376194a.png)

**While dragging**
![dragging](https://user-images.githubusercontent.com/46184489/63323238-93a85680-c325-11e9-8875-b10b37e34f3e.png)

**After dropping**
![dropped](https://user-images.githubusercontent.com/46184489/63323336-d0744d80-c325-11e9-8c79-a26882e34db3.png)

While dragging item 2406 tot position 2412, we want the item on position 2412 to be replaced with 2406. Item 2406 should be replaced by 2412. However while dragging, you see item 2412 shifting to the right. After dropping, I transfer the items from one array to another, then everything looks fine again. Yet while dragging, the shifting looks kinda weird.

I've also tried using the cdkDropListExited() and cdkDropListEntered() functions. While entering another droplist I tried transfering the items from array, this however gives an error while doing this. This causes the drag to immediately return an error and stop the dragging animation. The transfer works fine, but when you want to transfer an item across multiple rows, you need to drag it from row 1 to 2, from 2 to 3, and 3 to 4. 

```
polyfills.1d085f2f6dd3cd5ef6d0.js:1 Uncaught TypeError: Cannot read property '_sortItem' of undefined
    at t._updateActiveDropContainer (main.54052263792432cbeeb4.js:1)
    at n._pointerMove [as _next] (main.54052263792432cbeeb4.js:1)
    at n.__tryOrUnsub (main.54052263792432cbeeb4.js:1)
    at n.next (main.54052263792432cbeeb4.js:1)
    at n._next (main.54052263792432cbeeb4.js:1)
    at n.next (main.54052263792432cbeeb4.js:1)
    at n.next (main.54052263792432cbeeb4.js:1)
    at HTMLDocument.handler (main.54052263792432cbeeb4.js:1)
    at t.invokeTask (polyfills.1d085f2f6dd3cd5ef6d0.js:1)
    at e.runTask (polyfills.1d085f2f6dd3cd5ef6d0.js:1)
```
This error is kind of logic, because I'm messing with the array, while the drag and drop is still active (user is still holding the mouse button)



**The layout used:**
```
<table>
  <tbody>
	<tr id="{{indexRow}}" *ngFor="let row of layout; let indexRow = index;"
		style="height: 70px; font-size: 10pt" class="text-center" cdkDropList
		(cdkDropListDropped)="drop($event, indexRow, true)" cdkDropListOrientation="horizontal"
		(cdkDropListExited)="from($event)" (cdkDropListEntered)="to($event)">
	  <td cdkDrag *ngFor="let field of row.column; let indexColumn = index;" class="cursor-pointer"
		style="width: 100px; border: 1px solid; height: 70px; padding: 0px; margin: 0px; position: relative;"
		[ngStyle]="{'border': '1px solid #000000', 'color' : productColors | filterPipeTextColorById : field.color, 'background-color': productColors | filterPipeBackgroundColorById : field.color}"
		[ngClass]="selected.product == field.id ? 'active' : ''"
		(click)="setProduct(field.id, field.pluId, indexRow, indexColumn); saveColor(field.id, indexRow, indexColumn );"
		id="{{indexRow}}_{{indexColumn}}">
		<span *ngIf="field.pluId" [innerHtml]="field.text"></span>
		<span *ngIf="!field.pluId">
		  <br>
		  <fa-icon [icon]="faPlus" size=""></fa-icon>
		  <br>
		</span>
		<span class="pl-2 float-left align-bottom cursor-move" cdkDragHandle>
		  <fa-icon [icon]="faGripVertical" class="mr-2"></fa-icon>
		</span>
	  </td>
	</tr>
  </tbody>
</table>
```

**Functions used:**
```
drop(event: CdkDragDrop<string[]>, indexCardGroup, internal?) {

    let previousCardGroupIndex = event.previousContainer.id;
    let newCardGroupIndex = event.container.id;

    // Some debug info
    // Row
    //console.log(event.container.id);
    // Column 
    // console.log(event.currentIndex);

    /*
    if (this.hiddenItem) {
      document.getElementById(this.hiddenItem).style.display = "block";
    }
    */

    // Drop from product overview
    if (event.item.element.nativeElement.id && internal != true) {
      this.products[event.container.id].column[event.currentIndex].pluId = Number(event.item.element.nativeElement.id);
    } else {
      // Transfer from group to another and reposition
      if (previousCardGroupIndex != newCardGroupIndex) {
        // Transfer the dragged item to the new row
        transferArrayItem(this.products[event.previousContainer.id].column, this.products[event.container.id].column, event.previousIndex, event.currentIndex);

        // Transfer the item that was on the dropped position to the array where the dropped item came from
        transferArrayItem(this.products[event.container.id].column, this.products[event.previousContainer.id].column, event.currentIndex + 1, event.previousIndex);
      } else {
        // Move the item inside the row (the same array)
        moveItemInArray(this.products[indexCardGroup].column, event.previousIndex, event.currentIndex);
      }
    }
    this.saveLayout();
  }
```

**Debug functions**
```
 from(event: CdkDragExit) {
    this.dragDropSwitch.from = {};
    this.dragDropSwitch.from.event = event;
    this.dragDropSwitch.from.rowId = event.container.id;
    this.dragDropSwitch.from.columnId = event.item.element.nativeElement.id;
  }

  to(event: CdkDragEnter<string[]>) {
    this.dragDropSwitch.to = {};
    this.dragDropSwitch.to.event = event;
    this.dragDropSwitch.to.rowId = event.container.id;
    this.dragDropSwitch.to.columnId = event.item.element.nativeElement.id;
}
```

**Other functions used for other part of the application, nothing interesting here**
```
setProduct();
saveColor();
```

**Comment by andrewseguin** [comment]
Sorry for the delay in providing help with this - we are currently limited on resources for troubleshooting issues. You will probably have better luck getting help if you post on StackOverflow.
