### ISSUE TITLE
MatInput autofocus only applies on first view of page?

### ISSUE THREAD

**Issue by WHairstonLOI** [angular/components#16727]
#### Bug, feature request, or proposal:
Possible bug? Not sure - I'm a noob to Angular.

#### What is the expected behavior?
Autofocus should apply to the matInput field every time the page loads.

#### What is the current behavior?
Adding autofocus to a matInput field only focuses the field the first time the page is loaded. Subsequent loads of the page ignore the autofocus; the matInput field still functions, but does not automatically receive the focus.

#### What are the steps to reproduce?
Create a two-page app. One page contains a matInput with autofocus decorator. The first time that page is viewed in the app, autofocus applies to the field. Navigate to the other page, then return to the first page - autofocus no longer applies.

#### What is the use-case or motivation for changing an existing behavior?
UI consistency

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8.1.2, Material 8.1.1, Windows 10 v1803, TypeScript 3.4.5, Chrome and Edge

**Comment by crisbeto** [comment]
Closing since the `autofocus` attribute is controlled by the browser, it's not something that we've added in Material.
