### ISSUE TITLE
StaticInjectorError(AppModule)[MatDialogContainer -> MatDialogConfig] -> NullInjectorError: No Provider for MatDialogConfig

### ISSUE THREAD

**Issue by vishesh1king** [angular/components#16721]
![2019-08-08](https://user-images.githubusercontent.com/8725690/62712057-c134fc00-ba17-11e9-818d-e6dffcee3ed2.png)

I get this NullInjectorError when ever i try to open the mat dialog box. It happens only in **IE 11**. In chrome, safari and firefox it works like charm. I have used material dialog box. Below i have mentioned how i open the mat dialog box. I open it in a component whenever necessary.

```
this.dialogRef = this.dialog.open(CommonModalComponent, {
            width: '500px',
            data: {
                modal_title: 'Back to service connections',
                modal_description: 'Are you sure you want to go back to service connections step? All connection data will be reset.',
                modal_action: 'Yes',
                modal_data: 'yes',
            }
        });

        this.dialogRef.afterClosed().subscribe(result => {
            if (result === 'yes') {
                // Do action
            }
        });
```

In my module file i have imported like below,

```
import {MatSelectModule} from '@angular/material/select';
import {MatDialogModule} from '@angular/material/dialog';
import {CommonModalComponent} from './modals/common-modal/common-modal.component';
import {
    MatButtonModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatInputModule,
    MatNativeDateModule, NativeDateAdapter
} from '@angular/material';
@NgModule({
  imports:[
       MatDatepickerModule,
        MatNativeDateModule, MatFormFieldModule, MatInputModule,
        MatButtonModule, SatDatepickerModule, SatNativeDateModule,
        NgxMatSelectSearchModule, MatSelectModule, MatDialogModule
  ]
})
entryComponents: [CommonModalComponent]
```

#### Expected Behavior

It must open the dialog box in IE 11.

#### Actual Behavior

But it throws NullInjector error every time i try to open the dialog box.

#### Environment

Angular CLI: 7.3.8
Node: 11.9.0
Angular: 7.2.12
Browsers
Chrome: 75.0(works)
Firefox: 68.0.1 (works)
IE: 11.22 (Error)
Edge: 38.14(works)

**Comment by mshirey** [comment]
I'm getting this same error in a very similar context.  Did you ever determine what the root cause was?

**Comment by vishesh1king** [comment]
This was a case where the error was "NullInjectorError" for "MatDialogRef". Thus i included it in the modules and this error popped out. I removed all inclusions of mat dialog in app.module.ts and did the following,

1. import {MatDialogModule} from '@angular/material/dialog';
2. Included this MatDialogModule in the module imports.

How it works as usual in IE. Important note: Do not forget to include your dialog component as "entryComponents" in modules.
ex: entryComponents: [CommonComponent]

Hope it helps !
