### ISSUE TITLE
mat-autocomplete with optgroups report n of 0 items in a list when using a screenreader (Accessibility)

### ISSUE THREAD

**Issue by helfrichmichael** [angular/components#16729]
#### Reproduction

Stackblitz: https://stackblitz.com/angular/jepgrkeyqbr?file=app%2Fautocomplete-optgroup-example.ts

Steps to reproduce:
1. Turn your screenreader on on Chrome OS (usually Ctrl + Alt +Z)
2. Navigate/tab to the autocomplete.
3. Once expanded, start scrolling using the arrow keys.
4. Keep track of what the screen reader is announcing.
 
 
#### Expected Behavior

What behavior were you expecting to see?
It should read "**Option Name** List Item x of y". X being the number of the option you are currently hovering on and y being the length of the group of options.

#### Actual Behavior

What behavior did you actually see?
It's reading "**Option Name** List Item n of 0". N being the number of the option in the list. This is inaccessible for users with screen readers since they have no insight to the list size or if they are approaching a new group.

**Screencap of this:** https://imgur.com/a/P7WlHQG

#### Environment

- Angular: 8.2.1
- CDK/Material: 8.1.2
- Browser(s): Chrome 76
- Operating System (e.g. Windows, macOS, Ubuntu): Chrome OS (76.0.3809.90)

**Comment by jelbourn** [comment]
I just tested this with the latest of everything (ChromeVox, material) and the indices are read correctly.
