### ISSUE TITLE
Select - keyboard home button click choose the first option

### ISSUE THREAD

**Issue by Danieliverant** [angular/components#16749]
#### Reproduction

See in Angular Material examples:
https://material.angular.io/components/tooltip/examples

Steps to reproduce:
1. choose an option from the select (don't lose focus).
2. press the Home button on the keyboard.
 
#### Expected Behavior

Default home button behavior - scroll to top of the page.

#### Actual Behavior

The first option of the select being selected.

#### Environment

- Angular: 7.2.13.
- CDK/Material: 7.3.7.
- Browser(s): Chrome.
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu.

**Comment by crisbeto** [comment]
This matches the behavior of the native `select` element which also selects the first option when you press home. Closing since it works as expected.
