### ISSUE TITLE
customize mat-menu-panel panel of Matmenu

### ISSUE THREAD

**Issue by orphen92** [angular/components#16742]
Hello whats is the solution for have my custom style for the mat-menu-panel panel of Matmenu.

i have try this for now:
class
panelClass
backdropClass

the class appears to the mat-menu-panel but i can't add my style because of shadowDom i think.
I don't want to remove view.encapsulation if its possible.

have you a solution for me please?

**Comment by andrewseguin** [comment]
Without setting the view encapsulation to `None`, you'll want to add a custom `class` to the `<mat-menu>` which will show up on the panel. You can then add your custom styles to the global styles sheet using that class selector.

https://stackblitz.com/edit/angular-y3jqzt
