### ISSUE TITLE
mat-tab-nav-bar with many tabs to be scrollable, just like mat-tab-group

### ISSUE THREAD

**Issue by zijianhuang** [angular/components#16752]
#### Feature Description

mat-tab-group provides horizontal scrolling when there are many tabs, and mat-tab-nav-bar should have such behavior as well.

#### Use Case

The same use case with mat-tab-group.

**Comment by crisbeto** [comment]
[This should be supported as of 8.1.0.](https://github.com/angular/components/blob/master/CHANGELOG.md#810-denim-antipode-2019-07-15)

**Comment by zijianhuang** [comment]
Thanks. I had just checked, and apparently mat-tab-nav-bar had tried to create a horizontal scrolling, but somehow failed. I would have some further tests soon. Apparently there is some bug either in my app codes or in the component.

So the label of this issue may be changed to bug or defect.

**Comment by zijianhuang** [comment]
Apparently this is some issue in my app code.
```html
<div fxLayout="row" ...>
	<nav mat-tab-nav-bar>
		<a mat-tab-link
```

After removing `fxLayout="row"`, things had become fine. The removed flex layout attribute is a legacy left over.

@crisbeto , you may close this case.
