### ISSUE TITLE
Menu: click on disabled button does not close the menu in Firefox

### ISSUE THREAD

**Issue by PierreRott** [angular/components#16754]
#### Reproduction

https://stackblitz.com/angular/yvgvkgpqmpy?file=app%2Fmenu-icons-example.ts

Steps to reproduce:
1. open menu
2. click on disabled button
3. check whether the menu is closed or not
 
 
#### Expected Behavior

Menu should close.

#### Actual Behavior

Menu does not close.

#### Environment

Angular CLI: 8.0.3
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

#### Package Version

@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cdk                       8.0.1
@angular/cli                       8.0.3
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

- Browser(s): Firefox 68.0.1
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10 Enterprise

![disabled_option_close](https://user-images.githubusercontent.com/34771265/62865952-0c992400-bd10-11e9-8cb4-cec1bb860797.gif)

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/components/pull/16696.
