### ISSUE TITLE
mat-dialog-actions and mat-card-actions do not have stroked and flat button magin implemented

### ISSUE THREAD

**Issue by Totati** [angular/components#16762]
#### Reproduction

[Demo](https://stackblitz.com/edit/angular-mat-dialog-and-card-actions)
 
#### Expected Behavior

.mat-flat-button and .mat-stroked-button should have the same style of margin like .mat-button and .mat-raised-button when they are placed inside .mat-dialog-actions and .mat-card-actions.

#### Actual Behavior

They don't have any king of margin. 

#### Environment

- Angular: 8.2.2
- CDK/Material: 8.1.2

[Related issue](https://github.com/angular/components/issues/15561) with .mat-stroked-button in .mat-dialog-actions is closed, but the connected merge request is blocked.

**Comment by crisbeto** [comment]
Will be handled by https://github.com/angular/components/pull/11961.

**Comment by crisbeto** [comment]
Closing as fixed by https://github.com/angular/components/pull/11961.

**Comment by Totati** [comment]
@crisbeto are you sure this fixed the issue with the MatCard? Cause in your commit you fixed the dialog alone. In the master branch [card.scss](https://github.com/angular/components/blob/37086fd9502717bb158a7b3351aa8755f0462616/src/material/card/card.scss#L86) file still has the old selectors, not the .mat-button-base.
