### ISSUE TITLE
Angular Material unit testing search filter data?

### ISSUE THREAD

**Issue by Dileep-raja** [angular/components#16765]
applyFilter(filterValue: string) {
    console.log("filter data"+filterValue)
    this.dataSource.filter = filterValue.trim().toLocaleLowerCase();
    if (this.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }

Any help how to write unit test for this function?

**Comment by andrewseguin** [comment]
Closing since this does not follow the issue template.
