### ISSUE TITLE
ng-add: option to set up typography styles for native elements

### ISSUE THREAD

**Issue by TimoPot** [angular/components#16776]
#### Reproduction

Steps to reproduce:
1.  create new angular app
2.  do: ng add @angluar/material
result:
added 3 packages from 4 contributors in 15.766s
UPDATE src/main.ts (391 bytes)
UPDATE src/app/app.module.ts (577 bytes)
UPDATE angular.json (3608 bytes)
UPDATE src/index.html (490 bytes)
UPDATE src/styles.css (181 bytes)

4. notice that in index.html the fonts links are added but the body tag has no class
 
 
#### Expected Behavior
The schematic should add class="mat-typography" to the body tag in index.html

#### Actual Behavior
The schematic changes the index.html to add font links but did not change the body tag

#### Environment

- Angular: 8.1.1
- CDK/Material: 8.1.1
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Totati** [comment]
In the [documentation ](https://material.angular.io/guide/typography#usage) this is mentioned.

**Comment by TimoPot** [comment]
Yes you’re correct. 
But the schematic does all the steps in the documentation to except this step.
And if a user is not aware of that then no typography is applied and the user wont know why.

**Comment by devversion** [comment]
@jelbourn Do we actually want to do this as part of `ng add`. How about adding an option (with prompt) for this?

**Comment by jelbourn** [comment]
Seems reasonable as a prompt in `ng add`.

**Comment by LayZeeDK** [comment]
In `@angular/material@9.0-rc.8`, this prompt is here:

>? Set up global Angular Material typography styles?

but the `mat-typography` class is added to the `body` tag no matter what we answer.

**Comment by LayZeeDK** [comment]
⬆️ @crisbeto
