### ISSUE TITLE
CDK Overlay not calling the detach event while using CloseScrollStrategy

### ISSUE THREAD

**Issue by aryaroudi** [angular/components#16779]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-jfzhcl

Steps to reproduce:
1. Open the menu do the scroll, menu get closed and now you need to click 2 times on the button to open the menu again
 
 
#### Expected Behavior

What behavior were you expecting to see?

the `detach` output should be called to close the menu correctly.

#### Actual Behavior

What behavior did you actually see?

The `detach` output never call the close function that I sent in when the menu gets closed by doing the scroll

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/components/pull/7950.

**Comment by aryaroudi** [comment]
thanks @crisbeto waiting for the merge 👍

**Comment by vanrado** [comment]
Thanks for initiative to fix that, but it seems that fix is still not merged. Is there any easy workaround? I would use close scroll strategy. One workaround could be create custom listener/observer on scrollevent, but I prefer to use more "Angular way"... Thanks
