### ISSUE TITLE
Wrapped disabled button remains clickable

### ISSUE THREAD

**Issue by igor-pavlichenko** [angular/components#16777]
So I'm creating wrapper components around material buttons to customise and set a default behaviour and I've ran into a problem:
If I disable the button but assign a (click) to the wrapper element - it gets triggered if I click on the text of the button.

Interestingly enough, if I also assign a click event to the inner button - that event isn't triggered, but the click assigned to the wrapping element does.

#### Reproduction

https://stackblitz.com/edit/angular-qtexwb

Steps to reproduce:
1. create a **my-button** component to wrap any mat-button
2. disable the button
3. assign a click event handler (with a console.log or something like that) to the wrapper component **my-button**
4. try clicking the button and then the label/text of that button
 
 
#### Expected Behavior

No clicks should be triggered

#### Actual Behavior

When clicking on the **text/label** of the button - the **my-button** click event is triggered

#### Environment

- Angular: 8.2.2
- CDK/Material: 8.1.2
- Browser(s): Chrome 76.0.3809.100 (also happens in opera which is chromium based, but not in firefox)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Mojave 10.14.6

**Comment by andrewseguin** [comment]
This happens when the click event is triggered on an inner container and the click event listener is on an outer container: https://stackblitz.com/edit/angular-qtexwb-asveka?file=main.ts

**Comment by andrewseguin** [comment]
Since this happens with a standard HTML element, we'd prefer not to change this "expected" behavior. However, this issue's action can be that we add in a note (markdown, comments, etc) that documents this behavior.

**Comment by igor-pavlichenko** [comment]
This isn't expected at all, when I disable an element I expect nothing inside of it to be clickable.
Is it an Angular problem, or is it Chromium's problem? Point me a direction where I should report it.

For now, as a workaround I had to add a click listener to the inner wrapper and .stopPropagation() & .preventDefault() on it.. this doesn't feel like an elegant solution, more like an ugly hack.

**Comment by andrewseguin** [comment]
I agree it's not expected. I see that this is the same in Safari, but in Firefox the event is not propagated. I suspect this stems from an older set of code in webkit. We have no plans to normalize this behavior. You could file an issue with Webkit and Blink but I don't suspect this behavior will be changed since it's been around for a long time
