### ISSUE TITLE
Render Component inside mat Dialog not working

### ISSUE THREAD

**Issue by GlauberF** [angular/components#16786]
#### Reproduction
I need to dynamically pass a component into a dialog and it must be rendered.

I have an object, with several components, example:
```javascript
{
        title: 'Vimbo Countdown',
        content: `<vimbo-countdown eventDate="2040-07-28"></vimbo-countdown>`
}
```

When the user clicks on the title, he opens a dialog and renders what is inside the content.
it is including in html, but not rendering, as if it does not understand the component.

my dialog html:
```html
<div class="dialog-content-wrapper">

    <mat-toolbar matDialogTitle class="mat-accent m-0">
        <mat-toolbar-row>
            <span class="title dialog-title">{{title}}</span>
        </mat-toolbar-row>
    </mat-toolbar>

    <div mat-dialog-content class="p-24 m-0" vimboPerfectScrollbar>
        <div [innerHTML]="content"></div>
    </div>

    <div mat-dialog-actions class="m-0 p-16" fxLayout="row" fxLayoutAlign="end center">
        <button mat-button (click)="matDialogRef.close()" class="mat-accent" aria-label="Close">
            CLOSE
        </button>
    </div>

</div>
```

my dialog component:
```javascript
import { Component, ViewEncapsulation, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Component({
    selector: 'developer-knowledge-base-article',
    templateUrl: './article.component.html',
    styleUrls: ['./article.component.scss'],
    encapsulation: ViewEncapsulation.None
})
export class KnowledgeBaseArticleComponent {

    public content: SafeHtml;
    public title: SafeHtml;

    /**
     * Constructor
     *
     * @param {MatDialogRef<KnowledgeBaseArticleComponent>} matDialogRef
     * @param {MAT_DIALOG_DATA}_data
     * @param {DomSanitizer} domSanitizer
     */
    constructor(
        public matDialogRef: MatDialogRef<KnowledgeBaseArticleComponent>,
        @Inject(MAT_DIALOG_DATA) public _data: any,
        private domSanitizer: DomSanitizer
    ) {
        console.log(_data);
        this.content = this.domSanitizer.bypassSecurityTrustHtml(_data.article.content);
        this.title = _data.article.title;
    }
}
```

In the html dialog, inspecting is appearing, but it doesn't work, like anywhere else in the app
![Captura de Tela_selecionar área_20190814200309](https://user-images.githubusercontent.com/11314585/63062238-8d058380-bece-11e9-9daa-cf71fe924acc.png)

if it had rendered correctly, the html would look something like the image below.
![Captura de Tela_selecionar área_20190814200415](https://user-images.githubusercontent.com/11314585/63062291-b4f4e700-bece-11e9-8921-3ea2ec19ddf2.png)

and the component, I'm important at the root of the module
```javascript
@NgModule({
    declarations: [
        DeveloperKnowledgeBaseComponent,
        KnowledgeBaseArticleComponent
    ],
    imports: [
        RouterModule.forChild(routes),

        MatButtonModule,
        MatDialogModule,
        MatIconModule,
        MatListModule,
        MatToolbarModule,

        VimboSharedModule,

        VimboCountdownModule,
        VimboHighlightModule
    ],
    providers: [DeveloperKnowledgeBaseService],
    entryComponents: [
        KnowledgeBaseArticleComponent
    ]
})
```

**Comment by KumVishal** [comment]
Hi,

You can add component dynamic in the dialogue box by using angular component factory resolver and a directive.

Steps:

.Create a directive with view container ref injected in the constructor of this directive.
.Use ng template and add this directive selector in this template and add this ng template in the HTML file of dialogue HTML file.
.Inject the component factory resolver in the constructor of the dialogue ts file.
.Call resolve component factory of the resolver class passing in the component as a argument.
.Call createComponent() method of view container ref of the directive created above.
.Pass in the above method component factory created above.

**Comment by andrewseguin** [comment]
Angular components are compiled ahead of time, and trying to add components via innerHTML won't work since it does not invoke any kind of dynamic compilation.

You likely want to try to pass the Component to create it dynamically rather than trying to use innerHTML: https://angular.io/guide/dynamic-component-loader
