### ISSUE TITLE
Better error reporting for mat-form-field

### ISSUE THREAD

**Issue by oleersoy** [angular/components#16797]
#### Feature Description

It looks as if `mat-form-field` cannot be used without `MatInputModule`, at least in the context of the API documentation.  [We could easily end up with this scenario](https://stackoverflow.com/questions/57522683/error-error-mat-form-field-must-contain-a-matformfieldcontrol-while-using-api-d/57522750#57522750).

Provide a brief summary of the feature you would like to see.
Better error reporting to address this:
https://stackoverflow.com/questions/57522683/error-error-mat-form-field-must-contain-a-matformfieldcontrol-while-using-api-d/57522750#57522750

#### Use Case

Describe the use case(s) that the proposed feature would enable.
Ideally the error would say that we also need to import the `MatInputModule`

**Comment by crisbeto** [comment]
`mat-form-field` can also be used with the `MatSelectModule`, as well as any custom controls that have implemented the `MatFormFieldControl` interface.

**Comment by andrewseguin** [comment]
We could add the error string to our docs to explain what they error means and how to resolve

**Comment by crisbeto** [comment]
We have a section specifically for this error in the docs: https://material.angular.io/components/form-field/overview#error-mat-form-field-must-contain-a-matformfieldcontrol
