### ISSUE TITLE
@angular/material vs @angular/components

### ISSUE THREAD

**Issue by mswilson4040** [angular/components#16790]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/

Did @angular/material2 change to @angular/components? When I click on the GitHub link on the Angular Material page, I end up here. I also don't see the @angular/material2 GitHub Repo anymore (it just redirects me here)

I am confused because I'm trying to upgrade our Angular Project via `ng update` and it's not listing any info for `cdk` or `material`. Should I remove the `@angular/material` and `@angular/cdk` packages and replace it with `@angular/components`?

running `ng add @angular/components` yields a 404 not found.

I understand that in the readme, it states this:

> This is the home for the Angular team's UI components built for and with Angular. **These include Material Design components and the Angular Component Development Kit (CDK).**

I'm not seeing any documentation on this change... Looking for some clarity here...

**Comment by buster95** [comment]
I am confused too

**Comment by mswilson4040** [comment]
*Should tap*

**Comment by devversion** [comment]
Sorry if that was unclear in the past. I hope it's now. We switched the repository to `components` as this repo obviously contains more than just Angular Material. We provide packages for dealing with the youtube-player API or with google-maps. Similarly is the Angular CDK not tied to Angular Material.

Packages remain as is. `@angular/cdk`, `@angular/material`, `@angular/youtube-player`, `@angular/google-maps` and more.
