### ISSUE TITLE
[Tabs] Documentation to header pagination

### ISSUE THREAD

**Issue by felipefialho** [angular/components#16799]
#### Documentation Feedback

I am adding some functionalities using HammerJS and I need to use some properties emitted from `MatPaginatedTabHeader`.

For example to emit an event to next and previous pagination. But I didn't found nothing on documentation and also didn't found on code source the best approach to implement it.

Can you describe me how is the accept properties in API? 

After it I can open a PR with this items.

**Affected documentation page:** https://material.angular.io/components/tabs/api

Thanks!

**Comment by andrewseguin** [comment]
Can you describe more about what you are wanting to do with the `MatPaginatedTabHeader`? It is not exposed with an API (no `Input` or `Output`)

**Comment by felipefialho** [comment]
Hey @andrewseguin, how are you?

I would like to access the events to `previous` and `next` item on pagination when I swiped on header using HammerJS.

Do you know some elegant way to do this using `MatPaginatedTabHeader`?

**Comment by jelbourn** [comment]
Closing this since it's not super clear what the end goal is here vs. talking about specific APIs for the tabs. Feel free to open a new issue with further details.
