### ISSUE TITLE
Last row get selected when I toggle the checkbox in the header with single selection

### ISSUE THREAD

**Issue by Yassinekli** [angular/components#16796]
I tried to implement mat-table with a single selection, and I realized that when I toggle the checkbox that exists in the header, the last row gets selected.

here is an example in StackBlitz and try to toggle the header checkbox to see what's happening
https://stackblitz.com/edit/angular-mwleht?embed=1&file=app/table-selection-example.ts

**Comment by andrewseguin** [comment]
Your `SelectionModel` is not multi-select enabled. When you select all rows, it will only keep the latest selected value.

Change `false` to `true` in the `SelectionModel` construction: `selection = new SelectionModel<PeriodicElement>(true, []);`

https://stackblitz.com/edit/angular-mwleht-jgyfgp?file=main.ts

**Comment by Yassinekli** [comment]
@andrewseguin but I think that what I did, you can click the link https://stackblitz.com/edit/angular-mwleht?embed=1&file=app/table-selection-example.ts and see that.
What I'm trying to explain is that there is a bug, so when I toggle the header checkbox the last row gets checked and I think it's a bad behaviour.
You can try it, toggle the header checkbox and see what's happen.
and I appreciate your answer 👍
