### ISSUE TITLE
Updating to version 8.1.3 updates Angular core libraries to prerelease version.

### ISSUE THREAD

**Issue by zhaparoff** [angular/components#16794]
#### Reproduction
Run `ng update @angular/material`
 
#### Expected Behavior
@angular/material is updated, @angular/core version remains unchanged or, at least, some warning displayed before updating it to prerelease version.

#### Actual Behavior
@angular/core is silently updated to the latest prerelease version (9.0.0-next.2)

#### Environment
- Angular: 8.2.2
- CDK/Material: 8.1.2 -> 8.1.3
- Browser(s): -
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10, x64

**Comment by andrewseguin** [comment]
This seems to be an open issue with the CLI where it sees 9.0.0.next as the latest version. Here's the issue to track: https://github.com/angular/angular-cli/issues/14980
