### ISSUE TITLE
cdk-virtual-scroll: viewport does not render correct number of items after browser zoom

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16802]
See https://stackblitz.com/edit/angular-ndhumn for repro. If the page is refreshed after zooming everything works as expected, so its probably a cached size that needs to be re-measured after zooming

**Comment by mmalerba** [comment]
A workaround for this is to listen for window resize events and call `checkViewportSize`: https://stackblitz.com/edit/angular-ob6zq5?file=src/app/app.component.ts

**Comment by el-meher** [comment]
is this the same problem as the one described in  [https://github.com/angular/components/issues/16775](#16775) ?
