### ISSUE TITLE
Getting duplicate snack-bar

### ISSUE THREAD

**Issue by MrKaisGit** [angular/components#16807]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue-zjgrqe

Steps to reproduce:
1.  Create a CustomErrorHandler class and implements ErrorHandler.
2.  Open snack--bar with error message if any error occur in component in handleError method
 
#### Expected Behaviour

What behaviour were you expecting to see?

Expecting single snack-bar with override settings .

#### Actual Behaviour

What behaviour did you actually see?

Getting multiple snack-bar, one with default (opening top left corner ) and other one with override settings.

#### Environment

- Angular: 8.1.2
- CDK/Material: 8.1.1
- Browser(s): Firefox Quantum 68.0 (64-bit)
- Operating System : Fedora 30 x64

**Comment by andrewseguin** [comment]
Your example fails to load - looks like the `MatSnackBar` is not injecting into your service. Can you fix this error and respond when its working? Thanks

**Comment by MrKaisGit** [comment]
Thanks for your assistance... I did fixed the StackBlitz code... It working fine now.. But my actual code getting duplicate SnackBar

**Comment by helzgate** [comment]
@MrKaisGit How did you fix this?  I'm getting the exact same thing.  First I get a snackbar in the top left that I can close, after I close it I get one at the bottom center that I can't close.

**Comment by helzgate** [comment]
I found the fix.  For me it was because I was using a 3rd party library to scan, in this case Cognex Barcode scanner for Cordova.  I wasn't initiating the scan outside of angular and handling the result to display in snackbar back inside angular.  Once I implemented the following code the problem went away:

```
this.zone.runOutsideAngular(() => {    // <-----  IMPORTANT ----->
        cmbScanner.startScanning();
        cmbScanner.setResultCallback(result => {
          if (result && result.readResults && result.readResults.length > 0) {
            this.zone.run(() => {            // <-----  IMPORTANT ----->
              // check result and display snackbar
            });
          }
        });
      });
```
