### ISSUE TITLE
keep checkbox checked while scrolling using angular virtual scroll

### ISSUE THREAD

**Issue by paco76** [angular/components#16808]
**What are you trying to do?**
keep a checkbox checked while scrolling up and down.

**What are you seeing that does not match your expectations?** 
Console must show the selected value only! but it produces different values.

here is a StackBlitz https://stackblitz.com/edit/angular-m5sh2y that demonstrate the strange behavior.

**Steps to reproduce:**
1. select one name only from the list
2. open Console
3. scroll up and down several times and observe the Console for the different values that the function creates.

- Angular:
- CDK/Material:
- Browser(s): chrome
- Operating System (Ubuntu): 

any suggestions ?

**Comment by andrewseguin** [comment]
It looks like `MatSelectionList` is built assuming that the options are static. You may have better luck managing the selection state yourself: https://stackblitz.com/edit/angular-r1rbny?file=src/app/app.component.ts

**Comment by paco76** [comment]
**andrewseguin** thanks for that.
your way of thinking and changes you made to the code make a much better picture but I really have to find the answer to that and I just can't :((

**Steps to reproduce after changes you made** 
1. select the top 5 checkboxes and also the last one
2. scroll up and down several times and observe how a checkbox that was checked getting unchecked and **auto** checked again.
