### ISSUE TITLE
mat-form-field floatLabel="never" appearance="outline" will shows the label

### ISSUE THREAD

**Issue by edjm1971** [angular/components#16800]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
https://stackblitz.com/edit/components-issue-yrfuba

Steps to reproduce:
1. Create item <mat-form-field floatLabel="never">
2. Create item <mat-form-field floatLabel="never" appearance="outline">
 
 
#### Expected Behavior

What behavior were you expecting to see?
  #1 The label will not show when data has been entered.
  #2 The label will not show when data has been entered.

#### Actual Behavior

What behavior did you actually see?
  #1 the label did not show when data had been entered
  #2 the label shows after data had been entered

#### Environment

- Angular: 
- CDK/Material:
- Browser(s): FF 68.0.2 and Chrome 76.0.3809.100
- Operating System (e.g. Windows, macOS, Ubuntu):  win32 x64

Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by andrewseguin** [comment]
The outline appearance does not support the `never` input, but this can be achieved by using `placeholder` on the input rather than the `<mat-label>`

https://stackblitz.com/edit/components-issue-jj3ap4?file=app/app.component.html

See docs for notes on this https://material.angular.io/components/form-field/api
