### ISSUE TITLE
cdkDrag should work inside a router-outlet

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/components#16816]
If you have a router-outlet and put a component, which has a cdkDrag attribute, inside of it, dragging does not work at all.
Can't this be corrected, please, because there are probably router-outlet(s) in more or less all non-trivial apps and I cannot use the drag-drop feature at all due to this error.
The problem is also described in https://github.com/angular/components/issues/15948, but the error still exists in the current version of the CDK (8.1.3).

**Comment by crisbeto** [comment]
Can you elaborate on how it doesn't work and potentially post an example of what you're doing? Our current dev app uses a `router-outlet` with a `cdkDrag` in it and it's working correctly.

**Comment by henrikdahl8240** [comment]
I would like to remove this issue because I have realized that I was wrong.

**Comment by henrikdahl8240** [comment]
In case others may benefit, the issue was, that what I put inside the router-outlet belonged to another NgModule and therefore it didn't work at first glance.
