### ISSUE TITLE
Mat Side Nav doesn't apply `-webkit-box-orient: vertical;` style upon opening a sidenav

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#16854]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-evutzr

Steps to reproduce:
1. Open Sidenav on the Stackblitz link above
2. Observe that even if Browser shows that `-webkit-box-orient: vertical;` is applied but the style is not visible. If you manually toggle this style it works.
 
 
#### Expected Behavior

What behavior were you expecting to see?
![image](https://user-images.githubusercontent.com/48334588/63602534-a4f79a00-c595-11e9-96b1-f64bcacabc33.png)

#### Actual Behavior

What behavior did you actually see?
![image](https://user-images.githubusercontent.com/48334588/63602553-b2148900-c595-11e9-800d-21ad29ef4e60.png)

#### Environment
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 12.3.1
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.0.1
@angular/cli                      8.0.6
@angular/material                 8.0.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

- CDK/Material:    ` "@angular/material": "^8.0.1",`
- Browser(s): `Chrome Version 76.0.3809.100 (Official Build) (64-bit)`
- Operating System: ` Windows 7 SP1`

**Comment by jelbourn** [comment]
`box-orient` (and its webkit variant) is a non-standard property left over from an ld version of the flexbox spec. Any bugs with it are probably related to that.
