### ISSUE TITLE
mat-dialog doesnt add the 'cdk-global-scrollblock' class to the root sometimes

### ISSUE THREAD

**Issue by rgjain** [angular/components#16864]
#### Reproduction

There are no specific steps to reproduce. It is happening in some components and in few it works fine.

#### Expected Behavior

What behavior were you expecting to see?
The class 'cdk-global-scrollblock' should get added to the HTML element when a dialog is open

#### Actual Behavior

What behavior did you actually see?
In some cases it is not getting added for me. I dont have a specific scenario identified yet.

#### Environment

- Angular: 7
- CDK/Material: 8
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The dialog won't try to block scrolling if the page isn't scrollable.

**Comment by devversion** [comment]
Looks like this works as expected. Closing! If you have a good use-case on why it should be added always, please create a new issue as feature request.
