### ISSUE TITLE
MatInput displays white as black

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/components#16866]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

![Screenshot_20190824-062832](https://user-images.githubusercontent.com/23146481/63632965-767ecb00-c638-11e9-95eb-aa0e3792f994.jpg)

Steps to reproduce:
1. Add a MatInput directive to an input within a mat-form-field
2. Give it type color
3. Do not enter a value for color
 
#### Expected Behavior

What behavior were you expecting to see?

Expected black to be black. 

#### Actual Behavior

What behavior did you actually see?

Angular Material component displays white as black i.e. if you don't enter a value for the form field the Material input will show black; however, when you actually submit the form, the real value will be white. This is true even after opening the colour picker, leaving the value as #000000 (black) and hitting OK without changing anything else in the color picker. 

#### Environment

- Angular: 7.1
- CDK/Material: 7.1
- Browser(s): Chrome, Firefox, MS Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by mmalerba** [comment]
appears to be fixed https://stackblitz.com/edit/components-issue-5fpk3o?file=src/app/example-component.html
