### ISSUE TITLE
Allow *ngIf and *ngFor to coexist

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/components#16867]
#### Feature Description

Provide a brief summary of the feature you would like to see.

I would like *ngFor and *ngIf to co-exist on the same element without conflicting. 

#### Use Case

Describe the use case(s) that the proposed feature would enable.

Sometimes I want to chose whether to instantiate based on one value and then iterate based on another if it is instantiated. Currently I would have to employ one of a few suboptimal strategies:

1: Use a display css binding to hide the fact the element is instantiated. Not useful when I want the component not to exist, not just not to be seen, for example in cases where it contains a data calculation service. 
2. Introduce additional wrapper elements, complicating the DOM in potentially counter-intuitive ways likely to introduce style bugs.
3. Hack through the DOM/shadow DOM in my controller to force Angular to do what I ask it using raw JavaScript/TypeScript, breaking separation of concerns.

**Comment by intellix** [comment]
You can use another ng-container wrapper which won't result in extra DOM to preserve your styles:

https://github.com/angular/angular/issues/4792#issuecomment-149282241

**Comment by crisbeto** [comment]
This is a limitation on the framework, not inside Angular Material or the CDK.
