### ISSUE TITLE
cdkDragDrop not retain edited data when cross-drop

### ISSUE THREAD

**Issue by TLKG** [angular/components#16865]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ugrc2b

Steps to reproduce:
1. edit text boxes in each column list
2. drag-drop within the same list, data retained.
3. drag-drop across won't.

#### Expected Behavior

What behavior were you expecting to see?
Edited data retained.

#### Actual Behavior

What behavior did you actually see?
updated data resumed back to original value.

#### Environment

- Angular: 8
- CDK/Material: 8.1.2
- Browser(s): Chrome, 76.0.3809.100
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10

**Comment by crisbeto** [comment]
That's because the CDK doesn't know anything about your data. In this case value is only inside of the specific DOM node and when you move it to a new list the node is recreated. You should have a data binding that updates the value inside your model so that the data is persisted.
