### ISSUE TITLE
Mat-Grid-List: gutterSize support for fxLayout

### ISSUE THREAD

**Issue by TimBo93** [angular/components#16881]
#### Feature Description
maybe it is related to (https://github.com/angular/components/issues/4211 or https://github.com/angular/material/issues/10654).

I would appreciate it if it would be possible to use clean fxLayout responsive attributes in the Mat-Grid-List `gutterSize`.

`<mat-grid-list cols="3" rowHeight="1:1" gutterSize="50px" gutterSize.lt-md="20px">`

#### Use Case

This would make it possible to seamlessly reduce the distances between individual tiles on mobile devices.

#### Status quo
Currently there is the possibility to use the `MediaObserver` in the TS to store the current state in a variable and to access it by expression. But this is cumbersome and doesn't feel right.

**Comment by jelbourn** [comment]
For the time being we have no intention of adding flex-layout style attributes to any of the Angular Material components; we'd like to someday maybe it easier for Angular itself to support this style of binding, but for now it adds more bloat to the components than we're comfortable with.
