### ISSUE TITLE
cdkDrag in ngSwitch

### ISSUE THREAD

**Issue by william-lohan** [angular/components#16895]
#### Reproduction

https://stackblitz.com/edit/components-issue-6xqvcp-cdkdrag-in-ngswitch?file=app/app.component.html

Steps to reproduce:
1. Drag first item, see y axis locked
2. Drag any other item, drags freely

Also if you look in the console the `QueryList` of `CdkDropList._draggables` only ever has one element.
 
 
#### Expected Behavior

All `[cdkDrag]` s to be part of `[cdkDropList]` they are inside of.

#### Actual Behavior

`[ngSwitch]` obstructs 

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/components/pull/17226.
