### ISSUE TITLE
datatable filter not working if we right click on the input and paste

### ISSUE THREAD

**Issue by mohitande** [angular/components#16907]
#### Reproduction

https://stackblitz.com/angular/xxbjkkldmgl?file=app%2Ftable-filtering-example.ts

1. In the DataTable, copy a column value and right-click on the filter input and click on paste.
2. data won't filter.
![Image of DataTable, not filtering]
https://ibb.co/Lx0Vh0D
 
#### Expected Behavior

What behavior were you expecting to see?
I expecting to show filtered data on paste

#### Actual Behavior

What behavior did you actually see?
showing all the data

#### Environment

- Angular: ~8.0.2
- CDK/Material: ^8.0.2
- Browser(s): Google Chrome 74.0.3729.131 (64 - bit)
- Operating System (Linux - Fedora):

**Comment by jelbourn** [comment]
While this is a bug in the example, it so minor that I don't think it's worth fixing since it would make the example more complicated.
