### ISSUE TITLE
Using MatDialogClose breaks default form submit functionality

### ISSUE THREAD

**Issue by flauc** [angular/components#16909]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-bde981

Steps to reproduce:
1.  Click on the `Doesn't Work` button to open the dialog
2.  Hit enter 
 
 
#### Expected Behavior

In the working example hitting enter submits the form and in this case, closes the dialog. I wouldn't expect that adding 
the `MatDialogClose` directive in place of the click method would change that.

#### Actual Behavior

Adding `MatDialogClose` prevents the form from being submitted when hitting enter and not having the button focused.

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Chrome 76.0
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by tomicarsk6** [comment]
More about the reason behind that you can see here #2599.

**Comment by flauc** [comment]
I don't understand why it would override `type=submit` if already defined on the element though.

**Comment by tomicarsk6** [comment]
I agree with you, that is something that needs to be supported, if you don't define button type then it should work like it's working, but if you define it then this value should be used instead.

**Comment by jelbourn** [comment]
Agreed that it shouldn't change the `type` if it's set manually. As a workaround, you can add a submit button that calls `dialogRef.close()`
