### ISSUE TITLE
Missing icon drag_indicator

### ISSUE THREAD

**Issue by theunreal** [angular/components#16901]
I'm simply trying to:

`<mat-icon>drag_indicator</mat-icon>`

The icon does not appear, although I see it exists here: https://material.io/resources/icons/?search=drag&icon=drag_indicator&style=baseline

Not sure if the issue related to https://github.com/google/material-design-icons

**Comment by jelbourn** [comment]
Angular Material doesn't add any icons itself, instead relying on the user to provide icons independently. 

https://github.com/google/material-design-icons is probably the right place, though be sure you're loading the right variant of the icon font, as not all of them load all of the icons.
