### ISSUE TITLE
scroll to end method for angular cdk virtual scroll

### ISSUE THREAD

**Issue by shuaibindia007** [angular/components#16902]
#### Feature Description

Provide a brief summary of the feature you would like to see.

#### Use Case

Describe the use case(s) that the proposed feature would enable.
In a list.. when the user scrolls to the end angular material should be able to configure a method which is triggered when the list ends.

**Comment by crisbeto** [comment]
This should be covered by `CdkVirtualScrollViewport.scrollToIndex` already.
