### ISSUE TITLE
In VoiceOver, aria-label on mat-radio-button is read twice

### ISSUE THREAD

**Issue by calebegg** [angular/components#16913]
StackBlitz seems to be down, but it's easy to reproduce--just add an aria-label to any mat-radio-button. The label gets duplicated, and VO reads both.

![image](https://user-images.githubusercontent.com/782920/63965662-a595a200-ca67-11e9-9326-bc2e6ab73f86.png)

**Comment by jelbourn** [comment]
@calebegg add like which of these?
```html
<mat-radio-button [aria-label]="...">

<!-- or -->

<mat-radio-button [attr.aria-label]="...">
```

**Comment by calebegg** [comment]
Just <mat-radio-button aria-label=“...”>
