### ISSUE TITLE
MAT PAGINATOR UNUSUAL BEHAVIOR

### ISSUE THREAD

**Issue by buster95** [angular/components#16915]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?
Mat Paginator => when change datasource length, mat paginator should set to first page

#### Actual Behavior

What behavior did you actually see?
Mat paginator 
when change items length, not set in the first page

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): MicrosoftEdge Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by llorenspujol** [comment]
I don't see any MatPaginator on this stackblitz example, an you review it?

**Comment by jelbourn** [comment]
It sounds like you expect the paginator current page to reset if the total length changes. Right now they are intentionally kept independent. Feel free to open a new issue with a reproduction if I'm misunderstanding.
