### ISSUE TITLE
Make attachBackdrop public

### ISSUE THREAD

**Issue by jonathanazulay** [angular/components#16922]
#### Feature Description

It's possible to detachBackdrop but not to reattach it. There's a private method on on OverlayRef to attachBackdrop, maybe it should be public?

#### Use Case

1. Modal close animation begins (slideout for example)
2. Backdrop is detached
3. User reopens modal before leave animation is completed
4. Modal starts to slide back in, here backdrop should be reattached

**Comment by jelbourn** [comment]
@crisbeto do you remember why `detachOverlay` is public to begin with?

**Comment by crisbeto** [comment]
`detachBackdrop` is public so that we can start the backdrop animation and have it run while the exit animation for something like a dialog is running.

**Comment by crisbeto** [comment]
I'm closing this since `detachBackdrop` is only there to facilitate animations, it isn't meant to be re-attached.
