### ISSUE TITLE
Range slider for from and to values

### ISSUE THREAD

**Issue by ranbuch** [angular/components#16936]
#### Feature Description
As described on the [material design guidelines](https://material.io/components/sliders/#usage)

#### Use Case

Let the user specify 2 values like `from price` and `to price` when the second one is always greater then the first one.

**Comment by AdditionAddict** [comment]
Duplicate of #1331

**Comment by devversion** [comment]
Yes. Closing as a duplicate. Thanks @AdditionAddict
