### ISSUE TITLE
Example using a mat-checkbox inside a mat-menu

### ISSUE THREAD

**Issue by MRMokwa** [angular/components#16945]
#### Documentation Feedback

I'd like to see an example that uses mat-menu with mat-checkbox. There's no easy way to know the right way to implement it. 

In [stackoverflow](https://stackoverflow.com/questions/55053605/angular-material-checkbox-in-mat-menu-problem-with-dark-themes) there is a suggestion to use this way:

`<mat-checkbox class="mat-menu-item">Problem here</mat-checkbox>`

But using it in the class doesn't feel correct to me, also it doesn't use the property:
```
@Input()
role: 'menuitem' | 'menuitemradio' | 'menuitemcheckbox'
```

**Affected documentation page:** https://material.angular.io/components/menu/api

**Comment by crisbeto** [comment]
This isn't something that we've built yet. The role is defined like that in case somebody wants to build it themselves.
