### ISSUE TITLE
Use inline flex instead of flex on mat header row and mat row elements.

### ISSUE THREAD

**Issue by oleersoy** [angular/components#16959]
#### Feature Description

https://medium.com/@ole.ersoy/making-the-angular-material-data-table-rows-fit-content-f227f4d9355e

Right now, since the `mat-header-row` is a `flex` container it will only expand to fit the parent container, and if the `mat-header-cell`s are wider than that they will overflow the container.

#### Use Case

Allow the `mat-head-row` and `mat-row` to fit the content.

[See this SO for more details](https://stackoverflow.com/questions/57773529/getting-a-flex-container-to-expand-to-fit-the-total-width-of-all-the-contained-i?noredirect=1#comment101982457_57773529)

And this one:

https://stackoverflow.com/questions/57764056/expanding-the-angular-material-data-table-header-row-to-match-row-content-width

**Comment by oleersoy** [comment]
Looks like this causes a different issue.  The column now wraps for tables with a small number of columns:

https://stackblitz.com/edit/angular-material-table-hide-columns-bug?file=src/app/app.component.ts

**Comment by andrewseguin** [comment]
The flex layout table is not well supported and only useful for a limited number of cases. I recommend using the native `table` version
