### ISSUE TITLE
Angular material issue with Change Detection

### ISSUE THREAD

**Issue by popular123** [angular/components#16957]
#### Bug, feature request, or proposal:
I have used material components like mat-select,checkbox etc. The issue is mat-select is not opening until i click on another material component

#### What is the expected behavior?
Material component should open as it has default behaviour

#### What is the current behavior?
Material component is only opening when i click on another material component.
For mat-select: Options is only showing when i click on another material component.
For Checkbox : Checking/Unchecking only work when i click on another material component.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/animations": "^7.2.5",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@types/fabric": "^1.5.53",
    "@types/xrm": "^9.0.11",
    "core-js": "^2.5.4",
    "fabric": "^2.6.0",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"

**Comment by crisbeto** [comment]
It's hard to tell what is going on based on the information in the issue. Can you post a Stackblitz that shows the issue?

**Comment by popular123** [comment]
what i m doing is using "this.changeDetection.detectChanges();", before using everything works perfectly

**Comment by jelbourn** [comment]
Unfortunately this isn't enough information to investigate anything. Without a reproduction (e.g. StackBlitz), we don't have anything to look into.

**Comment by devversion** [comment]
Closing as no reproduction has been provided and it's unclear what this issue is about.

Please create a new issue if this issue still surfaces, but make sure to include a proper reproduction.
