### ISSUE TITLE
Mat-select overlapped with mat-label

### ISSUE THREAD

**Issue by sngvahmed** [angular/components#16969]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-buq6rw?embed=1&file=app/select-overview-example.ts&view=preview 
but download the source code and run it local in safari

![Bug](https://i.stack.imgur.com/UQHTC.png)

Steps to reproduce:
1. use simple mat-select with mat-label and mat-form
2. create the component 
3. add setInterval with logic that adding in the array that include values and update the mat-select value at the same time 
 
 for the summary open the [stackblitz link](https://stackblitz.com/edit/angular-buq6rw?embed=1&file=app/select-overview-example.ts&view=preview) and download the source code then run it localy in the safari

#### Expected Behavior
the mat-label should be above the mat-select value 

#### Actual Behavior
mat-label value overlapped with mat-select value

#### Environment
- Angular: 8
- CDK/Material: 8.0.2
- Browser(s): Safari
- Operating System : macOS

**Comment by ElBedeawi** [comment]
I have the Same issue Thanks for the reproducing it.

**Comment by crisbeto** [comment]
That's because the app that you're downloading from Stackblitz doesn't include a theme. There's even a warning about it in the console:

```
Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming
```
