### ISSUE TITLE
MatSpinner is unaffected by transform: translate()

### ISSUE THREAD

**Issue by hodossy** [angular/components#16981]
#### Reproduction

Example: https://components-issue-v63m7m.stackblitz.io

Resize the window to see that the top left corner of the spinner is in the center.

Steps to reproduce:
1. Have an absolutely positioned element with a spinner inside:
```
position: absolute;
top: 0;
left: 0;
bottom: 0;
right: 0;
```
2. Apply the following css:
```
position: relative;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```
 
 
#### Expected Behavior

Spinner is properly centered

#### Actual Behavior

Translate is not affecting the spinner

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): Chrome 76
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by donroyco** [comment]
MatProgressSpinner _itself_ is indeed unaffected by `transform` property. To circumvent this, just add a div around the `<mat-spinner>` and give it that div the absolution positioning:

```css
position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

**Comment by crisbeto** [comment]
@donroyco is correct. Also after https://github.com/angular/components/pull/16930 gets in the animation won't be on the host anymore.
