### ISSUE TITLE
Make MatBottomSheetRef Constructor Injection Use Case Symmetrical 

### ISSUE THREAD

**Issue by oleersoy** [angular/components#17011]
#### Feature Description

The implementation approach for `MatBottomSheetRef` is different and not symmetrical to the implementation approach for other angular components.

For example we have to declare a provider with default values.  Angular could create the default values for us and the implementation could override when necessary.  More here:

https://stackoverflow.com/questions/57846500/nullinjectorerror-no-provider-for-matbottomsheetref

#### Provide a brief summary of the feature you would like to see.

Defaults provided by angular so that we can we can use `MatBottomSheetRef ` the same way we use all other components / services.

#### Use Case

Describe the use case(s) that the proposed feature would enable.

Just import the `MatBottomSheet` module.  And use the service in the components:

For example if we import it like this:

`import { MatBottomSheetRef } from '@angular/material';`

We get the null injection error.  This does not happen with any other component.

We have to import it like this:

`import { MatBottomSheetRef} from '@angular/material/bottom-sheet';`

**Comment by devversion** [comment]
Hello! Thanks for your issue. I wasn't able to see the issue you were describing in the issue and StackOverflow. The recommended import as of v8 is the latter (i.e. `material/bottom-sheet`).

The `MatBottomSheetRef` should be provided automatically for the rendered bottom-sheet content. I'm not sure why one would need to provide that manually, except for tests.
