### ISSUE TITLE
[Table] sort not working when is in a div with a *ngIf

### ISSUE THREAD

**Issue by axelbon** [angular/components#17021]
#### Reproduction

https://stackblitz.com/edit/table-ngif-issue-x5wxje
 
#### Expected Behavior

Table sort

#### Actual Behavior

Sort table not working correctly. Happens when the table is in a div or other element with a *ngIf"something"

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by andrewseguin** [comment]
Your view child query should not be set to `static: true` if it is in an `ngIf`
