### ISSUE TITLE
Add to cdkDropList events data about keyboard with pressed control keys

### ISSUE THREAD

**Issue by Dok11** [angular/components#17032]
#### Feature Description

`<div cdkDropList (cdkDropListDropped)="drop($event)">`  
I want get in `$event` data about pressed keys like Alt, Ctrl or Shift for example.

#### Use Case

For different behaviour and more various UI/UX scenarios with keyboard participio.

**Comment by crisbeto** [comment]
Not exactly what was requested here, but #17077 will expose the native `MouseEvent` that triggered the dropping. From it you can get which key is pressed using `event.ctrlKey` or `event.altKey`.
