### ISSUE TITLE
mat-tab-nav-bar can break scrolling?

### ISSUE THREAD

**Issue by robert-king** [angular/components#17041]
#### Reproduction

Steps to reproduce:
unable to reproduce as the arrows dont show up even with latest package.json deps: https://stackblitz.com/edit/components-issue-djptud 

however this is how it happens reproduce:
on chrome, open dev-tools and set device to mobile (e.g. iphone).
On mat-tab-nav-bar, if you have too many tabs to fit, left and right arrows appear. if you hold down touch the right arrow, it goes across to the rightmost tab, after this, scrolling is broken for the entire app on every page, you cant scroll. 

```
<nav mat-tab-nav-bar>
    <a mat-tab-link
       *ngFor="let child of childList.list; let idx=index"
       [routerLink]="idx"
       routerLinkActive #rla="routerLinkActive"
       [active]="rla.isActive">
      {{child.firstName}} {{child.lastName}}
    </a>
  </nav>
```

only way i found to fix scrolling is to close the browser tab and reopen the app. (refreshing doesnt fix)
 
- Angular: 8.2.5
- CDK/Material:  8.1.4
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): mac, running iphone mode in devtools

<img width="367" alt="Screen Shot 2019-09-11 at 10 40 20 AM" src="https://user-images.githubusercontent.com/793016/64655608-e1c1fd00-d480-11e9-8c80-0ab294b7eac6.png">
<img width="333" alt="Screen Shot 2019-09-11 at 10 43 09 AM" src="https://user-images.githubusercontent.com/793016/64655646-fbfbdb00-d480-11e9-8c4a-85e28ed9aba7.png">

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Just tried this and I could not reproduce the issue. I tried in Chrome dev tools with emulation and on an actual Android device. Your StackBlitz has a error being thrown, which may be part of the problem. Feel free to open a new issue if you're able to provide a reproduction with the latest version.
