### ISSUE TITLE
Some Troubleshooting about overlay.ts source

### ISSUE THREAD

**Issue by kisslove** [angular/components#17043]
some code at overlay-containder.ts.I'am confused why remove all previousContainers eveythime,that could lead to I can not use this cdk mutil-times in a project.

```
protected _createContainer(): void {
    const containerClass = 'cdk-overlay-container';
    const previousContainers = this._document.getElementsByClassName(containerClass);
    // Remove any old containers. This can happen when transitioning from the server to the client.
    for (let i = 0; i < previousContainers.length; i++) {
      previousContainers[i].parentNode!.removeChild(previousContainers[i]);
    }
    const container = this._document.createElement('div');
    container.classList.add(containerClass);
    this._document.body.appendChild(container);
    this._containerElement = container;
  }
```

**Comment by jelbourn** [comment]
All of the overlay code assumes there's exactly one overlay _container_, which contains multiple overlay panes. If a new one is created, it replaces the previous container.

**Comment by kisslove** [comment]
@jelbourn ，so sorry,this leads to I could not use multiple cdk in one project.because it will remove old containers when the another cdk comes in.so this old cdk can not work.the reason is the old overlay still keep the reference of this old container(this._containerElement ),but it can't find previous containers.so it can not work(show overlay);
