### ISSUE TITLE
Menu mirrors CDK overlay offset

### ISSUE THREAD

**Issue by rcketscientist** [angular/components#17049]
#### Reproduction

If you shift the overlay to not interfere with a titlebar the menu will shift the same amount.  Select, however, works fine.

https://stackblitz.com/edit/angular-ff47mh
 
#### Expected Behavior

I would expect the same behavior for both, ideally the current select behavior which works regardless of an overlay offset.

#### Actual Behavior

Menu is offset by the same amount applied to the CDK overlay.

**Comment by rcketscientist** [comment]
I removed the overlay offset by instead defining that all overlays are `nodrag` from an electron PoV.  However, I would be interested to know if there was a way to solve this if an offset was legitimately needed, since `select` seems to be ok.

**Comment by crisbeto** [comment]
The idea with the overlay container is that it should always be the same size as the viewport and it shouldn't be offset. `mat-select` probably works because we have a bunch of extra logic that positions the selected option in the dropdown on top of the trigger.
