### ISSUE TITLE
Allow click Outside to close a dialog when there is no Backdrop

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#17040]
#### Feature Description

I would like a to have the dialog to close when I click outside the dialog and there is no Backdrop

#### Use Case

In this stack blitz example I am unable to close the dialog by clicking it outside 

https://stackblitz.com/edit/angular-tkg6v6

**Comment by crisbeto** [comment]
Will be addressed by https://github.com/angular/components/pull/16611.
