### ISSUE TITLE
Mac Safari DragEvent

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#17042]
#### Reproduction

The following lines cause an error on OSX/IOS Safari:
`export class MyComponent{
@HostListener('dragenter', ['$event'])
  handleEnter(event: DragEvent) {
    event.preventDefault();
  }
}`

Receiving 'ReferenceError: Can't find variable: DragEvent'.

The line above compile add line `z8e("design:paramtypes",[DragEvent])`, which cause the error.
 
#### Environment

- Angular: 8.2.5
- CDK/Material: 8.2.0
- Browser(s): Safari
- Operating System: macOS, IOS (IPhone)

**Comment by TaylorNoelJordan** [comment]
I'm having the same issue.

**Comment by crisbeto** [comment]
Closing since this isn't an issue with Material or the CDK. You're getting that error, because the `DragEvent` isn't supported on your browser. See https://developer.mozilla.org/en-US/docs/Web/API/DragEvent.
