### ISSUE TITLE
Datepicker dates and manually entered dates differs

### ISSUE THREAD

**Issue by clasericson** [angular/components#17045]
#### Reproduction

https://stackblitz.com/edit/angular-du34ef
https://angular-du34ef.stackblitz.io

Steps to reproduce:
1. Choose a date with the date picker, for example 10th of September 2019. With my locale ('sv'), the selected date will be '2019-09-09T22:00:00.000Z' as presented in the page after selection.
2. Manually enter a date, for example 9th of September 2019. In my test I typed in 2019-09-09 and the selected date became '2019-09-09T00:00:00.000Z'
 
 
#### Expected Behavior

I was expecting that I would get the same selected date no matter selection method. 

#### Actual Behavior

Selecting a date via date picker resulted in a correct UTC-formatted date. But the manually entered date was not correct. It seems like the manually entered is expected to be entered in UTC, not in my current locale.

#### Environment

- Angular: 8.2.5
- CDK/Material: 8.1.4
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by tomicarsk6** [comment]
You can create your custom DateAdapter that implements NativeDateAdapter, and then do the custom implementation of parse and format methods that will match your requirements. And afterwards you can provide that custom DateAdapter instead of default one.

**Comment by clasericson** [comment]
> You can create your custom DateAdapter that implements NativeDateAdapter, ...
Yes, that's true! That is one way of getting around this odd behaviour and probably also the easiest in this case. On the other hand, for the ones that doesn't realize this behaviour, it creates unnecessary headache. In my opinion, the manually entered date should be the same as the one that the date picker provides.

**Comment by tomicarsk6** [comment]
I agree with you, but why is that you can read here #14291. It's basically like that because of a limitation of Java's script native parsing. They have created NativeDateAdapter and MomentDateAdapter that you can use to create your own custom DateAdapter that will suit to your needs.
