### ISSUE TITLE
'active' is not a valid property of <a>

### ISSUE THREAD

**Issue by cromefire** [angular/components#17055]
#### Reproduction

StackBlitz is unusable for me

https://github.com/cromefire/active-tab-link
 
 
#### Expected Behavior

```html
<nav mat-tab-nav-bar>
    <a mat-tab-link [active]="true">Tab</a>
</nav>
```

Should result in an active tab

#### Actual Behavior

```
ERROR in src/app/app.component.html(21,21): error TS8002: 'active' is not a valid property of <a>.
```

#### Environment

- Angular: `9.0.0-next.5`
- CDK/Material: `8.2.0`
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): `Ubuntu 18.04`

**Comment by cromefire** [comment]
And yes the `MatTabsModule` is included, it worked in older versions of `angular` and `components` and there are no errors shown in my IDE.

**Comment by naveedahmed1** [comment]
I can confirm this is happening after upgrade to `Angular Components 8.2.0`

**Comment by tinybigideas** [comment]
Getting the same error along with other CDK related errors on HTML templates. Downgraded to `8.0.0` and all is good.

**Comment by naveedahmed1** [comment]
I am not sure if its an error related to Angular Material or Angular IVY.

Latest version of Angular throws similar error for `selectedIndex` for `mat-tab-group` 

And I can confirm the issue still exists with Angular 9.0.0-next.8 and Angular Components v 8.2.0.

**Comment by DibyodyutiMondal** [comment]
I experienced the same issue. Resolved by reverting my package-lock.json

**Comment by cromefire** [comment]
Can confirm the downgrading works

**Comment by DibyodyutiMondal** [comment]
downgrading what to 1.2.0?

**Comment by cromefire** [comment]
Material and CDK

**Comment by jelbourn** [comment]
This should be fixed now.

**Comment by Splaktar** [comment]
Please try `9.0.0-next.0` as this should be resolved in that release.
