### ISSUE TITLE
[cdk-connected-overlay] add animation support on opening and closing

### ISSUE THREAD

**Issue by daanishnasir** [angular/components#17068]
#### Feature Description
Reference to closed issue [cdk-connected-overlay] add animation support on opening and closing #5127

Provide a brief summary of the feature you would like to see.

#### Use Case

Describe the use case(s) that the proposed feature would enable.

Currently it is not possible to animate an open and close transition when using cdk-connected-overlay. While you can animate the content inside the overlay you can't animate the cdk overlay transition itself so it looks pretty wonky and unappealing. The overlay itself is what should be animated not the content. 

Maybe something like this would be great!

   [cdkConnectedOverlayTransitionIn]="180ms ease-in "

   [cdkConnectedOverlayTransitionOut]="200ms ease-out "

**Comment by crisbeto** [comment]
It's already possible to animate it using Angular animations. You can see an [example in the `mat-select` component](https://github.com/angular/components/blob/master/src/material/select/select.html#L19).

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
