### ISSUE TITLE
[Scroll] MatSelect Options scroll over other elements. 

### ISSUE THREAD

**Issue by BantramFidian** [angular/components#17061]
#### Reproduction

Steps to reproduce:
1. Visit https://material.angular.io/components/select/examples
2. Click on a select (the options dialog should open)
![step1](https://user-images.githubusercontent.com/29603738/64762476-8eae7f80-d53e-11e9-9010-4ef10e2b0099.PNG)
3. Scroll your screen with the mousewheel outside of the options without clicking
4. Options schould stay visible while screen scrolls
 ![BugReport](https://user-images.githubusercontent.com/29603738/64762416-6f175700-d53e-11e9-8d05-a63d526f67bd.PNG)

 
#### Expected Behavior

Options close once the Select Element is out of the ViewPort and should most definetly not overlay other components.

I feel like there should be a trigger that checks whether the select field should be visible i.e. is in viewport and not overlayed by another component and close the options in that case.

#### Actual Behavior

Options stay open and even block the header.

#### Environment

- Angular: 8.2.
- CDK/Material: MatSelect
- Browser(s): Chrome, Internet Explorer 10, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

This behaviour looks quite ugly in my app and I am struggling to come up with a clean and performance friendly solution to my problem, since I don't really want to flood my app with .getBoundingClientRect() calls.

Any advice?

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

@BantramFidian by default `MatSelect` disabled page scroll while open. How are you making the page scroll here?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
