### ISSUE TITLE
Add buffer mode to MatSlider

### ISSUE THREAD

**Issue by wasp898** [angular/components#17065]
#### Feature Description

Introduce a buffer mode to MatSlider, similar to the one already available in MatProgressBar

#### Use Case

In most video or audio streaming players it may be required to show the amount of buffer being downloaded during the playback. Adopting a progress bar isn't enough because the user needs to be able to seek back and forth in the media, which requires a slider. I'm suggesting a slider bar with the ability to draw a buffer line, with a customizable color.

**Comment by jelbourn** [comment]
I don't see us adding this feature unless it were added to the Material Design spec.
