### ISSUE TITLE
Wire up tertiary testing API docs in material.angular.io

### ISSUE THREAD

**Issue by devversion** [angular/components#17063]
We need to figure out how we handle docs generation for tertiary entry-points such as `cdk/testing/testbed` or `material/button/harness`.

cc. @mmalerba @jelbourn

**Comment by Splaktar** [comment]
There is a PR for material-aio here: https://github.com/angular/material.angular.io/pull/660

**Comment by mmalerba** [comment]
@andrewseguin I believe this is done now right?
