### ISSUE TITLE
Drag and drop - missing styles after theme changing

### ISSUE THREAD

**Issue by Rogaliusz** [angular/components#17089]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-drag-and-drop-themes-bug 

I Can only reproduce changing primary color to first, in my env also all styles were missed.

Steps to reproduce:
1. Create few themes (+ picker mechanism)
2. Create drag and drop component (with @mixin background color from theme).
3. Put in cdkDrag any mat element with color
4. Run & Change theme to another
5. Do some works on drag and drop panel.
 
 
#### Expected Behavior

Dragged elements will in this same styles/colors like chosen theme.

#### Actual Behavior

Dragged elements haven't any styles + primary colors are fetched from first theme.

#### Environment

- Angular: 7.1.0
- CDK/Material: 7.2.0
- Browser(s): Chrome & Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS and Docker (on Linux) on test server.

<img width="1607" alt="obraz" src="https://user-images.githubusercontent.com/17571389/64913555-7dce5b80-d742-11e9-84df-152c3efabffc.png">

<img width="1607" alt="obraz" src="https://user-images.githubusercontent.com/17571389/64913050-1eb81900-d739-11e9-9a05-ce0bb62c3514.png">

**Comment by crisbeto** [comment]
That's because the preview is `position: fixed` and appended to the `body` in order to avoid issues with `z-index` and `overflow: hidden`. It should work if you set your theme on the body.

**Comment by Rogaliusz** [comment]
My theme on the body? Could You write some more information?

**Comment by crisbeto** [comment]
The DOM usually looks something like this:

```html
<body>
  <div class="some-theme">
    <div class="drop-list">
      <div class="drag-item"></div>
    </div>
  </div>
</body>
```

However when dragging starts the preview is moved out to the bottom of the body so your theme won't apply to it.

```html
<body>
  <div class="some-theme">
    <div class="drop-list">
    </div>
  </div>

  <div class="drag-item drag-preview"></div>
</body>
```

**Comment by Rogaliusz** [comment]
but the primary color is already applied to the body, it was done by angular theme control, right? 

Also I want only change the one div not all site

**Comment by crisbeto** [comment]
I'm glad that it worked out, but you should keep in mind that this could cause the color scheme to change while you're dragging. Usually the way to solve it would be to set a class on the preview, but the only way to do it right now is to provide a custom preview. I'll add another API that allows for a class to be set since re-providing the entire preview can be boilerplate-ey.
