### ISSUE TITLE
SELECT_PANEL_VIEWPORT_PADDING

### ISSUE THREAD

**Issue by King2231** [angular/components#17081]
#### Documentation Feedback
There is this constant SELECT_PANEL_VIEWPORT_PADDING mentioned in the API section for mat-select. But there is nothing mentioned on how exactly can this be used. I have a scenario where in I wish to specify a boundary which the mat-select panel must not cross. Is this SELECT_PANEL_VIEWPORT_PADDING related to what I am looking for? If yes, how do I use it? Just declare it the way it is written in the documentation. I need not bind to any elementref or something?
(There are other components too for which some more details would be useful. The angular material is very powerful library and the documentation too is good but some more details could help better.)

Thanks.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by crisbeto** [comment]
I think that constant was exported so that we can use it in our unit tests and it accidentally ended up in the public API because we have an `export * from './select'`. It isn't something that intended to be changed.

**Comment by King2231** [comment]
Also this from Autocomplete 
@Input('matAutocompleteConnectedTo') connectedTo: MatAutocompleteOrigin
I tried using this 
**this.trigger.connectedTo=new MatAutocompleteOrigin(this.attrInput)**

But i get an error Module not found: Error: Can't resolve '@angular/material/autocomplete/typings/autocomplete-origin'
