### ISSUE TITLE
mat-checkbox makes mat-grid-tile non-resposive

### ISSUE THREAD

**Issue by Arno-v** [angular/components#17095]
Steps to reproduce:
create a mat-grid-list with tiles containing a mat-checkbox. See:
https://stackblitz.com/edit/angular-y54cqq?embed=1&file=app/grid-list-overview-example.html
 
I expected the checkboxes to remain in the center of the tile while resizing the window e.g. by dragging the separator in stackblitz

Instead the checkboxes remained on their initial position. It appears that the figure which is created inside the tile no long responds the size changes of the tile. I used chrome developer tools to monitor the width and height of the tile and the figure. The tile size changes on resize, the figure size remains at its initial value.

**Comment by Arno-v** [comment]
I have replaced the mat-checkbox with ordinary HTML checkboxes, and this works properly, however I would like to use the mat-checkbox because it looks better. Any suggestion on how to fix this?

**Comment by jelbourn** [comment]
Closing this because we are pretty unlikely to add new features to `MatGridList` going forward now that CSS Grid provides a significantly more robust tool for creating this style of layout.
