### ISSUE TITLE
Angular Material Datepicker issue when using Dutch language

### ISSUE THREAD

**Issue by harangusdan** [angular/components#17109]
I want to use multiple languages for the Material Datepicker. I use the setLocale method from DateAdapter but it generates an inconsistency regarding the display of the days of week. In the Dutch version, Monday is considered as week-end day and it is disabled by my week-end days filter. Also, the days of week in Dutch are displayed with starting lowercase.
  
#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

<img width="256" alt="Screenshot 2019-09-17 at 09 57 17" src="https://user-images.githubusercontent.com/55430168/65041765-1d1c6a00-d960-11e9-8ccb-e9f4e185a1ee.png">
<img width="254" alt="Screenshot 2019-09-17 at 09 58 12" src="https://user-images.githubusercontent.com/55430168/65041767-1d1c6a00-d960-11e9-8832-a6a859b6702f.png">
<img width="295" alt="Screenshot 2019-09-17 at 10 12 21" src="https://user-images.githubusercontent.com/55430168/65041768-1db50080-d960-11e9-9a7e-e94e03a1081a.png">

**Comment by jelbourn** [comment]
Which DateAdapter are you using?

**Comment by harangusdan** [comment]
I use DateAdapter from '@angular/material'

**Comment by jelbourn** [comment]
[See the docs for i18n.](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings)

By default, the component uses the native JavaScript `Date`, which has extremely limited i18n support. For more robust i18n, you need to use an alternate `DateAdapter`.
