### ISSUE TITLE
mat-progress-bar rendering bug when mode=buffer and height is different than 4px

### ISSUE THREAD

**Issue by alvaromartmart** [angular/components#17105]
#### Reproduction

https://stackblitz.com/edit/angular-pr4ncb

Steps to reproduce:
1. Add a `mat-progress-bar` element in *buffer* mode
2. Change the element's height to a value different than the default 4px
 
 
#### Expected Behavior

There should be a single line of moving dots, centered in the progress bar height.
**Edit:**  I understand that the height value of 4px comes from Material Design specifications for progress bars, I just think it would be better if the *buffer* version implementation considered the actual height of the element, instead of rendering overlapping dots.

#### Actual Behavior

Several overlapping dots are rendered.

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
Closing this issue since it hasn't gotten any activity in a long time and we generally don't support overrides of our styles.
