### ISSUE TITLE
embedding mat-optgroup elements using *ngFor causes app to crash/freeze

### ISSUE THREAD

**Issue by alvaromartmart** [angular/components#17106]
#### Reproduction

https://stackblitz.com/edit/angular-xwukxn?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Embedding `mat-optgroup` elements using *ngFor over a *hard-coded* array works OK.
```html
<mat-select>
  <mat-optgroup *ngFor="let g of [{name: 'group 1'}, {name: 'group 2'}]" [label]="g.name">
    <mat-option>None</mat-option>
  </mat-optgroup>
</mat-select>
```
2. However, trying to pass an array returned by an object getter to the *ngFor results in the app freezing.
```ts
class MyClass {
    get values() { return [{name: 'group 1'}, {name: 'group 2'}]; }
}

class MyComponent {
    instance = new MyClass();
}
```
```html
<mat-select>
  <mat-optgroup *ngFor="let g of instance.values" [label]="g.name">
    <mat-option>None</mat-option>
  </mat-optgroup>
</mat-select>
```
 
#### Expected Behavior

The `mat-select` should be displayed correctly.

#### Actual Behavior

The app freezes.

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
When you put the array in a getter like that you end up returning a new array every time Angular runs change detection. This means that as far as Angular is concerned the data always keeps changing which means that the UI has to be re-rendered.

**Comment by alvaromartmart** [comment]
Ouch. Of course, that makes sense. I was shocked by the sudden freezes and the solution was actually quite simple 😅 
Thank you!
