### ISSUE TITLE
Create user documentation for test harnesses

### ISSUE THREAD

**Issue by mmalerba** [angular/components#17118]
Including:
- [x] Docs for authoring harnesses
- [x] Docs for using harnesses
- [ ] Docs for creating new harness environments
- [x] Guide for use with Angualar Material components
- [ ] Add thorough TSDoc and corresponding generated docs for individual harnesses

**Comment by devversion** [comment]
For reference: Related to #17063

**Comment by jelbourn** [comment]
Fixed by #17754
