### ISSUE TITLE
Mat-Table row grouping with indexBy

### ISSUE THREAD

**Issue by Superkarl** [angular/components#17111]
#### What are you trying to do?

I've read [this solution](https://stackoverflow.com/questions/52217179/angular-material-mat-table-row-grouping), which provides a **row grouping** on an Angular Material 2 mat-table. To increase the performance, i use trackby (https://material.angular.io/cdk/table/overview).

#### What troubleshooting steps have you tried?

> But I get the wrong grouping when I use **trackby**!

#### Reproduction

**Demo**: https://stackblitz.com/edit/angular-mattable-with-collapsible-groupheader-pg241g?file=app%2Ftable-basic-example.html

***table-basic-example.html***
```
<table mat-table [dataSource]="dataSource" class="mat-elevation-z8" [trackBy]="trackByIndex">
```

***table-basic-example.ts***
```
trackByIndex(index, item) {
   return index;
}
```
  
#### Environment

- Angular: 6.1.9
- CDK/Material: 6.4.7
- Browser(s): Google Chrome Version 76
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment]
I suspect you are changing the data such that the index for each item changes, e.g. the item in the 10th spot may change to be in the 5th spot. You should try to use a more unique identifier for the data
