### ISSUE TITLE
Autosize is mentioned different in the docs than in the Stack Blitz example

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#17112]
#### Documentation Feedback

[Documentation for Input AutoSize](https://material.angular.io/components/input/api ) 
mentions to use 
`@Input('mat-autosize')
matAutosize: boolean` 

[But in the Stack Blitz example for Auto-resizing textarea](https://stackblitz.com/angular/pbadbpbgyog?file=app%2Ftext-field-autosize-textarea-example.html)  I see `  <textarea matInput
            cdkTextareaAutosize
            #autosize="cdkTextareaAutosize"`

I would like to know which one is the correct one Thanks.
Also note: the docs don't have mention of `maxlength="300"` max length characters anywhere for the same

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** [https://material.angular.io/components/input/overview](https://material.angular.io/components/input/overview)

**Comment by crisbeto** [comment]
`matAutosize` is marked as deprecated and is only there for backwards compatibility. You should use `cdkTextareaAutosize`.
