### ISSUE TITLE
CDK Portal throws Error: "HierarchyRequestError" in IE11

### ISSUE THREAD

**Issue by Schoko19961** [angular/components#17110]
#### Bug:
When CDK portal is used to project content into a new window. It is throwing Error: "HierarchyRequestError" in Internet Explorer 11.

#### What is the expected behavior?
The projected content is visible in the new Window.

#### What is the current behavior?
Internet explorer throws an error and the content is displayed in the component which includes the Portal. It is working fine in Chrome & Firefox

#### What are the steps to reproduce?
app.component.html
```html
<button (click)="show()">Click me!</button>

<ng-container *cdkPortal>
  <h1>This should be visible in the new Window</h1>
</ng-container>
```
app.component.ts
```ts
import { CdkPortal, DomPortalOutlet } from '@angular/cdk/portal';
import {
    ApplicationRef, ChangeDetectorRef, Component, ComponentFactoryResolver, Injector, ViewChild
} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  @ViewChild(CdkPortal, { static: true })
  portal: CdkPortal;

  constructor(
    private componentFactoryResolver: ComponentFactoryResolver,
    private applicationRef: ApplicationRef,
    private injector: Injector,
    private changeDetector: ChangeDetectorRef) {

  }
  show() {
    const externalWindow = window.open('', '_blank', 'width=500px,height=500px');
    const host = new DomPortalOutlet(externalWindow.document.body, this.componentFactoryResolver, this.applicationRef, this.injector);
    host.attach(this.portal);
    this.changeDetector.detectChanges();
    externalWindow.focus();
  }
}
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: v8.0.1
Angular/cdk: v8.2.0
Browser: Internet Explorer 11

**Comment by crisbeto** [comment]
I'm not sure whether we can do much about it. AFAIK IE doesn't allow for DOM nodes to be moved from one window to another. The workaround usually is to use `innerHTML`, but that's not an option for the CDK portal.

**Comment by jelbourn** [comment]
Closing since this is a fundamental limitation of IE11
