### ISSUE TITLE
Mat-tab first selected tab is rendered as inactive

### ISSUE THREAD

**Issue by leomayer** [angular/components#17124]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-y4kyje?file=app%2Ftab-group-basic-example.css
Pictures are attached in [Stackoverflow](https://stackoverflow.com/q/57989219/325868) (with some additional conversation)

Steps to reproduce:
1. Create a mat-tab-group
2. Open it, first tab is selected
 
 
#### Expected Behavior

What behavior were you expecting to see?

The label and the badge should be rendered as active.

#### Actual Behavior

What behavior did you actually see?

The label and the badge should be rendered as inactive.

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chorme
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

Note:
Fixing as mentioned in Stackoverflow is possible - but the way to fix it is deprecated.

**Comment by tomicarsk6** [comment]
In the [documentation](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) says that preferred way is to use ::ngDeep for a broader compatibility with the tools.

So in my opinion is safe to use ::ngDeep until further notice.

**Comment by olliechick** [comment]
Also, as soon as you click on something that is not the tab, it is rendered as inactive.

**Comment by crisbeto** [comment]
The underline under the tab label is the selected indication, not the change in opacity. It's also worth noting that the reduced opacity will be removed in the MDC version of the tabs.
