### ISSUE TITLE
mat-select with panelClass to position options underneath trigger prevent mat-select-trigger from being clicked

### ISSUE THREAD

**Issue by mattduggan** [angular/components#17128]
#### Reproduction

https://stackblitz.com/edit/angular-jgairm

Steps to reproduce:
1. Create global class with margin-top to position .mat-select-panel below the mat-select-trigger when open
2. Add class to panelClass attribute of mat-select
3. Click mat-select-trigger to open panel
4. Click mat-select-trigger again to close panel

#### Expected Behavior

mat-select-panel closes

#### Actual Behavior

mat-select-panel does not close

#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

### Notes

This appears to be an issue with the positioning of .cdk-overlay-pane, but it's unclear how to reposition that via overlayDir (`CdkConnectedOverlay`).

**Comment by crisbeto** [comment]
The select has no way of knowing where the panel is going to go from the custom `panelClass`. Overriding the built-in styles with `panelClass` is at your own risk.
