### ISSUE TITLE
MatCheckbox doesn't check on mobile in certain conditions

### ISSUE THREAD

**Issue by KyleDavis** [angular/components#17146]
#### Reproduction
I am not able to reproduce this on stackblitz, only in my current project.

When the viewing the page in mobile, clicking on the checkboxes causes the ripple effect on the background but does not check the checkbox.

1. Open https://test.aryv.com/checkbox-test either on a mobile device, or set chrome to a device through dev tool and reload. The page must be loaded with chrome set to a mobile device.

2. Click on the checkbox
 
#### Expected Behavior

The checkbox should be checked.

#### Actual Behavior

The ripple effect displays but the checkbox is not checked.

#### Environment
My project is currently on 7.2, but this behavior exists on 8.2 as well.
- Angular: 7.2.8, 8.2.7
- CDK/Material: 7.2, 8.2
- Browser(s): Chrome, iOS Safari
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Android, iOS

**Comment by crisbeto** [comment]
I can definitely reproduce it in your example, but nowhere else (the docs site or our dev app). Could it be something in your app that's interfering with it?

**Comment by devversion** [comment]
Hello! I was trying to look into your issue, but unfortunately the reproduction does not work anymore (our bad since we took so long to take this up again; sorry!).

Please resubmit a new issue if this still surfaces. Thanks!

**Comment by KyleAlanDavis** [comment]
I resubmitted #19466 and reworded the repro steps a bit. You have to load the page after it is in mobile view if you are doing it through Chrome Dev tools. (or reload after setting to mobile view). I'm guessing that's what happened when you checked it, because it still repros the same?
