### ISSUE TITLE
[MdSelectionList/MatListOption] Add readonly support for items

### ISSUE THREAD

**Issue by diosney** [angular/components#17141]
#### Feature Description

Right now only `disabled` is supported for items, which excludes the option if they were previously selected from the final result.

With `readonly`, the items wouldn't be able to be interacted with but if they were previously checked, then they make it to the final result.

#### Use Case

To have selection list with items visually stylized as readonly that cannot be checked/unchecked due some business conditions.

Reference: 

https://material.angular.io/components/list/api#MatListOption

**Comment by crisbeto** [comment]
You mentioned this in your description:

> Right now only disabled is supported for items, which excludes the option if they were previously selected from the final result.

The intention with the `disabled` binding is that it only blocks user interactions, but if the option is selected any other way (e.g. programmatically), it'll still be shown as selected and will propagate to the model. From my testing it seems like it works as expected. Can you post example where it doesn't work like that?

**Comment by diosney** [comment]
@crisbeto Thanks, I still am figuring this out, changing constantly the code to corner what it is happening, maybe it is a miss-configuration from my side, if I'm able to determine was it was I will post it here.

Thanks again.

**Comment by diosney** [comment]
@crisbeto You are right, I'm sorry, all points out that the related logic to that specific field was the culprit.

I cleaned up everything (a 2 level formGroup, a valuesChanges on a main field responsible to updating the select-list, and added a missing `compareWith`) and worked like a charm.
