### ISSUE TITLE
ERROR in node_modules/@angular/material/tooltip/typings/index.d.ts.TooltipComponent.html(1,51): Argument of type 'Observable<BreakpointState>' is not assignable to parameter of type 'Promise<any>'.   Type 'Observable<BreakpointState>' is missing the following properties from type 'Promise<any>': then, catch, [Symbol.toStringTag], finally

### ISSUE THREAD

**Issue by LuomingXu** [angular/components#17140]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.  ng build --prod --output-path docs --base-href //

 
#### Expected Behavior

What behavior were you expecting to see?
ng build --prod success

#### Actual Behavior

What behavior did you actually see?
ng build error

#### Environment

- Angular: 8.3.4
- CDK/Material: 8.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Win

**Comment by LuomingXu** [comment]
I change @angular/material/tooltip/typings/index.d.ts line: 162
former: _isHandset: Observable<BreakpointState>;
now: _isHandset: Promise<BreakpointState>;

it works.
Is it a bug?

**Comment by crisbeto** [comment]
Seems like this was a user error that was resolved. Closing.
