### ISSUE TITLE
Possibility to initialize multiple values into mat-button-toggle-group

### ISSUE THREAD

**Issue by FontanyLegall-Brandon** [angular/components#17142]
*After the close of issue https://github.com/angular/components/issues/16780 by the bot, I allow myself to repost it because the proposed solution does not work*

**Proposal:**
Having the possibility to initialize a mat-button-toggle-group with multiple values

Exemple :
```
<mat-button-toggle-group #group="matButtonToggleGroup" value="email,phone" multiple>
                <mat-button-toggle value="email" aria-label="email">
                    <mat-icon>email</mat-icon>
                </mat-button-toggle>
                <mat-button-toggle value="phone" aria-label="phone">
                    <mat-icon>phone</mat-icon>
                </mat-button-toggle>
</mat-button-toggle-group>
```
Setting value of mat-button-toggle-group with values list

The proposed solution `[value]="['email', 'phone']"` dont work, here is a stackblitz : https://stackblitz.com/edit/angular-vr2sb8?embed=1&file=app/button-toggle-overview-example.html

**Comment by crisbeto** [comment]
Your example doesn't work because you're supposed to bind it as `[value]="['email', 'phone']"`, not `value="['email', 'phone']"`.
