### ISSUE TITLE
Unable to update to v. 8.2.0

### ISSUE THREAD

**Issue by brgrz** [angular/components#17172]
I am getting the following issue trying to upgrade to 8.2.0 and as far as I can understand it says the packages dependencies would somehow break but I don't understand how because it also says those dependeciens only require >= 5 or 6. And why would an update want to bring in "9.0.0-next.7"?

```
ng update @angular/material    
Using package manager: 'npm'
Collecting installed dependencies...
Found 53 dependencies.
Fetching dependency metadata from registry...

                  Package "@auth0/angular-jwt" has an incompatible peer dependency to "@angular/common" (requires ">=6.0.0", would install "9.0.0-next.7").
                  Package "ngx-perfect-scrollbar" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0", would install "9.0.0-next.7").

Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

**Comment by Swoox** [comment]
First of all I see you using 3rd party libs,
Second the dependency doesn't come from materials but from the Angular parts.
Based on the second point you're posting this in the wrong github.

**Comment by brgrz** [comment]
@Swoox other packages are up to date, so are angular packages
