### ISSUE TITLE
ExpansionPanel in content projection in modal closes after first open

### ISSUE THREAD

**Issue by ivanivanyuk1993axelot** [angular/components#17177]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-pjv1un

Steps to reproduce:
1. Open modal
2. Close modal
3. Open modal
 
 
#### Expected Behavior

Expansion panel is opened

#### Actual Behavior

Expansion panel is closed(it has correct class, but style visibility: hidden, height: 0)

#### Environment

- Angular: ~8.2.0
- CDK/Material: ^8.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu, Windows 10

**Comment by TheParad0X** [comment]
Same Problem here.
