### ISSUE TITLE
tabs: programmatically setting selectedIndex should not trigger selectedIndexChange

### ISSUE THREAD

**Issue by hullis** [angular/components#17170]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-vyr7qq?file=app/tab-group-basic-example.html

Steps to reproduce:
1. Click the button.
2. Check the console.
 
 
#### Expected Behavior

What behavior were you expecting to see?

When I programmatically set `selectedIndex`, it should not trigger `selectedIndexChange`. Just like `ngModel` won't trigger `ngModelChange`.

#### Actual Behavior

What behavior did you actually see?

`selectedIndexChange` emits.

#### Environment

> I guess these are irrelevant.

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wendzhue** [comment]
If this is a not a bug, could you please tell me why it's designed like this?

**Comment by djleonskennedy** [comment]
@wendzhue seems like it's not a bug, cause all works well, here a working reproduction

https://stackblitz.com/edit/angular-aa6qhr?file=app/tab-group-basic-example.ts

**Comment by wendzhue** [comment]
@djleonskennedy Yeah. I am just curious why it's designed as this. Not to my instinct and not the same with `ngModel`.

**Comment by djleonskennedy** [comment]
@wendzhue seems `ngModel` (`FormControl`) have a lot more conditions for emit value like disabled, dirty, touched etc.

**Comment by TheParad0X** [comment]
I am having the same problem. I see this as a bug.

**Comment by devversion** [comment]
I think this is a fair request. https://github.com/angular/components/issues/18431#issuecomment-583393610 is related and states that it's up to the consumers to filter out non-user/interaction changes. It's unclear to me what is best here though.

I could imagine that we only fire on interactive changes. That would match with other components (like slide-toggle, checkbox etc.) and generally also matches events from native HTML elements.
