### ISSUE TITLE
CdkDropList breaks when data changes during draging

### ISSUE THREAD

**Issue by SC-JC** [angular/components#17185]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-dbvkgq

Steps to reproduce:
1. Make cdkDropList
2. Add cdkDrag
3. Set Interval to change data every few seconds
 
 
#### Expected Behavior

What behavior were you expecting to see?
It should continue the dragging and choose the new respective data for that index.

#### Actual Behavior

What behavior did you actually see?

It reset the dragging and made it impossible to do any further dragging/dropping essentially removing drag/drop till i reload the page

#### Environment

- Angular: 8.2.6
- CDK/Material: 8.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
This should work if you add a `trackBy` to the `ngFor`. The problem is that there's no way of knowing whether the data was changed because it was removed, or because it was swapped out.

**Comment by SC-JC** [comment]
Sorry for the late update, it seems to resolve the issue.

Thanks again :)
