### ISSUE TITLE
MatCalendarHeader at version8 periodButtonText doesn't display TH local format

### ISSUE THREAD

**Issue by Bhadhorn** [angular/components#17187]
#### Expected Behavior

get periodButtonText(): string {
    if (this.calendar.currentView == 'month') {
      return this._dateAdapter
          .format(this.calendar.activeDate, this._dateFormats.display.monthYearLabel)
              .toLocaleUpperCase();
    }
    if (this.calendar.currentView == 'year') {
      return this._dateAdapter.getYearName(this.calendar.activeDate);
    }
    const activeYear = this._dateAdapter.getYear(this.calendar.activeDate);
    const firstYearInView = this._dateAdapter.getYearName(
        this._dateAdapter.createDate(activeYear - activeYear % 24, 0, 1));
    const lastYearInView = this._dateAdapter.getYearName(
        this._dateAdapter.createDate(activeYear + yearsPerPage - 1 - activeYear % 24, 0, 1));
    return `${firstYearInView} \u2013 ${lastYearInView}`;
  }

#### Actual Behavior

get periodButtonText(): string {
    if (this.calendar.currentView == 'month') {
      return this._dateAdapter
          .format(this.calendar.activeDate, this._dateFormats.display.monthYearLabel)
              .toLocaleUpperCase();
    }
    if (this.calendar.currentView == 'year') {
      return this._dateAdapter.getYearName(this.calendar.activeDate);
    }

    const activeYear = this._dateAdapter.getYear(this.calendar.activeDate);
    const minYearOfPage = activeYear - getActiveOffset(
      this._dateAdapter, this.calendar.activeDate, this.calendar.minDate, this.calendar.maxDate);
    const maxYearOfPage = minYearOfPage + yearsPerPage - 1;
    return `${minYearOfPage} \u2013 ${maxYearOfPage}`;
  }

What behavior did you actually see?
- Look at firstYearInView and lastYearInView on version 6 has getYearName() but version 8 doesn't
that make some locale time display is unusual.

**Comment by crisbeto** [comment]
I'm not sure I follow. Can you elaborate what the issue is?

**Comment by Bhadhorn** [comment]
I try to use mat-calendar to display my local time which is Buddhist year.
https://drive.google.com/open?id=1DRBOXLca0T6ck0zA-EEDpytE6Bt2A8j6
on this current view the button on the left top show correctly but when I click on it
https://drive.google.com/open?id=1lZtimexfH1kseK-HUuFzCq5V-dsklS99
then it move to multi-years view
You can see the year on the button is not Buddhist year as it should be like so that the problem 

and I found that this problem doesn't occur on Angular material version 6 because there is function getYearName() on firstYearInView and lastYearInView  variables on periodButtonText(): which Angular material version 8 doesn't has
