### ISSUE TITLE
matsort cancel pending sort ?

### ISSUE THREAD

**Issue by d00lar** [angular/components#17198]
hello
How do i cancel pending sort on matsort ?
i need mattable with matsort AND resizable columns

so i builded my resizable mattable based on this

https://stackblitz.com/edit/angular-rtfc5v 
because mattable doeas not support it 'from box'

and it works but after every resize - sorting is happening

#### What is the expected behavior?
it would be realy nice to have option to cancel this 'pending' sort ? 
 I tried event.preventDefault(); and event.stopPropagation();. but, the sortstill occurs.

or add mattable resize columns options 'out of the box'

#### What is the current behavior?
it is sorting on every click even  drag etc ven if i do disabled and enabled during this resize but still it is making the sort.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 8.2.7
CDK/Material: 8.2
Browser(s): Chrome 78

**Comment by jelbourn** [comment]
We avoid any kind of cancellation API in Angular Material:
* The accessibility of "cancelling" is tricky- it's hard to communicate to screen-reader users that the expected action didn't happen and why. This would be especially true with e.g. tabs, where it would be very easy to throw off the interaction pattern if you interrupt an expected action with a dialog.
* There's no clear line on which actions would be cancellable and which aren't from an API consistency standpoint. 
* It generally makes the library code more complex and harder to reason about
* It makes any "cancellable" interaction asynchronous
