### ISSUE TITLE
Modal dialog does not block focus reaching the background aria-hidden page

### ISSUE THREAD

**Issue by smhigley** [angular/components#17205]
#### Reproduction

This repros on the docs page for dialog: https://material.angular.io/components/dialog/overview

Steps:
1. Open dialog
2. Jump to the browser URL bar
3. Tab into the page
 
#### Expected Behavior

Focus should not reach inactive page elements

#### Actual Behavior

Focus reaches controls in the background of the page, and with a screen reader running this means hitting tab stops with no semantic information, since they are nested within an element with `aria-hidden`.

#### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): Firefox, Chrome, Edge (likely any browser)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows & macOS

The `inert` attribute is a nice way to fix this if you're willing to take on a polyfill. Otherwise the only other solutions I know of are a global `focusin` listener, or walking the DOM and manipulating `tabindex` for all focusable elements (and then restoring it to the previous value on close)

**Comment by wagnermaciel** [comment]
Duplicate of #9035
