### ISSUE TITLE
Drag drop placeholder in front of elements

### ISSUE THREAD

**Issue by paulferaud** [angular/components#17208]
#### Reproduction

Go on the document page for https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-placeholder

Drag an item from the end of the list, up.
 
#### Expected Behavior
The placholder should be animating "behind" the rows

#### Actual Behavior
When draging an item "up" (index going down), then the placeholder is shown in *front* of the cards:
![image](https://user-images.githubusercontent.com/43784631/65706350-4754e280-e058-11e9-8745-56fd64b9dad8.png)

(note that I added border to the items, and black background, for better visualization)

#### Thoughts
- Playing with z-index has no effect
- Only happens when dragging to a lower index from the initial drag position
- Individual drag position is not relevant, just that it’s a transition at a lower index

#### Environment
- Angular: ?
- CDK/Material: 8.2.1
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The placeholder element is just another element inside the list so changing the `z-index` does work. Here's an example that has it always appearing over the other elements: https://stackblitz.com/edit/angular-1yremt?file=app/cdk-drag-drop-custom-placeholder-example.css.

**Comment by paulferaud** [comment]
Oh. I had to add `position: relative` for it to work. I guess there’s a workaround then. Would be nice if this was included in the generated css though.

**Comment by crisbeto** [comment]
Including it in the generated CSS might be a little too opinionated since it depends very much on the setup of your app and how it's supposed to behave. Closing since it works as expected.

**Comment by paulferaud** [comment]
> Closing since it works as expected.

Thanks.

Would it make sense to fix this by updating the example snippet? I know I implemented by basically copy pasting the snippet, and then tailoring it to my own needs.

Had the z-index been there to begin with, it would have helped.
