### ISSUE TITLE
Ripple shows dots in firefox

### ISSUE THREAD

**Issue by AnisTss** [angular/components#17201]
#### Reproduction

[mat-ripple-bug.zip](https://github.com/angular/components/files/3653889/mat-ripple-bug.zip)

#### Expected Behavior

I expect the ripple animation to be smooth.

#### Actual Behavior

In Firefox it shows noise dots:
![rippleBug](https://user-images.githubusercontent.com/11518540/65625019-e8915980-dfc2-11e9-87fd-d9d258153221.gif)

I am using **Firefox 69.0**
![image](https://user-images.githubusercontent.com/11518540/65625113-18406180-dfc3-11e9-8ea2-1555059ac463.png)

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.2.1
- Browser(s): Firefox 69.0
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
I wasn't able to reproduce it against Firefox 69 both on Windows and on a Mac. Maybe something else in your app is interfering?

**Comment by AnisTss** [comment]
This is happening to me even on the Material site:
![rippleBugMatSite](https://user-images.githubusercontent.com/11518540/65699779-809c4b00-e076-11e9-97b7-845e771f22d4.gif)

**Comment by devversion** [comment]
Hello! I wasn't able to reproduce this issue on my end. Please resubmit a new issue if this still surfaces on your end.
