### ISSUE TITLE
Unable to copy text from disabled matInput on firefox. This works on Chrome and Safari.

### ISSUE THREAD

**Issue by stayingcool** [angular/components#17204]
#### Reproduction
https://stackblitz.com/edit/angular-material-starter-nn9b35?file=app/app.component.html

Steps to reproduce:
1. Try to copy the text from the matInput textbox
2. This works on Chrome and Safari. However, unable to do so on Firefox.
 
 
#### Expected Behavior
We should be able to copy text from a disabled matInput textbox.

What behavior were you expecting to see?
The same behavior as seen in Chrome and Safari

#### Actual Behavior
Unable to copy text from disabled matInput on firefox.

What behavior did you actually see?
Unable to copy text from disabled matInput on firefox. Please look at more information on stackoverflow issue I created to get the feedback from the larger community as well.
https://stackoverflow.com/questions/58073357/unable-to-copy-text-from-disabled-matinput-on-firefox

#### Environment

- Angular:
Angular 7.0.2
- CDK/Material:
7.0.2

- Browser(s):
Chrome, Safari, Firefox (Latest)

- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows and Mac

**Comment by crisbeto** [comment]
It looks like this is a browser limitation since it happens even if you remove all of the Material functionality (`mat-form-field` and `matInput`). Closing since this isn't something we have control over.

**Comment by stayingcool** [comment]
I have added these 2 lines in the stackblitz demo which is plain HTML:
```
<input value="readonly text" readonly>

<input value="disabled text" disabled>
```

You can see there is different behavior in the Firefox browser. 

I'm not worried about whatever approach Angular has taken, just need to have consistent behavior across browsers. I'm using Angular and not plain HTML. Please advise the best way to handle this issue.
