### ISSUE TITLE
'_supportsShadowDom' was not found in '@angular/cdk/platform'

### ISSUE THREAD

**Issue by adamhinckley** [angular/components#17209]
#### Expected Behavior
Successful compile

#### Actual Behavior

ERROR in node_modules/@angular/material/esm2015/autocomplete.js 465:16-34
"export '_supportsShadowDom' was not found in '@angular/cdk/platform'

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Chrome - N/A this is a compiling issue
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

#### Here are the dependencies in package.json
 "dependencies": {
        "@angular/animations": "^8.0.0",
        "@angular/cdk": "~8.0.0",
        "@angular/common": "^8.0.0",
        "@angular/compiler": "^8.0.0",
        "@angular/core": "^8.0.0",
        "@angular/forms": "^8.0.0",
        "@angular/material": "^8.0.0",
        "@angular/platform-browser": "^8.0.0",
        "@angular/platform-browser-dynamic": "^8.0.0",
        "@angular/router": "^8.0.0",
        "@fortawesome/angular-fontawesome": "^0.4.0",
        "@fortawesome/fontawesome-svg-core": "^1.2.18",
        "@gm2/ui-library": "file:libs/ui-library/src",
        "@nestjs/common": "^6.3.2",
        "@nestjs/core": "^6.3.2",
        "@nestjs/jwt": "^6.1.1",
        "@nestjs/passport": "^6.1.0",
        "@nestjs/platform-express": "^6.2.4",
        "@nestjs/swagger": "^3.0.2",
        "@ngxs-labs/dispatch-decorator": "^1.3.1",
        "@ngxs-labs/emitter": "^1.9.0",
        "@ngxs-labs/immer-adapter": "^3.0.5",
        "@ngxs-labs/select-snapshot": "^1.1.0",
        "@ngxs/devtools-plugin": "^3.5.0",
        "@ngxs/router-plugin": "^3.5.0",
        "@ngxs/storage-plugin": "^3.5.0",
        "@ngxs/store": "^3.5.0",
        "@nrwl/angular": "^8.0.1",
        "class-transformer": "^0.2.3",
        "class-validator": "^0.9.1",
        "core-js": "^2.5.4",
        "date-fns": "^2.0.0-beta.2",
        "hammerjs": "^2.0.8",
        "helmet": "^3.18.0",
        "immer": "^3.1.3",
        "lodash": "^4.17.15",
        "ng2-pdf-viewer": "^5.3.3",
        "ngx-toastr": "^10.0.4",
        "passport": "^0.4.0",
        "passport-jwt": "^4.0.0",
        "reflect-metadata": "^0.1.12",
        "rxjs": "~6.4.0",
        "swagger-ui-express": "^4.0.7",
        "zone.js": "^0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.800.0",
        "@angular/cli": "8.0.0",
        "@angular/compiler-cli": "^8.0.0",
        "@angular/language-service": "^8.0.0",
        "@fortawesome/fontawesome-pro": "^5.8.2",
        "@fortawesome/pro-light-svg-icons": "^5.8.2",
        "@fortawesome/pro-regular-svg-icons": "^5.8.2",
        "@fortawesome/pro-solid-svg-icons": "^5.8.2",
        "@nestjs/schematics": "^6.3.0",
        "@nestjs/testing": "^6.2.4",
        "@nrwl/cypress": "8.0.1",
        "@nrwl/jest": "8.0.1",
        "@nrwl/nest": "8.0.1",
        "@nrwl/node": "8.0.1",
        "@nrwl/workspace": "8.0.1",
        "@types/jest": "24.0.9",
        "@types/jquery": "3.3.6",
        "@types/lodash": "^4.14.136",
        "@types/node": "~8.9.4",
        "codelyzer": "~5.0.1",
        "cypress": "3.2.0",
        "dotenv": "6.2.0",
        "jest": "24.1.0",
        "jest-preset-angular": "7.0.0",
        "prettier": "1.16.4",
        "ts-jest": "24.0.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "tslint-eslint-rules": "^5.4.0",
        "typescript": "~3.4.5"
    }
}

**Comment by crisbeto** [comment]
Your dependency on `@angular/cdk` is set to `~8.0.0`, whereas `@angular/material` is set to `^8.0.0`. You should make sure that the CDK and Material versions line up.

**Comment by adamhinckley** [comment]
@crisbeto thanks for replying to this.  I tried your solution and it didn't work.

This is the change I made based on your suggestion.  I'm still getting the same error.  Any other ideas?
```
"dependencies": {
        "@agm/core": "^1.0.0",
        "@angular/animations": "^8.0.0",
        "@angular/cdk": "^8.0.0",
        "@angular/common": "^8.0.0",
        "@angular/compiler": "^8.0.0",
        "@angular/core": "^8.0.0",
        "@angular/forms": "^8.0.0",
        "@angular/material": "^8.0.0",
        "@angular/platform-browser": "^8.0.0",
        "@angular/platform-browser-dynamic": "^8.0.0",
        "@angular/router": "^8.0.0",
        "@capacitor/android": "^1.2.1",
        "@capacitor/cli": "^1.2.1",
        "@capacitor/core": "^1.2.1",
        "@fortawesome/angular-fontawesome": "^0.4.0",
        "@fortawesome/fontawesome-svg-core": "^1.2.18",
        "@gm2/ui-library": "file:libs/ui-library/src",
        "@ionic-native/core": "^5.15.0",
        "@ionic-native/http": "^5.15.0",
        "@ionic-native/splash-screen": "^5.15.0",
        "@ionic-native/status-bar": "^5.15.0",
        "@ionic/angular": "^4.10.1",
        "@nestjs/common": "^6.3.2",
        "@nestjs/core": "^6.3.2",
        "@nestjs/jwt": "^6.1.1",
        "@nestjs/passport": "^6.1.0",
        "@nestjs/platform-express": "^6.2.4",
        "@nestjs/swagger": "^3.0.2",
        "@ngxs-labs/dispatch-decorator": "^1.3.1",
        "@ngxs-labs/emitter": "^1.9.0",
        "@ngxs-labs/immer-adapter": "^3.0.5",
        "@ngxs-labs/select-snapshot": "^1.1.0",
        "@ngxs/devtools-plugin": "^3.5.0",
        "@ngxs/router-plugin": "^3.5.0",
        "@ngxs/storage-plugin": "^3.5.0",
        "@ngxs/store": "^3.5.0",
        "@nrwl/angular": "^8.0.1",
        "bcrypt": "^3.0.6",
        "class-transformer": "^0.2.3",
        "class-validator": "^0.9.1",
        "core-js": "^2.5.4",
        "date-fns": "^2.0.0-beta.2",
        "hammerjs": "^2.0.8",
        "helmet": "^3.18.0",
        "immer": "^3.1.3",
        "lodash": "^4.17.15",
        "ng2-pdf-viewer": "^5.3.3",
        "ngx-toastr": "^10.0.4",
        "passport": "^0.4.0",
        "passport-jwt": "^4.0.0",
        "reflect-metadata": "^0.1.12",
        "rxjs": "~6.4.0",
        "swagger-ui-express": "^4.0.7",
        "zone.js": "^0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.800.0",
        "@angular/cli": "8.0.0",
        "@angular/compiler-cli": "^8.0.0",
        "@angular/language-service": "^8.0.0",
        "@fortawesome/fontawesome-pro": "^5.8.2",
        "@fortawesome/pro-light-svg-icons": "^5.8.2",
        "@fortawesome/pro-regular-svg-icons": "^5.8.2",
        "@fortawesome/pro-solid-svg-icons": "^5.8.2",
        "@ionic/angular-toolkit": "^2.0.0",
        "@nestjs/schematics": "^6.3.0",
        "@nestjs/testing": "^6.2.4",
        "@nrwl/cypress": "8.0.1",
        "@nrwl/jest": "8.0.1",
        "@nrwl/nest": "8.0.1",
        "@nrwl/node": "8.0.1",
        "@nrwl/workspace": "8.0.1",
        "@types/jest": "24.0.9",
        "@types/jquery": "3.3.6",
        "@types/lodash": "^4.14.136",
        "@types/node": "~8.9.4",
        "add": "^2.0.6",
        "codelyzer": "~5.0.1",
        "cypress": "3.2.0",
        "dotenv": "6.2.0",
        "jest": "24.1.0",
        "jest-preset-angular": "7.0.0",
        "prettier": "1.16.4",
        "ts-jest": "24.0.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "tslint-eslint-rules": "^5.4.0",
        "typescript": "~3.4.5"
    }
```

**Comment by BruneXX** [comment]
Hi, I've the same problem with universal but during build I'm receiving this error, the versions match, the @crisbeto solution do not work in this case.

**Comment by BruneXX** [comment]
I can confirm that there's an issue making the SSR build using angular universal, material and CDK
Angular v8.2.6 with Material v8.2.3 and angular/cdk v8.2.3 thrown this error: https://github.com/angular/components/issues/17209
If it helps someone, downgrading to v8.0.0 was the temporary solution for me. I hope angular team can take a look into this sooner than later..

**Comment by ShankyTiwari** [comment]
I had the same issue, this solved my problem.

```ng update @angular/cdk```

**Comment by BruneXX** [comment]
In my case I've installed the latest version of CDK and Material and
doesn't work.

**Comment by sv615218** [comment]
Hi,
I also had same issue, i was using @angular/cdk 8.0.1, which doesnot had **_supportsShadowDom** so i install @angular/cdk 8.2.3, it worked for me.
npm i @angular/cdk

**Comment by davidilieberman** [comment]
updating @angular/cdk got past the build error, but now I am experiencing a runtime compile error:

./node_modules/@angular/material/esm2015/autocomplete.js 465:16-34
"export '_supportsShadowDom' was not found in '@angular/cdk/platform'

**Comment by vbabak** [comment]
`ng update @angular/cli @angular/core @angular/material @angular/cdk`
helped to me

**Comment by yamraj21** [comment]
> `ng update @angular/cli @angular/core @angular/material @angular/cdk`
> helped to me
