### ISSUE TITLE
[cdk-stepper] Add ability to disable _onKeyDown management

### ISSUE THREAD

**Issue by bradtaniguchi** [angular/components#17210]
#### Feature Description
Right now the cdk-stepper overrides the SPACE and ENTER keys as seen [here](https://github.com/angular/components/blob/master/src/cdk/stepper/stepper.ts#L467)

This prevents use-cases where you want to use these keys in the `matStepLabel`, such as this example where a `mat-form-field` is placed in the `matStepLabel` template ref.

We should provide a way to escape/deactivate this underlying feature for the stepper. 

#### Use Case
(see above)

Here is an example of the current behavior:
https://stackblitz.com/angular/yjpbpelmxqxd?file=app%2Fstepper-overview-example.html

**Comment by devversion** [comment]
Hello! Thanks for this issue! I'd love to take a look at your issue/feature request, but I don't quite follow on the use-case. You are mentioning that you want to have a form-field inside the step label (that has these prevented keydown events).

I don't see that in the provided StackBlitz and I'm wondering if there is a good concrete use-case?

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
