### ISSUE TITLE
[MAT-TABLE] Combining each column filtering and sorting in mat-table

### ISSUE THREAD

**Issue by abhinavnigam99** [angular/components#17215]
#### Reproduction

https://stackblitz.com/edit/components-issue-ckdrt3?file=app%2Fapp.component.ts

Steps to reproduce:
1. Just run the app
2. You will find filter form field and column name are aligned to each other.
3. If you remove matSort completely everything is fine with filter below column name.
 
 
#### Expected Behavior

Mat Sort should be attached with column.
Since filter must be added between th of ng-container it gets distorted once we add matSort

#### Actual Behavior

matSort and matFilter for each column should behave in a way that they don't misalign the content

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by andrewseguin** [comment]
Not sure what the best approach here is but its unlikely that we will add more styling to fix this case since it is unlikely. You could add some top margin to the form field to line it up with the text to its left
