### ISSUE TITLE
When mat-ripple is used in mat-table, it does not work as intended

### ISSUE THREAD

**Issue by kaito3desuyo** [angular/components#17214]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ufywnm

Steps to reproduce:
1. Import MatTableModule and MatRippleModule
2. add ``matRipple`` to ``<tr mat-row>``
 
 
#### Expected Behavior

Ripple appears only in the clicked table row.

#### Actual Behavior

Ripple appears throughout the table.

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): Chrome 76.0.3809.132
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 x64

**Comment by andrewseguin** [comment]
Unfortunately this is the limitation to tables in the browser - rows do not have a typical layout scheme as most other rendered containers. To see this, try adding a child to the row, just like ripple does, and set it to absolutely position itself to `top: 0; left: 0; right: 0; bottom: 0`. Youll see that it does not fill the row's element
