### ISSUE TITLE
IconRegistry: Add api for listing available icons

### ISSUE THREAD

**Issue by epelc** [angular/components#17219]
#### Feature Description

You should be able to list available icons using the `MatIconRegistry`. Currently this is not exposed or really tracked besides for elements currently in the dom.

#### Use Case

Creating an icon picker from all available icons without passing in predefined lists or loading config files which generated your icon sets again.

**Comment by jelbourn** [comment]
I think that this feature is a bit too niche to warrant adding an API. Since the application controls the icons that are going into the icon registry, it does have the ability to know the icons available.
