### ISSUE TITLE
mat-progress-bar animation stops if route transition animation is present in Safari

### ISSUE THREAD

**Issue by semykov** [angular/components#17233]
#### Reproduction

StackBlitz to reproduce the issue: https://stackblitz.com/edit/angular-wf5g7b

Issue is reproducible in Safari browser. See details below.

Steps to reproduce:
1. Create simple app with two routes and simple navigation between them.
2. Add route transition animation
3. Add mat-progress-bar with 'indeterminate' mode to one component.
4. When you navigate from one screen to the screen with progress bar, the progress bar does not animate.
 
 
#### Expected Behavior

Inteterminate progress bar should keep animating.

#### Actual Behavior

Inteterminate progress bar stops animating.

#### Environment

- Angular: 8.2.8
- CDK/Material: 8.2.1
- Browser(s): Safari 13.0.1
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Mojave 10.14.6

**Comment by ilinyhsergey** [comment]
I have the same issue on Safari 12.1 on macOS Mojave

**Comment by moritzgloeckl** [comment]
This also occurs on any iPhone app running Ionic inside a `WKWebView`.

**Comment by crisbeto** [comment]
I can see the issue, but I don't think there's anything we can do about it. The progress bar is animated using CSS and the browser can decide to pause the animation if there's a lot of scripting going on in the main thread (e.g. when a new route is being created).
