### ISSUE TITLE
Moment date adapter with Material datepicker strict mode issue

### ISSUE THREAD

**Issue by brgrz** [angular/components#17235]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-qn3txm

Steps to reproduce:
1. Strict mode for moment adapter is turned on in app.module providers section
2. valuechanges is set up at the form
3. When user starts typing in date, for instance types in "10" and stops, the valuechanges should fire with the value of Moment date object being invalid (invalid: true).
4. Currently it fires with the Moment date value being expanded to 10/01/2019, making it valid date. Now, this could be ok behaviour prior we had the strict mode or when strict mode is off but not when it is turned on.
 
#### Expected Behavior

For incomplete dates entered into the form the Datepicker/Moment date adapter currently works in a way of "autocompleting" the value to the current month, which is unwanted when strict mode in turned on.

#### Actual Behavior

If user enters "10" currently the datepicker/dateadapter expands it to 10/1/2019 (for default en-us locale being in use). Even when strict mode is on.

#### What behavior were you expecting to see?

The Moment value from the datepicker value should be invalid (or maybe null).

#### Environment

- Angular: 8.2.8
- CDK/Material: 8.2.1
- Browser(s): latest chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by brgrz** [comment]
Please note: the date locale is set to "sl" inside the app.module.ts but for some reason Stackblitz is not picking it up and the datepicker is being served with default locale but the same issues manifests with this locale as well.

**Comment by crisbeto** [comment]
That's because you need to add `MAT_MOMENT_DATE_ADAPTER_OPTIONS` to the `deps` array when you provide the datepicker adapter. [Here's a working fork of your example](https://stackblitz.com/edit/angular-axd7fx?file=src/app/app.module.ts).

**Comment by brgrz** [comment]
@crisbeto Thank you. This is not documented anywhere within the Docs.

**Comment by crisbeto** [comment]
I'm not sure whether we should call it out explicitly since this is how DI works in general, it's not something specific to Material. We might have to correct it if we have any live examples though.

**Comment by brgrz** [comment]
It's just that there's talk about configuring date adapter and providing it (making it seem that alone is enough to just work) but no text or API description or example code mentions that you have to inject the date adapter options into the Deps for date adapter provider, which is way I easily overlooked that.

**Comment by crisbeto** [comment]
The docs have been updated in #17259.
