### ISSUE TITLE
Bug with mat-label & mat-autocomplete on iOS

### ISSUE THREAD

**Issue by AnnaRainier** [angular/components#17231]
#### Reproduction
On iOS devices in safari mat-label (that should auto float) overlaps input text
Reproducible on https://material.angular.io/components/autocomplete/examples
https://stackblitz.com/angular/goyoyymgdgp?file=app%2Fautocomplete-simple-example.ts

screenshot with the issue
[https://drive.google.com/file/d/0BwabUX8IWhojajRxUWxiWDZ1Q1ZUUWlyVGhrWnI4dUtfbjFv/view?usp=sharing](url)

Steps to reproduce:
1. Focus on input field with autocomplete
2. Select any option proposed in autocomplete
3. Blur input
4. Focus on input again
5. Remove all text from input
6. Select other option from autocomplete
 
#### Expected Behavior
After another option gets selected, label floats up

#### Actual Behavior
After another option gets selected, label overlaps input text

#### Environment

- Angular: 8+
- CDK/Material: 8+
- Browser(s): iOS Safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 13.0+

**Comment by FlorinPorusniuc** [comment]
I have the same problem. Are there any news related to this issue?

**Comment by KyryloPorozhnii** [comment]
I have the same issue too.
Any updates?

**Comment by lousley** [comment]
I have the same issue too.

**Comment by IgorIevgeniev** [comment]
Any updates on this? The bug appeared after iOS13 update.

**Comment by AnnaRainier** [comment]
https://github.com/angular/components/pull/17676
have requested a PR with a fix for this

**Comment by AnnaRainier** [comment]
looks like this doesn't reproduce anymore in v.9.2.4, closing the issue
