### ISSUE TITLE
Release script fails if github API rate limit is exceeded

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#17240]
It exceeded the rate limit for GitHub API, which is causing the release script to fail. In this rare case, it'd be nice to pass in an oath token in this case

**Comment by devversion** [comment]
We should be able to just consume a token from `process.env.GITHUB_TOKEN` (or other aliases). The token is already required for the merge script and other `ng-dev` tools

**Comment by devversion** [comment]
Closing as we'll rely on authentication with the new release script for dev-infra 😄
