### ISSUE TITLE
build(release): generates invalid semver versions and breaks material.angular.io builds

### ISSUE THREAD

**Issue by Splaktar** [angular/components#17264]
#### Reproduction
Steps to reproduce:
1. Release a new version
 
#### Expected Behavior
Only valid semver should be used for the versions in https://github.com/angular/material2-docs-content/blob/8.2.x/package.json

#### Actual Behavior
We’re appending partial commit SHAs to the end of the versions, i.e. `8.2.0-c29c507`, `8.2.1-a5d2ed8`, and the latest `8.2.2-0462599`.

However, `8.2.2-0462599` is not valid semver, so yarn won’t install it.

You can check using this validator: https://jubianchi.github.io/semver-check/#/8.2.2-0462599/8.2.2-0462599

The leading `0` is the issue. It doesn’t accept versions like `01.02.03`, it has to be `1.2.3`.

Checking with the `0` removed, says valid semver (https://jubianchi.github.io/semver-check/#/8.2.2-462599/8.2.2-462599).

The related commits:
- https://github.com/angular/material2-docs-content/commit/069a66bd81564f6e6f96d6a5737a4c5d99db02bb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- https://github.com/angular/components/commit/04625994e04120a42a5608140898868293de2f09

#### What is seen when trying to build material.angular.io
```sh
$ yarn install
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
error Can't add "@angular/material-examples": invalid package version "8.2.2-0462599".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by devversion** [comment]
Seems like this is an issue we always had since introducing snapshot builds. The issue is generally quite rare as not every SHA starts with a leading zero. Definitely a good catch 😄 

Here is a fix: #17267
