### ISSUE TITLE
Drag drop cdk blocks native dragenter/dragleave listeners

### ISSUE THREAD

**Issue by timstoddard** [angular/components#17261]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-cdk-drag-drop-issue

Steps to reproduce:
1. Create a list of `cdkDrag` items in a `cdkDropList` container.
2. Add to each item, a directive that has a `@HostListener` for `'dragenter'` and `'dragleave'` events.
3. Drag the items around, the host listeners do not fire when one item is dragged over another.
 
 
#### Expected Behavior

What behavior were you expecting to see?
Native drag events should fire.

#### Actual Behavior

What behavior did you actually see?
Native drag events do not fire.

#### Environment

- Angular: 8.2.8
- CDK/Material: 8.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

#### What I'm Really Trying to Do

I want to make my own version of placeholders on top of the drag/drop api. I'm working on an app where the draggable items can take up most of the screen width, so we just want to show a line (in css just a border on whichever item as necessary, not an actual element) as a placeholder, that moves to the left side of an item if the user hovers over the left half and vice versa for the right. I'd like to use the dragenter/dragleave events to know when to apply the placeholder class to a certain item, because otherwise I pretty much have to calculate which item is being hovered based on the mouse position relative to the items in the drop list.

**Comment by crisbeto** [comment]
We block a bunch of native events in order to prevent things like scrolling and text selection, but we provide alternatives to them. You should be able to use the `cdkDropListEntered` and `cdkDropListExited` events.

**Comment by timstoddard** [comment]
I tried using the `cdkDropListEntered` and `cdkDropListExited` events, but those only fire when the containers are entered/exited. I want to fire events when any draggable item is dragged over another item in the list.

**Comment by crisbeto** [comment]
Did you try using `cdkDropListSorted`? It fires when the positions of any of the items have been swapped.

**Comment by timstoddard** [comment]
I have tried that. However, in our app we have `cdkDropListSortingDisabled` on the drop list since the items are very wide so we don't want them to be moved around while the user is dragging. Hence why I wanted to use native drag/drop events.

**Comment by ShakinFire** [comment]
Hey guys. I am facing the same issue where `cdkDropListExited` event is triggered only when you drag the item in another list or the initial one. Is there an event that is triggered right after you leave the `cdkDropList` boundaries? For example - if you leave the boundaries of the list you were trying to drag an item to, the item reset its initial position.

**Comment by ShakinFire** [comment]
**Update:** Something as a workaround to the above would be to check the property `isPointerOverContainer` on the `CdkDragDrop` event. It is a toggle for hovering in and out of a container.

**Comment by crisbeto** [comment]
Closing the issue since we have to block native events in order to provide a consistent dragging experience across devices. As mentioned above, we provide custom events that should be the equivalent of the native ones. Please post a feature request if a particular event is missing or doesn't have an equivalent.
