### ISSUE TITLE
enterPredicate called every cdkDropList

### ISSUE THREAD

**Issue by doyeonOh** [angular/components#17266]
enterPridicate is called on every cdkDropList on dragMove.

#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

> working
- cdk 7.1.0
- https://stackblitz.com/edit/angular-dragdrop-cdk7?file=package.json

> Not working
- cdk 8.2.0
- https://stackblitz.com/edit/angular-dragdrop-cdk8?file=package.json

Steps to reproduce:

1. Drag and drop the box.
2. Check log in console window
 
 
#### Expected Behavior

What behavior were you expecting to see?
- I was expecting enterPredicate to only work on the drop target cdkDropList when dragging and dropping.

#### Actual Behavior

What behavior did you actually see?
- Only the drop target cdkDropList does not work and enterPredicate is called on all cdkDropLists.
- cdk 7.1.1 will work as intended, but 8.2.0 will not work as intended.
 
#### Environment

- Angular: 8.2,0
- CDK/Material: 8.2.0
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): ubuntu 19.04

**Comment by gonlliuk** [comment]
@crisbeto Hello! Could you tell me, when the issue's PR will be merged and new version of cdk will be published to npm? We want to release a new version of our app in a few days, and just don't know, should we wait for this bug fix? Thx a lot :)

**Comment by crisbeto** [comment]
This isn't super high on our priority list so it probably won't make it into release within the next few days.
