### ISSUE TITLE
Mat Bottom Sheet Rendering Error

### ISSUE THREAD

**Issue by AvaGanesh** [angular/components#17277]
When openBottomSheet() is called the following error appears;

//Component where it is called
constructor(private fb:FormBuilder,private bottomSheet: MatBottomSheet,private snackBar:MatSnackBar) { }

  openBottomSheet(): void {
    this.bottomSheet.open(BottomSheetComponent);
  }

//Module 
import { NgModule } from '@angular/core';
// import { BrowserModule } from '@angular/platform-browser';

import {MATERIAL_SANITY_CHECKS} from '@angular/material/core';
import { CommonModule } from '@angular/common';
import { RuleconfigComponent } from './ruleconfig.component';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import {MatCardModule} from '@angular/material/card';
import { Routes, RouterModule } from '@angular/router';
import {MatGridListModule} from '@angular/material/grid-list';
import { LightComponent } from './light/light.component';
import {MatStepperModule} from '@angular/material/stepper';
import {MatDividerModule} from '@angular/material/divider';
import {MatSnackBarModule} from '@angular/material/snack-bar';

// import {MatTableDataSource} from '@angular/material/table';
import {MatDialogModule} from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import {MatCheckboxModule} from '@angular/material/checkbox';
import { LottieAnimationViewModule } from 'ng-lottie';
import {MatTableModule} from '@angular/material/table';
import {MatInputModule} from '@angular/material';
import {MatSelectModule} from '@angular/material/select';
import {MatFormFieldModule} from '@angular/material/form-field';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { SelectDropDownModule } from 'ngx-select-dropdown';
import {MatBottomSheetModule} from '@angular/material/bottom-sheet';
// import { AngularBottomSheetModule } from 'angular-bottom-sheet';

// import { MatPaginator } from '@angular/material/paginator';

import 'hammerjs';
import { FormflowComponent } from './formflow/formflow.component';
import { FormflowminimalComponent } from './formflowminimal/formflowminimal.component';
import { AdditionalConfigComponent } from './additional-config/additional-config.component';
import {MatTabsModule} from '@angular/material/tabs';
import { BottomSheetComponent } from './bottom-sheet/bottom-sheet.component';

const routes: Routes = [{
  path: '',
  component: RuleconfigComponent,
  children: [
    {
        path: 'light',
        component: LightComponent,
    },
    {
        path: '',
        redirectTo: 'light',
        pathMatch: 'full',
    },
    
  ],
}];

@NgModule({
  declarations: [RuleconfigComponent, LightComponent, FormflowComponent, FormflowminimalComponent, AdditionalConfigComponent, BottomSheetComponent],
  imports: [
    CommonModule,
    MatButtonModule,
    // MatTableDataSource,
    NgbModule,
    MatCardModule,
    MatTableModule,
    MatSelectModule,
    MatGridListModule,
    FormsModule,
    ReactiveFormsModule,
    MatBottomSheetModule,
    MatDividerModule,
    MatTabsModule,
    SelectDropDownModule,
    MatSnackBarModule,
    MatInputModule,
    MatStepperModule,
    MatDialogModule,
    MatCheckboxModule,
    MatFormFieldModule,
    LottieAnimationViewModule.forRoot(),
    // MatPaginator,
    RouterModule.forChild(routes)
  ],
  providers: [ {
    provide: MATERIAL_SANITY_CHECKS,
    useValue: false
 },],
  entryComponents:[BottomSheetComponent]
})
export class RuleconfigModule { }

///*** Error ***///
LightComponent.html:5 ERROR TypeError: Cannot read property 'appendChild' of undefined
    at NbOverlayContainerAdapter._createContainer (index.js:1043)
    at NbOverlayContainerAdapter.getContainerElement (overlay.js:768)
    at Overlay._createHostElement (overlay.js:3200)
    at Overlay.create (overlay.js:3159)
    at MatBottomSheet._createOverlay (bottom-sheet.js:665)
    at MatBottomSheet.open (bottom-sheet.js:565)
    at LightComponent.openBottomSheet (light.component.ts:83)
    at LightComponent.submitHandler (light.component.ts:87)
    at Object.eval [as handleEvent] (LightComponent.html:5)
    at handleEvent (core.js:43992)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    OS :  Windows 10
    Libraries:
    "@angular-devkit/build-angular": "~0.803.0",
    "@angular/cli": "^8.3.7",
    "@angular/compiler-cli": "~8.2.3",
    "@angular/language-service": "~8.2.3",
  "@angular/common": "~8.2.3",
    "@angular/compiler": "~8.2.3",
    "@angular/core": "~8.2.3",
    "@angular/forms": "~8.2.3",
    "@angular/material": "^8.2.2",
    "@angular/platform-browser": "~8.2.3",

#### Is there anything else we should know?
Same errors are shown in Mat snack bar as well

**Comment by crisbeto** [comment]
It's hard to tell what's going on without seeing what that `NbOverlayContainerAdapter` is doing.

**Comment by devversion** [comment]
Yeah. We won't be able to help with that issue as there isn't enough information provided. Please submit another issue w/ reproduction if this is still an issue.
