### ISSUE TITLE
Custom mat-select panel width affects overlay panel on IE11

### ISSUE THREAD

**Issue by michael-letcher** [angular/components#17276]
#### Reproduction

Set the width of the mat-select to something like 40px.

#11609
 
 
#### Expected Behavior

Width of the drop down to be the same in IE as it is in Chrome

#### Actual Behavior

Width of the drop down is not the same in IE as it is in Chrome but is instead 40px wide

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.1.0
- Browser(s): Chromium: 76.0.3809.100, IE: 11.737.17763.0 
- Operating System (e.g. Windows, macOS, Ubuntu): macOS, Win10

#### Notes

The solution mentioned in #11609 solves the issue

`  
.cdk-overlay-pane {
    display: block;
}
`

**Comment by zhaparoff** [comment]
I've faced the same issue with drop-down panel width in IE 11 using the latest versions of Angular and Material Components:
    "@angular/core": "8.2.12",
    "@angular/material": "8.2.3",
Repro: https://stackblitz.com/edit/angular-material-issue-nt6g9o
Link for IE: https://angular-material-issue-nt6g9o.stackblitz.io

In Chrome overlay pane has dynamic width, trying to display the whole option text.
In IE pane width is fixed to the control width, truncating even short options, especially when we have control width set to some small value.

**Comment by jelbourn** [comment]
I can confirm that, when doing this, the width of the select overlay matches the width of the triggers, truncating items.

**Comment by michael-letcher** [comment]
IE has been deprecated.
