### ISSUE TITLE
datepicker: double role definition in calendar-body.html

### ISSUE THREAD

**Issue by abdulrahman-khankan** [angular/components#17280]
#### Reproduction

There are two role definitions, one `role="gridcell"` and another `role="button"`, isn't it supposed to be only one?

The 2nd role was added about 3 months ago.

https://github.com/angular/components/blob/master/src/material/datepicker/calendar-body.html#L31

https://github.com/angular/components/blob/master/src/material/datepicker/calendar-body.html#L43
 
 
#### Expected Behavior

To have single role on each `<td>`

#### Actual Behavior

There are two `role` definitions for each `<td>`

#### Environment

- Material -> Datepicker -> Calender body

**Comment by jelbourn** [comment]
Yep, that's a pretty big oversight

**Comment by crisbeto** [comment]
Definitely a bit overshight, although it looks like browsers were still picking up the correct role. I think the way this is handled is that the last attribute takes precedence.

**Comment by Splaktar** [comment]
This was introduced in PR https://github.com/angular/components/pull/16402 which went into `8.2.0`.

We have a possibly related issue in https://github.com/angular/components/issues/17689.
