### ISSUE TITLE
cdkDrag breaks scrolling when element dropped to original position

### ISSUE THREAD

**Issue by aeslinger0** [angular/components#17287]
#### Reproduction

Steps to reproduce:
1. Using a touch-screen laptop, go to https://stackblitz.com/edit/cdkdragstartdelay-bug-demo
2. Shorten the window so the scrollbar appears
3. Touch and hold an element for > 1 sec (because cdkDragStartDelay is set to 1000) and then drag around the screen - drop element back in original position
4. Attempt to scroll the page by touching the **same element** and moving up or down within 1 second (before cdkDragStartDelay elapses). Notice the page will not scroll unless you begin by touching anything other than that element.
 
#### Expected Behavior

The screen should scroll when swiping on the element I dragged within the cdkDragStartDelay limit.

#### Actual Behavior

Could not scroll.

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
Should be fixed by https://github.com/angular/components/pull/17150 in 9.0.0-next.0.

**Comment by alcalyn** [comment]
Cool ! Also is the fix will be available on 8.2.x ?

**Comment by crisbeto** [comment]
Most-likely not since we don't usually backport minor fixes. The upgrade to 9.0.0 should be fairly simple though.

**Comment by alcalyn** [comment]
Thank you for having backported it to `8.2.3` :)
