### ISSUE TITLE
Virtual scroll: element out of cdkVirtualFor

### ISSUE THREAD

**Issue by javadRazmjuo** [angular/components#17298]
Open this stackblitz : https://stackblitz.com/edit/angular-c8pvrm
when i scroll down and scroll up ,  before the other elements bind ,   The yellow element appears a little earlier and disappears

**Comment by shanehsu** [comment]
Hi, looking at your example, you put the yellow card inside the viewport, which I believe to be an unsupported use case. 

The viewport can only manage content that is created using `cdkVirtualFor`, or [to create a parent element for those that needs one][1].

Also, your itemSize does not reflect what your content is in size. 

[1]: https://material.angular.io/cdk/scrolling/overview#elements-with-parent-tag-requirements

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

@shanehsu is right- the virtual scroll viewport should only contain elements managed by `cdkVirtualFor`
