### ISSUE TITLE
Strange Subscriber Memory Leak when using mat-radio-group

### ISSUE THREAD

**Issue by dottodot** [angular/components#17306]
I'm not sure why this is happening and can't see an obvious reason but when I use  mat-radio-group in my template I seem to get and big Subscriber memory leak, and if I remove mat-radio-group that leak no longer occurs.
![Screenshot 2019-10-06 at 13 06 52](https://user-images.githubusercontent.com/811652/66269087-4aac5300-e83c-11e9-86df-93e466c389a7.png)
```
  <mat-radio-group [formControl]="shopService.sort" aria-label="Select an option">
    <mat-radio-button [value]="option.query" *ngFor="let option of shopService.sortOptions">{{option.title}}
    </mat-radio-button>
  </mat-radio-group>
``` 
if I remove the mat-radio-group so I just have the mat-radio-button I also don't get the leak. i.e
```
   <mat-radio-button [value]="option.query" *ngFor="let option of shopService.sortOptions">{{option.title}}
    </mat-radio-button>
```
Just a bit confused as to why this would be happening.

**Comment by crisbeto** [comment]
At what point are you taking the memory snapshot? I tried a similar setup to the one you posted, but I never got any references to a `Subscriber`.

**Comment by dottodot** [comment]
@crisbeto So I'm taking a snapshot on my home page then navigating to the page that uses mat-radio-group and repeating several times and then taking another snapshot. I have also tried on a clean install and can't replicate. So don't understand how this can be happening, all I know is I don't get the leak when mat-radio-group isn't present.

**Comment by crisbeto** [comment]
That's odd. Have you tried shaving off as much as possible? E.g. removing the `ngFor` and the `formControl`?

**Comment by dottodot** [comment]
@crisbeto OK so if I remove the `formControl` I don't get the issue.

**Comment by dottodot** [comment]
the only thing I can think of is the formControl is linked to the following in a service

```
  sort = new FormControl('popular');
```
then elsewhere I'm using `this.shopService.sort.valueChanges` which is part of observable chain. This however is subscribed to using the async pipe which I've always assumed handles the unsubscribing for you.

**Comment by dottodot** [comment]
So I changed the `mat-radio-group` to use `[(ngModel)]` rather than `[formControl]` and the problem has gone.

**Comment by crisbeto** [comment]
Looks like this was resolved and the original issue was coming from the Angular forms module.
