### ISSUE TITLE
MatTable default filter not working with nested objects

### ISSUE THREAD

**Issue by ffirsching** [angular/components#17315]
#### Reproduction

quick example: https://stackblitz.com/edit/angular-r6dfy7

Steps to reproduce:
1. try filtering for a weight
2. no match will be found
 
 
#### Expected Behavior

I would expect, that even though weight is now an object, it get's correctly converted to a string and will be searched accordingly.

#### Actual Behavior

If we take a look at the default filter function in [MatDataSource](https://github.com/angular/components/blob/master/src/material/table/table-data-source.ts) we can see that the output is just [object object] and not the actual values.

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.3
- Browser(s): Chrome  77.0.3865.90
- Operating System (e.g. Windows, macOS, Ubuntu):  Win 10 Version 10.0.18362 Build 18362

**Comment by jelbourn** [comment]
`MatTableDataSource` is meant to be a relatively simple implementation for super minimal use-cases. For richer filtering, you can create a custom data source.
