### ISSUE TITLE
Dialog not closed after animation finished.

### ISSUE THREAD

**Issue by yantrab** [angular/components#17312]
https://stackblitz.com/edit/angular-xhuuhy?file=app%2Fdialog-overview-example.html

open dialog and close it with "no thanks"...

```
  onNoClick(): void {
    const wrapper = document.getElementsByClassName(
      "cdk-global-overlay-wrapper"
    )[0];
    const animation = wrapper.animate([{ left: "0" }, { left: "100%" }], {
      duration: 600,
      easing: "ease-out"
    });
    animation.onfinish = () => this.dialogRef.close();
  }
```

**Comment by crisbeto** [comment]
It's not closing because you need to run it inside `NgZone.run`. That being said, animating the dialog like this isn't something that we support in the first place so it's up to you to make it work.
