### ISSUE TITLE
IE11 Datepicker wrong date

### ISSUE THREAD

**Issue by artecoop** [angular/components#17316]
#### Reproduction
https://stackblitz.com/edit/components-issue-stuebn

Steps to reproduce:
1. open the stackblitz here with IE11 or replicate it on your computer.
2. Open the datepicker
3) it shoud show you the date of September 14, 2020 and September 21, 2020. But IE11 show something like February 9, 2021 and September 9 2021.
 
 #### Expected Behavior
See the correct dates. This applies only to IE. Other browsers are unaffected.

#### Environment

- Angular: 0.803.8
- CDK/Material: 8.2.2
- Browser(s): IE11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by manklu** [comment]
Works for me (Windows 10)

![image](https://user-images.githubusercontent.com/22273143/66722402-59cb6c00-ee0d-11e9-92c9-9ad8b7bc6cc4.png)

**Comment by artecoop** [comment]
mmh, please try to change the dates. 
Strange btw, I also use windows 10

**Comment by manklu** [comment]
Works too. Which locale do you use?

>  I also use windows 10

Then you should change the OS in the environment description.

**Comment by artecoop** [comment]
I'm using windows 10 on fedora boxes. Windows uses en-us as language, the site I'm working on is in italian: on angular, locale is set up both in provide and html tag (<html lang="it">)

**Comment by crisbeto** [comment]
Stackblitz doesn't work on IE11 anymore, but I tried transferring the setup to our dev app and IE worked correctly there.
