### ISSUE TITLE
circular icon button with a strange ripple effect when clicked

### ISSUE THREAD

**Issue by ymchun** [angular/components#17314]
#### Reproduction

Steps to reproduce:
1. use chrome
2. click on icon button
3. see the ripple, it has an angle. 
 
#### Expected Behavior
the button should have circular ripple effect.

#### Actual Behavior
![Untitled](https://user-images.githubusercontent.com/282311/66306051-4747c300-e933-11e9-923f-178573c60ee3.gif)

#### Environment
I tried with firefox, no problem.

- Angular: v8.2.9
- CDK/Material: v8.2.2
- Browser(s): chrome v77.0.3865.90
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I'm running the same version of Chrome and I wasn't able to reproduce it.

**Comment by ymchun** [comment]
Seems it's rare case for some machine running google chrome. I have another mac running the same OS and chrome, no issue at all. :v

**Comment by cmermingas** [comment]
I had this exact same issue with the ripple's lower-left corner a couple of weeks ago but I cannot reproduce it now :-/

When trying to reproduce that, I noticed a similar issue with Safari macOS and iOS:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7100704/68264776-a4589680-000f-11ea-8771-81143fb6e115.gif)

Here's a StackBlitz in case it helps: https://stackblitz.com/edit/angular-material-2-qqqzgc

**Comment by ymchun** [comment]
May be this related to rendering function of chrome on some machine. I tried reinstall chrome and it fixed. But after changing some config of rendering on chrome, the issue show up again.
