### ISSUE TITLE
Doesn't bind ngModel mat-radio-group

### ISSUE THREAD

**Issue by NurGuz23** [angular/components#17327]
Hi,

here the bug. When load exam.lst_questions, doesn't bind values on radios

` <form>
                        <div class="form-group">
                            <div class="group-question" *ngFor="let question of exam.lst_questions; let i = index">
                                <label><b>{{question.d_question}}</b></label>
                                <mat-radio-group class="radio-group" [disabled]='true' name="b_userAnswer" [ngModel]="question.b_userAnswer">
                                    <mat-radio-button class="radio-button" *ngFor="let answer of optionsAnswers" [value]="answer.value">
                                        <span class="mat-radio-label" >
                                            {{answer.desc}}
                                        </span>
                                    </mat-radio-button>
                                </mat-radio-group>
                                <div class="card">
                                    <div class="card-body card-body-anwers">
                                       <div class="desc-question" [innerHTML]="question?.d_answer" ></div>    
                                    </div>
                                </div>    
                            </div>
                        </div>    
                    </form>`

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
