### ISSUE TITLE
Mat-Select with Ag-Grid on Edge

### ISSUE THREAD

**Issue by yosoyju** [angular/components#17321]
#### Reproduction

https://angular-vt3fhy.stackblitz.io

Steps to reproduce:
1. Click on cell in Edge
 
 
#### Expected Behavior

Select box is approximately the same width as the cell.

#### Actual Behavior

Select box is the width of the entire grid.

I believe the problem lies in this line of code:
`this._triggerRect = this.trigger.nativeElement.getBoundingClientRect();`
In Chrome, the trigger element is the cell, but in Edge, I believe it is the grid itself.

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): Edge 44 (but not present in 42)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Looks like this StackBlitz doesn't work any more. Feel free to open a new issue w/ an updated reproduction.
