### ISSUE TITLE
W3C Errors from Validation Checker while running angular material app in browser

### ISSUE THREAD

**Issue by SadhuSa** [angular/components#17338]
Steps to reproduce:
1. To run the W3C Nu Validation Check:

Copy the Source Code
Navigate to https://validator.w3.org/nu/
Select Text Input from the Check by dropdown
Replace the pre-populated code by pasting in the code that you have copied
Select the Check button
2. Auto-generated html code from angular-material components does violate w3c compliance.

i.e block elements can't be used as a child of inline elements.

As this code is auto-generated, Need some help to resolve it
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
There's not enough information here to follow up on; feel free to open a new issue with more specific problems and where specifically they occur.
