### ISSUE TITLE
mat-tab-header-pagination displaying incorrectly

### ISSUE THREAD

**Issue by Anderman** [angular/components#17347]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

mat-tab-header-pagination should only be displayed when the tabs cannot fit inside the container.

#### Actual Behavior

![image](https://user-images.githubusercontent.com/1858745/66525011-59bd2a80-eaf4-11e9-886a-419a76de5801.png)
![image](https://user-images.githubusercontent.com/1858745/66525036-6f325480-eaf4-11e9-9719-81238cf515f9.png)
![image](https://user-images.githubusercontent.com/1858745/66525166-ea940600-eaf4-11e9-86cc-32332f8d64ce.png)

A small rounding problem in chrome?

#### Environment

- Angular:8.2.8
- CDK/Material:8.2.1
- Browser(s):chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows10

**Comment by Anderman** [comment]
I found a workaround  to fix the bug

```
export class ToolbarComponent implements OnInit {
  constructor(public auth: AuthService, private router: Router) { }
  @ViewChild(MatTabNav, { static: true }) public matTabNav: MatTabNav;
  public ngOnInit() {
    this.matTabNav._checkPaginationEnabled = _checkPaginationEnabled;
  }
}

function _checkPaginationEnabled() {
  {
    const isEnabled = this._tabList.nativeElement.scrollWidth > this._elementRef.nativeElement.offsetWidth + 1;
    if (!isEnabled) {
      this.scrollDistance = 0;
    }
    if (isEnabled !== this._showPaginationControls) {
      this._changeDetectorRef.markForCheck();
    }
    this._showPaginationControls = isEnabled;
  }
}

```

**Comment by Anderman** [comment]
related to #8907

**Comment by Anderman** [comment]
@andrewseguin Another cause of wrong pagination is the inkt-bar. If the inkt-bar is outside the navigationbar the scrollwidth of the tablist give the wrong information.
this should be `this._tabList.nativeElement.firstChild.scrollWidth`

To fix this I update the patched function to:
```@javascript
function _checkPaginationEnabled() {
this._elementRef.nativeElement.offsetWidth, 'isEnabled', this._showPaginationControls);
  const isEnabled = this._tabList.nativeElement.firstChild.scrollWidth > this._elementRef.nativeElement.offsetWidth + 1;
  if (!isEnabled) { this.scrollDistance = 0; }
  if (isEnabled !== this._showPaginationControls) { this._changeDetectorRef.markForCheck(); }
  this._showPaginationControls = isEnabled;
}
```

**Comment by jelbourn** [comment]
I wasn't able to reproduce this; feel free to open a new issue if you're able to provide a reproduction in StackBlitz
