### ISSUE TITLE
There is a mat-input for filter in header cell. If I input space in that input field, the column sort will be changed.

### ISSUE THREAD

**Issue by nickyang9206** [angular/components#17357]
<table mat-table class="full-width-table" (matSortChange)="sortData($event)" [dataSource]="data" aria-label="Elements" matSort matSortActive="name" matSortDirection="asc" >

        
        <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>
                <mat-form-field style="margin-top: 0px;">
                    <input matInput placeholder="Name" (keyup)="filter()"  [(ngModel)]="name" >
                </mat-form-field>
            </th>
            <td mat-cell *matCellDef="let user">{{user.name}}</td>
        </ng-container>

**Comment by devversion** [comment]
Hello! This issue doesn't follow our issue templates and we are not sure what's the action here. Please resubmit and follow the templates. We're happy to help!
