### ISSUE TITLE
Stepper should not validate optional form

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#17355]
#### Reproduction

Steps to reproduce:
1. Add a step to a stepper and mark it optional 
2. Provide the step a form control with required fields
3. Add a 2nd step
4. move to the 2nd step.
5. return back to 1st step
 
 
#### Expected Behavior

If a step is optional, no validation on should take place when moving to next step.

#### Actual Behavior

The form is being validated, resulting in misguided interface in warn color on required fields.

#### Environment

- Angular: 8.2
- CDK/Material: 8.2
- Browser(s): Chrome

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
