### ISSUE TITLE
Mat-Tree Selectionmodel Multible false selection not working correctly

### ISSUE THREAD

**Issue by YannikN-Dev** [angular/components#17354]
#### Reproduction
(Sorry for Picture Links to ibb.co, i couldnt upload png's or jpg's here)
What i changed:

I added this to the example tree:

```
  MultiValue: {
    MultiValue: [
      'Multi', 'Value'
    ]
  },
  SingleValue: {
    SingleValue: [
      'SingleValue'
    ]
  },
  SingleValue2: {
    SingleValue2: {
      Single: null
    }
  }
```
and changed the boolean value of multible to false:

` checklistSelection = new SelectionModel<TodoItemFlatNode>(false /* multiple */);`

https://stackblitz.com/edit/angular-nxw3u1?file=app/tree-checklist-example.ts

Steps to reproduce:
1. Select lowest level child of SingleValue or SingleValue2
 
 
#### Expected Behavior

What behavior were you expecting to see?

I expected all parent nodes to be correctly selected when selecting the lowest level node with no siblings on its level

Picture with multible values on the lowest level: [Picture Link](https://ibb.co/n0csVhd)

#### Actual Behavior

What behavior did you actually see?

The immediate parent of the selected element wasnt selected.

Picture with single values on the lowest level: [Picture Link](https://ibb.co/5F8PVWv)
Other picture with single values on the lowest level: [Picture Link](https://ibb.co/YWmfkGP)

#### Environment

- Angular: 8.2.1
- CDK/Material: 8.2.0
- Browser(s): Firefox and Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment]
Hello! I think this might be a question more suitable for StackOverflow. The problem in the code seems that it still assumes that multiple nodes can be selected. e.g. if you look into the `todoItemSelectionToggle` method. It might need more changes of the example to get single selection working.

Closing as I don't see any concrete issue from the Angular Material tree here. Thanks!
