### ISSUE TITLE
Expanding content in mat-card

### ISSUE THREAD

**Issue by doom777** [angular/components#17358]
#### Feature Description

Allow for expanding content in mat-card, as defined in https://material.io/components/cards/

#### Use Case
A card represents some information which takes a lot of space, and does not have to be displayed immediately on load, but rather on demand.

**Comment by jelbourn** [comment]
This isn't something we plan to add to card, which is mostly just a div with a fancy border/shadow. You should be able to use cdk/expansion to accomplish this interaction pattern, though
