### ISSUE TITLE
youtube-player docs use invalid tag syntax

### ISSUE THREAD

**Issue by Dj-jom2x** [angular/components#17368]
https://github.com/angular/components/tree/master/src/youtube-player
<youtube-player></youtube-player> not <youtube-player />
else it will throw
```
 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Only void and foreign elements can be self closed "youtube-player" ("height="200" frameborder="0" allowfullscreen>
```

this part is i have no idea 
```
const tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    document.body.appendChild(tag);
```

but it throws 

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:4200').

 delete this
https://github.com/angular/components/blob/b30aedda8332d7e27d77b32f67fb7b65e88de551/src/youtube-player/youtube-player.ts#L119

so if we don't attach width..  it will auto-fill it.. not the original 640px

**Comment by Dj-jom2x** [comment]
playerVars also is missing.. it says not working it says cant bind... but the docs states is working 
![image](https://user-images.githubusercontent.com/12135498/66652152-8cd3fb00-ec67-11e9-8fbb-8a09d941099b.png)

**Comment by crisbeto** [comment]
This has been fixed in master.
