### ISSUE TITLE
Material input placholder is not displayed in IE11

### ISSUE THREAD

**Issue by muniraji2i** [angular/components#17367]
While using material input using both label and placeholder , placeholder not displayed in IE11

```
<mat-form-field>
<mat-label>Name</mat-label>
<input type="text" matInput placeholder="hello">
</mat-form-field>
```
Placeholder text hello not displayed

**Comment by manklu** [comment]
IE11 doesn't display placeholders if the field is focused.

https://js-jepykr.stackblitz.io/
https://stackblitz.com/edit/js-jepykr

**Comment by crisbeto** [comment]
The previous comment is correct that IE doesn't render placeholders. Closing since Material doesn't polyfill DOM APIs.
