### ISSUE TITLE
Angular_Tables_W3C Errors

### ISSUE THREAD

**Issue by vpadicgifederal** [angular/components#17370]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.Tool used: W3C Nu Validation check.
2. To run the W3C Nu Validation Check:
Copy the Source Code
Navigate to https://validator.w3.org/nu/
Select Text Input from the Check by dropdown
Replace the pre-populated code by pasting in the code that you have copied
Select the Check button
Once the initial check has completed, use HFP's customized version of the parsing bookmarklet to only see the errors that violate WCAG success criterion 4.1.1, which checks for the presence of well-formed HTML markup. For details on where to download and how to use the 4.1.1. Parsing Filter bookmarklet go to: https://alm.cgifederal.com/collaborate/display/HFP/Customization+of+4.1.1+Parsing+Filter
 
 
#### Expected Behavior

What behavior were you expecting to see?

The W3C Nu validate check tool should not throw any html markup errors 

#### Actual Behavior

What behavior did you actually see?
Currently when we ran W3C Nu Validate tool it is throwing 208 errors from the markup which seems not applicable.

#### Environment
Dev,Test and Prod

- Angular:
- CDK/Material:
- Browser(s): Chrome, Firefox and IE
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment]
I'm assuming you're talking about the custom attributes (without a `data-` prefix). This is a part of using Angular and we have no intent to remove these attributes.
