### ISSUE TITLE
Filter Predicate function unit testing with Jasmine

### ISSUE THREAD

**Issue by AniketBhadane** [angular/components#17383]
#### What are you trying to do?

I want to write Unit Tests for MatTable DataSource FilterPredicate function. I'm using Jasmine to write unit tests.

#### What troubleshooting steps have you tried?

I have a filter predicate function which I use to filter a mat-table in angular

```
this.dataSource.filterPredicate = this.myService.tableFilter();

tableFilter(): (data: any, filter: string) => boolean {
    let filterFunction = function (data, filter): boolean {
      let filterValues = JSON.parse(filter);
      ... my logic ...
    };
    return filterFunction;
  }
}
```

I want to write a unit test to test this filter predicate function

```
it('filter table', inject(
    [MyService],
    (service: MyService) => {

      // how to do this?
      let messageObject = service.tableFilter(dummyData, 
        getDummyFilterValues());
    }
  ));
```

#### Environment

- Angular: 8

**Comment by andrewseguin** [comment]
Unfortunately we don't have the resources to answer troubleshooting questions right now - I recommend heading over to StackOverflow to get answers from our community.
