### ISSUE TITLE
Using mat-menu as context menu: How to close opened mat-menu, and open it in another location

### ISSUE THREAD

**Issue by brucebrit** [angular/components#17386]
Angular: v8.2.8
Angular material: 8.2.2

I manage to use  mat-menu (angular material) to emulate the context menu.  Right clicking anyway on my page, the menu appears at my mouse location. 

**What I want to achieve**: when I move my mouse to another location on the page, I right click again. I was expecting the menu at the original location to close, and reopen at the new location. 

**But In reality:** Nothing happen and the menu at the original location remain open, and no menu open at the new location. 

In fact, I have to left click to close the opened menu at original location, followed by right click to open menu at the new mouse location.

**Question:** Any idea how to achieve what I want?

```
@Component({
  selector: 'fl-home',
  template:`
 <mat-menu #contextmenu>
      <div >
           <button mat-menu-item>Clear all Paths</button>
       </div>
  </mat-menu>
  <div [matMenuTriggerFor]="contextmenu" [style.position]="'absolute'" [style.left.px]="menuX" [style.top.px]="menuY" ></div>
  
  <div class="container" (contextmenu)="onTriggerContextMenu($event);"> ....</div>
`})
export class HomeComponent  {

    menuX:number=0
    menuY:number=0

    @ViewChild(MatMenuTrigger,{static:false}) menu: MatMenuTrigger; 
    
   
    onTriggerContextMenu(event){
        
        event.preventDefault();
        this.menuX = event.x - 10;
        this.menuY = event.y - 10;
        this.menu.closeMenu() // putting this does not work.
        this.menu.openMenu()

    }
}
```

**Comment by andrewseguin** [comment]
Unfortunately we are very limited right now on resources, so we cannot take the time to investigate troubleshooting issues right now. It would probably help if you post to StackOverflow with a reproduction of what you are trying to do.
