### ISSUE TITLE
mat-tab-group stops audio/video player on tab leave

### ISSUE THREAD

**Issue by iiiyx** [angular/components#17391]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/angular-otmu5c

Steps to reproduce:
1. start the audio player on the Player tab
2. go to the Description tab
 
 
#### Expected Behavior

Audio continues playing

#### Actual Behavior

Audio stops

#### Environment

- Angular: 8.2.10
- CDK/Material: 8.2.3
- Browser(s): Chrome 77.0.3865.120
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

#### Description
Certainly, this is a premature optimization made at https://github.com/angular/components/blob/14c4dba1b35c52cae893dee23ecf9e4d89f0790b/src/material/tabs/tab-body.ts#L76-L91
Why are you detaching the content of the tab even when a component's user doesn't ask to?

**Comment by iiiyx** [comment]
There are also other issues concerning this detaching. For example, the view of a detached tab is inited empty and the mat-tabs-group user should implement workarounds for this.
A simple example:
there is a video player on the first tab, there is an image editor on the second tab
scenario: the user takes a snapshot from the video and it is loaded to the editor.
issue: editor can't be inited, because its tab has an empty view
workaround: hold the image editor initialization and store the snapshots until the tab view is attached.
But why do we must make such workarounds? We want to just use Tabs!

**Comment by jelbourn** [comment]
Going to track this in #19480
