### ISSUE TITLE
Fire change events upon initialization

### ISSUE THREAD

**Issue by magneticflux-** [angular/components#17398]
#### Feature Description

Components that have change events should fire them when their initial value it set.

#### Use Case

This would let reactive observers of that value receive an initial value, making `BehaviorSubject`s able to be used to track component state.

Currently, to find the value of a component just after init, the component must be injected into its parent using `@ViewChild` and then the value must be manually extracted.

Otherwise, the `BehaviorSubject`'s initial value must be specified in the component's code as well as in the component's template, which is prone to becoming desynchronized during refactoring due to the duplicated code.

##### A concrete use case example

I want to receive `MatPaginator` page events to update my query. I don't want to have to manually trigger it the first time because that would require an additional layer of event handling and/or some spaghetti code, it should just be triggered like every other change event since the value is changing from being absent to being present.

#### Implementation Considerations

This could be a flag that defaults to `false` to prevent breaking existing applications, but I don't think many existing applications would break from this change unless their event handling is very fragile.

**Comment by crisbeto** [comment]
This seems a little arbitrary because we've had multiple issues in the past where people have requested the exact opposite: only dispatching change events if the value changed as the result of a user action.

**Comment by magneticflux-** [comment]
I searched for prior issues on this topic and found #1125 which refers to inconsistency rather than strictly change-on-init or not. In that issue, I noticed that @jelbourn stated that change-on-init was unequivocally a bug, and I'm interested in hearing the reasoning behind that design decision.

I think that firing a change event on init when defaults are set is the more flexible approach, since users could:
1. Simply drop the first event using RXJS `skip(1)` and get the old behavior
2. Enable/disable a flag to control the behavior

**Comment by magneticflux-** [comment]
@crisbeto I'd be happy to start work on a PR with these changes once we have a solid plan of what needs to be done!

**Comment by devversion** [comment]
Yeah, I'd agree with @crisbeto. I think our understanding of this was that we want to match native elements as much as possible. i.e. `input[type=checkbox]` does not emit `change` for its initial value either.

See: https://stackblitz.com/edit/comp-17398?file=src/app/app.component.ts

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'll close this issue, because there hasn't been any activity in a long time and the current behavior is intentional.
