### ISSUE TITLE
Mat-form  outline border

### ISSUE THREAD

**Issue by albahrawy** [angular/components#17390]
I noticed a small bug in outline border calcualtion:
this is an issue with setting a  **_previousDirection** variable in form-field.ts
1- the initial value is 'ltr', regardless if the page is originally loaded with 'rtl' layout.
2- in subscribtion of _dir.changes you call   
this.updateOutlineGap(); before setting the value in    
 this._previousDirection = this._dir.value;  
so the outlineGap calculated on the old value

my work around:
add style of mat-label to:
background-color: white;
padding:10px;

so no need to calculate outline gap.

please advice

**Comment by mohsen77sk** [comment]
This problem persists
I tested in 8.2.3 but it doesn't work

**Comment by AlirezaPhf** [comment]
i update my angular material
but This problem persists
pls help Me

**Comment by mohsen77sk** [comment]
تا زمان حل این مشکل از ورژن 8.2.2 استفاده کنید.

**Comment by jonathanlie** [comment]
we need this change in v8. When is it gonna be merged to the stable version?
