### ISSUE TITLE
MatDialog content scroll broken when padding changed

### ISSUE THREAD

**Issue by oupablo** [angular/components#17394]
#### Reproduction

Changing the padding of the dialog container seems to break scrollable content allowing the user to scroll past the content and clipping the actions in the initial view.

Stackblitz: https://angular-e6ldqp.stackblitz.io

Steps to reproduce:
1. set the mat-dialog-container padding to 0px
2. scroll to the bottom of the dialog
 
 
#### Expected Behavior

Setting the .mat-dialog-container padding to 0px should just remove padding and the dialog-content should scroll within the mat-dialog-content container.

#### Actual Behavior

Setting the padding to 0px breaks the scrolling causing the entire dialog to scroll and hides the title. 

Adding the following to the styles.css seems to resolve the issue but is not ideal.

```
.mat-dialog-actions {
  margin-bottom: 0px !important;
}
```

**Comment by crisbeto** [comment]
There's no way for us to detect this. Since you're overriding our padding, it's up to you to reset the margin as well.
