### ISSUE TITLE
Tabbing on keyboard still selects chip in mat-chip-list when selectable is false

### ISSUE THREAD

**Issue by jpike88** [angular/components#17401]
Basically, I want to be able to allow tabbing on the keyboard to skip a mat-chip-list when ```selectable``` is ```false```, just like I can when ```disabled``` is ```true```.

https://stackblitz.com/edit/angular-dsjch8-65hoje

I use my chips in a form next to my field titles and prefer if users could read them easily AND be able to not have the tab button get stuck in them

**Comment by crisbeto** [comment]
The current API is a little confusing, but `selectable` means being able to mark it as selected using the spacebar, it won't prevent you from tabbing into it. You can distinguish the selected items by their colored background. We have something better coming up that you can trying out by importing the `MatChipsModule` from `@angular/material-experimental/mdc-chips`.
