### ISSUE TITLE
tabs: ink bar inconsistent height/position in Chrome

### ISSUE THREAD

**Issue by tao-cumplido** [angular/components#17403]
#### Reproduction

In Chrome the ink bar below the tabs sometimes has a small gap between the bottom border or appears to have too much height. I took two screenshots from the documentation: https://material.angular.io/components/tabs/examples

In Firefox it looks good, in Chrome it is off.

May have to do with the fact that my desktop scaling is set to 125%, i.e. `devicePixelRatio` is 1.25 in browsers.
 
 
#### Expected Behavior

![image](https://user-images.githubusercontent.com/6384563/66824547-c8611480-ef48-11e9-8763-96dad9565f1c.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/6384563/66824467-a6679200-ef48-11e9-84bd-46af05afd985.png)

#### Environment

- Angular: 8.2.10
- CDK/Material: 8.2.3
- Browser(s): Chrome 77
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Looks like an issue with scaling. I'm closing the issue since we can't do much about how the browser decides to approximate the element size if the screen is zoomed out.
