### ISSUE TITLE
Disable ripple for checkbox 

### ISSUE THREAD

**Issue by ability-app** [angular/components#17404]
#### Reproduction

Steps to reproduce:
1. GoTo a modified example from the docs: https://stackblitz.com/edit/angular-wqcqyp
2. {provide: MAT_RIPPLE_GLOBAL_OPTIONS, useValue: { disabled: true }} inside main.ts
3. mat-checkbox [disableRipple]="true" in checkbox-configurable-example.html
 
 
#### Expected Behavior
IT should not be visible but after updating to angular 8 and Angular material latest version the ripple is visible again even if disableRipple is used, so I added the global disable ripple configuration but still the same

#### Actual Behavior
The ripple on the checkbox on hover is visible although disableRipple and  MAT_RIPPLE_GLOBAL_OPTIONS disabled is specified

#### Environment

- Angular: 8
- CDK/Material: 8.2.4 (same issue with 8.1.4)
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by ability-app** [comment]
Could be connected to:
https://github.com/angular/components/issues/16100

Just add <mat-checkbox>Checked 1</mat-checkbox> to the app.component and you will see that it still has 'hover' effect, It's a regression after i updated from angular material 6, but it could be that I disabled it trough CSS.

**Comment by crisbeto** [comment]
The ripples only refer to the ones that are shown on clicks. It doesn't affect the one that show up in hover or focus, because they're there for accessibility.

**Comment by crisbeto** [comment]
Closing since this is working as expected.
