### ISSUE TITLE
mat-select disableOptionCentering global configuration

### ISSUE THREAD

**Issue by alexw10** [angular/components#17406]
#### Feature Description

Right now in our application we utilize the `mat-select` quite extensively and for each one we want to turn the `disableOptionCentering` to true there does not seem to be a way to do this globally.

This would be really great to have a configuration for because had to one manually add this to each `mat-select` and in the future developers will need to remember to do this and will be hard to maintain letting everyone know that they have to do this.

What would be good is something like what is done for the form field: https://material.angular.io/components/form-field/api#MAT_FORM_FIELD_DEFAULT_OPTIONS

#### Use Case

Makes it so that each developer does not need to know to turn `disableOptionCentering` to true. Gives us a consistent way to always have this on and forget about it essentially and will always be the right behavior in our application.

**Comment by dimitriy-k** [comment]
+ 1
