### ISSUE TITLE
Material icon doesn't show

### ISSUE THREAD

**Issue by ParrotInWeb** [angular/components#17405]
#### What are you trying to do?

I try to display icons on my computer from https://material.io/
https://ibb.co/T2H5dhr

#### What troubleshooting steps have you tried?

I try display icon of Firefox, Chrome, in incognito mode, after and before clean cache

#### Environment

- Angular: 
- CDK/Material: 
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by webtop** [comment]
Did you add the resource link to your index.html file?

**Comment by jelbourn** [comment]
As @webtop mentioned, you're likely missing the icon resource in your application. Closing since there's not much else to say without more information.
