### ISSUE TITLE
BottomSheet underlying page no scroll

### ISSUE THREAD

**Issue by spenoir** [angular/components#17423]
##Bug report
Why in the Angular docs example of a Bottom sheet: https://material.angular.io/components/bottom-sheet/overview does the underlying page, with the Bottom Sheet open, scroll (which is the behaviour I'd like); while in StackBlitz: https://angular-mhukw4.stackblitz.io it doesn't?

###Steps to reproduce
1. Click the button to open the Bottom sheet.
2. Try to scroll the underlying page.

###Actual behavior
Underlying page doesn't scroll while bottom sheet open.

###Expected behavior
Underlying page should scroll while bottom sheet open.

###Possible solution
Set some styles on page containers or body; perhaps flex related rules would help.
If there is specific code for locking the underlying page scroll, expose a boolean in the api for toggling it.

**Comment by crisbeto** [comment]
By default the bottom sheet uses a scroll strategy that blocks scrolling. You can use the `scrollStrategy` config option to pass in a different one.

**Comment by spenoir** [comment]
What is the scrollStrategy for Angular docs?

**Comment by crisbeto** [comment]
You can use `noop` strategy if you don't want it to block.

**Comment by spenoir** [comment]
Ah yeah thanks, just found it in the overlay docs: https://material.angular.io/cdk/overlay/overview#scroll-strategies
