### ISSUE TITLE
Can't drag mat-slider - when Ivy enabled

### ISSUE THREAD

**Issue by theunreal** [angular/components#17420]
#### Reproduction
Any angular project with mat-slider and Ivy enabled

```
"angularCompilerOptions": {
    "enableIvy": false
  }
```

Steps to reproduce:
1. Using mat-slider:

`<mat-slider></mat-slider>`

Enable ivy in tsconfig.app.json:

```
"angularCompilerOptions": {
    "enableIvy": false
  },
```
 
#### Expected Behavior

mat slider should be dragged using the cursor

#### Actual Behavior

Using the cursor to drag the mat-slider is not working when Ivy is enabled.

#### Environment

- Angular: 9.0.0-next.8
- CDK/Material:8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
You probably need to import `HammerModule`. Pre-Ivy it used to be imported by Angular, but it's not anymore. You can also update to the latest Material which doesn't use Hammer for the slider at all.

**Comment by jelbourn** [comment]
Closing this since it's almost certainly due to missing `HammerModule`. Angular Material will also drop its dependency on HammerJS in v9.
