### ISSUE TITLE
Angular Material - Basic Carousel

### ISSUE THREAD

**Issue by ceb-luclin** [angular/components#17437]
#### Feature Description

Initial basic carousel functionality that can be expanded on in future iterations. Basically the ability to choose the following:

- `perView` - sets items visible as the user navigates through the 
- `startsAt` - sets where the carousel should focus on init
- Arrows to move the carousel left/right

#### Use Case

The biggest benefit would be having this centralized in a community package that people can contribute to and support. Other benefits are not having to pull in dependencies like `jQuery` or vanilla packages that have issues with the lifecycle hooks of Angular.

Carousels are a very common component that people use in their Web applications. Would be awesome to see that hosted in Angular Material.

**Comment by jelbourn** [comment]
We currently have no plans to add any type of carousel component.
