### ISSUE TITLE
mat-chip separatorKeyCodes doesn't work if the mat-auto-complete panel is open 

### ISSUE THREAD

**Issue by achrafjdily** [angular/components#17448]
#### Reproduction

Use StackBlitz to reproduce your issue: https://run.stackblitz.com/api/angular/v1?file=app%2Fchips-autocomplete-example.ts

Steps to reproduce:
1. try to write 'app' and tap enter or comma to add the chip 
2. you can't add 'app' in this case because apple is present in the autocomplete
 
 
#### Expected Behavior

The autocomplete should not  prevent the user from adding chips

#### Actual Behavior

The autocomplete prevent adding chips

#### Environment

- Angular:8.1.0
- CDK/Material:8.2.1
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): win 10

**Comment by crisbeto** [comment]
Looks like this is an issue with the example, rather than the component. Will be fixed by https://github.com/angular/components/pull/17558.
