### ISSUE TITLE
mat-tab-body margins

### ISSUE THREAD

**Issue by EKashpersky** [angular/components#17454]
#### Feature Description

Add margirns for mat-tab-body 

#### Use Case

<mat-tab>
  Content with margins by default!
</mat-tab>

#### Tested with Angular Material version
@angular/material 8.2.3

**Comment by crisbeto** [comment]
In general we try to avoid adding margins and padding outside of our elements or around user content, because it's difficult to cater to all cases.

**Comment by EKashpersky** [comment]
@crisbeto I think margins should be there always, aren't they?
https://material.io/design/layout/responsive-layout-grid.html

**Comment by EKashpersky** [comment]
And uh oh, *mat-tab-body* isn't 'outside our element', it's dynamically generated within mat-tab and not accessed from outside.

**Comment by crisbeto** [comment]
That's correct, but it still wraps around user content.

**Comment by EKashpersky** [comment]
@crisbeto by (material) design there's no such a case when a tab could exist without a margin, correct me if i'm wrong.

**Comment by manklu** [comment]
@EKashpersky The specification says nothing about the tab body. Only the tabs itself are defined.

> there's no such a case when a tab could exist without a margin, correct me if i'm wrong.

Put a tab control inside a responsive grid. IMO no need for left and right margin. The gutters and/or margins of the grid are enough.

**Comment by jelbourn** [comment]
Early on, we decided to not add margins to components, deferring to users to decide what works best in their application. We still follow this philosophy.
