### ISSUE TITLE
cdk Table

### ISSUE THREAD

**Issue by gmerabishvili** [angular/components#17463]
I'd like to see a documentation of cdk table with pagination, sorting and etc without Material design. Can anyone guide me how to implement these functionalities without Material? Thank you.

**Comment by crisbeto** [comment]
These are the CDK table docs: https://material.angular.io/cdk/table/overview.

**Comment by gmerabishvili** [comment]
@crisbeto yes, I saw that, but it misses lotta stuff.  I couldn't find any docs about pagination or sorting on server side for example. Like the one an Angular Material table have. Can you help me to implement this functionalities ? I'm creating cdk table with bootstrap table styles.

**Comment by jelbourn** [comment]
You can look at `mat-paginator` and `mat-sort-header` as examples of how you could accomplish this. The CDK itself is agnostic to any particular design system; sort-headers and paginators are inherently tied into a certain look. However, the flow of data between these components and the data source is the same either way.
