### ISSUE TITLE
export '_supportsShadowDom' was not found in '@angular/cdk/platform'

### ISSUE THREAD

**Issue by BruneXX** [angular/components#17470]
Expected Behavior

**Successful compile**

Actual Behavior
ERROR in ./node_modules/@angular/material/esm5/autocomplete.es5.js 463:20-38
"export '_supportsShadowDom' was not found in '@angular/cdk/platform'

Environment
Angular: 8.2.6
CDK/Material: 8.2.6

Browser(s): Chrome - N/A this is a compiling issue

Operating System (e.g. Windows, macOS, Ubuntu): Linux

Here are the dependencies in package.json
  "dependencies": {
    "@angular-devkit/build-angular": "^0.803.1",
    "@angular/animations": "8.2.5",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.5",
    "@angular/compiler": "8.2.5",
    "@angular/core": "^8.2.5",
    "@angular/forms": "8.2.5",
    "@angular/http": "7.2.15",
    "@angular/material": "8.2.3",
    "@angular/platform-browser": "8.2.5",
    "@angular/platform-browser-dynamic": "8.2.5",
    "@angular/platform-server": "8.2.5",
    "@angular/router": "8.2.5",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.21",
    "@fortawesome/free-brands-svg-icons": "^5.10.1",
    "@fortawesome/free-solid-svg-icons": "^5.10.1",
    "@nguniversal/common": "^8.1.1",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
    "@ngx-loading-bar/core": "^4.2.0",
    "angularx-social-login": "^1.2.7",
    "compression": "^1.7.4",
    "core-js": "^2.4.1",
    "cors": "^2.8.5",
    "express": "^4.15.2",
    "focus-trap": "^5.0.2",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "ngx-device-detector": "^1.3.9",
    "reflect-metadata": "^0.1.10",
    "rxjs": "6.3.3",
    "rxjs-compat": "^6.5.3",
    "rxjs-tslint": "^0.1.7",
    "sessionstorage": "^0.1.0",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.1"
  },

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)

**Comment by BruneXX** [comment]
I'm afraid I cannot provide a StackBlitz for this one, the issue is at compilation time.. so meanwhile the app is in debug mode works fine, but fails during build. I think this will happen in an angular universal started project trying to use latest version of material I'll try to build a repo with those dependencies and share with you guys, but please take a look at this issue it seems a regression issue like in: 17209 for a month ago..

**Comment by jelbourn** [comment]
That would be great. Just based on the code, I don't see what the problem might be. Even in a server environment, the actual symbol should still be present.

**Comment by devversion** [comment]
Closing as this usually surfaces when the CDK version is not on par with the Angular Material version and we haven't gotten a lot of similar reports.
