### ISSUE TITLE
mat-tab-group destroying external angular web component(element) while switching out of the tab

### ISSUE THREAD

**Issue by naveed2304** [angular/components#17478]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

I am using `mat-tab-group` with three tabs where two tabs among them are containing normal Angular components while third tab is containing external Angular web component(element). Below is the code snippet for adding the components into `mat-tab-group`.

    <mat-tab-group>
      <mat-tab label="Tab-1">
        <some-angular-component></some-angular-component>
      </mat-tab>
      <mat-tab label="Tab-2">
        <some-other-angular-component></some-other-angular-component>
      </mat-tab>
      <mat-tab label="Tab-3">
        <external-angular-web-component></external-angular-web-component>
      </mat-tab>
    </mat-tab-group>
 
 
#### Expected Behavior

The tab containing the external web component should not get destroyed while switching the tab and should not get lazy loaded when opening the tab next time.

#### Actual Behavior

While switching from the tab containing the external web component, the component is getting destroyed and coming back to the tab re-initializes the external web component. This behavior is not experienced with normal Angular components.

#### Environment

- Angular: 7.2.0
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by tomicarsk6** [comment]
You posted wrong StackBlitz example.

**Comment by naveed2304** [comment]
> You posted wrong StackBlitz example.
