### ISSUE TITLE
cdkDragHandle directive dose not work correctly when ngZone is disabled

### ISSUE THREAD

**Issue by Ahmtk** [angular/components#17479]
#### Reproduction
When ngZone is disabled like this ( `detectChanges()` is called manually): `platformBrowserDynamic().bootstrapModule(MyModule, {ngZone: 'noop'})`,  `[cdkDragHandle] ` is ignored and the whole `[cdkDrag]` element becomes draggable. Please check this `stackblitz` example:

https://stackblitz.com/edit/components-issue-e3xur3

#### Expected Behavior
Only  `[cdkDragHandle]` element should be draggable.

#### Actual Behavior
The whole `[cdkDrag]` element is draggable.

#### Environment

- Angular: 8.2.2
- CDK: 8.2.3
- Browser(s): FireFox and Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
Currently Angular CDK (and Material) strictly require zone.js. We would like to make this optioning in the future, but don't currently have an ETA.
