### ISSUE TITLE
using a getter result for mat-select options causes an infinite loop

### ISSUE THREAD

**Issue by beagleknight** [angular/components#17493]
#### What are you trying to do?

When I use a getter in some component to provide the options for a `mat-select` in a child component it causes an infinite loop. The child component `ngOnChanges` is being called all the time.

#### What troubleshooting steps have you tried?

I didn't expect to create an infinite loop because if I use a simple `select` it works as expected.

#### Reproduction

https://stackblitz.com/edit/components-issue-civfkw?file=app%2Fchild.component.ts

Steps to reproduce:
1. Uncomment the block to use the `mat-select`.
2. The application became unresponsive 😞 
  
#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.0
- Browser(s): Google Chrome
- Operating System macOS

**Comment by crisbeto** [comment]
That's because the `options` getter returns a new array every time change detection is run so Angular thinks that the data has changed and it'll keep updating the view. You put the array into a regular property.

**Comment by beagleknight** [comment]
@crisbeto I understand the Angular behavior you mentioned but I don't get why `mat-select` and `select` behave differently. The problem here is the `mat-select` is triggering the change detection somehow while the `select` is not doing that. Do you have any idea why this could be happening?
