### ISSUE TITLE
disabled-sorting doesn't work after some iterations

### ISSUE THREAD

**Issue by LucaSoato** [angular/components#17504]
#### Reproduction

Steps to reproduce:
0. go to https://material.angular.io/cdk/drag-drop/overview#disabled-sorting
1. put carrot in target list
2. put apple in target list
3. put carrot back in source list
 
#### Expected Behavior

Preserving the dragged item's initial position in the source list, if the user decides to return the item

#### Actual Behavior

Carrot goes below tomato after being put back in source list 

#### Environment

- Opera browser on windows

**Comment by crisbeto** [comment]
The previous position is only preserved for the current drag sequence. Once the element is dropped into a new container it'll be reset next time you start dragging. From what I can tell this works as expected.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
