### ISSUE TITLE
(Ivy) Assertion error: failed to find directive with exportAs: matAutocomplete

### ISSUE THREAD

**Issue by sergey-morenets** [angular/components#17508]
#### Reproduction

We used Angular Material in our project and it compiles fine with Angular 9.0.0-next.13 (non-Ivy mode). But if we try to set Ivy mode in tsconfig.json:

  "angularCompilerOptions": {
    "enableIvy": true
  },

"ng build --prod" command failed.
We tried two Angular Material versions: 8.2.3 and 9.0.0-next.0 but error still reproduces.

#### Expected Behavior

Project compiled successfully.

#### Actual Behavior

ERROR in Error: Assertion error: failed to find directive with exportAs: matAutocomplete
    at project\node_modules\@angular\compiler\bundles\compiler.umd.js:28818:31

#### Environment

Angular CLI: 9.0.0-next.15
Node: 12.3.1
OS: win32 x64
Angular: 9.0.0-next.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.15
@angular-devkit/build-angular     0.900.0-next.15
@angular-devkit/build-optimizer   0.900.0-next.15
@angular-devkit/build-webpack     0.900.0-next.15
@angular-devkit/core              9.0.0-next.15
@angular-devkit/schematics        9.0.0-next.15
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-next.15
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-next.15
@schematics/angular               9.0.0-next.15
@schematics/update                0.900.0-next.15
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by crisbeto** [comment]
It's hard to tell what's going on based on the provided information. We have some examples of `matAutocomplete` that are working against Ivy. Can you post the code that's failing?

**Comment by mstawick** [comment]
I've seen those kinds of errors. In my case, they had nothing to do with the directive/pipe/etc. mentioned in the error message. They were caused by some other library that wasn't ivy-compatible. Importing it didn't raise any errors of its own, but it would mess up the module it was imported to. I solved it by creating blank project and adding 3rd party libraries/modules one by one, to see which one was causing the issue.

**Comment by joshcomley** [comment]
I get this intermittently with various Angular Material modules. It compiles fine the first time, but within four or five updates (if I'm using `--watch`) then it cops out with `failed to find directive with exportAs: [some-material-component]`. If it is an external package causing the issue I have no idea how to isolate it as the project is huge, with many dependencies and builds fine the first time anyway.

**Comment by sergey-morenets** [comment]
Not reproduced with @angular/cdk 9.0.0-rc.4
