### ISSUE TITLE
Angular Material: Audio player component

### ISSUE THREAD

**Issue by EdricChan03** [angular/components#17513]
#### Feature Description

There should be support for an Angular Material audio player component which would ideally be a wrapper over the native `<audio>` element in HTML.

The component should also expose outputs when the audio's playback state is toggled or when a new audio URL is set.

The component should ideally be easy for developers to set up the player.

There should also be support for playlists which most music applications implement.

(P.S. I was inspired by this library created by @vmudigal: https://github.com/vmudigal/ngx-audio-player. However, I would like to see this integrated into the main set of components available.)

#### Use Case

This feature would allow users to easily include this audio player in their app without having to create a custom player or use external 3rd-party components.

**Comment by jelbourn** [comment]
We don't currently have any plans to build any kind of audio/video components (aside from the recently released `youtube-player`)
