### ISSUE TITLE
[Tabs] Bottom border on md-tab-header is too dark

### ISSUE THREAD

**Issue by code-tree** [angular/components#1751]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Bottom border on md-tabs-header is a lighter color in dark theme.

![image](https://cloud.githubusercontent.com/assets/11289719/20038127/bd2662f8-a3f3-11e6-93d5-0ebd0b5ea3e6.png)

#### What is the current behavior?
Bottom border is too dark in dark theme.

![image](https://cloud.githubusercontent.com/assets/11289719/20038106/5804e746-a3f3-11e6-9386-062d5842b8d7.png)

#### What are the steps to reproduce?
n/a

#### What is the use-case or motivation for changing an existing behavior?
Follow Material spec

#### Which versions of Angular, Material, OS, browsers are affected?
2.0.0-alpha.9

#### Is there anything else we should know?
[Code is here](https://github.com/angular/material2/blob/a0d85d879320a1c005f89b779addf2d003ec9b08/src/lib/tabs/_tabs-theme.scss#L14)

Spec doesn't appear to mention this border, though it does appear in images.

**Comment by code-tree** [comment]
This should probably have an opacity, so that it works well with both plain backgrounds and primary/accent color backgrounds.

**Comment by johnqiuwan** [comment]
Hi @code-tree,

  Do you know how to remove the border-bottom css in   .md-tab-header ? 

Thank you

**Comment by code-tree** [comment]
Just put this in a global CSS file (not a component)

```css
.md-tab-header {
    border-bottom-style: none !important;
}
```

**Comment by itjayaprakash** [comment]
Hi Guys Try this code,
same problem facing me  i  fixed 

`md-tabs md-ink-bar {
    background: transparent;
}`

**Comment by andrewseguin** [comment]
Tabs no longer have a border bottom in the spec so this is more of a subjective call to provide any coloring of a bottom border. The MDC version will decide to just not show a bottom border at all
