### ISSUE TITLE
Clearer documentation on TrackBy with respect to index

### ISSUE THREAD

**Issue by ElGusanito** [angular/components#17525]
#### Documentation Feedback

I had an issue adding/ deleting rows to/from Angular material table because the behavior of index isn't clear at all from the documentation.  On first glance, using the let i= index construct seems to suggest that all the work is done for you when in fact you need to specify a trackBy function to keep index synchronised when adding/removing rows from the datasource.  

In my case, I'm using Angular templated forms so I have to create a unique name for each input on every row which I do using the index and I'm sure this can't be an uncommon scenario so it would be good if this was made a bit clearer somewhere.

**Affected documentation page:** [https://material.angular.io/components/table/api](url)

**Comment by andrewseguin** [comment]
It's not clear to me what you are suggesting. If you think the docs could be improved, we would definitely appreciate a pull requests with better wording.
