### ISSUE TITLE
New material theming support

### ISSUE THREAD

**Issue by arabbani** [angular/components#17546]
#### Feature Description

What is the roadmap on new material theming. 
[Google IO'19](https://www.google.com/url?sa=t&source=web&rct=j&url=%23&ved=2ahUKEwiHwNuU6MTlAhVWVH0KHW0KBCkQwqsBMAB6BAgIEAQ&usg=AOvVaw0VTJzWxrN8ZFOD4xbU2nov)

**Comment by jelbourn** [comment]
We have some work in progress that will expand our theming system with density levels, but nothing beyond that (e.g. shapes)

**Comment by arabbani** [comment]
Ok
