### ISSUE TITLE
Document naming convention for material files

### ISSUE THREAD

**Issue by JBorgia** [angular/components#17571]
I have tried searching through the issues here and on slack. I couldn't find details on this in the CODING_STANDARDS.md document.

The angular.io styleguide states:

> “Do follow a pattern that describes the symbol’s feature then its type. The recommended pattern is feature.type.ts.”

What is the reasoning behind leaving off the 'type' in the component file name for material components?

**Comment by jelbourn** [comment]
* It's more consistent with Google's internal file naming scheme (we sync the code into Google's source repository)
* Names like `button.component.ts`and `checkbox.component.ts` are beyond redundant for this repo in particular; the names of each thing stand on their own.

Feel free to send a PR to the coding standards to call this out explicitly.
