### ISSUE TITLE
Remove example code from JSDoc

### ISSUE THREAD

**Issue by Splaktar** [angular/components#17579]
#### Documentation Feedback

API docs with usage example code don't get formatted. We should avoid putting code snippets in these API docs.

Our Overview (sourced from `.md` file) and Examples is where example code should live.

**Affected documentation page:**
- [CdkNestedTreeNode](https://material.angular.io/cdk/tree/api#CdkNestedTreeNode)
- [New clipboard docs](https://next.material.angular.io/cdk/clipboard/api)

**Comment by ssupdoc** [comment]
Hey @Splaktar, I would like to contribute to this issue. I went through the contribution guidelines, spinned up a local dev environment, but I do not know how to proceed further as I am unable to locate the docs template or the code for it. Since this is my first time contributing to any project, I feel stupid asking such a seemingly stupid question, but I would really like to contribute to this one.

**Comment by ssupdoc** [comment]
I have added a PR for this issue: [#17622](
https://github.com/angular/components/pull/17622). I updated the comments in the documentation for APIs as I could not spin up a local env for the docs.

**Comment by Splaktar** [comment]
Sorry for the delay in responding. The docs can be run locally via a separate repo: https://github.com/angular/material.angular.io. Unfortunately, it's currently a tough process to test unmerged changes in the Components repo in the Docs repo.

**Comment by Splaktar** [comment]
But now that your changes are merged, you should be able to load up that repo, update the docs-content, and then verify that it looks good.

**Comment by ssupdoc** [comment]
Thanks @Splaktar . I tried starting the dev environment for [material.angular.io](https://github.com/angular/material.angular.io) and followed the dev setup steps. But I get an error:
`ERROR in Cannot resolve type entity i1.CdkPopoverEditExamplesModule to symbol`. Is there something that I am missing?

**Comment by Splaktar** [comment]
@ssupdoc that's due to some refactoring that we did recently in the components repo. I just merged in PR https://github.com/angular/material.angular.io/pull/673 to resolve this.

**Comment by ssupdoc** [comment]
@Splaktar That's cool. I pulled in the latest and the API documentation looks good now. Thanks for helping me out 👍
