### ISSUE TITLE
[Clipboard] Add support for Clipboard Web API

### ISSUE THREAD

**Issue by EdricChan03** [angular/components#17593]
#### Feature Description

Currently, the clipboard code from the CDK uses a `<textarea>` element and calls `document.execCommand('copy')` on the selected text in the `<textarea>`. However, this may be troublesome especially if there's a long amount of text to be copied.

What I'm suggesting is to use the [`Clipboard.writeText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText)  method from the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API).

Here's a description of the Clipboard API:

> The **Clipboard API** provides the ability to respond to clipboard commands (cut, copy, and paste) as well as to asynchronously read from and write to the system clipboard. Access to the contents of the clipboard is gated behind the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API); without user permission, reading or altering the clipboard contents is not permitted.
>
> This API is designed to supersede accessing the clipboard using [`document.execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). _- from [MDN docs for the Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)_

Currently, the Clipboard API is supported in the following browsers:

![Screenshot of supported browsers table from Clipboard API document on MDN](https://user-images.githubusercontent.com/20047125/68081369-f353cf80-fe47-11e9-8d5d-e29bbd04b7a4.jpg)

However, according to the [MDN docs for "Clipboard availability"](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#Clipboard_availability), it mentions that:

> The asynchronous clipboard API is a relatively recent addition, and the process of implementing it in browsers is not yet complete. Due to both potential security concerns and technical complexities, the process of integrating this API is happening gradually in most browsers.

#### Use Case

This would add another method of copying text instead of the current approach.

**Comment by crisbeto** [comment]
This might make it inconsistent between browsers, because from what I can tell, it also requires the user to grant permissions to the web page.

**Comment by jelbourn** [comment]
This is probably something we'd explore once the browser support story improves a bit more.

**Comment by crisbeto** [comment]
I'm closing this issue, because we can't make the switch in a backwards-compatible way. Our current API is synchronous and it returns a boolean indicating whether the action was successful, whereas the browser API is asynchronous.
