### ISSUE TITLE
google-map: add component for DOM elements for maps

### ISSUE THREAD

**Issue by Akxe** [angular/components#17603]
#### Feature Description

Implement [OverlayView](https://developers.google.com/maps/documentation/javascript/reference/overlay-view) and example [here](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/overlay-popup) the same way as the map and marker are.

#### Use Case

Sometimes one just needs a bit more control over the marker that should be shown on the map. This use case is quite more likely to be present when building a web app.

My use case is, that markers on the map have 4 boolean states, colour, and direction (0-360); 6 states in total. Generating image for each seems not the right path, thus I wanted to use SVG with variable inputs.

#### Possible API

```lang-html
<google-map>
  <app-map-marker 
    map-dom-marker
    [position]="position"
    [draw]="drawMethod"
  ></app-map-marker>
</google-map>
```
Component `app-map-marker` is user made, thus he can control the HTML & CSS of the element to display on map.

Directive `map-dom-marker` is from library and implements `onAdd` and `onRemove`. It also does implement default `draw` method, that measures the element, and makes element act similar to `google.maps.Marker`.

```lang-ts
type drawFnReturnType = {
  visible: false
} | {
  visible: true;
  x: number | string;
  y: number | string;
};
type drawFn = (
  projection: google.maps.MapCanvasProjection, 
  position: google.maps.LatLng,
) => drawFnReturnType;
```

It's `@Input`s are:
*  `@Input() draw: undefined | drawFn`, if the function is passed, it will be used instead of the default implementation.
* `@Input() position: google.maps.LatLng`
* possibly others...

**Comment by mbehrlich** [comment]
I think this is a good idea. I do think that onAdd and onRemove will likely need to be optional inputs as well to fully replicate the OverlayView API. I am focusing on standard components for now before I start working on ones that allow more custom behavior, but I've added OverlayView to the list of components that I want to replicate.

**Comment by Akxe** [comment]
Isn't `onAdd` and `onRemove` equivalent to  `ngInit` and `ngDestroy`? In case we use `@Directive` for OverlayView APIMarker implementation?

**Comment by mbehrlich** [comment]
According to the docs, they are run when setMap is called, which may not necessarily be at the same time as ngOnInit or ngOnDestroy. I'll have to look into this further to see if there is custom behavior we want to support with onAdd and onRemove.

**Comment by abductedMind** [comment]
What is the alternative outside generating custom images?

**Comment by abductedMind** [comment]
This issue is related but closed https://github.com/angular/components/pull/18815

I have reviewed my options and believe that this component doesn't help me in any way when it comes to creating a custom/new directive such as a marker that renders its content children instead of an icon.

If I am mistaken can someone point me to an option? Otherwise, in my case this Google Maps component gives me very little.

**Comment by Akxe** [comment]
@abductedMind Well... Both this issue and the PR are mine. Feel free to use the code in the PR as the solution, I do still use it to this date, though for performance reasons I moved away from google-maps package altogether.

**Comment by Akxe** [comment]
Also, closing this issue as it will **not** be resolved in favour: 

> I would want to keep the Angular version a pretty pure API facade of the underlying Google Maps API. Introducing extra features is a slope that leads to the two being inconsistent and harder to maintain as the Maps team makes API updates.
>
> If the Maps API has a feature that allows users to provide custom implementations of something, we should (eventually) support that same API.

_Originally posted by @jelbourn in https://github.com/angular/components/issues/18815#issuecomment-606270472_

**Comment by abductedMind** [comment]
@Akxe Thank you. After examining the Google Map Component code along with the similar AGM project, I couldn't help but think that the Google Map Component must be less-performant.

**Question**: you moved away from the Google Map Component, but still use the code in your PR - does this mean that you still use the code separate from the Google Map Component? (I haven't looked at your code yet)

**Comment by Akxe** [comment]
I made my own library. But many things work the same. I did create a "Virtual" ngFor, that does not create HTML elements for every map marker. And to save money, instead of destroying maps, when not used, I do recycle them. (Google does bill every new map and I use them on many different pages)
