### ISSUE TITLE
Checkbox shows focus when inner element has focus

### ISSUE THREAD

**Issue by jshoudy** [angular/components#17629]
#### Reproduction

https://stackblitz.com/edit/angular-rknbpc

Steps to reproduce:
1. Click before the checkbox.
2. Tab and see both the checkbox and the button showing focus.
 
#### Expected Behavior

The checkbox and the button are mutually exclusive in showing keyboard focus.

#### Actual Behavior

Whenever the inner button has focus so does the checkbox. This is always problematic but more noticeable when the checkbox is disabled since focus goes directly to the button.

**Comment by crisbeto** [comment]
There should be ways around this, but I'm not sure whether we should fix it since putting a button inside a checkbox isn't a supported case.

**Comment by jelbourn** [comment]
Yeah, this isn't something we will address; a checkbox label officially only supports phrasing content, not interactive elements.
