### ISSUE TITLE
Paginator issues with the data length

### ISSUE THREAD

**Issue by buster95** [angular/components#17628]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://stackblitz.com/angular/lrnjnmrrmlp?file=src%2Fapp%2Fpaginator-configurable-example.ts

Steps to reproduce:
1.  go to last page
2.  then change the data length
A blank page appears, since the length of the current data is not filling up to the current page, you must press the button on the previous page many times
 
 
#### Expected Behavior

What behavior were you expecting to see?
I want that the paginator current page change to 1 because if the data change you dont know if the current data length could be filling the current page

#### Actual Behavior

What behavior did you actually see?
current page is in empty

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 1902

**Comment by ccjmne** [comment]
I don't think this should be the Paginator's responsibility.

What if I build a UI that lets users remove an item from the collection in a single click? They wouldn't want to be brought back to the first page.

I think it's reasonable that it is up to you to call `paginator.firstPage()` when your data model is updated, if you desire so.

**Comment by andrewseguin** [comment]
We intentionally designed the `MatPaginator` to simply display what it is told, rather than automatically deciding what to do when the page is out of range of the length. Unfortunately there is no one-size-fits-all solution to automatically selecting a page in this case

**Comment by buster95** [comment]
> I don't think this should be the Paginator's responsibility.
> 
> What if I build a UI that lets users remove an item from the collection in a single click? They wouldn't want to be brought back to the first page.
> 
> I think it's reasonable that it is up to you to call `paginator.firstPage()` when your data model is updated, if you desire so.

I try to do that but not work, I don't know why
