### ISSUE TITLE
Media query hover:none triggered on desktop Chrome in Ubuntu Wayland session

### ISSUE THREAD

**Issue by martinbdz** [angular/components#17630]
#### Reproduction

1. Visit the example page for the material buttons:
https://material.angular.io/components/button/examples 

2. Hover over the basic or stroked buttons.
 
#### Expected Behavior

The background of the buttons should change.

#### Actual Behavior

The background does not change in Chrome but does so in Firefox. The problem is that the `@media (hover: none)` query is being triggered somehow. I tried a fresh Chrome without any extensions and saw the same behavior. After further testing it seems to only happen in the Ubuntu 19.10 Wayland session.

#### Environment

- Angular: 8.2.11
- CDK/Material: 8.2.3
- Browser(s): Chrome 78.0.3904.87, Firefox 70.0.1
- Operating System: Ubuntu 19.10 Wayland session
- No touch screen monitors attached

**Comment by crisbeto** [comment]
This sounds like more of a browser bug than something on our end. We can't do too much about how the browser interprets the media queries.

**Comment by martinbdz** [comment]
You are correct, somehow I was not able to find the chromium bug report yesterday. Here is the link: https://bugs.chromium.org/p/chromium/issues/detail?id=867912 .

So the workaround for now is to overwrite the necessary styles until a fix is released.
