### ISSUE TITLE
On Mobile, when opening a drawer, it removes the menu at the top. unable to get it back without refreshing

### ISSUE THREAD

**Issue by d3rpp** [angular/components#17634]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. I was using an iPhone 8 for testing
2. my Testing URL is tgs-testing.yeeeeet.ga
3. it loads fine at first but when the sidebar is opened, the top menu bar disappears
4. not 100% certain it is a problem with this however if it is then I have no idea how to fix it on my side
 
 
#### Expected Behavior

What behavior were you expecting to see?

- lack of disappearing menu bar

#### Actual Behavior

What behavior did you actually see?

- disappearing menu bar

#### Environment

- Angular: 8.2.3
- CDK/Material: Indigo-Pink Material
- Browser(s): Safari for iOS
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

this was, unfortunately, all of the info I could get on the issue

**Comment by MRMokwa** [comment]
I'm not able to reproduce, your StackBlitz doesn't seen to have a drawer component.

**Comment by D3RPSTROYER** [comment]
also, I was only able to see this effect in production. so i am unable to do it in a developer environment, sorry

**Comment by jelbourn** [comment]
Looks like the repro isn't up any more- going to close for now, feel free to open a new issue if there's some bug still occurring.
