### ISSUE TITLE
Sidebar: toggle via observable @Input()

### ISSUE THREAD

**Issue by alastair-todd** [angular/components#17639]
#### Feature Description

Add a `toggleTrigger: Observable<boolean>` `@Input` to the `Sidebar` component

#### Use Case

I use a state-based UI architecture, and I want to bind an observable boolean directly to the sidenav so that I don't have to manage the `open()` and `close()` methods myself.

`<mat-drawer toggleTrigger="burgerBarVisible$"></mat-drawer>`

**Comment by MRMokwa** [comment]
Try this:
`<mat-drawer [opened]="burgerBarVisible$ | async">`

**Comment by jelbourn** [comment]
Yep, the `async` pipe is the preferred approach for this.
