### ISSUE TITLE
Breaking changes in angular/components 9.0.0-next / no manual refactor for imports

### ISSUE THREAD

**Issue by karacas** [angular/components#17645]
#### Feature Description
Any way to avoid manual refactor for resolve a this breaking change: "Components can no longer be imported through "@angular/material". Use the individual secondary entry-points, such as @angular/material/button."

#### Use Case
Upgrade from angular 8 to angular 9

**Comment by crisbeto** [comment]
If you're using the Angular CLI we do have an `ng update` schematic that should migrate everything for you. What are you using to update?

**Comment by karacas** [comment]
@crisbeto tnxs!!

**Comment by crisbeto** [comment]
Can the issue be closed?

**Comment by karacas** [comment]
Shure, tnx again!
