### ISSUE TITLE
mat-select(multiple): Possibility to track how selection was changed, via checkbox or on label click. 

### ISSUE THREAD

**Issue by vyacheslavzhabitsky** [angular/components#17655]
#### Feature Description
So actually we can track selection target only via native (click) event on mat-option and then check the target, but would be good to have it in _MatSelectChange_ event. 

#### Use Case
e.g. I want to close mat-select when we click on label(not checkbox).
e.g. I want to change selection only when we click on checkbox.
e.g. I want to reset selection when target is label(not checkbox) and make selected only clicked option.

Now we forced to use event (click) instead of (selectionChange) that makes discrepancy in logic, would be good to use only selectionChange and be able to know it was a checkbox  selection or label click.
I understand perfectly that I can implement this without using the event provided by the Material, but as for me it’s not right

**Comment by mmalerba** [comment]
For accessibility purposes, the checkbox is just visual decoration. We can't treat it differently than clicking on label without breaking accessibility for the select.
