### ISSUE TITLE
[MatTooltip] tooltip doesn't disappear when button become disabled

### ISSUE THREAD

**Issue by Amit775** [angular/components#17654]
#### Reproduction

https://angular-iuvhg6.stackblitz.io

Steps to reproduce:
1. focus on the input
2. hover the mouse over the button until tooltip is shown
3. delete the input so the button become disabled
4. the tooltip will be shown until you focus again on the input
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expect that the tooltip will disappear when the button become disabled

#### Actual Behavior

What behavior did you actually see?
the tooltip still shown and doesn't disappear until I focus again to the input

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): chrome 78
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by lueenavarro** [comment]
I am also experiencing this issue, mattooltip does not show on disabled buttons in chrome. it works on FF though.

**Comment by jelbourn** [comment]
I think this is too niche/rare of a use-case to add extra code for. You can accomplish this in the app layer with `matTooltipDisabled`
