### ISSUE TITLE
CdkPortalOutlet attachComponentPortal not render portal to outlet when portal have viewContainerRef

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#17650]
actually, I m not 100% confirm this is a bug or is by design. because document not very clear for this part. 

#### Reproduction
https://github.com/keatkeat87/ng-mat-portal-outlet-issue
![portal outlet](https://user-images.githubusercontent.com/8691013/68453279-1a3b4880-0230-11ea-9be2-02364df64998.gif)

#### Expected Behavior
the portal should render in outlet not view container.

#### Actual Behavior
the portal render in view container.

more details: 
I check the source code, class CdkPortalOutlet
![image](https://user-images.githubusercontent.com/8691013/68448022-16ea9180-021d-11ea-93cc-e051d4ff4f37.png)
as the comment said that 
    // If the portal specifies an origin, use that as the logical location of the component
    // in the application tree. Otherwise use the location of this PortalOutlet.
if i not wrong, logical location is not equal to render location, so in this part, should have some code to move the element to outlet location.
i think it should work same as DomPortalOutlet
![image](https://user-images.githubusercontent.com/8691013/68448155-882a4480-021d-11ea-8bef-39d14bb01296.png)
in the end, move element to outlet.
another interesting thing is in class CdkPortalOutlet 
when we attach a templatePortal, it just ignore the templatePortal viewContainerRef. 
![image](https://user-images.githubusercontent.com/8691013/68448227-c1fb4b00-021d-11ea-9edb-7ec32f55f6a7.png)
it work not same as attach a component portal. it really make user confusing.
 

#### Environment

- Angular: 9.0.0 rc1
- CDK/Material: 9.0.0 rc 0
- Browser(s): chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by crisbeto** [comment]
You're correct, this is defininitely a bug. We probably hadn't noticed it until now because we either don't pass in a different `ViewContainerRef` or we use the `DomPortalOutlet` which doesn't have this issue. Should be fixed in #17731.
