### ISSUE TITLE
How can I prevent a mat-expansion-panel from opening when clicked?

### ISSUE THREAD

**Issue by TheParad0X** [angular/components#17651]
I want to control my **mat-expansion-panel solely with the panel's [expanded] input property**. I am using NGRX as state management.

Therefore, **I don't want the panel to open when clicked**. Instead, I have my own click listener that will dispatch the right action that will lead to the panel to open.

How can I prevent it from opening when clicked? I tried (click)="$event.stopImmediatePropagation(); but it does not do the trick.

```
<mat-accordion [multi]="true">
  <mat-expansion-panel [expanded]="item.isOpen">
    <mat-expansion-panel-header (click)="togglePanel($event, item)">
        <!-- Header Content-->
    </mat-expansion-panel-header>

    <ng-template matExpansionPanelContent>
        <!-- Panel Content -->
    </ng-template>
  </mat-expansion-panel>
</mat-accordion>
```

Any ideas?

**Comment by crisbeto** [comment]
You can bind to the `disabled` property on the `mat-expansion-panel`.

**Comment by manklu** [comment]
@crisbeto That would change the appearance, make it unusable with keyboard and propagate wrong information to screen readers. It should just not open automatically :wink:

Ideally there would be a boolean input to disable automatic opening and an event so the developer doesn't need to write the listener itself.

Btw this may be useful for other components too. e.g. Tabs, Tree etc.

**Comment by crisbeto** [comment]
Isn't this the point though? Otherwise the user would click it without any feedback on why nothing is happening.

**Comment by qirex** [comment]
using css to disable pointer events works:  
```
.disabled-pointer {
  pointer-events: none;
}
```

See https://stackblitz.com/edit/angular-wykguu for exmaple

**Comment by manklu** [comment]
@crisbeto The event handler will dispatch an action and as result of the action processing and state change the panel will open.

In the easiest case the action will just open the panel. But it's also possible to open the panel only after you have successfully loaded data from external sources, or display an error if that fails.

The possibilities of what is done before opening the panel are almost unlimited.

**Comment by devversion** [comment]
I think this looks like a good feature request, but I'm not sure if that complies with the Material Design specification the expansion panel is based on. Also it's unclear how this plays together with accessibility.
