### ISSUE TITLE
google-maps: perf: defer event listener subscription

### ISSUE THREAD

**Issue by Akxe** [angular/components#17663]
#### Feature Description

Currently every google-maps component will add all of its possible event listeners just in case. It might boost performance not to do so until anything listens to this. I a not sure if it is possible with event emitters. 

#### Use Case

Possible performance benefits while using maps components.

**Comment by crisbeto** [comment]
This should be the case already. See https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.ts#L463.

**Comment by Akxe** [comment]
I missed that line on first read through. But won't it break if event listener is added afterwards? I think having native observable with `@Output` annotation with `replayBuffer`, (with ref count) might be better suited no?

**Comment by crisbeto** [comment]
It would break if the subscription is added after init, but I think the assumption that was made there was that users would subscribe through Angular event bindings.

**Comment by Akxe** [comment]
Indeed it seems reasonable, though it should be mentioned in comment then, no?

But maybe someone on Google team knows hot to create cold/warm `EventEmmiter`, anyone? (Pleas tag someone if you know someone who might know)

**Comment by crisbeto** [comment]
Handled by https://github.com/angular/components/pull/17845.
