### ISSUE TITLE
docs(select): overlayDir should be a private API

### ISSUE THREAD

**Issue by Maxstgt** [angular/components#17678]
### Bug, enhancement request, or proposal:
I guess, there is a typo on the angular material docs.
![Screenshot from 2019-11-12 11-34-37](https://user-images.githubusercontent.com/39312833/68685406-622cd900-056a-11ea-8fb2-d219c90360e4.png)
Shouldn't it be panel?

### Detailed Reproduction Steps:
Visit https://material.angular.io/components/select/api#MatSelect
### What is the use-case or motivation for changing an existing behavior?
To make the world typo-free ;)

**Comment by Splaktar** [comment]
I just spoke to the team and this API should not be in the docs since it is intended to be a private API.

**Comment by Maxstgt** [comment]
Nice, glad to help
