### ISSUE TITLE
Safari Autofill doesn't work on Material inputs

### ISSUE THREAD

**Issue by beyondsanity** [angular/components#17677]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-2kubcp

Steps to reproduce:
When the input fields are wrapped inside mat-form-field the autofill UI isn't shown.
When the input fields are moved out the mat-form-field or the matInput directive is removed autofill works.

 
#### Expected Behavior

Safari users should be able to see the key icon or at least the autofill suggestion.

#### Actual Behavior

Safari doesn't show the usual key icon and autofill suggestion.
Pressing the cmd+shift+A shortcut triggers autofill correctly.

#### Environment

- Angular: 8.2.13
- CDK/Material: 8.2.3
- Browser(s): Safari 13.1
- Operating System:  MacOS

**Comment by devversion** [comment]
Hello! I just tried this with Safari 13.1 macOS Catalina and I got the key icon and autofill suggestions as expected. Can you please help with reproducing this? It seems like this has been fixed.

**Comment by beyondsanity** [comment]
Hello @devversion,

I've tried again my Stackblitz after months and it seems to be working correctly now.

Thanks,
