### ISSUE TITLE
CDK drag and drop is broken on second run

### ISSUE THREAD

**Issue by MrBra1nwash** [angular/components#17670]
Steps to reproduce:
1. Create a simple angular app with two pages: one with drag and drop, second without it
Example of the page with drag and drop:

```
<div cdkDropList (cdkDropListDropped)="dropped($event)">
    <div *ngFor="let item of items$ | async" cdkDrag>{{item.title}}</div>
</div>
```

2. Navigate to next page in the application without drag and drop and then go back in the browser to the page with DND
 
 
#### Expected Behavior

Drag and drop is working

#### Actual Behavior

Drag and drop is not working at all. Like it doesn't exist

#### Environment

- Angular: 8.2
- CDK/Material: 8.2
- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I'm unable to reproduce this issue based on the provided information. Can you put together a Stackblitz or a repo that shows it?

**Comment by MrBra1nwash** [comment]
Sorry for the unclear explanations. For now, I found source of the issue, but it still very strange for me. I am using `nrwl` library and i have `react` app inside my `angular` app. So when I have even one redux selector into `react` app, after visiting the page with this react app and going back - drag and drop stop working. If I comment selectors - it works. It seems it is not a bug of the `CDK DragAndDrop`, but it is still very strange...
