### ISSUE TITLE
cdkTextareaAutosize duplicating input on firefox mobile 

### ISSUE THREAD

**Issue by emko** [angular/components#17688]
#### Reproduction
```
   <mat-form-field>
    <textarea matInput cdkTextareaAutosize placeholder="description"></textarea>
  </mat-form-field>
```
 
#### Expected Behavior

User input should not duplicate

#### Actual Behavior

each key press repeats all previous keys with it so if you start with K and then press J you will get KKJ and so on, this result is on Firefox android, tested chrome on android works fine same with Firefox/Chrome on windows 10 desktop.

#### Environment

- Angular: 8.3
- CDK/Material: @angular/cdk": "^8.2.3 
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by jelbourn** [comment]
I just tried this on FF Mobile on my Pixel 3 and didn't encounter any issues. Is there any further information you can provide? It might have been fixed in Firefox since this issue was opened.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
