### ISSUE TITLE
Migrating to v9 => automatically migrate deprecated APIs via schematics

### ISSUE THREAD

**Issue by juristr** [angular/components#17683]
#### Reproduction

Steps to reproduce:
1. Create a v8 project where the `import { SelectionModel } from '@angular/cdk/collections';` is being used
2. Use the `SelectionModel`'s deprecated `onChanged` API
3. Upgrade to the latest v9 RC release via `ng update @angular/material@next`
 
#### Expected Behavior

As quickly discussed with @jelbourn and @StephenFluin I'd expect the upgrade to happen automatically, meaning the `onChanged` should  be automatically migrated to the new `changed` API.

#### Actual Behavior

The code is not migrated.

#### Environment

- Angular: v8
- CDK/Material: v8
- Operating System (e.g. Windows, macOS, Ubuntu): macos

**Comment by devversion** [comment]
We actually have an migration for this, but it looks like our ng-update target version did not include `next` or `rc` releases. Here is a fix: https://github.com/angular/components/pull/17704.

**Comment by Splaktar** [comment]
PR https://github.com/angular/components/pull/17704 has been merged, but it's not yet released. `rc.2` should include this fix and should be released soon.
