### ISSUE TITLE
when install 9rc1 error

### ISSUE THREAD

**Issue by wohugb** [angular/components#17690]
#### Reproduction

nmp i 
 
 
#### Expected Behavior

ERROR in node_modules/@angular/material/core/common-behaviors/common-module.d.ts:8:10 - error TS2305: Module '"../../../cdk/a11y"' has no exported member 'HighContrastModeDetector'.

#### Environment

- Angular: 9rc.1
- CDK/Material: 9rc1
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  ubuntu

**Comment by wohugb** [comment]
when use ivy throw this error

ERROR in node_modules/@angular/material/bottom-sheet/bottom-sheet-container.d.ts:10:78 - error TS2305: Module '"../../cdk/portal"' has no exported member 'DomPortal'.

**Comment by devversion** [comment]
This is usually a sign of a mismatched CDK and Material version. By looking at:

https://unpkg.com/browse/@angular/cdk@9.0.0-rc.1/a11y/public-api.d.ts and
https://unpkg.com/@angular/material@9.0.0-rc.1/core/common-behaviors/common-module.d.ts everything seems fine. 

I'll try to reproduce this, but it would be nice if a reproduction is shared as part of the issue. I've seen a similar report some time ago, but wasn't able to reproduce it.

**Comment by devversion** [comment]
@wohugb What's the best way to reproduce your issue? The text you put into the `Reproduction` seems not helpful.

**Comment by wohugb** [comment]
I am sorry. I only updated material, not update cdk, now ok,thank you!
