### ISSUE TITLE
divider: disappears in Chrome at some zoom-adjustments

### ISSUE THREAD

**Issue by samerhijazi** [angular/components#17705]
#### Reproduction

Steps to reproduce:
1. Start current version of Chrome (77)
2. Open the website: https://material.angular.io/components/divider/overview
3. Look at the lines 
4. Some of the lines should disappear, when you change zoom
 
 
#### Expected Behavior

What behavior were you expecting to see?
Mat-Divider should be seen all the time.

#### Actual Behavior

What behavior did you actually see?
Mat-Divider disappears at some zoom-sizes (e.g. 75%)

#### Environment

- Angular:
- CDK/Material: https://material.angular.io/components/divider/overview
- Browser(s): Chrome 77
- Operating System: Windows 10

**Comment by Splaktar** [comment]
There is a [similar but different Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=793785) for input borders disappearing when zooming.

**Comment by jelbourn** [comment]
I'm going to attribute this to a Chrome bug; I don't think there's anything Angular Material can do here.
