### ISSUE TITLE
icon: settings_application is rendered with a 208px width when inline="true"

### ISSUE THREAD

**Issue by ranetpgit** [angular/components#17701]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Expecting "settings_application" mat-icon  to render properly

#### What is the current behavior?
"settings_application" mat-icon renders 208 pixels wide

#### What are the steps to reproduce?
Stackblitz link here:
https://stackblitz.com/edit/angular-g1fvvq?file=src/app/icon-svg-example.html
A screenshot just in case: 
![image](https://user-images.githubusercontent.com/16505733/68844088-e2ba1980-06d1-11ea-9b0f-7a59f1241839.png)

#### What is the use-case or motivation for changing an existing behavior?
So that icon could be used properly

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on the latest (2019 Nov. 14) Firefox, Chrome. 
Angular version 8.2.3

#### Is there anything else we should know?
The "settings" icon is basically a functional version of the "settings_application" icon. Although the current icon for "settings_application" is missing the box around the cogwheel, that the Material Design icons specify (https://material.io/resources/icons/?search=settings&icon=settings_applications&style=baseline)

**Comment by Splaktar** [comment]
Here's an update to the demo:
https://stackblitz.com/edit/angular-mat-icon-settings-17701?file=src/app/icon-svg-example.html

As you linked at the end of your post, the icon is called `settings_applications` and not `settings_application`. Changing to the correct name fixes it.

Additionally, there is an unlisted `settings` icon as well that behaves properly.
