### ISSUE TITLE
mat-tab-nav-bar should support label alignment

### ISSUE THREAD

**Issue by lbar** [angular/components#17719]
#### Feature Description

Classic `mat-tab-group` support label alignment of tabs, as documented here : https://material.angular.io/components/tabs/overview#label-alignment.
It should be nice to have this feature for `mat-tab-nav-bar`.

#### Use Case

Same as the use case for label alignment in `mat-tab-group`.

**Comment by crisbeto** [comment]
Sounds like it should be solved by https://github.com/angular/components/pull/14193.

**Comment by crisbeto** [comment]
Closing since this seems to be supported in master.
