### ISSUE TITLE
MatTableDataSource can't filter array of strings properly

### ISSUE THREAD

**Issue by yassine-klilich** [angular/components#17711]
Can not filter array of string properly.
I made a simple demo to show you the issue https://stackblitz.com/edit/angular-hayef3?file=src%2Fapp%2Ftable-filtering-example.html
So what happenned exactly, when I tried to filter the table by typing "item" I got nothing from the table.

**Comment by ffirsching** [comment]
Have a look at the default filterPredicate in the [dataSource ](https://github.com/angular/components/blob/master/src/material/table/table-data-source.ts). It clearly assumes the individual element to be of type Object.


`
const testString = "test 1234"

// function from default filterPredicate
const dataStr = Object.keys(testString).reduce((currentTerm: string, key: string) => {   
      return currentTerm + (testString as {[key: string]: any})[key] + '◬';
    }, '').toLowerCase();

console.log(testString)
// "t◬e◬s◬t◬ ◬1◬2◬3◬4◬"
`

So the string is taken apart into chars, and thats why you don't find anything.
