### ISSUE TITLE
i can't add the style of mat-icon in my datatable angular material !!! i import in my appmodule import * as Mat from '@angular/material'; and i add this in my imports[MatIconModule], how i can fix this plz

### ISSUE THREAD

**Issue by dridimedamine** [angular/components#17726]
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppRoutingModule } from './app-routing.module';
import { SharedModule } from './shared/shared.module';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { ColorPickerModule } from 'ngx-color-picker';
// @ts-ignore
import { IndexComponent } from './vente/journee/journeedetail/index/index.component';
import { IgxGridModule } from 'igniteui-angular';

import { PerfectScrollbarModule, PERFECT_SCROLLBAR_CONFIG, PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';

import { AppComponent } from './app.component';
import { ContentLayoutComponent } from './layouts/content/content-layout.component';
import { FullLayoutComponent } from './layouts/full/full-layout.component';

import { AuthService } from './shared/auth/auth.service';
import { AuthGuard } from './shared/auth/auth-guard.service';
import { CustomRender } from './parametre/parametre-genereaux/bareme/CustomRender';
import { CustomerEquipe } from './parametre/parametre-equipe/CustomerEquipe';
import { CustomPompe } from './parametre/parametre-pompe/CustomPompe';
import { CustomerCiterne } from './parametre/parametre-citerne/CustomerCiterne';
import { VenteComponent } from './vente/vente.component';
import { GridGroupbyStylingComponent } from './grid-groupby-styling/grid-groupby-styling.component';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {CustomRenderTypeCarburant} from './parametre/parametre-genereaux/type-carburant/CustomRender-TypeCarburant';
import {CustomRenderTypeCarburantCouleur} from './parametre/parametre-genereaux/type-carburant/CutomRender-TypeCarburantCouleur';
import {CustomRenderPistoletTypeCarburant} from './parametre/parametre-pompe/fiche-pompe/CustomRenderPistoletTypeCarburant';
import {CustomRenderEquipePeriodeLibelle} from './parametre/parametre-genereaux/equipe-periode/CustomRenderEquipePeriodeLibelle';
import { ToastrModule } from 'ngx-toastr';
import {MatTableModule} from '@angular/material/table';
import * as Mat from '@angular/material';
import {MatIconModule} from '@angular/material/icon';

//import { RootComponent } from './root/root.component';

const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true,
  wheelPropagation: false
};

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({

  declarations: [AppComponent, FullLayoutComponent, ContentLayoutComponent, CustomRender, CustomerEquipe,
    CustomPompe, CustomerCiterne, VenteComponent , GridGroupbyStylingComponent, CustomRenderTypeCarburant, CustomRenderTypeCarburantCouleur, CustomRenderPistoletTypeCarburant, CustomRenderEquipePeriodeLibelle],
  imports: [
    BrowserAnimationsModule,
    AppRoutingModule,
    SharedModule,
    HttpClientModule,
    NgbModule.forRoot(),
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]
      },
    }),
    PerfectScrollbarModule,
    IgxGridModule,
    FormsModule,
    ColorPickerModule,
    ToastrModule.forRoot({
      timeOut: 5000,
      positionClass: 'toast-top-right',
      preventDuplicates: true,
    }),
    ReactiveFormsModule,
    Mat.MatToolbarModule,
    Mat.MatButtonModule,
    Mat.MatGridListModule,
    Mat.MatInputModule,
    Mat.MatFormFieldModule,
    Mat.MatRadioModule,
    Mat.MatSelectModule,
    Mat.MatDatepickerModule,
    Mat.MatNativeDateModule,
    Mat.MatCheckboxModule,
    Mat.MatSnackBarModule,
    Mat.MatTableModule,
    Mat.MatIconModule,
    Mat.MatPaginatorModule,
    Mat.MatSortModule,
    Mat.MatDialogModule,
    MatIconModule,

     ],
  exports: [] ,
  entryComponents: [CustomRender, CustomerEquipe, CustomPompe, CustomerCiterne , CustomRenderTypeCarburant, CustomRenderTypeCarburantCouleur, CustomRenderPistoletTypeCarburant, CustomRenderEquipePeriodeLibelle ],
  providers: [
    AuthService,
    AuthGuard,
    {
      provide: PERFECT_SCROLLBAR_CONFIG,
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
    },
    { provide: PERFECT_SCROLLBAR_CONFIG, useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}

**Comment by crisbeto** [comment]
You can't import from `@angular/material` anymore. You should use the individual entrypoints. E.g. `import {MatDialogModule} from '@angular/material/dialog'`.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
