### ISSUE TITLE
virtual-scroll Chrome makes images jump

### ISSUE THREAD

**Issue by lenpino** [angular/components#17728]
I have a list of products and everything works fine on Safari and to some extend on Firefox. The list displays fine including some in line adds.

https://tuganga-test-html.s3-us-west-2.amazonaws.com
 (use mobile tools.. on screen bigger than 768px there is no virtual-scroll implementation)

The problem is with Chrome. Every product has a reference to an image:
<img style="max-height:210px;" [src]="producto?.url_img" [alt]="producto?.descripcion_corta">
It looks like Chrome has problems calculating the height of the image before hand. Feels like it waits for the product to be inside de scroll window to create the <li> with the image. It is not fast enough and it gives the wrong image or jumps to a previous product.
The problem can be mitigated making the scroll window's size, equals to the number of products * the hight of the product

If I remove the image, scrolls woks fine.

I have been working on a work around for a month. Please help

#### Environment

- Angular: 8.2.13
- CDK/Material: 7.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Looks like this link is broken now; feel free to open a new issue with a reproduction if there's still some issue occurring.
