### ISSUE TITLE
autocomplete overview link not working

### ISSUE THREAD

**Issue by ChuckIrvine** [angular/components#17734]
#### Reproduction

Navigate to https://material.angular.io/components/autocomplete/overview 
 
#### Expected Behavior

Expect to get the overview page.

#### Actual Behavior

Get:

Failed to load document: /docs-content/overviews/material/autocomplete.html. Error: OK

**Comment by crisbeto** [comment]
The URL works for me, maybe you're hitting some kind of caching issue? Does the same thing happen if you try it in a different browser?

**Comment by ChuckIrvine** [comment]
Right you are. The error was happening with Safari. I cleared history, and then the page displayed as expected. I also tried Chrome and no problems there. Thanks for taking a look!
