### ISSUE TITLE
Datepicker with  custom formats not working when typing in the date.

### ISSUE THREAD

**Issue by Strimi224** [angular/components#17748]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/dkbeaogoegv?file=src%2Fapp%2Fdatepicker-formats-example.ts

Steps to reproduce:
1. Use the code provided in the date picker example: https://material.angular.io/components/datepicker/examples
2. Type in a date in a format like: 11.12.2001
 
 
#### Expected Behavior

The date picker should format the string like: November 12, 2001

#### Actual Behavior

The date picker formatted the string like: January 11, 2012

#### Aditional Information

The first value is always the day and the second always the year and the third parameter is ignored.

#### Environment

- Angular: 8.1.19
- CDK/Material: 8.2.3
- Material Moment Adapter: 8.2.3
- Browser(s): Chrome
- Operating System (Windows):

**Comment by mackelito** [comment]
Your StackBlitz link does not work..
Have you provided your format using something like `{ provide: MAT_DATE_FORMATS, useValue: CUSTOM_DATE_FORMATS }` ?

**Comment by Strimi224** [comment]
I updated the StackBlitz link ist should work now.
And I provided everything like you said.

**Comment by ccjmne** [comment]
With the default `DateAdapter`s that are provided, you are supposed to use the same format for manual Date entry as the one used to format Dates.

---

Basically, if the 22nd of November 2019 is displayed: `November 22, 2019`, then the format the Datepicker uses to try and parse your textual entry is: `"MMM DD, YYYY"`.

With the setup that you have in your current StackBlitz, you shouldn't be typing in `11.12.2001`, but rather `November 12, 2001`.

---

I reckon you should be able to implement your own `DateAdapter`, however, which lets you have finer control over these configurations:

```typescript
@Injectable()
export class CustomDateAdapter extends MomentDateAdapter {

  private static readonly PARSE_FORMAT: string = 'MM.DD.YYYY';
  private static readonly DISPLAY_FORMAT: string = 'MMM DD, YYYY';

  constructor() {
    super('en');
  }

  public format(date: Moment, _displayFormat: string): string {
    return date.format(CustomDateAdapter.DISPLAY_FORMAT);
  }

  public parse(value: any, _parseFormat: string | string[]): Moment | null {
    return moment(value, CustomDateAdapter.PARSE_FORMAT, 'en', false);
  }
}
```

Import it as such, in your Application's `module`:

```typescript
providers: [
    // ...,
    { provide: DateAdapter, useClass: CustomDateAdapter }
],
```

Please note that I haven't tested this, and maybe there are smarter ways to provide the formats you wish to use (it seems they are being provided to `DateAdapter#parse` and `DateAdapter#format`...

**Comment by ccjmne** [comment]
Well, turns out there were smarter ways, and a quick googling led me to [this answer on StackOverflow](https://stackoverflow.com/questions/51195601/custom-native-date-adapter-no-longer-works-since-upgrade-of-angular-material-fro).

Excerpt: 

```typescript
export const ISO_FORMAT = {
    parse: {
        dateInput: 'LL',
    },
    display: {
        dateInput: 'YYYY-MM-DD',
        monthYearLabel: 'MMM YYYY',
        dateA11yLabel: 'LL',
        monthYearA11yLabel: 'MMMM YYYY',
    },
};
```

```typescript
providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
    { provide: MAT_DATE_FORMATS, useValue: ISO_FORMAT },
    ...
]
```
