### ISSUE TITLE
Mat-chip-list with required option always shows error

### ISSUE THREAD

**Issue by hodossy** [angular/components#17742]
#### Reproduction

Use the chip list input example, add a formcontrol and a required input. (based on the [chip-list.spec.ts](https://github.com/angular/components/blob/master/src/material/chips/chip-list.spec.ts#L1453))

Steps to reproduce:
1. Prerequisite: Chip list with a form control and it is marked required. See this [Stackblitz](https://stackblitz.com/edit/angular-cfbb3w)
2. Focus on field
3. Focus out
4. Field is marked required in an error state
5. Add a new chip
6. Field is still marked required in an error state
 
 
#### Expected Behavior

Field marked as Valid whenever there is a chip. Marked as Invalid and the error is shown when there are no chips in the list.

#### Actual Behavior

Once the field has lost focus, the error state is always shown, independently of the number of chips present.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome 78
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by hodossy** [comment]
Any comments? I cannot make my form validation without a patch or workaround for this.

**Comment by hodossy** [comment]
@jelbourn,
Could you please take a look at this? Thanks!

**Comment by devversion** [comment]
@hodossy Thanks for this issue. I think you might be a bit confused here. The chip list's control value represents "selected" chips and not chips in the list. Related: https://github.com/angular/components/issues/8801
