### ISSUE TITLE
9.0.0-rc.2: Dark theme issues

### ISSUE THREAD

**Issue by realharry** [angular/components#17746]
#### Reproduction

* Cannot reproduce on StackBlitz due to error. Sample code: https://components-issue-3aehwp.stackblitz.io

Steps to reproduce:
1. Create mat-tab-group/mat-tabs with labels, either via the 'label' attribute or using `<ng-template mat-tab-label>`
2. Apply a dark theme, e.g., `pink-bluegrey` or `purple-green`

 
#### Expected Behavior

The label (light color) should be displayed on the dark background.

#### Actual Behavior

The background is light (presumably white), and hence the label is not visible.

#### Environment

- Angular: 9.0.0-rc.2
- CDK/Material: 9.0.0-rc.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 18.04

![mat-tab-background-issue](https://user-images.githubusercontent.com/28793852/69107678-673ccd00-0a2f-11ea-9df7-cd633bd94cc2.png)

**Comment by realharry** [comment]
Not sure if it's related. But, found a similar issue (resolved 2 years ago): https://github.com/angular/components/issues/4320

**Comment by realharry** [comment]
StackBlitz editor URL: https://stackblitz.com/edit/components-issue-3aehwp

**Comment by realharry** [comment]
I just ran into the same problems with `<mat-list>`, `<mat-divider>`, and `<mat-form-field>`. It's very likely that this issue affects many components (but, not all, for some reason).

**Comment by crisbeto** [comment]
Your example works correctly for me. The tabs are written in a way that assumes that they'll be on top of the proper theme background so as long as they're inside an element with `mat-app-background` they'll work as intended.

**Comment by realharry** [comment]
Ah, my bad. I somehow forgot about `mat-app-background`. Adding this class to the `<body>` fixed the issue. I'll close the ticket. Thanks.
