### ISSUE TITLE
Drag and Drop: If view port changes to have a smaller width, element could be off screen

### ISSUE THREAD

**Issue by 128keaton** [angular/components#17759]
#### Reproduction

https://stackblitz.com/angular/mjmpdxjmmee?file=src%2Fapp%2Fcdk-drag-drop-overview-example.ts

![Example](https://user-images.githubusercontent.com/1402918/69269458-acc7da00-0b96-11ea-9d23-8328bb54f495.gif)
Above is an example from a project I am working on.

Steps to reproduce:
1.  Drag an element to the far right side of the screen.
2.  Resize view port
 
 
#### Expected Behavior

The parent container scales and the draggable elements squeeze to fit.

#### Actual Behavior

The draggable element is off screen and can only be accessible through scrolling. Scrolling is fine on a desktop, but for mobile sized screens, it is just too clunky.

#### Environment

- Angular: 9.0.0-rc.2
- CDK/Material: 9.0.0-rc.2
- Browser(s): Chrome, Safari.
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by crisbeto** [comment]
We do this already if you're using a drag boundary, but I don't think we'd want to do this for all cases because it can end up overriding user data.

**Comment by 128keaton** [comment]
@crisbeto My bad, I just realized I set the container to hide overflow. For the record, you cannot do that for the auto-scrolling to function properly.
