### ISSUE TITLE
cdkDragBoundary is resetting positions of draggable elements when boundary is invisible

### ISSUE THREAD

**Issue by aalbericio** [angular/components#17750]
#### Reproduction

Use StackBlitz to reproduce your issue: https://angular-p8rakh.stackblitz.io

Steps to reproduce:
1.  There are two tabs. Select "**tab-2**". Move around the red proxy/div and set it somewhere different than 0, 0.

2. Move to "**tab-1**". This is a blank-tab but it's enough to reproduce the bug. Now, resize your chrome window (1 pixel is enough).

3. Move back to "**tab-2**" and ... boom! the red proxy/div **has been reset to position 0, 0**!

This actually makes cdkDragBoundary unusable for us since we have a very flexible and rich layout system.

 
 
#### Expected Behavior

What behavior were you expecting to see?

I was expecting the cdkDrag + cdkDragBoundary to exactly work as if "**tab-2**" was always visible: **maintaining the red proxy at its dragged position** (translate3d) **or modify it depending on the available container size**.

#### Actual Behavior

What behavior did you actually see?

As stated before, the dragged red proxy gets its position reset after a chrome window resize if boundary container is "invisible". 

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): 78.0.3904.97
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Enterprise 1809

**Comment by crisbeto** [comment]
Definitely a bug, but I think that the thing that triggers is the window being resized since that's the time when the draggable elements inside of boundaries get repositioned.

**Comment by aalbericio** [comment]
It is the window resize event that fires the issue.

If you switch off "**cdkDragBoundary**", everything works as expected (no repositioning) but, of course, without boundaries.

It's definitely a bug when combining"**cdkDragBoundary**" with **cdkDrag**.
