### ISSUE TITLE
Blank Screen On virtual scroll with mat tab group

### ISSUE THREAD

**Issue by J1445** [angular/components#17767]
#### What are you trying to do?
I am Trying to implement Mat tab group with Virtual Scroll  
cdk scroll content gets empty when I  scroll upto partial level and change group 

What are you seeing that does not match your expectations? 
Empty data is being shown when tab is changed either it should reset scroll position to zero and show the list or scroll the list where user left scrolling partially

The data is shown again when user scrolls manually
![ezgif-6-e948c87032d2](https://user-images.githubusercontent.com/57798061/69305982-05a57a00-0c4c-11ea-91fe-85852b473421.gif)

We can only help if we can reproduce the problem ourselves. 

https://stackblitz.com/edit/angular7-virtual-scroll-issue-tf6mdz?file=package.json

Steps to reproduce:
1. Scroll City Virtual scroll to a limit and change tab to country tab
2. upon selecting city again  empty tab  list is shown unless user manually scrolls
  
#### Environment
Have tested the both Angular 7 and Angular 8  cdk material core 
- Angular: 7/8 
- CDK/Material: 7/8
- Browser(s): Chrome / Firefox
- Operating System  : Ubuntu

**Comment by J1445** [comment]
@crisbeto  by any means, Can you look into this issue?

**Comment by CoolCross** [comment]
https://material.angular.io/components/tabs/overview#lazy-loading
<img width="267" alt="20191129222150" src="https://user-images.githubusercontent.com/24381562/69874767-c08de180-12f6-11ea-924d-ad74ae18609c.png">

**Comment by dima11221122** [comment]
The same bug with ng zorro tabs https://github.com/angular/components/issues/17975

**Comment by J1445** [comment]
> https://material.angular.io/components/tabs/overview#lazy-loading
> <img alt="20191129222150" width="267" src="https://user-images.githubusercontent.com/24381562/69874767-c08de180-12f6-11ea-924d-ad74ae18609c.png">

thank you  though this works as a work around but i dont see as a solution since the derived content 
on mat tab content shouldn't behave differently on the mat content type  

`If the tab contains several complex child components or the tab's contents rely on DOM calculations during initialization, it is advised to lazy load the tab's content.`

**Comment by paco76** [comment]
**list.component.html**

    <mat-tab-group #matTabGroup>
        <mat-tab label="TAB ONE">

            <cdk-virtual-scroll-viewport [matTabChangeEvent]="matTabChangeEvent">
            </cdk-virtual-scroll-viewport>

        </mat-tab>
        <mat-tab label="TAB TWO">

            //  ANOTHER VIRTUAL SCROLL

        </mat-tab>
    </mat-tab-group>

**list.component.ts**

    @ViewChild('matTabGroup') matTabGroup: MatTabGroup;
    matTabChangeEvent: boolean = false;

    // ON TAB CLICK
     this.matTabGroup.selectedTabChange.pipe(
      takeUntil(this.onDestroy),
      tap((tabChangeEvent: MatTabChangeEvent) => {

        // INFORM VIRTUAL SCROLL OF TAB CHANGE
        this.matTabChangeEvent = true;

      })
    ).subscribe();

**cdk-virtual-scroll-viewport.component.ts**

    @Input() matTabChangeEvent: boolean;
    @ViewChild('viewport') viewport: CdkVirtualScrollViewport;

    constructor(...) { }

    ngOnChanges() {
        if (this.matTabChangeEvent) {
            if (this.viewport) {
                this.viewport.scrollToIndex(0);
                this.viewport.checkViewportSize();
            }
        }
    }

**Comment by andrewseguin** [comment]
Lazy loading is likely the right thing here since it reduces the number of issues related to delayed layout rendering.
