### ISSUE TITLE
Angular 5: CSP style-src 'self' blocks all angular material styles and generates a  csp violation error on the browser console

### ISSUE THREAD

**Issue by Ragha2207** [angular/components#17783]
#### Bug, feature request, or proposal:
I have Angular 5 app running on Apache Server which has a strict csp style-src 'self'. All the styles of material components are getting blocked and generates violation errors on the browser console. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-cli: 1.6.0
Angular: 5
Material: 5.2.5
browsers: Chrome, Firefox

**Comment by jelbourn** [comment]
This isn't anything that Angular Material controls- the way Angular renders CSS happens at the framework level.

**Comment by Ragha2207** [comment]
Thanks for the information.
Does upgrading the Angular framework help in avoiding this issue?
