### ISSUE TITLE
How to target a container to open MatDialog

### ISSUE THREAD

**Issue by sampkme** [angular/components#17795]
#### What are you trying to do?

What are you trying to do?

#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? 

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: https://stackblitz.com/fork/components-issue 

Steps to reproduce:
1. 
2. 
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
