### ISSUE TITLE
Scroll event not fired with mat-sort-header

### ISSUE THREAD

**Issue by prom00** [angular/components#17807]
Hi all!

I've got a very weird issue. I'm showing data to the user with a table format and the matSort module. When I have the mat-sort-header atrribute added to a header, the scroll event is not fired at all times. The wheel event is however always fired.

This results in the window not scrolling (getting stuck). When you drag the scrollbar manually, the scroll is working again. However the time it stays working is shorter after manual scrolling.

#### Reproduction

I've tried to reproduce this on stackblitz, but can't reproduce it. While inserting my dataset in the example, everything keeps working.

When inserting the stackblitz example in our application, the bug still remains...
 
 
#### Expected Behavior

While scrolling the page, the scroll event should always be fired

#### Actual Behavior

The scroll event suddenly stops firing. The wheel event is still being fired...

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by awattarpeter** [comment]
We do experience the same issue. Even with Angular: 9.0.0-rc.5 and Ivy enabled. 

Scrolling with the mouse wheel works again flawlessly after adding the following style (style.scss):
```
.mat-sort-header-pointer-left, .mat-sort-header-pointer-right {
  display: none !important;
}
```
This issue might be related to #11301

**Comment by prom00** [comment]
That is indeed working! Perfect thank you!

The only issue what now happens is the icon isn't shown correctly. 
![image](https://user-images.githubusercontent.com/46184489/70516349-253b0e80-1b37-11ea-9425-dc0e646cce6e.png)

Should I build my own icons, or how did you fix this?


> We do experience the same issue. Even with Angular: 9.0.0-rc.5 and Ivy enabled.
> 
> Scrolling with the mouse wheel works again flawlessly after adding the following style (style.scss):
> 
> ```
> .mat-sort-header-pointer-left, .mat-sort-header-pointer-right {
>   display: none !important;
> }
> ```
> 
> This issue might be related to #11301

**Comment by prom00** [comment]
I've tested Firefox, Firefox has no issues, looks like a Chrome 78 issue... 

Looks like 79 is literally planned:
![image](https://user-images.githubusercontent.com/46184489/70540869-49faaa80-1b66-11ea-9f09-4b2f59bb32cf.png)

**Comment by prom00** [comment]
![image](https://user-images.githubusercontent.com/46184489/70603356-aa392d00-1bf6-11ea-9f4c-4110085da5b0.png)

The update has fixed the issue. Thanks for the mentions, as this has made it more clear to me!
