### ISSUE TITLE
Small fix on components lists left menu in official website

### ISSUE THREAD

**Issue by davideas** [angular/components#17803]
Not a bug related to the components, just, could you please simply remove the CSS property `height` currently set to `75vh` in `docs-component-viewer-nav-content` element in your official site https://material.angular.io/components ?
It causes scrolling issue during consultation of documentation, make it show content as much as it is: simply remove the height property or make it fixed. Thanks.

**Comment by crisbeto** [comment]
I think the idea with that `max-height` is so that you don't have to scroll the entire page to click on a different navigation item.

**Comment by crisbeto** [comment]
Closing since this is working as expected.
