### ISSUE TITLE
Dialog, performance impact

### ISSUE THREAD

**Issue by striky1** [angular/components#17808]
#### Reproduction

https://stackblitz.com/edit/components-issue-5seg4e

Steps to reproduce:

1. Run ng.profiler.timeChangeDetection()
2. Run at least three attempts (keep results in your mind or wherever)
3. Open Mat Dialog Component
4. Run again at least three attempts
5. Compare with previous results without Mat Dialog Component and you will see how much has this Component impact on performance
 

#### Expected Behavior

Similar performance as it is without opened Mat Dialog Component.

#### Actual Behavior

Big impact of performance during the opened Mat Dialog Component.

#### Environment

- Angular: 8.x.x
- CDK/Material: 8.x.x
- Browser(s): 
    Chrome v78.0.3904.97
    Firefox v70.0.1
    Safari v13.0.3
- Operating System (e.g. Windows, macOS, Ubuntu): 
    macOS v10.14.6

**Comment by jelbourn** [comment]
(going back and triaging older issues)

Looking at the stackblitz, I only see differences in the 1/1000th of a millisecond range. Is that what you're referring to here?

**Comment by striky1** [comment]
@jelbourn I'm referring what is written in StackBlitz.

Nr. | Detection Cycles | ms per check | opened dialog
-- | -- | -- | --
1 | ~73948 | 0.01 | FALSE
2 | ~90875 | 0.01 | FALSE
3 | ~92807 | 0.01 | FALSE

vs
Nr. | Detection Cycles | ms per check | opened dialog
-- | -- | -- | --
1 | ~15631 | 0.03 | TRUE
2 | ~25970 | 0.02 | TRUE
3 | ~23741 | 0.02 | TRUE

It's not big performance impact (0.01 - 0.02ms slower) but it's weird that it happens just because is Dialog opened. I wanted to show that probably is something not ideal on that Component.

Thank you

**Comment by jelbourn** [comment]
How large of a magnitude impact are you seeing in more complex scenarios? With the simplified example, I probably wouldn't invest any time into investigating sub-millisecond differences. If adding more components amplifies this to bigger effects, it might be worth looking into.

**Comment by wagnermaciel** [comment]
Closing because no clarification was provided.
