### ISSUE TITLE
mat-form-field with appearance set to outline throws type error on older browsers

### ISSUE THREAD

**Issue by philmayfield** [angular/components#17810]
#### Reproduction

Steps to reproduce:
1. Open the [form-field example page](https://material.angular.io/components/form-field/overview) on Edge <= v22
Note: the behavior has been fixed in the current version of Edge (v24 at the time of writing)
 
 
#### Expected Behavior

What behavior were you expecting to see?
No type errors.

#### Actual Behavior

What behavior did you actually see?
`stack: "TypeError: Object doesn't support property or method 'Symbol.iterator' at t.prototype.updateOutlineGap..."`

I believe the error is originating from [this line of code](https://github.com/angular/components/blob/b56bcadaeaf2420c7a0e3dac429f47e67a058bee/src/material/form-field/form-field.ts#L562), and could probably be fixed by changing it to:

`for (const child of Array.from(labelEl.children)) {...`
or
`Array.prototype.forEach.call(labelEl.children, function (child) {...`

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2
- Browser(s): MS Edge 42
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by aeldar** [comment]
Temporary fix for Material consumers is to add this polyfill to `polyfill.ts`:

`import "core-js/fn/symbol/iterator.js";`

**Comment by aecz** [comment]
> Temporary fix for Material consumers is to add this polyfill to `polyfill.ts`:
> 
> `import "core-js/fn/symbol/iterator.js";`

Works but adds more than 100 lines of code.
For Edge at least it can be solved with just the following line:
```js
HTMLCollection.prototype[Symbol.iterator] = [][Symbol.iterator];
```

Also, the error is due in my opinion to an incorrect use of the API: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children
Edge supports Symbol and iterators perfectly without polyfills. You just can't use an `HTMLCollection` like an `array` if you follow the specs: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection
