### ISSUE TITLE
Layouting with mat grid list

### ISSUE THREAD

**Issue by LRagji** [angular/components#17821]
#### Documentation Request

I understand mat-grid-list can be used for page layouts and most blog/videos/documentation i saw explain only basic layouts, i felt need for documentation where a lil moderate to complex layouts needs to be explained using matgrid..Eg: A grid tile content which grows in height, tweet list. If there is any documentation or group for the same.. where mat grid is explained in detail please let me know..

**Comment by jelbourn** [comment]
The only docs/examples currently are https://material.angular.io/components/grid-list. 

We don't have any plans to add more features for grid-list, since it's mostly been made obsolete by CSS Grid.

**Comment by LRagji** [comment]
Does it make sense to include obselete tag on docs so that new developers can hook up on css grid...

**Comment by jelbourn** [comment]
We have an item on the backlog to decide what exactly to do with `mat-grid-list`. It might be updating it to use CSS Grid, it might be adding new features that make it more useful, or it might be deprecating it.
