### ISSUE TITLE
[Discussion] Expose underlying Google Map object

### ISSUE THREAD

**Issue by luckmager** [angular/components#17827]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Add <google-map ~></google-map< to your template.
2. Add @ViewChild(GoogleMap, { static: false }) map: GoogleMap to your component
3. Construct a KmlLayer: 
kmlLayer: google.maps.KmlLayer = new google.maps.KmlLayer({
    url: '/assets/test.kml',
});

4. Try to use the setMap() function:
ngAfterViewInit() {
    this.kmlLayer.setMap(this.map);
}
 
#### Expected Behavior

What behavior were you expecting to see?
A layer above my map based on the .kml file

#### Actual Behavior

What behavior did you actually see?
error: InvalidValueError: setMap: not an instance of Map

The current setMap function does not accept a GoogleMap instance as arg...

#### Environment

- Angular: 8.2.14
- CDK/Material: 9.0.0-rc.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by jelbourn** [comment]
The reason this does not work is that you're passing the `GoogleMap` _Angular Component_, not the underlying Google Maps API map object. We don't currently expose this underlying object, but maybe we should.

**Comment by mbehrlich** [comment]
Right now the underlying Google Map is the _googleMap property on the GoogleMap component. I think it's a good idea to expose this as `googleMap` though, so I will do that.
