### ISSUE TITLE
Import modal in app.module

### ISSUE THREAD

**Issue by LudwigBrio** [angular/components#17831]
#### Bug, feature request, or proposal:
I'm using lazy loading but when I want to define a component as modal, I have to import it and al its child componenrts in app.module in entryComponents.

#### What is the expected behavior?
I want to import it in the child module

#### What is the current behavior?
I have to import it in app.module

**Comment by aneeskodappana** [comment]
what is the actual issue you are facing?

you have to import the component into the module and register it on entry components and declaration.
if you want to use the component in multiple modules you need to create a shared module and register the component as you did in the app.module and also need export it too. (remove from app.module)

then you can import that shared module into your lazy loaded modules and use the component as a modal.

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
