### ISSUE TITLE
CdkVirtualScrollViewport smooth scroll not working in Safari

### ISSUE THREAD

**Issue by waterplea** [angular/components#17847]
#### Reproduction

Here's a fork of virtual scroll demo with a button to reproduce the issue:
https://stackblitz.com/edit/angular-virtual-scroll-smooth-ios

Steps to reproduce:
1. Call scrollToOffset/scrollToIndex with `'smooth'` behavior on Safari
 
 
#### Expected Behavior

Viewport scrolls smoothly

#### Actual Behavior

Viewport scrolls immediately in Safari and smoothly in good browsers

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS/iOS

#### Other details

This is probably because it uses native scrollIntoView with behavior and it is not supported in Safari. If Angular team will not include the fallback with its CDK, it is probably good to mention this limitation on the Scrolling demo page of the CDK.

**Comment by waterplea** [comment]
I also tried these 2 polyfills and it didn't help:
https://www.npmjs.com/package/scroll-behavior-polyfill
https://www.npmjs.com/package/smoothscroll-polyfill

**Comment by nikxco** [comment]
> I also tried these 2 polyfills and it didn't help:
> https://www.npmjs.com/package/scroll-behavior-polyfill
> https://www.npmjs.com/package/smoothscroll-polyfill

```javascript
import smoothscroll from 'smoothscroll-polyfill';

smoothscroll.polyfill();
document.documentElement.style.scrollBehavior = "";
```
Add the above lines in `main.ts` file, that should do the trick.
