### ISSUE TITLE
Dialog opened on page with scrollbars leads to invisiblity of the page in the background 

### ISSUE THREAD

**Issue by tomatenspaten** [angular/components#17854]
#### What are you trying to do?

I want to open a dialog from a page. If the page has no scrollbars you can see the opened dialog and in the background you can still see the page.
If there are scrollbars on the page (for example when more data is displayed) and i open the dialog then the dialog is shown and the page is not visible in the background.

#### What troubleshooting steps have you tried?

I have already tried to find some hints in the DOM if something is different when the page is not showing but without success.
I also tried a dirty way and deactivating the scrollbars right before opening the dialog. But that didn't help either.
Also i tried to switch to CDK/Material: 8.2.3 but that had too many dependencies (including going to Angular 8) which led to nearly the whole applications appearance being broken.

#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by andrewseguin** [comment]
Sorry for the delay in providing help with this - we are currently limited on resources for troubleshooting issues. You will probably have better luck getting help if you post on StackOverflow. Note that it is much better if you can provide a reproduction on StackBlitz
