### ISSUE TITLE
In Mat Table with mat-sort-header bug on scroll 

### ISSUE THREAD

**Issue by Alina177** [angular/components#17856]
#### Reproduction
https://stackblitz.com/edit/angular-1vg9gn-trp98z?file=app%2Ftable-basic-example.html

It's a first bug in your components, respect for your staff. But today I find an interesting bug
Steps to reproduce:
1. Just create a basic table from  https://material.angular.io/components/table/overview with sort and test in Chrome Browser
2. And try to scroll...ooops(((( 
 
 
#### Expected Behavior

What behavior were you expecting to see?
Correct work with scrolling

#### Actual Behavior

What behavior did you actually see?
Didn't work scroll

#### Environment

- Angular: 
- CDK/Material: ^8.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by tomicarsk6** [comment]
Can you explain a little bit, which type of scroll is not working, scrolling with mouse, or scrolling with keyboard arrows?

**Comment by Alina177** [comment]
Actually, both. All that you need is table with using mat-sort-header and scroll in you table or for example scroll in Mat Dialog. Just try it

**Comment by tomicarsk6** [comment]
I tried that, but I don't see any problem with scroll, it works normally on your stackblitz example to, both with mouse and with arrows.

**Comment by ShivPandey** [comment]
> #### Reproduction
> https://stackblitz.com/edit/angular-1vg9gn-trp98z?file=app%2Ftable-basic-example.html
> 
> It's a first bug in your components, respect for your staff. But today I find an interesting bug
> Steps to reproduce:
> 
> 1. Just create a basic table from  https://material.angular.io/components/table/overview with sort and test in Chrome Browser
> 2. And try to scroll...ooops((((
> 
> #### Expected Behavior
> What behavior were you expecting to see?
> Correct work with scrolling
> 
> #### Actual Behavior
> What behavior did you actually see?
> Didn't work scroll
> 
> #### Environment
> * Angular:
> * CDK/Material: ^8.1.4
> * Browser(s): Chrome
> * Operating System (e.g. Windows, macOS, Ubuntu): macOS

I also facing the same issue with chrome browser. only mouse wheel scroll is not working

**Comment by Relic** [comment]
I'm having the same issue with a project. My project is quite complex but if the current stackblitz doesn't work and nobody can reliably reproduce it, I can try to create one with this bug reproducible when I have some time.

In my case, if mat-sort-header is present, my mouse wheel scroll semi-randomly breaks and stops scrolling after a short time of scrolling around, in different places depending on the speed of the mouse wheel movement. Moving the scroll bar or scrolling with arrow keys, or some other random things that I couldn't reliably identify (waiting a while or messing around in dev console seem to fix it sometimes), fix it temporarily until I start scrolling with mouse wheel again.

This makes tables with sort headers completely unusuable currently.

**Comment by skobak** [comment]
I also experience the same issue.

![image](https://user-images.githubusercontent.com/6191306/70534478-70ffaf00-1b5b-11ea-8eee-86a757adf62a.png)

Easy to test: 
The scroll will work well again If you delete  code in a red rectangle (image above) in the inspector,

**Comment by Relic** [comment]
Following @skobak's comment I dug a little deeper. Seems something with the pointer indicating sort direction itself is breaking it somehow.

![image](https://user-images.githubusercontent.com/2211270/70536310-bec9e680-1b5e-11ea-97ee-af5b32a62b1c.png)

Deleting the three indicated elements fixes the problem, but keeping any of them still causes it to break.

**Comment by ShivPandey** [comment]
> I'm having a similar issue here. The current stackblitz doesn't reproduce this for me either, so if nobody can reliably reproduce it, I can try to create one with this bug reproducible when I have some time.
> 
> Angular: ^8.2.12
> CDK/Material: ^8.2.3
> Browser(s): Chrome
> Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 64-bit
> 
> In my case, if mat-sort-header is present, my mouse wheel scroll semi-randomly breaks and stops scrolling after a short time of scrolling around. The place where it breaks is reproducible in that if I scroll slowly it always breaks in the same place and scrolling faster breaks it reliably in the same place further down the page. It doesn't seem to happen in my case if there is not much to scroll, but if there are many elements and a lot to scroll through it breaks consistently. Moving the scroll bar or scrolling with arrow keys, or some other random things that I couldn't reliably identify (waiting a while or messing around in dev console) seemed to fix it temporarily until I start scrolling with mouse wheel again.
> 
> This makes tables with sort headers completely unusuable currently.

exactly similar things happened and mat-table-sort is unusable now

**Comment by andrewseguin** [comment]
I suspect we had a bug before but has been since fixed - I'm not seeing any issues
