### ISSUE TITLE
Angular apps removing eachothers overlay

### ISSUE THREAD

**Issue by Gurran** [angular/components#17865]
#### Reproduction

Steps to reproduce:
1. Have two angular applications on same page (Let's call them A and B)
2. Open Overlay on the app highest up the HTML (A)
3. Close Overlay
4. Open Overlay in the other app (B)
5. Open Overlay in the first app (A)
 
 
#### Expected Behavior

What behavior were you expecting to see?

Overlay for app A should be visible

#### Actual Behavior

What behavior did you actually see?

Overlay never opens. Overlays for app A is broken. 

#### Why I think this is happening

What happens is that when the second apps overlay is opened? OverlayContainer.prototype._createContainer() is called. Where all divs with the class 'cdk-overlay-container' is removed and overwritten. This breaks all future overlays for app A. 

I've tried to remake the original div which app A used. But I does not seem to work.

Function in question: https://github.com/angular/components/blob/036729dc1a7b41236fcda9b23c578f9ef65b484c/src/cdk/overlay/overlay-container.ts#L50-L68

#### Environment

- Angular: 9.0.0-rc.4
- CDK/Material:
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows

**Comment by crisbeto** [comment]
Should've been fixed by https://github.com/angular/components/commit/29eec7729253ef8329267dc21eb604eacdf15c7f a few months ago.
