### ISSUE TITLE
Recreating FormGroup with disabled attribute has different effect on matSelect vs matInput

### ISSUE THREAD

**Issue by kyletanders** [angular/components#17860]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-qr6rcq

Steps to reproduce:
1. Click Recreate Form button
2. Notice that the input is disabled but the mat-select is not

Also just for comparison see that calling formControl.disable() does work as expected:
3. Reload the page
4. Click 'Disable Function' button
5. Notice both input and select are disabled as expected 
 
#### Expected Behavior

What behavior were you expecting to see?
Expected matSelect and matInput to both be disabled when creating a new FormGroup where the disabled value was set to true for both of them.

#### Actual Behavior

What behavior did you actually see?
Only the matInput was disabled

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Skfsh** [comment]
Actually this issue applies to other controls as well.

https://stackblitz.com/edit/angular-8-material-starter-template-szedxq?file=src%2Fapp%2Fapp.component.html

Only Input, datepicker and autocomplete work as expected.

**Comment by crisbeto** [comment]
This came up in https://github.com/angular/components/issues/17985.

**Comment by kyletanders** [comment]
Quick note on this... it appears the datepicker has a similar issue.  The input itself seems to be disabled, but the icon that triggers the datepicker is still enabled and allows you to select a date.  See demo from Skfsh:  [(https://stackblitz.com/edit/angular-8-material-starter-template-szedxq?file=src%2Fapp%2Fapp.component.html)]
