### ISSUE TITLE
form-field: expose typography variables for customization

### ISSUE THREAD

**Issue by VincentG85** [angular/components#17878]
Would it be possible to allow setting the $infix-padding variable when customizing theme via the @mat-core mat-core mixin ? 

[Source](https://github.com/angular/components/blob/master/src/material/form-field/_form-field-outline-theme.scss#L87)

**Comment by iammikecohen** [comment]
I would also like to see this feature so I have written a more detailed feature request. If this is something deemed worth adding I will also contribute to the PR if desired. Thanks for the consideration.

**Overview of the Issue**
Sass maps are used to set many theming variables in Material. Material uses the `$config` map passed to mixins to get values, or computes local mixin variables based on values from the config. Other Sass variables are declared as defaults but can be changed at compilation time. Padding is often based on the relative unit `em` which directly relates to font size of that element. There is no way to change this ratio without CSS overrides.
![image](https://user-images.githubusercontent.com/12703795/80763000-32b35e00-8b03-11ea-8987-b06969a8afb6.png)
![image](https://user-images.githubusercontent.com/12703795/80763142-7dcd7100-8b03-11ea-975b-156f9260b043.png)

**Motivation for or Use Case**
Form elements. Sometimes a UI designer decides that a form filed or dropdown needs to be "tighter" than usual. This is achievable by writing CSS overrides to change the padding of the dropdown or form field but it would feel more maintainable to create a material theme that's configured to have a smaller ratio between font size and padding.
![image](https://user-images.githubusercontent.com/12703795/80763447-24b20d00-8b04-11ea-8d0c-2c23de12b0d2.png)

**Suggest a Fix**
Replace hard coded variables related to infix with a variable pulled from the config Sass map or use a ternary like `if` statement to null check the config map and use the previously hard coded `em` value as a fallback.

**Comment by devversion** [comment]
Hello! Our components follow the Material Design specification as closely as possible. We recently started working on density as described per Material Design spec. That should allow developers to increase density (i.e. reducing spacing) for components such as the form-field.

In general though, I agree that it would make sense to have these variables at top-level at least, so that they can be overridden. Marking this as feature request w/ P5.

This _should_ also be fixed / more customizable with the upcoming MDC-based form-field implementation.

**Comment by amysorto** [comment]
Closing this issue since MDC based components are now the default components and the legacy ones have been removed. These values can be adjusted by updating the CSS variable. Current work is ongoing to make these overrides easier as well.
