### ISSUE TITLE
Implement the radioGroup property for a radio button as an input binding

### ISSUE THREAD

**Issue by Maus3rVonDutch** [angular/components#17879]
#### Feature Description

Hi,

I think the current implementation of the radio-buttons in relation to the the radio-group is very limiting, you cannot use the radio group in a custom parent control and the radio button in custom child controls. 
Consider implementing the `radioGroup` property of the radio button as an `@Input()` binding.

#### Use Case

Consider the following scenario: I would like to create an abstraction for rendering questionnaires, the html code might look something like this:

```
<mnc-questionnaire [entityKey]="'QST_THE_FIRST_QUESTIONNIARE'"
  [questionnaireForm]="questionnaireForm">
  <mnc-question [entityKey]="'Q_FIRST_QUESTION'">
    What do you think of the first question?

    <mnc-answer-options-group>
      <mnc-answer-option-radio [entityKey]="'A_OPTION_A'">Option A</mnc-answer-option-radio>
      <mnc-answer-option-radio [entityKey]="'A_OPTION_B'">Option B</mnc-answer-option-radio>
      <mnc-answer-option-radio [entityKey]="'A_OPTION_C'">Option C</mnc-answer-option-radio>
    </mnc-answer-options-group>
  </mnc-question>

  <mnc-question [entityKey]="'Q_SECOND_QUESTION'">
    What about the second question?
    <mnc-answer-options-group>
      <mnc-answer-option-radio [entityKey]="'A_OPTION_1'">Ok that's fine</mnc-answer-option-radio>
      <mnc-answer-option-radio [entityKey]="'A_OPTION_2'">Sorry, I don't agree</mnc-answer-option-radio>
    </mnc-answer-options-group>
  </mnc-question>
</mnc-questionnaire>
```

The template for the `mnc-answer-options-group` might look like:
```
<section [formGroup]="parentForm">
  <section [formGroupName]="formGroupName">
    <mat-radio-group class="answer-options-radio-group"
      [formControlName]="parent.entityKey">
      <ng-content></ng-content>
    </mat-radio-group>
  </section>
</section>

```

And template for the `mnc-answer-option-radio`:
```
<mat-radio-button
  class="answer-radio-button"
  [value]="entityKey">
  <ng-content></ng-content>
</mat-radio-button>
```

The current implementation expects the radio group to be a direct ancestor for the radio buttons (it is injected via the constructor), so it is not working for my use (different scope: parent vs child component).

A simple solution would be (besides the @Optional() constructor injection) to make the `radioGroup` property an `@Input()` binding

#### Temporary solution
For anyone struggling with this scenario: for now I solved this by simply subclassing the `MatRadioButton`, but I'd rather not do that because of any future breaking changes that might occur. 

Here is my simple solution:

```
@Component({
  moduleId: module.id,
  selector: 'mnc-radio-button',
  templateUrl: './mnc-radio-button.component.html',
  styleUrls: ['./mnc-radio-button.component.scss'],
  // tslint:disable-next-line: no-inputs-metadata-property
  inputs: ['disableRipple', 'tabIndex'],
  encapsulation: ViewEncapsulation.None,
  exportAs: 'matRadioButton',
  // tslint:disable-next-line: no-host-metadata-property
  host: {
    class: 'mat-radio-button',
    '[class.mat-radio-checked]': 'checked',
    '[class.mat-radio-disabled]': 'disabled',
    '[class._mat-animation-noopable]': '_animationMode === "NoopAnimations"',
    '[class.mat-primary]': 'color === "primary"',
    '[class.mat-accent]': 'color === "accent"',
    '[class.mat-warn]': 'color === "warn"',
    // Needs to be -1 so the `focus` event still fires.
    '[attr.tabindex]': '-1',
    '[attr.id]': 'id',
    '[attr.aria-label]': 'null',
    '[attr.aria-labelledby]': 'null',
    '[attr.aria-describedby]': 'null',
    // Note: under normal conditions focus shouldn't land on this element, however it may be
    // programmatically set, for example inside of a focus trap, in this case we want to forward
    // the focus to the native element.
    '(focus)': '_inputElement.nativeElement.focus()',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MncRadioButtonComponent extends MatRadioButton implements OnInit {
  @Input()
  radioGroup: MatRadioGroup;

  constructor(
    @Optional()
    @Host()
    radioGroup: MatRadioGroup,
    elementRef: ElementRef,
    _changeDetector: ChangeDetectorRef,
    _focusMonitor: FocusMonitor,
    _radioDispatcher: UniqueSelectionDispatcher,
    @Optional()
    @Inject(ANIMATION_MODULE_TYPE)
    _animationMode?: string,
    @Optional()
    @Inject(MAT_RADIO_DEFAULT_OPTIONS)
    _providerOverride?: MatRadioDefaultOptions) {
    super(radioGroup, elementRef, _changeDetector, _focusMonitor, _radioDispatcher, _animationMode, _providerOverride);
  }
}
```

Then you simple provide the radio group as a binding, retrieved from the parent:

Get from parent Parent:
```
export class AnswerOptionsGroupComponent implements OnInit {
  parentForm: FormGroup;

  formGroupName: string;

  @ViewChild(MatRadioGroup, { static: true }) radioGroup: MatRadioGroup;
```

Provide it tho child control with a binding:
```
@Component({
  selector: 'mnc-answer-option-radio',
  templateUrl: './answer-option-radio.component.html',
  styleUrls: ['./answer-option-radio.component.scss']
})
export class AnswerOptionRadioComponent implements OnInit {
  @Input()
  entityKey: string;

  questionForm: FormGroup;
  radioGroup: MatRadioGroup;

  constructor(
    @Host()
    public parent: AnswerOptionsGroupComponent) { }

  ngOnInit(): void {
    this.radioGroup = this.parent.radioGroup;
  }
}

// use it like this in the template: `answer-option-radio.component.html`:

<mnc-radio-button [radioGroup]="radioGroup"
  class="answer-radio-button"
  [value]="entityKey">
  <ng-content></ng-content>
</mnc-radio-button>

```

**Comment by Maus3rVonDutch** [comment]
Sadly virtually no response to this issue. At the time of writing as was just testing things out in PoCs, but now I need to implement some actual code for production. 

For anyone who is watching this and would like to use this hacky approach, I have a small update to get this working with reactive forms. I Just noticed the radio's weren't update when using patchValue of a bound reactive form.  This is caused by the implementation of the MatRadioButtonGroup which look for an explicit type:

```
/** Child radio buttons. */
  @ContentChildren(forwardRef(() => MatRadioButton), { descendants: true })
  _radios: QueryList<MatRadioButton>;
```

So when using a custom type as in the code above, the radio group won't find the new radios.

When can fix this by two ways I guess, subclassing the RadioGroup and fix the issue there, or add some further hacks to the custom radio component. Because this all is hacky anyway, I chose the latter, because I hope in the future this issue will be addressed and then I only have to change one component (i.e. the custom radio component)

So here is the code you need to add to your custom radio to make reactive forms updates working again:

```
ngOnInit(): void {

    super.ngOnInit();

    // TODO: HACK:
    // this is hacky and might break in the feature, but for now it seems to work.
    // the MatRadioGroup _radios property expects typeof MatRadioButton, so it find none because we use MncRadioButtonComponent
    // so register this radio manually, in order to let them (the checked status) be updated be reactive form changes
    this.radioGroup._radios = (this.radioGroup._radios instanceof QueryList
      ? [this]
      : [...this.radioGroup._radios as [], this]) as unknown as QueryList<MncRadioButtonComponent>;
  }
```

**Comment by jelbourn** [comment]
(triaging older issues)

The ARIA spec expects that a radio-group is the direct parent of a radio button, so putting it somewhere else in the DOM defaults the point of using radio-group for a11y. If you want to connect radio-buttons in different parts of the DOM to have unique selection, you can give them the same `name` property. Otherwise I don't see us adding other ways to connect separated radios/groups.
