### ISSUE TITLE
[Sort] Sort disabled using directive *ngIf in mat-table

### ISSUE THREAD

**Issue by castor-dev3** [angular/components#17875]
#### Reproduction

Use StackBlitz to reproduce your issue: [https://stackblitz.com/edit/angular-tqmkv7](https://stackblitz.com/edit/angular-tqmkv7)

Steps to reproduce:
1. Add a directive `*ngIf`to the material table.
2. Click to sort the table.
 
 
#### Expected Behavior

Sorted table

#### Actual Behavior

Sort not working

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.2.3
- Browser(s): Opera, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

PD: To workaround this issue i've used the property `[hidden]` instead of `*ngIf`

**Comment by andrewseguin** [comment]
You are not connecting the sort directive to the data source. Since the table is not in the view, the view query is not picking up the `MatSort`, so this `this.dataSource.sort = this.sort;` does not actually set the sort.
