### ISSUE TITLE
YouTube player component triggers change detection every 250ms

### ISSUE THREAD

**Issue by ukyo** [angular/components#17882]
#### Bug:

Currently, the YouTube player component triggers change detection every 250ms.
When a `YT.Player` instance is created, `setInterval` is called in it.

#### What is the expected behavior?

The YouTube player component should trigger change detection only by events.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-xnpnny?file=src%2Fapp%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/youtube-player 8.2.3

**Comment by crisbeto** [comment]
Fixed in master.
