### ISSUE TITLE
(Bug) The examples is not displayed correctly as on the material.angular.io 

### ISSUE THREAD

**Issue by long20014** [angular/components#17887]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-testign?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Install angular/material using npm
2. Import neccessary modules as the instructions
3. Copy the example on material.angular.io to test
 
 
#### Expected Behavior

What behavior were you expecting to see?
- Display exactly what is being shown on material.angular.io example.

#### Actual Behavior

What behavior did you actually see?
- The result on stackblitz link. 

#### Environment

"@angular/animations": "^8.0.0 || ^9.0.0-0",
"@angular/cdk": "8.2.3",
"@angular/common": "^8.0.0",
"@angular/compiler": "^8.0.0",
"@angular/core": "^8.0.0",    
"@angular/material": "^8.2.3",
"@angular/platform-browser": "^8.0.0",
"@angular/platform-browser-dynamic": "^8.0.0",

- Operating System (e.g. Windows, macOS, Ubuntu):  Window 10

**Comment by long20014** [comment]
![angular_material_bug_03](https://user-images.githubusercontent.com/29418477/70290618-12f56380-180b-11ea-8ef0-eb0947990b9d.png)
![angular_material_bug_02](https://user-images.githubusercontent.com/29418477/70290621-12f56380-180b-11ea-98f1-8cb24ceb9344.png)
![angular_material_bug_01](https://user-images.githubusercontent.com/29418477/70290622-138dfa00-180b-11ea-80fa-f217f512b5ba.png)

**Comment by manklu** [comment]
You must include a theme in your project. If you use the CLI to add material this will be done automatically.

**Comment by long20014** [comment]
@manklu  Ok, thanks
