### ISSUE TITLE
[@angular/cdk/drag-drop 8.2.3] Wrong place holder position when list is rorated

### ISSUE THREAD

**Issue by JoranLive** [angular/components#17880]
#### Bug:

@angular/cdk/drag-drop 8.2.3
When dragging an item into a drop list that has been rotated, the place holder does not appear at the proper location.
It rotation is 180 and we move the item to the top, place holder moves to the bottom.

![Capture d’écran du 2019-12-05 15-41-44](https://user-images.githubusercontent.com/58560323/70245084-cb70c800-1775-11ea-936e-61b7efcc56a8.png)

#### What are the steps to reproduce?

Very easy to reproduce from the "**cdk-drag-drop-custom-placeholder-example**" from "**https://material.angular.io/cdk/drag-drop/examples**".

Just add "transform: rotate(180deg);" in the "**.example-list**" class.

**https://stackblitz.com/angular/jbkglkkdddn**

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/cdk/drag-drop 8.2.3

**Comment by devversion** [comment]
That seems to be the same root cause as in #18143. Thanks for this report!
