### ISSUE TITLE
mat-button has focus after calling the method .close()/toggle()

### ISSUE THREAD

**Issue by vitarunaeva** [angular/components#17898]
#### Reproduction

This example from the `mat-sidenav` Angular documentation
https://stackblitz.com/angular/rxqmknvbkog?file=src%2Fapp%2Fsidenav-disable-close-example.ts

 
#### Expected Behavior

Mat-button (`open`) hasn't focus after calling the method `.close()`/`toggle()`

#### Actual Behavior

Mat-button (`open`) has focus after calling the method `.close()`/`toggle()`

#### Environment

- Angular: 8
- CDK/Material: 8.2.1
- Browser(s): Chrome  72.0.3626.109
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
That's because focus gets restored to where it was before the sidenav was opened. You can turn it off by setting `[autoFocus]="false"`.
