### ISSUE TITLE
Angular Mat Overlay removes previous overlays

### ISSUE THREAD

**Issue by ksharm-02** [angular/components#17899]
In the updated Mat Overlay (introduced in Angular v8), previous overlays are removed when a new overlay is opened.
[Here](https://github.com/angular/components/blob/27fae292721bcc48b68c16fe5c7ac5e928eaa57d/src/cdk/overlay/overlay-container.ts#L58) is the line.

**Issue**
When using multiple angular applications together (micro-frontend), the reference to overlays are kept in memory [here](https://github.com/angular/components/blob/7.3.x/src/cdk/overlay/overlay-container.ts#L40) but, the element is itself removed from DOM by other micro app. Consequently, the dialog is not shown.

**Comment by crisbeto** [comment]
Should've been resolved by https://github.com/angular/components/pull/17006.
