### ISSUE TITLE
Wrong overlay pane position after anchor scrolling in mobile Safari

### ISSUE THREAD

**Issue by pshurygin** [angular/components#17890]
#### Reproduction

https://angular-overlay-anchor.stackblitz.io
https://stackblitz.com/edit/angular-overlay-anchor

Steps to reproduce:
1. Open on a real iOS device via Safari
2. Click "Toggle overlay"
3. Click "Anchor link" => overlay is closed, window is scrolled to anchor
4. Click "Toggle overlay" again
 
#### Expected Behavior

Overlay position is correct

#### Actual Behavior

Overlay pane with anchor link is in the wrong position (not connected to toggle)

#### Environment

- Angular: 
stackblitz is using v8.2.14, the issue persists with latest v9.0.0-rc4
- CDK/Material: 
stackblitz is using v8.2.3, the issue persists with latest v9.0.0-rc4
- Browser(s): 
mobile Safari
- Operating System (e.g. Windows, macOS, Ubuntu): 
Tested on iOS 12.4 with iPhone 8plus

**Comment by pshurygin** [comment]
I would also like to have any workaround for this issue for the time being, as this one affects our iOS users in a really bad way.

**Comment by pshurygin** [comment]
It looks like the problem is caused by scrollStrategy: block, as it does not occur with default scrollStrategy.

**Comment by michaill** [comment]
there are many problems with iOS devices and positions or scrolls. the root cause is imho the incorrect evaulation of window.innerWidth and window.innerHeight.

solution is described here: https://github.com/angular/components/issues/18890#issuecomment-668444881

**Comment by crisbeto** [comment]
I think I saw it on a device stuck at iOS 12, but I wasn't able to on an iOS 13 device. Is anybody else seeing the issue?

**Comment by crisbeto** [comment]
Closing due to a lack of activity.
