### ISSUE TITLE
an error message is displays while running the app based on route

### ISSUE THREAD

**Issue by sincy123** [angular/components#17908]
Error: Invalid configuration of route ''. One of the following must be provided: component, redirectTo, children or loadChildren

RouterModule.forRoot
([ { 
path:'', loadChildren:'./mainhomemodule/mainhomemodule.module#MainhomeModule' 
} ])

In mainhome.module.ts,

RouterModule.forChild
([ { path:'', component:HomeComponentComponent, children:[{ path:'', component:HomeComponent }]
 } 
]) ],

**Comment by crisbeto** [comment]
Closing since there isn't much info to go on and the code snippet isn't using any Material/CDK functionality.
