### ISSUE TITLE
Cannot individually disable mat-chip in mat-chip-list

### ISSUE THREAD

**Issue by uncvrd** [angular/components#17907]
#### Reproduction

StackBlitz reproduction: https://stackblitz.com/edit/angular-xjycte
 
#### Expected Behavior
I set a ternary operator on the disabled attribute of the `mat-chip`. If it equals a certain value in the list, then that specific chip should be disabled. 

#### Actual Behavior
All of the chips are disabled regardless of ternary true/false value

This method works perfectly fine if I use it for the `removable` property (added in the stackblitz, as you can see one of the items does not have a "cancel" button), but I cannot seem to get this to work with the `disabled` property

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS 10.15.2

**Comment by crisbeto** [comment]
That's because you aren't binding to the `disabled` property, you're just setting an attribute. You should change the `disabled` to `[disabled]`.
