### ISSUE TITLE
mat-select custom panel height scroll bug

### ISSUE THREAD

**Issue by gpaimla** [angular/components#17901]
#### Reproduction

Use StackBlitz to reproduce your issue: https://angular-wbfhyg.stackblitz.io/

Steps to reproduce:
1. Add a custom height to the mat-select: (https://stackblitz.com/edit/angular-wbfhyg?embed=1&file=src/styles.scss)
2. open the mat-select and select some options (EX: 5th option and last option)
3. close the select and reopen it
4. as soon as you open the select, scroll all the way down to the last option and then back up again to the first option. repeat this for about 5 seconds, if the scrolling doesnt get stuck within 5 seconds close and reopen the select (bug happens 4/5 times)
 
 
#### Expected Behavior

What behavior were you expecting to see?
Scrolling shouldnt get stuck via mouse scroll

#### Actual Behavior

What behavior did you actually see?
Scrolling via mouse scroll gets stuck

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome (Version 78.0.3904.108) (bug doesnt happen on firefox)
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by mmalerba** [comment]
I was able to repro this using the stackblitz provided, however after upgrading it to Angular 10 I can no longer reproduce: https://stackblitz.com/edit/angular-wbfhyg-tb8wc4?file=src%2Fapp%2Fdialog-overview-example-dialog.html
