### ISSUE TITLE
Is it possible to have the mat-label above the outline of the input?

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#17913]
### **What are you trying to do?**

I searched through the documentation and having a problem finding where I can specify a label `"floatLabel=always"` to be ABOVE the mat-form-field with the outline appearance `"appearance=outline"`. 

Is this even possible?

Label not above outline:
![Screen Shot 2019-12-10 at 11 38 59 AM](https://user-images.githubusercontent.com/11908147/70558455-27ef3100-1b42-11ea-970e-ba50a87f24ec.png)

Label above outline:
![Screen Shot 2019-12-10 at 11 41 35 AM](https://user-images.githubusercontent.com/11908147/70558456-27ef3100-1b42-11ea-82f3-d8df27721c25.png)

Thank you for any feedback!

**Comment by smileLilith** [comment]
+1 to how to do it as well I couldn't find that out

**Comment by tomicarsk6** [comment]
You can simply put mat-label outside of mat-form-field.

https://stackblitz.com/edit/angular-ggrkhy?file=src/app/form-field-label-example.html

**Comment by smileLilith** [comment]
Great, thank for reply and example.

Would it be possible to add this example to documentation?

**Comment by tomicarsk6** [comment]
I'm not sure that this should be added to the documentation, simply because labels above outline input fields are not following material design.

How labels should behave with text fields you can read in the link below.

https://material.io/components/text-fields/#usage

**Comment by omaracrystal** [comment]
> You can simply put mat-label outside of mat-form-field.
> 
> https://stackblitz.com/edit/angular-ggrkhy?file=src/app/form-field-label-example.html

Thank you!! So simple!

**Comment by tomicarsk6** [comment]
@omaracrystal  Can you close the issue, because it wasn't really an issue, it was more misunderstanding.
