### ISSUE TITLE
Tabs are no longer eagerly loaded

### ISSUE THREAD

**Issue by jedsmith13** [angular/components#17914]
#### Reproduction

See the basic example from the documentation.
https://stackblitz.com/angular/yrlkmpdepnm?file=src%2Fapp%2Ftab-group-basic-example.ts

#### Expected Behavior

As per the documentation, I would expect the contents of all three tabs to be rendered to the DOM unless I used the lazy-loading method described in the documentation.

I need this functionality as my tabs are intended to be accessed immediately and they contain important information for the page which should be crawlable.

#### Actual Behavior

Content of tabs "Second" and "Third" is only rendered when one of those tabs is active which removes the content for "First"

#### Environment

- Angular: ^8.2.9
- CDK/Material: ~8.2.2
- Browser(s): Tested in Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Tested in Ubuntu

**Comment by jelbourn** [comment]
This is working as intended; only the active tab appears in the DOM. The "eagerly loaded" part refers to the instantiation of the Angular component class for the tab content
