### ISSUE TITLE
Float label don't match right position

### ISSUE THREAD

**Issue by chobijaeyu** [angular/components#17919]
#### Reproduction

```
<mat-card class="login-card" [formGroup]="loginForm">
    <div [hidden]="!errorMsg">username or password wrong</div>
    <div>
        <h3><b>サインイン</b></h3>
    </div>
    <div>
        <mat-form-field appearance="outline">
            <i class="material-icons" matPrefix> person </i>
            <mat-label>ユーザーID</mat-label>
            <input type="text" matInput formControlName="username" required>
        </mat-form-field>
    </div>
    <div>
        <mat-form-field appearance="outline">
            <i class="material-icons" matPrefix> lock </i>
            <mat-label>パスワード</mat-label>
            <input type="password" matInput formControlName="password" required>
        </mat-form-field>
    </div>
    <div><button mat-raised-button [disabled]="!loginForm.valid" color="primary" (click)="onSubmit()">login</button>
    </div>
</mat-card>
```
 #### Actual Behavior

![inputError](https://user-images.githubusercontent.com/25117318/70586926-e2973600-1c0b-11ea-9ef6-ccf3989bbd94.gif)

#### Environment

- Angular: 8.0.6
- CDK/Material: @angular/material 8.2.2
- Browser(s):chrome
- OS: darwin x64

**Comment by Geronimo94** [comment]
Cannot reproduce your issue using your code in Stackblitz, look at this: https://stackblitz.com/edit/angular-of42wd?file=src/app/form-field-appearance-example.html

Having said that: Do you have some css in your source code that could be corrupting this styles?

**Comment by chobijaeyu** [comment]
@Geronimo94 thanks for your answer,
actually I tried to comment all styles,
still not looking good
![inputError2](https://user-images.githubusercontent.com/25117318/70971123-905e8500-20e3-11ea-9f27-75941f517587.gif)

**Comment by crisbeto** [comment]
The issue seems to come from the fact that we're measuring the outline gap before your font icon set has loaded. Before the icons have loaded the prefix just says "person" which is what pushes the gap towards the middle. I don't know whether there's a good way for us to know when a font icon set was loaded so that we can re-measure the outline gap. You should be able to work around it by calling `updateOutlineGap` on the `MatFormField`, although that isn't very convenient either.

**Comment by chobijaeyu** [comment]
> The issue seems to come from the fact that we're measuring the outline gap before your font icon set has loaded. Before the icons have loaded the prefix just says "person" which is what pushes the gap towards the middle. I don't know whether there's a good way for us to know when a font icon set was loaded so that we can re-measure the outline gap. You should be able to work around it by calling `updateOutlineGap` on the `MatFormField`, although that isn't very convenient either.

@crisbeto thanks for your answer,

I did this:

```
  @ViewChildren('inputMat') inputMats: QueryList<MatFormField>

......

  ngAfterViewInit() {
    this.onUpdateGap()
  }

  onUpdateGap(){
    setTimeout(() => {
      this.inputMats.forEach(x=>{
        x.updateOutlineGap()
      })
    });
```

Actually, It's no working.What I'm missing?

**Comment by crisbeto** [comment]
That might still be too early. Have you tried with a longer timeout?

**Comment by chobijaeyu** [comment]
@crisbeto 
500ms ,its works!
thank you.
