### ISSUE TITLE
[Table] Large amount of extra (empty) space added to the cell content for the nested divs

### ISSUE THREAD

**Issue by peterlitvak** [angular/components#17917]
I have a simple case where I need to add one div inside another inside the table cell.
It seems that if the outer div has width: 100% and the inner div has set width in px the cell grows beyond the original width of the outer div.

https://components-issue-vfxckd.stackblitz.io
https://stackblitz.com/edit/components-issue-vfxckd

If you comment out inner div in the last column you can see the default column size and if the inner (red) div is added the cell grows horizontally even though that the inner div is smaller that the outer one.

#### Environment

- Angular: 7.3.7
- CDK/Material: Material
- Browser(s): Chrome (latest)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by jelbourn** [comment]
This sounds like it doesn't have anything to do with Angular Material, it's just the behavior of CSS.
