### ISSUE TITLE
I'm getting angular material Date picker animation issue in my project what causing issue? im using angular 5 material 

### ISSUE THREAD

**Issue by Yadhunandansolus** [angular/components#17928]
![Capture11](https://user-images.githubusercontent.com/58779767/70630950-6bd15b80-1c52-11ea-87d6-729d895c5d07.PNG)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
