### ISSUE TITLE
Tree checklist not unchecking selection for node with single child

### ISSUE THREAD

**Issue by saikrishna-t7** [angular/components#17924]
#### Bug, feature request, or proposal:
When changing selection, the previously selected is not getting deselected if the previously selected item is the only child of the node.

#### What is the expected behavior?
The previous selection should get deselected when changing the selection.

#### What is the current behavior?
The previous selection does not get deselected when changing the selection.

#### What are the steps to reproduce?
The tree data
```jsonc
{
  Fruits: {
      Apple: null
      },
  Groceries: {
    'Almond Meal flour': null,
    'Organic eggs': null,
    'Protein Powder': null
  },
  Reminders: [
    'Cook dinner',
    'Read the Material Design spec',
    'Upgrade Application to Angular'
  ]
};
```
Not allowing multiple selections
`checklistSelection = new SelectionModel<TodoItemFlatNode>(false);`

Selecting `Apple` first, then selecting any other item does not deselect `Apple`

#### What is the use-case or motivation for changing an existing behavior?
I want to select only one item from the entire tree.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
**Angular**: 7.3.2
**Material**: 7.3.3
**OS**: Windows 10
**TypeScript**: 3.2.2

**Comment by crisbeto** [comment]
From what I can tell this is working as expected. Since it's an example of a checklist you're supposed to be allowed to select multiple items at the same time.
