### ISSUE TITLE
Input type="file" support

### ISSUE THREAD

**Issue by JDillon522** [angular/components#17922]
#### Bug, feature request, or proposal:
Feature Proposal

#### What is the expected behavior?
Instead of creating a hidden input and a button to handle file uploads it'd be great for `matInput` to support `type="file"` inside a `mat-form-field`. This would make error handling much smoother and more in line the UI.
`<input #fileUpload matInput mat-raised-button type="file"  accept="image/png, image/jpeg, image/jpg">`

#### What is the current behavior?
> ERROR Error: Input type "file" isn't supported by matInput.

**Comment by jelbourn** [comment]
This has been on our backlog for a long time (which we track in Jira), but we don't have any plans to work on it. The biggest obstacle is a lack of a Material Design spec for it.

**Comment by tomavic** [comment]
Still hardly needed!!!

**Comment by kellyprankin** [comment]
This would be really great if it was available. It gets real awkward when you have such a nice form and then you gotta implement some hacky thing for the file upload that doesn't play nice with the rest of what we've built.

**Comment by kellyprankin** [comment]
> This has been on our backlog for a long time (which we track in Jira), but we don't have any plans to work on it. The biggest obstacle is a lack of a Material Design spec for it.

Is there anything that can be done to help push for a Material Design spec for this?

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because implementing it on our end is going to be tricky since the implementation depends on the backend and we can't realistically cover all possible backend implementations.
