### ISSUE TITLE
Dates 'YYYY-MM-DD' parsed as UTC and  'MM/DD/YYYY' as local timezone

### ISSUE THREAD

**Issue by Andreea-G** [angular/components#17931]
#### Bug:

When calling `new Date()` on a string, a date of the form 'YYYY-MM-DD' is parsed as UTC meanwhile a date of the form  'MM/DD/YYYY' is parsed in local timezone.

#### What is the expected behavior?

All dates including 'YYYY-MM-DD' should be parsed as local timezone. E.g. both of these:
`new Date('12/10/2019')` and `new Date('2019-12-10')` should give (assuming you're in PST):
```
Tue Dec 10 2019 00:00:00 GMT-0800 (Pacific Standard Time)
```

#### What is the current behavior?
`new Date('12/10/2019')` gives 
```
Tue Dec 10 2019 00:00:00 GMT-0800 (Pacific Standard Time)
```
Meanwhile `new Date('2019-12-10')` gives
```
Mon Dec 09 2019 16:00:00 GMT-0800 (Pacific Standard Time)
```
Therefore if attempting to extract back the date, in the second case a date of December 10 ends up as December 9.

#### What is the use-case or motivation for changing an existing behavior?
It's inconsistent and unexpected behavior, which can lead to code that is error-prone.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All as far as I can tell.

<img width="1603" alt="Screenshot 2019-12-11 09 08 53" src="https://user-images.githubusercontent.com/8748158/70643459-e61fc280-1bf5-11ea-98e6-fb1543c25b4a.png">

**Comment by calebegg** [comment]
To be clear, these are the repro steps:

1) Type 2019-09-09 into the date picker
2) Press tab or click away
3) Date appears as 09/08/2019

Can reproduce on https://material.angular.io/components/datepicker/overview

**Comment by bdirito** [comment]
It's actually worse then that. Date parsing can be browser specific.

**This behavior is part of JavaScript itself not Angular.** See the docs at
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

The proposal to standardize this can be found at
https://github.com/tc39/proposal-uniform-interchange-date-parsing

Having said that its only stage 1 so I'd not expect a change anytime soon.

**Comment by calebegg** [comment]
Right -- I think my point here is that Angular should not use native Date parsing at all.

**Comment by mmalerba** [comment]
It is possible to use other date implementations (see https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings), but we do hope to improve the `NativeDateAdapter` as well https://github.com/angular/components/issues/8100
