### ISSUE TITLE
Option to disable focus on bottom sheets

### ISSUE THREAD

**Issue by nehalist** [angular/components#17944]
#### Feature Description

Currently if `autoFocus` is disabled the focus is still being set to the container:

https://github.com/angular/components/blob/45d34ad4ff85d36096df5ccef1b1f5658364372d/src/material/bottom-sheet/bottom-sheet-container.ts#L206-L215

It would be really useful to disable focus capturing entirely.

#### Use Case

In my case the bottom sheet is triggered by changing the value of a text input - which results in losing focus as soon as the bottom sheet opens.

As a workaround I'm saving the previously selected element and reset the focus to this element within `afterOpened`. The disadvantage of this workaround is that if you're switching focus before the bottom sheet is completely opened (e.g. by hitting tab) the focus is reset to the wrong element.

**Comment by crisbeto** [comment]
There are a couple more issues, aside from the one you listed:
1. Screen reader users would have no way of knowing that the bottom sheet was opened.
2. It would be a breaking change to modify the behavior of `autoFocus` to what you're proposing which means that we might have to add another focus-related flag to the config.

**Comment by jelbourn** [comment]
I don't see us supporting this; as a modal dialog, a11y strictly requires focus to move to the dialog element.
