### ISSUE TITLE
Using ngIf with matSort

### ISSUE THREAD

**Issue by cgeenen** [angular/components#17946]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
Create an angular material table with a sort  Like in the api examples, if you add an ngIf on the datasource within the table tag it will not work, if you remove the ngif it will

#### Environment

- Angular: 7.0.7
- CDK/Material: 7.0.0
- Browser(s): any 
- Operating System (e.g. Windows, macOS, Ubuntu): RHEL6

**Comment by crisbeto** [comment]
Can you post an example of what you're doing?

**Comment by andrewseguin** [comment]
You are probably trying to set the `MatSort` using a view query in `ngOnInit`. If you add an `ngIf`, that `MatSort` view query will be undefined during `ngOnInit`. You should set the sort when the view query populates after the table is rendered into the view
