### ISSUE TITLE
cdkDragFreeDragPosition error 

### ISSUE THREAD

**Issue by GabrielDambroski** [angular/components#17948]
When I add [cdkDragFreeDragPosition] to a div I get an error.

![Anotação 2019-12-12 110603](https://user-images.githubusercontent.com/43409178/70718679-69611700-1ccf-11ea-9df8-ef6e5868a3fc.png)

example:
```
<div class="example-box" cdkDragBoundary=".example-boundary" cdkDrag [cdkDragFreeDragPosition]="dragPosition">
  <h2>Test</h2>
</div>
```
 

- Angular: 8
- CDK/Material:
- Browser(s): chrome  78.0.3904.108
- Operating System: Windows:

**Comment by crisbeto** [comment]
I think the issue comes from the fact that you haven't included the `DragDropModule` in your module's `imports`.

**Comment by GabrielDambroski** [comment]
I am importing DragDropModule into my NgModule, and the drag drop function works, but when I add [cdkDragFreeDragPosition] to determine a position the error occurs.

**Comment by crisbeto** [comment]
That's odd, because the error points to the module not being included. If this is inside a lazy-loaded route, you might have to add the import to the lazy module as well.

**Comment by Achilles1515** [comment]
@GabrielDambroski try adding this instead of `cdkDragFreeDragPosition`.

`[cdkDragDisabled]="false"`

You should get a similar error if what Crisbeto said is correct.

**Comment by crisbeto** [comment]
Closing since there hasn't been any activity in a while.
