### ISSUE TITLE
Mat-button in dialog getting darken at the time opening the modal

### ISSUE THREAD

**Issue by suriyaJaay** [angular/components#17958]
Hi,

Could someone tell me how to fix the intermittent issue which is attachment?

I'm not sure, whether my issue is already recorded or not, but i don't find any solution so far.

**Issue:**

For testing purpose, i used to open and close the modal dialog as quickly as possible. suddenly the button getting darken at least two time for 6 to 10 click. 

Pls let me know if my don't share my issue clearly.

thanks

![button dark](https://user-images.githubusercontent.com/19813670/70798599-5c96fe80-1d75-11ea-9f87-abc92ec6e90f.png)

**Comment by DanielHabenicht** [comment]
If you want a quick answer you might be better off at [Stackoverflow](https://stackoverflow.com).

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
