### ISSUE TITLE
Subtitle in toolbar

### ISSUE THREAD

**Issue by noobcoder15** [angular/components#17954]
#### Feature Description

Android supports natively subtitles in the toolbar/actionbar. Angular Material does not.

Example: https://i.stack.imgur.com/Qrtbr.png

#### Use Case
The use case is to show additional information with a smaller font below the title.

Example:
title: #topic
subtitle: 123 subscribers

**Comment by jelbourn** [comment]
We have no plans to support this directly. However, the toolbar is little more than a div with a background color, so you can add any arbitrary content into it.
