### ISSUE TITLE
Closing sidenav with escape does not work when mode is "side" 

### ISSUE THREAD

**Issue by dauledk** [angular/components#17965]
#### Reproduction

Steps to reproduce:
1.  Open this [stackblitz](https://stackblitz.com/edit/sidenav-autofocus-bug) 
2. Click the sidenav.toggle() button to open sidenav
3. Press escape on your keyboard
 
#### Expected Behavior

What behavior were you expecting to see?
I was expecting the sidenav to close. 

#### Actual Behavior

Sidenav does not close.

#### Environment

- Angular: 8.2
- CDK/Material: 8.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

#### Workaround

There seems to be 2 workarounds. [Related SO question](https://stackoverflow.com/questions/59328308/how-to-close-angular-material-sidenav-with-escape).

1. Setting focus inside the sidenav, and then pressing escape
2. Adding a `@HostListener` on the esc key

**Comment by crisbeto** [comment]
We decided against fixing this, because the fix would depend on how the sidenav is used in the application. See the discussion in https://github.com/angular/components/pull/17967. For your case you should be able to fix it by adding adding another keyboard listener and using the API to close it.
