### ISSUE TITLE
Make it possibe to override $mat-dialog-padding

### ISSUE THREAD

**Issue by mackelito** [angular/components#17968]
#### Feature Description
Would like to be able to override the default padding of dialogs

#### Use Case
Do not want to use a custom panel for each dialog opened

**Comment by jelbourn** [comment]
We currently have no plans for this level of customization for `MatDialog` (especially via Sass variables), however we are working on a `CdkDialog` that is very similar but has no opinionated styles. It's currently in `@angular/cdk-experimental` but hasn't been released as stable yet.
