### ISSUE TITLE
mat-option fails to render display when value is null or undefined

### ISSUE THREAD

**Issue by Dorus** [angular/components#17980]
#### Reproduction

Use StackBlitz to reproduce your issue:  https://stackblitz.com/edit/angular-wponfn?file=src/app/select-overview-example.html

Steps to reproduce:
1.  Create `mat-options` with `[value]="null"`
2.  Select said `mat-options`
 
 
#### Expected Behavior

The selected display value is visible. Like it would be with plain `option` dropdown.

#### Actual Behavior

The selected display value is not visible.

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

Ps. this has been fixed in angular a couple years ago. See https://github.com/angular/angular/issues/10349

**Comment by crisbeto** [comment]
This works as expected. Setting it to `null` or `undefined` causes the option to be treated as a "reset" option which is the equivalent of declaring a native `option` without a `value`.
