### ISSUE TITLE
2 mat-autocomplete boxes overlapping. second box unclickable

### ISSUE THREAD

**Issue by kebuder** [angular/components#17987]
#### Reproduction
Steps to reproduce:
1. Place 2 mat-autocomplete elements underneath each other
2. Click the bottom mat-autocomplete and try to select an item
3. Item is not clickable and selects the autocomplete above.
 
 
#### Expected Behavior
Both autocomplete boxes should work independently.

#### Actual Behavior
The autocomplete box from the first element blocks the click function on the second box.
![image](https://user-images.githubusercontent.com/1346522/70996973-44581400-20d4-11ea-8058-9c166290a74b.png)

This visualisation shows the first box overlapping the second. Normaly you would not see this box but the "invisable" box will still interfere with the second box. So only Accum and Adalady are clickable.

#### Environment

- Angular: 7.2.15 
- Ionic 4.9.1
- CDK/Material: 7.3.7
- Browser(s): Chrome/firefox (mobile and web)
- Operating System: Windows 10

**Comment by CharlieReitzel** [comment]
Experiencing this issue as well.  It appears to be a manifestation of the broken Chrome decision to ignore autocomplete='off'.   Note, this problem occurs even when generating random values, e.g. autocomplete='123564sdfdsk34r2isdfposiduf posdi' in ngOnInit().   I can also see that matAutocomplete is respecting the native attribute.   So this really looks like a Chrome bug.

See [Issue 914451: Autofill does not respect autocomplete="off"](https://bugs.chromium.org/p/chromium/issues/detail?id=914451).

**Comment by mmalerba** [comment]
It seems to be working fine in this example https://stackblitz.com/edit/angular-r2e39d?file=src/app/autocomplete-simple-example.html what you're seeing is likely an issue with that app, not the autocomplete
