### ISSUE TITLE
angular component vs ReactDOM.render

### ISSUE THREAD

**Issue by codewithshehraz** [angular/components#17982]
#### Bug, feature request, or proposal:
PS:I have a react component, that have a button and on clicking, a modal popup shows. I compile the react build and use the js and cs files in a chrome extension.

My chrome extension put a div with class awvComponent on multiple places in a web app and my react component rendered against each element that have the class. Following code is doing this perfectly.
```

class App extends React.Component {
  render() {
    return(
    <div>
      <button type="button" className="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        show Modal
      </button>
      <div className="modal fade" id="exampleModal" tabIndex={-1} role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="false">
      Modal COde here
      </div>
    </div>
    );
  }
}
const elements = document.getElementsByClassName('awvComponent');
for(var i=0; i< elements.length; i++ ){
  ReactDOM.render(<App  />, elements[i]);
}
export default App;

```

Now I want to have the same implementation in angular.

I have created the same functionality in angular 8. Where I have a component that have button and on clicking button a modal appears. And its selector is awv-component.

When I put the selector in app.component.html multiple times my awv-component render multiple times in UI, means multiple button created and each have its own modal.

I have to use this functionality in my chrome extension.

I created the production build and put js and css code in my extension. My chrome extension injected some tags <awv-component></awv-component> in web application. And this time angular component only created for first tag and not for the other tags.

So is that is achievable in angular 8, to create a angular component and then render it out side the angular app, using the selector, on multiple places of html page
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link href="MY-STYLE-SHEET-CODE-OF-ANGULAR-PRODUCTION-BUILD"/>
  <title>Angular Component Reuse</title>
</head>
<body>

<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<script src="MY-JS-CODE-OF-ANGULAR-PRODUCTION-BUILD" />
</body>
</html>
```
#### What is the expected behavior?
```
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
```
should render 3 components.

#### What is the current behavior?
```
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
<MY-ANGULAR-COMPONENT></MY-ANGULAR-COMPONENT>
```
is rendering 1 component

**Comment by ahnpnl** [comment]
I don't think this question belongs to the context of this repo. You should ask this question on StackOverflow.

**Comment by jelbourn** [comment]
Yeah- I'd suggest asking this on StackOverflow. The GitHub issues here are for bugs/feature requests for Angular's common UI component libraies

**Comment by codewithshehraz** [comment]
I think it is the limitation in Angular we can't use its component multiple time, outside the root component.
