### ISSUE TITLE
Avoid adding multiple tooltip body click listeners

### ISSUE THREAD

**Issue by jelbourn** [angular/components#18004]
Tooltip defines a body click listener: https://github.com/angular/components/blob/b56bcadaeaf2420c7a0e3dac429f47e67a058bee/src/material/tooltip/tooltip.ts#L627

We probably don't want one of these per tooltip, and we also probably want to only register it when a tooltip is actually open. The way it is now, I'm wondering if it causes a change detection every time anyone clicks anywhere.

**Comment by crisbeto** [comment]
If I remember correctly, this listener is only registered while a tooltip is open. It's on the internal tooltip component which is created and destroyed for each open/close.

**Comment by jelbourn** [comment]
Oh yeah, I mistakenly thought it was the directive.
