### ISSUE TITLE
Material mat-stepper api says there is property "disabled" but there isnt any.

### ISSUE THREAD

**Issue by andreElrico** [angular/components#18014]
#### Documentation Feedback

where?:
https://material.angular.io/components/stepper/api#MatStepHeader

Its states:

> disabled: boolean | Whether the option is disabled.

But there is no such property:

Ref: 
https://github.com/angular/components/blob/a30094b4703776ffc1ffb2343b95c6c7cc22109d/src/material/stepper/step-header.ts#L67
https://github.com/angular/components/blob/a30094b4703776ffc1ffb2343b95c6c7cc22109d/src/cdk/stepper/step-header.ts#L22

**Comment by devversion** [comment]
Thanks for submitting this issue! This is a bug in our docs. We are tracking it with https://github.com/angular/components/issues/17148.
