### ISSUE TITLE
MenuItem Directive

### ISSUE THREAD

**Issue by rcketscientist** [angular/components#18013]
https://github.com/angular/components/blob/master/src/material/menu/menu-item.ts#L42

It is referred to as a directive, but is a `Component` and indeed doesn't have a template.  Is there a reason it's `Component`?

**Comment by crisbeto** [comment]
Technically all components are also directives, but we should be more accurate in the docs. I'm not sure about the point that it doesn't have a template, because one [can be found here](https://github.com/angular/components/blob/master/src/material/menu/menu-item.html).

**Comment by rcketscientist** [comment]
Meh, reading comprehension...it's gonna be big.  Totally missed the last line `templateUrl`, sorry.
