### ISSUE TITLE
Angular Material Button Component W3C Errors for Generated HTML

### ISSUE THREAD

**Issue by JoshMal** [angular/components#18010]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/angular-w3c-errors-mdqmtt

Steps to reproduce:
1.  Open the page generated by the angular code in the stackblitz link above. 
     https://angular-w3c-errors-mdqmtt.stackblitz.io/
2. Open developer tools (F12) in the page in step 1
3. Copy the <body> tag and everything inside of it
4. Navigate to the W3C Nu HTML Checker
5. Select the "Source" checkbox, and "text input" from the "Check by" dropdown
6. Replace the <body></body> tags with the code you have copied from the angular page.
7. Click the "check" button
8. Scroll to the errors that say "Element div not allowed as child of element button in this context."
 
 
#### Expected Behavior

What behavior were you expecting to see?

There should not be any markup errors thrown for the structure of the HTML generated by angular.

#### Actual Behavior

What behavior did you actually see?

There are markup errors thrown for the HTML structures of buttons generated by Angular Material. "Element div not allowed as child of element button in this context."

![image](https://user-images.githubusercontent.com/59030886/71189443-77231900-2248-11ea-825d-aa6abd1263b8.png)

![image](https://user-images.githubusercontent.com/59030886/71189535-97eb6e80-2248-11ea-9c82-f7afc0a5ad5a.png)

#### Environment

- Angular: 8
- CDK/Material:
- Browser(s): Chrome, Firefox and IE
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
This isn't something that we support.
