### ISSUE TITLE
[googlemaps] - zoomChanged -> zoom_changed

### ISSUE THREAD

**Issue by AerisG222** [angular/components#18026]
When using "@angular/google-maps": "^9.0.0-rc.0", the zoomChanged event never fires.

Currently, google-map.ts:222 reads as follows:

@Output() zoomChanged: Observable<void> = this._eventManager.getLazyEmitter<void>('zoomChanged');

However, based on the related google docs (which is nicely commented on line 220: https://developers.google.com/maps/documentation/javascript/reference/map#Map.zoom_changed) it looks like the event name should be "zoom_changed" rather than "zoomChanged".

**Comment by crisbeto** [comment]
Sorry about that, it looks like I messed up the name when I was redoing the way events are managed in #17845.

**Comment by AerisG222** [comment]
No worries - thanks for all the work you have put into this!
