### ISSUE TITLE
MatAutocomplete using custom height of MatOption (AUTOCOMPLETE_OPTION_HEIGHT issue)

### ISSUE THREAD

**Issue by DmitryAstafyev** [angular/components#18030]
#### Reproduction

Steps to reproduce:
1. Change height of option (for example due overwriting global styles)
2. Add many options to get a scroll box in the drop-down.
3. Focus input and press ARROW_DOWN 
 
Demonstration of the bug: https://stackblitz.com/edit/angular-aumbgt
 
#### Expected Behavior

Scrolling should happen **only** on last visible item in a drop-down list

#### Actual Behavior

Scrolling happens based on the height of item (in a drop-down list), which is hardcoded in 
AUTOCOMPLETE_OPTION_HEIGHT constant)

It doesn't make sense to customize component at all, because 48px is too much for many cases.

#### Environment

- Angular: 8
- CDK/Material: MatAutocomplete
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by DmitryAstafyev** [comment]
It's quite weird, why such a needed option like the height of item (option) isn't defined as input.
 
Probably I've missed something and there are some ways to modify it, but in documentation - nothing about how to do it. 

I really hope Angular's Team will comment on why 48px is all we need. 

If I've missed some way to define a height of option - well, it would be just awesome to have it in the documentation. 

While we are waiting for a response from Angular's Team, here is a solution:

#### Step 1. Change style.
It's the easiest moment. We can just change the global style. Let's use 24px instead 48px

```
mat-option.mat-option{
    position: relative;
    height: 24px!important;
    line-height: 24px!important;
    max-height: 24px!important;
}
```

#### Step 2. Overwrite original `_scrollToOption` method of `MatAutocompleteTrigger`
The pain is located here: https://github.com/angular/components/blob/49a1324acc05cec1c5ff28d729abfe590f6772dd/src/material/autocomplete/autocomplete-trigger.ts line 498, method `_scrollToOption`.

This method takes two hardcoded constants (`AUTOCOMPLETE_OPTION_HEIGHT`, `AUTOCOMPLETE_PANEL_HEIGHT`) and uses it to calculate new scroll position. Sure, if you have not 48px, but less or more - it will work incorrectly.

So, we have to **overwrite** this method. 

The most elegant way to do it - using `Directive` (keep in mind, we can get access with `@ViewChild()` to `MatAutocompleteTrigger` and change it in the scope of a parent component, but it's not a reusable solution).

#### Step 2.1. Create directive
```
import { Directive } from '@angular/core';
import { Host, Self, Optional, Input, OnInit } from '@angular/core';
import { MatAutocompleteTrigger, AUTOCOMPLETE_OPTION_HEIGHT, AUTOCOMPLETE_PANEL_HEIGHT } from '@angular/material';
import {
  _countGroupLabelsBeforeOption,
  _getOptionScrollPosition
} from '@angular/material/core';

@Directive({
    selector: '[matAutocompleteTriggerAccessor]',
})

export class DirectiveAccessor implements OnInit {
    
    @Input() optionHeight: number = AUTOCOMPLETE_OPTION_HEIGHT;
    @Input() panelHeight: number = AUTOCOMPLETE_PANEL_HEIGHT;

    constructor(
      @Host() @Self() @Optional() public _refTrigger: MatAutocompleteTrigger
    ) { }

    public ngOnInit() {
      if (this._refTrigger === undefined || this._refTrigger === null) {
        return;
      }
      this._refTrigger['_scrollToOption'] = this._scrollToOption.bind(this._refTrigger, this.optionHeight, this.panelHeight);
    }

    private _scrollToOption(
      this: MatAutocompleteTrigger,
      optionHeight: number,
      panelHeight: number,
    ): void {
      const index = this.autocomplete._keyManager.activeItemIndex || 0;
      const labelCount = _countGroupLabelsBeforeOption(
        index,
        this.autocomplete.options,
        this.autocomplete.optionGroups
      );
      if (index === 0 && labelCount === 1) {
        this.autocomplete._setScrollTop(0);
      } else {
        const newScrollPosition = _getOptionScrollPosition(
          index + labelCount,
          optionHeight,
          this.autocomplete._getScrollTop(),
          panelHeight
        );
        this.autocomplete._setScrollTop(newScrollPosition);
      }
  }
}
```
* So, we use "original" code of `_scrollToOption` method. Only one thing we do - avoid using constants: `AUTOCOMPLETE_OPTION_HEIGHT`, `AUTOCOMPLETE_PANEL_HEIGHT`
* instead these constants we are adding two inputs `optionHeight` and `panelHeight`
* as defaults values for new inputs, we are using values of `AUTOCOMPLETE_OPTION_HEIGHT`, `AUTOCOMPLETE_PANEL_HEIGHT`

#### Step 2.2. Add directive and addition inputs
Now we can modify our template and add a new directive and addition inputs.

```
<form class="example-form">
  <mat-form-field class="example-full-width">
    <input type="text" placeholder="Pick one" aria-label="Number" matInput [formControl]="myControl" [matAutocomplete]="auto" matAutocompleteTriggerAccessor [optionHeight]="24">
    <mat-autocomplete #auto="matAutocomplete">
      <mat-option *ngFor="let option of options" [value]="option">
        {{option}}
      </mat-option>
    </mat-autocomplete>
  </mat-form-field>
</form>
```
**Note**. Our directive `matAutocompleteTriggerAccessor` should be attached to `<input>`, but not to `<mat-autocomplete>`.

And that's all. Now all works as it should.

Here is a full solution: https://stackblitz.com/edit/angular-cn4ox8

**Comment by pandalzz** [comment]
Nice！

**Comment by devversion** [comment]
We need to re-audit this when we get to the point of having a MDC-based autocomplete. I'm thinking the height should be controlled by the density system we've been working on, but there should still be a way to override it at runtime through an inline style for example (like we did with the expansion panel density). Linking to the issue for later tracking: #16253
