### ISSUE TITLE
CDK portal throwing "HierarchyRequestError" in IE11

### ISSUE THREAD

**Issue by varad11** [angular/components#18039]
Encountered same issue as  #17110

**Issue:**
On IE11 when trying to display content on new window it gives "HierarchyRequestError".

HierarchyRequestError occurs when attaching portal to portal host

host.attach(this.portal);

**Current Behavior:**
The content is displayed on the main window instead of the new window. The issue is not encountered on Chrome & Firefox

**Expected Behavior:**
The content should be displayed on new window.

**Sample Code:**

```
import { Component, HostListener, ViewChild, OnInit, ComponentFactoryResolver, ApplicationRef, Injector} from '@angular/core';
import { CdkPortal, DomPortalOutlet } from '@angular/cdk/portal';
@Component({
  selector: 'app-window',
  template: `
    <ng-container *cdkPortal>
      <p>Testing External Window</p>
    </ng-container>
  `
})
export class WindowComponent implements OnInit{

  @ViewChild(CdkPortal) portal: CdkPortal;

  private exWindow: any;

  constructor(
    private componentFactoryResolver: ComponentFactoryResolver,
    private applicationRef: ApplicationRef,
    private injector: Injector) { }
      
  ngOnInit() {
    this.exWindow = window.open('', 'External Window Example', 'width=400,height=200,left=200,top=200');
    
    const host = new DomPortalOutlet(
      this.exWindow.document.body,
      this.componentFactoryResolver,
      this.applicationRef,
      this.injector
    );

    host.attach(this.portal);
  }
}
```

**Versions used:**

Angular: v7.0.1
Angular/cdk": "^8.2.3"
Browser: Internet Explorer 11

**Comment by manklu** [comment]
> Encountered same issue as #17110

Why do you think you will get another answer as https://github.com/angular/components/issues/17110#issuecomment-533897513 and https://github.com/angular/components/issues/17110#issuecomment-548534066?

**Comment by crisbeto** [comment]
As mentioned in https://github.com/angular/components/issues/17110, there's not much we can do about it since it's a browser limitation.
