### ISSUE TITLE
Angular Material - DOM nodes are not getting released in Browser memory after updating patch release 9.0.0-rc.7

### ISSUE THREAD

**Issue by KarthikeyanP21** [angular/components#18038]
@crisbeto, @vivian-hu, Angular Material - DOM nodes are not getting released in Browser memory after updating patch release 9.0.0-rc.7

Packages Used:

"@angular/cli": "^7.3.8",
"@angular/animations": "9.0.0-rc.7",
"@angular/cdk": "^7.3.3",
"@angular/common": "~7.0.0",
"@angular/compiler": "~7.0.0",
"@angular/core": "~7.0.0",
"@angular/forms": "~7.0.0",
"@angular/http": "~7.0.0",
"@angular/material": "^7.0.3",
"@angular/material-moment-adapter": "^7.0.3",
"@angular/platform-browser": "~7.0.0",
"@angular/platform-browser-dynamic": "~7.0.0",
"@angular/router": "~7.0.0",

#### Environment

- Angular: 7.3.8
- CDK/Material: 7.3.3/7.0.3
- Browser(s): Chrome 73
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 7/10

**Comment by manklu** [comment]
@KarthikeyanP21 
> "@angular/animations": "9.0.0-rc.7"
"@angular/core": "~7.0.0"

Why do you think that this versions are a good match?

**Comment by KarthikeyanP21** [comment]
@manklu, I have faced memory leak issue in current application which was developed under Angular 7 and that's why i put the patch version 9.0.0-rc-7 for animations.

I have verified with latest version of angular which is also having memory leak issue because of Material components (Date Picker/Select Dropdown/Modal Dialog/etc..), PFB the packages used:

"@angular/animations": "~9.0.0-rc.7",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~9.0.0-rc.7",
    "@angular/compiler": "~9.0.0-rc.7",
    "@angular/core": "~9.0.0-rc.7",
    "@angular/forms": "~9.0.0-rc.7",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~9.0.0-rc.7",
    "@angular/platform-browser-dynamic": "~9.0.0-rc.7",
    "@angular/router": "~9.0.0-rc.7",

Please advice me the right version of angular and its depedency which works perfectly. Thanks.

**Comment by balagurumahalinga** [comment]
https://github.com/manklu,

I'm on Angular material 7.3.3 still seeing the memory leak issue after select and dialog is triggered.

Also tried with latest dependencies like Angular material 8.2.3 and Angular/ animation _9.0.0-rc.7 , could not see any improvement. 

Does anybody know if there is possible workaround?

**Comment by manklu** [comment]
@balagurumahalinga If you want to try the fix you must update angular **and** material to the latest rc version. If you have still a leak you should provide a reproduction.

A simple 'I have a problem' is not sufficient to identify problems.

**Comment by devversion** [comment]
Yeah, that's unfortunately not sufficient information. We'd love to have a look at this. Memory leaks are definitely high priority. Please resubmit if you think that this is still an issue.
