### ISSUE TITLE
Autocomplete options overlaps the title bar

### ISSUE THREAD

**Issue by fzs1994** [angular/components#18037]
#### Documentation Feedback

Autocomplete options overlaps the title bar

![image](https://user-images.githubusercontent.com/10684213/71415542-3aa95000-2682-11ea-925d-389f5b936b29.png)

**Affected documentation page:** [Page Link](https://material.angular.io/components/autocomplete/examples)

**Comment by crisbeto** [comment]
Thank you for the report, but this is working as expected.
