### ISSUE TITLE
mat-select disableOptionCentering doesn't work with panelClass

### ISSUE THREAD

**Issue by webkhushboo** [angular/components#18045]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-rprnhe?embed=1&file=app/app.component.html

Steps to reproduce:
1. Create mat-select dropdown at the bottom of the page and panelClass to it for e.g `panelClass='custom-select'`
```
.custom-select {
 margin-top: 30px; 
}
```
2. Add 10-15 options in the list.
3. Select the last item in the dropdown list
4. Then click on item again . It will show the overlay separated from dropdown. 
 
 
![image](https://user-images.githubusercontent.com/10898595/71473015-52581400-27fb-11ea-8f32-3e8db27d1f75.png)

#### Expected Behavior

What behavior were you expecting to see?
Overlay for dropdown should touch the dropdown. 

#### Actual Behavior

What behavior did you actually see?
Overlay for dropdown is not touching the dropdown . When I checked the developer tools its showing the below property 
`transform: translateX(-16px) translateY(-225px);`

#### Environment

- Angular: ~7.2.0
- CDK/Material: ^7.3.6
- Browser(s): Chrome version 79.0.3945.88 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro

**Comment by webkhushboo** [comment]
@crisbeto 
Can you please suggest your input on this ?

**Comment by crisbeto** [comment]
@webkhushboo the select positioning isn't really set up to account for position changes from the `panelClass` so if you're doing it, it's at your own risk. The `panelClass` is meant mostly for changing the appearance.

**Comment by crisbeto** [comment]
Closing since this has been working as expected and there hasn't been any feedback in a while.

**Comment by webkhushboo** [comment]
@crisbeto 
If I have to disable centering of dropdown and I want options should be populated just below the dropdown , how should I do it?
