### ISSUE TITLE
CDK-Tree (FlatTree docs) - Collapsing doesn't collapse descendants

### ISSUE THREAD

**Issue by avrahamkam** [angular/components#18040]
#### Reproduction

The docs: https://material.angular.io/cdk/tree/overview#flat-tree
https://stackblitz.com/angular/ggqypydxrvv?file=src%2Fapp%2Fcdk-tree-flat-example.ts

(This issue doesn't effect MatTree).

Steps to reproduce:
1. Expand Vegetables
2. Expand Orange (to see Pumpkin and Carrots)
3. Collapse Vegetables

This is the expanded view:
<img width="243" alt="Screen Shot 2019-12-24 at 11 48 56 AM" src="https://user-images.githubusercontent.com/47183466/71420530-b506af80-2643-11ea-8192-2100689e09a8.png">

#### Expected Behavior
Pumpkin and Carrots will be hidden

#### Actual Behavior
Orange is hidden but Pumpkin and Carrots are visible
<img width="234" alt="Screen Shot 2019-12-24 at 11 49 02 AM" src="https://user-images.githubusercontent.com/47183466/71420500-9b656800-2643-11ea-9c63-24f8e76ee754.png">

#### Environment

- Angular: ^8.3.8,
- Material: ~8.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

#### Update

It seems that at the moment that `treeControl.toggle` is being called for both expand and collapse (because the `cdkTreeNodeToggle` is being used). Ideally, it should be using the `treeControl.collapseDescendants` method for collapse, and the `treeControl.expand` method for expand.

Stackblitz with proposed fix for the example in the docs:
https://stackblitz.com/edit/angular-d8rm6r?embed=1&file=src/app/cdk-tree-flat-example.ts

I've intentionally made use of the `treeControl` class instead of directly updating the `node.isExpanded` attribute.

**Comment by avrahamkam** [comment]
**Possible solution**

Instead of the click event triggering this:
```
(click)="node.isExpanded = !node.isExpanded"
```
It should look something like:
```
(click)="node.isExpanded ? collapseNode(node) : expandNode(node)"
```
With these functions in the component:
```
	expandNode(node) {
		node.isExpanded = true;
	}
	collapseNode(node) {
		node.isExpanded = false;
		let idx = this.treeData.indexOf(node) + 1;
		while (idx < this.treeData.length && this.treeData[idx].level > node.level) {
			this.treeData[idx].isExpanded = false;
			idx += 1;
		}
	}
```

**Comment by andyb-esdm** [comment]
The shouldRender method should be something like this:

    shouldRender(node: ExampleFlatNode) {
       let parent = this.getParentNode(node);
       while (parent) {
           if (!parent.isExpanded) {
               return false;
           }
          parent = this.getParentNode(parent);
       }
       return true;
    }

**Comment by harshilparmar** [comment]
Can I try this?

**Comment by CristhianParra** [comment]
Looks like this was already solved, since the error it's not longer happening in the docs page

**Comment by avrahamkam** [comment]
As @CristhianParra pointed out, this is no longer an issue.

**Comment by andyb-esdm** [comment]
Glad it's fixed. Thanks.
