### ISSUE TITLE
Paginator------jump to a specific page

### ISSUE THREAD

**Issue by lijunhaoabroad** [angular/components#18056]
#### Feature Description

Provide a brief summary of the feature you would like to see.

Hi, I would like to know how I can add a feature that jumps to a certain page on the paginator?
perhaps a dropdown list next to it which has the total pages allowing users to jump to a specific-numbered page?

Thank you ! 

#### Use Case

Describe the use case(s) that the proposed feature would enable.

**Comment by crisbeto** [comment]
Just noticed that this is a duplicate of https://github.com/angular/components/issues/7615.
