### ISSUE TITLE
Stripped down virtual scroller

### ISSUE THREAD

**Issue by Akxe** [angular/components#18073]
#### Feature Description

Provide some sort of API that would allow us to dynamically add or remove component the same way virtual scroller do, **but** here you would have to pass indexes of components to be shown.

#### Use Case

Fliping of book pages. (Turn JS and similar)

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

I don't really follow the request here. Feel free to open a new issue with more details.

**Comment by Akxe** [comment]
This can be frozen. I basically wanted cdk-portals,
