### ISSUE TITLE
mat-datepicker is unaware of timezones

### ISSUE THREAD

**Issue by olliekrk** [angular/components#18075]
#### Bug, feature request, or proposal:

This is a feature request.

#### What is the current behavior?

Currently mat-datepicker has no option to set the timezone, therefore currently selected date which is placed in a circle is always in system timezone.

#### What is the use-case or motivation for changing an existing behavior?

I would like to use mat-datepicker which is aware of currently selected timezone in my app.

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization

You can provide an alternate / custom date adapter to control the timezone being used.
