### ISSUE TITLE
Date picker (overlay) top section is hiding due to space issue.

### ISSUE THREAD

**Issue by spoonofdesign** [angular/components#18099]
Issue:
Date picker (overlay) top section is hiding due to space issue.
https://stackoverflow.com/questions/59584736/date-picker-overlay-top-section-is-hiding-due-to-space-issue

Expected behaviour:
If available space is less than automatically date picker (overlay) should shift and show full UI.

Current behaviour:
https://v6.material.angular.io/components/datepicker/overview

  
#### Environment

- Angular: 
- CDK/Material: 6.4.7
- Browser(s): Chrome/ IE Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Should've been fixed in 7.0.0 by https://github.com/angular/components/pull/11607.
