### ISSUE TITLE
select: when used in conjunction with grouping, the dropdown menu doesn't align with the select field

### ISSUE THREAD

**Issue by cybrooke** [angular/components#18119]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-ggkn8g?file=app%2Fapp.component.html

Steps to reproduce:
1. Open select menu
2. Observe dropdown option menu doesn't have the right width

![mat_select_with_group_offset](https://user-images.githubusercontent.com/24299332/71859348-37d54300-30f7-11ea-9db1-c3965df646eb.PNG)

 
#### Expected Behavior

For the dropdown menu to align with the select field underneath, like it does if no mat-opt-group is used.

#### Actual Behavior

The dropdown option menu doesn't fully cover the select field width; 

#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.0
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

From what I can see the div wrapper for the dropdown menu doesn't take into account the extra 0.75em padding on "outline" and "fill" form-field appearences.

**Comment by crisbeto** [comment]
You're right that it isn't wide enough, but the position is correct. According to the spec the text of the option in the dropdown has to align with the text inside the select field.

**Comment by mmalerba** [comment]
It's correct according to an older version of the spec, but the spec has updated. This is being tracked by https://github.com/angular/components/issues/18928
