### ISSUE TITLE
Datepicker swaps the day and month on manual input when MAT_DATE_LOCALE = da_DK or de_DE

### ISSUE THREAD

**Issue by Leandowich** [angular/components#18112]
#### Reproduction

Stackblitz displaying issue: https://stackblitz.com/edit/components-issue-eeoxhd

Steps to reproduce:
1. Write "8.1.2020" and blur/leave input field
2. See that the datepicker displays "1.8.2020"
 
#### Expected Behavior

I expect to see the valid date that I typed.

#### Actual Behavior

The day and month was switched around for no apparent reason

#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.0 
- Browser(s): Version 79.0.3945.88 (Officiel version) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro, Version 1809, OS build 17763.914

**Comment by tomicarsk6** [comment]
It's not an issue, is simply how Datepicker is working. By default it parses the date in mm/dd/yyyy format.
Defining locale is not enough, if you wan't to change default parsing format you need to create your own DateAdapter that extends NativeAdapter, and change the parse method in a way that suit your needs.
