### ISSUE TITLE
MatTable with MatTableDataSource scrolling problem on dataSource update 

### ISSUE THREAD

**Issue by LucaMurarolli** [angular/components#18122]
Hi,

 I'm pretty new to Angular and I did a CRUD RESTful application using HttpService, Mat-Table and MatTableDataSource. Everything is working fine except that in Chrome my table scrollbar always scroll to bottom when I refresh my datasource. Do you know what could it be? 
This is my code, as you can see when I close the dialog I call the getLinedevices() method that update the dataSource. 
If, for example, I am deleting a record in the middle of the table after the datasource updates the scrollbar scrolls to the bottom.
This doesn't happen in firefox.

Any suggestions will be appretiated,

Thanks,
Luca
```
export class LinedeviceComponent implements OnInit {

  displayedColumns: string[] = [....];
  linedevices: Linedevice[];
  linedevice: Linedevice;
  dataSource = new MatTableDataSource(this.linedevices);
  lineId: number;
  deviceId: number;
  description: String;
`
  /**
   * HttpClientService 
   */
  constructor(
    private httpClientService: HttpClientService,
    private location: Location,
    public dialog: MatDialog,
    public deleteDialog: MatDialog,
    public insertDialog: MatDialog
  ) { }

  ngOnInit() {
    this.getLinedevices();
  }

getLinedevices() {
    this.httpClientService.getLinedevices().subscribe(
      response => this.dataSource.data = response,
    );
  }
/*
   * Dialog di Delete  
   */

  openDeleteDialog(): void {
    const dialogRef = this.deleteDialog.open(DialogDeleteComponent, {
      width: '500px',
      data: { lineId: this.lineId, deviceId: this.deviceId, description: this.description }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The delete dialog was closed');
      /*console.log(result);*/
      this.getLinedevices();
    });
  }
```

**Comment by andrewseguin** [comment]
Unfortunately we are tight on resources and unable to do much troubleshooting right now. I recommend asking on Stackoverflow, but also providing a reproduction in StackBlitz
