### ISSUE TITLE
[Testing]: Mat checkbox doesn't change its state on click

### ISSUE THREAD

**Issue by prabh-62** [angular/components#18129]
#### What are you trying to do?

Unit testing angular application which includes angular material components. Specifically, material components are not behaving the same way in karma-chrome browser as they do in actual chrome browser.

#### What troubleshooting steps have you tried?
Listed below in Reproduction section.

#### Reproduction

Steps to reproduce:
1. `npx @angular/cli new small-app`: Create new angular app and select default prompts
2. `cd small-app` 
3. `yarn ng add @angular/material` (say, yes to all prompts)
4. Edit `src/app/app.component.html`
```html
<mat-checkbox>Check me!</mat-checkbox>
```
5. Edit `src/app/app.module.ts` & `src/app/app.component.spec.ts`
```typescript
import { MatCheckboxModule } from '@angular/material/checkbox';

imports: [
  ...
  MatCheckboxModule
]
```
6. `yarn start`. Clicking on checkbox changes the state of checkbox.
![yarn_start](https://user-images.githubusercontent.com/13006107/71945014-93eda500-3193-11ea-96e4-cf4d88443ea8.gif)

7. `yarn test`. Clicking on checkbox does nothing.
![yarn_test](https://user-images.githubusercontent.com/13006107/71945094-cdbeab80-3193-11ea-97bd-d4260b3e7ad4.gif)

8. Edit `angular.json` and remove material theme from `test`
![remove_theme](https://user-images.githubusercontent.com/13006107/71945211-36a62380-3194-11ea-9c5e-b51d89ccdb33.gif)

9. `yarn test` again. This time checkbox changes its state on click.
![yarn_test_no_theme](https://user-images.githubusercontent.com/13006107/71945241-4cb3e400-3194-11ea-91f6-c3da33670ca8.gif)

The same behaviour can be reproduced in other input components like [**Select**](https://material.angular.io/components/select/overview). With Material Select component, no options appear on click in test mode.

What am I missing here? What can I do so I don't have to remove material **theme** to have consistent experience between karma launched chrome browser and normal chrome mode?

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome 79
- Operating System (e.g. Windows, macOS, Ubuntu):  Mac OS Catalina

**Comment by crisbeto** [comment]
What element are you trying to click? You need to click either the `label` or the `input` inside the `mat-checkbox`.

**Comment by prabh-62** [comment]
I tried clicking both on the label as well as the input. (Point 7 above)

**Comment by crisbeto** [comment]
We've got a bunch of tests that do this and they're all passing. See https://github.com/angular/components/blob/master/src/material/checkbox/checkbox.spec.ts#L186.

**Comment by prabh-62** [comment]
If I check devtools, the `checked` state of checkbox does toggle. it just doesn't reflect in the UI.


![checbox_vs_devtools](https://user-images.githubusercontent.com/13006107/71989192-33944d00-31ff-11ea-8314-94c897410479.gif)

**Comment by oauthentik** [comment]
Actually i ran on a similar problem but related to the SelectionModel used in datatables. 
can someone links up some working snippet for selection model testing ? i'm using Ang7

**Comment by bAmrish** [comment]
I am also running into a similar issue. I am trying to run a test which clicks `mat-checkbox` but the underlying `click` event is not triggered. I do see the hidden `input` element's `checked` status is update. 

Any idea on how to fix this?

**Comment by bAmrish** [comment]
So I was able to get around this using component harness for testing. 

There is a sample code I used in my test. Hopefully it will be useful for anyone facing similar problem.



```
describe('StudyDataFilterComponent', () => {

  let fixture: ComponentFixture<MyComponent>;
  let rootLoader: HarnessLoader;

  beforeEach(() => {
    TestBed.configureTestingModule({
    declarations: [MyComponent]
  });

  fixture = TestBed.createComponent(MyComponent);
  rootLoader = TestbedHarnessEnvironment.documentRootLoader(fixture);
  fixture.detectChanges();
  
  it('should do something', fakeAsync(async () => {
 
    const menu = await rootLoader.getHarness(MatMenuHarness);
    await menu.open();

    const myCheckox = await rootLoader.getHarness(MatCheckboxHarness.with({selector: '#my-checkbox'}));
    await studyCheckbox.check();
  }));
});

```

Of course you can find a guide on this here: https://material.angular.io/guide/using-component-harnesses

**Comment by devversion** [comment]
I think this is because the test completed and the component is just left in the DOM without the actual checkbox component being instantiated anymore. Hence it doesn't update the classes/styles properly.

If the test is running, and you add a timeout to keep it alive, you'll be able to toggle it as expected.

**Comment by devversion** [comment]
Looked slightly more into it. Angular cleans up jasmine tests by default in `beforeEach` (not in `afterEach` 😄). That leaves the last test component in the DOM (also helps with focused tests and debugging). In tests, ZoneJS change detection is not used, so the component does actually not refresh.
