### ISSUE TITLE
Helper classes 

### ISSUE THREAD

**Issue by anuj9196** [angular/components#18120]
#### What are you trying to do?

Coming from `bootstrap` (ngb-bootstrap) background. I am trying to center align contents like center align spinner in a card.

#### What troubleshooting steps have you tried?

Couldn't find any predefined way (or class) to align the contents. In the bootstrap, it is possible by using `text-center|left|right` or `float-left|right|` etc classes.

After googling for the issue, the only solution received is to write own CSS for aligning content.

There should also be classes to define margin, padding, etc.

A question for the same has been posted on Stackoverflow: https://stackoverflow.com/q/59612489/3719167
  
#### Environment

- Angular: 8.2.6
- CDK/Material: 8.2.3
- Browser(s): Any
- Operating System: macOS

**Comment by EmixamZ** [comment]
Hi Anuj, 
Not sure if that's the recommended way to solve this but I'm using Angular Flex-Layout : 

https://github.com/angular/flex-layout
Demo : https://tburleson-layouts-demos.firebaseapp.com/#/docs

It's quite similar to Bootstrap system 

Hope it will help.
