### ISSUE TITLE
form-field(outline): floating label overlaps outline in MS Edge

### ISSUE THREAD

**Issue by graphical-iain** [angular/components#18127]
#### Reproduction

Steps to reproduce:
1. Open https://material.angular.io/components/form-field/overview#form-field-appearance-variants in Microsoft Edge
2. Click into the Outline form field example.
 
 
#### Expected Behavior
The outline should not be visible underneath the label, as in other browsers.
![image](https://user-images.githubusercontent.com/6206408/71935561-1c108200-3175-11ea-9d6d-c0c6182c94c2.png)

#### Actual Behavior
The outline overlaps with the label text.
![image](https://user-images.githubusercontent.com/6206408/71935539-0ac77580-3175-11ea-93d8-c44a298c72ec.png)

#### Environment
- CDK/Material: 8.2.3
- Browser(s): Edge
- Operating System: Windows 10

**Comment by Splaktar** [comment]
What version of Edge is this an issue with?

**Comment by stockcj** [comment]
This issue exists on Edge version 42.17134, but not on any post Chromium (80+) versions I've tested.

**Comment by stockcj** [comment]
It looks like the width property of .mat-form-field-outline-gap isn't being set. This is being done in line 590 of form-field.ts:

```
    for (let i = 0; i < gapEls.length; i++) {
      gapEls[i].style.width = `${gapWidth}px`;
    }
```
I'm guessing it's either an issue with that, or with calculating the width before it's applied.

I'm going to have to set these manually for each form field to work round this.

**Comment by andrewseguin** [comment]
Closing since this issue does not occur in Chromium-based Edge. We no longer support older versions
