### ISSUE TITLE
v9 Tooltip has no background color

### ISSUE THREAD

**Issue by anton-white** [angular/components#18139]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip should have a background color.

#### What is the current behavior?
Tooltip has no background color and is not visible, i.e. is transparent.

#### What are the steps to reproduce?
Use original mat-tooltip from v9

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 9.0.0-rc.8
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        8.3.14
@angular/cdk                      9.0.0-rc.7
@angular/material                 9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               8.3.14
@schematics/update                0.900.0-rc.8
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

#### Is there anything else we should know?
Looks like the following style is missing from v8:
```
.mat-tooltip {
  background: rgba(97,97,97,.9);
}
```

**Comment by crisbeto** [comment]
Are you sure that you have included a theme? It's hard to tell based on the provided information.

**Comment by anton-white** [comment]
Thanks for the direction. Yes, we have a theme included and we are extending it.

`$mat-light-theme-background` received a new entry in v9: `tooltip: map_get($mat-grey, 700)`
So in our theme the `tooltip` key was missing.

To avoid further possible issues I've used `map_merge` instead of direct reassigning of `$mat-light-theme-background`.
