### ISSUE TITLE
NativeDatepicker with MAT_DATE_LOCALE and en-GB swaps day/month continuously

### ISSUE THREAD

**Issue by intellix** [angular/components#18132]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-a5a7jk?file=src%2Fapp%2Fdatepicker-overview-example.html

Steps to reproduce:
1. Add `{ provide: MAT_DATE_LOCALE, useValue: 'en-GB' },`
2. Focus field and type: "01/12/1988" and blur field
3. Focus field and press: "backspace" and "8" and blur field

The same thing happens with locales like "de-DE"
 
#### Expected Behavior

What behavior were you expecting to see?
You should see "01/12/1988" as you blur the field. When you edit that field with the same value, it should stay as "01/12/1988"

#### Actual Behavior

What behavior did you actually see?
"01/12/1988" becomes "12/01/1988" and editing it again changes it back and forth to "01/12/1988"

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): OSX Chrome
- OS Locale: United Kingdom
- navigator.language: "en"

#### Temporary workaround
Just set the locale to something like "en".

Potentially related: https://github.com/angular/components/issues/7823 and https://github.com/angular/components/issues/7143

After a little bit of debugging I see that: new Date("12/01/1988") is regarded as 1st December (en-US) as opposed to 12th January (en-GB) and then it's formatted using en-GB (opposite)

<img width="1680" alt="Screenshot 2020-01-08 at 17 16 01" src="https://user-images.githubusercontent.com/1162531/72000285-dddd9600-323a-11ea-8abd-b057916c3cbc.png">
<img width="1458" alt="Screenshot 2020-01-08 at 17 01 31" src="https://user-images.githubusercontent.com/1162531/72000287-de762c80-323a-11ea-9088-a102ad23339d.png">

**Comment by crisbeto** [comment]
As you mentioned, by default the datepicker just passes the value straight into the `Date` constructor and relies on the browser to do the parsing. If you want more control over how it's done, you can provide your own date adapter or use the provided Moment.js one.

**Comment by mmalerba** [comment]
This is a limitation of the native `Date` object in JavaScript. 
Currently I recommend using the `MomentDateAdapter` or another custom date adapter rather than the standard `NativeDateAdapter` (see https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings)

We should however, try to make a better experience for the `NativeDateAdapter`.
This issue is being tracked by https://github.com/angular/components/issues/8100
