### ISSUE TITLE
Add documentation for MatBottomSheetRef.dismiss

### ISSUE THREAD

**Issue by cwilby** [angular/components#18136]
#### Documentation Feedback

The page explains how to pass data into the sheet via `MatBottomSheet.open`, but doesn't mention you can also pass data back to the calling component via [`MatBottomSheetRef.dismiss`](https://github.com/angular/components/blob/a744dc31e9045df589cd2c93c14553f0fa62f0bb/src/material/bottom-sheet/bottom-sheet-ref.ts#L92).

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/components/bottom-sheet/overview

**Comment by spdi** [comment]
It is documented in Api tab.
https://material.angular.io/components/bottom-sheet/api#MatBottomSheetRef


dismiss
--
Dismisses the bottom sheet.

result?R | Data to be passed back to the bottom sheet opener.

**Comment by crisbeto** [comment]
Closing since the API docs mention that the parameter. That being said, we should probably allow data to be passed through `MatBottomSheet.dismiss` as well.
