### ISSUE TITLE
when i trigger material tabs switch,page back to top.

### ISSUE THREAD

**Issue by 513205785Xie** [angular/components#18146]
#### Reproduction

https://components-issue-wwbr1b.stackblitz.io

Steps to reproduce:
1. Make sure your browser's viewable area is greater than 650px
2. Swipe to the bottom of the page
3. Switch tab pages
 
 
#### Expected Behavior

Page stays at the bottom

#### Actual Behavior

Page jumps to the top

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.0
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): window7,  window10

**Comment by jelbourn** [comment]
This is working as expected- when the tabs change, one is removed from the DOM and the other added. If the tab body is the only thing affecting the page height, the browser will naturally move back to a higher location. You could address this by introducing a min-height for the content area.
