### ISSUE TITLE
mat-select is scrolling up when selecting

### ISSUE THREAD

**Issue by MadyAkira** [angular/components#18154]
#### Reproduction
![ezgif-3-99fed5f7556f](https://user-images.githubusercontent.com/42877823/72199088-377fd380-347a-11ea-8283-ccf2c6a4aff1.gif)
[StackBlitz issue](https://stackblitz.com/edit/angular-vs8nco-jxmg2o)

Steps to reproduce:
1. Change the height of mat-option to unset;
2. Scroll down and select a value
 
 
#### Expected Behavior
The mat-select component shouldn't be scrolling up when selecting a value.

#### Actual Behavior
The component scroll up when selecting a value.

#### Environment

- Angular : 8.1.3
- CDK/Material: Angular Material design
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS Mojave 10.14

**Comment by crisbeto** [comment]
The select expects options to be of a certain height and we currently don't support overriding it so you're doing it at your own risk.
