### ISSUE TITLE
a disabled mat-expansion-panel cannot be expanded programmatically

### ISSUE THREAD

**Issue by adamdport** [angular/components#18171]
#### Reproduction

https://stackblitz.com/edit/angular-qz4usp?file=src/app/expansion-steps-example.html

Steps to reproduce:
1. in example, first panel is disabled and the second is not
2. the first button will call "open" on the first panel, and the second, the second.
3. notice that the first button doesn't work, but the second does
 
 
#### Expected Behavior

By calling "open" programmatically (via button click), I expect the disabled panel to open, as per [the docs](https://material.angular.io/components/expansion/overview#disabling-a-panel)

> Expansion panels can be disabled using the disabled attribute. A disabled expansion panel can't be toggled by the user, but **can still be manipulated programmatically**.

#### Actual Behavior

The disabled (first) panel won't open programmatically

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): chrome 79
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by tomicarsk6** [comment]
You can see in this stackblitz example how you can achieve this, it's basically your example but with functionality to open or close expansion panel programatically:
https://stackblitz.com/edit/angular-qz4usp-rkdmag?file=src%2Fapp%2Fexpansion-steps-example.html
