### ISSUE TITLE
AutofillMonitor does not work in Firefox & IE 11

### ISSUE THREAD

**Issue by juliandavidmr** [angular/components#18174]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/rekpyvoxyqp?file=src%2Fapp%2Ftext-field-autofill-directive-example.html

Steps to reproduce:
1. Have the fields suggest information.
2. Select an item suggested by the web browser.
3. Chrome shows the label: `Autofilled!`, but **Firefox does not**.
 
#### Expected Behavior

What behavior were you expecting to see?

That the CDK autofill recognizes when the field is filled from the suggestions. In this case, show the label: `Autofilled!`

#### Actual Behavior

What behavior did you actually see?

An old bug: https://bugzilla.mozilla.org/show_bug.cgi?id=950510

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): 72.0.1 (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10.

**Comment by mmalerba** [comment]
This was a bug in firefox that appears to have been fixed now - test in 107.0.1 (64-bit)
