### ISSUE TITLE
Option to position *cdkDragPreview under the cursor

### ISSUE THREAD

**Issue by JohnKis** [angular/components#18176]
#### Feature Description
When using custom preview templates with *cdkDragPreview, the preview is always positioned next to the cursor. This behaviour is different to using the default preview where the preview is positioned relative the pickup location.

I had a look in the code and removing the if shorthand at [https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-ref.ts#L753](https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-ref.ts#L753) solves this. Checking the `_getPointerPositionInElement` method I couldn't find any reason why it wouldn't work with custom preview templates.

#### Use Case
This would be improve UX when using a custom preview template that has similar dimensions to the root element.

**Comment by crisbeto** [comment]
The reason why it was made this way is because we can't know ahead of time the size of the custom preview until it's actually in the DOM.

**Comment by JohnKis** [comment]
@crisbeto - Fair enough. I guess it makes more sense in cases where the preview size is known to be the same as the draggable element's. I opened a related feature request: #18177. 

It could be an option that's disabled by default.

**Comment by crisbeto** [comment]
Closing since it should be handled by https://github.com/angular/components/issues/18177.
