### ISSUE TITLE
maxlength is not working in Android devices matChipInput. 

### ISSUE THREAD

**Issue by brijeshIOGit** [angular/components#18185]
```
<mat-form-field appearance="outline">
            <input
              matInput
              type="text"
              placeholder="Enter expertise here..."
              [matChipInputFor]="expertise"
              [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
              (matChipInputTokenEnd)="add($event)"
              minlength="3"
              maxlength="20"
            />
            <mat-hint>Please write and press "ENTER" to add Expertise</mat-hint>
          </mat-form-field>

```
Steps to reproduce:
1. Add input for matChipInput. 
2. Write rule for maxlength as maxlength="20" on input field.
3. try this input in android phone.
4. You can enter more than 20 characters unless you have set maxlength 20.
 
 
#### Expected Behavior

User should not enter more than 20 characters in matchipinout?

#### Actual Behavior

user can enter more than 20 characters.?

#### Environment

- Angular:^8.1.1
- CDK/Material:^8.0.2
- Browser(s): chrome
- Operating System (Android):

**Comment by crisbeto** [comment]
`maxlength` is a native attribute, not something that comes from Material. Closing since this isn't something the Material chips are responsible for.
