### ISSUE TITLE
overrideProvider not working for MAT_DATA_DIALOG

### ISSUE THREAD

**Issue by super-it-guy** [angular/components#18204]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. When trying to reassign useValue in unit test from after it was assigned in the poviders array:
 providers: [
        {
          provide: MAT_DIALOG_DATA,
          useValue: dataDialogSrv
        }
by using TestBed.overrideProvider(MAT_DIALOG_DATA, {useValue: dataDialogSrv2}) in the individual 'it' statement, it is not working to change the value. This is true even when .compileComponents() is not run after the providers. 
2. in unit test:

beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
       MyModule
      ],
      declarations: [
      MyComponent
      ],
      providers: [
        provideMockStore({ initialState }),

        {
          provide: MAT_DIALOG_DATA,
          useValue: {name: 'test1'}
        }
      ]
    });
it('should change value of MAT_DIALOG_DATA ', () => {
 TestBed.overrideProvider(MAT_DIALOG_DATA, {useValue : {name: "test2"}});
TestBed.compileComponents();
fixture.detectChanges();

component.ngOnInit();
     fixture.detectChanges();
    expect(component.data).toEqual({
       name: 'test2',
});

});
 
 
#### Expected Behavior

What behavior were you expecting to see?
test should pass

#### Actual Behavior

What behavior did you actually see?
test is failing because name value is still 'test1'

#### Environment
Angular, Material, karma, jasmine, Windows
- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by devversion** [comment]
Hello! I cannot reproduce your issue: https://stackblitz.com/edit/comp-18204?file=app/app.component.spec.ts.

Please make sure that you do not call `compileComponents` before overriding the provider. I notice that you do it correclty in your shared code, but it might be different for your app.
