### ISSUE TITLE
Upgrade to iOS 13 causing problems with events

### ISSUE THREAD

**Issue by iblatnick** [angular/components#18209]
After updating to iOS 13.x my Angular Apps Swipe gesture is no longer working properly to show side menu items. After updating it fails to to lock the cdk-virtual-scroll-viewport leading to undesired behavior. I am using hammerjs to lock the list from scrolling when swiping. The events seem to be interrupting each other, did something change in iOS or this plugin as the translateX we are doing on horizontal gestures is being cancelled by scrolling instead of being locked.

Versions in use:

- Angular 8.1.1
- hammerjs 2.0.8
- @angular/cdk/scrolling 8.2.3

**Comment by michaelurban** [comment]
HammerJS has been dropped as a dependency in v9 (https://github.com/angular/components/blob/master/guides/v9-hammerjs-migration.md).

The latest version of HammerJS (v2.0.8) was released in early 2016 and I've seen several issues when using it with recent browser releases. I don't believe that it is being actively maintained. The Angular Material docs need to be updated to warn off future users.

**Comment by jelbourn** [comment]
Closing since this sounds like an issue with HammerJS rather than Angular Material specifically. As @michaelurban mentioned, we are dropping HammerJS as a dependency in v9; going forward, the components will be agnostic to gesture handling.
