### ISSUE TITLE
generate Theme on Demand like material 1

### ISSUE THREAD

**Issue by akvaliya** [angular/components#18219]
#### Feature Description

In angular material 1 it is possible to generate/swap themes dynamically with option [generateThemesOnDemand](https://material.angularjs.org/latest/Theming/04_multiple_themes)

#### Use Case

I have a requirement to use color pallet based on domain. And site has one copy deployed with multiple domains.

In angular material 1 with `generateThemesOnDemand `this can be done easily

#### What is the current behavior?
Only static theming is possible, where you have to generate your css files from sass in advance.

#### What is the use-case or motivation for changing an existing behavior?
Multi-tenant systems with single hosting.

**Comment by jelbourn** [comment]
We have no plans to support this; AngularJS Material's run-time theming system often led to multi-second delays in loading the page due to generating massive amounts of CSS.
