### ISSUE TITLE
Error: Missing definitions for header, footer, and row

### ISSUE THREAD

**Issue by Ahouelete** [angular/components#18217]
when use ng-zorro-antd and material simultaneously, got some error like: Error: Missing definitions for header, footer, and row; cannot determine which columns should be rendered.

Enviroment:
angular 7.0.2
material 7.0.2
ng-zorro-antd 1.8.0

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
