### ISSUE TITLE
Datepicker Component Does Not Honor `updateOn` Configuration When No Year Is Present

### ISSUE THREAD

**Issue by zakmac** [angular/components#18229]
#### Reproduction

https://stackblitz.com/edit/angular-dxyamu?file=src/app/datepicker-start-view-example.ts
Original, misfiled ticket with information that does not fit this project's template: https://github.com/angular/angular/issues/34873

Steps to reproduce:
1. Create a datepicker input and link to a `FormControl` with `updateOn: 'blur'`
2. Delete characters starting at the rightmost and remove the year

Note how `valueChanges` will not fire while deleting the year, but will fire for every keypress subsequent to deleting the year. This behavior gets less predictable when not simply deleting the year; for example, starting to delete at the first digit of the year and continuing past the slash and into the digits representing month.
 
 
#### Expected Behavior

`valueChanges` does not fire until the input field is `blur`ed

#### Actual Behavior

`valueChanges` updates on every keypress when no year is present.

![matdatepicker valuechanges](https://user-images.githubusercontent.com/2379809/72751713-32570e80-3b75-11ea-8da6-23335e2bd15e.gif)

#### Environment

The issue may be caused by package **@angular/forms**
Present in Angular ~7 in our organization's application, as well as in the linked StackBlitz running Angular ~8.

**Comment by crisbeto** [comment]
This looks like it could be the same issue as https://github.com/angular/components/issues/16461 which has a fix in 9.0.0-rc.7.

**Comment by zakmac** [comment]
> This looks like it could be the same issue as #16461 which has a fix in 9.0.0-rc.7.

Yes this looks to be the same issue. I will close this ticket and re-file post-9.0 if the behavior persists.
