### ISSUE TITLE
 _changePageSize don't appears on the documentation of Paginator component

### ISSUE THREAD

**Issue by dluque92** [angular/components#18220]
#### Bug, feature request, or proposal:

 _changePageSize(pageSize: number): void don't appears on the documentation of the api
https://material.angular.io/components/paginator/api

https://github.com/angular/components/blob/master/src/material/paginator/paginator.ts

#### What is the expected behavior?
https://github.com/angular/components/blob/master/src/material/paginator/paginator.ts

Have it present here https://material.angular.io/components/paginator/api

#### What is the current behavior?
Is not present https://material.angular.io/components/paginator/api

#### What are the steps to reproduce?
Open https://material.angular.io/components/paginator/api

#### What is the use-case or motivation for changing an existing behavior?
Use the current documentation to know which methods are available to use

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by crisbeto** [comment]
Properties and methods that start with an underscore are private and won't show up in the public API docs. They're exposed as public members so that they can be used in the component's view.

**Comment by dluque92** [comment]
Maybe then should be a private method

**Comment by crisbeto** [comment]
As I said above, they need to be marked as public members so that they can be used in the component's view.

**Comment by dluque92** [comment]
Maybe then, as I said above, if we need to use it in the component's view, as public method as it is, maybe should be also in the API documentation, because anyway is public and you can use it, doesn't matter if you set underscore before or not
