### ISSUE TITLE
Css variable error in cdk components.

### ISSUE THREAD

**Issue by skbelalmd** [angular/components#18228]
The checkbox color in the dropdown doesn't change as per the style set using ng-deep where as the style set to simple mat-checkbox changes the color as per css variable. Check below link.

https://stackblitz.com/edit/angular-wnqcek?file=src%2Fapp%2Fselect-multiple-example.css

**Comment by crisbeto** [comment]
I'm not sue what you're referring to since the checkbox is black in the example that you posted.

**Comment by skbelalmd** [comment]
In the example, I can override the colors of check box (only for checked) using css variable in ::ng-deep style i.e black.

But the checkbox color in mat-select is not getting changed to the defined variable. That's why the color is transparent when you choose any option.

**Comment by crisbeto** [comment]
It's probably because we use a different lightweight checkbox for `mat-select` which is called `mat-pseudo-checkbox`.

**Comment by jelbourn** [comment]
Closing since it's not clear there's any issue here. Please open a new issue with the issue template if you believe there is a legitimate bug to report.
