### ISSUE TITLE
Issue with Right Panel on Angular Material

### ISSUE THREAD

**Issue by abhinav-goyall** [angular/components#18235]
#### Documentation Feedback

While going through documentation i found out the color for Install Angular Material and Display a Component changes as i scroll down but not happening for the Appendix. Even after clicking appendix it goes to the appendix section but didn't highlight the appendix int eh contents panel.
It doesn't seems very consistent behavior. It should be consistent with the other items.

Feel free to provide any suggestions of content or examples you’d like us to include.

Link: https://material.angular.io/guide/getting-started
![getting_started_error1](https://user-images.githubusercontent.com/47552229/72783455-7d902080-3c4c-11ea-9a40-d684061ce90a.PNG)

**Comment by abhinav-goyall** [comment]
Hi,
Greetings!
Could you please check on this documentation feedback.
Thanks

**Comment by abhinav-goyall** [comment]
Any updates on the above feedback?

**Comment by jelbourn** [comment]
This happens when the last section is short enough that the table-of-contents still sees an earlier section at the "active" section. It's minor enough that I don't think we'll address for the foreseeable future.
