### ISSUE TITLE
Inconsistency in Contents Panel in theming page

### ISSUE THREAD

**Issue by abhinav-goyall** [angular/components#18236]
#### Documentation Feedback

Theming your own components is not behaving as other items in the Contents panel. Even clocking on it is higlightinng the previous item in that item list.

Link: https://material.angular.io/guide/theming
![theming_error](https://user-images.githubusercontent.com/47552229/72784749-7dddeb00-3c4f-11ea-9de0-8ca71596d369.PNG)

**Comment by abhinav-goyall** [comment]
Hi,
Greetings!
Could you please check on this inconsistency in documentation.

Thanks

**Comment by abhinav-goyall** [comment]
Any updates on the above issue?

**Comment by abhinav-goyall** [comment]
any updates?

**Comment by walvekarnikhil** [comment]
This is happening since we didn't scroll past the anchor point. The link is not marked as "active".

https://github.com/angular/material.angular.io/blob/master/src/app/shared/table-of-contents/table-of-contents.ts#L142
```
  private isLinkActive(currentLink: any, nextLink: any): boolean {
    // A link is considered active if the page is scrolled passed the anchor without also
    // being scrolled passed the next link
    const scrollOffset = this.getScrollOffset();
    return scrollOffset >= currentLink.top && !(nextLink && nextLink.top < scrollOffset);
  }
```

**Comment by jelbourn** [comment]
This appears to be fixed in the latest version of the site
