### ISSUE TITLE
Angular <mat-select> not working with nebular components

### ISSUE THREAD

**Issue by hanaravind** [angular/components#18249]
I am trying to implement `mat-select` (angular material UI) along with the nebular components
but `mat-select` is not working when same component/module has nebular imports . if i remove imports of nebular module mat-select works .

with using nebular version `4.1.1` and version of angular material `8.2.3`

Here is my stackblitz workaround that you can clearly see that `mat-select dropdown` is not working.
https://stackblitz.com/edit/github-ngmzqm?file=src%2Fapp%2Fhome%2Fhome.component.html

**Comment by crisbeto** [comment]
There are a couple of console warnings about the Material structural styles not being included and the CDK version not matching. Have you tried resolving them?

**Comment by hanaravind** [comment]
@crisbeto  Those are minor warnings  that i have cleared now and after resolving also its not working
