### ISSUE TITLE
[mat-chip-list] Change event doesn't provide reliable results and breaks when multiple property is changed

### ISSUE THREAD

**Issue by myieye** [angular/components#18245]
#### Reproduction

StackBlitz to reproduce issue(s): https://stackblitz.com/edit/angular-14snje

Steps to reproduce:
1. Click "One Fish"
2. Change event says that "One Fish" is the only selected chip even though 2 other tags are also selected
3. Click "toggle multiple" to disable multiple selection
4. Click "Two Fish"
5. "One Fish" and "Two fish" are shown to be selected, but the change event says only "One Fish" is selected
6. Click "One Fish"
7. Now the change event says that only "Two Fish" is selected
8. Remove HTML attribute "multiple" from mat-chip-list in code and restart app
9. Click "One Fish"
10. Only "One Fish" is selected
11. Click "toggle multiple" to enable multiple selection
12. Click "Two Fish"
13. Both "One Fish" and "Two Fish" are shown to be selected, but the change event says that only "Two Fish" is selected
 
#### Expected Behavior

The change event triggered by mat-chip-list should always match the chips that are visually marked as selected.
When the multiple property is changed to false, only the first selected chip should remain selected.

#### Actual Behavior

1. The list doesn't include pre-selected chips in the first change event (i.e. chips that are selected at their creation time)
2. If multiple is initially false and then later changed to true, the change-event values array never contains more than 1 value even though multiple tags can be visually marked as being selected

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
That's because the event is referring to the value changed by the user.

**Comment by myieye** [comment]
That may be part of it, but I can't imagine how that explains my "Actual behaviour" point 2. Nor does it explain how multiple chips can be selected when multiple is changed to false.

I'm guessing that changing the value of `multiple` just isn't supported.
