### ISSUE TITLE
mat-datepicker select "in" and "out" type for two-way binding (e.g. ISO date string)

### ISSUE THREAD

**Issue by smnbbrv** [angular/components#18253]
#### Feature Description

Please provide a way to deal with ISO date strings in two-way binding (e.g. `ngModel`).

Probably it does not end with the ISO date string as a possible type. Let's say another example is to use `google.protobuf.Timestamp` from protobuf as input and output for the model.

It might be that I'm repeating another issue here, however I did not succeed finding one.

#### Use Case

I want to pass string as input for datepicker and receive string as output. That's normally a quite expected behavior from a form input and it is definitely not in place; a `Moment` instance is replacing my input, although it was of type `string` (I use moment date adapter)

Currently I need to perform ugly patching like `(ngModelChange)="contact.birthDate = $event.toISOString()"`

```html
<mat-form-field>
    <mat-label>{{ 'entity:ContactPerson/property:birthDate/name' | translate }}</mat-label>
    <input matInput [matDatepicker]="picker" #birthDateModel="ngModel" [(ngModel)]="contact.birthDate" name="contact.birthDate" (ngModelChange)="contact.birthDate = $event.toISOString()">
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker #picker></mat-datepicker>
  </mat-form-field>
```

[Another example on SO](https://stackoverflow.com/questions/55657747/how-to-two-way-bind-angular-material-datepicker-to-a-string-property)

If there is another cleaner way to achieve the string in -> string out (or any custom type) behavior, please guide me.

**Comment by manklu** [comment]
@smnbbrv You can write your own date adapter.

**Comment by crisbeto** [comment]
As mentioned above, this can be handled in a custom date adapter.
