### ISSUE TITLE
Entry point configuration check should run against release package

### ISSUE THREAD

**Issue by devversion** [angular/components#18250]
The entry-point configuration CI check should run against the release package, and not run simply against the `config.bzl` file. The reason for this is that we don't need to generate manifests and pass data through `.bzl` files to the JS script. 

Also configuring does not always mean that the entry point is actually released. We could incorporate this into the release validation scripts that already run on CI anyway.

**Comment by mmalerba** [comment]
Closing since we're unlikely to have time to work on this and our current process has never had issues with forgetting to release an entry point. This is something we can reconsider in the future if the need arises.
