### ISSUE TITLE
Stackblitz does not run

### ISSUE THREAD

**Issue by bp-brainiak** [angular/components#18256]
#### Bug, feature request, or proposal:

trinying to run examples and stacklblitz does not run
#### What is the expected behavior?
see the code on stackblitz

#### What is the current behavior?
stackblitz shows 

"Internal Server Error"
![Anotación 2020-01-22 144804](https://user-images.githubusercontent.com/2272009/72919437-3d04d580-3d26-11ea-9273-185fa73e825a.jpg)

#### What are the steps to reproduce?

I click the "Edit in stackblitz" button

#### Is there anything else we should know?
![Anotación 2020-01-22 144804](https://user-images.githubusercontent.com/2272009/72919472-4c841e80-3d26-11ea-94ea-a3c02f1c2077.jpg)

**Comment by crisbeto** [comment]
Sounds similar to https://github.com/angular/components/issues/18255. It might be worth waiting a bit and trying again.

**Comment by amayer42** [comment]
This has been happening to me for a while as well.  A co-worker showed me that they are being redirected to the proper stackblitz link when they click on the link from Material.  I get the same "Internal Server Error" message as you though @bp-brainiak .  I use FF as my primary browser and cannot get it to work, but I loaded up Chrome, cleared cache, and was able to get the links to work for me.  Seems odd that clearing cache would clear up a 500 error though...

**Comment by jelbourn** [comment]
I just tried and it works for me. I suspect this might be a transient error on StackBlitz's side.

**Comment by bhalicki** [comment]
Looks like this is still an issue.

Occurs when trying to access examples for Tree and Table.  Haven't tried other examples.

https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Ftree-flat-overview-example.ts
https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Ftable-basic-example.ts

Clearing cache did not resolve the issue.
