### ISSUE TITLE
mat-sidenav-content margin-left is not correct

### ISSUE THREAD

**Issue by olcayusta** [angular/components#18268]
#### Reproduction

Steps to reproduce:
1. Open Firefox
2.  https://sidenav-bug-72mryglch.now.sh/  (Normal Sidenav)
3.  https://sidenav-bug-6601swo2z.now.sh/ (Autosize Sidenav)
 
#### Expected Behavior

The margin-left value should not be miscalculated

#### Actual Behavior

The problem seems a bit strange, it works fine in development mode, but I encounter this problem in the production environment.

In the dev environment, I think the error is not appearing because the files are large in size.

This problem is clearly evident now with firefox.
It is sometimes seen in Chrome and Edge browsers.

Normal
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52415595/73015811-c9e68680-3e2d-11ea-8746-3d9e76db51f2.gif)
(First load is not correct, if resize is correct)

Autosize
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/52415595/73015824-cfdc6780-3e2d-11ea-97fc-114418d9446b.gif)
(First load is correct but with bug)

#### Environment

- Angular: 9.0.0-rc.10
- CDK/Material: 9.0.0-rc.8
- Browser(s): Firefox 72
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by ilyaryabchinski** [comment]
I got the same issue on my project. Seems like the only workaround now is to calculate this margin-left value yourself and set !important rule using Renderer2 or style-bindings.

**Comment by jelbourn** [comment]
I just tested this in Firefox and don't see any issues. I tried turning on network throttling as well to see if the issue only occurred while the images were loading, but it worked fine either way. Can you elaborate on what you're seeing? I can't quite make it out from the images you posted.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
