### ISSUE TITLE
Bug in autoComplete

### ISSUE THREAD

**Issue by rezarozbahani** [angular/components#18286]
#### What is the expected behavior?
[viewValue]="option.Name" [value]="option.Id"

#### What is the current behavior?
[viewValue]="option.Name" [value]="option.Name"

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
    <mat-form-field class="example-full-width">
      <input type="text" placeholder="Pick one" aria-label="Number" matInput [formControl]="myControl"
        [matAutocomplete]="auto">
      <mat-autocomplete #auto="matAutocomplete" (optionSelected)="optionSelected($event)">
        <mat-option *ngFor="let option of diseasesObservable | async" [viewValue]="option.Name" [value]="option.Id">
          {{option.Name}}
        </mat-option>
      </mat-autocomplete>
    </mat-form-field>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
lateast 

#### Is there anything else we should know?
I expect [viewValue]="option.Name" filled in TextBox and  [Value]="option.Id" doesn't Fill in TextBox  
and in optionSelected($event) have ViewValue (Title for example) and have Value (1 for example ) 
Notice : [Value]="option.Id" bind to TextBox in html 
Thanks

**Comment by crisbeto** [comment]
I'm not sure I follow what the issue is here. Also `mat-option` doesn't have a `viewValue` input.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
