### ISSUE TITLE
On mobile devices cdkDrag hasn't got autoscroll

### ISSUE THREAD

**Issue by afferenslucem** [angular/components#18297]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Tap to target element.
2. Move it to bottom border of container.
 
 
#### Expected Behavior

Container should be slowly scrolling

#### Actual Behavior

Conteiner not responds for item moved to the bottom

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by crisbeto** [comment]
It's hard to tell what's going on without seeing what your setup is. Auto scrolling works for me against the examples on material.angular.io.

**Comment by crisbeto** [comment]
Closing since there hasn't been any activity in a while.
