### ISSUE TITLE
cdkDropList get "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted." by fast scroll

### ISSUE THREAD

**Issue by afferenslucem** [angular/components#18296]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Fast scroll down
2. Fast scroll up
Repeat 3-4 times
 
#### Actual Behavior

What behavior did you actually see?
![image](https://user-images.githubusercontent.com/18226034/73167437-af582a00-4119-11ea-9923-2a42370f5584.png)

#### Environment

- Angular: 8.3.23
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windors

**Comment by crisbeto** [comment]
I couldn't reproduce it based on the provided information.

**Comment by crisbeto** [comment]
Closing since there hasn't been any information on how to reproduce the issue.
