### ISSUE TITLE
mat-icon font causing an overflow

### ISSUE THREAD

**Issue by alexm-aceable** [angular/components#18295]
#### Reproduction

https://stackblitz.com/edit/angular-e2qgob?file=src%2Fapp%2Ficon-overview-example.html

Steps to reproduce:
1. Visit the stackblitz link
2. Notice there is a horizontal scrollbar seemingly caused by nothing

After doing some digging, I've found the root issue to be the text "checkmark" in `<mat-icon>checkmark</mat-icon>` is still taking up space despite text not being rendered.

In this screenshot notice the horizontal scrollbar:

<img width="1440" alt="Screen Shot 2020-01-26 at 6 22 08 PM" src="https://user-images.githubusercontent.com/42749863/73144320-59787900-406a-11ea-96dc-ab0521cebad6.png">

In this screenshot I've disabled the icon font so we can see that the "checkmark" text is taking up space.

<img width="1440" alt="Screen Shot 2020-01-26 at 6 22 29 PM" src="https://user-images.githubusercontent.com/42749863/73144342-8167dc80-406a-11ea-9cef-733bd3be3830.png">

#### Potential Fix

Setting `.material-icons { overflow: hidden }` is a quick and easy fix for this issue.

#### Expected Behavior

Icon font shouldn't take up more space than its set `width: 24px`.

#### Actual Behavior

Icon font is taking up more than the set `width: 24px` of the icon.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.14
- Browser(s): Firefox, Safari, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by manklu** [comment]
Interestingly, it doesn't occur when you use the ligatures from the icon overview page.
e.g. fingerprint or radio_button_checked

**Comment by jelbourn** [comment]
`checkmark` isn't one of the Material Design ligatures- it's just `check`. The extra space is coming from the superfluous `mark`
