### ISSUE TITLE
Stuttering scrollbar (Virtual scrolling) when using el.offsetHeight

### ISSUE THREAD

**Issue by xXKeyleXx** [angular/components#18308]
#### Reproduction

https://stackblitz.com/edit/angular-dz9eqz?file=src%2Fapp%2Fcdk-virtual-scroll-overview-example.ts

Steps to reproduce:
1. Drag the scrollbar up and down with slow/medium speed
2. Watch for stuttering of the scrollbar
3. Remove the `headerBarElement.offsetHeight` line
4. See it working like expected
 
 
#### Expected Behavior
Smooth scrolling like you can see when using the example (https://stackblitz.com/angular/aemdyrjmebn)

#### Actual Behavior
A stuttering scrollbar

#### Environment
- Browser(s): Chrome & Firefox tested
- Operating System: Windows

```
@angular-devkit/architect          0.803.23
@angular-devkit/build-angular      0.803.23
@angular-devkit/build-optimizer    0.803.23
@angular-devkit/build-webpack      0.803.23
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cdk                       8.2.3
@angular/cli                       8.3.23
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.23
@schematics/angular                8.3.23
@schematics/update                 0.803.23
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by crisbeto** [comment]
I'd say that this is working as expected. Reading the `offsetHeight` will cause the browser to re-compute the dimensions of the element. When you combine that with triggering it on each change detection, you end up with [layout thrashing](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing).
