### ISSUE TITLE
Table with paginator, ExpressionChangedAfterItHasBeenChecked when restoring page index

### ISSUE THREAD

**Issue by Wisdomb33r** [angular/components#18311]
#### Reproduction

My case is a quite straightforward search result display with paginator. When I navigate away from the search result route from the first result page and come back to it, everything works fine. When I navigate away from another page (index > 0) and come back to it, an `ExpressionChangedAfterIthasBeenChecked` error is raised.

Reproduction link : https://stackblitz.com/edit/angular-okcqx3

Steps to reproduce:
1. Clic on "item11" or "item22" link, then "back to table". No error is raised
2. Navigate to page 2 or 3 and clic any link ("item33" for instance), then "back to table". Error is raised.

Detailed messages (two different errors are raised) : 

- `Previous value: 'disabled: true'. Current value: 'disabled: false'`
- `Previous value: 'null: undefined'. Current value: 'null: 33'`

I know the conditions which can lead to `ExpressionChangedAfterIthasBeenChecked` but could not identify any here. I could narrow the condition for the second error :

`<a (click)="displayItem(item)" *ngIf="item.id">{{item.name}}</a>`

However, I do not understand why my code would trigger a change during the two detection cycles. I cannot figure out why the `*ngIf` at this line of the template would be interpreted once as undefined, then as 33. The id of the item is always present in this 33 item. The name of the property (`null`) is also quite strange.
 
#### Expected Behavior

No error raised in browser console.

#### Actual Behavior

An `ExpressionChangedAfterIthasBeenChecked` Error is raised.

Note : This behavior is present only during development phase as the check is removed as expected by the `--prod` compilation. I did NOT see any production problem related to it. However, due to a general ErrorHandler in the application (which is catching all the frontend errors for proper display), the `ExpressionChangedAfterIthasBeenChecked` is rather annoying as it triggers this general handler.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Tested on Chrome and Firefox
- Operating System : Win 10

**Comment by tomicarsk6** [comment]
It's not a problem with ```*ngIf``` inside of anchor tag in template, problem lies in this line:
```this.itemsDS.paginator.pageIndex = this.itemsService.currentIndex;```.

**Comment by Wisdomb33r** [comment]
@tomicarsk6 I tried to use the work around solution proposed in your link, and it almost worked... almost because only one of the two errors raised was removed.

https://stackblitz.com/edit/angular-mfruwv

The `Previous value: 'null: undefined'. Current value: 'null: 33'` is now gone, but the other is still present.

**Comment by tomicarsk6** [comment]
Yes I know, I updated your example by simply wrapping everything that you have done in setTimeout function. This is a hack, but there is no other way to do it. You can see what I have done here https://stackblitz.com/edit/angular-bnjvrb?file=src/app/table/table.component.ts

And more about how to debug such an errors and why they are happening, you can read it i this two blog posts:

https://blog.angular-university.io/angular-debugging/
https://indepth.dev/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error/

**Comment by Wisdomb33r** [comment]
@tomicarsk6 Nice, I thank you very much for your help. Hope this gets corrected in material one day...
