### ISSUE TITLE
[Form field] mat-label doesn't not instantly reflected in UI when using ngIf

### ISSUE THREAD

**Issue by aitboudad** [angular/components#18310]
#### Reproduction

https://stackblitz.com/edit/angular-mscc8j
 
 
#### Expected Behavior

should render label when is set

#### Actual Behavior

When the label is set the UI doesn't detect changes until the field catches focus

#### Environment

- Angular: `8.2.14`
- CDK/Material: `8.2.3`
- Browser(s): `Chrome`
- Operating System (e.g. Windows, macOS, Ubuntu): `macOS`

**Comment by devversion** [comment]
Good catch. I can confirm that this is a bug. It looks like we don't detect that label has been projected. Most likely our `ContentChild` query for the label needs to mark the component as dirty.

**Comment by devversion** [comment]
I looked into implementing this. It would be low-effort to add this to the MDC-based form-field, but the standard one will be a bit more complicated due the way it manages the outline notch width.

To me it seems like there is no good use-case to swap out the floating label dynamically. The content of the label can already be swapped out, but it seems like it should be a definite decision whether a form-field has a floating label or not.
