### ISSUE TITLE
Drag and drop - Preview swaping items instead of moving

### ISSUE THREAD

**Issue by andre-f-paggi** [angular/components#18317]
#### What are you trying to do?

Swap items in preview mode instead of moving them.

I got it working on the drop method by using this code
```
 drop(event: CdkDragDrop<string[]>) {
    const temp = this.items[event.currentIndex];
    this.items[event.currentIndex] = this.items[event.previousIndex];
    this.items[event.previousIndex] = temp;
  }
```

But the preview does not work like that, instead it moves the items to the initial dragged item position.

#### What troubleshooting steps have you tried?

I tried disabling sorting, but when I do that, the drop event always set `event.currentIndex` equal to `event.previousIndex`.

#### What are the steps to reproduce?
Stackblitz: [https://stackblitz.com/edit/components-issue-15vjqk](https://stackblitz.com/edit/components-issue-15vjqk)

Move items around.
  
#### Environment

- Angular: 8.1.1
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System): Windows 10 Pro X64

**Comment by andre-f-paggi** [comment]
Maybe if I could lock the initial position and still use the drop method, it would work great

**Comment by andrewseguin** [comment]
Sorry for the delay in providing help with this - we are currently limited on resources for troubleshooting issues. You will probably have better luck getting help if you post on StackOverflow.
