### ISSUE TITLE
Google Maps Polygon & Polyline & Rectangle & Circle

### ISSUE THREAD

**Issue by Yavorss** [angular/components#18322]
As I see, now the GoogleMaps component has only Marker support, but internally Google maps supports Polygon & Polyline & Rectangle & Circle. Are they part of the current round map or it's a low priority for now?

**Comment by crisbeto** [comment]
We have support for polyline in master already and rectangle is currently in a feature branch.

**Comment by Yavorss** [comment]
Is there something that I need to kee

**Comment by Yavorss** [comment]
Are there any problems with Circle implementation and something that we need to keep in mind if we start working on it?

**Comment by crisbeto** [comment]
I don't think there are any problems with it, it's just that nobody's asked for it so we haven't built it.

**Comment by touhidrahman** [comment]
Halfway through upgrading the raw implementation of google-maps to @angular/google-maps in our production app and found that `map-circle` is not there. Would love to get this feature soon.

**Comment by pgg** [comment]
Polygon please

**Comment by schmorrison** [comment]
After some work I got polygons to draw, here is my component:

home.page.ts
```
@Component({
  selector: 'app-home',
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.scss'],
})
export class HomePage implements OnInit {
  center = {lat: 50.3, lng: -104.5};
  zoom = 8;
  polygon: google.maps.LatLngLiteral[] = [];
  options: google.maps.PolygonOptions = {
    strokeColor: '#FF0000',
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: '#FF0000',
    fillOpacity: 0.35,
    visible: true
  };

addMarker(event: google.maps.MouseEvent) {
  this.polygon = [...this.polygon, event.latLng.toJSON()];
}

removeMarker() {
  this.polygon = this.polygon.slice(0, this.polygon.length - 1);
}


googleMapsLoaded() {
    if ('google' in window && typeof window.google === 'object' && typeof window.google.maps === 'object') {
      google.maps.event.trigger(this.map, 'resize');
      return true;
    }
    return false;
  }
```

home.page.html
```
<google-map #map *ngIf="googleMapsLoaded()" width="100%" height="80vh" 
            [center]="center" [zoom]="zoom" 
            mapTypeId="HYBRID"
            (mapClick)="addMarker($event)" (mapRightclick)="removeMarker()">
            <map-polygon *ngIf="polygon.length > 0" #roofArea [paths]="polygon" [options]="options"></map-polygon>
        </google-map>
```

**Comment by mbehrlich** [comment]
The Geometry components are now all in  the master branch.
