### ISSUE TITLE
Can't bind to 'dataSource' since it isn't a known property of 'table'

### ISSUE THREAD

**Issue by testengine999** [angular/components#18325]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("

<div class="mat-elevation-z8">
  <table mat-table [ERROR ->][dataSource]="dataSource" matSort>

    
"): ng:///AdminLayoutModule/DashboardComponent.html@5:19
Can't bind to 'matHeaderRowDef' since it isn't a known property of 'tr'. ("
    </ng-container>

    <tr mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColu"): ng:///AdminLayoutModule/DashboardComponent.html@31:23
Property binding matHeaderRowDef not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    </ng-container>

    [ERROR ->]<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; col"): ng:///AdminLayoutModule/DashboardComponent.html@31:4
Can't bind to 'matRowDefColumns' since it isn't a known property of 'tr'. ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row [ERROR ->]*matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:16
Property binding matRowDefColumns not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    [ERROR ->]<tr mat-row *matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:4
Can't bind to 'pageSizeOptions' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageSizeOptions' input, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </table>

  <mat-paginator [ERROR ->][pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:17
'mat-paginator' is not a known element:
1. If 'mat-paginator' is an Angular component, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  </table>

  [ERROR ->]<mat-paginator [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:2
Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("

<div class="mat-elevation-z8">
  <table mat-table [ERROR ->][dataSource]="dataSource" matSort>

    
"): ng:///AdminLayoutModule/DashboardComponent.html@5:19
Can't bind to 'matHeaderRowDef' since it isn't a known property of 'tr'. ("
    </ng-container>

    <tr mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColu"): ng:///AdminLayoutModule/DashboardComponent.html@31:23
Property binding matHeaderRowDef not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    </ng-container>

    [ERROR ->]<tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; col"): ng:///AdminLayoutModule/DashboardComponent.html@31:4
Can't bind to 'matRowDefColumns' since it isn't a known property of 'tr'. ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row [ERROR ->]*matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:16
Property binding matRowDefColumns not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    [ERROR ->]<tr mat-row *matRowDef="let row; columns: displayedColumns;">
    </tr>
  </table>
"): ng:///AdminLayoutModule/DashboardComponent.html@32:4
Can't bind to 'pageSizeOptions' since it isn't a known property of 'mat-paginator'.
1. If 'mat-paginator' is an Angular component and it has 'pageSizeOptions' input, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </table>

  <mat-paginator [ERROR ->][pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>"): ng:///AdminLayoutModule/DashboardComponent.html@36:17
'mat-paginator' is not a known element:
1. If 'mat-paginator' is an Angular component, then verify that it is part of this module.
2. If 'mat-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  </table>

  [ERROR ->]<mat-paginator [pageSizeOptions]="[5, 10, 25, 100]"></mat-paginator>
</div>")

**Comment by tomicarsk6** [comment]
Can you also post your NgModule, it seems that you forgot to import MatTableModule to your NgModule.

**Comment by crisbeto** [comment]
It looks like you need to import the `MatTableModule` as @tomicarsk6 mentioned.

**Comment by testengine999** [comment]
I already imported in my **app.module.ts** but not working...

import {MatTableModule} from '@angular/material';

@NgModule({
 imports: [
'MatTableModule'
]
});

**Comment by tomicarsk6** [comment]
Please post whole **app.module.ts**.

**Comment by crisbeto** [comment]
If you're using the table inside a lazy-loaded module you need to import it inside the lazy module as well.
