### ISSUE TITLE
[Table] when predicate is out of scope, and far from flexible

### ISSUE THREAD

**Issue by Totati** [angular/components#18328]
I wanted to show different rows of multiple type of data depending on user role, and *matRowDef directive is really strict with the when predicate.

#### Reproduction
https://stackblitz.com/edit/angular-material-cdk-table-row-def-when

#### Actual Behavior
https://github.com/angular/components/blob/master/src/cdk/table/table.ts#L919
The table calls and passes attributes for the when function directly.

#### Expected Behavior
It would be better if it worked like *ngFor.

#### Environment

- Angular: 9.rc-10
- CDK/Material: 9.rc-8
- Browser(s): Chrome, Chromium edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by andrewseguin** [comment]
I'm not sure what you mean by it being strict, it looks like in your first example that you were able to provide the right function to the table rows.

To simplify your code, you can consider setting your predicates as class properties rather than functions that return functions:
```ts
  isTextRow = (_i: number, row: string | PeriodicElement) => typeof row === 'string';
  isElement = (_i: number, row: string | PeriodicElement) => typeof row !== 'string';
  showAdminRow = (i: number, row: string | PeriodicElement) => this.isAdmin && this.isElement(i, row);
```
