### ISSUE TITLE
datepicker: ripple doesn't disappear around icon

### ISSUE THREAD

**Issue by ThatsEli** [angular/components#18324]
#### Reproduction

https://components-issue-tmqtis.stackblitz.io

Steps to reproduce:

1. Click on the icon next to the input element
2. Select a date
 
 
#### Expected Behavior

The ripple around the icon shouldn't be there(It should disppear after clicking in the icon while opening the dialog)

#### Actual Behavior

After the dialog closes, there is a ripple around the icon that shouldn't be there. I have to click somewhere else to get it to disappear

![image](https://user-images.githubusercontent.com/15199652/73344169-2c9eae80-4282-11ea-9666-784e3e8d7426.png)

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome 79.0.3945.130
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 1909

**Comment by crisbeto** [comment]
This is an accessibility feature that works as expected. It shows that focus was returned to the button.

**Comment by ThatsEli** [comment]
Oh, my bad. :) Is there a way to disable this? `disableRipple` only works for the button 🤔

**Comment by crisbeto** [comment]
We generally don't support APIs that degrade the accessibility of the app. In this case you should be able to preserve keyboard focus while hiding the programmatic one like this:

```css
.mat-button-base.cdk-program-focused .mat-button-focus-overlay {
    display: none;
}
```

**Comment by ThatsEli** [comment]
Okay, thank you 👍
