### ISSUE TITLE
Required asterisk of form field labels are wrongly colored in accent color 

### ISSUE THREAD

**Issue by tarekis** [angular/components#18326]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Required asterisk of form field labels are colored in **primary** (as in the color that is used to color the label) color.

#### What is the current behavior?
Required asterisk of form field labels are colored in **accent** color.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-svwsjn (fork of [offical template](https://stackblitz.com/angular/qxnldxyaday) with `required` set on the input component)

#### What is the use-case or motivation for changing an existing behavior?
Fulfilling the (current) material design spec.

> If required text is colored, that color should also be used for the asterisk  

Taken from http://material.io/components/text-fields/#anatomy in the section _Label text > Required text indicator_  at `Wed, 29 Jan 2020 9:54:57 GMT`, see screenshot for reference.

![Workspace 1_446](https://user-images.githubusercontent.com/16593597/73348473-c1f17100-4289-11ea-9289-cf8c48e2c82d.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All permutations of every variable listed should be affected.

Confirmed with
**Angular**: 7.55
**Material**: 8.2.0; 8.2.3
**OS**: Ubuntu 18.04.3 LTS
**Typescript**: 3.5.3
**Browsers**: Chrome Version 79.0.3945.88 (Official Build) (64-bit)

#### Is there anything else we should know?
This has been this way since 2016, since the initial commit of the (then) responsible file for theming the asterisk: https://github.com/angular/components/commit/e0726e15bf0fd1696e9bcb53f8d75d25ca815689#diff-002aa63d52575ed15761f1e16e547059R15

I suspect the material design spec was different back then.

This has been reported in a smaller scope previously, but not yet been fixed: https://github.com/angular/components/issues/16826

**Comment by mmalerba** [comment]
Dup of https://github.com/angular/components/issues/16826
