### ISSUE TITLE
Day.js date implementation / date adapter

### ISSUE THREAD

**Issue by vanrossumict** [angular/components#18337]
#### Documentation Feedback

Hi there, we're working on a date implementation / date adapter for Angular Material based on [Day.js](https://github.com/iamkun/dayjs).
Day.js is a date library which has much better treeshaking capabilities than Moment.js, thus reducing your bundle size greatly, but still offers the same amount of great features.
Recently we have also implemented support for locales, so this should by now be a reasonable alternative to the Moment date adapter.
Therefore I would like to propose mentioning this date adapter in the list of date implementations in your documentation.

Suggested addition to the documentation:
**Module**: MatDayjsDateModule
**Date type**: Dayjs
**Supported locales**: [See project](https://github.com/iamkun/dayjs/tree/dev/src/locale)
**Dependencies**: [Day.js](https://github.com/iamkun/dayjs)
**Import from**: @tabuckner/material-dayjs-adapter
P.S. we have also implemented the MAT_DATE_FORMATS provider

Let us know what you think.

**Affected documentation page:** https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by tabuckner** [comment]
Happy to submit a PR to update the documentation if that makes things any easier. :)

**Comment by jelbourn** [comment]
Tracking this in #20599 going forward
