### ISSUE TITLE
MatTable examples use CdkTable attributes 

### ISSUE THREAD

**Issue by wambowams** [angular/components#18342]
In the documentation for mat-table the example looks like below:
```
<mat-table [dataSource]="dataSource">
  <!-- User name Definition -->
  <ng-container cdkColumnDef="username">
    <mat-header-cell *cdkHeaderCellDef> User name </mat-header-cell>
    <mat-cell *cdkCellDef="let row"> {{row.username}} </mat-cell>
  </ng-container>

  <!-- Age Definition -->
  <ng-container cdkColumnDef="age">
    <mat-header-cell *cdkHeaderCellDef> Age </mat-header-cell>
    <mat-cell *cdkCellDef="let row"> {{row.age}} </mat-cell>
  </ng-container>

  <!-- Title Definition -->
  <ng-container cdkColumnDef="title">
    <mat-header-cell *cdkHeaderCellDef> Title </mat-header-cell>
    <mat-cell *cdkCellDef="let row"> {{row.title}} </mat-cell>
  </ng-container>

  <!-- Header and Row Declarations -->
  <mat-header-row *cdkHeaderRowDef="['username', 'age', 'title']"></mat-header-row>
  <mat-row *cdkRowDef="let row; columns: ['username', 'age', 'title']"></mat-row>
</mat-table>
```
But if u use this with the cdk attributes, it doesn't work as the cdk attributes are no known attributes for mat-header-row etc. 
It should be mentioned, to add the CdkTableModule or the example should use the corresponding mat attributes.

https://material.angular.io/components/table/overview

**Comment by testengine999** [comment]
I got Below Error
[https://material.angular.io/components/table/overview]

Error: Template parse errors: Can't bind to 'dataSource' since it isn't a known property of 'table'.

**Comment by sacgrover** [comment]
This was already fixed in https://github.com/angular/components/pull/17612

**Comment by crisbeto** [comment]
Seems to have been fixed in master. There are a few leftover places, but they're in internal development apps and I'll clean them up separately.

**Comment by testengine999** [comment]
ok, thanks buddy........
