### ISSUE TITLE
ng-template inside MatAutocomplete doesn't work

### ISSUE THREAD

**Issue by fetis** [angular/components#18353]
#### Reproduction

https://stackblitz.com/edit/angular-wwwm2h

Steps to reproduce:
1.  Click on the input field
  
#### Expected Behavior

Autocomplete list is rendered on input click

#### Actual Behavior

Nothing is rendered

If you uncomment extra `mat-option` then list appears. I think ii's connected with the fact that autocomplete is unable to determine the number of options if they're coming from `ng-template`

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
The autocomplete won't open if it doesn't pick up any options using`ContentChildren`. Projecting them in via `ngTemplateOutlet` like this isn't supported.

**Comment by fetis** [comment]
@crisbeto I recently implemented component where used `QueryList.changes` to track dynamic elements in projected content. Why not use it here as well?

**Comment by crisbeto** [comment]
The problem isn't that the content is projected, it's that the content is actually an `ng-container` which creates the items through a `TemplateRef`. This case won't be picked up by the `QueryList`.

**Comment by fetis** [comment]
so, is it a general Angular problem? Maybe we can address it to Angular team?

**Comment by crisbeto** [comment]
It's definitely a framework limitation, but I'm not sure that it's a bug since this is the way it has always worked.

**Comment by fetis** [comment]
ok, I see. Thanks for explanation
