### ISSUE TITLE
base.js:4915 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. 

### ISSUE THREAD

**Issue by andzejsw** [angular/components#18351]
Getting this on my angular 8.2.14 build: 
"[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event".
I know this error was reported in this thread: https://github.com/angular/components/issues/4221.
But it is closed even when issue is still not resolved.

**Comment by crisbeto** [comment]
What Material/CDK components are you using on the page that's logging the warning?

**Comment by andzejsw** [comment]
> What Material/CDK components are you using on the page that's logging the warning?

After i removed all Material/CDK components from project, still this error was visible.

**Comment by andzejsw** [comment]
My bad. This error was showing for youtube script, which was blocked by adblocker.
