### ISSUE TITLE
MatTabHeader missing in MatTabGroup

### ISSUE THREAD

**Issue by drakesong** [angular/components#18350]
#### Description
I have recently upgraded @angular/material from 8.1.2 to 8.2.3. The following snippet now gives me the following error: _**"Property '_tabList' does not exist on type 'MatTabGroupBaseHeader'."**_

```
@ViewChild(MatTabGroup, { static: false }) tabs: MatTabGroup;

const tabHeaderLabelList = <HTMLElement>(
    this.tabs._tabHeader._tabList.nativeElement.querySelector(
        '.mat-tab-labels'
    )
);
```

I've noticed that in PR #16805, under file _src/material/tabs/tab-group.ts_, _MatTabGroupBaseHeader_ is now being used for __tabHeader_ property instead of _MatTabHeader_. Because _MatTabGroupBaseHeader_ doesn't have __tabList_ property, I am getting this error and cannot compile. 

Would anybody be able to provide suggestions as to how to fix this error? Going to downgrade @angular/material to 8.1.1 for now. Thank you.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.1.2 -> 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by testengine999** [comment]
i got below error

Can't bind to 'dataSource' since it isn't a known property of 'table'

**Comment by crisbeto** [comment]
Properties whose names start with an underscore are considered private APIs and we don't make any commitments around backwards compatibility and things being moved around between versions.
