### ISSUE TITLE
Mat-DatePicker is adding "â" before and after the date.

### ISSUE THREAD

**Issue by talentedaamer** [angular/components#18370]
On `IE 11`. The date picker was not working and the search results were not showing up. When I see the data sent to the API call I found that datepicker is adding a special character before and after the date values. e.g when i enter the date `02/02/2020` -> `â2â/â2â/â2020`.

It should always return the same date entered in the input.

`@angular/cdk": "^7.1.0`
`@angular/material": "^7.1.0`
`IE 11`
`Windows`

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)

**Comment by talentedaamer** [comment]
@jelbourn i found the bug and solution, when I use `.toDateTImeString()` function on `DatePicker value` it was adding these special characters in `IE11`, I used `moment.format('dd/mm/yyyy')` and it was fixed. thank you.
