### ISSUE TITLE
Material Button removes data attributes

### ISSUE THREAD

**Issue by spock123** [angular/components#18396]
#### Reproduction

Steps to reproduce:

Create a button with a data attribute (here: data-cy):

`<button data-cy="loginBtn"  mat-raised-button type="button" (click)="submit()">Button</button>
`

 
#### Expected Behavior

Data attributes are not stripped 

#### Actual Behavior

What behavior did you actually see?

Attribute `data-cy `is removed when serving/building the app

#### Environment

- Angular: 8.2.10
- CDK/Material: 8.2.3

**Comment by crisbeto** [comment]
It's most likely something different in your app. Here's an example that shows it preserving the attribute: https://stackblitz.com/edit/angular-2pcyar.
