### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded in all documentation pages

### ISSUE THREAD

**Issue by tobiashoeft** [angular/components#18410]
#### Documentation Feedback

When I go to the page, I get the following error regardless of which subpage

![image](https://user-images.githubusercontent.com/5573898/73910768-8883bb80-48b0-11ea-86ef-0f41cbf3d997.png)

**Affected documentation page:**

https://material.angular.io/

Browser: CHROME Version 80.0.3987.87 (Offizieller Build) (64-Bit)

**Comment by crisbeto** [comment]
I'm not seeing it on my end. Could it be a caching issue?

**Comment by tobiashoeft** [comment]
> I'm not seeing it on my end. Could it be a caching issue?

Its an extension issue sorry for that.

The extension that blocks is an alpha https://github.com/typebytes/ng-profiler-devtools/

So a client problem if that extension is active.

I close it.
