### ISSUE TITLE
mat-form-field with nested FormArray breaks control behavior

### ISSUE THREAD

**Issue by BenRib** [angular/components#18412]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-pnmusw

Steps to reproduce:
1. Go to the StackBlitz linked above
2. Click on the mat-form-field controls ('mat-form-field + matInput' and 'mat-form-field + select (matNativeControl)') at sub-item level
3. Check the box "Display nested mat-form-field with mat-select" at the top of the screen 
 
#### Expected Behavior

1. Ability to get the focus on the mat-form-field inner control when clicking on it and/or using tab key in order to set its value
2. No hang when trying to display a mat-select in a mat-form-field within a nested FormArray

#### Actual Behavior

1. Native input and select controls behave as expected but there is no way to get the focus of level 2 mat-form-field controls in order to update their values independently from their types. However the value of the control is updated in the mat-form-field control when updated from the native one, so it looks like the binding works fine.
2. The application hangs and the memory used by the process keeps increasing when trying to display mat-select in a mat-form-field within a nested FormArray.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome 80.0.3987.87
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
I think this is the result of some issue with the example code, not Angular Material. Even the nested native controls don't work right. The select dropdown won't open and the input de-focuses after typing a single letter.

Looking in the chrome inspector I can see that every time I click the nested elements are being re-rendered which is probably what's causing a lot of this weird behavior.
