### ISSUE TITLE
How to place a mat-menu on Overlay.

### ISSUE THREAD

**Issue by seanzx** [angular/components#18416]
I tried to place a mat-menu to the overlay I created, turns out that the overlay will be closed when I  click the MatMenuTrigger.

I wonder if it is a WAI, and I guess it is because mat-menu creates another overlay and there could only be one overlay in the page. So how could I place a met-Menu?

**Comment by jelbourn** [comment]
It's not really clear what you're asking here without any code.

**Comment by seanzx** [comment]
Turns out it is because I place the mat-menu into the <form></form>.
