### ISSUE TITLE
Setting initial value of MatSelect using Reactive Forms does not set matSelect.value

### ISSUE THREAD

**Issue by trevorhreed** [angular/components#18423]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-reabu9?file=src%2Fapp%2Fapp.module.ts

Steps to reproduce:
0. (Skip these steps and just refer to the StackBlitz)
1. Create a Reactive Form with MatSelect component
2. Set the initial value for the MatSelect component when creating the form (e.g. with FormBuilder, etc.)
3. Display the value of the MatSelect (e.g. using a template ref: `<mat-select #select>...</mat-select> ... {{ #select.value }}`)
 
#### Expected Behavior

The value of #select.value should be equal to the initial value set in the FormGroup/FormControl

#### Actual Behavior

The value for #select.value is empty

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mimedo** [comment]
Hey, since you're not assigning in your component a default value, it will remain empty.
To assign a default value, add a property in your component and add in the template a property binding.

**Template:**
_To print the default value_
`<p>The selected color is: '{{ defaultColor }}'</p>`
...
_Add property binding_
`<mat-select [(value)]="defaultColor" formControlName="color">`

**Component:**
_Add property (under form and data)_
`defaultColor = '#0000FF';`

**Comment by trevorhreed** [comment]
The default value is set at src/app/app.component.ts:19

**Comment by chaudharydivya** [comment]
Hi I am facing an issue with reactive form control usage. For mat-select I have a default JSON array with name and id. Of which I am showing only name in the drop down. I want to set a name as default using similar JSON but I am not able to do that. Kindly suggest :
`<form [formGroup]="form">
  <mat-form-field>
    <mat-label>Color</mat-label>
   <mat-select [(value)]="state.name" formControlName="state">
     <mat-option *ngFor="let state of stateList" [value]="state">
     {{ state.name }}
      </mat-option>
      </mat-select>
  </mat-form-field>
</form>`

`
this.stateList=[{name:'def',id:'1'},{name:'ghi',id:'2'}];
this.form = this.formBuilder.group({
      state: {name:'abc',id:'1'}
    })`

**Comment by Harkindey** [comment]
WOW SO THIS ISSUE EXIST.
