### ISSUE TITLE
Conflicting components: MatFormField,MatFormField while Testing with Angular 8

### ISSUE THREAD

**Issue by ignaciojvig** [angular/components#18425]
#### Reproduction

Steps to reproduce:
1. Import "MatSelectModule" in my-component.spec.ts
2. Run "npm run test"
 
 
#### Expected Behavior
Jest running my tests as expected

#### Actual Behavior
An error is thrown, with the current message: 

> Template parse errors:
> More than one component matched on this element.                                                                        Make sure that only one component's selector can match a given element.                                                 Conflicting components: MatFormField,MatFormField
![with-mat-select-module](https://user-images.githubusercontent.com/18212861/73993208-426e3c80-4930-11ea-9797-a099c2baa5a4.png)

If I remove 'MatSelectModule', I got another error:

> Template parse errors:
> 'mat-select' is not a known element:
> 1. If 'mat-select' is an Angular component, then verify that it is part of this module.                                 2. If 'mat-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
![without-mat-select-module](https://user-images.githubusercontent.com/18212861/73993221-53b74900-4930-11ea-858a-5c133c3102f5.png)

#### Environment

- Angular: ~8.2.14
- CDK/Material: ^8.2.3
- Browser(s): Chrome 80.0.3987.87
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This sounds like an issue with your environment. I would recommend trying the latest version and _potentially_ clearing your `node_modules`

**Comment by omnibrain** [comment]
@ignaciojvig I'm having the exact same problem after migrating from Karma to Jest. Did you find a solution to this?

**Comment by ignaciojvig** [comment]
@omnibrain unfortunatly i had no success using Jest :(
I switched back to Karma and it started working

**Comment by jaganathanb** [comment]
Looks like it is [material ui](https://github.com/ngx-formly/ngx-formly/issues/777) issue.

**Comment by jelbourn** [comment]
Closing since this seems to be unrelated to Angular Material itself.
