### ISSUE TITLE
mat tabs, ng-content

### ISSUE THREAD

**Issue by GlauberF** [angular/components#18437]
#### Reproduction

stackblitz: https://stackblitz.com/edit/mat-tabs-vimbo-form?file=src%2Fapp%2Fmat-tabs%2Ftabset%2Ftabset.component.html

Steps to reproduce:
I am creating dynamic tabs, and in my scenario I need to use ng-content (I believe it is the only way), but it is not working.
It renders only the content of the last element.

if anyone can help, i am grateful.

**Comment by andrewseguin** [comment]
Your code seems to expect that each tab is inserting the `ng-content`, but unfortunately Angular will only put it into one. You may get better help if you ask for help on StackOverflow and show what you are trying to do.

**Comment by GlauberF** [comment]
@andrewseguin would you know any way to fix this? :)

https://stackoverflow.com/questions/60121060/custom-type-mat-tabs-for-ngx-formly-does-not-render-the-content-of-all-tabs
