### ISSUE TITLE
@angular/material-moment-adapter@9.0.0 is not published under the "latest" tag

### ISSUE THREAD

**Issue by thetric** [angular/components#18432]
`@angular/material-moment-adapter@9.0.0` should be published under the `latest` tag, not `next`. See https://yarnpkg.com/package/@angular/material-moment-adapter:

![image](https://user-images.githubusercontent.com/19861998/74036255-2dd78600-49bc-11ea-9c60-5fad3aa6d7d1.png)

**Comment by Nexxado** [comment]
FYI to install manually:

```Bash
# Yarn
yarn add @angular/material-moment-adapter@^9.0.0

# Npm
npm i @angular/material-moment-adapter@^9.0.0
```

**Comment by jelbourn** [comment]
Fixed, thanks!
