### ISSUE TITLE
Drag-and-Drop Editable Text Fields Sample 

### ISSUE THREAD

**Issue by TLKG** [angular/components#18459]
#### Documentation Feedback

[All samples of Drag-and-Drop](https://material.angular.io/cdk/drag-drop/examples) are on read-only items. Would like to see a bi-drectional editable list of drag-and-drop sample. I'm looking for a way to implement, for [example](https://stackblitz.com/edit/angular-kwcrnh?embed=1&file=src/app/cdk-drag-drop-custom-placeholder-example.html)
**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/cdk/drag-drop/examples

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I don't think that we need to do this, because there's nothing specific to inputs that would warrant a dedicated example. They work in the same way as other elements when it comes to dragging and dropping.
