### ISSUE TITLE
Have MatDrawer extend CdkScrollable

### ISSUE THREAD

**Issue by sjlskyward** [angular/components#18453]
#### Feature Description

Heavy related to [#9136](https://github.com/angular/components/issues/9136). Since `.mat-drawer-inner-container` is generated, `cdkScrollable` cannot be added.By extending `CdkScrollable` would make `MatDrawer` behave like `MatDrawerContent`, which already extends `CdkScrollable`

#### Use Case

Subscribe to scroll events and manage scroll behavior of `MatDrawer`; this would allow `MatDrawerContent` to respond dynamically to scroll events on `MatDrawer`, and vice versa.

**Comment by devversion** [comment]
Thanks for this issue. Could you please clarify the use-case for having `CdkScrollable` on the drawer itself? Couldn't you wrap the drawer yourself with `cdkScrollable` if needed?

**Comment by devversion** [comment]
I chatted with @crisbeto about this. Seems like a good use-case that tooltips/menu can be used in the drawer. Wrapping the drawer manually _should_ definitely work, but it's not really convenient and this should work out of the box.
