### ISSUE TITLE
PageUp and PageDown dont work in cdk/scrolling component

### ISSUE THREAD

**Issue by davidglezz** [angular/components#18460]
#### Reproduction
PageUp and PageDown dont work in cdk/scrolling component with Chrome, in firefox it works fine.

https://material.angular.io/cdk/scrolling/overview

Steps to reproduce:
1. Focus some cdkScrollable example
2. press the pageUp key 3 times or more
 
#### Expected Behavior
To scroll like non-virtual scrollable panels.

#### Actual Behavior
PageUp stop scroll after 2 or 3 keystrokes.
PageDown stop scroll sometimes.

#### Environment
- Angular: 8, 9
- CDK/Material: 8, 9
- Browser(s): Chrome 
- Operating System: Windows

**Comment by jelbourn** [comment]
I just tried this in Chrome 81 on Windows and PgUp and PgDown work as expected in all of the examples on https://material.angular.io/cdk/scrolling/overview. Closing for now, feel free to file a new issue if there are more details.
