### ISSUE TITLE
Examples link to stackblitz are broken

### ISSUE THREAD

**Issue by AElMehdi** [angular/components#18462]
For some reason the examples [external links to stackblitz](https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fexpansion-overview-example.ts) are broken: `Internal Server Error in Firefox` and `Cannot GET /api/angular/v1 in Chrome`.

Can be checked out in the `expansion panel`  [examples page](https://material.angular.io/components/expansion/examples), and apparently in all the other examples pages.

**Comment by sacgrover** [comment]
Checked. Working fine for me.  https://stackblitz.com/angular/vmknnbrxjgr?file=src%2Fapp%2Fexpansion-overview-example.ts

**Comment by AElMehdi** [comment]
Yeap, now it's working. Thanks.
