### ISSUE TITLE
Clarify use of non-standard "align" attribute for mat-dialog-actions

### ISSUE THREAD

**Issue by cwatzl** [angular/components#18479]
#### Documentation Feedback

Documentation suggests using the `align` attribute to align the content of `mat-dialog-actions` directives to the middle or right. However, `align` is an obsolete HTML attribute and not valid HTML5, and my IDE's static code analysis tools rightfully complain about using it. If using `align` really is the right way of doing this regardless of W3C standards, this should be clarified in the docs (and possibly be explicitly declared as a property of the `MatDialogActions` directive to make IDEs stop complaining). 

**Affected documentation page:** https://material.angular.io/components/dialog/overview

**Comment by crisbeto** [comment]
The dialog isn't meant to use the `align` attribute, but `align` is a custom attribute. It didn't make sense to turn it into an input, because it's only used for styling.

**Comment by devversion** [comment]
I would agree that this is confusing. Given that `align` is not standard for `HTMLDivElement`, I think it would make sense to turn this into an input (that also helps w/ type-checking; IDE's and bindings).

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDivElement

**Comment by PooSham** [comment]
I could take this as my first issue I think. A fun christmas activity 😁🎅

**Comment by PooSham** [comment]
Question: Would adding an input and removing the css code count as `feat`, `fix` or `docs` in the type when I commit? I think it's hard to classify things like this.

**Comment by PooSham** [comment]
As of now, my solution would be a breaking for those using `[attr.align]="x"`. I'd assume this is a very special case, probably only used for demo apps. Should I solve it in some other way, such as adding an input that is called `justify` and keep the old scss code for backwards compability?
