### ISSUE TITLE
mat-drawer-container triggers angular detection cycles on window:resize

### ISSUE THREAD

**Issue by Ploppy3** [angular/components#18471]
#### Reproduction

https://stackblitz.com/edit/angular-se13bg?file=src%2Fapp%2Fsidenav-drawer-overview-example.html

Steps to reproduce:
1. `<mat-drawer-container></mat-drawer-container>`
 
#### Expected Behavior

`mat-drawer-container` should not trigger angular detection cycle when the window is resized

#### Actual Behavior

`mat-drawer-container` triggers angular detection cycles on window:resize

#### Environment

- Angular: 9
- CDK/Material: 9

**Comment by crisbeto** [comment]
Sounds like it could be resolved by https://github.com/angular/components/pull/15814 since the sidenav is set up to only trigger change detection if its margin has changed.
