### ISSUE TITLE
Overlay update position allow set _isInitialRender

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#18487]
#### Feature Description

Normally we have 3 scenarios where there is a need to update position
1. window resize
2. on scroll 
3. on content change (after ajax back)

Currently material already done the first and second for us.

1. window resize will always update position and will use _isInitialRender = true.
![image](https://user-images.githubusercontent.com/8691013/74425788-397cee00-4e8f-11ea-83ed-dbb603e55914.png)

2. on scroll will update position _isInitialRender = false

3. on content change. material does not listen to content, but we are still able to call `overlayRef.updatePosition` after ajax calls respond. But we can't set `_isInitialRender = true` because this is a private method. It will cause an unexpected result, especially when we use withFlexibleDimensions.

The step: 
 1: attach content to overlay (content height = 0 because waiting for ajax back)
 2:. overlay will set width height to container (withFlexibleDimensions)
![image](https://user-images.githubusercontent.com/8691013/74426905-31be4900-4e91-11ea-96f0-651417e2329b.png)
 3: When ajax data returns, we call `updatePosition`, but because of `_isInitialRender = false` 
overlay can't get the right width and height to calc, so it will result in an unexpected result.
https://www.youtube.com/watch?v=d_jcX09KO_Q

So I suggest material should allow to set `_isInitialRender` when calling `updatePosition`.

**Comment by crisbeto** [comment]
@keatkeat87 we talked about this with the team and we decided that it doesn't make sense to add a dedicated API for it, because it's a very niche use case. You should be able to achieve the same result with the current APIs by doing this:

```
positionStrategy.withLockedPosition(false);
positionStrategy.apply();
withLockedPosition.withLockedPosition(true);
```
