### ISSUE TITLE
mat-menu-item color

### ISSUE THREAD

**Issue by DerHerrGammler** [angular/components#18496]
I would like to see that i can set a color attribut to a mat-manu-item so that the button get this color

Provide a brief summary of the feature you would like to see.

Better menu with colors

Describe the use case(s) that the proposed feature would enable.

actually i use multicolor menus with an old bootstrap style now i want to build the same menu in mat menus but i cant set the color of the buttons without a hack

**Comment by jelbourn** [comment]
We don't have any plans to do something like this since it's not captured in the Material Design spec
