### ISSUE TITLE
mat-slider does not have hover or drag effect

### ISSUE THREAD

**Issue by curbol** [angular/components#18492]
#### Reproduction

https://stackblitz.com/edit/angular-iul3da?file=src%2Fapp%2Fripple-overview-example.html
or
https://material.angular.io/components/slider/overview

Steps to reproduce:
1. Hover or drag the slider thumb circle
2. There is no halo effect as specified in Material Design
 
#### Expected Behavior

There should be a halo effect as specified in the Material Design spec. This is the transparent ring around the draggable part of the slider.

https://material.io/components/sliders/#continuous-slider
![f6250f92-010a-4777-9ae4-e7443c3f3b6d](https://user-images.githubusercontent.com/5971687/74452075-30b3fa00-4e46-11ea-86fb-7d6c609afc6e.jpg)

Expected to work similar to this: https://vuetifyjs.com/en/components/sliders

#### Actual Behavior

There is no halo effect. There is no user feedback or animation other than being able to move the thumb circle. No hover effect and no drag effect.

#### Environment

The older version of angular material design using the "md-" prefix has this effect, but the newest version using the "mat-" prefix does not.

- Angular: any recent version
- CDK/Material: 5.2.5 to 9.0.0
- Browser(s): Chrome (all?)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS (all?)

If this is an intentional design decision, then it should at least be an option for the dev to enable. It seems like a mistake to me as the rest of the component library has similar effects. Also the library should be following the Material Design guidelines.

**Comment by devversion** [comment]
Great issue. Thanks! We plan on basing our current slider implementation on the canonical Material Design slider provided by the MDC team. We have a prototype in the experimental package already, but that one is not matching the spec either as the MDC team currently reworks their slider.

**Comment by devversion** [comment]
Related issue on the MDC side: https://github.com/material-components/material-components-web/issues/5515.

**Comment by amysorto** [comment]
This is fixed in the MDC based slider component in v15
