### ISSUE TITLE
Angular 9 Upgrade Erroring on cdk-high-contrast mixin

### ISSUE THREAD

**Issue by msorens** [angular/components#18507]
#### Reproduction

Steps to reproduce:
1. Download code from this branch: https://github.com/chef/automate/tree/ms/angular-9-upgrade
2. cd components/automate-ui
3. npm install
4. ng build
 
#### Expected Behavior

No build errors

#### Actual Behavior

Several errors of this form:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: wrong number of arguments (2 for 1) for `cdk-high-contrast'
        on line 1934 of node_modules/@angular/material/_theming.scss, in mixin `cdk-high-contrast`
        from line 1934 of node_modules/@angular/material/_theming.scss, in mixin `mat-badge-theme`
        from line 5112 of node_modules/@angular/material/_theming.scss, in mixin `angular-material-theme`
        from line 47 of src/styles/chef-theme.scss
        from line 5 of /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/src/styles.scss
>>     @include cdk-high-contrast(active, off) {
```

#### Other Details

We are currently upgrading from Angular 8.3.21 to Angular 9 alongside Angular Material and are hung up an issue pertaining to cdk-high-contrast when running ng-build. The specific output is that we're providing the wrong number of arguments for `cdk-high-contrast`, currently providing 2 but we should be providing 1. We haven't touched any of the Angular code ourselves and this was working previously.

We have looked into both #34731 and angular/components#18147 and can't completely deduce if they are related - at first glance it appears this is separate but wondering if there may be a link somewhere.

#### Affected Packages

@angular/material/_theming.scss, in mixin cdk-high-contrast
@angular/material/_theming.scss, in mixin mat-badge-theme
@angular/material/_theming.scss, in mixin angular-material-theme

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): NA
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

Originally reported in the core repo (https://github.com/angular/angular/issues/35425); was guided to re-report it here.

**Comment by crisbeto** [comment]
It might be worth double-checking that both Material and the CDK are at version 9. This looks like it could be loading the CDK mixins from version 8.

**Comment by msorens** [comment]
Thanks. I have triple-checked. Here is what is in package.json:
```
$ grep '@angular' package.json 
27:    "@angular/animations": "^9.0.0",
28:    "@angular/cdk": "^9.0.0",
29:    "@angular/common": "^9.0.0",
30:    "@angular/compiler": "^9.0.0",
31:    "@angular/core": "^9.0.0",
32:    "@angular/forms": "^9.0.0",
33:    "@angular/material": "^9.0.0",
34:    "@angular/platform-browser": "^9.0.0",
35:    "@angular/platform-browser-dynamic": "^9.0.0",
36:    "@angular/platform-server": "^9.0.0",
37:    "@angular/router": "^9.0.0",
64:    "@angular-devkit/build-angular": "~0.900.1",
65:    "@angular/cli": "^9.0.1",
66:    "@angular/compiler-cli": "^9.0.0",
67:    "@angular/language-service": "^9.0.0",
```
Furthermore, if I grep package-lock.json, then look for any "8"s -- `grep '@angular' package-lock.json | grep 8` I get no hits, so there are no version 8 residuals.

**Comment by crisbeto** [comment]
Trying out the linked repo, it seems like the real error is this:

```
ERROR in src/main.ts:4:54 - error TS2307: Cannot find module './assets/chef-ui-library/loader'.

4 import { applyPolyfills, defineCustomElements } from './assets/chef-ui-library/loader';
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The Sass compilation error seems to be a side-effect of the error above being thrown earlier down the line.

**Comment by msorens** [comment]
Apologies, @crisbeto . The above steps are failing for you because you have not built from our codebase before, so that dependency is missing. The steps on a virgin system would be:
```
cd components/automate-ui
npm install
make update-ui-lib
ng build
```

**Comment by msorens** [comment]
Hello, @crisbeto ! Just wanted to check if there is any update on this? It is the only blocker to my Angular 9 update.

**Comment by SEAjamieD** [comment]
Hi material team, checking in to see if you may have thought of any other actions we could take or had any other issues with this.  Thanks again for your help.

**Comment by msorens** [comment]
It turns out we had a copy of _theming.scss in our code base but it was not being kept current. Will be getting rid of the copy soon, but in the meantime just bringing it current resolved this issue.
