### ISSUE TITLE
material table not showing new line (\u0085)

### ISSUE THREAD

**Issue by buzzbonner24** [angular/components#18506]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Display text in mat-cell containing "first line \u0085 second line".
2. All text is displayed on the same line with an invalid character displayed for the new line.
 
 
#### Expected Behavior

What behavior were you expecting to see?

Text to appear on 2 lines

#### Actual Behavior

What behavior did you actually see?

Text appears on 1 line with invalid character

#### Environment

- Angular: 8.11
- CDK/Material: 8.11
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by tomicarsk6** [comment]
You pasted a wrong stackblitz example, please fix that so that we can help you.

**Comment by andrewseguin** [comment]
I'm not sure I understand - do you normally see this character in HTML working as you expect?

https://jsfiddle.net/ayjtrqdo/
