### ISSUE TITLE
How to add containers, row, columns, margin, padding in Angular Material?

### ISSUE THREAD

**Issue by gegobyte** [angular/components#18514]
#### What are you trying to do?

Trying to add margin or spacing between components, row, columns, containers etc..

#### What troubleshooting steps have you tried?

Can't find anything related to it in the [docs](material.angular.io).
  
#### Environment

- Angular: 9.0.2
- CDK/Material: 9.0.0

Yesterday I started learning Angular, before I was creating websites using Materialize CSS. It has a responsive grid system, one can add container class and it automatically gives margin on both left and right. In Angular Material, everything starts at the top left and there is no spacing between components, for example - if I add a toolbar and then a card, the card will be directly attached to the bottom of the toolbar with no vertical spacing.

I can't find any container either which can add horizontal margin. So how to add all these things?

**Comment by crisbeto** [comment]
Angular Material doesn't include a grid system to avoid locking people into a particular grid and all our components are written in a way that should work with any grid.
