### ISSUE TITLE
Examples link to stackblitz are broken in Firefox

### ISSUE THREAD

**Issue by medeirosjoaquim** [angular/components#18518]
Examples in stackblitz are broken like in [this example](https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fexpansion-overview-example.ts) where the link was taken from https://material.angular.io/components/expansion/overview

It's the same as mentioned in #18462.

I get "Internal Server Error" for all links. Perhaps it has something to do with the new version, cause I can google the examples and find the old link that works.

**Comment by xXTechGodSquadXx** [comment]
I tried in Google Chrome and the links worked after they failed like this in Firefox Developer Edition

**Comment by medeirosjoaquim** [comment]
> I tried in Google Chrome and the links worked after they failed like this in Firefox Developer Edition

Hi! You are right. I dont use chrome, just firefox. Tried and it worked on chrome. Problem persists on firefox.

**Comment by jgwinner** [comment]
Confirmed. Quite frustrating.

Seems to work OK in Edge also.

Stackblitz itself works great on Firefox, just not from Angular or Material documentation :(

        == John ==

**Comment by BojanKogoj** [comment]
Is this still an issue? It's working fine for me on Firefox 76.0b6

**Comment by medeirosjoaquim** [comment]
> Is this still an issue? It's working fine for me on Firefox 76.0b6

I think it's solved. I'm using Firefox 75.0 on Ubuntu and it's working fine now.
