### ISSUE TITLE
google-map gray in expansion panel | safari

### ISSUE THREAD

**Issue by opela** [angular/components#18516]
####
Steps to reproduce:
1. put google-map component inside angular material expansion panel

 
#### Expected Behavior

To be able to zoom on every browser when google-map is inside angular material expansion panel. It’s fine in chrome.

#### Actual Behavior

The map becomes gray with no content, on zoom/drag it appears again. This behavior is valid for safari on latest mac os and ios

#### Environment

- Angular: 9.0.1
- CDK/Material:9.0.1
- Browser: safari

**Comment by devversion** [comment]
Hello! I was looking into this issue but wasn't able to reproduce it.

https://stackblitz.com/edit/angular-4vefep?file=src/index.html.

Can you please clarify the problem you're seeing and maybe attach some screenshots?
