### ISSUE TITLE
Image-list component

### ISSUE THREAD

**Issue by vajahath** [angular/components#18515]
#### Feature Description

Material design contains a spec for [image-list](https://material-components.github.io/material-components-web-catalog/#/component/image-list).
It would be nice if we have an angular material equivalent for this.

#### Use Case

Please see [image-list](https://material-components.github.io/material-components-web-catalog/#/component/image-list)

**Comment by zelliott** [comment]
Have you seen https://material.angular.io/components/grid-list/overview?

**Comment by vajahath** [comment]
Yeah. OK.
Since the use case can be accomplished by the grid system, I'm closing this for now. Thanks.

Btw, I just wanted to let you know that you guys are doing really great with Angular and Angular Material. ⭐️
