### ISSUE TITLE
MatInput - On Mobile devices pressing enter key should trigger blur and hide keyboard

### ISSUE THREAD

**Issue by naveedahmed1** [angular/components#18523]
#### Reproduction

On mobile devices we often have text fields for example in case of search bar, where we want the form to be submitted when user hits enter key or search button on keyboard. When using normal HTML input, pressing enter/search button automatically submits the form and hides the keyboard.

When using matInput, though pressing enter/search button does submit the form but it doesn't hides the keyboard.
 
```
<form [formGroup]="form" (ngSubmit)="search()">
              <mat-form-field class="mat-form-field-full-width">
                <input matInput formControlName="keywords" type="search" placeholder="Title">
              </mat-form-field>
</form>

```
#### Expected Behavior

When using matInput, pressing enter/search button should hide the keyboard.

#### Actual Behavior

The keyboard remains visible although the form is submitted.

#### Environment

- Angular: 9.x
- CDK/Material:9.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by crisbeto** [comment]
`MatInput` isn't doing anything in particular that could prevent this. Maybe it depends on the context that the input is used in? E.g. if it's inside a `form`.

**Comment by naveedahmed1** [comment]
I got it fixed by adding below code in form submit function:

```
if (document.activeElement instanceof HTMLElement) {
      document.activeElement.blur();
    }
```

**Comment by crisbeto** [comment]
Interesting, we have some logic that focuses the input on clicks inside the form field. I wonder whether pressing enter doesn't end up firing that `click` handler.

**Comment by naveedahmed1** [comment]
Well I don't think so, if we have multiple input fields in a form and we set focus on first input and press enter key, it sets focus on next input. If pressing enter was firing click handler, it shouldn't set focus on next input, right?

**Comment by crisbeto** [comment]
[This example](https://stackblitz.com/edit/angular-jtechm) seems to work for me on iOS. I'm not able to test it against Android.

**Comment by naveedahmed1** [comment]
Probably because of `alert('searching');` which sets focus to the alert dialog.

**Comment by crisbeto** [comment]
This one works too: https://stackblitz.com/edit/angular-jtechm-pxjet5.

**Comment by naveedahmed1** [comment]
Doesn't seem to work on Android 9 (Chrome 80).

**Comment by naveedahmed1** [comment]
It seems that the issue is with form-field, because when i try this demo of native form input where type is `search` it works fine https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_search

**Comment by mmalerba** [comment]
I don't think that necessarily points to a bug in form-field. @crisbeto posted a stackblitz that shows a native input with the same issue.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
