### ISSUE TITLE
Guide: Creating a custom form field control

### ISSUE THREAD

**Issue by tobiasschweizer** [angular/components#18537]
#### Documentation Feedback

I walked through your guide "Creating a custom form field control" and wondered why you provide a getter for `@Input value` that is actually not used in the code.

I think that 

```ts
_handleInput(): void {
    this.onChange(this.parts.value);
  }
```

should be changed to 

```ts
_handleInput(): void {
    this.onChange(this.value);
  }
```

Then when getting a value the additional logic defined in `@Input value` would take effect when the input element is changed. Also an instance of `MyTel` is returned and not just an `object`. 

**Affected documentation page: https://material.angular.io/guide/creating-a-custom-form-field-control**

see also https://community.indepth.dev/t/never-again-be-confused-when-implementing-controlvalueaccessor-in-angular-forms/44 for further details

**Comment by tobiasschweizer** [comment]
@crisbeto If you want I can provide a PR with a fix.

**Comment by tobiasschweizer** [comment]
I figure the changes would need to go here: https://github.com/angular/components/blob/3d351802ccb4469e38c4360fe31c157b2273d86e/src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts#L149-L151

**Comment by devversion** [comment]
@tobiasschweizer I did not author that demo, but your proposal seems reasonable. A PR would definitely be appreciated. Thanks!

**Comment by tobiasschweizer** [comment]
> A PR would definitely be appreciated. Thanks!

Ok, will do.

**Comment by tobiasschweizer** [comment]
ok, I created #18609
