### ISSUE TITLE
cdk drag: add ability to update internal _activeTransform

### ISSUE THREAD

**Issue by fxck** [angular/components#18530]
I want to use `cdkDrag` for the dragging part of a custom scrollbar. But the thing is, the native scroll occurs, I apply transform3d to the custom scrollbar thumb, which is simultaneously the drag handle, now when I try to drag after scroll occurred, those transforms get all messed up.

So ideally I would like to be able to sync those values.

This works:

```
(this.cdkDragYRef as any)._dragRef._activeTransform.y = this._scrollbarPosition.y;
(this.cdkDragXRef as any)._dragRef._activeTransform.x = this._scrollbarPosition.x;
```

**Comment by crisbeto** [comment]
That was one of the purposes of the `cdkDragFreeDragPosition` input, although I'm not completely sure how well it'll work if it's being updated while dragging.

**Comment by fxck** [comment]
Looks like updating `_activeTransform` like this doesn't quite work either.

**Comment by fxck** [comment]
Is there a way to update cdkDragFreeDragPosition with method? I'm trying not to trigger change detection..

**Comment by fxck** [comment]
I'm closing this @crisbeto, `cdkDragFreeDragPosition` does exactly what I want. And `_dragRef.setFreeDragPosition` works, albeit it's going thru that private property.

I'd suggest naming cdkDragFreeDragPosition something more descriptive and adding a `setFreeDragPosition` method to CdkDrag. 

What do you think, should I make a PR (for that method at least, that rename would probably be breaking change not work doing right now I guess..)?

**Comment by crisbeto** [comment]
I agree that the name isn't great, but I couldn't come up with anything more descriptive.

Regarding the method, won't it be a little redundant? The input [basically calls directly into it](https://github.com/angular/components/blob/master/src/cdk/drag-drop/directives/drag.ts#L301).
