### ISSUE TITLE
Mat-chip steals focus from other element

### ISSUE THREAD

**Issue by OndrejPiza** [angular/components#18542]
Hi,

I have a strange issue when using mat-chip-list with mat-chip. Every time I change something in mat-chip, eg. class or make angular to reflect change in object, mat-chip which was changed gets focus by browser even that I disabled it for selection.

```
<mat-chip-list [selectable]="false">
  <ng-container *ngFor="let item of items">
    <mat-chip [selectable]="false" (click)="onItemSelected(item)"
      [ngClass]="{'selected': item?.id === +selectedItemId, 'new-message': item?.newMessage}">
    </mat-chip>
  </ng-container>
</mat-chip-list>
```

Basically there is a text box on this page. User is typing some text and when in upper menu any change happens, this text box lose focus and user has to refocus it again manually.
Did I miss something in documentation?

Thank you for any advice

**Comment by crisbeto** [comment]
I couldn't reproduce it based on the provided info. Can you post a Stackblitz that shows the issue? You can fork one of the examples from here: https://material.angular.io/components/chips/examples

**Comment by OndrejPiza** [comment]
I will prepare demo as close to my project as possible, because it also evolves Redux (but I doubt this could be the issue).

**Comment by OndrejPiza** [comment]
I've tried to reproduce it on stackblitz and no luck so far. But I'm pretty sure it is caused by this component getting focus or at least taking it from that textarea element. But without moving whole complex application to stackblitz I cannot determine which action is causing this => I do not imply that there is something wrong in this library.

Thank you for your support.
