### ISSUE TITLE
"@angular/material/icon" has missing dependencies @angular/cdk/coercion

### ISSUE THREAD

**Issue by jadekler** [angular/components#18544]
```
"@angular/material": "^9.0.0
```

Repro: https://github.com/jadekler/angular-spinner/tree/e3cb4b0bfa06ce35d3dc1711219cab68105202ac

(run `ng serve`)

With the following `app.module.ts`,

```ts
import { BrowserModule } from '@angular/platform-browser';
import {MatIconModule} from '@angular/material/icon';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    MatIconModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I get,

```
$ ng serve

chunk {main} main.js, main.js.map (main) 2.01 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 686 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.72 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-02-18T18:52:33.404Z - Hash: 2b4530d3884f9dda3f77 - Time: 2307ms

ERROR in The target entry-point "@angular/material/icon" has missing dependencies:
 - @angular/cdk/coercion
```

Seems like `@angular/material/icon` is not installing all its deendencies?

**Comment by jelbourn** [comment]
`@angular/cdk` is a peer dependency of `@angular/material` ([package.json](https://unpkg.com/browse/@angular/material@9.0.0/package.json))

https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by jadekler** [comment]
Thanks for the link and the information.

AFAICT peer dependencies [are not automatically installed](https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically) (wow). For posterity, that's in contrast to https://nodejs.org/es/blog/npm/peer-dependencies/ - it appears as though the auto-install described in https://nodejs.org/es/blog/npm/peer-dependencies/ was reverted sometime in npm3+. Good lord, what a mess.

OK, so, AFAICT, the value that peer dependency declarations provide is occasionally telling users about invalid versions of my-lib and my-peer-lib. However, it seems to not actually address point of declaring a dependency - installing said dependency when an upstream user says `install my deps`.

Overall this seems a poor experience for users. When users depend on this library and their build fails (because they don't have cdk), they have zero clue what's going on. One certainly does not expect to have to go look into the package.json of various dependencies. It seems like the easiest way to get around this is to just depend on every single @angular thing, which horribly bloats a build. Is that what everyone does? It seems like all the stackblitz examples linked from the documentation site do so, so it seems to be a pattern.

I don't think any of this is going to change, but FWIW I think this is a poor experience for users and should be fixed. If material needs cdk to work, why not just add it to dependencies?

(disclosure: I'm not a javascript person and am not aware of what the downsides of adding it as a dep has - it just seems insane that it _is_ a dependency but it's not being declared as such)

**Comment by jadekler** [comment]
Update: after discussion, seems like it has to be this way or else users get two copies of cdk. Bummer. One nice-ish solution would be for npm to be intelligent enough to suggest missing peer dependencies when it fails.
