### ISSUE TITLE
Mat-select listens window 'resize' event inside the zone

### ISSUE THREAD

**Issue by llorenspujol** [angular/components#18546]
#### Reproduction

1- Open the dev tools.
2- Resize the window.
3- See the console.log('Tick') being fired multiple times.

Stackblitz: https://stackblitz.com/edit/angular-nuyaqc

 
#### Expected Behavior

I expect that on window resize there isn't any CD run fired by mat-select component

#### Actual Behavior

Somehow mat-select component is listening window 'resize' event inside the zone, this fires a CD run on every 'resize' event. This CD run is not necessary since mat-select, as far as I know, doesn't react on window changes, and if so, it should do it outside the zone and detecting changes locally IMO.

#### Environment

- Angular: ~9.0.0
- CDK/Material: ~9.0.0
- Browser(s): Chrome (latest)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
I bet the culprit is the cdk overlay code. It positions the overlay depending on how much space is left, but I don't think it needs to be listening inside the NgZone

**Comment by crisbeto** [comment]
Closing since this should've been resolved by https://github.com/angular/components/pull/15814 a long time ago.
