### ISSUE TITLE
Mat-Table inside a Mat-table with multiTemplateDataRows

### ISSUE THREAD

**Issue by w1ldworm** [angular/components#18558]
#### Reproduction

https://stackblitz.com/edit/angular-8oxy2f

Steps to reproduce:
1. Create a table with multiTemplateDataRows
2. Add a table inside the expansion ng-container
 
 
#### Expected Behavior

Table should be rendered properly and in the expansion must be a table

#### Actual Behavior

Faced with duplicate column name error although it was not raised in Angular Material v8

#### Environment

- Angular: 9.0.1
- CDK/Material: 9.0.1
- Browser(s): Chrome 80.0.3987.116
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by andrewseguin** [comment]
Unfortunately we do not support nested tables. This is due to implementation limitations that we face from the framework
