### ISSUE TITLE
ScrollDispatchModule not in @angular/cdk/scrolling

### ISSUE THREAD

**Issue by laurent1** [angular/components#18569]
@angular/cdk version 9.0.1 does not export member ScrollDispatchModule.

`import { ScrollDispatchModule } from '@angular/cdk/scrolling';
`

**Comment by crisbeto** [comment]
The `ScrollDispatchModule` was removed since it has been deprecated for a while. If you're only using the `ScrollDispatcher`, you can use it directly without importing the module, otherwise you can import the `ScrollingModule` instead.
