### ISSUE TITLE
bug(table): Sticky elements not working in Edge

### ISSUE THREAD

**Issue by matthiaswelz** [angular/components#18562]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Correct rendering

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/8686683/74941471-59fafa00-53f3-11ea-9cfa-315801aeb2a6.png)

![image](https://user-images.githubusercontent.com/8686683/74941503-6bdc9d00-53f3-11ea-80c0-c5719f6b3f6d.png)

![image](https://user-images.githubusercontent.com/8686683/74941521-74cd6e80-53f3-11ea-8c90-f65696939fe6.png)

#### What are the steps to reproduce?

Visit https://material.angular.io/components/table/overview with Edge

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material:
9.0.1

Browser:
Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

**Comment by andrewseguin** [comment]
Closing since this affects pre-Chromium Edge which we do not support
