### ISSUE TITLE
Possible injector-memoryleak

### ISSUE THREAD

**Issue by kbarendrecht** [angular/components#18560]
I've encountered a possible memoryleak with `angular/cdk` and `angular/core`. I figured this was the spot to post this issue since it has to do with the `overlay`, `componentportal` and `portalinjector`.

#### Reproduction

https://github.com/kbarendrecht/injector-loop-repro
*I tried stackblitz first, but it seems like it's not possible to use ivy there yet.

### Structure
- `AppComponent` attaches a PanelComponent to a `cdk/overlay` and injects `HelloWorldComponent`.

- `PanelComponent` tries to render `HelloWorldComponent` inside a `ngComponentOutlet`.

### Steps to reproduce:
Step 1: Run `ng serve` and open the browser console

Step 2: Uncomment the `p` tag with `ngModel` binding

Step 3: Observe the `PanelComponent.createInjector()` being triggered continuously
 
#### Expected Behavior

What behavior were you expecting to see?

_The component being rendered._

#### Actual Behavior

What behavior did you actually see?

_The component wasn't rendered._

#### Environment

- Angular:
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
- CDK/Material:
    "@angular/cdk": "^9.0.1",
- Browser(s):
Brave - Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows 10 Pro 1909 - 18363.657

**Comment by crisbeto** [comment]
The problem is that you have a call to `createInjector` inside the view (`*ngComponentOutlet="component, injector: createInjector()"`). This means that any time Angular runs change detection, `createInjector` will run and will return a new injector which will be passed to the `injector` property.
