### ISSUE TITLE
 Mat Paginator is not working properly along when used conditional rendering (*ngIf) on the outer div. 

### ISSUE THREAD

**Issue by boorac** [angular/components#18571]
#Reopening 

Same issues, locked by angular-automatic-lock-bot:

https://github.com/angular/components/issues/10205

https://github.com/angular/components/issues/15966

https://github.com/angular/components/issues/10474

https://github.com/angular/components/issues/11692

Is this really a bug, and if not what is the expected way of solving this?

**Comment by andrewseguin** [comment]
This isn't a bug, just that you cannot access `ViewChild` elements before view initialization if they have  a structural directive applied, e.g. ngIf, ngFor. Instead you need to wait until after view init to use them or assign them to a variable
