### ISSUE TITLE
MatBottomSheet adds style to HTML root tag <html>

### ISSUE THREAD

**Issue by rohitmishra98** [angular/components#18572]
#### Bug, feature request, or proposal:
Mat Bottom Sheet adds a style `top:-${scrolled length of the page} px; ` to the <html></html>

#### What is the expected behavior?
Should no manipulate the root Html tag.

#### What is the current behavior?
changes style values in html root.

#### What is the use-case or motivation for changing an existing behavior?
When opening the bottom sheet the Html gets `-random px` and shifts to top so user sees a blank screen behind the bottom sheet.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

These are my angular dependencies
` "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",`
appears on chrome 80.*
MACOS,Windows,Ubuntu.

**Comment by crisbeto** [comment]
This is used to block scrolling on the page while the bottom sheet is open.

**Comment by rohitmishra98** [comment]
but breaks the UI by adding a calculated negative top to root html,
user cant see the background

**Comment by crisbeto** [comment]
There might be some other styles in your app that are throwing it off. You can also disable the scroll blocking by passing in a different scroll strategy:

```
constructor(private _bottomSheet: MatBottomSheet, private _overlay: Overlay) {
  _bottomSheet.open(SomeComponent, {
    scrollStrategy: _overlay.scrollStrategies.noop()
  });
}
```
