### ISSUE TITLE
Change Detection runs multiple times with material components

### ISSUE THREAD

**Issue by tp1906** [angular/components#18570]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://components-issue-is9tqp.stackblitz.io/

Steps to reproduce:
1. Click on native select and view console and you'll notice there is no output of "Checking the view"
2. Click on the material select and view console and you'll notice there are 6 outputs of "Checking the view",
 
#### Expected Behavior

What behavior were you expecting to see?
I would expect there to be a single change detection if the value changed or when the drop-down closes.  There should not be multiple change detections when you click on the mat-select.

#### Actual Behavior

What behavior did you actually see?
Change detection is called 6 times when you click on mat-select without changing the selection.  When you click outside the mat-select, change detection is called 8 times.  

#### Environment

- Angular:  8.2.8
- CDK/Material: 8.2.3
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MRMokwa** [comment]
That's probably 'cause you have a function in your template (`get runChangeDetection()`). 
When you click the mat-select, it has to create it's options components, and angular has to trigger change detection to resolve your template function, since it's not pure.
You should avoid using functions in the template, and instead go with pipes, if it's an option.

**Comment by crisbeto** [comment]
@MRMokwa is correct. Furthermore, there are multiple events that happen during the select's opening sequence which may need to trigger change detection. The fact that change detection is running, doesn't necessarily mean that anything is updating in the DOM. Closing since this works as expected.
