### ISSUE TITLE
Can angular be added to the code sample at least?

### ISSUE THREAD

**Issue by alialtun14** [angular/components#18580]
The following page can be accessed via github angular / component readme.md. I know that teams within Google make independent decisions. Can angular be added to the code sample at least?

https://material-components.github.io/material-components-web-catalog/#/component/card?type=basic

**Comment by jelbourn** [comment]
We're working on mdc-based components in `@angular/material-experimental` right now- once they're ready to be used from the main `@angular/material` package, we'll do more to highlight them.
