### ISSUE TITLE
[MatTree] Missing documentation that MatButtonModule is needed

### ISSUE THREAD

**Issue by beyerleinf** [angular/components#18586]
#### Documentation Feedback

While using the MatTree today I came across an issue where there were no styles applied to the MatTree. My app was running inside Electron.
After a while, I figured out that I needed to add the MatButtonModule to my app. You can check out the issue in [this StackBlitz](https://stackblitz.com/edit/angular-mat-tree-button-issue?file=src/app/material-module.ts) I forked from the original example.

**Affected documentation page:** [https://material.angular.io/components/tree/overview](https://material.angular.io/components/tree/overview)

**Comment by lukaonik** [comment]
Hi,
The nature of MatTree, is that we are passing components from the outside module, so do we need actually to hint, that we want to import the modules for these components?

**Comment by beyerleinf** [comment]
Hey,
to be honest, now that some time has passed I don't know why I didn't get this a year ago... 😄
