### ISSUE TITLE
AutoCompelete popup div doesnot on top div

### ISSUE THREAD

**Issue by ProfFL028** [angular/components#18591]
i'm integrating material with primeng, when i use primeng's popupdialog for edit some entity.
autocomplete's popup div will show at first time, but hidden below the dialog after the dialog reopen.

**Comment by ProfFL028** [comment]
because .cdk-overlay-container z-index use 1000 by default. and primeng's popup dialog‘s z-index begin with 1000 and automate add by 1 after reopen....
i have to change indigo-pink.css file, make all z-index to 10000 instead

**Comment by crisbeto** [comment]
In general we don't make change to get Material to work with other libraries, because it wouldn't be sustainable. As you said, you can bump up the `z-index` yourself to make it work.
