### ISSUE TITLE
[bug] z-index on autocomplete

### ISSUE THREAD

**Issue by indraraj26** [angular/components#18605]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
![image](https://user-images.githubusercontent.com/23274631/75219511-f9890580-57c2-11ea-9f9a-0e7101ffd483.png)

 
#### Expected Behavior
provider better way to override z-index depend upon application

#### Actual Behavior
it is overlapping other elements on dom

#### Environment

- Angular: 
- CDK/Material: 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. Overlays are set up so they open on top of everything else.

**Comment by indraraj26** [comment]
Hi @crisbeto , 

Scenario:  
Step 1: I have set cdk overlay z-index to 1 for every components with that it will not overflow to my navbar. 
Step 2: In that component, I have ngbModal from ng-bootstrap which has greater z-index than cdk overlay as i changed the cdk overlay z-index: 1
Step 3: Now i cant see MatAutoComplete dropdown in ngbModal.

Expected: Can we have option in matautocomplete to set z-index dynamically for cdk overlay.
