### ISSUE TITLE
cdkTrapFocus does not work in lazy mat-menu content

### ISSUE THREAD

**Issue by twjacobsen** [angular/components#18602]
#### Reproduction

https://stackblitz.com/edit/mat-menu-lazy-cdk-trap-focus?file=src/app/app.component.html

Steps to reproduce:
1. Open the menu, tab through the inputs. It'll stop at the last input. Tabbing backwards will start focusing out of the trap (the trigger button, other elements in StackBlitz)
2. Comment out the `ng-template`s to disable lazy loading, see that the focus trap now works
 
 
#### Expected Behavior

I'd expect it to trap the focus.

#### Actual Behavior

Focus is not trapped.

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Firefox 73, Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS Catalina

**Comment by crisbeto** [comment]
We have a PR that should solve this issue (https://github.com/angular/components/pull/16407), but last time we tried to get it merged it broke some tests in Google.

**Comment by crisbeto** [comment]
The related PR has been merged so this should be resolved now.
