### ISSUE TITLE
CDK -> FlexibleConnectedPositionStrategy does not work with SVG elements

### ISSUE THREAD

**Issue by mirceapop89** [angular/components#18618]
#### Reproduction

https://stackblitz.com/fork/cdk-overlay-issue

Steps to reproduce:
1. Hover the red circle.
 
#### Expected Behavior

The overlay should have been opened to the right of the circle, as it was configured so.

#### Actual Behavior

The overlay was opened in the top left corner of the page.

#### Environment

- Angular: 8.2.14 and 7.2.15
- CDK/Material: 8.2.3 and 7.3.7
- Browser(s): Chrome 80.0.3987.106 but older versions too
- Operating System: macOS and Ubuntu

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/components/pull/18595.
