### ISSUE TITLE
overlay: conflicting with Angular Elements 

### ISSUE THREAD

**Issue by Gaurav-enest** [angular/components#18616]
#### Detailed Reproduction Steps: 
1. Create two apps 
**A: Angular elements** 
**B: Normal angular app**
2. Convert app A to a angular element's app
https://angular.io/guide/elements
3. Use app **A** into **B** using element selector
4. Add mat menu into app **B (consuming app)**
https://material.angular.io/components/menu/overview

5. See mat menu not showing any content 

Note : Mat menu working fine in app **B** if I'm not using custom elements 

### What is the current behavior?
Clicking on mat menu not showing anything 

### What is the expected behavior?
Clicking on mat menu should show the menu content. 
 
### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 8.2.14
- AngularJS Material: 8.2.14
- OS: windows
- Browsers: Chrome 79.0.3945.130

**Comment by Splaktar** [comment]
Do you have a StackBlitz or GitHub reproduction that you can link here?

**Comment by Gaurav-enest** [comment]
@Splaktar Let me create GitHub repo will back to you soon. thanks

**Comment by Gaurav-enest** [comment]
@Splaktar Upgrading to angular version 9 solved my issue .

**Comment by manoharnv** [comment]
> Do you have a StackBlitz or GitHub reproduction that you can link here?

Here is a sackblitz link which reproduces the issue.

https://stackblitz.com/edit/angular-nr58ab-tbu38h

The angular app has two elements:
1. menu -> this is defined in the host application
2.  "open" button which opens a mat modal on clicking it. this one is created using angular elements  (js for this angular element is imported in index.html)

Problem:
scenario 1: click on menu -> click on "open" button -> dismiss the modal -> click on menu again -> it will not open -> but click on "open" button -> it opens the modal

scenario 2: click on "open" buttton -> dismiss the modal -> click on menu -> the menu opens -> click on "open" button -> modal doesn't open -> click on menu -> it opens.
