### ISSUE TITLE
MatInputHarness.getName() fails with MatInput and ngModel

### ISSUE THREAD

**Issue by bampakoa** [angular/components#18624]
#### Reproduction
I am trying to get the name of a `MatInput` control which is bound to a component property `name` as:
`<input matInput [name]="name" [(ngModel)]="model">`

I am using the `getName()` method of `MatInputHarness` as: 

```
const input = await loader.getHarness(MatInputHarness);
expect(await input.getName()).not.toBe('')
```

but the expectation fails. If I remove the `ngModel` directive, the test passes successfully.

https://stackblitz.com/edit/components-issue-atwks1
 
 
#### Expected Behavior

The test should pass

#### Actual Behavior

The test fails

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I looked into it quickly and I managed to reproduce it. It looks like the issue is that when `ngModel` is set, the native DOM `name` property isn't being set on the `input` element.

**Comment by bampakoa** [comment]
@crisbeto if we inspect the element using dev tools it looks like the `name` property is set correctly to the `test` value. Or is this the attribute that I see over there?

![image](https://user-images.githubusercontent.com/7170892/76105191-2916e980-5fdd-11ea-8ef2-695587feb054.png)

**Comment by crisbeto** [comment]
Here's what I'm trying. In my case the `input` doesn't have a `name` attribute or `name` property. https://stackblitz.com/edit/angular-gfc66v

**Comment by bampakoa** [comment]
@crisbeto you are right! I inspected the second input of my example that does not have `ngModel`, sorry about that. So, what do you think? Is this a bug with `ngModel`?
