### ISSUE TITLE
Problem when same id on check box in different component

### ISSUE THREAD

**Issue by moronyoh** [angular/components#18621]
#### Reproduction

Use StackBlitz to reproduce your issue: [StackBlitz](https://stackblitz.com/edit/angular-material-ecznnk)

Steps to reproduce:
1. Click on 'Open dialog' button
2. Click on check box and see that the check box in the dialog is not working but the check box in the first view is toggled
3. Focus the check box with the key 'Tab' and then type 'Space' and this time the check box in the dialog is working.
 
 
#### Expected Behavior

The two check box should be isolated, even if they have the same id, because they are in two different component.

#### Actual Behavior

The checkbox in the dialog is linked to the other one.

#### Environment

- Angular: 7.2.16
- CDK/Material: 7.3.7
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Fedora

**Comment by Totati** [comment]
It's not a problem with angular material, you can't isolate id-s. When you give id to anything by hand you have to pay attention. If you remove your id-s, the mat-checkbox generates unique id-s.

**Comment by crisbeto** [comment]
@Totati is correct. If you're giving it custom IDs, you should take care that they aren't duplicated.
