### ISSUE TITLE
mat icon create bolder svg than original 

### ISSUE THREAD

**Issue by Andrew3005** [angular/components#18625]
![image](https://user-images.githubusercontent.com/33102765/75357540-34ba3000-58ba-11ea-8b06-a2765efbcc9e.png)
right SVG - background image in div
left SVG - same SVG in mat icon (added by matIconRegistry)

left SVG has to be the same, but mat icon add bold lines in SVG, or how it works - I don't understand

**Comment by crisbeto** [comment]
Can you post the original SVG? Otherwise it's impossible to investigate.

**Comment by Andrew3005** [comment]
@crisbeto how I can add a SVG in comment?

**Comment by crisbeto** [comment]
I mean the source code of the SVG.

**Comment by Andrew3005** [comment]
<svg width="26" height="25" viewBox="0 0 26 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.7717 17.5024C17.4929 17.5024 17.2668 17.729 17.2668 18.0082C17.2668 18.2874 17.4929 18.5141 17.7717 18.5141C18.0504 18.5141 18.2766 18.2874 18.2766 18.0082C18.2766 17.729 18.0504 17.5024 17.7717 17.5024Z" fill="#545A66"/>
<path d="M13.4297 8.59937C13.4297 8.31996 13.2035 8.09351 12.9248 8.09351C12.6461 8.09351 12.4199 8.31996 12.4199 8.59937C12.4199 8.87858 12.6461 9.10523 12.9248 9.10523C13.2035 9.10523 13.4297 8.87858 13.4297 8.59937Z" fill="#545A66"/>
<path d="M8.07812 18.5141C8.35679 18.5141 8.58299 18.2874 8.58299 18.0082C8.58299 17.729 8.35679 17.5024 8.07812 17.5024C7.79945 17.5024 7.57324 17.729 7.57324 18.0082C7.57324 18.2874 7.79945 18.5141 8.07812 18.5141Z" fill="#545A66"/>
<path d="M25.5497 20.9182L22.8202 19.7032V8.59967C22.8202 8.3993 22.7005 8.21375 22.5101 8.13273L13.4297 4.21961V0.505863C13.4297 0.226453 13.2035 0 12.9248 0C12.646 0 12.4199 0.226453 12.4199 0.505863V4.21961L3.3395 8.13273C3.15904 8.20782 3.02947 8.391 3.02947 8.59967V19.7032L0.299992 20.9182C0.045188 21.0318 -0.0695921 21.3306 0.0436103 21.5859C0.156024 21.8396 0.453427 21.957 0.710006 21.8428L3.5375 20.5841L12.7254 24.5434C12.8469 24.5958 12.9954 24.599 13.1244 24.5434L22.3121 20.5841L25.1396 21.8428C25.3972 21.9574 25.694 21.8387 25.806 21.5859C25.9192 21.3306 25.8045 21.0318 25.5497 20.9182ZM12.4199 5.32104V6.57622C12.4199 6.85543 12.646 7.08208 12.9248 7.08208C13.2035 7.08208 13.4297 6.85543 13.4297 6.57622V5.32104L21.0375 8.59967L12.9248 12.0959L4.81211 8.59967L12.4199 5.32104ZM6.69415 18.625C6.58075 18.3697 6.28236 18.2549 6.02776 18.3682L4.03902 19.2536V9.36775L12.4199 12.9795V23.3106L4.79456 20.0245L6.43777 19.2929C6.69258 19.1793 6.80736 18.8803 6.69415 18.625ZM13.4297 23.3106V12.9795L21.8104 9.36775V19.2536L19.8219 18.3684C19.5669 18.2549 19.2687 18.3697 19.1555 18.6252C19.0423 18.8805 19.1571 19.1793 19.4119 19.2929L21.0551 20.0245L13.4297 23.3106Z" fill="#545A66"/>
</svg>

**Comment by Andrew3005** [comment]
I have removed `<` and `>`

**Comment by Andrew3005** [comment]
@crisbeto 
what I want to achieve: change SVG color by css
by it is not working. so I have changed SVG stroke: currentColor;
that is why it is bolder

what is other way to change color for custom SVG?

**Comment by Andrew3005** [comment]
in CSS I done
SVG { path { fill: currentColor } } (globally)

and works as expected

is this way correct? to change color for SVG

**Comment by Andrew3005** [comment]
no, it is not a correct way
because SVG can contain path, line, circle, line, rect elements 
and if to set color for them - it wont be SVG as we expect

any solutions?

**Comment by jelbourn** [comment]
@Andrew3005 here's a stackblitx with your icon working normally:
https://stackblitz.com/edit/angular-bfbwjj?file=src%2Fapp%2Ficon-svg-example.ts

The extra boldness is probably coming from some css in your application.
