### ISSUE TITLE
mat-list-option tabindex is -1 in mat-selection-list

### ISSUE THREAD

**Issue by ogiexela** [angular/components#18631]
#### Reproduction

Steps to reproduce:
1. https://stackblitz.com/angular/dlookbyxlng?file=src%2Fapp%2Flist-selection-example.html
2. try navigating the selection list using tab
 
 
#### Expected Behavior

users should be able to navigate each list option using tab

#### Actual Behavior

only the first option is reachable using tab

setting tabindex="0" is changed back to tabindex="-1"

#### Environment

- Angular: 9
- CDK/Material: 9.1.0
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by ogiexela** [comment]
same with mat-radio-button in mat-radio-group

**Comment by zelliott** [comment]
`MatSelectionList` is implemented as an ARIA `listbox`, and thus follows the [ARIA Listbox Design Pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox). The keyboard interaction specified in the design pattern is that arrow keys should move between list options, not tab. If `MatSelectionList` navigated between list options with tab, it would fail to follow the listbox keyboard interaction, and subsequently be a confusing widget for keyboard and screen reader users.

Essentially the same story for `MatRadioGroup`, take a look at the [ARIA Radio Group Design Pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton).

**Comment by crisbeto** [comment]
Closing since it's working as expected.
