### ISSUE TITLE
CdkScrollable inside Overlay

### ISSUE THREAD

**Issue by Mesya82** [angular/components#18635]
#### Reproduction

https://stackblitz.com/edit/components-issue-zkpvqj?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Use `cdk-virtual-scroll-viewport` inside `ng-template`
2. Load previously mentioned `ng-template` inside `Overlay`
 
 
#### Expected Behavior

`cdk-virtual-scroll-viewport` works as expected, having height, rendering items that can be scrolled

#### Actual Behavior

`cdk-virtual-scroll-viewport` has 0 height even though I tried to set `100%` for it and its parent. Also note, that the `wrapper` inside viewport has items rendered and they have correct height as well as wrapper itself.

#### Environment

- Angular: locally encountered with 8.2.14, stackblitz with 9.0.2
- CDK/Material: locally encountered with 8.2.3, stackblitz with 9.1.0
- Browser(s): Chrome 80.0.3987.106
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 18362.357

**Comment by crisbeto** [comment]
Your issue seems to be due to the element not having a `width`. If you set `width: 100%` on `cdk-virtual-scroll-viewport` it works correctly.
