### ISSUE TITLE
Angular 9: Importing Material Web Components from Library causes issues

### ISSUE THREAD

**Issue by AdrianMF** [angular/components#18649]
#### Reproduction
I have a stackblitz that has code, but I can't seem to get stackblits to support an Angular multi-project.
https://stackblitz.com/edit/angular-fbbf6q

Steps to reproduce:
1. Download the code from stackblitz link above
2. `npm run build && npm run start` - this will build the library then start the app which imports the library
3. Open browser to http://localhost:4200/  to see issues.
 
#### Expected Behavior

I would expect to see the Material components functioning properly.

#### Actual Behavior

I get limited functionality, some components display but with no animations or interaction, some components don't display at all
![Screen Shot 2020-02-28 at 11 22 30 AM](https://user-images.githubusercontent.com/1189227/75556271-a4483080-5a1c-11ea-8c9b-1190a8f33b4a.png)

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): FF
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

#### Notes
I was doing this same thing in Angular 8 with no problems, that is, exporting Material as web components from a library into an app. However with the Angular 9 upgrade it doesn't seem to be functioning completely.

**Comment by devversion** [comment]
Hello! I was trying this reproduction but everything worked as expected on my end. 

![image](https://user-images.githubusercontent.com/4987015/83340860-67226180-a2dd-11ea-81bc-18754462a4f4.png)

Is there anything special I'd need to try, or has this issue been resolved already in the StackBlitz? I'm closing this as there is nothing actionable of us right now, but we're happy to have another look. Please let us know!
