### ISSUE TITLE
compile error maximum call stack exeeded after upgrading from 9.1.0 to 9.0.0

### ISSUE THREAD

**Issue by rengert** [angular/components#18641]
I am trying to upgrade from 9 to 9.1. but i recieving the following message for all applications containing material. 

Compiling @angular/material/core : es2015 as esm2015

ERROR in Maximum call stack size exceeded

Other source before could be compiled

In my log i can find

Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015

the lines above. Unfortunately there is not detailed error message. Someone is facing same issue?

Thank you

**Comment by crisbeto** [comment]
Can you try installing 9.0.4 of the framework? I believe it's supposed to have a fix for this.

**Comment by rengert** [comment]
Well, the original issue has been fixed i guess. and seems working until the compile process ends with

Error when flattening the source-map
RangeError: Maximum call stack size exceeded

Now in button, formfield, suffix ....

**Comment by rengert** [comment]
Switching off the sourcemap generation solves the issue temporary
Thanks for you qick response, hopefully the sourcemap generation is fixed soon :)

**Comment by crisbeto** [comment]
Closing since this is something that should be fixed in core, if it hasn't been fixed already.
