### ISSUE TITLE
Accordion example broken - No provider found for DateAdapter

### ISSUE THREAD

**Issue by dexster** [angular/components#18646]
#### Documentation Feedback

The accordion example is not working. I'm assuming due to this console error

`
ERROR Error: MatDatepicker: No provider found for DateAdapter. You must import one of the following modules at your application root: MatNativeDateModule, MatMomentDateModule, or provide a custom implementation.`

https://material.angular.io/components/expansion/examples

**Comment by crisbeto** [comment]
Should've been fixed by https://github.com/angular/components/pull/18772.
