### ISSUE TITLE
perf(matIconRegistry): parse SVG iconsets on demand

### ISSUE THREAD

**Issue by mleibman** [angular/components#18644]
#### Summary

Named SVG icons are loaded by fetching **all** registered iconsets, parsing them by calling `_svgElementFromString(svgText)`, and then looking in the created DOM nodes for a matching icon. This approach results in a lot of up-front work, and can cause performance issues.

In a large and complex application, it is typical to register multiple large SVG iconsets (we have almost 10, with one over 700Kb!). Few of those icons are used right away, yet all of them are parsed synchronously on load.

(A similar issue has been reported in https://github.com/angular/components/issues/3828.)

#### Proposed improvement

One easy way to optimize it would be to fetch the iconsets as before, but instead of always parsing them by calling `_svgElementFromString(svgText)`, first check if the `svgText` contains the icon name, and if it doesn't, store `svgText` for the future in `SvgIconConfig`, but defer actual parsing until it is needed. The check for the presence of the icon in the iconset can be something as simple as doing `svgText.indexOf(iconName) !== -1`.

**Comment by crisbeto** [comment]
What are you using to register the icons? I can see the SVG being parsed ahead of time in the methods where you register the icon as a string (e.g. `addSvgIconSetLiteral`), but from what I can tell that shouldn't be happening in the ones where you register a URL.

**Comment by mleibman** [comment]
@crisbeto `MatIconRegistry.addSvgIconSet(url)`.
