### ISSUE TITLE
How to create mat-table dynamically

### ISSUE THREAD

**Issue by Gnorro** [angular/components#18658]
Hi

I read lots about adding mat-table columns dinamically but I couldn't do what I need.

I need to create a mat-table dynamically. This table can't have a fixed number of columns because that number depends on the results of an API call.

This is en example of what I get from API call:
```javascript
[
	{
		"productCode": "24.250.01",
		"Valvola": "22.398.14 ",
		"Kg": "40/60 ",
		"Taglia": "S ",
		"Variante": "Codice giacca ",
		"Colore": " COLORE_rosso_pieno Rosso "
	},
	{
		"productCode": "24.250.02",
		"Valvola": "22.398.14 ",
		"Kg": "50/70 ",
		"Taglia": "M ",
		"Variante": "Codice giacca ",
		"Colore": " COLORE_rosso_pieno Rosso "
	},
	{
		"productCode": "24.250.03",
		"Valvola": "22.398.14 ",
		"Kg": "Oltre 60 ",
		"Taglia": "L ",
		"Variante": "Codice giacca ",
		"Colore": " COLORE_rosso_pieno Rosso "
	}
]
```

The number of fields returned by API call is dynamic: In this example are 6 fields, but it can be also something like:
```json
{
		"productCode": "24.250.03",
		"Misura": "1",
		"Peso": "12",
		"Spessore": "3"
	}
```

What I need is to create a mat-table with 6 columns (for the 1st example) or 4 (for the 2nd example)
And then display data consequently

Can you help me please?

thanks

**Comment by MRMokwa** [comment]
There's an [guide in table overview (3. Define the row templates)](https://material.angular.io/components/table/overview#3-define-the-row-templates) that explains exactly what you need... 

> This means that by changing your column list provided to the rows, you can easily re-order and include/exclude columns dynamically.

Just change the "columnsToDisplay" as you wish.

```
<tr mat-header-row *matHeaderRowDef="columnsToDisplay"></tr>
<tr mat-row *matRowDef="let myRowData; columns: columnsToDisplay"></tr>
```

Also, this question is more suitable other community channels, like stackoverflow. Next time you could use:

- StackOverflow: https://stackoverflow.com/questions/tagged/angular-material2
- Gitter: https://gitter.im/angular/material2
- Google Groups: https://groups.google.com/forum/#!forum/angular-material2

**Comment by Gnorro** [comment]
Thanks
