### ISSUE TITLE
[a11y] Typo in @angular/cdk/a11y package breaks build

### ISSUE THREAD

**Issue by flash-me** [angular/components#18652]
#### Reproduction

Steps to reproduce:
1. `npm i @angular/cdk`
2. Open node_modules/@angular/cdk/bundles/cdk-a11y.umd.js
3. There you will find the following piece of code:

`...((global.ng = global.ng || {}, global.ng.cdk = global.ng.cdk || {}, global.ng.cdk.a11Y = {}), global.ng.common, ....`
 
Especially the UMD ID `global.ng.cdk.a11Y` is wrong, since every other module of the @angular/cdk or @angular/material framework looks for an UMD ID of `global.ng.cdk.a11y` (small writte 'y')
 
#### Expected Behavior

What behavior were you expecting to see?

UMD ID of `global.ng.cdk.a11y`

#### Actual Behavior

What behavior did you actually see?

UMD ID of `global.ng.cdk.a11Y`

#### Environment

- CDK/Material: 9.1.0

**Comment by crisbeto** [comment]
I can reproduce this against our local build, but from what I can tell it's not a typo, because we're passing in the correct name into Rollup. My guess is that something in Rollup uppercases it when it sees the number in the name.

**Comment by flash-me** [comment]
Alright, I'll issue this on @rollup. This issue can be closed from imo! 
Thanks for your time @crisbeto :) 

cheers
flash :zap:

**Comment by crisbeto** [comment]
Let's keep it open for now, there might be a way to work around it on our end. It's surprising that we haven't heard about it until now.

**Comment by flash-me** [comment]
There is another issue with the naming, when it is written with a dash. But against the decision to close the issue, imho this is not specific to `@angular/components`. 

Could be related to @rollup aswell. I'm not sure. I'll try to dig in more this WE, if I can find some time.

cheers
flash :zap:

**Comment by devversion** [comment]
@flash-me Thanks for the issue! I've looked into it and it looks like a bug in `@angular/bazel`. I've created a fix for it in https://github.com/angular/angular/pull/35792.
