### ISSUE TITLE
MatAutocomplete selection option event order

### ISSUE THREAD

**Issue by raygig** [angular/components#18650]
#### Feature Description

The current order of events when selecting an option from MatAutocomplete is as follows:

1. Update the NgModel
2. Bring focus to the autocomplete
3. Emit select event which calls @Output() optionSelected

This is the code which executes this logic.

```
    MatAutocompleteTrigger.prototype._setValueAndClose = 
    function (event) {
        if (event && event.source) {
            this._clearPreviousSelectedOption(event.source);
            this._setTriggerValue(event.source.value);
            this._onChange(event.source.value);
            this._element.nativeElement.focus();
            this.autocomplete._emitSelectEvent(event.source);
        }
        this.closePanel();
    };
```

I am proposing to call the focus() event after this.autocomplete._emitSelectEvent(event.source); 

The issue is if you want to test the current selected model value in the focus() event it will be incorrect because the setting of the model happens after focus is called.

#### Use Case

In the focus event we are testing if the model value is blank and if so then open the panel to give suggested search items.

**Comment by crisbeto** [comment]
Rather than using the `focus` even, couldn't you use the `optionSelected` event instead? It's not a big deal to change this, but I'm trying to understand what the use case is.

**Comment by raygig** [comment]
We are trying to build a suggestion feature which is activated when the autocomplete is focused and the ngmodel is null. 

Currently this breaks with this scenario. 

1. Autocomplete has ngmodel===null
2. The user focuses the autocomplete
3. Suggestions are displayed
4. User searches ands selects an option
5. The suggestion options display again

#5 happens because the focus event triggers before ngmodel is set.
