### ISSUE TITLE
MAT_LABEL_GLOBAL_OPTIONS deprecated but docs still show it

### ISSUE THREAD

**Issue by pburkindine** [angular/components#18678]
#### Documentation Feedback

https://material.angular.io/components/form-field/overview

...still points to MAT_LABEL_GLOBAL_OPTIONS for setting `float`, but the compiler indicates this token is deprecated in favor of MAT_FORM_FIELD_DEFAULT_OPTIONS

**Comment by devversion** [comment]
Thanks for the issue. I've sent a PR that fixes this documentation issue: #18690

**Comment by pburkindine** [comment]
LGTM thanks
