### ISSUE TITLE
Change progress bar value from component instance

### ISSUE THREAD

**Issue by frct1** [angular/components#18676]
#### Reproduction

Steps to reproduce:
1.  Create progress bar dynamically through ComponentFactoryResolver
2. Try to change value of progress bar instance
 
 
#### Expected Behavior
Changing value and progress bar mode through component instance

#### Actual Behavior
Value not changing (without any errors). When changing mode of progress bar through component instance also not working. Looks like it is just takes only first defined property values.

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0-rc.10
- Browser(s): Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It sounds like you're not triggering change detection so it can't pick up the change, but it's hard to tell without seeing the code.

**Comment by frct1** [comment]
@crisbeto 
Hi, i've tried to calling change detection but without any result.
Is there available stackblitz template with latest Angular Material packages ? Didn't found it at issue creating moment 😞

**Comment by crisbeto** [comment]
If you go to [any of the examples in the docs site](https://material.angular.io/components/progress-bar/overview), you can click the "Edit" icon which will create a Stackblitz from the example.

**Comment by frct1** [comment]
Oh, got it, thank you so much.
Will create example shortly

**Comment by frct1** [comment]
Here we go: 
ViewChild case (reference to component #bar): https://stackblitz.com/edit/angular-xu8tmk?file=src%2Fapp%2Fprogress-bar-determinate-example.ts

ng-container case: https://stackblitz.com/edit/angular-xu8tmk-rqfimd?file=src%2Fapp%2Fprogress-bar-determinate-example.ts

**Comment by frct1** [comment]
@crisbeto 
Hi, still assigned `needs clarification` label on this issue.
Do i need to provide more info ?

**Comment by ChelloApps** [comment]
I think I'm seeing exactly the same thing here, I've been building a new Angular 9 app and have just 3 hours trying to get the progress bar to work!  I gave up trying t get ViewChild to work so resorted to binding the [value] but still no progress bar!!

**Comment by frct1** [comment]
@ChelloApps 
Yes that's totally unexpected behavior. But devs still keep "needs clarification"...
