### ISSUE TITLE
Drag and Drop: Distinguish a click event from a drag event

### ISSUE THREAD

**Issue by saunandrea** [angular/components#18677]
#### Feature Description

I came to the Angular drag and drop from Dragula which supports distinguishing click from drag. 

Dragula: "Click or Drag! Fires a click when the mouse button is released before a mousemove event, otherwise a drag event is fired. No extra configuration is necessary."
https://bevacqua.github.io/angularjs-dragula/

Maybe this already exists but I couldn't find any documentation indicating as much.

#### Use Case

While dragging allows you to add the item in a specific location, clicking would just add the item to the end of the list.

**Comment by crisbeto** [comment]
By default the CDK is set up so that dragging won't start unless the user puts their pointer down and drags for at least 5 pixels so you should be able to bind a `click` event directly. You can tweak the threshold using `CDK_DRAG_CONFIG` injection token.

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback in a while.
