### ISSUE TITLE
MomentJS cannot be optimized and the moment-date-adapter is causing increased bundle size

### ISSUE THREAD

**Issue by realharry** [angular/components#18683]
#### Reproduction

Steps to reproduce:
1. Add a dependency on `MatMomentDateModule` on your angular app. 
2. Build the app with `ng build --prod`.
3. Notice the increase in the output bundle size. 

Screenshot of webpack-bundle-analyzer of the main bundle (built with `--stats-json`):

![Stats - Screenshot from 2020-03-02 19-10-41](https://user-images.githubusercontent.com/28793852/75739666-5cded000-5cba-11ea-9d69-a7f8c75ad442.png)

#### Expected Behavior

Addition of a "simple" widget should not increase the output bundle size dramatically.

#### Actual Behavior

Huge increase in the bundle size, on the order of a few hundred kilobytes. (Over 338kb added by moment.js alone, in my example.)

#### Environment

- Angular: 9.0.4
- CDK/Material: 9.1.0
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

**Comment by marko164** [comment]
It would be great if `MatMomentDateAdapter` could work with [moment-mini](https://www.npmjs.com/package/moment-mini)

**Comment by eduardocereto** [comment]
moment.js unfortunately doesn't do well with tree shaking. Here are some extra info on alternatives that do.

https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by devversion** [comment]
Thanks for this issue. We are aware of the limitations with MomentJS. We should really document the bundle size implications with the moment date adapter. Additionally it might be good to provide a better integrated date adapter (one that can be more optimized).

We have various proposals for other date adapters (such as `date-fns` or `day.js`)

**Comment by Splaktar** [comment]
Related feature request for date-fns Adapter: https://github.com/angular/components/issues/10278. PRs wanted for this.

**Comment by jelbourn** [comment]
Tracking providing official alternatives to moment in #20599
