### ISSUE TITLE
Nested stepper - When i click on one step it should show child steps in same line

### ISSUE THREAD

**Issue by Nikhilrj22** [angular/components#18689]
#### What are you trying to do?

Nested stepper - When i click on one step it should show child steps in same line and child steps should have grouped in container
![image(1)](https://user-images.githubusercontent.com/61736540/75769268-e5697900-5d6b-11ea-9e59-185b8e89297b.png)

#### What troubleshooting steps have you tried?

1. I tried to include mat-horizontal-stepper inside one more mat-horizontal-stepper, but this didnt come in single line.

2. Child steps gets added to the parent stepper, which is wrong
  
#### Environment

- Angular: 8
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Nested steppers should be fixed by https://github.com/angular/components/pull/18458.
