### ISSUE TITLE
Layout issues with CDK BreakpointObserver when used with Angular SSR 

### ISSUE THREAD

**Issue by realharry** [angular/components#18680]
#### Reproduction

Steps to reproduce:
1. Create an angular app. Use BreakpointObserver to dynamically adjust layouts based on the window size.
2. Enable Angular SSR.
3. Load an app and observe that the initial server-loaded layout is different from the client-based layout.
 
 
#### Expected Behavior

It'll be great if the server-side rendering and client-side rendering use the same layout.

#### Actual Behavior

Server-side rendered page layout is completely different from the client-side layout. I'm not sure if there will be any solution for this. But, unfortunately, the current implementation essentially makes server side rendering incompatible with BreakpointObserver. That is, if you wanna use SSR, you cannot use BreakpointObserver. Or, if you use BreakpointObserver, you cannot really use SSR (because of the abrupt layout change during the page load).

#### Environment

- Angular: 9.0.4
- CDK/Material: 9.1.0
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

**Comment by jelbourn** [comment]
Yes, you fundamentally can't use media queries on the server. `BreakpointObserver` is a purely client-side utility.
