### ISSUE TITLE
MAT_LABEL_GLOBAL_OPTIONS deprecated but float doesn't work w/o

### ISSUE THREAD

**Issue by pburkindine** [angular/components#18681]
#### Reproduction

https://stackblitz.com/edit/float-always

Steps to reproduce:
1. label should be floated but isn't

After bumping to material 9.1.0 from 9.0.1, MAT_LABEL_GLOBAL_OPTIONS is listed in lint as deprecated in favor of MAT_FORM_FIELD_DEFAULT_OPTIONS; however this does not work as expected at least for the `float` default previously set up for label.

Replacing:
```
{
      provide: MAT_LABEL_GLOBAL_OPTIONS,
      useValue: { float: 'always' }
}
```
by adding float to MAT_FORM_FIELD_DEFAULT_OPTIONS...
```
    {
      provide: MAT_FORM_FIELD_DEFAULT_OPTIONS,
      useValue: { appearance: 'outline', float: 'always' }
    },
```

... does not result in a floating placeholder.

**Comment by devversion** [comment]
I think the issue here is that the option `float` needs to be `floatLabel`. Our changelog mentions:

> MAT_LABEL_GLOBAL_OPTIONS exported in @angular/material/core is deprecated. Use MAT_FORM_FIELD_DEFAULT_OPTIONS from @angular/material/form-field. Note that the property float is now matching the input name floatLabel.

Let me know if that helps. Thanks!

**Comment by pburkindine** [comment]
Oops!  Sorry I missed that.
