### ISSUE TITLE
mat-datepicker behaviour

### ISSUE THREAD

**Issue by bl9l** [angular/components#18692]
Hi.
There are two bugs.

https://stackblitz.com/edit/components-issue-pv5czm?file=src%2Fmain.ts
 
 
#### Expected Behavior

1. I expect that `mat-datepicker` will not change my manual input data
2. Open the datepicker without bluring the input

#### Actual Behavior

1. In russian locale we use `dd.mm.yyyy format`. And when I try to type the date myself, sometimes it swaps the day and the month. For instance if you type `12.11.2003` , after the blur it changes to `11.12.2003`.
2. If I will try to open the datepicker on the focus event like this `(focus)="picker.open()"`, it will blur the input and `required` error will appear.

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by domsew** [comment]
Ad 1: You should read [this](https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings).
[Looking at the source](https://github.com/angular/components/blob/9343d08524c5ff6968f9fc18d9311d73a785dc39/src/material/core/datetime/native-date-adapter.ts#L186-L193) Material uses `Date.parse()` method, which treats first digit as month.
You can override this method or use `MatMomentDateModule` (recommended).

**Comment by bl9l** [comment]
@domsew Thank You. It is my fault.

**Comment by bl9l** [comment]
But what about the second issue? I have already read lots of other issues about it. But none of them has mention about the validators, like `Validators.required`.

**Comment by domsew** [comment]
I would not say that this is a bug. I think that this is expected behaviour, because `MatDatepicker` listens to user interactions, so it needs to have focus when is created. Think about whether you really need open datepicked on input focus. Maybe `MatDatepickerToogle` is sufficient?

If you really want it, you could try to write custom validator which will check if datepicker is opened.

**Comment by bl9l** [comment]
I got it. Thank you

**Comment by rochapablo** [comment]
`{ provide: MAT_DATE_FORMATS, useValue: dateFormats }` seems to make no change...

adding

```
{
  parse: {
    dateInput: ['DD/MM/YYYY'],
  },
  display: {
    dateInput: 'DD/MM/YYYY',
    monthYearLabel: 'MM/YYY',
    dateA11yLabel: 'DD/MM/YYYY',
    monthYearA11yLabel: 'MM/YYY',
  },
}
```

it still changing the format after the input change where `DD/MM/YYYY` it will become `MM/DD/YYYY`

**Comment by bl9l** [comment]
@rochapablo [the propper solution](https://github.com/angular/components/issues/18692#issuecomment-594166479)
