### ISSUE TITLE
Is there any feature in moveToDate programmatically in mat-calendar. 

### ISSUE THREAD

**Issue by ankushgoyal27** [angular/components#18694]
#### Feature Description
In mat-calender, move to particular date or month programatically would be great. 
#### Use Case
I am using mat-calendar in my application as inline calendar. 
Having dropdown to select the month and date. Having date modal button alongside the dropdown. 

If user select any date from dropdown, then click on date modal button. 
Date modal open with the selected value. 

But the calendar month is displayed with the today's date and month. 

#### Expected:
In the date modal calendar should display the selected month and date from the dropdown.

**Comment by domsew** [comment]
Try
`this.calendar.activeDate = this.calendar.selected = YOUR_DATE;`

**Comment by ankushgoyal27** [comment]
Its working Dom. Thanks for your help
