### ISSUE TITLE
mat-slide-toggle using incorrect text color in dark-theme

### ISSUE THREAD

**Issue by hfournier** [angular/components#18701]
#### Reproduction

Steps to reproduce:
1. Add mat-slide-toggle to menu in dark-theme

```
<mat-menu #userMenu="matMenu">
  <button mat-menu-item (click)="logout()">Logout</button>
  <mat-slide-toggle
     [(ngModel)]="darktheme"
     (change)="changeTheme($event)">Dark Theme
  </mat-slide-toggle>
</mat-menu>
``` 
 
#### Expected Behavior

What behavior were you expecting to see?
Expect mat-slide-toggle text to be white in dark-theme

#### Actual Behavior

What behavior did you actually see?
mat-slide-toggle text is black in dark-theme

![image](https://user-images.githubusercontent.com/13371332/75838936-3d0fe080-5d7c-11ea-956d-e611823f1900.png)

#### Environment

- Angular: 9.0.4
- CDK/Material: 9.0.1
- Browser(s): Firefox, Edge (chromium)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
When I tested this using the MDC based slide-toggle and menu components which are coming soon in v15, the text color is correct
