### ISSUE TITLE
TestHarness API locatorFor is not working for ShadowDOM Element

### ISSUE THREAD

**Issue by VijayanRamachandran** [angular/components#18702]
#### Reproduction

Below is the code snippet where we created an Angular Element and Written TestHarness for that Angular Element.

**angular-element-example.component.html**

![Tag](https://user-images.githubusercontent.com/25306014/75859613-52d6e180-5e20-11ea-8b0f-128f59a87f19.png)

**angular-element-example.component.ts**
 
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  templateUrl: './angular-element-example.component.html',
  styleUrls: ['./angular-element-example.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom
})

export class AngularElementExampleComponent 
{
  Message = "Message from AngularElement";
  constructor() {   }  
}

**AngularElementTestHarness.ts**

import { ComponentHarness } from '@angular/cdk/testing';

export class AngularElementTestHarness extends ComponentHarness
{    
    static hostSelector = 'angular-element-example';    
    private heading1 = this.locatorFor('h1');
    public async headingText(): Promise<string>  
    {
        const trigger = await this.heading1;
        return (await trigger()).text();
    }
}

Below is the Element Hierarchy in Inspect Tool.

![ElementHierarchy](https://user-images.githubusercontent.com/25306014/75859741-96c9e680-5e20-11ea-9c4d-7e1e41bf6eca.png)

#### Actual Behavior

When I try to run below test we are getting error as

**Error: Failed to find element matching one of the following queries: 
(TestElement for element matching selector: "h1")**

![Test](https://user-images.githubusercontent.com/25306014/75859888-df819f80-5e20-11ea-8830-e29cbea2eb9a.png)

As h1 is in #shadow-root, AngularElementTestHarness could not able to locate h1 
**private heading1 = this.locatorFor('h1');**

Same is the case when we use TestHarness for any WebComponents developed in lit-element or Polymer.

#### Expected Behavior

AngularElementTestHarness should be able to locate h1 even h1 is in #shadow-root

**private heading1 = this.locatorFor('h1');**

#### PS: 
In Angular Element (angular-element-example.component.ts) if I change the encapsulation as below then TestHarness is working as expected.

**encapsulation: ViewEncapsulation.None**

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by devversion** [comment]
Thanks. That's a great issue! We've added support for a custom `querySelectorAll` method. You could then use a library like `kagekiri` to query for harnesses in a shadow-piercing way. See: https://github.com/angular/components/pull/18178
