### ISSUE TITLE
MatButton not styled if in Dialog exported by Angular Library

### ISSUE THREAD

**Issue by fabriziodebortoli** [angular/components#18705]
I've created an Angular libray by `ng g library xxx` with my commons components like a ConfirmDialog using MatDialogModule

In main app  `<button mat-flat-button color="primary">DIALOG</button>` is correctly styled:
![image](https://user-images.githubusercontent.com/20535803/75893026-8884c600-5e32-11ea-8dbe-8758603abd04.png)

Opening Dialog, buttons are not styled:
![image](https://user-images.githubusercontent.com/20535803/75893149-ab16df00-5e32-11ea-9747-7dfdd3e251c0.png)

#### Reproduction

I cannot use StackBlitz to reproduce because it not supports angular libraries so I created a repo:
https://github.com/fabriziodebortoli/library-material-dialog-styles.git

Steps to reproduce:
1.  git clone https://github.com/fabriziodebortoli/library-material-dialog-styles.git
2.  cd library-material-dialog-styles
3. npm install
4. npm start
 
 
#### Expected Behavior

Buttons inside Dialogs must be styled

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular: ~9.0.3
- CDK/Material: ~9.1.0
- Browser(s): Latest Chrome

**Comment by asimon91** [comment]
I confirm this bug is happening to me too.

**Comment by Kurainode** [comment]
I can also confirm.

**Comment by devversion** [comment]
Looks like your library module does not import `MatButtonModule`. The compiler is not able to automatically infer what the `mat-button` attribute in the dialog component resolves to.

**Comment by fabriziodebortoli** [comment]
Not solved.
I imported MatButtonModule in LibraryModule but buttons are still without styles

**Comment by devversion** [comment]
@fabriziodebortoli In your app module you don't seem to import the library module though. I tried these changes locally (now a second time) and was able to fix it that way. No reason to downvote.

**Comment by fabriziodebortoli** [comment]
I imported LibraryModule in AppModule using `import { LibraryModule } from '@azz/library';` 
but I still have the problem...

Trying 
`import { LibraryModule } from 'projects/azz/library/src/public-api';`
it's ok but I think is not the correct way to do it

**Comment by devversion** [comment]
@fabriziodebortoli Okay so there are a couple of things:

1. Add `MatButtonModule` to the library module
2. Actually add the library module to the AppModule.
3. Import the `Confirm` dialog component from the library `@azz/library` import and not directly through the source files. That causes the library module to be ignored.

I hope that helps.

**Comment by fabriziodebortoli** [comment]
These things have already been done.

Importing from @azz/library does not work. 
Only importing directly.

**Comment by devversion** [comment]
Okay. I definitely confirmed multiple times now that this is working as expected. There is not more we can do. Sorry.

**Comment by fabriziodebortoli** [comment]
Your proposed changes are already been done and it does not work as you can see from my repo.
So I think I don't understand what you mean.
Thanks anyway.

**Comment by devversion** [comment]
@fabriziodebortoli I don't know what you tried or not, but what I can see is that your repository does _not_ have the direct import removed in the app component. Surely you might have tried that before, but I can only assume you did not. Fixing that import, along with bullet points (1), (2) and (3), makes it work for me.

https://github.com/fabriziodebortoli/library-material-dialog-styles/blob/master/src/app/app.component.ts#L3

**Comment by devversion** [comment]
I assume you did not replace the import in app component as this file hasn't been touched since the initial reproduction, while you applied all other suggestions (from my posts) to the repository.

**Comment by fabriziodebortoli** [comment]
Now I understand and it works.
Thank you for your time.
