### ISSUE TITLE
matstepper: clear(not selected) when rendering initially

### ISSUE THREAD

**Issue by spraveen420** [angular/components#18719]
#### Feature Description

During initial render matstepper should not be selected by default or clear button to unselected all even initial state should be unselected

#### Use Case

When I am in some other page I don't want initial step to be selected it should show only flow

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
