### ISSUE TITLE
Accessibility: Android mat-radio-button says 'not selected' when selected

### ISSUE THREAD

**Issue by kjparkdavid** [angular/components#18713]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Go to https://material.angular.io/components/radio/overview on Android phone
2. Turn on Voice Assistant
3. Select a radio button
 
 
#### Expected Behavior

What behavior were you expecting to see?

Expect Voice Assistant on the radio button to say 'checked' as on iOS Safari.

#### Actual Behavior

What behavior did you actually see?

Voice Assistant says 'not selected'.

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.1.0
- Browser(s): Android Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by mmalerba** [comment]
I just tested this and it seems to work as expected on:
Pixel 3
Android 10
Chrome 83
Angular Material 10.0.1
