### ISSUE TITLE
mat-select: First option is auto selected after hitting tab on keyboard - Angular 9 specific

### ISSUE THREAD

**Issue by njennes** [angular/components#18718]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-9-0-0-rc-1-ugp4bv

Steps to reproduce:
1. Select a valid option in the first dropdown menu other than "None"
2. Do a few tabs on the keyboard to see that nothing changes
3. In the first dropdown select the "None" value
4. Hit tab on the keyboard, you can see that it auto selects the first valid option in the dropdown, even though you selected "None" as the option. It should stay on the "None" option
 
#### Expected Behavior

What behavior were you expecting to see?
I expect the "None" value to stay as that option when I select it and hit tab on the keyboard

#### Actual Behavior

What behavior did you actually see?
When I select "None" and hit tab on the keyboard, it auto selects the first valid value even though I want "None" as the option

#### Environment

- Angular: 9 (It doesn't happen in versions below 9)
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I couldn't reproduce it based on the provided info. Here's what I'm trying:

![demo](https://user-images.githubusercontent.com/4450522/76115291-35547400-5fe8-11ea-83d5-3d32880c676a.gif)

**Comment by njennes** [comment]
@crisbeto 
Thanks for testing! I think I know why it didn't work for you. 

In step 3 when you click the "None" value, don't click out of the dropdown with your mouse. Instead, immediately hit tab on the keyboard, you can see that it auto selects the first valid option in the dropdown, even though you selected "None" as the option. It should stay on the "None" option

**Comment by crisbeto** [comment]
I was only using my keyboard in the example above. Any time the dropdown closes it's because I pressed tab.

**Comment by mrnateriver** [comment]
I can confirm this issue. However, not with the provided Stackblitz.
Reproduction:
https://stackblitz.com/edit/angular-4bafkw

Select any meaningful value with mouse, click away.
Then open dropdown with mouse, select NULL value **with mouse** and **TAB** out.

This happens because of this change: https://github.com/angular/components/commit/93fdb00b95d123c6fffcf79557598848ddf77e96

When tabbing out, it selects last focused entry from dropdown, but it seems that selecting an entry with an empty value with mouse doesn't focus it.

**Comment by crisbeto** [comment]
@mrnateriver I can reproduce it in the linked Stackblitz, but not against our dev app on master. Maybe the fix hadn't gone out yet when the Stackblitz was put together?

**Comment by mrnateriver** [comment]
@crisbeto I've put up the Stackblitz just before I've commented on this issue. I suppose Stackblitz locks dependencies' versions once created, and if that's the case, then you can see that @angular/material 9.2.1 is used, as demonstrated on this screenshot.

![image](https://user-images.githubusercontent.com/22825372/80910432-946d0580-8d59-11ea-9da3-fc9e0a91d363.png)

**Comment by crisbeto** [comment]
Sorry for the delay here, I must have missed the notification. Is it still a problem with the latest version? I just tried again, but I wasn't able to reproduce it against our latest dev app either and any fix mentioned above definitely should've gone out by now.

I suspect that #18797 in particular resolved it which went out in version 9.2.2.

**Comment by njennes** [comment]
@crisbeto @mrnateriver 
I forked the stackblitz created by @mrnateriver and updated to v10, and the issue is resolved. Thank you everyone!
https://stackblitz.com/edit/angular-tucuu1
