### ISSUE TITLE
mat-line elements do not style correctly when in <ng-container>

### ISSUE THREAD

**Issue by MonocleKelso** [angular/components#18714]
#### Reproduction
Any elements decorated with mat-line that are not direct descendants of mat-list-item do not style correctly. Our use case for this is rendering a list of items from a union type where we display different information depending on what type the item is; but below is a more trivial example.

Steps to reproduce:
`<mat-list>
  <mat-list-item>
    <p mat-line>Foo</p>
    <ng-container *ngIf="fooHasChanges">
        <p mat-line>Changes</p>
        <p mat-line *ngFor="let change of foo.changes">
            {{change.value}}
        </p>
    </ng-container>
  </mat-list-item>
</mat-list>
`
 This appears to be related to https://github.com/angular/components/issues/5502
A similar fix for mat-grid-list was implemented here https://github.com/angular/components/issues/12809
 
#### Expected Behavior

The elements are styled correctly.

#### Actual Behavior

The elements are not styled correctly and render on the same line as the previous mat-line.

#### Environment

- Angular: ^8.2.14
- CDK/Material: ^8.2.3
- Browser(s): Chrome latest
- Operating System Windows

**Comment by crisbeto** [comment]
This should've been fixed all the way back in the 8.0 beta versions by #15552.

**Comment by MonocleKelso** [comment]
Simple recreate - https://angular-vgupch.stackblitz.io

**Comment by crisbeto** [comment]
It's because we expect the `mat-line` to be projected in a specific place, but that doesn't match anymore once you wrap it in an `ng-container`. You can fix it by adding `ngProjectAs="[mat-line]"` on the `ng-container`.

**Comment by MonocleKelso** [comment]
Thanks for the feedback but not sure why this issue was closed. The unit test committed in https://github.com/angular/components/pull/15552/commits/a42efc63a0614b0432ee08fbffa551c8fa6658c0 uses `ngSwitch` as opposed to `*ngIf` so I'm guessing this comes down to how content is projected under those 2 directives.

Your suggestion to use `ngProjectAs` would work but at that point you might as well put the structural directive on the element itself. This becomes cumbersome when you're wanting to render multiple mat lines under a single condition (as your unit test does).

**Comment by crisbeto** [comment]
I closed the issue, because this is how the framework works. Inside the list item we have a `<ng-content select="[mat-line]">` which means that it's looking for a `mat-line` that is a descendant of the item. When you wrap it inside an `ng-container` that selector won't match anymore so the line will be projected in the wrong place. Even though `ng-container` doesn't really "exist" at runtime, it's still another layer at the time projection happens (it's basically the same as if you'd wrapped the `mat-line` in a `div`).
