### ISSUE TITLE
help([Mat-Toolbar]): 'mat-toolbar' is not a known element:

### ISSUE THREAD

**Issue by mackelito** [angular/components#18723]
Rather suddenly I started to get these errors (Basically for every material component I use.. this was working fine the other day but now it's not !?
````
ERROR in src/app/layouts/main-layout/main-layout.component.html:2:3 - error NG8001: 'mat-toolbar' is not a known element:
    1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
    2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
````
The modules has been imported..
````
import { NgModule } from '@angular/core';
import { MainLayoutComponent } from './main-layout/main-layout.component';
import { MatListModule } from '@angular/material/list';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatSidenavModule } from '@angular/material/sidenav';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatIconModule } from '@angular/material/icon';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { HeaderFooterLayoutComponent } from './header-footer-layout/header-footer-layout.component';
import { CommonModule } from '@angular/common';

@NgModule({
  declarations: [
    MainLayoutComponent,
    HeaderFooterLayoutComponent
  ],
  imports: [
    CommonModule,
    RouterModule,
    FlexLayoutModule,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatButtonModule
  ],
  exports: [
    MainLayoutComponent,
    HeaderFooterLayoutComponent
  ]
})
export class LayoutsModule { }

````

#### What troubleshooting steps have you tried?
I have done `rm -rf node_modules` and cleared npm cache.. 
Then did a `npm i`
#### Environment
Angular CLI: 9.0.5
Node: 12.14.1
OS: darwin x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

**Comment by mackelito** [comment]
Not sure if it's related or not but now I often need to kill the server running on :4200

**Comment by lookatmypinky** [comment]
FWIW, same issue a couple days ago as well on 8.2.14.  Out of the blue with no project changes.
