### ISSUE TITLE
bug(mat-autocomplete): when additional data is appended to the list, focus of the current active element is lost

### ISSUE THREAD

**Issue by manu-058** [angular/components#18735]
#### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/angular-wzvzfq (load link)
2. click on autocomplete component.
3. press 'DOWN_ARROW_KEY' (data is appended but the active element is losing the focus)
4. But this behaviour not present mat-select ( focus of active element is not lost after appending the data)

 
 
#### Expected Behavior

What behavior were you expecting to see?
=> when data is appended to the existing list, focus should remain on the current active element.
#### Actual Behavior

What behavior did you actually see?
=> when additional data is appended to the list, focus of the current active element is lost.

#### Environment

- Angular: 8
- CDK/Material: 8.2.3
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Suggestion to correct this behaviour.**
changes needed in autocomplete-trigger.ts file
existing-1

![Screenshot (252)](https://user-images.githubusercontent.com/38914354/76060303-f5b96800-5fa6-11ea-87e1-a7bd3b4e23d8.png)

changes-1
![Screenshot (253)](https://user-images.githubusercontent.com/38914354/76060439-52b51e00-5fa7-11ea-9b8b-f3b83e1bb638.png)

existing-2
![Screenshot (254)](https://user-images.githubusercontent.com/38914354/76060459-5e084980-5fa7-11ea-91d6-343ea4cdcad1.png)

changes-2
![Screenshot (255)](https://user-images.githubusercontent.com/38914354/76060483-6a8ca200-5fa7-11ea-9991-09f678ed57e7.png)

this may solve the issue, i guess.

**Comment by crisbeto** [comment]
It behaves this way on purpose. We want the user start back from the top if they've filtered the list.

**Comment by manu-058** [comment]
oh ok got it.
@crisbeto  thank you for the replay.
