### ISSUE TITLE
bug(snackbar): MatSnackBarRef subscribes to Observables in constructor, never unsubscribes

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#18744]
See code at https://github.com/angular/components/blob/master/src/material/snack-bar/snack-bar-ref.ts

The constructor subscribes to several streams but I don't see that it ever unsubscribes. I assume this will cause a memory leak over time.

```ts
  constructor(containerInstance: MatSnackBarContainer,
              private _overlayRef: OverlayRef) {
    this.containerInstance = containerInstance;
    // Dismiss snackbar on action.
    this.onAction().subscribe(() => this.dismiss());
    containerInstance._onExit.subscribe(() => this._finishDismiss());
  }
```

**Comment by crisbeto** [comment]
All of these get completed at some point. E.g. here's where it happens for `_onExit`  https://github.com/angular/components/blob/master/src/material/snack-bar/snack-bar-container.ts#L171
