### ISSUE TITLE
bug(matInput): errorStateMatcher validates invalid emails 

### ISSUE THREAD

**Issue by teodossidossev** [angular/components#18749]
#### Reproduction

StackBlitz: https://stackblitz.com/angular/vbgpxydjdrv

Steps to reproduce:
1. enter any combination of a-z0-9, followed by @ and then another combination of 
a-z0-9. Do not enter a period. (example: invalid@email)
 
 
#### Expected Behavior

Invalid email address error to be present

#### Actual Behavior

Invalid email address error is not present

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by crisbeto** [comment]
I believe that `foo@bar` is technically a valid email address. Either way, I'm closing this because the email validator has nothing to do with the `errorStateMatcher`. The matcher only determines when the errors should be shown.
