### ISSUE TITLE
bug([MAT-PAGINATOR]): [I can not customize labels of the pagiantor by providing MatPaginatorIntl instance]

### ISSUE THREAD

**Issue by xstor1** [angular/components#18752]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Just install material design 9.1.1.
2.  Create your own instance of MatPaginatorIntl: `
export class MyMatPaginator extends MatPaginatorIntl {
  itemsPerPageLabel = 'Položek na stránku';
  nextPageLabel = 'Další stránka';
  previousPageLabel = 'Předchozí stránka';
}`
3. Rewrite the labels to custom one: (itemsPerPageLabel,previousPageLabel,nextPageLabel )
4. Register my instance in app.module:    
```
 {
      provide: MatPaginatorIntl,
      useClass: MyMatPaginator
 }
```

 
 
#### Expected Behavior

I assume i would be able to see customized label.

#### Actual Behavior

I see non customized label.

#### Environment

- Angular: 9.0.1
- CDK/Material: 9.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by xstor1** [comment]
Can someone check this please?

**Comment by Totati** [comment]
@xstor1  Hi, https://stackoverflow.com/a/47594193/4797961, but here is the exact example from the answer https://stackblitz.com/edit/angular-5mgfxh-cwgmym

**Comment by xstor1** [comment]
@Totati  Thanks.
