### ISSUE TITLE
bug(google-maps/MapEventManager): MapEventManager's TS definition constructor doesn't  accept ngZone

### ISSUE THREAD

**Issue by Akxe** [angular/components#18754]
#### Reproduction

~~Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue~~
Cannot create as stackblitz cannot work with `@angular/google-maps`.

```ts
import {Component, NgZone} from '@angular/core';
import { MapEventManager } from '@angular/google-maps/map-event-manager';

@Component({
  selector: 'example-component',
  templateUrl: 'example-component.html',
  styleUrls: ['example-component.css'],
})
export class ExampleComponent {
	private _eventManager = new MapEventManager(this._ngZone);

  constructor(
    private _ngZone: NgZone,
  ) {}
}
```
 
 
#### Expected Behavior

No error.

#### Actual Behavior

Error with `MapEventManager` as here: `Expected 0 arguments, but got 1.ts(2554)`

#### Environment

- Angular: 9.0.5
- CDK/Material: 9.1.1
- Browser(s): --- TS Compolation
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The `MapEventManager` isn't part of the public API.
