### ISSUE TITLE
bug([MatExpansionModule]): Mat-Expansion-Panel missing example 2 ui

### ISSUE THREAD

**Issue by marcnoon** [angular/components#18769]
The 2nd example of the expansion panel is missing titled: 'Mat Expansion Panel as Accordian'.  Only the title appears, and the code section and code appears.   But the actual demo example is msising.

https://material.angular.io/components/expansion/examples

**Comment by geromegrignon** [comment]
Hello, thanks for the report.
There is already an issue #18771  and a pull request going on to fix it #18772.
You can close this issue.

**Comment by crisbeto** [comment]
Looks like the related PR was merged. Closing.
