### ISSUE TITLE
Mat-checkbox: Focus input

### ISSUE THREAD

**Issue by godzsa** [angular/components#18762]
#### Feature Description
Add a focus property or input to the mat-checkbox component so it can be focused automatically by code.

#### Use Case
I create a form where the first input is a checkbox, I want it to be automatically focused

**Comment by jelbourn** [comment]
We have no plans for adding any kind of automatic focus behavior to any of the individual components. There is an item in the backlog to explore a general focus management solution in the cdk, but it's pretty far down on the list.
