### ISSUE TITLE
help(cdk/platform): User Agent deprecation

### ISSUE THREAD

**Issue by gpini** [angular/components#18763]
According to this https://www.chromestatus.com/feature/5704553745874944 and this https://www.chromestatus.com/feature/5995832180473856 in 20202 there will be user agent deprecation in favor of Sec-CH-UA Client Hints.
Are you planning to introduce new navigator.getUserAgent() promise to manage this for device detection?

**Comment by jelbourn** [comment]
It's too early to tell for now; we'll have to see how standardization goes.
