### ISSUE TITLE
bug(Table): Angular 9: caching column definitions breaks nesting tables

### ISSUE THREAD

**Issue by dtarjeft** [angular/components#18768]
#### Reproduction

Steps to reproduce:
1. Open [this](https://stackblitz.com/edit/angular-nested-mat-table?file=package.json) StackBlitz from [this](https://stackoverflow.com/a/57839402) StackOverflow answer regarding nested material tables using Angular 8.
2. Observe that clicking on table rows causes the table to expand/collapse and show nested data.
3. Upgrade Angular to 9.0.5. For convenience, [here's](https://stackblitz.com/edit/angular-nested-mat-table-xggusf?file=package.json) a StackBlitz with this completed.
 
#### Expected Behavior

Nested material tables in each mat-row with those columns defined, opening and closing as intended. No errors.

#### Actual Behavior

Expanding a row works the first time, then fails, leaving the table in a bad state throwing errors to the effect of `Duplicate column definition name provided` - the expansion/collapse functionality completely stops working at this point.

One _can_ work around this by creating a dummy component who's sole purpose is to pass the data to another instance of `mat-table` - I've shown this in a [fork](https://angular-nested-mat-table-rlai7s.stackblitz.io) of the Angular 9 StackBlitz. _Note: I didn't preserve the filters from the original StackBlitz, as that was not part of the functionality in question._

#### Environment

- Angular: 9.0.5
- CDK/Material: 9.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by FredyValstrauss** [comment]
I'm facing this exact same issue with Angular 9 and Angular Material 9.1.0. Please help!

**Comment by dtarjeft** [comment]
@FredyValstrauss [This component](https://stackblitz.com/edit/angular-nested-mat-table-rlai7s?file=app%2Fnested-table.ts) should work around the issue for the time being, though I trust the Angular team will be able to come up with a better solution.

**Comment by FredyValstrauss** [comment]
Hi @dtarjeft, your work aroud worked wonderful in my case. I only modified the template to use templateURL and use a separate html file, but it works just fine. As you said, this is a work around and Angular team should release a better and much simpler solution. Thanks again for the work around!
