### ISSUE TITLE
fr([BUTTON]): [BUTTON SIZES?]

### ISSUE THREAD

**Issue by MisterJ936** [angular/components#18774]
#### Feature Description

I would like to see a new properties for button the determines their sizes, from extra small, small, default, large, and extra-large. 

#### Use Case

Using a css styling with button is a bad Idea, because if their is a new update on the button component, the css style would ignore some important styling for the button.

**Comment by geromegrignon** [comment]
It would break [Material Design guidelines](https://material.io/components/buttons/#specs).

**Comment by jelbourn** [comment]
Duplicate of #18241
