### ISSUE TITLE
docs(material/expansion-panel): accordion example throws No provider found for DateAdapter

### ISSUE THREAD

**Issue by h3d0** [angular/components#18771]
#### Detailed Reproduction Steps: 
1. Go to https://material.angular.io/components/expansion/examples
1. Open Dev Console

### What is the expected behavior?
Accordion example is working.

### What is the current behavior?
Accordion example is broken:
![image](https://user-images.githubusercontent.com/7346327/76220438-2c4de780-6220-11ea-8843-27fcbc5cf474.png)

### What is the use-case or motivation for changing an existing behavior?
All users visiting a website are affected.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 9.1.0
- AngularJS Material: 9.1.0
- OS: All
- Browsers: All

**Comment by Splaktar** [comment]
I beleive that this is due to https://github.com/angular/components/blob/6baffb3c17025899770dbdb38f80e130537d48c9/src/components-examples/material/expansion/index.ts#L26-L32 not importing a DateAdapter.
