### ISSUE TITLE
drag-drop: Keep 'cursor: move' when dragging

### ISSUE THREAD

**Issue by baalimago** [angular/components#18779]
#### Feature Description
Keep the `cursor:move` property on at all times when dragging an element in the drag-drop, even if the cursor goes outside the drag-drop list. 

#### Use Case

When dragging an item, the user shouldn't do anything but dragging said element. So to have the cursor suggest that it's possible to click, or mark, or whatever the cursor is indicating, seems to me to be unintuitive.

**Comment by crisbeto** [comment]
We try to add only the essential structural styles in the CDK and the cursor isn't one of them. It should be easy to add it by yourself, there are a few examples doing it in the docs. https://material.angular.io/cdk/drag-drop/overview

**Comment by JohnKis** [comment]
I believe the op meant setting a cursor when dragging an item from a drop list, which isn't possible at the moment because the drag preview disables pointer events.

I'm having the same issue and I could come up with a workaround for it so far.

**Comment by JohnKis** [comment]
One not particularly nice workaround could be defining the following style which forces a cursor on all elements:
```scss
body.force-cursor {
  * {
    cursor: default !important;
  }
}
```

Then you could add the class to `document.body` when the drag starts and remove it when the drag ends.
