### ISSUE TITLE
Can't use the local CSS with matTooltipClass 

### ISSUE THREAD

**Issue by stormyqq** [angular/components#18788]
I used matTooltipClass property with img tag to style the matTooltip tool tip. I used the img tag as following.

```
<img [src]="image" 
     [matTooltip]='varImageToolTip'
     [matTooltipClass]="'toolTip'"/>
```

then in the local CSS, I used as following.

```
.toolTip {
  font-size:14px;
}
```

BUT when I tested out the code, I couldn't see the font is 14px big. I used ::ng-deep, :host ::ng-deep in front of the .toolTip class name in the CSS, but it didn't work out too, then I used the following CSS in the global CSS

```
.toolTip {
  font-size:14px;
}
```

then it works fine. The font came big as it's intended. I am wondering why the style doesn't apply when it's used in the local CSS? 

I use the following Angular versions in package JSON. 
    "@angular/core": "~8.2.14",
    "@angular/material": "^8.2.3",

**Comment by quanterion** [comment]
It's because tooltip DOM nodes is inside cdk-overlay that is directly inside <body>, not inside your component. To style it you have to customize it in global css file.

**Comment by crisbeto** [comment]
@quanterion is correct. Closing since everything is working as expected.
