### ISSUE TITLE
BUG PAGE MATERIAL.ANGULAR.IO

### ISSUE THREAD

**Issue by robertal99** [angular/components#18791]
IS THIS NORMAL IN YOUR WEB PAGE WHEN ITS REDUCES IN AUTOCOMPLETE ?
![ESCRITORIO](https://user-images.githubusercontent.com/54558382/76440012-3e986480-638b-11ea-8e87-a39e82b700da.PNG)

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by robertal99** [comment]
Hello , i do not speak in English, your autocomplete component seems it a
bug whit scroll
