### ISSUE TITLE
bug(MatInputHarness): Does not properly set value with <input type="color">

### ISSUE THREAD

**Issue by roger6106** [angular/components#18790]
#### Reproduction

See StackBlitz: https://stackblitz.com/edit/components-issue-3u5pnf?file=src/app/app.component.spec.ts 

Steps to reproduce:
1. Using the MatInputHarness, `setValue('#123456')` (or any other color) of an `<input type="color">`.
2. Use `getValue()` to get the result.
 
#### Expected Behavior

The value should be `#123456`.

#### Actual Behavior

It is always `#000000`.

#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.2
- Browser(s): Chrome 80.0.3987.132, Safari 13.0.5
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15.3

**Comment by eitak** [comment]
There's a similar issue with `<input type="datetime-local">`.

**Comment by tobiasschweizer** [comment]
I am facing an issue with `type="number"` and number strings with fractions: 

- `setValue('1.5')`
- `getValue()` -> '5'

@crisbeto Do you want me to open a new issue for this?

**Comment by crisbeto** [comment]
The fix for this issue should fix yours as well @tobiasschweizer.

**Comment by tobiasschweizer** [comment]
> The fix for this issue should fix yours as well @tobiasschweizer.

That's great news! 

Should we add an `it` for a number string with decimals in https://github.com/angular/components/blob/ccab78c2c4b45c51d6eabc6cc70b4541c80dbc10/src/material/input/testing/shared.spec.ts?

**Comment by KevinVillela** [comment]
Interestingly, this appears to be correctly setting the value on the form control, but isn't actually working with form validation. For example, if I check `formCtrl.value`, I get '-1234', which is great. But if I also have a validator on that form control that checks that the value is non-negative, `formCtrl.valid` is still `true` (even after blurring). I narrowed it down to declaration of `type="number"` on the input element.
