### ISSUE TITLE
[mat-select] Mousedown on mat-select option causes focus on separate mat-form-field when contained in overlay components

### ISSUE THREAD

**Issue by reed-lawrence** [angular/components#18796]
Example here: https://github.com/reed-lawrence/ionic-sticky-routes

#### Actual Behavior

When intiating mousedown a mat-select option on any overlay component such as a modal, it will focus the first mat-form-field in the component.

![Screen Shot 2020-03-11 at 4 48 57 PM](https://user-images.githubusercontent.com/30061591/76468771-c184e380-63ba-11ea-8b6e-1d148160ef88.png)

In the above example I am clicking the mat-option within the mat-select and you can see that it is focusing the mat-form-field unrelated to the mat-select.

This behavior is NOT present in non-overlay containers. 

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Safari & Chrome
- Operating System: macOS

**Comment by crisbeto** [comment]
This looks like an issue with Ionic. I'm guessing that the `ion-modal` has some kind of focus trapping behavior which gets triggered, because it loses focus when the user puts their pointer down on a different element.
