### ISSUE TITLE
fr(Slider): 0-based +/- values

### ISSUE THREAD

**Issue by axos88** [angular/components#18798]
#### Feature Description

I'd like to have a slider that has the value 0 in the middle, and values range from -x to +x.
The line should be colored from the middle to the selected value (currently it's always from the left or right in case it's inverted).

#### Use Case

Personality axis antagonist trait slider, for ex: (introvert ... extrovert)

**Comment by mzehetho** [comment]
I made a [feature request](https://github.com/material-components/material-components/issues/76) in the spec. Sadly it was not added.

**Comment by jelbourn** [comment]
Closing this since, as you ran into, it's not part of the spec, so I don't see us prioritizing adding support for this.
