### ISSUE TITLE
matTooltip ignores line-breaks when setting text dynamically.

### ISSUE THREAD

**Issue by stefan-falk** [angular/components#18802]
I am trying to follow [these examples](https://stackoverflow.com/questions/47058483/angular-2-material-mattooltip-multiline) but it seem that the way I am setting the tooltip-text does not work.

From my stackoverflow question: https://stackblitz.com/edit/angular-cxppu9-bu1fwv?file=src%2Fapp%2Ftooltip-overview-example.html

#### Reproduction

[Example 1](https://stackblitz.com/edit/angular-cxppu9?file=src%2Fapp%2Ftooltip-overview-example.ts)
[Example 2](https://stackblitz.com/edit/angular-cxppu9-bu1fwv?file=src%2Fapp%2Ftooltip-overview-example.html)
 
#### Expected Behavior

See multiple lines in the MatTooltip.

#### Actual Behavior

Text is only a single line.

#### Environment

- Angular: 9

**Comment by crisbeto** [comment]
The tooltip inserts its value as plain text, not using `innerHTML` for security reasons, hence why your example doesn't work. Closing since this isn't something that we support.
