### ISSUE TITLE
I cannot declare type on CdkDragDrop event for CdkDrag item data

### ISSUE THREAD

**Issue by Wilt** [angular/components#18804]
#### What are you trying to do?

I want to declare the data type when I drop a draggable item inside a drop container.
The handler takes a `CdkDragDrop` event as an argument, but the item type is not declarable.
I can only declare the types of the `CdkDropList` for the `previousContainer` and current `container`.
I would like to declare the type of `CdkDrag` so it reflects to the item.data.

#### What troubleshooting steps have you tried?

Checking documentation, clearly not declarable at this state (code from `CdkDragDrop` class):

```
/** Event emitted when the user drops a draggable item inside a drop container. */
export interface CdkDragDrop<T, O = T> {
    /** Index of the item when it was picked up. */
    previousIndex: number;
    /** Current index of the item. */
    currentIndex: number;
```
-----------------------------
Here lies the problem:
```
    /** Item that is being dropped. */
    item: CdkDrag;  // <---- TYPE NOT DECLARABLE, DEFAULTS TO any
```
-----------------------------
```
    /** Container in which the item was dropped. */
    container: CdkDropList<T>;
    /** Container from which the item was picked up. Can be the same as the `container`. */
    previousContainer: CdkDropList<O>;
    /** Whether the user's pointer was over the container when the item was dropped. */
    isPointerOverContainer: boolean;
    /** Distance in pixels that the user has dragged since the drag sequence started. */
    distance: {
        x: number;
        y: number;
    };
}
```

#### Reproduction

    public onDrop(event: CdkDragDrop<Type1, Type2>): void {
      const droppedItem = event.item;  //CdkDrag<any>
      const data = event.item.data;  //any
    }

droppedItem will always be of type `CdkDrag<any>`
data will always be of type `any`
I want to declare the type of my dropped data.

A StackBlitz to demonstrate what I am trying to do: 

https://stackblitz.com/edit/cdk-ng-drag-drop-dfnswr
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by Wilt** [comment]
Thanks for that change!

**Comment by crisbeto** [comment]
Closing since this was resolved in master.
