### ISSUE TITLE
docs-bug(Ripple): Ripple page doc Failed to load

### ISSUE THREAD

**Issue by Krystian95** [angular/components#18814]
Hi, the page https://material.angular.io/components/ripple/overview is incorrectly loaded (tab "OVERVIEW"), with the error `Failed to load document: /docs-content/overviews/material/ripple/ripple.html. Error: Not Found`.

<img width="1552" alt="Schermata 2020-03-13 alle 01 22 37" src="https://user-images.githubusercontent.com/24765669/76578618-7c9ba280-64c9-11ea-842b-d01a3e2c4b9e.png">

**Comment by devversion** [comment]
Thx for reporting this. https://github.com/angular/material.angular.io/pull/734 will fix this.
