### ISSUE TITLE
Add documentation for CDK Collections

### ISSUE THREAD

**Issue by mikejunt** [angular/components#18818]
#### Bug, feature request, or proposal:

The cdk/Material table and especially the Material Paginator/Sort need dataSource classes to function correctly with complex data objects.    However, they currently have circular documentation that leads nowhere.   Material Table references the CDK table, which references the datasource, which, like all cdk Collections classes, is completely undocumented.

#### Is there anything else we should know?

I would suggest some official documentation around the Collections classes and DataSource objects in particular to understand what kind of inputs they are looking for and how they should be modified for complex objects to function with the sort/Paginator functions without extensive trial and error.

**Comment by andrewseguin** [comment]
Thanks for reporting the issue -this is definitely a place where we are currently lacking. Unfortunately we haven't had the resources to prioritize this, but we'd be happy to welcome any suggestions in a pull request
