### ISSUE TITLE
docs-bug(Guide: Creating a custom form field control): Missing Validators in FormGroup

### ISSUE THREAD

**Issue by tobiasschweizer** [angular/components#18817]
#### Documentation Feedback

In the example implementation of a `MatFormFieldControl` `FormGroup` is used. However, validation happens in the value getter:

```ts
@Input()
  get value(): MyTel | null {
    const {value: {area, exchange, subscriber}} = this.parts;
    if (area.length === 3 && exchange.length === 3 && subscriber.length === 4) {
      return new MyTel(area, exchange, subscriber);
    }
    return null;
  }
```

 I think it would be better if a validator was provided. Then in the value getter, simply the validity of the form would have to be checked:

```ts
@Input()
  get value(): MyTel | null {
    if (this.parts.valid) {
      const {value: {area, exchange, subscriber}} = this.parts;
      return new MyTel(area, exchange, subscriber);
    }
    return null;
  }
```

I guess `Validators.minLength()` and `Validators.maxLength()` would do the job.

**Affected documentation page: https://material.angular.io/guide/creating-a-custom-form-field-control**

**Comment by tobiasschweizer** [comment]
@mmalerba If you want me to do this, I am happy to provide a PR.

**Comment by mmalerba** [comment]
@tobiasschweizer sure, I'd be happy to accept a PR for this. Thanks for taking the time to fix up this example

**Comment by tobiasschweizer** [comment]
Ok, will do! 

Could you tell me how I can test this (actually run the code)?

**Comment by mmalerba** [comment]
Sure, just run `yarn dev-app` and go to localhost:4200/examples. There's a lot of examples, so ctrl+f for "form-field-custom-control" and expand that one

**Comment by tobiasschweizer** [comment]
done in https://github.com/angular/components/pull/18844
