### ISSUE TITLE
bug(datepicker): disabled datepicker is not working in IE11

### ISSUE THREAD

**Issue by kalyanishrikant** [angular/components#18839]
#### Reproduction
StackBlitz is currently not working on IE.
This is reproducible on https://material.angular.io/components/datepicker/examples ('Disabled Datepicker' example)

Steps to reproduce:
1. Go to https://material.angular.io/components/datepicker/examples in IE
2. The 'Disabled Datepicker' example is not working and there is a console error

```
ERROR Error: Unexpected call to method or property access.
```

 
#### Expected Behavior

Datepicker should be displayed in disabled state.

#### Actual Behavior

Nothing is displayed and there is error on console.

The issue seems to be in `set disabled(..) {}` when `element.blur()` is called.

#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.2
- Browser(s): IE11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
There's a PR to resolve the error https://github.com/angular/components/pull/18202. Until it lands, you should be able to work around it by binding to `disabled` like this `[disabled]="true"`.

**Comment by crisbeto** [comment]
The related fix has been merged.
