### ISSUE TITLE
bug(MatDrawer - MatChip): Using a MatChip in a Matdrawer leads to unstyled MatChip with overflowing Ripple

### ISSUE THREAD

**Issue by Kryptand** [angular/components#18849]
#### Reproduction

Use StackBlitz to reproduce your issue: [Link](https://stackblitz.com/edit/angular-qnswnd)

Steps to reproduce:
1. Use a Mat-Drawer
2. Insert a Matchip into either Drawer or Content
 
 
#### Expected Behavior

What behavior were you expecting to see?
A styled mat-chip.

#### Actual Behavior

What behavior did you actually see?
 A unstyled Mat-Chip with overflowing Ripple effect.
#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.3
- Browser(s): Google Chrome 80, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
It's because you have to wrap the chip in a `mat-chip-list` which brings in all the structural styles.
