### ISSUE TITLE
fr(cdk/schematics): how pass another range version to TargetVersion

### ISSUE THREAD

**Issue by jhonyeduardo** [angular/components#18843]
#### Feature Description

createUpgradeRule only agree TargetVersion (v6,v7,v8,v9) but my-lib uses another range versions, will be 2.0.0.

The better would be possible to pass another TargetVersion.

#### Use Case

I want use the createUpgradeRule to reuse this functionality in my custom ng-update.

**Comment by devversion** [comment]
The `@angular/cdk/schematics` entry-point is internal only. This explains why the target versions are hard-coded as they just match what `ng update` for `@angular/cdk` or `@angular/material` supports.

Please submit a feature request (or look for existing issues) about shared utils for `ng update` on the CLI repository. I don't think that the CDK is the right place for this.

**Comment by devversion** [comment]
Also, https://github.com/nitayneeman/schematics-utilities/tree/master/src could potentially fork the ng-update utilities and improve things here. In general though, the update system is not designed to be used externally. It might be a good idea to explore if it could be in the future though. 

So, I could also see a feature request for this (with some good explanations on why the CDK one should be made public?)
