### ISSUE TITLE
fr(Tab): Add setter for _contentPortal property

### ISSUE THREAD

**Issue by ipajonro** [angular/components#18850]
#### Add setter method for _contentPortal property

If we want to extend functionality of MatTab class, we need to set _contentPortal property, wich is a private property. It has a getter method but not a setter method. So adding a getter we will can extend MatTab class and make a component with our requirements.

#### Use Case

In case you need to modify or extend MatTab behaviour, but maintaining rest of functionality.

**Comment by jelbourn** [comment]
Currently we're not doing any work to explicitly make the Material Design components easier to extend; the long-term goal is that the CDK would serve that purpose.
