### ISSUE TITLE
bug([@angular/material]): Autocomplete panel should grow to left when doesn't fit viewport

### ISSUE THREAD

**Issue by JonWallsten** [angular/components#18854]
#### Info
Not sure if this is a bug or a feature request.
I was digging around in the code to understand what's going on. It seems like the only way on getting what I want is to use RTL instead of LTR on the overlay panel. I didn't actually change this in the code, but I did change the value in Dev Tools while running my code and it was positioned correctly. However this should be set dynamically when the Auto complete panel doesn't fit.
I also tried to change the `preferredPositions` to use `originX=end` instead of start. But it didn't change the outcome

#### Reproduction

https://stackblitz.com/edit/angular-material-2-yzct7d

Steps to reproduce:
1. Focus the input field and watch the Autocomplete panel
 
#### Expected Behavior
When the panel doesn't fit within the viewport's width I expect the panel to grow from right to left instead.

![image](https://user-images.githubusercontent.com/5993909/76947696-4bc2cf80-6906-11ea-8cff-9f15ce1ddd5e.png)

#### Actual Behavior

The box doesn't fit in the viewport

![image](https://user-images.githubusercontent.com/5993909/76946810-e3bfb980-6904-11ea-8daa-62947449eda9.png)

#### Environment

- Angular: 9.x.x
- CDK/Material: 9.x.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Wouldn't this cause the same issue but in the other direction? Also did you override the panel width? We have some logic that forces the panel to be the same width as the input.

**Comment by JonWallsten** [comment]
@crisbeto: Sorry, I should have mentioned that this occurs when the with is set manually. We have tables with inputs where the field can be really small, but the values can be really long. So we calculate a width based on the characters displayed in the option. 

It should not be a problem if it's applied dynamically when it can't fit.

FlexibleConnectedPositionStrategy already checks if you can fit the panel:

![image](https://user-images.githubusercontent.com/5993909/76952208-0eae0b80-690d-11ea-83c4-d0c9cae6e186.png)

If it can't fit it should reposition with RTL and check again.

I would have expected adding another preferredPosition would have solved this:
![image](https://user-images.githubusercontent.com/5993909/76952366-47e67b80-690d-11ea-9d48-5e083ad77d00.png)

But I guess it only does the calculations from the right side of the host instead of the right, which of course will be worse.
