### ISSUE TITLE
Mat-form-field mat-labels updated incorrectly when font-size changes

### ISSUE THREAD

**Issue by mihaionduma** [angular/components#18866]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-vwwrbm-f1fnyk

Steps to reproduce:
1. Build a mat-form-field with outline appearance, a mat-label as the outline header text
2. Change the font-size after the component has been displayed

See the stackblitz for a more detailed look.
 
 
#### Expected Behavior

I would like to see the component update when the font-size css property changes.

#### Actual Behavior

The mat-form-field outline label is in the wrong position after the font size has been changed

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.1.3
- Browser(s): Google Chrome Version 80.0.3987.132
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment]
Listening for font size changes on our end and updating the outline would be extremely inefficient, hence why we aren't doing it. You can use the `MatFormField.updateOutlineGap` method to tell the form field that it's supposed to recalculate its outline gap.
