### ISSUE TITLE
fr(Date Picker): Provide timezone

### ISSUE THREAD

**Issue by airasyaqub** [angular/components#18870]
Feature Description

Any way to provide time zone which the date picker will use under the hood. Right now it uses system time zone.

Use Case

I am working on a product which uses time zones to set the discount coupons expiry. I would like to use the store time zone rather system time zone when user is creating a discount and setting its start/end date/time. I have also tried using "Custom Adapter" with my own parser function. The problem with that approach is it only triggers that parser function when date is manually input rather than selected from date picker drop down.  

My implementation

`
export class CustomDateAdapter extends MomentDateAdapter   {

	private _generalSettings$: Observable<IGeneralSettings> = this._generalSettingsStore.select(generalSettingsSelectors.selectGs);
	private _gsSubscription: Subscription;
	private _timeZone: string;

	constructor(
		@Optional() @Inject(MAT_DATE_LOCALE) dateLocale: string,
		private _generalSettingsStore: Store<GeneralSettingsState>,
		) {
		super(dateLocale);
		this._getGS();
	}

	parse(value: any, parseFormat: string | string[]): Moment | null {
		console.log(value);
		if (value && typeof value === 'string') {
			return moment(value).utc().utcOffset(this._timeZone);
			// return moment.utc(value, parseFormat, this.locale, true);
		}
		return value ? moment(value).utc().utcOffset(this._timeZone) : null;
	}

	private _getGS(): void {
		this._gsSubscription = this._generalSettings$.subscribe((res: IGeneralSettings) => {
			// this.logService.debug('gs response ==>', res);
			if (res) {
				this._timeZone = _getOffset(res.timeZone);
			}
		});
	}`

In my module 

`
providers: [
		DiscountService,
		{
			provide: DateAdapter, useClass: CustomDateAdapter
		}
	]
`

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization

You can provide an alternate/custom `DateAdapter` that lets you have full control over how time/timezones are handled.
