### ISSUE TITLE
Material-date-picker : Searching in input gives incorrect date need to convert it into UTC

### ISSUE THREAD

**Issue by akshaybhat30** [angular/components#18873]
#### What are you trying to do?

What are you trying to do?

I am trying to capture users locale and change the date format based on the captured locale.
Everything is working fine except:-
When i try to enter the date manually using the input i am not getting the output date in UTC format but when i am selecting a date from the calendar manually i am converting it to UTC using the createDate function by extending MomentDateAdapter.

What are you seeing that does not match your expectations? 
Is there any way to change the manual input to UTC as well ?
#### Reproduction

StackBlitz:-  https://stackblitz.com/edit/angular-moment-date-adapter-overriding-h6zeds?file=app%2Fcustom-date-adapter.tsSteps

Steps to reproduce:
1. Try to select a value from calendar and see the console (notice the date is converted to UTC)
2. Now try to add a date manually by typing in and see the console (date is not converted to UTC).
  
#### Environment

- Angular: 8.2.14
- CDK/Material: 8.0.0
- Browser(s):  80.0.3987.132 
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
I'm getting an error when trying to run your Stackblitz, but at a glance, it seems like your custom date adapter isn't creating the Moment dates as UTC. You can see how the default `MomentDateAdapter` is doing it here: https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts#L251

**Comment by crisbeto** [comment]
Closing due to lack of response.
