### ISSUE TITLE
help(dev-app): yarn dev-app gives SASSCompiler error on windows

### ISSUE THREAD

**Issue by lukaonik** [angular/components#18880]
#### What are you trying to do?
I am trying to run dev-app on latest version of master branch

#### What troubleshooting steps have you tried?
I am trying to run dev-app application,by using yarn dev-app and it gives me the following errror

```
ERROR: C:/projects/components/src/dev-app/BUILD.bazel:162:1 SassCompiler src/material/grid-list/grid-list.css failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at C:/users/onika/_bazel_onika/mitqcfzm/bazel-workers/worker-29-SassCompiler.log ---8<---8<---
'""' is not recognized as an internal or external command,
operable program or batch file.
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 8.108s, Critical Path: 0.53s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
iBazel [6:42PM]: Error starting process: fork/exec C:\Users\onika\AppData\Local\Temp\bazel_script_path345870083.bat: %1 is not a valid Win32 application.
iBazel [6:42PM]: Run start failed fork/exec C:\Users\onika\AppData\Local\Temp\bazel_script_path345870083.bat: %1 is not a valid Win32 application.
iBazel [6:42PM]: Error reading config: open .bazel_fix_commands.json: The system cannot find the file specified.
```

#### Reproduction

there is no way I can reproduce it either stackblitz,or anywhere else, because it's framework issue

Steps to reproduce:
1. yarn
2. yarn dev-app
  
#### Environment

- Angular: ^9.1.0-next.4
- CDK/Material: 9.2.0-next.0
- Browser(s): none
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10 Enterprise

**Comment by crisbeto** [comment]
I've been running master all day without any issues on Windows, but I have seen that error before. I've had it happen when Bazel didn't like some characters in the output path (in my case it was some whitespace).

**Comment by devversion** [comment]
Hello! I'm running Bazel on Windows too, but haven't seen that in a while. This usually happens when the cloned project path contains spaces (which isn't the case here as it looks), or if the `BAZEL_SH` environment variable is explicitly set (this variable is not needed anymore).

I'm happy to help. Is this is still an issue for you? Closing in the meanwhile as I don't believe this is an upstream issue on our end. This seems like a client issue with how Bazel launches arbitrary binaries.
