### ISSUE TITLE
help([mat-sidenav-container]): [Autosize is blocking my Protractor tests]

### ISSUE THREAD

**Issue by manuman94** [angular/components#18894]
#### What are you trying to do?

I'm trying to execute e2e tests with Protractor in a project with a mat-sidenav-container with the `autosize` attribute.

#### What troubleshooting steps have you tried?

The main problem is that waitForAngular() function that Protractor uses frequently does not end until the Angular Zone has ended all tasks. Autosize is making my protractor waitForAngular() function to be waiting until its timeout. When I remove the autosize parameter my tests are working again (and waitForAngular() resolves).
I'm using Angular v8.0.3 and Angular Material v8.0.1, is this solved in a later release?

#### Reproduction

Steps to reproduce:
1. Use a mat-sidenav-container with autosize attribute
2. Run a simple Protractor test that use waitForAngular(). Example:
```
browser.getCurrentUrl().then((url) => {
    expect(url).toContain('mydomain.com');
});
```
This code is waiting for Angular.
  
#### Environment

- Angular: 8.0.3
- CDK/Material: 8.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 18, Windows

**Comment by crisbeto** [comment]
I'm guessing it's because of the timeout we're using to debounce it potentially being run inside the `NgZone`. I've submitted #18898 since there's no reason for it to be in the zone in the first place.

**Comment by manuman94** [comment]
Thank you for your quick response. 

I wonder when will this PR be released as we are thinking in update our project's Angular and Angular Material versions to the latest (I see that is approved and marked with _target:patch_). We are implementing e2e tests and this is blocking our flow.

Thank you, greetings.

**Comment by crisbeto** [comment]
I can't guarantee when it's going to go out, because it has to go through the same process as the rest of our PRs. Until it goes out, you can disable `autosize` only for e2e tests yourself.
