### ISSUE TITLE
bug: InnerHTML binding will not work in MatCell (MatTabel)

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular/components#18893]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ua3bhb?file=src/app/table-basic-example.ts

Steps to reproduce:
1. Create a MatTable (you can just use the example mat-table from the docs)
2. In the `<td>` element where we use `*matCellDef="..."` add `[innerHTML]="..."`
3. Add some html inside of it (for example some css style on a new html element like icon or image)
 
#### Expected Behavior
The Html render can parse the content of the innerHtml into the web page

#### Actual Behavior
The innerHtml is being treated like a innerText. The html tags are removed, only can see the inner text of the tag

#### Environment

- Angular: 9.x
- CDK/Material: 9.1.3
- Browser(s): Chrome/ Opera
- Operating System (e.g. Windows, macOS, Ubuntu):  Win 10

![image](https://user-images.githubusercontent.com/7883039/77332808-35b07700-6d2b-11ea-9924-6408a5602ba1.png)
![image](https://user-images.githubusercontent.com/7883039/77332856-42cd6600-6d2b-11ea-9117-23558869a9b8.png)
![image](https://user-images.githubusercontent.com/7883039/77332876-4b25a100-6d2b-11ea-8fec-b095bc2fe7cb.png)
![image](https://user-images.githubusercontent.com/7883039/77332928-5ed10780-6d2b-11ea-8e1c-05381fcb2a18.png)

**Comment by jelbourn** [comment]
This is not related to the table or Angular Material; this is Angular's security model working as intended: https://angular.io/guide/security
