### ISSUE TITLE
fr(Drag-Drop): Setting z-index

### ISSUE THREAD

**Issue by piernik** [angular/components#18902]
In source code I see that z-index of preview is hard coded: https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-ref.ts
```
extendStyles(preview.style, {
      // It's important that we disable the pointer events on the preview, because
      // it can throw off the `document.elementFromPoint` calls in the `CdkDropList`.
      pointerEvents: 'none',
      // We have to reset the margin, because it can throw off positioning relative to the viewport.
      margin: '0',
      position: 'fixed',
      top: '0',
      left: '0',
      zIndex: '1000'
    });
```

Problem is that I'm using drag-drop feature n bootstrap modal which has z-index 1050 - so I have to change it, but I cannot.

**Comment by Totati** [comment]
Yeah, we use cdk drag and drop in a bootstrap dialog, and we had to configure the all the variables for z-index in bootstrap to work correctly.
