### ISSUE TITLE
bug([formfield]): FormField control inside expansion panel with mat-label throws exception

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/components#18910]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
https://stackblitz.com/github/santoshyadav198613/material-error-demo

Steps to reproduce:
1. Click on Exapnsion Demo 
2. Keep the console open 
3. Error "ERRORError: mat-form-field must contain a MatFormFieldControl."
4. If you remove mat-label it works 
 
#### Expected Behavior

What behavior were you expecting to see?
It should not throw any exception

#### Actual Behavior

What behavior did you actually see?
Throws ERROR
Error: mat-form-field must contain a MatFormFieldControl.

#### Environment

- Angular: 9.0.6
- CDK/Material: 9.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because you need to import the `MatInputModule`.

**Comment by santoshyadav198613** [comment]
Oops sorry, I don't know what I was thinking, thanks for the answer.
