### ISSUE TITLE
bug(select): update mat-select to match latest version of the spec

### ISSUE THREAD

**Issue by gabrielgambarra** [angular/components#18928]
#### What are you trying to do?

I'm trying to use the [mat-select-trigger](https://material.angular.io/components/select/overview#customizing-the-trigger-label) and when I use the prop 'multiple', the size of select panel grows.

The size of select panel must have the size of the mat-form-field.

#### What troubleshooting steps have you tried?

```
::ng-deep .cdk-overlay-pane {
  .mat-select-panel {
    min-width: 100% !important;
    transform: translateX(40px) !important;
  }
}
```

With the code above on the SCSS of my component, I'm able to reduce the width size of select panel, but when I reduce it, the orientation of select panel goes to left so I use transform to put it on 'center'. Like this:

![image](https://user-images.githubusercontent.com/33934389/77695483-3a229d00-6f82-11ea-96c1-c49d4fea5640.png)

But the problems with this 'solution' are:

- All the selects of my app are affected.
- It's not the default appearance of the mat-select.

#### Reproduction

```
<mat-form-field fxFlex floatLabel="always" shouldLabelFloat="false" appearance="outline">
    <mat-label>Reparações</mat-label>
    <mat-select [formControl]="reparacoesId" multiple>
        <mat-select-trigger>
            {{temReparacoes() ? (reparacoesId.value[0].repairType | translateEnum: 'reparacao') : ('')}}
            <span *ngIf="reparacoesId.value?.length > 1">
                (+{{reparacoesId.value.length - 1}})
            </span>
        </mat-select-trigger>
        <mat-option panelClass="reparacoes-options" *ngFor="let reparo of this.item.avaliacao.reparos"
            [value]="reparo.id">{{reparo.repairType | translateEnum: 'reparacao'}}</mat-option>
    </mat-select>
</mat-form-field>
```
With the code above I have the next resulte:

![image](https://user-images.githubusercontent.com/33934389/77694604-ad2b1400-6f80-11ea-89ff-19e477a28c17.png)

Steps to reproduce:
1. On ```<mat-select [formControl]="reparacoesId" multiple>``` just use the multiple prop. If you remove the multiple prop, the select turn to normal appearance.

#### Result that I'd like to have

Well, I just want this appearance...

![image](https://user-images.githubusercontent.com/33934389/77696615-09dbfe00-6f84-11ea-9608-2f9bdff724c0.png)

... but with the checkboxes and the right width of a normal mat-select.

#### Environment

- Angular: 7.2.0
- CDK/Material: 7.3.7
- Browser(s): Chrome
- Operating System: Elementary os.

**Comment by crisbeto** [comment]
This is behaving as expected. The select panel is already pretty narrow to begin with and adding a checkbox without extending it is going leave very little space for the option's text.

**Comment by mmalerba** [comment]
Yeah, as @crisbeto mentioned, this is intentional. It's designed so that the option text aligns with the trigger text. At the time this was implemented, that's what the Material Design spec showed. However, at this point the spec has changed https://material.io/components/menus#exposed-dropdown-menu
