### ISSUE TITLE
bug(MatCheckbox): Checkbox not disabled when form is disabled.

### ISSUE THREAD

**Issue by jraadt** [angular/components#18923]
#### Reproduction

https://stackblitz.com/edit/components-issue-g38766?file=src%2Fapp%2Fexample-com

Steps to reproduce:
1. Create a form with a checkbox. Have it enabled in your form definition.
2. Disable form in ngOnInit. All fields become disabled and the disabled() method on the checkbox form element is true, but the checkbox behaves like it's still enabled.
 
 
#### Expected Behavior

What behavior were you expecting to see?

Checkbox should be disabled like the rest of the fields.

#### Actual Behavior

What behavior did you actually see?

Checkbox stays enabled.

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, macOS

**Comment by crisbeto** [comment]
You have a typo in your template. It's supposed to be `formControlName`, not `formGroupName`.
