### ISSUE TITLE
bug(mat-expansion-panel): Focus and hover backgrounds cannot be overridden in CSS

### ISSUE THREAD

**Issue by acohenOT** [angular/components#18920]
#### Reproduction

https://stackblitz.com/edit/angular-nlepch

Steps to reproduce:
<ol>
<li>Hover over a collapsed header. Notice it does not use the color specified in CSS.</li>
<li>Expand the first panel</li>
<li>Click in the first name field</li>
<li>Hover over the expanded header. Notice it does not use the color specified in CSS.</li>
<li>Tap tab twice to put keyboard focus on the 2nd panel header. Notice it does not use the color specified in CSS.</li>
</ol>
 
 
#### Expected Behavior

Use the background color specified in CSS, for normal, hover, and focus states.

#### Actual Behavior
On hover over a collapsed header, the component is forcing a specific background color.

On hover over an expanded header, the component is forcing its background to inherit from the panel itself. 

When keyboard focus is placed into a collapsed header, the component is forcing a specific background color.

The only way to override this is seemingly to use **!important** or to override the generic mat-expansion-panel-header class.

This appears to be a regression as it worked in some prior version of Angular Material (though I can't say exactly which).

#### Environment

- Angular: 9.0.7
- CDK/Material: 9.1.3
- Browser(s): Chrome
- Operating System : Windows

**Comment by Totati** [comment]
Of course you can, you just need to be more specific :)
https://stackblitz.com/edit/angular-nlepch-ntwzxz

**Comment by acohenOT** [comment]
@Totati thank you for your reply. Yes, I know you can set them by overriding the generic class names. What does not work is using a specific class name. Your styles might affect other components that are using mat-expansion-panel.

See this updated example. When I change your mat-expansion-panel-header to **my-expansion-panel-header**, your styles no longer work.

https://stackblitz.com/edit/angular-nlepch-wz79io

**Comment by Totati** [comment]
@acohenOT for me your second example works correctly.

**Comment by acohenOT** [comment]
@Totati step 1 does work, you're right. However steps 2 - 5 from the original bug report do not work.

**Comment by acohenOT** [comment]
Made some adjustments to the styles and it's working now. Thanks @Totati .

https://stackblitz.com/edit/angular-nlepch-wz79io
