### ISSUE TITLE
help([google-maps]): [Working example of testing a component which uses a google map]

### ISSUE THREAD

**Issue by vbourdeix** [angular/components#18926]
Is there an example project somewhere showing how to test a component using a google-map component ? I've tried a lot of things, but I had to give up.

For example I tried using the following code in my beforeEach :
```
    mapSpy = createMapSpy(DEFAULT_OPTIONS);
    mapConstructorSpy = createMapConstructorSpy(mapSpy);
```
But I still get an error such as "Uncaught TypeError: googleMap.setOptions is not a function "

**Comment by sqljim** [comment]
Am having the same problem with Angular 9.1 where I'm getting ReferenceError: google is not defined, so I'd love to see a working example too..

**Comment by maroon17** [comment]
+

**Comment by crisbeto** [comment]
We've got tests for the Google Map and related components that can be used as a reference: https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.spec.ts#L56

@vbourdeix your test seems to be failing because your mock is incomplete.

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
