### ISSUE TITLE
bug([mat-select]): [RangeError: Maximum call stack size exceeded when using mat-select in formarray]

### ISSUE THREAD

**Issue by specialsagar** [angular/components#18932]
#### Overview of the Issue
When using mat-select inside angular's reactive formarray, it always ends up returning with max call stack exceeded.

#### Reproduction
https://stackblitz.com/edit/angular-mat-select-in-form-array
 
#### Expected Behavior
It should work in the same manner as mat-input.

#### Actual Behavior

What behavior did you actually see?
ERROR RangeError: Maximum call stack size exceeded
    at eval (validators.ts:419)
    at eval (validators.ts:460)
    at Array.map (<anonymous>)
    at _executeValidators (validators.ts:460)
    at eval (validators.ts:420)
    at eval (validators.ts:460)
    at Array.map (<anonymous>)
    at _executeValidators (validators.ts:460)
    at eval (validators.ts:420)
    at eval (validators.ts:460)

#### Environment

- Angular: 8.3.25
- CDK/Material: 8.2.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by trik** [comment]
it's not related to mat-select, you are iterating over credentials.value instead of credentials.controls
here a working example
https://stackblitz.com/edit/angular-mat-select-in-form-array-mbspwp

**Comment by crisbeto** [comment]
Closing since it seems to be fixed by the suggestion from @trik.
