### ISSUE TITLE
Can't make multi-line matTooltip, always getting single-line

### ISSUE THREAD

**Issue by alireza-saberi** [angular/components#18941]
#### Bug, feature request, or proposal:
Bug: Multiple line tool-tip

#### What is the expected behavior?
Using `[matTooltip]="myMultiLineStringGenerator()"` combined with `[matTooltipClass]="'my-tooltip'"` gives me multi-line tooltips

#### What is the current behavior?
I get one liner tooltip, and I have no control when lines ends and moves to the next line

#### What are the steps to reproduce?
html
```
<p  [matTooltipClass]="'my-tooltip'"
       [matTooltip]="getTooltopScript(nearestStations)">
                Hello World!
</p>
```

typescript
```
getTooltopScript(ns: any[]]){
          let part1 =  ns[0]['stationName'] ;
          let part2 = ns[0]['regionName'];
          return `${part1}.\r\n\
           ${part2}.`;
}
```

CSS
```
.mat-tooltip {
    white-space: pre-line;
}

::ng-deep .mat-tooltip {
    white-space: pre-line;
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 9,     "@angular/material": "^8.1.4",    "typescript": "~3.7.5", Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by crisbeto** [comment]
Your text probably isn't long enough. Here's an example that shows it breaking into multiple lines. https://stackblitz.com/edit/angular-3sn1ge?file=src/app/tooltip-overview-example.html

**Comment by dhavalkakkad** [comment]
I know this thread is closed, but in case anyone is still looking for help, this solution works for me. 
https://www.angularjswiki.com/material/tooltip/#adding-multiline-tooltip-using-mat-tooltip

Tested and verified for Angular 9. 

I hope this helps. Cheers
