### ISSUE TITLE
Suggestion: Replace `MatDialogRef#getState` with a getter

### ISSUE THREAD

**Issue by EdricChan03** [angular/components#18942]
#### Bug, feature request, or proposal:

The `getState` method of the `MatDialogRef` class should be replaced with a getter:

https://github.com/angular/components/blob/29e74eb9431ba01d951ee33df554f465609b59fa/src/material/dialog/dialog-ref.ts#L213-L216

#### What is the expected behavior?

`getState` should be replaced with a getter:

```typescript
get state(): MatDialogState;
```

#### What is the current behavior?

It isn't a getter:

```typescript
getState(): MatDialogState;
```

#### What are the steps to reproduce?

NIL

#### What is the use-case or motivation for changing an existing behavior?

It would save a few letters from typing the `get` prefix when retrieving the current state of the dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular v9.x.x
- Angular Material v9.x.x (and older)

#### Is there anything else we should know?

Was there any reason as to why a method with a `get` prefix used instead of a getter?

**Comment by crisbeto** [comment]
We try to avoid using getters/setters whenever we can, because they generate more code compared to a regular method when transpiled to ES5.
