### ISSUE TITLE
bug(mat-slide-toggle): Use confirm dialog with slide toggle, if cancel the dialog, should not change the state

### ISSUE THREAD

**Issue by qiufengyu** [angular/components#18950]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-dchf74
Steps to reproduce:
1. Click the slide toggle and select cancel the confirm dialog
2. The state of the toggle still gets changed

After some research, `(ngModelChange)="onHide()"` will have the old value before toggling. Resetting value in the function body does NOT work. The implementation of slide-toggle is not something like `slideToggleValue = !slideToggleValue`?

event.stopPropogation() does NOT work also. 

Wondering if there could be a workaround. Many thanks.
 
 
#### Expected Behavior

If click cancel, the state of the toggle should remain the old value.

#### Actual Behavior

If click cancel, the state of the toggle still gets changed

#### Environment

- Angular:
- CDK/Material:^9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by devversion** [comment]
The NgModel behaves as expected. It will always emit the new/current value.

To achieve what you want, best would be to just prevent the click and `keydown#space` event. Angular has nice syntactic sugar to listen to the space keypress.

See my updated StackBlitz: https://stackblitz.com/edit/angular-dchf74?file=src%2Fapp%2Fslide-toggle-overview-example.ts

**Comment by qiufengyu** [comment]
> The NgModel behaves as expected. It will always emit the new/current value.
> 
> To achieve what you want, best would be to just prevent the click and `keydown#space` event. Angular has nice syntactic sugar to listen to the space keypress.
> 
> See my updated StackBlitz: https://stackblitz.com/edit/angular-dchf74?file=src%2Fapp%2Fslide-toggle-overview-example.ts

Thanks for the reply.
If someone click "cancel" in the confirm dialog, the state should not be change. The updated repo does not solve the problems.
Users may not want to press space to switch the content.

**Comment by devversion** [comment]
Looks like I didn't share the right StackBlitz. https://stackblitz.com/edit/comp-18950?file=src%2Fapp%2Fslide-toggle-overview-example.ts.

Does that work better for you?

**Comment by qiufengyu** [comment]
Thank you Paul. This is exacty what I want.
