### ISSUE TITLE
Disabled buttons contrast ratio is not WCAG 2.1 compliant

### ISSUE THREAD

**Issue by micamp** [angular/components#18954]
#### Bug, feature request, or proposal:
Disabled buttons color should contrast with the background with at least a 3:1 ratio to meet new WCAG 2.1 requirements.

#### What is the expected behavior?
Disabled buttons color should contrast with the background with at least a 3:1 ratio to meet new WCAG 2.1 requirements.

#### What is the current behavior?
Disabled buttons color contrast compared to the background is less than the required 3:1 ratio.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

https://material.angular.io/components/button/examples
Use a color contrast tool to measure the contrast of a disabled button text color and the background.

#### What is the use-case or motivation for changing an existing behavior?
The WCAG 2.1 standard will go into effect June 30, 2020.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, all browsers.

#### Is there anything else we should know?
Thank you

**Comment by manklu** [comment]
@micamp

> Disabled buttons color should contrast with the background with at least a 3:1 ratio to meet new WCAG 2.1 requirements.

Can you state the source of the requirement? AFAIK inactive  user interface components don't have a contrast requirement.

See https://www.w3.org/TR/WCAG21/#contrast-minimum and https://www.w3.org/TR/WCAG21/#contrast-enhanced

> The visual presentation of text and images of text has a contrast ratio of at least ..., except for the following:
...
Incidental: Text or images of text that are part of an inactive user interface component ...
...

**Comment by amysorto** [comment]
As mentioned by @manklu, disabled elements don't seem to need to meet color contrast requirements in WCAG 2.1 and the same is true for WCAG 2.2: https://www.w3.org/TR/WCAG22/#contrast-minimum. Closing this bug.
