### ISSUE TITLE
Input Placeholder keeps rotating.

### ISSUE THREAD

**Issue by sauravgaursmith** [angular/components#18952]
Guys I need your help. I'm facing an issue only on Firefox. This is related to Angular 4 (This version is not supported now). Have look on attached gif. I'm not getting this issue on every system. This seems to be a system specific issue. This is due to transform property of CSS keeps changing. Not able to find root cause why transform property keeps changing.
![firefoxbug](https://user-images.githubusercontent.com/25001992/77949147-1c3b9c00-72e4-11ea-99d6-7b5d06ef5eac.gif)

Firefox Details:
![firefox-version](https://user-images.githubusercontent.com/25001992/77949817-33c75480-72e5-11ea-88b2-f69c7a21c820.png)

#### Environment
- Angular: 4.4.6
- CDK/Material: 4.4.6
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by jelbourn** [comment]
There is no 4.x version of Angular Material or CDK; it was 2.0.0-beta, and then it jumped to 5.

Either way, Angular 4 is far enough back that there's not really anything we'd be able to help with here.
