### ISSUE TITLE
bug(radio): not compatible with typescript useDefineForClassFields compiler option

### ISSUE THREAD

**Issue by nicolashenry** [angular/components#18973]
#### Reproduction

Steps to reproduce:
1. Add ```"useDefineForClassFields": true,``` to tsconfig.json in a project that use ```@angular/material/radio```
2. Run ```ng serve```
 
 
#### Expected Behavior

No error

#### Actual Behavior

This error occurs:
```
ERROR in node_modules/@angular/material/radio/radio.d.ts:183:9 - error TS2611: 'disabled' is defined as a property in class 'CanDisableRipple & HasTabIndex & MatRadioButtonBase', but is overridden here in 'MatRadioButton' as an accessor.

183     get disabled(): boolean;
            ~~~~~~~~
```

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 7

**Comment by devversion** [comment]
Thanks for this issue. Let's track of support for `useDefineForClassFields` in a dedicated issue: https://github.com/angular/components/issues/19221.
