### ISSUE TITLE
bug(google-maps): Inconsistent naming/visibility/optionality of properties for the JavaScript API objects

### ISSUE THREAD

**Issue by eamon-otuathail** [angular/components#18979]
#### Expected Behavior
Consistent naming/visibility/optionality should be applied to all seven of the Angular Google Maps components and the underlying Google Maps JavaScript API objects they manage. 

#### Actual Behavior
The Public API to Angular Components' Google Maps Package is here:
https://github.com/angular/components/blob/master/tools/public_api_guard/google-maps/google-maps.d.ts
6 out of the 7 Angular classes make available as a public property the JavaScript API object they manage: 
~~~~
class GoogleMap: 	_googleMap: UpdatedGoogleMap;
class MapMarker:	_marker?: google.maps.Marker;
class MapCircle: 	circle: google.maps.Circle;
class MapPolygon:	_polygon: google.maps.Polygon;
class MapPolyline:	_polyline?: google.maps.Polyline;	
class MapRectangle:	_rectangle: google.maps.Rectangle;
~~~~
The 7th component prefixes its internal JavaScript API object with "private" so it is not part of the public API:  
https://github.com/angular/components/blob/master/src/google-maps/map-info-window/map-info-window.ts
~~~~
class MapInfoWindow {
  ..
  private _infoWindow?: google.maps.InfoWindow;
}
~~~~
I see four (easy to fix) problems with the above arrangements. 

There is inconsistent naming - MapCircle has "circle" (no underscore) whereas the others do start with an underscore. 
I don't think any property whose name starts with an underscore should be publicly made available. 
There is inconsistent visibility: MapInfoWindow's underlying object is marked private, the others not. 
There is inconsistent optionality: marker?, polyline? and _infoWindow? are marked optional, the others not. 

The same naming/visibility/optionality rules should applied  for all seven components. There are valid reasons why app developers using Angular might want to get access to the underlying Google Maps JavaScript API object, so the MapCircle approach seems best, and it should  be consistently applied to the other components.

**Comment by jelbourn** [comment]
The real question is why `circle` isn't marked as internal like the rest.  @mbehrlich?

**Comment by mbehrlich** [comment]
Should be fixed now. Circle in particular just happened to be fixed before the others. All are now public properties.
