### ISSUE TITLE
bug([moment-date-adapter]): MomentDateAdapter not guarding against `undefined` locale 

### ISSUE THREAD

**Issue by moritzgloeckl** [angular/components#18971]
#### Reproduction

Using the `MomentDateAdapter` and setting up the locale as `undefined` leads to an error. Calling `this._adapter.setLocale(undefined)` is not throwing an exception. When the `MomentDateAdapter` calls `createDate()`, it specifically calls:

`const result = this._createMoment({year, month, date}).locale(this.locale);`

Since `this.locale` is `undefined`, the `locale()` method of moment acts as a getter, thus returning a default locale such as `en`.

The `MomentDateAdapter` further checks for

`if (!result.isValid())`

which is failing, because the method `.isValid()` does not exist for type `string`.
 
 
#### Expected Behavior

`setLocale()` should guard against an `undefined` value, or the `createDate()` method should deal with this unexpected behavior more gracefully.

#### Actual Behavior

`MomentDateAdapter` initialization fails with `ERROR TypeError: result.isValid is not a function`

**Comment by crisbeto** [comment]
The code explicitly requires a `string` to be passed in. If you enable `strictNullChecks` in your `compilerOptions` it'll catch issues like this during compilation.

**Comment by annieyw** [comment]
Closing this as this seems to be resolved.
