### ISSUE TITLE
docs-bug([COMPONENT]): [TITLE]

### ISSUE THREAD

**Issue by CryHenry** [angular/components#18975]
I can't find any documentation or examples of how to get the component to fitBounds(). I'm using the <google-maps> component in another component with an @Input for the locations of markers, but the map refuses to fitBounds() or panToBounds().

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
