### ISSUE TITLE
bug(tabs): Missing ink bar with primary color palette mat-palette(*, 1000)

### ISSUE THREAD

**Issue by iget-esoares** [angular/components#18978]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Create application with custom theme, using `$primary = mat-pallete($any-color, 1000)`
2. Add the sample mat-tab from documentation

StackBlitz: https://stackblitz.com/edit/components-issue-9psapx
 
 
#### Expected Behavior

The Ink bar behind selected tab label should appear.

#### Actual Behavior

The Ink bar behind selected tab label doesn't appear. Changing theme to `$primary = mat-pallete($any-color, 900)` works.

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.0
- Browser(s): Version 80.0.3987.162 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 18.04

**Comment by jelbourn** [comment]
`1000` isn't a valid Material Design hue: https://material.io/design/color/#tools-for-picking-colors

**Comment by iget-esoares** [comment]
Makes sense! :innocent: sorry!
