### ISSUE TITLE
docs-bug(datepicker): matDatepickerFilter API documentation has incorrect type

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#18986]
#### Documentation Feedback

The API documentation for matDatepickerFilter shows it's type as  `(date: D) => boolean` when it's actually  `(date: D | null) => boolean`.  

It also doesn't explain what conditions would cause it to get called with a null value.  

I noticed the example on the Examples tab does have the correct type, but just does a (d || new Date()) and gives no reason for why null should be treated as the current datetime.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

https://material.angular.io/components/datepicker/api#MatDatepickerInput
https://github.com/angular/components/blob/master/src/material/datepicker/datepicker-input.ts#L118

**Comment by crisbeto** [comment]
Since the docs are generated from the source, it means that either the content on the site is outdated (unlikely since the type hasn't changed in 2 years) or the docs generation script is doing something weird.

**Comment by crisbeto** [comment]
Since this issue was filed we've introduced a `DateFilterFn` type which seems to solve the original problem. I'll close the issue.
