### ISSUE TITLE
mat-checkbox doesn't support [checked] and formControlName alongside

### ISSUE THREAD

**Issue by Napstergfr** [angular/components#18993]
Whenever i am using **formControlName** and **[checked]** at the same time it is not working.
I am not using **[(ngModel)]** as this is a form array and it's generating dynamically.
Here is my code:

> `<mat-checkbox
>               color="primary"
>               [formControlName]="'idChecked'"
>               class="font-medium"
>               [checked]="eSc.includes(eS[i].id)">
>               {{  eS[i].name }}
>  </mat-checkbox>`

**Comment by crisbeto** [comment]
The two aren't intended to be used together since it's not clear what happens if their values conflict with each other. If you want something to be pre-checked, you can do it through the `FormControl`.

**Comment by Napstergfr** [comment]
Thank you for the clarification !
