### ISSUE TITLE
bug([COMPONENT]): [TITLE] Material tooltip should be enabled on [matTooltipDisabled]="0" 

### ISSUE THREAD

**Issue by shaheerkhan12605** [angular/components#19007]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-6fypne

Steps to reproduce:
1. create a div with mat-tooltip
2. on [matToolTipDisabled] pass 0 as input
 
 
#### Expected Behavior

What behavior were you expecting to see?
As matToolTipDisabled receive boolean Input so if we use `[matTooltipDisabled]= "0"` in html template then the matTooltip should be enabled , **0** is to be considered as falsy value

#### Actual Behavior

What behavior did you actually see?
 I am using `[matTooltipDisabled]= "0"` in html template and matTooltip is still disabled in the template

#### Environment

- Angular: 7.2.7 & 9.1.0
- CDK/Material:7.2.0 & 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS(10.14.6)

**Comment by crisbeto** [comment]
The input is explicitly set to require a boolean so passing in other random values is at your own risk.
