### ISSUE TITLE
bug(cdkScrollingModule): No list-items using server-side-rendering (angular-universal)

### ISSUE THREAD

**Issue by Tobitubbie** [angular/components#19012]
#### Bug, feature request, or proposal:
When using angular-universal's server-side-rendering in combination with the `cdkScrollingModule` the rendered html-document returned by the server never contains any list-items.

_Reason why this happens:_  
During the rendering process on the server the variable `elementRef` in the component `cdkVirtualScrollViewport` has no property called `clientHeight` nor `scrollTop`.

As a result the method `updateRenderedRange` sets `scrollOffset` and `viewportSize` to _undefined_ which leads to a wrong renderedRange.

#### What is the expected behavior?
There should be a (configurable) fallback value if those essential properties are missing, so the document that is sent to the client contains at least some list-elements.

#### What is the current behavior?
The rendered document does not contain any list-items.

#### What are the steps to reproduce?
1. Set up an angular-universal app
2. Import the ScrollingModule of `@angular/cdk`
3. Disable the execution of JavaScript on the client (that only the html-document returned by the server is shown)
4. Request the page containing the list

#### What is the use-case or motivation for changing an existing behavior?
Due to the server-side-rendering the user sees the website much faster (while the angular-application still loads) but it only shows an empty list which is not quite useful.  
As a result the whole performance-boost brought with angular-universal is lost.

#### Environment
Angular: 9.1.0
CDK/Material: 9.2.0
Browser(s): Chromium 80.0.3987.162
Operating System: Windows 10

**Comment by crisbeto** [comment]
The `CdkVirtualScrollViewport` has a method called `setRenderedRange` which you can use to tell it how many its should be shown. E.g. calling it with `{start: 0, end: 10}` will show the first 10 items. You should be able to get a hold of the viewport and tell it how many items you want to be shown this way.

**Comment by Tobitubbie** [comment]
Thanks @crisbeto that works just like expected :)

I had to add this code into the `AfterViewChecked`-Hook where i check if the **platform is a server** and if the **viewport is initialized** _(it runs through several angular-hooks until it's not undefined anymore)_.

For others running over the same problem here is my code snippet:
```ts
export class ListComponent implements AfterViewChecked {

   @ViewChild(CdkVirtualScrollViewport) scrollViewport: CdkVirtualScrollViewport;

   constructor(@Inject(PLATFORM_ID) private platformId: object) { }

   ngAfterViewChecked(): void {
      if(this.scrollViewport && isPlatformServer(this.platformId)) {
         this.scrollViewport.setRenderedRange({start: 0, end:10});
      }
   }
}
```
