### ISSUE TITLE
help(SnackBar): Electron and Snackbar don't work well together

### ISSUE THREAD

**Issue by ErraticFox** [angular/components#19011]
#### What are you trying to do?

I'm building an Electron Desktop application using Angular Material. When communicating with the back end of the app to get information, sending it to the front end of the app and displaying that data via snackbar. To listen for the event on the front end (getting the data from the back to the front) I use the listener for `ipcRenderer` like so

```ts
this.ipc.render.on('test', (e, res) => {
	snackbar.open(res, 'close')
})
```

this works somewhat. For some reason, it auto-positions it to the top left. Clicking the action button will make it snap to the default original position or to the position in the config, if you have one set. Then the action button will do nothing after this, after clicking anywhere on the app except the action button, it'll disappear. If there is no action button set, it will not disappear.

#### What troubleshooting steps have you tried?
The first line in this example down below will work perfectly fine and will use the config. The one inside the listener wont apply the config until after the action button is clicked and then clicked outside of it (as stated before) 
```ts
snackbar.open(res, 'close', config)
this.ipc.render.on('test', (e, res) => {
	snackbar.open(res, 'close', config)
})
```

#### Reproduction

I have tried to recreate this in StackBlitz as at first I thought it was having trouble updating the view or communicating with the service and components, but it seems to be between Electron and snackbar specifically (all other components don't have troubling relaying data from Electron).
  
I can make a git here soon for reproduction (I recreated a lot of my app from the ground up to only hit this again)
#### Environment

- Angular: 9.0.7
- CDK/Material: 9.2.0
- Browser(s): Electron/Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It might be worth wrapping your `open` call in an `NgZone.run`.

**Comment by ErraticFox** [comment]
@crisbeto I had tried this before and it didn't work because I had put it around the listener. Though I was going to try this before making my git repo for the test, but forgot and after painstaking putting together the test repo for the error, I tried this (only around the snackbar inside the listener) and it's working. (╯°□°）╯︵ ┻━┻

Appreciate it!
