### ISSUE TITLE
Datepicker Input - (beginDateSelectedChange)

### ISSUE THREAD

**Issue by varun1233** [angular/components#19017]
#### Feature Description

Is it possible to add beginDateSelectedChange feature of sat-calendar to the datepicker-input?

#### Use Case

The need arises in cases when we want to restrict the user to a selected end date based on the begin date selected by the user. Currently there are only two Event Emitter supported by the datepicker-input that are (dateChange) and (dateInput) both of which fires event after both begin and end date are selected, which does not fullfill the current requirement.
Is there any future scope to add the feature to date-picker Input also?

**Comment by crisbeto** [comment]
There is no "begin" stage of selecting a date. It's just the user clicking on something and it gets selected immediately.

**Comment by mmalerba** [comment]
This is not an API pattern we use widely if at all in this library, so I don't think we want to add it. If you want to restrict what dates are selectable I suggest using validation instead: https://material.angular.io/components/datepicker/overview#date-validation The datepicker support min and max validation as well as a filter function
