### ISSUE TITLE
bug([Button Toggle Group]): [Material Toggle buttons do not completely disable through bindings]

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#19028]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-jpbbaq?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Material Toggle Button group when given the attribute "disabled" or having event binding 
"[disabled]=true" does not completely disable the button.
2. The button APPEARS to be disabled but it's not preventing the user clicking on it - which it should and also have cursor be cursor: not-allowed
 
 
#### Expected Behavior

What behavior were you expecting to see?
Completely disabled buttons with disabled attribute set or bindings set to true

#### Actual Behavior

What behavior did you actually see?
The button APPEARS to be disabled but it's not preventing the user clicking on it - which it should and also have cursor be cursor: not-allowed

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina

Angular CLI: 9.1.0
Node: 12.16.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular-devkit/schematics-cli    0.13.9
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.0.7
@schematics/angular               9.1.0
@schematics/schematics            0.13.9
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

**Comment by crisbeto** [comment]
The `disabled` attribute only blocks click events on native browser elements (e.g. `button`). Since `mat-button-toggle` is a custom element, the attribute won't block your custom `click` handler. In your example, you should be able to remove the `click` handlers completely since the toggle group keeps track of the value for you.
