### ISSUE TITLE
bug(chips): Returning array of objects from a component method will hang application

### ISSUE THREAD

**Issue by gentunian** [angular/components#19045]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-fpjhzo

Steps to reproduce:
1. Open the stackblitz link above
2. Slide toggle "show bug".
 
#### Expected Behavior

We are expecting to see the chips component.

#### Actual Behavior

Application hangs.

#### Environment

StackBlitz environment posted above.

## Background

When using `*ngFor` directive behaviour differs from using a component method or an inline array. 

This code works:
```
<div *ngFor="let item of [{}]">
  <mat-chip-list>
    <mat-chip>chip</mat-chip>
  </mat-chip-list>
</div>
```

This code breaks and hangs the entire browser:
```
// HTML
  <div *ngFor="let item of some()">
    <mat-chip-list>
      <mat-chip>another chip</mat-chip>
    </mat-chip-list>
  </div>

// Component code
some() { return [{}]; }
```

I've searched "mat-chip-list nfor" and no issues where found.

**Comment by crisbeto** [comment]
It happens because the `some` method returns a different array every time it is invoked, causing change detection to be run continuously. The inline example works, because Angular can detect it inside of a template and prevent it from happening. It'll work if you move the array to a property.

**Comment by gentunian** [comment]
@crisbeto but this does not happen with another component. It's happening with chips.

**Comment by crisbeto** [comment]
I'm guessing there's something that triggers change detection when chips are initialized which causes it to keep re-rendering.

**Comment by gentunian** [comment]
Weird thing is that the example deliberately uses chips with static data from the template. Why would change detection triggers?
