### ISSUE TITLE
bug([drag-drop]): Draggables are not updating when transferring items to a new array using the DragDrop Service

### ISSUE THREAD

**Issue by uncvrd** [angular/components#19049]
#### Reproduction

StackBlitz recreation of the problem: https://stackblitz.com/edit/angular-kj7y4p

Steps to reproduce:
1. Drag and drop an item from the top list to the bottom list
2. Try to drag that same item after dropping it, you can no longer pick it up!

I have a certain situation where I need to create a multi-list drag and drop in my project using the `DragDrop` service. I am able to successfully move items around within it's parent list, but when I try and transfer that item to a new list, I've discovered that the `_draggables` property does not update to transfer the item to the new list. Therefore, once I move the item to a new list, I can no longer drag it.

![Alt Text](https://media.giphy.com/media/Za2T3ufb976pfLDusw/giphy.gif)

In this gif, I drag `Get To Work` to the second list, and try and drag that element again after dropping, I cannot. At the very end I show that I **can** pick up the list item `Get Up` above it though.
 
#### Expected Behavior

I expect to be able to drag and drop an item into a new array, and then pick that same item back up and drag and drop it around either list, but instead, the item is no longer draggable.

#### Actual Behavior

When dropping an item in to a different list, I cannot pick it back up to drag again.

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.0
- Browser(s): Chrome  80.0.3987.163
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This is working as expected. The drop list doesn't know how your data or the elements are set up so it's up to you to call `withItems` again with the updated list. The `DragDrop` is meant to be used when you're building custom drag&drop directives and it requires a bit more manual work. We're doing the same in the built-in `CdkDropList` directive. A good place to do it is in the `beforeStarted`.
