### ISSUE TITLE
docs-bug(material-docs): add readme file on how to contribute to docs

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/components#19042]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

Angular has https://github.com/angular/angular/blob/master/aio/README.md  which explains, how to contribute to docs, can't find the same for the material.

Feel free to provide any suggestions of content or examples you’d like us to include.

I would love to help with creating the docs.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by Splaktar** [comment]
You can find it here: https://github.com/angular/material.angular.io#contributing

I added some details about how the docs are generated last summer. However, the current docs structure isn't well documented and the development process is fragmented.

## If you are just fixing docs-infrastructure and not content
You can do that pretty easily in the https://github.com/angular/material.angular.io repo.

## If you are fixing examples/demos
You can do that in this repo via the dev-app (`yarn dev-app`) and using the page that lists all of the Examples.

## If you are fixing docs content
This is where things are messy and not well documented. There are some hacks and workarounds, but I haven't yet found a productive and repeatable way to do this or document it. There is an existing desire/issue to refactor how the docs are generated to solve this, but I don't have an ETA. Right now, I basically have to make the changes in the best way that I can (referring to how other docs content renders for other components) in this repo, get the changes merged, and then review them in the https://github.com/angular/material.angular.io repo using `yarn build:content`. If there are still some minor issues, I need to submit another PR, repeat as needed. It's too painful.

**Comment by santoshyadav198613** [comment]
Thanks @Splaktar , My issue was related to "fixing docs content" so should I close this one, as there is something already in discussion.

**Comment by devversion** [comment]
I'm not sure what's best here. I could imagine us capturing the information @Splaktar provided, but at the same time, I'm hoping that we can simplify the process in the future. i.e. by using a monorepo.

**Comment by Splaktar** [comment]
Yes, I think that we need to make the docs content process more well defined and productive/accessible. But do we have another issue tracking that infrastructure issue (that should be P2 or P3) as this one is more about contributor docs?

**Comment by mmalerba** [comment]
Closing since the current contributing doc now has links to where the content is generated from: https://github.com/angular/material.angular.io#where-does-the-content-come-from
