### ISSUE TITLE
bug([MatExpansionModule]): [Double scroll on iOs]

### ISSUE THREAD

**Issue by Merwan1010** [angular/components#19050]
![image](https://user-images.githubusercontent.com/42877823/79059832-7ca1e480-7cb9-11ea-95a7-61cab79a2881.gif)

![image](https://user-images.githubusercontent.com/42877823/79059818-4d8b7300-7cb9-11ea-94a0-6363e666bea5.gif)

#### Reproduction
Steps to reproduce:

/!\ Only on iOs Native
1. Use the mat-expansion-panel with the setting [expand] on true on init
2. Fill it with a scrollable div
3. Scroll the div
 
 
#### Expected Behavior
Only the div should be scrolling

#### Actual Behavior
The div and the page are scrolling

#### Code

```
<ion-item *ngFor="let el of [].constructor(5) ; let i = index" style="width:100%;" style="color : blue">
        {{i}}
      </ion-item>

      <mat-accordion >
        <mat-expansion-panel
                [expanded]="isOpen"
        >

          <mat-expansion-panel-header>
            <mat-panel-title>
              <p>Example</p>
            </mat-panel-title>
            <mat-panel-description>
              <p>Hi</p>
            </mat-panel-description>
          </mat-expansion-panel-header>


          <div class="fixed" scrollY="true" style="max-height: 35vh ; border : 1px solid black">
            <ion-list>
              <ion-item *ngFor="let el of [].constructor(10) ; let i = index" style="width:100%;">
                {{i}}
              </ion-item>
            </ion-list>
          </div>
        </mat-expansion-panel>
      </mat-accordion>

      <ion-item *ngFor="let el of [].constructor(30) ; let i = index" style="width:100%;"  style="color : blue">
        {{i}}
      </ion-item>
```

```
.fixed[scrollx=true], div[scrolly=true] {
  position: relative;
  overflow: hidden;

  ::-webkit-scrollbar {
    display: none;
  }
}

.fixed[scrollx=true] {
  overflow-x: auto;
}

.fixed[scrolly=true] {
  overflow-y: auto;
}

```

#### Environment

Angular CLI: 8.1.3
Node: 12.3.1
OS: darwin x64
Angular: 8.1.3

**Comment by crisbeto** [comment]
This looks like an OS-level issue. The expansion panel doesn't do much, aside from setting a height and animating it.

**Comment by josephperrott** [comment]
This is indeed an artifact of the way which iOS handles scrolling related to `overflow: hidden`.  Additional investigation would be needed to determine if we can change how we set overflows on the expansion panel.

**Comment by MadyAkira** [comment]
Thanks for your comment guys. For now im keeping the component open oninit to avoid the glitch, but i hope we could find a solution. 🤗

**Comment by crisbeto** [comment]
Closing the issue since it isn't something we have much control over. The expansion panel is basically just a `div` with `overflow: auto` so it's to the browser to determine when to scroll.
