### ISSUE TITLE
bug([button mat-fab]): Button Circle doesn't grow with text

### ISSUE THREAD

**Issue by palminha** [angular/components#19058]
#### Reproduction

Steps to reproduce:
1. code to replicate `<button mat-fab color="accent" routerLink="/step1">CLICK HERE TO START</button>`

#### Expected Behavior

The button should grow.

E.g. if we use the raised button it grows with text:
`<button mat-raised-button color="accent" routerLink="/step1">CLICK HERE TO START</button>`

#### Actual Behavior

The fab button doesn't grow to include all the text inside

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.0
- Browser(s): Google Chrome 
- Operating System: Ubuntu

**Comment by mmalerba** [comment]
This is supported now through the extended fab variant, though it appears we forgot to add documentation about it, so I've opened a PR to do so.
