### ISSUE TITLE
bug([website]): [Side Panel Toggle Issue | Safari]

### ISSUE THREAD

**Issue by arjunkesava** [angular/components#19068]
#### Reproduction

This is not a component bug. This is a angular material website issue.

Steps to reproduce:
1. Open Safari Browser.
2. Open any component page (ex: https://material.angular.io/components/bottom-sheet/examples)
3. Click on the side nav panel's any header (ex: Navigation or Layout) 

> In the below image, the `Layout`, `Buttons & Indicators` should open, but they were hidden.

![image](https://user-images.githubusercontent.com/16076136/79187999-7dfb1a80-7e3b-11ea-9da3-5ab23d103443.png)

#### Expected Behavior

What behavior were you expecting to see?
- On the click of side pane, list header, the list should toggle

#### Actual Behavior

What behavior did you actually see?
- But its not getting open after closing it.

#### Environment

- Angular: 
- CDK/Material: 9.2.0
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15

**Comment by jelbourn** [comment]
This should be addressed by work @annieyw is already doing (we're getting rid of the expand/collapse in the nav)

**Comment by annieyw** [comment]
Closing since the expand/collapse sections in the side nav have been removed.
