### ISSUE TITLE
bug with testing MatSelect using getHarness and getOptions

### ISSUE THREAD

**Issue by metalllus** [angular/components#19075]
#### Reproduction

Steps to reproduce:
When I have multiple matSelect elements on page, I use getHarness() method with an appropriate selector to get the required harness. When I use the getValueText() method on the grabbed harness, I get the expected value. However if I then use the getOptions method on this harness, I get the options from the very first matSelect element on the page and not the options from the matSelect harness I got using the selector. 
 
 
#### Expected Behavior

Get the correct options from the MatSelectHarness grabbed using a selector.

#### Actual Behavior

I get the options from the very first matSelect element on page and not the options from the matSelect harness I got using the selector. 

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): latest Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Can you post what your test and test component look like?
