### ISSUE TITLE
help([MatTable]): [trackBy on a MatTable tied to a FormArray seems to fail]

### ISSUE THREAD

**Issue by LioSergent** [angular/components#19081]
Hello ! Sorry if this is not the right place to post such an issue. At this point it looks like a bug to me, but maybe I am just not using Angular properly. 

#### What are you trying to do?
Use trackBy to speed up a large and somewhat complex editable table that we previously built using mat-table and a FormArray where the user can create, update, delete rows and save changes.

### What are you seeing that does not match your expectations? 
Adding the trackBy property with a simple tracker function (obj => obj.id) makes deletion of lines of the table not rendered properly even if the data in the component looks correct.

#### What troubleshooting steps have you tried?
-Removing the trackBy, which works but causes other problems in the application I'm working on.
-Changing the tracker function with various approaches, which yields a variety of results, but never exactly what I am looking for and/or not usable in my real case. 
-Make the table not tied to a form, which works but defeats my actual use of using the power of Angular reactive forms for edition, validation...
-Use a FormGroup (keyed on id) instead of a FormArray, which works but complexifies data management in my case as change detection is different. This is the workaround I am trying to make work on my real-case right now. [EDIT]: so this approach works well, but I am still wondering why it's not working with a FormArray. 

#### Reproduction
I tried to isolate the problem as much as I could within: 
[]https://stackblitz.com/edit/angular-rijqud?file=src%2Fapp%2Fapp.component.ts

Try to delete Chris for instance. You'll see Serena appear twice. Basic console.logs seem to indicate data is correct. 
  
#### Environment
Tried:
- Angular: 7.2.0 & 9.1.0
- CDK/Material: 7.3.7 & 9.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

Thanks a lot !

**Comment by andrewseguin** [comment]
I tried digging into the example but it's a bit more complex than I have time to investigate into. I think asking on StackOverflow might be a better way to go.
