### ISSUE TITLE
error NG8001: 'cdk-virtual-scroll-viewport' is not a known element:

### ISSUE THREAD

**Issue by aduyinuo** [angular/components#19084]
I used the` <cdk-virtual-scroll-viewport>` component in my html

#### Actual Behavior
But constantly getting 
```
 ERROR in new-post.component.html:73:1 - error NG8001: 'cdk-virtual-scroll-viewport' is not a known element:
    1. If 'cdk-virtual-scroll-viewport' is an Angular component, then verify that it is part of this module.
    2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
```
error

#### Environment
I have angular cdk installed;
```
import { ScrollingModule } from '@angular/cdk/scrolling';
import {CdkVirtualScrollViewport} from "@angular/cdk/scrolling";
```
in app.module.js
```
import {ScrollingModule} from '@angular/cdk/scrolling';
import {CdkVirtualScrollViewport} from "@angular/cdk/scrolling";
```
in my new-post component trying to use ` <cdk-virtual-scroll-viewport>` 

What other steps did I miss?

**Comment by mehdifracso** [comment]
You should add the ScrollingModule  to imports in app.module.ts :
imports: [ ScrollingModule, ]

**Comment by devversion** [comment]
Please provide a reproduction. @mehdifracso provided a good hint. At first glance this looks like the module has not been imported correctly.
