### ISSUE TITLE
help([tree]): [Why is there argument "level" in buildFileTree?]

### ISSUE THREAD

**Issue by andreElrico** [angular/components#19090]
#### What are you trying to do?

Trying to understand mat-tree

#### What troubleshooting steps have you tried?

Reading the sources and the example code.

#### Reproduction

[STACKBLITZ](https://stackblitz.com/angular/pmkypbmxkyq?file=src%2Fapp%2Ftree-checklist-example.ts)

  

    buildFileTree(obj: {[key: string]: any}, level: number): TodoItemNode[] {
      return Object.keys(obj).reduce<TodoItemNode[]>((accumulator, key) => {
          const value = obj[key];
          const node = new TodoItemNode();
          node.item = key;
      if (value != null) {
        if (typeof value === 'object') {
          node.children = this.buildFileTree(value, level + 1);
        } else {
          node.item = value;
        }
      }

        return accumulator.concat(node);
      }, []);
  
    }

### Q:
Why is there argument `level: number` in function `buildFileTree` from official docs? From my understanding its noop (no operation)?

**Comment by andrewseguin** [comment]
Sorry for the delay in providing help with this - we are currently limited on resources for troubleshooting issues. You will probably have better luck getting help if you post on StackOverflow.
