### ISSUE TITLE
bug([Radio]): [radio group selected cannot create checked property]

### ISSUE THREAD

**Issue by wjun20314** [angular/components#19106]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. radio group with two radio button
2. selected="male" is not working for default value
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by Totati** [comment]
Could you provide a demo please? What kind of form do you use? Reactive or template driven?

**Comment by wjun20314** [comment]
Sure. I using Reactive Form.
I'm try to set the default value when the form is loaded, but I set the `selected="Male"` it prompted me a messages `Cannot create property 'checked' on string 'Male'`

```
<mat-radio-group [formControl]="gender" selected="Male">
    <mat-radio-button name="male" value="Male">Male</mat-radio-button>
    <mat-radio-button name="female" value="Female">Female</mat-radio-button>
    <mat-error *ngIf="gender.invalid">{{getGenderErrorMsg()}}</mat-error>
  </mat-radio-group>
```

Another weird things is I checked the material library radio button package.json have this problems show in my vscode 

`String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".`

**Comment by crisbeto** [comment]
The `selected` property is used to set a selected radio button, not a selected value. If you want something to be pre-selected, you can do it when you initialize your `formControl`, e.g. `gender = new FormControl('male')`.

**Comment by Totati** [comment]
The name attributes should be the same as well. The easiest way is to set the name on the mar-radio-group.
```
<mat-radio-group name="gender" [formControl]="gender">
    <mat-radio-button value="male">Male</mat-radio-button>
    <mat-radio-button name="female" value="female">Female</mat-radio-button>
    <mat-error *ngIf="gender.invalid">{{getGenderErrorMsg()}}</mat-error>
</mat-radio-group>
```
And in your component.ts you can set the value as Crisbeto said.

**Comment by wjun20314** [comment]
> 
> 
> The `selected` property is used to set a selected radio button, not a selected value. If you want something to be pre-selected, you can do it when you initialize your `formControl`, e.g. `gender = new FormControl('male')`.

Alright, thank you. This solution really help.

`String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"`
Btw what is this problem? for my library?

**Comment by crisbeto** [comment]
That error doesn't look like it's coming from Material.

**Comment by mmalerba** [comment]
Closing as this was resolved in the discussion above
