### ISSUE TITLE
Drag and Drop between tables

### ISSUE THREAD

**Issue by Tezzy24** [angular/components#19105]
Hi,
I am trying to implement drag and drop feature between two tables.
So basically the idea is to drag from one table to another table and which ever row is dragged it should have a relation with the particular row of the other table.The same rows can have multiple relations as well and this functionality can be also be used with other tables as well.

Kindly shed some information on this to how can this be implemented.
 
#### What is the expected behavior?
Expected behavior is to have have many-many relation as well as one-many relation between both tables. 

#### What is the current behavior?
Currently only a one-one functionality is working and that to is not getting implemented with other tables as well.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I am using Angular 6.

**Comment by andrewseguin** [comment]
This would be a great question for the community at StackOverflow. We're currently trying to clean up our issues and finding that we are limited on resources to be able to provide good troubleshooting help right now.
