### ISSUE TITLE
bug(MatCheckbox): fails to toggle when the binding is updated in the click handler.

### ISSUE THREAD

**Issue by TrevorKarjanis** [angular/components#19100]
#### Reproduction

https://stackblitz.com/edit/angular-l69cmq?file=src%2Fapp%2Fapp.component.ts

1. Bind a MatCheckbox to a property on a component class.
2. Set the property value to true in a click handler on the checkbox.
3. Click the checkbox.
 
#### Expected Behavior

The input handles the click event first and toggles the checkbox value. The property value is already true when the parent's click handler is executed.

#### Actual Behavior

The click hander sets the property to true, and the form control toggles the checkbox before the input handle's the click event. The checkbox is toggled twice and remains false with one click.

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.0
- Browser(s): Chrome 80.0.3987.163
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina

#### Additional context

I understand that this scenario might seem weird. In the real application, I have a case where I cancel the click and display a confirmation dialog. That is why I am performing the toggle in the click handler in the alternate case.

Given the comment at the top of _onInputClick (checkbox.ts line 399), I would guess that the parent is handling the label's click event and the label is triggering the input's click event. Therefore, the input handles the click event after the parent.

This may be expected based on the implementation or get fixed as result of the MDC migration. This issue is useful for my tracking open or closed.

### Workarounds

- Cancel the event in the click handler.
- Perform side effects as a reaction to the checkbox value change using the change event or getters and setters.

**Comment by jennynju** [comment]
![image](https://user-images.githubusercontent.com/46782518/82987373-fc95cb00-a029-11ea-853e-ec0846a4b9ae.png)

@TrevorKarjanis, I think this is because _onInputClick  happens before the browser update the checkbox to its new value.
Needs to add a setTimeout when updating the variable this._checked.

**Comment by mmalerba** [comment]
@jennynju is correct, though rather than a `setTimeout` I would just do `event.stopPropagation(); event.preventDefault()`

**Comment by TrevorKarjanis** [comment]
@jennynju @mmalerba That's definitely a simpler explanation. I think I didn't expect the binding to update the checkbox before it handled the click event. I am canceling the event, so thank you for the feedback.
