### ISSUE TITLE
Can't bind to 'expanded' since it isn't a known property of 'mat-accordion'.([mat-accordion]): [Cannot use expanded on MatAccordion]

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#19101]
#### Reproduction

Use StackBlitz to reproduce your issue: 

https://stackblitz.com/edit/components-issue-k7rbu9?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Using the input prop of [expanded]="true" not recognised by MatExpansionModule aka mat-accordion 
2. See Stackblitz --> https://stackblitz.com/edit/components-issue-k7rbu9?file=src%2Fapp%2Fexample-component.html
 

 
#### Expected Behavior

What behavior were you expecting to see?
Hello! I am trying to only have the accordion functional on the mobile view. Desktop view - I will be removing the toggle button with [hideToggle]="true" (this works) and have all panels expanded. So I have tried to make them all expand in a few ways. 
1. I tried to use a function call ``this.matAccordion.openAll();`` by executing it AfterViewInit, 
2. I've tried [expanded]="true" 

**Neither work and I get this error for #2 with ``Can't bind to 'expanded' since it isn't a known property of 'mat-accordion'.``
** Get this error with #1 ``ERROR TypeError: Cannot read property 'openAll' of undefined``

Also once I expand the view I will be disabling with [disabled]=true but that also throws an error similar to the error I get with #2.
``Can't bind to 'disabled' since it isn't a known property of 'mat-accordion'.``
#### Actual Behavior

What behavior did you actually see?
1. The [expanded]="true" should expand all panels of the accordion
2. The [disabled]="true" should not allow user to collapse or expand the the accordian
3. this.matAccordion.openAll() should work on an Angular lifecycle

#### Environment

- Angular: 9.0+
- CDK/Material: 9.0+
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac Os

**Comment by crisbeto** [comment]
1. The `expanded` input is on `mat-expansion-panel`, not `mat-accordion`.
2. Your `openAll` call doesn't work, because you're querying for the wrong reference.

Here's a working example: https://stackblitz.com/edit/components-issue-61zxvq
