### ISSUE TITLE
bug All Components: not compatible with Ivy

### ISSUE THREAD

**Issue by rdelormeCHS** [angular/components#19117]
I created a brand new project and cannot do anything with Angular material:

    ERROR in node_modules/@angular/material/input/input-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@angular/material/input) which declares MatInputModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

I tried to go back to a previous version:

 "dependencies": {
    "@angular/animations": "~9.0.3",
    "@angular/cdk": "^9.1.2",
    "@angular/common": "~9.0.3",
    "@angular/compiler": "~9.0.3",
    "@angular/core": "~9.0.3",
    "@angular/forms": "~9.0.3",
    "@angular/material": "^9.1.2",
    "@angular/platform-browser": "~9.0.3",
    "@angular/platform-browser-dynamic": "~9.0.3",
    "@angular/router": "~9.0.3",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"

Expected: A new project should compile -- nothing custom added to it.

**Comment by crisbeto** [comment]
We're running all of our tests against Ivy, as well as our local development app. Furthermore, the Framework repo has a CI check that runs all of our tests against any of their changes. This looks like it could be an issue with your setup.

**Comment by rdelormeCHS** [comment]
how can i figure that out - what to check in my setup? I am newer to angular. I have no idea what to check- I did a new project-> installed angular/animations/cdk. Then, adding a material module, it gives that error. i find it strange to have an error after doing a basic install. I have another angular project that works, i don't see any differences in the various json files.

**Comment by eamon-otuathail** [comment]
A) I note you are using the latest production release of Angular Material:
~~~~
"@angular/material": "^9.1.2",
~~~~
but older versions of the main Angular packages. I would advise you update to the latest version of the production Angular libraries - if working with a new project, the best way to do this is get the latest Angular CLI and simply create  a new project and hence you do not need to manually set any versions; and you should get:
~~~~
 "@angular/core": "~9.1.1",
 "@angular/forms": "~9.1.1",
 "@angular/platform-browser": "~9.1.1",
  etc. 
~~~~
B) You mentioned installing the CDK - to get a simple Material app up and running you do not need to manually add the CDK. I wonder if there are version incompatibilities if you are bringing in your own version? 
C) You should double-check that you are correctly registering `MatInputModule` in your app.module.ts. 
~~~~
import {MatInputModule} from '@angular/material/input';
...
@NgModule({
..
imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MatInputModule,
....
}
~~~~
An error similar to what you are reported can be generated by passing a construct that is not an `NgModule` into imports.  Specifically:
~~~~ 
import {MatInput} from '@angular/material/input'; // <--- MISTAKE (Module missing)
@NgModule({
  ..
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    MatInput,            << ------------MISTAKE (Module missing)
~~~~
will generate this error message:
~~~~
ERROR in node_modules/@angular/material/input/input.d.ts:30:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/material/input) which declares MatInput has not been processed correctly by ngcc, or is not compatible with Angular
~~~~

**Comment by jelbourn** [comment]
Closing since this seems to be an environment issue
