### ISSUE TITLE
docs-bug(material-docs): Add MatIconTestingModule to documentation

### ISSUE THREAD

**Issue by BojanKogoj** [angular/components#19131]
#### Documentation Feedback

Add [MatIconTestingModule](https://github.com/angular/components/blob/master/src/material/icon/testing/fake-icon-registry.ts) to MatIcon documentation. Right now there is almost impossible to know this NEW feature exists, I only found it in change log.

Something like this should be enough:
> If you receive `Error: Error retrieving icon :icon_name! Unable to find icon with the name ":icon_name"` on custom icons add `MatIconTestingModule` to tests.

**Affected documentation page:** https://material.angular.io/components/icon/overview

**Comment by crisbeto** [comment]
Fixed in https://github.com/angular/material.angular.io/pull/757.
