### ISSUE TITLE
bug(MatTable): Cannot have two MatSortables with the same id

### ISSUE THREAD

**Issue by alexandreducatti** [angular/components#19147]
When trying to dynamically remove/add columns to a `MatTable` with `MatSort` enabled, I'm getting `Cannot have two MatSortables with the same id` multiple times. Despite the errors in browser's console, the sorting feature doesn't seem to be affected.

#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-zfdrxm

Steps to reproduce:
1. Add `matSort` directive to `MatTable`
2. Add `mat-sort-header` directive to `mat-header-cell`
3. Remove and add columns dynamically
 
 
#### Expected Behavior

What behavior were you expecting to see?
Dynamically add or remove columns with no errors

#### Actual Behavior

What behavior did you actually see?
I'm getting `Cannot have two MatSortables with the same id`.

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Google Chrome 81.0.4044.113
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Mojave 10.14.6

**Comment by trik** [comment]
identifiers are supposed to be unique.. if you really need to have a value displayed in different columns, why don't you simply add column with the same data source and a unique id?

https://stackblitz.com/edit/angular-zfdrxm-sws75d

**Comment by jelbourn** [comment]
This is working as intended; the IDs must be unique.
