### ISSUE TITLE
help(mat-dialog mat-sidenav): How to show sidenav above dialog or bind dialog to main app

### ISSUE THREAD

**Issue by delbiancodavide** [angular/components#19148]
#### What are you trying to do?

I'm trying to open a sidenav from a modal thru a service that handles the opening of the sidenav with a custom component rendered inside it.

The sidenav belongs to the main app and the dialog is injected outside the main app making it impossible to correct the z-index of the sidenav to be above the modal.

#### Reproduction

https://stackblitz.com/edit/angular-ertzyo-c6jehs

Steps to reproduce:
1. click the button to open the modal
2. click the footer button to toggle the sidenav
  
#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment]
Sorry for the delay in providing help with this - we are currently limited on resources for troubleshooting issues. You will probably have better luck getting help if you post on StackOverflow.
