### ISSUE TITLE
Tabs control is not displaying the tab navigation buttons sometimes

### ISSUE THREAD

**Issue by jemilioinza** [angular/components#19145]
Hello, we are using the material components library in our application. We have noticed that when the tab control loads (https://material.angular.io/components/tabs/overview) the arrows to navigate between tabs are not displayed sometimes. 

This situation happens often when the tabs are displayed inside a collapsable panel.

Are you aware of this situation?

Thank you.

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
