### ISSUE TITLE
bug([mat-checkbox]): Same data-id attribute causes unexpected behavior

### ISSUE THREAD

**Issue by kr0tchy** [angular/components#19154]
#### Reproduction
https://stackblitz.com/edit/components-issue-agbcze

Steps to reproduce:
1. Create more `<mat-checkbox>` with the same `data-id` attribute 
2. If you try to select any elements, only the first will be checked/unchecked
 
 
#### Expected Behavior
data- attributes should not have cause any unexpected behavior 

#### Actual Behavior
If you put a `data-id` attribute then checkbox `id` attribute will have the same value as the `data-id`

#### Environment

- Angular: 9.0.1
- CDK/Material: 9.1.0
- Browser(s): Chrome  81.0.4044.113
- Operating System: Windows 10

**Comment by crisbeto** [comment]
I'm guessing Angular maps the `data-id` to the `id` input on the checkbox which then proxies it to the `input` element. I don't think we can anything about it, but you can work around it by changing it to `[attr.data-id]="'select'"`.
