### ISSUE TITLE
Adding Material to a Library Project (Could not find the project main file inside of the workspace config)

### ISSUE THREAD

**Issue by epaitz** [angular/components#19156]
I am trying to build an Angular Library project that has Material installed. It was not working in my original project so I decided to create a new workspace and library project from scratch. Here are the commands I used.
```
ng new test-workspace --create-application=false
cd .\test-workspace\
ng generate library test
ng add @angular/material
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose a prebuilt theme name, or "custom" for a custom theme: Indigo/Pink
? Set up global Angular Material typography styles? Yes
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1434 bytes)
√ Packages installed successfully.
Could not find the project main file inside of the workspace config (projects/test/src)
```
After this step I was going to add the following...

```
    "@angular/cdk": "^9.2.1",
    "@angular/material": "^9.2.1
```
...to the peerDependencies of test-workspace\projects\test\package.json but I do not know what do to do with the error I received after trying to install Material. Is this more of a warning than an error?

```
Could not find the project main file inside of the workspace config (projects/test/src)
```
Any help would be greatly appreciated. 

Thanks

```
Angular CLI: 9.1.1
Node: 12.16.1
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.1
@angular/cli                       9.1.1
@angular/material                  9.2.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by Nathan-Froeh** [comment]
I'm having this problem as well, I was on version 8.3.23 and just updated to latest but no change.
Any workaround's or fixes?

**Comment by DrJuriko** [comment]
The same problem...

**Comment by devversion** [comment]
Thanks for all the reports. We have a fix PR pending for this. I'd be interested in knowing how this only came up now? Hasn't this error surfaced in the past too? (maybe there is an issue and I just didn't see).

**Comment by DrJuriko** [comment]
Yesterday I refreshed my angular env with latest and tried to create my first library. To be honest, I tried to add  "ngx-bootstrap": "^5.6.1". My angular env: 

Angular CLI: 9.1.4
Node: 12.8.1
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-ng-packagr   0.901.4
@angular-devkit/build-optimizer    0.901.4
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@ngtools/webpack                   9.1.4
@schematics/angular                9.1.4
@schematics/update                 0.901.4
ng-packagr                         9.1.2
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

**Comment by zmzimpl** [comment]
The same problem when i am trying to `ng add ng-zorro-antd`
