### ISSUE TITLE
bug([pink&blue-grey theme]): [Material Blue-grey theme is Not sowing dark background]

### ISSUE THREAD

**Issue by Nagarajnaidu921** [angular/components#19155]
#### Reproduction
Angular material pink-blue grey is not showing dark background and material dark theme is not working.
But it is working in StackBlitz

Use StackBlitz to reproduce your issue: [https://components-issue-qyqwty.stackblitz.io](https://components-issue-qyqwty.stackblitz.io/)

Steps to reproduce:
1. create new Angular App using `ng new testapp`
2.  add angular material ng add @angular/material
3. use use card module and use some formfields inside card component
4. use some input field outside card component
5 Expected output should be like ([output](https://components-issue-qyqwty.stackblitz.io))

 
#### Expected Behavior

What behavior were you expecting to see?
([Expected Behaviour](https://components-issue-qyqwty.stackblitz.io)

#### Actual Behavior

What behavior did you actually see?
[screenshot1](https://drive.google.com/file/d/1iSNH9sBm5YOFXu5ZdGQHfelbnQORMA12/view?usp=sharing)
[screenshot2](https://drive.google.com/file/d/1z71jRI4iOxY7JLSgtL1QIVGMVzWsoMEB/view?usp=sharing)

#### Environment

Angular CLI: 9.1.3
Node: 12.16.2
OS: linux x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@angular/cdk                      9.2.1
@angular/material                 9.2.1
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
Browser(s): Firefoz 75.0
Operating System: Ubuntu

**Comment by crisbeto** [comment]
It's because we try to avoid having global styles in Material. You can add the `mat-app-background` class to the element that wraps around your content (e.g. the `body`).
