### ISSUE TITLE
bug([MatTabGroup]): ['disablePagination Input not working']

### ISSUE THREAD

**Issue by ojas-gulati-b** [angular/components#19153]
The **disablePagination** Input for mat-tab-group component for material tabs does not work, 
even though it was fixed in [#17409](https://github.com/angular/components/pull/17409).

Looking at the source code I could see that even though the @Input to the component has been introduced as disablePagination  but the constructor still calculates it based on defaultConfig of Tabs

**Comment by crisbeto** [comment]
Can you post an example of what you're doing? While the changes in #17409 pick up the initial value from the config, it only happens once on init and your own binding will override it.

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
