### ISSUE TITLE
bug(build): ngcc compatibility check is not run against built packages in CI

### ISSUE THREAD

**Issue by trik** [angular/components#19157]
#### Reproduction

See output of `yarn ngcc build` job
[https://circleci.com/gh/angular/components/134736](https://circleci.com/gh/angular/components/134736)
 It doesn't include any package from @angular/cdk or @angular/material
 
#### Expected Behavior

ngcc should compile the built packages

#### Actual Behavior

ngcc doesn't compile any of the built packages

#### Environment

- Angular: 9+
- CDK/Material: 9+
- Browser(s): //
- Operating System (e.g. Windows, macOS, Ubuntu): //

**Comment by devversion** [comment]
Thanks for the issue report. That is a good catch!! The tests ran in the past, but ngcc changed in so many ways that the check did not run properly. I've sent a fix #19161.

Sorry for the conflicting PR. This appeared to me as something we want to fix as soon as possible. Your effort to fix this is definitely appreciated! Thx again 😄

**Comment by trik** [comment]
I was able to catch it just because we are using a build pipeline heavily inspired by yours, let me thank your for the great job! I haven’t a deep knowledge of ngcc and how it detects packages entry points. I just noticed that adding the packages to the yarn lock made the job, but for sure your changes are the right way to do it. I’ll be closing my PR
