### ISSUE TITLE
Material dialog id changes everytime when a dialog is open

### ISSUE THREAD

**Issue by alimemonzx** [angular/components#19167]
Whenever i open angular material dialog the id in tag change always when i open it. Everytime the id changes its hard to get the reference of dialog.

See the 2 images below.
![Image 1](https://i.ibb.co/rH5s9q8/material1.png)
![Image 2](https://i.ibb.co/7npVLnB/material2.png)

**Comment by Splaktar** [comment]
You can use `[panelClass]` or `addPanelClass()` as specified in https://material.angular.io/components/dialog/api in order to get predictable selectors for the dialog. Then within the dialog, you can target the title using the `.mat-dialog-title` class.
