### ISSUE TITLE
help(Sidenav): how to code a sidenav like material.angular.io did

### ISSUE THREAD

**Issue by hylerrix** [angular/components#19163]
#### What are you trying to do?

I`m trying to write a Sidenav skeleton demo, just like official document navigation skeleton(A menu in the left part and content body in the right part with overview\api\examples tabs):

![](https://user-images.githubusercontent.com/19285461/80196805-6d734d00-8650-11ea-9611-d9f30f3c43c5.png)

And I`m new to Angular, I cannot figure out how to code this Sidenav skeleton, and I can not find where is the relevant source code about this skeleton after I cloning this repo.

If anyone can help me, I'll be much appreciated. 😁

#### What troubleshooting steps have you tried?

I have already read the [Sidenav Document](https://material.angular.io/components/sidenav/overview), and still don't understand.

Because according to this document, I need to code Sidenav as follows, but in Official Sidenav skeleton, it's class called `docs-component-viewer-nav-content ng-tns-c139-5` rather than `mat-drawer-inner-container ng-tns-c36-0`:

```
<mat-sidenav-container class="example-container" *ngIf="shouldRun">
  <mat-sidenav mode="side" opened>Sidenav content</mat-sidenav>
  <mat-sidenav-content>Main content</mat-sidenav-content>
</mat-sidenav-container>
```

#### Reproduction

As above, I use the `mat-sidenav-container` tag but don't know how to realize the Sidenav style of the official website one by one.

#### Environment

- Angular: ~9.1.0
- CDK/Material:^9.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
The docs site is using a custom navigation. You can find the source here: https://github.com/angular/material.angular.io/blob/f9ee14a24a9c171c8d2cb6d053e055538eb21506/src/app/pages/component-sidenav/component-sidenav.ts#L100.
