### ISSUE TITLE
bug(Drag&n&Drop): Data from dropped item is undefined

### ISSUE THREAD

**Issue by MozGOkluY** [angular/components#19160]
#### Reproduction

Use StackBlitz to reproduce your issue (forked from documentation examples and added only **console.log**): https://stackblitz.com/edit/angular-trx3ff?file=src/app/cdk-drag-drop-connected-sorting-group-example.ts

Steps to reproduce:
1. Try to receive data form dragged item in the event
 
 
#### Expected Behavior

What behavior were you expecting to see?
**event.item.data** returns data that attached to the item

#### Actual Behavior

What behavior did you actually see?
**event.item.data** is undefined

#### Environment

- Angular:9+
- CDK/Material:9+
- Browser(s):All
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

<img width="1184" alt="Screenshot 2020-04-23 at 22 13 54" src="https://user-images.githubusercontent.com/35643970/80139858-ce971400-85af-11ea-9724-777e5c546628.png">

I will be grateful for any help.

**Comment by crisbeto** [comment]
That's because you haven't attached any data. You can do through the `cdkDragData` input, e.g. `[cdkDragData]="item"`.
