### ISSUE TITLE
[menu-item]: Clicking on disabled menu-item closes the menu 

### ISSUE THREAD

**Issue by gauravsoni119** [angular/components#19173]
#### Reproduction

https://material.angular.io/components/menu/examples

Steps to reproduce:
1. Click on the disabled mat-menu item. 
 
 
#### Expected Behavior
The menu should not be closed if the menu-item is disabled
I believe below is the code for this but still, the menu gets closed
https://github.com/angular/components/blob/master/src/material/menu/menu-item.ts#L145-L146

#### Actual Behavior

The menu gets closed when we click.

- Angular:
- CDK/Material: latest
- Browser(s): Google Chrome
- Operating System (Ubuntu):

**Comment by crisbeto** [comment]
Looks like it's due to https://github.com/angular/components/pull/16696 which was put in place to normalize some browser inconsistencies.
