### ISSUE TITLE
can i use @angular/cdk/schematics in my custom schematics?

### ISSUE THREAD

**Issue by jhonyeduardo** [angular/components#19184]
#### Bug, feature request, or proposal:
Question

#### What is the current behavior?
can i use @angular/cdk/schematics?

I built a schematics update and have some features that i would can use from @angular/cdk/schematics, how
buildComponent, addImportToRootModule and others.

But i have fear to use, because is not officialy documented.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
9

**Comment by jelbourn** [comment]
Not at this time- this isn't a public API
