### ISSUE TITLE
bug(dateRangePicker): model set value called multiple times on init

### ISSUE THREAD

**Issue by mcalmus** [angular/components#19186]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

This is related to the pre-release date range picker

html:
<mat-form-field floatLabel="never">
    <mat-date-range-input [rangePicker]="dateRangePicker">
        <input matStartDate placeholder="Start date" [(ngModel)]="fromDate" />
        <input matEndDate placeholder="End date" [(ngModel)]="toDate" />
    </mat-date-range-input>
    <mat-datepicker-toggle [for]="dateRangePicker" matSuffix></mat-datepicker-toggle>
    <mat-date-range-picker #dateRangePicker></mat-date-range-picker>
</mat-form-field>
TypeScript:
private _to: Date;
private _from: Date;
set toDate(newDate: Date) {
  console.log("set to date");
  this._to = newDate;
}
get toDate(): Date {
  return this._to;
}
...etc.

Steps to reproduce:
1. Create range picker attaching models to the start and end date (partial code included)
2. Load page
 
 
#### Expected Behavior
What behavior were you expecting to see?

setters called once (maybe twice) during startup

#### Actual Behavior
What behavior did you actually see?

Set is called dozens (maybe hundreds?) of times.

#### Environment

- Angular: 9.1.3
- CDK/Material: build from date-range branch
- Browser(s): FF
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS 10.15.5

**Comment by crisbeto** [comment]
I'm only seeing the setters being run twice with the provided code running against master. Are you sure that you weren't looking at the getters?

**Comment by mcalmus** [comment]
Turns out my get method was doing something like:
`return new Date(this._to);` so there was a new object every time.
