### ISSUE TITLE
bug(mat-tab): sticky tab content doesn't stick inside mat-tab on Safari

### ISSUE THREAD

**Issue by awormasi** [angular/components#19189]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-pwmph4

Steps to reproduce:
1. On Safari, go to the StackBlitz and scroll horizontally in the mat-tab and observe that the div saying "doesn't stick" doesn't stick to the left
2. Scroll horizontally in the div outside of the mat-tab and observe that the div saying "sticks" sticks to the left
3. On Chrome, go to the StackBlitz and notice that both divs stick to the left, inside and outside of mat-tab.
 
 
#### Expected Behavior

Div saying "doesn't stick" should stick to the left on Safari. Position:sticky should work inside mat-tab on Safari.

#### Actual Behavior

Position:sticky doesn't work inside mat-tab on Safari.

#### Environment

- Angular: 
    "@angular/animations": "^9.0.0",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/forms": "^9.0.0",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/router": "^9.0.0",
- CDK/Material:
    "@angular/cdk": "^9.0.0",
    "@angular/material": "^9.0.0",
    "@angular/material-moment-adapter": "^9.0.0",
- Browser(s):
    Safari Version 13.1 (15609.1.20.111.8)
    Chrome Version 81.0.4044.122 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): 
    macOS Catalina 10.15.4

**Comment by jelbourn** [comment]
As far as I can tell, this appears to be a bug in Safari/WebKit. Everything works as expected in Chrome, Firefox, and Edge. I don't see what the tab body would be doing that would break this per expected behavior of `position: sticky`.
