### ISSUE TITLE
FlexibleConnectedPositionStrategyOrigin type does not support SVGElement, or at least Element

### ISSUE THREAD

**Issue by georgelviv** [angular/components#19194]
**Expected Behavior:**
_FlexibleConnectedPositionStrategyOrigin_ should accept Element, (or SVGElement)

**Actual Behavior**
_FlexibleConnectedPositionStrategyOrigin_ does not accept Element, (or SVGElement)

**Environment**
Angular version 9.2.1

**Details**

In PR bellow, was fixed to support svg, but it was not updated interface
https://github.com/angular/components/issues/18618

Interface here
https://github.com/angular/components/blob/ddc9fd6baa4f75a8b2edc20b7bec9edf92353203/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L36

Please fix this, currently temporary solution I have

```
       this.positionStrategy.setOrigin(this.getProperTarget());
	private getProperTarget(): ElementRef | HTMLElement {
		if (this.target instanceof HTMLElement) {
			return this.target;
		} else {
			return new ElementRef(this.target);
		}
	}
```

**Comment by georgelviv** [comment]
Any updates?

**Comment by crisbeto** [comment]
Looks like the fix went in a while ago, but I didn't tag it properly so the issue wasn't closed. https://github.com/angular/components/pull/19199
