### ISSUE TITLE
bug([cdk/layout]): [addEventListener is undefined in iOS >=12]

### ISSUE THREAD

**Issue by wisespace-io** [angular/components#19193]
I had issues loading my Angular 9 app on iPhone, it loads in all desktop browsers and android devices, just got an blank page in iPhone. It raised an promiseReactionJob exception .. running the lasted iOS version (13.4.1). I checked  index.html and the scripts are loaded as expected.
So, after isolate the problem, I identified that it was failing in the call below because addEventListener is undefined

    this.forMobileLandscapeAndDown.addEventListener('change', this.mediaQueryListener);

I checked the content of fem2015/layout.js and addEventListener does not exist in Safari for iOS.

The fix on my app was check the OS and call addListener instead of removeListener only for iOS.

#### Environment

- Angular: 9.1.2
- CDK: 9.2.1
- Browser(s): Safari/Firefox/Chrome
- Operating System: iOS >= 12

**Comment by crisbeto** [comment]
This looks like an issue with your own code. We have zero calls to `addEventListener` inside the `layout` module.

**Comment by wisespace-io** [comment]
I use like below ...

    import { MediaMatcher } from '@angular/cdk/layout';

    ....

    private observeViewportWidthChanges() {
        this.forMobileLandscapeAndDown = this.media.matchMedia('(max-width: 767px)');
        this.mediaQueryListener = () => {
           // doing something else
        };

        // On iphone, it fails on the call below, because addEventListener is UNDEFINED, 
        // but works fine on Android (Chrome), Windows (Chrome, Firefox, Edge) 
        this.forMobileLandscapeAndDown.addEventListener('change', this.mediaQueryListener);
    }

   Call `addEventListener('change', this.mediaQueryListener);` only fails on iPhone

**Comment by crisbeto** [comment]
I don't see the CDK `MediaMatcher` being used anywhere in your example.

**Comment by wisespace-io** [comment]
See the constructor and the line below ...

    this.forMobileLandscapeAndDown = this.media.matchMedia('(max-width: 767px)');

**Comment by crisbeto** [comment]
I see. All the media matcher does it handle some browser inconsistencies around `matchMedia`, but it still returns the native `MediaQueryList` so it's up to you to choose the proper method. If you want this to be abstracted away for you, you can use the `BreakpointObserver` service.

**Comment by jelbourn** [comment]
Closing since this seems unrelated to Angular CDK.
