### ISSUE TITLE
bug([mat-tab]): unable to use space in an input within mat-tab-label

### ISSUE THREAD

**Issue by muberraduman** [angular/components#19190]
#### Reproduction

Steps to reproduce:
1. Open this URL : https://angular-akfnab.stackblitz.io
2. Try to write something into input box with space character. 
 
 
#### Expected Behavior

Expected to be able to use space character in the input box

#### Actual Behavior

I can type anything but space character.

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows & Mac

**Comment by crisbeto** [comment]
It looks like your example is throwing errors.

**Comment by muberraduman** [comment]
Please check it again.

Thanks


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
