### ISSUE TITLE
bug(mat-chip): Deletion of chips with array of primitives removes the wrong DOM element

### ISSUE THREAD

**Issue by glouischandra** [angular/components#19202]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-s6lcg8

Steps to reproduce:
1. Have array of primitives power the mat-chip
2. Add two chips that have the same primitive values
3. Deleting the first chip will delete the DOM of the second one.
 
 
#### Expected Behavior
Deleting the first chip deletes the DOM of the first element

#### Actual Behavior
Angular seems to remove the DOM of the last element with the same value

#### Investigation
This issue seems to stem from *ngFor and how it tracks reference of DOM from the value of the loop. This issue is not repro-able when the chips are powered with objects or using trackBy with unique index, but I'm wondering if there's something we can do with Mat-chip + mdc-chip to automatically solve this problem.

#### Environment
- Angular: v9.1.3
- CDK/Material: v9.2.1
- Browser(s): Chrome 81
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS

**Comment by jelbourn** [comment]
@crisbeto it's probably worth taking a look to see if there's something we could try here; I talked w/ @glouischandra about this, and we're not sure if it's possible when using primitives (based on the way `IterableDiffer` works)

**Comment by crisbeto** [comment]
I don't think we can do anything about it, or at least not without a huge API change. The framework is responsible for rendering and keeping track of the elements, not the chip list, so it's out of our control what gets rendered out.
