### ISSUE TITLE
Tab Group Arrows are shown when not needed 

### ISSUE THREAD

**Issue by doczoidberg** [angular/components#19203]
#### What are you trying to do?
I need to add tabs dynamically. But then the scroll arrows are also shown when not needed:
![image](https://user-images.githubusercontent.com/1972209/80581756-ea664400-8a0d-11ea-88b7-d54650ebfc34.png)

  
#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): all

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
