### ISSUE TITLE
Can't bind to 'icon' since it isn't a known property of 'map-marker'.

### ISSUE THREAD

**Issue by mukurpuri** [angular/components#19204]
#### Reproduction

Steps to reproduce:
1. Added <google-map></google-map>
2. Added <map-marker></map-marker> component inside it with an icon prop with value 
`{url: "http://maps.google.com/mapfiles/ms/icons/green-dot.png"}.`

 
 
#### Expected Behavior

What behavior were you expecting to see?
I was expecting to see a green color marker for that location

#### Actual Behavior
What behavior did you actually see?
I saw the same red color and got a warning in my console _Can't bind to 'icon' since it isn't a known property of 'map-marker'._

#### Environment

- Angular: ~9.1.2
- CDK/Material: "@angular/google-maps": "^9.2.1",
<img width="998" alt="Screenshot 2020-04-29 at 3 54 51 PM" src="https://user-images.githubusercontent.com/10636579/80586079-0976cd00-8a32-11ea-85d9-0b9ffbffc6c0.png">

- Browser(s): Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Mac

**Comment by crisbeto** [comment]
You can set the icon through the `options` input: `<map-marker [options]="{icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'}"></map-marker>`.

**Comment by mukurpuri** [comment]
@crisbeto  Thanks that helped.
