### ISSUE TITLE
bug(mat-chip): programmatically changing 'selected' shows wrong results

### ISSUE THREAD

**Issue by Stexxen** [angular/components#19217]
#### Reproduction

https://stackblitz.com/edit/angular-ag2dmh
Initial View
![image](https://user-images.githubusercontent.com/4494301/80806521-d14ac800-8bb2-11ea-9e26-d80b2d1df033.png)

Steps to reproduce:
1. Click "setFirstSelectedFalse", *both* Chips will now become un-selected, yet selected value is still true for second chip
![image](https://user-images.githubusercontent.com/4494301/80806449-a496b080-8bb2-11ea-97c5-237c8bd97f47.png)

2. Click "setFirstSelectedTrue", only the first shows as selected, but the selected value for both are true.
![image](https://user-images.githubusercontent.com/4494301/80806560-e6bff200-8bb2-11ea-9264-85c530783d50.png)

#### Expected Behavior

As 'setFirstSelectedFalse' only affects the first chip, only that chip should become unselected

#### Actual Behavior

Changing one chip to selected=false, changes all chips **visually** to selected=false, yet the data is still true

Changing one chip to selected=true, only changes that chip to selected=true

Something appears to be wrong with change detection, I think

#### Environment

- Angular: 9.1.4
- CDK/Material: 9.2.1
- Browser(s): Chrome 81
- Operating System  macOS: 10.15.3

**Comment by swseverance** [comment]
@Stexxen can you add `[multiple]="true"` to `mat-chip-list`. I believe that resolves the issue.

**Comment by Stexxen** [comment]
@swseverance I hadn't realised that applied in this situation as multiple chips were already selected at the start, but that does indeed fix it.
Many Thanks
