### ISSUE TITLE
MatTableDataSource - Unit Separator

### ISSUE THREAD

**Issue by sdavids** [angular/components#19222]
#### Feature Description

https://github.com/angular/components/blob/master/src/material/table/table-data-source.ts#L192

> The character is intended to be something that has a very low chance of being typed
> in by somebody in a text field. This one in particular is "White up-pointing triangle with dot"

What about the Unit Separator `\u001f`?

https://en.wikipedia.org/wiki/C0_and_C1_control_codes#US

**Comment by jelbourn** [comment]
I don't see any reason to change it presently unless it's causing a problem.
