### ISSUE TITLE
Slider display wrongly on null value with thumb label

### ISSUE THREAD

**Issue by Etmutt** [angular/components#19220]
https://material.angular.io/components/slider/examples
Steps to reproduce:
1. set value on null
2. set thumb label

>>the sliding dot will display in full black instead of the grey circle expected (on chrome)

**Comment by crisbeto** [comment]
I couldn't reproduce it based on the instructions. Can you fork the Stackblitz and show an example?

**Comment by Etmutt** [comment]
I'm getting it in the doc as well ; using firefox 75.0

![image](https://user-images.githubusercontent.com/62804622/80860184-c2c1e680-8c6e-11ea-8fd6-47c7cded072e.png)

**Comment by crisbeto** [comment]
I don't remember the context behind it, but I believe that it's intentional.

**Comment by devversion** [comment]
It looks like the thumb behaves as expected in Firefox and Chrome. If `Show thumb label` is not checked, the thumb is not filled, but if the option is set, the thumb is filled (black as of now).
