### ISSUE TITLE
bug(MatRadioButton): MatRadioButton's text color does not follow the color scheme when in MatMenu

### ISSUE THREAD

**Issue by Khoasiate** [angular/components#19235]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-cxaoov

Steps to reproduce:
1. Create custom dark theme
2. Create MatMenu
3. Create MatRadioButton in MatMenu
 
 
#### Expected Behavior

What behavior were you expecting to see?

MatRadioButton's text color should be white (or at least light)

#### Actual Behavior

What behavior did you actually see?

MatRadioButton's text color is black

#### Environment

- Angular: 9
- CDK/Material: Yes, both
- Browser(s): Brave v1.7.98, Safari 13.1.1
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

#### Possible fixes

I fixed it for me by creating following mixin

```
@mixin mat-radio-theme-fix($theme) {
	$foreground: map-get($theme, foreground);

	mat-radio-button {
		color: map-get($foreground, text);
	}
}
```

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/components/pull/19113.
