### ISSUE TITLE
bug([<mat-select>]): form is submitted even if mat-select is not selected, required does not work

### ISSUE THREAD

**Issue by eau-de-la-seine** [angular/components#19244]
Hi, my problem is quite simple, Angular Material's **native select** `required` works fine:
```
<mat-form-field>
    <mat-label>Project</mat-label>
    <select matNativeControl formControlName="projectName" (change)="onChangeProjectName($event.target.value)" required>
        <option *ngFor="let project of userProjects" [value]="project.id">{{project.id}}</option>
    </select>
</mat-form-field>
```

**BUT** the `<mat-select>` version **submits the form even if the field is not selected**. The `required` is not respected:
```
<mat-form-field>
    <mat-label>Project</mat-label>
    <mat-select formControlName="projectName" (change)="onChangeProjectName($event.target.value)" required>
        <mat-option *ngFor="let project of userProjects" [value]="project.id">{{project.id}}</mat-option>
    </mat-select>
</mat-form-field>
```
This code is really similar to Angular Material's native version, but I use `<mat-select>` and `<mat-option>`, and I have removed `matNativeControl`.

As you can see I don't have problem with Angular Material's native version, just have a problem with the `<mat-select>` version. I didn't put the whole form but I use : 
* `(ngSubmit)` on `<form>` for submitting the form
* `ngNativeValidate` on `<form>` for validation (because it's way nicer than using `Validators.required`)
* `[formGroup]` on `<form>` and `formControlName` on fields (because it's looks way nicer than using `[formControl]="myFormName.controls.myFieldName"` on each form field).

#### Environment

- Angular: 9.1.4
- CDK/Material: 9.2.2
- Browser(s): Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
The automatic form submission prevention is something that is done at the browser level only for native controls. Since `mat-select` is a custom control that the browser doesn't know about, it's up to you to check the validity and call `preventDefault` on the `submit` event.
