### ISSUE TITLE
bug(cdk/schematics): Regression in CDK version 9.2.2 where the public api changed

### ISSUE THREAD

**Issue by lukasholzer** [angular/components#19258]
#### Reproduction

Install the CDK with version `9.2.2` and try to import `createUpgradeRule` and `RuleUpgradeData` from the schematics package of the CDK.

with version `9.2.1` it was working. So the API was broken in a patch version.

 
#### Expected Behavior

It should be possible to import `createUpgradeRule` and `RuleUpgradeData` with the version **9.2.2** of `@angular/cdk`

```typescript
import {
  createUpgradeRule,
  RuleUpgradeData,
} from '@angular/cdk/schematics';
```
#### Actual Behavior

A regression was introduced with this version where those two functions are not exported anymore this causes the build to fail.

```
error TS2305: Module '"@angular/cdk/schematics"' has no exported member 'createUpgradeRule'.
error TS2305: Module '"@angular/cdk/schematics"' has no exported member 'RuleUpgradeData'.
```

#### Environment

- Angular: 9.1.3
- CDK/Material: 9.2.1 -> 9.2.2
- Browser(s): ---
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by jelbourn** [comment]
cdk/schematics is unfortunately not a public API and is not documented anywhere. We'd like to someday offer some of what we've built publicly, but for now we don't have the ability to support it as such.
