### ISSUE TITLE
docs-bug([COMPONENT]): [TITLE]

### ISSUE THREAD

**Issue by carlosvargas31** [angular/components#19262]
Hello, I would like to know if I can circulate the (mat-slider) in any way? Well, I checked the documentation several times, but I didn't find any way to transform the slider to a circular shape, and so the value would show me in the middle! Also, displaying percentage information is much better this way. Attentive to the answer ... 

https://material.angular.io/components/slider/api

In the event of being impossible at this time! I would put it as a recommendation, for future improvements to the mat-slider, which in my opinion is very useful. In addition to that if we have any tool that can recommend me!

Thanks

**Comment by jelbourn** [comment]
This is not supported or planned.
