### ISSUE TITLE
youtube-player: Support PlayerVars

### ISSUE THREAD

**Issue by d052057** [angular/components#19267]
I am not sure what I am doing here, please bare with me.
I am trying to use playerVars for youtube-player component.  I am not sure that the feature is available or not in this component. 
If it is existed, please advise me how to do it.  If not, are you planning add it to the future or is there any way around it (what I would like to do is to add closed caption and playlist).

Thanks.

**Comment by jelbourn** [comment]
Looks like this is a legit feature request for the youtube-player

**Comment by crisbeto** [comment]
There's an existing PR for this already https://github.com/angular/components/pull/17672, but I don't know whether we don't want to take it over and do it again since it's pretty stale?

**Comment by d052057** [comment]
I did figure it out how to do this just one pass from angular 8/9 to youtube api directly.  You can access all of its functions and its variables that the Api has. I can give my sample app if you would like.  This can supercede your app @angular/youtube-player (if you don't mind).
Thanks.
    On Wednesday, May 6, 2020, 10:05:28 AM PDT, Jeremy Elbourn <notifications@github.com> wrote:  
 
 


Looks like this is a legit feature request for the youtube-player

**Comment by lautarojgarcia177** [comment]
@d052057 could you please give your sample app?

**Comment by d052057** [comment]
Please take look at d052057/Angular9

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
d052057/Angular9

test code. Contribute to d052057/Angular9 development by creating an account on GitHub.
 |

 |

 |


Thank you.

    On Saturday, May 23, 2020, 12:57:24 PM PDT, Lautaro Garcia <notifications@github.com> wrote:  
 
 


@d052057 could you please give your sample app?

**Comment by devversion** [comment]
@YourDeveloperFriend Would you be able to update your existing PR for this? https://github.com/angular/components/pull/17672

**Comment by d052057** [comment]
Sorry about my last email. I though it was something else.  Regarding youtube player, I did write everything from scratch using javascript and that is the reason why I can access with no issues. ngx-plyr would be best for accessing and playing youtube video. It is the most complete version.
Thank you.
    On Tuesday, May 26, 2020, 03:37:43 AM PDT, Paul Gschwendtner <notifications@github.com> wrote:  
 
 


@YourDeveloperFriend Would you be able to update your existing PR for this? #17672

**Comment by CardzMania** [comment]
playerVars are still not working for me... don't have no effect...
