### ISSUE TITLE
bug(mat-form-field): MatSuffix does not get applied when inside a structural directive

### ISSUE THREAD

**Issue by PierreDuc** [angular/components#19268]
#### Reproduction

[StackBlitz](https://stackblitz.com/edit/components-issue-vt5ad2?file=src%2Fapp%2Fexample-component.html)

Steps to reproduce:
```
<mat-form-field>   
  <input matInput>
 
  <ng-container *ngIf="true">
    <mat-icon matSuffix>close</mat-icon>
  </ng-container>
</mat-form-field>
```
  
#### Expected Behavior

The `matSuffix` being put inside the `mat-form-field-suffix`

#### Actual Behavior

The `matSuffix` is being put in the `mat-form-field-infix`

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

---

It works if you put `matSuffix` on the structural directive like 

```
<mat-icon *ngIf="true" matSuffix>close</mat-icon>
```
 
but this causes issues if you want a conditional date picker in your `mat-form-field`:

```
<mat-form-field>   
  <input *ngIf="type !== 'date'"  matInput>
 
  <ng-container *ngIf="type === 'date'">
    <input matInput>
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker #picker></mat-datepicker>
  </ng-container>
</mat-form-field>
```

I know you can put the `*ngIf` on the `mat-form-field` and just declare that two times, but it would be nice if the conditional `matSuffix` would work as expected :). I assume the [`ng-content [select]`](https://github.com/angular/components/blob/master/src/material/form-field/form-field.html#L61) cannot find the selection if it's inside a template

**Comment by crisbeto** [comment]
We use `ng-content select="[matSuffix]"` to project the element into the proper place. Since it's placed inside of an `ng-container`, the selector won't match anymore. We can't do anything about it since this is how the framework works.
