### ISSUE TITLE
docs-bug(mat-tab-group): mat-tab-stretch exists and is not documented anywhere

### ISSUE THREAD

**Issue by porqupine** [angular/components#19263]
#### Documentation Feedback

It would be very useful to have all properties that affect a given component clearly and visibly documented. Today I found out about mat-tab-stretch after hacking away for a while with no success. 

Scouring https://material.angular.io/components/tabs/api and related provided no hint of its existence, and was only mentioned on this S.O. thread - https://stackoverflow.com/questions/48839430/make-tab-labels-stretch-to-full-width-in-material-design-for-angular

**Affected documentation page:** https://material.angular.io/components/tabs/api

**Comment by FrankiePo** [comment]
It is just an attribute in css with little styles.
We could add MatTabStretch directive and it will be available through API tab.
But I guess it's too much for a 4 lines of scss code.

**Comment by zarend** [comment]
Closing because there is already an [example using mat-tab-stretch](https://material.angular.io/components/tabs/examples#tab-group-stretched).
