### ISSUE TITLE
npm install @angular/material-moment-adapter results in timeout

### ISSUE THREAD

**Issue by mvivancheva9** [angular/components#19275]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
I should be able to install the package

#### What is the current behavior?
When trying to istall @angular/material-moment-adaptor this result in the folloring error:

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://ec2-18-203-173-100.eu-west-1.compute.amazonaws.com:8081/repository/npm-group/@angular%2fmaterial-moment-adaptor failed, reason: connect ETIMEDOUT 18.203.173.100:8081

#### What are the steps to reproduce?
run npm install @angular/material-moment-adapter

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.10
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@angular/flex-layout              7.0.0-beta.24
@angular/localize                 9.1.2
@angular/material                 7.3.7
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.5.5
typescript                        3.2.4
webpack                           4.29.0

**Comment by crisbeto** [comment]
It looks like either npm is timing out, or whatever proxy your connection is going through. Either way, this isn't something that we have control over.
