### ISSUE TITLE
bug([mat-expansion-panel]): [Page becomes unresponsive when component is inside ngFor without trackBy]

### ISSUE THREAD

**Issue by alexanderwiebe** [angular/components#19281]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/github/alexanderwiebe/mat-expansion-in-ngfor

Steps to reproduce:
1. Have an ngFor that iterates on an array of objects returned from a function.
2. place a mat-expansion-panel with a mat-expansion-panel-header inside
 
It fails if the function returns an array of objects but not an array of primitives.
It succeeds if trackBy is added.
The ngFor works if there isn't a mat-expansion-panel-header element inside it.

#### Expected Behavior

It works regardless of the ngFor array provided whether from a function or not, whether it has trackby or not.

#### Actual Behavior

Page increases ram usage and becomes unresponsive then crashes

#### Environment

- Angular:^9.0.0
- CDK/Material:^9.0.0
- Browser(s): Chrome 81.0.4044.138 (Official Build)(64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
That's because every change detection causes a new array to be returned, which in turn triggers another change detection, causing an infinite loop. You shouldn't be returning new objects like this, because it can lead to memory leaks and infinite loops.

**Comment by alexanderwiebe** [comment]
Thank you for that insight. That is the bug.  When I don't have the mat-expansion-panel it doesn't continue to call the function repeatedly.  When I add this specific angular component it results in an infinite loop which is a bug.

**Comment by crisbeto** [comment]
It's probably because the expansion panel has some event listeners for when an animation start and finishes. Since event listeners trigger change detection, they might be what's kicking it into the infinite loop.

**Comment by alexanderwiebe** [comment]
That still sounds like a bug.  Is there anywhere in the angular documentation that you could direct me to that says ngFor can not use a function to return the items?

**Comment by alexanderwiebe** [comment]
I tried to create an example without any animations and it is still causing the infinite loop. https://github.com/alexanderwiebe/mat-expansion-in-ngfor/tree/no-animations
