### ISSUE TITLE
How to open a particular menu programmatically if more than one menu elementhelp([COMPONENT]): [TITLE]

### ISSUE THREAD

**Issue by coderdipti** [angular/components#19292]
I want to get ViewChild dynamically to open the menu.
Here is my html code:
<button mat-menu-item [matMenuTriggerFor]="animals" (mouseover)="openOnMouseOver1()">Animal index</button>
<button mat-menu-item>Birds</button>
<button mat-menu-item>Mammals</button>
<button mat-menu-item [matMenuTriggerFor]="test" #clickHoverMenuTrigger="matMenuTrigger" (mouseover)="openOnMouseOver()">Test index</button>

.ts file code:
 @ViewChild(MatMenuTrigger, { static: false }) contextMenu: MatMenuTrigger;
 @ViewChild('clickHoverMenuTrigger',{ static: false }) clickHoverMenuTrigger: MatMenuTrigger;

Currently I am getting @ViewChild individually, is there anyway to get this dynamically? I want to open the menu using  this.contextMenu.openMenu() dynamically and close other menu items.
PLease if possible provide StackBlitz example.

**Comment by andrewseguin** [comment]
Please re-open your troubleshooting issue with a stackblitz showing what you have and what you want it to do. That way we can point you in the right direction
