### ISSUE TITLE
'mat-spinner' is not a known element.

### ISSUE THREAD

**Issue by drrrMikado** [angular/components#19305]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
'mat-spinner' is a known element.

#### What is the current behavior?
Template parse errors:
'mat-spinner' is not a known element.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-qobfhh?file=src%2Fapp%2Fapp.module.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 9.1.4
Material: 9.2.2

**Comment by matthieudesprez** [comment]
There is not mat-spinner or mat-progress-spinner in your example.

Have you imported the MatProgressSpinnerModule ?

**Comment by drrrMikado** [comment]
> There is not mat-spinner or mat-progress-spinner in your example.
> 
> Have you imported the MatProgressSpinnerModule ?

Sorry,Stackblitz url was updated.

**Comment by fatihtoker** [comment]
I have the same issue with mat-dialog. I didn't event change anything about material module. Yesterday it started to throw the error all of a sudden.

**Comment by matthieudesprez** [comment]
> > There is not mat-spinner or mat-progress-spinner in your example.
> > Have you imported the MatProgressSpinnerModule ?
> 
> Sorry,Stackblitz url was updated.

Ok, you are still missing the MatProgressSpinnerModule in your AppModule imports, it should looks like:
```typescript
@NgModule({
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    MatProgressSpinnerModule
  ],
  declarations: [
    AppComponent
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

Once it's added, the app should compile without any error, but you would still have to add a link to a material theme on top of your style.css file to make the spinner visible:
```scss
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
```

**Comment by drrrMikado** [comment]
> > > There is not mat-spinner or mat-progress-spinner in your example.
> > > Have you imported the MatProgressSpinnerModule ?
> > 
> > 
> > Sorry,Stackblitz url was updated.
> 
> Ok, you are still missing the MatProgressSpinnerModule in your AppModule imports, it should looks like:
> 
> ```ts
> @NgModule({
>   imports: [
>     BrowserModule,
>     ReactiveFormsModule,
>     MatProgressSpinnerModule
>   ],
>   declarations: [
>     AppComponent
>   ],
>   bootstrap: [ AppComponent ]
> })
> export class AppModule { }
> ```
> 
> Once it's added, the app should compile without any error, but you would still have to add a link to a material theme on top of your style.css file to make the spinner visible:
> 
> ```css-scss
> @import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
> ```

It's solved.Thank you.
