### ISSUE TITLE
fr(MatCalendar): Two month view

### ISSUE THREAD

**Issue by FrankiePo** [angular/components#19309]
#### Feature Description

Add new view for mat-calendar for desktop usage
![image](https://user-images.githubusercontent.com/5219218/81500382-96dfda00-92da-11ea-9c70-33fb47c059e0.png)
Source https://material.io/components/pickers#desktop-pickers

#### Use Case

Describe the use case(s) that the proposed feature would enable.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/18966.
