### ISSUE TITLE
bug([MatFormFieldHarness]): getControl() returns first input on the page, not the input within the form field

### ISSUE THREAD

**Issue by jkossis** [angular/components#19315]
#### Reproduction

Steps to reproduce:
1. Create a form with two mat form fields, each with a respective mat input
2. Get the harness for the 2nd form field's mat input (via the 2nd form field harness' `getControl()` method), and set it to any value.
 
#### Expected Behavior

Setting the value of the mat input returned by `getControl()` should set the value of the mat input associated with the corresponding form field.

#### Actual Behavior

Setting the value of the mat input returned by `getControl()` sets the value of the first mat input on the page, not necessarily the one associated with the form field. 

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.1.3
- Browser(s): Jest 25.5.4
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Can you post what your test looks like? I gave it a quickly try locally and it seemed to work as expected.

**Comment by jkossis** [comment]
@crisbeto going to share the test here shortly, but wanted to point out, this is where the issue most likely lies. 

https://github.com/angular/components/blob/master/src/material/form-field/testing/form-field-harness.ts#L98

If you step through that, it select the first mat input harness, not necessarily the one tied to that mat form field.

**Comment by jkossis** [comment]
```
it('should login', async () => {
    const router = TestBed.inject(Router);
    const routerNavigateSpy = jest.spyOn(router, 'navigate').mockReturnValueOnce(Promise.resolve(true));

    authServiceMock.login.mockReturnValueOnce(of(void 0));

    fixture.detectChanges();

    const emailFormField = await loader.getHarness(MatFormFieldHarness.with({selector: '[data-test="email"]'}));
    const emailInput = (await emailFormField.getControl()) as MatInputHarness;

    const passwordFormField = await loader.getHarness(MatFormFieldHarness.with({selector: '[data-test="password"]'}));
    const passwordInput = (await passwordFormField.getControl()) as MatInputHarness;

    const login = await loader.getHarness(MatButtonHarness.with({
      text: 'Login'
    }));

    await emailInput.setValue('test@test.com'); // This sets the email input
    await passwordInput.setValue('password'); // This also sets the email input, should set the password input

    expect(component.form.valid).toEqual(true);

    await login.click();

    expect(authServiceMock.login).toHaveBeenCalledTimes(1);
    expect(routerNavigateSpy).toHaveBeenCalledTimes(1);
  });
```

**Comment by crisbeto** [comment]
I'm still having a hard time reproducing it. Here's the test that I have which is passing:

```
fit('', async () => {
  const emailFormField = await loader.getHarness(MatFormFieldHarness.with({
    selector: '[data-test="email"]'
  }));
  const emailInput = await emailFormField.getControl() as any;

  const passwordFormField = await loader.getHarness(MatFormFieldHarness.with({
    selector: '[data-test="password"]'
  }));
  const passwordInput = await passwordFormField.getControl() as any;

  await emailInput.setValue('test@test.com');
  await passwordInput.setValue('password');

  expect(await emailInput.getValue()).toBe('test@test.com');
  expect(await passwordInput.getValue()).toBe('password');
});
```

And this is what I have in the test component:

```
<mat-form-field data-test="email">
  <mat-label>Email</mat-label>
  <input type="text" matInput>
</mat-form-field>

<mat-form-field data-test="password">
  <mat-label>Password</mat-label>
  <input type="password" matInput>
</mat-form-field>
```

Note that I'm running this through `TestBed` in a headless Chrome which could make a difference. 

Another thing worth trying could be to call `MatInputHarness.focus` before setting the value. It might be setting it on the wrong input if focus isn't being moved.

**Comment by jkossis** [comment]
@crisbeto not sure what the issue was, but now it seems to be working. Very odd. Nonetheless, closing the issue.
