### ISSUE TITLE
fr(cdk/drag-drop): support configurable propagation of mousedown and touchstart events

### ISSUE THREAD

**Issue by lincolnthree** [angular/components#19333]
#### Feature Description

Allow exposing native mousedown and touchstart events to parent elements such  that listeners farther up the chain can respond before a CdkDragEvent has started. Without these events, certain gestures (swiper, etc) cannot be achieved when events are started on a DragRef element, as drag-drop effectively swallows them whether they are used or not.

This feature should be enabled only if desired using the `CDK_DRAG_CONFIG` InjectionToken / provider pattern.

#### Use Case

Allow propagation of events to parent components in the DOM. Example: Using a cdkDragDrop component inside a horizontal swiper, where the native element's scroll direction is vertical.

**Comment by alexander-clark** [comment]
This would be really helpful. I'm trying allow dropping of items into fullcalendar using their ThirdPartyDraggable interface - https://fullcalendar.io/docs/third-party-dragging - but as soon as I add the cdkDrag, the integration breaks, presumably because every native event is being swallowed.

**Comment by lincolnthree** [comment]
Agreed @alexander-clark -- And just for anyone reviewing priorities on this issue. This is a complete blocker for our use of CDK. We've switched to React DND which supports the customization we need to support overlapping drag containers and non-drag gestures.
