### ISSUE TITLE
bug([MatStepper]): Press enter on input element (e.g. input, checkbox) jump to other tab step

### ISSUE THREAD

**Issue by nirkai** [angular/components#19342]
#### Reproduction
When pressing '**Enter**' key on input element inside a mat-stepper (checked on the horizontal stepper) the current step are skipped on.

_EDIT:
`Checkbox` element not should be clicked by `Enter`, but just by `space` like mentioned in [MDA site](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role)._

Can be reproduce on the official site example:
https://material.angular.io/components/stepper/examples

For example with checkbox:
https://stackblitz.com/edit/angular-reffdt

Steps to reproduce:
1. Navigate by keyboard or mouse to tab stepper.
2. Press 'Enter' key on an input element.
3. The focus "jump" to next tab step.
 
 
#### Expected Behavior
1. The focus should stay on the current tab step.

#### Actual Behavior
1. The focus jump to next tab step.

#### Environment

- Angular CLI: 9.0.1
- CDK/Material: Angular material 9.0.0
- Browser(s): 

1. Chrome Version 81.0.4044.129
2. Firefox Version: 76.0.1

- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows 10

**Comment by crisbeto** [comment]
Since the `input` is inside a `form` element, pressing enter will trigger the native form submit behavior. This seems to be working as expected.

**Comment by nirkai** [comment]
Thanks @crisbeto . 
Are you sure this is the expected behavior?

If I want to make a little more complex form it can make things to be very unexpected. 

For example: I want to add `x` button to clear the input filed, or add a button that open more details in the form. The user not expected to clear the filed when he clicked on `Enter`, or any other thing to happen.

You can add the `button` attribute of `type="button"` of course, but it not an obvious. 

I updated the [example ](https://stackblitz.com/edit/angular-reffdt) to illustrate things.
In the first step page you can enter string to the filed and press `Enter` (you can try to click `enter` on the `checkbox` too).
In the second page an 'alert' will pop up (can be any dialog).

**Comment by jelbourn** [comment]
This is working as expected as it relates to using the native `<form>` element. However, you have control over this behavior by either:
* Not using a native `<form>` with the stepper, or
* Capture and `preventDefault` on the key event
