### ISSUE TITLE
I want to fix tool bar like angular material nav bar. Please help me out how to do

### ISSUE THREAD

**Issue by Harshitha-7** [angular/components#19349]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by Harshitha-7** [comment]
Like We have sticky:true; do we have any class to stick tool bar

**Comment by lukaonik** [comment]
The mat-toolbar is a very simple component, it's only used for layout it's children elements. you can style mat-toolbar itself to fix it.
```
<mat-toolbar class="header"></mat-toolbar>
<style>

.header{
  position:fixed;
  top:0;
left:0;
right:0;
}
</style>
```

**Comment by Harshitha-7** [comment]
Don't angular material has predefined style for fixing toolbar like in side nav bar

**Comment by lukaonik** [comment]
no there is no predefined style for that

**Comment by Harshitha-7** [comment]
![image](https://user-images.githubusercontent.com/64891401/82209158-6e835b80-992a-11ea-9c2c-d0f87f441729.png)

Actually i wan't tool bar fixed and scroll as same like that picture(Angular material page)

**Comment by Harshitha-7** [comment]
please tell me that css

**Comment by vikasprashar99** [comment]
style={ position: "fixed", top: "0%", width: "100%", zIndex: "100" }

Try your code with this CSS

**Comment by annieyw** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2).
