### ISSUE TITLE
bug(drag-drop): preview does not work in <table> IE11 Edge18

### ISSUE THREAD

**Issue by Spaier** [angular/components#19351]
#### Reproduction

Github repro: https://github.com/Spaier/angular-cdk-drag-drop-in-table-ie11

drag and drop in `<table>`

Html
```
<table>
  <thead>
    <tr>
      <th>Column 1</th>
    </tr>
  </thead>
  <tbody cdkDropList
         [cdkDropListData]="items"
         (cdkDropListDropped)="drop($event)">
    <tr
      *ngFor="let item of items"
      cdkDrag
      cdkDragBoundary="tbody"
      [cdkDragData]="item">
      <td>{{item}}</td>
    </tr>
  </tbody>
</table>
```

Ts
```
import { Component } from '@angular/core';

import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.scss' ]
})
export class AppComponent  {
  items = ['Item 1', 'Item 2', 'Item 3', 'Item 4']

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(
      this.items,
      event.previousIndex,
      event.currentIndex);
  }
}
```

#### Expected Behavior

other template(s) moved to show where this template will be added

![Expected Gif](https://raw.githubusercontent.com/Spaier/angular-cdk-drag-drop-in-table-ie11/master/assets/expected.gif)

#### Actual Behavior

other template(s) aren't moved while cursor isn't released

![Actual Gif](https://raw.githubusercontent.com/Spaier/angular-cdk-drag-drop-in-table-ie11/master/assets/actual.gif)

#### Environment

- Angular: 9.1.7
- CDK/Material: 9.2.3
- Browser(s): IE11, Edge <= 18
- Operating System:  Windows

**Comment by crisbeto** [comment]
The issue seems to be that IE/Edge ignore the `transform` property on `tr` elements, which should be supported according to the spec.

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
