### ISSUE TITLE
bug([Mat-tooltip]): [Material Tooltip wont show on Angular 9]

### ISSUE THREAD

**Issue by detmold** [angular/components#19357]
#### Reproduction

https://codesandbox.io/embed/angular-9-template-utvxs?fontsize=14&hidenavigation=1&theme=dark

Steps to reproduce:
1. Install angular 9
2. Put on any html element: matTooltip="Info about the action" 
 
 
#### Expected Behavior

Tooltip will show

#### Actual Behavior

Tooltip wont show

#### Environment

- Angular 9:
- CDK/Material:
- Browser(s):
- Chrome, Firefox

**Comment by crisbeto** [comment]
It's because you haven't added `MatTooltipModule` to your module's `imports`.
