### ISSUE TITLE
bug([Mat-option]): selected values are emitted several times

### ISSUE THREAD

**Issue by vyacheslavzhabitsky** [angular/components#19358]
#### Reproduction

https://stackblitz.com/edit/angular-6ja7pc

Steps to reproduce:
1. Select different values few times
2. Check the console with log of onSelectionChange emitter
 
#### Expected Behavior

I expected that I would see the selected option which is emitted once

#### Actual Behavior

Option is emitted twice and second emit is wrong

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS

**Comment by crisbeto** [comment]
We use `mat-option` both for single selection and multi-selection panels, which is why the option emits both when it's selected and deselected. Closing since this is working as expected.

If you want an event that only emits when a value is selected, you can use `selectionChange` from `mat-select`.
