### ISSUE TITLE
fr(MatTooltip): Allow for template content/html

### ISSUE THREAD

**Issue by WynieCronje** [angular/components#19367]
#### Feature Description

Allow for HTML/Dynamic content inside MatTooltip with use of ng-template

#### Use Case

In my case. I show on a disabled button a tooltip explaining why the button is disabled. For this HTML and Binding is required inside the tooltip.

something like: 

```
<button mat-raised-button
        matTooltip="disabledReasons"
        [matTooltipDisabled]="!buttonDisabled">
  Submit
</button>

<ng-template #disabledReasons>
   ...
</ng-template> 
```

----- OR -------

```
<button mat-raised-button
        matTooltip
        [matTooltipDisabled]="!buttonDisabled">

<ng-template mat-tooltip-content>
   ...
</ng-template> 
  Submit
</button>
```

**Comment by jelbourn** [comment]
For accessibility purposes, tooltips can only contain plain text and not complex html content
