### ISSUE TITLE
docs-bug(mat-tab-nav): "selectedIndex" does not exist

### ISSUE THREAD

**Issue by keithguerin** [angular/components#19382]
#### Documentation Feedback

**Affected documentation page:** https://material.angular.io/components/tabs/api
Issue: mat-tab-nav-bar has a documented "selectedIndex" attribute, but it does not appear to exist.

I ran into the issue and then found a fix at https://stackoverflow.com/questions/50349155/selectedindex-is-not-working-for-mat-tab-nav-bar-angular-material-tabs

**Comment by crisbeto** [comment]
The docs are correct. Note that the `selectedIndex` isn't marked as an `Input` which means you can't bind to it.
