### ISSUE TITLE
help(linebreak-style exception): running yarn lint command throws many "Expected linebreak to be 'LF'" exceptions

### ISSUE THREAD

**Issue by lukaonik** [angular/components#19394]
#### What are you trying to do?

I try to run yarn lint command on the source, whenever I do that I get the following exception
"linebreak-style         Expected linebreak to be 'LF'", almost on every line. 

#### What troubleshooting steps have you tried?

run yarn lint command on the source

#### Reproduction

Steps to reproduce:
1. yarn lint

  
#### Environment

- Operating System (e.g. Windows, 10x):

**Comment by crisbeto** [comment]
This is working as expected. Your line endings are probably set to CRLF by default. At least in vscode you can change them here: 

![7bI90bY](https://user-images.githubusercontent.com/4450522/82338698-7d7f1200-99ed-11ea-999b-bda69d6be69d.png)
