### ISSUE TITLE
fr(menu/testing): add a method to get a HarnessLoader for menu content

### ISSUE THREAD

**Issue by mmalerba** [angular/components#19395]
#### Feature Description

Add a method to get a HarnessLoader for the menu content

#### Use Case

The menu harness provides methods to get standard menu content like items, however, some users add other custom content to their menus. Providing a HarnessLoader for the content will allow them access to this custom content

**Comment by crisbeto** [comment]
The `MatMenuHarness` extends the `ContentContainerComponentHarness` now which resolves this issue.
