### ISSUE TITLE
A text label that is displayed when the user hovers over a blank area

### ISSUE THREAD

**Issue by apeter10** [angular/components#19398]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A text label that is displayed when the user hovers over a mat-icon element.

#### What is the current behavior?
A text label that is displayed when the user hovers over a blank area on the right of a mat-icon element.

#### What are the steps to reproduce?
If the icon name is 'information', a text label that is displayed when the user hovers over a blank area on the right of a mat-icon element.
But the icon name is 'home', the behavior is normal.
Please refer to the StackBlitz starter: https://tinyurl.com/y9b25qya

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, 7, 8, 9

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/11826.
