### ISSUE TITLE
fr(DRAG&DROP): It should be possible to set the speed of the drag and drop

### ISSUE THREAD

**Issue by GitHubish** [angular/components#19401]
We find that the drag and drop is too slow on our project management application (Trello Like). We would like the drag and drop to be as fast as on Trello.

Is it possible?

**Comment by crisbeto** [comment]
What speed are you referring to exactly? The automatic scroll speed or something else?

**Comment by GitHubish** [comment]
I see I made a mistake in the title, I only put the modal feature... it's about the Drag And Drop CDK.

To answer you @crisbeto , indeed I wasn't very clear. I'm talking about horizontal scrolling in my case when I move an element out of the screen. Horizontal scrolling is quite slow and therefore not very practical. Hopefully my request is a little clearer.

**Comment by vadimromanyak** [comment]
Any updates on this?

**Comment by bj2jung** [comment]
I have the exact same issue, wondering if there is any update
