### ISSUE TITLE
bug([drag-drop]): mouse events during CDK drag have inconsistent behaviour in major browsers

### ISSUE THREAD

**Issue by danigiri** [angular/components#19418]
#### Reproduction

https://stackblitz.com/edit/components-issue-mdmwve

Steps to reproduce:
1) Go to https://material.angular.io/cdk/drag-drop/overview
2) Take the  cdk-drag-drop-sorting-example
3) Add 
```
    (mouseenter)="mouseEnter(movie)"
    (mouseleave)="mouseLeave(movie)"
```
to the example html template
4) Add
```
mouseEnter(movie: string) {
    console.info("enter ", movie);
}
mouseLeave(movie: string) {
    console.info("leave ", movie);
}
```
to the component .ts file
5) move mouse from the top to **Episode I - The Phantom Menace**, drag it past **enter Episode II - Attack of the Clones**, release mouse, move mouse to the left without going over any other movie tiles
6) Try in different major browsers
 
#### Expected Behavior 

Either this order of mouse events (beahviour 1)
```
enter Episode I - The Phantom Menace
leave Episode I - The Phantom Menace
enter Episode II - Attack of the Clones
leave Episode II - Attack of the Clones
enter Episode I - The Phantom Menace
leave Episode I - The Phantom Menace
```
Or  (behaviour 2)
```
enter Episode I - The Phantom Menace
enter Episode II - Attack of the Clones
leave Episode II - Attack of the Clones
enter Episode I - The Phantom Menace
leave Episode I - The Phantom Menace
```
for all major browsers

#### Actual Behavior

Google Chrome and Safari exhibit behaviour 1, Firefox exhibits behaviour 2, consistently.

#### Environment

- Angular:   "@angular/core": "^9.0.2"
- CDK/Material:    "@angular/cdk": "^9.1.0"
- Browser(s): Safari Version 13.1 (15609.1.20.111.8), Google Chrome Version 81.0.4044.138 (Official Build) (64-bit), Firefox 76.0.1 (64-bit)
- Operating System: macOS

#### Comments
It looks like the actual underlying DOM manipulation taking place is done differently. Both behaviours are OK (if a bit counterintuitive) but the observed difference is confusing at best, consistent behaviour would be great. If out of the scope of the component (and down to the browser) we could have some caveat on the documentation mentioning that mouse events during drag will not necessarily be consistent in different browsers implementation.

I am activating some information panel on the currently dragged and I can work around by adding guards variable in mousedown(activate a flag), mouse events (ignored if flag), dropped callback(deactivate flag). Mouseup is not called on the dropped callback though, so it may be called in the future (as that is not part of the documented 'contract' either) and may break my code.  A note about mouse events not being part of the contract (and therefore potentially exhibiting undefined behaviour) on the docs would definitely help.

#### Screenshots attached
firefox:
![firefox](https://user-images.githubusercontent.com/1434295/82611159-2da47480-9bc0-11ea-8d6c-fdac98089f04.png)

chrome and safari:
![other-browsers](https://user-images.githubusercontent.com/1434295/82611168-32692880-9bc0-11ea-9b74-ba273405f3fd.png)

**Comment by danigiri** [comment]
(edited original post to upload correct screenshots)

**Comment by crisbeto** [comment]
There are a couple of issues with using mouse events here:
1. You're not guaranteed that they'll all fire in the way you expect them to, especially if the elements are being animated.
2. The mouse events either won't fire, or they'll be very inconsistent on touch devices, even without the CDK.

Is there a reason why you can't use the various events provided by the `drag-drop` module?

**Comment by danigiri** [comment]
Thanks for looking into this, indeed documentation does not specify any guarantees on how the animation will be performed and we end up with this behaviour, with the addition that may differ between browser implementation.

1) I would say that it would help a lot that we get some mention on this in https://material.angular.io/cdk/drag-drop/overview as it may not be obvious to users, it would have saved me some hours of debugging. In retrospect it looks obvious to me now, but it was not so at the time.
Something along the lines of "List manipulation when dragging and dropping is done using a combination of DOM changes and animations, the specific order of those actions is an implementation detail". But I may be biased by my use-case.

2)  True, touch is extra complicated in my scope, I am trying to solve the mouse one first and then think of touch (more on this below)

****
Regarding the various events in `drag-drop`, the use case I am working on wants to highlight using styles the locations where drag-and-drop is allowed, before the users go and drag the item to the list and find out that it's not an allowed location. This is better explained using an example:

Take `CdkDragDropEnterPredicateExample` and add another list called `Odd numbers` where only odd numbers are allowed, to find out which of the two lists is ok to drop onto, the user has to drag and experimentally try to drop onto the two lists (or understand the logic, which is trivial in this case, but may not be obvious in real world applications). It would be great if we could change the style of the target lists when rolling over the original item (ok for mouse, not so for touch) or at least starting to drag (ok for mouse and touch) that item to highlight to the user which of the two destination lists is eligible.

You can start to emulate this with callbacks on `mouseup` and `mousedown`, plus a callback on `cdkDropListDropped`, but we're crossing domain boundaries, for the same control logic, I have callbacks on low level DOM events (like mouseup) and on high level `cdk*` events. A minor semantic detail, but it would be neater if we could expose `CdkDragStart`, as then the control logic would remain within the cdk* domain for the start and end of the interaction, and be less implementation dependant.

Secondly, imagine a more advanced use case, where we want to highlight *where* in the list users are allowed to drop before they try it, in `CdkDragDropEnterPredicateExample` we would want the user to drop the items in numerical order within `Even numbers` and not just anywhere within that list.

In `cdkDropListEnterPredicate` does not have enough granularity, so what we have to do is allow drop, and on `cdkDropListDropped` have logic to detect we dropped in a disallowed location, skip changing the model and convey to the user (like a reverse animation) that this was disallowed. Users will simply ask, why wasn't I told in advance this was not a good location?

There is no way to know where in the list we are hovering to warn the user that it's a disallowed location.

As a workaround we can:
1) Play with low level events: brittle, browser dependant, not touch friendly, crosses domain boundaries, not guaranteed to work in the future
2) Move from a destination list of N items to N destination lists of 1 item so I can have a tailored `cdkDropListEnterPredicate` for each one, we have: convoluted, still crossing domain boundaries, defeats the purpose of using `drag-drop` component in the first place.

Probably exposing `CdkDragSortEvent` would let me build a far more robust solution, without brittle low level logic, and not crossing domain boundaries. `CdkDragSortEvent` would have to take into account when hovering into an empty list (there is no items being swapped) or hovering just at the beginning or end (we're not technically swapping items, just prepending or appending). So may be a `CdkDragHoverEvent` would be more semantically appropriate.


****

Hopefully this helps in describing the use-case and how the lack of events exposed make this hard to solve. If exposing. Thanks in advance for checking this out.

**Comment by crisbeto** [comment]
The CDK adds a CSS class called `cdk-drop-list-receiving` to lists that the current item can be dropped into which you can use to style your list. As for the more advanced use case where you have different areas where the item can be dropped, maybe you can emulate it by using multiple drop lists?

**Comment by danigiri** [comment]
`cdk-drop-list-receiving`: I'll give it a go, thanks for the tip
> maybe you can emulate it by using multiple drop lists?
I gave it ago and code increased in complexity a lot (as opposed to something like `CdkDragSortEvent` being exposed), I'll try the reverse animation approach now and give it some additional thinking to compare that with the multiple drop lists.

Thx for the hints!

**Comment by danigiri** [comment]
Can close this, will have a go at the reverse animation approach as stated, thanks for checking this out.
