### ISSUE TITLE
feat(cdk/overlay): connected-overlay directive should have input for disabling escape close

### ISSUE THREAD

**Issue by MikeDabrowski** [angular/components#19420]
#### Feature Description

Currently connected-overlay is hardcoded to be closed on escape. https://github.com/angular/components/blob/5f125395e0d39eb7e6a34d0c3355fc474f4d37a8/src/cdk/overlay/overlay-directives.ts#L287-L289
I propose adding a way to control this behavior.

#### Use Case

In my project I need an overlay that does not close on keyboard event. Also, if in the overlay we have a form, there may happen a situation when user should be forced to complete it before closing the overlay.

I create overlay in this manner:
```
  cdk-connected-overlay
  cdkConnectedOverlayHasBackdrop
  cdkConnectedOverlayBackdropClass="light-backdrop"
  [cdkConnectedOverlayOrigin]="origin"
  [cdkConnectedOverlayPositions]="positions"
  [cdkConnectedOverlayOpen]="isOpen"
  [cdkConnectedOverlayScrollStrategy]="scrollStrategy"
```

**Comment by victorward** [comment]
Any update on this feature, for us it's something crucial ...
We can contribute if you need any help ;)

**Comment by victorward** [comment]
@devversion Can you take a look if PR with this feature is good enough? #20585

**Comment by joelkesler** [comment]
Has this been solved for you with recent updates?

I see a check has been added that lets you bypass the escape key closing with `cdkConnectedOverlayDisableClose`

https://github.com/angular/components/blob/15.0.x/src/cdk/overlay/overlay-directives.ts#L316-L319

**Comment by victorward** [comment]
Yes, it was solved for me when it was released. I don't remember the details but I see that we are using it
