### ISSUE TITLE
feat(youtube-player): add option to hide controls or pass `playerVars` options

### ISSUE THREAD

**Issue by lautarojgarcia177** [angular/components#19427]
#### Feature Description

Youtube's player hide controls

#### Use Case

I want to hide the player's controls and provide my own

**Comment by devversion** [comment]
It looks like these options could be set through the `playerVars` option when we construct the `Yt.Player`. We could provide a way for consumers to pass these options, or have convenience inputs (though that might be verbose to maintain).

cc. @YourDeveloperFriend

**Comment by devversion** [comment]
Closing this as a duplicate of https://github.com/angular/components/issues/19267
