### ISSUE TITLE
Reactive forms using FormBuilder.array() loses focus of input control

### ISSUE THREAD

**Issue by patilmangeshv** [angular/components#19430]
#### Bug, feature request, or proposal:
Bug in ReactiveForms

#### What is the expected behavior?
After entering a value the focus should remain in the input control. The input control is created using FormBuilder.array().

#### What is the current behavior?
After entering a value the input control loses the focus.

#### What are the steps to reproduce?
Providing a github repository link below. Please refer the readme.md for more details.

https://github.com/patilmangeshv/ngFormsIssue.git

#### What is the use-case or motivation for changing an existing behavior?
It seems a bug unless I am missing something in my code.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular version 9.1.9
OS: MacOS 10.15.4
Typescript: 3.8.3

#### Is there anything else we should know?
Please readme.md file for more details

**Comment by EdricChan03** [comment]
You're posting in the wrong repository - this repository is for Angular components including Angular Material and the CDK. I suggest that you should either:

- Post a bug report on the [Angular repository](https://github.com/angular/angular/issues/new)
- Or ask a question on [StackOverflow](https://stackoverflow.com/questions/ask)

**Comment by crisbeto** [comment]
Closing since the project doesn't appear to be using any of the components from this repository.
