### ISSUE TITLE
bug([mat-selection-list]): [mat-selection-list component is very slow in IE11 and working fine in other browsers]

### ISSUE THREAD

**Issue by ilapavuluri** [angular/components#19435]
#### Reproduction

Hi Team,

I am using mat-selection-list in my application and more than 100 options with checkboxes, it is working in chrome, firefox and edge but in IE11 it is very slow and hangs.

Appreciate your help. 

Here is the sample code:
```html
        <div>
            <mat-selection-list #options [(ngModel)]="selectOptions" [compareWith]="compareFunction" (selectionChange)="onOptionSel($event)">
                <mat-list-option *ngFor="let cio of ciOptions" checkboxPosition="before" [value]="cio" aria-label="cio">
                   {{cio.label}}
                </mat-list-option>
             </mat-selection-list>
        </div>
```

Steps to reproduce:
1. I am using mat-selection-list in my application and more than 100 options with checkboxes, it is working in chrome, firefox and edge but in IE11 it is very slow and hangs.
2. Here is the sample code:
```html
        <div>
            <mat-selection-list #options [(ngModel)]="selectOptions" [compareWith]="compareFunction" (selectionChange)="onOptionSel($event)">
                <mat-list-option *ngFor="let cio of ciOptions" checkboxPosition="before" [value]="cio" aria-label="cio">
                   {{cio.label}}
                </mat-list-option>
             </mat-selection-list>
        </div>
 ```
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by ilapavuluri** [comment]
Hi Team,

Please help me in solving this issue, else I cannot use mat-selection-list.

Thanks
Ashok.

**Comment by Splaktar** [comment]
@ilapavuluri We chatted about this and I think that this is resolved by using `*cdkVirtualFor`?

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
