### ISSUE TITLE
help(FullscreenOverlayContainer): Why does OverlayContainer exist at all?

### ISSUE THREAD

**Issue by tmtron** [angular/components#19434]
As I understand [FullscreenOverlayContainer](https://material.angular.io/cdk/overlay/overview#full-screen-overlays) is the same as `OverlayContainer` except that it also works in full-screen mode.  
So I wonder: why would we ever want to use `OverlayContainer` when it does not work in full-screen mode - and why is this the default?

Are there any disadvantages of using `FullscreenOverlayContainer`?

related [Stackoverflow question](https://stackoverflow.com/questions/57019959/overlaycontainer-vs-fullscreenoverlaycontainer)

**Comment by jelbourn** [comment]
IIRC the original reasoning was that handling full-screen mode was extra code that not everyone necessarily needed, so it was done in a separate class. If we were doing this from scratch, I'm not 100% sure we'd do the same thing, but I don't think it's enough of a problem to go through refactoring now.
