### ISSUE TITLE
fr(matStepper): Most useless component ever

### ISSUE THREAD

**Issue by demiro** [angular/components#19445]
I pretty much love angular material, but this component is the worst component I ever used.
I cannot remember when was the last time I fought so much with a component.

Instead of making my life easy, it made it so much harder. I could have done a normal tabs with some extra logic, ages ago. Or a bit longer with my own component.

I just need a normal stepper (whether numbers or icons)... 
the possibility to select a desired step dynamically and make a step disabled (not by setting everything as linear and setting previous steps as not completed)... 

Don't get me started on lazy loading, etc.

Please, I urge you, please... redesign this whole component and make it more developer friendly

**Comment by andrewseguin** [comment]
Sorry that our stepper was more of a hinderance than help. It's not uncommon that a component is designed for one set of use cases, but fails to meet the needs of others. We'd be open to receiving any help to make the component better.

**Comment by demiro** [comment]
The easiest would be to extend the tab component for the same purpose....  and ...
- restyle
- add automatic number (label) option
- add linear functionality....

anything else, tab component is great... handles the labels well, can put the disabled to a tab, can lazy load content, etc.
