### ISSUE TITLE
[Table] Sort example incorrectly sorts JSON parsed string, part 2.

### ISSUE THREAD

**Issue by cik10p** [angular/components#19455]
Hello,

This bug is continuation of previously reported bug.
https://github.com/angular/components/issues/19444
My previous bug report was closed, with no code example provided that could prove that I was wrong. I still think this is an issue, and it should be addressed.

Speaking of sorting algorithm, I was explained that according to lexicographical comparison (sorting) in JS this works as designed. But I must disagree. 
Because in my lexicographical sorting example, I am getting desired results.
![image](https://user-images.githubusercontent.com/3006420/82986313-4bc60680-9ffe-11ea-8fc1-065320c987d8.png)

I am still trying to parse a JSON string, and load it into Element data array. And display sorted results correctly.
Here is my example here: https://stackblitz.com/edit/angular-92pdva-pkkzwk?file=app%2Ftable-sorting-example.ts Please visit https://github.com/angular/components/issues/19444 issue for more details.

**Comment by devversion** [comment]
Hey. Please give us a chance to reply on your original issue 😄 I'm re-opening the other one as we already have a discussion there.
