### ISSUE TITLE
build: release output contains forward references that break at runtime

### ISSUE THREAD

**Issue by lacolaco** [angular/components#19454]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. https://stackblitz.com/edit/angular-wudjzd?
2. Downdoad app as zip
3. open zip, `npm install` and `npm start`
 
 
#### Expected Behavior

As well as on Stackblitz, it should work correctly on the local environment. But it isn't.

#### Actual Behavior

Datepicker throws a runtime error.

![image](https://user-images.githubusercontent.com/1529180/82978922-b5570c80-a020-11ea-8988-046cf76fa006.png)

I think maybe it is caused by `ngcc` process but I'm not sure.

#### Environment

```
Angular CLI: 10.0.0-rc.0
Node: 12.14.1
OS: darwin x64

Angular: 10.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.0
@angular-devkit/build-angular     0.1000.0-rc.0
@angular-devkit/build-optimizer   0.1000.0-rc.0
@angular-devkit/build-webpack     0.1000.0-rc.0
@angular-devkit/core              10.0.0-rc.0
@angular-devkit/schematics        10.0.0-rc.0
@angular/cdk                      10.0.0-next.2
@angular/material                 10.0.0-next.2
@ngtools/webpack                  10.0.0-rc.0
@schematics/angular               10.0.0-rc.0
@schematics/update                0.1000.0-rc.0
rxjs                              6.5.5
typescript                        3.9.3
webpack                           4.43.0
```

**Comment by devversion** [comment]
Thanks for this issue. That is a known issue. It's related to: https://github.com/microsoft/TypeScript/issues/27519 and https://github.com/angular/angular/issues/30106.

**Comment by mcalmus** [comment]
Any workarounds for this? In which version did this begin? I've successfully messed up my working copy of code but am not sure which change(s) caused the problem.

**Comment by devversion** [comment]
@mcalmus It broke with https://github.com/angular/angular/commit/a1001f2ea0e59e3ce20bcc8c93d6ab5a912f6a4a, and we started building release output with those changes in `next.2`. Staying on `next.1` is the current workaround.
