### ISSUE TITLE
google-maps: expose directives for template reference usage

### ISSUE THREAD

**Issue by anthonyblanchettepotvin** [angular/components#19462]
#### Feature Description

Add `exportAs` directive meta-data to the `map-polygon`, `map-polyline`, `map-circle` and `map-rectangle` directives. That would allow to template reference the directives' class's instance in order to pass it as an argument into a function call, to access its properties from within the DOM and everything else that template referencing features.

#### Use Case

You could create a template reference inside a `map-polygon` directive tag and pass the reference as an argument into a function call like so :

![issue_1](https://user-images.githubusercontent.com/56654138/83042167-54730880-a00f-11ea-841e-7a69343c9a6c.PNG)

This allows the function `onPolygonClick` to receive the `MapPolygon` instance, as an argument, of the polygon that has been clicked. With that you could change the properties of the `MapPolygon` instance like `editable`, `draggable`, `visible` to dynamically modify the appearance and the behavior of the polygon.

![issue_2](https://user-images.githubusercontent.com/56654138/83043729-3a3a2a00-a011-11ea-9a93-f99aaf9b3031.PNG)

#### Current Use Case

Correct me if I am wrong, but at the moment, I don't think this is possible. The `MapPolygon` directive doesn't have the `exportAs` meta-data, so it's not possible to template reference a `MapPolygon` instance.

Of course, you can pass the `google.map.Polygon` object declared in an `*ngFor` in a function call like so :

![issue_3](https://user-images.githubusercontent.com/56654138/83044765-a23d4000-a012-11ea-850e-40e46319c811.PNG)

But then, doing something like that :

![issue_4](https://user-images.githubusercontent.com/56654138/83044871-c862e000-a012-11ea-8da8-e97b2259771b.PNG)

Do not hide the polygon.

#### Scope

This issue applies to the following directives : `map-polygon`, `map-polyline`, `map-circle` and `map-rectangle`.

**Comment by devversion** [comment]
Seems like we can do this for other directives/components in the `google-maps` package too.

**Comment by devversion** [comment]
Seems like a good feature request to me. Since most of these google-maps parts (such as `map-polygon`) are directives, using an implicit template reference does not work. Therefore I think it would make sense to have `exportAs` on those directives.
