### ISSUE TITLE
bug(Select): dont show icon in select 

### ISSUE THREAD

**Issue by behroozbc** [angular/components#19460]
#### Reproduction

https://stackblitz.com/edit/angular-rw5yju
Steps to reproduce:
1. click on select
2. choice on option 
 
 
#### Expected Behavior

Show icon in select 

#### Actual Behavior

show name of icon 

#### Environment

- Angular:9.1.6
- CDK/Material:9.2.3
- Browser(s):Microsoft edge Version 83.0.478.37
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10 Version 1909

**Comment by devversion** [comment]
Hello! This works as expected. A `mat-option` always holds a textual representative value that is determined based on the elements `textContent`.

The select uses that value (by default) for displaying the selected option. You can override this with a custom trigger by using `MatSelectTrigger`. I hope that helps!

https://material.angular.io/components/select/examples
