### ISSUE TITLE
Drag & Drop component with MatInput textarea throws an exception

### ISSUE THREAD

**Issue by bursacmilan** [angular/components#19463]
#### Bug
I'm using the Drag & Drop component. Basically it's a CdkDropList with Mat-Input textareas as drag items (cdkDrag). If I move a textarea (and do not click first on the textarea), all works as expected. But if I click first on the textarea, write something in it and move it, so the following error appears: 
`Error in /turbo_modules/@angular/cdk@9.2.4/bundles/cdk-drag-drop.umd.js (1160:47)
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`

I saw in the error, that a canvas element has a width or height of 0. So I debugged and found out, that if I click on the textarea, an element with name "lt-mirror" appears:
`<lt-mirror style="display: none;">...</lt-mirror>`

This element has a height, width, maxHeight and maxWidth of 0. Maybe this is a problem.
If I use a textarea without MatInput (or a MatInput with an `<input>` element), so all works fine

#### What is the expected behavior?
I can drag and drop MatInput textareas without errors.

#### What is the current behavior?
An error ist thrown if moving an MatInput textarea in a cdkDropList.

#### What are the steps to reproduce?
You can reproduce the error on the following Stackblitz: https://stackblitz.com/edit/angular-upzsf5

1. Click on a textarea
2. Write something
2. Try to move it
3. Error is thrown

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I'm using Angular Material Components 9.2.4.

**Comment by jelbourn** [comment]
@bursacmilan I tried your StackBlitz but it doesn't throw any errors. We don't have any `<canvas>` elements in the entire library, so I suspect it's probably something in your application.  

Which browser / OS did you use?

**Comment by bursacmilan** [comment]
Hi @jelbourn, when creating the GIF for the preview I noticed that I use an add-on for the spelling correction (the blue dot that appears). After uninstalling the addon, the error no longer occurs. The issue can be closed. Thanks & sorry.


![record](https://user-images.githubusercontent.com/16178688/83080276-13fea380-a07e-11ea-9104-5ce2e2d475b0.gif)
