### ISSUE TITLE
fr(MatSelectHarness): Allow clicking/getting options by value instead of label

### ISSUE THREAD

**Issue by mischkl** [angular/components#19470]
#### Feature Description

Allow clicking and getting options from MatSelectHarness by value instead of label.

#### Use Case

In our application the labels for selects may change due to requirements changing over time, but the values don't. Therefore it would be more helpful for the OptionHarnessFilters to allow filtering by value than by text.

**Comment by devversion** [comment]
cc. @crisbeto. I think that we cannot do that as the value could be any arbitrary (non-string) value that doesn't necessarily translate well to the DOM. The harnesses only work on the actual DOM (and do not have access to component instances), so we cannot retrieve the value.

That is most likely also the reason why there only is a `getText()` method for the option harness.

**Comment by mmalerba** [comment]
Closing this issue since it's not feasible with the way the harnesses are designed.
