### ISSUE TITLE
help(mat-icon): Failing HTTP requests on registered SVG icons that are served through CDN

### ISSUE THREAD

**Issue by antonisPanos** [angular/components#19489]
#### What are you trying to do?

I'm trying to fetch SVG files, that are set in the MatIconRegistry,  from CDN. While most of the assets, that are set in the icon registry are fetched successfully, some randomly fail.

The CORS policy is set, on the AWS bucket that serves my assets through CDN, and allows all `GET` requests. All assets there (js, fonts, images. etc.) are served successfully.

Also this is how the SVG files are registered in my app:
```
this.matIconRegistry.addSvgIcon(
  'houseGray', this.domSanitizer.bypassSecurityTrustResourceUrl(require('../../../assets/img/regular/house--shuttle-gray.svg'))
);
```
##### Note: I use `require()` because I want the asset path to be prefixed with the `deploy-url` when I build for production.

While most of the assets are fetched successfully, sometimes, some fail due to CORS. I noticed that the requests that fail, are missing the HTTP method in the request and I was wondering how this can be possible.

This is a successful request:
```
Request URL: https://my-staging-cdn.s3.amazonaws.com/admin/9e8ed37372ddebdad28dc758d0422fd1682cd47c/house--shuttle-gray.70463f6a5833405a53d8.svg
Request Method: GET
Status Code: 200 OK
Remote Address: 52.216.114.35:443
Referrer Policy: no-referrer-when-downgrade
```
This is an unsuccessful request that leads to CORS error:
```
Request URL: https://my-staging-cdn.s3.amazonaws.com/admin/9e8ed37372ddebdad28dc758d0422fd1682cd47c/house--shuttle-gray.70463f6a5833405a53d8.svg
Referrer Policy: no-referrer-when-downgrade
```
Note, that on the latter, the HTTP request method is missing.

This behavior even happens with (non-cached) assets that were previously fetched successfully (like my example). Seems like that this behavior is a little random, regarding which assets are affected and when.

What's noteworthy is that this happens on Chromium based browser and Safari, but not with Firefox (all at their latest version at the time of writing)

Since the HTTP request is handled by the MatIconRegistry, I was hoping you got an idea on what's going on here and if it's possible for a request to be missing the HTTP request method.

#### What troubleshooting steps have you tried?

- Tried to change the path of the asset
- Allowed all HTTP methods on my CORS policy
- Checked that the file exists on my CDN
- Checked the validity of the code of the SVG file
- Fetched the SVG file alone with a `GET` request from the same address that was failiing
- Changed the target of my build in `tsconfig` from `es5` to `es6` hoping that the request will be created in some other way

#### Reproduction

Unfortunately, I can't provide my environment for testing on the issue, because the bucket belongs to a company and it accepts requests from specific origins

Steps to reproduce:
1. Register svg files in the MatIconRegistry
2. Use `require()` to set the file path
3. Set a `deploy-url` to a different origin and allow GET requests in CORS policy
4. Use a Chromium based browser
  
#### Environment

- Angular: 8.2
- CDK/Material: 8.2
- Browser(s): Chromium based browsers and Safari
- Operating System (e.g. Windows, macOS, Ubuntu):  Arch, Ubuntu, macOS

**Comment by jelbourn** [comment]
@antonisPanos `MatIconRegistry` uses `HttpClient` in a pretty straightforward way, so I don't see how it would be causing CORS issues here. Is there something specific in `MatIconRegistry` you think is problematic here? Without that, there's not much we can really do here.

**Comment by antonisPanos** [comment]
I don't think it's something specific my friend. To be honest it's a very strange case and the worst is that I can't find a way to reproduce it. Like I mentioned in the issue, this behavior is not consistent and I thought of asking, just in case you faced something similar.

I'm going to close this issue. Thanks for your time my friend!
