### ISSUE TITLE
virtual scroll does not drag-n-drop

### ISSUE THREAD

**Issue by snoooopy-ch** [angular/components#19491]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-7nkwxb?file=src/app/example-component.ts

#### Expected Behavior
I want to it works with drag-n-drop action whenever and whatever I scroll it.

#### Actual Behavior
When I drag and drop it after scrolling somewhere, It doesn't work.
It changes other postion.
I am sure that previousIndex and currentIndex are wrong in drop event.

#### Environment
- Angular: 9
- CDK/Material:
- Browser(s): Chrome83
- Operating System (e.g. Windows, macOS, Ubuntu): Win10

**Comment by crisbeto** [comment]
Should be covered by https://github.com/angular/components/issues/10122.

**Comment by snoooopy-ch** [comment]
Hi, Kostadinov.
Thanks for your time to read my thread.

I read the #10122, but I couldnot find the solution.
Would do you update the way it works?
Or Is it on correcting now?

It is appreciate if you replay me.
Kind regards.

**Comment by crisbeto** [comment]
Drag&drop with virtual scroll doesn't work at the moment. #10122 is the issue we use to keep track of problems like this.

**Comment by snoooopy-ch** [comment]
Thanks for you reply.

May I have a chance to work it in the future?
If It is possible, When is it?
