### ISSUE TITLE
bug (cdk/drag-drop): Can't add Theme style '.cdk-drag-preview'

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular/components#19494]
- The theme class is set on the app-component which is the first (and only) element of the `body`.
- When executing drag-and-drop the dragged element (with the class `.cdk-drag-preview`) is attached to the body.

Due to this the `.cdk-drag-preview` isn't controlled by themes system.

This bug was already reported twice see:
1. https://github.com/angular/components/issues/17089
2. https://github.com/angular/components/pull/17304

The first bug was resolved with a workaround - Set the theme class directly on the body, not on the app-component.
The 2nd bug was resolved with some code change by the material team.

However I'm still getting this problem. Can someone tell me how to fix this?? (putting the theme selector on the body will not work for me)

**Comment by jelbourn** [comment]
> The theme class is set on the app-component

Nothing in Angular Material sets a theme class to any element like this. It sounds like something your app would be doing. It sounds like you may just be having a CSS targeting or specificity issue, which you would have a better chance debugging on StackOverflow or gitter. Feel free to open another issue with a reproduction if you believe there's some bug in cdk/drag-drop.
