### ISSUE TITLE
Need Help!!

### ISSUE THREAD

**Issue by IngoManthey** [angular/components#19490]
I've been trying to solve my problem for 3 days now, but can't find anything on Google and I'm at the end with my knowledge.
I have a MapMarker:
`this.marker = {
      position: {
        lat: this.lat,
        lng: this.lng,
      },
      label: {
        color: 'red',
        text: ' ',
      },
      title: this.gT('maps.Homeposition'),
      info: this.positionText,
      options: {
        draggable: true,
      },
    };`

`<map-marker *ngIf = "marker"
    [position]="marker.position"
    [label]="marker.label"
    [title]="marker.title"
    [options]="marker.options"
    (mapDragend)="mapDragend()"
  >
  </map-marker>`

When I move the marker, the mapDragend event is fired. The marker.position property is still the same. How do I get the new position ???

Thanks for help.

**Comment by devversion** [comment]
Hello! You could use the `getPosition` method. `marker.position` is not updated as it is just passed one-way into the `map-marker` component. e.g.

```html
<map-marker #marker (mapDragend)="onDragEnd(marker.getPosition())">
</map-marker>
```

or you just access the marker through a view children and call `MapMarker.getPosition()`.

I hope that helps! 😄
