### ISSUE TITLE
feat(mat-slide-toggle): Consider adding loading state indicator

### ISSUE THREAD

**Issue by philmayfield** [angular/components#19501]
#### Feature Description

Add a progress spinner to the "thumb" of the mat-slide-toggle component as shown in the Behavior section of Material design documentation: [https://material.io/components/selection-controls#switches](https://material.io/components/selection-controls#switches)

#### Use Case

Material describes the toggle behavior as "When a user toggles a switch, its corresponding action takes effect immediately."  For most of us working in the web, that means a potentially async event triggered on change.  This would let us show visually that the app is "working on it".

**Comment by jelbourn** [comment]
This isn't something we specifically plan on doing, though it could conceivably be added to MDC Web at some nebulous point in the future.
