### ISSUE TITLE
Mat Tabs endless toggling issue on fast changing of tabs

### ISSUE THREAD

**Issue by prtk9** [angular/components#19506]
**Expected Behavior**
Change tabs very quickly, each tab has large amounts of data to process. When switching between tabs too quickly the tabs shouldn't go into an endless toggle.

**What behavior were you expecting to see?**
On changing tabs very quickly, it shouldn't get stuck in endless toggle and instead stop on the last clicked tab.

**What behavior did you actually see?**
Change tabs very quickly, each tab has large amounts of data to process. When switching between tabs too quickly the tabs go into an endless toggle.

**Comment by crisbeto** [comment]
It's hard to tell what's going on from the description. Can you post a Stackblitz that shows the issue?

**Comment by prtk9** [comment]
https://github.com/angular/components/issues/4639, this was a similar issue raised by someone and it has the required reproduction steps.
@crisbeto Could you please try and have a look at that ?

**Comment by crisbeto** [comment]
It looks like a fix for that issue was pushed a long time ago so if this fails, it's probably something different.

**Comment by prtk9** [comment]
yes, but the issue still persists, when there are two or more than two tabs and each tab contains lot of content(suppose 1000000 records in a grid), fast toggling between the tabs results in an endless cycle of toggling. On attaching a debugger every thing seems to work fine, as in proper index of the selected tab is passed, but it goes on endlessly.

**Comment by jelbourn** [comment]
@prtk9 without a reproduction there's not much we can investigate. Is there any way you can provide a StackBlitz?

**Comment by Callan003** [comment]
I am facing the same issue :(
Did you find any solution?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.

(this is a canned response)
