### ISSUE TITLE
Update Mat-table row without refreshing  page or component

### ISSUE THREAD

**Issue by komalgmore** [angular/components#19509]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.  when  timers value 00:00:00 want to change status from open to closed.  without refreshing page.
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
Please fill out the template so that we can help you resolve the bug you are reporting
