### ISSUE TITLE
bug(mat-chip-list): ReferenceError: Cannot access 'MatChipRemove' before initialization

### ISSUE THREAD

**Issue by Sky4CE** [angular/components#19511]
#### Reproduction

Steps to reproduce:
1.  Create new angular 10 rc app
2. Add angular material 10 rc
3.  
```
import { MatChipsModule } from '@angular/material/chips';
@NgModule({
	imports: [
		MatChipsModule
```
 
 
#### Expected Behavior

MatChips should work

#### Actual Behavior

What behavior did you actually see?
![image](https://user-images.githubusercontent.com/9821633/83522746-c654c180-a4e9-11ea-84cc-c6e6231e3805.png)

#### Environment

- Angular: 10.0.0-rc.0 - 10.0.0-rc.2
- CDK/Material: 10.0.0-next.0 - 10.0.0-next.2
- Browser(s): Chrome 83
- Operating System (e.g. Windows, macOS, Ubuntu): Win10

**Comment by devversion** [comment]
Hello! This should have been fixed by in our latest RC of Angular CDK/Material. Can you please update? Looks like you're still on `next.2`. Please keep us updated! Thanks
