### ISSUE TITLE
ngcc failed to run on @angular/material@9.2.1

### ISSUE THREAD

**Issue by eng-dibo** [angular/components#19513]
I just created a new Angular project with `Ivy` enabled using stackblitz and installed `@angular/material@9.2.1`.
it is the only installed package (and it's peer dependency @angular/cdk) .

but I got an error `ngcc failed to run on @angular/material@9.2.1`

https://stackblitz.com/edit/angularmaterial-262020

error:
```
Error in ~/src/main.ts
ngcc failed to run on @angular/material@9.2.1.
```

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* **Any relevant details about your build environment**

(this is a canned response)

**Comment by eng-dibo** [comment]
I already included a StackBlitz reproduction. @jelbourn 
and here it is again 
https://stackblitz.com/edit/angularmaterial-262020

**Comment by jelbourn** [comment]
I misunderstood that the error is ocurring _in_ StackBlitz

**Comment by devversion** [comment]
@eng-dibo Could you please clarify what I need to do the reproduce this in StackBlitz? When I open the shared StackBlitz, the app just compiles fine and the toolbar renders for me.

**Comment by andrewseguin** [comment]
Same here- seems okay to me. Wheres the error?

**Comment by davide1995** [comment]
Set ("enableIvy": false) under angularCompilerOptions in tsconfig.json to solve the issue

**Comment by devversion** [comment]
Closing this issue as there is no sufficient information to reproduce this.
