### ISSUE TITLE
help(COMPONENT): TITLE Fix the first item in draggable list, so that it's position is never changed.

### ISSUE THREAD

**Issue by arunguptacatalystone** [angular/components#19521]
Description :

There's a scenario that I have a list which needs to be rendered in CDK Drag Drop.
What i want is that the first item is non draggable & it's position should never change. 
Currently, non draggable items are also moved if we drag another item around it.

Example : 
**Header**
**Item1**
**Item2**

So Item1 & Item2 should can never be dropped on no. 1 position. 

The solution i have right now is : Keep the First Item out of the loop & draggable list. But that doesn't seem legit.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/15712.

**Comment by arunguptacatalystone** [comment]
Well it's strange that the you said my issue is duplicate of the of #15712 issue & on that issue you mentioned that one is duplicate of mine.
So when will you provide the solution.
That's very unprofessional.🤨

**Comment by crisbeto** [comment]
I haven't commented anything on #15712 saying that it's a duplicate of this one.

**Comment by arunguptacatalystone** [comment]
> I haven't commented anything on #15712 saying that it's a duplicate of this one.

Ohh sorry i misread that last statement.
