### ISSUE TITLE
bug(input): matInput overwrites aria-described by

### ISSUE THREAD

**Issue by josephperrott** [angular/components#19528]
Copied from internal bug report:

According to https://material.angular.io/components/input/overview#accessibility:

> Any mat-error and mat-hint are automatically added to the input's aria-describedby list,...

but it seems they are not added but replace the pre-existing aria-describedby, see [here](https://github.com/angular/components/blob/8008218223b621d9bedb857c56364eceb85cd89e/src/material/input/input.ts#L84)

We use the aria-describedby to announce keyboard shortcuts for sending the form, and that breaks if matInput overwrites this.

Would it be possible to store the previous aria-describedby attribute and maintain it whenever setting this? That seems more inline with the docs and allows e.g. our use case.

cc: @rehmsen

**Comment by devversion** [comment]
That's an interesting bug. I agree that this behavior is confusing. We could get around it by merging it with the static `aria-describedby` attribute value that we inject in the `MatInput` `constructor`.

**Comment by rehmsen** [comment]
Thanks for filing it here.

Another suggestion that was proposed internally is for the error handling to use `aria-errormessage` instead of `aria-describedby`. Example:

```
<label>
  Comment
  <input matInput type="text" value="???" aria-errormessage="error">
</label>
<p id="error">
Please enter a valid comment
</p>
```

Would have to check how well this is supported by screenreaders though, and we might still not want to clobber the value passed by the component user.
