### ISSUE TITLE
Add docs for cdk/coercion

### ISSUE THREAD

**Issue by mateusrcm** [angular/components#19530]
Just a question and a suggestion, why such things as cdk/coercion doen't have documentation on your website, and why don't u guys implemented it yet?

**Comment by jelbourn** [comment]
We originally wrote docs for the subpackages that we considered most useful. At that time, cdk/coercion only had two functions in it (`coerceBooleanProperty `and `coerceNumberProperty`). It's grown a bit since then and probably does warrant it's own docs now.

**Comment by umairhm** [comment]
Since this documentation was missing, I thought to write some reference docs around this with examples. You can find it here:
https://indepth.dev/angular-cdk-coercion/
