### ISSUE TITLE
mat-button docs show examples for mat-button-toggle

### ISSUE THREAD

**Issue by umutyerebakmaz** [angular/components#19533]
#### Documentation Feedback

In the document of the material button component, in the example of using the toggle button. They showed that it was used only by importing matButtonModule. However, MatButtonToggle Module should also be specified in the API tab. It is required for the given toggle button sample to work.

https://material.angular.io/components/button/api

**Comment by jelbourn** [comment]
The issue here is that the button-toggle examples aren't supposed to be shown on the docs for `MatButton`

**Comment by walvekarnikhil** [comment]
@jelbourn , can I take this up?
Here is the analysis:
- Examples are matched using the prefix specified in [documentation-items.ts ](https://github.com/angular/material.angular.io/blob/master/src/app/shared/documentation-items/documentation-items.ts)
- button & button-toggle both start with '**button-**' prefix, so examples are getting mixed. [Code Link](https://github.com/angular/material.angular.io/blob/master/src/app/shared/documentation-items/documentation-items.ts#L90)
- There is a way that can exclude certain examples using "exclude" property, we can add that for the button.

```
    {
      id: 'button',
      name: 'Button',
      summary: 'An interactive button with a range of presentation options.',
      exampleSpecs: {
        prefix: 'button-',
        exclude: ['button-toggle-appearance', 'button-toggle-exclusive', 'button-toggle-overview']
      },
      additionalApiDocs: [{name: 'Testing', path: 'material-button-testing.html'}],
    },
```

Please let me know if I am missing anything or another way to fix this.

**Comment by jelbourn** [comment]
@walvekarnikhil sounds good, go for it!

**Comment by walvekarnikhil** [comment]
PR is created. 
Is there any other way to link PR for material.angular.io with this issue? so that the issue closes after PR is merged.

**Comment by walvekarnikhil** [comment]
@jelbourn , do I need to tag someone for the material.angular.io PR?

**Comment by jelbourn** [comment]
I just assigned a couple of reviewers there

**Comment by walvekarnikhil** [comment]
> I just assigned a couple of reviewers there

Thanks @jelbourn

**Comment by crisbeto** [comment]
Looks like the related PR was merged in. Closing.
