### ISSUE TITLE
ng test dispatchFakeEvents error

### ISSUE THREAD

**Issue by adi86** [angular/components#19537]
#### Bug, feature request, or proposal:
While running ng test and dispatchFakeEvents problem

#### What is the expected behavior?
Ng test runs

#### What is the current behavior?
`ERROR in ./src/app/shared/components/chips-with-input/chips-with-input.component.spec.ts
Module not found: Error: Can't resolve '@angular/cdk/testing/testbed/fake-events' in 'C:\projects\ITM.SD.CT.RTB.Angular\src\app\shared\components\chips-with-input'
resolve '@angular/cdk/testing/testbed/fake-events' in 'C:\projects\ITM.SD.CT.RTB.Angular\src\app\shared\components\chips-with-input'
  Parsed request is a module
  using description file: C:\projects\ITM.SD.CT.RTB.Angular\package.json (relative path: ./src/app/shared/components/chips-with-input)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/projects/ITM.SD.CT.RTB.Angular/src
        using description file: C:\projects\ITM.SD.CT.RTB.Angular\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\projects\ITM.SD.CT.RTB.Angular\package.json (relative path: ./src/@angular/cdk/testing/testbed/fake-events)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events.js doesn't exist
            as directory
              C:\projects\ITM.SD.CT.RTB.Angular\src\@angular\cdk\testing\testbed\fake-events doesn't exist
      C:\projects\ITM.SD.CT.RTB.Angular\src\app\shared\components\chips-with-input\node_modules doesn't exist or is not a directory
      C:\projects\ITM.SD.CT.RTB.Angular\src\app\shared\components\node_modules doesn't exist or is not a directory
      C:\projects\ITM.SD.CT.RTB.Angular\src\app\shared\node_modules doesn't exist or is not a directory
      C:\projects\ITM.SD.CT.RTB.Angular\src\app\node_modules doesn't exist or is not a directory
      C:\projects\ITM.SD.CT.RTB.Angular\src\node_modules doesn't exist or is not a directory
      C:\projects\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\projects\ITM.SD.CT.RTB.Angular\node_modules
        using description file: C:\projects\ITM.SD.CT.RTB.Angular\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\package.json (relative path: ./fake-events)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events is not a file
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events.js doesn't exist
            as directory
              existing directory
                using path: C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index
                  using description file: C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\package.json (relative path: ./fake-events/index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index doesn't exist
                    .ts
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index.ts doesn't exist
                    .tsx
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index.tsx doesn't exist
                    .mjs
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index.mjs doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\projects\ITM.SD.CT.RTB.Angular\node_modules\@angular\cdk\testing\testbed\fake-events\index.js doesn't exist`

angular.json
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "RTB": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/RTB",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles/styles.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/styles"
              ]
            },
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            },
            "ci": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.ci.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "RTB:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "RTB:build:production"
            },
            "ci": {
              "browserTarget": "RTB:build:ci"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "RTB:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles/styles.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/styles"
              ]
            },
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "RTB"
}
`
package.json: 
`{
  "name": "rtb",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "prebuild.prod": "node git.version.js",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build",
    "test": "ng test",
    "test:ci": "ng test --reporters junit --watch false --browsers=ChromeHeadlessCI",
    "lint": "ng lint",
    "cypress:open": "cypress open",
    "start:ci": "ng serve --configuration ci --watch=false",
    "start:ci-watch": "ng serve --configuration ci"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.9",
    "@angular/cdk": "^9.1.9",
    "@angular/common": "^9.1.9",
    "@angular/compiler": "^9.1.9",
    "@angular/core": "^9.1.9",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "^9.1.9",
    "@angular/material": "^9.1.9",
    "@angular/platform-browser": "^9.1.9",
    "@angular/platform-browser-dynamic": "^9.1.9",
    "@angular/router": "^9.1.9",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "d3": "^5.16.0",
    "d3-tip": "^0.9.1",
    "date-fns": "^2.9.0",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "karma-junit-reporter": "^2.0.1",
    "keycloak-angular": "^7.1.0",
    "keycloak-js": "^10.0.2",
    "lodash": "^4.17.15",
    "ng5-slider": "^1.2.4",
    "ngx-permissions": "^7.0.3",
    "rxjs": "~6.5.5",
    "saturn-datepicker": "^8.0.1",
    "smoothscroll-polyfill": "^0.4.4",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.7",
    "@angular/cli": "^9.1.7",
    "@angular/compiler-cli": "^9.1.9",
    "@angular/language-service": "^9.1.9",
    "@cypress/webpack-preprocessor": "^5.4.1",
    "@types/d3": "^5.7.2",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/lodash": "^4.14.155",
    "@types/node": "^14.0.10",
    "codelyzer": "^5.1.2",
    "cypress": "^4.7.0",
    "cypress-file-upload": "^4.0.7",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "^5.0.9",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^3.3.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "ngx-strongly-typed-forms": "^8.0.1",
    "ts-loader": "^7.0.5",
    "ts-node": "^8.10.2",
    "tslint": "^6.1.2",
    "typescript": "~3.8.3"
  }
}
`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Happened after migration from version 8 to 9. 

#### Is there anything else we should know?
Cypress directory is outside src

**Comment by devversion** [comment]
Hello! I'm trying to figure out what is going on. Is your app importing directly from `@angular/cdk/testing/tesbed/fake-events` somewhere? or better, do you use any test harnesses from Angular Material?

The Stacktrace itself is unfortunately not enough information. It's unclear whether this happened after just running `ng update` or when you started using any of the new features in v9 (such as harnesses).

**Comment by adi86** [comment]
Hi, yes we import directly from fake-events:
`import { dispatchFakeEvent } from '@angular/cdk/testing/testbed/fake-events';`
We didn't change anything in code, only ng update before in version 8 it was working correctly.  We don't use hanesses.

**Comment by devversion** [comment]
Hello! I'm slightly confused about this issue because in version 8 we didn't even had the fake-event utils in this location/or even public. https://unpkg.com/browse/@angular/cdk@8.2.3/testing/

Could you potentially provide more context on how this worked before? I can only state that in the current state, these utils are not public and never were public API 😄

**Comment by devversion** [comment]
I'm closing this as I don't think there is an issue from our side and this hasn't come up anywhere else. Please note that this does not mean that we'll not continue looking when you provide more information! thanks!
