### ISSUE TITLE
large packages with ivy and being included in the main. *. js

### ISSUE THREAD

**Issue by GlauberF** [angular/components#19540]
#### Expected Behavior

After updating to version 9 of Angular and activating the Ivy compilation, my main file is very large and analyzing through source-map-explorer, I see that the main part occupied in the main is because of the material.
Another point is it correct for the material packages to appear in the main?

link to download the source-map-explorer that I generated: https://we.tl/t-i2QOam9LkD

#### Environment

<pre><code>
Angular CLI: 9.1.7
Node: 12.16.3
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.7
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                9.1.7
@schematics/update                 0.901.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by devversion** [comment]
Hello! Thanks for this issue. That seems to be be actually tracked as part of a larger CLI issue: https://github.com/angular/angular-cli/issues/16866.
