### ISSUE TITLE
bug(workspace): We need to deduplicate browsers in our WORKSPACE

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#19543]
### Context
The bug is being knowingly introduced here in PR #19320. We are loading another version of chromium in the repository from `dev-infra`. We plan on using the browsers loaded from `dev-infra` as that one has RBE improvements. This is an issue to make sure we remember to deduplicate the browsers once that PR is merged in.

Paraphrasing @devversion, this change has the potential of speeding up local dev. Right now browser archives are extracted frequently due to bad caching.

**Comment by devversion** [comment]
I created https://angular-team.atlassian.net/browse/DEV-115 for the tracking of the bad caching issue. Something is not reliably configured for extracting the browser archives.
