### ISSUE TITLE
DatePicker: JAWS announces abbreviated weekend day names

### ISSUE THREAD

**Issue by ankushgoyal27** [angular/components#19541]
#### Reproduction

Steps to reproduce:
1.  Run the JAWS
2.  Open the firefox browser
3. Click on the datepicker toggle button
4. press tab until reaches the weekday
 
 
#### Expected Behavior

It should read long weekdays name as Sunday, Monday, Tuesday, Wednesday, Thursday Friday, Saturday.

#### Actual Behavior

It is reading weekdays as Sun, Mon, Tuesday, wed, Thursday Friday, Sat

#### Environment

- Angular: 9.0.1
- CDK/Material: 9.0.2
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
FWIW we won't be able to test JAWS again until we get back into the office

**Comment by crisbeto** [comment]
I think that this is resolved in master. Each week day header has an `aria-label` with the long day name now.
