### ISSUE TITLE
bug(dialog): Dialog button shaded gray on open, and source button after closing

### ISSUE THREAD

**Issue by michaelfaith** [angular/components#19542]
I didn't see anything in the release notes about this, so i wasn't sure if it was intentional, but after updating to the latest, i'm seeing a different behavior on the dialog buttons.  When a dialog is launched it's now applying a cdk-program-focused class to the first button in the dialog, and then applying the same to the source button that launched the dialog after closing.  If this isn't a bug, is there a way to turn that off? It's causing issues with our styles.

#### Reproduction

https://stackblitz.com/angular/dlgapjpkkyj?file=src%2Fapp%2Fdialog-overview-example.ts

Steps to reproduce:
1. Click the Pick One button 

#### Environment

- Angular: 9.1.9
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 64x

**Comment by crisbeto** [comment]
This is an accessibility feature that is working as expected. You can turn it off by setting `autoFocus: false` and `restoreFocus: false` in the config.

**Comment by michaelfaith** [comment]
@crisbeto thanks for the quick reply and pointing me towards the appropriate properties.
