### ISSUE TITLE
bug(drag-drop): cdk-overlay-pane is not scrollable

### ISSUE THREAD

**Issue by MursalovAltun** [angular/components#19555]
To reproduce this issue we need to create a material dialog and make it draggable using cdkDrag directive and cdkDragRootElement=".cdk-overlay-pane" applied to the dialog's header.
Therefore in mobile devices we are not able to scroll dialog's content

StackBlitz with the issue - https://stackblitz.com/edit/angular-ivy-nyrwmp

This issue only appears in 9.0.0+ versions.
 
 
#### Expected Behavior

Just drag dialog clicking header

#### Actual Behavior

Now we are dragging dialog by touching anywhere in the dialog, even by inputs touching

#### Environment

- Angular: v9+
- CDK/Material: v9+ 
- Browser(s): Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Android 7.0

**Comment by crisbeto** [comment]
It seems like 2 different issues are being described here.

1. Based on the issue title, `cdk-overlay-pane` isn't meant to be scrollable so if you need it to be, you have to override the CSS yourself.
2. Based on the issue description, it seems like you've hit a legitimate bug where `cdkDragHandle` can't be set on a `cdkDrag` element.
