### ISSUE TITLE
snack-bar: does not disappear when clicking on it multiple times

### ISSUE THREAD

**Issue by chandanjawale** [angular/components#19554]
**Snack bar should be disappear in sometime after clicking  PIZZA PARTY button**:
 -  `If we clicks continuously and multiple times on PIZZA PARTY button*`
 -  ` The snack bar is not getting dis-appeared in completed interval time`

**Steps to reproduce the issue: *
 
 -  `Click multiple times on PIZZA PARTY button`
 -  `See the result`
 -   `Change the routes  and see the results`
 
**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: Chromium *`
  -  `OS:  Ubuntu 16.04 LTS*`

----

**Comment by Splaktar** [comment]
I cannot reproduce this in `9.2.4` on [the examples](https://material.angular.io/components/snack-bar/examples).
