### ISSUE TITLE
MatFormField: Changing appearance is not reflected in the view.

### ISSUE THREAD

**Issue by directcuteo** [angular/components#19556]
**Reproduction**
Steps to reproduce:

1. Define a mat-form-field:
My own: 
```
<mat-form-field appearance="{{data.appearance}}">
        <mat-label>Some label</mat-label>
        <input #inputElement matInput type="text"/>
 </mat-form-field>
```
2. Change the appearance:
`update() { this.data.appearance = 'outline'; //was 'standard' before  }` 
or
    `@ViewChild(MatFormField) matFormField: MatFormField;`
``update() {
this.matFormField.appearance = 'outline';  //was 'standard' before
}``

**Expected Behavior**
It should change the appearance of the `<mat-form-field>` .

**Actual Behavior**
There is no visual effect in either of the 2 approaches.
|
|
|
 `ChangeDetectionStrategy` is set to default for my component. I am using Angular 9 and "@angular/material": "^8.1.3"

**Comment by crisbeto** [comment]
It sounds like you aren't triggering change detection when you change the appearance. Here's an example that shows it working: https://stackblitz.com/edit/angular-hgseag
