### ISSUE TITLE
bug(CDK): The application is unable to start using cdk/material version 10.0.0-rc.1

### ISSUE THREAD

**Issue by ahimik** [angular/components#19575]
#### Reproduction

Steps to reproduce:
1. Update cdk/material v. 9.2.4 to v.10.0.0-rc.1
  
#### Expected Behavior

Application is bootstrapped successfully.

#### Actual Behavior

White screen. Application bootstrap fails with the following error:

```
bidi.js:76 Uncaught TypeError: Class constructor Directionality cannot be invoked without 'new'
    at Module../node_modules/@angular/cdk/__ivy_ngcc__/fesm2015/bidi.js (bidi.js:76)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex.js (flex.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/environments/environment.ts (environment.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)
```

#### Temporal workaround

Turning off ivy in tsconfig.json:
```
    "angularCompilerOptions": {
        "enableIvy": false
    }
```

#### Environment

- Angular: 9.1.9
- CDK/Material: 10.0.0-rc.1
- Browser(s): Chrome v83.0.4103.97
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 64bit

**Comment by Delagen** [comment]
```
 Can't resolve '@angular/cdk/bidi/dir-document-token' in '...\@angular\cdk\__ivy_ngcc__\esm2015\bidi'
```

**Comment by jelbourn** [comment]
@crisbeto could you take a look at this?

**Comment by jelbourn** [comment]
I tried out a project with rc1 and everyone was working as expected. Does anyone have additional information for this?

**Comment by Delagen** [comment]
Are you using enableIvy flag? Rc.1 ngcc compilation produces import paths like @angular/cdk/bidi/dir-document which does not resolvable with ivy compiler. Rc0 ngcc processing does not produce this behaviour

**Comment by jelbourn** [comment]
I tried it with a fresh CLI project which has ivy enabled by default. Do you have more information about what's in the application that triggers this? I added a `mat-slider`, which transitively imports `BidiModule` and everything worked fine.

**Comment by Delagen** [comment]
Seems working with angular 10rc6 & cdk 10rc2

**Comment by crisbeto** [comment]
Closing since it looks like the issue was resolved upstream.
