### ISSUE TITLE
MatStepper `tabpanel` element should not have `tabindex="0"`

### ISSUE THREAD

**Issue by Wloclawek** [angular/components#19574]
#### Reproduction

Steps to reproduce:
1. Open: https://material.angular.io/components/stepper/api
2. Use tab and go to first input.
 
 
#### Expected Behavior

Focus should always be visible (users using only the keyboard). 

A11Y / WCAG / accessibility

#### Actual Behavior

Between the first step (tab) and the first field, the focus disappears.

#### Environment

- Angular: 8.
- Angular Material: 9.2.4
- Browser(s): Firefox 77, Chrome 83
- Operating System: Windows 10.

**Comment by jelbourn** [comment]
Looked at this, the `role="tabpanel"` here has `tabindex="0"` which shouldn't be the case.

**Comment by crisbeto** [comment]
We've got a PR for this already https://github.com/angular/components/pull/16809. Also closing as a duplicate of https://github.com/angular/components/issues/16692.
