### ISSUE TITLE
bug(Cdk virtual scroll): Cdk virtual scroll not working properly with compareWith

### ISSUE THREAD

**Issue by ilapavuluri** [angular/components#19584]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. I found a serious problem with *cdkVirtualFor, this improved the performance but breaking my functionality, in my selection-list, I will select options by checking the check-box like in the below image, if I select a option and scroll down and scroll up again I am losing the selection.

 
![image](https://user-images.githubusercontent.com/28562196/84236235-f832dd00-ab14-11ea-8011-818d7d974e91.png)

![image](https://user-images.githubusercontent.com/28562196/84236257-fff28180-ab14-11ea-8caf-234f9c057581.png)

<cdk-virtual-scroll-viewport itemSize="40" class="virtual-scroll-viewport">
          <mat-selection-list color="accent" #options [(ngModel)]="selectOptions" [compareWith]="compareFunction"
          (selectionChange)="onOptionSel($event)">
          <mat-list-option *cdkVirtualFor="let cio of ciOptions | filter:searchItem " checkboxPosition="before" [value]="cio.id" aria-label="cio">
            {{cio.label}}
          </mat-list-option>
        </mat-selection-list>
      </cdk-virtual-scroll-viewport>

compareFunction = (option1:string, option2:string)=> option1===option2;

 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
Unfortunately the cdk's virtual scrolling isn't yet integrated with existing Angular Material components; you can follow #10122

**Comment by ilapavuluri** [comment]
Hi Jelbourn,

Thanks for the response, I have more than 1000 records, without virtual scroll it is very slow, is there any alternate solution?

Appreciate your help.

Thanks
Ashok.

**Comment by Splaktar** [comment]
@ilapavuluri sorry for the delay in taking a look at this.

You will probably want to either find 
1. a way to not include all of your records in the at one time list (implement some kind of pagination) without `*cdkVirtualFor` or 
1. use `*cdkVirtualFor` along with a custom component (i.e. remove your use of `MatSelectionList`) and custom class for handling your UI state

The first option is likely the easiest (and `MatTable` with `MatPaginator` might be helpful), but your API will have to support paging.

**Comment by ilapavuluri** [comment]
Thank you so much Michael for your response.

Thanks
Ashok.
