### ISSUE TITLE
help(mat-dialog): Closing behaviour of Material dialog

### ISSUE THREAD

**Issue by poddarkhushbu07** [angular/components#19586]
I want to have following behaviour on closing dialog

1. Dialog can be closed by _ESC_ or any event triggered from inside the dialog 
2. Prevent clicking outside the dialog, to close dialog

To achieve 1st, I need to set **disableClose** property to false. And to achieve 2nd behaviour, I had to set **disableClose** property to true.

How can I achieve this?

Thanks.

**Comment by jelbourn** [comment]
You can use `disableClose` along with `OverlayKeyboardDispatcher` to manually close on escape.
