### ISSUE TITLE
bug(MatFormField): MatSuffix does not align with input text with appearance "outline"

### ISSUE THREAD

**Issue by jermowery** [angular/components#19580]
#### Bug, feature request, or proposal:

When using a MAtFormField with appearance "outline" and a matSuffix the suffix is not aligned with the input text

#### What is the expected behavior?

The suffix should align with the input text

#### What is the current behavior?

The text is not aligned

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-inhpxm-besr6m

#### What is the use-case or motivation for changing an existing behavior?

Fix alignment

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All?

**Comment by jelbourn** [comment]
cc @devversion @mmalerba

**Comment by mmalerba** [comment]
updated #12803 to reflect the priority of this issue, will post an update there
