### ISSUE TITLE
feat(mat-radio-group): Support for required directive in reactive forms

### ISSUE THREAD

**Issue by yohny** [angular/components#19606]
#### Feature Description

Add support for required directive on `mat-radio-group` even when used with reactive forms

#### Use Case

The required directive https://angular.io/api/forms/RequiredValidator works on `<input>` even when using reactive forms (aka. you dont have to add Validators.required to your input's FormControl, you can add `required` atribute to the input in html template instead),
It would be nice for this to be also possible with `mat-radio-group`, so in reactive forms you dont have to do

```
myForm: new FormGroup({
  myRadio: new FormControl(null, Validators.required) // this works
})
```
but you could add `required` attribute to `<mat-radio-group>` in html template.

You can to this in template-driven forms, but for it to work you have to also add [ngModel] to the `mat-radio-group` which you dont want to do in reactive forms.

It seems like other people expect this to work too https://stackoverflow.com/questions/51633895/make-mat-radio-button-a-required-field-in-a-form

**Comment by crisbeto** [comment]
From my testing it looks like the control already gets marked as invalid when the `required` input is set and a value hasn't been selected. Here's what the test looks like:

```

it('should fail', () => {
  const control = fixture.componentInstance.formControl;
  fixture.detectChanges();

  expect(control.getError('required')).toBeTruthy();

  fixture.nativeElement.querySelector('.mat-radio-input').click();
  fixture.detectChanges();

  expect(control.getError('required')).toBeFalsy();
});
```

And this is the test component:

```

@Component({
  template: `
    <mat-radio-group [formControl]="formControl" required>
      <mat-radio-button value="1">One</mat-radio-button>
    </mat-radio-group>
  `
})
class RadioGroupWithFormControl {
  formControl = new FormControl();
}
```

@yohny can you post an example that doesn't work?

**Comment by yohny** [comment]
you are right, all works as expected :smile: 

my problem was that I had radio-group inside *ngIf
```html
<form [formGroup]="myForm" (ngSubmit)="submit()">
  <ng-container *ngIf="options?.length else noOptions">
    Pick one option:
    <mat-radio-group formControlName="myRadio" required>
      <mat-radio-button *ngFor="let o of options" [value]="o">{{o.name}}</mat-radio-button>
    </mat-radio-group>
  </ng-container>
  <ng-template #noOptions>No options available</ng-template>
  <button type="submit" [disabled]="!myForm.valid">Submit</button>
</form>

```
When there were options available form wasn't valid (allowed to submit) until some option was selected. However when there were no options form was valid even though no option was selected.
If I moved required validation from template attribute to FormControl constructor, all started working as I expected (aka. form was not valid until some option was selected and in case of no options form remained invalid). This made me think that there is an issue with required attribute, even though in reality (as usual) the issue was between the chair and the keyboard :smiley:
The form was valid if there were no options because in such case the whole radio-group (including required attribute) wasn't in the DOM, so Angular didn't know that given form control is required, therefore its containing form was valid. However when required validation was in FormControl's constructor angular knew that given control is required even without options and thus form stayed invalid.
