### ISSUE TITLE
feat(MatMenu): menuOpened and menuClosed provide some event details

### ISSUE THREAD

**Issue by drstonebraker** [angular/components#19605]
#### Feature Description

It would be helpful if the events emitted by menuOpened and menuClosed in the MatMenu api would provide some more details about the event that caused the open or close.

#### Use Case

I am tracking various user behavior and prefer to make distinctions between mouse events triggering various features and keyboard events triggering various features. 

#### Extended idea

If this is done by identifying some kind of event type, it would be useful if, when I call openMenu, toggleMenu, or closeMenu, I could optionally provide a custom type, so that I can distinguish between different programmatic calls to open or close the menu.

**Comment by jelbourn** [comment]
I don't see us adding a feature like this since the use-case would be pretty niche. With all features, we have to weight the size/complicity of the added code against how wide of an audience would benefit from those features.
