### ISSUE TITLE
Angular mat-stepper component, styling horizontal-line

### ISSUE THREAD

**Issue by ZenEND** [angular/components#19623]
### Bug, feature request, or proposal:

Add some class like "before-selected" to the step that is before selected step. The main task is to make theme for the angular material components, and current issue is just that I can not get the step before selected, also horizontal line before selected step   

### Expected behavior
![image](https://user-images.githubusercontent.com/45174774/84498681-cb6bfa80-acb9-11ea-9777-c4c2046db4e9.png)

### Current behavior
![image](https://user-images.githubusercontent.com/45174774/84498552-8942b900-acb9-11ea-896f-e5cf9ca3b5af.png)

### Current packages versions

   - "@angular/animations": "~9.0.2",
   -  "@angular/cdk": "^9.2.1",
   -  "@angular/common": "~9.0.2",
   - "@angular/compiler": "~9.0.2",
   - "@angular/core": "~9.0.2",
   - "@angular/forms": "~9.0.2",
   - "@angular/material": "^9.2.1",
   - "@angular/cli": "~9.0.3",
   - "typescript": "~3.7.5"

**Comment by devversion** [comment]
Hello! This looks like a question for StackOverflow if I understand your issue correctly. We do not provide any official way to style the horizontal line.

Obviously it's possible to do it by targeting `.mat-stepper-horizontal-line`, but there is no good way to select the horizontal line before a selected step header. You most likely would need to implement it together with some JS logic as there is no good way to select a horizontal line preceding a step-header with `aria-selected=true`.

**Comment by devversion** [comment]
I think adding a class to the step header before the selected one is rather specific to your use-case and that seems out of scope for the Angular Material stepper. You might be able to add such a class on your own.
