### ISSUE TITLE
bug(MatDialog+MatExpansionPanel): MatExpansionPanel causes MatDialog to scroll to expansion panel

### ISSUE THREAD

**Issue by jkyoutsey** [angular/components#19630]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-uk31wr
 
#### Expected Behavior

Putting an expansion panel on a dialog should not cause the dialog to scroll to the expansion panel when the dialog is opened.

#### Actual Behavior

Putting an expansion panel on a dialog causes the dialog to scroll to the expansion panel when the dialog is opened.

![image](https://user-images.githubusercontent.com/3846466/84541694-7cc05f80-acbd-11ea-9d13-d468d80b0c98.png)

#### Environment

- Angular: 9.1.2
- CDK/Material: 9.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OSX High Sierra

**Comment by jelbourn** [comment]
Confirmed that this is happening and is also pretty weird

**Comment by crisbeto** [comment]
I'd say that this is expected due to the focus trap focusing the first focusable element. If you want focus to land on a different element, you can set the `cdkFocusInitial` attribute on it. You can also disable automatic focus through the `autoFocus` option and manage it yourself.

**Comment by jkyoutsey** [comment]
> I'd say that this is expected due to the focus trap focusing the first focusable element. If you want focus to land on a different element, you can set the `cdkFocusInitial` attribute on it. You can also disable automatic focus through the `autoFocus` option and manage it yourself.

@crisbeto Can you elaborate on what the fix would look like on the `mat-expansion-panel` element? I can't find any documentation on the `autoFocus` attribute that you mention. I don't have another interactive element that takes focus on this dialog, so I need a way to override the focus trap.

**Comment by crisbeto** [comment]
`autoFocus` is an option in the `MatDialog.open` call.

**Comment by jkyoutsey** [comment]
I'd call that fixed! Thank you @crisbeto

**Comment by jelbourn** [comment]
Yeah, I totally should have noticed that.
