### ISSUE TITLE
MatTabNavBar: space key does not activate the selected tab

### ISSUE THREAD

**Issue by nirkai** [angular/components#19642]
###### Without router-outlet directive
The `mat-tab-nav-bar` directive not activate tabs with <kbd>Enter</kbd>&<kbd>Space</kbd> by default (like in 'real' tabs).

[Official example](https://stackblitz.com/angular/lnjdedkpgdg) (without router-outlet).

Steps to reproduce:
1. Focus on unselected tab (with arrow keys) and press <kbd>Enter</kbd> or <kbd>Space</kbd>
2. The selected tab not activated and the route page isn't display.

###### With router-outlet directive
The `mat-tab-nav-bar` directive with routerLink (like shown [here](https://material.angular.io/components/tabs/overview#tabs-and-navigation)) activate selected tabs with <kbd>Enter</kbd> but not with <kbd>Space</kbd>.

[Custom example](https://stackblitz.com/edit/angular-rul4hb) (with router-outlet).

Steps to reproduce:
1. Focus on unselected tab and press <kbd>Enter</kbd>.
2. The selected tab activated.
3.  Focus on unselected tab and press <kbd>Space</kbd>.
4. The selected tab not activated and the route page isn't display.
 
#### Expected Behavior

Select tabs with <kbd>Enter</kbd> or <kbd>Space</kbd> keys will activate the selected tab.

There is also a function call that should handle it. here is the [call](https://github.com/angular/components/blob/b225b875714ec4335e509b122432b29bb033708b/src/material/tabs/tab-nav-bar/tab-nav-bar.html#L12) and here is the [function](https://github.com/angular/components/blob/b225b875714ec4335e509b122432b29bb033708b/src/material/tabs/paginated-tab-header.ts#L269).

#### Actual Behavior

When tab selected by <kbd>Space</kbd> the route not activated.

#### Environment

- Angular: 9
- CDK/Material: 9.2.4

**Comment by crisbeto** [comment]
I believe that this intentional for the tab nav bar. It is set up to work with links and as such, it gives up the responsibility for highlighting the current tab to the link via the `active` input.

Technically it'll be easy to make it work, but I can see it being confusing for both space and enter key presses, because links don't do anything on space.

**Comment by nirkai** [comment]
Thanks for your replay @crisbeto 

Technically you are right of course, the element is indeed `a` tag element.
But, conceptually, the `mat-tab-nav-bar` and the `mat-tab-link` is more like Tabs (design and behavior). 
The behavior of the `router-outlet` is peculiar. It's route link, but in app routing.

What i'm not understand is what prevent the[ _keydown function](https://github.com/angular/components/blob/b225b875714ec4335e509b122432b29bb033708b/src/material/tabs/paginated-tab-header.ts#L269) to exec, like I mentioned in the question.

Without routerLinkActive directive even the <kbd>Enter</kbd> key is not fire the event. But the <kbd>End</kbd> and <kbd>Home</kbd> work as expected. 

BTW, same question for the <kbd>Tab</kbd> press.  
If we consider it more like tab, we can make the <kbd>Tab</kbd> behavior to be like in real tab. Just bind the `tabindex` to the active property. 
But maybe this will force to change all the `aria` attributes to be like in other tabs.

**Comment by Splaktar** [comment]
AngularJS Material's `md-nav-bar` has pretty good keyboard accessibility which is described [here](https://material.angularjs.org/latest/api/directive/mdNavBar#keyboard-navigation). We use the [Tabs with Manual Activation Example from WAI-ARIA](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html). A related example is the [Navigation Menubar Example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html#).

**Comment by nirkai** [comment]
Please pay attention that the current behavior of the <kbd>Tab</kbd> with the <kbd> Arrow</kbd> keys is very confused.  [Here ](https://stackoverflow.com/q/61849612/8994917)is more details about it.

The Arrow interaction is usually reserved for lists.

**Comment by zarend** [comment]
Hello, I believe this was fixed in v15. I can select tabs with both the space and enter keys.
