### ISSUE TITLE
bug(TABS): Ink bar could use transformX instead of left to improve performance.

### ISSUE THREAD

**Issue by tomasdev** [angular/components#19647]
#### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/angular/lnjdedkpgdg (basic example from [Docs](https://material.angular.io/components/tabs/examples))
2. Open Chrome Dev Tools
3. Go to Performance tab
4. Select 6x CPU Slowdown
5. Observe the line animation as you click through the elements.
 
#### Expected Behavior

Performance is optimal for each device. It should worsen somewhat linearly. This is particularly noticeable when using tabs to provide fixed navigation elements on a page (i.e., https://fonts.google.com/specimen/Roboto) that have their active element updated on scroll.

#### Actual Behavior

Performance becomes very poor very fast depending on device. I.e., simulated 6x CPU slowdown on a 2019 Macbook Air makes it very noticeable there are frames taking longer than 16ms to render the ink bar animation (meaning the ink bar appears to "jump" instead of animate)

#### Notes

From Paul Irish ca. 2012: "...left has very large time to paint each frame, which results in a choppier transition" (https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/)

Affected line: https://github.com/angular/components/blob/master/src/material/tabs/ink-bar.ts#L95

**Comment by crisbeto** [comment]
We did this for a while, but we ended up reverting it because it caused some issues when the page is zoomed in (see https://github.com/angular/components/pull/11661). It might be worth trying it again only for the ink bar position though, rather than both the width and position.

**Comment by jelbourn** [comment]
Closing since we attempted this before (and reverted it), and because the MDC-based version of the tabs will just being using MDC's style.

**Comment by tomasdev** [comment]
For those coming to this issue from Google. My workaround:
- Set in CSS: `left: 0 !important`
- Set in JS: `.mat-ink-bar` the `translateX` value

**Comment by crisbeto** [comment]
On top of what @jelbourn said, if you want to try out the new tabs implementation that uses a different approach for the ink bar, you can import the MatTabsModule from material-experimental/mdc-tabs, instead of material/tabs.
