### ISSUE TITLE
feat(google-maps): Allow to inject/create/link angular component into MapInfoWindow

### ISSUE THREAD

**Issue by ybarbaria** [angular/components#19655]
#### Feature Description
I am currently using the agm-snazzy-info-window component which allow to implement any kind of component as info window for a marker. I would love to find this kind of feature for the MapInfoWindow because currently the MapInfoWindow has a very limited usage. 

#### Use Case
I need to display some complex component with some interaction, event and change detection into the MapInfoWindow but currently we can't create any component into the MapInfoWindow.

**Comment by crisbeto** [comment]
From what I can tell, you should be able to put your component directly into the info window like this:

```
<map-info-window>
  <your-component></your-component>
</map-info-window>
```

Is this what you're looking for?
