### ISSUE TITLE
feat(material form field): Please remove the fixed width

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#19654]
https://stackoverflow.com/questions/62396489/getting-material-form-fields-to-fit-within-a-flex-box-container

Having the `180px` fixed with on the `mat-form-field-infix` makes it difficult to space the fields using flexbox.  

For example if we use 33%, but also have margins on the fields they will still wrap.  Ideally these should be able to space themselves out using the flexbox only.

**Comment by andreElrico** [comment]
For me its UNCLEAR what you want. What the desired layout looks like ???

[maybe?](https://stackblitz.com/edit/angular-material-fit-form-fields-tkwef2?file=src/app/app.component.html)

I dont think the `mat-form-field-infix` can change, this would break the world. Use css.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate/respond. It's not clear in this case what're you're actually trying to accomplish.
