### ISSUE TITLE
bug(cdkTrapFocus): cdkTrapFocusAutoCapture has no effect after 'init' step

### ISSUE THREAD

**Issue by MaKCbIMKo** [angular/components#19664]
#### Expected Behavior

I can have binding for `cdkTrapFocusAutoCapture` input.
And if I have input that is disabled at start and gets enabled later, in simple case I can pass `myInputControl.enables` to `cdkTrapFocusAutoCapture` input and it will get focus once it's enabled.

#### Actual Behavior

`cdkTrapFocusAutoCapture` input has effect only once when the focus trap initialized. And if later the value for this input has changed - it has no effect.

#### Environment

- Angular: 9.1.11
- CDK/Material: 9.2.4

**Comment by crisbeto** [comment]
Looks like the related PR got merged in, but I forgot to mark this issue as resolved.
