### ISSUE TITLE
bug(mat-checkbox): noop clickAction prevents keyboard click event

### ISSUE THREAD

**Issue by antoinebrault** [angular/components#19663]
#### Reproduction

noop clickAction prevents keyboard click event but doesn't prevent mouse events. If a click is done with the mouse, the handler is called.

https://stackblitz.com/edit/mat-checkbox-clickaction

Steps to reproduce:
1. press SPACE when focusing checkbox
 
#### Expected Behavior

Should call onClick() method (print 'test' in console)

#### Actual Behavior

click method is not called.

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This is working as expected. Setting the click to `noop` disables the _native_ checkbox behavior, but it doesn't change any listeners that you add in your application (in this case your click handler). The fact that pressing space on a checkbox triggers a click event is part of the native checkbox behavior that you're disabling with `'noop'`.

**Comment by antoinebrault** [comment]
the bug is that it doesn't trigger a click event.

**Comment by antoinebrault** [comment]
Then why is that click event still works on some events (click or touch) and not on SPACE? It's a weird behavior when you can focus the checkbox but events don't bubble up. 

What I expect when using noop is that the behavior of MatCheckbox is noop, not the click event.

As stated in the doc:
noop
Do not change the checked value or indeterminate value. Developers have the power to implement customized click actions.

I can't fully implement custom click event if keyboard events are disabled.

**Comment by jelbourn** [comment]
You would need to manually had a keyboard event listener. The fact that pressing space emits a "click" event is a special behavior of the underlying native `<input type="checkbox">`; other DOM elements don't emit click events when you press space on them. There's no way to `preventDefault` on the native checkbox toggling without _also_ preventing the space-key-emits-click behavior.

**Comment by antoinebrault** [comment]
**button**, **radio** also emit click event with space. 

I didn't even realize with default mat-checkbox the keyboard click event is still lost.

**Comment by antoinebrault** [comment]
Maybe there's a way to skip event.stopPropagation() for keyboard clicks, since it's there to prevent a double mouse click on label.

**Comment by amakhrov** [comment]
To me it also looks like a bug rather than a feature, since it effectively prevents using `noop`. (with `noop` my checkbox becomes less accessible)

From the comment in the component code I understand that the whole thing with stopPropagating is to prevent double click events.
Maybe a better approach would be to allow propagation of "click" event from the visually hidden input, but stop propagating the one originated from the wrapping label? Would such an approach also prevent double event while being better resembling the native checkbox behavior?

**Comment by antoinebrault** [comment]
@amakhrov "change" event would mean the value was updated, which it isn't. In this case, they use stopPropagation() to cancel the double mouse click event on label + checkbox. IMO it's really weird/bug that it also cancels the single "keyboard" click event.
