### ISSUE TITLE
@angular/material/core - The target entry-point has missing dependencies

### ISSUE THREAD

**Issue by piotr-mamenas** [angular/components#19675]
#### What are you trying to do?

I am trying to upgrade Angular to version 9 and Ivy along with Material. I followed the original angular update guide from v8 to v9 and also added ngcc as postinstall into the scripts section of the package.json

I keep receiving:
Warning: Entry point 'ng5-slider' contains deep imports into 'D:/Project/whoonid/Application/ClientApp/node_modules/ng5-slider/node_modules/rxjs/Subject', 'D:/Project/whoonid/Application/ClientApp/node_modules/ng5-slider/node_modules/rxjs/Subscription', 'D:/Project/whoonid/Application/ClientApp/node_modules/ng5-slider/node_modules/rxjs/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/material/bottom-sheet : es2015 as esm2015
Compiling @angular/material/button-toggle : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/checkbox : es2015 as esm2015
Compiling @angular/material/chips : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/material/datepicker : es2015 as esm2015
Compiling @angular/material/expansion : es2015 as esm2015
...
Compiling @angular/material/tree : es2015 as esm2015

ERROR in The target entry-point "@angular/material/core" has missing dependencies:
 - @angular/core
 - @angular/platform-browser
 - rxjs
 - rxjs/operators
 - @angular/platform-browser/animations
 - @angular/common
 - @angular/forms

I tried downgrading the packages selectively but just ended up with more errors.
  
After each attempt at fixing it, I do a full clear of npm cache, remove package-lock.json and the node_modules folder just to be sure some packages are not being cached but this doesn't seem to be the case.

#### Environment

package.json:
  "dependencies": {
    "@angular/animations": "^9.1.11",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.11",
    "@angular/compiler": "^9.1.11",
    "@angular/core": "^9.1.11",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^9.1.11",
    "@angular/http": "^7.2.16",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.11",
    "@angular/platform-browser-dynamic": "^9.1.11",
    "@angular/platform-server": "^9.1.11",
    "@angular/router": "^9.1.11",
    "@fullpage/angular-fullpage": "^0.0.14",
    "@kolkov/angular-editor": "^1.1.2",
    "@microsoft/signalr": "^3.1.5",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/entity": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "@ngrx/store-devtools": "^9.2.0",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "@ngx-translate/core": "^11.0.1",
    "@okta/okta-angular": "^2.0.0",
    "@swimlane/ngx-charts": "^14.0.0",
    "core-js": "^3.6.5",
    "font-awesome": "^4.7.0",
    "ng5-slider": "^1.2.4",
    "rxjs": "^6.5.5",
    "tslib": "^1.13.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.8",
    "@angular/cli": "^9.1.8",
    "@angular/compiler-cli": "^9.1.11",
    "@angular/language-service": "^9.1.11",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.12.47",
    "aspnet-prerendering": "^3.0.1",
    "codelyzer": "^5.2.2",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "node-sass": "^4.14.1",
    "protractor": "^5.4.4",
    "ts-node": "^8.10.2",
    "tslint": "^5.19.0",
    "typescript": "~3.8.3"
  }

tsconfig.json:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

**Comment by jelbourn** [comment]
@piotr-mamenas any way you can share a reproduction? This seems most likely an environment issue without anything further to investigate.

**Comment by magyk-software** [comment]
@jelbourn i am having the same issue. my current error:
`ERROR in The target entry-point "@swimlane/ngx-charts" has missing dependencies:
 - tslib
 - @angular/core
 - @angular/common
 - @angular/animations
 - @angular/cdk/portal
 - rxjs
 - rxjs/operators
 - @angular/platform-browser
`
what would I do to check my environment?

**Comment by jelbourn** [comment]
Without a reproduction there's not really much I can recommend other than clearing your node_modules and lock file and re-install.

**Comment by piotr-mamenas** [comment]
Clearing node_modules and lock files as well as many other solutions did not work.

You can reproduce it easily by just creating an empty project with these dependencies.

There is a stack here that no one can answer: https://stackoverflow.com/questions/62418620/missing-material-dependencies-after-upgrade-to-angular-9 I already set up a bounty and it failed

**Comment by devversion** [comment]
I tested the exact same dependencies you have listed in the issue, and ran `ngcc` as postinstall. I wasn't able to reproduce this - and we also run separate tests for ngcc which seem to work as expected. Please create a new issue; with a working reproduction (as a repository) if this is still an issue. I don't see anything that could be wrong with the Angular Material packages.
