### ISSUE TITLE
docs-bug(COMPONENT): Is there a running tutorial on this repository code? 

### ISSUE THREAD

**Issue by chenjianlong-java** [angular/components#19673]
I downloaded the project file, but trying to execute with command bazel test、yarn test etc was unsuccessful
I didn't find any documentation or video tutorials
how to use bazel to build this angular/component code
Can someone teach me！！

**Comment by devversion** [comment]
@changLiuUNSW Can you share more information on what you are seeing?

**Comment by chenjianlong-java** [comment]
> @changLiuUNSW Can you share more information on what you are seeing?

actually,i don't know how to build this repository width bazel,
and I don't know which commands to run
is there a documentation or video tutorials for this?

**Comment by devversion** [comment]
@chenjianlong-java There shouldn't be any knowledge of Bazel required. We expose all the common method in Yarn scripts. e.g. `yarn build` or `yarn test`. You mentioned that `yarn test` fails, but I wonder what you were seeing there?

Here is a small document that should help with setting up the project locally: https://github.com/angular/components/blob/master/DEV_ENVIRONMENT.md.

**Comment by chenjianlong-java** [comment]
> @chenjianlong-java There shouldn't be any knowledge of Bazel required. We expose all the common method in Yarn scripts. e.g. `yarn build` or `yarn test`. You mentioned that `yarn test` fails, but I wonder what you were seeing there?
> 
> Here is a small document that should help with setting up the project locally: https://github.com/angular/components/blob/master/DEV_ENVIRONMENT.md.

Thank you. That's exactly what I wanted, but it would be nice if there were more detailed documentation
