### ISSUE TITLE
feat(cdk-text-field): Add row-wise error indicators for textarea.

### ISSUE THREAD

**Issue by andreElrico** [angular/components#19686]
#### Feature Description

[myStackblitz](https://stackblitz.com/edit/angular-y3uppy-tqzr1m?file=src%2Fapp%2Ftext-field-autosize-textarea-example.css)

rowwise error/ success indicators are something I was looking for. It would be a nice acompany to `cdkTextareaAutosize`.

Is this something the cdk has an interest to further research and elaborate ?

+ this is just my first draft (no tests, no optimizations). I want to create a library if this is not interesting for the cdk.

#### Use Case

Have a lintable UX if bulk data is provided in a textarea.

**Comment by jelbourn** [comment]
Thanks for the proposal- we don't have any plans to add a feature like this
