### ISSUE TITLE
YouTube Player : no cookie mode

### ISSUE THREAD

**Issue by BenLune** [angular/components#19681]
#### What are you trying to do?

What are you trying to do?

I would like to use the material YouTube Player in nocookie mode in order to respect privacy.

What are you seeing that does not match your expectations? 
I don't see  anything about it, which is, to my point of view, quite important.
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by BenLune** [comment]
Am I the only one to be concerned by privacy policy?

**Comment by scote** [comment]
I am also interested with no cookie mode. Is there a workaround ?

**Comment by BenLune** [comment]
OK, I'm not the only one :-)

**Comment by flumpt** [comment]
@scote @BenLune Did you find a workaround? I'm also interested in no cookie mode.

**Comment by BenLune** [comment]
Hi all,
Thanks a lot, I'm happy to see it resolved, and I hope it will help people to better use this component.
