### ISSUE TITLE
help(Datepicker): cut off on small displays

### ISSUE THREAD

**Issue by angelvk83** [angular/components#19696]
I'm trying to show the complete datepicker calendar in a small screen, but it is not possible to access to the whole calendar.

There is no scroll, and no possibilities to reach all the content of the datepicker when the display is smaller than the datepicker.

It happens with any datepicker, for example that from the official page:

https://material.angular.io/components/datepicker/overview

Steps to reproduce:
1. Reduce the navigator window, to a heigh of no more than 300px
2. Open the datepicker
3. Try to access the hole days (It isn't possible)
  
#### Environment

- Angular: 9.0.2
- CDK/Material: 9.0.1
- Browser(s): Chrome & Firefox (Last versions)
- Operating System: Windows 10

**Comment by crisbeto** [comment]
You can enable touch UI mode through the `touchUi` input which will make the datepicker scale based on the screen size. Here's an example: https://stackblitz.com/angular/mkjpykkkoek

**Comment by angelvk83** [comment]
Thanks!! That fits perfect what we need!
