### ISSUE TITLE
feat(google-maps): allow map to be styled natively instead of through inputs

### ISSUE THREAD

**Issue by markgoho** [angular/components#19732]
#### Feature Description
Currently, the google-map object takes a height and width input which are then coerced to px values. This appears to break whenever a value is provided that isn't a css length unit.

#### Use Case
I'd like to set the height of the google to be `calc(100vh - var(--header-height))`. Unfortunately, because the api is designed to use these inputs as _inline styles_ I'm forced to use `!important` to override the default `500px` values. For example, if I use css in the global scope:

``` css
.map-container {
  height: calc(100vh - var(--header-height));
  width: 100%;
}
```
what you end up with is:
![image](https://user-images.githubusercontent.com/9759954/85430773-92037c80-b54e-11ea-9b99-f91729d4e273.png)
and
![image](https://user-images.githubusercontent.com/9759954/85430806-9def3e80-b54e-11ea-8f65-683e875ea37f.png)

### Solution

Remove the inputs and allow folks to style the map natively using css.

**Comment by crisbeto** [comment]
In retrospect, we should've probably left the sizing completely to CSS, rather than having inputs for it. Allowing the `width` and `height` to be null might be a good compromise.

**Comment by crisbeto** [comment]
Closing since the related PR (https://github.com/angular/components/pull/19790) went in already, but I didn't mark it correctly so it didn't auto-close the issue.
