### ISSUE TITLE
Distorted Mat-Date-Picker display in angular-8

### ISSUE THREAD

**Issue by AnupDeval** [angular/components#19744]
We are using the angular-8 with Mat-DatePicker.
Below is the code snippet,

`<input matInput name="picker" [matDatepicker]="Picker" [(ngModel)]="batchEntity.batchDate"
                placeholder="Choose a date" class="textbox txt mandatory" disabled
                (dateChange)="toggleField('BatchDate')"
                [ngClass]="{'error': (ValidationResult.batchDate)}">
              <mat-datepicker-toggle matSuffix [for]="Picker"></mat-datepicker-toggle>
              <mat-datepicker #Picker disabled="false"></mat-datepicker>`

This works perfectly but for display for month of June is completely distorted as shown below --
<img width="371" alt="DatePicker" src="https://user-images.githubusercontent.com/38226919/85590444-07805300-b60a-11ea-8e2f-aabab10a5900.png">

How can i fix the display of the datepicker?

**Comment by crisbeto** [comment]
It looks like some of your styles are overriding the styles from the datepicker. You should be able to figure it out by looking at the "Styles" tab in the element inspector.

**Comment by crisbeto** [comment]
Closing since this looks like an error in the user's app.
