### ISSUE TITLE
bug(DATEPICKER): MomentAdapter wrong parsing value from text-input

### ISSUE THREAD

**Issue by izmaylovdev-ume** [angular/components#19758]
#### Reproduction

https://stackblitz.com/angular/yjpeopmmgdgg?file=src%2Fapp%2Fdatepicker-formats-example.ts
It also reproduces in doc https://material.angular.io/components/datepicker/examples

Steps to reproduce:
1. Try to paste to input 02/02/20 or 02.02.19
 
 
#### Expected Behavior

After formatting get "February 2, 2020"

#### Actual Behavior

After formatting get "January 2, 2002"

#### Environment

- Angular: 10.0.0
- CDK/Material: 10.0.0
- Browser(s): Chrome
- Operating System macOS

**Comment by swseverance** [comment]
@izmaylovdev-ume if the following works for you can you please close the issue? Thanks

```typescript
export const MY_FORMATS = {
  parse: {
    dateInput: 'L',
  },
  display: {
    dateInput: 'LL',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};
```

**Comment by izmaylovdev-ume** [comment]
Works, thank you. But you there are still bug in official sample.
