### ISSUE TITLE
mat-tab-nav-bar not working anymore after v10 upgrading

### ISSUE THREAD

**Issue by JeanBaptisteINITIATIVES** [angular/components#19754]
Hi,

I make the migration this morning to the new v10 Material version + v10 Angular version. Great work. But I have an issue with my navigation inside a <nav mat-tab-nav-bar> tag which is not working anymore... The initial route works fine, but when switching from tabs, the new content is not rendering, or very slowly and not completely...

Here is my html : 
`<mat-card class="mat-elevation-z3 nav-card">
        <div class="row">
            <div class="col-12">
                <nav mat-tab-nav-bar>
                    <a #tab
                        mat-tab-link
                        *ngFor="let link of navLinks"
                        [hidden]=link.hide
                        [routerLink]="link.path"
                        routerLinkActive
                        #rla="routerLinkActive"
                        [active]="rla.isActive"
                        [tabIndex]="link.tabindex">
                        <fa-icon *ngIf="link.icon" [icon]="[link.icon[0].style,link.icon[0].name]"></fa-icon>
                        <span class="d-none d-lg-inline">{{ link.label }}</span>
                    </a>
                </nav>
            </div>
        </div>
        <router-outlet #o="outlet"></router-outlet>
    </mat-card>`

And my navLinks array : 
`navLinks = [
        { path: 'header', label: 'En-tête', icon: [{ style: 'fas', name: 'id-card-alt' }], hide: false, tabindex: '-1' },
        { path: 'search-parties', label: 'Recherche', icon: [{ style: 'fa', name: 'search' }], hide: true, tabindex: '-1' },
        { path: 'party/detail', label: 'Détail contact', icon: [{ style: 'fa', name: 'address-book' }], hide: true, tabindex: '-1' },
        { path: 'party/add', label: 'Ajout contact', icon: [{ style: 'fa', name: 'plus' }], hide: true, tabindex: '-1' },
        { path: 'body', label: 'Corps', icon: [{ style: 'fas', name: 'sitemap' }], hide: false, tabindex: '-1' },
        { path: 'payment', label: 'Règlement', icon: [{ style: 'fas', name: 'money-bill-alt' }], hide: false, tabindex: '-1' },
        { path: 'infos', label: 'Infos', icon: [{ style: 'fas', name: 'info-circle' }], hide: false, tabindex: '-1' },
        { path: 'tracking', label: 'Suivi', icon: [{ style: 'fas', name: 'sticky-note' }], hide: false, tabindex: '-1' },
        { path: 'restocking', label: 'Commandes liées / Réassorts', icon: [{ style: 'fas', name: 'external-link' }], hide: false, tabindex: '-1' },
        { path: 'product-planning', label: 'Planning produit', icon: [{ style: 'fa', name: 'calendar' }], hide: false, tabindex: '-1' }
    ];`

I tried with the updated Material documentation to adapt the code, without success.
The <router-outlet> matches child routes in my .ts routing file.

Best regards,

Jean-Baptiste BELIN

**Comment by devversion** [comment]
Hello! This is unfortunately not enough information for us to reproduce this. I can see the tab-nav-bar working. Could you please resubmit this issue / or comment here with a reproduction in StackBlitz?
