### ISSUE TITLE
docs-bug(CHIPS): Error retrieving examples 

### ISSUE THREAD

**Issue by sydneyluce** [angular/components#19768]
#### Documentation Feedback

With 10.0.0 update, it looks like there are some errors retrieving the "chips" component examples.

`Failed to load document: /docs-content/examples-highlighted/material/chips/chips-overview/chips-overview-example_undefined-html.html. Error: OK`

`Failed to load document: /docs-content/examples-highlighted/material/chips/chips-stacked/chips-stacked-example_undefined-html.html. Error: OK`

**Affected documentation page:** https://material.angular.io/components/chips/overview

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/components/pull/19762.
