### ISSUE TITLE
bug(mat-icon): Error retrieving icon :mysvg! User login is required. For silent calls, request must contain either sid or login_hint

### ISSUE THREAD

**Issue by alvipeo** [angular/components#19767]
angular 10, material 10.

I can't really repro this issue as I use authn/authz in my project.

The issue is with this custom SVG. here's the service:
```
@Injectable({
  providedIn: "root",
})
export class IconService {
  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {}

  public registerIcons(): void {
    this.loadIcons(Object.values(AppLanguage), "assets/flags");
  }

  private loadIcons(iconKeys: string[], iconUrl: string): void {
    console.log(iconUrl);
    iconKeys.forEach((key) => {
      const keyLower = key.toLowerCase();
      this.matIconRegistry.addSvgIcon(
        keyLower,
        this.domSanitizer.bypassSecurityTrustResourceUrl(
          `${iconUrl}/${keyLower}.svg`
        )
      );
    });
  }
}
```

When user is logged in to the app I see the SVG, no problem. But when the user is not authenticated I get the following error:
> Error retrieving icon :mysvg! User login is required. For silent calls, request must contain either sid or login_hint
    at SafeSubscriber._error (icon.js:713)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.error (Subscriber.js:135)
    at Subscriber._error (Subscriber.js:75)
    at Subscriber.error (Subscriber.js:55)
    at TakeSubscriber._error (Subscriber.js:75)
    at TakeSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at TapSubscriber._error (tap.js:56)

But I do NOT restrict any access for **assets**!
This is the routes setup:
```
const routes: Routes = [
  {
    path: "",
    component: HomeComponent,
    pathMatch: "full",
  },
  {
    path: "someroute",
    canActivate: [TmvAuthorizedGuard],
    canLoad: [TmvAuthorizedGuard],
    loadChildren: () =>
      import("./concerts/concerts.module").then((m) => m.ConcertsModule),
  },
  { path: "unauthorized", component: NotAuthorizedComponent },
  {
    path: "**",
    component: NonExistingPageComponent,
  },
];
```

The SVG icon is used in HomeComponent.

**Comment by crisbeto** [comment]
This looks like an issue with your setup. What the error is saying is that the HTTP request for the icon (basically a `HttpClient.get`) failed with the error `User login is required. For silent calls, request must contain either sid or login_hint`. You should either adjust the backend not to require a login to fetch icons, or serve the icons from someplace else.
