### ISSUE TITLE
bug(MAT-STROKED-BUTTON): Incorrect Border color

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/components#19769]
#### Reproduction

Steps to reproduce:
1.  <button mat-stroked-button color="primary">Button</button>
2. In **_theming.scss** line **2204** styles for not disabled button owerrides primary border color
  ```
.mat-stroked-button:not([disabled]) {
    border-color: mat-color($foreground, divider);
  }
```
#### Expected Behavior
in `color="primary"` and not `disabled ` button color of borders should be primary by default
![image](https://user-images.githubusercontent.com/5783161/85823170-8a3a1700-b79e-11ea-8ed4-b17858c5974f.png)

**Comment by wagnermaciel** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment
(this is a canned response)
