### ISSUE TITLE
e2e test browser versions need to be updated

### ISSUE THREAD

**Issue by Achilles1515** [angular/components#19778]
I see the following browsers being tested in the **ci/circleci: tests_saucelabs** continuous integration output logs for pull requests:

```
Edge 17.17134.0 (Windows 10.0.0)
Mobile Safari 11.0.0 (iOS 11.2.0)
```

Neither of these browser versions are officially supported by the Angular Components team.

>The Angular Components team supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and IE11 / Edge.

As the issue title states, what browsers and browser versions are all being e2e tested?
Is iOS 13 being tested?

**Comment by jelbourn** [comment]
@devversion it does look like our browser versions are a bit out of date

**Comment by devversion** [comment]
Firefox has been updated with https://github.com/angular/components/pull/20014
Other browsers pending with: https://github.com/angular/components/pull/19961

**Comment by devversion** [comment]
Done! Thanks @Achilles1515 for raising this!
