### ISSUE TITLE
bug(Mat-Datepicker): Aria-label is not recognized by voiceover in iPhone 

### ISSUE THREAD

**Issue by ankushgoyal27** [angular/components#19773]
#### For iPhone
Steps to reproduce:
1. Launch the Datepicker example from angular material docs.
2. Start the voice over in iphone 
3. Swipe over the dates

I think this is happening may be because of tabindex is not updating from -1 to 0 when keydown in safari or swipe right in iPhone Safari.
 
#### Expected Behavior

It should read the aria-label date for eg. June 26th 2020.

#### Actual Behavior

It is just reading the date like 26, 27 and soon.

#### For Android
Steps to reproduce:
1. Launch the Datepicker example from angular material docs.
2. Start the talkback in Android 
3. Swipe over the dates
 
#### Expected Behavior

It should read the aria-label date for eg. June 26th 2020.

#### Actual Behavior

It is just reading the date like June 26th 2020 disabled and soon.

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.2.4
- Browser(s): safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

**Comment by ankushgoyal27** [comment]
Hi, anyone please help me for this issue.

**Comment by crisbeto** [comment]
I spent some time looking into it, but from what I could tell and from Googling around, it looks like VoiceOver on iOS can just decide not ignore the `aria-label` and there isn't much we can do about it. Technically we can have the label inside an invisible element in each cell, but that could degrade the experience for users that have different screen readers.

**Comment by ankushgoyal27** [comment]
Thank you Kris for the Input, I already tried this solution and it works.
