### ISSUE TITLE
bug(cdk-overlay-container): duplication when using an external library

### ISSUE THREAD

**Issue by ALapaque** [angular/components#19770]
#### Reproduction

The issue is when I'm adding ngx-contextMenu to my project the dom inject a new container "cdk-overlay-container" in the dom when I navigate to different components within module. And we're using these containers to set a class for theming.
I don't know if it comes from Angular/material or ngx-contextMenu so I'm posting an issue on both.
But if I remove the ngx-contextmenu package the containers works perfectly.

Use https://github.com/ALapaque/dyma-cocktails/tree/issues/contextMenu

![bug-ngx-contextMenu](https://user-images.githubusercontent.com/46450511/85839700-98d2ff00-b79b-11ea-8b4b-fec60773d1e5.gif)

Steps to reproduce:

1. Click on 'Acheter'
2. Click on 'button next to Cocktails and go to panier'
3. Right click on an element of the list
4. See the DOM contains now two containers, one with the class theme and one without

 
#### Expected Behavior

What behavior were you expecting to see?
As before we should only have one container which is trigger even in components part in a module.

#### Actual Behavior

What behavior did you actually see?
when we're navigating and loading different modules, if we need to inject an element like a mat-menu or a context menu in the DOM it duplicates the <div class="cdk-overlay-container"></div>

#### Environment

- Angular: 9.1.11
- CDK/Material: 9.2.4
- Browser(s): Chrome Version 85.0.4181.9 (Build officiel) dev (64 bits)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment]
@ALapaque I cloned your repo but I wasn't able to make an overlay appear with the instructions provided

**Comment by ALapaque** [comment]
@jelbourn I did manage to make a fix by doing a rollback of the library I use for the context menu. So I've set an issue on his repo in order to let him know this thing.

**Comment by jelbourn** [comment]
Okay, sounds like this is an issue somewhere else, so closing this one.

**Comment by ALapaque** [comment]
@jelbourn as I mentionned in the initial message I'm not sure where this issue comes from the as I've rollback the context-menu library I think this comes from this library.


Sorry for this inconvenience.
