### ISSUE TITLE
feat(COMPONENT): Styling an area to show that It's restricted after a cdkDrag

### ISSUE THREAD

**Issue by samuelidehen** [angular/components#19772]
#### Feature Description
  I want to be able to style a restricted area once a cdkDrag is made to show the Users that they can not make a cdkDrop in that zone.
Provide a brief summary of the feature you would like to see.
 I tried to make the area [cdkDropListDisabled]= "true" and then style the .cdk-drop-list-disabled{} but this doesn't give the desired result because it styles the restricted area even before any cdkDrag Event. The desired result is that the restricted area is dynamically style upon cdkDrag and styling is removed after cdkDrop
#### Use Case
 The Use case is for better User Experience to show the User what areas can be dropped in and what areas are restricted.
Describe the use case(s) that the proposed feature would enable.

**Comment by crisbeto** [comment]
You should be able to have `[cdkDropListDisabled]="isDisabled"` where `isDisabled` starts off as `false` and then you flip it to `true` after the first drop event.

**Comment by samuelidehen** [comment]
I tried that It does not work . I want it disabled upon drag not drop.

**Comment by crisbeto** [comment]
Sorry for the delay, I think this got buried in the other notifications. So you're trying to change the `cdkDropListDisabled` when dragging starts? I think it might not be working because you have to trigger change detection for the value to be picked up.

**Comment by samuelidehen** [comment]
Yes I am trying to change the cdkDropListDisabled when dragging starts, I attached  a (cdkDragStarted) on the cdkDrag that calls a dragStart() function.`(cdkDragStarted)="dragStart($event)"` .That solves the problem but I would believe there has to be a better solution

**Comment by samuelidehen** [comment]
I urgently need a solution for this issue @crisbeto .

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. Given that there hasn't been any activity in two years, I'm assuming that the issue was resolved. Feel free to open a new issue if that's not the case.
