### ISSUE TITLE
bug(MatMenuTrigger): Memory Leak - menu close subscription is not cleaned up - v5.2.5

### ISSUE THREAD

**Issue by bijinab** [angular/components#19781]
#### Reproduction

Steps to reproduce:
1. Create a mat-menu component in a parent component
2. Add MatMenuTrigger ([matMenuTriggerFor]) on a dynamically built child component. eg: list item
3. Destroy the child component
4. Child component and its DOM nodes are removed from DOM but not from memory
 
 
#### Expected Behavior

All subscriptions are cleaned up.
Child component and its DOM nodes are removed from memory.

#### Actual Behavior

Menu close subscription is not cleaned.
Child component and its DOM nodes are not removed from memory.
```
    MatMenuTrigger.prototype.ngAfterContentInit = /**
     * @return {?}
     */
    function () {
        var _this = this;
        this._checkMenu();
        this.menu.close.subscribe(function(reason) {
            _this._destroyMenu();
            // If a click closed the menu, we should close the entire chain of nested menus.
            if (reason === 'click' && _this._parentMenu) {
                _this._parentMenu.closed.emit(reason);
            }
        });
        ...
    };
```

#### Environment

- Angular: 5.2.7
- CDK/Material: 5.2.5

**Comment by crisbeto** [comment]
Closing since we aren't backporting any fixes for version 5 anymore.
