### ISSUE TITLE
bug(youtube-player): the "ready" event is not sent or captured when the youtube player is done loading

### ISSUE THREAD

**Issue by goossaert** [angular/components#19788]
#### Reproduction

The [youtube-player](https://github.com/angular/components/tree/master/src/youtube-player) component has an event named "ready" which can be captured to detect when the youtube player has loaded, to get a reference to it so that future actions can be performed on it (play, pause, etc.). With Angular v9.1.11 and youtube-player v9.2.4, the "ready" event is no longer emitted.

Here is a Stackblitz link for an example: https://stackblitz.com/edit/angular-youtube-player-example-6rrcta

Steps to reproduce:
1. Open the file `/src/app/video/video.component.ts` in the provided Stackblitz link, and observe that the “ready” event is configured to call the showready() method, which should log to the console the message “I am ready” as soon as the youtube player loads (i.e. when the page loads).
2. Open the developer tools in your web browser, and open the console.
3. Reload the Stackblitz link.
4. Observe that no message “I am ready” is displayed in the console, hence proving that the “ready” event is not being sent or captured.
 
 
#### Expected Behavior

The expected behavior was that the message "I am ready" was supposed to show in the console, proving that the "ready" even was being sent or captured correctly.

#### Actual Behavior

The behavior seen in the provided example is that the "ready" event is not being sent or captured.

#### Environment

- Angular: 9.1.11
- CDK/Material: 9.2.4
- Browser(s): Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina 10.15.3

**Comment by crisbeto** [comment]
It's working for me when testing it out against master. Have you tried updating to the latest version?

**Comment by goossaert** [comment]
I upgraded all Angular components in my project to v10.0.0, including `youtube-player`, and that version works for me. I'll close the ticket then, feel free to reopen if needed. Thanks!
