### ISSUE TITLE
reduce -> some

### ISSUE THREAD

**Issue by tamtakoe** [angular/components#19794]
Sorry if stupid question.
https://github.com/angular/components/blob/2a9741824ed6fcb43302cc241f5441123ba73e90/src/cdk/table/table.ts#L787-L790
This looks strange. Why not:
```
this._rowDefs.some((def: BaseRowDef) => !!def.getColumnsDiff())
```
?

**Comment by jelbourn** [comment]
Probably no particular reason; feel free to send a PR if you want to clean it up. Closing this since it's not a functional bug
