### ISSUE TITLE
GoogleMap compilation error

### ISSUE THREAD

**Issue by estebanTMachine** [angular/components#19802]
I am having the following error when I try to compile:

Uncaught TypeError: Class constructor GoogleMap cannot be invoked without 'new'

And this is my Angular version.

Angular CLI: 9.1.9
Node: 14.3.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@angular/google-maps              10.0.0
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0.

I tried changing the 'target' in the 'tsconfig.json' file from es2015 to es5, but the problem continues.
I´m working on a completely new installation with no other components. 
This is the full error message in console: 

google-maps.js:473 Uncaught TypeError: Class constructor GoogleMap cannot be invoked without 'new'
    at Module../node_modules/@angular/google-maps/__ivy_ngcc__/fesm2015/google-maps.js (google-maps.js:473)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.component.ts (app.component.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:79)

**Comment by Tochukwuibe** [comment]
I am facing the  same issue

**Comment by gagermaniac** [comment]
me too

**Comment by gagermaniac** [comment]
use version ^9.2.4 work perfectly

**Comment by jelbourn** [comment]
Does this happen with v10 of Angular? For any UI  components on this repo, they require a version of Angular of the same major version.

**Comment by estebanTMachine** [comment]
Ok, it was just an Angular version problem. I did solve it running the next command> npm install @angular/cli@latest. Now, I'm working on v10. Thanks to everyone

**Comment by AdaLollA** [comment]
> use version ^9.2.4 work perfectly

sorry for the necro, but changing the entire angular versioning just for one component does not feel right. Transitioning the maps plugin to ^9.2.4 worked perfectly when using all current ionic default settings. The newest version of it, 10.0.1, does not work with the default ionic setup and threw the error of this issue.
