### ISSUE TITLE
docs-bug(COMPONENT): Textual improvements of the progress-bar documentation

### ISSUE THREAD

**Issue by d2a-pnagel** [angular/components#19817]
#### Documentation Feedback

In the documentation on progress bars, a few times the description says "... where the user wants to indicate ..." but this is incorrect. The user does not want to indicate anything here. Also, the texts are gramatically incorrect and confusing.

https://material.angular.io/components/progress-bar/overview#buffer

- Current text: "Operations where the user wants to indicate some activity or loading from the server, use the buffer indicator."
- Suggestion: "Use the buffer indicator to indicate loading from the server in addition to the actual progress."

https://material.angular.io/components/progress-bar/overview#query

- Current text: "For situations where the user wants to indicate pre-loading (until the loading can actually be made), use the query indicator."
- Suggestion: "Use the query indicator to indicate pre-loading before the actual loading starts."

Thanks,
Peter

**Comment by walvekarnikhil** [comment]
Can I help in fixing this?

**Comment by crisbeto** [comment]
Sure, feel free to send in a PR.
