### ISSUE TITLE
help(CdkTable): Why are we always forcing rerendering all rows even when 1 column had changed

### ISSUE THREAD

**Issue by Humberd** [angular/components#19825]
In my project we extensively use CdkTable and had recently stumbled upon performance issue. We are rendering 20 rows with 40 columns. When we dynamically add even 1 column the table instead of adding that one column rerenders all 20 rows with 41 columns. Is there a particular reason why are we not using difference approach just like we do with rendering additional rows?

Here is the method responsible for such a behaviour:
https://github.com/angular/components/blob/1106cb1ea7d07ce603e2afeb3a9e0e0f71d4e5db/src/cdk/table/table.ts#L786+L802

**Comment by andrewseguin** [comment]
In order to get that performance benefit, we would need an 2D iterable differ, one that compares across rows (that is what we use now), and another that compares across columns. This overhead was deemed excessive for the vast majority of cases and it didn't seem worth complicating the table for.
