### ISSUE TITLE
help @angular/google-maps

### ISSUE THREAD

**Issue by nedpuganti** [angular/components#19839]
how can I open marker info window on maps from external button click.

example : https://jsfiddle.net/upsidown/8gjt0y6p/

how do I do it in angular

**Comment by crisbeto** [comment]
The Google Maps module has a `map-info-window` directive that you can attach to a marker using its `open` method. We don't have live examples for it yet, but you can see how it works in our dev app:
https://github.com/angular/components/blob/master/src/dev-app/google-map/google-map-demo.ts#L99
https://github.com/angular/components/blob/master/src/dev-app/google-map/google-map-demo.html#L19
