### ISSUE TITLE
bug(datepicker): `calendar.selectedChange.emit` not working in v10 (regression?)

### ISSUE THREAD

**Issue by acalvo** [angular/components#19836]
#### Intro

I have a custom datepicker that wraps material's datepicker and [adds a custom header](https://material.angular.io/components/datepicker/overview#customizing-the-calendar-header). This custom header provides some useful action buttons to set the date to the most typical needed dates for that use case; for example, a button to set it in a month from today.

This component was built in Angular Material 6-7 times and worked flawlessly till Angular Material 9. Upgrading to Material v10, though, made it stop working. The problem seems to be in `this.calendar.selectedChange.emit(theDateIWantToSet);` which doesn't update the input's date anymore. See minimal repro below.

#### Expected Behavior

1. Go to https://stackblitz.com/edit/components-issue-qqxg7v (made with Angular 9)
2. Click in the icon to open the calendar.
3. Click in the `In a month` button.
4. See how the popup is closed and the date is updated (a month from today is added; August 2, 2020 in the time of writing this). This is the expected behavior.
 
 
#### Reproduction

Steps to reproduce the regression:
1. Go to https://stackblitz.com/edit/components-issue-tbqwwk (same code as before, but dependencies upgraded to Angular 10)
2. Click in the icon to open the calendar.
3. Click in the `In a month` button.
4. See how the popup is closed but **the date doesn't change**.

#### Actual Behavior

`this.calendar.selectedChange.emit(theDateIWantToSet);` doesn't change the date to `theDateIWantToSet`.

#### Environment

- Angular: any (working with both 9 and 10)
- CDK/Material: not working with 10, working with 9 and below
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
In general the event emitters that are provided by Material are only intended to be subcribed to and the fact that it worked by emitting to it manually was a coincidence. We had to move some things around to support the date range picker which probably broke your use case. Instead of going through the calendar to update the date, you can inject the `MatDateSelectionModel` and set the value through there.

**Comment by acalvo** [comment]
Works great injecting `MatDateSelectionModel`. Thanks for the clarification! 😄
