### ISSUE TITLE
Provide lighter surface for dark themes elevations

### ISSUE THREAD

**Issue by MikaStark** [angular/components#19837]
#### Feature Description

Hi there ! First of all thanks for your amazing works on Angular and Angular components :).

Today I want to propose to enrich the current elevation API by providing lighter background color depending on elevation level just like it's exposed here [https://material.io/design/color/dark-theme.html#properties](https://material.io/design/color/dark-theme.html#properties). Of course it will be enabled only for dark themes.

Why this feature request ? Because some components like `mat-expansion-panel` are very hard to distinct inside a `mat-card` because they have the same background color. This problem is also present in light themes but there is no material recommandations for it. I'm not a design expert and I have no idea how to handle this. Suggestions are welcomed :)

![image](https://user-images.githubusercontent.com/23034761/86342972-9cadc800-bc58-11ea-9a70-19c14cb9e0a0.png)

#### Use Case

It can be used with native `.mat-elevation-zX` class or with an additionnal class/mixin.

**Comment by jelbourn** [comment]
I think in the future we will be generally exploring more flexibility in the theming system, but in the near term we don't have any plans to change the way background/foreground palettes work
