### ISSUE TITLE
bug(MatSidenav): Overlay scroll strategies do not work in sidenavs and drawers.

### ISSUE THREAD

**Issue by TrevorKarjanis** [angular/components#19846]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-ng8reg?file=src%2Fapp%2Fapp.component.ts

Steps to reproduce:
1. Utilize an overlay or a component with an overlay in a mat-sidenav or mat-drawer that overflows.
2. Declare cdkScrollable on the sidenav or drawer.
3. Scroll the sidenav or drawer.
 
#### Expected Behavior

The overlay's scroll strategy is honored (e.g. the overlay remains fixed to its origin).

#### Actual Behavior

The sidenav's inner container, .mat-drawer-inner-container, handles the overflow and scrolls. Therefore, the cdkScrollable directive has no effect and the scroll strategy is not honored.

#### Environment

- Angular: 10.0.2
- CDK/Material: 10.0.1
- Browser(s): Chrome 83.0.4103.116
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

#### Related Issues

- #10079 has many comments that are likely caused by this issue. However, it is specific to autocomplete while this issue affects all overlays.
- #8405 is the same issue for tabs.

#### Fix

CdkScrollable is [declared on mat-sidenav-content](https://github.com/angular/components/blob/master/src/material/sidenav/sidenav-container.html#L8) but not .mat-drawer-inner-container.

#### Workaround

Place the following in your global styles, and declare CdkScrollable on the mat-sidenav.
```sass
.mat-drawer, .mat-sidenav {
  &[cdk-scrollable], &[cdkScrollable] {
    .mat-drawer-inner-container {
      overflow: visible;
    }
  }
}
```

**Comment by dragosgr** [comment]
I don't understand how this is supposed to help the autocomplete issue.
