### ISSUE TITLE
Deprecate form-field standard and legacy appearance

### ISSUE THREAD

**Issue by devversion** [angular/components#19849]
For V11, we should deprecate the standard and legacy form-field appearances. We already did it in the past, but reverted immediately as the filled/outlined appearances were not having good prefix/suffix icon alignment.

We decided that we just want to fix this as part of our MDC effort. As the spec, and MDC do not support these legacy/standard
appearances anymore, we need to deprecate the appearances. This is slated for v11 and this issue is primarily for tracking.

**Comment by crisbeto** [comment]
Closing since this is done.
