### ISSUE TITLE
bug(mat-slider): Slider jumps back while dragging

### ISSUE THREAD

**Issue by meblum** [angular/components#19842]
#### Reproduction

Bug demo https://stackblitz.com/edit/components-issue-mat-slider
 
 
#### Expected Behavior

The slider should not be automatically move to current value while dragging is in progress

#### Actual Behavior

The slider is updated even while dragging, preventing user from dragging it

#### Environment

- Angular: 10
- CDK/Material: 10

**Comment by wagnermaciel** [comment]
This is fixed in the new MDC version of the slider

Quick stackblitz of the same example w/ the new MDC slider:
https://stackblitz.com/edit/angular-zp3h25?file=src%2Fapp%2Fslider-overview-example.html,src%2Fapp%2Fslider-overview-example.ts
