### ISSUE TITLE
bug(CDK Overlay): css transitions applied to cdk-overlay-pane do not work with dynamic cdkConnectedOverlayOrigin

### ISSUE THREAD

**Issue by zakhenry** [angular/components#19853]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-acneit?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Click each button in turn
2. See that the overlay attached to each button move from one button to the other
 
 
#### Expected Behavior

Due to the css rule specifying a transition time, the overlay should animate from one position to another

#### Actual Behavior

The overlay teleported, as if the transition rule did not apply

#### Environment

- Angular: ^10.0.1
- CDK/Material: ^10.0.1
- Browser(s): Chrome 83
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by zakhenry** [comment]
Update - this is caused by the `FlexibleConnectedPositionStrategy.prototype._resetOverlayElementStyles` method, it sets the `left` and `top` attributes to `''`, which removes the CSS rule entirely, causing any transition to be ignored.

https://github.com/angular/components/blob/master/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L854-L855

It can be fixed by monkey patching that method, however a real fix would be to change those values to `0`. I'm willing to submit an MR, though I have no idea if that would be a breaking change or not.

**Comment by crisbeto** [comment]
We use the `top` and `left` properties to position the overlay so you shouldn't be using them to animate it. The proper way to do it would be to apply the transition on an element inside the overlay.

**Comment by zakhenry** [comment]
@crisbeto the issue is that I want the entire overlay to be moved from one element to another, animating the internals wont work

**Comment by crisbeto** [comment]
I get it, but my point is that these properties aren't a public API since we have to use them to position the overlay correctly. Any overrides would be at your own risk. Another alternative can be to create a custom `PositionStrategy` that doesn't mess with the positioning. If you don't want to repeat all the logic, you can still extend the `FlexibleConnectedPositionStrategy`.

**Comment by jelbourn** [comment]
Yeah, this is working as intended. Our position strategy depends on having full control over those two properties to function correctly. The best thing to do if you want more direct control over the petitioning would be to create a custom position strategy.
