### ISSUE TITLE
feat(MatDateRangePicker): Can’t customize if a date click is a “start date”/prevent empty ranges

### ISSUE THREAD

**Issue by paulferaud** [angular/components#19854]
#### Feature Description

Make it possible to configure the DateRangePicker for scenarios where selecting empty date ranges does not make sense.

#### Use Case

We are working on a tool for hotels, where we *frequently* deal with “check-in/check-out” date pairs.

In such situation, selecting start == end just does not make sense. I feel that this is generally a common use case?

While we can *validate* the input (or fudge it on the fly), it would be nice if the popup “just” handled it.

For example, if you click an end-date that is before start-date, then the popup will just assume that you are re-choosing a new start date, and not close and say your range is invalid.

I’d want to be able to configure that selecting start == end to have the same behavior. EG: be a no op, and not close the popup.

**Comment by crisbeto** [comment]
This should be possible by providing a custom `MatDateRangeSelectionStrategy`. There's an example under the "Customizing the date selection logic" section: https://material.angular.io/components/datepicker/overview#customizing-the-date-selection-logic

**Comment by paulferaud** [comment]
Right. I guess it wasn’t immediately obvious to me how that worked.

Anyways, copy pasting from `DefaultMatCalendarRangeStrategy<D>`, but replacing this line:
```typescript
if (end == null && date && this._dateAdapter.compareDate(date, start) >= 0)
```
with:
```typescript
if (end == null && date && this._dateAdapter.compareDate(date, start) > 0)
```
Did it for me.

Thanks!
