### ISSUE TITLE
[Tooltip]: Initial state of tooltip

### ISSUE THREAD

**Issue by maratkalibek** [angular/components#19862]
#### Feature Description

You can specify the initial state of tooltip from `TooltipVisibility` (visible, hidden).

#### Use Case

In FAB's there is a need to initially show explaining text near the button. It is done with a tooltip. So for FAB, you can initially set tooltip to visible state.

![image](https://user-images.githubusercontent.com/4571314/86516938-abf26880-be46-11ea-9a70-1130ec4062d4.png)

Imate taken here - https://material.io/components/buttons-floating-action-button#types-of-transitions

**Comment by seytzhan** [comment]
It would be very useful feature.

**Comment by jelbourn** [comment]
Closing this because I think this is too much of a niche/specialized use-case that could also be accomplished in other ways
