### ISSUE TITLE
Input placeholder doesn't go above the real input when the appearance is outline 

### ISSUE THREAD

**Issue by newshahn** [angular/components#19864]
#### What are you trying to do?

I want the input label to stay above the input field like this:

![input-field](https://user-images.githubusercontent.com/45605065/86528409-b3ecef80-bebc-11ea-8f37-57f6d90a5836.PNG)

but it's staying in the middle of the input outline like this:

![input-field-incorrect](https://user-images.githubusercontent.com/45605065/86528460-31186480-bebd-11ea-82d4-ae37ac663d19.PNG)

#### What troubleshooting steps have you tried?

So far, I have tried adding the `floatLabel="always"` to the html `mat-form-field` but it doesn't do what I want.

#### Reproduction

https://stackblitz.com/edit/input-field-label 

#### Environment

- Angular: 9.0.1
- Browser(s): Chrome
- Operating System: Windows

**Comment by crisbeto** [comment]
This is how it's supposed to work according to the Material Design spec. See https://material.io/components/text-fields#outlined-text-field.
