### ISSUE TITLE
bug(Menu): matMenuTriggerFor still triggered after adding stopPropagation

### ISSUE THREAD

**Issue by LoganDupont** [angular/components#19884]
#### Reproduction

https://stackblitz.com/edit/angular-tgtfci-gjtttg

Steps to reproduce:
1.  Click on the menu button
2. The menu will open
 
 
#### Expected Behavior

What behavior were you expecting to see?
By adding `(click)="$event.stopPropagation()"` I would expect the menu will not open. Is there a possibility to prevent this trigger from opening? For ex. When you want to open the menu via different event and not via the click event. At the moment I tried to create a custom form field which should only open the menu via the onContainerClick function.

#### Actual Behavior

What behavior did you actually see?
When clicking on the button the `matMenuTriggerFor` opens the menu even if we added a click function to stop event propagation.

#### Environment

- Angular: 10.0.2
- CDK/Material: 10.0.1
- Browser(s): Only tested on chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Only tested on Windows

**Comment by crisbeto** [comment]
It's probably because Angular binds the menu `click` event before yours so propagation is stopped too late. You could prevent it either by marking the button as `disabled` or by setting `pointer-events: none` on it. I'm closing the issue since we can't do much about it on our end.
