### ISSUE TITLE
mat-selection-list static scroll bug

### ISSUE THREAD

**Issue by SvenBudak** [angular/components#19881]
I try to limit a `mat-selection-list` to 6 items and make the list scrollable. The items are static. So no big magic.

If I click on the scrollbar halfway. the scrollbar jumps up again and again. With the mouse wheel the scrolling works without errors.

Stackblitz: https://stackblitz.com/edit/mat-selection-list-scroll-bug

**Comment by crisbeto** [comment]
Same root cause as https://github.com/angular/components/issues/18948.
