### ISSUE TITLE
Kendo UI: No provider for dialogRef

### ISSUE THREAD

**Issue by poojasharma1993** [angular/components#19901]
for component you need to import module in your module file in which you have registered your component as

**import { DialogsModule } from "@progress/kendo-angular-dialog";**

for component as

**import { DialogRef } from '@progress/kendo-angular-dialog';**

and for testing file(spec) as

**import { DialogsModule, DialogRef } from '@progress/kendo-angular-dialog';**

providers: [{ provide: DialogRef, useValue: { close: (dialogResult: any) => { } } }]

**Comment by crisbeto** [comment]
This is the repository for Angular Material and the CDK, not Kendo UI.
