### ISSUE TITLE
bug(matDatepicker): Type MatDatepicker is not assignable to type MatDatepicker<Moment>

### ISSUE THREAD

**Issue by Markoo08** [angular/components#19906]
#### Reproduction

getting Type MatDatepicker is not assignable to type MatDatepicker<Moment> when  value of [max] attribute is null
Inspection info: Reports incorrect return type of an Angular binding expression.

In our case its :
[max]="(observable$ | async)?.date"

#### Actual Behavior

Webstorm throws an error.

#### Environment

- Angular: 8.3.20
- CDK/Material: 8.2.3
- Moment adapter: 8.2.3
- Browser(s): Chrome 83.0.4103.116
- Operating System:  macOS

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
