### ISSUE TITLE
Google Map is Empty after Implement Options

### ISSUE THREAD

**Issue by DMuellerFielddata** [angular/components#19908]
Hi, 
if I iplements the Code for the Google Map Options, my Map empty.
What do I Wrong?
[https://stackblitz.com/](https://stackblitz.com/edit/angular-ivy-bm1vad)

.html

```
<google-map
  height="500px"
  width="100%"
  [options]="mapOptions"
  [zoom]="mapZoom"
></google-map>
```

.ts
```

import { Component} from '@angular/core';
import { MapInfoWindow, MapMarker, GoogleMap } from '@angular/google-maps'

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent {
  zoom=15;
  options : google.maps.MapOption = {
    maxZoom: 18,
    minZoom: 15,
    fullscreenControl: false,
    streetViewControl: false,
    mapTypeControl: false,
  }
}

```

"@angular/core": "~9.1.3",
"@angular/google-maps": "^9.2.2",

**Comment by crisbeto** [comment]
It looks like the map isn't rendering, because you haven't set a `center` in the options. Since this seems like a bit of a gotcha, I'll make some changes so we add a default `center` if one isn't provided. Until then, you should be able to get it working like this:

```
options: google.maps.MapOptions = {
    maxZoom: 18,
    minZoom: 15,
    fullscreenControl: false,
    streetViewControl: false,
    mapTypeControl: false,
    center: {lat: 37.421995, lng: -122.084092}
};
```

**Comment by DMuellerFielddata** [comment]
it works, thx

**Comment by crisbeto** [comment]
Let's keep it open since the current behavior isn't intuitive. There's a PR out to fix it.

**Comment by DMuellerFielddata** [comment]
ok
