### ISSUE TITLE
Hide/remove underline for input

### ISSUE THREAD

**Issue by BizzottoClaudio** [angular/components#19900]
Referring to [#11383](https://github.com/angular/components/issues/11383) and [#6623](https://github.com/angular/components/issues/6623 ) to hide/remove the underline on the input.
Currently the best working solution that i've found is [jurl'answer on stackoverflow](https://stackoverflow.com/a/55394544/8949981):

```
<mat-form-field appearance="none">
    <mat-label>"None" form field</mat-label>
    <input matInput placeholder="Placeholder">
  </mat-form-field>
```
the only problem with this solution is that the height of the input increases, messing up the design.
Given all the attempts that can be found searching for it, i'd like to ask for a feature (e.g. an input property 'isReadonly') for the mat-form-field that hides the underline and caret of the dropdown.

**Comment by jelbourn** [comment]
We don't have any plans at this time to offer an API to customize `mat-form-field` beyond what's described in the Material Design spec

**Comment by swseverance** [comment]
@BizzottoClaudio in your global stylesheet you can add:

```css
.mat-form-field-underline,
.mat-select-arrow-wrapper {
  visibility: hidden;
}
```

This change should not impact the height or width of the elements as a result.

[Stackblitz](https://stackblitz.com/edit/angular-g5rjra)
