### ISSUE TITLE
bug(youtube-player): the `height` and `width` properties cannot be read or set

### ISSUE THREAD

**Issue by goossaert** [angular/components#19909]
#### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-youtube-player-example-thwqfj

Steps to reproduce:
1. Open the file `/src/app/video/video.component.ts` in the provided Stackblitz link, and observe that the `ready` event is configured to call the `onPlayerReady()` method, which should log to the console the height and width of the player as soon as it finishes loading. The `onPlayerReady()` method also sets the height and width to half of the default dimensions.
2. Open the developer tools in your web browser, and open the console.
3. Reload the Stackblitz link.
4. Observe that `height` and `width` show up as being `undefined`, and that the dimensions of the player remain unchanged inside the page.
 
 
#### Expected Behavior

The expected behavior is for `height` and `width` to retrieve and set the dimensions of the player.

#### Actual Behavior

The actual behavior is that neither `height` or `width` seem to be doing anything, i.e. nothing happens.

#### Environment

- @angular/youtube-player: 10.0.1
- Angular: 10.0.2
- CDK/Material: 10.0.1
- Browser(s): Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina 10.15.3

**Comment by jelbourn** [comment]
The `ready` event emits an event of type `YT.PlayerEvent` which does not have width and height properties. To read these properties from the Angular component, you would use a `@ViewChild` query to grab the component and read its height and width.
