### ISSUE TITLE
bug(MAT_HAMMER_OPTIONS): can't import MAT_HAMMER_OPTIONS from '@angular/material/core' in Angular v10

### ISSUE THREAD

**Issue by anndyd** [angular/components#19917]
#### Reproduction

Steps to reproduce:
1.  upgrade Angular and Material from 9 to 10
2. gesture-config.ts created from src/material/schematics/ng-update/migrations/hammer-gestures-v9/gesture-config.template
3. import {MAT_HAMMER_OPTIONS} from '@angular/material/core' shows error.
 
 
#### Expected Behavior
gesture-config.ts should work well.

#### Actual Behavior

import {MAT_HAMMER_OPTIONS} from '@angular/material/core';
Module '"../../../node_modules/@angular/material/core"' has no exported member 'MAT_HAMMER_OPTIONS'

#### Environment

- Angular: 10.0.1
- CDK/Material: 10.0.1
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
It was marked as deprecated for a long time and we've removed it from v10 since it wasn't being used for anything. It's in the breaking changes section of the changelog: https://github.com/angular/components/blob/master/CHANGELOG.md#breaking-changes-1
