### ISSUE TITLE
fr(MatStepper): No notification mechanism on step `interacted` without a step change.

### ISSUE THREAD

**Issue by paulferaud** [angular/components#19918]
#### Reproduction

- Given a linear stepper, with steps associated to forms.
- Have step 1 with an invalid state (which would prevent navigating to step 2)
- Click on header 2.
  
#### Expected Behavior

A SelectionChange event to be fired, saying step 1 was selected (from step 1 before, yes)

#### Actual Behavior

Nothing happened

#### Why

By clicking on the next step, but being denied, then the step is marked as “interacted”, which causes the formFields’s errorStateMatcher start emitting true, making field “red”. This is nice user experience.

HOWEVER, my Steps are actually implemented by components, and they have `ChangeDetectionStrategy.OnPush`. The issue I have is I have NO WAY to notify my component of the event, and tell it to refresh it’s form’s states.

Might be related to https://github.com/angular/components/issues/18080

#### Environment

- Angular: 10.0.1

**Comment by jelbourn** [comment]
@paulferaud would you be able to create a reproduction in StackBlitz that demonstrates the issue?

**Comment by paulferaud** [comment]
Sure. Here: https://stackblitz.com/edit/angular-adnhub

I’m not entirely sure what the “expected” behavior needs to be. The issue is my nested component has no way of being notified of the change:

- Clicking on a “Next” `matStepperNext` button triggers from submit, which is an event the nested component can listen to: https://screencast.googleplex.com/cast/NTA3NDg2OTQyOTQ2OTE4NHw2ZmM1YjcyNS01Mg
- Clicking the “Top navigation” does *not* submit, nor fire any other events, so the nested component does not get notified, and it cannot trigger change detection: https://screencast.googleplex.com/cast/NTY2OTk4NDA1NzQyNTkyMHw3NTRhM2FiYS05NQ

(Sorry about internal videos. Not sure how else to easily share)

Would there be any easy to make `MatStepper`’s `next()` method somehow submit the form that is configured on that `MatStep`?

The alternative might also be to also monitor `selectionChange` events, eg:
```
merge(formGroupDirective.ngSubmit, matStepper.selectionChange).subscribe(() => cd.detectChanges);
```
But that breaks down because in this case, since no event is actually fired. Essentially nothing is fired.
