### ISSUE TITLE
help(MatSelectModule): How to get event that element of options attached to dom 

### ISSUE THREAD

**Issue by shah-dhaval** [angular/components#19921]
#### What are you trying to do?

Applying perfectscrollbar

#### What troubleshooting steps have you tried?

https://stackblitz.com/edit/angular-dj85ga?file=src%2Fstyles.scss

#### Reproduction

https://stackblitz.com/edit/angular-dj85ga?file=src%2Fstyles.scss
 
I have used method when selectbox open but it seems not proper way, is any way to know when element attached to overlay-container?

**Comment by crisbeto** [comment]
The `opened` or `openedChange` events should be correct since they also wait for the animation to be finished. Your example seems to be throwing, because `openedChange` fires both when opening and when closing. If you want an event that only fires on open, you can use `opened`.
