### ISSUE TITLE
help(YouTube): Enable casting to devices PlayerVars enablecastapi

### ISSUE THREAD

**Issue by astone2014** [angular/components#19954]
Ability to enable casting on the YouTube iframe.

I found this flag `enablecastapi` in a [Reddit post](https://www.reddit.com/r/Chromecast/comments/1r2sef/enabling_chromecast_in_youtube_embedded_iframe/)

#### What are you trying to do?

Cast my youtube videos to chromecast, roku, and other devices.

#### What troubleshooting steps have you tried?

node_modules/@types/youtube/index.d.ts

Does not contain the variable enablecastapi

#### Reproduction

Not sure how I would pass this to the player.

This pr has the ability to pass params [#19746]. But type doesn't give ability to cast.
  
#### Environment

- Angular:
@angular/cli                      10.0.2
- CDK/Material:
@angular/material                 10.0.1
@angular/cdk                      10.0.1
@angular/youtube-player           10.0.1
- Browser(s):
Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): 
Windows

**Comment by crisbeto** [comment]
It looks like you can pass it through the `playerVars`, but you'd have to cast your config to `any`. I can see it changing the `iframe` source, although it doesn't seem to be affecting anything else in the player UI. We could expand our type to include the value, but ideally `@types/youtube` would be updated instead.

**Comment by astone2014** [comment]
That's sufficient. I don't think this flag is officially supported yet. Hopefully the team can expose more casting API features in the future. Thanks!
