### ISSUE TITLE
mat-dialog's data restricts to one page when window.print()

### ISSUE THREAD

**Issue by Mehak03** [angular/components#19988]
mat-dialog's data get's cut when window.print()

What is the expected behavior?

window.print() should print all of the data in dialog

What is the current behavior?

window.print() only prints part of the data. 

Previous link to the similar issue but didn’t find any answer. : 
https://github.com/angular/components/issues/10957

Is there any solution to it apart from moving to a new component ?

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
