### ISSUE TITLE
help(Overlay, custom): How to best handle overlay with inputs

### ISSUE THREAD

**Issue by Akxe** [angular/components#19990]
#### What are you trying to do?

I want to create this dialog/overaly/div.
![image](https://user-images.githubusercontent.com/2001798/87529085-c1f5f980-c68e-11ea-9609-0e1a63bf8594.png)

This is the HTML of the component
```html
<mat-form-field>
	<mat-label>{{filterer.label}}</mat-label>
	<input
		#mixedControl
		matInput
		[formControl]="filterer.mixedControl"
		[placeholder]="filterer.placeholder"
		[matAutocomplete]="auto"
		name="rita-shop-search"
	>
	<mat-autocomplete #auto="matAutocomplete" autoActiveFirstOption (optionSelected)="onOptionActivated($event)">
		<mat-option
			*ngFor="let option of autocomplete$ | async"
			[value]="option.value"
			[innerHTML]="option.hintText"
		></mat-option>
	</mat-autocomplete>
</mat-form-field>

<div class="mat-elevation-z5" [@additionalFilters]="additionalFiltersState$ | async">
	<ng-content></ng-content>
</div>

```

#### Why am I asking for help here?

I am asking here because even with all those give components I cannot find a correct way to solve this problem. A question as this is usually not accepted by StackOverflow.

#### What troubleshooting steps have you tried?

* I have created overlay via div, but then I would need an overlay to handle click outside to close it.
* I also did create the same with cdkOverlay, but then the `tabindex` was all messed up.

In both scenarios, I still need to figure out, how to handle when the overlay should be opened. At first, I tried to hook on FocusKeyManager on the component host, but then when I encountered `mat-select` I found out, it "defocused" the `mat-select` when clicking on select's option, or when clicking out of it. (Is this a but?)

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: https://stackblitz.com/fork/components-issue 

Steps to reproduce:
1. 
2. 
  
#### Environment

- Angular: 10.0.3
- CDK/Material: 10.0.1
- Browser(s): Chrome 83
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Akxe** [comment]
@jelbourn This is the look when the overlay is closed:
![image](https://user-images.githubusercontent.com/2001798/87780336-cd802680-c82e-11ea-884e-12482a13f94e.png)

My intention is to create a primary input, where values from all inputs bellow are aggregated, and where they can be written (for advanced users).

I want the overly to ideal not be restricted to overflow, but more importantly, I want the overlay to react to tabbing correctly (have correct tab index)

**Comment by jelbourn** [comment]
Are you expecting the overlay content to be in the tab order based on what it's attached to? If that's the case, you would have to manually manage focus for the overlays; they are always attached directly to the body and won't in the tab order of the main page content.

**Comment by jelbourn** [comment]
We don't have anything in Angular CDK that would manage tab order for you. You could explore adding "dummy" elements that capture `focus` and redirect into the overlay, or potentially exploring manual `tabIndex` numbers for the whole page (which is generally not a great idea). Going to close since this isn't really a bug with the overlay itself.

**Comment by Akxe** [comment]
@jelbourn This was never marked as bug, but rather as “help”. How about adding the ability to create origin for the overlay used by select? It would solve the tabindex...

```
<mat-select [overlay-origin]=“element”>
  ...
</mat-select>
<div #element></div>
```
