### ISSUE TITLE
bug(Expansion Panel): Expansion Panels aligned in a grid all expand/collapse at the same time

### ISSUE THREAD

**Issue by obumnwabude** [angular/components#19993]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue-expansion-panels-in-grid

Steps to reproduce:
1. Repeat and populate expansion panels in a container
2. Style the container to align the panels with the grid display in CSS at wide widths
 

#### Expected Behavior

What behavior were you expecting to see?
That when the panels lie side-by-side in wider screens, expanding or collapsing one panel, only expands or collapses it and does not affect the expansion state of other panels by it.

#### Actual Behavior

What behavior did you actually see?
When the panels lie side-by-side in wider screens, expanding or collapsing one panel, expands or collapses all other panels that on the same grid row with it.

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Ubuntu

**Comment by jelbourn** [comment]
@obumnwabude by adding `display: grid` to the parent element of the grid, you're affecting the height of the expansion panel when the grid layout occurs. You can fix this by adding a `div` around each expansion panel, like this: 
https://stackblitz.com/edit/components-issue-expansion-panels-in-grid-kmyr4g?file=src%2Fapp%2Fexample-component.html

**Comment by obumnwabude** [comment]
Okay, thank you!
