### ISSUE TITLE
bug(mat-table): *matNoDataRow not displayed when data is empty

### ISSUE THREAD

**Issue by MRMokwa** [angular/components#19992]
#### Reproduction

https://stackblitz.com/edit/components-issue-uj7g1k

Steps to reproduce:
1.  Notice that no message is displayed when array is empty.
![image](https://user-images.githubusercontent.com/12090931/87548889-830e7680-c683-11ea-9c5a-7d5f78c5d81a.png)

2. Uncomment the data in ELEMENT_DATA array, and apply "abc" to the filter, now a message from matNoDataRow is displayed
 ![image](https://user-images.githubusercontent.com/12090931/87548922-8f92cf00-c683-11ea-8524-dda8d36ac1f0.png)

 
#### Expected Behavior

What behavior were you expecting to see?
When data is an empty array, it should display the matNoDataRow

#### Actual Behavior
It only shows matNoDataRow if the data has at least one value before applying the filter.

#### Environment

- Angular: 10.0.3
- CDK/Material: 10.0.2
- Browser(s):  Chrome
- Operating System Windows

**Comment by rafagarcia** [comment]
Just updated my project from version 9 to version 10 and still not working

My versions:
"@angular/material": "^10.1.0",
"@angular/core": "~10.0.5",

**Comment by MRMokwa** [comment]
It's merged, but it's not on npm yet.
Probably in next version (~in a couple of days) it will be available.
