### ISSUE TITLE
docs-bug(CDK:Overlay): Stackblitz example broken

### ISSUE THREAD

**Issue by rramsey** [angular/components#19997]
#### Documentation Feedback

**Provide a brief summary of what you would like to see changed in our documentation at material.angular.io.**

I'd like to see the Stackblitz example for the CDK Overly work. 

Feel free to provide any suggestions of content or examples you’d like us to include.
To reproduce:

1. Go to https://material.angular.io/cdk/overlay/examples
2. Click on the button to "Edit Overlay basic example example in Stackblitz"  (yes, 'example' is duplicated in the html and should be fixed)
3. Stackblitz https://stackblitz.com/angular/ldqanovorkl?file=src%2Fapp%2Fcdk-overlay-basic-example.ts opens in a new tab
4. Stackblitz spinner icon appears messed up, but that is not a problem with the documentation
5. When the spinner goes away, a series of error messages appears.  At the top is:
`Error in /turbo_modules/@angular/compiler@10.0.4/bundles/compiler.umd.js (2921:21)
Template parse errors:
There is no directive with "exportAs" set to "cdkOverlayOrigin" `

**Affected documentation page:** 

https://material.angular.io/cdk/overlay/examples

Tested on Windows 10 Pro, 1803 Build 17134.1550 in browsers:

- Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Firefox 72.0.2 (64-bit)
- Edge Chromium Version 79.0.309.71 (Official build) (64-bit)

Firefox and Edge did not display the messed up spinner on Stackblitz, but had the same error messages.

**Comment by saifabusaleh** [comment]
Looks like `OverlayModule` is missing in `material-module`

Can I take this issue?
i still need to know how to edit `material-module`, as I can't find `DemoMaterialModule` in `src/components-examples/cdk/overlay/cdk-overlay-basic/`

**Comment by jelbourn** [comment]
@saifabusaleh sure, the code lives here: https://github.com/angular/material.angular.io/blob/master/src/assets/stack-blitz/src/app/material-module.ts

**Comment by saifabusaleh** [comment]
@jelbourn Thanks for reply

Created pull request
