### ISSUE TITLE
feat(cdk/testing): include select event to TestElement

### ISSUE THREAD

**Issue by joaqcid** [angular/components#20005]
#### Feature Description

When defining a custom `Harness`, `TestElement` does not include the event `select` to apply on `<select>` elements

#### Use Case

Implementing this event would allow to migrate existing test using `By` to `Harness` and `TestElement`

**Comment by crisbeto** [comment]
Can you post an example of how the event is being bound? I'm not sure that the `select` event makes sense on the `select` element since it's fired when the user marks some text in an input. See https://developer.mozilla.org/en-US/docs/Web/API/Element/select_event

**Comment by joaqcid** [comment]
hi @crisbeto ! 

maybe i didnt make myself clear, what i mean is that when you locate a `<select>` Html Element, there's no method to select an inner option

```
<select id="select_field" //... >
//... options
</select>
```

```
import { ComponentHarness } from '@angular/cdk/testing';

export class SelectFieldComponentHarness extends ComponentHarness {
  static hostSelector = 'select-field';

  getSelect = this.locatorFor('select');

  async selectOption(){
   const el  =  await this.getSelect()
   el. //there's no method to select an option here
  }
}
```

**Comment by crisbeto** [comment]
I think you might be able to do the same with `setInputValue` on the `select` element.

**Comment by jelbourn** [comment]
@joaqcid does clicking the option element not work?

**Comment by KaneFreeman** [comment]
I am having a similar issue. I am trying to figure out how to trigger an `onChange` event for a select. Clicking the select to open, then clicking the desired option does not trigger it.

**Comment by crisbeto** [comment]
I have a feeling that there isn't a way to programmatically select an `option` element and have it emit the `change` event so we might have to simulate it. Before we do, @KaneFreeman can you post an example of what wasn't working for you?

**Comment by joaqcid** [comment]
@crisbeto here's how im currently doing it

```
export const select = (element: HTMLSelectElement, value) => {
  element.value = value;
  element.dispatchEvent(new Event('change'));
};
```

**Comment by KaneFreeman** [comment]
@crisbeto I have a native select with an `(change)` event on it.

```ts
<select (change)="someFunction($event.target.value)">
    <option>Option 1</option>
    <option>Option 2</option>
    <option>Option 3</option>
</select>
```

 I am trying to mimic the setup mentioned in [using-component-harnesses](https://material.angular.io/guide/using-component-harnesses) that you use for `MatSelectHarness` (which I realize is not a native select). In the unit tests I have it click on the `select` then on the `option`. This is not triggering the `change` event.
