### ISSUE TITLE
docs-bug(MatDialog): Deprecated content in documentation

### ISSUE THREAD

**Issue by dzsofa** [angular/components#20007]
#### Documentation Feedback

entryComponents is deprecated since Angular 9 as far as I know (https://angular.io/guide/deprecations#entryComponents), but MatDialog's Overview has a whole section dedicated to configuring content via entryComponents,

**Affected documentation page:** Insert a link to the affected page on material.angular.io

https://material.angular.io/components/dialog/overview

**Comment by crisbeto** [comment]
`entryComponents` are still required for use with ViewEngine which we support. Once it is removed, we'll clean up all references.
