### ISSUE TITLE
bug(MatIcon):Using the class directive with MatIcon has surprising results

### ISSUE THREAD

**Issue by jermowery** [angular/components#20012]
#### Reproduction

https://stackblitz.com/edit/angular-hvp3gk
 
#### Expected Behavior

Using all of the following should **add** a class to MatIcon when used with a MatIcon in a template:

- `ngClass="className"`
- `[ngClass]="''className'"`
- `class="className"`
- `[class]="'className'"`

#### Actual Behavior

What behavior did you actually see?

Using the following on a MatIcon correctly adds the class name "className" to the MatIcon in the DOM:

- `ngClass="className"`
- `[ngClass]="''className'"`
- `class="className"`

However, using `[class]="'className'"` **replaces** the class names added to the MatIcon host element

#### Environment

- Angular: Latest
- CDK/Material: Latest
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by jermowery** [comment]
I think this is widespread across components, I can also replicate this with MatExpansionPanel.
Perhaps this is a bug in Angular itself?

**Comment by jelbourn** [comment]
Yeah, this is a known shortcoming of Angular itself WRT `class` bindings. Closing since this is fixed under ivy.
