### ISSUE TITLE
bug(mat-calendar): The dateClass callback is not called then in month view.

### ISSUE THREAD

**Issue by N-Andronopoulos** [angular/components#20017]
#### Reproduction

Steps to reproduce:
1.  Have a mat-calendar like:
```
              <mat-calendar
                [minDate]="today"
                [maxDate]="serviceMaxDate"
                [dateFilter]="filterDates"
                [dateClass]="classDates"
                [selected]="selectedDate"
                (selectedChange)="selectedDateChanges($event)">
              </mat-calendar>
```
2. Select -> years (on top) -> select a year -> then dateFilter is called (for all year dates) but the dateClass is not. So I don't get css classes on months cells.  
 
 
#### Expected Behavior

I should be able to put css classes on month cells just like the days cells.

#### Actual Behavior

Only while in date view the dateClass callback is called for all month days.

#### Environment

- Angular: 9
- CDK/Material: 9.2.4,
- Browser(s): Chrome 83+
- Operating System: Windows 10

**Comment by jelbourn** [comment]
@N-Andronopoulos can you share a stackblitz that demonstrates this issue?

**Comment by crisbeto** [comment]
I think that this is working as expected. The name implies that it'll be called only on date cells, rather than month or year cells from the other views.

**Comment by N-Andronopoulos** [comment]
I think its logical to be used as I describe it since `filterDates` works in year view and there isn't an other way to put classes in year view. If it's implied that `filterDates` shouldn't work then and we should have a `filterMonth`/`classMonth` callbacks, but I think that's a waste of interface space. Year view (where you pick a month) should call `classDates` like it calls `filterDates` for all 365 days of the year.

**Comment by crisbeto** [comment]
That's fair. I think that we might need to pass in the name of the current view to the callback too, otherwise there won't be a way to distinguish the first date of a month from the cell representing that month.
