### ISSUE TITLE
feat(mat-selection-list): Allow deselecting elements when multiple=False 

### ISSUE THREAD

**Issue by rhofour** [angular/components#20036]
#### Feature Description

I'd like to have a mat-selection-list where up to one element can be selected. Currently the list when multiple is set to false, the list can start with no selection, but as soon as an item is selected it will always have exactly one selection. I'd like to propose adding another toggle which controls if items can be deselected or not.

I can easily write up the trivial code here, I'm just not sure what an acceptable name for the property would be. allowToggling could work, but it might be confusing for the multiple selection lists where presumably it shouldn't take effect.

**Comment by cbejensen** [comment]
I would also appreciate some way to change this functionality. Seems like you could just alter the logic of this function, which currently prevents toggling if the option is already selected (if I am reading this right - haven't tested):

https://github.com/angular/components/blob/0911820f90d2262eea9ce2e92c0984b03db4a690/src/material/list/selection-list.ts#L268-L270

**Comment by mmalerba** [comment]
After discussing this with some a11y experts, we concluded that this pattern would likely be unexpected & confusing to screen reader users. Better patterns for this use case would be an option representing nothing selected, a button to reset the selection, or potentially a different interaction pattern entirely (depending on the particular use case). Given that conclusion, I'm going to close this issue
