### ISSUE TITLE
Default range selection in inline date picker

### ISSUE THREAD

**Issue by tshakeel18** [angular/components#20039]
I have to use inline date picker with no input linked to it, same like you have in your demo link but here I am unable to property for passing date range as default range, output is fine but unable to locate Input for date range like 'begin' and 'end' value, there is property named as selected but that is just for single date.

**Comment by crisbeto** [comment]
What do you mean by using it inline? Are you using `mat-calendar` directly or `mat-datepicker`? It would be useful to see what your markup looks like.

**Comment by tshakeel18** [comment]
> What do you mean by using it inline? Are you using `mat-calendar` directly or `mat-datepicker`? It would be useful to see what your markup looks like.


```
<div class="inlineCalenderContainer"> 
    <sat-calender [rangeMode]="true" (dateRangesChange)="inlineRangeChange($event)" [selected]="selectedDate"> 
    </sat-calender>
</div>
```
This is the exact code available in your demo.
