### ISSUE TITLE
bug(WEBSITE): Angular Material website CSS bug

### ISSUE THREAD

**Issue by besimgurbuz** [angular/components#20049]
## Angular Material's website CSS bug
![image](https://user-images.githubusercontent.com/33575384/87993808-259b7f00-caf4-11ea-9863-996057ce6b0d.png)

[Detected in this page]( https://material.angular.io/guide/schematics)
 
#### Expected Behavior

Footer should be at the bottom

#### Actual Behavior

Footer at the center of the website

**Comment by crisbeto** [comment]
Looks like I broke this in https://github.com/angular/material.angular.io/pull/834. It'll be fixed by https://github.com/angular/material.angular.io/pull/839.
