### ISSUE TITLE
feat(drag-drop): Custom drag preview insertion location

### ISSUE THREAD

**Issue by Achilles1515** [angular/components#20055]
#### Feature Description

Drag preview DOM insertion location is currently the document body or fullscreen element.

```ts
/** Gets the element into which the drag preview should be inserted. */
function getPreviewInsertionPoint(documentRef: any): HTMLElement {
  // We can't use the body if the user is in fullscreen mode,
  // because the preview will render under the fullscreen element.
  // TODO(crisbeto): dedupe this with the `FullscreenOverlayContainer` eventually.
  return documentRef.fullscreenElement ||
         documentRef.webkitFullscreenElement ||
         documentRef.mozFullScreenElement ||
         documentRef.msFullscreenElement ||
         documentRef.body;
}
```

...which is being used here:
```ts
  /** Starts the dragging sequence. */
  private _startDragSequence(event: MouseEvent | TouchEvent) {
    // ...
    const dropContainer = this._dropContainer;

    if (dropContainer) {
      // ...
      const preview = this._preview = this._createPreviewElement();
      // ...
      getPreviewInsertionPoint(this._document).appendChild(preview);
      // ...
    } else {
      // ...
    }
  // ...
  }
```

It would be nice to have an `@Input() previewInsertionPoint: ElementRef | HTMLElement` for the `CdkDropList` directive to specify a custom location, other than the document body, to append the preview element.

The above code would then change to something like:
```ts
  /** Starts the dragging sequence. */
  private _startDragSequence(event: MouseEvent | TouchEvent) {
    // ...
    const dropContainer = this._dropContainer;

    if (dropContainer) {
      // ...
      const preview = this._preview = this._createPreviewElement();
      // getPreviewInsertionPoint(this._document).appendChild(preview);
      const previewInsertionPoint = dropContainer.previewInsertionPoint ? coerceElement(dropContainer.previewInsertionPoint) : getPreviewInsertionPoint(this._document);
      previewInsertionPoint.appendChild(preview);
      // ...
    } else {
      // ...
    }
  // ...
  }
```

#### Use Case

A custom preview insertion location will allow for more advanced stacking/ordering layouts and styling. I have a specific use case with a drop list + boundary element, where I **always** want the drag items to be rendered under certain surrounding elements. When the drop list is sitting statically, it looks fine. But when I start dragging, the preview is rendered above everything else - which is okay for a lot of drag and drop scenarios but not mine.

Consider drop shadow CSS styling. The drop shadow can visually extend beyond the drag boundary, while the element itself is still contained inside the drag boundary. As stated above, when the list and drag items are sitting statically, the drop shadow extending beyond the drag boundary is being hidden by the ordering/z-index/styling of other elements (which is what I want). The moment the preview element (w/ drop shadow applied) becomes active, it's drop shadow is completely visible and extending outside of the drag boundary and there is nothing I can do about it because the preview element is in a completely different DOM location (bottom of document body, on top of everything) nowhere near the drop list and it's neighboring elements.

Let me know if you need anymore info.

Also, a public `dragRef.getPlaceholderElement()` method exists. Can a public `dragRef.getPreviewElement()` method also be added to allow accessing the preview element during hooks/events?

**Comment by crisbeto** [comment]
I believe this is covered by https://github.com/angular/components/issues/13288. Also we recently talked about what the API for this should look like and we ended up on something very similar (ignore the naming):

```
@Input() cdkDragPreviewContainer: 'global' | 'in-place' | 'parent' | HTMLElement
```

**Comment by Achilles1515** [comment]
> I believe this is covered by #13288. Also we recently talked about what the API for this should look like and we ended up on something very similar (ignore the naming):
> 
> ```
> @Input() cdkDragPreviewContainer: 'global' | 'in-place' | 'parent' | HTMLElement
> ```

Great. Looks like that will work.
