### ISSUE TITLE
bug(MatCheckbox): Missing animation from indeterminate to checked 

### ISSUE THREAD

**Issue by troncomputers** [angular/components#20066]
#### Reproduction

[Missing animation from indeterminate to checked - stackbliz](https://stackblitz.com/edit/angular-ivy-nnr72p)
 
#### Expected Behavior

Check icon should animate every time when status/state is changed from indeterminate to checked.

#### Actual Behavior

If first, initial value of status is indeterminate the spinnig animation is working fine. At the second attempt, changing from indeterminate to checked, the box is strangely blinking and there is no spinning animation.

#### Environment

```
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.3
Node: 12.15.0
OS: win32 x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cdk                      10.1.0
@angular/cli                      10.0.3
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.1.0
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.6.0
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by phongca22** [comment]
It also occurs on Angular 9.1.11 and Angular Material 9.2.4

**Comment by phongca22** [comment]
It also occurs in Angular 9.1.11 and Angular Material 9.2.4

**Comment by troncomputers** [comment]
Is this going to be fixed soon? So many versions has been released and nothing changed. Should I use "Experimental"? What is it?

**Comment by FredericGryspeerdt** [comment]
Any updates on this? We experience the same behavior in Angular 10.2.3 and Angular Material 10.2.3.

**Comment by amysorto** [comment]
This animation behavior is fixed in the new MDC based checkbox component coming soon in v15.
