### ISSUE TITLE
Mat-checkbox get/set custom string value instead of bool in reactive form

### ISSUE THREAD

**Issue by sankirna** [angular/components#20067]
#### Feature Description

Mat-checkbox get/set custom string value instead of bool in reactive form. It would be good if have api reference so we can avoid casing and event subscribe 

#### Use Case

Describe the use case(s) that the proposed feature would enable.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
