### ISSUE TITLE
feat(stepper): Ability to display errors on steps that had no interaction

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#20068]
### Feature Description

I want to be able to trigger the step error manualy (changing the state of the step).

### Use Case

In a non-linear stepper, I can go to the last step, ignoring some steps (no interaction), and could submit my data even though the form (related with the uninterected step) is invalid.

### Reproduction 
https://stackblitz.com/edit/angular-cxdumw

1) Click on the 3th step
2) Click on the 4th step
3) Click on Save

#### Current bahavior
![image](https://user-images.githubusercontent.com/12090931/88175862-d55c1400-cbfc-11ea-9cfa-cabd67ee208d.png)

#### Expected behavior
![image](https://user-images.githubusercontent.com/12090931/88176058-1fdd9080-cbfd-11ea-9762-cc89a1382877.png)

### Observation
As a workaround to get my desired behavior, you can uncomment the `save()` function content and try the reproduction steps from above again.

`this.matStepper.steps.forEach(x => x.select());`

This way the [interacted property](https://github.com/angular/components/blob/cc1e0fe5964a23eeb4a68e9d090539cb9cdcc04b/tools/public_api_guard/cdk/stepper.d.ts#L15) is set to true, and error state is displayed.

**Comment by paulferaud** [comment]
See also #20215 

> As a workaround to get my desired behavior, you can uncomment the `save()` function content and try the reproduction steps from above again.
> 
> `this.matStepper.steps.forEach(x => x.select());`

FWIW, `this.matStepper.steps.forEach(x => x.interacted = true);` seems to also work for me, and does not come with the overhead of “stepping” through everything.
