### ISSUE TITLE
bug(mat-form-field): mat-prefix / suffix are misaligned on Firefox and Chrome for outline appearance

### ISSUE THREAD

**Issue by jadengis** [angular/components#20074]
#### Reproduction
https://stackblitz.com/edit/angular-v1zbur?file=src%2Fapp%2Fform-field-prefix-suffix-example.html

This stackblitz repro is forked from an example in the component showcase at https://material.angular.io/components/form-field/overview
Screenshot of behaviour on Firefox:
![Screenshot from 2020-07-22 19-43-56](https://user-images.githubusercontent.com/13421336/88240367-e59fdd80-cc54-11ea-9cd1-71e861391a68.png)
 
#### Expected Behavior
- mat-icon-button's in the mat-prefix of suffix should be centered vertically with respect to the border of the outline form field
- Text in the mat prefix or suffix should be aligned with the input text baseline

#### Actual Behavior
- on Firefox, the mat-icon-button prefix / suffix is rendered high of center
- on Firefox and Chrome, the text prefix / suffix is rendered lower than the text input baseline

#### Environment

- Angular: 10 (experienced in 9 as well)
- CDK/Material: 10.1.0 (I experienced this in 9 as well)
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

### Addendum
I wrote a style hack that solved the issue with the text prefix/suffix alignment issue for my. I will include it here in case it sheds some light on the issue.
```
// A style hack to fix the appearance of prefixes and suffixes on outline form
// fields that aren't a mat-icon-button.
.mat-form-field-appearance-outline {
  .mat-form-field-prefix,
  .mat-form-field-suffix {
    top: 0 !important;

    & > .mat-icon-button {
      top: 0.25em;
    }
  }
```

**Comment by AlexElin** [comment]
This issue is similar to https://github.com/angular/components/issues/12803

**Comment by amysorto** [comment]
I tested this on Firefox with the new MDC based components (now in v15!) and the the icons and text are aligned correctly now.
