### ISSUE TITLE
BrowserAnimationsModule not added to app,module.ts

### ISSUE THREAD

**Issue by cliffeby** [angular/components#20070]
Console errors showed BrowserAnimationsModule was not added to app.module.ts.  Manual addition of import solved the error reporting issue.
 
I used npm i @angular/cdk rather than the suggested npm add.

#### Environment

- Angular: 10
-Angular/cli: 10.0.3
- CDK/Material:10.1.0
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
Just installing the library won't modify your code at all. Only running an `ng add` schematic will do that.

**Comment by cliffeby** [comment]
Thanks.  I added the schematic, but installed the cdk.
