### ISSUE TITLE
Entry accelerators for Datepicker 

### ISSUE THREAD

**Issue by Jadamae77** [angular/components#20078]
I am working on a web application using Angular. Is there a way to add shortcuts/accelerators to the date input? For example, a user should be able to type "+1" and have the input resolve to tomorrow's date. At the very least I would like to be able to set an input of "6-18" to 6-18-2020 instead of 6-18-2001. Thank you!

**Comment by jelbourn** [comment]
You could potentially add a custom directive on the text input, but there's nothing like this built in (and no plans to add anything similar).

**Comment by Jadamae77** [comment]
Thank you, I will look into that.
