### ISSUE TITLE
docs-bug(Table): Table examples don't fit the screen

### ISSUE THREAD

**Issue by DenysVuika** [angular/components#20081]
#### Documentation Feedback

All `Table` examples go off the screen horizontally.

You can check the issue here:
https://material.angular.io/components/table/examples

version: 10.1.0

**Comment by crisbeto** [comment]
Probably a general issue with the docs site layout since it shouldn't be allowed to stretch that much to begin with, no matter what content it has.

**Comment by wagnermaciel** [comment]
@crisbeto Correct me if I'm wrong but this issue seems to have been resolved.

**Comment by crisbeto** [comment]
Yes, I don't see it stretching anymore. Closing.
