### ISSUE TITLE
[Tabs] Prevent user from activating/deactivating tabs

### ISSUE THREAD

**Issue by Daeluse** [angular/components#2008]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Following a similar function to how canActivate and canDeactivate works on Routing, it would be extremely beneficial to have a way to run a check before allowing a tab to be activated or deactivated.

#### What is the use-case or motivation for changing an existing behavior?
Within the tabs, if a user is able to change a setting or edit information and the user is required to click 'save' before the changes are committed, there should be a way to prompt the user of the existing changes before they can navigate away, by switching tabs or routes. The necessity here would be that we would need a way to check both on tab switch and route switch without (hopefully) having to duplicate code.

**Comment by finalxcode** [comment]
+1

**Comment by PhilHuot** [comment]
Would be really nice to have.

**Comment by crisbeto** [comment]
This is possible already using the `disabled` input on `mat-tab` and `mat-tab-link`. There's an example in the docs as well: https://material.angular.io/components/tabs/examples#tab-nav-bar-basic
