### ISSUE TITLE
mat-error doesnt work in mat-date-range-picker

### ISSUE THREAD

**Issue by SamuelSchwienbacher** [angular/components#20115]
## Bug, enhancement request, or proposal
Bug

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  https://stackblitz.com/angular/oaraqppyjoo?file=src%2Fapp%2Fdate-range-picker-forms-example.ts

#### Detailed Reproduction Steps
1. enter an invalid date

### Explain the expected behavior
Error message should be shown (mat-error)

### Explain the current behavior
Field only gets red

### Discuss the use-case or motivation for changing the existing behavior
Errors on date range picker are a must

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 9.0.7
- AngularJS Material: 10.0.1
- OS: Windows 10
- Browsers: Chrome
 
#### Stack Trace
```

```

**Comment by crisbeto** [comment]
The name of the error is `matDatepickerParse`, not `matStartDateInvalid` or `matEndDateInvalid`. If you swap it out in your `ngIf` it should work.
