### ISSUE TITLE
help(select): is possible to customise the panel position in multiple selection?

### ISSUE THREAD

**Issue by x1c0** [angular/components#20126]
#### What are you trying to do?

I would like to know if is possible to shrink the options panel to fit the input width when we have selection multiple:

actual:
![image](https://user-images.githubusercontent.com/2421483/88826572-31a8d000-d1c9-11ea-9457-8d5a05a11bc4.png)

desired:
![image](https://user-images.githubusercontent.com/2421483/88826997-ad0a8180-d1c9-11ea-87a9-2ea22edc5927.png)

Thank you in advance!

#### Environment

- Angular: 9.2.4
- CDK/Material: 9.2.4
- Browser(s): Chrome 
- Operating System: macOS

**Comment by wagnermaciel** [comment]
Hi @x1c0 ! We do not support resizing the options panel at this time.
