### ISSUE TITLE
mat-tab-group with mat-select, forms input fields disappear while mouse hover over the form in Safari

### ISSUE THREAD

**Issue by nolafs** [angular/components#20121]
#### Reproduction

Steps to reproduce:
1. Create a tab group with two sections
2. Add mat-select component to each tab
3. Safari only, open tab and rollover the controls and they will flicker in and out, only the underline of select component is visible

 
 
#### Expected Behavior

The form is perfectly fine in Chrome but in Safari the mat-select causes to remove the nested form in tabs.

#### Actual Behavior

Safari, the forms within the tab, all content disappears while the mouse is moving over the form.

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I tried reproducing it inside our dev app and on Stackblitz, but I wasn't able to against Safari 13. It sounds like there might be something else in your app that's influencing it. For reference, here's what I tried https://stackblitz.com/edit/angular-a572vw.

**Comment by EmmieAndreas** [comment]
im having the same problem only in chrome but on all inputs and buttons inside mat-expansion after upgrading to Angular 10 (10.0.5)

Works fine on 9.0.6
Unable to reproduce on simple example of my code on stackblitz
I will keep this updated

**Comment by zarend** [comment]
Hello @nolafs,

Thank you for reporting this issue. Unfortunately we are not able to take action if we cannot reproduce it. This might have already been fixed. If the issue persists, please provide reproduction steps or file a new issue report.

- Zach
