### ISSUE TITLE
help(mat-chips): Selectable property seems to not work

### ISSUE THREAD

**Issue by veronesecoms** [angular/components#20127]
#### What are you trying to do?
I'm trying to disable the selection of a mat-chip, only abling the click in the "remove" icon.
#### What troubleshooting steps have you tried?
I set the property "selectable" as false, but seems to nothing changes happens.
#### What are you seeing that does not match your expectations? 
My expectation is that when i set the property "selectable" as false, i can't click in the chip, removing the effect selectable.
When i set this component with "disabled" property this work, but i think the disabled property is not semantic in this case... 
#### Reproduction
[Stackblitz reprodution](https://stackblitz.com/edit/angular-kjwtmj)

Steps to reproduce:
1. Click in the chips
2. You will see a "selectable" effect

**Comment by jelbourn** [comment]
What you're seeing isn't chip selection, it's the chip's focus state. The selection makes the chip a different color:
https://stackblitz.com/edit/angular-kjwtmj-zw35ql?file=src%2Fapp%2Fchips-autocomplete-example.html
