### ISSUE TITLE
help(drag-and-drop): How to use connectedTo with id's

### ISSUE THREAD

**Issue by muuvmuuv** [angular/components#20139]
#### What are you trying to do?

I would like to move a node from one area to another but using id's.

#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? 

#### Reproduction

~~https://stackblitz.com/edit/angular-39ghcm?file=src%2Fapp%2Fcdk-drag-drop-connected-sorting-example.html~~
https://github.com/muuvmuuv/angular-issue-20139

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
What is the issue here? The linked Stackblitz seems to be working.

**Comment by muuvmuuv** [comment]
Appears it works one first load. Maybe a cached version from the fork. Edit something in the HTML @crisbeto

**Comment by crisbeto** [comment]
Hmm this is odd. It stops being connected if I edit something as you said, but if I refresh the view afterwards it starts working again.

**Comment by muuvmuuv** [comment]
Yes. And even more strange is that In my local project it does not even work on first load.

**Comment by crisbeto** [comment]
Do you have to do anything specific for it not to work in your project, or is it broken as soon as you land on the page? I think the Stackblitz breaks, because of the way it does hot reloading which prevents some lifecycle hooks from being destroyed, but that shouldn't be a problem in a real project.

Also have you tried connecting the two drop list with `cdkDropListGroup`?

```
<div cdkDropListGroup>
  <div cdkDropList></div>
  <div cdkDropList></div>
</div>
```

**Comment by muuvmuuv** [comment]
Yes but this only works in the demo not in my app since I create those lists dynamically. Maybe this is the issue that I create them dynamically.

**Comment by muuvmuuv** [comment]
Here is the current version: https://github.com/muuvmuuv/angular-ivy-fyo19q

**Comment by muuvmuuv** [comment]
No it is working. I just had an issue with the dataSource object.
