### ISSUE TITLE
Static Drag and Drop PlaceHolder Feature Requesting

### ISSUE THREAD

**Issue by akpmohan07** [angular/components#20137]
As the currently available placeholder is created only the item is dragged.
Where the requested is static and seperate placeholder element where items can be dragged!..

[Stackoverflow](https://stackoverflow.com/questions/54549461/how-to-use-a-placeholder-for-angular-material-7-drag-and-drop)

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
