### ISSUE TITLE
feat(dialog): Ability to scroll body instead of dialog content

### ISSUE THREAD

**Issue by ingljo** [angular/components#20138]
#### Feature Description

It would be nice to have an option to scroll body instead of the dialog content.
If you scroll the body, the browser address bar get automatically hidden on mobile devices and creates a better user experience.

Example from material-ui (scroll=body):
https://material-ui.com/components/dialogs/#scrolling-long-content

Example from bootstrap modal:
https://getbootstrap.com/docs/4.0/components/modal/#scrolling-long-content

#### Use Case
Any dialog with long content

**Comment by morki** [comment]
We don't use Material but custom framework built on CDK, so I tried to implement this on top of CDK, but I was not successfull. I think whole Overlay module and scrolling strategies is not designed for this use case, but maybe I just misinterpret it.

**Comment by evil-shrike** [comment]
+100 
it's a must-have feature.
Currently putting long content in MatDialog is quite problematic. Built-in mat-dialog-content is a toy with its fixed height (who needs it?). And it's not only about putting long content in dialogs, it's about different heights of browser windows, just normal usability - I believe if dialog isn't fitting in the window there should be scrolling by default.
I can imagine two approaches: scroll window and scroll dialog. The former is more preferable. But any scrolling is much better that nothing as now.
I tried specifying overflow for cdk-overlay-pane element:
```
.cdk-overlay-pane {
  overflow-y: auto;
}
```
but it affects other overlay, for example creates ugly scrolling in mat-select:
![image](https://user-images.githubusercontent.com/1203230/113014862-a6cc0b00-9185-11eb-8ca6-4be8e69253b0.png)

**Comment by evil-shrike** [comment]
There was a very similar request #14377 but it's closed and locked with pretty controversial reasoning:

>I don't think this really makes sense for the dialog. The dialog is supposed to be a modal popup that blocks interaction with the rest of the page, including scrolling. You might be able to make something for your use case using the CDK overlay which the dialog is based on 

The fact that dialog is a popup doesn't mean that usability should suffer and users shouldn't be able to see all content. It's perfectly normal to have dialog with scrolling. Just look at real-life-proved [scrollable dialogs in Bootstrap](https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content).

**Comment by wagnermaciel** [comment]
Hi all, unfortunately the scrolling behavior outlined by the [material design spec](https://material.io/components/dialogs#behavior) is very specific in this case 


> Most dialog content should avoid scrolling. When scrolling is required, the dialog title is pinned at the top, with buttons pinned at the bottom. This ensures selected content remains visible alongside the title and buttons, even upon scroll.

@evil-shrike I'm not sure if I'm understanding what you meant when you said `usability should suffer and users shouldn't be able to see all content. It's perfectly normal to have dialog with scrolling`, but dialogs can still have scrollable content, you just cannot scroll title and buttons at the bottom (as per the material design spec) - [see the examples on our docs site](https://material.angular.io/components/dialog/examples)
