### ISSUE TITLE
bug(table-data-source): Sorting of a string column/property breaks if one record contains a number only

### ISSUE THREAD

**Issue by stnor** [angular/components#20140]
#### Reproduction
[edit, thanks @jelbourn]
https://stackblitz.com/edit/angular-xpwhup?file=src/app/table-sorting-example.ts
 
#### Expected Behavior
The sorting of strings should work as one expects when values are strings.

#### Actual Behavior
The sortingDataAccessor won't sort a string column correctly if one or more records contain a number only eg '1'.

Ex: ['One' ,'2', 'Three']

#### Suggested change
Use typeof value === 'number' instead of _isNumberValue perhaps, or something more elaborate?

#### Environment

- Angular: 10
- CDK/Material:10

**Comment by jelbourn** [comment]
Reproduction: https://stackblitz.com/edit/angular-xpwhup?file=src/app/table-sorting-example.ts

Confirmed that this happens and that it's weird

**Comment by Hugoer** [comment]
Hi! I could try to take care of myself. The solution I propose is to compare the data type after the call to _isNumberValue, if one of them is numeric and the other string, it would convert the numeric value to string, so if both are numeric the sort by number would be kept (faster ) and if not it would be ordered by text. I did a test on the stackblitz mentioned by jelbourn and it would work

**Comment by jelbourn** [comment]
@andrewseguin thoughts?

**Comment by sahilmore-git** [comment]
fix(material/table): Sorting of a string column/property breaks if one record contains a number only 

If the number is a string and in between strings we treat it as a number and group it at the start/end of the table based on it's ascending or descending. I have [fixed the issue in my commit here](https://github.com/sahilmore-git/components/commit/42bacec862d02118557b01fcc19cbcde6079661b) and I think it will work properly.

Fixes #20140

**Comment by sahilmore-git** [comment]
@jelbourn Please correct me if I am wrong.

**Comment by sahilmore-git** [comment]
@stnor any views ??

**Comment by stnor** [comment]
LGTM

**Comment by Solonel** [comment]
Hello, I still have the issue on Angular 13.3.3, value **058233665663** is not place well
Example on mat table that didn't work :
https://stackblitz.com/edit/angular-mw3b1x?file=src/app/table-basic-example.html
Example with sort header that work :
https://stackblitz.com/edit/angular-fsdnz2?file=src/app/sort-overview-example.ts

**Comment by viniciusschuelter** [comment]
I probably fixed that https://github.com/angular/components/pull/25444, @andrewseguin @crisbeto can u take a look?
