### ISSUE TITLE
docs-bug(Tabs): Example fails to load

### ISSUE THREAD

**Issue by DenysVuika** [angular/components#20141]
#### Documentation Feedback

One of the Tabs examples is missing:

```
Failed to load document: /docs-content/examples-highlighted/material/tabs/tab-group-basic/tab-group-basic-html.html. Error: OK
```

<img width="1109" alt="Screenshot 2020-07-30 at 14 15 48" src="https://user-images.githubusercontent.com/503991/88927546-7d15b980-d26f-11ea-96f8-4a751b05522f.png">

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/components/tabs/overview

**Comment by crisbeto** [comment]
Will be fixed in #20142. Until it is released, the source of the example can be seen here: https://github.com/angular/components/tree/master/src/components-examples/material/tabs/tab-group-basic.
