### ISSUE TITLE
bug(MatProgressSpinner): Progress spinner circle expands beyond the specified diameter

### ISSUE THREAD

**Issue by AlexLangdon** [angular/components#20159]
#### Reproduction

Create a progress spinner with a stroke width greater than 10.

https://stackblitz.com/edit/components-issue-hjmhk7?file=src%2Fapp%2Fexample-component.html
 
#### Expected Behavior

The spinner circle should remain within the specified diameter as with the parent progress-spinner element.

#### Actual Behavior

The spinner circle expands outside its parent progress-spinner element and beyond the specified diameter. The circle will continue to expand as the stroke width is increased, potentially overlapping adjacent components.

![image](https://user-images.githubusercontent.com/8414922/89133337-e79a5400-d512-11ea-804b-58631b3eddda.png)

#### Notes

This is related to the way the circle radius is calculated here:

https://github.com/angular/components/blob/294b8ee3c969e0550238ccbe8df1722c1c4e9318/src/material/progress-spinner/progress-spinner.ts#L233-L235

Subtracting a `STROKE_WIDTH` constant of 10 means that the circle element will only have the correct size when the spinner stroke width is 10. 

#### Related Issues

#19469 - The use of STROKE_WIDTH in the radius calculation also prevents progress spinners of diameter <= 10 from being shown.

Opening this issue based on discussion in a related PR https://github.com/angular/components/pull/20062

#### Environment

Environment
Angular: 10.0.7
CDK/Material: 10.1.1
Browser(s): Google Chrome Version 84.0.4147.105
Operating System: Windows 10 version 1909

**Comment by mmalerba** [comment]
This is fixed using the new MDC-based progress spinner in version 15: https://stackblitz.com/edit/angular-dwqxqp
