### ISSUE TITLE
slider: not sliding anymore after the version 9.2.0 with Capacitor JS

### ISSUE THREAD

**Issue by tototares** [angular/components#20162]
## Bug 

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  https://material.angular.io/components/slider/overview 

#### Detailed Reproduction Steps
1. Install Capacitor from https://capacitorjs.com/ 
2. Install Angular Material in Version 9.2.1
3. Try to slide the slider on a mobile (android or iOS) device

### Explain the expected behavior
Slider should slide

### Explain the current behavior
Slider doesn't slide

### Discuss the use-case or motivation for changing the existing behavior
In Version 9.2.0 everything works fine, after the update it's not working anymore. I guess this commit caused the issue: angular/components@ca3c68f

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 10.0.7
- AngularJS Material: > 9.2.0
- OS: android and iOS
- Browsers: Capacitor JS

**Comment by jelbourn** [comment]
@crisbeto is there a strong reason to not listen on body instead of `document` for slider?

**Comment by Michael-Doner** [comment]
Hey @crisbeto, can I support you here? :) Thanks in advance.

**Comment by amysorto** [comment]
I can't reproduce this behavior for the legacy slider in v14 or the new MDC based slider component (which is available as of v15) on Chrome on an iOS device.
