### ISSUE TITLE
feat(cdk/scrolling): ScrollToIndex function

### ISSUE THREAD

**Issue by Akxe** [angular/components#20161]
## Feature Description

A function that would scroll to an element/item rather than to offset would be much appreciated, as now the developer must implement logic to calculate offset based on his understanding of the scrolling module.

## Use Case
To streamline developer experience of scrolling to element. This will also be essential once #10113 will be implemented.

## Possible functions
* ~~`scrollItemIntoView`~~
* `scrollIndexIntoView`

Pass the item in the collection to scroll to. Type of function would mirror [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

The types would be:
```ts
/**
Interface already in TS
interface scrollIntoViewOptions {
  behavior?:  'auto' | 'smooth';
  block?:  'start' | 'end' | 'center' | 'nearest';
  inline?:  'start' | 'end' | 'center' | 'nearest';
}
*/
function scrollIndexIntoView(
  index: number, 
  options?: scrollIntoViewOptions,
)
```

**Comment by crisbeto** [comment]
I think the index method makes sense, but I'm not sure about passing in an element. By definition virtual scrolling doesn't keep all elements in the DOM at the same time so you wouldn't be able to get a hold of an element outside the viewport anyway.

**Comment by Akxe** [comment]
@crisbeto There is no function that involves `HTMLElement`, there is one for item. It is basically the same as index, but you need to do `list.indexOf(item)` with it first...

**Comment by crisbeto** [comment]
The description and title talk about an element in "A function that would scroll to an element". IMO it should only be an index since it keeps the API surface smaller and the `indexOf` call is trivial to add yourself.

**Comment by Akxe** [comment]
Wrong title I suppose. The `item` function can be left unimplemented. I was at first mirroring the native API.

**Comment by Akxe** [comment]
EDITed: Proposition to not contain `scrollItemIntoView`.

**Comment by Akxe** [comment]
@crisbeto I have tried to create `scrollIndexIntoViewIfNeeded`, but I hit a problem. I don't seem to be able to recognize if the index (, or its element) is within the visible viewport.

```ts
const viewPort: CdkVirtualScrollViewport;

scrollToIndex(index: number): void {
	const range = viewPort.getRenderedRange();

	if (range.start > index || range.end < index) {
		// Scroll is 100% needed.
		viewPort.scrollToIndex(index, 'auto');
	} else {
		// The index is within range, but not necessarily within visible viewport!
	}
}
```

A function `this.viewPort.getViewportRange()`, is needed to be able to consistently scroll to element in list. It would also allow me to scroll the element to the middle of the list instead of start.
