### ISSUE TITLE
bug(bidi): latest 10.1.2 fail to compile due module resolution

### ISSUE THREAD

**Issue by Delagen** [angular/components#20179]
#### Expected Behavior

What behavior were you expecting to see?
In version 10.1.1
In NPM package `@angular\cdk\esm2015\bidi\directionality.js`
```
import * as i1 from "./dir-document-token";
```
Which resolve correctly

#### Actual Behavior

What behavior did you actually see?
In NPM package `@angular\cdk\esm2015\bidi\directionality.js`
```
import * as i1 from "@angular/cdk/bidi/dir-document-token";
```
which does not resolve

#### Environment

- Angular: 10.0.7
- CDK/Material: Specified above
- Browser(s): does not affected
- Operating System (e.g. Windows, macOS, Ubuntu):  does not affected

**Comment by crisbeto** [comment]
This code hasn't changed in a long time so it's probably something related to the build.

**Comment by Delagen** [comment]
@crisbeto I think the same. Look at this file history. No changes for last version

**Comment by devversion** [comment]
Interestingly it doesn't show up in [the snapshot builds](https://github.com/angular/cdk-builds/blob/master/esm2015/bidi/directionality.js#L11). On NPM it looks like the last two patch releases are fine, but the release from yesterday (i.e. `v10.1.2` has the incorrect import again).

**Comment by devversion** [comment]
Looked into it. It's a bug that happens with the `@bazel/typescript` workers. That also explains why it only surfaces in a few releases, while others are good. The issue surfaces when one built e.g. the CDK package in devmode before building the NPM packages in prodmode.

The TypeScript worker caches the AMD/UMD module name for the `dir-document-token` file in the devmode compilation. In prodmode, the AMD/UMD module names are re-used from the devmode compilation. This causes the Angular compilation to output differently/unexpectedly as the `dir-document-token` file has an explicit AMD/UMD name that the Angular compiler uses to refer to the file (when compiling the `@Injectable` definition in directionality).

**Comment by devversion** [comment]
@Delagen Out of curiosity: Do you have a custom build pipeline? This is a valid issue. Thanks for reporting it! I'm just wondering how you are affected by this. Angular CLI projects by default use the `fesm2015` output that is not affected by this issue.

**Comment by devversion** [comment]
Proposed fix: https://github.com/bazelbuild/rules_typescript/pull/504. I'm going to wait how difficult it will be to get this merged. Otherwise we'll just patch this change into this repository and into `rules_nodejs` (like they already do for other changes).
