### ISSUE TITLE
Option's panel doesn't position/aligned with mat-select for some last options

### ISSUE THREAD

**Issue by amitjain2609** [angular/components#20174]
If a mat-select is placed at the bottom side of the screen then it's getting offsetY value which is moving the vertical position of the option's panel and is not aligned with the position of the drop down itself.

Repro steps:
1. Select a value "Tomato" or below from the dropdown.
2. Click on drop down again to open the option's panel.
3. Option's panel is not aligned with the drop down. 

Actual alignment:
![image](https://user-images.githubusercontent.com/19508824/89236150-aa7ea200-d5a4-11ea-8925-b65062a9f236.png)

Expected alignment:
![image](https://user-images.githubusercontent.com/19508824/89235986-33490e00-d5a4-11ea-9190-8caa547d189b.png)

Stackblitz repro:
https://stackblitz.com/edit/mat-select-bug-uc8m2c?file=src%2Fapp%2Fmat-select-bug.html

Angular: 10.0.0

**Comment by crisbeto** [comment]
I believe this is the same issue as https://github.com/angular/components/issues/19620.
