### ISSUE TITLE
bug(badge): a component use badge while the component is setted "overflow:hidden" , the badge will be hidden ,too. But I want to see the badge display completely

### ISSUE THREAD

**Issue by zcg8633** [angular/components#20196]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://stackblitz.com/edit/components-issue-h6kvyc?file=src%2Fapp%2Fexample-component.html

![image](https://user-images.githubusercontent.com/44219901/89376193-eb4ff580-d721-11ea-89f4-1f28420b0f99.png)

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
This is working as intended; a badge can only render when its attached element is visible.
