### ISSUE TITLE
bug(MatMenuItem): If a <span> or any other node is used in the Item label, getLabel() doesn't work

### ISSUE THREAD

**Issue by cdavidnt** [angular/components#20200]
#### Reproduction

https://stackblitz.com/edit/components-issue-vpdbyy?embed=1&file=src/app/example-component.html

Steps to reproduce:
1. Create a list of mat-menu-items
2. Use a custom node in one of them (<span> for example) to style the item
3. Use MatMenuItem.getLabel()
 
 
#### Expected Behavior

What behavior were you expecting to see?
item.getLabel() would work to get the label text contents of the mat-menu-item, regardless if they're in nested nodes.

#### Actual Behavior

What behavior did you actually see?
item.getLabel() only works if the component is specifically a text node and does not recurse into nested nodes:
https://github.com/angular/components/blob/master/src/material/menu/menu-item.ts#L177

#### Environment

- Angular: 10.0.3
- CDK/Material: 10.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by jelbourn** [comment]
We do have a solution for this in the experimental cdk menu:
https://github.com/angular/components/blob/cdbf2c18103ef71077f87ae9e86b74e50cc2fd2c/src/cdk-experimental/menu/menu-item.ts#L134-L142
