### ISSUE TITLE
bug(mat-snack-bar): Default options are ignored when opening a snack bar from component

### ISSUE THREAD

**Issue by Lolmewn** [angular/components#20204]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-23ur6d

Steps to reproduce:
1. Create a component and use the `MAT_SNACK_BAR_DEFAULT_OPTIONS` injection token to inject default settings into either the component being used in `snackBar.openFromComponent()` or the module's providers
2. Open the snackbar
 
#### Expected Behavior

What behavior were you expecting to see?
The default options supplied in the injection token should tell the snack bar to only stay open for 5000 milliseconds

#### Actual Behavior

What behavior did you actually see?
The default options supplied in the injection token are unused and the snack bar never closes.

#### Environment

- Angular: 10.0.4
- CDK/Material: 10.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by Lolmewn** [comment]
I think I misunderstand how providers work, adding the default options to the app's main module do seem to be picked up.

**Comment by jelbourn** [comment]
You need to provide the options where the Snackbar module is imported, rather than in the component being opened; by the time that component is instantiated, the snackbar has already consumed whatever options are set.
