### ISSUE TITLE
feat(mat-option): change font size for option

### ISSUE THREAD

**Issue by trubachoff** [angular/components#20212]
#### Feature Description

Why should the **mat-option** font size to **_subheading-2_** (looks like big)? Can change to **_body-1_** (main font size)?

https://github.com/angular/components/blob/8b680837931a4c22734bf1cf4cc076aa200e07aa/src/material/core/option/_option-theme.scss#L55

**Comment by amysorto** [comment]
This is fixed in it's MDC equivalent which is available in v15. Now it is being set here: https://github.com/angular/components/blob/main/src/material/core/option/_option-theme.scss#L62.
