### ISSUE TITLE
Recurrsive tables pagination possiblities

### ISSUE THREAD

**Issue by swamy501** [angular/components#20217]
I would like to check on Pagination possibilities on recursively added Mat Tables like table inside another table upto 5 levels( a tree structure).
We want to add pagination exclusively for outer table, for rows of all tables  will be considered. 
Can you provide an example or possibilities using MatPaginatorModule to work in this scenario?

Thank you.

```
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?


#### Actual Behavior

What behavior did you actually see?


#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 
```

**Comment by jelbourn** [comment]
MatTable doesn't support nesting tables at this time.
