### ISSUE TITLE
help(cdk-virtual-scroll-viewport): How to use autosize and event scrolledIndexChange

### ISSUE THREAD

**Issue by niknikita** [angular/components#20227]
How to use autosize and event scrolledIndexChange?
The height of each element is different, so autosize must be used. When using autosize, the scrolledIndexChange event stops working and an error appears
Error: cdk-virtual-scroll: scrolledIndexChange is currently not supported for the autosize scroll strategy

**Comment by wagnermaciel** [comment]
That error is reflecting that the autosize and virtual scroll is still experimental and not yet considered stable

**Comment by niknikita** [comment]
> That error is reflecting that the autosize and virtual scroll is still experimental and not yet considered stable

what should I do? how to solve a problem?
