### ISSUE TITLE
Any plans to integrate twitter bootstrap layout system?

### ISSUE THREAD

**Issue by bunnyvishal6** [angular/components#20233]
As Twitter Bootstrap's Layout system is pretty solid and effort less to get started and had pretty defaults compared to our Layout package, Can Bootstraps layout system be integrated with Layout package? 
Or Are there any plans to integrate any other layout library.

**Comment by jelbourn** [comment]
Nope, we're more focused on component primitives with the cdk and Material Design components built on top of them
