### ISSUE TITLE
bug(MatTooltip): Multiline mat-tooltip on mat-table cell is not working

### ISSUE THREAD

**Issue by harshadray** [angular/components#20230]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-4mtwsw
Steps to reproduce:
1. Open a stackblitz and hover over on 'No.'(Number) column of table
2. you will see that, tooltip is not break on second line.
 
 
#### Expected Behavior

- It should break in second line.

#### Actual Behavior

- Its working for button and span but not on mat-table cell.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.14
- Browser(s): Chrome (84.0.4147.105)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

![image](https://user-images.githubusercontent.com/34907148/89612649-f3cd3b00-d89d-11ea-9146-a75a2b3cffcb.png)

**Comment by crisbeto** [comment]
What I find odd here is that it even breaks into multiple lines for the `button` and `span` cases, because I wouldn't have expected it to since we only support plain text for tooltips. My guess is that Angular automatically converts the HTML entities into new line characters and it just happens to work.

**Comment by harshadray** [comment]
Well, I have added class at global level to break it on next line. But as I mentioned, same is not working for mat-cell.

```
.mat-tooltip-class-here {
  white-space: pre-line !important;
}
```

**Comment by harshadray** [comment]
There is inconsistency in terms of new line chars.

For the button and span `&#13;` works as new line but for the table cell, we might need to use ` \r\n` or `\n.`
