### ISSUE TITLE
bug(Mat Slider): Can't access private variable inside displayWith fn

### ISSUE THREAD

**Issue by cfficaurzua** [angular/components#20248]
#### What are you trying to do?
I'm trying to format the string inside the slider Thumb,
This works Ok, but the format is conditional to the settings the user has chose in a selection above.
e.g:
15 => 6b if genre is sport
15 => V6 if genre is boulder.
![image](https://user-images.githubusercontent.com/13381072/89712950-35bfb500-d962-11ea-9e57-25ee95de2549.png)

#### What troubleshooting steps have you tried?
HTML
```
<mat-slider thumbLabel #gradeSlider [displayWith]="formatGrade" min="0" max="37" step="1" value="10" formControlName="grade">	
```
TS

```
 pitchForm:FormGroup;
 constructor(
    private route: ActivatedRoute,
    private helper:HelperService,
    private auth:AuthService,
    private afs:AngularFirestore,
    private formBuilder:FormBuilder,
    private router:Router) {
  	this.pitchForm = this.formBuilder.group({
      name: [null, Validators.required],
      grade: [15, Validators.required],
      genre: ['sport', Validators.required],
      id: [this.afs.createId(), Validators.required],
      sigma:[this.getSigmaFromCertainty(0.5), null],
      author:[null, null]
    });

  formatGrade(value: number) {
    console.log(this)
    if (this.pitchForm){
      if (this.pitchForm.value["genre"]=='boulder'){
        return _boulderGrades[Math.round(value)][localStorage.getItem("boulderGradeSystem") || "vermin"]
      }
    }
    return _sportGrades[Math.round(value)][localStorage.getItem("sportGradeSystem") || "yds"]
  }
```
What are you seeing that does not match your expectations? 
pitchForm (FormGroup) should be accessible inside the formatGrade (the displayWith fn).
but when I console.log(this) I got the MatSlider component instead of the parent component (where the function should reside).
hence pitchForm does not exist.
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-jwggda

Steps to reproduce:
1. create a mat-slider with displayWith fn
2. in displayWith fn try to access a private variable (this.var)
  
#### Environment

- Angular: 10.0.6
- CDK/Material: 10.1.1
- Browser(s): Chrome 84.0.4147.105
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment]
I don't think we can do much to get your original context, but if you declare the `displayWith` function like this it will work: 

```
formatGrade = (value: number) => {
  if (this.formGroup){
    if (this.formGroup.value["genre"]=='boulder'){
      return 'V6'
    }
  }
  return '6b'
}
```
