### ISSUE TITLE
docs-bug(button): Missing documentation for MatButtonHarness with() static function

### ISSUE THREAD

**Issue by chivesrs** [angular/components#20270]
#### Documentation Feedback

https://material.angular.io/components/button/api#MatButtonHarness

There is a static `with()` function that lets you find the right instance of mat-button on the page, yet this documentation doesn't support it.

https://material.angular.io/guide/using-component-harnesses states 

`
You can also use the static with method implemented on all Angular Material component harnesses. This method creates a HarnessPredicate, an object that filters loaded harnesses based on the provided constraints. The particular constraint options vary depending on the harness class, but all harnesses support at least:
`

The docs for the `with()` function should exist on the Harness docs page as well, and not on this random guide.

Here is the function I am talking about:
https://github.com/angular/components/blob/master/src/material/button/testing/button-harness.ts#L34

**Comment by chivesrs** [comment]
Lumping this in but can file a new bug if needed.

https://material.angular.io/components/button/api#ButtonHarnessFilters states that there is a `text` filter on the filter interface. But, there is also the `selector` and `ancestor` filter from `BaseHarnessFilters` that isn't in that documentation.

I guess superclasses/inheritance isn't parsed when generating this doc?

**Comment by jelbourn** [comment]
@devversion do we extract API docs for static methods?
