### ISSUE TITLE
STACKBLITZ EXAMPLES NOT WORKING IN DOCUMENTATION!

### ISSUE THREAD

**Issue by davejacobs777** [angular/components#20284]
#### Documentation Feedback

NONE OF THE STACKBLITZ EXAMPLES ARE WORKING IN THE DOCUMENTATION!!

**Comment by crisbeto** [comment]
I tried a few and they seem to be working. Can you give an example?

**Comment by LeaBergerCH** [comment]
https://stackblitz.com/angular/nqyvakemvvr?file=src%2Fapp%2Fsidenav-position-example.ts

Sidenav examples doesn't work for me

**Comment by crisbeto** [comment]
It looks like the same issue as https://github.com/angular/components/issues/20271.

**Comment by devversion** [comment]
Yeah. Closing as a duplicate of https://github.com/angular/components/issues/20271.
