### ISSUE TITLE
Mat-tab: Wrong focus on tab when using keyboard navigation.

### ISSUE THREAD

**Issue by shineinsert** [angular/components#20293]
I am developing keyboard control my website and in the mat-tab I used left/right arrow it should go to tab follow my control.

When use keyboard control to focus on Tabs and press left arrow to move focus It focus on wrong tab like it remember action from tab navigate at first time

In mat-tab component when use left and right arrow sometime it go to opposite my control. I’m not sure I using it wrong way? 

Tabs should navigate correct follow by the arrow that user press on keyboard.

#### Environment

- Angular: 10
- CDK/Material: 10.1.3

**Comment by jelbourn** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment

(this is a canned response)
