### ISSUE TITLE
bug(Sort Header): When sorting strings, all uppercase letters come before all lowercase letters

### ISSUE THREAD

**Issue by garretpremo** [angular/components#20299]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-glgbhq?file=src/app/sort-overview-example.ts

Steps to reproduce:
1. Sort the **Dessert (100g)** column
 
#### Expected Behavior

What behavior were you expecting to see?

Order of rows should be:

Cupcake
Eclair
frozen yogurt
Gingerbread
Ice cream sandwich

#### Actual Behavior

What behavior did you actually see?

Order of rows was:

Cupcake
Eclair
Gingerbread
Ice cream sandwich
frozen yogurt

#### Environment

- Angular: 10.0.9
- CDK/Material: 10.1.3
- Browser(s): Chrome version 84.0.4147.125
- Operating System: Windows

**Comment by jelbourn** [comment]
This is working as intended since it's the default lexical sort order. You can customize the sort function to ignore case.
