### ISSUE TITLE
help(MatCalendar): using DateRange but range is not displayed, selectChange fires Date instead of DateRange

### ISSUE THREAD

**Issue by Venipa** [angular/components#20307]
#### What are you trying to do?

implementing a date range picker dialog with the calendar component

#### What troubleshooting steps have you tried?

range is not previewed/displayed, change event returns Date object

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

StackBlitz: https://stackblitz.com/edit/components-issue-wsgnr4?file=src/app/example-component.html
  
#### Environment

- Angular: 10.0.3
- CDK/Material: 10.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The range isn't showing up, because you aren't using the `DateRange` class. We determine whether to show a range with a `foo instanceof DateRange` check, here's a working example https://stackblitz.com/edit/components-issue-q9db1k.

**Comment by Venipa** [comment]
@crisbeto thanks it works now 👍 

i've noticed this green highlight is there any meaning to it?
![image](https://user-images.githubusercontent.com/17952364/90248551-32806980-de39-11ea-9529-6f02d6df5f8c.png)

**Comment by crisbeto** [comment]
The green state is because you're passing in a comparison range through the `comparisonStart` and `comparisonEnd` inputs. It shows where the main range and the comparison ranges overlap. There's some more info about it in the docs: https://material.angular.io/components/datepicker/overview#comparison-ranges

**Comment by Venipa** [comment]
@crisbeto is it possible to use their range picker select strategy?
(sorry for the constant pings :( )
