### ISSUE TITLE
Is there a way to use mat-calendar with range dates?

### ISSUE THREAD

**Issue by thais-molica** [angular/components#20309]
I see mat-date-range-picker uses mat-calendar internaly. Is there a way I can use directly the mat-calendar and yet select a range of dates? I'm asking this because I want to customize my modal and display a list of suggested date ranges along with the calender it self. Seems to me that the better way to do this is using only the calendar.

I would like to do something like this:

```
<div class="modal">
  <ul>
    <li>Date range suggestion</li>
  </ul>
  <mat-calendar></mat-calendar>
</div>

**Comment by crisbeto** [comment]
If you pass in a `DateRange` object to the calendar's `selected` input it'll show up as a range.

**Comment by thais-molica** [comment]
Can you give an example, please?

Thanks

**Comment by crisbeto** [comment]
We don't have any live examples of a standalone `mat-calendar`, but you can check out this recent issue that has some links https://github.com/angular/components/issues/20307.

**Comment by thais-molica** [comment]
Perfect! Thank you very much ;)
