### ISSUE TITLE
docs-bug(table): Table examples are too wide

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#20313]
https://material.angular.io/components/table/examples

Table examples are too wide
![Screen Shot 2020-08-14 at 9 28 57 AM](https://user-images.githubusercontent.com/22898577/90271379-95a9d600-de10-11ea-88d5-e0ae22edfddc.png)

**Comment by Splaktar** [comment]
Some of this was fixed in https://github.com/angular/components/pull/20063.
