### ISSUE TITLE
docs-bug: Resizing window from narrow to wide does not make the table of contents appear

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#20315]
Resizing the docs site to a narrow width causes the Table of Contents to disappear. 

Resizing it back to a wide width does not cause it to re-appear.

![Screen Shot 2020-08-14 at 10 15 14 AM](https://user-images.githubusercontent.com/22898577/90275385-0f44c280-de17-11ea-97d3-0b1d439292dd.png)

**Comment by geromegrignon** [comment]
I'm working on a PR

**Comment by geromegrignon** [comment]
PR opened : https://github.com/angular/material.angular.io/pull/878
