### ISSUE TITLE
bug(DATEPICKER): Datepicker format Date doesn't work if you type it

### ISSUE THREAD

**Issue by web-dave** [angular/components#20321]
#### Reproduction

You can find a example here: https://stackblitz.com/edit/angular-nhkztz
(Its a fork if the Documentation on Stackblitz)

Steps to reproduce:
1. click on the calendar icon next to the input
2. Select a Date from the popup (f.e. 04.08.2020)
3. The input displays: 04.08.2020
4. Now change the value in the input to 04.08.2021 (Its important to have a input event here)
5. leave the input by tap or by clicking nect to the input (NOT ON THE CALENDAR ICON!)
6. The input displays:  
  - in chrome: 08.04.2021
  - in Edge: 04.01.2008
  - in FireFox: 04.01.2008
 
 
#### Expected Behavior

I expect to see the date I just typed.

#### Actual Behavior

If you set the date by hand (keyboard) and you use a custom format, the value is parsed wrong (The format is not processed correctly here)

#### Environment
OS Windows 10
Surface Book2
Chrome 84.0.4147.125, Edge 84.0.522.59 , FireFox 78.0.2

```json

  "dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/cdk": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/forms": "^10.0.0",
    "@angular/material": "^10.0.0",
    "@angular/material-moment-adapter": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/router": "^10.0.0",
    "angular-in-memory-web-api": "~0.11.0",
    "moment": "^2.26.0",
    "rxjs": "^6.5.5",
    "tslib": "^1.11.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.0",
    "@angular/cli": "^10.0.0",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@angular/localize": "^10.0.0",
    "@types/node": "^12.12.41",
    "codelyzer": "^5.2.2",
    "ts-node": "^8.4.1",
    "tslint": "^6.1.2",
    "typescript": "~3.9.5"
  }
```

**Comment by web-dave** [comment]
Same behavior with my Moto Z2 play (Android, chrome, touch)

**Comment by crisbeto** [comment]
This is working as expected. By default we pass in the input value through `new Date()` which may not necessarily produce the same results. If you want to customize the behavior, you can provide a different `DateAdapter` or use the Moment date adapter instead.

**Comment by web-dave** [comment]
As I did here?
https://stackblitz.com/edit/angular-dateadapter-example-stackoverflow1-jwbjka?file=app/custom-date-adapter.ts
I'm wondering how moment should be able to handle it correctly.
Can you provide an example?

**Comment by mmalerba** [comment]
Your example is using a different format for parsing input vs displaying date in the input. If you switch it to use the same format for both it should behave as expected https://stackblitz.com/edit/angular-nhkztz-fhrtrs?file=src%2Fapp%2Fdatepicker-formats-example.ts

**Comment by web-dave** [comment]
Thx
