### ISSUE TITLE
material/table: not able to create dynamic reference for mat-autocomplete inside the mat-table (nested formGroup)

### ISSUE THREAD

**Issue by Ram-97** [angular/components#20328]
I have created a nested `form group` using `form array` and used the form array as a `datasource` for mat-table.

After that, I am using the `idMaterial formcontrol` to show the mat-autocomplete.I have tried to create `dynamic template reference variable` for mat-autocomplete. But, it shows `undefined instance error`.

Here is my try:
**ts**
![image](https://user-images.githubusercontent.com/46098790/90313497-ac445000-df2a-11ea-88b0-070f55013cfc.png)

**html**
![image](https://user-images.githubusercontent.com/46098790/90313438-49eb4f80-df2a-11ea-9b05-3962d0821c07.png)

Please help me in fixing this issue. Thanks in advance.

**Comment by Splaktar** [comment]
Please provide a StackBlitz or git repo reproduction that can be used to verify and/or debug your issue.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.

(this is a canned response)
