### ISSUE TITLE
bug(youtube-player): When loading youtube player inside a Tab the iframe refreshes

### ISSUE THREAD

**Issue by shahraship** [angular/components#20329]
#### Reproduction

Use StackBlitz to reproduce your issue: https://components-issue-xxet19.stackblitz.io

Steps to reproduce:
1. Include a youtube player in tab component
2. switch tabs and you'll see the iframe re-loads.
 
 
#### Expected Behavior

What behavior were you expecting to see?

The iframes should not reload, just because we are switching tabs

#### Actual Behavior

What behavior did you actually see?

The iframes are reloading

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
It's because tabs remove their content from the DOM while it's off-screen. Changing the behavior is covered by https://github.com/angular/components/issues/19480.
