### ISSUE TITLE
bug: Accessibility issue with mat-select paginator(mat-paginator) 

### ISSUE THREAD

**Issue by Jagan494** [angular/components#20333]
#### Bug

The mat-select which is used in Paginator can’t be read by screen readers as the user changes the number which focus on the extended dropdown. 
 
#### Expected Behavior

The screen reader to be able to read the value of select field.  

Mat-paginator should have provision to use native select component inside paginator component

#### Actual Behavior

There is accessibility issue on Mat-Paginator because of mat-select field

**Comment by jelbourn** [comment]
Duplicate of #11083
