### ISSUE TITLE
Probably the issue is that tab component is playing on the "display" value.

### ISSUE THREAD

**Issue by KasunGamage** [angular/components#20347]
Probably the issue is that tab component is playing on the "display" value.
I made a similar component which changes the "visiblity" value instead of "display" and it stopped reloading.

_Originally posted by @ShubhenduVaid in https://github.com/angular/components/issues/5239#issuecomment-368071906_

Hi @ShubhenduVaid can u explain little bit this?

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
