### ISSUE TITLE
bug: "class" host binding conflicts with user "class bindings

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#20353]
#### Root cause

The following host bindings are clobbered if the user applies a dynamic class binding of their own:

```ts
host: {'class': 'mat-card-title'}
```

This does not occur in Ivy since their new algorithm handles this case and applies both bindings.

#### Reproduction

https://stackblitz.com/edit/angular-utbiyp-zedm4d?file=src%2Fapp%2Fcard-fancy-example.html
 
#### Expected Behavior

Both cards should have the same styles applied.

#### Actual Behavior

Styles differ because the second card did not apply the class `mat-card-title`

**Comment by jelbourn** [comment]
This is a known/expected behavior going from VE to Ivy and I don't think there's anything we can do about it in the library.
