### ISSUE TITLE
Add custom text below date on load of the page

### ISSUE THREAD

**Issue by jigardarji318** [angular/components#20361]
#### Feature Description

Need to add custom text below all dates on the page load.

#### Use Case

![CalendarImge1](https://user-images.githubusercontent.com/23478282/90647164-a8c80600-e255-11ea-8830-f6164037340c.png)

So basically we wanted the same functionality as shown in the attached image.

Can you please help me out in this case

**Comment by jelbourn** [comment]
We don't have any plans to add this in the foreseeable future.
