### ISSUE TITLE
characters with diacritic don't fit in select

### ISSUE THREAD

**Issue by rattkin** [angular/components#20370]
![image](https://user-images.githubusercontent.com/910080/90770404-0742c200-e2f2-11ea-8fdc-4c7567c214f5.png)
uppercase characters with diacritic marks don't fit.
tops of the diacritic marks are cut off.
With dome appearance modes, the whole diacritic might be cut off.

https://stackblitz.com/edit/angular-ihah5c?file=src%2Fapp%2Fselect-overview-example.html

**Comment by JanProchy** [comment]
This needs to be fixed asap because
* Many languages use accented characters
* Overiding overflow property is road to hell 
* CSS unavaibility to combine overflow-x/y or overflow-text

**Comment by amysorto** [comment]
When testing with the new MDC based select component which is coming soon in v15, the diacritical marks I tried don't get cut off for uppercase letters anymore. Closing this bug since it's fixed there.
