### ISSUE TITLE
Can not smooth scroll on IOS 13

### ISSUE THREAD

**Issue by nguyenngocchaugv** [angular/components#20399]
#### Reproduction

Steps to reproduce:
1. Open select mat-select
2. Using mobile ios 13. Tapping on the mat-select and scroll up
 
 
#### Expected Behavior

Users can scroll items in mat-select. 

#### Actual Behavior

The Smooth scroll can not work
I have an issue when I scroll the page which has multiple inputs field. I can not scroll up or down. Because the browser misunderstand between hold tap and scroll or focused input

#### Environment

- Angular: V9
- CDK/Material: V9
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): IOS 13

**Comment by crisbeto** [comment]
I couldn't reproduce it on a device running iOS 13.6.1. Is there a specific example that isn't working for you?

**Comment by nguyenngocchaugv** [comment]
@crisbeto It occurred sometime. I doubt that the reason for this issue is angular-material. I have one page which contains full-screen input. When I tap on the input and move up. Scrolling does not work. 
[https://ibb.co/wWN1SYS](url)

**Comment by crisbeto** [comment]
It doesn't sound like we can do much about it on our end. There's probably an element with `overflow: auto` somewhere that should have the `-webkit-overflow-scrolling: touch` style.
