### ISSUE TITLE
docs(Stepper): suggestions to improve docs

### ISSUE THREAD

**Issue by dev054** [angular/components#20408]
**Affected documentation page:** https://material.angular.io/components/stepper

1. Examples using `MatStepperIntl`. There's a small mention to it in the overview page, but it'd be better if you put a real example on it. Basically the same request as #8239 (for paginator).
2. StepState is not being shown up in API page. To know what `stepState` `@Input` expects we should go deep in code.
3. Examples without using `stepControl`. There's currently no example on the example page.

**Comment by amysorto** [comment]
Thanks for the suggestions! An example using MatStepperIntl was added in this PR: [angular/components#22685](https://github.com/angular/components/pull/22685). 

StepState does show up in the API page. Also, the example that has tests with the MatStepperHarness doesn't use stepControl.

**Comment by dev054** [comment]
> Thanks for the suggestions! An example using MatStepperIntl was added in this PR: [angular/components#22685](https://github.com/angular/components/pull/22685).

Nice to know, thanks!

> StepState does show up in the API page.

Hmm, I just noticed that it is being shown in `cdk/stepper`. It would be nice if we can have an anchor to types/interfaces/classes references. I'll submit a new issue for this.

> Also, the example that has tests with the MatStepperHarness doesn't use stepControl.

I see, thanks!
