### ISSUE TITLE
feat(Stepper): Possibility of disabling focus on activation

### ISSUE THREAD

**Issue by dev054** [angular/components#20428]
#### Feature Description

Currently once a step is active, it receives focus. I want to disable this and I don't find a proper way to do this right now.

#### Use Case

Describe the use case(s) that the proposed feature would enable.

Currently I've disabled the step header navigation by using CSS (relates to #20427), but it still shows the focus on activation.

**Comment by crisbeto** [comment]
Moving focus is an accessibility feature and we generally don't provide APIs that would degrade the app's accessibility. You might be able to do it by setting `pointer-events: none` on the stepper header.
