### ISSUE TITLE
bug(MatDateRangePicker): date range emits changes to form

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#20432]
#### Reproduction

https://stackblitz.com/edit/angular-ki1fyd?file=src/app/date-range-picker-overview-example.ts

Steps to reproduce:
1. ngOnInit patches form values using emitEvent: false;
2. The form dirty is true;
 
should have been false.

**Comment by zehavibarak** [comment]
To my understanding, date-range-input.ts calls _registerModel() in ngAfterContentInit() after the value is set, causing it to trigger changes to form control.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/20213.
