### ISSUE TITLE
Angular Material not working!

### ISSUE THREAD

**Issue by edwin042** [angular/components#20445]
ERROR in node_modules/@angular/material/tabs/tabs-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
This likely means that the library (@angular/material/tabs) which declares MatTabsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider 
checking with the library's authors to see if the library is expected to be compatible with Ivy.

    8 export declare class MatTabsModule {

**Comment by crisbeto** [comment]
As the error says, it likely means that the dependencies weren't processed by ngcc correctly. You can try to clear your `node_modules` and reinstall.

**Comment by edwin042** [comment]
Yeah thank you It worked!
