### ISSUE TITLE
bug(mat-datepicker): Input pattern is ignored.

### ISSUE THREAD

**Issue by Mastermindzh** [angular/components#20446]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-1v5vvr-monz1x?file=src/app/datepicker-filter-example.html

Steps to reproduce:
1. Add the datepicker
2. Add **any** pattern validation on the input field
4. Observe inputModel.valid somehow
5. valid starts out as false, change the date in the datepicker and it will always be true even if the provided pattern in step 2 doesn't match. 
 
#### Expected Behavior

I would expect the pattern to be validated and the result of it to be put into inputModel.valid

#### Actual Behavior

The pattern is ignored and the value of inputModel.valid is always true.

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Chrome, Chromium, Edge (chromium based), Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows and Arch Linux

**Comment by crisbeto** [comment]
`pattern` is a native HTML property, not something that we're providing from Material. It should either be handled at the `@angular/forms` level like the other validators (e.g. `required`) or you can provide your own custom validator.
