### ISSUE TITLE
bug(CdkTextareaAutosize): Autosize not working when ancestor display none

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#20443]
#### Reproduction

https://stackblitz.com/github/keatkeat87/angular-material-textarea-autosize-display-none-issue

Steps to reproduce:
![autosize-display-none-issue](https://user-images.githubusercontent.com/8691013/91519500-61acd580-e925-11ea-9593-207e458a56a1.gif)

#### Expected Behavior
What behavior were you expecting to see?
textarea size should display all text

#### Actual Behavior
What behavior did you actually see?
textarea size not display all text

Detail: 
this happens when ancestor use display none + change detect set to "OnPush"
when i check material source code, i found that, auto size only work when DoCheck.
so if textarea is not first child layer, it won't update the size.
![image](https://user-images.githubusercontent.com/8691013/91519970-b13fd100-e926-11ea-8186-facaa56e0c15.png)

#### Environment

Angular CLI: 10.0.8
Node: 12.18.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.1.3
@angular/cli                      10.0.8
@angular/material                 10.1.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

**Comment by crisbeto** [comment]
This has come up in the past (e.g. https://github.com/angular/components/issues/5222). Unfortunately we can't do much about it, because we'd have to poll for the size of the `textarea` on each change detection which will cause layout thrashing. You can tell it to resize manually by getting a hold of it using `ViewChild` and calling `resizeToFitContent`.
