### ISSUE TITLE
bug(mat-datepicker): tab index not being set on datepicker toggle

### ISSUE THREAD

**Issue by JudahMorrison** [angular/components#20440]
#### Reproduction

Steps to reproduce:
1. Setup a mat-datepicker:

    <mat-form-fieldclass="date-input" >
      <input matInput [matDatepicker]="datePick"
        ngDefaultControl
        tabindex="{{tabindex}}
        formControlName="date"
      />
      <mat-datepicker tabindex="{{ 1 + tabindex}}" ></mat-datepicker>
      <mat-datepicker-toggle
      matSuffix
      [for]="datePick"
      ></mat-datepicker-toggle>
    </mat-form-field>

2. Put tabindex='1' on input and tabindex='2' on mat-datepicker.
 
 
#### Expected Behavior

What behavior were you expecting to see? Tabs onto datepicker input and then tabs onto the calender icon.

#### Actual Behavior

What behavior did you actually see? Tabs onto input and off.

#### Environment

- Angular: 10
- CDK/Material: 10.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The input is spelled as `tabIndex` (note the capital `I`) in order to match the native DOM property name. I think that's why the value isn't being picked up in your case.

**Comment by JudahMorrison** [comment]
Thanks @crisbeto! My problem was, I was trying to use the standard html element "tabindex" on the mat-datepicker element (It looks like gitlab removed some of the code I pasted in my issue). I needed to move it to mat-datepicker-toggle, switch to "tabIndex", and use it as a angular component property input, ie.  [tabIndex]="2".
