### ISSUE TITLE
Datepicker height issue with large custom header 

### ISSUE THREAD

**Issue by dexster** [angular/components#20459]
#### Reproduction

https://stackblitz.com/edit/components-issue-9tpthp

Steps to reproduce:
1. Create a custom calendar header with a height of 100px;
2. If there are 6 day rows in a month then the calendar has this style issue. If the height was greater it would affect more rows
 
#### Expected Behavior
Calendar content should remain inside container. mat-calendar-content should probably have an independent height style from the heading. 

#### Actual Behavior

Container not resizing to accomodate header height:
![datepicker](https://user-images.githubusercontent.com/6392334/91707905-cb74eb80-eb80-11ea-80f1-5249497d650d.png)

#### Environment

- Angular: 10.0.3
- CDK/Material : 10.0.1
- Browser(s): Firefox/Chrome
- Operating System: macOS

**Comment by ramprakashram** [comment]
Can i take up this issue ?
