### ISSUE TITLE
mat-progress-spinner : want to achieve text in middle of it

### ISSUE THREAD

**Issue by AshishkrGoyal** [angular/components#20458]
Hi Guys,
we are using angular material mat-progress-spinner and want to achieve something like this :

![image](https://user-images.githubusercontent.com/25322851/91687681-f4e04800-eb7d-11ea-82fb-d46d1d3ca6d2.png)

can we do it with this.

thanks in advance.

**Comment by devversion** [comment]
Hello! thanks for this issue.

This is not something officially supported as the Material Design spec does not suggest us showing text within the circle. It's totally do-able though. See for example https://stackoverflow.com/questions/46365836/how-to-set-text-inside-md-progress-spinner-in-angular-4.
