### ISSUE TITLE
bug at: https://material.angular.io/components/stepper/api

### ISSUE THREAD

**Issue by chrisj-skinner** [angular/components#20457]
#### Reproduction

Appears that the following link (tab) is erroring: https://material.angular.io/components/stepper/api

Steps to reproduce:
1. Go to https://material.angular.io/components/stepper/api
2. See the loading message / errors in console.
 
 
#### Expected Behavior

To see the API docs

#### Actual Behavior

Loading message stays up. Errors in console. Loading message is never replaced.

**Comment by crisbeto** [comment]
What error are you seeing? It's working for me so you might have a cached version that's breaking.

**Comment by devversion** [comment]
Closing as I cannot reproduce it either, and it looks like it was a cache issue.
