### ISSUE TITLE
WARNING when Ng Serve - Angular Datatable Issue

### ISSUE THREAD

**Issue by edwin042** [angular/components#20455]
Warning: Entry point 'angular-datatables' contains deep imports into '[....path]/node_modules/rxjs/Rx'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by crisbeto** [comment]
`angular-datatables` isn't in this repository. It seems like you're looking for this: https://github.com/l-lin/angular-datatables

**Comment by edwin042** [comment]
Thank you @crisbeto for your concern!
