### ISSUE TITLE
bug(autocomplete): Autocomplete menu inside sidenav doesn't respect parent placement

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#20461]
#### Reproduction

![sidenav_menu_bug](https://user-images.githubusercontent.com/12090931/91748123-d38b5600-eb95-11ea-88f8-a2f570f98b63.gif) 
 
#### Expected Behavior

Autocomplete options should stick to it's parent element,
or should close the menu when scrolling.

#### Actual Behavior

It doesn't keep track when scrolling. 

#### Environment

- Angular:
- CDK/Material: 10.1.3
- Browser(s): Chrome 85.0.4183.83 - 64 bits
- Operating System: Windows 10 (OS Build 19041.450)

**Comment by mrmokwa** [comment]
Example: https://tdssoftware.github.io/query-view/clientes

Repo: https://github.com/TdsSoftware/query-view

**Comment by tomicarsk6** [comment]
Possible duplicate of #10079.

Possible solution to your problem: https://github.com/angular/components/issues/10079#issuecomment-619887760.

**Comment by mrmokwa** [comment]
Yeah, you're right, closing it.
