### ISSUE TITLE
bug(Map Markers): Markers not in DOM

### ISSUE THREAD

**Issue by verygreenboi** [angular/components#20460]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-m6qbws?file=src/app/app.component.ts

Steps to reproduce:
1. Load a lot of markers on the map
 
 
#### Expected Behavior

The markers should be accessible on the dom. I use CSS to rotate the markers. Per my requirements, I can't use marker clustering.
 

#### Actual Behavior

The markers appear nowhere in the document but are still visible on the map

#### Environment

- Angular: 10.0.14
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by wagnermaciel** [comment]
This is working as expected. This is the way google maps renders markers. We don't do anything special to this on the angular side.
