### ISSUE TITLE
material/input: matTextareaAutosize causes jumping to the bottom when editing

### ISSUE THREAD

**Issue by saurabhsingh1003** [angular/components#20469]
When i'm try to edit my textarea in material input and i have used matTextareaAutosize for automatic height so when i'm trying to edit its jumping to bottom.

Do you guys have any solution to stop this? thanks for your support.

checkout the code attached below:
for more info please checkout the zip file.

browser-chrome
<mat-form-field class="example-full-width">
    <mat-label>Leave a comment</mat-label>
    <textarea matInput matTextareaAutosize placeholder="Ex. It makes me feel..."></textarea>
  </mat-form-field>
</form>
[jump.mp4.zip](https://github.com/angular/components/files/5156077/jump.mp4.zip)

https://stackblitz.com/edit/angular-weoqds?file=src%2Fapp%2Finput-overview-example.html

- Angular:
- CDK/Material:
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by saurabhsingh1003** [comment]
@jpzwarte @mprobst @dpurp @alexweber can you please look this issue.

**Comment by tomicarsk6** [comment]
I tweaked your stackblitz example a little bit, you can have a look [here](https://stackblitz.com/edit/angular-weoqds-gfxm1b?file=src%2Fapp%2Finput-overview-example.html).

I simply added two things `matAutosizeMinRows` and `matAutosizeMaxRows` and with that, when you editing something, there is no jump anymore to the "bottom".

**Comment by saurabhsingh1003** [comment]
@tomicarsk6 even i tried same thing its works but this is not my requirement because i want height to be set based on the content of user and it display in page. you added [matAutosizeMaxRows]=15 and inside scroll is there that  i don't want.

**Comment by saurabhsingh1003** [comment]
@tomicarsk6 my requirement is height should be add based on content and user want to edit it will not jump..

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
