### ISSUE TITLE
Which version do I use?

### ISSUE THREAD

**Issue by FizzBuzz791** [angular/components#20466]
Apologies if this has already been answered but I couldn't find the information easily.

I'm running @angular/core version 9.1.12 and generally try to keep other packages in line with this, i.e. common, cli, forms, etc.

It looks like the latest 9.x version is 9.2.3, so I'm wondering if that's compatible with 9.1.12 or whether I should be trying to keep the versions consistent?

**Comment by jelbourn** [comment]
As long as the major version is the same, everything should be compatible.
