### ISSUE TITLE
Material Sorting is not working with different numeric values

### ISSUE THREAD

**Issue by bikash2015github** [angular/components#20473]
Can anyone explain how the material sorting is working? not able to understand the sorting logic.Attached the screenshot.

![image](https://user-images.githubusercontent.com/18417454/91969001-1d5d7300-ed33-11ea-8c68-f130f36f4288.png)

Angular Version:9.2.4
Material UI Version:9.2.4

**Comment by wagnermaciel** [comment]
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment
(this is a canned response)
