### ISSUE TITLE
bug(COMPONENT): TITLE

### ISSUE THREAD

**Issue by pwwpche** [angular/components#20472]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1.  Use the official example for Material Select (here I use optgroup example) 
   https://stackblitz.com/angular/gxormyablya?file=src%2Fapp%2Fselect-optgroup-example.ts
2. Use `ngTemplateOutlet` with `<ng-container>` inside <mat-select>. For example, change _src/app/select-optgroup-example.html_, replace all with following code

```html
<h4>mat-select</h4>
<mat-form-field appearance="fill">
  <mat-label>Pokemon</mat-label>
  <mat-select [formControl]="pokemonControl">
    <ng-container *ngIf="true; then group else option"></ng-container>
  </mat-select>
</mat-form-field>

<ng-template #group>
  <div>
    <mat-optgroup *ngFor="let group of pokemonGroups" [label]="group.name"
                  [disabled]="group.disabled">
      <mat-option *ngFor="let pokemon of group.pokemon" [value]="pokemon.value">
        {{pokemon.viewValue}}
      </mat-option>
    </mat-optgroup>
  </div>
</ng-template>
<ng-template #option><div>
  <mat-option>-- None --</mat-option></div>
</ng-template>
```
 
 
#### Expected Behavior

What behavior were you expecting to see?

Clicking on select, it should show a dropdown

#### Actual Behavior

What behavior did you actually see?

Dropdown is not shown, nothing is popped up

However, when adding a dummy option `<mat-option>dummy</mat-option>` inside mat-select, dropdown will be shown. Guess there is something to do with cdk overlay?

#### Environment

- Angular: ^10.0.0, following official example
- CDK/Material: ^10.0.0, following official example
- Browser(s): Chrome Version 85.0.4183.83 (Official Build) (64-bit), also Safari Version 13.1.1 (15609.2.9.1.2)
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS

**Comment by wagnermaciel** [comment]
This is the expected behavior. The `mat-optgroup` needs to be a direct descendant of `mat-select`.

If you want to change the options conditionally, you can change the underlying data you're binding to instead of doing the conditional in the template.
