### ISSUE TITLE
mat-table cloumn resize(on mouse drag of header column)

### ISSUE THREAD

**Issue by indira2003** [angular/components#20475]
I want to use a capability in mat-table where on drag of column header it can change it's width.
I tried this example, but it's not working for me at all.

https://stackblitz.com/edit/flex-table-column-resize

If anyone has ever worked on any functionality, please help me as it's urgent.
I am using angular material 9.

**Comment by wagnermaciel** [comment]
There's an experimental column resize feature in `@angular/cdk-experimental/column-resize` and `@angular/material-experimental/column-resize`. This feature is still in development; the api may still change and it doesn't have any documentation yet. #8312
