### ISSUE TITLE
help(Tabs): 

### ISSUE THREAD

**Issue by directcuteo** [angular/components#20488]
Hi. Using the `MatTab` component I am able to show my tabs. There are many tabs so the arrows are visible to navigate through the tabs.
I have implemented myself a 'home' button so that pressing this button the `selectedIndex` will become 0 (first tab will be active).

The problem I have is that if the `selectedIndex` is 0, then I use the arrows to navigate again and the zeroIndex tab is not visible anymore and then I press the home button the transition will not work, so basically the button does nothing if the `selectedIndex` is zero before clicking the button.

Here's a picture that may help understand:
![image](https://user-images.githubusercontent.com/37619567/92097103-615a8180-ede0-11ea-92c7-29fbc6235923.png)

**Comment by wagnermaciel** [comment]
This is working as expected.

It seems like if the 0th tab is already selected you'll need to scroll manually - there's no api for that. You could set the `scrollLeft` on the scrolling container.
