### ISSUE TITLE
bug(mat-expansion-panel): Component never use background color from the theme always fallback to default

### ISSUE THREAD

**Issue by ybonnefond** [angular/components#20490]
Overriding `card` background color in a theme does not affect the background color of the `mat-expansion-panel` compnent

#### Reproduction

https://stackblitz.com/edit/components-issue-vinxqi?file=src/styles.scss

#### Expected Behavior

Background color of the `mat-expansion-panel` should come from `$theme.background.card`

#### Actual Behavior

Background lookup is done in `$theme.color.background.card` which does not exist in a theme and therefore always fallback to the default value.

#### Environment

- Angular: 10.0.0
- CDK/Material: 10.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

#### Details

I believe the issue is located in the `@mixin mat-expansion-panel-theme`
https://github.com/angular/components/blob/10.1.x/src/material/expansion/_expansion-theme.scss#L103

If a theme is passed as parameter, The `color` config is extracted from the theme using `mat-get-color-config` and then passed to `mat-expansion-panel-color`

But the `mat-expansion-panel-color` seems to expect a theme object as input, not just the color sub key. It tries to extract the background and foreground config of the theme:
https://github.com/angular/components/blob/10.1.x/src/material/expansion/_expansion-theme.scss#L11

**Comment by wagnermaciel** [comment]
This is the expected behavior. It used to be that the theme functions returned an map that included the `background`, but we have since changed this so that `background` lives on `color`. 

Overwriting the background or foreground colors like this isn't something we officially support. It'll keep working if you do this but the internals of that theme map could change between releases.

**Comment by ybonnefond** [comment]
@wagnermaciel Thanks for the clarification

Is there an official way to change the background color of components (e.g. expansion panel or cards)?
