### ISSUE TITLE
bug(DragDrop): directives cdkDragPlaceholder and cdkDragPreview not working

### ISSUE THREAD

**Issue by FedericoAndreoli** [angular/components#20504]
#### Reproduction

StackBlitz:https://stackblitz.com/edit/components-issue-h9nopg?file=src%2Fapp%2Fexample-component.ts
 
 
#### Expected Behavior

I'm expecting to see the custom preview and custom placeholder declared in the .html file.

#### Actual Behavior

Nothing really happens and default components are used.

#### Environment

- Angular: 8.3.29
- CDK/Material: 8.2.3 for both
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 

Is it a bug or am I missing something very simple?

**Comment by crisbeto** [comment]
The directives have to be placed inside of a `cdkDrag` element.

**Comment by FedericoAndreoli** [comment]
> The directives have to be placed inside of a `cdkDrag` element.

Now i see, i knew that it was sompething stupid. Thank you so much!!
