### ISSUE TITLE
bug(CDK scrolling): Inconsistent scrolling with the mouse wheel

### ISSUE THREAD

**Issue by Arktiswind** [angular/components#20505]
#### Reproduction
Just look at the examples in different browsers: https://material.angular.io/cdk/scrolling/overview#virtual-scrolling

Steps to reproduce:
scroll with the mouse wheel in the examples 
* in Chrome/Opera it jumps from `Item 3` at the bottom to `Item 7` at the top, never displaying items 4 to 6.
* in Edge(Chromium) it just scrolls 2 items.
* only in FF it scrolls as expected from `Item 3` at the bottom to `Item 4` at the top.
 
 
#### Expected Behavior

Scroll behavior as in FF.

#### Environment

- Angular: 
- CDK/Material: 10.2.0 , 9.2.4 
- Browser(s): Chrome, Opera, Edge(Chromium)
- Operating System: Windows 10

**Comment by mmalerba** [comment]
This sounds like probably just differences in how browsers handle mouse wheel scrolling. Normalizing this behavior across browsers is outside the scope of Angular Material.
