### ISSUE TITLE
export '_DisposeViewRepeaterStrategy' was not found in '@angular/cdk/collections'

### ISSUE THREAD

**Issue by sakthivel-ar** [angular/components#20506]
I am trying to do "ng build" or "ng serve"

Steps I have tried:
- Deleted node_modules and reinstalled through npm.
- Performed "npm update".
- Ran "npm install --save @angular/cdk"

I am facing the below error.
```
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 58:58-86
"export '_DisposeViewRepeaterStrategy' was not found in '@angular/cdk/collections'

ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 84:66-94
"export '_DisposeViewRepeaterStrategy' was not found in '@angular/cdk/collections'

ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 58:23-46
"export '_VIEW_REPEATER_STRATEGY' was not found in '@angular/cdk/collections'

ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 84:31-54
"export '_VIEW_REPEATER_STRATEGY' was not found in '@angular/cdk/collections'
```

Environment:
- Angular: 10
- CDK/Material: __ivy_ngcc__
- Operating System - Ubuntu

**Comment by crisbeto** [comment]
This usually means that your versions of `@angular/material` and `@angular/cdk` are different.

**Comment by mohankoli** [comment]
I got same issue, I was facing issue  with particular version 10.1.3 in @angular/material and @angular/cdk.
I just updated package josn  file with  "@angular/cdk": "10.2.0" and   "@angular/material": "10.2.0".

now it working fine for me

thanks
Mohan

**Comment by crisbeto** [comment]
Closing since it appears like it's a version mismatch issue.
