### ISSUE TITLE
bug(DatePicker): Can't select date

### ISSUE THREAD

**Issue by bcdevworks** [angular/components#20515]
#### Reproduction

Here's the form field as it is in the tempalte:
`<mat-form-field>
   <mat-label>Ingresa una fecha (dd/mm/yyyy)</mat-label>
     <input matInput [matDatepicker]="picker" formControlName="appointmentDate" [min]="getMinDate()">
     <mat-error *ngIf="requestForm.controls.appointmentDate.hasError('required')[innerHtml]="inputValidators.required.errorMessage"></mat-error>
      <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
      <mat-datepicker #picker></mat-datepicker>
    </mat-form-field>`

In my component I'm calling this on **ngOnInit**:

`private createForm(): void {

    this.requestForm = this.formBuilder.group({
      appointmentDate: new FormControl('', [
        Validators.compose([
          Validators.required
        ])
      ]),
      appointmentTime: new FormControl('', [
        Validators.compose([
          Validators.required
        ])
      ]),
      notes: new FormControl('', [
        Validators.compose([
          Validators.pattern(this.inputValidators.textInput.pattern),
        ])
      ])
    });
  }`
 
#### Expected Behavior

Should see date populate input field upon selection in calendar dropdown.

#### Actual Behavior

Nothing happens when clicking a date in the calendar dropdown.

#### Environment

- Angular: 10.1.0
- CDK/Material: 10.2.0
- Browser(s): Chrome 85.0.4183.83
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 20.04

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/components/pull/20362 which was merged a few days ago, but hasn't been released yet.
