### ISSUE TITLE
bug(MatTable): Sorting arrow in header does not update on sortChange from outside

### ISSUE THREAD

**Issue by akottr** [angular/components#20519]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-fhtjni

Steps to reproduce:
1. Click on 'sort by name'
2. Table is sorted but arrow up (asc search) does not show up
 
 
#### Expected Behavior

What behavior were you expecting to see?
Arrow in the header should follow the sorting order

#### Actual Behavior

What behavior did you actually see?
No sorting arrow in the header is shown

#### Environment

- Angular: 10.1.0
- CDK/Material: 10.2.0
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): ubuntu

**Comment by crisbeto** [comment]
I believe this is the same underlying issue as https://github.com/angular/components/issues/19467.
