### ISSUE TITLE
bug(mat-icon-button): text in mat-icon-button not fully displayed in Safari on Mac

### ISSUE THREAD

**Issue by bit-shube** [angular/components#20521]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-piw1js?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Just open it in Safari on Mac
 
#### Expected Behavior

The text should be fully visible. It works in Chrome and Firefox on Mac

#### Actual Behavior

Text is truncated.

#### Environment

- Angular: ^10.1.0
- CDK/Material: ^10.2.0
- Browser(s): Safari 13.1.2 (15609.3.5.1.3), Chrome 85.0.4183.102, Firefox 80.0.1 (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Catalina 10.15.6 on MacBook Pro

**Comment by crisbeto** [comment]
`mat-icon-button` isn't really meant to show text, it's main purpose is to show icons. Note how the ripple looks weird when you click on it as well.
