### ISSUE TITLE
Mat-Paginator: Ensures elements with an ARIA role that require child roles contain them.

### ISSUE THREAD

**Issue by Sheepu-dev** [angular/components#20529]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/mkqleegjgor?file=app%2Fpaginator-overview-example.ts

Steps to reproduce:
1. Go to the Preview window or copy the URL from Preview window and browse with the browser having Accessibility Insight tool as extension.
2. Run the Accessibility Insight(Keros) tool and check the Result. 
 
 
#### Expected Behavior
Accessibility Insight should not report any violations for Paginator Control.
ARIA Role required by Child Element.

#### Actual Behavior

Ensures elements with an ARIA role that require child roles contain them.

![image](https://user-images.githubusercontent.com/61267553/92718867-0399dc80-f380-11ea-84ad-99253f6f6f61.png)

#### Environment

- Angular:~0.901.1
- CDK/Material:5.2.5
- Browser(s):Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Window

**Comment by crisbeto** [comment]
See the discussion here: https://github.com/angular/components/pull/20082#issuecomment-686622547. Our select is based on a newer version of the ARIA spec that doesn't require an `input` to be placed inside a `combobox`. A lot of these automatic accessibility checks haven't been updated to the latest spec yet.

**Comment by Sheepu-dev** [comment]
@crisbeto I am not running older version of Material .I am running Latest version of Material(i.e 10.2.1) and found same Accessibility Insight Issue. Please refer below screen .

![image](https://user-images.githubusercontent.com/61267553/93326333-42270f80-f836-11ea-9002-127d0cc5f0f9.png)


![image](https://user-images.githubusercontent.com/61267553/93326445-6edb2700-f836-11ea-964f-007190dd4095.png)

Can you please reopen the reported Bug

**Comment by crisbeto** [comment]
The thread I mentioned above (https://github.com/angular/components/pull/20082#issuecomment-686622547) refers to the latest version.
