### ISSUE TITLE
feat(mat-selection-list): Toggle on different event that 'click'

### ISSUE THREAD

**Issue by Akxe** [angular/components#20520]
#### Feature Description

Provide the ability to change the "event" that changes the `selected` state of `list-option` component. 

Options I came up with:
* Click - Current behaviour; DEFAULT
* Double click - Self-explanatory; This is what I actually want for my use case
* Keyboard only - Only allow "space" and "enter" to select options

#### Use Case

Sometimes the click event is bound to something else. In my case, I do use currently highlighted row/option as well as checkboxes.

* The highlighted row/option is used to preview the option (image, description, location in the map).
* The checkboxes reflect what the user has selected as viable options for him.

I need to be able to highlight the option on click, but I want to be able to alter the `selected` state via double click.

## Example
I am currently rewriting angularJS app to angular + material. This is the  [angularJS app](https://mapy.agereklama.cz/8670/?h=5E0C7D34143B3F6F8765813E2063E5CD&v=1&c&s=0&l=0&p=0&nl&t=admin#!#115). 

![Image of the app, in case the link would not be online anymore](https://user-images.githubusercontent.com/2001798/92622349-392dbf80-f2c5-11ea-811e-f8eed8a09d41.png)

The eye in the green list symbolizes the currently selected option. When scrolling through the list you may see that the image above changes, also one of the markers on the map will get a white dot. 

The "checkbox" ("X" or checkmark over small image) tells the user whenever it is the one he wanted or not. On double click, he can toggle the state too.

**Comment by crisbeto** [comment]
You should be able to control it through the `selected` input. E.g.


```
<button (click)="isSelected = true">Toggle</button>

<mat-list-option [selected]="isSelected"></mat-list-option>
```

**Comment by Akxe** [comment]
This looks promising. I will give it a try and get back to you

**Comment by Akxe** [comment]
@crisbeto This does not work as clicking the `<mat-list-option>` will still toggle the on click.

I have tried `<mat-list-option (click)="stopEvent($event)">`, where stop event is: `e.preventDefault()`, `e.stopPropagation` and `e.stopImmediatePropagation()`. But this still does not work.

**Comment by Akxe** [comment]
@crisbeto @mmalerba May I ask you for your view on this? Have I overlooked something? I can make the PR, this looks easy enough...

**Comment by mmalerba** [comment]
I don't think this is a feature we want to add since it would lead to unexpected behavior from an accessibility standpoint. If you're not concerned with accessibility, I recommend using the plain `mat-list` and hooking up the events yourself to manage selection.
