### ISSUE TITLE
bug(MatDialog): Displays at a different size but is fixed by screen refresh

### ISSUE THREAD

**Issue by adamdWork** [angular/components#20524]
#### Reproduction

I can reproduce the issue but not on stack blitz. I have attached animated gif files showing the issue.
 
#### Expected Behavior

When a MatDialog is opened it should display at the correct size.

#### Actual Behavior

When a MatDialog is opened it displays at an unexpected size, refreshing the screen (Ctrl-F5) fixes the issue i.e. if then displays at the expected size.

More details:
Our testers have reported a strange issue when we publish our documents to sharepoint. We are using a  third party document viewer. After the document is published to sharepoint we lock the document as read only using the third party document viewer. We have raised the issue with the third party supplier but their document viewer is in an iFrame so they don't think it could be causing our issue.

After doing this the user opens another dialog box and it displays at unexpected dimensions. If I refresh the screen, the dialog box, displays at its expected dimensions. See attached 37221.gif. We are using a MatDialog component.

The current width of the dialog box and height is set as a percentage. What I did was to hard code the width, height, min width, max width, min height and max height to be a certain amount of fixed screen pixels like this:
        dialogConfig.width = '1000px';
        dialogConfig.minWidth = '1000px';
        dialogConfig.maxWidth = '1000px';
        dialogConfig.minHeight = '600px';
        dialogConfig.height = '600px';
        dialogConfig.maxHeight = '600px';

I then emptied the dialog box of all content (html) and formatting (css) and repeated the steps. I have left the typescript code for the MatDialog as is, but none of that does anything to the width or height. These are only set when the dialog opens. The dialog box is now blank but the issue still exists. I have attached the video 37721_blank. So I really don't think this is an issue with our code. As per above we don't think it is anything to do with the document viewer. Could the MatDialog itself be causing this issue? How do we fix this?

#### Environment

- Angular: 8.2.14
- Material
- Browser(s): Chrome
- Operating System: When I run locally I use windows. The deployed version runs on Azure. The issue appears on the deployed version and when running locally.

**Comment by adamdWork** [comment]
![37721](https://user-images.githubusercontent.com/70997922/92666795-8fdedc00-f34d-11ea-8953-a467a215d059.gif)
![37721_blank](https://user-images.githubusercontent.com/70997922/92666814-98cfad80-f34d-11ea-9515-d5b987218b9d.gif)
Uploading the files again as I didn't get any feedback that they were uploaded successfully.

**Comment by mmalerba** [comment]
I don't think there's enough evidence that this is an issue with Angular Material and not just an issue with the particular application. If you are able to come up with a minimal reproduction that shows the issue is with Angular Material, we'll be happy to take a look.
