### ISSUE TITLE
<mat-select> : screen reader not narrating 'expanded/collapsed' when opened and closed (Accessibility Issue)

### ISSUE THREAD

**Issue by deepakparamesh** [angular/components#20533]
### Issue Description
Screen reader (NVDA) is not narrating 'expanded/collapsed' when they are opened and closed in Material angular version 8.2.3

#### Reproduction

Steps to reproduce:
1. Install any Screen reader.
2. open and close the mat-select while screen reader is 'ON' 
 
#### Expected Behavior

The screen reader should narrate as 'Expanded/Collapsed' when the select is opened/closed

#### Actual Behavior

The screen reader not narrating as 'Expanded/Collapsed' when the select is opened/closed

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Edge Chromium, Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, MacOs, Ubuntu

**Comment by crisbeto** [comment]
`mat-select` had a lot of accessibility issues, apart from the one mentioned here. In 10.2.0 we released a new version with a reworked accessibility pattern.
