### ISSUE TITLE
help(COMPONENT): Responsive grid (tile) colspan for different screens

### ISSUE THREAD

**Issue by Ratikant01** [angular/components#20539]
How can we change grid (tile) colspan values depending on screen size?

`<mat-grid-list cols="12" rowHeight="100%">
  <mat-grid-tile [colspan]="8" id="first">
  </mat-grid-tile>
  <mat-grid-tile [colspan]="4" id="second">
  </mat-grid-tile>
</mat-grid-list>
`

my requirement is like this:
(mat-grid-tile: ids -> "first" and "second")
1) Change the "first" mat-grid-tile colspan to 8 and "second" mat-grid-tile colspan to 4 for lg & xl screens
2) Change the "first" mat-grid-tile colspan to 6 and "second" mat-grid-tile colspan to 6 for md & sm screens
3) Hide "first" mat-grid-tile and change "second" mat-grid-tile colspan to 12 for mobile (xs) screens

any help?

**Comment by crisbeto** [comment]
You can use the `BreakpointObserver` to automatically update the `cols` or `colspan` based on a breakpoint:

```
class YourComponent {
  cols$: Observable<number>;

  constructor(breakpointObserver: BreakpointObserver) {
    this.cols$ = breakpointObserver.observe('(max-width: 599.99px)')
      .pipe(map(state => state.matches ? 6 : 12));
  }
}

// In the template
<mat-grid-list [cols]="cols$ | async"></mat-grid-list>
```

**Comment by crisbeto** [comment]
Closing due to a lack of activity.
