### ISSUE TITLE
Bug-Angular Material-Nested Tree.

### ISSUE THREAD

**Issue by aydinmaz** [angular/components#20549]
In the example of nested Tree ,for the node without children there should't be _**matTreeNodeToggle**_  tag , it is like this : 

  <mat-tree-node *matTreeNodeDef="let node" **matTreeNodeToggle**>
    <li class="mat-tree-node">
      
      <button mat-icon-button disabled></button>
      {{node.name}}
    </li>
  </mat-tree-node>

but it should be like : 

  <mat-tree-node *matTreeNodeDef="let node" >
    <li class="mat-tree-node">
      
      <button mat-icon-button disabled></button>
      {{node.name}}
    </li>
  </mat-tree-node>

by having this tag, everytime you click on a node without children , state of **treeControl.isExpanded(node)**  changes  to false and true ,which is incorrect . in the example it doesn't create problem but in real case if you want to add more logic ,it creates problem.

**Comment by mmalerba** [comment]
This seems to be the example in question: https://github.com/angular/components/blob/master/src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html

Seems like a good issue for a community contribution

**Comment by walvekarnikhil** [comment]
@mmalerba , can I take this up?

**Comment by mmalerba** [comment]
I think someone beat you to it: https://github.com/angular/components/pull/20683
