### ISSUE TITLE
bug(Chips): Comma not working as separator in Chips with Input example on Android

### ISSUE THREAD

**Issue by hhubik** [angular/components#20552]
#### Reproduction

Steps to reproduce:
1.  On Android smartphone, open https://material.angular.io/components/chips/examples
2. Find `Chips with Input` example.
3. Enter `abc,def` in the input box.
 
 
#### Expected Behavior

Entering `,` (comma) should create a new chip.

#### Actual Behavior

A new chip does not get created until `Enter` is tapped.

#### Environment

- Angular: `material.angular.io` as of today
- CDK/Material: `material.angular.io` as of today
- Browser(s): Chrome for Android, using Gboard virtual keyboard version `9.7.05`
- Operating System (e.g. Windows, macOS, Ubuntu): Android Pie

**Comment by crisbeto** [comment]
I believe this is the same issue as https://github.com/angular/components/issues/9237.
