### ISSUE TITLE
Material Angular v10 Datepicker not working with min and max

### ISSUE THREAD

**Issue by alaksandarjesus** [angular/components#20550]
I have a working datepicker working on v 9.x. The project was upgraded to v10 and now in the datepicker the dates are non-selectable

[https://stackblitz.com/edit/angular-ivy-ghliws](stackblitz link)

If i remove the

`[min]="min.startDate" [max]="min.endDate"`

i was able to select dates.

I did cross verify with their api documentation and no change i could notify on their api.

https://material.angular.io/components/datepicker/api

Please let me know what am i missing out on the update.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/19907 which has a fix that should come out in the next patch release.
