### ISSUE TITLE
bug(chips): After adding new chip to a chip list, previous selected chip is lost.

### ISSUE THREAD

**Issue by juan-saad** [angular/components#20555]
#### Reproduction

Check my solution at: https://stackblitz.com/edit/multiple-selection-chips

Steps to reproduce:
1. Add a chip from the list
2. Select the chip from the step 1
3. Add another chip from the list
4. Check console log and you'll see that MatChip.selected is equal to false when it was previously marked as selected.
 
#### Expected Behavior

I would expect to maintain previous selection, to bypass this issue I had to iterate over the whole list of chips and selected the last selected chip.
If you check, in my solution I've created a method to bypass this: **recalculateChipSelection**

#### Actual Behavior

Previously selected chip is Unselected.

#### Environment

- Angular: 10.1.0
- CDK/Material: 10.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This is happening because your `ngFor` is binding to `getSelectedChallenges()`, which is creating a new array instance every time, so the values in the selection model aren't seen as the same.  The `SelectionModel` from the cdk just uses reference equality when doing comparisons.
