### ISSUE TITLE
bug(CdkDragDrop): Autoscroll Not Triggering with Drag and Drop in Material Dialog

### ISSUE THREAD

**Issue by nthompson77787** [angular/components#20563]
#### Reproduction

Stackblitz Example:
[https://stackblitz.com/edit/angular-4jbrc5?file=src/app/dialog-content-example-dialog.html](https://stackblitz.com/edit/angular-4jbrc5?file=src/app/dialog-content-example-dialog.html)

Steps to reproduce:
1. Add CdkDragDrop to dialog component
2. Create a drag and drop list that has many items and extends past the viewport in the dialog so the dialog drag and drop list is scrollable (as seen in my example)
3. Try to drag and drop the top item to the bottom of that drag and drop list and you will see that autoscroll is not triggered within the dialog 
 
#### Expected Behavior

Autoscroll should be triggered in a dialog when moving drag and drop items in a list that extends outside of the viewable container (overflow-y) that would be scrolled.

#### Actual Behavior

Autoscroll is not triggered when trying to move the first item to the last order in the dialog.

#### Environment

- Angular: 10.0.7
- CDK/Material: 10.1.1
- Browser(s): Chrome 84.0.4147.135
- Operating System (e.g. Windows, macOS, Ubuntu): Mac Catalina 10.15.6

**Comment by Achilles1515** [comment]
Add the `cdkScrollable` directive to the `MatDialogContent` directive.

```html
<mat-dialog-content class="mat-typography" cdkScrollable>
<!-- ... -->
</mat-dialog-content>
```

**Comment by nthompson77787** [comment]
Wow! It was that easy?! Awesome @Achilles1515! I updated my Stackblitz with that code to hopefully help someone else who runs into the same issue. Thank you.
