### ISSUE TITLE
cdkDropListGroup not connecting nested cdkDropLists

### ISSUE THREAD

**Issue by kevinmanncito** [angular/components#20567]
#### Reproduction

If I manually connect two nested lists using the `cdkDropListConnectedTo` moving between lists works as expected. If I try to use `cdkDropListGroup` to connect the nested lists it doesn't work. I verified that `cdkDropListGroup` does work when the lists are not nested.

Steps to reproduce:
1. Here is the flat `cdkDropListGroup`:  https://stackblitz.com/edit/flat-drag-drop-group?file=src/app/app.component.html
    * It works without issue dragging between lists
2. Here are the nested lists using `cdkDropListConnectedTo`: https://stackblitz.com/edit/connected-lists?file=src/app/app.component.html
    * It works without issue dragging between nested lists
3. Here are the nested lists using `cdkDropListGroup`: https://stackblitz.com/edit/nested-drag-drop-group?file=src/app/app.component.html
   * I'm unable to drag and drop between the nested lists
 

#### Expected Behavior

The [angular cdk docs](https://material.angular.io/cdk/drag-drop/overview) say:

> If you have an unknown number of connected drop lists, you can use the `cdkDropListGroup` directive to set up the connection automatically. Note that any new `cdkDropList` that is added under a group will be connected to all other lists automatically.

I was expecting the`cdkDropListGroup` to automatically connect my lists even if they are nested.

#### Actual Behavior

Only by manually connecting the lists was I able to get drag and drop to work between nested lists.

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by Achilles1515** [comment]
Drop lists are attached to a group through dependency injection. It is by design that a drop list nested inside of another drop list does not inherit the same group as the parent drop list.

Note how each drop list re-provides a `CDK_DROP_LIST_GROUP` with a value of `undefined`.

https://github.com/angular/components/blob/a098c95d7cc0450bb578b238ee2265f6a6ea8b97/src/cdk/drag-drop/directives/drop-list.ts#L52-L69

Perhaps the docs need to be updated to make this more clear.

**Comment by crisbeto** [comment]
@Achilles1515 is correct that the group only picks up top-level lists. This is by design so that we don't recursively connect any nested list. It's also worth noting that nesting doesn't work very well at the moment which is tracked in #16671.
