### ISSUE TITLE
bug(table): matNoDataRow directive doesn't work when wrapped by another table

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#20560]
#### Reproduction
Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-kclee3?file=src/app/table-wrapped-example.html

Steps to reproduce:
1. Set filter "asd" that has no matches
2. Notice that the message from *matNoDataRow is not displayed
 
 #### Expected Behavior

What behavior were you expecting to see?

![image](https://user-images.githubusercontent.com/12090931/93083441-fecb7600-f668-11ea-91ee-bb14a3f55264.png)

Should display the message from *matNoDataRow 

#### Actual Behavior

What behavior did you actually see?
None is shown

![image](https://user-images.githubusercontent.com/12090931/93083680-55d14b00-f669-11ea-9539-ed13d4ada395.png)

#### Observations

If I move the code from child-table to wrapper-table, the mesage is displayed.
But this solution is odd, since we'll be having table row definitions divided in different files.

Also, in my case, I'm wrapping the behavior of selecting rows, the type of my data (user, card, order...) changes accordingly to the child-table that is used, and so, my message should reflect that.

![image](https://user-images.githubusercontent.com/12090931/93083582-30dcd800-f669-11ea-9548-4db465a0a022.png)

![image](https://user-images.githubusercontent.com/12090931/93083734-6d103880-f669-11ea-9bad-a83c416d050d.png)

#### Environment

- Angular: 10.0.6
- CDK/Material: 10.1.3

**Comment by crisbeto** [comment]
Looks like the issue is two-fold:
1. We don't have a way to programmatically add a no data row.
2. We have to add an example of how to use to the `table-wrapped` example.
