### ISSUE TITLE
Newest Firefox does not validate manually inputted date into datepicker

### ISSUE THREAD

**Issue by munchkindev** [angular/components#20564]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/material/datepicker

### Is this a regression?

 I am not sure.

### Description

 When I copy-pasted the code from the documentation (10th example from the examples page) and tried inputting the date manually in the Chrome browser no validation problems appeared. It even reformated the date (removed useless zeroes I think). Then agian when I use Firefox I get validation error thrown out visually (a.k.a. not in console). 

## 🔬 Minimal Reproduction

https://stackblitz.com/angular/ggmegkeymjo?file=src%2Fapp%2Fdatepicker-locale-example.ts

## 🔥 Exception or Error
<pre><code>

There is no error per se, only a mat-error showing up.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.13.1
OS: win32 x64

Angular: 10.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@angular/material                 10.0.1
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

Firefox 81.0b9 (64-Bit)

**Comment by crisbeto** [comment]
It seems to work for me. Maybe the date that you're entering is invalid, based on your locale?

**Comment by munchkindev** [comment]
@crisbeto thanks for replying. No, the date is inputted in the correct format for my locale. 
The bug appears to be present on Firefox 80.0.1 (Stable) as well... I am using default browser settings.
I forgot to mention that I used Firefox 81.0b9 Developer Edition.

**Comment by crisbeto** [comment]
Can you post the exact text that isn't being validated for you? Also for reference, I was on Firefox 79 which updated to 80, but both were behaving correctly.

**Comment by munchkindev** [comment]
![grafik](https://user-images.githubusercontent.com/62607227/93745424-d1944000-fbf3-11ea-88ca-9b50209e1d41.png)

**Comment by munchkindev** [comment]
I am using the de-DE locale and there should be no error.

**Comment by crisbeto** [comment]
Does it happen on any other browsers, or is it just Firefox. It might be worth revisiting this once Firefox 81 hits the stable channel, but I doubt that it'll have much of an impact. For reference, it still seems to work for me:

![demo](https://user-images.githubusercontent.com/4450522/93745722-ab26d280-fbfc-11ea-99a3-eabc15b84b34.gif)

**Comment by munchkindev** [comment]
Maybe the bug is specific to the de-DE locale? It's just Firefox..

**Comment by crisbeto** [comment]
For what it's worth, that Stackblitz you posted above is set to `ja-JP`, but even changing it to `de-DE` works for me. I'll set the issue back to needing triage so we can revisit it once Firefox 81 comes out. It's worth noting that we don't really do any date parsing ourselves so even if it's a problem, we probably won't be able to do much about it. The date parsing is delegated to the `DateAdapter` which by default passes the string directly into `new Date()` so another approach can be to create your own `DateAdapter` (potentially by extending `NativeDateAdapter`). See the docs for reference: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by munchkindev** [comment]
To anyone having a similar issue - apparently the problem was that I forgot to import the DateAdapter and other of the providings (just check the official documentation). I also needed to install `moment` and `@angular/material-moment-adapter` with `npm i`. After this the code works on every browser :-) Thanks for the date parsing explanation @crisbeto ! It's weird that the code doesn't work only on Firefox if you somehow forget that part. Is there some date parsing logic included in other browsers like Chrome or something?

**Comment by crisbeto** [comment]
It's all the same logic, but it's up to the browser to determine how they implement the `Date` class.
