### ISSUE TITLE
bug(card): box-sizing: border-box does not work when adding border

### ISSUE THREAD

**Issue by kydinh93** [angular/components#20570]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-drfdkd?file=src/app/example-component.css

Steps to reproduce:
1. Create a simple card with click event to add/remove the border
 
 
#### Expected Behavior

What behavior were you expecting to see?
`border-box` should be applied when toggle border visibility.

#### Actual Behavior

What behavior did you actually see?
`border-box` is not applying so the card jerks up and down when toggle border visibility.

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): Chrome, Firefox

**Comment by crisbeto** [comment]
The card gets moved around, because it doesn't have border to begin with and you add one afterwards. Closing since this is an issue with your style override, rather than the styles we provide.
