### ISSUE TITLE
Can you tell me what is this line for, my code works without  ?[@direction]="direction"   

### ISSUE THREAD

**Issue by eMelgooG** [angular/components#20578]
Hello 👋
I don't quite get this:

> `<button (click)="toggleState = !toggleState" mat-button>{{ toggleState ? 'more_vert' : 'more_horiz' }}</button>`
> Does not work for obvious reasons.

I don't see the reason why that wouldn't work — this does seem reasonable to me.

As for your questions about animations, Angular does have this covered!
Here's the official ["getting started" for Angular animations](https://angular.io/guide/animations). I browsed through it just yesterday, and it is quite comprehensible.

I built a [StackBlitz featuring a "toggle button"](https://stackblitz.com/edit/angular-material2-issue15578) like the one you suggested, with Angular-powered transitions.

Here's the gist of it.

```typescript
@Component({
  selector: 'hello',
  template: `
    <button mat-button
      [@direction]="direction"
      (click)="state = !state">
      <mat-icon>more_{{ direction }}</mat-icon>
    </button>`,
  styles: [`h1 { font-family: Lato; }`],
  animations: [
    trigger('direction', [
      transition('horiz <=> vert', [
        style({
          transform: `scale(1.5)`,
          opacity: 0
        }),
        animate('.2s 0s ease-out'),
      ])
    ])
  ]
})
export class HelloComponent {
  @Input() public state: boolean = false;

  protected get direction(): 'vert' | 'horiz' {
    return this.state ? 'vert' : 'horiz';
  }
}
```

Is there something I am missing in your question? Or does my approach help you?

_Originally posted by @ccjmne in https://github.com/angular/components/issues/15578#issuecomment-475792789_

**Comment by jelbourn** [comment]
It's the animation. 
https://angular.io/guide/animations
