### ISSUE TITLE
9.2.4 cd/scrolling/api  

### ISSUE THREAD

**Issue by ChipClark** [angular/components#20576]
# 📚 Docs or angular.io bug report

### Description

API reference for Angular CDK scrolling
INCORRECT
import {CdkScrollableModule} from '@angular/cdk/scrolling';

CORRECT
import { CdkScrollableModule  } from '@angular/cdk/scrolling/scrolling-module';

### What's the affected URL?**
https://v9.material.angular.io/cdk/scrolling/api

**Comment by jelbourn** [comment]
This has been fixed in v10, it should just be `ScrollingModule`.
