### ISSUE TITLE
docs-bug(COMPONENT): No need to configure dialog and bottom sheet via entryComponents

### ISSUE THREAD

**Issue by ajtowf** [angular/components#20574]
#### Documentation Feedback

Both [dialog](https://material.angular.io/components/dialog/overview) and [bottom sheet](https://material.angular.io/components/bottom-sheet/overview) states that the components needs to be configured as entryComponents, quote from the docs:

*Similarly to MatDialog, MatBottomSheet instantiates components at run-time. In order for it to work, the Angular compiler needs extra information to create the necessary ComponentFactory for your bottom sheet content component.*

Given the following deps in package.json both components work fine without declaring them as entryComponents:
 
    "dependencies": {
      "@angular/animations": "^10.1.0",
      "@angular/cdk": "^10.2.0",
      "@angular/common": "^10.1.0",
      "@angular/compiler": "^10.1.0",
      "@angular/core": "^10.1.0",
      "@angular/flex-layout": "^10.0.0-beta.32",
      "@angular/forms": "^10.1.0",
      "@angular/material": "^10.2.0",
      "@angular/platform-browser": "^10.1.0",
      "@angular/platform-browser-dynamic": "^10.1.0",
      "@angular/router": "^10.1.0",
      "rxjs": "^6.6.0",
      "tslib": "^2.0.0",
      "zone.js": "^0.10.2"
    }

works during local dev `ng s`, and production builds `ng build --prod` and with aot `ng build --aot`

**Comment by crisbeto** [comment]
The reason we still have that comment is that we support both Ivy and ViewEngine. `entryComponents` is redundant with Ivy, but is still required by ViewEngine. We should reflect it in the comment though.

**Comment by ajtowf** [comment]
@crisbeto thanks for clarifying that, I agree that the docs should reflect this, created a PR for this to update the docs.

**Comment by jelbourn** [comment]
Thanks for raising this- I'm going to say that we'll leave this as-is for the time being (until ViewEngine goes away) since it's a no-op for Ivy users.

**Comment by ajtowf** [comment]
Great call, better to leave faulty docs as-is than accepting the PR that's ready to be merged with the suggested clarification made by @crisbeto.
