### ISSUE TITLE
cdk-virtual-scroll, mat-table: expandable rows work only when scrolling

### ISSUE THREAD

**Issue by scarabedore** [angular/components#20583]
#### What are you trying to do?

Use virtual scroll with a mat-table having expandable rows:
- https://github.com/angular/components/issues/10122#issuecomment-626647861
- https://material.angular.io/components/table/examples

#### What troubleshooting steps have you tried?

Without scrolling the table, rows can be expanded.
Once the table has been scrolled, rows will not expand, until table is further scrolled.

#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-bug-evpqam?file=src/app/my-table/my-table.component.ts

Steps to reproduce:
1. Click on a row: the row expands correctly.
2. Scroll to the end.
3. Scroll to the top.
4. Click a row: the row doesn't expand.
5. Scroll a little tiny bit (~50px): previously clicked row expands.
  
#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): Firefox, Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
cdk-table doesn't officially support virtual scrolling yet (see https://github.com/angular/components/issues/10122). There's a contributor working on this, but we don't yet have an ETA.

**Comment by scarabedore** [comment]
Changing the click handler from
```html
<tr mat-row *matRowDef="let element; columns: columnsToDisplay;"
    class="example-element-row"
    [class.example-expanded-row]="expandedElement === element"
    (click)="expandedElement = expandedElement === element ? null : element">
</tr>
```
to
```html
<tr mat-row *matRowDef="let element; columns: columnsToDisplay;"
    class="example-element-row"
    [class.example-expanded-row]="expandedElement === element"
    (click)="onClickedRow(element)">
</tr>
```
and adding
```ts
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
[...]
  constructor(private cdr: ChangeDetectorRef) {}
  onClickedRow(element) {
    this.expandedElement = this.expandedElement === element ? null : element;
    this.cdr.detectChanges();
  }
```
did the job.

However, why aren't the changes automatically detected by Angular?
