### ISSUE TITLE
Selected tab label should use text color from theme to match the indicator

### ISSUE THREAD

**Issue by chouclee** [angular/components#2058]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
1. https://material.google.com/components/tabs.html#tabs-usage
"The text color is the same as the tab indicator."

2. https://material.angularjs.org/latest/demo/tabs

#### What is the current behavior?
Font just get bold when tab was clicked. And bold effect only works when tab is focused.

#### What are the steps to reproduce?
http://plnkr.co/edit/dmgo93aaGYwOhK2FULix?p=preview

Looks like the material2 lib in plnkr is not the latest. On my laptop, master branch has same behavior. For both ``md-tab-groups`` and ``md-tab-nav-bar``

#### What is the use-case or motivation for changing an existing behavior?
Follow default material design guide.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular: 2.1.0
Material: master branch
Browsers: Chrome 54.0.2840.98, Safari 9.1.3

#### Is there anything else we should know?
No

**Comment by amysorto** [comment]
The tab selection styling is consistent with [the tab material spec](https://m2.material.io/components/tabs#usage) in the new MDC based tab component (available in v15).
