### ISSUE TITLE
feat(Datepicker): Add an option for a standalone/inline date range picker

### ISSUE THREAD

**Issue by SafaAman** [angular/components#20592]
#### Feature Description
The current datepicker and date range picker are implemented as flyouts on an input field, but a standalone date range picker that could be implemented inline would allow for covering use cases where the flyout isn't desired. 

#### Use Case
* As a user, I want to have a form with a date input and display a date picker to the right/below the input field
* As a user, I want to have a form with a start date and end date in separate input fields, with a date range picker calendar displayed below the two fields

**Comment by hakimio** [comment]
You can already do this using undocumented `mat-calendar` component:
[Calendar date range selection example](https://stackblitz.com/edit/angular-dfqwce?file=src/app/date-range-picker-overview-example.html)

**Comment by zarend** [comment]
Hello @SafaAman, does using the mat-calendar component meet your needs?

-Zach

**Comment by crisbeto** [comment]
You should be able to do this already using `mat-calendar`.
