### ISSUE TITLE
matInput placeholder is missing since update to v10

### ISSUE THREAD

**Issue by shure77** [angular/components#20596]
Since we did the update to Angular Material Version 10, the input placeholder was gone. When rendered in the DOM the placeholder attribute is missing. Attributes like ng-reflect-placeholder and data-placeholder are still there. 

So this code:
<input matInput placeholder="Number" [(ngModel)]="number" (keyup.enter)="applyFilter()" />

Results into this:
`<input _ngcontent-jef-c239="" matinput="" class="mat-input-element mat-form-field-autofill-control ng-pristine ng-valid cdk-text-field-autofill-monitored ng-touched" ng-reflect-placeholder="Number" id="mat-input-3" data-placeholder="Number" aria-invalid="false" aria-required="false">`

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
