### ISSUE TITLE
bug(MAT-CHIP): Non-standard capitalizatin for tabindex

### ISSUE THREAD

**Issue by mcalmus** [angular/components#20602]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://stackblitz.com/edit/components-issue-tmy3hw?file=src/app/example-component.html

#### Expected Behavior

What behavior were you expecting to see?

tabindex should be set using "tabindex"

#### Actual Behavior

What behavior did you actually see?

Must use tabIndex (capital I) to make tabbing work.

See  https://github.com/angular/components/pull/17699

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 
Angular 10
Material 10

**Comment by crisbeto** [comment]
The casing is meant to match the way the native property is spelled. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/tabIndex

**Comment by mcalmus** [comment]
What about this? https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by mcalmus** [comment]
What about this? https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by mcalmus** [comment]
What about this? https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by crisbeto** [comment]
That's an attribute which is case-insensitive. Angular actually has logic to map `tabindex` to `tabIndex`, because it's a common typo https://github.com/angular/angular/blob/11506491393d33ac808da78a3bbb3a8bc9fb5588/packages/core/src/render3/instructions/shared.ts#L983.

**Comment by jelbourn** [comment]
Closing as working-as-intended. This is an unfortunate aspect of the web platform where the _attribute_ is all lower-case but the _property_ is camelCase.
