### ISSUE TITLE
bug(mat-label): Upper case letters with accent are truncated when used in mat-form-field

### ISSUE THREAD

**Issue by JCollerette** [angular/components#20615]
#### Reproduction

https://stackblitz.com/edit/components-issue-utk4dr?file=src%2Fapp%2Fexample-component.html

![image](https://user-images.githubusercontent.com/71652570/93783184-6cdbe400-fbf9-11ea-8a79-0fb61964ded9.png)

Steps to reproduce:
1. Use capital letters with accent as Label in an Input Form Field
 
 
#### Expected Behavior

To be able to see the accents

#### Actual Behavior

The accents are truncated

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.0
- Browser(s): Chrome Version 85.0.4183.102 / Edge Version 85.0.564.51
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro

**Comment by wagnermaciel** [comment]
As a workaround, you can add this to `styles.scss` to fix the issue.

```css
.mat-form-field-label-wrapper .mat-form-field-label {
  overflow: visible;
}
```

https://stackblitz.com/edit/components-issue-tuxkbf?file=src%2Fstyles.scss

**Comment by pgeza** [comment]
I suggest the following as a workaround. 
to preserve: text-overflow: ellipsis;

`
.mat-form-field-label-wrapper .mat-form-field-label {
  overflow: hidden visible;
}
`

**Comment by amysorto** [comment]
The accents being cut off for uppercase letters has been fixed in the MDC based input component which will be available in v15 soon.
