### ISSUE TITLE
You should be able to add arbitrary class bindings to `md-header-cell` elements.

### ISSUE THREAD

**Issue by gopi532** [angular/components#20611]
You should be able to add arbitrary class bindings to `md-header-cell` elements.

_Originally posted by @jelbourn in https://github.com/angular/components/issues/6470#issuecomment-322621918_

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
