### ISSUE TITLE
ERROR in Cannot read property '0' of undefined after Material update

### ISSUE THREAD

**Issue by csaicharan** [angular/components#20628]
I just updated the Angular material from 8 to 10 and then this error pops up, The following are the angular angular dependencies in package.json.

	"@angular/animations": "10.1.0",
		"@angular/cdk": "^10.2.2",
		"@angular/common": "10.1.0",
		"@angular/compiler": "10.1.0",
		"@angular/core": "10.1.0",
		"@angular/fire": "^5.2.3",
		"@angular/forms": "10.1.0",
		"@angular/localize": "^10.1.0",
		"@angular/material": "^10.2.2",
		"@angular/material-moment-adapter": "^10.2.2",
		"@angular/platform-browser": "10.1.0",
		"@angular/platform-browser-dynamic": "10.1.0",
		"@angular/router": "10.1.0",

**Comment by devversion** [comment]
Hello! Thanks for this issue! Unfortunately this issue does not provide enough information. Can you please create another issue showing:

* A stack trace if there is one?
* The full error message
* The commands you explicitly ran (e.g. did this happen during ng update or ng serve)
