### ISSUE TITLE
mat-hint is not aligned

### ISSUE THREAD

**Issue by acherniak** [angular/components#20629]
Steps to reproduce:
Add &lt;mat-hint [align]="'end'">test&lt;/mat-hint>
 
#### Expected Behavior

Aligned to the end

#### Actual Behavior

Aligned to the start

#### Environment

- Angular: 10.1.2
- CDK/Material: 10.2.2
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
Confirmed this issue https://stackblitz.com/edit/angular-mtjdtn?file=src/app/form-field-hint-example.html

**Comment by acherniak** [comment]
@crisbeto what's ETA on the fix?

**Comment by crisbeto** [comment]
There's a pending PR with a fix, but I can't give an ETA since it has to go through the same process as the rest of our PRs. If it's urgent, you should be able to apply the same styles yourself.
