### ISSUE TITLE
bug(MatInput): Safari password autofill UI not shown

### ISSUE THREAD

**Issue by JohnKis** [angular/components#20639]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-catfhd?file=src/app/example-component.html

Steps to reproduce:
1. Click on the first password input field
2. Click on the second password input field
 
 
#### Expected Behavior
The Safari autocomplete UI should be visible on both password inputs.

#### Actual Behavior
The Safari autocomplete UI is only visible on a the second (non-Material) input.

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): Safari 13.1.2
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina 10.15.6

**Comment by JohnKis** [comment]
Possibly related to #17677

**Comment by mmalerba** [comment]
We intentionally hide input decorations for things like the number input spinner because they don't look great with the Material UI. Though in this case it does seem to take away an important bit of functionality. We should probably add some exception to not remove this on Safari.
