### ISSUE TITLE
FocusMonitor TypeError: Cannot read property 'remove' of undefined (classlist)

### ISSUE THREAD

**Issue by Lolmewn** [angular/components#20632]
While using @angular/cdk ~10.2.2 and @angular/material ^10.2.2 I keep encountering the following error:
```
TypeError: Cannot read property 'remove' of undefined
    at FocusMonitor._toggleClass (a11y.js:1928)
    at FocusMonitor._setClasses (a11y.js:1957)
    at FocusMonitor.stopMonitoring (a11y.js:1897)
    at MatTooltip.ngOnDestroy (tooltip.js:249)
    at executeOnDestroys (core.js:9070)
    at cleanUpView (core.js:8992)
    at destroyViewTree (core.js:8796)
    at destroyLView (core.js:8945)
    at RootViewRef.destroy (core.js:9679)
    at ComponentRef$1.destroy (core.js:22234)
    at resolvePromise (zone.js:1215)
    at resolvePromise (zone.js:1165)
    at zone.js:1277
    at ZoneDelegate.invokeTask (zone.js:407)
    at Object.onInvokeTask (core.js:27418)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Zone.runTask (zone.js:179)
    at drainMicroTaskQueue (zone.js:583)
```

The error occurs when I navigate from one page to the other. I noticed the MatTooltip class in the stacktrace, and I'd like to note that while many of the components on the page use tooltips, none were active during the time of navigation (this was instigated by a div with routerLink inside a MatMenu).
The error appears to completely break the website, leaving only a background color. Refreshing the page successfully completes the navigation. 
If any further information is needed, please let me know.

**Comment by crisbeto** [comment]
Can you post the element that you're attaching the tooltip to? I think that this could happen if it's on an SVG element and you don't have a polyfill for `classList`.

**Comment by Lolmewn** [comment]
@crisbeto Of course. I searched for instances of matTooltip in *.html files, the following elements use matTooltip:
```
<button mat-icon-button (click)="openPreview(row)" [disabled]="!row.status" matTooltip="{{'ANNOUNCEMENTS.PREVIEW' | translate}}">

<span *ngIf="isLive(location)" class="location-live-tag" matTooltipShowDelay="100" matTooltip="{{'BUILDING_NAV.LIVE_TOOLTIP' | translate}}" matTooltipPosition="right">LIVE</span>

<button mat-mini-fab class="add-button" matTooltip="{{'SETTINGS.BUILDING.VACATION.NEW' | translate}}" (click)="add(vacations)">
    <mat-icon>add</mat-icon>
</button>
<button mat-mini-fab class="import-button" matTooltip="{{'SETTINGS.BUILDING.VACATION.IMPORT' | translate}}" (click)="openImportModal(importDialog)">
    <mat-icon>cloud_download</mat-icon>
</button>

<mat-icon color="warn" matTooltip="{{'MENU.ERROR_LOADING_LOCS' | translate}}">error</mat-icon>

<div matTooltip="{{'INTERVALS.RT_UNAVAILABLE' | translate}}">
    <span [innerHTML]="'INTERVALS.' + int.name | translate"></span>
</div>

<div (click)="remove(event)" (mousedown)="$event.stopPropagation()" *matTooltip="'DELETE' | translate" class="delete-btn">x</div>
```

Since you're suspecting SVG elements, perhaps the tooltip on the mat-icon is the issue? This specific tooltip is hidden most of the time (only shows when an error occurs while loading data from some backend) though.

**Comment by crisbeto** [comment]
Thanks, none of these are using SVG in a way that would break it. `mat-icon` isn't a problem either, because the `svg` node is inside the `mat-icon` node. The one that looks suspicious is the `*matTooltip="'DELETE' | translate"` since prefixig the `matTooltip` with a `*` will turn it into a comment node. You should be able to change it to just `[matTooltip]="'DELETE' | translate"`. Can you try it and let me know if it helps? Even if it's an issue in your code, we should be detecting this and throwing a better error.

**Comment by Lolmewn** [comment]
@crisbeto This does indeed seem to fix the issue. Thanks for your help! I hope this helps to track down any potential bug/issue with the (mis)handling of Angular components.

**Comment by jelbourn** [comment]
Closing since this seems to be resolved / working as expected.
