### ISSUE TITLE
bug(mat-selection-list): Check icon is not properly aligned when using zoom levels below 100% on firefox

### ISSUE THREAD

**Issue by Johannitor** [angular/components#20630]
![Missalignment at 90%](https://user-images.githubusercontent.com/50795659/93865057-0f619900-fcc6-11ea-8649-0c76c8036331.png)

We encountered this bug within our application (Angular 9.1.9 & Material 9.2.4) but it can easily be reproduced on the official Angular Material docs for the latest version (Angular 10.1.0 & Material 10.2.2).

#### Reproduction

Docs page where this can be reproduced: [https://material.angular.io/components/list/overview#selection-lists](https://material.angular.io/components/list/overview#selection-lists)

Steps to reproduce:
1. Visit the above linked [docs page](https://material.angular.io/components/list/overview#selection-lists) in **Firefox**
2. If not already there, scroll down to "Selection lists"-section
3. Select one or more options in the "List with selection"-example
4. Decrease zoom level (for me the misalignment is most noticable at 90%)
5. There should now be a noticeable misalignment of the check icon within the checkbox

This behaviour appears to be only present in Firefox. Chrome handles the alignment with lower zoom-levels fine.
 
#### Expected Behavior

Check icon is properly aligned in the middle of the checkbox.

#### Actual Behavior

Check icon is shifted to the top-left corner

#### Environment

- Screen Resolution: 1920x1080
- Angular: 9.1.9 & 10.1.2
- CDK/Material: 9.2.4 & 10.1.0
- Browser: Firefox 80.0.1
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by wagnermaciel** [comment]
Won't fix. This bug will be fixed by the mdc version of the component

<img width="1526" alt="Screen Shot 2020-09-22 at 2 24 39 PM" src="https://user-images.githubusercontent.com/25158423/93939250-5d36cb00-fcdf-11ea-8925-a3e2b917ec93.png">
