### ISSUE TITLE
Question: can we expect @angular/material-moment-adapter to be deprecated?

### ISSUE THREAD

**Issue by john--** [angular/components#20641]
This isn't an issue. Just a question.

I use @angular/material-moment-adapter in my Angular project. It's been brought to my attention that the Moment.js project is basically being deprecated and they encouraging others to find an alternative. Does this mean that the same can be said for @angular/material-moment-adapter? Should I start looking for a replacement?

**Comment by Splaktar** [comment]
I believe their post was that MomentJS is done, not dead. I don't believe that we have plans to remove the adapter in v11 or v12, so you shouldn't need to be in a rush to migrate to something that doesn't exist (see https://github.com/angular/components/issues/20599 for progress on adapters for other date libraries). Once those other adapters are done, then you would be free to use the one that works best for your project.
