### ISSUE TITLE
help(Theming): Is it possible to apply a dark theme to the scrollbar?

### ISSUE THREAD

**Issue by PHPadawan** [angular/components#20643]
Hello,

I am trying to apply a dark theme to the scrollbar because it does not go along with a dark theme. 

<img width="115" alt="13cea3a5481b8a3a8141772912b59e62" src="https://user-images.githubusercontent.com/12775942/94074847-5a7cc880-fdfa-11ea-99a6-04863f5f952a.png">

I tried it with a mixin but it seems, once its loaded, it does not change. Is it even possible with the cdkScrollable to archiv this?

Thanks in advance!

**Comment by crisbeto** [comment]
We don't provide pre-made scrollback styling, because it can't be done reliably across browsers. You can write your own styles based on top of our themes by following the theming guide: https://material.angular.io/guide/theming.
