### ISSUE TITLE
bug(mat-card): align in mat-card-actions can be set to 'middle' but get error "Type '"middle"' is not assignable to type '"start" | "end"'."

### ISSUE THREAD

**Issue by hisham** [angular/components#20642]
#### Reproduction

Steps to reproduce:

Set align property of mat-card-actions to 'middle'
 
 
#### Expected Behavior

Buttons are aligned in middle of view with no errors. 

#### Actual Behavior

Buttons are aligned in middle of view, but I get these errors in terminal: 

```
 error TS2322: Type '"middle"' is not assignable to type '"start" | "end"'.
    36   <mat-card-actions align="middle">
                           ~~~~~~~~~~~~~~


```

#### Environment

- Angular: 10.1.3
- CDK/Material: 10.2.2
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
`middle` isn't a supported value since it isn't something in the Material Design spec.
