### ISSUE TITLE
IQ Server picking up "smart-webcomponents-angular 7.1.0" from this project

### ISSUE THREAD

**Issue by folterung** [angular/components#20651]
My team is using Angular Material in our project and for some reason our IQ Server is picking up an issue with licensing for "smart-webcomponents-angular 7.1.0" which it believes is coming from this project (below is a screenshot). I have searched the dependencies and cannot find any mention of it.

I apologize for such a bizarre question but any insight into why this may be occurring would be extremely useful. 

## Screenshot(s)

![image](https://user-images.githubusercontent.com/4267615/94158569-8cb91500-fe50-11ea-988e-1f8c6af385d6.png)

**Comment by crisbeto** [comment]
There is no mention of that package anywhere in our project so it's probably an issue on your end. It might be a package that you depend on that in turn depends on `@angular/material`.
