### ISSUE TITLE
bug(MatExpand): Newly added item to panel not toggle able

### ISSUE THREAD

**Issue by behuda** [angular/components#20661]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-tn6hwr

Steps to reproduce:
1.  Open console then type `window.foo()`
 
#### Expected Behavior

The last added panel is not toggle-able on click of the header, you must click outside for it to toggle properly.

#### Actual Behavior

Should toggle on click of header

#### Environment

- Angular: 10.1.3
- CDK/Material: 10.2.2

You might why call window.foo()
window.foo() is simulation data coming from external BT device.

**Comment by crisbeto** [comment]
It's because `foo` is being run outside of the Angular zone. You can fix it by changing it to this:

```
constructor(private cdr: ChangeDetectorRef, ngZone: NgZone) {
  window["foo"] = () => ngZone.run(() => this.add());
}
```
