### ISSUE TITLE
bug(tree): Leaf nodes are not collapsed if top-level folder is collapsed

### ISSUE THREAD

**Issue by helmbold** [angular/components#20665]
#### Reproduction

The bug is reproducible with the flat tree example in the [official documentation](https://material.angular.io/cdk/tree/overview). What is the same as the respective [Stackblitz example](https://stackblitz.com/angular/kerxmngqjav?file=src%2Fapp%2Fcdk-tree-flat-example.ts). 

Steps to reproduce:
1. Expand "Vegetables" node and then "Green" and "Orange" nodes.
2. Collapse "vegetables"
 
 
#### Expected Behavior

All nodes under "Vegetables" should disappear (should be collapsed).

#### Actual Behavior

"Green" and "Orange" disappear, but the leaf nodes are still visible.

Expanded nodes:
![image](https://user-images.githubusercontent.com/5079980/94411217-9ad0a380-0178-11eb-9611-142e527323d5.png)

After collapsing "Vegetables":
![image](https://user-images.githubusercontent.com/5079980/94411310-b76cdb80-0178-11eb-8390-cfbae7b6a8c3.png)

#### Environment

- Angular: 10.2.2
- CDK/Material: 10.2.2
- Browser(s): Chrome 85
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
This looks like an issue for the cdk flat tree example. The material flat and nested tree examples work fine, and the cdk nested tree example works fine.
