### ISSUE TITLE
onKeydown(event) requires deprecated attribute event.keyCode.

### ISSUE THREAD

**Issue by James-Vanguard** [angular/components#20670]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/cdk/fesm2015/a11y.js

### Is this a regression?
No, but the previous version supported the event.keyCode and event.which attributes, which were not deprecated before but are now

### Description
The onKeydown(event) function 

## 🔬 Minimal Reproduction

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 12.3.0
OS: win32 x64

Angular: 9.1.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.9
@angular-devkit/build-angular      0.901.9
@angular-devkit/build-ng-packagr   0.901.9
@angular-devkit/build-optimizer    0.901.9
@angular-devkit/build-webpack      0.901.9
@angular-devkit/core               9.1.9
@angular-devkit/schematics         9.1.9
@angular-devkit/schematics-cli     0.901.9
@angular/cdk                       9.2.4
@angular/material                  9.2.4
@ngtools/webpack                   9.1.9
@schematics/angular                9.1.9
@schematics/schematics             0.901.9
@schematics/update                 0.901.9
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**
Attachments

[Enironment.txt](https://github.com/angular/angular/files/5293969/Enironment.txt)

[a11y.zip](https://github.com/angular/angular/files/5293995/a11y.zip)
![2020-09-28_13-00-44 onKeydown only takes event with deprecated value](https://user-images.githubusercontent.com/72038157/94465707-4fc18b00-018e-11eb-8674-8a96880e1dff.png)

**Comment by James-Vanguard** [comment]
> Hi @James-Vanguard, this question is related to Material Components, so I'm transferring this ticket to the Components repo for further investigation. Thank you.

Thanks for your help Andrew

**Comment by crisbeto** [comment]
This has come up in the past and the reasons we use it are that:
1. At the time when we wrote most components, `KeyboardEvent.key` wasn't widely available in all browsers.
2. Even if `key` is available, it isn't consistent across browsers (e.g. IE/Edge call the up arrow `Up`, whereas other browsers call it `ArrowUp`).
3. Even though `keyCode` is marked as deprecated, it likely isn't going anywhere, because of the amount of code out there that depends on it.

**Comment by James-Vanguard** [comment]
Hello Kristiyan,

Thank you for explaining the issue. We are currently updating our component logic automated testing to remove all deprecated values. As such some of our tests which create an event and add values to it are no longer working with this function, but the function is necessary to test the component. I understand your reasoning for keeping event.keyCode as an option. Since the value is deprecated, please add a conditional to allow for the use of either event.key, event.code, or both in the onKeydown(event) function. Please let me know when you will be able to push this. Thank you so much for your help.

--
James Kelly
Client Experience | Full Stack Developer
Defence Building

**Comment by jelbourn** [comment]
Switching to the `key` property is currently tracked under https://github.com/angular/components/issues/7374
