### ISSUE TITLE
feat(schematics): allow for using @nrwl/nx generate on @angular/material add schematic

### ISSUE THREAD

**Issue by troywweber7** [angular/components#20675]
#### Feature Description

`@nrwl/nx` is becoming more popular for managing mono-repos. However, `nx` doesn't have an `nx add` command, only an `nx generate` command. It would be nice to have some sort of schematic alias that would allow the `ng add @angular/material` logic to be run within an `nx` mono-repo.

There are some hurdles to overcome. At the moment, you can only run `ng add @angular/material` if you chose angular instead of `nx` as your CLI. If you choose `nx` as your CLI, then it generates a `workspace.json` instead of an `angular.json`. You can kind of get around this by moving `workspace.json` to `angular.json`, installing the angular CLI, and then running the `ng add` command, but it would be nice if there was first-class support for usage in an `nx` mono-repo using the `nx` CLI.

**Comment by jelbourn** [comment]
@kyliau IIRC there's a way to run an `ng add` schematic via the `ng generate` command, yes?

**Comment by alan-agius4** [comment]
@jelbourn, you can run the `ng-add` schematic from another schematic, although prior to running the `ng-add` schematics, the package will need to be installed, this logic and logic to save the package in the package.json as dependency, dev dependency or not save it at all is only available in Angular CLI (https://github.com/angular/angular-cli/blob/master/packages/angular/cli/commands/add-impl.ts). 

This seems to me that it should be a feature request to `nx`.

**Comment by jelbourn** [comment]
@alan-agius4 that wasn't quite what I had in mind. I decided to just try it out and yes, you can use `ng generate` to run the `ng add` command so long as you install the package first:
```
ng generate @angular/material:ng-add
```

Not sure if nx supports this, but that would be a feature request for nx.
