### ISSUE TITLE
I have the same issue even I've already imported MatRadioModule into my module

### ISSUE THREAD

**Issue by roberto-github-ctrl** [angular/components#20671]
I have the same issue while I've already imported MatRadioModule into my module

_Originally posted by @meysam-mahmoodi in https://github.com/angular/material.angular.io/issues/308#issuecomment-571456153_

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular-material2`.
