### ISSUE TITLE
bug(mat-form-field): Cannot set property validator of [object Object] which has only a getter

### ISSUE THREAD

**Issue by mackelito** [angular/components#20677]
#### Reproduction

Steps to reproduce:
1.  see console on https://stackblitz.com/edit/angular-material2-issue-1chnbs?file=app%2Fcustom-input%2Fpostal-code.component.ts
 
 
#### Expected Behavior

Not expecting this error message :)

**Comment by crisbeto** [comment]
It seems like a problem with your own code. The same error is thrown even if all the Material directives are removed: https://stackblitz.com/edit/angular-material2-issue-5mymmz?file=app%2Fcustom-input%2Fpostal-code.component.html

**Comment by mackelito** [comment]
@chisbeto oh crap you're right!.. Thx!
hmm any ideas on why?

**Comment by mackelito** [comment]
The problem was that I was not setting the control correctly..
`[formControl]="ngControl?.control"`
