### ISSUE TITLE
feat(COMPONENT): Time Picker. 

### ISSUE THREAD

**Issue by siddhant-dev** [angular/components#20688]
#### Feature Description

To have time picker clock similar what we have for Android library. 

#### Use Case

To apply WFH timing on my corporate system.

**Comment by Totati** [comment]
Duplicate of https://github.com/angular/components/issues/5648

**Comment by siddhant-dev** [comment]
> Duplicate of #5648

My god it is has been pending for 3 years now. 😮

**Comment by siddhant-dev** [comment]
Closing this as it a duplicate feature request. #5648
