### ISSUE TITLE
docs-bug(Input): email examples don't use email type

### ISSUE THREAD

**Issue by mfishma** [angular/components#20682]
#### Documentation Feedback

The examples for email input don't use the input `type` of `email`. There's a real opportunity to improve the user experiences of those who tend to copy and paste a lot of code from these examples. Would you add `type="email"` to the `<input>` field in those examples, both in the overview and in the examples pages?

If using `type="email"` causes problems, at least please provide at least one code example, or calling out why it doesn't play well with Material Angular.

**Affected documentation pages:** 
* https://material.angular.io/components/input/examples
* https://material.angular.io/components/input/overview

Impact: Our documentation often refers back to the documentation on this site, however, now we have to include these caveats and instructions on the email forms in order to get the correct keyboard to appear on mobile devices.

**Comment by walvekarnikhil** [comment]
@jelbourn , can I take this up?
Do we need to change the input type for all emails?

**Comment by mfishma** [comment]
please consider a P4 - this is a small change with big impact, as it reminds developers to use the right type in order to bring up the relevant keyboards on mobile, improving user experience.

**Comment by jelbourn** [comment]
@walvekarnikhil feel free to send a PR
