### ISSUE TITLE
bug(dateRangePicker): Date range picker minimum date is set one month ahead of value

### ISSUE THREAD

**Issue by AdrianBorg** [angular/components#20691]
#### Reproduction

https://stackblitz.com/edit/angular-aiay7d?file=src%2Fapp%2Fdate-range-picker-overview-example.ts

Steps to reproduce:
1. Add min date using base Javascript Date object
2. Try scroll to the min date in the date picker
 
#### Expected Behavior

The minimum date is from the minimum date specified onwards. 
If a date initialised as `new Date(2020, 1, 10)` is set as the minimum date, the earliest date that can be selected is the 10th of Jan 2020.

#### Actual Behavior

The minimum date is from a month after the date specified. 
If a date initialised as `new Date(2020, 1, 10)` is set as the minimum date, the earliest date that can be selected is the 10th of Feb 2020.

#### Environment

- Angular: 10.1.4
- CDK/Material: 10.2.3
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
This is working as expected and isn't something that we control. The month numbers in the `Date` constructor are 0-based so the 10th of January would be `new Date(2020, 0, 10)`. You can test it out by pasting it in the JS console of your dev tools. You can check the `monthIndex` here for more info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
