### ISSUE TITLE
help(youtube-player): not able to play any videos from YouTube Movies channel

### ISSUE THREAD

**Issue by video-vocabulary** [angular/components#20715]
#### What are you trying to do?

Play videos from [this](https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g) channel with `youtube-player` component

#### What troubleshooting steps have you tried?

`youtube-player` component is not able to play any videos from [this](https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g) channel in production mode, but able to play them in development mode (`ng serve`)

#### Reproduction

Here is the example - https://stackblitz.com/edit/angular-ivy-emrpyh

Steps to reproduce:
1. add `youtube-player` component to the project
2. as `videoId ` set any video from [this](https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g) channel
  
#### Environment

- Angular: 10.0.8
- CDK/Material:
- Browser(s): Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Catalina Version 10.15.7 (19H2)

**Comment by crisbeto** [comment]
I get a message that the author has restricted access to the video in my country. There's also a setting that prevents videos from being embedded that could be blocking it.

**Comment by video-vocabulary** [comment]
> There's also a setting that prevents videos from being embedded that could be blocking it.

But it works on my local computer with `ng serve`

**Comment by Achilles1515** [comment]
I think this is just a Chrome (or maybe Chromium) issue and doesn't have anything to do with the cdk/youtube-player. Both videos in your StackBlitz work fine in FireFox, for example.

**Comment by acosmicflamingo** [comment]
There’s a project that also stopped working today: https://github.com/youtube/youtube-ios-player-helper. I wonder if YouTube itself changed something with the iframe API that broke everything that depends on it for embedding YouTube videos

**Comment by video-vocabulary** [comment]
> I think this is just a Chrome (or maybe Chromium) issue and doesn't have anything to do with the cdk/youtube-player. Both videos in your StackBlitz work fine in FireFox, for example.

Interesting observation, I've tried it on Safari and indeed it works

**Comment by jelbourn** [comment]
Closing this since I don't think it has anything to do with the Angular wrapper; it seems like this is something with the underling YouTube iframe embed.
