### ISSUE TITLE
bug(material): Pink/Blue Grey themes not not working

### ISSUE THREAD

**Issue by rbalet** [angular/components#20716]
#### Reproduction

The stackblitz : https://stackblitz.com/edit/angular-ivy-fj2vxv?file=angular.json

Steps to reproduce:
1.  `npm install -g @angular/cli`
2.  `ng new my-dream-app`
3.  `cd my-dream-app`
4.  `ng add @angular/material`
5.  _Choose a prebuilt theme name, or "custom" for a custom theme:_ Pink/Blue Grey
6.  _Set up global Angular Material typography styles?_ Yes
7.  _Set up browser animations for Angular Material?_ Yes

Into the `app` folder

**app.module.ts**
```ts
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    MatInputModule,
    MatFormFieldModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

**app.component.html**
```html
<form class="example-form">
  <mat-form-field class="example-full-width">
    <mat-label>Favorite food</mat-label>
    <input matInput placeholder="Ex. Pizza" value="Sushi" />
  </mat-form-field>

  <mat-form-field class="example-full-width">
    <mat-label>Leave a comment</mat-label>
    <textarea matInput placeholder="Ex. It makes me feel..."></textarea>
  </mat-form-field>
</form>

```
 
#### Expected Behavior
![image](https://user-images.githubusercontent.com/44493964/95019995-dc75b880-0668-11eb-81a0-46ee7170d2c9.png)

#### Actual Behavior
![image](https://user-images.githubusercontent.com/44493964/95019988-d54eaa80-0668-11eb-9052-1b979ac4ab58.png)

#### Environment

- Angular: 10.1.4
- CDK/Material: 10.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
It does work. The problem in your case is that you're using a dark theme, but you haven't set the background color to anything so the components blend into it. You can fix it by adding the `mat-app-background` class either to the body or to a wrapper element around the app. Note that if you add it to the `app` node itself, you'll also need a `display: block`.
