### ISSUE TITLE
Angular Material vs Angular MDC

### ISSUE THREAD

**Issue by nitulkukadia** [angular/components#20718]
What is difference between both of this and which is preferable to use?

Angular Material - Material Design components for Angular - https://material.angular.io
Angular MDC - Material Web Components for Angular -  https://github.com/trimox/angular-mdc-web

How it is different from implementation and contributors point of view?
Are they both maintained by google ?

**Comment by mrmokwa** [comment]
In a really shallow description, both are component librarys that use material design as guideline to build it's components. 

The first one is maintained by Angular team (Google).
The second is a third-party integration incorporating Google Material Components library

Also, you should avoid opening issues for support questions. More info at https://github.com/angular/components/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by jelbourn** [comment]
The second library you link there is not an official Angular library; it's a community project based on MDC Web. Here's the gist:

* Angular Material today is a standalone implementation of Material Design components built by the Angular team at Google
* MDC Web is a separate library of component _primitives_ built by the Material Design team at Google

The Angular team has been working on refreshing the existing Angular Material components to incorporate MDC's primitives internally, these new versions of the components are available for testing in the `@angular/material-experimental` package today, but they're not yet stable. In a future version of Angular, they will replace the existing components.

See the Angular roadmap for more information: https://angular.io/guide/roadmap
