### ISSUE TITLE
bug(Slider): Jaws and NVDA incorrectly announcing decimal numbers

### ISSUE THREAD

**Issue by Aivanic** [angular/components#20719]
#### Reproduction

https://stackblitz.com/edit/components-issue-nr5zgy?file=src%2Fapp%2Fexample-component.html
(stackblitz have weird behaviour, you have to add tabindex="0" for working example)

Steps to reproduce:
1.  Enable Jaws or NVDA
2.  Focus slider
3.  Move slider
 
 
#### Expected Behavior

Screen reader announce 0.2

#### Actual Behavior

Screen reader announcing e.g. 0.20000068

#### Environment

- Angular:  V. 10.1.3
- CDK/Material: V. 10.2.3
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Reopening since the fix had to be reverted.
