### ISSUE TITLE
Add mat-icon dynamically is missing in docs

### ISSUE THREAD

**Issue by FilipMachinia** [angular/components#20726]
#### Documentation Feedback

The docs don't mention how to add `<mat-icon>` dynamically from js.

Its not straightforward as you need to add classes like `mat-icon` and `material-icons`.

**Affected documentation page:** https://material.angular.io/components/icon/overview

**Comment by jelbourn** [comment]
@FilipMachinia can you clarify what you mean by adding dynamically?

**Comment by FilipMachinia** [comment]
Hi @jelbourn, I mean something like this:
```
const expandSectionIcon = document.createElement('mat-icon');
expandSectionIcon.innerHTML = 'expand_less';
expandSectionIcon.className = 'mat-icon material-icons';
``` 

 It would be great to have this mentioned in the docs.

**Comment by jelbourn** [comment]
This isn't really how Angular is meant to be used; Angular expects that your DOM structure is codified in a component template. Angular does have APIs for dynamically loading components: https://angular.io/guide/dynamic-component-loader, but you would generally not do direct DOM manipulation like this.
