### ISSUE TITLE
bug(MatCheckbox/MatSlideToggle/DragDrop): Some components don't work in mobile for upgraded angularjs material to angular material project

### ISSUE THREAD

**Issue by KyleDavis** [angular/components#20725]
#### Reproduction

I've created a stackblitz for this: https://stackblitz.com/edit/angular-ivy-qhprlc
You can view the issue in mobile: https://angular-ivy-qhprlc.stackblitz.io/

Steps to reproduce:
1. Create an angularjs to angular upgrade project which includes both angularjs material and angular material.
2. Add a MatCheckbox, MaxSlideToggle, or DragDrop list.
 
#### Expected Behavior

I expect the checkbox to check when tapped.

I expect the slidetoggle to toggle when tapped.

I expect to be able to sort the list when taping and dragging on an item.

#### Actual Behavior

What behavior did you actually see?

MatCheckbox will display the ripple effect, but not become checked when tapped.

MatSlideToggle also displays the ripple effect, but does not toggle when tapped.

The dragdrop list will pick up the item and move it when tapped and drag. Releasing the tap does not drop the time. Tapping again in the list will move the item originally selected to the new place tapped. Tapping outside of the list will drop the item where it was released.

Note this a further investigation of issues #19466 and #17146, which I've finally been able to get a repo on stackblitz for.
https://github.com/angular/components/issues/19466
https://github.com/angular/components/issues/17146

#### Environment

- Angular: 7.2.8, 8.2.7, 9.1.0, 10.1.4
- CDK/Material: 7.2, 8.2, 9.2, 10.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Android

**Comment by BobDankert** [comment]
Confirmed behavior, affects Chrome on Android and mobile device mode in Chrome for Windows. Works properly on iOS Safari (tested on iPad). Firefox on Android works with checkbox and slide-toggle, though the drop event in the drag-drop list has issues. Edge on Android works the same as Chrome (as expected)

**Comment by jelbourn** [comment]
I would guess that the gesture handling code from AngularJS Material is interfering with event handling here. That gesture code is notorious for having unintended side-effects. If you're not relying on any of the gesture interactions in AngularJS (mainly the swipes IIRC), I'd recommend [turning it off](https://material.angularjs.org/latest/api/service/$mdGestureProvider#mdgestureprovider-disableall) and seeing if that fixes it.

**Comment by KyleDavis** [comment]
Thank you so much! Can confirm that disabling the gestures fixes the issues I was seeing.

Here's the fixed version for anyone else who runs across this. https://stackblitz.com/edit/angular-ivy-jbjrpj
