### ISSUE TITLE
cannot pass options as a template to mat-select

### ISSUE THREAD

**Issue by kartikgreen** [angular/components#20738]
I am trying to pass mat-options as a template to mat-select but it doesn't work. Below here is the link to stackblitz,

https://stackblitz.com/edit/angular-mat-select-with-ngmodel-mujorn?embed=1&file=app/select-overview-example.ts

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
