### ISSUE TITLE
Scrollblock for Dialogs and Bottom Sheets: Always add 'cdk-global-scrollblock' class to the root when opening a bottom sheet or dialog

### ISSUE THREAD

**Issue by ortegamarcel** [angular/components#20734]
#### Feature Description

When opening a dialog/bottom sheet the 'cdk-global-scrollblock' is applied to the html tag, preventing the background to be scrollable through the modal. According to the answer of @crisbeto "The dialog won't try to block scrolling if the page isn't scrollable" - https://github.com/angular/components/issues/16864

But actually I have a use case (with bottom sheets), where it would be useful to always apply the class.

#### Use Case

I have a bottom sheet menu, from which I can open other bottom sheets. The first (menu) bottom sheet applies 'cdk-global-scrollblock'. When the other one is opened, the background is not scrollable anymore (because of the blocking class), so it removes it again, making the page in the background scrollable again.

My use case is only with bottom sheets, but since the similar issue, https://github.com/angular/components/issues/16864, describes the same problem, I assume dialogs and bottom sheets work the same in this behaviour. Correct me, if I am wrong.

#### Feature Request (Summary)

If 'cdk-global-scrollblock' is applied and a new bottom sheet/dialog is opened, the class should stay.

**Comment by jelbourn** [comment]
Realistically, I don't see us adding an option for this because it's pretty niche. I think you would have better luck toggling content inside of a single bottom-sheet rather than opening multiple bottom-sheets.
