### ISSUE TITLE
feat(MatDatepickerModule): Inclusive End Date on date range selection

### ISSUE THREAD

**Issue by alexvdvalk** [angular/components#20736]
#### Feature Description

Currently when using the new date range picker component, the end date is exlucded from the date selection. It would be helpful to have an option to set the date picker to be inclusive of the end day.

#### Use Case

A user is looking for something on a single specific day, so they may set the start and end dates in the range to the same value, expecting that the range would be set for that day only.

Currently if you select the same start and end date in your range, it's essentially a range of 0 seconds. The component allows this, but it doesnt really make sense.

**Comment by jelbourn** [comment]
I get how it could be confusing, but people can always set the end date to the next unit in the future, so I wouldn't see us adding an API for this.
