### ISSUE TITLE
feat(mat-checkbox): add functionality for adding custom icons for mat checkbox states

### ISSUE THREAD

**Issue by jnenning** [angular/components#20733]
#### Feature Description

A user should be able to set an own icon for e.g. the indeterminate state. It would be nice if you can set a SVG file in CSS or register your icon in the matIconRegistry and then give the user the functionality to set the icon for the states after that.

#### Use Case

A use case would be when someone wants to use his own icon set. I have currently a project where I have got an icon which looks similar to the material but with some changes (checkmark is thicker and the border-radius was changed).

**Comment by jelbourn** [comment]
`MatCheckbox` is pretty tightly targeted at the Material Design spec, so we don't have any plans to support customizing the checked icons.
