### ISSUE TITLE
bug(DATEPICKER): DatePicker shows prior date inside the calendar but correct date in the input field.

### ISSUE THREAD

**Issue by akshaybhat30** [angular/components#20749]
#### Reproduction

Stackblitz link :- https://stackblitz.com/edit/angular-moment-date-adapter-overriding-f89kp8?file=app%2Fdatepicker-formats-example.ts

Steps to reproduce:
1. Set current timezone to +5:30 (Chennai).
2. Check the value in the input (10/01/2020) and the date selected in the calendar is showing as 01.
3. Change the system timezone to -12 such that there is a difference in date and check the component again.
4. the value shown outside is still 10/01/2020 but the date selected inside the component is 30.

**Note i have made a custom moment date adapter for this case to handle date format based on the locale of the user**
 
 
#### Expected Behavior

What behavior were you expecting to see?
The date selected should be 10/01/2020 and should be consistent at both the places.

#### Actual Behavior

What behavior did you actually see?
the value shown outside is still 10/01/2020 in the input box but the date selected inside the component when you open the calendar is 09/30/2020.

![image](https://user-images.githubusercontent.com/56155908/95450834-d6ded380-08f1-11eb-96c4-48d6802c360a.png)

#### Environment

- Angular: 8
- CDK/Material: 8.0.0
- Browser(s): Google chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

Stackoverflow link:- https://stackoverflow.com/questions/62319261/issues-with-custom-moment-date-adapter

**Comment by crisbeto** [comment]
A few notes:
1. It could be a problem with your own adapter since all the date logic is driven by it. Does the same issue happen if you use the `MomentDateAdapter` from `@angular/material-moment-adapter`?
2. The Stackblitz link throws an error so it's difficult to investigate.
3. You're running an older version of Angular. Have you tried updating to v10?

**Comment by akshaybhat30** [comment]
Hi @crisbeto 

1. No it does not happen when i use MomentDateAdapter. I built this custom date adapter for handling the date format according to different user locales.

2. Here is the sharable link for the [Stackblitz](https://angular-moment-date-adapter-overriding-f89kp8.stackblitz.io)

3. No did not try updating it to v10 but might be updating it in future once we have a go ahead from our team.

**Comment by jelbourn** [comment]
@akshaybhat30 since this doesn't happen with the Moment adapter, the most likely cause is something in your custom date adapter.
