### ISSUE TITLE
MatSort: Unable to provide DataSource.sort directive

### ISSUE THREAD

**Issue by fosteman** [angular/components#20744]
What are you trying to do?
Setting up Sorting mechanism for a table. Followed through the guidelines: 
provided `matSort` directive in template
loaded up `MatSortModule`
installed `@ViewChild(MatSort) sort`
assigning `this.dataSource.sort = this.sort` with `this.dataSource = new MatDataSource([])`

#### What troubleshooting steps have you tried?
`console.log(this.sort)` is OK.
```
MatSort {_disabled: false, _isInitialized: true, _pendingSubscribers: null, initialized: Observable, sortables: Map(1), …}
initialized: Observable {_isScalar: false, _subscribe: ƒ}
sortChange: EventEmitter_ {_isScalar: false, observers: Array(2), closed: false, isStopped: false, hasError: false, …}
sortables: Map(1) {"Score" => MatSortHeader}
start: "asc"
_direction: ""
_disabled: false
_isInitialized: true
_pendingSubscribers: null
_stateChanges: Subject {_isScalar: false, observers: Array(1), closed: false, isStopped: false, hasError: false, …}
direction: (...)
disableClear: (...)
disabled: (...)
__proto__: _class4
```

What are you seeing that does not match your expectations? 
1. `sorting-header` does not work on number column
2. Console:

```
Attempting to configure '__source' with descriptor '{"value":"MatSortHeader","configurable":true}' on object 'function MatSort() {
    var _this;

    Object(_Users_timfosteman_work_space_speak_client_node_modules_babel_runtime_helpers_esm_classCallCheck__WEBPACK_IMPORTED_MODULE_3__["default"])(this, MatSort);

    _this = _super.apply(this, arguments);
    /** Collection of all registered sortables that this directive manages. */

    _this.sortables = new Map();
    /** Used to notify any child components listening to state changes. */

    _this._stateChanges = new rxjs__WEBPACK_IMPORTED_MODULE_9__["Subject"]();
    /**
     * The direction to set when an MatSortable is initially sorted.
     * May be overriden by the MatSortable's sort start.
     */

    _this.start = 'asc';
    _this._direction = '';
    /** Event emitted when the user changes either the active sort or sort direction. */

    _this.sortChange = new _angular_core__WEBPACK_IMPORTED_MODULE_4__["EventEmitter"]();
    return _this;
  }' and got error, giving up: TypeError: Cannot define property __source, object is not extensible
```

#### Reproduction

Although we would not see the WebPack error above in the StackBlitz, am I missing something ?
https://stackblitz.com/edit/components-issue-ykw4sz?devtoolsheight=33&file=src/app/example-component.html

  
#### Environment

- Angular: 10.1.3
- CDK/Material: 10.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
It's hard to tell why you're getting the error since it doesn't happen on the Stackblitz. My hunch is that the `sort` isn't available yet during `ngOnInit` so you can try setting up the query like `@ViewChild(MatSort, {static: true}) sort`.

As for why your demo isn't working, it's because you've capitalized the names in `matColumnDef` and they're supposed to be lower case. Here's a working fork of your example: https://stackblitz.com/edit/components-issue-5yfcqn?file=src%2Fapp%2Fexample-component.html
