### ISSUE TITLE
text blurred in IE when using virtual scroll

### ISSUE THREAD

**Issue by ZOUJIELynn** [angular/components#20755]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. check cdk-virtual-scroll-viewport
2. the reason is `transform: translateZ(0px)` in IE
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
I couldn't reproduce it myself against the examples on material.angular.io, although I have seen the same issue in other places. I think that while removing the `translateZ(0)` would fix the blurring, it was put in there as a performance optimization so it can cause other problems. Leave it up the @mmalerba to make a call on whether we should fix it.

**Comment by mmalerba** [comment]
If it problematic in IE we could probably just remove it in IE and leave it for other browsers
