### ISSUE TITLE
bug(Datepicker): Hover state on the picker persists after the calendar is clicked away

### ISSUE THREAD

**Issue by nwmv** [angular/components#20750]
#### Reproduction

Steps to reproduce:
1. Click on the dropdown arrow to reveal the calendar.
2. Click somewhere other than the calendar (e.g., a bit to the right of the dropdown arrow) to hide the calendar.
 
 
#### Expected Behavior

The dropdown arrow reverts to its default state, and in particular no grey circle surrounds it.

#### Actual Behavior

A grey circle that appears to be a hover state persists around the dropdown arrow.

#### Environment

- Angular: Angular 2
- CDK/Material: Material
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
It's because we restore focus to where it was before the datepicker was opened and it's intentional. It's unlikely that we'll remove it, because it's an accessibility feature, but we can add a `restoreFocus` option similar to the one in `MatDialog`.

**Comment by nwmv** [comment]
Glad to know it. Thank you.

**Comment by geromegrignon** [comment]
@crisbeto i can work on a PR
