### ISSUE TITLE
docs-bug(dialog): Suggest using strong types for MAT_DIALOG_DATA

### ISSUE THREAD

**Issue by bampakoa** [angular/components#20759]
#### Documentation Feedback

In the **Sharing data with Dialog component** section, the type of `MAT_DIALOG_DATA` in the described example is set to `any`. Given that it is encouraged to use strongly typing in Angular projects, I would suggest to use the following interface for the example:

```
interface DialogData {
 name: string;
}

export class YourDialog {
  constructor(@Inject(MAT_DIALOG_DATA) public data: DialogData) { }
}
```

**Affected documentation page:** https://material.angular.io/components/dialog/overview#sharing-data-with-the-dialog-component

I would love to work on a related PR if you find it useful. 🙏

**Comment by crisbeto** [comment]
Feel free to send in a PR. It might be worth doing a code search in case there are other places like it in the docs.

**Comment by bampakoa** [comment]
Thanks very much for your feedback @crisbeto . I will prepare a PR for this 👍

**Comment by bampakoa** [comment]
@crisbeto is there any `yarn` script that I can run to verify my changes or should I just rely on the markdown preview?

**Comment by crisbeto** [comment]
Verifying them is somewhat convoluted since the docs site is in a separate repo. You can rely on the Markdown preview.
