### ISSUE TITLE
CdkVirtualScrollViewport.measureScrollOffset('bottom') not going to 0 on 1.25 or 1.50 Windows Desktop Scaling settings

### ISSUE THREAD

**Issue by liviualexandrubobocu** [angular/components#20776]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Use a list wrapped in cdk-virtual-scroll-viewport in HTML.
2.  Add  @ViewChild(CdkVirtualScrollViewport) virtualScroll: CdkVirtualScrollViewport  to the component
3.  Inject private scrollDispatcher: ScrollDispatcher in component constructor
4. Register scroll event via scrollDispatcher this.scrollDispatcher.scrolled(10).pipe(...)
5. Use Display Settings 125% or 150%.
6.  Measure this.virtualScroll.measureScrollOffset('bottom') when scrolling. Bottom of the list will be 0.59.. instead of 0

 
#### Expected Behavior

What behavior were you expecting to see?
this.virtualScroll.measureScrollOffset('bottom') should be 0 when scrolling to the bottom of the list

#### Actual Behavior

What behavior did you actually see?
this.virtualScroll.measureScrollOffset('bottom') should be 0.59.. when scrolling to the bottom of the list

#### Environment

- Angular: 7.2.0
- CDK/Material: 7.3.7
- Browser(s): Chrome 85.0.4183.102 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by mmalerba** [comment]
This seems to have been fixed. Here's a stackblitz showing it working even at 125% and 150%: https://stackblitz.com/edit/angular-q2rshe
