### ISSUE TITLE
help(Datepicker): set the format dynamically

### ISSUE THREAD

**Issue by noamyg** [angular/components#20774]
I'd like to be able to set the format of dates dynamically, without changing the locale.

I've succesfully used `this.dateAdapter.setLocale('en-GB')`. However, I'd like to be able to get the user preferred format from API (MM/DD/YYYY or DD/MM/YYYY, for instance) and to set it dynamically.
I know I can do something like `if (value === 'DD/MM/YYYY') this.dateAdapter.setLocale('en-GB')` but I want to make it 100% generic.

Thanks!

**Comment by jelbourn** [comment]
There's an example of setting a custom format in the docs:
https://material.angular.io/components/datepicker/examples
