### ISSUE TITLE
Angular pipes and directives could not be used as a global state for all modules?

### ISSUE THREAD

**Issue by Hasnat150822** [angular/components#20782]

**Comment by geromegrignon** [comment]
This question is about Angular, not about Angular/Components.
Could you move it to the framework @alan-agius4 ?

To avoid using a big Shared Module you can create a Module per Pipe/Directive in order to get more control of what is actually being used in your lazy loaded modules.

**Comment by Hasnat150822** [comment]
> This question is about Angular, not about Angular/Components.
> Could you move it to the framework repo?
> 
> To avoid using a big Shared Module you can create a Module per Pipe/Directive in order to get more control of what is actually being used in your lazy loaded modules.

ok I have move this question into angular repo to suggest feature.
