### ISSUE TITLE
Add StackBlitz starters for harnesses

### ISSUE THREAD

**Issue by thw0rted** [angular/components#20784]
I want to report an issue with unit testing features of the library (like `TestbedHarnessEnvironment`) but the template only links to one starter Stackblitz, which is not configured to run tests.  The Angular docs include a link to [this Stackblitz](https://stackblitz.com/angular/nnvnepvjlxl) which uses Karma to run tests in browser, and works great, but does not use this library at all.  I'm struggling to create a test-running Stackblitz that illustrates my problem.

It would be great if someone more familiar with Stackblitz than I am could set up a new starter, forked from [the current one](https://stackblitz.com/fork/components-issue), that runs one or two simple unit tests against the starter page -- "it should have the text 'Basic Button' on the button", "it should call the event handler when the user slides the toggle", etc.  Then it would be easy to fork the test template and show problems with the test helpers.

**Comment by jelbourn** [comment]
We've actually already started adding examples for harnesses that will run in StackBlitz: https://github.com/angular/components/pull/20722

**Comment by thw0rted** [comment]
Thanks for the example, Jeremy.  The tests are helpful, but I was actually more interested in the Stackblitz side -- pre-rigging the deps for Karma etc,, configuring the runner, that sort of thing.  I could probably come up with one myself, but the point of the issue was that such a preconfigured starter should be part of the Bug Report template, to facilitate reporting bugs in the test utilities.

**Comment by annieyw** [comment]
we can work towards adding it to the bug template but meanwhile you can try forking from [here](https://stackblitz.com/angular/pybjypxbmdj?file=src%2Fapp%2Fbutton-harness-example.spec.ts)

**Comment by thw0rted** [comment]
Perfect, Annie, that's exactly what I had in mind!  Thanks, I'm going to add my fork to #20785 now.

**Comment by annieyw** [comment]
Closing as this seems to be resolved.
