### ISSUE TITLE
bug(DatePicker): Days put into a single long row for production build

### ISSUE THREAD

**Issue by johannesjo** [angular/components#20794]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. git clone https://github.com/johannesjo/super-productivity
2. yarn
3. ng serve --prod
4. Open up app
5. Create a task by entering something into the input and pressing enter
6. Click on the other part of the newly created task so that a border appears around it
7. press t
8. click "time spent on other day"
9. click calendar icon next to "Date for new entry*"

#### Expected Behavior
Days are put into rows in packs of 7.

#### Actual Behavior
All days are in a single row

#### Environment

- Angular: 10.0.9
- CDK/Material: 10.2.4
- Browser(s): Latest Chrome and earlier versions (84.0.4147.105)
- Operating System: Dosn't matter

**Comment by jelbourn** [comment]
@johannesjo I tried your app and the Datepicker renders normally:
![image](https://user-images.githubusercontent.com/838736/96184716-b7493b80-0eed-11eb-8c9d-2e9aba218077.png)

**Comment by johannesjo** [comment]
@jelbourn are you sure? Did you start the app with the  `--prod` flag?

**Comment by geromegrignon** [comment]
I tried it with the `--prog` flag as well and it renders normally too.

**Comment by johannesjo** [comment]
@geromegrignon did you mean `--prod`instead of `--prog`? İ just tested again and it does reproduce as described on my desktop browser and my mobile chrome as well. But İ will do some more testing, for different browsers etc..

**Comment by geromegrignon** [comment]
@johannesjo i meant `-prod` sorry.

As it works fine on cloning the project twice, try to clone it in another folder and follow the steps you described to reproduce the issue.
If it renders normally, i would consider deleting node_modules and run `yarn install`

**Comment by johannesjo** [comment]
@geromegrignon oh. Deleting node_modules did the trick. Thank you very much. I was convinced that this might not be the issue, as I encountered this also on my CI, but that might have been due to caching... 

I am closing this. Sorry, for the inconvenience.
