### ISSUE TITLE
help(Mat-Tree): Trying to add a window click event is swallowed by CdkTreeNodeToggle. Why?

### ISSUE THREAD

**Issue by gioele-antoci** [angular/components#20795]
I am simply trying to attach a click event to the entire window.
I noticed that the event is swallowed by `CdkTreeNodeToggle` [here](https://github.com/angular/components/blob/master/src/cdk/tree/toggle.ts#L39
). 

Why is the event not propagated?

#### Reproduction
https://stackblitz.com/edit/angular-dma36r?file=src/app/tree-checklist-example.ts
Steps to reproduce:
1. Click around with the console open and notice that the event is swallowed when clicking on a leaf checkbox.

**Comment by jelbourn** [comment]
Clicks in the tree are not propagated because they would bubble up to parent nodes and potentially cause them to toggle as well. You probably want to use `addEventListener` with `useCapture` to accomplish this.
