### ISSUE TITLE
mat-tab-group | add mat-tab-body-previous & mat-tab-body-next in mat-tab-body DIV

### ISSUE THREAD

**Issue by ahmedkhairydev** [angular/components#20804]
#### Feature Description

I wanna get access to the previous & next tab, and I can't do that!

#### Use Case

the use case is I wanna translate animation in RTL direction, and I can't do that because I can't access the previous & next tab!

**Comment by jelbourn** [comment]
`mat-tab-group` already reverses the animation in RTL mode. It's not really clear from your issue what you're trying to accomplish and what you've tried. Feel free to open a new issue that provides more detail.
