### ISSUE TITLE
ngx-mask adding extra - for mask 99999.9999-99999

### ISSUE THREAD

**Issue by aaberhane** [angular/components#20806]
I am using Angular 10.1.5 and ngx-mask 10.0.4.  This is how my control looks like in the html
<input type="text" class="form-control" aria-label="Matter" aria-describedby="Matter" formControlName="matterIDsel" mask="99999.9999-99999" pattern="^[\d]{5}\.[\d]{4}-[\d]{5}" [specialCharacters]="['-','.']" [showMaskTyped]="true" [dropSpecialCharacters]="false" />
but on the application when you type the format ends up as follows 99999.9999--9999

**Comment by jelbourn** [comment]
`ngx-mask` isn't something from this repo.
