### ISSUE TITLE
Bug(mat-select): mat-select not showing mat-option

### ISSUE THREAD

**Issue by mjsaijem09** [angular/components#20816]
mat-option in not popping up in mat-select
```
<mat-form-field appearance="fill">
    <mat-label>Toppings</mat-label>
    <mat-select [formControl]="toppings" multiple>
        <mat-option *ngFor="let topping of toppingList" [value]="topping">{{topping}}</mat-option>
    </mat-select>
</mat-form-field>
```

```
import { FormControl } from "@angular/forms";

export class NewSalesComponent implements OnInit {
  toppings = new FormControl();
  toppingList: string[] = [
    "Extra cheese",
    "Mushroom",
    "Onion",
    "Pepperoni",
    "Sausage",
    "Tomato"
  ];

  constructor() {}

  ngOnInit() {}
}
```
stackblitz
https://stackblitz.com/edit/layouting?file=src%2Fapp%2Fnew-sales%2Fnew-sales.component.html
![image](https://user-images.githubusercontent.com/50950599/96242971-b17b5500-0fd6-11eb-8902-4e3a5585f2d6.png)

**Comment by kozrkozr** [comment]
Add @angular/animations to your dev dependencies and import BrowserAnimationsModule (from '@angular/platform-browser/animations') to your AppModule

**Comment by mjsaijem09** [comment]
@kozrkozr Thanks
