### ISSUE TITLE
MAT-OPTION: Screen reader announces an option with label of "No" as "Number"

### ISSUE THREAD

**Issue by tp1906** [angular/components#20815]
This issue was closed under #20810, however, I do believe it is an issue within angular material.  This issue occurs while using angular material version 10.2.1 but works fine under version 9.1.0.

#### Reproduction

**Angular Material v10.2.1** - https://stackblitz.com/edit/components-issue-upbgwh?file=package.json **(doesn't work)**
**Angular Matearial v9.1.0** - https://stackblitz.com/edit/components-issue-egx1ge?file=package.json **(works fine)**

Steps to reproduce:

Using version 10.2.1...

1. Run Chromevox extension
2. Tab to mat-select
3. Hit Enter to open drop-down
4. Use arrow keys to navigate to options
5. Listen to screen reader, when "No" is selected it will read "Number three of four". All other options read the label and then position correctly.

Using version 9.1.0...

1. Run Chromevox extension
2. Tab to mat-select
3. Hit Enter to open drop-down
4. Use arrow keys to navigate to options
5. Listen to screen reader, it will read No correctly

 
 
#### Expected Behavior

What behavior were you expecting to see?

It should read label and then position. For my example, it should read, "No, three of four"

#### Actual Behavior

What behavior did you actually see?

It reads, "Number three of Four". It looks like it is translating No to Number which is a shorthand for Number.

#### Environment

Angular: 10.1.0
CDK/Material: 10.2.0
Browser(s): Chrome  86.0.4240.75
Operating System (e.g. Windows, macOS, Ubuntu): Windows
ChromeVox: 53.0.2784.6

**Comment by tp1906** [comment]
I wanted to follow-up and let you know that this does NOT work with NVDA either.  I will be testing on JAWS 18 once it's been installed.

**Comment by jelbourn** [comment]
I tested both your v10 and v9 examples with NVDA. Both of them read "Number" for the "No" option. However, I don't think that this behavior has anything to do with `MatSelect`; we don't have a label string "Number" anywhere in our codebase, and it's certainly nowhere in the DOM for the example. This leads me to conclude that this is just the behavior of the screen reader whenever it encounters "No" like this, which is outside of our direct control.

**Comment by tp1906** [comment]
I did notice that mat-select accessibility changed from v9 to v10.  In v9, mat-select would not announce the item that was selected.  In v10 this  works but now I have the ‘No’ issue.  I recall that in v9 mat-select had a role=listbox but it is now combobox similar to the mat-autocomplete.  Not sure if this has anything to do with this issue

NVDA Test:  both v9 and v10 don’t work.

JAWS 18 Test:  both v9 and v10 work.

The only way I could get this to read correctly on all screen readers is to add a comma after the word ‘No’.

What reader should we use with Angular Material components so that it passes our 508 compliance guidelines?  Thanks!

**Comment by jelbourn** [comment]
I chatted with some other a11y folks in Google and this definitely seems like a bug in either NVDA or one of its dependencies. You can reproduce the behavior without Angular Material at all with something like 
```html
<div role="listbox"><div role="option" tabindex=0>no</div></div>
```

I'd recommend filing an issue with NVDA.
