### ISSUE TITLE
MAT-OPTION: Screen reader announces an option with label of "No" as "Number"

### ISSUE THREAD

**Issue by tp1906** [angular/components#20810]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-m1awrt?file=src/app/example-component.html

Steps to reproduce:
1. Run Chromevox extension
2. Tab to mat-select
3. Hit Enter to open drop-down
4. Use arrow keys to navigate to options
5. Listen to screen reader, when "No" is selected it will read "Number three of four".  All other options read the label and then position correctly.
 
 
#### Expected Behavior

What behavior were you expecting to see?

It should read label and then position.  For my example, it should read, "No, three of four"

#### Actual Behavior

What behavior did you actually see?

It reads, "Number three of Four".  It looks like it is translating No to Number which is a shorthand for Number.  

#### Environment

- Angular: 10.1.0
- CDK/Material:  10.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
- ChromeVox: 53.0.2784.6

**Comment by tp1906** [comment]
I am using Chrome version: 86.0.4240.75

**Comment by jelbourn** [comment]
I don't believe this is anything we're doing; it seems like that's just the screen-reader deciding it's an abbreviation.

That said, it's worth pointing out that the ChromeVox browser extension is _not_ supported and is not a real screen-reader.

**Comment by tp1906** [comment]
Actually, I do believe this is an issue as it works fine while using Angular Material 9.1.0 and I tested using ChromeVox

Angular Material v10.2.1 - https://stackblitz.com/edit/components-issue-upbgwh?file=package.json (doesn't work)
Angular Matearial v9.1.0 - https://stackblitz.com/edit/components-issue-egx1ge?file=package.json (works fine)
