### ISSUE TITLE
Align MDC-based chip harnesses with existing MatChipHarness

### ISSUE THREAD

**Issue by jelbourn** [angular/components#20826]
The MDC-based chip harness is missing several APIs from the original due to some implementation differences between the two. We need to bridge this before the MDC-based component is considered fully stable.

**Comment by MatteoVH** [comment]
I'm taking on the addition of the `remove` method for the MatChipHarness.

**Comment by MatteoVH** [comment]
Hi Kristiyan,

My fix (#20831) shouldn't be affected by #20801, but thank you for the heads up.

When testing my PR by using the harness in my unit tests, it seems like the custom `width` `propertyName` doesn't actually matter. The `(removed)` output is still triggered and the HTML element is correctly removed from the DOM.

**Comment by MatteoVH** [comment]
Hey, looks like I was wrong and the `width` `propertyName` is necessary. My project's unit test was passing for other reasons that were unrelated (still not sure why, exactly.) I'll wait for #20764 to be merged.

**Comment by crisbeto** [comment]
Resolved in https://github.com/angular/components/pull/21051.
