### ISSUE TITLE
feat(cdk-row, mat-row): Allow with `a` elements

### ISSUE THREAD

**Issue by MendyBerger** [angular/components#20833]
#### Feature Description

Allow `cdk-row` to be used on an `a` element (and maybe other elements as well).

`a[cdk-row]`

#### Use Case

Allowing rows to be anchor tags would help with accessibility, since currently developers [use JavaScript](https://stackoverflow.com/a/53765608/5253155) to mimic links.

**Comment by jelbourn** [comment]
The table is a real native `<table>` element, which must contain `<tr>` (which then contains `<td>`). Having an `<a>` as a child of a `<table>` (or `tbody`, `thead`, etc.) would be invalid, especially for a11y.

**Comment by MendyBerger** [comment]
According to the docs `mat-table` and `cdk-table` can be used with or without a `table` element.
When using it without the table element I think an `a` element does make sense.

**Comment by MendyBerger** [comment]
@jelbourn would you mind answering on my comment and/or reopen this issue?

**Comment by jelbourn** [comment]
We do have a non-table version of the API, but we generally discourage its use since it doesn't offer as good of an a11y experience as the native table. Because of that, we wouldn't want to add any exclusive features to the non-table version.

**Comment by MendyBerger** [comment]
@jelbourn thanks for the reply
