### ISSUE TITLE
docs(material/select): select with dialog example in dev app not selecting options

### ISSUE THREAD

**Issue by rameshworsht** [angular/components#20840]
#### Reproduction
This issue can be reproduced on the dialog example: https://material2-dev.firebaseapp.com/select 

Steps to reproduce:
1. Navigate to Dialog
2. Use the Voice Over (mac screen reader) and open the select drop-down
3. Try to navigate the option with UP/DOWN arrow key. The VO navigation doesn't select the options
 
 
#### Expected Behavior

What behavior were you expecting to see?
- Using VO is in safari, DOWN/UP arrow navigation should read/announce the select option.

#### Actual Behavior

What behavior did you actually see?
The screen reader does read the selected options in the select component inside the dialog model. 

Relate Issue: https://github.com/angular/components/pull/20695

#### Environment

- Angular: 9+
- CDK/Material: CDK
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

GIF: http://www.giphy.com/gifs/ZGTv8ZW9I2UtXYOD0x

**Comment by annieyw** [comment]
This doesn't seem to be a VoiceOver specific issue as the select isn't working with normal navigation. This seems to just be an issue with the specific example. Here you can see that the select works fine in a dialog: https://stackblitz.com/edit/angular-6guxnc?file=src/app/dialog-content-example.ts
