### ISSUE TITLE
mat select and mat-autocomplete is not scrollable on safari

### ISSUE THREAD

**Issue by akshata456** [angular/components#20846]
iphone 11 pro max/13.2
safari 13
angular9
material 9.2.4

mat select dropdown is not scrollable. Check with https://material.angular.io/components/select/examples also it's also not show scrolling in this example. Please take look on this issue. Thanks.

**Comment by jelbourn** [comment]
We tried this on an iOS device and could not reproduce. Do you have more information?

**Comment by akshata456** [comment]
I copy this code from select examples nothing do more , but it's not working. Also try to add virtual scrolling inside mat-select it's gives slow performance. Can you have any idea why this happening and it's only in ios device.

**Comment by jelbourn** [comment]
Currently the material components doesn't support being used with virtual scroll inside of them (#10122). Aside from that, there's not enough information for us to really investigate anything here.
