### ISSUE TITLE
Duplicate mat-chip if same predefined tag was assigned inside ngFor

### ISSUE THREAD

**Issue by ajsemana** [angular/components#20847]
Hi all,

I used the same given sample from the angular component page https://material.angular.io/components/chips/examples which is the "Chips Autocomplete" to be exact. But when I used it inside *ngFor it keeps doing exactly the same with the other containers who has the same predefined tags. I am using it for a chat application by the way.

Please see below snapshot. Thanks!

![image](https://user-images.githubusercontent.com/19888091/96720941-802acc80-13bc-11eb-9524-5531f3ccc56a.png)

**Comment by geromegrignon** [comment]
Please consider to fill in the issue template : 
```
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?


#### Actual Behavior

What behavior did you actually see?


#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): 

```

Your actual expectation is missing among other things (especially as you are declaring duplicates while looping other data with the predefined tags, which at first sight is working as intended).

**Comment by ajsemana** [comment]
> Please consider to fill in the issue template :
> 
> ```
> #### Reproduction
> 
> Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
> 

![image](https://user-images.githubusercontent.com/19888091/96897106-54344780-149f-11eb-9860-c4359ace75b6.png)

> Steps to reproduce:
> 1. Add the <mat-chip-list #chipList> code wrapped inside an *ngFor
> 2. Since I have a chat application if I send same file with the same default chips as the other files it clones the chips on other containers if you tried to add or remove.
>  
>  
> #### Expected Behavior
> 
> What behavior were you expecting to see?
> I expect that each containers having the autocomplete chips will not copy the same actions as the others. It must act independently with other mat-chip-list conatiners.
> 
> #### Actual Behavior
> 
> What behavior did you actually see?
> I see that the chips from other file containers are copying exactly the same with the other container having the same default chips.
> 
> #### Environment
> 
> - Angular: v6.2.3
> - CDK/Material: v6.2.1
> - Browser(s): Chrome/Firefox/Safari
> - Operating System (e.g. Windows, macOS, Ubuntu): Windows
> ```
> 
> Your actual expectation is missing among other things (especially as you are declaring duplicates while looping other data with the predefined tags, which at first sight is working as intended).

**Comment by geromegrignon** [comment]
is `idx` the index of your file container?
As you are passing it as an argument  to the `assignFileTagChip()` and `assignFileTag()` functions, the problem should lie there. Please consider we don't know your context and please provide all required code to understand how you add tags to the data of each container.

**Comment by ajsemana** [comment]
> is `idx` the index of your file container?
Yes it is the index coming from the ngFor.
![image](https://user-images.githubusercontent.com/19888091/96902729-f1927a00-14a5-11eb-9c70-644ca995913c.png)

> As you are passing it as an argument to the `assignFileTagChip()` and `assignFileTag()` functions, the problem should lie there. Please consider we don't know your context and please provide all required code to understand how you add tags to the data of each container.

Hope the below code helps. I've seen no problem with `assignFileTagChip()` and `assignFileTag()` functions.
What I suspect is the **assignFileCtrl** which I think needs to be declared unique per containers to avoid doing same actions with other containers that has the same default tags during the first render.

**HTML:**

                            <mat-form-field class="assign-chip-list" class="hideElement" id="file-tag-{{idx}}"
                                *ngIf="! message?.isUser && ! message?.isSaved && message?.deliveryStatus === 'done' && isAgent">
                                <mat-chip-list #chipList>
                                    <mat-chip *ngFor="let assignedServiceRequest of message?.tags"
                                        [selectable]="selectable" [removable]="removable"
                                        (removed)="removeFileTag(assignedServiceRequest, assignedServiceRequest?.TagName, idx)">
                                        {{ assignedServiceRequest }}
                                        <mat-icon matChipRemove *ngIf="removable">cancel</mat-icon>
                                    </mat-chip>
                                    <input placeholder="" #assignRequestInput [formControl]="assignFileCtrl"
                                        [matAutocomplete]="auto" [matChipInputFor]="chipList"
                                        [matChipInputSeparatorKeyCodes]="separatorKeysCodes"
                                        [matChipInputAddOnBlur]="addOnBlur"
                                        (matChipInputTokenEnd)="addFileTagChip($event, idx)">
                                </mat-chip-list>
                                <mat-autocomplete #auto="matAutocomplete" (optionSelected)="assignFileTag($event, idx)">
                                    <mat-option *ngFor="let requestData of filteredAssignRequest | async"
                                        [value]="requestData">
                                        {{ requestData.TagName }}
                                    </mat-option>
                                </mat-autocomplete>
                            </mat-form-field>
                            

**TS:**

visible = true;
    selectable = true;
    removable = true;
    addOnBlur = false;
    separatorKeysCodes: number[] = [ENTER, COMMA];
    assignFileCtrl = new FormControl();

assignFileTag(event: MatAutocompleteSelectedEvent, paramIndex: number): void {
        try {
            console.log("assignFileTag >> paramIndex:", paramIndex);

            if (paramIndex >= 0) {
                const value = event.option.value;

                //CHIPS RELATED ACTION HERE            
                if (typeof (this.allServiceRequestList.find(x => x.TagName === value.TagName)) === "object") {
                    if (this.dialog[paramIndex].tags.indexOf(value.TagName) < 0) {
                        this.dialog[paramIndex].tags.push(value.TagName);
                 
                        this.assignFileCtrl.setValue(null);
                    }
                }
            }
        } catch (ex) {
            this._globalService.exceptionError("assignFileTag", ex);
        }
    }

addFileTagChip(event: MatChipInputEvent, paramIndex: number): void {
        const input = event.input;
        const value = event.value;
 
        if (input) {
            input.value = "";
        }

        this.assignFileCtrl.setValue(null);
    }

**Comment by geromegrignon** [comment]
```
What I suspect is the assignFileCtrl which I think needs to be declared unique per containers to avoid doing same actions with other containers that has the same default tags during the first render.
```

Yes i advice you to rely on the FormArray API to get a unique FormControl per message.

**Comment by ajsemana** [comment]
> ```
> What I suspect is the assignFileCtrl which I think needs to be declared unique per containers to avoid doing same actions with other containers that has the same default tags during the first render.
> ```
> 
> Yes i advice you to rely on the FormArray API to get a unique FormControl per message.

Do you have any sample I can follow on how to apply FormArray to assign it on every new container?

**Comment by geromegrignon** [comment]
Without FormArray, just by looping over a list, it works using the autocomplete example from the Angular Material Documentation : https://stackblitz.com/edit/angular-87cxp2?file=src/app/chips-autocomplete-example.ts

If you can't adapt it, please move the issue to stackoverflow as the project works as intended.

**Comment by ajsemana** [comment]
> Without FormArray, just by looping over a list, it works using the autocomplete example from the Angular Material Documentation : https://stackblitz.com/edit/angular-87cxp2?file=src/app/chips-autocomplete-example.ts
> 
> If you can't adapt it, please move the issue to stackoverflow as the project works as intended.

Will do. Thank you for your kind assistance.
