### ISSUE TITLE
feat(DatePicker): Allow custom footer

### ISSUE THREAD

**Issue by meblum** [angular/components#20854]
#### Give option to add a custom footer for the date picker

Currently, there's only the option of adding a custom header to the date picker.
It would be really helpful if a custom footer is allowed as well.

#### Use Case

Giving an option of adding a custom footer will allow developers to add custom functionality to the picker.

Will fix issue #11753
Will also solve #5648

**Comment by meblum** [comment]
@jelbourn I just discovered https://material.angular.io/components/datepicker/api#MatDatepickerActions. Is this a new feature? Looks like it addresses this issue.

**Comment by jelbourn** [comment]
Yes, it does- it even has documentation: https://material.angular.io/components/datepicker/overview#confirmation-action-buttons. Thanks!
