### ISSUE TITLE
feat(material): Allow focus origin to be an optional input to focus() methods.

### ISSUE THREAD

**Issue by jesscxu** [angular/components#20858]
#### Feature Description

WHAT: For Angular Material components that have a focus() method, allow for the origin param to be optional and remove the default origin value.

WHY: For cases where the focus() method is called and the origin is already defined, we don’t want to override the origin using focusVia to always be some default value. In many cases, we want to leave the origin unchanged, but if there are cases that need the origin to be updated, allow for this with an optional origin param.

#### Use Case

If the focus origin value is keyboard, and some interaction happens where we want to set focus to another element somewhere on the page by explicitly calling focus(), then in cases where the focus origin should remain the same, the current implementation causes the origin to change and the interaction to be weird. This is also due to the fact that we use a single, global focus monitor attached to the document body in eventual detection mode. 

Here are the components to update:
-button
-checkbox
-menu item
-menu trigger
-radio
-expansion panel header
-slide toggle
-step header

**Comment by jelbourn** [comment]
Would it work for your use case if the `FocusMonitor` publicly exposed `lastFocusOrigin` so you could just read that and pass it through to the `focus` method manually? 

Changing the default behavior if no origin was specific would be a breaking change that would potentially be difficult to land in Google, so doing it manually would be an easier change to make, especially since we seem to already track the last focus origin.

**Comment by crisbeto** [comment]
Another problem with adding `origin` parameters everywhere is that we'd have to inject and use `FocusMonitor` in components that don't use it at the moment which will be a breaking constructor change.

**Comment by jesscxu** [comment]
Interesting thought, yes that would work for components where we call `focus` and could pass `lastFocusOrigin` in. However, this wouldn't work for Angular Material components that call `focus` on another Angular Material component.

My main concern is that when calling `focus` one would need to know to access the `lastFocusOrigin` from the global `focusMonitor` and pass that through the `focus` call vs. just using `.focus()` which is more intuitive.

I am curious how "bad" the breaking change would be? I attempted to look through the history of some of these focus methods and couldn't exactly understand the reason why the default focus origin (and the chosen value that is different for different components) was necessary? Do you have more background knowledge on that?

**Comment by jesscxu** [comment]
@crisbeto I believe all the components I want to add an `origin` param to (the focus methods of radio, slide toggle, etc.) already inject `FocusMonitor`, though I may have missed something and understand incorrectly!

**Comment by jesscxu** [comment]
@jelbourn I am currently trying to see how many issues my change would cause in Google with button.

@crisbeto Here is an example PR: https://github.com/angular/components/pull/20898 for the change I am proposing for button (and other components as well). 

Let me know if this information helps!

**Comment by mmalerba** [comment]
I think this seems fine as long as it doesn't turn out to be too breaking (which it seems not to be). The proposal isn't to add origin parameters everywhere, its just to stop defaulting the parameter to `'program'` in places where it has already been added. Instead we will allow the origin to be set according to whatever the `FocusMonitor` decides it should be.

**Comment by jesscxu** [comment]
Closing this since it has been resolved and the changes have been made.
