### ISSUE TITLE
bug(MatCheckbox): check/uncheck not working in QQ browser on iPhone

### ISSUE THREAD

**Issue by sashaaro** [angular/components#20852]
#### Reproduction

Steps to reproduce:
1.  Open https://material.angular.io/components/checkbox/overview QQ browser on iPhone
2. try check/uncheck checkbox
 
 
#### Expected Behavior

checkbox should change view when check  /uncheck

#### Actual Behavior

checkbox view does not change

#### Environment

- Angular:10.1.2
- CDK/Material:10.2.1
- Browser(s): QQ Browser 10.8.3.4539
- Operating System (e.g. Windows, macOS, Ubuntu): iPhone ios 12.4.8

https://apps.apple.com/ru/app/qq%E6%B5%8F%E8%A7%88%E5%99%A8-%E7%83%AD%E7%82%B9%E6%96%B0%E9%97%BB%E5%A4%B4%E6%9D%A1%E7%9F%AD%E8%A7%86%E9%A2%91%E6%8A%A2%E5%85%88%E7%9C%8B/id370139302
https://www.dropbox.com/s/aj2685owjni4m1b/IMG_0582.PNG?dl=0
https://www.dropbox.com/s/r6w4uz7rc1uduq3/RPReplay_Final1603376785.MP4?dl=0

**Comment by jelbourn** [comment]
Unfortunately this isn't a browser we support.
