### ISSUE TITLE
Embed Test Documentation in the API Comments

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#20868]
https://fireflysemantics.medium.com/embedding-test-example-documentation-for-api-usability-and-code-flow-d80fef9e7a03

For example it will make reading and understanding the SASS API simpler:

```
// For a given hue in a palette, return the contrast color from the map of contrast palettes.
//@param $color-map
//@param $hue
@function mat-contrast($palette, $hue) {
    @return map-get(map-get($palette, contrast), $hue);
}
```

It would be nice if an example of how to use the API were included in the API description / comments.

**Comment by annieyw** [comment]
We do have some code snippets in the theming guides (eg. https://material.angular.io/guide/theming) Can you clarify where exactly/what type of examples you are looking for?

**Comment by fireflysemantics** [comment]
@annieyw for example in [this issue](https://github.com/angular/components/issues/20874) the code looks like this:

```
    text: map-get($base-palette, $text),

    default-contrast: mat-contrast($base-palette, $default),
    lighter-contrast: mat-contrast($base-palette, $lighter),
    darker-contrast: mat-contrast($base-palette, $darker)
```

And when I saw that I thought `text` is probably an alias for this `default-contrast: mat-contrast($base-palette, $default)`.

However it uses `map-get` which means it's just the default primary color or 500.

If it came with a use case embedded in the comments of the code then it becomes clearer what the intention is.

So for text a CSS or SCSS snippet showing how it is used clears up any confusion and also helps future maintainers of the code base.

I find that it's also really helpful in building out code real time both with respect to building clarity around the API and communicating with team members.

**Comment by jelbourn** [comment]
Closing this since I think the Sass API is now fully documented with the latest rewrites for Angular v12. We don't have any plans to embed example usage in SassDoc.
