### ISSUE TITLE
feat(google-maps): allow ability to update bounds in GroundOverlay

### ISSUE THREAD

**Issue by thomasdmitchell** [angular/components#20865]
#### Feature Description

Allow the ability to update the bounds of a GroundOverlay.

#### Use Case

 Currently it updates opacity, URL so I think it would be useful to allow bounds to update if possible

**Comment by crisbeto** [comment]
This came up when I added the ability to update the other properties. Here's the relevant discussion https://github.com/angular/components/pull/19306#discussion_r423206503
