### ISSUE TITLE
[Question] Should text in mat-palette resolve to a contrast color?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#20874]
#### Question

The [`mat-palette` function](https://github.com/angular/components/blob/caad0b54ed41949f0ee529c152508749875bc9af/src/material/core/theming/_theming.scss) resolves text like this: ` map-get($base-palette, $text)`.  Is that correct?  Seems like it should resolve to a contrast color ...?
```
// Creates a map of hues to colors for a theme. This is used to define a theme palette in terms
// of the Material Design hues.
// @param $color-map
// @param $primary
// @param $lighter
@function mat-palette($base-palette, $default: 500, $lighter: 100, $darker: 700, $text: $default) {
  $result: map_merge($base-palette, (
    default: map-get($base-palette, $default),
    lighter: map-get($base-palette, $lighter),
    darker: map-get($base-palette, $darker),
    text: map-get($base-palette, $text),

    default-contrast: mat-contrast($base-palette, $default),
    lighter-contrast: mat-contrast($base-palette, $lighter),
    darker-contrast: mat-contrast($base-palette, $darker)
  ));

  // For each hue in the palette, add a "-contrast" color to the map.
  @each $hue, $color in $base-palette {
    $result: map_merge($result, (
      '#{$hue}-contrast': mat-contrast($base-palette, $hue)
    ));
  }

  @return $result;
}
```

It seems like perhaps the code author meant to do `mat-contrast` instead of `map-get`?

**Comment by fireflysemantics** [comment]
Also asked this on SO:

https://stackoverflow.com/questions/64505758/what-does-it-mean-to-generate-density-in-angular-material

**Comment by jelbourn** [comment]
The `text` key in palette produced by `mat-palette` is meant to only really be used from a _foreground_ palette, where `text` is the correct key. The contrast colors are keyed under `*-contrast`.
