### ISSUE TITLE
bug(button): Disable button within Directive when using prebuilt theme remains enabled

### ISSUE THREAD

**Issue by stephenlautier** [angular/components#20876]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular10-ivy-mat?file=src/styles.css

Steps to reproduce:
1. Run app
2. **Command A** button remains enabled (even tho its disabled via directive `ssvCommand`) - every 2.5sec should cycle between enable/disable
3. Comment out style import within `style.css` and it will as intended

#### Expected Behavior

When disabling a button within a Directive, when using material AND loaded a prebuilt theme, button should be styled as disabled.

#### Actual Behavior

Button is remained styled as enabled, even though its disabled

#### Environment

- Angular: 10.0.9
- CDK/Material: 10.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

Note this on material 8/9 used to work, updated to 10.x and it didn't

**Comment by crisbeto** [comment]
It's because you're setting a `HostBinding` which is the equivalent of doing `button.disabled = true`. Our disabled styling goes through the `@Input() disabled` which won't be evaluated in this case.

There are a couple of ways around it:
1. You can inject `MatButton` and set the `disabled` property on it. See https://stackblitz.com/edit/angular10-ivy-mat-nyodxk?file=src%2Fapp%2Fcommand.directive.ts.
2. You can bind the `mat-button-disabled` class as a `HostBinding` although then the button will still be clickable, unless you also set the `disabled` property.

**Comment by stephenlautier** [comment]
@crisbeto Thanks for your reply and thanks for the suggested options. Though unfortunately, both options will make the directive dependant on the material itself; in the actual scenario the directive itself doesn't depend on Material, and its a library on its own, so neither of them is an actual solution for me 😞 

It would be nice if there are features that allow you to observe attributes instead of inputs, so things like this will be able to work.

**Comment by crisbeto** [comment]
If we were to support it, we'd either have to check the DOM on each change detection or maintain a `MutationObserver`, on every single button on the page. Given the potential performance degradation it could cause for a complex page, it doesn't sound like a good trade-off for something that is an edge case to begin with.

**Comment by stephenlautier** [comment]
@crisbeto yea not saying material should use `MutationObserver`, but maybe some of angular core to handle such scenarios, efficiently.

Anyway but, so why with Material v9.x or less this used to work correctly? As this is a "regression" with v10.x. If you down version to material 9 in my example it will actually work.

**Comment by crisbeto** [comment]
It probably worked on 9.x, because we used to use the `disabled` attribute for styling. In 10.x we started using the `mat-button-disabled` class in order to support the case where a button appears disabled, but it's still focusable.
