### ISSUE TITLE
feat(material): Add support for character counter

### ISSUE THREAD

**Issue by danieldanielecki** [angular/components#20902]
#### Feature Description

Support for character counter that displays the ratio of characters used and the total character limit. Such a feature [has Vuetify](https://vuetifyjs.com/en/components/text-fields/#counter) and [has been introduced in material-components-web](https://github.com/material-components/material-components-web/pull/4244).

#### Use Case

Limiting upper bound characters of an input field in an easy to follow way for the user.

**Comment by JoeMellon** [comment]
What's wrong with just using `mat-hint` for this?

`<mat-hint align="end">{{ inputName.value.length }} / 256</mat-hint>`

**Comment by crisbeto** [comment]
@JoeMellon is correct, `mat-hint` is intended to be used for cases like this.

**Comment by danieldanielecki** [comment]
I was a bit afraid how it'd work out for more than 1 `mat-hint`, but it works perfectly! Thanks 👍 

<img width="680" alt="working" src="https://user-images.githubusercontent.com/12736263/98464082-a58f4700-21c0-11eb-8869-b2ac04163c66.png">
