### ISSUE TITLE
MatIcon is not working in Shadow Dom

### ISSUE THREAD

**Issue by maniya108** [angular/components#20910]
# 🐞 MatIcon is not working in Shadow Dom

### Affected Package

 The issue is caused by package @angular/material/icon

### Is this a regression?

 When am using shadow dom in my components. Mat icon will not render

### Description

 
When am using shadow dom in my components. Mat icon will not render

## 🔬 Minimal Reproduction

 use `encapsulation: ViewEncapsulation.ShadowDom`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by crisbeto** [comment]
Are you using SVG icons or font icons? I ran a quick test and the SVG ones worked fine. For the font icons to work, you'll have to include the font stylesheet inside the same shadow root as the icon.

**Comment by maniya108** [comment]
@crisbeto can you share some sample code or repository.
Thanks

**Comment by crisbeto** [comment]
There are a couple of live examples and code in the docs site: https://material.angular.io/components/icon/examples

**Comment by crisbeto** [comment]
Closing due to a lack of activity.
