### ISSUE TITLE
Error when removing steps from material stepper with ngIf when the selectedIndex is greater than the updated stepper length

### ISSUE THREAD

**Issue by MarkFSkinner** [angular/components#20923]
**Bug, feature request, or proposal:**

bug

**Description**

I am making a material stepper where the subsequent steps change dynamically depending on which radio button option a user selects in their current step. When the user goes back and changes a selection, which then reduces the number of subsequent steps from what it was before, I am experiencing an error. More specifically, this error occurs when the number of newly rendered steps is less than the `selectedIndex` of the previously rendered steps.

When the new steps are rendered, they are all closed (none are set as the `selectedIndex`). When I click on one of the steps I get this error:
```
ERROR TypeError: Cannot set property 'interacted' of undefined
```

When you click on a step it is calling this function which changes the `selectedIndex` of the stepper:

```
set selectedIndex(index) {
        const newIndex = coerceNumberProperty(index);
        if (this.steps && this._steps) {
            // Ensure that the index can't be out of bounds.
            if ((newIndex < 0 || newIndex > this.steps.length - 1) &&
                (typeof ngDevMode === 'undefined' || ngDevMode)) {
                throw Error('cdkStepper: Cannot assign out-of-bounds value to `selectedIndex`.');
            }
            if (this._selectedIndex != newIndex && !this._anyControlsInvalidOrPending(newIndex) &&
                (newIndex >= this._selectedIndex || this.steps.toArray()[newIndex].editable)) {
                this._updateSelectedItemIndex(index);
            }
        }
        else {
            this._selectedIndex = newIndex;
        }
    }
```

In my case, we are hitting the line that calls this function:

``` 
_anyControlsInvalidOrPending(index) {
        const steps = this.steps.toArray();
        steps[this._selectedIndex].interacted = true;
        if (this._linear && index >= 0) {
            return steps.slice(0, index).some(step => {
                const control = step.stepControl;
                const isIncomplete = control ? (control.invalid || control.pending || !step.interacted) : !step.completed;
                return isIncomplete && !step.optional && !step._completedOverride;
            });
        }
        return false;
    }
```

This line is causing the error: 

```
steps[this._selectedIndex].interacted = true;
```

At this point, `this._selectedIndex` is the index we are moving away from, since it hasn't been set to the new value yet. So it is trying to set the `interacted` property of the previous step (the one you are leaving), but in this case that step no longer exists in the DOM due to the `ngIf` and, therefore, this line is causing an `undefined` error and crashing.

Seems like there should be a way to account for this situation where the previously selected step no longer exists. Maybe just an `undefined` check that only updates the `interacted` property if the step still exists in the DOM?

**Comment by crisbeto** [comment]
I believe this is the same issue as https://github.com/angular/components/issues/20735 which has a pending PR.
