### ISSUE TITLE
feat(Expansion Panel Header): Provide a way to disable keydown event

### ISSUE THREAD

**Issue by Robouste** [angular/components#20934]
#### Feature Description

By default, the mat-expansion-panel-header adds a keydown event, breaking some potential functionalities.

https://github.com/angular/components/blob/f7d7502f9eba5293c98841a0e7063bd84589a340/src/material/expansion/expansion-panel-header.ts#L63

We should be able to disable this feature.

#### Use Case

Adding a keydown event is preventing the possibility to add editable field inside the expansion header as the user is not able to enter spaces or add a new line.

**Comment by crisbeto** [comment]
It's unlikely that we'll build something like this into the library, because it'll break accessibility. You should be able to get it to work for your case by adding `(keydown)="$event.stopPropagation()"` around your text field.

**Comment by Robouste** [comment]
Thank you, it did the trick :)
