### ISSUE TITLE
bug(mat-form-field): anchor mat-icon-button as matSuffix focus misaligned

### ISSUE THREAD

**Issue by Totati** [angular/components#20949]
#### Reproduction

[Demo](https://stackblitz.com/edit/angular-ynkmw7?file=src%2Fapp%2Fform-field-appearance-example.html)
![image](https://user-images.githubusercontent.com/17689719/97810463-53a46980-1c74-11eb-9f4d-5cdc9e38fbdb.png)

Steps to reproduce:
1. focus the suffix of the Link input
 
#### Expected Behavior

Have the same alignment as the Button input's suffix.

#### Actual Behavior

It's misaligned

#### Environment

- Angular: 10.2.1
- CDK/Material: 10.2.6
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by abu-sufyan1** [comment]
You can solve this, this way -

`<mat-form-field appearance="fill">
	<mat-label>Link</mat-label>
	<input matInput placeholder="Placeholder" />
	<button onclick="window.open('www.google.com', '_blank');" mat-icon-button matSuffix>
    <mat-icon>open_in_new</mat-icon>
  </button>
</mat-form-field>`

**Comment by TakumaKira** [comment]
Hi @Totati!

I created the PR for this.

Temporarily, you can apply the identical fix by adding below on `styles.scss`.
```css
.mat-icon-button {
  display: flex !important;
  justify-content: center;
  align-items: center;
}
```
