### ISSUE TITLE
bug(mdc-checkbox): v11-rc1 breaks MDC-checkbox

### ISSUE THREAD

**Issue by twerske** [angular/components#20956]
#### Reproduction

Steps to reproduce:
1. Implement an mdc-checkbox in Version 11-rc.1
2. Apply style into css: `@import '~@angular/material-experimental/mdc-checkbox/checkbox-theme';`
3. ng serve
 
It seems a reverted PR may reintroduce a broken path in the mdc-checkbox style
 
#### Behavior

``` Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '@material/checkbox/checkbox-theme' as checkbox-theme;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@angular/material-experimental/mdc-checkbox/_checkbox-theme.scss 1:1  @import
  src/styles.scss 16:9                                                               root stylesheet ```

#### Environment

- Angular: 11-rc1
- CDK/Material: 11-rc1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mmalerba** [comment]
This seems to work for me if I `yarn global add @angular/cli` and then create a new project. I suspect its probably the same issue as https://github.com/angular/components/issues/18392 (though I think it's been resolved)

**Comment by twerske** [comment]
Resolved with a Canary version update to `"material-components-web": "^8.0.0-canary.911014711.0"`
