### ISSUE TITLE
bug(menu): matMenuTrigger not exposing menuOpen properly

### ISSUE THREAD

**Issue by MatLang** [angular/components#20959]
#### Reproduction

Issue not reproducible on Stackblitz. Therefore, I opted to create this repo: https://github.com/MatLang/menuDemo.

The repository contains a simple menu in a component that has its changeDetection set to OnPush.

```html
<button mat-button #trigger="matMenuTrigger" [matMenuTriggerFor]="menu">
  Menu
  <span *ngIf="trigger.menuOpen">down</span>
  <span *ngIf="!trigger.menuOpen">up</span>
</button>
<mat-menu #menu="matMenu">
  <button mat-menu-item>Item 1</button>
  <button mat-menu-item>Item 2</button>
</mat-menu>
```

Steps to reproduce:
1. Clone the above repo
2. Serve the application
3. Open/Close the menu
 
 
#### Expected Behavior

I am expecting "up" and "down" to show up alternatively, depending on if the menu is closed or not.

#### Actual Behavior

The behavior is inconsistent, i.e. showing "up" and "down" in different states.

#### Possible Fix

Follow a more reactive approach and expose the menuState as a stream.

#### Environment

- Angular: ~10.2.0
- CDK/Material: ^10.2.7
- Browser(s):  Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mmalerba** [comment]
This is working as intended. Because you're using `OnPush` change detection, you need to somehow let Angular know that it needs to detect changes when the menu opens or closes. The easiest way to do this would be to use the `(menuOpened)` and `(menuClosed)` events. You could do something like this:

```html
<button mat-button #trigger="matMenuTrigger" [matMenuTriggerFor]="menu"
        (menuOpened)="opened = trigger.menuOpen" (menuClosed)="opened = trigger.menuOpen">
  Menu
  <span *ngIf="opened">down</span>
  <span *ngIf="!opened">up</span>
</button>
```
