### ISSUE TITLE
feat(material): grid system missing in `@angular/material`

### ISSUE THREAD

**Issue by nasreddineskandrani** [angular/components#20950]
#### Feature Description
Hi,
Angular material is listed for example in [this article](https://medium.com/@dharmendraoist/19-best-angular-ui-frameworks-to-use-for-faster-development-in-2020-b50e8e8c5072) as the most used and top ui lib. for angular. I personally like it 👍 

If i compare `@angular/material` to `ngx-bootstrap` or `ng-prime` or even `salesforce`. I see a missing part 'the grid system'.
bootstrap: https://getbootstrap.com/docs/4.0/layout/grid/
prime: https://www.primefaces.org/primeng-flexgrid/
salesforce/lightning: http://www.lightningdesignsystem.com/utilities/grid/

material.io website describes a [grid system here](https://material.io/design/layout/responsive-layout-grid.html).

The request:
 If it's `@angular/flex-layout` then it should be linked in the documentation of the github repo. as official grid-system.
Or **I think personally that `@angular/material` should add it's own with css classes and not directives => like other libs do.**

side notes:
- https://blog.logrocket.com/css-grid-or-css-frameworks/
Css grid is not used everywhere. A lot incorp. are still using a grid system from css-frameworks.

- I see some teams in companies **including bootstrap only for the grid system** on top of `@angular/material`.

Thank you

**Comment by hakimio** [comment]
Nowadays CSS grid should be preferred to JS grid systems like bootstrap since you can achieve pretty much the same and its performance is much better. I don't see much value in this feature.

**Comment by jelbourn** [comment]
This is something we intentionally don't want to add. In particular, we don't want to get into the layout business, especially with so many options already out there (CSS flexbox, CSS grid, etc.). Our focus will continue to be on just the UI components.

**Comment by nasreddineskandrani** [comment]
thanks. Pretty clear 👍
