### ISSUE TITLE
docs-bug(MatCardModule): useless mat-card tag in the doc examples

### ISSUE THREAD

**Issue by leogout** [angular/components#20958]
#### Documentation Feedback

Here :
https://material.angular.io/components/card/examples 
On the second example, there is a `<mat-card></mat-card>` above the Shiba Inu example :
![image](https://user-images.githubusercontent.com/9843962/97960113-109be080-1db1-11eb-84db-ddb1d3ee89d4.png)

```
<mat-card> <- here
</mat-card> <- and here
<mat-card>
  <mat-card-header>
    <div mat-card-avatar></div>
    ...
```
I suggest to remove those unused tags.

**Comment by mmalerba** [comment]
This is actually supposed to be an example demonstrating how to use the `MatCardHarness` for testing, but the example isn't showing up right in the docs

**Comment by annieyw** [comment]
The harness examples should be live on the doc site now.
