### ISSUE TITLE
bug(MatInput, MatFormField): Deletes contents of sibling input when removed

### ISSUE THREAD

**Issue by obumnwabude** [angular/components#20998]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue
https://stackblitz.com/edit/components-issue-5gkex1

Steps to reproduce:
1. In Component Class, get a FomGroup with one of its keys as a FormArray which in turn contains FormControls
2. In the template, bind the formGroup to a form element. In this form element, assign the formArray's name to a div and iterate over the controls of the formArray.
3. Use MatFormField wrap inputs or textareas with MatInput attribute, bound to formControls contained in the formArray
4. Add a button to the form element which creates dynamically creates new inputs and appends them to the formArray
5. Add a button to the mat-form-field element for removing that particular formField from the formArray 

#### Expected Behavior

What behavior were you expecting to see?
That when you click the remove button of a particular formField, it just removes it.

#### Actual Behavior
It removes that formfield and goes further to replace the contents of the formField preceding it with its current contents, and if it was empty, it equally replaces the contents of the preceding formField's input/textarea with an empty string (in other words, clears its contents)

What behavior did you actually see?
That when the remove button of a particular formField is clicked, it should only remove that formField, if it goes further to bring focus into the input/textarea of the formField preceding it, it should not replace or clear the contents of this preceding formField

#### Environment

- Angular: 10.2.7
- CDK/Material: 10.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

**Comment by crisbeto** [comment]
This is a problem with your setup which comes from the fact that you're passing in `undefined` to the `remove` method, not the index. It works when you replace the `(click)="remove(index)"` with `(click)="remove(i)"`.
