### ISSUE TITLE
id is not set on matEndDate input of the date range picker, why?

### ISSUE THREAD

**Issue by tomekwszelaki** [angular/components#21000]
Comparing the `matStartDate` and `matEndDate` elements I noticed the `matEndDate` doesn't have the id set:

![image](https://user-images.githubusercontent.com/1482166/98649424-e1005180-2337-11eb-9e40-46b88c578cee.png)

Is that by design or just an oversight?

Thanks!

**Comment by crisbeto** [comment]
It's intentional. That ID is only used by the form field label and we can't have it pointing to more than one input.
