### ISSUE TITLE
bug(MatSelect): MatSelect overlay has transparent background when loading options

### ISSUE THREAD

**Issue by DickerCan** [angular/components#21001]
#### Reproduction

1. create an angular project with mat select
2. use long option list (500+ entries)
3. open select on scroll using the scrollbar
(on stackblitz the bug does not occur)
 
 
#### Expected Behavior

When select is too slow to show all options, it shows white background until options are loaded.

#### Actual Behavior

![B00732B2-23CF-43E8-AF44-60C224410008](https://user-images.githubusercontent.com/22917740/98666692-a86b7280-234d-11eb-8582-3f0ceb39b2d8.GIF)

The background goes transparent when loading options

#### Environment

- Angular: 10.2.2
- CDK/Material: 10.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
From that I can tell, this is just the browser struggling to keep up with all the elements. The `.mat-select-panel` has a background color already so we can't do much more about it.
