### ISSUE TITLE
bug[mat-icon] unreachable code result from possible spell miss

### ISSUE THREAD

**Issue by chigix** [angular/components#21024]
https://github.com/angular/components/blob/65e9ad158a0a051b999640ebcb4ef955c9255358/src/material/icon/icon.ts#L256

Because `previousValue` is accessible on the `SimpleChanges` event object rather than the `svgIconChanges` that is obtained from [`changes['svgIcon']`](https://github.com/angular/components/blob/65e9ad158a0a051b999640ebcb4ef955c9255358/src/material/icon/icon.ts#L231), the line https://github.com/angular/components/blob/65e9ad158a0a051b999640ebcb4ef955c9255358/src/material/icon/icon.ts#L256 becomes unreachable at present.

Please confirm is it an intended design or just a bug ?

If it is a bug, would it be a necessity to update testing cases in spec files to reflect this corresponding conditional branch ?

**Comment by crisbeto** [comment]
I'm not sure I follow what the issue is here. The `svgIconChanges` is a `SimpleChange` object that contains the current and previous value for the `svgIcon` input. That being said, we aren't even using `ngOnChanges` after #20509 so this code doesn't exist anymore.
