### ISSUE TITLE
docs-bug(checkbox): Documentation use "MAT_CHECKBOX_CLICK_ACTION" without notification of deprecation. When MAT_CHECKBOX_DEFAULT_OPTIONS should be used. Errors in v11. 

### ISSUE THREAD

**Issue by Eddygn** [angular/components#21025]
The checkbox documentation page has a section about the usage of "MAT_CHECKBOX_CLICK_ACTION" to define the behavior on clicks. 
It didn't provide any indication that this method is deprecated, nor that it was replaced with  ```{provide: MAT_CHECKBOX_DEFAULT_OPTIONS, useValue: { clickAction: 'noop' } as MatCheckboxDefaultOptions }```

Running a project after upgrading the Angular and Material package will produce an error.

Migration didn't touch this. I don't know if it was updated in earlier migration, since I've only added the provider a week ago, into v10 project. (no notice of deprecation anywhere I saw)

**Affected documentation page:** 
https://material.angular.io/components/checkbox/overview

**Comment by lxandrexl** [comment]
waiting solution :( i had same issue

**Comment by adhispace** [comment]
Hi....can I take this...as this will be my first attempt to contribute. thanks
