### ISSUE TITLE
bug(cdk/testing): sendKeys doesn't watch input selection

### ISSUE THREAD

**Issue by skoropadas** [angular/components#21030]
#### Reproduction
This is an issue with TestHarness, I don't know how I can reproduce it with StackBlitz.

Steps to reproduce:
try to execute this code for the input element

```
input.sendKeys('34')
input.sendKeys(TestKey.LEFT_ARROW);
input.sendKeys(TestKey.LEFT_ARROW);
input.sendKeys('12')
```
 
#### Expected Behavior

input value will be "1234"

#### Actual Behavior

input value will be "3412"

#### Environment

- Angular: master
- CDK/Material: master
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by wagnermaciel** [comment]
@skoropadas I think you might be running into a race condition because you are not awaiting your `input.sendKeys()` calls.

I'd also like to add that you can avoid using `sendKeys()` altogether by calling `setValue()`. Let me know if this resolves your issue.

**Comment by skoropadas** [comment]
> @skoropadas I think you might be running into a race condition because you are not awaiting your `input.sendKeys()` calls.
> 
> I'd also like to add that you can avoid using `sendKeys()` altogether by calling `setValue()`. Let me know if this resolves your issue.

Sorry for the delay. In my code, I use `await input.sendKeys ()`, I saw the implementation of `sendKeys()`, they just add a new value by character something like `input.value += charOfNewValue`.
I'm just trying to check my masked input, but masked input works with selection, so when you try to use 'sendKeys ()', you get the wrong value in the input.
Also, what is `setValue()`? `ComponentHarness` doesn't have it.

**Comment by wagnermaciel** [comment]
@skoropadas `setValue()` is a method on an input harness
https://github.com/angular/components/blob/master/src/material/input/testing/input-harness.ts#L114

I'm not sure I can be more helpful / do much more debugging without a way to reproduce the behavior you're seeing. Here's a link to a stackblitz containing tests that you could potentially modify to demonstrate this issue
https://stackblitz.com/angular/rxgklkrvyxn?file=src%2Fapp%2Fbadge-harness-example.ts

**Comment by skoropadas** [comment]
@wagnermaciel Oh, sorry I didn't explain. I'm writing tests for my own library of components and not for the material, so I use `sendKeys()`

**Comment by wagnermaciel** [comment]
@skoropadas To me this looks like you are trying to use the `sendKeys()` method in unit tests where native keypress events are not able to be used to interact with native browser `<input>`s.  Emulating the full behavior of the browser is outside of the scope of what we want the harnesses to do
