### ISSUE TITLE
MatCheckbox not rendering check for undefined color when using default options

### ISSUE THREAD

**Issue by Eddygn** [angular/components#21031]
#### Reproduction

https://stackblitz.com/edit/angular-yyan4s?file=src%2Fapp%2Fcheckbox-overview-example.html

Steps to reproduce:
1.  Adding the default behavior provider ```    {
      provide: MAT_CHECKBOX_DEFAULT_OPTIONS,
      useValue: { clickAction: "noop" } as MatCheckboxDefaultOptions
    }```
2. Setting any checkbox via input, for example: ```<mat-checkbox [checked]="true">Checked</mat-checkbox>```
 
 
#### Expected Behavior

![image](https://user-images.githubusercontent.com/33177527/98990326-fd1c1280-2532-11eb-89cd-b7e15d90fcb4.png)

#### Actual Behavior

What behavior did you actually see?

![image](https://user-images.githubusercontent.com/33177527/98990370-0ad19800-2533-11eb-82f7-5a0ef36e3d29.png)

#### Environment

- Angular: 11
- CDK/Material: 11
- Browser(s): Firefox 82
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by jelbourn** [comment]
@crisbeto this was supposed to be fixed in #18467 but the stackblitz above still seems to have the problem behavior
