### ISSUE TITLE
iframe youtube popup blocker

### ISSUE THREAD

**Issue by Navin-vis** [angular/components#21040]
Can you help me out how can i remove allow attribute from iframe and add sandbox attribute
I am using "@angular/youtube-player": "^11.0.0",
My dev devDependencies are as follows
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.21",
    "@angular/cli": "^8.3.21",
    "@angular/compiler-cli": "~8.2.9",
    "@angular/language-service": "~8.2.9",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }

**Comment by crisbeto** [comment]
Our implementation is based on the [YouTube iframe API](https://developers.google.com/youtube/iframe_api_reference) which means that we don't actually have direct access to the `iframe` itself. From what I can tell, what you're asking for can't be configured through the API so we won't be able to do much about it.
