### ISSUE TITLE
bug(DATEPICKER): Close calendar button not placed correctly when opened using button click event

### ISSUE THREAD

**Issue by acohenOT** [angular/components#21043]
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-y4se2w

Steps to reproduce:
1. Create a button that when clicked, opens the date picker (instead of using `mat-datepicker-toggle` component)
2. Click button to open the date picker (notice UI artifact in the bottom left of the calendar)
3. Tap the TAB key twice (notice the `Close calendar` button is on the inside of the calendar border)
 
 
#### Expected Behavior

When the picker is open, no UI artifact at the bottom of the calendar
![image](https://user-images.githubusercontent.com/34688558/99100156-6c344e00-25a9-11eb-86d0-9f14357117d7.png)

When you tab to the `Close calendar` button, the button should appear outside of the calendar border
![image](https://user-images.githubusercontent.com/34688558/99100195-7e15f100-25a9-11eb-8c41-a2592c800974.png)

#### Actual Behavior

What behavior did you actually see?

When the picker is opened using a button click event, a UI artifact appears at the bottom of the calendar
![image](https://user-images.githubusercontent.com/34688558/99100258-971ea200-25a9-11eb-80f1-1b5bd4867cc9.png)

When you tab the button, the button appears inside the calendar component
![image](https://user-images.githubusercontent.com/34688558/99100299-a69deb00-25a9-11eb-82e2-ed887d78a0d1.png)

#### Environment

- Angular: 11.0
- CDK/Material: 11.0
- Browser(s): Chrome 86
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
The problem is that the specificity of the close button styles is too low and can be overridden by `mat-button` in some cases. I've submitted #21058 to fix it, but there's no good workaround until the fix lands, apart from manually setting `display: none` on the button.
