### ISSUE TITLE
bug(Select): overlayPanelClass doesn't do anything

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#21050]
#### Reproduction

Use StackBlitz to reproduce your issue: 

https://stackblitz.com/edit/components-issue-xtgy1y?file=src%2Fapp%2Fexample-component.css

Steps to reproduce:
1. Place 
2.Place overlayPanelClass on the mat-select component ie: <mat-select overlayPanelClass="custom-overlay-class"> 
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expected that the Overlay would have that custom class apply, however, nothing happens.

#### Actual Behavior

What behavior did you actually see?
Nothing happens.

#### Environment

- Angular: 8
- CDK/Material: Latest 
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
There are two problems with your example:
1. The input is called `panelClass`, not `overlayPanelClass`.
2. The styles are inside of a component with view encapsulation which means that even if the class was applied, you wouldn't be able to see your changes.

Here's a working example https://stackblitz.com/edit/components-issue-lhxvsf?file=src%2Fapp%2Fexample-component.ts.

**Comment by omaracrystal** [comment]
I need the class on the outer most overlay. The issue I am having is that I am consuming an outside 3rd party resource for a modal. Within that modal is a form. The select overlay z-index is below the 3rd party modal. I need the ``overlayPanelClass`` which is described in the Docs as "Class or list of classes to be applied to the menu's overlay panel.". The ``panelClass`` is described as "Classes to be passed to the select panel. Supports the same syntax as ngClass."
