### ISSUE TITLE
feat(MatTabHeader): Add left/right as options to MatTabHeaderPosition

### ISSUE THREAD

**Issue by mackelito** [angular/components#21067]
#### Feature Description
For flexibility it would be a great addition to have the option to have tabs on the left/right side
Provide a brief summary of the feature you would like to see.

#### Use Case
To be able to have tabheaders on the left/right side user could create more flexible views and layouts

**Comment by crisbeto** [comment]
For this to work we'd have to place the tabs on top of each other which is discouraged by the Material design spec. See:
![Tabs_-_Material_Design_-_Google_Chrome_2020-11-23_17-09-02](https://user-images.githubusercontent.com/4450522/99985765-a7efc480-2dae-11eb-8e27-1831c4aa6c5f.png)
