### ISSUE TITLE
bug(Scrolling): [Accessibility] - Virtual scroll viewport does not support keyboard interactions and is device dependent

### ISSUE THREAD

**Issue by ramji-seetharaman** [angular/components#21062]
**Reproduction**
https://stackblitz.com/angular/jbyrbregorl?file=src%2Fapp%2Fcdk-virtual-scroll-overview-example.ts

**Steps to reproduce:**

1. Navigate to the StackBlitz link provided above
2. Use any examples from the documentation for Scrolling CDK
3. Using keyboard interactions (Tab, Shift + Tab), verify whether the user can scroll the virtual scroll viewport (Issue)

**Expected Behavior:**
The <cdk-virtual-scroll-viewport> when displaying a large list of elements must be keyboard accessible. When using Tab, Shift + Tab, since there are interactive elements in the viewport, they need to be keyboard accessible. Any scrollable content that has interactive elements needs to receive explicit keyboard support by including them in the natural focus order(tabindex).

**Actual Behavior**
Currently the <cdk-virtual-scroll-viewport> is not keyboard accessible and is device dependent. Users need to use mouse to scroll through the contents in the viewport. Person with motor impairments who rely on keyboard/switch devices will not be able to access the elements inside the virtual scroll viewport. 

**Environment**
Angular: 10.2.7
CDK/Material: 10.2.7
Browser(s): all
Operating System (e.g. Windows, macOS, Ubuntu): all

![image](https://user-images.githubusercontent.com/71451445/99322248-943bdf80-283d-11eb-8726-a413c37749f9.png)

**Comment by crisbeto** [comment]
For this to work, we'd have to keep all the elements in the DOM which defeats the purpose of virtual scrolling. Closing since there isn't much we can do about it.
