### ISSUE TITLE
Virtual Scroll CDK render error elements

### ISSUE THREAD

**Issue by MinhPhuPham** [angular/components#21069]
My purpose:  Create a components is layout scroll to load data, but have error display data when scroll.

My issue: 
> - Scroll to last (load all data). => Then scroll up again, and scroll down (a few times), you will see the last few elements, sometimes lost while displayed data.
_*You can see this issue more clearly when display 3 column_

Here is in stackblitz: 
[https://stackblitz.com/edit/virtual-scroll-angular?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/virtual-scroll-angular?file=src%2Fapp%2Fapp.component.ts)
  
#### Environment

- Angular: 9+
- CDK/Material: 9+
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
I don't quite follow what the problem is. Does it sound similar to https://github.com/angular/components/issues/19313?

**Comment by MinhPhuPham** [comment]
I don't thinks it similar to issue #19313. Because in here, i using grid layout for virtual scroll => when scroll down, virtual ought to fixed element quality (like 9 element) but in position scroll bar, it will make the detect item in here and render new element to fixed items quality in default. and it make the view changed with error viewer item

**Comment by arumuganainar73** [comment]
Any solution for this ?
