### ISSUE TITLE
mat-form-field with appearance outline incorrectly recalculate outline-gap position if trigger Directionality change event. 

### ISSUE THREAD

**Issue by Serg-Mois** [angular/components#21061]
#### Reproduction

Stackblitz example: https://stackblitz.com/edit/material2-mat-form-field-outline-rtl-issue-rzivqz?file=src/app/app.component.ts
 
![image](https://user-images.githubusercontent.com/37027173/99304421-053dc000-285b-11eb-8ea1-2e8f716aae66.png)

 
Strange behavior, if we manually set dir=rtl for the document root - everything works fine, the outline-gap position is  recalculated correctly unless we trigger Directionality change event;

#### Environment

- Angular:  10.2.3
- CDK/Material: 10.2.7
- Browser(s): Chrome 86
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by mmalerba** [comment]
You shouldn't call `emit` directly on the `ChangeEmitter` from `dir`. That doesn't actually update the underlying value, just causes it to emit an event. In general, the owner of the `EventEmitter` is the only one that should be calling `emit` on it. If you want to dynamically change the direction I recommend doing something like `[dir]="myDir"` and then changing myDir to "ltr" or "rtl" in your ts.
