### ISSUE TITLE
bug(Select): overlayPanelClass doesn't do anything

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#21095]
#### Reproduction

Reopening https://github.com/angular/components/issues/21050 with more details

I need to place a custom class on the outermost overlay div. 
The issue I am having is that I am consuming an outside 3rd party resource for a modal which has a higher z-index then material. Within that modal is a form made with material components. The select overlay z-index is below the 3rd party modal.

I need the **overlayPanelClass** which is described in the Docs as: "_Class or list of classes to be applied to the menu's overlay panel._". 

The **panelClass** is described as "_Classes to be passed to the select panel. Supports the same syntax as ngClass._"

Use StackBlitz to reproduce your issue:

https://stackblitz.com/edit/components-issue-xtgy1y?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:

1. Add overlayPanelClass on the mat-select component that sits within a 3rd party modal that has a higher z-index then the overlay. 

Expected Behavior
What behavior were you expecting to see?
I expected that the outermost overlay div to have that custom overlayPanelClass so I can adjust the z-index to be above the 3rd party modal. 

Actual Behavior
What behavior did you actually see?
No class is applied to the outermost overlay div.

Environment
Angular: 8
CDK/Material: Latest
Browser(s): Chrome latest
Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by omaracrystal** [comment]
So there is no way to make sure that ``z-index`` is only on one particular overlay then? It would automatically be applied everywhere with your solution right?

**Comment by crisbeto** [comment]
That's correct, all Material overlays will be under `cdk-overlay-container` which has the `z-index`.

**Comment by mihaicrisan** [comment]
it actually works with **backdropClass** instead of **overlayPanelClass** , 
same goes for **panelClass**. it actually works with **class**
the documentation seems wrong.

**Comment by crisbeto** [comment]
Closing since there hasn't been any activity in a long time.
