### ISSUE TITLE
help(CdkTableDataSourceInput): Can't use async pipe for dataSource with strictTemplates 

### ISSUE THREAD

**Issue by rafagsiqueira** [angular/components#21091]
#### What are you trying to do?

Trying to use async pipe on an observable dataSource when strictTemplates are enabled:
```
<mat-table [dataSource]="vms$ | async">
```

#### What troubleshooting steps have you tried?

When trying to compile with I am getting the following error:
```
Type 'Vm[] | null' is not assignable to type 'CdkTableDataSourceInput<Vm>'.
```
I have tried to use (vms$ | async)!, and other unlikely combinations to avoid the null return type, with no success. All results in syntax errors.

I appreciate any help with this!

#### Reproduction

Steps to reproduce:
1. On the component: vms$: Observable<Vm[]> = new Observable<Vm[]>();
2. On the template: <mat-table [dataSource]="vms$ | async">
3. Disabling strictTemplates solves the problem

#### Environment

- Angular: 11.0.0
- CDK/Material: 11.0.0
- Typescript: 4.0.5
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by Totati** [comment]
Datasource accepts an observable as an input, so you can write just `<mat-table [dataSource]="vms$">` [Example](https://stackblitz.com/edit/angular-oqaegc?file=src/app/table-basic-example.html)

**Comment by Totati** [comment]
Datasource accepts an observable as an input, try writing just <mat-table [dataSource]="vms$">

**Comment by rafagsiqueira** [comment]
Wow. I feel stupid. @Totati thank you!
