### ISSUE TITLE
help(Google-Map): map-marker-clusterer doesnt seem to be in the npm package.

### ISSUE THREAD

**Issue by tmmschmit** [angular/components#21094]
#### What are you trying to do?

Hello, I'm trying to use the component `map-marker-clusterer` (https://github.com/angular/components/tree/master/src/google-maps/map-marker-clusterer) added 13 days ago in `google-maps`. 

#### What troubleshooting steps have you tried?

It is in the repo, but it doesn't look to be in the compiled version : 
![Screenshot from 2020-11-19 11-31-44](https://user-images.githubusercontent.com/60105862/99695062-1c4b0080-2a5b-11eb-9cba-8dd34a7412f5.png)
![Screenshot from 2020-11-19 11-31-09](https://user-images.githubusercontent.com/60105862/99695063-1c4b0080-2a5b-11eb-838f-5f25929acc76.png)
![Screenshot from 2020-11-19 11-30-48](https://user-images.githubusercontent.com/60105862/99695110-2e2ca380-2a5b-11eb-9fcf-1c6372e1bdd2.png)

I use the last version:

![Screenshot from 2020-11-19 11-32-13](https://user-images.githubusercontent.com/60105862/99695059-1bb26a00-2a5b-11eb-8982-2baa6c15d42f.png)

but it doesn't work...

#### Reproduction

https://github.com/angular/components/blob/master/src/google-maps/map-marker-clusterer/README.md

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): 10

What I'm doing wrong? Thanks!

**Comment by crisbeto** [comment]
The clusterer was merged in for the next minor version which hasn't been released yet. It should be out in 11.1.0. Until then you can grab a build from https://github.com/angular/google-maps-builds.

**Comment by tmmschmit** [comment]
Thanks!

**Comment by DarthCoding** [comment]
@crisbeto how can i get this build? Or do you know when the next minor version will be release?
