### ISSUE TITLE
bug(material/chips): material chips are shaking with multi-lines on drag

### ISSUE THREAD

**Issue by yhilcenko** [angular/components#21090]
#### Reproduction

When you drag any mat-chip element on a mat-chip-list and there is more than one line of chip elements available, others chips are shaking (see gif below) 
![Nov-19-2020 14-06-49](https://user-images.githubusercontent.com/5311090/99670238-828e4e00-2a70-11eb-96f1-337c2728843b.gif)

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-rkfmhj?file=src/app/chips-drag-drop-example.ts

Steps to reproduce:
1. Try to move any chip.

#### Environment

- Angular: 10.
- CDK/Material: 10
- Browser(s): Chrome / Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS X

**Comment by crisbeto** [comment]
We currently don't support mixed orientation drag&drop. This is being tracked by #13372.
