### ISSUE TITLE
Renderer2 not used in mat-drawer

### ISSUE THREAD

**Issue by delbiancodavide** [angular/components#21108]
https://github.com/angular/components/blob/bb2bb9c3065ec1a7a845de072305893a7378383a/src/material/sidenav/drawer.ts#L789

I think that this piece of code should be changed to use Renderer2

**Comment by Achilles1515** [comment]
No. In general, don't use Renderer.

https://github.com/angular/components/pull/8235

**Comment by crisbeto** [comment]
@Achilles1515 is correct, we don't need to use `Renderer2` for cases like this anymore.
