### ISSUE TITLE
CDK Virtual scroll supports CDK Drag&Drop

### ISSUE THREAD

**Issue by Vitashev** [angular/components#21106]
#### Feature Description

Currently, CDK Virtual scroll doesnt work together with CDK Drag&Drop

#### Use Case

We have a big list of tasks, and we want to use virtual scroll to limit dom rendering. At the same time we want to use reorder functionality using Drag&Drop.

**Comment by crisbeto** [comment]
We currently don't support drag&drop with virtual scrolling. This is tracked in https://github.com/angular/components/issues/10122.
