### ISSUE TITLE
feat(@angular/google-maps): Add cluster support

### ISSUE THREAD

**Issue by MonocleKelso** [angular/components#21102]
#### Feature Description

Currently @angular/google-maps does not support marker clusters (https://github.com/googlemaps/js-markerclustererplus). It'd be great if it did.

#### Use Case

We're trying to transition off AGM (https://github.com/SebastianM/angular-google-maps) and onto the official package but cannot do so fully until marker clusters are supported.

**Comment by crisbeto** [comment]
This was added in https://github.com/angular/components/pull/20944 which should be released with v11.1.0.

**Comment by hassang11** [comment]
@crisbeto is a timeline for when v11.1.0 will be released - Looking forward to use this app
