### ISSUE TITLE
Angular Material doesn't give clear information about mat-form-field must contain a MatFormFieldControl

### ISSUE THREAD

**Issue by wizardnet972** [angular/components#21109]
Angular Material doesn't give clear information about where in the HTML the problem is, instead I got message: "mat-form-field must contain a MatFormFieldControl".

This is uncomfortable because I have component with a 70+ material components, including many inputs, select, datepicker, autocomplete, and I not sure where in  my code I don't have `matInput` for example.

The code I got from my client and in the component, I have 4000+ lines of code and the problem is the message not say where I missing this attribute.

So this is very frustrating. please consider making a change with this.

I suggest something like "input( 30:2) missing matInput" when I wrap inside `mat-form-field` (and so').

![image](https://user-images.githubusercontent.com/4997825/99879637-d89cf600-2c16-11eb-8013-4b0ae50534cd.png)

**Comment by crisbeto** [comment]
> I suggest something like "input( 30:2) missing matInput" when I wrap inside mat-form-field (and so').
Our code is only executed during runtime so we don't have access to your source code. Closing the issue since we can't do much more about this, aside from the error that we're already throwing.
