### ISSUE TITLE
Roboto font moves on page load.

### ISSUE THREAD

**Issue by uloga** [angular/components#21118]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. When page loads for the first time Roboto font that has different font weight e.g 700, 900 moves or scales into place
2. see on https://material.angular.io/ website the hero title "Angular Material" when loaded for first time.
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expect font not to scale or move.

#### Actual Behavior

What behavior did you actually see?
The font scales into place or in some cases moves slightly from left to right.

#### Environment

- Angular: 9
- CDK/Material: 9.2.4
- Browser(s): Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): 
Macos

**Comment by crisbeto** [comment]
We've set it up this way on purpose so that text is shown in a system font before Roboto has loaded since that's better than not showing text at all.

**Comment by uloga** [comment]
Oke, bad choice IMHO. The website on first load looks weird, see no purpose for nice font if the whole website, titles, buttons etc move / scale in place on first page load.

**Comment by uloga** [comment]
It's a bug IMO when you use mat-typography on body tag then it doesn't happen but then you can't change font but use the basic font sizes, e.g you can't change the font weight or font size it's not that useful IMHO. Fixed it by removing roboto completely. It's just hard to look at. :(

**Comment by crisbeto** [comment]
For what it's worth, this is something that you can control on your end when you load Roboto, it's not controlled by Material. If you want to change the behavior for your own app, you can add `&display=block` to the Google Fonts URL that loads Roboto.  There's for info in the docs: https://developers.google.com/fonts/docs/css2

**Comment by uloga** [comment]
Thanks that's great!
