### ISSUE TITLE
bug(Chips): CDK Drag/drop jank with multiple rows

### ISSUE THREAD

**Issue by baxelson12** [angular/components#21112]
#### Reproduction

Steps to reproduce:
1.  https://stackblitz.com/angular/rnjaakoakda?file=src%2Fapp%2Fchips-drag-drop-example.ts (or Angular material website)
2.  Reduce screen to create a line break
3.  Struggle
 
 
#### Expected Behavior

Ability to rearrange chips on different rows

#### Environment

- Angular: ^10.0.0
- CDK/Material: ^10.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10

**Comment by crisbeto** [comment]
We currently don't support mixed orientation drag&drop. This is being tracked by https://github.com/angular/components/issues/13372.
