### ISSUE TITLE
bug(mat-select):  automatic scrolling of options when height of option is set in css

### ISSUE THREAD

**Issue by negberts** [angular/components#21121]
#### Reproduction

https://stackblitz.com/edit/components-issue-16pt1s
 
#### Expected Behavior

What behavior were you expecting to see?

No scrolling of the options panel when clicking higher numbers in the select list. 

#### Actual Behavior

What behavior did you actually see?

When clicking on items (for instance number 50) the panel starts scrolling down to higher numbers because the height of mat-option is set to 30px instead of 48px. 

#### Environment

- Angular: 11.0.2
- CDK/Material: 11.0.0
- Browser(s): Edge, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
The current `mat-select` implementation assumes that the options and the option panel will have a particular height so changing it yourself won't work. We have a new one in `@angular/material-experimental/mdc-select` which has the same logic, but slightly different CSS which doesn't have this limitation. You can either switch to it now or we'll eventually merge it into `@angular/material/select`.

**Comment by negberts** [comment]
@crisbeto thank you for your reply. do you have a timeline for eventually? Is that 2 weeks? 2 months? 2 years?

**Comment by crisbeto** [comment]
Probably within the next year, but it's difficult to say. I think that you can safely use it, if this is something that's blocking you, because both implementation are on top of the same base class and they run the same set of unit tests.
