### ISSUE TITLE
bug(select): when matTooltip is applied to mat-option, tooltip is not being displayed when i  try to navigate through each options using keyboard.

### ISSUE THREAD

**Issue by manu-058** [angular/components#21123]
#### Reproduction

Below is the stackblitz link of reproducing the issue
https://stackblitz.com/edit/angular-mxcuiv?file=src/app/select-overview-example.html

#### Steps to reproduce:
1. click on the mat-select dropdown.
2. press the down arrow key( focus is brought to the 2nd option , but the tooltip is not displayed )
 
 
#### Expected Behavior

What behavior were you expecting to see?
1. click on the mat-select dropdown.
2. press the down arrow key, if the focused option has matToolip, tooltip must be displayed.

#### Actual Behavior

What behavior did you actually see?
1. click on the mat-select dropdown.
2. press the down arrow key( focus is brought to the 2nd option , but the tooltip is not displayed )

#### Environment

- Angular: 10
- CDK/Material: 10.0.0
- Browser(s): chrome
- Operating System : Windows

**Comment by crisbeto** [comment]
That's because the options don't actually receive focus, but it's simulated focus using `aria-activedescendant`. We can't change it, because it's required for the accessibility pattern that we're using for the select and autocomplete.
