### ISSUE TITLE
docs-bug(COMPONENT): Add v11. sub domaine access

### ISSUE THREAD

**Issue by kevinLourencoDev** [angular/components#21135]
#### Documentation Feedback

Hi, documentation missing the subdomain access: 

https://v9.material.angular.io/components/categories --> 9.2.4
https://v10.material.angular.io/components/categories --> 10.2.7
https://v11.material.angular.io/components/categories --> error type DNS_PROBE_FINISHED_NXDOMAIN

**Comment by crisbeto** [comment]
We only create a subdomain once a version isn't the currently-active one. The v11.material.angular.io will be added when we release v12.
