### ISSUE TITLE
Unexpected result for mat-dialog-close

### ISSUE THREAD

**Issue by clovergaze** [angular/components#21149]
#9020 is still relevant, please see #9020 for details.

**Comment by crisbeto** [comment]
The reason why #9020 was closed still stands: there's no way for us to distinguish between `<button mat-close>` and `<button [mat-close]="''">` so we can't close the dialog with `undefined` by default.

**Comment by jelbourn** [comment]
Closing this because it's not feasible for us to distinguish between an intentional empty string an an attribute without a binding
