### ISSUE TITLE
docs-bug(Checkbox): Indeterminate Checkbox [color] attribute missing

### ISSUE THREAD

**Issue by t-kaufmann** [angular/components#21163]
#### Documentation Feedback

In the checkbox documentation the first section "Basic checkboxes" provides an example with sub-checkboxes. In the HTML code, the `[color]="task.color"` attribute of the "Indeterminante" checkbox is missing (it uses the "accent" color, although the color has been defined to be "primary" in the component.ts.

**Affected documentation page:**  [ https://material.angular.io/components/checkbox/overview](https://material.angular.io/components/checkbox/overview)

**Comment by crisbeto** [comment]
Will be resolved by https://github.com/angular/components/pull/21167.
