### ISSUE TITLE
bug(mat-datepicker): mat-datepicker is not displaying

### ISSUE THREAD

**Issue by KevinLourd** [angular/components#21164]
#### Reproduction

Steps to reproduce:
1. add in a component a datepicker
```
          <mat-form-field appearance="fill">
            <mat-label>Choose a date</mat-label>
            <input matInput [matDatepicker]="picker">
            <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            <mat-datepicker #picker></mat-datepicker>
          </mat-form-field>
```
(code taken from [material angular doc / Basic datepicker](https://material.angular.io/components/datepicker/overview))
2. refresh the page
 
 
#### Expected Behavior

It should display the datepicker inside the component

#### Actual Behavior

The whole component disappear from the page

#### Environment

- Angular CLI: 11.0.2
- @angular/material: 11.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): mac

**Comment by codef0rmer** [comment]
@KevinLourd I could see the datepicker as normal: https://stackblitz.com/angular/drmrmlgelky?file=src%2Fapp%2Fdatepicker-overview-example.html.

Are you sure that there is nothing wrong with your application? Do you see any error in the console?

**Comment by KevinLourd** [comment]
Thank you @codef0rmer. I was indeed missing additional 
`import { MatNativeDateModule } from '@angular/material/core';
`
cf https://stackoverflow.com/questions/60548634/matnativedatemodule-matmomentdatemodule-not-found-in-angular-9-1-1
