### ISSUE TITLE
docs-bug(versions): versions dropdown is wrong in some subdomains

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#21178]
#### Documentation Feedback

Some subdomains show the wrong versions in the versions dropdown. We should always request the versions.json from https://material.angular.io/.

**Affected documentation page:**
* https://v8.material.angular.io/
* https://v9.material.angular.io/

**Comment by mmalerba** [comment]
This is fixed, all of the subdomains are now using the versions.json from master
