### ISSUE TITLE
bug(MatMenu): empty element not removed/hidden from DOM breaks flex layouts

### ISSUE THREAD

**Issue by tomasdev** [angular/components#21182]
#### Reproduction

Demo: https://stackblitz.com/edit/angular-vf8oer?file=src%2Fapp%2Fmenu-icons-example.html

Steps to reproduce:
1. Create a mat-menu inside an element with `display: flex`
 
 
#### Expected Behavior

Given that `mat-menu` is only used to know what to show on the CDK overlay, it should be either safe to remove it or to have a `display: none` by default in its theme definition.

#### Actual Behavior

The render of `<mat-menu>` messes up the flex layout.

#### Environment

- Angular: any
- CDK/Material: any
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
I don't think that we can remove the element manually, because Angular keeps an internal reference to it and it may cause an error next time it tries to destroy it or add something next to it. The proposal about having it be `display: none` sounds reasonable.
