### ISSUE TITLE
bug(MatDialog) while opening buttons stays focused and vice versa

### ISSUE THREAD

**Issue by Gag92** [angular/components#21193]
while opening modal 'OK' button stays focused
![image](https://user-images.githubusercontent.com/13536259/100856039-56c58c00-34a4-11eb-8358-3074b9c0f7d9.png)

and vice versa: pressing 'No thanks', 'Pick One' button stays focused

![image](https://user-images.githubusercontent.com/13536259/100856105-6e047980-34a4-11eb-8afe-8a6f19636f94.png)

example:
https://stackblitz.com/angular/qvlxjvyvpby?file=src%2Fapp%2Fdialog-overview-example.ts

**Comment by decay42** [comment]
Pass in `autoFocus: false` as a dialog option.

In your example:
```this.dialog.open(DialogOverviewExampleDialog, {
      autoFocus: false,
      width: '250px',
      data: {name: this.name, animal: this.animal}
    });```

**Comment by Gag92** [comment]
great thnx
