### ISSUE TITLE
Conflict with ngNeat Tailwind builder causing Angular Material schematics to fail due to not using the default builder

### ISSUE THREAD

**Issue by MirageDT** [angular/components#21199]
#### Feature Description

Whe installing Tailwind CSS (with the help of the ngNeat schematic), it becomes impossible to install Angular Material with the help of the schematic. 

We get served with the error 

```
No project index HTML file could be found.
```

Upon further investigation, it seems that the following line is at the root of the problem : 

https://github.com/angular/components/blob/c68791db9a0b4107d04fa924c27a087cd00a8989/src/cdk/schematics/utils/project-targets.ts#L15

The schematic uses the `builder` property to find its way into the projects and update the files accordingly.

Replacing the builder for the install works, and putting it back give some errors with custom theming (one must import the theming from a relative path to `_theming.scss`). The issue is that not everyone might take the time to look into the source code to find why it does not work ... 

Would it be possible to allow the schematic to be used even when the builder property has changed ?

#### Use Case

Describe the use case(s) that the proposed feature would enable.

**Comment by crisbeto** [comment]
Are you still getting the same error? I spent a bit of time looking into it, but the only error I managed to get was:

```
Your project is not using the default builders for "build". The Angular Material schematics cannot add a theme to the workspace configuration if the builder has been changed.
```

It's also worth noting that the Tailwind schematic generates the following error when running `ng serve`, even before I've tried adding the Material one:

````
Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
```

**Comment by Splaktar** [comment]
The Angular CLI v11.2.x now supports Tailwind without the need for the ng-neat builder. That should enable the Angular Material schematics to be used again.

There may be some other issues with the CLI's Tailwind implementation, but those appear to be getting sorted out.

I think that this can be closed now?

**Comment by crisbeto** [comment]
This shouldn't be a problem with the CLI's built-in support for Tailwind.
