### ISSUE TITLE
bug(mat-expansion-panel): focusable element on the header is being announced as button with entire card content as label

### ISSUE THREAD

**Issue by mirandaxhuang** [angular/components#21198]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://components-issue-r8sc13.stackblitz.io

Steps to reproduce:
1. use stackblitz link above or - create an mat-expansion-panel add one focusable element to the panel header
2. focus on the focusable element and listen to feedback from JAWS with firefox on Windows
 
 
#### Expected Behavior

The focusable element being announced only with its own label and role

#### Actual Behavior

JAWS announces all the content on the card and a role of button for the focusable element 

#### Environment

- Angular: 11.0
- CDK/Material: Material
- Browser(s): firefox
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by annieyw** [comment]
The whole expansion panel header has `role="button"` and putting an element with `role="link"` within it is not supported behaviour.
Changing this to a feature request for a version of the expansion header that has a separate button that opens the panel.

**Comment by jelbourn** [comment]
Closing this as WAI since the expansion panel header _is_ a button, following the semantics of the native `<details>` and `<summary>`  elements. It is thus not supported to put other interactive controls, such as buttons or anchors, inside of the panel header.
