### ISSUE TITLE
bug(CdkPortal): Cannot pass background image to new tab using cdkportal 

### ISSUE THREAD

**Issue by priyaganjare** [angular/components#21192]
#### Reproduction
I am using CDK portal to show static content in new tab(window). I am able to show all content to new tab except background image. Issue is reproduced in below stackblitz url.
https://stackblitz.com/edit/angular-open-window-wisvpv

Steps to reproduce:
1. Load stackblitz url and click on 'open me' button.
2. Separate tab will get opened.
3. Image which is added through css is not appearing in separate tab.
 
 
#### Expected Behavior

What behavior were you expecting to see?
svg icon image should get rendered on separate tab.

#### Actual Behavior

What behavior did you actually see?
svg icon image is not getting rendered on separate tab.

**Comment by annieyw** [comment]
Seems like the background image was being accessed by the relative path.
Demo with fix: https://stackblitz.com/edit/angular-open-window-jcuqzu?file=src%2Fapp%2Fapp.component.css
