### ISSUE TITLE
componentFactoryResolver does not seem to load all children components

### ISSUE THREAD

**Issue by adamraetz** [angular/components#21221]
I am trying to limit unneeded navigation for my SPA by dynamically loading some components and their children components directly to the main page. 

```
    @ViewChild('dynamicInsert', { read: ViewContainerRef, static: false }) dynamicInsert: ViewContainerRef;


    watchForApplication() {
        this.menuService.ApplicationMenuItem.pipe(takeUntil(this.onDestroy$)).subscribe((res: MenuItem) => {

            if (res.menuItemId == 371) {
                let component = TraveldeskLandingComponent;
                this.appName = res.title;
                this.injectDynamicComponent(component);
            }
        });
    }

    // injects the select 3x application into the Workspace
    injectDynamicComponent(componentName) {
        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(componentName);
        const containerRef = this.viewContainerRef;
        containerRef.clear();
        containerRef.createComponent(componentFactory);
    }
```

These are my handler functions. 

Within the HTML of the main page component I have a simple:
```
          <div #dynamicInsert></div>
```

The component I am initially testing to inject looks like this:
```
<div fxLayout="column" fxLayoutAlign="center" style="max-width: 90% !important">
  <mat-tab-group mat-align-tabs="center">
    <mat-tab label="Call Tracker"><app-calltracker></app-calltracker></mat-tab>
    <mat-tab label="Call Report"><app-callreport></app-callreport></mat-tab>
    <mat-tab label="Call Types"><app-calltypes></app-calltypes></mat-tab>
  </mat-tab-group>
</div>

```
Only the first component loads. Within it's tab. The second and third components do not load at all. 

If I try to force only the 2nd or 3rd components they will not load. 

In our production environment where this landing page is navigated to the components load just fine. 

So I am on the trail that there is something wrong with the componentfactory, but I don't understand because why would it load the first tab <app-calltracker> yet if I remove it... it will not load anything.

**Comment by crisbeto** [comment]
It's hard to tell what's going on without a running example. Can you post a Stackblitz that shows the issue? You can fork one of the examples from the docs which has everything set up https://material.angular.io/components/tabs/examples.
