### ISSUE TITLE
bug(mat-checkbox): change color of checkbox dynamically using [ngStyle] or some other way

### ISSUE THREAD

**Issue by Aniket-Kale** [angular/components#21258]
#### Issue description
In my case, I am getting colors from API and I want to bind colors dynamically. I know we can change by adding [CSS](https://stackoverflow.com/a/50795914/9172846) but I need to change dynamically. 

#### Reproduction

[Issue reproduction](https://stackblitz.com/edit/components-issue-checkbox-color-change?file=src%2Fapp%2Fexample-component.html)

Steps to reproduce:
1. Open above stackblitz and open app.component.html file
2. See checkboxes, I am trying to use `[ngStyle]` but I'm not able to bind dynamic colors.

 
#### Expected Behavior

We should be able to change the color of the checkbox using `[ngStyle]` or some other way

#### Actual Behavior

I am not able to change the color dynamically.

#### Environment

- Angular: "^9.0.0"
- CDK/Material: "^9.2.4"
- Browser(s): Chrome
- Operating System: Ubuntu

Please let me know If there is any way to achieve this. Thanks.

**Comment by crisbeto** [comment]
This will be impractical to do on our end, especially if we want it to be consistent and supported across all components. The color of the checkbox can be customized through the `mat-checkbox-color` mixin from `@angular/material/theming`. You can use the mixin to pre-define the possible color combinations and switch between them using a CSS class.
