### ISSUE TITLE
docs-bug(COMPONENT): Are Material components web components?

### ISSUE THREAD

**Issue by lakshaysharmaadp** [angular/components#21261]
#### Documentation Feedback

I see non-native markup in the dom explorer for material angular components. I am trying to understand if that is a web component or something in conjunction with the customElement Registry

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by crisbeto** [comment]
They're not web components, they're regular Angular components. The custom tag names aren't tied to a component in the `customElements` registry.
