### ISSUE TITLE
Allowing a user to pass CSS classes via property binding to the Angular material components.

### ISSUE THREAD

**Issue by indrajit2629** [angular/components#21260]
**Description :**
When a user wants to apply CSS class to one of the rendered HTML element(probably a nested one) by angular material to apply his custom CSS classes it would be easy to apply dynamic theme.

**Use case :**
Apart from pre written theming CSS via SCSS a user can generate CSS variables asynchronously from API call and create respective CSS classes(which get passed as a property binding) to `mat-X ` tags which applies dynamic styling.

**Comment by crisbeto** [comment]
In general we consider the elements inside the `mat-` components as private implementation details that can change between versions so providing this would be impractical. You could change your selector to something like `.mat-checkbox .some-internal-element`, but it's at your own risk.

**Comment by indrajit2629** [comment]
Appreciate your comments, thank you.
