### ISSUE TITLE
Guide for custom form controls causes a TS2611 when implemented with Angular11 / TS4

### ISSUE THREAD

**Issue by rGunti** [angular/components#21274]
#### Documentation Feedback

The current Material documentation (https://material.angular.io/guide/creating-a-custom-form-field-control) proposes that when creating a custom form field control, one can use computed properties to implement required fields. However since Angular 11 & Typescript 4, this causes a TS2611 error when building.

So either the interfaces need to be updated or the documentation needs to change.

**Affected documentation page:** https://material.angular.io/guide/creating-a-custom-form-field-control

**Comment by CueToDo** [comment]
Is there any workaround for this? After upgrade, my project no longer builds.

Error: ../../../node_modules/@angular/material/radio/radio.d.ts:183:9 - error TS2611: 'disabled' is defined as a property in class 'CanDisableRipple & HasTabIndex & MatRadioButtonBase', but is overridden here in 'MatRadioButton' as an accessor. 

Angular 11.0.5
Material 9.1.1
Typescript 4.0.5

**Comment by Mia-Salazar** [comment]
Same here, any solution?

**Comment by crisbeto** [comment]
Closing since it sounds like this was resolved eventually.
