### ISSUE TITLE
bug(mat-slider): when mat-slider has parent with .mat-accent it will not show the primary color

### ISSUE THREAD

**Issue by andreElrico** [angular/components#21271]
#### Reproduction

Steps to reproduce:

https://stackblitz.com/edit/angular-ma9v9u?file=src%2Fapp%2Flist-single-selection-example.html
 
 
#### Expected Behavior

mat-slider with color=primary should display primary color, nomatter where its used.

#### Actual Behavior

If parent has class mat-accent it will make the slider accent color.

### Solution

The solution is obvious:

https://github.com/angular/components/blob/d4f2fa6301e4878fec838a7efa2dd094576f9665/src/material/slider/_slider-theme.scss#L54

this here wins over mat-primary ... Im asking if other components are programmed in this same "general selector fashion"

#### Environment

latest stackblitz from docs (see date of this post)

**Comment by jelbourn** [comment]
While I agree that this is kind of weird, I don't think we will do anything to change it. It's somewhat unexpected to put a slider inside of another form control that supports the `color` input. In particular, putting a slider into a selection list or chip would be invalid from an accessibility perspective.

**Comment by crisbeto** [comment]
This can happen if a slider is put inside a tab group with an explicit color. Reopening.

**Comment by andreElrico** [comment]
Thank you @crisbeto, I can confirm, it will happen with a tab with color accent. It will also happen with a slider inside a toolbar.
 It seems NOT to happen with vert./hor. stepper.
