### ISSUE TITLE
bug(mat-option): toggles on enter, which is not required by ARIA spec

### ISSUE THREAD

**Issue by stevenyxu** [angular/components#21285]
https://github.com/angular/components/blob/87dcfad7d4da40c0decdfc9d1dc0515bd19adb3a/src/material/core/option/option.ts#L166

Typically, options like most selection controls toggle only on space. The ARIA APG demonstrates this https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-rearrangeable.html#ex2_label.

This has resulted in some bugs reported that mat-option is wrongly responding to enter keypresses.

**Comment by crisbeto** [comment]
Removing the "enter" key handling would be easy, but I suspect that if we were to align to the UX pattern linked above, it would be a large breaking change.

**Comment by zarend** [comment]
Hello @stevenyxu ,

Thank you for reporting accessibility issues. Is this only an issue for you when doing the rearrangeable listbox pattern? We currently do not have any components that officially support rearrangeable listbox.

-Zach

**Comment by amysorto** [comment]
Closing this issue since there has not been a follow up response
