### ISSUE TITLE
bug(mat-dialog): dialog has a scroll in Chrome 88

### ISSUE THREAD

**Issue by tiberiuzuld** [angular/components#21337]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/angular/qkjllvpjrrer?file=src%2Fapp%2Fdialog-overview-example.ts

Steps to reproduce:
1.  Open link https://material.angular.io/components/dialog/overview in Chrome 88
2.  Click "Pick one"
3. Observe scroll in the dialog
 
 
#### Expected Behavior

What behavior were you expecting to see?
No scroll in the dialog
Open in Chrome 87 see no scroll.

#### Actual Behavior

What behavior did you actually see?
There is a scroll present in the dialog
This may be an issue in Chrome rendering.

#### Environment

- Angular: 11.0.4, 10.1.0
- CDK/Material: 11.0.2 , 10.2.7
- Browser(s): Version 88.0.4324.41 (Official Build) beta (64-bit) ,  Version 87.0.4280.88 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10, Ubuntu 20.10

Chrome 87 
![image](https://user-images.githubusercontent.com/15310395/101983074-15da2e00-3c81-11eb-8f81-2392149f4f92.png)

Chrome 88 
![image](https://user-images.githubusercontent.com/15310395/101983077-1ffc2c80-3c81-11eb-936b-b40a4d83b9e6.png)

**Comment by jelbourn** [comment]
Marking this as "needs clarification" so that we revisit when Chrome 88 hits stable to see if the issue made it through beta (I at least confirmed it doesn't happen on 87)

**Comment by HitomiTenshi** [comment]
It also happens on Chromium 89. I am currently on `89.0.4349.0` and it's there. I had this bug for about a month now (I'm on Canary) and was hoping that it gets fixed by the Chromium devs, but no changes yet. Pretty sure now that it will land in stable if no one intervenes.

**Comment by HitomiTenshi** [comment]
What's up, me again.

I just tested with the latest build `89.0.4358.0` and the scroll bar is gone. 👏 

Let's hope it gets backported to Chromium 88.

![chrome_2020-12-16_12-12-47](https://user-images.githubusercontent.com/7304212/102341371-0bc57180-3f98-11eb-83e0-a48ddfb6c21c.png)

**Comment by tiberiuzuld** [comment]
Seems to be fixed in beta Version 88.0.4324.50 (Official Build) beta (64-bit)
