### ISSUE TITLE
help(MomentDateAdapter): Luxon Adapter

### ISSUE THREAD

**Issue by toamitc** [angular/components#21347]
As Moment does not support ecmascript module so we are trying to move to Luxon, but wondering if we have LuxonAdapter similar way as we have MomentDateAdapter that can be used with Date Picker? If not what is recommendation?
  
#### Environment

- Angular: 10
- CDK/Material:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by hakimio** [comment]
https://github.com/angular/components/pull/14681
https://github.com/angular/components/issues/20599#issuecomment-705201800

**Comment by annieyw** [comment]
Duplicate of https://github.com/angular/components/issues/20599
