### ISSUE TITLE
bug(mat-tree): mat-tree reports a compilation error wher used with a trackBy option in NestedTreeControl

### ISSUE THREAD

**Issue by POFerro** [angular/components#21364]
Hi,

I have a mat-tree associated with the tree control:
`public readonly mainMenuTreeControl = new NestedTreeControl<IMainMenuNode, string>(node => node.children, { trackBy: this.mainMenuItemTrackBy });`

where `this.mainMenuItemTrackBy` is defined as `(menuNode: IMainMenuNode): string{ ... }`
when used in a view like `<mat-tree [dataSource]="..." [treeControl]="mainMenuTreeControl">...</mat-tree>`

compiler reports an error: 
 error TS2322: Type 'NestedTreeControl<IMainMenuNode, string>' is not assignable to type 'TreeControl<IMainMenuNode, IMainMenuNode>'.
 31         [treeControl]="mainMenuTreeControl"
 
from what I have seen in code I believe MatTree<T> should in fact be MatTree<T, K =T> as is NestedTreeControl defined and the property treeControl should also be: `@Input() treeControl: TreeControl<T, K>;`

Can you help me?
Thanks in advance
POFerro

**Comment by crisbeto** [comment]
An identical issue was reported with the framework a few days ago (https://github.com/angular/angular/issues/40125), could it be the same as this one? Can you try the solution from the last comment to see if it resolves it?

**Comment by POFerro** [comment]
Hi @crisbeto ,

No, this case is different, I'll explain:
As of commit: [#19602](https://github.com/angular/components/commit/e2c7e1ab878b6a4019ee85efdda17b535d40ead4)
TreeControl is defined as two argument generic: `TreeControl<T, K = T>` this change was to include the ability of having a trackBy function defined in the control itself and K is the return type of this function. 

While this change happened in the TreeControl classes the class MatTree didn't change to reflect the second generic parameter so now if K != T in TreeControl class the property type in MatTree will mismatch since it is defining the property type as being `TreeControl<T, T>` (second generic parameter type is being inferred by default value K = T).

**Comment by rafaelss95** [comment]
This should be closed by #21421.

**Comment by crisbeto** [comment]
Thanks for the heads-up. Closing as something that should've be resolved.
