### ISSUE TITLE
feat(cdkDragDrop): Update the displaced area by a placeholder when it's size is dynamically changed during drag

### ISSUE THREAD

**Issue by rotsin** [angular/components#21379]
#### Feature Description

Currently when using cdkplaceholder, the height of it can be changed dynamically changed during drag:
`<div class="drop-preview-placeholder" [ngStyle]="{ 'min-height': someDynamicHeight }" *cdkDragPlaceholder></div>`

The problem is that when the placeholder is drawn into a droplist it will use it's initial height when offsetting items in the list. It somehow needs to be updated to use the new height. The visual size of the placeholder is correct, but a large empty area appears below it and other elements from the list are pushed downward and rendered over other elements.

Is there a way to update this placeholder offset during a drag?
If not, is there a way to end the current drag and programmatically start a new one (with the updated placeholder)?

#### Use Case

I have a board with several lanes. Each lane contains cards. The cards can be moved amongst themselves or onto other lanes. Each card contains line items. The items can be moved amongst themselves or onto other cards and also in the lanes themselves. When a line item is dropped into a lane, a new card is created with that item. I would like to have a placeholder for the line item that has the height of a line item when dragging it onto a card and the height of a card when dragged over a lane.

![1](https://user-images.githubusercontent.com/6517497/102492610-9b435100-407a-11eb-88c8-17bdbb69e3d1.png)
![2](https://user-images.githubusercontent.com/6517497/102492620-9ed6d800-407a-11eb-8f70-6029d36d33b2.png)

Thank you!

**Comment by crisbeto** [comment]
I believe this is the same problem as https://github.com/angular/components/issues/14703. We try to limit the number of measurements we're making of the DOM since it can impact performance and there's no good way of knowing when the size of an element has changed.
