### ISSUE TITLE
bug(mat-tab): mat-tab content disappearing when order changes, using Ivy

### ISSUE THREAD

**Issue by satnav** [angular/components#21374]
#### Overview
I am trying to implement a mat-tab-group with multiple tabs where the user can drag and drop the tabs to re-arrange their order. When a tab gets moved (via the drag and drop), the content of the other tabs will disappear (depending on which tab is moved). However I was only able to replicate this issue when Ivy was enabled.

#### Reproduction
Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-vmj8fs

Steps to reproduce:
1. Open the StackBlitz and re-arrange the tabs by dragging and dropping. The content of each tab will be visible when you click between then.
2. Go to the Settings panel on StackBlitz and check Enable Ivy.
3. Once compiled, re-arrange the tabs again; the content of some of the tabs will disappear. (e.g. if you move tab 1 to the last position, tabs 2, 3, 4, and 5 will have no content).
 
#### Expected Behavior
The content of each tab to be preserved.

#### Actual Behavior
The content of tabs disappearing.

#### Environment
- Angular: 11.0,4
- CDK/Material: 11.0.2 both
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I believe that this is an issue in the framework. Potentially the same as https://github.com/angular/angular/issues/37895.

**Comment by crisbeto** [comment]
I'll close this since it appears to be the same issue as the linked one.
