### ISSUE TITLE
bug(datepicker) : The callback on matDatepickerFilter does not receive a Date, but an object like { _d: Date , ...}

### ISSUE THREAD

**Issue by WaterLion-Be** [angular/components#21396]
#### Reproduction

Use StackBlitz to reproduce your issue: 
To reproduce : https://stackblitz.com/edit/angular-ivy-yeydki

Steps to reproduce:
1. Create a project containing a Datapicker with matDatepickerFilter

npm install @angular/material @angular/cdk
npm install @angular/animations
npm install hammerjs
npm install moment
npm install @angular/material-moment-adapter
 
#### Expected Behavior

Continue to receive a (Date | null) in matDatepickerFilter callback.

#### Actual Behavior

Receiving an object like 
`Object { _isAMomentObject: true, _i: {…}, _isUTC: false, _pf: {…}, _locale: {…}, _d: Date Thu Dec 24 2020 00:00:00 GMT+0100 (heure normale d’Europe centrale), _isValid: true }`
(You can see it in a browser console (not in the StackBlitz console))

#### Environment

- Angular: 11.0.5
- CDK/Material: 11.0.3 / 11.0.3
- Browser(s): FireFox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
The function receives whatever date format you've configured through the date adapter. In your example you've added the `MomentDateAdapter` which means that you're getting moment.js date objects.

**Comment by WaterLion-Be** [comment]
Thanks and sorry for my lack of experience with web applications. It was by importing `@angular/material-moment-adapter` and not using it that I produced this effect.
