### ISSUE TITLE
help(Dialog): 100% height on body element causing issues

### ISSUE THREAD

**Issue by Araknos** [angular/components#21414]
I have an issue with Dialog component from Material similar to https://github.com/angular/material/issues/681

When opening a dialog with

```
html, body {
    height: 100%;
}
```

A second scrollbar appears and the background screen is buggy (going under my footer, out of the screen).

This answer https://github.com/angular/material/issues/681#issuecomment-86023189 fixed my bug but is this supposed to be resolved ?

#### Environment

- Angular: 9
- CDK/Material: 10.2.7

**Comment by crisbeto** [comment]
I wasn't able to reproduce it by setting `height: 100%` in our dev app. Can you post an example that shows the issue? You can fork one of the examples [from the docs](https://material.angular.io/components/dialog/overview) to Stackblitz.

**Comment by Araknos** [comment]
Here is an example: https://stackblitz.com/angular/lmgyqdyygqpk
The problem was `overflow-x: hidden` !
