### ISSUE TITLE
bug(mat-menu): menu gets cut off below the screen if you force it not to close and then filter a list

### ISSUE THREAD

**Issue by hypocore** [angular/components#21413]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- https://stackblitz.com/edit/angular-10-material-mat-menu-cutoff-issue-test

Steps to reproduce:
1. Scroll down until half of the "8" is visible
2. There should be just enough room for the menu to open downward
3. Open the menu
4. Click "Filter less than 6" in the menu
5. Notice the menu is cutoff at the bottom of the screen
6. If a scroll bar appears on the menu, you have either scrolled down too far or scrolled back up after opening the menu
 
 
#### Expected Behavior

A scrollbar appears or the menu repositions itself above the trigger.

#### Actual Behavior

The menu cuts off options below the bottom of the screen scroll height.

This appears to be similar to:
https://github.com/angular/components/issues/17477

The workaround listed in that bug report does not fix the issue.

The menu cut-off issue is much worse if you add a min-height to the menu. The actual requirement I have is to have the menu remain open and not scroll internally. 

#### Environment

- Angular: 10.2.4
- CDK/Material: 10.2.7
- Browser(s): 
Chrome 87.0.4280.88 (Official Build) (64-bit), 
Firefox 82.0.3 (64-bit), 
Edge 44.18362.449.0
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by hypocore** [comment]
updating to angular 11 and showing min-height in another bug as jamesnben to so bug report can be shown at work.

**Comment by hypocore** [comment]
reopening because the bug is still present, please refer to https://github.com/angular/components/issues/21420 for a more easily reproducible version with min-height.

**Comment by crisbeto** [comment]
This seems identical to https://github.com/angular/components/issues/21420. Closing as a duplicate.
