### ISSUE TITLE
bug(dialog): mat-dialog doesn't close when a navigation happens

### ISSUE THREAD

**Issue by ms-dosx86** [angular/components#21411]
#### Expected Behavior

A dialog should close when an angular navigation happens

#### Actual Behavior

A dialog closes only when you hit the "back" button, but doesn't close when you navigate via `routerLink` or `Router.navigate`. It does make sense, since OverlayRef subscribes to `Location`'s events, not `Router`'s. But what's the point of `closeOnNavigation` option if it doesn't close on angular navigation? I've googled and haven't found an answer to my question, so I'm asking here. Why do you guys use `Location`'s events? It seems like [this code](https://github.com/angular/components/blob/master/src/cdk/overlay/overlay-ref.ts#L153) should look like
```
    if (this._config.disposeOnNavigation) {
      this._locationChanges = this._router.events
        .pipe(filter(event => event instanceof NavigationEnd))
        .subscribe(() => this.dispose());
    }
```

where `this._router` is a `Router`'s instance. But surely you know more than I do, so I just wanna know why it is designed like so.

#### Environment

- Angular: 11.0.0
- CDK/Material: 11.0.0
- Browser(s): Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS 10.15.7

**Comment by crisbeto** [comment]
The reason it's set up this way is that we don't want to add a dependency between Material and `@angular/router` since all apps might not necessarily be using Angular's router. If you want a generic way to handle this in your app, you can add something like the following in your main module:


```
constructor(router: Router, dialog: MatDialog) {
  router.events.subscribe(event => {
    if (event instanceof NavigationEnd) {
      dialog.closeAll();
    }
  });
}
```

**Comment by ms-dosx86** [comment]
@crisbeto Thanks
