### ISSUE TITLE
bug: cdk drag drop, changed font in dragged item when fullscreen

### ISSUE THREAD

**Issue by b-mi** [angular/components#21443]
Angular / material / cdk 9, 10, 11.

When fullscreen by code / runtime, font of dragged item has changed font.

Bug in Chrome, Edge, Firefox, on android mobile chrome browser

Stackblitz: https://angular-9-material-starter-2vgvna.stackblitz.io/
Stackblitz source: https://stackblitz.com/edit/angular-9-material-starter-2vgvna?file=src%2Fapp%2Fapp.component.html

See font difference here:
![image](https://user-images.githubusercontent.com/26021541/103154874-19020d80-479b-11eb-9ea7-308696956eea.png)

Font should not change during drag.

**Comment by crisbeto** [comment]
It's because the drag preview is inserted into the fullscreen element, if there is one, otherwise it won't be visible. In your case the `body` has the font styles while the `html` is the fullscreen element. You can fix it on your end either by making the `body` fullscreen or moving the font styles to the `html`.

**Comment by b-mi** [comment]
Thank you, it works. 

` 

    let elem = document.documentElement; // bug with font
    let elem = document.body; // fix font problem
`

However, after the change, the background color changes to black. It probably doesn't matter in a regular application. But F11 in Chrome sets fullscreen so that it is neither necessary to change the fullscreen background color. 
Maybe cdk could also support the correct procedure for switching to fullscreen, because many codes on the web for fullscreen do not work properly. 
Also, this nice cdk Drag-drop functionality does not support responding to a dark theme. 
It would be very nice if it could be worked out. 
Well thank you.
