### ISSUE TITLE
bug(Angular Material 11 Samples): Sample projects don't work forked locally

### ISSUE THREAD

**Issue by florin05** [angular/components#21461]
#### Reproduction
Steps to reproduce:
1. Got to sample input component page https://material.angular.io/components/input/overview
2. Click on the "Edit basic inputs example in StackBlitz"
3. Sample app works fine
4. Download code locally: (Fork the project,  Connect repository, clone the repo locally)
5. In the local project folder run "npm install"
6. run "npm run start"
7. in browser go to http://localhost:4200/
8. App does not render (shows "loading Current build: 11.0.3")

Same behavior with other Angular Material 11 sample projects
Same steps with Angular Material 10 samples work fine
Noe: If I change the index.html content to place the component directive inside the "body" element directly, it renders, but the formatting is not applied. 
 
 
#### Expected Behavior

At step 8 I expect to see the same behavior as I see in Stackblitz sample or with Angular Material 10 local app
![image](https://user-images.githubusercontent.com/11194908/103229835-e45c9600-4901-11eb-8b19-356349c06380.png)

#### Actual Behavior

See step 8
![image](https://user-images.githubusercontent.com/11194908/103229736-ad868000-4901-11eb-80b4-5d42af058c28.png)

#### Environment

- Angular: 11
- CDK/Material: 11
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
For the record, it seems to work for me when I download the Stackblitz directly, but I haven't tried forking it to a repo. Do you get an error in the console?

**Comment by florin05** [comment]
> For the record, it seems to work for me when I download the Stackblitz directly, but I haven't tried forking it to a repo. Do you get an error in the console?

Indeed, if I download the project it works.
I think the difference is in the "index.html" content, once I copy the one from the downloaded version it works.
The forked version is this, missing the "html" and "body" tags

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet">
<div class="mat-app-background basic-container">
  <input-overview-example>loading</input-overview-example>
</div>
<span class="version-info">Current build: 11.0.3</span>
```
