### ISSUE TITLE
bug(mat-tab): tabs pagination not working when ChangeDetectionStrategy.OnPush active

### ISSUE THREAD

**Issue by Neill83** [angular/components#21494]
https://stackblitz.com/edit/angular-lqxupf?file=src/app/tab-nav-bar-basic-example.ts

I want to get working the pagination when change detection is on push. What can i do? Is this a bug?

**Comment by crisbeto** [comment]
I think the problem is that you're detaching the `ChangeDetectorRef` in the constructor which will prevent the changes from being picked up.

**Comment by Neill83** [comment]
Yes but that's what i need to do to use `cdr.detectChanges()`. Or am I wrong?

**Comment by crisbeto** [comment]
I think that comment applies mostly for very performance-sensitive applications. You should be able to remove the `detach` and `detectChanges` calls in your example.

**Comment by Neill83** [comment]
In the example, for sure... but in my real project its a bit questionable to do that
