### ISSUE TITLE
bug(mat-dialog): The typing for `_closeDialogVia` method is invalid

### ISSUE THREAD

**Issue by semens-corp** [angular/components#21503]
#### Reproduction

Try to use `_closeDialogVia` method with a `MatDialogRef<T, R>` where `T` and `R` are different types (probably the most common case).

StackBlitz (really abstract example here, but it shows the behavior):
https://stackblitz.com/edit/dialog-ref-closing-issue?file=src%2Fapp%2Fexample-component.ts

#### Expected Behavior

What behavior were you expecting to see?

TypeScript compiler should allow to use `_closeDialogVia` method with a `MatDialogRef<T, R>` instance where `T` and `R` are different types.

#### Actual Behavior

What behavior did you actually see?

TypeScript compiler complains about the types of `result` parameter being incompatible with what is provided as an argument.

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

**Comment by jelbourn** [comment]
The underscore indicates that this is a private method and should not be used by downstream apps.

**Comment by semens-corp** [comment]
@jelbourn 
Hm, even though it's a private method, there is still a mistake in the method's typing, right? And the method can be used from the library's code.
Moreover, judging by the comment in the code, this method is (or was?) going to become a part of public API. Should we really close it without a resolution?
