### ISSUE TITLE
ngbDropdown not working with cdkDrag Angular 11.0.3

### ISSUE THREAD

**Issue by abhayciitizen** [angular/components#21518]
`ngbDropdown` not closing when clicking on menu item. Its working fine outer side `cdkdrag` div but not inside cdkdrag. I tried remove cdkDrag then its working fine. I also tried to change version of `ngbDropdown` and `cdkDrag`.
It's also working fine when using manual installing `bootstrap` with `jQuery`.

**Comment by crisbeto** [comment]
I don't know how the `ngbDropdown` is set up, but my guess is that the internal `event.stopPropagation` on `mousedown` from the CDK is breaking it. The `stopPropagation` call has been removed in https://github.com/angular/components/pull/21227 which should resolve it.
