### ISSUE TITLE
Please Support column resize on table!!! PLEASEEEEEE

### ISSUE THREAD

**Issue by mikila85** [angular/components#21514]
#### Feature Description

COLUMN RESIZE

Please Support column resize on table!!! PLEASEEEEEE

#### Use Case

EVERY DAY EVERY ONE ALWAYS ASKING FOR THIS, Please please stop doing experimental and do column resize as part of mat-table <3 <3 <3

**Comment by michaelnem** [comment]
Yes we need this!!!s

**Comment by mikila85** [comment]
+1

**Comment by mycwacc** [comment]
+1

**Comment by jelbourn** [comment]
Duplicate of #8312
