### ISSUE TITLE
feat(CdkOverlay): bring it back excludeFromOutsideClick 

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#21521]
#### Feature Description
If I not missing up something, I remember in material v10. there is a overlay config "excludeFromOutsideClick" allow us to set some custom logic about outside click. but I can't found it in v11.

version 10
![image](https://user-images.githubusercontent.com/8691013/104051063-7d54b080-5222-11eb-9dc0-83f997f3a5d2.png)

version 11
![image](https://user-images.githubusercontent.com/8691013/104051103-8ba2cc80-5222-11eb-8b30-9af8548598c9.png)

#### Use Case
When clicking Google ads menu trigger button, the menu won't close. 
If I try to implement it using CDK overlay, the menu will close when clicking the trigger button. because the button is outside of overlay.

Google Ads
![dada1](https://user-images.githubusercontent.com/8691013/104051286-e0dede00-5222-11eb-86b5-56fa6c7d85de.gif)

CDK Overlay
![dada11](https://user-images.githubusercontent.com/8691013/104051703-81cd9900-5223-11eb-89e8-b687275971ff.gif)

Please consider bring it back.

**Comment by crisbeto** [comment]
It's been a while since the change was made, but from what I remember, we decided that the API was a bit too rigid only with the string. We ended up with a `overlayOutsideClick` event emitter that you can subscribe to and decide how you want to handle it. Is this what you're using?

**Comment by keatkeat87** [comment]
oic, alright, I got it, I will handle it myself, thank for your quick reply ^.^
