### ISSUE TITLE
bug(DIALOG): Dialog's content jump around after opening

### ISSUE THREAD

**Issue by Akxe** [angular/components#21520]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-1fvgvm

Steps to reproduce:
1. Click on "Basic Button"
2. See odd behaviour
 
 
#### Expected Behavior

Dialog appeared and no content re-drawing appears

#### Actual Behavior

You see the panels are open and immediately change to closed. This sudden change makes it very unappealing to the eye.

#### Environment

- Angular: 11.0.7 (10.1.0 on my PC)
- CDK/Material: 11.0.3 (10.2.5 on my PC)
- Browser(s): Chrome, but probably all
- Operating System (e.g. Windows, macOS, Ubuntu): independant

**Comment by crisbeto** [comment]
I believe this is the same issue as https://github.com/angular/components/issues/13870.
