### ISSUE TITLE
ng-reflect-model shows correct value but not reflecting in mat select

### ISSUE THREAD

**Issue by Akhil-kotha** [angular/components#21539]
<mat-label class="col-sm-4 col-form-label" >Crop Type  <span  class="required-asterisk">*</span></mat-label>  
        <div class="col-sm-10">  
       <mat-select   placeholder="Select Crop Type" [(ngModel)]="cropname"  class="select" formControlName="croptype">
            <mat-option *ngFor = "let i of Croptype"  [value] = "i">{{i.CropName}}</mat-option> 
       </mat-select>
        </div>  
When i tried to use two way binding to bind dynamic value to ngmodel, ng-reflect-model is updating correct value,but view is not getting updated
In component.ts
 Croptype =
 [ { CropID: '1', CropName: 'sweetlime', ScientificName: 'CitrusImetta' }, ];
 this.cropname=newsortOrder != undefined ? newsortOrder.cropName : ''; 
when iam updating ngmodel value with below line the above issue occurs

The issue is in following example: https://stackblitz.com/edit/angular-be1gqv?file=src%2Fapp%2Fapp.component.html

**Comment by crisbeto** [comment]
The `ng-reflect-` attributes are mostly there for backwards-compatibility and you shouldn't depend on them, because they won't be set in production mode. Closing the issue, because it's also something that the framework is responsible for.

**Comment by Akhil-kotha** [comment]
so,please tell the fix for this issue
