### ISSUE TITLE
feat(COMPONENT): TITLE

### ISSUE THREAD

**Issue by xyboox** [angular/components#21553]
#### Feature Description

I was wondering if there is or would be any implementation of the google-maps map-circle events ( like radius_changed )

#### Use Case

I have a map with a radius setable by the user and would like to be able to subscribe to the radius_changed event so I can re-set the map zoom level based on the new bounds.

**Comment by crisbeto** [comment]
There seems to be a `radiusChanged` event already: https://github.com/angular/components/blob/master/src/google-maps/map-circle/map-circle.ts#L150
