### ISSUE TITLE
ng-reflect-model shows correct value but not reflecting in mat select

### ISSUE THREAD

**Issue by Akhil-kotha** [angular/components#21550]
Crop Type *

<mat-select placeholder="Select Crop Type" [(ngModel)]="cropname" class="select" formControlName="croptype">
<mat-option *ngFor = "let i of Croptype" [value] = "i">{{i.CropName}}

When i tried to use two way binding to bind dynamic value to ngmodel, ng-reflect-model is updating correct value,but view is not getting updated
In component.ts
Croptype =
[ { CropID: '1', CropName: 'sweetlime', ScientificName: 'CitrusImetta' }, ];
this.cropname=newsortOrder != undefined ? newsortOrder.cropName : '';
when iam updating ngmodel value with below line the above issue occurs
stackblitz example: https://stackblitz.com/edit/angular-be1gqv?file=src%2Fapp%2Fapp.component.html

**Comment by crisbeto** [comment]
We don't have control over how `ng-reflect-` attributes are set, this is something that the framework is responsible for. Furthermore, they're only set during development mode so you shouldn't be depending on them in the first place.
