### ISSUE TITLE
MatSelect's dropdown with many options is positioned incorrectly after browser resize

### ISSUE THREAD

**Issue by dmromanov** [angular/components#21571]
**Overview of the Issue**
MatSelect's dropdown with **many options** is positioned incorrectly after browser resize
The issue doesn't occur if selectbox has few options (2-3)

Angular and Material Versions
**8.2.3**
Also reproduced in newer versions: 
9.0.0
10.2.7
11.0.3

**Motivation for or Use Case**
The dropdown popup is visually unrelated and detached from the parent selectbox. Works differently for other uses of the selectbox

**Browsers and Operating System**
Reproduced on Firefox 84.0.2, Chromium 87.0.4280; issue looks like browser-independent issue.

**Reproduce the Error**

1. Open documentation for Angular Material SelectBox https://v8.material.angular.io/components/select/examples
2. Find a selectbox with **many options**: State selector.
3. Scroll the window so that the selectbox is located near to the bottom of browser's window
3. Select an option in the middle of the list: Michigan
4. Open a dropdown again, don't click anything
5. Reduce browser's window' height from the bottom
Dropdown element will reposition itself incorrectly

**Screenshots**

![image](https://user-images.githubusercontent.com/299059/104445144-d2d5e800-55a9-11eb-9175-9c4b695aa84d.png)

**Related Issues**

This issue from AngularJS Material looks like somewhat similar to the current issue https://github.com/angular/material/issues/5435

**Comment by amysorto** [comment]
When I tested this in using the MDC based select component coming soon in v15, things seem to reposition correctly when following the steps above.
