### ISSUE TITLE
feat(mat-color-picker): Built in color picker

### ISSUE THREAD

**Issue by ishanuda** [angular/components#21581]
#### Feature Description

Is it possible to develop a color picker as a built in feature in the library.
Some examples are:

[md-color-picker](https://www.uplabs.com/posts/angular-material-color-picker)
[Angular Material Color Picker](https://www.npmjs.com/package/@angular-material-components/color-picker)
[Angular Color Picker](https://www.npmjs.com/package/ngx-color-picker)

#### Use Case

This will enable to use the color picker as a built in feature for developers.

Thank you very much

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/2948.
