### ISSUE TITLE
bug(mat-expansion-panel): scrollIntoView sets header content to empty when collapsed

### ISSUE THREAD

**Issue by amiteshhh** [angular/components#21622]
#### Reproduction

https://stackblitz.com/edit/angular-yg9mb5

Steps to reproduce:
1. Collapse the expansion panel
2. Call method `scrollIntoView` on any of the content element
 
 
#### Expected Behavior

It should do nothing or at least expansion panel header text should still be visible.

#### Actual Behavior

`mat-expansion-panel-header` is shifting up by few pixel and leaving the content empty.

#### Environment

- Angular: 11.0
- CDK/Material: 11.0
- Browser(s): Chrome/Edge/Safari
- Operating System (e.g. Windows, macOS, Ubuntu):  WIndows/Mac

![image](https://user-images.githubusercontent.com/11266423/105022908-48d9c380-5a70-11eb-82e0-1d8aba6b756d.png)

**Comment by crisbeto** [comment]
I believe this is the same issue as https://github.com/angular/components/issues/21159.
