### ISSUE TITLE
bug(cdk): Animations fire only the first time

### ISSUE THREAD

**Issue by pgkehle** [angular/components#21635]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/ncstate-sat-popover-examples
- Harnesses: https://stackblitz.com/edit/ncstate-sat-popover-issues

Steps to reproduce:
1. Hover over the demo popover, popover opens with expected animations
2. Blur the demo, popover closes with expected animations
3. Hover over again, popover opens immediately without animations
 
 
#### Expected Behavior

What behavior were you expecting to see?

Step 3 should have opened the popover with the same animations as the first time.

#### Actual Behavior

What behavior did you actually see?

The popover opens immediately without animations.

#### Environment

- Angular: ^11.0.0
- CDK/Material: ^11.0.0
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

Note: We have an open issue on the project regarding this issue [here](https://github.com/ncstate-sat/popover/issues/194
)

**Comment by crisbeto** [comment]
This is likely an issue with the `@ncstate/sat-popover` project. The CDK hasn't really changed how it works for several major versions now.

**Comment by pgkehle** [comment]
Not really looking for 'likely an issue' statement here. We have tried a number of things to debug the project without success. Nothing is glaringly different. 

Please look again.

**Comment by crisbeto** [comment]
I'm confident that the issue isn't on our end, because all overlay-based components in `@angular/material` use the CDK and they don't have such animation issues. E.g. you can see how `mat-menu` or `mat-tooltip` are set up.

**Comment by pgkehle** [comment]
@crisbeto thank you.  We can look at those two as examples.  In my debug I didn't see anything that stood out that might be different.
