### ISSUE TITLE
bug(mat-select): mat-select-color mixin does not style mat-options whereas mat-select-theme mixin does

### ISSUE THREAD

**Issue by Argee88** [angular/components#21644]
#### Reproduction

Steps to reproduce:
1. Include the mat-select-theme mixin to register the default theme (here dark-theme) `@include mat-select-theme($dark-theme);`
2. Include the mat-select-color mixin to override the default theme (here with the light-theme) `.light-theme { @include mat-select-color($light-theme); }`

#### Expected Behavior

When using the light theme and clicking on a mat-select, I expect the the options to be styled according to the style definitions for the light theme.

#### Actual Behavior

The options are styled according to the style definitions for the default (dark) theme. This only changes when I additionally include `@include mat-option-color($light-theme);`

Either I should have to include `@include mat-option-theme($dark-theme);` when setting up the default theme or mat-select-color should take care of the styling of the options as well. Anything else is confusing.

#### Environment

- Angular: 10.1.6
- CDK/Material: 10.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
`mat-option` has a separate theme called `mat-option-theme`.

**Comment by Argee88** [comment]
True. However, it appears that mat-select-theme also takes care of what mat-option-theme's job is; but mat-select-color does not take care of what mat-option-color's job is. That's the inconsistency I mean.

```
@include mat-select-theme($dark-theme);

.dark-theme {
  @include mat-select-color($dark-theme);
}

// at this point the default styling and the .dark-theme are correctly applied on mat-selects and mat-options

.light-theme {
  @include mat-select-color($light-theme);
  @include mat-option-color($light-theme); // <-- has to be included in order to override mat-option colors correctly; based on the setup earlier I would expect mat-select-color to be sufficient
}
```

**Comment by jelbourn** [comment]
I don't quite follow here; `mat-select-theme` doesn't do anything _but_ call `mat-select-color`:
https://github.com/angular/components/blob/029136e1810bef1359c79263bbdcddc9af2910a7/src/material/select/_select-theme.scss#L82-L99

So I don't see how their behavior could be different.

**Comment by crisbeto** [comment]
Closing since there hasn't been any clarification in a while.
