### ISSUE TITLE
NG-Bootstrap not working in 11 based on 10 Doc.

### ISSUE THREAD

**Issue by pankajToday** [angular/components#21641]
I am have installed new angular 11 form cli. that is totally new version.  so after that when i try to install 

`ng add @ng-bootstrap/ng-bootstrap`
then it giving me errors 

Installing packages for tooling via npm.
Installed packages for tooling via npm.
UPDATE package.json (1412 bytes)
UPDATE src/app/app.module.ts (1606 bytes)
UPDATE angular.json (3666 bytes)
- Installing packages (npm)...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: instafixx@0.0.0
npm ERR! Found: @angular/common@11.0.9
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^6.0.0" from @ng-bootstrap/ng-bootstrap@2.2.2
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"^2.0.0-alpha.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Apoorva\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Apoorva\AppData\Local\npm-cache\_logs\2021-01-19T14_00_28_351Z-debug.log

my package to json file 
{
  "name": "instafixx",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.6",
    "@angular/common": "~11.0.6",
    "@angular/compiler": "~11.0.6",
    "@angular/core": "~11.0.6",
    "@angular/forms": "~11.0.6",
    "@angular/platform-browser": "~11.0.6",
    "@angular/platform-browser-dynamic": "~11.0.6",
    "@angular/router": "~11.0.6",
    "@ng-bootstrap/schematics": "^2.0.0-alpha.1",
    "@types/jquery": "^2.0.47",
    "jquery": "^3.5.1",
    "ngx-captcha": "^8.0.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0-alpha.0",
    "bootstrap": "^4.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.6",
    "@angular/cli": "~11.0.6",
    "@angular/compiler-cli": "~11.0.6",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

please note that "@ng-bootstrap/ng-bootstrap": "^2.0.0-alpha.0", being locate here. but i try to use  **Alert**  or etc component then it create many issue.

**Comment by jelbourn** [comment]
The ng-bootstrap repo is here: https://github.com/ng-bootstrap/ng-bootstrap
