### ISSUE TITLE
docs-bug(mat-autocomplete): problem with formControl binding in reactive forms

### ISSUE THREAD

**Issue by Ric-01** [angular/components#21642]
#### Documentation Feedback

I face the following issue when using material autocomplete version 11.0.3 together with Angular 11.0.9:
If coding the formControl property binding into the the connected input element like described on the documentation page (https://material.angular.io/components/autocomplete/overview) together with reactive forms approach, the posted object is always null.
I changed it by doing like follows:

Instead of
```html
<input type="text" matInput [formControl]="myFormControlName" [matAutocomplete]="auto" />
```
I did the following:
```html
<input type="text" matInput formControlName="myFormControlName" [matAutocomplete]="auto" />
```
Only the latter one works in that sense, that the object posted from the input is not null in onSubmit event.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** https://material.angular.io/components/autocomplete/overview

**Comment by jelbourn** [comment]
In your snippet it looks like you tried binding a form control **name** to the form control property, which expects a form control instance. If there's something else going on, feel free to open a new issue with a StackBlitz reproduction.
