### ISSUE TITLE
bug(cdk/overlay): use of ngZoneRunCoalescing opens the overlay at wrong position

### ISSUE THREAD

**Issue by michael-hein** [angular/components#21674]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-wgkr2a

Steps to reproduce:
1. setting"ngZoneRunCoalescing" to "true" in the main.ts
``` ts
platformBrowserDynamic()
  .bootstrapModule(AppModule, { ngZoneRunCoalescing: true })
  .catch(err => console.error(err));
```
2. open any CDK overlay or any angular-material component which uses them (mat-select, mat-bottom-sheet..)
 
#### Expected Behavior
* the overlay should open at the right position
![image](https://user-images.githubusercontent.com/51996054/105460560-4489f200-5c8c-11eb-9d46-98953c9d5987.png)

#### Actual Behavior
* overlay opens at top left
![image](https://user-images.githubusercontent.com/51996054/105460592-4f448700-5c8c-11eb-927d-508cbe99146e.png)

#### Environment

- Angular: 11.1.0
- CDK/Material: 11.1.0
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The issue comes from the fact that `NgZone.onStable` doesn't emit when the option is enabled. There are other places in Material and the CDK that are broken by this behavior. Is this intended @JiaLiPassion?

**Comment by JiaLiPassion** [comment]
@crisbeto , this is a bug of `ngZoneRunCoalescing`, and in fact, there is a dead loop when enable this option, I will create a PR to fix it asap.
