### ISSUE TITLE
bug(Mat-Checkbox): Change event not trigger when checked change programmatically/using toggle()

### ISSUE THREAD

**Issue by phoenix09208** [angular/components#21670]
`change` event does not fires when setting `checked` or call `toggle()` of the mat-checkbox

according to [documentation](https://material.angular.io/components/checkbox/api) 

@Output()change: EventEmitter<MatCheckboxChange> | Event emitted when the checkbox's checked value changes.
-- | --

and

toggle
--
Toggles the checked state of the checkbox.

#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-8zxzxh-mbe54c

Steps to reproduce:
1.  bind `change` event for `mat-checkbox`
2.  call `checkbox.toggle()` in code
 
 
#### Expected Behavior

`change` event fires

#### Actual Behavior

`change` not event fires

#### Environment

- Angular: 11.1.0
- CDK/Material: 11.0.1
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
In general we have a rule that we only dispatch `change` events when the value was changed by the user. Since you're the one making the programmatic change, you should already know when the change is happening.
