### ISSUE TITLE
bug(DragDropModule): Dropping an item triggers click event in document in Firefox only.

### ISSUE THREAD

**Issue by antur84** [angular/components#21691]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-dnd-firefox-click-ubxh75?file=src/app/cdk-drag-drop-sorting-example.ts

Steps to reproduce:
1. Use Firefox (latest).
2. Drag and drop items in the list. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

No logs should be written to console, the listener is setup for document click events.
This is working as expected in MS Edge (chromium, latest) and Google Chrome (latest)

#### Actual Behavior

What behavior did you actually see?

Document click events are triggered, logs are written to console.

#### Environment

- Angular: 11.0 (11.1 still broken)
- CDK/Material: 11.0 (11.1 still broken)
- Browser(s): Firefox
- Operating System Windows 10

**Comment by crisbeto** [comment]
The `drag-drop` module is set up not to mess with `click` events at all so this is likely a browser-level issue. If you want to prevent the event consistently across all browsers, you can add `(mousedown)="$event.preventDefault()"`.

**Comment by antur84** [comment]
Thanks for the swift reply. Unfortunately I can't even mend the StackBlitz reproduction example with the `mousedown` fix, no matter what dom level I apply it on. Resorted to pausing the click listener on body during dragging instead. 🤷‍♂️
