### ISSUE TITLE
bug(MatListItemHarness): wrong host selector

### ISSUE THREAD

**Issue by tryptophane** [angular/components#21717]
This is the definition of the hostSelector for MatListItemHarness:

```static hostSelector = `${MatListHarness.hostSelector} .mat-list-item`;```

This will never match, because a mat-list-item usually doesn't have the CSS class attribute "mat-list".

**Comment by crisbeto** [comment]
I'm not sure I follow what the problem is here. The selector means that it's search form a `.mat-list-item` inside a `.mat-list`.

**Comment by tryptophane** [comment]
My bad, sorry for the noise...
