### ISSUE TITLE
bug(DatePicker): StackBlitz provided in the documentation does not show dates in French format

### ISSUE THREAD

**Issue by Yanal-Yves** [angular/components#21724]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- https://stackblitz.com/angular/qmoqvlayglx?file=src%2Fapp%2Fdatepicker-locale-example.ts

Steps to reproduce:
1.  Go to https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings
2. Search for "Datepicker with different locale" => you should find the section explaining how to set the local for mat-date-picker
3. Click on the StackBlitz link => the StackBlitz open in a new tab
4. Select a date (for instance 2020-12-09 => the formatted date selected in the input is "12/9/2020"
5. Click "Dynamically switch to French" button => nothing happens

#### Expected Behavior

The input should show "09/12/2020"

French date rules:
- French people write "Day/Month/Year"
- Dates are padded with 0. We write "09/12/2020" not "9/12/2020"

#### Actual Behavior

What behavior did you actually see?
- The date is not formated the French way after clicking on the "Dynamically switch to French" button

#### Environment

- Angular: 11.0.0
- CDK/Material: 11.0.0
- Browser(s): Google chrome Version 88.0.4324.104 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro 20H2 build 19042.746

**Comment by Yanal-Yves** [comment]
The example inside the documentation is behaving differently but is wrong too.

#### STR:
1. Go to https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings
2. Search for "Datepicker with different locale" => you should find the section explaining how to set the local for mat-date-picker
3. On the live example select a date (for instance 2020-12-09 => the formatted date selected in the input is "2020/12/09", I don't know if this is correct or not.
4. Click "Dynamically switch to French" button => the input now shows "9/12/2020" which is wrongly formatted in French (France)

#### Expected behavior:
"09/12/2020" (Dates are padded with 0. We write "09/12/2020" not "9/12/2020")

#### Environment:
Angular: 11.0.0
CDK/Material: 11.0.0
Browser(s): Google chrome Version 88.0.4324.104 (Official Build) (64-bit)
Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro 20H2 build 19042.746

I think that to be completed, we should :
1. Make sure the live example and the associated StackBlitz behave the same.
2. Fix and explain how we are supposed to format dates the right way in different locales. I am having a hard time to make the Datepicker behave as expected by French people.

I am sorry, I don't know how to fix this bug and I don't understand how the [MAT_MOMENT_DATE_FORMATS](https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/moment-date-formats.ts) could be the same for all languages. I was expecting to have one MAT_MOMENT_DATE_FORMATS value per locale.

**Comment by crisbeto** [comment]
This seems to be an issue with the demo on Stackblitz specifically, because the same code works locally. Also note how the calendar isn't in Japanese initially. As for padded vs non-padded dates, this isn't something we determine, we use the data that's built into Moment.js.
