### ISSUE TITLE
CDK DRAG&DROP : Transfer item from on group list to another on click or keyup event (keyup.code ===13)

### ISSUE THREAD

**Issue by Prabin1111** [angular/components#21734]
#### Feature Description
CDK DRAG&DROP with transfer feature on events(mouse, key etc)

#### Use Case
it help to transfer a input filed from one group to another

**Comment by crisbeto** [comment]
Using the keyboard isn't really drag and drop anymore. You can implement this yourself already by binding a `keydown` event.
