### ISSUE TITLE
bug(cdk/drag-drop): Cannot drag without scrolling on mobile devices.

### ISSUE THREAD

**Issue by shervin01** [angular/components#21749]
This change (https://github.com/angular/components/pull/21227) has broken dragging on mobile devices. On mobile dragging will also trigger scroll. To reproduce go here on a mobile device or use chrome's toggle device tool bar: https://material.angular.io/cdk/drag-drop/examples 

#### Reproduction

Steps to reproduce:
1. go here on a mobile device or use chrome's toggle device tool bar: https://material.angular.io/cdk/drag-drop/examples 
2. then scroll down a bit.
3. then try to drag one of the boxes. You can see that screen also scrolls.
 
 
#### Expected Behavior

Screen should not scroll while dragging. You can see the desired behavior here: https://v10.material.angular.io/cdk/drag-drop/examples

#### Actual Behavior

Screen/Document scrolls while dragging

#### Environment

- Angular: 11.1.1
- CDK/Material: 11.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Tested on Android as well as Desktop chrome with toggle device set to iPhoneX

**Comment by crisbeto** [comment]
It's unlikely that #21227 introduced it since `stopPropagation` doesn't have an effect over whether scroll events. This likely happened in #21382 which accidentally made it so scrolling only gets blocked on the second `touchmove` event. I've submitted #21752 which should resolve it.

**Comment by shervin01** [comment]
@crisbeto Yes you are correct. Thanks for looking into this.
