### ISSUE TITLE
bug(MatDialogHarness ): tests from the docs fail

### ISSUE THREAD

**Issue by AlexElin** [angular/components#21758]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Harnesses: https://stackblitz.com/angular/xokkndljdpx?file=src%2Fapp%2Fdialog-harness-example.ts

##### Steps to reproduce:
1. Open a link to StackBlitz from the [docs](https://material.angular.io/components/dialog/examples)
 
 
#### Expected Behavior

There're no failed tests

#### Actual Behavior

Jasmine report shows all (4) tests failed 
![material](https://user-images.githubusercontent.com/13061803/106365399-69462f80-6346-11eb-9971-052a86abf2e6.jpg)

#### Environment

- Angular: 11.0.0
- CDK/Material: 11.0.0
- Browser(s):

- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
#21759 will fix the example. In order to get it working for yourself, you have to change line 30 from:

```
loader = TestbedHarnessEnvironment.loader(fixture);
```

To the following:

```
loader = TestbedHarnessEnvironment.loader(fixture);
```
