### ISSUE TITLE
feat(MapMarkerClusterer): Add `options` input parameter

### ISSUE THREAD

**Issue by LexLuengas** [angular/components#21763]
#### Feature Description

Several components including GoogleMap and MapMarker have a `options` input parameter that allow to pass a complete options object. The wrapped APIs already support such an options object. The MarkerClusterer constructor is no exception.

For the sake of consistency, MapMarkerClusterer should also expose an `options` input.

#### Use Case

Currently:

```
<map-marker-clusterer
  [gridSize]="markerClustererOptions.gridSize"
  [maxZoom]="markerClustererOptions.maxZoom"
  [zoomOnClick]="markerClustererOptions.zoomOnClick"
  ...
>
  <map-marker
    *ngFor="let markerOptions of markerOptions"
    [options]="markerOptions.options"
  ></map-marker>
</map-marker-clusterer>
```

Instead, it would be more useful:

```
<map-marker-clusterer
  [options]="markerClustererOptions"
>
  <map-marker
    *ngFor="let markerOptions of markerOptions"
    [options]="markerOptions.options"
  ></map-marker>
</map-marker-clusterer>
```

**Comment by crisbeto** [comment]
Sounds reasonable, but should wait on https://github.com/angular/components/pull/21753 which moves some code around in the clusterer.
