### ISSUE TITLE
bug(Scrolling): Scroll Tracking Causes IFrames to Flicker

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#21761]
#### Reproduction

Scroll down in this article until you reach the Gist rendered with an IFrame.

https://developer.fireflysemantics.com/guides/guides--recreating-the-ngrx-demo-app-with-firefly-semantics-slice-state-manager

Notice the flickering.  

It does that due to the scroll tracking needed to show and hide the toolbar.

#### Expected Behavior

Ideally no flickering.

- Angular:
- CDK/Material: 11
- Browser(s): Firefox, Chrome
- Operating System (Ubuntu):

**Comment by crisbeto** [comment]
It seems like something is calling `document.write` on each scroll which is causing everything to re-render. Closing since this appears to be an issue with your own code.
