### ISSUE TITLE
docs-bug(COMPONENT): Bottom Sheet `entryComponents` should not be needed anymore with Angular Ivy

### ISSUE THREAD

**Issue by ahnpnl** [angular/components#21764]
#### Documentation Feedback

With Angular Ivy, it should not be needed anymore to configure dynamic components via `entryComponents`. I think the documentation section https://material.angular.io/components/bottom-sheet/overview#configuring-bottom-sheet-content-via-entrycomponents needs to be adjusted to be only required for Angular non-Ivy.

**Affected documentation page:** https://material.angular.io/components/bottom-sheet/overview#configuring-bottom-sheet-content-via-entrycomponents

**Comment by crisbeto** [comment]
It can't be removed, because we still support apps running ViewEngine. All the `entryComponents` usages will be removed once ViewEngine is removed from Angular.

**Comment by ahnpnl** [comment]
Hmm what I meant is not removing it, but adding additional text to mention that the section should not be needed for Angular Ivy.
