### ISSUE TITLE
bug(Toolbar): Pre element bleed through

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#21760]
#### Reproduction

If you scroll down with this article:

https://developer.fireflysemantics.com/guides/guides--recreating-the-ngrx-demo-app-with-firefly-semantics-slice-state-manager

Notice that the `pre` element bleed through the toolbar.

#### Environment

- Angular: 11
- CDK/Material: 11
- Browser(s): Chrome, Firefox
- Operating System (Ubuntu):

**Comment by crisbeto** [comment]
This is a problem with your setup. You have to set a higher `z-index` on the toolbar.
