### ISSUE TITLE
bug(MatTabGroup): StaticInjectorError thrown when using MatTabGroup with wrapper component

### ISSUE THREAD

**Issue by pec0ra** [angular/components#21770]
#### Reproduction

See this [Stackblitz](https://stackblitz.com/edit/components-issue-mat-tab-group-wrapper?devtoolsheight=33&file=src/app/example-component.html)

Create a component that includes a `MatTabGroup` whose `MatTab` come inside `ng-content`
```html
<mat-tab-group #tabGroup>
     <ng-content></ng-content>
</mat-tab-group>
```
 
#### Expected Behavior

The `MatTabGroup` should not give an error, as it was the case with Angular 10 / Angular Material 10.
See this [stackblitz](https://stackblitz.com/edit/components-issue-mat-tab-group-wrapper-working-with-angular-10?file=package.json) for a working example with Angular 10 / Angular Material 10

#### Actual Behavior

The following error is thrown:
```
Error: StaticInjectorError(AppModule)[MatTab -> InjectionToken MAT_TAB_GROUP]:
StaticInjectorError(Platform: core)[MatTab -> InjectionToken MAT_TAB_GROUP]:
NullInjectorError: No provider for InjectionToken MAT_TAB_GROUP!
```

#### Environment

- Angular: 11.1.1
- CDK/Material: 11.1.1
- Browser(s): Tested in Chrome and Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Tested on macOS and Ubuntu

**Comment by guillaumesp** [comment]
I confirm, I have the same issue !
Someone knows how long it will take to merge the PR and new version will be released ?

**Comment by Brutusn** [comment]
I 'fixed' the issue by providing the MAT_TAB_GROUP token in the wrapper component:

```
providers: [
	{
		provide: MAT_TAB_GROUP,
		useValue: undefined,
	},
],
```

**Comment by matpinsdorf** [comment]
I have the same issue !

**Comment by tgudroe** [comment]
Same issue.

**Comment by dokolyski** [comment]
Same

**Comment by scaki** [comment]
I have the same problem, when does pr go live?

**Comment by Roseidon** [comment]
Will this fix also be applied to older versions of Angular Material? So far I only see it in version 12.x, but not 11.x

**Comment by crisbeto** [comment]
It won't. We usually only backport fixes to older version if they're for a serious issue.

**Comment by Roseidon** [comment]
Is there a possibility to add it myself via a Pull-Request to 11.2.x? :D

**Comment by crisbeto** [comment]
Merging the fix itself isn't that difficult, but releasing the changes and updating the docs takes a while.
