### ISSUE TITLE
bug(mat-grid-list): Remove <figure> element from inside mat-grid-tile

### ISSUE THREAD

**Issue by gogitter7** [angular/components#21775]
#### Reproduction

When using the mat-grid-tile element, Angular inserts a "figure" tag on page render. This can cause confusion for screen readers reading aloud the "figure" tag before reading the content inside the tile.
 
 
#### Expected Behavior

Content inside the mat-grid-tile should render as the programmer enters it, rather than inserting a "figure" tag. (If the programmer wishes to surround the content in a figure, they can enter that themselves).

#### Actual Behavior

The mat-grid-tile component renders a "figure" tag around the ng-content inserted by the programmer, causing unwanted behavior with screen readers.

#### Environment

- Angular: 9
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by christianruest** [comment]
hey all, i've come accross this issue, as i am facing some problems with the figure element and I saw that the PR was opened and already approved quite some time back, so I wanted to ask about the usual turn-around time of such issue. So by when would you approximately merge the pr?
