### ISSUE TITLE
[Paginator] Please add hidePageRangeActions property for mat-paginator just like hidePageSize

### ISSUE THREAD

**Issue by ErVishalM** [angular/components#21789]
#### Feature Description

Hi, I was using mat-paginator and I wanted to give a feature request. I do not want range action div in paginator.
So can we add a property in mat paginator named as `@Input() hideRangeActions: boolean` just like `@Input() hidePageSize: boolean`
![image](https://user-images.githubusercontent.com/43669644/106751374-196dae00-664f-11eb-9708-401e7d02d727.png)

#### Use Case

If I have set the property hideRangeActions = "true" then below div will hide and only page size div will be coming
![image](https://user-images.githubusercontent.com/43669644/106751719-99941380-664f-11eb-8c58-8fec639c0cfc.png)

#### Validation
If I am using `mat-paginator` then **only one of the input property can be true not both** `hideRangeActions = "true" or hidePageSize = "true"`

**Comment by crisbeto** [comment]
It wouldn't be much of a paginator if the actions were hidden since the user won't have the ability to change the page.

**Comment by ErVishalM** [comment]
@crisbeto User can change the page size which will show the number of results according to items per page drop-down selected value. So one of the property should be false as I wrote validation above.

**Comment by jelbourn** [comment]
I don't think we would add an option for this since I think it's somewhat of an edge case to not want to support actually changing pages. It may make sense to swap this out for a custom component. You could also use `display: none` on that part of the control, but this is brittle since the DOM structure of the component could change over time.
