### ISSUE TITLE
bug(MatChip): Long text content overflows chip container

### ISSUE THREAD

**Issue by mcalmus** [angular/components#21784]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

https://components-issue-ebvvs5.stackblitz.io

Steps to reproduce:
1. Create a chip with a very long text string
 
#### Expected Behavior

What behavior were you expecting to see?
Chip text is truncated with an ellipses, allowed to grow fatter, or something similar

#### Actual Behavior

What behavior did you actually see?
Text overflows chip container.

#### Environment

- Angular: 11.1
- CDK/Material: 11.1
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by jelbourn** [comment]
I don't see us every doing anything like this directly in the library. From Material Design's point of view, chips are generally meant to be relatively short. Any kind of truncation/ellipses application also has localization concerns (e.g, you wouldn't want to truncate a longer word to an inappropriate word), so this kind of behavior is better off left to the application.
