### ISSUE TITLE
help(mat-date-range-picker): How i can access the "isComplete()" method of range picker?

### ISSUE THREAD

**Issue by veronesecoms** [angular/components#21795]
#### What are you trying to do?
I'm trying to access the method "isComplete()" of range-picker in my template

What are you trying to do?
```
<div *ngIf="!picker.isComplete()">
    You should select the range date
</div>
<mat-date-range-picker
   #picker
 ></mat-date-range-picker>
```

What are you seeing that does not match your expectations? 
I'm facing this error: `' error TS2339: Property 'isComplete' does not exist on type 'MatDateRangePicker<any>'.`

#### Environment

- Angular:
    "@angular/core": "~10.0.14",
- CDK/Material:
    "@angular/material": "^10.1.3",

**Comment by jelbourn** [comment]
This is an API on the selection model rather than the component itself. 
https://material.angular.io/components/datepicker/api#MatDateSelectionModel
