### ISSUE TITLE
bug(Datepicker): Top left calender button has unclear purpose

### ISSUE THREAD

**Issue by StudioSpindle** [angular/components#21792]
Using the DatePicker for [selected years and months](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months). Typically I guess the user wants to use the month and year, and never the day. 

So by using the startView property to `multi-year` you will see the month and year in the select field:

![Screenshot 2021-02-03 at 17 57 28](https://user-images.githubusercontent.com/9882035/106781442-5b93f100-6649-11eb-83ca-58c9ca91fe6e.png)

Once you click on the icon the pop-up opens you are able to change the date.

**Current outcome:**

Here comes the bug. When you click on the button on the left top:

![Screenshot 2021-02-03 at 17 59 25](https://user-images.githubusercontent.com/9882035/106781879-d5c47580-6649-11eb-940d-f11b0282bc7b.png)

You will be able to select a day:

![Screenshot 2021-02-03 at 18 00 37](https://user-images.githubusercontent.com/9882035/106781940-e8d74580-6649-11eb-95ca-f5f74f80f5c3.png)

Why would you want to enable the user to select a day in a month and year calendar?

**Expected outcome:**

I was expecting instead that you would see the month that was selected. And if you'd click on it you would be sent to that year showing all the months. 

When setting the startView to year the button entirely does not need to be there. Or am I misinterpreting this whole thing?

**Comment by StudioSpindle** [comment]
Since you can use the arrow keys you can disable the calendar control button for the `year` view:

```
::ng-deep .date-picker .mat-calendar-period-button { display: none; }
```

But for the month/year datepicker this won't be a good solution since you'd like to be able to switch between the month and year view.

**Comment by jelbourn** [comment]
Right now this is working as designed, at least. We don't officially support only month/year selection; the `startView` property only controls which view is the first thing rendered, but users can always go back to the individual day selection. 

The feature to only have month/year selection is tracked in #14202

**Comment by jmoliveras** [comment]
This worked for me:

https://stackblitz.com/edit/angular-z2zfjx-rwkbsd?file=app%2Fdatepicker-custom-header-example.ts

Just change line 91 from 
this.calendar.currentView == "month" ? "multi-year" : "month";
 to 
this.calendar.currentView == "year" ? "multi-year" : "year";

**Comment by jmoliveras** [comment]
> Using the DatePicker for [selected years and months](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months). Typically I guess the user wants to use the month and year, and never the day.
> 
> So by using the startView property to `multi-year` you will see the month and year in the select field:
> 
> ![Screenshot 2021-02-03 at 17 57 28](https://user-images.githubusercontent.com/9882035/106781442-5b93f100-6649-11eb-83ca-58c9ca91fe6e.png)
> 
> Once you click on the icon the pop-up opens you are able to change the date.
> 
> **Current outcome:**
> 
> Here comes the bug. When you click on the button on the left top:
> 
> ![Screenshot 2021-02-03 at 17 59 25](https://user-images.githubusercontent.com/9882035/106781879-d5c47580-6649-11eb-940d-f11b0282bc7b.png)
> 
> You will be able to select a day:
> 
> ![Screenshot 2021-02-03 at 18 00 37](https://user-images.githubusercontent.com/9882035/106781940-e8d74580-6649-11eb-95ca-f5f74f80f5c3.png)
> 
> Why would you want to enable the user to select a day in a month and year calendar?
> 
> **Expected outcome:**
> 
> I was expecting instead that you would see the month that was selected. And if you'd click on it you would be sent to that year showing all the months.
> 
> When setting the startView to year the button entirely does not need to be there. Or am I misinterpreting this whole thing?

This worked for me:

https://stackblitz.com/edit/angular-z2zfjx-rwkbsd?file=app%2Fdatepicker-custom-header-example.ts

Just change line 91 from
this.calendar.currentView == "month" ? "multi-year" : "month";
to
this.calendar.currentView == "year" ? "multi-year" : "year";
