### ISSUE TITLE
bug(OverlayContainer): extending OverlayContainer cause build issues in angular 11

### ISSUE THREAD

**Issue by rezres** [angular/components#21802]
#### Reproduction

Steps to reproduce:
1. clone [this](https://github.com/rezres/Overlay-V11)
2. run ng build or serve
 
 
#### Expected Behavior
Expected Build to succeed, this was the case until we updated to angular 11

#### Actual Behavior
Build Error 
The directive MyOverlayService inherits its constructor from OverlayContainer, 
but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of OverlayContainer's constructor. Either add a @Directive decorator to OverlayContainer, or add an explicit constructor to MyOverlayService.

#### Environment
angular/cdk: 11.1.1
angular/common: 11.1.2
angular/compiler:  11.1.2
angular/core: 11.1.2

**Comment by dianmonblan** [comment]
@rezres I don't understand what the problem is.

**Your code**
```javascript
@Directive()
@Injectable()
export class MyOverlayService extends OverlayContainer implements OnDestroy {
  protected _createContainer(): void {
    super._createContainer();
    if (!this._containerElement) {
      return;
    }
    const parent = document.querySelector('.my-selector') || document.body;
    parent.appendChild(this._containerElement);
  }

  ngOnDestroy() {
    super.ngOnDestroy();
    this._containerElement = null;
  }
}
```
Error obtained when doing `ng serve`
`Error: src/app/my-overlay-container.service.ts:6:14 - error NG2006: The directive MyOverlayService inherits its constructor from OverlayContainer, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of OverlayContainer's constructor. Either add a @Directive decorator to OverlayContainer, or add an explicit constructor to MyOverlayService.`

**Solution**
```javascript
import { OverlayContainer } from '@angular/cdk/overlay';
import { Injectable, OnDestroy } from '@angular/core';

@Injectable()
export class MyOverlayService extends OverlayContainer implements OnDestroy {
  protected _createContainer(): void {
    super._createContainer();
    if (!this._containerElement) {
      return;
    }
    const parent = document.querySelector('.my-selector') || document.body;
    parent.appendChild(this._containerElement);
  }

  ngOnDestroy() {
    super.ngOnDestroy();
    this._containerElement = null;
  }
}
```
Running successful platform `ng serve` 

Regards,

**Comment by rezres** [comment]
@dianmonblan 
Thanks a lot, I am sorry to waste your time, I am surprised it used to work just fine before, not sure how was that happening, I only noticed this issue when I updated to Angular 11 and figured there is something wrong.

**Comment by dianmonblan** [comment]
@rezres no problem!

The team should be asked to integrate the [Decorator missing from parent class possibility](https://docs.angular.lat/guide/migration-undecorated-classes#migrating-classes-that-use-di) this must be integrated!

Regards,

**Comment by wagnermaciel** [comment]
Sorry, I don't understand why I was @mentioned on this. Was this an accident?

**Comment by dianmonblan** [comment]
> Sorry, I don't understand why I was @mentioned on this. Was this an accident?

Sorry @wagnermaciel an accident y equivocación.
