### ISSUE TITLE
feat(DASHBOARD): TITLE  Enhance the Schematic to generate widgets with settings and a base class

### ISSUE THREAD

**Issue by weedkiller** [angular/components#21808]
#### Use Case
Hello, this is a request to enhance the Dashboard Schematic Generation.

Since business mostly use dashboards for reporting fragments of information\visuals\charts\tables across the organization and always house that data inside widgets; these widgets always contain _common basic_ plumbing that could be placed in a base class. However, that base is missing, if you could please enhance the Dashboard Schematic _**it would greatly benefit the developer community if a strategy/pattern was used in the dashboard component**_. These reports are data housed inside widgets form of charts, maps, tables etc.  However, in this schematic there is no UI aggregation, or common base settings.

**Dashboard**

- [ ] Typical dashboard is One (or many pages/tabs)
- [ ] Each Dashboard houses widgets/containers
- [ ] Be able to share change strategy with their contained widgets and other tabs
- [ ] DI` @Injectable` Service to accept new or remove old widgets

**Widgets** -

- [ ] Each of the widgets should extend from a base class
- [ ] The widget should share/exchange some common data with other widgets
- [ ] Widgets should have settings (an Icon gear, that can be extend, `Print, Copy, Export, Import, Refresh` etc.)
- [ ] Some lifecycle that allows them to clean up or change within that dashboards context

![image](https://user-images.githubusercontent.com/21086190/106939093-cd257b00-66ed-11eb-877b-39b80cd33f25.png)

Some places have layed out information on this, because it was lacking.
![image](https://user-images.githubusercontent.com/21086190/106939914-e2e77000-66ee-11eb-869a-ddb8fddf659f.png)

**Comment by jelbourn** [comment]
@weedkiller I think something like this would be really useful, but it's probably not something we'd make directly. I think this would be great as a community project. Our schematics are pretty barebones since they're mostly meant to be an example of how to set up / consume the Angular Material components.
