### ISSUE TITLE
bug(DATEPICKER): Datepicker custom format doesn't update HH:mm

### ISSUE THREAD

**Issue by 7amou3** [angular/components#21823]
#### Reproduction

You can find a example here: https://stackblitz.com/edit/angular-nhkztz-4jyvdy?file=src%2Fapp%2Fdatepicker-formats-example.ts

Steps to reproduce:
1. click on the calendar icon next to the input
2. edit the hours or minutes HH:mm 
3. HH:mm resets to default value every time I try to set new one
 
 
#### Expected Behavior

I expect to see the hours/minutes I just typed.

#### Actual Behavior

HH:mm resets to previous value

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Chrome 88.0.4324.146 and Edge 88.0.705.56
- Operating System:  Windows 10

**Comment by crisbeto** [comment]
The component is a datepicker, not a timepicker so we don't have any logic to preserve the hour/minute information.

**Comment by 7amou3** [comment]
is there any workaround?
