### ISSUE TITLE
feat(MatDatepicker): Add pass-through change and click events to MatDatepickerToggle

### ISSUE THREAD

**Issue by mcalmus** [angular/components#21836]
#### Feature Description

MatDatepickerToggle is a button, but it doesn't have a mechanism for apps that include it to know when it has been changed to clicked. This would be a useful feature.

#### Use Case

We do click metrics on the site, but I could see other cases where a developer might want to know when the date picker was opened.

**Comment by mcalmus** [comment]
(click) is not firing for me. Nor is there a click event firing with my @HostListener (not shown).

https://stackblitz.com/edit/components-issue-uosggb?file=src/app/example-component.ts

**Comment by Totati** [comment]
Hi, the event propegetion is stopped, because it would focus the mat-form-field. https://github.com/angular/components/blob/master/src/material/datepicker/datepicker-toggle.ts#L116

**Comment by crisbeto** [comment]
I think that we should remove the `stopPropagation` and find a different way of preventing focus from reaching the form field.

**Comment by mcalmus** [comment]
Not that anyone was asking, but confirmed in 11.2.1.

**Comment by crisbeto** [comment]
Confirmed that it was fixed or confirmed that it's still happening?

**Comment by mcalmus** [comment]
Confirmed as fixed. Sorry.
