### ISSUE TITLE
bug(map-marker): Race condition input / output

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/components#21851]
#### Reproduction
 Order of input/output has an impact on `(mapClick)` ouput:
  This works
 ```html
<map-marker (mapClick)="log()" [position]="position"></map-marker>
 ```

This doesn't trigger "log" method on click
  ```html
<map-marker [position]="position" (mapClick)="log()"></map-marker>
 ```
 
 I haven't test every scenarii but this work: 
 ```html
 <map-marker
  [options]="{ icon: '....' }"
  (mapClick)="log()"
  [position]="position">
</map-marker>
```
So maybe it only apply to the couple `[position]` / `(mapClick)`...
 
#### Expected Behavior
Order of input/ouput shouldn't impact behavior

#### Actual Behavior
Order of input/ouput does impact behavior

#### Environment

Angular CLI: 11.1.2
Node: 12.18.3
OS: win32 x64

Angular: 11.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

**Comment by crisbeto** [comment]
I tried it out based on the provided info and both snippets worked for me. Have you tried to isolate it further to rule out any issues from your app? For reference, here's what I have:

```
<google-map height="400px" width="750px" [center]="center">
  <map-marker [position]="center" (mapClick)="log()"></map-marker>
</google-map>
```

Where `center = {lat: 24, lng: 12};`.

**Comment by GrandSchtroumpf** [comment]
I tried to reproduce after a fresh reboot this morning, and everything was working correctly. I'm very sorry for disturbing...
