### ISSUE TITLE
Getting Error: 'mat-date-range-picker-actions' is not a known element 

### ISSUE THREAD

**Issue by vinitsingh64** [angular/components#21862]
#### Documentation Feedback

I want to add action buttons in my material date range picker. So i added this code given in documentation on link below

`<mat-date-range-picker #picker [touchUi]="true">
        <mat-date-range-picker-actions>
          <button mat-button matDateRangePickerCancel>Cancel</button>
          <button mat-raised-button color="primary" matDateRangePickerApply>
            Apply
          </button>
        </mat-date-range-picker-actions>
      </mat-date-range-picker>`

But when i run application i am getting error: `'mat-date-range-picker-actions' is not a known element `

I have also imported ` MatDatepickerModule` and  `MatNativeDateModule` still getting this error. Without action buttons it is working fine,

**Affected documentation page:** Insert a link to the affected page on material.angular.io
[Date picker actions](https://material.angular.io/components/datepicker/overview#confirmation-action-buttons)

**Comment by crisbeto** [comment]
What version of Material are you running? The action buttons were added in 11.1.0.

**Comment by vinitsingh64** [comment]
> What version of Material are you running? The action buttons were added in 11.1.0.

Ohh. ok.. i am using `^10.2.2`. Thanks for heads up.. I will update Material version and check again.

**Comment by vinitsingh64** [comment]
Thanks It worked after updating angular material version.
