### ISSUE TITLE
feat(COMPONENT): Make DataSource<T> an interface

### ISSUE THREAD

**Issue by s4m0r4m4** [angular/components#21887]
#### Feature Description
Instead of an entirely abstract class (see https://github.com/angular/components/blob/master/src/cdk/collections/data-source.ts), why not make it an interface? 

#### Use Case
This would enable users such as myself to create custom data sources that extend _other_ classes. With DataSource<T> being an abstract class, it means I have to extend that to make a custom DataSource and therefore cannot extend any other class with my custom DataSource. My use case is that i have a logging base class, and want to extend it in a new class to also act as a custom Data Source.

**Comment by crisbeto** [comment]
Changing it at this point would be breaking. For what it's worth, TypeScript allows you to implement classes as well. E.g. you should be able to do `MyDataSource implements DataSource`.

**Comment by s4m0r4m4** [comment]
Thanks for the lightning-fast response! Yeah I get that it's a breaking change, maybe not worth it at this point in time. Perhaps just for consideration if you guys ever revamp Table Datasources.

Thanks for the tip about implementing the DataSource instead of extending it, that worked just fine for me. That tidbit could be helpful for addition to the docs, what do you think? I'd be happy to submit a quick PR for the docs update.

**Comment by crisbeto** [comment]
Sure, feel free to send out a PR and I can review it.
