### ISSUE TITLE
bug(Mat-tab-link): Not working using routerLinkActive directive

### ISSUE THREAD

**Issue by mackelito** [angular/components#21882]
#### Reproduction

This is the current router setup and it works fine.
this is a lazy loaded module under the path `search`

so the url's become as follows...
`search/all`
`search/web`
`search/guides`
`search/user`
`search/books`

```
const routes: Routes = [
  {
    path: '',
    component: GlobalSearchComponent,
    children: [
      {
        path: '',
        redirectTo: 'all'
      },
      { path: 'all', component: AllComponent },
      { path: 'web', component: WebComponent },
      { path: 'guides', component: GuidesComponent },
      { path: 'users', component: UsersComponent },
      { path: 'books', component: BooksComponent }
    ]
  }
];
```

Now I got a request to get rid of ´/all´ and just have the url as `search` so I changed it into this:
```
const routes: Routes = [
  {
    path: '',
    component: GlobalSearchComponent,
    children: [
      {
        path: '',
        // redirectTo: 'all' <--- removed
        component: AllComponent
        // pathMatch: 'full' <--- removing this does nothing..
      },
      //{ path: 'all', component: AllComponent },
      { path: 'web', component: WebComponent },
      { path: 'guides', component: GuidesComponent },
      { path: 'users', component: UsersComponent },
      { path: 'books', component: BooksComponent }
    ]
  }
];
```

and it works... except that the routerLinkActive directive is not working as I expect it to..

```
  <a
    *ngFor="let link of links"
    routerLinkActive
    #rla="routerLinkActive"
    [routerLink]="[link.url]"
    [queryParams]="{ query: urlQueryParameter }"
    [active]="rla.isActive"
    >{{ link.title }}
  </a>
```
`[active]="rla.isActive"` is not working?
 
#### Expected Behavior

As in the first setup the tab should have a underline marking it as selected/active

#### Actual Behavior

It get's focus but the "border" is not moved to active tab

#### Environment
- Angular: 9.2.4
- CDK/Material: 9.2.4

**Comment by crisbeto** [comment]
Closing since this issue since the `active` binding's implementation is fairly simple: whichever tab is has it set to `true` will become highlighted. This is an issue with the value which is supplied to `active` binding, either by `RouterLinkActive` or your app.

**Comment by mackelito** [comment]
Yeah my bad.. I found the problem and forgot to close this ticket...
I just needed to use `[routerLinkActiveOptions]="{ exact: true }"` :)
