### ISSUE TITLE
Accessibility Bug: Name, role and tooltip is not defined for the "Next/Previous" mat-tab-header-pagination

### ISSUE THREAD

**Issue by swatisahay** [angular/components#21889]
If After resizing at 200% "Next/Previous" control does not have the name, role and title defined,  so it would be difficult for users to complete their tasks and use this control.

Actual Result:
Name, role and tooltip is not defined for the "Next/Previous" control which appears at 200% screen resize.

Expected Result:
Name, role and tooltip should be properly defined for the "Next/Previous" control which appears at 200% screen resize

![image](https://user-images.githubusercontent.com/39397953/107827266-47cc4700-6d3b-11eb-9cc1-682ed6d3e9b7.png)

**Comment by crisbeto** [comment]
The next/previous buttons only change the scroll position of the header which screen reader users won't be able to see, hence why the buttons are `aria-hidden`. Tabs are navigated using the keyboard arrow keys.

**Comment by crisbeto** [comment]
Closing since this is working as expected.
