### ISSUE TITLE
feat(elevation): Elevation to support negative values to show box-shadow up oriented

### ISSUE THREAD

**Issue by alejandrocoding** [angular/components#21904]
#### Feature Description

Elevation helper only supports values between 0 and 24, and with those values the box shadow shows below.

I see the value of supporting negative values too (-24 to 24) where the negative values apply the same logic/style but above the component. Changing the box-shadow Y offset of the already provided values is working fine.

#### Use Case

Tabs component supports headerPosition whether is above|below (https://material.angular.io/components/tabs/api#MatTabHeaderPosition)

So If I want to build a top tab navigation menu and I want to have elevation working on top with the `headerPosition="below"` I can have a good looking component as here:

<img width="903" alt="Captura de pantalla 2021-02-14 a las 19 58 00" src="https://user-images.githubusercontent.com/5755545/107886444-249ec480-6f00-11eb-984b-0bdd0d9702be.png">

The only _problem_ is that elevation does not support the shadow on top but rather only on bottom.

### Usage Proposal

For using  the mat-elevation mix, it would be:
```
@import '~@angular/material/theming';

mat-tab-group {
  @include mat-elevation(-8);
}
```

For using the class selector, it would be:
```
<mat-tab-group class="mat-elevation-z-8">....</mat-tab-group>
```

The values for the negative elevations would be the same as for the positive but just adding a negative mark (-) for the Y offset, so no changes in terms of design/elevation/values are being suggested here.

I already know where to make the changes in the source code, but instead of pushing a PR, I thought it was worth to first suggest the change here and see if you agree or see the point of this feature.

_Note: I can work-around this just using plain css, but I think the elevation helper is very clean and powerful and it would be great if it would support this use case too, imo._

**Comment by crisbeto** [comment]
The mentioned use case makes sense, but the Material design spec doesn't talk about negative elevations https://material.io/design/environment/elevation.html#default-elevations. Even the term "elevation" doesn't really make sense to me for something negative.

**Comment by alejandrocoding** [comment]
Hi @crisbeto thanks for replying and sharing feedback.

I think we see the point/benefit of what's been suggested, if the problem is about the negative semantic meaning under "elevation" context, there might be another approach that sounds/read better than the one mentioned?

mat-elevation-reverse?
...

or do you think that the cost of the syntax is too big to afford so discarding this feature?

**Comment by BH4NG** [comment]
mat-excavate-z would seem the most logical to me.
+1 on the feature request

**Comment by jelbourn** [comment]
Looking at this, I don't think this is a feature we would move forward with. We're working towards basing Angular Material on top of MDC Web, and their elevation system also only captures the common case of the "light source" being on the top left of the screen: https://material.io/develop/web/supporting/elevation

The state of elevation may change over time with the evolution of the Material Design spec, but I don't see us expanding the elevation API with the current iteration of the spec.
