### ISSUE TITLE
bug(mat-accordion): mat-accordion styles break 'position: sticky;' functionality

### ISSUE THREAD

**Issue by trevorhreed** [angular/components#21914]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-2larmt?file=src/app/app.component.ts

Steps to reproduce:
1. Scroll
 
 
#### Expected Behavior

While scrolling, the yellow toolbar on the left in the example above (which has `position: sticky;` set in the CSS) should 'stick' on-screen until the entire `<section>` element (it's parent element) has scrolled out of view. I've provided a second example on the right which uses a work around (`mat-accordion.workaround * { overflow: unset }`) to make it behave properly, but I'm guessing that workaround will break the behavior of the `<mat-accordion>` component at least in edge cases.

#### Actual Behavior

The yellow toolbar does not stick at all. The behavior of `position: sticky;` is entirely broken by the `<mat-accordion>` component's use of the `overflow` property.

#### Environment

- Angular: 11.2.0
- CDK/Material: 11.2.0
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
The accordion really isn't meant to do this so whatever styles you're adding on top are at your own risk. We can't remove the `overflow: hidden`, because it would mess up the animation. Here's a slowed down example:

![demo](https://user-images.githubusercontent.com/4450522/108736059-84fdb980-7531-11eb-8afa-42a234ec3b2b.gif)

**Comment by trevorhreed** [comment]
Would it be possible to include the `overflow: hidden` styles only during animation? I'd do this myself, but the `mat-expansion-panel` doesn't receive the `ng-animating` class, only the `mat-expansion-panel-content` element. Even with no other changes, adding `ng-animating` to the `mat-expansion-panel` element would allow me to override the necessary styles on my own.

**Comment by trevorhreed** [comment]
**Workaround**

```scss
  mat-expansion-panel{
    overflow: unset;
    .mat-expansion-panel-content{
      overflow: unset;
      &.ng-animating{
        overflow: hidden;
      }
    }
  }
```

I am unable to find an edge case where this workaround breaks the functionality.
