### ISSUE TITLE
bug(INPUT): IOS user agent styles overwrite component styles for disabled input

### ISSUE THREAD

**Issue by annahansen** [angular/components#21918]
#### Reproduction

Steps to reproduce:
1. open your form with disabled inputs in your windows browser (chrome)
2. open your form with disabled inputs on your iphone browser
 
 
#### Expected Behavior
styles of disabled inputs should be the same on both devices

#### Actual Behavior
styles between devices are different caused by user agent styles applied by ios browser

**Comment by crisbeto** [comment]
Can you post a screenshot of it breaking? I just tried it out against an iOS 13 device and it looked as expected.

**Comment by crisbeto** [comment]
Closing since I wasn't able to reproduce it and there hasn't been any new information in a few months.
