### ISSUE TITLE
bug(matDatepickerFilter): No date clickable if matDatepickerFilter is set with ".bind(this)"

### ISSUE THREAD

**Issue by felixfiskare** [angular/components#21929]
Inside my matDatepickerFilter I need to access the component. Till Angular 9 it worked to set `bind(this)` on the filter Function.
Unfortunately this doesn't work no longer. Whenever I define a matDatepickerFilter in a template like this  `[matDatepickerFilter]="valiDateStart.bind(this)"` I can't click on a month on the corresponding matDatePicker.
Once I remove the `bind(this)` the datePicker works again.

#### Reproduction

https://stackblitz.com/edit/components-issue-5tpaxb?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Click on second calender Icon
2. Click a month on the opening popup
 
 
#### Expected Behavior
I would expect to see the month view for the clicked month

#### Actual Behavior
No reaction. The month selection view is still shown

#### Environment

- Angular: Had the problem with Angular 10 and 11
- CDK/Material: 10 & 11 as well
- Browser(s): Current Firefox, Current Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Currently using Fedora, haven't checked another OS yet

**Comment by crisbeto** [comment]
Calling `bind` like this in the view causes change detection to run continuously since it returns a new function instance on each detection run. You should declare your bound function ahead of time like this: https://stackblitz.com/edit/components-issue-gpyqth?file=src%2Fapp%2Fexample-component.html

**Comment by felixfiskare** [comment]
Awesome! Thank you so much!

**Comment by pionas** [comment]
Hi,

i have a problem similar to you but i need add two arguments.
`[matDatepickerFilter]="myFilter.bind(this, i, ii)"`
how can i do it?

**Comment by pionas** [comment]
@crisbeto https://stackblitz.com/edit/components-issue-cjthe5?file=src%2Fapp%2Fexample-component.html this not working

**Comment by crisbeto** [comment]
See the example above. You need to move your `bind` call into a property, otherwise you're triggering infinite change detection.

**Comment by pionas** [comment]
@crisbeto but how? i have got a list of datepicker and everyone has custom own configuration and i need to know index of loop
