### ISSUE TITLE
docs-bug(custom form field control): documet usage ngAcceptInputType_disabled/required

### ISSUE THREAD

**Issue by AlexElin** [angular/components#21920]
#### Documentation Feedback
In the [Stakblitz example](https://stackblitz.com/angular/bqqnammjylr?file=src%2Fapp%2Fform-field-custom-control-example.ts) you use

```
  static ngAcceptInputType_disabled: BooleanInput;
  static ngAcceptInputType_required: BooleanInput;
```

But in the [doc text](https://material.angular.io/guide/creating-a-custom-form-field-control) there're no mentions regarding these fields.

I think there's sense to document _why_ these fields are used.

**Affected documentation page:** https://material.angular.io/guide/creating-a-custom-form-field-control

**Comment by jelbourn** [comment]
This is an Angular feature: https://angular.io/guide/template-typecheck#input-setter-coercion
