### ISSUE TITLE
bug(Material Icon): Registering custom SVG icon with MatIconRegistry throw error in Angular 11.2

### ISSUE THREAD

**Issue by avlyn92** [angular/components#21938]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-icon-issue

Steps to reproduce:
1. register custom SVG icon with MatIconRegistry, and as well using DomSanitizer for safeUrl (follow code snippet from https://material.angular.io/components/icon/examples under SVG icons)
2. run in localhost:4200 
 
 
#### Expected Behavior

What behavior were you expecting to see?

- All SVG Icons registered into matIconRegistry should be populated on the view

#### Actual Behavior

- While some SVG Icons able to be displayed on the view (browser), some of them are instead throwing error: Error retrieving icon :chevron-right! Unable to find icon with the name ":chevron-right"

#### Environment

- Angular: 11.2.1
- CDK/Material: 11.2.1
- Browser(s): Chrome, Firefox, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This appears to be working as intended. Your StackBlitz registers the icons in `ngOnInit`, which is too late. `ngOnInit` occurs _after_ change detection has run, so by that time the icons would have already tried to render. You should be able to register icons in the constructor or an `NgModule` or `Component`
