### ISSUE TITLE
bug(MatRadioButton, MatCheckbox): Visual checked indicators are not visible when high contrast mode is enabled

### ISSUE THREAD

**Issue by byanofsky** [angular/components#21936]
#### Reproduction

Steps to reproduce:
1. In Firefox, [disable High Contrast Mode](https://support.mozilla.org/en-US/kb/disable-high-contrast-mode-firefox) (specifically, set the color override option to "Never", which overrides the high contrast mode set by Windows)
2. Visit: https://stackblitz.com/edit/components-issue-ysgjhh. 2 radio buttons and 2 checkboxes will be rendered. One of the radio buttons is checked and one of the checkboxes is checked.
3. Note the visual indicators of the checked radio button and checkbox are visible
4. Set the Firefox [color override option](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_custom-font-color) to "Always". (Enabling the OS's high contrast mode is not necessary for repro. However, if you wish to enable: On Windows, [enable "High Contrast Mode"](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_custom-font-color). On Mac, you can [invert colors](https://support.apple.com/et-ee/guide/mac-help/unac089/mac) to emulate Windows high contrast mode.)
5. Note the visual indicators of the checked radio button and checkbox are no longer visible

**IMPORTANT:** If you refresh the page after enabling the color override, the visual indicators will be visible.
 
#### Expected Behavior
After enabling the color override, the visual indicators of checked radio button and checkbox should be visible.

#### Actual Behavior
After enabling the color override, the visual indicators of the checked radio button and checkbox are **NOT** visible.

#### Environment

- Angular: 1.11.0
- CDK/Material: 11.1.1
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows & macOS

**Comment by byanofsky** [comment]
#### Additional notes regarding my investigation:

* The checkbox and radio buttons indicators rely on background colors. It appears that Firefox overrides these background colors, which is why the indicators are not visible.
* The [HighContrastModeDetector](https://github.com/angular/components/blob/master/src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts) adds the necessary classes to the document body so that the high contrast CSS is applied to radio buttons and checkboxes. However, the method `_applyBodyHighContrastModeCssClasses` is only fired when the injectable is constructed. Therefore, if a user enables high contrast mode AFTER a page is loaded, the necessary CSS is not applied because the required classes have not been added to the document body.
* I was unable to uncover a mechanism to observe a change in high contrast mode state. 

#### Possible Solution
In the repro StackBlitz, I've added some CSS in [`example-component.css`](https://stackblitz.com/edit/components-issue-ysgjhh?file=src%2Fapp%2Fexample-component.css) that partially fixes this issue by adding a pseudo element with a thick enough border (specifically, a border width that is half the width of the indicator element). The border color is set to an rgba value whose alpha value is 0. Therefore, when not in high contrast mode, the border is not visible. But when high contrast mode is enabled, the border mimics the styling of the background color.

Note: the CSS conflicts with the existing high contrast mode CSS. Therefore, if high contrast mode is enabled AND THEN the page is loaded, you'll see two indicators in the radio button. If my test CSS works, perhaps it can replace the existing high contrast CSS (I observed a positioning issue with the existing high contrast CSS applied to radio buttons).

**Comment by crisbeto** [comment]
As you mentioned, the high contrast styling depends on the `HighContrastModeDetector` which only runs on app initialization. I don't know whether we can do anything about it, because the browser doesn't expose a method of responding to changes in the high contrast mode. The alternative would be to poll for changes, but that'll be inefficient since the detection depends on `getComputedStyle`.

**Comment by byanofsky** [comment]
@crisbeto what are your thoughts with my approach demoed here: https://stackblitz.com/edit/fix-radio-checkbox-high-contrast?file=src/app/example-component.css (note: I was just hacking around with the CSS. It isn't production ready, but demos the general approach).

This approach allows specifying colors for high contrast mode without relying upon the classes added by the `HighContrastModeDetector`. Bonus: it also fixes an issue with the positioning of the radio button checked indicator.

I'm planning to raise a PR with a similar implementation. But I could see the argument that my approach is over-engineering for an edge case.

**Comment by crisbeto** [comment]
I think that your example would work for this one specific case, but applying it to the entire library will be tricky and doing a one-off is inconsistent. If this is a problem for you, we have support for strong focus indicators which do something similar. You can check out how the strong focus indicators work on our dev app.

**Comment by jelbourn** [comment]
I'm going to close this since I believe it is infeasible for us to detect when high-contrast mode changes after the page has already rendered.
