### ISSUE TITLE
help(<Google-map>): How do I access the instance of the map object in my typescript?

### ISSUE THREAD

**Issue by MatthewHightech** [angular/components#21939]
#### What are you trying to do?

I am trying to use the instance of my map for a `service = new google.maps.places.PlacesService(map);` so I can use `service.findPlaceFromQuery` 
I'm not sure how I can access my map object since I never initialized a `map = new google.maps.Map()` 

#### What troubleshooting steps have you tried?

 I've looked through the documentation and can seem to find how I can access an instance of the map object in my typescript since I never initialized a `map = new google.maps.Map()` 

What are you seeing that does not match your expectations? 

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
- Components: https://stackblitz.com/fork/components-issue 
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. This is not an issue that you would need to reproduce to help me find the answer.
2. 
  
#### Environment

- Angular: 11
- CDK/Material:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by ilmalte** [comment]
Hi Matthew, 

If you already have a google-map component in your HTML you should be able to access it by using an Angular property decorator called [ViewChild](https://angular.io/api/core/ViewChild)

As you can see from the [google-map.ts source code](https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.ts) the component is exported as "googleMap".

You can retrive the component instance by defining an id in the HTML (that I called myMap in my snippet). I really hope this could be helpful and solve your problem!

```
// google-maps-demo.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'google-map-demo',
  templateUrl: 'google-map-demo.html',
})
export class GoogleMapDemo {
  @ViewChild('myMap') map: GoogleMap;
  center: google.maps.LatLngLiteral = {lat: 24, lng: 12};
  zoom = 4;

  moveMap(event: google.maps.MapMouseEvent) {
    this.center = (event.latLng.toJSON());
  }

  move(event: google.maps.MapMouseEvent) {
    this.display = event.latLng.toJSON();
  }
}
```

```
<!-- google-maps-demo.component.html -->
<google-map #myMap="googleMap"
	    height="400px"
            width="750px"
            [center]="center"
            [zoom]="zoom"
            (mapClick)="moveMap($event)"
            (mapMousemove)="move($event)"
            >
</google-map>

<div>Latitude: {{display?.lat}}</div>
<div>Longitude: {{display?.lng}}</div>
```

**Comment by MatthewHightech** [comment]
Awesome! Thanks so much for the help. It took a minute to figure it out since I was still passing 
`map` into `const service = new google.maps.places.PlacesService(map);`

where the **correct** param for `PlacesService()` is `map.googleMap`

The final solution I found was

map.component.ts

    import { Component, OnInit, ViewChild } from '@angular/core';
    import { GoogleMap } from '@angular/google-maps';
    @Component({
      selector: 'app-map',
      templateUrl: './map.component.html',
      styleUrls: ['./map.component.scss'],
    })
    
    export class MapComponent implements OnInit {
        @ViewChild('myMap') map: GoogleMap;
        
        constructor() {}
        
        ngOnInit() {}
        
        someFunction() {
            const service = new google.maps.places.PlacesService(this.map.googleMap);
            service.nearbySearch(request, callback(results, status));
        }
    
    }

   

 map.component.html 
    
    <google-map
            #myMap="googleMap"
            height="55vh"
            [zoom]="mapService.zoom"
            [center]="mapService.center"
            [options]="mapService.options">
    </google-map>

Thanks again for the quick response @ilmalte  :)

**Comment by ilmalte** [comment]
You are welcome! 

In these days I’m migrating a work project from agm package to this official Angular package so I’ve faced a problem similar to yours. 

Unfortunately it looks like right now there are still no tutorials or similar and this repo is poorly documented so the only way to figure it out at the moment is to look at the source code!

By the way, I see this as an opportunity to help people and collaborate by writing  tutorials😊

**Comment by MatthewHightech** [comment]
Ahh, yeah, that would explain the confusion I've been having with the documentation I've been finding...I think I keep finding AGM resources that appear to have a different syntax/structure than the newer Google Maps Angular Component. 

I'm actually working on an MVP for an open-source project that utilizes this Angular component so I'd be happy to share it with you when I'm done with the MVP (next few weeks) and maybe even provide it as an example for how to integrate certain Google Map API features with this component (such as Google Places Query, Directions, etc. ) 

Thanks again for your help and hard work on this great tool :) Enjoy the rest of your week!
