### ISSUE TITLE
bug(GeoCoder): GeoCoder service not exported and hence not usable in google-maps.

### ISSUE THREAD

**Issue by ResourceHog** [angular/components#21954]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://github.com/angular/components/blob/master/src/google-maps/map-geocoder/README.md
- Reproduction: https://stackblitz.com/edit/angular-ivy-qgamgh?file=src/app/app.component.ts

Steps to reproduce:
1.  install @angular/google-maps
2.  import GoogleMapsModule into the ngModule.
3. import MapGeocoder from @angular/google-maps
 
 
#### Expected Behavior

Should be able to inject the service into a component constructor

#### Actual Behavior

Compiler is like "what the fuck is this shit get out of here with that nonsense! There ain't no such thing as MapGeocoder in the @angular/google-maps package chump"

#### Environment

- Angular: 10
- CDK/Material:
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Ubuntu(docker)

**Comment by crisbeto** [comment]
It is being exported, but the code hasn't been released yet. https://github.com/angular/components/blob/master/src/google-maps/public-api.ts#L31

**Comment by jelbourn** [comment]
Closing since this is done; the new API will be part of v12

**Comment by ratsey** [comment]
@jelbourn  Opening myself up to get burned for this question, but when will v12 be released? The documentation already references MapGeocoder.

**Comment by hudzenko** [comment]
Why then documentation tells that as a library user I can use MapGeocoder. It is not available - I can not export it

**Comment by crisbeto** [comment]
What documentation are you referring to? The readme on GitHub is from the latest commit on the `master` branch.

**Comment by Exac** [comment]
@hudzenko Try this:

```bash
ng update @angular/cli --next
ng update @angular/material --next
ng update @angular/cdk --next
```

**Comment by nikosred** [comment]
npm i @angular/google-maps@next worked for me!
