### ISSUE TITLE
bug(mat-form-field): mat-form-field inputs not rendering properly when deployed

### ISSUE THREAD

**Issue by RobertWoehr** [angular/components#21973]
#### Reproduction

Steps to reproduce:
1. Add form markup to template file using mat-form-field elements with input elements displaying the 4 different appearances.
2. View app in browser.
 
https://stackblitz.com/edit/angular-ivy-gl3pev

#### Expected Behavior

What behavior were you expecting to see?

I expect the mat-form-fields of the deployed app to render exactly as they do when the app in run locally.

![image](https://user-images.githubusercontent.com/78363807/108604033-681e8600-7379-11eb-84fb-4cebbd09476e.png)

#### Actual Behavior

What behavior did you actually see?

The mat-form-fields render incorrectly on stackblitz:

![image](https://user-images.githubusercontent.com/78363807/108604060-900de980-7379-11eb-9ad2-f6978051fae7.png)

Also render incorrectly when app is hosted in SharePoint Online on a Web Part Page using a Content Editor Web Part:

![image](https://user-images.githubusercontent.com/78363807/108604116-c5b2d280-7379-11eb-98dd-5406e159ad11.png)

Another observation, textarea fields seem to render just fine in mat-form-field elements.

I followed this article to deploy angular apps to SharePoint Online:

https://www.c-sharpcorner.com/article/sharepoint-with-angular/

I'm fairly new to Angular and feel that a dependency was missed or misconfigured during deployment?  Having said that, I merely copied & pasted the code of my simple example app to stackblitz & it doesn't render properly there either.

In SharePoint, sometimes I get a 404 error, but not always:

![image](https://user-images.githubusercontent.com/78363807/108604809-2217f100-737e-11eb-8e69-9b24d87dc295.png)

#### Environment

- Angular: 10.0.14
- CDK/Material: 10.2.7
- Browser(s): Chrome 88.0.4324.182 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

Angular CLI: 10.0.8
Node: 13.12.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.7
@angular/cli                      10.0.8
@angular/material                 10.2.7
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.9
webpack                           4.43.0

**Comment by crisbeto** [comment]
As far as I can tell, it's because you haven't included a theme. There's more information in the theming guide: https://material.angular.io/guide/theming
