### ISSUE TITLE
MatRangeDateSelectionModel should be excluded from public API

### ISSUE THREAD

**Issue by MursalovAltun** [angular/components#21985]
#### Documentation Feedback

Any usage example of injectable service MatRangeDateSelectionModel

**Affected documentation page:** [https://material.angular.io/components/datepicker/examples](https://material.angular.io/components/datepicker/examples)

**Comment by jelbourn** [comment]
@crisbeto is this class mostly used internally?

**Comment by crisbeto** [comment]
Yes, the model is used internally to sync up the value between the various datepicker components. We should mark it as `@docs-private` so that it doesn't show up in the docs.
