### ISSUE TITLE
bug(Table): filteredData of MatTableDataSource is not filled instantly on data change

### ISSUE THREAD

**Issue by o-serhiichyk** [angular/components#21984]
#### Reproduction

Steps to reproduce:
1. Use Material 11.1.0 or above (up to 11.2.1).
2. Create table with *ngIf that checks 'filteredData' property of table's MatTableDataSource.
3. Clear 'data' property of MatTableDataSource.
4. Set some 'data' to MatTableDataSource.
 
https://stackblitz.com/edit/components-issue-rgcbps?file=src/app/example-component.ts
 
#### Expected Behavior

Table is hidden and then displayed again.

#### Actual Behavior

Table is hidden and can not be displayed.

**P.S.** Everything works fine with Material 11.0.4 and below.

#### Environment

- Angular: 11.2.1
- CDK/Material: 11.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by jelbourn** [comment]
I confirmed that `filteredData` is indeed not being updated as I'd expect when `data` is updated in the linked StackBlitz
