### ISSUE TITLE
bug(matInput): Reactive form getter method doesnt work with matInput

### ISSUE THREAD

**Issue by andaqui** [angular/components#21988]
#### Reproduction
https://stackblitz.com/edit/angular-reactive-form-matinput-get

Steps to reproduce:
1. Fill in firstname input
2. Click submit
3. Check the console log
4. `this.formGroup.get['firstname']` cant retrieve the value, it returns `undefined`. (while `this.formGroup.controls['firstname']` can)
 
#### Expected Behavior
The formgoup getter of the reactive form should be able to get the value of firstname.

#### Actual Behavior
The formgroup getter method can not get the value of firstname input when using matInput. It returns `undefined`.

#### Environment
- Angular: 11.0.4
- CDK/Material: 11.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by crisbeto** [comment]
I believe that `get` is a function so you'll have to call it like this: `this.formGroup.get('firstname')`.

**Comment by andaqui** [comment]
yea..of course.. my bad. Closing.
