### ISSUE TITLE
Setting negative input with type="number". MatInputHarness.

### ISSUE THREAD

**Issue by kurtisblaine** [angular/components#22001]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Input with type=number
2. set input of negative value
 
 
#### Expected Behavior

What behavior were you expecting to see?
Negative value being setting in input field

#### Actual Behavior

What behavior did you actually see?
Negative value not being set

#### Environment

- Angular: 11
- CDK/Material: 11.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Can you post what your test looks like? I tried the following which seems to work:

```
fit('', async () => {
  const input = await loader.getHarness(inputHarness.with({selector: '#numberControl'}));
  await input.setValue('-1');
  expect(await input.getValue()).toBe('-1');
});
```

The template looks like this:
```
<mat-form-field>
  <input matNativeControl id="numberControl" type="number">
</mat-form-field>
```
