### ISSUE TITLE
bug(list): radio group inside selection list with misalign after interaction

### ISSUE THREAD

**Issue by andreElrico** [angular/components#22018]
#### Reproduction

https://stackblitz.com/edit/angular-45ybsy-inbrmc

Steps to reproduce: (effect is more severe on chrome for me)
1. change any radio button
2. radio button will misalign vertically

(I know its probably not ment to add radio buttons inside list items)

what is causing this and how can I fix/ workaround this?
 
#### Expected Behavior

Dont misalign

#### Actual Behavior

It will misalign

**Comment by crisbeto** [comment]
This isn't a setup we support since it doesn't make sense from an accessibility standpoint.

**Comment by andreElrico** [comment]
any hint or tipp why that is behaving weirdly?

**Comment by crisbeto** [comment]
It's hard to tell without diving into it, but it seems to be related to the ripple coming from the radio button.
