### ISSUE TITLE
Add click output to clusterer

### ISSUE THREAD

**Issue by maartenvanasperen** [angular/components#22020]
#### What are you trying to do?
I am trying to create a listener on a marker cluster. So I can get all markers from that clicked cluster event.
But It doesn't seem to work with a google maps example and I cant find any documentation about cluster clicks on [https://github.com/angular/components/blob/master/src/google-maps/map-marker-clusterer/README.md](url). 

#### What troubleshooting steps have you tried?
I tried to add a listener to the MapMarkerClusterer, see code below. The listener code is from this example: [https://github.com/googlemaps/js-markerclustererplus/blob/df5fcb3dca33051ad6690093a5ca51e4d5c81de9/examples/events_example.html#L65](url)
I also tried the default (click) from Angular, but I don't get an event. 

#### Current code (not working)

```html
// map.component.html

<map-marker-clusterer (click)="clusterClick()" [zoomOnClick]="false">
            <map-marker #marker="mapMarker" *ngFor="let result of results"
                        [position]="result.position"
                        [options]="markerOptions"
                        (mapClick)="selectMarker(marker, result)"
            >
            </map-marker>
       </map-marker-clusterer>
```

```ts
// map.component.ts

@ViewChild(MapMarkerClusterer, { static: false }) markerClusterer: MarkerClusterer;

for (const markerCluster of this.markerClusterer.getClusters()) {
          google.maps.event.addListener(markerCluster, 'click', c => {
              console.log(c.getMarkers());
          });
 }
```
  
#### Environment
- Angular: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): 

So how can I get a cluster click event to work, so I can get all the markers from that cluster and implement that in my code?

**Comment by crisbeto** [comment]
Looks like the event is called `clusterclick` https://stackoverflow.com/questions/5710568/markerclusterer-on-click-zoom. We should have an `Output` for this on the `MapMarkerClusterer` component.

**Comment by maartenvanasperen** [comment]
@crisbeto thanks for your reply! `clusterclick` is deprecated [https://github.com/googlemaps/js-markerclustererplus/blob/82f1b7026b8458a719d1e59135adda4033cca8cd/src/markerclusterer.ts#L33-L34](url) that is why I used `click`.

And that library is used, as seen here: `https://github.com/angular/components/tree/master/src/google-maps/map-marker-clusterer`

>The MapMarkerClusterer component wraps the MarkerClusterer class from the Google Maps JavaScript MarkerClustererPlus Library.
