### ISSUE TITLE
bug(checkbox): A small dot in the middle of an inactive radio button

### ISSUE THREAD

**Issue by Zjadlbymc0s** [angular/components#22036]
#### Reproduction
Steps to reproduce:
1. https://material.angular.io/components/checkbox/examples
 
#### Expected Behavior

The unselected radio button should be without a small dot in the center.

#### Actual Behavior

![radio button](https://user-images.githubusercontent.com/36198797/109286299-5bd77480-7822-11eb-8525-d59085fec5e1.png)

#### Environment
- Browser: Firefox 86.0 (64 bit)
- Operating System:  Windows 10

**Comment by crisbeto** [comment]
I wasn't able to reproduce it on Firefox 86 and Windows 10. What is your system-level zoom?

**Comment by Zjadlbymc0s** [comment]
125% (recommended)
When I set it to 100% the problem disappeared

**Comment by crisbeto** [comment]
Thanks, I'm able to reproduce it now.
