### ISSUE TITLE
help(prebuilt-themes): sideEffect: false removing prebuilt theme from build

### ISSUE THREAD

**Issue by recunius** [angular/components#22048]
#### What are you trying to do?

What are you trying to do? Include a prebuilt-theme using Webpack v4

#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? In a production build the prebuilt-theme is removed from the output

#### Reproduction

globalStyles.js
```js
import '@angular/material/prebuilt-themes/indigo-pink.css';
```
webpack.config.js
```js
   ...
   mode: 'production',
   rules: [
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      }
   ]
   ...
```

Ways to bypass the tree shaking

1. Update loader rule in webpack.config.js forcing sideEffects to true
```js
   ...
   mode: 'production',
   rules: [
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
        sideEffects: true,
      }
   ]
   ...
```

2. avoid ESM tree shaking
```js
require('@angular/material/prebuilt-themes/indigo-pink.css');
```

If using `ng build` instead of `webpack` there's no issue when including `@angular/material/prebuilt-themes/indigo-pink.css` in angular.json `...architect.build.styles` array, I'm guessing because `ng build` is not honoring the sideEffects field inside of @angular/material's package.json

Should the css files under prebuilt-themes/ be marked as `sideEffect: true`?

#### Environment

- Angular: 10.2.4
- CDK/Material: 10.2.7
- Browser(s): Chrome / Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Fedora

**Comment by crisbeto** [comment]
This is `sideEffects: false` behaving as expected since you technically aren't using any "imports" from that module and Webpack assumes that it's side-effect-free and drops it. You should either include it through the `angular.json` file or potentially use `@import` inside of your Sass.
