### ISSUE TITLE
bug(Autocomplete): panelClosingActions not triggering with filtered options

### ISSUE THREAD

**Issue by Chuli2k** [angular/components#22062]
#### Reproduction

https://stackblitz.com/edit/components-issue-panelclosingactions?file=src/app/example-component.html

Steps to reproduce:
1. Open example
2. Write 'aaa' into input (something that is not on the list)
3. Delete 'aaa'
4. Select an item from the list
 
 
#### Expected Behavior

The panelClosingActions observable should emit something when selecting an option from the list (log to console in example).

#### Actual Behavior

Nothing happens.

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Firefox 86, Chrome 88.0.4324.190
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
It looks like this is the same underlying issue as https://github.com/angular/components/issues/14777. Closing as a duplicate.
