### ISSUE TITLE
Height of material components

### ISSUE THREAD

**Issue by stefann01** [angular/components#22069]
#### Documentation Feedback

What is the proper way to change the height of material components like select, input, button menu, etc.? There is nothing about this in the documentation. Or those the theming provide this functionality? In the theming documentation is writing only about colours and fonts.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by crisbeto** [comment]
I believe that this is covered by https://github.com/angular/components/issues/4597. In short, we don't support it everywhere yet, but we have a lot of components in `material-experimental` that do.
