### ISSUE TITLE
useUtc: true not working with customDateAdapter

### ISSUE THREAD

**Issue by akshaybhat30** [angular/components#22080]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-moment-date-adapter-overriding-h6zeds?file=main.ts

Steps to reproduce:
1. Change your system timezone so that there is a difference of atleast 1 day.
2. Observe the date shown is not the same as provided i.e '2020-11-30T00:00:00Z';
3. Now go to main.js and change the useClass for DateAdapter to MomentDateAdapter.
4. Observe that the date is changed to 11/30/2020;
 
 
#### Expected Behavior

What behavior were you expecting to see?
when we pass useUtc as true while using a custom date adapter it should work as expected.

#### Actual Behavior

What behavior did you actually see?
useUtc does not work when we extend MomentDateAdapter and make a custom one.

#### Environment

- Angular: 7
- CDK/Material: ^7.3.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
`useUtc` is implemented at the date adapter level so it's your responsibility to account for it in your custom adapter. You can see how it is being handled in the existing `MomentDateAdapter`. https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts
