### ISSUE TITLE
bug(tree): tree memory leak in ivy

### ISSUE THREAD

**Issue by rppig42** [angular/components#22094]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Editor: https://stackblitz.com/edit/components-issue-c6s9kr?file=src%2Fapp%2Fexample-component.ts
- Application: https://components-issue-c6s9kr.stackblitz.io/

Steps to reproduce:

**This problem emerges with angular-cli@11/ivy turned on. Stackblitz is using angular-cli@9 with ivy turned off,  to reproduce the issue, you have to test on your local**
1. click the button for like 20 times
2. take a memory heap snapshots
3. search detached in the class filter
 
 
#### Expected Behavior

few detached elements

#### Actual Behavior

many detached elements
![image](https://user-images.githubusercontent.com/48581046/109758305-53b67500-7c26-11eb-86f2-15696890c98a.png)

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by crisbeto** [comment]
I wasn't able to reproduce it against our local dev app running Angular 11 with Ivy enabled. Is the screenshot above from your app or the Stackblitz? Have you tried looking at where the detached DOM nodes are being retained?

**Comment by rppig42** [comment]
It's caused by a Chrome extension I installed, sorry 😳

**Comment by tmtron** [comment]
> It's caused by a Chrome extension I installed, sorry 😳

And which extension was it?

**Comment by rppig42** [comment]
> > It's caused by a Chrome extension I installed, sorry 😳
> 
> And which extension was it?

keysmith https://chrome.google.com/webstore/detail/keysmith/igfbafcgnaemgipnngnppdhilhpmmnoh
