### ISSUE TITLE
help(CDK/drag and drop): How to support drag and drop in up, down, left and right positions

### ISSUE THREAD

**Issue by yiquanchaoren** [angular/components#22113]
#### What are you trying to do?

I'm building a form builder. From the list on the left, you can drag and drop controls to the right and place them at will.

#### What troubleshooting steps have you tried?

I want to achieve the following effect, but I don't know how to do it
![draganddrop](https://user-images.githubusercontent.com/35981627/109918549-1c14ff00-7cf2-11eb-88fb-b810b593c2a7.gif)

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
- Components: https://stackblitz.com/fork/components-issue 
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Drag one of the left control list
2. The drag and drop position cannot be above, below, left or right of an existing control.
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by yiquanchaoren** [comment]
Any idear ? I need your help....................

**Comment by yiquanchaoren** [comment]
？

**Comment by crisbeto** [comment]
This question is better suited for StackOverflow or something similar since this is a bug tracker. As a pointer, you can declare a group of drop lists which are all connected to each other. For the blue indicator you can style the `.cdk-drag-placeholder`.

```
<div cdkDropListGroup>
  <div *ngFor="let group of groups" cdkDropList>
    <div *ngFor="let item of group" cdkDrag></div>
  </div>
</div>
```
