### ISSUE TITLE
Is it possible to shape trianle or anything on your google map?  (Google Map)

### ISSUE THREAD

**Issue by AleksandarMiha** [angular/components#22117]
#### Feature Description

Is it possible to make a shape on your google map?
If possible, can you show me an example of that?

#### Use Case

Describe the use case(s) that the proposed feature would enable.

**Comment by jelbourn** [comment]
The full underlying Google Maps API is here: 
https://developers.google.com/maps/documentation/javascript/overview

Feel free to open a feature request if there's a specific feature of that API you would like to see exposed in the angular component.
