### ISSUE TITLE
bug(mat-tab-group): First tab is activated even if disabled

### ISSUE THREAD

**Issue by guilhermetod** [angular/components#22119]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-ocdlcs?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Open stackblitz
2. Verify the first tab is active
3. Change active tab to second
4. Verify the first tab is disabled and impossible to be activated again
 
 
#### Expected Behavior

If the first tab is disabled, it should either have no default active tab or activate the first enabled tab found.

#### Actual Behavior

The first tab is active at first moment, then after switching to another tab, the first tab is impossible to be activated again, as it should be in first moment.

**Comment by jelbourn** [comment]
This is working as intended. The `disabled` property prevents a user from selecting the tab, but the developer still has total control of the `selectedIndex` independent of `disabled` state.
