### ISSUE TITLE
help(Mat-Menu): Can I open nested menu on click event instead of hover

### ISSUE THREAD

**Issue by anjummulla** [angular/components#22126]
StackOverflow: https://stackoverflow.com/questions/tagged/angular-material2
stackblitz: https://stackblitz.com/edit/angular-sjy3em-ermrc7?file=app%2Fmenu-overview-example.ts
Google Groups: https://groups.google.com/g/angular-material2/c/Rr0AhgLoFuU/m/g0DczGA2AgAJ

#### What are you trying to do?
I am using mat-menu for mobile device to create hamburger menu.
I am trying to open nested mat-menu on click instead of hover

#### What troubleshooting steps have you tried?
created sample code in below link
https://stackblitz.com/edit/angular-sjy3em-ermrc7?file=app%2Fmenu-overview-example.ts

What are you seeing that does not match your expectations? 
only main menu icon click is working and for sub levels only hover is working not click

#### Reproduction
https://stackblitz.com/edit/angular-sjy3em-ermrc7?file=app%2Fmenu-overview-example.ts
We can only help if we can reproduce the problem ourselves. 

  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
Our menu component is the pop-up kind of menu shown in https://material.angular.io/components/menu/examples. For a navigation "menu" in a sidenav, you would want to use something like `mat-list`.
