### ISSUE TITLE
CdkTable defaults to role="grid" when it should probably default to role="table"

### ISSUE THREAD

**Issue by Wildebrew** [angular/components#22122]
# Incorrect accessibility markup for A.M. tables

Based on [These table examples](https://material.angular.io/components/table/examples)

All examples uses the ARIA grid markup
* `role="grid"` on the container
* `role="gridcell"` on regular table cells

This is misleading at best and can cause major screen reader user issues at worst.
The [grid role](https://www.w3.org/TR/wai-aria-1.2/#grid) is meant for a two-dimentional layout of interactive elements, such as a spreadsheet or a datepicker.
It is not intended for use with static/normal tables, including sortable static tables (where clicking the column headers can sort by that column), not even for tables with one or two action buttons per row (e.g. "delete" or "more info").

To fix, do one of 2 things:
### Remove the ARIA markup
(all instnaces of the role attribute).
The underlying HTML markup is correct table markup.

### Replace grid roles with static table roles

* Replace `role="grid"` with `role="table"`
* Replace every instance of `role="gridcell"` with `role="cell"`

This would be sufficient. Other role attributes (columnheader, rowheader, row and rowgroup) are equally valid in a table and grid structure.

**Comment by Splaktar** [comment]
From https://www.w3.org/TR/wai-aria-1.2/#table:

> The `table` role is intended for tabular containers which are not interactive. If the tabular container maintains a selection state, provides its own two-dimensional navigation, or allows the user to rearrange or otherwise manipulate its contents or the display thereof, authors SHOULD use `grid` or `treegrid` instead.

----

Our Material tables can be non-interactive in certain configurations, but the most common use case is that the table and it's cells are interactive. This includes sorting, paging, tool buttons, and the ability for cells to contain interactive content like inputs, selects, checkboxes, buttons, etc.

**Comment by jelbourn** [comment]
Yeah, the original intent of the cdk-table is that it _is_ the fully interactive `role="grid` pattern. However, over time we've seen that people do often use it as a regular `role="table"`. We should consider changing the default and making it easier to swap between the two.

**Comment by Wildebrew** [comment]
Absolutely. It's honestly quite simple to do, the person just has to
decide whether this is a "static table" or "interactive table".
I think some documentation and a parameter the developer can parse in
would do the trick. You just have to adjust the roles as explained in
the original comment (grid + gridcell for interactive, table + cell
for static)


On 3/5/21, Jeremy Elbourn <notifications@github.com> wrote:
> Yeah, the original intent of the cdk-table is that it _is_ the fully
> interactive `role="grid` pattern. However, over time we've seen that people
> do often use it as a regular `role="table"`. We should consider changing the
> default and making it easier to swap between the two.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/angular/components/issues/22122#issuecomment-791761945


-- 
Work hard. Have fun. Make history.

**Comment by Splaktar** [comment]
@annieyw was working on this in https://github.com/angular/components/pull/22491. It recently got merged, but then reverted due to presubmit issues.

**Comment by agmcleod** [comment]
One issue im running into that may be related. On firefox for mac, using the mac voice over with keyboard navigation. It doesn't seem to be able to leave the <thead> row when it has role="rowgroup". If I remove those it seems fine. Could be a firefox bug, but I can't seem to find anything on it.

**Comment by jelbourn** [comment]
This was eventually landed in https://github.com/angular/components/pull/23161

@agmcleod feel free to open an issue with the full details if you're using the latest version that includes the aforementioned PR
