### ISSUE TITLE
bug(material/datepicker): descender of letter gets cut off with `outline` appearance

### ISSUE THREAD

**Issue by PhilippeMorier** [angular/components#22125]
## Overview of the Issue

When having a datepicker with the appearance set to `outline` the [descenders](https://www.figma.com/dictionary/descender/) within the label (for placeholder) get slightly cut off.

![Descender](https://static.wikia.nocookie.net/typography/images/5/57/Descs-latin_times.png/revision/latest/scale-to-width-down/400?cb=20141024023421)
Source: https://typography.fandom.com/wiki/Descender

## Angular and Material Versions

"@angular/animations": "^11.2.4",
"@angular/cdk": "^11.2.3",
"@angular/common": "^11.2.4",
"@angular/compiler": "^11.2.4",
"@angular/core": "^11.2.4",
"@angular/forms": "^11.2.4",
"@angular/material": "^11.2.3",
"@angular/material-moment-adapter": "^11.2.3",
"@angular/platform-browser": "^11.2.4",
"@angular/platform-browser-dynamic": "^11.2.4",
"@angular/router": "^11.2.4",
"core-js": "^3.9.1",
"moment": "^2.29.1",
"rxjs": "^6.6.6",
"tslib": "^2.1.0",
"zone.js": "^0.11.4"

## Motivation for or Use Case

I'd like to use the datepicker with the appearance `outline` without cut off descenders. It doesn't provide an optimal UX and overall impression.

## Browsers and Operating System

Issue observed on macOS Big Sur 11.2.2 with following browsers:
- Brave, Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)
- Safari, Version 14.0.3 (16610.4.3.1.4)
- Firefox, Version 85.0.2 (64-bit)

## Reproduce the Error

See [this Stackblitz](https://stackblitz.com/edit/angular-material-expension-icon?file=src%2Fapp%2Fapp.component.html).

## Screenshots

|Cut off "g"||
|-|-|
|![2021-03-04 07 50 12](https://user-images.githubusercontent.com/12933406/110080858-5da5b880-7d8b-11eb-8847-70af2201212f.gif)|![2021-03-04 07 56 36](https://user-images.githubusercontent.com/12933406/110080876-639b9980-7d8b-11eb-8065-732abd3874f4.gif)|

## Related Issues

N/A

## Suggest a Fix

One could set the `height` of the label to `19px` or remove `overflow: hidden;` on `.mat-form-field-label` but that doesn't feel like we're fixing the root cause 🤕 .

**Comment by crisbeto** [comment]
I believe that this has the same root cause as https://github.com/angular/components/issues/20370.
