### ISSUE TITLE
Generated API docs missing member descriptions from base class

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22128]
#### Documentation Feedback

Fill _Description_ column in the docs for `MatDatepicker`
Currently all descriptions are absent

https://material.angular.io/components/datepicker/api#MatDatepicker

**Comment by jelbourn** [comment]
It looks like this is a general bug with our API generation tooling where it's not reading the descriptions from members defined in the base class, with `MatDatepicker` being the most obvious example.

**Comment by crisbeto** [comment]
This was fixed in https://github.com/angular/components/pull/22482, I just hadn't tagged the PR correctly. Closing.
