### ISSUE TITLE
bug(matSelect): disableOptionCentering: true + overlay opens on top -> scroll is off

### ISSUE THREAD

**Issue by Ignasimg** [angular/components#22131]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-mw8zrx?file=src%2Fapp%2Fexample-component.css

Steps to reproduce:
1. Open select and choose option 10
2. Open select again
 
 
#### Expected Behavior

I would expect to see the selected option in the overlay panel

#### Actual Behavior

When there's an option already selected and _disableOptionCentering: true_ and the overlay opens on top rather than bottom, the scroll within the overlay panel is off.

#### Environment

- Angular: ^11.2.3
- CDK/Material: ^11.2.2
- Browser(s): Chrome 88.0.4324.190
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
This is fixed in the new MDC based select component coming soon in v15
