### ISSUE TITLE
bug(docs): Overview Content of a11y package is random headings

### ISSUE THREAD

**Issue by twerske** [angular/components#22133]
#### Reproduction

Steps to reproduce:
1. https://material.angular.io/cdk/a11y/overview
<img width="330" alt="overview menu of a11y docs" src="https://user-images.githubusercontent.com/15061394/110174568-4c31d000-7dce-11eb-8bd3-02743ff3dbe3.png"> 
 
#### Expected Behavior
Overview should show the a11y tools available:
ListKeyManager
- Example

FocusTrap
- Example

InteractivityChecker
- Example
etc 

#### Actual Behavior
Overview is a mixture of headers from the different a11y tooling. Markdown may be tagged wrong?

#### Environment
v11 docs site

**Comment by jelbourn** [comment]
Something is definitely weird with how the TOC is being generated. Might be related to #21751. @Splaktar want to take a look since you dealt with this recently?

**Comment by Splaktar** [comment]
I will take a look.

**Comment by Splaktar** [comment]
It looks like this was messed up when more content was added in v6. Here's the v5 site: https://v5.material.angular.io/cdk/a11y/overview.

**Comment by Splaktar** [comment]
PR https://github.com/angular/components/pull/22136 fixes this, but looking into this uncovered a lot of other questions in https://angular-team.atlassian.net/browse/COMP-164.

**Comment by Splaktar** [comment]
Now that this has been merged and the docs-content generated, I can post a screenshot of what this will look after the docs site gets deployed the next time.

![Screen Shot 2021-03-07 at 19 53 06](https://user-images.githubusercontent.com/3506071/110261597-db7de580-7f7e-11eb-98f4-0d3bc8e47986.png)
