### ISSUE TITLE
help(mat-stepper): Prevent mat-stepper from changing steps using keyboard

### ISSUE THREAD

**Issue by noobyogi0010** [angular/components#22142]
#### What are you trying to do?

I've a linear vertical `mat-stepper` within which I render multiple different components. This `mat-stepper` and "next" and "previous" buttons are on same component. I've prevented user from changing the step by directly clicking on `mat-step`. Now if a user navigates to the stepper from keyboard, then he/she is able to move between steps using keyboard. I want to prevent user from doing so at all.

#### What troubleshooting steps have you tried?

I've tried using stepControl to control this movement based on formGroup's validation. But it allows to navigate between steps once the formGroup is valid.

#### Environment

- Angular: v10.0.6
- CDK/Material: v10.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This isn't something that we support, because it would make the component less accessible.
