### ISSUE TITLE
MatDialog : Theme display bug with FullscreenOverlayContainer

### ISSUE THREAD

**Issue by Alex9974** [angular/components#22146]
Hello guys,

Sorry to bother you here, but we are facing an issue in our dev team.

We have a div that can be displayed as a full screen container by the navigator. Inside this div we open a modal MatDialog. This MatDialog is attached to the body not to the div, so we use FullscreenOverlayContainer to supports correct displaying of overlay elements in fullscreen mode.
For our application, we uses 2 themes, one default and dark. When the modal MatDialog is opened from the div in full screen mode, the selected theme (default or dark) is well transmitted to the modal which is displayed correctly. On the other hand, when the div is not in full screen mode, the modal MatDialog doesn't receive the selected theme and is therefore not displayed correctly.

Thanks in advance for your time

**The div is in full screen mode, the theme (.dark-theme) is well transmitted to the modal MatDialog** : 
![full-screen](https://user-images.githubusercontent.com/59565576/110358283-843e4a80-803c-11eb-8acb-cee9cfcb45c3.png)

**The div is not in full screen mode, the theme (.dark-theme) is not transmitted to the modal MatDialog :** 
![not-full-screen](https://user-images.githubusercontent.com/59565576/110358443-b485e900-803c-11eb-8c62-ce073bb3072f.png)

**Comment by crisbeto** [comment]
It's hard to tell what might be going on without an example. Maybe you have to add the theme class to the fullscreen element?

**Comment by redvp** [comment]
Hello crisbeto, I will try and provide you with more information.

Theme classes are added dynamically and globally via an ngrx store, like so :

`const classList = this.overlayContainer.getContainerElement().classList`
`const toRemove = Array.from(classList).filter((item: string) =>item.includes('-theme'))`
`if (toRemove.length) { classList.remove(...toRemove) }`
`classList.add(theme.endsWith('dark') ? 'dark-theme' : 'default-theme')`

Where overlayContainer is an instance of OverlayContainer.

Some modules in our app need fullscreen support, these modules use the FullscreenOverlayContainer (added to providers in said modules)
`{ provide: OverlayContainer, useClass: FullscreenOverlayContainer }`

Result is as above, theming isn't applied to dialogs opened from modules with fullscreen support.
Any help would be greatly appreciated

**Comment by redvp** [comment]
After running more tests, providing FullscreenOverlayContainer globally in app.module solves our problem with opening dialogs. It just seems sub-optimal, not sure if there are any drawbacks to this solution. Maybe performance wise ?

**Comment by crisbeto** [comment]
Closing since the issue seems to have been resolved. And to answer the last question: there shouldn't be any performance issues with providing the `FullscreenOverlayContainer` globally.
