### ISSUE TITLE
feat(Material Select) - Showing checked values at top in case of Multiple Selections

### ISSUE THREAD

**Issue by omkarshinge** [angular/components#22186]
**Showing checked values at top in case of Multiple Selections.**

The feature to let the options that are selected to be at the top of the list
i.e. One should be able to see the checked values at the top of the dropdown values followed by the unchecked values

**Use Case**

While using Material Select component with Multiple Selections enabled having many values user needs to scroll down to look up what all values have been selected. It would be nice if the checked values are displayed at the top by default for ease of use from the perspective of user.

This can be achieved using `<mat-optgroup>` but it becomes an overhead to maintain two different arrays for checked & unchecked values or iterate through the array twice for the separation of checked & unchecked values.

**Comment by Xender007** [comment]
Hi, @omkarshinge 
First of all I got the basic idea and I think its quite nice if we can add this feature in angular.

I have one question on this feature ( **I am new here but I like JS so as angular, so want to explore more, please correct me if I am saying anything wrong.**) 
If user selecting any values from multi-select dropdown that should show under **checked group** right ? But how it should show when there is no selected value/data (view after page load without any pre-selected values), do I need to make that group hidden until user selected anything or I can show one message like "-None selected-".

Note : I want to learn more about angular by contributing to this project. Please help me to understand. Thanks !

**Comment by crisbeto** [comment]
We can't implement it on our end, because we don't have access to the data representing the options. You should be able to do it yourself by sorting the selected options to the top of the list inside the `selectionChange` event.
