### ISSUE TITLE
bug(SELECT): doesn't preserve state with angular 11 HMR

### ISSUE THREAD

**Issue by mtosic** [angular/components#22212]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-1xabnd

Steps to reproduce:
1.  Run the SELECT in angular CLI with --hmr: ng serve --hmr
2. Change value of basic mat-select and basic native select
3.  Change any HTML
4.  Basic mat-select doesn't preserve state with --hmr, basic native select preserves state
 
 
#### Expected Behavior

I expect mat-select to preserve state with --hmr enabled

#### Actual Behavior

mat-select doesn't preserve state with --hmr enabled, only basic native select does.

I also tried with angular@next, angular-cli@next and angular-material@next.
Same behaviour.

#### Environment

- Angular: 11.2.4
- CDK/Material: 11.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
@mgechev is it even possible to preserve state like this with HMR today?

**Comment by mgechev** [comment]
Seems like it should be. @alan-agius4 would have more context here.

**Comment by alan-agius4** [comment]
Unlike when using `matNativeControl` on a native `<select>`, `<mat-form-field>` doesn't wrap/decorate a native `<select>` form element. 


HMR form state rehydration is only performed on native HTML form elements.

**Comment by mtosic** [comment]
@alan-agius4  Can form state rehydration be implemented on material components with non-native elements or this is technical limitation from Webpack?

**Comment by alan-agius4** [comment]
It’s not a limitation from webpack, but rather a missing feature from end. Unfortunately at the moment there is no easy way to apply only apply changes to component template/styles without re-bootstrapping the entire application which causes the state of components to be lost. 

There are a couple of issues related to this:
https://github.com/angular/angular/issues/39367
https://github.com/angular/angular-cli/issues/19867

**Comment by jelbourn** [comment]
Closing this since it's not possible on the angular/components side to support this- it's something Angular as a whole would need to support.
