### ISSUE TITLE
CDK VirtualScroll: Event when user stops scrolling in virtual scroll

### ISSUE THREAD

**Issue by developer-bala** [angular/components#22248]
#### What are you trying to do?

Im having a table with thousands of records to be displayed on the single page. So, Im using virtual scroll to display the data thereby I could minimize DOM manipulation.

There, I would like to apply the css at run time. Once the user stops the scrolling on my virtual scroll table, I need to apply the css to my table.

#### What troubleshooting steps have you tried?

I have searched for any events in cdk. I have found the scolled event in scrolldispatcher but i couldnt able to find the event while user stops the scrolling. Please help me on this.

 ```
this.scrollDispatcher.scrolled()
      .subscribe(event => {
        console.log('scrolled');
      });
```

Any help would be greatly appreciated!! Thanks in advance

  
#### Environment

- Angular: 8 
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Ubuntu):

**Comment by jelbourn** [comment]
The typical way you would do this is by debouncing scroll events. With rxjs, you can use the `debounceTime`  operator:
https://rxjs-dev.firebaseapp.com/api/operators/debounceTime

**Comment by adrianclaudiudima** [comment]
Event of not scrolling is the opposite of scrolling. This can be achieved using the following syntax : 

```
this.scrollDispatcher.scrolled().pipe(
      // don't catch each scroll event as you won't need it.
      debounceTime(10),
      // switchMap will not emit within the chain if new observable comes from scroll dispatch. Here you can configure when you consider the user has stopped the scrolling process
      switchMap(() => of('scroll stopped').pipe(delay(300)
      ))
    ).subscribe(v => console.log(v));
```
