### ISSUE TITLE
Mat-Tabs not working after upgrading to angular version 11

### ISSUE THREAD

**Issue by sebskyw** [angular/components#22257]
My tabs are not longer working after upgrading to abgular 11 and most recent version of angular-matertiall. 

The tabs are rendered correctly however when I do click on tabs those are not switching....

![image](https://user-images.githubusercontent.com/34474743/111455857-998b3700-8716-11eb-84b3-c173a519fccd.png)
![image](https://user-images.githubusercontent.com/34474743/111455866-9d1ebe00-8716-11eb-8216-244728ffb370.png)

**Comment by crisbeto** [comment]
The `restoredCtx` was merged to the v12 branch of Angular (https://github.com/angular/angular/pull/40833). Is it possible that you installed Angular 12 while you're on v11 of Material?

**Comment by sebskyw** [comment]
please find the versions
![image](https://user-images.githubusercontent.com/34474743/111542328-d9333c80-8771-11eb-9592-0bdb59fe53cf.png)

**Comment by crisbeto** [comment]
It looks like some of your `@angular` dependencies are at version 12 while others are at 11. They should all be on the same major version.

**Comment by sebskyw** [comment]
Damn, that was the issue. Thanks a lot!

czw., 18 mar 2021 o 07:39 Kristiyan Kostadinov ***@***.***>
napisał(a):
