### ISSUE TITLE
docs-bug(Autocomplete): Examples autocomplete doesn't work

### ISSUE THREAD

**Issue by peteichuk** [angular/components#22278]
#### Documentation Feedback

examples don't work on main site - material.angular.io and stackblitz service

error in console:
`main-es2015.807f533dcf8794ae3ae6.js:1 ERROR TypeError: Cannot read property 'selectors' of null`

version 12.0.0-next.3 (because I can't checkout to the 11 version)

**Affected documentation page:** https://material.angular.io/components/autocomplete/examples

**Comment by peteichuk** [comment]
Some examples in Select don't work too

https://material.angular.io/components/select/examples

**Comment by crisbeto** [comment]
Should be fixed now. We accidentally deployed the wrong version.
