### ISSUE TITLE
Show number of row in material table

### ISSUE THREAD

**Issue by ngantran91** [angular/components#22279]
Hi,
I have read through the material table document, but I can't see an example of showing line count in the total number of records returned.
And I wrote down a directives and put it in the mat-paginator and I got the result, but it seems to generate a lot of errors.
![Screenshot_2](https://user-images.githubusercontent.com/80188330/111617206-6aa7ba80-8815-11eb-8613-cb22e6932b7e.png)
Help me!
issue after search keyword on the list:
![Screenshot_3](https://user-images.githubusercontent.com/80188330/111617679-020d0d80-8816-11eb-8d1f-e0defc39d0d9.png)

**Comment by jelbourn** [comment]
This isn't something the table or paginator provide, you'd have to keep track within your app.
