### ISSUE TITLE
mat-form-field have vertical align issue on FF and Chrome using Prefix & suffix on appearance="outline"

### ISSUE THREAD

**Issue by darxx** [angular/components#22280]
Originally taken from:
https://material.angular.io/components/form-field/overview

More information in stackblitz example.

[Example](https://stackblitz.com/edit/angular-3uwa6d?file=src/app/form-field-prefix-suffix-example.html)

**Comment by Splaktar** [comment]
Duplicate of https://github.com/angular/components/issues/20074.
