### ISSUE TITLE
bug(mat-form-field): Does not show placeholder text when mat-label is empty

### ISSUE THREAD

**Issue by glued** [angular/components#22297]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-w1cssx?file=src/app/form-field-appearance-example.html

Steps to reproduce:

1. Create a Material form field with an empty mat-label and an input with placeholder
```
<mat-form-field appearance="outline">
  <mat-label></mat-label>
  <input matInput placeholder="Placeholder" />
  <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
  <mat-hint>Hint</mat-hint>
</mat-form-field>
```

The placeholder only appears if you remove the empty mat-label
 
#### Expected Behavior

Show the placeholder

#### Actual Behavior

Placeholder is not shown

#### Environment

- Angular:11.0.0
- CDK/Material:11.0.0
- Browser(s):Chrome 88
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
I agree that it's a bug, but dealing with it on our end in a reliable and performant way will be tricky, because we'd have to observe the DOM for changes. Furthermore, providing empty labels is an accessibility issue. I'm closing this issue, because it can be handled by the consumer by not providing an empty `mat-label` in the first place.

**Comment by glued** [comment]
I'm dynamically creating / adjusting form elements based on user actions... if I remove the label in one scenario then re-add it in another it breaks...

**Comment by crisbeto** [comment]
Couldn't you put an `ngIf` on the label so it doesn't render when empty?

**Comment by glued** [comment]
adding `*ngif` to the label doesnt work, it will never reappear... I ended up creating a custom directive to fix the issue to call change detection on the parent
```
@Directive({ selector: '[cdMatLabelFix]' })
export class MatLabelFixDirective {
  private _value: string | undefined = '';

  @Input()
  set value(value: string | undefined) {
    if (this._value === value) return;
    this._cdRef.markForCheck();
    this._value = value;
  }

  constructor(@SkipSelf() private _cdRef: ChangeDetectorRef) {}
}
```
