### ISSUE TITLE
feat(radio/checkbox): Improve printing stylesheet

### ISSUE THREAD

**Issue by felhag** [angular/components#22298]
#### Feature Description
Not sure if this is a bug or a feature, but when printing some components the background-color isn't included. For example: 
- radio buttons
- checkboxes
- sliders (found a separate issue for this: #11364)

There might be more components of course.

#### Use Case
Use the browser print function on page containing Angular Components. Because the background-color isn't included you can't tell if a radio or checkbox is selected. 

Component:
![image](https://user-images.githubusercontent.com/62592273/111864838-9afd6f00-8963-11eb-9920-8d1448b5c071.png)

When printing: 
![image](https://user-images.githubusercontent.com/62592273/111864859-bff1e200-8963-11eb-8467-925438ac5e5a.png)

**Comment by crisbeto** [comment]
Closing since the related PR was just merged in.
