### ISSUE TITLE
bug(autocomplete): clicking option doesn't select it when options are returned from function

### ISSUE THREAD

**Issue by Burtsev-Alexey** [angular/components#22312]
#### Reproduction

https://stackblitz.com/edit/angular-tica2t?file=src/app/autocomplete-simple-example.html

Steps to reproduce:
1.  Click inside number field. (A list of options will appear showing the only option "One"
2.  Click the "One" option.
 
 
#### Expected Behavior

Option is selected.
Options drop-down closed option value is showed inside Number field.

#### Actual Behavior

Nothing happens.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
Seems like you're missing a `trackBy`. Also, getting the collection from a function call is not considered best practice.

Working example:
https://stackblitz.com/edit/angular-tica2t-bno4ev?file=src%2Fapp%2Fautocomplete-simple-example.html

**Comment by Burtsev-Alexey** [comment]
> Seems like you're missing a `trackBy`. Also, getting the collection from a function call is not considered best practice.
> 
> Working example:
> https://stackblitz.com/edit/angular-tica2t-bno4ev?file=src%2Fapp%2Fautocomplete-simple-example.html

Thank you. I thought trackBy is optimization and is not required for code to work correctly.
Can you please explain a bit why it is mandotary in this example?
