### ISSUE TITLE
feat(date-range-picker): Double calendar view

### ISSUE THREAD

**Issue by jpike88** [angular/components#22318]
#### Feature Description

Choosing a date range in angular material could use a dual calendar look, like used in appointment/bookings, see below

<img width="849" alt="Screenshot 2021-03-23 at 11 25 51 PM" src="https://user-images.githubusercontent.com/9585787/112181536-1cd4ed00-8c2f-11eb-9d66-f1abcb8c38ab.png">

**Comment by jelbourn** [comment]
For now we don't have any plans to add this kind of feature to the datepicker. At some point in the future we'll probably look at expanding the functionality, but it's far enough out that I'll close this for now.
