### ISSUE TITLE
Couldn't find MapDirectionsService in google/map package

### ISSUE THREAD

**Issue by David-Don1998** [angular/components#22317]
**StackBlitz link is refered here**
https://stackblitz.com/edit/angular-ivy-itzaxw?file=src%2Fapp%2Fapp.component.ts

![public-api d ts - google-map - Visual Studio Code 3_23_2021 6_58_45 PM](https://user-images.githubusercontent.com/58950211/112155189-12086100-8c0b-11eb-8cff-55da09b4f908.png)
![public-api d ts - google-map - Visual Studio Code 3_23_2021 6_58_45 PM (2)](https://user-images.githubusercontent.com/58950211/112155248-1f255000-8c0b-11eb-9dbd-addd9a3155c8.png)

**Comment by crisbeto** [comment]
What version are you running? The service was introduced in 12.0.0-next.1.

**Comment by jelbourn** [comment]
Closing since this hasn't been released to stable yet which is likely the issue.
