### ISSUE TITLE
bug(mat-dialog): Tab content jumps a little right after dialog opening.

### ISSUE THREAD

**Issue by liesahead** [angular/components#22323]
#### Reproduction

![jumping_dialog_reproduction](https://user-images.githubusercontent.com/32300784/112313492-92cd6880-8cb0-11eb-9d50-a30f2f254e22.gif)

Here are the two adjacent frames extracted from the gif above, there you can see that alignment of elements is slightly different (if you don't see - I recommend to use page ruler to make sure I don't lie).
![frame_1 1](https://user-images.githubusercontent.com/32300784/112443198-56077d00-8d55-11eb-86ad-02e41f941f3a.png)![frame_2 2](https://user-images.githubusercontent.com/32300784/112443201-56a01380-8d55-11eb-8daf-2c34bc6f0d1a.png)

Use StackBlitz to reproduce your issue: 
- https://stackblitz.com/edit/angular-hwqwcc?file=src/app/dialog-overview-example-dialog.scss

Steps to reproduce:
1. Open the given link and open/close dialog at least a few times.
2. If cannot reproduce the bug - enable max cpu throttling in devtools.

Option 2:
1.  Open the angular material documentation: https://material.angular.io/components/dialog/overview
2. Open/close first dialog at least a few times.
3. If cannot reproduce the bug - enable max cpu throttling in devtools.
 
 
#### Expected Behavior

Dialog content shouldn't move after dialog opens with that beautiful 'grow' style animation.

#### Actual Behavior
The dialog content is jumping a little (depends on what content it has). I'm afraid that the issue https://github.com/angular/components/issues/13870 also might be related to this bug. So it's the dialog's fault that expansion panel is expanded and content is jumping.

#### Environment

- Browser(s): Chrome (Version 89.0.4389.90 (Official Build) (64-bit))
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 latest version

**Comment by crisbeto** [comment]
I don't see any jumping on my end. Are you referring to the bluriness between the first and second screenshot?

**Comment by liesahead** [comment]
@crisbeto, Hi, thanks for checking! Not really, blurriness is an animation which is perfectly fine. In gif above you should focus on watching the text inputs (how they jump a little up after dialog init). Looks like it's just around 1 or 2px, but when almost all elements move it's noticeable (at least for me). Here are two adjacent frames and I used ruler to try to show that inputs slightly are in different positions.

![image](https://user-images.githubusercontent.com/32300784/112946151-d9eaac00-913d-11eb-8759-c993e1fbb092.png)

**Comment by crisbeto** [comment]
Thanks for the screenshot, but I still can't notice it on my machine. It looks like some kind of artifact from the animation so I'm not sure whether we can do much about it.

**Comment by liesahead** [comment]
It was more noticeable on my old laptop, it works very slow, that's when I noticed the jumping. Now I'm using high-end laptop and it unnoticeable without enabling hard throttling. So, I'm not sure, if nobody except me has issues with this, probably this issue should be closed. What do you think?

**Comment by jelbourn** [comment]
Closing since it seems to not be an issue any more
