### ISSUE TITLE
question: usage of @angular/dev-infra-private

### ISSUE THREAD

**Issue by kyubisation** [angular/components#22335]
This might be an unusual question; Is it alright to use the @angular/dev-infra-private package?

I am aware of the "INTERNAL USE ONLY" notice, which is why I'm asking via this issue.
Is the "INTERNAL USE ONLY" declared, because usage might tax the build infrastructure of the Angular dev environment or is it more along the lines of "You're on your own"?

The reason for this question is the bazelbuild/rules_webtesting hasn't created a release since september 2019 and we're starting to run into potential problems.

**Comment by crisbeto** [comment]
I believe that it's more of a "You're on your own situation" since we don't consider it a public package and we'll make changes to it based on the requirements of our projects.

**Comment by kyubisation** [comment]
Thank you for the reply.
Since our project is heavily inspired by the angular/components setup, we will test if this would be an improvement to our current situation. We do not expect any support and will contribute any improvement/fix back to angular/components, as we have previously done (although they were/might be small).
