### ISSUE TITLE
Bug in MatBottomSheet: Opener Button appears pressed after closing Bottom Sheet

### ISSUE THREAD

**Issue by Danelrf** [angular/components#22341]
As the title says,
when opening a Bottom Sheet with a button, it keeps its pressed style after the Bottom Sheet has been closed.

This is evident in the official Example from Angular Material
https://stackblitz.com/angular/oogkgkxvppl?file=src%2Fapp%2Fbottom-sheet-overview-example.ts

as well as

https://material.angular.io/components/bottom-sheet/overview
 

Apologies if this expected behaviour.

**Comment by crisbeto** [comment]
This is working as expected, because focus has to be returned to the element that had it before the bottom sheet was opened. You can disable it by passing in `restoreFocus: false` when opening the bottom sheet, but doing so will degrade the accessibility of your app.
