### ISSUE TITLE
md-select width issue

### ISSUE THREAD

**Issue by StephaneMourgues** [angular/components#2234]
#### Bug, feature request, or proposal:
md-select width is always 112px, whatever the size of the displayed option

#### What is the expected behavior?
When the selected option is wider than the md-select, the md-select should resize accordingly

#### What is the current behavior?
The md-select has a fixed width

#### What are the steps to reproduce?
See plunker here:
https://plnkr.co/edit/eMIni8u4rBzJj07bKRJQ?p=preview

Default selected value is very long, the down arrow is in the middle of the text.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-alpha.11-3
Tested with chrome 55.0.2883.87 , firefox 51.0b7

**Comment by Andrade2905** [comment]
any news?

**Comment by Andrade2905** [comment]
In my project, I used this style for correction:
```
div.mat-autocomplete-panel{
  max-width: 600px; 
}
```

**Comment by anapanadero** [comment]
I have the same problem. Any news?

**Comment by farley911** [comment]
Agreed this is a very annoying thing when working with md-select to always have to go and override the default width to make it work.

**Comment by Nodarii** [comment]
Also there are cases when we need kind of "small" selects, but it's impossible to have it due to `min-width` property set to '112px', on the '.mat-select-trigger' element

**Comment by johnpaulmanoza** [comment]
Solved this by adding this to my theme.scss or any global css

```
.mat-select-trigger { 
    min-width: 30px !important; 
}
```

**Comment by Nodarii** [comment]
@johnpaulmanoza, yes it works, but as for me it's not proper way to do it

**Comment by alexbeattie42** [comment]
@Nodarii I submitted pull request: https://github.com/angular/material2/pull/5750 to solve this issue

**Comment by jelbourn** [comment]
Closing this since I don't see us ever doing anything like this in the library. Changing the width of the select trigger upon selection would be a pretty jarring user experience (potential layout shifts). I've heard requests for sizing the trigger based on the options, but that would require rendering and measuring all of the options for every select before they're opened, which would be a performance nightmare.
