### ISSUE TITLE
bug(Tooltip): Long tap for showing tool tip on iOS is not working correctly

### ISSUE THREAD

**Issue by wegascee** [angular/components#22360]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-vcwanu?file=src/app/tooltip-overview-example.html

Steps to reproduce:
1. Long tap on "Action" button with iOS device
 
 
#### Expected Behavior

Tool tip is shown on long tap, click event is not executed. Working on all iOS devices.

#### Actual Behavior

Depending on the device:
- iPad: no tooltip
- iPhone (iOS 14): tooltip is shown and text below is selected
- iPhone (iOS 12): tooltip is shown, but also click event is triggered

#### Environment

- Angular: 8.3.29
- CDK/Material: 8.2.3
- Browser(s): Safari/WKWebView
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

**Comment by crisbeto** [comment]
Have you tried it against a newer version of Material? It seems to be working correctly for me on material.angular.io against an iOS 14 device.

**Comment by wegascee** [comment]
After trying to get the update working, I finally managed to get to:

* Angular: 11.2.6
* CDK/Material: 11.2.6

I tested with the same devices, but this didn't changed something for me. The iOS 14 device (Simulator) shows a weird behavior. Most of the time it doesn't work, one/two times it did what it should do. Did you try it multiple times one after another?

**Comment by zarend** [comment]
@wegascee , does the issue persist for you?

**Comment by zarend** [comment]
Hello @wegascee ,

Thank you for reporting this issue. Unfortunately we are not able to take action if we cannot reproduce it. This might have already been fixed. If the issue persists, please provide reproduction steps or file a new issue report.

- Zach
