### ISSUE TITLE
cannot find mat-core()

### ISSUE THREAD

**Issue by spbroom** [angular/components#22362]
I'm using angular-material as part of an angularjs-angular hybrid app. I have a custom these style sheet which up till a few days was working fine, but now I'm getting this error "Cannot find mixin mat-core" 
for the line: 
`@include mat-core();`

**Comment by crisbeto** [comment]
What version of Material are you using. Also are you using `node-sass` or `sass`?

**Comment by spbroom** [comment]
node-sass and @angular/material@12.0.0-next.4-sha-a2c4b7664

**Comment by crisbeto** [comment]
In Angular v12 we're switching to the new `@use`-based [module system in Sass](https://sass-lang.com/documentation/at-rules/use) which isn't supported by `node-sass`. If you switch over to `sass`, it should work without any other changes on your end. It's also worth noting [that `node-sass` is deprecated](https://sass-lang.com/blog/libsass-is-deprecated).

**Comment by jelbourn** [comment]
Our changelog for v11 noted that `node-sass` with Angular Material is officially unsupported:
https://github.com/angular/components/blob/master/CHANGELOG.md#material-19

**Comment by spbroom** [comment]
> In Angular v12 we're switching to the new `@use`-based [module system in Sass](https://sass-lang.com/documentation/at-rules/use) which isn't supported by `node-sass`. If you switch over to `sass`, it should work without any other changes on your end. It's also worth noting [that `node-sass` is deprecated](https://sass-lang.com/blog/libsass-is-deprecated).

thanks a million, that fixed it.
