### ISSUE TITLE
feat(Pagination): Add pagination component

### ISSUE THREAD

**Issue by lashaloladze** [angular/components#22361]
#### Feature Description

I think adding the Pagination component is a Good Idea. Existing Material Paginator has only the next or prev page button. What if we need to jump on the last page or somewhere in the middle? That will require more steps than clicking just numbers or using go To Page input to jump on page

#### Use Case

I will provide some demos from the web (I am not the author) just for the Examples 
![react-ultimate-pagination](https://user-images.githubusercontent.com/42858276/112833501-df95b280-90a7-11eb-95b8-12c503039e9e.png)

**Comment by crisbeto** [comment]
I think that is identical to https://github.com/angular/components/issues/7615, although it asks for a dropdown rather than a list of pages. I'll close this as a duplicate and mention that we should consider this layout as well.
