### ISSUE TITLE
help(MatStepper): Type 'AbstractControl | null | undefined' is not assignable to type 'AbstractControlLike'

### ISSUE THREAD

**Issue by Senshi111** [angular/components#22386]
Im having problem with stepper using using a single form and only when i have strict enable in tsconfig.json

using 
  angular/material: 11.2.7
  angular/cli: 11.2.6

my html
![2021-04-01_21-42](https://user-images.githubusercontent.com/40372242/113346645-69f24680-9334-11eb-96de-a2a0a12305e8.png)

my .ts
![2021-04-01_21-43](https://user-images.githubusercontent.com/40372242/113346684-75de0880-9334-11eb-87f4-846cfcafdcdb.png)

so im having the error 

> Type 'AbstractControl | null | undefined' is not assignable to type 'AbstractControlLike'.
  Type 'undefined' is not assignable to type 'AbstractControlLike'.ngtsc(2322)

**Comment by crisbeto** [comment]
It's because the `get` method can return `undefined` which the type doesn't allow. You have to cast it to a non-nullable type, e.g. `[stepControl]="checkoutFormArray?.get(0)!"`.
