### ISSUE TITLE
feat(COMPONENT): MatTab output selected

### ISSUE THREAD

**Issue by randym127** [angular/components#22382]
#### Feature Description

Add a selected output to MatTab

#### Use Case

When dynamically creating MatTab in a template it would be nice if when that tab is selected MatTab emitted the selection. i.e.

`<mat-tab-group dynamicHeight>
	<mat-tab *ngFor="let tab of tabs" [label]="tab.name" (selected)="tabSelected(tab)">
	  <ng-template matTabContent>
		...
	  </ng-template>
	</mat-tab>
</mat-tab-group>`

**Comment by jelbourn** [comment]
`MatTabGroup` already has a `selectedTabChange` output.
