### ISSUE TITLE
bug(mat-tab-group): Pagination is not updated when the display value of the parent is updated

### ISSUE THREAD

**Issue by mlbiche** [angular/components#22384]
#### Reproduction

StackBlitz to reproduce the issue: https://stackblitz.com/edit/components-issue-t4l4fx?file=src/app/example-component.ts

Steps to reproduce:
1. Click on Toggle button

#### Expected Behavior

The pagination should be displayed as the tab list in the tab header is overflowing.

#### Actual Behavior

When the tab group is shown, the pagination is not displayed. The pagination is then displayed once a tab is clicked.
In my project, the pagination is not even displayed again once a tab is clicked.

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.3
- Browser(s): Tested on Chromium and Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Tested on macOS Windows

**Comment by crisbeto** [comment]
Unfortunately we can't do much about this, because there's no performant way for us to know when the element becomes visible. Technically we can get it to work with a `ResizeObserver`, but we can't use it yet, because we have to support IE11.
