### ISSUE TITLE
feat(_MatOptionBase ):  ViewValue 

### ISSUE THREAD

**Issue by Admo63** [angular/components#22393]
Hello, :)

#### Feature Description

Property for customize the viewValue in _MatOptionBase.

#### Use Case

If a option contains buttons or other elements, the label of the option in triggerValue is textContent because viewValue is textContent of the option and is not customisable by a property.

Best regards,
Adrien

**Comment by jelbourn** [comment]
This probably isn't something we will add since adding other controls inside of an option isn't a valid for accessibility

**Comment by Admo63** [comment]
Ok thank you :)
