### ISSUE TITLE
How to increase form field error message scale

### ISSUE THREAD

**Issue by jhonToni** [angular/components#22421]
#### What are you trying to do?
I want to increase scale of the form field hints and errors by the form-field-theme but in the theme file the value is fixed.
How can I do ?
[File link](https://github.com/angular/components/blob/master/src/material/form-field/_form-field-theme.scss#L143)

**Comment by crisbeto** [comment]
This isn't something that we support. You could override the styles in your CSS file, but it's at your own risk.
