### ISSUE TITLE
bug(MatInput): change and mouseup events do not trigger after dragging value onto input

### ISSUE THREAD

**Issue by HansCronau** [angular/components#22433]
#### Reproduction

Use StackBlitz to reproduce your issue: 
[StackBlitz Demo: no mouseup and change event](https://stackblitz.com/edit/components-issue-jashyp?devtoolsheight=33&file=src/app/example-component.html)

Steps to reproduce:
1. Have a `matInput` and listen to its events `mouseup` and `change`.
2. Drag and drop a value onto the input.
 
 
#### Expected Behavior

The new value is visible in the input field and is communicated by the `mouseup` and `change` events.

#### Actual Behavior

The new value is visible in the input field, but it is not communicated by the `mouseup` and `change` events.

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Firefox, Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10, elementaryOS 5.1 (Ubuntu 18.04)

**Comment by geromegrignon** [comment]
By removing Angular Material content (mat-form-field tag and matInput directive), the problem still occurs : so it's not related to this project.

**Comment by HansCronau** [comment]
@geromegrignon Do you think this would be suited for a bug report on Angular?

**Comment by geromegrignon** [comment]
No as it's not related to Angular either.
It's how the plaform works.
Here is an example with Javascript : https://stackblitz.com/edit/web-platform-cixbv8?file=index.html

**Comment by HansCronau** [comment]
@geromegrignon Thanks for your explanation! I'll close this issue.
