### ISSUE TITLE
feat(theme): Allow more then only 3 colors in themes

### ISSUE THREAD

**Issue by Leccho** [angular/components#22430]
#### Feature Description

Allow to add more then 3 colors in themes (primary/accent/warn).

#### Use Case
```scss
// What's in use right now
$theme: mat-light-theme(
  (
    color: (
      primary: mat-palette($blue),
      accent: mat-palette($green),
      warn: mat-palette($red),
    ),
  )
);

// The feature request
$theme: mat-light-theme(
  (
    color: (
      primary: mat-palette($blue),
      accent: mat-palette($green),
      warn: mat-palette($red),
      custom: mat-palette($custom),
    ),
  )
);

```

**Comment by crisbeto** [comment]
These palettes are based on the Material design spec so we can't just make up more. Furthermore, I'm not sure how adding more would work, considering that we'd have update our own themes to know about these palettes that haven't been defined yet.
