### ISSUE TITLE
error NG8001: 'map-marker-clusterer' is not a known element when try to use map cluster

### ISSUE THREAD

**Issue by SugarLin** [angular/components#22443]
#### What am I trying to do?
I'm trying to use map-marker-clusterer in google-map tag.
I follow the guideline in https://github.com/angular/components/tree/master/src/google-maps/map-marker-clusterer.
Done installed @googlemaps/markerclustererplus, but still come out this error.
Please help for this.

#### Reproduction
Follow the guideline in https://github.com/angular/components/tree/master/src/google-maps/map-marker-clusterer.
  
#### Environment

- Angular: 
- CDK/Material: @angular/cdk: 9.2.4, @angular/material:^9.2.4, @angular/google-maps: 10.2.7, @googlemaps/markerclustererplus: 1.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
The clusterer component was added in version 11.1.0 and it looks like you're on 10.2.7.
