### ISSUE TITLE
Make slider value non-nullable

### ISSUE THREAD

**Issue by thw0rted** [angular/components#22444]
#### Documentation Feedback

The linked docs give the type of `value` as `number | null` but the overview never describes a state when the value can actually be `null`.  They say "The initial value is set to the minimum value unless otherwise specified".

If the value actually can be `null`, an example of this should be provided.  If the value is never `null` (which seems to make more sense?) then the API should be updated so that `value` is simply `number`.

**Affected documentation page:** https://material.angular.io/components/slider/api

**Comment by crisbeto** [comment]
I think that a null can be assigned [here](https://github.com/angular/components/blob/master/src/material/slider/slider.ts#L870) if the `reset` method of the related `FormControl` is called. Changing the type shouldn't be a problem, but it could be considered a breaking change at this point.

**Comment by thw0rted** [comment]
That's interesting, it didn't occur to me that the default for `FormControl` must always be `null`.  Aren't there native controls whose value cannot be `null`?  I feel like this came up on another issue recently but I'm having trouble remembering which.

**Comment by crisbeto** [comment]
We've handled similar cases in other components by setting it to zero when `null` is passed in. It's just that updating the type now would be breaking.
