### ISSUE TITLE
Error in src/styles.css  - Error: ENOENT: No such file or directory.

### ISSUE THREAD

**Issue by AdamJow** [angular/components#22440]
Hi,
I have just encountered a sudden issue:

**Error in src/styles.css
Error: ENOENT: No such file or directory., '/dev/null'**

This suddenly started to happen.
There was no issue and my angular project we working just fine the all of a sudden the issue occurred without any changes to the project on my account.

It's like the following was suddenly unavailable:

@import '~@angular/material/prebuilt-themes/purple-green.css';

It feels like someone has moved the prebuilt-themes to another path?

Same issue happens in all my previous angular projects that uses the "@import '~@angular/material/prebuilt-themes/" .
They have been fine for a year now we have an issue?

Please try it yourself...   Simply add the following standard code  into your styles.css :

@import '~@angular/material/prebuilt-themes/purple-green.css';

**Comment by crisbeto** [comment]
It looks like you're trying to add the `@import` to a .css file which has a different meaning compared to a .scss file. This is likely an issue with your setup.
