### ISSUE TITLE
bug(mat-autocomplete): Using displayWith directive cause problem in input display

### ISSUE THREAD

**Issue by YehudahA** [angular/components#22457]
#### Reproduction

https://stackblitz.com/edit/matautocomplete-bug

This sample project is based on the [official demo](https://stackblitz.com/angular/gjvbjoypnqpx), with simple button to set the value of the ```FormControl```, using ```formControl.setValue``` method.
 
 ``` ts
    setValue(value: string){
      this.myControl.setValue(value);
   }
 ``` 

#### Expected Behavior

When I set the value of the FormControl, the input element should show the value.

#### Actual Behavior

The input is Empty.

### Remarks

The problem accour when the ```autocomplete``` source is a list are objects, and the ```autocomplete```  uses ```[displayWith]``` to display the value.
If a change the source to string, it works well.
 
#### Environment

- Angular:
- CDK & Material: 11.
- Browser: Chrome.

**Comment by geromegrignon** [comment]
As the goal of `displayWith` is to allow you to customize the behavior, it's your responsibility to handle each use case : 

```typescript
displayFn(user: User | string) {
    if (typeof user === "string") {
      return user;
    }
    return user && user.name ? user.name : "";
  }
```

**Comment by crisbeto** [comment]
@geromegrignon is correct, you should account for this in your function.
