### ISSUE TITLE
cdkTextareaAutosize throws when ng-content has *ngIf

### ISSUE THREAD

**Issue by aleixsuau** [angular/components#22469]
#### Reproduction

[StackBlitz example](https://stackblitz.com/edit/cdktextareaautosize-bug-can-not-read-appendchild)

Steps to reproduce:
1. Create a textarea with the cdkTextareaAutosize directive.
2. Create a wrapper component with a *ngIf for the projected content ```<ng-content *ngIf="true"></ng-content>```. It also happens with *ngTemplateOutlet, so probably it happens with any structural directive.
3. Wrap the textarea with the wrapper component ```<app-wrapper><textarea cdkTextareaAutosize></textarea></app-wrapper>```.
 
 
#### Expected Behavior

What behavior were you expecting to see?
It should project the textarea input into the wrapper ng-content tag and show it when *ngIf evaluates to true.

#### Actual Behavior

What behavior did you actually see?
It throws: ```ERROR TypeError: Cannot read property 'appendChild' of null...```

#### Environment

- Angular: Last
- CDK/Material: Last
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

**Comment by jelbourn** [comment]
`<ng-content>` isn't a real element, but is instead a compiler primitive that Angular's compiler uses to know where to insert projected content. Since it's not a real element, it can't have attributes/properties/directives. 

As an alternative, you can put `ngIf` on an `ng-container` around the `ng-content`.

**Comment by aleixsuau** [comment]
Hi @jelbourn ,

Thanks for your answer, I didn't know that.

I already tried with an ng-container and it throws too. I updated the [Stackblitz](https://stackblitz.com/edit/cdktextareaautosize-bug-can-not-read-appendchild).
