### ISSUE TITLE
bug(COMPONENT): How do I get the new position of a map marker in the mapDragend event?

### ISSUE THREAD

**Issue by IngoManthey** [angular/components#22461]
`<map-marker *ngIf = "marker"
    #markerElem
    [position]="marker.position"
    [label]="marker.label"
    [title]="marker.title"
    [options]="marker.options"
    (mapDragend)="mapDragend(markerElem)"
  >
  </map-marker>`

`mapDragend(marker: MapMarker) {
    const position = marker.getPosition();
    this.canSave = this.setData(position.lat(), position.lng());
  }`

Hiere I get the error marker.getPosition is not a function. What  can I do??

Regards Ingo

**Comment by crisbeto** [comment]
It's probably because the `#markerElem` is referring to the marker element node, not the `MapMarker` instance. You should change the `#markerElem` to `#markerElem="mapMarker"`.
