### ISSUE TITLE
docs-bug(stepper): misleading default icon documentation

### ISSUE THREAD

**Issue by oberbeck** [angular/components#22498]
#### Documentation Feedback

The stepper documentation says the default icons are 
```
`create` and `done`
```
but it seems to be
```
`edit` and `done`
```

**Affected documentation page:**
* https://material.angular.io/components/stepper/overview#overriding-icons
* [src/material/stepper/stepper.md](https://github.com/angular/components/blob/master/src/material/stepper/stepper.md)

**Comment by wagnermaciel** [comment]
The `edit` and `create` icons are identical - https://fonts.google.com/icons?selected=Material+Icons&icon.query=create

We don't have control over the material icons so I'm going to close this issue

**Comment by oberbeck** [comment]
In order to be able top overwrite an icon, one must know which icon to overwrite. Therefore it does matter.
