### ISSUE TITLE
feat(COMPONENT): pass the `Attribute` as a parameter 

### ISSUE THREAD

**Issue by bakkiung** [angular/components#22501]
#### Feature Description
pass the `Attribute` as a string parameter from the caller.
For example,  all the `Attribute` in https://material.angular.io/components/button/overview.

#### Use Case
Implementation of a wrapper component to wrap a mat button. The mat button needs to expose the attribute options to the caller without needing the caller/parent component knowing the existence of built in attribute.   (#information hiding)

**Comment by wagnermaciel** [comment]
We don't plan on implementing something like this any time soon. There are also potential workarounds where you could achieve this functionality without this added feature.
