### ISSUE TITLE
[Sort] sort direction not reading on IE11 + JAWS

### ISSUE THREAD

**Issue by chakravarthypasam** [angular/components#22516]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular-material

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes it used to work in angular V5.

### Description

 A clear and concise description of the problem...
Angular material table - sort direction not reading in screen reader. 
 MatSortHeaderIntl.sortDescriptionLabel is available in Angular V5 and its not available from V6. sortDescriptionLabel has an option to read the direction of the sort order(asc or dsc). Could someone please help fixing this issue or suggest a work around. Thanks in advance.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular V9

</code></pre>

**Anything else relevant?**

**Comment by jelbourn** [comment]
@chakravarthypasam which screen reader (and version)? Which browser (and version)? How did you interact with the sort-header: through screen-reader navigation or tab navigation?

**Comment by chakravarthypasam** [comment]
I'm using JAWS screen reader Version 2020.2012.13 ILM. The browser is IE 11 version 11.1139.18362.0. I used tab navigation to  interact with the header. When I tab over to the header JAWS announces the "column name" followed by "To change sorting hit Enter". When I click on enter it Just announces "Enter" but not the sorting order something like "Sorted Ascending or Descending".

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
