### ISSUE TITLE
bug(MatRipple): mat-ripple-element is not fired correctly on disable

### ISSUE THREAD

**Issue by cynthialong0-0** [angular/components#22520]
Working on resolving a bug that `MatRipple` stuck in the focus state. When on disable, sometimes the ripple cannot fade out the ripple in time. After investigation, it seems that there is opportunity when the `mouseup` event is not captured before setting to disable and `mat-ripple-element` is not fired correctly . 

#### Reproduce the error
[Live example in stackblitz](https://stackblitz.com/edit/angular-idn9y3?file=src%2Fapp%2Fbutton-ripple.ts)
##### Step to reproduce
1. Immediately click the icon button when move the cursor on it.
2. Try couple of times if you cannot see the state stuck after you move away the cursor.
3. Try more times after you reproduce it - you will see the color of the state becomes darker, since multiple `mat-ripple-element`s are not fired correctly.

![image](https://user-images.githubusercontent.com/82900738/115483284-56d0e900-a205-11eb-8672-c1e7a8d6e970.png)

#### Expected behavior
`mat-ripple-element` should be always deleted on mouse up 

#### Environment
Angular Material: 11.2.9
rxjs: 6.6.7
Browser: Chrome
Operating system: Mac

#### Fix
On disable, it should call `fadeOutAll()` method to make sure all `mat-ripple-element`s are fired. So I propose to have this change on the ripple `disabled` variable:
```typescript
  set disabled(value: boolean) {
    if (value) {
      this.fadeOutAll();
    }
    this._disabled = value;
    this._setupTriggerEventsIfEnabled();
  }
```

**Comment by jelbourn** [comment]
cc @devversion who I think was the last one to do major work on the ripple

Just to make sure I fully understand the reproduction- the issue is that the button becomes disabled after the ripple has been initiated, but before the ripple animation completes and the element is removed?

**Comment by cynthialong0-0** [comment]
> cc @devversion who I think was the last one to do major work on the ripple
> 
> Just to make sure I fully understand the reproduction- the issue is that the button becomes disabled after the ripple has been initiated, but before the ripple animation completes and the element is removed?

Yes I believe so.

**Comment by kseamon** [comment]
Relates to internal ticket 184573511
