### ISSUE TITLE
bug(google-maps): dragend event on Polygon listener breaks MatSnackBar

### ISSUE THREAD

**Issue by BrantOlsen** [angular/components#22533]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-47xjfu?file=src%2Fapp%2Fexample-component.ts

Steps to reproduce:
1. Create a polygon on the google-map.
2. Add a `dragend` listener that opens a snackbar message.
 
 
#### Expected Behavior

The snackbar to appear at the bottom of the screen then dismiss.

#### Actual Behavior

The snackbar opens in the top left and never goes away.

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because the Google Maps events run outside of the Angular zone. You should either wrap the callback in a `NgZone.run` call or use the `map-polygon` from the `@angular/google-maps` module which has a `polygonDragend` event that is wrapped automatically.
