### ISSUE TITLE
bug(cdk/scrollable): executing detect changes from element scrolled subscription breaks rendering

### ISSUE THREAD

**Issue by charsleysa** [angular/components#22547]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-5a9h1x?file=src/app/hello/hello.component.ts

Steps to reproduce:
1. click on any button with open share (fine), the bottom sheet will open as expected
2. scroll down and click on any button with open share (not fine), the bottom sheet will not render correctly and have large latencies when animating
 
 
#### Expected Behavior
Everything rendered correctly, no latency in animations.

#### Actual Behavior
Rendering is broken and animations have large latencies.

#### Environment

- Angular: 11.x
- CDK/Material: 11.x
- Browser(s): Edge 90
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Big Sur 11.2.3

**Comment by crisbeto** [comment]
It's because `elementScrolled` runs outside of the Angular zone in order to avoid triggering change detection for every pixel. You can fix it by adding an `NgZon.run` call around the logic that updates the view. See https://stackblitz.com/edit/angular-ivy-bwungz?file=src/app/hello/hello.component.ts.

**Comment by charsleysa** [comment]
@crisbeto thanks for the info! I should have known it would be something simple!

I noticed the docs don't mention this information for CdkScrollable.elementScrolled, is it possible for the docs to be updated so that all APIs that run outside of the Angular Zone are marked as such?
