### ISSUE TITLE
docs-bug(MatSelect): How to preselect options within a multi or single mat-select that relies on an Input() value?

### ISSUE THREAD

**Issue by omaracrystal** [angular/components#22556]
#### What are you trying to do?

I am trying to preselect items within a multi select (or single select). Currently, I am able to set the form value correctly, however the UI is not reflecting those values as selected.

#### What troubleshooting steps have you tried?

I have tried compareWith function to pull the display value. This compareWith function runs BEFORE any Inputs() are fully loaded. So the extractValue is undefined. If I hard code this value it still doesn't seem to solve my issue anyways.

#### What are you seeing that does not match your expectations? 

I expect the raw value of the control form set values to reflect in the UI.

#### Reproduction

- Code here on StackBlitz: https://stackblitz.com/edit/angular-mat-select-multi-with-formcontrol-klabfl?file=app%2Fselect-search-dropdown.component.html

- Stackoverflow: https://stackoverflow.com/questions/67238476/how-to-preselect-options-within-a-multi-or-single-mat-select-that-relies-on-an-i
  
#### Environment

- Angular: 10.2.1
- CDK/Material: 10.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by mmalerba** [comment]
Hi, thanks for the report. There's a lot going on in this Stackblitz which makes it difficult to pin down what the source of the error might be. Can you provide a more minimal reproduction that demonstrates the issue?

**Comment by omaracrystal** [comment]
Hello! 

I eventually got it to work with this as the compare function for multi select at least -->

```
  compareWithFn(optionOne: any, optionTwo: any): boolean {
    if (typeof optionOne === "string" && typeof optionTwo === "string") {
      return optionOne === optionTwo;
    } else {
      return _.isEqual(optionOne, optionTwo);
    }
  }
```

Because the object can be anything, I am using underscore library to compare the two objects to see if they are identical. Not sure why it doesn't work with single select though.

**Comment by mmalerba** [comment]
It looks like your `selectedOption` is being set as an array of options rather than a single option. Changing it to a single option fixes it: https://stackblitz.com/edit/angular-mat-select-multi-with-formcontrol-scmc9w?file=app%2Fmy-app%2Fmy-app.component.ts
