### ISSUE TITLE
docs-bug(MatFormField): custom form field example: why `MAT_FORM_FIELD` is injected

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22557]
#### Documentation Feedback

In the cusom form field [example](https://stackblitz.com/angular/lmgkeymermdg?file=src%2Fapp%2Fform-field-custom-control-example.ts) I see the line
```
@Optional() @Inject(MAT_FORM_FIELD) public _formField: MatFormField,
```
But the related [guide](https://material.angular.io/guide/creating-a-custom-form-field-control) say nothing about these injection.
Also from the code it's unclear why it's injected.  `_formField` is not used anywhere.

Could explain in the docs why it's injected? Or remove it if it's unnecessary

**Comment by annieyw** [comment]
Confirmed that the injection is not needed - probably leftover from something else and can just be removed. Feel free to send a PR to remove it.

**Comment by ammarnajjar** [comment]
I stumbled against this same issue and I would like to make a PR, if it's ok with you @AlexElin  @annieyw

**Comment by ammarnajjar** [comment]
as I was investigating more I found that  `_formField` is used indeed in the template here:

https://github.com/angular/components/blob/ad248652e7da31398176fe11878b59805e440b5a/src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html#L3

@annieyw would you please take another look into it?

**Comment by annieyw** [comment]
@ammarnajjar ah thanks for pointing it out, I must've missed it when I looked at the example initially. In that case `_formField` should be kept in.

Closing this as this is resolved.

**Comment by AlexElin** [comment]
@annieyw currently the [Improving accessibility](https://material.angular.io/guide/creating-a-custom-form-field-control#improving-accessibility) chapter is not aligned with the actual code.  
In the guide we see     `[attr.aria-labelledby]="parentFormField?.getLabelId()"`  
But the actual code is `[attr.aria-labelledby]="_formField?.getLabelId()"> `
Because of that a docs reader can't find anything by seacrhing `_formField` in the docs.
So a small change is required and the issue could be reopened
