### ISSUE TITLE
docs-bug(MatFormField): inconsistency between Custom form field guide and live example for `errorState`

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22558]
#### Documentation Feedback

In the [Custom form field guide]( https://material.angular.io/guide/creating-a-custom-form-field-control#errorstate ) the `errorState` is just set to `false`. 
But in the related [live example](https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fform-field-custom-control-example.ts) it has another implementation:

```
get errorState(): boolean {
    return this.parts.invalid && this.parts.dirty;
}
```

There's need to eliminate inconsistency between the guide and the live example

**Affected documentation page:** https://material.angular.io/guide/creating-a-custom-form-field-control#errorstate

**Comment by annieyw** [comment]
Confirmed that the guide should be updated to reflect the live example.
