### ISSUE TITLE
Angular Material - Is there a way to lazy load the expansion panel every time I open

### ISSUE THREAD

**Issue by aruntoday** [angular/components#22553]
#### Feature Description

The Mat expansion panel **(matExpansionPanelContent)** lazy loads the contents for the first time it opens, Is there a way to lazy load the expansion panel every time I open it.

#### Use Case
```
        <mat-expansion-panel [expanded]="'employee'== selectedValue.ID">
            <mat-expansion-panel-header>
                <mat-panel-title>
                    Employee
                </mat-panel-title>
            </mat-expansion-panel-header>
            <ng-template matExpansionPanelContent>
                <app-ter-employee></app-ter-employee>
            </ng-template>
        </mat-expansion-panel>
```
Describe the use case(s) that the proposed feature would enable.

**Comment by mmalerba** [comment]
If you want the DOM to be removed when the panel is collapsed, you can accomplish that using `*ngIf` like this: https://stackblitz.com/edit/angular-dnbvxz?file=src/app/expansion-overview-example.html
