### ISSUE TITLE
help(Mat-Form-Field): Angular Material components not displaying correctly

### ISSUE THREAD

**Issue by Utsav-Sharma33** [angular/components#22554]
![Screenshot (1)](https://user-images.githubusercontent.com/32520700/115921603-5781ad80-a499-11eb-87ea-981ddc5c769c.png)
![Screenshot (2)](https://user-images.githubusercontent.com/32520700/115921609-59e40780-a499-11eb-844e-d644c7d76509.png)

![Screenshot (3)](https://user-images.githubusercontent.com/32520700/115922142-248be980-a49a-11eb-8d5f-74a60dda7a83.png)

Github repository url : Utsav-Sharma33/material

I added a mat-form-field tag in my component but it is not rendering correctly. When not focussed, float-label is not showing. But on selection of matInput input tag , float label is showing. I am attaching screenshots.
`
const mat_modules = [
  MatFormFieldModule, MatInputModule, MatIconModule
]

const components = [
  FormFieldComponent,
]

@NgModule({
  declarations: [
    ...components
  ],
  imports: [
    CommonModule,
    ...mat_modules
  ],
  exports: [
    ...components
  ]
})
export class ComponentsModule { }
`

**Comment by annieyw** [comment]
Please include a stackblitz reproduction if possible. https://stackblitz.com/angular/brrjxjxxddab?file=src%2Fapp%2Fform-field-prefix-suffix-example.ts might be a good starting point.

From a quick glance, it seems like you might be missing the theme (https://material.angular.io/guide/theming)

**Comment by Utsav-Sharma33** [comment]
Github repository url : Utsav-Sharma33/material

**Comment by Utsav-Sharma33** [comment]
> Please include a stackblitz reproduction if possible. https://stackblitz.com/angular/brrjxjxxddab?file=src%2Fapp%2Fform-field-prefix-suffix-example.ts might be a good starting point.
> 
> From a quick glance, it seems like you might be missing the theme (https://material.angular.io/guide/theming)

Github repository url : Utsav-Sharma33/material

**Comment by Utsav-Sharma33** [comment]
Github repository url : Utsav-Sharma33/material

**Comment by mmalerba** [comment]
Yeah, as @annieyw mentioned, you don't seem to have either a custom Sass or prebuilt CSS theme added in that repo. Please read our theming guide for info about how to set that up: https://material.angular.io/guide/theming

**Comment by Utsav-Sharma33** [comment]
Resolved !! Thanks
