### ISSUE TITLE
index mismatch with scrolling and zooming with cdk-virtual-scroll-viewport

### ISSUE THREAD

**Issue by mclr47** [angular/components#22564]
#### Feature Description
https://stackblitz.com/edit/index-cdk

#### Use Case

The desired behavior: when cdk-virtual-scroll-viewport is scrolled to the top => index=0 , whereas scrolling to the very bottom the index = items.length, regardless of zooming in or out.
Please zoom in and out and observe the highlighted index,
, while scrolling all the way up and all the way down.
  
   cdk-virtual-scroll-viewport  as in the stackblitz with routerlink directive to fragments  added to each item will be used  to
create a toc [Table Of Content] to the page.

**Comment by annieyw** [comment]
Seems like the use case you are describing is out of scope for virtual scope. The goal of the virtual scroll is to replicate normal scrolling without rendering all the elements. You can maybe replicate this behaviour by adding invisible elements at the end that will allow the user to scroll down further.

**Comment by mclr47** [comment]
> #### Feature Description
> 
> https://stackblitz.com/edit/index-cdk
> #### Use Case
> 
> The desired behavior: when cdk-virtual-scroll-viewport is scrolled to the top => index=0 , whereas scrolling to the very bottom the index = items.length, regardless of zooming in or out.
> Please zoom in and out and observe the highlighted index,
> , while scrolling all the way up and all the way down.
> 
> cdk-virtual-scroll-viewport as in the stackblitz with routerlink directive to fragments added to each item will be used to
> create a toc [Table Of Content] to the page.

Thank you for looking into the issue. 
Let's make abstraction of the use case described above, since may not be the most compelling. 
 But,  how can I produce:  
_The desired behavior_: when cdk-virtual-scroll-viewport is scrolled to the top => index=0 , whereas scrolling to the very bottom the index = items.length, regardless of zooming in or out.
Of note :scrolling to the very bottom  the "active index" changes value by increasing with zooming in and even exceeds the "items.length" value, which is counterintuitive to me... why ?
.....since with my best effort I am not able to follow the advice given. A modified stackblitz would help me best understand and implement the desire behavior.
  Thank you !
