### ISSUE TITLE
Issue with matInput type="datetime-local" due to chrome update version 90

### ISSUE THREAD

**Issue by Clementinagurjar** [angular/components#22567]
Hi All,
Please suggest me some way to fix the below issue:
The date part of a datetime field is not getting highlighted as it used to do before when I clicked in the empty space in the text field.
This started to happen after new Chrome update to version 90.

**Comment by petebacondarwin** [comment]
Transferred to components repo

**Comment by crisbeto** [comment]
Can you post what your code looks like @Clementinagurjar? It seems to work for me on Chrome 90:
![demo](https://user-images.githubusercontent.com/4450522/116439259-a6d82d00-a84f-11eb-9fab-93de2d7c02cd.gif)

For reference, here's what I'm using:
```html
<mat-form-field>
  <mat-label>Test</mat-label>
  <input matNativeControl type="datetime-local">
</mat-form-field>
```

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback in a long time.
