### ISSUE TITLE
help(Datepicker): Datepicker not working with timestamp as input value with moment-date-adapter

### ISSUE THREAD

**Issue by jmelich** [angular/components#22568]
**What are you trying to do?**  
I trying to use timestamp as input value for mat-datepicker

**What are you seeing that does not match your expectations?** 
The date adapter is ignoring my parse configuration setted to "X" as [Moment Documentation](https://momentjs.com/docs/#/displaying/format/) says I have to set if input value is a timestamp. 

#### Reproduction
I attach this stackblitz where you can see the parse configuration for input is an "X" and the initial value is a timestamp which mat-datepicker can't recognize until I select the first value.

[https://stackblitz.com/edit/angular-evhhwk?file=package.json](https://stackblitz.com/edit/angular-evhhwk?file=package.json)

Steps to reproduce:
1. Open stackblitz and see initial value below mat-datepicker. It's supposed timestamp is supported but doesn't being recognized by datepicker
2. Select a date from picker and you can see it isn't doing conversion to the variable but display is showing the right timestamp.
  
#### Environment

- Angular: 11.0.0
- CDK/Material: 11.0.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

**Comment by mmalerba** [comment]
`MY_FORMATS.parse.dateInput` determines how _user_ input is parsed, not how programmatic input is interpreted. Instead you can create a moment object from your timestamp before passing it to the `FormControl`
