### ISSUE TITLE
docs-bug(Drag&Drop): Drag Events with typos

### ISSUE THREAD

**Issue by rafaeldcastro** [angular/components#22569]
#### Documentation Feedback

A series of events on the Drag & Drop documentation are mispelled. 
It indicates like:

cdkDragStart, cdkDragEnd or cdkDragMove

and the correct are:

cdkDragStart**ed**, cdkDragEnd**ed** or cdkDragMov**ed**

Don't know how many may be wrong. But I'm positive sure that you were already alerted on this issue.
So its just a reminder

**Affected documentation page:** https://material.angular.io/cdk/drag-drop/api#CdkDragMove

**Comment by crisbeto** [comment]
I don't think that they're typos. One is the name of the event and the other is its interface, they don't necessarily have to be the same. Furthermore, renaming them now would be a breaking change.
