### ISSUE TITLE
Issue(drag and drop): can`t handle scroll of list inside list

### ISSUE THREAD

**Issue by Katttori** [angular/components#22580]
Hello, i have a structure when my drag and drop list is inside another drag and drop list and i need to drop elements from the third list to second. Item from list 3 shouldn t be dropped inside list 1 but in list 2. However autoscroll of list 1 does not work when i drag item from list 3 so i ve implemented custom scroll. Then i`ve faced an issue when i scroll list 1 -  placeholder is not moved with cursor (i saw in native material autoscroll this issue resolved by resorting items and move placeholder for a diference in scroll). Is it possible to make this sorting available for material user?

`<mat-list #list1> `

` <mat-list-item>`
`<mat-list #list2> `
`</mat-list>`
`</mat-list-item>`

`</mat-list>`

`<mat-list #list3> `
`</mat-list>`

#### Reproduction

https://stackblitz.com/edit/angular-ui7u9m-5w9as5?file=src/app/cdk-drag-drop-disabled-sorting-example.html

Steps to reproduce:
1. drag item from second list to the green list 
2. scrol first list a bit while dragging 
3. see white placeholder not on the same line with dragged item

![Screenshot 2021-04-28 110528](https://user-images.githubusercontent.com/36365097/116369937-96559180-a812-11eb-83a9-cf36f75160bc.png)

**Comment by crisbeto** [comment]
We don't officially support nested lists at the moment. Closing as something that should be covered by https://github.com/angular/components/issues/16671.
