### ISSUE TITLE
MatTabGroup pagination chevron incorrect color when using backgroundColor property

### ISSUE THREAD

**Issue by MarkoSkugor** [angular/components#22587]
**What is the expected behavior?**
mat-tab-group pagination chevron should be correct contrast color

**What is the current behavior?**
https://stackblitz.com/angular/manempdpqjo?file=src%2Fapp%2Ftab-group-theme-example.ts

CSS selector for mat-tab-header-pagination-chevron is broken for mat-tab-group and only works for mat-tab-nav-bar

Screenshot from Angular Material docs example:
![image](https://user-images.githubusercontent.com/17053390/116463878-40481480-a839-11eb-9e5d-a04e235c9f78.png)

This selector specifically is broken as .mat-tab-header-pagination is not a direct child of .mat-tab-group
![image](https://user-images.githubusercontent.com/17053390/116463701-0119c380-a839-11eb-9045-454254440f01.png)

**What are the steps to reproduce?**
go to this stackblitz and shrink screen on blue background mat-tab-group until the pagination chevrons appear
https://stackblitz.com/angular/manempdpqjo?file=src%2Fapp%2Ftab-group-theme-example.ts

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
11 (confirmed this was working in 10), all browsers and OS affected

**Comment by jelbourn** [comment]
The issue here is with this CSS selector applies the desired border color when changing the background color:
```css
.mat-tab-group.mat-background-primary > .mat-tab-header-pagination .mat-tab-header-pagination-chevron
```

The problem is that `.mat-tab-header-pagination` is not a direct child of `.mat-tab-group`, `mat-tab-header` is in between.
