### ISSUE TITLE
bug(MapGeocoder): MapGeocoder not exported (+ others)

### ISSUE THREAD

**Issue by enrij** [angular/components#22594]
#### Reproduction

Steps to reproduce:
1. Create a new app
`ng new MyApp`

2. Install google-maps module
`npm install @angular/google-maps`

3. Import GoogleMapsModule in app.module.ts
`import { GoogleMapsModule } from '@angular/google-maps';`
`imports: [
    BrowserModule,
    GoogleMapsModule
  ],`

4. In the app.component.ts import the MapGeocoder
`import {MapGeocoder} from '@angular/google-maps';`

#### Expected Behavior

inject MapGeocoder

#### Actual Behavior

Error: Module '"@angular/google-maps"' has no exported member 'MapGeocoder'.

#### Environment

- Angular: 11.2.9 (core),
- CDK/Material: 11.2.11 / 11.2.11
- Browser(s): Edge (Chromium) / Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 x64 20H2

#### Notes
- The same applies for MapDirectionsService
- <map-direction-renderer> cannot be placed inside a <google-map> component along with other components. There the available ones:

![image](https://user-images.githubusercontent.com/13519234/116578511-c899e880-a911-11eb-8bb0-bdadf14ecb45.png)

**Comment by jelbourn** [comment]
This feature is added in v12 (see the commit tags):
https://github.com/angular/components/commit/86251af444874fc5e1be8f4aa20d203c15b211a5
