### ISSUE TITLE
bug(radio): Ripple effect does not fade out after clicking radio button

### ISSUE THREAD

**Issue by mdickopp** [angular/components#22593]
When clicking on a radio button, the ripple effect does not fade out as it does for checkboxes. I would expect radio buttons and checkboxes to behave the same in this regard, i.e., the ripple effect to fade out.

#### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/radio/overview
2. Click on “Option 1”
 
 
#### Expected Behavior

When clicking the radio button, the ripple effect should first appear and then fade out.

#### Actual Behavior

When clicking the radio button, the ripple effect (light pink circle in the screenshot) appears and remains visible.

![mat-radio-ripple](https://user-images.githubusercontent.com/19174977/116546226-a7c19b00-a8f1-11eb-8709-7183da178f68.png)

#### Environment

- Angular: 11.2.10
- CDK/Material: 11.2.9
- Browser(s): Firefox 88.0, Chromium 89.0.4389.114
- Operating System (e.g. Windows, macOS, Ubuntu): Debian Linux 11

**Comment by Totati** [comment]
Hi. That's the focus indicator. https://github.com/angular/components/issues/14349

**Comment by mdickopp** [comment]
#13544 suggests that the focus indicator should only remain visible when the elements has been focused by keyboard or programmatically (in particular https://github.com/angular/components/issues/13544#issuecomment-428873172).

It seems inconsistent to me that radio buttons and checkboxes behave differently in this regard. Is this really intended?

**Comment by jelbourn** [comment]
This is working as intended, see the canonical example in the Material spec:
https://material.io/components/selection-controls
