### ISSUE TITLE
help(google-maps/polygon): googlemaps-polygon draw live

### ISSUE THREAD

**Issue by SathishS90** [angular/components#22601]
Ive tried to update the LatLngLiteral[] for the polygon draw in the google map, it only loads preloaded value,

need help to update the polygon selection to be updates after each select, followed the document, but still it only loads after page refresh.

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
