### ISSUE TITLE
help(MatBottomSheet): the scroll event failed to be fired in a bottom sheet

### ISSUE THREAD

**Issue by DukeCaesar** [angular/components#22602]
#### What are you trying to do?

I am trying to detect the scroll event in a bottom sheet.

#### What troubleshooting steps have you tried?

It seems that the scroll event could not be detected in a bottom sheet.

#### Reproduction

Steps to reproduce:
1. Opens a bottom sheet in a component:
`const bottomSheetRef = this.bottomSheet.open(MyComponent);`
2. Attach a scroll event to the top div element in the  component
`<div id="comment-list-div" (scroll)="onScroll($event)">`
`some overflow content here`
`</div>`

3. try to detect the scroll event in the component
`onScroll(event: any) {
   console.log('onScroll function has been called.');
}`

#### Environment

- Angular:11.2.4
- CDK/Material:11.2.4
- Browser(s):Firefox, 88.0 (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
We don't do anything special that would prevent the scroll event from firing. What could be happening is that an element different from your `comment-list-div` is actually the one being scrolled, but it's hard to tell without a reproduction.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.

(this is a canned response)
