### ISSUE TITLE
Dialog component is not modal when used as in Documentation

### ISSUE THREAD

**Issue by akloster** [angular/components#22620]
#### Documentation Feedback

I am trying to implement a modal popup dialog. I am trying to follow the documentation about the dialog component. And so far I am managing to show a pop up dialog, which animates in and out, and is somewhat styled, but it does not gray out the background and does not disable the rest of the page as expected. I can instantiate multiple instances of the dialog which add up one after the other. I also tried setting "hasBackdrop" to both false and true, to no avail. 

I am new to Angular Material so I lack the ability to recreate the issue on StackBlitz.

I would further suggest to document options like "hasBackdrop", "width", "height", and others implicitly. There seem to be quite a few of them in the source code.

**Comment by crisbeto** [comment]
The dialog has a backdrop by default so it sounds like you're missing some styles. Most likely you haven't included a theme in your app. There's some more information in the theming guide: https://material.angular.io/guide/theming

**Comment by akloster** [comment]
Thank you, that was what I was missing.
