### ISSUE TITLE
bug(Mat Select): Mat Checkbox added inside Mat Select is not operable using keyboard

### ISSUE THREAD

**Issue by omkarshinge** [angular/components#22639]
#### Reproduction

Use StackBlitz to reproduce issue: 
URL : https://stackblitz.com/edit/angular-ivy-fksjwl

### Note : 
Currently Mat Select is not having checkbox to select all elements / options in multiple selection mode (We have Ctrl +a key combination) but our use case require us to have a checkbox to check / uncheck all options.
The feature request [#9149](https://github.com/angular/components/issues/9149) may eliminate this issue for us.

Steps to reproduce:
(Use keyboard to perform all operations)
1. Traverse till Mat Select using tab/ Shift+tab key combinations.
2. Open the Mat Select dropdown using Enter / Space key.
3. Check that focus is on the Mat Checkbox that we have added.
4. Try checking that Select All check box using Enter or Space key
 
 
#### Expected Behavior :
Select All checkbox that we have added should be able to check / uncheck.

#### Actual Behavior :
Select All checkbox that we have added doesn't get checked / unchecked even though after opening the dropdown the focus is on the Select All checkbox (Mat Checkbox) that we have added.

#### Environment :

- Angular: 10.2.3
- CDK/Material: 11.0.2
- Browser(s): Chrome / Firefox / Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is intentional (note how the element is called `mat-pseudo-checkbox` instead of `mat-checkbox), because the select follows the `combobox` pattern. The checkbox is purely decorative and isn't meant to be something that the user interacts with. Also the `combobox` pattern uses the arrow keys to navigate, rather than tabbing.
