### ISSUE TITLE
mat-slide-toggle default disabled value

### ISSUE THREAD

**Issue by ranouf** [angular/components#22638]
Hi,

I try to get "false" when the toggle is disabled currently I have a "null".

I found here that this is supposed to overwrite the default value:
https://stackoverflow.com/questions/56108213/how-to-disable-the-drag-option-on-angular-material-slide-toggle-component

```
import { MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS } from '@angular/material';

@Component({
  selector: 'app-selector',
  templateUrl: './template.html',
  providers: [
    {provide: MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS , useValue: {disableToggleValue: false, disableDragValue: true}},
  ]
})
```

But I continue to get null when it's inactived and true when it's activated.

Any Idea?

**Comment by ranouf** [comment]
I need to use this line in the module where I load the MatSlideToggleModule to make it works

**Comment by crisbeto** [comment]
This isn't something that we support at the moment. The `disableToggleValue` is used to prevent the value from being changed and it defaults to `false`.

**Comment by ranouf** [comment]
thanks :)
