### ISSUE TITLE
bug(MatInput): aria-invalid is not set to true when the input is invalid

### ISSUE THREAD

**Issue by pongells** [angular/components#22635]
#### Reproduction

Steps to reproduce:
1. go to https://stackblitz.com/angular/xonvlpvdlxg
2. focus and blur the input
 
 
#### Expected Behavior

The `input` element should automatically have `aria-invalid` set to true (as per documentation).

#### Actual Behavior

`aria-invalid` remains `false`

#### Environment

- Angular: 11.2.12
- CDK/Material: 11.2.12
- Browser(s): firefox, chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
The value will be changed as soon as you type into the input. This is done on purpose to reduce noise for screen reader users. See https://github.com/angular/components/pull/21609.
