### ISSUE TITLE
help(DRAG AND DROP): Change standard DropList behavior after drop an item

### ISSUE THREAD

**Issue by rafaeldcastro** [angular/components#22655]
#### What are you trying to do?

I have dropList working as big scale dropzone. For this master list children, I'm tracking where they're being dropped and applying their *transformation(position)* values to *fix* their position on the dropzone.

I want to rely on the useful behavior of droplists, but although the elements retain their x/y translate positions, as soon as I move a second element inside the master list. The standard list behavior kick in and clear my transformation values e align all the elements within a list format.

*I just want to know if there is a way to stop the cdkDropList process of list alignment and force a "free" drag drop behavior for its children?*

**Comment by jelbourn** [comment]
https://material.angular.io/cdk/drag-drop/overview#cdk-drag-drop-overview shows how to do free drop/drop. Does that cover what you're trying to do? It's not clear why you would want a drop-list (which doesn't auto-alignment) and _also_ free-drag. or how you would expect it to work

**Comment by rafaeldcastro** [comment]
@jelbourn I made the same question on stackoverflow with more details. Gonna copy/paste here :D

**Stackoverflow question:** [How to change an Angular Material CdkDroplist behavior to emulate a “free” dropzone?
](https://stackoverflow.com/questions/67524084/how-to-change-an-angular-material-cdkdroplist-behavior-to-emulate-a-free-dropz)

> The goal is to make a full-width dropzone. In wich I can drop "widgets" and drag them freely around the dropzone. But the twist is that I can also drop list widgets, in wich I can drop other widgets as well..
>
> So I have this [stackblitz](https://stackblitz.com/edit/angular-free-dropzone-list?file=src/app/app.component.html) with the code, and [this video](https://www.youtube.com/watch?v=54uPoZwbfmI&ab_channel=RafaeldeCastro) showing the strange behavior
> 
> Any help? I could remove the cdkdroplist directive and assume everything as a Draggable item but will lost the list features on the elements...
> 
> Same problem as other [this guy](https://stackoverflow.com/questions/58566122/how-do-i-use-cdkdroplist-with-free-drag-cdkdrag-elements) in stackoverflow


**app.component.html**

```
<div
      cdkDropList
      id="todo"
      [cdkDropListData]="todo"
      [cdkDropListConnectedTo]="widgetIds"
      class="example-list board"
      (cdkDropListDropped)="drop($event)">
    
        <div class="example-box widget item{{item.id}}"
          id="item{{item.id}}" 
          *ngFor="let item of todo" 
          cdkDrag
          (cdkDragReleased)="cdkDragReleased($event, item)"
          [cdkDragData]="item"
          [ngStyle]="{
                    'transform': 'translate3d('+ item.dragPosition.x +'px,'+ item.dragPosition.y +'px,'+ item.dragPosition.z +'px)'
                }">{{item.label}}</div>
    </div>
    
    <div class="example-container widget widget-a">
      <h2>In Progress</h2>
    
      <div
        cdkDropList
        id="inprogress"
        [cdkDropListData]="inprogress"
        [cdkDropListConnectedTo]="widgetIds"
        class="example-list"
        (cdkDropListDropped)="drop($event)">
        <div class="example-box item{{item.id}}"
          id="item{{item.id}}" 
          *ngFor="let item of inprogress" 
          cdkDrag
          (cdkDragReleased)="cdkDragReleased($event, item)"
          [cdkDragData]="item">{{item.label}}</div>
      </div>
    </div>
    
    <div class="example-container widget widget-b">
      <h2>Done</h2>
    
      <div
        cdkDropList
        id="done"
        [cdkDropListData]="done"
        [cdkDropListConnectedTo]="widgetIds"
        class="example-list"
        (cdkDropListDropped)="drop($event)">
        <div class="example-box item{{item.id}}"
          id="item{{item.id}}" 
          *ngFor="let item of done" 
          cdkDrag
          (cdkDragReleased)="cdkDragReleased($event, item)"
          [cdkDragData]="item">{{item.label}}</div>
      </div>
    </div>

```
**app.component.ts**
```
export class AppComponent {
      widgetIds = ['todo', 'inprogress', 'done'];
    
      todo = [
        { id: 1, label: 'Item 1', dragPosition: { x: 45, y: 549, z: 0 } },
        { id: 2, label: 'Item 2', dragPosition: { x: 190, y: 236, z: 0 } },
        { id: 5, label: 'Item 5', dragPosition: { x: 93, y: 142, z: 0 } }
      ];
    
      inprogress = [
        { id: 3, label: 'Item 3', dragPosition: { x: 0, y: 0, z: 0 } },
        { id: 6, label: 'Item 6', dragPosition: { x: 0, y: 0, z: 0 } },
        { id: 7, label: 'Item 7', dragPosition: { x: 0, y: 0, z: 0 } }
      ];
    
      done = [
        { id: 4, label: 'Item 4', dragPosition: { x: 0, y: 0, z: 0 } },
        { id: 8, label: 'Item 8', dragPosition: { x: 0, y: 0, z: 0 } }
      ];
    
      constructor() {}
    
      drop(event: CdkDragDrop<any>) {
        if (event.previousContainer === event.container) {
          moveItemInArray(
            event.container.data,
            event.previousIndex,
            event.currentIndex
          );
        } else {
          transferArrayItem(
            event.previousContainer.data,
            event.container.data,
            event.previousIndex,
            event.currentIndex
          );
        }
      }
    
      cdkDragReleased(event: CdkDragRelease<any>, item) {
        const widDomElement: any = document.querySelector(`.item${item.id}`);
        const el: any = document.querySelector(`.cdk-drag-preview.item${item.id}`);
        let arrT = el.style.transform
          .replaceAll('px', '')
          .replaceAll(' ', '')
          .replaceAll(')', '')
          .replaceAll('translate3d(', '')
          .split(',');
    
        item.dragPosition = {
          x: Number(arrT[0]),
          y: Number(arrT[1]),
          z: Number(arrT[2])
        };
      }
    }

**Comment by wagnermaciel** [comment]
@rafaeldcastro I believe this issue was resolved in https://github.com/angular/components/commit/7508f46e7d1fd2eb0c20fdf8b913aacfcad5ea5a. Does this issue persist for you?
