### ISSUE TITLE
Column resizing and reordering is not working together when we apply both functions on a same material table

### ISSUE THREAD

**Issue by BhagyashreeCH** [angular/components#22662]
I am using angular material table to perform column sorting and resizing, both are working fine, if I add column re-ordering(drag and drop) for the same as mentioned here https://material.angular.io/components/table/examples#table-reorderable , column reordering works but not able to perform resize operation after this.

please provide your inputs. 

Thanks in advance.

**Comment by crisbeto** [comment]
Can you post a reproduction? It hard to guess what could be going wrong without one.

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.
