### ISSUE TITLE
bug(mat-datepicker): Datepicker input doesn't clear on invalid value

### ISSUE THREAD

**Issue by sarkar-aniket** [angular/components#22663]
When I enter invalid text in the date input, the control value goes null but the datepicker input is not cleared of the invalid value.

#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-z7nui6?file=src%2Fapp%2Fdatepicker-overview-example.ts

Steps to reproduce:
1. Open the above stackblitz link
2. In the date field, input an invalid value like "31-31-2001" and tab out
3. The formcontrol goes to an invalid state, the value becomes null but the input still shows the invalid value
 
 
#### Expected Behavior

On entering an invalid value, the input should be cleared as the control value is null.

#### Actual Behavior

The control value is null, but the invalid value is still shown on the screen

#### Environment

- Angular: 11.2.13
- CDK/Material: 11.2.12
- Browser(s): Edge, Chrome, Firefox

**Comment by jelbourn** [comment]
@mmalerba this seems familiar- I vaguely recall this is intentional with the way that angular forms works, right?

**Comment by crisbeto** [comment]
This behavior is intentional. If we were to clear the input when an invalid value is entered, the user won't have the chance to correct their mistake.

**Comment by sarkar-aniket** [comment]
User can correct their mistake if they are there in the same date picker field. But once they move to some other field in the form the value remains. Due to this many times, it gives a notion to the user that the value is provided but when the form is submitted null value goes.

**Comment by crisbeto** [comment]
This is why the form field has invalid indication of the form of a red border/red text.

**Comment by sarkar-aniket** [comment]
Thanks a lot! I also noticed now that the form control has **matDatepickerParse** error which can also be shown to the user.
