### ISSUE TITLE
feat(table): Improve CdkTable keyboard accessibility when combined with MatSort

### ISSUE THREAD

**Issue by davidhicks980** [angular/components#22667]
#### Feature Description
A way to easily access MatSort within the template when used in conjunction with cdk-header-cell 

#### Use Case
Improve the implementation of CdkTable navigation for users.

### Additional Detail
When using MatSort, an accessible sort header can be conveniently added to CdkTable. However, when implementing arrowkey accessibility per [W3's datatable example](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html#),  it is hard to listen to keydown events from the sort header within the table template. It would be nice to have an easier way to control keydown events on the sort headers.

Also, this is my first feature request, so sorry in advance if I did something wrong!

**Comment by crisbeto** [comment]
What makes it difficult to listen to keydown events? It's a little hard to tell without knowing what you're trying to do.

**Comment by davidhicks980** [comment]
That’s a great question.  I’m trying to implement a roving tabindex on CdkHeaderCell or MatSort (one or the other). For grids requiring a roving tabindex, I have been using a directive (the directive specifies the 2d coordinates of a cell within a table, and pressing the arrow key moves the focus and tabindex by querying the proper coordinates). The issue that I’ve run into is that every MatSort directive appends div elements that have a tabindex of 0. Because there is no direct DOM access to the MatSort directive, I’m currently listening for changes to MatSort via @ViewChildren and setting the tabindex of each MatSort header to -1. If there was direct DOM access to MatSort, I would imagine it would be easier to implement keyboard-accessible tables, but I also could be going about this the wrong way?  I hope this makes sense – and no worries if not…  From: Kristiyan KostadinovSent: Wednesday, 12 May 2021 2:21 amTo: angular/componentsCc: davidhicks980; AuthorSubject: Re: [angular/components] feat(COMPONENT): Improve CdkTable keyboard accessibility when combined with MatSort (#22667) What makes it difficult to listen to keydown events? It's a little hard to tell without knowing what you're trying to do.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
