### ISSUE TITLE
bug(RadioButton): TabIndex ignored

### ISSUE THREAD

**Issue by IanIsFluent** [angular/components#22674]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-fopvu4?file=src/app/example-component.html

Steps to reproduce:
1. Use tabindex on a mat-radio-button
2. Its set to 0 or -1
 
 
#### Expected Behavior

The tabindex work

#### Actual Behavior

The tabindex didn't work

#### Environment

See stackblitz

**Comment by jelbourn** [comment]
This is working as intended. `MatRadioButton` internally manages the tabindex on its internal native `<input type="radio">`. We don't support customizing this tabIndex.

**Comment by IanIsFluent** [comment]
@jelbourn Can I change this to a feature request with the text: support customising tabindex then? :)
