### ISSUE TITLE
I am getting following error when I run ng serve 

### ISSUE THREAD

**Issue by kushalbajje** [angular/components#22671]
node_modules/@angular/material/core/option/optgroup.d.ts:17:22 - error TS2420: Class '_MatOptgroupBase' incorrectly implements interface 'CanDisable'.
      Property 'disabled' is missing in type '_MatOptgroupBase' but required in type 'CanDisable'.
    
    17 export declare class _MatOptgroupBase extends _MatOptgroupMixinBase implements CanDisable {
                            ~~~~~~~~~~~~~~~~
    
      node_modules/@angular/material/core/common-behaviors/disabled.d.ts:12:5
        12     disabled: boolean;
               ~~~~~~~~
        'disabled' is declared here.
    node_modules/@angular/material/button/button.d.ts:22:22 - [91merror TS2420: Class 'MatButton' incorrectly implements interface 'CanColor'.
      Type 'MatButton' is missing the following properties from type 'CanColor': color, defaultColor
    
    22 export declare class MatButton extends _MatButtonMixinBase implements AfterViewInit, OnDestroy, CanDisable, CanColor, CanDisableRipple, FocusableOption {
                            ~~~~~~~~~
    node_modules/@angular/material/button/button.d.ts:22:22 - error TS2420: Class 'MatButton' incorrectly implements interface 
'CanDisable'.
      Property 'disabled' is missing in type 'MatButton' but required in type 'CanDisable'.
    
    22 export declare class MatButton extends _MatButtonMixinBase implements AfterViewInit, OnDestroy, CanDisable, CanColor, CanDisableRipple, FocusableOption {
                            ~~~~~~~~~

**Comment by kushalbajje** [comment]
> I notice you are using `"@angular/material": "github:angular/material2-builds",`
> I am going to transfer this to the `components` repo, since it doesn't appear to be related to the core framework.
> But to get a faster resolution to this issue, I would recommend sharing a minimal reproduction of this error, removing any 3rd party libraries from the setup.

I removed node modules and I ran npm install commdan from that point I am getting the above mentioned errors.

I believe it's because of typescript version, the current stable version of typescript is 4.2.4 but application throws a error saying typescript version should be >= 4.0.0 and  < 4.1.0

When I downgrade the typescript version to 4.0.2 I am getting TS1005 error which is typescript syntax error, I don't know how to resolve this, could you help me with this.

Thanks
Kushal Bajje

**Comment by kushalbajje** [comment]
But I still didn't get the answer!

**Comment by kushalbajje** [comment]
If I run ng serve for the first time I get the following erros.


Error: node_modules/@angular/material/core/common-behaviors/constructor.d.ts:14:
64 - error TS1005: ';' expected.

14 export declare type AbstractConstructor<T = object> = abstract new (...args:
any[]) => T;
                                                                  ~~~
node_modules/@angular/material/core/common-behaviors/constructor.d.ts:14:69 - er
ror TS1109: Expression expected.

14 export declare type AbstractConstructor<T = object> = abstract new (...args:
any[]) => T;
                                                                       ~~~
node_modules/@angular/material/core/common-behaviors/constructor.d.ts:14:82 - er
ror TS1011: An element access expression should take an argument.

14 export declare type AbstractConstructor<T = object> = abstract new (...args:
any[]) => T;


node_modules/@angular/material/core/common-behaviors/constructor.d.ts:14:83 - er
ror TS1005: ';' expected.

14 export declare type AbstractConstructor<T = object> = abstract new (...args:
any[]) => T;

     ~
node_modules/@angular/material/core/common-behaviors/constructor.d.ts:14:85[0m -
 error TS1128: Declaration or statement expected.

14 export declare type AbstractConstructor<T = object> = abstract new (...args:
any[]) => T;

After this, once I saved app.module.ts file it will give the previously mentioned errors.

Can anyone help me with this, I am new to angular.

**Comment by crisbeto** [comment]
It looks like your TypeScript version is too old. Material requires at least version 4.2. Have you tried updating to it?

**Comment by kushalbajje** [comment]
I found the fix for this issue, the actual problem was with the angular material version 12.0.0 and the typescript version should be above 4.0.0 and less than 4.1.0.
