### ISSUE TITLE
feat(MatTooltip): HTML support, at last?

### ISSUE THREAD

**Issue by inad9300** [angular/components#22672]
#### Feature Description

It can be found in any of:
- https://github.com/angular/components/issues/19367
- https://github.com/angular/components/issues/17082
- https://github.com/angular/components/issues/6515
- https://github.com/angular/components/issues/5672
- https://github.com/angular/components/issues/5440
- https://github.com/angular/components/issues/3676
- https://github.com/angular/components/issues/3566

#### Use Case

An image is worth more than a thousand words... (Notice the bold text and the different colors used. In case it wasn't clear, this is from Google Chrome.)

<img width="300" alt="chrome-tooltip" src="https://user-images.githubusercontent.com/3440331/117950551-975ae880-b313-11eb-8943-ead924d5ccef.png">

Honestly, the reasons given so far for not supporting HTML in tooltips just don't seem to be strong enough. It's fine that a guideline recommends not to abuse this feature, but enforcing it for everybody all the time is too restrictive. It sounds a bit pitiful when put into words, but please allow us to use HTML in the web... The other main argument seems to be that this affects accessibility, but this believe hasn't been well explained. If having plain text inside a tooltip is not seen as a problem, I don't see how having a `<b>` tag can be.

**Comment by jelbourn** [comment]
This article does a good job of explaining why allowing arbitrary content in a tooltip is problematic for accessibility:
https://sarahmhigley.com/writing/tooltips-in-wcag-21/

Ultimately, this is a feature we don't intent to support directly in `matTooltip` for a combination of design, a11y, and code complexity. However, `cdk/overlay` provides all the heavy lifting for implementing a custom tooltip that can support arbitrary content.

**Comment by inad9300** [comment]
Thanks for sharing the article, it is an interesting read.

In particular with regards to rich HTML content inside elements referenced by `aria-describedby`, claims are made but no evidence is provided. If a screen reader interprets (e.g.) `<strong>` outside such elements, I don't see how it will fail to do so inside them (I'm not saying they always do, but I don't think anyone is suggesting to stop using `<strong>` altogether either).

On the other hand, the [ARIA specification](https://www.w3.org/TR/wai-aria-1.1/#aria-describedby) does mention that multiple HTML elements are allowed to be contained inside elements referenced by `aria-describedby` (emphasis mine):
> The element or elements referenced by the aria-describedby comprise the entire description. Include ID references to multiple elements if necessary, **or enclose a set of elements (e.g., paragraphs) with the element referenced by the ID**.

The argument about code complexity is not appreciated either. If it really is that complex, it would be nice if the library took care of it for users, given how close it is to doing so anyway. Furthermore, `cdk/overlay` is a huge step back in accessibility, as it lacks `aria-describedby` and other basic tooltip-oriented interactions.

If you cannot figure out a good (API) design for this or how to integrate it into your code base, it seems more appropriate to mark the issue with "help wanted", instead of just dismissing it.
