### ISSUE TITLE
feat(MatTreeModule): Material Tree data structure

### ISSUE THREAD

**Issue by ishanuda** [angular/components#22688]
#### Feature Description

Adding a flat array to consume by the tree module with out using child array.

Provide a brief summary of the feature you would like to see.

Using a uid (Unique ID of the tree item) and the pid (Parent ID of the tree item).
uid continues form 0 to the length of the array.
pid is the parent id of any other existing item of the tree, if the item needs to be a child item.
pid can be kept as (-1) making the item as the root node of the item list

#### Use Case

```
const tree = [

  // 1st root node of the list with child items referred by the pid
  {
    uid: 0,
    pid: -1, // no parent id
    title: 'Parent item 1',
  },
  {
    uid: 1,
    pid: 0,
    title: 'Child item 1 of parent item 1',
  }
  {
    uid: 2,
    pid: 1,
    title: 'Child item 2 of child item 1',
  }

  // 2nd root node of the list with its child items referred by the pid
  {
    uid: 3,
    pid: -1, // no parent id
    title: 'Parent item 2',
  },
  {
    uid: 4,
    pid: 3,
    title: 'Child item 1 of parent item 2',
  },
  ....
]
```

Describe the use case(s) that the proposed feature would enable.

Using a flat array it is easy to filter and to reach an item very easily in order to highlight a particular item in the tree as an active tree item.

**Comment by jelbourn** [comment]
It's not really clear what you're requesting here. The tree already supports accepting a flat array as a data source where you specify the indent level for each item.

**Comment by ishanuda** [comment]
Hi @jelbourn,

I see a flat node with an array that is still having child arrays.

My idea is here not to depend on a child arrays, but to build the relationship with the uid and pid to separate the child elements.

[Example](https://stackblitz.com/edit/angular-ivy-zk9lzx?file=src%2Fapp%2Fapp.component.ts)

I just created the example to show you the array structure but there may be problems with the implementation.
Please just consider about the array structure.

Thank you very much.
