### ISSUE TITLE
bug(cdk/overlay): cdkConnectedOverlay closes on escape even when another overlay is open

### ISSUE THREAD

**Issue by igodorogea** [angular/components#22694]
#### Reproduction

StackBlitz to reproduce: 
- https://stackblitz.com/edit/mat-menu-escape-key-issue?file=src/app/menu-overview-example.html

Steps to reproduce:
1. Open overlay
2. Open menu
3. Press Escape
 
 
#### Expected Behavior

Only menu is closed, overlay stays open.

#### Actual Behavior

Overlay and menu are both closed.

#### Environment

- Angular: 11.2.x - 12.0.0
- CDK/Material: 11.2.x - 12.0.0
- Browser(s): Chrome, Opera, FF, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This is specifically the behavior of  the `cdkConnectedOverlay` directive, which always closes on escape without doing any extra checking. To work around, you could manually use the `Overlay` service which gives more control over the escape behavior. Alternatively, you can set `disableClose` on `cdkConnectedOverlay` and either conditionally re-enable it or manually close on escape.

**Comment by igodorogea** [comment]
@jelbourn are you sure that this is a bug in `cdkConnectedOverlay`?
There is no such issue with `autocomplete` or `datepicker`.
Both of them are somehow stopping Escape propagation.
Shouldn't `menu` do the same?

**Comment by jelbourn** [comment]
I see- it looks like it could be fixed on either side, then.
