### ISSUE TITLE
docs-bug(CODING_STANDARDS): Guide for booleans are contradictive.

### ISSUE THREAD

**Issue by andreElrico** [angular/components#22717]
#### Documentation Feedback

https://github.com/angular/components/blob/master/CODING_STANDARDS.md

you write:

> Except for @Input properties, use is and has prefixes for boolean properties / methods.

a little bit above we have an example:

```
  /** Whether the button is disabled. */
  disabled: boolean = false;
```

I guess this is meant to be an Input,

So I guess @Input() should be added, or `is` should be added to disabled (`isDisabled`);

**Comment by jelbourn** [comment]
Yeah, that example is only meant to demonstrate the comment; something like `disabled` would be an `@Input` property.
