### ISSUE TITLE
bug(slider): thumb out of sync after drag cancelled

### ISSUE THREAD

**Issue by lucasmaj** [angular/components#22719]
#### Reproduction
Steps to reproduce:
1. Start dragging the thumb with mouse. 
2. Just before releasing mouse button press ESC key.
3. Thumb remains on new position while model value still has value before drag started. 
 
 
#### Expected Behavior
When ESC is pressed, indicating cancelling the drag action, the thumb should come back to position before drag started, thus thumb position and value remains in sync.

#### Actual Behavior

Thumb position is not in sync with model value.

#### Environment

- Latest demo pages,
- Chrome Windows

**Comment by jelbourn** [comment]
I kind of wonder why we abort value updates on escape at all. It seems a bit strange for the combination of active pointer event and keyboard event.

**Comment by lucasmaj** [comment]
Yes, that would work as well I think to just ignore ESC.
