### ISSUE TITLE
bug(COMPONENT): DOMException when using matInput and type="time" on ios

### ISSUE THREAD

**Issue by AdditionAddict** [angular/components#22726]
I'm getting the following error when using matInput and type="time" on ios

#### Error

> Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable

#### Use

```
  <mat-form-field class="onmachinetime">
      <input type="time" matInput placeholder="On Machine Time" formControlName="onmachinetime" />
   </mat-form-field>
```

It looks like this is caused by the following code in `src/material/input/input.ts` as `setSelectionRange` is not applicable for a time input. 

Note you doen't need ios device to reproduce the error - using Firefox > Resonsive Design Mode (Ctrl + Shift + M) also gives the error
```
        // On some versions of iOS the caret gets stuck in the wrong place when holding down the delete
        // key. In order to get around this we need to "jiggle" the caret loose. Since this bug only
        // exists on iOS, we only bother to install the listener on iOS.
        if (_platform.IOS) {
            ngZone.runOutsideAngular((/**
             * @return {?}
             */
            () => {
                _elementRef.nativeElement.addEventListener('keyup', (/**
                 * @param {?} event
                 * @return {?}
                 */
                (event) => {
                    /** @type {?} */
                    let el = (/** @type {?} */ (event.target));
                    if (!el.value && !el.selectionStart && !el.selectionEnd) {
                        // Note: Just setting `0, 0` doesn't fix the issue. Setting
                        // `1, 1` fixes it for the first time that you type text and
                        // then hold delete. Toggling to `1, 1` and then back to
                        // `0, 0` seems to completely fix it.
----------------------->el.setSelectionRange(1, 1);
                        el.setSelectionRange(0, 0);
                    }
                }));
            }));
```

#### Patch Fix

In the meantime I'm using the patch below to stop the error:
```
import { Directive, ElementRef, Renderer2 } from '@angular/core';

@Directive({
  selector: '[appFixTimePick]'
})
export class FixTimePickDirective {

  constructor(private _elemRef: ElementRef, private _renderer: Renderer2) {
    this._renderer.setProperty(this._elemRef.nativeElement, "setSelectionRange", () => { })
  }
}
```

```
<mat-form-field class="offmachinetime">
    <input type="time" matInput appFixTimePick placeholder="Off Machine Time" formControlName="offmachinetime" />
</mat-form-field>
```

**Comment by AdditionAddict** [comment]
Note Stackblitz is down for me so I've been unable to reproduce

**Comment by jelbourn** [comment]
We tried this on iOS and Firefox responsive mode and could not reproduce: https://stackblitz.com/edit/angular-n3t57z?file=src/app/input-overview-example.html

Feel free to open a new issue if you can provide a reproduction.

**Comment by AdditionAddict** [comment]
@jelbourn Thanks. I wasn't giving the `<mat-label></mat-label>`, expecting placeholder to work, which seems to cause the issue.

Given correct use doesn't produce an error I won't reopen and trust anyone encountering issues will find this closed issue.

Demo:
https://stackblitz.com/edit/angular-n3t57z-dnyqwl?file=src/app/input-overview-example.html

**Comment by crisbeto** [comment]
I managed to reproduce it when there is both a `mat-label` and a `placeholder` as well. Reopening the issue.
