### ISSUE TITLE
docs-bug(COMPONENT): Table 

### ISSUE THREAD

**Issue by steve-accelex** [angular/components#22722]
#### Documentation Feedback

missing page in Table Documentation (see attached screenshot)
<img width="1042" alt="Screenshot 2021-05-19 at 09 44 37" src="https://user-images.githubusercontent.com/79309894/118783845-5d479480-b887-11eb-870e-5f7eb214129b.png">

**Comment by Raise-Exception** [comment]
most probably network connectivity latency

**Comment by itea-dev** [comment]
@steve-accelex 

Tested and it's loading correctly. Could you check again ?

It might be due to network connectivity as pointed out by @Raise-Exception .

![imagen](https://user-images.githubusercontent.com/53100338/118847026-986cb680-b8cd-11eb-80f0-26f101d24fa4.png)

**Comment by jelbourn** [comment]
Everything appears to be working correctly, seems like it may have just been a transient network connectivity issue.
