### ISSUE TITLE
After command "ng update" from 11 to 12: mixin typography-hierarchy undefined

### ISSUE THREAD

**Issue by jeroenburgers** [angular/components#22737]
I'm trying to update our Angular application with Material to version 12.0.1. For this I use the update docs/steps from Angular (https://update.angular.io/?l=3&v=11.0-12.0). Everthing is successfull, but I still have one error. During the update some files has been changed automatically. In one of the files this happend:

Added:
@use '~@angular/material' as mat;

Changed from:
@include mat-base-typography($my-sass-var, 'body');

Into:
@include mat.typography-hierarchy($my-sass-var, 'body');

Result:
typography-hierarchy mixin undefined 
  
#### Environment

- Angular: 12.0.1
- CDK/Material: 12.0.1

**Comment by crisbeto** [comment]
It looks like we forgot to expose the mixin through the new theming entry point. We'll have a fix for this in the next patch version.

**Comment by jeroenburgers** [comment]
> It looks like we forgot to expose the mixin through the new theming entry point. We'll have a fix for this in the next patch version.

Thank for adding.
