### ISSUE TITLE
schematics/update: SELECT_PANEL_MAX_HEIGHT was not found in '@angular/material/select after migration 

### ISSUE THREAD

**Issue by kourmouOmar** [angular/components#22747]
after updating the angular project with angular material from version 11 to 12 I encountered this error during the build and also when the project was launched

- Angular: 12
- AngularJS Material: 12

 
![bug](https://user-images.githubusercontent.com/45284536/118990030-711ff300-b97a-11eb-87a8-e0dffec1623f.PNG)

Error: ./node_modules/ngx-mat-select-search/__ivy_ngcc__/fesm2015/ngx-mat-select-search.js 558:55-78
"export 'SELECT_PANEL_MAX_HEIGHT' was not found in '@angular/material/select'

Error: ./node_modules/ngx-mat-select-search/__ivy_ngcc__/fesm2015/ngx-mat-select-search.js 565:23-46
"export 'SELECT_PANEL_MAX_HEIGHT' was not found in '@angular/material/select'

**Comment by Splaktar** [comment]
This issue is fixed in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/321 as part of `ngx-mat-select-search` which is a third party component not supported by the Angular Components team.
