### ISSUE TITLE
bug(COMPONENT): Dialog not closing when open from error handler.

### ISSUE THREAD

**Issue by yantrab** [angular/components#22760]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-gxoiyv?file=src%2Fapp%2Fdialog-elements-example.ts

Steps to reproduce:
1. raise error from some getter or function 
2. bind html component to this getter or function
3. catch all error in the global event handler
4. open dialog
 
 
#### Expected Behavior

What behavior were you expecting to see?
dialog open as well and can be closed

#### Actual Behavior

What behavior did you actually see?
dialog opened without any binding and not closing.

#### Environment

- Angular:12
- CDK/Material:12
- Browser(s):chrom
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by jelbourn** [comment]
The dialog isn't closing because the error being thrown in your binding is interrupting the close.
