### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by huntr-helper** [angular/components#22762]
👋 Hello, we've received a report for a potential critical severity security issue in your repository.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-angular/components** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by crisbeto** [comment]
cc @josephperrott this seems to be pointing your `test-jperrott` Firebase instance.

**Comment by JamieSlome** [comment]
@jelbourn - was this a valid issue?

**Comment by jelbourn** [comment]
It was reporting on just an old test/experimental firebase instance and also doesn't follow our [procedure for security issue reporting](https://angular.io/guide/security) (though I see now that this isn't documented on GitHub, which it should be)
