### ISSUE TITLE
Components are deformed

### ISSUE THREAD

**Issue by jimyhdolores** [angular/components#22770]
When a component is resized, the text components are affected
![image](https://user-images.githubusercontent.com/10909792/119372270-babf5500-bc7c-11eb-93b7-588f96a8af2f.png)
![image](https://user-images.githubusercontent.com/10909792/119372305-c27ef980-bc7c-11eb-99da-e25ad96d4bd1.png)
![image](https://user-images.githubusercontent.com/10909792/119372339-cc086180-bc7c-11eb-8a85-ae0d69c65791.png)

**Reproducible project**

https://github.com/jimyhdolores/ng-uridicas

version angular material:
 "@angular/material": "^11.2.6"

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

Specifically, we're not able to dig into the GitHub repo and interpret what you're doing and provide advice. 

(this is a canned response)
