### ISSUE TITLE
bug(material/table): cdkDrag of mat-header-cell styling broken when used with "sticky: true"

### ISSUE THREAD

**Issue by brendanowens** [angular/components#22781]
### Reproduction
I believe that [#21403](https://github.com/angular/components/pull/21403) (released in 11.0.4) introduced this bug. I have included the same StackBlitz, once using 11.0.3, and once using 11.0.4, to demonstrate the bug that was introduced.

Steps to reproduce:
1. Using "@angular/material": "^11.0.4" or greater (I have also tested with 11.2.12 and 12.0.1 and the bug persists)
2. Set up a mat-table using `cdkDrag` on the `mat-header-cell`'s 
3. On the `mat-header-row`, set `*matHeaderRowDef="displayedColumns; sticky: true"`
4. Drag the column header and observe the styling of the header as it is being dragged

StackBlitz of issue: https://mat-table-sticky-after.stackblitz.io
 
### Expected Behavior
The expected behavior is that the styling of the header remains next to the pointer as it is being dragged. This is the behavior **PRIOR** to `11.0.4`.

See this StackBlitz of `11.0.3` for the expected behavior: https://mat-table-sticky-before.stackblitz.io

<img width="581" alt="dragging-11_0_3" src="https://user-images.githubusercontent.com/21250577/119408670-b2cad980-bcab-11eb-875d-73b52f16c050.png">

### Actual Behavior
The behavior in `^11.0.4` is that the styling is shifted: https://mat-table-sticky-after.stackblitz.io

<img width="582" alt="dragging_11_0_4" src="https://user-images.githubusercontent.com/21250577/119408336-27e9df00-bcab-11eb-87ec-410d12c6f8f6.png">

#### Environment

- Angular: >= 11.0.4
- CDK/Material: >= 11.0.4
- Browser(s): Chrome 90.0.4430.212
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 11.2.3

**Comment by crisbeto** [comment]
I think the problem here is that the `th` loses its structure when we pull it out of the `table` to generate the preview. I'll keep this open, but I'm not sure that we can do much about it. Alternatively, you can provide a custom preview element using `cdkDragPreview`.
