### ISSUE TITLE
Expansion panel headers inside a dialog jump size upon dialog open

### ISSUE THREAD

**Issue by jelbourn** [angular/components#22785]
Reproduction: https://stackblitz.com/edit/angular-pfrqah?file=src%2Fapp%2Fdialog-overview-example-dialog.html

The expansion panel headers start off with their expanded state height, and then quickly jump to their collapsed height. I suspect this has something to do with angular's animations, but it needs further investigation.

**Comment by jelbourn** [comment]
Yeah, disabling animations does eliminate the issue (setting `[@.disabled]="true"`)
https://stackblitz.com/edit/angular-pfrqah-s61yu8?file=src%2Fapp%2Fdialog-overview-example-dialog.html

**Comment by crisbeto** [comment]
This is a long-standing issue and I'm pretty sure that we have other similar ones open. It happens, because of the behavior in `@angular/animations` where parent animations block all descendant animations.

**Comment by crisbeto** [comment]
Closing this as a duplicate of #13870 which has been open for longer.
