### ISSUE TITLE
bug(material/select): incorrect or missing SELECT_ITEM_HEIGHT_EM migration for v12

### ISSUE THREAD

**Issue by DenysVuika** [angular/components#22787]
When upgrading from Angular Components 11 to 12, the `SELECT_ITEM_HEIGHT_EM` constant is not exported from the `@angular/material/select` anymore and the projects that rely on this constant won't compile.
 
#### Expected Behavior

What behavior were you expecting to see?

The upgrade tools fix the namespace to be `@angular/material/select/select`, or export the constant properly from the `@angular/material/select`

#### Actual Behavior

Compilation issues as constant is no longer exported

**Comment by jelbourn** [comment]
This was an intentional removal of a deprecated symbol in v12: https://github.com/angular/components/pull/21827. 

It does look like there was a bug with our changelog script, though, that didn't include this in the changelog.

**Comment by HaidarZ** [comment]
Why it has been removed despite it's still used inside the select component code.

**Comment by angelaki** [comment]
Any news on this?
