### ISSUE TITLE
bug(material-experimental/mdc-button): should have 48px touch target at default density level

### ISSUE THREAD

**Issue by mmalerba** [angular/components#22799]
Not all button variants currently meet this requirement. We should be able to add the `mdc-button--touch` class to achieve this: https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#making-buttons-accessible

We should do this sooner rather than later, as it will only become more difficult to land over time.

**Comment by crisbeto** [comment]
@mmalerba I think that we may have to discuss this further. I gave the `mdc-button--touch` a shot, but it's implemented as a `margin-top: 6px; margin-bottom: 6px` on `mdc-button`. We currently have a rule against adding margins on the outer host element and wrapping the button in a `div` isn't really an option. An alternative is to use MDC's `touch-target` mixin directly, but the problem with it is that it'll produce a touch target that is always 48px tall which might not scale down very well on the higher density buttons.
