### ISSUE TITLE
Is there a way to focus on a table row?

### ISSUE THREAD

**Issue by afroguy16** [angular/components#22805]
#### Feature Description

I would like to focus on a table row

#### Use Case

Coming back to a page with a table, I would like to focus on the previous row that I clicked. It would be nice to be able to add a focus attribute that handles that.

**Comment by andrewseguin** [comment]
Technically if you want to let a row be focused, you need to give it a `tabindex=0` but this breaks accessibility. By default rows are not focusable: https://stackblitz.com/edit/angular-3pzfih-q2wzts?file=src%2Fapp%2Ftable-basic-example.html

If instead you are looking for just a way to provide extra styling to a particular row, you can simply add a class binding to the row that is conditional based on some value you set: https://stackblitz.com/edit/angular-opbexf?file=src/app/table-basic-example.ts
