### ISSUE TITLE
docs: Annotations are being shown

### ISSUE THREAD

**Issue by rafaelss95** [angular/components#22803]
#### Documentation Feedback
Annotations like `@nodoc`, `@docs-private`, `@param`, `@description`, `@deprecated` and `@breaking-change` are being shown in the docs as you can see below:

![Captura de Tela 2021-05-25 às 21 12 33](https://user-images.githubusercontent.com/11965907/119588096-7334e800-bda6-11eb-8a74-926f63f5f113.png)
![Captura de Tela 2021-05-25 às 21 15 53](https://user-images.githubusercontent.com/11965907/119588097-74feab80-bda6-11eb-8c6e-08499f314e85.png)
![Captura de Tela 2021-05-25 às 21 23 18](https://user-images.githubusercontent.com/11965907/119588098-74feab80-bda6-11eb-92c3-eb48c7874991.png)
![Captura de Tela 2021-05-25 às 21 27 31](https://user-images.githubusercontent.com/11965907/119588100-75974200-bda6-11eb-8c2e-0b32777b36e6.png)

**Affected documentation page:** Insert a link to the affected page on material.angular.io
Some of them are:

- https://material.angular.io/components/form-field/api#MatFormField
- https://material.angular.io/components/slide-toggle/api#MatSlideToggleRequiredValidator
- https://material.angular.io/components/snack-bar/api#MatSnackBar
- https://material.angular.io/components/datepicker/api#MatStartDate

**Comment by crisbeto** [comment]
The following fix from a couple of days addresses this issue https://github.com/angular/components/pull/22766.
