### ISSUE TITLE
bug(@angular/google-maps): @types/googlemaps is deprecated in favor of @types/google.maps

### ISSUE THREAD

**Issue by bdirito** [angular/components#22818]
As posted on the npm page @types/googlemaps is deprecated, @angular/google-maps specifies this as a dependency. It should now be @types/google.maps instead

see:
https://www.npmjs.com/package/@types/googlemaps

**Comment by Heatmanofurioso** [comment]
We can't use the new types package, since we get types declared in both packages.

It would be useful to get this changed

**Comment by jpoehnelt** [comment]
> We can't use the new types package, since we get types declared in both packages.

You can likely avoid this issue with `skipLibCheck: true` in tsconfig https://www.typescriptlang.org/tsconfig#skipLibCheck
