### ISSUE TITLE
bug(mat-expansion-panel): Css not applied

### ISSUE THREAD

**Issue by mackelito** [angular/components#22824]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-tmnwab?file=src%2Fapp%2Fexample-component.scss

Steps to reproduce:
1. look at the css in dev-tools

#### Expected Behavior
background color should be applied

#### Actual Behavior
background color is not applied

I can solve it by using ::ng-deep but I'm kind of curious as to why one works and the other dosen't

#### Environment

- Angular: 10.2.0
- CDK/Material: 10.2.0
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu):  N/A

**Comment by jelbourn** [comment]
See https://material.angular.io/guide/customizing-component-styles

**Comment by mackelito** [comment]
@jelbourn I think you mean https://v10.material.angular.io/guide/customizing-component-styles.. and yes I have looked.. but it does not explain why it works fine on one of the selectors and not the other.

**Comment by jelbourn** [comment]
It's because the header lives directly in the template of your component, but the body lives in the template of the expansion-panel component.

**Comment by mackelito** [comment]
I see.. and that is due to how the component is structured? Due to some content projection perhaps?
