### ISSUE TITLE
bug(@angular/youtube-player): Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by mbatyra** [angular/components#22835]
#### Reproduction

I'm using @angular/youtube-player@11.2.13 as lazy loaded component with kendo-dialog. Youtube video is loaded correctly but usually i'm getting error in console before load: 

www-widgetapi.js:722 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8000').

The error appears on localhost and also on production. 

#### Expected Behavior

Youtube video is loaded without error.

#### Environment

- Angular: 11.2.14
- CDK/Material: 11.2.13
- @angular/youtube-player: 11.2.13
- Browser(s): Chrome 90.0.4430.212
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
I've seen this occasionally in our dev app as well, but I don't think that we can do much about it since it comes from YouTube's code that's isolated inside of the `iframe`.
