### ISSUE TITLE
bug(MATERIAL): material fab button does not resize with text

### ISSUE THREAD

**Issue by kek-Sec** [angular/components#22842]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1.  https://angular-material-idettd.stackblitz.io 
 
#### Expected Behavior

What behavior were you expecting to see?

material - fab button does not resize depending on text

#### Actual Behavior

What behavior did you actually see?
Text overlaps / overflows button

#### Environment

Angular CLI: 12.1.0-next.3
Node: 12.21.0
Package Manager: npm 7.14.0
OS: linux x64

Angular: 12.1.0-next.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0-next.3
@angular-devkit/build-angular   12.1.0-next.3
@angular-devkit/core            12.1.0-next.3
@angular-devkit/schematics      12.1.0-next.3
@angular/cdk                    12.0.2
@angular/flex-layout            12.0.0-beta.34
@angular/material               12.0.2
@schematics/angular             12.1.0-next.3
rxjs                            6.6.7
typescript                      4.2.4

**Comment by crisbeto** [comment]
Closing the issue, because the FAB isn't meant to show text according to the Material design spec.
![Buttons_floating_action_button_-_Material_Design__2021-06-02_17-45-18](https://user-images.githubusercontent.com/4450522/120511091-59109080-c3ca-11eb-9d2a-f3e468b6d0b0.png)
