### ISSUE TITLE
bug(MATERIAL): Expose $dark-primary-text and $light-primary-text 

### ISSUE THREAD

**Issue by jpike88** [angular/components#22859]
I used to be able to access $dark-primary-text and $light-primary-text using the @include method in sass, but with @use I can't access those variables anymore when defining my own theme. Please expose them through it

**Comment by crisbeto** [comment]
Previously these variables were exposed by accident. We used the `@use` migration as a chance to clean up accidental public APIs like these. You can either copy over the values [from here](https://github.com/angular/components/blob/master/src/material/core/theming/_palette.scss#L29) or access them through one of the theme palettes.
