### ISSUE TITLE
docs-bug(theming): duplicate theming guide is missing

### ISSUE THREAD

**Issue by shinkhouse** [angular/components#22857]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

The current guide on duplicate theme styles does not seem to include the new way to call the various theming functions 
For example:
```
@use '~@angular/material' as mat;

$my-primary: mat.define-palette(mat.$indigo-palette, 500);
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);

// The "warn" palette is optional and defaults to red if not specified.
$my-warn: mat.define-palette(mat.$red-palette);
```

Shouldn't some of the themes defined in the duplicate theming styles doc be defined like "mat.define-light-theme(...)"?

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/guide/duplicate-theming-styles

**Comment by crisbeto** [comment]
I think that I missed this, because I was searching for `@import` in the entire codebase, but this guide doesn't have any imports.
