### ISSUE TITLE
Angular drag and drop issue with nested content and connectedList

### ISSUE THREAD

**Issue by vilcheztorrado** [angular/components#22850]
Hello!!
I have been trying to solve this issue for days but i didnt found a solution.
My problem is trying to create a dropList that contains inside other dropLists. 
Almost behavior is correct, the problem is when i try to reorder items inside the nested dropList, it can not be posible. 
I created in stackblitz an example of the bug.
https://stackblitz.com/edit/angular-rsvmbj

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/16671.
