### ISSUE TITLE
bug(Material SCSS): [DEPRECATION WARNING] Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#22866]
#### Reproduction

Steps to reproduce:
1. Upgrade angular 11 project to 12
2. Compile scss or run upgraded angular 12 project via serve command
 
#### Expected Behavior

/(divide) warning message should not come in console.

Related links - https://github.com/sass/sass/issues/2565

#### Actual Behavior

What behavior did you actually see?
![image](https://user-images.githubusercontent.com/34937515/120618242-861b7c80-c478-11eb-944b-10cce2b5b938.png)

#### Environment

- Angular: 12
- CDK/Material: "@angular/material": "^12.0.1",
- Browser(s): NA (Issue is coming while compiling scss or serving angular 12 project)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by RaphL** [comment]
I have the same issue
