### ISSUE TITLE
bug(button): mat-button-disabled class not added with ngClass

### ISSUE THREAD

**Issue by rothsandro** [angular/components#22861]
#### Reproduction

GitHub: https://github.com/rothsandro/mat-btn-demo
The issue itself can be reproduced in StackBlitz but another use case that works locally does not work in StackBlitz so I created a repo instead.

Steps to reproduce:
1. Add a button with mat-raised-button (or mat-button, ...)
2. Add the class `mat-button-disabled` to the button via `ngClass`.
 
 
#### Expected Behavior

The button should have the class "mat-button-disabled" and should look like disabled.

#### Actual Behavior

The class is not present (and the button does not have the disabled styling).

Disabling a button with the disabled attribute works but it will remove the element from the accessibility tree. It's better to use a class and keep the button enabled. Using a disabled class seems to be supported for this reason, there is a comment in the component: https://github.com/angular/components/blob/master/src/material/button/button.ts#L67-L69

When using the static class attribute instead of `ngClass` it works (at least locally, but not in StackBlitz).

#### Environment

- Angular: 12.0.2
- CDK/Material: 12.0.2
- Browser(s): Chrome 90
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This isn't something that we support. If a button is disabled, it should be disabled for assistive technology as well. The correct way of doing it is through the `disabled` input.

**Comment by rothsandro** [comment]
A year ago the component was changed to use the CSS class instead of the disabled attribute for this reason, see https://github.com/angular/components/commit/c2abcadb027f79d6cd5404c2bc857a7770df95c1.

> ... which wants to avoid _actually_ disabling buttons so that they can have tooltips

 So the change was made with the intention to support this, or did I misinterpret this?

--- 

> If a button is disabled, it should be disabled for assistive technology as well.

I don't agree, see 
https://css-tricks.com/making-disabled-buttons-more-inclusive/
https://twitter.com/buildsghost/status/1389228551874899969

**Comment by crisbeto** [comment]
Those changes were made primarily to allow for tooltips to fire on a disabled button.
