### ISSUE TITLE
bug(form-field): matPrefix does not style SVG icons properly

### ISSUE THREAD

**Issue by Parent5446** [angular/components#22863]
#### Reproduction

Steps to reproduce:
1. Use [SVG icons](https://v7.material.angular.io/components/icon/overview#svg-icons) with `<mat-icon>`
2. Add an icon to a form field using `matPrefix`
 
 
#### Expected Behavior

The icon resizes appropriately to the form field, similar to what is done with `<mat-icon-button>`

#### Actual Behavior

The icon does not resize, particularly w.r.t. the width of the element, leaving it too close to the placeholder text in the input element.

This is because `matPrefix` has [special styling](https://github.com/angular/components/blob/25924faf07d79c1173ebe9e75b0b8574a125c79b/src/material/form-field/_form-field-theme.scss#L171-L189) for `.mat-icon` alone that works only for font-based icons, and styling for `.mat-icon-button .mat-icon` that works with both styles of icon, but it lacks styling for `.mat-icon` alone that works with SVG-style icons.

Perhaps the styles can be adjusted so that an explicit `height` and `width` is given to the `<mat-icon>`, similar to what is already being done with `.mat-icon-button`.

#### Environment

- Angular: angular/angular@e039075a2837b0decf17cfbd5382d675c331bbeb
- CDK/Material: ade09010454bd82e547522326a6fe6178c9a39f3
- Browser(s): Firefox 88.0.1
- Operating System (e.g. Windows, macOS, Ubuntu): gLinux

**Comment by crisbeto** [comment]
Can you post what your markup looks like? I looked into this, but SVG and font-based icons behaved similarly for me.

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback in a long time. It can be reopened if we get more information.
