### ISSUE TITLE
feat(MAT-BUTTON): Make _theme-property SASS mixin public

### ISSUE THREAD

**Issue by mcalmus** [angular/components#22862]
#### Feature Description

Make existing _theme-property SASS mixin from button-theme publicly accessible.

#### Use Case

We have a custom theme that uses the _theme-property mixin from the button-theme SASS class. Prior to v12 this worked fine. In v!2 this is disallowed because it is considered a private member. "Private members can't be accessed from outside their modules".

It would be useful to have this mixin accessible to theme creators.

**Comment by crisbeto** [comment]
`_theme-property` is a private mixin since it's there only to save us some typing. You can use the `color` mixin instead which includes all of the necessary styles to change the button color.
