### ISSUE TITLE
bug(Chips): multiple isn't respected

### ISSUE THREAD

**Issue by RogierVC** [angular/components#22867]
#### Reproduction
https://stackblitz.com/edit/angular-zq2wrf?file=src/app/chips-autocomplete-example.html

Steps to reproduce:
1. Add `[multiple]="false"` to `<mat-chip-list>`
 
#### Expected Behavior
The user should not be allowed to select multiple chips.

#### Actual Behavior
The user is able to select multiple chips.

#### Environment
- Angular: 12.0.3
- CDK/Material: 12.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
`multiple` refers to whether multiple chips are allowed to be selected (e.g. colored background), not whether multiple chips can be in the list. You can control the number of chips through the value that you pass to `ngFor`.

![demo](https://user-images.githubusercontent.com/4450522/121143181-0fe29580-c83d-11eb-8b1c-cc13c8505a1c.gif)
