### ISSUE TITLE
bug(cdkTrapFocus): Axe Issue "Ensure aria-hidden elements do not contain focusable elements"

### ISSUE THREAD

**Issue by suryatejanandipati** [angular/components#22872]
I am using the cdkTrapFocus directive on a modal to trap the focus inside the when modal is opened with the tab key. We recently updated Axe to Axe Expert. And we are facing an axe issue as "Ensure aria-hidden elements do not contain focusable elements". 

I saw that the cdkTrapFocus directive is adding a div tag with tabindex="0" and aria-hidden="true". 

Expected Behavior
cdkTrapFocus should not set aria-hidden to true because hidden area elements are not supposed to have focusable content https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=AxeChrome but the point of having a focus trap is so that you can use it with focusable content.

Actual Behavior
cdkTrapFocus sets aria-hidden to true

Please let me know how to fix this or whether it is a false positive for AXE Expert.

Environment
Angular 9,
Browser: Chrome
OS: Windows
CDK/Material: "@angular/cdk": "^9.0.0"

**Comment by crisbeto** [comment]
This isn't a problem, because if the user lands on the hidden element, their focus will be moved immediately to the new first focusable element in the focus trap. We made the anchors `aria-hidden` so that the user isn't able to navigate to them using screen reader shortcuts.
