### ISSUE TITLE
bug(mat-dialog): scroll jumps back after dialog close when NoopScrollStrategy is used

### ISSUE THREAD

**Issue by akosgavaller** [angular/components#22870]
#### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/edit/components-issue-vxtsjw?file=src/app/example-component.ts
2. Click on the "Open overlay" button
3. Scroll down the page while the overlay is open
4. Click on the "Close" button on the overlay
 
 
#### Expected Behavior

The scroll position should remain after close.

#### Actual Behavior

The scroll jumps back after close.

#### Environment

- Angular: 12.0.1
- CDK/Material: 12.0.1
- Browser(s): Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
That's because focus is restored to the element that opened the dialog. This is an accessibility feature that is turned on by default. You can disable it by passing `restoreFocus: false` when opening the dialog.
