### ISSUE TITLE
bug(MAT-MENU): Broken on v12.0.3

### ISSUE THREAD

**Issue by bkarv** [angular/components#22886]
#### Reproduction

Example in Angular material only
https://stackblitz.com/edit/angular-mx7jap?file=src%2Fapp%2Ftop-bar%2Ftop-bar.component.html

Example in Ionic combined with Angular Material
https://stackblitz.com/edit/ionic-angular-v5-geg5bw?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Create nested mat-menu
 
 
#### Expected Behavior

What behavior were you expecting to see?
1. Nested menus should not displayed when parent menu selected
2. Menus should nicely align each other side by side

#### Actual Behavior

What behavior did you actually see?
1. All nested menus show when parent clicked (happens with angular/ionic version)

2. Layout looks like a dogs breakfast. Ie 
<img width="350" alt="Screen Shot 2021-06-04 at 11 36 01 pm" src="https://user-images.githubusercontent.com/10624315/120809631-a1c47700-c58d-11eb-8ace-3610232be866.png">

#### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): stackblitz
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Did this used to work in v11? We haven't made very many changes to `mat-menu` in the past few releases.

**Comment by bkarv** [comment]
Not sure about v11 as i have skipped a version in the upgrade. But definitely worked for for v10. 

Even if you try the nested menu example in: https://material.angular.io/components/menu/overview
It doesn't work as expected.

**Comment by crisbeto** [comment]
How does the example from the docs site break for you? It definitely works as expected for me.

**Comment by bkarv** [comment]
Thanks for prompt response.

I get the funny layout as described above. However I just checked on the stackblitz provided by the angular material site for v12 instead of doing a manual update in stackblitz (or within my app). It seems to work there as expected so it must be something missing when upgrading. 

Apart from importing following:
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatMenuModule } from '@angular/material/menu';

and  below packages. Is there anything else that needed to be added in angular material when migrating across from 10 to 11/12. I noticed there was a change sass for v11, is there anything thats need to be done here when upgrading?

<img width="457" alt="Screen Shot 2021-06-05 at 3 37 18 pm" src="https://user-images.githubusercontent.com/10624315/120881371-ed216880-c613-11eb-99b5-eedff5ec41bd.png">

**Comment by crisbeto** [comment]
There haven't been any large `mat-menu` changes in a while and the Sass refactor between 11 and 12 is backwards-compatible. What you're describing sounds like a Material theme might not be included.

**Comment by bkarv** [comment]
Yes you are right, i tried inserting 
`<button mat-raised-button color="primary">Primary</button>`

and get a similar incorrect style issue. There must be some import missing although I did compare to the material's official stackblitz and imported all modules in below app.module.ts

https://stackblitz.com/edit/angular-mx7jap?file=src/app/app.module.ts

I'll have to go through line by line see what is missing.

**Comment by bkarv** [comment]
No matter found the issue, inserting following in style.css resolved the issue the in stackblitz.

`@import '~@angular/material/prebuilt-themes/indigo-pink.css';
`
Updated:
https://stackblitz.com/edit/angular-mx7jap-3a7dt9?file=src%2Fstyles.css

For my Angular Ionic app, the above css needs to be imported into global.scss instead

**Comment by bkarv** [comment]
For any upgrading more information here:

https://material.angular.io/guide/theming#using-a-pre-built-theme

Thanks @crisbeto for your help. Issue resolved and I am closing this.
