### ISSUE TITLE
docs-bug(MatChips): there's no docs for `MatChipAvatar`

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22905]
#### Documentation Feedback

The class `MatChipAvatar` is mentioned several times in the chips component [API docs](https://material.angular.io/components/chips/api).  
But there's no docs for the `MatChipAvatar` itself.
![image](https://user-images.githubusercontent.com/13061803/120918504-717bf600-c6bd-11eb-88bc-d5740b6804ae.png)

![image](https://user-images.githubusercontent.com/13061803/120918471-472a3880-c6bd-11eb-96d6-95bff40210ab.png)

**Comment by crisbeto** [comment]
I think that we excluded it because it's a directive that adds some styles to any DOM node. That being said, I don't see a reason why we can't just say that in the docs.

**Comment by Manish-Giri** [comment]
@crisbeto Hello, can I take this up?

**Comment by crisbeto** [comment]
Sure, also feel free to ping me on the PR and I can review it.
