### ISSUE TITLE
bug(sidenav): sidenav width "jumps" without any interaction

### ISSUE THREAD

**Issue by PowerKiKi** [angular/components#22909]
#### Reproduction

Use StackBlitz to reproduce your issue: 

- https://stackblitz.com/github/ecodev/natural/tree/blinking2

Steps to reproduce:

1. With Google Chrome only
2. Click alternatively on Home and Other page menu entry
3. See that the pink area extend for about ~1 seconds and then shrink again
 
 
#### Expected Behavior

I expect the `<mat-sidenav>` width (in pink) to remain constant at all times.

#### Actual Behavior

The width of `<mat-sidenav>` is changing for about ~1 second before returning to its correct width.

Since my code is doing pretty much nothing at all, I don't expect "jumping" behavior like that. Especially not after what seems to be a `setTimeout()`.

In the video below, I click exactly one time per button, yet we clearly see what seems to be a 2-step "animation" of the  `<mat-sidenav>` width for each click.

https://user-images.githubusercontent.com/72603/120990600-ac645380-c7bb-11eb-9f1e-972500bb3d69.mp4

#### Environment

- Angular: 12.0.3
- CDK/Material: 12.0.3
- Browser(s): Chrome 91.0.4472.77  (Firefox is OK)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
I think the problem is that you're using `mat-nav-list`, but you haven't included a Material theme. This means that when you click the link, Material tries to create a ripple which increases the width. There's some information about theming in the getting started guide: https://material.angular.io/guide/getting-started

**Comment by PowerKiKi** [comment]
Unfortunately this is not the source of the problem. I pushed the Material theme to the StackBlitz and the bug still appears:


https://user-images.githubusercontent.com/72603/121005654-fe60a580-c7ca-11eb-9d55-688095119e4c.mp4

**Comment by crisbeto** [comment]
It seems like it's related to the ripple, because it goes away if I set `disableRipple` on the `mat-nav-list`.

**Comment by dan5082** [comment]
Having a very similar issue on mat-drawer

**Comment by PowerKiKi** [comment]
I can confirm that adding `disableRipple` will fix the issue. However it is not an applicable workaround for me, as I need those ripples.

I updated the StackBlitz to entirely remove `<mat-nav-list>` and use a native `<ul>` instead. And worse, I moved the problematic button from the menu to the main page content, so outside of the jumping layout, and the bug still occurs:

https://user-images.githubusercontent.com/72603/121106803-b5980380-c841-11eb-911c-61db3bb6aa47.mp4

I also noticed that removing `fxFill` would "fix" the issue, but since it breaks the whole layout it is also not a viable workaround.

So far I think the bug appear when `<mat-sidenav-container>`, `fxFill` and ripple effects are used together, though they might not be the only combinaison to trigger the bug.

@dan5082 could you please confirm whether you use `@angular/flex-layout` in your project ?

**Comment by PowerKiKi** [comment]
The StackBlitz is now using Angular 12.1 and all latest deps, but the bug still occurs.

And since `@angular/flex-layout` pretty much [did not change between 11.0 and 12.0](https://github.com/angular/flex-layout/compare/11.0.0-beta.33...12.0.0-beta.34), it seems unlikely that it would have been introduced by flex-layout. But just for the sake of it, I tested with 11.0.0-beta.33 and it also is reproducible. That means that the bug has be introduced by a change in either `@angular/material` or `@angular/core`, but not `@angular/flex-layout`.

**Comment by PowerKiKi** [comment]
After an update to Angular 13 I cannot reproduce the issue anymore. Going back to Angular 12, I also cannot reproduce the issue anymore. My conclusion is that the bug was actually in Chrome and now with Chrome 98.0.4758.102, I cannot reproduce at all.

I consider this issue solved somewhere between Chrome 91.0.4472.77 and 98.0.4758.102.
