### ISSUE TITLE
docs-bug(MatChips): describe how to use chips with forms

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22906]
#### Documentation Feedback

Describe how to use chips with forms: reactive and template-driven. Add examples

**Affected documentation page:** https://material.angular.io/components/chips/overview

**Comment by sapatgit** [comment]
@crisbeto Hi, can I try this?

**Comment by balaji-balamurugan** [comment]
Hi, I can take this, if anyone is not working on this issue.
