### ISSUE TITLE
bug(MapMarker): Strange behavior when (mapDragend) is present and unable to pan map to new position

### ISSUE THREAD

**Issue by fabioaccetta** [angular/components#22913]
Ionic application (latest) with angular (latest ~12) + @angular/google-maps (latest ~12).
I'd like to make the marker dragable, catch the new position (LatLng) and pan the map center to the new position.
I'm doing something wrong?

#### Reproduction
Steps to reproduce:
1. use `<google-map>` tag and `<map-marker>` one without `(mapDragend)` event with `markerOptions: {dragable: true}` and initial position set:

```
<google-map [height]="height" [width]="width" [zoom]="zoom">
    <map-marker #marker="mapMarker" [options]="markerOptions"></map-marker>
</google-map>
```
With this html I can correctly move the marker inside the map, and the last position of the marker is preserved when the event ends (even if the map does not pan her center to the new position because, of course, none still told her to do this and I'd like to make this to happen thanks to the mapDragend event).

2. when using the `(mapDragend)` event inside the `<map-marker>` tag, the marker can be still dragable but when I move it and release the mouse, the marker moves back to original position, even if the method `onDragEvent()` does actually nothing (only console.logging the event.latLng property that, however, is still correct):

```
<google-map [height]="height" [width]="width" [zoom]="zoom">
    <map-marker #marker="mapMarker" [options]="markerOptions" (mapDragend)="onDragEnd($event)"></map-marker>
</google-map>
```
 
 
#### Expected Behavior
I expect to see the marker dragable and it's position as the last after dragging

#### Actual Behavior
The marker is correctly dragable but when the `(mapDragend)` is declared, it's last position is correctly recorded (console.log shows new correct position) but the marker comes back to it's initial position after the event is fired.

#### Environment

- Angular: 12.0.3
- Ionic: 5.5.2
- CDK/Material (only @angular/google-maps): 12.0.3
- Browser(s): Google Chrome (updated)
- Operating System (e.g. Windows, macOS, Ubuntu): Linux Debian (updated)

**Comment by fabioaccetta** [comment]
Forgot to write some unsuccessful test:

```
onDragEnd(event: google.maps.MapMouseEvent) {
    event.domEvent.preventDefault();
    event.domEvent.stopPropagation();
    event.domEvent.stopImmediatePropagation();

   [...]
   
   return false;
}

```
But nothing useful happened.

**Comment by crisbeto** [comment]
I just tried it out and it worked as expected for me. Here's what I have:

```
<google-map height="400px" width="750px" [zoom]="zoom" [center]="center">
  <map-marker [position]="center" [options]="markerOptions" (mapDragend)="onDragEnd($event)"></map-marker>
</google-map>
```

Could the problem be that you aren't passing a `position` to the marker?

**Comment by fabioaccetta** [comment]
Solved: I refactored all the code, including parent and child components, better event handling and everything seems to work correctly.

Thanks @crisbeto, but I think the problem was exactly the opposite: even if the map events were correctly fired, something was locking map center and marker position.

Now, with a cleaner event handler, the flow seems to be right, thanks.
