### ISSUE TITLE
feat(AutoComplete): Need ability to set input value upon start up

### ISSUE THREAD

**Issue by Welborn09** [angular/components#22914]
#### Feature Description

There needs to be a 'setValue' method that will populate the input component of the MatAutomation component. 

#### Use Case

If a user is editing a record, let's say Import Details form, and the field of the Autocomplete is 'Parts'. Whatever the record value is for parts needs to be populated on the input of the AutoComplete. 
for instance (autoPart is reference to MatAutomation):
 this.autoPart.setValue('MSX Part');

**Comment by crisbeto** [comment]
The autocomplete module has support for `@angular/forms` so you can control the value using `ngModel` or `formControl`.

**Comment by Welborn09** [comment]
Thank you for the replay @crisbeto but can you provide an example of this? I have researched for this and from what I am seeing no one has been able to do this.

**Comment by Welborn09** [comment]
@crisbeto I did what you suggested and used [(ngModel)] in my autocomplete and still didn't work

`<mat-form-field class="dialog-input">
          <mat-label>Client</mat-label>
          <input #clientInput
                 type="text"
                 placeholder="Type to search"
                 aria-label="Client"
                 matInput
                 [formControl]="clientControl"
                 [matAutocomplete]="autoClient"
                 (focusout)='selectClient(clientInput.value)'
                 [(ngModel)]="selectedClient">
              <mat-autocomplete autoActiveFirstOption
                 panelWidth="350px"
                 #autoClient="matAutocomplete"
                 (optionSelected)='selectClient($event.option.value)'>
                  <mat-option *ngIf="isLoading"
                              class="is-loading">Loading...</mat-option>
                  <ng-container *ngIf="!isLoading">
                      <mat-option *ngFor="let option of filteredClients"
                                  [value]="option.value">
                          {{option.value}}
                      </mat-option>
                  </ng-container>
              </mat-autocomplete>
      </mat-form-field>`

In my TypeScript I am setting 'selectedClient' to an object and nothing shows up in my autocomplete. Would a typical object suffice or does it have to be a specific type?
