### ISSUE TITLE
SassError: Invalid CSS after "@include mat": expected 1 selector or at-rule, was ".core();"

### ISSUE THREAD

**Issue by hippidyhoppy** [angular/components#22935]
#### What are you trying to do?
I am trying to update my project from Angular 11 to 12, including @angular/material and @angular/cdk but unfortunately now I am getting the above issue.

`SassError: Invalid CSS after "@include mat": expected 1 selector or at-rule, was ".core();"`

#### What troubleshooting steps have you tried?
I checked with npm ls node-sass and there are no occurrences:

```
hippidyhoppidy@one-MacBook-Pro app % npm ls node-sass
app@0.0.0 /Users/hippidyhoppidy/Projects/app
└── (empty)
```

I was still getting the same error and then I decided to add sass to my project and now this is the output but I still get the same error:
```
hippidyhoppidy@one-MacBook-Pro app % npm ls sass     
app@0.0.0 /Users/hippidyhoppidy/Projects/app
├─┬ @angular-devkit/build-angular@12.0.3
│ └── sass@1.32.12 
└── sass@1.34.1 
```

Already looked into these two but no luck so far:
https://stackoverflow.com/questions/67527236/angular-material-sasserror-invalid-css-after-include-mat-expected-1-select
https://stackoverflow.com/questions/67622281/angular-material-sasserror-invalid-css-after-include-mat-expected-1-select

#### Reproduction

It is failing in my `theme.scss` file:

```
@use '~@angular/material' as mat;

@include mat.core(); // ------> it fails here

// more theming code afterwards
```

  
#### Environment

- Angular: 12.0.0
- CDK/Material: 12.0.0
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): macOS BigSur
- npm: ~6.14.11
- node: >=14.16.0

**Comment by crisbeto** [comment]
It sounds like you're using `node-sass` which is deprecated and doesn't support the new module system. Can you try switching to the canonical `sass` package? https://www.npmjs.com/package/sass

**Comment by jelbourn** [comment]
Closing since this is likely due to using `node-sass`. Feel free to reopen if you can provide more details.
