### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#22936]
### Deprecation Warning
I started getting this warning while working on migrating mdc components:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($variable1, $variable2)

More info and automated migrator: https://sass-lang.com/d/slash-di
```

This is not urgent, but I figured I should at least create an issue so that this is not forgotten.

**Comment by crisbeto** [comment]
This was fixed in https://github.com/angular/components/commit/a4043f41f539ed910c80c780e1815f5625282b94. There are still a few leftover warnings due to MDC which will be fixed by https://github.com/angular/components/pull/22932.
