### ISSUE TITLE
bug(Scrolling,DragDrop): Dragging with scrolling dont work as expected when placed inside ViewEncapsulation.ShadowDom container

### ISSUE THREAD

**Issue by kmiasko** [angular/components#22939]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-bdyprt

Steps to reproduce:

1. Drag an item down
2. Wait for scroll to fire
 
#### Expected Behavior

Element should be placed over / under element that dragged item is on

#### Actual Behavior

Element is placed over / under other element, like the scroll never happened

#### Environment

- Angular: 11.2.14
- CDK/Material: 12.0.4
- Browser(s): Chrome
- Operating System Windows

**Comment by mmalerba** [comment]
@crisbeto is there anything we can do to make this work better with shadow dom?

**Comment by crisbeto** [comment]
There is, I've had this on my list as something that can potentially break, I just hadn't had the time to circle back to it.
