### ISSUE TITLE
Angular Google Maps Error - initMap is not a function.

### ISSUE THREAD

**Issue by lakindu2002** [angular/components#22963]
I installed @angular/google-maps via npm and i set up the API key on index.html via a script import.
I get this error when loading the application on the browser console.

`initMap is not a function`

**Comment by lakindu2002** [comment]
Okay its okay, I managed to fix it by removing the `initMap` callback param in the script import.

**Comment by mmalerba** [comment]
Closing since it sounds like the issue has been resolved
