### ISSUE TITLE
help(core): Sass module system and !default

### ISSUE THREAD

**Issue by DMezhenskyi** [angular/components#22969]
#### What are you trying to do?

Before version 12 I could override some default variables from _theming.scss (i.e $mat-toolbar-minimum-height) by using:
```
@use '~@angular/material/theming' as mat with(
  $mat-toolbar-minimum-height: 32px
); 
```
It was working fine for my projects but it doesn't work with a new sass module system introduced with v12. After some googling I found out that it is not recommended to override defaults (though why is it marked with !default then?) and also I saw that CSS variables are one of the ways to address the issue once the support of IE11 is dropped. Since IE 11 is deprecated I would like to ask what is the state of this feature? Is it already on the roadmap? And what would be the recommended way to override default sizes for different elements like buttons, toolbar etc until Angular Material gets official CSS3 support?

Thank you!

**Comment by crisbeto** [comment]
We dropped the `mat-*` prefix as part of the migration. You can try setting the variable name to `$minimum-height` instead.

**Comment by jelbourn** [comment]
Overriding Sass variables is something we explicitly do not support. Some of the variables do have `!default` just historically, but it was never intended to be overridden by end-developers. Adjusting component sizes will be supported at part of #4597 (with the MDC-based components), but isn't thing we provide an API for today.

**Comment by DMezhenskyi** [comment]
> We dropped the `mat-*` prefix as part of the migration. You can try setting the variable name to `$minimum-height` instead.

Hi @crisbeto! Thanks for response. Yep, I have noticed that `mat-*` has been dropped. The problem actually is that if I import sass module using `with` (like in an example above) I get `SassError: This module was already loaded, so it can't be configured using "with"`. My bad, I should have mentioned it the error message it in the issue body.

@jelbourn Thank you for the link and clarification!
