### ISSUE TITLE
RFC: New date adapters distribution

### ISSUE THREAD

**Issue by crisbeto** [angular/components#22975]
# Context
Currently we have two first-party date adapters for Angular Material (`NativeDateAdapter` and `MomentDateAdapter`) and we don’t recommend using either of them, because one only parses dates correctly in the `en-US` format and the other one depends on moment.js which is now deprecated. We have a [highly-upvoted feature request](https://github.com/angular/components/issues/20599) to add more date adapters and doing so is straightforward and we are seeking community feedback on how we might best distribute new adapters. 

**Disclaimer**: this RFC is meant to start the discussion around how we want to distribute date adapters in the future. We can't commit to a timeline on when the new adapters will be added.

The current options are:

## Option 1: Separate npm package for each adapter
Identical to how we’re currently distributing the Moment date adapter. We’d have separate top-level packages for each new adapter, like `@angular/material-luxon-date-adapter`, `@angular/material-date-fns-date-adapter` etc.

### Pros
* Allows us to enforce the required third-party library dependency (Luxon, date-fns etc.) through `peerDependencies`. 

### Cons
* Adds to the top-level `@angular` namespace with more packages. The large number of npm packages is a common developer complaint from Angular developers.
* Unclear how it will be documented since our docs site is only set up for larger top-level packages like `material` and `cdk`.
* Less discoverable, because users would have to look for the date adapters on npm in-between the other Angular packages.

## Option 2: Single top-level package for all adapters
We would add a single top-level package called `@angular/material-date-adapters` which exposes all first-party date adapters and has dependencies on all of their date libraries.

### Pros
* Easy to enforce peer dependency versions through npm.
* Limits the pollution of the top-level `@angular` namespace to only one new package.

### Cons
* May increase the size of users’ `node_modules` unnecessarily, because they would be installing date libraries that they might not use.
* Difficult to document with our current infrastructure.
* Includes additional peer dependencies that the project might not actually use.

## Option 3: Package within Material without explicit dependencies
Under this approach the date adapters would be placed under a new entrypoint called `@angular/material/date-adapters`, however we wouldn’t specify a dependency on third-party date libraries explicitly so that users of Material don’t download them automatically. It would be up to the consumer to install the dependency for the adapter that they’re using.

### Pros
* Does not pollute the global `@angular` namespace.
* Easily discoverable since it’s already inside Material.
* Does not add any new dependencies, unless the user opts into them.
* Easy to document with our current infrastructure.

### Cons
* Consumers may get hard-to-diagnose errors, because the required date library hasn’t been installed.
* No good way for us to enforce that a specific version of a date library is used. E.g. a library may come up with a new breaking release and there won’t be any way for us to indicate that we aren’t compatible with this release yet.

## Option 4: Package within Material with explicit dependencies
This approach is identical to Option 3, however we would list all of the supported date libraries as peer dependencies.

### Pros
* Allows us to enforce peer dependency versions through npm.
* Does not add to the global `@angular` namespace.
* Easily discoverable since it’s already inside Material.
* Easy to document with our current infrastructure.

### Cons
* Users can get warnings about peer dependencies that they don’t intend on using. E.g. npm could warn them that they need to install Luxon, even though they only intend to use the date-fns adapter.

**Comment by martinmcwhorter** [comment]
If this was a ranked vote, I would vote in order: 1, 2, 3, 4

**Comment by DmitryEfimenko** [comment]
Ranked vote: 1, 3, 2, 4
I feel that specifying peer deps is important. Discoverability can be solved via documentation. I can see how top level package is undesirable, but the cons of the alternatives are just too harsh

**Comment by kyubisation** [comment]
I would vote 1 or 3.
With 3, sanity checks would be possible with packages that expose a version in its public API (e.g. Luxon).
If 1 is chosen, I would prefer the native date adapter to be included in the base package. This might include the Temporal Adapter in the future.

**Comment by BodoPapa** [comment]
Ranked vote; 3, 1, 2, 4

**Comment by piotter121** [comment]
Ranked vote: 3,1,2,4

**Comment by wellington1993** [comment]
Ranked vote: 1, 3, ...  2, 4

**Comment by gabynevada** [comment]
Ranked vote: 3, 4, 2, 1

**Comment by andreialecu** [comment]
> Users can get warnings about peer dependencies that they don’t intend on using. E.g. npm could warn them that they need to install Luxon, even though they only intend to use the date-fns adapter.

Peer dependencies can (and should in this case) be made optional: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

**Comment by andreialecu** [comment]
Option 3 is invalid because it can break in unexpected ways when used with workspacea, and yarn 2 explicitly prevents it: https://yarnpkg.com/advanced/rulebook/#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

However option 4 is OK, by marking the peers as optional as per my previous comment.

My vote: 4

**Comment by manumqln** [comment]
I would vote for 3. But ok to have these adapters in any ways as they are very much required

**Comment by chriscurnow** [comment]
4, 1, 2, 3

**Comment by jochenjonc** [comment]
Option 4, with the optional peer dependencies
Then 2, 1, 3

**Comment by rfprod** [comment]
I'd vote for option 4.
If 4 is not available, then option 1.

**Comment by Splaktar** [comment]
Just FYI, this is a request for comments and discussion. Posting your input, comments, feedback, etc is more helpful to us then posting a ranked vote list.

**Comment by crisbeto** [comment]
Thank you for the feedback, the RFC period is now over.
