### ISSUE TITLE
help(CDK): Bootstrap call not found

### ISSUE THREAD

**Issue by enorfelt** [angular/components#22971]
#### What are you trying to do?

Trying to add @angular/material to project by running "ng add @angular/material".
This gives me "Bootstrap call not found"

#### What troubleshooting steps have you tried?

"ng add @angular/material" gives me "Bootstrap call not found"

#### Reproduction

Steps to reproduce:
1. ng add @angular/material
  
#### Environment

- Angular: 12.0.3
- CDK/Material: 
- Browser(s): -
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

SchematicsException [Error]: Bootstrap call not found
    at findBootstrapModulePath (\src\frontend\node_modules\@angular\cdk\schematics\utils\vendored-ast-utils\index.js:451:15)
    at Object.getAppModulePath (\src\frontend\node_modules\@angular\cdk\schematics\utils\vendored-ast-utils\index.js:474:32)
    at \src\frontend\node_modules\@angular\material\schematics\ng-add\setup-project.js:65:44
    at Generator.next (<anonymous>)
    at fulfilled (\src\frontend\node_modules\@angular\material\schematics\ng-add\setup-project.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Bootstrap call not found

**Comment by crisbeto** [comment]
The "bootstrap call" means that the schematics are looking for a method call for `bootstrapModule`, but they aren't finding them. How is app bootstrapped?

**Comment by crisbeto** [comment]
I believe it tries to find the main module in order to start building out the dependency graph. It is specifically looking for syntax that looks like `foo.bootstrapModule` so if you're doing something different, it might not find it.

**Comment by enorfelt** [comment]
> I believe it tries to find the main module in order to start building out the dependency graph. It is specifically looking for syntax that looks like `foo.bootstrapModule` so if you're doing something different, it might not find it.

Thx it solved that issue but gave me a new error about default builder .. ended up adding it manually.
