### ISSUE TITLE
bug(Sidenav): MatDrawer's close api is not working after async calls

### ISSUE THREAD

**Issue by rajeevuipath** [angular/components#22973]
#### Reproduction
https://stackblitz.com/edit/angular-ckgwhe?file=src/app/sidenav-autosize-example.css

Steps to reproduce:
1. Open sidenav by clicking on `Toggle sidenav` button
2. Clicking on second button, it closes (sync)
3. Click on first button in sidenav (async =>  using `delay` to close it after 1 sec)

#### Expected Behavior
sidenav should get closed after 1 sec
 
#### Actual Behavior
sidenav is not closing

#### Environment
- Angular: 11 + 
- CDK/Material: Sidenav
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by mmalerba** [comment]
I think the issue is that you're not subscribing to the stream so that `tap` function is never run. Here's a working example that subscribes instead: https://stackblitz.com/edit/angular-ckgwhe-gnjrn1?file=src%2Fapp%2Fsidenav-autosize-example.ts
