### ISSUE TITLE
bug(matertial badge): [matBadgeHidden]="true" is not working

### ISSUE THREAD

**Issue by miguelmoya1** [angular/components#22984]
#### Reproduction

Steps to reproduce:
1.  matBadgeHidden attribute is not working
 
 
#### Expected Behavior

What behavior were you expecting to see?
That the badge is not displayed

#### Actual Behavior

What behavior did you actually see?
The badge

#### Environment

Angular CLI: 12.0.4
Node: 14.17.0
Package Manager: yarn 1.22.5
OS: win32 x64

**Comment by crisbeto** [comment]
Can you post what your code looks like? I just tried it out and it worked for me. See https://stackblitz.com/edit/angular-y4mk2j?file=src%2Fapp%2Fbadge-overview-example.ts.

**Comment by miguelmoya1** [comment]
If I use it here it doesn't work

`
<app-button [matBadgeHidden]="totalUnread === 0" [matBadge]="totalUnread" matBadgePosition="before"
      matBadgeColor="accent" routerLink="/report" [addClass]="actualRoute === 'report' ? 'active' : ''">
      <app-svg [classes]="actualRoute === 'report' ? 'primary' : ''" type="report"></app-svg>
    </app-button>
`

But if I use it in a div, works

`
    <div [matBadgeHidden]="totalUnread === 0" [matBadge]="totalUnread" matBadgePosition="before"
      matBadgeColor="primary">
      <app-button routerLink=" /report" [addClass]="actualRoute === 'report' ? 'active' : ''">
        <app-svg [classes]="actualRoute === 'report' ? 'primary' : ''" type="report"></app-svg>
      </app-button>
    </div>
`

the app-button only contains this

`
<button [ngClass]="addClass">
  <span class="line"></span>
  <ng-content></ng-content>
</button>
`

**Comment by crisbeto** [comment]
It's difficult to tell what's going on without a reproduction case. Do you get any errors in the console? It's possible that the `MatBadgeModule` wasn't imported in the correct place. Also does the badge show up if you remove the `matBadgeHidden`?

**Comment by miguelmoya1** [comment]
Yes, if I remove the hidden if it is shown, and everything is imported as in the example you gave me.
