### ISSUE TITLE
bug(mat-select): arrow icon(Chevron Down) is not placed properly in IE

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#22980]
#### Reproduction

Steps to reproduce:
1. Open following example in IE - https://material.angular.io/components/select/examples#select-value-binding
2. Click on the dropdown 
3. Select none
4. Check the arrow placement when there is nothing selected in mat-select
 
 
#### Expected Behavior

Arrow icon should be aligned properly with the floating label which is currently happening in chrome.

![Chrome mat-select dropdown](https://user-images.githubusercontent.com/34937515/122065057-45741980-ce0f-11eb-92d0-1f40fe2a139d.jpg)

#### Actual Behavior

Arrow icon is not aligned properly with floating label

![IE mat-select dropdown](https://user-images.githubusercontent.com/34937515/122065084-49a03700-ce0f-11eb-8871-631cbc674785.jpg)

#### Environment

- Angular: 12
- CDK/Material: "@angular/material": "^12.0.1", "@angular/cdk": "^12.0.1"
- Browser(s): IE, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by iKrishnaSahu** [comment]
For time being, I have added a workaround for this issue -

```
.mat-select-trigger {
   float: right;
}
```

**Comment by jljohnson001** [comment]
@iKrishnaSahu a head's up: [Angular support](https://github.com/angular/angular/issues/41840) for IE is deprecated and will be removed by Angular v13.

**Comment by jelbourn** [comment]
Since IE11 support is ending in v13, I don't see us realistically fixing this between now and then.
