### ISSUE TITLE
bug(mat-tab): iframe reloads on tab change

### ISSUE THREAD

**Issue by hoanghuynh** [angular/components#22993]
#### Reproduction

1. Embed an iframe in a tab content
2. Move to another tab and switch back
3. The iframe is reset

Preview : https://stackblitz.com/edit/tab-iframe-reset?file=src/app/app.component.html

(This is reported previously as #5239.)
 
#### Expected Behavior

The iframe doesn't reload.

#### Actual Behavior

The iframe reloads.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/19480.

**Comment by hoanghuynh** [comment]
Thank for the quick triage and the MR @crisbeto!
