### ISSUE TITLE
mat-chip-list drag and drop sample does not work well and should be removed

### ISSUE THREAD

**Issue by simeyla** [angular/components#23025]
#### Documentation Feedback

The sample for `mat-chip-list` contains a drag and drop demo.
This demo works fine as it stands because the number of chips is small.

HOWEVER drag and drop functionality does NOT work with `mat-chip-list` if the list wraps. 

If you resize the browser it's literally impossible to drag and drop these chips to a useful position:

![image](https://user-images.githubusercontent.com/3656278/122657370-cbe27100-d117-11eb-9f76-58b6d4be519b.png)

The reason this occurs is that the order of items in a drag and drop list is determined [by this function](https://github.com/angular/components/blob/4caf039949cbd0ce1bf598936fac0ac3faba5398/src/cdk/drag-drop/drop-list-ref.ts#L624): 

```
private _cacheItemPositions() {
    const isHorizontal = this._orientation === 'horizontal';

    this._itemPositions = this._activeDraggables.map(drag => {
      const elementToMeasure = drag.getVisibleElement();
      return {
        drag,
        offset: 0,
        initialTransform: elementToMeasure.style.transform || '',
        clientRect: getMutableClientRect(elementToMeasure),
      };
    }).sort((a, b) => {
      return isHorizontal ? a.clientRect.left - b.clientRect.left :
                            a.clientRect.top - b.clientRect.top;
    });
  }
```

This function literally sorts the order of items based on the visible X and Y position on screen. Clearly this will not work if the items wrap since the first item on each row will contain an X coordinate of zero! 
**Edit: Just found a [tracking issue](https://github.com/angular/components/issues/13372) for this already.**

I spent A LOT of time trying to design drag and drop functionality around chip lists but everything is now broken since I'm finding out they don't work with real world data (like a narrow column with 20 chips). 

Therefore either: 

1) The sample should be removed from the docs because it isn't scalable and will only trip people up.
2) A note needs to be added that it only works for a single row of chips that don't wrap.

Related issue: https://github.com/angular/components/issues/13215

Original PR to add the sample: https://github.com/angular/components/pull/15276

**Comment by crisbeto** [comment]
I'll close this as something that should be resolved by https://github.com/angular/components/issues/13372. Mixed orientation support for drag&drop is on our roadmap.
