### ISSUE TITLE
bug(Themeing): Angular Material 12.0.5 Custom Theme generated not working. 

### ISSUE THREAD

**Issue by tgajdo** [angular/components#23021]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/components-issue-ynarhw

Steps to reproduce:
1. create new angular project
2. ng add @angular/material 
3. select custom theme
 
 
#### Expected Behavior

Custom theme generated should work out of the box

#### Actual Behavior

I get the following error:
```
./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "@include mat": expected 1 selector or at-rule, was ".core();"
        on line 10 of src/styles.scss
>> @include mat.core();
```
However it seems the main even the `@use '~@angular/material' as mat;` line won't work as I can't ctrl+click to find it. 

#### Environment

- Angular: 12.0.5
- CDK/Material: 12.0.5
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
I just tried generating a new project based on the steps above and it worked as expected. What command do you get the error on? I was testing with `ng serve`. Also can you check if there's `node-sass` in the `package.json`? The `@use` syntax isn't supported by the `node-sass` package, only the official `sass`.

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.
