### ISSUE TITLE
bug(CdkStepper): Does not automatically assign roles or aria labels for accessibility like it says it will in the documentation

### ISSUE THREAD

**Issue by Jacobra93** [angular/components#23044]
#### Reproduction

Issue is present in provided example from documentation: 
https://stackblitz.com/angular/xaanarvvorqn?file=src%2Fapp%2Fcdk-custom-stepper-without-form-example.ts

Steps to reproduce:
1. Extend the cdkStepper for a custom component
 
#### Expected Behavior

In the CdkStepper documentation overview there is an "Accessibility" section, where it says it automatically sets roles and aria labels. I do not see these being set in the example cdkStepper in stackblitz or in my project. Not sure if there is something special I need to do, but since it said it did it automatically by default I assumed nothing special had to be done.

#### Actual Behavior

No roles or aria labels are automatically set.

#### Environment

- Angular: 12
- CDK/Material: 12

**Comment by crisbeto** [comment]
I suspect that this has been copied over from the docs for the Material stepper.

**Comment by Jacobra93** [comment]
Gotcha, so the fix would just be that section being removed from the CdkStepper docs?

**Comment by crisbeto** [comment]
The fix would be mentioning that it doesn't come with accessibility treatment and saying what the recommendation would be. Although it is a little weird that we have one directive (the step header) that comes with a `role`.

**Comment by Jacobra93** [comment]
Sounds good. Speaking of the step header directive, as far as I can tell the FocusableOption and the focus method doesn't do much. I assumed if I called the focus method when using the left and right keys to navigate between the steps, it would get the focus-visible to that step header but it doesn't.
