### ISSUE TITLE
bug(mat-datatable): styling issue in 'Arrow' type sorting icon in Mat-Datatable	

### ISSUE THREAD

**Issue by snehil-agrawal** [angular/components#23048]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://material.angular.io/components/table/examples#table-http

Steps to reproduce:
1. Notice sort icon
2. icon's stem is pushed slightly to rightwards.
 
 
#### Expected Behavior

What behavior were you expecting to see?
Icon's stem should be positioned horizontally center.

#### Actual Behavior

What behavior did you actually see?
Icon's stem is positioned rightwards and not exactly touching vertex of `v` shape.

#### Environment

- Angular: Angular 12
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
It looks correct to me. Can you post a screenshot of what it looks like for you?

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.
