### ISSUE TITLE
[google-maps] Unable to use in-built classes - Expose util classes

### ISSUE THREAD

**Issue by vijaypushkin** [angular/components#23058]
It is impossible to use methods like Point or Size classes

```
const point  = new google.maps.Point(0, 0)
                   ~~~~~~~~~~~~~~~
```
Uncaught ReferenceError: google is not defined

There is clearly no work around for this

**Comment by crisbeto** [comment]
We aren't doing anything to hide these classes. Either you haven't loaded the Google Maps API, or you're trying to access them before the API has finished loading.

**Comment by vijaypushkin** [comment]
I was using it before loading the Maps script, Got it, thanks
