### ISSUE TITLE
Mat Tab animationDuration="0ms" cannot be used with an index in a ngFor loop

### ISSUE THREAD

**Issue by cfoxy17** [angular/components#23065]
Angular 12.0.4 Angular Material Version 12.0.4

**Works:**

`

        <mat-tab-group` dynamicHeight>
        
          <ng-container *ngFor="let person of people; let k=index"> 
        
              <mat-tab label="{{person.firstName}}"></mat-tab>
        
          </ng-container>
        
        </mat-tab-group>

`

**Causes an out of memory error even with a list size of only 3:**

`

        <mat-tab-group dynamicHeight  animationDuration="0ms">
        
          <ng-container *ngFor="let person of people; let k=index"> 
        
              <mat-tab label="{{person.firstName}}"></mat-tab>
        
          </ng-container>
        
        </mat-tab-group>

`

If I remove the "let k=index" I do not see the out of memory error, or if I remove the animationDuration="0ms" I do not see the error. 

This seems to be a legitimate issue.

**Comment by crisbeto** [comment]
It seems to work for me here https://stackblitz.com/edit/angular-sn5v7r?file=src%2Fapp%2Ftab-group-basic-example.html. Can you post an example of it breaking?

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.
