### ISSUE TITLE
bug(datepicker): Currently selected month and day are highlighted when browsing a different year

### ISSUE THREAD

**Issue by jskorupski** [angular/components#23069]
#### Reproduction

Feel free to close this if this is intended behavior.
You can reproduce this with the default datepicker demo on the Angular Material site: https://material.angular.io/components/datepicker/overview

Steps to reproduce:
1. Open datepicker - by default, current date is selected
2. Go to year browser, change to different year than current
3. Notice that the current month, in this different year is highlighted blue as an Active Cell
4. Similarly, choosing a different month in this different year shows the selected day of the month highlighted blue for that different year AND different month.
 
 
#### Expected Behavior

What behavior were you expecting to see?
When selecting a new year that differs from the existing selection, I don't expect any months or days in that year be highlighted
If there IS a blue highlight, to help users find the same date in a different year, then I still don't expect the same day of the month on a totally different year AND month to also highlight blue. 

#### Actual Behavior

What behavior did you actually see?
Example: If my initial chosen date is August 1, 2021, then switching to 2022 shows August of 2022 highlighted, and August 1, 2022. In addition, September 1, 2022, October 1 2022, etc are all highlighted.

#### Environment

- Angular: Version as seen on demo site
- CDK/Material:Version as seen on demo site
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu, OS X, presumably Windows as well

**Comment by jskorupski** [comment]
Note that I believe one source of the issue, in the case of the month of a different year being highlighted, is that activeCell is enabled for any matching month, and does not take into account the selected year: https://github.com/angular/components/blob/master/src/material/datepicker/month-view.html#L25

**Comment by crisbeto** [comment]
I believe that this is intentional, because the `activeDate` is used as a starting point when navigating using the keyboard.

**Comment by crisbeto** [comment]
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.
