### ISSUE TITLE
[Feature] - Dynamic generation of Themes with just one css variable.

### ISSUE THREAD

**Issue by SvenBudak** [angular/components#23078]
I have so many questions and suggestions.... I do not know how to combine them in the smartest way, short and bundled into one question. I'll try: I'm planning a project where it is absolutely necessary to generate a theme dynamically from the backend with just one primary color variable. Because SCSS is a build language, this is only conditionally possible. I know you can use css variables with material color palettes. But then you would have to define a color in the backend for 100 - 900. and also for the A colors. After a long search I found something that seems to solve all my problems: https://artik-man.github.io/material-theme-creator/

Unfortunately this pure css solution only works with the old template syntax without @use. And I would like to wait for the new mdc release. Then this css solution will probably not work at all i think.

I don't know the best way to make you guys understand. But i have often needed this feature that i can change the whole theme with one css variable.

in the linked theme creator, there are 4 values: Hue, Saturation, Lightness and Contrast treshhold. I find this super... Can you imagine to add such support natively in the upcoming mdc update? That would make life easier for many people.

**Comment by wagnermaciel** [comment]
Unfortunately this is not supported with our current system. Perhaps @jelbourn can give insights into whether something like this would be possible in our future theming system.

**Comment by jelbourn** [comment]
Sometime in the next year we do plan on revamping our theming system. This would involve switching to CSS variables and aligning more closely with the current Material Design spec, and would _probably_ coincide with moving the MDC-based components to stable. However, we don't yet have the detailed design of what that would look like. 

If you want a generate a theme server-side, you can do that today by having an endpoint that serves a CSS file output from the Sass compiler (if your server is running node). Beyond that I don't there's there's much we can do here at the moment.
