### ISSUE TITLE
Material Table Dynamic (Unique) Columns for each Row 

### ISSUE THREAD

**Issue by junnyman** [angular/components#23079]
#### Feature Description

Hi, I am working on Material Table component and heavily use (nested) rowspan to dynamically group the rows. The rowspan in Mat-table automatically pushes rows and cells located under (nested and spanned) row to the left. Since nested levels are different on each group of rows, I need to insert compensating columns into some rows to align the table content. 

#### Use Case
In short, I need groups of rows having different set of columns.
So I tried to insert columns (cells) for each row group like this:
'<tr mat-row  *matRowDef="let row;columns: getColumns() ; when: isGroup; ">'
but I am not able to feed any arguments such as (item, index) into getColumns() in order to have unique columns in each group of rows.

Is there any work around for this issue or will there be any chance this becomes a new feature?
Since nested rowspan can happen as deep as 1 - 20, I thought making template for each group was not an option.

**Comment by jelbourn** [comment]
You can define multiple `mat-row` elements, each with its own set of columns, and use the `when` function to control when that row template is used.
