### ISSUE TITLE
feat(google-maps): Add (ready) event emitter

### ISSUE THREAD

**Issue by ilianiv** [angular/components#23072]
#### Feature Description

I need to subscribe for mapReady event. Could you add `@Output() ready`, just like the one in youtube-player?

https://github.com/angular/components/blob/70582c0ea22038878a5abfd26097b7f996841c47/src/youtube-player/youtube-player.ts#L181

#### Use Case

Do some work after google-map is initialised, like calling fitBounds() method or sending a directions request, etc...

**Comment by crisbeto** [comment]
I think the `idle` or `tilesloaded` events should be doing something similar already.

**Comment by ilianiv** [comment]
Idle fires multiple times. After panning or zooming. I’ve used it as a workaround 
gmap.idle.pipe(first()).subscribe()

**Comment by crisbeto** [comment]
I'm closing this, because there's a way to achieve the same with the existing API. In general we try not to diverge from the APIs that are exposed by Google Maps.
