### ISSUE TITLE
help(cdkDragDrop): Can't update element's position on screen within ngFor with array

### ISSUE THREAD

**Issue by frknfndk** [angular/components#23089]
#### What are you trying to do?

I am trying to update items position with cdkDragFreeDragPosition. It doesn't work in an ngFor element loop with position:absolute.

I update the array but it doesn't effect element's position on screen.

#### What troubleshooting steps have you tried?

I didn't try any troubleshooting. I am not sure but maybe this is a bug. 

#### Reproduction

You may find stackblitz URL to reproduce. 

https://stackblitz.com/edit/angular-fzqdyd?file=src/app/cdk-drag-drop-free-drag-position-example.ts

Steps to reproduce:
1.  Click on 'Change element position' button
2. You will see script is updated the array but element position is still same. 
  
#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because you're only changing the object properties, but since the object reference stays the same, change detection won't pick it up. Changing it to `this.dragFields[index].position = {x: 300, y: 40};` works.

**Comment by frknfndk** [comment]
Thank you very much! It solved my issue.
