### ISSUE TITLE
bug(DateAdapter): setLocale force formatting

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/components#23082]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-rue5uk?file=src/app/datepicker-locale-example.ts

Steps to reproduce:
1. On the input enter "03/10/1991"
2. Hit tab
3. The result becomes "10/03/1991"
 
If you comment out the `setLocale`, then the behavior disappear.
 
#### Expected Behavior
The input value should not be updated onBlur.

#### Actual Behavior
The input value is formatted on onBlur

#### Environment

- Angular: 12
- CDK/Material: 12.1.0
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by GrandSchtroumpf** [comment]
I think this error is also related to that fact that if I enter "27/01/1991" which is a valid value in French, the input will emit an error.
To reproduce:
1. https://stackblitz.com/edit/angular-rue5uk?file=src%2Fapp%2Fdatepicker-locale-example.ts
2. Enter "27/01/1991"
3. See Error

This happens with or without using `setLocale` explicitly

**Comment by wagnermaciel** [comment]
The native date adapter uses javascript's native `Date` which doesn't handle parsing date formats in locales other than en-US. I would recommend using the moment date adapter (like this https://stackblitz.com/edit/angular-rue5uk-nwvncm?file=src/app/datepicker-locale-example.ts) or writing your own date adapter using a date library https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings.
