### ISSUE TITLE
angular-google-maps: Implement "setZoom()" method

### ISSUE THREAD

**Issue by vadimluminous** [angular/components#23093]
#### Feature Description

Implement Set Zoom. Google Maps Javascript API has a setZoom method https://developers.google.com/maps/documentation/javascript/reference/street-view#StreetViewPanorama.setZoom but I do not see it in this angular package.

#### Use Case

Let's say you initially set the zoom level with

```
.ts
this.zoom = 9;
```

```
.html
[zoom] = "this.zoom"
```

Later on, the user zooms out and using 

`this.googleMap.getZoom() = 14`

Now if I were to again set 

`this.zoom = 9`

Nothing happens to the map. It's missing the setZoom feature it looks like.

**Comment by crisbeto** [comment]
Passing in another value to the `[zoom]` input calls `setZoom` internally. If the map isn't updating for you, it's likely because you aren't triggering change detection.
