### ISSUE TITLE
bug(cdk/drag-drop): Missing `cdkDrawPreviewContainer` directive?

### ISSUE THREAD

**Issue by maxime1992** [angular/components#23114]
#### Expected Behavior

What behavior were you expecting to see?

Being able to use `cdkDrawPreviewContainer` as state by the [doc on the repo](https://github.com/angular/components/blob/b92f97f55c8ed974f988897374622402fa3361c5/src/cdk/drag-drop/drag-drop.md#drag-preview-insertion-point) and the official documentation (which probably just reflects the markdown file): https://material.angular.io/cdk/drag-drop/overview#drag-preview-insertion-point

![image](https://user-images.githubusercontent.com/4950209/124455067-7352db00-dd89-11eb-8cd7-470754f3ec3b.png)

#### Actual Behavior

What behavior did you actually see?

This directive doesn't seem to be anywhere? Searching for it on all github only gives back that result where the doc mention it once: https://github.com/search?q=cdkDrawPreviewContainer&type=code

Looking in `angular/components` repo or even into the node_modules of my project for `cdkDrawPreviewContainer` doesn't seem to give anything. Was it removed maybe at some point? I'd really need it because I'm trying to reorder lines in a table and the whole layout is broken. I had good hopes with this one directive but unfortunately it doesn't seem to be available anywhere

#### Environment

- Angular: 12.1.0
- CDK/Material: 12.1.0
- Browser(s): Not relevant
- Operating System (e.g. Windows, macOS, Ubuntu): Not relevant

**Comment by crisbeto** [comment]
It's an input called `cdkDragPreviewContainer` on `cdkDrag`, there's just a typo in the docs. I've submitted a PR to fix it.

**Comment by maxime1992** [comment]
Awesome I'll try it out, thanks :pray: !
