### ISSUE TITLE
Add 'none' option to MatFormFieldAppearance type

### ISSUE THREAD

**Issue by rowe-stamy** [angular/components#23118]
appearance="none" is a convinient and clean way to modify the style of a form field.
Unfortunatly it works only with strictTemplates disabled in the moment.
Please extend the type definition of appearance tag on a mat-form-field with the 'none' option.

https://github.com/angular/components/blob/b682f84c43f05ed2b5b29b990aa8bf18a5170120/src/material/form-field/form-field.ts#L69

**Comment by crisbeto** [comment]
This isn't something that we'll support, because it isn't in the Material Design spec. If it happens to work right now, it's by accident.
