### ISSUE TITLE
bug(Table): mat-table inside a RTL parent cannot be scrolled horizontally

### ISSUE THREAD

**Issue by SepehrSepahi** [angular/components#23113]
#### Reproduction
[StackBlitz](https://stackblitz.com/edit/angular-gx3emn?file=src/app/table-basic-example.html)

Steps to reproduce:
1. Put a basic mat-table inside a RTL container (or RTL document)
2. It cannot be scrolled horizontally.
3. If you change RTL to LTR it works.
 
 
#### Expected Behavior

Material table should be horizontally scrollable while using RTL.

#### Actual Behavior

Material table breaks the page scrollability when RTL is used.

#### Environment

- Angular: 12.1.1
- CDK/Material: 12.1.1
- Browser(s): Edge 91.0
- Operating System: Windows 10

**Comment by crisbeto** [comment]
We aren't doing anything special for the overflow, it's just that you need the `dir="rtl"` to be on the overflowing element or one of its parents. Here's a working example https://stackblitz.com/edit/angular-gx3emn-e554pm?file=src/app/table-basic-example.html.

**Comment by SepehrSepahi** [comment]
Thanks, but adding  `overflow: auto` to the container breaks the `sticky: true` of the Material table. ([StackBlitz](https://stackblitz.com/edit/angular-gx3emn-yznqip?file=src/app/table-basic-example.html))

**Comment by crisbeto** [comment]
I posted that example to illustrate that we aren't doing anything special that would break scrolling. The fix for your app would likely be to put the `dir="rtl"` somewhere further up in the DOM.

**Comment by crisbeto** [comment]
I'm closing this since we don't do anything that would change the scroll behavior of a table. It's likely an issue on your end with where the `dir` attribute is being set.
