### ISSUE TITLE
help(CDK): Support RxJs 7

### ISSUE THREAD

**Issue by JorisDebonnet** [angular/components#23120]
#### Feature Description

Support RxJs 7.

#### Use Case

I would like to update my project to RxJs 7, but I can't, because @angular/cdk declares (since recently) a peerDependency for RxJs which is fixed to ^6.5.3.

Is there any incompatibility with RxJs ^7.0.0? If not, then I hope this can simply be updated in the package.json on the next release.

**Comment by crisbeto** [comment]
See https://github.com/angular/angular/issues/41897.

**Comment by JorisDebonnet** [comment]
Thank you.
