### ISSUE TITLE
bug(strong-focus): Mixin causes error when passed color value

### ISSUE THREAD

**Issue by literalpie** [angular/components#23133]
Colors as an input [was supported](https://github.com/angular/components/blob/12.0.x/src/material/core/focus-indicators/_focus-indicators-theme.scss#L28) in 12.0, and [is not supported in 12.1.x](https://github.com/angular/components/blob/12.1.x/src/material/core/focus-indicators/_focus-indicators-theme.scss#L15). I think this is an unintentional breaking change.

#### Reproduction

Steps to reproduce:
This works in 12.0.2, but not in 12.1.1
```
@include mat-strong-focus-indicators-theme(blue);
```
 (I don't think custom themes work in Stackblitz?)
 
#### Expected Behavior

It should build properly

#### Actual Behavior

Building fails and there is an error

> Sass error: $map2: blue is not a map

#### Environment

- Angular: 12.1
- CDK/Material: 12.1.1
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Windows and Mac

See conversation in #23016. This was fixed, but has not been merged because it was marked as a feature, not a bug fix. I think this should be important enough to prioritize a fix asap since it breaks code that previously works

**Comment by wagnermaciel** [comment]
Fixed by https://github.com/angular/components/pull/23134.
