### ISSUE TITLE
Datepicker shows one day behind in Angular 12

### ISSUE THREAD

**Issue by PierreKoung** [angular/components#23139]
Here is a short video of how it is doing 

https://user-images.githubusercontent.com/44596656/125050385-339a3500-e0a2-11eb-9b0e-46f8fa476558.mp4

About errors, there are no errors on the component everything looks nice but this problem still persist.

> About my build environment : 
**OS**: Windows 10
**Angular Version**: 12

I still have the issue

_Originally posted by @PierreKoung in https://github.com/angular/components/issues/23132#issuecomment-877022770_

**Comment by jelbourn** [comment]
This isn't a bug in the component- it is the behavior of the native JavaScript `Date` object. In particular, Daylight Saving Time between locales causes the time portion of the date value to cross the day boundary. For this reason, among many other, we recommend people use a full i18n library.

**Comment by PierreKoung** [comment]
> i18n library

What will be the best i18n Library for fix this problem please ?
Ngx-translate
i18Next
or other ?
