### ISSUE TITLE
docs-bug(COMPONENT): mat-stepper 

### ISSUE THREAD

**Issue by renzobarrionuevo** [angular/components#23131]
In the stepps examples when one copies the example and runs it in an angular project they provide an error due to this code line: <mat-stepper [linear]="isLinear" #stepper>.
gives us the following error when compiling:
error NG8001: 'mat-stepper' is not a known element
It gave me many problems, to the point of wanting to stop using material and the solution was as simple as putting:
<mat-horizontal-stepper [linear]="isLinear" #stepper>.

Maybe there is some other way that it works as it is written in the documentation but I really couldn't find it.

**Comment by crisbeto** [comment]
There are a couple of reasons why it could've happened:
1. You didn't import the `MatStepperModule` in the correct place.
2. You are on an older version of Material that doesn't support `mat-stepper`, but only `mat-horizontal-stepper` and `mat-vertical-stepper`. We only introduced `mat-stepper` in version 12.0.0.

**Comment by renzobarrionuevo** [comment]
I was use get started guide to start my project and install Material with command: ng add @angular/material
I am going to review the version that I installed. Thank you very much for your reply.
