### ISSUE TITLE
feat(MatTab): Handle before MatTab change event.

### ISSUE THREAD

**Issue by IvanWSM** [angular/components#23156]
#### Feature Description

Output an event when another tab is clicked but before the actual tab is selected.

#### Use Case

Having a form on each tab or other components that handle states. This would allow users to capture the change event, check for unsaved changes and reacting accordingly, for example, if I have unsaved changes on a form inside a tab, and I try to move to another tab, I could display a confirmation dialog letting the user know about the unsaved changes and allowing them to either save the changes and moving or discarding them and moving on.

**Comment by wagnermaciel** [comment]
This seems like an unnecessary feature. There are alternate solutions that you could use to get around this - for example, you could subscribe to events on input controls. We've avoided adding events for both before and after in order to not bloat the API

**Comment by IvanWSM** [comment]
That's if you only think about inputs, it could be any component that handles flags as properties, since MatTabs accept other custom components and even allows them to be lazy-loading I think it would be pretty useful to expect that some of these components might have data that you might want to make sure stays updated when moving to other tabs without removing lazy-loading

**Comment by wagnermaciel** [comment]
I'm fairly confident that in these cases another solution could be used to handle these problems without having to introduce more to our API. If we tried to handle all cases like this our components would be unmanageable
