### ISSUE TITLE
mat-error not showing error when control is wrapped in a component

### ISSUE THREAD

**Issue by lslocum** [angular/components#23168]
#### Reproduction
https://stackblitz.com/edit/angular-np88sv

Steps to reproduce:
1. Open the stackblitz
2. Touch the email control and move away. Notice the required error shows.
3. Enter a word or a letters then move away. Notice the email error does not show, but the control clearly knows it has an error.
 
 
#### Expected Behavior

What behavior were you expecting to see?
The message "{{value}} is not a valid email" and the control has red border.

#### Actual Behavior

What behavior did you actually see?
No border on the control and no error being reported through mat-error

#### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This is working as expected as Angular is designed. The internals of an Angular component are a black box, so the form field would have no way of "seeing" the `mat-error` inside a custom component.
