### ISSUE TITLE
bug(mat-menu): Button highlighting persists even after different button is highlighted

### ISSUE THREAD

**Issue by SLKnutson** [angular/components#23175]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- https://stackblitz.com/edit/angular-yrcycm?file=src/app/menu-nested-example.html

Steps to reproduce:
1. Click to open "Animal Index"
1. Mouse over "Vertebrates" to expose submenu
1. Mouse over  "Reptiles" to expose submenu
1. Move mouse down to "Birds"
 
 
#### Expected Behavior

The highlighting on Reptiles should be removed, only Birds should be highlighted

#### Actual Behavior

Both Birds and Reptiles are highlighted.
![image](https://user-images.githubusercontent.com/49452862/125805231-151be093-a852-4fa6-8376-ad0483c21455.png)

#### Notes
This has something to do with using both `ChangeDetectionStrategy.OnPush` and `<ng-template matMenuContent>`. If either is removed, the bug goes away. The reproduction was made by taking the example from the angular documentation and adding those two things. Thanks!

**Comment by jelbourn** [comment]
I confirmed that this is fixed in the MDC menu (I currently have a demo deployed on https://jelbourn-dev.web.app)

**Comment by crisbeto** [comment]
I think that this is unrelated to MDC, but some change detection weirdness around `matMenuContent`.
