### ISSUE TITLE
feat(mat-icon): Dinamically add a css class in the html replicating the ligature text for webfont

### ISSUE THREAD

**Issue by ivan-saorin** [angular/components#23183]
#### Feature Description

It would be nice that the `mat-icon` would add to the generated html a css class replicating Its text.

E.g. `<mat-icon>edit</mat-icon>` --> `<mat-icon class="md-edit">edit</mat-icon>`

This would allows to target the element via css to further customize the element.

#### Use Case

Let's imagine we just installed a library via `npm i` with a custom component that use `mat-icon` (via web-font) internally to display an icon. In our application we would like to customize that icon due to internal company rules.
As far as I have understood there is no way to achieve that result via css. And as we are talking about a compiled component we don't control, we cannot change It to use svg instead.
The feature proposal would allow some override through css.

**Comment by PowerKiKi** [comment]
See https://github.com/angular/components/issues/23195 for a proposal to solve both this issue and the search engine issue at once.
