### ISSUE TITLE
Mat paginator in multiple MatTables

### ISSUE THREAD

**Issue by alexisml-12** [angular/components#23198]
Hi I have multiple MatTables in my template in this way

    `
    <div id="GroupFor">
            <div fxLayout="row wrap" *ngFor = "let group of groups | searchGroupFilter:searchText">
         //group data
       </div>
    </div>
    <div fxFlex.gt-lg="82" fxFlex.gt-md="81" fxFlex.gt-xs="100" fxFlex="100" id="tableDiv">
      <mat-card class="mat-card-employee">
        <mat-card-content>
          <div class="table-responsive">
            <table mat-table [dataSource]="dataSource.filteredData | filterGroups:group.id" class="table employee-list no-wrap">
              //rows and columns
            </table>
            <mat-paginator #paginator [pageSizeOptions]="[5, 10, 20]" showFirstLastButtons></mat-paginator> 
          </div>
        </mat-card-content>
      </mat-card>
      </div>
     </div>
    `

And here I have a pipe filter to list in the MatTable all the users according to their GroupId, I realized that the mat-paginator is undefined because of that, because there are multiple MatTables and I need help to know how to make the mat-paginator work in the multiple MatTables, here is my `component.ts`. 

    `@ViewChild(MatTable, { static: true }) table: MatTable<any> = Object.create(null);

    displayedColumns: string[] = ['name', 'username' , 'email', 'action'];
    @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator = Object.create(null)

    ngOnInit(): void {
    this.Groups();
    
    }
    ngAfterViewInit(): void {
     this.dataSource.paginator = this.paginator;
     console.log(this.paginator);
    }

    Groups(){
    this.dataSource = new MatTableDataSource();
    this.apiSvc.Cards().subscribe((rsp: any) => { 
        this.groups = rsp;
        
    });
    
    this.apiSvc.Cards().pipe(
        switchMap((rsp:any[])=>{
            return forkJoin(
                rsp.map(x=>this.apiSvc.Groups(x.id))
                )
            })
    ).subscribe((res:any[])=>{

        this.dataSource.data = res;
        this.dataSource.paginator = this.paginator;
        
     });
    }`

Please I need help with this, thanks beforehand

**Comment by crisbeto** [comment]
When you query for the paginator using `@ViewChild(MatPaginator)` the framework will find the first paginator and stop searching. If you have multiple on the page and you want to find a specific one, you can pass in a name to `ViewChild` instead:


```
<mat-paginator #paginator-one></mat-paginator>
<mat-paginator #paginator-two></mat-paginator>
```

And then in the component you'd have:

```
@ViewChild('paginator-one') paginatorOne: MatPaginator;
@ViewChild('paginator-two') paginatorTwo: MatPaginator;
```

**Comment by alexisml-12** [comment]
Hi @crisbeto, thanks for taking the time to answer me, I tried in that way but I don't have more than 1 table, I used the same template but is inside of a loop  `<div fxLayout="row wrap" *ngFor = "let group of groups | searchGroupFilter:searchText">` , that's why I need this filter `filterGroups:group.id` in the table tag, so it doesn't work for me in that way but anyways thank you!
