### ISSUE TITLE
bug(MatTabNav): scrollable MatTabNav bug

### ISSUE THREAD

**Issue by tworry** [angular/components#23201]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- [https://stackblitz.com/edit/angular-b4mepp?file=src/styles.scss](https://stackblitz.com/edit/angular-b4mepp?file=src/styles.scss)

Steps to reproduce:
1. set MatTabNav [disablePagination]="true"
2. change mat-tab css in style.scss
3. add more tab-link to make the MatTabNav scrollable
4. sroll to the end,and click the last link
 
#### Expected Behavior

the clicked link is active, the scroller is not changed

#### Actual Behavior

the MatTabNav is back to the start,and the clicked link is not active,just focused

#### Environment

- Angular:12.1.2
- CDK/Material:12.1.1
- Browser(s):chrome 91.0.4472.77
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
First of all, this isn't something we support since you're overriding the built in styles. 

That being said, there's an existing PR that should fix your issue too https://github.com/angular/components/pull/21911.
