### ISSUE TITLE
bug(MatIcon): Creating a Self Initializing Mat Icon Asset Service?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#23221]
#### Reproduction

[This SO link has the description and Stackblitz](https://stackoverflow.com/questions/68489777/angular-12-nullinjectorerror-no-provider-for-assetservice
)

This did work in Angular 11, and [per earlier discussions](https://github.com/angular/angular/issues/36631) it was supposed to work in Angular 12 ...

 
 
#### Expected Behavior

The service should be inject by the module and self initialize.

What behavior were you expecting to see?

#### Actual Behavior

An null injection error is thrown ...

#### Environment

See Stackblitz ...

**Comment by jelbourn** [comment]
The problem here is that you have a circular TypeScript dependency between `AssetsModule` and `AssetsService`, it's surprising it ever worked before. You can eliminate the circular dep by reorganizing the code, such as by using an `InjectionToken` and an interface.
