### ISSUE TITLE
Menu is auto focusing the first item even when it is not opened via keyboard

### ISSUE THREAD

**Issue by DevCeN** [angular/components#23232]
https://github.com/angular/components/blob/e5d685a59c8c9a5cff33aac8d6876339e4c109be/src/material/menu/menu-trigger.ts#L350-L360

This method is supposed to auto focus the first active menu item when the menu is opened via keyboard only (which makes sense), however, it doesn't seem to be checking the opening source and does the auto focus anyway, which is not good when the menu is opened by mouse (see [this](https://stackoverflow.com/questions/68493744/stop-angular-material-menu-from-showing-url-link-when-not-hovering-on-a-menu-ite) as an example issue). Potentially also bad for touch input? 

Please restore the original behaviour of this method and back port the fix to v10 as well, thank you!

**Comment by crisbeto** [comment]
Focus has to always be moved. The `focusFirstItem` call only determines if the item is going to be highlighted as a result of the interaction.

**Comment by crisbeto** [comment]
I'm closing the issue, because it works as expected. Focus always has to be moved, it's just a matter if we style it as focused.

**Comment by DevCeN** [comment]
@crisbeto hummm, if you pay some attention to the comment at line 352 "the menu was opened via the keyboard." you should see the issue is the focus should only be moved if the menu is opened via the keyboard, rather than always as you have put it.

**Comment by crisbeto** [comment]
Focus has to always be moved, that comment refers to focus _indication_ not being added when it's opened using the mouse. If we didn't move focus, it would stay behind on the menu trigger which would allow the user to interact with content behind the menu. It also won't allow us to pick up keyboard events coming from inside the menu.
