### ISSUE TITLE
help(MatTab): Lazy loading TemplateRef in a loop

### ISSUE THREAD

**Issue by Cohaven** [angular/components#23246]
#### What are you trying to do?

I'm trying to lazy load TemplateRefs as content of material tabs within a loop.

```
<mat-tab-group>
  <mat-tab *ngFor="let tab of tabs">
    <ng-template mat-tab-label>
      <span class="tab-label">
        <icon [name]="tab.icon" size="small"></icon>{{tab.label}}
      </span>
    </ng-template>
    <ng-template matTabContent>
      <ng-container *ngTemplateOutlet="tab.contentTemplate"></ng-container>
    </ng-template>
  </mat-tab>
</mat-tab-group>
```

#### What troubleshooting steps have you tried?

The content template is displayed, but it is not being lazy loaded. When I try to display static tab content instead of a template, lazy loading seems to work.
  
#### Environment

- Angular: 11.0.9
- CDK/Material: 11.2.2
- Browser(s): Google Chrome
- Operating System: macOS

**Comment by crisbeto** [comment]
Can you post what the full code looks like? Setting the `matTabContent` like you did should be enough to lazy load it.

**Comment by Cohaven** [comment]
Sorry for the delay. Here's a stackblitz example: https://stackblitz.com/edit/angular-rxjs-sandbox-nmdp6g?file=src/app/components/tab-group/tab-group.component.ts

**Comment by crisbeto** [comment]
The problem with the "Template version" is that even though you're rendering the content into an `ng-template` using `<ng-template><ng-content></ng-content></ng-template>`, it's going to be rendered initially. What happens under the hood is that Angular will create the content and then put it into the `ng-template`. We can't do much about it in Material, because it's just how the framework works.

**Comment by Cohaven** [comment]
I see. Do you have any suggestions on how to accomplish my lazy loading goal?

**Comment by crisbeto** [comment]
You'd have to do something similar to what we're doing: pass in the content wrapped inside an `ng-template` already. So instead of doing:

```
<app-tab>
  content
</app-tab>
```

You'd have to do something like:

```
<app-tab>
  <ng-template>content</ng-template>
</app-tab>
```

**Comment by Cohaven** [comment]
Do you mean like this? https://stackblitz.com/edit/tab-lazy-load-template-nfcx1p?file=src/app/app.component.html
It doesn't seem to work. If you have some time, I would really appreciate a stackblitz example of how content-projected lazy loading can work with matTabContent. You can use my example as a starting point.

**Comment by Cohaven** [comment]
I've implemented this, which seems to work. 
https://stackblitz.com/edit/tab-lazy-load-template-y3qrzj?file=src/app/components/tab-group-template/tab-group-template.component.ts
