### ISSUE TITLE
feat(matautocomplete): Make matautocomplete work with contenteditable

### ISSUE THREAD

**Issue by bjdash** [angular/components#23257]
#### Feature Description

Currently [matAutocomplete] is only supported with text inputs. Using it with a div with contenteditable throws below error.
`Can't bind to 'matAutocomplete' since it isn't a known property of 'div'.`

#### Use Case

It will be useful to support autocomplete with custom inputs that uses contenteditable.

Example use case:
- Open [https://apic.app/online](https://apic.app/online)
- In the welcome screen under **I want to start with** select **API testing**
- In the request panel you will see few options like URL params, Headers, Body etc. Select **Headers**
- The text boxes shown here are using contenteditable divs
- Typing in `a` shows few suggestions but typing {{a}} uses contenteditable to highlight the values with custom styling

**Comment by Splaktar** [comment]
![Screen Shot 2021-08-09 at 13 39 18](https://user-images.githubusercontent.com/3506071/128749532-afb80f0e-70dd-46dd-a9eb-65194d650a0b.png)

To save others from digging down into the link above to find this example. See above.

**Comment by crisbeto** [comment]
We talked about this and we decided not to support it, because we can't guarantee good accessibility when the autocomplete trigger is a `contenteditable` element. That being said, you should be able to do it yourself by creating your own autocomplete trigger directive that extends the Material one:

```
import {MatAutocompleteTrigger} from '@angular/material/autocomplete';

@Directive({
  selector: '[contenteditable][matAutocomplete]'
})
export class CustomAutocompleteTrigget extends MatAutocompleteTrigger {};
```
