### ISSUE TITLE
bug(mat-grid-list): rowHeight does not adapt for smaller screens when content is large

### ISSUE THREAD

**Issue by CruzST** [angular/components#23264]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-kmvrtm?file=src/app/grid-list-overview-example.html
https://angular-kmvrtm.stackblitz.io

Steps to reproduce:
1.  Click on above stacksblitz link or the application link
2. Observe the content in the first box fits
3. Resize the window and observe that the content of the first box gets cut off
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expected the row height to adjust and compensate for overflow and increase to ensure all content is visisble

#### Actual Behavior

What behavior did you actually see?
The content gets cut off.
![image](https://user-images.githubusercontent.com/30658915/127390025-83013cce-f6db-4fe8-a4a4-05996f8f4251.png)

#### Environment

- Angular: 11.X
- CDK/Material: 9.X
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Comment by crisbeto** [comment]
The row height isn't meant to resize based on the content, but rather to line up with the rest of the rows. I'm closing the issue, because it works as expected. You might be able to get the same effect with a bit more flexibility using CSS grid.
