### ISSUE TITLE
bug(youtube-player): Video is zoomed out instead of fitting to the window in mobile mode

### ISSUE THREAD

**Issue by omega17** [angular/components#23268]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Go the existing demo https://angular-youtube-player.stackblitz.io/
2. Goto chrome dev tools to select mobile mode. Reload the screen, the video is not adjusted for mobile mode. Its zoomed out.
 
 
#### Expected Behavior

What behavior were you expecting to see?
The youtube-player should fit to the mobile screen like its doing in desktop and tablet modes.

#### Actual Behavior

What behavior did you actually see?
Video is zoomed out and does not fit to the screen

#### Environment

- Angular: 10.2
- CDK/Material: Using angular CLI
![Capture](https://user-images.githubusercontent.com/59318104/127432431-688d678f-06ac-426e-b623-f8f92dcc1bab.PNG)

- Browser(s): Chrome (Latest version)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because the player defaults to a width of `640px`. It should work if you do something like `<youtube-player width="100%"></youtube-player>`.

**Comment by crisbeto** [comment]
As far as I can tell, this is working as expected (assuming a `width` is provided). I'm closing the issue, but it can be reopened if there is any new information.
