### ISSUE TITLE
bug(mat-date-range-picker): entering startDate greater than endDate shows invalid date error even after changing the dates

### ISSUE THREAD

**Issue by ValdasGal** [angular/components#23271]
**Reproduction**

https://angular-tcj5rd.stackblitz.io

Steps to reproduce:

1. Open stackblitz
2. Enter 3/1/21 (with keyboard) as `Start Date` (any date greater than `End Date` works)
3. Click outside of the daterange (so input gets blurred and validation error is visible)
4. Enter 4/1/21 (with keyboard) as `End Date`

**Expected Behavior**

After changing `End Date` to be greater than `Start Date` validation should be updated.

**Actual Behavior**

Validation error is being displayed until you change `Start Date` to be earlier than `End Date`.
Selecting same dates in datepicker still shows an error, until `Start Date` is changed to another date.

**Environment**

- Angular: 12.1.4
- CDK/Material: 12.1.4
- Browser(s): irrelevant
- Operating System (e.g. Windows, macOS, Ubuntu): irrelevant

**Comment by crisbeto** [comment]
This sounds identical to https://github.com/angular/components/issues/21875.
