### ISSUE TITLE
bug(MatMenu): Not accessible by keyboard

### ISSUE THREAD

**Issue by vyatkin0** [angular/components#23278]
#### Reproduction

All examples with menu on page https://material.angular.io/components/menu/examples
 
#### Expected Behavior

DOWN_ARROW: Focuses the next menu item
UP_ARROW: Focuses previous menu item

Html code for "Basic menu" should be like this:
```
<div class="mat-menu-content ng-tns-c38-25">
<button mat-menu-item="" class="mat-focus-indicator mat-menu-item ng-tns-c38-25" role="menuitem" tabindex="0" aria-disabled="false">Item 1<div matripple="" class="mat-ripple mat-menu-ripple"></div>
</button>
<button mat-menu-item="" class="mat-focus-indicator mat-menu-item ng-tns-c38-25" role="menuitem" tabindex="-1" aria-disabled="false">Item 2<div matripple="" class="mat-ripple mat-menu-ripple"></div>
</button>
</div>
```
#### Actual Behavior

Menu is not accessible by keyboard.

Wrong html code is generated for menu:
```
<div class="mat-menu-content ng-tns-c38-25">
<button mat-menu-item="" class="mat-focus-indicator mat-menu-item ng-tns-c38-25" role="menuitem" tabindex="0" aria-disabled="false">Item 1<div matripple="" class="mat-ripple mat-menu-ripple"></div>
</button>
<button mat-menu-item="" class="mat-focus-indicator mat-menu-item ng-tns-c38-25" role="menuitem" [tabindex="0"  - THIS IS ERROR!!!] aria-disabled="false">Item 2<div matripple="" class="mat-ripple mat-menu-ripple"></div>
</button>
</div>
```
#### Environment

All examples with menu on page https://material.angular.io/components/menu/examples

**Comment by crisbeto** [comment]
It seems to work for me:
![demo](https://user-images.githubusercontent.com/4450522/127657289-cbe9cd3e-643a-4796-8215-50b15025fc1a.gif)

**Comment by tokenbox-io** [comment]
Sorry it's my mistake. Please disregard the issue.

**Comment by vyatkin0** [comment]
Sorry it's my mistake. Please disregard the issue.
