### ISSUE TITLE
bug(Materail): Custom component theming mixins no longer working in Angular 12

### ISSUE THREAD

**Issue by jamesg-gxg** [angular/components#23281]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1.  Try to use _mat-button-theme-property amongst others in custom component theming for angular material
 
#### Expected Behavior

What behavior were you expecting to see?
My solution build without errors and properly custom theme my component

It seems to have been renamed to theme-property in [here](https://github.com/angular/components/blob/master/src/material/button/_button-theme.scss#L64)

Tried using that but it didn't work

It seems to be purposefully hidden now
[here](https://github.com/angular/components/blob/master/src/material/button/_button-legacy-index.scss)

Are we not allowed to use it? 

#### Actual Behavior

What behavior did you actually see?
Its breaking my build because it cannot find mixin _mat-button-theme-property

#### Environment

- Angular:  12
- CDK/Material: 12
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment]
This is a private API that is now being hidden correctly. Previously it was exposed by accident, because Sass didn't have a way of hiding exports. The convention for private APIs in Sass is symbols starting with an underscore or with `private`.
