### ISSUE TITLE
help(MatTab): Cutomisable Tab Overflow

### ISSUE THREAD

**Issue by shammy8** [angular/components#23292]
Is there a way to change the default behaviour of handling tab overflow in MatTab? I would like to remove the default left right arrows and add a button which will open a drop down menu with all the tabs in a list. Is there a easy way to do this? If some one can point me in the general direction that'll be appreciated. Thanks.

**Comment by crisbeto** [comment]
It's not something that we support officially, but I've seen something similar in another issue report https://github.com/angular/components/issues/23241.
