### ISSUE TITLE
feat(mat-experimental): theme components the MDC way

### ISSUE THREAD

**Issue by austinw-fineart** [angular/components#23299]
#### Feature Description
With the MDC components in Angular Material, I'd like to be able to use my existing theme with them. The experimental package currently has mixins for theming the MDC components using... a palette, from Material 1. My understanding is that this exists for legacy reasons, but I would like a way to have Angular Material consume theming options from MDC Web, or at the very least something more inline with what MDC Web offers.

#### Use Case
In MDC Web, theming is done like this:
```
@use "@material/theme/theme-color" with (
  $primary: #FEDBD0,
  $on-primary: #442C2E,
);
@use '@material/typography/variables' as typography-variables with (
  $styles-button: ( letter-spacing: normal ),
);
```
Compared to whatever this is:
```
@use '~@angular/material' as mat;
@use '~@angular/material-experimental' as mat-experimental;
$my-primary: mat.define-palette(mat.$indigo-palette);
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);
$my-theme: mat.define-light-theme((
  color: (
    primary: $my-primary,
    accent: $my-accent
  ),
  typography: mat-experimental.define-mdc-typography-config(),
));
@include mat-experimental.all-mdc-component-themes($my-theme);
```

**Comment by amysorto** [comment]
Closing this old issue, but our [theming guide](https://material.angular.io/guide/theming) has updated information on how to theme the components.
