### ISSUE TITLE
MAT Select: Getting Container element empty error using HTML Validator.

### ISSUE THREAD

**Issue by JainAshish** [angular/components#23301]
Issue Description:
Using Siteimprove Accessibility Checker browser extension tool, getting Container element empty error on the mat select component.

Steps to reproduce:
1. Add Siteimprove Accessibility Checker extension from Chrome Store and run the tool on the following URL: https://rxbpoevrxqj.angular.stackblitz.io/
2. Validate the issue page which stated " Container Element is empty" for the mat select component.
 
 
Expected Behavior:
When we have an element with an explicit semantic role that has at least one of its required owned elements, as we used role="listbox" and its owned element role "listitem" or <li> should be used instead of role="option".

Actual Behavior:
With Mat select component, role="option" used which is not owned element role of the "listbox".

#### Environment

- Angular: 7.3.7
- Browser(s): Chrome, Edge
- Operating System: Windows, MacOS

![image](https://user-images.githubusercontent.com/3896163/128032636-44bf6895-2b6f-436d-b88a-c06f6fe37b1f.png)

**Comment by crisbeto** [comment]
It's likely because we only render the options to the DOM while the select is open. I'm closing the issue, because we've tested this with screen readers in the past and it isn't a problem for accessibility, even though it gets flagged by some automated tooling.
