### ISSUE TITLE
cdkDragPreviewContainer not working

### ISSUE THREAD

**Issue by pedrollanes** [angular/components#23303]
I have put a dialog with a ckdDrag list, but the dragview goes behind the dialog, and I can see that the drag preview is attached to body. I have tried to  use cdkDragPreviewContainer ="parent" but it doesn't do anything. So I think that the directive property doesn't work.

`<ng-template #dialog>`
`  <div class="container-dialog" >`
`    <div class="column0">`
`      <div class="catalog-panel">`
`        <div class="catalog-items-panel"`
`          cdkDropList`
`          [cdkDropListData]="notAssigned"`
`          (cdkDropListDropped)="dropNotAssigned($event)">`
`          <div class="image-panel" *ngFor="let catalogue of notAssigned" cdkDrag [cdkDragData]="catalogue"`
`            cdkDragPreviewContainer ="parent">`
`            <img class="catalog-image" [src]="catalogue.background" />`
`          </div>`
`        </div>`
`      </div>`
`    </div>`
`</ng-template`

**Comment by crisbeto** [comment]
What version of Angular are you running? The `cdkDragPreviewContainer` input was introduced in version 12.0.0.

**Comment by pedrollanes** [comment]
That's was the problem. I upgraded to 12.0.0 and everything was fine. Thanks¿
