### ISSUE TITLE
feat(COMPONENT): multibranch hierarquical tree

### ISSUE THREAD

**Issue by fergardi** [angular/components#23335]
#### Feature Description

Hello everyone. I would like to know if there is anything inside (official) Material Design components library than can achieve the following result obtained from [beautifull-skill-tree](https://github.com/andrico1234/beautiful-skill-tree#examples), a React component:

![image](https://user-images.githubusercontent.com/3602272/128821179-0cc14c8c-20b1-456f-a10d-1b96f4b8cf77.png)

#### Use Case

I know there is a [hierarquical tree](https://material.angular.io/components/tree/overview) but only allows for "single" (axis) branches. This could be handy for showing a multibranch tree (like a genealogical family tree, or a game skills tree, for instances) the user can interact with.

Thanks for your insights.

**Comment by jelbourn** [comment]
Since Angular Material is focus on building things in the Material Design spec, I don't see us pursuing a feature like this.
