### ISSUE TITLE
bug(dev-infra): 404 when installing @angular/material-luxon-adapter@12.2.0

### ISSUE THREAD

**Issue by zarend** [angular/components#23331]
#### Reproduction

Steps to reproduce:
1. in a terminal, run `npm install @angular/material-luxon-adapter@12.2.0`
 
#### Expected Behavior

Installs the Luxon adapter package.

#### Actual Behavior

Returns the error `404 Not Found - GET https://registry.npmjs.org/@angular/material-luxon-adapter/-/material-luxon-adapter-12.2.0.tgz`

![image](https://user-images.githubusercontent.com/7720245/128745738-d17545d1-cf88-4312-bd32-78bf4925be52.png)

#### Environment

- Angular: N/A
- CDK/Material: N/A
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Big Sur 11.5.1 
- node: v12.14.1
- npm: v16.13.4

#### Additional Notes
A new version of components will be published this Wednesday that should fix it. This looks related to the npm issue [tarballs 404ing? #12563](https://github.com/npm/npm/issues/12563).

##### Work-Around
To work-around this issue, install the rc version.
`npm install @angular/material-luxon-adapter@12.2.0-rc.0`

**Comment by crisbeto** [comment]
This appears to have been resolved. Closing.
