### ISSUE TITLE
bug: <noscript> tags prevent from including styles in index.html in production

### ISSUE THREAD

**Issue by yegor-pelykh** [angular/components#23364]
#### Reproduction

Steps to reproduce:
1. Project is created with custom theme
2. `npm run build`
 
#### Expected Behavior

I see my custom theme applied in production. 

#### Actual Behavior

I see that my theme is NOT applied in production, instead there is some default theme in grayscale.

in `dist` folder there is `index.html` file. There is a line inside it:
`<noscript><link rel="stylesheet" href="styles.css"></noscript>`

If I remove `<noscript>` tags, seems that my theme is applied.
Are these `<noscript>` tags wrong?

There are no any problems with applying theme in development mode.

#### Environment

- Angular: 12.2.0
- CDK/Material: 12.0.1
- Browser(s): Mozilla Firefox 91.0
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment]
According to MDN (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link), the `link` tag can only occur in the `head` or in some cases in the `body`. I think that you can safely remove the `noscript` tag in your case.

**Comment by yegor-pelykh** [comment]
Yes, I can remove it. But it gets regenerated every time I build again. So this is an error in generating html code? With these tags, the application in production simply does not work, since it has no styles.

**Comment by crisbeto** [comment]
It sounds like there's something in your build pipeline that is adding the `noscript` tag. We don't have control over the build so you'll have to figure it out yourself.
