### ISSUE TITLE
feat(dialog): Support default dialog options as part of a dialog component

### ISSUE THREAD

**Issue by Harpush** [angular/components#23373]
#### Feature Description

Allow adding a default mat dialog config to a specific component. Maybe even through the `MAT_DIALOG_DEFAULT_OPTIONS` token or a static property.

#### Use Case

Mostly when creating a dialog component the one developing it decides what's the recommended width, height, autoFocus, etc...
It seems to me like having the ability to add default dialog options on a specific component can make sure that opening it from many places will be with the same options and won't require duplicating the options or remembering to reference an options constant when opening.

The order of options will be:
Opening options > Specific component options > global `MAT_DIALOG_DEFAULT_OPTIONS`

**Comment by crisbeto** [comment]
The `MAT_DIALOG_DEFAULT_OPTIONS` is passed in through DI so you should be able to achieve this by providing the token at a lower level in dependency tree. E.g. you can have one set of options at the top-level module and another one somewhere further down in a feature module.

**Comment by Harpush** [comment]
@crisbeto But providing it on the dialog component doesn't work...
