### ISSUE TITLE
bug(sidenav): sidenav margin calculation incorrect when element sheds a scrollbar

### ISSUE THREAD

**Issue by AmitMY** [angular/components#23382]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-jxgy3q?file=src/app/example-component.html

Steps to reproduce:
1. Create a sidenav, with a scrollbar
2. Resize the page with `ctrl-` until the scrollbar is gone
3. See that the margin of the sidenav content is not updated (probably missing a `requestAnimationFrame` [here](https://github.com/angular/components/blob/769996ed3f359c1a168ae35abb1de1231958f7bc/src/material/sidenav/drawer.ts#L747)
 
 
#### Expected Behavior

Sidenav content should have the correct margins

#### Actual Behavior

It does not, after a scrollbar is shed

#### Environment

- Angular:  12.2.1
- CDK/Material: 12.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

https://user-images.githubusercontent.com/5757359/129602571-d5ed2079-5dd1-4ef9-8795-df9b5d8b1a2d.mp4

**Comment by crisbeto** [comment]
I couldn't reproduce the issue myself, but we've had similar reports in the past. It's because we don't have a way of knowing when the sidenav's size has changed. You should be able to fix this by setting the `autosize` input on the sidenav container. Note that it has some performance implications, because it has to check the DOM more frequently for size changes.

**Comment by AmitMY** [comment]
The example stackblitz I give reproduces the issue, you can see it in the video.

You could use a `ResizeObserver`, or I believe add a `requestAnimationFrame` before querying for the sidenav's size.

In any case, this is a bug (as I reproduced it), please reopen.

**Comment by crisbeto** [comment]
Does the `autosize` input resolve the issue for you? We've been planning on using a `ResizeObserver` with it as a way to reduce the performance hit.

**Comment by AmitMY** [comment]
Yes, `autosize` works.
