### ISSUE TITLE
docs-bug(COMPONENT): TITLE

### ISSUE THREAD

**Issue by derekkite** [angular/components#23381]
#### Documentation Feedback
Testing components with mat-card and other material components gave me a warning

console.warn
      Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

      at MatCommonModule.Object.<anonymous>.MatCommonModule._checkThemeIsPresent (../../../../src/material/core/common-behaviors/common-module.ts:144:15)
...

It turns out there is a simple solution

providers: [
        {provide: MATERIAL_SANITY_CHECKS, useValue: false}
      ],
]

It would be helpful if it was mentioned in the using-component-harnesses guide.

Thanks
**Affected documentation page:** https://material.angular.io/guide/using-component-harnesses

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/23365.
