### ISSUE TITLE
bug(COMPONENT): TITLE reading KML data from a file support in google maps

### ISSUE THREAD

**Issue by soori-reddy** [angular/components#23380]
#### Reproduction

Use StackBlitz to reproduce your issue: 
-  https://stackblitz.com/edit/angular-ivy-nc8iqn

Steps to reproduce:
1.have one static kml and refer the same in component
if we use a kml https url of same content it is working
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?
it is expected to load kml

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
We proxy the `url` directly through to the Google Maps API so this is either an issue with the formatting of your URL or something in Google Maps. I'm closing the issue since we can't do much more about it.
