### ISSUE TITLE
feat(@angular/google-maps): can’t set “className” to customize label marker => MarkerLabel 

### ISSUE THREAD

**Issue by fox-alvarez** [angular/components#23396]
Currently @angular/google-maps does not allow adding **"className"** to customize the label of a marker.

**It only allows the following options:**
- color
- fontFamily
- fontSize
- fontWeight
- text

![Captura de pantalla 2021-08-18 113945](https://user-images.githubusercontent.com/1591087/129938232-e8df5d42-978a-465d-ab0b-050daffccc1f.png)

**Question:**
¿How could we add a white border to the text (Label market)?

**Comment by crisbeto** [comment]
You should be able to pass in a `MarkerLabel` object into the `label` input of the `map-marker`. Docs about the `MarkerLabel`: https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerLabel.

**Comment by fox-alvarez** [comment]
Solved.

Turns out I was using the old version of types:
@types/googlemaps

Instead of the new one:
@types/google.maps
