### ISSUE TITLE
feat(DateAdapter): Add a method for getting the ISO week number

### ISSUE THREAD

**Issue by artfulsage** [angular/components#23422]
#### Feature Description

This method should return the ISO week number. It has locale independent calculation algorithm and so could be implemented in the base class. And maybe it will be a start point for adding the local week number getter.

#### Use Case

`DateAdapter` or based on it custom adapters can be used not only in Material Components but also inside custom components or even in some enterprise apps to abstract from concrete datetime library. I understand it even as a kinda calendar adapter. And if so there could be a method for getting the week number. I know that its kinda tricky operation because of different locales but there is an algorithm for getting the week number in ISO way. So what do you think about adding it to `DateAdapter`? Personally I can make the PR.

**Comment by crisbeto** [comment]
We talked about this in our team sync meeting and we decided not to proceed with it, because we only add APIs to the `DateAdapter` if we need them for Material components. You could work around it your own project by importing one of our adapters and extending it.

**Comment by artfulsage** [comment]
I understand, that this code, if it exists, should be in the core library and not in the components, so I agree with your point, but still wanted to try.
