### ISSUE TITLE
docs-bug: Stackblitz examples will not build

### ISSUE THREAD

**Issue by joelkesler** [angular/components#23420]
When I click the "Edit <example name> in Stackblitz button on [the Angular Material site](https://material.angular.io/components/table/examples), the resulting Stackblitz link will not build

> Error in turbo_modules/@angular/material@12.2.2/table/table-module.d.ts (8:22)
> Appears in the NgModule.exports of DemoMaterialModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.
> 
> This likely means that the dependency (@angular/material/table) which declares MatTableModule has not been processed correctly by ngcc.

Examples from the Mat Table examples page: https://material.angular.io/components/table/examples

![image](https://user-images.githubusercontent.com/303329/130293057-4f8ad9a8-7636-42a6-b680-50d43d04edcb.png)

![image](https://user-images.githubusercontent.com/303329/130293074-5d1dbd91-7ec3-4537-8e14-61dff723bede.png)

Example from Mat Button:

![image](https://user-images.githubusercontent.com/303329/130293511-8320ef2c-5e11-462e-9bb1-3c0bb3c3525c.png)

**Comment by jdgarvey** [comment]
I also noticed this... for me, when I go into settings on stackblitz and disable the "Enable Ivy" checkbox, it starts working:
![image](https://user-images.githubusercontent.com/1544557/130471531-ff904a32-d0b4-4efb-b4fc-f5636e982207.png)

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material.angular.io/pull/1050 when we release the docs site again.
