### ISSUE TITLE
Material Carousel

### ISSUE THREAD

**Issue by justcoder1** [angular/components#23424]
I wanted to implement a carousel today in my angular project and I was shocked frankly to see this was not a feature available in angular material when you even use one on the home screen of 'Angular Material'.

Do you still not have plans to implement such a component/feature to angular material?

Thanks

**Comment by Splaktar** [comment]
Duplciate of https://github.com/angular/components/issues/1081.

**Comment by jelbourn** [comment]
This is something we have no plans to implement for a couple of reasons:
* It's not included in the Material Design spec
* Carousels are notoriously hard to use well for accessibility 
* We have a number of higher priority requests we _do_ plan to implement (like time picker)

It's not the goal of Angular Material to provide a comprehensive set of all widely used UI component patterns, instead focusing on the core components outlined in the Material Design spec and leaving further extensions to the community.

**Comment by justcoder1** [comment]
Thanks for taking the time to respond Jeremy and explaining the reason for the missing Carousels option in material.  I hope this is something that will make its way onto your 'to do plan' as I think it would be great to have access to one through material.

Thanks
Justin
