### ISSUE TITLE
MatDateRangeInput separator not showing

### ISSUE THREAD

**Issue by roddc** [angular/components#23452]
#### What are you trying to do?

I am trying to set `MatDateRangeInput` focus state programmatically via `_updateFocus` method, and `_shouldHideSeparator`  return false, this should show the separator, but it is not showing.
#### What troubleshooting steps have you tried?

The separator is not showing.
#### Reproduction

Steps to reproduce:
1. MatDateRangeInput._updateFocus('program')
  
#### Environment

- Angular:12.0.4
- CDK/Material:12.0.4
- Browser(s):chrome

**Comment by jelbourn** [comment]
Directly via the DOM API, same as you would any other `input` in your application.
