### ISSUE TITLE
bug(chips): matChipRemove should not apply to icons

### ISSUE THREAD

**Issue by jelbourn** [angular/components#23463]
All of our examples that use `matChipRemove` apply directly to `mat-icon`, which is not great for a11y; instead, the directive should go on a button that _contains_ an icon.  

Alternatively, we can _project_ `<mat-icon matChipRemove>` into a button within the component. This fix might be preferable since it will "fix" anyone who has copied this example so far.

**Comment by crisbeto** [comment]
I think that we'll have to make some changes before we recommend `<button matChipRemove>`, because the user agent styles will interfere with the icon.

**Comment by jelbourn** [comment]
@crisbeto yeah, definitely. We could try making `button[matChipRemove]` a component with the right styles, but I don't have a sense off the top of my head how breaking that would be.
