### ISSUE TITLE
bug(cdkDrag): cdkDrag will grab the underlying link insted of the element.

### ISSUE THREAD

**Issue by Baluditor** [angular/components#23469]
Hi. I'm having issues with the cdkDrag feature when I'm using it on a link element. Sometimes it grabs the underlying link instead of the draggable element. It's inconsistent when it's happening.

StackBlitz:  https://angular-pqknrn.stackblitz.io

Steps to reproduce:
1. Grab a cdkDrag element with at the <a> tag ( you might need to do it multiple times to happen). 
2. Move the element

**Expected Behavior**

The component/element is grabbed and dragged instead of the link.

**Actual Behavior**

The underlying <a> tag is being grabbed and dragged.

#### Environment

- Angular: 12.2.3
- CDK: 12.2.3
- Browser(s): Version 92.0.4515.159 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10. 

![angular-cdkdrag-bug](https://user-images.githubusercontent.com/34071416/131088518-1305511f-a036-473a-a4af-14772f3c3c7b.png)

**Comment by Baluditor** [comment]
Hi @crisbeto. I've created a video to better demonstrate how this is happening. Sadly, the config did not make any difference to it. 
https://youtu.be/3KA7b0uFS3w

**Comment by crisbeto** [comment]
I still can't reproduce it in our dev app. Here's what I'm doing:
![demo](https://user-images.githubusercontent.com/4450522/131362149-cf108c41-a5d5-496e-85b9-59441ba5a319.gif)

**Comment by Baluditor** [comment]
Could you please share a link to that app? I'd like to give it a try and see. It might happen that somehow the code structure is responsible for it, but doubt it as it was happening in the Stackblitz I shared. Thansk.

**Comment by crisbeto** [comment]
It's our local development app so all you have to do is:
1. Clone this repo.
2. Run `yarn`.
3. Run `yarn dev-app`.
4. Go to localhost:4200.

Here's the code for the drag&drop demo. All I did was to swap out the `div` with links and to remove the drag handles. https://github.com/angular/components/tree/master/src/dev-app/drag-drop

**Comment by Baluditor** [comment]
Thanks a lot, I'll give it a try.

**Comment by Baluditor** [comment]
I've tried to follow your instructions but I get this error: 
![image](https://user-images.githubusercontent.com/34071416/131650551-a131f7c7-ae7e-4091-b5c2-ebe45745c8c0.png)

**Comment by crisbeto** [comment]
Our build system hasn't been working well on Windows, I had to set some things up manually myself. Alternatively, you can fork one of the examples from the docs to Stackblitz and share it that way. https://material.angular.io/cdk/drag-drop/examples

**Comment by Baluditor** [comment]
I've forked it and the bug also happening there. Here is the screenshot: 
![image](https://user-images.githubusercontent.com/34071416/131836099-8f4785ee-1528-452f-9512-468f54905879.png)

Also, here is the link to the Stackblitz: 
https://stackblitz.com/edit/angular-onbscd?file=src/app/cdk-drag-drop-connected-sorting-group-example.html

If you wish, I can show you via screen share or something how you can "achieve" this behavior. But as you can see, all I did is replaced the <div? with an <a> tag.

**Comment by Baluditor** [comment]
Hi, any update on this, please?

**Comment by crisbeto** [comment]
There's no update since I haven't been able to reproduce the issue.

**Comment by Baluditor** [comment]
Fine, seems something happened in the meantime and this got fixed somehow as I can't reproduce it anymore.
