### ISSUE TITLE
bug(MAT-SLIDER): Mat-Slider changes text color despite existing color code.

### ISSUE THREAD

**Issue by YSFKBDY** [angular/components#23473]
I have a component in my project with some text and a conditional mat-slider.

When mat-slider is hidden, my text looks like this: 
![111](https://user-images.githubusercontent.com/27686947/131137847-610ec7af-70e2-40f3-84c7-e8059111ec8f.jpg)

And when it is visible, my text looks like this: 
![222](https://user-images.githubusercontent.com/27686947/131137899-daa7d776-8508-449f-b1ac-6fc47c1e65b5.jpg)

My code:
> <mat-slider *ngIf="isVisible" [min]="minValue" [max]="maxValue" [step]="stepValue" [thumbLabel]="true" [tickInterval]="1"></mat-slider>
> < div style="color: #0089D6; font-size: 13px; font-weight: 500;">This is a sample text.< /div >

Color code doesn't change and I've looked for any css override, but I couldn't find anything. However, color changes as seen above. Why is this happening?

#### Environment

- Angular: 10.2.3
- CDK/Material: 11.0.3
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): win32 x64

**Comment by crisbeto** [comment]
This looks like some sort of browser rendering bug so I don't think that we can do much about it.
