### ISSUE TITLE
feat(COMPONENT): TITLE

### ISSUE THREAD

**Issue by JDelladecimas** [angular/components#23472]
#### Feature Description

Add ability to set the order of tabs within a tab-group.

#### Use Case

As a developer I would like the ability to set the order of the tabs based on user preference. Currently I need to code this using dynamic content which makes the code a bit messy and hard to read and has an impact on performance.
It would be good to be able to write the html as expected and then pass an object to the tab-group that dictates the tab order.

**Comment by crisbeto** [comment]
Changing the order dynamically with something like `ngFor` is the recommended way of doing this. Having a different way would go against the framework's conventions.
