### ISSUE TITLE
bug(MatMenuTrigger): triggerMore.open doesn't work well in firefox 

### ISSUE THREAD

**Issue by mirko1987** [angular/components#23489]
#### Reproduction

When I call triggerMore.open()  from angular material  the menu does'nt work in firefox;
 
 

#### Environment

- Angular11:
- CDK/Material12:
- Browser(s) firefox:
- Windows:

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
