### ISSUE TITLE
bug(mat-menu): close mat-menu on mouse leave - it starts flickering

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/components#23487]
## Description

I am using mat-menu, I am displaying a menu when the mouse enters the event for a specific button.it works fine.

But I want to close `mat-menu` when the mouse leaves the button. it is not working.

Please fin the sample in below:

https://stackblitz.com/edit/example-angular-material-toolbar-menu-vrobtz?file=app%2Fapp.component.html

## Reproduce steps

- open the above sample
- hover home icon, you can see menu popup gets opened
- move away before entering menu, you can see menu popup not get closed
- sample - https://stackblitz.com/edit/example-angular-material-toolbar-menu-vrobtz?file=app%2Fapp.component.html

### Note - I have tried to use mouse-leave for that button but it start flickering

sample - https://stackblitz.com/edit/example-angular-material-toolbar-menu-uxlbba?file=app%2Fapp.component.html

**Comment by crisbeto** [comment]
Closing since this isn't something that we officially support.
