### ISSUE TITLE
bug(mat-table): Animations on expanding rows cause html duplication when item order changes.

### ISSUE THREAD

**Issue by JohanBeekers** [angular/components#23488]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-pbplsn?file=src/app/example-component.html

Steps to reproduce:
1. Expand the 'Owl' row by clicking on it. (Not the checkbox) It shows 'Some content here.'
2. Click the 'Swap items' button. It moves 'cat' just above the 'wasp' row.
3. Close the 'owl' row by clicking on it. The content is still visible. 
4. Expand the 'Owl' row again by clicking on it. The content is duplicated and shows 'Some content here.' twice.
5. Expand the 'Bee' row by clicking on it. Both rows appear to be open now.
 
 
#### Expected Behavior
Closing the row, or opening a different row, correctly removing the content of the open row after a reorder has happened.

#### Actual Behavior
After the reorder, the open row's content never gets removed when it closes. Opening the same one again, duplicates the content.

#### Environment

- Angular: 12.2.2
- CDK/Material: 12.2.2
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

#### Additional information
Clicking 'Swap items' will move the second row (Cat) to the second last position (above Wasp).
Having 'Mouse', 'Cat' or 'Wasp' expanded when swapping items, works fine.
But having any of the other items expanded, between cat and wasp, causes something to break.
Closing the expanded element 'deselects' it, but it still appears open.
Opening it again doubles the content of that row.
Expanding a different row results in 2 expanded rows.
This behaviour can be repeated multiple times when expanding rows between the second and last row.

When the closing row content contains another component, it's ngOnDestroy is triggered. But like the text, it remains in the HTML.

The only 'fixes' I was able to find:
- Removing the animation from the row, but clearly I would like to keep it.
- Changing 'trackById' to track by index, but this comes with it's own issues. Like selections 
messing up and it animating the previous position to closed and opening the new position.

**Comment by crisbeto** [comment]
This looks like an issue in the `animations` package https://github.com/angular/angular/issues/18847.

**Comment by JohanBeekers** [comment]
Yep, you are correct. 
I swear i tried to reproduce it before with a normal ngFor, but couldn't get the same duplication behaviour. Only some animation issues. 
But I just tried it again using a normal HTML table and was able to get the same duplication effect. 
Same for using a div structure, but it only seems to happen when the animating div is a deeper nested child. Not a direct child of the element with the ngFor.
