### ISSUE TITLE
help(overlay): text rendering differences

### ISSUE THREAD

**Issue by luna-magicad** [angular/components#23502]
#### What are you trying to do?
Render text consistently but this is very likely a bug in chromium. It works as expected in Firefox. But I haven't been able to reproduce it outside using angular-material.

This can happen seemingly randomly for example I have a mat-dialog and the text was rendered in one way. Then inside the `<mat-tab-group>` the text is rendered differently.
 
![text-rendering-differences](https://user-images.githubusercontent.com/58553063/131633166-d58035a3-0562-4914-aedd-90b096d5d6ea.png)

#### What troubleshooting steps have you tried?

The text's anti-aliasing method in chrome & edge changes seemingly randomly. I've tried using webkit-font-smoothing and other things. Setting the css `mix-blend-mode: multiply;` on `.mat-dialog-container` solves it for most of our dialog texts.  

#### Reproduction

I haven't been able to reproduce this outside of my own code base and on the official documentation:
https://material.angular.io/cdk/overlay/examples

Because when I tried to do it in the stackblitz for that example I can't reproduce it there. Nor in a codepen.

Steps to reproduce:
1. Use chrome on windows 10.
2. Go to https://material.angular.io/cdk/overlay/examples
3. Set the color for "Overlay basic example" -  `.docs-example-viewer-title-spacer`  to `color: #004985;`
4. Open the overlay 
5. Set the color for the `overlay .example-list > li` to `color: #004985;`
6. Compare the text "Overlay basic example" and "Item 1". You may have to take a screenshot and zoom in the image. But the text for overlay basic example is rendered with subpixels and the item 1 is just using regular antialiasing.
  
#### Environment

- Angular: 12.2.3
- CDK/Material: 12.2.3
- Browser(s): Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10, Build 19042

**Comment by crisbeto** [comment]
This looks like some sort of browser rendering issue that we don't have much control over so I'm closing the issue. Setting `mix-blend-mode` on all overlays isn't an option, because it could cause other issues.
