### ISSUE TITLE
bug(form-field): mistakenly throws error if using `ng-template` reference

### ISSUE THREAD

**Issue by jeripeierSBB** [angular/components#23515]
The error 'mat-form-field must contain a MatFormFieldControl.' is thrown when using template references which are defined outside a `mat-form-field` tag.

#### Reproduction

Steps to reproduce:
1. Go to https://stackblitz.com/edit/angular-tu9mz7?file=src/app/form-field-appearance-example.html
2. See console error

Interestingly, if the template is defined inside the `mat-form-field`, no error is thrown:
1. Again, go to https://stackblitz.com/edit/angular-tu9mz7?file=src/app/form-field-appearance-example.html
2. Change else condition reference from 'otherSelectOutside' to 'otherSelectInside'
3. No console error visible
 
 
#### Expected Behavior

`ng-template` blocks which are located outside the `mat-form-field` tag should be considered as valid.

#### Actual Behavior

The error 'mat-form-field must contain a MatFormFieldControl.' is thrown.

#### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by jelbourn** [comment]
This is working as expected. The form control within the `mat-form-field` connects to the field via the dependency injection tree (which powers both injection and queries). When the template is defined outside of the form-field, there's no way for the field to get a hold of the control and set up the communication between the two. This is an unfortunate limitation of Angular.
