### ISSUE TITLE
bug(google-maps): Zoom control is not placed correctly on the map

### ISSUE THREAD

**Issue by petivagyok16** [angular/components#23513]
#### Reproduction

In the image it is visible that zoomControl cannot be seen floating above the maps. Even though i have set it in my mapOptions:

```ts
const mapOptions = {
      disableDefaultUI: true,
      fullscreenControl: false,
      center: { lat: 47.54808005417875, lng: 19.07462832805228 },
      zoom: 16,
      zoomControl: true,
      zoomControlOptions: {
        position: google.maps.ControlPosition.RIGHT_BOTTOM,
      },
   }
```
it is still not working.
I have to hack it from css to put it to the right place.

![Screenshot 2021-09-02 at 11 07 59](https://user-images.githubusercontent.com/16253571/131816611-dc3fdb22-7f98-40cf-8db9-445373c3b872.png)

Steps to reproduce:
1. Add zoomControl to your google maps
2. it will be invisible somewhere above the map
 
 
#### Expected Behavior

What behavior were you expecting to see?
See the zoom control at the right place where i am setting it in the mapOptions

#### Actual Behavior

What behavior did you actually see?
Zoom control floats above the map, it is invisible.

#### Environment

- Angular: 12.1.0
- CDK/Material: 12.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 11.5.2

**Comment by jelbourn** [comment]
@crisbeto I don't think this would have anything to do with our wrapping of the google maps client, right?

**Comment by crisbeto** [comment]
I tried it against our local dev app, but it looks as expected. There might be some other styles on the page that are interfering with it. For reference, this is what my code looks like:

```
mapOptions = {
    disableDefaultUI: true,
    fullscreenControl: false,
    center: { lat: 47.54808005417875, lng: 19.07462832805228 },
    zoom: 16,
    zoomControl: true,
    zoomControlOptions: {
      position: google.maps.ControlPosition.RIGHT_BOTTOM,
    },
 };

<google-map [options]="mapOptions"></google-map>
```

**Comment by petivagyok16** [comment]
alright. thanks!
