### ISSUE TITLE
bug(AutoComplete): AutoComplete Test harness failure

### ISSUE THREAD

**Issue by npersad** [angular/components#23512]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. go to stackblitz https://stackblitz.com/edit/angular-ndwwvd?file=src%2Fapp%2Fautocomplete-harness-example.html
2. run example
3. the last test (verbatim from the below link) is failing https://github.com/angular/components/blob/2c48fc8aaf9ea34bb8ce935b8be5d7eac27623f7/src/components-examples/material/autocomplete/autocomplete-harness/autocomplete-harness-example.spec.ts#L61

#### Expected Behavior

What behavior were you expecting to see?
mat option length should be 1 and equal to "New York"

#### Actual Behavior
0 mat options are being found and returned
`undefined is not an object (evaluating 'options[0].getText')`
What behavior did you actually see?
`options.length` should be 1 and  `options[0].getText()` should be New York

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by npersad** [comment]
<img width="1401" alt="Screen Shot 2021-09-01 at 11 51 39 PM" src="https://user-images.githubusercontent.com/6717111/131779097-e225bb48-df86-4189-b0cd-b94c99916b6d.png">

**Comment by jelbourn** [comment]
@npersad your StackBlitz seems to be broken for environment setup reasons, here's a working one: 
https://stackblitz.com/angular/aaaxqrvykxva?file=src%2Fapp%2Fautocomplete-harness-example.spec.ts

With that, I can't see any differences in the code between this example (which is working as expected) and the one you provided. Is there something missing here?

**Comment by npersad** [comment]
Hi @jelbourn.  Running your example in safari, 2 test fail.  But all tests pass from chrome.  Similar tests fail when I run
ng test.  Any ideas?


<img width="1792" alt="Screen Shot 2021-09-07 at 4 50 18 PM" src="https://user-images.githubusercontent.com/6717111/132409102-ac1755ec-0444-40d5-bec4-5c812da67add.png">

chrome
<img width="1792" alt="Screen Shot 2021-09-07 at 4 50 07 PM" src="https://user-images.githubusercontent.com/6717111/132409115-e37746aa-b5d7-4910-84cf-9cb0b4982b07.png">

**Comment by npersad** [comment]
close for now.  maybe reopen in the future when after I give this another proper try as the radio button harness works and it might give me clues if im doing something wrong with the auto complete harness
