### ISSUE TITLE
feat(table): Dynamically Rending a Component Inside the Expandable Column of Angular Material Data Table

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#23533]
#### Feature Description

I'd love to be able to configure a custom data table component with another component that could render inside the expandable column of an Angular Material Data Table.  I think that's what Angular Material CDK Portals are for, but I'm not sure if it will work since each table row needs a new component instance that will render data from the model.  I'm still experimenting with it, and I tried using a template here without any love (But it demonstrates what the end goal is):

https://stackoverflow.com/questions/69051547/using-ng-template-inside-ng-container-of-angular-material-data-table-expandable

#### Use Case

Be able to configure dynamic content for the expandable row of a custom data table.

Describe the use case(s) that the proposed feature would enable.

So for example we could configure a component on a custom data table.  Something like:

```
<fs-custom-expandable-data-table rowExpandComponent="ChartComponent">
</s-custom-expandable-data-table>
```

And the chart component would be rendered inside the expandable row of the table.

**Comment by fireflysemantics** [comment]
@jelbourn suppose we have a custom data table defined and it can be declared like this:

```
<fs-custom-expandable-data-table rowExpandComponent="ChartComponent">
</s-custom-expandable-data-table>
```

How can we do that?  So it. renders a datasource and. has an expandable row that when clicked will render the configured `ChartComponent`.  That component is just the component class definition and the expandable row would have the instance of it with data from the corresponding master row ..

**Comment by jelbourn** [comment]
I think that should be something you can accomplish today via something like `ngComponentOutlet`. Closing this since I don't think it's a feature request for the table so much as a general question.
