### ISSUE TITLE
Context menu is not working in Angular 9

### ISSUE THREAD

**Issue by bala-visolve** [angular/components#23535]
I have updated my application from angular 8 to 9.
ngx-contextmenu is not at all working in angular 9. 

I have updated the packages version to recent also but still context menu is not showing up.

Any help would really appreciated!!

- Angular: 9
- CDK/Material: ngx-contextmenu@5.4.0
- Browser(s): Chrome and firefox
- Operating System ( Ubuntu):

**Comment by Totati** [comment]
ngx-contextmenu is not part of this repo. You should file your issue here: https://github.com/isaacplmann/ngx-contextmenu

**Comment by bala-visolve** [comment]
Thanks Totati.

I have filed the same there
