### ISSUE TITLE
help(@angular/google-maps): Event directionsChanged returns undefine

### ISSUE THREAD

**Issue by DiegoHerrera262** [angular/components#23540]
#### What are you trying to do?

i'm trying to get the end points of direction after drag on either end. The idea is to be able to update the directions of a custom component when the end points in the map change by user. The code is more or less like this

```html
<google-map 
    *ngIf="loadedCenter" 
    [height]="'100%'" 
    [width]="'100%'" 
    [center]="center" 
    [options]="options"
>
      <map-directions-renderer 
          *ngIf="showDirectionsRoute" 
          [directions]="directionsRoute" 
          [options]="routeOptions" 
          (directionsChanged)="setDirectionsOnDrag($event)"
      >
      </map-directions-renderer>
</google-map>
```

At the moment, the handler `setDirectionsOnDrag` only logs the event. However, the output is `undefined`. I'm new to Angular and @angular/google-maps specifically.

#### Reproduction

Install @angluar/google-maps with npm, and set `draggable: true` on directive options for `MapDirectionsRenderer`. The idea is to get the new coordinates and address for the new end points after drag. 
  
#### Environment

- Angular: 12.2.0
- CDK/Material: @angular/google-maps^12.2.4
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Big Sur.

**Comment by crisbeto** [comment]
The `directionsChanged` event is a direct proxy of the `directions_changed` event from Google Maps. Since their event doesn't attach any event data, ours doesn't either. See https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRenderer.directions_changed.

**Comment by DiegoHerrera262** [comment]
I see. Is there any way to access the new route details after drag in my component? I'm fairly new to angular. Thanks in advance
