### ISSUE TITLE
help(COMPONENT): Apply angular material to chrome extension development

### ISSUE THREAD

**Issue by lilopusic** [angular/components#23555]
#### What are you trying to do?

Apply angular material in chrome extension development

#### What troubleshooting steps have you tried?
`<link rel="stylesheet" href="styles.c9ba96590e65260d312d.css" media="print" onload="this.media='all'">`
In the generated index.html, this piece of code will cause an error and fail to apply the style correctly. The error message is as follows. Simply put, it violates the CSP
![image](https://user-images.githubusercontent.com/7373882/132629465-ddd18ec0-97ac-4a6c-bc2a-3c96a2626134.png)

When I change it to this:
`<link rel="stylesheet" href="styles.c9ba96590e65260d312d.css">`
Everything is ok
So, can we get rid of this grammar? I don’t want to manually change the compiled index.html every time
#### Reproduction

Steps to reproduce:
1. ng add @angular/material
2. ng build --prod
3. check the output index.html
  
#### Environment

- Angular: 12.2.0
- CDK/Material: 12.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This looks like an issue in your own code. The error is complaining, because of the `onload` attribute on the `link` tag.

**Comment by lilopusic** [comment]
Hi @crisbeto 
It's not my own code, this is the original index.html:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Chroma</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
</body>
</html>
```
No onload attribute and this is the compiled index.html:
```
<!DOCTYPE html><html lang="en"><head>
  <meta charset="utf-8">
  <title>Chroma</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<style>body,html{height:100%;}body{margin:0;font-family:Roboto,Helvetica Neue,sans-serif;}</style>
<link rel="stylesheet" href="styles.c9ba96590e65260d312d.css" media="print" onload="this.media='all'">
<noscript><link rel="stylesheet" href="styles.c9ba96590e65260d312d.css"></noscript></head>
<body>
  <app-root></app-root>
<script src="runtime.2376bfe922c744799a6c.js" defer></script>
<script src="polyfills.20f8a15b4ec93c55c15e.js" defer></script>
<script src="main.39a90ae15dc98163bb8a.js" defer></script>

</body></html>

```
The onload attribute appeared, the entire link tag and its content are added during the compilation process,I did not find the reopen button but I think this question should be reopened
Please help to check it, thanks.

**Comment by crisbeto** [comment]
We don't have control over that `index.html` in this project. You should file an issue with whatever tool is generating the index file for you.

**Comment by lilopusic** [comment]
Thanks for the hint, this is indeed related to angular/cli, and I have found a solution
https://github.com/angular/angular-cli/issues/20864
