### ISSUE TITLE
feat(COMPONENT): TITLE NativeDateAdapter

### ISSUE THREAD

**Issue by nicolae536** [angular/components#23557]
#### Feature Description

Provide a brief summary of the feature you would like to see.
Expose the full interface of DateAdapter<Date> in NativeDateAdapter.
As a dev for simplicity when creating my custom DateAdapter I extended the NativeDateAdapter. It would be nice to expose the methods inside DateAdapter<Date> exactly how they are in the original interface since when extending the NativeDateAdapter I would need to use a @ts-ignore to declare the parse method with the second parameter.

```
// NativeDateAdapter implements parse method without the second parameter dateFormat: ParseDateInputFormat, which is wrong cause DateAdapter parse
    // method signature is parse(value: any, dateFormat?: any): T | null. Because of this we cannot override the method parse in the correct way by having
    // parse(value: any, dateFormat: ParseDateInputFormat | null | undefined): Date | null since the parse inside of the NativeDateAdapter which we extend
    // is declared parse(value: any): Date | null. In order to mitigate this issue we have to ignore the next line because the datepicker will call the
    // dateAdapter like this dateAdapter.parse(value, dateFormat) and we need the dateFormat in order to decide which strategy we will use to parse the
    // date and typescript cannot see that we are overriding the method correctly because the NativeDateAdapter implements the interface in the wrong way.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    public parse(value: any, dateFormat: ParseDateInputFormat | null | undefined): Date | null {
```

#### Use Case

Extending NativeDateAdapter in custom class without needing to disable typescript for certain methods.

**Comment by crisbeto** [comment]
Closing the issue, because exposing the `dateFormat` parameter would be misleading since it won't do anything.
