### ISSUE TITLE
Material Input: Align Prefix and Placeholder

### ISSUE THREAD

**Issue by wolframm** [angular/components#23556]
Please align the placeholder with the prefix. Example code from 

 ![image](https://user-images.githubusercontent.com/6116001/132633035-b3421018-6cc0-4e9b-9562-b576357a1a1d.png)

Example code taken from material.angular.io: https://stackblitz.com/angular/aeoyvdnebyj?file=src%2Fapp%2Finput-prefix-suffix-example.ts

**Comment by crisbeto** [comment]
Aligning the prefix to the placeholder will break the alignment when the input has text. Also it's worth noting that the primary use case for the prefix/suffix is icons, rather than text.
