### ISSUE TITLE
bug(COMPONENT): Content Projection Child to Parent using NgContent

### ISSUE THREAD

**Issue by angulardev123** [angular/components#23561]
I'm trying to project content from a child component to a parent component in an Angular 9+ application. All of the examples that I see project content from parent to child, but I can't find any that go from child to parent. Is this even possible? In the example below, I'm trying to project the div from the child to the ng-content slot in the parent. This throws no errors on a sample app but the div from the child never renders. Is there any other way to achieve this without using content projection?

Steps to reproduce:

Parent component template:

```
<div>
     <ng-content select="contentfromchild"></ng-content>
</div>
```

Child component template:

```
<div>
   <div contentfromchild>Hi, I'm from the child component!</div>
</div>
```

App component template:

```
<parent-component>
     <child-component></child-component>
</parent-component>
```
 
#### Expected Behavior

I should be able to see the child's content in the parent's ng-content.

#### Actual Behavior

The child's content never renders in the parent's ng-content.

#### Environment

- Angular: 9+
- CDK/Material:
- Browser(s): Chrome 93
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment]
It isn't possible. I'm closing the issue since the bug tracker isn't the right place to ask questions like this. Better places would be StackOverflow or Discord.
