### ISSUE TITLE
bug(Input): label misaligned in outline appearance with text-align=right

### ISSUE THREAD

**Issue by stenlee** [angular/components#23564]
#### Reproduction

Form field label with **appearance=outline** and **text-alight=right** is misaligned in all browsers.

<img width="241" alt="Screenshot 2021-09-10 at 9 14 37" src="https://user-images.githubusercontent.com/936907/132814980-00167265-c095-42c3-aef2-f9feb19c1074.png">

```
<mat-form-field appearance="outline" style="text-align: right;">
   <mat-label>Label</mat-label>
   <input matInput />
</mat-form-field>
```

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Chrome, Safari, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Overriding our built-in styles like this isn't officially supported. We keep the specificity low so you can do it if you need to, but it's at your own risk.
