### ISSUE TITLE
bug(slide toggle): dialog content has a scrollbar if slide toggle is placed at the bottom

### ISSUE THREAD

**Issue by orlando1108** [angular/components#23565]
#### Reproduction

StackBlitz
https://stackblitz.com/edit/angular-uxrzxc?file=src%2Fapp%2Fdialog-overview-example-dialog.html

Steps to reproduce:
1. create a form with slide toggle inputs at the bottom
2. place that form inside a dialog content
3. from the stackblitz, click on 'pick one'
4. you can see a scrollbar 
 
#### Expected Behavior

The dialog content should take in account the slide toggle sizes in order to not create an overflow. So the scrollbar should not be visible.

#### Actual Behavior

The dialog content does not take in account the slide toggle sizes and create an overflow in y axis. So the scrollbar is visible automatically.

#### Environment

- Angular: 12.2.4
- CDK/Material: 12.2.4
- Browser(s): Chrome
- Operating System: Windows

**Comment by crisbeto** [comment]
This is the same root cause as https://github.com/angular/components/issues/8798.
