### ISSUE TITLE
bug(mat Tab link): Not able to create dynamic  nested navigation with mat tab link

### ISSUE THREAD

**Issue by 123adsens** [angular/components#23567]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. https://stackblitz.com/edit/angular-jt7mh2?file=app%2Ftab-nav-bar-basic-example.html
 
 
#### Expected Behavior

What behavior were you expecting to see?
willl come as nested navigation sub nav under main navigation

#### Actual Behavior
All links coming as single line

What behavior did you actually see?
All links coming as single line

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing since this isn't something that we support, because nesting anchor tags isn't allowed. See https://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link.
