### ISSUE TITLE
bug(Material/Select): Need aria-controls attribute set to fix Axe Core critical issue

### ISSUE THREAD

**Issue by drc-nloftsgard** [angular/components#23570]
#### Reproduction

Using the Select documentation page at https://material.angular.io/components/select/overview and the Axe DevTools Chrome plugin https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

Steps to reproduce:
1. Scan the entire page with Axe DevTools (version 4.3.1) at https://material.angular.io/components/select/overview
 
#### Expected Behavior

No critical issues related to ARIA

#### Actual Behavior

12 instances of "Required ARIA attributes must be provided" one for each <mat-select> that does _not_ use the native select.

#### Environment

- Angular: 12.2.4
- CDK/Material: 12.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

I've been tracking Select (ie. Combobox) a11y issues since [11083](https://github.com/angular/components/issues/11083) and a fix with [PR-20082](https://github.com/angular/components/pull/20082). I believe https://github.com/dequelabs/axe-core/issues/2505 fixed the false positive issue in Axe Core happening after PR-20082.

HOWEVER, with Axe Core 4.3 and ARIA 1.2 there is an additional accessibility requirement related to definition of aria-controls on the select field. The [ARIA 1.2 spec](https://www.w3.org/TR/wai-aria-1.2/#combobox) states:
> Authors MUST set aria-controls on a combobox element to a value that refers to the combobox popup element.

So the fix would be to set aria-controls to the id of the listbox div's id (eg. mat-select-50-panel); resulting in:

```html
<mat-select role="combobox"
  aria-controls="mat-select-50-panel"
  aria-autocomplete="none"
  aria-haspopup="true"
  class="mat-select ng-tns-c176-163 ng-tns-c155-162 mat-select-empty ng-star-inserted"
  aria-labelledby="mat-form-field-label-83 mat-select-value-51"
  id="mat-select-50"
  tabindex="0"
  aria-expanded="false"
  aria-required="false"
  aria-disabled="false"
  aria-invalid="false">
...
</mat-select>
...
<div role="listbox"
 tabindex="-1"
 class="ng-tns-c176-163 ng-trigger ng-trigger-transformPanel mat-select-panel mat-primary"
 id="mat-select-50-panel"
 aria-multiselectable="false"
 aria-labelledby="mat-form-field-label-83"
 style="transform-origin: 50% 24px 0px; font-size: 16px; opacity: 1; min-width: calc(100% + 32px); transform: scaleY(1);">
...
</div>
```
![Screen Shot 2021-09-10 at 3 45 45 PM](https://user-images.githubusercontent.com/44977770/132915703-37858a6a-b6ed-4721-bacb-6a9c572dd685.png)

**Comment by crisbeto** [comment]
We already set an `aria-controls`, but it's only there while the select is open, because the panel doesn't exist in the DOM when closed. See https://github.com/angular/components/blob/master/src/material/select/select.ts#L1084.

**Comment by drc-nloftsgard** [comment]
Thanks @crisbeto - I had our Accessibility Manager test with the select open and it seems to not be an issue. Axe may still flag it as an issue but in our assessment it is a false positive. I will close this issue.
