### ISSUE TITLE
Which library will replace moment.js

### ISSUE THREAD

**Issue by StefanKern** [angular/components#23573]
### Description

Since moment.js says, that there are better alternatives, I was wondering which library will replace moment.js for the moment `@angular/material-moment-adapter`?

Knowing this would be important for us, because we want only one date library in our project, and ideal it is the same as angular will be using.

### Proposed solution

-

### Alternatives considered

-

**Comment by crisbeto** [comment]
That's up for you to decide since moment.js hasn't named a successor library. We currently have date adapters for Luxon (made by some of the same people that did Moment) and `date-fns`.
