### ISSUE TITLE
bug(cdk/scrolling): Append only mode together with FixedSizeVirtualScrollStrategy results in a jumping view

### ISSUE THREAD

**Issue by philippspindler** [angular/components#23577]
#### Reproduction

See the example in the official material documentation
https://material.angular.io/cdk/scrolling/overview#cdk-virtual-scroll-append-only 

1. Scroll down
2. Scrolling is delayed and the correct position is only set after a delay

https://user-images.githubusercontent.com/66056500/133094702-a4ca5760-a677-44eb-9873-8bb13f109861.mov

Note: This effect becomes even more apparent when the rendering of an item is more expensive!

#### Expected Behavior

Virtual scrolling with `appendOnly` sets the correct position without jumping to the top.

#### Actual Behavior

The virtual scroll using `appendOnly` jumps for a certain time to the top of the scrolling container. After this period of time, the correct scroll position is set.

#### A possible solution

I was able to solve this issue by implementing a CustomScrollingStrategy that copy-pastes [FixedSizeScrollingStrategy](https://github.com/angular/components/blob/8f052ccca2b6ca28083c7d550be1952060c0cd92/src/cdk/scrolling/fixed-size-virtual-scroll.ts#L21) and adapts [line 171](https://github.com/angular/components/blob/8f052ccca2b6ca28083c7d550be1952060c0cd92/src/cdk/scrolling/fixed-size-virtual-scroll.ts#L171).

```diff
- this._viewport.setRenderedContentOffset(this._itemSize * newRange.start);
+ this._viewport.setRenderedContentOffset(0, 'to-start');
```

I am missing the insights to be able to open a pull request fixing this issue respecting all different use cases of virtual scrolling with and without `appendOnly`. So I am open to any kind of help to fix this issue.

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by chabb** [comment]
@philippspindler Thanks for opening this issue and posting a fix.  
I've encountered the same issue. The issue with your fix is that it might break things when `appendOnly` is set to false, and it does not take the other issue you've opened https://github.com/angular/components/issues/23578

The trick is to get the updated rendered change before setting the offset, that way, you'll get the correct range, and it will take in account the fix you suggested in your other issue

Here is a variant based on your fix

```diff
- this._viewport.setRenderedContentOffset(this._itemSize * newRange.start);
 +  const newRangeStart = this._viewport.getRenderedRange();
 +  this._viewport.setRenderedContentOffset(this._itemSize * newRangeStart);
 +}
```

It would be a nice fix to have, as the `appendOnly` has a bad user experience when a list has more complex items; the user sees the same items when it scrolls down, which is very confusing

If there is any interest, I can try to write some UT and help with the PR
