### ISSUE TITLE
SassError: Can't find stylesheet to import. @use '~@angular/material' as mat;

### ISSUE THREAD

**Issue by Tim-arts** [angular/components#23576]
#### Steps to reproduce:
1. Create a new Angular project
2. Try to create a custom theme following this [documentation](https://material.angular.io/guide/theming#defining-a-theme)
3. Compile the SCSS file
 
 
#### Expected Behavior

The watcher runs and compiles successfully the SCSS file

#### Actual Behavior

I'm on Webstorm, which set up a SASS watcher to compile the SCSS files located in my project folder. While running the watcher it fails:
```
Error: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material' as mat;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  theme-light.scss 1:1  root stylesheet
```

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Chrome Version 93.0.4577.63 (Official Build) (64-bit)
- Operating System: Windows
-  NPM: 7.23.0

#### Additionnal information

I've tried the solution indicated right [there](https://stackoverflow.com/questions/67652012/sasserror-cant-find-stylesheet-to-import-use-angular-material-as-mat) but it doesn't work as well

**Comment by crisbeto** [comment]
You should use `@use '~@angular/material' as mat;` instead of `@use '~@angular/material/theming' as mat;`. Also in general you should use `ng update` to update your `@angular` packages, because it has automated migrations that account for breaking changes like this one.

**Comment by Tim-arts** [comment]
I was using `@use '~@angular/material'` as mat; but changed for `@use '~@angular/material/theming' as mat;` since it was not working. 

`ng update` output ->
```
Using package manager: 'npm'
Collecting installed dependencies...
Found 25 dependencies.
We analyzed your package.json and everything seems to be in order. Good work!
```

Still have the error
