### ISSUE TITLE
bug(mat-slider): mat-slider doesn't work well with Electronjs

### ISSUE THREAD

**Issue by benjamimbessa** [angular/components#23586]
When I use mat-slider in application working with Electronjs, the default behavior doesn't occurs . 

Problems found:
  1 - Click in  mat-slider he doesn't change the value;
  2 - Click again, value finally change, but if click in any other location in page, the value change again
  3 - The issue is cyclic
 
#### Actual Behavior
![mat-slider](https://user-images.githubusercontent.com/13962168/133445373-a94f5c84-a73d-4519-a42b-982b04d67d8b.gif)

#### Environment

- Angular: 12.2.2
- CDK/Material: 12.2.2
- Browser(s): Electronjs (Embebed)
- Operating System : Windows 10

**Comment by wagnermaciel** [comment]
Closing as Electronjs is not a supported browser. If this issue is reproducible in [any of our supported browsers](https://github.com/angular/components#browser-and-screen-reader-support), feel free to reopen a new issue
