### ISSUE TITLE
bug(MatRadio): Custom theme makes center circle invisible

### ISSUE THREAD

**Issue by eolant** [angular/components#23605]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-7ijs5v?file=src%2Fstyles.scss

Steps to reproduce:
1. Add a radio button
2. Add custom theme with blue as primary palette
 
 
#### Expected Behavior

Radio button color is blue when selected

#### Actual Behavior

Radio button color middle circle is transparent

![image](https://user-images.githubusercontent.com/1523110/134004786-f833e4d3-8347-4d58-8fac-7a3c13e8c247.png)

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS

**Comment by crisbeto** [comment]
It's because the hues being passed into `define-palette` are incorrect. It works if you change this:

```
$mat-accent: mat.define-palette(mat.$orange-palette, a200, a100, a400);
```

To this:

```
$mat-accent: mt.define-palette(mat.$orange-palette, A200, A100, A400);
```

I've submitted https://github.com/angular/components/pull/23612 to throw an error for cases like this one.
