### ISSUE TITLE
(bug: mat-table): Sorting function in Material Table does not work Properly

### ISSUE THREAD

**Issue by Torage** [angular/components#23602]
https://stackblitz.com/edit/angular-ffbgwt?file=src%2Fapp%2Ftable-expandable-rows-example.ts

Steps tp reproduce:

if clicked on the arrow to sort and then on an element to expand, it will not expand. you have to click the element several times and the expansion animation is broken.
![image](https://user-images.githubusercontent.com/14995147/133962724-182d6c60-9f6f-44e5-aecd-f2d23dc2ecc7.png)

Environment
Angular: 11.0.9 and 12.0.0 and others
CDK/Material: 11.1.1 and 12.0.0 and others
Browsers: Problem manifests on both Chrome, FF and Edge
Operating System: MacOS. Windows 10

**Comment by crisbeto** [comment]
This has come up in the past. I believe that the root cause is https://github.com/angular/angular/issues/18847.
