### ISSUE TITLE
Feature request: Wrap Data Layer for google maps component

### ISSUE THREAD

**Issue by malizia-g** [angular/components#23611]
Hello,
I need to render GeoJson  data on google-maps component.
Are you planning to wrap the [Data Layer](https://developers.google.com/maps/documentation/javascript/datalayer)?

Is there any workaround? (like access to the map object)
```typescript 
//Get the map object here 
map.data.loadGeoJson(
    "https://storage.googleapis.com/mapsdevsite/json/google.json"
  );
```

Thank you in advance

**Comment by malizia-g** [comment]
solved for now using @ViewChild as a workaround

**.html**
```html
<google-map  #mapRef>  </google-map>
```

**.ts**
```typescript
@ViewChild('mapRef') mapRef: GoogleMap;
  ngAfterViewInit() {
    this.mapRef.data.loadGeoJson("https://storage.googleapis.com/mapsdevsite/json/google.json");
  }
```

**Comment by crisbeto** [comment]
It looks like this is already available. Closing.
