### ISSUE TITLE
material components documentation examples (V 12.2.5) are failing to run on Stackblitz 

### ISSUE THREAD

**Issue by GautamSKochar** [angular/components#23615]
When we choose option to edit example on stackblitz, new tab gets open with example but it fails to run and prompt as below error
 
Steps:
1. Go to https://material.angular.io/components/sidenav/overview (**Version 12.2.5**)
2. Open any component example and edit it on stackblitz
3. example fails to run and prompts error as below:
`Error in ~/src/main.ts
ngcc failed to run on @angular/forms@12.2.5, @angular/cdk@12.2.5, @angular/platform-browser-dynamic@12.2.5, @angular/platform-browser@12.2.5, @angular/compiler@12.2.5, @angular/material-moment-adapter@12.2.5, @angular/router@12.2.5, rxjs@6.6.7, zone.js@0.11.4, moment@2.29.1, @angular/common@12.2.5, tslib@1.14.1, tslib@2.3.1, @angular/animations@12.2.5, @angular/core@12.2.6, @angular/material@12.2.5, parse5@5.1.1.`

<img width="1349" alt="Screenshot 2021-09-22 at 3 50 49 PM" src="https://user-images.githubusercontent.com/10945126/134326951-40e454ad-22e4-4615-a525-b83d215b86db.png">

<img width="1366" alt="Screenshot 2021-09-22 at 3 56 41 PM" src="https://user-images.githubusercontent.com/10945126/134327981-6aef20af-034e-47a7-ad6a-6c06bfd86abc.png">

**Comment by lekhmanrus** [comment]
Related to stackblitz/core#1364.
**Workaround:** set `enableIvy: false` in `tsconfig.json`.
