### ISSUE TITLE
bug(cdk/table): Default role value in angular 12 is now table and before it was grid

### ISSUE THREAD

**Issue by pmancaux** [angular/components#23616]
#### Expected Behavior

in angular 12.2.5 documentation : https://github.com/angular/components/blob/12.2.5/src/material/table/table.md

you say that :

`Table's default role is grid, and it can be changed to treegrid through role attribute.`

But if we see the source code : https://github.com/angular/components/blob/12.2.5/src/cdk/table/table.ts

`  if (!role) {
      this._elementRef.nativeElement.setAttribute('role', 'table');
    }`

default value seem to be 'table' and this have an impact on UFT Microfocus because all test failed on identification object of type mat-table

In previous version of angular before < 12 default value is grid as you can see :

`https://github.com/angular/components/blob/11.2.13/src/cdk/table/table.ts`

what is the expected behavior?

#### Environment

- Angular: 12.2.5
- CDK/Material: mat-table - cdk/table
- Browser(s): Chrome/firefox
- Operating System (e.g. Windows, macOS, Ubuntu):  ubuntu/windows

**Comment by viniciusschuelter** [comment]
If this was intentional I believe it is no longer a bug, I recommend closing this issue @jelbourn @crisbeto

**Comment by jelbourn** [comment]
Yes, this was an intention change. Based on usage inside Google, we found that the vast majority of `MatTable` instances were better served by `role="table"` than `role="grid"` and thus changed the default. 

Thanks for noting this issue @viniciusschuelter
