### ISSUE TITLE
validation for mat-select multi Angular 11?

### ISSUE THREAD

**Issue by suriyaJaay** [angular/components#23610]
Hi Team,

Is there any way to set form validation for `mat-select multi` like minimum one value to select so the enable submit button?
I've no clue to how and where to start with.? could someone help me on this?

How can enable button only after user selecting at least one value
[MINIMAL EXAMPLE](https://stackblitz.com/edit/angular-y1haz7?file=src%2Fapp%2Fselect-multiple-example.html)
```
onSelectionChange(e){
// how to get checkbox infromation here
}
```

Thanks

**Comment by lekhmanrus** [comment]
Please take a look [here](https://stackblitz.com/edit/angular-y1haz7-kakzvn?file=src%2Fapp%2Fselect-multiple-example.ts).

**Comment by wagnermaciel** [comment]
Closing since @lekhmanrus already posted the correct answer.
