### ISSUE TITLE
bug(material-date-fns-adapter): can't install a package

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/components#23621]
#### Reproduction

Steps to reproduce:
1. Navigate to an empty folder
2. Run `npm init -y`
3. Run `npm i @angular/material-date-fns-adapter`
4. Observe error:
   ```sh
   npm ERR! code ETARGET
   npm ERR! notarget No matching version found for tslib@0.0.0.
   npm ERR! notarget In most cases you or one of your dependencies are requesting
   npm ERR! notarget a package version that doesn't exist.
   npm ERR! notarget
   npm ERR! notarget It was specified as a dependency of '@angular/material-date-fns-adapter'
   ```
 
 
#### Expected Behavior

Package should be installed without error

#### Actual Behavior

Package installation does not work

#### Environment

- Angular: N/A
- CDK/Material: N/A
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment]
`@angular/material-date-fns-adapter` is not published as stable on NPM (yet), so to install it, you'd need to add `@next` currently, until we hit v13 stable. e.g.

```
yarn add @angular/material-date-fns-adapter@next
```
