### ISSUE TITLE
Form Field: Documentation should include ReactiveFormsModule

### ISSUE THREAD

**Issue by totally85** [angular/components#23622]
Link: https://material.angular.io/components/form-field/overview

In order to bind [formControl] to email in the Error Messages section, the user has to import ReactiveFormsModule in the app.module.ts file.

**Comment by gas0324** [comment]
When using colspan and sticky fixed columns at the same time, the scrolling is abnormal
The left of test2 is 0

**Comment by lekhmanrus** [comment]
That section is focused on `mat-error`, and not on type of form (Reactive / Template-Driven). [StackBlitz example](https://stackblitz.com/angular/moyeqnvjkovn?file=src%2Fmain.ts) has `ReactiveFormsModule` import though.
IMO, documentation looks pretty clear.

**Comment by crisbeto** [comment]
Closing since the generated examples already have the reactive forms module.
