### ISSUE TITLE
bug(cdk/overlay): OverlayRef.outsidePointerEvents() should not emit with mousedown inside overlay and mouseup outside it

### ISSUE THREAD

**Issue by kyubisation** [angular/components#23643]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-iikzo4?file=src%2Fmain.ts

Steps to reproduce:
1. Click open to open overlay
2. Mousedown inside the overlay, move mouse outside overlay and release click
 
 
#### Expected Behavior

`OverlayRef.outsidePointerEvents()` does not emit, since the mouse down did originate inside the overlay.
This is useful in scenarios where users want to mark text inside and overlay and copy it, but might move the cursor outside the overlay.

#### Actual Behavior

`OverlayRef.outsidePointerEvents()` emits (see console)

#### Additional notes

I implemented a workaround by replacing the 'click' event with the 'mousedown'; See overlay-outside-click-dispatcher.service.ts and main.ts:37-42
It is also certainly possible to implement a workaround that does not rely on `outsidePointerEvents()`, but it would be far easier to use it.

Unfortunately I don't know whether the current behavior is intentional by the components team or merely an oversight.

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The issue comes from the fact that we listen for `click` events at the `body`. I don't think that `mousedown` is a valid solution, because it won't account for touch devices.

**Comment by kyubisation** [comment]
Would additionally registering `touchstart` work?
This might cause the event handler to be called twice, depending on circumstances, but that should not be a problem.

**Comment by crisbeto** [comment]
I think that we could potentially use pointer events.

**Comment by kyubisation** [comment]
`pointerdown` seems to work with the above example.
However, I am limited in regard to testing devices. 
May I create a PR? Or would you like to deal with this in a different way?

**Comment by crisbeto** [comment]
Feel free to send a PR, but I expect that this will be difficult to land in Google, because people's tests will have to be updated to dispatch the correct event.

**Comment by kyubisation** [comment]
Ah, I see. Yes, that is a potential problem.
Nevertheless, I will create a PR for this, hopefully this week.
Is there any way to test that against the internal Google code base, without breaking the projects? (I'm not directly familiar with the Google monorepo setup.)
I was thinking about creating an automatic migration, but I don't think it's (easily) possible to detect this exact scenario.

**Comment by crisbeto** [comment]
We won't merge the PR unless it passes all of the internal checks, but I was pointing it out because it could stay open for a long time.

**Comment by kyubisation** [comment]
That's understandable.
I'll still try to provide the PR and we will try to find a workaround for our use case for the moment.

**Comment by kyubisation** [comment]
Maybe a naive question; the CDK already provides/uses `_isTestEnvironment` for the overlay container. Would it be an option to additionally register the `click` event in a test environment?

**Comment by crisbeto** [comment]
We generally try not to have drastically different behavior between tests and the real component. The `_isTestEnvironment` is used in two very specific cases that wouldn't have an effect on the actual application.

**Comment by kyubisation** [comment]
Yeah, that's reasonable. It was a long shot.

**Comment by crisbeto** [comment]
This also feels a little weird to me since people would have to be familiar with the internals of the dispatcher in order to use the API. And as you mentioned, there's the issue of double events. I'll add this issue for discussion during our next team meeting to get some different perspectives on it.

**Comment by kyubisation** [comment]
Could you elaborate a bit more on 1.?

As for the workaround; Yes, this should work, but as a library author this might have unintended consequences. So, I will probably have to implement another workaround.

**Comment by crisbeto** [comment]
I think that this part is problematic, because it can break for events coming from the shadow DOM:

```
    // The composed path of the pointerdown event will always be empty
    // in this scenario so we directly use the target property.
    return pointerDownEvent?.target ?? _getEventTarget(event);
 ```

I think you could work around it by saving the result from `_getEventTarget` during the `pointerdown` though.

I'm also not sure why we would need the 5s grace period. Couldn't we save the event target on `pointerdown`, compare it on `click` and then clear it? When another click happens, it'll overwrite the target. Also CCing @jelbourn here in case he has any input.

**Comment by kyubisation** [comment]
The grace period was intended as a fail-safe for unexpected scenarios, but it might not be necessary.

Thanks for the hint with `_getEventTarget` during the event context. I adapted it accordingly:
https://stackblitz.com/edit/components-issue-c4nuas?file=src/app/overlay-outside-click-dispatcher.service.ts
