### ISSUE TITLE
bug(Expansion Panel): Last item in non-white accordion has white flickering

### ISSUE THREAD

**Issue by DavyKoravand** [angular/components#23648]
#### Reproduction

Steps to reproduce:
1. Use an Angular Material theme which has a non-white accordion.
2. Create an accordion with at least 2 expansion panels (I have tested 4 myself, that definitely works, using that in the code example).
3. Click on the last item to collapse it. You will see white flickering at the bottom.

See the red arrow in the image below (ignore the blue censoring):
![image](https://user-images.githubusercontent.com/22157621/134992252-f7f603a7-c078-4b92-b32a-13d8c2518ecd.png)

Repro code (requires a non-white theme for the accordion):
```
<mat-accordion>
    <mat-expansion-panel>
        <mat-expansion-panel-header>
            <mat-panel-title><fa-icon [icon]="faQuestionCircle"></fa-icon>T</mat-panel-title>
        </mat-expansion-panel-header>
        <p>D</p>
        </mat-expansion-panel>
        <mat-expansion-panel>
        <mat-expansion-panel-header>
            <mat-panel-title><fa-icon [icon]="faQuestionCircle"></fa-icon>T</mat-panel-title>
        </mat-expansion-panel-header>
        <p>D</p>
        </mat-expansion-panel>
        <mat-expansion-panel>
        <mat-expansion-panel-header>
            <mat-panel-title><fa-icon [icon]="faQuestionCircle"></fa-icon>T</mat-panel-title>
        </mat-expansion-panel-header>
        <p>D</p>
        </mat-expansion-panel>
        <mat-expansion-panel>
        <mat-expansion-panel-header>
            <mat-panel-title><fa-icon [icon]="faQuestionCircle"></fa-icon>T</mat-panel-title>
        </mat-expansion-panel-header>
        <p>D</p>
        </mat-expansion-panel>
</mat-accordion>
```
 
 
#### Expected Behavior

The color should just be flat, no white flickering.

#### Actual Behavior

White pixels flickering at the bottom of the collapsed last item.

#### Environment

- Angular: 12.2.7
- CDK/Material: 12.2.7
- Browser(s): Google Chrome & Microsoft Edge are tested, both have it
- Operating System: Windows 10

**Comment by crisbeto** [comment]
I tried it against a few different browsers across a few devices and I wasn't able to reproduce it. This looks like a rendering artifact from your particular setup and I'm not sure that we can do much about it. E.g. I've seen something similar when I'm remoting into another machine and there's a CSS transition.
