### ISSUE TITLE
bug(mat-card): Picture elements on mat-cards have incorrect top-margin, when no heading is present

### ISSUE THREAD

**Issue by Trombach** [angular/components#23649]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-5lp7n2?file=src/app/example-component.html

Steps to reproduce:
1. Create a `<mat-card>` element with no title, or subtitle
2. Add a `<picture>` element with at least one `<source>` element
```html
<mat-card>
  <picture>
    <source
      srcset="https://material.angular.io/assets/img/examples/shiba2.jpg"
    />
    <img mat-card-image />
  </picture>
</mat-card>
```
 
#### Expected Behavior

What behavior were you expecting to see?

The top of the image should be flush with the top edge of the card, just like when using an `<img/>` tag

#### Actual Behavior

What behavior did you actually see?

There was a gap between the top edge of the card and the image. This is due to how the css class that overwrites the padding of the card is applied [here](https://github.com/angular/components/blob/6e1f522d6a50d6f589d069775bc771b5590bff4c/src/material/card/card.scss#L191).

#### Environment

- Angular:
- CDK/Material: 12.2.7
- Browser(s): Chrome 94, Safari 15
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I've submitted #23678 to fix it. Note that you'll also have to move the `mat-card-image` attribute to the `picture` element itself.

**Comment by Trombach** [comment]
@crisbeto Thanks for the quick fix! Much appreciated
