### ISSUE TITLE
Stackblitz examples are broken

### ISSUE THREAD

**Issue by sonukapoor** [angular/components#23641]
It seems that all of the stackblitz examples are broken. Whenever I click on the stackblitz icon in any of the angular material examples tab, I get the below screen:

![image](https://user-images.githubusercontent.com/59734/134788489-37824a5f-3237-4ac1-bbc1-c86951a178de.png)

Here is the URL to one of the examples:

https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Ftable-harness-example.ts

This link was opened from this page:

https://material.angular.io/components/table/examples

**Comment by crisbeto** [comment]
Should be resolved by https://github.com/angular/material.angular.io/pull/1075.
