### ISSUE TITLE
feat: Create a fab-speed-dial component

### ISSUE THREAD

**Issue by mmalerba** [angular/components#23654]
#### Feature Description

The spec allows for FABs to be arranged in a [speed-dial](https://material.io/components/buttons-floating-action-button#types-of-transitions). We should discuss if this is something we want to add built-in support for.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/860.

**Comment by mmalerba** [comment]
I thought there was an open issue for that somewhere, I couldn't find it though. Thanks!
