### ISSUE TITLE
Allow MatSnackBarRef to be closed with an ActionValue

### ISSUE THREAD

**Issue by angelaki** [angular/components#23660]
Currently the Snackbar can only be `dismiss`'ed or `dismissWithAction`'ed. And the action cannot be passed! So if I have more than one action I need to store the result in a static scope (or am I mistaken?). Wouldn't it make much more sense to just have a dismiss-method with an optional value parameter? Like the MatDialog has?

This dismiss / dismissWithAction thing really feels dusty ...

**Comment by crisbeto** [comment]
I think that it limited on purpose, because snack bars are meant primarily for simple pieces of information that go away automatically after a certain amount of time, not for passing data around.

**Comment by angelaki** [comment]
In general I totally agree with you - but my scenario is quite plausible, too:

I show an event with a close button and an action. Now there are three scenarios absolutely relevant for me:

- snackbar hid **unnoticed**
- snackbar hid **intentionally**
- command was selected

Guess that's a pretty common and justifiable usecase. So come on, give it a bit more prio 👍 Not at least since it costs absolutely no effort.

**Comment by crisbeto** [comment]
I'll add this for discussion in our next team meeting.

**Comment by jelbourn** [comment]
We discussed this and decided that this is a especially niche use case considering the snackbar's intended use in the Material Design spec. We'll leave it open at the lowest priority for now and revisit if there's more demand in the future.

**Comment by angelaki** [comment]
Ok, so I'll probably go on with my global variable. Eventhough I see no need to **not** just let the snackbar use a similar interface the dialog uses - it has no disadvantages.

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because it doesn't appear to have gotten any traction since the last discussion.
