### ISSUE TITLE
selected index dosen't work well

### ISSUE THREAD

**Issue by ziedunited92** [angular/components#23676]
I use angular stepper in my application and when i click the button to go to next step the selected index is always the first step unless you refresh the page. this is my code can any one help me please:

This is the function triggered when i hit the next step button:
![image](https://user-images.githubusercontent.com/50137270/135625879-995525eb-2752-4cd2-a967-81dfdcb1daa7.png)

and this is my ngOnInit function:
![image](https://user-images.githubusercontent.com/50137270/135626054-2b77e8b5-8772-47b9-9c79-d2d5a69792bc.png)

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Comment by ziedunited92** [comment]
@crisbeto I am sorry i didn't follow the template but you can just read my issue and help me if you want . This is not helpfull to close the issue without resolving it .

**Comment by crisbeto** [comment]
A couple of screenshots of code with no context around them isn't enough information to investigate a potential bug.
