### ISSUE TITLE
can't initilize the stepper while closing the modal

### ISSUE THREAD

**Issue by ziedunited92** [angular/components#23675]
I use an angular stepper in a child component and i call it in a parent component which contain a modal. I need to initialize the stepper in each time i close the modal so i use this code:

@ViewChild('stepper') stepper: MatStepper;

 popup_hiding(stepper: MatStepper) {
    
     this.stepper.selectedIndex = 0;
     this.stepper.reset();
    
    

  }

but in my case i get the stepper as undefined . can any one help me please 
![image](https://user-images.githubusercontent.com/50137270/135624207-60585fc1-3537-4859-a18d-b1bae61c3601.png)

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
