### ISSUE TITLE
Add Customize Css Class to the Mat-Tab-Content and other Mat-X tags which are generated runtime

### ISSUE THREAD

**Issue by angelaki** [angular/components#23685]
Found this old issue that has been unresolved closed: https://github.com/angular/components/issues/9290.

I want to apply styles to specific `mat-tab-body`s but classes on the `mat-tab` component aren't applied on the `mat-tab-body` - or actually nowhere; they just get lost.

How about just applying them there?

**Comment by crisbeto** [comment]
Which element are you trying to apply the class on exactly? The `mat-tab-body` is an internal component that isn't available outside the `MatTabModule`.

**Comment by angelaki** [comment]
Yeah, that's right. My problem is: right now I am not able to somehow mark a `mat-tab-body` depending on it's related `mat-tab`. In my case I'd like to disable the scrolling behavior (but only for one tab) since the component inside offers it's own.

My current solution is `css nth-child` ... But ... I'd think you'd agree, that this is no _solution_ 😉

**Comment by crisbeto** [comment]
You're right, we don't have a good way of doing this at the moment. You might be able to work around it using a lazy-loaded tab and wrapping the content in your own `div` with a specific class. See https://material.angular.io/components/tabs/overview#lazy-loading.

**Comment by angelaki** [comment]
It least a good solution for now - thank you!

**Comment by angelaki** [comment]
Sorry, a bit off-topic, but: can recycle of these template be controlled? I'd like to keep them, as soon as they've been created once.
