### ISSUE TITLE
@types/googlemaps DEPRECATED

### ISSUE THREAD

**Issue by A2Ple98** [angular/components#23696]
Hi, I've been having a lot of issues lately with this package, as it was deprecated and now @types/google.maps is the one to use. Many other packages are using the new one so conflits arise when installing both types. This problem exists in both 12.2.8 and 11.2.13. The packages I had problems were @googlemaps/js-api-loader and @googlemaps/markerclusterer. For the last one I had to go back to the previous versions of the package @googlemaps/markerclustererplus and not use the latests version (1.2.3), I had to go back to 1.1.0 which was published 7 months ago. 
Is there any posibility for this to be fixed in v11lts and latests please?

**Comment by crisbeto** [comment]
We're switching to the non-deprecated typings in version 13. We can't backport this to an earlier version, because it's technically a breaking change.
