### ISSUE TITLE
feat(ANGULAR GOOGLE MAPS): Is it possible to use the new package @googlemaps/markerclusterer? 

### ISSUE THREAD

**Issue by francesco-clementi-92** [angular/components#23695]
#### Feature Description

I'd like to use the package https://www.npmjs.com/package/@googlemaps/markerclusterer instead of the old one https://www.npmjs.com/package/@googlemaps/markerclustererplus.

#### Use Case

It will be possible to use different algorithms, improve performance and more.

**Comment by luca-sharryland** [comment]
Does this issue still not consider for new updates? Is it possible to vote again?

**Comment by royvanderwesten** [comment]
We really need to reopen this issue. It took me too long to realize that I have to use the new Markerclusterer package, but add the script tag of the old markerclusterer package to the head. Otherwise I get the markerclusterer class not found error. I'm not even sure it's a features, seems more like a bug to me.

**Comment by zellkon** [comment]
I have same issue, Can we fix this issue ?

**Comment by itayperry** [comment]
Will this make the `<map-marker-clusterer>` component work?

**Comment by PhSlowSense** [comment]
I have the same problem, using the map-marker-clusterer component throw the error "class not found" that recommend to install the deprecated MarkerClustererPlus library...

**Comment by rbalet** [comment]
@PhSlowSense and @volo4dev 

For me, the only version that is working is the following.
```
"dependencies": {
    "@googlemaps/markerclusterer": "^2.1.4",
},
"devDependencies": {
    "@types/google.maps": "^3.53.2",
}
```

**Comment by PhSlowSense** [comment]
Thanks @rbalet I will try !

**Comment by runette** [comment]
For information - in my app I created a component based on the code in the draft PR https://github.com/angular/components/pull/24853 updated for the latest version of the component and for Dynamic API loading.

This seems to work well for me - but I make no guarantees.

I have added an Input to tell the clusterer when the API is loaded - which I linked to the google map "loaded" output event. I am very sure that there are better ways of doing this but I don't have the time to find out.

If I find the time - I might create a new PR based on this and someone can improve that.

The component is in this gist: 

https://gist.github.com/runette/3cc43124bad49df69e28ae177cfdc8b9

the calling html is :

```(html)
<google-map height="100%"
            width="100%"
            [options]="options"
            (mapInitialized)="loaded($event)"
>
    <new-map-marker-clusterer
        [options]="clusterOptions"
        [apiInitialized]="apiLoaded"
    >
        @for (marker of markerPositions; track marker) {
            <map-marker 
                [position]="marker.position" 
                [icon]="marker.icon" 
                [clickable]="true"
                (mapClick)="markerClick($event)"
            />
        }
    </new-map-marker-clusterer>
</google-map>
```

and 

```(ts)
  loaded($event) {
    this.apiLoaded.next();
}
```

**Comment by jmeinlschmidt** [comment]
Support for Advanced Markers with Marker Clusterer is currently missing. This is related to https://github.com/angular/components/issues/29187 and https://github.com/angular/components/issues/23695.
