### ISSUE TITLE
./node_modules/@angular/material/fesm2015/core.js:150:26-44 - Error: export '_isTestEnvironment' 

### ISSUE THREAD

**Issue by dean-g** [angular/components#23690]
ng build is throwing the following error with the recent version upgrade, 

./node_modules/@angular/material/fesm2015/core.js:150:26-44 - Error: export '_isTestEnvironment' (imported as '_isTestEnvironment') was not found in '@angular/cdk/platform' (possible exports: Platform, PlatformModule, _getEventTarget, _getFocusedElementPierceShadowDom, _getShadowRoot, _supportsShadowDom, getRtlScrollAxisType, getSupportedInputTypes, normalizePassiveListenerOptions, supportsPassiveEventListeners, supportsScrollBehavior)

Can someone please check this and advise?

**Comment by crisbeto** [comment]
Most likely yours versions of `@angular/material` and `@angular/cdk` don't match. Usually it isn't a problem unless we add a new API to the CDK like here.

**Comment by dean-g** [comment]
Thank you so much @crisbeto. it worked now!
