### ISSUE TITLE
feat(google-maps): Getting google.maps.Map instance

### ISSUE THREAD

**Issue by piernik** [angular/components#23703]
#### Feature Description

Getting `google.maps.Map` instance with `ViewChild` is over complicated and You have to use `setTimeout` to wait for map init. Maybe introducing `(mapReady)` with instance as `$event` ?

#### Use Case

I need it to manipulate mapTypes

**Comment by viniciusschuelter** [comment]
Was this not fixed in the PR https://github.com/angular/components/pull/23856 ? @andrewseguin
