### ISSUE TITLE
bug(MatTabHeader): Rouding problem when zooming will show PaginationControls when not needed

### ISSUE THREAD

**Issue by Anderman** [angular/components#23724]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-1v9muy
see also issue [mat-tab-header-pagination displaying incorrectl](https://github.com/angular/components/issues/17347)

Steps to reproduce:
1. open in fullscreen and try to zoom in and out until there are PaginationControls visible 
2. 
 
 
#### Expected Behavior

No PaginationControls  when not needed

#### Actual Behavior

PaginationControls are visible. Sometimes they are always but are not easy to reproduce in stackblitz

#### Environment

- Angular:
- CDK/Material:
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
![image](https://user-images.githubusercontent.com/1858745/136715605-a68bba5d-ef02-4f16-aec3-41e9bfb8c367.png)

Can be fixed by adding 1
see also [SO](https://stackoverflow.com/questions/40879171/in-javascript-why-does-getboundingclientrect-sometimes-return-floating-point)

// original code from [paginated-tab-header](https://github.com/angular/components/blob/dda2e0f6f21238197bab801fe939de011bca3764/src/material/tabs/paginated-tab-header.ts)
```typescript
function _checkPaginationEnabled(this: MatTabHeader) {
  if (this.disablePagination) {
    this._showPaginationControls = false;
  } else {
    // const isEnabled = this._tabList.nativeElement.scrollWidth > this._elementRef.nativeElement.offsetWidth;
    const isEnabled = this._tabList.nativeElement.scrollWidth > this._elementRef.nativeElement.offsetWidth + 1;
    if (!isEnabled) {
      this.scrollDistance = 0;
    }

    if (isEnabled !== this._showPaginationControls) {
      this._changeDetectorRef.markForCheck();
    }

    this._showPaginationControls = isEnabled;
  }
}
```

Log of scrollwidth,offsetwidth when zooming in and out. The scrollwidth is not constant with a specefic zooming level but offset width is.
![image](https://user-images.githubusercontent.com/1858745/136743964-e441d6be-fa0b-4d83-b98d-9594878c19cf.png)

**Comment by jelbourn** [comment]
@Anderman at which zoom level do you run into this?
