### ISSUE TITLE
Some IE11 cleanups accidentally landed in 12.2.x

### ISSUE THREAD

**Issue by thedavids** [angular/components#23736]
#### Reproduction

Steps to reproduce:
1. Use @angular/material version 12.2.8 or later
2. Import the MatBadgeModule in your app module
2. Create a div with a matBadge (ex: <div [matBadge]="123">Test</div>)
3. Open in Internet Explorer to see the badge is not displayed and that there is an error in the console

It seems to be because of this line
`const badges = this._elementRef.nativeElement.querySelectorAll(`:scope > .${BADGE_CONTENT_CLASS}`);`
located in this method `_clearExistingBadges`
In the badge component
 
#### Expected Behavior

We should see the badge correctly even in IE

#### Actual Behavior

The badge is not displayed and we have a syntax error in the IE console

#### Environment

- Angular: 12.2.8
- CDK/Material: 12.2.8
- Browser(s): Internet Explorer
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
@crisbeto did some digging and determined that issue related to datepicker here comes from a missing polyfill 

```
/**
 * IE11 requires the following for NgClass support on SVG elements
 */
// import 'classlist.js';  // Run `npm install --save classlist.js`.
```

Closing this since the other issue (badge) has been reverted and should be back to normal in the next patch release.
