### ISSUE TITLE
bug(cdk-virtual-scroll-viewport): Changing viewport size does not trigger recalculation

### ISSUE THREAD

**Issue by zacnomore** [angular/components#23753]
#### Reproduction

Editor: https://stackblitz.com/edit/components-issue-qzvagd?file=src/app/example-component.html
Viewer: https://components-issue-qzvagd.stackblitz.io/

Steps to reproduce:
1. Be careful to not change the viewport size while viewing this example. For example, hovering the menu bar on MacOS will trigger a resize event.
2. Wait for the animation to complete
3. Scroll through the list, note the visible gap between the last item and the bottom of the viewport

To see the expected behavior resize the window to trigger a recalculation
 
 
#### Expected Behavior
The change in the virtual scroll viewport's size should trigger a recalculation and show items to fill the newly available space

#### Actual Behavior
When the scrollable area grows, empty space becomes visible and persists while scrolling

#### Environment

- Angular: 12.2.5
- CDK/Material: 12.2.5
- Browser(s): Firefox 93, Chrome 94
- Operating System:  Windows 10 -  10.0.19043, macOS Big Sur - 11.6

**Comment by mmalerba** [comment]
dup of #10117
