### ISSUE TITLE
Does cdkDrag suppress native drag and drop events? 

### ISSUE THREAD

**Issue by peternixey** [angular/components#23765]
#### What are you trying to do?

Use native drag and drop events such as `dragstart`, `dragenter` and `dragexit` in conjunction with cdkDrag. Without these it's hard to build richer behaviours in as well as things like visually highlighting the drop zone. 

#### What troubleshooting steps have you tried?

I have tried attaching these events to both the container list and the individual draggable list items but they don't seem to fire.

#### Reproduction

https://components-issue-un5pqw.stackblitz.io

Steps to reproduce:
1. Go to the stackblitz
2. Try dragging items in the list
3. Notice that the ondragstart event doesn't fire
4. Try adding other native drag events and see whether they work - I can't seem to make them do so
  
#### Environment

- Angular: 12.2.9
- CDK/Material: 12.2.9

**Comment by crisbeto** [comment]
It suppresses the native events so that they don't interfere with the custom dragging, but there are events and CSS classes that should allow you to achieve the same result. E.g. you can use the `cdk-drop-list-receiving` class to style a drop zone that can receive an item. See https://material.angular.io/cdk/drag-drop/overview#styling.

**Comment by peternixey** [comment]
@crisbeto, thanks for taking the time to respond. In light of @YipingRuan’s question how would one fire events on other elements? Just treat them as single item lists?

What I’m starting to perhaps realise is that it might be the terminology that’s throwing me off. I assume that a droplist needs to be a list in the way we would conventionally think of a list. What I’m starting to consider is that maybe it’s just a droparea which incidentally comes with sortable list functionality. 

That sounds like a trivial distinction but understanding it would probably help me a lot with understanding the drag and drop ethos in material. Is that the correct interpretation?

**Comment by YipingRuan** [comment]
@crisbeto 
Thank you.

If my understanding is correct, you meant I should not use `cdkDropList` if I want to move list item around.
Use `cdkDrag` and events like `cdkDragEntered` will be fired at the landing DOM.

**Comment by crisbeto** [comment]
Closing the issue since there's doesn't seem to be anything for us to do.
