### ISSUE TITLE
help(Bottom-sheet): Not able to add button above bottom sheet

### ISSUE THREAD

**Issue by indraraj26** [angular/components#23785]
#### What are you trying to do?

I am trying to add one button just above the bottom sheet with z-index of 9999 but button is not fully visible.
It is working fine if i remove `transform: translateY(0%);`  from tag `mat-bottom-sheet-container`.  but it is not so smooth as you can see 
Playground: [stackblitz working](https://stackblitz.com/edit/angular-qjac1g-eb5esr?file=src%2Fapp%2Fbottom-sheet-overview-example-sheet.html)

Question: 
Why did we use this transform on mat-bottom-sheet-container?
is there any side-effect if i remove this transform from mat-bottom-sheet-container?

#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? 

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
- Components: https://stackblitz.com/edit/angular-qjac1g?file=src%2Fapp%2Fbottom-sheet-overview-example-sheet.html

Steps to reproduce:
1. none
  
Current Output: 
![image](https://user-images.githubusercontent.com/23274631/137854434-fd862971-c2c6-49d7-98cb-a27fbaa99efa.png)

Expected Output: 
![image](https://user-images.githubusercontent.com/23274631/137854554-a58de7c8-100f-4d30-ab72-75d8b222a45b.png)

#### Environment

- Angular:  12
- CDK/Material:12
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by lekhmanrus** [comment]
You also could try adding overflow property to custom CSS class in `panelClass` option:
```css
::ng-deep .mat-bottom-sheet-container.overflow-visible {
  overflow: visible;
}
```
See [StackBlitz](https://stackblitz.com/edit/angular-qjac1g-c7see9?file=src%2Fapp%2Fbottom-sheet-overview-example-sheet.html).
