### ISSUE TITLE
card: allow for 'center' alignment

### ISSUE THREAD

**Issue by chakrachi** [angular/components#23784]
please allow for center keyword in alignment for card actions

export declare class MatCardActions {
/** Position of the actions inside the card. */
align: 'start' | 'end' | 'center';
}

it works fine when added

**Comment by crisbeto** [comment]
Setting this at a low priority, because while there's nothing in the spec that disallows centered actions, I don't think that it makes sense from a design perspective.

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing the issue, given that it hasn't had much traction and the actions will look weird if they're positioned in the center. If you want to do this anyway, you can add the following style to your app:

```css
.mat-card-actions {
  display: flex;
  justify-content: flex-end;
}
```
