### ISSUE TITLE
Help: Error while passing ci/circleci: api_golden_checks for Google Maps.

### ISSUE THREAD

**Issue by umernaeem217** [angular/components#23782]
I am trying to create a PR and the PR is causing failed **_ci/circleci: api_golden_checks_**. I have tried running `yarn approve-api google-maps` but this command also gives an error `ERROR: Skipping '//tools/public_api_guard:google-maps/.md_api.accept': no such target`.   I think that my project is not configured properly. Can someone help me know the steps you have to follow before creating a PR.

PR Link:
https://github.com/angular/components/pull/23775

I am attaching the error screenshot.
![image](https://user-images.githubusercontent.com/34766137/137779454-e3cf7255-a3f8-4c0e-be38-cb5a9c6b0abd.png)

- Browser(s): Chrome
- Operating System Windows 10.

**Comment by crisbeto** [comment]
It's an issue with the `approve-api` script that has been there for a while now. You can achieve the same result with this: `yarn bazel run //tools/public_api_guard:google-maps/google-maps.md_api.accept`.
