### ISSUE TITLE
feat(tabs): mat-tab-nav-bar should support routerLinkActive

### ISSUE THREAD

**Issue by karmasakshi** [angular/components#23801]
#### Feature Description

At present, `mat-tab-nav-bar` expects active state to be maintained via a boolean expression as mentioned here: https://material.angular.io/components/tabs/overview#tabs-and-navigation. Instead of setting `[active]="booleanExpression"`, can we leverage the `routerLinkActive` directive or have a simpler way to maintain the active state?

#### Use Case

Since this component is primarily used for navigation, I think simplifying the active state management would be a good addition to the component.

**Comment by Totati** [comment]
For us it was not. When you are not using an `*ngFor` (we are not) it gets quite ugly. We use this [custom MatTabLinkActive directive](https://stackblitz.com/edit/angular-ytrt16?file=src%2Fapp%2Fmat-tab-link-active.directive.ts). It's basically a hack as it bypasses TypeScript, however in Angular 13 we will change it for a simple directive that not extends the `RouterLinkActive` but injects it, beacuse RouterLinkActive will have an [isActiveChange](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link_active.ts#L118) event.
