### ISSUE TITLE
Angular material Dialog screen have no fadeout transition while closing the dialog box.

### ISSUE THREAD

**Issue by abhijithraj221** [angular/components#23816]
While closing dialog screen there is no transition effect like when opening dialog.

While we try to close by clicking the button or outside dialog screen, dialog screen suddenly closes without a transition effect.

It is also not showing on the angular material official website ( https://material.angular.io/components/dialog/overview ).

There is no option to add a custom animation for dialog on the angular material website.

Looking forward to fixing this issue.

Thanks

**Comment by crisbeto** [comment]
We do have a closing animation, but it's much more subtle when closing which makes it a little harder to notice. This is according to the Material design spec. Here's where the animation is defined https://github.com/angular/components/blob/master/src/material/dialog/dialog-animations.ts#L37.
