### ISSUE TITLE
feat(cdk/scrolling): scroll-to-top sticky button

### ISSUE THREAD

**Issue by maurice85** [angular/components#23835]
#### Feature Description

After you've scrolled down for an X amount of pixels a sticky button appears on the bottom right which causes the scroll index
to reset to zero when pressed. This automatically scrolls the virtual scroller back to the top. Very handy for large lists. Primefaces already [has such a component](https://www.primefaces.org/primeng/showcase/#/scrolltop) but its not compatible with the virtual scroller of angular.

#### Use Case

When having scrolled down a lot, you can quickly go back to the top with one click of the button, instead of having to manually scroll up.

**Comment by crisbeto** [comment]
I don't think that this belongs in the CDK. The UX of the button very much depends on the app's UX and the CDK tries to be as UX-agnostic as possible.
