### ISSUE TITLE
help(COMPONENT): Input text overlapping issue

### ISSUE THREAD

**Issue by vishalsinghpoker** [angular/components#23833]
i tried the listed issue on this repo to fix the mat input text overlapping issue. Overlapping issue not coming always, its a random case.

I tried to fetch the data from api and then patching to form. 
Check the Image to get more idea about issue- https://ibb.co/DWLqZx8

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
