### ISSUE TITLE
bug(mat-tab-group): reordering tabs does not work if ivy is activated 

### ISSUE THREAD

**Issue by legrottagliegionata** [angular/components#23859]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/mat-tabs-ordering?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Click "tab2"
2. "tab2" is visible 
3. Click "tab1"
4. "tab1" is visible
5. Click "reverse" button
6. Click "tab2"
7. "tab2" is broken.

**this only happens when the "Settings" -> "Enable Ivy" flag is enabled** 
 
#### Expected Behavior

The tabs should change their order and clicking them should appear

#### Actual Behavior

The tabs are sorted but clicking on some tabs the content is not rendered

#### Environment

- Angular: 12.2.12
- CDK/Material: 12.2.12
- Browser(s): Chrome Versione 95.0.4638.54 (Build ufficiale) (arm64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS/Ubuntu

**Comment by crisbeto** [comment]
This is caused by an issue in the framework https://github.com/angular/angular/issues/18847.
