### ISSUE TITLE
bug(datepicker): Datepicker Range not honoring min & max

### ISSUE THREAD

**Issue by donbwhite** [angular/components#23866]
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1.  Create Datepicker Range or use the [Datepicker Range SB Example](https://stackblitz.com/angular/kglymmqaxjx?file=src%2Fapp%2Fdate-range-picker-overview-example.ts)
2. add min and/or max options
3. in UI open modal to select dates
 
 
#### Expected Behavior

What behavior were you expecting to see?
Dates before the min and after the max should be greyed out and not selectable (as with a single datepicker)

#### Actual Behavior

What behavior did you actually see?
All dates are selectable. Not being disabled.

#### Environment

- Angular: 11.2 & 12.2
- CDK/Material: 11.2 & 12.2
- Browser(s): Chrome, Brave, FireFox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by lekhmanrus** [comment]
Looks like it is working as expected, isn't it? See [StackBlitz](https://stackblitz.com/edit/angular-cgcfhw?file=src%2Fapp%2Fdate-range-picker-overview-example.html).

**Comment by donbwhite** [comment]
You're right @lekhmanrus . I was placing the min/max in the wrong place. Thought it went on the input tags.
