### ISSUE TITLE
bug(mat-form-field): label is not aligned when using text-align center

### ISSUE THREAD

**Issue by gleisonkz** [angular/components#23867]
#### Reproduction

https://stackblitz.com/edit/components-issue-d6xpva?file=src%2Fapp%2Fexample-component.html

![image](https://user-images.githubusercontent.com/48810597/139714782-9d7d9758-a5ef-473d-989d-a254612c775d.png)

Steps to reproduce:
1.  click inside the input 
 
#### Expected Behavior

When the input is focused, the label and the gap in the outline should be properly aligned.

#### Actual Behavior

The gap is placed based on the initial value of input so if the initial value of input is not set , the label will appear misaligned.

#### Environment

- Angular:
- CDK/Material: 12.2.9
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We don't support this, because it isn't in the Material design spec.
