### ISSUE TITLE
bug(mat-form-field): label is not within the border gap for outline appearance

### ISSUE THREAD

**Issue by sbrunecker** [angular/components#23863]
#### Reproduction

https://stackblitz.com/edit/components-issue-jbhqbn

![image](https://user-images.githubusercontent.com/33121464/139562394-3935cd13-b9cf-403c-9ce1-0215801db51e.png)

Modify the initial value of `countryCode` in `src/app/example-component.ts` to see that the gap is moving based on the initial prefix length (e.g. `""` and `"+12345"`).

![image](https://user-images.githubusercontent.com/33121464/139562520-f137efc0-ad30-4b30-9cfc-4f3f710d91c6.png)
![image](https://user-images.githubusercontent.com/33121464/139562534-475739ef-b37e-4ddf-9f2a-83b4e28640c6.png)

Now changing the country to USA:

![image](https://user-images.githubusercontent.com/33121464/139562640-d265f4ed-c47c-4431-94dc-cf944abf639d.png)

 
 
#### Expected Behavior

When the input is focused, the label and the gap in the outline are properly aligned in the upper left corner. 

#### Actual Behavior

The gap is placed based on the initial prefix while the label is placed based on the current prefix so if the initial prefix length is not the same as the current prefix length, the label will appear misaligned.

#### Environment

- Angular: 12.2.9
- CDK/Material: 12.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I've pushed #23869 which will fix this. Until the fix is released, you can also resolve it on your end by calling `updateOutlineGap` on the form field when the prefix changes.
