### ISSUE TITLE
Drag and Drop example broken

### ISSUE THREAD

**Issue by leonardb** [angular/components#23865]
https://material.angular.io/cdk/drag-drop/overview#cdk-drag-drop-disabled-sorting

In the description it states ```in addition to preserving the dragged item's initial position in the source list, if the user decides to return the item.```

Initial position is not preserved when an item is dragged from left panel to right panel and then returned.

When the item is returned it is placed wherever dropped, not in its initial position.

**Comment by crisbeto** [comment]
Note to self: this seems to work some of the time, but other times the item gets inserted at the point where it enters the start container. In particular, it happens consistently when dragging the last item in the left column, but all other items return to their initial positions as expected.
