### ISSUE TITLE
bug(mat-form-field): PLACEHOLDER IS EMPTY BY DEFAULT

### ISSUE THREAD

**Issue by pacocom** [angular/components#23893]
#### Reproduction
```html
<mat-form-field>
  <mat-label>Filter Scopes</mat-label>
  <input
    matInput
    [(ngModel)]="filterValue"
    (keyup)="applyFilter()"
    placeholder="Filter"
  />
</mat-form-field>
```
Angular Material < 10
When input is not focused -> input.placeholder = 'Filter';
When input is focused -> input.placeholder = 'Filter';

Angular Material >= 10
When input is not focused -> input.placeholder = '';
When input is focused -> input.placeholder = 'Filter';

**Why input has empty placeholder when input isn't focused?**
**I want input.placeholder has always with its own value.**
**I don't want to use floatLabel="always".**

```html
<mat-form-field floatLabel="always">
  <mat-label>Filter Scopes</mat-label>
  <input
    matInput
    [(ngModel)]="filterValue"
    (keyup)="applyFilter()"
    placeholder="Filter Scopes"
    test-selector="pi-scope-filter"
  />
</mat-form-field>
```
When input is not focused -> input.placeholder = 'Filter';
When input is focused -> input.placeholder = 'Filter';

Use StackBlitz to reproduce your issue: 
version <10 https://stackblitz.com/edit/angular-9-material-starter-3byooq
version >=10 https://stackblitz.com/edit/angular-ivy-pfcpwr

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior
Placeholder always has value.

#### Actual Behavior

What behavior did you actually see?
Placeholder has value only if input is focused

#### Environment
  "dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "^9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "core-js": "^3.6.4",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "^0.10.3"
  },

versus 

  "dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/cdk": "12.2.12",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/material": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
    "rxjs": "^7.3.0",
    "tslib": "^2.3.1",
    "zone.js": "^0.11.4"
  },

**Comment by jelbourn** [comment]
This is working as intended- the floating label is rendered where the placeholder would normally be (when not floating, which happens with focus by default). Rendering them both would cause one to render on top of the other.

**Comment by pacocom** [comment]
Please, reopen, this is not the problem, can you read the problem?

The problem is that native input.placeholder is empty when isn't focused (angular-material >= 10).
![image](https://user-images.githubusercontent.com/7735329/140473129-465016b7-f2d8-4999-b6c3-1160ad4fb037.png)

Why?
