### ISSUE TITLE
bug(mat-drawer-container, mat-tab-group): Contents popping in and out when using ":enter" or ":leave" animation

### ISSUE THREAD

**Issue by MetaMoRpheXx** [angular/components#23890]
#### Reproduction

https://stackblitz.com/edit/components-issue-fmg4zf?file=src%2Fapp%2Fexample-component.html

Steps to reproduce:
1. Place an `*ngIf` and animation (_using :enter or :leave_) on `mat-tab-group` or `mat-drawer-container` either on a parent element or at the element itself.
2. toggle the `*ngIf` value.
 
 
#### Expected Behavior

Contents inside those component shouldn't pop in or out when the parent element is animating. 

#### Actual Behavior

Some parts and contents of the components blinks out or in before the animation is finished. Haven't tested it on other components, it might have that issue as well.

#### Environment

- Angular: 12.2.10, 12.2.12, 13.0.0
- CDK/Material: 12.2.10, 12.2.12, 13.0.0
- Browser(s): Chrome, Edge
- Operating System: Windows

**Comment by crisbeto** [comment]
It's because by default the animations module blocks children from animating when a parent has a running animation. We can't do much about it on our end, but you can tweak your animation to use `animateChild`. https://stackblitz.com/edit/components-issue-ztwdsz?file=src%2Fapp%2Fexample-component.ts
