### ISSUE TITLE
bug(mat-form-field): PLACEHOLDER IS EMPTY BY DEFAULT

### ISSUE THREAD

**Issue by pacocom** [angular/components#23903]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 9

#### Reproduction
```html
<h4>floatLabel="auto"</h4>
<mat-form-field>
  <mat-label>Filter Scopes</mat-label>
  <input matInput placeholder="Filter" />
</mat-form-field>
```
Angular Material < 10
When input is not focused -> input.placeholder = 'Filter';
When input is focused -> input.placeholder = 'Filter';

Angular Material >= 10
When input is not focused -> input.placeholder = '';
When input is focused -> input.placeholder = 'Filter';

The problem is that native input.placeholder is empty when isn't focused (angular-material >= 10).
![image](https://user-images.githubusercontent.com/7735329/140473129-465016b7-f2d8-4999-b6c3-1160ad4fb037.png)

**Why input has empty placeholder when input isn't focused?**
**I want input.placeholder has always with its own value.**
**I don't want to use floatLabel="always".**

### Reproduction

WORK
version <10 https://stackblitz.com/edit/angular-9-material-starter-3byooq

NOT WORK
version >=10 https://stackblitz.com/edit/angular-ivy-pfcpwr

### Expected Behavior

 Native Placeholder always has value.
![image](https://user-images.githubusercontent.com/7735329/140473519-c4dda562-8c5b-4bb4-8ddb-7ea04eee73cf.png)

### Actual Behavior

What behavior did you actually see?
Native placeholder has value only if input is focused
![image](https://user-images.githubusercontent.com/7735329/140473129-465016b7-f2d8-4999-b6c3-1160ad4fb037.png)

#### Environment
  "dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "^9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "core-js": "^3.6.4",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "^0.10.3"
  },

versus 

  "dependencies": {
    "@angular/animations": "^12.2.5",
    "@angular/cdk": "12.2.12",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/material": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
    "rxjs": "^7.3.0",
    "tslib": "^2.3.1",
    "zone.js": "^0.11.4"
  },

**Comment by crisbeto** [comment]
We're doing this for accessibility reasons and it's working as expected (see https://github.com/angular/components/pull/10466). The attribute needs to be cleared, because screen readers will read out the same text twice.
