### ISSUE TITLE
bug(mat-datepicker): IOS: Incorrect hover display after year selection

### ISSUE THREAD

**Issue by ydamato** [angular/components#23904]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

On IOS when a year is selected, the month cell underneath is highlighted with a focus state.

https://user-images.githubusercontent.com/15203580/140481702-da322755-2788-4de8-ae29-a418befcc501.mp4

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/datepicker/examples
2. Open a date picker and select a year

### Expected Behavior

Only the selected month should be highlighted.

### Actual Behavior

Selected month and month underneath selected year are highlighted with the same style.

### Environment

- Angular: 12.2.6
- CDK/Material: 13.0.0
- Browser(s): Safari
- Operating System: IOS

**Comment by SteveBidenko** [comment]
Just FYI: This issue started from Angular Material v.10.2.7
