### ISSUE TITLE
bug(Mat Form Field): Mat Label alignment incorrect when matPrefix is present. 

### ISSUE THREAD

**Issue by AtozEvo** [angular/components#23916]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `mat-label` and `matPrefix` in a `mat-form-field`, the `mat-label` is not correctly aligned based on MD's Interactive demo [example](https://material.io/components/text-fields). The label is moved the the right due to the space at the start of the form field being used by `mat-prefix`. 

### Example code
```
<mat-form-field >
	<mat-label>Test Label</mat-label>
	<div matPrefix><mat-icon>favorite</mat-icon></div>
	<input matInput placeholder="label" value="value" autocomplete="off" />
</mat-form-field>
```

### Reproduction

Steps to reproduce:
1. Create a `mat-form-field`
2. Add `mat-label` to the form field. 
3. Add `mat-prefix` to the form field. 
4. See the alignment run. 

_Optional_
5. Check MD site to see if it is intended design
6. Search and check the web for possible discussions on this issue. 
7. Fail to find discussions and feel confused. 

### (From MD site)

![image](https://user-images.githubusercontent.com/45632351/140700140-e41c3d74-9785-4959-bf2d-402717130219.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/45632351/140700038-0b533981-947b-4bc6-bc3a-8cb237495d75.png)

### Environment

- Angular: 12.2.11
- CDK/Material: 12.2.11
- Browser(s): Version 95.0.4638.69 (Official Build) (64-bit)
- Operating System Windows10

**Comment by crisbeto** [comment]
This is fixed in the MDC implementation of the form field.

**Comment by AtozEvo** [comment]
Hi,

What do i need to do to solve this on my project? 

How do i make use of MDC with `@angular/material`? Do i just need to update to v13?

**Comment by crisbeto** [comment]
You'd have to import `MatInputModule` and `MatFormFieldModule` from `@angular/material-experimental/mdc-input` and `@angular/material-experimental/mdc-form-field`. You'll also have to include the `mdc-input-theme` and `mdc-form-field-theme` mixins from `@angular/material-experimental` in your theme.

**Comment by AtozEvo** [comment]
Thanks for the quick response. I will read up more on this. But since it is under 'experimental', would it be wise to use it in a production app?

**Comment by crisbeto** [comment]
These components are going to become the default eventually (see https://github.com/angular/components/issues/23923) and they're fairly stable at the moment. You should keep in mind that since they're in experimental, they aren't covered by our breaking changes policy so we might introduce breaking API changes at any time.
