### ISSUE TITLE
state of mdc-Components

### ISSUE THREAD

**Issue by Kr0san89** [angular/components#23923]
### Documentation Feedback

Hello,

i would be curious if the Angular Components team could give some update on the state of the mdc integration. 

I would be interested if the current implementation will be replaced and in which time span this planned. Also if you could give some insights how much breaking changes we will encounter.

At starting angular material you had a table which component is already done and for the missing one, when it is planned. I wonder if something like that would make sense for mdc, to provide more insight how the progress is. I Did see you have a "Project" about it here in github, but i'm unsure how complete it is.

Thanks

### Affected documentation page

https://angular.io/guide/roadmap / https://material.angular.io/ / https://github.com/angular/components/tree/master/src/material-experimental

**Comment by jelbourn** [comment]
We're currently working towards finalizing our plan to move the MDC components into the stable `@angular/material` package (how `ng update` will work, deprecation timeline for the older components, etc.) We're shooting for v14 here, but (like any new feature) there's always a chance that it might end up slipping to a later release if something in our dependency stack ends up blocking. I'll also update the README when we have a more definite idea of whether we can commit to v14.
