### ISSUE TITLE
bug(mat-slider): Ticks are not visible after changing step size

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#23928]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Ticks are not visible after changing step size

Before changing step size -

![image](https://user-images.githubusercontent.com/34937515/140901593-e8039283-c75b-4dca-a89d-462ddbb15f5d.png)

After changing step size -

![image](https://user-images.githubusercontent.com/34937515/140901723-e0d89555-333e-4645-8490-46a459b4f43a.png)

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/slider/examples
2. Check Show ticks option
3. Change Tick interval to 25
3. Hover on the slider, You will be able to see Ticks
4. Change the step size to 25
5. Hover on the slider, Ticks are gone

### Expected Behavior

Even after changing the step, Ticks should be visible

### Actual Behavior

After changing the step, Ticks are not visible

### Environment

- Angular:  "^12.2.7",
- CDK/Material: "^12.2.7"
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Totati** [comment]
The points are calculated based on the `stepSize`. The `tikInterval` is basically "show a point at every {tikInterval} step". You set the `tikInterval` to 25 and you have your `step` at 25 and `max` at 100. You would have a point at value 25*25 = 625.

**Comment by hexiaoli999** [comment]
Can't swipe on your phone
