### ISSUE TITLE
docs-bug(Datepicker):  there is no warning about the need to import.

### ISSUE THREAD

**Issue by italomp** [angular/components#23927]
### Documentation Feedback

It would be interesting to warn that I need to import MatNativeDateModule to use MatDatepickerModule components.

Thank you.

### Affected documentation page

https://material.angular.io/components/datepicker/api

**Comment by crisbeto** [comment]
We have a runtime error if no date adapter is provided. Also the date adapter you pick depends on what object you're using to represent dates. There's more info in the docs: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings
