### ISSUE TITLE
bug(MatDialog): backdrop-filter assigned to overlay through MatDialogConfig not applied until page resize

### ISSUE THREAD

**Issue by Usurer** [angular/components#23937]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I create a CSS class with `backdrop-filter` rule and assign this class to `backdropClass` field of MatDialogConfig when executing `dialog.open`, the style effect is not applied, until I resize the window.

![BlurMatDialogReport](https://user-images.githubusercontent.com/915414/141156495-1955741c-68b6-4ef2-9a88-8506266f2b70.gif)

This seems to be a recently introduced behavior and I'm not sure whether this ticket should be here, or should I address the Chromium team - as the backdrop works ok on Chromium v93.0.4553.0 (Developer Build) but not on Chrome v95.0.4638.69 (Official Build)

### Reproduction

Example: https://stackblitz.com/edit/angular-kjugua

Steps to reproduce:
1. Open the docs https://material.angular.io/components/dialog/examples and open the first example (Dialog with header, scrollable content and actions) in Stackblitz
2. Add class to `styles.scss`:
```css
.blurred {
  backdrop-filter: blur(5px);
}
```
3. Set this class as a `backdropClass` for the dialog
```typescript
const dialogRef = this.dialog.open(DialogContentExampleDialog, {
    backdropClass: 'blurred',
});
```
4. Run the sample and open the dialog

### Expected Behavior

Content beneath the dialog background is blurred

### Actual Behavior

Content beneath the dialog background is not changed, until user resizes the window.

### Environment

- Angular: 13.0.0
- CDK/Material: 13.0.0
- Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- Windows

**Comment by crisbeto** [comment]
I think that this is a browser issue due to the `transition` that we have on the backdrop. I'm closing the issue, because we can't do much on our end, but you can fix it yourself by changing the class to this:

```
.blurred {
  backdrop-filter: blur(5px);
  transition: none;
}
```
