### ISSUE TITLE
feat(theming): Gradients, Static Background Images and Shaders for Themes

### ISSUE THREAD

**Issue by mkarg** [angular/components#23963]
### Feature Description

CSS allows to set not only a background color but also a background gradient or image. WebGL allows to even write shaders. The theming API unfortunately does not yet support either. It would be great if theming would not just cover colors, but also would allow to write Angular Themes which set a background image (like a rusty metal surface) or even set a background shader (like floating water). That would make Angular applications look much more modern and cool than just setting a color.

### Use Case

Cool applications need to be able to use cool themes.

**Comment by jelbourn** [comment]
While I agree that this would be cool, this isn't currently something we plan on tackling any time soon. This could change if the If Material Design spec moves more in this direction.

**Comment by mkarg** [comment]
> While I agree that this would be cool, this isn't currently something we plan on tackling any time soon. This could change if the If Material Design spec moves more in this direction.

I am very sad to hear that, as the currently limited theming possibilities are mortifying. It is hard to compete with other vendors using non-Angular Components based platforms, so for us, this is a **major** drawback of Angular Components.
