### ISSUE TITLE
bug(datepicker): Months in Estonian language are too long

### ISSUE THREAD

**Issue by llaz00** [angular/components#23981]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If language is set to Estonian ('et') the month names in datepicker are too long (in other languages like English they're cut of at 3 characters)
<img width="369" alt="image" src="https://user-images.githubusercontent.com/49528536/142384277-d0ec45bf-ace5-4e87-a45d-3efba3630e38.png">

### Reproduction

Stackblitz: https://stackblitz.com/edit/components-issue-mrozgp?file=src/app/example-component.ts

Steps to reproduce:
1. Set DateAdapter locale to Estonian ('et')
2. Open datepicker
3. Click in the month/year title
4. Select year
5. Months view should be displayed with too long names

### Expected Behavior

Months should be cut off at 3 characters as in other languages

### Actual Behavior

Month names are displayed enterely

### Environment

- Angular: 12.2.9
- CDK/Material: 12.2.9
- Browser(s): Chrome 95.0.4638.69 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS Monterey (12.0.1)

**Comment by jelbourn** [comment]
@llaz00 This looks like the behavior of the browser's `Intl` API:
```ts
var f = Intl.DateTimeFormat('et', {month: 'short'});
f.format(new Date('Sept 1, 2021'));

// returns 'september'
```

You have a couple options here:
* Use an alternate `DateAdapter` implementation that has different formatting for Estonian
* Add a custom `DateAdapter` and manually control the formatting
