### ISSUE TITLE
feat(MatDateRangePicker): Implement TouchUI

### ISSUE THREAD

**Issue by troncomputers** [angular/components#23988]
### Feature Description

``` html
<mat-date-range-picker touchUi #picker></mat-date-range-picker>
```
Now it's "normal" sized calendar but in center of the screen.

### Use Case

Bigger calendar for mobile devices with touch support.

**Comment by crisbeto** [comment]
The range picker inherits from the same base class as the datepicker so the touch UI should be there.

**Comment by troncomputers** [comment]
You're right. On small devices (phone) it looks small so I assumed that it is not working, but on bigger one (tablet) it's fine.
