### ISSUE TITLE
feat(map-marker): add setters

### ISSUE THREAD

**Issue by cfficaurzua** [angular/components#23995]
### Feature Description

The javascript library has setters:
- setAnimation
- setClickable
- setCursor
- setDraggable
- setIcon
- setLabel
- setMap
- setOpacity
- setOptions
- setPosition
- setShape
- setTitle
- setVisible
- setZIndex

But the MapMarker class has only getters.
Can we add them? or theres is a reason not to?

### Use Case

well basically I want to add a bounce animation when I click the marker
```
<map-marker #marker="mapMarker" *ngFor="let element of data"
		[position]="element.drop"
		(mapClick)="openInfoWindow(marker, infoWindow)"
		[options]="markerOptions(element)">
</map-marker>
```
```
  openInfoWindow(marker: MapMarker, infoWindow:MapInfoWindow) {
    marker.setAnimation(google.maps.Animation.BOUNCE)
    this.previousInfoWindow ? this.previousInfoWindow.close() : null 
    infoWindow.open(marker);
    this.previousInfoWindow = infoWindow
  }
```

**Comment by crisbeto** [comment]
All of these fields should be settable through the `options` input.
