### ISSUE TITLE
help(MatTableModule): table refresh: only refresh changed row(object)

### ISSUE THREAD

**Issue by kzhui125** [angular/components#23998]
### What are you trying to do?

```typescript
const ELEMENT_DATA: PeriodicElement[] = [
  {position: 1, name: 'Hydrogen', weight: 1.0079, symbol: 'H'},
  {position: 2, name: 'Helium', weight: 4.0026, symbol: 'He'},
  {position: 3, name: 'Lithium', weight: 6.941, symbol: 'Li'},
];

const ELEMENT_DATA2: PeriodicElement[] = [
  {position: 1, name: 'Hydrogen', weight: 1.0079, symbol: 'H'},
  {position: 2, name: 'Helium', weight: 4.0026, symbol: 'He'},
  {position: 3, name: 'Lithium', weight: 6.941, symbol: 'Li'},
];

/**
 * @title Binding event handlers and properties to the table rows.
 */
@Component({
  selector: 'table-row-binding-example',
  styleUrls: ['table-row-binding-example.css'],
  templateUrl: 'table-row-binding-example.html',
})
export class TableRowBindingExample {
  displayedColumns: string[] = ['position', 'name', 'weight', 'symbol'];
  dataSource = ELEMENT_DATA;
  clickedRows = new Set<PeriodicElement>();

  test(): void {
    this.dataSource = ELEMENT_DATA2;
  }
}
```

When test() is called, I find that all table rows dom are recreated.
Is there a way to let MatTableModule auto compare old array and new array (primary key id), only rerender changed rows.

Thanks,

### What troubleshooting steps have you tried?

run the code

### Reproduction

run the code

### Environment

code from https://material.angular.io/components/table/examples

**Comment by mrmokwa** [comment]
Perhaps you need to use trackBy. Taken from the [angular material site](https://material.angular.io/components/table/api#MatTable):

`@Input() trackBy: TrackByFunction<T>`

> Tracking function that will be used to check the differences in data changes. Used similarly to ngFor trackBy function. Optimize row operations by identifying a row based on its data relative to the function to know if a row should be added/removed/moved. Accepts a function that takes two parameters, index and item.

**Comment by kzhui125** [comment]
@mrmokwa thank you, I will have a try
