### ISSUE TITLE
mat-raised-button: @HostBinding('disabled') not working with Angular material 12

### ISSUE THREAD

**Issue by adelinor** [angular/components#24006]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

6.3.0

### Description

A material button in version 12 does not show as disabled when the attribute is set with a property annotated with `@HostBinding('disabled')` .

### Reproduction

Steps to reproduce:
1. The custom directive `myDirective` disables a button when the directive parameter contains an 'a'
      i.  In Angular version 6, the `HostBinding` decorator works as expected and disables/enables the button (standard button or Angular Material), see https://stackblitz.com/edit/angular-ivy-ptt2t4?file=src%2Fapp%2Fmy-directive.directive.ts
      ii. In Angular verstion 12, the `HostBinding` decorator only works with a standard button. Disabling/enabling does not seem to apply on the Angular Material button, see https://stackblitz.com/edit/angular-ivy-17ajyo
2. The standard button renders correctly as disabled but not the Angular material button

### Expected Behavior

The button should appear as disabled.

### Actual Behavior

Angular material button shows as enabled.

### Environment

- Angular: 12.2.13
- CDK/Material: 12.2.13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by adelinor** [comment]
Hi,

Looking at the [Angular material source code](https://github.com/angular/components/blob/master/src/material/button/button.ts), I found a solution to the host property binding issue raised in this ticket which works with Angular 12.

Instead of using the `HostBinding` decorator, the `host` property metadata declared as in line 70 of the [button.ts](https://github.com/angular/components/blob/master/src/material/button/button.ts) works as expected:

```ts
@Directive({
  selector: '[myDirective]',
  host: {
    '[attr.disabled]': 'disabled || null',
    '[class.mat-button-disabled]': 'disabled',
  },
})
```

This is illustrated in the following [snippet on stackblitz](https://stackblitz.com/edit/angular-ivy-3eh8uj?file=src%2Fapp%2Fmy-directive.directive.ts) showing the button being enabled/disabled.

**Comment by wagnermaciel** [comment]
This is working as expected. The mat-button does not use the underlying native button as its source of truth, so manually disabling the native button will trigger changes to the mat-button. The workaround you gave works because you are manually appending the `mat-button-disabled` class. You can accomplish the same thing with hostbindings like so:

```
  @HostBinding('disabled')
  @HostBinding('class.mat-button-disabled')
  disabled = true;
  ```

That being said, you should probably try using a ControlValueAccessor to accomplish this instead of host bindings, since that is the intended way of programmatically disabling the mat-button.

**Comment by adelinor** [comment]
In Angular 6, the disabled state of the mat-button was aligned with the one of the underlying native button. In that sense, there is a change not properly documented.

**Comment by wagnermaciel** [comment]
@crisbeto do you think it would be possible for us to reconcile this behavior to have the disabled state reflected on the actual component? I think @adelinor is correct here in that because we are exposing the native button, using the native button's api should be valid

**Comment by crisbeto** [comment]
We used to use the disabled state for styling, but it was changed on purpose in https://github.com/angular/components/pull/19406. It looks like it was done this way in order to allow focusable disabled buttons.

**Comment by wagnermaciel** [comment]
Ah, I see. In that case, this is working as expected, correct?

**Comment by crisbeto** [comment]
Yes, it's working as expected. @adelinor you could bind to `class.mat-button-disabled` instead.
