### ISSUE TITLE
feat(Horizontal Expansion Panel): Add Horizontal option to the Expansion Panel

### ISSUE THREAD

**Issue by RonanCodes** [angular/components#24001]
### Feature Description

Currently the Angular Material Expansion Panel expands vertically, but not horizonally:
https://material.angular.io/components/expansion/overview

### Use Case

I have a use case where a card needs to be able to be expanded horizontally.

This person has the same use case:
https://stackoverflow.com/questions/46360604/opening-angular-material-expansion-panel-vertically

**Comment by crisbeto** [comment]
As far as I can tell, this isn't in the Material Design spec so we likely won't support it.
