### ISSUE TITLE
bug(google-maps): Update google maps typings

### ISSUE THREAD

**Issue by uragun91** [angular/components#24009]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Please update google-maps typings from `@types/googlemaps` to `@types/google.maps` since [@types/googlemaps](https://www.npmjs.com/package/@types/googlemaps) is now deprecated. Currently creates an issue when you need to rely on `@types/google.maps` package:
![](https://i.imgur.com/RprvYe4.png)

### Reproduction

Steps to reproduce:
1. Make use of some package which needs @types/google.maps (e.g. "@googlemaps/js-api-loader": "~1.12.10")
2. Try to build the project

### Expected Behavior

Successful build

### Actual Behavior

Build fails with Duplicate identifier error

### Environment

- Angular: 11.2.13
- CDK/Material: 11.2.13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
We switched to the new types in version 13. See https://github.com/angular/components/pull/23350.
