### ISSUE TITLE
bug(Accessibility): @use '@angular/cdk' no longer works

### ISSUE THREAD

**Issue by bryantlikes** [angular/components#24002]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.12

### Description

The documentation for **Hiding elements in an accessible way** shows to `@use '@angular/cdk'` which no longer works. 

https://material.angular.io/cdk/a11y/overview#hiding-elements-in-an-accessible-way

Following the overlay setup works as expected. 

https://material.angular.io/cdk/overlay/overview#initial-setup

Note: Fixed this locally by changing my import to be:

@import '@angular/cdk/a11y-prebuilt.css'; 

### Reproduction

Steps to reproduce:
1. Add  `@use '@angular/cdk';` to the root scss file of an angular project
2. Build the project and it will error with no scss document found

### Expected Behavior

Should import the stylesheet

### Actual Behavior

Stylesheet doesn't get imported

### Environment

- Angular: 13.0.2
- CDK/Material: 13.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I just tried creating a new CLI project with version 13.0.2 and the following in `styles.scss` and it worked fine:

```
@use '@angular/cdk';

html, body { height: 100%; }
body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }

@include cdk.a11y-visually-hidden;
```

**Comment by bryantlikes** [comment]
For some reason I had `@use '~@angular/cdk'; which didn't work. Switching to just `@use '@angular/cdk'` without the tilde works so I will close this.
