### ISSUE TITLE
help(COMPONENT): shortMonthNams can not get to expected

### ISSUE THREAD

**Issue by CSi-CJ** [angular/components#24017]
### What are you trying to do?

In my functional requirements, the expected calendar month name is a normal English abbreviation, not all uppercase.
The following is my customized shortMonthName format and MatDateFormats
![image](https://user-images.githubusercontent.com/57539387/143543791-181f05f5-b550-4d82-b1f9-ff49d25940b2.png)
![image](https://user-images.githubusercontent.com/57539387/143543965-3be28870-d418-401f-af80-45338d3d781f.png)

but I got it unexpected:
![1637911743(1)](https://user-images.githubusercontent.com/57539387/143543175-1369acd5-6a46-4cbd-bd48-f896c7d3d484.png)

### What troubleshooting steps have you tried?

I tried to modify the MatDateFormats format, but still did not get the desired result
![image](https://user-images.githubusercontent.com/57539387/143544170-f767f82e-5ea3-4bd8-81b4-4fa62e0942e6.png)
![image](https://user-images.githubusercontent.com/57539387/143544364-3bdeba18-38bb-4be8-884d-756a0ccaf743.png)

### Reproduction

Steps to reproduce:
1. 
2. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by 70u9H13** [comment]
Look's like that for now we can't get rid of the uppercase because it's literally hardcoded in the `MatYearView` component: `return new MatCalendarCell(
      month,
      monthName.toLocaleUpperCase(),
      ariaLabel,
      this._shouldEnableMonth(month),
      cellClasses,
);`
Possible hacky solution could be to change those months directly in `MatYearView`. Something like that: 
`change(view: MatCalendarView) {
    if (view === 'year') {
      this.calendar.yearView._months = this.calendar.yearView._months.map((row: MatCalendarCell[]) => {
        row.forEach(cell => {
          cell.displayValue = 'test';
        })
        return row;
      })
      this.calendar.yearView._changeDetectorRef.markForCheck();
    }
  }`

**Comment by CSi-CJ** [comment]
@70u9H13 thanks! So it looks like a bug, I can’t customize the monthName views I want
