### ISSUE TITLE
help(map-directions-renderer): How can I modify the PolylinesOptions of Angular Components map-Directions-renderer?

### ISSUE THREAD

**Issue by yigsvnsla** [angular/components#24016]
### What are you trying to do?

hi I'm trying to edit the PolylinesOptions of the `<map-directions-renderer>`  component and I can't get results

I need to generate multiple renderers to generate different paths independent of each other, with these PolylinesOptios is to generate a custom line to identify the routes from each other. [( Live Example )](http://jsfiddle.net/p5gmyd0z/5/)

>**_Expected result_**
![image](https://user-images.githubusercontent.com/55502763/143517531-5fda5ef7-6646-4ec1-9ddd-d2256a69ba78.png)

>**_Obtained result_**
![image](https://user-images.githubusercontent.com/55502763/143517458-efca20de-f801-47f0-b5de-195d5fe19a52.png)

that's why all renderers are bound to the same variable

```typescript
@ViewChildren('directionsRender') directionsRenders : QueryList<ElementRef<google.maps.DirectionsRenderer> >;
```
```typescript
  this.directionsRenderOption = {
    draggable:false,
    suppressInfoWindows:true,
    markerOptions:{
      draggable: false,
      clickable:false,
    };,
    polylineOptions:{
      strokeColor: '#9966ff',
      strokeOpacity: 0,
      icons: [{
        icon: {
          path: google.maps.SymbolPath.CIRCLE,
          fillOpacity: 1,
          scale: 3
        },
      offset: '0',
      repeat: '1px'
      }],
    }
  }`
```
```html
<google-map
        #map 
        height="100%" 
        width="null" 
        [options]="this.mapOptions"
        (tilesloaded)="tilesLoaded()"
        *ngIf="this.itemList.length != 0"
    >
        <map-directions-renderer 
            #directionsRender 
            *ngFor="let directionResult of directionsResults"
            [options]="directionsRenderOption" 
            [directions]="directionResult" 
        >
        </map-directions-renderer>
    </google-map>
```

### What troubleshooting steps have you tried?

I already tried to insert the options through a QueryList from a @ViewChildren and all the nativeElements return undefined in their methods but if they return the ElementRef from the Dom

it only happens with the PolylineOption, since if I modify for example the options of the markers if it applies these properties, Example: Modify the MarkerOptions of the rendering options to draggable, if you apply the changes

> **_Results ( Marker A )_**
![image](https://user-images.githubusercontent.com/55502763/143518193-e4f69ad8-9c19-4042-b4fc-356a4192e2ed.png)

### Reproduction

Steps to reproduce:
1. insert PolylineOptions in this component
2. rendered component

### Environment

- Angular: 12.1.4
- CDK/Material: @angular/google-maps
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubunt): All

**Comment by crisbeto** [comment]
If you're only changing the `polylineOptions` property in `directionsRenderOption`, the problem might be that change detection isn't picking it up and notifying the directions renderer, because the reference to `directionsRenderOption` doesn't change. You can try cloning the object when you change the options: `directionsRenderOption = {... directionsRenderOption, polylineOptions: newPolylineOptions}`.
