### ISSUE TITLE
How to override Angular material styling with using ::ng-deep

### ISSUE THREAD

**Issue by JmattaPF** [angular/components#24043]
### Feature Description

I need to update Angular material dropdown and textbox styling but not able to do it without using ::ng-deep but it is going to be deprecated soon. So what are the other ways to do it?

**Comment by chenc041** [comment]
you can set @Component option encapsulation to  ViewEncapsulation.None
I try it is effect effect

**Comment by Rajdeep97** [comment]
@chenc041 @JmattaPF Setting ViewEncapsulation to None, leads to the styles being promoted to global. This can make styles applied in one component affect other component too.

One way I mitigate this is by, adding a class to the component, let's say 'style-comp-a' and covering all styles of that component under this class.

**Comment by crisbeto** [comment]
The answer from @Rajdeep97 is correct. We disable view encapsulation on all of our components so you should be able to target the elements directly, at your own risk.

**Comment by JmattaPF** [comment]
Tried but didn't work. Only working option I found is using ::ng-deep but it is going to deprecate soon. So looking for some other option which can be used without the fear or deprecation.
