### ISSUE TITLE
input type="file"

### ISSUE THREAD

**Issue by vardhan1122** [angular/components#24044]
### Feature Description

Hi Good Morning.,
I am reading all angular-material document, not available in matInput type="file",please add this new feature as soon as possible.

### Use Case

Profile Image Upload

**Comment by Rajdeep97** [comment]
@vardhan1122, input=file is present as a default attribute of input in any browser. It is suggested that you style the default attribute as per your own needs.

**Comment by crisbeto** [comment]
We intentionally don't support the `file` input, because the way it's implemented depends on how your backend is set up.
