### ISSUE TITLE
bug(mat-slider): Experimental mat-slider throws Cannot read properties of undefined (reading '_hostElement')

### ISSUE THREAD

**Issue by adrian-heath** [angular/components#24057]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When adding the most basic experimental mat-slider to a page it throws the error

TypeError: Cannot read properties of undefined (reading '_hostElement')

when initializing the page.  This does not happen with other experimental controls or the normal mat-slider.  The page does not use a form.

### Reproduction

Steps to reproduce:
1.  Create a page with routing (in my case it is lazy-loaded but I don't think this matters)
2. craete a <mat-toolbar> containing a <mat-slider>  
3. Navigate to the page and an alert is show with the above message

### Expected Behavior

the experimental mat-slider works as expected

### Actual Behavior

Error thrown and the slider renders as a solid bar

### Environment

- Angular: 13.0.2 (also 12.x)
- CDK/Material: Experimental 13.0.2
- Browser(s): Chrome 96
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by adrian-heath** [comment]
This is the console output for the error

![image](https://user-images.githubusercontent.com/13252125/144761741-81eaad67-6cbc-4d20-859c-5a40c1e16b7b.png)

**Comment by crisbeto** [comment]
Can you post what your component's template looks like? We have tests for the slider that don't throw this error.

**Comment by crisbeto** [comment]
Just a guess based on the stack trace: you're probably missing an `input` inside the slider. The public API of the experimental slider is slightly different than the current one. You can see some usages here: https://github.com/angular/components/blob/master/src/dev-app/mdc-slider/mdc-slider-demo.html
