### ISSUE TITLE
docs-bug(density): Why doesn't "applying density" describe how to apply density.

### ISSUE THREAD

**Issue by grapevinegizmos** [angular/components#24056]
### Documentation Feedback

Very frustrating that nowhere on the page titled "Applying Density", here [https://material.io/design/layout/applying-density.html](url), does it actually explain how to apply density to a particular control on a form or view.

There's a lot of info on **why** and **when** you might adjust density, and what it will look like when you do, but not a single code example on how to actually "apply density" to a control in a component template and support it in a module.   Why are there no stackblitz links demonstrating how to use the feature?

The one example I did find elsewhere, was pretty much incomprehensible to me and would itself would require a lot of studying just to figure out what's going on.  The example is not constructed in the usual way, with components, templates etc., but instead builds the entire example in .ts files (no html or css templates) which makes it just really opaque to figure out how to actually use it in a conventional angular application.   (Also you can't even get to this example on this page -- you have to click through to the install page on https://material.io/develop/web/supporting/density and for some reason the example is hosted on something called "Glitch" rather than on Stackblitz, like _every other example code section in material.io_

Can you do better here?  I was really lookingf forward to this feature, but its going to take me (unnecessary) hours of experimentation to guess at how to use it.

### Affected documentation page

https://material.io/design/layout/applying-density.html

**Comment by crisbeto** [comment]
It's worth noting that the material.io page isn't maintained in this repo. We maintain only material.angular.io.

**Comment by grapevinegizmos** [comment]
Ah, right.  Didn't realize that.  Is angular material planning on supporting material density? Is it supported now?

**Comment by Rajdeep97** [comment]
@grapevinegizmos As far as I know, yes they do, and recently they even added support for it in code. However, the documentation needs to be updated on how to apply them.

**Comment by crisbeto** [comment]
We support density primarily in the components under `material-experimental` and a handful of the ones in `material`. We'll have proper documentation once the experimental components have been moved into stable. You can find an example of it's used here: https://github.com/angular/components/blob/master/src/dev-app/theme.scss
