### ISSUE TITLE
bug(COMPONENT): Angular material component harness expansion panel description not working

### ISSUE THREAD

**Issue by thu9999** [angular/components#24058]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

MatExpansionPanelHarness getDescription return a Promise<''> instead of Promise<string|null>

### Reproduction

Steps to reproduce:
1. Testing component template having mat-panel-description inside a mat-expansion-panel

### Expected Behavior

MatExpansionPanelHarness.getDescription() should return a Promise<string|null> instead of Promise<''>

### Actual Behavior

MatExpansionPanelHarness.getDescription() returns Promise<''>

### Environment

- Angular: 11.2.4
- CDK/Material: 11.2.3
- Browser(s): NA
- Operating System (e.g. Windows, macOS, Ubuntu): windows 11

**Comment by crisbeto** [comment]
The method returns `string | null` already. See https://github.com/angular/components/blob/master/src/material/expansion/testing/expansion-harness.ts#L87.
