### ISSUE TITLE
docs-bug(COMPONENT): Need more info on getSvgIconFromURL 

### ISSUE THREAD

**Issue by adityakmehta** [angular/components#24060]
### Documentation Feedback

Looking for an Implementation example of "**getSvgIconFromURL**" in **mat-icon**. It would be great if we can get a detailed documentation on using this method to implement caching. There is no sample implementation of this functionality whatsoever.

Thanks

### Affected documentation page

https://v9.material.angular.io/components/icon/api

**Comment by crisbeto** [comment]
The method is used like all other methods that return observables (e.g. the ones in `HttpClient`). Also caching is built into it already. Here's an example of how it can be used: https://github.com/angular/components/blob/master/src/material/icon/icon.spec.ts#L257
