### ISSUE TITLE
help(core): Is there a way to import private styles in core?

### ISSUE THREAD

**Issue by nzbin** [angular/components#24087]
### What are you trying to do?

I have written a [material extensions library](https://github.com/ng-matero/extensions), so I need the import some privte styles such as `theming.private-legacy-get-theme` `theming.private-check-duplicate-theme-styles`. But I can't import this styles in version 13, I want to know how to solve this issue.

### What troubleshooting steps have you tried?

```scss
@use '@angular/material/core/theming/theming'
```

### Reproduction

Steps to reproduce:
1.
2.

### Environment

- Angular: 13
- CDK/Material: 13
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
There isn't. The whole point of private APIs is that they shouldn't be imported.
