### ISSUE TITLE
Bidi Bug(Material components): Angular material components use wrong css rules for bidi

### ISSUE THREAD

**Issue by rasoulMrz** [angular/components#24100]
### Description

Some angular material components do not work as expected in complex bidi situations where we have an RTL application with some LTR pages.
suppose you have a simple HTML as follows:
```
<div dir="rtl">
     <div dir="ltr">
                 // some angular material components here (e.g. mat-form-field with outline appearance)
     </div>
</div>
```
The outcome would be a mess like this:
![image](https://user-images.githubusercontent.com/28677424/145972832-345fc3cd-19d0-4027-a295-a8bcddf08663.png)

The problem comes from some CSS rules like this one:
```
[dir=rtl] .mat-form-field {
    text-align: right;
}
```

It is obvious that this rule applies to all components with an RTL ancestor!! even if the actual effective dir is LTR like the example above.

One solution here could be using a directive like this one:
```
export class BidiClassDirective
{

    constructor(readonly dir: Directionality)
    {
    }

    @HostBinding("class.ltr")
    get isLtr(): boolean
    {
        return this.dir.value === 'ltr';
    }

    @HostBinding("class.rtl")
    get isRtl(): boolean
    {
        return this.dir.value === 'rtl';
    }
}
```
In any component that has some direction-sensitive CSS, you have to use this directive to get the actual direction value.
For example inside the mat-form-field component:

```
<div class="mat-form-field-wrapper" matBidiClass>
          <div class="mat-form-field">
               //..................
          </div>
<div>
```
The CSS would be something like:
```
mat-form-field-wrapper.rtl >  .mat-form-field {
    text-align: right;
}
```

The proposed approach makes it a bit harder to implement the mat components but the result would be solid in any bidi situation.

### Reproduction

Steps to reproduce:
suppose you have a simple HTML as follows:
```
<div dir="rtl">
     <div dir="ltr">
                 // some angular material components here (e.g. mat-form-field with outline appearance)
     </div>
</div>
```

### Expected Behavior

The components should appear properly with respect to the actual effective dir! Like this:
![image](https://user-images.githubusercontent.com/28677424/145974910-72691a13-5ad5-4e60-8a8a-d441cdc97444.png)

### Actual Behavior

But they currently appear like this:
![image](https://user-images.githubusercontent.com/28677424/145972832-345fc3cd-19d0-4027-a295-a8bcddf08663.png)

### Environment

- Angular:  12.2.7
- CDK/Material: 12.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by rasoulMrz** [comment]
Until now i have seen this issue in the form field and the paginator

**Comment by crisbeto** [comment]
We talked through this in our team meeting and decided not to support it for now, because it'll require refactors in most of our components in order to handle something that's somewhat of an edge case. Furthermore, even if we did refactor all our CSS, this will break again when we switch to the MDC component CSS in the near future.
