### ISSUE TITLE
bug(autocomplete): Highlight the typed text in autocomplete in xCode iPhone simulator safari

### ISSUE THREAD

**Issue by NeliaRudyk** [angular/components#24101]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Highlight the typed text in autocomplete in xCode iPhone simulator iPhone 13 iOS 15.2 safari.

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/autocomplete/examples using xCode simulator iPhone 13 iOS 15.2 safari browser.
2. type text in first example.

### Expected Behavior

Expected Results:
Typed text should not be highlighted

### Actual Behavior

Actual Results:
Typed text are being highlighted

### Environment

- Angular: 12.2.13
- CDK/Material: ^12.2.0
- Browser(s): xCode simulator iPhone 13 iOS 15.2 safari.
- Operating System - macOS

**Comment by crisbeto** [comment]
Are you referring to this text highlighting when there's a typo in the text?

![image](https://user-images.githubusercontent.com/4450522/146019036-e5ec23ca-a88f-4f91-935a-2aa74ff4eefa.png)

**Comment by NeliaRudyk** [comment]
yes

**Comment by crisbeto** [comment]
I'm not sure if we can do much about it, because this happens at the OS level. I can see the `spellcheck` HTML attribute potentially affecting it https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck.

**Comment by crisbeto** [comment]
Closing this issue since we can't do much to solve it on our end.
