### ISSUE TITLE
bug(formfield): remove ViewEngine workarounds in _control getter

### ISSUE THREAD

**Issue by manuelmeister** [angular/components#24104]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

There is still a workarounds for the view engine present.

https://github.com/angular/components/blob/master/src/material/form-field/form-field.ts#L247-L257

### Reproduction

https://github.com/angular/components/blob/master/src/material/form-field/form-field.ts#L247-L257

### Expected Behavior

Form field is easier to maintain

### Actual Behavior

Unused code

### Environment

- Angular: 13.1.0
- CDK/Material: 13.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
I took a quick stab at this and it ended up causing a bunch of "Changed after checked" errors.

**Comment by manuelmeister** [comment]
Okay, I'll close this then.
