### ISSUE TITLE
MatDatepickerInput min and max should work during runtime

### ISSUE THREAD

**Issue by zijianhuang** [angular/components#24103]
### Feature Description

Currently, the min and max properties of MatDatepickerInput are only working when being assigned as Input parameters during the initialization of the component. However, if I alter the parent variable assigned to the max/min input parameter, nothing changes. And also, if I use @ViewChild to reference to the MatDatepickerInput , and assign a new value to the max/min property of the component, nothing changes.

Feature Request:
Changing the max/min property during runtime should reflect the constraints in the calendar popup.

### Use Case

For example, I have 2 date input side by side:
Admission Date and Discharge Date.

The business rule is that, Discharge Date should not be earlier than Admission Date. That is, technically, after the user inputs Admission Date, the min property of Discharge Date should be set to the value of Admission Date, so the user won't be able to select an invalid Discharge Date.

**Comment by zijianhuang** [comment]
I had also tried the dateFilter property of MatDatepickerInput , that is, assign a new filter function to dateFilter:
```js
this.datePickerInput.dateFilter = (d: Date) => d >= min;
```

Apparently this Input property is working only during the init of the component. Hopefully this property also responds to runtime change of the assigned call back function.

**Comment by zijianhuang** [comment]
I realized out, the Input property works in some sort of subscription model. So I need to setup a parent variable assigned to the Input property, and change the value of the initially assigned variable. Then dynamically changing max/min works.

If this is intended way of working with only subscription model, not new assigned value, @Mateiral team you may delete this require.

**Comment by crisbeto** [comment]
The last comment is correct, you should be changing these through the `@Input`, not directly in the setter since that won't trigger change detection in order to update the view.
