### ISSUE TITLE
bug(Datepicker): Some dates are not converted correctly

### ISSUE THREAD

**Issue by c2ofh** [angular/components#24111]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

There are datums that do not work if you enter them by hand.
If you enter [here](https://material.angular.io/components/datepicker/examples#datepicker-api) (Datepicker action buttons -> Choose a date)

The date "11.11.1950", it works. It automatically becomes 11/11/1950, 
but if you enter "25.08.1950", for example, it doesn't work. It is still 25.08.1950 

We get the class "ng-invalid", although the date is correct. If you select the date with the date picker, it works. 

![image](https://user-images.githubusercontent.com/10913793/146288357-a62ec388-8cda-40df-80ce-a0200148feb7.png)
![image](https://user-images.githubusercontent.com/10913793/146288420-4690a0d2-d370-4b9b-a6a4-00397a3cd1c6.png)

```ts
this.minDate = new Date('1870-01-01');
this.maxDate = new Date('2021-12-16');
this.startView = 'multi-year'

//@inputs
this.required = true
this.disabled = false
this.key = "date_of_birth"
this.model = data.primaryGuest
this.errorLabel = "text..."
```

HTML
```html
<input matInput type="text"
       [matDatepicker]="id"
       [max]="maxDate"
       [min]="minDate"
       [name]="key + '_' + name"
       [value]="value"
       [(ngModel)]="model[key]"
       [disabled]="disabled"
       [required]="required">
<mat-datepicker-toggle matSuffix [for]="id"></mat-datepicker-toggle>
<mat-datepicker [startView]="startView" #id></mat-datepicker>
<label translate class="error">{{errorLabel}}</label>
```

### Reproduction

Steps to reproduce:
1. Enter 25.08.1950 by hand
2. The date is not converted correctly.
3. Enter 11.11.1950 by hand
4. The date is converted correctly.

### Expected Behavior

25.08.1950 -> 25/08/1950

### Actual Behavior

25.08.1950 -> 25.08.1950

### Environment

- Angular: 10.2.7
- CDK/Material: 10.2.7
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
This is covered in the datepicker docs: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

The tl;dr is that by default we parse using the built-in JavaScript `Date` type which can break down in some locales. We provide ways to customize it based on your needs.
