### ISSUE TITLE
bug(COMPONENT): 'get' and 'set' accessor must have the same type 

### ISSUE THREAD

**Issue by almas77abolfazl** [angular/components#24112]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11.2.13 . I am using from this version

### Description

When I'm using DropDown of PrimeNg. I needed to install the Angular CDK. 
 after installation I see this error in node_modules => CDK : **'get' and 'set' accessor must have the same type**  
I realized And noticed that get and sets do not follow the same type.
So I used the same version as before, 11.2.13

### Reproduction

Steps to reproduce:
1. 
2. 

### Expected Behavior

not get the error in gets and sets

### Actual Behavior

**'get' and 'set' accessor must have the same type**  

A get in one place is a number and in another place NumberInput

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You likely need to update your TypeScript version to 4.3 or above.

**Comment by glv1at118** [comment]
> You likely need to update your TypeScript version to 4.3 or above.

I am having the same issue. Tried updating the typescript version to latest (4.5.4) but not working. There's actually no version 4.3 in typescript but version 4.3.5. But this also not work. Error message from compiler saying typescript version must be between 4.2.3 and 4.3. 

This issue needs a fix.

**Comment by crisbeto** [comment]
It sounds like your version of Angular is too old as well. In general, the major versions of `core`, `cdk` and `material` should be the same.
