### ISSUE TITLE
How to override Angular material styling without using ::ng-deep

### ISSUE THREAD

**Issue by JmattaPF** [angular/components#24113]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

How to override Angular material styling without using ::ng-deep because it is going to deprecate soon.

### Reproduction

Steps to reproduce:
1. 
2. 

### Expected Behavior

Looking for an option that can be used without the fear of deprecation.

### Actual Behavior

Looking for an option that can be used without the fear of deprecation.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The specificity on our styles is generally pretty low so you can either do your overrides in the global `styles.css` or in your component styles. Note that you might have to set `encapsulation: ViewEncapsulation.None` on your component in order for the styles to apply.
