### ISSUE TITLE
feat(snack-bar): inject/override custom animation for MatSnackBar

### ISSUE THREAD

**Issue by Nikita-schetko** [angular/components#24127]
### Feature Description

Hi guys! 
Is it possible to override standard animation located [here](https://github.com/angular/components/blob/master/src/material/snack-bar/snack-bar-animations.ts) with custom one? 

### Use Case

I would like to tweak animation little bit and make it more look like spotify's one:

![](https://media0.giphy.com/media/e09OgqaZO3DtRrH9JL/giphy.gif?cid=790b76116bd3f5b5cede0c885ad20104dc29d22f28ece0da&rid=giphy.gif&ct=g)

**Comment by crisbeto** [comment]
This isn't possible at the moment and it isn't likely to be added.
