### ISSUE TITLE
bug(COMPONENT): Horizontal List Orientation under an RTL element does not work properly

### ISSUE THREAD

**Issue by kianooshsanatkar** [angular/components#24134]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I add `direction:rtl;` style to HTML (or any parent element) drop behavior does not work properly, it moves the item but in the wrong index.

---

I use a simple trick to handled it. But still, I thought it might need to be reported. And maybe we can use a simple way to handle the problem.

In my case I just change the `drop` function like this:

```
drop(event: CdkDragDrop<string[]>): void {
  let totalLists = this.myLists.length - 1;
  let previousIndex = totalLists - event.previousIndex;
  let currentIndex = totalLists - event.currentIndex;
  moveItemInArray(this.myLists, previousIndex, currentIndex);
}
```

I guess it must be a bit complex to find if an oriented list is truly right to left or left to right, but a very simple way is to use a flag for reverse calculation.

### Reproduction

Steps to reproduce:

1. For demonstration we can use an example by the documentation.
[material.angular.io/#horizontal-sorting](https://material.angular.io/cdk/drag-drop/overview#cdk-drag-drop-horizontal-sorting)
[stackbliz](https://stackblitz.com/run?file=src/app/cdk-drag-drop-horizontal-sorting-example.ts)
2. Just add RTL direction to html or body in style.css
`body {
  direction: rtl;
}`
 

### Expected Behavior

Drop to the correct Index

### Actual Behavior

The items are dropped in reverse order.

### Environment

- Angular: 12.1.4
- CDK/Material: 12.1.4
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We don't support setting a `direction` through CSS, because there's no efficient way for us to detect it in JS. You should set the direction in your markup using the `dir` attribute.

**Comment by kianooshsanatkar** [comment]
Thanks @crisbeto 🙏
