### ISSUE TITLE
MatButtonModule: mat-raised-button not working in child component within a module

### ISSUE THREAD

**Issue by bhadresh-dahanuwala** [angular/components#24144]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Issue:

mat-raised-button color="warn" not working in child components of a module

This works fine in app-component.html but the same does not work in other component which I have. 

There is no compilation error neither in "ng serve" nor when I inspect in chrome.

### Directory Structure

<img width="299" alt="DirectoryStructure" src="https://user-images.githubusercontent.com/38015612/147722959-322fae8e-5c69-454b-893f-1f05236463fe.png">

### user.module.ts

<img width="912" alt="user module ts" src="https://user-images.githubusercontent.com/38015612/147723150-350d59aa-78d3-4aa8-a5c9-ca2d7fca32a8.png">

### user-login.component.html

<img width="851" alt="user-login component html" src="https://user-images.githubusercontent.com/38015612/147723352-b7eb8ffb-d617-4c8b-a291-62b00b21c80d.png">

### app.module.ts

<img width="819" alt="app module ts" src="https://user-images.githubusercontent.com/38015612/147723443-52c1bb32-6952-4768-bfd4-d0f1c80489f3.png">

### app.component.html

<img width="857" alt="app component html" src="https://user-images.githubusercontent.com/38015612/147723479-3f359c88-1c88-4033-856b-e9cf66a169de.png">

### Output on webpage

<img width="1079" alt="webpage" src="https://user-images.githubusercontent.com/38015612/147723531-91e7173f-181b-4356-a63c-1f895fbc486b.png">

### Note

The first button with the correct style is coming from app.component.html and the second one where the style is not getting applied is coming from user-login.component.html

### Reproduction

Steps to reproduce:

Use the attached directory structure as a reference

1. Add import { MatButtonModule } from '@angular/material/button'; to the app component
2. Add the same to some other component within a module (in a separate directory)
3. Add button to both the html files

### Expected Behavior

Both the buttons should use the style and be shown in Red

### Actual Behavior

The button in the app.component.html is applying the style and showing Red as expected

The button in user-login.component.html is not applying the style

### Environment

OS: MacOS 12.1
npm: 8.1.2
ng --version
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4

Browser: Chrome and Safari

**Comment by crisbeto** [comment]
Closing since this is likely an issue on your end. The button module isn't doing anything special that would prevent it from executing in a child module. You can try adding the `MatButtonModule` to the `exports` field of your module.
