### ISSUE TITLE
help(material-experimental/mdc-button): Why `MatFabAnchor` component using `MAT_BUTTON_INPUTS`?

### ISSUE THREAD

**Issue by enten** [angular/components#24145]
### What are you trying to do?

I'm wondering why `MatFabAnchor` component using `MAT_BUTTON_INPUTS` as component's inputs? Would that be a mistake?

We can see that `MatMiniFabAnchor` component using `MAT_ANCHOR_INPUTS` as component's inputs (instead of `MAT_BUTTON_INPUTS`).

```ts
@Component({
  selector: `a[mat-fab]`,
  templateUrl: 'button.html',
  styleUrls: ['fab.css'],
  inputs: [...MAT_BUTTON_INPUTS, 'extended'],
  host: {
    ...MAT_ANCHOR_HOST,
    '[class.mdc-fab--extended]': 'extended',
    '[class.mat-mdc-extended-fab]': 'extended',
  },
  exportAs: 'matButton, matAnchor',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MatFabAnchor extends MatAnchor {
  // ...
}

@Component({
  selector: `a[mat-mini-fab]`,
  templateUrl: 'button.html',
  styleUrls: ['fab.css'],
  inputs: MAT_ANCHOR_INPUTS,
  host: MAT_ANCHOR_HOST,
  exportAs: 'matButton, matAnchor',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MatMiniFabAnchor extends MatAnchor {
  // ...
}
```

### What troubleshooting steps have you tried?

NA

### Reproduction

Steps to reproduce:
1. See source code [material-experimental/mdc-button/fab.ts#L145](https://github.com/angular/components/blob/24180d1/src/material-experimental/mdc-button/fab.ts#L145)

### Environment

- Angular: All
- CDK/Material: material-experimental 24180d1
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by andrewseguin** [comment]
That does seem incorrect, thanks for pointing this out
