### ISSUE TITLE
bug(mat-icon-button,mat-fab,mat-raised-button,mat-flat-button): Hover effect is missing

### ISSUE THREAD

**Issue by amakhrov** [angular/components#24157]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This is largely a duplicate of https://github.com/angular/components/issues/3946
The resolution in the original issue was "matches the spec".

Well, there is no spec for icon button per say. But the toggle button in the current spec (v2) clearly has the hover state: https://material.io/components/buttons#toggle-button
![Screen Shot 2022-01-03 at 2 26 21 PM](https://user-images.githubusercontent.com/1004015/147987123-26e5ede8-1bf5-4cdd-b98d-24171182a3f2.png)

For FAB, the spec doesn't say this explicitly, but the demo shows the change of elevation when hovered (https://material.io/components/buttons-floating-action-button#usage). The v3 spec explicitly calls out the elevation change, as well as background opacity (https://m3.material.io/components/floating-action-button/specs)
Raised and flat button - similar to FAB.

### Reproduction

E.g. demos in https://material.angular.io/components/button/examples

### Expected Behavior

Hover effect should exist for all button types

### Actual Behavior

Hover effect is missing

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by mrmokwa** [comment]
I add mat-button directive together with mat-icon-button to my buttons to achieve this behavior.

Exemple
```
<button mat-icon-button mat-button routerLink="new" matTooltip="Add">
   <mat-icon>add</mat-icon>
</button>
```

**Comment by andrewseguin** [comment]
Looks like the hover effect has been placed back into the spec and is present in the MDC button version. We'll likely not be able to prioritize porting the styles back, but will leave this open to track the issue

**Comment by amysorto** [comment]
All the new MDC based button components have a hover effect and will be available in v15 soon. Closing this issue.
