### ISSUE TITLE
bug(mat-tabs): animationDuration="0ms" no longer works

### ISSUE THREAD

**Issue by gpaimla** [angular/components#24161]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Previously we could set animationDuration="0ms" to disable mat-tab animation
https://github.com/angular/components/issues/13428
this no longer works.

### Reproduction

Steps to reproduce:
1.  go to https://material.angular.io/components/tabs/examples#tab-group-animations 
2.  open in stackblitz
3.  changing tabs still uses animation

### Expected Behavior

using animationDuration="0ms" should disable the animation

### Actual Behavior

default animation duration

### Environment

- Angular: 13
- CDK/Material: 13
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): win32 x64

**Comment by crisbeto** [comment]
It works for me both in the docs site and when I open it in Stackblitz. It also worked when I tried it against the code in master. Can you post when your markup looks like?

**Comment by gpaimla** [comment]
Okay, I checked it again with a fresh mind and indeed it works.
The docs site has no animations for the mat-ink-bar so it made me think that animationDuration="0ms" would behave the same way but it doesn't.
As for a fix, I changed the mat-ink-bar CSS transition duration to 0ms
