### ISSUE TITLE
bug(migrate): nx migrate 13.2.4 fails everytime

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#24163]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

nx migrate 13.2.4 fails everytime.

### Reproduction

Steps to reproduce:
1. Create work space using npx create-nx-workspace@12.10.0 --cli="angular"
2. Migrate workspace using nx migrate 13.2.4

### Expected Behavior

Migration should complete without any error

### Actual Behavior

Migration is failing with error.

Complete log - 

`
PS C:\Projects\projects\workspace\test-ws1-r55> nx migrate 13.2.4
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@13.2.4
Fetching @nrwl/angular@13.2.4
Fetching @nrwl/cli@13.2.4
Fetching @nrwl/cypress@13.2.4
Fetching @nrwl/eslint-plugin-nx@13.2.4
Fetching @nrwl/jest@13.2.4
Fetching @nrwl/linter@13.2.4
Fetching @nrwl/tao@13.2.4
Fetching @angular/cli@~13.0.0
Fetching @angular-devkit/build-angular@~13.0.0
Fetching @angular/core@^13.0.0
Fetching @angular/common@^13.0.0
Fetching @angular/forms@^13.0.0
Fetching @angular/compiler@^13.0.0
Fetching @angular/compiler-cli@^13.0.0
Fetching @angular/platform-browser@^13.0.0
Fetching @angular/platform-browser-dynamic@^13.0.0
Fetching @angular/router@^13.0.0
Fetching @angular/language-service@^13.0.0
Fetching @angular/animations@^13.0.0
Fetching @angular/material@^13.0.0
Fetching @angular/cdk@^13.0.0
Fetching zone.js@~0.11.4
Fetching typescript@~4.4.3
Fetching @angular-eslint/eslint-plugin@~12.6.0
Fetching @angular-eslint/eslint-plugin-template@~12.6.0
Fetching @angular-eslint/template-parser@~12.6.0
Fetching jest-preset-angular@11.0.0

 ERROR  The migrate command failed.

Command failed: npm install @angular-devkit/build-angular@~13.0.0
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.13.12: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.13.12: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.13.12: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.13.12: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.13.12: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.13.12: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.13.12: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.13.12: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.13.12: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-darwin-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.13.12: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.13.12: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.13.12: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.13.12: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.13.12: wanted {"os":"sunos","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.13.12: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.13.12 (node_modules\@angular-devkit\build-angular\node_modules\esbuild\node_modules\esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.13.12: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nice-napi@^1.0.2 (node_modules\piscina\node_modules\nice-napi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for nice-napi@1.0.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\E5648603\AppData\Local\Temp\3\tmp-24156-q2Nn6tXkAo04\package.json'
npm WARN @angular-devkit/build-angular@13.0.4 requires a peer of @angular/compiler-cli@^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@13.0.4 requires a peer of typescript@~4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@13.0.4 requires a peer of @angular/compiler-cli@^13.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@13.0.4 requires a peer of typescript@~4.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN tmp-24156-q2Nn6tXkAo04 No description
npm WARN tmp-24156-q2Nn6tXkAo04 No repository field.
npm WARN tmp-24156-q2Nn6tXkAo04 No README data
npm WARN tmp-24156-q2Nn6tXkAo04 No license field.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\E5648603\AppData\Local\Temp\3\tmp-24156-q2Nn6tXkAo04\node_modules\@babel\helper-builder-binary-assignment-operator-visitor
npm ERR! dest C:\Users\E5648603\AppData\Local\Temp\3\tmp-24156-q2Nn6tXkAo04\node_modules\@babel\.helper-builder-binary-assignment-operator-visitor.DELETE       
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\E5648603\AppData\Local\Temp\3\tmp-24156-q2Nn6tXkAo04\node_modules\@babel\helper-builder-binary-assignment-operator-visitor' -> 'C:\Users\E5648603\AppData\Local\Temp\3\tmp-24156-q2Nn6tXkAo04\node_modules\@babel\.helper-builder-binary-assignment-operator-visitor.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Projects\.npm-cache\_logs\2022-01-05T06_16_25_209Z-debug.log

Error: Command failed: C:\Users\E5648603\AppData\Local\Temp\3\tmp-7148-ALl9Yq0ittEf\node_modules\.bin\tao migrate 13.2.4
    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Object.handler (C:\Projects\projects\workspace\test-ws1-r55\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:101:25)        
    at Object.runCommand (C:\Projects\projects\workspace\test-ws1-r55\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Projects\projects\workspace\test-ws1-r55\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Projects\projects\workspace\test-ws1-r55\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Projects\projects\workspace\test-ws1-r55\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\Projects\projects\workspace\test-ws1-r55\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16600,
  stdout: null,
  stderr: null
}
PS C:\Projects\projects\workspace\test-ws1-r55>
`

### Environment

- Angular CLI: 13.1.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

- Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment]
This is the repository for Angular Components, perhaps you meant to file the issue elsewhere?
