### ISSUE TITLE
feat(*): Make @HostBinding('disabled') work again

### ISSUE THREAD

**Issue by eosgortor** [angular/components#24165]
### Feature Description

With Material prior 12 I could write a directive with a HostBinding on disabled to support the use case.

```
  @Directive({
    selector: '[permission]'
  })
  export class PermissionDirective {
    @Input() permission: string = ''; // Required permission
    @HostBinding('attr.disabled') get disabled() { 
      return this.permission != "allowed" || null; 
    }
  }
```

Since Material 12 I don't know anymore how to do this. For a button I could add a HostBinding for the class 'mat-button-disabled'. 
`HostBinding('class.mat-button-disabled')`
But how to do it when I want to use the directive for all controls that can be disabled (checkbox, radio, input, ...)? 

There was already an issue (#24006) filed regarding that. But with no general solution.

### Use Case

I want to disable controls, if the user has no permission to use them

**Comment by andrewseguin** [comment]
Interacting with a sibling component using a directive might be challenging using attributes and class names. Ideally you use something that provides the permission value directly to the `disabled` input of the button, like a common service. That way you are not coupled with the implementation details for each individual component.

**Comment by eosgortor** [comment]
Could you please elaborate how such a common service would look and how it could interact with the input properties of the different types of components?
