### ISSUE TITLE
bug(MatButtonToggle): MatButtonToggle breaks when disabling/enabling it

### ISSUE THREAD

**Issue by MeMeMax** [angular/components#24173]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

10.2.0

### Description

We made a major upgrade from Angular 10 to Angular 13. Now our MatToggleButtons do not work as expected. I could reproduce it in a stackblitz independent from our project.

There are two issues I see which might be also related to each other. I connected the mat-toggle-button with reactive forms to a form variable in my ts file.
1. When I disable the mat-toggle-button I can still click on them and the value is actually changed which shouldn´t be possible.
2. When I reenable the mat-toggle-button after clicking on the disabled buttons I can´t click them anymore in enabled state.

I made a stackblitz for reproduction:
https://stackblitz.com/edit/angular-ivy-zqthgm?file=package.json

### Reproduction

Steps to reproduce:
1. Go the stackblitz: https://stackblitz.com/edit/angular-ivy-zqthgm?file=package.json
2. Click around on the mat-toggle-button -> everything works
3. Click enable/disable button to disable the mat-toggle-group
4. Click around on the disabled mat-toggle-button -> still works but it shouldn´t as they are disabled
5. Click enable/disable button to enable the mat-toggle-group
6. Try to click on the enabled mat-toggle-button -> doesn´t work but it should as they are enabled

### Expected Behavior

1. Disabled mat-toggle-buttons shouldn´t be clickable
2. Enabled mat-toggle-buttons should be clickable after reenabling them

### Actual Behavior

1. Disabled mat-toggle-buttons are clickable
2. Enabled mat-toggle-buttons are not clickable after reenabling them

### Environment

- Angular:
    "@angular/animations": "13.0.0",
    "@angular/cdk": "13.1.1",
    "@angular/common": "13.0.0",
    "@angular/compiler": "13.0.0",
    "@angular/core": "13.0.0",
    "@angular/forms": "13.1.1",
    "@angular/material": "13.1.1",
- CDK/Material: 13.1.1
- Browser(s): Chrome and Firefox tested
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Totati** [comment]
For some reasons the ` _buttonToggles: QueryList<MatButtonToggle>` is empty in `MatButtonToggleGroup`. When you disable the group, the children won't be marked for check here. https://github.com/angular/components/blob/master/src/material/button-toggle/button-toggle.ts#L224

**Comment by MeMeMax** [comment]
I just discovered that this is due to some other package which was broken at 13.0.0. I updated all packages to 13.1.1 - now it works.
