### ISSUE TITLE
help(version update errors): Getting errors on serve after version update

### ISSUE THREAD

**Issue by dcp3450** [angular/components#24170]
### What are you trying to do?

I updated anuglar and material from 9 -> 10 but getting errors like this:

`ERROR in src/app/system-tools/user-management/add-user/add-user.component.html(11,7): Directive MatInput, Property '_ariaDescribedby' does not exist on type 'MatInput'.`

### What troubleshooting steps have you tried?

Cleared packages and reran `npm i`

### Reproduction

Steps to reproduce:
1. Followed https://update.angular.io/?l=2&v=9.1-10.2 steps
2. get errors on `ng serve`

### Environment

```
Angular CLI: 10.2.4
Node: 12.22.8
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.4
@angular-devkit/build-angular   0.1002.4
@angular-devkit/core            10.2.4
@angular-devkit/schematics      10.2.4
@angular/cdk                    10.2.7
@angular/cli                    10.2.4
@angular/material               10.2.4
@schematics/angular             10.2.4
@schematics/update              0.1002.4
rxjs                            6.5.5
typescript                      3.9.10
```

**Comment by crisbeto** [comment]
You should make sure that you're running the same version of `@angular/material` and `@angular/cdk`.

**Comment by dcp3450** [comment]
> You should make sure that you're running the same version of `@angular/material` and `@angular/cdk`.

Running everything at the same (10.2.4) and the issue remains.

**Comment by crisbeto** [comment]
The log you posted above shows that the CDK is at 10.2.7.

**Comment by dcp3450** [comment]
> The log you posted above shows that the CDK is at 10.2.7.

I updated it locally. I can paste the new numbers if you want.

**Comment by mmalerba** [comment]
The property it's complaining about `_ariaDescribedby` is an internal API not meant to be used by apps. It looks like it was removed at some point which is probably why you're seeing the error.

**Comment by dcp3450** [comment]
But I'm not using `_ariaDescribedby` @mmalerba , this doesn't help me resolve the issue. Only tells me why it happens, which is great but I don't really know where to go from here.

**Comment by crisbeto** [comment]
It's difficult to tell what could be breaking based on the provided information, but the error sounds like something on like 11 of `src/app/system-tools/user-management/add-user/add-user.component.html` is trying to access a property called `_ariaDescribedby`. The property is present only in the `MatChipList`, `MatDateRangeInput` and `MatSelect` components.
