### ISSUE TITLE
bug(COMPONENT): mat-bottom-sheet-container adding aria-hidden element with tabindex = 0

### ISSUE THREAD

**Issue by mustafaodeh123** [angular/components#24180]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

tabindex and aria-hidden that get added when we use mat-bottom-sheet which get detected by WCAG 2.1 as "aria-hidden elements must not contain focusable elements".

}--></mat-bottom-sheet-container>
<div tabindex="0" class="cdk-visually-hidden cdk-focus-trap-anchor" aria-hidden="true"></div>

### Reproduction

Steps to reproduce:
 Add MatBottomSheetModule to ngModule and then use mat-bottom-sheet-container in your component

### Expected Behavior

After adding reference to the component I can open and close bottom sheet.

### Actual Behavior

It's working as expected but there is an extra element with aria-hidden get added it to the DOM on the runtime.

<div tabindex="0" class="cdk-visually-hidden cdk-focus-trap-anchor" aria-hidden="true"></div>

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The automated tool is probably complaining about the focus trap around the bottom sheet. This isn't a real problem for users, because the invisible element immediately redirects focus to a different focusable element.
