### ISSUE TITLE
Help(matInput): Required form controls validation automatically adds asterisks to the placeholder with 13 upgrade 

### ISSUE THREAD

**Issue by bhavyakalluri90** [angular/components#24193]
### What are you trying to do?

As of version 12 and below dint have this behavior we already have an asterisk hardcoded into the placeholder 
which now leads to the issue of two asterisks on 13 upgrade 

Hence I am looking to find a global config setting that I can set to false may be.
So that the mat input placeholder no longer should asterisk on the required validator.

### What troubleshooting steps have you tried?

I am looking to find a global config setting that I can set to false maybe.
So that the mat input placeholder no longer should asterisk on the required validator.

### Reproduction

Steps to reproduce:
1. 
2. 

### Environment

- Angular:13.1.1
- CDK/Material: 13.1.1
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by domsew** [comment]
Have you ever tried to read documentation [link](https://material.angular.io/components/form-field/api#MatFormFieldDefaultOptions)?

**Comment by bhavyakalluri90** [comment]
Thanks i got to this option of setting hideRequiredMarker to false on the mat-form-field removes the asterisk

I am looking for a more global way of turning the hideRequiredMarker  off on all  mat-form-field usages?

**Comment by crisbeto** [comment]
You can specify `hideRequiredMarker` globally using the `MAT_FORM_FIELD_DEFAULT_OPTIONS` injection token.

**Comment by bhavyakalluri90** [comment]
Thank you that's exactly what I was looking for
