### ISSUE TITLE
help(mat-select): How can I modify the style of one mat-select but not affect others on the same page without global css？

### ISSUE THREAD

**Issue by XSun771** [angular/components#24228]
### What are you trying to do?

I tried to add component-name and the style class name to the mat-select like

`<mat-select [panelClass]="'component-name logger'">`

and add style in style.css in angular project's root dir so it will affect globally.

```css
.component-name.logger {
    max-width: 700px;
}
```

But now it's forbidden to use global styles because of my team's requirements.

And the elements generated from mat-select doesn't have the property of component-id, so styles in componet-style.css will not affect them.

And I have questioned in [Stackoverflow](https://stackoverflow.com/questions/70755717/how-can-i-modify-the-style-of-one-mat-select-but-not-affect-others-on-the-same-p?noredirect=1#comment125085558_70755717)

### What troubleshooting steps have you tried?

How can I modify the style of one mat-select but not affect others on the same page without global css？

### Reproduction

Steps to reproduce:
1. a simple angular-mateiral2 demo project
2.  put two mat-select on one page, and try to modify some style of one without affect the other without global style.

### Environment

- Angular: 10
- CDK/Material: current version
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by crisbeto** [comment]
Your two options are:
1. Include the override in your global styles.
2. Include the override in a component's styles and set `encapsulation: ViewEncapsulation.None`.
