### ISSUE TITLE
feat(mat-icon): I need to change size of mat-icon

### ISSUE THREAD

**Issue by TortuC** [angular/components#24220]
### Feature Description

i want to change the size of mat-icon by props

### Use Case

I used some SvgIcons and the size are different from each other, at this time, I need to set the size of the mat-icon.

**Comment by fireflysemantics** [comment]
You can do that like this:

```
<mat-icon [svgIcon]="SVG.FS_1_LOGO.name" style="width: 42px; height:42px; font-size: 42px"></mat-icon>
```

Full article here including how to create a self initializing module for your SVG Resources:

https://developer.fireflysemantics.com/tasks/tasks--angular--creating-a-self-initializing-material-icons-svg-assets-service

**Comment by mrmokwa** [comment]
Try adding this to your css

```
.mat-icon {
   transform: scale(2);
}
```

**Comment by crisbeto** [comment]
Closing since the comment from @fireflysemantics provided the correct answer.
