### ISSUE TITLE
bug(MatFormField): multiple selects inside a formfield, click on last select opens two selects

### ISSUE THREAD

**Issue by rchod** [angular/components#24223]
### Description
<img src="https://user-images.githubusercontent.com/623771/149923948-96e62b77-9730-44fe-997a-9a7d6e372ee2.png" width="400" height="300" />

```

<mat-form-field appearance="fill">
<mat-label>Select</mat-label>
<br /><br />
<div style="display: flex">
  <mat-select>
    <mat-option value="one">First option</mat-option>
    <mat-option value="two">Second option</mat-option>
  </mat-select>
  <mat-select>
    <mat-option value="one">First option</mat-option>
    <mat-option value="two">Second option</mat-option>
  </mat-select>
  <mat-select>
    <mat-option value="one">First option</mat-option>
    <mat-option value="two">Second option</mat-option>
  </mat-select>
</div>
</mat-form-field>
```

### Reproduction

Steps to reproduce:

I put the code in the discription

replace template here https://material.angular.io/components/form-field/examples#form-field-overview with code in discription

### Expected Behavior

click on last select should open last select

### Actual Behavior

click on last select opens two selects

### Environment

- Angular: 13.0.0-next.0
- CDK/Material: 13.1.2
- Browser(s): google-chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
We don't support multiple form controls inside the same form field.

**Comment by rchod** [comment]
@crisbeto then the doc is slightly misleading ?

> `<mat-form-field>` is a component used to wrap several Angular Material components and apply common Text field styles such as the underline, floating label, and hint messages.

**Comment by crisbeto** [comment]
The docs are referring to things like `mat-label` and `mat-error`.
