### ISSUE TITLE
We're moving away from positioning the dropdown on top of the select. You can try our new select based on top of MDC's styles. The API and behavior is exactly the same since it shares the same base class as the current select, but the CSS will be slightly different and the dropdown is only positioned above/below. You can try it by importing `MatSelectModule` from `@angular/material-experimental/mdc-select` instead of `@angular/material/select`.

### ISSUE THREAD

**Issue by khepf** [angular/components#24229]
Hello,

Any update on when the corrections to the mat-select dropdown positioning might be ready for production? I have a few teams holding off on updating from Angular Material 11 for this reason alone.

Thank you!
Jeremy

We're moving away from positioning the dropdown on top of the select. You can try our new select based on top of MDC's styles. The API and behavior is exactly the same since it shares the same base class as the current select, but the CSS will be slightly different and the dropdown is only positioned above/below. You can try it by importing `MatSelectModule` from `@angular/material-experimental/mdc-select` instead of `@angular/material/select`.

_Originally posted by @crisbeto in https://github.com/angular/components/issues/23625#issuecomment-931448386_

**Comment by khepf** [comment]
13.1.1
I thought I would try out the experimental `mat-select` version but I am getting quite a few errors.

First of all, `npm install @material/line-ripple` needs to be installed, per the first build error. Then it build successfully. But when I start it, I am getting:
`Error: Module not found: Error: Can't resolve '@material/textfield' `
`Error: Module not found: Error: Can't resolve '@material/dom' `
`Error: Module not found: Error: Can't resolve '@material/notched-outline'`

I had a look at some old Angular 11 builds and these modules were not located there either.

I am not finding any answers for these errors when I search for them.

**Comment by crisbeto** [comment]
You can install this instead which brings in all of the MDC code. https://www.npmjs.com/package/material-components-web

Also note that you'll have to include the theme for the MDC select. There's more info here: https://github.com/angular/components/blob/master/src/material-experimental/mdc-select/README.md

**Comment by khepf** [comment]
cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
