### ISSUE TITLE
@angular/google-maps - Documentation or Bug:  map.fitBounds

### ISSUE THREAD

**Issue by SheldonHage** [angular/components#24246]
### Documentation Feedback

I've been unable to reach success using the Angular Google Maps documentation to implement map.fitBounds.   I can successfully set multiple map markers using the module as well as success using a pure javascript approach.

Perhaps my implementation is incorrect (which I will suspect first).  However there is no sample to reference.  Obviously this is an important aspect of the mapping function.  I suggest a small example with setting >1 map marker and then a boundary using .fitBounds.

Thank you

### Affected documentation page

@angular/google-maps Docs

**Comment by crisbeto** [comment]
Our component is just a wrapper around the Google Maps API so you can refer to their docs for a more detailed description. https://developers.google.com/maps/documentation/javascript/reference/map#Map.fitBounds

**Comment by SheldonHage** [comment]
Perhaps I was not clear enough:  The Angular-specific way of doing it...is not described at all and Google's materials on the topic are great; this does absolutely zero with respect to implementing your wrapper-specific method of getting map.fitBounds to work.   I believe your wrapper does not work in this specific example; I believe you forgot to wrap this one.

Try it yourself and see.   There is zero examples showing your wrapper successfully can do a map.fitBounds.  Again, I have all I need to implement this using Javascript; in fact it worked the first try with a few lines of code.   No matter what I try using your wrapper, map.fitBounds throws a NULL reference to the latlng values being input.

I am trying to help your team build a complete product here.   I've given your Google Maps wrapper a lot of time and effort and frankly its far easier to just use the Javascript methods and abandon this wrapper completely.    Not being a pain here; genuinely want your efforts to be worth something.   But if each time I write up an issue its simply closed, I will stop.  My time is especially valuable to me.

**Comment by crisbeto** [comment]
It's difficult to say what is going on without looking at the code, but for reference, our `fitBounds` method literally just calls into the Google Maps version of `fitBounds` https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.ts#L334. This means that it's likely an issue with the value that is being passed into the method.

**Comment by savanrajkotiya** [comment]
I'm dropping small code snippet for fitBounds with angular google map component , which is perfectly working in my case.

```

// define angular google component using @ViewChild decorator 
 @ViewChild(GoogleMap) googleMap: GoogleMap;
 
// ref.
let markers =  [
      {
        lat: 43.516034,
        lng: 5.471529,
      },
      {
        lat: 43.523021,
        lng: 5.456153,
      },
      {
        lat: 43.523021,
        lng: 5.456153,
      },
    ];
    
    let bounds = new google.maps.LatLngBounds();

    markers.forEach((marker:any) => {
      bounds.extend(
        new google.maps.LatLng(marker.lat, marker.lng)
      );
    });
    // directly can access fitBounds.
    this.googleMap.fitBounds(bounds);
   
```
