### ISSUE TITLE
DatePicker component

### ISSUE THREAD

**Issue by reethupriya** [angular/components#24254]
### What are you trying to do?

I only want to use the datepicker styles, how is that possible without including everything else in the stack

### What troubleshooting steps have you tried?

I have tried including in datepicker styles component without importing styles globally but only few styles are rendering.

### Reproduction

Steps to reproduce:
1. 
2. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You can use the datepicker component on its own, but it still needs some structural styles. At minimum, you need the Material core styles and the datepicker theme.
