### ISSUE TITLE
help(Core): After 13.1.3 release css modules build fails because of missing hues.

### ISSUE THREAD

**Issue by jose-torres-chang** [angular/components#24250]
### What are you trying to do?

On our project we are using custom theming, we are defining custom palettes, but we don't need each of the hues, so we only defined the ones we need, with this change [#23612](https://github.com/angular/components/commit/65bc9feedcb223a62d92b2b799392cbb9238a6b7), our CI/CD process start failing, after some research we found out the above described was the cause, but how can we go around this issue? We don't need all of the hues for each palette.

### What troubleshooting steps have you tried?

We tried using map-merge with some random prebuilt palette and it works, but seems like a poluted solution to this issue.

### Reproduction

Steps to reproduce:
1. Update to version 13.1.3
2. Define custom theme palette.
3. Run ng-build. Build fails beacause of the missing hues.

### Environment

- Angular: 13.1.3
- CDK/Material: 13.1.3
- Browser(s): build step
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
This means that you had invalid styles in your theme. The error is only going to be thrown if something requested a color that doesn't exist. Previously in such cases the function would've returned `null` and Sass would've skipped the style altogether which is a silent error.

**Comment by JSHSJ** [comment]
Can confirm, ran into the same issue. So we now have to define the whole palette?

We were only defining a few of the palette hues before, but this doesn't seem to be possible anymore.

**Comment by jose-torres-chang** [comment]
@crisbeto would you advise on a solution like using a fallback palette for not used hues?

**Comment by crisbeto** [comment]
Yes, in general your palette should be complete, otherwise some styles might not look right. If you don't want to define the full palette, you can always extend one of the built-in ones with your color overrides.

**Comment by crisbeto** [comment]
Closing since it's working as expected. We've never intentionally supported incomplete palettes.
