### ISSUE TITLE
bug(COMPONENT): build breaks if following hues 100, 500 and 700 is not present in color palettes

### ISSUE THREAD

**Issue by sp90** [angular/components#24268]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v12.x.x

### Description

So when i have a color palette that only have the hue ex 500 it breaks due to `material/core/theming/_theming.scss 55:14` it seems that its now in v13 required to have 100, 500 and 700 for the palettes not to break. 

I think this is a misbehaviour since color palettes are defined some times for errors or success color palettes only.

### Reproduction

Steps to reproduce:
1. Add a color palette with only hue 500, for like a success or error color
2. Build breaks

### Expected Behavior

The expected behavior is that i can use the palette as any other palette but im not required to add both 100, 500 & 700 hue and the build to not break when i do so.

### Actual Behavior

Build failed

### Environment

- Angular: 13.1.3
- CDK/Material: 13.1.3
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
See the discussion in https://github.com/angular/components/issues/24250.

**Comment by wagnermaciel** [comment]
This is working as intended

We use those values internally, so the failures are legitimate. Not passing in these values creates weird breakages which are hard to debug. I agree, this validation probably should have been added in maybe a minor version instead of patch

**Comment by sp90** [comment]
Then definately better error message.

None the less i think that requiring certain colors should also be documentated in the documentation about themes maybe?
