### ISSUE TITLE
bug(MapMarker): MapMarker wraps positions, NOT Markers

### ISSUE THREAD

**Issue by VashJuan** [angular/components#24271]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

According to https://github.com/angular/components/tree/master/src/google-maps/map-marker:

_"The MapMarker component wraps the google.maps.Marker class from the Google Maps JavaScript API. The MapMarker component displays a marker on the map when it is a content child of a GoogleMap component. Like GoogleMap, this component offers an options input"_

What I am seeing is that MapMarker actually wraps only google.maps.LatLngLiteral. It appears there is ONLY one google.maps.MarkerOptions allowed for the whole set of markers on a map.

I am new to all this, so may have other options, but I'm looking to display locations over time of 4 Search & Rescue teams: each team with a different icon/title, and to have the colors of the markers fade in color over time. Is there another approach to this? 

(I guess I can mix & match the Angular wrappers and the underlying google.Maps API. Is that a fluid process/documented anywhere?!)

This may be related to [https://github.com/angular/components/issues/21225](https://github.com/angular/components/issues/21225)

### Reproduction

Steps to reproduce:
1. 
2. 

### Expected Behavior

`
markers: google.maps.Marker[] = [];

  addMarker(event: google.maps.MapMouseEvent) {
    this.markers.push( 
       new google.maps.Marker({
           position: event.latLng.toJSON(),
           title: "Team B",
           label: "10:20:29: status is normal",
           options: {draggable: false, icon: "teamB.ico"}
       })
     )
  }
`

and

`
<map-marker *ngFor="let marker of markers"
              [position]="marker.position"
              [title]="marker.title"
              [label]="marker.label"
              [options]="marker.options"></map-marker>
`

### Actual Behavior

Wrong type...

### Environment

- Angular: latest
- CDK/Material: x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): win

**Comment by wagnermaciel** [comment]
@crisbeto Could you take a look

**Comment by crisbeto** [comment]
The `map-marker` is a representation of a single marker in your markup, it doesn't represent the actual DOM node that is added on the map itself since that is handled by the Google Maps API. You're likely only seeing one marker, because you keep inserting it at the same position. Here's an example that works for me showing two markers somewhere in Libya:

```
  markerPositions: google.maps.LatLngLiteral[] = [
    {lat: 24, lng: 12},
    {lat: 25, lng: 13},
  ];
```

``` html
<google-map height="400px" width="750px">
  <map-marker *ngFor="let markerPosition of markerPositions" [position]="markerPosition"></map-marker>
</google-map>
```

**Comment by VashJuan** [comment]
My issue is not being able to display lots of markers (they work fine), it is that they ALL WILL LOOK ALIKE.

I would say map-marker is only representing a series of positions - if all have the same appearance/use the same identical marker.

google.maps.Marker has a lot of other options than just a position. Every marker on a map should be able to have a unique appearance. That is easily possible with `markers[] = google.maps.Marker[] ` it is impossible with `positions[] = MapMarker[]`.

Hopefully I'm wrong, but I don't think so. Thanks for taking another look at this issue!

I fortunately found the onMapInitialized event:
`onMapInitialized(newMapReference: google.maps.Map){}` which allows dual use of GoogleMap and google.maps.Marker, so I'm fine.

**Comment by crisbeto** [comment]
You can pass different configurations to each marker using the `options` input, if you want to. I would double-check that you're actually specifying the options correctly.
