### ISSUE TITLE
bug(tooltip): Tooltips are sometimes empty

### ISSUE THREAD

**Issue by sebastianrath** [angular/components#24278]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am using [MatToolTip](https://material.angular.io/components/tooltip/api) and I encounter them often being empty like this:

<img width="153" alt="Screen Shot 2022-01-26 at 10 29 17 AM" src="https://user-images.githubusercontent.com/12844423/151193253-b4bbee66-17e1-40cb-b94d-3ae7bcf1359d.png">

Each hover creates an additional empty bubble with an offset to the right. I can't replicate this on Stackblitz yet.

My component looks like this:

## foo.component.html
```html
<div *ngIf="project">
   <button mat-icon-button type="button" matTooltip="XYZ">
      Hover me
   </button>
</div>
```

## foo.component.ts
```typescript
...
@Input() project: FooProject | null;
...
```

## foo.component.scss
```
// Empty
```

I made two observations:

1) Pressing a keyboard input like **CTRL** or **ALT** will update the view and show the correct tooltip.
2) Removing `*ngIf` or setting it to `true` will result in a correct tooltip behaviour.

This is how the DOM looks like if the tooltip is empty:

```html
<div class="cdk-overlay-container">
    <div class="cdk-overlay-connected-position-bounding-box" dir="ltr"
        style="top: 0px; left: 0px; height: 100%; width: 100%;">
        <div id="cdk-overlay-8" class="cdk-overlay-pane mat-tooltip-panel" style="top: 303px; left: 510.273px;">
            <mat-tooltip-component aria-hidden="true" class="ng-tns-c42-131">
                <div class="mat-tooltip ng-tns-c42-131 ng-trigger ng-trigger-state"></div>
            </mat-tooltip-component>
        </div>
    </div>
</div>
```

### Reproduction

Steps to reproduce:
1. Hover over the tooltip.

### Expected Behavior

This is how it should look like.

<img width="120" alt="Screen Shot 2022-01-26 at 10 32 07 AM" src="https://user-images.githubusercontent.com/12844423/151193842-f23fb3a2-9180-49a1-bf9c-700e97af908e.png">

### Actual Behavior

The tooltips are empty.

### Environment

- Angular: 11.2.13
- CDK/Material: 11.2.13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS, Windows, Linux

**Comment by wagnermaciel** [comment]
Could you provide a reproduction in stackblitz? My best guess would be that you forgot to include the tooltip theme styles.

**Comment by seb-mtl** [comment]
I tried to reproduce this, without any success yet. The tooltip themes are included, and they work if I literally set it to `*ngIf="true"` but I understand if the given information is not enough. I will keep reducing my project as far as I can.

**Comment by crisbeto** [comment]
I can reproduce something similar if I explicitly try to bind the tooltip's `mouseenter` event using `NgZone.runOutsideAngular`. Maybe something similar is happening in this case?

**Comment by areksliwa-modento** [comment]
I have the same issue. I have a table with patients and after scrolling down, there are new rows rendered. And the issue with tooltip empty squares appears only on these newly rendered rows. After 700 delay tooltip with content appear correctly

**Comment by s001dxp** [comment]
I'm experiencing the same issue. Sometime they show and sometimes they don't. 
![Image from iOS](https://user-images.githubusercontent.com/309768/176926765-b691ce09-4759-4ba3-a9d7-1aad4cbeedd2.jpg)

**Comment by seb-mtl** [comment]
I switched to popper.js with Angular bindings. It took me just a few minutes to replace 100 tooltips across my app.

**Comment by kiranatious** [comment]
Im able to reproduce the issue..

**Comment by kiranatious** [comment]
the issue exists ver 9

**Comment by Bettaswamy** [comment]
Any update on this tooltip issue.

**Comment by Bettaswamy** [comment]
> I'm experiencing the same issue. Sometime they show and sometimes they don't. ![Image from iOS](https://user-images.githubusercontent.com/309768/176926765-b691ce09-4759-4ba3-a9d7-1aad4cbeedd2.jpg)

Were you able to fix this?

**Comment by youtopiavr** [comment]
We are also encountering this bug.

**Comment by pszulcint** [comment]
I'm facing the same issue, angular material v. 14.2.0

![image](https://github.com/angular/components/assets/142868198/41bfac3b-b518-4a96-ba71-50db126edcf0)

Here is a demand behavior:

![image](https://github.com/angular/components/assets/142868198/24c78587-ab6c-4e05-87a8-81eb290926b7)

As you can see it's placed wrong, has no content and wrong style.

**Comment by Harpush** [comment]
We also have this bug - mostly in ag grid cells

**Comment by zarend** [comment]
Hello,

Thank you for reporting. We are unable to reproduce. I was wondering if we could check with you if this issue requires further action.  Unfortunately we may not be able to take action if we cannot reproduce it. Could you please provide a stackblitz reproduction of the issue?

Best regards,

Zach

**Comment by llorenspujol** [comment]
I also encountered this bug. It happens 100% of the time when the tooltip is created outside the zone. In such cases, the `mouseenter` event will not be within the zone, and consequently, `this._ngZone.onMicrotaskEmpty` will not emit. [Here](https://stackblitz.com/edit/kpqfdc?file=src%2Fexample%2Ftooltip-empty-bug-example.ts) is a StackBlitz that reproduces it.

Overall, creating components outside the zone doesn't seem like a great idea, but sometimes it happens due to other factors. Would it be beneficial to check whether we are outside the zone and re-enter if that is the case? The only drawback is that 99% of the time, that checking function will return `true` and not provide additional value. On the other hand, this bug would be solved.

I can provide a PR.

**Comment by louischristner** [comment]
We encountered this issue when using tooltips in a Leaflet popup. We generate the popup from an angular component with a tooltip using a factory. The component works as intended when used outside of Leaflet, but when used in a popup the tooltip appears empty.

![Screenshot from 2023-11-09 10-46-46](https://github.com/angular/components/assets/52711941/ce8ae77c-ec5f-49fb-bbbe-f56cbe9b69c2)

https://github.com/angular/components/assets/52711941/edd1c511-7edb-4f67-9871-f3077ba5702d

I created a reproduction of the issue in [Stackblitz](https://stackblitz.com/edit/angular14-leaflet-kskrkn?file=src%2Fapp%2Fapp.component.ts).

**Comment by pukassh** [comment]
To make it work on lazy loaded/rendered elements, use [matTooltip]="'example'" instead of matTooltip="example".

**Comment by aarce1054** [comment]
Me pasa lo mismo , alguien pudo resolver este problema?

**Comment by joewIST** [comment]
We also experience this issue; we see the grey box for about 0.5s and then the actual tooltip and content appears.

**Comment by louischristner** [comment]
We found a solution to our issue ([see previous comment](https://github.com/angular/components/issues/24278#issuecomment-1803562881)). The problem was caused by the `ComponentFactoryResolver` which was deprecated. We replaced the `ComponentFactoryResolver` by a `ViewContainerRef` as specified in [this Stackoverflow post](https://stackoverflow.com/questions/70946038/replace-deprecated-angular-componentfactoryresolver-componentfactory).

[Here](https://stackblitz.com/edit/angular14-leaflet-p3nyng?file=src%2Fapp%2Fapp.component.ts) you can find a fixed version of the [previous Stackblitz](https://stackblitz.com/edit/angular14-leaflet-kskrkn?file=src%2Fapp%2Fapp.component.ts).
