### ISSUE TITLE
Taking mat-label from mat-form-field causes accessibility issue

### ISSUE THREAD

**Issue by mostafabita** [angular/components#24284]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I wanted to have control label above mat-form-field rather than a floating label inside mat-form-field.
According to https://github.com/angular/components/issues/17913 I wrote this and works fine
```
<mat-label for="name">Name</mat-label>
<mat-form-field [appearance]="outline">
   <input id="name" matInput type="text"/>
</mat-form-field>
```
but arises when I mat-select inside mat-form-field, I removed mat-label from mat-form-field but component didn't notice and adds an empty element for label and also adds `aria-labelledby` attribute to mat-select, after running lighthouse you can see a warning related to empty element used for mat-select label.
```
<label for="subject">Subject</label>
<mat-form-field [appearance]="outline">
   <mat-select id="subject">
      <mat-option>1</mat-option>
      <mat-option>2</mat-option>
   </mat-select>
</mat-form-field>
```

### Reproduction

Steps to reproduce:
1. Add a sample material select component https://material.angular.io/components/select/overview
2. Remove mat-label from mat-form-field 
3. Add an ID to mat-select
4. Add a label outside of mat-form-field and add for="ID" attribute
5. Run lighthouse to generate an Accessibility report

### Expected Behavior

When mat-label is not exists inside mat-form-field, aria-labelledby should not be added to mat-select.

### Actual Behavior

I wanted to have control label above mat-form-field rather than a floating label inside mat-form-field.
According to https://github.com/angular/components/issues/17913 I wrote this and works fine
```
<mat-label for="name">Name</mat-label>
<mat-form-field [appearance]="outline">
   <input id="name" matInput type="text"/>
</mat-form-field>
```
but problem arises when I mat-select inside mat-form-field, I removed mat-label from mat-form-field but component didn't notice and adds an empty element for label and also adds `aria-labelledby` attribute to mat-select, after running lighthouse you can see a warning related to empty element used for mat-select label.
```
<label for="subject">Subject</label>
<mat-form-field [appearance]="outline">
   <mat-select id="subject">
      <mat-option>1</mat-option>
      <mat-option>2</mat-option>
   </mat-select>
</mat-form-field>
```

### Environment

- Angular: 13.0.0
- CDK/Material: 13.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Closing, because we don't support this use case.
