### ISSUE TITLE
feat(MatFormField): Add new css class when field has been touched

### ISSUE THREAD

**Issue by rhilliges** [angular/components#24287]
### Feature Description

I would like to have a css class on the mat-form-field component (e.g. mat-form-field-touched) when the inner ng-control was touched. Adding it as a conditional class in the host section of the MatFormField might do the trick:

```
@Component({
...

   host: {
      '[class.mat-form-field-touched]': '_control.ngControl.touched',
   }
...
})
```

### Use Case

My designer wants to give a form field a different background color, whenever the user has touched it.

**Comment by lekhmanrus** [comment]
Isn't that currently possible? `ng-touched` applies to <mat-form-field> component as soon as control is touched.

**Comment by rhilliges** [comment]
Yes that works. Just forgot to bind a form controll to the select input...
