### ISSUE TITLE
help(mat-table): Why does matColumnDef not need the asterisk notation?

### ISSUE THREAD

**Issue by shinkhouse** [angular/components#24290]
### What are you trying to do?

I was currious was *matCellDef, *matHeaderCellDef, and *matRowDef are all using structural/asterisk notation but the matColumnDef is not? Is it because the former are using some template container and matColumnDef basically just gets/sets the class name? Could you give an explanation with an example?

### What troubleshooting steps have you tried?

N/A

### Reproduction

N/A

### Environment

- Angular: 12.0.0
- CDK/Material: 12.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by andrewseguin** [comment]
Sort of - it's a necessity to provide templates to the table but also give a way for the table to grab references. It's not the clearest API but its as simple as Angular will let us make it
