### ISSUE TITLE
bug(COMPONENT): mat-dialog html render but constructor not runing until click on the screen (weird bug)

### ISSUE THREAD

**Issue by hiepxanh** [angular/components#24305]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description
I create dialog display after google login fail. Then
![image](https://user-images.githubusercontent.com/16970990/151575765-b6354fb5-53e6-4a24-91e9-23070a4c5dc5.png)
my dialog load without trigger ngOnInit 
![image](https://user-images.githubusercontent.com/16970990/151575892-ad784b59-65b0-4cb4-8055-e255586d9027.png)
only I click on the dialog or screen, it start loading the dialog data.
![image](https://user-images.githubusercontent.com/16970990/151575947-26b1db22-10e5-43be-ad47-c05893d9c24d.png)
You can watch my video for more detail
https://user-images.githubusercontent.com/16970990/151576047-dbbdfa31-4ad5-4e9e-8469-f9cc37164845.mp4
I already use `this.cd.detectchanges()` to make angular update but it just not work

### Reproduction

It very hard for me to reproduce, I just know it present there, I dont know what cause of problem.
Steps to reproduce:
1. create dialog
2. dialog not loading, only render html
3. click to screen to make it load ts file

### Expected Behavior

load normally

### Actual Behavior

the ts file not load until I click on the screen, only this dialog have this situation, I have about 10 other dialog is work perfectly fine.

### Environment

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: pnpm 6.11.5
OS: win32 x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2 (cli-only)
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
webpack                         5.65.0

**Comment by hiepxanh** [comment]
I guesss because I'm just open from other screen then it lose focus?

**Comment by hiepxanh** [comment]
currently my workaround is faking a click on the target element
 ` (document.querySelector('app-confirm') as any)?.click();`

**Comment by wagnermaciel** [comment]
Please provide a reproduction in stackblitz so we can investigate

https://stackblitz.com/run?file=src/app/dialog-content-example.ts

**Comment by ajafff** [comment]
The code that opens the dialog does not run inside the NgZone, therefore no change detection happens

**Comment by hiepxanh** [comment]
thank you, I will try to reproduce, maybe it run outside ngZone

**Comment by hiepxanh** [comment]
confirm run outside zone.js, have to force run in zone.js, fail to use change detection. I decide to use https://github.com/ngneat/dialog
