### ISSUE TITLE
bug(COMPONENT): MapHeatmapLayer

### ISSUE THREAD

**Issue by snowflake752** [angular/components#24301]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

https://github.com/angular/components/blob/master/src/google-maps/map-heatmap-layer/README.md
The example for MapHeatmapLayer attached here is not working.
P.S. added visualization library in the API_key.

### Reproduction

Steps to reproduce:
1. 
2. 

### Expected Behavior

This should work

### Actual Behavior

![image](https://user-images.githubusercontent.com/40699134/151526968-f96c293b-6fb2-4fdf-9582-0e777ce765ab.png)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):
![image](https://user-images.githubusercontent.com/40699134/151526824-36929b2b-da80-4bbe-920e-2843cddb5b70.png)

**Comment by wagnermaciel** [comment]
@crisbeto Could you take a look

**Comment by crisbeto** [comment]
The exact code from the documentation works for me. This is likely an issue your end or you just aren't zoomed in enough to see the heatmap.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/4450522/154998627-be1e81ca-fb6e-44b2-b41e-78b9ef2571a1.png">
