### ISSUE TITLE
bug(MAT_DIALOG): Dialog backdrop not working as expected on Chrome 97 vs Firefox

### ISSUE THREAD

**Issue by Polyterative** [angular/components#24315]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Opening official dialogs in docs shows no backdrop.
This happens on my prod too. 
Latest Firefox works as should instead. 

### Reproduction

Steps to reproduce:
1. Open any dialog with chrome 97 on https://material.angular.io/components/dialog/examples

### Expected Behavior

Should show backdrop and exit on click

### Actual Behavior

No backdrop, ignores click outside dialog

### Environment

- Angular: 13.2,13.1
- CDK/Material: 13.2,13.1
- Browser(s): Chrome 97.0.4692.99 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Win

**Comment by crisbeto** [comment]
It shows a backdrop as expected for me on the same version of Chrome on both Windows and Mac. Maybe something else is messing with it (e.g. a browser extension)?

**Comment by Polyterative** [comment]
OK, this is an absolutely crazy story, but apparentl it was totally caused by an extension.
I did try it in Incognito before submitting the issue, but there is only one extension I keep on Incognito mode, which is uBlock Origin.

There is a certain block list that disables the backdrop via CSS apparently.
Disabling it fixed the issue.

Leaving this for posterity. Thanks @crisbeto and sorry for the trouble. 

![image](https://user-images.githubusercontent.com/16295552/151804349-fa7df504-35c9-4873-be79-c941c5af6b6a.png)
