### ISSUE TITLE
bug(CDK): cdk-describedby-message-container visible below application footer

### ISSUE THREAD

**Issue by tylerjharden** [angular/components#24327]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The div with ID `cdk-describedby-message-container`, despite being tagged with visibility: hidden, will show as an empty white block the size of the tooltip labels it contains.

The only hack that appears to fix this is a `display: none` on the element ID in the application stylesheet.

### Reproduction

Steps to reproduce:
1. Create an application with a footer and tooltips on multiple items
2. See CDK DescribedBy container below the application footer.

### Expected Behavior

This hidden div being invisible, not taking up visible space in the rendered DOM.

### Actual Behavior

The div `cdk-describedby-message-container` shows as an invisible div, still taking up space beneath an application footer.

### Environment

- Angular: 11.1.2
- CDK/Material: 11.2.13
- Browser(s): Edge 
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
It sounds like you haven't included the `core` mixin which hides the element completely.

**Comment by tylerjharden** [comment]
@crisbeto Are you able to refer me to an example implementation or documentation so that I can test that?

**Comment by crisbeto** [comment]
https://material.angular.io/guide/theming#the-core-mixin

**Comment by tylerjharden** [comment]
That resolved the issue, thank you.
