### ISSUE TITLE
docs-bug(tabs): non-existing input property preserveContent for mat-tab-group as for version 13.2.1

### ISSUE THREAD

**Issue by YuriiKovalenko** [angular/components#24369]
### Documentation Feedback

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/33899537/152793829-0c1a6a03-a880-462a-90c7-1eb18ed31233.png">

Documentation introduced preserveContent feature for mat-tab-group component, but `tab-group.d.ts` doesn't have it despite of package version of `@angular/material` package is exact 13.2.1.

P.S. I saw this feature had been recently merged to master, so looking forward for release.

### Affected documentation page

https://material.angular.io/components/tabs/overview#keeping-the-tab-content-inside-the-dom-while-its-off-screen

**Comment by YuriiKovalenko** [comment]
Also [StackBlitz sandbox](https://stackblitz.com/run?file=src%2Fapp%2Ftab-group-preserve-content-example.html) failed to compile.
And example on the doc page doesn't preserve content in that example.

**Comment by crisbeto** [comment]
The feature is available in v14, but I think that it showed up in the docs because we're pointing the docs site to `master` on https://github.com/angular/material2-docs-content. cc @devversion

**Comment by crisbeto** [comment]
No, in general we don't backport features to previous versions. The switch from 13 to 14 should be pretty straightforward though.

**Comment by crisbeto** [comment]
Closing since the documentation looks correct now.
