### ISSUE TITLE
bug(VirtualScroll): Virtual scroll inside initially hidden container doesn't work well

### ISSUE THREAD

**Issue by Harpush** [angular/components#24362]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a virtual scroll container is rendered inside display none element - when shown the scrolling doesn't work well and some items are not rendered.

### Reproduction

Steps to reproduce:
1. Toggle the hidden state with the button
2. Try to scroll and see the problem

Stackblitz: https://stackblitz.com/edit/angular-3aywjn?file=src/app/cdk-virtual-scroll-append-only-example.ts

### Expected Behavior

Fully functional virtual scroll after shown

### Actual Behavior

Scroll doesn't work well - some items are not rendered correctly

### Environment

- Angular: 13.0.4
- CDK/Material: 13.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by pkirchniawy** [comment]
Hello @Harpush :slightly_smiling_face:

I face the same issue when using the virtual scroll element inside a container with display:none. But I found a workaround.

We canuse the properties `minBufferPx` and `maxPxBuffer` to fix our problem. If I understand it right, it does the following thing: If the scroller detects, that there is less whitespace left than the minBufferPx value, it renders more elements to fill it up. So the whitespace that gets created by the bug inside a hidden container gets filled up properly.

In your example, i added this properties and it worked. :upside_down_face:

```
<cdk-virtual-scroll-viewport
    itemSize="50"
    minBufferPx="500"
    maxBufferPx="1000"
    class="example-viewport"
  >
    <div *cdkVirtualFor="let item of items" class="example-item">{{item}}</div>
  </cdk-virtual-scroll-viewport>
```

**Comment by andrewseguin** [comment]
It would be feasible to add in a delay mechanism where the virtual scroll checks if it is displayed, and otherwise uses IntersectionObserver to detect when its safe to initialize. However, it's possible that may happen more than once, and the code will get more complicated about when it checks to re-init on each hidden/display.

I think it's acceptable to just call the `checkViewportSize` to force the virtual scroll to update, and it's up to the client to make that call.

**Comment by Harpush** [comment]
@andrewseguin Any example for such code using intersection observer? Might just create a directive that does just that if it won't get baked in the virtual scroll module
