### ISSUE TITLE
docs: theming docs misspells pink-bluegrey.css as pink-bluegray.css

### ISSUE THREAD

**Issue by riteshwaghela** [angular/components#24378]
### Documentation Feedback

Theming document lists several prebuilt theme names. One of the file name mentioned is **pink-bluegray.css**, this seems to be incorrect as the the actual file name which gets created is **pink-bluegrey.css**.

So the pink-bluegray.css needs to be changed to pink-bluegrey.css.

### Affected documentation page

https://v12.material.angular.io/guide/theming

**Comment by emceearjun** [comment]
I would like to pick this issue up if that's okay.

**Comment by AlirezaEbrahimkhani** [comment]
@riteshwaghela 
Hi ! as you can see in the PR review conversation both spelling are covered.
based on this [link](https://github.com/angular/components/blob/master/src/material/core/theming/_palette.scss#L671)
