### ISSUE TITLE
feat(COMPONENT): Mat-select select full group

### ISSUE THREAD

**Issue by AlexeyOplachko** [angular/components#24381]
### Feature Description

Would be nice to have native "Select/deselect all in group" option in `mat-select` if it's set to `multiple` and has `<mat-opt-group>` inside 
Smth like this. 
![image](https://user-images.githubusercontent.com/45398541/153053301-f8b0875d-8b48-4c5d-b727-0b071f20670b.png)

**Comment by wagnermaciel** [comment]
Duplicate of #9149
