### ISSUE TITLE
bug(Datepicker): Cannot highlight specific dates with v13

### ISSUE THREAD

**Issue by keith-aa** [angular/components#24383]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Tried running the "Highlighting specific dates" example from https://material.angular.io/components/datepicker/overview on Stackblitz. It would not highlight. Also, tried downloading the example and updating to latest release. It still did not work.

Expected
![highlighted](https://user-images.githubusercontent.com/76117016/153092598-25cedbdf-3553-4e55-94f3-eeffa63a68a8.PNG)

Actual
![not-highlighted-as-expected](https://user-images.githubusercontent.com/76117016/153092638-eb4c881a-f832-423d-a0f0-4d3f8a9177ab.PNG)

### Reproduction

Steps to reproduce:
1. Download [angular-date-class-filter-13.zip](https://github.com/angular/components/files/8028249/angular-date-class-filter-13.zip)
2. Extract zip file.
3. npm install
4. ng serve --port 4000
5. Open browser to port 4000
6. Click calendar icon

### Expected Behavior

Expected to see the 1st and 20th highlighted.
![highlighted](https://user-images.githubusercontent.com/76117016/153093858-e769501e-e5f0-4f61-ba1b-da960bccf631.PNG)

### Actual Behavior

Neither day is highlighted.
![not-highlighted-as-expected](https://user-images.githubusercontent.com/76117016/153093831-8f4960a3-5b5e-41a2-bef1-2357b6ffdeaf.PNG)

### Environment

C:\Temp\examples\angular-date-class-filter-13>ng version

Angular CLI: 13.2.2
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cdk                    13.2.1
@angular/material               13.2.1
@schematics/angular             13.2.2
rxjs                            7.4.0
typescript                      4.4.4

**Comment by crisbeto** [comment]
The class does get assigned correctly. The problem appears to be that the `background: none` added in the following change has a higher specificity and overrides the background from the custom class. https://github.com/angular/components/commit/43db8445e0eb7bf2dc57c4f95314f7965d1c240b#diff-c9da88d358126fd9af0bcfe70ca9dce66f53916557502d2e817772d860c9822cR48
