### ISSUE TITLE
help(Material Date picker): Issue when adding Datepicker to a remote component in module federation

### ISSUE THREAD

**Issue by srukshan98** [angular/components#24392]
### What are you trying to do?

I am trying to use datepicker within an remote component using module federation and am getting the attached error message.
![image](https://user-images.githubusercontent.com/32130720/153338288-01204289-a695-40c5-bbeb-7f4b617a20f2.png)

### What troubleshooting steps have you tried?

- Added `@angular/material` as shared library to webpack config of all projects
- Tried adding `@angular/material/core` as shared library to webpack config of all projects
- Added MatDatepickerModule and MatNativeDateModule to import of App Modules of both base and remote projects
- Tried Adding MatDatepickerModule and MatNativeDateModule as providers too.
- Tried installing `@angular/material-moment-adapter` and using it instead of MatNativeDateModule.

### Reproduction

Steps to reproduce:
1. Clone the repo with the sample app containing the error([click this link](https://github.com/srukshan98/nx-ng-mfe-date-picker-issue))
2. run npm install
3. run following commands in separate terminals
  - npx ng s
  - npx nx build remote -c=development --watch
  - npx http-server dist/apps

### Environment

- Angular: 12.3.3
- CDK/Material: 12.2.13
- Browser(s): Microsoft Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by alexanderwiebe** [comment]
I created a PR to your branch:
https://github.com/srukshan98/nx-ng-mfe-date-picker-issue/pull/1
Added material core and material datebicker to the container app module and webpack config

It works for me, let me know if this resolves your issue.

**Comment by srukshan98** [comment]
Hi @alexanderwiebe, 
I was getting this error when running the app after merging the fix.

![88b98613-55be-46c6-b05f-095ff88a7900](https://user-images.githubusercontent.com/32130720/153829160-aa28d3de-56c6-4d5d-8ce0-64698588f6d3.jpg)

I was able to fix it by adding eager to all and have pushed it now. But now I am getting a different error.

![image](https://user-images.githubusercontent.com/32130720/153829454-5cf027c9-f3dc-4d1c-ba66-dd82df63bf16.png)

**Comment by alexanderwiebe** [comment]
MatInputModule module needs to be imported by both remote and container.  
That is a separate issue though, you can validate the date picker works by commenting out the mat-form-field in remote-animate-component.html

**Comment by srukshan98** [comment]
Thank you, Now it works

**Comment by ducvu212** [comment]
![image](https://user-images.githubusercontent.com/20634152/158605558-32a88886-a1a4-42c6-b3be-d72ca252c6d1.png)
i get an error like image for mat-datepicker in spite of i imported other module in root module.ts file and remote module.ts. @alexanderwiebe can you help me :(
