### ISSUE TITLE
docs: Add missing $theme to theming docs

### ISSUE THREAD

**Issue by chsami** [angular/components#24405]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I get an runtime error. Following the official document guide on using scss variables in your project: https://material.angular.io/guide/theming-your-components. 

![image](https://user-images.githubusercontent.com/23292806/153752764-88ad051c-48f7-411a-8186-bec3b7ce853e.png)

### Reproduction

Steps to reproduce:
1.  Add the following code to your styles.scss

```
@use 'sass:map';
@use '@angular/material' as mat;

$color-config: mat.get-color-config($theme);
$primary-palette: map.get($color-config, 'primary');
$accent-palette: map.get($color-config, 'accent');
$warn-palette: map.get($color-config, 'warn');
$is-dark-theme: map.get($color-config, 'is-dark');
```

2.  Run project

### Expected Behavior

No errors

### Actual Behavior

![image](https://user-images.githubusercontent.com/23292806/153752937-26421735-f9c9-4708-93c6-e487b3da302b.png)

### Environment

- Angular: 13.2.0
- CDK/Material: 13.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

Repo with the a clean angular 13 project to reproduce: https://github.com/chsami/angular13withmaterial

**Comment by crisbeto** [comment]
It looks like you're referring to a variable called `$theme` that doesn't exist.

**Comment by crisbeto** [comment]
I don't think that we should be adding the `$theme` to the guide. It's not supposed to be a complete code snippet, but rather a way to show you how to use the theming APIs once you already have a theme.

**Comment by wagnermaciel** [comment]
In that case, can we close this issue?

**Comment by chsami** [comment]
> I don't think that we should be adding the `$theme` to the guide. It's not supposed to be a complete code snippet, but rather a way to show you how to use the theming APIs once you already have a theme.

I agree, It's very confusing for new people wanting to customize the theme.

**Comment by Piyush132000** [comment]
Hii , Is anybody working on it? Otherwise I could try to fix it if you don't mind.

**Comment by Vaishnavi1411** [comment]
Hi, I am Vaishnavi a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by ZeroGDrive** [comment]
> I don't think that we should be adding the `$theme` to the guide. It's not supposed to be a complete code snippet, but rather a way to show you how to use the theming APIs once you already have a theme.

Okay seeing it was opened again, should we include the theme$ in the code snippet ?

**Comment by MisterMunchkin** [comment]
Hi, Is this still an issue with the docs? Because if it is I'd want to try and contribute. Is the docs something I can edit from forking this repo?
