### ISSUE TITLE
bug(mat-chip): Clicking on disabled chip moves focus to first mat-chip

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#24416]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This issue is reproducing in two different scenario -

- Clicking on disabled chip moves focus to first element
- Clicking inside `mat-chip-list` but outside `mat-chip` moves focus to fist element

### Reproduction

Steps to reproduce scenario 1:

1. Visit https://stackblitz.com/edit/angular-etf7sz-rmwpxh?file=.gitignore
2. Click on disabled mat-chip
3. Focus will move to first mat-chip

Steps to reproduce scenario 2:
1. Visit https://material.angular.io/components/chips/examples#chips-overview
2. Click on white space inside `mat-chip-list` but outside `mat-chip` as shown in below image - 

![image](https://user-images.githubusercontent.com/34937515/154048278-c8262534-987d-4232-8e2e-5b25bcbf780d.png)

3. Focus will move to first mat-chip

### Expected Behavior

Focus should not move to first mat-chip

### Actual Behavior

Focus is moving to first mat-chip

### Environment

- Angular: 13.1.2
- CDK/Material: 13.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. Otherwise focus will be lost completely.

**Comment by iKrishnaSahu** [comment]
@crisbeto even clicking on disabled mat-chip scenario which shifts the focus to first mat-chip is expected?

**Comment by crisbeto** [comment]
Yes since we have nowhere else to move focus. We can't leave it on the disabled chip, because it isn't interactive.
