### ISSUE TITLE
Info missing on mat-buttons hover effect

### ISSUE THREAD

**Issue by carbdias** [angular/components#24424]
### Documentation Feedback

Similarly to what I have mentioned in other issue for radio buttons, there is a lack of information on how to apply CSS on CSS selectors, states, such has the hover effect, that I cannot find the way to override the default behaviour of mat-buttons on mouse over and on mouse click.

Thank you,

Carlota

### Affected documentation page

https://material.angular.io/components/button/overview

**Comment by crisbeto** [comment]
Same answer as #24423. We don't consider this a public API so that's why it's undocumented.

**Comment by carbdias** [comment]
Hello, this question is for buttons and not radio-buttons?

Which would be the class to hide?

Thank you very much for your help,

Carlota


Kristiyan Kostadinov ***@***.***> escreveu no dia segunda,
21/02/2022 à(s) 18:16:
