### ISSUE TITLE
Info missing for Mat-Radio-Buttons CSS selectors

### ISSUE THREAD

**Issue by carbdias** [angular/components#24423]
### Documentation Feedback

Hello, I have a question in general that I have been searching in the internet and I don't find answer anywhere, also in the documentation, so I was hoping you could explain me, how can I access mat-radio-buttons styles for changing (in this case, removing), the outside grey circle that appears on hover effects, and the light-circle that appear arround radio buttons when it has the focus.
This hover/active/focus styles, I can't find the way for changing / personalize them.

Thank you,

Carlota

### Affected documentation page

https://material.angular.io/components/radio/overview

**Comment by crisbeto** [comment]
This isn't something we generally document, because it's an implementation detail and can change between versions. For the radio specifically, you can hide the circle by setting `display: none` on `.mat-radio-button .mat-ripple-element`, but it's at your own risk.
