### ISSUE TITLE
bug(mat-tab-group): preserveContent not working 

### ISSUE THREAD

**Issue by stiles-j** [angular/components#24432]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

[preserveContent] does not work.  Even in the Angular Material online documentation the [preserveContent] input is not working as expected.  

### Reproduction

Steps to reproduce:
1. Create a mat-tab-group with at least two tabs where one of the tabs content contains an iframe 
2. Change tabs, the content in the iframe will not continue to play, or will the content stay loaded in the DOM

### Expected Behavior

The content in the hidden tab containing the iframe should continue to play and continue to exist in the DOM

### Actual Behavior

The content in the iframe stops playing and is removed from the DOM 

### Environment

- Angular: 13.1.3
- CDK/Material: 13.2.2
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The first version that has the feature is `14.0.0-next.2`, but it looks like you're on 13. The docs currently have an issue where they're showing the API docs for the next feature. They'll be fixed once we release https://github.com/angular/material.angular.io/pull/1123.
