### ISSUE TITLE
bug(mat-form-field): PLACEHOLDER IS EMPTY BY DEFAULT

### ISSUE THREAD

**Issue by daniel-seitz** [angular/components#24444]
Please look at the
### Full Explanation [here](https://github.com/angular/components/issues/23893#)

This is either a bug or the documentation should be changed. 

[Here](https://material.angular.io/components/form-field/overview) it states:
"If you want to create a legacy form field with a placeholder but no label, **you will need to specify an empty label** to prevent the placeholder from being promoted."

Together with this code:
```
<mat-form-field>
  <mat-label></mat-label>
  <input placeholder="Just a placeholder">
</mat-form-field>
```

However **the `<mat-label></mat-label>` prevents** the placeholder to be **displayed**.

Current Solution: Remove the mat-label
```
<mat-form-field>
  <input placeholder="Just a placeholder">
</mat-form-field>
```

**Comment by crisbeto** [comment]
As far as I can tell the docs mentioned here don't exist anymore. Closing.
