### ISSUE TITLE
feat(all components): Material You/3

### ISSUE THREAD

**Issue by danitag78** [angular/components#24447]
### Feature Description

Hi, I tried to use @angular/material-experimental thinking it was ready to Material You, but I see that it is not. From what I read on the Material Design site, the mdc- components are still those of Material 2.0, while for version 3 it is necessary to implement the mwc- components
Have you planned to implement these components?

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/22738.
