### ISSUE TITLE
bug(material/input): name property setting overrides developer defined name property

### ISSUE THREAD

**Issue by tthrash** [angular/components#24463]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v13.1.2

### Description

This [change](https://github.com/angular/components/commit/feac08f13843e3476245535a7fa5f3dfee04b027) broke a lot of code. The issue is tons of code was adapted to the fact that Angular Material input was not setting name attribute, so they directly set it themselves. Now with this change Angular Material Input overrides that.

For example, see [Covalent Dynamic Forms Input](https://github.com/Teradata/covalent/blob/main/src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html)

### Reproduction

Steps to reproduce:
1. Set name attribute on a mat-input field directly with `[attr.name]="name"`
2. Try to access element by name attribute, such as in tests.

### Expected Behavior

If name attribute is directly set, then Angular Material Input needs to set name attribute more carefully.

### Actual Behavior

Angular Material Input overrides name attribute directly set by user of mat-input.

### Environment

- Angular: 13.2.2
- CDK/Material: 13.2.2
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by tthrash** [comment]
Yep, I understand that. However, my team is using this Covalent dynamic forms library in our project and that library is infrequently updated. I'm unsure when they will release an update that will fix it. We were hoping this could be fixed in Angular Material in a patch release, so we don't need to revert updates or fork the library to have this fixed if Covalent does not release an update soon that fixes it.

**Comment by andrewseguin** [comment]
Sorry @tthrash but we do not plan to have any more patch releases before the next major
