### ISSUE TITLE
bug(Expansion Panel): Expansion Panel is set to closed, but is open and then gets closed being inside the Stepper

### ISSUE THREAD

**Issue by nilokadnedzar** [angular/components#24480]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When you have a **closed** Expansion Panel as part of the Stepper it is open and then gets closed. It should be closed right away.

_This only happens when the default animation of the Stepper is enabled._

### Reproduction

Steps to reproduce:
1. Put a **closed** Expansion Panel into the first step of the Stepper
2. Keep default animation enabled of Stepper
3. Reload app mutiple time

### Expected Behavior

Expansion Panel should be closed right away.

### Actual Behavior

Expansion Panel is open for some milliseconds and then gets closed.

### Environment

- Angular: 13.2
- CDK/Material: 13.2.4
- Browser(s): Chrome 98.0.4758.109
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Monterey 12.2.1

**Comment by zarend** [comment]
Hello, we took a look at this and couldn't reproduce. Could you please provide a stackblitz reproduction of the issue?

**Comment by crisbeto** [comment]
This should be the same root cause as https://github.com/angular/components/issues/22785.
