### ISSUE TITLE
feat(snackBar): allow mat-icon to be used by default

### ISSUE THREAD

**Issue by rbalet** [angular/components#24501]
### Feature Description

When opening a snackBar, it could be useful to be able to add an icon to it that will use the mat-icon per default. 

```typescript
this._snackBar.open('Changes saved', 'ok', {
      duration: 2000,
      verticalPosition: 'top',
      icon: 'check_circle' // <-- Here
})
```

### Use Case

Added at the beginning of the container, this could be displayed as follow.

![image](https://user-images.githubusercontent.com/44493964/156331610-b10a288a-e5d3-4fe9-b1b7-dd2ab27a6009.png)

## Pro
* Google now have plenty of icon
* Icon are faster to being analyzed by a user than a text, snackbar are meant to be displayed for a short amount of time. Icon will help to improve the UX a lot.

_I can make a PR, if this issue is accepted_

**Comment by crisbeto** [comment]
We're following the Material Design specification which explicits mentions that icons shouldn't be used inside snack bars.

See: https://material.io/components/snackbars#anatomy
<img width="804" alt="image" src="https://user-images.githubusercontent.com/4450522/156361986-c7623de6-c88e-4cd2-b6cd-02ed71621d8b.png">

**Comment by rbalet** [comment]
@crisbeto Thanks for your quick response. I wasn't aware of this rules.
