### ISSUE TITLE
SassError: Can't find stylesheet to import: "@import '~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';"

### ISSUE THREAD

**Issue by andvasp** [angular/components#24537]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.0.0

### Description

The system cannot find the file style file. I need to include the node_modules in the path to work. Is this right way to solve this problem?

From: @import '~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
To:   @import 'node_modules/@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';

styles.css
@import '@angular/material/theming';
@import '~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss'; // Error here

I found this issue https://github.com/angular/components/issues/23889 but it refers to not find the file at **~@angular/material**. This works for me using **@angular/material** but using another path different from @angular, it does not.

### Reproduction

Steps to reproduce:
1. Include a reference for a style file that exists in node_modules but not in an angular directory.

clone the project https://github.com/kuhnroyal/mat-datetimepicker/tree/v9.0.33
npm install --save @mat-datetimepicker/core --legacy-peer-deps
Uncomment the line 19 and comment the line 20 at file https://github.com/kuhnroyal/mat-datetimepicker/blob/v9.0.33/src/styles.scss
ng serve

### Expected Behavior

Compilation without error.

### Actual Behavior

 Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
19 │ @import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\styles.scss 19:9  root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
19 │ @import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\styles.scss 19:9  root stylesheet
    at tryRunOrWebpackError (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\HookWebpackError.js:88:9)
    at __webpack_require_module__ (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:5023:12)
    at __webpack_require__ (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:4980:18)
    at C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:5051:20
    at symbolIterator (C:\Temp\mat-datetimepicker\node_modules\neo-async\async.js:3485:9)
    at done (C:\Temp\mat-datetimepicker\node_modules\neo-async\async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (C:\Temp\mat-datetimepicker\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Temp\mat-datetimepicker\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:4958:43
    at symbolIterator (C:\Temp\mat-datetimepicker\node_modules\neo-async\async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
19 │ @import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\styles.scss 19:9  root stylesheet
    at Object.<anonymous> (C:\Temp\mat-datetimepicker\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!C:\Temp\mat-datetimepicker\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!C:\Temp\mat-datetimepicker\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[5].rules[1].use[0]!C:\Temp\mat-datetimepicker\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].rules[1].use[1]!C:\Temp\mat-datetimepicker\src\styles.scss:1:7)
    at C:\Temp\mat-datetimepicker\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:432:11
    at Hook.eval [as call] (eval at create (C:\Temp\mat-datetimepicker\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Temp\mat-datetimepicker\node_modules\tapable\lib\Hook.js:14:14)
    at C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:5025:39
    at tryRunOrWebpackError (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\HookWebpackError.js:83:7)
    at __webpack_require_module__ (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:5023:12)
    at __webpack_require__ (C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:4980:18)
    at C:\Temp\mat-datetimepicker\node_modules\webpack\lib\Compilation.js:5051:20
    at symbolIterator (C:\Temp\mat-datetimepicker\node_modules\neo-async\async.js:3485:9)

Generated code for C:\Temp\mat-datetimepicker\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!C:\Temp\mat-datetimepicker\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!C:\Temp\mat-datetimepicker\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[5].rules[1].use[0]!C:\Temp\mat-datetimepicker\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].rules[1].use[1]!C:\Temp\mat-datetimepicker\src\styles.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n   ╷\n19 │ @import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';\r\n   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n  src\\styles.scss 19:9  root stylesheet");

### Environment

Angular CLI: 13.2.4       
Node: 14.17.1
Package Manager: npm 8.5.2
OS: win32 x64

Angular: 13.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
ng-packagr                      13.2.1
rxjs                            7.5.4
typescript                      4.5.5

**Comment by andvasp** [comment]
I found this issue here https://github.com/angular/components/issues/23896. But the problem is for another import that is not from angular.

**Comment by crisbeto** [comment]
`@mat-datetimepicker` isn't maintained in this repository or by our team. Please file the issue in the relevant one.

**Comment by andvasp** [comment]
Hi @crisbeto!

Thanks for your time. The **@mat-datetimepicker** is just one example. What I am reporting here is angular cannot import an scss file inside a module that exists. To work I need to include node_modules in the path. It was working before in previous version.

If this behavior is expected now, I agree that should be closed but I don't think it should be.


```
// styles.css
@import '@angular/material/theming';
@import 'existing-style-file-in-node_modules.scss'; // Error here
@import 'node_modules/existing-style-file-in-node_modules.scss'; // Works properly
```

Thanks in advance if you can analyze this again and let me know if this is the behavior from now.

**Comment by crisbeto** [comment]
The `@import 'existing-style-file-in-node_modules.scss';` import fails, because it looks like a relative file path so the Sass loader doesn't know to look for it in the node_modules

**Comment by andvasp** [comment]
Ok. I just thought that this could continue working. All code below searches inside node_modules but the last one not because is a scss file.

Thanks!
```
@import "@angular/material/prebuilt-themes/indigo-pink.css";
@import 'bootstrap/dist/css/bootstrap.css';
@import 'jstree/dist/themes/default/style.css';
@import "material-design-icons/iconfont/material-icons.css";
@import '@angular/material/theming';
@import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss'; // Just here does not work.
```
