### ISSUE TITLE
bug(theming): elevation helpers not working when applied directly to components

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#24549]
### Description

I want to replace the current elevation of mat-card (that has elevation of 1), since it doesn't match the elevation of mat-expansion-panel (that has elevation of 2).

If i try using the elevation helpers to override the elevation of card like the example below, the elevation is ignored, and the current elevation (1) is used.

```
@import '~@angular/material/theming';

mat-card {
  @include mat-elevation(2);
}
```

Updating the elevation helpers to use a `!important` would probably fix this issue.

### Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-wkvanc?file=src/app/card-overview-example.scss)

### Expected Behavior

It should override the elevation of mat-card.

### Actual Behavior

The elevation helper is ignored.

### Environment

- Angular: 13.2
- CDK/Material: 13.2
- Browser(s): Chrome
- OS: win32 x64

**Comment by lekhmanrus** [comment]
Like a temporary workaround you could use ([StackBlitz](https://stackblitz.com/edit/angular-wkvanc-hekkvh?file=src%2Fapp%2Fcard-overview-example.scss)):
```scss
@use '@angular/material' as mat;

mat-card:nth-child(n) {
  @include mat.elevation(20);
}
```

**Comment by crisbeto** [comment]
Usually we keep the specificity pretty low, but it's higher on the card in order to allow class overrides. E.g. you can set the `mat-elevation-z2` class directly on `mat-card` to change the default. If you want to use the mixin, you should bump up the specificity. I'm closing the issue, because things are working as expected.
