### ISSUE TITLE
docs-bug(Google Maps): how do you disable the default UI in Angular?

### ISSUE THREAD

**Issue by FANMixco** [angular/components#24573]
### Documentation Feedback

I cannot find any example of the equivalent for this function:

https://developers.google.com/maps/documentation/javascript/examples/control-disableUI?hl=en

![image](https://user-images.githubusercontent.com/1666156/157847703-fa83be84-2b28-41ba-be13-470f748f2865.png)

It fails or something is not exposed.

### Affected documentation page

https://github.com/angular/components/tree/master/src/google-maps#readme

**Comment by crisbeto** [comment]
You should be able to use `[options]={disableDefaultUI: true}`.

**Comment by FANMixco** [comment]
Hi @crisbeto, this should be added in the documentation as suggested.
