### ISSUE TITLE
bug(mat-mdc-slider): thumb should use % instead of px

### ISSUE THREAD

**Issue by tomasdev** [angular/components#24590]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

https://stackblitz.com/edit/angular-us2jqe-a7chp1?file=src%2Fapp%2Fslider-overview-example.ts

The thumb is not correctly positioned when resizing the container of a mat-mdc-slider. However, the track is.

### Reproduction

Steps to reproduce:
1. Have a mat-mdc-slider with CSS `width: 100%`
2. Resize it's container with any means other than window resize (i.e., a UX could have a panel that pushes content meaning the container will be less wide)

<img width="614" alt="Screen Shot 2022-03-14 at 4 21 19 PM" src="https://user-images.githubusercontent.com/364033/158254712-28f08a36-8faf-481f-aee4-8ac555be769a.png">

### Expected Behavior

Thumb and track are always aligned

### Actual Behavior

Thumb and track stop being aligned

### Environment

- Angular: 13
- CDK/Material: 13
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
This is an issue in MDC, but we should be able to handle it on our side as well.
