### ISSUE TITLE
bug(Drag and Drop): Adding items to a dropList while dragging breaks cdkDrag element layout

### ISSUE THREAD

**Issue by BenRacicot** [angular/components#24593]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Adding items to the dragList element while dragging causes miscalculation in their layout.

I've seen that "[infinite scrolling isn't supported](https://github.com/angular/components/issues/19003)". Combining the virtual scroller CDK seems like at least a todo-worthy feature. 

Either way this issue is specifically regarding a bug that occurs when adding items to a dropList array (while dragging) breaks the appearance and usability of that list.

### Reproduction

Steps to reproduce: [Repro](https://stackblitz.com/edit/angular-6mmern?file=src%2Fapp%2Fcdk-drag-drop-connected-sorting-example.ts)
1. drag any item in the Todo list to the bottom of the list to push an additional 10 items onto the array
2. continue dragging to see that some drag elements are now of varying heights and drop zones are overlapped.

### Expected Behavior

Manipulating an array which drives drag and drop list data does not break the layout in any scenario.

### Actual Behavior

Broken calculation of layout.

### Environment

    "@angular/animations": "~13.0.0",
    "@angular/cdk": "13.2.6",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/material": "13.2.6",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

**Comment by crisbeto** [comment]
This is the same root cause as https://github.com/angular/components/issues/14703. `cdk/drag-drop` "locks in" the dimensions of the container at the start of the dragging sequence for performance reasons.
