### ISSUE TITLE
help(cdk stepper): how add state step to ngfor steps

### ISSUE THREAD

**Issue by SrgGs** [angular/components#24598]
### What are you trying to do?

`      <li
        *ngFor="let step of steps; let i = index"
        (click)="selectStepByIndex(i)"
        [class.active]="selectedIndex === i"
      >
        <ng-container [ngTemplateOutlet]="step.stepLabel.template"></ng-container>
      </li>`
      
      
how to add add step state?

in cdk it is not possible only in mat :/ 

### What troubleshooting steps have you tried?

How add 

### Reproduction

Steps to reproduce:
1. 
2. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by SrgGs** [comment]
in cdk? nope :)

**Comment by andrewseguin** [comment]
This request is missing reproduction or a link to a stackblitz showing what you have tried. Feel free to open a new issue with more information that would allow us to quickly diagnose what you are attempting.
