### ISSUE TITLE
docs-bug(mat-autocomplete): Incorrect tab title for optgroup example code

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#24604]
### Steps to Reproduce
1. Go to the [Autocomplete optgroup Example](https://material.angular.io/components/autocomplete/examples#autocomplete-optgroup).
2. Click the "View Code" button

### Result
One of the tabs for viewing the code reads `./autocomplete-optgroup-example.html`.

<img width="1366" alt="Screen Shot 2022-03-16 at 8 46 07 AM" src="https://user-images.githubusercontent.com/25158423/158630610-fbc825e4-fa12-46b0-94ee-1dbc52c49589.png">

### Affected documentation page

https://material.angular.io/components/autocomplete/examples#autocomplete-optgroup

**Comment by AlirezaEbrahimkhani** [comment]
@wagnermaciel 
I think this problem is solved by this PR #24626.

**Comment by crisbeto** [comment]
Looks like the related PR was merged. Closing.
