### ISSUE TITLE
Change color on mat-radio-button in disabled state

### ISSUE THREAD

**Issue by RListerberg** [angular/components#24603]
### Feature Description

Hi!
Maybe I'm missing that this is already possible to do but is it possible to change the color of a mat-radio-button that's set in a disabled state? Or does the disabled state overwrite all css which is applied to it?

Currently it turns the radiobutton into a slighty faded out gray but I would like to have it in a slighty faded out red.

### Use Case

We would like to use this in a feature where we are comparing two environments values where the options are the same but the values might differ between the environments, being false in one and true in the other. So blue (primary in own) and red (disabled, warn in the other) next to each other in a comparison feature.

**Comment by andrewseguin** [comment]
Unfortunately this will not be supported since the Material spec gives us the guidance for what should be colored by the theme. I recommend just using a custom CSS override to set it.
