### ISSUE TITLE
bug(form field): using *ngif on a form field breaks harness in tests

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/components#24619]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `*ngIf` directive on form field it somehow messes up harness which cannot find the component.
Please see the [Stackblitz demo](https://stackblitz.com/edit/angular-2nql7m?file=src/app/form-field-harness-example.html)

### Reproduction

Steps to reproduce:
1. [Run stackblitz](https://stackblitz.com/edit/angular-2nql7m?file=src/app/form-field-harness-example.html)
2. 

### Expected Behavior

no error 

### Actual Behavior

```
Error: Failed to find element matching one of the following queries:
(MatFormFieldHarness with host element matching selector: ".mat-form-field" satisfying the constraints: host matches selector "#with-errors")
```

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by geromegrignon** [comment]
Hi @GeorgeKnap,

The proper syntax for the structural directive is `*ngIf`, not `*ngif`.
By fixing it, the test succeeds.

**Comment by crisbeto** [comment]
Closing since it's a user error. There's also this log in the console indicating that it's incorrect:

```
ERROR: 'NG0303: Can't bind to 'ngif' since it isn't a known property of 'mat-form-field'.'
```
