### ISSUE TITLE
bug(mat-chip): Ripple overflows on Safari

### ISSUE THREAD

**Issue by ovlad** [angular/components#24624]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The ripple generated by clicking on a mat-chip element overflows.

### Reproduction

Steps to reproduce:
1. Enter from a Safari browser on the official Angular Material docs page of the mat-chip component (https://material.angular.io/components/chips/examples)
2. Click on any of the chips

### Expected Behavior

The ripple to not overflow.

### Actual Behavior

The ripple overflows.

### Environment

- Angular: 13.3.0
- CDK/Material: -
- Browser(s): Safari v15.2
- Operating System (e.g. Windows, macOS, Ubuntu): macOS v12.1

**Comment by crisbeto** [comment]
Sounds like something that'll be solved by https://github.com/angular/components/pull/21495.
