### ISSUE TITLE
bug(mat-button): Many buttons are losing their border in high contrast (forced-colors) mode

### ISSUE THREAD

**Issue by alicequiros** [angular/components#24661]
### Is this a regression?

- [ ? ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Uncertain

### Description

Many buttons (such as mat-button and mat-flat-button) lack a border in high contrast mode on Google Chrome. This makes it difficult for users who are vision impaired or who prefer HC mode to identify the buttons as interactive components.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/81990996/159955840-0bc40a32-3ca1-4e51-83a0-8113b100902f.png">

### Reproduction

Steps to reproduce:
1. Enable forced-colors:active in Google Chrome (see [this link](https://developer.chrome.com/blog/new-in-devtools-98/#forced-colors))
2. Navigate to button demos at https://material.angular.io/components/button/overview
3. Observe that almost none of the buttons have borders

### Expected Behavior

I expect the buttons to have a border or other visual indicator that makes them easy to identify

### Actual Behavior

The buttons lack a border, causing them to resemble plain text

### Environment

- Angular: 13.3.1 (as per demo page)
- CDK/Material:
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by crisbeto** [comment]
Did you refresh after you enabled high contrast mode? Here's what they look like for me:
![Button__Angular_Material_-_Google_Chrome_2022-03-24_23-14-18](https://user-images.githubusercontent.com/4450522/160019016-d003ed19-dda5-4d5e-a07b-b1acf456cc87.png)

**Comment by crisbeto** [comment]
Closing since this works if there's been a refresh after high contrast mode has been enabled.
