### ISSUE TITLE
docs-bug(CHANGELOG): changelog does not document all breaking changes

### ISSUE THREAD

**Issue by amayer42** [angular/components#24684]
### Documentation Feedback

Note: This is a documentation bug in the `changelog.md` file, not in `material.angular.io` itself.

I am currently upgrading one of my company's Angular applications from v11 to v12 and noticed that one of their internally published packages was depending upon an export (`'MAT_STEPPER_GLOBAL_OPTIONS'` from `'@angular/cdk/stepper'`). I assumed that this was a deprecation and went searching the changelog for notice of the deprecation so that I could be sure of what change needed to be made. Upon searching the changelog, I could not find a deprecation/breaking change related to this. However, I did find this PR, https://github.com/angular/components/pull/21901, which seems to describe the deprecation.

I know that you all utilize automation to generate your changelog, so I was confused as to how this had been missed. I think that it's because the commit message contains the text "BREAKING CHANGES:" rather than "BREAKING CHANGE:".

I wanted to make a note of this to see if you all would manually update the `changelog.md` file to include this as a breaking change and perhaps audit your PRs to see if anything else may have been accidentally missed in the past?

### Affected documentation page

https://github.com/angular/components/blob/master/CHANGELOG.md

**Comment by andrewseguin** [comment]
Thanks - it seems that v12 in particular missed a lot of breaking changes and I'm wondering if that's due to manual edits to the CHANGELOG when we released. @devversion Do you know whether the changelog automation looks at both `BREAKING CHANGES:` and `BREAKING CHANGE:`?

**Comment by devversion** [comment]
@andrewseguin I fixed this some time ago with https://github.com/angular/dev-infra/commit/233967980d1a410f7cd146983529b802b3c477da. Unfortunately this wasn't available for v12, but is now available going forward.

**Comment by amayer42** [comment]
@devversion thank you for addressing it and @andrewseguin thank you for double checking. Glad to hear that this will be better checked moving into the future.
