### ISSUE TITLE
error sass in _theming.scss after angular material version update

### ISSUE THREAD

**Issue by Glazebnaya-Kristina** [angular/components#24680]
### What are you trying to do?

After update angular material I get an error

### What troubleshooting steps have you tried?

I'm updated node-sass to 7.0.1
I don't understand to do

<img width="439" alt="image" src="https://user-images.githubusercontent.com/46931114/160463435-009bd78f-ae15-4bfa-8fe7-3c7e2d980f8c.png">

### Reproduction

Steps to reproduce:
1.  Update angular/angular material to 13v

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This error can happen if the palette that you're passing into the Angular Material theming mixins is incomplete.

**Comment by Glazebnaya-Kristina** [comment]
> Эта ошибка может произойти, если палитра, которую вы передаете в миксины темы Angular Material, неполная.

yes thanks, I found it. By default, the function assigned 700, but I didn’t have such a field
