### ISSUE TITLE
feat(mat-form-field): Remove the label spacing or the center value if the label is not present.

### ISSUE THREAD

**Issue by infacto** [angular/components#24688]
### Feature Description

**Form field with label**
```html
<mat-form-field>
  <mat-label>Label</mat-label>
  <input matInput>
</mat-form-field>
```
![default](https://user-images.githubusercontent.com/60390085/160569245-c3b3aeaf-c491-45c4-90e2-4eaa9d451d41.png)

**Form field without label (actual)**
```html
<mat-form-field>
  <input matInput>
</mat-form-field>
```
![no-label](https://user-images.githubusercontent.com/60390085/160569255-ebe0549f-f8ab-4c4b-993c-6b02950be12f.png)

**Form field without label (expected)**
```html
<mat-form-field>
  <input matInput>
</mat-form-field>
```
![expected](https://user-images.githubusercontent.com/60390085/160569254-5f335468-1e9d-4ca7-9bda-efba6bf8d3ac.png)
(remove mat-label reserved space)
or
![expected2](https://user-images.githubusercontent.com/60390085/160570073-c08cae28-5ee3-450c-afb7-68cc0b6f01d1.png)
(center the value like the mat-label does)

We could add an optional attribute for `mat-form-field` like `label="none"` or something like this.

(all inputs are `appearance="fill"`, the new default, currently set in `MAT_FORM_FIELD_DEFAULT_OPTIONS`)

### Alternative

Just give access over CSS for example via SDOM [part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part).

### Use Case

Using inputs on context without label required.

Due to different themes on GitHub, this is probably more visible:
![collage](https://user-images.githubusercontent.com/60390085/160574270-5c0d4e3f-fca1-401a-b5a3-62ce7951e7be.png)

**Comment by crisbeto** [comment]
An input without a label is generally discouraged due to poor accessibility. That being said, you can get a similar look with the MDC-based form field which supports dense form fields.

**Comment by acohenOT** [comment]
@crisbeto a common use case would be when implementing a custom label outside of the form field (linking them with "for" attribute).

**Comment by andrewseguin** [comment]
Have you tried using the MDC-based form field with a higher density setting? That might achieve what you are looking for. 

In general I don't expect us to change this since we try to stick with the Material Design spec and not allow too much deviation natively

**Comment by rubper** [comment]
> An input without a label is generally discouraged due to poor accessibility. That being said, you can get a similar look with the MDC-based form field which supports dense form fields.

yes, but that doesn't mean that you must use Material's labels always
I agree with this change, we need more support for custom labels

**Comment by nzbin** [comment]
I have created a form-group component ([online demo](https://ng-matero.github.io/extensions/components/form-group/overview)) in the [Material Extensions library](https://github.com/ng-matero/extensions). It's very easy to use. In fact, you can customize the form field styles by yourself.

**Comment by mmalerba** [comment]
As mentioned above, this is supported by using denser form-fields (see example here: https://stackblitz.com/edit/63zz66?file=src%2Ftheme.scss) beyond that I don't think we plan to add additional APIs around this use case
