### ISSUE TITLE
bug(Mat-Form-Field): Angular Material form field Long label overlapping with input text

### ISSUE THREAD

**Issue by nikhil4326** [angular/components#24685]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular material form field label overlaps with user entered text, Also long labels with fields have issue with responsiveness. 

### Reproduction

Check stackblitz link: https://stackblitz.com/edit/angular-ar2ulq

### Expected Behavior

 Complete label should be visible, it should not get shrink.

### Actual Behavior

Label is getting shrink or not appearing on the screen

### Environment

- Angular: 9.2.4
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This custom style is breaking it:

```
.mat-form-field-label {
  white-space: normal !important;
}
```

Closing the issue since generally we don't encourage overrides like this.

**Comment by nikhil4326** [comment]
Even if we remove the override what would be other option?

**Comment by crisbeto** [comment]
I don't follow. Removing the override fixes the issue because the text doesn't wrap anymore.

**Comment by nikhil4326** [comment]
Removing override fixes the overlap issue, but it doesn't fix the label issue as well. Complete label should appear on screen. If not, How end user will read the complete  field label? (if it long to appear on screen). check stackblitz: https://stackblitz.com/edit/angular-ar2ulq

**Comment by crisbeto** [comment]
The Material Design spec doesn't recommend splitting it across multiple lines or truncating, but rather keeping the label short to begin with. The truncation is a fallback in case a really tall label does come in.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/4450522/160999170-9fcbf63b-6524-4fad-9c12-d1d46244f909.png">
