### ISSUE TITLE
bug(matTooltip): tooltip doesn't disappear when mouseleave the selector

### ISSUE THREAD

**Issue by xavier-che** [angular/components#24689]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.13

### Description

When mouseleave the selector, the tooltip should disappear, it would, but, in the case that the mouse is **between the selector and the tooltip**, the tooltip won't disappear in the latest version

### Reproduction

Steps to reproduce:
1. Create button with tooltip 
2. Mouse hover between the selector and the tooltip

### Expected Behavior

the tooltip disappears

### Actual Behavior

the tooltip didn't disappear

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by volvachev** [comment]
Hi, the previous behaviour has been changed (#4942). Now `tooltip' does not disappear by default when the cursor moves to it.

If you want the previous behavior, use the `MAT_TOOLTIP_DEFAULT_OPTIONS` token and set `{disableTooltipInteractivity: true}`.

**Comment by xavier-che** [comment]
@volvachev thanks! it works!

_**app.module.ts**_
```
import { MAT_TOOLTIP_DEFAULT_OPTIONS, MatTooltipDefaultOptions } from '@angular/material/tooltip';

export const myCustomTooltipDefaults: MatTooltipDefaultOptions = {
    showDelay: 0,
    hideDelay: 0,
    touchendHideDelay: 1500,
    disableTooltipInteractivity:true 
};

providers: [
    { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: myCustomTooltipDefaults }
],
```

**Comment by crisbeto** [comment]
Closing since it sounds like it's working as expected.
