### ISSUE TITLE
docs-bug(tabs): Tabs documentation doesn't reflect latest changes

### ISSUE THREAD

**Issue by zelliott** [angular/components#24694]
### Documentation Feedback

https://github.com/angular/components/pull/24316 was submitted over a month ago to update some Material tabs documentation. I remember specifically checking and seeing this documentation live on https://material.angular.io/components/tabs/overview, a week or so after the PR was submitted.

Now, however, if I go to https://material.angular.io/components/tabs/overview, I do not see the changes in that PR reflected.

### Affected documentation page

https://material.angular.io/components/tabs/overview

**Comment by andrewseguin** [comment]
Odd, thanks for pointing this out. We are following a different process for our documentation releases and I wonder if there's a mixup going on. @devversion Looks like the content isn't matching the latest on the docs

**Comment by devversion** [comment]
@zelliott I've sent a patch-port to make the docs change visibile in material.angular.io until we hit v14. Can you please review & confirm that the corresponding runtime changes are part of v13.3.x? (I was looking for `MatTabNavPanel` and it exists there)

**Comment by zelliott** [comment]
Yep, if `MatTabNavPanel` exists in 13.3.x, then these docs changes should also be in v13.3.x. LGTM'd your PR.
