### ISSUE TITLE
bug(mat-button): Focus state doesn't pass the Non-Text Contrast Criteria from WCAG 2.1

### ISSUE THREAD

**Issue by manu911** [angular/components#24702]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Current looking of a mat-button in focus state:
![image](https://user-images.githubusercontent.com/26325600/160801998-f3128dce-3b6f-4fb2-8e13-ec92614dcdef.png)

Current looking of a mat-checkbox in focus state:
![image](https://user-images.githubusercontent.com/26325600/160810079-cd31f68f-6957-4b3a-882e-431cd60899c4.png)

Focus state doesn't pass the 1.4.11 Non-Text Contrast Criteria from WCAG 2.1 with the adjacent colors.
It happens with mat-checkbox, mat-radio-button, mat-datepicker-toggle, mat-expansion-panel and some other interactable components.

This criterion mention:

"For active controls any visual information provided that is necessary for a user to identify that a control is present and how to operate it must have a minimum 3:1 contrast ratio with the adjacent colors. Also, any visual information necessary to indicate state, such as whether a component is selected or focused must also ensure that the information used to identify the control in that state has a minimum 3:1 contrast ratio.

This Success Criterion does not require that changes in color that differentiate between states of an individual component meet the 3:1 contrast ratio when they do not appear next to each other. For example, there is not a new requirement that visited links contrast with the default color, or that mouse hover indicators contrast with the default state. However, the component must not lose contrast with the adjacent colors, and non-text indicators such as the check in a checkbox, or an arrow graphic indicating a menu is selected or open must have sufficient contrast to the adjacent colors."

Going further in the criterion we can see an example that states it using a graphical example (in this case a checkbox but it is applicable for any interactable component):
![image](https://user-images.githubusercontent.com/26325600/160797376-10d91823-c408-4d5a-88eb-44d9e4b34237.png)

Source: https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast

### Reproduction

Steps to reproduce:
1. Implement the component mat-button
2. Use tab key to moves to the component
3. Check the contrast ratio between the background of the page and the background of the button in focus state.

### Expected Behavior

The best approach is using an outline, leaving the default outline managed by the user agent it will pass the criterion, as mentioned in this:

"Success Criterion [1.4.11 Non-text Contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast) (Level AA): The visual [presentation](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-presentation) of the following have a [contrast ratio](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-contrast-ratio) of at least 3:1 against adjacent color(s):

User Interface Components
Visual information required to identify [user interface components](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-user-interface-component) and [states](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-state), **except for inactive components or where the appearance of the component is determined by the user agent** and not modified by the author; "

### Actual Behavior

Current looking of a mat-button in focus state:
![image](https://user-images.githubusercontent.com/26325600/160801998-f3128dce-3b6f-4fb2-8e13-ec92614dcdef.png)

Focus state doesn't pass the 1.4.11 Non-Text Contrast Criteria from WCAG 2.1 with the adjacent colors.

### Environment

- Angular: 
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
Hello, thank you for the detailed investigation. Please use [Strong focus indicators](https://material.angular.io/guide/theming#strong-focus-indicators) to give the focus state more contrast.
