### ISSUE TITLE
docs-bug(datepicker): typo, missing a space in the date format section

### ISSUE THREAD

**Issue by zarend** [angular/components#24708]
### Documentation Feedback

There's a typo in the " Choosing a date implementation and date format settings
" section of the datepicker docs. There is a missing space after "Customizing the parse and display formats".

<img width="887" alt="image" src="https://user-images.githubusercontent.com/7720245/160945292-1003a357-1d08-4397-b8c3-36137d583bc0.png">

### Affected documentation page

https://material.angular.io/components/datepicker/overview

**Comment by zarend** [comment]
This could be a good first-issue for new contributors. :)

**Comment by crisbeto** [comment]
The change was merged. Closing.
