### ISSUE TITLE
bug(google-map): fitBounds need to run in setTimeout to apply

### ISSUE THREAD

**Issue by christophe-mailfert** [angular/components#24703]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Our app use a lot of GoogleMap and duno why the first loading of the map works correctly but all other with the navigation fail to fitBounds.
The only why i found to fix it is to wrap the fitbounds with a setTimeout.

### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/components-issue-wtbvby?file=src%2Fapp%2Fexample-component.ts
2. Without the setTimeout nothing appends
3. With the map update the center

### Expected Behavior

fitbounds without a setTImeout

### Actual Behavior

Need a setTimeout to fitBounds

### Environment

- Angular: 13
- CDK/Material: 13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by andrewseguin** [comment]
The stackblitz is not working - it shows an empty page

**Comment by mloffer** [comment]
This is still a problem.

- `@ViewChild(GoogleMap)` is `undefined` inside `ngAfterViewInit`.
  - Still `undefined` if you reference it inside setTimeout.
- `@ViewChild(GoogleMap)` is `undefined` inside of `GoogleMap.mapInitialized`
  - Finally available if you reference it inside setTimeout.

**Comment by Ritin** [comment]
facing same issue as @mloffer 
@angular/core@17.0.8
@angular/google-maps@17.0.4
GoogleMap and MapPolygon dont work
it works inside onMapClick()  without the need for setTimeout

**Comment by amysorto** [comment]
I am closing this issue since there isn't a reproduction linked and hasn't been updated in a while. Please open a new issue if this is still persisting for you with a reproduction. Thanks!
