### ISSUE TITLE
docs-bug(theme): App background color.

### ISSUE THREAD

**Issue by infacto** [angular/components#24726]
### Documentation Feedback

How to set the `mat-app-background` color? The default color is `#fafafa` which is set in `_core-theme.scss:16`.
This can be use e.g. on `<body class="mat-app-background">`.

```scss
// This does not work:
$light-theme: mat.define-light-theme(
  (
    color: (
      primary: $light-primary,
      accent: $light-accent,
    ),
    background: #ffff00
  )
);

// This does not work:
$background: map-get($light-theme, background);
$background: map_merge($background, (background: $light-background));
$light-theme: map_merge($light-theme, (background: $background));

@include mat.core-color($light-theme);
@include mat.all-component-themes($light-theme);
```

The docs lacks about the background.
Angular Material definitely have a background color. But how to change it in proper way?

My current workaround e.g.: 

```scss
.mat-app-background,
mat-sidenav-container {
  background: #ff0000 !important;
  --mat-app-background: #ff0000 !important;
}
```

Please tell me how to set the background in theme. I'm exhausted. There are some threads on web about this topic. But no solution really works. Did I miss something? 

### Affected documentation page

https://material.angular.io/guide/theming#application-background-color

And btw. the default color of `mat-chip`. But anyway... Perhabs another issue.

**Comment by crisbeto** [comment]
Here's how it's created if you want to do it yourself. It's using all public APIs https://github.com/angular/components/blob/master/src/material/core/_core-theme.scss#L20.
