### ISSUE TITLE
bug(MatFormField): core-styles() mixin writes color, should it be on MDC's color() instead?

### ISSUE THREAD

**Issue by tomasdev** [angular/components#24734]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

(material-experimental)

I'm not sure if this belongs here or at https://github.com/material-components/material-components-web

But!

At https://github.com/material-components/material-components-web/blob/master/packages/mdc-form-field/_mixins.scss there's a color setting:

```
@include feature-targeting.targets($feat-color) {
      @include theme.property(color, text-primary-on-background);
}
```

At https://github.com/angular/components/blob/master/src/material-experimental/mdc-form-field/_form-field-theme.scss there's a color mixin:
```
@mixin color($config-or-theme) {
```

Which in turns means... doing `@include mat.mdc-form-field-theme($theme);` once, and repeating `@include mat.mdc-form-field-color($theme);` per theme (in our case, dark and light) the form fields don't have the right color. The color seems to be set to black, no matter what `$theme` is passed to `mat.mdc-form-field-color`

### Reproduction

Steps to reproduce:
1. Create a new site.
2. Separate `...-theme` suffixed mixins from `...-color` suffixed mixins.
3. Repeat only the color mixins for defining themes, calling the `-theme` only once.

### Expected Behavior

The color mixins provide enough rules to ensure the theme is respected

### Actual Behavior

The Angular Components color mixin is not enough, and text can become black on black, even though `$theme` defines a white foreground palette.

### Environment

- Angular: 12 or 13?
- CDK/Material: 12 or 13?
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
Closing since this code doesn't seem to exist anymore.

**Comment by tomasdev** [comment]
Still an issue at https://github.com/material-components/material-components-web/blob/master/packages/mdc-form-field/_form-field.scss#L43

**Comment by crisbeto** [comment]
AFAIK that just defines the token slot, but the value is set by the theme. Either way, we're in the process if moving away from these structural styles so this should go away on its own soon.
