### ISSUE TITLE
bug(MatInputHarness): Does not properly set negative value when input is type="number"

### ISSUE THREAD

**Issue by Gummiees** [angular/components#24738]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

StackBlitz: https://stackblitz.com/edit/angular-ivy-8xdgnt?file=src%2Fapp%2Fapp.component.spec.ts

This is the same as https://github.com/angular/components/issues/19314. However, since that ticket is locked, a new one must be opened.

### Reproduction

Steps to reproduce:
1. Use `<input type="number">`
2. Set a negative value using the `MatInputHarness.setValue('-1')`
3. Check the value using `MatInputHarness.getValue()`
4. The value returned is `1`

### Expected Behavior

Value should be set to negative number.

### Actual Behavior

Value is transformed into a positive number.

### Environment

- Angular: 13.3.1
- CDK/Material: 13.3.1
- Browser(s): Chrome 100.0.4896.75
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 12.2

**Comment by crisbeto** [comment]
There was a fix for something similar in 13.3.2 via e9734a9c663b0e462e5c3d8ba2126a87aeeb3191. Can you try updating to see if it resolves your issue?

**Comment by Gummiees** [comment]
@crisbeto Thanks for the fast response, but still not working. Updating to the latest versions works if the input is not set to be `type="number"`.

Thanks to the commit you linked, I figured out a way to do a workaround.

This does not work:
```ts
await numberInputHarness.setValue('-1');

expect(numberInputControl.value).toBe(-1); // Fails, says that the value is '1'
```

Yet if I do it as it has been implemented on the test from https://github.com/angular/components/commit/e9734a9c663b0e462e5c3d8ba2126a87aeeb3191, it does work:
```ts
const input = await numberInputHarness.host();
input.sendKeys('-1');

expect(numberInputControl.value).toBe(-1); // Works 🎉 
```

I'd say the bug is not really solved, since when using `setValue()` it is failing, but at least there is a workaround 🙂

**Comment by Gummiees** [comment]
❗ Correction: this was my bad! @crisbeto what you linked actually works. Updating is not throwing an error anymore.

The problem was that I was expecting `'-1'` when the value is set to `-1`, meaning that, indeed, on the latest version the issue has been solved.

Many thanks!
