### ISSUE TITLE
help(Bottom Sheet): Flash of color on click when bottom sheet open <Responsive: Mobile>

### ISSUE THREAD

**Issue by bstaley** [angular/components#24730]
### What are you trying to do?

This is more of a question. 

here's the example: [stackblitz example](https://stackblitz.com/edit/angular-qytaja)

- open bottom sheet
- set responsive to iphone 12
- click anything but the links
- see a flash of (the themed?) color

Why is this happening? Does it maybe have to do with a11y focus or something? Can I turn it off?
![flashing_bottom_sheet](https://user-images.githubusercontent.com/2222437/161583921-4f6a4121-ed2a-4d14-8bf2-be084a43fb28.png)

### What troubleshooting steps have you tried?

- deleting dom to try to narrow it down (if i delete style.css and the overlay, it stops)
- debug events
- look for changes on all elements

### Reproduction

here's the example: [stackblitz example](https://stackblitz.com/edit/angular-qytaja)

Steps to reproduce:
- open bottom sheet
- set responsive to iphone 12
- click anything but the links
- see a flash of (the themed?) color

### Environment

- Angular: 13.0.0
- CDK/Material: 13.3.2
- Browser(s): Chrome 99.0.4
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Do you see this on a real device or is it just in the Chrome simulator? We have some styles to prevent it, but the simulator might be ignoring them.

**Comment by bstaley** [comment]
Alright, just tested on an Android Emulator(AVD) and it's not showing that color. So just must be the Chrome simulator.

**Comment by crisbeto** [comment]
I'll close this assuming it's an issue with the simulator.
