### ISSUE TITLE
google maps - get typeError Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by yaniv33** [angular/components#24742]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

"@types/googlemaps": "^3.39.13",
"@agm/core": "^3.0.0-beta.0",

### Reproduction

set map with the following 

  <agm-circle
    [latitude]="lat + 0.3"
    [longitude]="lng"
    [radius]="50000"
    [fillColor]="'red'"
    [circleDraggable]="true"
    [editable]="true"
  >
  </agm-circle>

### Expected Behavior

no error

### Actual Behavior

keep getting the error 

core.mjs:6485 ERROR TypeError: Cannot read properties of undefined (reading 'then')
    at Observable._subscribe (agm-core.js:299:1)
    at Observable._trySubscribe (Observable.js:37:1)
    at Observable.js:31:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:22:21)
    at agm-core.js:1543:1
    at Map.forEach (<anonymous>)
    at AgmCircle._registerEventListeners (agm-core.js:1542:1)
    at AgmCircle.ngOnInit (agm-core.js:1493:1)
    at callHook (core.mjs:2542:1)

### Environment

Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: yarn 1.17.3
OS: win32 x64

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.2.6
rxjs                            7.4.0
typescript                      4.5.5

- Browser(s):
Chrome

- Operating System (e.g. Windows, macOS, Ubuntu):
WIN 11

**Comment by terencehonles** [comment]
Just a heads up this is not the package for the error you are referring to. That is this one https://github.com/SebastianM/angular-google-maps, I would suggest you look into changing your project to depend on `@angular/google-maps` which is the package you may be expecting to be using and what is contained here.

**Comment by crisbeto** [comment]
Closing since this appears to be using a module that our team doesn't maintain.
