### ISSUE TITLE
bug(tabcontrol): tabcontrol (the header) steals focus since 13.3.0

### ISSUE THREAD

**Issue by BasieP** [angular/components#24748]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.6

### Description

We have a tabcontrol with 2 tabs.
The first tab had some input fields I give focus.

Then after like a full second orso, the tabcontrol steals the focus back, and the first header of the first tabs becomes the active htmlelement on the page.
Therefor I cannot properly set focus on my input element.

I am not very familiair with zonejs and rxjs, but I suspect the following changes the cause of the problem:
https://github.com/angular/components/commit/41320d07e14b405e20b2b8fdca84488547cb4845

### Reproduction

Hard to reproduce. In a simple example it seems to work.

In a our application it doens't.

Differences are perhaps we have a tabgroup with 2 tabs. Both of the tabs contain a control.
the first control contains a form with the input field.

I have a screenshot that could explain a lot about what i think is wrong:
https://snipboard.io/EtQguw.jpg

As you can see I have a method in the component of the first tab.
It focusses on the input field, and registers a 'blur' handler. Which triggers moments after we set the focus.
In the callstack you can see the problem. I just don't know what triggers it..

### Expected Behavior

I expect components to not steal focus, or if they do have an event that says 'now i'm done stealing focus'

### Actual Behavior

after all the events of the tabgroup are done, something triggers a focus steal.

### Environment

- Angular: 13.3.0
- CDK/Material:13.3.0
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by crisbeto** [comment]
The changes from 41320d07e14b405e20b2b8fdca84488547cb4845 only affect the tab header pagination and the alignment of the ink bar, they aren't going to move focus. It's hard to say what else could be going on without a reproduction.

**Comment by zarend** [comment]
Hello @BasieP ,

Thank you for reporting. We are unable to reproduce. I was wondering if we could check with you if this issue requires further action. Could you please provide a stackblitz reproduction of the issue?

Thanks,
Zach

**Comment by zarend** [comment]
Hello @BasieP ,

Thank you for reporting this issue. Unfortunately we are not able to take action if we cannot reproduce it. This might have already been fixed. If the issue persists, please provide reproduction steps or file a new issue report.

- Zach
