### ISSUE TITLE
Ordering issue while placing Elements in CDK Droplist

### ISSUE THREAD

**Issue by danishkhan3621** [angular/components#24750]
### What are you trying to do?

I have to list one is where initially all the options will be there and second one is multiple blanks where one can drag and drop the items, There are two issues which i'm facing 
) when i fill the lists by dragging and dropping the items on blanks first item is dropped at 0th postiion second item is filling the space of 1st location and when i drop the 3rd  item at the 2nd index it interchanges with the 1st index. 
2)  If i drag items one by one it fills the list from 0th index, Is it possible to fill items only at exact location where the user drops the list item

This is the link that i was trying 

https://stackblitz.com/edit/angular-xnirx8 

app.component.html

```
[<div cdkDropListGroup>
<div class="maidropse">
    <span>Thus to describe data, one needs to know the extent of variability. This is given by the measures of dispersion.</span>
    <div cdkDropList [cdkDropListData]="done" class="example-list" cdkDropListSortingDisabled="true" (cdkDropListDropped)="drop($event)">
        <div class="example-box " cdkDrag>{{ done[0] }}</div>
    </div>
    <span> ,are the three commonly used measures of dispersion.</span>
    <div cdkDropList [cdkDropListData]="done" class="example-list" cdkDropListSortingDisabled="true" (cdkDropListDropped)="drop($event)">
        <div class="example-box " cdkDrag>{{ done[1] }}</div>
    </div>

    <span>, and are the three commonly used measures of dispersion.</span>
    <div cdkDropList [cdkDropListData]="done" class="example-list" cdkDropListSortingDisabled="true" (cdkDropListDropped)="drop($event)">
        <div class="example-box " cdkDrag>{{ done[2] }}</div>
    </div>
    <span>  are the three commonly used measures of dispersion.</span>
</div>



<div class="dropbtns pt-3">
    <div cdkDropList [cdkDropListData]="todo" class="" cdkDropListOrientation="vertical" cdkDropListSortingDisabled="true" (cdkDropListDropped)="drop($event)">
        <button class="example-box btn drobtn2 " *ngFor="let item of todo" cdkDrag>{{ item }}</button>
    </div>
  
</div>
</div>](url)
```

app.component.ts

```
import { Component } from '@angular/core';
import {
  CdkDragDrop,
  moveItemInArray,
  transferArrayItem,
} from '@angular/cdk/drag-drop';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  name = 'Angular';
  todo = ['Range', 'interquartile range', 'standard deviation', 'quartile'];

  done = [];

  drop(event: CdkDragDrop<string[]>) {
    if (event.previousContainer === event.container) {
      moveItemInArray(
        event.container.data,
        event.previousIndex,
        event.currentIndex
      );
    } else {
      transferArrayItem(
        event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex
      );
    }
  }
}

```

### What troubleshooting steps have you tried?

I have searched for these issues but could not get the exact solution

### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/angular-xnirx8 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
From what I can tell, this is a problem with your setup, rather than the `cdk/drag-drop` module. You're passing the the same data to all 3 lists so that's why the result doesn't end up in the same place as where you're dropping it.
