### ISSUE TITLE
bug(menu): Using menu in component with CD "OnPush" and *ngIf causing "ExpressionChangedAfterItHasBeenCheckedError"

### ISSUE THREAD

**Issue by hakimio** [angular/components#24764]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.2

### Description

Following error is thrown after opening the menu:
```
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@transformMenu': 'void'. Current value: 'enter'.. 
```

### Reproduction

Steps to reproduce:
1. Create a component which uses `matMenuTriggerFor` directive. Let's call it `cmp1`.
2. Create component `cmp2` with change detection `OnPush`
2. Inside `cmp2` template create html element with `*ngIf` directive (`<div *ngIf="foo"></div>`)
3. Place `cmp1` element inside the element with `*ngIf`

### Expected Behavior

No errors when opening the menu.

### Actual Behavior

Error:
```
NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@transformMenu': 'void'. Current value: 'enter'..
```

### Reproduction demo app
[mat-menu-bug.zip](https://github.com/angular/components/files/8480319/mat-menu-bug.zip)

### Environment

- Angular: 13.2.3
- CDK/Material: 13.2.3
- Browser(s): Chrome 100
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
This isn't enough information to investigate the issue. I tried changing our menu demo app to use `OnPush` and it didn't throw any errors.

**Comment by hakimio** [comment]
@crisbeto yes, the reproduction is a bit more involved than I thought. Sorry for not providing a demo initially. I have now updated the bug description with a link to the demo app (`mat-menu-bug.zip`).
Works fine with `13.2.2` and throws error with `13.2.3`.

**Comment by hakimio** [comment]
@crisbeto did you have some time to check the issue? Do you think it's something that can be fixed on this library side or the issue lies with the way menu component is used in the provided reproduction project?

**Comment by crisbeto** [comment]
I did reproduce it with your zip file, but I haven't had the time to narrow down the root cause.

**Comment by hakimio** [comment]
@crisbeto any plans to look into this at some point?
