### ISSUE TITLE
help(COMPONENT): google-maps

### ISSUE THREAD

**Issue by jacinlowe** [angular/components#24786]
### What are you trying to do?

I am trying to resize the map with css. but for some reason no matter what selector combo i use it will not resize past the default.

### What troubleshooting steps have you tried?

setting height & width with an ngbind and passing null
`
<div class="my-google-map">
<google-map [options]="options" (mapClick)="moveMap($event)" (mapMousemove)="move($event)" [height]="null"
            [width]="null">
<google-map>
</div>
`
`
//map-component.component.scss
.my-google-map{
    .map-container{
      width: 800px;
      height: 600px;
    }
  }

`

### Reproduction

Steps to reproduce:
1. 
2.
https://stackblitz.com/edit/components-issue-gvqfbg?file=src/app/google-map/map-component.component.scss

### Environment

- Angular:
- 13.3.1
- CDK/Material:
- 
- Browser(s):
- all
- Operating System (e.g. Windows, macOS, Ubuntu):
windows

**Comment by lekhmanrus** [comment]
Is that what you are looking for? See [StackBlitz](https://stackblitz.com/edit/components-issue-swiik8?file=src/app/google-map/map-component.component.scss).
```scss
.my-google-map ::ng-deep .map-container {
  width: 100%;
  height: 500px;
}
```

**Comment by jacinlowe** [comment]
> Is that what you are looking for? See [StackBlitz](https://stackblitz.com/edit/components-issue-swiik8?file=src/app/google-map/map-component.component.scss).
> 
> ```css-scss
> .my-google-map ::ng-deep .map-container {
>   width: 100%;
>   height: 500px;
> }
> ```

That worked thank you!!! 
I wish that the documentation had that in there. it kinda gives false hope that it should work by just passing null to the width and height values
