### ISSUE TITLE
bug(mat-select): "mat-select-trigger" breaks the view with 'mat-chip-list' component

### ISSUE THREAD

**Issue by dmytrodemchenko** [angular/components#24796]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.1.1

### Description

With a new update, it started to break the view which is not expected for multiple selections. 
Demo: [https://stackblitz.com/edit/angular](https://stackblitz.com/edit/angular-1qdodn-e9rmoh?file=src/app/chips-autocomplete-example.html)

<img width="432" alt="Screenshot 2022-04-18 at 16 06 23" src="https://user-images.githubusercontent.com/11888586/163812578-410ac009-ae97-4f4a-b804-0f1c2e65dc09.png">

### Reproduction

Provided a demo in description in StackBlitz

### Expected Behavior

Should work as it was previously in 13.1.1 or somehow handle it )

### Actual Behavior

Broken view of the mat-select component. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Chips inside of a select are not an interaction pattern we support, because it doesn't make sense in terms of accessibility. It happened to work in the past by accident.
