### ISSUE TITLE
CDK drag drop not working when we add CSS transform on cdkDragHandle

### ISSUE THREAD

**Issue by pavandixit93** [angular/components#24812]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As per Given UI I want to show cdkDragHandle(**+**) little bit away from drag item, To match GUI I am using CSS transform on cdkDragHandle so that it will placed away from drag items please refer below screenshot. 

I have added specific width on draglist(50px) and CSS transform(-150px) on draghandle, when i am trying to drag and drop item it is not working as expected.

If i remove below css from app.component.css, it works fine,
` .cdk-drop-list {
  width: 50px;
}

.cdk-drag-handle {
  transform: translateX(150px);
}`
![image](https://user-images.githubusercontent.com/21095558/164369715-8f254105-c24e-45f9-bf21-762c3557a3bc.png)

### Reproduction

[Steps to reproduce:
1. Go to (https://stackblitz.com/edit/angular-cdk-drag-drop-sortable-flex-wrap-v2-9v5zik)
2. Drag using (**+**) drag icon
3. Ideally it should drop dragged item to new position

### Expected Behavior

When i am dragging item to new position it should be dragged and dropped to new position.

### Actual Behavior

When i am dragging item to new position it is not getting dropped to new position.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Dragging only works when your cursor overlaps a drop item. It'll work if you move your pointer over another item, rather than over the other handles which are positioned outside of the items (e.g. try moving your cursor above one of the white boxes).

**Comment by pavandixit93** [comment]
@crisbeto Totally agree and i am aware of the scenario, but since we got this UI and we are using grid UI, Is there any out of the box way if i want to achieve without moving cursor above one of the white boxes? 
Like i said i want to keep drag handle away from drag items so i can not assume that every time cursor will be above drag item.

**Comment by crisbeto** [comment]
Not really, the drag&drop can't know that the swapping has to happen even when the cursor is outside of its bounds. You can change your markup instead so the `cdkDrag` is on an element that spans the entire row.

**Comment by pavandixit93** [comment]
Ok thank you @crisbeto I will try this.

**Comment by crisbeto** [comment]
I'm closing this issue since the module is working as expected. It can be reopened if any other issues come up.
