### ISSUE TITLE
bug(mat-chip-list): cdkDropListDropped does not compile.

### ISSUE THREAD

**Issue by grapevinegizmos** [angular/components#24819]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-chip-list fails to compile with error `Argument of type 'Event' is not assignable to parameter of type 'CdkDragDrop<Vegetable[], Vegetable[], any>'.
  Type 'Event' is missing the following properties from type 'CdkDragDrop<Vegetable[], Vegetable[], any>': previousIndex, currentIndex, item, container, and 4 more.ngtsc(2345)`

I get the red squigly on 5, under the `$event` parameter to the drop function.  (The .ts file shown below.)

I've used exactly the same code as is shown in the documentation for the example: Chips Drag and Drop on this page:  [https://material.angular.io/components/chips/examples](url)

Here's what I'm seeing in VSCode:
![image](https://user-images.githubusercontent.com/8684037/164555001-03f221ab-57ab-47e8-b9c6-9ea36801d8ac.png)

code:  
```
<mat-chip-list
class="example-chip"
cdkDropList 
cdkDropListOrientation="horizontal"
(cdkDropListDropped)="drop($event)">
<mat-chip
  class="example-box"
  cdkDrag
  *ngFor="let vegetable of vegetables">
  {{vegetable.name}}
</mat-chip>
</mat-chip-list>
```

### Reproduction

The example works as expected in StackBlitz.

Perhaps this is some kind of configuration error but I dont' see what it is.

Below a screenshot of the .ts file.
![image](https://user-images.githubusercontent.com/8684037/164555680-ef1307bf-8d12-4bb8-a1e3-c8c0b5919e6f.png)

Code:
```
import {CdkDragDrop, moveItemInArray} from '@angular/cdk/drag-drop';
import {Component} from '@angular/core';

export interface Vegetable {
  name: string;
}

/**
 * @title Chips Drag and Drop
 */
@Component({
  selector: 'chips-drag-drop-example',
  templateUrl: './chips-drag-drop-example.html',
  styleUrls: ['./chips-drag-drop-example.scss'],
})
export class ChipsDragDropExample {
  vegetables: Vegetable[] = [
    {name: 'apple'},
    {name: 'banana'},
    {name: 'strawberry'},
    {name: 'orange'},
    {name: 'kiwi'},
    {name: 'cherry'},
  ];

  drop(event: CdkDragDrop<Vegetable[]>) {
    moveItemInArray(this.vegetables, event.previousIndex, event.currentIndex);
  }
}
```

### Expected Behavior

Same as on example web page on material.io for the Chips Drag and Drop example.

### Actual Behavior

Would not compile.  (See above).

### Environment

Here is output from `ng version`

![image](https://user-images.githubusercontent.com/8684037/164555242-b9ba7939-c238-4e4a-a091-b6439a27308b.png)

tsconfig.json in case helpful:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ],
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Comment by crisbeto** [comment]
This would happen if you didn't import the `DragDropModule` into your component's module.

**Comment by grapevinegizmos** [comment]
Yes that's the problem.   The api documentation page on material.if didn't mention it so i didn't know.   Would be helpful to include a note somewhere , unless i missed it thanks.

**Comment by crisbeto** [comment]
This is how the framework works: you have to import the things that you're going to use. I don't think that we have to mention it in each docs page.

**Comment by grapevinegizmos** [comment]
Yeah, I realize now when I looked at the docs again that the import was shown on line 1 of the example.
