### ISSUE TITLE
bug(mat-button): disabled not following html specs

### ISSUE THREAD

**Issue by WilliamChelman** [angular/components#24848]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When making use of `[disabled]` on any sort of `mat-button`, instead of just having `disabled` in the html, we get [disable]="true", which is not correctly following [html specs for boolean attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute).

It is to be noted that, in absence of `mat-button`, `[disabled]` is behaving correctly on `<button>`. I wouldn't be surprised if this had to do with the [boolean coercion being made](https://github.com/angular/components/blob/master/src/material/core/common-behaviors/disabled.ts#L30).

### Reproduction

Steps to reproduce:
1. go to the [stackbliz](https://stackblitz.com/edit/components-issue-ug7qvf?file=src/app/example-component.html)
2. notice the difference in html `disable` attributes between the native button and the material one

### Expected Behavior

`disabled` is following [specs](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute)
```html
<button 
  _ngcontent-nxh-c308="" 
  mat-raised-button="" 
  class="mat-focus-indicator mat-raised-button mat-button-base mat-button-disabled" 
  ng-reflect-disabled="true" 
  disabled>[...]</button>
```

### Actual Behavior

`disabled` attribute is set to `true`
```html
<button 
  _ngcontent-nxh-c308=""
   mat-raised-button="" 
  class="mat-focus-indicator mat-raised-button mat-button-base mat-button-disabled" 
  ng-reflect-disabled="true" 
  disabled="true">[...]</button>
```
`="true"` should not be there in `disabled="true"`

### Environment

- Angular: 11, 12, 13 & 14.next-12
- CDK/Material: 11, 12, 13 & 14.next-12 (tested trough https://material.angular.io/components/button/overview and equivalent for each version)
- Browser(s): Edge 100
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by rothsandro** [comment]
`[disabled]` on a native button binds to the disabled property. The material button binds to the disabled attribute (not the prop) using `[attr.disabled]` ([see code](https://github.com/angular/components/blob/main/src/material/button/button.ts#L71)). The behavior can be reproduced when using `[attr.disabled]="true"` on a native button, it will result in `disabled="true"`.

This was changed because the same code is used for links (`<a>`) which don't have a disabled property (https://github.com/angular/components/pull/15308).

**Comment by jelbourn** [comment]
It's true that button renders `disabled="true"`, but it doesn't have any practical implications AFAIK, so I don't see a compelling reason to change it.
