### ISSUE TITLE
bug(mat-tooltip): flickering issue on mat-tooltips with delay setting

### ISSUE THREAD

**Issue by avatsaev** [angular/components#24849]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

?

### Description

When hovering out of a mat tooltip with a delay before the delay ends, there is flicker of the mat tooltip which appears and then quickly disappears.

Stackblitz from from the official documentation with added delay setting: https://stackblitz.com/edit/angular-jhdwzh?file=src%2Fapp%2Ftooltip-custom-class-example.html

loom: https://www.loom.com/share/02182737108a4887bdcf5ded660fdb50

### Reproduction

Steps to reproduce:
1. create a mat tooltip with a delay of 1000
2. hover in and out of the element with tooltip quickly
3. the tooltip flickers when mouse moves out of the element before the delay ends

### Expected Behavior

The tooltip shouldn't be displayed when the mouse moves out of the element before the delay ends

### Actual Behavior

The tooltip flickers when moving the mouse out of the element before the delay ends.

### Environment

- Angular: 13.3
- CDK/Material: 13.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows/Macos

**Comment by volvachev** [comment]
I think it's similar to this one. (#24614).
