### ISSUE TITLE
help(THEMING): How do we theme component overlays (Dropdown, Snackbox...)?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#24858]
### What are you trying to do?

I've asked about how to Theme overlays (Dropdown, snackbox, etc.) on Stackoverflow here:

https://stackoverflow.com/questions/72074206/rendering-overlay-containers-when-theming-angular-material

I also created a github repository that shows what I'm trying to do per the tutorials that I have found on the subject.

Right now I can't get the dropdown to apply the dark theme, but everything else works fine.  I would really appreciate any tips you can give me.

### What troubleshooting steps have you tried?

Created a github repository and I have done research.  I also read all the documentation on Angular Material Theming and unfortunately there is no guidance on theming the CDK overlay contains in there.

### Reproduction

Steps to reproduce:
1. git clone git@github.com:fireflysemantics/angular-theming-test.git
2.cd ngular-theming-test
3. ng serve -o

### Environment

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.4
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cdk                    13.3.5
@angular/cli                    13.0.4
@angular/material               13.3.5
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4

**Comment by crisbeto** [comment]
There are a few options. You can either:
1. Apply your theme class on the `body`.
2. Pass in your theme class to the overlays using `OverlayConfig.panelClass`.
3. Inject `OverlayContainer`, get a hold of the container element using `getElementContainer` and apply your class to it.
