### ISSUE TITLE
bug(checkbox): Merged pull request caused a breaking change with checkbox checked value

### ISSUE THREAD

**Issue by jpduckwo** [angular/components#24859]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.6

### Description

Regarding https://github.com/angular/components/pull/20645
When this change was merged the checked value only accepts all non-null value as true except boolean false or 'false' string. This caused us issues where we were passing 0 or 1 and both are now treated as true.

I don't dispute the merge, but I think that this should be highlighted more prominently as a potential breaking change in the changelog.

> Thanks for your patience with getting this in :) there were several internal failures where clients were passing objects, strings, and arrays rather than booleans, causing unexpected changes

You can see it caused issues for the internal tests in the pull request comments for the same reason. People might have unexpected broken checkboxes without realising after upgrading (like we did)

EDIT: Comments are locked by the bot on the PR... if it's just been merged, I feel comments should be allowed again as I would have posted / linked this issue there...

### Reproduction

Steps to reproduce:
NA

### Expected Behavior

Notification in the changelog

### Actual Behavior

No notification of the potential impact of this change

### Environment

- Angular: 13.3.4
- CDK/Material: 13.3.4
- Browser(s): na
- Operating System (e.g. Windows, macOS, Ubuntu): na

**Comment by crisbeto** [comment]
> I don't dispute the merge, but I think that this should be highlighted more prominently as a potential breaking change in the changelog.

The problem is that basically any change can be breaking and we can't stop making changes altogether. We've drawn the line at TS compilation errors and larger runtime behavior changes. I wouldn't consider the change in https://github.com/angular/components/pull/20645 to be breaking, because the `MatCheckbox.checked` was already typed as a `boolean`.

**Comment by jpduckwo** [comment]
Hi @crisbeto, thanks for commenting, I understand totally. I will note that this is one of the first times ever that a minor change has broken our app and also did it in a silent way. It was unexpected, and would usually expect this type of behaviour in major releases. Hopefully this issue will help if anyone else experiences checkboxes that stay checked and don't know why :)
