### ISSUE TITLE
bug(DATEPICKER): dateAdapter.setLocale('fa') not working properly

### ISSUE THREAD

**Issue by newshahn** [angular/components#24861]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using Angular material datepicker with locale('fa) which is persian/jalali calendar, today date is 1 day ahead. So for example, today is Ordibehesht 12th but material datepicker is showing Ordibehesht 13th. Moreover, when I choose a date in the datepicker, for example (۱۹/۴/۱۳۷۶), the datepicker closes and the date that is shown in the input isn't actually what I chose. Instead it's (۱۷/۴/۱۳۷۶).

### Reproduction

https://components-issue-mle1fv.stackblitz.io

### Expected Behavior

For today's date to be shown correctly and the input value to be the same as the date selected.

### Actual Behavior

Today's date is not shown correctly and the input value of the datepicker is not the same as the date selected.

### Environment

- Angular: 13.3.2
- CDK/Material: 13.3.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mmalerba** [comment]
The `NativeDateAdapter` unfortunately doesn't work well for locales other than en-US. I recommend using one of our other adapters: @angular/material-date-fns-adapter, @angular/material-luxon-adapter, or @angular/material-moment-adapter. I tried with date-fns and it picks the correct date: https://stackblitz.com/edit/components-issue-qniree?file=src%2Fapp%2Fmaterial-module.ts,src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts
