### ISSUE TITLE
bug(mat-calendar): selected date not highlighted in mat-calendar

### ISSUE THREAD

**Issue by ntorrey** [angular/components#24870]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using an inline `<mat-calendar>` element, the selected day is not highlighted. I've tried using it in both chrome and edge and it doesn't seem to work. Going back to previous versions doesn't seem to help either so I wonder if it's a browser issue.

### Reproduction

Stackblitz:
https://stackblitz.com/edit/components-issue-umowpp?file=src/app/material-module.ts

Steps to reproduce:
1. Add an inline `<mat-calendar>` element
2. Click on a day in the inline `<mat-calendar>` element.
3. It does not highlight the selected day.

### Expected Behavior

I am expecting to see the day of the month highlighted when I select it.

### Actual Behavior

Nothing happens when I selected a day in an angular inline `<mat-calendar>` element.

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment]
Hello @ntorrey,

To highlight a selected day on the inline calendar, pass a Date to the `[(selected)]="selected"` banana-in-a-box. For further instructions, see [ Using mat-calendar inline
 https://material.angular.io/components/datepicker/overview#datepicker-inline-calendar].
 
 Thanks,
 Zach

**Comment by zarend** [comment]
@DaSchTour AFAIK auto-scrolling to the selected date is not a supported feature of inline calendar. To programmatically scroll to a month, use the . For reference, see the [MatCalendar API documentation](https://material.angular.io/components/datepicker/api#MatCalendar).
