### ISSUE TITLE
Adding a few plain divs and then scrolling on a mobile device causing a lot of frames to drop

### ISSUE THREAD

**Issue by vajahath** [angular/components#24889]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

a simple `app.component.html` with some divs
```html
<div class="banner"></div>

<nav>stuff</nav>
<br />
<br />

<div class="div-container">
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
  <div class="mat-elevation-z3 card-like">1</div>
  <div class="mat-elevation-z3 card-like">2</div>
  <div class="mat-elevation-z3 card-like">3</div>
  <div class="mat-elevation-z3 card-like">4</div>
</div>
```
I'm testing in Pixel 3a.

plain-div sample :clapper: 
![plain-div-eg](https://user-images.githubusercontent.com/12165822/167000882-b9dc9e6f-b184-42ca-8b06-7d0441a6663c.mp4)

material grid sample (even worse): :clapper: 
![material grid sample](https://user-images.githubusercontent.com/12165822/167001192-5ab404c4-e820-4fb4-93e8-a7facba3b7aa.mp4)

a normal SO page (for comparison): :clapper: 
![normal so page](https://user-images.githubusercontent.com/12165822/167001542-eceaf731-99a1-4560-b680-53141d1ffac7.mp4)

Minimal reproduction zip (~500kb): :package: [fps-drop-angular-demo.zip](https://github.com/angular/angular/files/8633538/fps-drop-angular-demo.zip)

Chrome version details :camera_flash: https://user-images.githubusercontent.com/12165822/166986210-02585925-bc60-406b-9f1b-32411aaf8e79.png

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/files/8633538/fps-drop-angular-demo.zip

### Please provide the exception or error you saw

```true
No error messages. But we can see the fps drop in the attached video.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            13.3.5 (cli-only)
@angular-devkit/schematics      13.3.5 (cli-only)
@angular/cli                    13.3.5 (cli-only)
@schematics/angular             13.3.5 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
```

**Comment by crisbeto** [comment]
I don't think that we can do much about this since we're following the Material Design specification. Also it's not as simple as `if (hasBoxShadow()) { beSlow() }`. It depends on how large the shadow is and what is around the element. If this is something you're concerned about, you should be able to add `* { box-shadow: none; }` to your CSS.
