### ISSUE TITLE
help(cdk/material): Custom parameters to migration script 

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#24891]
### What are you trying to do?

Is there way to pass parameters to migration script?

We have a implemented migration scripts for our private libraries to fix breaking changes and inside that we are running npm install for some required packages. But now to fix peerDependencies issue, we have either pass --force/--legacy-peer-deps which I cannot hardcode. 
So is there a way to pass user defined parameters to migration script?

### What troubleshooting steps have you tried?

NA

### Reproduction

NA

### Environment

- Angular: ^13.2.0
- CDK/Material: ^13.2.0
- Browser(s): NA
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
I'm not sure if this is a components specific issue and I don't have enough context to help out. Can you please add more information about the issue?

**Comment by iKrishnaSahu** [comment]
@amysorto We have extended ng update feature for our private library. We update package version and fix breaking changes with our custom migration scripts just like what you have in [cdk](https://github.com/angular/components/blob/2f9a59a24c0464cbed7f54cbeb5cba73e6007715/src/cdk/schematics/ng-update/index.ts#L18) and then we run npm install via migration script to install updated packages.

```ts
export function updateToV13(customArguments): Rule {
  // customArguments.parameter
  return createMigrationSchematicRule(
    TargetVersion.V13,
    cdkMigrations,
    cdkUpgradeData,
    onMigrationComplete,
  );
}
```

So my question is - Is there any way to pass `customArguments` to the migration script which I can provide via `ng update @my/private-lib --parameter` or maybe some other way to achieve the same.

**Comment by mmalerba** [comment]
This sounds like more of a question about schematics authoring. I'm not sure if update schematics support command line flags like that, at least I don't think we've done that before in Angular Material/CDK. You might want to try opening a feature request for it on https://github.com/angular/angular-cli
