### ISSUE TITLE
 MatDialog: When using in dynamically loaded component workaround deprecated

### ISSUE THREAD

**Issue by artu-ole** [angular/components#24913]
### What are you trying to do?

Main issue that has the bug explanation and 2 workarounds provided: [MatDialog: When using in dynamically loaded component throws error No provider for MatDialog](https://github.com/angular/components/issues/19335#)

>1. Add the `MatDialogModule` to the root module so that the service is available in your whole application
>2. Retrieve the `ComponentFactoryResolver` for the lazy module and instantiate the component through that.

### What troubleshooting steps have you tried?

Out of the two workarounds the first one is going against minifying the initial bundle size and the lazy loading principles in case the material component is used only in the lazy module.
The second @devversion's workaround functions well, however, now that both `ComponentFactoryResolver` and `Compiler` usage is deprecated with Ivy it is something that needs either another workaround or a proper fix. 
Possibly related issue(https://github.com/angular/components/issues/10820) which I have encountered as well, the dynamically loaded components with angular material dependency resolution is in underwhelming state which limits their usage for complex angular applications.

### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/components-issue-m7dysp?file=src/main.ts
2. Notice all the deprecations
![image](https://user-images.githubusercontent.com/15938416/168039378-e27a36de-f07b-4529-83bc-811390107e2d.png)

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0

**Comment by wagnermaciel** [comment]
@devversion Would you be able to give an update on this now that Angular no longer requires Component factories?

**Comment by devversion** [comment]
I think this is working as expected. If your lazy dialog component relies on a `NgModule` scope, this module would need to be loaded manually first so that the right providers are actually instantiated. This might be DX-wise more intuitive now with standalone components but conceptually the solutions presented in the original issue were not workarounds.

**Comment by artu-ole** [comment]
@devversion The issue that I'm trying to raise is that second solution presented in the original issue now relies on deprecated apis. Is there a workaround?

**Comment by hiepxanh** [comment]
Here you are, I solve it today. https://gist.github.com/hiepxanh/1306f075b2478e62133473d8cfaca537

```.ts

@ViewChild('datepickerTemplate', { read: ViewContainerRef }) datepickerTemplate!: ViewContainerRef;
  constructor(private fb: FormBuilder) {}

  async loadComponent() {
    const { DatepickerAtom } = await import('../../atoms/datepicker/datepicker.atom');
    const componentRef = this.datepickerTemplate.createComponent(DatepickerAtom);
    const dobControl = this.optionalForm.get('dob');
    if (dobControl) {
      componentRef.instance.dob = dobControl;
    }
  }

  ngOnInit(): void {
    this.loadComponent();
  }

```


upgrade to angular 14 and see my post here: 

https://dev.to/hiepxanh/angular-14-standalone-component-help-reduce-bundle-size-and-the-story-behind-you-may-not-know-1f44

**Comment by hiepxanh** [comment]
Sorry, using phone and cannot make example code ![image](https://user-images.githubusercontent.com/16970990/169848315-5e637852-8842-4983-805e-b81c20be540a.png)

**Comment by artu-ole** [comment]
@hiepxanh Thank you, unfortunately this does not provide a solution. 
Can you fork https://stackblitz.com/edit/components-issue-m7dysp?file=src%2Fmain.ts and modify `loadComponent()` not to use deprecated code keeping that fact that material dialog module is lazy loaded?

**Comment by devversion** [comment]
Thanks for posting this here. Yes, I can confirm that this is the expected API (it has been introduced in v13): https://github.com/angular/components/blob/c67a299a38b713c660b571b9f004168e2a9155db/src/components-examples/private/load-example.ts#L21
