### ISSUE TITLE
<mat-radio-button>: A11y Accessibility issue with mat radio button.

### ISSUE THREAD

**Issue by shrhegde** [angular/components#24918]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi,

We are using <mat-radio-component> for radio buttons. After Applying high contrast mode, the focus is not visible on the radio buttons.

### Reproduction

Steps to reproduce:
1. Go to [radio-example] (https://stackblitz.com/run?file=src%2Fapp%2Fradio-overview-example.ts)
2. Apply high contrast mode. In windows, got to Settings -> Accessibility -> Contrast themes -> Apply Night sky.
3. In [radio-example] (https://stackblitz.com/run?file=src%2Fapp%2Fradio-overview-example.ts), select or unselect any radio button. The status change is not visible. 
4. Also when you focus on the radio buttons using keyboard, the focus is not visible in high contrast mode.

### Expected Behavior

1. In high contrast mode, the inner circle should be visible when radio button is checked.
2. In high contrast mode, when navigating through keyboard the focus should be visible on radio buttons.

### Actual Behavior

1. In high contrast mode, the inner circle is not visible when radio button is checked.
2. In high contrast mode, when navigating through keyboard the focus is not visible on radio buttons.

### Environment

- Angular: 7.x.x, Latest version
- CDK/Material: 7.3.6 and Latest
- Browser(s): Chrome, Chromium Edge: Version 98.0.1108.13 (Official build) dev (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Win11

**Comment by zarend** [comment]
Hello,

I tested the radio component in Window Hich Contrast Mode and the selection indicator works. Please re-open or file a new issue if you continue to have a11y issues with mat radio button.

-Zach
