### ISSUE TITLE
help(Gestures): What is the recommended way to include gestures into Angular Material?

### ISSUE THREAD

**Issue by CalaxDev** [angular/components#24936]
### What are you trying to do?

I have been researching on how to enable general gestures and animations with Angular Material.
Back with AngularJS Material there were many Material-Like Controls with Animations like the Fab-Speed-Dial, and the Material-Spec and up until Angular 9 (I think) swipe-to-open Sidenavs were supported via gestures.

However this Gesture-Support was then dropped. Looking at HammerJS, which was previously used but then dropped, I am now wondering what the recommended/preferred way to include native-like/feeling controls (without using something like ionic/capacitor) would be.

Is there some recommendation for some library? Or is the general consensus "Build it yourself with Vanilla JS/Do not use gestures/animations"?

On Desktop gestures are not supported, sure, but for mobile devices, especially when packaged as a PWA, it would provide quite some "responsive" feeling and value if an Angular App worked just like a mobile app would.
(For example - Swipe Sidenav to Open/Close, Swipe Snackbar to close, ...)

### What troubleshooting steps have you tried?

-

### Reproduction

-

### Environment

Angular CLI: 13.3.3
Node: 18.0.0 (Unsupported)
Package Manager: npm 8.6.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.3 (cli-only)
@angular-devkit/core         13.3.3 (cli-only)
@angular-devkit/schematics   13.3.3 (cli-only)
@schematics/angular          13.3.3 (cli-only)

**Comment by Hapanmuffinssi** [comment]
This is really good question. As some gesture handling libraries such as HammerJS are kind of legacy today. We made our own swipe-directive to cover most basic situations (up/down/left/right with timing and swipe length calculations) and to provide necessary outputs to react accordingly. Maybe there is a better way, or a modern library, to handle this but so far have not found any.

RxJS has been very useful as it has nice event handling tools to compose with. fromEvent acting as a starting point.

**Comment by CalaxDev** [comment]
> This is really good question. As some gesture handling libraries such as HammerJS are kind of legacy today. We made our own swipe-directive to cover most basic situations (up/down/left/right with timing and swipe length calculations) and to provide necessary outputs to react accordingly. Maybe there is a better way, or a modern library, to handle this but so far have not found any.
> 
> RxJS has been very useful as it has nice event handling tools to compose with. fromEvent acting as a starting point.

Could you point me to your library by any chance? I would love to see how you implemented this!

**Comment by Hapanmuffinssi** [comment]
Unfortunately I do not have permission to publish work related libraries (it's a DIY approach). But it is a small directive which is used with a HTML-element and captures touch events related to the element. I can explain how this approach works (well, it works for our needs :))

First, I found this nice solution to detect if we are dealing with a touch device (or not):
https://stackoverflow.com/a/63666289

After detection is done there is a simple RxJS handling system:

```
if (supportsTouch) {
    const element = el.nativeElement;
    const touchStart = fromEvent(element, 'touchstart');
    const touchEnd = fromEvent(element, 'touchend');
    zip(touchStart, touchEnd)
        .pipe(
            map(([a, b]) => ({
                start: a as TouchEvent,
                end: b as TouchEvent
            }))
        )
        .subscribe((swipe) => { work with the result here });
}
```

el.nativeElement is the element the directive is used with. For example, an element located inside **mat-sidenav** as a part of the main menu. Swiping that element would then close the sidenav-container.

The idea was that every user gesture starts and ends at some point. So let's compose a package with RxJS zip. Then, when the result is available, there is swipe object with start & end as TouchEvent. Then, calculate what is necessary with the result. For example:

- Get coordinates and timestamps from swipe.start & swipe.end
- Calculate what the user did based on the coordinates and how long it took (skip super long periods)
- Activate correct output event emitter (right/left/up/down) based on what the user did

That is basically it. Hope it is of some help. And maybe there are better ways to deal with these...

**Comment by zarend** [comment]
AFAIK, we do not plan to bring back HammerJS or add broad support for gestures, but Feel free to file a Feature request  [https://github.com/angular/components/issues/new/choose](https://github.com/angular/components/issues/new/choose).

I can also suggest posting an issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

I'll leave this open as a P3 for now as we should address gestures in our documentation.

**Comment by CalaxDev** [comment]
> AFAIK, we do not plan to bring back HammerJS or add broad support for gestures, but Feel free to file a Feature request https://github.com/angular/components/issues/new/choose.
> 
> I can also suggest posting an issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.
> 
> I'll leave this open as a P3 for now as we should address gestures in our documentation.

Thank you so far for this answer!
I'm curious however, is there any "official" recommendation on how to add gestures on our own? Any best practice?

**Comment by zarend** [comment]
Hi @CalaxDev , we recommend developers implement gestures however works best for their application.

To clarify: we have a few components with some kind of gestures, such as tooltip, but we do not plan on adding any more gestures.

Thanks,
Zach

**Comment by CalaxDev** [comment]
Hey @zarend - Thanks for the clarification.

May I just ask why Angular Material is not going to support gestures?
Considering the Material Spec talking about gestures in a rather positive light (helping users achieve tasks quickly, as intuitive controls, etc.) and with Angular Material otherwise following the Material Design Spec for it's components, I am not quite sure why that important aspect has actively been decided against - Especially since Angular Material is used in a lot of Mobile First Applications, at least to my knowledge.

**Comment by zarend** [comment]
Hello,

I looked at the [Gestures material design page](https://material.io/design/interaction/gestures.html). That page looks like it is general guidance that can apply to any platform – native mobile, web etc. The page doesn't prescribe a specific implementation, and different consumers could arrive at different solutions based on their needs. It is more flexible for people to be able to add the gesture handling suite of their choice and connect it to the components. We are not well equipped to build, publish and maintain a general purpose gesture library.

There are a variety of solutions that would add dependency complexity that not all consumers want. 

Thanks,
Zach

**Comment by CalaxDev** [comment]
Hello!

I understand, and agree with what you mentioned just above. 

I've seen that, for example, the Ionic Team has a general purpose gesture library available - Perhaps, in the future, there could be some collaborative effort to extract this part form ionic and make it available as a Plugin into Angular Material - That's however just a naive idea of mine. However, I think that'd make sense and a lot of Angular Material users pretty happy :>

For now, however, I'm extremely grateful for your answers and elaboration on your choices and look forward to continue using Angular and it's Material library.

Thanks again, @zarend!
