### ISSUE TITLE
bug(MatSpinner ): MatSpinner is not longer visible after Angular 13.2.4

### ISSUE THREAD

**Issue by johnbu2** [angular/components#24953]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.4

### Description

I have created a loading wait service which uses MatSpinner based upon existing code example

https://medium.com/@velenra/using-angular-material-spinner-with-cdk-overlay-8ab92bfbafee
https://stackblitz.com/edit/mat-spinner-and-cdk-overlay-moxmh3

The issue I am experiencing since upgrading Angular beyond 13.2.4 is the background displays but the spinner is not longer displaying.  Nothing is displayed in the browser console that I can see.

The code for the spinner is

```javascript
import { Overlay, OverlayRef } from "@angular/cdk/overlay";
import { ComponentPortal } from "@angular/cdk/portal";
import { Injectable } from "@angular/core";
import { MatSpinner } from "@angular/material/progress-spinner";

// spinner so overlay and doesn't require separate component
// https://medium.com/@velenra/using-angular-material-spinner-with-cdk-overlay-8ab92bfbafee
// https://stackblitz.com/edit/mat-spinner-and-cdk-overlay-moxmh3

@Injectable({
  providedIn: "root"
})
export class LoadingWaitService {
  private readonly overlayRef: OverlayRef = null;
  private showCount = 0;

  constructor(private readonly overlay: Overlay) {
    this.overlayRef = this.overlay.create({
      hasBackdrop: true,
      backdropClass: "dark-backdrop",
      positionStrategy: this.overlay.position()
        .global()
        .centerHorizontally()
        .centerVertically()
    });
  }

  show() {
    this.showCount++;
    if (this.showCount === 1 && !this.overlayRef.hasAttached()) {
      const spinnerRef = this.overlayRef.attach(new ComponentPortal(MatSpinner));
      spinnerRef.instance.color = "accent";
    }
  }

  hide() {
    this.showCount--;
    if (this.showCount > 0)
      return;
    this.showCount = 0;
    setTimeout(() => {
      if (this.showCount === 0)
        this.overlayRef.detach();
    }, 500);
  }
}
```

### Reproduction

Steps to reproduce:
1.  Upgrade package.json from 13.2.4 to latest 13 version
2.  re run the application and no spinner

### Expected Behavior

The spinner displays after upgrading to new version of Angular

### Actual Behavior

The spinner no longer display after Angular upgrade

### Environment

- Angular:  cli/13.3.6, core/13.3.9
- CDK/Material: cdk/13.3.7, material/13.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
In the newer versions of Material we combined the `MatSpinner` and `MatProgressSpinner` classes since they are basically the same thing. The way we infer if it's a `MatSpinner` is by checking that the `nodeName` of the element is `mat-spinner`. This broke your use case, because using the `MatSpinner` directly in the `ComponentPortal` inferred it as a `mat-progress-spinner`. You can fix it by adding this like to your code:

```
spinnerRef.instance.mode = "indeterminate";
```

Here's a working example: https://stackblitz.com/edit/angular-djjwfs
