### ISSUE TITLE
bug(Datepicker): Page scrolls when using down arrow in datepicker month-view popup

### ISSUE THREAD

**Issue by elenachiosa** [angular/components#24969]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.13

### Description

After the update to Angular 13, the datepicker month view has keyboard interaction issues.

### Reproduction

Steps to reproduce:
1. Go to [Basic datepicker example on the Material site](https://material.angular.io/components/datepicker/overview#datepicker-overview)
2. Open the datepicker by using the datepicker button (using either mouse or keyboard)
3. While in month-view, keep pressing the down arrow key 

### Expected Behavior

The calendar popup does not move in the page.

![mat-month-view-expected](https://user-images.githubusercontent.com/17402311/170222151-db3583e9-8fd5-4c9a-a897-febf8dadcdb7.gif)

### Actual Behavior

After a few arrow key presses, the page scrolls and the datepicker popup moves as well.

![mat-month-view](https://user-images.githubusercontent.com/17402311/170221243-88da0ff5-b7ab-4b7f-8ff8-27b1f2158825.gif)

### Environment

- Angular: 13.3.5
- CDK/Material: 13.3.5
- Browser(s): Chrome, Edge
- Operating System: Windows

**Comment by crisbeto** [comment]
I couldn't get it to happen on my machine. Did you press any specific sequence of keys after you open the datepicker?

**Comment by elenachiosa** [comment]
> I couldn't get it to happen on my machine. Did you press any specific sequence of keys after you open the datepicker?

No, just the down arrow right after opening the popup.

**Comment by elenachiosa** [comment]
I updated the browsers in the original post. It also reproduces on Edge if you keep pressing the down arrow.
No issues found on Firefox.

**Comment by arnulf-s** [comment]
Same issue with autocomplete:
  https://material.angular.io/components/autocomplete/examples

Worked in ver 12:
  https://v12.material.angular.io/components/autocomplete/examples

**Comment by crisbeto** [comment]
Here's what I'm doing on Chrome

https://user-images.githubusercontent.com/4450522/170245001-4a59c24f-88c2-45d5-b704-5670df347a61.mov

**Comment by elenachiosa** [comment]
> Here's what I'm doing on Chrome
> 
>  Screen.Recording.2022-05-25.at.12.44.56.mov

Maybe the OS make a difference...? I am on Windows.

**Comment by zarend** [comment]
Well, this is a tricky one. After the keydown event happens, there is a slight delay before we focus the cell. We wait until after view checked, then focus the active cell in a `setTimeout`. The `setTimeout` was added to fix an issue with Voice Over screen reader. That delay might be related to this behavior.

https://github.com/angular/components/blob/37edbe997b3e624ffe189bb963721d0b0bd9b1a0/src/material/datepicker/calendar-body.ts#L222
