### ISSUE TITLE
Mat-select/Mat-option don't restrain focus with voice over

### ISSUE THREAD

**Issue by GlenStautland** [angular/components#24960]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When navigating the mat-options in mat-select with voiceOver, it is possible to "swipe" out of the options list and navigate in the background when the mat-select menu is open. The issue occurs when "swiping" to the last item and back to the first. It is not possible to "swipe" out of the menu if the user is on the last item. The user will be stuck on the last item. But if the user is on the first item(mat-option-item[0]) the next swipe doesn't take the user to the last mat-option-item, but out of the menu to the mat-select element. Then it's possible to navigate behind the menu

### Reproduction

Steps to reproduce:
1. Use voice over and open mat-select 

### Expected Behavior

When user is on the last mat-option-item the next "swipe" should take the user to the first mat-option-item. User on the first mat-option-item the next "swipe(up)" should take the user to the last mat-option-item

Example:

mat-option[0] -> swipe up/left/back should take the user to mat-option[2]
mat-option[1]
mat-option[2] -> swipe down/right/forward should take the user to mat-option[0]

### Actual Behavior

mat-option[0] -> swipe UP: Focus is set to mat-select element and menu is still open
mat-option[2] -> swipe DOWN: Focus is set to mat-option[0]

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):
- VoiceOver

**Comment by zarend** [comment]
Confirming that I can reproduce this issue.

VoiceOver | MacOS 12.4 (21F79) | Chrome Version 102.0.5005.61 (Official Build) (x86_64)
