### ISSUE TITLE
bug(cdk/overlay): Overlay not updating position on scroll

### ISSUE THREAD

**Issue by jarri-official** [angular/components#24992]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.13

### Description

When using a overlay with scroll strategy set RepositionScrollStrategy, position of a overlay is not updaring while scrolling.

### Reproduction

Steps to reproduce:
1. This bug is present in official documentation, as example https://material.angular.io/cdk/overlay/examples

### Expected Behavior

In previous version of documentation overlay is working as it should https://v12.material.angular.io/cdk/overlay/examples

### Actual Behavior

https://material.angular.io/cdk/overlay/examples

### Environment

- Angular: 13.3.5
- CDK/Material: 13.3.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is an issue with the docs, not the overlay. The scrollable container isn't registered as being a `cdkScrollable` so the overlay doesn't know that it's supposed to update.
