### ISSUE TITLE
bug(drag-drop): Not working with web component

### ISSUE THREAD

**Issue by KyDenZ** [angular/components#24998]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When exporting an Angular component to a web component, drag and drop does not work in the latter

### Reproduction

https://stackblitz.com/edit/angular-drag-and-drop-example-z3dzqg

### Expected Behavior

The drag and drop should work with the web component

### Actual Behavior

Drag and drop does not work with web component

### Environment

- Angular: `13.1.0`
- CDK/Material: `13.1.0`
- elements: `13.1.0`
- Browser(s): `Chrome 102.0.5005.61`
- Operating System: `macOS`

**Comment by amysorto** [comment]
I can't reproduce since all three examples you have seem to be working for me when I downgraded the stackblitz to the versions you listed. If your problem persists, please create a new issue with a reproducible example.

**Comment by KyDenZ** [comment]
Try to drop an element from the web component list to an Angular component or vice versa
