### ISSUE TITLE
bug(MatDialog): Mouse press outside of dialog enables backwards navigation and interacting outside of the dialog

### ISSUE THREAD

**Issue by oskartheren** [angular/components#25009]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a dialog is displayed I expect that the user should not be able to interact with the UI behind the dialog. But this is possible by using the keyboard while the mouse is pressed down.

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/dialog/overview
2. Open a dialog in any of the examples
3. Press down left mouse button outside of the dialog (keep it pressed down)
4. Press shift + tab

### Expected Behavior

It navigates in the dialog.

### Actual Behavior

It navigates outside of the dialog.
As long as the mouse is pressed down the user will be able to continue navigating and even interact with elements behind the dialog

### Environment

- Angular: 13.3.8
- CDK/Material: 13.3.8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment]
This is such an edge-case interaction that I don't think it's worth addressing. At some point we will likely look at the native `<dialog>` element and/or the native `inert` attribute for focus trapping that would make this obsolete (no ETA, though).
