### ISSUE TITLE
Spiderify Markers

### ISSUE THREAD

**Issue by ishanjaidka** [angular/components#25006]
### Feature Description

Spiderify markers with same coordinates

### Use Case

When there are similar locations for whatever reason, marker cluster should be able to spiderify markers in-order to view different markers at same location with different details

**Comment by zarend** [comment]
Hello @ishanjaidka ,

This component provides a Google Maps Angular component that implements the
[Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial).
File any bugs against the [angular/components repo](https://github.com/angular/components/issues).

-Zach
