### ISSUE TITLE
bug(GoogleMap): map is greyed when running in an Ionic Mobile App on ios device

### ISSUE THREAD

**Issue by vcomperq** [angular/components#25011]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

in my Ionic 6 application running under capacitor, i'm using angular googleMaps component. I need to use this map component in several pages of my application.

In my browser, everything works fine. When i run the app on my IOS physical device, the map is correctly displayed in the first page. But, when i navigate to **other page** with the same googleMap component, the map is displayed greyed out. When i touch the map, the grey disappears and the map is correctly displayed.

In Google Cloud Console, i resticted the API key to some http urls ( not to an IOS app because of ionic ) but this does not solve the issue.

Do you have any ideas ?

Thanks

### Reproduction

Steps to reproduce:
1. run the ionic App on physical IOS device
2. check the google map component

### Expected Behavior

the map is correctly displayed

### Actual Behavior

the map is greyed out when running on physical IOS device

### Environment

- Angular: 12
- CDK/Material:
- Browser(s): IOS Device
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is likely an issue with the Google Maps API, rather than the Material wrapper around it. We don't have any control over how Maps decides to render.
