### ISSUE TITLE
help(material-experimental/mdc-select): NG0300 Error when importing experimental component

### ISSUE THREAD

**Issue by to-ros** [angular/components#25031]
### What are you trying to do?

I'm having an issue with the mat-select where it isn't possible to define the item height externally.
When searching the issue I found #23838 which indicated to try the experimental version.
After following the instructions on [material-experimental/mdc-select](https://github.com/angular/components/tree/main/src/material-experimental/mdc-select) i receive a NG0300 error.
In my application I receive the following error: `NG0300: Multiple components match node with tagname mat-form-field: MatFormField and MatFormField.`
When creating the reproduction stackblitz and using the mat-select without a mat-form-field I receive the following error: NG0300: Multiple components match node with tagname mat-option: MatOption and MatOption.

I can't seem to figure out how to only import the experimental mat-select to check if this resolves my issue with the current "default" mat-select.

### What troubleshooting steps have you tried?

There's not much to troubleshoot, if I import anything from material-experimental my application no longer works.
I remove the import and "revert" to the default component my application works.

### Reproduction

Steps to reproduce:
1. add: import { MatSelectModule } from '@angular/material-experimental/mdc-select';
2. [https://stackblitz.com/edit/components-issue-rl9w1j?devToolsHeight=33&file=src/app/example-component.html](stackblitz)

### Environment

Angular CLI: 13.3.7
Node: 16.14.0
Package Manager: npm 8.5.3
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1303.7
@angular-devkit/build-angular        13.3.7
@angular-devkit/core                 13.3.7
@angular-devkit/schematics           13.3.7
@angular/cdk                         13.3.9
@angular/cli                         13.3.7
@angular/flex-layout                 13.0.0-beta.38
@angular/material                    13.3.9
@angular/material-date-fns-adapter   13.3.9
@angular/material-experimental       13.3.9
@schematics/angular                  13.3.7
rxjs                                 7.5.5
typescript                           4.6.4

**Comment by crisbeto** [comment]
You can only use the MDC version of `mat-select` with the MDC version of `mat-form-field`. You likely have an import of the non-MDC form field somewhere else in your app.

**Comment by to-ros** [comment]
Hi @crisbeto,

Thanks, it seems other modules are also importing the `mat-form-field` as I had already "replaced" it with the one from `material-experimental`.
I'll dig around some more to figure out which one's exactly and replace them as well.
