### ISSUE TITLE
bug(Bottom-sheet): The panelClass in Material bottom-sheet is not added to the <mat-bottom-sheet-container> in v14

### ISSUE THREAD

**Issue by xavier-che** [angular/components#25033]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

The panelClass of config in Material bottom-sheet is not added to the class of tag "mat-bottom-sheet-container" but to it's parent tag "div" which class is cdk-overlay-pane.

Below are the demo that I set the panelClass valued "share-sheet".

▼ The bug of v14
![image](https://user-images.githubusercontent.com/84447400/172362859-d2585e9d-96b8-4ecf-bb4b-20d02060494e.png)

▼ The previous version presented 
![image](https://user-images.githubusercontent.com/84447400/172363141-11e646b3-c50c-48d8-bf5f-0c3591bf970e.png)

### Reproduction

Steps to reproduce:
1.  set the panelClass of configuration to the bottom sheet in component.
2. to check the code.

### Expected Behavior

The panelClass  is added to the class of  tag "mat-bottom-sheet-container".

### Actual Behavior

The panelClass  is not added to the class of tag "mat-bottom-sheet-container".
but to it's parent tag "div"

### Environment

- Angular: 14.0.0
- CDK/Material: 14.0.0
- Browser(s): chrome 102.0.5005.63
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is a side-effect of #24951. `panelClass` was always meant to be set on the parent on the bottom sheet, not the container, but the old behavior was likely an oversight when the bottom sheet was introduced. You should be able to target the same element in your CSS by changing the selector to `.share-sheet .mat-bottom-sheet-container`.

**Comment by xavier-che** [comment]
Okay, I see
Thx! it work.
