### ISSUE TITLE
bug(Datepicker): local example does not work in stackblitz

### ISSUE THREAD

**Issue by worthy7** [angular/components#25040]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The local example on this page works fine
https://material.angular.io/components/datepicker/examples

But it doesnt not compile if you open the stackblitz.

https://stackblitz.com/run?file=src%2Fapp%2Fdatepicker-locale-example.ts

Also, on v7 of this documentation (seems to be similar code), the example in stackblitz actually DOESN'T WORK.
The local is not set to japanese in the picker like it shows in the docs.

### Reproduction

https://stackblitz.com/run?file=src%2Fapp%2Fdatepicker-locale-example.ts

### Expected Behavior

Should compile and functionally show japanese locale in the datepicker on init.

### Actual Behavior

Doesn't even compile.

### Environment

- Angular: 7 or 14
- CDK/Material: ?
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
I believe this was fixed in https://github.com/angular/material.angular.io/pull/1156.

If you make a new stackblitz example from the docs, it should build and run okay.
