### ISSUE TITLE
Angular Components Website not showing up when the version is set to 13

### ISSUE THREAD

**Issue by KLN888** [angular/components#25041]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.x

### Description

When the version is selected as 13 then the angular components website is showing a blank white page that is showing nothing.

### Reproduction

Steps to reproduce:
1. It is related to the angular website
2.

### Expected Behavior

After fixing  this then the website should work normally when we selected different versions of angular.

### Actual Behavior

The website is showing great examples of various components in angular when various versions are selected except when the previous version i.e, 13 selected .After selecting version 13 it showing a blank white page .

### Environment

- Angular: 
- CDK/Material:
- Browser(s): chrome and firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu
- Link-https://material.angular.io/components/categories

**Comment by crisbeto** [comment]
Should've been fixed in https://github.com/angular/material.angular.io/pull/1151.
