### ISSUE TITLE
docs-bug(Guides): Detail manual installation steps more in-depth

### ISSUE THREAD

**Issue by anddam** [angular/components#25051]
### Documentation Feedback

[getting started](https://material.angular.io/guide/getting-started) and [schematics](https://material.angular.io/guide/schematics) pages instructs to use `ng add` with the schematics and describe the effects as:

```
Running ng add will:

* Ensure project dependencies are placed in package.json
* Enable the BrowserAnimationsModule your app module
* Add either a prebuilt theme or a custom theme
* Add Roboto fonts to your index.html
* Add the Material Icon font to your index.html
* Add global styles to
  - Remove margins from body
  - Set height: 100% on html and body
  - Make Roboto the default font of your app
```

On tools like [stackblitz](https://stackblitz.com/) this is hardly accomplished since you do not get access to `ng`.

Having a more detailed description that can be implemented by hand would solve this.

For instance for the theme adding step one could have:

    Add `@import '@angular/material/prebuilt-themes/deeppurple-amber.css';` to `styles.css`

### Affected documentation page

https://material.angular.io/guide/getting-started

**Comment by amysorto** [comment]
The Stackblitz examples on material.angular.io uses web containers which means you can run node.js inside the browser. The command `ng serve` builds and serves the example you see. You can run other cli commands in the terminal there.

**Comment by anddam** [comment]
Still worth mentioning that on docs, someone like me creating angular POW on stackblitz from scratch will likely choose "Angular" as project type rather than "Next.js" or "Node.js starter".

With the former you have support for generating a few elements but not the `ng add` support, and once you create the project you cannot get a terminal.
