### ISSUE TITLE
feat(observes): Allow custom `options` for observe

### ISSUE THREAD

**Issue by cipchk** [angular/components#25069]
### Feature Description

Expect to listen for size, but:

```ts
{
          characterData: true,
          childList: true,
          subtree: true,
        }
```

### Use Case

```ts
this._contentObserver.observe(this._elementRef, { attributes: true  })
```

Some other [parameters](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#parameters).

**Comment by crisbeto** [comment]
We've had a PR this open for a while, but it never got anywhere https://github.com/angular/components/pull/13842.
