### ISSUE TITLE
bug(cdk): `hasModifierKey` could also accept `MouseEvent` to check for modifier keys.

### ISSUE THREAD

**Issue by liesahead** [angular/components#25079]
### Description

Currently it accepts only `KeyboardEvent` type.

### Expected Behavior

Accepts `KeyboardEvent | MouseEvent`

### Actual Behavior

Accepts just `KeyboardEvent`

### Environment

- Angular: Any
- CDK/Material: Any
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by crisbeto** [comment]
Closing, because this wouldn't make sense from a code organisation standpoint. All the code in `@angular/cdk/keycodes` is written around dealing with keyboard events specifically. Having one function that accepts a `MouseEvent` in there can be confusing.
