### ISSUE TITLE
help(HasElementRef): Common-Behaviors HasElementRef interface not available in Angular Material 14

### ISSUE THREAD

**Issue by anthony-serrano** [angular/components#25074]
### What are you trying to do?

After updating to Angular 14, the folder **common-behaviors** is not being found.

Is it exposed in a different place? 

```
import { HasElementRef } from '@angular/material/core/common-behaviors/color'

export class TestClass implements HasElementRef {
  constructor(public _elementRef: ElementRef) {}
}
```

### What troubleshooting steps have you tried?

I tried looking into different places but I didn't find the folder or the interface HasElementRef anymore.

### Reproduction

```
import { HasElementRef } from '@angular/material/core/common-behaviors/color'

export class TestClass implements HasElementRef {
  constructor(public _elementRef: ElementRef) {}
}
```

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The interface is still there, but it was never a public API to begin with. It's also worth noting that deep imports are no longer supported. Closing since it's working as expected.
