### ISSUE TITLE
Mat-menu voice over focus

### ISSUE THREAD

**Issue by GlenStautland** [angular/components#25086]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

I have previously reported a partially fixed bug related to "mat-menu-item don't restrain focus". This was fixed in v.14. But it's still a small issue. 

Before: When using voice-over, mat-menu did not always set the focus to the first menu item and it was possible to navigate out of the menu and on the elements behind the menu

Present: The focus is set to the first menu item and contained inside the menu when navigating to the bottom. However, when navigating back to the first item, it's possible to continue "up" and out of the menu to the elements behind. voice-over

### Reproduction

Steps to reproduce:
1. Open mat-menu with voice-over on
2.Navigate to last item, and back to the first(mat-menu-item[0]). The next "swipe" to the left will take you out of the menu and to elements behind the menu, and the menu is still open
 

### Expected Behavior

The focus should not leave the menu before the user close the menu

### Actual Behavior

The focus goes out of the menu and on elements behind the menu

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
confirming that I can reproduce on the [Basic Menu example](https://material.angular.io/components/menu/overview#menu-overview).

macOS 12.4 (21F79) | Voice over | Chrome Version 102.0.5005.115 (Official Build) (x86_64)

**Comment by jelbourn** [comment]
I believe this is working as expected

> The focus should not leave the menu before the user close the menu

I don't believe this is actually an expected behavior for menus, only for dialogs. If you try the W3C's own menu example, you can use VoiceOver navigation to move out of the menu:
https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links

@GlenStautland is there some specific ARIA or WCAG requirement that you're basing this report on?
