### ISSUE TITLE
Issue with Bottom sheet in angular material

### ISSUE THREAD

**Issue by KLN888** [angular/components#25085]
### What are you trying to do?

When I was trying to click on the button in bottom page example in angular material .It is showing different options like google docs ,google plus etc to share the given file but it is not redirecting  when i clicked on them which are to the respective link provided in html but when i am opening the same in new tab its redirecting to the specified link .

### What troubleshooting steps have you tried?

I tried using different versions of angular but of no use

### Reproduction

Steps to reproduce:
1. open material.angular.io
2.click on components
3.now click on bottom sheet on the side bar
4.now click open file button in the example 
5.four different options will be available on the sheet
6.click on them 
7.There is no response after the click 

### Environment

- Angular:all
- CDK/Material: material.angular.io
- Browser(s):chrome,firefox
- Operating System :Ubuntu

**Comment by crisbeto** [comment]
The demo page is only intended to show what the bottom sheet looks like, it isn't supposed to redirect you anywhere.
