### ISSUE TITLE
bug(overlay): OverlayReference is no longer being exported in @angular/cdk @ 14

### ISSUE THREAD

**Issue by lucavb** [angular/components#25098]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.x

### Description

The interface `OverlayReference` can no longer be imported. This is somewhat unfortunate because the interface is being used as an argument for the `.attach()` method of `PositionStrategy` which is still being exported. The TypeScript compiler with `strict` or `noImplicitAny` refuses to build the application. 

My guess is that this file needs to export the interface https://github.com/angular/components/blob/main/src/cdk/overlay/public-api.ts 

### Reproduction

Steps to reproduce:
1. View this [project](https://stackblitz.com/edit/components-issue-vracvq?file=src/app/custom-strategy.ts). Try to import the `OverlayReference`.

### Expected Behavior

Being able to import all required types and interfaces for already exposed interfaces.

### Actual Behavior

The shipped index.d.ts specifies the following:

```
declare interface OverlayReference {
```

which means that TypeScript won't import the interface. That would require the `export` keyword

### Environment

- Angular: 14.0.2
- CDK/Material: 14.0.2
- Browser(s): None / cannot be build
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
The `OverlayReference` is mostly a utility for us to avoid circular imports. It is the same as the `OverlayRef` that is exposed.

**Comment by lucavb** [comment]
Fair enough. With `OverlayRef` I can build my library package 👍.
