### ISSUE TITLE
bug(MatDatepickerModule): MatDatepicker jumps between Date formats in Input

### ISSUE THREAD

**Issue by CakeWithDivinity** [angular/components#25100]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the MatDatepickerModule and adding a MatDatepicker or MatDateRangePicker, the value in the input jumps between two date format states. 
This seems to only occur when changing the MAT_DATE_LOCAL Injection Token. I only tested this with 'de-DE', so I don't know if this happens with different formats t.o. 
It changes its value when you enter the vanilla HTML Input and do a change that marks the input as touched. So adding a space behind the value also triggers this. The value seems to switch back and forth between dd-MM-yyyy and MM-dd-yyyy. 

This also only occurs if both `MM` and `dd` are valid `MM` candidates. So `31-01-2022` will not jump between formats, while `01-02-2022` does. 

### Reproduction

Stackblitz: https://stackblitz.com/edit/angular-ivy-mlmcoc?file=src%2Fapp%2Fapp.module.ts

Steps to reproduce:
1. Choose a Date from the datepicker that uses a Day which is valid as a month
2. Click into the vanilla HTML Input
3. Press the spacebar or change anything in the value
4. Click outside the input or press tab to loose focus

### Expected Behavior

The value inside the vanilla HTML input should not switch the date-format when touching it and blurring it again. 

### Actual Behavior

The value inside the vanilla HTML input switches back and forth between `dd.MM.yyyy` and `MM.dd.yyyy`

### Environment

- Angular: 14.0.2
- CDK/Material: 14.0.2
- Browser(s): Chromium based, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu, Windows

**Comment by zarend** [comment]
Hello, I took a look at the example, it it uses the `MatNativeDateModule`, which only supports the `en-US` locale. I believe using a date adapter such as `MatMomentDateModule` should resolve this issue. Instructions for doing this are in [ Choosing a date implementation and date format settings
]https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by zarend** [comment]
Please install a date adapter following the instructions in https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings, and let me know if the Datepicker meets the needs for your use case.

**Comment by CakeWithDivinity** [comment]
@zarend Hey, thank you for the reply. I am sorry, I didn't see that part of the documentation. Adding the correct DateModule fixes the issue. Thank you for your help.
