### ISSUE TITLE
bug(Mat-input): matInput type='number' should accept only digits in Firefox

### ISSUE THREAD

**Issue by Prajapatigithub** [angular/components#25107]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have taken below example from Angular material webite, which is working as expected in Chrome but not in Mozilla firefox. matInput type="number" is allowing any character including number in Mozilla Firefox. Even examples shown on Angular material website itself not working in Firefox but working in Chrome.

<mat-form-field appearance="fill" floatLabel="always">
    <mat-label>Amount</mat-label>
    <input matInput type="number" class="example-right-align" placeholder="0">
    <span matPrefix>$&nbsp;</span>
    <span matSuffix>.00</span>
  </mat-form-field>

![image](https://user-images.githubusercontent.com/43925090/174420900-c9e6c4b9-beb0-42c1-af1b-44d1dd40f2fe.png)

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/form-field/examples & scroll down to the amount field.

3. Check in Chrome and Firefox. In Firefox text box will allow any character to type.

### Expected Behavior

matInput type='number' should accept/allow only digits and not any other character.

### Actual Behavior

matInput type='number' accepting any character including number.

### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): Mozilla firefox
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
Material doesn't have any special behavior for `number` inputs (or any of the other input types). It only styles the `input` and the form field around it. Closing this issue, because this is a browser inconsistency.
