### ISSUE TITLE
bug(MatStep): MatStep.isErrorState should accept AbstractControl instead of UntypedFormControl

### ISSUE THREAD

**Issue by migmigmig** [angular/components#25103]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm going through the process of activating strict template typechecking.

Our legacy code sends FormControlGroup instances into isErrorState.  Unfortunately, the compiler won't accept a FormControlGroup instance for an UntypedFormControl.

However, the underlying ErrorStateMatcher accepts AbstractControl.  And everything has seemed fine (for years) with passing a group here.

As a secondary item, it would be great if methods that take " | null " as part of their parameter types would also allow those params to be optional?

Thanks!

### Reproduction

Steps to reproduce:
1. Pass a FormControlGroup instance as the first param to MatStep.isErrorState()

### Expected Behavior

Compiler happily accepts FormControlGroup.

### Actual Behavior

Compiler complains that FormControlGroup doesn't match UntypedFormControl.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment]
@amysorto could you take a look at this? It should be a pretty quick fix

**Comment by crisbeto** [comment]
Worth noting that we're also using `UntypedFormControl` in `mixinErrorState` which should be changed.
