### ISSUE TITLE
bug(tabs  / mat-tab-link): No underline in selected tab after fresh application start 

### ISSUE THREAD

**Issue by dulekNo** [angular/components#25117]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular app with mat-tab-nav-bar and mat-tab-link
Then we run our angular application (fresh start/ initial load/ refresh page), even we have correctly selected **activeLink** we cannot see underline under selected tab. 
Even using  _alignInkBarToSelectedTab()  and realignInkBar() did not help.

The problem is visible in example stackBlitz for component.

![image](https://user-images.githubusercontent.com/15363531/174564151-f2bb7938-7ae2-4365-82a8-ab338386c777.png)

### Reproduction

Steps to reproduce:

As I said, the problem is visible in  example stackBlitz for component.

Go here:
https://material.angular.io/components/tabs/examples
Scroll to a very bottom of the page (Basic use of the tab nav bar),
Click icon to "Edit this example in StackBlitz"
Click the button and go here (or just follow the link):
https://stackblitz.com/run?file=src%2Fapp%2Ftab-nav-bar-basic-example.ts

Let application load and just look at output. 
![image](https://user-images.githubusercontent.com/15363531/174565100-d4f16725-11b6-449e-9a9d-bfc05856dcaf.png)
There is no underline under 1st tab.
But, when we click the second tab we will see animation (underline going from 1st to 2nd tab) and underline is visible under 2nd tab.
![image](https://user-images.githubusercontent.com/15363531/174565359-b4b79be3-9ac1-4137-b1dd-193bcc03ccd6.png)

### Expected Behavior

On initial load, we should be able to see underline in the selected tab.

### Actual Behavior

On initial load, there is no underline in tab link component.

### Environment

- Angular: 14.0.0
- CDK/Material: material current version (14.0.2)
- Browser(s): Chrome V. 102.0.5005.115 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows.

// All can be check in stackBlitz example

**Comment by zarend** [comment]
Confirming that I can reproduce by forking the [Basic use of the tab nav bar example](https://material.angular.io/components/tabs/examples#tab-nav-bar-basic)

https://stackblitz.com/edit/jgqdxu--run?file=src/app/tab-nav-bar-basic-example.ts
