### ISSUE TITLE
feat(cdkDropListGroup): Connect two group

### ISSUE THREAD

**Issue by Identity-labs** [angular/components#25118]
### Feature Description

This workaround is used to make both orientation horizontal & vertical to work as same time.

https://stackblitz.com/edit/yag-dnd-dashboard?file=src%2Fapp%2Fdashboard%2Fdashboard.component.html

But we loose the case to have two list connected with two set of data

### Use Case

Need to use groups and having them connected to transfert data between them

**Comment by Identity-labs** [comment]
...

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
