### ISSUE TITLE
mat-select does not display default (null) option text in mat-option

### ISSUE THREAD

**Issue by zolakt** [angular/components#25120]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm reposting this issue again: https://github.com/angular/components/issues/6466

since you closed it without providing any reasonable workaround or an explanation why you chose to implement this super weird, opinionated, behaviour. What is the reason to implement it like this? What problems does you implementation solve or prevent? From what I can see, it's just limiting a very common use-case, without any reasonable benefits. If you really insist on this, at least make it optional with an input binding, so we can opt-out of it when we don't need it. 

The only workaround for this is to use some other value, e.g. '' and then map it back and forth all over the place, for each mat-select. Honestly this is ridiculous. Totally messy, bug prone etc. and still a very poor workaround. 

I haven't found a single workaround that would enable the desired behaviour in the use-case when you have your own component, implementing control value accessor, which wraps a mat-select. 

### Reproduction

http://plnkr.co/edit/i919jzNOoXhlPeN4hxxE?p=preview

### Expected Behavior

Select should display text associated with null/undefined value when provided

### Actual Behavior

Select displays nothing

### Environment

- Angular: 14,0,0
- CDK/Material: 14.0.0
- Browser(s): ALL
- Operating System (e.g. Windows, macOS, Ubuntu): ALL

**Comment by wagnermaciel** [comment]
@crisbeto Given this was a deliberate decision, is this considered working as intended? Or would you like to revisit this eventually?

**Comment by crisbeto** [comment]
Yes, this is working as expected. The idea was to mimic the behavior of the native `select` and `option` elements with `mat-select` and `mat-option`.

**Comment by zolakt** [comment]
@wagnermaciel @crisbeto Sorry, but that is not an answer.
You could declare every single bug as "deliberate decision" this way...

Can you provide some workaround?

Also, can you name just one lib (any framework, any technology) that works the way that your does?
It's simply not true that native select works like this. (see screenshot).
It shows "NONE" as selected, it doesn't shown an empty string.
![image](https://user-images.githubusercontent.com/1048531/175956083-81b560e6-ca29-4efe-aa93-55dd66f4b8ff.png)

I honestly don't get your reasoning.
This is a needless limitation that is making a super common used case (optional filters, "ALL" options etc) nearly impossible to implement.

You could at least make it optional. Instead of forcing a opinionated, weird, behaviour like this, for no good reason.

**Comment by crisbeto** [comment]
You still have the ability to control what the trigger looks like using the `mat-select-trigger` element. There's a live example in the docs: https://material.angular.io/components/select/examples#select-custom-trigger

**Comment by zolakt** [comment]
@crisbeto No you don't. I've tried that already.

Here is a stacblitz example: 
https://stackblitz.com/edit/angular-l21cgb?file=src/app/select-custom-trigger-example.ts

The custom trigger is not shown either if the `mat-option` value is "empty".
In that case it shows the placeholder.
And you can't use the placeholder for this purpose if you use floating labels.
Even if you could, it would be an awful hack.

This line is the problem:
https://github.com/angular/components/blob/8ca012fdf63a540c0364d6acecd1d378f60f444e/src/material/select/select.html#L16

Others have reported this already in the original thread.
https://github.com/angular/components/issues/6466#issuecomment-332743725

**Comment by crisbeto** [comment]
> If the list of mat-options contains an "empty" value, than that initial/blank state doesn't make sense to begin with. So they shouldn't be able to get to it from the start, or after selection. That is how a native select works. There is no blank state.

Users may find that weird though since the form field around the select changes if a value is shown. For example you could have an empty form with a few `input` elements and a `mat-select`. The label of the inputs won't be floating, but the select will, despite the fact that you haven't interacted with it.

**Comment by Totati** [comment]
> And please don't treat `null` and `undefined` as the same thing. It's not. You could potentially treat `undefined` as a reset option, but `null` is definitely not some magical reset option. It is an explicit value.

FormControls change undefined values to null.

**Comment by zolakt** [comment]
> Users may find that weird though since the form field around the select changes if a value is shown. For example you could have an empty form with a few `input` elements and a `mat-select`. The label of the inputs won't be floating, but the select will, despite the fact that you haven't interacted with it.

True. But the current behaviour is even more weird. You select something (with an "empty" value) and it just disappears. This is a functionality issue, compared to the opposite which is a UX issue, at best.
Making this optional is the cleanest way to go. Let the devs decide what it less weird for their use case. 

> FormControls change undefined values to null.

Yeah, true, I think this is weird as well.
It converts `undefined` to `null` for the initial value, but not when you change selection.
Pretty weird and inconsistent

https://user-images.githubusercontent.com/1048531/176408691-9aef702d-114a-4ba1-8ed5-adfa75481fec.mp4

.

**Comment by mgechev** [comment]
Hey @zolakt, I wanted to thank you for the engagement in this issue and all the helpful information.

Going up the thread:

>To me this looks like a case of a bruised ego. Instead of making it right, you refuse to acknowledge the fact that you made a poor design choice

I want to ensure that we're all focused on improving Angular, and I'd recommend assuming good intentions.

Such statements and personal attacks are not welcome in our communication channels. Let's stick to a constructive tone and collaborative environment.

**Comment by zolakt** [comment]
@mgechev I apologise for the harshness, it was impulsively written. There was no bad intention.

In my defence, it can be frustrating to try to get you guys into an argumented discussion.
You have a tendency to close threads quickly, without really considering them thoroughly.
This happened to the original thread. And then you did the same to this one immediately.

So again, I'm sorry if I offended anyone. 
I just hope this finally gets reconsidered and fixed. 
It's a 5 year old issue, that is pretty annoying.

**Comment by martine-dowden** [comment]
Any movement on this? it would be really nice to have mat select respect null value display text.

**Comment by reislucas94** [comment]
Hello, any updates on this issue?

**Comment by Lempkin** [comment]
Any news here ?

**Comment by enrique-lozano** [comment]
5 years and we still don't have a solution or a workaround. Very frustrating.

**Comment by GabrielBB** [comment]
@mgechev @zolakt Please, we need this. Mapping to `null` is a very common case with dropdowns that display an "All" option. The only way right now is to map it to an empty string which makes less sense. As @zolakt said, please don't be so opinionated with this, let us devs choose what we want as value.

**Comment by carlos-ds** [comment]
While I do think the tone of this issue is far too harsh (bad decisions happen, and it's not always easy to undo the consequences), I also want to advocate for the ability to map to `null`. It would be great if this was revisited with flexibility in mind.

**Comment by zolakt** [comment]
@GabrielBB Why are you asking me :) I'm in the same boat as everyone else here, waiting for someone to finally fix this after 5+ years. The only workaround I have is to use 0 instead, which is incredibly stupid and tedious to maintain, but I found no better workaround

**Comment by prinf** [comment]
My vote here as well, why do we need to think every time about what value to use for the "All" option, why to choose from nonlogical values ('', '-', '-1', '0' etc.) while "null" would be ideal...

**Comment by JWess** [comment]
I agree that mapping to `null` is needed. Here is the workaround I've been using:

```
<mat-form-field floatLabel="always">
  <mat-label>State</mat-label>
  <mat-select placeholder="Any" formControlName="state">
    <mat-option [value]="null">Any</mat-option>
    <mat-option *ngFor="let state of states" [value]="state.id">
      {{ state.name }}
    </mat-option>
  </mat-select>
</mat-form-field>
```

![msedge_tHTZNix0Lw](https://user-images.githubusercontent.com/8697891/230666282-62a80914-73c8-48c2-b5c9-a650bc08f36d.gif)

**Comment by DibyodyutiMondal** [comment]
https://github.com/angular/components/issues/25120#issuecomment-1500577134

This gif is basically the crux of the entire issue. My client just told me he wanted to see 'All' as the displayed value for empty field in one of the dropdowns inside his form. 

That grey-out by default behavior is awkward for sure.

**Comment by inorganik** [comment]
Just wanted to chime in, the suggested workaround with `mat-select-trigger` does not work. In the example stackblitz I tried
```html
    <mat-select-trigger>
      {{ foodCtrl.value ? foodCtrl.value : 'I am null'  }}
    </mat-select-trigger>
```
And it still displays the placeholder text, even though the value is `null`. 

This stackblitz exhibits the problem with and without the mat-select-trigger, alongside a native select that works as intended: https://stackblitz.com/edit/4mzrpg?file=src%2Fexample%2Fselect-overview-example.html

**Comment by inorganik** [comment]
Best workaround I have found is to set the placeholder text to whatever you want to display for null and set floatLabel="always" on the mat-form-field

**Comment by abcox** [comment]
I need the `mat-select-trigger ` with `floatLabel="always"` that I can "clear" (with 'X' button on the control) that, when cleared, will show "Make your selection" (for example).

**Comment by skyRoma** [comment]
Please, make this change, guys.

**Comment by zolakt** [comment]
> Just wanted to chime in, the suggested workaround with `mat-select-trigger` does not work. In the example stackblitz I tried
> 
> ```
>     <mat-select-trigger>
>       {{ foodCtrl.value ? foodCtrl.value : 'I am null'  }}
>     </mat-select-trigger>
> ```
> 
> And it still displays the placeholder text, even though the value is `null`.
> 
> This stackblitz exhibits the problem with and without the mat-select-trigger, alongside a native select that works as intended: https://stackblitz.com/edit/4mzrpg?file=src%2Fexample%2Fselect-overview-example.html

Not sure where you have seen a workaround suggestion with `mat-select-trigger`.
I've tested that already, commented that it doesn't work and posted the problematic code: [here](https://github.com/angular/components/issues/25120#issuecomment-1167722284).

Although, I highly doubt anyone will ever fix that code, even after pointing out the exact problematic line. Personally, I've given up on waiting for this. The stupid workaround will have to do. If you wait for these guys to fix anything, you will never finish a single project. Now I'll probably get downvoted for pointing out the obvious, but sadly, that is reality...

**Comment by Erbenos** [comment]
Given that the fix on the surface levels seems to be changing https://github.com/angular/components/blob/5398170c6865d9881162096f2a40b77a74cf3953/src/material/select/select.ts#L1110 and similar cases of handling nulls, are you open for contributions regarding this or is keeping up the current behavior more important for you in regards to backwards compability or other reasons?

**Comment by muhamedkarajic** [comment]
How can this be bugged? Seriously.

**Comment by muhamedkarajic** [comment]
For me the default value dose not get displayed at all.

```html
<mat-form-field appearance="outline">
          <mat-label>{{ 'FIELD' | translate }}</mat-label>
          <mat-select
            [disabled]="isReadOnly$ | async"
            placeholder="{{ 'FIELD_PLACEHOLDER' | translate }}"
            (valueChange)="item.field.next($event)"
            [value]="item.field | async"
          >
            @for (item of OTHER.FIELD_TYPES_ARRAY; track item) {
              <mat-option [value]="item">{{ item }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
```

**Comment by IgorKurkov** [comment]
Any news on this one? We need to support null for mat-select as @zolakt mentioned > "It is an explicit value" of none.

<mat-select-trigger> still doesn't show/override if the control value is null. (link is here https://github.com/angular/components/issues/7758)

Should we use workarounds or tricks or can we just add support for null to make the mat-select more flexible?

**Comment by antoci-alin** [comment]
Totally need this fix as well.

**Comment by dburgos92** [comment]
Please, it is necesary...
