### ISSUE TITLE
bug(stackblitz): Stackblitz is down

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#25142]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Stackblitz is down.

![image](https://user-images.githubusercontent.com/34937515/175296948-dd31cac9-0564-41f5-9608-5fad470eb660.png)

### Reproduction

Steps to reproduce:
1. Open https://material.angular.io/components/select/examples
2. Open any example in stackblitz
3. Check if the example is loading in stackblitz

### Expected Behavior

Example should load in stackblitz

### Actual Behavior

Example is not loading in stackblitz

### Environment

- Angular: NA
- CDK/Material: NA
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Achilles1515** [comment]
Works for me as of now.

**Comment by iKrishnaSahu** [comment]
Seems like some cache related issue. Tried on other browser which worked fine for me.
