### ISSUE TITLE
bug(mat-checkbox): Checkbox not rendered in multi-column layout on Chrome (Version 103.0.5060.53 (Official Build) (64-bit))

### ISSUE THREAD

**Issue by kathrinkuenzli** [angular/components#25153]
### Description

In multi-column layout, using an unordered list, the mat-checkbox is no longer rendered/visible on Chrome Browser.

The Bug maybe relates to https://github.com/angular/components/issues/19089

### Reproduction

https://stackblitz.com/edit/angular-dcfswq-yfp4aw?file=src/app/checkbox-overview-example.css

Steps to reproduce:
1. Create an unordered list with each checkbox being wrapped by a list item tag
2. Set column-count: 2; on the unordered list
3. Open Page in Chrome Version 103.0.5060.53 

### Expected Behavior

All Checkboxes are visible and selectable.

![24-06-_2022_14-52-16](https://user-images.githubusercontent.com/30047637/175539870-789d02d2-3872-40e9-b5fd-8308736eb9ab.png)

### Actual Behavior

Starting with the Second Row the Checkboxes are no longer visible. If I click on the Position of the last Checkbox ('Warn'), the first Checkbox gets selected (Primary).

![24-06-_2022_14-45-33](https://user-images.githubusercontent.com/30047637/175539264-afefc575-ede3-4e26-a302-8b7007d2bb43.png)

### Environment

- Angular: 14, 12.2.13
- CDK/Material:14.0.3, 12.2.13
- Browser(s):Version 103.0.5060.53 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
I am also able to reproduce this on a Window machine

**Comment by crisbeto** [comment]
This is definitely some sort of browser bug, because adding `.mat-checkbox { transform: translateZ(0); }` fixes it.

**Comment by pedroestabruxelles** [comment]
@crisbeto  position: relative on the same class also fixes the problem
