### ISSUE TITLE
improve(tooltip): Prevent mouse over tooltip.

### ISSUE THREAD

**Issue by infacto** [angular/components#25173]
### Improvement Description

The tooltip should not receive any pointer events. It's annoying when the mouse is over a tooltip which causes never closing tooltips. 

My current solution in global styles:

```scss
.mat-tooltip-panel {
  pointer-events: none;
}
```

Consider to add this to your component. Tooltip is not interactive and I doubt anyone want to select the text. We could treat this as bug.

### Use Case

Tooltips can overlay other element. For example action buttons in a table. It's bad UX when you move your mouse to an button, but cannot clicked because the tooltip of another element overlaps it. 

| Before | After |
| :-: | :-: |
|![before](https://user-images.githubusercontent.com/60390085/176159370-6cf176ad-9c1c-4105-a986-ef72999e56f7.gif)|![after](https://user-images.githubusercontent.com/60390085/176159369-f3a15be6-91c9-492d-8d68-14f94cf2f5ba.gif)|
| 👎 | 👍 |

**Comment by crisbeto** [comment]
This was done to improve accessibility. You can disable it in your app by providing the `disableTooltipInteractivity` option using the `MAT_TOOLTIP_DEFAULT_OPTIONS` injection token.

**Comment by infacto** [comment]
OK thanks. Not seen. It works as well. I just wonder if we should toggle the init value. Any reasons for interactivity? What does "improve accessibility" mean in this case?

**Comment by infacto** [comment]
I don't think that's a good idea in this case. In fact the native tooltip does also not allow mouse over. It behaves like `disableTooltipInteractivity = true`. Which is the less annoying way. I don't see the accessibility relation. An option to have the tooltip open on mouseover is a good idea. But should be an opion. Not per default enabled. But do what you want.

**Comment by jelbourn** [comment]
While this behavior has been somewhat controversial, it's explicitly a WCAG requirement:
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

We have an option to turn it off for folks, but we try to keep all default behaviors aligned with formal a11y guidelines. I could see WCAG changing this at some point, but these standards move forward pretty glacially.
