### ISSUE TITLE
Multiple components match node with tagname mat-form-field

### ISSUE THREAD

**Issue by jonathanwilke** [angular/components#25186]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello everyone,

we migrated our application to use Angular 14 and restructured everything as standalone components. Now our unit tests are breaking with the following error: 

**_NG0300: Multiple components match node with tagname mat-form-field: MatFormField and MatFormField._**

We couldn't find any existing solution to this so far.

Hope you can help us.

### Reproduction

We have built a standalone FormControlComponent that imports MatFormFieldModule and this is used in all of the components where the tests are failing.

### Expected Behavior

Since the MatFormFieldModule is only imported once there should not be a problem with duplicate tagnames.

### Actual Behavior

See error above.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Both of these should be bringing in the same form field. You should check if one of the imports is coming from `@angular/material/` while the other is from `@angular/material-experimental/`.
