### ISSUE TITLE
bug(MatTooltip): Tooltip of first item is blocking tool tip of second item, when items are placed one below other like menu. It is an issue when tooltip position is 'below' or 'above''

### ISSUE THREAD

**Issue by cceravikumark** [angular/components#25184]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular/material": "13.2.5

### Description

Please refer the description in reproduction steps.

### Reproduction

Steps to reproduce:
It is simple case of 3 button items arranged one below other like menu items. Please refer at 
(https://stackblitz.com/edit/angular-fo9lax?file=src%2Fapp%2Ftooltip-overview-example.html)

### Expected Behavior

Tool tip of item is expected to be shown properly for the item that is being hover over.
1. Hove over item1, tooltip is expected for item 1.
2. Move down and hover over item2, tooltip of item 2  is expected to be shown.
3. Move down and hover over item3,  tooltip of item 3  is expected to be shown.

### Actual Behavior

It is simple case of 3 button items arranged one below other like menu items. Please refer at 
(https://stackblitz.com/edit/angular-fo9lax?file=src%2Fapp%2Ftooltip-overview-example.html)
Tool tip is NOT shown properly, if hover over item from item 1 to item 3.
1. Hove over item1, tooltip is shown for item 1.
2. Move down and hover over item2, tooltip of item 1 is shown, Tooltip of item2 is expected.
3. Move down and hover over item3, tooltip of item 1 is shown.
Here the tooltip of first item is blocking the below items when the tooltip position is 'below', which default tooltip position.

Tool tip is shown properly, if hover over item from item 3 to item 1.
1. Hover over item3, tool tip of item 3 is shown.
2. Move up and hover over item 2, tool tip of item 2 is shown.
3. Move up and hover over item 1, tool tip of item 1 is shown.

### Environment

- Angular: 14
- CDK/Material: 13.3.9/14.0.0
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is working as intended. See https://github.com/angular/components/issues/25173 for more context and how to disable it.

**Comment by cceravikumark** [comment]
Thank you.
