### ISSUE TITLE
feat(mdc-button): Use Material 3 naming for Angular (button) components

### ISSUE THREAD

**Issue by the-ult** [angular/components#25207]
### Feature Description

Atm the naming of the mdc-button is (mostly) the same as in the current/legacy `mat-button`

However, the buttons in https://m3.material.io/components/buttons/overview have different names:
- [Elevated button](https://m3.material.io/m3/pages/common-buttons/guidelines/#4e89da4d-a8fa-4e20-bb8d-b8a93eff3e3e)
- [Filled button](https://m3.material.io/m3/pages/common-buttons/guidelines/#9ecffdb3-ef29-47e7-8d5d-f78b404fcafe)
- [Filled tonal button](https://m3.material.io/m3/pages/common-buttons/guidelines/#07a1577b-aaf5-4824-a698-03526421058b)
- [Outlined button](https://m3.material.io/m3/pages/common-buttons/guidelines/#3742b09f-c224-43e0-a83e-541bd29d0f05)
- [Text button](https://m3.material.io/m3/pages/common-buttons/guidelines/#c9bcbc0b-ee05-45ad-8e80-e814ae919fbb)

But the current `mdc-button` implementation (still) uses: ` button[mat-button], button[mat-raised-button], button[mat-flat-button],button[mat-stroked-button]`

Wouldn't it be more logical to use the same naming as https://m3.material.io?

**Comment by amysorto** [comment]
It is unlikely the name will change now since MDC button is now released.
