### ISSUE TITLE
bug(ng add @angular/material): doesn't configure material correctly

### ISSUE THREAD

**Issue by adorogensky** [angular/components#25215]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.17

### Description

ng add @angular/material doesn't configure material correctly

### Reproduction

Steps to reproduce:
1. git clone git@github.com:adorogensky/angular-training.git
2. git checkout ng14
3. ng add @angular/material
4. add example code from https://material.angular.io/components/radio/examples to hello-world.component.html
5. run the app and try to select mat radio button

### Expected Behavior

mat radio button gets selected

### Actual Behavior

mat radio button won't get selected

### Environment

- Angular:
- CDK/Material: 14.0.4
- Browser(s): Chromium Version 102.0.5005.115 (Official Build) Fedora Project (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Fedora Linux 36 (Workstation Edition)

**Comment by crisbeto** [comment]
Were you able to go through the entire `ng add` process? I got an error at the end:

```
The package @angular/material@14.0.4 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
? Choose a prebuilt theme name, or "custom" for a custom theme: Indigo/Pink        [ Preview: https://material.angular.io?theme=indigo-pink ]
? Set up global Angular Material typography styles? No
? Include the Angular animations module? Include and enable animations
UPDATE package.json (1270 bytes)
✔ Packages installed successfully.
Cannot read properties of undefined (reading 'kind')
```

**Comment by adorogensky** [comment]
yes, i was getting that same error message at the end.

**Comment by crisbeto** [comment]
Thank you for confirming, that's likely the root cause.

**Comment by adorogensky** [comment]
it seems to me that the root cause of this issue is the upgrade from 11 to 14. branch ng11 now contains the basic angular app of version 11. ng14 is how i upgraded from ng11, i had to use --force to upgrade from 12 to 13 and from 13 to 14.

**Comment by adorogensky** [comment]
i just verified that creating a new app straight with version 14 doesn't have this issue. i'm going to close this and create a new issue for update from 11 to 14.
