### ISSUE TITLE
docs-bug(mat-icon): Available mat-icon ligatures no longer match Material Icons

### ISSUE THREAD

**Issue by mtpultz** [angular/components#25213]
### Documentation Feedback

Using `<mat-icon>` and the official [Material Icon](https://fonts.google.com/icons) site was how designers would choose the icons we would use, but recently the site icon names no longer match what `<mat-icon>` displays.  

For example, `undo` on the site is:

<img width="140" alt="image" src="https://user-images.githubusercontent.com/599498/177019659-a5171c1a-19a2-4a5c-9e4c-851812397cbd.png">

But, `<mat-icon>` displays:

<img width="34" alt="image" src="https://user-images.githubusercontent.com/599498/177019674-c1ca9248-76a3-4fbf-9c9c-32997d407f1a.png">

If these are no longer synced due to css2 API changes, or how they are used has changed it would be great to know where we can see the available icons now for the `<link>` provided on install of Angular Material:

```html
<link
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet" />
```

### Affected documentation page

https://material.angular.io/components/icon/overview

**Comment by crisbeto** [comment]
This sounds like an issue with the Material design icons, not with our implementation.
