### ISSUE TITLE
bug(MatRadioButton): won't display as selected after clicking on it

### ISSUE THREAD

**Issue by adorogensky** [angular/components#25214]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was
12.2.17
_No response_

### Description

MatRadioButton won't display as selected after clicking on it

### Reproduction

Steps to reproduce:
1. https://github.com/adorogensky/angular-training/tree/ng-wtf3
2. http://localhost:4200/
3. clicking on a radio button

### Expected Behavior

the radio button will display as selected

### Actual Behavior

the radio button won't display as selected

### Environment

- Angular: 14.0.4
- CDK/Material: 14.0.4
- Browser(s): Chromium Version 102.0.5005.115 (Official Build) Fedora Project (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Fedora Linux 36 (Workstation Edition)

**Comment by crisbeto** [comment]
It's because you haven't set a `value` on the radio buttons.

**Comment by adorogensky** [comment]
no it's not, here check out the last commit. i used an example code from here https://material.angular.io/components/radio/examples

**Comment by crisbeto** [comment]
You also haven't included a theme. There's even a warning about in the console.

**Comment by adorogensky** [comment]
i don't see any warnings in the console. what environment are you testing in? i ran ng add @angular/material and chose the default theme.

**Comment by adorogensky** [comment]
you can check out ng14 branch, which is an upgrade of a simple app that has two components app and hello-world from 11 to 14 following steps from https://update.angular.io. do ng add @angular/material and select all the default options. then add that example code that won't work.

**Comment by adorogensky** [comment]
so this is a problem with ng add script, it won't add './node_modules/@angular/material/prebuilt-themes/indigo-pink.css' to angular.json

**Comment by adorogensky** [comment]
closing this issue, new one with better description is created https://github.com/angular/components/issues/25215
