### ISSUE TITLE
bug(Tooltip): is not close when cursor is moving toward the tooltip

### ISSUE THREAD

**Issue by ofirrifo** [angular/components#25219]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

Up to angular material version 12 included the tooltip was closed when the cursor pointer move to the tooltip.
Since angular material version 13  this behavior was changed as you can see from your [changelog](https://github.com/angular/components/pull/24475)  

This new behavior cause a bug in a big project I'm workin on.
This is a regression since version 13.

I think the best will be if you can give to the tooltip directive a new input which keep the tooltip open in case cursor is move toward the tooltip and the old behavior will continue work as it was.
other wise it brake the old behavior.

### Reproduction

Steps to reproduce:
1. open [angular materi](https://material.angular.io/components/tooltip/overview) in the first example move the mouse toward the tooltip the tooltip not disappear. this start from version 13 

u can see it work as expected in version 12 -> https://v12.material.angular.io/components/tooltip/overview

### Expected Behavior

tooltip should be closed when cursor pointer move toward the tooltip

### Actual Behavior

tooltip is keep display when cursor pointer move toward the tooltip

### Environment

- Angular: 13 and 14
- CDK/Material: 13 and 14
- Browser(s): all browser
- Operating System (e.g. Windows, macOS, Ubuntu): mac

**Comment by crisbeto** [comment]
This is working as intended. See https://github.com/angular/components/issues/25173 for more context and how to disable it.
