### ISSUE TITLE
docs-bug(guides/elevation): Link to theming-guide is broken

### ISSUE THREAD

**Issue by oliverkierepka** [angular/components#25228]
### Documentation Feedback

The Link in `guides/elevation.md` is broken. This PR fixes that by introducing the missing link handle.

### Affected documentation page

https://material.angular.io/guide/elevation

**Comment by crisbeto** [comment]
Should've been fixed by https://github.com/angular/components/pull/25229.

**Comment by oliverkierepka** [comment]
cool. thanks
