### ISSUE TITLE
bug(SELECT): You have to click twice when select is open

### ISSUE THREAD

**Issue by richardsengers** [angular/components#25233]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

So when you have a select which is openend and you have a button next to it, you cannot click the button. You have to click twice. This is also mentioned here:  https://github.com/angular/components/issues/15416

According to the comment it should work like a native select, but with native selects you can click a button when the select is opened.

### Reproduction

You can test this by going to the demo page: https://material.angular.io/components/select/examples
Open one of the select and try to click another select. It only closes the current select but no other seelct is openend. You have to press twice.

Now let's do the same with the native select on the same page. As you can see, you don't have to click twice

### Expected Behavior

Make the behaviour of the select the same as native select

### Actual Behavior

Have to double click to trigger siometing else when select is opened

### Environment

- Angular: 14.0.4
- CDK/Material: 14.0.4
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment]
I can repro on Chrome OS

Chrome/Chrome OS Version 102.0.5005.75 (Official Build) (64-bit)

**Comment by zarend** [comment]
Well, AFAIK the requirements are that the mat-select correctly implements the ARIA combox pattern and adheres to the material design spec. There is no requirement that it behaves exactly like native select. Although, it should be similar to a native select.

**Comment by wagnermaciel** [comment]
I discussed with the team and we've concluded that this is working as intended
