### ISSUE TITLE
bug(Angular Material): Installing Angular Material 14 under Angular 14 after update from 12.x fails: Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by Sebi2020** [angular/components#25246]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11 (as far as I know)

### Description

See #25215 (now closed...) for reference.  The issue claims that this error is caused by an upgrade from Angular 11 to 14. This is not the case. This also happens if you start a new project with Angular 12 and upgrade to 14.

I followed the update guide, but the error persists.

### Reproduction

Steps to reproduce:
1. Create new project with Angular 12.x
2. Upgrade to Angular 13.x
3. Upgrade to Angular 14.x
4. Install Angular material with command `ng add @angular/material@14`
5. Error: `Cannot read properties of undefined (reading 'kind')`

### Expected Behavior

Should not cause an error. Steps to fix this should be mentioned in the update guide.

### Actual Behavior

Install of Angular Material v. 14.x fails.

### Environment
```
Angular CLI: 14.0.5
Node: 16.13.2
Package Manager: npm 8.13.2
OS: win32 x64

Angular: 14.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular-devkit/architect       0.1400.5
@angular-devkit/build-angular   14.0.5
@angular-devkit/core            14.0.5
@angular-devkit/schematics      14.0.5
@angular/cdk                    14.0.4
@angular/material               14.0.4
@schematics/angular             14.0.5
rxjs                            6.6.7
typescript                      4.6.4
```
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by vvolodin** [comment]
I'm having a similar problem, using Angular 14.0.5:
```
Skipping installation: Package already installed
? Choose a prebuilt theme name, or "custom" for a custom theme: Custom
? Set up global Angular Material typography styles? Yes
? Include the Angular animations module? Include and enable animations
UPDATE package.json (1747 bytes)
✔ Packages installed successfully.
Cannot read property 'kind' of undefined
```

**Comment by timothylombrana** [comment]
Same with just a new project, no upgrades needed to reproduce.

Angular CLI: 14.1.0
Node: 16.16.0
Package Manager: yarn 1.22.10 
OS: darwin x64

Angular: 14.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@angular/fire                   7.4.1
@schematics/angular             14.1.0
rxjs                            6.6.7
typescript                      4.6.4

**Comment by adorogensky** [comment]
angular team, updates?

**Comment by addon-tly** [comment]
Same here.  Getting this error on installing angular material, and also on calling ng g @angular/material:navigation

**Comment by adorogensky** [comment]
ANGULAR TEAM, updates????

**Comment by Sebi2020** [comment]
still no response from the angular team...

**Comment by SebaQuiros** [comment]
Exact same problem. Console logs:
`Cannot read properties of undefined (reading 'kind').`

`Angular: 14.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@angular/cdk                    14.1.1
@angular/material               14.1.1
@schematics/angular             14.0.1
rxjs                            7.5.5
typescript                      4.6.4


C:\Users\sebaq\Documents\Programación\ArgentinaPrograma\Proyectos\Portfolio>`

**Comment by aallnneess** [comment]
Same Problem. Updating Angular 13 to 14...

**Comment by edwincosta** [comment]
I have the same issue:
**Cannot read properties of undefined (reading 'kind')**

### Project dependencies
"@angular/animations": "^14.1.3",
    "@angular/cdk": "^14.1.2",
    "@angular/common": "^14.1.3",
    "@angular/compiler": "^14.1.3",
    "@angular/core": "^14.1.3",
    "@angular/forms": "^14.1.3",
    "@angular/material": "^14.1.2",
    "@angular/platform-browser": "^14.1.3",
    "@angular/platform-browser-dynamic": "^14.1.3",
    "@angular/router": "^14.1.3",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

**Comment by FatalMerlin** [comment]
I have the same problem using `ng add @angular/material`

**Comment by FatalMerlin** [comment]
Okay I just found a workaround:

1. run `ng add @angular/material` as usual
2. select theme
3. select typography
4. IMPORTANT: Choose to disable Angular animations module ("Do not include") - the last option

Voilà

![image](https://user-images.githubusercontent.com/14237330/186022032-1c54cd97-a24e-4491-a54a-0b27c0130ac1.png)

**Comment by uvero** [comment]
@FatalMerlin your solution worked and helped me with `ng add @angular/material`. However, I ran into the same error with `ng generate @angular/material:navigation <component-name>`, like @edwincosta

Anyone has help?

**Comment by FatalMerlin** [comment]
@uvero glad to help!

Regarding your question:

Try running:

`npm i -D @schematics/angular`
or
`yarn add -D @schematics/angular`

It resolved a similar problem for me :)

**Comment by uvero** [comment]
Thank @FatalMerlin, I've tried it, but it didn't help. What did help is adding `--skip-import`, so, if anyone stumbles upon the same problem, I hope it helps.

However, those are still workarounds - I hope the Angular team figures it out soon.

**Comment by Codefans-fan** [comment]
same issue for me

**Comment by macorifice** [comment]
same issue here 

![Screenshot 2022-09-08 at 23 39 52](https://user-images.githubusercontent.com/2563910/189230907-4d98bfd7-f0e4-419d-ac2e-d114e72d81e9.png)

![Screenshot 2022-09-08 at 23 42 18](https://user-images.githubusercontent.com/2563910/189231201-3a05ac8e-5a22-4b21-88c6-c89d27b457c5.png)

**Comment by zlaval21** [comment]
I had this issue and fixed it by updating to the latest TypeScript version. Currently `4.8.3`. Hope this works for others.

**Comment by wenici** [comment]
> Bon je viens de trouver une solution :
> 
>     1. Cours `ng add @angular/material`comme d'habitude
> 
>     2. sélectionne un thème
> 
>     3. sélectionner la typographie
> 
>     4. IMPORTANT : Choisissez de désactiver le module d'animations angulaires ("Ne pas inclure") - la dernière option
> 
> 
> Voilà
> 
> ![image](https://user-images.githubusercontent.com/14237330/186022032-1c54cd97-a24e-4491-a54a-0b27c0130ac1.png)
> 
> PS : Je pense que vous pouvez ensuite configurer manuellement le module d'animations en suivant ces instructions : [ https://angular.io/guide/animations#step-1-enabling-the-animations-module ](https://angular.io/guide/animations#step-1-enabling-the-animations-module)

It worked for me, thanks

**Comment by whizyrel** [comment]
Update your typescript version, that works too

**Comment by zarend** [comment]
Hello @Sebi2020,

Does the issue persist when upgrading typescript version?

-Zach

**Comment by exitlol** [comment]
@zarend I can confirm as i ran into this issue while updating a project from angular 10 to 14 with the correct steps.
That updating typestript to the latest version will solve the installation error, and completes without any issue.

Hope this helps.

**Comment by alanblake** [comment]
confirming 
npm i typescript@latest 
fixed this issue for me

**Comment by zarend** [comment]
@Sebi2020,

I believe this issue is resolved by updating typescript as suggested by [zlaval21](https://github.com/zlaval21) and a few others. I think we can go ahead and close out this issue. Thank you everyone for participating.

@Sebi2020 does this issue persist for you? If so, could you please provide a stackblitz reproduction?

-Zach

**Comment by Sebi2020** [comment]
@zarend No, it does not. I will close the issue now

**Comment by MauriRios** [comment]
npm i typescript@latest works for me
