### ISSUE TITLE
feat(google-maps): Support for Overlapping Marker Spiderfier in the google maps component?

### ISSUE THREAD

**Issue by tommueller** [angular/components#25251]
### Feature Description

I am very pleased that we do have the map-marker-clusterer component now. However, the clustering is still very much incomplete without support for some sort of spiderfying in higher zoom levels.

Please add support for this, i.e via https://github.com/jawj/OverlappingMarkerSpiderfier

### Use Case

When zooming in on clustered locations, it is still not possible to depict locations which are located very, very close together.

**Comment by zarend** [comment]
Hello @tommueller ,

The `@angular/google-maps` package implements the [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API). If there is something in the Google Maps JavaScript API that is not implemented please file a bug here. For improvements with the Google Maps JavaScript API, the best place to file that is with the Google Maps JavaScript API itself.

-Zach
