### ISSUE TITLE
feat(google-maps): use mapMarkerClusterer instead of mapMarkerClustererPlus

### ISSUE THREAD

**Issue by rbalet** [angular/components#25256]
### Feature Description

The `google-maps` component is using the [mapMarkerClustererPlus](https://www.npmjs.com/package/@googlemaps/markerclustererplus) library, which is deprecated in favor of the [markerClusterer](@googlemaps/markerclusterer) one.

### Use Case

The former markerclustererplus does have some error which the newest version may fix.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/23695.
