### ISSUE TITLE
bug(MatDialog): afterOpened is not always called, probably due to change detection issues

### ISSUE THREAD

**Issue by JonWallsten** [angular/components#25261]
### Is this a regression?

Note sure

### Description

This is an intermittent issue. But I have scenarios where it fails 80% of the time. I think it got a little bit worse when I went from 13.x.x -> 14.x.x. But that might be due to other code changes. 
I don't think I can reproduce it in StackBlitz since it's involved a complex setup and a chain of events.
But I can certainly try if the description is not detailed enough.

When opening dialogs the `afterOpened()` observer is not always "called". And since that's where I run `updateSize()` and `updatePosition()`. The dialog ends up looking like this:
![image](https://user-images.githubusercontent.com/5993909/178484322-8794ebc8-650e-429f-8276-9a00a269dda6.png)

If I run `this.cd.markForCheck()` after the dialog code the observer is called, so it definitely has something to do with Change Detection. However this is a feasible solution since I open the dialogs from a common services, where injecting ChangeDetectionref is not possible.

`this.applicationRef.tick();` does not help (I thought this was a Global Change detection tick?)

The reason I think Change detection is not working properly is because we use native async/await.
However I use the `zone.run()` code for that reason:
```
return this.zone.run(() => {
    const dialog = this.matDialog.open<T>(template, { ...config, viewContainerRef: !useGlobalViewRef ? this.viewContainerRef : undefined });
    dialog.afterOpened().subscribe(() => {
        if (!config.width) {
            dialog.updateSize();
        }

        if (!config.position) {
            dialog.updatePosition();
        }
    });
    return dialog;
});
```

But I still get the issue. This code responsible for calling the `afterOpened` observer is never reached:
```
_containerInstance._animationStateChanged.pipe((0,WEBPACK_IMPORTED_MODULE_8__.filter)(event => event.state === 'opened'), (0,WEBPACK_IMPORTED_MODULE_9__.take)(1)).subscribe(() => {
  this._afterOpened.next();

  this._afterOpened.complete();
}); // Dispose overlay when closing animation is complete
```

So the dialog is created, opened and visible on screen. But the `_animationStateChanged` event does not seem to happen, which causes the `afterOpened` observable to never be "called".

Should it be this dependent on Change detection to work? And why does running it in the zone not make the internal `Change Detection` in the `MatDialog` component to work?

Thanks!

### Reproduction

N/A

### Expected Behavior

The `afterOpened()` observer should be "called"

### Actual Behavior

The `afterOpened()` observer is not called due to some animationStateChange not being triggered due to Change Detection issues.

### Environment

Angular CLI: 14.0.1
Node: 16.14.0
Package Manager: npm 8.3.1 
OS: win32 x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core 
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1400.1
@angular-devkit/build-optimizer   0.1302.1
@angular-devkit/core              14.0.1
@angular-devkit/schematics        14.0.1
@ngtools/webpack                  14.0.1
@schematics/angular               14.0.1
ng-packagr                        14.0.2
rxjs                              7.5.5
typescript                        4.7.3
webpack                           5.73.0

**Comment by gonzalo-lorieto** [comment]
try downgrade `rxjs` to `6.x`

**Comment by zarend** [comment]
Hello @JonWallsten ,

This looks like more of a support request than a bug report. This issue tracker is not suitable for support requests. However, the extended community of users can provide more help:

 - [StackOverflow](https://stackoverflow.com/questions/tagged/angular-material2)
 - [Gitter](https://gitter.im/angular/material2)
 - [Google Groups](https://groups.google.com/forum/#!forum/angular-material2)
 
 -Zach
