### ISSUE TITLE
feat(GOOGLE-MAPS): Add Restriction input configuration

### ISSUE THREAD

**Issue by carlosdag28** [angular/components#25268]
### Feature Description

Hello team, I see the need to use the restriction property in angular to restrict the bounds of a map.

But I see that I can not pass an input with the configuration because it does not exist. I'm currently using the `"@angular/google-maps" version: "^14.0.4"`

![image](https://user-images.githubusercontent.com/35420704/178728368-d1667042-6009-4fe7-9d4a-f9367e7de0cd.png)

### Use Case

User like me who wants to restrict the limits of the map to a specific area

**Comment by crisbeto** [comment]
You should be able to set it through the `options` input.

**Comment by carlosdag28** [comment]
Thanks @crisbeto, it works!
