### ISSUE TITLE
bug(md-tooltip): Performance issue when ViewChild contains many instances of md-tooltip on a scrolling panel

### ISSUE THREAD

**Issue by surajpatnaik1986** [angular/components#25294]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

md-tooltip when placed inside a grid with many rows, many instances of this components gets created which does heavy DOM manipulation when user places mouse on the element where md-tooltip is associated and does a scrolling. This finally causes the performance issue in browsers like IE11.

Solution:

User can set mdTooltipShowDelay and avoid this issue to some extend but the ideal solution would be look for scroll event and once user stop scrolling, attach tooltip to DOM

### Reproduction

Steps to reproduce:
1. Create a grid using ngFor or material grid
2. place md-tooltip in a grid cell
3. make sure the grid has many records e.g. 500 (we cannot assume all users using virtual scrolling or paging)
4. open the application in IE-11 and keep the mouse on the grid cell where the md-tooltip is applied
5. do scrolling quickly

### Expected Behavior

No Performance issue or browser freezing

### Actual Behavior

IE11 freezes while scrolling quickly

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
@surajpatnaik1986 ie11 is no longer a supported browser. Here is [a list of our supported browsers](https://github.com/angular/components/blob/main/README.md#browser-and-screen-reader-support). If you can reproduce this issue on a supported browser, please feel free to file a new issue with a link to a stackblitz demo
