### ISSUE TITLE
bug(mat-menu): Upon opening the menu, the first item is in selected state.

### ISSUE THREAD

**Issue by vvolodin** [angular/components#25299]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I open my menu with four buttons in it, the first button is highlighted and highlighted state doesn't go away when I move the mouse over other items.

### Reproduction

Steps to reproduce:
1. Add mat-menu
2. Have 4 button elements in it

### Expected Behavior

No items are selected when opening the menu.

### Actual Behavior

As in description

### Environment

- Angular: 14.0.6
- CDK/Material: 14.0.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This is working as expected. It's showing the user where their focus is and it isn't going to show up when opening the menu using your mouse.
