### ISSUE TITLE
map-marker component doesn't fire mapClick event

### ISSUE THREAD

**Issue by adellamaggiora** [angular/components#25319]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`<google-map id="map" height="100%" width="100%" (mapInitialized)="onMapInitialized($event)">
  <map-marker [position]="livePosition"></map-marker>
  <map-marker *ngFor="let marker of markers" [position]="marker?.position" [icon]="marker?.icon"
    (mapClick)="openInfo(marker, infoWindow)">
  </map-marker>
</google-map>
`

the function "openInfo" is not called when a marker is clicked.

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

The function should be called

### Actual Behavior

The function is not called

### Environment

- Angular: 14.0.6
- CDK/Material: 14.0.5
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Linux Debian

**Comment by zarend** [comment]
ty for reporting, @adellamaggiora 

Could you please provide a stackblitz reproduction of the issue?
-Zach

**Comment by adellamaggiora** [comment]
I resolved using the straight google maps library without this Angular wrapper. I guess the problem was a combination of map-marker and map-cluster together.

**Comment by zarend** [comment]
Thanks for letting us know. I'll close this issue as you were able to resolve the problem.
