### ISSUE TITLE
CDK Drag Drop issues with nested lists - On Drop cannot reconize child list

### ISSUE THREAD

**Issue by guilhermebentomarques** [angular/components#25333]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi all,
I'm facing an issue and I can't drag and drop correctly when I have nested lists.

The link to understand issue is here: https://stackblitz.com/edit/angular-cdk-drag-drop-vrgtqh?file=app/cdk-drag-drop-connected-example.html

Is there anything to do in this case related to CDK, or it is a limitation?

Thank you all,
Guilherme Marques.

### Reproduction

Steps to reproduce:
1. Drag the second red square
2. Drop the second red square in the first red square zone.

The blue square (parent) is overriding the child (red square) and I cannot reach the child red square when I drop. 

![image](https://user-images.githubusercontent.com/10928446/180758546-395f1407-5bb1-4816-8144-6089605c2567.png)

### Expected Behavior

The console log should be:
Line 1 - from red-square-2-data
Line 2 - to red-square-1-data

### Actual Behavior

Check the console log.
Line 1 - from red-square-2-data
Line 2 - to blue-square-1-data

### Environment

- Angular:  12.2.16
- CDK/Material: 12.2.13
- Browser(s): All majors (Chrome, Firefox, Edge)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
Ps: The stackblitz link is using an older version but the issue is the same with the version above.

**Comment by crisbeto** [comment]
Covered by https://github.com/angular/components/issues/16671.
