### ISSUE TITLE
feat(SIDENAV): Possibility to have multiple sidenav at the same position

### ISSUE THREAD

**Issue by GregoireLgt** [angular/components#25335]
### Feature Description

Hi, this feature was already asked a few years ago but the issue was locked : https://github.com/angular/components/issues/1514

I find myself in the situation where I need to have multiple Sidenav positioned at the end of my viewport (so on the right of the viewport).

Is this something that can be considered for the Sidenav component ? For instance, ng-boostrap allows to do the same thing with their [Offcanvas component](https://ng-bootstrap.github.io/#/components/offcanvas/examples).

**Angular: 13.3.11
@angular/material: 13.3.9**

### Use Case

The user wants to display additional information by clicking on different buttons which always open a Sidenav on the right of the viewport

**Comment by GregoireLgt** [comment]
EDIT : For anyone struggling with this problem, the simple solution : 

I managed to solve my problem by creating multiple div inside my <mat-drawer> and by adding *ngIf conditions, so i ended up having just one mat-drawer with dynamic content

**Comment by crisbeto** [comment]
Closing since this isn't supported by the Material Design spec, as far as I can tell.
