### ISSUE TITLE
help(MatInput): Appearence outline with prefix and suffix

### ISSUE THREAD

**Issue by ropoko** [angular/components#25358]
### What are you trying to do?

I am trying to use the input with outline appearence, also with prefix and suffix text, but for some reason the input text does not align with the suffix and prefix

example:

![image](https://user-images.githubusercontent.com/49417432/181776629-cfa2c078-96f9-43e6-9d59-897230643fec.png)

### What troubleshooting steps have you tried?

I tried inspecting html on browser and adding some custom css, but is doesn't work

### Reproduction

Steps to reproduce:
1. In mat-form-field component (appearence - outline) add the <input matInput type="text">
2. add the prefix and suffix:
```html
<p matPrefix>R$</p>
<p matSuffix>,00</p>
```
4. My code:
```html
<mat-form-field appearance="outline">
    <input
      matInput
      formControlName="valorVoucher"
      class="input-voucher"
    />
    <p matPrefix>R$</p>
    <p matSuffix>,00</p>
    <mat-hint color="contrast">Valor mínimo RS500,00</mat-hint>
</mat-form-field>
```

### Environment

- Angular: 14.0
- CDK/Material: 14.0.4
- Browser(s): edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by wagnermaciel** [comment]
This appears to be fixed in our latest version
https://stackblitz.com/run?file=src%2Fapp%2Fform-field-prefix-suffix-example.html
