### ISSUE TITLE
bug(MatBottomSheet): Property panelClass adds class to a wrong element

### ISSUE THREAD

**Issue by SSlippa** [angular/components#25353]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.0

### Description

When we use class MatBottomSheet to create a popup panel we use method open() and pass a configuration MatBottomSheetConfig and one of the properties is "panelClass" that should my custom class to mat-bottom-sheet-container
Instead of adding it to this html element it is added to cdk-overlay-pane -> it is a parent element of mat-bottom-sheet-container

### Reproduction

Steps to reproduce:
1. 
2.
https://stackblitz.com/edit/angular-gteslf?file=src%2Fapp%2Fbottom-sheet-overview-example.ts,src%2Fapp%2Fbottom-sheet-overview-example.html

### Expected Behavior

when using property panelClass it should add class to mat-bottom-sheet-container

### Actual Behavior

when using property panelClass it is adding class to cdk-overlay-pane

### Environment

- Angular: 14.1.0
- CDK/Material: 14.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
This is working as intended since the `cdk-overlay-pane` is what we is meant by "panel". You can still style the container by targeting `.custom-panel-class .mat-bottom-sheet-container` in your selectors.

**Comment by SSlippa** [comment]
So then the description should be different from "Extra CSS classes to be added to the bottom sheet container", because it is written container, and in the previous version, it was really added to the container.
