### ISSUE TITLE
Mat Datepicker not able to assign 'startAt' in TS

### ISSUE THREAD

**Issue by vishwas097** [angular/components#25363]
### What are you trying to do?

TypeError: Cannot set properties of undefined (setting 'startAt')

    <mat-form-field>
      <mat-label>A:</mat-label>
      <input matInput [matDatepicker]="sectionpicker" [(ngModel)]="selectedSection.date"  (dateChange)="save(true)" readonly [ngModelOptions]="{standalone: true}" />
      <mat-datepicker-toggle matSuffix [for]="sectionpicker"></mat-datepicker-toggle>
      <mat-datepicker #sectionpicker ></mat-datepicker>
    </mat-form-field>

TypeScript
import { MatDatepicker } from '@angular/material/datepicker';
  @ViewChild('sectionpicker') datePicker: MatDatepicker<Date>;
      this.datePicker.startAt = new Date("10/10/1996");    

### What troubleshooting steps have you tried?

Tried to assign values and use [startAt] in HTML but there are rendering issue, it takes time to render in multiple datepicker case.

### Reproduction

Steps to reproduce:
1. Install Angular Material
2.Try to use Datepicker 'startAt'

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**If I Try to assign the 'startAt ' value by considering the calendar open event, Only the year and month is set, the date is not getting highlighting for some reason.**

**Comment by crisbeto** [comment]
`startAt` only determines which page of the calendar will be shown when the overlay is opened, it doesn't control the highlighted date.
