### ISSUE TITLE
bug(BUTTON): Icon button is not centered within ripple, causes input height change

### ISSUE THREAD

**Issue by karmasakshi** [angular/components#25361]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

2 issues: When putting the clear option in an input, it's seen that the icon is not centered within its ripple. Additionally, when using a custom font, it is seen that the line-height causes the input to increase in height as soon as the icon appears. The issue seems to be:

`.mat-form-field-suffix .mat-icon-button .mat-icon { line-height: 1.125 }`. This can be solved by setting `line-height: 1`. Attaching screenshot, video and link from Docs for reference.

https://stackblitz.com/run?file=src/app/input-clearable-example.ts

<img width="443" alt="Screen Shot 2022-07-30 at 10 44 03 AM" src="https://user-images.githubusercontent.com/4698762/181878878-d9279e42-da34-4742-93cf-53bd1c3c191e.png">

https://user-images.githubusercontent.com/4698762/181879134-b2a17374-cdbd-4100-8d90-13bbfb7aad11.mov

### Reproduction

Steps to reproduce:
1. Use a clearable input, input text

Alternatively, also use a custom font to see the height issue:

```
@use '@angular/material' as am;

@font-face {
  font-display: swap;
  font-family: 'Nova';
  font-style: normal;
  font-weight: 300;
  src: url('assets/fonts/Nova-300.woff2') format('woff2');
}

$my-typography: am.define-typography-config(
  $font-family: "'Nova', sans-serif",
);

@include am.core($my-typography);
```

### Expected Behavior

1. Icon should be centered
2. Height should remain consistent irrespective of the font

### Actual Behavior

1. Icon is not centered
2. Height is not consistent

### Environment

- Angular: 14.1.0
- CDK/Material: 14.1.0
- Browser(s): Chrome and Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by amysorto** [comment]
Changing the font didn't cause an issue for me and the ripple still seems centered. Can you provide a stackblitz with a example that does this for you?

**Comment by karmasakshi** [comment]
Sorry I am unable to reproduce this on StackBlitz, but it looks different from Docs site (screenshot attached). I will close anyway. It could be an issue with downloaded fonts or the commercial font we're using; will create another ticket if I get more info. Thanks for checking.

https://material.angular.io/components/input/examples
https://stackblitz.com/edit/angular-hmvykm?file=src%2Fstyles.scss

<img width="854" alt="Screen Shot 2022-08-16 at 1 09 40 PM" src="https://user-images.githubusercontent.com/4698762/184844260-12c528eb-1d7a-4fce-97d4-57c3f9a34369.png">

<img width="680" alt="Screen Shot 2022-08-16 at 1 09 54 PM" src="https://user-images.githubusercontent.com/4698762/184844281-1355c92c-5727-4562-ac2a-abc31b8a22d2.png">

**Comment by karmasakshi** [comment]
I was able to identify the difference causing this issue: the height calculation in Chrome is different from that on Safari and Firefox. Attaching the screenshot. Firefox isn't allowing me to run StackBlitz but when I compare the same on the Docs site, the value is a round figure (27px) so it works there. I will attach a working sample if I'm able to create one.

<img width="1383" alt="Screen Shot 2022-08-18 at 9 52 35 PM" src="https://user-images.githubusercontent.com/4698762/185463341-1f53e749-ef2c-4f35-8f2b-0abebb51dcbd.png">

<img width="1343" alt="Screen Shot 2022-08-18 at 9 53 11 PM" src="https://user-images.githubusercontent.com/4698762/185463351-9587e0a0-f5a4-4640-b8fa-6ccb3c9cc349.png">

<img width="1359" alt="Screen Shot 2022-08-18 at 9 53 55 PM" src="https://user-images.githubusercontent.com/4698762/185463358-536daadb-9cf6-4d76-be4c-ed6982e0bd96.png">
