### ISSUE TITLE
help(COMPONENT): mat input type: time 

### ISSUE THREAD

**Issue by samlam67812** [angular/components#25376]
### What are you trying to do?

I am trying to make a form input with matinput type=[time] with time intervals provided.

### What troubleshooting steps have you tried?

    Here is my code:
`
<mat-label> Start Time </mat-label> 
   <mat-form-field appearance="outline">
   <mat-label>Enter Start Name</mat-label> 
   <input matInput formControlName="start_time" type="time" step="1500" min="06:00" max="24:00"> 
</mat-form-field>
`
  
I have added the property step which is native html input type.
However when I added to my matinput, there is no effect on the time selector.

### Reproduction

Steps to reproduce:
1. 
2.

### Environment

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
- 
Angular CLI: 14.0.4
Node: 16.14.2
Package Manager: npm 8.7.0 
OS: win32 x64

Angular: 14.0.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.4
@angular-devkit/build-angular   14.0.4
@angular-devkit/core            14.0.4
@angular-devkit/schematics      14.0.4
@schematics/angular             14.0.4
rxjs                            7.5.5
typescript                      4.7.4

**Comment by wagnermaciel** [comment]
Hi, unfortunately we do not yet provide a form input for type=[time]. This feature is currently not planned
