### ISSUE TITLE
docs(mat-checkbox): add info about how checkbox should be used

### ISSUE THREAD

**Issue by ropoko** [angular/components#25387]
### Documentation Feedback

While using mat-checkbox in a form, I tried to use the mat-checkbox inside a mat-form-field and this returned me this error below:

![image](https://user-images.githubusercontent.com/49417432/182635503-acd5c6c2-b089-41d0-8348-6427190a5909.png)

The reason is that the mat-checkbox cannot be used inside a mat-form-field component, but this is not specified in any part of the docs, and I think it could be helpful

### Affected documentation page

https://material.angular.io/components/checkbox/overview

**Comment by amysorto** [comment]
On the `form-field` docs page, its lists out which other components it's meant to work with: https://material.angular.io/components/form-field/overview. So I'll mark this issue as closed.
