### ISSUE TITLE
bug(drag-drop): Inner elements shown with an Angular animation are not removed from the DOM

### ISSUE THREAD

**Issue by garethdn** [angular/components#25397]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After dragging and dropping an element with the `cdkDrag` directive attached, inner elements with an Angular animation that are conditionally shown (e.g. with `*ngIf`) are not removed from the DOM.

If the element that is conditionally shown is an Angular Component, the `ngOnDestroy` hook is correctly called but the associated element appears to remain in the DOM.

### Reproduction

https://stackblitz.com/edit/angular-ax1ahd-alwskr?file=src/app/cdk-drag-drop-sorting-example.html

Steps to reproduce:
1. Drag the 2nd item (Attack of the Clones) to the first position
2. Click the "Toggle show" button on the "Attack of the Clones" item
3. "Is showing" should disappear but it does not

### Expected Behavior

"Is showing" should disappear

### Actual Behavior

This element remains in the DOM. Further interactions with the button creates a duplicate elements. This behaviour can be repeated multiple with the same `cdkDrag` element.

### Environment

- Angular: 13 and 14
- CDK/Material:  13 and 14
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This looks like it's caused by https://github.com/angular/angular/issues/18847.
