### ISSUE TITLE
feat(COMPONENT): all mat components use as cusom element in html template

### ISSUE THREAD

**Issue by YJPrakash** [angular/components#25407]
### Feature Description

Using the same name of angular material components like (mat-button or mat-icon). Register all the default material components as custom elements. This is helpful for the fastest way of templating used in website development. 

### Use Case

[stackoverflow question](https://stackoverflow.com/questions/73260483/how-to-use-angular-material-components-as-web-
components-use-custom-elements-in)

I am using the following versions in my Dev environment:
Angular: 12.2.16 LTS
node: 14.20.0 LTS
ubuntu os: 22.04LTS

**Comment by crisbeto** [comment]
You're free to register the components as web components yourself, but we don't have any plans to do this within the library.
