### ISSUE TITLE
feat(CDK Dialog): add the possibility to know if any window is open

### ISSUE THREAD

**Issue by BenLune** [angular/components#25403]
### Feature Description

I need to get a property on Dialog Service to know if any window is open to protect my scroll listener reaction. If any window is open, I don't want to trust the window scroll event.

### Use Case

I'm working on an application with effects depending on user scroll actions.
Using the CDK Dialog, when I open a dialog, the overlay is added, and some stuff updates the body tag, changing its display, position etc.
My listener to scroll event wake up because the scroll moved to position 0, which is not totally true, because the scroll visually didn't change.
I can already deal with window id, but I think it could be simpler to get such property.

**Comment by amysorto** [comment]
The dialog service does have a property called `openDialogs` which would give you this list: https://material.angular.io/cdk/dialog/api#Dialog.
