### ISSUE TITLE
bug(DatePicker): Once date selected in DatePicker pop up, changing value via keyboard changes the value of it to null

### ISSUE THREAD

**Issue by FA91AN** [angular/components#25401]
### Description

If I change the date value with the keyboard the value inside the form changes accordingly. But as soon as I change the date with the selector pop up and then want to change it again with the keyboard, the value sets to null.

### Reproduction

Steps to reproduce:
1. Change date with pop up (via button)
2. Change date with keyboard like '01/01/2022' (text input)

### Expected Behavior

Something like '01/01/2022'

### Actual Behavior

null

### Environment

- Angular: 14.1.0
- CDK/Material: 14.1.0
- Browser(s): Brave
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment]
Hello,

Can you provide a stackblitz reproduction of the issue?
-Zach

**Comment by zarend** [comment]
Hello @FA91AN 

Thank you for reaching out. Unfortunately we are not able to take action if we cannot reproduce it. This might have already been fixed. If the issue persists, please provide reproduction steps or file a new issue report.

- Zach
