### ISSUE TITLE
help(MatMenuHarness): MatMenuHarness.getItems() always returns 0 items

### ISSUE THREAD

**Issue by jacksonopp** [angular/components#25438]
### What are you trying to do?

Using the `MatMenuHarness` seems to get the menu trigger, but does not seem to be able to interact with the actual menu. When I use the `getItems()` method, I expect that the items length should be the number of items in the menu, but it is always 0. When I use the `open` method, i expect `isOpen` to be true, but it is false.

### What troubleshooting steps have you tried?

I have tried following the harness instructions as provided. I have tried surpassing the menu harness by using the component fixture.

### Reproduction

Steps to reproduce:
1. Create a component containing a button and a menu with three items
2. Create a spec that gets the menu harness
3. Use the `getItems()` method
4. Expect the length of the items to be 3
5. Observe: length is 0 and spec fails

https://stackblitz.com/edit/harness-issue-yzubby?file=src/app/button-harness-example.spec.ts

### Environment

- Angular: 14
- CDK/Material: 14
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
There are a few issues in your test:
1. You have to import an animations module in the test component. There's an error in the console about it.
2. The selector for menu items is `mat-menu-item`, not `matMenuItem`.
3. You have to open the menu so the items can be rendered in the DOM.

Here's a working example: https://stackblitz.com/edit/harness-issue-dvjngm?file=src%2Fapp%2Fbutton-harness-example.spec.ts,src%2Fapp%2Fbutton-harness-example.html
