### ISSUE TITLE
feat(palette): allow to separate "warn" and "error" palette colors

### ISSUE THREAD

**Issue by raphael22** [angular/components#25433]
### Feature Description

Warning and Error are two distinct state that should be separate IMO.

And for now, we can't easily distinct warning state from error in material theme generation.

### Use Case

Having a warning state distinct from an error state.
![image](https://user-images.githubusercontent.com/3912356/183870845-a8b68ecb-eff3-4198-8faf-fbe6a188a621.png)

**Comment by andrewseguin** [comment]
It's not clear what is being asked here - do you want to have a separate "error" palette alongside primary, accent, and warn?

**Comment by raphael22** [comment]
Yes, to handle warning and error state separately.

I add a "warn-accent" palette for error state (as 'error' token can't be used).

But this implies lot of custom implementation and documentation to be use as class helper for large team. (as the [color] attributes won't allow custom palette name).

**Comment by amysorto** [comment]
The palette colors come from the material spec. In both M2 and M3 there is `error`, but no `warn` color palette. Closing this issue since these components are based off on the material color palettes.
