### ISSUE TITLE
bug(mat-option/): ::before on mat-option doesn't work anymore

### ISSUE THREAD

**Issue by FromageGratuit** [angular/components#25437]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.3.9

### Description

style like below is now ignored: 

`.mat-option {
  &::before {
    min-width: 20px;
    content: '';
  }
  &.mat-selected::before {
    font-family: 'Material Icons';
    content: '\e5ca';
  }
}
`

### Reproduction

Steps to reproduce:
1. style mat-option's before pseudo element

### Expected Behavior

https://stackblitz.com/edit/angular-37wm25-kbrrqx?file=src/app/select-overview-example.scss (13.3.9)

### Actual Behavior

https://stackblitz.com/edit/angular-n8xz94?file=src/app/select-overview-example.scss (14.1.1)

### Environment

- Angular: 14.1.1
- CDK/Material: Material
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Closing the issue since `::before` is an implementation detail of `mat-option` and as such we don't make any guarantees that it won't change. Recently we started using it to render focus indicators for high contrast mode users.
