### ISSUE TITLE
How to set stroke with on mat-icon.

### ISSUE THREAD

**Issue by patrickcerny** [angular/components#25436]
### What are you trying to do?

I'm trying to change the stroke width to 300. I am using the official @angular/material package. I cannot find any documentation on how to change the stroke width as on https://fonts.google.com/icons. 

### What troubleshooting steps have you tried?

I've tried to change the  contents of the `<link>`'-tag which imports the css file.

### Reproduction

Using angular and material.

### Environment

Angular CLI: 14.0.4
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

**Comment by amysorto** [comment]
On that fonts.google.com/icons page, they have a tool to give you the corresponding css. On the left hand side you can customize the icons to your specifications, and then if you click on any icon and a panel pops out on the right with the styles.
