### ISSUE TITLE
bug(MatSelect): typeaheadDebounceInterval should not fire after blur

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#25452]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the user uses the keyboard to select an option in a mat-select and then tabs out of the field, the value is expected to be the option matching what the user typed.  Instead that value is not set until after the typeaheadDebounceInterval  has expired.

Our app was trying to save a user's selections in a mat-select to the server using the blur event.  But we were getting the wrong value since the debounce interval was still in effect.  We don't want to use selectionChange since that would fire multiple request if the user uses the arrow keys or mouse wheel.

### Reproduction

https://stackblitz.com/edit/components-issue-2uvyjq?file=src/app/example-component.html

Steps to reproduce:
1. Rapidly type 'A' and tab 
2. Value & Value On Blur will both still be N
3. About 3 seconds later value will change to A, but Value On Blur will still be N

### Expected Behavior

The search being debounced would execute immediately on blur and the value would be set correctly.

### Actual Behavior

The value of an unfocused control changes some unknowable amount of time after the user leaves the control.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by james-schwartzkopf** [comment]
I must say this fix is the opposite of what I would have expected.  So if the user types something and then leaves the control, it's value depends on how long they waited before tabbing?  That seems like it would be extremally frustrating for people doing data entry without looking at the screen.

**Comment by crisbeto** [comment]
The alternative would be to try and guess what they were trying to enter which is equally as problematic, in my opinion.

**Comment by james-schwartzkopf** [comment]
> The alternative would be to try and guess what they were trying to enter which is equally as problematic, in my opinion.

But they would get the same thing they would have gotten if they waited half a second and then tabbed.  Why force them to wait?

**Comment by crisbeto** [comment]
I'm thinking of tabbing away as more of a cancellation request than a confirmation. E.g. when entering something in an autocomplete, tabbing away doesn't accept the option that you've highlighted.

**Comment by james-schwartzkopf** [comment]
For keyboard users tab is the means of moving to the next control.  I also disagree with having autocompletes behave the way you describe.  That behavior makes things very difficult for data entry people who do not look at their screens.
