### ISSUE TITLE
bug(mat-select): Exception in combination of mat-select and mat-input

### ISSUE THREAD

**Issue by DawnSouther** [angular/components#25462]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Add mat-select and mat-input to mat-form-field, use mat-select as matPrefix, when input is clicked, mat-select will trigger click event, causing input to fail to enter

### Reproduction

https://stackblitz.com/edit/angular-2ogvvr?file=src/app/input-prefix-suffix-example.html

### Expected Behavior

can enter normally

### Actual Behavior

Click on `input` but triggers select

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This isn't something we support. Form fields can only have one form control. In this case both `matInput` and `matSelect` are form controls.
