### ISSUE TITLE
'mat-drawer-container' is not a known element not works even though i installed all necessary @Angular/material library

### ISSUE THREAD

**Issue by ksabada** [angular/components#25476]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Error: src/app/app.component.html:1:1 - error NG8001: 'mat-drawer-container' is not a known element:
1. If 'mat-drawer-container' is an Angular component, then verify that it is part of this module.
2. If 'mat-drawer-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

### Reproduction

Error: src/app/app.component.html:1:1 - error NG8001: 'mat-drawer-container' is not a known element:
1. If 'mat-drawer-container' is an Angular component, then verify that it is part of this module.
2. If 'mat-drawer-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

### Expected Behavior

Error: src/app/app.component.html:1:1 - error NG8001: 'mat-drawer-container' is not a known element:
1. If 'mat-drawer-container' is an Angular component, then verify that it is part of this module.
2. If 'mat-drawer-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

### Actual Behavior

Error: src/app/app.component.html:1:1 - error NG8001: 'mat-drawer-container' is not a known element:
1. If 'mat-drawer-container' is an Angular component, then verify that it is part of this module.
2. If 'mat-drawer-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by geromegrignon** [comment]
HI @ksabada, may you please complete the **Environment** part of your message?

**Comment by crisbeto** [comment]
It looks like the `MatSidenavModule` isn't imported in the correct place.
