### ISSUE TITLE
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

### ISSUE THREAD

**Issue by mahirkabir** [angular/components#25479]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

_Originally posted by @crisbeto in https://github.com/angular/components/issues/23670#issuecomment-1003029688_

Hello, may I know where to find the issue template?

**Comment by crisbeto** [comment]
When you press the "New issue" button, the text field is prefilled with the issue template.
