### ISSUE TITLE
bug(mat-date-range-picker): selecting the same from date twice does not triggered a change

### ISSUE THREAD

**Issue by DerBasler** [angular/components#25473]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Selecting the same from date does not trigger a change.
If I want to ignore the same date I can do that in a pipe myself. 

### Reproduction

Stackblitz demo:

https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-jyhvjs?file=src/app/app.component.ts

Steps to reproduce:

Create a MatDateRangePicker as shown in the docs
Check formControl/dateChange changes

1. Select **from**
2. Select **to**
3. Select same **from**

### Expected Behavior

Selecting the same **from** would also trigger a dateChange like if a different one would be selected.

### Actual Behavior

The change does not trigger if the same **from** date is selected.
The change is only triggered if a different **from** date  is selected.

### Environment

Angular: 13.3.0
CDK/Material: Material 13.3.0
Browser(s): Chrome
Operating System: Windows

**Comment by crisbeto** [comment]
This is working as intended. We've had the exact opposite issue reports in the past where users were expecting the change event not to fire if the same date is selected since nothing has changed.
