### ISSUE TITLE
bug(material table): Infinite loop when component has any setInterval

### ISSUE THREAD

**Issue by raghavendrars** [angular/components#25484]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a simple page which contains only material table(I have copied the material sample table stackbliz example) and related logic to bind header and display columns. In header row cell is bound with a method(function)  to return some dynamic value.  Other than this I have only 1 additional simple setInterval event inside ngOnInit. 

Problem : Header row bind method keeps on triggering whenever setInterval triggers.

Below is the stackbliz example
https://stackblitz.com/edit/angular-material-data-table-infinite-scroll-pchcho?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/11958305/185220672-c4d5d4ec-6349-4945-97da-a315166d1e45.png)

### Reproduction

Steps to reproduce:
1. add any method to mat table header binding.To know how many times its called the method add console log.
2. add setInterval to current component.
3. Watch the console, testMethod keeps on executing for earch setInterval trigger(5 second)

### Expected Behavior

Mat table header binding should not call the function when setInterval triggers

### Actual Behavior

Mat table header binding method keeps on executing when setInterval triggers

### Environment

- Angular: cli 12
- CDK/Material: mat 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by geromegrignon** [comment]
Hello, it's unrelated to Angular Material, But Angular itself.
That's how change detection works with Angular.

That's why it's encouraged to avoid calling functions in templates for performance purposes.

**Comment by crisbeto** [comment]
Closing since this is just how change detection works.
