### ISSUE TITLE
docs-bug(Typography): Possible GDPR Violation

### ISSUE THREAD

**Issue by BenjaminHofstetter** [angular/components#25480]
### Documentation Feedback

The Typography Guide suggest this

```html 
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
```

Isn't that violating the GDPR according to ...
[German Court Rules Websites Embedding Google Fonts Violates GDPR](https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html)

Maybe we should add an information or bundle fonts with the app and serve it locally. What do you think ?

### Affected documentation page

https://material.angular.io/guide/typography

**Comment by geometricpanda** [comment]
Might be worth referencing the Angular build optimization config, for inlining fonts:

https://angular.io/guide/workspace-config#optimization-configuration

**Comment by mgechev** [comment]
The Angular CLI inlines the font face definition, but you'd still need to fetch the font from a Google CDN. You can check how to use self-hosted font definition [here](https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts).

To learn more about what using the Google Fonts API means for the privacy of users, please see the [Google Fonts FAQs](https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users). Inquiries about Google Fonts can be sent to [fonts@google.com](mailto:fonts@google.com).
