### ISSUE TITLE
docs-bug(mat-form-field): Appearance of components is altered by the documentation styling itself

### ISSUE THREAD

**Issue by skopekreep** [angular/components#25510]
### Documentation Feedback

Investigating why some of my app's Angular Material components look different from those in the docs led to the observation that some of the styles from the docs pages themselves were altering the appearance of the Angular Material components embedded within.  This is likely unintentional and undesirable and may lead to confusion.

### Example
The default font size of the mat-form-field should be 14px, as pictured here in a fresh Aqngular install with a single Material component.
<img width="1792" alt="component_in_new_angular_install" src="https://user-images.githubusercontent.com/8973526/185815383-7039d3ca-d72c-426d-b8b3-f7c06b14c928.png">

But when viewed in the context of the docs, the font size is 16px.
![Chrome](https://user-images.githubusercontent.com/8973526/185815408-d9de52af-3942-482c-845d-fa3901a729a9.png)

This was observed in both Chrome and Safari on Mac.

It looked like, at least in one case, that the `<p>` tag styling of the docs was being inherited by the mat-form-field.  There may be a more thorough explanation, but I believe this illustrates the issue in a verifiable and reproducible way.

### Additional Notes
This same issue seems to be affecting `mat-input` (https://material.angular.io/components/input/overview) as well, and possibly others.

### Affected documentation page

https://material.angular.io/components/form-field/overview

**Comment by skopekreep** [comment]
@AdelSkiDzNew Thanks for taking a look at this. 

Your screenshot shows the component in an existing Material template, which may be having the same effect on the rendering of the `font-size` that I'm reporting, namely, font size values may be inherited from parent elements if not adequately declared on the component itself (which is what I suspect the issue to be).  

If you are willing, could you either share the source of your template so I can reproduce exactly your screenshot or preferably create a clean install using `ng new` and install `@angular/material` only and then drop the component on the page and see if that changes the computed font size?  Thanks.

**Comment by amysorto** [comment]
If I create a new app, I also see `font-size: 16px`.
