### ISSUE TITLE
bug(mat-tab-group): dynamic height hides overflow-x

### ISSUE THREAD

**Issue by dvdnhm** [angular/components#25538]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I use dynamicHeight with the Mat Tab Group component, the defined CSS class also hides the overflow-x

```
.mat-tab-group-dynamic-height .mat-tab-body-content {
	overflow: hidden;
}
```
It is correct on the mat-tab-body tag but missed on div with the mat-tab-body-content class.
```
.mat-tab-group.mat-tab-group-dynamic-height .mat-tab-body.mat-tab-body-active {
	overflow-y: hidden;
}
```

### Reproduction

Steps to reproduce:
1.  Set a Mat Tab Group to dynamic height
2. have wide content in the tab

### Expected Behavior

The **overflow-x** should not be hidden because of **dynamic height**

### Actual Behavior

**.mat-tab-group-dynamic-height .mat-tab-body-content** definition in the css sets the **overflow-x** to **hidden** 

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0
- Browser(s): Chrome, Safari
- Operating System: Windows, macOS, iOS

**Comment by andrewseguin** [comment]
Can you provide a stackblitz showing your issue?

**Comment by dvdnhm** [comment]
I am not sure how relevant this problem after two major versions & 1 year later... 

+ material components went through many significant updates ( & caused so much problem), probably same html structure is not there anymore.

**Comment by amysorto** [comment]
If the issue persists with the MDC based components please open a new issue, thanks!
