### ISSUE TITLE
bug(COMPONENT): Clipboard does not copy value inside bootstrap 5.2 modal

### ISSUE THREAD

**Issue by gorden0929** [angular/components#25568]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Clipboard inside bootstrap 5.2 modal is not working but show success in result.

without modal is working fine.

[repo](https://github.com/gorden0929/clipboard-bug) to reproduce bug

### Reproduction

Steps to reproduce:
1. git clone https://github.com/gorden0929/clipboard-bug
2. npm i
3. ng serve

### Expected Behavior

copy the value to clipboard.

### Actual Behavior

show success but doesnt copy the value to clipboard.

### Environment

- Angular: 14.2.1
- CDK/Material: 14.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by GiacomoRobino** [comment]
navigator.clipboard.writeText(str) seems to work

**Comment by atulhm** [comment]
I modified PendingCopy constructor to allow passing an htmlElement. when in modal, I passed an elenent within the  modal and that did the trick.

**Comment by atulhm** [comment]
One reasonable method for dealing with modal. and focus issues could be to search for a list of optional classes  that can be configured when the module is loaded.
default to body, but allow the user to either via a configuration and/or in the call to clipboard.copy pass an HTMLElement for the textarea to be appended to.

**Comment by amysorto** [comment]
I am closing this issue since, we don't support the Bootstrap components because that is a separate library.
