### ISSUE TITLE
feat(matInput): Implement possibility of 24-hour time format

### ISSUE THREAD

**Issue by leonardokrleza** [angular/components#25589]
### Feature Description

Currently it is possible to use matInput with type="time" but unfortunately it is only available in 12-hour format (AM/PM). Most people then resort to ngx-material-timepicker but it can get problematic, especially inside forms (mat-form-field, etc.). 
I think that it would be a great additional feature (and simple, at first glance) that would circumvent using two libs for single form.

### Use Case

Current time capability:
`<input matInput type="time">`

Suggested capability:
`<input matInput type="time" timeFormat="24">`

**Comment by crisbeto** [comment]
This is related to the native time input that we don't have much control over. The browser will pick the format based on the user's locale and there doesn't appear to be a way to override it.
