### ISSUE TITLE
docs-bug(mat-paginator): Consider documenting ability to change styling for page size dropdown

### ISSUE THREAD

**Issue by drk-mtr** [angular/components#25597]
### Documentation Feedback

As highlighted in https://github.com/angular/components/pull/18800, the page size dropdown looks wrong if a default formfield style is set globally.

Based on this page, the recommendation is to avoid using the "standard" or "legacy" setting for formfield appearance: https://material.angular.io/components/form-field/overview

It therefore seems to make sense to set a global default, but this breaks the page size dropdown.

My understanding is that overriding this is a case of adding a provider as follows:

```ts
        {
            provide: MAT_PAGINATOR_DEFAULT_OPTIONS,
            useValue: { formFieldAppearance: 'legacy' }
        }
```

Should this be documented?

### Affected documentation page

https://material.angular.io/components/paginator/overview

**Comment by amysorto** [comment]
The [MDC based form field](https://material.angular.io/components/form-field/api#MatFormFieldAppearance) only has `fill` and `outline` now. Since this is no longer applicable, I am closing this issue.
