### ISSUE TITLE
bug(Tab bar nav): 508 Compliance Issue

### ISSUE THREAD

**Issue by jpemberton92** [angular/components#25604]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.3

### Description

The button that is used to navigate the tab structure is not assigned a value or text.  This is causing 508 compliance issues for accessibility.  There is no way we've found via css or otherwise to access the button to either give it text or value.

### Reproduction

Steps to reproduce:
1. Place a nav mat-tab-nav-bar component with items on a page.
2.  Examine page in browser with a tool that evaluates accessibility - ie 'WAVE Evaluation Tool' extention for Chrome

### Expected Behavior

We should be able to access the button to either give it value text or have a way so if its disable to not even render it on that screen.

### Actual Behavior

The button is present and we are unable to access it through any available methods or properties to give it a value or text  or hide it.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The button is `aria-hidden` so assistive technology won't find it in the first place. If you're navigating with a keyboard, the button isn't necessary since you're navigating directly within the list.
