### ISSUE TITLE
bug(matPaginator): Mat-Paginator Background is #FFFFFF when mat-sidenav-container is #FAFAFA

### ISSUE THREAD

**Issue by dandalton1** [angular/components#25638]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Placing a paginator inside of a sidenav container causes a barely noticeable box around the paginator layout:

![image](https://user-images.githubusercontent.com/33505454/190216214-c6b2d7bb-759a-4ffc-b61e-5cd6fe2f9c0b.png)

This is because the background of the paginator is set to `white` when the sidenav container is `#fafafa`.

A workaround is to put in your global `styles.scss` the directive `.mat-paginator { background-color: transparent; }`, but that's not something we should have to do.

### Reproduction

[StackBlitz Reproduction](https://components-issue-5zegav.stackblitz.io)

The following will also reproduce the issue:

```angular
<mat-sidenav-container>
  <mat-sidenav> </mat-sidenav>
  <mat-sidenav-content>
    Some stuff...
    <mat-paginator
      [length]="500"
      [pageSize]="10"
      [pageSizeOptions]="[5, 10, 25, 100]"
    ></mat-paginator>
    Some more stuff...
  </mat-sidenav-content>
</mat-sidenav-container>
```

### Expected Behavior

The same color between the paginator and the container.

### Actual Behavior

A box

### Environment

Angular CLI: 14.1.3
Node: 16.15.1
Package Manager: npm 8.18.0
OS: win32 x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.1.3
@angular/cli                    14.1.3
@schematics/angular             14.1.3
rxjs                            7.5.6
typescript                      4.7.4

**Comment by crisbeto** [comment]
`mat-paginator` is set up primarily to work with `mat-table` which has a white background. You can add this to your stylesheet to override it:

```css
.mat-paginator {
    background: transparent;
}
```
