### ISSUE TITLE
Can't type localized symbol

### ISSUE THREAD

**Issue by AlexPshkov** [angular/components#25645]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I can't type russian letter 'б' at the angular material "chips" input.
For example, the first input: https://material.angular.io/components/chips/examples

**Comment by crisbeto** [comment]
It appears to work for me. Maybe the "б" character on your keyboard is the same key code as one of the separator keys for the chips?

![demo](https://user-images.githubusercontent.com/4450522/190509578-ee4dcc9b-d8db-4df0-93f5-c625f2614076.gif)
