### ISSUE TITLE
bug(Material): Upgrade 14.0.2 to 14.2.2 causes "node_modules/@material/base/observer-foundation.d.ts:25:75 - error TS2344: Type 'Adapter' does not satisfy the constraint '{}'"

### ISSUE THREAD

**Issue by VashJuan** [angular/components#25657]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.0.2

### Description

I'm using pretty basic founctions from Material, but after upgrading get:
`Error: node_modules/@material/base/observer-foundation.d.ts:25:75 - error TS2344: Type 'Adapter' does not satisfy the constraint '{}'.

25 export declare class MDCObserverFoundation<Adapter> extends MDCFoundation<Adapter> {
                                                                             ~~~~~~~

  node_modules/@material/base/observer-foundation.d.ts:25:44
    25 export declare class MDCObserverFoundation<Adapter> extends MDCFoundation<Adapter> {
                                                  ~~~~~~~
    This type parameter might need an `extends {}` constraint.`

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

compilation without errors

### Actual Behavior

errors as mentioned above

### Environment

- Angular: 14.2.2
- CDK/Material: 14.2.2
- Browser(s): Chrome (latest updates)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 (all updates)

**Comment by VashJuan** [comment]
Going from:
`export declare class MDCObserverFoundation<Adapter> extends MDCFoundation<Adapter> {`
to:
`export declare class MDCObserverFoundation<Adapter extends {}> extends MDCFoundation<Adapter> {`
in file node_modules/@material/base/observer-foundation.d.ts:25:75 
seems to fix it.

**Comment by crisbeto** [comment]
This looks like an issue with MDC so it should be reported here: https://github.com/material-components/material-components-web.
