### ISSUE TITLE
docs: Actualize "What we're working on now" in README

### ISSUE THREAD

**Issue by AlexElin** [angular/components#25652]
### Documentation Feedback

Actualize "What we're working on now" section in README file.
At present it is for Q4 2021.

![image](https://user-images.githubusercontent.com/13061803/190889127-ddb1d1fd-bce4-490e-bb6b-78a255b67436.png)

### Affected documentation page

https://github.com/angular/components/blob/main/README.md

**Comment by ferrorenan** [comment]
Hey guys, Can I get this issue and resolve it!?

**Comment by anisabboud** [comment]
Seems resolved by https://github.com/angular/components/commit/90e7f30af4b4c6c40397ffc36ee8964f66dfe8e5 🎉
