### ISSUE TITLE
bug(MatMenu): focusFirstItem is not working

### ISSUE THREAD

**Issue by AndiBern** [angular/components#25658]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.3.1

### Description

We are opening some matMenus programmatically which sets a visible focus on the first element of the menu. To be consistent we also focus the first element manually when the users opens the menu via click. 
With Angular 14 this function does not work anymore. 

### Reproduction

StackBlitz with Angular 14: https://stackblitz.com/edit/angular-14-broken-focus-first-item?file=src/app/app.component.html

- in the file "app.component.html" I set (menuOpened)="demo.focusFirstItem()" which does visible focus the first item of the menu

StackBlitz with Angular 13, to prove it was working with Angular 13: https://stackblitz.com/edit/angular-material-13-focus-first-item?file=src/app/app.component.html

### Expected Behavior

If I call focusFirstItem(), the first item in the menu should be in correct focus.
As the default parameter is 'program' and programmatic opening of menus sets usually the visible focus, same as 'keyboard' parameter.

### Actual Behavior

focusFirstItem() does nothing

### Environment

- Angular: 14.2.2
- CDK/Material: 14.2.2
- Browser(s): Chrome

**Comment by crisbeto** [comment]
For what it's worth, focus does land on the first item, but it doesn't appear to have the correct origin.
