### ISSUE TITLE
Bug (Dialog Component) accessibility issue : Aria hidden element must not be focusable or contain focusable elements

### ISSUE THREAD

**Issue by sahithiKondapalli** [angular/components#25664]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Following Accessibility issue reported in angular dialog component when I ran accessibility scan using "Axe Dev tools"

" Aria hidden element must not be focusable or contain focusable elements"

Environment
Angular: 14.0.0

CDK/Material: 14.2.1

"dependencies": {
"@angular/animations": "~14.0.0",
"@angular/cdk": "14.2.1",
"@angular/common": "~14.0.0",
"@angular/compiler": "~14.0.0",
"@angular/core": "~14.0.0",
"@angular/forms": "~14.0.0",
"@angular/material": "14.2.1",
"@angular/material-moment-adapter": "14.2.1",
"@angular/platform-browser": "~14.0.0",
"@angular/platform-browser-dynamic": "~14.0.0",
"@angular/router": "~14.0.0",
"moment": "^2.18.1",
"rxjs": "~7.4.0",
"tslib": "^2.3.0",
"zone.js": "~0.11.5"
},

Browser(s): Chrome

Operating System (e.g. Windows, macOS, Ubuntu): Mac (Also noticed on Windows as well)

### Reproduction

- Go to https://material.angular.io/components/dialog/overview
- Install Axe Dev Tools extension from [here](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)
- Open the Dialog
- From the dev tools click on the axeDevTools tab and scan the entire page
- You would notice the issue.
- Expected Behavior
- Expectation would be no accessibility issues reported on this component.

### Expected Behavior

The issue shouldn't be shown

### Actual Behavior

Seeing the following issue.

" Aria hidden element must not be focusable or contain focusable elements"

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is only a problem if the element is actually able to receive focus. Since our dialog has a focus trap, this won't affect users.
