### ISSUE TITLE
bug(mdc-migration): content has changed error executing migration

### ISSUE THREAD

**Issue by mcalmus** [angular/components#25671]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Trying to run the Material 15 mdc-migration schematics script it keeps erroring out with `Content at path "<filepath>" has changed between the start and the end of an update.`

### Reproduction

I don't really know how to provide a reproduction or even how to demonstrate the problem.

### Expected Behavior

Migration succeeds

### Actual Behavior

Migration fails

### Environment

- Angular: 15.0.0-next.2
- CDK/Material: 15.0.0-next.1
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mcalmus** [comment]
Removing the file listed in the error just moves the filename listed to the next down the line.

**Comment by crisbeto** [comment]
This one should be resolved after some of the recent migration changes.
