### ISSUE TITLE
bug(*): Mat-menu in floating toolbar above dialog renders menu items behind the toolbar

### ISSUE THREAD

**Issue by JonWallsten** [angular/components#25677]
### Is this a regression?

No

### Description

I have a mat-dialog component and on top of that I have a floating/movable toolbar. 
In that toolbar I have split-button with a dropdown (mat-menu).
But the z-index in the `cdk-overlay-container` is making this problematic.
Right now I have to choose to have the toolbar behind the component, or the dropdown behind the toolbar.

![image](https://user-images.githubusercontent.com/5993909/191736880-98b834a9-1566-4cf0-972f-949d70b371cd.png)

![image](https://user-images.githubusercontent.com/5993909/191738759-dd4af2c2-e3ba-44d4-b63f-e1b8ea704544.png)

Is this as designed? Is there any workarounds?

### Reproduction

Steps to reproduce:
1. Pass a component into mat-dialog.
2. Add a component outside of the dialog and set `position: fixed` and `z-index: 1001`.
3. Add a mat-manu to the outside component.
4. Open the menu. It will be behind the outside component.

### Expected Behavior

The menu should not be behind the component opening the menu.

### Actual Behavior

Menu is hidden behind the button triggering it.

### Environment

Angular CLI: 14.2.3
Node: 16.17.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.2.3
@angular/cli                    14.2.3
@ngtools/webpack                14.2.3
@schematics/angular             14.2.3
ng-packagr                      14.2.1
rxjs                            7.5.6
typescript                      4.8.3
webpack                         5.74.0

**Comment by crisbeto** [comment]
This is working as designed with the idea being that stacking only applies between overlays created using the `cdk/overlay` module. If you create your toolbar using the CDK, it should stack as expected.
