### ISSUE TITLE
bug(COMPONENT): How to display percentage on horizontal stacked bar graph using ngx-charts in angular

### ISSUE THREAD

**Issue by PriyankaNGowda** [angular/components#25686]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

How to display percentage inside the horizontal stacked bar graph using ngx-charts?
is there any other way to display percentage(%) based on positive and negative feedback given by the user on the bar graph in angular?

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

How to display percentage inside the horizontal stacked bar graph using ngx-charts?
is there any other way to display percentage(%) based on positive and negative feedback given by the user on the bar graph?

### Actual Behavior

How to display percentage inside the horizontal stacked bar graph using ngx-charts?
is there any other way to display percentage(%) based on positive and negative feedback given by the user on the bar graph in angular

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing since ngx-charts isn't maintained in this repository.
