### ISSUE TITLE
help(COMPONENT): <mat-progress-bar> or <progress>?

### ISSUE THREAD

**Issue by sh977218** [angular/components#25683]
### What are you trying to do?

According to Mozilla (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA#sect2), they suggest using native HTML element `<progress>` over `<div>` when enhance website's accessibility. I know Angular Material also take accessibility as high priority, why does Angular Material decide to use `<div>` as progress bar?

### What troubleshooting steps have you tried?

N/A

### Reproduction

N/A

### Environment

- CDK/Material:

**Comment by crisbeto** [comment]
It's because the Material Design progress bar supports more features than the native one and the native progress bar isn't as customizable.

**Comment by sh977218** [comment]
That makes sense. Thanks for the answer.
