### ISSUE TITLE
feat(cdk/menu): Support passing additional context data like material/menu

### ISSUE THREAD

**Issue by jneuhaus20** [angular/components#25708]
### Feature Description

Angular Material Menu lets you pass additional data to the template when using lazy rendering (see [Menu | Passing in data to a menu](https://material.angular.io/components/menu/overview#passing-in-data-to-a-menu)).  In order to implement this in terms of CdkMenu and offer a consistent feature set across presentation patterns, CdkMenu needs to support this as well.

I think `CdkMenuTriggerBase` and `CdkMenuBase` both need to implement this in concert so it has full support across the family of derived classes, and offers the most extensibility for library consumers.

### Use Case

One use case that is currently supported by MatMenu, but _not_ CdkMenu, is using a single menu to support a list of items, with contents determined dynamically per item.

Example template:
```html
<!-- A list of things  -->
<button *ngFor="let item of items" [matMenuTriggerFor]="menu" [matMenuTriggerData]="{item}">
  {{ item.label }}
</button>

<!-- Each one has the same menu with the same items, but some might be disabled -->
<mat-menu #menu="matMenu">
  <ng-template matMenuContent let-item="item">
    <button mat-menu-item>Rename</button>
    <button mat-menu-item [disabled]="item.isRemovable">Remove</button>
  </ng-template>
</mat-menu>
```

Making a dedicated component would arguably be overkill, and this could not currently be refactored into a context menu (say to provide a primary action by clicking on each item) without looking for a suitable third-party library.

**Comment by jelbourn** [comment]
cc @mmalerba
