### ISSUE TITLE
bug(badge): matBadgePosition non-compound values defaults the cross axis to "after" or "above"

### ISSUE THREAD

**Issue by martin-the-geek** [angular/components#25707]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

matBadgePosition accepts the following values:

- above after
- above before
- below before
- below after
- before
- after
- above
- below

When the value is either "before" or "after" the style `mat-badge-above` is added.

When the value is either "above" or "below" the style `mat-badge-after` is added.

### Reproduction

![image](https://user-images.githubusercontent.com/22961746/192391699-5af27a3a-c52a-4ad3-a40f-0a417e1e725b.png)

### Expected Behavior

When the position is either "before" or "after", then the badge should be neither "above" nor "below".

When the position is either "above" or "below", then the badge should be neither "before" nor "after".

### Actual Behavior

When the position is either "before" or "after" the badge is also positioned above.

When the position is either "above" or "below" the badge is also positioned after.

### Environment

- Angular: 14.1.3
- CDK/Material: 14.1.3

**Comment by martin-the-geek** [comment]
The issue is that the position styles are applied as positive and negative checks (`isAbove()` and `!isAbove()`) instead of checking applying the "below" style only if a separate below check succeeds.

https://github.com/angular/components/blob/36af2a3fbec56ef96b0f0f4fa93f770464e92a7d/src/material/badge/badge.ts#L54-L57

And the `isAbove` and `isAfter` should be checking if "above" or "after" is found instead of checking if the opposite value was not found.

https://github.com/angular/components/blob/36af2a3fbec56ef96b0f0f4fa93f770464e92a7d/src/material/badge/badge.ts#L152-L160

**Comment by wagnermaciel** [comment]
Hi, this appears to be working as intended. The badge defaults to the most common use case when values are unspecified while still allowing users to configure for specific use cases
