### ISSUE TITLE
Add autocompleteOff to MatFormFieldDefaultOptions

### ISSUE THREAD

**Issue by StefanKern** [angular/components#25700]
### Feature Description

**Feature Description**

Please add an option to MatFormFieldDefaultOptions to disable the autocomplete on the field.
This will allow us to default all form fields with disabled autocomplete without specifying the `autocomplete="off"`on each one. Add the field to MatFormFieldDefaultOptions and default the value of the autocompleteOff input of MatFormField this this value (I think this is trivial)

**Use Case**
In our app our UX team wants all autocompletes on all forms to be turned off default, so setting it on each from is overkill. We have to specify `autocomplete="off"` on every single usage of MatFormField which is tedious and becomes error prone. Add this feature would eliminate this issue for us.

PS: this feature request is based on this feature request: https://github.com/angular/components/issues/16243

**Comment by Totati** [comment]
I think MatFormField has nothing to do with this. It does not have the reference of the underlying native input which could be a select too. Select does not have autocomplete attribute. This feauture could be implemented in MatInput, however IMO it's easy to create a directive that matches the `[matInput]:([autocomplete])` selector which dose this thing for you.

**Comment by nlmarco** [comment]
We already tried the approach using a directive, but since it seems to be impossible to register _global_ directives since Angular 2.0, this is not a good approach. We'd need to import a new module (containing the directive) into dozens of other modules :disappointed:

**Comment by crisbeto** [comment]
I see how this can be useful, but as @Totati said above, the Material input has nothing to do with the autocomplete so introducing a feature like this would be additional maintenance cost for no benefit. We'll also have to introduce an `@Input() autocomplete` in case some input fields need to be different from the default. There's also the issue that if we do it for `autocomplete`, we might as well do it for all the other attributes in the HTML spec.
