### ISSUE TITLE
bug(material/core): Luxon date adapter not support initial Luxon DateTime object

### ISSUE THREAD

**Issue by Vevl** [angular/components#25710]
### Is this a regression?

- No

### Description

When I use Luxon DateTime object to init form control date is not visible in the datepicker. 

### Reproduction

1. Create form control with luxon DateTime `luxonControl = new FormControl(DateTime.now())`
2. Add this control to datepicker 
```
<mat-form-field>
      <mat-label>Luxon datepicker</mat-label>
      <input matInput [matDatepicker]="dp" [formControl]="luxonControl" />
      <mat-hint>MM/DD/YYYY</mat-hint>
      <mat-datepicker-toggle matSuffix [for]="dp"></mat-datepicker-toggle>
      <mat-datepicker #dp></mat-datepicker>
</mat-form-field>
```
3. Date is not visible in UI

### Expected Behavior

Luxon DateTime should be parsed in `deserialize` method.

Here is my fork with edited code I just messed up the commit message and I don't have local environment so if somebody can test it, it would be great.

https://github.com/angular/components/compare/main...Vevl:components:vevl-patch

### Actual Behavior

Datepicker not showing the date if there is a Luxon DateTime object as input.

### Environment

- Angular: ~14.2.0
- CDK/Material: ^14.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Vevl** [comment]
@crisbeto

**Comment by crisbeto** [comment]
I took a look into this, but I believe that the current logic already works like this. In the `DateTime.now()` example, `deserialize` is going to go all the day down to this call: https://github.com/angular/components/blob/main/src/material-luxon-adapter/adapter/luxon-date-adapter.ts#L238 which in turn looks like this: https://github.com/angular/components/blob/main/src/material/core/datetime/date-adapter.ts#L221

**Comment by Vevl** [comment]
@crisbeto you're right I have no idea why it was not working for me back then.
https://stackblitz.com/edit/angular-inhbib?file=src/app/datepicker-value-example.ts
--> stackblitz with reproduction and as you said its working.
