### ISSUE TITLE
OutlineGapPositioning(MatFormField): Outline gap not moving to center when floating label is aligned to center

### ISSUE THREAD

**Issue by lyba-alphai** [angular/components#25712]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi I am trying to use the `matformfield ` with everything center aligned. 

Expected behavior is that the text field should have centered aligned everything when `appearance="outline"`. I was able to get the floating label to center but the outline gap is not calculated correctly and it is not aligned with the label. It did move a bit but it is still not aligned. 
I tried to update the margins using `.mat-form-field-outline-gap` but it did not work. I have attached an image showing the issue and I need the gap to be positioned according to the label position.

![image](https://user-images.githubusercontent.com/108064246/192500968-11f050bb-dcf7-48d9-9097-30e53665d6cf.png)

### Reproduction

Steps to reproduce:

Just give this to the form field 
```
 .mat-form-field-label{
    text-align: center;
  }
```

### Expected Behavior

Expected behavior is that the text field should have centered aligned everything when `appearance="outline"`.

### Actual Behavior

Outline gap is not calculated correctly and it is not aligned with the label. It did move a bit but it is still not aligned. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing the issue since centering the label isn't supported.
