### ISSUE TITLE
help(cdk-dialog): Not able to override position of the dialog 

### ISSUE THREAD

**Issue by vatsalRai** [angular/components#25737]
### What are you trying to do?

I upgraded from @angular/cdk-experimental/dialog to @angular/cdk/dialog 

### What troubleshooting steps have you tried?

I found that the `position: DialogPosition` property was no longer there in `DialogConfig` class.  

What is the correct way to override the default position (center) of the dialog?

### Reproduction

https://stackblitz.com/edit/angular-ivy-el1p3b?file=src%2Fapp%2Fdialog%2Fdialog.service.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdialog%2Fdialog-ref.ts,src%2Fapp%2Flogin%2Flogin.component.ts,src%2Fapp%2Flogin%2Flogin.component.scss,src%2Fapp%2Fapp.component.html

### Environment

- Angular: 14.2.2
- CDK/Material: >= 14 < 15
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): win32 x64

**Comment by crisbeto** [comment]
That's because it's done through the `positionStrategy` option. Here's an example: https://stackblitz.com/edit/angular-ivy-bh6xub
