### ISSUE TITLE
bug(Autocomplete): test example in docs failing

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/components#25739]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

in material docs examples for autocomplete there is a link to stackblitz which fails
[https://material.angular.io/components/autocomplete/examples#autocomplete-harness](https://material.angular.io/components/autocomplete/examples#autocomplete-harness)

it fails the tests where options panel should get opened but doesn't. I just encountered this in my workspace with material 14.2.2
the error: 
`Error: Unable to retrieve options for autocomplete. Autocomplete panel is closed.`

### Reproduction

Steps to reproduce:
```
  it('should be able to type in an input', async () => {
    const input = await loader.getHarness(MatAutocompleteHarness.with({selector: '#plain'}));
    await input.enterText('Hello there');
    expect(await input.getValue()).toBe('Hello there');
  });
```

### Expected Behavior

test pass

### Actual Behavior

test fail

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
I just tried it out and it worked. Maybe it was a flake? It's also worth noting that we run these tests on our CI and they've been passing.

**Comment by GeorgeKnap** [comment]
I just tried again and also passed . dunno what happened before
