### ISSUE TITLE
<mat-icon> color="accent" seems not working on Safari

### ISSUE THREAD

**Issue by giuseppebrb** [angular/components#25741]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Even if in other browser (eg. Chrome) the following code would set the accent color to the "home" icon, in Safari it seems that the color input is being ignored.

`<mat-icon color="accent">home</mat-icon>`

### Reproduction

Steps to reproduce:
1. Add a <mat-icon> element within a component
2. Set color to "accent"
3. Check the result on a Safari browser

### Expected Behavior

The icon should change color accordingly to the value of color input.

### Actual Behavior

On Safari, the color input seems to be totally ignored

### Environment

- Angular: @angular/core 11.2.14
- CDK/Material: @angular/material 11.2.4
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Monterey 12.6

**Comment by crisbeto** [comment]
It works for me in our local development app. Could it be something else from your app that is interfering with it?

**Comment by giuseppebrb** [comment]
Thanks for the feedback, I've noticed an error with the import of the theme in the `angular.json` file. Everything seems ok now!
