### ISSUE TITLE
bug(mat-icon): the icon is cut off in some cases

### ISSUE THREAD

**Issue by Den-dp** [angular/components#25774]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

I found that after updating from angular/material@13 to 14 - `mat-icon` started to "crop" the icon inside.

I see it in my app but also in the official angular material docs site https://material.angular.io

### Reproduction

Steps to reproduce:
1. navigate to https://material.angular.io/
2. open theme selector

### Expected Behavior
![image](https://user-images.githubusercontent.com/1770529/194593007-d39e4391-df58-4bab-9e7b-6702fd9f6c87.png)

https://v13.material.angular.io/

### Actual Behavior
**note the hight of the right mat-icon**
![image](https://user-images.githubusercontent.com/1770529/194593122-39665183-0591-455a-ae06-f025b2e1fb06.png)

https://material.angular.io/

### Environment

- Angular: 14
- CDK/Material: 14.2.4
- Browser(s): Google Chrome
- Operating System: Windows

**Comment by Den-dp** [comment]
And of course, I have the same `mat-icon` issue in my project (but in my case, it affects the checkbox `mat-icon`)
![image](https://user-images.githubusercontent.com/1770529/200573892-369187af-ff69-4d87-94db-c8c122e3fd62.png)

For now I'm using the following fix:
```css
.mat-icon {
  overflow: initial !important;
}
```
![image](https://user-images.githubusercontent.com/1770529/200573931-55d718e0-809b-4920-bb57-c53b28fb99cd.png)

**Comment by amysorto** [comment]
Seems to be working in v15 and v15 now
