### ISSUE TITLE
docs-bug(COMPONENT): Piece of shit material components

### ISSUE THREAD

**Issue by RahulSingh225** [angular/components#25819]
### Documentation Feedback

Update your piece of shit documentation to let new developers at least know from where to import your piece of shit modules from.

### Affected documentation page

https://material.angular.io/

**Comment by wagnermaciel** [comment]
Hi @RahulSingh225,

I want to ensure you that we're all focused on providing good documentation, and I'd recommend assuming good intentions.

This is not the way to request help or provide feedback, and such statements are not welcome in our communication channels.

You can find where to import modules under the API tab in our docs.
https://material.angular.io/components/autocomplete/api
