### ISSUE TITLE
help(mat-autocomplete): re-show select list with async data

### ISSUE THREAD

**Issue by raphael22** [angular/components#25827]
### What are you trying to do?

Make filled autocomplete field show list of options for async data as it does for static data from the examples.

### What troubleshooting steps have you tried?

Async pipe data won't allow autocomplete to show options after one has been selected.
Static data does.

### Reproduction

First and last example of angular material doc: https://material.angular.io/components/autocomplete/examples

First example, "Highlight the first autocomplete option" won't show select list after selection, has async data.

Last example, "Simple autocomplete" show select list after selection, has static data.

### Environment

- Angular: 13 or 14
- CDK/Material: 13 or 14
- Browser(s): Chrome
- Operating System: WSL2

**Comment by andrewseguin** [comment]
The example doesn't show more options because it is filtering the results based on the input, not because it is async. Am I misunderstanding your issue?

**Comment by raphael22** [comment]
I thought the correct behavior was dropdown showing after selection, but that's depend on filtering implementation.

Closing.
