### ISSUE TITLE
feat(MDC-MIGRATION): Handle selectable MatChip

### ISSUE THREAD

**Issue by mcalmus** [angular/components#25824]
### Feature Description

Legacy MatChip has a selectable attribute, but this has been moved to MatChipOption.

mdc-migration should change mat-chip items containing selectable attribute to mat-chip-option.

Ideally, <mat-chip [selectable]="false"> should just remove the attribute.

### Use Case

Migration from Material 14 to 15 using MDC.

**Comment by crisbeto** [comment]
What is it currently being changed to for you? As far as I can tell from our unit tests, `mat-chip` is changed to `mat-chip-option` by default: https://github.com/angular/components/blob/main/src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.spec.ts#L46

The only case where that won't happen is if there's an `input` element connected to the chip list.

**Comment by mcalmus** [comment]
My code looks more or less like this, and no change was made to it by migration:
```
<mat-chip-list>
  <ng-container *ngFor-"let c of criteria | keyvalue">
    <ng-container *ngIf="c.key === 'something'">
      <mat-chip *ngFor="let anItem of c.value" [selectable]="false">anItem</mat-chip>
    </ng-container>
  </ng-container>
</mat-chip-list>
```

**Comment by mcalmus** [comment]
I have another that looks like this that was left alone which may be what you said about inputs:
```
<mat-chip-list #chipList>
  <mat-chip *ngFor="let item of items">{{item}}</mat-chip>
  <input type="text" matInput [matChipInputFor]="chipList"
</mat-chip-list>
```
It was changed to `mat-chip-grid` during the standard 14 to 15 migration, but the `mat-chip` was left alone throughout.

**Comment by crisbeto** [comment]
Thanks for the clarification. The problem is that the schematic wasn't migrating template elements, e.g. the `*ngFor` in this case.
