### ISSUE TITLE
bug(MatTooltip): show below native html dialog

### ISSUE THREAD

**Issue by cesco69** [angular/components#25847]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

```ts
import { Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'tooltip-overview-example',
  template: `
  <dialog #dialog style="height: 50px; opacity: 0.8">
    <button matTooltip="Test">test</button>
  </dialog>
  <button (click)="openDialog()">Open</button>`,
})
export class TooltipOverviewExample {
  @ViewChild('dialog') dialog: ElementRef<HTMLDialogElement>;
  openDialog() {
    this.dialog.nativeElement.showModal();
  }
}
```

https://stackblitz.com/edit/angular-3rx9ry?file=src%2Fapp%2Ftooltip-overview-example.ts

### Reproduction

Steps to reproduce:
1. Put `MatTooltip` into `<dialog>` and open with `showModal()`

### Expected Behavior

MotTooltip show hover the dialog

### Actual Behavior

MotTooltip show under the dialog

### Environment

- Angular: 14
- CDK/Material: 14

**Comment by crisbeto** [comment]
Same root cause as https://github.com/angular/components/issues/25799.
