### ISSUE TITLE
bug(sidenav,chips): Using chip list in a sidenav results in an unavoidable horizontal scroll bar

### ISSUE THREAD

**Issue by AdamuKaapan** [angular/components#25849]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the stock Angular Material sidenav, and then adding a mat-chip-list into it, a horizontal scroll bar is always visible even if the content more than fits.

### Reproduction

Steps to reproduce:
1. Add an empty `mat-sidenav-container` with a `mat-sidenav` and `mat-sidenav-content`
2. In the `mat-sidenav`, add a `mat-chip-list` and at least one `mat-chip` with text
3. Observe the horizontal scroll bar visible at the bottom. In the StackBlitz, I also see a vertical scroll bar, but this is not happening in my personal project.

[StackBlitz](https://stackblitz.com/edit/angularmaterial-sidenav-chip?file=src/app/sidenav-overview-example.html)

### Expected Behavior

The chips should fit in the sidenav with no issue and no scroll bar should be visible unless a max width was imposed.

### Actual Behavior

The chips cause a horizontal scrollbar to appear. Removing the chips or using other content causes the scrollbar to go away - it is only present when chips are also present.

A vertical scroll bar also seems to appear in the provided StackBlitz but my personal project has not hit this issue, only the horizontal one.

### Environment

- Angular: CLI 14.2.4
- CDK/Material: 14.2.3
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows (WSL 2), whatever StackBlitz uses

**Comment by zarend** [comment]
The negative margin is likely the culprit here.

**Comment by CrowhopTech** [comment]
Hi @zarend - I see the "Fixed in MDC" label and found the PR moving chips to use MDC. Is that change pulled into a release yet so I can grab it?

**Comment by zarend** [comment]
Hi @CrowhopTech ,

The MDC components will be available in the upcoming v15 release. If you would like to use them sooner, they're available in the `rc` and `next` releases.

-Zach

**Comment by amysorto** [comment]
Tested with MDC based components, the scroll bar does not appear anymore
