### ISSUE TITLE
bug(mat-chip-list): Accessibility issue: [aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by CruddyShad0w** [angular/components#25841]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running lighthouse against any `mat-chip-list` that is currently empty the following accessibility issue occurs _[aria-*] attributes do not match their roles_

This seems to occur after an implementation in:https://github.com/angular/components/issues/7564
This dynamically set the role, but leaves the `aria-` attributes set causing the accessibility issue.

Screenshots that depict the issue in lighthouse:
![image](https://user-images.githubusercontent.com/38229188/197057802-aec7ddeb-8642-4f15-8829-b5df11d47154.png)

### Reproduction

Steps to reproduce:
1. Navigate to the angular material chips examples: https://material.angular.io/components/chips/examples
2. Remove the options pre-filled in the Chips Autocomplete example
3. Run lighthouse in snapshot mode from the chrome developer tools.

### Expected Behavior

No accessibility issue for `mat-chip-list` under "Serious"

### Actual Behavior

"[aria-*] attributes do not match their roles" accessibility issue

### Environment

- Angular: 14.2.6
- CDK/Material: 14.2.5
- Browser(s): Google Chrome Version 106.0.5249.119 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by amysorto** [comment]
The test is passing in lighthouse for the new MDC based components coming soon in v15.
