### ISSUE TITLE
bug(google-maps): Method google.maps.Map.setCenter throws TypeError: setCenter is not a function

### ISSUE THREAD

**Issue by eldarj** [angular/components#25853]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

#### Issue
Calling setCenter method on a `google.maps.Map` object breaks with following error message

> TypeError: setCenter is not a function

I more or less followed the Autocomplete Places guide on developers.google.com: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

This is the error
![image](https://user-images.githubusercontent.com/28787596/197398492-3a55fcca-04b4-4ff2-8945-ecc78d66d72a.png)

---
#### Versions
```
"@angular/core": "~13.0.0"
"@angular/google-maps": "^13.3.9"
```

Below is the part of the sample that I have in place.

I lazily load google maps and once done, I add a listener to the `google.maps.places.Autocomplete` - `place_changed`

When the input changes, this function gets executed without issues. However, calling `setCenter` with a valid `latLng` object fails.

#### Module
```
imports: [
    GoogleMapsModule,
    HttpClientModule,
    HttpClientJsonpModule,
]
```

#### Component Html
```
<google-map #mapRef [options]="options" [center]="center"></google-map>
```

#### Component Typescript
```
googleMapsLoaded: Observable<boolean>;
@ViewChild('mapRef') mapRef: google.maps.Map;
@ViewChild('addressInputRef') addressInputRef: any;
center: google.maps.LatLngLiteral = {
    lat: 25.0893271,
    lng: 55.1458288
  };

  options: google.maps.MapOptions = {
    zoom: 15
  }

ngAfterViewInit(): void {
    this.googleMapsLoaded = this.httpClient.jsonp(
      'https://maps.googleapis.com/maps/api/js?key=my-key&libraries=places',
      'callback').pipe(
      map(() => {
        let autocomplete = new google.maps.places.Autocomplete(
          this.addressInputRef.nativeElement
        );

        autocomplete.addListener('place_changed', () => {
          let place = autocomplete.getPlace();

          if (!place.geometry || !place.geometry.location) {
            return;
          }

          // here I get the place.geometry.location without issues, but setCenter breaks
          // I also tried instantiating a new google.maps.LatLng, but same issue
          this.mapRef.setCenter(place.geometry.location);
        });

        return true;
      }), catchError(() => of(false)),
    );
  }
```                          

### Reproduction

Steps to reproduce:
1. Follow code in issue description
2. or follow https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

### Expected Behavior

I expect the map to refresh with the new latLng position

### Actual Behavior

setCenter throws `TypeError: this.mapRef.setCenter is not a function`

### Environment

- Angular: 13.0.2
- CDK/Material: -
- Browser(s): Google Chrome 105.0.5195.125 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
You're getting that error, because the `GoogleMap` component doesn't have a `setCenter` method and you aren't getting a compilation error, because you're using the wrong type for `mapRef`.

**Comment by eldarj** [comment]
So, where's the gotcha in the above code, what's wrong, and what should be different? Inspecting the type in runtime will show the same type as the source code when checking from IDE, and the source code shows that a `setCenter` method exists, however at runtime it breaks.

Is the above missing a @types package or I'm using a wrong one?

**Comment by crisbeto** [comment]
Closing since there hasn't been any activity after the previous comment.
