### ISSUE TITLE
feat(google-maps): Add offset (or anchor, or position) option to Marker's label object

### ISSUE THREAD

**Issue by themos-exelia** [angular/components#25857]
### Feature Description

Just an easy way to offset the label's position, so that it does not overlap with the marker's svg path or png icon.

### Use Case

When the map is zoomed out, I would like the marker's Label to not overlap with its (custom) icon

**Comment by zarend** [comment]
Hello @themos-exelia ,

Generally, we accept feature requests that can clearly be implemented with the [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API).

I believe there already exists documentation of managing overlapping marker with label. See[Managing markers, labels, and POI collisions](https://developers.google.com/maps/documentation/javascript/manage-marker-label-collisions). Does that resolve the issue for you?

-Zach

**Comment by themos-exelia** [comment]
Hi @zarend! Thank you for the prompt reply, I tried specifying the `collisionBehavior:
    google.maps.CollisionBehavior.REQUIRED_AND_HIDES_OPTIONAL,`, and also the `REQUIRED` option, but to no avail...
Even with the `v=beta` trigger, the labels are still rendered over the marker symbol:
![image](https://user-images.githubusercontent.com/111559645/197624269-c6dec995-5f9a-49bd-8224-ef2f4eaebb82.png)

All I need is a way to offset/move the label just a few pixels below the marker symbol, it's not an issue of multiple markers overlapping with one another.

**Comment by amysorto** [comment]
I am closing this bug since this seems to be related to the API itself. You can [file an issue for the Google Maps API](https://issuetracker.google.com/issues/new?component=188853&template=788207) if your problem has not been resolved.
