### ISSUE TITLE
bug(DatePicker): Fix shortcut to open datepicker

### ISSUE THREAD

**Issue by DannyBoyNg** [angular/components#25868]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The shortcut to open/close the datepicker is Alt+up/down. The problem is the datepicker also opens when I press Ctrl+Alt+down or even Ctrl+Shift+Alt+down. That is super annoying because I use those shortcuts for other things. Can we please put a check in that Ctrl and Shift are not pressed before opening the Datepicker. So only Alt+down. That would be extremely helpful.

### Reproduction

Steps to reproduce:
1. Press Ctrl+Alt+down
2. Press Ctrl+Shift+Alt+down

### Expected Behavior

I expect the Datepicker not to open when either Ctrl or Shift are pressed.

### Actual Behavior

The Datepicker will open.

### Environment

- Angular: 14.2.6
- CDK/Material: 14.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by sasidharansd** [comment]
Can I work on this bug? I would love to take this if its okay.
