### ISSUE TITLE
bug (MatTabNav): Active tab indication disposition on right-to-left

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#25877]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using nav mat-tab-nav-bar on right-to-left html document incorrectly shows the active tab indicator to the left rather than the right.

### Reproduction

Steps to reproduce:
1.  Set html dir=rtl
2. Add mat-tab-nav-bar tag with one mat-tab-link.

```html
<html>
<body dir="rtl">
  <nav mat-tab-nav-bar>
    <a mat-tab-link>Show me</a>
  </nav>
</body>
</html>
```

### Expected Behavior

The active indication should have shown to the right.

### Actual Behavior

The indication shows to the left.

### Environment

- Angular: 1.14
- CDK/Material: 1.14
- Browser(s): Chrome / Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment]
Hello @zehavibarak ,

I cannot reproduce. Could you provide a Stackblitz reproduction using https://stackblitz.com/fork/components-issue?

-Zach
