### ISSUE TITLE
MatStepper Doesn't Allow Styling

### ISSUE THREAD

**Issue by mswilson4040** [angular/components#25872]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to apply basic styling to the MatStepper. However, the styles seem to get completely stripped out. If I use the deprecated `::ng-deep`, things work just fine. But, `::ng-deep` is being (or is) deprecated. What is the proper way to do this?

Example:
Trying to hide the `.mat-horizontal-stepper-header-container` and change the background of `.mat-horizontal-content-container` to red.

```
.mat-horizontal-stepper-header-container {
  display: none !important;
}

.mat-horizontal-content-container {
  background: red !important;
}
```

But this works just fine:
```
::ng-deep .mat-horizontal-stepper-header-container {
  display: none !important;
}

::ng-deep .mat-horizontal-content-container {
  background: red !important;
}
```

Repro:
https://stackblitz.com/edit/angular-ylfbfk?file=src/app/stepper-overview-example.css

Expected result:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/19480392/198122669-89e6e11b-5374-45c3-9ec8-8b5dfc09c909.png">

Actual result:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/19480392/198122746-9103f6ce-8cd8-4202-aa87-949f66abac79.png">

### Reproduction

https://stackblitz.com/edit/angular-ylfbfk?file=src/app/stepper-overview-example.css

### Expected Behavior

Basic styling should apply to components without needing to use the deprecated `::ng-deep`

### Actual Behavior

No styles apply to the component without specifying `::ng-deep`

### Environment

- Angular: 14.2.1
- CDK/Material: 14.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

**Comment by crisbeto** [comment]
It's because by default the styles of all components are encapsulated which means that they can only target elements within the template. You can disable it by setting `encapsulation: ViewEnapsulation.None` in the `@Component`.

**Comment by mswilson4040** [comment]
`ViewEncaplsulation.None` introduces more problems that I do not wish to deal with. I understand the encapsulation of component styles, but my question is about the recommended alternative to the deprecated `::ng-deep` if one exists. If that answer is `ViewEncapsulation.None`, it will be unfortunate.

**Comment by crisbeto** [comment]
There is no alternative, this is the whole point of view encapsulation.

**Comment by mswilson4040** [comment]
So it's either `ViewEncapsulation.None` or rebuilding the component to my standards using CDK? It seems a little much for wanting to hide a header.

I would expect some option similar to `:host`, but for `:child` or something.

**Comment by crisbeto** [comment]
That's just how view encapsulation works: it encapsulates all of the styles.

**Comment by mswilson4040** [comment]
Reiterating "it's just how it works" is not helpful.

**Comment by zarend** [comment]
Hello @mswilson4040 ,

We hope that the MatStepper meets your needs. For support requests, I believe you will get more help from a different channel, as we can only give limited support in this issue tracker. Consider asking for support on:

 - [StackOverflow](https://stackoverflow.com/questions/tagged/angular-material2)
 - [Gitter](https://gitter.im/angular/material2)
 - [Google Groups](https://groups.google.com/forum/#!forum/angular-material2)
 
 If you believe this is something that the MatStepper could do to better meet your needs, consider filing a feature request or creating a github discussion.
 
-Zach
