### ISSUE TITLE
[Help List]selecting a list-item in mat-nav-list?

### ISSUE THREAD

**Issue by diuming** [angular/components#25887]
### Feature Description

Hi,

I exercise `mat-nav-list` in `sidenav`.
How do I draw background when I selected a `mat-list-item`? (Do you provide a good way to do this?)
Can I set a default `mat-list-item` be selected?
How do I place a prefix Icon` <mat-icon matListIcon>folder</mat-icon>` in `mat-list-item`?
thanks.

```
<mat-sidenav-container>
    <mat-sidenav mode="side" opened="true">
        <mat-nav-list>
            <a mat-list-item href="..." *ngFor="let link of links"> {{ link }} </a>
         </mat-nav-list>
    </mat-sidenav>
</mat-sidenav-container>
```
![Screen Shot 2022-10-28 at 10 08 57 AM](https://user-images.githubusercontent.com/39903550/198465089-efe0cecc-80e0-44fd-9347-2e587548ae46.png)

Better

![Screen Shot 2022-10-28 at 9 41 32 AM](https://user-images.githubusercontent.com/39903550/198481874-ea8aa0c3-a9d5-4631-b5e8-e62e57059234.png)

**Comment by zarend** [comment]
The MDC-based navigation list has an `@Input activated`, which I believe is what you're looking for.

**Comment by diuming** [comment]
@zarend thanks for helping me.
I cannot see anything about `activated` description in document.
Could you give me some example.
thanks

Where can I insert `activated` in following template?
```
<mat-sidenav-container>
    <mat-sidenav mode="side" opened="true">
        <mat-nav-list>
            <a mat-list-item href="..." *ngFor="let link of links"> {{ link }} </a>
         </mat-nav-list>
    </mat-sidenav>
</mat-sidenav-container>
```

**Comment by amysorto** [comment]
As @zarend mentioned, the new MDC based navigation list has better support for this and will be available soon in v15. Here is an [explaination on how to use activated input](https://github.com/angular/components/blob/main/src/material/list/list.md#navigation-lists).

For the non MDC components (v14 and below), our [docs site](https://material.angular.io/components/categories) has an [example of a side nav-list](https://github.com/angular/material.angular.io/blob/main/src/app/pages/component-sidenav/component-nav.html#L6) that highlights the text based on what page you are on. It [uses the router to apply a special class when active](https://angular.io/api/router/RouterLinkActive), and [defines the colors in the CSS](https://github.com/angular/material.angular.io/blob/main/src/app/pages/component-sidenav/_component-sidenav-theme.scss#L29).

In terms of adding an icon to a list item, there is an example on the docs site that does that for a list component https://material.angular.io/components/list/examples#list-sections.
