### ISSUE TITLE
feat(CDK-DRAG-DROP): XY positioning mode

### ISSUE THREAD

**Issue by Identity-labs** [angular/components#25895]
### Feature Description

Add new positioning mode with floating XY mode, with defined layout, with amount of cols and rows.

I can help on this 

### Use Case

Ability to move item on the defined grid
Ability to swap item on the grid, with optional callback validator to prevent the change
Ability to set amount of colonnes and rows
Ability to have dynamic amount of colonnes and rows

**Comment by crisbeto** [comment]
This should be doable already with the `cdkDragConstrainPosition` input.
