### ISSUE TITLE
feat(Angular Google Maps): Add Support for Advanced Markers in the Angular Google Maps

### ISSUE THREAD

**Issue by skepticmonk** [angular/components#25897]
### Feature Description

please add support for advanced markers in Angular Google Maps or can you please specify when it would be added?

**Comment by LukasMachetanz** [comment]
Is there any update on this? I also would like to use Advanced Markers as described in https://cloud.google.com/blog/products/maps-platform/announcing-highly-customizable-higher-performance-markers.

**Comment by shaji-Dev** [comment]
Any update on this? AdvancedMarkerView are a breakthrough in performance and are highly useful.

**Comment by flogy** [comment]
Would be interested in this too.

**Comment by pm20390** [comment]
Would really like this feature, it's a blocker for me at the moment.

**Comment by armando-ota** [comment]
Any example of how to use it as plain JS in angular component ?

**Comment by torusservices** [comment]
Bump, please! This is very important especially when needing to define colors for the markers. As per the previous question, how did you guys manage to get around this? It's a shame that angular and google maps are not jelling well together you would think that the two teams would communicate.

**Comment by torusservices** [comment]
@amysorto How likely is it that a minor issue gets addressed by Angular Devs? If not very much can there be a debate to raise the priority?

**Comment by torusservices** [comment]
@crisbeto do you think this can be looked at? Is there any way we could help?

**Comment by amysorto** [comment]
I'll raise the priority to a P3, although we don't plan to work on this feature soon at this time. Although we would happily accept a community PR for this.

**Comment by OgiSss** [comment]
Hi I can take care of it if you don't mind.  @amysorto

**Comment by merkisoft** [comment]
@OgiSss @crisbeto thx for the advanced marker support.

MapAdvancedMarker is missing icon

could you add that pls?

**Comment by jmeinlschmidt** [comment]
Support for Advanced Markers with Marker Clusterer is currently missing. This is related to https://github.com/angular/components/issues/29187 and https://github.com/angular/components/issues/23695.

**Comment by crisbeto** [comment]
This was resolved by #28525.
