### ISSUE TITLE
bug(mat-select): Small custom option width makes it 'jump'

### ISSUE THREAD

**Issue by lapincsmatyas** [angular/components#25908]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the overlay panel is set to smaller than the form field width, the width of the panel 'jumps' a little bit. 
It is only reproducable in Safari.

### Reproduction

Steps to reproduce:
1. Create a mat-select component with mat-option entries (the [basic select example](https://material.angular.io/components/select/overview) from Angular Material site works too)
2. Add a panelClass property to the mat-select component
3. Change the panel min-width to a smaller value with !important 
4. Open the app in Safari
5. Open the mat-select component by clicking on it

[StackBlitz example](https://stackblitz.com/edit/components-issue-f91qxs?file=src%2Findex.html,src%2Fmain.ts,src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts,src%2Fapp%2Fexample-component.css,src%2Fapp%2Fmaterial-module.ts)

### Expected Behavior

The overlay panel should have the set width, but without 'jumping'

### Actual Behavior

The overlay width 'animates' to a bigger width and then jumps to the custom width.

### Environment

- Angular: 14.1.3
- CDK/Material: 14.1.3
- Browser(s): Safari 16.1
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Ventura

**Comment by amysorto** [comment]
I cannot reproduce this issue in the MDC components
