### ISSUE TITLE
bug(typography): theming typography

### ISSUE THREAD

**Issue by AnkitaSood** [angular/components#25902]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

According to [the example](https://material.angular.io/guide/typography#typography-configs-and-theming) in the guide for creating a custom typography config for a particular theme, the font-family can be overridden for a particular theme by passing a typography config while creating a theme.

I tried following the exact steps shown in the example for a custom theme. The font family for all the material components was overridden. However, the font-family for simple HTML elements (with no material classes) doesn't get overridden. 
Notice the screenshots in which the h1 tag has the same font-family, whereas the font-family of material card is clearly different. 

<img width="1977" alt="Screen Shot 2022-10-31 at 10 29 16 PM" src="https://user-images.githubusercontent.com/7992938/199152506-8b51b95d-c252-46e4-95a2-733666ea42dd.png">

<img width="1987" alt="Screen Shot 2022-10-31 at 10 29 27 PM" src="https://user-images.githubusercontent.com/7992938/199152426-6d3cc427-0ef3-4dc3-afbf-f0ec43b054a2.png">

Here's is the link to the simple demo app that I created to demonstrate this bug: https://github.com/AnkitaSood/typography-demo/blob/main/apps/mat-type-demo/src/styles.scss#L46

### Reproduction

Steps to reproduce:
1. Follow the steps to customize typography as mentioned in the typography guide https://material.angular.io/guide/typography#typography-configs-and-theming

### Expected Behavior

The typography config should be able to update the typography changes for all elements being customized for the class/ theme.

### Actual Behavior

Only material components are reflecting the typography config changes.

### Environment

- Angular: ~14.2.0
- CDK/Material: 14.2.5
- Browser(s): All modern browers
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
By default Material doesn't touch any elements outside of its own components. If you want the Material typography on other elements, you can apply the `mat-typography` class. See https://material.angular.io/guide/typography#using-typography-styles-in-your-application.

**Comment by AnkitaSood** [comment]
As evident in the screenshot, am using the `mat-typography` class to apply material typography on other elements. It doesn't update the font-family for those elements for a custom theme. The solution you have suggested doesn't work when a custom theme is used to override the default config.
