### ISSUE TITLE
Mat tool Tip (Multi Line Paragraph)

### ISSUE THREAD

**Issue by arpudhanaresh** [angular/components#25903]
### Feature Description

Hi, I needed to show larger data in mat-tool tip
WHile using linebreak, it getting in multiple lines
When laptop screen is small it hidding the larger lines(for ecample: more than 15 lines)
In more than 15 lines is it possible to get data in 2 paragraph(like 2 columns)

### Use Case

This feature may help if there is more data to show in tooltip

**Comment by nzbin** [comment]
You can check my answer on [stackoverflow](https://stackoverflow.com/questions/56620424/dont-we-have-option-for-dynamic-content-inside-mat-tooltip/68371318#68371318).

**Comment by wagnermaciel** [comment]
Currently line breaks in tooltips are not supported / part of the material design spec
