### ISSUE TITLE
bug(mat-snackbar): panelClass styles not being applied to Snack Bar in v15

### ISSUE THREAD

**Issue by pavankjadda** [angular/components#25915]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.6

### Description

When I try to Mat Snack Bar in v15.0.0-rc.1, the panelClass css is being applied.

### Reproduction

Steps to reproduce:
1. The v14 demo can be found here: https://stackblitz.com/edit/angular-ivy-nw4vhw?file=src%2Fapp%2Fapp.component.ts
2. The v15 demo can be found here: https://stackblitz.com/edit/angular-ivy-em47oi?file=src%2Fapp%2Fapp.component.html

### Expected Behavior

The snack bar should apply styles as expected

### Actual Behavior

The snack bar not applying styles as expected

### Environment

- Angular: 15.0.0-rc.1
- CDK/Material: 15.0.0-rc.1
- Browser(s): Chrom 107
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
It's because in v15 the background color is on a different element. We don't consider this a breaking change since style overrides like this are impossible to account for. Here's a working example: https://stackblitz.com/edit/angular-ivy-4rhpy3?file=src%2Fstyles.scss.

**Comment by pavankjadda** [comment]
@crisbeto Thanks. I still see **Close** button in default color. Where can I find more information about these new classes?

**Comment by pavankjadda** [comment]
Never mind, I found it. It's `--mat-mdc-snack-bar-button-color` CSS variable and Overriding it worked for me

 ```
--mat-mdc-snack-bar-button-color: var(--white-color);
```
