### ISSUE TITLE
bug(COMPONENT): Use a stepper inside a tab

### ISSUE THREAD

**Issue by abd-naj** [angular/components#25925]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

When changing the tab, The contents of the stepper is hidden, but it appears when we change  any step (at first time)

### Reproduction

example forked from angular material the official site
https://stackblitz.com/edit/angular-qv3ov2?file=src%2Fapp%2Fstepper-overview-example.html,src%2Fapp%2Fstepper-overview-example.ts

### Expected Behavior

The stepper is not affected when changing the tab

### Actual Behavior

The contents of the stepper hidden when changing the tab

### Environment

- Angular: ^14.2.6
- CDK/Material: ^14.2.6
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by geromegrignon** [comment]
Hi @abd-naj, would you have an example of your expected behavior with Angular 13?

Why would the content dedicated to a tab would stay visible by switching tab? It negates the purpose of tabs.

**Comment by abd-naj** [comment]
@geromegrignon thank you.
When i return to the tab that contains the stepper, the items are hidden.
![image](https://user-images.githubusercontent.com/25603088/200247220-582a17ae-1917-4602-a92c-bbad1e218428.png)

**Comment by geromegrignon** [comment]
Thanks for the details, I could not reproduce it first by interacting with the form before heading to another tab.
I can reproduce this by landing on the application and directly switching tabs.
