### ISSUE TITLE
feat(cdk/drag-and-drop): Animation on edge condition when transferring an item.

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [angular/components#25954]
### Feature Description

When I transfer item between columns I would like to see smooth animation same as it works on single column. When you jump between columns there is no animation at first.

https://jam.dev/c/762dbfa0-7296-468d-a813-8953f4ebbe4a

**Comment by crisbeto** [comment]
We don't support animations when an item enters or leaves a list, because it's hard to predict what the layout will look like once the item is in the new list.
