### ISSUE TITLE
bug(mat-input): readonly attribute still allows interaction 

### ISSUE THREAD

**Issue by GeorgianStan** [angular/components#25968]
### Description

**MatInput** [readonly](https://material.angular.io/components/input/api#MatInput) attribute is not working as expected. It gives the impression that the user can still interact with the input element.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/angular-ivy-frqmuz?file=src/app/app.component.html)

### Expected Behavior

If an `input` (MatInput) has the attribute `readonly` set to true, I'm expecting that no interaction is allowed with that input.

### Actual Behavior

In the code provided on StackBlitz, if the user clicks the input it still triggers the ripple effect. At the same time the user can click on the clear button and clear the content of the input.

### Environment

They are all visible on the StackBlitz example.

**Comment by crisbeto** [comment]
It behaves similarly to the `readonly` attribute of the native `input` element which looks identical to a non-readonly `input`, except that it doesn't allow the user to change the value. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly.

**Comment by GeorgianStan** [comment]
Ok, then to achieve a fully `readonly` (no interaction) appearance for an element, we should use the `disabled` attribute and update the style for our needs?

**Comment by crisbeto** [comment]
Yes, if you don't want any interactivity, the correct state is `disabled`.
