### ISSUE TITLE
bug(autocomplete): mat-autocomplete remains opened when toggling datepicker

### ISSUE THREAD

**Issue by andreidorinm** [angular/components#25960]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The issue consists in having the datepicker and the mat-autocomplete opened at the same time. 

![Screenshot 2022-11-11 at 15 56 38](https://user-images.githubusercontent.com/73621790/201390349-71898791-4a82-406d-9bc1-512944c78e9a.png)

### Reproduction

Steps to reproduce:
1. First you open the mat-form-field that uses mat-autocomplete
2. And now you try to toggle mat-datepicker at the same time and you can see that both  of them remain opened

### Expected Behavior

The desired outcome should be: When you toggle the mat-form-field that has mat-autocomplete on and then you toggle the mat-datepicker immediately after the mat-autocomplete one should close not remain opened.

### Actual Behavior

Both of them remain opened

### Environment

- Angular: 14
- CDK/Material: Material
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Same root cause as https://github.com/angular/components/issues/17352.
