### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by DevBrunoo** [angular/components#25976]
### What are you trying to do?

Translate the code comments to Portuguese, I would like to be able to use the contents of this repository to write an article

### What troubleshooting steps have you tried?

no

### Reproduction

Steps to reproduce:
1. 
2.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Same resolution as https://github.com/angular/angular/issues/48060.
