### ISSUE TITLE
docs-bug(ALL): List all CSS Variables

### ISSUE THREAD

**Issue by GrandSchtroumpf** [angular/components#25998]
### Documentation Feedback

With @angular/material@15 we can use CSS variable.
It would be very useful to list the CSS variable that are available globally (`--mdc-theme-primary`) and per component (`--mat-mdc-form-field-floating-label-scale`).
Something like [Ionic documentation](https://ionicframework.com/docs/api/action-sheet#css-custom-properties-1) would b great !

### Affected documentation page

https://material.angular.io/guide/theming
https://material.angular.io/components/:component/api

**Comment by motabass** [comment]
This seem to me as the new approach for dynamic themes. Right now im getting scss compile errors because i am using css variables in my palettes which seems not supported anymore since v15.

**Comment by crisbeto** [comment]
These CSS variables aren't technically public at the moment. We're working on a new theming API based on CSS variables that will be documented.
