### ISSUE TITLE
bug(mat-nav-list): text in dark theme is black

### ISSUE THREAD

**Issue by bulldog98** [angular/components#25996]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

latest 14.x

### Description

For example in the documentation the mat-nav-list has dark text on dark background (in dark theme)

![grafik](https://user-images.githubusercontent.com/314259/202388902-a176d965-a5d2-43d2-a626-3f3474504e3f.png)

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/categories
2. Enable a dark theme

### Expected Behavior

The text of the navigation sidebar is light on dark background

### Actual Behavior

The text of the navigation sidebar is black on dark background

### Environment

- Angular:
- CDK/Material: 15.0.0
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Could this be a caching issue on your end? This is what the site looks like for me:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/4450522/202393758-efcb8da9-f6e5-407e-8abc-d86905f03afd.png">

**Comment by bulldog98** [comment]
Yes was a caching issue.
