### ISSUE TITLE
bug(List): MatSelectionListChange requires again a deprecated property

### ISSUE THREAD

**Issue by sergiotome** [angular/components#26005]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The options attribute was removed in v14 of Angular Material, but it seems like it has been added back in v15 even though it has been directly included in the documentation as a deprecated attribute. 

### Reproduction

Steps to reproduce:
1. Create a project with Angular Material 13 that uses the MatSelectionListChange class. Class requires 3 attributes: Source, Option and Options
2. Migrate the project to Angular Material 14: The Option attribute has been removed and code needs to be updated to get rid of it 
3. Migrate the project to Angular 15: The Option attribute is added back, and has again been included in the documentation directly as a deprecated attribute.

### Expected Behavior

I didn't expect the Option attribute to be part of MatSelectionListChange since it was already removed in v14

### Actual Behavior

The attribute is again present and required in v15

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by devversion** [comment]
Oh yeah, that's a good spot. I think back when we removed it in v14, the still-experimental MDC list code was not updated.

I don't know if we would need to wait until v16 for removal here again.
