### ISSUE TITLE
feat(COMPONENT): Is it possible to keep the main row sticky until the expanded rows getting scroll past from table?

### ISSUE THREAD

**Issue by frontend-expert-member** [angular/components#26001]
### Feature Description

Hi Team,

I have a mat table with expanded rows, I would like to have a feature to keep the main row become sticky once you have expanded the row and it will be place at the top of the table while scrolling it, until you scroll past the particular group of expanded rows.

Please find the screenshot attached.
![expand-rows-](https://user-images.githubusercontent.com/19622392/202453546-31a5b3a2-77c6-45b8-b63d-d624f52a80e2.png)

Keep the marked row should be sticky and be place on top of the expanded row.
Material V11.1.0
Angular 11.1.0

**Comment by andrewseguin** [comment]
This can be done with custom CSS using position sticky
