### ISSUE TITLE
bug(chip-list): Input `selectable` not working.

### ISSUE THREAD

**Issue by infacto** [angular/components#26007]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

idk

### Description

When setting `selectable` to mat-chip-list, you can still select mat-chip. The `selectable` attr on mat-chip itself does also not work.

![chip-select](https://user-images.githubusercontent.com/60390085/202522462-d0ee81ae-6278-4156-8f5d-1ee30e2bb7b3.gif)

### Reproduction

See [demo](https://stackblitz.com/edit/components-issue-jpqf6b?file=src/app/example-component.html).

### Expected Behavior

When `<mat-chip-list [selectable]="false"><mat-chip></mat-chip></mat-chip-list>` then mat-chip should not be selectable.

### Actual Behavior

You can still select.

### Environment

- Angular: v14.2.11
- CDK/Material: v14.2.7
- Browser(s): Chrome  07.0.5304.107
- Operating System; Windows 10

Some background: The annoying thing is, that when you have this in an input and click on the form-field, it always selects the first chip. It's a very bad UX and makes it impossible to scroll through chips. Because it always scrolls back to the first pos. Anyway, selectable should work.

**Comment by crisbeto** [comment]
Your gif is showing the focus indication, not the selection indication which is a colored background.

**Comment by infacto** [comment]
Ok, then feature request for an option to disable focusable chips?

**Comment by crisbeto** [comment]
Focus indication is required for accessibility and we generally don't put in options to disable accessibility features. You can disable it in your own app with the following style override:

```
.mat-mdc-chip-focus-overlay {
  display: none;
}
```
