### ISSUE TITLE
bug(website): Can't change docs version.

### ISSUE THREAD

**Issue by infacto** [angular/components#26006]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Idk

### Description

![docs-version](https://user-images.githubusercontent.com/60390085/202517056-0ac7aa8e-6778-4869-821b-38525f6fcfa7.gif)

### Reproduction

Steps to reproduce:
1. Visit https://material.angular.io/
2. Try to change version.

Btw. when you're already on a deeper page (e.g. chip-list docs) and using this version menu. You'll land on the root path of the page.

### Expected Behavior

I wanted to view the latest Angular version 14. I need it because chip-list is not available in Angular 15.

### Actual Behavior

Not working.

### Environment

- Browser(s): Chrome Version 107.0.5304.107
- Operating System: Windows 10 (20H2 Build 19042.746)

Also tested on latest Firefox. Btw. what is to be expect with Angular Material 15 related to chip-list?

Update: I manually deleted all data from local storage, indexeddb, cookies, cache, etc and loaded the page in dev mode pressing on reload button and choose clear all and reload. A full purge. And now it works.
![image](https://user-images.githubusercontent.com/60390085/202518949-5e77f9ea-65f0-4cb0-8796-0222180c8a20.png)
It's maybe the typical Angular cache problem when updating website. -.- You can't expect the user to do that (purge all data).

**Comment by devversion** [comment]
We can reduce the max-age for the file used for determining the version picker. I will look into that

**Comment by devversion** [comment]
Should be fixed going forward: https://github.com/angular/material.angular.io/commit/0ed64783d0ddaa6ad5cfd0b5485148ef254d3667
