### ISSUE TITLE
help(mat-tab-group): Property fitInkBarToContent not working as given in example

### ISSUE THREAD

**Issue by maddybin** [angular/components#26018]
### What are you trying to do?

<mat-tab-group fitInkBarToContent>
  <mat-tab label="First">Content 1</mat-tab>
  <mat-tab label="Second">Content 2</mat-tab>
  <mat-tab label="Third">Content 3</mat-tab>
  <mat-tab label="Fourth" disabled>Content 4</mat-tab>
</mat-tab-group>

### What troubleshooting steps have you tried?

<mat-tab-group fitInkBarToContent>
  <mat-tab label="First">Content 1</mat-tab>
  <mat-tab label="Second">Content 2</mat-tab>
  <mat-tab label="Third">Content 3</mat-tab>
  <mat-tab label="Fourth" disabled>Content 4</mat-tab>
</mat-tab-group>

### Reproduction

<mat-tab-group fitInkBarToContent>
  <mat-tab label="First">Content 1</mat-tab>
  <mat-tab label="Second">Content 2</mat-tab>
  <mat-tab label="Third">Content 3</mat-tab>
  <mat-tab label="Fourth" disabled>Content 4</mat-tab>
</mat-tab-group>

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
Could you provide more context and the link to the example? It seems like the details portion is empty. We ask people follow these [steps to create an issue](https://github.com/angular/components/blob/main/CONTRIBUTING.md#-submitting-an-issue).

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
