### ISSUE TITLE
feat(fab): Basic color

### ISSUE THREAD

**Issue by infacto** [angular/components#26022]
### Feature Description

Allow basic color for FABs too. Not only for the default buttons.

https://material.angular.io/components/button/overview

### Use Case

![image](https://user-images.githubusercontent.com/60390085/202727793-6650b4c1-3a7a-45c6-8da0-470b0c722570.png)

Update:

The following works:

```html
<button mat-fab color="basic">
  <mat-icon>home</mat-icon>
</button>
```

The other buttons uses basic color, when no color attribute is set. The FAB uses accent (or primary) as fallback.

**Comment by amysorto** [comment]
The [material design spec](https://m2.material.io/components/buttons-floating-action-button#anatomy) specifies that FABs should be contrasting from the background, so I'll close this bug.
