### ISSUE TITLE
bug(list): Action buttons inside mat-list-item not clickable as of 15.0.0

### ISSUE THREAD

**Issue by lucasvanhalst** [angular/components#26023]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

When you add one or more action buttons to a mat-list-item, the click event never triggers. In version 14 or lower it would.
See stackblitz example.

### Reproduction

https://stackblitz.com/edit/components-issue-9jydqo?file=src/app/example-component.html

### Expected Behavior

Click events should not be consumed by mat-list-item, they should be propagated.

### Actual Behavior

Click events aren't triggered/propagated

### Environment

- Angular:15.0.0
- CDK/Material:15.0.0
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by benelliott** [comment]
https://github.com/angular/components/issues/26010

**Comment by amysorto** [comment]
The fix for this will be in the next patch (see the issue linked in the comment above for the relevant PR). Thanks for trying out MDC!
