### ISSUE TITLE
bug(all): directives are not standalone

### ISSUE THREAD

**Issue by ghost** [angular/components#26036]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As the standalone APIs have become stable in v15, I expected `@angular/material` directives to be declared as standalone, but it did not happen for some reason?

### Reproduction

```
import { MatTooltip } from '@angular/material/tooltip';

@Directive({
  selector: '[appCustomTooltip]',
  hostDirectives: [MatTooltip],
})
export class CustomTooltipDirective {}
```

### Expected Behavior

MatTooltip and MatLegacyTooltip should be standalone directives

### Actual Behavior

`Error: NG0308: Host directive MatTooltip must be standalone.`

### Environment

```
Angular CLI: 15.0.0
Node: 18.12.0
Package Manager: npm 9.1.1
OS: win32 x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by maartentibau** [comment]
It's a work in progress I think.
At this moment only `CdkMenu` and the sub-elements are `standalone` from what I can make of the source code.

Maybe it might be an idea to clearly state in the docs which components are already `standalone` and which ain't.

**Comment by terameta** [comment]
I agree with @maartentibau  about a list and hopefully a roadmap for the standalone directives.   
Currently I am also having the same issue with CDK Overlay, which will probably open many possibilities for most of the developers who are consuming CDK components/directives.

**Comment by maxime1992** [comment]
Agree. To add some more info about this, I'd like to use [directive composition](https://angular.io/guide/directive-composition-api) except that it requires to imports directives declared as standalone:

> Directives used in hostDirectives must be standalone: true

So I'll probably have to make some nasty work around and pass all the possible inputs etc instead of having a neat way to extend material

**Comment by wagnermaciel** [comment]
Hi, this is something that's on our radar but we still haven't been able to fully plan out. It's definitely something on the horizon, though

**Comment by michaelfaith** [comment]
@wagnermaciel if you're inviting external contributions for the standalone migration work, I'd be up for helping with it.

**Comment by andrewseguin** [comment]
Hey @michaelfaith - this work is pending some team discussion about our strategy for providing components that have a lot of dependencies. Previously, these would all be bundled in the NgModule, but as standalone we need to decide how users should consume them.

**Comment by hakimio** [comment]
If you would fix https://github.com/angular/angular/issues/48089, you could just export read-only array like [the documentation](https://angular.io/guide/standalone-components#standalone-components-for-library-authors) suggests.

**Comment by meriturva** [comment]
What I'm expecting is to use a few directives (cdkTrapFocus) has composition: https://angular.io/guide/directive-composition-api#adding-directives-to-a-component

I advise starting with the incremental adoption of "standalone" only for cdk directives with few dependencies (the same approach we are taking here on our private component library).

My two cents.

**Comment by meriturva** [comment]
Ok @hakimio but the main issue here is:

https://angular.io/guide/directive-composition-api#adding-directives-to-a-component

Specially:

_Directives used in hostDirectives must be standalone: true._

**Comment by hakimio** [comment]
Yes, I know that you can't use non-standalone directives as host-directives, my comment was meant for @andrewseguin

**Comment by michaelfaith** [comment]
> Hey @michaelfaith - this work is pending some team discussion about our strategy for providing components that have a lot of dependencies. Previously, these would all be bundled in the NgModule, but as standalone we need to decide how users should consume them.
> 
> This is something we want to do, but likely after v17

@andrewseguin  Sounds good.  At the point where you're ready to move on it, if you're inviting contributions, I'd be up for helping.

**Comment by flensrocker** [comment]
`MatSuffix` is something I want to use as host directive and stumbled upon this issue...

Without this, every user of my reusable suffix component has to remember to put that on the element. Not that bad but it would be nice to "DRY" that out...

**Comment by liesahead** [comment]
`CdkMonitorElementFocus` also can't be used that way, sadly.

**Comment by roma2341** [comment]
Please answer me why custom standalone directives can't import modules ? I need to show MyModalComponent. But it has it's own MyModalModule where I import material components. If I try to show MyModalComponent from my directive as it is it will throw me a bunch of errors e.g mat-icon is not defined, because my directive doesn't know anything about MyModalModule... i don't understand this, angular team just make feature and don't describe how should we use their standalone directives without ability to import things we need.

**Comment by michaelfaith** [comment]
If MyModalComponent isn't standalone too, then you should be importing MyModalModule into your directive's imports, rather than MyModalComponent.

**Comment by roma2341** [comment]
> If MyModalComponent isn't standalone too, then you should be importing MyModalModule into your directive's imports, rather than MyModalComponent.

The problem is that Directives doesn't have imports.

**Comment by michaelfaith** [comment]
Right, sorry.  Brain hasn't gotten up to full speed yet.

**Comment by JeanMeche** [comment]
CDK & Material were ported to standalone by #28155.
