### ISSUE TITLE
bug(MatFormField/MatSuffix): first visible Mat Suffix (inside form) triggers click on input field enter event

### ISSUE THREAD

**Issue by Venipa** [angular/components#26047]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

?

### Description

I've been experiencing issues, i've used mat suffix to display a clear button which clears the current control/input field but i experienced that input enter event also triggers a click event on mat suffix

### Reproduction

Steps to reproduce:
[stackblitz](https://stackblitz.com/edit/components-issue-wtyk5p?file=src/app/example-component.ts)

### Expected Behavior

Enter not causing mat suffix click event on first control

### Actual Behavior

Enter on inputs causes first visible suffix to trigger click event

https://user-images.githubusercontent.com/17952364/203159699-4e252767-4b02-49e0-a1b7-3ce7e88b3404.mp4

### Environment

- Angular: v15.0.0
- CDK/Material: v15.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by devcrev** [comment]
Add type="button" to your button controls.

"submit" is the default type if the attribute is not specified for buttons associated in a form, or if the attribute is an empty or invalid value. 

So pressing enter while in the form invokes the first button where you did not specify the attribute.

For reference: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type](url)

**Comment by devcrev** [comment]
And here is some documentation regarding the pressing of ENTER while in a form and how it relates to buttons in the form.[https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission](url)
