### ISSUE TITLE
bug(slider): Basic and Range Slider do no render properly inside MatDialog, when EnterAnimationDuration > 0

### ISSUE THREAD

**Issue by Jonas-wtec** [angular/components#26043]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The Angular Material Slider Component's Thumb doesn't render properly inside a Dialog Component when the default animation isn't deactivated. 

The Slider Thumb (both within Basic Slider as well as Range Slider) is not rendered at the correct location, but instead 20% to the left, when placed inside the Dialog Component without disabling its (default) enterAnimation.
 
Depending on the slider's size, this can be quite noticable. The Slider Component should behave identically whether being placed in a Dialog Component with Animation enabled or not. 
Disabling the Dialog's enterAnimation fixes the issue. 

Please take a look at my Stackblit [bug reproduction](https://stackblitz.com/edit/components-issue-d6eokh?file=src/app/example-component.ts) (or alternatively as [Application URL](https://components-issue-d6eokh.stackblitz.io)).

### Reproduction

Stackblit [bug reproduction](https://stackblitz.com/edit/components-issue-d6eokh?file=src/app/example-component.ts) (or alternatively as [Application URL](https://components-issue-d6eokh.stackblitz.io)).

Steps to reproduce:
1. Open MatDialog without disabling default enter Animation
2. Within said Dialog, place the Slider Component
3. Both basic slider and range slider will have missplaced thumbs (20% to the left of its intended value)

<img width="1268" alt="Bildschirm­foto 2022-11-21 um 23 31 25" src="https://user-images.githubusercontent.com/106608655/203094249-66d26650-d67a-4bdd-92f5-02eb81c54192.png">

### Expected Behavior

The Slider Component's Thumb should be rendered at its correct location, given by its value.

### Actual Behavior

The Slider Component's Thumb is rendered approx. 20% to the left of its intended place.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Chrome, Safari, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Tested on macOS

**Comment by csvn** [comment]
I think I encountered the same issue. My slider uses steps and is rendered inside a `MatDialog`.
As soon as a user interacts with it, the thumb pops off to the end of the track like it should.

![image](https://user-images.githubusercontent.com/8770194/204045384-7b25f809-dab0-4c51-8b0b-3adba334e777.png)
![image](https://user-images.githubusercontent.com/8770194/204046234-9ccbacec-691a-4b84-bfca-477db19ca64b.png)

I see that there is already a fix in progress though. Let's hope it's merged and that there's a patch release soon 🤞😇
