### ISSUE TITLE
bug(Tooltip): matTooltipClass is not being fully applied

### ISSUE THREAD

**Issue by gabrielw007** [angular/components#26040]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

matTooltipClass is not being fully applied.
see below - only  "white-space: pre-line;" centralizes the text but the rest has no impact on the tooltip style

 <div id="{{'testtubes_tubsBox_'+ getVesselFullId(vessel)}}" class="tubs-box grow"
           (click)="OnFocusVessel($event, vessel)" on-focusout="OnFocusOutVessel()">
        <img id="{{'testtubes_vesselImg_' + getVesselFullId(vessel)}}" tabindex="-1" [src]="getImg(vessel.vesselId)"
             class="tub-button" matTooltip="{{ showVesselToolTip(vessel) }}" matTooltipClass="vessel-tooltip-class" />
      </div>

.vessel-tooltip-class {
    background-color: #eff2f9 !important;
    color: #242424 !important;
    font-size: medium;
    font-weight: 500;
    white-space: pre-line;
    text-align: right !important;
}

### Reproduction

Attached the component and the css tooltip in the text 

### Expected Behavior

all tooltip class properties to be applied

### Actual Behavior

matTooltipClass is not being fully applied.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): chrome
- Operating System Windows 10

**Comment by crisbeto** [comment]
The panel class is being applied on the same element as before, but the new MDC-based tooltip sets the background color on a different inner element than before. Closing since it's impossible for us to account for all possible style overrides.

**Comment by gabrielw007** [comment]
Can you please specify how to modify the tooltip color and background color? which element i should use?

**Comment by crisbeto** [comment]
You would have to target the `.mdc-tooltip__surface` element.

**Comment by gabrielw007** [comment]
Thanks, that works!

I think an example about this should be added in the documentation of Tooltip.

Do you have a list of all those elements like that .mdc-tooltip__surface to modify a style of a component, like tooltip?

Usually pre-defined styles are not good enough…



Kind Regards,

***@***.***
Gabriel Wissotzky
Software Engineer
Mobile: 054 560-6798
Fax: 03 938-5505
www.orsyx.com<%20www.orsyx.com%20>
