### ISSUE TITLE
Since update to v15 I'm not able to change chip text color using [style.color]

### ISSUE THREAD

**Issue by mhosman** [angular/components#26059]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Since update to v15 I'm not able to change chip text color using [style.color]

### Reproduction

Use [style.color]

### Expected Behavior

It should change the color of the text

### Actual Behavior

Since update to v15 I'm not able to change chip text color using [style.color]

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by crisbeto** [comment]
Style overrides like this generally aren't supported by us and are at your own risk.
