### ISSUE TITLE
bug(button): Icons inside mat-button inside ng-template no longer vertically aligned

### ISSUE THREAD

**Issue by alienwareone** [angular/components#26055]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.x

### Description

Regression between legacy implementation and new MDC implementation.

### Reproduction

Correct vertical alignment with legacy implementation:
https://stackblitz.com/edit/angular-yetsx8?file=src%2Fapp%2Fbutton-overview-example.html

Incorrect vertical alignment with MDC implementation:
https://stackblitz.com/edit/angular-hr8fqg?file=src%2Fapp%2Fbutton-overview-example.html

### Expected Behavior

1. the alignment behavior should be unchanged, or
2. the change in behavior should be documented in the changelog

### Actual Behavior

The aligment is different and this is not mentioned in the changelog or migration guide.

### Environment

Angular: 15.0.0
CDK/Material: 15.0.0
Browser(s): Chrome
Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because we now use content projection to insert the icon in the correct slot. You can fix it by setting the `matButtonIcon` attribute on the `ng-template`: https://stackblitz.com/edit/angular-hr8fqg-pomzrx?file=src%2Fapp%2Fbutton-overview-example.html
