### ISSUE TITLE
bug(radio, checkbox, button): very ugly focus bug on touch devices

### ISSUE THREAD

**Issue by RobinKamps** [angular/components#26068]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

new mdc components behave very ugly on touch devices (android and win tested).
the underlying new 48x48px touch target is highlighted with a grey box on click.
labels are also highlightet with a grey box.

### Reproduction

Steps to reproduce:
go to https://material.angular.io/components/tree/examples with a touch device (android/win) and touch the elements of the checkbox tree

### Expected Behavior

no focus selection boxes on touch

### Actual Behavior

focus selection boxes appear on touch

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android, Win

**Comment by Totati** [comment]
![Screenshot_20221124-084606](https://user-images.githubusercontent.com/17689719/203723365-0c93a3e3-98a6-43fc-ab4f-0640b9c05795.png)
This is how it looks.
