### ISSUE TITLE
bug(button): mat-buttons in toolbar don't use toolbars text color

### ISSUE THREAD

**Issue by beckerjohannes** [angular/components#26063]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

When using a `mat-button` inside a `mat-toolbar` with `primary` color (like the code snippet below) the text color of the `mat-button` is not the same as the toolbar text color. For `mat-icon-button' it is correct.

```html
<mat-toolbar color="primary"
  ><span>My App</span>
  <button mat-button>Button 1</button>
  <button mat-button>Button 2</button>
  <button mat-icon-button>
    <mat-icon>share</mat-icon>
  </button>
</mat-toolbar>
```

### Reproduction

Example with Angular 15: 
https://stackblitz.com/edit/components-issue-fonhmb?file=src/app/example-component.html

### Expected Behavior

Buttons having the same text color as the regular navbar text and icon buttons.

### Actual Behavior

![image](https://user-images.githubusercontent.com/56342691/203517722-e286cd72-8579-4297-9d9b-8c07f0b4b292.png)

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by romainmoreau** [comment]
With this change, it causes another regression versus v14 when it's the buttons inside the toolbar that have a color; now in v15, the text of the buttons doesn't use the specified color , is it what's expected now?
https://stackblitz.com/edit/toolbar-colored-buttons-14?file=src/app/app.component.html
https://stackblitz.com/edit/toolbar-colored-buttons-15?file=src/app/app.component.html
