### ISSUE TITLE
docs-bug(COMPONENT): Incomplete documentation for Tooltip

### ISSUE THREAD

**Issue by giancarlo-dm** [angular/components#26078]
### Documentation Feedback

What this property do?

PositionAtOrigin

![image](https://user-images.githubusercontent.com/9747155/203796851-63b7b983-3065-4bdd-9e3b-f97f27ee26d1.png)

### Affected documentation page

https://material.angular.io/components/tooltip/api

**Comment by geromegrignon** [comment]
Hi @giancarlo-dm,

Here is the missing description:
> Default value for whether tooltips should be positioned near the click or touch origin
   instead of outside the element bounding box.

I created a pull request to fix it on the website.

**Comment by giancarlo-dm** [comment]
Thanks!
