### ISSUE TITLE
bug(mdc-chip-grid): Autocompleted chip-grid does not work with custom display function

### ISSUE THREAD

**Issue by Neloop** [angular/components#26077]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

In version 14 we created auto-completed chip-grid with form-control which contains objects in array as value and not string, the values were displayed with custom function and it worked great. But it stopped working in mdc components in version 15.

The problem is that **after focus** is moved from chip-grid, values in chip-grid changes, they are nulled, or set to empty string. But even if I set initial value as **array** into form-control something automatically changes it to **comma separated string**. Please see stackblitz below.

### Reproduction

Steps to reproduce:
1. Open stackblitz https://components-issue-doytbf.stackblitz.io
2. Add value to the chip-grid by selecting some value from the autocomplete list
3. If you try to add second value from the list or move focus from chip-grid, the first value is nulled and appears to be empty

### Expected Behavior

As pointed out earlier, this worked in 14, values in form-control were correctly stored in array and we could work with those values. But in 15 it seems that value in form-control is automatically changed from array to comma separated string.

### Actual Behavior

![image](https://user-images.githubusercontent.com/15379972/203788870-fe97b145-0315-4117-b1bd-d4728e071ecd.png)

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): latest FF
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This happens because you didn't assign a value to the `mat-chip-row` which makes it fall back to its text content as the value. It works if you set `[value]="element"` on the chip row.

**Comment by Neloop** [comment]
Thanks, it works! I can't seem to find it in documentation about chip-grid, maybe it could be added?
