### ISSUE TITLE
CdkDialogContainer: can no longer simply be extended

### ISSUE THREAD

**Issue by jambudipa** [angular/components#26071]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.5

### Description

Extending `CdkDialogContainer` now yields the following error:

> error NG2016: The component DialogContainerComponent inherits its constructor from CdkDialogContainer, but the latter has a constructor parameter that is not compatible with dependency injection. Either add an explicit constructor to DialogContainerComponent or change CdkDialogContainer's constructor to use parameters that are valid for DI.

### Reproduction

This is the unmodified code from the 14.2.5 version of the CDK which worked fine:

```
import { Component } from '@angular/core';
import { CdkDialogContainer } from '@angular/cdk/dialog';

@Component({
  selector: 'app-dialog-container',
  templateUrl: './dialog-container.component.html',
  styleUrls: ['./dialog-container.component.css']
})
export class DialogContainerComponent extends CdkDialogContainer {
}
```

### Expected Behavior

Should compile without errors.

### Actual Behavior

> error NG2016: The component DialogContainerComponent inherits its constructor from CdkDialogContainer, but the latter has a constructor parameter that is not compatible with dependency injection. Either add an explicit constructor to DialogContainerComponent or change CdkDialogContainer's constructor to use parameters that are valid for DI.

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.0
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 13.0.1

**Comment by crisbeto** [comment]
FWIW the CDK dialog container constructor hasn't changed since it was introduced. I suspect that the error here started being reported because the Angular compiler settings changed.

**Comment by appocalypseltd** [comment]
Care to elaborate? I have changed nothing other than running ng update.

In any case, it seems to be a typing problem, not sure how that would give rise to this issue?

**Comment by crisbeto** [comment]
I suspect that the `angularCompilerOptions` defaults have changed either in the Angular CLI or the compiler. Either way, this is definitely something we should resolve.

**Comment by crisbeto** [comment]
I asked around in the team and it looks like this was a bug in the compiler that will be fixed by https://github.com/angular/angular/pull/48156 in the next release.

**Comment by appocalypseltd** [comment]
How will I know when this fix is publicly available? And is it a case of my update?

**Comment by crisbeto** [comment]
You can see which fixes are out in each release in the changelog https://github.com/angular/angular/blob/main/CHANGELOG.md. It should be released next week.
