### ISSUE TITLE
bug(Input): Input of type="time" doesn't have icon and drop-down anymore

### ISSUE THREAD

**Issue by knabbema** [angular/components#26099]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

`<input matInput type="time">` presents differently in version15.0.0 and does not show the clock icon anymore. Therefore the drop-down to pick a time can no longer be accessed. The time can only be entered via number keys:
![input-timeV15](https://user-images.githubusercontent.com/67003614/204251137-ab1e149f-16f2-43d2-98a5-3949233cf3ef.PNG)

Previous version:
![input-timeV14](https://user-images.githubusercontent.com/67003614/204251213-e429174d-105e-4058-a450-339a442d0387.PNG)

### Reproduction

Steps to reproduce:
1. set type of input to time: 
`<form class="example-form">`
 ` <mat-form-field class="example-full-width">`
    `<mat-label>Pick a time</mat-label>`
    `<input matInput type="time"/>`
  `</mat-form-field>`
`</form>`

### Expected Behavior

Input field shows clock icon and drop-down can be accessed to pick a time via mouse click.

### Actual Behavior

Time can only be entered via number keys.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Edge, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is covered in the "Input" section of the upgrade guide: https://material.angular.io/guide/mdc-migration#input. You can re-enable the indicator by adding the following CSS:

```
.mat-mdc-input-element::-webkit-calendar-picker-indicator {
  display: block;
}
```
