### ISSUE TITLE
bug(COMPONENT): Material input floating label outline bug

### ISSUE THREAD

**Issue by erkanisuf** [angular/components#26102]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This happens when you click on input (on focus).
![Screenshot 2022-11-28 at 16 30 45](https://user-images.githubusercontent.com/63913743/204303172-b487cfcd-d794-45bb-b282-9542b001922f.png)

```
<div class="flex justify-center items-center h-screen w-screen login-view">
  <div class="bg-white shadow-2xl w-1/2 h-1/2 flex justify-center items-center">
    <form class="flex flex-col w-full h-full justify-center items-center self-center">
      <mat-form-field appearance="outline" class="w-1/2">
        <mat-label>Email</mat-label>
        <input matInput placeholder="Email" type="email">
        <mat-icon matSuffix><i class="fa-solid fa-user p-4"></i></mat-icon>
      </mat-form-field>
      <mat-form-field appearance="outline" class="w-1/2">
        <mat-label>Password</mat-label>
        <input matInput placeholder="Password" type="password">
        <mat-icon matSuffix><i class="fa-solid fa-key p-4"></i></mat-icon>
      </mat-form-field>
      <button mat-raised-button color="primary" class="w-1/2 p-4 m-4">Login</button>
    </form>
  </div>
</div>
```

### Reproduction

Steps to reproduce:
1. Use the angular documentation and add outlined input with a label.
2. Focus on the input.
3. Outline border looks weird.

### Expected Behavior

Outline border should appear as in the example in the docs

### Actual Behavior

Outline border on click looks not pretty.

### Environment

- Angular:15.0
- CDK/Material: 15.0
- Browser(s): Chrome (possibly other browsers too)
- Operating System (e.g. Windows, macOS, Ubuntu): Mac

**Comment by kdambrauskas** [comment]
Not sure if it will help or not:
https://stackblitz.com/edit/angular-mca8sg?file=src%2Fapp%2Finput-clearable-example.html

This magic happens when tailwind is added.
.mdc-notched-outline__notch border-right gets 2px width. Guess it needs to be explicitly set to none.

**Comment by jtumain** [comment]
> .mdc-notched-outline__notch { border-right: none; }

Thanks for this - fixed the same issue I was having.

**Comment by juane1000** [comment]
Also just ran into this. Not sure if it was due to the most recent package update to ngMaterial or something else since I've had tailwind installed before first seeing this.

**Comment by nzbin** [comment]
![R8HF_~1YF 5S R% 3L@YQ 5](https://user-images.githubusercontent.com/20625845/208807960-99af3da8-4c3e-4b7f-9334-252d588605a5.jpg)
![@HH0ICGDDI 7SACV~3C}4ZN](https://user-images.githubusercontent.com/20625845/208808248-bdb3ae4b-d934-4a30-8865-84b0aa7a1c22.jpg)
It will be ok if you remove the tailwind base. I think this is a tailwind issue, it shouldn't add border style to all the elements.

**Comment by nckenn** [comment]
#9993

**Comment by nckenn** [comment]
I had to disable preflight styles #9993

**Comment by elvince** [comment]
Hi,

I face this also with all latest packages (taillwind, angular, material).
I used the temp fix provided, but what would the potential impact of it?

`.mdc-notched-outline__notch { border-right: none; }`

Is there an ETA for fix in this library or is it considered as an issue in Tailwind?

Thanks,

**Comment by alenkvakic** [comment]
Just wanted to bring this up again as it is April 2023 and it is a really annoying bug if you use outline inputs and do not find this open issue here. Should probably be addressed at tailwind directly.

**Comment by andrewseguin** [comment]
This appears to be due to tailwind adding styles on top of the input styles
