### ISSUE TITLE
docs-bug(PageEvebnt, in-code comment): previousPageIndex breaking change comment is confusing

### ISSUE THREAD

**Issue by Bilal-io** [angular/components#26121]
### Documentation Feedback

This question is related to in-code comments rather than the Angular Material website.

In this line[ ../paginator.ts#L63](https://github.com/angular/components/blob/18664ed40673267a2749230d99d111427c4fff37/src/material/paginator/paginator.ts#L63) it says breaking-change 8.0.0 To be made into a required property. I assume 8.0.0 here is referring to Angular version 8. 

Did that decision to make the property required change? If so, it would be better to remove the comment.

### Affected documentation page

PageEvent

**Comment by amysorto** [comment]
Yeah it sems it was never actually made into a required property, I'll make a PR to remove that comment.
