### ISSUE TITLE
bug(INPUT): Density not implemented for material input

### ISSUE THREAD

**Issue by electrofLy** [angular/components#26134]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

n/a

### Description

The density function is not implemented for the material input. Check https://github.com/angular/components/blob/8279120ebfe3a003ade9c8ba4dac7ba904e02c35/src/material/input/_input-theme.scss#L16

### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/edit/angular-7gyudi?file=src%2Ftheme.scss,src%2Fstyles.scss
2. Updating density of the theme.scss file does nothing

### Expected Behavior

Adjusting density changes the input size.

### Actual Behavior

Adjusting density does not change the input size.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The mixin is only there for consistency. The actual density is implemented as a part of the form field.

**Comment by electrofLy** [comment]
[as a reference] although the problem is not that it is not implemented, the issue is still there with 15.0.0 and apparently have already been fixed in https://github.com/angular/components/pull/26075
