### ISSUE TITLE
feat(material/card): add default options injection token

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#26148]
### Feature Description

**Feature Description**

Add `MAT_CARD_DEFAULT_OPTIONS` injection token, to allow changing the default appearance of card from raised to outlined.

### Use Case

From
`<mat-card appearance="outlined">
`
To
`<mat-card>`

But keeping the outlined appearance.

edit:

Would be nice a option to choose the default align (start/end) in card actions.

**Comment by crisbeto** [comment]
There's a `MAT_CARD_CONFIG` token that does this already.
