### ISSUE TITLE
docs-bug(COMPONENT): How update to latest version 15.0.1 from 14.1.0

### ISSUE THREAD

**Issue by maddybin** [angular/components#26145]
### Documentation Feedback

I am using `14.1.0` currently and I need to update to the latest version `15.0.1`. I am using `angular/CLI => 14.1.3`. I ran        
 `ng add @angular/material` but its updating my plugin from 14.1.0 to 14.2. There is no information I found regarding updating this. 

### Affected documentation page

https://material.angular.io/guide/getting-started

**Comment by amysorto** [comment]
This will take you through the commands needed for updating Angular, just make sure you click the checkbox that says `I use Angular material`: https://update.angular.io/?v=14.0-15.0.

We also added the new MDC based components in v15, if you also want to migrate to those follow this guide: https://material.angular.io/guide/mdc-migration
