### ISSUE TITLE
feature(ALL): to allow different sizes of material components

### ISSUE THREAD

**Issue by vignesh-openwings** [angular/components#26154]
### Feature Description

I'm a big fan of the Angular framework. As a result, I'm attempting to create all of my projects in Angular solely. But I can't figure out how to resize ui components in angular material to versions like small medium large xlarge. Official documentation explicitly states not to change any internal styles because it may break my code in future versions. I'm currently using CSS's zoom property to create several variants (small, medium, large) of the components. This works for the majority of the components, but not all. . What else can I do at this point? Any suitable recommendations would be much appreciated.

**Comment by crisbeto** [comment]
This should be covered by https://github.com/angular/components/issues/4597.
