### ISSUE TITLE
bug(material/button): MDC-based Icon FABs are vertically offset

### ISSUE THREAD

**Issue by LayZeeDK** [angular/components#26160]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

This issue affects the Icon FAB and Icon Mini FAB variants of the MDB-based Button component.

![MDC-based FABs and Mini FABs using `@angular/material@15.0.1`](https://user-images.githubusercontent.com/6364586/205271145-21b03f48-97ba-4292-97b5-ee5af2d0edff.png)

*MDC-based FABs and Mini FABs using `@angular/material@15.0.1`.*

![FABs and Mini FABs using `@angular/material@14.2.7`](https://user-images.githubusercontent.com/6364586/205271271-d7129255-54ef-44e4-902f-2a894e57420f.png)

*FABs and Mini FABs using `@angular/material@14.2.7`.*

### Reproduction
- [Angular Material 15 documentation -> Button -> Examples -> Button varieties](https://material.angular.io/components/button/examples)
- [Reproduction StackBlitz](https://stackblitz.com/edit/angular-1sqlp8-zinekj)
- [Comparison to legacy Icon FAB StackBlitz](https://stackblitz.com/edit/angular-1sqlp8-duqfnq)

Steps to reproduce:
1. Place MDC-based FAB or Mini FAB with text.
2. Place MDC-based Icon FAB or Icon Mini FAB next to the text-based FAB or Mini FAB.

### Expected Behavior

The FABs or Mini FABs are vertically aligned.

### Actual Behavior

The Icon FAB or Icon Mini FAB is vertically offset from the FAB or Mini FAB.

### Environment

- Angular: 15.0.2
- CDK/Material: 15.0.1
- Browser(s): Edge Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11 Pro

**Comment by crisbeto** [comment]
This can be fixed by setting `vertical-align: middle` on the FABs, but I'm not sure that we want to fix it this way since it can cause other layout issues.

**Comment by andrewseguin** [comment]
Verified that this is an issue, but this is not a supported case for Material Design anyways. From the spec:

"Don't display multiple FABs on a single screen. Instead, consider using a menu or, in rare cases, pairing a small FAB with a default FAB."

If you must do it, applying the style provided by @crisbeto should do the trick
