### ISSUE TITLE
bug(mat-slider): drag, blur values on FireFox in Material v15

### ISSUE THREAD

**Issue by milofin77** [angular/components#26172]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

When you move the slider and release the click, the value is different of the last dragged value. 
When you blur by clicking outside, the value is now another one. 

### Reproduction

Steps to reproduce:
1. Go on the official Material exemple : https://material.angular.io/components/slider/examples
2. Use first exemple
3. Drag to 10, realease the click, you got 14, click outside the slider, you got 11.

### Expected Behavior

Same slider as other browsers

### Actual Behavior

Not same slider as other browsers

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.1
- Browser(s): FireFox 107
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by babajonni** [comment]
Can confirm this bug. Even shows up in the official documents:
https://material.angular.io/components/slider/examples

Set the ```step``` to: ```0.5``` and you can see that the value changes when releasing the mouse click button.

**Comment by babajonni** [comment]
Solved in 15.0.3. @wagnermaciel

**Comment by wagnermaciel** [comment]
Ah, I think I forgot to close this out. Thank you for confirming @babajonni!!!
