### ISSUE TITLE
help(Angular Material): Problem changing a default variable

### ISSUE THREAD

**Issue by RafaelMartinsRibeiro** [angular/components#26181]
### What are you trying to do?

I'm trying to change the default value of these variables:

```
$overlay-container-z-index,
$overlay-z-index,
$overlay-backdrop-z-index,
```

### What troubleshooting steps have you tried?

![image](https://user-images.githubusercontent.com/102157214/205641182-b0e3cfa9-d6de-416b-9098-c9c179af6001.png)
![image](https://user-images.githubusercontent.com/102157214/205641287-af1fc2d4-1a75-43de-8cf8-da07781dcd51.png)

But it is saying that the variable is not declared with !default
![image](https://user-images.githubusercontent.com/102157214/205641741-7767a36e-dc6f-43f3-9920-591d3cedc7fd.png)

### Environment

- Angular: "@angular/core": "~12.2.6"
- CDK/Material: "@angular/cdk": "~12.2.6", "@angular/material": "^12.2.6"
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
This is not something that we provide support for
