### ISSUE TITLE
bug(sort): sort arrow takes up space even when not shown

### ISSUE THREAD

**Issue by marcobuschini** [angular/components#26198]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the sort arrow is not shown (the column is not sorted and the mouse is not over it) the sort arrow is not removed from the DOM but only made 100% transparent. This makes the arrow take up space event if not shown. If the table has many columns and the columns become tight this makes **centered headers** appear not centered.

### Reproduction

Steps to reproduce:
1. create a mat-table with many centered headers than can be sorted

### Expected Behavior

The sort arrow should be removed from the DOM via ng-if instead of via color change.

### Actual Behavior

The sort headers appear not to be centered when the arrow is not visible (they are centered if the arrow is taken into account)

### Environment

```
Angular CLI: 14.2.10
Node: 16.14.2
Package Manager: npm 8.5.0 
OS: linux x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/material               14.2.7
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by andrewseguin** [comment]
Keeping the sort arrow present in the DOM is intentional so that layout is not affected when sorting changes. Sounds like you may be able to accomplish what you want using `display: none` when sorting is not present on a column
