### ISSUE TITLE
feat(Button): Make content-projection for icon possible for any other icon definitions like fa-icon or <i>

### ISSUE THREAD

**Issue by anschm** [angular/components#26196]
### Feature Description

Actually the button HTML is implemented like this:

```
<span
    class="mat-mdc-button-persistent-ripple"
    [class.mdc-button__ripple]="!_isFab"
    [class.mdc-fab__ripple]="_isFab"></span>

<ng-content select=".material-icons:not([iconPositionEnd]), mat-icon:not([iconPositionEnd]), [matButtonIcon]:not([iconPositionEnd])">
</ng-content>

<span class="mdc-button__label"><ng-content></ng-content></span>

<ng-content select=".material-icons[iconPositionEnd], mat-icon[iconPositionEnd], [matButtonIcon][iconPositionEnd]">
</ng-content>

<span class="mat-mdc-focus-indicator"></span>

<span matRipple class="mat-mdc-button-ripple"
     [matRippleDisabled]="_isRippleDisabled()"
     [matRippleTrigger]="_elementRef.nativeElement"></span>

<span class="mat-mdc-button-touch-target"></span>
```

We can see that the mat-icon is projected into the button by using css classes. This has the limitation to use the button only with mat-icon if the button should habe a icon. But whats about fa-icon or <i>?

It would be great to add a button like:

```
  <button mat-icon-button (click)="click()">
    <fa-icon [icon]="faIcon"></fa-icon>
  </button>
```

In this case the fa-icon contains a svg like mat-icon can do. It would be cool to project fa-icon into the button like mat-icon. This can be done with a directive name like icon or any other name.

### Use Case

Use mat-button also with other icon components like <i> or fa-icon.

**Comment by crisbeto** [comment]
You can project a different icon by setting the `matButtonIcon` attribute.

**Comment by anschm** [comment]
Okay, I see. I think we can close this feature request.
