### ISSUE TITLE
docs-bug(cdk-dialog): CDK Dialog docs missing explanation on how to access dialogRef when using a TemplateRef

### ISSUE THREAD

**Issue by karptonite** [angular/components#26193]
### Documentation Feedback

The docs [are clear](https://material.angular.io/cdk/dialog/overview#sharing-data-with-the-dialog-component) on how to access the data when opening a modal using a TemplateRef--you can use `let-data`. But it is silent on how to access the `dialogRef`, which is needed if you want to, for example, close the modal. By inspecting the code, I figured out I could use `let-dialogRef="dialogRef"`, but it wasn't obvious.

### Affected documentation page

https://material.angular.io/cdk/dialog/overview

**Comment by Nik-09** [comment]
Hi @karptonite Can you please assign this issue to me?
Thank you.

**Comment by karptonite** [comment]
I don't think I have authority to assign issues.

**Comment by Nik-09** [comment]
Adding @crisbeto for ref.

**Comment by skilledDev96** [comment]
@Nik-09 you still working on this?
