### ISSUE TITLE
bug(form-field): matSuffix and matPrefix not clickable anymore

### ISSUE THREAD

**Issue by olischmidt123** [angular/components#26209]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14.2.7

### Description

When using a click event or a tag around a matSuffix or matPrefix it doesnt trigger.

### Reproduction

Steps to reproduce:

`
        <mat-form-field>
          <mat-label>Test</mat-label>
          <input matInput value="">
          <mat-icon matSuffix color="primary" click="test()">launch</mat-icon>
        </mat-form-field>`

### Expected Behavior

When using an a tag: open new tab or window
When using click event: execution of function

### Actual Behavior

No effect when clicking

### Environment

- Angular: 15.0.3
- CDK/Material: 15.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mmalerba** [comment]
It looks like #25987 fixed the issue with clicking prefix/suffix in outline form-field, but fill one has a different issue where the overlay element used to darken the color on focus is blocking clicks
