### ISSUE TITLE
[Paginator] Add jump-to-item functionality

### ISSUE THREAD

**Issue by vladkasianenko** [angular/components#26216]
### Feature Description

Bug, feature request, or proposal:
Feature request

What is the expected behavior?
To be able to jump to a specific item from the dataSource.
If MatSort applied, paginator should consider it.
It should also scroll to this element.

What is the current behavior?
Absence.

What is the use-case or motivation for changing an existing behavior?
I have a table with say ten elements per page, I have 20-30 pages. When I interact with source item not on the table, I want to update view in the table.
Currently I do it like this:

``` ts
const sortedData = this.tableDataSource.sortData(this.tableDataSource.data, this.tableDataSource.sort);
const itemIndex = sortedData.findIndex(x => x.id === item.id);
const pageSize = this.tableDataSource.paginator.pageSize;
const pageIndex = itemIndex < pageSize - 1 ? 0 : Math.floor(itemIndex / pageSize);

// Should call both: pageIndex and page.emit
this.tableDataSource.paginator.pageIndex = pageIndex;
this.tableDataSource.paginator.page.emit({
          pageIndex,
          pageSize,
          length: this.tableDataSource.paginator.length,
});

// Wait for the Paginator to be updated and rendered
// There's an event: 'page', but it's called to early (not rendered yet)
// This is not reliable
setTimeout(() => {
          const querySelector = `[id='${item.id}']`;
          this.perfectScrollbar.directiveRef.scrollToElement(querySelector, null, 1000); // TODO: offset the height of sticky header
}, 1000);
```

**Comment by andrewseguin** [comment]
It seems the utility you built is great for what you are trying to accomplish. I don't expect to add this functionality to our library anytime soon, especially since the paginator is intentionally unaware of the data presented
