### ISSUE TITLE
bug(MatDialog): Dialog not closing when using broadcastChannel API

### ISSUE THREAD

**Issue by augustynzentner** [angular/components#26213]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In a project we are using MatDialog. At some point dialog is closed and we broadcast message(using BroadcastChannel API) that should open same dialog in other opened tabs/windows of same app. If I only use one instance of the app(single tab) everything works fine but when I use multiple tabs it doesn't close the dialog apart from first flow. 

### Reproduction

Steps to reproduce:
1. Stackblitz:  https://stackblitz.com/edit/github-pumtun - you can open app in two separate tabs - top right corner of stackblitz editor Open in New Tab
2. open dialog in tab1 and then close it (message is broadcasted, dialog closes)
3. switch to tab2 - here the dialog shows but upon closing nothing happens - like entire js execution is freezing

### Expected Behavior

Dialog closes in current tab and opens in other tabs/windows of the same app without problems.

### Actual Behavior

After second change dialog no longer closes. Strangely I found out that clicking any button on the keyboard unfreezes the execution 🤔 

### Environment

- Angular: 14 
- CDK/Material: 14 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This is likely because the API hasn't been patched by ZoneJS. You can try wrapping your call in `NgZone.run`.

**Comment by augustynzentner** [comment]
@crisbeto, this helped indeed, thank you 🙇
