### ISSUE TITLE
bug(migration): after ng update some Legacy imports are broken

### ISSUE THREAD

**Issue by Marax** [angular/components#26223]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I've updated angular from version 14 to 15.

There was lot of changes to the imports, but there are two which failed to update correctly:
`import {MatDialog} from '@angular/material/dialog';`
changed to:
`import {MMatLegacyDialog as MatDialog from '@@angular/material/legacy-dialog;`
(double **MM** missing **}** after **MatDialog** and missing **'** at the end.

and also this
import {FloatLabelType} from '@angular/material/form-field';
to this
import {LegacyFloatLabelType} from '@angular/material/legacy-form-field';
missin **as FloatLabelType**

For the second one I think problem could be that here https://github.com/angular/components/blob/45732634fe28c1a3cf8695190024ec21fecfee2e/src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts#L65 both old/new lines are with Legacy prefix

### Reproduction

Steps to reproduce:
1. Have angular 14 with file containing
import {FloatLabelType} from '@angular/material/form-field';
`import {MatDialog} from '@angular/material/dialog';`
imports
2. run ng update @angular/material@15
3. see broken imports

### Expected Behavior

Imports should be correctly migrated.

### Actual Behavior

Imports are broken as mentioned above.

### Environment

- Angular: 14 to 15
- CDK/Material: 15
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
I just tested this out and I was not able to reproduce the malformed dialog import, but it does fail to migrate `FloatLabelType`
