### ISSUE TITLE
bug(menu): Menu item focus isn't working when using content projection

### ISSUE THREAD

**Issue by michaelfaith** [angular/components#26243]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We've packaged up the mat-menu (with a button) into an app bar action component with some defaults set for consistency, and it uses content projection via ng-content for the menu-items.  That way we define the menu behavior once, and provide the items in the handful of places we're using it.  All of that seems to work fine, except for the keyboard focus behavior.  When the menu opens, the focus remains on the button, rather than moving to the first menu item like it does when the items are just statically nested.

### Reproduction

Stackblitz: https://stackblitz.com/edit/angular-7dkegj?file=src/app/menu-overview-example.html

```html
<button mat-button [matMenuTriggerFor]="menu">Menu</button>

<mat-menu #menu="matMenu">
  <ng-content></ng-content>
</mat-menu>
```

1. select the Current build text
2. tab to the button with keyboard
3. activate button to pop menu

### Expected Behavior

First menu item should be focused

### Actual Behavior

Focus remains on button

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by rothsandro** [comment]
See #25323

**Comment by michaelfaith** [comment]
@rothsandro shoot, thanks for pointing me towards that one.  I searched with a few different search terms and didn't see that one.  I noticed the technical limitation mentioned in the other issue had to do with Menu using `ContentChildren` as its mechanism for affecting focus.  Is there another way to go about querying the menu items that would work with content projection (I thought `ContentChildren` _did_ query items populated via content project (opposed to `ViewChild`))?

**Comment by michaelfaith** [comment]
I see the `_directDescendantItems` are populated from the `_allItems` list, with this filter.  So is it this filter that's eliminating the content projected items because `_parentMenu` isn't set, or does the list really not contain the items at all?

https://github.com/angular/components/blob/b6a0bc20052cd6f5531843cfa0359b458b9aa0d5/src/material/menu/menu.ts#L526-L534

**Comment by rothsandro** [comment]
@michaelfaith `ContentChildren` does query items populated via content projection but only for one "level" of content projection, see this five year old issue https://github.com/angular/angular/issues/16299

**Comment by crisbeto** [comment]
We rely on `ContentChildren` to pick up the items which won't work when they're project through multiple levels. Closing since we can't do much about it on our end.

**Comment by michaelfaith** [comment]
> We rely on `ContentChildren` to pick up the items which won't work when they're project through multiple levels. Closing since we can't do much about it on our end.

Do you have any advice for how one might pursue a workaround, or is it just not technically feasible across the board to achieve this?

**Comment by crisbeto** [comment]
It's not easily doable on our end without changing how the menu is set up. A couple of alternatives for your case, depending on what your custom menu needs to do:
* Use a directive to apply a class to the menu, if all you need to change is styling.
* Extend the Material menu in your custom menu. You will have to copy the menu template [from here](https://github.com/angular/components/blob/main/src/material/menu/menu.html), but it's fairly small and hasn't change in a while.

**Comment by michaelfaith** [comment]
Thanks for the advice. I'll explore these options.
