### ISSUE TITLE
bug(Table): selectionModel problems then providing initiallySelectedValues 

### ISSUE THREAD

**Issue by Arktiswind** [angular/components#26241]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Table with selectionModel is not working correctly then you provide an initiallySelectedValues list.
- isSelected() always returns false > checkbox isn't checked
- if you toggle() an initially selected row it gets added another time to the selected list

### Reproduction

Stackblitz from your example with an initiallySelectedValues set on the selectionModel.
I added the selection column to show isSelected() is returning false and the content of selectionModel.selected.
Stackblitz for 14.2.7 but same problem is in 15.0.2.

https://stackblitz.com/edit/angular-9wuv4y?file=src/app/table-selection-example.ts

### Expected Behavior

isSelected() returns true for initiallySelectedValues.

### Actual Behavior

isSelected() returns false for initiallySelectedValues.

### Environment

- Angular: 14.2.7 / 15.0.2
- CDK/Material: 14.2.7 / 15.0.2
- Browser(s): Chrome/FF
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Your example doesn't work, because you're providing an object literal in the initial values array. The selection model compares by reference which is why your value isn't being picked up.
