### ISSUE TITLE
docs-bug(Typography): Description on mat-body-1 and -2 appear reversed

### ISSUE THREAD

**Issue by michaelfaith** [angular/components#26251]
### Documentation Feedback

Looking at how `mat-body-1` (`mat-h4`) and `mat-body-2` (`mat-body`) classes are applied, it seems that the descriptions in the documentation are reversed?  

![image](https://user-images.githubusercontent.com/8071845/207342290-3e4db57a-a1ea-49ad-b173-2108963ff880.png)

![image](https://user-images.githubusercontent.com/8071845/207342693-1a591657-9d8f-4381-a9cd-3861ff4fceea.png)

### Affected documentation page

https://material.angular.io/guide/typography#typography-levels

**Comment by DrVickie8** [comment]
Hello,
@michaelfaith what is the package and scope of this issue?

Trying to make a commit message, but finding it difficult to know the package and scope to use for the commit message format.

**Comment by michaelfaith** [comment]
I would suggest "docs(material/typography)" similar to this one by Jeremy: https://github.com/angular/components/pull/25975

**Comment by DrVickie8** [comment]
Alright.
@michaelfaith, How can I pass the "ci/angular: merge status" and "ci/circleci: lint" tests?
I've been trying to create a PR for a while now, and it's my first time here.

**Comment by michaelfaith** [comment]
@DrVickie8 the "merge status" one is referring to the missing "target" label on the PR.  Notice some of the PRs have this "target" label indicated the significance of the change.  I.e. can it be part of a patch release (i.e. a bug fix), or is it significant enough to be part of a "major" release (i.e. has breaking changes).  I believe this should be a "target: patch", since it's a bug fix.
![image](https://user-images.githubusercontent.com/8071845/210056806-82561eb0-2c8b-417c-824b-f6e8185ea7b0.png)

For the lint error, it actually tells you in the CI error message.  The commit message isn't formatted according to the contributing standards: 
![image](https://user-images.githubusercontent.com/8071845/210056885-e045bba4-5b37-4168-bee8-861e87a1896c.png)

You'd need to redo the commit message so it aligns to what's listed in the [`CONTRIBUTING.md`](https://github.com/angular/components/blob/main/CONTRIBUTING.md#commit)

**Comment by JanneHarju** [comment]
So is this related to these missmatch in documentation: 
https://material.angular.io/guide/typography#using-typography-styles-in-your-application
https://material.angular.io/guide/typography#typography-levels
![image](https://user-images.githubusercontent.com/17338490/215086763-cc67ada8-acd5-47fe-a7d0-1ebdcaebcccc.png)

Before fix can someone tell me which one is correct? I try to migrate from angular 14 version to 15.

**Comment by JanneHarju** [comment]
After little investigation it seems that my finding is different than this issue. Although related. So can my findings be fixed also in this issue?

**Comment by michaelfaith** [comment]
@JanneHarju i'm not sure i understand what your issue is. Can you explain?

**Comment by JanneHarju** [comment]
I tried to color code those which are incorrect. So for example if you check h4 element. At left side(Typography levels) it says subtitle-2 and right side(Using typography styles in your application) it says h4 element is body-1. Same kind of miss match in other two.

**Comment by michaelfaith** [comment]
I see what you mean.  The table I was highlighting conflicts with the table lower in the same page.  I was just pointing out that the name in the top table didn't reflect what was implemented for mat-body-1 and 2.  I didn't even realize there were the conflicts between the tables.  It seems like there needs to be an accuracy check across both sets of tables, identifying which rows are correct for each and then aligning them.

**Comment by JanneHarju** [comment]
I think they should be aligned with material design spesification so even implementation might have flaws. I don't say there is but source for truth should be original source. Although I'm not sure does it contain anything this implementation spesific. But still implementation and both tables must me aligned with each other atleast.
