### ISSUE TITLE
bug(Range Slider Component): slider has wrong track width when selecting range by tapping on mobile

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/components#26250]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when selecting range by tapping range slider on Iphone, track range is not correctly adjusted which leads to weird behaviors

![image](https://user-images.githubusercontent.com/56136563/207307913-21f99fe3-c15b-42ba-ba9d-de7212a94a06.png)

### Reproduction

Steps to reproduce:
1. open material.angular.io in safari web browser on an Iphone
2. go to slider component and scroll down to range slider
3. tap around on edge of range slider

### Expected Behavior

slider track range should  not overflow range slider thumbs

### Actual Behavior

track range overflowing

### Environment

- Angular: 15.0.2
- CDK/Material:
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): IOS 16.0

**Comment by wagnermaciel** [comment]
Taking a look at this again, I believe this was fixed by a separate change
