### ISSUE TITLE
bug(checkbox): checkbox ripple remains after click

### ISSUE THREAD

**Issue by parkb83** [angular/components#26254]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When a checkbox is selected or deselected, the final circular ripple shadow remains on display until something else is clicked.

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/checkbox/overview
2. Click on any checkbox

### Expected Behavior

Circular ripple shadow should disappear, as per v14

### Actual Behavior

Circular ripple shadow remains 

### Environment

- Angular Material 15
- Chrome

**Comment by RobinKamps** [comment]
the remaining focus behavior is as expected - new in m3 material spec: https://m3.material.io/components/checkbox/specs .

**Comment by vmuresanu** [comment]
Got it working by applying in global scss. 
```
.mdc-checkbox__ripple {
  display: none;
}
```
To be honest I don't quite get the idea of having it always focused. As seen in the attached gif file:
![image](https://im2.ezgif.com/tmp/ezgif-2-047033d7a7.gif)
When opening modal, if checkbox is first item it will always be focused, thus ripple will be active. Also when user clicks on the checkbox it should be selected the outline of the ripple seems to be unnecessary. This new focus behaviour is buggy and not intuitive.

**Comment by parkb83** [comment]
Thanks Vmuresanu

Adding your suggestion results in the expected behavior I was looking for, 

```
.mdc-checkbox__ripple {
  display: none;
}
```

I agree, when the ripple remains after click it is easy to mistake it as 'hanging' or incomplete.
