### ISSUE TITLE
bug(mat-tab-link): Selector ::before is not working in `mat-tab-link` class

### ISSUE THREAD

**Issue by OlenaPeretiatko** [angular/components#26277]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.1.1

### Description

I used to have selectors .mat-tab-label-active::before, .mat-tab-label-active::after, which worked great in version 13, but after updating to version 14 only ::after works good, and selector with ::before not showing at all.

### Reproduction

-

### Expected Behavior

all selectors works good

### Actual Behavior

selector ::before is not working

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by OlenaPeretiatko** [comment]
@crisbeto, @devversion could you please fix it?

**Comment by crisbeto** [comment]
The `::before` and `::after` are internal implementation details that you can target at your own risk. We can't guarantee that they won't be used by our own styles.
