### ISSUE TITLE
@angular/material/core/theming/_theming.scss (v15.0.3) problems

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/components#26286]
### Description

After installing the `"@angular/material": "15.0.3"` package, strange errors related to `@use '../density/private/compatibility';` appears in the `@angular/material/core/theming/_theming.scss` file. It seems that variables from the `_compatibility.scss` file are not accessible in `_theming.scss`.

![image](https://user-images.githubusercontent.com/5693835/208179635-22eb9d1b-8934-49d8-8015-e22d17557a4b.png)

![image](https://user-images.githubusercontent.com/5693835/208180165-84b97ddb-2983-496e-ba3f-1cbf5d006b60.png)

### Reproduction

Steps to reproduce:
1. `npm i @angular/material`

### Expected Behavior

No such problems inside an official package.

### Actual Behavior

![image](https://user-images.githubusercontent.com/5693835/208180165-84b97ddb-2983-496e-ba3f-1cbf5d006b60.png)

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.3
- Browser(s): Chrome 108.0.5359.125 
- Operating System: Windows 10

**Comment by crisbeto** [comment]
Can you check which version of Sass you're running? It looks like you're using one that might not support some of the latest syntax.

**Comment by wagnermaciel** [comment]
Closing since no additional info was provided
