### ISSUE TITLE
bug(Material): css variables don't work in color palettes

### ISSUE THREAD

**Issue by Selindek** [angular/components#26280]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

if I define a palette this way: 

$dynamic-primary: (
...
  500: var(--theme-primary-500),
...
  contrast: (
...
    500: var(--theme-primary-contrast-500),
...
  ),
);

... and pass it to a theme, then I got a warning/error during compilation.

If I use all-legacy-component-themes() I get only a warning, but all-component-themes() throws an error.

The variable --theme-promary-500 can be defined in css and/or from ts. (or even overridden when the user selects a new color.) It worked nicely in the previous version.

### Reproduction

Steps to reproduce:
1. pass a color as a css variable into a palette: var(--theme-primary-500)
2. try to build.

### Expected Behavior

no warning, no error

### Actual Behavior

warning / error:
var(--theme-primary-500) is not a color. Falling back to "dark" tone.

### Environment

- Angular:  15.0.2
- CDK/Material: 15.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This should mostly be addressed in version 15.0.3.

**Comment by inlym** [comment]
Notify me if resolved.

**Comment by Londeren** [comment]
The discussion is here https://github.com/angular/components/issues/25981
