### ISSUE TITLE
bug(MatCheckbox): disableRipple not working

### ISSUE THREAD

**Issue by EMokro** [angular/components#26282]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Currently the disableRipple directive does nothing.

### Reproduction

Steps to reproduce:
1. use Angular Material 15
2. use `disableRipple` on `mat-checkbox`

Here is an Stackblitz example
https://stackblitz.com/edit/angular-xvd8ju?file=src/app/checkbox-configurable-example.html
or repo
https://github.com/EMokro/angular-material-15-checkbox-no-ripple

### Expected Behavior

It should disable the mat ripple effect.

### Actual Behavior

It does nothing

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.3
- Browser(s): Brave v1.46.144 / Chromium 108.0.5359.128
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
This is working as expected. `disableRipple` only removes the ripples on clicks, not the ripple that is used for focus indication. We generally don't provide APIs to disable accessibility features like focus indication. You can hide it at your own risk with `.mdc-checkbox__ripple { display: none; }`.
