### ISSUE TITLE
bug(mat-slider): value label is invisible inside a mat-list-item

### ISSUE THREAD

**Issue by davidshen84** [angular/components#26287]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

```
  <mat-list role="list>
      <mat-list-item role="listitem" >
        Length:
        <mat-slider max="99" min="1" step="1" showTickMarks discrete>
          <input matSliderThumb [formControl]="SliderControl">
        </mat-slider>
      </mat-list-item>
  </mat-list>
```

In the above example, I am trying to display a value label when a user moves the slider thumb. The label is displayed correctly if the `mat-slider` is not inside a `mat-list-item`. But if it is inside a `mat-list-item`, I can only see the bottom of the label. 

### Reproduction

Steps to reproduce:
1. Create a new project with Angular 15
2. Put a `mat-slider` with `discrete` attribute inside a `mat-list-item`

### Expected Behavior

The label should be visible.

### Actual Behavior

The label is not fully visible.

### Environment

- Angular: 15.0.3
- CDK/Material: 15.0.3
- Browser(s): 108.0.5359.100
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by davidshen84** [comment]
Hi @wagnermaciel,

Thanks for the update. The `mat-list-item` in Angular 14 worked as I expected, so I just assume this is the right way to align a list of form controls.

What would be the easiest way to align a list of form controls using Angular material CDK? Maybe a one-column grid?

**Comment by wagnermaciel** [comment]
To be honest, I'm not sure the best way to go about aligning form controls using the CDK, but if I were you I'd probably use either a css grid container to handle layout stuff. I think the CDK grid is somewhat obsolete now that CSS grid has become standardized  ¯\_(ツ)_/¯
