### ISSUE TITLE
bug(mat-menu) trigger is setting aria-expanded to null instead of false 

### ISSUE THREAD

**Issue by OlivierNourry** [angular/components#26281]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This is kind of a re-opening of #16859 that was closed for inactivity. 

The possible values for `aria-expanded`  are `true`, `false`, or `undefined` (see https://www.w3.org/TR/wai-aria-1.1/#aria-expanded for reference). The default value is `undefined`, implying that either there are no children for the element, or these children are all visible in the UI. Which, in effect, is exactly the same as when the value is `true`. Thus, when the value of `aria-expanded` is anything other than `false`, it is actually equivalent to  `true`.
In this case, having `null` instead of  `false` results in having  `true` instead of  `false` -- meaning that users get the opposite of the intended information.

The consequence is that blind users of screen readers are led to believe that the menu is displayed, whereas it's collapsed. This doesn't come from the screen reader actually, but from the browser that populates the accessibility API with the info it is fed with through the HTML code -- which is incorrect here.

### Reproduction

Steps to reproduce:
1. Add a button with [matTriggerFor] for a mat menu
<button mat-icon-button
        #menuButton
        [matMenuTriggerFor]="exampleMenu">
</button>

<mat-menu #exampleMenu="matMenu">
2. Inspect the accessibility information of the element in the browser, with the menu collapsed ("States" section in Firefox in the Accessibility view. In Chrome, check the Accessibility tab in the Inspector)

### Expected Behavior

In the "States" section in Firefox, one item is "Collapsed" (no Expanded). In Chrome, the property Expanded is set to false

### Actual Behavior

In the "States" section in Firefox, one item is "Expanded". In Chrome, the property Expanded is set to true

### Environment

- Angular:
- CDK/Material:
- Browser(s): Firefox, Chrome (not checked but other browsers that follow the spec will show the same behavior)
- Operating System (e.g. Windows, macOS, Ubuntu): not relevant

**Comment by crisbeto** [comment]
What version of Material are you running? As far as I can tell from this https://github.com/angular/components/blob/main/src/material/menu/menu-trigger.ts#L81, the `aria-expanded` should always be `true` or `false`.

**Comment by OlivierNourry** [comment]
@crisbeto 
(Responding on behalf of my client, who ran into the issue)
This has been fixed as of v15. But is observable on 11, 12, 13 and 14 (my client is limited to v13 due to their server).
Can this be fixed for previous versions?

**Comment by crisbeto** [comment]
We don't backport fixes to older versions, unless they're related to security.
