### ISSUE TITLE
docs-bug(Button): Alignemt of buttons is broken in the "Basic buttons" of buttons docs

### ISSUE THREAD

**Issue by AlexElin** [angular/components#26297]
### Documentation Feedback

Alignemt of buttons is broken in the "Basic buttons" section of the [docs](https://v15.material.angular.io/components/button/overview) page.
See the below screenshots for more details (Disabled Icon button is under Accent Flat button and many other cases).

V15 (broken):
![image](https://user-images.githubusercontent.com/13061803/208634581-335f132c-5bef-4f4c-80af-01c40e6bea1b.png)

V14 (Ok):
![image](https://user-images.githubusercontent.com/13061803/208634766-1d586d95-79d7-47cc-b749-0ed1f98fe3f4.png)

### Affected documentation page

https://v15.material.angular.io/components/button/overview

### Browser
Google Chrome 108.0.5359.125

**Comment by amysorto** [comment]
This is being set by MDC here: https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/_button-shared-theme.scss#L45.

It follows the [button material spec](https://m2.material.io/components/buttons#specs), where buttons without any borders have a padding of 8px versus 16px if they do.
