### ISSUE TITLE
MatFormFieldAppearance "standard" is missing

### ISSUE THREAD

**Issue by pkelleter** [angular/components#26299]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

With v15 the Type MatFormFieldAppearance was refactored to lose the properties _legacy_ and _standard_. 
Hereby _standard_ was replaced by _undefined_, so the absence of an appearance should represent _standard_ now.

There is a problem when are using provide _MAT_FORM_FIELD_DEFAULT_OPTIONS_ though. When we set the default to something else we will not be able to opt-in for _standard_ anywhere else anymore since  we can not set the appearance explicity to standard _anymore_

Even if I "trick" TypeScript into taking the string _standard_ by casting it to any, Angular Material will throw since it seems to check the value at runtime and tell me that this is not a valid value.

This used to be possible in v14 and blocks me from migrating to v15.

### Reproduction

Steps to reproduce:
1. {provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: {appearance: 'outline'}} in your AppComponent
2. try to set the appearance to _standard_ for any Angular Material Component in your codebase

### Expected Behavior

_MatFormFieldAppearance_ should accept _standard_ as a value again

### Actual Behavior

_MatFormFieldAppearance_ is typed in a way that _standard_ is absent as a value - and it throws at runtime if you somehow manage to still pass it otherwise.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by mrmokwa** [comment]
The MDC spec do not support these legacy/standard appearances anymore, so Angular team deprecated and removed them.

**Comment by Totati** [comment]
`legacy` and `standard` appearances were [deprecated in version 9.0.0](https://github.com/angular/components/blob/main/CHANGELOG.md#900-tungsten-hombre-2020-02-06)

**Comment by crisbeto** [comment]
The comments above are correct. The `standard` and `legacy` appearances aren't in the Material Design spec anymore.
