### ISSUE TITLE
bug(mat-checkbox): cdk-keyboard-focused is missing in mdc checkbox

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#26292]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

`cdk-keyboard-focused` is missing in mdc checkbox

### Reproduction

Steps to reproduce:
1. Visit https://material.angular.io/components/checkbox/overview
2. Inspect `mat-checkbox`
3. Now navigate to checkbox using keyboard
4. Check `cdk-keyboard-focused` class is missing

### Expected Behavior

`cdk-keyboard-focused` should be added if we are navigating via keyboard

### Actual Behavior

`cdk-keyboard-focused` is not getting added if we are navigating via keyboard

### Environment

- Angular: 15
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by maxcapraro** [comment]
I am running into this issue as well and can reprocuce / confirm the steps outlined by @iKrishnaSahu.

**Comment by Ulse81** [comment]
Is there a reason why `FocusMonitor` was removed here with Material 15?

**Comment by wagnermaciel** [comment]
The cdk classes applied to our components are considered an implementation detail and are subject to change

**Comment by iKrishnaSahu** [comment]
@wagnermaciel
does that mean you are going to remove these cdk-* classes for other components as well?

**Comment by wagnermaciel** [comment]
Not necessarily. I'm just saying that if we were to remove other cdk- classes from our components there would be no warning, deprecation process, or effort to maintain backwards compatibility because it is not something we support relying on
