### ISSUE TITLE
bug(mat-checkbox): Multiple cdk-keyboard-focused class instances if using cdkMonitorElementFocus inside legacy checkbox

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#26293]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Multiple `cdk-keyboard-focused` class instances if using `cdkMonitorElementFocus` inside legacy checkbox

### Reproduction

Steps to reproduce:
1. Open [this stackblitz](https://stackblitz.com/edit/angular-1qw5ga-bfdibz?file=src/app/checkbox-configurable-example.html)
2. Inspect checkbox as well as anchor tag
3. Now navigate to the anchor tag via keyobard
4. `cdk-keyboard-focused` class is applied to both checkbox and link

### Expected Behavior

`cdk-keyboard-focused` class should not get applied to both the elements

### Actual Behavior

`cdk-keyboard-focused` class is gettting applied to both the elements

### Environment

- Angular: 15
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. We monitor focus both on the checkbox and the content inside of it. Since focus is inside the checkbox, classes are added to both elements.
