### ISSUE TITLE
bug(Form Controls): FormControl disabled state now overrides the template state

### ISSUE THREAD

**Issue by zakhenry** [angular/components#26302]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

This is a regression, before the [disabled] attribute of a form element (radio, toggle etc) would take precedence, but now this attribute appears to be ignored entirely if the component is bound to a form control

Before:
https://stackblitz.com/edit/angular-pw8j5w?file=src/app/radio-ng-model-example.html
<img width="219" alt="Screenshot 2022-12-21 at 11 22 43" src="https://user-images.githubusercontent.com/721513/208778273-d27a4fb7-e3e7-4cfd-a1d8-ff6c83cf5e42.png">

After:
https://stackblitz.com/edit/angular-tomdov?file=src/app/radio-ng-model-example.html
<img width="245" alt="Screenshot 2022-12-21 at 11 22 49" src="https://user-images.githubusercontent.com/721513/208778310-f2e9be17-66d7-41ff-a286-fa7cb01f992e.png">

Note the content of these demos are identical other than the different bootstrapped version, one is showing the control as disabled (v14) and the other as enabled (v15)

### Reproduction

Steps to reproduce:
1. Set up a form component with a [disabled]="true" attribute
2. Attach a formControl via [formControl] with no disabled state set (the default)
3. Inspect the ui

### Expected Behavior

Form component should be disabled

### Actual Behavior

Form component is not disabled

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by EmmanuelRoux** [comment]
Probably because of this (breaking) change from @angular/forms v15 ?
https://github.com/angular/angular/commit/6ab382e4f1f5f27f48482f84152191a6d44ac1c4

__But `[disabled]` should not be bind from template with reactive forms__

**Comment by crisbeto** [comment]
@EmmanuelRoux is correct. We implement the `ControlValueAccessor` and leave it up to the forms module to notify the component when it should be disabled.
