### ISSUE TITLE
bug(mat-icon-button): inner handler on mat-icon inside mat-button is not triggered

### ISSUE THREAD

**Issue by mdainovich** [angular/components#26309]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

Hi all!

Found and issue when inner handler inside mat-button is not trigered. At the same time the handler on mat-button itself is working fine.

### Reproduction

Angular 15 example
https://stackblitz.com/edit/angular-5wvgmw-etfpj6?file=src/app/button-overview-example.html

Steps to reproduce:

1. Open stackblitz
2. Open browser console
3. Click on home button
4. See only hanlder log in console
5. Not see innerHandler log in console

### Expected Behavior

Inner handler inside mat-icon-button is trigger.
There are both handler and innerHandler logs in console

Works fine in Angular 14

https://stackblitz.com/edit/angular-s8w8xi?file=src/app/button-overview-example.ts

### Actual Behavior

Inner handler inside mat-icon-button is trigger.

### Environment

- Angular: 15
- CDK/Material: 15.0.3
- Browser(s): any
- Operating System: any

**Comment by lilas78** [comment]
While waiting for the fix from Angular, The following ovveride in SCSS fixes the problem :
.mat-icon{
z-index : 1;
}

**Comment by andrewseguin** [comment]
The icon should not have a click handler
