### ISSUE TITLE
help(mat-raised-button): translation not updated on mobile browser

### ISSUE THREAD

**Issue by vcomperq** [angular/components#26311]
### What are you trying to do?

using the ngx-translate feature, i try to selected an other language than the default one.

### What troubleshooting steps have you tried?

All my texts are correctly translated except my mat-raised-button

### Reproduction

Steps to reproduce:
1.  use the translate service from ngx-translate to change to an other than the default one
2. everything is correctly translated except the text within the mat-raised-button

### Environment

- Angular: 14.2.12
- CDK/Material:14.2.7
- Browser(s): Chrome mobile 108.0.5359.112
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS 13.0.1

**Comment by crisbeto** [comment]
This is an issue with ngx-translate. Material doesn't have control over the content inside the button.
