### ISSUE TITLE
[WCAG]: ARIA hidden element must not be focusable or contain focusable elements

### ISSUE THREAD

**Issue by t3z3ndra** [angular/components#26331]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running axe dev tool in https://v7.material.angular.io/components/dialog/overview getting error for 
ARIA hidden element must not be focusable or contain focusable elements

![image](https://user-images.githubusercontent.com/117698245/209664619-2824fb80-7786-443f-976e-565d7b575cd4.png)
https://github.com/angular/components/blob/main/src/cdk/a11y/focus-trap/focus-trap.ts#L327 i can see _createAnchor method adds the aria-hidden=true, is there a way to override this in consumers?

### Reproduction

Steps to reproduce:
1. navigate to https://v7.material.angular.io/components/dialog/overview
2. open dialog by clicking on button
3.  run axe dev tool in the page

### Expected Behavior

ARIA hidden element must not be focusable or contain focusable elements should not come when running axe dev tool

### Actual Behavior

ARIA hidden element must not be focusable or contain focusable elements is coming when running axe dev tool

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This isn't a problem for users, because the focus trap anchor immediately moves focus away from itself.
