### ISSUE TITLE
docs-bug(THEMING): Difference between Angular Material Theming all-component-colors and all-component-themes?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#26342]
### Documentation Feedback

What is the difference between Angular Material Theming all-component-colors and all-component-themes?

[I also asked about this on Stackoverflow in the context of another question.](https://stackoverflow.com/questions/74890266/difference-between-angular-material-theming-all-component-colors-and-all-compone)

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by crisbeto** [comment]
Material themes for each component are split up into 3 parts: colors, typography and density. `all-component-colors` only includes the color styles for the components while `all-component-themes` includes colors, typography and density.

**Comment by crisbeto** [comment]
This is somewhat covered in the theming guides here:
https://material.angular.io/guide/theming-your-components
https://material.angular.io/guide/theming
