### ISSUE TITLE
bug(DragDropModule): cdkDragHandle does not work without zonejs

### ISSUE THREAD

**Issue by phamtienmanh** [angular/components#26340]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

cdkDragHandle does not work if I config BootstrapOptions ngZone: 'noop'

### Reproduction

Steps to reproduce:
plz check this stackblitz: https://stackblitz.com/edit/angular-m67jz9?file=src%2Fmain.ts
1. Change the default platformBrowserDynamic to
  platformBrowserDynamic()
    .bootstrapModule(AppModule, {
      ngZone: 'noop',
    })
    .catch((err) => console.error(err));

### Expected Behavior

only an element with cdkDragHandle can be used to drag a CdkDrag instance.

### Actual Behavior

I can drag everywhere

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.3
- Browser(s): Chrome Version 108.0.5359.125 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Window

**Comment by crisbeto** [comment]
Covered by https://github.com/angular/components/issues/9169.
