### ISSUE TITLE
bug(mat-button): Button is clickable even if the cursor is not on the button

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#26354]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Button is clickable even if the cursor is not on the button

v15
![mat button v15](https://user-images.githubusercontent.com/34937515/210320304-ccbe3b78-6d02-4156-91b4-10b75672440b.gif)

v14
![mat button v14](https://user-images.githubusercontent.com/34937515/210320325-d8712c10-ad84-447f-b62e-e12f510cc3e0.gif)

### Reproduction

Steps to reproduce:
1. Visit https://material.angular.io/components/button/overview
2. Try the same step which is shown in the attached gifs

### Expected Behavior

Button should not be clickable if cursor is not on the button

### Actual Behavior

Button is clickable if cursor is not on the button

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. In the MDC buttons we added an extra element to make sure that buttons have a appropriately-sized touch target for touchscreen users. See https://github.com/angular/components/blob/main/src/material/button/button.html#L24.
