### ISSUE TITLE
bug(MatButton): button class cannot be applied dynamically

### ISSUE THREAD

**Issue by tstankevicius** [angular/components#26350]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Button style (basic, raised, etc.) cannot bet set dynamically anymore. None of these options below work.

<button
  [ngClass]="{'mat-raised-button' : true}"
  [class.mat-raised-button]="true"
  [attr.mat-raised-button]="true"
  type="button">
  Label
</button>

### Reproduction

Steps to reproduce:
Check example below:
https://stackblitz.com/edit/components-issue-afusnu?file=src%2Fmain.ts

### Expected Behavior

Button changes style dynamically

### Actual Behavior

Buttons does not apply styles dynamically

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
Closing since this wasn't officially supported in the first place. It happened to work before by accident, but now multiple classes are required to style the button.

**Comment by tstankevicius** [comment]
Thanks for reply. What do you mean multiple classes? Multiple custom classes instead of material ones? Can you provide any example pls?

**Comment by crisbeto** [comment]
For example, to style a raised button the `mdc-button`, `mdc-button--raised` and `mat-mdc-raised-button` classes all have to be applied.
