### ISSUE TITLE
docs-bug(component): is there any documentation available for what all css var properties we have for a specific component?

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#26367]
### Documentation Feedback

Is there any documentation available for what all css var properties we have for a specific component(button etc)?

### Affected documentation page

https://material.angular.io/components/button/api

**Comment by crisbeto** [comment]
The current variables aren't really meant to be used outside of our own theming. We're working on a new theming API that will be documented.

**Comment by iKrishnaSahu** [comment]
@crisbeto In which future release we can expect this new theming api changes?
