### ISSUE TITLE
feat(button): Any plan to support structural css var properties?

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#26385]
### Feature Description

Do you guys have anything already planned to support below properties as css var -
- padding
- height (this is supported but it is getting overridden by non css var styling)
- opacity (static/hover)

Also some of the theming css vars are missing - 
- border-color

This same goes for other components as well

### Use Case

We are creating a design system and we need a robust solution to implement it.
We are trying to override material component with CSS variables.
Is there any better approach of overriding styles of material component other than css vars?

**Comment by crisbeto** [comment]
Yes, we're currently in the process of reworking all components to support a variable-based theming API.
