### ISSUE TITLE
bug(mat-stepper): Custom font not applied to mat-stepper

### ISSUE THREAD

**Issue by fikkatra** [angular/components#26388]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When applying a custom font through theming, the font is not applied to some components, e.g. mat-stepper. Other components like mat-button, work well with the custom font.

### Reproduction

Steps to reproduce:
1. Import the custom font
2. Create a font config with mat.define-typography-config and set $font-family to the custom font
3. Apply the typography config to the theme
4. Render a mat-stepper component

See [this StackBlitz](https://stackblitz.com/edit/angular-rtlw1e?file=src/theme.scss). This is a fork of one of the mat-stepper examples [from the docs](https://material.angular.io/components/stepper/examples), with changes applied to (only) theme.scss.

On the contrary, applying the same steps and rendering a mat-button, everything works well and the button is rendered with the custom font. See [this StackBlitz](https://stackblitz.com/edit/angular-av8kdt?file=src/theme.scss).

### Expected Behavior

Text within mat-stepper should use the custom font.

### Actual Behavior

Text within mat-stepper uses the default font family Roboto.

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by fikkatra** [comment]
Fixed by adding `@include mat.typography-hierarchy($theme);`

**Comment by crisbeto** [comment]
Should have been fixed by https://github.com/angular/components/commit/434ec52c8de5c714e458ae12514e5b43c6977933.
