### ISSUE TITLE
bug(theming): CSS classes for typography levels (e.g. .mat-caption) do not work anymore

### ISSUE THREAD

**Issue by fikkatra** [angular/components#26389]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When using CSS classes to set a typography level (cf. [the documentation](https://material.angular.io/guide/typography#typography-configs-and-theming)), the styles are not applied. 

E.g. setting `.mat-caption` or `.mat-headline-3` does't have any effect.

### Reproduction

Steps to reproduce:
1. Apply the `mat-caption` or `mat-headline-3` CSS class to a HTML element containing text

Stackblitz: https://stackblitz.com/edit/angular-pmykqc?file=src/app/app.module.ts (see index.html)

### Expected Behavior

The element should be rendered with a 'caption', resp. headline-3 style, as documented in [the docs](https://material.angular.io/guide/typography#typography-configs-and-theming)

### Actual Behavior

Applying the class doesn't have any effect

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
In v15 the typography hierarchy isn't included by default anymore. You have to add it yourself with `@include mat.typography-hierarchy($theme);`.

**Comment by fikkatra** [comment]
@crisbeto thanks, that fixed the issue.However, the necessity to include this mixin is not mentioned anywhere, not in the docs on [theming](https://material.angular.io/guide/theming) and [typography](https://material.angular.io/guide/typography), and not in the [mdc migration guide](https://rc.material.angular.io/guide/mdc-migration). Can the team please add it?

The migration guide does briefly mention the mixin, but specific to the cards section, and without the theme parameter, which causes the compilation to fail.

FYI including the mixin also fixes https://github.com/angular/components/issues/26361 and https://github.com/angular/components/issues/26388, possibly also https://github.com/angular/components/issues/26387
