### ISSUE TITLE
bug(MatSelect): MatSelect allows assigning a value which isn't found in the MatOptions

### ISSUE THREAD

**Issue by zetti-caletti** [angular/components#26381]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the native html-select, when assigning a value which isn't found in the option tags the value becomes an empty string.
However in MatSelect you can assign any value, even if its not provided through the MatOptions.
This behaviour is inconsistent with the native html select.

### Reproduction

Steps to reproduce:
[https://stackblitz.com/edit/angular-n3xzus](https://stackblitz.com/edit/angular-n3xzus)

### Expected Behavior

The value also becomes an empty string like in native select

### Actual Behavior

MatSelect allows assigning any value. And also every type. Native html select only allows setting string values, whereas MatSelect you can assign values of any type. Allowing to set any type is not a big problem for me, but it is if you want for example migrate from MatSelect to native select.

### Environment

Latest

**Comment by crisbeto** [comment]
We allow assigning arbitrary values programmatically, because you as the application author have control over it. The options are only limited for user interactions. Closing since it works as expected and it would be a breaking to change it now.
