### ISSUE TITLE
bug(mat-chip): Using an array of objects from a component's method hangs the application

### ISSUE THREAD

**Issue by nikxco** [angular/components#26399]
### Description

I'm creating a widget where I use `mat-chip-list` and `mat-chip` to render active filters, I'm using a component method to populate `mat-chip-list` but it's causing the entire application to freeze (the method returns a javascript array of objects instead of observable).

### Reproduction

Steps to reproduce:
Use an array of objects to render the `mat-chip-list`.
https://stackblitz.com/edit/components-issue-fpjhzo

filter.component.ts
```
get activeFilterOptionsList(): any[] {
    const activeOptions = this.activeFilterOptions;
    let output: any[] = [];
    for (const key in activeOptions) {
      output = [...activeOptions[key], ...output];
    }
    return output;
}
```

filter.component.html
```
<mat-chip-list>
    <mat-chip 
        *ngFor="let option of activeFilterOptions" 
        (removed)="onChipRemoved($event.chip)" 
        [value]="option.name">
                        {{option.name}}
         <button matChipRemove>
             <mat-icon>cancel</mat-icon>
         </button>
    </mat-chip>
</mat-chip-list>
```

### Expected Behavior

`mat-chip-list` should be rendered with an array of objects, not only with Observable.

### Actual Behavior

`mat-chip-list` freezes the application if an array of objects is used.

### Environment

- Angular: 14.2
- CDK/Material: 14.2.7
- Browser(s): Chrome
- Operating System: macOS

**Comment by crisbeto** [comment]
This is causing an infinite change detection, because any time `activeFilterOptionsList` is accessed, it produces a new array which means that the view needs to be re-rendered.

**Comment by nikxco** [comment]
@crisbeto yeah, I suspect that too... but that issue is not present in `mat-list` with `mat-list-item`. structurally they have similar markup.
```
<mat-list>
    <mat-list-item *ngFor="let option of activeFilterOptionsList">{{option.name}}</mat-list-item>
</mat-list>
```
this works perfectly fine.

**Comment by crisbeto** [comment]
There's probably something in the chip that triggers another round of change detection as a result which throws it into the loop. Either way, this isn't something we support since it'll cause other performance issues down the road.

**Comment by nikxco** [comment]
It's not about supporting a new feature or functionality, it's about triaging a bug in the existing component `mat-chip` which is causing an issue for the simplest of use cases where chips are not working with `ngFor`.

`mat-chip-list` with `mat-chip` is having the same markup as `mat-list` with `mat-list-item` (which works perfectly).

`mat-chip` is not supposed to be used with `*ngFor` that consumes an array from a `getter` property?

**Comment by crisbeto** [comment]
Fixing the bug would mean supporting this behavior as well. This isn't a pattern we want to encourage people to use.
