### ISSUE TITLE
bug(Dialog): MatDialogClose

### ISSUE THREAD

**Issue by andreisrob** [angular/components#26393]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The MatDialogClose directive has a method for finding an open dialog, and uses the dialog container's css class name, which has been changed in version 15.

[See here](https://github.com/angular/components/blob/69598f113be73a29a9216e1b8280158041fe823e/src/material/dialog/dialog-content-directives.ts#L160)

The css class `mat-dialog-container` no longer exists, and must be changed to `mat-mdc-dialog-container`

### Reproduction

Steps to reproduce:
1. Include the `MatDialogClose` directive in a dialog via TemplateRef
2. Click the button that has the directive

### Expected Behavior

Dialog should close

### Actual Behavior

Dialog does not close

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The link is pointing to some old code. The current one is using the correct class name: https://github.com/angular/components/blob/main/src/material/dialog/dialog-content-directives.ts#L164
