### ISSUE TITLE
help(Migrating Material): Getting errors when trying to migrate materials

### ISSUE THREAD

**Issue by ueoeae** [angular/components#26396]
### What are you trying to do?

Trying to upgrade from Angular v12 to Angular v15. Managed to get my app running on v15 but there are some styling issuses. I am now trying to run `ng generate @angular/material:mdc-migration` to see if this fixes some of the issues. However, I am getting errors when trying to run this command (a lot of similar ones), here is an example:

    CssSyntaxError: <css input>:2:3: Unknown word

      1 | .header-container
    > 2 |   display: flex
        |   ^
      3 |   margin: 24px 40px 10px
      4 | 
    
    Failed to process stylesheet: /src/app/decks/about/about.component.sass (see error above).

Any ideas what is causing this?

### What troubleshooting steps have you tried?

Don't know where to start.

### Reproduction

Steps to reproduce:
1. 
2.

### Environment

- Angular: 15.0.5
- CDK/Material: 15.0.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because you're using the `.sass` syntax which we don't support in our migrations. I've sent out #26450 to avoid the error, but you'll have to migrate the styles to MDC yourself.

**Comment by ueoeae** [comment]
> It's because you're using the `.sass` syntax which we don't support in our migrations. I've sent out #26450 to avoid the error, but you'll have to migrate the styles to MDC yourself.

That explains a lot, thanks. I've migrated manually.
