### ISSUE TITLE
Mat Form Field ERROR outline and label not responding positioning and changing color properly on SAFARI and Chrome on IOS devices and macbooks

### ISSUE THREAD

**Issue by klsolano7** [angular/components#26403]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

N/A

### Description

When a user selects in and out of an input field that is "required", the error for the input field is not responding properly.
The outline of the input field is a combination of blue and red. The label does not float properly to the top of the input field.  This only happens in IOS devices V16 and MAC Ventura V16.

![image](https://user-images.githubusercontent.com/40219885/211876321-4e786e5c-ae21-45e0-8686-36224a067cdf.png)

### Reproduction

Steps to reproduce:
1.  Click inside of input field that is "required"
2. Click outside of input field

### Expected Behavior

When there is an error in the input field, the red border should outline completely. The Label should float properly to the top.

### Actual Behavior

Red outline is not wrapping around 100%. The Label does not float all the way to the top.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by xanather** [comment]
This also happening to me.

**Comment by mmalerba** [comment]
I tested with the following and was unable to reproduce. Please open a new issue with additional info on how to reproduce if you are still seeing this issue.

Repro Link: https://stackblitz.com/edit/twb636
Angular: 16.0.0
CDK/Material: 16.0.2
Browser(s): Chrome 113.0.5672.126 (Official Build) (x86_64), Safari Version 16.4 (18615.1.26.110.1)
Operating System: MacOS Ventura Version 13.3.1
