### ISSUE TITLE
Make  dialogs draggable

### ISSUE THREAD

**Issue by Son-Lam** [angular/components#2640]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Users shall be able to drag dialogs around. Example, bootstrap already have draggable dialogs (http://jsfiddle.net/dave_wilton/a3gyq/5/) 

#### What is the current behavior?
Dialogs position are fixed on the page. If users want to see something behind them they have to close the dialog, which is quite anoying.

#### What are the steps to reproduce?
Just open a dialog and try to move is round - you cannot.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
User-friendlies. Users may be editing a large spreadsheet and they need to pop up a dialog and enter data for one row. But they may need to look at data from other rows to make decision. In this case, with Angular Material2, they have to save incomplete data set or abandon it to close the dialog and open it later.

#### Which versions of Angular, Material, OS, browsers are affected?
ALL

**Comment by jelbourn** [comment]
We have some thoughts on drag-drop in general, but anything in that space is firmly post-beta.

**Comment by cmark11** [comment]
Is this post-beta code available to integrate or 'test' out in the current version of angular-material2? Maybe using a gist?

**Comment by LeoTanoue** [comment]
Any updates for this feature? I couldn't find a road map page anywhere to keep track of what's being worked on.

**Comment by thefliik** [comment]
@LeoTanoue the [readme on the front page](https://github.com/angular/material2) begins by laying out the current roadmap

**Comment by crisbeto** [comment]
This is possible now using the CDK `drag-drop` module.
