### ISSUE TITLE
Bug in Mat pagination

### ISSUE THREAD

**Issue by shagunagra** [angular/components#26417]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Whenever I go to the next page and after going to 4-6 pages when I change the page size it is not starting the current page no. from 1.
![Screenshot from 2023-01-12 18-11-46](https://user-images.githubusercontent.com/59168880/212070003-5cb8cd1a-f32d-4764-a357-ca4bbad10a68.png)

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

Whenever I go to the next page and after going to 4-6 pages when I change the page size it is not starting the current page no. from 1.

### Actual Behavior

Whenever I go to the next page and after going to 4-6 pages when I change the page size it is not starting the current page no. from 1.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The paginator only goes back to the first page when the size changes if there's only one page worth of results.
