### ISSUE TITLE
feat(Datepicker): Able to open date picker with grayed out dates of previous and current month instead of empty space

### ISSUE THREAD

**Issue by ankurdeal** [angular/components#26420]
### Feature Description

I tried to find out from git issues.

Wasn't able to find anything related to it.

In date-picker month view it only displays dates of selected month. On first row and last row dates/days that belong to previous/next months are not displayed. Instead empty space is displayed.

Usually in calendars complete 6 rows displays and dates that belong to previous/next month should get display in gray.

### Use Case

I want to display full month view calendar with next/previous month's dates/days as grayed out instead of empty space.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/26768.
