### ISSUE TITLE
help(Migrating to MDC-based Angular Material Components): TextEncoder is not defined error

### ISSUE THREAD

**Issue by Wendryl** [angular/components#26423]
### What are you trying to do?

I'm currenctly trying to upgrade my legacy material components to MDC and I'm getting the following error:
![image](https://user-images.githubusercontent.com/43496662/212189718-4da49386-1fac-45f4-ba3a-d5bd0f049836.png)

### What troubleshooting steps have you tried?

I tried some solutions like [messing around with node_modules dependencies](https://stackoverflow.com/questions/19697858/referenceerror-textencoder-is-not-defined), but no success.

### Reproduction

Steps to reproduce:
1. Run `ng generate @angular/material:mdc-migration`
2. Select one or more components to migrate: 
![image](https://user-images.githubusercontent.com/43496662/212190172-b084d7be-1fdb-4a4a-b3b1-3173b65da634.png)

### Environment

- Angular: 15.1.0
- CDK/Material: 15.1.0
- Browser(s): Google Chrome Version 109.0.5414.74 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 22.04.1 LTS x86_64

**Comment by mstawick** [comment]
I've experienced the same behavior. What I did is modify the file:
`./node_modules/@angular/material/schematics/ng-generate/mdc-migration/index_bundled.js`

adding this line at the top:
`var { TextEncoder, TextDecoder } = require("util");`

After this the migration ran as expected.

node v18.13.0 btw

**Comment by leomayer** [comment]
Same here - with the provided fix the command run as expected

**Comment by PowerKiKi** [comment]
Out of 10 projects, 9 failed with this error. Luckily the provided workaround fixed the migration for all projects.

**Comment by Wendryl** [comment]
Thanks to @mstawick I fixed that issue when adding the TextEncoder/TextDecoder on the mdc-migration module.
It works as expected now!
Thank you so much!

**Comment by leomayer** [comment]
Just as side note after analysis on our side: the command shell was running with Node 19.2.0 while the installed version pointed to 19.4.0. `Util` is available since 8.3.x - so it should be found within the context anyway.

It's the `fingerprint` method which uses the first time the Text decoder.

The other problem is that it's highly unclear if the script finished or not. Would be great to have at least an end notification plus documented what to expect when the script finished.

**Comment by PowerKiKi** [comment]
The script will output a list of all files updated. From memory, it looked something like:

```
[UPDATED] src/main.ts
```

If you have no output at all, maybe checked last exit code with something like `echo $?`. But most likely it finished without finding anything to update. Or else you'd see error thrown.

**Comment by DaSchTour** [comment]
Is this maybe related to this issue? https://github.com/angular/angular/issues/48748

**Comment by DaSchTour** [comment]
Or maybe related to this? https://github.com/angular/angular-cli/pull/24662

**Comment by mmalerba** [comment]
Closing as a dup of https://github.com/angular/angular-cli/pull/24662

**Comment by Adarshg315** [comment]
> 

@mstawick  will it not work for node -v 18.11.0 ?
