### ISSUE TITLE
docs-bug(THEME): Difference between Angular Material Theming all-component-colors and all-component-themes?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#26425]
### Documentation Feedback

Could someone please help with this question:

[Difference between Angular Material Theming all-component-colors and all-component-themes?](https://stackoverflow.com/questions/74890266/difference-between-angular-material-theming-all-component-colors-and-all-compone)

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/26342.
