### ISSUE TITLE
bug(COMPONENT): Mat Date picker not showing in Mat Dialog

### ISSUE THREAD

**Issue by hrandika** [angular/components#26432]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When added a date picker on the reactive form witch is in a dialog, the picker does not show up. But one top right corner the pop is there but not visible.

### Reproduction

Steps to reproduce:
1. Create a dialog with reactive form in it.
2.Have a Mat Date picker
3. Try to open the picker
<img width="887" alt="image" src="https://user-images.githubusercontent.com/7107923/212414396-e8b1e247-5913-4e71-81a6-23924ec8d383.png">

### Expected Behavior

Should show the picker next to the input

### Actual Behavior

picker shows in top right corner not visible also

### Environment

- Angular: 15.0.0
- CDK/Material: 15.1.0
- Browser(s): Chorome/Safari
- Operating System (e.g. Windows, macOS, Ubuntu):Ubuntu/MacOS

**Comment by EliseoPlunker** [comment]
I feel that it's not a bug else you have an error in your code, check this [working stackblitz](https://stackblitz.com/edit/angular-2b1i2t?file=src%2Fapp%2Fdialog-overview-example-dialog.html,src%2Fapp%2Fdialog-overview-example.ts,src%2Fapp%2Fdialog-overview-example.html). NOTE: Works on FireFox and Chrome (Windows)

**Comment by hrandika** [comment]
Issue seem to be produced when we call the open() method from another service. If we call open() from component it works fine. Will update on finding
