### ISSUE TITLE
bug(mat-table): Wrong row height for flex

### ISSUE THREAD

**Issue by angelaki** [angular/components#26438]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm just checking the new MDC guidline / changelog and was wondering why in the [demo](https://material.angular.io/components/table/examples#table-flex-basic) the new row height (52px) was missing for the flex table. 

This is because the height is reset here https://github.com/angular/components/blob/main/src/material/table/_table-flex-styles.scss#L3 to (the old) 48px but if I'm not mistaken the value needs to be 52px (or gets picked from the original style)?

Btw. the same is for padding. The flex table overrides the expected default values from MDC.

### Reproduction

Flex-Table of the example does not have the new height:

https://material.angular.io/components/table/examples#table-flex-basic

### Expected Behavior

Using flex / html table should not make a difference in row height?

### Actual Behavior

Flex / Html table differ in row height ...?

### Environment

- Angular: 15.0.3
- CDK/Material: 15.0.2

**Comment by andrewseguin** [comment]
This is intentional as per the comments in `table.scss`:

```

// Flex rows should not set a definite height, but instead stretch to the height of their
// children. Otherwise, the cells grow larger than the row and the layout breaks.
.mat-mdc-table mat-header-row.mat-mdc-header-row,
.mat-mdc-table mat-row.mat-mdc-row,
.mat-mdc-table mat-footer-row.mat-mdc-footer-cell {
  height: unset;
}

```
