### ISSUE TITLE
docs-bug(THEME): Is it ok to use mat.$private-dark-primary-text? 

### ISSUE THREAD

**Issue by hisham** [angular/components#26439]
### Documentation Feedback

I'm upgrading to v15, and need access to $dark-primary-text to setup my theme. Previously I would import it via `@angular/material/theming as mat` and then use mat.$dark-primary-text. 

With v15, ```mat``` is imported via `@use '@angular/material' as mat`, and dark-primary-text is available via mat.$private-dark-primary-text. 

What is the recommended approach to get access to the dark-primary-text color? Should we continue to import @angular/material/theming or is this considered legacy at this point? 

Better documentation to support migrating to the new theme API is needed overall. 

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by crisbeto** [comment]
`@angular/material/theming` is considered legacy and will be removed eventually and the `private-` prefix in the variable implies that it's only exported for use within the library and may be removed in the future. You should be able to extract the color from the palettes though. E.g. `$red-palette.contrast.50`.
