### ISSUE TITLE
bug(CHIP): Keyboard interaction is sometimes not possible

### ISSUE THREAD

**Issue by ftaffelt** [angular/components#26435]
### Is this a regression?

- [ ] no

### Description

Template code using ngTemplateOutlet for the content seems to break the keyboard interaction for chips. See the stackblitz:
[https://stackblitz.com/edit/components-issue-83xaa2?file=src%2Fapp%2Fexample-component.html](https://stackblitz.com/edit/components-issue-83xaa2?file=src%2Fapp%2Fexample-component.html)

### Reproduction

Steps to reproduce:
1. open [Showcase](https://stackblitz.com/edit/components-issue-83xaa2?file=src%2Fapp%2Fexample-component.html)
2. keyboard interaction with the first chip listbox works
3. keyboard interaction with second chip listbox fails

### Expected Behavior

Users can move through the chips using the arrow keys and select/deselect them with space.

### Actual Behavior

No keyboard interaction in the second block.

### Environment

- Angular:15.0 also 15.1
- CDK/Material: 15. also 15.1
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
This configuration isn't supported. We use `ContentChildren` to find the chips inside the chip set and `ContentChildren` don't work when they're placed in an `ng-template` outside of the list.

**Comment by TemRhythm** [comment]
@ftaffelt in your case you can put your template inside mat-chip-listbox content and tabIndex will set to '0'
```
<mat-chip-listbox>
    <ng-container *ngTemplateOutlet="options"></ng-container>
    <ng-template #options>
        <mat-chip-option>first</mat-chip-option>
        <mat-chip-option>second</mat-chip-option>
        <mat-chip-option>third</mat-chip-option>
    </ng-template>
</mat-chip-listbox>
```

**Comment by ftaffelt** [comment]
> in your case you can put your template inside mat-chip-listbox content and tabIndex will set to '0'
thanks, this is how i rewrote my code.
