### ISSUE TITLE
After updating to angular material 15 my components stayed ba

### ISSUE THREAD

**Issue by alexdomingues** [angular/components#26448]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![image](https://user-images.githubusercontent.com/31892337/213072498-870351fa-fe48-4cbb-ac69-2e4658c85014.png)

### Reproduction

<mat-form-field class="" appearance="outline">
                            <mat-label>First name</mat-label>
                            <input matInput>
                          </mat-form-field>

### Expected Behavior

the standard

### Actual Behavior

![image](https://user-images.githubusercontent.com/31892337/213072600-e367f9b7-c621-4fa0-8fb6-85a1036d52cc.png)

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
