### ISSUE TITLE
bug(mat-button): mat-mdc-button-disabled not reflected

### ISSUE THREAD

**Issue by angelaki** [angular/components#26445]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When disabling the new mdc button I expected a style `mat-mdc-button-disabled` getting applied. With the old button a style `mat-button-disabled` was applied as well.

### Reproduction

Just disable a <button mat-button>

### Expected Behavior

Class `mat-mdc-button-disabled` getting applied. At least this should get mentioned in the migration guide.

### Actual Behavior

No class is applied to determine the buttons state.

### Environment

- Angular: 15
- CDK/Material: 15

**Comment by crisbeto** [comment]
The class is an implementation detail, not a public API. The MDC versions set the `disabled` attribute instead.
