### ISSUE TITLE
bug(Theming): dark theme input labels are hard to read with the built-in custom theme template

### ISSUE THREAD

**Issue by The-MAZZTer** [angular/components#26441]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Not sure if present or not, it's in 15.0 and 15.1, I did not check older versions.

### Description

Input and select boxes are given a brighter background ("on-surface" color) using a focus overlay div when you hover or focus them. The resulting background color is a light gray. This can make some label text colors more difficult to read than necessary including the default custom theme set up by the ng add setup script for @angular/material.

Oddly enough if I enable auto dark mode in Chrome's flags it decides to change this white background into a black one which looks much better (this is what initially sent me on this rabbit hole because I forgot it was on and doing things as it does).

### Reproduction

https://stackblitz.com/edit/angular-ivy-mftvsq

Material docs site has the same problem; focus either input field in the first example while using either of the provided dark themes:

https://material.angular.io/components/input/overview

I first reproduced using the command line tools:

Steps to reproduce:
1. ng new <project> (no routing)
2. cd <project>
3. ng add @angular/material (custom theme, enable animations)
4. change the theme to dark mode in styles.scss.
5. add mat input and mat form field modules to app.module.ts
6. add a mat input to app.component which uses a mat-label.
7. ng serve and check it out

### Expected Behavior

The label should remain readable while the input is focused.

IMO the focus overlay for input/select/textarea should be less opaque white or should be black ("surface" color?) instead to avoid lowering contrast with text color. Not sure if light theme needs adjustment as well, I think it was more readable.

Alternatively the label and underline should be white instead of primary color for maximum readability.

I don't know what the material guidelines have to say about this if anything.

### Actual Behavior

The text is difficult to read while the input is focused as the background becomes a light gray and the label color is primary.

### Environment

- Angular: 15.1.0
- CDK/Material: 15.1.0
- Browser(s): Chrome 111.0.5532.2 and 108.0.5359.126
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 11 22H2 and Windows 10 21H2

**Comment by crisbeto** [comment]
This is fixed with the M3 styles.
