### ISSUE TITLE
feat(mat-menu): add an active CSS class for the active (selected) mat-menu-item

### ISSUE THREAD

**Issue by GregoireLgt** [angular/components#26452]
### For accessibility purposes,

The selected mat-menu-item should have a CSS active class to put some border color or something else to clearly state what mat-menu-item is ACTIVE...

Regards,

**Comment by crisbeto** [comment]
The menu items can't be selected so there's no way for us to know when to apply the class. You should be able to apply any custom class you want to them though.

**Comment by GregoireLgt** [comment]
@crisbeto, i see. I think in my case / context, we slightly twisted the mat-menu from its original use because we use them as the main application menu to change the route. So that might be why, thanks for your response

Regards,
