### ISSUE TITLE
"Could not find Material Core Theme" during SSR - Angular Universal

### ISSUE THREAD

**Issue by jwittekind** [angular/components#26468]
### What are you trying to do?

In my server.ts logs of my angular universal ssr app a warning gets show on every Request.
It's not visible on client side chrome devTools logs.

`Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming`

Though, the theming still works as expected.

### Troubleshooting

I followed this guide for angular material theming: https://material.angular.io/guide/theming

My styles.scss looks somtheing like this:

### styles.scss
```
@use '@angular/material' as mat;

@include mat.core();

// Import Palettes
@import 'palettes';

// Import typography css
@import 'typography';

$ep-light-theme: mat.define-light-theme(
  (
    color: (
      primary: $ep-primary-palette,
      accent: $ep-accent-palette,
      warn: $ep-warn-palette,
    ),
    typography: $ep-typography,
    density: 0,
  )
);

@include mat.core-theme($ep-light-theme);

$ep-dark-theme: mat.define-dark-theme(
  (
    color: (
      primary: $ep-dark-primary-palette,
      accent: $ep-dark-accent-palette,
      warn: $ep-dark-warn-palette,
    ),
    typography: $ep-typography,
    density: 0,
  )
);

.adm-dark-theme,
.ep-dark-theme {
  @include mat.all-component-themes($ep-dark-theme);
}
```

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.0
- Browser(s): Chrome and node.js Inspector
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by crisbeto** [comment]
We have a `typeof getComputedStyle !== 'function'` check [here](https://github.com/angular/components/blob/main/src/material/core/common-behaviors/common-module.ts#L111) that should prevent the theming check from running on the server. Is it possible that you're mocking out `getComputedStyle` on your server?

**Comment by jwittekind** [comment]
In deed i have discovered a simple mock here:
`global['getComputedStyle'] = () => ({ getPropertyValue: () => '' });`

Interesting! Removing it really does make the warning disappear from the server logs.
That's what i was looking for. 

So, i did not open an issue here, but is there a reason why the server side renderer is not checked by 
`isPlatformServer()` or renders the core theme appropriately?
if computed styles are necessary they can obviously not be correct.
But wouldn't it a better solution to get rid of this warning?

**Comment by crisbeto** [comment]
We have the warning, because it's common for people to forget to include the theme and file issues that their components don't look correctly. That being said, we should be able to detect the server in a more robust way.

**Comment by jwittekind** [comment]
Awesome! Thank you!  🙌
