### ISSUE TITLE
bug(mat-checkbox): Incorrect value ('on') for @Input FormControl

### ISSUE THREAD

**Issue by marekwalach** [angular/components#26481]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `mat-checkbox` with `[formControl]` and providing to it FormControl created inside the same component that implements `<mat-checkbox>` then value of this control is `true/false` but when we provide identical FormControl but from `@Input` in the component then the value of such control after first interaction is set to `'on'` and stay that way forever.

### Reproduction

Steps to reproduce:
1. Create component which implements `<mat-checkbox>` with `[formControl]` attribute
2. Add `@Input formControl: FormControl` to the component and use it to provide FormControl to the mat-checkbox
3.  Observe value of provided FormControl.

StackBlitz: [https://stackblitz.com/edit/angular-ivy-6c3wq8](https://stackblitz.com/edit/angular-ivy-6c3wq8)

### Expected Behavior

Value of FormControl should always be `true/false` no matter where FormControl was originated. 

### Actual Behavior

FormControl value (provided via `@Input`) after first interaction is set to `'on'` and stay that way forever.

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.1
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by mmalerba** [comment]
This appears to be a result of the `ngDefaultControl` directive you added. That provides an instance of [DefaultValueAcessor](https://github.com/angular/angular/blob/main/packages/forms/src/directives/default_value_accessor.ts), but a checkbox should be using a [CheckboxValueAccessor](https://github.com/angular/angular/blob/main/packages/forms/src/directives/checkbox_value_accessor.ts) Removing the attribute makes it behave normally: https://stackblitz.com/edit/angular-ivy-hqtjk5?file=src%2Fapp%2Fapp.component.html
