### ISSUE TITLE
bug(drag-drop): cdkDragHandle is not working on table resp. columns

### ISSUE THREAD

**Issue by ValentinBossi** [angular/components#26483]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In a table row only a specific coulmn should be to initiate the dragging. now its the whole row.

### Reproduction

Steps to reproduce:
1. go  to https://stackblitz.com/edit/angular-467iil-rbkkrf?file=src%2Fapp%2Fcdk-table-basic-example.ts,src%2Fapp%2Fcdk-table-basic-example.html 
2. only "No." column should be possible to initiate the drag not another column

### Expected Behavior

on a table i want to define that the first column can be used to initiate the dragging.

### Actual Behavior

i can specify which column has like an drag start event listener. now the whole row is like a listener.

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.1
- Browser(s): chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by andrewseguin** [comment]
In your example, the code shows that the row is the one being dragged:

```
  <tr (cdkDragStarted)="onDragStart($event)" cdkDrag cdk-row *cdkRowDef="let row; columns: displayedColumns;"></tr>

```

Nothing indicates that only a column should be dragging

**Comment by ValentinBossi** [comment]
@andrewseguin sure cause otherwise the row is not draggable? how would you do it?
