### ISSUE TITLE
bug(drag.drop): .cdk-drag-preview {   cursor: grabbing !important;} does not show grabbing

### ISSUE THREAD

**Issue by ValentinBossi** [angular/components#26495]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

i want to show a grabbing cursor when dragging is  ongoing otherwise grab. thats not working.
with component css selector .cdk-drag-preview this should work. other css is working.

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

cursor should be grabbing.

### Actual Behavior

cursor is default.

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by mmalerba** [comment]
`.cdk-drag-preview` has `pointer-events: none` to prevent it from interfering with the drag/drop operation. This means things like `cursor` and `:hover` styles won't work on it
