### ISSUE TITLE
bug(nav-list): Missing hover effects when list-item is inside a ng-template

### ISSUE THREAD

**Issue by fast-facts** [angular/components#26494]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Latest Angular 14

### Description

`mat-list-item`s within a `mat-nav-list` do not have the proper hover effect (cursor changes to a point and the background is highlighted) if the `mat-list-item` is inside an `ng-template` and is created via a `ng-container`. 

### Reproduction

Steps to reproduce:
1. Open the following url: https://stackblitz.com/edit/components-issue-w3jdyg?file=src/app/example-component.html
2. Hover over all 6 `span`s

### Expected Behavior

All 6 `span`s should be highlighted when hovered over

### Actual Behavior

Only 3 of the `span`s are highlighed, namely 1, 3 and 5

### Environment

- Angular:  15.1.1
- CDK/Material: 15.1.1
- Browser(s): Latest chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by ftaffelt** [comment]
this sounds a lot like #26435
