### ISSUE TITLE
feat(card): Add primary action directive/component

### ISSUE THREAD

**Issue by MikaStark** [angular/components#26497]
### Feature Description

Hi, first of all thanks for all the hard work done until now on Angular Material, especially MDC migration.

If we look at [Material cards specs](https://m2.material.io/components/cards#actions), an action section specify that a card can have a `primary action`. Today, Angular Material doesn't provide any component or directive that cover this spec.

```html
<div class="mdc-card">
  <div class="mdc-card__primary-action" tabindex="0">
    <!-- content within actionable area -->
    <div class="mdc-card__ripple"></div>
  </div>
  <!-- ... content ... -->
</div>
```

Of course, we could add a simple wrapping tag with the appropriated `class`, `tabindex` and even a `matRipple` directive. But like `mat-card-header` or `mat-card-content`, a `mat-card-primary-action` directive could be nice and avoid direct usage of MDC

#### Actual

```html
<mat-card>
  <div class="mdc-card__primary-action" tabindex="0" matRipple>
    <!-- content -->
  </div>
</mat-card>
```

#### Proposal

```html
<mat-card>
  <div mat-card-primary-action>
    <!-- content -->
  </div>
</mat-card>

<mat-card>
  <mat-card-primary-action>
    <!-- content -->
  </mat-card-primary-action>
</mat-card>
```

**Comment by amysorto** [comment]
Thanks for the support, it is appreciated! Right now, `mat-card` isn't an interactive element. It's unlikely we add support for this in the near future, so I'll be closing this bug.

Although for documentation, interactivity is also something that the [m3 specs](https://m3.material.io/components/cards/specs) also specify for elevated cards: .
