### ISSUE TITLE
bug(cdk/drag-and-drop): drag handle does not work in ng-template

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [angular/components#26493]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

Is there any way to connect cdkDrag element with ng-template where in that ng-template there is a cdkDragHandle?

I would like to drag element only by tag marked with cdkDragHandle.

### Reproduction

Here is small stackblitz to show the issue: https://stackblitz.com/edit/angular-admshu?file=src/app/cdk-drag-drop-connected-sorting-group-example.html

### Expected Behavior

When I drag element with cdkDragHandle in ng-template it works properly - only element tagged with cdkDragHandle can drag the wole element.

### Actual Behavior

CdkDragHandle is not taken into account. 

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by piyapanw** [comment]
First of all, I am very new to Angular.
If you would like to drag element only by tag marked with cdkDragHandle.
You can use card instead of ng-template.

https://stackblitz.com/edit/angular-admshu-aya7ug?file=src/app/cdk-drag-drop-connected-sorting-group-example.html

**Comment by crisbeto** [comment]
Angular uses `ContentChildren` to find the handle inside the `cdkDrag`. `ContentChildren` doesn't work across template boundaries like this hence why the handle isn't being picked up.
