### ISSUE TITLE
bug(mat-sort): sort arrow changes, but data is not sorted in the table

### ISSUE THREAD

**Issue by woteska** [angular/components#26506]
### Is this a regression?

I do not know.

### The previous version in which this bug was not present was

I do not know.

### Description

Data is not sorted in children's table when triggering the children's sorts to work in sync with the parent table's sort.

### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/edit/angular-yzr1r9-jtjxz6?file=src/app/table-sorting-example.ts
2. Click on the first 'Name' column on the top 2 times (sort should be active: 'name', direction: 'desc')
3. Verify that the parent table's rows are sorted correctly (in desc alphabetical order)
4. And also see that the children's table sort arrow points to the good direction
5. Also also see that the data is not sorted in the children's table (despite point 4.)
6. Verify that the children's data sorted only if the children's table header is clicked directly

Note: children's headers are not visible in the real use-case, it is visible now only for the demo.

### Expected Behavior

Data should be sorted in all tables.

### Actual Behavior

Data is not triggered to be sorted.

### Environment

- Angular: 14
- CDK/Material: 14
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

See demo.

**Comment by rpisarew** [comment]
It's stop working for me too, but with Angular Material v13.3.0. If I click on a column it calls my handler, but every time with the direction 'asc' and it does not cycle through the directions on further clicks.

**Comment by rpisarew** [comment]
I stepped with the debugger through the sort code, it looks like the current active sort column is not stored and because of that it is setting the direction to 'asc' every time (see [here](https://github.com/angular/components/blob/29056380e26a2a9501c32194de84a97b32a56fba/src/material/sort/sort.ts#L169)).

```typescript
  sort(sortable: MatSortable): void {
    if (this.active != sortable.id) {
      this.active = sortable.id; // <-- this.active is still undefined on the next call
      this.direction = sortable.start ? sortable.start : this.start;
    } else {
      this.direction = this.getNextSortDirection(sortable);
    }

    this.sortChange.emit({active: this.active, direction: this.direction});
  }
```

**Comment by woteska** [comment]
> I stepped with the debugger through the sort code, it looks like the current active sort column is not stored and because of that it is setting the direction to 'asc' every time (see [here](https://github.com/angular/components/blob/29056380e26a2a9501c32194de84a97b32a56fba/src/material/sort/sort.ts#L169)).
> 
> ```ts
>   sort(sortable: MatSortable): void {
>     if (this.active != sortable.id) {
>       this.active = sortable.id; // <-- this.active is still undefined on the next call
>       this.direction = sortable.start ? sortable.start : this.start;
>     } else {
>       this.direction = this.getNextSortDirection(sortable);
>     }
> 
>     this.sortChange.emit({active: this.active, direction: this.direction});
>   }
> ```

Nice! Do you have a workaround idea?
I have also tries to programatically set the sort by setting the dataSource.sort.sort(getSortable()), but it worked really strange.

**Comment by rpisarew** [comment]
I'm still searching for a solution (I have this one only with one table), but your Stackblitz is working for me properly.

**Comment by rpisarew** [comment]
I found my issue. The problem for me was that the component was unmounted to show a loader and that was resetting the internal state.

**Comment by amysorto** [comment]
The sorting on the Stackblitz is also working for me. Thanks @rpisarew for helping debug!

**Comment by woteska** [comment]
> The sorting on the Stackblitz is also working for me. Thanks @rpisarew for helping debug!

Please reopen it, because it is not working and does not connects to @rpisarew's issue.

The toppest No. sort header clicked only. You can see that the child table No. data is not sorted!

![Media_230507_021550](https://user-images.githubusercontent.com/6689409/236651527-6111b3f2-4655-491d-9226-f2efa0ffb1fc.gif)
