### ISSUE TITLE
help(mat-form-field matInput): How to resize component?

### ISSUE THREAD

**Issue by Rezorl** [angular/components#26518]
### What are you trying to do?

What is the best way to resize mat-form-field input? I have several inputs in the application and each of them has a different size, is it possible to do this using mat.input-theme or mat-typography? In angular 13 you had to change the font-size.

### What troubleshooting steps have you tried?

I've tried overriding the scss classes, but that seems like a bad idea to me.

### Reproduction

```
<mat-form-field class="small-input" appearance="fill">
  <mat-label>Input</mat-label>
  <input matInput>
</mat-form-field>

<mat-form-field class="normal-input" appearance="fill">
  <mat-label>Input</mat-label>
  <input matInput>
</mat-form-field>

<mat-form-field class="big-input" appearance="fill">
  <mat-label>Input</mat-label>
  <input matInput>
</mat-form-field>

.small-input {
@include mat.what? // height 20px 

}

.big-input {
@include mat.what? // height 80px
}

```

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by tomicarsk6** [comment]
Maybe you can use textarea instead of input, and use ``cdkTextareaAutosize`` directive to fit its content. There is even an official example of how you can [resize](https://material.angular.io/cdk/text-field/overview#text-field-autosize-textarea) textarea.

**Comment by Rezorl** [comment]
Thanks for the answer, that's what I was looking for.

I have one more question.

What's the best way to change the height of a mat-form-form in matInput?

The standard mat-form-field matInput has 78px height and I would like to set 60px in one of them and 50px in the other.

It is possible?

**Comment by tomicarsk6** [comment]
From Angular Material v15 there is something called density which you can easily use to resize the ``mat-form-field``.  

The idea is that you can use a scale where zero represents a default density. You can then decrement the number for more density or increment the number for less density. You can read all about it [here](https://material.angular.io/guide/theming#customizing-density).

To see it in practice you can look at this [stackblitz](https://stackblitz.com/edit/angular-kyfetk-ybwdt8?file=src%2Fstyles.scss,src%2Fapp%2Fform-field-appearance-example.html) example.

To change the size of the ``mat-form-field``, you need to change the size of the container in which ``mat-form-field`` is defined as you can see as well on the same stackblitz example that I mentioned above.

If you are using an earlier version of Angular Material, you can just simply use the ``font-size`` option on the container as well.

**Comment by Rezorl** [comment]
Thanks a lot, this is exactly what I need to use in my application.

I noticed that with density -2 the mat-label stopped showing with appearance="fill". With appearance="outline" and density -2 the mat-label works fine.

**Comment by tomicarsk6** [comment]
To learn more about the density you can read the [material](https://m2.material.io/design/layout/applying-density.html#components) guidelines, I hope some things will be a little bit clearer to you afterward.
