### ISSUE TITLE
bug(mat-slider): Mat slider unstable values when sliding and when release click

### ISSUE THREAD

**Issue by vslzl** [angular/components#26517]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat slider with range (even without range) acts weird. When sliding thumb with mouse click and dragging, it shows the actual values properly but when you release the mouse button it changes its value abnormally. I attached a gif that demonstrates problem.

### Reproduction

```
                    <div class="w-full px-4">
                        <mat-slider class="mt-2 w-full mx-0" min="0" [max]="maxHoleSize"  disableRipple="true">
                            <input formControlName="minHoleSize" matSliderStartThumb>
                            <input formControlName="maxHoleSize" matSliderEndThumb>
                        </mat-slider>
                    </div>
```

just use this snippet with tailwindcss classes. 

### Expected Behavior

when you release the mouse, (as you can follow with starting and ending of ripple effects on gif) you'll see the anomaly.

### Actual Behavior

![Screen_Recording_2023-01-27_at_23_14_49_AdobeExpress](https://user-images.githubusercontent.com/17459982/215194490-c0cb2d53-8d88-44a0-a5c1-09be04c77db0.gif)

### Environment

- Angular:15.0.0
- CDK/Material:15.0.0
- Browser(s):firefox, safari
- Operating System (e.g. Windows, macOS, Ubuntu): macos

**Comment by wagnermaciel** [comment]
Could you try this on the latest patch. I believe this issue has been fixed

**Comment by vslzl** [comment]
Yes it works now, I should have checked that in the first place, sorry for your time. thanks
