### ISSUE TITLE
bug(mat-list): matListItemLine doesn't seem to take into account config `preserveWhitespaces: false`

### ISSUE THREAD

**Issue by maxime1992** [angular/components#26512]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Unsure whether that's always been the case or not.

I have `preserveWhitespaces` set to false in both my `tsconfig.json` and `main.ts` as a provided token with `COMPILER_OPTIONS`. 

So I'd expect no spaces around if I have:

```
<mat-list>
  <mat-list-item>
    <h3 matListItemTitle>test</h3>

    <p matListItemLine>
      Test
    </p>
  </mat-list-item>
</mat-list>
```

(note that in `matListItemLine` I went to a new line)

But I do get one: 

![image](https://user-images.githubusercontent.com/4950209/215053927-8ce72511-3adb-43fb-be51-1f343b24808a.png)

If I replace the `matListItemLine` by a `matListItemTitle` for example, that extra space is gone.

### Reproduction

[Stackblitz repro](https://stackblitz.com/edit/components-issue-jbaoti?file=src%2Fapp%2Fexample-component.html,src%2Fmain.ts,tsconfig.json)

### Expected Behavior

No extra space

### Actual Behavior

An extra space

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Both Chrome and Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by mrmokwa** [comment]
#26164

**Comment by maxime1992** [comment]
Woups, sorry for the duplicate and thanks for the link @mrmokwa !

Closing so we only have 1 to track

**Comment by mrmokwa** [comment]
Don't worry man! Unfortunatelly, don't think we'll have a solution soon, as pointed out by @crisbeto reply in the first issue.
