### ISSUE TITLE
feat(google-maps): Add the library to angular-cli update

### ISSUE THREAD

**Issue by alvarocjunq** [angular/components#26511]
### Feature Description

Include the `@angular/google-maps` library to the `ng update @angular/material` command .

**Comment by crisbeto** [comment]
Closing since `@angular/google-maps` is a separate package from `@angular/material`.

**Comment by alvarocjunq** [comment]
Hi @crisbeto 
Sorry for ask, but separate how? Since the code is here in the same repo?

https://github.com/angular/components/tree/main/src/google-maps

The feature request can be to include it? 
Thanks iin advance =)
