### ISSUE TITLE
docs-bug(Button): Mention that the MDC buttons have a more specific selector for the button color

### ISSUE THREAD

**Issue by AlexElin** [angular/components#26510]
### Documentation Feedback

The MDC buttons have a more specific selector for the button color (there was a related issue https://github.com/angular/material.angular.io/pull/1164 in this project earlier).

However, at the moment the Guide [Migrating to MDC-based Angular Material Components](https://material.angular.io/guide/mdc-migration#button) misses this moment.

I propose to add mentioning of the above change into the guide.

### Affected documentation page

https://material.angular.io/guide/mdc-migration#button

**Comment by amysorto** [comment]
Currently the only supported way of changing a button's color is through [theming](https://material.angular.io/components/button/overview#theming). Later this year we will support further customization of color with a new token-based theming API.
