### ISSUE TITLE
'MatIconRegistry' does not appear to be an NgModule, Component, Directive, or Pipe class.

### ISSUE THREAD

**Issue by AnassL** [angular/components#26521]
### Description

When added MatIconRegistry to Imports section of a freshly created app AppModule, I got error.

'MatIconRegistry' does not appear to be an NgModule, Component, Directive, or Pipe class.

### Actual Behavior

Here is the error message:

This likely means that the library (@angular/material/icon) which declares MatIconRegistry has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### Environment

- Angular: 15.1.2
- CDK/Material: 15.1.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by geromegrignon** [comment]
Hi @AnassL,

MatIconRegistry is not meant to be added to the imports on a ngModule.
As explained in the [docs](https://github.com/angular/angular/issues/30264):

> MatIconRegistry is an injectable service

**Comment by crisbeto** [comment]
Closing since this is a user error.
