### ISSUE TITLE
fear(BUTTON): Ability to convert all double clicks on all mat-buttons (or clickable elements in general) to single click

### ISSUE THREAD

**Issue by jpike88** [angular/components#26523]
### Feature Description

I use mat-button exclusively for clickable elements in my app. People often double-click buttons out of habit, which would trigger a double api call etc... it would be painstaking to add this debounce function to all mat-buttons in my code.

It would be good if I can have a global setting on which intelligently handles this.

### Use Case

Stop people from double clicking everything and getting weird results sometimes

**Comment by geromegrignon** [comment]
The button should not be clickable at all if some computation is happening and should not be triggered meanwhile.
Users should not have to guess what's happening and why clicking on an active button does not work.

Disable the button during the related computation.
