### ISSUE TITLE
bug(TYPOGRAPHY): `.mat-typography` CSS class no longer works in v15

### ISSUE THREAD

**Issue by hakimio** [angular/components#26524]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

After upgrade to v15 `.mat-typography` CSS class no longer works when using customized theme.
The issue can be reproduced in the official demos. For example, content of [the "Dialog content" demo](https://material.angular.io/components/dialog/overview#dialog-content) has incorrect styling.

Related bug reports: #26184 #26351

### Reproduction

Steps to reproduce:
1. Define your theme [the recommended way](https://material.angular.io/guide/theming): [theme.scss](https://stackblitz.com/edit/angular-zi6bkz?file=src%2Ftheme.scss)
2. Try to add `.mat-typography` CSS class to some container in your app

### Expected Behavior

Material design styles are applied to the section using `.mat-typography`.

### Actual Behavior

Material design styles are not applied

### Environment

- Angular: 15.1.2
- CDK/Material: 15.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by AlbertoBonfiglio** [comment]
@hakimio, 
Hi, I used the project in your [link](https://material.angular.io/components/dialog/overview#dialog-content) and customized the theme by adding to the $theme
`
typography: mat.define-typography-config(
    $font-family: 'Solitreo'
  ),
`
and '<link href="https://fonts.googleapis.com/css2?family=Solitreo&display=swap" rel="stylesheet">' to index.html

and seems to be working
![Screenshot 2023-01-31 115333](https://user-images.githubusercontent.com/15167415/215639778-2a65b3cc-8bc3-469a-9ecb-f682feb9ac17.jpg)

**Comment by hakimio** [comment]
@AlbertoBonfiglio that's not the issue I described. The issue is that styles from mat-typography are not applied.

**Comment by AlbertoBonfiglio** [comment]
Hi,
Could you please expand? Fo you have a sample of what styles are not
applied?

Cheers
Alberto

**Comment by Woogielicious** [comment]
> @AlbertoBonfiglio that's not the issue I described. The issue is that styles from `.mat-typography` are not applied.

Maybe first you should show some code of your implementation...

i had nearly the same issue and a lot of another and could it fix in my custom_theme where i have to export the typography to the components. 
The Angular 15 had a lot of changes in the custom styling. 

if you use a custom typo than you should write it like 


`$app-primary: mat.define-palette(map.get($theme-colors, 'color-primary'));`
`$app-accent: mat.define-palette(map.get($theme-colors, 'color-accent'));`
`$app-warn: mat.define-palette(map.get(base.$base-colors, 'color-warn'));`
`$typography: mat.define-legacy-typography-config();`
`$theme: mat.define-light-theme(`
  `(`
      `color: (`
       `primary: $app-primary,
       accent: $app-accent,
       warn: $app-warn,
      ),`
      `typography: $typography,`
      `density: 0,`
` )`
`);`
`@include mat.all-component-themes($theme);`
`@include mat.all-legacy-component-themes($theme);`
`@include mat.all-component-typographies($typography);`

the new thing in the mat.define-light-theme is that we have to declare here the typography and density, for that you need the line `$typography: mat.define-legacy-typography-config();` and next important is the "export" or "include" into all components, the second line below you need only when you write typography in the old way was also mentioned in the other bugs where wo linked in your bug.

`@include mat.all-component-themes($theme);`
`@include mat.all-legacy-component-themes($theme);`
`@include mat.all-component-typographies($typography);`

**Comment by hakimio** [comment]
I have linked official dialog demo project ("Dialog with header, scrollable content and actions") in my first post where you can clearly see that typography CSS is not applied to the content of the dialog.
I don't care about your theme customizations.

How the same demo looked in `v14`:
![v14](https://user-images.githubusercontent.com/768105/215794781-23e03c3b-adcb-419c-8619-6e9e2678ed9e.PNG)

How it looks now in `v15`:
![v15](https://user-images.githubusercontent.com/768105/215795992-13a73e82-7781-4bbc-b091-a4b9396c1004.PNG)

Can you spot the difference?

The missing CSS:
![styles](https://user-images.githubusercontent.com/768105/215794859-bfb043eb-aefe-41ae-8018-9357c63323d9.PNG)

**Comment by crisbeto** [comment]
It's because the `typography-hierarchy` mixin isn't included by default anymore. I've sent out a PR to update the docs. You should be able to get it to work by adding `@include mat.typography-hierarchy($your-typography-config)` to your theme.

**Comment by hakimio** [comment]
@crisbeto thank you for creating a PR to update the docs.
Would be great if the StackBlitz demos could be updated as well to fix the issue.

**Comment by elrondfeng** [comment]
I have the same issue. I added @include mat.typography-hierarchy($lawyer-typography); to my custom theme, but still not working
