### ISSUE TITLE
bug(cdk/drag-drop): Incorrect "this" in method given to cdkDropListSortPredicate

### ISSUE THREAD

**Issue by ionty** [angular/components#26525]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using cdkDropListSortPredicate to call a method in a component, "this" does not point to the component but to an object of type CdkDropList.

### Reproduction

Steps to reproduce:
1.  Use chrome to go to the Angular docs page https://material.angular.io/cdk/drag-drop/overview#controlling-whether-an-item-can-be-sorted-into-a-particular-index
2. Open the example for "Controlling whether an item can be sorted into a particular index" in Stackblitz
3. In the method sortPredicate insert a line like 
`console.log(this.constructor.name, this.numbers);`
4. Open the developer console of Chrome
5. Drag an item of the list over another item
6. Look into developer console and check if the right class name is output

### Expected Behavior

In the method sortPredicate "this" should point to the instance of CdkDragDropSortPredicateExample, the member numbers should be defined.

The output in the console should be something like

`CdkDragDropSortPredicateExample [1, 2, 3, 4, 5, 6, 7, 8]`

### Actual Behavior

In the method sortPredicate "this" points to an object of type CdkDropList. The member "numbers" is undefined.

The output in the console is
`CdkDropList undefined`

### Environment

- Angular: 13/14/15
- CDK/Material: 13/14/15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Linux/Ubuntu

**Comment by geromegrignon** [comment]
That's due to the way `sortPredicate` is used here.
If you need to access the component, change the function to :

```ts
sortPredicate() {
    return (index: number, item: CdkDrag<number>) => (index + 1) % 2 === item.data % 2;
  }
```

and the template to: `[cdkDropListSortPredicate]="sortPredicate()"`.

**Comment by crisbeto** [comment]
It's because we don't have access to the declaring component ourselves either. You can work around it by declaring your sort predicate as an arrow function. 

@geromegrignon your example can cause excessive change detections, because it returns a new function every time.

**Comment by ionty** [comment]
@crisbeto @geromegrignon Thanks a lot for your answers, I solved it with your hints.

Just one more question: Why is the component available in cdkDropListDropped but not in cdkDropListSortPredicate.

**Comment by Totati** [comment]
@ionty https://academind.com/tutorials/this-keyword-function-references
