### ISSUE TITLE
bug(schematics): running ng-add generator in a TS4.8.4 workspace errors

### ISSUE THREAD

**Issue by Coly010** [angular/components#26540]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Angular CLI (build-angular) has a peer dependency range of TS set as: `"typescript": ">=4.8.2 <5.0"`

I may be mistaken, but I assume this means that TS 4.8.2+ should be supported.

However, running the ng-add generator of `@angular/material` within an Angular Workspace that uses TS 4.8.4 results in a TS error during AST utils.

![image](https://user-images.githubusercontent.com/12140467/216028552-0f3e8e86-94a5-4f33-897d-53a5c6f99bb4.png)

The parsed source file (after running `parseSourceFile`) produces a different result between TS4.8.4 and TS4.9.5.

### Reproduction

Steps to reproduce:
1. npx -y @angular/cli@latest new testngadd
2. npm install typescript@4.8.4
3. npm install @angular/material@latest
4. ng g @angular/material:ng-add

### Expected Behavior

The ng-add generator should successfully integrate Angular Material to the application.

### Actual Behavior

The ng-add generator throws a TS AST error.
![image](https://user-images.githubusercontent.com/12140467/216029159-1f28d244-906e-43ed-b18f-7c1e4885cffa.png)

### Environment

Angular CLI: 15.1.3
Node: 16.17.1
Package Manager: npm 8.15.0
OS: darwin x64

Angular: 15.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.3
@angular-devkit/build-angular   15.1.3
@angular-devkit/core            15.1.3
@angular-devkit/schematics      15.1.3
@angular/cli                    15.1.3
@schematics/angular             15.1.3
rxjs                            7.8.0
typescript                      4.8.4

**Comment by crisbeto** [comment]
Closing since TS 4.8 isn't supported at the framework level anymore.
