### ISSUE TITLE
Angular v9 documentation is not accesible

### ISSUE THREAD

**Issue by ShaklinSyedMohammed** [angular/components#26548]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

not sure

### Description

I am trying to reach angular v9 documentation through the dropdown option present in the home page and also through google search, but it shows an error stating that address is not accessible

### Reproduction

Steps to reproduce:
1.  Go to angular material website
2. Click on the version dropdown and select v9

or
1. Search for angular material v9 in google
2. Click on the [v9.](https://v9.material.angular.io/) link

### Expected Behavior

Website to load

### Actual Behavior

Error screen where address is not accesible

### Environment

- Angular:
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): mac os, android

**Comment by tomicarsk6** [comment]
Everything is working normally, so I don't have an idea why you don't see it.

![Screenshot 2023-02-02 at 09 36 36](https://user-images.githubusercontent.com/14099912/216273103-76d4718f-fb69-411e-81e6-ba357f2713ee.png)

**Comment by ShaklinSyedMohammed** [comment]
Now its working fine, earlier had issue, thanks closing the ticket.
