### ISSUE TITLE
bug(mat-form-field): Form field with icon prefix or suffix makes long label overflow  

### ISSUE THREAD

**Issue by domestack** [angular/components#26558]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using mat-form-field together with <mat-icon> prefix or suffix and long label, label is overflowing input box. Seems that text-overflow: ellipse doesn't account for suffix neither prefix width. 

`<div class="row">
  <div class="col-2">
    <mat-form-field>
      <mat-icon matIconSuffix>info_outline</mat-icon>
      <mat-label>Very very very very very long label</mat-label>
      <input matInput />
    </mat-form-field>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <mat-form-field>
      <mat-label>Very very very very long label</mat-label>
      <input matInput [matDatepicker]="datePickerAfter" formControlName="applicationAfter">
      <mat-datepicker-toggle matIconPrefix [for]="datePickerAfter"></mat-datepicker-toggle>
      <mat-datepicker #datePickerAfter></mat-datepicker>
    </mat-form-field>
  </div>
</div>`

### Reproduction

Steps to reproduce:
1. Create mat-form-field with matIconSuffix or matIconPrefix.
2. Create mat-label with long text.
3. If label text is wider than input box, then label is overflowing it.

### Expected Behavior

Label should not overflow input box.

### Actual Behavior

![Screenshot 2023-02-02 193358](https://user-images.githubusercontent.com/113232400/216400803-0a5f73b8-18e9-4505-83da-fa0ab2bd2cf4.png)

### Environment

- Angular: 15.1.2
- CDK/Material: 15.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by henrikcomes** [comment]
Here is a Stackblitz with the Issue.
https://stackblitz.com/edit/angular-tq1tvp?file=src%2Fapp%2Fselect-overview-example.html

**Comment by Mesya82** [comment]
Just a bump because encountering the same issue

**Comment by pmpak** [comment]
We also spotted the same issue. We are currently using:

Angular: 17.3.5
CDK/Material: 17.3.5

**Comment by alexmacavei** [comment]
Seems like the label inside the mat-mdc-form-field-infix has a longer width than it's parent. Setting it to 100% does the trick, but I'm not sure if that's MD intent or it's really a bug. It also looks weird on our project when we have, for ex, 2 suffix buttons in the form input field.
