### ISSUE TITLE
bug(MatDialog): Modal dialog Custom Panel Class no longer applying styles

### ISSUE THREAD

**Issue by ewanstinson** [angular/components#26551]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.2

### Description

I recently upgraded Angular to version 15 and noticed the default padding of the dialog modal has been removed, which I believe was set to 24px previously.

Then I tried setting it manually through passing in a class declared on the main styles to the panelClass property, as described in the docs below, but every permutation of this doesn't seem to be working anymore.

https://github.com/angular/components/blob/main/guides/customizing-component-styles.md#styling-overlay-components

The only solution seems to be manually setting it in the component class being used for the dialog itself.

### Reproduction

As described in the docs:

https://github.com/angular/components/blob/main/guides/customizing-component-styles.md#styling-overlay-components

### Expected Behavior

Before the upgrade all our MatDialog modals had the 24px padding by default and custom styling wasn't an issue.

### Actual Behavior

Now there is no padding applied and can no longer apply custom styles as described in the docs.

### Environment

- Angular: 15
- CDK/Material: 15.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Andrea-Lucas** [comment]
+1

**Comment by AlexElin** [comment]
@ewanstinson As I see the absense of padding is as designed behavior for v15.
There's a special note regardnig this in the migration guide - https://material.angular.io/guide/mdc-migration#dialog
