### ISSUE TITLE
Material modules increases app size per each module. Reuse components.

### ISSUE THREAD

**Issue by infacto** [angular/components#26552]
Currently you indirectly forces developer to only use a single huge Angular module. Instead of using multiple modules. Why?
Because every time you import a Material module, it increases the app size. And even more if you use a shared module for this.

Example: 

You import `MatButtonModule` in two modules. Use case: A page and a dialog with its own module. Build you app and you see duplicated code. The MatButton code is not reused. It appears two times in built code as exact copy.

There is also an article what descibes the use of shared modules: 
https://indepth.dev/posts/1191/stop-using-shared-material-module
This will reduce the app size. But does not fix the core issue. 

In this issue we want to find a solution. Find a way to import this Framework/Components only once and use it in every module in you app without increasing the app size for each module by Material modules. Maybe tree-shaking? Would forRoot/forChild work? I'm sure you have better ideas. 

Why not just initialize the framework once in e.g. main or main module? Like the most other UIs work. E.g. Ionic.

**Comment by andrewseguin** [comment]
If you can show this is an issue, I'd recommend filing it against the framework itself. Off the top of the head, the only time I can imagine the sizes being bigger is when you are lazy loading some route or component, which probably comes self-contained. There is nothing we can do about this from the Material side
