### ISSUE TITLE
feat(Table): Add registerFilter function to MatDataSource

### ISSUE THREAD

**Issue by jcuenca95** [angular/components#26553]
### Feature Description

Add a register function to change the behavior of the filter as we do with `filterPredicate` but with all the dataset

### Use Case

I need to group the data based on condition and I can't implement this with filterPredicate because I need reference to the data array and to reduce this array.

**Comment by andrewseguin** [comment]
To access all the data, define your filterPredicate in a scope that has a reference to the data source and access the data from that

https://stackblitz.com/edit/hhnfwy?file=src%2Fapp%2Ftable-filtering-example.ts
