### ISSUE TITLE
bug(Stepper): Stepper does not respect theme font family

### ISSUE THREAD

**Issue by mattMcMt** [angular/components#26567]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.5

### Description

The typography used by the material stepper is the default Roboto font-family regardless of the defined typography theme configuration.

### Reproduction

Steps to reproduce:
1. Create a custom typography configuration in accordance with https://material.angular.io/guide/typography that uses a different font-family
2. Link to new font from index.html
3. Create a component that includes a material stepper
4. The step label will still be Roboto; other text on the page under the stepper will also be the default font-family

https://stackblitz.com/edit/components-issue-smzgm2

### Expected Behavior

The stepper label and other text under the stepper should respect the theme's typography configuration for font-family.

### Actual Behavior

The font-family used for the stepper label and other text under the stepper is the default Roboto even when a custom typography theme specifies a different font-family.

The theme specifies Open Sans as the font-family.  The easiest way to tell the difference is the shape of the 'g'.
![image](https://user-images.githubusercontent.com/124381122/216665366-97a681ec-a888-4a34-a69f-d58edc4f05ee.png)

I believe this is do to the stepper theme (_stepper-theme.scss) still using the 2014 typography definitions:
```
@mixin typography($config-or-theme) {
  $config: typography.private-typography-to-2014-config(
      theming.get-typography-config($config-or-theme));
  .mat-stepper-vertical, .mat-stepper-horizontal {
    font-family: typography-utils.font-family($config);
  }

```
Other components are using the 2018 config (ex from _card-theme.scss):
```
@mixin typography($config-or-theme) {
  $config: typography.private-typography-to-2018-config(
      theming.get-typography-config($config-or-theme));
  @include mdc-helpers.using-mdc-typography($config) {
    // Card subtitles and titles are an Angular Material construct (not MDC), so we explicitly
    // set their typographic styles here.
    .mat-mdc-card-title {
      @include mdc-typography.typography(headline6);
    }

    .mat-mdc-card-subtitle {
      @include mdc-typography.typography(subtitle2);
    }
  }
} 
```

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Should've been fixed in https://github.com/angular/components/pull/26471.
