### ISSUE TITLE
bug(mat-icon-button): mat-icon-button ignores density specification

### ISSUE THREAD

**Issue by eLarocque** [angular/components#26569]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi,
There seems to be an issue where `mat-icon-button` is not affected when setting the density option.

I'm not sure if this is intended, but according to material design spec, the icon buttons should be affected by the density options. 
reference: https://m2.material.io/design/layout/applying-density.html#components
(you can see the button icon examples)
![image](https://user-images.githubusercontent.com/8459019/216710371-85aec44a-1512-4969-b4ea-c39359b88832.png)

If this is intended, what would be the best way to make the buttons smaller?

### Reproduction

Steps to reproduce:
1. Apply the density option on buttons using the mat-icon-button directive `@include mat.button-density(-3);` 
2. The density (size) of the button does not change.

![image](https://user-images.githubusercontent.com/8459019/217101058-ae6c3a9c-5220-4e84-85e0-646cb43da252.png)

Demo: https://stackblitz.com/edit/angular-cf7rfy
In the stackblitz, you can see that although the first set of mat-button-icons are included in the selector that is affected by the `@include mat.button-density(-3);` and the second set is not, both sets are identical.

### Expected Behavior

I would expect a size change in the mat-icon-button

### Actual Behavior

mat-icon-button ignores density specification

### Environment

- Angular: 15.1.3
- CDK/Material: 15.1.3
- Browser(s): Chrome Version 109.0.5414.120
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by eLarocque** [comment]
Update: I added another example in the stackblitz when the mat-icon is used in a form control with density set at -5. You can see that the icon is blocking the form control from being at a -5 density.
![image](https://user-images.githubusercontent.com/8459019/217100728-8fb675a7-010b-4830-86f8-006941db8738.png)

This is with the following density settings:
```scss
@include mat.form-field-density(-5);
@include mat.icon-density(-5);
```

**Comment by ftaffelt** [comment]
mat icon-button has it's own density mixin. so you should use:

`@include mat.icon-button-density(-3);`

**Comment by eLarocque** [comment]
@ftaffelt nice catch, thanks for the info!

I still have an issue with regards to the second use case (in the form field), but I will open a new issue for that specifically.
