### ISSUE TITLE
docs-bug(COMPONENT): Theming

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#26573]
### Documentation Feedback

I asked about this on Stackoverflow.  The question is about how to avoid duplicating styles in Angular 15.

[This is the question](https://stackoverflow.com/questions/75276638/generating-an-angular-theme-for-angular-15).

The answer is to only call ` @include mat.all-component-themes($theme);` in the main theme, and then use `@include mat.all-component-colors($theme);` in subsequent themes like this.

However it seems to me that this will then leave out generated CSS code for the scope of that theme.

```
.dark-theme {
    //======================================
    // THEME INITIALIZATION
    //======================================
    @include mat.core-theme($theme);
    @include mat.all-component-themes($theme);
}
//and this being your secondary theme
.light-theme {
    //======================================
    // THEME INITIALIZATION
    //======================================
    @include mat.core-color($theme);  <---- This is the magic
    @include mat.all-component-colors($theme); <---- This is the magic
}
```

IIUC with the above type of theme generation the rules generated for the light and dark themes would be mutually exclusive, and so the light theme would only have the color specific CSS declarations, but would be missing CSS declarations generated for the dark theme with `mat.all-component-themes($theme);`.

Some clarification on this in the documentation would be terrific.

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by NetPenguins** [comment]
@fireflysemantics is this a question of the styles of the elements not being shared or the colors? If the concern is making css adjustments for specific components won't share the theme colors then that is an easy fix by using a theme mixin. This would follow the standards found at https://material.angular.io/guide/theming-your-components and allow you to pass in the colors based on the theme. Nothing fancy here just something simple like: 
```scss
@use "../../app/shared/components/example/example-theme" as example;

@mixin colors($theme, $typography-config) {
  @include example.theme($theme, $typography-config);
 ... //more included component themes 
}
```
Then in your light and dark themes you would jut include this `colors` mixin providing that themes defined object.

**Comment by fireflysemantics** [comment]
@NetPenguins angular themes are scoped using a class selector.

So in the stackoverflow question / answer we use the `.dark-theme` and `.light-theme` selectors to scope all the generated styles.

The scopes are mutually exclusive.  That means that styles scoped to the `.dark-theme` are only in effect when the dark theme is applied and vice versa.

So I think if we only use:
```
@include mat.all-component-colors($theme); <---- This is the magic
```

To generate say the light theme, it will. be missing styling that the dark theme has, and the dark theme has no way of sharing the missing styles with the light theme, since what is generated for the dark theme is scope with the `.dark-theme` class.

**Comment by NetPenguins** [comment]
@fireflysemantics so the way I accommodate this is by following the docs suggestion about breaking out theme based sass from the components styles  https://material.angular.io/guide/theming-your-components#step-1-extract-theme-based-styles-to-a-separate-file 

Using this same principle I create a shared mixin for all common elements like `a div main` etc and put them in a custom theme file. So creating. a directory in `styles` called elements and then adding an _index.scss. Inside I add 
```sass
// src/styles/elements/_index.scss
@use 'SASS:map';

@mixin custom-element-colors($theme) {
   $color-config: mat.get-color-config($theme);
   $primary-palette: mat.get($color-config, 'primary');
   $accent-palette: mat.get($color-config, 'accent');

   a {
      color: mat.get-color-from-palette($primary-palette);
      &:hover {
         color: mat.get-color-from-palette($primary-palette, A100);
   } 
 //... rest of color based styles 
}
```

Then in your theme files you can include the mixin using 
```sass
// src/styles/themes/_dark.scss
@use '../elements';
...
.dark {
   @include elements.custom-element-colors($theme-dark);
}
```


This is the same technique I apply to custom components as well as it is more directly explained in the docs.

**Comment by fireflysemantics** [comment]
@NetPenguins I understand the technique of breaking off the SASS for components that is theme specific.

And this technique is also mutually exclusive (Completely separate from / apples / oranges ... ) the issue of generating redundant styles when scoping themes.

IIUC at the moment the only way I know to generate all the styles required by a specific scope is to use `mat.all-component-themes($theme)` within its block scope ( `.dark-theme`, `.light-theme`, etc)

```
.dark-theme {
    //======================================
    // THEME INITIALIZATION
    //======================================
    @include mat.core-theme($theme);
    @include mat.all-component-themes($theme);
}
```

And the way I understand it is you have to do this for all blocks, in order for each block to have all the CSS required.

The reason for this is that blocks are mutually exclusive.  If you tried to generate a block like this:

```
    //======================================
    // THEME INITIALIZATION
    //======================================
    @include mat.core-color($theme);  <---- This is the magic
    @include mat.all-component-colors($theme); <---- This is the magic
```

It would be missing CSS / SASS from `all-component-themes` and since blocks are mutually exclusive the application will now be missing some CSS ...

**Comment by fireflysemantics** [comment]
@NetPenguins I think maybe this is the way it has to be done.  First generate a default theme without scoping it like this:

```
$my-app-theme: mat.define-light-theme(
  (
    color: (
      primary: $my-app-primary,
      accent: $my-app-accent,
      warn: $my-app-warn,
    ),
  )
);
@include mat.core-theme($theme);
@include mat.all-component-themes($my-app-theme);
```

So if we don't apply a scope class at all to the `body` ( Like `.dark-theme` for example) the theme will just be the default.

And then for other themes outside of the default generate them like this ( Light Theme Example):

.light-theme {
    //======================================
    // THEME INITIALIZATION
    //======================================
    @include mat.core-color($theme);  <---- This is the magic
    @include mat.all-component-colors($theme); <---- This is the magic
}

So now the "Magic" should work ... Knock on wood ... Because the `.light-theme` rules will be applied, but if there is additional shared "Global" CSS used that is not color specific those rules will still be applied as well ...

If someone from Angular could confirm that this is the right way to use the API that would be awesome ...

**Comment by wagnermaciel** [comment]
Yeah, the correct is to have the default theme be declared in global scope and then only override the colors using the colors mixin within the scope of the new theme(s). I'd also recommend avoiding using `all-component-*` mixins and instead using the specific mixins for the components being used in your app (e.g. `mat.button-theme`) to avoid pulling in unnecessary styles for unused components
