### ISSUE TITLE
help(ComponentHarness): TestElement.sendKeys() on disabled inputs

### ISSUE THREAD

**Issue by alvaromartmart** [angular/components#26577]
### What are you trying to do?

I expect `TestElement.sendKeys` to respect the disabled status of input elements, however they don't seem to. The input is properly disabled on the application, the harness properly detects its disabled status... but `sendKeys` seems to bypass it.

Maybe I misunderstood something, any help would be appreciated.

### What troubleshooting steps have you tried?

I tried running extra change detection cycles, etc. to no avail.

### Reproduction

Steps to reproduce:
1. In the Stackblitz demo below, the test `CustomInputHarness > should not fill disabled input` should pass

https://stackblitz.com/edit/node-g4jhab?file=harness-sendkeys-demo/src/app/custom-input-component/custom-input-component.harness.ts

### Environment

- Angular: 14.2, 15.1
- CDK/Material: 14.2, 15.1
- Browser(s): Chrome, though doesn't seem relevant
- Operating System (e.g. Windows, macOS, Ubuntu): macOS, though doesn't seem relevant

**Comment by crisbeto** [comment]
We can't do this across all the environments we support (TestBed, Protractor and WebDriver), because the e2e testing framework won't send keyboard events to disabled elements. We could make it work on TestBed, but then the behavior will be inconsistent.
