### ISSUE TITLE
bug(List): mat-list-items insterted via content projection are not interactive

### ISSUE THREAD

**Issue by phrei** [angular/components#26582]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

In a `mat-nav-list` all `mat-list-item`s should be considered "interactive" (see [docs](https://material.angular.io/components/list/overview#navigation) and [Code](https://github.com/angular/components/blob/5f0f071ac5bece0ecb7a5b2a196615d420841b3c/src/material/list/nav-list.ts#L38)) but this is not the case with `mat-list-item`s that are inserted into the list with content projection.

### Reproduction

Outline.html
```
<mat-nav-list>
  <ng-content select="[menu]">
  </ng-content>
...
```

Component.html
```
<ng-container menu>
        <a mat-list-item [routerLink]="myRouterLink">
            <mat-icon matListItemIcon>note_add</mat-icon>
            <span>Add</span>
        </a>
```

Other `mat-list-item`s that are directly under the `mat-nav-list` get the correct CSS-Class.

You can see it because the cursor doesn't change for non interactive items.

### Expected Behavior

All `mat-list-item`s should be considered "interactive".

### Actual Behavior

`mat-list-item`s that are inserted with content projection are not considered "interactive".

### Environment

Angular CLI: 15.1.4
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 15.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             15.1.4
rxjs                            6.6.7
typescript                      4.8.4

**Comment by crisbeto** [comment]
Closing since the list uses `ContentChildren` to find the items which won't work if they're declared outside of the element. This is how projection works at the framework level and we don't have control over it.
