### ISSUE TITLE
docs-bug(datepicker): Improve/Describe type `D`

### ISSUE THREAD

**Issue by infacto** [angular/components#26594]
### Documentation Feedback

What's `D`? Please describe. Also: A single letter type is maybe not the best type. Is it generic? I cannot find type reference. Btw, is `string` also allowed? It seems so... 

![image](https://user-images.githubusercontent.com/60390085/217581608-bb215682-7016-4228-9575-4ca5b3bb44ce.png)

Update: There is also an input type `C`.
Update: Ok, as I see, the output is a dayjs instance. Adapter. (A weird uglyfied output on console.)

Anyway, can we descibe als these types and where they come from (adapter, etc.)?

### Affected documentation page

https://material.angular.io/components/datepicker/api

**Comment by AlexElin** [comment]
This issue is subset of the https://github.com/angular/components/issues/22121 issue.

**Comment by crisbeto** [comment]
Closing since this should be covered in https://github.com/angular/components/issues/22121.
