### ISSUE TITLE
bug(mat-select): Mat Select trigger with chips inside going out of mat-form-field-wrapper

### ISSUE THREAD

**Issue by ajayz09** [angular/components#26591]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Mat Select Trigger Multiple | Angular 14

Mat Select Trigger with chips inside is going outside of the mat-form-field-wrapper when number of selections exceeds a certain value as it tries to populate to a new line.

This was working as expected in Angular 10-12

### Reproduction

Steps to reproduce:
1. Use mat-select-trigger with mat-chips
2. Select multiple options from the selection panel expanding the mat-form-field to another line.

### Expected Behavior

![image](https://user-images.githubusercontent.com/38266421/217435942-b8e07998-0c32-4293-8937-6c88f3031faf.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/38266421/217435811-5486024c-e915-4e08-a733-61c609ddf1db.png)

### Environment

- Angular: 14.2.4
- CDK/Material: 12.2.6
- Browser(s): Google chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
This isn't a supported pattern, because it doesn't make sense from an accessibility perspective.
