### ISSUE TITLE
feat(MatSelect): MatOptgroup should have programmatic capability

### ISSUE THREAD

**Issue by boomdizz** [angular/components#26595]
### Feature Description

I have a need to programatically manipulate the mat-optgroup. My usecase has a cascade/sequence of filters (MatSelects) that is needed to query the backend for 'Automobiles' that match the query. The filters are things like 'Manufacturer', 'Model' etc..... So as the consumer selects a Manufacturer, the downstream filter for Model only shows the Models that correspond to that Manufacturer (or that set of manufacturers, as I am using 'multiple' on the MatSelect). The final set of filters make a graphql query (could well be a REST API instead) to the backend that return some attributes of the selected group of Autos, e.g. mpg, etc.) So pretty straightforward design.
Each filter is a multiple select filter where the end user can select multiple options on the filter. There is an 'All' option group that contains all of the options in the filter/MatSelect. Visually, the option group does what it should. But I need to programatically manipulate the option group. I have rules like - if none of the options are selected in a group, enable all the options in the group. Essentially, none is not a valid option. I need to:
(1) From an option find the parent option group
(2) Check if the option group has no options enabled and/or all options enabled
(3) Enable/Disable the entire option group in one API call.
I can provide additional details as needed.
I am working with Angular material 14.2.6

### Use Case

Use cases provided in the Feature Description

**Comment by boomdizz** [comment]
Any thoughts on this request?

**Comment by crisbeto** [comment]
We don't really offer programmatic APIs for any of our components, because the idea is that this should be done through the template through something like `ngFor`.
