### ISSUE TITLE
bug(mat-menu): mat-menu opens at the bottom of the page on mobile device

### ISSUE THREAD

**Issue by DemeSteve** [angular/components#26602]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In my angular material data table there is vertical three dots in a cell in each row. Clicking on this three dots opens a mat-menu. On computer it works fine, but from mobile device it opens at the bottom of the page from the 92nd row.
If the viewport meta tag is not added it is wrongly showing from the 92nd row. If it's added it is wrongly showing even from the first row.

### Reproduction

I have
`<meta name="viewport" content="width=device-width, initial-scale=1">`
in my application.

### Expected Behavior

From mobile devices the mat-menu should open next to the button where I click it.

### Actual Behavior

From mobile devices the mat-menu opens at the bottom of the page (with a css bottom: 0 or bottom: 2px generated).

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by DemeSteve** [comment]
Update: meta viewport has nothing to do with this issue.

**Comment by zarend** [comment]
Hello @DemeSteve ,

Thank you for reporting this issue. I cannot reproduce.  I was wondering if we could check with you if this issue requires further action. Could you please provide a stackblitz reproduction of the issue?

Environment
 - iPhone SE (1st gen)
 - iOS 15.7.3
 - https://material.angular.io/components/menu/overview

-Zach
