### ISSUE TITLE
bug(checkbox): tick colour does not change when using css variables

### ISSUE THREAD

**Issue by andrew-cunliffe** [angular/components#26605]
### Is this a regression?

- No

### Description

We are building a new project and need to be able to theme the site, to make this easier we are using material plus tailwind and as such using css variables to define a number of things including colours...

The issue is that with a dark colour the tick is remaining as black rather than changing to white as it does when using a hex value

### Reproduction

Steps to reproduce:
1.  New project and create CSS variables like...  :root { --color-primary-normal: #442244 }
2. Setup material with a theme like....

```
$palette: (
    50: var(--color-primary-light),
    100: var(--color-primary-normal),
    200: var(--color-primary-dark),
    A50: var(--color-accent-light),
    A100: var(--color-accent-normal),
    A200: var(--color-accent-dark),
    contrast: (
        50: var(--color-white),
        100: var(--color-white),
        200: var(--color-white),
    ),
);

$ui-primary: mat.define-palette($palette, 100, 50, 200);
$ui-accent: mat.define-palette($palette, A100, A50, A200);

$ui-theme: mat.define-light-theme(
    (
        color: (
            primary: $ui-primary,
            accent: $ui-accent,
        ),
    )
);

@include mat.checkbox-theme($ui-theme);
```

3. Use the mat-checkbox on your page (set to primary or accent) the tick remains black

### Expected Behavior

Should use the contrast colour for the tick and support css variables when doing this

### Actual Behavior

does not detect and change the colour to contrast correctly

### Environment

- Angular: 15.1.x
- CDK/Material: 15.1.x
- Browser(s): Safari, Chrome, Firefox
- Operating System: macOS

**Comment by andrew-cunliffe** [comment]
Currently for a workaround, having to do this

```
.mat-mdc-checkbox.mat-primary {
    --mdc-checkbox-selected-checkmark-color: var(--color-white);
}
```

**Comment by crisbeto** [comment]
Closing since we don't support CSS variables like this. We're in the process of providing a new theming API based on variables.
