### ISSUE TITLE
bug(DatePicker): Incorrect parsing of date when typing YYYY-MM-DD format

### ISSUE THREAD

**Issue by jmaruiz** [angular/components#26617]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Date picker input updates to the previous day when using this specific format: YYYY-MM-DD
You must use hyphens and double digit month and day (from my testing).

### Reproduction

Steps to reproduce:
1. Problem exists in the documentation page = https://material.angular.io/components/datepicker/overview
2. Manually type in 2023-02-13 into the first test input
3. Press tab to blur input
4. See that the date has been updated to 2/12/2023

### Expected Behavior

Date should update to 2/13/2023

### Actual Behavior

Date actually updates to the previous day, in this case 2/12/2023

### Environment

- Angular: 15
- CDK/Material: 15.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Tested in Windows and macOS

**Comment by wagnermaciel** [comment]
I'm going to consider this a non issue because the desired input pattern for that datepicker is MM/DD/YYYY. Your input would work on a different locale - https://material.angular.io/components/datepicker/examples#datepicker-locale
