### ISSUE TITLE
custom theme : Undefined mixin (angular material 15.1.4)  @include theme.validate-theme-styles($light-theme, $theme)

### ISSUE THREAD

**Issue by elrondfeng** [angular/components#26610]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

SASS custom theme stopped working. 

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
54 │   @include theme.validate-theme-styles($light-theme, $theme);
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  @material\linear-progress\_linear-progress-theme.scss 54:3                 theme-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 14:3  -palette-styles()
  node_modules\@angular\material\core\theming\_all-theme.scss 47:5           @content
  node_modules\@angular\material\core\theming\_theming.scss 402:3            private-check-duplicate-theme-styles()
  node_modules\@angular\material\core\theming\_all-theme.scss 44:3           all-component-themes()
  src\lawyer.scss 35:1                                                       root stylesheet

### Reproduction

Steps to reproduce:
1. angular version: 15.1.4 ;  angular material version: 15.1.4 
2. create a custom theme : 

@use '@angular/material' as mat;
@import '@angular/material/theming';
@include mat.core();

$my-primary: mat.define-palette(mat.$indigo-palette, 800);
$my-accent: mat.define-palette(mat.$green-palette, A700);
$my-warn: mat.define-palette(mat.$red-palette,A700);

$theme: mat.define-light-theme((
  color: (
    primary: $my-primary,
    accent: $my-accent,
    warn: $my-warn,
  )
));

@include mat.core-theme($theme);
@include mat.all-component-themes($theme);

3. ng build

### Expected Behavior

ng build successful 

### Actual Behavior

ng build failed.  some angular material components can apply the custom themes successfully, like button
some angular material components including the mat.checkbox-theme and mat.dialog-theme  need to use the  validate-theme-styles mixin,  failed. 

./src/lawyer.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
54 │   @include theme.validate-theme-styles($light-theme, $theme);
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  @material\linear-progress\_linear-progress-theme.scss 54:3                 theme-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 14:3  -palette-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 35:7  @content
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 193:5    @content
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 233:3    disable-mdc-fallback-declarations()
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 192:3    using-mdc-theme()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 33:3  color()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 60:7  @content
  node_modules\@angular\material\core\theming\_theming.scss 402:3            private-check-duplicate-theme-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 54:3  theme()
  node_modules\@angular\material\core\theming\_all-theme.scss 47:5           @content
  node_modules\@angular\material\core\theming\_all-theme.scss 47:5           @content
  node_modules\@angular\material\core\theming\_theming.scss 402:3            private-check-duplicate-theme-styles()
  node_modules\@angular\material\core\theming\_all-theme.scss 44:3           all-component-themes()
  src\lawyer.scss 35:1                                                       root stylesheet

### Environment

- Angular:
- CDK/Material:
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

Angular: 15.1.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@angular/fire                   7.5.0
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             15.1.5
rxjs                            7.5.7
typescript                      4.9.5

**Comment by HiveSolution** [comment]
Hey @elrondfeng, did you find a solution for this problem? I'm currently struggling with the same error.

**Comment by MikeMatusz** [comment]
I'm experiencing this is as well. `material-components-web` hasn't released in a year (most likely related to the Material Design 3 shift), which puts other libraries that rely on them in a tough spot, since there are various breaking changes but no consolidated changelog.  Seems like it wouldn't be too uncommon to have an app that uses both `@angular/material` and another library for a composite component also based on Material.

**Comment by MikeMatusz** [comment]
FYI, I haven't tried the migration to MDC-based components yet, but I was able to proceed with legacy components for now by adding `node_modules/@angular/material/node_modules` explicitly in `includePaths`, or `styleIncludePaths` for ng-packagr.

**Comment by andrewseguin** [comment]
It sounds like this is because your application has it's own dependency on Material Components Web. Unfortunately we do not support this case
