### ISSUE TITLE
mat-input does not disable when we use attr.disabled / [disabled] in html

### ISSUE THREAD

**Issue by devayazahmed** [angular/components#26625]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-input does not disable when we use attr.disabled in html while readonly is working fine

### Reproduction

Steps to reproduce:
1. attr.disabled/ [disabled] is not working on mat-input when we use in HTML file
2. Read only is working on mat-input when we use in HTML file

### Expected Behavior

[disabled] should allow on mat-input when we use in HTML file

### Actual Behavior

[disabled] is not working on mat-input when we use in HTML file

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The input overrides the `attr.disabled` in a host binding. You should use `[disabled]` to bind to it instead.
