### ISSUE TITLE
SassError: 'Hue "100" does not exist in palette. Available hues are: 500, contrast'

### ISSUE THREAD

**Issue by mayankgpt185** [angular/components#26622]
### What are you trying to do?

I have upgraded my angular version from 12 to 13.3.10 after removing node modules i'm getting a following sass error:-

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: 'Hue "100" does not exist in palette. Available hues are: 500, contrast'
55 │     lighter: _get-color-from-palette($base-palette, $lighter),
  

### What troubleshooting steps have you tried?

steps that didn't work:-
1. removed node_modules and package-lock.json, reinstalled then
2. added @import '~@angular/material/core/theming/theming'; in style.scss
3. upgraded node-sass version to latest

### Reproduction

Steps to reproduce:
1. update angular to version 13
2. npm i and ng s

### Environment

- Angular: 13.3.10
- CDK/Material:13.3.9
- Browser(s): chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by aikrez** [comment]
The pallette needs at least 3 hues: 100, 500, 700

**Comment by crisbeto** [comment]
As mentioned in the other comment, it's likely because your theme palette is incomplete.
