### ISSUE TITLE
docs-bug(Accordion): Accordion provider

### ISSUE THREAD

**Issue by Alessandroinfo** [angular/components#26639]
### Documentation Feedback

In many cases in Angular Material to communicate with parent component is used a parent provider with injection token and there is a comment that says:

(For example into the accordion)
```
/**
* Injection token that can be used to reference instances of `CdkAccordion`. It serves
* as alternative token to the actual `CdkAccordion` class which could cause unnecessary
* retention of the class and its directive metadata.
*/
export const CDK_ACCORDION = new InjectionToken<CdkAccordion>('CdkAccordion');
```

And in the child component it's needed to use like this:
`constructor(@Inject(ACCORDION) accordion: AccordionComponent){}`

What mean this and why it's not enough only use into the child component the reference of the parent component like this:

`constructor(public cdkAccordion: CdkAccordion){}`

Thanks

### Affected documentation page

accordion

**Comment by crisbeto** [comment]
As mentioned in the doc string: we use the token to avoid retaining the accordion unnecessarily.
