### ISSUE TITLE
bug(cdkDrag): strange behavior of cdkDropList elements while we changed their state

### ISSUE THREAD

**Issue by AnnaKozlova** [angular/components#26640]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a collapse animation for expansion panels that needs to be triggered when dnd is clicked and started; when mousedown happen, but before move; the time of the animation can be different; every expansion panel is drag element;

1. It is not clear how to track the situation when we want to update an element before interacting with dnd or even in dnd process;

maybe you have some solutions on this? 

2. There is a strange situation if we try to change the state of such panels already on the dragStart event => the panels are collapsed, but the dnd logic breaks; placeholder appears in unexpected places here;

[example](https://stackblitz.com/edit/angular-csru2j?file=src%2Fapp%2Fexpansion-overview-example.ts)

### Reproduction

Steps to reproduce:
1. change state of drag elements during drag start

### Expected Behavior

1. it would be great to have some approach for interacting with dnd elements before directly starting dnd
2. even if the state of the items changes during drag -> this does not break the logic

### Actual Behavior

1. there is no default approach to change state before drag start
2. dnd behaves strangely if the internal state of the elements changes

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.1
- Browser(s): Chrome
- Operating System: macOS

**Comment by Achilles1515** [comment]
https://github.com/angular/components/issues/14703

**Comment by mmalerba** [comment]
This sounds like the same issue as https://github.com/angular/components/issues/14703, due to the expansion panel height changing. Closing as a duplicate
