### ISSUE TITLE
bug(MatRipple): MatRipple can not be disabled for child components (in some scenarios)

### ISSUE THREAD

**Issue by angelaki** [angular/components#26656]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

(mousedown)="$event.stopPropagation()" stopped MatRipple from doing animations triggered by child components

### Description

With Angular Material 14 it was possible to stop the MatRipple from getting triggered by child components utilizing a `(mousedown)="$event.stopPropagation()"`. With Angular 15 it somehow stopped working. It is still working for simple scenarios but somehow not e.g. in MatTable

### Reproduction

In this stackblitz [AngularMaterial15](https://stackblitz.com/edit/angular-phk79p) the column _NoRipple_ is still triggering MatRipple while it wasn't with [AngularMaterial14](https://stackblitz.com/edit/angular-gcpqiz).

### Expected Behavior

Be able to let e.g. buttons in the table not trigger the row's ripple effect.

### Actual Behavior

Row's MatRipple effect always gets triggered.

### Environment

- Angular: 15
- CDK/Material: 15

**Comment by crisbeto** [comment]
This isn't something we've ever supported. The supported way to disable ripples is through the `disableRipple` input on the directive or Angular's `[@.disabled]` bindings.

**Comment by angelaki** [comment]
@crisbeto but I guess that's a behavior many people are relying on? I guess just because of the many issues with the new components most are still stuck on the legacy ones.

In my scenario I have a button in a mat-table-row for showing actions for this row. When clicking the button, a context-menu opens but the row click won't happen (navigate to the record) and I don't want to show the ripple-effect. Should I actually disable the ripple on button click, wait for a timeout and re-enable it? Or is there another approach? I guess my use-case is quite common. Sure it _wasn't ever supported_. But does a library explicitly need support common JS event handling (like `stopPropagation` / `preventDefault`)?

**Comment by crisbeto** [comment]
The `mousedown` events are just an implementation detail though, we never advertised the fact that it uses `mousedown` as being a public API. Your example doesn't work anymore, because we started using event delegation for the ripples under the hood to improve the initialization time. You might be able to work around it with CSS instead. E.g. set `.mat-ripple-element { display: none; }` whenever there's a `:active` on your row.

**Comment by angelaki** [comment]
I just checked the code and I guess the main reason is that you switched to [capture](https://github.com/angular/components/blob/ef0fa0569216ea1f47b4da4757dacdcbc59b5546/src/material/core/ripple/ripple-event-manager.ts#L15). Is there a reason this can't stay a regular bubbling event? Than users where able to stop the handler from elements **below** the ripple effect. What is a quite common use-case imho.

Since the handler is passive anyway, captureing or not will almost have no performance impact.

**Comment by angelaki** [comment]
I've adopted my example a bit so you see a _real world scenario_: [stackblitz](https://stackblitz.com/edit/angular-phk79p-fyt248). With AngularMaterial14 the button wouldn't trigger to ripple effect. And it still wouldn't, if the event was bubbling.

**Comment by angelaki** [comment]
@crisbeto what do you think about my _real world scenario_? Isn't this something that should be supported? At least I cannot find a nice workaround / solution for this.
