### ISSUE TITLE
bug(mat-slider): ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by bageren** [angular/components#26653]
### Is this a regression?

- I don't know but didn't notice it previously

### Description

When using mat-slider together with portals, Angular throws "NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked" in development mode.

### Reproduction

Steps to reproduce:
1. Create a mat-slider in a template.
2. Create a new TemplatePortal with template from step 1
3. Create a portal outlet and pass in the TemplatePortal from step 2

https://stackblitz.com/edit/angular-ylc6kv?file=src%2Fmain.ts

### Expected Behavior

I would expect Angular to not throw "NG0100: ExpressionChangedAfterItHasBeenCheckedError"

### Actual Behavior

Angular throws "NG0100: ExpressionChangedAfterItHasBeenCheckedError"

### Environment

- Angular: 15.1.5
- CDK/Material: 15.1.5
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by wagnermaciel** [comment]
This does not seem to be an issue with the slider. The changed after checked error you're seeing is coming from the application. Here is the same example throwing the same error, except without using the mat-slider

https://stackblitz.com/edit/angular-xjbbma?file=src%2Fmain.ts,src%2Findex.html
