### ISSUE TITLE
bug(mat-button): Button Animation Not Working With Angular 15 Legacy mat-button Component

### ISSUE THREAD

**Issue by fearghalom** [angular/components#26666]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.13

### Description

I upgraded an application from Angular v12 to Angular v15 and noticed an issue with a spinner animation on a  legacy mat-raised-button component. We'd like to upgrade to Angular v15 without migrating to the latest Angular Material MDC components at this time. When using the legacy imports on V15, the spinner animation doesn't activate. If I use the latest imports in Material v15, the spinner animation works ok. 

### Reproduction

Steps to reproduce:
1. I've created a project on GitHub to reproduce the issue: https://github.com/fearghalom/angular15_material_issue.git
2. I've defined a custom theme
3. I've created a simple app with two buttons. One is a mat-raised-button (legacy) and the other is a simple HTML button. 
4.  Clicking on a button should show the spinner animation but it only works on the simple HTML button. 
5. If i change from the legacy Material imports to the latest, the spinner on the mat button works ok. 
6. I did some investigation and found that commenting out a line in _node_modules/@angular/material/core/focus-indicators/_private.scss_ , resolved the issue.

```
@use 'sass:map';
@use 'sass:meta';
@use '@angular/cdk';
@use '../style/layout-common';
@use '../theming/theming';

// Private sass variables that will be used as reference throughout component stylesheets.
$default-border-width: 3px;
$default-border-style: solid;
$default-border-color: transparent;
$default-border-radius: 4px;

// Mixin that renders the focus indicator structural styles.
@mixin structural-styling($prefix) {
  .#{$prefix}-focus-indicator {
    position: relative;

    &::before {
      @include layout-common.fill();
      box-sizing: border-box;
      pointer-events: none;
      //display: var(--#{$prefix}-focus-indicator-display, none);  !!!! COMMENTING OUT THIS LINE FIXED ISSUE  !!!!// Hide the indicator by default.
      border: var(
          --#{$prefix}-focus-indicator-border-width,
          #{$default-border-width}
        )
        var(
          --#{$prefix}-focus-indicator-border-style,
          #{$default-border-style}
        )
        var(
          --#{$prefix}-focus-indicator-border-color,
          #{$default-border-color}
        );
      border-radius: var(
        --#{$prefix}-focus-indicator-border-radius,
        #{$default-border-radius}
      );
    }

    // By default, render the focus indicator when the focus indicator host element takes focus.
    // Defining a pseudo element's content will cause it to render.
    &:focus::before {
      content: '';
    }
  }
```

### Expected Behavior

Button spinner should work as in Angular v12.

### Actual Behavior

Button spinner does not activate.

### Environment

Angular CLI: 15.1.6
Node: 14.21.2
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 15.1.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5

**Comment by crisbeto** [comment]
This looks like an issue in a custom style override. Closing since this isn't something we have control over.
