### ISSUE TITLE
bug(mat-dialog-content): mat-dialog-content style messed up 

### ISSUE THREAD

**Issue by elrondfeng** [angular/components#26669]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I am using a custom theme. I upgraded from 14 to 15. all of my dialog which use mat-dialog-conent looks really weird now.  
![image1](https://user-images.githubusercontent.com/12999574/220371113-b782bb87-c30d-4c70-83af-8e946c83db8d.png)
previously, it looked like this: 
![image](https://user-images.githubusercontent.com/12999574/220371243-916d21fc-22e2-4496-bc49-b44002ff780b.png)

there are some css added to mat-mdc-dialog-content: 
![image](https://user-images.githubusercontent.com/12999574/220371380-efd0b7ba-2295-4eba-a6b6-66a2fc3dfe85.png)

I changed my custom theme to : 
`// Custom Theming for Angular Material
// For more information: https://material.angular.io/guide/theming
@use '@angular/material' as mat;
// Plus imports for other components in your app.

// Include the common styles for Angular Material. We include this here so that you only
// have to load a single css file for Angular Material in your app.
// Be sure that you only ever include this mixin once!
@include mat.core();

// Define the palettes for your theme using the Material Design palettes available in palette.scss
// (imported above). For each palette, you can optionally specify a default, lighter, and darker
// hue. Available color palettes: https://material.io/design/color/
$lawyer-primary: mat.define-palette(mat.$indigo-palette, 800);
$lawyer-accent: mat.define-palette(mat.$green-palette, A700);

// The warn palette is optional (defaults to red).
$lawyer-warn: mat.define-palette(mat.$red-palette,A700);
$lawyer-typography: mat.define-typography-config();
@include mat.typography-hierarchy($lawyer-typography);

// Create the theme object. A theme consists of configurations for individual
// theming systems such as "color" or "typography".
$lawyer-theme: mat.define-light-theme((
  color: (
    primary: $lawyer-primary,
    accent: $lawyer-accent,
    warn: $lawyer-warn,
  ),
  typography: $lawyer-typography,
/*  density: 0,*/
));

// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include mat.all-component-themes($lawyer-theme);
@include mat.all-component-typographies($lawyer-typography);
@include mat.typography-hierarchy($lawyer-theme);`

but, the mat.typography-hierarchy does not help

### Reproduction

Steps to reproduce:
1. use a custom theme 
2. use mat-dialog-content 

### Expected Behavior

the style is same as before on angular material 14

### Actual Behavior

style looks very wierd 

### Environment

- Angular:  15.1.5
- CDK/Material: 15.1.5
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by wagnermaciel** [comment]
Hi, your theme file seems to be set up correctly. If I had to guess, there is probably some custom css in your application trying to style the internals of the mat-dialog which are no longer being applied due to changes in the internal dom structure of the mat-dialog from v14 to v15. If it is possible to avoid depending on our internal dom structure for your custom css, I would recommend doing so to prevent your css from breaking in the future

I'll also mention that it is incorrect to expect that the v14 components look the same as v15 components. There were many changes in the appearance of our components and it is possible that the appearance will change in the future to continue to keep up with the material design specs
