### ISSUE TITLE
bug(mat-checkbox): Value gets removed when disable is present on Formcontrol

### ISSUE THREAD

**Issue by invaderb** [angular/components#26671]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Not 100% sure if this is a bug or intended feature but it causing me a bit of a headache.  

I have a dynamically generated form to manage user permissions across a bunch of tools and has a few stipulations on how those permissions can be added or removed based on grantable/role permissions I want to be able to disable those mat checkboxes but still have a potential value for them however I noticed that if disable is added to the formcontrol when adding to a formarray the value is getting completely removed.

Is there a way around this, any help would be greatly appreciated.

### Reproduction

reproduced stackblitz
https://stackblitz.com/edit/angular-wtakex?file=src/app.component.ts

### Expected Behavior

Even if disable is added there should still be a value

### Actual Behavior

Value is removed when disable is present on formcontrol

### Environment

- Angular: v15
- CDK/Material: v15
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This is how the forms module works, we don't have control over it in Material.
