### ISSUE TITLE
bug(mat-chip-row): color property doesn't update chip background color

### ISSUE THREAD

**Issue by KaoDeo** [angular/components#26670]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Giving theme palette color to the color input doesn't update color of the component.

### Reproduction

Steps to reproduce:

1. Giving any color values to [color] doesn't change background color of the chip

https://stackblitz.com/edit/components-issue-xulxok?file=src%2Findex.html,src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts

### Expected Behavior

Background color of the chip should be the value assigned('primary' | 'accent' | 'warn') to the color input as it is described in API.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/91371368/220386611-29ec9202-dad8-4762-91ec-2620271efd2b.png">

### Actual Behavior

The component doesn't change color and has a grey color.

### Environment

- Angular: 15.1.5
- CDK/Material: 15.1.4
- Browser(s): Google Chrome 
- Operating System: Windows

**Comment by crisbeto** [comment]
The color only applies when the chip is selected.

**Comment by KaoDeo** [comment]
> The color only applies when the chip is selected.

When I click the chip, the background still doesn't change. You can test that on the demo

**Comment by crisbeto** [comment]
Ah right, only the `mat-chip-listbox` allows selection, not the `mat-chip-grid`. You can get the non-selectable chips to show their color by adding the `highlighted` attribute, e.g. `<mat-chip-row color="warn" highlighted>item</mat-chip-row>`.

**Comment by crisbeto** [comment]
Closing since it's working as expected and there's an API to achieve the result.
