### ISSUE TITLE
bug(component): No documentation for style overriding

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#26684]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a styling library which styles all material components based on a given desing specs.  But material v15 has migrated all angular components styles to [MDC components](https://github.com/material-components/material-components-web) which broke all our extisting styles because of DOM structure change.

Now we are again planning to styles all MDC components but this time we want to follow future proof styling path but I don't see any document which I can follow and add extensive styles on top of MDC styles.

I can see material now using `--mdc-*` custom properties for all components and using those variables I can override the styles but I don't see any documentation for the same.

Angular material now using [MDC](https://m2.material.io/components/) styles but MDC suggesting [Material Design 3](https://github.com/material-components/material-web) which is yet another web component library based on Lit.

Does Angular material continue using [MDC](https://m2.material.io/components/) components styles or planning to use  [Material Design 3](https://github.com/material-components/material-web) styles. 

What should be the best path for such users who want to override styles on top of Angular material library.

### Reproduction

NA

### Expected Behavior

There should be a proper documentation for style overriding 

### Actual Behavior

NA

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
In general we don't encourage style overrides directly since they might break if we change the internal HTML. We're in the process of implementing a new theming API that would allow for the variables to be set.
