### ISSUE TITLE
bug(google-maps): google.maps.ControlPosition.RIGHT_TOP returning undefined when pushing measure distance widget

### ISSUE THREAD

**Issue by marwanataviva** [angular/components#26682]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are running some unit tests for our google map component where the tests seem to fail due to `google.maps.ControlPosition.RIGHT_TOP` returning undefined when trying to push the measure distance widget element in our `ngAfterViewInit()` function like so: `this.map.controls[google.maps.ControlPosition.RIGHT_TOP].push(measureDistanceWidgetRootElement)`

where `measureDistanceWidgetRootElement` is defined as a native element:
`this.measureDistanceWidget.map = this.map.googleMap!`
`let measureDistanceWidgetRootElement = this.measureDistanceWidget.element.nativeElement`

Error output:
`TypeError: Cannot read properties of undefined (reading 'push')`

However, all the tests pass once we change the control position to a value that does not return undefined, like `google.maps.ControlPosition.RIGHT_BOTTOM`. This behavior is only observed when running the unit tests and not while the application is running, the measure distance widget works as expected. Therefore, we want to know why some control positions are returning undefined while others are not and if this error could be replicated.

### Reproduction

Steps to reproduce:

Create a measure distance widget component and try pushing it to the RIGHT_TOP control position in ngAfterViewInit() as a native element, something like this:

`this.measureDistanceWidget.map = this.map.googleMap!
let measureDistanceWidgetRootElement = this.measureDistanceWidget.element.nativeElement
this.map.controls[google.maps.ControlPosition.RIGHT_TOP].push(
            measureDistanceWidgetRootElement
        )`

### Expected Behavior

`google.maps.ControlPosition.RIGHT_TOP` should not return undefined and the unit tests pass.

### Actual Behavior

`google.maps.ControlPosition.RIGHT_TOP` returns undefined and the unit tests fail.`

### Environment

- Angular CLI: 13.3.10
- Node: 16.14.0
- Package Manager: npm 8.3.1
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 64 bit

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.10
@angular-devkit/build-angular   13.3.10
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.10
@angular/cdk                    13.3.9
@angular/cli                    13.3.10
@angular/flex-layout            13.0.0-beta.38
@angular/google-maps            13.3.9
@angular/material               13.3.9
@schematics/angular             13.3.10
rxjs                            7.8.0
typescript                      4.6.4

**Comment by crisbeto** [comment]
This is likely because the Google Maps API isn't included in the tests.
