### ISSUE TITLE
feat(CDN): @angular/material CDN resources not available in v13

### ISSUE THREAD

**Issue by WangJiaoJo** [angular/components#26697]
### Feature Description

Hi, 

There are the CDN resources for @angular/material@11.2.12 and @angular/material@12.2.12 but no CDN resource for v13+.
https://cdn.jsdelivr.net/npm/@angular/material@12.2.12/bundles/
https://cdn.jsdelivr.net/npm/@angular/material@11.2.12/bundles/

Is there any reason that the CDN resources are not available from v13?
Thanks.

**Comment by crisbeto** [comment]
You might have to reach out to the people responsible for jsdelivr.net since it's not something we control.

**Comment by crisbeto** [comment]
We don't do anything for jsdelivr at all. They must have picked it up at some point and stopped picking it at a later point.

**Comment by WangJiaoJo** [comment]
Got it. 
May I ask do you know how to build this js for CDN usage?
https://cdn.jsdelivr.net/npm/@angular/material@12.2.12/bundles/material-button.umd.js

Thanks.

**Comment by jimaek** [comment]
jsDelivr uses NPM as source, so if some files stopped existing that means they stopped being uploaded to NPM.

**Comment by crisbeto** [comment]
At some point we stopped publishing UMD bundles to npm so that might be why. This was an intentional change that is unlikely to be rolled back.

**Comment by WangJiaoJo** [comment]
Thanks for your reply!
Is it because Angular does not support build the bundles JS files and use 'mjs' instead from Angular 13 so the UMD bundles only available in Angular v12 and below?

Thanks.

**Comment by crisbeto** [comment]
Yes, we stopped supporting UMD bundles because they're non-standard and they're difficult to tree shake.

**Comment by MartinKolarik** [comment]
@WangJiaoJo maybe jsDelivr's esm mode might work for you? E.g., https://cdn.jsdelivr.net/npm/@angular/material@13.3.9/fesm2020/autocomplete/testing.mjs/+esm

**Comment by crisbeto** [comment]
Closing since this isn't something we have much control over.
