### ISSUE TITLE
bug(mat-stepper): MatStepper and MatStep not working through content projection

### ISSUE THREAD

**Issue by joeveiga** [angular/components#26690]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello. I'm not sure if this is by design, but I'd expect this code to work. MatStepper is already using `descendants: true` in it's `@ContentChildren` query so I'd assume this is allowed.

```ts
import 'zone.js/dist/zone';
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';
import { MatStepperModule } from '@angular/material/stepper';

@Component({
  selector: 'my-app-stepper-container',
  standalone: true,
  imports: [MatStepperModule],
  template: `
  <mat-stepper>
    <ng-content></ng-content>
  </mat-stepper>
  `
})
export class StepperContainer {}

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule, MatStepperModule, StepperContainer],
  template: `
    <my-app-stepper-container>
      <mat-step>my step</mat-step>
    </my-app-stepper-container>
  `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App);
```
```
ERROR
Error: R3InjectorError(Standalone[App])[MatStepper -> MatStepper -> MatStepper]:
NullInjectorError: No provider for MatStepper!
```

### Reproduction

Steps to reproduce:
https://stackblitz.com/edit/angular-tnkyk1?devToolsHeight=33&file=src/main.ts

### Expected Behavior

`MatStepper` and `MatStep` work through content projection.

### Actual Behavior

`NullInjectorError` is thrown.

### Environment

- Angular: 15.2.0
- CDK/Material: 15.2.0
- Browser(s): Chrome 110.0.5481.177 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
The stepper uses `ContentChildren` to pick up the steps that have been projected. `ContentChildren` doesn't work if the children have been defined inside the stepper element. This is how it works at the framework level and we don't have an alternative.
