### ISSUE TITLE
bug(mat-option): Not showing ngx translated text until interaction with select

### ISSUE THREAD

**Issue by anckaert1998** [angular/components#26707]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

When a page is loaded where a MaterialSelect is used and the control of that MaterialSelect has a value, it should show the correct option.

Currently it selects the option, but it does not show the text. The text of that option is translated inside the <mat-option> with the use of the translate pipe of @ngx-translate 

### Reproduction

I made the following stackblitz: https://stackblitz.com/edit/angular-qsfxtm

### Expected Behavior

The option correspondig with the initial formcontrol value should be shown

### Actual Behavior

The option is selected, but the text is not visible until you interact with the select

### Environment

Angular CLI: 15.1.2          
Node: 16.18.1                
Package Manager: yarn 1.22.19
OS: win32 x64                

Angular: 15.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
ng-packagr                      15.1.1
rxjs                            7.8.0
typescript                      4.9.4
webpack                         5.75.0

**Comment by crisbeto** [comment]
This looks like an issue with the pipe which we don't have control over.

**Comment by anckaert1998** [comment]
@crisbeto What is the indication that it's something on their side? I can add that when I create an issue on their side

**Comment by aikrez** [comment]
@crisbeto 
Version that works
```
 "@angular/cdk": "15.0.0",
 "@angular/material": "15.0.0",
```

version that broke
```    
"@angular/cdk": "15.0.1",
"@angular/material": "15.0.1",
```

Maybe related to https://github.com/angular/components/commit/f61a213821d37917235ab270d5ccff240d4bd6e8?

**Comment by anckaert1998** [comment]
@crisbeto could you have a look again please?
