### ISSUE TITLE
bug(mdc-form-field): Label css is duplicated multiple times.

### ISSUE THREAD

**Issue by liesahead** [angular/components#26706]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

V14

### Description

Even in the official ([docs](https://material.angular.io/components/radio/overview)) page css is duplicated.

![image](https://user-images.githubusercontent.com/32300784/221834465-7dab004a-e2ee-459f-9c10-86176c6f0e09.png)

![image](https://user-images.githubusercontent.com/32300784/221834687-ad8ced33-3e0d-4986-9df2-aa19f116aed4.png)

### Reproduction

1. Open [demo](https://material.angular.io/components/radio/overview) page;
2. Open dev tools;
3. Check the mat-radio or mat-slide-toggle label css in inspector.

### Expected Behavior

CSS shouldn't be duplicated.

### Actual Behavior

CSS is duplicated.

### Environment

Angular CLI: 15.1.6
Node: 18.14.0
Package Manager: yarn 3.3.0
OS: win32 x64

Angular: 15.1.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1501.6
@angular-devkit/build-angular      15.1.6
@angular-devkit/build-ng-packagr   0.1002.4
@angular-devkit/core               15.1.6
@angular-devkit/schematics         15.1.6
@angular/cli                       15.1.6
@schematics/angular                15.1.6
rxjs                               7.8.0
typescript                         4.9.5

**Comment by wagnermaciel** [comment]
Same as https://github.com/angular/components/issues/26712

**Comment by liesahead** [comment]
So, the upgrade to v15 breaks lots of stuff (which takes more than a week to fix after the automatic migration) and it seems that’s how it should be according to your replies 😄
