### ISSUE TITLE
bug(COMPONENT): After the form control uses the required attribute, the error message cannot be merged with the custom validator attribute

### ISSUE THREAD

**Issue by pipeng119** [angular/components#26711]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

After using the required attribute in the form control, the object collecting error information will automatically be filled with a required attribute with a value of true, or if the custom form validator also returns the required attribute with a value of the other error information. Finally, in html, developers using formControl to get errors for this control can only get {required: true}.

### Reproduction

Steps to reproduce:
```
// html
 <form *ngIf="!!formGroup" [formGroup]="formGroup" novalidate>
    <div>
      <mat-form-field>
        <mat-label>Name</mat-label>
        <input matInput formControlName="name" required autocomplete="off">
        <mat-error *ngIf="formGroup.get('name').errors && formGroup.get('name').touched">
          {{formGroup.get('name').errors | json}}
          <div *ngFor="let err of this.formGroup.get('name').errors | keyvalue">Name {{err.value}}</div>
        </mat-error>
      </mat-form-field>
</form>
```
```
// ts
onNgInit(): void {
this.formGroup = this.fb.group({
name: [
        formValue.name,
        [this.requiredFn()],
      ],
});
}

requiredFn(): ValidatorFn {
    return (control: AbstractControl): { [key: string]: string } | null => {
      let value = control.value;

      // when input filled with only spaces
      if (typeof value === 'string') {
        value = value.trim();
      }

      if (!value && value !== 0) {
        return { required: 'is required' };
      }
      return null;
    };
  }
 
```

### Expected Behavior

I want the error information provided by the custom validator to override the error information provided by the required attribute

### Actual Behavior

The error message for the custom validator cannot override the error message provided by the required attribute

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.9
- Browser(s): Chrome  110.0.5481.100
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Closing since this is likely an issue with the Forms module, not Material. The Material input doesn't do any validation.
