### ISSUE TITLE
bug(mat-checkbox): indeterminate state is not reflected in component classlist anymore.

### ISSUE THREAD

**Issue by liesahead** [angular/components#26713]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

V14

### Description

V14
![image](https://user-images.githubusercontent.com/32300784/222149828-ccfcb6b7-8847-48fe-b5ed-420800943a36.png)

V15
![image](https://user-images.githubusercontent.com/32300784/222149742-8a905787-8d6f-4264-958e-cee8f3160a7d.png)

### Reproduction

Steps to reproduce:
1. Open [docs/demo](https://material.angular.io/components/checkbox/overview);
2. Open devtools;
3. Toggle one of these checkboxes;
![image](https://user-images.githubusercontent.com/32300784/222150041-1e2225fe-4ec0-4586-94d6-34c0e3a947d1.png)
4. See that `mat-mdc-checkbox-indeterminate` is not set.

### Expected Behavior

Like with checked state should be reflected in classlist:

![image](https://user-images.githubusercontent.com/32300784/222150234-2039a873-6ecb-4b52-a0a2-6142fe6da4c1.png)

### Actual Behavior

Indeterminate state reflection is missing from classlist.

### Environment

Angular CLI: 15.1.6
Node: 18.14.0
Package Manager: yarn 3.3.0
OS: win32 x64

Angular: 15.1.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1501.6
@angular-devkit/build-angular      15.1.6
@angular-devkit/build-ng-packagr   0.1002.4
@angular-devkit/core               15.1.6
@angular-devkit/schematics         15.1.6
@angular/cli                       15.1.6
@schematics/angular                15.1.6
rxjs                               7.8.0
typescript                         4.9.5

**Comment by crisbeto** [comment]
This class isn't a public API. Previously we used it for styling, but we don't need it anymore with the MDC implementation.

**Comment by liesahead** [comment]
@crisbeto, could you give a link to public API? Because it's not clear which classes can be used for styling and which are not. In this case `mat-checkbox-checked` is used, but `max-checkbox-indeterminate` is not which is super confusing. Most of the components are almost uncustomizable at all.

**Comment by crisbeto** [comment]
These classes are all implementation details. Since you're the one telling the checkbox if it should be indeterminate, you can also set a custom class on it.
