### ISSUE TITLE
bug(mat-button): `ng-container` element is effecting the rendered DOM structure when used with `mat-icon` in `mat-button` template's innerHTML

### ISSUE THREAD

**Issue by vitale232** [angular/components#26714]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

My understanding of the [`ng-container`](https://angular.io/api/core/ng-container) element is that it can be used with structural directive's in a component's template without affecting the underlying DOM structure. In the MDC version (at version 15) of Angular Material, using `ng-container` within a button has an effect on the rendered DOM.

These expectations are based off of the Angular documentation, as well as my experience with previous versions of Angular Material. This issue was noticed while migrating an existing app to MDC.

### Reproduction

Steps to reproduce:
1. Load this stackblitz in a Chromium based browser: https://stackblitz.com/edit/angular-1fvgpn?file=src%2Fapp%2Fbutton-overview-example.html,src%2Fapp%2Fbutton-overview-example.ts
2. Observe the difference between the disabled button and the enabled button. 

### Expected Behavior

I expect the disabled button (no `ng-container`) and the enabled button (with `ng-container`) to have the same visual appearance and the same DOM structure, since `ng-container` was used to host the `NgIf` directive.

### Actual Behavior

Using `NgIf` on an `ng-container` that contains a `MatIcon` within a `MatButton` is effecting the rendered DOM structure. The disabled button's innerHTML has the `mat-icon` rendered as a direct child of the `button`. The enabled button renders the `mat-icon` within the `span.mdc-button__label` element, as a "grandchild" of the `button`.

This difference in DOM structure leads to an inconsistent visual appearance that is challenging for library consumers to style away. I believe this breaks the expectations of the `NgContainer` API.

### Environment

- Angular: ~15.2
- CDK/Material: ~15.2
- Browser(s): Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

**Comment by crisbeto** [comment]
It's because `ng-container` is still counted as an element when content projection happens. It's just how it works at the framework level. You can work around it by putting the `matButtonIcon` attribute on the `ng-container`.

**Comment by vitale232** [comment]
Thanks for the response. I've updated the Stackblitz with your useful workaround, incase anyone stumbles onto this.
