### ISSUE TITLE
bug(mat-button): cleanup unused selector [matButtonIcon]

### ISSUE THREAD

**Issue by klyakh** [angular/components#26726]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-button's template contains selector `[matButtonIcon]`, which I believe is not used anymore.

https://github.com/angular/components/blob/main/src/material/button/button.html

```html
...
<ng-content select=".material-icons:not([iconPositionEnd]), mat-icon:not([iconPositionEnd]), [matButtonIcon]:not([iconPositionEnd])">
</ng-content>
...
<ng-content select=".material-icons[iconPositionEnd], mat-icon[iconPositionEnd], [matButtonIcon][iconPositionEnd]">
</ng-content>
...
```

I've searched trough the repository and that is the only file that contains "matButtonIcon".

### Reproduction

Not applicable.

### Expected Behavior

ng-content's select property doesn't contain outdated selectors.

### Actual Behavior

ng-content's select property does contain outdated selector.

### Environment

Angular CLI: 15.1.2
Node: 16.13.0
Package Manager: yarn 1.22.5
OS: win32 x64

**Comment by crisbeto** [comment]
The selector is used if you want to project an icon into the correct place in the button and you aren't using `mat-icon`.

**Comment by klyakh** [comment]
Oh, so if I want to use some not `.material-icons` icon and I'm not using `mat-icon`, then I need to add attribute `matButtonIcon` to my custom icon element. Is this how it is supposed to be used?

**Comment by crisbeto** [comment]
Exactly
