### ISSUE TITLE
feat(mat-grid-list): Compatibility with MDC Web

### ISSUE THREAD

**Issue by haskelcurry** [angular/components#26720]
### Feature Description

In the latest versions of Angualr Material most of the components were migrated on MDC web and now acting as a wrappers over the Web Components provided by Material, to improve the compatibility.
Hovewer, the Grid List component doesn't seem to be based neigher on [MDC](https://m2.material.io/develop/web/supporting/layout-grid) nor on [Material specs](https://m2.material.io/design/layout/responsive-layout-grid.html#breakpoints) even.  

Could you pleaes clarify the plans on this?

**Comment by crisbeto** [comment]
We aren't planning to support the grid list through MDC since the functionality can be achieved with less code using CSS grid. We initially implemented the grid list because we had to support IE.
