### ISSUE TITLE
bug(material/paginator): checkmark added for selected page size hides label text

### ISSUE THREAD

**Issue by JaxonWright** [angular/components#26734]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v15.1.0

### Description

#25962 added a checkmark/checkbox to the end of the selected items in a single-select input component. A side effect from this is that now selected page sizes that are larger than 9 show an ellipsis instead of the actual label. This is evident even on the Angular Material documentation for the `<mat-paginator>`.

### Reproduction

Steps to reproduce:
1. Select a page size larger than 9 on a paginator
2. Open the select input again and observe it now appears as "...✔️"
https://material.angular.io/components/paginator/examples

### Expected Behavior

I would probably expect there to be no checkmark on this input at all due to how small of an input it is now that the MDC-based select input does not allow the dropdown to be wider than the input itself by default.

### Actual Behavior

There is a checkbox at the end of the selected option and it causes an ellipsis to appear in place of the actual label.

### Environment

- Angular: 15.2.0
- CDK/Material: 15.2.0
- Browser(s): Probably any, but I use Chrome 110.0.5481.178
- Operating System (e.g. Windows, macOS, Ubuntu): Probably any, but I use Windows 11

**Comment by JaxonWright** [comment]
@zarend I see you updated the default behavior of the paginator in [#26746](https://github.com/angular/components/pull/26746) which may warrant this issue being closed. Perhaps you are waiting for your ultimate fix that you mention in the PR, though.

**Comment by crisbeto** [comment]
Fixed in https://github.com/angular/components/pull/26746.
