### ISSUE TITLE
bug(mat-datepicker): the dateChange event not triggered on re-entering (keyboard) currently selected date

### ISSUE THREAD

**Issue by RafalBesztak** [angular/components#26748]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

matDatepicker do not trigger event (dateChange) on re-entering (keyboard) in the input the same date (currently selected date)

### Reproduction

Stackblitz: https://stackblitz.com/angular/odrmqdenkrv?file=app%2Fdatepicker-events-example.html

Steps to reproduce:
1.  select in datepicker any date, ie 3/8/2023
![image](https://user-images.githubusercontent.com/11212675/223669671-d280e915-f914-47cb-ab9a-68193898ee21.png)

2. clear the input by selecting text and BACKSPACE
![image](https://user-images.githubusercontent.com/11212675/223669841-97efbd33-1748-47b7-80aa-2742610c093a.png)

3. Re-enter using keyboard the same date '3/8/2023'
![image](https://user-images.githubusercontent.com/11212675/223669671-d280e915-f914-47cb-ab9a-68193898ee21.png)

4. (dateChange) is not triggered, (dateInput) is triggered correctly
![image](https://user-images.githubusercontent.com/11212675/223671430-bbd32654-f960-4b9b-b267-af63121e0c88.png)

### Expected Behavior

event (dateChange) is triggered when i erase selected date and re-enter the date

### Actual Behavior

event (dateChange) is NOT triggered when i erase selected date and re-enter the date

### Environment

- Angular: 6.x.x - 15.x.x
- CDK/Material: 7.x.x - 15.x.x
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
This sounds like it's working as expected. The date didn't change so the `dateChange` event doesn't fire.
