### ISSUE TITLE
bug(Mat Form Build): Multiple components match node with tagname mat-form-field: MatFormField and MatFormField

### ISSUE THREAD

**Issue by artikhurana** [angular/components#26741]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have created a standalone component that has 4 mat form fields. While running test cases using jest it gave me error 
Multiple components match node with tag name mat-form-field: MatFormField and MatFormField

### Reproduction

Steps to reproduce:
1. Create standalone component
2. Create 4 mat form fields
3. Run test cases

### Expected Behavior

Test case should run

### Actual Behavior

Test cases failing

### Environment

- Angular: 14.0.0
- CDK/Material:14.0.0/14.0.3
- Browser(s): -Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
You likely have both the legacy and MDC-based `MatFormFieldModule` imported somewhere.
