### ISSUE TITLE
bug(mat-menu): mat menu density is not applied

### ISSUE THREAD

**Issue by electrofLy** [angular/components#26759]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Lowering the density of mat menu component does not change the density of a mat menu item.

### Reproduction

https://stackblitz.com/edit/angular-t3wxbs?file=src%2Ftheme.scss

Steps to reproduce:
1. Open `theme.scss` and set density to -2
2. Open a mat menu item and check it's height

### Expected Behavior

Height with density of 0 - 48px
Height with density of -2 - 36px

### Actual Behavior

Height with density of 0 - 48px
Height with density of -2 - 48px

### Environment

- Angular: 15.2.2
- CDK/Material: 15.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is discussed in https://github.com/angular/components/pull/21621. According to the spec, density isn't supposed to apply to overlays.
