### ISSUE TITLE
Schematics - Need to Provide Admin Template and Web App Template #34558

### ISSUE THREAD

**Issue by prabhakarand7** [angular/components#26753]
### Feature Description

As of now we have Schematics like dashboard, left menu, tables like that but nowadays developer expect to get full UI like admin template, basic web page templates.

We can provide more templates as developer wants. I know it's little bit complicated but we need to work on this. If we provide this feature many developers and entrepreneur like our technology, more company they will use our technology

This feature already reported, please find the below link for more details 
https://github.com/angular/angular/issues/34558 

### Use Case

All companies building the templates or buying templates for their business and applying the templates in our Angular technology. Instead of building from scratch or buying from third party we will provide the list of templated while creating our angular project.

**Comment by amysorto** [comment]
I'm going to close this bug since it's unlikely this will be done in the near future. Although I do think it's a cool idea worth exploring eventually!
