### ISSUE TITLE
bug(mat-form-field): Multi matIconSuffix stacking without min-width

### ISSUE THREAD

**Issue by JoeMellon** [angular/components#26758]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using two buttons with the `matIconButtonSuffix` directive the buttons stack unless the form-field has a set min-width of 300px - anything less stacks the button and displays them incorrectly.

**290px width on form-field - stacks buttons incorrectly**
![image](https://user-images.githubusercontent.com/20834865/223996992-8256402a-dd72-4cd2-9089-ebfc896c2e81.png)

**300px width on form-field - displays buttons correctly inline**
![image](https://user-images.githubusercontent.com/20834865/223997206-825d594d-d816-41ca-b209-04461e809f4e.png)

### Reproduction

Steps to reproduce:

[Stackblitz example](https://stackblitz.com/edit/angular-7tjcjs?file=src%2Fapp%2Fform-field-prefix-suffix-example.html)

### Expected Behavior

Buttons to display inline with no minimum 300px width on the form-field.

### Actual Behavior

Buttons stacking when width of form-field is less than 300px.

### Environment

- Angular: 15.2.2
- CDK/Material: 15.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This ended up breaking a lot of internal apps. I'm closing the issue, because it's my understanding that we technically don't allow more than one suffix anyway. You can fix it in your app by adding this to your global styles:

```
.mat-mdc-form-field-icon-suffix {
  display: inline-flex;
}
```
