### ISSUE TITLE
bug(Card & Table): Table breaks out of card when it gets to wide

### ISSUE THREAD

**Issue by Warwizza** [angular/components#26767]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a table cell gets a value which it cannot wrap (without breaking words) and the page gets to small the tabel will break out of the boundaries of the card containing it. See screenshot
![image](https://user-images.githubusercontent.com/40668465/224361174-85efb961-d798-4617-ada4-dbb75dc99ffb.png)

### Reproduction

Steps to reproduce:
1. Open this [StackBlitz](https://stackblitz.com/edit/angular-nwbq8b?file=src%2Fapp%2Ftable-basic-example.html,src%2Fapp%2Ftable-basic-example.ts)
2. Resize the page width to see the table break out of the card.

### Expected Behavior

I expect that the card grows with contents it cannot contain.

### Actual Behavior

The table breaks out of the card

### Environment

Angular CLI: 15.2.1
Node: 16.13.1
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 15.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5

**Comment by mmalerba** [comment]
This is the standard behavior of the HTML `<table>` element. Setting `table-layout: fixed` might give you the behavior you're looking for: https://stackblitz.com/edit/angular-nwbq8b-efd5dh?file=src%2Fapp%2Ftable-basic-example.html,src%2Fapp%2Ftable-basic-example.css, alternatively you could just divs or change the `display` property on the table elements
