### ISSUE TITLE
bug(mat-autocomplete): Previous-selected option is still selected even though the value is cleared

### ISSUE THREAD

**Issue by lhmcn** [angular/components#26761]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

When an option is selected and then the value is cleared, the option in the dropdown menu is still marked as selected. This is not the same as V14.

### Reproduction

Steps to reproduce:
1. Navigate to the first official example (Highlight the first autocomplete option)
2. Select "Three"
3. Clear the value (Three) by pressing backspace

### Expected Behavior

No option is selected, as it was in V14 (see picture below)
![image](https://user-images.githubusercontent.com/13793092/224109768-7421aa50-1c00-4429-9039-349f9369d4ec.png)

### Actual Behavior

The option "Three" is still selected in the dropdown menu (see picture below)
![image](https://user-images.githubusercontent.com/13793092/224109428-72ad271d-0fe2-4e8b-a387-81dd43614bdd.png)

### Environment

Official demo (V15.2.2)
https://material.angular.io/components/autocomplete/examples

**Comment by iislucas** [comment]
Verified this is still an issue in angular 16.0.1 also.

**Comment by ronniebarker** [comment]
Also - any set of the value does not alter the selection in the list
![image](https://github.com/angular/components/assets/129157/065a3970-b1dc-4677-800b-cb97cc786e48)
