### ISSUE TITLE
Material Stepper Component for Mobile (and not only that)

### ISSUE THREAD

**Issue by LuisOfCourse** [angular/components#26775]
### Feature Description

Hi everyone,

I want to ask a new feature to @angular/material package.

This feature involves steppers and changes the way headers are displayed. The default way of a @angular/material stepper is this one.
![image](https://m1.material.io/assets/0B7WCemMG6e0VOFVjMHV2TWdOMnM/components-acux-stepper-linear.png)

This is really nice for big enough screen to display. But when we go a little smaller, like on a phone screen, we encounter this problem: 
![image](https://user-images.githubusercontent.com/99544966/224537972-ae5b7d46-3500-4760-a064-375633d41aa3.png)

The solutions you can use are more like a workaround and less of a solution per se.
One of them is to change the display mode of the stepper from horizontal to vertical.
Another one is (a limited solution) to move the text of each item header to the bottom, but this doesn't work if you have slightly longer text or >4 steps.

The solution that i propose (that i found searching around) is this one:
![good_bad-form_steppers](https://user-images.githubusercontent.com/99544966/224537674-f4a3c61d-d348-459e-8594-f4c7f1a89667.png)
Credit: https://uxmovement.com/wp-content/uploads/2018/12/good_bad-form_steppers.png (UXMOVEMENT)
By borrowing some logics from the spinner and displaying only the current step header you are set up!

If this idea is a good one, some points needs to be discussed on how to implement it in the current stepper.

### Use Case

On mobile it can be really useful to have this feature from a UX/UI standpoint. 
If you have at least 4 steps you will see that the header will be crowded of "step header item" and text will be cut. 
A possible solution for now (already offered by the package) is to move the Stepper Material mode from horizontal to vertical.

I think that this solution is still not a good one, It's a workaround.

**Comment by amysorto** [comment]
Thanks for looking at some solutions. As mentioned, the [recommended workaround for small screens](https://material.angular.io/components/stepper/overview#accessibility) is to use a vertical stepper or a responsive stepper. 

In terms of changing stepper to look visually different, that would require UX input to figure out a better alternative. For now, I'll close this bug since we likely won't be able to do that soon.
