### ISSUE TITLE
bug(mat-radio-button): mat-radio-inner-circle (selected) mat-radio-button not correctly centred in mat-dialog

### ISSUE THREAD

**Issue by provoke-md** [angular/components#26784]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a mat-radio-button is in a scrollable/overflown mat-dialog the mat-radio-inner-circle (selected) mat-radio-button loses centring at certain resolutions/scroll heights.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/127812210/224882385-6e0451b6-aeb3-4df4-8184-689f376fb6eb.png)

https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-yamfte?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdialog-overview-example-dialog.html,package.json

### Reproduction

Steps to reproduce:
1. Open StackBlitz in Chrome or Edge.
2. Open developer tools and 'device view'.
3. Click 'Open the dialog' button
4. Select a radio button
5. Adjust resolution/screen height and width.

### Expected Behavior

mat-radio-inner-circle centred in the mat-radio-button when adjusting the height/dimensions. 

### Actual Behavior

mat-radio-inner-circle moves to off-centre in the mat-radio-button

### Environment

- Angular: 13.3
- CDK/Material: 13.3
- Browser(s): Chrome/Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We don't backport fixes to Angular v13 anymore. Please try it with Angular 15 or newer.
