### ISSUE TITLE
bug(Button, Input): Native events are bubbling up and not suppressed

### ISSUE THREAD

**Issue by nilesh0107** [angular/components#26788]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have seen most of component native events are suppressed and reemitted form material component, but in button and Input component still I am seeing event's are bubbled up.

> ### **Question: Why angular material is suppressing and reemitting native event's from material component?**

### Reproduction

Steps to reproduce:
1. add click event  listener on mat-button.
2. check eventListener is triggering

Another Scenario:
1. add change event listener on mat-checkbox.
2. check eventListener is not triggering.

### Expected Behavior

If angular material behavior is suppress and remit then same should works with button and input also.

### Actual Behavior

button and Input component are not suppressing events and event's are bubbled up

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
We only do this if a native event has the same name as one of the directive's outputs.

**Comment by nilesh0107** [comment]
> We only do this if a native event has the same name as one of the directive's outputs.

@crisbeto - still I have question,
why native event behavior is suppressed when event has same name, any specific reason behind that?

**Comment by crisbeto** [comment]
The reason is that we wanted to emit the custom `MatCheckboxChange` event on `change`. If we didn't prevent bubbling on the native event, users would have their callback fire twice. The checkbox emits a custom event, because it allows us to attach custom data like the checkbox instance that the event is coming from.
