### ISSUE TITLE
bug(FormField): appearance "outline" breaks UI

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [angular/components#26787]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

If the we use the example from the https://material.angular.io/components/form-field/overview, with appearance outline. The width of the input field is set to minimum

### Reproduction

Steps to reproduce:
1. https://material.angular.io/components/form-field/overview
2. Select and use the appearance outline example

### Expected Behavior

![Screenshot (4)](https://user-images.githubusercontent.com/46624268/224986877-2f98bffd-9d27-4695-bc57-7f26b88f3d50.png)

### Actual Behavior

![Screenshot (2)](https://user-images.githubusercontent.com/46624268/224986574-ce99e6ea-75b6-408e-8dea-c085f057b575.png)

### Environment

- Angular: 15.2.2
- CDK/Material: 15.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by wagnermaciel** [comment]
Hi @muhammad-usman-anwar , I was unable to reproduce the behavior shown in the screenshot. Could you provide a stackblitz with a more detailed description of how to reproduce this bug?

Here's a screenshot from when I tried interacting with the appearance outline example

<img width="1146" alt="Screenshot 2023-03-17 at 4 43 00 PM" src="https://user-images.githubusercontent.com/25158423/226038415-a262b032-5956-41dc-a1fc-142cfbe41303.png">

**Comment by urugator** [comment]
In case you're using Tailwind:
```
@layer base {
  *,
  ::before,
  ::after {
    // https://github.com/tailwindlabs/tailwindcss/discussions/9993
    // Only reason why Tailwind sets it to "solid" is so you don't have to specify border style together with "border[-x]" class.
    // That's something we can live without.
    border-style: none;
  }
}
```
You will have to manually add `border-[style]` class everywhere.

**Comment by muhammad-usman-anwar** [comment]
its because of tailwind

**Comment by muhammad-usman-anwar** [comment]
its because of tailwind

**Comment by muhammad-usman-anwar** [comment]
its because of tailwind
