### ISSUE TITLE
Compatibility issues seen in edge browser

### ISSUE THREAD

**Issue by kunal-epsc** [angular/components#26785]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Seeing accessibility and compatibitlity issues when opening the app in edge browser
![Compatibility](https://user-images.githubusercontent.com/99380988/224908668-0d229980-f413-46cc-a93e-0efb66ed7758.PNG)
![Accessibility-1](https://user-images.githubusercontent.com/99380988/224908689-83183f78-0f8c-423b-b1d2-6e4b14fdbf56.PNG)
![Accessibility-2](https://user-images.githubusercontent.com/99380988/224908694-fb6cfa89-93b7-4783-9aa5-03ea508a6742.PNG)
![Accessibility-3](https://user-images.githubusercontent.com/99380988/224908697-bddb980f-8cb7-4682-8f76-5a2b6bb81d65.PNG)

### Reproduction

Steps to reproduce:
1. Create an angular app 
2. Implement various componets like mat menu, icon button etc. An exaustive list can be seen in the attached screenshots above 

### Expected Behavior

No issues should be seen when accessing the application cross browser

### Actual Behavior

Issues are no seen in chrome browser, but are seen in edge browser

### Environment

- Angular: 14.2
- CDK/Material: 14.2
- Browser(s): 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69'
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 (not tested on any other OS)

**Comment by crisbeto** [comment]
Closing since the warnings don't affect users and the ones about buttons not having titles are up to the button consumer to specify.
