### ISSUE TITLE
docs-bug(MatSlider): displayWith handler losing implementation context

### ISSUE THREAD

**Issue by 3phase** [angular/components#26789]
### Documentation Feedback

I was wondering whether there's a specific reason for implementing the `displayWith` property in the [Mat Slider](https://github.com/angular/components/blob/main/src/material/slider/slider.ts#L357) as an arrow function.
As a side effect, the arrow function makes the handler lose the this-context of the component, where it's implemented. 
Thus, the implementation would always refer to the `MatSlider`-component properties instead of the component-specific ones.

If there's a reason for that implementation, I guess it's going to be helpful to be mentioned in the documentation, because so far I wasn't able to find anything relevant.

### Affected documentation page

https://material.angular.io/components/slider/api

**Comment by crisbeto** [comment]
`displayWith` has to be an arrow function, because there's no way for the slider to get a reference to the component class it is rendered inside of.
