### ISSUE TITLE
bug(MatDialog): Shadow covered and not visible

### ISSUE THREAD

**Issue by fbuscaroli2** [angular/components#26814]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The MatDialog components shadow is covered and not visibile.

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

![image](https://user-images.githubusercontent.com/128463836/226559993-175c450b-83a0-4bd8-ae0d-13b54fd4b953.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/128463836/226560119-8599c94c-c9e6-40fe-8be7-e6cda6ede657.png)

### Environment

- Angular: 15.2.3
- CDK/Material: 15.2.3
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is a likely an issue with your app. The dialog on the docs site has the correct shadow https://material.angular.io/components/dialog/overview.

**Comment by fbuscaroli2** [comment]
@crisbeto, yes. my fault!
