### ISSUE TITLE
bug(mat-tabs): Example of mat-tabs deletion is showing wrong index

### ISSUE THREAD

**Issue by parijat93sharma** [angular/components#26816]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If we have three tabs and we navigate to the second tab or the 1st index and delete the first tab or the 0th index the selectedIndex doesnt update .

### Reproduction

Steps to reproduce:
1. Go to angular material website https://material.angular.io/components/tabs/examples, Under header 'Tab group with dynamically changing tabs'. Open Stackblitz.
2. Remove the delete button html code from inside the mat-tab and place it outside the mat tab. Instead of passing index of mat-tab to remove function just pass 0 like (click)="removeTab(0)"
3. Navigate to Tab1 or index =1 for mat tab and hit the delete button. The first mat tab gets deleted but the selectedIndex.value is still 1 in the screen. 
4. It only stops working when the currentIndex = 1 and we delete the 0th index
Demo stackBlitz: https://components-issue-qwmzq3.stackblitz.io

### Expected Behavior

The selectedIndex.value should show correct values

### Actual Behavior

The selectedIndex.value shows incorrect value 

### Environment

- Angular:15.0.0
- CDK/Material:15.2.3
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by EnverUsta** [comment]
is this ticket still waits for the fix @parijat93sharma?

**Comment by abonvalle** [comment]
I couldn't reproduce it, this may have been fixed by #28256

**Comment by parijat93sharma** [comment]
Yes i am closing this issue. It has been fixed. Thanks
