### ISSUE TITLE
bug(FormField): Cannot change the colour of the underline in a mat form field

### ISSUE THREAD

**Issue by MadamMcNugget** [angular/components#26812]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I used to be able to change the color of the underline in a mat form field by targeting the css properties .mat-form-field-underline and .mat-form-field-ripple.  This does not work anymore.

I've tried renaming the property to .mat-mdc-form-field-underline, .mat-mdc-form-field-appearance-fill-underline, .mat-mdc-form-field-line-ripple, but none of them seem to work. 

Is there another name for this property or has this function been removed?

Thanks!

### Reproduction

Steps to reproduce:
stackblitz: https://stackblitz.com/edit/components-issue-tjdrxr?file=src%2Fapp%2Fexample-component.html,src%2Fstyles.scss,src%2Fapp%2Fexample-component.css,src%2Findex.html
1. create an input form field
2. change color of the underline in styles.css file

### Expected Behavior

This is before update to version 15
![image](https://user-images.githubusercontent.com/8701961/226475157-2edcf5ff-8ea7-44b8-b776-784bbad184c4.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/8701961/226474950-47c0fd0e-8493-4f3d-92c5-dfeef1d54224.png)

### Environment

- Angular: 15.2.3
- CDK/Material: 15.2.2
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by liesahead** [comment]
I think the answer is here

https://material.angular.io/guide/theming#style-customization-outside-the-theming-system

**Comment by amysorto** [comment]
Overriding styles is not encouraged as mentioned in the link above. The only supported color changes are based on your primary, accent, or warn colors defined in your theme, the docs has an example for how to do this: https://material.angular.io/components/form-field/examples#form-field-theming. 

For a different color you would need to override, and for this particular underline this should work.
```
.mdc-text-field--filled .mdc-line-ripple::after {
  border-bottom-color: springgreen;
}
```
