### ISSUE TITLE
CSS: Need utility classes in Angular Material.

### ISSUE THREAD

**Issue by dhondiramjawade** [angular/components#26837]
### Feature Description

As front end architect I want to be minimalistic and optimistic with font-end libraries and framework. Angular is a good framework and it has many capability than any other front-end framework ever. 

Angular material has improved developers productivity and also project timeline as it has very rich component library with rich functionality. 

But the problem is every front end developer need some CSS utility classes with good configuration and typography for their  application. Till now some were using [angualr/flex-layout](https://github.com/angular/flex-layout) and now Angular team is no longer support that library. 

[Tailwindcss](https://github.com/tailwindlabs/tailwindcss) is a CSS utility based framework but it is not compatible with Angular material.
But we do not want to depend on another library for CSS utility.

**Can Angular team add utility classes for flexbox, gird and other CSS utility in Angular Material itself, So that angular community won't not depend on any other CSS library or framework.**

### Use Case

**Angular Material - Component framework.**

Alternatives are
1. [bootstrap](https://github.com/twbs/bootstrap)   - CSS utility + component framework.
2. [tailwindcss](https://github.com/tailwindlabs/tailwindcss)  - CSS utility + component framework.

**Comment by rubenheymans** [comment]
I'm using a combination of angular material + tailwind + flowbite and it works well. Too bad I have to (almost) step away from angular material because it's an overcomplicated mess with a lot of missing features. Some of the components are really good like datepicker or dialog.
