### ISSUE TITLE
feat(MatListItem): Should have a color directive

### ISSUE THREAD

**Issue by ChrTall** [angular/components#26836]
### Feature Description

It would nice if there was a directive to set the color of mat-list-items and icons.
Overriding the internal CSS of MatListItem is kind of hard and might fail in the future.

I like the padding and would rather not create the whole Mat Line Layout without the existing directives. 

### Use Case

If you want to display a list of error messages you might want to style them to your warn palette color.
MatListItemIcon with an Delete Icon button might also be styled to your warn palette color.

**Comment by ChrTall** [comment]
partially relates to #26804

**Comment by crisbeto** [comment]
This should be covered by our upcoming changes to the theming API.
