### ISSUE TITLE
feat(mat-checkbox): Tristate (false --> true --> indeterminate) option for checkbox

### ISSUE THREAD

**Issue by angelaki** [angular/components#26841]
### Feature Description

I once built a directive (some kind of subclassing) for the mat-checkbox that isn't working anymore since MDC. Now I'm thinking about making it a PR rather than just building my own directive again.

Would this feature be interesting? Was this already discussed? Or is it rather a rare use-case (or not liked from a UX perspective?) and I should stay with my (reworked) directive?

### Use Case

In some cases I want a checkbox to represent three states (e.g. yes / no / no answer). Right now the checkbox control does not allow this by default.

Gues this could be achieved by a new `clickAction`?

**Comment by mmalerba** [comment]
This seems like probably not a common enough use case for it to be baked into the library, but could instead be build on top using `clickAction` or even the `mat-pseudo-checkbox` which would probably allow for more control over the behavior. I think the accessibility behavior for this feature is unclear and would probably make implementing as part of the library tricky, as accessibility is an important concern for our library.

**Comment by angelaki** [comment]
Ok, thank you. Building a neat directive; if anyone ever finds this and is interessted: feel free to ask.

By the way: @mmalerba, is there a way to set a `clickAction` for a single Checkbox? _Providing_ it will set this behavior for all checkboxes from now on.

**Comment by amakhrov** [comment]
I'm currently struggling with implementing a "controlled" (input-driven) tri-state checkbox with mat-checkbox. The underlying `input` state gets out of sync (similar to https://github.com/angular/components/issues/22149, which somehow resurrected after an MDC migration).

I feel that being able to set `clickAction` on an individual checkbox would solve the issue for me

**Comment by angelaki** [comment]
I actually don't get the idea of being able to set the `clickAction` only via DI. Guess there should be a overriding property, too. Never the less, here is my directive. Sure pretty hacky, but does it's job (Angular 16) quite well:

```
import { Directive, Input, OnDestroy, isDevMode } from '@angular/core';
import { MatCheckbox } from '@angular/material/checkbox';
import { NotImplementedError } from '@cerebrum/error/errors';

@Directive({ selector: '[cTriState]' })
export class TriStateCheckboxDirective implements OnDestroy {
    constructor(
        private _matCheckbox: MatCheckbox
    ) {
        this._emitChangeEvent = _matCheckbox[EMITCHANGEEVENT]?.bind(_matCheckbox);

        if (isDevMode()) {
            if (!this._emitChangeEvent) { throw new NotImplementedError(`No \`${EMITCHANGEEVENT}\`-method found; MatCheckbox must have changed`); }
            if (!(CHECKED in _matCheckbox)) { throw new NotImplementedError(`No \`${CHECKED}\`-property found; MatCheckbox must have changed`); }
        }

        this._nativeElement = _matCheckbox._elementRef.nativeElement;
        this._nativeElement.addEventListener('click', this._handleClickBound, { capture: true });
    }

    @Input() cTriState?: boolean;
    @Input() cTriStateIndeterminateValue = null;

    private _handleClick(event: MouseEvent): void {
        if (
            //Direktive deaktiviert
            this.cTriState === false ||

            //Checkbox gerade `checked` oder `indeterminate`
            this._matCheckbox.checked ||
            this._matCheckbox.indeterminate
        ) { return; }

        this._matCheckbox.indeterminate = true;
        this._matCheckbox[CHECKED] = this.cTriStateIndeterminateValue;

        this._emitChangeEvent();
        event.preventDefault(); event.stopPropagation();
    }

    private _handleClickBound = this._handleClick.bind(this);
    private _nativeElement: HTMLElement;
    private _emitChangeEvent: () => void;

    ngOnDestroy(): void {
        this._nativeElement?.removeEventListener('click', this._handleClickBound, { capture: true });
    }
}

const EMITCHANGEEVENT = '_emitChangeEvent';
const CHECKED = '_checked';
```

But it sure breaks the type-safety a bit: the checkbox's checked value is actually a boolean accepting only true / false. My directive sets an individual value.
