### ISSUE TITLE
Angular 15 MDC Outline input not showing required tags

### ISSUE THREAD

**Issue by awdorrin** [angular/components#26848]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

With `appearance: 'fill' ` asterisks are displayed properly, but with `appearance; 'outline'` they are not.
```
        <mat-form-field class="date-width"
                        matTooltip="Based on RTG_Final task">
          <mat-label>Original RTG Date:</mat-label>
          <input type="date" matInput formControlName="origRTGDate" readonly
                 [required]="form.get('subcInfo.origRTGDate')?.errors?.required" />
        </mat-form-field>
```

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

See Asterisk for required fields for all form-field appearance types

### Actual Behavior

Not seeing required asterisk for outline mat-form-field types

### Environment

- Angular: 15.2.4
- CDK/Material: 15.2.4
- Browser(s): Chrome
- Operating System Windows

**Comment by crisbeto** [comment]
This should've been resolved by https://github.com/angular/components/pull/26028.
