### ISSUE TITLE
MatDialog viewContainerRef invalid

### ISSUE THREAD

**Issue by alvin0216** [angular/components#26863]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

version 14.2.7
code here:

```ts
import { Component, Inject, ViewChild, ViewContainerRef, } from '@angular/core';
import { Dialog, DIALOG_DATA } from '@angular/cdk/dialog';
import { MatDialog, MatDialogConfig } from '@angular/material/dialog';
export interface DialogData {
  animal: 'panda' | 'unicorn' | 'lion';
}

@Component({
  selector: 'cdk-dialog-data-example-dialog',
  templateUrl: 'cdk-dialog-data-example-dialog.html',
  styleUrls: ['./cdk-dialog-data-example-dialog.css'],
})
export class CdkDialogDataExampleDialog {
  constructor(@Inject(DIALOG_DATA) public data: DialogData) {}
}

/**
 * @title Injecting data when opening a dialog
 */
@Component({
  selector: 'cdk-dialog-data-example',
  templateUrl: 'cdk-dialog-data-example.html',
})
export class CdkDialogDataExample {
  @ViewChild('container', { read: ViewContainerRef }) container: ViewContainerRef;

  constructor(public dialog: MatDialog, private viewContainerRef: ViewContainerRef) {}

  openDialog() {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.viewContainerRef = this.container;
    const dialogRef = this.dialog.open(CdkDialogDataExampleDialog, dialogConfig);
  }
}
```

cdk-dialog-data-example.html

```html
<button (click)="openDialog()">Open dialog</button>
<div #container>xxx</div>
```

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

I want the dialog to mount to the specified dom instead of overlay.

### Actual Behavior

MatDialog viewContainerRef invalid

### Environment

- Angular: ~14.0.0
- CDK/Material: 14.2.7
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): window11

**Comment by alvin0216** [comment]
I don't know how to solve this problem,  the api in the documentation is invalid

**Comment by alvin0216** [comment]
I want to override dialog.open method, there is a DOM hanging on overlay, I called **TopDom**，

Every time the dialog.open method is called, I want the component to be inserted before the TopDom, what should I do?

**Comment by crisbeto** [comment]
The overlay container is used to ensure that the dialog stacks relative to other overlays and that it isn't clipped by `overlay: hidden`. As such we don't support setting the rendering location in the DOM. The `ViewContainerRef` only determines where the dialog is rendered in the DI tree.
