### ISSUE TITLE
Menu- Unable to navigate using arrow keys

### ISSUE THREAD

**Issue by Suresh918** [angular/components#26875]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When we have input text area in mat menu, the up and down arrow keys are not working inside text area to navigate.

### Reproduction

Steps to reproduce:

Please check the code in the stackblitz. We have text area inside menu. After entering some in the text area in multiple lines, if you use arrow up and down keys the cursor has to be moved accordingly. But it is not happening.
[](https://stackblitz.com/edit/angular-s8knmv?file=src/app/menu-icons-example.ts)

### Expected Behavior

The arrow keys should work inside the text area for navigation.

### Actual Behavior

The arrow keys are not working inside the text area for navigation.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing the issue since we don't support putting a `textarea` inside a menu, because it's not a valid accessibility pattern.
