### ISSUE TITLE
bug(mat-form-field): Password visibility shows two buttons on first load

### ISSUE THREAD

**Issue by wtygibbs** [angular/components#26871]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

On first load, when typing into the password field an alternate visibility button is displayed. The issue goes away after first load.

Edit, working accessible StackBlitz
https://stackblitz.com/edit/angular-rrcgpa?file=src/app/form-field-prefix-suffix-example.ts

### Reproduction

Steps to reproduce:
1. Refresh the stack blitz
2. Begin typing in the password field

### Expected Behavior

There should only be one visibility button displayed at any given time.

The icon corresponds with a boolean. There should only be 2 states.

### Actual Behavior

A new button appears to the left of the one that is supposed to be there. It is fully functional with toggling password visibility.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.2.5
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by wagnermaciel** [comment]
Hi, is the stackblitz public? I can't access it

**Comment by wtygibbs** [comment]
Hi @wagnermaciel, my apologies for not getting back to this sooner. I assume the Stackblitz should be accessible because its the example from the official docs: [Form-field prefix-suffix example](https://material.angular.io/components/form-field/overview#prefix--suffix).

However, now that I have re-visited the example it appears to be functioning properly again.

**Comment by wagnermaciel** [comment]
Oh, nice. Always nice when things work out lol. Probably got fixed in one of the recent patches 👍🏽
