### ISSUE TITLE
bug(google-maps): Cannot control size by css

### ISSUE THREAD

**Issue by obzocker** [angular/components#26898]
### Description

It is currently not possible to control the height and width of the google-map [component ](https://github.com/angular/components/blob/2f9a59a24c0464cbed7f54cbeb5cba73e6007715/src/google-maps/google-map/google-map.ts)through css despite the code comment saying so: 
`  /** Height of the map. Set this to null if you'd like to control the height through CSS. */
  @Input() height: string | number | null = DEFAULT_HEIGHT;`

I suspect this is bug stems from this line: 
`      styles.width = this.width === null ? '' : coerceCssPixelValue(this.width) || DEFAULT_WIDTH;`

The height/width is set within the component to ' ' and overwrites the .css style

### Reproduction

Here's the [stackblitz](https://stackblitz.com/edit/components-issue-4118nl?file=src/app/example-component.html) 

You'll need your own Google-Maps API-Key though

### Expected Behavior

Control size of google-map with css

### Actual Behavior

Not apple to control size of google-map component with css.

### Environment

- Angular: 15.2.5
- CDK/Material: 15.2.5
- Browser(s): Chrome & Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
Your example isn't styling the same element as the width/height APIs. If you target the CSS styles at the correct element they work as expected: https://stackblitz.com/edit/components-issue-28rqh8?file=src%2Fapp%2Fexample-component.scss
