### ISSUE TITLE
bug(MatSelect): List loses focus after source data change

### ISSUE THREAD

**Issue by SergiyCh** [angular/components#26895]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2.5

### Description

If mat-select was opened it can be navigated using keyboard. But if after the opening the source data was updated - the expanded options loses focus and MatSelect.focus() method also doesn't work. So user unable to navigate list using ketboard.

[Demo project](https://stackblitz.com/edit/angular-xu7clc?file=src/app/select-custom-trigger-example.ts)

### Reproduction

Steps to reproduce:
1. Prepare some data for list
2. After list opened using .open() method - update source data
3. List become unfocused

### Expected Behavior

List always focused to navigate with keyboard.

### Actual Behavior

List loses focus after update so user can't use keyboard to navigate it.

### Environment

- Angular:
- CDK/Material:
- Browser(s): Chrome
- Operating System: Windows

**Comment by wagnermaciel** [comment]
This is not a behavior we intentionally supported. Updating the contents of an _open_ mat-select is considered undefined behavior
