### ISSUE TITLE
bug(COMPONENT): MatError is displayed inside MatFormField Borders when wrapped in NgContainer

### ISSUE THREAD

**Issue by jwittekind** [angular/components#26900]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Given the following code:

```
<mat-form-field appearance="outline" fxFlex>
  <mat-label>First Name</mat-label>
  <input matInput formControlName="firstName">
  <ng-container *ngIf="(firstNameErr$ | async) as firstNameErr"> // ⬅ NgContainer
    <mat-error>Please enter at least {{ firstNameErr?.requiredLength }} characters</mat-error>
  </ng-container>
</mat-form-field>
<mat-form-field appearance="outline" fxFlex>
  <mat-label>Nachname</mat-label>
  <input matInput formControlName="lastName">
  <mat-error *ngIf="(lastNameErr$ | async) as lastNameErr"> // ⬅ No NgContainer
    Please enter at least {{ lastNameErr?.requiredLength }} characters
  </mat-error>
</mat-form-field>

```

the mat-error gets incorrectly displayed inside the matFormField Outlines:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/21268801/230778783-b79c300e-6291-44d9-89ab-116e1359671e.png">

### Reproduction

Steps to reproduce:
1. See Code above

### Expected Behavior

The MatError gets display below the outlines of the FormField even when wrapped in an NgContainer

### Actual Behavior

The Mat Error gets displayed below the outlines of the FormField when wrapped in an NgContainer

### Environment

- Angular: 15.1.1
- CDK/Material: 15.1.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by wagnermaciel** [comment]
Placing ng-content inside of an ng-container will break content projection for the wrapper component. There is no way around this because of how content projection works in Angular, so we must consider this to be working as intended

Still, I believe your desired affect can be achieved using Angular's built-in form validation - https://angular.io/guide/form-validation.

**Comment by jimyhdolores** [comment]
I have the same problem, in my case I have the mat-error in a separate component where, according to a logic, the mat-error is shown, it is worth mentioning that this did not happen in previous versions. What solution can you give me? Thank you.
