### ISSUE TITLE
bug(Legacy inputs): Legacy inputs styles are broken

### ISSUE THREAD

**Issue by bbonczek** [angular/components#26910]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Legacy inputs (non-mdc) no longer look good. 

### Reproduction

Steps to reproduce:
1. Look at simple form with mat-form-fields using legacy module (`MatLegacyInputModule, MatLegacyFormFieldModule`)
Stackblitz editor: https://stackblitz.com/edit/components-issue-51iywd?file=src/app/example-component.html
Stackblitz hosted app: https://components-issue-51iywd.stackblitz.io/

### Expected Behavior

The form should look like this:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/11254976/231415404-75d797db-9c16-4075-98e8-09ee0ca7dd6d.png">

### Actual Behavior

It looks like this:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/11254976/231413635-ee314131-03d3-4f37-ab2f-e44a982eb287.png">

### Environment

```
Angular CLI: 15.2.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1502.4
@angular-devkit/build-angular      15.2.4
@angular-devkit/core               15.2.4
@angular-devkit/schematics         15.2.4
@angular/cdk                       15.2.6
@angular/cli                       15.2.4
@angular/fire                      7.5.0
@angular/material                  15.2.6
@angular/material-moment-adapter   15.2.6
@schematics/angular                15.2.4
ng-packagr                         15.2.2
rxjs                               7.8.0
typescript                         4.9.5
```
Browser: Chrome 111

**Comment by wagnermaciel** [comment]
I believe you're missing the legacy component themes. Please see https://material.angular.io/guide/theming for more details

Try adding this to your styles.scss
```
$primary: mat.define-palette(mat.$blue-palette);
$accent: mat.define-palette(mat.$grey-palette);
$theme: mat.define-light-theme((
  color: (primary: $primary, accent: $accent),
  typography: mat.define-typography-config(),
  density: 0
));
@include mat.all-legacy-component-themes($theme);
```

Here's an example
https://stackblitz.com/edit/components-issue-9kg1ac?file=src%2Fstyles.scss

**Comment by bbonczek** [comment]
Thank you for a help. It might be a good idea to update migration guide, as this information is missing and it is hard to find.
