### ISSUE TITLE
feat(QoL): We really need quality of life improvements / updates

### ISSUE THREAD

**Issue by richardsengers** [angular/components#26912]
### Feature Description

A lot of developers, like me, are still stuck on version 14 and unable to update to 15
To me this project almost looks like a dead end (have a look at the amount of commits in 2023). Tons of issues are still open and important feature requests (2017 2018 etc) are not being picked up.
We as a company have designed our complete frontend to Angular Material and we need to know if we need to switch to another library. I know this is all open software, but we need to keep our application updated with Angular core, which we cannot do anymore

There is no Material roadmap, and (almost) no input from the developing team.
If this project is still alive, we need at least some information about QoL updates and issues need to be picked up.

**Comment by wagnermaciel** [comment]
Hi @richardsengers , sorry to hear you're having a bad experience updating from 14 to 15

With regards to your first comment, age does not increase an issues priority. We are a small team operating on a very large scale, so we do not currently have the bandwidth to fix every single issue filed. That being said, there have already been [hundreds of commits in 2023](https://github.com/angular/components/pulls?q=is%3Apr+updated%3A%3E%3D2023-01-01+), so I'm unsure what is giving the impression that the project is a dead end

As for our roadmap, our priorities have not shifted much from [Q4 2022](https://github.com/angular/components#what-were-working-on-now-q4-2022), but I will see to it that the roadmap is updated to match our latest endeavors

Please feel free to file an issue on how the v14-15 migration tooling is not working for you. This is a particularly important area of interest for our team, and without updating to v15 you will be missing out on most of our QoL updates

Hope this addresses all of your questions. This does feel like more of a discussion than an issue so if you'd like to continue this dialog, please use https://github.com/angular/components/discussions

**Comment by richardsengers** [comment]
Hi @wagnermaciel ,

Thank you very much for the quick reply.
Sorry about the commits. I was looking at these stats:
https://github.com/angular/components/graphs/contributors?from=2022-12-06&to=2023-04-13&type=c

For us there are two major blocking issues for updating 
#25981 and #26179 

Maybe there are more blocking issues for us, we don't know yet since we are not able to update / migrate :-)

Thank's again for the quick reply....really appreciated.

**Comment by wagnermaciel** [comment]
No problem. I'll discuss these issues with the team to see if we can get them prioritized. If I can't get them prioritized, I'll at least try to provide an update for why we've chosen to place our efforts elsewhere 👍🏽

**Comment by richardsengers** [comment]
You are a legend! Thank you very much for the updates 👍🏽
