### ISSUE TITLE
MatSnackBar MDC 'impossible' to style background/foreground colors

### ISSUE THREAD

**Issue by awdorrin** [angular/components#26928]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Pre MDC

### Description

use to be able to set a panelClass like:
ths.snackbar.open(message, 'X', {panelClass: ['success-snackbar'] });

.success-snackbar {
  background: lightgreen;
  color: black;
  white-space: pre-wrap
}

With MDC components, this is no longer possible as the MDC styles take precedence and documentation gives no help in determining proper approach.

Best i've been able to do since is:

.success-snackbar .mat-mdc-snack-bar-actions {
  background-color: green;
  color: black;
}

Background color of the action button gets set to green, but the foreground color is ignored.

### Reproduction

see above

### Expected Behavior

panelClass css should apply properly to the snackbar as it has in the past

### Actual Behavior

css overridden by undocumented/hidden MDC classes

### Environment

- Angular/CDK/Material: 15.2.5-7

**Comment by awdorrin** [comment]
/rant-start...
The MDC updates for SnackBar have made things incredibly overcomplicated and without documentation you are doing a great disservice to the developers who use your product.

What was very simple and straight forward prior to Angular 15 MDC:
```
.success-snackbar {
  background: green;
  color: white ;
  white-space: pre-wrap
}
```

Has become ridiculously over complicated:
```
.success-snackbar.mat-mdc-snack-bar-container {
  .mdc-snackbar__surface {
    background: green;

    .mat-mdc-button {
      color: white !important;
    }
  }

  .mat-mdc-snack-bar-label.mdc-snackbar__label {
    color: white;
    font-weight: 500;
    white-space: pre-wrap
  }
}
```
The statement here: https://material.angular.io/guide/mdc-migration#snack-bar that 
`For simple, text-based snack-bars, there are no significant changes`
is laughable considering all the undocumented CSS class changes that override the panel class settings.

Had it not been for the post I stumbled across by Rakia Ben Sassi here: https://betterprogramming.pub/how-to-create-a-fancy-mat-snackbar-with-tailwind-css-a9fa0cf0b0c9#ec3a
it would have taken me a lot longer to finally get a solution.
As it is, I wasted over 8 hours trying to fix something simple.

Also, whoever on the material team that decided that the MDC migration was no longer optional but the default, between Angular 15.0/15.1 and 15.2 - that was a horrible decision.
/rant-end

**Comment by danrald** [comment]
@awdorrin Ya, I have work to do, it makes me look bad telling me superiors that we should upgrade. Only to find, that I have to rewrite %30 of my application along with the styling. Angular should come out and say that you will have to do a rewrite if you upgrade. Sad.

**Comment by awdorrin** [comment]
@ftaffelt Thanks for the suggestion, but unfortunately it does not work.
In the below screenshot, .error-snackbar is overridden by two different .mat-mdc-snack-bar-container rules found in: @angular/material/snack-bar/_snack-bar-theme.scss

![mat-snackbar-broken-css](https://user-images.githubusercontent.com/41024025/233630732-0ad7d4ed-6bce-4d86-ba47-741dfccc826d.png)

**Comment by awdorrin** [comment]
After more experimentation, and adding !important tags, the following does appear to work:
```
.success-snackbar {
  --mdc-snackbar-container-color: green !important;
  --mdc-snackbar-supporting-text-color: white !important;
  --mat-mdc-snack-bar-button-color: white !important;
  white-space: pre-wrap
}
```
Still:
- Why are the naming rules undocumented?
- Why are the names so inconsistent? --mdc-snackbar-* vs --mat-mdc-snack-bar-*

None of this is obvious nor does it follow 14 versions of Angular history and convention.

And the thing is, I didn't get to choose legacy or MDC - the update procedure changed from the initial V15 release instructions.
Its like someone on the MDC team, after seeing all the negative feedback, decided to double-down and force their view.

A lot of my coworkers want to ditch Material and move to something else (anything else) and I see this same sentiment across multiple developer sites.

MDC should have been introduced as '@angular\material2' or '@angular\material-mdc' not forced.

**Comment by ftaffelt** [comment]
hmm, strange because this worked for me:
https://stackblitz.com/edit/angular-uwlwmz?file=src%2Fstyles.scss

**Comment by wagnermaciel** [comment]
Hi, custom css like this is not supported. Are you unable to achieve this using the snack-bar's color mixin?
https://material.angular.io/guide/customizing-component-styles

**Comment by awdorrin** [comment]
@wagnermaciel Can you elaborate? I don't see anything at the link you provided that discusses anything about how to use the snack-bar's color mixin.

**Comment by wagnermaciel** [comment]
Ah sorry, that doc is just documenting what I said earlier about us not supporting custom css like this. Here's the guide on how to use our theming api

https://material.angular.io/guide/theming
