### ISSUE TITLE
MatAutoComplete and CDKVirtualScrollViewPort issues with selected indicator

### ISSUE THREAD

**Issue by awdorrin** [angular/components#26934]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

I don't know if this is a regression with Angular 15 MDC, as we only tried using this recently, and not on a previous angular version.

### Description

When trying to use a cdk-virtual-scroll-viewport with a mat-autocomplete the selected checkmark indicator is repeatedly displayed for unselected options, and regular intervals, based on where the actual selected item is in the list.

### Reproduction

```
    <mat-autocomplete #auto="matAutocomplete" [displayWith]="supplierDisplayFn">
      <cdk-virtual-scroll-viewport [ngStyle]="{height: '200px'}" itemSize="25">
        <mat-option *cdkVirtualFor="let l of filteredSuppliers | async" [value]="l">
          {{ l.supplierCode }} - {{ l.supplierName }}
        </mat-option>
      </cdk-virtual-scroll-viewport>
    </mat-autocomplete> 
```

### Expected Behavior

Only the actual selected item should be shown selected with the checkmark icon.

### Actual Behavior

if the second item is selected, then when the viewport is refreshed with the next set of items, the 2nd item of the new set is also selected.

### Environment

- Angular: 15.2.7
- CDK/Material: 15.2.7

**Comment by crisbeto** [comment]
Closing since we don't support virtual scrolling in the autocomplete yet.
