### ISSUE TITLE
bug(schematics): legacy components migration didn't update .spec.ts files

### ISSUE THREAD

**Issue by amakhrov** [angular/components#26958]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When updating from v14 to v15, the update schematics changes material module imports to their legacy counterparts. This worked well for the main app, but didn't change any unit test files ( .spec.ts ).

Our project structure:
```
<root>
  src/
    tsconfig.json // project-style, references to tsconfig.appjson, tsconfig.spec.json
    tsconfig.app.json
    tsconfig.spec.json
  tsconfig.base.json  
```

### Reproduction

Run `ng update @angular/cdk@15 @angular/material@15`

### Expected Behavior

Unit test files, `include`'d in `tsconfig.spec.json` are updated during the migration.

### Actual Behavior

Unit tests are untouched. Main app code is properly migrated, though

### Environment

- Angular: 15.2.6
- CDK/Material: 14.2.2 -> 15.2.7
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by wagnermaciel** [comment]
Hmm, this looks like it's probably either an issue with the underlying CLI builder or the way we're configuring it. This will need a closer look to really understand what's going wrong here

**Comment by amakhrov** [comment]
The reason is that the migration grabs tsconfigs from architect definitions in `angular.json` . In our case, unit tests are done with `@angular-builders/jest:run`, which doesn't reference the tsconfig file inside angular.json (it has a reasonable default, that we don't need to override).

Explicitly specifying `tsConfig` property for the `test` target in `angular.json` has solved the issue for us.

**Comment by amakhrov** [comment]
I guess this being caused by custom jest integration makes it out of scope for the Material repo though.
