### ISSUE TITLE
bug(CDK Focus Monitor): Empty class attribute remains when de-focusing element

### ISSUE THREAD

**Issue by elenachiosa** [angular/components#26956]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When tabbing away or clicking outside an element that's monitored by Focus Monitor, an empty class attribute remains. 

I have some generic style regarding classes on the project that breaks for this scenario and I would like for the empty class to not exist there. As a workaround for now, I check that, when the element is not focused anymore, if the classlist value is an empty string I manually remove the class attribute myself.

### Reproduction

Steps to reproduce:
1. Go to the example titled "Monitoring focus with FocusMonitor" on the [official Angular CDK documentation](https://material.angular.io/cdk/a11y/overview#focus-monitor-directives)
2. Open Developer Tools and follow the changes that happen to the button labeled "Focus Monitored Element"
3. Focus via keyboard (or mouse) -> the button will have these classes added: "cdk-focused cdk-keyboard-focused" (or cdk-mouse-focused)
4. Stop focusing the button (tab away or click outside the button)

### Expected Behavior

The class attribute on the button is cleared completely from the DOM.

### Actual Behavior

The class attribute remains and has an empty value.
![image](https://user-images.githubusercontent.com/17402311/233053559-6d84d3f1-52d8-44a2-b034-3376365f076c.png)

### Environment

- Angular: (whatever is used on the [official Angular CDK documentation](https://material.angular.io/cdk/a11y/overview#focus-monitor-directives)) 15.2.6 at the moment of writing this
- CDK/Material: (whatever is used on the [official Angular CDK documentation](https://material.angular.io/cdk/a11y/overview#focus-monitor-directives)) 15.2.6 at the moment of writing this
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This behavior is inherited from the browser itself since we're going through the `classList` API.

**Comment by crisbeto** [comment]
Closing since this is how the native APIs behave.
