### ISSUE TITLE
mat-datepicker: invisible 'Close calendar' button (.mat-datepicker-close-button) is missing tabIndex=-1

### ISSUE THREAD

**Issue by kcruijss** [angular/components#26973]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The `mat-datepicker` has an invisible button (with label 'Close calendar') below its `mat-calendar` within the same div. Since it's invisible, it's not too big of a deal that it's there in the first place. But one issue I noticed is that it incorrectly is missing a tabIndex=-1, and will gain focus and become visible when tabbing through the datepicker.

### Reproduction

Steps to reproduce:
1. Go to the mat-datepicker demo page: https://material.angular.io/components/datepicker/overview
2. Open the Basic datepicker (by clicking the calendar-icon)
3. Click tab on your keyboard, and see how it shows and focuses the previously invisible 'Close calendar' button

![image](https://user-images.githubusercontent.com/5364335/233657704-295ac4c1-6da0-4ecf-96a7-c848b2379d3e.png)

### Expected Behavior

The invisible 'Close calendar' button should have a `tabIndex=-1`.

### Actual Behavior

It currently has no tabIndex, so we can tab to the invisible button.

### Environment

- Angular: 15.2.8
- CDK/Material: 15.2.8
- Browser(s): any (checked in Google Chrome; FireFox; and Edge)
- Operating System (e.g. Windows, macOS, Ubuntu): any (checked in Windows)

**Comment by crisbeto** [comment]
The button is intentionally there so users can tab into it. This is similar to how some sites deal with the `Skip to content` links.
