### ISSUE TITLE
bug(AutoComplete): Doesn't scroll on mobile when tooltip is added

### ISSUE THREAD

**Issue by HarelM** [angular/components#26979]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2

### Description

When adding a tooltip to an autocomplete dropdown items the scroll doesn't work on mobile.

### Reproduction

Steps to reproduce:
1. Set `matTooltip` on the autocomplete option item
2. Try to scroll on mobile device

Surf here from mobile and try to scroll the list after the dropdown opens:
https://stackblitz.com/edit/angular-material-autocomplete-tooltip?file=src%2Fapp%2Fautocomplete-auto-active-first-option-example.ts

### Expected Behavior

Scroll should always work

### Actual Behavior

The user can't scroll

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by crisbeto** [comment]
On mobile tooltips are shown on a long press gesture which can interfere with other gestures like taps. The get around this limitation, by default the tooltip will block other gestures. You can control how they behave using the `matTooltipTouchGestures` input. More info in the docs: https://material.angular.io/components/tooltip/api

**Comment by HarelM** [comment]
This workaround is nice, but in version 14 it used to work out of the box, there was no need for this worksround - long press would show tooltip and touch scroll would still work...
Just saying :-)

**Comment by crisbeto** [comment]
Maybe it worked for that specific case, but it was problematic in other places. We decided to handle it this way since tooltips can be placed anywhere. You can configure it globally for your entire app with the `MAT_TOOLTIP_DEFAULT_OPTIONS` DI token. Closing since it's working as expected.

**Comment by HarelM** [comment]
Can you clarify in the docs what's the default value? It's not clear. Is it off or auto?

**Comment by crisbeto** [comment]
It defaults to `auto`.
