### ISSUE TITLE
bug(mat-select): ng-template inside mat-select

### ISSUE THREAD

**Issue by faribauc** [angular/components#26976]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Not sure if this is intended or not, seems elated to #10379. The issue I'm having is when using `ng-template` directly witnin a `mat-select` element. The goal here is to build a recursive nested dropdown with option groups and options.

### Reproduction

https://stackblitz.com/edit/components-issue-kp8neg?file=src/app/example-component.html

### Expected Behavior

Select UI component should build properly.

### Actual Behavior

Select UI dropdown is empty.

### Environment

- Angular: 14.2.0
- CDK/Material: 14.2.7
- Browser(s): Chrome 112.0.5615.121
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 22.04 LTS

    "@angular/animations": "^14.2.0",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/material": "^14.2.7",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "convert-units": "^3.0.0-beta.5",
    "csvtojson": "^2.0.10",
    "jszip": "^3.10.1",
    "lodash": "^4.17.21",
    "rxjs": "~7.5.0",
    "ts-debounce": "^4.0.0",
    "ts-md5": "^1.3.1",
    "tslib": "^2.3.0",
    "uuid": "^9.0.0",
    "zone.js": "~0.11.4"

**Comment by crisbeto** [comment]
It's because Material uses `ContentChildren` to find the options which doesn't work when they're projected in from a different place in the template. We can do much about it since this is how content projection works at the framework level.
