### ISSUE TITLE
feat(COMPONENT): RATING, SKELETON, ETC

### ISSUE THREAD

**Issue by Deliana90** [angular/components#26983]
### Feature Description

missing features like [rating](https://mudblazor.com/components/rating), [skeleton](https://mudblazor.com/components/skeleton), [navmenu](https://mudblazor.com/components/navmenu#sub-groups), etc.
even newcomer like [MUDBLAZOR](https://mudblazor.com/docs/overview) has more feature than angular material T__T sad

**Comment by crisbeto** [comment]
Closing since these components aren't in the Material design spec.
