### ISSUE TITLE
bug(table): `renderRows` doesn't trigger change detection in content projection

### ISSUE THREAD

**Issue by jmeinlschmidt** [angular/components#26985]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Please see the Stackblitz. This is a particular case. However, running `renderRows` on the projected table component doesn't trigger change detection for this child component. Although this behaviour seems correct for the _OnPush_ strategy, I am still looking for ways to make this example work. This isn't particularly a matter only of `renderRows`, but the same behaviour is observed while using Observables or custom Data source.

In other words, how can I set the `dataSource` from the wrapper component and make it run the change detection without actually modifying the projected (child) component?

### Reproduction

https://stackblitz.com/edit/angular-qsduhf?file=src%2Ftable.ts

### Expected Behavior

The data source will run the change detection and display table body content.

### Actual Behavior

The table is empty, and no data is projected due to a missing change detection run. Manually running change detection from inside the child component is needed.

### Environment

- Angular: 15.2.8
- CDK/Material: 15.2.8
- Browser(s): Version 112.0.5615.137 (Official Build) (arm64) 
- Operating System: macOS

**Comment by andrewseguin** [comment]
Change detection with projected contents is difficult to define in Angular - the correct solution for this is likely to use `Default` change detection here instead of `OnPush`
