### ISSUE TITLE
npm install hangt reify:@angular/material: timing reifyNode:node_modules/typescript

### ISSUE THREAD

**Issue by ofeigenbaum** [angular/components#26989]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/122781274/234227734-09d8e1e8-5193-44eb-bcf0-c0834ce7ebfe.png">

### Reproduction

Steps to reproduce:
1. ng add angular material 15
2.npm i

### Expected Behavior

npm wont hang

### Actual Behavior

npm hangt

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): chrome, firefox
- Operating System (e.g. Windows, macOS, Ubuntu):macos npm and node lts

**Comment by crisbeto** [comment]
This is likely an issue in your setup. None of the warnings in the screenshot refer to Material.
