### ISSUE TITLE
bug(Autocomplete): Density is applied only to input field

### ISSUE THREAD

**Issue by HarelM** [angular/components#26998]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Applying density to mat-form-field that has an autocomplete doesn't change the density of the auto complete.

### Reproduction

Steps to reproduce:
1. Create an input form field
2. Set scss density to -2
3. Compare how the auto-complete looks compared to non-dense version

The following is the stackbliz:
https://stackblitz.com/edit/angular-autocomplete-density-issue?file=src/app/autocomplete-simple-example.scss

somewhat related to the following issue: #26208

### Expected Behavior

The density should affect both controls

### Actual Behavior

The density is only applied to the input field

### Environment

- Angular: 15.2
- CDK/Material: 15.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
Based on the discussion in https://github.com/angular/components/pull/21621, it sounds like density isn't supposed to apply to overlays.

**Comment by HarelM** [comment]
You linked to an issue which was opened more than two years ago with no actual progress... Great...
Is there a workaround I can use using css or something?

**Comment by crisbeto** [comment]
The discussion there mentions that according the Material design spec, density shouldn't apply to overlays (e.g. menus and dropdowns). That's why we haven't addressed it.
