### ISSUE TITLE
docs-bug(form-field): Links to MatLegacyFormFieldControlHarness are broken

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#26991]
### Steps to reproduce
1. Visit https://material.angular.io/components/input/api#MatInputHarness
2. Click the "`MatLegacyFormFieldControlHarness`" link 

### Expectation
The link takes you to documentation explaining what "`MatLegacyFormFieldControlHarness`" is & does.

### Actual
The link takes you to the site's home page: https://material.angular.io/.

### Affected documentation page

https://material.angular.io/components/input/api#MatInputHarness

**Comment by crisbeto** [comment]
Closing since the legacy components were deleted.
