### ISSUE TITLE
bug(MatSelectHarness): MatSelectHarness clickOptions does not work

### ISSUE THREAD

**Issue by yogeshgadge** [angular/components#26996]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

```
    const select = await loader.getHarness(selectHarness.with({selector: '#basic'}));
    await select.clickOptions({ text: '10' });
    const selected = await select.getValueText();
    expect(selected).toBe('10');
```

### Reproduction

[MatSelectHarness - specs](https://harness-issue-86nzcu.stackblitz.io)

### Expected Behavior

It should reflect the selected text value

### Actual Behavior

Does not set the selected value

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
It's failing because the options don't have a value so the select can't distinguish them. You can change it to this to get it working: `<mat-option *ngFor="let opt of options" [value]="opt">{{ opt }}</mat-option>`.
