### ISSUE TITLE
docs-bug(Chips): _chips is not documented. Unclear of intent of property

### ISSUE THREAD

**Issue by ChandlerBaskins** [angular/components#26999]
### Documentation Feedback

In Material v14 you could access the chips of a MatChipList using the `chips` property. With the update to v15 and new classes, MatChipListBox exposes this property `_chips`. Due to common usage of a underscore to denote private properties this causes confusion on whether this should be a publicly accessible property.  Could we get some insights on the intentionality of this property and whether its ok for use in app code land. 

### Affected documentation page

https://material.angular.io/components/chips/api#MatChipSet

**Comment by ChandlerBaskins** [comment]
v14 docs that show chips as a public property **https://v14.material.angular.io/components/chips/api#MatChipList**

**Comment by crisbeto** [comment]
Properties prefixed with an underscore are considered private to the library hence why they're undocumented.

**Comment by ChandlerBaskins** [comment]
Thanks for the clarification! What should we be using instead?

**Comment by crisbeto** [comment]
You should be able to write your own `ViewChildren` query to get all the chips.
