### ISSUE TITLE
feat(mat-tab-group): add stretchTabs to MatTabsConfig for v15.x.x

### ISSUE THREAD

**Issue by mangei** [angular/components#27002]
### Feature Description

In https://github.com/angular/components/issues/26645 @joelkesler described a great configuration addition for backwards compatibility which is now merged into main.

I would be great to have this available in a v15 release.

main: https://github.com/angular/components/blob/main/src/material/tabs/tab-config.ts#L41  
15.2.x: https://github.com/angular/components/blob/15.2.x/src/material/tabs/tab-config.ts#L39

Will this be part of an upcoming v15 release or can you make it part of it?

### Use Case

Currently I am migrating lot of micro-frontends with a shared component library. Just adapting the configuration would be an easy thing, instead of migrating all tab-components and making sure, that every other developer doesn't forget about this, to have a consistent UX.

Thanks a lot! 💪   
~Manuel

**Comment by crisbeto** [comment]
Closing since we don't backport features to old versions.
