### ISSUE TITLE
Mat-Select is not functioning properly after angular and material version upgrade from v10 to v15.2.4

### ISSUE THREAD

**Issue by rishwanthrajaa** [angular/components#27003]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular V10.1.5 and Material V10.2.4

### Description

This report is regarding dropdown field issue of Angular Material V15.2.4 (Mat-Select)

Recently, we have upgraded our project's angular version from v10.1.5 to v15.2.4. 
Application's drop down fields were working fine in angular v10.1.5 and material v10.2.4. 
But when the version got upgraded with angular v15.2.4 and material v15.2.4., all the drop down fields are facing issue in showing the selected option.

**Issue**:
- There is no issue in listing the options. 
- After selecting any one of the option, mat-select has to show up the selected option.
- But the field is blank after selecting an option.

**Version and Coding strategy**:
1. Reactive Form is used. FormBuilder and FormGroup was used to create formcontrols.
2. After upgrade, All material imports was updated to legacy option. (Example - MatButtonLegacy)
3. In angular v10, Two-way data binding ([(ngModel)]) has been used to bind the id of the selected option, it worked fine.
4. But in v15 we have tried by removing the ngModel, still not fixed.
5. Have tired with [(value)] way of binding, that too didn't give a hand.
6. This is not a multiple select.
7. We have used exact code mentioned below in angular v10 and its not working in angular v15. Find the sample example here - https://material.angular.io/components/select/examples#select-form

**Support Needed**
1. Angular support team to provide a solution to fix the issue in Mat-Select drop down.
2. To provide if any code changes or import level changes has to be done.
3. We have tested with angular v15.2.4 and material version as v12.2.13, all seems fine.
4. Is it fine to have a downgraded material version with  higher angular version?.
5. **Kindly respond whether it is a good standard to have Angular v15.2.4 and material v12.2.13 as part of production release or provide an fix for the issue in the upgraded versions for both angular and material v15.2.4.**

Kindly refer the below attachment which shows actual issue in the dropdown after selecting an option, the field is blank;

<img width="696" alt="b4bc512e-f815-4e50-b949-c68a2370b082" src="https://user-images.githubusercontent.com/62600471/235129808-52abe281-fb86-475d-b6e5-b3e0698e7519.png">

### Reproduction

Steps to reproduce:
1. Set the angular version as 15.2.4 and material version as 15.2.4
2. Inject a Mat-Select drop down field in template
3. Set a list of options in .ts file for Mat-options (Example - Apple, Orange, Mango etc)
7. Options will be binding correctly in the selectable drop down.
8. Select any one of the values from the drop down list.
9. Issue - After selecting, selected value will not show up in the field.

### Expected Behavior

The expected behavior is -  After selecting any one of the option, mat-select has to show up the selected option.

Expected working one as mentioned in this example  - https://material.angular.io/components/select/examples#select-form 

### Actual Behavior

Actual behavior - After selecting an option, selected value does not show up in the Mat-Select Field.

Below one the case where the field is empty after selecting an option.

<img width="696" alt="b4bc512e-f815-4e50-b949-c68a2370b082" src="https://user-images.githubusercontent.com/62600471/235130488-3f3d1b4a-255e-47a6-9755-6dc69c353b6a.png">

### Environment

- Angular: **v15.2.4**
- CDK/Material: **CDK - v15.2.4 and Material - v15.2.4**
- Browser(s): **Google Chrome and Microsoft Edge**
- Operating System (e.g. Windows, macOS, Ubuntu): **Windows**

**Comment by crisbeto** [comment]
Please provide an example showing the select in a broken state. These step-by-step guides take a long time to follow and generally don't show the issue.

**Comment by rishwanthrajaa** [comment]
@crisbeto 
After selecting a dropdown, it should show the selected value right? But it doesn't show up
The below one is the broken drop down issue

![image](https://user-images.githubusercontent.com/62600471/236110920-3e03a11f-f3fc-46f3-8bdf-72b1b3e0e4e4.png)
