### ISSUE TITLE
bug(COMPONENT): General Standalone Functionality

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#27009]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Trying to make the Button Example standalone.  This works except if I try to add a `mat-select` to the demo, it starts having issues.

https://stackoverflow.com/questions/76134076/making-the-angular-materials-button-example-standalone

### Reproduction

Steps to reproduce:
1. See Stackoverflow Stackblitz
2.https://stackoverflow.com/questions/76134076/making-the-angular-materials-button-example-standalone

### Expected Behavior

It should work.

### Actual Behavior

Please see stackoverflow link:
https://stackoverflow.com/questions/76134076/making-the-angular-materials-button-example-standalone

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You have to add either `provideAnimations` or `provideNoopAnimations` to the `providers` of the `bootrstraApplication` call.

**Comment by fireflysemantics** [comment]
@crisbeto  OK aweesome!  Also someone has a working example here in this question:

https://stackoverflow.com/questions/76147869/making-the-angular-material-select-demo-stackblitz-into-a-standalone-component
