### ISSUE TITLE
bug(MatSlideToggle): Use primary, accent and warn colors of palette instead of 300,600,200 and 900 

### ISSUE THREAD

**Issue by AndreasMietk** [angular/components#27017]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

To use the colors property on the [mat-slide-toggle](https://material.angular.io/components/slide-toggle/overview) the developer has to define explicitely the color values of `300`, `600`, `200` and `900` in the `$color-palette`, otherwise the fallback values will be used.

All other components i have seen use the `primary`, `accent` or `warn` values on the palette to work in conjunction with the `color` property (e.G. `mat-radio-button`) except this one.

The scss file in question is this one 
[src/material/slide-toggle/_slide-toggle-theme.scss](https://github.com/angular/components/blob/main/src/material/slide-toggle/_slide-toggle-theme.scss#L50)

Here is an example for the radio button to get the correct colors:
[src/material/radio/_radio-theme.scss](https://github.com/angular/components/blob/main/src/material/radio/_radio-theme.scss#L12)

### Reproduction

Steps to reproduce:
1. Define color palette not using the `300`, `600`, `200` and `900` keys as hues
```scss
$primary-palette: (
   default:  #9F9F9F,
   lighter:  #E8E8E8,
   darker: #262626
)

$my-theme: mat.define-light-theme(
   color: (
      primary: mat.define-palette($primary-palette, default, lighter, darker)
   )
)

...
```
3. Use `<mat-slide-toggle color="primary">`

### Expected Behavior

Color of component should be `#9F9F9F`

### Actual Behavior

Color of toggle is `#6200ee` (fallback)

### Environment

- Angular: 15.1.3
- CDK/Material: 15.1.1/15.2.8
- Browser(s): Vivaldi (chromium)
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
The current colors are based on the Material design spec. If we didn't use the right hues, they won't match the designs anymore.
