### ISSUE TITLE
docs-bug(COMPONENT): Disable outside click close in mat-select

### ISSUE THREAD

**Issue by gokujy** [angular/components#27019]
### Documentation Feedback

![image](https://user-images.githubusercontent.com/18545714/235849682-bc133dc5-2d94-4e16-9e34-01e3350c9b24.png)

I want to disable the outside click of mat-select, I have a requirement is close when clicking on the done button if any option is selected.

Is there any way to do this? Please help me...

### Affected documentation page

https://material.angular.io/components/select/overview

**Comment by crisbeto** [comment]
Closing since we don't support this pattern with buttons in the select in the first place. Also worth noting that clicking outside isn't the only way to close it, there's also the escape key.
