### ISSUE TITLE
mat-checkbox does not allow selecting of text in WebKit browsers (Safari, Epiphany)

### ISSUE THREAD

**Issue by t00** [angular/components#27027]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

When selecting a mat-checkbox text and starting selection from the checkbox text, selection will not be made and checkbox state is toggled.

When starting selection from beyond the checkbox text (before tick on the left or after text) or ending selection beyond the checkbox text - selection is made correctly.

Affects only WebKit using pointer. WebKit touch, Chrome and Firefox are fine.

Reproducible on https://material.angular.io/components/checkbox/overview but also on https://v7.material.angular.io/components/checkbox/overview.

### Please provide a link to a minimal reproduction of the bug

https://material.angular.io/components/checkbox/overview

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 5.2.5 - 16.0.0
```

**Comment by crisbeto** [comment]
It works for me both when starting the selection from the checkbox text and when starting it from the outside. I'm closing the issue since we don't do anything special for text selection, it's up to the OS/Browser.

https://user-images.githubusercontent.com/4450522/237014952-95e2c7e5-5e3f-4b00-af85-6be84aa6e6c5.mov

**Comment by t00** [comment]
I have had this issue reported by a Mac user yet I am using Epiphany to reproduce it and behavior is consistent with the report - WebKit is the only engine changing checkbox state when selecting the text.

@crisbeto I am not sure how were you able not to trigger the check event on Safari/Mac but it is a common knowledge that WebKit has it's quirks and quite likely special treatment might be needed for it.

In our app (Angular 13) we do use native browser highlighting to mark areas of text for feedback and unstable selection is preventing users from reporting issues with content present in checkbox text areas.

Is there a workaround to hook into mat-checkbox mousedown/up events and prevent checked change when selection length > 0?

[Screencast from 2023-05-09 20-16-41.webm](https://github.com/angular/components/assets/1933165/c2a559ea-a08f-4442-86d3-3ad51bd524ac)

**Comment by t00** [comment]
@crisbeto Please find below a recording of Chromium 113. It works perfectly - does not tick the checkbox regardless of selection start/end. It won't even trigger the checkbox when selection started when hovering over the checkbox and ended in the middle of text.

Hope you can use it for reference of expected behaviour.

[Screencast from 2023-05-09 20-34-12.webm](https://github.com/angular/components/assets/1933165/b3e86e24-3487-42c3-a671-3037e366dfd3)

**Comment by crisbeto** [comment]
This is how native checkbox work as well though, e.g. check out the demo here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox. `mat-checkbox` is basically a native checkbox with `opacity: 0`.

**Comment by t00** [comment]
That is a good point, I should have checked a plain checkbox. It should have been a WebKit bug report then - thanks for looking into it.
