### ISSUE TITLE
bug(matInput): Attribute binding doesn't initially work on mat-form-field wrapped textarea

### ISSUE THREAD

**Issue by Nikovic** [angular/components#27020]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm trying build a textarea component in which the textarea may or may not be "readonly". For this I have an boolean "editable" which I'm attribute-binding to readonly as described in [Angular's documentation](https://angular.io/guide/attribute-binding) (`[attr.readonly]="editable ? null : 'readonly'"`). However, this binding seems to be ignored initially. When changing the editable field later, the binding works.

I've built this stackblitz to demonstrate: https://stackblitz.com/edit/angular-attribute-bug-12079483?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

The native textarea behaves correctly (i.e. is readonly) from the start. The mat-form-field wrapped textarea only becomes readonly after toggling the button twice.

A further detail I've found: If 'editable' is initialized to true (right at it's declaration), and then set to false in ngAfterViewInit, the binding works. If setting to false is done in ngOnInit already, it doesn't work. It also doesn't work if editable was initialized to false in the first place.

### Reproduction

Steps to reproduce:
1. Without touching the toggle button in the stackblitz, edit the second textarea. Observe that it works (when it shouldn't)
2. Toggle the button twice
3. Observe that both textareas are now readonly.

### Expected Behavior

Both textareas should start off readonly.

### Actual Behavior

Only the non-wrapped textarea starts off readonly.

### Environment

- Angular: 14.3.0
- CDK/Material: 14.2.7
- Browser(s): I checked Chrome and Firefox, I presume it's all of them
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
You should bind it with the `readonly` input: `<textarea [readonly]="editable"></textarea>`.
