### ISSUE TITLE
bug(mat-tab): tabs are focusable even if they are disabled

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#27030]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.4

### Description

bug(mat-tab): tabs are focusable even if they are disabled

Example - https://v15.material.angular.io/components/tabs/examples#tab-group-ink-bar

Also cdk-* classes are getting applied in disabled mode

v15.2.9 - https://stackblitz.com/edit/fpkg6a-vehkd7?file=package.json

![v15 2 9](https://user-images.githubusercontent.com/34937515/236162368-87d58a09-f624-4604-b9c3-54ecb1955b0c.gif)

v15.0.4 - https://stackblitz.com/edit/ippjv4?file=package.json

![v15 0 4](https://user-images.githubusercontent.com/34937515/236162392-2d989760-2ac2-410a-a94d-e33cd0aa5385.gif)

### Reproduction

Steps to reproduce:
1. Go to https://stackblitz.com/edit/fpkg6a-vehkd7?file=src%2Findex.html
2. Try to navigate on mat-tab using keyboard as shown in attached GIF

### Expected Behavior

Disabled item should not get focus

### Actual Behavior

Disabled item is getting focus

### Environment

- Angular: 15.2.8 (exists in 16 a well)
- CDK/Material: 15.2.8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. Users need to be able to navigate to disabled tabs to know that they exist.
