### ISSUE TITLE
feat(MatDialogHarness): Please add method to check MatDialogActions.align

### ISSUE THREAD

**Issue by ChrTall** [angular/components#27042]
### Feature Description

Please add a method to MatDialogHarness to check MatDialogActions.align.
Currently you can only check the text content of MatDialogActions.

### Use Case

Helps for testing components.

**Comment by amysorto** [comment]
Hi @ChrTall, this feels like a really specific thing to test for (or maybe I am missing the context specific to your tests) so I am going to close this issue.
