### ISSUE TITLE
feat(CdkDropList): Add Harness to make it easier to test CdkDropList implementations

### ISSUE THREAD

**Issue by ChrTall** [angular/components#27045]
### Feature Description

Currently it is really hard to test custom implementations of the CdkDropList.
It would be a nice to have a TestHarness similar to the TestHarnesses in the Material library.

### Use Case

Testing components that utilize CdkDropList.

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/22067.
