### ISSUE TITLE
bug(MatTable): Jumpy MatPager when inside expandable MatTable

### ISSUE THREAD

**Issue by vitaly-t** [angular/components#27052]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

With your [examples section](https://material.angular.io/components/table/examples), there are demos for using expandable `MatTable`, with the help of `ngTemplateOutlet`, and there are demos for using `MatPager`. But there isn't a single example of using both. And if there were, you would see that when combining expandable `MatTable` with `MatPager`, it no longer looks well.

What happens - every time we expand a panel, all panels that are below + the pager show an animation artifact whereby the whole thing jumps lower first, and then it jumps back up, which doesn't look well. Just as we remove `MatPager` from expandable `MatTable`, that artifact disappears.

### Reproduction

Take any of the [existing examples](https://material.angular.io/components/table/examples) of expandable `MatTable` (with template), and add `MatPager` into such demo, you will get the undesired effect of jumpy animation upon expansion.

### Expected Behavior

When adding `MatPager` into expandable `MatTable`, the latter must continue animating as before.

### Actual Behavior

Once `MatPager` is added into expandable `MatTable`, expansion of any item results in a jump of all items below + the pager.

### Environment

- Angular: 15.2.9
- CDK/Material: 15.2.9
- Browser(s): Chrome 112
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by vitaly-t** [comment]
I found that this depends on what's inside the expansion container. I will investigate more, and publish an update or a new issue. Closing it for now.

**Comment by vitaly-t** [comment]
**UPDATE**

The issue manifests itself when we have anything with CSS Flex inside the expansion panel. Anything flex-based results in a glitch in `MatTable` animation after adding `MatPager`.

**Comment by vitaly-t** [comment]
I got to the bottom of it...

In every demo for expandable `MatTable` you applied this class on the animated element:

```css
.example-element-detail {
  overflow: hidden;
  display: flex;
}
```

If we comment out `display: flex`, then the issue with the pager starts showing for various content inside the expansion view, i.e. the pager starts jumping up and down on expansion.

It's a weird one.

**Comment by andrewseguin** [comment]
What is `MatPager`? Can you provide a link to a stackblitz showing the issue

**Comment by vitaly-t** [comment]
Cannot quite reproduce on the standard example, so closing it.
