### ISSUE TITLE
bug(cdk/table): Borders in sticky Header

### ISSUE THREAD

**Issue by glutengo** [angular/components#27077]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using sticky headers with `border-collapse: collapse` and borders on the `td` elements (in our case: `border-right`), the border does not remain sticky but scrolls out of the viewport.

![cdktable_sticky_header_border_AdobeExpress](https://github.com/angular/components/assets/14246032/8a29b9af-809f-47f4-a80d-aa45106cf09b)

Repro: https://stackblitz.com/edit/w4lwqg?file=src/app/cdk-table-basic-example.css

### Reproduction

Steps to reproduce:
1. Open the example https://stackblitz.com/edit/w4lwqg
2. Start scrolling

### Expected Behavior

The dark right border of the table header columns stay where they are

### Actual Behavior

The dark right border of the table header columns leave the viewport

### Environment

- Angular: 16.0.0
- CDK/Material: 16.0.0
- Browser(s): Chrome Version 113.0.5672.92 (Official Build) (x86_64)
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS 13.3.1 (a) (22E772610a)

**Comment by inspiremithun** [comment]
Hi Team is any one working in this bug.  i would like to work if no one started working

**Comment by wagnermaciel** [comment]
The cdk library does not provide styles beyond what is needed to achieve behaviors. The border scrolling is just part of how the native browser handles sticky header els with collapsed borders.

See this html example:

https://stackblitz.com/edit/w4lwqg-nwyu9t?file=src%2Fapp%2Fcdk-table-basic-example.html,src%2Fapp%2Fcdk-table-basic-example.css
