### ISSUE TITLE
bug(matTabLink): disabled flag does not work

### ISSUE THREAD

**Issue by fbuscaroli2** [angular/components#27071]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.x

### Description

the mat-tab-link disabled flag does not prevent click

### Reproduction

Steps to reproduce:
1.  Add a (click) action to a mat-tab-link

### Expected Behavior

The click action should not occur.

### Actual Behavior

The click action is executed any way.

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
Binding to the click event still works for `mat-tab-link` when disabled in v16.0.1
