### ISSUE TITLE
matieral tab header: pagination controls flickering

### ISSUE THREAD

**Issue by alexfung888** [angular/components#27084]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

At some particular widths, the tab header will jump between two states:

-   display the tab headers with pagination control (ie < on far left and > on far right)
-   display the tab headers without pagination controls

I cannot make a sample code to show this, but it has already appeared on two of my pages. When it happens, the page width is wide enough to show all the tab headers without scrolling. Yet, the <> appears (making the headers to be displayed with less spacing) and then disappears. It is happening at more times per second than my eye can catch. All I can see is a pair of blur images for each tab header, since they are placed at slightly different locations with vs without the <>. On inspection, the class `mat-mdc-tab-header-pagination-controls-enabled` will be applied and removed from the mat-tab-header at top speed. 

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

the tab headers should either be displayed with or without the scrolling  controls < and >

### Actual Behavior

the display is swapping between the two, making the headers unreadable.

### Environment

- Angular: 16.0.1
- CDK/Material: 16.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by amysorto** [comment]
I tried to reproduce this, but am not able to. I'll close this issue but if you can reproduce and provide a stackblitz link, I can take another look.
