### ISSUE TITLE
bug(mat-checkbox): checkbox is not affected by theme default density

### ISSUE THREAD

**Issue by lgaida** [angular/components#27085]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

I am currently migrating from v14 to v15 and i'm now trying to rework my layouts to match the previous v14 look as much as possible.

I have always been using a custom theme and i am importing the component themes on my own (NOT using the `all-component-themes`).

Since everything was a bit smaller in v14 i tried to mimic this by relying on the new density-features. When playing around with v15 and density i have noticed that some components seem to not care about the default density defined in my theme.

A very obvious one is the checkbox which does not care about the default density at all.

There are two checkboxes, a default one and an explicitly denser one. In the theme.scss i have set the default theme density to 0.

A "denser checkbox" is wrapped in a div with css-class "dense", which is used in theme.scss to include the checkbox-density(-3) explicity.

Given i change the theme default density to -3, i expect the default checkbox to shrink to the same size of the explicitly denser checkbox. However the default checkbox stays the same size, ignoring the default density.

A simple form-field/input however proves that the theme is configured properly, since the input will shrink based on the provided theme default density.

### Reproduction

See a minimal reproduction on [stackblitz](https://stackblitz.com/edit/angular-autocomplete-density-issue-pzrcpe?file=src/theme.scss)

### Expected Behavior

I expect the checkbox to respect the theme density and shrink accordingly.

### Actual Behavior

The checkbox stays the same size no matter what the theme density is.

### Environment

- Angular: 15.2.8
- CDK/Material: 15.2.8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

**Comment by shinkhouse** [comment]
I've also experienced this very same issue. I used the stackblitz example from Angular Material v15 documentation on mat-checkbox and added the density configuration on the theme level and tried the individual mat.checkbox-density(-2) example and neither have worked.

**Comment by NachmanBerkowitz** [comment]
have you tried wrapping in a body tag?
`body{
      @include mat.checkbox-density(-3);
}`

**Comment by wagnermaciel** [comment]
Hi, from what I've gathered, this behavior is intentional. The checkbox is being affected by the change to density in that the focus ring and ripple are smaller making the overall size of the checkbox smaller

The goal of decreasing density isn't to make everything look tiny, it's to allow more information to fit on the screen. For the checkbox, the square inside was not the limiting factor for that, which is why it does not get smaller when the density changes

**Comment by lgaida** [comment]
Hi, thanks for your reply. I am aware that the density does not affect the checkbox rectangle but the touchable focus/ripple area. I opened this issue because i am setting a theme-wide density of -3 but the checkbox does not seem to be affected by it. 
```
$theme: mat.define-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      warn: $theme-warn,
    ),
    typography: $typography,
    density: -3,
  )
);
@include mat.core-theme($theme);
@include mat.checkbox-theme($theme);
```
Given the above snippet i expect that the checkbox-theme takes care of applying the correct density of -3. I expect all my checkboxes to have a density of -3 but they don't.

They only shrink after i explicitly include & use the checkbox-density within a css-class
```
.dense {
  @include mat.checkbox-density(-3);
}
```
