### ISSUE TITLE
`valueChange` Event in v16.0.0 No Longer Emits Values Continuously During Slider Drag

### ISSUE THREAD

**Issue by matzar** [angular/components#27097]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.0

### Description

In version 15.1.0, the `valueChange` event used with `matSliderThumb` would emit values continuously as the slider was being dragged. This was particularly useful for updating values in real-time during a drag operation. For instance, consider the following setup:

```html
<mat-slider>
  <input
    (dragStart)="dragSliderStartMin(index)"
    (valueChange)="minSliderValueChange($event, index)"
    matSliderStartThumb
  />
  <input
    (dragStart)="dragSliderStartMax(index)"
    (valueChange)="maxSliderValueChange($event, index)"
    matSliderEndThumb
  />
</mat-slider>
```

```ts
async dragSliderStartMin(index: number) {
  await this.loadFile(i);
}

minSliderValueChange(value: number, index: number) {
  // ...
}

// ...
```

However, in the newly released v16.0.0, this behavior appears to have changed. The `valueChange` event only emits a value when the slider dragging operation ends, as opposed to continuously during the drag.

To restore the previous behavior, one workaround I found is using `ngModel` for template-driven binding:
```html
<mat-slider>
  <input
    [(ngModel)]="sliderValue"
    (ngModelChange)="sliderValueChange($event)"
    matSliderThumb
  />
</mat-slider>
```

Alternatively, I achieved the same result by using `formControl` with reactive forms and subscribing to `valueChange`:
```html
<mat-slider>
  <input
    (dragStart)="dragSliderStartMin(index)"
    [formControl]="expectationMin($event, index)"
    matSliderStartThumb
  />
  <input
    (dragStart)="dragSliderStartMax(index)"
    [formControl]="expectationMax($event, index)"
    matSliderEndThumb
  />
</mat-slider>
```
```ts

ngOnInit() {
  this.addSubscriptions();
}

addSubscriptions() {
  this.expectationMin(this.index)
    .valueChanges.pipe(distinctUntilChanged())
    .subscribe((value) => {
      console.log('min value changed', value);
      this.minSliderValueChange(value, this.index);
    });

  // same for expectationMax and maxSliderValueChange
}
```

I wanted to bring up this change in behavior as it may impact other users who relied on the continuous value emission during slider drags in their projects. Can anyone confirm if this change was intentional or if it's a bug?

### Reproduction

Steps to Reproduce:

1. Reproduction of the issue in Angular v16.0.0

Navigate to the StackBlitz sample code for Angular v16.0.0: [Angular 16 slider with valueChanges showing value only when drag ends](https://stackblitz.com/edit/angular-16-material-starter-xdmmkz?file=package.json).

In this sample, notice that when you drag the slider, the value changes are only displayed when the dragging ends. This is the behavior we're discussing in this issue.

2. Comparison with the behavior in Angular v15.1.0

Now, navigate to the StackBlitz sample code for Angular v15.1.0: [Angular 15, same source code, slider with valueChanges showing value when dragging the slider](https://stackblitz.com/edit/angular-16-material-starter-fmmekv?file=package.json).

In this sample, when you drag the slider, the value changes are continuously displayed next to the slider as you're dragging. This is the previous behavior we're comparing to.

By observing the behavior in both versions of Angular with the same source code, you can clearly see the difference in valueChange event emissions during slider dragging.

### Expected Behavior

In Angular Material version 15.1.0, the `valueChange` event used with `matSliderThumb` was designed to emit values continuously as the slider was being dragged. This enabled real-time value updates during a drag operation. I expect to see this same behavior in Angular Material version 16.0.0.

### Actual Behavior

In Angular Material version 16.0.0, the `valueChange` event's behavior appears to have changed. Instead of emitting values continuously during the slider dragging operation, it now only emits a value when the slider drag operation ends. This change interrupts real-time value updates and only allows for updates when the user releases the slider.

### Environment

- Angular: 16.0.0
- CDK/Material: 16.0.0
- Browser(s): Version 113.0.5672.92 (Official Build) (arm64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOs Ventura, Version 13.3.1

**Comment by wagnermaciel** [comment]
Hi, IIRC this was an intentional change so that value change operates the same way the actual change event does on the native slider. You can still listen for changes to the value as the user drags using the input event listener on the slider thumbs
