### ISSUE TITLE
feat(skeleton ): skeleton loading

### ISSUE THREAD

**Issue by mohammadmahdihasani** [angular/components#27090]
### Feature Description

This component is available in all kits and frameworks, but it is not present in this framework
Be sure to add this item It is badly needed
To use this component, we must use another library, which is highly risky
We have to use this additional library to style our software components: https://www.npmjs.com/package/ngx-skeleton-loader

**Comment by wagnermaciel** [comment]
This is not something we plan on tackling in the foreseeable future, primarily because it is not part of the material design spec which we do our best to adhere to

**Comment by mohammadmahdihasani** [comment]
> This is not something we plan on tackling in the foreseeable future, primarily because it is not part of the material design spec which we do our best to adhere to

But the absence of this component is very annoying

**Comment by wagnermaciel** [comment]
I sympathize with that sentiment, but it's not feasible for us to implement and maintain every component desired by the community. We are a very small team with many users so we have had to make careful decisions about the things we prioritize & build/maintain :(
