### ISSUE TITLE
bug(datepicker): dateFilter is not working properly

### ISSUE THREAD

**Issue by robertIsaac** [angular/components#27098]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.3.9

### Description

when using `dateFilter` on the date picker, the `selectedChange` event never emit

from what I'm seeing in https://material.angular.io/guide/mdc-migration, the date picker doesn't have any breaking changes, if I'm wrong please refer me to what I need to update to make it work again (and if possible please fix the reprod)

### Reproduction

Steps to reproduce:
1. use `mat-calendar` normally
2. use `dateFilter` for it

https://stackblitz.com/edit/angular-syqmnz?file=src/main.ts

### Expected Behavior

when choosing different date the `selectedChange` event to emit

### Actual Behavior

when choosing different date the `selectedChange` event does not emit

### Environment

- Angular:
- CDK/Material: 15.2.2 (same behavior with 14.0.6)
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by robertIsaac** [comment]
FYI in Angular 13.3.9 it works only if the change detection strategy is on push
Updating to 14.0.0 it doesn't work

**Comment by crisbeto** [comment]
It's because you're recreating the `dateFilter` function for each change detection. This causes change detection to run continuously and interrupt the click. Your `dateFilter` function should be static, e.g. if you change it to `dateFilter = () => true` it works as expected.

**Comment by robertIsaac** [comment]
> It's because you're recreating the `dateFilter` function for each change detection. This causes change detection to run continuously and interrupt the click. Your `dateFilter` function should be static, e.g. if you change it to `dateFilter = () => true` it works as expected.

in the real application I need to pass a variable from the template to the function
so it's more like

```ts
  dateFilter = (foo: Foo) => {
    return (date: Date) => this.isEnabled(foo, date);
  };
```

**Comment by crisbeto** [comment]
It's a little janky, but the way to do it would be to assign it to a property of the component class and have the `dateFilter` read it from there.

**Comment by robertIsaac** [comment]
> It's a little janky, but the way to do it would be to assign it to a property of the component class and have the `dateFilter` read it from there.

to be clear, I'm talking about `ngFor`, how would I know which item of the array is this one?
the only workaround I can think of to work, is to create a component to wrap this inside
