### ISSUE TITLE
feat(COMPONENT): SASS Theming Extension functions for button colors

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#27095]
### Feature Description

It would be nice if there was a utility API for button colors that could be used both internally and by external clients.

[For example the Fab button](https://github.com/angular/components/blob/main/src/material/button/_fab-theme.scss) defines a `_fab-variant` mixin like this:

```
@mixin _fab-variant($foreground, $background) {
  @include mdc-fab-theme.theme((
    container-color: $background,
    icon-color: $foreground,
  ));

  --mat-mdc-fab-color: #{$foreground};
}
```

We can't use this outside of Angular because its private.

Something like this can be used both within the current code base and as a client facing API for extending the Fab button colors:

```
@use '@material/fab/fab-theme' as mdc-fab-theme;
@use '../common/' as *;

@mixin fab-variant($color-class, $foreground, $background) {
  &.#{ $color-class } {
    @include mdc-fab-theme.theme(
      (
        container-color: $background,
        icon-color: $foreground,
      )
    );
    background-color: var(--mdc-fab-container-color, transparent);
    color: var(--mdc-fab-icon-color, inherit);
    @include ripple-color($foreground);
  }
}

  }
}
```
It can be called like this with color extensions for the Fab button.

```
  .mat-mdc-fab {
    @include fab-variant(mat-success, $on-success, $success);
    @include fab-variant(mat-danger, $on-danger, $danger);
    @include fab-variant(mat-info, $on-info, $info);
  }
```

Also `_mdc-helpers` is also private.  Angular uses it in conjunction with delegation to the Material Components Web API like this:

```
@include mdc-helpers.using-mdc-theme($config) { ...
```

So it would be nice to be able to follow the same approach for grabbing property values via the `mdc` API ... 

It would be really nice if this were public as well:

```
@mixin _ripple-color($color) {
  --mat-mdc-button-persistent-ripple-color: #{$color};
  --mat-mdc-button-ripple-color: #{rgba($color, 0.1)};
}
```

Also the `fab-variant` type of approach works for all the buttons ( Using the MDC helper SASS mixins like `mdc-fab-theme.theme`, except for the icon button.  For the icon button ( Unless I missed something ) I had to code my own helper function that looks like this:

```
@use 'sass:map';

@mixin theme($color) {
  --mdc-icon-button-icon-color: #{map.get($color, icon-color)};
}
```

With that the variant extension method can be implemented like this:

```

/**
 * The MDC API is not symmetric with respect to the other button theme helper mixins
 */
//@use '@material/icon-button/icon-button-theme' as mdc-icon-button-theme;
@use './el-x-icon-button-theme' as el-x-icon-button-theme; 
@use '../common/' as *;

@mixin icon-variant($color-class, $color) {
  &.#{ $color-class } {
    @include el-x-icon-button-theme.theme((
      icon-color: $color
    ));
    color: var(--mdc-icon-button-icon-color);
    @include ripple-color($color);
  }
}
```

### Use Case

Extend buttons colors.

**Comment by fireflysemantics** [comment]
https://github.com/material-components/material-components-web/issues/8105

**Comment by wagnermaciel** [comment]
Hey, I think we are already working on a solution to this issue. We are currently working on a new token based theming api which will enable supported finer-grained customization of component styles. I don't think the roadmap is public but you can see the progress on our main branch

https://github.com/angular/components/commits/main

E.g.
https://github.com/angular/components/commit/5459f5cd5fc7dd838cfde36a1108da3d43d40d42

**Comment by fireflysemantics** [comment]
Hey @wagnermaciel that's awesome!  I would be really nice if this ticket could stay open as a way to track the progress.
