### ISSUE TITLE
Form Field Accessor Tags for Scss and CSS

### ISSUE THREAD

**Issue by onedeaddonkey** [angular/components#27101]
### Documentation Feedback

Prior to version 15 we are able to change the opacity on all manner of form fields, selectors, radio buttons, buttons, sliders, basically every type of component and more specifically disabled fields. 

Now, nothing I do within the main theme SCSS or the component level CSS can access the new mat-mdc-form-fields.

I think it's great that you guys are looking to come more in line with the MDC base, but please, provide in depth documentation on actually accessing the individual component classes which allow us to tailor the experience for our end users. 

Version 15 was borderline catastrophic for us, and our end users cannot handle how transparent disabled fields are.  Please provide the documentation that allows us to tweak these things again. Or give us back the old ng-deep, something, anything, that allows us to actually access the components like we used to. 

Thank you.

### Affected documentation page

https://v15.material.angular.io/components/form-field/examples

**Comment by mt5242874** [comment]
Although I completely agree with this, it may be beneficial to roll back to V14 for angular material.

**Comment by andrewseguin** [comment]
The transition to v15 is non-trivial and we understand the migration pain. We are performing the same work within Google across thousands of apps. We hope that by aligning closer to Material Design, we can more quickly improve the components as design changes.

That said - feel free to use `ng-deep` to style components. It is deprecated, but with no alternative. The Angular team acknowledges that it's okay to use as long as there's no other way to deeply style components
