### ISSUE TITLE
bug(COMPONENT): Colors Not Supporting at any place

### ISSUE THREAD

**Issue by anoop-mobikasa** [angular/components#27107]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

no

### Description

<img width="960" alt="image" src="https://github.com/angular/components/assets/28626409/576af17a-7362-4d2d-8511-bf0b37922de5">
This error is showing.

style.scss
<img width="952" alt="image" src="https://github.com/angular/components/assets/28626409/eb6892dc-1984-4e36-bf8f-1e47577234aa">

<img width="960" alt="image" src="https://github.com/angular/components/assets/28626409/cb7f503a-3a5a-4edd-8732-6ffa3fca240b">

<img width="960" alt="image" src="https://github.com/angular/components/assets/28626409/54e8dda0-af54-4ef4-8d33-bc85e56be2ad">

<img width="960" alt="image" src="https://github.com/angular/components/assets/28626409/0fda941f-eb9b-4bff-a71a-369e5751c580">

### Reproduction

Steps to reproduce:
1.  just add material in standalone ng 16 application 
2. select custom theme

### Expected Behavior

colors should appear on buttons

### Actual Behavior

colors not showing

### Environment

- Angular: 16
- CDK/Material:
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): window

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4

**Comment by wagnermaciel** [comment]
It's tough to understand what exactly the issue is here - seems like you are saying there are no colors but also that there is an error. It would be easier to understand if there was a stackblitz reproduction of the issue

As for the error, you have an @use on line 37 causing that error
