### ISSUE TITLE
Angular material form fields height change

### ISSUE THREAD

**Issue by AngularTx** [angular/components#27120]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Is there a way to make the height of the form field ( like say 40px) and make sure that all components attached to form fields (select , text area etc. ) will works fine with the change. 

### Reproduction

just a query on how this can be achieved in best way 

### Expected Behavior

just a query on how this can be achieved in best way . Would like to make all form fields of same height and make sure all of the  basic features would work as expected. 

### Actual Behavior

   just a query on how this can be achieved in best way . Would like to make all form fields of same height and make sure all of the  basic features would work as expected. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
I think the density API is what you're looking for

https://material.angular.io/guide/theming#customizing-density
https://stackblitz.com/edit/flwarj?file=src%2Fapp%2Fform-field-overview-example.html,src%2Ftheme.scss
