### ISSUE TITLE
jalali calendar

### ISSUE THREAD

**Issue by amirheydari9** [angular/components#27133]
### Feature Description

The Jalali Angular Material calendar does not work properly and we have to use side packages that are usually compatible with older versions of Angular and we cannot fully use the new features of Angular in our project. Please add Jalali calendar support to Angular Material

### Use Case

jalali calendar

**Comment by ShrootBuck** [comment]
ah yes I love me a good old persian calendar

**Comment by amysorto** [comment]
It's unlikely we can add support for this at this time so I'll be closing this issue
