### ISSUE TITLE
docs-bug(COMPONENT): docs(api-docs/material-table): fixed description for MatHeaderRow

### ISSUE THREAD

**Issue by nishchay7pixels** [angular/components#27143]
### Issue :
Description under **MatHeaderRow extends CdkHeaderRow** is

> Footer template container that contains the cell outlet. Adds the right class and role.

However it should be,

> Header template container that contains the cell outlet. Adds the right class and role.

<img width="1685" alt="Screenshot 2023-05-23 at 5 26 51 PM" src="https://github.com/angular/components/assets/24619269/d10d30ed-f2df-40e4-9c7f-faa14c0607aa">

### Affected documentation page

https://material.angular.io/components/table/api#MatHeaderRowDef

**Comment by Naaajii** [comment]
ello, cool find - but you are not suppose to make PRs directly into [material2-docs-content](https://github.com/angular/material2-docs-content) instead fork this [repo](https://github.com/angular/components/) to make necessary changes in docs. happy contributions!
