### ISSUE TITLE
bug(mat-slider): current value out of sync with form value

### ISSUE THREAD

**Issue by maxime1992** [angular/components#27145]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Current value of the slider can be out of sync between the actual form value and the view.

### Reproduction

[Minimal reproduction on Stackblitz](https://stackblitz.com/edit/components-issue-rp3ric?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts).

Steps to reproduce:
1. Open up the stackblitz repro
2. Look at the example-component.ts file
3. Read the whole comment explaining what's expected
4. In the view, click next button twice to end up in wrong state (all explained in details in stackblitz as a comment)

### Expected Behavior

When updating the form value, the current value in the view should be the correct one.

### Actual Behavior

In some cases, it looks like the current value in the view isn't the correct one (in this case, it looks like it's taking the previous max value as current one).

| Initial state ✅ | First state ✅ | Second state ⛔ |
| --| -- | -- |
| ![image](https://github.com/angular/components/assets/4950209/27b22c13-1e87-42f2-b06d-3705410e9d66) | ![image](https://github.com/angular/components/assets/4950209/db6e9a6f-b932-4630-92c2-526f28f7b00e) | ![image](https://github.com/angular/components/assets/4950209/b2cff3ce-9d40-4d72-8f2a-eeab4db71c27) |

### Environment

```
Angular CLI: 15.0.4
Node: 16.14.2
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.2.1
@angular/material               15.2.1
@schematics/angular             15.0.4
ng-packagr                      15.0.3
rxjs                            7.6.0
typescript                      4.8.4
```

**Comment by maxime1992** [comment]
Although... It kind of makes sense that it takes the highest value allowed as the boundaries are not applied just yet.

I believe running CD manually after setting the new boundaries will work (before setting the new value).

But it can be a bit confusing, if there's any way to make this a little bit safer good, otherwise I understand that it's not really something that can be fixed.

**Comment by wagnermaciel** [comment]
Yeah, your description of the behavior is correct. We could expose a method on the `mat-slider` to set the min/max/value simultaneously so that users don't need to manage that interaction themselves (although, I don't believe that this would eliminate this problem). I'll close this issue but if you feel strongly that we should introduce a batch update function, feel free to open a feature request and we can revisit this
