### ISSUE TITLE
bug(mat-tab): NG0912: Component ID generation collision detected in unit test

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#27163]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Getting below error while running unit tests of the application

`Chrome 113.0.0.0 (Windows 10) WARN: 'NG0912: Component ID generation collision detected. Components 'MatTab' and 'MatLegacyTab' with selector 'mat-tab' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912'
`

<img width="939" alt="image" src="https://github.com/angular/components/assets/34937515/266a4c59-b6b6-4f64-853e-969bf8c6b475">

### Reproduction

Steps to reproduce:
1. Create new angular 16 app (npx ng new)
2. Install material (ng add @angular/material)
3. Use legacy version of mat tab inside your component
4. Try to run units of the component in which you are using legacy mat-tab

Or you can use attached zip file

[ng16app.zip](https://github.com/angular/components/files/11561130/ng16app.zip)

### Expected Behavior

Running units should not throw the warning

### Actual Behavior

Running units is throwing the warning

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This should be resolved once we're on a version that includes https://github.com/angular/angular/pull/50203.

**Comment by amakhrov** [comment]
Looks like the fix from https://github.com/angular/angular/pull/50203 has been reverted.

Is there any way forward to suppress those warnings in unit tests?

**Comment by amakhrov** [comment]
Interesting that in our code base (which uses Material extensively, and only partially migrated to MDC yet), we only observe 2 conflicting Material components:
> Components 'MatTab' and 'MatLegacyTab' with selector 'mat-tab' generated the same component ID

and

> Components 'MatTextColumn' and 'MatLegacyTextColumn' with selector 'mat-text-column' generated the same component ID

Perhaps it would be a simple enough interim change to fix these two and unblock projects that wish to upgrade to Angular 16?

**Comment by crisbeto** [comment]
That fix was resubmitted eventually so the root cause is likely different.
