### ISSUE TITLE
docs-bug(Sidenav): Add example on combining mat-sidenav with mat-tree

### ISSUE THREAD

**Issue by marklagendijk** [angular/components#27177]
### Documentation Feedback

For business applications a common requirement is to have multi-level navigation.
Currently the documentation does not explain how this can be achieved.

When I needed to implement this myself, I could not find any simple example online. The examples I found tried to combine `mat-nav-list` with `mat-accordion`, but only achieved this by doing quite a few hacks.

In the end I found out that `mat-tree` can easily be combined with `mat-nav-list` to achieve this use case. This works very straightforward and does not require any hacks.

I created a [Stackblitz example](https://stackblitz.com/edit/vpnnoq?file=src%2Fexample%2Fsidenav-menu.component.html) that shows the approach.
I think it would be very valuable to add an example like this to the documentation. This also ensures that the use case isn't accidentally broken.

### Affected documentation page

https://material.angular.io/components/sidenav/examples

**Comment by andrewseguin** [comment]
That example sounds fairly complex and niche - I'm glad it worked out well for you, but this doesn't sound like what we are going for with examples

**Comment by marklagendijk** [comment]
I wouldn't call multi-level navigation a niche use case.
The only complicated part is automatically opening the parent menu-item of a menu-item that has been navigated to.

I would say that common use cases that are a bit trickier / less obvious are exactly the kind of thing a developer is looking for in the documentation.
