### ISSUE TITLE
feat(COMPONENT): "Reload this page" handling

### ISSUE THREAD

**Issue by Panic7** [angular/components#27189]
### Feature Description

When a user leaves unsaved data, and tries to reload the page with browser `Reload this page`, or hotkey `F5` - with @HostListener on `beforeunload` we can show confirmation dialog, but we cannot handle its response. That is, provide some interface, or something else, so that depending on confirm/cancel response, we could perfom some actions.

### Use Case

For example, i want to set some value for an current user while he edit some data, but when he stopped/refreshing/leave page i want to unset this value. Ok, partly i can do this using CanDeactivate<> interface, and show my dialog, but this only works to change the routing, whereas refreshing the page does not change the route

**Comment by andrewseguin** [comment]
I don't see how providing this can give much value to users since it should be fairly trivial to set up this custom experience in applications.
