### ISSUE TITLE
bug(matMenu): panelClass and overlayPanelClass don't work with matMenu

### ISSUE THREAD

**Issue by Yura13** [angular/components#27200]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![image](https://github.com/angular/components/assets/17030431/e4c2bbda-5cc8-4df0-bdff-dd34ccd943b0)

### Reproduction

Add panelClass and overlayPanelClass to matMenu component. Those classes don't appear in html when opening menu

### Expected Behavior

panelClass and overlayPanelClass should work with matMenu

### Actual Behavior

panelClass and overlayPanelClass don't work with matMenu

### Environment

- Angular: 15.2.7
- CDK/Material: 15.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

The same behavior for v.16

**Comment by andrewseguin** [comment]
Please provide a stackblitz reproduction of your issue

**Comment by swseverance** [comment]
@Yura13 you can use the `class` input to apply classes:
```html
<mat-menu
  #aboveMenu="matMenu"
  yPosition="above"
  class="red blue"
>
  <!-- #enddocregion menu-position -->
  <button mat-menu-item>Item 1</button>
  <button mat-menu-item>Item 2</button>
</mat-menu>
```

As for the `overlayPanelClass` it does not appear to be an `@Input` of the `MatMenu` component. If I'm not mistaken it can only be set via `MAT_MENU_DEFAULT_OPTIONS` so you could do something like this:

```typescript
import {Component} from '@angular/core';
import {MAT_MENU_DEFAULT_OPTIONS} from '@angular/material/menu'
/**
 * @title Menu positioning
 */
@Component({
  selector: 'menu-position-example',
  templateUrl: 'menu-position-example.html',
  providers: [
    {
      provide: MAT_MENU_DEFAULT_OPTIONS,
      useValue: {
        overlapTrigger: false,
        xPosition: 'after',
        yPosition: 'below',
        backdropClass: 'cdk-overlay-transparent-backdrop',
        overlayPanelClass: 'green'
      }
    }
  ]
})
export class MenuPositionExample {}
```

**Comment by Yura13** [comment]
@swseverance 
Yes, you are right. Thanks!
