### ISSUE TITLE
bug(slider): Track bar of a range slider gets out of sync with the thumbs

### ISSUE THREAD

**Issue by amakhrov** [angular/components#27207]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When clicking/ dragging the slider thumbs it sometimes results in the track getting one step behind the thumb. It's quite easy to see if the steps of the slider are large enough (e.g. min=0 max=9 step=1).

I could only reproduce it when interacting with different thumbs each time: e.g. first, interact with the "start" thumb, then interact with the "end" thumb.

I suspect it happens when the "click" event is quickly followed by a slight dragging of a thumb - but it's just a speculation from my side.

It happens both in Material 15 and 16

### Reproduction

StackBlitz link: https://stackblitz.com/edit/benvwf?file=src%2Fexample%2Fslider-range-example.html
Steps to reproduce:
1. Move the start thumb to the next position
2. Move the end thumb to a new position

Repeating the two steps until the issue is reproduced

### Expected Behavior

The track is always aligned with the thumbs position

### Actual Behavior

Occasionally, the track stays one step behind

Screenshots:
<img width="431" alt="Screenshot 2023-05-31 at 5 28 57 PM" src="https://github.com/angular/components/assets/1004015/4f245f95-f780-47c9-98e3-2585304f9358">
<img width="467" alt="Screenshot 2023-05-31 at 5 06 54 PM" src="https://github.com/angular/components/assets/1004015/3e088a5f-0267-4067-9ae8-5567f8b8cea2">
<img width="780" alt="Screenshot 2023-05-31 at 5 05 06 PM" src="https://github.com/angular/components/assets/1004015/0a0aad94-d52d-4aed-8937-6c53a22e9414">
<img width="755" alt="Screenshot 2023-05-31 at 5 02 27 PM" src="https://github.com/angular/components/assets/1004015/dead999b-aeff-4a63-9fcf-7690df149567">

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Firefox, Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by wagnermaciel** [comment]
Fixed by [PR #27218](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fangular%2Fcomponents%2Fpull%2F27218)
