### ISSUE TITLE
bug(mat-select): adding content inside mat-select causes weird scroll jumping behavior when clicking on mat-options

### ISSUE THREAD

**Issue by patrick99e99** [angular/components#27209]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When scrollable content exists at the top of the pane of a mat-select, after scrolling down to get to the actual mat-options, when clicking these options, the scroll position of the pane jumps around and has extremely buggy and bizarre behavior.

I was able to reproduce this issue with a simple example:

### Reproduction

StackBlitz link: 
https://stackblitz.com/edit/angular-14-material-uoxt1m?file=src%2Fapp%2Fhello.component.html

Steps to reproduce:

Simply click the select drop down and scroll down to the options and check some of them and you will notice that every time you click, the pane's scroll position jumps around...

### Expected Behavior

the scroll position should not change when clicking options.

### Actual Behavior

scroll position jumps around and is extremely weird and confusing.

### Environment

- Angular: 14.1.0
- CDK/Material: 14.2.0
- Browser(s):  Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by crisbeto** [comment]
We only support projecting `mat-option` and `mat-optgroup` in the select.
