### ISSUE TITLE
MatSelect allows disabled input l while MatInput does not

### ISSUE THREAD

**Issue by Aadish0905** [angular/components#27201]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am not able to disable mat-input using [disabled] = true or [attr.disabled] = true or form.get("form-control").disable.
It doesn't work.

### Reproduction

Steps to reproduce:
1. add [disabled] in mat-input
2.

### Expected Behavior

Input should be greyed out when disabled is used.

### Actual Behavior

It is not working as of now. It is still allowed to edit

### Environment

- Angular: 12.2.5
- CDK/Material:12.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is likely an issue on your end. Here's an example that has a disabled input: https://material.angular.io/components/input/examples#input-form
