### ISSUE TITLE
bug(Material forms): mat-option elements are outside any containers they should be in

### ISSUE THREAD

**Issue by LordM4x** [angular/components#27221]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

These elements are outside of the div, form and mat-form-field
![image](https://github.com/angular/components/assets/82895323/7a71580f-cd74-4e53-b1d4-7cb37c85f870)
And it does not make sense to me why

### Reproduction

I have no idea how to use stackblitz.

HTML:
```

<div id="main">
  <div class="column">
    <p class="heading">Forge your Sword!</p>
    <form [formGroup]="swordForm" (ngSubmit)="submitSword()">
      <mat-form-field>

        <mat-label>Sword's name:</mat-label>
        <input matInput type="text" placeholder="Doran's Blade" formControlName="swordName" maxlength="128">

      </mat-form-field>

      <mat-form-field>

        <mat-label>Creator's name:</mat-label>
        <input matInput type="text" placeholder="Doran" formControlName="creatorName" maxlength="64">

      </mat-form-field>

      <mat-form-field>
        <mat-label>Select your parts:</mat-label>
        <mat-select multiple formControlName="parts">
          <mat-option *ngFor="let part of parts" [value]="part">

            <app-part [part]="part"></app-part>

          </mat-option>
        </mat-select>
      </mat-form-field>
    </form>

  </div>
  <div class="column column-mid">
    <form [formGroup]="partForm"  (ngSubmit)="submitPart()" id="partform">
      <p class="heading">Create a Part</p>
      <mat-form-field>
        <mat-label>Select part-type:</mat-label>

        <mat-select formControlName="PartType">

          <mat-option *ngFor="let partType of forgingService.availablePartTypes" [value]="partType">

            <div [matTooltip]="partType.desc">{{partType.type}}</div>

          </mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field>
        <mat-label>Select material:</mat-label>
        <mat-select formControlName="Material">
          <mat-option *ngFor="let material of forgingService.availableMaterials" [value]="material">

            <app-material [Mat]="material"></app-material>

          </mat-option>
        </mat-select>
      </mat-form-field>
    </form>
  </div>
  <div class="column swordlist" >
    <app-sword *ngFor="let sword of swordService.swords" [sword]="sword"></app-sword>
  </div>
</div>
```

### Expected Behavior

I expect the mat-options to be added into the same container as the mat-select

### Actual Behavior

The mat-options were appended in a div at the end of the HTML 

### Environment

- Angular: 15.2.8
- CDK/Material: latest
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by LordM4x** [comment]
I tried to reproduce the issue in StackBlitz however in my multiple tries it either did not work at all or displayed it normal

**Comment by LordM4x** [comment]
https://github.com/angular/components/issues/15764
This issue is similar to mine

**Comment by emaggini-1** [comment]
I as well am experiencing this issue. [Here is a stackblitz which reproduces it.](https://stackblitz.com/edit/angular-16-jest-preset-7wcbwk?file=src%2Fapp%2Fapp.component.html) @amysorto  @LordM4x

**Comment by emaggini-1** [comment]
It seems that the overlay is incorrectly placed outside the app-root.

<img width="753" alt="image" src="https://github.com/angular/components/assets/117313160/e25e27d1-9202-445d-9268-905ec5ca615e">

**Comment by emaggini-1** [comment]
Thank you for the reminder. I should have updated this post. Yes, I did figure that out as well. Seems like if the library is going to experience such issues when missing a default theme, the compiler should at least thrown a warning.
