### ISSUE TITLE
bug(table & sort): Issue with sorting column passed from parent to child

### ISSUE THREAD

**Issue by angelxz** [angular/components#27240]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to create a component which dynamically creates a material table with sorting and I want to be able to define custom columns. The problem is that I can't seem to make sorting work with these custom columns.

What I noticed is the following:
- It is not possible to define a `mat-sort-header` in the custom columns because it requires a parent with `matSort`.
- When you create a parent with `matSort` the column with `mat-sort-header` gets "assigned" to the parent `matSort` which is different from the `matSort` in the component, that creates the dynamic table.
- Using the `register` method of `MatSort` doesn't seem to work.

I would be very grateful if you could help me a bit, because I've been quite stuck and can't seem to find a solution.

This is not exactly a bug I suppose, but I am not sure how to label it.

### Reproduction

[StackBlitz link](https://stackblitz.com/edit/components-issue-iw33ux?file=src%2Fapp%2Ftable-wrapper-component.ts)

### Expected Behavior

The custom columns to sort.

### Actual Behavior

The custom columns won't sort.

### Environment

ng version output:

```
Angular CLI: 16.0.2
Node: 18.13.0
Package Manager: npm 9.6.6
OS: linux x64

Angular: 16.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@angular/cdk                    16.0.1
@angular/material               16.0.1
@schematics/angular             16.0.2
rxjs                            7.4.0
typescript                      5.0.4
```

**Comment by andrewseguin** [comment]
You're best bet may be to create a custom sorting component that extends the `MatSortHeader`. Then you should be able to provide your own logic to assign `this._sort`.

Unfortunately we don't have the resources to dig in too deep to solve the problem, but perhaps you could ask this somewhere like StackOverflow
