### ISSUE TITLE
bug(CDK): The cursor should always be forbidden for dragging disabled items.

### ISSUE THREAD

**Issue by zhonglin94** [angular/components#27242]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The cursor should always be forbidden for dragging disabled items.

https://github.com/angular/components/assets/32061513/39fca799-b9a3-4ee3-9b0d-95455065b789

### Reproduction

Reproduce link: https://material.angular.io/cdk/drag-drop/overview#disabled-dragging
Steps to reproduce:
1. Go to the reproduce link(the disabled dragging section)
2. Drag the disabled item
3. The cursor is the pointer for the first time
4. Drag the disabled item again
5. The cursor becomes forbidden

### Expected Behavior

The cursor should always be forbidden for dragging disabled items.

### Actual Behavior

The cursor is a pointer when dragging the dragging disabled items sometimes.

### Environment

- Angular: 16.0.3
- CDK/Material:16.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by garrettld** [comment]
The behavior you're seeing isn't from the CDK, it's from your browser. The thing you're dragging on step 4 of your reproduction is not the drag item at all, it's the text you highlighted in step 2, and the cursor changing is your browser's behavior. It works exactly the same on all text elements, regardless of whether they use CDK drag/drop.
