### ISSUE TITLE
When mat select no options then why hide mat select trigger selected data?

### ISSUE THREAD

**Issue by moon-web75** [angular/components#27266]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I search the data then not founding any search data then no options are there then hide the selected data

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Selected data not display

### Actual Behavior

Selected data not display

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
Hello @moon-web75 ,

Thank you for reaching out. I'm not sure I totally understand what hide mat select trigger selected data means. Unfortunately, we might not be able to take action on this unless we can reproduce the issue.

Could you please provide a Stackblitz reproduction of the issue?

-Zach

**Comment by moon-web75** [comment]
Hello @zarend Thank you for your response,

I have attested the video and share the Stackbliz link

LINK : https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html


[Tab-1686548820750.webm](https://github.com/angular/components/assets/95608631/79d9e760-e891-492c-a554-9f2fe4dec7d7)
