### ISSUE TITLE
bug(mat-sidenav): Mat-sidenva will disappear when mat-sidenav-content contains mat-form-field

### ISSUE THREAD

**Issue by KarosChen** [angular/components#27275]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the official document, sample code of fixed position sidenavs scenario in sidenavs component,
mat-sidenva can't be rendered on browser.
But, when I remove mat-form-field in mat-sidenva-content, sidenavs will be rendered.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. https://stackblitz.com/edit/x2ujhg-pigdhe?file=package.json
2.

### Expected Behavior

Mat-sidenva should display when it used with mat-form-field
Expected display:
![good](https://github.com/angular/components/assets/25933094/1be98fed-5727-46da-b9e1-1c19e12f570d)

### Actual Behavior

Mat-sidenva will disappear when mat-sidenav-content contains mat-form-field
Actual display:
![error](https://github.com/angular/components/assets/25933094/6f5c6374-24d4-4b0a-a049-738566edb5dd)

### Environment

- Angular: 16.0.0
- CDK/Material: 16.0.4
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by shambhu-22** [comment]
Hi please include MatInputModule, in your stackblitz example i added it & it made navbar visible. Let me know if it isn't resolved

**Comment by KarosChen** [comment]
@shambhu-22 You are right! When I add MatInputModule, navbar become visible. I think official stackblitz example have some error. Hope official could fix it. Thank for your reply!
