### ISSUE TITLE
docs-bug(COMPONENT): Opening and closing a sidenav Stackblitz example freezes on build

### ISSUE THREAD

**Issue by eflowbeach** [angular/components#27281]
### Documentation Feedback

The Stackblitz example on this page: https://material.angular.io/components/sidenav/overview#sidenav-open-close (Opening and closing a sidenav) freezes while Fetching packages:
![image](https://github.com/angular/components/assets/5221303/ad263046-05f0-4baf-b1e9-8ce1b4c8b05d)

~/projects/w3spml--run
❯ yarn install && yarn start
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[################################################################################################] 920/921

### Affected documentation page

https://material.angular.io/components/sidenav/overview#opening-and-closing-a-sidenav

**Comment by Naaajii** [comment]
Seems to be working fine, I believe it can be network issue.

![image](https://github.com/angular/components/assets/54370141/14677f4b-3f11-40c8-b0fc-6e7bd66a977f)
