### ISSUE TITLE
bug(MatSelect): Translated (Transloco) Mat select does not show text without interaction when transloco string is the only non-whitepace character

### ISSUE THREAD

**Issue by SebastianRzk** [angular/components#27311]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

I don't know, I am using transloco the first time and with nx-translate I experienced no inconvenience. 

### Description

When my option text contains only a translated string (with transloco), the initial value selection is not presented

Example code:

```html
<mat-form-field>
    <mat-label>nach Erfolg</mat-label>
    <mat-select value="only-fehlerhaft" (selectionChange)="onChange()" [(value)]="selectedOption">
        <mat-option
                [value]="OPTION_ONLY_FEHLERHAFT">
            {{"some.cool.key.nurFehlerhaft" | transloco}}</mat-option>
        <mat-option
                [value]="OPTION_ONLY_ERFOLGREICH">{{"some.cool.key.nurErfolgreich" | transloco}}</mat-option>
        <mat-option
                [value]="OPTION_ALLE">{{"some.cool.key.alle" | transloco}}</mat-option>
    </mat-select>
</mat-form-field>
```
Results in:
![drowdown_broken](https://github.com/angular/components/assets/5215946/12f903bd-390f-439c-b350-57bd1c9e1f3e)

When I put text / or a non-whitespace character (e.g. `&zwnj;` ) next to a translation-key, it works as expected:

```html
<mat-form-field>
    <mat-label>nach Erfolg</mat-label>
    <mat-select value="only-fehlerhaft" (selectionChange)="onChange()" [(value)]="selectedOption">
        <mat-option
                [value]="OPTION_ONLY_FEHLERHAFT">
            &zwnj;{{"some.cool.key.nurFehlerhaft" | transloco}}</mat-option>
        <mat-option
                [value]="OPTION_ONLY_ERFOLGREICH">{{"some.cool.key.nurErfolgreich" | transloco}}</mat-option>
        <mat-option
                [value]="OPTION_ALLE">{{"some.cool.key.alle" | transloco}}</mat-option>
    </mat-select>
</mat-form-field>
```
![drowdown_workaround](https://github.com/angular/components/assets/5215946/0921e8a2-adeb-4be9-b1da-6fbba931165d)

What I've already tried:

* Calling ChangeDetectorRef manually -> Does not help
* Change ChangeDetectionStrategy from OnPush to Default -> Does not help
* Inserting cool whitespace char-hack -> works :D

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Should show translated text.

### Actual Behavior

Does not show the text. But there is a workaround. 

### Environment

- Angular: 16.0.0
- CDK/Material: 16.0.0
- Transloco: 4.2.6
- Browser(s): Firefox and Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by JonasDev17** [comment]
Just a guess but maybe set your selectedOption to null initially instead of ""  (empty string)

**Comment by SebastianRzk** [comment]
Thank you for the Idea.
For now, I hardcoded the selected value:
![image](https://github.com/angular/components/assets/5215946/0c477199-e542-40da-9499-f048d54babc9)
Changing it (e.g. on OnInit) does not trigger a re-render.

**Comment by JonasDev17** [comment]
I recommend using reactiveforms: https://angular.io/guide/reactive-forms
