### ISSUE TITLE
bug(mat-slider): Slider can not be dragged from outside the thumb when [step] input is used, in Safari iOS

### ISSUE THREAD

**Issue by jbgtmartin** [angular/components#27316]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

In iOS Safari, when the [step] input is used, the slider can not be dragged from outside of the thumb. It means that if I start dragging on the slider track for instance, but not on the slider thumb itself, the thumb's ripple will show, but the thumb won't move to my finger's location.

If I remove the [step] input, the thumb is behaving correctly.

I didn't have this issue with the legacy implementation.

It can be measleading, because if the user drags a little outside the "drag target", the ripple will show as if the interaction was working, but the thumb will not move.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-bf7qpd?file=src%2Fapp%2Fexample-component.html
Steps to reproduce:
1. Open the stackblitz on iOS. You can also see it on Angular's website in the [first example](https://material.angular.io/components/slider/examples), by switching between 0 and non-0 step value.
2. Start dragging on the track, not on the thumb itself

### Expected Behavior

The thumb should move to the finger's location, and then follow the finger.

### Actual Behavior

The thumb's ripple shows, but the thumb does not move.

### Environment

- Angular: 16.1.1
- CDK/Material: 16.1.1
- Browser(s): Safari on iOS
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 16.3.1, iPad OS 16.2, iPad OS 15.6

**Comment by wagnermaciel** [comment]
Hello @jbgtmartin! I tried this out using the native html `input type="range"` ios slider and ironically it seems like the behavior of the first slider is correct and the second one is a bug. You can see this more clearly if you show the value of the sliders

https://stackblitz.com/edit/components-issue-z2rlu4?file=src%2Fapp%2Fexample-component.html

For context, the new slider is built directly on top of the native html slider. While that has it's benefits, the downside is that the behavioral quirks of each independent browser implementation is going to be reflected in the mat-slider

**Comment by jbgtmartin** [comment]
Thank you for your answer, there indeed seems to be an issue with change detection in the second one...

Regarding the first slider, as a workaround I have tried to disable the ripple, so that the user doesn't think that the thumb is dragging when it's not. But there is still the thumb label that can be misleading too.

Do you know if there is a simple way to disable the ripple and the thumb label when the user is dragging outside of the thumb? So that at least the user understands that the thumb won't move, and that he has to click on the thumb itself?

**Comment by wagnermaciel** [comment]
No, I don't think there's a workaround like that. I'll need to dig deeper into this to see how the ios slider behaves to know what the correct behavior is. The ripple is meant to reflect the focused state of the slider, so if it turns out that the ios slider is focused when the user clicks the track, the ripple should show (even if it doesn't let them drag for whatever reason)

I hope that's not the case. If it is, I'll raise this issue to the rest of the team to see if we can make an exception for not mirroring the exact behavior of the ios slider implementation

**Comment by jbgtmartin** [comment]
I think that's the case... When the user clicks the track on iOS, the slider is focused (the ripple shows, and the thumb label as well), but it's not draggable unless the finger is exactly on the slider thumb

**Comment by BButner** [comment]
Just jumping in here to confirm...

If I tap anywhere on the Slider on iOS, the slider thumb ripple effect appears. However, I am only able to drag **if I touch the thumb itself.**

So far every person in-house that we've had testing our web page has immediately noticed this regression with the Sliders.

**Comment by BButner** [comment]
@wagnermaciel Is there any workaround available for this, or maybe an ETA on a fix?

Just asking as I have a product I need to push an update to by the end of August, and this bug is one of my tickets. This is obviously not your problem, I'm not trying to instill a sense of urgency/rush you. More-so just looking for a potential timeline that I can report back.

If you need me to do any verification/testing/reproducing let me know and I'll get it to you ASAP.

Thanks!

**Comment by wagnermaciel** [comment]
I was able to make the behavior of the `mat-slider` slightly better on IOS compared to the native html slider by making it so that the value is _always_ updated on pointerdown on the slider track, not just if the pointerdown + pointerup event happen in quick succession

There's one annoying test failure that needs to be debugged so I'm not sure if this will land before tomorrow's release, but I will do my best to get this in as soon as possible :)

**Comment by BButner** [comment]
> I was able to make the behavior of the `mat-slider` slightly better on IOS compared to the native html slider by making it so that the value is _always_ updated on pointerdown on the slider track, not just if the pointerdown + pointerup event happen in quick succession
> 
> There's one annoying test failure that needs to be debugged so I'm not sure if this will land before tomorrow's release, but I will do my best to get this in as soon as possible :)

If it doesn't make it in before tomorrow's release, when is the next release that this would be in? Sorry, I'm not familiar with the release cycle here...

Either way, you're my hero 🥇

**Comment by wagnermaciel** [comment]
Haha thank you. We cut a new release every Wednesday so August 9th would be the next one if I miss tomorrow

**Comment by BButner** [comment]
@wagnermaciel Unfortunately even with this fix, it's not fixed enough to be able to close the ticket I have on my end in time. I've had to revert to using the deprecated legacy slider for the time being.

On my iPhone 13, in Safari, the slider was still only grabbable by the very small thumb. Pressing anywhere on the slider *did* update the value, but it was not automatically dragging.

Thanks for the effort, and I'll keep an eye out for future fixes!

**Comment by wagnermaciel** [comment]
Dang, I'm sorry to hear that. The problem is that this is the native behavior of the `<input type="range"` on IOS. This is what I meant when I initially wrote

> the new slider is built directly on top of the native html slider. While that has it's benefits, the downside is that the behavioral quirks of each independent browser implementation is going to be reflected in the mat-slider

**Comment by BButner** [comment]
Hey, no problem! I just really appreciate the quick responses and effort you put in! :)

In my short web experience, seems like iOS really likes to just make my life harder in the weirdest and most unnecessary ways...

**Comment by BButner** [comment]
@wagnermaciel Is there any chance of getting this issue re-opened? I'm running into another issue with the Legacy Sliders. When reverting back to the current slider implementation, when I press on the slider somewhere the thumb *does* move, but the bound value does not update. Happens on Safari and Edge on my iPhone.

**Comment by BButner** [comment]
@wagnermaciel Correct, but the actual dragging still seems to be in a regressed state. I can press somewhere on the slider and start dragging, however the thumb does not drag with me. It sticks to where I initially tapped down. Currently still the only way to drag the thumb is to drag the thumb itself, which is still somewhat difficult to consistently grab.
