### ISSUE TITLE
bug(slide-toggle): Component does not look like Material Design (icon inside).

### ISSUE THREAD

**Issue by infacto** [angular/components#27339]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

Tested on website with version menu 14.2.7.

### Description

I wonder why you didn't stick to the Material Design for the slide-toggle aka switches. Since you strictly reject any suggestions to improve these components in case of non-compliance with the Material Design. In this case, it's about the switch/toggle.

| Angular Material | Material Design |
| --- | --- |
|![image](https://github.com/angular/components/assets/60390085/0cf827e3-44cb-4b42-a448-20402f6d3ce0)|![image](https://github.com/angular/components/assets/60390085/59b9ecd8-e238-439e-a90a-457756550c1d)|
| https://material.angular.io/components/slide-toggle | https://m2.material.io/components/switches |

How to remove the icon? At least there should be an option to hide the icon. Or better vice versa (option to show). Maybe configure this global instead of each time.

Angular Material 14
![image](https://github.com/angular/components/assets/60390085/364130b8-fedc-41b7-9b1f-324a63c2171d)

### Reproduction

1. Try to implement M2 switches.
2. Checkout Angular Material slide-toggle.
3. Wonder why this component does not look like M2.

### Expected Behavior

Look like Material Design (M2).

### Actual Behavior

Does not look like Material Design.

### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s):Chrome latest
- Operating System: Windows 10

**Comment by andrewseguin** [comment]
The icon is for accessibility purposes and does match the spec provided by Material Design 3. You are referring to the Material Design 2 spec which was the old look. https://m3.material.io/components/switch/overview

**Comment by infacto** [comment]
@andrewseguin No thats not correct. 

Afaik M3 is implemented in web components [here](https://github.com/material-components/material-web) as mentioned in #7560. 

And even if you mix M2 and M3 - which is also not the MD way - you still didn't look like M3.

M2+M3+Custom Angular Material thing:
![image](https://user-images.githubusercontent.com/60390085/247492171-0cf827e3-44cb-4b42-a448-20402f6d3ce0.png)

M3:
![image](https://github.com/angular/components/assets/60390085/f0c4da97-11a3-46a0-88b9-b8e90bd3df15)

But anyway, as I see correctlay the recent pull request #27330 already fixes it for upcoming versions. Not yet tested...
