### ISSUE TITLE
bug(material/date-range-picker): placeholders for start and end show 'undefined'

### ISSUE THREAD

**Issue by quoctintran** [angular/components#27341]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello

If the placeholder of the start or the end of the date range picker is undefined, the control shows 'undefined' for the placeholder.

![image](https://github.com/angular/components/assets/22502986/91b69bde-2c29-4ac2-9fb6-0079625e322a)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/mrm9eu-q3oknm?file=src%2Fexample%2Fdate-range-picker-forms-example.ts
Steps to reproduce:
1. Click into the input control to focus
2. Undefined is showing (as an example only for the start)

### Expected Behavior

Display nothing or empty string

### Actual Behavior

Display 'undefined'

### Environment

- Angular: 16.1.1
- CDK/Material: 16.1.1
- Browser(s): Edge 114.0.1823.51 (Official build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 22H2 (OS Build 19045.2965)

**Comment by umernaeem217** [comment]
In the controller code, you are passing ```startPlaceholder = undefined;``` due to which it is showing you undefined. You can apply a conditional statement to make it an empty string.

**Comment by quoctintran** [comment]
@umernaeem217 yes, currently I would do that. But if I look at the code in [date-range-input.ts](https://github.com/angular/components/blob/798634ed5305745203b1a20f5519d9adb9ba07f5/src/material/datepicker/date-range-input.ts#L105C1-L109C4), the invention seems like that 'undefined' should not appear as a string. I guess that `_getPlaceholder()` already returns 'undefined'.

**Comment by crisbeto** [comment]
This is an issue with the consumer code, not with the date range picker. It's because it binds `undefined` directly to the native `placeholder` property of `HTMLInputElement` which then gets stringified. You can get it to work as you expect by using `[attr.placeholder]="placeholder"` instead.
