### ISSUE TITLE
Theme Not Applied for Legacy Components

### ISSUE THREAD

**Issue by ChelseaChilders** [angular/components#27345]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Not Applicable - Legacy Components Didn't Exist in Previous Versions

### Description

When using legacy buttons (by importing `MatLegacyButtonModule`) the theme is not being applied to the buttons as expected.
The theme is applied when not using legacy components (`MatButtonModule`).
However, I've read that the new MDC components are meant to be opt-in (when migrating my app, it automatically updated to use the legacy imports), so I think that having the theme not apply to legacy components would be an issue.
I've replicated the issue in this stackblitz: https://stackblitz.com/edit/f8rble-hjxjr7?file=src%2Fmaterial.module.ts.
If you switch the imports in `src/material.module.ts` from using legacy(`MatLegacyButtonModule`) to using MDC (`MatButtonModule`), you'll see the theme is applied for MDC components. If it's importing the legacy module, the theme is not applied.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/f8rble-hjxjr7?file=src%2Fmaterial.module.ts
If you switch the imports in `src/material.module.ts` from using legacy(`MatLegacyButtonModule`) to using MDC (`MatButtonModule`), you'll see the theme is applied for MDC components. If it's importing the legacy module, the theme is not applied.

### Expected Behavior

Theme to be applied in legacy components as they are in MDC components

### Actual Behavior

Theme is not applied to legacy component buttons

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS (also virtual? Stackblitz?)

**Comment by crisbeto** [comment]
It's because there are a different set of themes for the legacy components. Instead of `mat.all-component-themes`, you should include `mat.all-legacy-component-themes`.

**Comment by ChelseaChilders** [comment]
Ah, thank you. I assumed `all-component-themes` included legacy. Thank you for sharing `all-legacy-component-themes` with me.
