### ISSUE TITLE
bug(material/button): Button are not getting color custom in v16

### ISSUE THREAD

**Issue by lixaotec** [angular/components#27347]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

Dear folks,

Angular Material Button is not applying correctly the custom color for buttons.

If you create a button ex: mat-raised-button and tells color="green" and make the .mat-green {background-color: green} , it is been override by mdc .

To overcome I had to use !important

Do you confirm its a bug on this new verions? (v13 and prior did not happend)

![image](https://github.com/angular/components/assets/40803484/7490e5cb-5403-4e41-947a-4f4a1af09c4e)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

button should get custom color

### Actual Behavior

a transparency white keeps in button (the basic color because it did not respect order of my scss)

### Environment

- Angular: v16
- CDK/Material: v16
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
You can increase the specificity of your selectors in CSS to override the styles
