### ISSUE TITLE
DEV_ENVIRONMENT.md: add missing BAZEL_SH environment to mingwin's bash.

### ISSUE THREAD

**Issue by Anthony-Breneliere** [angular/components#27366]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Build and launch error following the DEV_ENVIRONMENT.md procedure

### Reproduction

I followed the DEV_ENVIRONMENT.md procedure to launch the dev-app.

```
# Developer guide: getting your environment set up
1. Make sure you have both `node` and `yarn` installed.
   We recommend using `nvm` to manage your node versions.
2. angular/components uses Bazel which requires certain Bash and UNIX tools.
   - On Windows: Follow the [instructions](https://docs.bazel.build/versions/master/install-windows.html#installing-compilers-and-language-runtimes)
   to install [`MSYS2`](https://www.msys2.org/) and the listed "Common MSYS2 packages".
   Afterwards add `C:\msys64\usr\bin` to the `PATH` environment variable.
3. Fork the `angular/components` repo on GitHub.
4. Clone your fork to your machine with `git clone`.
   Recommendation: name your git remotes `upstream` for `angular/components`
   and `<your-username>` for your fork. Also see the [team git shortcuts](https://github.com/angular/components/wiki/Team-git----bash-shortcuts).
5. From the root of the project, run `yarn` to install the dependencies.

To build angular/components in release mode, run `yarn build`. The output can be found under `dist/releases`.

To bring up a local server, run `yarn dev-app`. This will automatically watch for changes
and rebuild. The browser should refresh automatically when changes are made.
```

I deleted %userprofile%/_bazel_%username%, but I have the same error.

### Expected Behavior

dev-app launch successful

### Actual Behavior

I have the following error:

```
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: H:/projets/github/angular/components/tools/angular/BUILD.bazel:14:30: Bundling Javascript ../npm/node_modules/@angular/router/fesm2022/router.mjs [esbuild] failed: (Exit 127): _router_linked_bundle_esbuild_launcher.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\tools\angular\_router_linked_bundle_esbuild_launcher.bat --esbuild_args=bazel-out/x64_windows-fastbuild/bin/tools/angular/router_linked_bundle.args.json ... (remaining 2 arguments skipped)
/bin/bash: line 1: C:/users/antho/_bazel_antho/qrvuvg3m/execroot/angular_material/bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/tools/angular/_router_linked_bundle_esbuild_launcher.sh: No such file or directory
```

### Environment

node --version
v18.16.0
yarn --version
1.22.17
iBazel - Version v0.16.2
get-command ibazel
H:\Projets\GitHub\angular\components\node_modules\.bin\ibazel.cmd
bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
get-command bash  
Application     bash.exe                                           10.0.22... C:\Windows\system32\bash.exe

**Comment by Anthony-Breneliere** [comment]
> You might need to set an environment variable called BAZEL_SH to `C:\msys64\usr\bin\bash.exe`. Are you able to run any bazel commands?

That was it, thank you !

To complete the issue, that would be good to complete the DEV_ENVIRONMENT.md file as it is likely to have bash in c:\windows\system32 directory.

**Comment by robertIsaac** [comment]
> You might need to set an environment variable called BAZEL_SH to `C:\msys64\usr\bin\bash.exe`. Are you able to run any bazel commands?

this actually worked, thank you ❤️

**Comment by crisbeto** [comment]
Fixed in https://github.com/angular/components/pull/27643.
