### ISSUE TITLE
feat(COMPONENT): Design Tokens for Accessing Theme Colors as Variables

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#27362]
### Feature Description

I think it may be in the works with the Design Tokens feature, but figured I'd ask / request anyways.

This is it on Stackoverflow:

https://stackoverflow.com/questions/76544740/does-angular-material-have-css-token-variables-that-we-can-use-to-access-the-t

### Use Case

Angular 16 is introducing design tokens that we can use to customize component styles.

Are these available for all the theme colors?

I don't see them mentioned yet in the [Theme your own components with Angular Material's theming system](https://material.angular.io/guide/theming-your-components), so just curious if we are now able to do reference the theme colors at runtime?

Something like:

p {
   color: var(--mat-primary-default);
   background-color: var(--mat-primary-contrast-default);
}

**Comment by amysorto** [comment]
We are currently working on tokens, and that is meant to provide more granular control over components (like height, color, etc). 

I think what you are asking can be accomplished already if you follow this guide: https://material.angular.io/guide/theming-your-components#step-2-use-values-from-the-theme. You can grab color values from your theme and apply to it your own classes

**Comment by fireflysemantics** [comment]
Hi Amy,

I created another Feature Request where I explain it in more detail.
https://github.com/angular/components/issues/27369

We can currently grab theme color values, but it has to be done at compile time.  And so if we want to change a specific theme for the app, we have to recompile the application.  With design Tokens we can just change the colors and redeploy the theme only.  Hence we can skip having to recompile and redeploy the entire application.
