### ISSUE TITLE
bug(input matSliderThumb): dragEnd not working properly using touch (V15)

### ISSUE THREAD

**Issue by TheRealPingWin** [angular/components#27406]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

dragEnd output value doesn't update to the correct one, if dragged on mobile device or using firefox's responsive touch simulation.

### Reproduction

StackBlitz link: [](https://stackblitz.com/edit/angular-zsnfkb-ymxqxx?file=src%2Fapp%2Fprogress-spinner-overview-example.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fprogress-spinner-overview-example.ts) 
Steps to reproduce:
1. Use firefox's touch simulation or a mobile device
2. Drag the slider and the displayed value will not update as should with mouse

### Expected Behavior

dragEnd output should output the correct value.

### Actual Behavior

dragEnd output outputs the old value.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.1.2
- Browser(s): Firefox

**Comment by wagnermaciel** [comment]
@TheRealPingWin Could you provide a stackblitz link for the reproduction of the issue?

**Comment by wagnermaciel** [comment]
From what I can tell, this appears to be working as intended. The weird behavior you might be observing on firefox mobile could just be the behavior of the native html `<input type="range">` on that platform, which the new mat-slider is now built directly on top of
