### ISSUE TITLE
feat(html): How to host Angular Material fonts without internet or offline

### ISSUE THREAD

**Issue by fantasy0v0** [angular/components#27410]
### Feature Description

My operating environment does not have external network access, which causes the added links to be inaccessible.

<img width="693" alt="image" src="https://github.com/angular/components/assets/9549027/4b937392-5b16-41e4-a8bc-a590ae425d83">

### Use Case

By default, it can be used offline.

**Comment by crisbeto** [comment]
This isn't something we maintain, but there's more info here https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts.
