### ISSUE TITLE
mat-select: Angular mat-option multiple values

### ISSUE THREAD

**Issue by henafufa** [angular/components#27421]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have object looks like this

 allTransactionAccount = [
    { form_name: 'All Accounts', net_value: -145017687853.47995, vault_user_form_id: 0 },
    { form_name: 'Credit Card 363636363', vault_user_form_id: 18215, net_value: '-455.15' },
  ];

```
    <mat-form-field>
      <mat-select>
        <mat-option *ngFor="let account of allTransactionAccount" [value]="account.form_name">
          <div class="flex justify-between">
            <span>
              {{ account.form_name | truncateStrPipe : 25 }}
            </span>
            <span>
              {{ account.net_value | currency : 'USD' : true : '1.0-2' }}
            </span>
          </div>
        </mat-option>
      </mat-select>
    </mat-form-field>

```
As you see I set the value to account.form_name
I wanted to be only the form_name will be displayed when option item  get selected
but I am getting like both form_name and net_value like this
All Accounts - -145017687853.47995

I circled it with red 

<img width="299" alt="Screen Shot 2023-07-08 at 4 35 46 AM" src="https://github.com/angular/components/assets/37697829/94eb9f47-5710-45b3-a209-cec68b40bf63">

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I wanted to be only the form name get populated as value to mat-select,  and I wanted the net value to only show it the drop down.

When mat-option list selected I want form-name to get populated as it shown on picture

<img width="213" alt="Screen Shot 2023-07-08 at 4 40 54 AM" src="https://github.com/angular/components/assets/37697829/b913dfeb-e4e4-468e-99b3-0a6a3a8eb4db">

### Actual Behavior

<img width="299" alt="Screen Shot 2023-07-08 at 4 35 46 AM" src="https://github.com/angular/components/assets/37697829/6dea463e-47a0-4bcc-8a4c-c09251a80ff0">

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by henafufa** [comment]
Anything you can offer would be greatly appreciated, thanks!

**Comment by Gortyser** [comment]
This is not a bug but a question, better to ask it on StackOverflow.
However, you can customize the trigger/header with [mat-select-trigger](https://material.angular.io/components/select/overview#customizing-the-trigger-label) if I understand your problem correctly.

**Comment by henafufa** [comment]
Yeah you are right
Yes I get it with mat-select-trigger
Thanks, close for now, I will remove it
