### ISSUE TITLE
bug(Angular Material Chips): Setting up GM theme

### ISSUE THREAD

**Issue by palim1025** [angular/components#27420]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I would expect was that the following two snippets should have the same end-result. It seems to be the case for e.g. radio buttons but not for chips, specifically for chips rendered with appearance set to "hairline-suggestive".

```
@use 'third_party/javascript/angular_components/material' as mat;
@use 'javascript/angular2/components/gmat';

@include mat.chips-theme(mdc.$light-theme);
@include gmat.chips-theme(mdc.$light-theme);
```

```
@use 'third_party/javascript/angular_components/material' as mat;
@use 'javascript/angular2/components/gmat';

@include mat.chips-color($my-theme);
@include mat.chips-density($my-theme);
@include mat.chips-typography($my-theme);
@include gmat.chips-color($my-theme);
@include gmat.chips-density($my-theme);
@include gmat.chips-typography($my-theme);
```

### Reproduction

Stackblitz link: I could not figure out how to import GM themes into this framework

Steps to reproduce:
1. Compare hairline chips component rendered with both snippets for enabling GM theme
2. Notice that the appearance is different between the two different components:
<img width="364" alt="Screenshot 2023-07-07 at 4 27 56 PM" src="https://github.com/angular/components/assets/138937227/a0167f74-1135-4549-8b37-e4f021293deb">
<img width="357" alt="Screenshot 2023-07-07 at 4 28 42 PM" src="https://github.com/angular/components/assets/138937227/95abbaef-1bff-42fb-8785-bbc9a2829648">

A temporary fix was enabled by simply using `mat.chips-theme()`, as seen in the first snippet. However, as we move forward with enabling GM2 for the Angular Material Chips component, we need to move away from using `mat.chips-theme()` in order to customize Chips to comply with GM2 requirements.

### Expected Behavior

I expected to see the chip components to be rendered with the same appearance.

### Actual Behavior

Chips component does not render with the same appearance through using individual mixins vs `chips-theme` mixin.

### Environment

- Angular: v14+
- CDK/Material: v14+
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Please post g3-related questions on the internal channels, rather than on Github.
