### ISSUE TITLE
bug(expansion): expansion panel breaks when quickly closing panels using keyboard commands

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#27430]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a mat-expansion-panel has tabbable elements in it's panel content, the mat-expansion-panel will break if a user attempts to quickly close and tab away from a panel after closing (easily reproduced using space + tab)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/dgbfpa-3pq8m8?file=src%2Fexample%2Fexpansion-overview-example.html
Steps to reproduce:
1. Tab to the first expansion panel
2. Quickly try to close all of the expansion panels using keyboard commands (space + tab)

### Expected Behavior

You successfully close the expansion panels

### Actual Behavior

The expansion panels are closed but in a broken state

### Environment

- Angular: `16.1.1`
- CDK/Material: `16.1.4`
- Browser: `Chrome`
- Operating System: `macOs`

**Comment by kharazian** [comment]
Hello,

I'd like to know if someone is currently engaged with this task. If not, I'm ready to take a shot at it and work on the solution, pending your consent.

Thank you!
