### ISSUE TITLE
feat(MatDialog): Implement hide/show methods

### ISSUE THREAD

**Issue by pierophp** [angular/components#27448]
### Feature Description

This feature was previously discussed on #5162.

The proposed solution was to use the addPanelClass method to hide the dialog. But it doesn't work if you are using a backdrop. I built a [demo](https://stackblitz.com/edit/hide-md-dialog-with-backdrop?file=src%2Ftest%2Ftest.component.ts) to show the problem ([TestDialog01Component](https://stackblitz.com/edit/hide-md-dialog-with-backdrop?file=src%2Ftest-dialog-01%2Ftest-dialog-01.component.ts)).  There is no way to get the current overlay of the dialog to dispose of it manually  (See #15840).

I could find a workaround ([TestDialog02Component](https://stackblitz.com/edit/hide-md-dialog-with-backdrop?file=src%2Ftest-dialog-02%2Ftest-dialog-02.component.ts)) by not using the built-in backdrop and creating a custom overlay. But it feels too hacky.

The MdDIalog should have a built-in hide/show method or expose the overlayRef. 

If the team accepts it, I could implement it and send a PR.

### Use Case

I think in at least two use cases:

- An expensive operation to render the dialog.
- Using [Optimistic UI](https://uxplanet.org/optimistic-1000-34d9eefe4c05) to hide the modal as soon as the user clicks the button, but it needs to run some async operations that depend on each other, so you cannot destroy the modal until all the operations are complete (my use case).

**Comment by andrewseguin** [comment]
The solution here seems to be saving the data entered on the dialog so you can re-create it when the dialog is opened. I don't imagine we will add an API to hide the dialog without destroying it

**Comment by pierophp** [comment]
Hey @andrewseguin, what about exposing the  OverlayRef (#15840)? It would solve the problem as well.
