### ISSUE TITLE
docs-bug(Guide): Define a typography level

### ISSUE THREAD

**Issue by dtslvr** [angular/components#27449]
### Documentation Feedback

The documentation states that I can customize the font size via:

```
@use '@angular/material' as mat;

$my-custom-level: mat.define-typography-level(
  $font-family: Roboto,
  $font-weight: 400,
  $font-size: 1rem,
  $line-height: 1,
  $letter-spacing: normal,
);
```

How can I actually make use of `$my-custom-level`? It seems that this part is missing in the documentation.

### Affected documentation page

https://material.angular.io/guide/typography#define-a-level

**Comment by mmalerba** [comment]
I don't think the intent of the API was actually to let people create and use their own custom levels, it was to create a config that could be used as a custom configuration for one of the predefined levels (body-1, headline-4, etc.)

**Comment by amysorto** [comment]
Closing since the [theming guide](https://material.angular.io/guide/theming#customizing-your-typography) has been updated with information about typography.
