### ISSUE TITLE
bug(Clipboard): Copy to clipboard doesn't work in elem.requestFullscreen()

### ISSUE THREAD

**Issue by pstyrna** [angular/components#27447]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using document.element.requestFullscreen(), coping to clipboard through angular/cdk/clipboard doesn't work. It works fine using navigator.clipboard.writeText(). 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/zffwu2?file=src%2Fexample%2Fcdk-clipboard-overview-example.ts
Steps to reproduce:
1. Enter fullscreen by clicking "Open fullscreen" button
2. Click "Copy to clipboard button" 

### Expected Behavior

Text from text area to be copied to clipboard. 

### Actual Behavior

Nothing happens. 

### Environment

- Angular: 16.1.1
- CDK/Material: 16.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by zarend** [comment]
Assigning to @crisbeto for cdk/clipboard. I can reproduce with the provided stackblitz.

 - macOS 13.4.1 (c) (22F770820d)
 - Chrome Version 114.0.5735.198 (Official Build) (arm64)
