### ISSUE TITLE
bug(mat-form-field): unwanted border appears after mat-label.

### ISSUE THREAD

**Issue by liesahead** [angular/components#27469]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

When form field appearance is set to outline unwanted border appears at the end of `mat-label`. This happens only when field is focused.

I set the border color to red so you can see which element is at fault. By default it takes the primary color (screenshot 3).

![image](https://github.com/angular/components/assets/32300784/3308e3f4-73c4-4ea4-8c5f-e5540c3e7673)
![image](https://github.com/angular/components/assets/32300784/7f421a80-1d48-4753-8057-e5c7d3622e92)
![image](https://github.com/angular/components/assets/32300784/2d398627-a639-4a59-afd2-c66aace46b0a)
![image](https://github.com/angular/components/assets/32300784/421a3008-f528-4851-8198-2aebfba1c07a)

### Reproduction

The interesting this is I'm not sure why this happens because it works correctly in the `material` docs.

### Expected Behavior

No unwanted side-border

### Actual Behavior

Unwanted border is present

### Environment

Angular CLI: 16.1.4
Node: 18.14.0
Package Manager: npm 9.4.2
OS: win32 x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6

**Comment by vbraun** [comment]
Possibly related: https://github.com/angular/components/issues/26102

**Comment by liesahead** [comment]
@vbraun , indeed it is 👍🏼
