### ISSUE TITLE
bug(Input): @include mat.input-density(-2); has no effect

### ISSUE THREAD

**Issue by marc-wilson** [angular/components#27470]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

It doesn't appear that the density works for input elements. If you define your density in the core theme, it works. But, that's for all components. I want a specific density for only input components.

I am following the documentation here: https://material.angular.io/guide/theming#customizing-density

`@include mat.input-density(-2);` has no effect.

Drilling into some of the code, `mat.input-density` eventually calls an empty sass mixin:

**_input-theme.scss**
`@mixin density($config-or-theme) {}` 

I'm not entirely sure if the empty mixin is related, but following the code, that's where I end up.

Works:
```
$theme: mat.define-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      warn: $theme-warn,
    ),
    typography: mat.define-typography-config(),
    density: -2
  )
);

// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include mat.all-component-themes($theme);
```

Does not work:
```
$theme: mat.define-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      warn: $theme-warn,
    ),
    typography: mat.define-typography-config(),
    density: 0
  )
);

// Include theme styles for core and each component used in your app.
// Alternatively, you can import and @include the theme mixins for each component
// that you are using.
@include mat.all-component-themes($theme);
@include mat.input-density(-2); // <- Add custom density for inputs
```

### Reproduction

StackBlitz link: https://stackblitz.com/edit/cy5fh6?file=src%2Ftheme.scss,src%2Findex.html
Steps to reproduce:
1. Set custom density on input component using mat.input-density as outlined in the documentation
2. Observe there is no effect

### Expected Behavior

Custom density should reflect on the component it is set on.

### Actual Behavior

Density is not set.

### Environment

Angular CLI: 16.1.4
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.1.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@angular/cli                    16.1.4
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      4.9.5

**Comment by marc-wilson** [comment]
It looks like `mat.form-field-density(-3)` does things correctly. Maybe we are supposed to be setting density by way of form-field instead of input, select, etc...?

**Comment by crisbeto** [comment]
You're right, it's the form field that controls the density of the input. The input only has a `density` mixin for consistency with the rest of the library, but it's a noop.

**Comment by mmalerba** [comment]
Yep, its there for API consistency. If there are design spec changes at some point in the future that require adding density-dependent styles for input, they would go there, but currently its a no-op.

**Comment by marc-wilson** [comment]
It would be worth updating the documentation with this information as the current documentation is extremely lite around this subject.

I use webstorm, and webstorm doesn't want me doing anything with `mat.form-field-*`. I'm not entirely sure if this is specific to webstorm, some export issue, or the way I'm importing it. It only gives me options for 

<img width="648" alt="image" src="https://github.com/angular/components/assets/19480392/8cfbcb11-6807-40c4-ac04-7c2a86fcd928">


When I use `mat.form-field-*`, it does work, but webstorm gives me an error saying that it can't find the mixin.
<img width="511" alt="image" src="https://github.com/angular/components/assets/19480392/c6f861c6-eff5-4c2f-ad6b-82b0288c6580">

Just a little confusing how this is supposed to work when the only documentation mentioned is the snippet above. And that snippet creates a big assumption that any component can be set by `mat.component-name-theme/color/density/typography`. I also remember quite a big of head scratching when it came time to migrate all the components that fall under the form field umbrella to mdc.
