### ISSUE TITLE
bug(table): disable IOS elastic bounce scroll

### ISSUE THREAD

**Issue by fernandajuarez22** [angular/components#27489]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using mat-table with the first column and header sticky, the horizontal and vertical scroll shows a bounce effect.
I have tried to disable it using the property 'overscroll-behavior: contain' or 'overscroll-behavior: none' on the table tag, but I don't get any results. How can this behavior be prevented?

table css:
![image](https://github.com/angular/components/assets/126126519/b6a1cb48-49a4-4f9b-93af-306391a903fc)
bounce effect ios:
![IMG_FBED7579A73D-1](https://github.com/angular/components/assets/126126519/884b2050-52be-4b26-960e-50116d689882)

### Reproduction

-

### Expected Behavior

disable IOS elastic bounce scroll horizontal and vertical

### Actual Behavior

https://material.angular.io/components/table/examples#table-sticky-columns

### Environment

- Angular: 13.3.9
- CDK/Material: 13.3.9
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu): IOS Device

**Comment by wagnermaciel** [comment]
Hi, unfortunately this is not something that the material table supports. I'll also mention that adding custom css on top of our components is unsupported and will make your application very prone to breaking in future releases if & when the underlying structure of the component changes
