### ISSUE TITLE
bug(mat-menu): Doesn't follow document LTR/RTL directionality when changed

### ISSUE THREAD

**Issue by sksadri** [angular/components#27498]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

dynamically flipping the direction of a page does not trigger a change in menu direction. It's only set when the page/component is loaded the first time

### Reproduction

StackBlitz link: https://stackblitz.com/edit/hnmqis?file=src%2Fexample%2Fmenu-overview-example.ts
Steps to reproduce:
1. Hit the toggle button,  the menu stays with the initial page direction when it was rendered...
2. Add dir="rtl" to index.html and the same behavior is observed

### Expected Behavior

Menu should follow the document direction and flip direction too.

### Actual Behavior

menu stays as it is when it rendered the first time.

### Environment

- Angular: 16.1
- CDK/Material: 16.1
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
We don't support changing the direction dynamically but modifying the DOM, because of the performance implications of monitoring attribute changes in the entire tree. You should either make sure that the direction is set correctly up-front or do so through the `dir` directive.
