### ISSUE TITLE
docs-bug(DEV_ENVIRONMENT.md): missing step for `build-essential`

### ISSUE THREAD

**Issue by robertIsaac** [angular/components#27514]
### Documentation Feedback

the project will build, but test fails without running first `sudo apt update`, `sudo apt install build-essential`
it takes a bit of time through the logs to realize it's because of the missing `gcc`

FYI
1. I'm working from wsl (Ubuntu), it might not be required if using normal Ubuntu version
2. I can't even build in native windows, followed the instruction to install `msys2` and `bazel` but it's still failing, it will be nice if someone working from windows improved the documentation to help other people do it

### Affected documentation page

https://github.com/angular/components/blob/main/DEV_ENVIRONMENT.md

**Comment by Naaajii** [comment]
I can confirm this as-well, I had a hard time trying to run the project on Windows (I had given up in middle of it & just install dual-boot Ubuntu) too but I was able to pull it off not sure how - it was pretty straight forward in Ubuntu though. I will spend some time this weekend to update the document, #27366 also highlights this issue that document is kinda outdated.

**Comment by robertIsaac** [comment]
> I can confirm this as-well, I had a hard time trying to run the project on Windows (I had given up in middle of it & just install dual-boot Ubuntu) too but I was able to pull it off not sure how - it was pretty straight forward in Ubuntu though. I will spend some time this weekend to update the document, #27366 also highlights this issue that document is kinda outdated.

that was actually very helpful, I managed to make it work
