### ISSUE TITLE
bug(mat-slider): When changing max value of mat-slider the input positions are not rendered correctly.

### ISSUE THREAD

**Issue by PRGWITHSTYLE** [angular/components#27513]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Not sure

### Description

When an observable is pushing a change to the max value of the slider the position of the slider thumbs is not correctly re-rendered.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. [Example](https://stackblitz.com/edit/k5rb3t?file=src%2Fexample%2Fslider-range-example.ts,src%2Fexample%2Fslider-range-example.html,src%2Fexample%2Fslider-range-example.css)
2.  Clearer example [Example 2](https://stackblitz.com/edit/k5rb3t?file=src%2Fexample%2Fslider-range-example.html)
3.  You can see in the above example that for some reason the lower value is not set and stays at the min value?

### Expected Behavior

The position of the slider would render correctly when pushed a new max value.

### Actual Behavior

The slider is rendered incorrectly

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by PRGWITHSTYLE** [comment]
Could anyone provide me a workaround?

**Comment by biswasSaumyadip** [comment]
> Could anyone provide me a workaround?

The issue is with the lower thumb, right?

**Comment by dbitkovski** [comment]
@PRGWITHSTYLE you should use initialization value, for example via `startWith`. The important thing here is that your `higherValue` must be greater than next `lowerValue`. For your case initialization value might be `{ higherValue: 501, max: 501 }`.

Each `matSliderTab` sets limits (min and max). When you initialize the slider with nulls, it takes `0` by default. So `matSliderStartThumb` has `min=0` and `max=0`. Next time the stream emits `{ lowerValue: 500, higherValue: 700, max: 2000 }`. `matSliderStartThumb` tries to apply `500` but it's maximum is `0` so it can't do anything but set it to 0.

**Comment by wagnermaciel** [comment]
+1 to what @dbitkovski said - you should double check the order the min, max, and values are being updated in - but also none of the subsequent updates are actually updating the `lowerValue` and `higherValue`. If you print them on the page, you can see that the values are not changing

https://stackblitz.com/edit/k5rb3t-wbmjrm?file=src%2Fexample%2Fslider-range-example.html

**Comment by PRGWITHSTYLE** [comment]
Lower and higher values do not matter for this issue, the fundamental issue is that the max value changes and the position of High and low on the slider are not moving accordingly based on the new max value

**Comment by dbitkovski** [comment]
@PRGWITHSTYLE they do.
>  Next time, the stream emits { lowerValue: 500, higherValue: 700, max: 2000 }. matSliderStartThumb tries to apply 500 but its maximum is 0, so it can't do anything but set value to 0.

Add `startWith({ higherValue: 700, max: 2000 })` to your stream and it will work fine because `matSliderStartThumb.max` will be `700`, not `0`
