### ISSUE TITLE
cdkScrollable is working but its scroll-bar is not visible in IPAD Device and Iphone Devices.

### ISSUE THREAD

**Issue by Abdullah-Haroon004** [angular/components#27526]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The Scrolling feature is working on IPAD Devices as well as the drag-and-drop item scroll. But the scrollbar is not visible in IPAD and iPhone Devices. 

Note: Apart from IPAD and Iphone Devices it’s working fine on every device. Even in MaC, it’s working fine.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Scroll-bar should show on IPAD

### Actual Behavior

Scroll-bar is not visible in IPAD.

### Environment

- Angular: 14.2
- CDK/Material: 14.2.3
- Browser(s): Safari & Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): iOS

**Comment by wagnermaciel** [comment]
Hi, unfortunately this is the native behavior of iOS, not something we have implemented or plan on working around
