### ISSUE TITLE
bug(Chips): Focus stays on previously selected chip on Safari

### ISSUE THREAD

**Issue by GreedyA1** [angular/components#27544]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14.2.7

### Description

V16

https://github.com/angular/components/assets/18186211/cc3f6a61-3f11-4921-8ad3-e57592549c9a

v14 (Expected Behaviour)

https://github.com/angular/components/assets/18186211/4f323acf-5f51-4e4d-b3a3-2fafd8cbfed5

### Reproduction

https://stackblitz.com/edit/s3j16l?file=src%2Fexample%2Fchips-overview-example.html

* open with safari
* click on chips 

### Expected Behavior

when new chip is clicked the focus should not be focused (gray)

MDC components doesn't have this issue on safari

https://stackblitz.com/edit/js-nkxcgf?file=index.js,index.html,style.css,index.scss,package.json

https://github.com/angular/components/assets/18186211/fa90d8a0-4192-4b61-8da1-cedf12d6294b

https://github.com/angular/components/assets/18186211/6c1c6501-2659-47d1-9e09-bb03ad5bb174

### Actual Behavior

previously clicked chip will stay focused

### Environment

- Angular:
- CDK/Material:
- Browser(s): Safari
- Operating System: MacOS, IOS

**Comment by andrewseguin** [comment]
Confirmed that the focus stays on the previous chip only in Safari 

https://stackblitz.com/edit/s3j16l-j1xegl?file=src%2Fexample%2Fchips-overview-example.html,src%2Fexample%2Fchips-overview-example.ts
