### ISSUE TITLE
bug(chips): text input in mat-chip-row prevent space key usage

### ISSUE THREAD

**Issue by dams-dev** [angular/components#27549]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Problem description :
When a text input is used into a mat-chip-row it's not possible to use the space key.

Cause :
Usage of matChipAction in chip-row.html prevent space usage.

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/rchveu-hjsuvg?file=src%2Fexample%2Fchips-autocomplete-example.html
Steps to reproduce:
1.  update first code sample from this url : https://material.angular.io/components/chips/examples
2. add input element under *fruit" binding : 
<mat-chip-row *ngFor="let fruit of fruits" (removed)="remove(fruit)">
        {{fruit}}
  <input type="text">
  <button matChipRemove [attr.aria-label]="'remove ' + fruit">
    <mat-icon>cancel</mat-icon>
  </button>
</mat-chip-row>

### Expected Behavior

Expect to be able to use space key.

### Actual Behavior

not able to use space key

### Environment

- Angular: 16.1.6
- CDK/Material: 16.1.6
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Nesting inputs like this inside of chip rows isn't supported. If you're building editable chips, you can use either the `editable` input ([example](https://material.angular.io/components/chips/examples#chips-input)) or project a `matChipEditInput`.
