### ISSUE TITLE
bug(dialog): document has RTL but dialog rendering LTR

### ISSUE THREAD

**Issue by Kumaresan-Periyasamy** [angular/components#27592]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular dialog opened with LTR even thought the document is mentioned as RTL.
![image](https://github.com/angular/components/assets/106318318/c0dc72ac-c63c-4003-ab29-4ab4ebd7fb45)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/hg55pw
Steps to reproduce:
1. default app will render with RTL direction
2. click on 'Pick one' button and the popup is render with LTR direction.

Step 1:
![image](https://github.com/angular/components/assets/106318318/4c91dcb7-e04c-4cf1-891a-8e257464285b)

Step 2:
![image](https://github.com/angular/components/assets/106318318/fe09db11-a27a-482c-8cc3-a51a9303513b)

### Expected Behavior

Dialog should render with RTL direction.

### Actual Behavior

Dialog should render with LTR direction.

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Naaajii** [comment]
You can set the direction of dialog when opening it btw.

![image](https://github.com/angular/components/assets/54370141/3f592893-65ae-4a40-a853-199b8db1ea65)

**Comment by Kumaresan-Periyasamy** [comment]
@Naaajii thank you.
