### ISSUE TITLE
bug(mat-progress-bar): starts from the middle when put in a button

### ISSUE THREAD

**Issue by schiemon** [angular/components#27598]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When putting a `mat-progress-bar` in `indeterminate`-mode inside a button, the progress bar starts animating at around 50% instead of at 0% (so completely from the left).

https://github.com/angular/components/assets/56340221/955a78de-27d1-4db1-b4a7-676b93b8577c

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-fhpfas?file=src%2Fmain.ts%3AL11,angular.json
Steps to reproduce:
1. Refresh the app.
2. Take note of the animation starting points of the progress bars.

### Expected Behavior

The progress bar should start animating from the left as it does in a `div`.

### Actual Behavior

The progress bar starts animating from around the middle.

### Environment

- Angular: 16.1.8
- CDK/Material: 16.1.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by amysorto** [comment]
Progress bars are not meant to be interactive elements so putting progress bars in buttons is not supported. I would highly recommend not following this pattern, especially since this isn't an accessibility pattern.
