### ISSUE TITLE
bug(drag-and-drop): Scrolling a parent container while dragging an item breaks placeholder/dropspot position

### ISSUE THREAD

**Issue by conner-fallone** [angular/components#27604]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using drag-and-drop without scroll (but some parent is scrollable), the drag placeholder seems to get out of sync with the cursor when you scroll while dragging. 

### Reproduction

https://stackblitz.com/edit/d1tv4h-4a6ghz?file=src%2Fapp%2Fcdk-drag-drop-custom-placeholder-example.html
Steps to Reproduce:
1. Start dragging an item 
2. Scroll down, and notice the item's placeholder/dropspot is now out of sync with the cursor

### Expected Behavior

The placeholder/dropspot for dragging should always match where the user's cursor is

### Actual Behavior

The placeholder/dropspot for dragging becomes out of sync with the user's cursor when scrolling while dragging. When dropping at the cursor, the item doesn't drop in that place.

### Environment

- Angular: 15
- CDK/Material: 15.2.9
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
You have to set `cdkScrollable` on the scrollable container so the CDK knows that it's being scrolled. Here's a working example: https://stackblitz.com/edit/d1tv4h-jimys6?file=src%2Fapp%2Fcdk-drag-drop-custom-placeholder-example.html
