### ISSUE TITLE
bug(mat-slider): thumb label affected by parent word-break

### ISSUE THREAD

**Issue by gpaimla** [angular/components#27612]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Upgraded to mdc based components and the sliders thumb label started looking like this: 
![image](https://github.com/angular/components/assets/14272566/9bf8703d-8e00-43ed-87d8-fb433658b180)
found out the culprit to be a word-break: break-word; on one of the parent divs, not sure if this is intended

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-okzuyh?file=src%2Fapp%2Fexample-component.html
Steps to reproduce:
1. move slider thumb

### Expected Behavior

slider thumb label shouldn't break on any parent having word-break

### Actual Behavior

slider thumb label inherits word-break

### Environment

- Angular: 15.2.4
- CDK/Material: 15.2.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Vidhanvyrs** [comment]
hey @gpaimla  I am happy to have a look at it and try to resolve it
