### ISSUE TITLE
bug(CDK drag and drop): animations inside of droped items

### ISSUE THREAD

**Issue by Arktiswind** [angular/components#27610]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We have some sortable lists. For them the sorting is deactivatable. So we added some angular animations to the containers to make them appear/disappear smother. 
But after dropping an item the animations aren't shown or are buggy.
1. try with *ngif on the actions container -> container is not removed, animation is not running, container is doubled on reappear
2. try with an animation to width 0 -> container is removed, animation is not running on disappear, is running again after that

(the stackblitz really helps here^^)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-fcr4rv?file=src%2Fapp%2Fexample-component.ts
Steps to reproduce:
1. click the toggle button -> drag buttons appear with animation
2. move item 1 in the top list to last position
3. click the toggle button
- in the top list the drag button disappears without animation
- in the bottom list it doesn't disappear
4. click the toggle button again
- top list works as expected again
- bottom list has two action containers on item 1

### Expected Behavior

animations are running as intended and *ngif is working and not doubling its container

### Actual Behavior

animations aren't working
*ngif doubles its container

### Environment

- Angular: 16.1.5 / 15.2.4
- CDK/Material: 16.1.5 / 15.2.5
- Browser(s): chrome, edge, firefox
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
I believe this is caused by the following issue in the Animations package: https://github.com/angular/angular/issues/18847.
