### ISSUE TITLE
Migration from mat-contrast in Angular 14 to Angular 16 not possible

### ISSUE THREAD

**Issue by atuzovic** [angular/components#27649]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

In Angular 14, it was possible to do the following:

`mat-contrast($primary-palette, $notice-bg-hue);
`

$notice-bg-hue is variable that holds hue value, e.g. 500.
So with mat-color and mat-contrast it was possible to get color value for both 500 and 500-contrast from same variable.

However, with mat.get-color-from-palette it is not possible to do this if hue is stored within variable.
I understand that you can type:
mat.get-color-from-palette($primary-palette, 500);
and
mat.get-color-from-palette($primary-palette, '500-contrast');

But that is not real reproduction of previous mat-contrast implementation.

It would be logical to have something like mat.get-contrast-from-palette, but I can't seem to find any documentation on that.

Is there a way to do this properly?

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

It should be possible to get contrast color from hue value stored in variable.
Adequate replacement for mat-contrast should exist.

### Actual Behavior

Replacement for mat-contrast is not available.

### Environment

- Angular: 16.2.0
- CDK/Material: 16.2.0
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by zarend** [comment]
Hello,

I believe that `mat-contrast` is from version 12.

This is the implementation of `mat-contrast` that I found when looking at the source code for version 12.0.0.

```
// For a given hue in a palette, return the contrast color from the map of contrast palettes.
// @param $color-map
// @param $hue
@function mat-contrast($palette, $hue) {
  @return map-get(map-get($palette, contrast), $hue);
}
```

I think what you're looking for is `mat.get-contrast-color-from-palette`. Does that provide you what you need?

Best regards,

Zach

**Comment by atuzovic** [comment]
@zarend  Yes, that was exactly what I was looking for, thanks!

It would be very useful if that is mentioned on this page of documentation:
https://material.angular.io/guide/theming

I spent quite of lot of time searching for it, but clearly without success.

Thank you once more, you can close the issue as it has been resolved. :)
