### ISSUE TITLE
bug(Paginator): MatPaginatorIntl returns changes is undefined error

### ISSUE THREAD

**Issue by EswarBalasubramanian** [angular/components#27645]
### Description

The MatPaginatorIntl provided in our library component's module.ts file in useFactory returns a console error on loading a mat table as "Cannot read properties of undefined (reading 'changes')" in markup.

### Possible Solutions

1. The custom matPaginatorIntl should not return undefined for the changes property.
2. The useFactory method should check for undefined before returning the custom matPaginatorIntl.

### Reproduction

Steps to reproduce:
    1. Install the library component.
    2. Import the library component into your project.
    3. Create a mat table.
    4. Set the mat table's paginator intl to the custom matPaginatorIntl returned by the useFactory method.
    5. Load the mat table

### Expected Behavior

The mat table should load without any errors.

### Actual Behavior

The mat table loads with the following console error:

Cannot read properties of undefined (reading 'changes')

### Environment

- Angular: 16.1.4
- CDK/Material: 16.1.4
- Node Version: 18.16.0
- Browser(s): Google Chrome, Firefox, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 pro

**Comment by crisbeto** [comment]
Can you post the code that provides `MatPaginatorIntl`?

**Comment by EswarBalasubramanian** [comment]
`
// customPaginatorIntl.service.ts

import { Injectable } from "@angular/core";
import { MatPaginatorIntl } from "@angular/material/paginator";
import { TranslateService } from "@ngx-translate/core";

@Injectable()
export class CustomMatPaginatorIntl extends MatPaginatorIntl {

  constructor(private readonly translate: TranslateService) {
      super();
  }
/* The translation code MX_AC_COMMON.COMMON_HOME is a key to a translation in a JSON file that will be loaded by the translateService.instant() method and returned as the translated text for the current language of the application */
  itemsPerPageLabel = this.translate.instant('MX_AC_COMMON.COMMON_HOME');

  getRangeLabel = function (page, pageSize, length) {
    if (length === 0 || pageSize === 0) {
      return '0 od ' + length;
    }
    length = Math.max(length, 0);
    const startIndex = page * pageSize;
    // If the start index exceeds the list length, do not try and fix the end index to the end.
    const endIndex = startIndex < length ?
      Math.min(startIndex + pageSize, length) :
      startIndex + pageSize;
    return startIndex + 1 + ' - ' + endIndex + ' / ' + length;
  };
}



// library-table.module.ts
...
imports: {
...
MatPaginatorModule,
MatTableModule,
...
}
...
// Tried both ways individually
providers: [
{
        provide: MatPaginatorIntl,
        deps: [TranslateService],
        useFactory: (translateService: TranslateService) =>
          new CustomMatPaginatorIntl(translateService),
},
{
        provide: MatPaginatorIntl, 
        useClass: CustomMatPaginatorIntl, 
        deps: [TranslateService]
}
]
...
`

**Comment by wagnermaciel** [comment]
Confirmed that the paginator internationalization example is broken

https://stackblitz.com/edit/7z5abz?file=package.json

**Comment by vsarangan** [comment]
Do we have any solution for this issue?
