### ISSUE TITLE
bug(MatAutocomplete): Resetting form still shows previous selected item

### ISSUE THREAD

**Issue by drberg** [angular/components#27652]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Resetting a form with autocomplete gives a visual impression that item is still selected.

I thought the fix from https://github.com/angular/components/issues/26761 would solve my issue, but unfortunately it persisted after updating.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/zdy1sg

Steps to reproduce:
1.  Open autocomplete.
![image](https://github.com/angular/components/assets/9393538/cfceb407-06b2-4087-ad76-3ac5d98945ea)
2.  Click 'Two'.
![image](https://github.com/angular/components/assets/9393538/4660b8b6-10be-4a58-912f-dfa92fa41dd1)
3.  Click 'Reset selection'. Notice that the input box is now empty.
![image](https://github.com/angular/components/assets/9393538/c119034b-1096-442d-9b8c-fed76384a732)
4. Open autocomplete again and observe that 'Two' is still marked as selected even though the value is not set in the form any more.
![image](https://github.com/angular/components/assets/9393538/18f53434-0e90-4c7a-9ca2-c75a8d1524db)

### Expected Behavior

I expected the selection list not to show any selected items when the form is reset.

### Actual Behavior

Previous selected item appears selected when it's not in the form.

### Environment

- Angular: 16.2.0
- CDK/Material: 16.2.0
- Browser(s): Edge and Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by RobinBomkamp** [comment]
Facing the same issue.
