### ISSUE TITLE
stepControl goes ahead even though the form is invalid

### ISSUE THREAD

**Issue by D4v1dMoDz** [angular/components#27650]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I created this mini project to test out a structure I had in mind for a project. I created a mat-stepper and dynamically create the steps with an ngFor which iterates on a list of type 'Step' which contains a property of type FormGroup which I pass to the stepControl of the step. The problem is both statically and dynamically the stepControl doesn't work, because as I said before, the stepper continues despite the invalid form.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-m4gc7y

### Expected Behavior

The step does not continue to the second step

### Actual Behavior

The step continues to the second step despite the invalidity of the step

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
Hello,

Thank you for reaching out.

> The step continues to the second step despite the invalidity of the step

To make the stepper "linear", provide the linear Input.

```
<mat-stepper [linear]="true">
```

For more information, see documentation of linear stepper at https://material.angular.io/components/stepper/overview#linear-stepper.

Best regards,

Zach

**Comment by D4v1dMoDz** [comment]
> Hello,
> 
> Thank you for reaching out.
> 
> > The step continues to the second step despite the invalidity of the step
> 
> To make the stepper "linear", provide the linear Input.
> 
> ```
> <mat-stepper [linear]="true">
> ```
> 
> For more information, see documentation of linear stepper at https://material.angular.io/components/stepper/overview#linear-stepper.
> 
> Best regards,
> 
> Zach

Oh thank you very much. I didn't notice, I thought it was set automatically in the presence of stepControl. Sorry for the disturbance!
