### ISSUE TITLE
bug(material/chips): Multiple CDK Focus classes

### ISSUE THREAD

**Issue by mazhar-fis** [angular/components#27660]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When we have cdk focus classes on close button of chips, the cdk focus classes on parent chip does not get removed.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/ginjja?file=src%2Fexample%2Fchips-form-control-example.ts
Steps to reproduce:
1. Navigate to chip using Tab Key
2. Navigate to chip's close icon using Tab Key

### Expected Behavior

When close icon is tabbed, cdk classes on parent chip should be removed.

### Actual Behavior

When close icon is tabbed, cdk classes on parent chip also stay. Hence seeing double focus styles and chip as well as close icon.

### Environment

- Angular: 16
- CDK/Material: 16.2.0
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is currently working as expected. Also worth noting that the focused classes are an internal implementation detail, not a public API.

**Comment by mazhar-fis** [comment]
We have a private exhaustive UI framework on top of Angular Material Library which is used throughout a large MNC. Inside that we are overriding default focus style with our custom styles (golden border on focus item). That's when it's causing issue of double focus styles i.e. on chip as well as close button.

Can you reconsider the default expectation @crisbeto ?
