### ISSUE TITLE
bug(COMPONENT): MatRadioButton

### ISSUE THREAD

**Issue by Anzil-Aufait** [angular/components#27680]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

Click event is firing twice when clicking on the radio label text. The issue is only happening when clicking on the label text.

The event will only fire once when clicking on the radio control element.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/jephxf?file=src%2Fexample%2Fradio-overview-example.css
Steps to reproduce:
1. Just click on the radio label text.
2. And open the inspector and check the console log. You will get the logged value from the click event.

### Expected Behavior

The event should fire only once.

### Actual Behavior

When clicking on the radio label text the event is firing twice.

### Environment

- Angular: 16.2.1, 15.2.9
- CDK/Material: 16.2.1, 15.2.9
- Browser(s): Chrome, Firefox.
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is the native browser behavior, not something coming from Material. In general we don't address cross-browser differences like this unless they affect the user experience.
