### ISSUE TITLE
bug(Theming): After updating to Material 15 theming no longer works

### ISSUE THREAD

**Issue by daniel-agouveia** [angular/components#27694]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello, everyone, In Material 14 we created our theme file like this:

```
@import '@angular/material/theming'

$primary: mat-palette($mat-grey)
$accent: mat-palette($mat-blue-grey, A200, A100, A400)
$warn: mat-palette($mat-red)

$theme: mat-light-theme($primary, $accent, $warn)

@include angular-material-theme($theme)
```
Our CSS files are in Sass and knowing Angular Material's theming APIs are built with Sass, I thought no issues would happen after the update, but every time we change the theme file to the following:

@use '@angular/material' as mat

@include mat.core()

$primary: mat.define-palette(mat.$mat-grey)
$accent: mat.define-palette(mat.$mat-blue-grey, A200, A100, A400)
$warn: mat.define-palette(mat.$mat-red)

$theme: mat.define-light-theme((
 color: (
   primary: $primary,
   accent: $accent,
   warn: $warn
 ),
 typography: mat.define-typography-config()
))

@include mat.core-theme($theme)

We get the following error:

SassError: expected ")".
  ╷
9 │ $theme: mat.define-light-theme((

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Create a project with Angular 15.2.9 and Material 15.2.9
2. Create a Sass file to define the theme
3. Try to run the project

### Expected Behavior

The theme would be applied no error should be thrown.

### Actual Behavior

The error SassError: expected ")".
  ╷
9 │ $theme: mat.define-light-theme((

Happens

### Environment

- Angular: 15.2.9
- CDK/Material: 15.2.9
- Browser(s): Brave
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
It looks like you're missing semicolons in a few places. Does this work?

```
@use '@angular/material' as mat;

@include mat.core();

$primary: mat.define-palette(mat.$mat-grey);
$accent: mat.define-palette(mat.$mat-blue-grey, A200, A100, A400);
$warn: mat.define-palette(mat.$mat-red);

$theme: mat.define-light-theme((
  color: (
    primary: $primary,
    accent: $accent,
    warn: $warn
  ),
  typography: mat.define-typography-config()
));

@include mat.core-theme($theme);
```

**Comment by daniel-agouveia** [comment]
I can't add semicolons to a Sass file since it uses indentation instead of curly braces and semicolons to describe the format of the document. It will also through an error do to the semicolons.

**Comment by crisbeto** [comment]
Either way this looks like a syntax error somewhere in your theme file, not an issue in Material.

**Comment by daniel-agouveia** [comment]
Okay, thank you I will look at this but nothing on the syntax seems wrong, I even copied and pasted what was on the theming tutorial in the material website, and still didn't work, and all I did was remove the semicolons they have. Which is this:

```
@use '@angular/material' as mat;

$my-primary: mat.define-palette(mat.$indigo-palette, 500);
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);

// The "warn" palette is optional and defaults to red if not specified.
$my-warn: mat.define-palette(mat.$red-palette);

$my-theme: mat.define-light-theme((
 color: (
   primary: $my-primary,
   accent: $my-accent,
   warn: $my-warn,
 ),
 typography: mat.define-typography-config(),
 density: 0,
));
```

**Comment by crisbeto** [comment]
The theming tutorial uses the .scss syntax, not the indetation-based one which might have some other differences.

**Comment by daniel-agouveia** [comment]
I Changed my syntax to $my-theme: mat.define-light-theme((color: (primary: $my-primary,accent: $my-accent,warn: $my-warn),typography: mat.define-typography-config(),density: 0)) so the theme is declared to one line only and fixes the issue
