### ISSUE TITLE
Angular material components use as webComponents

### ISSUE THREAD

**Issue by YJPrakash** [angular/components#27695]
### Feature Description

Templating using newly created web components. If it is run in the server using ngUniversal Express Engine render components from different html work as like as index.html. ie (looks like an Ejs template engine model)

### Use Case

Please refer
 [Is there a way to implement all material components and directives themselves act as web components using createCustomElements?](https://stackoverflow.com/questions/71464589/is-there-a-way-to-implement-all-material-components-and-directives-itself-act-as)

It's more specifically to templating fast like Ejs in Nodejs server-side rendering.

**Comment by crisbeto** [comment]
We don't currently have any plans to ship Angular Material as web components. They should work if you provide them through Angular Elements yourself though.
