### ISSUE TITLE
bug(MatDialog): stuttery animation and dropped frames while resizing browser while using 100% width

### ISSUE THREAD

**Issue by Siddhu-K** [angular/components#27706]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I wanted to have the mat dialog take the maximum width available so I am using { width: '100%' } while opening the dialog. However, I am having issues while resizing the browser window.

`openDialog() {
    this.dialog.open(DialogElementsExampleDialog, { width: '100%' });
}`

### Reproduction

StackBlitz link: https://stackblitz.com/edit/gdlxuq-mwqccp?file=src%2Fexample%2Fdialog-elements-example.ts
Steps to reproduce:
1. open the dialog and resize the browser window. Inspect with dev tools

### Expected Behavior

dialog resizes smoothly

### Actual Behavior

The animation is not smooth when I resize the browser window and chrome dev tools shows dropped frames

### Environment

Angular CLI: 16.2.0
Node: 18.12.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.0
@angular-devkit/build-angular      16.2.0
@angular-devkit/core               16.2.0
@angular-devkit/schematics         16.2.0
@angular/cdk                       16.2.1
@angular/cli                       16.2.0
@angular/material                  16.2.1
@angular/material-moment-adapter   16.2.1
@schematics/angular                16.2.0
rxjs                               7.8.1
typescript                         5.1.6
zone.js                            0.13.1

**Comment by crisbeto** [comment]
In general we don't address issue like this because users don't resize their browsers, and even if they did, this isn't breaking the experience for them.
