### ISSUE TITLE
mat-legacy-checkbox: inline style="display: none" breaks csp

### ISSUE THREAD

**Issue by work933k** [angular/components#27719]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are working on making our code-base Content Security Policy compliant. Unfortunately the mat-legacy-checkbox makes use of inline-styles which our CSP-policy blocks. 
https://github.com/angular/components/blob/16.0.x/src/material/legacy-checkbox/checkbox.html#L44

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Angular Material components to be CSP compliant

### Actual Behavior

An console error is triggered.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is a valid issue, but I'm closing it because the legacy components are no longer supported.
