### ISSUE TITLE
bug(Angular Google Maps): fitBounds north > 85 is causing a grey area

### ISSUE THREAD

**Issue by ssalveMobiltex** [angular/components#27710]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the fitbounds method to fit the markers, it is causing a grey area when the bounds.north > 85

eg.

public fitBounds(bounds: google.maps.LatLngBoundsLiteral): void {
    bounds.north = 89.14;
    this.map.fitBounds(bounds);
  }

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Grey area should not be seen

### Actual Behavior

Grey area at top is seen.

![image](https://github.com/angular/components/assets/123488872/48383acb-91d9-4acd-97d6-149210c7d756)

### Environment

- Angular:
- CDK/Material:      15.2.8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We can't do much about this since it looks like an issue with Google Maps itself.
