### ISSUE TITLE
bug(COMPONENT): TITLE

### ISSUE THREAD

**Issue by narayansinghjai** [angular/components#27732]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Im using mat-tab to display multiple tabs and im using @angular material 14.2.7
code:
<mat-tab-group (selectedTabChange)="selectedYearHandler($event)"
               [selectedIndex]="selectedYearIndex">
  <mat-tab *ngFor="let option of yearList">
    <ng-template mat-tab-label>
      {{option}}
    </ng-template>
  </mat-tab>
</mat-tab-group>

 public yearList: number[] = [2021, 2022, 2023];
 
 by default on ngonit it is selecting the first index i do not want to select the first index by default
 
 if i pass  selectedYearIndex to 1 it is selecting 2022 
 
 but when passing selectedYearIndex to -1 it selects the 2021 

the expected behaviour should be it should not select any of the tabs right?

kindly provide solution for this  prevent selecting of first index if i pass selectedYearIndex to -1

### Reproduction

StackBlitz link: 
Steps to reproduce:
Im using mat-tab to display multiple tabs and im using @angular material 14.2.7
code:
<mat-tab-group (selectedTabChange)="selectedYearHandler($event)"
               [selectedIndex]="selectedYearIndex">
  <mat-tab *ngFor="let option of yearList">
    <ng-template mat-tab-label>
      {{option}}
    </ng-template>
  </mat-tab>
</mat-tab-group>

 public yearList: number[] = [2021, 2022, 2023];
 

### Expected Behavior

  
 
 if i pass  selectedYearIndex to 1 it is selecting 2022 
 
 but when passing selectedYearIndex to -1it is selecting 2021

### Actual Behavior

 on ngonit it is selecting the first index i do not want to select the first index by default

### Environment

- Angular:14
- CDK/Material: 14.2.7
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

@crisbeto

**Comment by crisbeto** [comment]
Does this happen on Angular 16?

**Comment by narayansinghjai** [comment]
> Does this happen on Angular 16?

@crisbeto i haven't tried in angular 16

**Comment by wagnermaciel** [comment]
@narayansinghjai Please provide a stackblitz reproduction. I was unable to reproduce this locally

**Comment by narayansinghjai** [comment]
> @narayansinghjai Please provide a stackblitz reproduction. I was unable to reproduce this locally

https://stackblitz.com/edit/angular-tddtq9-3q6ta1?file=src%2Fapp%2Ftab-group-basic-example.ts,src%2Fapp%2Ftab-group-basic-example.html

if i set selectedIndex to -1 it is selecting first tab if i set to positive numbers it is selecting the particular index
if i set the index out of range it is selecting the last tab

please provide solution for this

**Comment by crisbeto** [comment]
We don't support setting the `selectedIndex` to -1. For accessibility purposes there always has to be a selected tab.
