### ISSUE TITLE
bug(material/table): last row border inconsistency

### ISSUE THREAD

**Issue by magentaRE** [angular/components#27731]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Tables with double header (column border and row border) have bottom border on the last row, but only below `<th>` elements. Table shown in the screenshot = Segment 1/2/3 is a columnheader, Region 1/2 is a rowheader and numbers are table data.

![image](https://github.com/angular/components/assets/48152706/e63ae550-910c-4a8c-9fa2-6c3aff19e91e)

`<td>` elements have special CSS selector which deletes this border from the last row. Is the same rule missing for `<th>` elements?

![image](https://github.com/angular/components/assets/48152706/f848309a-5e47-4a6e-a68b-ebe7ff5bedf3)

### Reproduction

Steps to reproduce:
1. Create a table with double header - column + row header
2. Observe last row's bottom border

### Expected Behavior

Last row's bottom border is not present in both `<td>` and `<th>` elements - claimed here: https://material.angular.io/guide/mdc-migration#table

### Actual Behavior

Last row border is not present in `<td>` elements and **is** present in `<th>` elements.

### Environment

- Angular: 16.2.0
- CDK/Material: 16.2.0
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11 Pro

**Comment by wagnermaciel** [comment]
@magentaRE Could you provide a stackblitz reproduction?

**Comment by magentaRE** [comment]
@wagnermaciel Apologies, I forgot to create one. Here it is: https://stackblitz.com/edit/stackblitz-starters-yu5tvs?file=src%2Fmain.ts
