### ISSUE TITLE
bug(drag-and-drop): Using matchSize on DragPreview directive does not work!

### ISSUE THREAD

**Issue by MurhafSousli** [angular/components#27750]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `*drapPreview`, the `matchSize` input does not do anything and the size of the preview element does not match the original item

### Reproduction

[StackBlitz link](https://stackblitz.com/edit/components-issue-1y4nnz?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts,src%2Fapp%2Fexample-component.css)

### Expected Behavior

Using `matchSize` on `*cdkPreview`, preview element should have the same size as the original item

### Actual Behavior

Using `matchSize` on `*cdkPreview` has no effect at all.

Actually in Webstorm `matchSize` appears to be underlined in red and says "Property matchSize is not provided by any applicable directives...." 

### Environment

- Angular: v16
- CDK/Material: v16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
Okay, so it looks like this is a syntax problem rather than a bug. To pass in the input you'd have to use an `ng-template` since the `*cdkDragPreview` shorthand will bind the property to the `div` rather than the directive. You can get it working like this:

```
<ng-template cdkDragPreview matchSize>
  <div class="example-box">{{timePeriod}}</div>
</ng-template>
```
