### ISSUE TITLE
bug(chip + checkbox): Checkbox within Chip doesn't change UI

### ISSUE THREAD

**Issue by tom94zoe** [angular/components#27759]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2.9

### Description

Checkbox doesn't change after click within Chip (mat-chip-row)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/4dexxz-na1sgg?file=src%2Fapp%2Fchips-overview-example.html,src%2Fapp%2Fchips-overview-example.ts
Steps to reproduce:
1. click on Checkbox
2. value changes
3. UI of Checkbox doesn't display changed value.

### Expected Behavior

Checkbox displays current value

### Actual Behavior

checkbox doesn't display change

### Environment

- Angular: 
- CDK/Material:
    "@angular/animations": "~15.0.0",
    "@angular/cdk": "15.2.9",
    "@angular/common": "~15.0.0",
    "@angular/compiler": "~15.0.0",
    "@angular/core": "~15.0.0",
    "@angular/forms": "~15.0.0",
    "@angular/material": "15.2.9",
    "@angular/material-moment-adapter": "15.2.9",
    "@angular/platform-browser": "~15.0.0",
    "@angular/platform-browser-dynamic": "~15.0.0",
    "@angular/router": "~15.0.0",
    "moment": "^2.18.1",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.5"
- Browser(s): chrome - latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment]
Hello,

Thank you for proving stackblitz reproduction.

Angular Material does not support using checkbox inside a mat-chip-listbox. The only element that maybe used inside mat-chip-listbox is mat-chip-option.

https://material.angular.io/components/chips/overview#selection-chips

Best regards,

Zach
