### ISSUE TITLE
bug(Button): Theme after migration 14 > 16

### ISSUE THREAD

**Issue by rmpt** [angular/components#27758]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

After migrating from 14 to 16, my theme stop working correctly. I've applied all the migration steps, with no changes to colors or contrasts, but it's not working as expected.

My SCSS theme file:

```
@use '@angular/material' as mat;
@include mat.core();

$my-palette: (
  50: #fff7e0,
  100: #ffeab1,
  200: #ffdc7e,
  300: #ffd04a,
  400: #ffc41f,
  500: #ffba00,
  600: #ffac00,
  700: #ff9900,
  800: #ff8700,
  900: #ee6001,
  contrast: (
    50: mat.get-color-from-palette(mat.$indigo-palette, '50-contrast'),
    100: mat.get-color-from-palette(mat.$indigo-palette, '100-contrast'),
    200: mat.get-color-from-palette(mat.$indigo-palette, '200-contrast'),
    300: mat.get-color-from-palette(mat.$indigo-palette, '300-contrast'),
    400: mat.get-color-from-palette(mat.$indigo-palette, '400-contrast'),
    500: #ffffff,
    600: #ffffff,
    700: #ffffff,
    800: #ffffff,
    900: #ffffff
  )
);


$my-primary: mat.define-palette($my-palette, 800, 500, 800, 800);
$my-accent:  mat.define-palette($my-palette, 800, 500, 800, 800);

$my-theme: mat.define-light-theme((
  color: (
    primary: $my-primary,
    accent: $my-accent
  ),
  typography: mat.define-typography-config(),
  density: 0
));
@include mat.all-component-themes($my-theme);
```

Contrast is not picked up from my definition. For instance, for hue 900, instead of white (#ffff) it gets black.

### Reproduction

This is a migration issue so it's not possible to reproduce in a stackblitz.

### Expected Behavior

Before migration it would look like this:
<img width="130" alt="image" src="https://github.com/angular/components/assets/16465379/aba303c5-2c42-443f-826b-f7379550fb6b">

### Actual Behavior

After migration, it looks like this:
<img width="141" alt="image" src="https://github.com/angular/components/assets/16465379/eea881a0-5a69-4b40-b2d7-e0a01e661dc4">

### Environment

- Angular: 16.2.1
- CDK/Material: 16.2.2
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS 12.6.7 (Monterey)

**Comment by rmpt** [comment]
anyone? I'm still trying to make it work correctly, no feedback at all from here..

**Comment by zarend** [comment]
Hello,

This looks like more of a support request than an Issue report to me.

We are able to provide a limited amount of support in this issue tracker. I think you would get more help by asking in one of our support channels such as Stackoverflow https://stackoverflow.com/questions/tagged/angular-material2 .

We have documentation for theming at [Theming your own components](https://v15.material.angular.io/guide/theming-your-components). If you believe there is an issue with Angular Material, I suggest narrow your issue down to a minimal reproducible case in a Stackblitz. If the behavior looks incorrect, hat would be a good thing to file an issue report on.

Best regards,

Zach
