### ISSUE TITLE
bug(FormField): Outlined formfield inside material tab has dissapearing right border

### ISSUE THREAD

**Issue by ulrikdom** [angular/components#27763]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I have a material tab group. Inside that I have two formfields with appearance outline. The formfields are placed in a grid so that they are horizontally adjacent to eachother. This results in that the right border of the right most formfield flickers when the window size changes.  It seems the border dissapears when the window size is even and shows when the size is odd.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/dmzrh3
Steps to reproduce:
1. Resize the rendered window, note that the right border of the right most formfield flickers. Dissapears on even window size.

### Expected Behavior

Border of form field should always be visible independent of window size.

### Actual Behavior

Right border of right most formfield dissapears.

### Environment

- Angular: 16.1.1
- CDK/Material: 16.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by ulrikdom** [comment]
My workaround is to add 1px horizontal padding to .mat-mdc-tab-body-content

**Comment by amysorto** [comment]
Closing this issue since its low priority and will not be addressed in the near future. If that changes, this issue can be reopened
