### ISSUE TITLE
bug(MatAutocomplete): matAutocomplete with initial value does not filter options and does not highlight selected

### ISSUE THREAD

**Issue by mmercure** [angular/components#27765]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

A MatAutocomplete field initialized with a value does not filter the list of options are mark selected item.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/vemaxm-6ktpyr?file=src%2Fexample%2Fautocomplete-auto-active-first-option-example.html

Steps to reproduce:
1. In the stackblitz, the formControl for the autcomplet is initialized with 'Two'
2. Click on the field
![image](https://github.com/angular/components/assets/6987117/ebbbb085-a3e9-4bfe-834b-0a89ea79f2de)

3. if I click on the option
![image](https://github.com/angular/components/assets/6987117/f2923435-4f9c-43ef-876e-82f0caccb0d7)

it is as expected.

4. after that if I click the 'clear' button
![image](https://github.com/angular/components/assets/6987117/4117476c-c10b-4f2d-b265-93e16d7d71f3)

value is still selected

5. reselect a value, lets say 'Two'
6. delete the two last letters
![image](https://github.com/angular/components/assets/6987117/c3c6bfc0-68a2-442b-a4c0-09c36e3f0d7f)

### Expected Behavior

The list of option should be filtered with the initial FormControl value
The actual value should be marked as selected.

Resetting the value should remove the selected

deleting last letter of input keeps last selected option as selected

### Actual Behavior

All options are displayed, and nothing indicates that a value is selected.

Resetting the form still displays a value as selected.

if not option exactly match the value, there should not be any selected option.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
`mat-autocomplete` doesn't do any filtering, it just displays the `mat-option` that are projected and keeps track of the value. You can get it to work by changing `startWith('')` to `startWith(this.myControl.value)`.

**Comment by mmercure** [comment]
Ok that's fair, and resetting the selected is addressed with #27652 
but what about the resetting selected when there is a partial value, or selecting when the value is the same, but was not selected in the dropdown?
