### ISSUE TITLE
feat(Dialog): Allow passing in component @Inputs when opening a dialog

### ISSUE THREAD

**Issue by cusher** [angular/components#27776]
### Feature Description

To pass data into a dialog, the current suggested pattern is to set `data` on the `DialogConfig` parameter when calling `open`, and then inject the data into the dialog component using the `DIALOG_DATA` injection token.

Another option is to set the inputs on the `componentInstance` *after* the dialog is opened, however if the component relies on the input being set before initialization, this can run into problems.

Angular 16 added the ability to [pass in component @Inputs as in route params](https://github.com/angular/angular/issues/18967), which allows the removal of basic wrapper components and per-component boilerplate for the most common cases of passing in data through the Router. It would be nice to see this change also reflected in Dialog.

### Use Case

- Enables using an existing component that takes in `@Input`(s) in a basic Dialog without creating a wrapper dialog component that exists solely to pass along injected data (admittedly, of questionable value, since many dialogs will need dialog-specific UI/behavior)
- Allows for passing in data to a dialog component in a more symmetric way with non-dialog components
- Eliminates the need to create a dialog data specific interface for type-safe parameter passing to dialog components

**Comment by crisbeto** [comment]
Actually I think this can be closed. With the changes from https://github.com/angular/components/pull/27536 you can call `setInput` on the dialog's `ComponentRef` yourself. This would be more flexible than having an `inputs` property on the `DialogConfig`, because it allows for the value to change dynamically.

**Comment by cusher** [comment]
Given the choice between setting inputs via an untyped name string, or creating boilerplate wrapper components to pass in the inputs while maintaining type checking throughout, I would stick with the latter 10 out of 10 times. And that's before considering things that can only be caught if all inputs are set at creation time, e.g. a missing `required` input.

That being said, in hindsight it makes way more sense to use whatever interface is exposed by Angular itself for setting inputs on dynamically created components, rather than creating a one-off solution for Dialog specifically. So perhaps I'll ~~complain about `setInput`~~ suggest adding a more robust interface for that on the main Angular repo.
