### ISSUE TITLE
autocomplete panel doesn't pop up when triggering focus on the input programatically

### ISSUE THREAD

**Issue by pd60193** [angular/components#27777]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using autocomplete harness to focus on the autocomplete, the autocomplete panel does not open

`const inputField = await loader.getHarness(MatAutocompleteHarness.with({ selector: '#autocompleteInput' }));
  await inputField.focus();
  const options = await inputField.getOptions();
  expect(options.length).toBeGreaterThan(0);`

The above code fails with 'Error: Unable to retrieve options for autocomplete. Autocomplete panel is closed.'
On checking further, I am sure that my autocomplete has options populated and this should work.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

The test should pass and the autocomplete panel should open.

### Actual Behavior

The above code fails with 'Error: Unable to retrieve options for autocomplete. Autocomplete panel is closed.'

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This sounds like an issue with your setup somewhere. We have a very similar test here: https://github.com/angular/components/blob/main/src/material/autocomplete/testing/shared.spec.ts#L85

**Comment by amysorto** [comment]
Closing since there hasn't been activity on this issue for a few months
