### ISSUE TITLE
Material 16 mat-select dropdown option field giubg bottom of page

### ISSUE THREAD

**Issue by shahanajoy** [angular/components#27779]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I am using angular 16 and Mat-select is using, its select field going down bottom of page.. Please help on this

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. install latest angular material
2.use  <mat-select>
    <mat-option *ngFor="let food of foods" [value]="food.value">
      {{food.viewValue}}
    </mat-option>

### Expected Behavior

dropdwon should come near to matselect field

### Actual Behavior

dropdown box going down of page

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You likely either haven't included the Material select theme or the Material core theme. Also in general this isn't enough information to investigate a bug.
