### ISSUE TITLE
bug(MatButtonToggle): Doesn't Reflect FormControl Value Update Programmatically with Object Values

### ISSUE THREAD

**Issue by ivayloc** [angular/components#27786]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `MatButtonToggleGroup` with a `formControl` and when the `MatButtonToggle` values are set as `object`s, there's an issue with reflecting the visual state of the button toggle. When setting the `FormControl`'s value programmatically, the `MatButtonToggle` does not receive the `mat-button-toggle-checked` class, making it impossible for users to visually identify the selected button.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/bzdxmp?file=src%2Fapp%2Fbutton-toggle-overview-example.ts

Steps to reproduce:
1. Initialize a MatButtonToggleGroup with a bound FormControl.
2. Set the values of the individual MatButtonToggle components as objects.
3. Programmatically set the value of the associated FormControl to one of the object values.
4. Observe the visual state of the MatButtonToggleGroup.

### Expected Behavior

When the value of the `FormControl` is set programmatically, the associated `MatButtonToggle` should visually reflect the selected state by having the `mat-button-toggle-checked` class.

### Actual Behavior

The `MatButtonToggle` does not receive the `mat-button-toggle-checked` class and remains in an unselected state visually, even though its value matches the `FormControl`'s value.

### Environment

- Angular: 15.2.9, 16.1.1
- CDK/Material: 15.2.9, 16.2.3
- Browser(s): Chrome
- Operating System: Windows 11

**Comment by amysorto** [comment]
For me the Stackblitz reproduction seems to be working. Can you check your link to see if that's the case for you? @ivayloc
