### ISSUE TITLE
bug(mat-icon): Click not being captured

### ISSUE THREAD

**Issue by wonboyn** [angular/components#27791]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a mat-icon configured to capture the click inside mat-form-field together with a matInput field.
Any click on the icon is being treated only as a focus on the input field rather than triggering the click function.

### Reproduction

<mat-form-field>
<mat-label>Some label</mat-label>
<input matInput formControlName="someField" />
<mat-icon matSuffix (click)="searchClicked()">search</mat-icon>
</mat-form-field>

### Expected Behavior

Function configured on mat-icon click event is triggered

### Actual Behavior

Input field shows focus

### Environment

- Angular: 16.2.3
- CDK/Material: 16.2.2
- Browser(s): Chrome
- Operating System: Ubuntu

**Comment by amysorto** [comment]
For interactive buttons, we have some [guidance to wrap it in `mat-button` or an `a` element](https://material.angular.io/components/icon/overview#interactive-icons). Although placing a button inside a form field seems like an uncommon interaction pattern to me, and something we would unlikely support.

Without more information about your specific use case, I am going to close this bug. Feel free to create a new one with a StackBlitz reproduction.
