### ISSUE TITLE
Drag object if page is scrolling

### ISSUE THREAD

**Issue by Flo0806** [angular/components#27794]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I wanna drag a object (dragging free and set any position to it - like the basic example). So I use simple the `cdkDrag` directive like this:

```
<div class="test">
  <div class="example-box" cdkDrag>Drag me around</div>
  <div>
    <!-- Copyright 2019 Google LLC. All Rights Reserved.
    Use of this source code is governed by an MIT-style license that
    can be found in the LICENSE file at http://angular.io/license -->
  </div>
</div>
```

The `test` class has a height of 1800px. So its content is scrollable. If I now drag the object and while I dragging I scroll the page, too (with mousewheel as example) the position of the object gets wrong - the object scrolls with the container so to say.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-hv5vd8-qca8ht?file=src%2Fapp%2Fcdk-drag-drop-overview-example.html
Steps to reproduce:
Use a `div` with only `cdkDrag` directive in a scrollable container (or main page)

### Expected Behavior

The object will hold her position under the mouse. So it should not scrolling with the parent container.

### Actual Behavior

The position of the object holds the position of the viewport. So it "scrolls" with it so to say.

### Environment

- Angular: 15.x
- CDK/Material: 8.2 - actual
- Browser(s): CHROME

**Comment by crisbeto** [comment]
There are a few problems with the example:
1. You need to mark any scrollable parent containers (excluding the actual document) with the `cdkScrollable` attribute so the CDK knows to listen for their scroll events.
2. You're using a _really_ old version of the CDK. In general it's recommended that the CDK is the same major version as the framework.

**Comment by Flo0806** [comment]
Yes... my issue. I have test it with the newest version of material cdkDrag and it works. Thx. This post can be closed.
