### ISSUE TITLE
Typography: Tailwind Prose Conflict

### ISSUE THREAD

**Issue by elvince** [angular/components#27802]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We set the mat-typography on our body.

For some components, we would like to use tailwind prose.
This plug-in is reseting all elements to have a ling of standard display graphics.

but Materail design override the prose plug-in on all HX headers elements typography.
How can I fix this?
Is there a way to "stop" mat-typograpphy to apply on HX tags contained under a specific div? 

Thanks

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Be able to stop mat-typography under certain elements. like with a class 'mat-typography-bypass'

### Actual Behavior

I'm seeing all material typography intead of tailwind prose one.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by json-derulo** [comment]
> We set the mat-typography on our body.

Why? Apparently you don't want the typography styles to be applied to the whole application, so only add the `mat-typography` class to those parent elements where you actually want Material Typography.

**Comment by elvince** [comment]
In fact, I want it to be applied on the whole application except 1 component.
I would rather set a "cancel class" than putting mat-typography to all the other components in my entire app ^^

**Comment by mmalerba** [comment]
This isn't a use case we really support, but you could try putting the typography styles in a css layer, that would cause them to be overridden by other rules regardless of the specificity. Here's an example: https://stackblitz.com/edit/awre4v?file=src%2Ftheme.scss
