### ISSUE TITLE
Angular Material Upgrade Issue

### ISSUE THREAD

**Issue by beejuspal** [angular/components#27815]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

1. If 'mat-chip-option' is an Angular component, then verify that it is part of this module.
2. If 'mat-chip-option' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

above issues occurred

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Free of error message

### Actual Behavior

Error: src/app/components/userinfo/education/education.component.html:32:13 - error NG8001: 'mat-chip-option' is not a known element:
1. If 'mat-chip-option' is an Angular component, then verify that it is part of this module.
2. If 'mat-chip-option' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

32             <mat-chip-option color="primary" selected
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
33               >Highest Education MBA</mat-chip-option
   ~~~~~~~~~~~~~~~

  src/app/components/userinfo/education/education.component.ts:8:16
    8   templateUrl: "./education.component.html",
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component EducationComponent.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
Hello,

This looks like more of a support request than an issue report to me. Issue reports usually have a Stackblitz reproduction or some kind of isolated reproduction.

We are able to provide a limited amount of support in this issue tracker. I think you would get more help by asking in one of our support channels such as Stackoverflow https://stackoverflow.com/questions/tagged/angular-material2 .

Best regards,

Zach
