### ISSUE TITLE
md-select doesn't expand + md-option text overflow doesn't work properly

### ISSUE THREAD

**Issue by fxck** [angular/components#2782]
_using 2.0.0-beta.1-592f33f_

since `.md-select-value` is absolutely positioned, it doesn't expand its parent and is flowing out it

![image](https://cloud.githubusercontent.com/assets/1303561/22257816/741d1cc8-e25f-11e6-8e03-ce365385c3f0.png)

also because of `display: flex` on md-option, ellipsis(three dots) do not work

![image](https://cloud.githubusercontent.com/assets/1303561/22257963/094274b0-e260-11e6-87cc-d5fae5a0520b.png)

@kara I guess? could try to fix it, but would like to know reasoning behind that absolute position and flex first..

**Comment by crisbeto** [comment]
Can't speak about the positioning, but the text ellipsis were fixed recently.

**Comment by fxck** [comment]
were they? I think I'm running the latest version from material2-builds(unless yarn is acting up again)

**Comment by helzgate** [comment]
I did the following to allow the text to autoresize:

html

    <form>
        <md-select #fixit placeholder="Filter">
            <md-option  *ngFor="let txt of linkCategories$ | async" (onSelect)="change(txt)">
                {{ txt }}
            </md-option>
        </md-select>
    </form>

component:

    @ViewChild('fixit') fixit: MdSelect;

...

    change(txt: string) {
        const font = window.getComputedStyle(this.fixit['_element'].nativeElement, null).getPropertyValue('font');
        let newwidth = 0;
        let canvas = document.createElement("canvas");
        let context = canvas.getContext("2d");
        context.font = font;
        let metrics = context.measureText(txt);
        newwidth = metrics.width + 18;
        this.fixit._selectedValueWidth = newwidth;
        this.fixit._triggerWidth = newwidth;
        // do something with selected txt
    }

**Comment by crisbeto** [comment]
This should've been resolved a long time ago.
