### ISSUE TITLE
bug(mat-paginator): need a way to add custom class on button's tooltip

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#27823]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We have created a theming system in our private library around angular material which consumes all the material components and created custom stylings for all those components.
We have custom stylings for tooltip as well which we apply using a custom class/attribute.

Is there any way I can assign a custom class on tooltip of the paginator's button?

Also there is no unique class applied to the tooltip of paginator's button.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

There should be a way to add custom class on tooltip of paginator's button

### Actual Behavior

There isn't any way to add custom class on tooltip of paginator's button

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by mmalerba** [comment]
This isn't possible for the paginator tooltips, since they're created internally to the paginator. However, all tooltips, including the paginator ones should have a class you can target to add custom styles: `.mat-mdc-tooltip-panel`
