### ISSUE TITLE
bug(Service): On hover the ChatGPT icon background color not changing

### ISSUE THREAD

**Issue by Junaid0067** [angular/components#27829]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In hovering on ChatGPT icon and Low Code Development icon, background color is not changing like it is changing for every icon

![image](https://github.com/angular/components/assets/96833116/62fd2462-20ff-46ef-b056-544ed9b5a410)

### Reproduction

Steps to reproduce:
1. Got to Home Page
2. Hover on Service in menu bar
3. then Hover on ChatGPT development icon

### Expected Behavior

Icon backgound color should be change for icon

### Actual Behavior

Icon bg color as it is on hovering

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment]
Hello,

This looks like more a a support request than an issue report to me.

We are able to provide a limited amount of support in this issue tracker. I think you would get more help by asking in one of our support channels such as Stackoverflow https://stackoverflow.com/questions/tagged/angular-material2 

Best regards,

Zach
