### ISSUE TITLE
bug(Autocomplete): Flickering/reappearing dropdown menu 

### ISSUE THREAD

**Issue by emilyzhang242** [angular/components#27831]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Using the legacy autocomplete component. We migrated to MDC. 

### Description

When you select an option in the matAutocomplete menu, the option dropdown flickers/flashes briefly. You can see this in any of the examples on the material angular page.

https://material.angular.io/components/autocomplete/examples

This is problematic because when I try to reopen the matAutocomplete panel using `requestAnimationFrame`, the old panel still exists and it pushes the new panel to the side for a brief moment while it reappears, causing really strange flickering behavior.

### Reproduction

N/A

### Expected Behavior

The dropdown should not flicker/reappear and should just vanish when an option is selected.

### Actual Behavior

The dropdown disappears and then reappears very briefly after selecting an option.

### Environment

- Angular: 2 
- CDK/Material: Material
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by mmalerba** [comment]
I'm not seeing any flickering. I think maybe what you're seeing is the fade out animation. The panel doesn't disappear immediately, it fades out over the course of a few ms. If you slow down the animations to 10% using the chrome devtools you can see this clearly.

**Comment by emilyzhang242** [comment]
@mmalerba Is there any way to remove the animation? I tried using `transition: none` on the autocomplete component and also tried using `NoopAnimationsModule` but neither caused the fading out to stop.
