### ISSUE TITLE
bug(OVERLAY): Overlay scrollblock always adds a scrollbar even if there is no scrolling possible

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/components#27834]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Make sure that:
- the browser tab is zoomed to more than 100%
- you're on a page that doesn't have a vertical scrollbar

activate a CDK overlay, even the one serving as the mat-dialog background is good enough.
the page will now have a vertical scrollbar:
<img width="1920" alt="image" src="https://github.com/angular/components/assets/1098243/6f5a134c-d433-4247-b166-ddef3e23fbd0">

Overriding 
<img width="263" alt="image" src="https://github.com/angular/components/assets/1098243/7caa5b3b-86d3-47ba-969f-92b250672735">
does the trick.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

No scrollbar if there is no scrollbar in the page.

### Actual Behavior

A scrollbar if there is no scrollbar in the page.

### Environment

- Angular: 16.2
- CDK/Material: 16.2 half MDC half not
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by mmalerba** [comment]
I'm not seeing this at least on this example with mat-dialog: https://stackblitz.com/edit/i6ufyx?file=src%2Fstyles.scss

Can you provide a reproduction stackblitz?

**Comment by LanderBeeuwsaert** [comment]
Hi @mmalerba thank you for the quick response. I've been trying to reproduce but haven't been able to.
I'm going to close this and if this would happen again I'll do more in-depth research to the cause.

Best regards
