### ISSUE TITLE
feat(Sidenav): Support hydration

### ISSUE THREAD

**Issue by intellix** [angular/components#27848]
### Feature Description

Sidenav and various other components should support Clientside Hydration. When I deliver the initial HTML from the server, the client should be able to hydrate my entire site without having a flash of replaced and recreated content.

I've been fighting with enabling it and then started to investigate why 2x components are skipping hydration. I thought that it was strange because I never explicitly added it and now that I can see that it was 100% disabled for anything inside a Sidenav: https://github.com/angular/components/commit/1a6f924e2da852be6bd78445f43bac0275264b6e

The whole application exists within a Sidenav but Material completely disables it (I assume due to direct DOM manipulation). It would be great if material didn't disable hydration, so we can improve UX and SEO with better lighthouse scores.

### Use Case

It would allow Material based websites to not suffer from poor lighthouse scores and flashing pages.

**Comment by alexcmoss** [comment]
This is also preventing me from moving to Angular 16. We use Angular Universal with the Preboot library to provide transition. Preboot is not maintained, and not supported by Angular 16 due to deprecation of Ivy. Sidenav is the single most important component for us to support hydration as it wraps most other elements in an application.

**Comment by elgerm** [comment]
[Here a minimal example of a sidenav where you can see the issue](https://github.com/elgerm/sidenav)

Clone and run project, open browser console, always see 1 component skipped hydration, which is the sidenav container component I guess.

![image](https://github.com/angular/components/assets/2996554/a14879cc-ffb8-4dff-b96a-c5d83e3dab76)

**Comment by tsenguunchik** [comment]
Any updates on this?

**Comment by muchbetterug** [comment]
+1 would love to see this in the near feature, seo is killing me <3

**Comment by crisbeto** [comment]
There are a couple of issues with backporting it:
1. This isn't really covered by our LTS policy. We primarily backport fixes related to security or accessibility.
2. Getting hydration to work in all components required some fixes in the framework that may have to be backported as well.
