### ISSUE TITLE
MatFormField (outline) label cut off in MatDialog

### ISSUE THREAD

**Issue by stnor** [angular/components#27845]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When setting theme density to -1 and using `<mat-form-field>` with appearance: 'outline' the top of the form field gets cut off in a MatDialog unless using the following rule as a global style:
```
  .mat-mdc-dialog-content > mat-form-field {
    margin-top: 4px !important;
  }
```

**Comment by andvasp** [comment]
I believe we are facing similar problem but not necessary inside a MatDialog. See the image below:

![image](https://github.com/angular/components/assets/18604227/7bcbb495-27e8-4b33-8907-209ef4db6b86)

Use the code below to test. It does not happen immediately. It needs some seconds to happen:
```
<form>
  <mat-form-field floatLabel="always" appearance="outline" style="font-size: 15px; width: 160px">
    <mat-label>Input 1</mat-label>
    <input matInput placeholder="Placeholder 1">
  </mat-form-field>
</form>
```
We noticed that it started after a Chrome update (117.0.5938.92).

**Comment by else-przemek** [comment]
I have some problem like @andvasp

**Comment by DanielHabenicht** [comment]
I too got this problem, and did not find your issue first. So I already created a bug report with reproduction here: https://github.com/angular/components/issues/28079
