### ISSUE TITLE
feat(Angular Material Design): Angular Material Design to Material 3

### ISSUE THREAD

**Issue by rockcoolt** [angular/components#27849]
### Feature Description

Hello 👋🏾
I'm sorry if my question has already been asked; I've been searching for a reliable answer for days. 😵‍💫

Is there a plan to migrate the design of Angular Material to Material 3?
If not, I think I'll have to use the web version of Material 3, which is not well-suited for Angular.

Thank you for your answers 🙏🏾

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/22738.
