### ISSUE TITLE
bug(menu): Focus lost when an input with a label is in a menu item

### ISSUE THREAD

**Issue by StevenSwitten** [angular/components#27852]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I've encountered this very weird bug where I have an input in a mat-menu-item. If the input has a label, and you type the first letter of that label in the input, the input loses focus.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-kjzj77?file=src%2Fapp%2Fexample-component.html
Steps to reproduce:
1. Click the button to show the menu
2. Type anything without the letter "D" -> it works fine.
3. Type the letter "D" -> focus is lost

### Expected Behavior

Focus should not be lost

### Actual Behavior

Focus is lost

### Environment

- Angular: 16.2.1
- CDK/Material: 16.2.1
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows & Android

**Comment by crisbeto** [comment]
It's because the menu has support for typeahead focus management. I'm closing the issue because inputs inside menu items aren't supported.
