### ISSUE TITLE
bug(mat-checkbox): cdk-keyboard-focused CSS class missing in checkbox after focus

### ISSUE THREAD

**Issue by magentaRE** [angular/components#27855]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7 (non MDC-based components)

### Description

When tabbing onto a checkbox, no CSS classes from CDK directives get applied to a checkbox. https://material.angular.io/cdk/a11y/overview#cdkmonitorelementfocus-and-cdkmonitorsubtreefocus

This used to work natively without even setting `cdkMonitorElementFocus` directive onto a checkbox. CSS classes don't get applied even if you put `cdkMonitorElementFocus` on the element. This was not a problem in the old non-MDC components. Screenshot from my app, old non MDC-based components, Material version 14.x.x:

![image](https://github.com/angular/components/assets/48152706/2c874ec4-530b-4afc-80d9-fb496f73af45)

This behavior works in `<mat-radio-button>`, you don't even have to set `cdkMonitorElementFocus` on the radio button. Those CSS classes get applied onto the focused radio button.

### Reproduction

StackBlitz link: not needed
Steps to reproduce:
1. Go to [https://material.angular.io/components/checkbox/overview](https://material.angular.io/components/checkbox/overview)
2. Observe any checkbox on the site in DevTools
3. Tab onto that checkbox on the site with keyboard or any other way (programatically, mouse,...)
4. `<mat-checkbox>` element should be getting `.cdk-focused` and `.cdk-${origin}-focused` CSS classes

### Expected Behavior

`.cdk-focused` and `.cdk-${origin}-focused` CSS classes should be applied onto checkbox when focused, clicked, etc.

### Actual Behavior

`.cdk-focused` and `.cdk-${origin}-focused` CSS classes are **NOT** getting applied onto checkbox when focused, clicked, etc.

### Environment

- Angular: 16.2.6
- CDK/Material: 16.2.5
- Browser(s): any (tried Chrome and Firefox)
- Operating System (e.g. Windows, macOS, Ubuntu): tried it on Windows, I don't know if it does work on others

**Comment by mmalerba** [comment]
We no longer use the CDK focus directives in our implementation of checkbox, but if you need the classes for your own styling you can add the `cdkMonitorSubtreeFocus` directive to the checkbox. Here's an example: https://stackblitz.com/edit/apc32q?file=src%2Fexample%2Fcheckbox-overview-example.ts,src%2Fexample%2Fcheckbox-overview-example.html

**Comment by magentaRE** [comment]
@mmalerba Thanks for letting me know! Is there any document which contains all these small changes regarding CDK focus directives (e.g. which components lost CDK focus classes, which gained them etc.)?
