### ISSUE TITLE
Material table broken after upgrading angular from 14 to 16

### ISSUE THREAD

**Issue by yohannestikabo** [angular/components#27877]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Unhandled Application Error TypeError: Cannot read properties of null (reading 'flags') at isDirectivelost (core.mis: 2157:19) at elementStart (core.mjs: 16300:27) at eelement (core.mjs: 16377:5) at DocumentsComponent_ng_template_14_mat_cell_13_Template (template.htm:65:15) at executeTemplate (core.mjs: 11986:13) at renderView (core.mjs: 13184:13) at createndRenderEmbeddedLView (core.mjs: 23961:5) at TemplateRef.createEmbeddedViewImp1 (core.mjs: 24047:31) at ViewcontainerRef.createEmbeddedView(core.mjs:24355:37) at MatTable._renderCellTemplateForItem

### Reproduction

I were not able to reproduce this in StackBlitz

### Expected Behavior

This supposed to display a material table with data, and it was working in Angular 14.

### Actual Behavior

Display a material table with data

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
Hi, it is infeasible for us to debug this only from an error message. If you are unable to reproduce the issue with a stackblitz, it is likely this is an issue in the application, not with the MatTable

If you are able to create a reproduction of the issue on stackblitz, please feel free to file a new issue
