### ISSUE TITLE
mat-select stranger behavior after updating to version 16.2.6

### ISSUE THREAD

**Issue by gurelsoycaner** [angular/components#27879]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

![image](https://github.com/angular/components/assets/5128170/eef2a96e-5972-4ace-8fb3-fe8241903e2f)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I'm not sure what happened after upgrading to version 16.2.6

### Actual Behavior

![image](https://github.com/angular/components/assets/5128170/1641ab4e-eef8-4428-99dc-7cd21cc1cc0f)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by wagnermaciel** [comment]
@gurelsoycaner Could you provide a stackblitz reproduction of the issue? It is infeasible to debug this without one. My best guess going just by the images you shared is that the z-index of one of the other elements is greater than the z-index of the mat-select dropdown

**Comment by crisbeto** [comment]
It looks like the theme for the select isn't included. See the theming guide for more information https://material.angular.io/guide/theming
