### ISSUE TITLE
docs-bug(website): Changing the version in the website's header should redirect to the page you were on

### ISSUE THREAD

**Issue by ilyakonrad** [angular/components#27912]
### Documentation feedback

Imagine you're reading docs on mat-select of version **x** and you want to check what has changed in version **y**. When you select a different version in the header, you're redirected to the main page.

It's really annoying to do two unnecessary clicks and scrolling when trying to compare the same component in different versions. Especially while headaching your way through upgrade from version 14 to 16.

Also a way to select a different version by opening it in a separate tab (like a link via mousewheel button) would be really, I mean really useful. That way you can see the difference even better and basically compare things side by side.

The solution might also be to put a version select inside of the component page, but again it would have much more value if I could open another version in a new tab.

Let's make the documentation of the component library that represents very good UI/UX design as easy to use and as user-friendly as the design itself.

### Affected documentation page

https://material.angular.io/

**Comment by naaajii** [comment]
I had mention this on [1196](https://github.com/angular/material.angular.io/issues/1196) but it did not get attention, it is a bit of headache navigating.

**Comment by amysorto** [comment]
Closing this issue since that PR mentioned above is now merged

**Comment by ilyakonrad** [comment]
Should it work already? Because for me it doesn't work.

**Comment by naaajii** [comment]
its working for me on [v18](https://material.angular.io/), [rc](https://rc.material.angular.io/) & [next](https://next.material.angular.io/), for example: while being on [v18](https://material.angular.io/components/badge/overview) badge switching to older version such as v16 (or till v10) navigates me to [v16](v16.material.angular.io) and so on. i also checked it for autocomplete.

i might be wrong but i believe might not work on versions behind v18 cause new changes arent backported. as in, once you go to older version from v18 to v16 - then try to go back on newer version of current component it won't take you there but on homepage.

**Comment by ilyakonrad** [comment]
Yep, it doesn't seem to work for versions under v18.
