### ISSUE TITLE
feat(MatSlider): Track should draw from zero mark when slider has a range from negative to positive

### ISSUE THREAD

**Issue by andrewalderson** [angular/components#27934]
### Feature Description

When a slider has a range from a negative to a positive (-45 to +45 as an example) the slider thumb can be centered at the zero mark but the track still gets drawn from the left side. The track should be drawn from the zero mark in each direction

<img width="119" alt="image" src="https://github.com/angular/components/assets/16738284/858a25be-7303-483e-bea2-721edb68b66b">
<img width="107" alt="image" src="https://github.com/angular/components/assets/16738284/a0284b1b-677e-4c1e-acff-58c896a71099">

I am currently using a directive to hack the slider to do this

```
@Directive({
  selector: 'mat-slider[ngxCenterOnZero]',
  standalone: true,
})
export class NgxCenterOnZeroDirective implements OnInit {
  #slider = inject(MatSlider, { self: true });

  ngOnInit(): void {
    this.#slider._updateTrackUI = (source: MatSliderThumb) => {
      // where is the zero value as a percentage on the rack
      const centerPercent = 0 - source.min / (source.max - source.min);
      const fillPercentage = source.fillPercentage - centerPercent;
      this.#slider._setTrackActiveStyles({
        left: `${centerPercent * 100}%`,
        right: 'auto',
        transformOrigin: 'left',
        transform: `scaleX(${fillPercentage})`,
      });
    };
  }
}
```

### Use Case

Well, it would make the slider more useful and be a better user experience

**Comment by wagnermaciel** [comment]
@andrewalderson Could you provide a stackblitz reproduction of the issue? I failed to reproduce this locally

Here's a starter stackblitz
https://stackblitz.com/run?file=package.json

**Comment by andrewalderson** [comment]
@wagnermaciel This isn't a bug, it is a feature request. There is nothing to reproduce but here is a Stackblitz anyways https://stackblitz.com/edit/krdwub?file=src%2Fexample%2Fslider-overview-example.html

If you set the min value of the slider to a negative number and the max value to a positive the zero mark will be between them but the active track always gets drawn from the left side.  For this configuration:

```
<mat-slider min="-45" max="45">
  <input matSliderThumb />
</mat-slider>
```

The track will get drawn from the -45 value. It should get drawn from the center point (where the zero value is) in each direction. If you look at the slider code you can see this
```
  private _updateTrackUINonRange(source: _MatSliderThumb): void {
    this._isRtl
      ? this._setTrackActiveStyles({
          left: 'auto',
          right: '0px',
          transformOrigin: 'right',
          transform: `scaleX(${1 - source.fillPercentage})`,
        })
      : this._setTrackActiveStyles({
          left: '0px',
          right: 'auto',
          transformOrigin: 'left',
          transform: `scaleX(${source.fillPercentage})`,
        });
  }
```

Always drawn from the left (or right for rtl) but it would be more informative if it was drawn from the center to the current position of the thumb in either direction.

**Comment by wagnermaciel** [comment]
Oh, sorry about that! I misunderstood completely. Thank you for clarifying

Unfortunately this custom behavior is not something we plan to support since it is not within the scope of what is described by the material design spec

https://m2.material.io/components/sliders

That said, I think your workaround is pretty solid. The only problem is that overriding `_updateTrackUI` is not a supported way to use our library so it can potentially be broken without warning by future changes. IMO for your use case it would probably be best to fork the slider code and apply your workaround directly so you don't need to worry about future updates to the slider breaking your component
