### ISSUE TITLE
MatInput border-radius style applies only to the right side of the input element

### ISSUE THREAD

**Issue by dnespola** [angular/components#27938]
### Is this a regression?
No

### Description

When i apply the following css style 

.mat-mdc-form-field.mat-primary {
  .mdc-notched-outline {
    &__leading {
      border-top-left-radius: 30px !important;
      border-bottom-left-radius: 30px !important;
    }

    &__trailing {
      border-top-right-radius: 30px !important;
      border-bottom-right-radius: 30px !important;
      flex-grow: 1;
    }
  }
}

then onyl the $__trailing part will be applied to the input element.
![20231012154502](https://github.com/angular/components/assets/26873216/d4f351b8-e751-43ff-a009-d750bd7a5884)

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/ljuwfd?file=package.json

### Expected Behavior

I expect rounded corner on booth side of the input box.

### Actual Behavior

Only the style is applied only to the trailing part of the box.

### Environment

- Angular: 16.2.0
- CDK/Material: 16.2.2
- Browser(s): Chrome & Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs
- Angular-Matrial: 16.2.8

**Comment by andrewseguin** [comment]
This is because the width of the element is only 12px, making it so that it cannot have a radius of 30px. You'll want to also increase it's width if you want it to be more curved
