### ISSUE TITLE
Swiper libraryinside Angular CDK Drag&Drop

### ISSUE THREAD

**Issue by Marius-Romanus** [angular/components#27950]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

When you insert swiper ([https://swiperjs.com/element](https://swiperjs.com/element)) into a draggable element of the Angular CDK and try to swipe, the following error appears in the console:

```
zone.js:1681 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at DragRef._getPointerPositionInElement (drag-drop.mjs:1081:64)
    at DragRef._initializeDragSequence (drag-drop.mjs:864:24)
    at DragRef._pointerDown (drag-drop.mjs:394:22)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Zone.runTask (zone.js:173:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:483:34)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1695:16)
    at Swiper.onAny (swiper-element-bundle.mjs:173:15)
```

<img width="385" alt="image" src="https://github.com/angular/components/assets/18282247/0ffffd79-b8f5-410e-9ca5-7d88baad5766">

It seems that the error comes from this function:
  ```
 /**
     * Figures out the coordinates at which an element was picked up.
     * @param referenceElement Element that initiated the dragging.
     * @param event Event that initiated the dragging.
     */
    _getPointerPositionInElement(elementRect, referenceElement, event) {
        const handleElement = referenceElement === this._rootElement ? null : referenceElement;
        const referenceRect = handleElement ? handleElement.getBoundingClientRect() : elementRect;
        const point = isTouchEvent(event) ? event.targetTouches[0] : event;
        const scrollPosition = this._getViewportScrollPosition();
        const x = point.pageX - referenceRect.left - scrollPosition.left;
        const y = point.pageY - referenceRect.top - scrollPosition.top;
        return {
            x: referenceRect.left - elementRect.left + x,
            y: referenceRect.top - elementRect.top + y,
        };
    }
```

Thanks, greetings!

### Reproduction

Git link: https://github.com/Marius-Romanus/bug-angular-swiper
Steps to reproduce:
1. clone repository
2. npm install
3. ng serve
4. slide where it says "Slide 1"
5. see console

### Expected Behavior

It is expected that there will be no error in the console

### Actual Behavior

zone.js:1681 Uncaught TypeError: Cannot read properties of undefined (reading '0')

### Environment

- Angular: 16.2.9
- CDK/Material: 16.2.8
- Browser(s): Chrome v118.0.5993.71 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11
- Node: v18.17.1

**Comment by crisbeto** [comment]
It looks like Swiper fires off fake events with the same names as the native ones, e.g. `touchstart` and `touchend`. See: https://swiperjs.com/swiper-api#event-touchStart. You'll have to add the `events-prefix` to the Swiper container to prevent it from clashing. Closing since this is outside of our control.
