### ISSUE TITLE
bug(slider): Thumb label should have opacity of 1

### ISSUE THREAD

**Issue by PowerKiKi** [angular/components#27953]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The slider component can optionally show a thumb label. That thumb label is shown with an opacity of 0.6. I believe because of https://github.com/angular/components/blob/3cbf125614f957770c52f382c46e6852ad033d75/src/material/slider/slider.scss#L103.

This is against [Material Design 3 spec](https://m3.material.io/components/sliders/specs) that shows the thumb label background color should be the same as the slider itself.

This is an accessibility issue since it can becomes very difficult to read, as seen here:

![image](https://github.com/angular/components/assets/72603/93d64163-2a90-4220-a242-b00349d95eba)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/5gakzy

Steps to reproduce:
1. slide in the middle of slider

### Expected Behavior

It should look more like this. At the very least have a totally opaque, non-transparent, thumb. As it was recently done for matTooltip.

![image](https://github.com/angular/components/assets/72603/06511a30-c501-47f7-ad5d-f0563cb80ec1)

### Actual Behavior

I cannot read my thumb label. 

### Environment

- Angular: 16.2
- CDK/Material: 16.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by amysorto** [comment]
Right now our components are based on Material Design 2: https://m2.material.io/components/sliders. Support for Material design 3 is coming soon. I'll close this issue for now since it's not applicable at this moment.
