### ISSUE TITLE
bug(cdk-dialog): Unable to inject providers provided via route config into dialog

### ISSUE THREAD

**Issue by TomTomB** [angular/components#27968]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Injecting providers into a dialog that are provided via route config currently always results in a R3InjectorError. Adding the view container ref or injector of the current component to the dialog's config does not fix this problem.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-x5794s?file=src%2Fmain.ts

### Expected Behavior

Injecting providers provided via route config should work.

### Actual Behavior

Injecting providers provided via route config always results in a R3InjectorError

### Environment

- Angular: 16.2.10
- CDK/Material: 16.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
This is the components repo, for framework specific issues please follow the instructions here: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#submit-issue.

Although there is a similar issue here that might answer your question: https://github.com/angular/angular/issues/51676.
