### ISSUE TITLE
bug(mat-chip-listbox): vertical orientation not working

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/components#27978]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`<mat-chip-listbox aria-orientation="vertical">`
![image](https://github.com/angular/components/assets/11920691/47b0397b-ddd7-43f0-80dc-ca0952666ad9)
this input seems to be broken as it stays horizontal...
![image](https://github.com/angular/components/assets/11920691/7c3bdbd2-a6fd-49f2-a043-ac3ac087503e)

### Reproduction

StackBlitz link: [https://stackblitz.com/edit/kup7ap?file=src%2Fexample%2Fchips-avatar-example.html](https://stackblitz.com/edit/kup7ap?file=src%2Fexample%2Fchips-avatar-example.html)

### Expected Behavior

vertical layout

### Actual Behavior

horizontal layout

### Environment

- Angular: 16.1.1
- CDK/Material: 16.2.9
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The orientation input is only there to indicate the orientation to assistive technology. The make the chips stacked, you have to add the `mat-mdc-chip-set-stacked` class to the `mat-chip-listbox`.
