### ISSUE TITLE
feat(MatToolbar): media query for size change should include orientation

### ISSUE THREAD

**Issue by andrewalderson** [angular/components#27974]
### Feature Description

The following is presented for your condieration.

Currently the media query for the MatToolbar that changes its height for mobile is:
```
@media (max-width: 599px)
	.mat-toolbar-row, .mat-toolbar-single-row {
		height: var(--mat-toolbar-mobile-height);
	}
}
```

Why doesn't it take orientation and media type into consideration?

Shouldn't the media query be something like (haven't actually thought this through but you get the drift):
```
@media only screen and (max-width: 599px) and (orientation: portrait),
  only screen and (max-height: 599px) and (orientation: landscape) {
	.mat-toolbar-row, .mat-toolbar-single-row {
		height: var(--mat-toolbar-mobile-height);
	}
}
```

I will get into the whole think with the css variables in another issue :)

**Comment by amysorto** [comment]
I assume this media query combined with the one you have already would solve your issue: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation. Here is more information about combining media queries: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries#creating_complex_media_queries. Feel free to reopen this issue if this doesn't work for your use case.

**Comment by andrewalderson** [comment]
@amysorto That doesn't answer my question: Why doesn't it take orientation and media type into consideration?

The css variable that is used for the height of the toolbar literally has the word 'mobile' in it.  In looking at the [BreakpointObserver](https://material.angular.io/cdk/layout/overview) documentation there is a breakpoint for 'Handset' which to me means 'Mobile'. Why isn't this breakpoint used for the mobile height of the toolbar instead of the one that just means 'xsmall' or am I not supposed to rotate my phone to landscape?

I can combine this media query with my own but regardless the one in the library code will still get triggered and this media query is undocumented so to know what it is I have to look at the code.  If you are going to have a media query in the code to change the height of the toolbar on 'mobile' then shouldn't the media query actually be for a 'mobile' screen.
