### ISSUE TITLE
bug(MatFormField): layout glitch on long hint text

### ISSUE THREAD

**Issue by Mradmedamine** [angular/components#27972]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When having a long hint text on a mat-form-field  the text overlaps with any text under the field.

![image](https://github.com/angular/components/assets/12666919/ffc5f4d2-b97f-41f2-a1d4-e6df881e7794)

https://stackblitz.com/run?file=src%2Fexample%2Fform-field-appearance-example.html

### Reproduction

StackBlitz link: 
Steps to reproduce:
1.  Put a a long hint text of 3 sentences at least
2.  See the changes on the UI.

### Expected Behavior

the hint text should be shown properly and not overlaps with the element on the bottom.

### Actual Behavior

The hint text is is being hidden by text under the mat-form-field.

### Environment

- Angular: 16.2.10
- CDK/Material:16.2.9
- Browser(s): Chrome Version 118.0.5993.88
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by amysorto** [comment]
Multiple lines is not something we support, since the material spec doesn't either: https://m2.material.io/components/text-fields#specs. This would require some custom css and overriding our styles to make this work for your use case.

**Comment by Mradmedamine** [comment]
![image](https://github.com/angular/components/assets/12666919/d574073b-a6e6-41fa-894b-3b42390772e2)

Same thing happens with mat-error. Its very common to have long hint or error and I find this not normal that the mat field container doesn't include fully the mat-error or mat-hint.  I know I can fix it with custom styling but this is not my preferable solution. This will make issues on future upgrades.
