### ISSUE TITLE
bug(mat-menu): panelClass is being overridden by the default styling

### ISSUE THREAD

**Issue by Matthew-The-Developer** [angular/components#28001]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When applying a panelClass to the mat-menu component to alter the max-width of the menu, to accommodate menu items with extra long text, the panelClass is applied but then overridden by mat-menu's default styling

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-nxy1yz?file=src%2Fapp%2Fexample-component.html,src%2Fstyles.scss
Steps to reproduce:
1. Open the menu by clicking the 'Menu' button
2. See that the menu item's text is wrapped instead of pushing the menu's width wider
3. With the menu open, open the element inspect in the DevTools and select the menu's panel from the DOM
4. See that the custom-panel-class is being applied to the menu but is being overridden be the component's defaults

### Expected Behavior

The expected behavior would be that the menu's width would be wide enough to display the menu item's text without wrapping it

### Actual Behavior

The current behavior is that the menu item's text is wrapped with in the menu's default max-width

### Environment

- Angular: 15.2.9
- CDK/Material: 15.2.9
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows (win32 x64)

**Comment by mmalerba** [comment]
We can't guarantee that styles targeted at just the custom class will have enough specificity to override our base styles. The class gives you a way to target that menu's popup, but you'll need to craft a selector with enough specificity to override the style you're interested in. There are many ways you could do this: `[role="menu"].custom-panel-class`, `.custom-panel-class.custom-panel-class`, `body .custom-panel-class`, etc. Example: https://stackblitz.com/edit/components-issue-yhosky?file=src%2Fapp%2Fexample-component.html,src%2Fstyles.scss
