### ISSUE TITLE
docs-bug(material design spec compliancy / compatibility): what process/system is used for this?

### ISSUE THREAD

**Issue by michahell** [angular/components#28006]
### Documentation Feedback

Hi,

A couple of questions came up in our team regarding Angular Material's compatibility and **parity** to material design specs.

We noticed that - for example - the `Expansion panel`, which was introduced in material design v1 (https://m1.material.io/components/expansion-panels.html#) still exists in the latest Angular Material version (https://material.angular.io/components/expansion/overview)

However, the expansion panel as a design component is not present in the material design v2 spec (except for list component expand-and-collapse: https://m2.material.io/components/lists#types no deeplink, search `expand and collapse`)

The first question is this:
Was it an explicit decision to keep supporting previous Material Design spec design components as opposed to dropping them and is this documented somewhere?

The second question is actually a followup question of the first: 
If it was [an explicit decision], is there some sort of deprecation policy for components that are phased out in future Material Design spec versions?

### Affected documentation page

https://material.angular.io/components/expansion/overview

**Comment by mmalerba** [comment]
Hi, thanks for your questions.

> The first question is this:
> Was it an explicit decision to keep supporting previous Material Design spec design components as opposed to dropping them and is this documented somewhere?

Yes, even though some of the components that we created are no longer part of the official spec, we think they still provide significant value for developers, so we have decided to retain them and keep them in line with the general guidelines of the spec (e.g. what colors, typography, border-radiuses, etc. to use).

> The second question is actually a followup question of the first:
> If it was [an explicit decision], is there some sort of deprecation policy for components that are phased out in future Material Design spec versions?

We follow the same [deprecation policy](https://angular.io/guide/releases#deprecation-practices) as the Angular framework. The short version is: if we decide to deprecate a component, it will remain as part of the library for at least the following two major releases before eventually being removed.
