### ISSUE TITLE
feat(cdk/a11y): isFakeMousedownFromScreenReader - Layout thrashing (forced layout reflow)

### ISSUE THREAD

**Issue by janousek** [angular/components#28010]
### Feature Description

The current implementation of the isFakeMousedownFromScreenReader function results in [Layout thrashing / forced layout reflow](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing). This method is called by InputModalityDetector on every mouse down event. This causes performance issues when using virtually any component that uses InputModalityDetector (CdkMenuTrigger for example).

Layout thrashing is triggered by this line:
https://github.com/angular/components/blob/01a95013c6ae0b7bce31f74ec8e1d4afe3749cda/src/cdk/a11y/fake-event-detection.ts#L18C35-L18C35
Which is caused by using the offsetX and offsetY properties.

It would be good to use another solution to detect fake mousedown events (without usage of these properties).

Based on my tests, it should be possible to use the screenX and screenY properties, which are also 0. But unlike offsetX and offsetY, they don't cause layout thrashing

**Comment by mmalerba** [comment]
Thanks for reporting! This does indeed seem like it would be bad for performance. I've opened a PR to fix it.
