### ISSUE TITLE
docs-bug(Form field input): Best way to adjust input outlined border width on focus? 

### ISSUE THREAD

**Issue by hisham** [angular/components#28023]
### Documentation Feedback

The documentation at https://material.angular.io/guide/customizing-component-styles and https://material.angular.io/guide/theming is not specific enough on how to best customize component style properties like the width of an outlined border when the input has focus. 

I came up with the below solution:
```
mat-form-field .mdc-text-field--focused .mdc-notched-outline > * {
  border-width: 1.5px !important;
}
```

The react version of material web suggests a mixin type approach but I tried it in angular and it didn't work for me: https://github.com/material-components/material-components-web-react/issues/941

Any guidance on this would be helpful. 

### Affected documentation page

https://material.angular.io/guide/customizing-component-styles

**Comment by wagnermaciel** [comment]
Hey, the current best way to do this would be to override our css variables, which are part of our new (unfinished) tokens api

Currently there is no guarantee for how components will behave when these tokens are modified - e.g. increasing border bottom makes icons align funny (idk if this actually happens, I'm just giving an example)

Here's an example:
https://stackblitz.com/edit/kcevmm?file=src%2Ftheme.scss
