### ISSUE TITLE
bug(CDK DragAndDrop): Dragging items between CdkDropLists from which at least one is contained in an element with transition property (for transform) does not work

### ISSUE THREAD

**Issue by DevLapar** [angular/components#28051]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Dragged items from one CdkDropList to another CdkDropList (let's call it Droplist2)  that is contained in an HTML element that moves by the means of transform: translate(x,y) **with a transition property** does not respond to the Droplist2 and can therefore not be dropped in it. However when commenting out the transition property but retaining the transform(x,y) property everything works fine and as intended

Bug happens when you enable transition on .example-container.hello.
If transition is disabled draggin items from To do to Done is working fine
However, when enabling transition (anything above 0s) the items from To Do
do not respond to the Done droplist anymore and you can't drop an item in it.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/drag-drop-inside-another-container-mprxck?file=app%2Fcdk-drag-drop-connected-sorting-example.html,app%2Fcdk-drag-drop-connected-sorting-example.ts,app%2Fcdk-drag-drop-connected-sorting-example.css
Steps to reproduce:
1. Open the CSS panel (cdk-drag-drop-connected-sorting-example.css)
2. Comment or Uncomment the "transition" property from .example-container.hello
3. Try dragging an item from the To Do list to the Done line
4. When transition property is commented out (so it's not active) dragging items works fine between Lists
5. When transition property is not commented (so it's active) dragging items does not work between Lists

### Expected Behavior

The dragged item should respond to the Done CdkDropList and should put itself into the Done list when entered/hovered over the Done list

### Actual Behavior

If transition property is active the dragged item does not respond to the Done CdkDropList and is therefore **not able** to put itself in the Done list. 

However if you comment out the transition property on .example-container.hello (in CSS file), the dragged item does respond to the Drop list and **is able** to put itself into it

### Environment

- Angular: v14
- CDK/Material: 7.3.6
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This isn't something we support really. For performance reasons the drag&drop module only measures the containers once when the dragging starts. Since there's an animation, it's possible that the measurement will happen while the animation is running. You might be able to work around it by adding `cdkDragStartDelay` equal to the duration of the animation.

**Comment by crisbeto** [comment]
I'm closing the issue since this isn't something we support.
