### ISSUE TITLE
docs-bug(stepper): Can't find any documentation on changing the default mat-step-header tabindex

### ISSUE THREAD

**Issue by smoothiesrock** [angular/components#28064]
### Documentation Feedback

I'm unable to find any supporting documentation for programmatically overriding the default mat-step-header tabindex behavior in any of the stepper variants. By default, the first or selected element has  tabindex="0", while the remaining nodes are set to tabindex="-1". Currently, there doesn't appear to be a recommendation for making all mat-step-headers keyboard focusable (or tabindex="0"), and visible to screen readers.

Thank you for your insight.

https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

### Affected documentation page

https://material.angular.io/components/stepper/overview

**Comment by wagnermaciel** [comment]
You can use arrow keys to move focus to the next mat-step-header
