### ISSUE TITLE
bug(mdc-icon-button): adding border to mat-icon-button causes icon to become misaligned

### ISSUE THREAD

**Issue by Vbuddies** [angular/components#28084]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the basic implementation of mat-icon-button the icon inside the button is properly aligned as expected within the button. It is centered both vertically and horizontally.

When a border is added to the mat-icon-button it shifts the icon down and to the right by the size of the border.

For instance a CSS border like so:
  border: 1px solid black
would cause the icon to move down by 1px and right 1px, this causes the icon to now be misaligned.

This is almost unnoticeable on small borders, but is increasingly obvious as the border gets bigger.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-8mcihf?file=src%2Fapp%2Fexample-component.html

You should be able to see once loaded that the icons are not centered within their border/parent element(button).

### Expected Behavior

Expect the icon within a mat-icon-button to be centered with or without border, and no matter what size the border is.

### Actual Behavior

The border width affects the position of the icon within the mat-icon-button causing it to not be centered.

### Environment

- Angular: v16.2.0
- CDK/Material: v16.2.0

**Comment by wagnermaciel** [comment]
Hi, changing the border of the icon button like this is not something the library supports as it is outside of the material design spec
