### ISSUE TITLE
Does v17 still needs Zone.js?

### ISSUE THREAD

**Issue by jon9090** [angular/components#28081]
### Feature Description

Does v17 still needs Zone.js?

**Comment by crisbeto** [comment]
Yes, there isn't a viable alternative for us at the moment.

**Comment by Casimodo72** [comment]
@crisbeto : Could you narrow down the range of that moment for us? I.e. months or years? Hard to make decisions on our side if we want to get rid of Zone.js without knowing if we get stuck using material.
