### ISSUE TITLE
bug(ALL): CSS variable fallback values not present in v17

### ISSUE THREAD

**Issue by neodescis** [angular/components#28100]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.x

### Description

In our applications, we have built CSS for the MDC components without applying an MDC theme. We include mat.core(), and we build on that. It seems that in v17, the base non-themed CSS for many (all?) components, as defined in the published .mjs files, no longer include fallback values for when the --mdc* variables are not defined. Take slider for example. Here is a rule published in 16.x as part of slider.mjs:

```
.mat-mdc-slider .mdc-slider__thumb-knob{border-radius:var(--mdc-slider-handle-shape, 50%); ...
```

In v17, there is no fallback value in slider.mjs:

```
.mat-mdc-slider .mdc-slider__thumb-knob{border-radius:var(--mdc-slider-handle-shape); ...
```

I am guessing this change was intentional, but not having those fallback values is breaking the styling of our applications. For example, given the lack of the above fallback, the slider thumb knob is no longer rounded How can we get the default values present in 16.x to be present in 17? Is there some way to set the variables to their defaults?

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-cawym5
Steps to reproduce:
1. Include only mat.core() in the application's CSS
2. See slider thumb is square

### Expected Behavior

CSS variable fallback values to be present, slider thumbs to be rounded

### Actual Behavior

CSS variable fallback values are not present, slider thumbs are square

### Environment

- Angular: 17.0.1
- CDK/Material: 17.0.0
- Browser(s): Chrome 119
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Yes, this was intentional. Our components are meant to be consumed with themes and providing the fallback values was masking bugs where people didn't provide the themes. To get the values, you should include the slider theme.
