### ISSUE TITLE
feat(COMPONENT): MatSuffix stand alone

### ISSUE THREAD

**Issue by hkashlan** [angular/components#28115]
### Feature Description

MatSuffix standalone

### Use Case

In my controls I always having a clear button as a suffix ex:

```
            <mat-form-field>
                <mat-label>any</mat-label>
                <mat-select formControlName="age">
                     ....
                </mat-select>
                <button mat-icon-button matIconSuffix
                        *ngIf="form.controls.age.value"
                        (click)="form.controls.age.reset()">
                    <mat-icon svgIcon="ak-close"></mat-icon>
                </button>
            </mat-form-field>
```

I was trying to replace this with a component to not repeat the code, so I created app-clear-value component 
so now the code
```
            <mat-form-field>
                <mat-label>any</mat-label>
                <mat-select formControlName="age">
                     ....
                </mat-select>
                <app-clear-value matIconSuffix />
            </mat-form-field>
```
now as you can see  `app-clear-value` is always matIconSuffix,

I tried the host MatSuffix but it was saying `Host directive MatSuffix must be standalone`
![image](https://github.com/angular/components/assets/4923194/1f7f40cf-cfd0-4a27-98ac-7aeeae155b48)

**Comment by crisbeto** [comment]
We're working on converting all directives to standalone. Should be covered by https://github.com/angular/components/issues/26036.
