### ISSUE TITLE
bug(Dialog): cannot use material components within dialogs

### ISSUE THREAD

**Issue by Burgov** [angular/components#28127]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Our application used to be an AppModule, I'm now rebuilding it to a standalone AppComponent and using the modern way of bootstrapping applications.

I'm running into a weird issue though. Cdk components work fine throughout the application, except when I use them in MatDialogs. Then, I get errors like these:

```
NullInjectorError: No provider for InjectionToken cdk-connected-overlay-scroll-strategy!
```

What could be the cause for this?

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

-

### Actual Behavior

-

### Environment

```
Angular CLI: 17.0.0
Node: 18.17.1
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.0
@angular/cli                    17.0.0
@angular/fire                   16.0.0
@angular/google-maps            17.0.0
@angular/material               17.0.0
@angular/ssr                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
webpack                         5.88.2
zone.js                         0.14.2
```

**Comment by spock123** [comment]
FWIW we don't have issues with this, would you have more details? I might be able to help out

**Comment by wagnermaciel** [comment]
Closing since as @spock123 mentioned, this is not debuggable without more details, and no further details or examples were provided
