### ISSUE TITLE
bug(MATOPTION): Regression in Material 17: failing compilation

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/components#28134]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.12

### Description

When upgrading from material 16.2.12 to 17.0.0 ; when a jest test runs and the class has a dependency to MatDialog:

<img width="1101" alt="image" src="https://github.com/angular/components/assets/1098243/7e939bac-ee59-4e9f-94e3-df0277a745f3">

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

no crash

### Actual Behavior

crash

### Environment

- Angular: 17.0.3
- CDK/Material: 17.0.0
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by crisbeto** [comment]
This error is happening due to the fact that we're using the new `@if` syntax in v17 of Material. I'm wondering if it somehow isn't pulling in v16 of Angular into the test. Do you get the same error when running the app?

**Comment by LanderBeeuwsaert** [comment]
@crisbeto ahhh, indeed, we still have a dependency using Angular Material 16
https://github.com/h2qutc/angular-material-components/pull/371
so probably that one is pulling it in.
However the application itself runs.
Is there a way to override this?

**Comment by crisbeto** [comment]
I think you would have to figure out which one of your dependencies is pulling in Angular 16 and update it. I believe Material should allow Angular 17 to be installed.

**Comment by crisbeto** [comment]
Closing this since we can't do much about it on our end.
