### ISSUE TITLE
bug(MatFormField): mat-form-field and mat-icon with new @if @else condition

### ISSUE THREAD

**Issue by AlexKorole** [angular/components#28172]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-icon for mat-form-field shows below mat-form-field component

Code: 
```
 <mat-form-field class="full-width" appearance="fill">
        <mat-label translate>attributes.FILE</mat-label>
        <input
          matInput
          readonly
          [required]="!editMode"
          formControlName="FILE"
          (click)="onImageFileClick()"
          class="input-file"
        />
        @if (isFolder) {
        <mat-icon matSuffix (click)="onClickItem()" style="cursor: pointer">folder</mat-icon>
        } @else {
        <mat-icon matSuffix (click)="onDeleteItem()" style="cursor: pointer">clear</mat-icon>
        }
      </mat-form-field>
```

![image](https://github.com/angular/components/assets/37747633/cf0f8196-7b5f-471d-afd3-38e758aa9264)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Create mat-form-field
2. Add 2 mat-icons with @if @else condition
3. Run application

### Expected Behavior

mat-icon should be on the right side of mat-form-field.

![image](https://github.com/angular/components/assets/37747633/96513bd7-5b57-459e-90ee-ef293783e9cb)

### Actual Behavior

mat-icon for mat-form-field shows below mat-form-field component.

![image](https://github.com/angular/components/assets/37747633/e9522177-9fd2-4618-a940-dfe3d713b350)

### Environment

- Angular: 17.0.2
- CDK/Material: 17.0.0
- Browser(s): Chrome Version 119.0.6045.160
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Unfortunately this is a limitation with how content projection works in the control flow (see https://github.com/angular/angular/pull/52414). There are a couple of ways to work around it:

1. Have a separate `@if` around each `<mat-icon>`.
2. Wrap the `@if {} @else {}` with `<ng-container matPrefix>`.
