### ISSUE TITLE
bug(Documentation website): Angular Material Documentation website not loading

### ISSUE THREAD

**Issue by rayansailani** [angular/components#28181]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

The following - https://material.angular.io/ is not opening at all! 

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

should open.

### Actual Behavior

taking too long to open.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Seems to work for me on a couple of different devices. This might be a problem on your end.

**Comment by mmalerba** [comment]
It loads for me as well, likely that this was an issue on ther user's end or some transient issue that has been resolved
