### ISSUE TITLE
Angular material and angular SSR == slow performance / high CLS

### ISSUE THREAD

**Issue by elgerm** [angular/components#28189]
### Is this a regression?

- [ ] No, but since angular ssr is a first class citizen now, it does matter more

### Description

Using angular material with angular SSR will lead to degraded performance. Because it will render from server AND re-render in the browser. Leading to large layout shifts and generally slower performance than no ssr at all.

From what I see in the source code the following components are skipped from hydration:
- drawer
- sidenav
- menu
- tab-group
- table
- autocomplete
- select
- stepper
- table
- chip-listbox

Encapsulating components like sidenav, drawer and tab-group should not be skipping hydration.

### Reproduction

Gifthub example repo: [here](https://github.com/elgerm/sidenav)
Steps to reproduce:
1. Add SSR
2. Add Material

### Expected Behavior

no re-rendering 

### Actual Behavior

components don't get hydrated

### Environment

- Angular:  17
- CDK/Material: 17
- Browser(s): all of them

**Comment by muchbetterug** [comment]
+1 its a big stopper from being awesome

**Comment by jwittekind** [comment]
+1 I'm confused by the log message "1 component(s) were skipped" even when i did not use ngSkipHydration anywhere.
Additionally i'd like to know what exact components got skipped and why. How can i make sure all components get hydrated properly. 

I noticed a huge difference in client hydration performance as soon as any component get's skipped during hydration.
On pages where i have skipped components the final hydration log message appears few seconds later than on other pages where all components are hydrated.

Please add Information to the log message

**Comment by mmalerba** [comment]
This should be fixed in 17.1, see: #28356 #28382 #28366 #28343 #28260
