### ISSUE TITLE
bug(mat-button): Basic button doesn't apply density config

### ISSUE THREAD

**Issue by ulrichson** [angular/components#28191]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Basic button with a `density < 0` defined in the theme doesn't have the same height as other button types:

![Screenshot 2023-11-27 at 17 17 08](https://github.com/angular/components/assets/449600/c971d4db-1a59-4fec-858d-317276b9b019)

This is the theme config:

```
$theme: mat.define-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      warn: $theme-warn,
    ),
    density: -3,
    typography: mat.define-typography-config(),
  )
);
```

In v16 it had the same height as other buttons.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/ujsqvj?file=src%2Ftheme.scss

### Expected Behavior

Basic button has same height as other button types when a `density < 0` is applied.

### Actual Behavior

Basic button has the default height regardless of `density` value

### Environment

- Angular: 17.0.4
- CDK/Material: 17.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by crisbeto** [comment]
This seems like it has been resolved. See https://stackblitz.com/edit/so7cyl?file=src%2Fstyles.scss
