### ISSUE TITLE
bug(theming/migration): `@angular/material/theming` SCSS entrypoint removed in v17

### ISSUE THREAD

**Issue by benelliott** [angular/components#28204]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.x

### Description

The `@angular/material/theming` entrypoint is broken in v17.x.

It looks like the `src/material/_theming.scss` file was deliberately removed as part of https://github.com/angular/components/commit/86e9e524c3234f44eece21632048cd4290e5f3f4#diff-bfa19b8f86d56d399fc0cb86ac55e1b95d161f081beb123cd2bcf31196eae030

However, I can't seem to find any mention of this breaking change in the release notes, nor is the problem automatically fixed by the migration schematic.

Additionally, the entrypoint still appears in the package.json:
https://github.com/angular/components/blob/main/src/material/package-base.json#L20

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Either the entrypoint should still work, or there should be some documentation as to how to migrate away from it.

I was previously using it to import public values such as `$light-primary-text` for use in my own palettes.

### Actual Behavior

The entrypoint no longer works, but still appears in the package.json.

### Environment

- Angular: 17.x
- CDK/Material: 17.x
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by thomasRS8000** [comment]
Any temp workaround for this? I used `angular-material-theme($my-theme)` from the `@angular/material/theming` import up till now. If I follow the [material theming guide](https://material.angular.io/guide/theming) and use `mat.all-component-themes($my-theme);` or any other proposition my theme stays broken

**Comment by mo-ian-watkins** [comment]
Seeing the same issue here on migrating Nx /Angular to 17.x

**Comment by jkapongo** [comment]
Seems to have been moved to `@angular/material/core/theming/theming`

**Comment by Michel73** [comment]
> Seems to have been moved to `@angular/material/core/theming/theming`

I don't think it's moved. It was already there in v16.

**Comment by dburgos92** [comment]
I just remove the import , and witth '@use '@angular/material' as mat;' my theme working well. It`s very strange

**Comment by benelliott** [comment]
Hi @mmalerba , the issue occurs regardless (I was using `@use`).

**Comment by benelliott** [comment]
@mmalerba Can you reopen this please? It has nothing to do with `@use`.

**Comment by KarolZirex** [comment]
Anyone fixes that problem?

**Comment by dangigrv** [comment]
Do we have any workaround

**Comment by scurtis7** [comment]
The only way I could get an `@import` to work was make it a relative path, which is horrendous but works.
From: `@import "src/assets/styles/variables";`
To: `@import "../../../../assets/styles/variables";`

**Comment by imasip** [comment]
> Using Sass `@import` for Angular Material has been deprecated for a while (since at least v12 I believe). In v17 we removed CSS that was only there for backwards compatibility with `@import`. All usages of our Sass should go through `@use` now.

I'm apply this solution and fix the problem. You should change your main.scss for usage @use instead on @import.

**Comment by born2net** [comment]
any resolution to this issue? same problem here :/

**Comment by mmalerba** [comment]
For our `@use` API, everything can be accessed from the top-level entry point: `@use '@angular/material' as mat;`. The `@angular/material/theming` entry point was only exposed to support pre-existing `@import` statements which were deprecated a long time back
