### ISSUE TITLE
bug(MatSlider): MatSliderRangeThumb input width is not changed if the input value is changed dynamically

### ISSUE THREAD

**Issue by sdiachenko** [angular/components#28206]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The MatSlider does not changes the width of the input[matSliderStartThumb] and the input[matSliderEndThumb] when a user changes the inputs value dynamically.

<img width="1522" alt="image" src="https://github.com/angular/components/assets/40065298/c7822536-cb06-4eb1-8694-eaea71d69de0">

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-pkhpjl?file=src%2Fapp%2Fexample-component.ts
Steps to reproduce:
1. Refresh the page
2. Click on "next step" button
3. Drag the slider's right thumb to right. Drop it.

### Expected Behavior

The "end" thumb has the respective value

### Actual Behavior

The "start" and "end" thumb are wrong placed

### Environment

- Angular: 15.2.6 - 16.2.1
- CDK/Material: 15.2.6 - 16.2.1
- Browser: Safari, Chrome
- Operating System: macOS, Windows

**Comment by wagnermaciel** [comment]
Looks like the "inactive" widths are not getting updated when the slider value is being programmatically updated. I'll look into this more today
