### ISSUE TITLE
bug(Slider): Tooltip is not showed on thumb hover

### ISSUE THREAD

**Issue by alex-waverley** [angular/components#28211]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Slider component doesn't work properly in Safari after changing slider's value.

https://github.com/angular/components/assets/84070515/186bb5cc-36bb-47d2-a7c1-8e86f9c5adc3

Reason: mat-slider-visual-thumb element is not getting `mdc-slider__thumb--with-indicator` css class on thumb hover 

### Reproduction

Steps to reproduce:
StackBlitz link: https://stackblitz.com/edit/components-issue-2ytten?file=src%2Fapp%2Fexample-component.html
1. hover thumb - tooltop is showed
2. click on slider to change its value
3. hover thumb - now tooltip is not showed

### Expected Behavior

Tooltip must be always showed on thumb hover.

### Actual Behavior

Tooltip is not showed on thumb hover after changing slider's value.

### Environment

- Angular: 16.2.1
- CDK/Material: 16.2.1
- Browser: Safari 16.6 (18615.3.12.11.2)
- Operating System: macOS Ventura 13.5.2

**Comment by wagnermaciel** [comment]
Increasing to p2 because this bug is annoying to me lol. Such a small bug but so annoyingly easy to reproduce that I need to fix it 😅
