### ISSUE TITLE
bug(autocomplete): requireSelection in an autocomplete with custom filter breaks valueChanges

### ISSUE THREAD

**Issue by XEvansWTW** [angular/components#28215]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using a custom filter (as shown in the example in the autocomplete documentation https://material.angular.io/components/autocomplete/overview), the valueChanges functionality does not work when requireSelection is added to the component.

### Reproduction

Stack Blitz
https://stackblitz.com/edit/vyil2i?file=src%2Fexample%2Fautocomplete-filter-example.ts,src%2Fexample%2Fautocomplete-filter-example.html

1. valueChanges pipe does not run when requireSelection is on autocomplete component.
2. Removing requireSelection causes it to work (see output in console).
3. This does not happen on a normal autocomplete component which doesn't have a custom filter.

Note that this demo uses minimal changes from the example given in the component's documentation.

### Expected Behavior

valueChanges pipe works as it does with a normal autocomplete without a custom filter.

### Actual Behavior

valueChanges pipe does not work at all.

### Environment

Angular 17 
Angular 17.0.1 material

**Comment by crisbeto** [comment]
This is sort of the point of `requireSelection`: it's only going to emit the event to the form control when the user selects a value from the list. If you're depending on `valueChanges` to do the filtering, you should use something like the `input` event instead.
