### ISSUE TITLE
docs-bug(Customizing Typography): Input?

### ISSUE THREAD

**Issue by benclarkdev** [angular/components#28245]
### Documentation Feedback

It seems that `input` was deprecated as a typography level in v15, but in "Customizing Typography" for v15-current, we have:

> The button and input typography levels do not map to CSS classes.

It seems like that is an oversight?

### Affected documentation page

guide/typography

**Comment by GiftLanga** [comment]
Hi @benclarkdev I'm trying to work on this issue but I'm failing to understand what the issue might be. Could you please explain further. Thanks.
