### ISSUE TITLE
bug(MatButton): MatButton leaking memory when removed from DOM with ngIf

### ISSUE THREAD

**Issue by csokviktor** [angular/components#28241]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

Garbage collection does not happen when buttons are deleted from DOM using ngIf. The issue does not occur with MatLegacyButtonModule only with the MatButtonModule.

Other components seem to work fine using the same testing methodology.

### Reproduction

Steps to reproduce:
1. Create a new Angular app
2. Use two material buttons in a component. The two buttons switch each other out using a bool variable and ngIf.
3. Press the available button multiple times.
4. Inspect memory usage.

Example code:
```ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.scss'],
  standalone: true,
  imports: [MatButtonModule, CommonModule],
})
export class DemoComponent {
  public shown = false;
}
```

```html
<button mat-button *ngIf="shown" (click)="shown = false">Demo shown</button>
<button mat-button *ngIf="!shown" (click)="shown = true">Demo not shown</button>
```

### Expected Behavior

 Buttons are garbage collected.

### Actual Behavior

Buttons are not garbage collected.
At startup:
![image](https://github.com/angular/components/assets/69304231/e04682a2-b950-4295-9fa6-de9bfcbef046)
After multiple clicks:
![image](https://github.com/angular/components/assets/69304231/7c53fa8b-608f-41d4-8b29-67468931ba85)

### Environment

- Angular:16.2.0
- CDK/Material:16.2.0
- Browser(s): Chrome Version 119.0.6045.200 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This seems identical to https://github.com/angular/components/issues/28240.
