### ISSUE TITLE
bug(MatButton): JS event listeners are not cleaned up

### ISSUE THREAD

**Issue by tibi0010** [angular/components#28240]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Hi!

For me it seems like whenever a new mat-button is clicked by the user and then it gets destroyed it leaves behind JS event listeners, DOM Nodes and JS heap size won't decrease. With every new mat-button clicked there are 4 new event listeners and 8 new DOM node.

Edit: Seems like when you just hoover the button without clicking it, it will leave some detached HTMLButtonElements.

I couldn't reproduce this in Angular Material v13 and v14 (MatLegacyButton), but can be reproduced easily in v16 and v17.

![button_click](https://github.com/angular/components/assets/153174614/f479b864-bdab-4e26-b82d-2e7b2090ca30)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-ym2bn1?file=package.json
Please download the code from stackblitz and run it locally. It doesn't matter if you serve it or build it.
Steps to reproduce:
1. Create a mat-button
2. Click it
3. Destroy it
4. Repeat step 1 to 3 while observing JS event listener count in Chrome performance monitor, run garbage collector manually

### Expected Behavior

JS event listener and DOM node count returns to its initial value after garbage collection.

### Actual Behavior

JS event listener and DOM node count increases every time a new button is clicked, even if we remove them with ngIf. It didn't decrease over time. Same behaviour can't be observed using MatLegacyButton

### Environment

- Angular: 16.2.12
- CDK/Material: 16.2.12
- Browser(s): Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Microsoft Windows Version 22H2 (OS Build 19045.3693)

**Comment by csokviktor** [comment]
Hey @crisbeto,

Thanks for your efforts fixing this issue. I have seen that the fix is already included in 17.0.4. Are you planning to include it in v16 as the issue also occures on that version?

**Comment by crisbeto** [comment]
I can bring it up in our next team meeting after the holidays, but usually we don’t backport fixes like this.

**Comment by crisbeto** [comment]
16.2.13 has been published which includes this fix.

**Comment by csokviktor** [comment]
Thanks for the effort! Will report it to the team to update our projects.
