### ISSUE TITLE
bug(Main Site v6.material.angular.io/components/sidenav/examples): Error when try to see example on stackblitz.com

### ISSUE THREAD

**Issue by terabajt** [angular/components#28255]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I can't to run help: https://stackblitz.com/angular/dyljjkygjgl?file=app%2Fsidenav-autosize-example.ts

Error in material-module.ts
The entrypoint for '@angular/cdk' could not successfully be resolved. The file '/turbo_modules/@angular/cdk@6.4.7/drag-drop' does not exist. Please log an issue with the package author or check for an updated version of the package.
<img width="1501" alt="Zrzut ekranu 2023-12-9 o 18 22 58" src="https://github.com/angular/components/assets/78153419/3e2faec8-8adb-41d3-911d-468b0024b0ad">

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I want to see example on site: https://v6.material.angular.io/components/sidenav/examples when i click to show on https://stackblitz.com/angular/rkxymaevjpj?file=app%2Fsidenav-overview-example.ts

### Actual Behavior

I see a bug: Error in material-module.ts
The entrypoint for '@angular/cdk' could not successfully be resolved. The file '/turbo_modules/@angular/cdk@6.4.7/drag-drop' does not exist. Please log an issue with the package author or check for an updated version of the package.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing since we don't backport fixes to such old versions.
