### ISSUE TITLE
bug(mat-table): Opening material table breaks previous styles on table

### ISSUE THREAD

**Issue by JalmariO** [angular/components#28272]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

version 14

### Description

I've updated my angular project from version 14 to 17 and tried to sort out problems that followed.
I can't figure out why my table styles breaks every time I open material table in my app.
Mat-mdc-row is always defaultin to 52px, even if I have set it to something else.

### Reproduction

StackBlitz link: https://stackblitz-starters-zegkxu.stackblitz.io (https://stackblitz.com/edit/stackblitz-starters-zegkxu)
Steps to reproduce:
1. Click row on table
2. New dialog with mat table should open and underlying tables row heigth changes.

### Expected Behavior

Height should not be affected.

### Actual Behavior

Height is changed to default (52px).

### Environment

- Angular: 17
- CDK/Material: 17

**Comment by JalmariO** [comment]
Here's the same code with version 14
https://stackblitz.com/edit/ngx-14-title-demo-u13zvk

**Comment by wagnermaciel** [comment]
Custom css overrides like this is not supported. It would be infeasible to not change underlying dom & css of these components while continuing to make progress on the library & keeping up with the material design spec
