### ISSUE TITLE
SnackBar no longer supports panelClass

### ISSUE THREAD

**Issue by incy-tron** [angular/components#28270]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 14.

### Description

https://github.com/angular/components/issues/26928#issuecomment-1533422940
Responding to closing of the referenced issue, which indicates "... we generally don't support style overrides like this".  Which contradicts the fact that you can provide a MatSnackBarConfig object when calling open on snackbar.  This config allows the passing in of "Extra CSS classes to be added to the snack bar container.", which doesn't work with the new MDC migration.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I was expecting to see my css class definition honored.

### Actual Behavior

Class definition not honored.  And there is no easy way to fix this without referencing the hidden css class definitions for the Snackbar.

### Environment

 "@angular/cdk": "^15.2.9",
    "@angular/common": "^15.2.10",
    "@angular/compiler": "^15.2.10",
    "@angular/core": "^15.2.10",
    "@angular/forms": "^15.2.10",
    "@angular/material": "^15.2.9",

**Comment by crisbeto** [comment]
The class still gets added, but you may have to increase the specificity of the selectors in your style override.
