### ISSUE TITLE
bug(mat-progress-bar): Indeterminate progress bar not moving when using custom theme with CSS variables

### ISSUE THREAD

**Issue by sebastianhaberey** [angular/components#28288]
### Description

When a custom theme is [used and initialized with CSS variables](https://github.com/sebastianhaberey/progress-bar-bug/blob/main/src/custom-theme.scss), the indeterminate progress bar doesn't seem to move. I am guessing the cause lies in track color and indicator color being the same:

<img width="362" alt="Bildschirmfoto 2023-12-15 um 10 29 25" src="https://github.com/angular/components/assets/4152849/28e3b133-2a3f-47e6-a2d9-18683a3a6161">

@crisbeto I see that you've been [working on the theme file where the indicator and track colors are defined](https://github.com/angular/components/blob/main/src/material/progress-bar/_progress-bar-theme.scss), would you have any advice on this?

### Reproduction

StackBlitz link: https://stackblitz.com/~/github.com/sebastianhaberey/progress-bar-bug
Steps to reproduce:
1. Create Angular Material workspace
2. Define custom theme using CSS variables
3. Add mat-progress-bar component (indeterminate)

### Expected Behavior

Progress bar is moving

### Actual Behavior

Progress bar does not move

### Environment

- Angular CLI: 17.0.7
- Node: 20.10.0
- Package Manager: npm 10.2.3
- OS: darwin arm64

**Comment by crisbeto** [comment]
I'm guessing the issue comes from this line: https://github.com/angular/components/blob/main/src/material/core/tokens/m2/mdc/_linear-progress.scss#L34. Since the value is a variable, we can't change its opacity anymore. I'm closing the issue since this setup isn't something we support. You can work around it by adding this to your styles:

```
.mdc-linear-progress__buffer-bar {
  opacity: 0.75;
}
```
