### ISSUE TITLE
bug(Theming): Error during theming after switching from 15.0.3 to 17.0.4 version of Angular Material

### ISSUE THREAD

**Issue by vpeacock** [angular/components#28286]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.3

### Description

After switching from version 15.0.3 to version 17.0.4, I get an error when theming, namely when using the background value, there was no such error in 15.0.3 and everything worked correctly

```
(status-bar: #e0e0e0, app-bar: #f5f5f5, background: #fafafa, hover: rgba(0, 0, 0, 0.04), 
card: white, dialog: white, disabled-button: rgba(0, 0, 0, 0.12), raised-button: white, 
focused-button: rgba(0, 0, 0, 0.12), selected-button: #e0e0e0, 
selected-disabled-button: #bdbdbd, disabled-button-toggle: #eeeeee, 
unselected-chip: #e0e0e0, disabled-list-option: #eeeeee, tooltip: #616161) 
isn't a valid CSS value.
    ╷
 │   $background-color: mat-color($_background, background);
    │                                ^^^^^^^^^^^^ value
    │                      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
unknown function treated as plain CSS
```

### Reproduction

StackBlitz link: [stackblitz](https://stackblitz.com/edit/stackblitz-starters-az4zze?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fglobal_styles.scss&title=Angular%20Starter)

Steps to reproduce:
1. the error appears when building the application

### Expected Behavior

When theming, I want to use the background and foreground values

### Actual Behavior

I get an error when theming, namely when using the background value, 

### Environment

- Angular: 17.0.7
- CDK/Material: 17.0.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It looks like you're using the deprecated `@import` Sass API that was removed in v17 https://github.com/angular/components/pull/27571. You can replace the `mat-color` by adding `@use '@angular/material' as mat` to the top of the file and using `mat.get-color-from-palette()`.
