### ISSUE TITLE
bug(MatCalendar): MatCalendar/MatDatePicker does not work when inside a MatDialog

### ISSUE THREAD

**Issue by thencke** [angular/components#28294]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

There is a strange bug when I try to put a mat-calendar component inside a mat-dialog, even importing the date adapters and such it behaves like if the date adapter was not imported/loaded since it throws an error in console.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-msepdb?file=src%2Fmain.ts
Steps to reproduce:
1. Click on 'Open Dialog' button
2. The calendar will not show correctly

### Expected Behavior

To show the calendar just like if put directly in a 'base' component (not in a dialog)

### Actual Behavior

The calendar shows wrongly and an error is thrown in console.

### Environment

- Angular: 17.0.7
- CDK/Material: 17.0.4
- Browser(s): Chrome, Opera
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by thencke** [comment]
If use angular ngModules instead of standalone components, it seems to be working fine.

**Comment by chusothe41** [comment]
Add this to the dialog component
`providers: [
    {provide: DateAdapter, useClass: NativeDateAdapter},
    {provide: MAT_DATE_FORMATS, useValue: MAT_NATIVE_DATE_FORMATS},
  ],`

**Comment by thencke** [comment]
@chusothe41 it works, thanks, closing the issue.
