### ISSUE TITLE
feat(theming): expose the sass function `theme-remove`

### ISSUE THREAD

**Issue by nzbin** [angular/components#28298]
### Feature Description

https://github.com/angular/components/blob/956b86fc98241e3ed17128513163eaedd2843479/src/material/_index.scss#L153-L154

expose the sass function `theme-remove`  just like `theme-has`.

### Use Case

I created a material extensions library https://github.com/ng-matero/extensions and I need the function `theme-remove`.

**Comment by crisbeto** [comment]
Can you elaborate on what it would be used for?

**Comment by nzbin** [comment]
I implement the same mixin `all-color` and it uses the `theme-remove`.
https://github.com/ng-matero/extensions/blob/main/projects/extensions/core/color/_all-color.scss

If it doesn't expose from the material `index.scss`, I would have to copy the whole file `inspection.scss`.

**Comment by crisbeto** [comment]
Leaving it up to @mmalerba if we should expose this.

**Comment by mmalerba** [comment]
Yeah I think it makes sense to expose this. I don't think I intended to make it internal, probably just forgot to add it to the forward list

**Comment by mmalerba** [comment]
Here's a PR to expose it: https://github.com/angular/components/pull/28314

**Comment by crisbeto** [comment]
Closing as fixed in #28314.
