### ISSUE TITLE
bug(theming): expose undefined function `private-typography-config-level-from-mdc`

### ISSUE THREAD

**Issue by nzbin** [angular/components#28297]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

https://github.com/angular/components/blob/956b86fc98241e3ed17128513163eaedd2843479/src/material/_index.scss#L145-L148

The function `typography-config-level-from-mdc` is undefined in `mdc-helpers`. In fact, we can find the function here.

https://github.com/angular/components/blob/956b86fc98241e3ed17128513163eaedd2843479/src/material/core/typography/_definition.scss#L216-L217

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Expose the function `private-typography-config-level-from-mdc`.

### Actual Behavior

The function `private-typography-config-level-from-mdc` is undefined.

### Environment

- Angular: 17.0.7
- CDK/Material: 17.0.4
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
The functions that are exposed with a `private-` prefix aren't public APIs.

**Comment by nzbin** [comment]
@crisbeto Yes, I know `private-` is not public APIs. I just want to point it is a wrong expose. In fact, there is no `typography-config-level-from-mdc` in `mdc-helpers.scss` and it is defined in the `typography/_definition.scss`

**Comment by crisbeto** [comment]
Ah yeah, I think we can just remove those. IIRC we had to expose them for the legacy components which have been deleted.
