### ISSUE TITLE
bug(mat-select): 'disableOptionCentering' input option not working

### ISSUE THREAD

**Issue by eevardone** [angular/components#28293]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

In Angular Material v14, by default, the selected active option would be centered when you open up the dropdown. It was the 'disableOptionCentering' input option that would determine whether to center the active option over the trigger. 

After upgrading to Angular Material v16, this option has no effect, though the API documentation for v15+ still lists it as an available Input. Since there is an effort with v15+ to better align with Material Design Components (MDC), it seems that 'disableOptionCentering' functionality is not supported. If so, please update the API documentation and code to remove support of this input option.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/fe9vgg?file=src%2Fapp%2Fselect-overview-example.html
Steps to reproduce:
1. Open dropdown and select an option
2. Re-open dropdown and notice that the selected active option is not centered
3. Add 'disableOptionCentering' input and set to false on mat-select

### Expected Behavior

The selected active option would be centered when you re-open the dropdown.

### Actual Behavior

The selected active option is not centered when you re-open the dropdown. The dropdown options open directly below the mat-select component.

### Environment

- Angular: 16.2.12
- CDK/Material: 16.2.10
- Browser(s): Google Chrome (Version 120.0.6099.109)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
That's because the new select doesn't do the option centering anymore. It shows the dropdown either below or above the trigger. This is aligned with the Material spec and it simplifies the component internals.

**Comment by eevardone** [comment]
@crisbeto Thanks for the response. I figured it didn’t align with Material spec and glad it’s now simplified. 

How do we go about having the Angular Material update the API documentation as it still lists that centering as an input option? Misleading for new and old users.
