### ISSUE TITLE
bug(SnackBar): set value in afterDismissed did not update the view

### ISSUE THREAD

**Issue by albahrawy** [angular/components#28300]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When subscribed to snackBarRef.afterDismissed() and set any value did not update the view till the next change cycle. 
I tried with normal variables and signal and in zone

### Reproduction

you can check it here: [StackBlitz link](https://stackblitz.com/edit/kdplkt?file=src%2Fexample%2Fsnack-bar-overview-example.html,src%2Fexample%2Fsnack-bar-overview-example.ts)
Steps to reproduce:
1. Click on Show Snack Bar
2. the three values should be updated: that not happen until the next change cycle
- after dismiss
- after dismiss signal
- after dismiss valueFromZone

### Expected Behavior

-

### Actual Behavior

-

### Environment

Angular CLI: 17.0.6
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@angular/cdk                    17.0.3
@angular/material               17.0.3
@schematics/angular             17.0.6
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

**Comment by crisbeto** [comment]
It's missing a change detection run. Here's a working example: https://stackblitz.com/edit/kdplkt-kp82dw?file=src%2Fexample%2Fsnack-bar-overview-example.html,src%2Fexample%2Fsnack-bar-overview-example.ts
