### ISSUE TITLE
bug(cdkScrollable): Drag horizontal scrolling with cdkDropList item and cdkScrollable not working when dir = RTL

### ISSUE THREAD

**Issue by namnguyen2020** [angular/components#28326]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm trying to provide horizontal scrolling while dragging a cdkDropList item with cdkScrollable. As of right now the page can't scroll with dir='rtl' (hebrew language).

Note: Works fine with dir='ltr'

Is there a way i can improve this

### Reproduction

My html code:

```html
<div [dir]="'rtl'">
    <div class="dashboard" cdkScrollable>
        <div class="d-flex" cdkDropListGroup>
            <div class="board-list" *ngFor="let board of boards">
                <div class="order-status-list" *ngIf="board">
                    <div class="px-3 pb-3 pt-3 fw-bold">
                        <span>
                            {{ board.status }}
                        </span>
                    </div>
                    <div class="order-card-container pl-2" cdkDropList [cdkDropListAutoScrollDisabled]="false" [cdkDropListAutoScrollStep]="10" [cdkDropListData]="board.orders" (cdkDropListDropped)="drop($event)" [id]="board.status">
                        <order-card *ngFor="let order of board.orders" [order]="order" [cdkDragData]="order" cdkDrag (cdkDragStarted)="dragStarted($event)" (cdkDragEnded)="dragEnded()"> </order-card>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

``` 

### Expected Behavior

I'm expecting horizontal scrolling while dragging a cdkDropList item with cdkScrollable when dir='rtl' (hebrew language).

### Actual Behavior

I'm trying to provide horizontal scrolling while dragging a cdkDropList item with cdkScrollable. As of right now the page can't scroll with dir='rtl' (hebrew language).

### Environment

- Angular: 14.2.0
- CDK/Material: 14.2.7
- Browser(s): Chrome Version 120.0.6099.129 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 64-bit

**Comment by namnguyen2020** [comment]
Hi @crisbeto , when will there be a patch for version 14?
Thanks.

**Comment by crisbeto** [comment]
There won't be because v14 is outside of our LTS policy. Also we generally don't backport fixes like this.

**Comment by namnguyen2020** [comment]
I'm sorry, because I see version 14 is LTS

![image](https://github.com/angular/components/assets/104457163/1e9dd5a1-8949-4745-9a55-b086986b914a)

**Comment by crisbeto** [comment]
That's just the name of the release tag. LTS versions go back one year as per the version policy: https://angular.io/guide/releases#support-window. Worth noting that even if v14 was in LTS, this fix likely wouldn't have been backported since it isn't particularly severe.
