### ISSUE TITLE
bug(menu): @Input panelClass not working as described https://material.angular.io/components/menu/api V17.0.4

### ISSUE THREAD

**Issue by robertkieschke** [angular/components#28338]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Input "panelClass" dows not work as described https://material.angular.io/components/menu/api
But "class" does.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/fjghip?file=src%2Fexample%2Fmenu-position-example.html,src%2Fstyles.scss
Steps to reproduce:
1. Open menu
2. use inspector

### Expected Behavior

"panelClass" instead of "class" as described in https://material.angular.io/components/menu/api

### Actual Behavior

"class" instead of "panelClass"

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
`panelClass` is the property name on `MatMenu`, but the input name is `class`. This is described already by the `@Input('class')`.
