### ISSUE TITLE
docs-bug(@angular/google-maps): google.maps.Map is not a constructor

### ISSUE THREAD

**Issue by YouZag** [angular/components#28341]
### Documentation Feedback

I followed the documentation exactly. Using Angular 17. I added the GoogleMapsModule in the imports of my standalone component. I am getting an error of "google.maps.Map is not a constructor"

### Affected documentation page

https://github.com/angular/components/blob/main/src/google-maps/README.md

**Comment by YouZag** [comment]
Alright, I understand now.  The docs have been updated with main but the docs are ahead of the releases. I'm novice - anyone know how to use a commit before a tagged release?

**Comment by crisbeto** [comment]
Correct, the `main` branch shows the docs for version 17.1 which will have a simpler way of loading the Google Maps API, but it hasn't been released yet (#28307). You can find the current docs at https://github.com/angular/components/tree/17.0.x/src/google-maps.

**Comment by tolgatopkara** [comment]
i imported  provideHttpClient(withInterceptorsFromDi(),withJsonpSupport()), to my app.config , 
 and implement the component like => 
 https://github.com/angular/components/tree/16.2.x/src/google-maps on this, its standalone and its works
