### ISSUE TITLE
bug(mat-input): outlined inputs don't support RTL

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [angular/components#28344]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Any Angular Material form control that is using the "outline" appearance, looks messed up in RTL.
![image](https://github.com/angular/components/assets/106555838/11f74560-eacf-4a98-896f-429ba70bd89b)

without RTL they look like this

![image](https://github.com/angular/components/assets/106555838/261c1694-7222-4fc8-a670-9dbdb03b4e3d)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/yw2eyk?file=src%2Findex.html
Steps to reproduce:
1.  Add Material inputs like mat-select or matInput directive to an input/textarea
2. Make the direction of your html document RTL.

### Expected Behavior

That the inputs look fine in both RTL and LTR like the filled inputs

### Actual Behavior

The inputs borders and label look messed up and sliced to three different parts

### Environment

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.0
@angular-devkit/build-angular      17.0.0
@angular-devkit/core               17.0.0
@angular-devkit/schematics         17.0.0
@angular/cdk                       17.0.4
@angular/material                  17.0.4
@angular/material-moment-adapter   17.0.4
@schematics/angular                17.0.0
rxjs                               7.4.0
typescript                         5.2.2
zone.js          0.14.0

**Comment by crisbeto** [comment]
It's because we don't support setting the direction through CSS, because there's no performant way to detect it. You have to use the `dir` attribute. Here's a working example https://stackblitz.com/edit/yw2eyk-ybjn3c?file=src%2Findex.html.
