### ISSUE TITLE
bug(Stepper): Cdk Stepper selected property setter method issue

### ISSUE THREAD

**Issue by kiran-cm** [angular/components#28345]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Cdk Stepper selected property setter method indexOf not setting correct index.

 this.selectedIndex = step && this.steps ? **this.steps.toArray().indexOf(step)** : -1;

### Reproduction

Steps to reproduce:
1. Create stepper using [Cdk stepper guide](https://v16.material.angular.io/guide/creating-a-custom-stepper-using-the-cdk-stepper)
2. Add onClick on cdkStep
3. In onClick callback, set **this.selected = this.steps.get(index);**
4. **selectedIndex** property of CdkStepper class not working properly.

### Expected Behavior

**selectedIndex** property should be set properly correctly when we set **selected** from wrapper component.

### Actual Behavior

selectedIndex set to -1

### Environment

- Angular: v16
- CDK/Material: v16
- Browser(s): NA
- Operating System (e.g. Windows, macOS, Ubuntu): NA

**Comment by crisbeto** [comment]
This is likely down to your implementation. You have to wait for all the steps to be rendered before assigning the selected one (e.g. in `ngAfterContentChecked`).
