### ISSUE TITLE
feat(material-date-fns-adapter): add support for date-fns 3

### ISSUE THREAD

**Issue by MikaStark** [angular/components#28357]
### Feature Description

`date-fns` 3 is now available (https://blog.date-fns.org/v3-is-out/). It would be great Angular Material supports it in `material-date-fns-adapter` package.

**Comment by EchoInside** [comment]
Same request here👍 
I have also `date-fns` v.3 in project and need to implement adapter.

**Comment by Tyler-V** [comment]
Same here :)

**Comment by crisbeto** [comment]
No, we don't backport features.
