### ISSUE TITLE
Issue in Material/Select with ngx-scrollbar

### ISSUE THREAD

**Issue by vartikaagrawal411** [angular/components#28367]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I need to use ngx scrollbar inside mat select component. For that I am giving 
max-height like this
![image](https://github.com/angular/components/assets/149461813/3cf29e3c-0119-4bd0-8fb3-e2acd0f22833)
and autoHeightDisabled= false  ,
![image](https://github.com/angular/components/assets/149461813/6df3edd6-cc1a-4d51-a1bc-c95bbc2514b3)

but, mat select dropdown is not adjusting it's position on top,  and is getting clipped
![image](https://github.com/angular/components/assets/149461813/5cc21532-3db5-4dde-9714-9a4be8cea7d1)

### Reproduction
1. Go to Scroll-event section
2. see the behavior in given dropdown

StackBlitz link: https://stackblitz.com/edit/ngx-scrollbar-jpa7wb?file=src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.html,src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.module.ts,src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.scss,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

### Expected Behavior

mat select dropdown should adjust itself on top so that content don't get clipped

### Actual Behavior

mat select dropdown is not getting adjusted on top and is getting clipped

### Environment

- Angular: 16.1.15
- CDK/Material: 16.1.15
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
We don't support integrations with other libraries like this, because we can't support all the different combinations that are on npm.
