### ISSUE TITLE
"Select/Unselect" event for mat-tab-group

### ISSUE THREAD

**Issue by GhoshWorld** [angular/components#28361]
### Feature Description

In this mat-tab-group, I need a "Select Unselect" event for same tab. When I select the tab the tab is fully selected and the page is properly routing but when I go to sub-route on this same page then the page changes but the tab remains selected. At that time I want the tab to be unselected or the event is deleted.

**Comment by zarend** [comment]
Hello,

Thank you for reaching out on our issue tracker. I wondering if you could help us understand what you need from mat-tab-group. I don't think I understand *why* you need a "Select Unselect" event. The model for MatTabs is that one tab is selected at a time. MatTabs doesn't have a "null" state, so it's not possible for zero tabs to be selected.

The selectedTabChange output event is emitted when the active tab changes. https://material.angular.io/components/tabs/overview#events

I was wondering if you had a Stackblitz of your use case, or why you can't get what you need out of the existing API for tabs?

Best Regards,

Zach

**Comment by crisbeto** [comment]
Closing since there hasn't been any follow-up.
