### ISSUE TITLE
bug(MatAutocomplete): When setting `MatAutocomplete.requireSelection = true`  and using the `MatAutocomplete.displayWith` input parameter, the `MatInput`'s `FormControl.valueChanges` observable does not emit values on text input, only on value selection

### ISSUE THREAD

**Issue by vitale232** [angular/components#28378]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the `MatAutcomplete` with the input property `requireSelection` set to `true`, everything works as expected for the simple case (filtering an array of strings).

When setting `requireSelection` to `true` while _also_ using the `MatAtocomplete.dispalyWith` input property, the `FormControl.valueChanges` observable on the `MatInput` instance only fires when an element is selected from the list. When the user types into the keyboard, the observable does not fire, thus the suggestions do not filter.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/ea5mfd?file=src%2Fexample%2Fautocomplete-display-example.html
Steps to reproduce:
1. Focus on the input in the example.
2. Start typing. You'll notice that the list does not filter, and the `pre` element below the input still has a value of null
3. Select a value from the list with the keyboard or the mouse. You'll see that the `valueChanges` trigger, and the `pre` element contains our "complex object"

### Expected Behavior

I would expect typing in the input would trigger `valueChanges` with the text that's been input, similar to how it works when the `requireSelection` property is set to false. 

Additionally, I would expect that entering a value that is not present in the list would result in no changes to the selected value, as documented by the `requireSelection` documentation, even when it's used in conjunction with `displayWith`

### Actual Behavior

When using `displayWith` in conjunction with `requireSelection`, the input `valueChanges` are only triggered by selecting a value from the list manually. Typing changes into the input _does not_ fire the observable. 

### Environment

- Angular: 17.0.4
- CDK/Material: 17.0.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): N/A

**Comment by shmert** [comment]
Same issue here. I see the culprit, but don't know how to fix it. 

autocomplete-trigger.mjs

```
_handleInput(event) {
            ...
            // If selection is required we don't write to the CVA while the user is typing.
            // At the end of the selection either the user will have picked something
            // or we'll reset the value back to null.
            if (!this.autocomplete || !this.autocomplete.requireSelection) {
                this._onChange(value);
            }
```

**Comment by crisbeto** [comment]
This is sort of the point of `requireSelection`: only a value selected from the list will be propagated to the CVA. If we emitted every value, it would be the same as it is right now. The other option would be to emit as the user is typing and then at the end either emit the selection or null, but we had feedback from users (https://github.com/angular/components/pull/27423) that this isn't useful because there's no way to distinguish whether the value comes from the user typing or the user selecting.

**Comment by vitale232** [comment]
Thanks for the additional context. It's eye-opening to see how you all arrived at this implementation.

While it's unfortunate the `requireSelection` feature is less useful in this common use case, it's relatively straightforward to create a workaround within application code.

https://stackblitz.com/edit/ea5mfd-grp4zx?file=src%2Fexample%2Fautocomplete-display-example.ts,src%2Fexample%2Fautocomplete-display-example.html
