### ISSUE TITLE
docs-bug(COMPONENT): Typo 

### ISSUE THREAD

**Issue by iamgreenintro** [angular/components#28387]
### Documentation Feedback

In https://github.com/angular/components/blob/main/guides/theming-your-components.md there is a typo: `desity` should be `density`.

![afbeelding](https://github.com/angular/components/assets/153526222/ae88eca2-eb02-444e-96bb-633f6e1d8465)

Can be seen on the website guides here: https://material.angular.io/guide/theming-your-components#reading-density-values

### Affected documentation page

https://material.angular.io/guide/theming-your-components#reading-density-values

**Comment by json-derulo** [comment]
Fixed by #28389
