### ISSUE TITLE
bug(Paginator): Form Field density is not propagated to the Page Size Select Form Field

### ISSUE THREAD

**Issue by marek-aguita** [angular/components#28398]
### Is this a regression?

No

### Description

When a different than default (higher) Form Field and Paginator density is applied, the Select Form Field inside the Paginator that serves to select the page size remains to have the same (default) height (42px). 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/iyuv6n?file=src%2Fexample%2Fpaginator-overview-example.html
Steps to reproduce:
1. open the StackBlitz link
2. check last lines of the theme.scss file where the code that is supposed to change the density of the Paginator and Form Field is applied
3. visually compare the heights of the Select Form Field inside the Paginator with the one that is outside the Paginator

### Expected Behavior

For example if `@include mat.form-field-density(-6);` is applied, the Form Fields should have 36px (without the Subscript Wrapper).

### Actual Behavior

The Select Form Field inside the Paginator has 42px height.

### Environment

- Angular: 17.0.0
- CDK/Material: 17.0.4
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by crisbeto** [comment]
This is working as expected. The paginator needs to make the form field narrower in order to fit in the default density: https://github.com/angular/components/blob/main/src/material/paginator/_paginator-theme.scss#L55. You should be able to control it through the paginator's density mixin.
