### ISSUE TITLE
Add a whole dark mode

### ISSUE THREAD

**Issue by AyishikD** [angular/components#28421]
### Feature Description

Adding a systemwide dark mode on the website. It would help in better visibility and readability. I would be very thankful if I get can get the issue assigned and get a chance to solve it and contribute to the organization.

**Comment by crisbeto** [comment]
The docs site already has two light and two dark theme. 
<img width="710" alt="image" src="https://github.com/angular/components/assets/4450522/a3ba5e0f-4f39-4cbb-824b-1339da021423">
