### ISSUE TITLE
bug(Autocomplete): requireSelection Fails After Selection & Value Change

### ISSUE THREAD

**Issue by lperezprimemso** [angular/components#28432]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After selecting an option from autocomplete before the focus is lost, if a single character is deleted, the component will not clear out the input and deselect the option. If two or more characters are deleted, the component works as normal.

### Reproduction

StackBlitz link: https://material.angular.io/components/autocomplete/overview#require-an-option-to-be-selected
Steps to reproduce:
1. Click into autocomplete input.
2. Select an option.
3. Before losing focus on input, backspace once.
4. Navigate away from input.
5. Partial value will remain with the option still selected.

### Expected Behavior

If user modifies value when requireSelection is set to true, the value on the input should always clear and the selected option should be deselected.

### Actual Behavior

Value on input is not cleared and the option is not deselected.

### Environment

- Angular: 
- CDK/Material: 17.0.5
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by tanoabeleyra** [comment]
Similarly, you can also add a single character after selection and the input isn't cleared.

Example in [official doc](https://material.angular.io/components/autocomplete/overview#require-an-option-to-be-selected):
<img width="563" alt="image" src="https://github.com/angular/components/assets/6851095/dde35b90-6820-4230-be17-9edca813cdea">

**Comment by mjastrzebowski** [comment]
Looks like @crisbeto assumed here [#28146](https://github.com/angular/components/pull/28146/files#diff-24782e72badacf230432f62766cb1c37892faf91b51cfbd03e107974c79b9de4R509-R511) that value will be cleared after panel is closed, but as done https://github.com/angular/components/pull/10176, `closed` is not emitted when there's no match in selection 

I will be happy to provide PR for that once I will fix/add tests

**Comment by lperezprimemso** [comment]
@mjastrzebowski thank you for looking into this but I do not understand why this would not be expected behavior? The field clears in all other scenarios. The definition of requireSelection is that is clears the value if none match.

**Comment by tanoabeleyra** [comment]
> Similarly, you can also add a single character after selection and the input isn't cleared.
> 
> Example in [official doc](https://material.angular.io/components/autocomplete/overview#require-an-option-to-be-selected): <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/6851095/298408029-dde35b90-6820-4230-be17-9edca813cdea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjAxODAsIm5iZiI6MTcwNjI1OTg4MCwicGF0aCI6Ii82ODUxMDk1LzI5ODQwODAyOS1kZGUzNWI5MC02ODIwLTQyMzAtYmUxNy05ZWRjYTgxM2NkZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDkwNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QxODE3ZjBiYjg5YTVhZTgzODIyMzQyNTViMTRiMDQ4N2I0MGQ2Y2U0YWNiZjA4MWVhMTRjYThjY2E4Njc1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HuwiQ6vZQ2IL2r3fZwDxFWQiHX3vgDjzwzxKS8k39xE">

I want to highlight that the input does not clear when typing a single character, but it does clear when typing more than one character. So, in any case this looks like a bug to me, as I don't see any reason why these two scenarios should behave differently.

**Comment by lperezprimemso** [comment]
Thank you!
