### ISSUE TITLE
Standalone components

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#28434]
### Feature Description

As Angular v17 is released with stable standalone component APIs, is there any plan for migrating material components to standalone components. If yes, Are we planning for automatic migration of modules to standalone components?

**Comment by json-derulo** [comment]
Check the code, the Material components are already migrated to standalone. What exactly are you missing?

**Comment by crisbeto** [comment]
All components are standalone in the 17.1 release.

**Comment by iKrishnaSahu** [comment]
> All components are standalone in the 17.1 release.

Thanks for the reply.
I just checked the latest codebase and I saw no new generators added to automatically migrate existing modules to standalone components. Can we expect automatic migration scripts in future release?

**Comment by andrewseguin** [comment]
Unfortunately I don't expect we'll have the resources available to set up any automatic migration scripts

**Comment by crisbeto** [comment]
There's a schematic in `@angular/core` that migrates to standalone automatically: https://angular.io/guide/standalone-migration

**Comment by MikaStark** [comment]
> All components are standalone in the 17.1 release.

I think it would be great to mention this on material.angular.io
