### ISSUE TITLE
bug(dialog): Material dialog enter/leave animation breaks in 17.1.0

### ISSUE THREAD

**Issue by wilson3q** [angular/components#28447]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.6

### Description

The material dialog enter/leave transition animation does not work in new release. Used to work fine on 17.0.X.

![image](https://github.com/angular/components/assets/67785341/46c3c4e7-c4fa-4a0f-93c1-4cf656c5f109)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Go to angular material demo site https://material.angular.io/components/dialog/examples
2. click "Open dialog slowly" button

### Expected Behavior

Dialog should open slowly, and transition animation should show.

### Actual Behavior

 Dialog does not open slowly as it was used to be. There is no transition animation at all.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by json-derulo** [comment]
I cannot reproduce this issue, for me even in 17.1.0 the dialog opens slowly, as expected. Tested Chrome, Firefox and Safari.

**Comment by wilson3q** [comment]
thanks for the fix. I manually added below css to my app style.scss. now animation works as expected. just temporary fix for my application to work.

`// temp fix
.mdc-dialog__container {
  transition: opacity linear var(--mat-dialog-transition-duration, 0ms) !important;
}
.mdc-dialog__surface {
  transition: transform, var(--mat-dialog-transition-duration, 0ms) !important;
}
`
