### ISSUE TITLE
feat(new component): Story

### ISSUE THREAD

**Issue by marloncommona** [angular/components#28455]
### Feature Description

Since the team's goal is to "Build high-quality UI components that developers can drop into existing applications", I would like to propose a "story" component similar to WhatsApp and Instragram storys. 
I would also love to see a component roadmap.

### Use Case

A library like Material Angular greatly supports the Angular framework as it makes the framework easy to use and to start with. Material Angular should ensure that it keeps up with UX/UI trends.

**Comment by crisbeto** [comment]
Closing since it isn't part of the Material Design spec.
