### ISSUE TITLE
docs(m3): docs are not updated to showcase how to use M3 experimental theme

### ISSUE THREAD

**Issue by eneajaho** [angular/components#28465]
### Documentation Feedback

Following the readme file steps or trying to get dev-app styles in another app doesn't work. 

https://stackblitz.com/edit/stackblitz-starters-qbqvmb?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fglobal_styles.scss&title=Angular%20Starter

### Affected documentation page

https://github.com/angular/components/tree/main/src/material-experimental

**Comment by eneajaho** [comment]
I managed to get it working: 
- Repo: https://github.com/eneajaho/material-3-demo
- Commit https://github.com/eneajaho/material-3-demo/commit/3f8e742967ade4b0c685c07b4ce727b1ba82a08e

https://github.com/angular/components/assets/25394362/36962f4a-ba6c-4523-94cb-98fce405fd1a

**Comment by crisbeto** [comment]
They'll be documented as a part of the release. Closing as planned.
