### ISSUE TITLE
bug(MatChipOption): Error when <mat-chip-option> mixed with <mat-chip> inside <mat-chip-listbox>

### ISSUE THREAD

**Issue by yurakis** [angular/components#28474]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When `<mat-chip-listbox>` contains both `<mat-chip>` and `<mat-chip-option>`, and `<mat-chip-option>` has `*ngIf` directive attached, toggling condition for the first time will cause an error in the console:
<img width="470" alt="image" src="https://github.com/angular/components/assets/13770788/b87d8cdd-beab-45b4-abb9-e529d5eacb70">

Changing `<mat-chip-listbox>` to `<mat-chip-set>` or `<mat-chip-option>` to `<mat-chip>` make this issue disappear. Also it does not appear when `*ngIf` is attached on `<mat-chip>` instead of `<mat-chip-option>`.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-2cpaai
Steps to reproduce:
1. Click `Toggle` button

### Expected Behavior

No error in the console.

### Actual Behavior

`You provided 'undefined' where a stream was expected.` error appeared in the console.

### Environment

- Angular: 17.1.0
- CDK/Material: 17.1.0
- Browser(s): Chrome 120.0.6099.234 (Official Build) (arm64)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Sonoma 14.1.2 (23B92)

**Comment by zarend** [comment]
Hello folks,

Thank you for reaching out.  `<mat-chip-listbox>` containing both `<mat-chip>` and `<mat-chip-option>` is not a supported configuration. `<mat-chip-listbox>` may only contain `<mat-chip-option>`.

https://material.angular.io/components/chips/overview#selection-chips

-Zach

**Comment by yurakis** [comment]
Hello @zarend,

Thanks for you reply. Probably it makes sense to handle it more gracefully? Some meaningful warning/error would make much more sense as right now it looks like it's an unhandled exception.
