### ISSUE TITLE
bug(MatSlider): MatSliderVisualThumb not properly destroyed

### ISSUE THREAD

**Issue by NchemIcaLS** [angular/components#28475]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the MatSlider is destroyed the MatSliderVisualThumb is also destroyed. However the ngOnDestroy of the MatSliderVisualThumb attempts to removeEventListener from an object that is not defined which throws a `TypeError: Cannot read properties of undefined`.

### Reproduction

Steps to reproduce:
1. Create MatSliderComponent with matSliderThumb
2. Destroy the component

### Expected Behavior

Should not throw an error when destroyed.

### Actual Behavior

MatSlider throws an error when destroyed.

### Environment

- Angular: 16.1

**Comment by crisbeto** [comment]
Is this happening in a test or for users? I can't reproduce it in an actual app, but I can see how it might happen in a test.
