### ISSUE TITLE
bug(cdk): 17.0.5 breaks cdkDrag

### ISSUE THREAD

**Issue by sandrooco** [angular/components#28480]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.4

### Description

I have two `cdkDropList` instances (in different components) and connected them to each other via `cdkDropListConnectedTo`. List a can only move stuff into list b, but not the other way around.
This implementation worked since around Angular (cdk) 11 or 13.

The items are draggable but the  `cdkDropListExited` event is never triggered. Also on the target list no `dragenter` event is triggered (not even drag placeholder shows up).

When I downgrade to 17.0.4 (with legacy peer deps) it works just like before. The 17.0.5 release notes don' suggest anything in connection to `cdkDrag` - what am I missing?

### Reproduction

StackBlitz link: I'm currently trying to create a repro - it's not easy since I have a large project with a bunch of components involved.
Steps to reproduce:
1. 
2.

### Expected Behavior

I expect the drag placeholder to show up and events to fire.

### Actual Behavior

as per description

### Environment

- Angular: 17.1.1
- CDK/Material: 17.1.1/since 17.0.5
- Browser(s): Chrome, Edge, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOs 14.1.2, Windows 11

**Comment by crisbeto** [comment]
Hmm this does sounds weird. There haven't been any substantial changes in a while on `cdk/drag-drop`: https://github.com/angular/components/commits/main/src/cdk/drag-drop.

**Comment by sandrooco** [comment]
We finally found the problem: there's a bit of a hack that we implemented which fixes some issues we had with nested drag & drop lists. [This commit](https://github.com/angular/components/commit/5849a7477d3e696d237b9e8f0b125d9ff3e25b7e) (DomRect instead of ClientRect) then caused our implementation to break (due to swallowed errors in our hack... 🙃)

So in the end, CDK did it's job perfectly fine.
