### ISSUE TITLE
bug(@angular/material-experimental): breaks theme secondary color

### ISSUE THREAD

**Issue by Fulll3** [angular/components#28487]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

git+ssh://git@github.com/angular/material-experimental-builds.git#bed96e28e7a35fc5a9357b738497dfd51907f76d 

### Description

Hi,

latest version is missing support for secondary color 
Latest version: git+ssh://git@github.com/angular/material-experimental-builds.git#95f8ae1dd5bda218024ce6d75bb92a913ade8472 .
Previous version: git+ssh://git@github.com/angular/material-experimental-builds.git#bed96e28e7a35fc5a9357b738497dfd51907f76d 

![image](https://github.com/angular/components/assets/15888184/0718c86f-83d9-4893-9379-df42788aa5fa)

vs 

![image](https://github.com/angular/components/assets/15888184/88145816-c4c2-4d28-a0e8-efa41111c5a0)

### Reproduction

StackBlitz link: I have large repo hard to repodruce in StackBlitz 
Steps to reproduce:
1. 
2.

### Expected Behavior

Support of secondary color in theme definition.

### Actual Behavior

Secondary color is not supported and throws error during compilation.

![image](https://github.com/angular/components/assets/15888184/669e5303-b62d-4155-baa2-d03ca851cdae)

### Environment

- Angular: 17.1.0
- CDK/Material:17.2.0-next.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
cc @mmalerba

**Comment by Fulll3** [comment]
@SeraphCoding for just testing purposes I made it work with workaround. I have manually replaced  commit version in package-lock.json. 

In node_modules/@angular/material-experimental  > resolved you can change the value to git+ssh://git@github.com/angular/material-experimental-builds.git#bed96e28e7a35fc5a9357b738497dfd51907f76d .

This is older build that was used in provided demo. 

<img width="871" alt="image" src="https://github.com/angular/components/assets/15888184/80499e68-4062-4181-a3b5-bf6a58729104">

**Comment by SeraphCoding** [comment]
> @SeraphCoding for just testing purposes I made it work with workaround. I have manually replaced commit version in package-lock.json.
> 
> In node_modules/@angular/material-experimental > resolved you can change the value to git+ssh://[git@github.com](mailto:git@github.com)/angular/material-experimental-builds.git#bed96e28e7a35fc5a9357b738497dfd51907f76d .
> 
> This is older build that was used in provided demo.
> 
> <img alt="image" width="871" src="https://private-user-images.githubusercontent.com/15888184/303119328-80499e68-4062-4181-a3b5-bf6a58729104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzY4MjQsIm5iZiI6MTcwNzMzNjUyNCwicGF0aCI6Ii8xNTg4ODE4NC8zMDMxMTkzMjgtODA0OTllNjgtNDA2Mi00MTgxLWEzYjUtYmY2YTU4NzI5MTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIwMDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzYwMmFlNWI0ZWU0YzQ4ZjMzZWM4MWVjY2Y4OTdiOTNkMmViZTNhNjBmZGIyYTJjNWIxMjlmYjg2Njc0MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydVUJ38ThCSQHEM2e-meiYsutqVgWNIeepEW9f6emsE">

Yeah it's resolved in the latest commit. I just grabbed the latest build to avoid the issue.

**Comment by mmalerba** [comment]
We changed `define-theme` to always derive the secondary palette from the secondary palette. This is because the M3 spec itself seems to assume that the secondary color is basically a more muted version of primary (but same general hue). If we just allow people to combine an arbitrary primary and secondary hue, I think it would result in some of the components not looking great.

The current state of things is that:
- The M2 concept of "primary" roughly maps to M3's "primary" or sometimes "secondary"
- The M2 concept of "accent" roughly maps to M3's "tertiary"
- The M2 concept of "warn" roughly maps to M3's "error"

And in fact we have a back-compat mixin that can be included to actually apply those mapping to the `.mat-{primary/accent/warn}` classes. (Though in general I would suggest people use the new `@include mat.xxx-color($theme, $color-variant: primary/secondary/tertiary/error)` API in M3 as it doesn't generate as much boilerplate CSS as the predefined classes

**Comment by amysorto** [comment]
There is a [schematic for custom themes](https://material.angular.io/guide/theming#customizing-your-colors) where you can specify a different secondary color.

Also with the addition of [#29363](https://github.com/angular/components/issues/29363) in v19, you will be able to override theme values system values with the `theme-overrides()` mixin including the secondary color. The theming guide will be updated with more details and instructions!
