### ISSUE TITLE
bug(mat-badge): Badge is not displaying content since 17.1.1

### ISSUE THREAD

**Issue by benuss** [angular/components#28483]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.1.0

### Description

Since updating to Angular 17.1.1 and Material 17.1.1 the content inside matBadge is not displaying anymore

### Reproduction

Can't link a StackBlitz because it loading dependencies for more than one hour for now ...
To reproduce : 

1. Create a new project with Angular 17.1.1
2. Add a icon with a matBadge
3. The content inside the badge is not displayed

By comparing the previous (17.1.0) css class of the matBadge, I noticed this difference : 

17.1.0:
![image](https://github.com/angular/components/assets/30980846/3fd84e8d-1bdb-48e7-b5f9-178446224cdf)
17.1.1:
![image](https://github.com/angular/components/assets/30980846/b9166032-2732-4c02-9111-896163583063)

Previously, the sass variables had a default value if not set, and now default values are absent.

### Expected Behavior

The content inside matBadge must be visible

### Actual Behavior

The content inside matBadge is NOT visible

### Environment

- Angular: 17.1.1
- CDK/Material: 17.1.1
- Browser(s): Chrome (120.0.6099.225)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This means that your theme isn't set up correctly. How are you including the badge theme?

**Comment by benuss** [comment]
Thanks ror your quick reply, I include theme with : 

My bad, by looking at the default theme I am applying at start using mat.all-component-themes, I was missing : 

    typography: mat.define-typography-config(),
    density: 0

Adding these resolve the problem. 
Sorry and thanks for the help !
