### ISSUE TITLE
bug(Badge): causes overflow in combination with matRipple

### ISSUE THREAD

**Issue by fabianvo** [angular/components#28542]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

< 15

### Description

#24602 introduced a regression by forcing matBadge to always overflow: visible.

Maybe this could be configurable via an optional property to not break existing use cases? We use matBadge not only with icons or buttons. It worked great so far.

A simple workaround for us, of course, is to simply add

`.mat-badge {
  overflow: hidden !important;
}`

to any component using matBadge. But that is hardly a long term solution.

### Reproduction

[StackBlitz matRipple + matBadge on div](https://stackblitz.com/edit/xunvzh)
Steps to reproduce:
1.  apply matBadge and matRipple to same element

### Expected Behavior

ripple should not overflow

### Actual Behavior

ripple effect will overflow

### Environment

- Angular: 17.1.2 (error introduced in 15)
- CDK/Material: 17.1.2 (error introduced in 15)
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
For cases like that it's recommended to put the ripple on an inner element. We need the `overflow: visible` on the badge, because otherwise it'll get clipped.
