### ISSUE TITLE
bug(mat-error): No style on mat-error without form-field in the same component

### ISSUE THREAD

**Issue by martibenn** [angular/components#28543]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.14

### Description

Hi 👋 

in a component using a `mat-error`
without any `mat-form-field` in the component
the `mat-error` is displayed without using the color `warn` (missing definition of `mat-mdc-form-field-error` class)

### Reproduction

StackBlitz link: [https://stackblitz.com/edit/jzya6i?file=src%2Fmain.ts](https://stackblitz.com/edit/jzya6i?file=src%2Fmain.ts)
Steps to reproduce:
1. Go to `with-color` to see a `mat-error` **using** `$theme-warn` color
2. Go to `without-color` to see a `mat-error` **not using** `$theme-warn` color

### Expected Behavior

`<mat-error>` are displayed **using** `color: warn`

### Actual Behavior

`<mat-error>` are displayed **without using** `color: warn`

### Environment

- Angular: ^17.0.0
- CDK/Material: ^17.0.0
- Browser(s): Chrome/Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
`mat-error` is only meant to be used with `mat-form-field` so this is working as expected.

**Comment by martibenn** [comment]
[re-asking](https://github.com/angular/components/issues/28543#issuecomment-1929636593) :
"if the behavior is expected, is there a way to detect that kind of usage within a project"
