### ISSUE TITLE
bug(mat-select): Zoneless breaks mat-select

### ISSUE THREAD

**Issue by spock123** [angular/components#28575]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When adding the new experimental `ɵprovideZonelessChangeDetection() `to go zoneless, mat-select no longer displays the options.

### Reproduction

1. Clone https://github.com/spock123/mat-select-zoneless.git
2. npm run start
3. Observe the mat-select works on initial page
4. Enable zoneless by uncommenting the line in app.config.ts, restart
5. Now mat-select no longer works. No error thrown. 

### Expected Behavior

Options shown when dropdown clicked.

### Actual Behavior

Options hidden even when clicking mat-select dropdown

### Environment

```
Angular CLI: 17.1.3
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@angular/cdk                    17.1.2
@angular/material               17.1.2
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js     
                    0.14.3
- Browser(s): Chrome
- Operating System (macOS):
```

**Comment by atscott** [comment]
Yes, this is a known issue and generally tracked by https://github.com/angular/components/issues/9169. Zoneless is not yet even in public experimental phase so please hold off on submitting issue reports until we’re ready to open it up for feedback and developer testing. At the moment, we have a large backlog of known issues that we’re working through.
