### ISSUE TITLE
docs-bug(COMPONENT): Links on stackblitz don't work 

### ISSUE THREAD

**Issue by ArturGudiev** [angular/components#28570]
### Documentation Feedback

some examples don't work on stackblitz

Angular Components - Responsive sidenav
Angular Components - Sidenav using injected ConfigurableFocusTrap
Angular Components - Sidenav with custom escape and backdrop click behavior
Angular Components - Fixed sidenav
Angular Components - Testing with MatSidenavHarness
Angular Components - Sidenav open & close behavior
Angular Components - Sidenav open & close behavior

![image](https://github.com/angular/components/assets/4563342/56a837ff-061c-4b64-bc34-5e4ee4bb6e57)
![image](https://github.com/angular/components/assets/4563342/1e57a411-2eb5-442e-a019-20080294b992)
![image](https://github.com/angular/components/assets/4563342/a8ac734e-780d-42e2-8cdc-8f88df74aa48)
![image](https://github.com/angular/components/assets/4563342/b42c7c9b-88c5-4abb-a37e-a5ebcabb6306)
![image](https://github.com/angular/components/assets/4563342/4ba1d007-c1d4-4eb9-957e-65d97a600771)

### Affected documentation page

https://material.angular.io/components/sidenav/examples

**Comment by crisbeto** [comment]
All of the examples worked for me on a couple of different machines. It's most likely an issue on your end.
