### ISSUE TITLE
bug(mat-progress-bar): Using dir="rtl" does not work correctly

### ISSUE THREAD

**Issue by vincentsels** [angular/components#28572]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Adding `dir="rtl"` to a `<mat-progress-bar>` used to flip the direction to right-to-left. This currently doesn't work anymore. The result seems something random:

![image](https://github.com/angular/components/assets/1068863/6e2f20a8-10b1-4ad8-a21b-635b9ee01515)

(note that explicitly setting `dir="ltr"` does work correctly)

This was already fixed once in 2021, but seems to be broken since then: https://github.com/angular/components/pull/22705

### Reproduction

StackBlitz link: https://stackblitz.com/edit/wnrmdf?file=src%2Fexample%2Fprogress-bar-determinate-example.html

### Expected Behavior

The progress bar is displayed from right to left.

### Actual Behavior

The progress bar is filled in somewhere in the middle, seemingly randomly.

### Environment

- Angular: 17.0.0
- CDK/Material: 17.0.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
I've sent a fix in #28576, but you can also resolve it by putting the `dir` on a parent element.
