### ISSUE TITLE
[CDK - Overlay] Cannot read properties of null (reading 'parentElement')

### ISSUE THREAD

**Issue by abpardal** [angular/components#28579]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

For some reason when showing a MatTooltip attaching the host is returning an error **Cannot read properties of null (reading 'parentElement')** since the _host is null.
`tooltip.show()`

Suggestion:

- Add a validation for _host like should prevent the issue (method **attach**  on **class OverlayRef**:

`if (this._host && !this._host.parentElement && this._previousHostParent) {
            this._previousHostParent.appendChild(this._host);
        }`

![image](https://github.com/angular/components/assets/121935876/07f5eaac-4073-46ca-9e35-0c668fe6c4e5)

### Reproduction

StackBlitz link: -
Steps to reproduce: Wasn't able to reproduce

### Expected Behavior

Should not return an error.

### Actual Behavior

Returns an error (Cannot read properties of null (reading 'parentElement')) when `this._host` is null.

### Environment

- Angular: ^13.3.9
- CDK/Material: ^13.3.9
- Browser(s): Chrome 121 on Linux
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
We can't do much without a reproduction. Also you're using an old version of the CDK/Material and the issue might not be present in the newer ones.
