### ISSUE TITLE
feat(MatOptgroup): Expand and collapse mat optgroups

### ISSUE THREAD

**Issue by anckaert1998** [angular/components#28582]
### Feature Description

Dear

I think it would be a nice addidition to add the feature for expanding and collapsing mat optgroups. When the possible groups and options are large, it could be nice to collapse the groups by default and the user can expand a group by clicking on it

### Use Case

Mainly for selects with a medium/large number of groups and options. This could help with quicker navigation through the list.

**Comment by wagnermaciel** [comment]
Hi @anckaert1998, unfortunately we will not be able to support this feature since it is not included in the Material Design Spec
