### ISSUE TITLE
When cdkDropListOrientation="horizontal" under dir="rtl", then CdkDragDrop.previousIndex can be incorrect

### ISSUE THREAD

**Issue by jeffschulzusc** [angular/components#28591]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When cdkDropListOrientation="horizontal" under dir="rtl", then CdkDragDrop.previousIndex can be incorrect.

like:
``` 
<div
    dir="rtl"
    cdkDropList
    #doneList="cdkDropList"
    cdkDropListOrientation="horizontal"
    [cdkDropListData]="done"
    [cdkDropListConnectedTo]="[todoList]"
    class="example-list-horiz"
    (cdkDropListDropped)="drop($event)">
    <div class="example-box" *ngFor="let item of done" cdkDrag>{{item}}</div>
  </div>
```
  
For example, I can't reorder (horiz list) properly, and can't move (horiz ro vert) list correctly:
https://stackblitz.com/edit/6om1jr-j3qhqe?file=src%2Fexample%2Fcdk-drag-drop-connected-sorting-example.html
https://stackblitz.com/edit/y3tacw?file=src%2Fexample%2Fcdk-drag-drop-connected-sorting-example.html

### Reproduction

StackBlitz links: 
1. (v16) https://stackblitz.com/edit/6om1jr-j3qhqe?file=src%2Fexample%2Fcdk-drag-drop-connected-sorting-example.html
2. (v17) https://stackblitz.com/edit/y3tacw?file=src%2Fexample%2Fcdk-drag-drop-connected-sorting-example.html

### Expected Behavior

Should function correctly as cdkDropList(s) when orientation is vertical and dir="ltr"

### Actual Behavior

Horizontal/rtl  cdkDropList is not dropping with correct index in its own list or to another list.

### Environment

- Angular: 16,17
- CDK/Material: 16,17
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
There are a couple of reasons why it doesn't work:
1. You need to import either the `BidiModule` or the `Dir` directive, because that's what the drop list uses to figure out the direction.
2. You need to the `dir="rtl"` on the parent of the list. Setting it on the list itself seems to mess up the layout.

Here's a working fork of your repro: https://stackblitz.com/edit/y3tacw-qxeza8.

**Comment by jeffschulzusc** [comment]
can the docs be updated to mention that importing the BidiModule is required
