### ISSUE TITLE
bug(Autocomplete): Setting [requireSelection]="true" breaks valueChanges

### ISSUE THREAD

**Issue by Cubelaster** [angular/components#28590]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular/material": "^12.2.10

### Description

I want to trigger custom filtering on Autocomplete, upon writing in the input. 
For that I used FormControl.valueChanges event emitter.
I subscribed inside OnInit and it worked fine. 
However, upon upgrading the Angular varsion to 17 and Material to @angular/material": "^16.2.12" it stopped working. 
I tried removing part by part until I identified that removing requireSelection="true" from mat-autocomplete fixed the error. 
This means that for some reason, requireSelection kills valueChanges emitter when typing in the input. 
This is a bug and needs fixing. 
Autocomplete.optionSelected still works as expected. 

### Reproduction

StackBlitz link:  https://stackblitz.com/~/github.com/Cubelaster/Angular17MatAutocompleteBug
Steps to reproduce: 
1. Go to /Test, open console. Any thing you write in the input is logged to the console. 
2. Add requireSelection="true" on mat-autocomplete, making it look like this <mat-autocomplete #auto="matAutocomplete" requireSelection="true">
3. Start typing: nothing happens anymore

### Expected Behavior

I would expect valueChanges over FormControl to be unaffected and working properly, as per documentation. 
https://material.angular.io/components/autocomplete/api

### Actual Behavior

Setting requireSelection="true" on mat-autocomplete kills valueChanges event emitter. 

### Environment

Angular CLI: 17.0.10
Node: 21.6.1 (Unsupported)
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.9
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.0.10
@angular/animations             17.1.2
@angular/cdk                    16.2.14
@angular/cli                    17.0.10
@angular/flex-layout            14.0.0-beta.41
@angular/material               16.2.14
@schematics/angular             14.2.13
ng-packagr                      17.1.2
rxjs                            6.6.7
typescript                      5.2.2
zone.js                         0.14.2

Warning: The current version of Node (21.6.1) is not supported by Angular.

- Browser(s): Chrome, Opera

**Comment by crisbeto** [comment]
This is working as expected. See the explanation at https://github.com/angular/components/issues/28378#issuecomment-1889244035.

**Comment by Cubelaster** [comment]
Ok, so the workaround is to use KeyUp event instead. 
Fair enough. 
However, I'm experiencing another issue then. 
The requireSelection="true" does not work for me.
The StackBlitz example has no issue removing the value from input if blur is hit, however, on my project this does not get triggered. 
I copy/pasted the code and the only difference is that the Autocomplete is set inside a MatDialog. 
So, my question is: are there some prerequisites for this to work? And if there are, which ones?

**Comment by Cubelaster** [comment]
I am experiencing a bug where _setValueAndClose always picks up the latest input value as _valueOnAttach and therefore never resets the value of said input if I set requireSelection. 

![image](https://github.com/angular/components/assets/14044616/d0d64d38-1806-4af4-919f-8db64051ffa1)

**Comment by Cubelaster** [comment]
Ah, I see what's happening:

Because I have an *ngIf there for options, each time the options get redrawn, the _valueOnAttach gets reset, meaning that the requireSelection will never clean the input because, well, each keyUp will redraw the panel... 
How can I work around it? @crisbeto 

![image](https://github.com/angular/components/assets/14044616/114a1b8a-039f-449e-b8f6-2b3610e6acb2)
