### ISSUE TITLE
bug(COMPONENT): When using mat-icon inside the button, it always come before the text

### ISSUE THREAD

**Issue by omshakti-maurya** [angular/components#28615]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to put the icon after the text but mat-icon always coming before the button text.

```
         <button
            mat-button
            color="primary"
            class="px-0"
            [matMenuTriggerFor]="menu"
          >
            <span> Sort </span>
            <mat-icon>sort</mat-icon>
          </button>
```

![image](https://github.com/angular/components/assets/143780099/da0107f6-df36-454a-a985-f2d3fd4c1089)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. create a button 
2. try to place the icon after the text in right side

### Expected Behavior

Icon should come after the button text if we are placing the icon next to text.

### Actual Behavior

I am trying to put the icon after the text but mat-icon always coming before the button text.

### Environment

- Angular: 16.2.12
- CDK/Material:16.2.10
- Browser(s):chrome
- Operating System (e.g. Windows, macOS, Ubuntu):macOs

**Comment by crisbeto** [comment]
You can set the `iconPositionEnd` attribute to position it to the end.
