### ISSUE TITLE
bug(COMPONENT): programmatically focused link gets focused, but the style doesn't apply

### ISSUE THREAD

**Issue by landoephan** [angular/components#28611]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to focus a link programmatically. The following stackblitz shows the behavior:

if you click on the button, the link should get focused. It actually get the focus, but you cannot see it.
If you change the code, so the button focuses the nearby input field, everything works well.
One more thing I noticed is that when is focus is actually on the button when you click it, the focus on the link works perfectly fine.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-9jocb8?file=src%2Fmain.ts,package.json
Steps to reproduce:
1. Open the link
2. click on the button

### Expected Behavior

Link is visually focused

### Actual Behavior

Link is focused, but you cannot see it (tab back and forth shows the actual focus)

### Environment

- Angular: 17.0.1
- CDK/Material:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Closing since this doesn't have anything to do with Material or the CDK.
