### ISSUE TITLE
bug(youtube-player): Ready event is never emitted

### ISSUE THREAD

**Issue by BojanKogoj** [angular/components#28619]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.1.1

### Description

[`ready`](https://github.com/angular/components/blob/main/src/youtube-player/youtube-player.ts#L209) event no longer emits, however some other events work as expected.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-saqwwz?file=src%2Fmain.ts
Steps to reproduce:
1. Run file (might need to open preview in new tab)
2. Click play on Youtube

### Expected Behavior

`ready` event to be emitted (and set isReady to true)

### Actual Behavior

`ready` never emits

### Environment

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@angular/cdk                    17.1.2
@angular/youtube-player         17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3

- Browser(s): Edge/Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
It's because the `ready` event fires when the API has been loaded. Now we no longer need to load the API until the video is played so the player is ready from the beginning. If you want to get the old behavior, you can set the `disablePlaceholder` attribute to go back to the old behavior.

**Comment by crisbeto** [comment]
> This obviously crashes since player isn't ready yet.
In what way does it crash? I'm asking since we have some logic in the component where calling `mute` before the player is ready will get cached and applied when it starts playing. See https://github.com/angular/components/blob/main/src/youtube-player/youtube-player.ts#L320.

**Comment by BojanKogoj** [comment]
Crashes because the whole `YouTubePlayer` component isn't ready yet, or at least available through `@ViewChild`

> TypeError: Cannot read properties of undefined (reading 'mute')

`pendingPlayerState` will work fine if `YouTubePlayer` component is ready and `YT.Player` isn't.
This is why we relied on `ready` event, since we didn't care when it is ready, but just mute when it is.

**Comment by crisbeto** [comment]
I think the problem is that you're accessing the player before `ngAfterViewInit`. It should be defined if you move the call there.

**Comment by BojanKogoj** [comment]
It works fine with `ngAfterViewInit` when component is immediately visible, but not when it's behind `@if`.
This example shows exactly the problem https://stackblitz.com/edit/stackblitz-starters-q5wasm?file=src%2Fmain.ts

**Comment by crisbeto** [comment]
I see. I think that you should be able to add `mute: 1` to the `playerVars`. I know you mentioned earlier that "playerVars has no muted property, so we relied on ready event to mute video before it started playing.", but I see it when I look at the typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/youtube/index.d.ts#L524

**Comment by BojanKogoj** [comment]
Thanks, that worked. I was looking at [YouTube Embedded Players and Player Parameters](https://developers.google.com/youtube/player_parameters) which doesn't have that property listed.

I think we can easily shift the rest of the functionality that was called on `ready` to other events, so this should work fine.
