### ISSUE TITLE
bug(mat-select): Option duplication / staying in component

### ISSUE THREAD

**Issue by angelaki** [angular/components#28627]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In a very rare edge-case I noticed that some options were duplicated / staying without function in the `mat-select`. It took me pretty much effort to reduce it to a minimal repro. Some code here might seam very unusual, but this all is needed for a custom control with filtering, paging and so on.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-92ymn4
Steps to reproduce:
1. Check 7, 8, 9 & Close
2. Uncheck 7, 8 & Close
3. Hit "clear"
4. Now open the select again. You'll notice item 7 & 8 are still present

In the code there are three parts that could (most likely? Not sure since it is pretty hard to reproduce) fix the issue. One weirder than another:

1. Removing the sort
2. Removing the div
3. Removing empty animation (!)

### Expected Behavior

No item duplication in select

### Actual Behavior

Items can be duplicated in pretty rare scenarios.

### Environment

- Angular: 16 & 17
- CDK/Material: 16 & 17

**Comment by angelaki** [comment]
@wagnermaciel don't know what happened here, just reformed it, please check if it works now.

**Comment by wagnermaciel** [comment]
@angelaki Unfortunately, adding unexpected content (in this case a wrapper div around your options) into the internals of the mat-select is unsupported

**Comment by angelaki** [comment]
Hey @wagnermaciel do you maybe have an idea what could cause this misbehavior? Maybe it is still interessting since this is just **one** of the three modifications, triggering this issue. Not even said, that it can even be caused without the div. I just  haven't found a reliable way. So maybe at least finding the root of this issue is still interessting? The behavior is just super weird.

**Comment by wagnermaciel** [comment]
I wouldn't be able to tell without digging into things, but it could be any number of things. Could be that a query within the mat-select is failing because of the unexpected html structure. Using `ngIf` and `ngFor` inside of ng-content is also a known foot-gun because it can cause the ng-content to not exist at certain lifecycle stages.

**Comment by angelaki** [comment]
Ok, I see. I was hoping the fact that reordering the items / using empty animations would make the issue interessting enough for someone to dig into the component ;)

What do you mean with 

> Using ngIf and ngFor inside of ng-content

Since the options usually get repeated via `ngFor` it is almost always used inside `ng-content`? I just need the inner div for some kind of loading-animation - guess I could change this code. Could putting another child to the `role="listbox"-div` solve the issue? Sure this would be way more _hacky_, since I need to somehow manipulate the inner html of the control.

**Comment by wagnermaciel** [comment]
Sorry, I meant only `ngIf`. `ngFor` is safe. `ngIf` can cause weirdness because it can prevent the wrapper component from having access to the element if it is not being rendered. I would recommend following the examples on our docs site

**Comment by angelaki** [comment]
But I guess showing / hiding options via ngIf is totally fine and commonly used? So this can't be an issue, I guess?

Never the less, I'd like to give it a try. I reload options in the `openedChange` event. But if initially no options exists (because of lazy loading), I somehow need to be able to open the mat-select. And the demos don't provide a similar solution for lazy loading. I even tried it without hiding the "empty option", but still the same behavior.

Btw.: your _Select with reset option_ demo is broken with native select - just noticed.
