### ISSUE TITLE
bug(material/bottom-sheet): overlay-panel has static position

### ISSUE THREAD

**Issue by aalzehla** [angular/components#28643]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to add MatBottomSheet to my project, but i noticed that it shows in the middle of the screen, not popup from botton as in example in documentation. 
after investigation i found it the overlay pane has static position as following: 
`<div id="cdk-overlay-4" class="bottomSheetPanelClass cdk-overlay-pane" style="max-width: 100%;position: static;margin-bottom: 0px;"></div>`

I tried adding the panel class "bottomSheetPanelClass" as following:
`.bottomSheetPanelClass{
  position: absolute;
  bottom: 0 !important;
}`

Also I tried using: `::ng-deep .cdk-overlay-pane:has(.bottomSheetPanelClass)` but nothing work.

BTW,  Imported material theme and used mat.core() in my styles.scss, everything is fine with material, the project is huge and material works perfectly but only this issue...

Could you please help me

### Reproduction

<img width="1134" alt="Screenshot 2024-02-25 at 8 25 19 PM" src="https://github.com/angular/components/assets/9719345/e1b18b5d-1175-4e50-b428-a44111a896d0">

### Expected Behavior

the MatBottomSheet pops up from down

### Actual Behavior

The BottomSheet show up in the middle of the screen same as dialogs

### Environment

- Angular: 17.1.1
- CDK/Material: 16.1.13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
It's because you're missing the common structural styles. You should add `@include mat.core()` to your theme file.

**Comment by aalzehla** [comment]
Thank you @crisbeto for replay,
I mentioned that I use @include mat.core() in my theme file. the issue still there

**Comment by crisbeto** [comment]
Ah sorry, I must've missed it in the original description. I suspect that some structural style is overwritten somewhere, but it's hard to tell without a reproduction. Can you post the code that you're using to open the bottom sheet?

**Comment by aalzehla** [comment]
Thank you @crisbeto 
Here is the code I open BottomSheet
```
advanceFilter(){
    this._bottomSheet.open(AdvanceFilterScreenComponent,{
      panelClass: "bottomSheetPanelClass"
    }).afterDismissed().subscribe(res=>{
      ///....
    });
  }
```

**Comment by crisbeto** [comment]
There isn't anything that stands out in the code snippet either. Can you check that nothing is interfering with the styles on the `.cdk-overlay-container`, `.cdk-global-overlay-wrapper` or `.cdk-overlay-pane` styles? They're the ones responsible for positioning.

**Comment by aalzehla** [comment]
This is the top of the styles.scss:

```
@use "@angular/material" as mat;
/* You can add global styles to this file, and also import other style files */
@font-face {
  font-family: "Neo-sans-arabic";
  font-style: normal;
  font-weight: 500;
  src: local("Neo-sans-arabic"), url("assets/fonts/NeoSansArabicMedium.ttf") format("ttf");
}

@import "@angular/material/theming";
@import "variables";

@include mat.core();

@import 'swiper/scss';
@import 'swiper/scss/navigation';
@import 'swiper/scss/pagination';

@import "themes/myc.scss";


@include ng-viv-ux-theme($app-theme);


@import "../node_modules/bootstrap/scss/bootstrap.scss";



html,
body {
  height: 100%;
  overflow: hidden;
  --mdc-typography-font-family: 'Neo-sans-arabic';
  --mdc-filled-button-container-height:40px;

}
body {
  margin: 0;
  font-family: 'Neo-sans-arabic';
  --mdc-typography-font-family: 'Neo-sans-arabic';
  --mdc-typography-letter-spacing:normal;
  --mdc-filled-button-container-height:40px;
}
```

there is no override for overlay pane in the styles.css

the problem is that the cdk-overlay-pane uses style attribute not CSS class it seems to me that hard coded in the BottomSheet itself, look at the element style attribute:

```
<div id="cdk-overlay-22" class="cdk-overlay-pane bottomSheetPanelClass" style="max-width: 100%; position: static; margin-bottom: 0px;"><div tabindex="0" class="cdk-visually-hidden cdk-focus-trap-anchor" aria-hidden="true">
    ....
</div>
```

**Comment by crisbeto** [comment]
Those inline styles are as expected. The bottom sheet is positioned using flexbox inside the `cdk-overlay-container` which is `position: fixed`.

**Comment by aalzehla** [comment]
OK, understand, thank you @crisbeto
