### ISSUE TITLE
Multi select mat auto complete 

### ISSUE THREAD

**Issue by mahak23** [angular/components#28649]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Guys, In multi select mat auto complete if I checked value from drop-down and press enter it shows [ object object] in input field.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I just want after press enter or space drop-down hide and checkbox value patch in input field.

### Actual Behavior

If I click anywhere in the screen it will work fine. Checkbox value patched in input but if I press enter it shows (object object) in input

### Environment

- Angular:10
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
Please re-open this issue with a reproduction
