### ISSUE TITLE
Date Range picker issue

### ISSUE THREAD

**Issue by Udhayanila8** [angular/components#28665]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The date range on trying to alter the date manually after choosing is not working properly.

**Note: The issue only occurs randomly, so check more than once without refreshing.**

### Reproduction

StackBlitz link:  https://material.angular.io/components/datepicker/overview
Steps to reproduce:
1. Select a date range from the Basic date range picker
![image](https://github.com/angular/components/assets/82999693/b007a283-2bb6-4cdd-8dff-56f1289b057b)
2. Place the cursor at the last index of the end date
![image](https://github.com/angular/components/assets/82999693/5a577b1b-fb6a-4787-8c10-6440a24b6377)
3. Try to delete the end date completely by pressing the 'Backspace key'.
4. Once the end date is removed the cursor is automatically placed at the beginning of the start date 
![image](https://github.com/angular/components/assets/82999693/aec37b4e-acd9-44de-a3b9-dcac2c11c9ac)

### Expected Behavior

The cursor should only be placed at the last index of the start date.  

### Actual Behavior

The cursor is automatically placed at the beginning of start date 

### Environment

- Angular: 17.2.1+sha-7d352fb
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Thilak-Saravanan** [comment]
Is it possible to have this fix in previous versions also? (v14+)
We are currently using angular 14 and we are running into this issue. We will not be able to update to Angular 17 anytime soon. So fix for this in latest version would be helpful.
