### ISSUE TITLE
bug(angular/material): mat-slider matSliderThumb is stuck as initially focused when rendered from a MatDialog

### ISSUE THREAD

**Issue by ettubrute47** [angular/components#28672]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using a mat-slider inside a MatDialog when the dialog is opened, the thumb is focused and you see the semi-transparent large disk around the thumb, and it doesn't go away until I click somewhere else. 

Unsure if this was working in previous version.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-vqttyy?file=src%2Fmain.ts
Steps to reproduce:
1. Click button, this will popup a dialog
2. Notice the slider in the dialog is set to focus

### Expected Behavior

The slider is not focused when the dialog pops up, and is only focused when the user interacts with it.

### Actual Behavior

The slider is initially focused and remains focused until the user clicks interacts somewhere else.

### Environment

- Angular: 17.2.1
- CDK/Material: 17.2.1
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by amysorto** [comment]
Upon opening a dialog, the first tabbable element is placed into focus for accessibility. You can change which element gets focus: https://material.angular.io/components/dialog/overview#focus-management
