### ISSUE TITLE
bug(mat-chip-list): Issue with mat-chip-selected class applied incorrectly

### ISSUE THREAD

**Issue by BogdanDvlpr** [angular/components#28678]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-chip-list and mat-chip selected doesn't work properly.

The issue is that the mat-chip-selected class is applied always on the last chip even though the selected value is not set

### Reproduction

StackBlitz link: https://stackblitz.com/edit/u5y9ka-tc38sc

### Expected Behavior

The mat-chip-selected class should be applied only when mat-chip selected is true

### Actual Behavior

The mat-chip-selected class is applied when the mat-chip selected value is false

### Environment

- Angular: v14.2.0
- CDK/Material: 14.2.7 
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by amysorto** [comment]
This affects the legacy component which is deprecated and removed as of v17
