### ISSUE TITLE
After Upgrading Angular 9 to 17 Material is not working

### ISSUE THREAD

**Issue by Ashokpalla** [angular/components#28684]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

9.1

### Description

I followed the Angular documentation for upgrading and i done the same, even i migrated the material also but still the material is not working

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

UI should work as Previous

### Actual Behavior

Present UI is not looking good

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
Typically we recommend upgrading one version at a time, and then checking for any breaking changes, and verifying your app while you go through that process. All the commands for that can be found here: https://update.angular.io/?v=9.0-17.0. I hope your upgrade goes smoothly! If there are specific issues please open them again here. Thanks!
