### ISSUE TITLE
bug(Angular material datepicker): Intializing date range input with formControl throws error

### ISSUE THREAD

**Issue by olawalemayor** [angular/components#28680]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After initializing the date range input with a formcontrol. the values of startDate and endDate assume the form control value but throws error on the console: 
![date-range-bug](https://github.com/angular/components/assets/40109521/058e902e-8f2c-4dea-b3b0-91277aa4331d)

Details:
    "@angular/animations": "^17.2.3",
    "@angular/cdk": "^17.2.1",
    "@angular/common": "^17.2.3",
    "@angular/compiler": "^17.2.3",
    "@angular/core": "^17.2.3",
    "@angular/forms": "^17.2.3",
    "@angular/material": "^17.2.1",
    "@angular/material-moment-adapter": "^17.2.1",

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-uxpbnj?file=src%2Findex.html
Steps to reproduce:
1.  Start the application
2. Examine the console
3. Also try selecting date

### Expected Behavior

It should work normally, no errors in console and being able to select start and end date

### Actual Behavior

Not able to select start and end date plus error in console
![date-range-bug](https://github.com/angular/components/assets/40109521/612652cf-c59b-4492-a776-1355747b9be4)

### Environment

- Angular: 17.2.3
- CDK/Material: 17.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by amysorto** [comment]
Can you take another look at the Stackblitz link? I'm not seeing the error you mentioned above

**Comment by olawalemayor** [comment]
@crisbeto Thanks, that was it.
