### ISSUE TITLE
Datepicker design breaks Angular 13 

### ISSUE THREAD

**Issue by Sonupro1997** [angular/components#28685]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11

### Description

I am using Angular Material 13.3.9 with a template-driven form that includes both a datetime picker (**@angular-material-components/datetime-picker
)** and a simple material date picker. Initially, these date pickers look fine, but their design breaks when I select either of them.
![image](https://github.com/angular/components/assets/32660232/291293d6-b21c-40e5-be84-981159cf0913)

![image](https://github.com/angular/components/assets/32660232/619345fb-7cbf-4f77-aa6a-f15b03f1a321)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Open mat datepicker and select any date
2. Now Open Datetime Picker (@angular-material-components/datetime-picker) and select any date
3. Go back and open mat datepicker

### Expected Behavior

Both the datepicker should work.

### Actual Behavior

I am using Angular Material 13.3.9 with a template-driven form that includes both a datetime picker and a simple material date picker. Initially, these date pickers look fine, but their design breaks when I select either of them.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
The examples on v13 documentation page seem to look fine for me: https://v13.material.angular.io/components/datepicker/overview. At this point v13 has our legacy components, so it is unlikely a fix will be applied for that. I would encourage you to compare with the examples on the docs site to make sure your code is set up correctly. If the issue still persists, please reopen this issue with a working reproduction on Stackblitz. Thanks!
