### ISSUE TITLE
bug(mat-calendar): Next&Prev Buttons does not fire monthSelected event

### ISSUE THREAD

**Issue by honibis** [angular/components#28712]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Next&Prev buttons changes month of calendar yet does not fire any event back to us.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

 It should fire monthSelected event as it happens when month is selected from year view.

### Actual Behavior

No event fired on next&prev button clicks

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by mmalerba** [comment]
This is working as intended, the `monthSelected` event fires only when the user selects a month from the year view. In the case of clicking the next/previous buttons, the user is not selecting a month, rather they are just browsing more dates that they may or may not select

**Comment by honibis** [comment]
Thank you for the clarification. In my implementation, I rely on server-side data to set selectable dates and colors based on availability. Thus, it's essential for me to track when users navigate through months to retrieve availability data for the month they are currently viewing.

While I understand that the monthSelected event is specifically designed to trigger when a user selects a month from the year view, having an event for month navigation through the next/previous buttons would greatly enhance the functionality. This would provide developers with a broader range of events to handle different interactions within the calendar component.

Upon reviewing the source code, I couldn't find any existing event that fires when users click the next/prev buttons to navigate between months. Having such an event would greatly benefit developers who rely on this functionality for various use cases beyond simple date selection.

**Comment by honibis** [comment]
Created a feature request for a new event instead of bug: https://github.com/angular/components/issues/28749
