### ISSUE TITLE
bug(form-field): floatLabel moves outside of it's container

### ISSUE THREAD

**Issue by pedroestabruxelles** [angular/components#28715]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.x

### Description

Up until v14 form-field had a margin-top to accommodate the floating label when using appearance outline, since v16 that was removed. 
This causes a number of regressions where a form-field is at the very top of, for example, a container that has overflow: hidden. 

A similar issue has been reported on a different context but this is not particular to the tabs it's a broad issue:
https://github.com/angular/components/issues/27764

### Reproduction

StackBlitz link: https://stackblitz.com/edit/pix6qb

StackBlitz on the latest working version: https://stackblitz.com/edit/tfsfgk

### Expected Behavior

![image](https://github.com/angular/components/assets/46717433/7b0cda1d-4e34-40b4-8631-4f548ce7bb85)

### Actual Behavior

![image](https://github.com/angular/components/assets/46717433/856fedfe-e54e-4c1b-88d1-018759392f75)

### Environment

- Angular: 15.x, 16.x, 17.x
- CDK/Material: 15.x, 16.x, 17.x
- Browser(s): any browser
- Operating System (e.g. Windows, macOS, Ubuntu): any system

**Comment by mmalerba** [comment]
This is one of those things where its hard to pick settings that make everyone happy. In some cases people may want the label to jut into the content above (e.g. if its just dead divider space), or they may have floating labels disabled in which case they similarly do not want the extra reserved space.

We actually did try to change this at one point: https://github.com/angular/components/pull/25161 but found that it causes too many issues for existing usages to be worth it. Instead we recommend that if your use case requires some extra space for the label, just add some top margin or wrap it in an element that adds top margin.

**Comment by RedHeadEmile** [comment]
> This is one of those things where its hard to pick settings that make everyone happy. In some cases people may want the label to jut into the content above (e.g. if its just dead divider space), or they may have floating labels disabled in which case they similarly do not want the extra reserved space.
> 
> We actually did try to change this at one point: #25161 but found that it causes too many issues for existing usages to be worth it. Instead we recommend that if your use case requires some extra space for the label, just add some top margin or wrap it in an element that adds top margin.

Would it be possible to create an option to enable or disable it ?
