### ISSUE TITLE
docs-bug(COMPONENT): <mat-radio-group> is compatible with @angular/forms...where "compatible" means "requires"

### ISSUE THREAD

**Issue by JanStureNielsen** [angular/components#28736]
### Documentation Feedback

The radio button documentation says: 

> Use with `@angular/forms`
> `<mat-radio-group>` is compatible with `@angular/forms` and supports both FormsModule and ReactiveFormsModule.

"Use with" is accurate but unclear; and, "compatible" is accurate but even less clear. The current _radio button_ implementation **requires** `@angular/forms`; it simply does not compile without it, so express that clearly, perhaps:

> Requires `@angular/forms`
> `<mat-radio-group>` requires `@angular/forms` and supports both FormsModule and ReactiveFormsModule. 

It's unfortunate that the radio button requires `@angular/forms` but that's an design and/or implementation issue.

### Affected documentation page

https://material.angular.io/components/radio/overview

**Comment by mmalerba** [comment]
This statement is talking about how users can use the radio group in their template, not how its implemented. They can either connect it to a `FormControl`, or just use standard inputs and outputs to interact with it: https://stackblitz.com/edit/dkddmi?file=src%2Fexample%2Fradio-overview-example.html,src%2Fexample%2Fradio-overview-example.ts

**Comment by JanStureNielsen** [comment]
Ugh -- sorry about the noise, @mmalerba -- I copied the documentation sample which uses `ngModel`, and `ngModel` requires the `FormsModule` not the radio group.
