### ISSUE TITLE
feat(COMPONENT): TITLE

### ISSUE THREAD

**Issue by SarenT** [angular/components#28733]
### Feature Description

Currently button toggle and slide toggle are not supported inside mat form fields. However, these two components would have been useful form fields. I see no reason, why not include them. It may help adding labels, errors.

### Use Case

These two components and perhaps others are valuable additions to forms and benefit from mat form field features. Or perhaps, am I missing something about the use of mat form fields?

**Comment by mmalerba** [comment]
I realize that the naming is a little bit confusing, but the form-field is actually an implementation of Material Design's text field: https://m3.material.io/components/text-fields/overview which is designed to work with `<input>` and `<select>`. While some of the features do make sense for other types of controls (e.g. ability to associate errors), others do not (e.g. floating label). Unless the Material Design spec expands their scope to cover how the component would be expected to interact with these other controls, its not something we are likely to add.
