### ISSUE TITLE
bug(Autocomple): impossible to apply filtering on autocomplete field when the requireSelection input is set to true

### ISSUE THREAD

**Issue by ulrick** [angular/components#28742]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

I created a filter in my autocomplete field. When I set the requireSelection directive to true, nothing happens while searching for an option.
When the requireSelection is false, the filter work correctly

### Reproduction

https://components-issue-vy44as.stackblitz.io

### Expected Behavior

Filters should work

### Actual Behavior

Filters do not work when requireSelection is true 

### Environment

@angular-devkit/architect          0.1703.0
@angular-devkit/build-angular      17.3.0
@angular-devkit/core               17.3.0
@angular-devkit/schematics         17.3.0
@angular/cdk                       17.2.2
@angular/material                  17.2.2
@angular/material-moment-adapter   17.2.2
@schematics/angular                17.3.0
rxjs                               7.8.1
typescript                         5.4.2
zone.js                            0.14.4
Browser(s): Chrome
Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. See https://github.com/angular/components/issues/28378#issuecomment-1889244035.
