### ISSUE TITLE
bug(CdkDrag- CdkDragBoundary): directive `cdkDragBoundary` input properties do not work when the directive is assigned to a host element in a component decorator

### ISSUE THREAD

**Issue by evheniyrz** [angular/components#28758]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

n/a

### Description

the value passed to the directive's input property is not set when the directive is assigned to a host element in a `@Component` decorator using a `hostDirectives` array

```
@Component({
hostDirectives: [
    {
      directive: CdkDrag,
      inputs:[
        'cdkDragBoundary:"body"' // doesn't work. see line:62 inside ngOninit method
      ]
    },
  ],

})

ngOnInit():void{
this._cdkDrag.boundaryElement = 'body'; // !!!it works this way!!!
}
```

### Reproduction

StackBlitz link: https://stackblitz.com/~/github.com/evheniyrz/angular-cdk-drag-handle
GitHub link: https://github.com/evheniyrz/angular-cdk-drag-handle
Steps to reproduce:
1. Create a draggable component
2. Set the directive - `CdkDrag` - to the component host using the component decorator property - `hostDirectives`
3. Set values for directive input properties

```
@Component({
hostDirectives: [
    {
      directive: CdkDrag,
      inputs:[
        'cdkDragBoundary:"body"'
      ]
    },
  ],

})
```

### Expected Behavior

the dragged element is limited to the value set to the property - `cdkDragBoundary`

### Actual Behavior

The draggable element is not bound to the value set for the directive's input property - `cdkDragBoundary`

### Environment

- Angular:
"@angular/core": "^17.3.1", "@angular/cli": "^17.3.1",
- CDK/Material:
- "@angular/cdk": "^17.3.1", "@angular/material": "^17.3.1",
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
The `inputs` array in `hostDirectives` doesn't pass a value to that input, it determines which inputs from the host directive should be exposed on the host. In your example you're exposing `cdkDragBoundary` as `"body"` (including the quotes).

**Comment by evheniyrz** [comment]
@crisbeto oh sorry
![image](https://github.com/angular/components/assets/42120738/ae7a8d20-bd80-424b-b34b-ca6de0af44bb)
