### ISSUE TITLE
bug(MatFormField): mat-label overlays prefix mat-icon in outline mat-form-field in tab groups

### ISSUE THREAD

**Issue by jbrecht** [angular/components#28776]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

This problem is incredibly corner case, but if you use:
1. a mat-form-field with appearance="outline",
2. containing a mat-icon with the matPrefix or matIconPrefix directive,
3. along with a mat-label,
5. and the mat-form-field is within a mat-tab in a mat-tab-group,
6. and is _not the first tab_ in the mat-tab-group

then the mat-label will overlay the prefix icon. 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/vdcxsa-sre18u?file=src%2Fexample%2Fform-field-appearance-example.html
Steps to reproduce:
1. You will see the form field is fine in tab One
2.  and broken in tab Two.

### Expected Behavior

I expect the mat-label to appear to the right of the prefix icon

### Actual Behavior

The mat-label overlays the prefix icon. In fact I think it starts a bit to the left of it out of view.

### Environment

- Angular: ng15, ng16, or ng17
- CDK/Material: 15, 16, 17
- Browser(s): Chrome
- Operating System: macOS

**Comment by jbrecht** [comment]
I see this is a duplicate of: https://github.com/angular/components/issues/26428

**Comment by wagnermaciel** [comment]
Seems like this isn't as niche of an issue as you may have expected 😅 I'll close this issue for now since it's a duplicate
