### ISSUE TITLE
bug(google-maps): google.maps.Marker is deprecated

### ISSUE THREAD

**Issue by andro-bulj** [angular/components#28774]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Deprecation warning shows when using @angular/google-maps.

As soon as map-marker component is loaded in app the warning is shown in console.
![image](https://github.com/angular/components/assets/57639646/fd8ca771-9a8c-422a-8164-dee43c638829)

According to google [google.maps.Marker](https://developers.google.com/maps/documentation/javascript/reference/marker) is now legacy and [google.maps.marker.AdvancedMarkerElement](https://developers.google.com/maps/documentation/javascript/reference/advanced-markers) should be used instead. 

In the code for example [map-marker.ts](https://github.com/angular/components/blob/70d416fe3f04c0088419d64c8f4d7465f80be281/src/google-maps/map-marker/map-marker.ts#L290) we can see that the legacy code is being used.

Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

### Reproduction

Steps to reproduce:
1. git grep google.maps.Marker

### Expected Behavior

To use google.maps.marker.AdvancedMarkerElement instead of google.maps.Marker

### Actual Behavior

google.maps.Marker is used in map-marker.ts and deprecated warning is shown in console.

### Environment

- Angular: 17.3.0
- CDK/Material: 13.3.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

Package Version
Angular CLI: 17.3.0
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

**Package Version**
---------------------------------------------------------
Angular CLI: 17.3.0
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@angular/cdk                    17.3.1
@angular/google-maps            17.3.1
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
@types/google.maps 3.55.5

**Comment by crisbeto** [comment]
As of #28525 there's an advanced marker component that can be used instead of the deprecated one.
