### ISSUE TITLE
bug(COMPONENT): The m3 design spec updates are a breaking change, and should not be considered SemVer minor releases in v17.

### ISSUE THREAD

**Issue by Kerrick** [angular/components#28788]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v17.1.2

### Description

The m3 design spec has different aesthetics and, more importantly for backwards compatibility, different sizes, compared to the m2 design spec. This means that a person updating from v17.1.2 to v17.2.x or higher has a high likelihood of a broken application layout due to the library's changes. The m3 changes should not be considered minor changes according to [semver](https://semver.org/), and should have caused a v18.0.0 release instead.

### Reproduction

Steps to reproduce:
1. Have an application that has been laid out based upon the sizes of components in the m2 spec present in v17.1.x
2. Update a supposedly non-breaking minor version, v17.2.x, and see the components all change size to match the m3 spec and break your application's layout.

### Expected Behavior

A major version should be released and v17.x's latest version should be the latest version to align with the m2 spec.

### Actual Behavior

A minor version was released and v17.x's latest version breaks applications that worked with v17.1.2.

### Environment

- Angular: Any
- CDK/Material: v17.3.1
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by crisbeto** [comment]
M3 is completely opt in and we don't have any plans of removing the M2 styles. In v18 we'll make any _new_ apps (theme included by `ng add @angular/material`) be M3 by default, but they will also be able to go back to M2 if they want to.

**Comment by json-derulo** [comment]
I think there is a misunderstanding. The **docs app** has recently migrated to M3. But any project on v17.x is still on M2 styles, unless the `@angular/material-experimantal` package is installed and configured accordingly, as per [docs](https://material.angular.io/guide/material-3). What you are describing in this issue does not reflect reality.

**Comment by geromegrignon** [comment]
I agree with @json-derulo: the docs app defaults to M3 now.

As the docs app installation guide does not mention the `@angular/material-experimental`part, what we see should be what we get by following the installation guide. It'll make sense with v18 but it's really misleading meanwhile.

We already have some questions about that on the Angular Discord as people are creating apps with the v17.3.1 version (as mentioned on the docs app) but are getting M2 styles.

**Comment by Kerrick** [comment]
Ah, sorry about the confusion. I’m glad the sizing isn’t changing without an opt-in in 17.x. While the docs around this could improve, I’ll close this issue since that’s a different topic. Thanks for the clarification!
