### ISSUE TITLE
docs-bug(Button): For m3 buttons there's a needed dependency on material-experimental?

### ISSUE THREAD

**Issue by delhan1** [angular/components#28808]
### Documentation Feedback

In angular material button component preview:
https://material.angular.io/components/button/overview

Is an example of new appearance of buttons (m3). I have newest version (17.3.2) but I see my buttons in old (m2) way. After inspecting the styles, it seems variables are taken from predefined themes with (for example) old border radius value:
![image](https://github.com/angular/components/assets/8963600/dc2219b5-6cfa-4160-b688-91de4563168a)
vs
![image](https://github.com/angular/components/assets/8963600/30a91ea1-32e1-473e-89a7-32389e3acfc3)

I found out I need to follow this page to be able to implement m3 styles properly (with usage of material-experimental) https://material.angular.io/guide/material-3 but there's no obvious way to apply it from the button's page code overview https://material.angular.io/components/button/overview

I checked stackblitz example for buttons that you present and it seems there's a needed dependency on material-experimental in order to be working properly:
![image](https://github.com/angular/components/assets/8963600/6a14037e-16ec-458f-b68e-bab93734a764)

So I'd suggest to put some switch in docs between m2 and m3 appearances, so it's clear what is what. It seems docs are now exclusively m3 and what was before about copy'n'paste of piece of code is now about wandering through docs and finding out you need to actually install material-experimental to make it look like it. Because by default m2 styles are used but they're no more shown in the docs.

### Affected documentation page

https://material.angular.io/components/button/overview

**Comment by crisbeto** [comment]
The code will be moved into `@angular/material` for version 18.
