### ISSUE TITLE
bug(MatButtonToggle): checkmark options added in 17.3 introduce an undocumented breaking change

### ISSUE THREAD

**Issue by hamfastgamgee** [angular/components#28810]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.2.x

### Description

The new-in-17.3 hideSingleSelectionIndicator and hideMultipleSelectionIndicator flags in MAT_BUTTON_TOGGLE_DEFAULT_OPTIONS are set in such a way that checkmarks will show up by default for all Material button toggles, regardless of M3 or otherwise.  This should either have been set to "true" by default for now (to hide them) or documented as a breaking change.  I just took a normal minor release and now my app which makes extensive use of button toggles has positioning issues all over the place due to the checkmark.  It's easy enough to override the injection token, but it shouldn't have been necessary for a minor release.

I 100% agree that the checkmark is nice to have for accessibility, etc, and it might be the proper default for a major release, but pretty sure the intent was not to have it show up by default in 17.3 given there were no upgrade notes, breaking change indicators, etc.

### Reproduction

Steps to reproduce:
1. Load up an existing app with mat-button-toggle.
2. Oops, default checkmarks!

### Expected Behavior

The checkmark should not be the default in a minor release.

### Actual Behavior

Checkmarks all over the place.

### Environment

- Angular: 17.3.2
- CDK/Material: 17.3.2
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Any

**Comment by zarend** [comment]
Hello,

Thank you for this feedback. In 17.3 minor release, MatButtonToggle displays checkmark indicator by default. Opt-out of checkmark using `hideSingleSelectionIndicator` and `hideMultipleSelectionIndicator`. Opt-out is available by Input and Dependency Injection, [API reference for Angular Material button-toggle](https://material.angular.io/components/button-toggle/api). If the checkmark is unwanted, you can inject configuration to disable it for all MatButtonToggle in your application.

I believe that making visual changes is generally not covered by [API changes policy](https://github.com/angular/angular/blob/main/docs/PUBLIC_API.md), so we generally don't consider visual changes to be breaking changes. Feel free to open a discussion if you would like to discuss further.

In general, we strive to make the default configuration the accessible configuration.

Best Regards,

Zach

**Comment by zarend** [comment]
Hello @hamfastgamgee , I think this is a reasonable opinion. I am aware of the checkmark changes, but I am less aware of the changes to button sizes. I'll share this feedback with our team.

Best Regards,

Zach

**Comment by simeyla** [comment]
This caught me out too and I've had this monstrosity live for several days without even having thought to check it. 

<img width="272" alt="image" src="https://github.com/angular/components/assets/3656278/fb2d745f-877b-41b8-81b0-80fe697dd14c">

Previously there was no check mark at all, although It seems I'd used `hideSingleSelectionIndicator` elsewhere before (unfortunately not in this place).

Fortunately end users are pretty resilient, even to ugly changes like this.
