### ISSUE TITLE
mat-form-field not working with highchart

### ISSUE THREAD

**Issue by spyadav14699** [angular/components#28822]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

if i am removing  
 mat-select it affecting other ui 
  <mat-form-field class="smallDropdown">
                <mat-select [(value)]="chartType">
                    <mat-option value="Bar Chart">Bar Chart</mat-option>
                    <mat-option value="Line Chart">Line Chart</mat-option>
                </mat-select>
                
            </mat-form-field>
            
            bit when i remove hole div it's working fine please look into this

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

should be work

### Actual Behavior

affecting other ui

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):
mac0s , all browser

**Comment by amysorto** [comment]
I don't have enough information here to assist. I assume you are referring to a separate library for charting, so it would likely make more sense to create your issue in that repository instead. If your issue is angular material specific, please create a new issue with a reproduction on StackBlitz.
