### ISSUE TITLE
feat(cdk-drag-drop): create new non mutating utils

### ISSUE THREAD

**Issue by DaSchTour** [angular/components#28824]
### Feature Description

Instead of mutating the arrays in `moveItemInArray`, `transferArrayItem` and `copyArrayItem` there should be new functions that return new arrays.

### Use Case

Especially with signals the mutating drag and drop utils `moveItemInArray`, `transferArrayItem` and `copyArrayItem` may lead to very ugly behavior. 

So for example this code will not work correctly but is hard to debug, as the changes do not update the UI or trigger effects.

Does not work, although some devs might expect it to work.
```ts
class SomeService {
  public readonly selected = signal([]);
  
  public move(previousIndex: number, currentIndex: number) {
        this.selected.update((selected) => {
          moveItemInArray(selected, previousIndex, currentIndex);
          return selected;
        });
    }
}
```

Workaround copy the array
```ts
class SomeService {
  public readonly selected = signal([]);
  
  public move(previousIndex: number, currentIndex: number) {
        this.selected.update((selected) => {
          moveItemInArray(selected, previousIndex, currentIndex);
          return [...selected];
        });
    }
}
```

Ideal solution
```ts
class SomeService {
  public readonly selected = signal([]);
  
  public move(previousIndex: number, currentIndex: number) {
        this.selected.update((selected) => {
          // to avoid breaking changes the name of the method might be different
          return moveItemInArray(selected, previousIndex, currentIndex);
        });
    }
}
```

**Comment by crisbeto** [comment]
We talked through it within the team and decided not do it, because it's pretty straightforward to use a spread operator before passing the array into the existing functions.

**Comment by DaSchTour** [comment]
I'm really stunned. While TC39 introduces non mutating toSorted/toReversed the angular team things that mutating arrays is still a good idea? I was already wondered why these array functions are mutating from the start, as this is a known cause for issues with change detection and in general a bad practice.
