### ISSUE TITLE
Strange behavior of FormGroup in custom control

### ISSUE THREAD

**Issue by VitalyV** [angular/components#28837]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I created my own custom control, which slightly changes the behavior of DatePicker from Angular material.
Inside the custom component, I use FormGroup to store the Start and End controls.
The main problem arose in the `writeValue` method.
Inside this method there is a code that sets a new state for the internal form and when calling `patchValue` with `emitEvent: false` parameter. But it doesn't work as expected.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-lsrf8q
Steps to reproduce:
1. Select any date in Datepicker
2. Click the `Set custom date range` button

### Expected Behavior

I expect that when clicking on the button in the console, only one line `#-write_value` will be output

### Actual Behavior

In addition to the string `#-write_value`, the string `#-selected_date` is also output, which is very strange, because I set the flag `emitEvent: false`

Why is this happening? What am I missing out on?

### Environment

- Angular: 16.1.3
- CDK/Material: 16.1.3
- Browser(s): Chrome 114.0.5735.199
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
I suspect this is the same root cause as https://github.com/angular/components/issues/21875.
