### ISSUE TITLE
feat(Datepicker): Inline datepicker | next previous click events

### ISSUE THREAD

**Issue by mit-bhalodi** [angular/components#28831]
### Feature Description

Fro inline datepicker we do not have a way to identify that which month view is currently opened when we click next and previous arrows. So basically there is not even emitter for next and previous buttons

### Use Case
I am using the inline datepicker and dateClass to show some information and color the cells accridingly. It works fine for the current month but when I move to previous/next month I want to make an API call based on the month view that has been selected color the cell background again based on the current view.

<img width="398" alt="Screenshot 2024-04-05 at 10 06 19 PM" src="https://github.com/angular/components/assets/42618929/8a1b03e7-6f7e-428a-9f5a-48700ecc4831">

**Comment by amysorto** [comment]
I think what you are looking for is `monthSelected`, an output on [`mat-datepicker`](https://material.angular.io/components/datepicker/api#MatDatepicker). Please reopen the issue if that doesn't work for your use case. Thanks!

**Comment by mit-bhalodi** [comment]
monthSelected emits even only when month is selected from the year view, what problem I am facing is we do not have any emitter **when we click next and previous arrows**.

**Comment by mit-bhalodi** [comment]
How can I reopen this issue?
