### ISSUE TITLE
Text description of static chips doesn't match code example

### ISSUE THREAD

**Issue by finleyjb** [angular/components#28845]
### Documentation Feedback

If you look at the documentation for chips, you can see that the textual description talks about using `<mat-chip-set>` and `<mat-chip>`. However, the example uses `<mat-chip-listbox>` and `<mat-chip-option>`. If there's a reason for this discrepancy, the documentation should specify why that is.

### Affected documentation page

https://material.angular.io/components/chips/overview#static-chips

**Comment by lsamboretrorabbit** [comment]
I have provided a solution, awaiting review
