### ISSUE TITLE
bug(MAT-TOOLTIP): Migration job in v15 performs a wrong replace

### ISSUE THREAD

**Issue by Avishai235423** [angular/components#28840]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The class mat-tooltip isn't equal to mat-mdc-tooltip.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.
 

### Expected Behavior

the right class should be - 'mdc-tooltip__surface'

### Actual Behavior

 replace mat-tooltip to mat-mdc-tooltip

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
It does seem that `mdc-tooltip__surface` is likely a better mapping, although the code for the migration tool is going to be deleted https://github.com/angular/components/pull/28838
