### ISSUE TITLE
bug(mat-sort-header) 'mat-sort-header' adds white space at the bottom of the page

### ISSUE THREAD

**Issue by hanlingczhong** [angular/components#28859]
### Description

I have used toolbar and sidebar for the navigation. And in the sidebar-content I have the 'router-outlet'.

Now on one of the pages, I use the Material Table there. The table itself works fine but if I add the mat-sort-header to the header th, it will create white space at the bottom of the page for some reason. And I don't think this is a style issue as it only appears if I use 'mat-sort-header'. Other things like pagination/filtering don't create this white space.

![image](https://github.com/angular/components/assets/156143059/3952aaaf-9957-4e31-9099-a6fd72ea8122)

Does anyone experience the same issue?

### Environment

- Angular: 17.2.3
- CDK/Material: 17.2.2
- Browser(s): Firefox and Google Chrome

**Comment by crisbeto** [comment]
Your theme is likely missing the `mat.core` mixin.

**Comment by hanlingczhong** [comment]
> Your theme is likely missing the `mat.core` mixin.

Thank you this is the issue.
