### ISSUE TITLE
bug(cdk/drag-drop): preview element position breaks when parent uses transform

### ISSUE THREAD

**Issue by chintankavathia** [angular/components#28864]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using `[cdkDragPreviewContainer]="'parent'"` and having parent element with css styles transform on it breaks the position of preview item when user starts dragging.

This is because preview item uses position: fixed and when parent has transform css, child with fixed position's offset starts from its parent instead of browser viewport.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/j5v8si?file=src%2Fexample%2Fcdk-drag-drop-connected-sorting-group-example.html
Steps to reproduce:
1.  create two connected drag drop list 
2. use [cdkDragPreviewContainer]="'parent'" on drag item in second list
3. apply style="transform: translateZ(0)" to parent 
4. now drag the item from second list and observe the position of preview item as you drag

### Expected Behavior

drag preview item should calculate correct position so that it follows mouse curser position.

### Actual Behavior

drag preview item gets wrong position and sometime shows far away from cursor position.

### Environment

- Angular: 17.3.0
- CDK/Material: 17.3.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
This is one of the reasons why we default the preview container to the `body`. I'm closing the issue since the browser doesn't have an API that would allow us to account for it, or we would have to do some ugly hacks that either compromise performance or can break other use cases.

**Comment by chintankavathia** [comment]
> This is one of the reasons why we default the preview container to the `body`. I'm closing the issue since the browser doesn't have an API that would allow us to account for it, or we would have to do some ugly hacks that either compromise performance or can break other use cases.

@crisbeto  Fair enough, but this needs to be mentioned somewhere in API so that users take this into account while using `[cdkDragPreviewContainer]="'parent'"`. right now it only talks about sideeffect of overflow:hidden.
