### ISSUE TITLE
bug(mat-selection-list): A List with single selection still writes an array instead an single value

### ISSUE THREAD

**Issue by NCC1701M** [angular/components#28861]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

not tested

### Description

When you are using `[(ngModel)]` on a `mat-selection-list` which is configured to only select a single option, `ngModel` still writes an array value instead of a single value.

When a value is selected, the selected values json representation is displayed e.g. `[ "Sneakers" ]`

### Reproduction

StackBlitz link: https://stackblitz.com/edit/xh9gxz-ae2ipa
Steps to reproduce:
1. Run the StackBlitz
2. Select a shoe type
3. See the json output below `Select one to see the ngModel value:`

### Expected Behavior

When the directive `[multiple]` is set to **false**, the selected value should be written directly instead on an array, because it's not possible to select more than one value, so there is no need for an array.

If `[multiple]` is set to **true**, then the actual behaviour is correct.

### Actual Behavior

The component is ignoring the `[multiple]` directive and always writing an array value using `[(ngModel)]`

### Environment

- Angular: 17.3.0
- CDK/Material: 17.3.0
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 20.04.0 LTS (StackBlitz default)

**Comment by amysorto** [comment]
I would call this a P5 issue, so I am going to close it. Although if there is more interest for this, the issue can be reopened!
