### ISSUE TITLE
Add Styling tab to component pages

### ISSUE THREAD

**Issue by dzivoing** [angular/components#28879]
### Documentation Feedback

Since theming angular material is proving very hard since the first version i suggest you create styling guides for each component. I know its a lot of work but it would be great to have it in the documentation. I would put there some of the most common ways to style a component. For example for mat card how to remove elevation. For buttons how to change colors outside of the primary. We all love material design but we need these things to make our apps feel like our apps. 

In the styling guide how are we supposed to know what mat.define-dark-theme properties etc. We need more documentation about those. 

I find myself googling these simple things every time i am implementing some of the designs and it is frustrating. I believe you did a good job creating all of these things for styling but it is very hard for us to use them.

Thank you and i hope you take this into consideration.  
This is related to documentation in general for all components

### Affected documentation page

https://material.angular.io/guide/theming#applying-a-theme-to-components

**Comment by mrmokwa** [comment]
You can check specs here:

https://m3.material.io/components

**Comment by amysorto** [comment]
Closed by https://github.com/angular/material.angular.io/pull/1283. Here is a preview for menu: https://next.material.angular.io/components/menu/styling
