### ISSUE TITLE
bug(Typography): .mat-mdc-tab-body-content gets a padding on its right side when mat.typography-hierarchy is included.

### ISSUE THREAD

**Issue by Gerandon** [angular/components#28872]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm not sure yet, what causes the problem, but:

If I understand it correctly:
When we want to create a custom theme, with typography, we have to create a theme (e.g.: light) in which, besides the colors we should define the `typography` field, to ensure, all our material components will have the defined typography styling.

If we want to extend these settings in our whole application, besides the material components we have to include another mixin, called `mat.typography-hierarchy` and call it with the same typo. settings as before.

**Here comes the funny part**
After I've included `typography-hierarchy`, a strange behavior happened with `<mat-tab-group>`, especally `<mat-tab>`.
Using this mixin a padding appears (I could not backtrack where it comes from yet) and even if the best scenario is to wrap our texts into their appropriate tag elements, It's still a bit strange for me.
Looks like this:
![Képernyőfotó 2024-04-11 - 21 16 46](https://github.com/angular/components/assets/16354561/0b6b6b08-9621-455f-9be4-ba86d2a9ad73)

I'm a bit confused and still I'm searching for what causes this.
If it's not a bug just an annoying thing, you can close this bug, but still it's a bit confusing for me why is that padding gets there additionally, with the same typography settings we are using inside material components

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-2kbrov?file=src%2Fglobal_styles.scss
Steps to reproduce:
1. Create a pure Angular project, including Angular Material with a Build-in theme.
2. Create a typography config
3. Include this config with `typography-hierarchy` mixin
4. Add `mat-tab` to the app.component, with a simple text inside the content
5. Check `mat-mdc-tab-body-content` whether there is a padding at the end or not

### Expected Behavior

No padding added additionally when using `typography-hierarchy`
![Képernyőfotó 2024-04-11 - 21 22 32](https://github.com/angular/components/assets/16354561/9d7aa21a-78f0-480d-b263-c051de049833)

### Actual Behavior

Padding is added to the end of the line
[
![Képernyőfotó 2024-04-11 - 21 16 46](https://github.com/angular/components/assets/16354561/04b8cb78-c42f-4528-bc2d-f875fce757bc)
](url)

### Environment

- Angular: 17.3.3
- CDK/Material: 17.3.3
- Browser(s): Chrome/Edge
- Operating System (e.g. Windows, macOS, Ubuntu): macOs/Windows

**Comment by crisbeto** [comment]
The difference comes from the fact that by default the `body` has `line-height: normal`, whereas `.mat-typography` sets `line-height: 16px`. There's no add padding being added, but rather the height of each line of text increases which adds the space. You can either reset the `line-height` back to `normal` on the body or specifically on the tabs.
