### ISSUE TITLE
MatSort: Setter is executed multiple times in some components and just once in other components

### ISSUE THREAD

**Issue by sbma24** [angular/components#28873]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I use mat-tabel for all tables in my app and MatSortto add a sort functionality to them. During adding the sort functionality to the tables I've experienced very strange behaviors of MatSort. In some components the setter of MatSort is executed multiple times and in other components just once.

As a result, I have to handle the MatSort in components where it's only set once differently as in the components where it's set multiple times.

I've searched for reasons. But haven't found any. The strange thing is that two of all components are almost the same but in one component the MatSort's setter is executed multiple times and in the other just once. 

### Reproduction

I don't know how I can reproduce the bug, because both components I speak about in the description set the table's data-source initially `public dataSource = new MatTableDataSource<Data2>();` and overwrite it after the data is set asynchron` this.dataSource = new MatTableDataSource(this.data);`. In some components the MatSort's setter is exeuted again if this.dataSource has been overwritten. 

StackBlitz link: https://stackblitz.com/edit/components-issue-omvcop?file=src%2Fapp%2Fcomponent-two%2Fcomponent-two.component.ts

In the Stackblitz you can see that I have to assign the matSort's-value to a private property in **component one** where I load the data asynchron. 

In **component two** the data is loaded synchron and the mat-sort works from the beginning. **Important**: In my application the data in component2 is loadad asynchon too, but has the behavior as if I would load the data synchron.

### Expected Behavior

The table's sort functionality and behavior has to work for asynchron loaded data equal.  

### Actual Behavior

The table's sort functionality is different between two components that load the data asynchron. In one of them it works and in the other it doesn't

### Environment

- Angular: ^15.5.1
- CDK/Material: ^15.1.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
Closing since we don't make any guarantees as to how often setters will be called. It's also trivial to ignore some of the calls if necessary.
