### ISSUE TITLE
feat(cdk/dialog): Support for Leaving Animation - wait for all child animations to complete before disposing the overlay

### ISSUE THREAD

**Issue by Char2sGu** [angular/components#28878]
### Feature Description

Currently, when closing a dialog, the corresponding overlay is immediately disposed (L106):

https://github.com/angular/components/blob/e3eef47f80a7c1dda4b538128fed7f530f7cdff1/src/cdk/dialog/dialog-ref.ts#L99-L113

And when disposing an overlay, the host `<div>` element of the overlay is immediately removed from the DOM (L269):

https://github.com/angular/components/blob/e3eef47f80a7c1dda4b538128fed7f530f7cdff1/src/cdk/overlay/overlay-ref.ts#L252-L280

The current behavior completely eliminated the possibility to implement a `:leave` animation for dialogs, since the ancestor element of the dialog, the overlay, is removed via the native DOM API, and the Angular animation engine cannot hook into this process to perform the `:leave` animation.

As a solution, I propose to allow the DialogContainer to decide when the overlay should be disposed. By doing so, we can create another DialogContainer aside from CdkDialogContainer, e.g. LeaveAnimationAwareDialogContainer, which performs a leave animation that does nothing but `animateChild()`. The LeaveAnimationAwareDialogContainer notifies the DialogRef to dispose the overlay after the leaving animation is completed.

**Comment by NickUfer** [comment]
Got the same problem, I solved it for now by extending Dialog and DialogRef. I use AnimationBuilder to build and play these animations and wait for them to finish to then execute `super.close()`. I'm thinking about creating a MR to add this directly into the lib.

**Comment by Char2sGu** [comment]
Here's another workaround: extend the `Dialog` implementation to delay the diposal of the dialog until all animations are done:

```ts
import { animateChild, query, transition, trigger } from '@angular/animations';
import {
  CdkDialogContainer,
  Dialog,
  DialogConfig,
  DialogRef,
} from '@angular/cdk/dialog';
import {
  BasePortalOutlet,
  CdkPortalOutlet,
  ComponentType,
} from '@angular/cdk/portal';
import { Component, Injectable, TemplateRef } from '@angular/core';
import { firstValueFrom, Subject } from 'rxjs';

/**
 * Currently, when closing a dialog, the corresponding overlay is immediately
 * disposed, which means that the host element of the overlay is immediately
 * removed from the DOM using the native API.
 *
 * The current behavior completely eliminated the possibility to implement a
 * `:leave` animation for dialogs, since the ancestor element of the dialog,
 * the overlay, is removed via the native DOM API, and the Angular animation
 * engine cannot hook into this process to perform the `:leave` animation.
 *
 * This class works around the issue by waiting `:leave` animations to complete
 * before disposing the overlay.
 *
 * @see https://github.com/angular/components/issues/28878
 */
@Injectable()
export class AnimationAwareDialog extends Dialog {
  override open<R = unknown, D = unknown, C = unknown>(
    componentOrTemplateRef: ComponentType<C> | TemplateRef<C>,
    config: DialogConfig<D, DialogRef<R, C>, BasePortalOutlet> = {},
  ): DialogRef<R, C> {
    if (componentOrTemplateRef instanceof TemplateRef)
      throw new Error('TemplateRef not supported');
    config.container = AnimationAwareDialogContainer;
    const ref = super.open(componentOrTemplateRef, config);
    const close = ref.close.bind(ref);
    ref.close = async (...args) => {
      const container = ref.containerInstance as AnimationAwareDialogContainer;
      const animationDone = firstValueFrom(container.animationDone$);
      // Detaching an overlay removes the overlay's content through standard
      // Angular APIs, so the animations can be correctly triggered.
      ref.overlayRef.detach();
      await animationDone;
      close(...args);
    };
    return ref;
  }
}

@Component({
  selector: 'agl-animation-aware-dialog-container',
  standalone: true,
  imports: [CdkPortalOutlet],
  template: `<ng-template cdkPortalOutlet />`,
  styles: `
    :host {
      display: block;
    }
  `,
  host: {
    '[@DialogContainer]': '',
    '(@DialogContainer.done)': 'animationDone$.next()',
  },
  animations: [
    trigger('DialogContainer', [
      transition(':leave', query('@*', animateChild())),
    ]),
  ],
})
export class AnimationAwareDialogContainer extends CdkDialogContainer {
  animationDone$ = new Subject<void>();
}
```

```ts
    {
      provide: Dialog,
      useClass: AnimationAwareDialog,
    },
```

**Comment by NickUfer** [comment]
I created [an MR](https://github.com/angular/components/pull/29002) for this which allows defining open and close animations for overlay and backdrops like this: https://github.com/angular/components/blob/f0a41563b71fe0a9932452a3759abcf6a728d13b/src/cdk/dialog/dialog-config.ts#L173-L207

Works great so far on the dev ui:

https://github.com/angular/components/assets/11254522/faebf6f8-9231-4190-861f-bf03eebd9204

The hide for 2 seconds is part of the opened component and has no animations implemented, so it looks a bit rough, but thats not part of the CDK

**Comment by amysorto** [comment]
Closing since we are trying to move away from having support for `@angular/animations` and encourage using CSS animations directly instead.

**Comment by NickUfer** [comment]
Well, that is literally not possible right now and this issue is still valid.
