### ISSUE TITLE
bug(icon-button): surface color variant not producing any tokens 

### ISSUE THREAD

**Issue by pgg** [angular/components#28882]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

@include mat.icon-color($theme, $color-variant: surface); not outputting tokens/css vars. styles compile just fine, but final icon with applied css class does not have overridden --mat-icon-color variable as is the case with other supported variants according to the m3 docs @ https://material.angular.io/guide/material-3

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-uhxy6j?file=src%2Fmain.ts
Steps to reproduce:
1. run app
2. inspect final css, surface-icon class missing, unlike primary-icon class

### Expected Behavior

final styles to contain both:
```
html .primary-icon {
  --mat-icon-color: #00dddd;
}
``` 
and 
```
html .surface-icon {
  --mat-icon-color: #...;
}
```

### Actual Behavior

surface-icon class missing

### Environment

```
Angular CLI: 17.3.4
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1703.4
@angular-devkit/build-angular    17.3.4
@angular-devkit/core             17.3.4
@angular-devkit/schematics       17.3.4
@angular/material-experimental   17.3.3
@schematics/angular              17.3.4
rxjs                             7.8.1
typescript                       5.3.3
zone.js                          0.14.4
```

**Comment by amysorto** [comment]
Hi! The [color palettes](https://material.angular.io/guide/material-3#reading-tonal-palette-colors) that can be passed in are `primary`, `secondary`, `tertiary`, `error`, `neutral`, and `neutral-variant`. 

Although in your case, surface technically comes from the neutral palette and is hue 98. So in your styles you can do the following:
```
html {
  --mat-icon-color: mat.get-theme-color($theme, neutral, 98);
}
```

**Comment by pgg** [comment]
hi @amysorto, see updated stackblitz:
```
Invalid color variant: neutral. Supported color variants are: surface, primary, secondary, tertiary, error.
```
