### ISSUE TITLE
docs-bug(multiple): `errors` seems a better choice in templates instead of `hasError()`

### ISSUE THREAD

**Issue by ice-blaze** [angular/components#28883]
### Documentation Feedback

Apprently in the Angular documentation to validate forms they never use `hasError()` function [source](https://angular.dev/guide/forms/form-validation#validating-input-in-template-driven-forms). But in material documentation it's used in some different [places](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown).

Even tho the performance gain will be small, I have the feeling we should have a documentation that should share code that follows the "best practices". 

### Affected documentation page

https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

**Comment by crisbeto** [comment]
Closing this based on the discussion in https://github.com/angular/components/pull/28884.
