### ISSUE TITLE
bug(ThemePalette): ThemePalette for Material 3

### ISSUE THREAD

**Issue by seneric** [angular/components#28902]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Currently in some components (radio-button for example) the color is typed themePalette.
But themePalette only allows 'primary', 'accent' and 'warn' colors.
So if we try to use it with a Material 3 palette it is not possible to specify a 'primary', 'secondary', 'tertiary' and 'error' color.

color.ts contain
`/** Possible color palette values. */

export type ThemePalette = 'primary' | 'accent' | 'warn' | undefined;`

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

ThemePalette Marerial 3 compatible

### Actual Behavior

ThemePalette only Marerial 2 compatible

### Environment

- Angular: 17.3.1
- CDK/Material: 17.3.1
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by amysorto** [comment]
Colors are different in M3, the spec has a whole new color system (https://m3.material.io/styles/color/roles). For example, `accent` does not exist in M3.

We have a mixin for backwards compatability that I would recommend taking a look at so you can keep your existing color variants but get to use M3: https://material.angular.io/guide/material-3#optional-add-backwards-compatibility-styles-for-color-variants

**Comment by seneric** [comment]
I know the "backwards compatability" mixin I use it !
But I want to develop a new full M3 compatability web site.

**Comment by JGSolutions** [comment]
i tried this with the different color variants for ex: primary, secondary or tertiary and does not work. Always getting the tertiary with a custom theme that i generated

@use '@angular/material' as mat;

$theme: mat.define-theme();

.tertiary-checkbox {
  @include mat.checkbox-color($theme, $color-variant: tertiary);
}

**Comment by seneric** [comment]
for me it works
I defined three classes
.tertiary-checkbox {
@include mat.checkbox-color($theme, $color-variant: tertiary);
}
.secondary-checkbox {
@include mat.checkbox-color($theme, $color-variant: secondary);
}
.primary-checkbox {
@include mat.checkbox-color($theme, $color-variant: primary);
}


In your html 
<mat-checkbox class="primary-checkbox">...</mat-checkbox>
<mat-checkbox class="secondary-checkbox">...</mat-checkbox>
<mat-checkbox class="tertiary-checkbox">...</mat-checkbox>

**Comment by JGSolutions** [comment]
it works, my bad. 
I passed the wrong theme: $theme: mat.define-theme(); 

Instead I had to pass my generated theme.

thanks for the reply
