### ISSUE TITLE
bug(mat-datepicker): datepicker color variants not being applied

### ISSUE THREAD

**Issue by pgg** [angular/components#28900]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

datepicker always receives primary colors. calendar does work though . . .

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-jpgaks?file=src%2Fstyles.scss
Steps to reproduce:
1. open date picker or date range picker, colours are always primary, unlike calendar

### Expected Behavior

color variants to be applied like calendar

### Actual Behavior

color variants are always primary

### Environment

```
Angular CLI: 17.3.5
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-experimental, platform-browser
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by crisbeto** [comment]
It's because the calendar is rendered in an overlay so you have to pass it into the `panelClass` input. Here's a working example: https://stackblitz.com/edit/stackblitz-starters-c5oafz?file=src%2Fmain.ts.

**Comment by pgg** [comment]
ok thanks!
