### ISSUE TITLE
bug(cdk/overlay): BlockScrollStrategy is not working properly when overlay is called inside OnInit

### ISSUE THREAD

**Issue by thekhegay** [angular/components#28922]
### Description

I didn't find any description in the [documentation](https://material.angular.io/cdk/overlay/examples), but when `Overlay` creation called in `OnInit`, `BlockScrollStrategy` is not blocking scroll.
 
I noticed another behavior:
- `height: 101vh` applied as `app-root` styles, block is working fine [(stackblitz)](https://stackblitz.com/edit/stackblitz-starters-pgkceq?file=src%2Fmain.ts)
- `height: 101vh` is applied as `.root` class with `@HostBinding` call - block is not working ([stackblitz](https://stackblitz.com/edit/stackblitz-starters-xzd26d?file=src%2Fmain.ts))

I think related: https://github.com/angular/components/issues/19020, https://github.com/angular/components/issues/22217

### Reproduction

Everything works fine when called inside `AfterViewInit`: https://stackblitz.com/edit/stackblitz-starters-sp8ikj?file=src%2Fmain.ts

### Environment

- Angular: 17.3.5
- CDK/Material: 17.3.5
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by crisbeto** [comment]
The strategy needs to measure the sizes of elements in order to block scrolling. `ngOnInit` is likely too early for that to happen reliably. You can try either moving it to a later hook or wrapping it in a `requestAnimationFrame`.
