### ISSUE TITLE
bug(DatePicker): Appearing in wrong position at bottom of component HTML

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/components#28920]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Here is my component code:

```
        <mat-form-field class="form-date">
          <mat-label>Contract Start Date</mat-label>
          <input matInput [matDatepicker]="picker" formControlName="contractStart">
          <mat-hint>DD/MM/YYYY</mat-hint>
          <mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
          <mat-datepicker #picker [startAt]="contractStart.value"></mat-datepicker>
        </mat-form-field>
```

The data picker when I open it always appears at the bottom of the HTML, rather than next to or above the form field, that is in a form, in a modal in the HTML. See attached picks. 

<img width="413" alt="Screenshot 2024-04-21 at 17 14 15" src="https://github.com/angular/components/assets/39380005/6a409bae-762c-48aa-ae6a-5f9fc40c2101">
<img width="526" alt="Screenshot 2024-04-21 at 17 14 27" src="https://github.com/angular/components/assets/39380005/972972ba-e696-40f6-88f0-019c2f76290e">

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Should appear next to the field it's called from, at the correct position and Z index, etc.

### Actual Behavior

Appearing at bottom of page, also at z index 0, at maximum width. 

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
You're likely missing the `mat.core` mixin in your theme.

**Comment by dreamstar-enterprises** [comment]
Thank you. I was missing the mat.core and didn't provide an argument to panelClass in mat-datepicker 
Is there somwhere that has all the new m3 color pallettles, comparing primary through to tertiary colors?
