### ISSUE TITLE
bug(AUTOCOMPLETE): Autocomplete options are flowing above the page header

### ISSUE THREAD

**Issue by mazhar-fis** [angular/components#28937]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When we open the autocomplete options and scroll the page, the popup flows above the page header.

https://github.com/angular/components/assets/114717711/a18a40f2-8ca5-4cb9-9611-3175ce084b14

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Go to: https://material.angular.io/components/autocomplete/overview
2. Go to example: Display value autocomplete
3. Open the options
4. Scroll the page down so that the popup overlaps the page header.

### Expected Behavior

The popup should flow below the page header.

### Actual Behavior

The popup is flowing above the page header.

### Environment

- Angular: 17.3.0
- CDK/Material: 17.3.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. Overlays are set up to be on top of everything on the page.
