### ISSUE TITLE
bug(BUTTON): primary color does not apply on button when encapsulation is shadowdom

### ISSUE THREAD

**Issue by kibetmasi** [angular/components#28935]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular Material _color="primary"_ does not work on mat-raised-button

### Reproduction

```
@Component({
  standalone: true,
  encapsulation: ViewEncapsulation.ShadowDom,

  `,

<button mat-raised-button color="primary" class="inline-flex py-2 px-6">
   Proceed
 </button>
```

### Expected Behavior

Passing _color="primary"_ should set the button color as the primary color on mat-raised-button

### Actual Behavior

Button color remains white and is unset

### Environment

@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
If you're using shadow DOM encapsulation, you have to include the button theme in the component itself since global styles don't apply.

**Comment by kibetmasi** [comment]
> If you're using shadow DOM encapsulation, you have to include the button theme in the component itself since global styles don't apply.

It still does not work when you remove shadow dom
Also, testing with other elements still works when set as shadow dom
I tried with multiple Material elements and the theme is preserved when encapsulation is shadow dom
