### ISSUE TITLE
bug(MatError): Cannot put spacing around Mat Error - want to put bottom margin - can only see left and right 16px padding

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/components#28930]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I can't edit spacing around mat-error.

I've tried

```
.mat-mdc-form-field-error-wrapper {
  margin: 0 16px 10px 16px !important;
}
```

But it doesn't work. If I have 3 errors shown at the same time, they overflow the main mat-form-field wrapper, and don't push the elements below them down

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

See above

### Actual Behavior

See above

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment]
Can you provide a stackblitz with your example?

**Comment by crisbeto** [comment]
Closing since there hasn't been any follow-up.
