### ISSUE TITLE
docs(material/theming): add section for overrides api to theming.md

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#28952]
### Documentation Feedback

Add a section to theming.md to describe the 3 new override APIs. The section should describe:

1. The benefits of using these APIs.
2. How to use them.
3. What use case each is best suited for.

This information is already outlined in [go/angular:mat-theming-overrides-api](http://go/angular:mat-theming-overrides-api).

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by key7men** [comment]
I urgently need the usage documentation for "override APIs".

**Comment by amysorto** [comment]
Closing since the docs site starting in v19 will have documentation for all the different componenent's override functions. This is an preview for button: https://next.material.angular.io/components/button/styling
