### ISSUE TITLE
feat(SELECT): dynamic width of select is causing visibility issue

### ISSUE THREAD

**Issue by Mehadmushtaq** [angular/components#28964]
I just migrated my product build on **angular 11 to angular 16** version by version after migrating to **angular material v15** seeing a lot of unexpected changes and following is one of them.

**Scenerio #1**
![Screenshot from 2024-04-25 15-42-05](https://github.com/angular/components/assets/64118753/d91555a1-8e87-4332-9303-a31b187d3b3d)

Dynamically changes width is a good addition to select but for small width options like in my case other options at the dropdown should not truncate its not user friendly also decreases readability either.

**Scenerio #2**
I have populated drop down with checkbox along with labels and on selection i want to show total select options 
here is when no one is selected 
![Screenshot from 2024-04-25 15-42-55](https://github.com/angular/components/assets/64118753/64c47d1c-158f-47bc-844a-34f00e94dea3)
as you can see user is unable to see any option just checkboxes

here is when user selected some options:
![Screenshot from 2024-04-25 15-47-45](https://github.com/angular/components/assets/64118753/6fb24614-a6bc-40ae-82fd-334e7c840684)

**Comment by crisbeto** [comment]
You can set `[panelWidth]="null"` on the select to let the dropdown grow based on the options.
