### ISSUE TITLE
feat(MapMarkerAdvanced, MapOptions, MapTypeStyle): MapMarkerAdvanced requires mapId, but MapTypeStyle[] cannot be used with a mapId

### ISSUE THREAD

**Issue by jacob-amptech** [angular/components#28983]
### Feature Description

When attempting to implement a dark theme using a MapTypeStyle[] in MapOptions the styles do not apply and the following message is printed to the console:

> A Map's styles property cannot be set when a mapId is present. When a mapId is present, Map styles are controlled via the cloud console.

For websites that need to be able to control toggling the map between dark and light theme, while also being forced off of the deprecated MapMarker, this poses a significant issue.

### Use Case

The ability for a website to control the styling of google maps to conform to toggling between light and dark theme.

**Comment by crisbeto** [comment]
Closing the issue since it's outside of our control. Our components are wrappers around the Maps API which isn't owned by our team and is the one printing the deprecation warnings.
