### ISSUE TITLE
bug(MatFormField): Cannot change color of MatFormField TextArea with CSS

### ISSUE THREAD

**Issue by lkaupp** [angular/components#28998]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Is there any way to change the different styles of a textarea using CSS without SCSS, less theming? The guide to changing the colors is very rudimentary when it comes to CSS and after the refactoring to MDC, also the guides that may be found on the www are not usable anymore. 

Colors to change of interest:
font-color
background-color
border-color
caret-color
text-color
underline-color

### Reproduction

Found one style variable by accident. Maybe you can help me with the others.

https://stackblitz.com/edit/stackblitz-starters-f3lymt?file=src%2Fmain.ts

### Expected Behavior

Change the colors of MDC components just by CSS classes. A more detailed documentation about CSS properties would be nice.

### Actual Behavior

Search the web and find nothing about MDC refactoring, including no official documentation.

### Environment

 ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.6
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.7
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.6
@angular-devkit/build-angular   17.3.6
@angular-devkit/core            17.3.6
@angular-devkit/schematics      17.3.6
@angular/cli                    17.3.6
@schematics/angular             17.3.6
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.5

**Comment by amysorto** [comment]
A lot of these styles are set by CSS variables, we don't publically document them now but we are currently working on way for users to edit these variables across their apps to make this experience easier.

In the meantime, for the variables you are looking for are the following:
- `--mat-form-field-container-text-font`
- `--mdc-filled-text-field-container-color`
- no border color variable
- `--mdc-filled-text-field-caret-color`
- `--mdc-filled-text-field-input-text-color`
- `--mdc-filled-text-field-active-indicator-color`

Hope that helps!

**Comment by lkaupp** [comment]
The last do not set the underline color only the standard not selected color:
non-active:
![image](https://github.com/angular/components/assets/26430608/6f5c3972-19ae-496d-b7ce-9f310320bb9e)
active (which CSS class?):
![image](https://github.com/angular/components/assets/26430608/b2da2eab-af1e-48b0-9059-21d7c50afb44)

**Comment by amysorto** [comment]
That is `--mdc-filled-text-field-focus-active-indicator-color`

**Comment by amysorto** [comment]
Once we have a more supported way of overriding these tokens (currently being worked on!), it will be added to docs so hopefully this is a much smoother and easier process!!
