### ISSUE TITLE
bug(cdk-drag): scroll doesn't work if scroll container is inside cdkDropList element

### ISSUE THREAD

**Issue by chintankavathia** [angular/components#29007]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We can enable scrolling with cdk drag and drop by using `cdkScrollable` but it only works if scroll container is either `cdkDropList`  itself or any parent element.

There can be situations where you have wrapper element which is scrollable inside `cdkDropList` element. applying `cdkScrollable` to this wrapper doesn't work.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/2bsare?file=src%2Fexample%2Fcdk-drag-drop-custom-placeholder-example.html,src%2Fexample%2Fcdk-drag-drop-custom-placeholder-example.ts

### Expected Behavior

There should be a possible way to also allow children element to act as scrollable container.

### Actual Behavior

auto scroll doesn't work if scrollable container is child of `cdkDropList` 

### Environment

- Angular: 17.3
- CDK/Material: 17.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Closing since it's working as expected. The assumption is that any scrolling will happen either on the `cdkDropList` or a parent. It can be worked around by making the list scrollable.
