### ISSUE TITLE
bug(mat-button-icon): m3 mat-icon-button is not applying color

### ISSUE THREAD

**Issue by pedroestabruxelles** [angular/components#29013]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

With the introduction of material 3 theme the mat-icon-button is not applying the color (primary, accent, etc) all of them have the same color.

![image](https://github.com/angular/components/assets/46717433/2d3a2aa8-88aa-498f-acc7-c28667a0dd17)

I'm surprised nobody noticed yet about this, it's very visible on the public page as you can see above.

### Reproduction

Not needed

### Expected Behavior

should have the theme color applied based on the color input

### Actual Behavior

all types of color have the same dark color

### Environment

- Angular: 17.x.x
- CDK/Material: 17.x.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jdkultur** [comment]
I believe there is a new API for coloring in angular M3.
https://material.angular.io/guide/material-3#using-component-color-variants

You can also include the `color-variants-back-compat` in your theme to use the old coloring API, https://material.angular.io/guide/material-3#optional-add-backwards-compatibility-styles-for-color-variants

**Comment by amysorto** [comment]
@jdkultur thanks for providing the info!
@pedroestabruxelles the links above are the right ones to look at!

**Comment by niltor** [comment]
I’m using angular18 with material 3. And I had added `  @include mat.color-variants-backwards-compatibility($dark-theme);`

`mat-icon-button` still not applying color

**Comment by niltor** [comment]
@amysorto  Pls reopen this issue!

**Comment by niltor** [comment]
![image](https://github.com/angular/components/assets/8222201/b883b368-9647-4145-915f-820fa87482bc)

**Comment by shimonsalamon** [comment]
For a temporary fix i put the color directly on the icon

``` 
<button mat-icon-button color="accent">
    <mat-icon color="accent">edit</mat-icon>
 </button>

<button mat-icon-button color="warn">
    <mat-icon color="warn">delete</mat-icon>
</button>

```

![image](https://github.com/angular/components/assets/75227800/bdd5b875-09b8-4604-83eb-fd119307b30f)
