### ISSUE TITLE
bug(MatDatePicker/DateRangePicker): Date picker validation seems to be missing some cases. 

### ISSUE THREAD

**Issue by nfioavu** [angular/components#29057]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Date picker form control validation presents different behaviours depending on the wrong dates inputed from keyboard. Seems like the date picker only shows error for day values above 31, not taking into consideration the month.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-jh9zom?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts
Reproduction is based on the values inputted from keyboard.

### Expected Behavior

The expected behaviour would be that the user would be prompted with error message everytime the keyboard value is not a valid date. Therefore the following example would trigger an error message: 2/29/2023, 4/31/2024, 5/32/2024, whereas these would be valid: 2/29/2024, 30/4/2024, 5/31/2024. 

### Actual Behavior

The actual behaviour is that day values above 31 will throw an error, while day values below 31 and not valid (30 days months/ february) will automatically switch the date to the next date. Therefore '4/32/2033' will trigger and error, while '4/31/2033' will swtich into '5/1/2033'. Same applies for leap years, '2/29/2023' turns into '3/1/2023'.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
By default we use the browser's built in date parsing which has some limitations. There's more information in the docs: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings
