### ISSUE TITLE
mat-mdc-button : Button Custom background color and text color are overriding in angular material 15

### ISSUE THREAD

**Issue by fahdkhan4** [angular/components#29059]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I have migrated angular from ver 14 to 15, In angular ver 14 all things are working good, after migrating to angular material 15 buttons are not picking the custom text color and background color. 

**button theme:**
@use '../_variables' as vars;

@mixin theme() {
	.blue-button {
		background-color: vars.$primary-default;
		color: white;
	}
}

**this class is overriding the font-color of the button :**
mat-mdc-button:not(:disabled) {
    color: var(--mdc-text-button-label-text-color, inherit);
}

**this class is overriding my background color:**
.mdc-button {
    background: rgba(0, 0, 0, 0);
}

**html file implementation of button:**
<button
	mat-button
	class="blue-button">
	Test
</button>

<img width="293" alt="button-issue" src="https://github.com/angular/components/assets/103899098/d04ee315-735e-4b92-b829-a2e38a352198">

**Note:**
         I dont want to solve this issue using the !important keyword so is there any work-around to fix this issue.
### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

The buttons are not picking the custom styling eg blue color as a background and white font color.

### Actual Behavior

The buttons should pick the custom styling eg blue color as a background and white font color.

### Environment

- Angular: 15.2.10
- CDK/Material: 15.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by crisbeto** [comment]
Closing since we don't officially support overrides like this. You can work around it by setting the CSS variables instead.

**Comment by fahdkhan4** [comment]
@crisbeto I haven't override any thing I have created a mat-button and then gave this css(blue-button) class which I define in theme mixin.

@mixin theme() {
.blue-button {
              background-color: vars.$primary-default;
              color: white;
}

The problem I am facing is my custom css (background color and color ) is overriding by these two classes (mat-mdc-button:not(:disabled , .mdc-button  ) which i defined in the description.I am not facing this problem in angular ver 14 but facing in angular version 15.

By giving !important property to the properties of my custom (blue button) class I can see my color applying on the button but without that its not picking the color.

**Comment by crisbeto** [comment]
The example you posted is overriding the built in styles.

**Comment by fahdkhan4** [comment]
@crisbeto  So here in this attachment my custom CSS is with **yellow color highlighted** and with the **blue color highlighted** is the built in styles of mdc-mat-button, so from these built in classes added in angular ver 15 my custom class (blue-button) is not working.

<img width="293" alt="button-issue" src="https://github.com/angular/components/assets/103899098/77b14fea-e115-44cc-9783-88ac94d14423">
