### ISSUE TITLE
docs-bug(Theming Angular Material): table of contents misses h2 headers

### ISSUE THREAD

**Issue by AlexElin** [angular/components#29071]
### Documentation Feedback

A table of contents on the "Theming Angular Material" page misses the h2 headers from the text. This breaks the structure of the table of contents. The below screenshot demonstrates the case

![image](https://github.com/angular/components/assets/13061803/fafd5340-2730-4559-9374-2f55d4c71e72)

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by skilledDev96** [comment]
I see this is an issue on other doc guide pages as well.
Can I have a look into it? 

*Side Note*
How would I be able to test the rendering of the side-nav as well as the guides as when we run the dev-app it only shows the demos of the components? @AlexElin

**Comment by crisbeto** [comment]
Feel free to look into it. The docs site is at https://github.com/angular/material.angular.io. You just need to clone the repo, run `yarn` and then `ng serve`. You can ping me for a review once there's a PR.
