### ISSUE TITLE
Reactive Forms - Mat Select - doesn't trigger form or control as invalid after control has been touched, and validator.required is set to true

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/components#29092]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

With this code

```
   this.contractEngagementInfo.addControl('jobTitle',
      this.formBuilder.control(null, [Validators.required]));
```

  ```
<!-- select -->
        <mat-select
          id="jobTitle"
          placeholder="Select a job title"
          formControlName="jobTitle"
          required>
          <mat-option>-- None --</mat-option>
          @for (jobTitle of allowableOptions;
            track jobTitle) {
            <mat-option [value]="jobTitle">{{jobTitle}}</mat-option>
          }
        </mat-select>
```

Current bug behaviour is that:

If the control gets loaded with data that is not amongst the allowable options, it will display

'Select a job title' - i.e. the placeholder. 
If I touch the control and select None, the control (and form) will become invalid, saying the field is required - great!

**However**, if I touch the control and don't select None, or the other options, and unclick away from the contrl, I'd expect that since I have a validator.required validator on the cnotrl, that because I touched the control, it should ALSO say control (and form) are invalid, when I unclick away from it (just like what happens with a normal input field)

This currently doesn' happen, and means if the data loaded initially is wrong, a user can send back the same invalid data (since Angular never sees the form as invalid)

<img width="712" alt="Screenshot 2024-05-17 at 19 28 15" src="https://github.com/angular/angular/assets/39380005/2ed49934-4ad9-405c-85b6-46cd2f2f4e85">

### Please provide a link to a minimal reproduction of the bug

[Reproduction on Stackblitz](https://stackblitz.com/edit/stackblitz-starters-gs9gmh?file=src%2Fmain.ts)

### Please provide the exception or error you saw

```true
See above
```

**Comment by pkozlowski-opensource** [comment]
Could you please have a look at it from the MatSelect perspective? Feel free to open a form-related issue if there are limitations there.

**Comment by dreamstar-enterprises** [comment]
I think I'll open another issue. Am I missing something though. Surely the behaviour should be the same as a normal input field. Once it's touched, and if it is required, then after it has been touched, it should become invalid. Before it's touched, it's fine for it to be valid.

**Comment by crisbeto** [comment]
Closing since the repro doesn't compile. Also here are the docs for customizing when error messages show up: https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown
