### ISSUE TITLE
bug(cdkDrag): cdkDrag is not working properly after element resized

### ISSUE THREAD

**Issue by ourdark** [angular/components#29113]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Resize an element bigger and then shrink to small, then drag the element to move, element teleport to unexpected position.
It is not happens for every time, but time to time.

### Reproduction

StackBlitz link: [click here](https://stackblitz.com/edit/stackblitz-starters-apuhzh?file=src%2Ftable-cdk.component.ts,src%2Ftable-cdk.component.css,src%2Fresize.directives.ts)
Steps to reproduce:
1. Resize div to a big size
2. Then resize it to small one
3. Drag the div

Repeat try several times.

### Expected Behavior

The mouse position(when drag) and target is associate with the current div position.

### Actual Behavior

Target div teleport to another position which is not associate(under) mouse position.

### Environment

- Angular:12.2.12 | 18.0.1
- CDK/Material:12.2.12 | 18.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It's because you're setting the `transform` which is also what the CDK uses to position itself. You can use the `CdkDrag.setFreeDragPosition` method to notify it of the new position.
