### ISSUE TITLE
bug(THEME): Components directive "color" not working with custom theme

### ISSUE THREAD

**Issue by IancovskiLimber** [angular/components#29128]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

Hello!

I'm trying to define a custom theme for a new project using Angular 18 following the [theming guide](https://material.angular.io/guide/theming). At first, I tried to select the custom theme option when I added the Angular Material to the project, so it created a generic theme using azure and blue palettes. When I insert a material button into the HTML, it is rendered with the primary color, but if I try to change its color to "accent" or "warn" with the color directive, nothing happens; it stays with the primary color.

### Reproduction

I tried to create a project on StackBlitz but an error occurs when I add Angular Material...

Steps to reproduce:
1. Create a new project using @angular/cli version 18 (for the style question, select "scss")
2. Add @angular/material to the project (for the theme question, select "custom", it will create a generic theme using azure and blue palletes)
3. Replace the content of app.component.html with a mat-flat-button using the color directive, as follows:
`<button mat-flat-button color="primary">Button</button>`
4. Run the project (the button will appear with an azure color)
5. Change the button color directive to "accent" or "warn"
6. Reload the project (the button color will not change)

### Expected Behavior

The color of the button must change when the color directive is changed.

### Actual Behavior

The color of the button don't change despite the color directive.

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
You need to include the `mat.color-variants-backwards-compatibility($theme)` mixin if you want support for the `color` attribute in M3.

**Comment by IancovskiLimber** [comment]
Thank you for your answer! This works, but I don't get one thing... What's the right way to change the button color between the theme colors in M3, without backwards compatibility?

**Comment by crisbeto** [comment]
The pre-built themes include the backwards compatibility styles: https://github.com/angular/components/blob/main/src/material/core/theming/prebuilt/rose-red.scss#L25. This is the intended way to consume it, because as far as I understand, M3 doesn't have the same concept for colors as in M2. We provide the mixin as way to avoid breaking existing clients.
