### ISSUE TITLE
feat(Buttons): Buttons & FABs with support for Icon + label

### ISSUE THREAD

**Issue by neo-xy** [angular/components#29130]
### Feature Description

At the moment Buttons and Fabs in documentaion are adjust for containing eaither a label or an icon,
are there any plans to extend api  so icon + label in a Buttons  and FABs can be easily aplied?
As now that can not be accomplished without adjusting and playing around with the css ;

Ex. of Fab with icon and label that destroys UI:

`    <button mat-fab (click)="drawer.toggle()">
        <span class="material-symbols-rounded" >add</span>
        <span i18n="@@sales">Sales</span>
    </button>`

**Comment by crisbeto** [comment]
There's an extended version of the FAB that supports both text and an icon. Here's an example: https://github.com/angular/components/blob/main/src/dev-app/button/button-demo.html#L15

Leaving the bug open so we can update the docs.

**Comment by crisbeto** [comment]
Button support both labels and icons already, which I realize we don't have any examples for. Here are some more examples https://github.com/angular/components/blob/main/src/dev-app/button/button-demo.html#L166-L174

**Comment by neo-xy** [comment]
guessingthe UI is of for me cause I'm using directly:
  <span class="material-symbols-rounded">home</span>
  instead of <mat-icon> 
  So now when I have You here:) : 
  Do you guys see a lot of value of sticking with <mat-icon> instead of   <span class="material-symbols-rounded"> - as I found the second one more easy to work with and customize

**Comment by crisbeto** [comment]
I'm not sure I understand the question, but you can see what the example looks like at https://ng-comp-devapp.web.app/button

**Comment by neo-xy** [comment]
code part of previews message was not visible :) that's why it was unclear (corrected now) 
but ok , ty (Y)
