### ISSUE TITLE
feat(dialog): input?

### ISSUE THREAD

**Issue by spock123** [angular/components#29134]
### Feature Description

This maybe be a dumb request, feel free to ridicule me - I don't know if this is even technically possible, but here goes;

Would it be possible to introduce an input() signal property to material dialog components, just like we can with normal components? 

### Use Case

Currently when opening a dialog, there is no way to feed it changing data directly from the calling code.
The only way is to make the dialog a "smart component" and import data streams itself. This is often redundant and creates confusing code. 

As it is now, the dialog is "stuck" with the initial data. Any other data, the dialog needs to import and stream itself.

A solution where an input() property could supply the dialog component with changing data, would be awesome. 
I am ,however, quite suspicious that this might not even be technically possible. Just wanted a confimation here :) 

Thanks

**Comment by crisbeto** [comment]
I think this is the same as https://github.com/angular/components/issues/28791.

**Comment by spock123** [comment]
@crisbeto  he, you're right, sorry.
