### ISSUE TITLE
bug(icon-button): The backwards compatability mixin for color variants is not affecting icon buttons

### ISSUE THREAD

**Issue by cuzo989874** [angular/components#29146]
### Documentation Feedback

In the previous version (Angular/Material 17), the color of the mat-icon-button could be customized. However, I am currently unable to access the code or obtain the correct demo version, even though the parameter still exists on the [API page](https://material.angular.io/components/button/api#MatIconButton).

<img width="857" alt="image" src="https://github.com/angular/components/assets/34397911/08f75683-9966-4843-b58b-d1972ddf7ea5">

### Affected documentation page

https://material.angular.io/components/button/overview#button-overview

**Comment by amysorto** [comment]
Thanks for pointing this out! In M3, you need to use a backwards compatability mixin to get that same code to work. See our [docs](https://material.angular.io/guide/material-2-theming#optional-add-backwards-compatibility-styles-for-color-variants) for how to use it. Let me know if that solves this issue for you!

I'll update this issue to track removing the color inputs for the component specific documentation.

**Comment by cuzo989874** [comment]
> Thanks for pointing this out! In M3, you need to use a backwards compatability mixin to get that same code to work. See our [docs](https://material.angular.io/guide/material-2-theming#optional-add-backwards-compatibility-styles-for-color-variants) for how to use it. Let me know if that solves this issue for you!
> 
> I'll update this issue to track removing the color inputs for the component specific documentation.

I understand that we should use the backwards compatibility mixin for setting the theme. However, the issue is that the `mat-icon-button` appears to be an exception; its color cannot be set. You can identify this problem by looking through the [docs](https://material.angular.io/components/button/overview#button-overview), specifically in the `icon` section.

**Comment by banut1** [comment]
Check this: https://github.com/angular/components/issues/29151.

Starting from that answer, here's what I did and works well:

For a primary icon button, I defined:

```
 .mat-mdc-icon-button.primary:not(:disabled) {
  @include mat.icon-color($theme, $color-variant: primary);
  @include mat.icon-button-color($theme);
}
```

For a warn one, I defined a whole warn theme and similarly to the above, a class .warn. It works well and does not use the m2 color attributes at all, neither the backwards compatibility mixin. 

Usage:
`<button mat-icon-button **class="primary"**>...</button>`

Hope it helps!

**Comment by amysorto** [comment]
@cuzo989874 Thanks for pointing out that the icon-button variant is missing. I took a closer look and yes that example does have the backwards compatability mixin but it isn't affecting icon buttons. I'll change the title for this issue accordingly. 

In the meantime, you can add custom styles for your icon buttons if necessary or do what @banut1 suggested. The CSS variable `--mat-icon-color` is how you can change the color. For example if you want to change the warn icon buttons you can do the following:
```
.mdc-icon-button.mat-warn {
  --mat-icon-color: $your-color;
}
```
Note: You can also directly access the color roles from the theme itself with [`mat.get-theme-color`](https://material.angular.io/guide/theming-your-components#reading-color-roles). So in the example above you can do `--mat-icon-color: mat.get-theme-color($your-theme, $error)`;

@midthun I agree, we are updating our docs for the different components page to make this more clear. Thanks!

**Comment by cuzo989874** [comment]
Here is my temporary solution, if anyone have same situation, you can follow this:

```scss
:root {
    .mat-primary {
        --mdc-icon-button-icon-color: #{variables.$primary-color};
        --mat-icon-button-state-layer-color: #{map.get(palette.$primary, 70)};
    }
    .mat-accent {
        --mdc-icon-button-icon-color: #{variables.$accent-color};
        --mat-icon-button-state-layer-color: #{map.get(palette.$tertiary, 70)};
    }
    .mat-warn {
        --mdc-icon-button-icon-color: #{variables.$error-color};
        --mat-icon-button-state-layer-color: #{map.get(map.get(palette.$primary, error), 70)};
    }
}
```

**Comment by crisbeto** [comment]
This was fixed by https://github.com/angular/components/pull/29433.
