### ISSUE TITLE
bug(cdk-dialog): restoreFocus doesn't work as expected

### ISSUE THREAD

**Issue by chintankavathia** [angular/components#29148]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`restoreFocus` allows to restore focus back to the element from where dialog was opened.
However it seems to be broken when user uses mouse click to dismiss the dialog.

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/2ejqtm?file=src%2Fexample%2Fcdk-dialog-overview-example.ts
Steps to reproduce:
1.  Use keyboard to focus on `Pick one` button 
2. Open the dialog by hitting `Return` key
3. Now use mouse and click on `cancel` button to close the dialog
4. Notice the focus is not restored back to `Pick one` button
 

### Expected Behavior

focus should be restored to the original element.

### Actual Behavior

focus is not restored back to the original element.

### Environment

- Angular: 17
- CDK/Material: 18
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
Focus does get restored, but as of some recent version (not sure which one) Chrome doesn't render the focus outline for mouse interactions. Here's the same example, but without relying on the browser's styles: https://stackblitz.com/edit/2ejqtm-8inbgy?file=src%2Fexample%2Fcdk-dialog-overview-example.ts
