### ISSUE TITLE
bug(matRipple): Ripple effect sometimes persists when used with cdkDrag

### ISSUE THREAD

**Issue by gkrzysztofbury** [angular/components#29159]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When setting up cdkDrag with multiple cdkDropList components, initiating a drag very quickly can cause the ripple effect to remain frozen on the component.

### Reproduction

- **Video:** [YouTube](https://youtu.be/TuqymtoH_MM)
- **StackBlitz:** [Example](https://stackblitz.com/edit/stackblitz-starters-xg3pcm?file=src%2Ftabs_container.ts)

### Expected Behavior

After the drag ends, the ripple effect should be removed from the button.

### Actual Behavior

The ripple effect remains on the button indefinitely.

**Cause:**

When the drag starts, the original button is removed from the DOM, and a placeholder is created in its place. Immediately after creation, the ripple state is set to `RippleState.FADING_IN` ([source](https://github.com/angular/components/blob/main/src/material/core/ripple/ripple-renderer.ts#L184)). However, the actual `FADING_IN` transition does not occur because the button is removed from the DOM.

**Proposed Solution:**

Modify the code at line 184 to set the state to `RippleState.VISIBLE`, and then set it to `RippleState.FADING_IN` on the `transitionstart` event. This way, the ripple will be removed here:
[Remove Ripple](https://github.com/angular/components/blob/main/src/material/core/ripple/ripple-renderer.ts#L414)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by gkrzysztofbury** [comment]
This fix doesn't work, the problem is that `mat-ripple-element` stays inside the original element, not placeholder/preview

![Screenshot](https://github.com/angular/components/assets/171156483/bdaf0892-14e3-40d8-abc4-3ff1cd9795c8)

**Comment by crisbeto** [comment]
I just tried it and couldn't reproduce this issue with the code at head:

https://github.com/angular/components/assets/4450522/c5c266c4-579d-41e3-a26c-29d77b23ec86

**Comment by gkrzysztofbury** [comment]
You have to:
1. have a setup with 2 connected cdkDragLists
2. click & drag very fast, like in single move, so the drag starts before ripple animation starts playing

**Comment by crisbeto** [comment]
I tried it again, but couldn't reproduce it. I also tried slowing down the animation to see if that makes a difference, but it didn't. Can you try it on this link? https://ng-dev-previews-comp--pr-angular-components-29197-dev-p8hzqfu4.web.app/drag-drop 

It's our demo app with your repro pasted in.

**Comment by gkrzysztofbury** [comment]
[Screen recording 2024-06-05 12.54.30.webm](https://github.com/angular/components/assets/171156483/9353a2b7-733e-4520-a083-fe25f769d8ee)

Here you go, it takes some practice to do this quick move, but once you get it is easy to reproduce

**Comment by gkrzysztofbury** [comment]
I can do this on ChromeOS and MacOS (Chrome & Safari)
