### ISSUE TITLE
feat(CDK Progress bar & spinner): Progress bar & spinner built-in options for displaying percentages and striped designs

### ISSUE THREAD

**Issue by alihamzatanveer565** [angular/components#29150]
### Feature Description

similar to other UI frameworks & Libraries, the progress bar & spinner should include built-in options for displaying percentages and striped designs.

Example from Vuetify:

![image](https://github.com/angular/components/assets/91602038/36a5a709-6e1f-4f3b-bbaf-815a958382ff)

![image](https://github.com/angular/components/assets/91602038/90dcce64-743e-4195-9c14-862e91d5c99c)

![image](https://github.com/angular/components/assets/91602038/d640d8fd-bc02-4449-8bfd-f2a8ff9bc348)

Example from PrimeNg:

![image](https://github.com/angular/components/assets/91602038/21d10064-634e-417f-810d-6a7e591f5e79)

### Use Case

I'm implementing file upload functionality and need to show a progress bar with percentages. But there is no built-in option therefore making a custom progress bar. So in the future, these should be included.

**Comment by crisbeto** [comment]
This isn't supported in the Material Design spec so that's why we don't support it either.
