### ISSUE TITLE
bug(M3-Buttons): missing color variants

### ISSUE THREAD

**Issue by banut1** [angular/components#29151]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Missing color-variant error for mat-fab:
![image](https://github.com/angular/components/assets/97966138/1916efdf-1dbf-4637-a077-fc57c0af2e89)

Usage: 
```
.danger {
  @include mat.fab-color($theme, $color-variant: error);
}
```

Error on any kind of color-variant for mat-icon-button:
![image](https://github.com/angular/components/assets/97966138/030b071e-7f1e-45b4-a3a5-c52c29acc42d)

Usage:
```
.danger {
  @include mat.icon-button-color($theme, $color-variant: primary);
}
```

### Reproduction

https://stackblitz.com/edit/67r7jk?file=src%2Ftheme.scss

### Expected Behavior

all color variants work for all components

### Actual Behavior

different errors in different use cases

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The color variants are defined by the Material spec which doesn't include an `error` variant. The way to do it would be to define a theme with your error colors and pass it to `mat.button-theme` like:

```
button.error-variant {
  @include mat.button-theme($your-error-theme);
}
```

**Comment by banut1** [comment]
I have generated the color palette with ng generate @angular/material:m3-theme, and it has generated an error palette alongside with primary, tertiary, secondary, neutral. I don't have an entire theme for the error colors, just that palette.

According to the docs, it seems a valid way to use the color variants:
https://material.angular.io/guide/theming#using-component-color-variants

For example, this works fine:
.danger {
  @include mat.icon-color($theme, $color-variant: error);
}

Can this be achieved for icon buttons and fabs without defining a whole error theme and just using the error colors from $theme?
