### ISSUE TITLE
feat(style): The sys variables are not fully defined, and Idea cannot automatically complete them.

### ISSUE THREAD

**Issue by chaosicu** [angular/components#29155]
### Feature Description

![截屏2024-05-31 11 52 11](https://github.com/angular/components/assets/66357978/9b546b91-eccc-45d1-bcd4-b51587049a80)

**Comment by crisbeto** [comment]
The variables are generated dynamically so that's probably why it can't find them in the source code. Closing since we can't do much about how Idea works.
