### ISSUE TITLE
bug(M3 mat-card): Elevated card uses the wrong surface color

### ISSUE THREAD

**Issue by admin-pilotds** [angular/components#29163]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

MDC M3 specification (https://m3.material.io/components/cards/specs) dictates that enabled elevated card container color should be **md.sys.color.surface-container-low**

However, in @material/tokens/v0_161/_md-comp-elevated-card.scss we have

...
'container-color': map.get($deps, 'md-sys-color', 'surface'),
...

Should be changed to

'container-color': map.get($deps, 'md-sys-color', 'surface-container-low'),

### Reproduction

No need for reproduction -- this is clearly not according to specification.

### Expected Behavior

An elevated card with 'surface-container-low' background

### Actual Behavior

An elevated card with 'surface' background

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.1

**Comment by andrewseguin** [comment]
The tokens are outside of our scope and would need to be fixed in the dependency https://github.com/material-components/material-components-web

I suggest filing the issue there

**Comment by andrewseguin** [comment]
Re-opening because our repository now owns its own token definitions rather than importing them from another package
