### ISSUE TITLE
docs-bug(Card): Testing with MatCardHarness Example

### ISSUE THREAD

**Issue by lukaszprus** [angular/components#29167]
### Documentation Feedback

What's the point of `?? []` in https://github.com/angular/components/blob/04d3b63de2fb843beb55836e39e930c3342d26f1/src/components-examples/material/card/card-harness/card-harness-example.spec.ts#L34 ?

Seems like it can be removed

### Affected documentation page

https://material.angular.io/components/card/examples#card-harness

**Comment by crisbeto** [comment]
Agreed, I don't think it's necessary.

**Comment by MichelleRetroRabbit** [comment]
If no one is already working on it, I would like to do this change.
