### ISSUE TITLE
bug(mat-tab-nav-bar): Empty space on mat-tab-nav-ba when removing the last tab

### ISSUE THREAD

**Issue by gkrzysztofbury** [angular/components#29162]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When removing a tab from the mat-tab-nav-bar that uses pagination buttons, the remaining tabs do not scroll to fill the available space, leaving an empty gap in the tab bar.

### Reproduction

- **Video:** [YouTube](https://youtu.be/YdQwlk09xUE)
- **StackBlitz:** [Example](https://stackblitz.com/edit/stackblitz-starters-jduyqj?file=src%2Ftabs_container.ng.html)

### Expected Behavior

After a tab is removed, the list of tabs should automatically scroll to fill the entire header, ensuring no empty space is left.

### Actual Behavior

When a tab is removed, an empty space remains on the tab bar.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
The nav bar is meant to be used with nav links. You can get the proper styling by setting the `mat-tab-link` on the elements. See https://stackblitz.com/edit/stackblitz-starters-7rcjyb?file=src%2Ftabs_container.ng.html
