### ISSUE TITLE
problem with mat-date-range-picker 

### ISSUE THREAD

**Issue by posaomstart** [angular/components#29177]
I have multilanguage app and I'm changing date locale based on selected country.
I wan't to change only date popup header label and keep my original formating of the selected dates no matter what the locale is.
for example:
I want my date to look like 15.04.2024. no matter the locale and formatting of calendar header labell should staj APR 2024.
for example:
APR 2024 should stay formatted like that and change depending on the locale.
Problem is when I override format function  APR 2024 becomes  01.04.2024. in calendar header label.

Any help would be appreciated.

CODE 

@Component({
  selector: "datepicker-header",
  styles: `
    .example-header {
      display: flex;
      align-items: center;
      padding: 0.5em;
    }

    .example-header-label {
      flex: 1;
      height: 1em;
      font-weight: 500;
      text-align: center;
    }
  `,
  template: `
    <div class="example-header">
      
      <button mat-icon-button (click)="previousClicked('month')">
        <mat-icon>keyboard_arrow_left</mat-icon>
      </button>
      <span class="example-header-label">{{ periodLabel }}</span>
      <button mat-icon-button (click)="nextClicked('month')">
        <mat-icon>keyboard_arrow_right</mat-icon>
      </button>
      

    </div>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [MatButtonModule, MatIconModule, MatDatepickerModule],
})
---------------------------------------------------------------------
export class DatepickerHeader<D>  implements OnDestroy {
  private _destroyed = new Subject<void>();

  constructor(
    private _calendar: MatCalendar<D>,
    private _dateAdapter: DateAdapter<D>,
    @Inject(MAT_DATE_FORMATS) private _dateFormats: MatDateFormats,
    cdr: ChangeDetectorRef
  ) {
    _calendar.stateChanges.pipe(takeUntil(this._destroyed)).subscribe(() => cdr.markForCheck());
  }

  ngOnDestroy() {
    this._destroyed.next();
    this._destroyed.complete();
  }

  get periodLabel() {
    return this._dateAdapter
    .format(this._calendar.activeDate, this._dateFormats.display.monthYearLabel)
    .toUpperCase();   // !!!!!!!!!!!!!!!!!!!!!! here I formatt LABEL wich is overriden by format function below
    }
    ....
    --------------------------------------------------------------------------------------------
}

export class CustomDateAdapter extends NativeDateAdapter {

    override getFirstDayOfWeek(): number {
        return 1;
    }
    override format(date: Date, displayFormat: any): string {
      return moment(date).format("DD.MM.YYYY.");  // !!!!!!!!!!!!!!! function that I override, changes both header label and range select output formatting
   }
}

--------------------

component.html
      <mat-date-range-input  [rangePicker]="picker" style="margin-bottom: 8px;">
                    <input matStartDate  readonly 
                
                    (dateChange)="dateMomentConverter($event.value );"
                     >
                    <input matEndDate   readonly 
                    (dateChange)="dateMomentConverter($event.value);"
                    >
                  </mat-date-range-input>
                  <div class="popupImgDivDate">
                    <mat-datepicker-toggle class="popupImg"  matIconSuffix [for]="picker" ></mat-datepicker-toggle>
                  </div>
                  <mat-date-range-picker (closed)="onDatepickerClose(key.colName)" #picker [calendarHeaderComponent]="datepickerHeaderMerge"></mat-date-range-picker>

---------------

and under providers inside app.module I have
  providers: [MatDatepickerModule, MatNativeDateModule,
    { provide: DateAdapter, useClass: CustomDateAdapter },
    }

**Comment by amysorto** [comment]
I would take a look at our [internationalization docs](https://material.angular.io/components/datepicker/overview#internationalization). There's some information there about overriding local locales if you want to keep your formatting consistent.
