### ISSUE TITLE
MatDialog not respecting positioning always placed as the last element of the DOM (v 17.2.1)

### ISSUE THREAD

**Issue by lpedrop** [angular/components#29179]
Although I'm using the options
`{ position: { right: '10px', top: '10px' }`

to align it at top and right, with 10px margin, it´s always being placed at the bottom left corner of the page.
In my case, if I have a drawer at left and open, it will be placed underneath that drawer. 
Also, for example, if I have a MatTable and want to display the dialog on click of a row item, it´s scrolling down all the elements of the table until reaching the bottom of the table, and then displays the dialog as one regular HTML element after the table.

![image](https://github.com/angular/material.angular.io/assets/583176/3cec844f-7c76-4e13-a064-f0e63043cdd5)

![image](https://github.com/angular/material.angular.io/assets/583176/b02de804-b75f-476d-9b10-45983e2abcde)
![image](https://github.com/angular/material.angular.io/assets/583176/e023cb10-4e16-49dc-918b-439e0fac530a)

![image](https://github.com/angular/material.angular.io/assets/583176/ee73b5df-69d2-40a9-adf4-a55a95490779)

**Comment by mmalerba** [comment]
Cannot reproduce: https://stackblitz.com/edit/4t2zqg?file=src%2Fexample%2Fdialog-data-example.ts
