### ISSUE TITLE
bug(COMPONENT): Misnamed property for snackbar theme

### ISSUE THREAD

**Issue by steveareeno** [angular/components#29172]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the node modules/@angular/material folder, the file _index.scss has a forward rule for the material UI snackbar with a misnamed property:

`@forward './snack-bar/snack-bar-theme' as snack-bar-* show snack-bar-theme, snack-bar-color,
  snack-bar-typography, snack-bar-density, snack-bar-base, bar-overrides;`

The last property, "bar-overrides", should probably be "snackbar-overrides" like all the other properties

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Open the file in the @angular/material node modules folder
2. Find the forward rule for snackbar

### Expected Behavior

Expect the property to be named snackbar-bar-overrides like the other properties.

### Actual Behavior

The property is named "bar-overrides"

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by andrewseguin** [comment]
Thanks, this will be fixed in #29180 29180
