### ISSUE TITLE
bug(CORE): mat-elevation-z classes not working anymore

### ISSUE THREAD

**Issue by Akxe** [angular/components#29170]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Any version of Angular 17 and bellow

### Description

The shadow classes are removed. Maybe they can be enabled, but it is hard to tell what should be enabled.

With the migration to the new Angular Material M3, many things changed, but they are somewhat poorly telegraphed. I tried to look through Angular's blog, Angular's update guide, and the whole of Angular Material's docs, but there is nothing about how to style components the new way. More important, all the demos on the pages use the "old" `colour` attribute to change colour.

### Reproduction

StackBlitz link: https://material.angular.io/guide/elevation
Steps to reproduce:
1. Click "toggle elevation"
2. Observe class changing but no styles applying

### Expected Behavior

It is okay that it changed. But the page should either not exist or, better, guide users to new standards on how to separate parts of UI.

### Actual Behavior

No shadow at all

### Environment

- Angular: 18+
- CDK/Material: 18+
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by nunoarruda** [comment]
Same issue here. It does not even work in the docs: https://material.angular.io/guide/elevation

Angular Team: Were `mat-elevation-z#` classes removed to follow M3 standards? 👇
<img width="1014" alt="Screenshot 2024-06-03 at 14 15 15" src="https://github.com/angular/components/assets/1189149/37eb7d4c-37d9-48b4-bf29-4039cfe7f82e">
Source: https://m3.material.io/styles/elevation/overview
