### ISSUE TITLE
"Marker Cluster" not functioning correctly with "Advanced Marker"

### ISSUE THREAD

**Issue by jaykishanutwani** [angular/components#29187]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

**Issue**

1. "Marker Cluster" not functioning correctly with "Advanced Marker" 
2.  `mapMouseout `& `mapMouseover `events not working with `map-advanced-marker`

**Link to runnable example**
[https://codesandbox.io/p/devbox/shy-platform-2h2y6y?file=%2Fsrc%2Fapp%2Fservice%2Fgoogle-maps.service.ts%3A19%2C16-19%2C28](https://codesandbox.io/p/devbox/shy-platform-2h2y6y?file=%2Fsrc%2Fapp%2Fservice%2Fgoogle-maps.service.ts%3A19%2C16-19%2C28)

**Note**

Already discussed this [issue ](https://github.com/angular/components/pull/28525#issuecomment-1971451652)here.
![image](https://github.com/angular/components/assets/171682430/995f01fe-8b42-4246-9ec1-14fb4c62a210)

### Reproduction

https://codesandbox.io/p/devbox/shy-platform-2h2y6y?file=%2Fsrc%2Fapp%2Fservice%2Fgoogle-maps.service.ts%3A19%2C16-19%2C28

### Expected Behavior

Marker Cluster should be visible without any error.
![image](https://github.com/angular/components/assets/171682430/bbd2289e-ac64-4f15-88df-33809994c9ef)

### Actual Behavior

Marker Cluster not visible with Advanced marker
![image](https://github.com/angular/components/assets/171682430/765d2d03-b7ec-4456-85e2-7ef3e15b29e1)

### Environment

- Angular:^17.3.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
The current clusterer doesn't support advanced markers. You can follow https://github.com/angular/components/issues/23695 for the new clusterer.
