### ISSUE TITLE
timezone offset-picker

### ISSUE THREAD

**Issue by LoganDupont** [angular/components#2919]
#### Bug, feature request, or proposal:
Do the Angular Material Team have any thoughts about creating a timezone offset-picker?

#### What is the expected behavior?
This behavior should let the user choose on what timezone he creates a Date object.

#### What is the current behavior?
Right now we have only a date-picker, but a time and offset-picker should also be nice to have. 

#### Is there anything else we should know?
In our project we want users to let have the possibility to choose when surveys can end on a specific date and time in random country. That's why we need an offset-picker for our users.

**Comment by mmalerba** [comment]
I'm currently working on datepicker, I do plan to allow specifying a custom timezone offset. (you can see the design doc here: https://docs.google.com/document/d/1RwPFESCbSSLMSDqxWo7jg4UUpGJTrXX6p5wYlb9pmNc/preview)

**Comment by AndrewEckart** [comment]
Any update on plans for a timezone selector?

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.

**Comment by airasyaqub** [comment]
Any update on this feature @mmalerba . I have also raised this in issue section as feature because we need to use user given time zone rather system timezone. Your comment will be appreciated.

**Comment by annieyw** [comment]
The Material Design spec for datepicker (https://material.io/components/date-pickers) does not include time zones, so this is out of scope for Angular Material.
