### ISSUE TITLE
bug(website): 17.3.6 Material version is showing Material 3 experimental styling instead of Material 2 styling

### ISSUE THREAD

**Issue by szabogerArgon** [angular/components#29196]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.1

### Description

Ever since experimental support for M.3 was added to Angular Material 17, the website now shows the components using the M.3 styling instead of M.2 for the latest 17 version:
![image](https://github.com/angular/components/assets/60918069/5b7ad315-02f3-4a15-8b79-f651ef0fce74)

Default appearance when used in a project:
![image](https://github.com/angular/components/assets/60918069/5406f6bb-2a08-405f-a6f2-4117212f5ac0)

The official documentation shouldn't show experimental styling and components. Currently, Angular 17 is the latest LTS version, and M.2 is the default appearance when used in a project, M.3 was still experimental in Angular Material 17:
https://v17.material.angular.io/guide/material-3

This behaviour causes a lot of confusion, since our customers/UX team see the M.3 styling in the documentation for verson 17, even though M.2 is the "stable" and default styling.

### Reproduction

https://v17.material.angular.io/components/slide-toggle/overview

### Expected Behavior

https://v17.material.angular.io/ should show M.2 styling.

### Actual Behavior

https://v17.material.angular.io/ is showing M.3 styling.

### Environment

- Angular 17.3.6:
- CDK/Material 17.3.6:
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by json-derulo** [comment]
Looks like this is a duplicate of #28787

**Comment by szabogerArgon** [comment]
> Looks like this is a duplicate of #28787

Thanks for noticing, closed as a duplicate.
