### ISSUE TITLE
Upgrade to 18 is causing compilation errors with Material theme definition functions.

### ISSUE THREAD

**Issue by rkchavali** [angular/components#29190]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16 & 17

### Description

Upgrade from 16 to 17. Existing Material custom theme works fine. Then upgrade from 17 to 18 - compilation error as follows: 

/src/assets/v4/becn-theme.scss?ngGlobalStyle - **Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):**
**HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined function.**
   ╷
8  │   $my-custom-typography-config: **mat.define-typography-config**($headline-1: mat.define-typography-level(88px, 96px, 400, $letter-spacing: 1.5px),  
   │ ┌───────────────────────────────^

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Custom theme definition should be complied without errors.

### Actual Behavior

Compilation error on Material Theme definition function.

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.1
- Browser(s): Chrome
- Windows 10 Enterprise

**Comment by T4toh** [comment]
Same error here, I think that themes before m3 are not compatible with the new scheme. I made a crappy configurable theme that don't work anymore. I'm reverting to 17 until I have time to remake it with the new structure.

**Comment by crisbeto** [comment]
All the M2 APIs are still supported, they were just renamed to start with `m2-`. How did you update? If you go through `ng update`, the CLI will make all the updates for you. If not, you can see all the renamed APIs here: https://github.com/angular/components/blob/main/CHANGELOG.md#material-1

**Comment by prasadamservices** [comment]
I did update using ng update.

**Comment by crisbeto** [comment]
Hmm then it's possible that you're hitting the same issue as https://github.com/angular/components/issues/29147

**Comment by ct-dixit** [comment]
All the M2 APIs are still supported, they were just renamed to start with m2-. How did you update? If you go through
 ng update @angular-cli @angular-core, the CLI will make all the updates for you.
 
 $my-custom-typography-config: mat.m2-define-typography-config($headline-1: mat.m2-define-typography-level(88px, 96px, 400, $letter-spacing: 1.5px),
 
![Screenshot 2024-06-05 173456](https://github.com/angular/components/assets/106728438/c7a496d6-1321-457b-81f9-c109c72135a0)

 
[https://github.com/angular/components/blob/main/CHANGELOG.md#material-1]

**Comment by T4toh** [comment]
> All the M2 APIs are still supported, they were just renamed to start with m2-. How did you update? If you go through ng update @angular-cli @angular-core, the CLI will make all the updates for you.
> 
> $my-custom-typography-config: mat.m2-define-typography-config($headline-1: mat.m2-define-typography-level(88px, 96px, 400, $letter-spacing: 1.5px),
> 
> ![Screenshot 2024-06-05 173456](https://private-user-images.githubusercontent.com/106728438/336828329-c7a496d6-1321-457b-81f9-c109c72135a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODk1NDgsIm5iZiI6MTcxNzU4OTI0OCwicGF0aCI6Ii8xMDY3Mjg0MzgvMzM2ODI4MzI5LWM3YTQ5NmQ2LTEzMjEtNDU3Yi04MWY5LWMxMDljNzIxMzVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMjA3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjNlNjQ0OGY4NzM5MWQyNTRhM2Q5ODc3ZDBkNmVjNGVmNzQ4MDE3MWY2YWY2ZWNkNzRmNGFmZTk1ZDRkOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i4UFjIlW3VhxiYBu0ifmplgByGFTQTtaB4uIocayuaQ)
> 
> [Angular 18 change log](https://github.com/angular/components/releases/tag/18.0.0)

I upgraded through the CLI with the same results as OP.

`
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 18.0.2 to perform the update.
✔ Packages successfully installed.
Using package manager: yarn
Collecting installed dependencies...
Found 45 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-eslint/schematics" has an incompatible peer dependency to "@angular/cli" (requires ">= 17.0.0 < 18.0.0", would install "18.0.2").
    Updating package.json with dependency @angular-devkit/build-angular @ "18.0.2" (was "17.3.8")...
    Updating package.json with dependency @angular/cli @ "18.0.2" (was "17.3.8")...
    Updating package.json with dependency @angular/compiler-cli @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/animations @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/common @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/compiler @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/core @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/forms @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/platform-browser @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/router @ "18.0.1" (was "17.3.10")...
    Updating package.json with dependency @angular/service-worker @ "18.0.1" (was "17.3.10")...
UPDATE package.json (2250 bytes)
✔ Packages successfully installed.
** Optional migrations of package '@angular/cli' **

This package has 1 optional migration that can be executed.
Optional migrations may be skipped and executed after the update process, if preferred.

Select the migrations that you'd like to run

** Executing migrations of package '@angular/core' **

> Updates two-way bindings that have an invalid expression to use the longform expression instead.
  Migration completed (No changes made).

> Replace deprecated HTTP related modules with provider functions.
UPDATE src/app/auxiliares/http.service.ts (6924 bytes)
UPDATE src/app/auxiliares/auxiliares.module.ts (1708 bytes)
  Migration completed (2 files modified).
`

Here is the log after the update, as you can see the ng update didn't touch the styles file.

**Comment by prasadamservices** [comment]
> All the M2 APIs are still supported, they were just renamed to start with m2-. How did you update? If you go through ng update @angular-cli @angular-core, the CLI will make all the updates for you.
> 
> $my-custom-typography-config: mat.m2-define-typography-config($headline-1: mat.m2-define-typography-level(88px, 96px, 400, $letter-spacing: 1.5px),
> 
> ![Screenshot 2024-06-05 173456](https://private-user-images.githubusercontent.com/106728438/336828329-c7a496d6-1321-457b-81f9-c109c72135a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTA0OTUsIm5iZiI6MTcxNzU5MDE5NSwicGF0aCI6Ii8xMDY3Mjg0MzgvMzM2ODI4MzI5LWM3YTQ5NmQ2LTEzMjEtNDU3Yi04MWY5LWMxMDljNzIxMzVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMjIzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQyYjY5NjZlM2JmZWM5YTE0NGM3NzU1ZjYwYmYxYmE1MDY2MTM0N2Y4ZjgzNmIwZThjOWZlNDFmNzJmY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hjfK_mI0ALP5w0rI4l2cs3xNCcMFPsO5uHpcX8PgeHk)
> 
> [Angular 18 change log](https://github.com/angular/components/releases/tag/18.0.0)

Updated function names prepending with '**m2-**' and the error went away. Thank you s=very much for the help.
