### ISSUE TITLE
bug(cdk/overlay): How can I prevent an overlay from dispatching a click event when it's opened by a pointerdown event on mobile?

### ISSUE THREAD

**Issue by rinarakaki** [angular/components#29198]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

There was a discussion about this before https://github.com/angular/components/issues/23643 but I want to know if there is an improvement for it instead of the workaround suggested there.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Doesn't dispatch click event when a dialog is opened by a pointerdown.

### Actual Behavior

It does and click the dialog content which causes unintended behaviour.

### Environment

- Angular: 17.3
- CDK/Material: 17.3
- Browser(s): Chrome (mobile)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
> There was a discussion about this before https://github.com/angular/components/issues/23643 but I want to know if there is an improvement for it instead of the workaround suggested there.

No, there haven't been any changes as far as I'm aware. There is #29044 which is vaguely related and which stops dispatching the outside click event for clicks on the trigger.
