### ISSUE TITLE
bug(Material Theme): Custom Theme Colors All Using Primary Color

### ISSUE THREAD

**Issue by ferhado** [angular/components#29206]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.x.x

### Description

All colors in the Angular Material components are displaying the same primary color when using a custom theme. This issue persists across various components and is not isolated to a specific one.

### Reproduction

1. Create a new Angular application.
2. Install Angular Material and set up a custom theme.
3. Observe that all components use the primary color for different types (accent, warn).

styles.scss:
![Screenshot 2024-06-06 085945](https://github.com/angular/components/assets/24419240/c625ce44-a48d-41ae-84b2-9f7ec9db5df0)

Component: 
![Screenshot 2024-06-06 090103](https://github.com/angular/components/assets/24419240/2f33d083-a897-4a17-a034-d8ccf9654473)

Result Preview: 
![Screenshot 2024-06-06 090156](https://github.com/angular/components/assets/24419240/9c78ff56-c9b6-4618-aeaa-6a69e4ee0789)

### Expected Behavior

The components should display the correct colors for primary, accent, and warn as defined.

### Actual Behavior

All components are displaying the same primary color regardless of the defined custom theme settings.

### Environment

Angular: 18.0.0
CDK/Material: 18.0.2
Browser(s): Chrome
Operating System: Windows

Please investigate this issue as it affects the overall appearance and functionality of the application using Angular Material with custom themes.

**Comment by amysorto** [comment]
Hi @ferhado, yes the color variants aren't a thing in M3 like they were in M2. Although we do realize many people customize their components this way, so we have a [backwards compatability mixin](https://material.angular.io/guide/material-2-theming#optional-add-backwards-compatibility-styles-for-color-variants) you can add to your theme file to get your code working again: `@include mat.color-variants-backwards-compatibility($theme);`.

**Comment by zilia-gmethot** [comment]
> Hi @ferhado, yes the color variants aren't a thing in M3 like they were in M2. Although we do realize many people customize their components this way, so we have a [backwards compatability mixin](https://material.angular.io/guide/material-2-theming#optional-add-backwards-compatibility-styles-for-color-variants) you can add to your theme file to get your code working again: `@include mat.color-variants-backwards-compatibility($theme);`.

It seems to me that the issue shouldn't be closed because the schematics generates code that isn't working out of the box.

**Comment by ferhado** [comment]
Hi @amysorto,

Thank you for clarifying the use of the backwards compatibility mixin for color variants in Material 3 (M3)

To improve clarity and avoid confusion, I suggest the following changes to the documentation:

1. Update component examples: Remove the use of color variants (primary, accent, warn) from component examples (e.g., buttons, cards) by default. Alternatively, clearly indicate in each relevant example that using these color variants requires the mat.color-variants-backwards-compatibility mixin.

2. Provide clear guidance: Include a note or link in the component examples that directs users to the theming section where the mixin is discussed.

This approach ensures that the examples are aligned with the default behavior in M3 and that developers are well-informed about the optional backwards compatibility mixin if they wish to use color variants.

Thank you for considering this suggestion.

Best regards
