### ISSUE TITLE
Angular M3 custom thema apply wrong contrast - Material 18

### ISSUE THREAD

**Issue by kemotx90** [angular/components#29211]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.* with m-2 custom palette contrast definition

### Description

With M-3 custom theme and custom palette (generated with suggested material schema) the contrast applied it's lower than expected.

my related [stackoverflow](https://stackoverflow.com/questions/78538323/how-to-apply-contrast-to-angular-material-theme-m-3)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-st8e6a?file=src%2Fstyles%2Fpalette%2Fpalette.scss
Steps to reproduce: run application

### Expected Behavior

contrast applyed by the following rules
[M3 roles](https://m3.material.io/styles/color/roles)

### Actual Behavior

low contrast applied and text unreadable (black text on blue content)

### Environment

- Angular: 18.0.0
- CDK/Material: 18.0.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by amysorto** [comment]
Can you take a look at your StackBlitz? A a quick glance theres some errors for me related to the theming.

Is there a specifc component you are seeing these incorrect contrast? Can you provide a screenshot of what you are seeing?

**Comment by kemotx90** [comment]
Sure.

primary
![immagine](https://github.com/angular/components/assets/60275739/49f02f61-8bbf-4727-a59b-308536de5eed)
![immagine](https://github.com/angular/components/assets/60275739/0d1ded07-075f-4386-9ae4-313d418b8d29)


secondary
![immagine](https://github.com/angular/components/assets/60275739/d7c8c484-0902-4d0d-8841-20c99c55b11a)
![immagine](https://github.com/angular/components/assets/60275739/c2941db3-454f-434e-a6bf-95e5850c46c6)


another primary palette
![immagine](https://github.com/angular/components/assets/60275739/448a594c-f353-4948-bba5-e1d627e0852a)
![immagine](https://github.com/angular/components/assets/60275739/b96370b3-32a3-459c-b86e-e16d45249fed)


this is the code that I use to apply bg-color
```scss
@use "@angular/material" as mat;

@import "../palette/palette";

@mixin theme($theme) {
  .sidenav-scroll-wrapper {
    background-color: mat.get-theme-color($theme, primary);
  }
}
```
you can find full scss code: [here](https://stackblitz.com/edit/stackblitz-starters-st8e6a?file=src%2Fstyles%2Flayout%2F_layout-component.theme.scss)

**Comment by amysorto** [comment]
The custom theme schematic has been updated since this issue was filed. I would run it again because there was an issue with slighly incorrect color generation: https://github.com/angular/components/pull/29536. Please open another issue if the colors still don't look correct!
