### ISSUE TITLE
Integrate Pre-built themes With Figma Material Theme Builder

### ISSUE THREAD

**Issue by JGSolutions** [angular/components#29218]
### Feature Description

I am debating to use some of the default Pre-built themes:
https://material.angular.io/guide/theming#pre-built-themes

At the same time I would like to use Figma to design my pages with the related pre-built-themes I choose.

How can I get those colors into Figma M3 file? I know there is a Material Theme Builder which I can select certain HEX colors. 

For example if I choose this theme $blue-palette will Figma generate the same tokens as Angular Material? 
Also how can I get the HEX color from $blue-palette predefined theme?

### Use Case

Able to have a selected defautt list of predefined themes int he figman Material Theme Bulder

**Comment by amysorto** [comment]
Unforunately at this time we do not have support for a Figma plugin and the Material theme builder figma plugin is a separate tool from the material team.

Although I think you can likely use the Material Theme Builder. To get the tonal palettes for our `$blue-palette` I think you would just need to insert this hex value: `#5a64ff`, which comes from here: https://github.com/angular/components/blob/main/src/material/core/theming/_palettes.scss#L220.

You can cross reference with the values in that `_palettes.scss` file linked above to see if they match the Figma output. I hope that works!
