### ISSUE TITLE
bug(Dialog): Dialog don't follow M3 specs

### ISSUE THREAD

**Issue by neo-xy** [angular/components#29230]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

It seems like dialog background is not following M3 sepcs-> should be surface-container-high but it's not.
(if it should not follow - can we know the reason why?) 

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

background is set to surface-container-high

### Actual Behavior

background is of different color (much more lighter)

### Environment

- Angular: 18
- CDK/Material:18
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by crisbeto** [comment]
We're taking the value directly from the Material team. The value is defined here: https://github.com/material-components/material-components-web/blob/master/packages/mdc-tokens/v0_161/_md-comp-dialog.scss#L66C6-L66C15

**Comment by crisbeto** [comment]
The values come directly from the Material Design team so the assumption is that they're correct. It's possible that the page with the spec is out of date.

**Comment by neo-xy** [comment]
@crisbeto ...or the page with tokens (scss) ...?   :)
(as components in Figma follow docs as well-> dialog bg is set to surface-high)
 ...I guess I would need to contact  MD team directly to get that resolve - cause at this point devs/designers don't know what to follow...
