### ISSUE TITLE
bug(Overlay): overlayOutsideClick triggered when clicking into shadowDOM within overlay

### ISSUE THREAD

**Issue by ChristophWieske** [angular/components#29241]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using a shadowDOM (e.g. with custom web components) within an overlay a click to that shadowDOM will trigger `overlayOutsideClick`.

Can you confirm that this is unintended behavior?
If yes, I´ll try to provide a pull request to fix it.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/cdk-overlay-web-components-issue?file=src%2Fmain.ts

Steps to reproduce:
1. Open the overlay by clicking the "open" button
2. Click the web component button

### Expected Behavior

The click does not trigger `overlayOutsideClick`

### Actual Behavior

The click does trigger `overlayOutsideClick`

### Environment

- Angular: 18.0.0
- CDK: 18.0.2

**Comment by ChristophWieske** [comment]
@crisbeto Love that this is going to be fixed so fast. I planned to let this be my first open source contribution, though.

Is there a way to show my willingness to provide a pull request for future issues? So that I can spend some time getting it ready - and getting familiar with the processes - before an experienced contributor does it with ease ;-)

**Comment by crisbeto** [comment]
Ah sorry, I didn't notice in the description that you wanted to fix it. In general feel free to send out a PR directly for bug fixes. For larger features it's a good idea to open an issue first so we can discuss if it's something we would want to support.
