### ISSUE TITLE
Button text color adopts background color after upgrading to Angular Material 18

### ISSUE THREAD

**Issue by ct-dixit** [angular/components#29250]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After upgrading to Angular and Angular Material version 18.0.0, the button text color incorrectly takes on the button's background color, making the text unreadable. This issue did not exist in version 17.0.0.

![Screenshot 2024-06-13 161546](https://github.com/angular/components/assets/106728438/47ff02be-f164-4788-afa6-beb2ff05893d)

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/stackblitz-starters-xswcad?file=src%2Fcustom-theme.scss,src%2Fcolor.scss,src%2Fmain.ts,src%2Fglobal_styles.css

Steps to Reproduce:
1. Set up a new Angular project with Angular 18 and Angular Material 18.
2. Implement a button using Angular Material components.
3. Apply a custom theme to the button with specific text and background colors.
4. Observe that the button text color adopts the background color instead of the specified text color.

### Expected Behavior

The button text color should remain distinct from the background color as specified in the theme settings.

### Actual Behavior

The button text color adopts the button's background color, making the text difficult to read.

### Environment

- Angular: 18.0.0
- CDK/Material: 18.0.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Window

**Comment by json-derulo** [comment]
See https://stackoverflow.com/a/78617559/5470544

In your custom palettes, you are using the same colors for hue and contrast. You should choose either black or white as contrast color, depending on which color gives best contrast. This is not an issue with Angular Material.

**Comment by crisbeto** [comment]
Closing since it looks like the palette wasn't defined correctly. Note that you can also generate a custom theme by running `ng generate @angular/material:m3-theme`.
