### ISSUE TITLE
bug(Datepicker): DatePicker does not emit event for `DateChange` or `DateInput` when bound form control setValue is called.

### ISSUE THREAD

**Issue by brian-weasner** [angular/components#29255]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm unsure if this is a bug or if it is expected functionality. Opening as a bug as I would either like functionality changed or some documentation update to reflect what I'm seeing.

The component outputs of `dateChange` and `dateInput` do not fire when the form control bound to the datepicker has it's value changed via a `setValue` call.

### Reproduction

StackBlitz link: <https://stackblitz.com/edit/bjdfqv?file=src%2Fexample%2Fdatepicker-events-example.ts>
Steps to reproduce:
1. Click the "Set Datepicker Input To Today Via Form Control" and see **NO** events are fired.
2. Click the "Set Datepicker Input To Today Via View Child" and see that events are fired. (as expected)

### Expected Behavior

When Form Control that is bound to a datepicker is updated via a call to `fooFormControl.setValue(bar)`, DateChange and DateInput Component level Outputs should emit because the date of the datepicker changed.

### Actual Behavior

No events are emitted from the DateChange and DateInput component level outputs.

### Environment

- Angular: 16 & 17
- CDK/Material: 16
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This is working as expected. We only fire off events when the user changes the value. It works for the `select` method because it's what we use in our own templates.

**Comment by brian-weasner** [comment]
Any chance the documentation on the material site that describes the output events could be updated to mention that they do not emit if a bound form control changes the selected date by calling `setValue`?
