### ISSUE TITLE
docs-bug(mat-table): Example suggesting to use max-width to set column width is misleading

### ISSUE THREAD

**Issue by TangerineCat** [angular/components#29294]
### Documentation Feedback

The CSS for this example uses the `max-width` property. However, if you expand the page wide enough, it's clear that this CSS rule doesn't do anything in Chrome, as the computed width of the cell is 72, which is longer than `max-width: 64px`

<img width="2070" alt="Screenshot 2024-06-20 at 12 11 03 PM" src="https://github.com/angular/components/assets/6618296/187221da-b188-48d9-bf64-fe4510416fc8">

AFAIK, the css `display: table-cell;` does not have a `max-width` property. This CSS should be removed to avoid confusion and a better example of how to configure max-width should be given.

### Affected documentation page

https://material.angular.io/components/table/examples#table-http

**Comment by andrewseguin** [comment]
Yeah it seems just setting `width` here would be a better example
