### ISSUE TITLE
docs-bug(@angular/google-maps): map-info-window

### ISSUE THREAD

**Issue by gstylli** [angular/components#29293]
### Documentation Feedback

There is an error in the map info window doc. It has  #marker="marker" which should be #marker="mapAdvancedMarker" as below.

<google-map
  height="400px"
  width="750px"
  [center]="center"
  [zoom]="zoom"
  (mapClick)="addMarker($event)">
    @for (position of markerPositions; track position) {
      <map-advanced-marker
        #marker="mapAdvancedMarker"
        [position]="position"
        (mapClick)="openInfoWindow(marker)" />
    }
    <map-info-window>Info Window content</map-info-window>
</google-map>

### Affected documentation page

https://github.com/angular/components/blob/main/src/google-maps/map-info-window/README.md

**Comment by crisbeto** [comment]
Fixed in #29343.
