### ISSUE TITLE
bug(Tabs): Box-shadow hidden

### ISSUE THREAD

**Issue by smilThakur** [angular/components#29302]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

applying box shadow the the content of any tab does not show due to inner css of overflow hidden and width 100%, adding margin reduced the size of the content which looks mis-align compared to tab icons

### Reproduction

StackBlitz link: https://stackblitz.com/edit/rs9pc4?file=src%2Fstyles.scss
Steps to reproduce:
1. add box-shadow to content 1 div and observe
2.

### Expected Behavior

too able to see the box-shadow

### Actual Behavior

box-shadow gets hideen

### Environment

- Angular: 18
- CDK/Material: 18
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Closing since this is working as expected. The `overflow: hidden` is necessary in order to render out the tab group correctly. You can add a margin or a padding to the content in order to give enough space for the box shadow.
