### ISSUE TITLE
docs-bug(COMPONENT): Add component as BottomSheet, Dialog AND @Input() example

### ISSUE THREAD

**Issue by seanmavley** [angular/components#29315]
### Documentation Feedback

Clarify with example how to use a component as bottomsheet AND also use the `@Input()` decorator

The examples on the bottomsheet and dialog page should include such scenario, as the error the comes up when not done right, is cryptic and vague.

The error: [lInjectorError: NullInjectorError: No provider for MatBottomSheetRef or MatDialogRef](https://stackoverflow.com/a/61443228/1757321)

### Affected documentation page

https://material.angular.io/components/bottom-sheet/examples

**Comment by seanmavley** [comment]
Also, how can one run locally the docs to get a page like this:

![image](https://github.com/angular/components/assets/5289083/7703cebe-63b1-4909-85a5-99a6d250da0f)

**Comment by andrewseguin** [comment]
The dialog's example "Injecting data when opening a dialog" shows how to pass data to the rendered component. Neither the dialog or bottom sheet components should expect `@input()`.

Inject this in your component to access data provided to your dialog:`@Inject(MAT_DIALOG_DATA) public data: DialogData`

The idea is similar for the bottom sheet
