### ISSUE TITLE
bug(COMPONENT): Inconsistency and uglified after updated.

### ISSUE THREAD

**Issue by calidion** [angular/components#29312]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

after update to v18, icon become very ugly.
: before update
![Screenshot from 2024-06-25 13-36-21](https://github.com/angular/components/assets/131776/c34b7ffd-9b18-4aaa-8192-67b736249b0d)
![Screenshot from 2024-06-25 13-35-11](https://github.com/angular/components/assets/131776/1ed18aac-fe86-4f41-a250-0e864d289d45)

: after update

![Screenshot from 2024-06-25 13-55-01](https://github.com/angular/components/assets/131776/fb66541e-9776-4c04-a7c8-53509f0bb725)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

style unchanged.

### Actual Behavior

changed.

### Environment

- Angular: v18
- CDK/Material: v18
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): ubuntu

**Comment by crisbeto** [comment]
This is the new design according to the Material Design specification: https://m3.material.io/components/switch/overview. You can switch back to the M2 appearance through the theme.
