### ISSUE TITLE
Mat-table: giving border to mat-mdc-row doesn't work 

### ISSUE THREAD

**Issue by henafufa** [angular/components#29316]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I wanted to give border for the row, but is is not working
when I give mat-mdc-cell the border works but that doesn't give the effect I wanted

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Actual Behavior

the css I added is not effective

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Can you post what you were trying to do?

**Comment by henafufa** [comment]
I did fixed
