### ISSUE TITLE
bug(MatListItem): Activated matListItemTitle color not changed when activated

### ISSUE THREAD

**Issue by blogcraft** [angular/components#29313]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The text of the activated MatListItem Should change color as it shows both in Angular Material and Material Design pages (m3)
![image](https://github.com/angular/components/assets/5615323/14192e1e-e47a-4619-b52c-81c394331623)
![image](https://github.com/angular/components/assets/5615323/fc3516c6-3790-4cc5-b500-ba955a256fb7)
![image](https://github.com/angular/components/assets/5615323/333472d3-862f-4616-a23a-7e0588563974)

But When Applied, Active only changes de button background.
![image](https://github.com/angular/components/assets/5615323/7922f395-00a3-4a8d-8fe7-5466d67d8969)

  ```
<mat-list-item
    routerLink="{{ item().routerLink }}"
    routerLinkActive
    #rla="routerLinkActive"
    [activated]="rla.isActive">
    <span matListItemTitle>{{ item().descripcion }}</span>
  </mat-list-item>
```

### Reproduction

StackBlitz link: I don't know hot make stackblitz to run in 18..0.5

### Expected Behavior

![image](https://github.com/angular/components/assets/5615323/14192e1e-e47a-4619-b52c-81c394331623)
![image](https://github.com/angular/components/assets/5615323/fc3516c6-3790-4cc5-b500-ba955a256fb7)
![image](https://github.com/angular/components/assets/5615323/333472d3-862f-4616-a23a-7e0588563974)

### Actual Behavior

![image](https://github.com/angular/components/assets/5615323/7922f395-00a3-4a8d-8fe7-5466d67d8969)

### Environment

- Angular: 18.0.5
- CDK/Material: 18.0.5
- Browser(s): Edge / Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by blogcraft** [comment]
I changed the theme color pallete to other colors, and the activated background is still blue for some reason.

sims that --mat-list-active-indicator-color wont adapt to the theme and --mdc-list-list-item-label-text-color won't set to an activated color.

**Comment by andrewseguin** [comment]
The color should be the system token `md.sys.color.on-secondary-container` according to https://m3.material.io/components/navigation-drawer/specs

This matches `secondary 10` in your theme palettem, which is essentially white/black with a tiny bit of color to it. We made the color change more pronounced on the docs site, which doesn't actually match M3 but we think it looks better =P
