### ISSUE TITLE
Marker clusterer

### ISSUE THREAD

**Issue by spartano74** [angular/components#29346]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Map-marker

### Description

using <map-advanced-marker insteadof 
 <map-marker /> @googlemaps/markerclusterer doesn't work

### Reproduction

☆

### Expected Behavior

Cluster marker as map-maker

### Actual Behavior

Doesn't work. The marker aren't clustered

### Environment

- Angular:17.3

**Comment by andrewseguin** [comment]
Please re-open with more clarity and information in the issue, and please include a reproduction
