### ISSUE TITLE
docs-bug(mat-select): I can't find how to use mat-select-search

### ISSUE THREAD

**Issue by YUHAI0** [angular/components#29347]
### Documentation Feedback

I can't find how to use mat-select-search, is it available in mat-select component ?

### Affected documentation page

https://material.angular.io/components/select/overview

**Comment by crisbeto** [comment]
Duplicate of https://github.com/angular/components/issues/5697.

**Comment by YUHAI0** [comment]
And a question I can use mat-select-search in official angular material ( not ngx-mat-select-search), but I can't find the document in official site document. @crisbeto
