### ISSUE TITLE
bug(MatCheckbox/MatSlideToggle): the component is included in the form control validators when using Reactive Forms

### ISSUE THREAD

**Issue by sebastian-altamirano** [angular/components#29369]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

I don't know if this behavior was present in previous versions, but I'm sure it happens in Angular v17 as well because that's where I first reproduced it.

### Description

When using `MatCheckbox` or `MatSlideToggle` with Reactive Forms (let's say we are using it with a `FormControl` named `control`), when one inspects `control.validator` it always contains an array with at least one validation function, even if `control` has no validator defined.

If we set a breakpoint in the `_setValidators` method of `AbstractControlDirective` we will see that it receives an instance of `_MatCheckbox`/`MatSlideToggle` (see screenshot).

![debugger](https://github.com/angular/components/assets/38230545/a1379572-e219-4648-8938-6d65d6c74eee)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-xpcrvu
Steps to reproduce:
1. Check the console logs to verify what is described in the description.

### Expected Behavior

`checkboxControl.validator` and `slideToggleControl.validator` must be `null`.

### Actual Behavior

`checkboxControl.validator`/`slideToggleControl.validator` are `[compose(control) { ... }]` (after the view has been initialized) when using `MatCheckbox`/`MatSlideToggle` with `FormControlDirective`.

### Environment

```
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cli                    18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by crisbeto** [comment]
The component is included in order to support the `required` input. This shouldn't be an issue, because if the component isn't required, it won't produce any validation errors.

**Comment by sebastian-altamirano** [comment]
I created the issue because I needed to find out if a form control had at least one validator associated with it. Since `AbstractControl` does not have a method to find this out, I had to resort to `control.validator` and `control.asyncValidator`, and I came up with a solution similar to the following:

```ts
function hasValidators(control: AbstractControl): boolean {
	return control.validator !== null || control.asyncValidator !== null;
}
```

But since `MatCheckbox` and `MatSlideToggle` include the component in `control.validator`, I had to modify the solution using `_rawValidators`:

```ts
function hasValidators(control: AbstractControl, isCheckboxOrSlideToggle: boolean): boolean {
	if (isCheckboxOrSlideToggle && '_rawValidators' in control && Array.isArray(control['_rawValidators'])) {
		return control['_rawValidators'].length > 1 || control.asyncValidator !== null;
	}

	return control.validator !== null || control.asyncValidator !== null;
}
```
