### ISSUE TITLE
bug(MatDialog): Browser selection disappears when dialog opens in firefox

### ISSUE THREAD

**Issue by junedzs** [angular/components#29362]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Browser selection disappears when dialog opens in firefox. It is working properly in Chrome.

### Reproduction

Steps to reproduce:
1. Go to https://v18.material.angular.io/components/dialog/api in Firefox browser
2. Select text using mouse
3. Click "Pick one" that opens dialog
4. Selection disappears

### Expected Behavior

Selection should retain. And it is working as expected in Chrome.

### Actual Behavior

Selection is disappearing

### Environment

- Angular: 14, 15, 16, 17, 18
- CDK/Material: 14, 15, 16, 17, 18
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
This is happening because we need to move focus into the dialog for proper accessibility. It's up to the browser whether or not it deselects the text when focus is moved.
