### ISSUE TITLE
docs-bug(Datepicker/DateFilterFn): DateFilterFn signature does not indicate possible 'Moment' types, instead includes 'null' and return value is not explained either

### ISSUE THREAD

**Issue by Opcyc-Ben** [angular/components#29385]
### Documentation Feedback

There is no indication that DateFilterFn can be handed a 'Moment' type value.
The filter function is also sometimes called with null as an argument, regardless of project setup, though no explanation is ever given as to what 'null' even conceptually means:
It's a Date filter. There are no 'null' dates on any human calendar. Should I filter them out? Does it even matter?
Furthermore: It is not explained in the docs, if true as a return value means keep or toss. Am I filtering out the good ones or the bad ones?
![image](https://github.com/angular/components/assets/142500282/95976703-858c-4d10-bace-59a82050f031)

### Affected documentation page

https://material.angular.io/components/datepicker/api#DateFilterFn

**Comment by hhaasbroek** [comment]
can this be assigned to me please :)

**Comment by Opcyc-Ben** [comment]
Wow, that was fast. Thank you so much,
