### ISSUE TITLE
feat(cdk/drag-drop): add mixed orientation support using transform

### ISSUE THREAD

**Issue by nghiadg** [angular/components#29393]
### Feature Description

These changes implement a new `DropListSortStrategy` that allows sorting of lists that can wrap by moving them using a `transform` which keeps the DOM stable and allows for the sorting to be animated

The new strategy can be enabled by setting `cdkDropListOrientation="mixed"`.

**Comment by crisbeto** [comment]
Closing based on https://github.com/angular/components/pull/29394#issuecomment-2212402465.
