### ISSUE TITLE
feat(cdk-table): Error state of mat-table

### ISSUE THREAD

**Issue by sh977218** [angular/components#29415]
### Feature Description

Sometime the cdk table data is from API, where API could throw error.
It would be really nice to have a directive when data from an API throw error (distinguish from empty data) on an error state, similar to directive `CdkNoDataRow`, but could be `CdkErrorStateRow`.

**Comment by crisbeto** [comment]
We can't do this automatically like we do with `CdkNoDataRow`, because we don't know if the data failed to fetch. It may be easier to do this yourself with an `@if`/`@else`.
