### ISSUE TITLE
bug(CDK OVERLAY): Incorrectly positioned panels when using css zoom property

### ISSUE THREAD

**Issue by Marbulinek** [angular/components#29424]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

When using css property zoom, like 
```css
body{
   zoom: 0.9;
}
```
CDK Overlay panel is incorrectly displaying panels like menu, select options etc.

[StackBlitz demo](https://cdk-overlay-zoom.stackblitz.io)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

When I will use css property zoom, all elements on cdk overlay will be displayed correctly.

### Actual Behavior

When I will use css property zoom, all elements on cdk overlay are pushed in other position as it should be.

### Environment

- Angular: 18.0.0
- CDK/Material: v.18
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, MacOs

**Comment by crisbeto** [comment]
Unfortunately we can't do much about this, because the browser reports the same dimensions with and without the `zoom`. The only way to handle it would be to check using `getComputedStyle`, but for that to work we would have to traverse the all the ancestors which will be inefficient.
