### ISSUE TITLE
bug(cdk/coercion): `coerceNumberProperty(thing, undefined)` has invalid implementation or signature

### ISSUE THREAD

**Issue by urugator** [angular/components#29425]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`coerceNumberProperty(thing, undefined)` works the same way as `coerceNumberProperty(thing)`, so it yields `0` if the `thing` isn't coercible to number. This is quite unexpected, because:
1. In all other cases the fallback argument is respected.
2. The return type is different: `coerceNumberProperty(thing, undefined)` returns `number | undefined`, even though the implementation always yields `number`.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Fallback argument should be respected even for `undefined`.

### Actual Behavior

`undefined` isn't respected as a fallback.

### Environment

- Angular: 17.0.6
- CDK/Material: 17.1.0
- Browser(s): *
- Operating System (e.g. Windows, macOS, Ubuntu): *

**Comment by GiftLanga** [comment]
I'll work on this issue if no one working on it.

**Comment by GiftLanga** [comment]
@urugator it's not possible to set the fallback value as **undefined** as you can see on the implementation the default fallback value is 0.
![image](https://github.com/user-attachments/assets/597a22cc-1b27-4a06-8b4a-dd731d98b4c9)

I suggest that you return a string as a work around like this.
`coerceNumberProperty<String>(value, 'undefined')`

**Comment by urugator** [comment]
>  the implementation the default fallback value is 0.

Yes and the issue states that the implementation or signature is not correct.
Either the implementation should check `arguments.length` or the return type of `coerceNumberProperty(x,undefined)` should resolve to `number`. Instead it matches `coerceNumberProperty<D>(value: any, fallback: D): number | D` overload, so the return type resolves to  `number` | `undefined`, which makes you believe it returns `undefined` when `value` is not coercible to number. I am just repeating what is already noted in the OP.

**Comment by GiftLanga** [comment]
It is correct that the return type of `coerceNumberProperty(x,undefined)` is `number | undefined` because of this definition `coerceNumberProperty<D>(value: any, fallback: D): number | D` as you stated. 

However as I said it is not possible to return `undefined` when the fallback default value is 0. The only way I can think of is to set the fallback default value to undefined, but that will break the tests.

A better recommendation would be to use `null` instead, because it's an assignment value.
`coerceNumberProperty(value, null)`

**Comment by urugator** [comment]
> it is not possible to return undefined when the fallback default value is 0.

```ts
export function coerceNumberProperty(value: any, fallbackValue: any) {
  return _isNumberValue(value) ? Number(value) : arguments.length === 2 ? fallbackValue : 0;
}
// coerceNumberProperty('foo') === 0
// coerceNumberProperty('foo', undefined) === undefined
```
Note that implementation signature is not visible from the outside, so this doesn't break the API, quite the opposite -  the  implementation is changed to match these 2 overload signatures, that are actually visible from the outside.

**Comment by GiftLanga** [comment]
Ohh okay I see, can you make the PR.

**Comment by urugator** [comment]
@crisbeto Thank you for picking this up, but I think you forgot to remove the default value in argument ` fallbackValue = 0` => `fallbackValue`. JS treats `undefined` as not provided:
```js
function foo(x=0) {
    console.log(arguments.length, x);
}
foo(); // 0 0
foo(undefined); // yields 1 0  but we want 1 undefined
```
