### ISSUE TITLE
Support using Angular CDK & Material v16 in Angular v18

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/components#29440]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Any Angular v17 version.

### Description

The `peerDependencies` sections in the `package.json` file for Angular CDK v16.2.14 and Angular Material v16.2.14 specify only @angular v16 or v17. However, there is declared official support for running Material M2, even in Angular v18. To allow it, it's necessary to add `^18.0.0` for all Angular packages in the `peerDependencies` sections of Angular CDK v16 and Angular Material v16.
```
// Angular CDK 16.2.14
"peerDependencies": {
    "@angular/core": "^16.0.0 || ^17.0.0",
    "@angular/common": "^16.0.0 || ^17.0.0",
    "rxjs": "^6.5.3 || ^7.4.0"
}
```
```
// Angular Material 16.2.14
"peerDependencies": {
    "@angular/animations": "^16.0.0 || ^17.0.0",
    "@angular/cdk": "16.2.14",
    "@angular/core": "^16.0.0 || ^17.0.0",
    "@angular/common": "^16.0.0 || ^17.0.0",
    "@angular/forms": "^16.0.0 || ^17.0.0",
    "@angular/platform-browser": "^16.0.0 || ^17.0.0",
    "rxjs": "^6.5.3 || ^7.4.0"
}
```
Using the `--legacy-peer-deps` flag is not the ideal solution because it also affects the installation of all other packages.

### Expected Behavior

Allow using Angular CDK v16 and Angular Material v16 together with Angular v18.

### Actual Behavior

When running the `npm i` command (Angular v18 environment), the following resolve problem appears:
```
Could not resolve dependency:
npm error peer @angular/common@"^16.0.0 || ^17.0.0" from @angular/cdk@16.2.14
npm error node_modules/@angular/cdk
npm error @angular/cdk@"16.2.14" from the root project
```

### Environment

- Angular: 18.1.0
- CDK/Material: 16.2.14
- Browser(s): Chrome, FF
- Operating System: Windows, macOS, Ubuntu

**Comment by crisbeto** [comment]
The current setup is consistent with our version policy. Supporting a wider version range would be more maintenance both on the Material/CDK side and on the framework's side.

**Comment by mlc-mlapis** [comment]
@crisbeto But Angular v18 was declared the last version with official support for running Material M2, right? The change from M2 to M3 was introduced in Angular v17.2, and the official version policy should cover Angular v18. What is the version policy you are talking about?

**Comment by crisbeto** [comment]
M2 is supported and is the default in v18. We introduced M3 as an opt-in feature.

**Comment by mlc-mlapis** [comment]
@crisbeto Are we talking about the same things? I am talking about using all those `MatLegacy____Module` modules. I checked the timeline in detail, and it's the fact that they were introduced in Angular v15. Does it mean that Angular v16 and v17 covered the maintenance range of the two major versions, and Angular v18 is already out of it?

**Comment by crisbeto** [comment]
Yes, the legacy modules were deprecated for two major versions so we removed them for v18.

**Comment by mchhh44** [comment]
@crisbeto sorry for reopening this thread, but you've claimed that we would be able to use Material v16 with Angular v18 during v17 launch. Thats really missleading, we were planning to use legacy components with angular v18

Here is the source of that claim ->
We deprecated legacy components in v15 to be removed in v17. Even though they’ll not be part of the Angular Material v17 package, you can still update your apps to Angular v17 and use the v16 Angular Material package. **This will be an option until v18, after which Angular Material v16 will no longer be compatible with newer versions of Angular.**
https://blog.angular.dev/introducing-angular-v17-4d7033312e4b
