### ISSUE TITLE
docs-bug(mat-slider): thumbLabel unsupported

### ISSUE THREAD

**Issue by dmauro13** [angular/components#29442]
### Documentation Feedback

Hi,

I recently upgraded from angular 13 to angular 18, and I noticed that since 16v mat-slider does not support the thumbLabel option.

In the documentation, it was present in version 14, then it disappeared.

Now I don't know what to replace it with, and in the documentation, there is no mention of this property disappearing. How can I replace it? And how can I make other components where it happens as well?

@Input()
thumbLabel: boolean

<mat-slider
		[(ngModel)]="_value"
		[max]="_max"
		[min]="_min"
		[step]="_step"
		[thumbLabel]="true"
		color="primary" #ngSlider><input matSliderThumb (change)="onChange({source: ngSliderThumb, parent: ngSlider, value: ngSliderThumb.value})" #ngSliderThumb="matSliderThumb" />
	</mat-slider>

### Affected documentation page

https://v14.material.angular.io/components/slider/api

**Comment by hhaasbroek** [comment]
Hi, you can assign this one to me

**Comment by hhaasbroek** [comment]
I don't completely understand because the docs does reference thumblabel in its example
`    <mat-slider
        class="example-margin"
        [disabled]="disabled"
        [max]="max"
        [min]="min"
        [step]="step"
        [discrete]="thumbLabel"
        [showTickMarks]="showTicks">
      <input matSliderThumb [(ngModel)]="value" #slider>
    </mat-slider>`
    
    here -> https://v18.material.angular.io/components/slider/examples

**Comment by dmauro13** [comment]
Thank you very much for the answer. (I dont' know why but i don't have permission to assign issues)

So what used to be an input parameter [thumbLabel] becomes [discrete]=“thumbLabel”?
My component is already matSliderThumb as in the v18 documentation example, but it is not shown.

Let's say my doubt is that the [thumbLabel] decorator has been deprecated since v14 but in the documentation there is no why and no alternative

**Comment by hhaasbroek** [comment]
I don't know if this really answers the question but I believe the recommended approach now involves setting the label property directly on the matSliderThumb component. This aligns with the current Material Slider implementation and ensures compatibility with future updates.
Something like this?
`<mat-slider>
  <mat-slider-thumb label="My Label"></mat-slider-thumb>
</mat-slider>`

**Comment by dmauro13** [comment]
It works. Thank you!

**Comment by crisbeto** [comment]
It sounds like this is resolved so I'll close it. It can be reopened if there's anything actionable on our end.
