### ISSUE TITLE
bug(youtube-player): youtube-player won't load video if videoId is provided via component properties

### ISSUE THREAD

**Issue by jimkoen** [angular/components#29455]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using Firefox 127 on Fedora, when loading videos with the /@angular/youtube-player component, the video fails to load if the video is provided via a component property.

I'm not sure if I'm using the component in a wrong way, as this doesn't seem like the intended behavior and would have been caught during testing. So I was wondering if someone could clarify how to use the component when  loading videos dynamically.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-vkhp3u?file=src%2Fmain.ts
Steps to reproduce:
1.  Create an instance of youtube-player and feed it's videoId from the components properties (or just run the stackblitz)

### Expected Behavior

The video loads the same way it would load when the videoId was defined in the template.

### Actual Behavior

An empty placeholder is shown, the video fails to load.

### Environment

- Angular: 18.x
- /@angular/youtube-player: 18.1.1
- Browser(s): Firefox 127.0
- Operating System: Fedora Linux

**Comment by crisbeto** [comment]
Your template is incorrect. The `videoId="this.video_id"` should be `[videoId]="this.video_id"`.

**Comment by Pieeer1** [comment]
> Your template is incorrect. The `videoId="this.video_id"` should be `[videoId]="this.video_id"`.

I just stumbled on this after having the same issue. This needs to be fixed in the documentation, as the documentation here:

https://github.com/angular/components/tree/main/src/youtube-player

does not use the [videoId], and instead uses videoId
