### ISSUE TITLE
feat(cdk/Overlay): Allow using string values in cdkConnectedOverlayOffsetX/Y

### ISSUE THREAD

**Issue by e-oz** [angular/components#29466]
### Feature Description

Right now `CdkConnectedOverlay.cdkConnectedOverlayOffsetX/Y` only accepts numbers. 
Please allow it to accept string values, like `2rem`, for example.

### Use Case

In one of my apps, it is the only part that doesn't scale when html.font-size is modified (or font size is changed in browser's settings).

**Comment by crisbeto** [comment]
The reason it only accepts numbers is because we're using the value in pixel-based calculations.

**Comment by e-oz** [comment]
Is it too much to ask for something like this?

```ts
let vPx = 0;
if (typeof v === 'string') {
  if (!v.endsWith('rem')) {
    vPx = parseFloat(v);
  } else {
    const rem = parseFloat(getComputedStyle(document.documentElement).fontSize);
    vPx = rem * parseFloat(v);
  }
}
```

**Comment by crisbeto** [comment]
I would be hesitant to support something like that, because some components authors may start expecting to also respond to dynamic changes, e.g. a media query that sets the `font-size` on the root node to a different value.

**Comment by e-oz** [comment]
That's fair, I understand that.
It would be easier to implement on my end :)

But still, I hope you move away from pixels some day 😎
