### ISSUE TITLE
bug(cdk/drag-drop): not possible to use custom drag handle with mat table rows

### ISSUE THREAD

**Issue by chintankavathia** [angular/components#29475]
### Description

CDK Drag and Drop allows to reorder rows within material table however it is not possible to restrict the reordering only using drag handle icon. 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/vaeujs-yrvig8?file=src%2Fexample%2Fcdk-drag-drop-table-example.html
Steps to reproduce:
1. Open drag and drop on table rows example from here https://material.angular.io/cdk/drag-drop/examples#cdk-drag-drop-table
2. Add `cdkDragHandle` to first cell def `mat-icon`

### Expected Behavior

Row should only be dragged using the icon.

### Actual Behavior

Rows can be dragged from anywhere within that row.

### Environment

- Angular: 18.1
- CDK/Material: 18.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by alessiobianchini** [comment]
Hi, I had a similar problem. A workaround to your problem would be to add `style="pointer-events: none;"` to the row and `style="pointer-events: all;"` to the cell. 
This is your stackblitz updated: https://stackblitz.com/edit/vaeujs-1jo3qp?file=src%2Fexample%2Fcdk-drag-drop-table-example.html

**Comment by xylplm** [comment]
hope to fix this bug as soon as possible, as it has a significant impact on the user experience.

**Comment by xylplm** [comment]
@andrewseguin Request experts to improve the progress. This issue has a significant impact on the operation of mobile devices. At present, I have to turn off this function on my mobile phone. I hope it can be repaired as soon as possible. Thank you.
