### ISSUE TITLE
Dropdown Alignment Issues After Upgrading from Angular 12 to Angular 15

### ISSUE THREAD

**Issue by sohinid2023** [angular/components#29473]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 12

### Description

I recently upgraded my web application from Angular 12 to Angular 15. Since the upgrade, I've encountered issues with the **alignment of all dropdowns**—they are no longer positioned correctly.

**Here are the specifics:**

- Previous Angular Version: 12
- Current Angular Version: 15
- Previous CDK Version: "@angular/cdk": "^12.0.0"
- Current CDK Version: "@angular/cdk": "^15.2.9" 

### For better understanding, I have attached two images:
- **Before Upgrade:** [Image showing correct alignment]
 ![image](https://github.com/user-attachments/assets/4a0423c5-031c-48e1-89d2-4f91ddf58e83)

- **After Upgrade**: [Image showing misaligned dropdowns]
![image](https://github.com/user-attachments/assets/fe63a34c-6984-4777-b11a-bfc19dfb509c)

Has anyone faced similar issues after upgrading Angular and the CDK? What steps can I take to resolve this alignment problem?

Thank you in advance for your help!

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

**Expected Outcome**: I was expecting the dropdowns to maintain their previous alignment and positioning after the upgrade. Specifically, I anticipated that the upgrade process would be smooth without affecting the layout of existing components.
![image](https://github.com/user-attachments/assets/29dee8f9-8599-4302-88c2-7218a79023a0)

### Actual Behavior

![image](https://github.com/user-attachments/assets/275915af-e998-4a7f-938e-08c4bcd4177a)

### Environment

- Angular: 15.2.11
- CDK/Material: "^15.2.9"
- Browser(s):Chrome Version 126.0.6478.182 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
