### ISSUE TITLE
bug(typography): Huge typography differences between material 2 and material 3

### ISSUE THREAD

**Issue by electrofLy** [angular/components#29544]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

M2

### Description

Including the typography using the typography-hierarchy mixin ```@include mat.typography-hierarchy($theme)``` adds some default styling for some html dom elements. 

For the headings elements h1..h6 there seems to be a huge difference in font-sizes. To compare H1 was set to 20px while now it is set to 44px. I find that to be a huge difference and really not matching the rest of the font-sizes.

In the code I see that for headings, the display typescales are used. Is it the correct one? Seems to me that those are not very web friendly scales.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-6yln2x?file=src%2Fstyles.scss

### Expected Behavior

Adequate font sizes for heading elements

### Actual Behavior

Huge headings which are incompatible with the rest of the application

### Environment

@angular-devkit/architect    0.1801.2
@angular-devkit/core         18.1.2
@angular-devkit/schematics   18.1.2
@schematics/angular          18.1.2
rxjs                         7.8.1
typescript                   5.4.5
webpack                      5.93.0
zone.js                      0.14.8

**Comment by mmalerba** [comment]
[The spec](https://m3.material.io/styles/typography/type-scale-tokens) only defines 3 headline typescales, but it isn't clear whether those are intended to be used as h1-3 (and title used for h4-6), or if they should be h4-6 (and display used for h1-3).

The typography-hierarchy mixin gives one possible mapping, but its certainly not the only valid mapping, and I would encourage users to write their own version of the mixin for their app if they find that a different mapping suits them better. The builtin mixin is not meant to be a definitive "you must use this" type of thing
