### ISSUE TITLE
bug(mat-select): mat-select dropdown color doesn't support theme switching

### ISSUE THREAD

**Issue by moondc** [angular/components#29567]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Switching the theme from light mode to dark mode (or vice versa) does not apply the new styles to mat-select's panel.  The mat-select color changes, but the mat-select panel does not.

(I started learning about theming 3 days ago using the angular theming documentation.  It is possible my code is the issue)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-ex6hok?file=src%2Fglobal_styles.scss
Steps to reproduce:
1. Click the dropdown (memorize the panel background color)
2. Select "Light Theme"
3. Notice the Select changed colors, but the dropdown panel did not.

To view the correct colors
1. Go to global_styles.scss
2. Modify line 10 to `@include mat.all-component-themes(theme.$light-theme);`
3. Ignore the color of the mat-select being wrong, only look at the panel.

### Expected Behavior

![image](https://github.com/user-attachments/assets/8e5a9745-7487-48b2-9e4b-ce270f628020)

### Actual Behavior

![image](https://github.com/user-attachments/assets/72fc83d9-fa9b-4d61-8a72-7a20c6e3adbc)

### Environment

- Angular: 18.1.4
- CDK/Material:  18.1.4
- Browser(s): Chrome, Firefox
- Operating System: Ubuntu

**Comment by moondc** [comment]
I inverted the "Actual Behavior" picture, but it's the same issue.  Starting in dark mode and switching to light, causes the mat-select to be light-theme and the mat-select panel to be dark-theme, even though my mixins should be converting all themes, colors, bases to light mode.
It's hopefully apparent when you visit the stackblizt

**Comment by json-derulo** [comment]
Your code needs optimization, there are a lot of warnings in the browser console about duplicate styles.

Regarding your issue, the dropdown is rendered in an Overlay which is placed directly in the body and not inside your `<app-root>`, as you can see in the below screenshot.

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/541bd56d-3b2a-4a7f-b0f6-97205872bd73">

For this reason, the class you apply to your `<header>` element does not have an effect on the dropdown. To apply the theme to your whole app, you should set the `light-theme` or `dark-theme` CSS class to the body or HTML. Alternatively, you can set the theme to the dropdown via the select's `panelClass` property:

```html
<mat-select [panelClass]="theme">
```

**Comment by crisbeto** [comment]
@json-derulo is correct, the theme needs to be set either their the `panelClass`, or by doing something like this:

```
constructor(container: OverlayContainer) {
  container.getContainerElement().classList.add('your-theme-goes-here');
}
```

**Comment by moondc** [comment]
Adding a service to add the theme class to the document.body worked!  Thank you
