### ISSUE TITLE
feat(tooltip): don't add aria-describedby if tooltip text is a prefix of host element aria-label

### ISSUE THREAD

**Issue by chivesrs** [angular/components#29594]
### Feature Description

Here is the scenario:

```
<button
  aria-label="Delete comment Billy bob said Hello"
  matTooltip="Delete"
  mat-icon-button
>
  <mat-icon>delete</mat-icon>
</button>
```

Screen reader will read out "Delete comment Billy bob said Hello button Delete", where the final Delete is extra duplicate (coming from the tooltip aria-describedby). Currently, if the aria-label matches the tooltip text exactly, then no such duplicity is added.

Feature request is to make this "match exact" condition to be a prefix. As in, if the tooltip text is a prefix of the aria-label, then do not add an aria-describedby.

In my example, because "Delete" is a prefix of "Delete comment Billy bob said Hello", then no aria-describedby would be added on.

**Comment by crisbeto** [comment]
This feels a bit arbitrary to me and I'm not sure if we can do it safely in all locales. Closing the issue since it can be worked around by changing the template.
