### ISSUE TITLE
docs-bug(cdk/text-field): missing information about required text-field-autosize mixin

### ISSUE THREAD

**Issue by KOHETs** [angular/components#29597]
### Documentation Feedback

The documentation for CdkTextareaAutosize does not mention that the text-field-autosize mixin is required.  Without this mixin, the autosizing might not function as expected, which could cause UI issues or confusion.

The cdkTextFieldAutofill documentation already explains the need for the text-field-autofill mixin, including why it’s needed and how to add it. I suggest adding similar information to the cdkTextareaAutosize documentation to cover the text-field-autosize mixin. While this might seem repetitive, it will help ensure consistency and clarity.

I can create a Pull Request with these changes.

### Affected documentation page

https://material.angular.io/cdk/text-field/overview

**Comment by crisbeto** [comment]
We're currently working towards not needing to manually include those mixins: https://github.com/angular/components/pull/29620
