### ISSUE TITLE
bug(material/slide-toggle): Sass deprecation warning since v18.2.0

### ISSUE THREAD

**Issue by json-derulo** [angular/components#29591]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.1.x

### Description

After updating to Angular 18.2.0 in an app using Angular Material with a custom theme, the following Sass warning is produced:

```lang-none
▲ [WARNING] Deprecation [plugin angular-sass]

    node_modules/@angular/material/slide-toggle/_slide-toggle-theme.scss:46:6:
      46 │       --mdc-switch-disabled-label-text-color: #{inspection.get-the...
         ╵       ^

          $theme,
          foreground,
          disabled-text
        )};

  Sass's behavior for declarations that appear after nested
  rules will be changing to match the behavior specified by CSS in an upcoming
  version. To keep the existing behavior, move the declaration above the nested
  rule. To opt into the new behavior, wrap the declaration in `& {}`.
  
  More info: https://sass-lang.com/d/mixed-decls
```

The warning originates from the Slide Toggle theme:

https://github.com/angular/components/blob/4f2bc4da78ff85c6a9d5a2323908c82e6af85e11/src/material/slide-toggle/_slide-toggle-theme.scss#L46

### Reproduction

StackBlitz link: https://stackblitz.com/edit/tq6jmr?file=src%2Fstyles.scss
Steps to reproduce:
1. Build / start the project

### Expected Behavior

No Sass warning produced

### Actual Behavior

Sass warning is produced

### Environment

Angular CLI: 18.2.0
Node: 18.20.3
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 18.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-experimental
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.0
@angular-devkit/build-angular   18.2.0
@angular-devkit/core            18.2.0
@angular-devkit/schematics      18.2.0
@schematics/angular             18.2.0
rxjs                            7.4.0
typescript                      5.4.5
zone.js                         0.14.6

**Comment by martinboue** [comment]
Same observation with M3 custom theme.

**Comment by crisbeto** [comment]
What version of Sass are you running?

**Comment by json-derulo** [comment]
I'm not overriding the Sass version, I'm using the one from `@angular-devkit/build-angular`. Their `sass` version is v1.77.8.

**Comment by xylplm** [comment]
I also encountered the same problem after upgrading to Angular 18.2.0

`▲ [WARNING] Deprecation [plugin angular-sass]

    node_modules/@angular/material/slide-toggle/_slide-toggle-theme.scss:46:6:
      46 │       --mdc-switch-disabled-label-text-color: #{inspection.get-the...
         ╵       ^

          $theme,
          foreground,
          disabled-text
        )};

  Sass's behavior for declarations that appear after nested
  rules will be changing to match the behavior specified by CSS in an upcoming
  version. To keep the existing behavior, move the declaration above the nested
  rule. To opt into the new behavior, wrap the declaration in `& {}`.

  More info: https://sass-lang.com/d/mixed-decls

  The plugin "angular-sass" was triggered by this import

    angular:styles/global:styles:2:8:
      2 │ @import 'src/assets/scss/style.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by zwjohn** [comment]
The same here

Sass's behavior for declarations that appear after nested
  rules will be changing to match the behavior specified by CSS in an upcoming
  version. To keep the existing behavior, move the declaration above the nested
  rule. To opt into the new behavior, wrap the declaration in `& {}`.

  More info: https://sass-lang.com/d/mixed-decls

  The plugin "angular-sass" was triggered by this import

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~

**Comment by PhilFlash** [comment]
Same problem here after upgrading to Angular 18.2.0

``
▲ [WARNING] Deprecation [plugin angular-sass]

    node_modules/@angular/material/slide-toggle/_slide-toggle-theme.scss:46:6:
      46 │       --mdc-switch-disabled-label-text-color: #{inspection.get-the...
         ╵       ^

          $theme,
          foreground,
          disabled-text
        )};

  Sass's behavior for declarations that appear after nested
  rules will be changing to match the behavior specified by CSS in an upcoming
  version. To keep the existing behavior, move the declaration above the nested
  rule. To opt into the new behavior, wrap the declaration in `& {}`.

  More info: https://sass-lang.com/d/mixed-decls

  The plugin "angular-sass" was triggered by this import

    angular:styles/global:theme-purple:1:8:
      1 │ @import 'src/styles/_theme_purple.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

``

**Comment by crisbeto** [comment]
Following up here: fixing these deprecation warnings will change the order in which some CSS will be generated which can break some users so we want to delay them until v19. To address the issue we'll:
1. Downgrade the CLI to a version before the warning started being logged (see https://github.com/angular/angular-cli/pull/28234). If you're managing the Sass dependency yourself, you should set the version to be lower than 1.77.7.
2. Land #29596 in v19.
3. Talk to the Sass team to see if there's a better way to handle it on our end, like potentially a new syntax.
