### ISSUE TITLE
bug(mat-select): Required attribute not working as expected 

### ISSUE THREAD

**Issue by oybekkamolov** [angular/components#29602]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

[Video of Issue](https://streamable.com/levi6l)

When the user presses the submit button on a form without a selection in a required drop-down, the form still gets submitted and the page refreshes. 

Note the **mat-select** element has the **required** attribute. 

```
<div class="content">
  <form>
    <mat-form-field>
      <mat-label>First Name</mat-label>
      <input matInput required />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Middle Name</mat-label>
      <input matInput />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Last Name</mat-label>
      <input matInput required />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Gender</mat-label>
      <mat-select required>
        <mat-option value="male">Male</mat-option>
        <mat-option value="female">Female</mat-option>
        <mat-option value="other">Other</mat-option>
      </mat-select>
    </mat-form-field>
    <button type="submit" mat-flat-button>Submit</button>
  </form>
</div>
```

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

For the form to prompt the user to fill out the mat-select field.

### Actual Behavior

The form submits. The page refreshes. All fields are cleared.

### Environment

- Angular: 18.2.0
- Node: 22.6.0
- CDK/Material: mat-select
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): win32 x64

**Comment by crisbeto** [comment]
It's because `mat-select` is a custom component and only native ones have the ability to prevent form submission. You should check the validation status of the form before allowing it to be submitted. Another option is to use `mat-form-field` with a native `select` element.
