### ISSUE TITLE
bug(cdk): Wrong offset of dragged element on RTL

### ISSUE THREAD

**Issue by vladretca** [angular/components#29604]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.2.2

### Description

When in RTL mode, and try to drag a element from a list, the element is offset to the right with the length of the screen width

### Reproduction

StackBlitz link: https://stackblitz.com/edit/kuk7sb?file=src%2Findex.html
Steps to reproduce:
1. add dir="rtl" to html tag in index.html
2. try to drag an element from the list

### Expected Behavior

The element should be under the drag start position (mouse) like it was in v17

### Actual Behavior

https://github.com/user-attachments/assets/d11d5cfb-3201-4819-b4e9-8d562280a25c

### Environment

- Angular: 18.1.3
- CDK/Material: 18.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
It looks like this was caused by #28945. I'm still figuring out how we can work around it.
