### ISSUE TITLE
docs-bug(tree): Replace deprecated NestedTreeControl in example code

### ISSUE THREAD

**Issue by Farbfetzen** [angular/components#29621]
### Documentation Feedback

The example code for the nested tree uses the [deprecated NestedTreeControl](https://material.angular.io/cdk/tree/api#NestedTreeControl). Please replace it to show users how to implement a nested tree without it.

### Affected documentation pages

- https://material.angular.io/components/tree/overview#nested-tree
- https://material.angular.io/cdk/tree/overview#nested-tree

**Comment by Farbfetzen** [comment]
Never mind, I found #27626 and #29062 which will resolve this issue.

**Comment by chrissena** [comment]
I'm very confused as I still can't find any examples using the new API on the examples tab. It still looks like they are all using the deprecated treeControl. Am I missing something?

**Comment by Farbfetzen** [comment]
The one titled "Tree with nested nodes, using childAccessor" is not using NestedTreeControl.

But I'm reopening this issue anyway because I think having examples using a deprecated api is an bug/oversight. The most important examples on the overview tab, the ones people stumble upon first, should be written in a way that doesn't give users deprecation warnings in their IDEs.

**Comment by chrissena** [comment]
How strange. I'm on v18.2.3 of the docs looking at examples of the mat-tree on the examples tab. I can't see "Tree with nested nodes, using childAccessor" anywhere at all. I can only see "Tree with nested nodes" which is still using the treeControl.

https://material.angular.io/components/tree/examples

I've even looked at RC and Next version of the docs and can't see it there either. Is there another version I should be looking at?

**Comment by chrissena** [comment]
Oh wait, I’ve just realized that the new examples are actually on the CDK Tree page in the CDK section of the docs: https://material.angular.io/cdk/tree/examples. It seems like an oversight that these haven’t been updated in the main components section.

I hadn’t thought to check the CDK docs, and I’m sure many others might do the same, only finding examples with the deprecated API.

It would be great if the main components section could also be updated to include the new examples and avoid confusion.

**Comment by Farbfetzen** [comment]
Sorry, I was referring to https://material.angular.io/cdk/tree/examples. The components and the cdk have similar looking documentation which confuses me sometimes.

**Comment by harish8895** [comment]
Well, I am trying to work with a child accessor but I am confused about how to expand particular nodes or expand decedents manually earlier it was like tree control. expand(node) or tree control. expand decedents (node).

**Comment by crisbeto** [comment]
Fixed by #29752.
