### ISSUE TITLE
Table ... click on element in a cell, also click on the row

### ISSUE THREAD

**Issue by jeffschulzusc** [angular/components#29629]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular Material Table ... at least v16 -> v18 

if you have <tr (click)="_selectrow()" ..> for example, then click element in <td><span>hello</span></td> and the click event propagates to the row ... so for example you can not select text for copy without also clicking the row 

### Reproduction

https://v16.material.angular.io/components/table/examples
"Binding event handlers and properties to the table rows."
Try to select text in a cell, you can not do it without the row click firing and you see in Click Log.

### Expected Behavior

Expected that an element in a <td> shall act as if pointer-events: all at a z-index grater than the <tr>

### Actual Behavior

Click on element in <td> also clicks the <tr>

### Environment

```
Node   : 21.5.0
OS     : darwin-arm64
yarn   : 1.22.21

nx (global)        : 18.0.6
nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/angular        : 18.0.6
@nx/cypress        : 18.0.6
@nx/devkit         : 18.0.6
@nrwl/devkit       : 15.8.5
@nx/eslint-plugin  : 18.0.6
@nx/nest           : 18.0.6
@nx/node           : 18.0.6
@nrwl/tao          : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
nx-cloud           : 18.0.0
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ngneat/transloco    : 6.0.4
@ngrx/effects        : 17.0.1
@ngrx/entity         : 17.0.1
@ngrx/router-store   : 17.0.1
@ngrx/schematics     : 17.0.1
@ngrx/signals        : 17.0.1
@ngrx/store          : 17.0.1
@ngrx/store-devtools : 17.0.1
@nx-dotnet/core      : 1.22.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@15.8.5
```

**Comment by crisbeto** [comment]
This is how event bubbling works in the browser: an event happening on an element also gets dispatched on its ancestors. You can stop the event from bubbling up by adding `$event.stopPropagation()` to the inner event.

**Comment by jeffschulzusc** [comment]
yes, sorry, is not a bug but a feature request ... it would be difficult to achieve maybe ?
i can stop propagation, but still if i mouse-down on my cell text, for example, but when i mouse-up say a few pixels outside of the text, then it counts as a click on the row ...
