### ISSUE TITLE
docs-bug(COMPONENT): Converting all examples to  Stackblitz makes things less intuitive

### ISSUE THREAD

**Issue by dataminion** [angular/components#29637]
### Documentation Feedback

I can't speak for others but any time I try to load a  Stackblitz example it takes at least 5 minutes and most of the time they fail. 

I just want to make sure I am using the right selector for the spinner or fab button I want it feels like things shouldnt be this hard

### Affected documentation page

https://material.angular.io/components/progress-spinner/examples

**Comment by crisbeto** [comment]
I completely agree that Stackblitz is way too slow as it is right now. When we first introduced it, it was taking less than a minute to completely boot up. 

For what it's worth, you can see the source code for each example by clicking on this button:
<img width="987" alt="image" src="https://github.com/user-attachments/assets/44b6a122-2e31-4211-a811-b6a05fc66547">

**Comment by crisbeto** [comment]
Fixed by https://github.com/angular/material.angular.io/pull/1268.

**Comment by dataminion** [comment]
Much love @crisbeto <3 I was sure this one would languish...

I have been using mat components in angular projects since before the typescript version even began I know almost all the selectors by heart but for some reason when I am designing I just like going back to the docs and looking at how the buttons render... its an irrational practice given all the other design tools our team uses.

Thanks so much!

**Comment by dataminion** [comment]
one wonders if commiting the cardinal sin of commiting the minified build to a repo somewhere  so that it could skip running npm install on page load might make the quick getting into it experience more smooth
