### ISSUE TITLE
bug(MatFlatButton): Button should be disabled if variable value is true

### ISSUE THREAD

**Issue by adamwoxsoft** [angular/components#29631]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Form validation returns true, but button is getting active (enabled)

### Reproduction

When you select an operator a button is getting enabled but `frmAuth.invalid` is `true` so it should be disabled.
[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-c1gqx3?file=src%2Fmain.ts)

### Expected Behavior

[disabled]="true" should be disabled

### Actual Behavior

[disabled]="true" is making button enabled/active

### Environment

Angular CLI: 18.1.4
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.1.4
@angular-devkit/schematics      18.1.4
@schematics/angular             18.1.4
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by crisbeto** [comment]
Are you sure that the form is actually invalid? I tweaked your example here to output the invalid state inside the button as well and it seems to work as expected: https://stackblitz.com/edit/stackblitz-starters-m34qxo?file=src%2Fmain.ts

**Comment by adamwoxsoft** [comment]
There is a console.log in `this.f.login.valueChanges.subscribe()`, why is there `true`, but UI shows `false`? 🤔😱
![Zrzut ekranu 2024-08-23 125828](https://github.com/user-attachments/assets/4a945f52-fcec-48cc-ac7d-6cb64b9c1380)

**Comment by crisbeto** [comment]
It sounds like change detection hasn't run so the value isn't reflected in the UI yet. You should be able to add a `changeDetectorRef.markForCheck` somewhere to get it to work. Either way, this seems like an issue with the app rather than the Material button.
