### ISSUE TITLE
md-hint add color property

### ISSUE THREAD

**Issue by tydanielson** [angular/components#2965]
This is a feature.  It would be really nice to use the color property like on `md-button` to determine which hints are warnings, accents or primary etc...  I'm using the hints for both showing validation errors and anything related to the users input.

**Comment by sumpton** [comment]
```<md-text>``` would be a terrific addition to work along with ```<md-hint>```

I have been refactoring hundreds of Bootstrap 4 fields to Material 2, and I appreciate ```<md-hint>``` very much. The positioning is also very useful.

But for validation messages I have been moving ```<div>``` out of the form-control, and wish there was a more direct and elegant Material component for Bootstrap's ```<... class="form-text">``` that could be used for all the form components.

**Comment by DevVersion** [comment]
Good idea. While I was thinking about the `color` property on `md-hint` I noticed that we often repeat the same logic to apply the color classes. 

A good solution would be having a directive that is responsible for the color classes. Need to discuss first.

**Comment by gvlekke** [comment]
I think it's also good to have a color on md-hint, but I think its better that you can set a error color to the input container and that material2 itself take that color and put in on the hint and the md-input-underline. 

For now I'm creating a css file that does that based on the ng-dirty and ng-invalid classes.

```
md-hint
  font-weight: lighter
  color: #A1A1A1

md-input-container.ng-dirty.ng-invalid
  .md-input-underline
    border-top-width: 2px
    border-color: #D50000

    .md-input-ripple
      background-color: #D50000

  md-hint
    color: #D50000
```

should i create a new issue: "add error styling to inputs" ?

**Comment by JoshMarler** [comment]
@gvlekke I agree with this being a good idea. Thanks for the css snippet. Helped me style my validation in the manner I required. Spent longer than I care to admit messing around having missed ng-dirty / ng-invalid overrides...

For those interested as of 2.4.6 relevant css is: 

```
md-input-container.ng-touched.ng-invalid {

  .mat-input-placeholder {
    color: red;
  }

  .mat-input-underline {
    border-top-width: 2px;
    border-color: red;
  }

  .mat-input-ripple {
    background-color: red;
  }

  md-hint {
    color: red;
  }
}
```

**Comment by kamarouski** [comment]
Out of the box styling solution for invalid inputs and error messages would be great. 

Color property for md-hint would definitely help a lot as everybody now need to write custom css to achieve this common task. Or maybe a separate md-error component.

Hopefully this will be considered before final release.

**Comment by niwrA** [comment]
I currently don't use any forms, just md-inputs (all inputs are hooked up to immediate updates on blur to the backend), and the first thing I did was try to add a color property to md-hint, so it certainly would feel a natural solution. Alternatively following the standard ng-dirty etc. would be great too of course.

**Comment by mmalerba** [comment]
This isn't something that's in the Material Design spec and we already have mat-error for showing error color messages. I don't think its a feature we'll add, though it should be easy enough for users to add by using CSS and Angular Material's theming system (see https://material.angular.io/guide/theming-your-components)
