### ISSUE TITLE
docs-bug(Button): Add to docs that buttons now need matRipple

### ISSUE THREAD

**Issue by e-oz** [angular/components#29670]
### Documentation Feedback

After 19.0.0-next.2, buttons lost default ripples, and now every button needs to be edited (add matRipple) if we want to keep the existing behavior.
I don't know if you will create a migration for this, but I think it's worth mentioning in the docs.
Same about checkboxes and chips.

### Affected documentation page

https://next.material.angular.io/components/button/overview

**Comment by crisbeto** [comment]
The ripples should still be there, we just stopped exposing the `MatRipple` instance as a public API. Here's an example that the ripples are still there:

https://github.com/user-attachments/assets/5e68448a-93e1-427a-b01e-10d291f6c378

**Comment by e-oz** [comment]
No, the ripples are gone. The example in docs is incorrect - try to open it in StackBlitz and you'll see that ripples are gone.

**Comment by crisbeto** [comment]
Hmm, I suspect that the Stackblitz template might be incorrect. Will take a look.

**Comment by e-oz** [comment]
I saw it in my app too, so I think StackBlitz is correct :)

**Comment by Totati** [comment]
https://github.dev/angular/components/blob/5bd5be60a2ba8d263ec71bec69d1e14a9bf6ffe2/src/material/core/private/ripple-loader.ts#L187
`MatRippleLoader` calls the `RippleRenderer` constructor without the injector. So when no direct `matRipple` is used, ripple classes are missing. Adding a matRipple to a button (or anywhere) fixes every button.

**Comment by crisbeto** [comment]
Yep, just sent a fix at #29672. There's an additional issue with the checkbox that also had to be addressed.
