### ISSUE TITLE
bug(mat-tab): mat tab content not visible if tab is switched during animation of parent div

### ISSUE THREAD

**Issue by iFederx** [angular/components#29687]
### Description

If you have a div animated that contains a mat-tab-group and you change tab during parent div's animation, the tab content will be invisible.
Last version tested: angular 16.2.1. I down't know if the issue is still present in 17+ versions

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-5papgq?file=src%2Fapp%2Fapp.component.ts
Steps to reproduce: change tab during animation

### Expected Behavior

I expect that changing tab during animation (also via ts code), will not break mat tabs.

### Actual Behavior

 after animation is finished, tab content will be invisible

### Environment

- Angular: 16.2.1
- CDK/Material: 16.2.1
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Closing since this is using a really old version of Material that is out of LTS by now.

**Comment by iFederx** [comment]
In this Angular v18 updated Stackblitz, you can see that the issue is already present:
https://stackblitz.com/~/github.com/iFederx/bug-tabs-example

**Comment by crisbeto** [comment]
I suspect this is the same root cause as #16230. Closing and I bumped the priority on #16230.
