### ISSUE TITLE
Feature request: md-slider - provide a mechanism for keeping the slider bubble always in the activated state

### ISSUE THREAD

**Issue by Mufasa** [angular/components#2969]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like the md-slider bubble to remain in its active state (i.e. the behaviour when it gets focus where it shows the currently selected value inside the bubble and the bubble appears a little larger).

#### What is the current behavior?
When md-slider loses focus then the bubble drops back down to a round ball without any indication of the currently selected value.

#### What are the steps to reproduce?
Just place an md-slider on your form and observe this behaviour.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
I don't think this is necessary as you can observe the current behaviour here:
https://material.angular.io/components/component/slider 

#### What is the use-case or motivation for changing an existing behavior?
At the moment I need to add another component near my md-slider to indicate to the user what value they have selected.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
No

**Comment by sumpton** [comment]
Would be great! This would relate to the "read only" option in the Angular 1 version.

> https://material.angularjs.org/latest/demo/slider

**Comment by mmalerba** [comment]
It's not part of the spec, but it does seem like a reasonable addition. Will talk to Jeremy about it when he's back from vacation.

**Comment by anselpeters** [comment]
any update on this?  i thought it was odd that a slider would be considered "inactive" if it were at the minimum value.

**Comment by mmalerba** [comment]
@anselpeters that's not what this issue is about, the minimum value state is WAI and follows the mocks: https://material.io/guidelines/components/sliders.html#sliders-discrete-slider

**Comment by paulwalker** [comment]
Can someone in the know perhaps paste some override css for now to always display the bubble? Thanks very much if so.

**Comment by wulfsberg** [comment]
@anselpeters @mmalerba The "minimum value is inactive" is a rather nonsensical quirk in the original spec, and has been changed.
Should the slider include an "appearance" parameter to flip between legacy and "new spec" look, like that mat-form-fields have? (And should that be a separate issue, or is it so closely related to this that it makes sense to handle it as one).

**Comment by mmalerba** [comment]
The slider should be updated to reflect the most recent version of the spec. I think it's probably similar enough that we only need one version of it though

**Comment by zsiegel92** [comment]
@wulfsberg @mmalerba @anselpeters +1 for removing the mat-slider-min-value styles! It makes it look disabled and, to me, seems like an accessibility _issue_ rather than an accessibility _feature_.

**Comment by nylocx** [comment]
Still nothing on that, I'm pretty new to Angular but it would be nice if someone could post a CSS hack to fix (means remove) the "mat-slider-min-value" style.

**Comment by jelbourn** [comment]
(revisiting old feature requests)

Closing this since I don't see us ever adding an API for this. We're moving towards basing our components on top of MDC Web, which pretty strictly adheres to the Material Design spec, which doesn't have this in its guidance.
