### ISSUE TITLE
bug(COMPONENT): mat-slider freezes after initial vertical movement on touch device

### ISSUE THREAD

**Issue by therlaup** [angular/components#29706]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

I am working on an app that requires a vertical slider. I use CSS to achieve a vertical slider using mat-slider despite it not being supported since v15. This works perfectly on a device with a mouse. However, when using the app on Android, dragging the sliders becomes frozen if the initial translation direction is vertical. Please see the video for an example.

https://github.com/user-attachments/assets/5d776a4a-41d6-42e1-a7be-2ad137d55779

### Reproduction

StackBlitz link: https://components-issue-dcm346.stackblitz.io
StackBlitz editor: https://stackblitz.com/edit/components-issue-dcm346?file=src%2Fapp%2Fexample-component.html
Steps to reproduce:
1. In Chrome, open dev console and activate device toolbar (Ctrl+ Shift+ M). Select a touch device.
2. Drag the sliders thumb first perpendicular to the track then parallel to the track.
3. On touch device: If the drag direction is initially vertical, then the slider becomes frozen and no additional movement is allowed. (unexpected behavior)
4. On mouse device: If the drag direction is initially vertical, then the slider still freely moves. (expected behavior)

### Expected Behavior

On touch devices, if the drag movement is initially vertical, the slider thumb should move according to translation parallel to the track.

### Actual Behavior

On touch devices, if the drag movement is initially vertical, the slider thumb becomes frozen to translation parallel to the track.

### Environment

- Angular: 18.2.2
- CDK/Material: 18.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by crisbeto** [comment]
Closing since the vertical slider isn't officially supported. We would accept a PR if it doesn't require a large rework of the component.
