### ISSUE TITLE
Adding markers to a map in Angular 2 using ngOnInit after initialization

### ISSUE THREAD

**Issue by typescripterpro** [angular/components#29702]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Embarking on my Angular journey by creating a sample app incorporating GoogleMaps.

```
import { Component, Input, OnInit, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormControl } from '@angular/forms';
import Appcomponent = require("../app.component");
import Accident = Appcomponent.Accident;
declare var google: any;
declare let map: any

@Component({
  selector: 'app-map',
  templateUrl: 'map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {

  private http: HttpClient;
  private baseUrl: string;

  private tags: string[];
  private accidents: Accident[];
  private accidentsMarkers: any[] = [];
  private markers: any[] = [];

  constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string) {
    this.http = http;
    this.baseUrl = baseUrl;
  }

  ngOnInit() {
    var mapProp = {
      center: new google.maps.LatLng(51.508742, -0.120850),
      zoom: 5,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
  }


  public loadAccidents(): void {
    this.http.get<Accident[]>(this.baseUrl + 'api/accidents').subscribe(result => {
      this.accidents = result;

      this.accidents.forEach(function (accident) {
        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(accident.location.coordinates.lat,
            accident.location.coordinates.lon),
          map: this.map,
          title: ""
        });
        this.markers.push(marker);
      });
    }, error => console.error(error));    
  }
}

```

### Same 

https://qanswer.space/questions/adding-markers-to-a-map-in-angular-2-using-ngoninit-after-initialization

### Actual Behavior

While I initialized map in ngOnInit, attempting to access it in loadAccidents results in an error message:

`ERROR TypeError: Cannot read property 'markers' of undefined`

The order of execution suggests that the constructor is called prior to ngOnInit. Considering this, I believe map should have been defined already.

### Expected Behavior

Is there an improved method to integrate Google Maps into an Angular application? Or is there something flawed in my approach?

### Environment

Angular

**Comment by crisbeto** [comment]
Closing since you're managing Google Maps yourself, whereas this repository is about the [Angular wrapper](https://github.com/angular/components/tree/main/src/google-maps) around the Google Maps API.
