### ISSUE TITLE
bug(CdkDialog): Can't Resolve DI for Injectable({}) service

### ISSUE THREAD

**Issue by Ezazhel** [angular/components#29717]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I use a service not provided in 'root', CdkDialog doesn't resolve providers from "parent" component.

This work well with MatDialog, but I'm trying to switch from MatDialog to Cdk

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-gp7hqz?file=src%2Fmain.ts
Steps to reproduce: 
1. Create a service not provided in 'root'
2. Create a modal-component use the service
3. Provide the service in the modal-container
4. Use Cdk/Dialog to open a new dialog from the modal-container
5. Check the console : R3InjectorError(Environment Injector)[_TestService -> _TestService]: 
  NullInjectorError: No provider for _TestService!

### Expected Behavior

D.I should work based on viewContainer. 
If we use a functional service, we could provide it in the modal-component, but if our service has other dependencies it won't work.

### Actual Behavior

This config : 
```
this.dialog.open(ModalComponent, {
            data: '...',
            injector: this.injector
        });
```
doesn't work
```
this.dialog.open(ModalComponent, {
            data: '...',
            viewContainerRef: this.viewContainerRef
        });
```
doesn't work too

```
this.dialog.open(ModalComponent, {
            data: '...',
            componentFactoryResolver: this.injector.get(ComponentFactoryResolver)
        });       
```
This does work, but it's bothersome

### Environment

- Angular: >= 16.x.x
- CDK/Material: >= 16.x.x
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by crisbeto** [comment]
You might have to add the CDK `Dialog` service to the `providers` array of your module. Either way, the service is `providedIn: 'root'` so that it works better with standalone.
