### ISSUE TITLE
feat(mat-select): Allow to enter custom value

### ISSUE THREAD

**Issue by csaikiran569** [angular/components#29729]
### Feature Description

Is there a way to enter custom value in the mat-select .

### Use Case

I have a use case to allow user to enter a custom value and also select a value from dropdown .

I did spent a lot of time to find a solution for this .I apologize if this feature is available .Please do let me know if this feature is available or can be added if it is not available ?

For now as a work around I actually added an option as "Other" if user selects that option I was showing a input box to enter the value .
![image](https://github.com/user-attachments/assets/d00bea5f-0d4e-41d1-9d98-dad71a929a8d)

**Comment by crisbeto** [comment]
This sounds like `mat-autocomplete`: https://material.angular.io/components/autocomplete/overview
