### ISSUE TITLE
bug(Tooltip): Missing word-break Design Token for Tooltips that was present in 18.0.2

### ISSUE THREAD

**Issue by Mystic-SAM** [angular/components#29732]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.0.2

### Description

In Angular Material version 18.0.2, a design token for word-break (**_--mdc-tooltip-word-break_**) was available and used for styling tooltips. However, this token appears to be missing in the latest version 18.2.3.

Details:
Version Affected: Angular Material 18.2.3
Impact: The absence of the word-break token affects how text overflow is handled in tooltips, potentially leading to layout issues or text being cut off incorrectly.

Currently, there is no way to modify certain properties of tooltips, such as word-break or max-width. Even when applying a custom class using matTooltipClass, the class is applied to the parent element, whereas these properties need to be applied to the element that actually contains the text to achieve the desired effects.

Below is the structure of the tooltip rendered in HTML:
![image](https://github.com/user-attachments/assets/f1684272-a79c-4b66-9c82-2dea8d80ffce)

### Reproduction

1. Upgrade Angular Material from version 18.0.2 to 18.2.3.
2. Observe the tooltip component's behavior regarding text overflow and wrapping.
3. Inspect the styles and tokens being used in developer tools.

### Expected Behavior

The **--mdc-tooltip-word-break** token should be available and functional in version 18.2.3, providing consistent behavior with previous versions, for tooltip components.

This screenshot below shows the token used for word-break in Angular Material version 18.0.2
![image](https://github.com/user-attachments/assets/4b65fc38-d06a-4d09-a3ce-179cbaf9a410)

### Actual Behavior

The token for word-break is not available anymore and there is no way to modify the word-break property in tooltip.

The screenshot below shows the styles applied to Tooltip in Angular Material version 18.2.3
![image](https://github.com/user-attachments/assets/49865007-a697-4a80-a3eb-31264ab55075)

### Environment

- Angular: 18.2.3
- CDK/Material: 18.2.3
- Browser(s): Chrome Version 128.0.6613.138
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The token wasn't exposed intentionally so that's why we removed it. You can still achieve the same with a custom class and targeting the child element, e.g. `.custom-class .mat-mdc-tooltip-surface { word-break: all }`.

**Comment by Mystic-SAM** [comment]
> The token wasn't exposed intentionally so that's why we removed it. You can still achieve the same with a custom class and targeting the child element, e.g. `.custom-class .mat-mdc-tooltip-surface { word-break: all }`.

@crisbeto Thank you for the clarification! I have a couple of follow-up questions:

1. Is it advisable to use internal Material class selectors for styling customizations? How stable are these classes, and what issues might I encounter with future upgrades if I rely on them? I understand that internal classes can change, which could affect my implementation.
2. Additionally, it would be really helpful if you could provide a list of all the available tokens and their stability.

Thanks for your assistance!

**Comment by crisbeto** [comment]
1. We have had cases in the past where we changed the classes, but they're mostly stabilized by now so I don't expect them to change unless there's a big rewrite.
2. There are a lot of tokens so it wouldn't be practical to list them all out here, but you can see them in your generated theme file. We're currently working on simplifying the theming system so it's based on a set of 15ish system tokens so the overrides are easier.
