### ISSUE TITLE
feat(google-maps/map-advanced-marker): Add support for some mouse events

### ISSUE THREAD

**Issue by vinlos** [angular/components#29741]
### Feature Description

`map-advanced-marker`, is missing support for mouse events:
* double click
* mouse out
* mouse over
* mouse up
* right click

It would really be great to implement those events to fill the gap with the [deprecated](https://developers.google.com/maps/deprecations#googlemapsmarker_in_the_deprecated_as_of_february_2024) `map-marker` component.

### Use Case

* display an info window while cursor is over a marker
* trigger any kind of event while cursor is over or out the marker
* trigger any kind of event after double clicking the cursor
* properly migrate components using [deprecated](https://developers.google.com/maps/deprecations#googlemapsmarker_in_the_deprecated_as_of_february_2024) `map-marker` which made use of those events

**Comment by vinlos** [comment]
thank you for creating and merging the PR so quickly

**Comment by crisbeto** [comment]
Fixed by #29747.
