### ISSUE TITLE
bug(matMenu): panelClass has no effect

### ISSUE THREAD

**Issue by e-oz** [angular/components#29761]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Was panelClass removed from mat-menu or did I apply it somehow wrong?
https://stackblitz.com/edit/rzed9a?file=src%2Fexample%2Fmenu-icons-example.html

### Reproduction

StackBlitz link: https://stackblitz.com/edit/rzed9a?file=src%2Fexample%2Fmenu-icons-example.html
Steps to reproduce:
1. Create rule `.test  {color: red !important}`
2. Create <mat-menu panelClass="test">

### Expected Behavior

Expected what is promised in docs :)

### Actual Behavior

Input is ignored like it doesn't exist

### Environment

- Angular: 19
- CDK/Material: 19
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): my OS

**Comment by e-oz** [comment]
I guess it was removed, and now setting "class" gives the same effect.

**Comment by crisbeto** [comment]
The public name has been `class` ever since we introduced the menu years ago. Maybe previously it was also exposed as `panelClass` by accident?

**Comment by e-oz** [comment]
Looks like I didn't read the alias. Sorry!
