### ISSUE TITLE
google.maps.importLibrary Not Working in Firefox Private Window

### ISSUE THREAD

**Issue by Urvishdudhagara** [angular/components#29787]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

 When opening the application for the first time in a Firefox private window, the following error is thrown:
 
 ERROR TypeError: google.maps.importLibrary is not a function
 
 This issue occurs consistently in Firefox's private mode but seems to work fine in other browsers and regular Firefox windows.

### Reproduction

- Open Firefox in private mode.
- Navigate to the application that uses google.maps.importLibrary for loading Google Maps libraries.
- Observe the error in the console.

### Expected Behavior

google.maps.importLibrary should work in Firefox private mode, and Google Maps libraries should load -without throwing an error.

### Actual Behavior

The function google.maps.importLibrary is not recognised, leading to a TypeError.

### Environment

Browser: Firefox (Private Mode)
Google Maps API version: [provide your version here]
Angular version: [provide your Angular version here]
Operating System: [provide OS details]
Additional Information:

**Comment by crisbeto** [comment]
It works for me against our dev app which is based on `importLibrary` so this is likely an issue on your end or in the Google Maps API. Either way we can't do much about it so I'm closing the issue.
<img width="811" alt="image" src="https://github.com/user-attachments/assets/1e7cf36f-1f27-466b-ad8a-f7aaf4ad6553">
