### ISSUE TITLE
bug(TREE): Tree with nested nodes renders child-nodes twice with new childrenAccessor

### ISSUE THREAD

**Issue by BeniFreitag** [angular/components#29808]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 18.1 or 18.2.6 with the deprecated NestedTreeControl.

### Description

Tree with nested nodes (childrenAccessor) renders child-nodes twice, when there's are items having no children.

![image](https://github.com/user-attachments/assets/b1d54257-7c4a-4684-ab07-a7342ba4ba8d)

### Reproduction

[StackBlitz link](https://stackblitz.com/edit/angular18-tree-duplicates?file=src%2Fexample%2Ftree-nested-child-accessor-overview-example.ts)
Steps to reproduce:
1. start with this example: [Tree with nested nodes (childrenAccessor)](https://material.angular.io/components/tree/examples#tree-nested-child-accessor-overview)
2. add a new item at the **beginning** of the datasource, having no children (e.g. ```{ name: 'Sample' }```)
3. expand _Fruit_ or _Vegetables_, the children are rendered twice.

### Expected Behavior

Child nodes should be rendered once.

### Actual Behavior

Child nodes are rendered twice.

### Additional Information
Only occours when using the new childrenAccessor in Angular 18.2. It workes with the depricated NestedTreeControl.

### Environment

- Angular: 18.2.6
- CDK/Material: 18.2.6
- Browser(s): Chrome 129
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by wagnermaciel** [comment]
This appears to be fixed in our latest version `18.2.9`

https://stackblitz.com/edit/qbsqut?file=src%2Fexample%2Ftree-flat-child-accessor-overview-example.ts
