### ISSUE TITLE
bug(mat-from-field): Remove the border for the input.

### ISSUE THREAD

**Issue by vejandla** [angular/components#29810]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

7.0

### Description

with angular material 7.0, mat-form-field used to have `appearance="none"` option, which would remove the border. But with angular material v 18, appearance none option is not supported anymore and also there is a no way (I could not find a way) or simply so hard to override these style. 

Appreciate any help.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/6whk1w?file=src%2Fexample%2Finput-overview-example.html
Steps to reproduce:
1. 
2.

### Expected Behavior

Borders for input fields should be hidden.

### Actual Behavior

borders are still showing.

### Environment

- Angular: V18
- CDK/Material: V18
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by sOnU1002** [comment]
i would like to work on it please assign me this task

**Comment by sOnU1002** [comment]
u need to assign the issue to me

**Comment by crisbeto** [comment]
We don't support `appearance="none"`, because it somewhat defeats the purpose of having the form field there. That being said, you should be able to get it by overriding the token values. E.g. for the border specifically you can set `--mdc-outlined-text-field-outline-color: transparent`.
