### ISSUE TITLE
feat(icon): add support for viewbox size when registering an svg iconset

### ISSUE THREAD

**Issue by alirezamirian** [angular/components#2981]
angular material v1.x [supports viewbox size][1] and it's necessary for arbitrary icon sets.

[1]: https://material.angularjs.org/latest/api/service/$mdIconProvider#mdiconprovider-icon-id-url-viewboxsize

**Comment by rishabhmhjn** [comment]
+1

**Comment by zeddever** [comment]
This requires changing the line:
https://github.com/angular/material2/blob/9062640b9a1ff98432218fc8ec59332ff154e781/src/lib/icon/icon-registry.ts#L466

to the code below:
`
const svgNode = this._setSvgAttributes(this._toSvgElement(iconElement));
if (iconElement.hasAttribute('viewBox') && !svgNode.hasAttribute('viewBox')) {
    svgNode.setAttribute('viewBox', iconElement.getAttribute('viewBox'));
}
return svgNode;
`
