### ISSUE TITLE
bug(COMPONENT): Angular mat-form-field not working properly - mdc-notched-outline__notch shows overlapping border

### ISSUE THREAD

**Issue by tp1906** [angular/components#29821]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I recently install angular material and when I use mat-form-field it displays a top/bottom overlapping border.  I believe the mdc-notched-outline__notch class is conflicting with something. If I remove the border it will have a gap in the form field border. Any suggestions on how to fix?

![Image](https://github.com/user-attachments/assets/b518412f-32b8-4490-bc08-1833c7925e47)

I added the following to global styles but it adds a blank gap in the border of the form field.

.mat-mdc-form-field.mat-mdc-form-field.mat-mdc-form-field.mat-mdc-form-field.mat-mdc-form-field .mdc-notched-outline__notch { border-style: hidden; }

![Image](https://github.com/user-attachments/assets/e9e75d95-ea0b-42b7-be8f-7289c6c27e8d)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

I'm expecting it to look and work like the examples in the documentation.

### Actual Behavior

Overlapping border on mat-form-field.

### Environment

- Angular: 18.0.7
- CDK/Material: 18.2.6
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
- Bootstrap: 5.3.3

**Comment by crisbeto** [comment]
I suspect this is the same root cause as https://github.com/angular/components/issues/28404.
