### ISSUE TITLE
docs-bug(common): The way deprecated symbols are rendered

### ISSUE THREAD

**Issue by moniuch** [angular/components#29839]
### Documentation Feedback

The docs for material have a general problem with deprecated symbols.
Here is just an example of *TreeControl

1. The word **Deprecated** on hover suggests through the question mark that there is some explanation behind it (which there is when you look into the TS code), but nothing happens either on hover or on click [it was impossible to capture that cursor in the screenshot]
2. I think for the sake of clarity, the name of a deprecated symbol should be style using strikethrough, and the explanation + suggestions what to use should immediately follow it, even before the old description. Currently the styling of the Deprecated word doesn't really stand out as much as it should, blends into the body text, IMO. 

![Image](https://github.com/user-attachments/assets/bd2fcfde-a218-4c57-ae08-b0f923bb7308)

### Affected documentation page

https://material.angular.io/cdk/tree/api#BaseTreeControl

**Comment by naaajii** [comment]
it shows a little popup saying when it will be deprecated on hover.

![Image](https://github.com/user-attachments/assets/005a7b4f-87dd-4d20-b4c7-bf0ae9cfb2d8)
