### ISSUE TITLE
Chips: disabled chips is receiving focus

### ISSUE THREAD

**Issue by naiduraa** [angular/components#29855]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

<mat-chip-listbox aria-label="Fish selection">
  <mat-chip-option>One fish</mat-chip-option>
  <mat-chip-option>Two fish</mat-chip-option>
  <mat-chip-option>Three fish</mat-chip-option>
  <mat-chip-option disabled>Four fish</mat-chip-option>
</mat-chip-listbox>

The disabled chips receives focus

### Reproduction

StackBlitz link: https://stackblitz.com/edit/xbnwf3?file=src%2Fexample%2Fchips-overview-example.html
Steps to reproduce:
1. Focus using tabs and see the disabled chips receives focus

### Expected Behavior

Disabled chips should not receives any focus

### Actual Behavior

Disabled chips receives any focus

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is working as expected. If focus skipped over the disabled chip, the user might not be aware that it exists. The disabled state is communicated through `aria-disabled`.
