### ISSUE TITLE
bug(YouTubePlayer): startSeconds and ready not working

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#29874]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

```
<youtube-player width="256" height="144" videoId="mVjYG9TSN88" [startSeconds]="5" (ready)="ready = true" (stateChange)="stateChange = true"/>
<p>{{ ready }}</p> 
<p>{{ stateChange }}</p>
```

![Image](https://github.com/user-attachments/assets/fe5d81c5-25e0-4430-b0c4-1e4a9653aec0)

[startSeconds] no function
(ready) no call

### Reproduction

git clone https://github.com/keatkeat87/ng-mat-youtube-start-time-issue
click and play the video

### Expected Behavior

1. the video should start at 5 seconds
2. the (ready) should emit

### Actual Behavior

1. the vide start at 0 second
2. the (ready) no emit 

### Environment

Angular CLI: 18.2.8
Node: 20.11.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 18.2.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.8
@angular-devkit/build-angular   18.2.8
@angular-devkit/core            18.2.8
@angular-devkit/schematics      18.2.8
@schematics/angular             18.2.8
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by crisbeto** [comment]
I suspect that this is an issue only with the placeholder behavior. As a workaround until it gets fixed, you can try setting `disablePlaceholder="true"`.
