### ISSUE TITLE
bug(MatRipple): MatRipple triggers on MatButton even with disableRipple set to true

### ISSUE THREAD

**Issue by PrathameshPatki** [angular/components#29880]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`MatButton` attribute `disableRipple` does not stop ripple from being triggered on the base button. The attribute `mat-ripple-loader-disabled` does appear on the button, but doesn't appear to have an effect.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-cqz4c2
Steps to reproduce:
1. Hover over or click on the base button "Test Button"
2. Ripple shows on the button

### Expected Behavior

As the `disableRipple` directive is set to `true`, the ripple should not appear on hover or click.

### Actual Behavior

Hover over or click on the button creates a ripple.

### Environment

- Angular: 18.2.2
- CDK/Material: 18.2.2
- Browser(s): Chrome v129
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Sequoia (15.0.1)

**Comment by PrathameshPatki** [comment]
I tested this using the dev-app locally, using v18.2.2. I see it there, too.

**Comment by crisbeto** [comment]
The ripple here is the one that happens on clicks, the hover/focus overlay can't be disabled because it's necessary for accessibility. You can hide it yourself by setting `.mat-mdc-button-persistent-ripple {display: none}`.

**Comment by PrathameshPatki** [comment]
Thanks
