### ISSUE TITLE
bug(MatAnchor): disabledInteractive not correctly applied

### ISSUE THREAD

**Issue by caleniuc** [angular/components#29882]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`MAT_ANCHOR_HOST` applies `aria-disabled` differently than `MAT_BUTTON_HOST`. On the anchor, `aria-disabled` is applied the same as `disabled`, so `disabledInteractive` has no effect on it.

Is this intended? I'd expect to be able to navigate via keyboard even on `<a>` buttons, if `disabledInteractive` and `disabled` are set.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/soecj6?file=src%2Fexample%2Fbutton-overview-example.html
Steps to reproduce:
1. Try to navigate via keyboard to the two buttons
2. Notice that only `<button>` is reachable, while `<a>` is not

### Expected Behavior

`<a>` button is reachable via keyboard if `disabledInteractive` is set and the button is `disabled`. - `aria-disabled` is applied on them, like on `<button>`

### Actual Behavior

`<a>` button is not reachable via keyboard if `disabledInteractive` is set and the button is `disabled`.

### Environment

- Angular: v18, v19.0.0-next.2
- CDK/Material: v18, v19.0.0-next.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by caleniuc** [comment]
The tab navigation issue probably is due to the default tabindex of an `<a>` that does not have a `href`. 
But still, we'd expect to have an `aria-disabled` in this case for screen readers, so they can identify it as disabled.

**Comment by crisbeto** [comment]
You're right that it's because of the lack of `href` https://stackblitz.com/edit/soecj6-g2sfu3?file=src%2Fexample%2Fbutton-overview-example.html. I don't think there's a way we can work around it, because even with `tabindex="0"` the browser doesn't allow tabbing to the anchor without an `href`. I'm closing the issue since omitting the `href` is invalid anyways.
