### ISSUE TITLE
standalone missing: stackBlitz example page

### ISSUE THREAD

**Issue by Gopi7a** [angular/components#29896]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

Once we click the stackBlitz link from the Angular Material page, showing error like  "error NG2010: 'imports' is only valid on a component that is standalone."
All the sample code in the stackBlitz missing **standalone: true** in @Component decorator.

Checked version 18+

Angular Material team, need to fix it.

### Reproduction

StackBlitz link: https://stackblitz.com/run?file=.gitignore

Steps to reproduce:
1. Go to Angular Material page
2. Select any components like Stepper, SideNav
3. Go To Example tab, open any of the StackBlitz link from example.
4. After loading the module, you will get an error like  "error NG2010: 'imports' is only valid on a component that is standalone."

To fix it,
need to add **standalone: true** in @Component decorator.

### Expected Behavior

Add the **standalone: true** in @Component decorator and should run the example code in StackBlitz without an error.

### Actual Behavior

After loading the module in StackBlitz example, you will get an error like  "error NG2010: 'imports' is only valid on a component that is standalone."

### Environment

- Angular: 18+
- CDK/Material: Angular Material StackBlitz
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by Gopi7a** [comment]
https://d9vazd.stackblitz.io

**Comment by crisbeto** [comment]
Should be fixed now by https://github.com/angular/material.angular.io/pull/1277.

**Comment by Gopi7a** [comment]
Thank you for resolving the issue.
