### ISSUE TITLE
Typo in function comment

### ISSUE THREAD

**Issue by FlorinCiocirlan** [angular/components#29926]
There is a typo in file _**[components](https://github.com/angular/components/tree/main)/[src](https://github.com/angular/components/tree/main/src)/[cdk](https://github.com/angular/components/tree/main/src/cdk)/[schematics](https://github.com/angular/components/tree/main/src/cdk/schematics)/[update-tool](https://github.com/angular/components/tree/main/src/cdk/schematics/update-tool)/index.ts**_

/**
   * Creates a program **_form_** the specified tsconfig and patches the host
   * to read files and directories through the given file system.
   *
   * @throws {TsconfigParseError} If the tsconfig could not be parsed.
   */

should be 

/**
   * Creates a program **_from_** the specified tsconfig and patches the host
   * to read files and directories through the given file system.
   *
   * @throws {TsconfigParseError} If the tsconfig could not be parsed.
   */

**Comment by crisbeto** [comment]
Fixed in 91adc4844a6fe665e20a0248cd7a8d8d453a4b35.
