### ISSUE TITLE
bug(Datepicker): manually entered value does not respect locale

### ISSUE THREAD

**Issue by MadMonkey87** [angular/components#29940]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a datepicker with 'de-CH' set as locale. Manually modifying the value will interpret the format as 'en-US'.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/i3tkkw?file=src%2Fexample%2Fdatepicker-overview-example.html
Steps to reproduce:
1. use the dropdown to select a date, i.e 1.10.2024 (1th of october)
2. click into the input field and use the keyboard to modify the date, i.e. to 3.10.2024
3. change focus, the date gets changed to 10.3.2024

### Expected Behavior

The date should remain at 3.10.2024

### Actual Behavior

The date changes to 10.3.2024

### Environment

- Angular: 19.0.0, also applies to 18.*
- CDK/Material: 19.0.0, also applies to 18.*
- Browser(s): Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The default date adapter uses the native JS `Date` class so it won't work against all locales. See the Internationalization section in the docs: https://material.angular.io/components/datepicker/overview#internationalization
