### ISSUE TITLE
Unable to resize radio button to smaller version

### ISSUE THREAD

**Issue by tp1906** [angular/components#29954]
Is it possible to resize the radio button including the ripple/outline?  I was able to resize the circle; however, the outline/ripple is not centered.

 .small-radio-button {
    .mdc-radio {
     padding: 2px;
      --mdc-radio-state-layer-size: 32px;
      height: 16px;
      width: 16px;
    }

    .mat-mdc-radio-touch-target {
      height: 16px;
      width: 16px;
    }

    .mdc-radio__background {
      height: 16px;
      width: 16px;
    }

    .mdc-radio__inner-circle {
      border-width: 8px;
    }

    .mdc-radio__outer-circle {
        border-width: 1px;
    }

  }

**Comment by crisbeto** [comment]
You should go through the `radio-density` mixin to resize the radio button. Note that this mostly resizes the ripple and the touch target around the radio button, rather than the inner circle itself.
