### ISSUE TITLE
bug(mat-select): Mat-Select does not have background with custom theme

### ISSUE THREAD

**Issue by johnerickbs** [angular/components#29961]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to use a custom theme palette with the "Color match" from the Material theme builder (https://github.com/material-foundation/material-color-utilities), but I have the following errors:

1- The material 3 theme builder generates a palette colors with HUE 5 and 15, these tone are not recognized by angular material, so I have to remove them in order to fix it.
2- The mat-select doesn't have background.

Is this a bug or what am I missing?

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-segeqm?file=src%2Fstyles%2Fm3-theme.scss

Steps to reproduce:

1. Open the material 3 theme builder (https://material-foundation.github.io/material-theme-builder/)
2. Select the option "Color match"
3. Put the colors for my palette (primary #034737 and tertiary #A9FF9B in my case)
4. export the json
5. Put the colors from the json in the **src/styles/m3-theme.scss**
6. You will get an error:

`Expected $config.color.primary to be a valid M3 palette. Got: (0: #000000, 5: #00150e, 10: #002118, 15: #002c21, 20: #00382b, 25: #004435, 30: #125040, 35: #215c4b, 40: #2f6857, 50: #49826f, 60: #639c88, 70: #7db7a2, 80: #98d3bd, 90: #b3efd8, 95: #c1fde6, 98: #e6fff3, 99: #f3fff8, 100: #ffffff, secondary: (0: #000000, 5: #08130f, 10: #121e1a, 15: #1c2824, 20: #27332e, 25: #323e39, 30: #3d4944, 35: #495550, 40: #55615c, 50: #6d7a74, 60: #87948d, 70: #a1aea8, 80: #bccac3, 90: #d8e6de, 95: #e6f4ec, 98: #effdf5, 99: #f3fff8, 100: #ffffff), neutral: (0: #000000, 5: #101110, 10: #1a1c1b, 15: #242625, 20: #2f3130, 25: #3a3c3a, 30: #464746, 35: #515351, 40: #5d5f5d, 50: #767776, 60: #90918f, 70: #ababa9, 80: #c6c6c4, 90: #e3e2e0, 95: #f1f1ee, 98: #faf9f7, 99: #fdfcfa, 100: #ffffff), neutral-variant: (0: #000000, 5: #0d1210, 10: #181d1a, 15: #222725, 20: #2d312f, 25: #383c3a, 30: #434845, 35: #4f5351, 40: #5b5f5d, 50: #737875, 60: #8d928f, 70: #a8aca9, 80: #c3c7c4, 90: #dfe3e0, 95: #eef2ee, 98: #f6faf6, 99: #f9fdf9, 100: #ffffff), error: (0: #000000, 10: #410002, 20: #690005, 25: #7e0007, 30: #93000a, 35: #a80710, 40: #ba1a1a, 50: #de3730, 60: #ff5449, 70: #ff897d, 80: #ffb4ab, 90: #ffdad6, 95: #ffedea, 98: #fff8f7, 99: #fffbff, 100: #ffffff))
    ╷
135 │   $light-theme: mat.define-theme(
    │ ┌───────────────^
136 │ │   (
137 │ │     color: (
138 │ │       theme-type: light,
139 │ │       primary: $_primary,
140 │ │       tertiary: $_tertiary,
141 │ │     ),
142 │ │   )
143 │ │ );
    │ └─^
    ╵
  src/styles/m3-theme.scss 135:15  @import
  src/global-styles.scss 2:9       root stylesheet
angular:styles/global:styles:1:8`

7. Remove the HUE 5 and 15 from each palette and now it is fixed
8. Select something from the mat-select and you will notice that it does not have a background

### Expected Behavior

A mat-select with a "normal" background

### Actual Behavior

The mat-select does not have background

### Environment

- Angular: 18.2.10
- CDK/Material: 18.2.11

**Comment by wagnermaciel** [comment]
Hi @johnerickbs, thanks for filing this issue. The theme builder you are using is unfortunately not owned by our team and is not tested against our style system.

That said, I am happy to share with you that in v19 we have introduced a new schematic for generating color palettes! This new schematic is tightly integrated with our system and should resolve this issue for you.

If you would like to try it now, you'll need to upgrade to one of the latest releases like [19.0.0-rc.0](https://github.com/angular/components/releases/tag/19.0.0-rc.0). Otherwise, you'll need to wait until our official release which is happening some time in mid-November.
