### ISSUE TITLE
bug(MatIcon): MatIcon within a MatMenuItem button does not show color when overridden

### ISSUE THREAD

**Issue by sjadamek** [angular/components#29978]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a MatIcon is displayed within a MatMenuItem it does not honor its color override as it is overridden by another internal style and icon color styles are declared in the styles.scss.

![Image](https://github.com/user-attachments/assets/35d94610-f15f-48c2-aa35-61be2f543ede)

![Image](https://github.com/user-attachments/assets/3550ce7e-2098-4747-a318-47e1436b09b9)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/ywkkhy

Steps to reproduce:
1. Add icon to menu
2. Set color of icon via class (M3 way)
3. Icon does not honor color due to override of .mat-icon-no-color

### Expected Behavior

Explicit user color class should override internal color class.

### Actual Behavior

Internal color class overrides user color class.

### Environment

- Angular: ^18.2.0 to ^19.0.0-next.2
- CDK/Material: ^18.2.0 to ^19.0.0-next.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
Since this is a style override, we can't do much about it since the selector isn't super specific as it is. There are a couple of options, you can either:
1. Change the selector so it's something like `.mat-mdc-menu-item .mat-icon` or `.mat-icon.primary-icon`.
2. Set the color through the `--mat-menu-item-icon-color` variable.

**Comment by sjadamek** [comment]
Thanks. I'll try to get that workaround to work for me using option one, first couple tries in the styles.scss haven't worked out.

```
.mat-mdc-menu-item .primary-icon
.mat-mdc-menu-item .mat-icon.primary-icon,
.mat-mdc-menu-item .mat-icon .primary-icon,
.mat-icon.primary-icon,
.primary-icon {
  @include mat.icon-color($theme, $color-variant: primary);
}
```

As a follow up though. What is the purpose of the _.mat-mdc-menu-item .mat-icon-no-color_ override when without it the icon already has a default color that at least in the test light and dark theme is almost imperceptibly washed out? Should ease of use trump a barely noticeable color change? I'm sure there is a designer somewhere that would say otherwise, but at least worth the consideration.

Regardless, thanks again for the suggestion.

**no-color enabled:**
![Image](https://github.com/user-attachments/assets/c72ef11d-dfc6-4fe9-9af4-3018eacde3d2)


**no-color disabled:**
![Image](https://github.com/user-attachments/assets/4a9568e1-ca2e-4b21-86e7-caaf37f0d82a)

**Comment by sjadamek** [comment]
@crisbeto I updated my previous stackblitz with your first recommendation and am not having any luck. It seems like it should be working, but it isn't. It even shows my style above the no-color style, but it doesn't take precedence.

![Image](https://github.com/user-attachments/assets/c4e1d546-1df7-418b-bb36-49dc3aa55c62)

**Comment by crisbeto** [comment]
The `@include mat.icon-color` doesn't work in this case, because it targets the base icon token `--mat-icon-color`, whereas icons inside the menu use `--mat-menu-item-icon-color`.
