### ISSUE TITLE
bug(mat-form-field): Hover outline width is not applying on v15+

### ISSUE THREAD

**Issue by bogdandevlpr** [angular/components#29979]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

The hover outline width doesn't work

### Reproduction

StackBlitz link: https://stackblitz.com/edit/xe4ycf-hyx7dg
Steps to reproduce:
1. Hover over the mat form field input

### Expected Behavior

Should apply outline width on hover like on Angular Material V14
https://v14.material.angular.io/components/form-field/examples

### Actual Behavior

The outline width of the form field doesn't increase in size when hovering over the form field input.
![Image](https://github.com/user-attachments/assets/c3ee8756-1f79-4dec-823f-2686e34d437a)

### Environment

- Angular: V15+
- CDK/Material: V15+
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by wagnermaciel** [comment]
@bogdandevlpr This is working as intended. This change was made in keeping up with the Material Design Spec.

**Comment by bogdandevlpr** [comment]
@wagnermaciel Sorry, just for me to understand better, so the intention is to have the `--mdc-outlined-text-field-hover-outline-width` not have any effect when any value is set to it ? And for the `--mdc-outlined-text-field-focus-outline-width` the intention is to take into consideration the value set to it ? Because this is what is currently happening.
