### ISSUE TITLE
feat(providers): provide Tokens in a Type Safe way

### ISSUE THREAD

**Issue by enesyalcin** [angular/components#29973]
## Syntax Sugarcoat Providers

The Angular Framework moved and is still moving to the new `provider` syntax approach, latest example is the `provideAppInitializer()` feature which comes with `angular@19`.  

In Angular Material we have the `provideNativeAdapter()` but besides that we don't have many providers. E.g. `LOCALE_ID` ist frequently used and provided but has no such provider and must be done with the old syntax.

```ts
const appConfig = [
   ...,
   // existing new Syntax
   provideNativeDateAdapter(),

   // existing old Syntax
   {
    provide: LOCALE_ID,
    useValue:'de-AT',
  },
];
```

## The Benefit

You have auto-complete and type safety out of the Box, so in this case you don't have to check which Properties the provider expects.

## Implementation Example
There would be no breaking Change introduced by this change.

```ts
// Type Safety included
export function provideMatPaginatorDefaultOptions(options: MatPaginatorDefaultOptions,): ValueProvider {
  return {
    provide: MAT_PAGINATOR_DEFAULT_OPTIONS,
    useValue: options,
  };
}
```

## Potential Providers

| Token | Provider |
|--------|--------|
| `LOCALE_ID` | `provideLocaleId` |
| `MAT_DIALOG_DEFAULT_OPTIONS` | `provideMatDialogDefaultOptions` |
| `DATE_PIPE_DEFAULT_OPTIONS` | `provideDatePipeDefaultOptions` |
| `MAT_FORM_FIELD_DEFAULT_OPTIONS` | `provideMatFormFieldDefaultOptions` |
| `MAT_PAGINATOR_DEFAULT_OPTIONS` | `provideMatPaginatorDefaultOptions` |
| `MAT_DATE_LOCALE` |  `provideMatDateLocale` | 
| `MAT_PROGRESS_BAR_DEFAULT_OPTIONS` | `provideMatProgressBarDefaultOptions` |

### Use Case

It would be easier to **provide** Angular Material specific **Tokens in a Type Safe way** without having to check in the Source Code which Options the Token expects.

```ts
  // Current Syntax
  {
    provide: MAT_PAGINATOR_DEFAULT_OPTIONS,
    useValue: {
      pageSizeOptions: [5, 10, 20, 50, 100],
      showFirstLastButtons: true,
    } as MatPaginatorDefaultOptions,
  },

  // Proposed Syntax
  provideMatPaginatorDefaultsOptions({
    pageSizeOptions: [5, 10, 20, 50, 100],
    showFirstLastButtons: true,
  }),
```

**Comment by akhil02hero** [comment]
Hi @enesyalcin  can i take this up and work on it ?

**Comment by crisbeto** [comment]
We talked through it with the framework part of the team which initially introduced the `provide*` pattern. It's not meant to replace the `{provide: TOKEN, useValue: ...}`, but rather help with bundling multiple providers together and when there's only one way to configure a set of providers. In our case the providers can be added in multiple ways (`useFactory`). There's an item in the backlog to make the `providers` array type safe which would help for this specific case.
