### ISSUE TITLE
feat(material/timepicker): Implement a visual picker

### ISSUE THREAD

**Issue by angelaki** [angular/components#29998]
### Feature Description

I was quite happy when I saw that finally a time-picker is joining the Angular Components team (https://github.com/angular/components/pull/29806). But after checking it now I'm a bit disappointed, it actually only is a dropdown. I expected it more to align to the Material Design Guide (https://m3.material.io/components/time-pickers/overview, eventough @crisbeto already implemented a nice component once).

Are there plans on supporting a visual input in the future? I still need to go with 3rd party components right now. Haven't found an issue for it, so sorry if this was requested already.

### Use Case

Allow the user to pick a time - easy as that.

**Comment by crisbeto** [comment]
We don't have plans at the moment to implement the dial design from the Material spec. There's an explanation in the [PR](https://github.com/angular/components/pull/29806) around why we went with the dropdown design.
