### ISSUE TITLE
Mat Dialog doesn't respect default max width of 80vw

### ISSUE THREAD

**Issue by bugfiler** [angular/components#30013]
According to documentation (https://material.angular.io/components/dialog/api#MatDialogConfig), the maxWidth of MatDialog should default to 80vw.

This is now defaulting to a max of 560px or the value of --mat-dialog-container-max-width

Dev tools indicates this bit of styling is setting it:
cdk-overlay-pane.mat-mdc-dialog-panel {
    max-width: var(--mat-dialog-container-max-width, 560px);
    min-width: var(--mat-dialog-container-min-width, 280px);
}

You can just set the width of any internal element to 90vw and see the scroll bar.
https://stackblitz.com/edit/c1gort?file=src%2Fexample%2Fdialog-content-example-dialog.html

This defaulted to 80vw as of 21 August 2024  with the Google3 version.

**Comment by andrewseguin** [comment]
Those defaults should only apply to applications using the new `mat.theme` API, which is newly introduced in the upcoming v19 release. Otherwise I would expect applications to have called `mat.dialog-theme` which would explicitly set those dialog variables to the expected value
