### ISSUE TITLE
bug(COMPONENT): Angular Material Tooltips are not consistent

### ISSUE THREAD

**Issue by avicarpio** [angular/components#30024]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The tooltips size on angular material are not consistent when more than one line is needed. I will attach 2 screenshots so you can see the difference.

![Image](https://github.com/user-attachments/assets/ac749ae1-9385-43e1-a37f-5c81adb6e24d)
![Image](https://github.com/user-attachments/assets/ab61cf32-c9d9-4c83-9840-0a3ba2bb1744)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

It should adjust the bounding box to the text.

### Actual Behavior

Leave a lot of horizontal margin for no reason.

### Environment

- Angular: 18.2.4
- CDK/Material: 18.2.4
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment]
I'm not sure we can do much about this. The problem is that the word "medialibrary" is a bit long so it ends up wrapping to the next line. You can either try playing around with your text, or change the `max-width` of the tooltip by adding this to your global styles:

```
.mat-mdc-tooltip-surface {
  max-width: none;
}
```
