### ISSUE TITLE
bug(google-maps/map-advanced-marker): add click events in angular 18

### ISSUE THREAD

**Issue by mikel500** [angular/components#30020]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In relation to the requested feature #29741  of adding click events to the map advanced marker. I am seeing that in the last tag of angular 18 there are not these events, could you generate a tag to add them? Thanks in advance.

### Reproduction

none

### Expected Behavior

Make events available

### Actual Behavior

Events not implemented in Angular 18

### Environment

- Angular:
- google/maps: 18.2.13

**Comment by crisbeto** [comment]
We only add features to `minor` or `major` releases, and we generally don't backport them.
