### ISSUE TITLE
docs-bug(app): theme text colors are inaccessible

### ISSUE THREAD

**Issue by adamlwomble** [angular/components#30048]
### Documentation Feedback

The text on documentation pages is difficult to read when the Cyan & Orange theme is selected: e.g., the page text for the Autocomplete component seems to be the color `rgb(26, 27, 31)` while the background-color for the page seems to be `rgb(16, 20, 20)`, which yields a color contrast ratio of about 1.07:1.

### Affected documentation page

https://material.angular.io/components/autocomplete/overview

**Comment by crisbeto** [comment]
Can you try clearing your cache? We reworked the themes in v19 and you might have the old one in your cache.

**Comment by adamlwomble** [comment]
Clearing my cache worked. Thanks!
