### ISSUE TITLE
Angular 18 tokens no longer emitted

### ISSUE THREAD

**Issue by dinesh250-star** [angular/components#30052]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18

### Description

In angular 18, tokens which were previously available for customizing a component is not emitted anymore.  Is this approach not used anymore?
https://v18.material.angular.io/guide/theming#granular-customizations-with-css-custom-properties
eg-
  --mdc-checkbox-unselected-hover-state-layer-color: red;
  --mdc-checkbox-unselected-hover-icon-color: red;

Instead a new way to override components has been introduced.
https://material.angular.io/guide/theming#component-tokens
eg - 
 elevated-container-color: red,
 elevated-container-shape: 32px,
 title-text-size: 2rem,

What is the right way to use them? In angular 18, we used the first link but now when moving to angular 19 do we need to change it again?

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

According to angular 18 docs we should have got token emitted but its not defined by default in angular material. Instead in style section of angular 19 we have new way to customize components.

### Actual Behavior

Instead of new way to override we should have got token which was in angular 18 as promised.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Those variables are still there, but we recommend going through the `overrides` mixins since they're documented and they have some safeguards in place to avoid breaking changes in the future.
