### ISSUE TITLE
docs-bug(COMPONENT): I can not use 0.0.0.0 ?

### ISSUE THREAD

**Issue by anlexN** [angular/components#30065]
### Documentation Feedback

I want to change localhost to 0.0.0.0 ?

![Image](https://github.com/user-attachments/assets/59f5c211-4dcb-47aa-a3b0-04b7bccacf35)

I have tried:

![Image](https://github.com/user-attachments/assets/2e8c82c5-7d76-4bf8-ab8d-01133f1961cb)

I tried this:

![Image](https://github.com/user-attachments/assets/a6e7f709-bedd-46e9-a89e-33edc968145a)

or I tried this:

![Image](https://github.com/user-attachments/assets/e0546673-fc45-4d19-ba39-80cdaed6a7b0)

Because I use docker in the windows. I want to access docker's ibazel url in the windows.

But `--host=0.0.0.0` is wrong.

### Affected documentation page

https://material.angular.io/guides

**Comment by crisbeto** [comment]
The host get passed through to `browser-sync`. This is likely an issue either with them or with the interaction of `browser-sync` + Docker + Windows.
