### ISSUE TITLE
bug(MatTooltip): Can't scroll if target element has matTooltip

### ISSUE THREAD

**Issue by ManicardiFrancesco** [angular/components#30069]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

According to Issue 4892, this bug should've been fixed in Angular 11+

### Description

Scrolling on a touch device doesn't work if the target of the gesture is an element using matTooltip.
This is apparently a regression as people mentioned it being fixed in angular 11+:
https://github.com/angular/components/issues/4892

Tagging @wagnermaciel @crisbeto and @jelbourn as they commented on the previous issue.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-nnqsnt?file=src%2Fmain.html
Steps to reproduce:
1. Open the stackblitz link with a touch enabled device (I tested with my Android phone and Firefox browser)
2. Try scrolling the element - it will not scroll if you target the "This will not scroll with touch" text.

I also included a CSS workaround which appears to be working but shouldn't be necessary.

### Expected Behavior

Scrolling behavior should not be affected by the presence or absence of a mat tooltip.

### Actual Behavior

Scrolling behavior is disabled by targeting a mat tooltip element.

### Environment

- Angular: 
- Angular CLI: 19.0.0
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 19.0.0
... animations, build, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0
@angular-devkit/core         19.0.0
@angular-devkit/schematics   19.0.0
@schematics/angular          19.0.0
rxjs                         7.8.1
typescript                   5.6.3
zone.js                      0.15.0
- CDK/Material:    "@angular/material": "^19"

- Browser(s): Firefox 
- Operating System (e.g. Windows, macOS, Ubuntu): Android

**Comment by ManicardiFrancesco** [comment]
Some additional info I gathered in the past hour:
The workaround I showed in the StackBlitz works by setting this css rule on the tooltip trigger element:
`touch-action: auto;`

I don't know why this works since the initial value of touch action is supposed to be auto anyway according to the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) - I checked the elements on my repro with inspect element and i confirmed that there is no touch action rule set on them.

**Comment by crisbeto** [comment]
It's because the tooltip uses a long press gesture on touch devices which can interfere with scrolling. You can use the `matTooltipTouchGestures` input to configure the behavior. There's more information in the docs: https://material.angular.io/components/tooltip/api

**Comment by ManicardiFrancesco** [comment]
Thank you for your time and for providing clarity on this @crisbeto!

I appreciate the quick response.

Could you elaborate on why scrolling and opening the tooltip can't work together by default?
What does it mean exactly when you say "it interferes" with scrolling?

With the workaround I implemented (`touch-action: auto !important;`), the scrolling and tooltip both work.
Could this behavior possibly be the default setting, or is there some edge case I'm missing?

The current behaviour is blocking me from using mat-tooltips in mat-table cells - the user is not be able to scroll the tables on mobile.
