### ISSUE TITLE
docs-bug(COMPONENT): TITLE

### ISSUE THREAD

**Issue by 0xFACE** [angular/components#30072]
### Documentation Feedback

I get following warning when building the application:
`The same typography styles are generated multiple times. Read more about how style duplication can be avoided in a dedicated guide. https://github.com/angular/components/blob/main/guides/duplicate-theming-styles.md [plugin angular-sass]`

But the link provided does not exist (404 error).

### Affected documentation page

https://github.com/angular/components/blob/main/guides/duplicate-theming-styles.md

**Comment by Sepandard** [comment]
Just wanted to chime in, I started working on this one.
