### ISSUE TITLE
outlined/stroked-item-icon-color token for mat-menu

### ISSUE THREAD

**Issue by cristinmr** [angular/components#30075]
### Feature Description

When adding buttons inside a `mat-menu`, the color of the icons defaults to `var(--mat-sys-on-surface-variant)`.

Although there is a token (item-icon-color) that modified the icon color, it does not take into consideration the different button styles (outlined/stroked).
Having separate tokens (**outlined-item-icon-color** and **stroked-item-icon-color**) would help.

This is how it looks now:
![Image](https://github.com/user-attachments/assets/bf2a791f-ba8f-4a0f-ac1f-15b9f0296219)

### Use Case

Having different types of buttons with icons inside a mat-menu

**Comment by crisbeto** [comment]
Closing since `mat-menu` only officially supports projecting `mat-menu-item`.
