### ISSUE TITLE
docs-bug(Ripple): Styling documentation tab doesn't load

### ISSUE THREAD

**Issue by tjaz-brelih** [angular/components#30098]
### Documentation Feedback

When navigating to the Styling tab for Ripple component the tab content only says Loading.
HTTP request for URL `https://material.angular.io/docs-content/tokens/material/ripple/ripple.json` returns a generic Firebase "Page Not Found" page with HTTP status 404.

### Affected documentation page

https://material.angular.io/components/ripple/styling

**Comment by crisbeto** [comment]
Definitely something we should fix. Until then you can find it in the "Core" section: https://material.angular.io/components/core/styling
