### ISSUE TITLE
bug(MatSlideToggle): Design styling tokens don't properly override the theme

### ISSUE THREAD

**Issue by Parnavs** [angular/components#30104]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I've added some styling to the MatSlideToggle component using the design tokens from the documentation, but some of them seem not to work. They get ignored because of the theme. It seems like they have a lower specificity. 

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-i9rg73?file=angular.json
Steps to reproduce:
1. Have the azure-blue theme installed
1. Override the styling using the mixin from angular documentation 
2. Some styling get's striked through in favor of the azure blue theme
3. ![Image](https://github.com/user-attachments/assets/c3f88cdd-4f7c-44a4-a3d6-8d2b48a7ae84)

### Expected Behavior

I'm expecting that the mixin would be enough to override as they work for the other tokens

### Actual Behavior

The styling gets ignored in favor of the theme's styling

### Environment

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.10
@angular-devkit/build-angular   18.2.10
@angular-devkit/core            18.2.10
@angular-devkit/schematics      18.2.10
@angular/cdk                    18.2.10
@angular/cli                    18.2.10
@angular/material               18.2.10
@schematics/angular             18.2.10
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

Chrome, Windows

**Comment by crisbeto** [comment]
It's because we were including the backwards-compatibility styles for `mat-accent`, `mat-primary` etc by default v18 to avoid breaking changes. You can either update to v19 which no longer includes the `mat-accent` styles by default, or increase the selector specificity of your overrides.
