### ISSUE TITLE
Unexpected Numbers Displayed in Angular Material Datepicker Calendar

### ISSUE THREAD

**Issue by KamranSohail619** [angular/components#30106]
### Description

I am using Angular Material's mat-datepicker in my Angular project. The datepicker UI is displaying incorrect numbers instead of proper dates (see screenshot). I want to show a proper calendar for date selection. 
Note: I have already imported all the required Angular Material modules, including MatDatepickerModule, MatInputModule, and MatNativeDateModule,

Here's the relevant code snippet:
<mat-form-field>
  <mat-label>Choose a To date</mat-label>
  <input
    matInput
    readonly
    [min]="selectedFromDate"
    [matDatepicker]="ToDatepicker"
    [(ngModel)]="selectedToDate"
    (dateChange)="onDateChange($event.value, 'addedon', 'lte')"
    placeholder="MM/DD/YYYY"
  />
  <mat-icon matSuffix [for]="ToDatepicker">event</mat-icon>
  <mat-datepicker #ToDatepicker></mat-datepicker>
</mat-form-field>

![Image](https://github.com/user-attachments/assets/f9a03e85-5c90-40c2-a19c-784b4776e86e)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

![Image](https://github.com/user-attachments/assets/034ce39f-9907-4051-b244-e17c78fd559d)

### Actual Behavior

![Image](https://github.com/user-attachments/assets/1053c293-2c6d-4f6a-a33f-810ec8993fbd)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
What locale are you on and which date adapter are you using?

**Comment by andgdk** [comment]
Looks like an issue with the styles. The columns are too wide and squish the last 3 days, so the correct numbers are partially overlapping.

**Comment by crisbeto** [comment]
This is most likely a case of styles bleeding in from other parts of the app and overriding Material's styles.

**Comment by KamranSohail619** [comment]
> This is most likely a case of styles bleeding in from other parts of the app and overriding Material's styles.

Yes, this was indeed the issue. The td, th { width: 25%; } style was overriding Material's styles. After removing or adjusting it, everything works fine now.
