### ISSUE TITLE
CALENDAR: start view month is not working

### ISSUE THREAD

**Issue by kai1992cool** [angular/components#30114]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

StackBlitz link:  https://stackblitz.com/edit/gmbffs-5g3jqc?file=src%2Fexample%2Fdate-range-picker-forms-example.html
Steps to reproduce:
1.  I have configured start view as month, but it is not showing month view

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/gmbffs-5g3jqc?file=src%2Fexample%2Fdate-range-picker-forms-example.html
Steps to reproduce:
1.  I have configured start view as month, but it is not showing month view

### Expected Behavior

the month view should be displayed

### Actual Behavior

the default view is only displayed for other views it is working, month has this problem.

### Environment

- Angular: ^19.0.0
- CDK/Material:^19.0.0
- Browser(s): Version 131.0.6778.86 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
What you're seeing _is_ the month view. If you wanted to see the view with the individual months, you should use the `startView="year"`.
