### ISSUE TITLE
When switch to a mobile view the MatBottomSheetModule does not work correctly

### ISSUE THREAD

**Issue by Vagner8** [angular/components#30110]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I happens only on the mobile view. 
When you clicked the edge of the MatBottomSheetModule  the whole MatBottomSheetModule is blinking.

### Reproduction

StackBlitz link: https://material.angular.io/components/bottom-sheet/overview
Steps to reproduce:
1.  Go to the link - https://material.angular.io/components/bottom-sheet/overview
2. Switch to the mobile view
3. Click at the edge of the MatBottomSheetModule like on the screen
![Image](https://github.com/user-attachments/assets/0e669caa-b739-43d9-a2f1-d1561aefba4d)
![Image](https://github.com/user-attachments/assets/ff3e1c45-6096-4f25-9347-0e2af56b2a29)

### Expected Behavior

the MatBottomSheetModule does not blink

### Actual Behavior

the MatBottomSheetModule is blinking

### Environment

- Angular: 18.2.11
- CDK/Material: 18.2.14
- Browser(s): Chrom
- Operating System (e.g. Windows, macOS, Ubuntu): Windows![Image](https://github.com/user-attachments/assets/dc315ea7-f608-4c1c-af7c-a32e4e24380d)

**Comment by crisbeto** [comment]
I can't reproduce it. The error's stack track looks like it's coming from a browser extension.
