### ISSUE TITLE
bug(Timepicker): Disabled not working in FormControl

### ISSUE THREAD

**Issue by horesse** [angular/components#30134]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The disabled property does not work correctly in timepicker. It blocks the time selection, but the selection from the menu is available

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/czbajk?file=src%2Fexample%2Ftimepicker-datepicker-integration-example.html
Steps to reproduce: 
1. Use FormControl
2. Disable input
3. U can change time

### Expected Behavior

Lock time selector

### Actual Behavior

Time selection is available

### Environment

- Angular: 19.0.0 - 19.0.2
- CDK/Material: latest
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Sent a fix at #30137 which will be in next week's release. Until it's fixed, you can work around it by setting the `disabled` attribute on `mat-timepicker-toggle`.
