### ISSUE TITLE
bug(Timepicker): Luxon provider does not display date if it exists

### ISSUE THREAD

**Issue by horesse** [angular/components#30140]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If there is an initial value in formControl, then when using provideLuxonDateAdapter(), the date will not be displayed when the page is loaded, but if we select the time, it will be displayed correctly.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/8xbgfc-eqfhl1?file=src%2Fexample%2Ftimepicker-forms-example.ts
Steps to reproduce:
1. Open Page
2. Check value in formControl
3. Timepicker input is empty

### Expected Behavior

Display time

### Actual Behavior

Timepicker value is empty when component is initialized even if formControl has value

### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by horesse** [comment]
p.s. i try use:
```typescript
// Material Date Adapter
        {
            provide: DateAdapter,
            useClass: LuxonDateAdapter,
        },
        {
            provide: MAT_DATE_FORMATS,
            useValue: {
                parse: {
                    dateInput: 'D',
                    timeInput: 'T',
                },
                display: {
                    dateInput: 'dd.MM.yyyy',
                    monthYearLabel: 'LLL yyyy',
                    dateA11yLabel: 'DD',
                    monthYearA11yLabel: 'LLLL yyyy',
                    timeInput: 'T',
                    timeOptionLabel: 'T',
                },
            },
        },
``` 

but I get the same negative result. With provideNativeDateAdapter() there is no such problem

**Comment by crisbeto** [comment]
It's because your example is using the built-in `Date` type and the Luxon adapter is expecting Luxon's `DateTime` type. Here's a working example: https://stackblitz.com/edit/8xbgfc-opkege?file=src%2Fexample%2Ftimepicker-forms-example.ts

**Comment by horesse** [comment]
> It's because your example is using the built-in `Date` type and the Luxon adapter is expecting Luxon's `DateTime` type. Here's a working example: https://stackblitz.com/edit/8xbgfc-opkege?file=src%2Fexample%2Ftimepicker-forms-example.ts

Ok, but in other cases I always used Date, including for Datepicker and there were no problems.

**Comment by crisbeto** [comment]
Ah, I see what you mean now. I've sent #30149 as a fix.
