### ISSUE TITLE
bug(mat.theme-overrides): Overridden CSS properties not displaying correctly in IDE hints

### ISSUE THREAD

**Issue by russelporosky** [angular/components#30143]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This is simply a quality of life improvement request.

![Image](https://github.com/user-attachments/assets/aa8104c0-6103-44c7-8482-f96ae4d51fa9)

I've overridden `on-surface` and `surface` in [the recommended manner](https://material.angular.io/guide/theming#system-tokens), but the IDE (IntelliJ in this screenshot) won't pick those modifications up.

The rendered page in the browser shows the correct colour, this is strictly an issue within the IDE.

The concern is that deeper into the project, when a developer is using Material CSS variables, the colour hints will not match what they are expecting (and needing) which will cause confusion and potentially result in additional variables being created by the developer that aren't actually needed, just so the IDE hints match their expectations.

### Reproduction

Steps to reproduce:
1. add Material to an Angular project
2. override a theme variable such as `surface`
3. use the matching CSS property in a rule (`--mat-sys-on-surface` in this example)
4. observe that the IDE colour hint does not match the overridden value

![Image](https://github.com/user-attachments/assets/aa8104c0-6103-44c7-8482-f96ae4d51fa9)

### Expected Behavior

The colour hints in the sidebar should show the overridden colour(s) instead of the defaults.

### Actual Behavior

What I see in the sidebar are the defaults for the current theme.

### Environment

- Angular: 19.0.3
- CDK/Material: 19.0.2
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS
- IDE: IntelliJ IDEA 2024.3 (Ultimate Edition)

**Comment by crisbeto** [comment]
Closing since we can't do much about this. You'll have to bring it up with the IDE developers.
