### ISSUE TITLE
MAT INPUT: The error messages show inside the form field, when a @if and @for are used to show the error messages.

### ISSUE THREAD

**Issue by kai1992cool** [angular/components#30151]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the below code block.

```
<form class="example-form">
  <mat-form-field>
    <mat-label>Email</mat-label>
    <input
      type="email"
      matInput
      [formControl]="emailFormControl"
      [errorStateMatcher]="matcher"
      placeholder="Ex. pat@example.com"
    />
    @if(emailFormControl?.invalid && emailFormControl?.touched){ 
      @for(error of getErrorMessages(''); track i; let i = $index){
        <mat-error> {{ error }} </mat-error>
      } 
    }
  </mat-form-field>
</form>
```

The errors get displayed inside the input field, which is wrong.

I know this is due to content projection of `mat-error` but am not sure if its a bug or an expected result.

Could you please advice.

### Reproduction

StackBlitz link: [stackblitz](https://stackblitz.com/edit/mpcfhkum?file=src%2Fexample%2Finput-error-state-matcher-example.html,src%2Fexample%2Finput-error-state-matcher-example.ts)
Steps to reproduce:
1. touch the input
2. tab out or click elsewhere, the errors are shown inside the input

### Expected Behavior

the error should display outside

### Actual Behavior

the error are displayed inside

### Environment

- Angular: ^19.0.0
- CDK/Material: ^19.0.0
- Browser(s): Version 131.0.6778.109 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The previous comment is correct. Closing.
