### ISSUE TITLE
bug(Timepicker): Integration with Datepicker does not work with FormControl

### ISSUE THREAD

**Issue by janek64** [angular/components#30150]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a `Timepicker` and `Datepicker` are bound to the same `FormControl` with a `Date` type, selecting a new value on either input will cause the data of the other input to be reset/removed. For example, when a date is already selected and then the time is selected, the date portion of the value will be reset to the current date.

The [documentation](https://material.angular.io/components/timepicker/overview#integration-with-matdatepicker) only demonstrates the integration via `ngModel`. Consequently, it is unclear to me whether it should also work with `FormControl`. Based on the description, I would have expected it. If it is explicitly not supported, I suggest that a corresponding hint should be added since using Reactive Forms is one of the most common ways for managing the values of inputs.

### Reproduction

StackBlitz link: [https://stackblitz.com/edit/components-issue-starter-qszwe9ry?file=src%2Fapp%2Fexample%2Fexample.component.ts](https://stackblitz.com/edit/components-issue-starter-qszwe9ry?file=src%2Fapp%2Fexample%2Fexample.component.ts)
Steps to reproduce:
1. Select a date that is not the current date (e.g tomorrow). The displayed value will correctly display the selected date.
2. Select any time. The displayed value will display the _current date_ and the selected time instead of the _selected date_.
3. Select a date that is not the current date. The displayed date will display _0:00_ as the time instead of _selected time_.

### Expected Behavior

1. Selections in the `Datepicker` change the date portion of the `FormControl`, but keep the selected time.
2. Selections in the `Timepicker` change the time portion of the `FormControl`, but keep the selected date.

### Actual Behavior

1. Selections in the `Datepicker` change the date portion of the `FormControl` and discard the selected time.
2. Selections in the `Timepicker` change the time portion of the `FormControl` and discard the selected date.

### Environment

- Angular: 19.0.3
- CDK/Material: 19.0.3
- Browser(s): Firefox 133, Chrome 131
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by Totati** [comment]
Duplication of https://github.com/angular/components/issues/30135, https://github.com/angular/angular/issues/58522

**Comment by crisbeto** [comment]
Closing as a duplicate.
