### ISSUE TITLE
bug(matAutocomplete): Autocomplete not opening with shadow DOM

### ISSUE THREAD

**Issue by XavierDupessey** [angular/components#30153]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

The `MatAutocomplete` does not open when starting writing text if the Shadow DOM encapsulation is used.
We have to click to trigger the opening.

Without Shadow DOM encapsulation (working):
https://github.com/user-attachments/assets/911e3de9-83c3-412e-a87e-6f994298fead

With Shadow DOM encapsulation (NOT working):
https://github.com/user-attachments/assets/c0ced996-2bf9-40d5-84ba-d2d5e490e10a

Thank you,
Xavier

### Reproduction

Checkout: https://github.com/XavierDupessey/ng-14-mat-autocomplete-issue
Run: `npm start`
Open `http://localhost:4200`

### Expected Behavior

The autocomplete should open when entering text even when Shadow DOM encapsulation is enabled.

### Actual Behavior

Select a value from the autocomplete, then input text to search another one: the autocomplete does not open.

### Environment

- Angular: 14
- CDK/Material: 14
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Closing since this is an issue against an old version of Angular. The autocomplete seems to work in the shadow DOM in the latest version.
