### ISSUE TITLE
bug(mat-timepicker): Disabling TimePicker does not prevent dropdown from opening

### ISSUE THREAD

**Issue by kanehjeong** [angular/components#30162]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When disabling a mat timepicker input field as well as the timepicker toggle, clicking the toggle or time value on the field still triggers the select dropdown for the times.

### Reproduction

[Stackblitz Link](https://stackblitz.com/edit/4nj2hwbz?file=src%2Fexample%2Ftimepicker-forms-example.ts)

Made the following changes off [this material example link](https://material.angular.io/components/timepicker/examples#timepicker-forms)
```
// timepicker-forms-example.ts
new FormControl({ value: initialValue, disabled: true }); // Added disabled here

// timepicker-forms-example.html
<mat-timepicker-toggle matIconSuffix [for]="picker" [disabled]="true"/> <!-- Added disabled here -->
```

Steps to reproduce:
1. Click the time value of the disabled input or the toggle icon
2. Notice the select menu pop up with the time selections despite input being disabled

### Expected Behavior

Should not open timepicker menu when input and toggle are both disabled

### Actual Behavior

Timepicker select menu opens

### Environment

- Angular: 19.0.2
- CDK/Material: 19.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
Will be fixed in this week's release by https://github.com/angular/components/pull/30137.
