### ISSUE TITLE
bug(AngularAnimations): Detached dom nodes with material component on navigation

### ISSUE THREAD

**Issue by theSumit67** [angular/components#30166]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a very basic app in Angular + Material version 14. 

On one page I have mat-tabs and a button which navigates to a blank component destroying the previous component. After navigation all of the DOM nodes are going to detached state. I need to fix this in huge angular app which is on version 14. Please let me know if there is any solution exist

![Image](https://github.com/user-attachments/assets/9f037f01-d6d0-4a6d-9614-c7d813cf6811)

![Image](https://github.com/user-attachments/assets/d9d21ca0-4363-489c-8d90-289ca69c4c3f)

Attaching sample project.[m14.zip](https://github.com/user-attachments/files/18098062/m14.zip)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. ng serve
2. click on the button to navigate to other page

### Expected Behavior

Detached DOM nodes should not be there

### Actual Behavior

All of the nodes are going in detached state

### Environment

- Angular:14.3.0
- CDK/Material:  14.2.7
- Browser(s): Chrome
- Operating System Windows, macOS, Ubuntu

**Comment by crisbeto** [comment]
Same root cause as https://github.com/angular/angular/issues/54149.
