### ISSUE TITLE
bug(mat-tab) Material Tab animation not working since v12+

### ISSUE THREAD

**Issue by hasokeric** [angular/components#30177]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v12.2.13

### Description

If you simply go to the page https://material.angular.io/components/tabs/overview#controlling-the-tab-animation and compare the *12.2.3* Angular Material docs to all the new ones the animations on the tabs stopped working.

Even when I try something like, it doesnt work.
```typescript
{
  provide: MAT_TABS_CONFIG,
  useValue: {
    animationDuration: '33330ms',
    fitInkBarToContent: true
  } as MatTabsConfig
},
```

### Reproduction

N/A

### Expected Behavior

The mat-tab should animate slower, the docs should work.

### Actual Behavior

The docs section doesn't animate.

### Environment

Angular Material Documentation

**Comment by hasokeric** [comment]
Just to re-iterate, the docs examples do not work, why they don't work I am not sure.

However I think the reason I am having issues was I am using `mat-tab-nav-bar` and it doesnt have all the config intializations that `mat-tab-group` has

https://github.com/angular/components/blob/a141c22e99467174225f74b6ccac730df92c46c8/src/material/tabs/tab-nav-bar/tab-nav-bar.ts#L166C1-L187C4

https://github.com/angular/components/blob/a141c22e99467174225f74b6ccac730df92c46c8/src/material/tabs/tab-group.ts#L275

**Comment by hasokeric** [comment]
If anyone comes across why your animations in the docs don't work... its because the docs check for `prefers-reduced-motion` and chrome reads it from windows.

![Image](https://github.com/user-attachments/assets/51659775-0281-4491-883e-2c6b63f0f9d2)

**Comment by crisbeto** [comment]
Closing since this looks like a user issue.
