### ISSUE TITLE
docs-bug(COMPONENT): No examples of migrating from material 2 to material 3 color variants for buttons.

### ISSUE THREAD

**Issue by tayambamwanza** [angular/components#30192]
### Documentation Feedback

The docs introduce a new way of working with colors and theming, I've managed to work out most of it and the system is simpler with one exception, I'm finding a lot of friction in figuring out how to get similar behaviour for configuring button colors as in the old version.

Previously it was possible to just set color="variant" but now after going through documentation and looking it up on google I still haven't quite figured out how to get most of the old behaviour back, the best I could manage was a warning color using tertiary but I feel like I'm missing a simpler solution, how do I set secondary and error/danger colors?

I used command and class below:

```
@angular/material:theme-color -- --primary-color '#7AA802' --secondary-color '#276667' --tertiary-color '#FF9800' --neutral-color '' --include-high-contrast
```

```
.warning-button {
  @include mat.button-theme(theme.$tertiary-palette)
}

```
I think it might help to have more examples in the docs of how to do this correctly, maybe just using the buttons page as the prime example would really help.

I wasn't expecting to get stuck here, I appreciate all the work, I also think it's understandable something that took setting one property I now can't figure out after spending a decent amount of time looking it up, there are probably some improvements that can be made.

Also a central guide/api page for almost all the various mixins/functions that are available might help.

 Thank you.

### Affected documentation page

https://material.angular.io/components/button/overview

**Comment by amysorto** [comment]
We have a mixin you can add to your theme file to get that `color="variant"` functionality back. There is more information about that here: https://material.angular.io/guide/material-2-theming#optional-add-backwards-compatibility-styles-for-color-variants.

The theming guide includes some examples of setting up theming in an application: https://material.angular.io/guide/theming. Please open a new issue with specific requests for any improvements. Thanks!

**Comment by tayambamwanza** [comment]
@amysorto Thanks, that's a backwards compatibility flag, I'm interested in setting up similar behaviour using the new api. I'm worried that relying on that could cause issues in the future where I'd eventually have to re-write anyway.

To be more specific a demo, or snippet for how I could setup similar behaviour using the new api would be great especially for those who are migrating from material 2.

If you don't feel it's necessary, ok, just thought I'd try request since it's the only issue I ran into trying to switch now, I'll figure it out eventually and write a blog post or something then 👍🏾.
