### ISSUE TITLE
bug(COMPONENT): MatSnackBar padding to the box shadow rendering a container with a custom background color

### ISSUE THREAD

**Issue by diegoquirino** [angular/components#30200]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

MatSnackBar padding to the box shadow rendering a container with a custom background color issue

### Description

The MatSnackBar component in Angular Material 19 appears to have visual rendering issues related to adding padding to the box shadow with a container with a custom background color style.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-ryes6wpj?file=src%2Fnotification%2Fnotification.component.ts
Steps to reproduce:
1. Trigger a MatSnackBar with a container with a custom background color style.
2. Observe the component's visual rendering (as shown in the StackBlitz).

### Expected Behavior

The MatSnackBar should render consistent shadow without visual padding from the message container with a custom background color style.

### Actual Behavior

- The snack bar's box shadow appears with padding from the message container with a custom background color style.

### Environment

- Angular: 19.0.3
- CDK/Material: 19.0.3
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
This may be a bit easier to do by setting the `panelClass` and applying the colors through the overrides API: https://material.angular.io/components/snack-bar/styling

**Comment by diegoquirino** [comment]
Hi @crisbeto
I tried styling, including mat.snack-bar-overrides, but as you can see in https://stackblitz.com/edit/stackblitz-starters-ryes6wpj?file=src%2Fnotification%2Fnotification.component.scss, it still not work.

**Comment by crisbeto** [comment]
It's because you've included the styles inside an encapsulated component. You have to either disable encapsulation on it or move your styles to the global stylesheet. Here's a working example: https://stackblitz.com/edit/stackblitz-starters-15owm2ek?file=src%2Fnotification%2Fnotification.component.ts,src%2Fnotification%2Fnotification.component.scss

**Comment by diegoquirino** [comment]
You're correct that encapsulation may cause the styles not to affect the Snackbar component directly. However, even when styles are correctly applied globally or encapsulation is disabled, there **might still be no visible changes** due to (_I believe_) the limited tokens provided by the mat.snack-bar-overrides mixin.

A **clear solution** to ensure flexibility and achieve the desired visual effect (only inside an encapsulated component) is **_to request or implement support for a new token_**, such as container-box-shadow, within the mat.snack-bar-overrides mixin. This would allow control over the box shadow of the Snackbar container, with values like none or transparent. This approach aligns with the existing flexibility provided by the container-color token, which already supports transparent.

**_Proposed Solution with Example_**

Extend mat.snack-bar-overrides to include the container-box-shadow token:

```scss
@use '@angular/material' as mat;

// Example: Overriding Snackbar styles with "container-box-shadow"
@include mat.snack-bar-overrides((
  container-color: transparent,  // Existing token
  container-box-shadow: none,   // Proposed new token
));
```

**Comment by diegoquirino** [comment]
Hi everyone! 😊

I’m excited to share that I’ve solved the issue with the colorful boxes for the Angular Material Snackbar notifications! 🎉 You can find the solution here: [[StackBlitz Link]](https://stackblitz.com/edit/stackblitz-starters-ryes6wpj?file=src%2Fstyles.scss)

A big thank you to everyone who helped and shared ideas along the way. Your input made this solution possible, and I truly appreciate it! 💙
