### ISSUE TITLE
bug(Paginator): disabled paginator icon focues

### ISSUE THREAD

**Issue by smil-thakur** [angular/components#30216]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v18

### Description

if the button for pagination is disabled it should not be focused using "tab" key, on material 19 upgrade disabled pagination button is focusable which is not expected

v19:
![Image](https://github.com/user-attachments/assets/618eb5a8-a73c-4ae0-a6d0-9fcf5f526b7d)

v18:

![Image](https://github.com/user-attachments/assets/52fd008c-1643-4691-bf4f-35c4a66b6f54)

### Reproduction

Steps to reproduce:
1. https://material.angular.io/components/paginator/overview go here press tab key and see disabled pagination button is focusable
2.

### Expected Behavior

it should be focusable and should be skipped like on
https://v18.material.angular.io/components/paginator/overview

### Actual Behavior

the disabled button of pagination is not skipped and is focused

### Environment

- Angular: 19
- CDK/Material: 19
- Browser(s): chrome
- Operating System: windows

**Comment by crisbeto** [comment]
This is intentional. See https://github.com/angular/components/pull/29379.
