### ISSUE TITLE
bug(MatDatepicker): Overriding MatDatepickerIntl texts

### ISSUE THREAD

**Issue by wsacha** [angular/components#30225]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello, I'd like to override the closeCalendarLabel for all places in the application where the Material Datepicker is used.
According to the documentation: https://material.angular.io/components/datepicker/overview#localizing-labels-and-messages,
I've provided my values, but it doesn't seem to work. The new texts are applied only if I provide a custom MatDatepickerIntl in the child component where the MatDatepicker is used. Am I doing something wrong that prevents me from overriding it globally?

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-6vdvpgxv?file=src%2Fmain.ts
Steps to reproduce:
1. Override `MatDatepickerIntl` globally  
2. Use the material datepicker in the child component
3. Open the datepicker and press TAB to show the close button.

### Expected Behavior

Overriding `MatDatepickerIntl` globally applies new labels to all MatDatepicker instances.

### Actual Behavior

Overriding `MatDatepickerIntl` globally does not applies new labels to all MatDatepicker instances.

### Environment

- Angular: 18
- CDK/Material: 18
- Browser(s): Firefox, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, macOS

**Comment by crisbeto** [comment]
It's because you're importing the `MatDatepickerModule` which then re-provides the default implementation. You should import the individual directives: https://stackblitz.com/edit/stackblitz-starters-f3zbbv71?file=src%2Ffoo%2Fdate-example%2Fdate-example.component.ts
