### ISSUE TITLE
bug(CDK/Menu): MenuItems as Content projection loos keyboard actions

### ISSUE THREAD

**Issue by GuidoHermans** [angular/components#30222]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are incorporating the CDK Menu in our app.
With use of content projection we try to extract the cdk references to a 'dropdown component', so the developer doesn't need to know of the CDK.

When we use content projection, it looks like the cdkMenuItemDirective is not completely activating the keyboard gestures.
Without content projection everything works (as expected)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-ybcawwsc?
Steps to reproduce:
1. Klik on the site
2. Use Tab to active the main button
3. Use arrow keys to navigate to the submenu
4. See that Test 1 & Test 2 are not navigateble and Test 3 and Test 4 are.

### Expected Behavior

Test 1 and Test 2 should be navigatable with keyboard.

### Actual Behavior

No keyboard navigation on content projected in the `<ng-template></ng-template>`

### Environment

```
Angular CLI: 19.0.5
Node: 20.17.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 19.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5
@angular-devkit/schematics      19.0.5
@angular/cli                    19.0.5
@schematics/angular             19.0.5
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by GuidoHermans** [comment]
> Not able to run the stackblitz. Giving error: `The Angular Compiler requires TypeScript >=5.5.0 and <5.7.0 but 5.7.2 was found instead.`

Fixed.

**Comment by shhdharmen** [comment]
It's happening because `cdkMenu` only projects `cdkMenuItem`. You need to update your logic a bit, iterate over all `contentChildren(CdkMenuItem)` and then project them using `cdkMenuItem` in your component.

Demo: https://stackblitz.com/edit/stackblitz-starters-yre6f8c9?file=src%2Fdropdown%2Fdropdown.component.html

**Comment by crisbeto** [comment]
Closing since Angular's content projection doesn't allow the menu to pick up items across components like this.
