### ISSUE TITLE
Drag drop with angular material table giving lots of error

### ISSUE THREAD

**Issue by PoojaM29** [angular/components#30232]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

V18

### Description

I am having my common table component in that using <table> tag for table creation but angular 19 not supporting this tag while using drag and drop feature.
Getting error like invalid dom structure for droplist. All items must be placed directly inside of the element container.
<table mat-table > </table>

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

<table> tag should support in drag and drop

### Actual Behavior

Table tag not getting support for drag and drag in angular material 19

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
