### ISSUE TITLE
bug(MatTabModule): Loading many formcontrols on 2nd, 3rd, etc tab (not 1st) will result in "Error: Could not find identifiable element"

### ISSUE THREAD

**Issue by ViVer-7** [angular/components#30243]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

My app uses the MatTabModule, with currently 5 tabs.
Using form controls on tab1 is working like expected, but on any other tab, it throws an error.
At least, when using A LOT of controls (like 100).

### Reproduction

Steps to reproduce:

HTML:
```
<mat-tab-group>
    <mat-tab label="Tab1">
        Some Content Tab1
    </mat-tab>
    <mat-tab label="Tab2">

        @for (i of [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]; track $index) {
            <div [formGroup]="form">
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
                <input matInput>
            </div>                
        }    
    </mat-tab>
</mat-tab-group>
```

Whenever I lower the number of loops....there is no error....

### Expected Behavior

Expected result is to be able to use as many controls as I want, without throwing an error...

### Actual Behavior

Tab and Form is loaded as expected, but throwing an error, see attached screenshot.
![Image](https://github.com/user-attachments/assets/8a56c962-c1b6-4b6f-bc10-e396cca9d026)

### Environment

- Angular: ~19.0.0
- Angular Material: ~19.0.4
- Browser(s): Chrome (latest)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment]
It looks like this error is coming from a Chrome extension.
