### ISSUE TITLE
bug(COMPONENT):  [ERROR] TS2305: Module '"@angular/material/core"' has no exported member 'CanUpdateErrorState'

### ISSUE THREAD

**Issue by gurelsoycaner** [angular/components#30252]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm getting a datetimepicker component error like
 [ERROR] TS2305: Module '"@angular/material/core"' has no exported member 'CanUpdateErrorState'
after updating to NG19;

I gat several error but all abt datetimepicker I guess
Error like :-
    node_modules/@angular-material-components/datetime-picker/lib/date-range-input-parts.d.ts:81:74:
      81 │ ..."@angular/material/core")._Constructor<CanUpdateErrorState> & i.

   node_modules/@angular-material-components/datetime-picker/lib/date-range-input-parts.d.ts:81:143:
      81 │ ...gular/material/core")._AbstractConstructor<CanUpdateErrorState>...
         ╵                          ~~~~~~~~~~~~~~~~~~~~

How do I fix this, pls help.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

   node_modules/@angular-material-components/datetime-picker/lib/date-range-input-parts.d.ts:81:143:
      81 │ ...gular/material/core")._AbstractConstructor<CanUpdateErrorState>...
         ╵                          ~~~~~~~~~~~~~~~~~~~~

### Actual Behavior

   node_modules/@angular-material-components/datetime-picker/lib/date-range-input-parts.d.ts:81:143:
      81 │ ...gular/material/core")._AbstractConstructor<CanUpdateErrorState>...
         ╵                          ~~~~~~~~~~~~~~~~~~~~

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
This is an issue with the `@angular-material-components/datetime-picker` package, not `@angular/material`. Closing the issue since we don't own that package.

**Comment by faraz-ahmad-uft** [comment]
@gurelsoycaner - I am facing the same issue. Could you please share your solution with me. Thanks.
