### ISSUE TITLE
[Tooltip] Continously shows/hides on certain container structure

### ISSUE THREAD

**Issue by bstaley** [angular/components#3040]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tooltip should show only once while being moused over

#### What is the current behavior?
When a tool-tip is positioned like the following it keeps show and hiding as you mouse over.
```
|-- div- fixed bottom right
        |-- div- relative
                |-- div- absolute 
                        |-- a md-mini-fab mdTooltip
```
#### What are the steps to reproduce?

just mouse over the md-mini-fab 
http://plnkr.co/edit/0qDDaLCMPeMYgElQeLhg

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, browsers are affected?
Failed on Chrome(latest), IE(Latest) and Edge(latest). ng-version 2.4.7

#### Is there anything else we should know?
No

**Comment by bradrich** [comment]
+1

**Comment by kostenko** [comment]
Same here

**Comment by jelbourn** [comment]
Tried this out with the latest version and couldn't reproduce, so it's likely been fixed
https://stackblitz.com/edit/angular-aswf7q?file=src/app/tooltip-auto-hide-example.html
