### ISSUE TITLE
[Tabs] Ink bar is not correctly aligned on init

### ISSUE THREAD

**Issue by VitalyVrublevskyy** [angular/components#3048]
#### Bug, feature request, or proposal:
Bug (Some different than https://github.com/angular/material2/issues/3044)

#### What is the expected behavior?
Highlighter [md-ink-bar] should invalidate position on init app

#### What is the current behavior?
Misaligned [md-ink-bar]. Please see attached image.

#### What are the steps to reproduce?
_Case 1_
1. Open demo application from material2 
2. Navigate to tabs (Especially for _Tab Nav Bar_ with routing example)
3. Apply **md-stretch-tabs** directive for <nav> and apply  styles for tab items 
`[md-stretch-tabs] [md-tab-link] {
  flex-basis: 0;
  flex-grow: 1;
}`
4. Try to expand / collapse application sidebar.

_Case 2_ (or _just apply attached git patch._ )
1. Open demo application from material2 
2. Setup  <md-sidenav **mode="side" opened="true"**>  for root app container.
3. Navigate to tabs (Especially for _Tab Nav Bar_ with routing example)
4. Apply **md-stretch-tabs** directive for <nav> and apply  styles for tab items 
`[md-stretch-tabs] [md-tab-link] {
  flex-basis: 0;
  flex-grow: 1;
}`
5. Select not first tab
6. Refresh page

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Patch: [MD_TabBar_issue.patch.zip](https://github.com/angular/material2/files/767999/MD_TabBar_issue.patch.zip)

#### Which versions of Angular, Material, OS, browsers are affected?
Based on  up to date sources of [material2](material2)

#### Is there anything else we should know?
![image](https://cloud.githubusercontent.com/assets/8617175/22847714/8a2d1702-eff7-11e6-94e7-30b8da6aeaff.png)

**Comment by jarekskuder** [comment]
Same here on iOS 10.3.2 cordova app

**Comment by levz0r** [comment]
Hi,
Any plans to fix this?

**Comment by Anderman** [comment]
Is there a workarond for this?

**Comment by Anderman** [comment]
I have this workarond
```typescript
  @ViewChild(MatTabNav) public matTabNav: MatTabNav;
  public ngOnInit() {
    setTimeout(() => this.matTabNav._alignInkBar(), 0);
  }

```

**Comment by bentaly** [comment]
This has changed to `_alignInkBarToSelectedTab` in Angular 8

**Comment by dhair-seva** [comment]
This is happening to me, because my sidebar for the entire app has a width change on route change, so if I have a mat-tab-group in any page, I would have to implement this, which means, I would have to do this in over 10+ pages. This workaround is not a good fix. Is there any other fix?

**Comment by omaracrystal** [comment]
I also have ran into this issue. The mat-ink-bar does not recalculate when there is a material side nave with the mode set to "side". Here is my work around with css (I am hiding the mat-ink-bar and using &:after styling):

```
.mat-tab-label {
  margin: 0 16px;

  .mat-tab-label-content {
    font-weight: 500;
    color: $blue-grey-1;
  }

  &.mat-tab-label-active {
    .mat-tab-label-content {
      font-weight: bold;
      color: black;

      &:after {
        content: '';
        display: block;
        position: absolute;
        width: 100%;
        height: 2px;
        background: $blue-3;
        right: 0;
        bottom: 0;
      }
    }
  }
}

mat-ink-bar {
  display: none !important;
}
```

**Comment by IgorKurkov** [comment]
So it does not work till now. 
Workaround by @Anderman with `ngAfterViewChecked()` works but might cause performance problems.
In my case content loads, and causes a vertical scrollbar, it resizes the page a bit (but `window.onresize` doesn't catch this resize event, so can't catch it yet), and sets the wrong alignment to mat-ink. My workaround - listen for routing event, wait for content loading by setTimeout with 1sec delay and realign mat-ink. But it is awful :) wait for a better neat solution
```
@ViewChild('matTabsRef', { static: false }) matTabsRef: MatTabNav;

fixResizeInkBar() {
  setTimeout(() => {
      if (this.matTabsRef) {
        this.matTabsRef._alignInkBarToSelectedTab();
      }
    }, 1000);
}

private listenRoutes(): void {
    this.subs.add(
      this.router.events
        .pipe(
          filter((event) => event instanceof NavigationEnd),
          startWith(true)
        )
        .subscribe((event) => {
          this.fixResizeInkBar();
        })
    );
  }
```

**Comment by pavanteja90** [comment]
Workaround by @Anderman works but ngAfterViewChecked gets called for every interaction by the user (which is a lot - You can test this by console logging in ngAfterViewChecked() method). To avoid this performance issue, I've used ngAfterViewInit() which gets called once after the view is initialised and added a delay of 100ms to setTimeout:

`
	@ViewChild("matTabNav") matTabNav: MatTabNav;
	ngAfterViewInit(): void {
		console.warn("CHecked");
		setTimeout(() => this.matTabNav._alignInkBarToSelectedTab(), 100);
	}
`

**Comment by simeyla** [comment]
This can be even worse if the control is not visible on init. 
That ends up giving you `width: 0px` for the ink bar making it look like it just isn't working at all.

For some cases the following can be a temporary fix.

```
nav.mat-tab-nav-bar 
{
    ::ng-deep .mat-ink-bar
    {
        min-width: 160px;
    }
}
```

Note: I'm using `mat-tab-nav-bar` as opposed to `mat-tab-group` but they use the same underlying ink bar.

**Comment by Melf11** [comment]
thie mat-ripple-element ist causing this issue. I don't know what the mat-ripple-element is doing exactly, but for me it's not necessary, so do:

```
.mat-ripple-element {
  display: none !important;
}
```
