### ISSUE TITLE
autocomplete panel doesn't pop up when triggering focus on the input programatically

### ISSUE THREAD

**Issue by fxck** [angular/components#3106]
see https://gist.run/?id=19eec6a0d5c69d65dbb847b12009ca9f, it starts working only after you do it the second time 

@kara

**Comment by willshowell** [comment]
I'm not at all familiar with using `ngZone`, but it seems like this change fixes it
```
autocomplete.ts


/** Panel should hide itself when the option list is empty. */
_setVisibility() {
  // Promise.resolve().then(() => this.showPanel = !!this.options.length);
  this.zone.run(() => this.showPanel = !!this.options.length);
}
```

**Comment by bergben** [comment]
Is there any workaround for this for now?

**Comment by willshowell** [comment]
The issue actually seems to be that clicking a button to focus the autocomplete triggers an `_outsideClickStream` event just after it has been opened, thus causing it to immediately close.

You can use a setTimeout to focus it after the outside click event fires.

http://plnkr.co/edit/cKYxnL9f8hV2Uklucd5d?p=preview

**Comment by willshowell** [comment]
Alternatively use `stopPropagation()` on the click event

http://plnkr.co/edit/m4W7zAGulSaxhPqqlpzp?p=preview

**Comment by willshowell** [comment]
Here's an updated plunker https://plnkr.co/edit/gyarTLKwyt97CX9304Fd?p=preview

**Comment by bruteforce** [comment]
Below code did the trick for me assuming focus is already on input field. 
```
import { MdAutocompleteTrigger} from '@angular/material';

@ViewChild(MdAutocompleteTrigger) trigger;

this.trigger._onChange("");
this.trigger.openPanel();
```

**Comment by mpolutta** [comment]
Combined willshowell and bruteforce solutions to solve for our 508 compliance scenario. Clear button is another scenario:
  openAutoSearchPanel() {
    if (this.searchText.length === 0) {
      this.autoSearchInputTrigger._onChange('');
      this.autoSearchInputTrigger.openPanel();
    }
  }
  clearSearchText() {
    console.log('>>> clearing searchText');
    this.searchText = '';
    /// hack: Another reported workaround - Allow the ClickStream to finish executing via setTimeout.
    ///   https://github.com/angular/material2/issues/3106
    setTimeout(() => {
      this.autoSearchInput.nativeElement.focus();
      this.openAutoSearchPanel();
    });
  }

**Comment by Charius** [comment]
yeah, got the same issue while implement custom field with autocomplete, timeout works, but this is pretty weird

**Comment by 1083** [comment]
Any update on this...?

**Comment by BBK-PiJ-2016-11** [comment]
+1, any updates?

**Comment by mischkl** [comment]
This problem also affects chiplist inputs with autocomplete. 😢

**Comment by RajendrasinhParmar** [comment]
Is there any workaround or fix for this issue?
I'm having a dropdown that fetches data dynamically from the server. When I click on the chip-list field it doesn't open autocomplete list until I input any character in that.

**Comment by hukacode** [comment]
> This problem also affects chiplist inputs with autocomplete. 😢

Me too, do you have any workaround?

**Comment by mischkl** [comment]
I got it working with the following:

```html
<input (focus)="onFocus()" ... >
```

```ts
@ViewChild(MdAutocompleteTrigger) trigger;

onFocus() {
  this.trigger._onChange(""); 
  this.trigger.openPanel();
}
```

**Comment by RajendrasinhParmar** [comment]
Thank you for response. I'll try this solution and will check if this works.

Just for a note that I'm fetching the list from REST API.

**Comment by hukacode** [comment]
Thanks @mischkl 
I changed to (click) and it's worked.

Regards,
Huka

**Comment by RajendrasinhParmar** [comment]
Thank you @mischkl 👍 that solution worked 😄

**Comment by ozgursarikamis** [comment]
> I got it working with the following:
> 
> ```
> <input (focus)="onFocus()" ... >
> ```
> 
> ```ts
> @ViewChild(MdAutocompleteTrigger) trigger;
> 
> onFocus() {
>   this.trigger._onChange(""); 
>   this.trigger.openPanel();
> }
> ```

great! thanks

**Comment by omaracrystal** [comment]
> ```ts
> @ViewChild(MdAutocompleteTrigger) trigger;
> ```

Is there any other part missing from this? It's not working for me :(

**Comment by lucas-sesti** [comment]
Hey, im trying to use the MatAutocompleteTrigger and openPanel, but, the function openPanel is undefined... how can i open the open from trigger?

**Comment by thematho** [comment]
@lucas-sesti this works for me:
```
@ViewChild(MatAutocompleteTrigger, { static: true }) trigger: MatAutocompleteTrigger;
// ****
 onClick(){
      this.trigger.openPanel();
} 

```

**Comment by PanchakshariPM** [comment]
import { MatAutocompleteTrigger } from '@angular/material/autocomplete';

Is the above import correct?

**Comment by idotj** [comment]
Quick fix in case you have more than 1 <mat-autocomplete> in your component:

In your .html
`<input (focus)="onFocus(0)" ... >
<input (focus)="onFocus(1)" ... >
<input (focus)="onFocus(2)" ... >`

In your .ts
`import {ViewChildren, QueryList} from '@angular/core';
import {MatAutocompleteTrigger} from '@angular/material/autocomplete';

@ViewChildren(MatAutocompleteTrigger) autoComplete: QueryList<MatAutocompleteTrigger>;

onFocus(value){
this.autoComplete['_results'][value]._onChange('');
this.autoComplete['_results'][value].openPanel();
}
`

Still this is a patch, in my case I discovered time after, that the problem was how data arrived after the first filter was executed. So I didn't use this solution anymore.

Here the link where another dev had the same problem.
I hope will help someone:
https://stackoverflow.com/questions/52536382/how-to-show-autocomplete-options-on-focus

**Comment by marcusshepp** [comment]
Will this ever get fixed?

**Comment by Lms24** [comment]
How is this bug still open? This is a seriously annoying bug which requires an annoying workaround when used together with reactive forms.

**Comment by mischkl** [comment]
Glad to see it finally got fixed! 🥳 Thanks @andrewseguin
