### ISSUE TITLE
MdDialog width configuration uncenter dialog.

### ISSUE THREAD

**Issue by yudielcurbelo** [angular/components#3239]
#### Bug, feature request, or proposal:
Bug: MdDialog not centered when is open passing a configuration of a custom width.

#### What is the expected behavior?
MdDialog should be the size of the specified width but keep his center location.

#### What is the current behavior?
MdDialog is being moved to the left.

#### What are the steps to reproduce?
[https://plnkr.co/edit/fvG6lS8VIihJUlfu01Bv?p=preview](https://plnkr.co/edit/fvG6lS8VIihJUlfu01Bv?p=preview)

`openDialog() {
    this.dialog.open(DialogOverviewExampleDialog, {
      width: '600px'
    });
}`

![image](https://cloud.githubusercontent.com/assets/15385920/23214509/ee9927ec-f8dc-11e6-812d-e7bf2c6d29c2.png)

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.2
Chrome in Windows

**Comment by crisbeto** [comment]
This happens when the dialog hits the max width and is an issue with how we have the dialog set up in general. I'll be reworking it once https://github.com/angular/material2/pull/3184 is merged.

**Comment by ryanpm40** [comment]
@crisbeto Is there a known workaround for this at the moment? Is there a way to apply styling to ".mat-dialog-container" that I'm unaware of? When I attempt to set a style to that class in my styleUrl sheet, it is ignored, since it is launched after the page is loaded from a button click.

**Comment by crisbeto** [comment]
There is no nice workaround @ryanpm40. Technically adding a `max-width` to the `.cdk-overlay-pane` should fix it, but the `cdk-overlay-pane` is used for all overlay-based Material components. Now that #3184 is merged, I can do a proper fix for it, though.

**Comment by ryanpm40** [comment]
@crisbeto Gotcha, thanks for the update! I suppose another temporary option for me would be to use some javascript to get the class element (but obviously not very ideal):

`document.getElementsByClassName('mat-dialog-container')[0];`

Looking forward to those changes :)

**Comment by MA-Maddin** [comment]
adding `margin: auto` to `.mat-dialog-container` makes it centered.

https://github.com/angular/material2/blob/70b31f177a2dacfd08f47b2a8898fca3f7bb91f9/src/lib/dialog/dialog.scss#L19

**Comment by willshowell** [comment]
As another solution, you can add a `panelClass` to the dialog and then apply whatever css just to that specific dialog.
```ts
this.dialog.open(MyDialogComponent, {
  panelClass: 'my-full-screen-dialog',
  data: { ... }
});
```
```scss
.my-full-screen-dialog .mat-dialog-container {
  max-width: none;
  width: 100vw;
  height: 100vh;
}
```

**Comment by zijianhuang** [comment]
thanks willshowell. This works well, and elegantly enough.

**Comment by julianobrasil** [comment]
@willshowell , I was testing the feature above, but I must be doing something terribly wrong. I tried to change background color of the backdrop panel and/or of the panel, but it seems to have no efect.

Is it working properly? Plunker: https://plnkr.co/edit/OjPQdv6Txqcn1v5nXG3p?p=preview

**Comment by willshowell** [comment]
@julianobrasil the styles must be global or without view encapsulation 😁

https://plnkr.co/edit/lGFjGSmhlr9tOoHK1gJp?p=preview
