### ISSUE TITLE
Morphable icons

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [angular/components#3275]
Hey guys, I'm wondering if you have any plans to—somehow—allow for morphable icons, I think that would be a pretty cool feature to have:
https://github.com/angular/material/issues/2993

Perhaps similar to how this directive over here works (which uses SVG Morpheus): https://github.com/klarsys/angular-material-icons

Thanks in advance!

**Comment by jelbourn** [comment]
Closing this since it's not something I ever see us doing.
