### ISSUE TITLE
[Autocomplete] Restrict selection to given set of items

### ISSUE THREAD

**Issue by julianobrasil** [angular/components#3334]
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
md-autocomplete could have an option to force selection. I think it's not in the design doc, but near 50% of the autocompletes I've used must had to force selection.

**EDITED:** When the requested "force selection" option is set to true, it could clear the input (and any bound property) if the user types something in and moves the focus to other component without selecting one of the options shown on the opened panel (if there are no sugestions, the input is also cleared on the blur event).

#### What is the current behavior?
**EDITED:** The feature is not achievable direclty from the component. _In one single project I'm working on, I have about 15 md-autompletes, and 11 of them must force selection. Currently I got this feature by two steps:_

_1. checking (in the intput's valueChanges observable) wether the value is an object - that I save in a private result property - or a regular string - that is ignored, by clearing up the same private result property (basically the input value is an object just when I select one option from the opened panel otherwise it is just a regular string that must be ignored)_

_2. in the blur event I verify wether the private result property is cleared or has a value (if it's cleared, I also clear the input)._

_Another way to do that is comparing what was typed to what came from the async server search - but I'm not sure if either of these aproaches is the best solution not wether it's suitable to the case of a search made directly in an in-memory array instead of bringing results fom a remote server. There are too many confusing workarounds to make it do what you want. I'm worried about the future, when I eventualy have to change anything in this code - it will be very time-consuming to remember all of this. There would be much less pain if, in a year from now **I could just look at the component and see something like forceSelection="true"**_.

**Comment by crisbeto** [comment]
Could you give an example of how it would work? The menu wouldn't close unless you select something?

**Comment by julianobrasil** [comment]
@crisbeto, If the user began to type and left the input without selecting one of the options shown in the opened panel, it would clear the input (and the binded property).

**Comment by crisbeto** [comment]
Thanks, that makes a bit more sense.

**Comment by rosslavery** [comment]
Basically a hybrid between a selectbox and an autocomplete. Can be thought of as:
* A `select` with a search feature or..
* An autocomplete that only allows values from the suggestion box.

**Comment by fxck** [comment]
I've hacked around this by checking whether the model value is an object (given that my items are actually objects) on blur, if it's a string, it means autocomplete was blurred without selecting an option (the value will be a string). But it's nowhere near ideal, it requires `setTimeout`s, as the value immediately after blur will still be a string even if you actually click on an item, as it needs some time to propagate.

**Comment by julianobrasil** [comment]
@fxck I had forgotten to mention the `setTimout`s. I had to use them too.

**Comment by badre429** [comment]
i agree with @rosslavery i real world app md-select has avg > 50 elements therfore its more productive to use autocomplete   that only allows values from the suggestion box.

it heard breaking to see your users scrool al the way down to select element

**Comment by fxck** [comment]
@badre429 @rosslavery there's a different feature for that https://github.com/angular/material2/pull/3211

**Comment by badre429** [comment]
@fxck  its a just pull request 
for me ***md-select*** with ***md-select-header*** to enable search plus clean buttun [x] it will be perfect form my apps

**Comment by gedclack** [comment]
Excuse me, how do you guys make a selection (from hundreds of options) without the discussed `md-select-header` ?
by using autocomplete? <-- but this is not built for doing that, right?

**Comment by julianobrasil** [comment]
This is an example of a email search input. As the user types an email it goes to the database, grab the suggestions and show to the user. If the user left the component without selecting one of them, it clears out the typed characters.

Template:
```
<md-input-container class="full-width">
   <!-- this the actual input control -->
   <input mdInput [formControl]="acpEmailControl" [mdAutocomplete]="acpEmail" type="text" placeholder="email" autocomplete="off"
   (blur)="checkEmailControl()" autofocus required>
   <!--this is to do an animation while search for the typed characters-->
   <span mdPrefix>
   <i [style.visibility]="showEmailSearchSpinner" class="fa fa-refresh fa-spin" style="font-size:14px;color:black;margin-right:5px"></i>
   </span>
</md-input-container>
<md-autocomplete #acpEmail="mdAutocomplete" [displayWith]="displayEmailFn">
   <md-option *ngFor="let user of usersFromDatabase" [value]="user" [style.font-size]="'0.7rem'">
      <div>
         {{ user?.userName }}<div style="float: right">{{user?.email}}</div>
      </div>
   </md-option>
</md-autocomplete>
```

Typescript code:

```
public acpEmailControl: FormControl = new FormControl();
private emailSearchSubscription: Subscription;
public showEmailSearchSpinner = 'hidden';
public usersFromDatabase: User[] = [];
public chosenUser: User;

ngOnInit() {
   // unsubscribe in ngOnDestroy
   this.emailSearchSubscription = this.acpEmailControl.valueChanges
      .startWith(null)
      .map((user: User | any) => {
        if (user && (typeof user === 'object')) {
          this.chosenUser = user;
        } else {
          this.chosenUser = new User();
        }

        return user && typeof user === 'object' ? user.userName : user;
      })
      .debounceTime(300)
      .switchMap<string, User[]>((typedChars: string) => {
        if (typedChars !== null && typedChars.length > 1) {
          this.showEmailSearchSpinner = 'visible';
          //  Observable that goes to the database grab for the
         //  users with email or name based on typedChars
          return this.userService.findLikeNameOrEmail(typedChars);
        } else {
          this.showEmailSearchSpinner = 'hidden';
          return Observable.of<User[]>([]);
        }
      })
      .subscribe((value: User[]) => {
        this.showEmailSearchSpinner = 'hidden';
        if (value.length > 0) {
          this.usersFromDatabase = value;
        } else {
          this.usersFromDatabase = [];
        }
      },
      err => console.log('error'));
}

// clears out the input if the user left it (blur event) without
// actually choose on of the options presented in the list
// The setTimeout is because the blur event propagates
// faster then input changes detection 
// (see @fxck comment above)
checkEmailControl() {
    setTimeout(() => {
      if (this.chosenUser.email === '') {
        this.acpEmailControl.setValue(null);
      } 
    }, 300);
  }

  displayEmailFn(user: User) {
    return (user && user.email && (user.email !== '')) ? user.email : '';
  }
```

**Comment by gedclack** [comment]
@julianobrasil thanks for showing me the codes :+1: 
I will try it now in my project.
*to reduce data transfer, is it a good idea if I load all the options in ngOnInit() and put it in a variable, then just filter that array with every valueChanges?
*which is better, to use FormControl and subscribe valueChanges like you did above, or just put (ngModelChange)="InputChanged()" in the template?

Thanks in advance, I am new to Angular and Angular Material.

**Comment by julianobrasil** [comment]
@gedclack, yes, you can choose the approach of saving the user's bandwith putting all in memory. It depends on what type machines you expect your clients to have. In my environment the most common type are PC's with low memory and Microsoft office applications running with lot's of small documents. They usually have a bad ui experience with anything you use, but I think saving some memory was a better approach to follow.  In this case I also have the benefit of delegating to the data server the work of filtering the array for me. An also, data transfer is not a significant problem for me.

You can change the code to use ngModelChage, but you'd have to add some extra code to do equivalent things as .debounce(300), which is available for the valueChanges observable.

Both points may be good for larger discussions. Try asking them on [stackoverflow.com](www.stackoverflos.com) to get more help with that (I've already heard a lot of "here is not the right place for this kind of question" in many posts. Let's avoid get lectured by moderators).

**Comment by gedclack** [comment]
@julianobrasil yep, better not to do long discussions here :) , your approach makes sense for me, but I choose to use ngModelChange and filter the array of options I put in a variable as the page load for the first time because my end users will access this Web App via Android Devices from remote locations with weak signal coverage, so I need it to send or receive data as small as possible everytime they submit something without the need to reload the entire page. Nice chat :+1:

**Comment by willshowell** [comment]
Here is a solution that doesn't require setTimeout:

```ts
this.trigger.panelClosingActions
  .subscribe(e => {
    if (!(e && e.source)) {
      this.stateCtrl.setValue(null)
      this.trigger.closePanel()
    }
  })
```

https://plnkr.co/edit/VWcGei7HxHYnncpzyYfW?p=preview

**Comment by julianobrasil** [comment]
Much... much better... setTimeouts always smelled like a fragile workaround to me.

**Comment by kleber-swf** [comment]
I created a [`Validator`](https://angular.io/guide/form-validation#custom-validation) to give an error if no option was selected. I know this is not the solution for this feature request, but it can be used as an alternative.

**Comment by kleber-swf** [comment]
But I have to admit, the @willshowell solution is much better 👍

**Comment by willshowell** [comment]
@jelbourn what are you thoughts api-wise for something like this? 

* `forceSelection` vs. `requireMatch`?
* Does it clear the input or set a validation error if blurred without a selection?
* Should the attribute belong on the trigger or the autocomplete?
* Is there an accessibility story?

**Comment by julianobrasil** [comment]
@willshowell, is there a difference between **`forceSelection`** and **`requireMatch`**? Or is it just a matter of names?

**Comment by willshowell** [comment]
@julianobrasil haha yeah just another name. I was also looking around at other implementations and saw [`md-require-match`](https://material.angularjs.org/latest/api/directive/mdAutocomplete) is used in Material 1 and in [Covalent chips](https://teradata.github.io/covalent/#/components/chips), so just a suggestion 😄 I have no preference either way... I would be content with anything better than the current workaround.

**Comment by julianobrasil** [comment]
In this case I'd go with `md-require-match` to keep it compatible with Material 1.

**Comment by jelbourn** [comment]
I fired off a query to our Google a11y team to see if this can be done in an accessible way, since the W3C description for `combobox` is ambiguous as to whether arbitrary text entry is _required_ or _allowed_.

**Comment by willshowell** [comment]
@jelbourn any feedback from the a11y team?

**Comment by jelbourn** [comment]
Unfortunately not yet

**Comment by thw0rted** [comment]
Thanks @willshowell for the example -- based on this, I was able to check `this.trigger.activeOption` to force selection when leaving focus:

    if (this.trigger.activeOption) {
      this.stateCtrl.setValue(this.trigger.activeOption);
      this.trigger.closePanel();
    }

Now I just need to focus the first suggestion after every list change and I'll have some reasonable UX for the interface.  (I have the luxury of ignoring a11y because my project is built around displaying maps.)

**Comment by julianobrasil** [comment]
Well, It seems something has changed in beta.12, it's not working anymore in the same way it did in beta.11: https://plnkr.co/edit/UsxFJSREpyJJCuOj0kHT?p=preview

**Comment by julianobrasil** [comment]
@crisbeto explained to me (https://github.com/angular/material2/issues/8093#issuecomment-340196775) what trigger.activeOption suppose to do and it's working as expected: 

https://stackblitz.com/edit/autocomplete-force-selection

**Comment by willshowell** [comment]
I don't really undertand the w3c documentation/drafting process, but I see [here (in what seems to be deleted archive section?)](https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#autocomplete) that the term is "editable" vs "non-editable" auto-complete.

> A text box and an associated drop-down list of choices where the choices offered are filtered based on the information typed into the box. Typically, an icon associated with the text box triggers the display of the drop-down list of choices. An editable auto-complete accepts text entry of choices that are not in the list. An example of an editable auto-complete is the URL field in the browsers.
> ...
> * Moving focus out of an auto complete field that does not contain a valid entry should either invoke an error or if a default value was initially assigned, reset the value to the default value.

There seem to be other considerations that would signal that a selection from the autocomplete dropdown is required:

> In a non-editable auto-complete, any letters that do not result in a match from the list are ignored. The drop down list of choices remains static until the user presses:
> * Escape to clear the text field
> * Backspace to remove some of the letters previously typed
> * an additional letter that results in a valid list of choices.

**Comment by julianobrasil** [comment]
One step forward: #8533

**Comment by lippomano** [comment]
Using this way I have an error:  `Cannot read property 'panelClosingActions' of undefined`
The code is inside the ngAfterViewInit().
And of course I already have   `@ViewChild(MatAutocompleteTrigger) trigger: MatAutocompleteTrigger;`

**Comment by julianobrasil** [comment]
@lippomano, are you sure you're not trying to access it too soon? Like in the `OnInit` instead of in the `AfterViewInit` handler; or right after the component become visible caused by a `*ngIf` switching to true.

**Comment by thw0rted** [comment]
I had this problem until I took it out from under an element that had an `*ngIf` -- trying to get a ViewChild on an element that's only there sometimes is more trouble than it's worth.  Better to convert the ancestor element to a `[hidden]` or similar.

**Comment by julianobrasil** [comment]
Alternatively you can use some setTimeouts. It really depends on how your app behaves.

**Comment by julianobrasil** [comment]
It seems @willshowell's solution is working fine since 5.0.2: https://stackblitz.com/edit/autocomplete-force-selection-tests

Thanks, @crisbeto.

**Comment by rafaelss95** [comment]
@julianobrasil It seems like your demo is broken because you forgot to import `rxjs` operators.

[Here's a working version](https://stackblitz.com/edit/autocomplete-force-selection-tests-w2fqww).

**Comment by julianobrasil** [comment]
Thanks,  @rafaelss95. I accidentally removed some `rxjs` imports during the final cleaning up in the demo code.

**Comment by MarkGunlogson** [comment]
My proposal was removed as dupe, but I feel using a validator would make the feature more congruent with Angular's built-in form validation since we're essentially marking the field invalid by clearing it on blur. @kleber-swf proposed using a validator and I went the same route in the commercial codebase I'm working with. It's simple and works great. IMO, clearing the field is not as user friendly and I argue that you could 'validate' any text field by clearing invalid input on blur but it's not always going to be the best user experience. =)

Also, one of the requirements I'm handling in our codebase is that the valid options can change over time. Clearing what the user typed in will not work in this use-case since it's important to see what was there before. Since the Autocomplete attaches to a regular form input field I would prefer it act like one, where I can set arbitrary values but they won't necessarily be valid. To me this is a difference of opinion primarily over whether an autocomplete should act more like a select or a text input. 

Another argument for a validator is that people who do data-entry will get used to typing in the whole value and quickly tabbing to the next field. Losing the whole field if you have a typo is annoying compared to shift-tab to correct a mistake.

I'll appreciate the feature however it gets realized, but If the Material team decides to go the validator route @kleber-swf has an implementation and I have one that I can probably get cleared as an OSS contribution.

**Comment by rosslavery** [comment]
If the intention is to limit a user's input to one of the suggestions, then why even _allow_ a user to type in arbitrary text and have it commited to the model, only to have it be validated, and then show them an error message.

I genuinely think the better UX leans towards what I mentioned in my comment [way back in February](https://github.com/angular/material2/issues/3334#issuecomment-283122114).

Which is, a "select with a search feature". There are countless libraries on the internet that provide an acceptable level of UX while accomplishing what people have been wanting now for quite some time. See: select2, chosen, selectize, etc, etc.

I respectfully think that there's a bit too much navel-gazing / bikeshedding regarding this issue. Back and forth with the a11y team, discussing not-yet-implemted w3c standards. Throughout the development material2, many other components and features have been implemented in a WIP state and improved upon later.

Perhaps it will be resolved by [this PR](https://github.com/angular/material2/pull/7835) allowing for a custom `mat-select` header.

**Comment by julianobrasil** [comment]
IMO both select with a search feature and an autocomplete with a force selection are very welcome. 

Sometimes you want to keep your options updated with a server database or simply don't want to load all of your possible options at once (to filter them later when the user types in). I this cases, the autocomplete with a force selection options would be more suitable. Otherwise the select filter would be perfect.

**Comment by thw0rted** [comment]
Juliano hits the nail on the head -- "searchable select" is not helpful for cases where your options number in the hundreds to thousands.  If nothing else, just passing a few thousand `<option>` tags to the HTML parser can result in multiple-second page loads, especially on older / slower clients (and I speak from experience).  The use case for "one of a list of thousands of items, which must already exist on the backend" is definitely not uncommon.

**Comment by rosslavery** [comment]
I don't think searchable select necessarily implies that all `<option>` tags be in the DOM at once. Most of the libraries I mentioned above (select2, chosen, etc), while not perfect, have the ability to _behave_ like a select, while still loading options in async from an endpoint.

To me the difference between autocomplete and searchable select is that autocomplete offers a list of suggestions to complete your input for you, while still allowing arbitrary text to be sent to the model --
 both during typing, and after selecting an item from the suggestion list.

A searchable select shows a list of suggestions based on the user's input, but will not commit the search query itself to the model -- it only saves to the model if the user selects from one of the options.

**Comment by kylecordes** [comment]
@rosslavery @thw0rted @julianobrasil  I have published some code (and the running demo) which achieves some of what is discussed here. It is a searchable select, but it is designed to be able to work with server-side data sources. It can be used to search a list vastly larger than you would ever load in the DOM. It is used for exactly these kind of use cases. The documentation and demo are pretty rough, but the code behind it as well proven.

It is more of a searchable select, and less of an autocomplete, and that it only allows values which the functions provided by the developer (presumably to talk to a backend server) approve of.

https://github.com/OasisDigital/angular-material-obs-autocomplete

demo:

https://oasisdigital.github.io/angular-material-obs-autocomplete/

**Comment by kylecordes** [comment]
Update to the above - I had a large improvement to that thing that I had not yet pushed to Github. I had updated the demo but not the code. Ooops. It is now pushed. If you're interested in a server-side capable auto complete, take another look.

**Comment by MarkGunlogson** [comment]
It seems we have several different approaches and implementation for each. I would prefer a validator but I'm fine with anything, can someone from ng team please make the call so we can open a PR for the relevant implementation? We're getting pretty close to this issue's first birthday.

**Comment by lippomano** [comment]
@julianobrasil , @rafaelss95 I am using your solution but I am in angular 4.4.x and I have a problem, when I select an option suggested in the autocomplete and then click tab to go in the next field I see the autocomplete field empty ( It triggers the panelClosingActions at Tab)  
`this.subscription = this.trigger.panelClosingActions
      .subscribe(e => {
        if (!e || !e.source) {
          this.stateCtrl.setValue( null);
        }
      },`

**Comment by julianobrasil** [comment]
@lippomano, unfortunatelly, there was a bug that was fixed in **Material 5.0.2** (the fix was finalized in **5.0.3**) that causes the problem you're describing. And Material 5 **depends on Angular 5**. You'll have to upgrade everything or step away from `panelClosingActions` for this purpose. In this case you'll have to work with some `setTimouts` to get the force selection feature (the code becomes a little messy without `panelClosingActions` - I personally don't like it).

**Comment by vlio20** [comment]
I have created a small directive, inspired by @julianobrasil stackblitz demo and solution using the trigger panelClose event: 
template:
```
<input matInput
             autoClose
             [control]="ctrl"
             [autoCompleteRef]="autoSalesRep"
             placeholder="Blarg..."
             [matAutocomplete]="auto"
             [formControl]="ctrl">
<mat-autocomplete #auto="matAutocomplete">
            <mat-option *ngFor="let item of items" [value]="item">
              <span>{{item}}</span>
            </mat-option>
 </mat-autocomplete>
```
autoClose directive:
```
@Directive({
  selector: '[autoClose]'
})
export class AutoCloseDirective implements AfterContentInit {

  @Input() control: FormControl;
  @Input() autoCompleteRef: MatAutocomplete;

  subscription: Subscription;

  constructor(@Host() @Self() private readonly autoCompleteTrigger: MatAutocompleteTrigger) {
  }

  ngAfterContentInit() {
    if (this.control === undefined) {
      throw Error('inputCtrl @Input should be provided ')
    }

    if (this.autoCompleteRef === undefined) {
      throw Error('valueCtrl @Input should be provided ')
    }

    setTimeout(() => {
      this.subscribeToClosingActions();
      this.handelSelection();
    }, 0);
  }

  private subscribeToClosingActions(): void {
    if (this.subscription && !this.subscription.closed) {
      this.subscription.unsubscribe();
    }

    this.subscription = this.autoCompleteTrigger.panelClosingActions
      .subscribe((e) => {
          if (!e || !e.source) {
            this.control.setValue(null);
          }
        },
        err => this.subscribeToClosingActions(),
        () => this.subscribeToClosingActions()
      );
  }

  private handelSelection() {
    this.autoCompleteRef.optionSelected.subscribe((e: MatAutocompleteSelectedEvent) => {
      this.control.setValue(e.option.value);
    });
  }
}

```

**Comment by mustafarian** [comment]
@vlio20 Thanks for the directive idea/code. It's the least intrusive approach IMO. 

You can simplify it a little by injecting `NgControl` into your directive and leaving it out or the inputs. Also I used `matAutocomplete`  which is already defined in the input instead of adding `autoCompleteRef` and it worked just the same.

This is how it looked after I made these changes.

```
<input matInput
             enforcedInputs
             placeholder="Blarg..."
             [matAutocomplete]="auto"
             [formControl]="ctrl">
  <mat-autocomplete #auto="matAutocomplete">
            <mat-option *ngFor="let item of items" [value]="item">
              <span>{{item}}</span>
            </mat-option>
 </mat-autocomplete>
```
and the relevant bits from the directive

```
export class EnforcedInputsDirective implements AfterContentInit {

    @Input()
    matAutocomplete: MatAutocomplete;

    constructor( @Host() @Self() private readonly autoCompleteTrigger: MatAutocompleteTrigger, private control: NgControl) {
    }

    private subscribeToClosingActions(): void {
        if (this.subscription && !this.subscription.closed) {
            this.subscription.unsubscribe();
        }

        this.subscription = this.autoCompleteTrigger.panelClosingActions
            .subscribe((e) => {
                if (!e || !e.source) {
                    this.control.control.setValue(null);
                }
            },
            err => this.subscribeToClosingActions(),
            () => this.subscribeToClosingActions());
    }
.....
}
```

**Comment by vlio20** [comment]
@mustafarian didn't know about the NgControl options. Indeed it is better.

**Comment by hbthanki** [comment]
@mustafarian the code is working and handling the valid value scenario only if user tabs out. However, if user clicks on autocomplete and clicks somewhere else, it will still clear.
This is working :
`if (!e || !e.source && !(e instanceof MouseEvent)) {`

**Comment by macjohnny** [comment]
forcing the value of an autocomplete could also be achieved with a `MatSelect` that can be searched / filtered: https://github.com/angular/material2/issues/5697

**Comment by mhosman** [comment]
I think this is a must-have when you need to search for example a user from a big database list (mat-select is not an option, you cannot load all the data at the same time). Also, it could be great to select multiple results in an autocomplete field (if you need to select multiple users like chip's example from select2 plugin).

**Comment by WizardPC** [comment]
Any progress on this ? Or a native mat-select with search ?

**Comment by fxck** [comment]
mat-select with search is blocked until rewrite of select later this year.

**Comment by jelbourn** [comment]
I wouldn't say rewrite, just restructuring

**Comment by umutesen** [comment]
Any progress?

**Comment by LautaroLorenz** [comment]
"select" with search is not the same as "autocomplete" because I need the user to write an option according to the situation

**Comment by umutesen** [comment]
```
 private autocompleteSelectionValidator(control: FormControl) {
    let selection = control.value;
    if (typeof selection === 'string') {
      return { incorrect: {} }
    }
    return null;
  }

 this.form = this.formBuilder.group({ 
      patientLocation: ['', this.autocompleteSelectionValidator]
    });
```

**Comment by thw0rted** [comment]
It seems to me like in the long run it would make the most sense to merge select and autocomplete into a single control type.  The presentation under current spec is basically the same, right?

So, you'd need a single control that:
* May have child `<option>s`, *or*
* Can load list items from an input (which could be async if it's contingent on user input), with 
* Input specifying whether to render a text field to type in, plus
* Input specifying whether user-typed value must be on the list to be valid, as well as
* Input that shows or hides the "arrow" for opening the list. (Select style vs autocomplete style)

If all these options can be combined independently, I think such a control could actually solve all the use cases presented in the above thread.

**Comment by suhag007** [comment]
https://stackoverflow.com/questions/48419050/angular-material-autocomplete-force-selection/51427590#51427590

**Comment by Shinigami92** [comment]
A bit optimized version of @umutesen 
```ts
private requireMatch(control: FormControl): ValidationErrors | null {
  const selection: any = control.value;
  if (typeof selection === 'string') {
    return { requireMatch: true };
  }
  return null;
}
```

**Comment by michaelb-01** [comment]
There's been a few good suggestions here, is there an official recommended method?

**Comment by grant77** [comment]
I monkey patched "_handleInput" and "_onChange" methods of MatAutocompleteTrigger to get the desired result.  I do not like using this intrusive approach, but I didn't see any other way for it to work the way I wanted it to.  I do not clear the text on blur if no option is selected, but the underlying form control value will be null.  Also, the underlying value will never be a string at any point in time, which was the case with a couple of solutions above.

Here is demo:
https://stackblitz.com/edit/angular-material2-issue-wbrzr1

**Comment by billbarni** [comment]
Does anyone have a working solution that covers all plausible scenarios?
The only thing missing in the @Shinigami92 answer is covering when the user types correctly the object label and does not select it, it should be considered valid. Or if the user selects the object and erases just the last letter and then retypes it...

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by seba161189** [comment]
<input (click)="focusOut()" type="text" matInput [formControl]="inputControl"
  [matAutocomplete]="auto">
   <mat-autocomplete #auto="matAutocomplete" [displayWith]="displayFn" >
     <mat-option (onSelectionChange)="submitValue($event)" *ngFor="let option of 
      options | async" [value]="option">
      {{option.name | translate}}
     </mat-option>
  </mat-autocomplete>

TS
focusOut() {
this.inputControl.disable();
this.inputControl.enable();
}

**Comment by viniciusi** [comment]
> @vlio20 Thanks for the directive idea/code. It's the least intrusive approach IMO.
> 
> You can simplify it a little by injecting `NgControl` into your directive and leaving it out or the inputs. Also I used `matAutocomplete` which is already defined in the input instead of adding `autoCompleteRef` and it worked just the same.
> 
> This is how it looked after I made these changes.
> 
> ```
> <input matInput
>              enforcedInputs
>              placeholder="Blarg..."
>              [matAutocomplete]="auto"
>              [formControl]="ctrl">
>   <mat-autocomplete #auto="matAutocomplete">
>             <mat-option *ngFor="let item of items" [value]="item">
>               <span>{{item}}</span>
>             </mat-option>
>  </mat-autocomplete>
> ```
> and the relevant bits from the directive
> 
> ```
> export class EnforcedInputsDirective implements AfterContentInit {
> 
>     @Input()
>     matAutocomplete: MatAutocomplete;
> 
>     constructor( @Host() @Self() private readonly autoCompleteTrigger: MatAutocompleteTrigger, private control: NgControl) {
>     }
> 
>     private subscribeToClosingActions(): void {
>         if (this.subscription && !this.subscription.closed) {
>             this.subscription.unsubscribe();
>         }
> 
>         this.subscription = this.autoCompleteTrigger.panelClosingActions
>             .subscribe((e) => {
>                if (!e || !e.source) {
>                     const selected = this.matAutocomplete.options
>                         .map(option => option.value)
>                         .find(option => option === this.formControl.value);
> 
>                     if (selected == null) {
>                         this.formControl.setValue(null);
>                     }
>                 }
>             },
>             err => this.subscribeToClosingActions(),
>             () => this.subscribeToClosingActions());
>     }
> .....
> }
> ```
> Edit: the original implementation has an issue whereby if the user focuses an input field that has a valid value and tabs away from the field (the field looses focus) the directive will clear the field value. We want to persist the field value if it's valid and only clear it if it's not in the list. To do that I added a check in the directive to see if the current value is still in the list of options, otherwise clear it.

I don't undertand the process, could you create a stackblitz demo?

**Comment by leblancmeneses** [comment]
Thanks mustafarian@ and vlio20@, this version gets rid of the subscription management and timeout. 

```
import { Directive, Input, Host, Self, AfterViewInit, OnDestroy } from '@angular/core';
import { untilDestroyed } from 'ngx-take-until-destroy';
import {MatAutocompleteTrigger, MatAutocomplete} from '@angular/material/autocomplete';
import {NgControl} from '@angular/forms';

@Directive({
  selector: '[appExtMatAutocompleteTriggerEnforceSelection]'
})
export class ExtMatAutocompleteTriggerEnforceSelectionDirective implements AfterViewInit, OnDestroy {

  @Input()
  matAutocomplete: MatAutocomplete;

  constructor(@Host() @Self() private readonly autoCompleteTrigger: MatAutocompleteTrigger,
      private readonly ngControl: NgControl) {  }

  ngAfterViewInit() {
    this.autoCompleteTrigger.panelClosingActions.pipe(
      untilDestroyed(this)
    ).subscribe((e) => {
      if (!e || !e.source) {
        const selected = this.matAutocomplete.options
            .map(option => option.value)
            .find(option => option === this.ngControl.value);

        if (selected == null) {
          this.ngControl.reset();
        }
      }
    });
  }

  ngOnDestroy() { }
}
```

View

```

    <mat-form-field>
      <input matInput type="text" placeholder="Vendor Selection" name="vendor"
          appExtMatAutocompleteTriggerEnforceSelection [(ngModel)]="vendor" [matAutocomplete]="auto1" [disabled]="!!isBusy.length" required />
    </mat-form-field>
    <mat-autocomplete #auto1="matAutocomplete" class="vendorAutocompletePanel" [displayWith]="displayVendorAs.bind(this)">
      <mat-option *ngFor="let option of vendors$ | async" [value]="option">
        {{option.DisplayName}}
      </mat-option>
    </mat-autocomplete>
```

**Comment by AndonyEmmanuelVelazquez** [comment]
Thanks @mustafarian and @vlio20, thanks, this directive solved my problem.
Also, why the status is still open?

**Comment by billbarni** [comment]
> 
> 
> Thanks @mustafarian and @vlio20, thanks, this directive solved my problem.
> Also, why the status is still open?

Because a directive should not be required, specially considering that such feature of `force selection` existed previsously and in the new angular/material versions is not present anymore.

**Comment by mhosman** [comment]
> Thanks @mustafarian and @vlio20, this version gets rid of the subscription management and timeout.
> 
> ```
> import { Directive, Input, Host, Self, AfterViewInit, OnDestroy } from '@angular/core';
> import { untilDestroyed } from 'ngx-take-until-destroy';
> import {MatAutocompleteTrigger, MatAutocomplete} from '@angular/material/autocomplete';
> import {NgControl} from '@angular/forms';
> 
> @Directive({
>   selector: '[appExtMatAutocompleteTriggerEnforceSelection]'
> })
> export class ExtMatAutocompleteTriggerEnforceSelectionDirective implements AfterViewInit, OnDestroy {
> 
>   @Input()
>   matAutocomplete: MatAutocomplete;
> 
>   constructor(@Host() @Self() private readonly autoCompleteTrigger: MatAutocompleteTrigger,
>       private readonly ngControl: NgControl) {  }
> 
>   ngAfterViewInit() {
>     this.autoCompleteTrigger.panelClosingActions.pipe(
>       untilDestroyed(this)
>     ).subscribe((e) => {
>       if (!e || !e.source) {
>         const selected = this.matAutocomplete.options
>             .map(option => option.value)
>             .find(option => option === this.ngControl.value);
> 
>         if (selected == null) {
>           this.ngControl.reset();
>         }
>       }
>     });
>   }
> 
>   ngOnDestroy() { }
> }
> ```
> 
> View
> 
> ```
> 
>     <mat-form-field>
>       <input matInput type="text" placeholder="Vendor Selection" name="vendor"
>           appExtMatAutocompleteTriggerEnforceSelection [(ngModel)]="vendor" [matAutocomplete]="auto1" [disabled]="!!isBusy.length" required />
>     </mat-form-field>
>     <mat-autocomplete #auto1="matAutocomplete" class="vendorAutocompletePanel" [displayWith]="displayVendorAs.bind(this)">
>       <mat-option *ngFor="let option of vendors$ | async" [value]="option">
>         {{option.DisplayName}}
>       </mat-option>
>     </mat-autocomplete>
> ```

How can I do this without the ngx-take-until-destroy import?

**Comment by mhosman** [comment]
Hey @Shinigami92 your solution works but the validation stay as an error until the UI is refreshed. How you can setError as null?

**Comment by bfwg** [comment]
Is there an official recommended method?

**Comment by AndonyEmmanuelVelazquez** [comment]
@bfwg My work around was validate the object binded to the autocompelte, so in the submit if the object is not valid i show an error.

**Comment by newmanw** [comment]
@leblancmeneses I am running into a couple of issues with your directive.

1. When adding a filter, the filter is not reset when an option is not selected.  This means that when going back into the field to select another option, 'filteredOptions' is filtering out most if not all options.

From: https://material.angular.io/components/autocomplete/overview#adding-a-custom-filter

```
<mat-option *ngFor="let option of filteredOptions | async" [value]="option">
  {{option}}
</mat-option> 
```

```
  ngOnInit() {
    this.filteredOptions = this.myControl.valueChanges
      .pipe(
        startWith(''),
        map(value => this._filter(value))
      );
  }
```

2. It would be nice to default back to the previous model value if the user types an invalid option.

**Comment by JayAhn2** [comment]
This feature is deadly needed...

**Comment by gitalvininfo** [comment]
> Here is a solution that doesn't require setTimeout:
> 
> ```ts
> this.trigger.panelClosingActions
>   .subscribe(e => {
>     if (!(e && e.source)) {
>       this.stateCtrl.setValue(null)
>       this.trigger.closePanel()
>     }
>   })
> ```
> 
> https://plnkr.co/edit/VWcGei7HxHYnncpzyYfW?p=preview
> 
> ~EDIT: note that this does not include escaping out of the autocomplete, tracking #6209~

Thanks for this. This is probably I'm looking for. In my case instead of returning the value of input field to null,I just return the value the previous selected option in mat autocomplete.

**Comment by essana3** [comment]
In the React Material-UI implementation of MatAutoComplete, if you type some value that does not exist in the list, the input is either reset or rebound to the last chosen value.
Why is this not the case here?

**Comment by infacto** [comment]
Just a use case about mat-autocomplete: The users enters text and selects an object of found items (over http). After that, another input element has been changned by the user which causes, that the http request responses other data (or empty). This causes that the mat-autocomplete input value does not exist anymore in the available options. The options are set via http Observable (async). 

Long story short: If the array for mat-option changes, it should validate if the selected value still exist, otherwise clear the input. But I'm not sure how to implement this. You have to check the data as json, because object reference are gone anyway (in general cases). 

In best case the component should handle this automatically. But an event which is triggered by options changed, will also help.

**Comment by willherr** [comment]
What's the discussion that's needed here? It sounds like this is a sought after feature  (although not necessary to have to implement).

Is the discussion regarding what to do when a user does not choose an option? Why not use the same behavior as a select when a user does not select an option (do nothing a.k.a. keep the state the same). 

Surely the discussion is not to or to not implement it? Someone said 50% of the time you need to force a selection. From my experience it is 95% of the time.

**Comment by AlixRoyere** [comment]
> I monkey patched "_handleInput" and "_onChange" methods of MatAutocompleteTrigger to get the desired result. I do not like using this intrusive approach, but I didn't see any other way for it to work the way I wanted it to. I do not clear the text on blur if no option is selected, but the underlying form control value will be null. Also, the underlying value will never be a string at any point in time, which was the case with a couple of solutions above.
> 
> Here is demo: https://stackblitz.com/edit/angular-material2-issue-wbrzr1

This solution seemed the best to have only valid data in the formControl, but it is only working in one way (view to model). In fact, when reseting the control or patching the value, displayed options are stuck to the ones matching last user interactions.

@grant77 Do you have any idea to make it work both ways?

I'm trying a different way with 2 formControls: one handling the clean data and another containing all user inputs.
I have synchronized values, errors and touched status when needed.
That's a bit overloaded, but it seems to work 😬
