### ISSUE TITLE
md-menu alignment broken on resize

### ISSUE THREAD

**Issue by andreasrueedlinger** [angular/components#3338]
#### Bug, feature request, or proposal:
Scenario: during an open menu some bound value changes and adds a new entry in the open menu. If this new entry is wider than the previous ones the whole menu width increases and breaks the alignment (if `x-position="before"` is used)

#### What is the expected behavior?
The aligment should not break and would not if for example `style.right` would be used instead of `style.left` in `ConnectedPositionStrategy#_setElementPosition` if `x-position="before"` is used.

#### What is the current behavior?
The aligment with the trigger breaks

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker link: http://embed.plnkr.co/B2vEK5C8NkIMF8t9svrY/

#### What is the use-case or motivation for changing an existing behavior?
Support dynamic menus

#### Which versions of Angular, Material, OS, browsers are affected?
All

**Comment by kara** [comment]
Yeah, we don't yet support adjusting the width after the menu is open.

**Comment by andreasrueedlinger** [comment]
It is maybe not a very common use-case. But I wanted some dialog/menu to be aligned with the trigger with some different content than a normal menu (for example a login form). But the normal dialog does not support alignment to an element (ok I can set the position but the "fitsViewport" logic is a bit more complex to implement yourself) and to have a transparent backdrop.

**Comment by jelbourn** [comment]
Closing since I believe this is obsolete
