### ISSUE TITLE
bug(input): Chrome autofill should set the form to valid

### ISSUE THREAD

**Issue by dahaupt** [angular/components#3414]
#### Bug, feature request, or proposal:
Probably a bug, but standard HTML input has the same issue in Chrome. Maybe anyone has an idea for a workaround.

#### What is the expected behavior?
Form changes state to valid if the autofill of Chrome fills input fields.

#### What is the current behavior?
You have to click inside the form / app to activate the autofill value and the state of the form changes to valid.

#### What are the steps to reproduce?

Plunker not possible, screenshot right after the start of the app:
![image](https://cloud.githubusercontent.com/assets/15915048/23560725/b6e038a2-003b-11e7-9632-31b60146f76a.png)

#### What is the use-case or motivation for changing an existing behavior?
Changing the state of the form to valid if the autofill value of Chrome is passed in.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.9,
Google Chrome 56
Material Beta 2
Windows 10

#### Is there anything else we should know?
I'm not sure if anyone else noticed this. It's not that bad but it looks confusing.

**Comment by dahaupt** [comment]
I've read this on stackoverflow and @mmalerba already mentioned something in that direction.

> The problem in Chrome browser: it does not allow access to the value of the password field after autofill (before user click on the page). So, there are two ways:
>1. remove validation of the password field;
>2. disable password autocompletion.

If nobody else has an idea I will close this and remove the validation because I think that's the best thing atm for login pages.

**Comment by mmalerba** [comment]
@dahaupt another idea would be to add validation only after the user interacts in some way (focus or input event maybe)

**Comment by wautersj** [comment]
@mmalerba Yes, That's how I usually take care of it.
Example: Never disable the login button based on validation, and when the login button is pressed it either redirects the user after successful login, or I show validation feedback.

**Comment by murilobd** [comment]
I'm on Angular 4 with Material Beta 8 and still facing this issue!

**Comment by AbakumovAlexandr** [comment]
Why was this closed?

Still not resolved in Angular Material 5.1.1.

**Comment by denishvachhani** [comment]
I am facing same issue with Angular 5.1.2 - Would be good if you anyone has figured out this one?

**Comment by tadamczak** [comment]
Vote to reopen :)

**Comment by mmalerba** [comment]
I've added some utilities for dealing with chrome autofill, they're available in 6.0.0-beta.2 https://github.com/angular/material2/blob/6.0.0-beta-2/src/lib/input/autofill.ts I would hold off on using it just yet though, the whole thing is being moved into the CDK soon: https://github.com/angular/material2/pull/9831

The `AutofillMonitor` detects when a field becomes autofilled, so you should be able to listen for that and re-check the validation.

**Comment by MarkPieszak** [comment]
@mmalerba Is there any chance this is going into a patched minor version of 5.x or is it only going to be available when 6.0 comes out?

**Comment by kostia-lev** [comment]
https://github.com/angular/material2/blob/master/src/material-examples/text-field-autofill-monitor/text-field-autofill-monitor-example.html

cannot make autofill work, ngoninit - form is not on the page yet, afterwards, it does not react on autofill event on chrome:-(, checked on angular 6, material 6

**Comment by ramsenjamuri** [comment]
Is there any work around for this issue? to make form valid when chrome autofill the fields

**Comment by KevCJones** [comment]
I'm just here for a solution but issue is on my project too. I'll be checking some SO suggestions like emitting an event in ngAfterViewInit to trigger change detection maybe? Or simulation of click.. same idea

**Comment by kherock** [comment]
So I've found that the main issue here is that Angular's `RequiredValidator` doesn't acknowledge inputs with autofilled input before the user has interacted with the page. The proper fix would probably need to be implemented in @angular/forms.

Regardless here's the workaround I've come up with that works pretty flawlessly:
https://gist.github.com/kherock/fad4c320c5894ec68373588e338955c5

**Comment by jagshub** [comment]
I tried the above gist, Inside ngOnInit this._elementRef.nativeElement.value  does not get the value still !
so i did tried "this._valueAccessor.onChange('dummy_trigger')" and that enabled the submit button and did not alter the input texts, so it works that way.  but i dont know what's happening.

**Comment by maxi7587** [comment]
I had the same issue. Solved it by adding a ´(change)="changeInput($event)"´ output in the form to trigger the following method:
´´´
changeInput(data) {
    data.control.setValue(data.$event.target.value);
}
´´´

**Comment by taskiukas** [comment]
why this issue is closed?

**Comment by alex-osman** [comment]
This is an important issue, please re-open until fixed

**Comment by N-Andronopoulos** [comment]
A simple (and paranoid) fix which worked for me:
```html
<input matInput 
  (change)="fixAutoFill($event, pwd.value)" 
  placeholder="Username"
  [formControl]="username" 
  name="username" 
  required>

<input matInput
  #pwd 
  placeholder="Password" 
  [formControl]="password" 
  type="password" 
  name="password" 
  required>
```
```ts
username = new FormControl('', [Validators.required, Validators.email]);
password = new FormControl('', [Validators.required]);

fixAutoFill(usr: Event, pwd: string) {
  if (usr) { this.username.setValue((usr.target as HTMLInputElement).value) }
  if (pwd) { this.password.setValue(pwd) }
}
```

**Comment by rbinsztock** [comment]
Please reopen this issue.

**Comment by rbinsztock** [comment]
> So I've found that the main issue here is that Angular's `RequiredValidator` doesn't acknowledge inputs with autofilled input before the user has interacted with the page. The proper fix would probably need to be implemented in @angular/forms.
> 
> Regardless here's the workaround I've come up with that works pretty flawlessly:
> https://gist.github.com/kherock/fad4c320c5894ec68373588e338955c5

I tried to use with Angular 7.2 but it's not fixing the autocomplete, I still need to click on the page for input validation to be triggered.

**Comment by mmalerba** [comment]
As was mentioned earlier in this issue, it is not possible to know the autofilled values until the user interacts with the page. There is no way around this, it's a security feature of Chrome. 

As @kherock demonstrated, it would be possible for the `RequiredValidator` to detect that _something_ is autofilled, though again, you can't actually read those values until the user interacts with the page. However, this change would need to be made in `@angular/forms` since that's where `RequiredValidator` lives. I've created an issue for forms here: https://github.com/angular/angular/issues/30616 please use that issue instead.

**Comment by rbinsztock** [comment]
With monkey patch used on https://autofillmon-validate.stackblitz.io/ the user does not need to interact with the page for form validation to be triggered. You can see the Submit button enabled when the page is loaded. I tried the monkey patch with Angular 7.2 but does not get the same behavior.

**Comment by mmalerba** [comment]
Here's a version of the above stackblitz with the versions updated to `@<7.3`, seems to work: https://stackblitz.com/edit/autofillmon-validate-qdrmvt?file=app/app.component.ts

**Comment by rbinsztock** [comment]
> Here's a version of the above stackblitz with the versions updated to `@<7.3`, seems to work: https://stackblitz.com/edit/autofillmon-validate-qdrmvt?file=app/app.component.ts

Thank you so the monkey patch only work for MD directive ? https://stackblitz.com/edit/autofillmon-validate-roxxqi I tried with custom input component.

**Comment by mmalerba** [comment]
The monkey patch works on `input` and `textarea` elements with a `required` attribute. Depending on how your component is implemented you may have to tweak it. Angular Material component APIs are designed so that the user puts the `required` attribute directly on a native `input` so that patch works as-is for Angular Material inputs

**Comment by billyjov** [comment]
The Monkey patch only works for me on firefox and still failed on chrome

**Comment by Mexxim** [comment]
Possible workaround:
set the first input to `autofocus` which introduces a light flicker but triggers the :valid pseudo-class

**Comment by rbinsztock** [comment]
> Possible workaround:
> set the first input to `autofocus` which introduces a light flicker but triggers the :valid pseudo-class

it trigger the validation for the first input only but the form state is still invalid until the user click/interact somewhere on the page.

**Comment by Hassan-Moin** [comment]
The Monkey patch not working for me on chrome iOS. Testing on iPhone XS and iOS 12 >

**Comment by laukstein** [comment]
This bug is still relevant, happens on Chrome 76. Has anyone filled Chrome bug for it?
