### ISSUE TITLE
md-autocomplete should select the activeOption when there is only one item in the dropdown

### ISSUE THREAD

**Issue by JacobBrandt** [angular/components#3654]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When the options are narrowed down to one option I would like that option to become the activeOption.

#### What is the current behavior?
When the options are narrowed down to one option there is no activeOption highlighted.

#### What are the steps to reproduce?
Filter the autocomplete options by typing until one option remains in the dropdown

#### What is the use-case or motivation for changing an existing behavior?
This is an autocomplete field but without this automatic selection when there is only one option I feel as though the component is just a filter.  When typing the user is forced to use the arrow keys to choose the only selection available.  Ideally they just want to hit ENTER to select that as the option and move on to the next form input.

#### Which versions of Angular, Material, OS, browsers are affected?
Latest

#### Is there anything else we should know?
Code wise this is easy to add.  Just need to handle the keyup event like this:

```
_handleKeyup(event: KeyboardEvent): void {
  if (this.autocomplete.options.length === 1) {
    this.autocomplete._keyManager.setFirstItemActive();
  }
}
```

**Comment by jelbourn** [comment]
This may be a problem for screen-reader users, need to confirm.

**Comment by sardeenz** [comment]
Any movement on this? Doesn't md-autoselect = 'true' do this in angularjs material?

**Comment by jelbourn** [comment]
Since this issue was created we've added a new option to the autocomplete that should enable this:
https://material.angular.io/components/autocomplete/overview#automatically-highlighting-the-first-option
