### ISSUE TITLE
Bundling of svg icons registered via mdIconRegistry

### ISSUE THREAD

**Issue by mark-buer** [angular/components#3720]
#### Feature request:
Automatic bundling of svg icons registered via mdIconRegistry (in concert with angular-cli).

#### What is the expected behavior?
Within a source tree, svg icons are stored alongside the `.component.ts` files that use/register them. The build system (angular-cli) coordinates with mdIconRegistry in order to inline the svgs into the final app bundle (or similar).

#### What is the current behavior?
When using angular-cli and mdIcon, svgs are stored within the assets directory. At least, this seems to be the path of least resistance.
At runtime, individual requests are made for each and every svg file.

#### What is the use-case or motivation for this feature?
Within a source tree, svg files are often best stored alongside their consumers, similar to how css and html templates are stored alongside their `.component.ts` file. Having the svgs elsewhere in the tree results in a maintenance burden (for example, an assets folder containing svgs with no clear consumers).
The svg files used for mdIcons are typically tiny, thus bundling within the js is probably appropriate so as to reduce the number of requests.

#122 specified a task "_Tool for generating svg bundles (output similar to what polymer's iron-icons works with)_" which was never completed. That incomplete task seems related to this issue.
#3132 is another related issue.

It is unclear whether this feature request should be raised against this project or against the angular-cli project.

**Comment by jelbourn** [comment]
This is something we wanted to do, but it likely won't see any attention for quite a while as we focus on polishing / expanding the components.

**Comment by mackelito** [comment]
Time for some love here? :)

**Comment by klemenoslaj** [comment]
Is there some straight forward workaround available though?  
I think making requests for each icon is the reason font icon will forever be used :D

**Comment by jpike88** [comment]
Perhaps svgIcon directive be allowed to fallback in such a way that it transforms the mat-icon into one using a ligature if it fails to have a match in the registry?

**Comment by klemenoslaj** [comment]
> Perhaps svgIcon directive be allowed to fallback in such a way that it transforms the mat-icon into one using a ligature if it fails to have a match in the registry?

That would mean you need to load fonts and all the icons (_unless some icon fails_), which is kinda suboptimal. And it still doesn't solve the bundling issue

**Comment by jpike88** [comment]
My problem is only slightly related to this but worth mentioning.

Many devs may want to add a few custom icons while still using the offical angular material icons. Problem is, the angular team don't provide a way to register the official icons with MatIconRegistry as they haven't provided them in a format that MatIconRegistry understands... 

https://github.com/angular/components/issues/15942#issuecomment-491571863

**Comment by crisbeto** [comment]
This should be possible now by adding the icons as string literals and using a Webpack loader for the bundling.
