### ISSUE TITLE
Harsh animation and transition effect on  Microsoft IE/EDGE

### ISSUE THREAD

**Issue by sohail85** [angular/components#3736]
#### Bug, feature request, or proposal:
We have been using angular material since its first version, and it has worst animation and transition effects on one of the worst browsers which unfortunately used by many since it came preinstall on windows machines.
its sometimes make us take decisions like to move over it and look for something similar or more popular.

#### What is the expected behavior?
if in the documentation says it supports most popular browsers it would be nice to have good animation or transition support out of the box for other browsers.

#### What is the current behavior?
Harsh animation and transition effect on  Microsoft IE/EDGE

#### What are the steps to reproduce?
just run the demo on EDGE side by side running on chrome

#### What is the use-case or motivation for changing an existing behavior?
to save developers time and to convince decision makers that this framework will make production smooth and on pace.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular material 2 on Microsoft browers.

**Comment by jelbourn** [comment]
@matsko Do you know anything about animation issues on IE / Edge ?

**Comment by sohail85** [comment]
@jelbourn : Well, I think almost all of the animation and transitions either do not work or they are harsh on IE, for example, tooltip, snakbar, ripple effect on opening and closing of menu which I observed.

**Comment by yogeshgadge** [comment]
@sohail85 Did you include `web-animations-js` in your HTML as polyfill ?

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
