### ISSUE TITLE
[Tooltip] Does not work within mat-placeholder

### ISSUE THREAD

**Issue by aldo-roman** [angular/components#3823]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
A mdTooltip element should display a tooltip if placed within a md-placeholder tag

#### What is the current behavior?
mdTooltip within a md-placeholder tag does not display

#### What are the steps to reproduce?
http://plnkr.co/edit/QAOYgSzLBpbM3ifmgQLL

#### What is the use-case or motivation for changing an existing behavior?
I want to display an info icon next to the placeholder (always floating) with an informative tooltip

#### Which versions of Angular, Material, OS, browsers are affected?
Can confirm for Angular 4, Material HEAD

#### Is there anything else we should know?
It seems the hover event is being captured by md-input-container and does not allow the mdTooltip to know when the user is hovering the cursor on it.

**Comment by aldo-roman** [comment]
So, basically, the pr was reverted by #4206 to fix #4167 

As a workaround, we are manually adding:
```
md-placeholder {
    pointer-events: auto;
}
```
See https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

@crisbeto is there any long-term solution?

**Comment by crisbeto** [comment]
I'm not sure what the long-term solution could be on our side @aldo-roman. On one hand, we can't allow the pointer events, because you're not able to fully interact with the input, but on the other we can't disable them either, because you can't bind mouse events. I'd say that the first use case is a lot more common, so we'll have to go for the lesser of two evils.

**Comment by aldo-roman** [comment]
I submitted a pull request to allow pointer-events on the tooltip host tag (not on the placeholder at all).

`:host {pointer-events: auto}`

**Comment by wagnermaciel** [comment]
Closing because mat-placeholder has been made obsolete

Working example:
https://stackblitz.com/edit/angular-dddm4l?file=src%2Fapp%2Finput-overview-example.html
