### ISSUE TITLE
Support relative paths for MatIcon based on baseUrl

### ISSUE THREAD

**Issue by zmanring-zz** [angular/components#4263]
#### Bug, feature request, or proposal:
The icons URL's seem to all be absolute based on /assets which works fine when you're in the root but when you need the icons to be relative it doesn't work.

#### What is the expected behavior?
The icons to be served up relative to the baseUrl

#### What is the current behavior?
Not relative, all absolute.

#### What are the steps to reproduce?
Deploy code into a sub-folder on s3 or alike

#### What is the use-case or motivation for changing an existing behavior?
My app assets are stored in a sub-folder and the svgs cannot be found there

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.x | Material 2.x Beta 3 | Mac

#### Is there anything else we should know?
Keep up the good work!

**Comment by fxck** [comment]
I'm not sure I understand what are you talking about. What icon, what url? Lib itself, demo app, web?

**Comment by zmanring** [comment]
so right now to bring in a icon/svg, I use

`mdIconRegistry.addSvgIcon('logo', sanitizer.bypassSecurityTrustResourceUrl('../../../assets/images/logo.svg'))`

But when I do that, the requested `logo.svg` after you deploy is looking for that file in `/assets/images/logo.svg`

This is fine and good when you have a app that sits in the root level of your domain. In my case it all sits behind a folder called `webapp`. Everything else works based on the `<base href="/webapp/">` but the icons do not.

Hope that helps @fxck ?

**Comment by sajaynambiar** [comment]
Any update or workaround ?

**Comment by PawelOwczarekFalcon** [comment]
I need fix too

**Comment by thethinkingmonks** [comment]
Thank you. This helped me to solve the issue.

**Comment by crisbeto** [comment]
This should be possible now using an icon resolver.
