### ISSUE TITLE
Autocomplete improvement proposal: Programmatically map inputs to autocomplete fields instead of relying on #selector.

### ISSUE THREAD

**Issue by viztastic** [angular/components#4351]
#### Proposal

It is currently not possible to easily integrate the autocomplete input in a reactive form with dynamically generated autocomplete fields. This is since the `#AutoCompleteIdSelector` cannot be dynamically indexed to be part of an `*ngFor` loop.

#### What is the expected behavior?

Would be great to attach a programmatic mapping between input and autocomplete tags as opposed to relying strictly on template variables.

Refer to `ng2-completer` module as an example of this in action.

#### What is the current behavior?

Currently mdAutoComplete require a template Id Selector.

#### What is the use-case or motivation for changing an existing behavior?

I have a form array that I'd like to dynamically insert Autocomplete fields into. 

#### Is there anything else we should know?

This would be greatly appreciated!

**Comment by ryanpm40** [comment]
Glad to see this feature request, it's exactly what I've been looking for!

I also think we should have the option to loop through an array in the same way you can for md-options inside an md-select.

**Comment by bogdanilin** [comment]
Hi! Is this feature coming anytime soon? Is there a workaround?

**Comment by rattkin** [comment]
> Hi! Is this feature coming anytime soon? Is there a workaround?

This looks like a workaround: https://stackoverflow.com/questions/46470430/angular-material-2-md-autocomplete-dynamic-name

**Comment by jelbourn** [comment]
Closing this issue since this is already doable- the trigger just needs a reference to the autocomplete instance, which can come from anywhere (not necesisarily a template variable)
