### ISSUE TITLE
Proposal: Grid-List input to ignore order of tiles and close all gaps

### ISSUE THREAD

**Issue by antoschd** [angular/components#4362]
#### Proposal
Add possibility to prioritize gap closing, even if this means that tiles appear in the wrong order. 

#### Current behavior
Order is allways respected. This can cause gaps.
http://plnkr.co/edit/Pl5Zfkrnvu7L9WFv6YOW?p=preview

#### Use-case / motivation for changing an existing behavior
Use-case: Closing gaps is more important than order. 
For example: We want to use the grid-list to display videos and images. Videos should be twice as big as images, colspan = 2 and rowspan = 2. If the data wouldn't change we could easily order them once, so that there is no gap. But images and videos are loaded dynamically, according to user selection.

#### High-level approach / API
The basis of the algorithm could be the use of an two-dimensional boolean array, to track the already placed tiles. Each element of the array corresponds to a row, each element of a row corresponds to a cell. True indicates that the cell is already occupied; false indicates an empty cell.

This way we could know about all rows in the grid-list and can start looking for a large enough gap, from the beginning for every tile (by reseting row- and column-index before each positioning). 

Finding a gap would be a bit more complex, because we could have to check "beneath".

The reseting of row/column index would only happen if the corresponding input had been set to true. Otherwise the existing behaviour is obtained (order is respected): 
this.columnIndex = gapStartIndex + tile.colspan; // Line 64 tile-coordinator

**Comment by jelbourn** [comment]
Closing this because we are pretty unlikely to add new features to MatGridList going forward now that CSS Grid provides a significantly more robust tool for creating this style of layout.
