### ISSUE TITLE
FR: Textarea should support mdAutocomplete

### ISSUE THREAD

**Issue by KevinVillela** [angular/components#4399]
**I'm submitting a... feature request**

**Current behavior**
<md-input-container>
  <textarea mdInput [mdAutocomplete]="auto"></textarea>
</md-input-container>
<md-autocomplete #auto="mdAutocomplete">

Gives error:
Can't bind to 'mdAutocomplete' since it isn't a known property of 'textarea'.

**Expected behavior**
The ability to attach an autocomplete to a textarea, similar to how it is done with an input element.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/EwjoZPaxL766dQm8timK?p=preview

**What is the motivation / use case for changing the behavior?**
The main use-case is probably for inputs that can have comma-separated values, where each value should be autocompleted. The canonical example of this is the Drive sharing UI.

**Please tell us about your environment:**
Should be environment-agnostic, since it is reproducible on the plnkr.

* **Angular version:** 4.1.1

* **Browser:**  all - this is an FR for compilation time.
 
* **Language:** all

**Comment by jasnoponjatno** [comment]
Would be awesome to see this feature! I think we need some kind of boolean flag on MdAutocomplete to  autocomplete last word in ngModel instead of whole ngModel on option selection.

**Comment by ArthurFromDnipro** [comment]
+1 for this feature, any updates?

**Comment by ccjmne** [comment]
Wouldn't it actually rather warrant the use of a Chips list?
These can be paired with an input (and Autocomplete): see [this example](https://material.angular.io/components/chips/overview#chip-input).

**Comment by crisbeto** [comment]
This has been supported for a while now.
