### ISSUE TITLE
Autocomplete: Incompatible with protractor tests

### ISSUE THREAD

**Issue by mrmeku** [angular/components#4467]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Within  protractor test I should be able to click an autocomplete option via the following command
`element(by.cssContainingText('.mat-autocomplete-visible .mat-option', optionText)).click()`

#### What is the current behavior?
The current behavior generates an error when the above call is invoked 
`Failed: stale element reference: element is not attached to the page document`

#### What are the steps to reproduce?
I can't provide a plunker since this is protractor specific behavior. Just use the existing autocomplete demo and make a protractor test to test clicking an autocomplete option. You'll find that the test will be either incredibly flaky or fails every time.

#### What is the use-case or motivation for changing an existing behavior?
You'll need to have e2e tests for the autocomplete component eventually. When you choose to write them you'll need to address this bug.

#### Which versions of Angular, Material, OS, browsers are affected?
All

#### Is there anything else we should know?
I'll provide any details you would like

**Comment by dubzzz** [comment]
In case it can help you:

I had a very similar issue for a while (played with `browser.wait` and `browser.sleep`). A solution has been to use `NoopAnimationsModule` instead of `BrowserAnimationsModule`.
