### ISSUE TITLE
Style overlay backdrop for MdSidenav

### ISSUE THREAD

**Issue by Dunos** [angular/components#4482]
**Feature Request**

**What is the expected behavior?**

Add an extra parameter to the MdSidenav element to add or remove backdrop shadow (just like the new _hasBackdrop_ being implemented in [#2822](https://github.com/angular/material2/pull/2822), and also being able to change its color.

**What is the current behavior?**

Backdrops only can be changed via global styles or custom CSS with /deep/

**What is the use-case or motivation for changing an existing behavior?**

To remove/style backdrops for specific sidenavs. One sidenav may not need a backdrop, or a backdrop with a different color or opacity.

**Comment by Lior-G** [comment]
I would agree and would like to see this.
I had not notice before this was opened when I opened https://github.com/angular/material2/issues/5300

**Comment by TobiasVdb** [comment]
+1

**Comment by mittcoats** [comment]
+1 -- this would be very helpful

**Comment by SvenBudak** [comment]
I am currently doing a themeSwitcher what is located in the SnackBar. it would be awesome if its possible to fade the background out and in on functionCall. It makes sense to show the backdrop to show people that there is something opend at bottom of screen (The SnackBar) but after they realize it, and change the color, they need to see the real color change of layout. so the Backdrop is anyoing in that moment they try to find the best color.

**Comment by crisbeto** [comment]
Closing since this has always been possible by targeting the `mat-drawer-backdrop` CSS class.
