### ISSUE TITLE
[Tooltip] Container is not being cleaned up

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/components#4487]
Some parts of tooltip do not disappear

Currently, if router starts navigate and at the same time mouse hovers any other (not same) element with tooltip:
![image](https://cloud.githubusercontent.com/assets/12189125/25967209/6a26a412-369e-11e7-94f0-f8383f92bbc3.png)

To reproduce, just make sure to hover and navigate at the same time

I would like to use tooltips in my app.

Here are versions:
```
    "@angular/animations": "4.1.0",
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/material": "2.0.0-beta.3",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@angular/platform-server": "4.1.0",
    "@angular/router": "4.1.0",
    "@covalent/core": "1.0.0-beta.3-2",
    "@covalent/http": "1.0.0-beta.3-2",
    "@covalent/markdown": "1.0.0-beta.3-2",
```

I'm sure @covalent's template is not related to this behavior.

**Comment by xrochoa** [comment]
![screen shot 2017-07-11 at 11 56 26 pm](https://user-images.githubusercontent.com/10101677/28105585-e9a37e1a-6694-11e7-9583-c327167cc6a1.png)
Something similar over here. It seems to happen when I hover over an element with a tooltip while the animation of the parent component is running from visible to void.

**Comment by Plondrein** [comment]
any update on this?

**Comment by SerhiiTsybulskyi** [comment]
I've got the same issue. Any update?

**Comment by crisbeto** [comment]
I wasn't able to reproduce this with the latest code. Closing the issue given that there hasn't been any activity in a long time.
