### ISSUE TITLE
Proposal: set the date format in mdInput type="date"

### ISSUE THREAD

**Issue by da45** [angular/components#4493]
Proposal:
Need to change the date format, for example:
` <md-input-container>
     <input  mdInput type="date" md-format="dd/mm/yyyy">       
</md-input-container>   `

#### What is the expected behavior?
user can set the date format

#### What is the current behavior?
 date format is the same as the default system date format

#### What is the use-case or motivation for changing an existing behavior?
not the same behaviour in laptop & smart phone, please check below pictures:

![laptop](https://cloud.githubusercontent.com/assets/19927289/25989889/b262cb8c-36f5-11e7-9de7-8edd7dff44bd.jpg)
![mobile](https://cloud.githubusercontent.com/assets/19927289/25989905/bdbae91a-36f5-11e7-8d40-76446ee474ed.jpg)

**Comment by jelbourn** [comment]
Closing this since I don't see us adding this type of functionality for the native date input.
