### ISSUE TITLE
Feature proposition: Add md-inset to md-divider

### ISSUE THREAD

**Issue by mist3r3** [angular/components#4570]
#### Bug, feature request, or proposal:
Adding md-inset inside md-divider

#### What is the expected behavior?
Showing divider only under between elements of the list, so in case you have multiple elements the divider is between the element and doesn't take into account an image on the left size or else.

#### What is the current behavior?
divider on the entire line only

#### What are the steps to reproduce?
-/
Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Existing already on angular JS.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular2

**Comment by CaerusKaru** [comment]
@mist3r3 `mat-divider` now supports `inset` as an option, can this be closed?

**Comment by crisbeto** [comment]
Closing since the divider has an `inset` input already.
