### ISSUE TITLE
sideNav does not support clipping below an app/tool bar as per material specification

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/components#4706]
#### Bug, feature request, or proposal:
Feature request to match material specification

#### What is the expected behavior?
The material specification states that sidenav's should have the ability to clip ( only effect content below an app/tool bar )  

#### What is the current behavior?
Currently the only way to accomplish this is to place the toolbar first, outside of the md-sidenav-container, BUT doing so then precludes using a sidenav in over mode, it's an either or solution

A typical real world use case is to make the left sidenav in over mode, and set the right sidenav's mode to side BUT clipped below the toolbar. 

#### What are the steps to reproduce?
http://plnkr.co/edit/jtCKUBw7mHkSkM4nF3Uh

Need a way to slide out the right sidenav without moving the toolbar, which isn't currently possible without doing some html and css hackery

#### What is the use-case or motivation for changing an existing behavior?
Match the specification so that we can implement mixed case uses of left and right sidenav positioning

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1.3 Material 2 Master 

#### Is there anything else we should know?
It is solveable by nesting md-sidenav-containers, which is the only way I could figure this out while tinkering with it, other methods didn't work.  While it seems to work fine it's a bit of a hack. 

http://plnkr.co/edit/EarMzAJj68pS5teE8oMQ?p=preview

One idea might be to create this structure behind the scenes and add clipToAppBar="true" for a sidenave then move the sidenav to the appropriate sidenav container. 

<md-sidenav mode="over" clipToAppBar="true"> places the sidenav into the inner container, else it resides in the out container. 

If not, just change the documents to at least show it's possible and how it's done

**Comment by gm112** [comment]
For other work arounds, I managed to workaround this by setting mat-toolbar's position to fixed in a container dev around only mat-toolbar bare minimal hack approach as well. Though that's far from an ideal solution still. =\

**Comment by Todd-Werelius** [comment]
@gm112 I tried similar solutions, but that had issues for me as well, I can't remember them all but I kept running into gotcha's 

So far I have only run into one obscure problem with nested side containers that I can't easily reproduce and the work around was trivial, so for me the nested solution is working out better.

**Comment by gtranter** [comment]
A problem that doesn't seem to have any workaround (therefore requiring Angular Material 2 to address it) is with elevation. The sidenav and app bar / toolbar should share the same elevation and both cast a shadow over the content. The sidenav always has the right shadow, but I've only been able to get the toolbar to either have no shadow (same elevation as content) or have a shadow that is over the sidenav. Neither is in compliance with Material Design rules. 

If anyone can share a workaround for the elevation issue it would be appreciated.

**Comment by willshowell** [comment]
@gtranter https://plnkr.co/edit/Y95B2qxq0SlkEhKzOuUO?p=preview

```css
.mat-sidenav-content {
  z-index: 1
}
```

**Comment by gtranter** [comment]
@willshowell Thanks - but what I am actually looking for is a solution for the elevation problem when in clipped mode, as that is the focus of this issue. Clipped mode means the sidenav pushes only the content area and is always below the app bar. Your example is full-height mode which pushes both the content area and the app bar.

**Comment by SamiAl90** [comment]
Any news on that? Would be super cool to have a sidenav clipped below the toolbar.

**Comment by giri-v** [comment]
I've tried setting the toolbar outside the mat-sidenav-container but that results in height:100% to overflow its parent. Would really like a nice clean solution.

**Comment by alsami** [comment]
This can be done manually by using the inputs `fixedTopGap` and `fixedBottomGap`. I created a [static-sample](https://stackblitz.com/edit/angular-material-fixed-sidenav) that I will update soon to be more dynamic by using the breakpoint-observer.

**Comment by guilherme-fafic** [comment]
set mat-sidenav fixedInViewport to false

**Comment by jelbourn** [comment]
Closing this since the sidenav now has options for fixed positioning.
