### ISSUE TITLE
Easy to accidentally change slider value while scrolling on touch devices

### ISSUE THREAD

**Issue by theely** [angular/components#4711]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
On touch devices the slider may causes usability issues.
The ability to click on the slider bar at a given position to quickly move the slider thumb at that position should be disabled on touch devices to prevent issues with scroll or other kind of gestures.
This would also align the md-slider behaviour to the native slider (iOS and Android).

#### What are the steps to reproduce?
For instance if you have a scrollable list of sliders, having the sliders reacting on every tap will prevent the list from being properly scrolled, see image.
<img width="356" alt="screen shot 2017-05-21 at 17 37 14" src="https://cloud.githubusercontent.com/assets/2025999/26285267/a6910982-3e4c-11e7-8d83-40f328b3af37.png">

#### What is the use-case or motivation for changing an existing behavior?
I would change the behaviour to be consistent with the native iOS and Android sliders and avoid touch gestures hijacking. Meaning that on touch devices the md-slider would only be controllable by dragging the thumb.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.0.1 - Material 2.0.0-beta.5 - MacOS 10.12.4 - typescript 2.2.2

**Comment by jelbourn** [comment]
@wagnermaciel and I took a look at this today, and while we agree that the behavior is unfortunate on mobile, it does align with the behavior of the native `<input type="range">` on Android and ChromeOS. Since it matches the native behavior, we'll probably leave this as is.
