### ISSUE TITLE
Request: Flexible toolbar space

### ISSUE THREAD

**Issue by bhoproove** [angular/components#4760]
#### What is the expected behavior?
Flexible toolbar space:
https://material.io/guidelines/patterns/scrolling-techniques.html

#### What is the current behavior?
md-toolbar does not have the scrolling technique mentioned on the material guideline.

**Comment by tinayuangao** [comment]
You can use flex-layout https://github.com/angular/flex-layout or css.

**Comment by bhoproove** [comment]
@tinayuangao I'm sorry, I don't understand how the flex-layout effects the flexible space of toolbar on scroll. Can you give me an example?

**Comment by mmalerba** [comment]
@DevVersion I believe this is requesting a feature to expand/collapse the toolbar on scroll, is that something we plan to do?

**Comment by bhoproove** [comment]
@mmalerba, @DevVersion 

 I think, visually, this is one of the nice things about Material design. 

Material design toolbar with image or 'expanded' look really gives a nice visual queue for users and the way Material design changes the toolbar on scroll minimizes the initial visuals so that the content can take over on priority. 

I believe this feature is especially helpful on mobile view.

**Comment by DevVersion** [comment]
@mmalerba I didn't plan to do that when I initially created the design doc. 

We had something similar in Material 1.x and it required us to have a different directive called `md-content`.

Still I think it's a useful feature and maybe we should consider creating another design doc just for this.

**Comment by filipedf** [comment]
+1

**Comment by jelbourn** [comment]
Closing this since we don't have any plans to add this feature.
