### ISSUE TITLE
feat(DatePicker): select range of dates

### ISSUE THREAD

**Issue by alaawerfelli** [angular/components#4763]
Hello,
it's possible to set date range in date picker (have the ability to choose startDate and endDate and get all dates between startDate and endDate).

**Comment by ss-bb** [comment]
Hi. 
As it is write [Here](https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker.md)
This is a feature that will come "Support for selecting and displaying date ranges"

**Comment by shyamal890** [comment]
+1 @ss-bb  the doc talks about "displaying" and not "setting". What we are requesting is "Date Range Picker" which is currently also supported by `ng-bootstrap`. Example of which is available here: https://ng-bootstrap.github.io/#/components/datepicker/examples

**Comment by raugaral** [comment]
Than, I understand that currently is not supported, no?

**Comment by chenby** [comment]
+1

**Comment by doom777** [comment]
+1

**Comment by FHappy** [comment]
+1

**Comment by fxck** [comment]
http://ej2.syncfusion.com/demos/#/material/daterangepicker/minmax.html this looks decent

**Comment by redasakhi** [comment]
+1

**Comment by RaulRG** [comment]
I think this is quite important for many scenarios (we will use Material for enterprise applications and we sure need it). @alaawerfelli said that it should return all the dates between startDate and endDate, but I think that the component should just return both dates, as the dates could be then calculated if needed. The design would be easier as you could use startDate / endDate as input / output parameters.

**Comment by dragester** [comment]
+1

**Comment by VitalyVrublevskyy** [comment]
+1

**Comment by FabienInan** [comment]
You can use [min] [max] attributes with your matDatePicker.

**Comment by lihanyu23** [comment]
@FabienInan [min] [max] attributes are about date validation, not related to date range selection.

**Comment by pyritewolf** [comment]
Is there a timeframe for the release of this feature? (or any place where we can see what are the things to come in the next couple of months?)

**Comment by fxck** [comment]
> (or any place where we can see what are the things to come in the next couple of months?)

readme

**Comment by SaturnTeam** [comment]
I'm trying to do date range picker, and I also want to contribute it. How it is better - another component(s) or write code to existing?

**Comment by SaturnTeam** [comment]
![image](https://user-images.githubusercontent.com/10252514/34666914-360ae512-f499-11e7-92c6-c5f59a92d1fb.png)
![image](https://user-images.githubusercontent.com/10252514/34666927-417bcfa6-f499-11e7-8b04-3c6c151c192c.png)
What do you think, this styles is ok?

**Comment by RaulRG** [comment]
@SaturnTeam : It looks good!! I looked at the Material Design specification, but they don't say anything about selection of ranges. Your design looks very material-like! :-)

**Comment by GerardoSabetta** [comment]
@SaturnTeam That looks awesome, care to share the code? Thanks!

**Comment by SaturnTeam** [comment]
@GerardoSabetta Code not ready yet

**Comment by SaturnTeam** [comment]
UI for selected range between one month
second primary-colored circle - it is :hover
![image](https://user-images.githubusercontent.com/10252514/34808005-7d7951aa-f6be-11e7-8e6a-73fbecbc7f8c.png)
![image](https://user-images.githubusercontent.com/10252514/34808024-982644ae-f6be-11e7-92e3-0c1038a54071.png)
![image](https://user-images.githubusercontent.com/10252514/34808026-9fab24e2-f6be-11e7-8055-76926a145729.png)

**Comment by SaturnTeam** [comment]
How do you think better - propagate values via existing `@Output() selectedChange: D` or create `@Output() dateRangeChange: MatDatePickerRangeValue<D>` ?

**Comment by SaturnTeam** [comment]
@enqminh What do you want from it? Code done only 30%

**Comment by lihanyu23** [comment]
@SaturnTeam it's not easy to help without seeing how you plan to build the component.

Will there be 2 inputs for the begin and the end of the range ? Will you have 2 outputs for each of them ?

**Comment by enqminh** [comment]
I just wanna datepicker form... to.

**Comment by SaturnTeam** [comment]
@lihanyu23 Ok, I got it. I will commit tomorrow to my repo to show. I'm going to use one input and add 1-3 additional variables  to `MatDatepicker` and it's childs. I started to create another component, but then I understand that 90% of code is the same with `MatDatePicker`, and I decided to update `MatDatepicker`.
About selecting and showing days through `MatCalendar` - no any problem.
The difficulty in displaying value in `<input>`. Examples, how I think to show them (depends on `DateAdapter`)
`01/31/2017 — 02/18/2017` (or `01/31 — 02/18/2017`)
Later to do these displaying
`nov 2017` (for 11/01/2017 — 11/31/2017)
`jul 2017 — dec 2017` (for 07/01/2017 — 12/12/2017)
And of course string parser will separate string (by — or -) to convert  it to two dates (begin and end). Also I don't forget about sauch date formats as 01-01-2001

**Comment by Den-dp** [comment]
@SaturnTeam Here is my ideas/mockup based on the styles of the latest datepicker.

![image](https://user-images.githubusercontent.com/1770529/34822433-9b9a65e6-f6cf-11e7-941c-3f51836546e8.png)

Pattern with "filling" like this should work better (especially for ranges greater than 1 months), because
* starting and ending points are always rounded and easy to notice
* all days between are just filled with background color so they looks less noisy as if it was with circles.

For styling I used
```
background-color: #e6f3ff;
```
and for corner points I used this trick
```
border-radius: 100% 0 0 100%;
```

**Comment by SaturnTeam** [comment]
@Den-dp I wanted to do the same too. I got some problem, but now I can't understand what it was.  I'll try tomorrow.  I didn't find your color in material pallete https://material.io/guidelines/style/color.html#color-color-palette I will look something similar

**Comment by Den-dp** [comment]
@SaturnTeam good catch! Any color from 50-200 should fit perfectly

**Comment by lihanyu23** [comment]
@SaturnTeam try to use 50 or 100 from the palette. Also I like @Den-dp's idea.

**Comment by RaulRG** [comment]
The color should depend on the current theme. Not everyone will use blue. 
From the material design page: https://material.io/guidelines/style/color.html#color-color-system

> A primary color is the color displayed most frequently across your app’s screens and components. It can also be used to accent elements, if you don’t have a secondary color.
> To create contrast between elements, you can use lighter or darker tones of your primary color. 
> 

I don't know if the Angular material implementation defines something like primary_color and primary_color_light for the themes, but we are looking for a color to specify the "from" and "to" dates and a lighter version of this color to show the selected dates.

**Comment by RaulRG** [comment]
@Den-dp I like your design. I agree with you that it looks less noisy => better

**Comment by SaturnTeam** [comment]
@lihanyu23 I commeted to my repo https://github.com/SaturnTeam/material2 . Serving is the same as usual material dev. Range mode enabled on http://localhost:4200/datepicker "Result"

**Comment by Den-dp** [comment]
@SaturnTeam haha, but why? :stuck_out_tongue_winking_eye: Good work! :sparkles: The first one looks great for me!

Also here I tried to use a lighter 50 color and it looks even better

![image](https://user-images.githubusercontent.com/1770529/34871623-0f220cd6-f797-11e7-87b7-77ce215c6200.png)

Personally, I do like the mockup without border-radius on each day, because the shape helps the eye to distinguish important information (where are the starting and ending points of the range) and f.e. expectations about whether or not the last day in calendar (DEC 31) is the end of the range is more clear.

Also for reference flights.google uses filled background in their calendar too

![image](https://user-images.githubusercontent.com/1770529/34871816-9b139548-f797-11e7-9751-9cd82b99607f.png)

**Comment by SaturnTeam** [comment]
Ohh, just look how cute these neighborhood dates.
![image](https://user-images.githubusercontent.com/10252514/34931621-433cba30-fa02-11e7-98be-15b3cde0ec16.png)
Code is ready (see my repo). Writing tests and documentation in progress

**Comment by SaturnTeam** [comment]
@juliemr @mmalerba Proposal https://docs.google.com/document/d/14S3BvSm9o8_7VKwJU0ek59V7Cm4Yjt6OOoMj_lpfYZ0/edit?usp=sharing

**Comment by SaturnTeam** [comment]
I created from my code standalone package. Installation: ` yarn add saturn-datepicker` or `npm install saturn-datepicker`. Disscussion and info https://github.com/SaturnTeam/saturn-datepicker

**Comment by SaturnTeam** [comment]
Anyone knows about a11y with range selection?

**Comment by mischkl** [comment]
Our requirements (searching for documents within certain date ranges) dictate that the start and/or end dates may be empty if the user chooses. That way the date range can be used to mean "after a specific date" when only the start date is chosen, "before a specific date" when only the end date is chosen, "between two dates" when both are chosen, or "any date" when neither date is chosen.

This is something that most third-party implementations can't do, but that would be especially useful particularly for search interfaces! It would be greatly appreciated if this use case would be taken into account. :)

**Comment by SaturnTeam** [comment]
@mischkl Do you have any ideas how to do it through UI?

**Comment by RaulRG** [comment]
@mischkl These are exactly our requirements as well. The typical scenario for a range date picker is to use it for filtering data. Of course, there is another use case like "dates for your hotel booking" were you need fixed limits, but for filtering it is quite usual to have an "open" limit.

**Comment by mischkl** [comment]
Here is a mockup I made of what such a date picker control could look like. It would not only support empty start/end dates but also  keyboard-only data entry, which I believe is another important goal that the current date picker already fulfills.

![datepicker-mockup](https://user-images.githubusercontent.com/8177979/36108950-4857d6a8-101e-11e8-8312-2748867537aa.png)

**Comment by jelbourn** [comment]
@mmalerba for discussion above ^

**Comment by Carniatto** [comment]
+1  any news?

**Comment by mmalerba** [comment]
@SaturnTeam Apologies for the slow response. Your implementation appears to line up pretty well with what I envisioned for range selection. Would you like to have a quick meeting to discuss what we need to do to move it into the main repo? (feel free to shoot me an email: mmalerba@google.com)

**Comment by Carniatto** [comment]
+1 
@SaturnTeam any news on that?

**Comment by AllNamesRTaken** [comment]
In the demo stackblitz you cant drag to select and it also auto commits without first showing what was selected. I got a bit surprised. Perhaps a draggable selection would make that easier. Also a double month view would make it more clear IMO.

Great work though,

**Comment by shlomiassaf** [comment]
@mmalerba 
This is the implementation using inheritance: [StackBlitz source + demo](https://stackblitz.com/edit/angular-material2-issue-ft4uxg?embed=1&file=app/app.component.html)

I'll point the obvious, 95% of the code is due to inheritance boilerplate due to angular templates and component metadata in derived components. Some boilerplates is due to extensive use of **private** modifiers and not **protected**.

I estimate the entire change is ~75-85 lines of code.

From the above, the majority goes to TS code in the components.
SCSS changes are minimal, around ~8 LOC.
HTML changes are also minimal, ~10 LOC.

Will happily post a PR for this.

You'r comments in [#10489 (comment)](https://github.com/angular/material2/pull/10489#issuecomment-375034796) are taken care of because it uses the same logic the already exist to handle dates.

The only thing to take care of is a keyboard input of invalid date range (e.g. end date < start date)

**Comment by mmalerba** [comment]
@shlomiassaf I do like the direction that's going, but it's strange that you have two different form-fields that pretend to be one. Something we could do instead would be to wrap then in another component/directive that acts as a `MatFormFieldControl`. I imagine the DOM would look something like this:

```html
<mat-form-field>
  <mat-date-range [matDatepicker]="picker" [formControl]="range">
    <input matStartDate>
    <input matEndDate>
  </mat-date-range>
  <mat-datepicker #picker><mat-datepicker>
</mat-form-field>
```

**Comment by mmalerba** [comment]
I was imagining it being an object:

```ts
class DateRange<D> {
  start: D;
  end: D;
}
```

The `mat-date-range` would coordinate with the child inputs to keep this in sync.

**Comment by shlomiassaf** [comment]
Funny, that's exactly what I did just with 2 form fields and sync outside

**Comment by Den-dp** [comment]
Btw, today I found that flights.google.com recently got an update which kind of use similar ideas from UI point of view. Just happy, that we are thinking in "Material"-way. :wink:

![image](https://user-images.githubusercontent.com/1770529/40248332-47a978ec-5ad8-11e8-9cca-4a9d6b5c5c74.png)

**Comment by brazilia28** [comment]
Hi,
I tried to implement my own daterange from datepicker.
Here is the code and demo : [https://stackblitz.com/edit/angular-material-daterange](url)

Left calendar is to select a start date and right calendar is to select an end date.

My issue is when I select a first date less than the end date. The change detection doesn't work and the right calendar is not re-rendered. But, if I select another start date, the right calendar is rendered.

Have you any suggestion on my issue ?

Thx a lot

**Comment by SaturnTeam** [comment]
@brazilia28 See https://github.com/SaturnTeam/saturn-datepicker . your implementation also doesn't support input from keyboard without datepicker

**Comment by DanPride** [comment]
Wow, so happy to see this. I need both date, date range and day of week. Clicking on a MTWTF should select all the dates in that week.

**Comment by SnakeME** [comment]
Google Analytics also has a Material Design Datepicker. We need this please!!
![bildschirmfoto 2018-06-29 um 14 44 45](https://user-images.githubusercontent.com/1651752/42092987-23394340-7bab-11e8-997c-d82207e6ff30.png)

**Comment by DanPride** [comment]
What I don't understand if there is a million developers out there supposedly,... why are there less than a dozen of us talking about this fundamental capability ???

**Comment by yuliankarapetkov** [comment]
Hi guys, could you please share a possible release date for this feature with us? Thanks 🔢

**Comment by botoxparty** [comment]
+1 for this feature request. Massive gap in Angular Material's input functionality. Date range picker is pretty standard.

**Comment by DanPride** [comment]
I am just now diving into typescript.
I am wondering how much it would take to edit the existing date picker.
I have decades of experience
Any Idea how big a task this would be for multiple selection?


Dan Pride
1-605-777-0491
1-360-850-9322 (Mobile)
http://danielpride.com
www.linkedin.com/in/danielpride/
http://archaeolibrary.com/
http://headlessuber.com
http://kingsolomonsgate.com
http://solomonschariot.com

**Comment by TobiasMalikowski** [comment]
Hey guys, I'm curios what the current state of this feature is?

**Comment by botoxparty** [comment]
@TobiasMalikowski I gave up on this and wrote one from scratch following this youtube tutorial:

https://www.youtube.com/watch?v=ovamx9ePIuE

It was actually super easy and is way more powerful than a material component (in terms of customising its functionality)

**Comment by TobiasMalikowski** [comment]
@botoxparty Thanks for your link. I've looked into this and saved it as a fallback solution.
However I still hope that the guys working on the Material date picker will finish it.

This is a essential feature when working with dates, so I hope this gets finished in the near future.
Anyway would be nice to hear from @SaturnTeam and @mmalerba :)

**Comment by SaturnTeam** [comment]
@TobiasMalikowski I already have a package based on material source code https://www.npmjs.com/package/saturn-datepicker

**Comment by fxck** [comment]
There's this https://github.com/angular/material2/pull/13041 whatever it means..

**Comment by SaturnTeam** [comment]
It seems like refactoring of input value as I discussed with @mmalerba some months ago

**Comment by mmalerba** [comment]
@Trendy There are currently two people working on it and I'm reluctant to add more so that coordinating between us doesn't become more difficult. I'll let you know if a good place to contribute to this comes up

**Comment by kendallcarey** [comment]
@mmalerba https://github.com/angular/material2/pull/13041 it looks like this project is completed? I would also like to use this once its released

**Comment by sancaruso** [comment]
@mmalerba please do you have a date on which the project will be completed and released?

**Comment by liuganchen** [comment]
翘首以盼
Looking forward

**Comment by Githamza** [comment]
any news ?

**Comment by SaturnTeam** [comment]
Just use https://www.npmjs.com/package/saturn-datepicker for a while

**Comment by botoxparty** [comment]
Last time I used Saturn datepicker it was a disaster.

Honestly just code your own datepicker I dont know why people are waiting
for this to happen.

**Comment by margielm** [comment]
We are  using Saturn datepicker in a project and it is very ok. Can defenetly really recommend it.

**Comment by hanyu-natsu** [comment]
I'm also using saturn-datepicker, it's based on a clone of material datepicker.
Till now I don't really have any issue with it.

**Comment by l3ender** [comment]
Any update on inclusion of date range in core Angular Material?

**Comment by doom777** [comment]
Well, this is the update. I really hope it's coming soon. @mmalerba  Is it ready enough for you to slap a release version on this issue?

**Comment by l3ender** [comment]
Any update? @doom777 @mmalerba

**Comment by doom777** [comment]
I don't work here, but the branch shows active development.

**Comment by mmalerba** [comment]
We're hoping to have a refactor in for 8.0 that switches the mat-datepicker and related components to use a selection model under the hood. This would allow us to add the date range picker in a later minor release

**Comment by mjdiaz25** [comment]
Is there any update ?

**Comment by imransilvake** [comment]
any update regarding date range picker?

**Comment by Rodrigo54** [comment]
the angular materials team is working together with the angular core team to launch the ivy compiler, do not expect any new feature until the ivy be released

**Comment by JamesHearts** [comment]
any update on this feature?

**Comment by mmalerba** [comment]
Just wanted to give a quick update on this:

First, I want to give a huge thank you to @MathiasPaumgarten who has been working on this part-time for quite a while. This is a huge undertaking and Mathias has been doing some awesome work.

So the current state is that it's still in progress, but its slow going. This feature depends on a huge refactor of one of our most complex components. It's taking some time to make sure we get it right and don't break existing users.

The plan is to switch from having all of the sub-components manage their selected state through intercommunication with each other, to coordinating it all through a selection model object. Different selection models will support either single date selection or range date selection. The selection model refactor is close to being ready, the code can be found here: https://github.com/angular/components/tree/date-selection-model.

Meanwhile we have started a new branch that will contain both the selection model changes, plus additional components and UI to deal with selecting ranges of dates. That code will live here (currently it's just the selection model changes): https://github.com/angular/components/tree/date-range.

**Comment by shahbaazchaviwale** [comment]
Hi mmalerba ,

when this feature  get release , & how can adopt in project till release

**Comment by Pijuli** [comment]
Any news? 👀 🙄

**Comment by MathiasPaumgarten** [comment]
@Pijuli Still in review. Sorry that this is taking longer than expected.

**Comment by rvoltolini** [comment]
Hi, I need a Rangepicker with 2 calendar side by side.
I downloaded the project and I made a workaround to do it.
Exist the possibility of add this feature here?
![Captura de tela de 2019-08-14 16-15-36](https://user-images.githubusercontent.com/30928235/63049331-c9c18280-beae-11e9-8535-537d3f4400e4.png)

**Comment by SaturnTeam** [comment]
@rvoltolini You can make a pr in my repo. So, people would be able to you it.

**Comment by clement911** [comment]
is this still in progress? wondering if we should start looking for a third party solution.

**Comment by azollai** [comment]
It would be a very nice feature, please speed up the process!

**Comment by absalonv** [comment]
Any news?

**Comment by mmalerba** [comment]
There's nothing new to report here. Nobody on the core team currently has time to work on this, but we are still working with some contributors who are able to work on it part time

**Comment by BurneyFM** [comment]
I am looking forward to this for 2 years now -- it would be great if there was a way to speed up the process.

**Comment by maxiprosk8** [comment]
just add this line to your proyect styles.css or styles .scss and voilá
@import '~saturn-datepicker/bundle.css';

**Comment by TomDobbelaere** [comment]
This is an issue from 2017, it's almost 2020, I'm just saying
I've currently come across a scenario where I need this, the current solution is to use two datepickers next to each other 🤷‍♂

**Comment by margielm** [comment]
@TomDobbelaere  using 2 date pickers is one, but not the only, solution to this problem. We are using most excellent solution from @SaturnTeam   (mentioned in this thread few times) and we are very happy with it. 
It would be great to have official component - but in the meantime saturn-datepicker is doing the job.

**Comment by doom777** [comment]
Overall, I feel like Angular is dying. It just doesn't have that much energy behind it. Maybe Ivy will fix that.

**Comment by DanPride** [comment]
It would be awesome if we could include time in this.

Dan Pride
1-605-777-0491
http://danpride.com
https://SolomonsChariot.com
http://archaeolibrary.com/
http://kingsolomonsgate.com
http://www.linkedin.com/in/danielpride

**Comment by guyng** [comment]
@mmalerba any news?

**Comment by mmalerba** [comment]
We're hoping to do this in Q1, @crisbeto will be working on it

**Comment by guyng** [comment]
> We're hoping to do this in Q1, @crisbeto will be working on it

@mmalerba @crisbeto 
Many people are counting on you. don't let them down..

**Comment by Splaktar** [comment]
This is now on the roadmap for Q1 as mentioned above, see the rest of the roadmap [here](https://github.com/angular/components#high-level-work-planned-for-q1-2020-jan---mar).

**Comment by thiagojsf** [comment]
Looking forward to this feature... May we help somehow?

**Comment by Splaktar** [comment]
@thiagojsf you could help by testing it and providing feedback once it appears in [material-experimental](https://github.com/angular/components/tree/master/src/material-experimental).

**Comment by botoxparty** [comment]
@Splaktar Would love to contribute, happy to test if you can shout out on here when it's up on experimental

**Comment by SaturnTeam** [comment]
I'm also would like to add that version to my datepicker!

**Comment by guyng** [comment]
@Splaktar Just a reminder, it is beginning of march and it's not yet in the material experimental. You said it should be released this quarter :)

**Comment by rgm267** [comment]
> @Splaktar Just a reminder, it is beginning of march and it's not yet in the material experimental. You said it should be released this quarter :)

Well pressuring will really make sure it gets done quicker...

**Comment by guyng** [comment]
> > @Splaktar Just a reminder, it is beginning of march and it's not yet in the material experimental. You said it should be released this quarter :)
> 
> Well pressuring will really make sure it gets done quicker...

Yes, that's how it works usually. no pressure, no progress

**Comment by Splaktar** [comment]
> @Splaktar Just a reminder, it is beginning of march and it's not yet in the material experimental. You said it should be released this quarter :)

I said no such thing. I pointed you to the Q1 roadmap which is still there and goes though the end of March. Either way, trying to enforce artificial deadlines on a project that you don't pay for or contribute to is... inappropriate.

As an update, I'm not working on the date range support, but I've seen some great demos of how it's coming along. I think that people will be very excited to use it :) Like any other major feature, not all use/edge cases will be supported in the first release. After it gets released, we'll gather feedback and prioritize additional enhancements (as usual).

**Comment by guyng** [comment]
> > @Splaktar Just a reminder, it is beginning of march and it's not yet in the material experimental. You said it should be released this quarter :)
> 
> @guyng I said no such thing. I pointed you to the Q1 roadmap which is still there and goes though the end of March. Either way, trying to enforce artificial deadlines on a project that you don't pay for or contribute to is... inappropriate.
> 
> As an update, I'm not working on the date range support, but I've seen some great demos of how it's coming along. I think that people will be very excited to use it :) Like any other major feature, not all use/edge cases will be supported in the first release. After it gets released, we'll gather feedback and prioritize additional enhancements (as usual).

Well, it's been almost 3 years since the initial request, what reaction did you expect? people i'v worked with no longer trust your(angular team) word since you consistently have been missing deadlines(e.g. angular 9 should have been released half year ago, date range a year ago, etc etc). Nothing personal, just think about what i said. if you want to build trust with the community meet your deadlines. and FYI, i did contribute to quite a few angular projects by emailing bugs list & potential features.
From outside view, it looks like only by nagging you/angular team is actually making progress, but that's just my opinion. Cheers.

**Comment by crisbeto** [comment]
It is being worked on (you can see the [`date-range` branch](https://github.com/angular/components/commits/date-range)). It's still missing a couple of features like comparison ranges, but we're on track to have it done by the end of March.

**Comment by guyng** [comment]
> It is being worked on (you can see the [`date-range` branch](https://github.com/angular/components/commits/date-range)). It's still missing a couple of features like comparison ranges, but we're on track to have it done by the end of March.

Thanks for the update

**Comment by diogoterremoto** [comment]
Many thanks to all involved on this feature. Really excited to use it!

**Comment by Totati** [comment]
I wonder if it would be possible to use the date-range picker to set open ranges. Like 2020.03.05. - null; null - 2020.03.05. Cause that would be nice and handy.

**Comment by anbiniyar** [comment]
I am super excited for this feature!

**Comment by clement911** [comment]
We're also eagerly waiting for this feature!
Is there a page with a demo of the current version so that we can provide feedback before it goes live?

**Comment by Splaktar** [comment]
@clement911 not yet, you can try the branch out though (see https://github.com/angular/components/issues/4763#issuecomment-595116421).

**Comment by clement911** [comment]
@Splaktar  how do we 'try out' a branch?

**Comment by Splaktar** [comment]
@clement911 https://github.com/angular/components/blob/master/DEV_ENVIRONMENT.md#developer-guide-getting-your-environment-set-up. Then in the dev-app, you can check out the datepicker demo.

**Comment by clement911** [comment]
Thanks @Splaktar  but honestly I just wish there would be a simpler way, like a demo that we can play with to provide some feedback on the component UX.

Will we be able to play with the date range on https://next.material.angular.io/components/datepicker ?

**Comment by Splaktar** [comment]
@clement911 something like that will be made available in the future.

**Comment by demiro** [comment]
excited!

**Comment by mfarahat** [comment]
I am very excited for this, are there any updates ?

**Comment by jelbourn** [comment]
You can see the demo of the in-progress work here: https://jelbourn-dev.firebaseapp.com/datepicker

FYI after starting we, we got some feedback that led to expanding the scope of the initial work to make sure we'll be able to eventually support touch selection, comparison ranges, and customizable range selection.

**Comment by demiro** [comment]
great.... would be also good example to see option with 2 months open the the same time when selecting a range (check most of the airlines... ryanair.com or avianca.com or united airlines or turkish airlines) this would be the most ux friendly...

also, one very UX feature would be in the input mask, when clicking on a date, to have  a whole date selected .... so if I am editing 1st date in the range... and click on the second (and it was already in) to select the whole date (regardles of which part of the date I click) and obviously let me edit from the left onward...  

and, maybe give a setting option, to have date part selected on the first click

meaning, if I want to change a year of the second date, now I would have to click on that year, and then double click again to select all numbers and then start typing to override it... instead of clicking a year to be selected and start typing, or click to select all and click again to edit normally desired digit...

I appreciate might not be desired functionality for all, but would be a nice feature to have and be able to configure it easily

**Comment by clement911** [comment]
It looks pretty great!

But I don't understand why March 9th o March 13th shows in a different color?

![image](https://user-images.githubusercontent.com/3426504/77817617-7d892280-70cc-11ea-9e77-e170106e1687.png)


> great.... would be also good example to see option with 2 months open the the same time when selecting a range (check most of the airlines... ryanair.com or avianca.com or united airlines or turkish airlines) this would be the most ux friendly...

We would also very much like this option. Our current calendar actually shows 2 months already because it's very common to select a date range that span across 2 consecutive months.

**Comment by clement911** [comment]
I'm assuming the input mask will be customizable / localizable ?
e.g., mm/dd/yyyy or dd/mm/yyyy?

Also the first day of the week could be different depending on locale, is that supported? (sorry 
 if it is already, I haven't used the existing calendar component)

**Comment by perchristian** [comment]
Sometimes the range needs to be set to only one day (from/to same day). This is not possible in the provided demo.

**Comment by mmalerba** [comment]
First, let me just say that with a UI as complex as a date range picker, there are a ton of features and possible UIs, but unfortunately we can't do them all. 

Specifically to answer some of the questions above:

@demiro 
1. There are no plans to add a 2 calendar side-by-side view, though we do intend to allow the <mat-calendar> to be used as a standalone component so that users can build their own side-by-side experience. We do intend to add the ability to scroll through months, but not in the first release.
2. The two ends of the range are completely separate <input> elements, so adding a feature to select the whole range would be quite complicated. This is not something we plan to do.

@clement911 
1. The different color dates are what we call a "comparison" range. Its an extra feature we threw in because it was requested by a number of Google teams, but showing a comparison range is optional, so it can be left out if you don't need it.
2. Localization will work the same as the normal datepicker, the only localization feature added specifically for the range picker is that the divider character in the input can be customized

@perchristian That's a good point, let me run that one by our UX folks

**Comment by clement911** [comment]
Got it, thanks for these explanations.

> Sometimes the range needs to be set to only one day (from/to same day)

I really hope that you fixed that one otherwise we just wouldn't be able to use this component.

**Comment by perchristian** [comment]
The arrow icons for previous/next months are lacking hover state.

**Comment by perchristian** [comment]
Sometimes we need to provide the user with a month picker. Are you planning to support configuring the picker to have month as the lowest level?

By the way: I am so glad you are developing this date range picker now :)

**Comment by demiro** [comment]
@mmalerba: shame there are no plans for side by side range... this dramatically improves UX... hopefully you will reconsider soon

**Comment by margielm** [comment]
@demiro  this is really a UX discussion, but does a datepicker really  make sense for selecting a month? selecting a day is pretty "complex" for the user, because different months have different number of days, maybe you are interested in seeing day of a week, plus we have leap years. We don't have any of that complexity when you just want to select a month. 
One could say that he/she wants to use date-picker for selecting a month to have consistency, but I would argue that simple dropdown with a month name,  and an input/dropdown for a year - is easier to use.

**Comment by mmalerba** [comment]
Filed https://github.com/angular/components/issues/18958 for the missing hover state.

The concept of date granularity/precision is something we've thought about a bit, but currently no concrete plans.

Unless side-by-side view gets explicitly added to the Material Design spec, I think what's more likely is that we'll focus on trying to make it easier for users to implement that and other custom UIs using the same building blocks we use for the default datepicker experience, but I don't really see is adding an API specifically for that

**Comment by margielm** [comment]
@mmalerba unless i am missing something Material Design spec does have side-by-side pickers:

https://material.io/components/pickers/#desktop-pickers


![image](https://user-images.githubusercontent.com/684828/78067507-1f439480-7397-11ea-814e-89c9012b6096.png)

**Comment by mmalerba** [comment]
@margielm oh, so it does (sorry I've been looking at unfinished internal stuff, I didn't even realize there's an official published spec now 😄)

I've created https://github.com/angular/components/issues/18966 to track this, it won't be in the first version of the range picker though

**Comment by tobiasschweizer** [comment]
> The concept of date granularity/precision is something we've thought about a bit, but currently no concrete plans.

I would be glad to help with precision (month and year), please see https://github.com/angular/components/issues/4853#issuecomment-615162582.

**Comment by crisbeto** [comment]
The feature is now in master and will be released in 10. Please post bugs as new issue reports. Closing and locking.
