### ISSUE TITLE
md-checkbox inside <div md-dialog-content> shows vertical scrollbar

### ISSUE THREAD

**Issue by julianobrasil** [angular/components#4764]
#### Bug, feature request, or proposal:
Bug, I think. New issue based on a closed one (#4748), to provide more details.

#### What is the expected behavior?
When you use a md-checkbox inside a `<div md-dialog-content>` container the vertical  scrollbar must not be shown.

#### What is the current behavior?
The vertical scrollbar is beeing shown when you put the md-checkbox **as the last component inside md-dialog-content** (if you do not use md-dialog-content attribute, or if you do not put the md-checkbox as the last component, everything works just fine):

```
<div md-dialog-content>
  <div >
      test 1
  </div>
  <div >
      test 2
  </div>
  <div>
      <md-checkbox>This is a text test</md-checkbox>
  </div>
</div>
```

#### What are the steps to reproduce?
Just open a md-dialog with the above discribed setup. The result is shown in the image bellow the following plunker link.

plunker: https://plnkr.co/edit/pjTo0vekZfDV7eHEtsF6?p=preview

![image](https://cloud.githubusercontent.com/assets/25405143/26398496/07f82f5c-4050-11e7-8d30-a2d692aabe1b.png)

If you switch positions of the **test 2 div** and the **md-checkbox div**, the vertical scrollbar goes away:

![image](https://cloud.githubusercontent.com/assets/25405143/26398435/d9c712ce-404f-11e7-8cb2-e2f976ed703a.png)

#### What is the use-case or motivation for changing an existing behavior?
Use the md-checkbox inside md-dialog

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/cli: 1.0.4
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3

Typescript: 2.3.2

#### Is there anything else we should know?
I've noticed that if I do not put the checkbox as the last component of the md-dialog-container in the plunker example, the scrollbar isn't shown. I faced the problem in Chrome 58.0.3029.110, and did not test  in other browsers.

**Comment by mmalerba** [comment]
@tinayuangao looks like checkbox doesn't include sufficient margin/padding

**Comment by DevVersion** [comment]
@mmalerba Yeah it's kinda related to missing margin on the checkbox.

The absolute ripple container exceeds the boundaries of the `md-checkbox` element and therefore causes the scrollbars to appear.

In general I thought that all of our components should not have any outer-margin set by default.

**Comment by mmalerba** [comment]
@DevVersion This is mostly true, but it might make sense to wrap it in an extra `div` and add some padding, since it looks kind of bad when the ripple overflows. The `md-input-container` does this, that way the component supplies the minimum required "margin" and the actual margin is reserved for additional space the user may want to add

**Comment by tinayuangao** [comment]
I don't think we should add outer-margin for checkbox or add padding with an extra `div`. Checkbox often appear in groups and their ripple elements may overlap. It's also better to let user add outer-margin so margins can collapse. 
It looks strange when we reserve the padding only for ripples: 
![image](https://user-images.githubusercontent.com/20677343/27098361-1e20f6b0-502c-11e7-8d78-343e68ae74a1.png)

One possible change is remove ripple element from DOM when user `disableRipple`.

**Comment by julianobrasil** [comment]
@tinayuangao, what about exposing the margin through an input attribute to the developer change it when it's necessary?

**Comment by julianobrasil** [comment]
Or, if the problem really happens just when the checkbox is the last component of a container:
```
md-checkbox:last-of-type label {
  margin-bottom: 0.8rem !important;
}
```
Forgive me if these sugestions as kind of stupid... I'm no css expert.

**Comment by mmalerba** [comment]
I would say let's just create a CSS class that the use can optionally add `mat-checkbox-margin` or something like that, but I don't really know of anywhere else in the library where CSS classes are part of our API, I'm not sure if that's something we want to start doing...

**Comment by amysorto** [comment]
This still occurs with the MDC checkbox being the last element in the MDC dialog.

**Comment by mmalerba** [comment]
This is working as intended because, for accessibility purposes, the checkbox's touch target extends beyond the space it occupies in the layout. There are several ways you could design your dialog to avoid the scrolling:
1. (preferred) Put the checkbox inside of a `mat-dialog-content` region: https://stackblitz.com/edit/angular-vdfduj?file=src%2Fapp%2Fdialog-overview-example-dialog.html,src%2Fapp%2Fdialog-overview-example.html
2. Wrap it in a div with `overflow: hidden`
3. Apply a more dense theme for the checkbox which removes the touch target, e.g. `@include mat.checkbox-density(-3)`

Note that solutions 2 & 3 may be detrimental to the accessibility of your app because they reduce the size of the checkbox's touch target.
