### ISSUE TITLE
feat(checkbox) Custom icon for checked state

### ISSUE THREAD

**Issue by MaxMaes** [angular/components#4768]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Please allow choosing a icon to be used in md-checkbox. Perhaps this is possible by utilizing MdIcon?

#### What is the current behavior?
SVG is hardcoded and to change it, we need to extend MdCheckbox and copy over a lot of code.

#### What is the use-case or motivation for changing an existing behavior?
In my project, I need to show a couple of different icons in a checkbox, depening on the associated action:
![image](https://cloud.githubusercontent.com/assets/8969390/26403361/3db2e914-408e-11e7-844d-7f7125d77c0c.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
beta-5

**Comment by tinayuangao** [comment]
This svg is part of the material design spec: https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox

**Comment by feech** [comment]
that allows me override the tick image
`  .mat-checkbox svg path {
    d: path("M 4.1 12.7 L 9 17.6 L 16.3 6.3");
  }`

I think you could extract path from your .svg

**Comment by jelbourn** [comment]
Closing this since we have no plans to support customizing the checkbox icon.
