### ISSUE TITLE
Add general theme color css classes

### ISSUE THREAD

**Issue by mbeckenbach** [angular/components#4927]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
A CSS class md-color-primary or md-background-color-primary to reduce the need for custom theme mixins. See material lite. They do this.

#### What is the current behavior?
You have to create custom theme mixins for this.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Simplicity

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Ng4.1.x, MD beta 6

**Comment by rasert** [comment]
This would be very good to style things that are not contained within a material component.

**Comment by m98** [comment]
@mbeckenbach Could you please explain more how should it work?
You mean user define `md-color-primary` and other colors create based on the chosen color?

**Comment by mbeckenbach** [comment]
@m98 Yes, thats what I mean. Should be quite easy with the sass compiler, shouldn't it?

**Comment by m98** [comment]
@mbeckenbach! Okay, I got what you mean.

Thanks for the extra information, I just was not sure at the first if you mean this or not.
