### ISSUE TITLE
md-checkbox don't honor the [value] binding

### ISSUE THREAD

**Issue by lobo-tuerto** [angular/components#4994]
#### Bug, feature request, or proposal:
md-checkbox don't honor the `[value]` binding.

#### What is the expected behavior?
https://material.angular.io/components/component/checkbox mentions an `@Input value` property that can be set as the value for this input.

#### What is the current behavior?
It only uses boolean values, it does not use whatever the user specifies in `[value]`.

#### What are the steps to reproduce?
http://plnkr.co/edit/4ryXsamVJlcMaDHJsEgu?p=preview

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
When trying to implement a checkbox-list control I want to have an array with the values that are represented by the checkboxes.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material: 2.0.0-beta.6
Angular: 4.1.1

**Comment by macjohnny** [comment]
@lobo-tuerto you can get the value in the `(change)` event, ie. `(change)="$event.source.value"`
See this http://plnkr.co/edit/uEcocFj4q7EUUxebjQff?p=preview

**Comment by lobo-tuerto** [comment]
@macjohnny Thanks for the useful example.

So do you think it's currently behaving as expected or should it be different?

**Comment by macjohnny** [comment]
@lobo-tuerto I think this is currently behaving as expected. It is the behavior of ngModel, and not related to material / md-checkbox, since the input binding for the value exists.

**Comment by julianobrasil** [comment]
Maybe the confusion comes from the fact that the component has two different conteptual things: it's state (true/false) and it's value. Apparently, what's passed to ngModel is it's state. 

Take a look at this issue: #4926. Someone is asking to implement a kind of a MdCheckboxGroup. If it gets implemented, it'll possibly work like [MdRadioGroup](https://material.angular.io/components/component/radio), binding the `value` property of the selected checkboxes to ngModel of the MdCheckboxGroup.

**Comment by masterfloda** [comment]
I think this is a bug, not a feature. if you submit a HTML form with `<input type="checkbox" name="foo" value="bar">` the parameter foo will have the str value `bar`, not bool `true`.

**Comment by seth-git** [comment]
I agree with masterfloda, I'm trying to set a value in a reactive form on a mat-checkbox element via the [value]="some angular variable" attribute. All I get out of the form is true or null. I would expect to get the specified value or null since that's what a regular checkbox would give me.

**Comment by crisbeto** [comment]
The `value` does get passed down to the `input`, see https://github.com/angular/components/blob/main/src/material/checkbox/checkbox.html#L9. I think the confusion comes from the fact that the way `value` works on checkboxes isn't what most people would expect. There's some more information about it on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value. We're also matching the behavior of the checkbox from `@angular/forms`. I'm closing the issue, because it looks like it's working as expected.
