### ISSUE TITLE
Feature request: custom view value for select and autocomplete

### ISSUE THREAD

**Issue by xuanshenbo** [angular/components#5067]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Select and Autocomplete allow custom view values, for example:
https://material.io/guidelines/components/menus.html#menus-usage
<img width="570" alt="capture" src="https://user-images.githubusercontent.com/7393393/27009691-c4544504-4ee8-11e7-8292-aa1adb775200.PNG">

This Menu allows icons in addition to text.
I understand the example is a Menu not Select or Autocomplete, but they are under the same category in Material Design 

#### What is the current behavior?
The values are limited to strings, and doesn't allow custom layout inside the Select and Autocomplete dropdown.

#### What is the use-case or motivation for changing an existing behavior?
As per the example screenshot.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.6

**Comment by julianobrasil** [comment]
Have you try something like:
```
<div>
    text to the left
    <div style="float: right">text to the right</div>
</div>
```
In the autocomplete md-option? It works with text. Maybe it works with icons to (material fonts of fontawesome).

**Comment by julianobrasil** [comment]
Take a look at this plunker: https://plnkr.co/edit/v3EoZp?p=preview

![image](https://user-images.githubusercontent.com/25405143/27010236-0046b0ce-4e76-11e7-9808-d2da0048a15b.png)

**Comment by xuanshenbo** [comment]
@julianobrasil that looks great thanks!

However I accidentally noticed that your code doesn't work on Firefox 53.0.3

Can you raise a bug for that?

Thanks!

**Comment by julianobrasil** [comment]
I think it's an issue with nested divs in Firefox. I modified the plunker. This will work both in Chrome, Firefox, Edge and IE:

```
<div>
      <div style="float: left;">{{ state }}</div>
      <div style="float: right;">
            <i class="material-icons" style="font-size: 15px">add_location</i>
            {{state}}
     </div>  
</div>
```

**Comment by jelbourn** [comment]
Closing this since I believe it's doable today (it would just be your mat-option template). Free free to open another issue if that's not the case.
