### ISSUE TITLE
Enhancement for autocomplete & datepicker: allow for positionning the options/calendar panel elsewhere than next to the input

### ISSUE THREAD

**Issue by balteo** [angular/components#5205]
#### Bug, feature request, or proposal:
Proposal for enhancement for autocomplete & datepicker

#### What is the expected behavior?
Panel for autocomplete options or datepicker calendar can be positionned elsewhere than next to their related input field.

#### What is the current behavior?
Panel for autocomplete options or datepicker calendar cannot be positionned elsewhere than next to their related input field.

#### What are the steps to reproduce?

```
<div fxLayout="row">
  <div fxFlex="50">
    <form [formGroup]="formStatus.form">
      <div>
        <md-input-container>
          <input mdInput placeholder="Address" [mdAutocomplete]="auto" formControlName="address">
        </md-input-container>
      </div>
    </form>
  </div>
  <div fxFlex="50" style="background-color: palegreen">
    <!-- options panel should appear here in the palegreen div -->
    <md-autocomplete #auto="mdAutocomplete" [displayWith]="addressFormatter">
      <md-option *ngFor="let address of addresses | async" [value]="address">
        {{ address.description }}
      </md-option>
    </md-autocomplete>
  </div>
</div>
```

#### What is the use-case or motivation for changing an existing behavior?
Autocomplete and datepicker usage will be more flexible

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular material: 2.0.0-beta.6 

If I am wrong and this feature is currently available, maybe a update to the documentation would be worthwhile.

**Comment by skonx** [comment]
Got the same with 2.0.0-beta.7

**Comment by willshowell** [comment]
Seems like this could be useful for a search like inbox's
<img width="593" alt="screen shot 2017-06-20 at 9 15 49 am" src="https://user-images.githubusercontent.com/6475576/27335003-1937de9e-5599-11e7-8f2d-b8b1c04194b8.png">

**Comment by renestalder** [comment]
For a start, I would be happy to deactivate the automatic positioning based on space. Like having an option for positioning:

* auto: Current behavior
* bottom: force to always show below the input field
* top: force to always show above the input field
* custom: What this whole issue ticket is suggesting

**Comment by benelliott** [comment]
It's ugly, but for anyone else who is desperate for a workaround you can cast to `any` then overwrite your instance's `MatAutocompleteTrigger._getOverlayPosition()` and `MatAutocompleteTrigger._getHostWidth()` functions in `ngAfterViewInit` (assuming the autocomplete trigger is not destroyed until the host component is destroyed too).

```
    constructor(
        private hostEl: ElementRef
    ) {}

    public ngAfterViewInit(): void {
        (<any>this.autocompleteTrigger)._getOverlayPosition = () => this.getAutocompleteOverlayPosition();
        (<any>this.autocompleteTrigger)._getHostWidth = () => this.getAutocompleteHostWidth();
    }

    private getAutocompleteOverlayPosition(): PositionStrategy {
        const trigger = this.autocompleteTrigger as any;
        trigger._positionStrategy = trigger._overlay.position().connectedTo(
            this.hostEl,
            {originX: 'start', originY: 'bottom'}, {overlayX: 'start', overlayY: 'top'}
        ).withFallbackPosition(
            {originX: 'start', originY: 'top'}, {overlayX: 'start', overlayY: 'bottom'}
        );
        return trigger._positionStrategy;
    }

    private getAutocompleteHostWidth(): number {
        return this.hostEl.nativeElement.getBoundingClientRect().width;
    }
```

**Comment by dhatawesomedude** [comment]
@benelliott we tried this solution but it didn't fix the issue. Did this work for you?

**Comment by benelliott** [comment]
@dhatawesomedude Yes, but it assumes you want to attach the panel to the host element. What didn't work for you?

**Comment by balteo** [comment]
The latest version of angular material's autocomplete has the feature described above. See: https://material.angular.io/components/autocomplete/overview#attaching-the-autocomplete-panel-to-a-different-element

I am not sure about the datepicker though. Can anyone let us know if this is planned for the datepicker?

**Comment by ymongo** [comment]
@benelliott  you're the man! With your code I succeed in forcing autocomplete to always open down. 
I just have a minor issue: when ngAfterViewInit triggers, my autocomplete still undefined causing me an error. But it works as I intend it to, thanks again!
