### ISSUE TITLE
Setting global configs

### ISSUE THREAD

**Issue by jaetea** [angular/components#5266]
#### Bug, feature request, or proposal:
Documentation for setting up global configs

#### What is the current behavior?
   providers: [
        {provide: MD_RIPPLE_GLOBAL_OPTIONS, useValue: { disabled: 'true' }}
    ]

Responds with console error

src\material-main.ts(122,19): error TS2304: Cannot find name 'MD_PLACEHOLDER_GLOBAL_OPTIONS'.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by artem-galas** [comment]
The documentation already updated. 

https://material.angular.io/components/ripple/overview#global-options

So I guess the issue should be closed.

**Comment by jelbourn** [comment]
Closing since this exists now.
