### ISSUE TITLE
[Proposal] Add a guide on how to use Overlay

### ISSUE THREAD

**Issue by Goodwine** [angular/components#5288]
#### Proposal:
Add a guide on how to use Overlay, like there is one for theming and flexbox.

#### What is the use-case or motivation for changing an existing behavior?
I've been using overlay lately for a couple components, and it's a bit hard to use due to the lack of documentation, but it's easy once you understand what's going on. Thankfully I was able to understand some of it with the MdDialog and MdTooltip, as well as reading the Overlay code, but it was a tough learning curve which I feel I haven't conquered yet.

Some things that might be useful for such guide are:

* How to override the overlay container so I put things in a known DOM element and make it easier for testing.
* How to get the component instance or overlayRef in a test without having to keep a property in the object.
* How to use position and scrolling strategies and how to test them.
* How to create a new strategy.

**Comment by jelbourn** [comment]
This will probably be rolled into another issue before too long, but we do plan on adding documentation everything under the "cdk" umbrella, including overlay.

**Comment by jjreisfl** [comment]
Any ETA for this? I know you are doing a great work but it's frustrating to not be able to use it at full potential :\

**Comment by arlowhite** [comment]
Also, how to update an Overlay when the underlying host element is destroyed or `positionStrategy` needs to change.

I want to maintain the same `OverlayRef` and Component instance, but want to update the `connectedTo` element OR update the `positionStrategy`. I'm not certain how to do this or if it's possible with the current API.

FYI, my usecase is an Overlay on a Plotly chart; whenever my chart updates, the SVG element I connect to is destroyed.

**Comment by jelbourn** [comment]
Closing since the Overview for cdk/overlay covers this:
https://material.angular.io/cdk/overlay/overview
