### ISSUE TITLE
Datepicker UX Improvement: Enable selection of year

### ISSUE THREAD

**Issue by kasperhhk** [angular/components#5321]
#### Bug, feature request, or proposal:
Want to be able to select year

#### What is the expected behavior?
Being able to select year without having to +/- 1 year at a time

#### What is the current behavior?
Currently you have to +/- increment/drecrement the year by 1 every click.
It would be better to be able to select the year somehow, not sure what the best solution is.

#### What are the steps to reproduce?
Open the datepicker and try to select 1985, then try to go back to 2017.
It takes a lot of clicks.

you can check you own example to try it out:
https://material.angular.io/components/datepicker/examples 

#### What is the use-case or motivation for changing an existing behavior?
When you have more than a couple of years available for the user to select from it quickly becomes tedious and frustrating going from one end to the other.
If it's easier solved by reloading the page, then it's flawed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 2 beta 7

**Comment by donroyco** [comment]
Your title is misleading. Your suggestion is a UX improvement to the current solution.

**Comment by julianobrasil** [comment]
It'll be eventually added. See comment https://github.com/angular/material2/issues/675#issuecomment-290670361 and the following discussion. In fact you're asking for something not planed, I thing. Maybe it worths copying this sugestion in #675, where they're tracking other sugestions to the datepicker.

**Comment by kasperhhk** [comment]
I'd like to note that on a mobile device, if you want to change years it is very easy to accidentally trigger the zoom functionality of the device because you have to tap once per year increment / decrement.

**Comment by annieyw** [comment]
Closing this because the datepicker now has a year selection view.
![Screen Shot 2021-03-29 at 2 17 41 PM](https://user-images.githubusercontent.com/20130030/112901405-4d2cf780-9117-11eb-9c26-5b63a032f838.png)
