### ISSUE TITLE
input: align-end demo is broken

### ISSUE THREAD

**Issue by mmalerba** [angular/components#5332]
The align-end demo for the input looks strange now, following #5141 it seems like the placeholder is right-aligned, but the input content is not. The placeholder animation is also strange, it seems to get clipped.

FWIW I'm not sure if the old behavior was exactly right either? previously the input content was right-aligned while the placeholder was not.

**Comment by jelbourn** [comment]
What demo? In `demo-app/` or in `material-examples/`?

**Comment by mmalerba** [comment]
demo app, didn't check the examples

**Comment by crisbeto** [comment]
Looks like this was resolved a long time ago, but the issue was never closed.
