### ISSUE TITLE
Automatically create a live preview for every PR

### ISSUE THREAD

**Issue by hansl** [angular/components#553]
It might be a firebase server, or AppEngine.  I would consider building a docker on Travis as a Part I and then sending that docker to a server as Part 2.

**Comment by jelbourn** [comment]
One possible approach:
1) Add GitHub hook to remote server when a PR is opened / updated
2) Remote server pulls the PR, builds, copies build output to a directory and serves it.
3) Bot posts to the PR with a link to the preview

**Comment by DevVersion** [comment]
So, I'm working on this issue.

The following steps will be executed:
- Waiting for Github Webhooks
- Applies PR patch to a extra branch for the PR (`preview/pr-517`)
- Builds Distribution with Angular CLI
- Bundles **required** dependencies into a bundle (accelerates firebase deploy and load time significant) 
- Modifies the `index.html` with a virtual DOM, to use the bundle file.
- Removes unnecessary vendors (e.g ´@angular` - it's now in the bundle)
- Deploys new change to the Firebase Hosting
- Post's link to the PR preview to the PR.

I've already finished this and it's working very well.

I saved a lot of time, by building / enhancing the internal Angular Bot for Material 1 (in progress)

@jelbourn If you wan't to chat about the implementation or how we should continue, let me know :)

**Comment by DevVersion** [comment]
Here is a live preview, how it currently looks like. 

It has a build time of ~ 1-2 minutes (*minus* wasted time for manually executing the hook).

- https://github.com/DevVersion/material2/pull/2

Notice, how the bot posts the link of the automatically built preview. (Message is just temporary)

**Comment by jelbourn** [comment]
@DevVersion wow, that was fast. 

> Bundles required dependencies into a bundle (accelerates firebase deploy and load time significant)

Are you just running `npm install` on each PR to get the latest clean dependencies?

Overall sounds great. Once you make a PR, I can spin up a new firebase instance and we can simply point the code to that.
