### ISSUE TITLE
Change the width of the drop-down list in md-select

### ISSUE THREAD

**Issue by mladilav** [angular/components#5535]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Change the width of the drop-down list in md-select

#### What is the current behavior?

Width too large

#### What are the steps to reproduce?

http://plnkr.co/edit/IpfpkJ?p=preview

for example here http://imgur.com/a/zlr64 i need small width

**Comment by willshowell** [comment]
Select has a `panelClass` input ([api](https://material.angular.io/components/select/api)) that should help.

**Comment by mladilav** [comment]
But if i change min-width by class in 'panelClass', width jumped when list open and close

**Comment by jelbourn** [comment]
Closing since I think this issue is obsolete.
