### ISSUE TITLE
Toolbar in Dialog

### ISSUE THREAD

**Issue by Karasuni** [angular/components#5537]
Is there any support or planned support for [`md-toolbar`](https://material.angular.io/components/toolbar/overview) in [dialog/modal/popups](https://material.angular.io/components/dialog/overview)? In `angularjs-material` this was a built-in feature:

![ss 2017-07-06 at 01 53 41](https://user-images.githubusercontent.com/15806406/27909769-93471cd4-6252-11e7-9e33-daf0a808e83c.png)

What I observe in `angular-material2` is a padding that applies to the whole dialog box which prevents the toolbar from properly extending from end to end:

![ss 2017-07-06 at 01 48 13](https://user-images.githubusercontent.com/15806406/27909665-0c31f1d8-6252-11e7-825a-abbd069736c3.png)

```html
<md-toolbar [color]="['primary']">md-toolbar</md-toolbar>
<h1 md-dialog-title>md-dialog-title</h1>
<md-dialog-content>
  md-dialog-content
</md-dialog-content>
<md-dialog-actions>
  <button md-raised-button [color]="['primary']" disabled>Send Feedback</button>
  <button md-button md-dialog-close [color]="['warn']">Cancel</button>
</md-dialog-actions>
```

**Comment by julianobrasil** [comment]
You can use the panelClass to custom the dialog: https://plnkr.co/edit/s2RVEBQVxtDUmUBlUp2t?p=preview. 

Take a look at this @willshowell's https://github.com/angular/material2/issues/3239#issuecomment-312963660

![image](https://user-images.githubusercontent.com/25405143/27917634-e6db91e6-6242-11e7-8fb3-9aaf84ec8cae.png)

**Comment by Karasuni** [comment]
There's no built-in support or plans to support it?

I tried to declare the css at the component level since those definitions should not be on the global scope. It doesn't appear to work though: [Plunker](https://plnkr.co/edit/BKyoqdZ6cpRBRY8qjbGl?p=preview)

**Comment by julianobrasil** [comment]
> There's no built-in support or plans to support it?

I don't know.

> I tried to declare the css at the component level since those definitions should not be on the global scope

In that case you must set encapsulation to none in @Component object:
```
@Component({
  selector: 'dialog-result-example',
  templateUrl: 'dialog-result-example.html',
  encapsulation: ViewEncapsulation.None
})
```

**Comment by jelbourn** [comment]
@crisbeto thought? I could potentially see this as an option on the dialog-title

**Comment by crisbeto** [comment]
It makes sense to have it on the title, but I'm reluctant to add a dependency between the toolbar and the dialog. I'd rather duplicate some styles and add a `color` input on the title.

**Comment by jelbourn** [comment]
Yeah, I was thinking more of an option to not have any padding

**Comment by marcincichocki** [comment]
What is wrong with nagative margin on `md-toolbar`(http://plnkr.co/edit/ttsP4v?p=preview)?

**Comment by crisbeto** [comment]
There's nothing inherently wrong with reusing `md-toolbar`, but in general we try to avoid dependencies between Material modules.

**Comment by emilio-martinez** [comment]
Maybe the Dialog could load a component that has a toolbar and a portal to then load a template or component in that portal.

```
Dialog
--------------------------------------------
| DialogWithToolbar                        |
| ---------------------------------------- |
| | Toolbar                              | |
| | ------------------------------------ | |
| | Portal<MyComponent|TemplateRef>      | |
| ---------------------------------------- |
--------------------------------------------

Dialog <= Portal<DialogWithToolbar> <= Portal<MyComponent|TemplateRef>
```

**Comment by tawani** [comment]
`.mat-toolbar {
    margin: -24px;
    margin-bottom: 0;
    width: auto;
}
.mat-dialog-content {
    margin: 0 -24px;  
    padding:0 !important;   
}

.mat-toolbar-row, .mat-toolbar-single-row {
    height: 40px !important;
}`

**Comment by victorcarvalhosp** [comment]
I solved creating a simple new component like this: 

mat-toolbar-dialog.component.ts
```
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-mat-toolbar-dialog',
  templateUrl: './mat-toolbar-dialog.component.html',
  styleUrls: ['./mat-toolbar-dialog.component.scss']
})
export class MatToolbarDialogComponent implements OnInit {


  @Input()
  title: string;

  constructor() { }

  ngOnInit() {
  }

}
```


mat-toolbar-dialog.component.scss
```
.mat-toolbar {
  margin: 0 -24px;
  margin-bottom: 0;
  width: auto;
}

.mat-dialog-content {
  margin: 0 -24px;
  padding: 0 !important;
}

.mat-toolbar-row, .mat-toolbar-single-row {
  width: auto !important;
}

.spacer {
  flex: 1 1 auto;
}
```

mat-toolbar-dialog.component.html
```
<mat-toolbar>
  <button mat-icon-button class="left-icon" mat-dialog-close>
    <mat-icon>close</mat-icon>
  </button>
  <span>{{title}}</span>
  <span class="spacer"></span>
  <ng-content select="[right]"></ng-content>
</mat-toolbar>
```


And just use like that:
```
<app-mat-toolbar-dialog title="Dialog Title">
  <div right>
    <button type="button" mat-icon-button>
    <mat-icon>add</mat-icon>
    </button>
    <button type="button" mat-icon-button>
    <mat-icon>search</mat-icon>
    </button>
  </div>
</app-mat-toolbar-dialog>
```

**Comment by jpike88** [comment]
I just started migrating from ng1 to ng2, and the lack of toolbar in dialog support out of the box is a bit of a surprise. How hard would it be to make this happen.

**Comment by jelbourn** [comment]
Closing this since the Material Design 2018 spec update moved away from the idea of the colored "toolbar" at the top of content, so we're not doing much with it now. At the end of the day, though, the toolbar is little more than a div with a background color.

**Comment by Karasuni** [comment]
> Closing this since the Material Design 2018 spec update moved away from the idea of the colored "toolbar" at the top of content, so we're not doing much with it now. At the end of the day, though, the toolbar is little more than a div with a background color.

Does that mean you will be retiring components like `toolbar` or will you just stop supporting and updating them?

**Comment by Splaktar** [comment]
@Karasuni See https://github.com/angular/components/issues/13964 and https://github.com/angular/components/issues/16367.

**Comment by Karasuni** [comment]
Will the `top-app-bar` be supported in `md-dialog` components?

**Comment by Splaktar** [comment]
> Will the `top-app-bar` be supported in `md-dialog` components?

I don't believe that is part of the spec. However, you can always add a `div` with a background color (even using the `mat-color($app-primary)` mixing) and `class="mat-elevation-z1"` and styles for negative margins to create your own dialog toolbars.
