### ISSUE TITLE
Week Picker, Show other month's day

### ISSUE THREAD

**Issue by nguyennk** [angular/components#5588]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Pick the whole week instead of just 1 day
Show other month's day

#### What is the current behavior?
None

#### What are the steps to reproduce?
Just create any datepicker

#### What is the use-case or motivation for changing an existing behavior?
![weepicker](https://i.imgur.com/u6gldpa.gif)

I managed to make my own weekpicker (only show current month's day) by extend the current DateAdapter (to change start day to Monday), some jquery/angular to manipulate element then some styling as well.
Would be good to see some "actualy" support for this feature so i can get a cleaner code :)

**Comment by Almar** [comment]
@nguyennk, could you please share your current solution? Perhaps in a Plunker?

**Comment by Nodarii** [comment]
Hey guys, 

I have the very same situation. Need week selector. Looks like in the most cases this is useless functional. 
I propose to expose an api for selecting dates via typescript. 

```typescript 
this.picker.selectedChanged.subscribe((selectedDate)=> {
  this.picker.setSelectedDates(...dates)
});
```

It would solve part of the desired functionality, but it would not solve hover over the week (highlight).

What do you think about it?

**Comment by Hartaxfr** [comment]
This feature is a must have !

**Comment by mahf** [comment]
is there any plan or workaround solution?

**Comment by cerkiner** [comment]
@nguyennk, I would like to see how you achieved this

**Comment by mmalerba** [comment]
We have the option to select a range of date now, which should support this use case. https://material.angular.io/components/datepicker/overview#date-range-selection
