### ISSUE TITLE
Docs for various forms of lists with more examples

### ISSUE THREAD

**Issue by janjaali** [angular/components#5675]
#### proposal:
The list documentation lists a set of different usages. To get a better overview of the capabilities it would be nice to have a more complete set of list-usage-examples.

#### What are the steps to reproduce?
https://material.angular.io/components/list/overview

#### What is the use-case or motivation for changing an existing behavior?
The user had to copy&paste (integrate) the provided examples into his application to see what the usage (use case) of the list-modifier are.

**Comment by jelbourn** [comment]
We're working on more list variants now and will revisit the docs when those are ready.

**Comment by jflip** [comment]
@jelbourn would like to pick this up as a first contribution if that is okay?

**Comment by jelbourn** [comment]
This list overview now documents the various flavors of list:
https://material.angular.io/components/list
