### ISSUE TITLE
Truncate the toolbar text/title

### ISSUE THREAD

**Issue by peluprvi** [angular/components#5740]
#### Bug, feature request, or proposal:
Request for an element to truncate the toolbar text/title.

#### What is the expected behavior?
https://material.angularjs.org/latest/demo/toolbar

#### What is the current behavior?
Long text overflows to the right, pushing buttons with it.

#### What are the steps to reproduce?
```html
<md-toolbar color="primary">
  <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>

  <md-toolbar-row>
    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>
    <span class="example-spacer"></span>
    <md-icon class="example-icon">verified_user</md-icon>
  </md-toolbar-row>

  <md-toolbar-row>
    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span>
    <span class="example-spacer"></span>
    <md-icon class="example-icon">favorite</md-icon>
    <md-icon class="example-icon">delete</md-icon>
  </md-toolbar-row>
</md-toolbar>
```

#### What is the use-case or motivation for changing an existing behavior?
Provide a default element to truncate the toolbar title.

#### Is there anything else we should know?
https://github.com/angular/material/issues/9026

Possible solution is create a `.mat-toolbar-title` on [toolbar.scss](https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.scss):
```scss
.mat-toolbar-title {
  @mixin mat-truncate-line();
  flex: 1 1 auto;
}
```

**Comment by DevVersion** [comment]
I remember that there was a discussion here on GitHub about the same already.

It all comes back to the same issue origin as in https://github.com/angular/material2/issues/5212#issuecomment-311135943.

As a solution, I like the idea of having a class or attribute that developers can apply to have an ellipsis on their title.

**Comment by devversion** [comment]
Coming back to this, I think we should simply document how one can have a text ellipsis for toolbar contents. Providing these styles by default from within the toolbar is rather inconvenient as we cannot assume which element is pure text or not (and we do not want to hide overflow incorrectly).

We should document that the following can be used to truncate toolbar content:

```scss
.my-toolbar-title {
  text-overflow: ellipsis;
  overflow: hidden;
}
```

**Comment by jelbourn** [comment]
Closing this since it's more of a general css thing rather than something specific to `mat-toolbar`.
