### ISSUE TITLE
Feature request: Add support for notification of changes to `[dir]` on `<html>` and `<body>`

### ISSUE THREAD

**Issue by parker-mike** [angular/components#5761]
As specified in guides/bidirectionality.md regarding `change` property of `Directionality`:
> It will not emit for changes to dir on <html> and <body>, as these are assumed to be static.

I'm not sure that this is a correct assumption to make, since overlayed items(`div.cdk-overlay-container`) are generated outside the Angular application context, so currently we don't have a single point to change the layout of the application. And since overlayed items, like dialogs, do represent integral parts of an application, I believe that it should be possible to notify these components of changes to `dir` on `<html>` and `<body>` using the same `Directionality` feature, since these nodes are the only common ancestors of both `div.cdk-overlay-container` and Angular application context.

Since @jelbourn in his [comment](https://github.com/angular/material2/pull/5474#discussion_r126516018) said that this is something that could potentially change in a subsequent iteration, I decided to open this feature request for a discussion.

**Comment by zehavibarak** [comment]
Could be helpful. Right now we need to set direction on every dialog open, and set dir manually per overlay portal.

**Comment by jelbourn** [comment]
Closing this since it's a pretty niche use-case to need to know when the `dir` changes outside of the Angular context. If someone really needs it, you can provide a custom `Directionality` that does this via a `MutationObserver`.
