### ISSUE TITLE
[Tabs] Create TabsKeyManager to reduce duplication between tabs and stepper

### ISSUE THREAD

**Issue by g1shin** [angular/components#5916]
`md-tab` and `md-stepper` both have `tab` roles that follow the same keyboard interaction pattern. 

Creating `TabsKeyManager` will reduce duplication between tabs and stepper components.

**Comment by crisbeto** [comment]
This one shouldn't be necessary anymore since the `ListKeyManager` supports horizontal directions.

**Comment by crisbeto** [comment]
Closing since `ListKeyManager` has had horizontal support for a long time now.
