### ISSUE TITLE
Selector enabling use of md-grid-tile with <a> tag

### ISSUE THREAD

**Issue by goelinsights** [angular/components#5918]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Grid tile can be used with routerLink to generate a href link. I'm using a visual navigation and realized there are no href tags generated with grid-list current implementation

#### What is the current behavior?
Grid tile with routerLink generates ng-reflect-router-link but no href tag unless an a tag is put in a level below (which in combination with mat-figure creates some formatting issues)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
SEO spiders often use href tags.  Hiding the tags reduces SEO visibility

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Angular Material 2.0.0-beta.8

#### Is there anything else we should know?
Should be able to fix, ie <a md-grid-tile> per the pattern used with md-card

**Comment by jelbourn** [comment]
Closing this because we are pretty unlikely to add new features to `MatGridList` going forward now that CSS Grid provides a significantly more robust tool for creating this style of layout.
