### ISSUE TITLE
Support for yPosition in mat-select

### ISSUE THREAD

**Issue by naveedahmed1** [angular/components#5934]
#### Bug, feature request, or proposal:
Please add support to specify yPosition for md-select as available in md-menu.

`@Input() yPosition | Position of the md-select in the Y axis.
`
md-select is able to position the select select list menu properly in almost all of the cases. But there could be cases in which we would want to specify the position of the select list on y axis. Let me share a use case. I have a bootstrap nav bar which is fixed on top. If I place a md-select below the navbar and select the last item in the select list and then close and re-open the list, part of it is hidden under navbar.

To fix this I have to increase z-index:

```
.cdk-overlay-container {
    z-index: 1030 !important;
}
```

Although it provides a workaround, but I believe it would be better if we could set yPosition though md-select api and set it to yPosition="below" so that select list open below.

**Comment by djtahl** [comment]
Hello any possibility to raise this topic again ? we have this option of yPosition for the menu component, I think it would be relevant to have it on the select as well.

**Comment by crisbeto** [comment]
I'm closing this since we're moving towards having the select dropdown always open below the trigger.
