### ISSUE TITLE
Report the number of pixel difference & percentage in screendiff test

### ISSUE THREAD

**Issue by tinayuangao** [angular/components#6012]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Report the number of pixel difference & percentage in screendiff test

#### What is the current behavior?
The test result only report pass/fail status. No pixel difference value/percentage reported

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Is there anything else we should know?
The result object have `{total: root mean square pixel difference of all pixels, percentage: percentage of difference}`
We should also change to `getFullReport` to get the pixel result.

**Comment by crisbeto** [comment]
Closing since we haven't been running screenshot diffs for a long time now.
