### ISSUE TITLE
datepicker: Integrate new angular i18n API into NativeDateAdapter

### ISSUE THREAD

**Issue by mmalerba** [angular/components#6030]
Angular core team is working on a new i18n API that should allow us to significantly improve the experience users get with the `NativeDateAdapter`. We should be able to make it work in browsers that don't support `Intl.DateTimeFormat` and most importantly we should be able to implement reasonable default parsing behavior for all locales.

**Comment by mmalerba** [comment]
Currently blocked on new i18n API being available in Angular

**Comment by denirun** [comment]
@mmalerba you can check my solution here #8100

**Comment by StefanKern** [comment]
Is this issue still open in 2019? Do we still none americans still depend on this dirty [hack] to not have manually entered dates changed? (https://github.com/angular/material2/issues/6263#issuecomment-320211085)?

**Comment by t00** [comment]
Mat looks like still in beta to me

**Comment by mmalerba** [comment]
Closing as a dup of https://github.com/angular/components/issues/8100
