### ISSUE TITLE
[Tabs] Scrollbar shows on tab changes

### ISSUE THREAD

**Issue by Robouste** [angular/components#6104]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
Have a smooth transition, no matter what's inside my tabs

#### What is the current behavior?
If the previous tab has a content longer (in height) then the md-list on the next tab, a scrolling bar is showing

#### What are the steps to reproduce?
[PLUNKR](http://plnkr.co/edit/bXbrjYEICBpMUjvMNoae?p=preview)
Switch from tab 1 to tab 2 to see the scrolling bar

#### What is the use-case or motivation for changing an existing behavior?
No unwanted effects

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta.8
Angular 4

**Comment by donroyco** [comment]
@Robouste What browser are you referring too? Next to that, please add `dynamicHeight` to your `md-tab-group` to see if it resolves the issue.

**Comment by grizzm0** [comment]
I noticed this myself the other day. Adding `dynamicHeight` as suggested by @donroyco solved the issue for me.

**Comment by Robouste** [comment]
hmm, that's wierd. Without the attribute, the height is dynamic but I see the scrollbar. With the attribute, the height is also dynamic but the scrolling is gone

**Comment by MA-Maddin** [comment]
facing the same issue.
Adding `dynamicHeight` prevents scrollbar from appearing, but sadly causes heavy impact on the height transition of my wrapper element.

**Comment by vincecampanale** [comment]
`dynamicHeight` removed the scrollbar when switching between tabs, but prevented the scrollbar from appearing in a tab that had overflow. Adding the following to my stylesheet did the trick:
`
mat-tab-group {
  height: 100%;
}
`

**Comment by vincecampanale** [comment]
Is it possible to have the scroll bar not show up between tab transitions, but still show up when there is overflow?

**Comment by seaBubble** [comment]
Adding dynamicHeight does not completely solve the issue for me.
The scrollbar still appears on the first tab change, then it stops appearing.

**Comment by Hextar** [comment]
@seaBubble I'm unsing dynamicHeight and I've proably managed to solve this with

`.mat-tab-body-content {
    &.ng-animating {
      overflow: hidden !important;
    }
  }`

added to my theme.scss

**Comment by seaBubble** [comment]
@Hextar I have tried that but I can still the scrollbar, unfortunately. Thanks for the suggestion though.
Are there any plans to look into fixing this?

**Comment by mmalerba** [comment]
Confirmed that there is no scrollbar during animation in v15: https://stackblitz.com/edit/angular-shzd6r-pwokjj (tested on Chrome w/ MacOS)
