### ISSUE TITLE
Screen readers announcing wrong amount of options after filtering in autocomplete

### ISSUE THREAD

**Issue by crisbeto** [angular/components#6255]
Steps to reproduce with NVDA and Firefox:
1. Open the autocomplete a11y demo.
2. Focus the input and press the down arrow.
3. At this point the screen reader reads out something along the lines of "Alabama, not selected 1 of 50".
4. Type "D" and press the down arrow. At this point the screen reader announces "Delaware, not selected, 1 of 1".
5. Delete the input text and press the down arrow. At this point there are 50 rendered options, however the screen reader reads out "Alabama, not selected, 1 of 1". When pressing down again the states get read out, but the list length isn't announced.

**Comment by jelbourn** [comment]
I just tested this with latest everything (material, Firefox, nvda) and it all works as expected.
