### ISSUE TITLE
[Feature Request] make all components and services extensible

### ISSUE THREAD

**Issue by e-cloud** [angular/components#6264]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Most of private fields and method of components and service should be declared as **protect**

#### What is the current behavior?
All of them is private, unable to perform inheritance.

#### What are the steps to reproduce?
I happen to implement a component trying extends `MdDatepicker`,
```ts
@Component({
    selector: 'md-datetimepicker',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MdDatetimepicker<D> extends MdDatepicker<D> implements OnDestroy {
    // ...
    constructor(
        private _dialog: MdDialog,
        private _overlay: Overlay,
        private _ngZone: NgZone,
        private _viewContainerRef: ViewContainerRef,
        private _scrollDispatcher: ScrollDispatcher,
        @Optional() private _dateAdapter: DateAdapter<D>,
        @Optional() private _dir: Dir,
        @Optional() @Inject(DOCUMENT) private _document: any
    ) {
        super(_dialog, _overlay, _ngZone, _viewContainerRef, _dateAdapter, _dir, _document)
    }
    //...
}
```

but the compiler complains something like this:
```
TS2415:Class 'MdDatetimepicker<D>' incorrectly extends base class 'MdDatepicker<D>'.
  Types have separate declarations of a private property '_dialog'.
```

if I remove the private declaration like:
```ts
    constructor(
        _dialog: MdDialog,
        _overlay: Overlay,
        _ngZone: NgZone,
        _viewContainerRef: ViewContainerRef,
        _scrollDispatcher: ScrollDispatcher,
        @Optional() _dateAdapter: DateAdapter<D>,
        @Optional() _dir: Dir,
        @Optional() @Inject(DOCUMENT) _document: any
    ) {
        super(_dialog, _overlay, _ngZone, _viewContainerRef, _dateAdapter, _dir, _document)
        if (!this._dateAdapter) {
            throw createMissingDateImplError('DateAdapter')
        }
    }
```

then, I can't access parent class's private fields.

#### What is the use-case or motivation for changing an existing behavior?
We should provide the possibility to extends the components and services. There is not any potential secure problem to prevent users to do this kind of extension, theoretically.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material2 2.0.0-beta.8, Angular 4.3.2, Typescript 2.4.2, all browsers, all OSes.

#### Is there anything else we should know?
no

**Comment by moshejs** [comment]
I agree. Would love to implement floating Fab based on FAB, or create a card with md-toolbar

**Comment by shyamal890** [comment]
+1

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because I don't see us realistically doing it. Our existing public API surface is already massive, and if we were to mark everything as `protected`, it would be even larger, possibly up to the point where every minor adjustment we make will become a breaking change.
