### ISSUE TITLE
Button toggle text highlight bug

### ISSUE THREAD

**Issue by scottarver** [angular/components#6409]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When text is highlighted, and a button group toggle item is clicked, the item click should respond/change. 

#### What is the current behavior?
When text is highlighted, and a button group toggle item is clicked, the item click does not respond or change. 

#### What are the steps to reproduce?
![button toggle](https://user-images.githubusercontent.com/6730885/29192665-cdbfe930-7de7-11e7-912e-9321ce9a3646.gif)

https://plnkr.co/edit/I5s7xNpnzOGCze5wU6K7?p=preview
Highlight the word "Selected" with the mouse, then click on one of the button toggles. 

#### What is the use-case or motivation for changing an existing behavior?
Having text highlighted on the page prevents button toggle groups from working, making the page seem like its broke.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/core @4.3.4
typescript 2.1.6
angular/material 2.0.0-beta.8

#### Is there anything else we should know?
A double click causes the highlighted text to become unlighted, and then it works.

**Comment by luanribeiross** [comment]
Also affects me. When changes like that are made.. arent you supposed to make it to be a beta 9 or something?

**Comment by DiyanDimitrov** [comment]
This issue seems to be fixed in the latest version. Here is an updated sample link:
https://stackblitz.com/angular/mddrjdpjlgn?file=app%2Fbutton-toggle-exclusive-example.ts

**Comment by crisbeto** [comment]
It sounds like this issue was fixed a long time ago. Closing.
