### ISSUE TITLE
set md-select width to width of its longest item

### ISSUE THREAD

**Issue by HegdeSach** [angular/components#6448]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
configure md-select box to use the width of the longest item.
![power designer - google chrome_3](https://user-images.githubusercontent.com/21358983/29259442-a539d8c6-80e0-11e7-84e7-899018b34300.jpg)

#### What is the current behavior?
md-select box has fixed width and it displays ellipsis for the longest item when selected
![power designer - google chrome_2](https://user-images.githubusercontent.com/21358983/29259447-aa2312a8-80e0-11e7-9264-b50d9edd57cf.jpg)

**Comment by kkotak** [comment]
Also allow md-select to grow to 100% of its parent container.
