### ISSUE TITLE
(Angular/CDK) Expose more methods from interactivity-checker

### ISSUE THREAD

**Issue by changLiuUNSW** [angular/components#6468]
I want to use some methods like ```isNativeFormElement```, ```isHiddenInput```, ```isInputElement``` and ```isAnchorElement``` from ```interactivity-checker```, but I find they are not accessible from ```InteractivityChecker``` service.
eg: ```isNativeFormElement```
https://github.com/angular/material2/blob/master/src/cdk/a11y/interactivity-checker.ts#L155

Can we move those functions into the ```InteractivityChecker``` service so that we can access them?

**Comment by crisbeto** [comment]
@jelbourn does it make sense to expose these? The checks seem pretty trivial.

**Comment by jelbourn** [comment]
@changLiuUNSW can you elaborate on why you want to use these functions?

**Comment by changLiuUNSW** [comment]
We have some scenarios need to find first native form element and trigger focusing for accessibility purpose.

**Comment by jelbourn** [comment]
For your second and third points, why are `isTabbable` and `isFocusable` not what you want? Those methods are really more implementation details than anything universally meaningful.

**Comment by changLiuUNSW** [comment]
@jelbourn 
```isTabbable ``` does not work for element with ```tabIndex= -1 ```, so it wont work for my second point.
Also  ```isFocusable ``` does not work for invisible element, so it wont work for my third point.

**Comment by changLiuUNSW** [comment]
@jelbourn
If you guys are OK with it. I will create a PR soon.

**Comment by jelbourn** [comment]
Closing this since I think that it's both obsolete and something we don't want to do.

**Comment by vanessanschmitt** [comment]
Hey @jelbourn! I was also hoping to use isPotentiallyFocusable. My use case is that I'm searching for the first focusable invalid element in a form, but the element may be in a collapsed section of the form, so isFocusable returns false because isVisible returns false. Would you be open to exposing isPotentiallyFocusable, or should I copy the implementation to our code base since that method isn't too much code? Let me know!

**Comment by jelbourn** [comment]
@vanessanschmitt I would be good with making `isPotentiallyFocusable` focusable, though I may want to bikeshed the name a bit to be less ambiguous.
