### ISSUE TITLE
Material's custom swipe recognizer sets touch-action: none

### ISSUE THREAD

**Issue by jelbourn** [angular/components#6484]
The custom recognizers in `GestureConfig` are causing `touch-action: none` to always be added to elements with _any_ hammer event. This is problematic because it will prevent normal scrolling. The `swipe` recognizer seems to be the culprit (with both `pan-y` and `pan-x` actions being tied to the recognizer, even though we only want `pan-y`)

We should probably only be adding recognizers that correspond to the events being listened for. This would require a (non-breaking) change in `@angular/platform-browser` to pass the event name to the `buildHammer` function.

**Comment by intellix** [comment]
Got this after updating to Angular 9 and this fixed it for us: https://github.com/hammerjs/hammer.js/issues/1014#issuecomment-298724577

**Comment by jelbourn** [comment]
Closing this since we have completely removed all HammerJS code in v10.
