### ISSUE TITLE
[Tooltip] Not working with contenteditable on iOS

### ISSUE THREAD

**Issue by Matthi0uw** [angular/components#6492]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Correct behavior is to create a contenteditable html mark or input with mdTooltip directive.

#### What is the current behavior?
We can create with only 1 of 2 elements, when html mark got both it's not working.
This behavior work in Chrome and Firefox...

#### What are the steps to reproduce?
Here my demo: http://plnkr.co/edit/3AbfAd0DJWUZjZ9xTLX9?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I would like to have an html mark editable with a tooltip when there is an error (display with the tooltip).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browser: safari (iOS)

**Comment by jelbourn** [comment]
We tried this out and found that the tooltip does show up on longpress as normal on a `contenteditable` div. You should, though, also be able to apply `matTooltip` to a container element if necessary.
