### ISSUE TITLE
MdSelect - md option doesn't fit the select container using dialog + flex layout

### ISSUE THREAD

**Issue by dhuallanca** [angular/components#6655]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Options should fit the select container

#### What is the current behavior?

Options container is smaller than select container.
#### What are the steps to reproduce?

https://plnkr.co/edit/yEtylQm2RDDrNGQu9GMI?p=preview

1. open the dialog
2. select an option
result: option container is smaller 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular v4.3
@angular/material 2.00 -beta8
@angular/flex-layout

**Comment by dhuallanca** [comment]
Hi @crisbeto, any update of this bug? I want to know when it will be merged :) or maybe you can give a work around.

**Comment by crisbeto** [comment]
It looks like the root cause for this issue was resolved a long time ago (https://github.com/angular/components/pull/6658#issuecomment-335253885). Closing.
