### ISSUE TITLE
Allow md-expansion-panel toggle to be placed at the beginning

### ISSUE THREAD

**Issue by alex321** [angular/components#6726]
#### Feature:

Give an option to allow the toggle of the `md-expansion-panel` to be placed at the beginning.

#### What is the current behavior?

The toggle is always placed at the end of the panel.

#### What is the use-case or motivation for changing an existing behavior?

Frequently people prefer to place it before the text for the panel.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
2.0.0-beta.10

**Comment by zladuric** [comment]
Hi,
Just a thought on this - while you're at it, could there also be a "no indicator at all" option? I mean, open panel only programatically and hide indicator? I guess those'd be two feature requests, but I'm willing to give it a try if somebody points me in the right direction.

I have such a use case now, so I'm struggling to steal clicks from the panel and it's ugly.

**Comment by josephperrott** [comment]
The current PR that for this feature actually has a `hidden` option.

For the ability to make it only open programmatically, I would suggest filing a separate issue to track it

**Comment by g-sari** [comment]
I opened this issue which is similar to this topic
https://github.com/angular/material2/issues/9337

**Comment by josephperrott** [comment]
Reopening as the PR to address this was rolled back
