### ISSUE TITLE
Incorrect initial placeholder position after update to beta.10

### ISSUE THREAD

**Issue by MaickelHubner** [angular/components#6849]
#### Bug, feature request, or proposal:
When init the component the placeholder is being shown over the content. After the focus it returns to normal

#### What is the expected behavior?
Placeholder showed in normal position since init

#### What is the current behavior?
<img width="328" alt="before" src="https://user-images.githubusercontent.com/15674062/30067915-8ba16a10-9232-11e7-8b73-77ef38ec98b7.png">
<img width="267" alt="after" src="https://user-images.githubusercontent.com/15674062/30067931-9679b51e-9232-11e7-82cc-6975157b949f.png">

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular4, Material 2.0.0-beta.10, browser Safari

**Comment by MaickelHubner** [comment]
I create a plunker, but there it works :-(

http://plnkr.co/edit/X7ZSaGW7t8nFx3KHQ09K?p=preview

**Comment by mmalerba** [comment]
#5692 changed input to use `OnPush` change detection. It sounds like this may be related to that. Is the data shown in the inputs loaded asynchronously?

**Comment by MaickelHubner** [comment]
Does not work too!!!
If I remove the option [formControl]="inputControl" of the input in HTML or if I remove the ? of the [value]="inputValue?.descricao" it worked well (but I receive the TypeError: undefined is not an object (evaluating '_co.inputValue.descricao') error).

**Comment by MaickelHubner** [comment]
I also realized that the change in conta.descricao do not appear in ngOnChanges, only in writeValue

**Comment by Tempus35** [comment]
@mmalerba I am having this issue as well and the data is patched/set after it is received from the server, the form is setup with blank values at first. But even after being added to the form, it is showing up in the inputs, the placeholder does not move till you click into the input.

**Comment by willshowell** [comment]
@Tempus35 can you reproduce either?

Here's a starter template: http://plnkr.co/edit/jZoIp0f9R4Krrm33w8VR?p=preview

**Comment by Tempus35** [comment]
@willshowell http://plnkr.co/edit/hTVZbkIUChw6SgTWDRFC?p=preview it appears to be when you do what I am doing int he plunker with making a new control or in the case of the component in this code I am working on, a form group. I will be changing my code to patch/set the value not make a new group. But that seems to be the cause.

**Comment by mmalerba** [comment]
Yep, this is due to `OnPush` change detection. Using `patchValue` instead of creating a new `FormControl` works: http://plnkr.co/edit/TmlV6lRpNRGRFYrpM9S5?p=preview

@crisbeto is there a way for us to detect if they give us a completely new `FormControl` and run change detection?

**Comment by Tempus35** [comment]
@mmalerba Another place this is an issue is on login forms, where the input might be filled in via a password manager. When the password manager fills in the inputs the placeholder is not moving up as it once did.

**Comment by MaickelHubner** [comment]
To fix the problem I simply used the setValue function of the formControl inside the set method:

`set inputValue(val) {
    this._inputValue = val;
    this.propagateChange(this._inputValue);
    if (val) {
      this.inputControl.setValue(val.descricao);
    }
  }`

**Comment by mmalerba** [comment]
@crisbeto That works for `formControl` since it goes on the input, but what if we had a `formGroup` on some parent element?

**Comment by crisbeto** [comment]
Not without defining our own directive that looks for `[formGroup]` @mmalerba.

**Comment by mmalerba** [comment]
Ok, so I see a couple ways we could deal with this:
1. Tell people not to do this
2. Tell people not to do this, but provide a `runChangeDetection` method for them to call if they must
3. Create a directive that matches `formControl` `formGroup` `formArray` any others? Inject that and use it to run change detection appropriately
4. Go back to `ChangeDetectionStrategy.Default`

@jelbourn @crisbeto

**Comment by jelbourn** [comment]
@kara do you have any input on this?

**Comment by zoechi** [comment]
I'm still seeing this with `OnPush`
