### ISSUE TITLE
Update list docs to indicate md-line directive instead of mdLine directive

### ISSUE THREAD

**Issue by nayfin** [angular/components#6876]
#### Bug, feature request, or proposal:
Documentation typo on [material.angular.io](https://material.angular.io/components/list/overview)

#### What is the expected behavior?
`md-list-item`s use `md-line` directive to create multi-lined list-items

#### What is the current behavior?
documentation under **Overview** tab calls it the `mdLine` directive

#### What are the steps to reproduce?
Update a few lines of HTML
Changes all instances of `mdLine` to `md-line`

#### What is the use-case or motivation for changing an existing behavior?
To give accurate documentation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Docs

#### Is there anything else we should know?
Nope

**Comment by jelbourn** [comment]
The docs currently say `matLine`, which is the correct, intended attribute.
