### ISSUE TITLE
Styles are not being applied if FormField is wrapped by a custom component

### ISSUE THREAD

**Issue by dev054** [angular/components#6963]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Styles like errors should be applied.

#### What is the current behavior?
No styles are being applied.

#### What are the steps to reproduce?
1 - Click on input and then click outside.
2 - No styles are applied to the input, like red placeholder and others.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/Y4bkpFX7Wu6VpITnsL5z?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.1
node: 8.1.1
os: linux x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.0
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.5.2
```

**Comment by willshowell** [comment]
Your "password has required error" is looking at the whole group, not the specific field:

https://plnkr.co/edit/q66PYiW71CddKKAL351M?p=preview

The control doesn't get the error set to it, so maybe your control value accessor implementation is missing something?

**Comment by dev054** [comment]
Thanks @willshowell for commenting.

Well, the original plunker is correct. The path can be specified either in `getError` and `hasError` _methods_, like this:

`this.formGroup.hasError('required', 'password')`
`this.formGroup.getError('required', 'password')`

to avoid this ugly (IHMO) thing:
`this.formGroup.get('password').hasError('required')`.

The control value accessor isn't missing nothing, you just copied the `DefaultValueAccessor`. In fact, I can either extends the `DefaultValueAccessor`  and don't implement nothing.

**Comment by willshowell** [comment]
Ah yep, my bad.

Looks like this is relevant

https://github.com/angular/material2/blob/f2cae6e8141c90fa0b62dc8a928f217bc085667b/src/lib/input/input.ts#L187-L198

And here is a hacky way around it

https://plnkr.co/edit/DiQq9z0d08di1lb55oYg?p=preview (workaround from [here](https://stackoverflow.com/questions/37781687/how-do-you-get-access-to-the-ngcontrol-from-a-controlvalueaccessor))

**Comment by dev054** [comment]
Hey thanks, it works. So, is it intended to work like this? I mean the styles in `MdFormField` are only applied if and only if there's an input WITH a `NgControl` associated.

**Comment by willshowell** [comment]
I'm not sure. @mmalerba what do you think?

**Comment by mmalerba** [comment]
I think we should try to make this work for `formControlName` too, @kara any ideas?

**Comment by crisbeto** [comment]
Closing since this hasn't had any activity in a long time and the component has been rewritten since then.
