### ISSUE TITLE
Styles in single component are not applied

### ISSUE THREAD

**Issue by mduerr18** [angular/components#7145]
Hi guys,

my problem is following:

![image](https://user-images.githubusercontent.com/32063851/30541284-ffdffbb0-9c7a-11e7-828f-e7197611eb92.png)

as you see my navbar has the background color red, so I styled my md-input in the navbar white. I defined those styles in my styles.scss, where I overwrite the styles of a prebuilt theme.

**styles.scss:**
![image](https://user-images.githubusercontent.com/32063851/30541594-6929287a-9c7c-11e7-99d7-bb5efd3bbca5.png)

Inside of the component you can see under the navbar, I want to overwrite the styles of the md-input because the background-color there is white and so you can´t even see the md-input. In the following screenshot you can see the stylesheet of the component:

![image](https://user-images.githubusercontent.com/32063851/30541940-aa812362-9c7d-11e7-8d82-4e4e68daa0cc.png)

these styles does not overwrite styles for my component. I also tried the single encapsulation types of angular 2, didn´t work either and I also tried the "/deep/" in my scss but this overwrites also the global styles.

thank you for your help,

kind regards,

Mario

**Comment by jelbourn** [comment]
While the spec doesn't every really make this super explicit, the kind of input you'd put in a toolbar like that is a [variant called a "solo field"](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations). It doesn't have a floating label, errors, or hints (though it can have prefix/suffix). Based on how different they are, I consider this to be a totally separate component from out existing input (the form-field style).

**Comment by mduerr18** [comment]
Thank you guys for your answers,

@jelbourn do you know a good tutorial where they show how to create a solo field with angular material 2

**Comment by jelbourn** [comment]
Closing this since we don't intend to build this variant of text input (since there' not much to it- you can just use a native input)
