### ISSUE TITLE
Sidenav goes into bad state when window is resized wide -> narrow -> wide rapidly

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#7177]
Navigate to https://material.angular.io/components/sidenav/overview

Rapidly resize the window from wide to narrow and back to wide. The sidenav stays closed but the drawer trigger is gone.

![image](https://user-images.githubusercontent.com/22898577/30607857-5b28f8b8-9d2b-11e7-9b2e-9f86f9f70d43.png)

Note - disabling animations fixes this (using browser-noop)

**Comment by SolidOtacon** [comment]
This is driving me crazy. I think it has to do with the fact that the animation is uninterruptible, so if the sidenav is closing and opened changes to true it gets ignored.

**Comment by jelbourn** [comment]
Appears to be fixed with the current version of the site
