### ISSUE TITLE
Enhance Docs for multiple themes

### ISSUE THREAD

**Issue by mbeckenbach** [angular/components#7196]
#### Bug, feature request, or proposal:
There should be some more guide on apps that have multiple themes regarding performance. There should be a guide on how to lazy load custom themes. I guess this would require some additional configuration for angular cli projects to have several theme files without including those hard in source.

#### What is the expected behavior?
Custom themes should only be downloaded when used.

#### What is the current behavior?
When creating multiple custom themes like shown in the guide, all themes will get downloaded at application start. When following the guide, you get a huge theme file, which is loaded at application start as it is referenced by angular cli.

#### What are the steps to reproduce?
Follow the theming guide and create multiple themes.

#### What is the use-case or motivation for changing an existing behavior?
I have an application that has about 20 themes, which is a requirement by the customer. (Wierd, i know)
I also have the requirement that a user can create a color scheme at runtime and save it for later use.

The first requirement can be solved by following the theming guide but produces quite a heavy initial page load size. For the second one I dont have a solution yet. Guess it will end up in some kind of server side scss compiler.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
4.3.x, beta 10

#### Is there anything else we should know?
It's way to hard to create color palettes. There are some generators out there, but it would be great to have an official generator.

**Comment by jelbourn** [comment]
Swapping themes really boils down to just switching the `<link>` `href` that points to the css file. Everything else is going to be specific to your application.

**Comment by willshowell** [comment]
@mbeckenbach for your first requirement (20 themes), you may need to step away from the cli and compile the sass yourself. That will give you 20 different theme files which you can swap out like @jelbourn mentioned. 

You'd probably be interested in the doc site's color picker

https://github.com/angular/material.angular.io/blob/master/src/app/shared/theme-picker/theme-picker.ts

And, more specifically, the style manager that swaps out the themes at runtime

https://github.com/angular/material.angular.io/blob/master/src/app/shared/style-manager/style-manager.ts

When you get to the runtime theme generation, please report back your findings! 😄

**Comment by julianobrasil** [comment]
Sometimes you get so immersed in angular ecosystem that it is easy to forget that after all it's nothing but the old regular javascript.

**Comment by mbeckenbach** [comment]
@willshowell 
Those links will be very helpfull. Thank you very much.
Compiling the themes outside of cli looks like the beast aproach for me at the moment.

At the moment I am really thinking about creating a very simple node web api to compile scss files on the fly, save the result to disk and return a link to the compiled css. But as I am a .net guy this should take some time to find out how things work in nodejs. Running nodejs from asp.net feels kind of wrong. :-)

@julianobrasil 
I totally agree. We have some team members that come from classic c# development and are new to the javascript world and they have to use typescript withing the angular cli. It's hard for them to realize, whats going on behind the szenes. Especially that objects could look different from what the typescript definition tells you.

**Comment by sryzycki** [comment]
@mbeckenbach I'm currently working on a product based on Angular CLI that also has the similar challenge: spin up multiple apps where each one needs to have a different theme and language.

Because of the official guide suggesting compiling the app using AOT to get the translated messages in, I've been thinking that the theme metadata also needs to be precompiled at the same time.

Any tips, discoveries that you could share?

**Comment by mbeckenbach** [comment]
@sryzycki 
I did not have the chance to dig into this within the last days.
As soon as I know more, I will share it.

**Comment by Rodrigo54** [comment]
The Angular CLI provides a lazy loading way for style files as we see referenced in [stories-global-styles](https://github.com/angular/angular-cli/wiki/stories-global-styles).

I would like to know if there is any strategy that takes advantage of the angular cli own to do the build of the themes, without having to do a build part as we see here in [material.angular.io](https://github.com/angular/material.angular.io/blob/master/tools/build-themes.sh)

Thank you for the excellent work you have done.
ps: sorry for my bad english

**Comment by jelbourn** [comment]
Closing this since the recent theming docs rewrite with Angular v12 adds more information on this topic:
https://material.angular.io/guide/theming#defining-multiple-themes
