### ISSUE TITLE
MatSelect: Long options are truncated

### ISSUE THREAD

**Issue by jermowery** [angular/components#7211]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Options should wrap or be shown in some way that does not hide the option text from the user.

#### What is the current behavior?
Long option text is truncated.

#### What are the steps to reproduce?

http://plnkr.co/edit/X8JZAatPpRD6RBSRgT7K?p=preview

#### What is the use-case or motivation for changing an existing behavior?

Text can be long in options, the user should not have the option text hidden from them.
For translated text that is longer than the source text this can happen more frequently.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by fxck** [comment]
related https://github.com/angular/material2/issues/3883

**Comment by dixy** [comment]
In a select in multiple selection mode, the option text is entirely hidden for long options on at least Firefox and IE 11.

![firefox-56](https://user-images.githubusercontent.com/1023798/31666042-21844276-b34b-11e7-9948-28b62e5a9ff7.jpg)
Firefox 56

![chrome-61](https://user-images.githubusercontent.com/1023798/31666048-298ded5a-b34b-11e7-93b6-da26db2d3764.jpg)
Chrome 61 is almost good (two dots hidden)

**Comment by crisbeto** [comment]
That is a separate issue from the one being discussed here @dixy, but thanks for the report. It should be fixed by #7857.

**Comment by UncleJimmy** [comment]
I want to add a tooltip on this "mat-option-text" as workaround, is there any way we could know the text is truncated or not?

**Comment by srix55** [comment]
Any way we can stop the truncate and allow the text to take the next line?

**Comment by Hydhen** [comment]
@UncleJimmy I've seen this workaround :
```
function isEllipsisActive(e) {
     return (e.offsetWidth < e.scrollWidth);
}
```
From this [link](https://stackoverflow.com/questions/7738117/html-text-overflow-ellipsis-detection)

But I didn't succeeded on getting the propeties from an element node, i'm stuck to this point : 

 ```
@ViewChild('select') select: MatSelect;
this.select.options.forEach((option: MatOption) => {
      console.log(option._getHostElement().childNodes[1]); // Gives the span element
});
```

**Comment by Hydhen** [comment]
Just find out you can do this :

```
<mat-option *ngFor="let obj of objs" [value]="obj.Code" matTooltip="{{ obj.Value }}" matTooltipPosition="before" matTooltipDisabled="{{ obj.Value.length < 25 }}">
                            {{ obj.Value }}
</mat-option>
```

It works well, but it evaluates according to the number of caracters and not if the text is ellipsed or not

**Comment by jelbourn** [comment]
The MDC-based version of `MatSelect` wraps option text:
https://stackblitz.com/edit/angular-mdc-issue-md2tzg?file=src%2Fapp%2Fexample-component.html

This is in material-experimental now and will eventually replace the existing `MatSelect`

**Comment by adityakmehta** [comment]
Hi.. was anyone able to find solution to [Resizing the mat-option with height and line-height for the mat-autocomplete alters the autocomplete keyboard scrolling #10038](https://github.com/angular/components/issues/10038#) ?

**Comment by oleg-golota** [comment]
I also need this bug https://github.com/angular/components/issues/10038# to be fixed. I wonder why it was closed?

**Comment by Totati** [comment]
It was marked as [duplicate](https://github.com/angular/components/issues/10038#issuecomment-367066290).

**Comment by amysorto** [comment]
Text wraps instead of truncating in the MDC based select component coming soon in v15, I am closing this bug.
