### ISSUE TITLE
Datepicker: more clearly document the fact that DateAdapter needs to completely new instances

### ISSUE THREAD

**Issue by mortenamby** [angular/components#7224]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When defining a custom date adapter the next/previous button in the datepicker popup should switch the displayed month.

#### What is the current behavior?
The next/previous buttons do not change the displayed month, only the month in the dropdown selector.

#### What are the steps to reproduce?

1. Create any custom date adapter and date formats to use with the datepicker.
2. Open the datepicker.
3. Click next or previous.
4. The displayed month does not change.

Plunker that illustrates the issue: http://plnkr.co/edit/BjhtN1PT9RAtzvKCcN3H?p=preview

#### What is the use-case or motivation for changing an existing behavior?
As it is a bug fix the buttons should work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: 2.0.0-beta.10
@angular/cdk: 2.0.0-beta.10
@angular/core: 4.4.3,

**Comment by donroyco** [comment]
The provided Plunker seems to be working fine for me.

**Comment by mortenamby** [comment]
Perhaps I was not clear enough.

If you look at the below screenshot, I have switched the month (to May as indicated by the selector in the top) by clicking the arrow buttons, however the displayed month is February. When not using a custom date adapter, the month switches correctly.
![datepicker_bug](https://user-images.githubusercontent.com/7424333/30698914-95b0c290-9ee3-11e7-9117-4f27b992aa8a.jpg)

**Comment by ghd8** [comment]
In your custom DateAdapter  you have to clone the date object for all "addCalendar*" methods,
then the month will be displayed correctly.

e.g.
```typescript
  addCalendarMonths (date: Moment, months: number): Moment {
    return  this.clone(date).add(months, "M");
  }
```

**Comment by mortenamby** [comment]
@ghd8 
Yep. That seems to fix it.
It does indeed say it should return a **new** date based on the given one if you look in the DateAdapter abstract functions. It should however be a little more clear that it expects a new instance.

So basically it can be narrowed down to improving the documentation of the DateAdapter which is scarce as it is.

**Comment by jelbourn** [comment]
Closing this since it doesn't seem to be a common issue that people encounter.
