### ISSUE TITLE
Input label flashes color when clicking an autocomplete option

### ISSUE THREAD

**Issue by jelbourn** [angular/components#7311]
https://material.angular.io/components/autocomplete/examples
* Focus the input
* Keep your eye on the label
* Click an option

Notice that the label very quickly flashes from primary color, to default color, to primary color.

(easier to see on a dark theme)

**Comment by donroyco** [comment]
Here's the behaviour in a GIF.

![autocomplete-flash](https://user-images.githubusercontent.com/1763537/30846026-3c6ca936-a296-11e7-8c12-de163281cfc1.gif)

**Comment by crisbeto** [comment]
Closing this since there hasn't been any activity in a long time and we can't do much about it, because the browser moves focus on `mousedown`, hence why the input briefly becomes blurred. We could delay the blurring, but that'll break a lot of tests for users.
