### ISSUE TITLE
Slider, thumb goes out of sync with track when updated rapidly

### ISSUE THREAD

**Issue by michaelbromley** [angular/components#7366]
#### Bug, feature request, or proposal:

Bug: When the value of an `<md-slider>` is rapidly updated (e.g. via a setTimeout or requestAnimationFrame), the track indicator correctly and smoothly updates, whereas the thumb lags behind and only updates its position in a jerky fashion.

![2017-09-27_21-21-44](https://user-images.githubusercontent.com/6275952/30933151-fb9b21a0-a3c9-11e7-8e3b-26531e3c6a77.gif)

#### What is the expected behavior?

The thumb moves smoothly as at value changes.

#### What is the current behavior?

It either stays in the same position or only moves when another even is occurring, e.g. the mouse is moved.

#### What are the steps to reproduce?

http://plnkr.co/edit/3EfZsHIFHRgnEHO79qdg?p=preview

```HTML
 <md-slider [value]="value" min="0" max="1000"></md-slider>
```

```TypeScript
    const tick = () => {
      this.value ++;
      if (this.running) {
        setTimeout(tick, 25);
      }
    };
    
    this.running = true;
    tick();
```
#### What is the use-case or motivation for changing an existing behavior?

I am building an app where I want to use the slider as a "scrub" control for an animation.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome 61
Angular 4.2.4
Material 2.0.0-beta.11
TypeScript 2.3.3

#### Is there anything else we should know?

Nope

**Comment by aastrouski** [comment]
@josephperrott
Hello!
This issue is still reproduced for Angular/Material 6.
Any plans to fix it?

We want to use Slider for Player component, but this bug stops our work(.

**Comment by adamk33n3r** [comment]
Unfortunately removing transitions isn't an acceptable "fix" in my case. I was able to get a smoothly sliding thumb by setting the interval to 100ms but that's slower than I'd like.

**Comment by jelbourn** [comment]
Confirmed that this is fixed in the new MDC-based slider (currently in `@angular/material-experimental`)

**Comment by amysorto** [comment]
I tested this with the MDC based slider which is available in v15, and it worked correctly. It is also working for the current components in v14.
