### ISSUE TITLE
mat-input DOM order of label and input

### ISSUE THREAD

**Issue by bsteffl** [angular/components#7402]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
It would be ideal if the label came before the input in the DOM order for the mat-input. Useful for adding your own custom styles if you want the functionality default look of inputs. This would also be useful if CSS were disabled.

#### What is the current behavior?
Label comes after input, however it has the appropriate aria labels and markup to associate the label with the input.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>  

*DOM order*  
![image](https://user-images.githubusercontent.com/10760551/30996072-91aa478e-a483-11e7-90e7-0a8e5ab1a080.png)   

*CSS disabled*  
![image](https://user-images.githubusercontent.com/10760551/30996156-2c42d2f2-a484-11e7-97d1-4ceeef2df756.png)  

#### What is the use-case or motivation for changing an existing behavior?
For applying custom styling to make form fields look like traditional inputs can cause complications when DOM order is flipped. Also useful if CSS was disabled.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 2.0.0-beta.11

**Comment by crisbeto** [comment]
For reference, the reason for this DOM order is to allow us to use the autofill selectors to float the label when the input has been pre-filled by the browser.

**Comment by bsteffl** [comment]
@crisbeto I haven't looked at the details of the styling for floating the label, but I'm guessing it's not something resolved by flexbox and order?

**Comment by crisbeto** [comment]
It's not. [If you look at this](https://github.com/angular/material2/blob/master/src/lib/form-field/form-field.scss#L128), the selector depends on the input coming before the label in the DOM order.

**Comment by crisbeto** [comment]
We're in the process of cleaning up our issue backlog. I'm closing this issue, because there hasn't been any activity in a long time and the current DOM structure is intentional.
