### ISSUE TITLE
[Tooltip] Cannot use fixed position in IE

### ISSUE THREAD

**Issue by dereklin** [angular/components#7538]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
tooltip with fixed position should work in IE, like in Chrome

#### What is the current behavior?
tooltip is not displayed in IE 11

#### What are the steps to reproduce?

https://plnkr.co/edit/CwWB1uxM1GgTNMafxNyw?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Normal tooltip feature.  Want to control the placement of the tooltip.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest versions from the current tooltip example in plunker

#### Is there anything else we should know?
It's not working in IE Edge either

**Comment by jelbourn** [comment]
I just tried the latest version on IE11 and the positioning seems to work correctly as far as I can tell in all cases. Feel free to open a new issue if there's a reproduction with v11+
