### ISSUE TITLE
Please add a guide for gestures

### ISSUE THREAD

**Issue by HarelM** [angular/components#7577]
#### proposal
I wanted to support swiping on an image array to create an accordion kinda of control.
material has a `GestureConfig` provider that is very well written and wrappers hammerjs.
A short guide in the material.angular.io site on how to use or configure it would help a lot.

#### What is the use-case or motivation for changing an existing behavior?
So that people would not have to dig into the code and be able to use an API for gestures that is tested and well defined.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest.

**Comment by crisbeto** [comment]
The `GestureConfig` hasn't been in use for a while now and is being removed completely either in v10 or v11.
