### ISSUE TITLE
[Tabs] MdTabs, MdExpansionPanel - overflow hidden for content crops radio/icon button ripples

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/components#7616]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Overflow hidden is applied to content when it's hidden or getting hidden/shown (during animation) only.

#### What is the current behavior?
Overflow hidden applied to content when it's shown as well.

#### What is the use-case or motivation for changing an existing behavior?
Things like radio/icon button ripples get cropped inside tab/expansion-panel content.

**Comment by mmalerba** [comment]
Looks like this has been resolved by #7617
