### ISSUE TITLE
[Accessibility] Add aria-labelledby to MatDialogConfig API 

### ISSUE THREAD

**Issue by opozo** [angular/components#7755]
#### Bug, feature request, or proposal:

Add aria-labelledby to MatDialogConfig API. [MatDialogConfig API](https://material.angular.io/components/dialog/api) supports aria-describedby, but it doesn't support aria-labelledby.

Check MDN documentation for an example: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

#### What is the expected behavior?

Screen reader should read dialog label from aria-labelledby attribute.

#### What is the current behavior?

Screen reader is not reading dialog label.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/material": "2.0.0-beta.12"

**Comment by glenngr** [comment]
Looks like this was fixed in #6558

**Comment by kwiniarski97** [comment]
@glenngr Aria labelledBy wasn't added to dialog config in that PR however I see than in newest angular version it is added. 
See file: https://github.com/angular/components/blob/master/src/material/dialog/dialog-config.ts
