### ISSUE TITLE
[Table] Show examples using multiple features

### ISSUE THREAD

**Issue by theunreal** [angular/components#7824]
#### Bug, feature request, or proposal:
Proposal

Add an example to the Angular Material docs about how to use different types of the data table features together:

Examples that can be given:
- Table with filtering & sorting
- Table with Paginator & Sorting

Currently it's not obvious how to change the connect() method to implement multiple data table features.

**Comment by jelbourn** [comment]
https://material.angular.io/components/table/examples#table-overview now exists with pagination, sorting, and filtering
