### ISSUE TITLE
[MatToolbar] Add provider to let users configure the default color

### ISSUE THREAD

**Issue by the-ult** [angular/components#7870]
#### Bug, feature request, or proposal:
Add global configuration for the `mat-toolbar` to set the default color through a provider

#### What is the expected behavior?
To be able to give the `mat-toolbar` a darker color, like the material design guides suggest.

#### What is the current behavior?
A toolbar can only have `no color`, `primary`, 'warn` or `accent`. And you'll have to override the css to use the `primary-dark` color.

#### Is there anything else we should know?
see: #7679

**Comment by jelbourn** [comment]
Closing this since we don't plan any really expanding mat-toolbar with further features at this point. We may eventually create a new app-bar component that supersedes the toolbar, but have no immediate plans for it.
