### ISSUE TITLE
Allow HammerJS to be lazy-loaded

### ISSUE THREAD

**Issue by yueluog** [angular/components#7905]
We divide our large web app into different modules and load most modules on demand. We have a core/bootstrapping module that is needed by every page. 

Some component behavior in Angular Material like mat-slider requires HammerJS to work. Angular HammerGesturesPlugin is created very early, so it needs to be in the core module. HammerGesturesPlugin constructor requires the injection of Angular Material GestureConfig. So GestureConfig needs to be in core module. GestureConfig checks for the existence of HammerJS at the construction time: https://github.com/angular/material2/blob/master/src/lib/core/gestures/gesture-config.ts#L16. As a result, HammerJS must be loaded before or as part of our core module.

We want to keep our core module as small as possible. Since not many pages of our app use mat-slider, could you construct the code in such a way that HammerJS is only needed when the page requires it?

This may require some change to Angular code. One option seems to be letting HammerGesturesPlugin delegate "support" function to GestureConfig.

**Comment by jelbourn** [comment]
See https://material.angular.io/components/datepicker/overview#internationalization

**Comment by jelbourn** [comment]
For now there's nothing we can do about this in Angular Material specifically since Angular itself doesn't support lazy-loading event plugins. Filed https://github.com/angular/angular/issues/19874 to track.

**Comment by yueluog** [comment]
Thanks Jeremy for opening a bug for Angular fix. 

Changing Angular framework to support lazy-loading event plugins is probably a complex and long term work. For this specific issue, there may be an easier fix. 
Add a "supports" function to HammerGesutreConfig class in Angular, and let HammerGesturesPlugin.supports function delegate the check to HammerGestureConfig.supports function. Then Angular Material GestureConfig can override "supports" function and check for HammerJS only when "supports" is called (instead of doing HammerJS check at construction time).

Do you think that this is a reasonable short-term work to do? (The complication is how to maintain backward compatibility.)

**Comment by jelbourn** [comment]
I'm not sure that would work; the Angular Material that use gestures rely on the event plugin being installed. If you don't get the error about HammerJS being absent, the components could silently fail.

**Comment by yueluog** [comment]
Could you clarify the exact concern?
We want to avoid having HammerJS loaded as part of bootstrapping (or core) module. It is ok to load Angular Material GestureConfig class in our core module. 
Today, if we do not load HammerJS as part of the core module, I think we will get silent failure other than the warning log from constructor of GestureConfig. In the proposal, the warning log can be moved to "GestureConfig.supports" function, so we can still get the warning log in dev mode.

**Comment by jelbourn** [comment]
I think I see what you mean; effectively making the event plugin no-op until Hammer is loaded

**Comment by yueluog** [comment]
Yes. Thank you Jeremy.

**Comment by yueluog** [comment]
Hi Jeremy, I haven't followed Angular Material interaction with HammerJS for a while. Was there any change in Angular Material that would make this bug obsolete now?

**Comment by jelbourn** [comment]
No updates on this

**Comment by caisq** [comment]
+1 to this feature request.

**Comment by jelbourn** [comment]
As of Angular v9, HammerJS is no longer a dependency of Angular Material.
