### ISSUE TITLE
how to prevent md-select focusing option by typing

### ISSUE THREAD

**Issue by we125182** [angular/components#7917]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
md-select can not focus on item by typing.(ps: of course if it can focus on item by multi typings will be nice)

#### What is the current behavior?
when i click the md-select and typing a letter, it focus the item which is start with the typing letter.
for example, if i typing 'A', it focus 'Apple', but continue typing 'P'. it focus on 'Piano'. I hope it still focus
'Apple' or don't focus item by typings.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.3.1
material 2.0.0-beta.10
typescript 2.4.2
browser google chrome

**Comment by willshowell** [comment]
IIRC it is like this to match native select behavior

**Comment by crisbeto** [comment]
This is an accessibility feature that is intended to match the native `select`. The keypresses are debounced so it only goes to "Piano" if you press "P" 200ms or more after you pressed "A".

**Comment by we125182** [comment]
thank you all for your answers. and i want to know there is anyway to prevent this feature? @crisbeto @willshowell

**Comment by jelbourn** [comment]
Closing this issue since we don't have any plans to support disabling typeahead since this is an important accessibility feature.
