### ISSUE TITLE
Dev Tools causing performance issues with MdSelect

### ISSUE THREAD

**Issue by rkajbaf** [angular/components#8157]
#### Bug, feature request, or proposal:
REQUEST, maybe BUG

#### What is the expected behavior?
When using MdSelect with dev tools open, render should be closer to the speed for when dev tools are closed.

#### What is the current behavior?
With dev tools open, loading a select takes about 4 to 5 times longer for a list of 2000 items than with dev tools closed.  As the list grows, the length of time increases proportionally.

For large lists, this makes development very cumbersome.  The native select does not have this issue.  The manner in which the app is built does not matter, AOT and JIT exhibit the same behavior.   I think some slow down is to be expected, but 5x seems like a lot.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>

https://angular-material2-issue-3e9zci.stackblitz.io

Test with dev tools open and closed and notice how long it takes to load the mdselect list.  Do the same test with the native select.  You will notice that the MdSelect slows down much more than the native select.

#### What is the use-case or motivation for changing an existing behavior?

Faster development. It's slow and locks up the screen regardless but its bearable with dev tools closed, but that makes development much more difficult.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "^4.4.6",
"@angular/material": "^2.0.0-beta.12",
"typescript": "~2.3.3",

Tested with Edge & Chrome 61 on Windows 10

**Comment by tytskyi** [comment]
@rkajbaf 

1. You have angular change detection error in app (ExpressinChanged....)
2. I think performance is weak due to around 4000 log into devtools console (event if they are filtered out and not visible) - `[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event ...`

**Comment by d3viant0ne** [comment]
@tytskyi - The latter has a PR already thankfully. The `touchstart` issue was resolved for a while & is back in `5.0.0` & definitely has an adverse effect on performance.

**Comment by crisbeto** [comment]
The issue with a `touchstart` warning being logged has been resolved for a long time now. Closing.
