### ISSUE TITLE
How do you clear an autocomplete manually?

### ISSUE THREAD

**Issue by mendor1990** [angular/components#8214]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Actually have the same problem which is reproduced in this example
https://stackblitz.com/edit/angular-material2-issue-v5gpri?file=app%2Ftag.component.html
I using an autocomplete chips component. Try to put some letter in input and select one of the values. Note that input not clearing. I trying to reset this value manually and nothing helps.

<img width="508" alt="2017-11-03 16 51 01" src="https://user-images.githubusercontent.com/9025523/32379809-37bc0d98-c0b7-11e7-89af-22cf57bb1553.png">

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome, MacOS Sierra 10.12.6
Angular ^4.4.6
@angular/material ^2.0.0-beta.12

**Comment by We-St** [comment]
I'm not sure why this would be set to such a low priority. Through this bug, you cannot combine chip input with autocompletes :/

**Comment by james-schwartzkopf** [comment]
@We-St You can work around the issue by changing:
`  (optionSelected)="add($event)"`
To:
`(optionSelected)="add($event); chipInput.value = ''"`

**Comment by james-schwartzkopf** [comment]
After a bit of playing around I was able to get it working, however there does appear to be an issue where the formControl setValue is not updating the value displayed in the control:
https://stackblitz.com/edit/angular-material2-issue-wmgcaj

I was able to work around this by using both formControl.setVaue and input.value so both view and model were in sync.

**Comment by gryole** [comment]
Faced the same problem. After little investigation of source code, found that `MatAutocompleteTrigger` [saves](https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete-trigger.ts#L408) previous value.
Setting empty value and dispatching "input" event worked for me:
```
input.value = '';
input.dispatchEvent(new Event('input', {
      'bubbles': true,
      'cancelable': true,
    }));
```

**Comment by jelbourn** [comment]
Revisiting old bugs- I think this one is obsolete. We have an example of this in our docs: https://material.angular.io/components/chips/examples#chips-autocomplete
