### ISSUE TITLE
Fully dynamic plunkr example for data table sorting

### ISSUE THREAD

**Issue by GregKass** [angular/components#8255]
#### Bug, feature request, or proposal:
proposal?

#### What is the expected behavior?
would be nice to have a fully dynamic plunkr example

#### What is the current behavior?
current examples only use static templates

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
[dynamic plunkr example](https://plnkr.co/edit/sg4zdOr1fXnlymX1rQmu?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
I was originally developing a plunkr when I first thought there may be a material bug working with ngSwitch. I resolved the issue and ended up with a working example of a sorting material data table using a fully dynamic template. It would be nice to have a dynamic example for the purposes of demonstrating working with dynamic data, and I didn't want to let my good plunkr go to waste.

#### Is there anything else we should know?

EDIT: plunkr is updated and working again, atm

**Comment by Misiu** [comment]
@GregKass Your plunkr isn't working anymore. I get this error every time I try to open it.

> Error: (SystemJS) XHR error (404) loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/layout
> 	Error: XHR error (404) loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/layout
> 	    at new k (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:12526)
> 	    at XMLHttpRequest.t [as __zone_symbol___onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:881)
> 	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:20606)
> 	    at t.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:15783)
> 	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:21563)
> 	Error loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/layout as "@angular/cdk/layout" from https://unpkg.com/@angular/material/bundles/material.umd.js
> 	    at new k (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:12526)
> 	    at XMLHttpRequest.t [as __zone_symbol___onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:881)
> 	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:20606)
> 	    at t.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:15783)
> 	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.5/zone.min.js:1:21563)
> 	Error loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/layout as "@angular/cdk/layout" from https://unpkg.com/@angular/material/bundles/material.umd.js

**Comment by raunakmatai** [comment]
Getting same error.

**Comment by GregKass** [comment]
I'm getting the same error from the original sorting table plunkr from which I based mine, linked from the material component page sorting example.

**Comment by GregKass** [comment]
I've updated my plunkr link above to get this working again. 

```systemjs.config.js``` needed updates

Here's an example of the original sorting table with the same ```systemjs.config.js``` changes applied to get it working again:

[materials sorting plunkr example](https://plnkr.co/edit/AVeUu5xiwt4tZayv8MP5?p=preview)

**Comment by crisbeto** [comment]
There are several examples of the table using dynamic sorting on the docs site now: https://material.angular.io/components/table/examples
