### ISSUE TITLE
MultiPortalHost

### ISSUE THREAD

**Issue by devlfm** [angular/components#8273]
Feature request:
Allow more than one Portal inside the PortalHost

#### What is the expected behavior?
More than one Portal inside the PortalHost, or maybe a new MultiPortalHost

#### What is the current behavior?
Only accepts one

#### What is the use-case or motivation for changing an existing behavior?
explained here #8254 and the "solution" would be the Portal be an empty div..

**Comment by josephperrott** [comment]
I am going to go ahead and mark this as a feature request, however it is very unlikely we will implement this without a use case for it that demonstrates a large need for multiple instances and use cases.

**Comment by devlfm** [comment]
Imagine a page-builder for newsletters or a drawing-canvas, and you have an OverlayRef and a Portal for the handles..  First you hit the problem that one Portal can only host one ComponentRef, then you hit the second wall if you want to add other overlay stuff like guides (that should have their own Portal too). Anyway I ended up using another OverlayRef, but it feels a lot of boiler code..
