### ISSUE TITLE
[cdk] indicate in docs which utilities operate outside NgZone

### ISSUE THREAD

**Issue by willshowell** [angular/components#8279]
#### Bug, feature request, or proposal:
Docs request

#### Current behavior
It takes a little extra digging in the source to understand `ScrollDispatcher#scrolled` and `ViewportRuler#change` emit outside the zone.

#### Expected behavior
A note in the jsdoc of these properties and methods.

**Comment by josephperrott** [comment]
This definitely seems like something that could be good to have in docs.  Though it will definitely take some designing as to how to surface it, as well as seeing if we could use something like linting to be sure that we always note `ngZone` usage.  Worse than not documenting it, imo would be to have it inconsistently documented.

**Comment by willshowell** [comment]
Agreed. Not having to hunt for the information would be good. Perhaps a prominent accent label.

A complication of a linter solution is that some utilities don't explicitly run outside of the zone, but can be called by another that does. For example, `onPositionChange`

https://github.com/angular/material2/blob/c13848e715c8940de3fb923e0a69ba42e67bbcb3/src/cdk/overlay/position/connected-position-strategy.ts#L74-L77

The subject is usually advanced by [`apply()`](https://github.com/angular/material2/blob/c13848e715c8940de3fb923e0a69ba42e67bbcb3/src/cdk/overlay/position/connected-position-strategy.ts#L111-L157), which is called by [`updatePosition()`](https://github.com/angular/material2/blob/c13848e715c8940de3fb923e0a69ba42e67bbcb3/src/cdk/overlay/overlay-ref.ts#L198-L203) which is sometimes called within but usually [outside](https://github.com/angular/material2/blob/c13848e715c8940de3fb923e0a69ba42e67bbcb3/src/cdk/overlay/scroll/reposition-scroll-strategy.ts#L46-L48) the [zone](https://github.com/angular/material2/blob/c13848e715c8940de3fb923e0a69ba42e67bbcb3/src/cdk/scrolling/scroll-dispatcher.ts#L144-L148).

**Comment by saulotoledo** [comment]
@jelbourn I think one could add the "has pr" label to this issue.

**Comment by jelbourn** [comment]
The PR here was merged; it added a note to the API docs for `ScrollDispatcher`, but not for `ViewportRuler`
