### ISSUE TITLE
Implement Alternative labels in Stepper component

### ISSUE THREAD

**Issue by demisx** [angular/components#8365]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Add an ability to display labels below step number. See the "Alternative labels" section on https://material.io/guidelines/components/steppers.html#steppers-types-of-steppers

#### What is the current behavior?
Apparently, placing labels under step numbers is not currently supported in Angular Material. At least, I didn't find anything in the docs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 2+, All browsers

**Comment by ahaan729** [comment]
Do we have any update on this or any temporary fix to make it work.
I want to place the labels below the step number.

**Comment by Philip-Sultanescu** [comment]
Here is my workaround: 

- on xs devices I hide the labels as they don't fit anyways
![screen shot 2018-01-08 at 15 38 06](https://user-images.githubusercontent.com/30979663/34675510-26c2c75a-f48a-11e7-8542-571ba27247e9.png)

- on sm devices I did my best to follow the official guidelines.
![screen shot 2018-01-08 at 15 38 56](https://user-images.githubusercontent.com/30979663/34675537-363e2346-f48a-11e7-8c9b-b5e495976fc4.png)

I couldn't figure out how to to make the lines in between go 8px right next to the icons, any contributions are welcome.

Also I didn't do anything for optional labels.
```
@media (max-width: 479px) {
  .mat-horizontal-stepper-header .mat-step-icon, .mat-horizontal-stepper-header .mat-step-icon-not-touched {
    margin-right: 0 !important;
  }
  .mat-step-label {
    display: none !important;
  }
}

@media (min-width: 480px) and (max-width: 767px) {
  .mat-stepper-horizontal {
    padding-left: 8px;
    padding-right: 8px;
  }
  .mat-horizontal-stepper-header {
    flex-direction: column;
    flex: 1;
    height: 104px !important;
    padding-left: 16px !important;
    padding-right: 16px !important;
  }
  .mat-horizontal-stepper-header .mat-step-icon, 
  .mat-horizontal-stepper-header .mat-step-icon-not-touched {
    margin-top: 24px;
    margin-right: 0 !important;
  }
  .mat-step-label {
    margin-top: 16px;
    width: 100%;
  }
  .mat-step-text-label {
    text-align: center;
  }
  .mat-stepper-horizontal-line {
    margin-top: -32px !important;
    max-width: 32px;
  }
}
```

**Comment by rahul2270** [comment]
@philip-firstorder-io : Can you share you html file for the same?

**Comment by tiagoseminotti** [comment]
@philip-firstorder You can use negative margins to bring the horizontal line closer to where you want them.

.mat-stepper-horizontal-line {
  border-top-width: 2px !important;
  margin: -38px -60px 0 -60px !important;
}

![image](https://user-images.githubusercontent.com/12500974/44029240-f9eda18e-9ed2-11e8-8d14-d6354d6a9217.png)

**Comment by lin-zy1229** [comment]
Please don't forget `::ng-deep`, e.g. 
```
::ng-deep .mat-step-header {
    border-radius: 50%;
}
```

**Comment by devversion** [comment]
We added support for this a couple of major versions ago. Closing this issue.

https://material.angular.io/components/stepper/overview#label-position
