### ISSUE TITLE
Scrollable overlays not staying attached when inside tabs

### ISSUE THREAD

**Issue by alexw10** [angular/components#8405]
#### Bug, feature request, or proposal:
Seems like this a bug unless someone can point me in a direction why what I have doesn't work.

#### What is the expected behavior?
When applying the `cdkScrollable` class I would expect the overlay to stay attached to the element

#### What is the current behavior?
Does not stay attached to the element

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Here is a StackBlitz:
https://stackblitz.com/edit/angular-material2-issue-yqzqdh

In the above I am applying the `cdkScrollable` class but it still does not seem to stay attached properly. Any ideas why? I believe I have it in the right spot which is on the element that is scrolling.
Tried it other places as well but still no luck.

#### What is the use-case or motivation for changing an existing behavior?
Would like to use overlay components inside tabs.

**Comment by willshowell** [comment]
Definitely wait for an official response, but I was able to get it to work like this,

```html
<mat-tab-group>
  <mat-tab label="Tab 1">
    <div cdkScrollable style="overflow-y: auto; height: 200px">
      <!-- ... -->
    </div>
  </mat-tab>
  <mat-tab label="Tab 2">Content 2</mat-tab>
</mat-tab-group>
```

**Comment by alexw10** [comment]
Yup, can confirm what you suggested does work @willshowell however I feel like wherever you put the cdkScrollable if that is the element that is scrolling for example my tab content is the part that is that should add it to the ScrollDispatcher and properly keep the element attached. I feel like this is still an issue will wait for official response as well. but will go with what you suggested for now @willshowell thanks! :)

**Comment by alexw10** [comment]
@crisbeto any ETA on when your PR will be merged?

**Comment by tommymonk** [comment]
Any update on this ?
