### ISSUE TITLE
Chip input placeholder wrong position

### ISSUE THREAD

**Issue by merobal** [angular/components#8505]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The cursor inside input for chips list should align with the placeholder if floatPlaceholder is set to "never".

#### What is the current behavior?
Misalignment.

#### What are the steps to reproduce?
Use `floatPlaceholder="never"` on default example.
![cursor-wrong-pos](https://user-images.githubusercontent.com/5844511/32943344-18c36a46-cb8c-11e7-813e-719855774e24.PNG)

#### What is the use-case or motivation for changing an existing behavior?
Design.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest on Plunker.

#### Is there anything else we should know?
Maybe related: #8448

**Comment by jelbourn** [comment]
@tinayuangao is this the same as #8448? If so, feel free to close

**Comment by merobal** [comment]
I marked that as related since it's about placeholder too, but the margin: 3px of the input cause this issue.

**Comment by merobal** [comment]
@jelbourn @tinayuangao I can confirm it's still an issue with rc.1:
https://plnkr.co/edit/rV9QEHQCOJYxTE6ddZ3y?p=preview

Possible fix:
https://plnkr.co/edit/s94OWYX9lIawldaUBwk1?p=preview

(Add $mat-chip-input-margin for the placeholder label when `floatPlaceholder` is set to `"never"`)

**Comment by merobal** [comment]
@tinayuangao Will https://github.com/angular/material2/pull/9762 solve this issue?
