### ISSUE TITLE
tabindex not supported on md-radio-group

### ISSUE THREAD

**Issue by tofesath** [angular/components#8553]
#### Bug, feature request, or proposal:
tabindex doesn´t work

#### What is the expected behavior?
Set focus on input and after pressed TAB, could be get focus md-radio-group with lower value of tabindex. In order second and first radio group.

#### What is the current behavior?
tabindex is ignored

#### What are the steps to reproduce?
https://plnkr.co/edit/xZNIXCXoRc8GFxUsc8qd?p=preview

#### What is the use-case or motivation for changing an existing behavior?
I want set custom order focus invoked by pressed tab

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on Angular 4.4.4, Angular/Material 2.0.0-beta.11, Chrome

**Comment by saulotoledo** [comment]
@jelbourn I think one could add the "has pr" label to this issue.

**Comment by saulotoledo** [comment]
@jelbourn I think one could add the "has pr" label to this issue.

**Comment by crisbeto** [comment]
Closing based on the discussion in https://github.com/angular/components/pull/8580 where it was decided not to add a `tabindex` on the group itself.
