### ISSUE TITLE
ComponentPortal attached to PortalHost not rendered when content is projected using *ngTemplateOutlet

### ISSUE THREAD

**Issue by glenstaes** [angular/components#8571]
#### Bug:
`ComponentPortal` attached to `PortalHost` not rendered when content is projected using `*ngTemplateOutlet`

#### What is the expected behavior?
When a `ComponentPortal` is attached to the `PortalHost` the component should be rendered within the `*ngTemplateOutlet`

#### What is the current behavior?
The component is not rendered even though the portal is successfully attached.
![2017-11-20_16-01-45](https://user-images.githubusercontent.com/8949285/33060300-146c42f6-ce98-11e7-9ce5-7d3741eeef61.png)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-di4q3k?file=app%2Fprojection.component.ts

#### What is the use-case or motivation for changing an existing behavior?
I'm building a master-detail component that renders a different component based on the subroute that is used.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v5.0.1
Angular CDK v5.0.0-rc.0

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Looking at your stackblitz, you've got a directive on `ng-content`, which isn't actually supported by the framework. `ng-content` is a compiler primitive that can't have any directives or attributes applied. If there's still some problem without that, feel free to open a new issue.
