### ISSUE TITLE
Change max and min inputs of datepicker

### ISSUE THREAD

**Issue by dev054** [angular/components#8647]
#### Bug, feature request, or proposal:
Proposal.

#### What is the expected behavior?
I'd like to proposal you to change those inputs to something like `[maxDate]` and `[minDate]`.

#### What is the current behavior?
Currently you can use `[max]` and `[min]` input's to `<input matInput> in order to refer to the validations of the `mat-datepicker` component, however you also can do it for refer to `min` and `max` validators of `@angular`. It seems really ambiguous for me.

**Comment by mmalerba** [comment]
We intentionally named the `min` and `max` inputs the same as the standard Angular ones so that developers can add validators to the datepicker input in the same way. If this is causing practical problems for you can you create an issue and explain what that problem is?
