### ISSUE TITLE
[Feature Request]: Alternative/due date marking for datepicker

### ISSUE THREAD

**Issue by httpNick** [angular/components#8690]
#### Bug, feature request, or proposal:
Feature request
#### What is the expected behavior?
Add an additional input to the datepicker that adds an alternative date which is marked on the view. (similar to how today is marked by a blue circle) in some other way (a different colored circle, an outline, etc.. not sure on this part yet).

#### What is the current behavior?
There is no option to add an alternatively marked date.

#### What is the use-case or motivation for changing an existing behavior?
Adds functionality to the datepicker which could be widely used in different business use cases (especially for things such as due dates, check out dates, release dates, etc).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Adds functionality to any future Material releases once it is deployed.

#### Is there anything else we should know?
Currently I am using a fork for the datepicker because the single largest issue is we have to have a due date circled on the calendar to indicate to the user that they have to pay their bill by a certain date (and a little custom accessibility additions). I am mainly opening this feature request because I think it could also be something other users of this component may need. Also, I wouldn't mind using the datepicker out of the box of course ;)

**Comment by fxck** [comment]
related https://github.com/angular/material2/issues/4410 ?

**Comment by crisbeto** [comment]
This is possible using the `dateClass` input. There's an example in the docs: https://material.angular.io/components/datepicker/overview#highlighting-specific-dates
