### ISSUE TITLE
[Tooltip] Bad error message when placed on non-element (ng-container)

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#8724]
When a `[matTooltip]` is placed on an `ng-container`, it is invalid but the resulting error message is unhelpful in finding out how to resolve the issue: `el.getAttribute is not a function`.

Should be able to check in the constructor if the `elementRef.nativeElement` exists and if not, a helpful error message can be provided.

**Comment by jelbourn** [comment]
Just tried with w/ the latest version and this seems to no longer throw any error message
