### ISSUE TITLE
[MatOption/MatOptgroup] - Expose docs to site

### ISSUE THREAD

**Issue by rafaelss95** [angular/components#8790]
#### Bug, feature request, or proposal:
Bug/Proposal

#### What is the expected behavior?
It'd be good to see some docs about [`MatOption`](https://github.com/angular/material2/blob/master/src/lib/core/option/option.ts)/`MatOptgroup`.

#### What is the current behavior?
There's no docs about `MatOption`/`MatOptgroup`.

**Comment by mmalerba** [comment]
They are both covered a little bit in the `mat-select` documentation: https://material.angular.io/components/select/overview but it would be good to have some additional info about using them outside the `mat-select`

**Comment by ienzam** [comment]
`MatOption` has been moved to a new file, so `MatSelect` doc doesn't contain `MatOption` documentation anymore.
Can you please add the documentation back?

**Comment by stagefright5** [comment]
How is this not a thing. Please consider this

**Comment by twalker1998** [comment]
Seconded- would love to see some MatOption documentation.

**Comment by Robouste** [comment]
Any update on this ? Without [this post on stackoverflow](https://stackoverflow.com/questions/50614991/angular-mat-select-multiple-selectionchange-finding-which-option-was-changed) about `onSelectionChange`, I would still be stuck figuring out how to deal with multi-select, to get only what the user selected

**Comment by paulazabalegui** [comment]
It's really necessary to know about the `mat-option` API. Actually I'm just researching in source code to figure out how to do certain things like listening on click event and other similar.
