### ISSUE TITLE
[Tooltip] Allow users to select text in tooltip

### ISSUE THREAD

**Issue by razorhenry1** [angular/components#8817]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
I want to copy value from tooltip which would be helpful to copy content which overflows and an ellipses is shown.

#### What is the current behavior?
If hideDelay is added, still I am unable to copy text as tooltip is shown in overlay container.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>

Please hover over version number. I need to copy data from tooltip
[Plunker](http://plnkr.co/edit/BsTlnGqX19t2UiTBblON?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
Sometimes some crucial text is too long and an ellipses is shown. In such case , user should be allowed to copy text from tootlip.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular : 4.3.6
Materail : 2.0.0.beta 10

**Comment by crisbeto** [comment]
This can now be controlled through the `matTooltipTouchGestures` input.
