### ISSUE TITLE
Recommended method for saving chip items and other chip features

### ISSUE THREAD

**Issue by BenRacicot** [angular/components#8819]
#### Bug, feature request, or proposal:
This is a feature request and or call for recommended method

#### What is the expected behavior?
Chips should validate, save to a form, be removable from a form, disallow duplicates, be separated by chosen delimiter

#### What is the current behavior?
Chips are added to `mat-chip-list`

#### What are the steps to reproduce?
How I am currently saving and removing chips to a form like this:
[https://stackblitz.com/edit/angular-material2-addchip](stackblitz.com/edit/angular-material2-addchip)

#### What is the use-case or motivation for changing an existing behavior?
I have seen several questions regarding chips on Gitter/StackOverflow. I'd like to ask for recommendations on the most efficient method to save and remove chips to a form. I cringe when I look over my `addChip()` method at the StackBlitz above and I think a lot of people are looking for a solid example.

I also didn't want to hijack #8801 regarding chip validation but maybe I can add to 8801 here for what is likely feature requests: 
Perhaps as developers we should be creating our own methods for chip entries but options such as validation, delimiting, saving/removing to a form easily and disallowing duplicates would be fantastic features to include. 

#### Is there anything else we should know?
The community really believes in your team's work. Thank you for your efforts in building/improving these features. Also, is there anything I can do to help?

**Comment by tinayuangao** [comment]
For delimiting, you can use `matChipInputSeparatorKeyCodes`  (see https://material.angular.io/components/chips/api). 

The docs for chip list needs improvements. We should have a better example for chip list with input and remove.

**Comment by tinayuangao** [comment]
Related issues: 
#8801 validation for chips
#9230 validation for duplicate chips on chip input

**Comment by jelbourn** [comment]
(revisiting older issues as part of a triaging fix-it)

Closing because I think this is a combination of obsolete and tracked in other issues. Feel free to open a new issue with more specific, granular feature requests.
