### ISSUE TITLE
Icons inside mat-icon-button not vertically centered.

### ISSUE THREAD

**Issue by romannurik** [angular/components#8842]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Icons inside mat-icon-button should be perfectly vertically centered.

#### What is the current behavior?
A 24px icon inside a 40px mat-icon-button by default ends up with 9px top padding and 7px top padding due to baseline-driven CSS layout.

Screenshot (red outlines and highlight to demonstrate the problem):
![image](https://user-images.githubusercontent.com/100155/33668140-dec18a5e-da6c-11e7-9221-f25483e3ae12.png)

#### What are the steps to reproduce?
Any basic mat-icon-button example has this problem, but I've forked and simplified an official example to make it easier to see:
https://stackblitz.com/edit/angular-3mdmnc

#### Is there anything else we should know?
This is one possible fix:

```
/* Coerce the <span> icon container away from display:inline */
.mat-icon-button .mat-button-wrapper {
  display: flex;
  justify-content: center;
}
```

**Comment by jelbourn** [comment]
@tinayuangao we should compare this to mdc

**Comment by Ploppy3** [comment]
Still no plan to fix this offset? I see that the person was even unassigned!

**Comment by rynop** [comment]
The way I do it is to utilize the `inline` attribute.  This will cause the icon to correctly scale with the size of the button.

```html
    <button mat-button>
      <mat-icon inline=true>local_movies</mat-icon>
      Movies
    </button>
    
    <!-- Link button -->
    <a mat-flat-button color="accent" routerLink="/create"><mat-icon inline=true>add</mat-icon> Create</a>
```

Then to solve the vertical alignment problem of the icon inside the button I add this to my `styles.css`:

```css
button.mat-button .mat-icon,
a.mat-button .mat-icon,
a.mat-raised-button .mat-icon,
a.mat-flat-button .mat-icon,
a.mat-stroked-button .mat-icon {
  vertical-align: top;
}
```

**Comment by andrewseguin** [comment]
This is still an issue, here's a stackblitz that shows this:

https://stackblitz.com/edit/angular-x5u5af?file=app%2Fbutton-types-example.css

**Comment by driima** [comment]
Any news on this? It's been an issue for well over a year now.

**Comment by xKloc** [comment]
It looks like adding a span around the text will correct this issue.

```
<button type="button" mat-button>
    <mat-icon>clear</mat-icon>
    <span>Clear</span>
</button>
```

**Comment by vishnu-dev** [comment]
Any updates on this?

**Comment by jpike88** [comment]
Can someone on the angular team give a definitive answer on if/when this issue will be fixed? It's a real eyesore, I don't know how this wasn't fixed when mat-icon-button was originally rolled out. @jelbourn ?

**Comment by Splaktar** [comment]
It's a P2, which is quite a high priority, so yes there are plans to address it. I don't think that it will get into `9.0.0`, but it's possibly a candidate for a `9.x` release.

The previous PR to fix this (PR https://github.com/angular/components/pull/8873) caused a LOT of screenshot failures for internal Google tests. So getting this fix synced into Google and released is going to be a major effort, even if the code change is very small.

Note that we've been focused on issues with a higher number of 👍 (for the OP) as this one only has 29.

**Comment by vyacheslavzhabitsky** [comment]
```
.mat-icon-button {
   line-height: unset
}
```

**Comment by Splaktar** [comment]
This may be something that we end up having to address in the new mdc-based components. If you could try out the [`MatButton`](https://github.com/angular/components/tree/a1e58631b8563cdf4faf3881849288966c4e3227/src/material-experimental/mdc-button) from [material-experimental](https://www.npmjs.com/package/@angular/material-experimental), it would be helpful if you could report if this is an issue that needs to be addressed there, before it leaves the experimental phase.

**Comment by JoeyVinyard** [comment]
I found a temporary fix for mat-mini-fab, and likely works for others as well. I simply added:
`.mat-mini-fab .mat-button-wrapper {
    padding: 0 !important;
}`
to my styles.css to remove the padding on the span that was inside of the buttons, this seemed to solve the issue for me.

Cheers

**Comment by simeyla** [comment]
No words...

**Comment by markkoo** [comment]
Any updates on this?

**Comment by wagnermaciel** [comment]
@crisbeto Could you verify for me whether or not this has been resolved? I checked on stackblitz and it seems ok now

https://stackblitz.com/edit/angular-zrplr2?file=src%2Fapp%2Fbutton-overview-example.css

**Comment by wagnermaciel** [comment]
@e-oz This is resolved in the new mdc-based implementation.

**Comment by e-oz** [comment]
@wagnermaciel could you please write a super-small example? Just 1-2 lines - I don't know the term “mdc” :) In Angular Material@14-next, mat-icon still has this issue.

**Comment by dwilches** [comment]
I just hit the same bug in Angular 14. Oddly, this was not affecting my application in Angular 13

**Comment by wagnermaciel** [comment]
@e-oz Sorry for the delay here! This got buried in my inbox. You can use the new component version by just changing your module import file path to `material-experimental` instead of `material`

https://github.com/angular/components/tree/main/src/material-experimental

**Comment by amysorto** [comment]
The new MDC based icon button component will be available in v15 soon where this issue is fixed! Closing this bug.
