### ISSUE TITLE
feat req: set line-height in typography defintions

### ISSUE THREAD

**Issue by bcoutch** [angular/components#8870]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-expansion-panel-typography should set the line-height from subheading-1

#### What is the current behavior?
Since mat-expansion-panel-typography does not set line-height, it is inherited from '.mat-typography'

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
StackBlitz starter (using latest `npm` release): https://stackblitz.com/edit/angular-material2-issue-7gt1mu<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.5, Material 5.0.0

**Comment by josephperrott** [comment]
`line-height` is actually not set by typography definitions from configs.  The line-height value is used within the `mat-typography-to-level-to-styles` mixin to determine the `font` attribute value.

To include this would be a request to include line-heights throughout all typography definitions.  as such I am going to make this as a feature.

**Comment by crisbeto** [comment]
Closing since the typography definitions have always had a `line-height` parameter.
