### ISSUE TITLE
[Menu] Truncated nested menus in FireFox

### ISSUE THREAD

**Issue by timwright35** [angular/components#8886]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The menus width to show the whole name like it does in Chrome and the menu to show all items (non-offscreen) when a long list is given.

#### What is the current behavior?
In Firefox the menu names are being truncated and in FF and Chrome the menu is off the screen when a long list is used.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-c2wnl5

#### What is the use-case or motivation for changing an existing behavior?

I have a place in my app where there is multiple nested menus that all have (at times) a long list of items. When that is the case in FF the menu truncates the item names and in both FF and Chrome does not show the full menu. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.1.0, Material 5.0.0-rc.2, Ubuntu, Typescript 2.4.2

**Comment by jelbourn** [comment]
I tried this real quick with the latest Angular Material and the latest Firefox and it doesn't seem to be an issue any longer. Free free to open a new issue if a problem persists.
