### ISSUE TITLE
[Stepper] Allow animation to be customized

### ISSUE THREAD

**Issue by AsafAgranat** [angular/components#8934]
Is it possible to **override the transition animation** set in Material Stepper?
I would like to set different timing and easing.

The Stepper animation currently is such:
````js
animations: [
    trigger('stepTransition', [
      state('previous', style({height: '0px', visibility: 'hidden'})),
      state('next', style({height: '0px', visibility: 'hidden'})),
      state('current', style({height: '*', visibility: 'visible'})),
      transition('* <=> current', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)'))
    ])
  ]
````
This is from [stepper.ts](https://github.com/angular/material2/blob/master/src/lib/stepper/stepper.ts) (line 119)

**Comment by eliteproxy7** [comment]
anyone found a way to customize the transition for the stepper? or at the ver least stop the exiting Step from just disappearing?

**Comment by jeandat** [comment]
At least if animation is not customisable, it should be refined. Currently the visible step disappears before animating next step. This is not pretty in my opinion. Of course this is subjective. 

It seems to me that it would be clearer for the end-user and also prettier if it was more of a carrousel. Clicking a step just slide from left to right or right to left. Eventually, the same could be done for the vertical stepper. I'm not a big fan of those accordions, they always lag on my machine and this is a Macbook pro.

**Comment by jelbourn** [comment]
Closing this since I don't think we would realistically prioritize this feature. Since cdk/stepper exists, it's relatively straightforward to put together a stepper with a custom animation.
