### ISSUE TITLE
[Select] Does not preselect values in Jasmine tests except in fakeAsync

### ISSUE THREAD

**Issue by josh18** [angular/components#8974]
#### Bug, feature request, or proposal:
Bug (possibly, not sure)

#### What is the expected behavior?
Select should preselect values inside a test

#### What is the current behavior?
Select does not preselect values inside a test _unless the component is inside_ `fakeAsync()` _when it is created_.

#### What are the steps to reproduce?
Would have liked to be able to make a demo but couldn't figure out how to use Jasmine inside of StackBlitz/Plunker.

All you need is a `<mat-select>` that has a preselected value. Essentially the test is this: https://github.com/angular/material2/blob/master/src/lib/select/select.spec.ts#L2253-L2270

If you have a similar test and the component isn't being created (`TestBed.createComponent()`) inside of `fakeAsync()` then the select inside your component won't have any preselected values. This is most noticeable when testing a `multiple` select as when you open the overlay none of the preselected values are checked.

Even if your test is inside `fakeAsync()` if you have a `beforeEach()` that is creating the component and is not using `fakeAsync()` then the select won't preselect valeus correctly.
```
beforeEach(() => {
     fixture = TestBed.createComponent(MyComponent);
     fixture.detectChanges();
});

it('should have preselected values', fakeAsync(() => {
    flush();

    // The preselected values aren't selected when you check here
});
```

Note that it doesn't seem to matter if you call `flush()` or not it just seems to need to be inside `fakeAsync()`.

#### What is the use-case or motivation for changing an existing behavior?
I'm not sure of the cause behind this and it could be completely intentional. However it took me awhile to figure out what was happening so thought I would create this in case anyone came across the same issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Testing using
```
Angular v5.0.1
Angular Material v5.0.1
Jasmine v2.8.2
Typescript v2.6.2

Windows v10
```

**Comment by crisbeto** [comment]
This is likely because the select defers assigning the selected value in order to avoid "changed after checked" errors. You can work around this either by calling `flush` in your tests or using the select test harness.
