### ISSUE TITLE
Angular Material schematics

### ISSUE THREAD

**Issue by jelbourn** [angular/components#8975]
Brainstorming ideas (some of these are more long-term):
* [x] Basic app layout with toolbar and sidenav
  * [ ] Could include a fab
  * [x] Could include a nav-list in the sidenav
  * [ ] Could include a `...` menu in the toolbar
* [x] Add a page with a grid-list layout
* [x] Add a page with a full-page data-table
* [x] Add a page with a full-page tree
* [ ] Add a card layout with drag-and-drop (similar to Google Keep)

**Comment by dpsthree** [comment]
Any interest in color palette and theme generators?

**Comment by t0f3rchr15** [comment]
Even basic material module creation would be useful to avoid the boilerplate every time you begin a new app:
``` bash
ng generate mat-module icon card ... --module shared
```

**Comment by Hotell** [comment]
check this @t0f3rchr15  @dpsthree  👉 https://github.com/Hotell/ng-cli-schematics

**Comment by mackelito** [comment]
Perhaps the app layouts could be css grid layout based? (nothing to do with schematics I know but still.. ) :)

**Comment by Splaktar** [comment]
Updated OP with checkboxes to show which are done and which are not at this point.

@mackelito currently the layouts are using the [CDK Layouts](https://material.angular.io/cdk/layout/overview) along with [mat-grid-list](https://material.angular.io/components/grid-list/overview) which uses `block` and `flex` layouts.

The `@angular/flex-layout` project currently supports CSS Grid layouts. Here's their [Guide](https://github.com/angular/flex-layout/blob/master/guides/Grid.md).

**Comment by devversion** [comment]
I'm closing this issue as we already have schematics and we should use individual tickets now for planned work.
