### ISSUE TITLE
Need a size attribute for mat-select

### ISSUE THREAD

**Issue by bibhas2** [angular/components#9041]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Currently mat-select shows only one ``mat-option`` at a time. We need a way to control the number of visible items. Such as:

```
<mat-select placeholder="Favorite food" size="10">
</mat-select>
```

#### What is the current behavior?
The ``size`` attribute as no effect on ``mat-select``.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.0
Angular material: 5.0.1

**Comment by YoussefTaghlabi** [comment]
We are looking to use the `size` attribute too. If material is not planning to support the `size` attribute, any recommendations on what we should be using instead?

**Comment by sircody01** [comment]
I would like to use a size attribute also, or something equivalent.

**Comment by rolzing** [comment]
Any updates on this?

**Comment by desianonhubject** [comment]
Needed here too...

**Comment by crisbeto** [comment]
We have a new version of the select coming up (same logic and API, but different CSS) which will support changing the size of the dropdown using CSS. You can try it out by importing the `MatSelectModule` from `@angular/material-experimental/mdc-select`.
