### ISSUE TITLE
Feature request: Add projectable nodes agrument to ComponentPortal

### ISSUE THREAD

**Issue by Anufryieu** [angular/components#9045]
#### What is the expected behavior?

[cdk/portal/portal.ts](https://github.com/angular/material2/blob/master/src/cdk/portal/portal.ts#L96)

```
constructor(
      component: ComponentType<T>,
      viewContainerRef?: ViewContainerRef | null,
      injector?: Injector | null,
      projectableNodes?: any[][] | null) {
    super();
    this.component = component;
    this.viewContainerRef = viewContainerRef;
    this.injector = injector;
    this.projectableNodes = projectableNodes;
  }
```

[cdk/portal/dom-portal-outlet.ts](https://github.com/jelbourn/material2/blob/master/src/cdk/portal/dom-portal-outlet.ts#L46)
```
componentRef = portal.viewContainerRef.createComponent(
          componentFactory,
          portal.viewContainerRef.length,
          portal.injector || portal.viewContainerRef.parentInjector,
          portal.projectableNodes);
```

createComponent method should get additional parameter - projectableNodes.

#### What is the current behavior?
[cdk/portal/portal.ts](https://github.com/angular/material2/blob/master/src/cdk/portal/portal.ts#L96)

```
constructor(
      component: ComponentType<T>,
      viewContainerRef?: ViewContainerRef | null,
      injector?: Injector | null) {
    super();
    this.component = component;
    this.viewContainerRef = viewContainerRef;
    this.injector = injector;
  }
```

[cdk/portal/dom-portal-outlet.ts](https://github.com/jelbourn/material2/blob/master/src/cdk/portal/dom-portal-outlet.ts#L46)
```
componentRef = portal.viewContainerRef.createComponent(
          componentFactory,
          portal.viewContainerRef.length,
          portal.injector || portal.viewContainerRef.parentInjector);
```

#### What is the use-case or motivation for changing an existing behavior?
I need to pass projectable nodes to component for component portal.

#### Is there anything else we should know?
#9030

**Comment by Anufriev** [comment]
Any updates?

**Comment by maxailloud** [comment]
This feature could be really useful.

**Comment by georgelviv** [comment]
Anyone, has some ideas, how to implement this with CDK Portal?

**Comment by yarinsa** [comment]
Making the same request. Does anyone managed to do it otherwise?
