### ISSUE TITLE
[Table] Paginator doesn't play nice with expandable rows

### ISSUE THREAD

**Issue by parker789** [angular/components#9052]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Using the when predicate within mat-table, i'd like to also be able to use MatPaginator correctly.

#### What is the current behavior?

Right now we have a working example of an exandable row within the table, but unfortunately these "hidden" rows are included within MatPaginator's length.

#### What are the steps to reproduce?

Can get a working plunkr if needed

#### What is the use-case or motivation for changing an existing behavior?

It's currently broken without

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest / Chrome OS

**Comment by andrewseguin** [comment]
Is this because you are using the `MatTableDataSource`?

**Comment by VivekShingala** [comment]
Has this been fixed yet? I am also using MatTableDataSource for expanded rows.

**Comment by parker789** [comment]
It's been so long since I've worked with this I'd have to dig some older code up to determine that. I'm assuming @VivekShingala that this is still an issue?

**Comment by kamalSaiDd** [comment]
Hi 
I have the same issue. Row expansion works but page count doubles

When rows expanded, Page count doubles.

I used MatTableDataSource

**Comment by josephkane** [comment]
same thing here, page count is doubled with "when," also using MatTableDataSource. Any update on a fix?

**Comment by parker789** [comment]
closing this as it's been dead for awhile
