### ISSUE TITLE
Use Data tables columns padding following Material guidelines

### ISSUE THREAD

**Issue by robmv** [angular/components#9152]
#### Bug, feature request, or proposal:

Proposal. Current material style data table has no padding between columns, only at the start of the first column and the end of the last one (left and right padding at row level).

[Material guidelines request a 56dp padding between all columns][1] (Column padding section). I personally think 24dp is enough. Data tables are a better designed for desktop interaction, so 24dp sounds right for a non touch UI.

On the guidelines example there are some columns with 24dp padding (the checkbox and description columns) and the pure numeric columns use 56dp. Maybe a new column property to indicate small or large paddings could help.

[1]: https://material.io/guidelines/components/data-tables.html#data-tables-specs

#### What is the expected behavior?

Data table columns should have a default padding

#### What is the current behavior?

Data table columns doesn't have padding

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-sbmhet

#### What is the use-case or motivation for changing an existing behavior?

A better default for columns padding. Currently all tables should be CSS styled to set the proper paddings. If an input property is added, better, the designer could  choose the two recommended column paddings at template level without CSS

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 5.1.0 and Material 5.0 as examples currently published on https://material.angular.io/components/table/overview

**Comment by SGissubel** [comment]
Has this been updated yet?  / Is there a way to add padding between cells?

**Comment by sharpninja** [comment]
I've spent the last hour trying to make this work with layout layout-padding and flex to no avail before I found this.  This is really important.  Can we get an eta?

**Comment by pjr0001** [comment]
> I could only get this to work with `!important`, as the `mat-` css is written into a style tag in the html and my `styles.scss` will not override otherwise. There must be a better way.
> 
> ```
> mat-cell,
> .mat-cell,
> mat-footer-cell,
> .mat-footer-cell,
> mat-header-cell .mat-header-cell {
>   padding: 0.75rem !important;
> }
> ```

just a heads up, you're missing a comma between mat-header-cell and .mat-header-cell

Thanks though! I ended up just doing this for now.

**Comment by Presiana** [comment]
> Hi, @michael-lang!
> Got your css but had to remove "display:block" as it was putting columns in rows.
> Thanks for sharing it.

You can set 
```
.mat-header-row, .mat-row {
    display: flex;
} 
```
and in this way everything looks fine

**Comment by m00dy** [comment]
> > Hi, @michael-lang!
> > Got your css but had to remove "display:block" as it was putting columns in rows.
> > Thanks for sharing it.
> 
> You can set
> 
> ```
> .mat-header-row, .mat-row {
>     display: flex;
> } 
> ```
> 
> and in this way everything looks fine

But, I don't feel good here 🔥 🔥 🔥

**Comment by benneq** [comment]
How often do the material specs change?

The padding for the first column should be 16px.
And the header row should have 48px height.

Angular materials uses 24px padding for the first column, and 56px header height.

**Comment by fahimehahmadi94** [comment]
::ng-deep .mat-row{
padding : 25px;
}

**Comment by amysorto** [comment]
The new MDC based table component coming soon in v15 has the correct padding between columns based on the [the material spec](https://m2.material.io/components/data-tables#anatomy).
