### ISSUE TITLE
[Tabs] Export all tab components to allow extending

### ISSUE THREAD

**Issue by nop1984** [angular/components#9216]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Extending the MatTabGroup

#### What is the current behavior?
not possible to extend MatTabGroup because of MatTabBody  and MatTabHeader and MatTabLabelWrapper are not included in module export list

#### What are the steps to reproduce?
Try to extend MatTabGroup to add tab close icon and function. You will get errors like "ERROR in : Can't bind to 'selectedIndex' since it isn't a known property of 'mat-tab-header'." to your overloaded template of MatTabGroup class

#### What is the use-case or motivation for changing an existing behavior?
Because having a static Tabs is not enough. I want to repoduce MDI behaviour where each tab will contain a named router-outlet of links which invoked by other components of application. And ofcource user must be able to close tabs he have opened before 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all is latest to current date

#### Is there anything else we should know?
There is only few string to add in @NgModule section to export: [] here https://github.com/angular/material2/blob/master/src/lib/tabs/tabs-module.ts

**Comment by nop1984** [comment]
@jelbourn , @josephperrott , @andrewseguin FYI, please take a look

**Comment by Dorkside** [comment]
This would be greatly appreciated

**Comment by andrewseguin** [comment]
Closing since we do not intend to support extending these private classes
