### ISSUE TITLE
Mat-icon : error in StackBlitz on the Examples tab for SVG icons

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [angular/components#9220]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To have a full working example on StackBlitz for the SVG icons, on the Examples tab (Mat-icon)

#### What is the current behavior?
The example is not working as the 'icon-svg-example.ts' is missing on StackBlitz.

#### What are the steps to reproduce?
Just click on the "Edit in StackBlitz" button on the Examples tab for SVG icons (Mat-icon)

**Comment by MA-Maddin** [comment]
Sad that SVG files are not allowed on StackBlitz at all, because they are "binaries".
https://github.com/stackblitz/core/issues/45

**Comment by EricSimons** [comment]
SVGs are allowed on stackblitz. We just need to enable the loader for vendor. Will get a fix in and circle back.

**Comment by crisbeto** [comment]
This seems to work now. Closing.
