### ISSUE TITLE
mat-select required does not set ngForm.form.valid to false if not set

### ISSUE THREAD

**Issue by Kayes-Islam** [angular/components#9259]
I have a mat-select with required. 
`<mat-select placeholder="Favorite animal" [formControl]="animalControl" required>`
I then use `!ngForm.form.valid` to disable the save button until required fields are filled in, but `ngForm.form.valid` isn't set to false. Attached is the reproduced sample.

[mat-select-issue.zip](https://github.com/angular/material2/files/1608939/mat-select-issue.zip)

**Comment by julianobrasil** [comment]
A zip file is nice, but I think it's easier to show the issue with stackbliz: https://stackblitz.com/edit/material2-issue-select

**Comment by julianobrasil** [comment]
Related to this: https://github.com/angular/angular/issues/14342#issuecomment-278148056

**Comment by aelkoussy** [comment]
Hi Guys,
Do we have any way to tackle this issue? I couldn't find any clue on how to set the dropdown as required using material & angular template driven forms (ngForm)

**Comment by aelkoussy** [comment]
This is not an issue, you can refer to this [stackoverflow question ](https://stackoverflow.com/questions/50087495/angular-5-material-dropdown-select-required-validation-is-not-working/50087824#50087824) about the same issue.

So this is not an issue & I recommend that someone close it to reduce noise.
