### ISSUE TITLE
Linear mode in stepper component doesn't work if stepControl is not set for every step

### ISSUE THREAD

**Issue by ganqqwerty** [angular/components#9268]
#### Bug, feature request, or proposal:
Make linear option work correctly even if there is no `stepControl`
#### What is the expected behavior?
`linear` option should prevent a user from skipping the steps.

#### What is the current behavior?
If we don't use stepControl for each step, the `linear` option doesn't change the behaviour of the stepper. 

#### What are the steps to reproduce?
I modified an example app for a linear stepper to demonstrate the bug [here](https://angular-dfj2ld.stackblitz.io). 

#### What is the use-case or motivation for changing an existing behavior?
`stepControl` is not a required option and some users don't use it, but still want to profit from `linear` option.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular material 2.0.0.beta2

**Comment by Avinkav** [comment]
Is this resolved yet? Or is there a workaround?

**Comment by az264** [comment]
when you don't want to use stepControl you should use completed that gets a boolean
