### ISSUE TITLE
[Tooltip] Breaks text input in Firefox

### ISSUE THREAD

**Issue by thw0rted** [angular/components#9333]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Applying `matTooltip` should not change behavior in `<input>`

#### What is the current behavior?
When `matTooltip` is applied to an `<input>` (not inside a `<mat-form-field>`), the text cursor starts to behave strangely.  Typing the (forward) delete key causes the text cursor to move forward once, *then* delete the next character.  It also makes it impossible to select text in the field using Shift and the left/right arrow keys.  Mouse drag (to select text) appears to be ignored.

#### What are the steps to reproduce?
Open [this Stackblitz](https://stackblitz.com/edit/angular-shqgy1), which was forked from the matTooltip docs example, in Firefox (tested on v57.0.4, Windows and Ubuntu).  Type some text in both boxes.  In the top box (no matTooltip), observe that the delete key works as expected and text can be selected with keyboard or mouse.  In the bottom box, observe strange delete-key behavior; try to select text with keyboard or mouse -- it's not possible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Observed with Angular 5.2.0, Material 5.0.0-rc3 and 5.0.2 release, Firefox 57 on both Ubuntu and Windows (probably Mac, don't have one in front of me)

#### Is there anything else we should know?
I don't have a pre-Quantum release of Firefox handy but I suspect this is related to something in the new codebase there.

**Comment by thw0rted** [comment]
On further investigation, it looks like the root cause of both problems (selection, and strange Delete key behavior) is the application of style: `-moz-user-select: none`.  In Chrome, `user-select: none` is applied but the browser appears to ignore this -- I can't seem to find guidance for how a browser is supposed to treat `user-select` and its variants in `<input>`s specficially.  So, I guess the question becomes, *why* does applying a `matTooltip` to an `<input>` cause it to have `user-select` (or a variant thereof) applied to the element?

**Comment by thw0rted** [comment]
It looks like there are two issues here.  The first is that Firefox handles `user-select` wrong for inputs, which [has been a known issue for 2 years](https://bugzilla.mozilla.org/show_bug.cgi?id=1231097) with no movement.  I'm kind of astonished nobody noticed, but that's beside the point -- I can fix it with a simple global rule:

    input { -moz-user-select: text !important; }

The second is a deeper design issue: why does matTooltip cause the target element to be styled with `user-select: none`?  I think I get the motivation -- in a touch environment, tooltips must fire on press (or long-press?) so you don't want to select the element when opening the tooltip.  But in a desktop environment, the tooltip fires on hover, so there's no danger of accidental selection.  Maybe this means that the selection restriction should only be applied when touch is available?  Or maybe even only on mobile?  I think it needs some discussion.

**Comment by crisbeto** [comment]
We already do a similar [workaround for input on iOS](https://github.com/angular/material2/blob/master/src/lib/tooltip/tooltip.ts#L217). Perhaps we should expand it to everything @andrewseguin?

**Comment by thw0rted** [comment]
I'm not sure if disabling this on *all* devices makes sense. If I have a touchscreen Windows laptop in tablet mode, running, say, Chrome, I have to longpress to show the tooltip.  Without these styles, will that also select a word, or maybe the whole input contents?

It seems to me that HammerJS is using a blunt instrument to address a problem that would benefit from a bit more finesse.  Is it not possible to stop propagation of the long-press event, keeping the default (selection) behavior from happening, without totally disabling all ways of selecting text?  Should I be addressing this concern to the HammerJS tracker instead?

**Comment by petogriac** [comment]
I spotted this not only in inputs, but also when you add a tooltip to a text in span or div or whatever. Then the text is not selectable for the user(so e.g. he cannot copy it), because _user-select: none;_ is added by mat-tooltip.

Is there any progress on this issue ? thanks for info

**Comment by crisbeto** [comment]
This can now be disabled on a case-by-case using the `matTooltipTouchGestures` input.

**Comment by thw0rted** [comment]
Am I right in assuming that the default behavior has changed and that if `matTooltipTouchGestures` is not specified, the "auto" behavior is applied?  Which would mean that the text-selection changes aren't applied to inputs, so the original issue is no longer applicable?

Re: the Firefox-specific bug, I just tested and I think it's been fixed at some point.

**Comment by crisbeto** [comment]
The default is `auto` which prevents text selection on anything except for `input` and `textarea`. I'm not sure about the Firefox-specific bug, but we stopped using Hammer.js a while ago which could've fixed it.
