### ISSUE TITLE
Mat-list-option model has refresh problem when is used as source list of mat-chip-list

### ISSUE THREAD

**Issue by desmoslevin** [angular/components#9335]
#### Bug, feature request, or proposal:

I'm using a list of options, with the angular material component. This is the ts class on which is based:

```
export class Attribute {
    id: number;
    title: '';

    constructor(values: Object = {}) {
        Object.assign(this, values);
    }
}

```
list of options
```
<mat-selection-list #list [(ngModel)]="selectedAttributes">
<mat-list-option class="mat-list-option" *ngFor="let a of attrs" [value]="a.id">{{a.title}}</mat-list-option>
</mat-selection-list>
```

list of chips, connected to the selected options of the list before
```
<mat-chip-list *ngFor="let x of selectedAttributes" [(ngModel)]="selectedAttributes">
<mat-chip [removable]="true" (remove)="remove(x)">{{x}}<mat-icon matChipRemove>cancel</mat-icon></mat-chip>
</mat-chip-list>
```

ts:

```
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Attribute } from '../../attribute';
...

@Component({
    selector: 'home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

    attrs: Attribute[] = [];
    selectedAttributes: number[] = [];

    constructor(
        private attrService: AttributeDataService,
        private router: Router,
    private changeDetectorRef: ChangeDetectorRef) { }

    ngOnInit(): void {
        this.getAttributes();
    }

    getAttributes(): void { 
    ... get the attributes here from an api
    }

   remove(attributeId: number): void {
            index = this.selectedAttributes.indexOf(attributeId);
            if (index != -1)
                this.selectedAttributes.splice(index, 1)
    }

}

```

#### What is the current behavior?
When I choose an option in the list, a chip appear. When I delete a chip, the option is not updated and remains checked

#### What is the expected behavior?
When I choose an option in the list, a chip appear. When I delete a chip, the option should be updated and it should be unchecked

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/cdk": "^5.0.3",
    "@angular/material": "^5.0.3",
    "@angular/common": "5.1.2",
    "@angular/compiler": "5.1.2",
    "@angular/core": "5.1.2",
    "@angular/forms": "5.1.2",
    "@angular/http": "5.1.2",
    "@angular/platform-browser": "5.1.2",
    "@angular/platform-browser-dynamic": "5.1.2",
    "@angular/router": "5.1.2",
    "core-js": "^2.4.1",
    "rxjs": "5.5.6",
    "zone.js": "^0.8.4",
    "@angular/flex-layout": "2.0.0-beta.12"

**Comment by mmalerba** [comment]
If this is still an issue can you please provide a stackblitz reproduction

**Comment by wagnermaciel** [comment]
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.
