### ISSUE TITLE
Focusing checked radio button does not work by tab key in IE

### ISSUE THREAD

**Issue by nikolaj10** [angular/components#9400]
#### Bug, feature request, or proposal:
Pressing the tab key to focus checked radio button does not work for internet explorer 11  in the following code (example in material.angular.io documentation):
```
<mat-checkbox>Seasons</mat-checkbox>
<br>
<mat-radio-group class="example-radio-group" [(ngModel)]="favoriteSeason">
  <mat-radio-button class="example-radio-button" *ngFor="let season of seasons" [value]="season">
    {{season}}
  </mat-radio-button>
</mat-radio-group>
<div class="example-selected-value">Your favorite season is: {{favoriteSeason}}</div>
```

#### What is the expected behavior?
Focusing the **checked** radio button after pressing tab key from the previous element (checkbox in this case)

#### What is the current behavior?
Example: Instead of focusing the checked radio button by pressing the tab key from the previous element (checkbox), it focuses the first (checked or unchecked) radio button after pressing the tab key
(it is described in more detail in the next paragraph, which contains all steps to reproduce the bug)

#### What are the steps to reproduce?
Example: After checking the second radio button (the spring one) from the example in the previously mentioned code and then clicking on the previous element (checkbox) before the radio button group, it focuses the right radio button (the spring one) after pressing the tab key, but if i repeat the previous step and checking the third radio button (the summer one) now and then clicking on the previous checkbox, it should focuses the third (checked) radio button (the summer one) after pressing tab key like it happened to the second one, but  it focuses the first (checked or unchecked) radio button, which is wrong i think

https://stackblitz.com/edit/angular-kzyxc7

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on:
Material 5.0.4
Angular 5.0.0
Windows 7
IE Version: 11.0.9600
IE Update Version: 11.0.49

**Comment by julianobrasil** [comment]
In the mean time, is updating IE an option? I have 11.0.50 and it works fine.

**Comment by nikolaj10** [comment]
Hi, i updated my comment, so now you should saw the wrong behavior on the web site. I'm sorry I did not describe the problem properly (in more detail) for the first time

**Comment by julianobrasil** [comment]
It must be very specific to the particular version you've mentioned. It still works for me in a more recent vertion (and Windows 10):

![image](https://media.giphy.com/media/l1IBjjbpVXXR6UCBO/giphy.gif)

**Comment by nikolaj10** [comment]
It's not the problem in the particular version of browser, because i also try it on Windows 10 with last version of Internet Explorer 11 (Update version 11.0.49) and it works, so you are right. But it's obviously not working for Windows 7 with the same version of IE 11.

**Comment by jelbourn** [comment]
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.
