### ISSUE TITLE
feat: allow `MatFormFieldControl` to be content projected into `mat-form-field` using `ng-content`

### ISSUE THREAD

**Issue by rodaz** [angular/components#9411]
#### Bug, feature request, or proposal:
Placeholder on input not floating when projected from ng-content.

#### What is the expected behavior?
Placeholder must floating, when input has some value.

#### What is the current behavior?
Placeholder looks like standard html placeholder, not like material placeholder. 

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-material2-issue-jekywv<br/>

#### What is the use-case or motivation for changing an existing behavior?
Inability to use mat input with content projection.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

#### Is there anything else we should know?
In console i have an error: mat-form-field must contain a MatFormFieldControl.

**Comment by mmalerba** [comment]
FYI it's not just the placeholder that has issues, this is completely unsupported right now, hence the errors

**Comment by Ilya1vanov** [comment]
Have the same issue. This feature will extremely help me to reduce boilerplate html. Please, fix it! Thx

**Comment by guilnorth** [comment]
News?

**Comment by papakojo** [comment]
I ended up using [material-design-lite](https://github.com/google/material-design-lite) as a temporary solution, hope this gets resolved soon.

**Comment by natepaxton** [comment]
Are there any related issues to this one?  This seems like a very glaring oversight that should've been fixed by now.

**Comment by winstonchavez** [comment]
ERROR Error: mat-form-field must contain a MatFormFieldControl.   same error, all modules working well, except this.

**Comment by ianchi** [comment]
Hi, any comments on the status of this issue?

**Comment by fxck** [comment]
Mh.. this complicates things. Not using `ng-content` but `ngTemplateOutlet`, but that the same story I guess.

**Comment by qwe852147** [comment]
There has a dirty method is setting the matformFieldControl in the child component.

StackBlitz: https://stackblitz.com/edit/angular-material2-issue-rewh7v?file=app/field.component.ts

**Comment by fatal-zio** [comment]
This is a rather glaring limitation. Hopefully it gets addressed soon.

**Comment by brampeirs** [comment]
This worked for me:

https://stackoverflow.com/questions/50574642/angular-material-mat-form-field-custom-component-matsuffix-in-ng-content

**Comment by conterio** [comment]
I only get this error when I add the basic native select, but other work fine.
<mat-form-field>
  <select matNativeControl required>

**Comment by iamruslanbakirov** [comment]
Waiting clear solutions...more than a year

**Comment by juniorgasparotto** [comment]
"Waiting clear solutions...more than a year" me too!

**Comment by robphoenix** [comment]
ping @mmalerba 

Is resolving this a consideration atm?

**Comment by claytoncc** [comment]
You need to import the **MatInputModule** into your **app.module.ts** file

**Comment by kapalex** [comment]
A somewhat crude solution I found to bypass the issue
```
<mat-form-field #matFormField [appearance]="appearance">
  <input matInput [hidden]="true">
  <ng-container [ngTemplateOutlet]="content"></ng-container>
</mat-form-field>
```

Seems to work, although you should test carefully

**Comment by Nziranziza** [comment]
> You need to import the **MatInputModule** into your **app.module.ts** file

import { MatInputModule} from '@angular/material';
works fine

**Comment by hankchiutw** [comment]
I got this work by:
```
<mat-form-field>
  <input matInput hidden>
  <ng-content></ng-content>
</mat-form-field>
```

**Comment by GrandSchtroumpf** [comment]
I didn't managed to make @qwe852147's solution work with version 9. So I came up with an even dirtier solution: 
html: 
```html
<mat-form-field>
  <ng-content></ng-content>
  <!-- Placeholder control to fool mat-form-field -->
  <ng-container *ngIf="beforeViewInit">
    <input matInput/>
  </ng-container>
</mat-form-field>
```

typescript:
```typescript
export class FormFieldComponent implements AfterViewInit
  beforeViewInit = true;  // Used to remove placeholder control
  @ContentChild(MatFormFieldControl) control: MatFormFieldControl<any>;
  @ViewChild(MatFormField) matFormField: MatFormField;

  constructor(private cdr: ChangeDetectorRef) {}
  ngAfterViewInit() {
    if (this.beforeViewInit) {
      this.matFormField._control = this.control;
      this.beforeViewInit = false;
      this.cdr.detectChanges();
    }
  }
}
```
I just hope this issue will be addressed at some point to avoid this ugly / suboptimzed solution.

**Comment by ASKN2811** [comment]
Import  "MatFormFieldControl" in which component you want to use if you use a particular component.

 import { Component, OnInit } from '@angular/core';
import {MatFormFieldModule,MatFormFieldControl} from '@angular/material/form-field';
@Component({
  selector: 'app-bike',
  templateUrl: './bike.component.html',
  styleUrls: ['./bike.component.scss']
})
export class BikeComponent implements OnInit {

  constructor() {
  }

  ngOnInit(): void {
  }

}

**Comment by mmalerba** [comment]
This is a limitation of Angular's content projection. https://github.com/angular/angular/issues/37319 has been filed to hopefully improve some of the short-comings
