### ISSUE TITLE
Support readonly for slider

### ISSUE THREAD

**Issue by DooMachine** [angular/components#9468]
#### Bug, feature request, or proposal:
Enabling disabled mat-slider to show value and color.

#### What is the expected behavior?
Cannot show previously selected value in mat-slider. And cannot set color to disabled slider.
Something like this
```
<mat-slider 
              showThumbLabelAlways ="true"
              thumbLabel="true"
              color="warn"
              showColorOnDisabled="true"
              disabled="true"
              value="immutableValue"></mat-slider>
```

#### What is the current behavior?
mat-slider has no preference to show thumbLabel on un-focused state and show default color in disabled state.

#### What is the use-case or motivation for changing an existing behavior?
To show detailed data in slider.

**Comment by DevVersion** [comment]
So basically a `readonly` mode, where the thumb label always shows?

![image](https://user-images.githubusercontent.com/4987015/35193961-474f67e6-feab-11e7-92c8-053a491c507a.png)

**Comment by DooMachine** [comment]
Yeah, it would be nice I guess.

**Comment by pdarii** [comment]
Will be cool

**Comment by DeepeshJha** [comment]
Any solution for this?

**Comment by lguerdan** [comment]
Yes please implement this.

**Comment by wagnermaciel** [comment]
Hello, unfortunately this is not something we plan to support. It is not within the scope of what we want to maintain and from a ui/ux pov it's almost certainly better practice to just disable the slider and display the value next to it

E.g.
```html
<mat-slider discrete showTickMarks disabled>
  <input matSliderThumb #thumb>
</mat-slider>
<p>Slider value: {{thumb.value}}</p>
```
