### ISSUE TITLE
Feature: Md-Slider with threshold and 2 colors 

### ISSUE THREAD

**Issue by rskendzic** [angular/components#9478]
#### Feature request, or proposal:
Change color of md-slider after threshold is breached. 
#### What is the expected behavior?
To be able to set threshold on slider, which will be shown to user, and which would change the color of slider from that point on.

![screen shot 2018-01-19 at 2 06 40 pm](https://user-images.githubusercontent.com/22195559/35152308-3915ab0c-fd22-11e7-8308-e567394c9f10.png)

`<mat-slider 
              color="primary"
              threshold="calculatedThreshold"
              threholdBreachedColor="warn"
              value="immutableValue"></mat-slider>`

#### What is the current behavior?
At the moment you can only have one color for slider.

#### What is the use-case or motivation for changing an existing behavior?
Notify user that he has limit, after which he is on his own, due to passing the suggested limit he should choose.

**Comment by timmoy** [comment]
If this is still available I'd like to take a stab at it.

**Comment by jelbourn** [comment]
Closing this since I don't see us adding support for this feature unless it were included in the Material Design spec.
