### ISSUE TITLE
Choppy dialog animation in Chrome on Android

### ISSUE THREAD

**Issue by pulsejet** [angular/components#9547]
#### Bug, feature request, or proposal:
The dialog opening animation is really choppy on Android under Chrome (tested in Marshmallow, Chrome 63)

#### What is the expected behavior?
Animation should be smooth

#### What is the current behavior?
The dialog lags terribly while opening

#### What are the steps to reproduce?
Open the [example dialog](https://material.angular.io/components/dialog/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.1 with Material 5.1.0 tested under Chrome 63, Android 6.0

**Comment by GreedyAlchemist** [comment]
I have the same issue. Especially when having a image in dialog. It opens really choppy and noticeably.

**Comment by abductedMind** [comment]
Me too. Its bad enough that we are considering not using it just because of this.

**Comment by mmalerba** [comment]
It seems fine now, just tested it.

Android 10 - Pixel 3
Angular 10

**Comment by pulsejet** [comment]
Thanks, it does seem to be fixed now.

On a side note @mmalerba I hardly think Pixel 3 is the right device to test for performance issues. In fact, even when I first reported the bug, it was never present on more powerful hardware.
