### ISSUE TITLE
Feat : [mat-button-toggle] - output for blur event. Dom is not reliable.

### ISSUE THREAD

**Issue by seedy** [angular/components#9624]
#### feature request :
There is not Output for blur or focusOut events for button toggle group component.
Using classic DomEvent relies on the component's implementation.
Button toggle is made of a hidden input which takes focus over the button after internal selection has been triggered.

I need to know when the group or any of its children lose focus.

Therefore, I cannot reliably bind on blur event or focusout event because I cannot know if my button loses focus because of its internal input or because of an outside click.

#### What are the steps to reproduce?
Have a look here and check console logs.
https://stackblitz.com/edit/angular-azywqh

This stackblitz was forked from material docs example on button toggle groups.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, based on documentation.

**Comment by seedy** [comment]
Workaround : 
https://stackblitz.com/edit/angular-azywqh-koxarx

```
const elem = this.radioGroup._buttonToggles.find((button) => {
                const isButton = (button.id === target.id);
                const isInput = (button.inputId === target.id);
                // workaround because radiobutton can trigger event on its child input
                return isButton || isInput;
            });
            // elem is one of our buttons or undefined. if elem is one of our buttons, do not trigger
            if (elem) {
                return;
            }
```

**Comment by tinayuangao** [comment]
@seedy You can always use `FocusMonitor` to track focus of a component. 

Example here: https://stackblitz.com/edit/angular-azywqh-azbmp2?file=app%2Fbutton-toggle-exclusive-example.ts

**Comment by seedy** [comment]
@tinayuangao It's then very easy to implement an eventEmitter method in the component, built upon your example. Would that be a recommended approach? I would try and do a PR soon.

**Comment by seedy** [comment]
Here's what I meant : https://stackblitz.com/edit/angular-azywqh-wjf2uj

**Comment by jelbourn** [comment]
Is there a reason `blurout` wouldn't work for you?

**Comment by seedy** [comment]
Sorry, I left this issue stale for a while.

You can consider it fixed as I didn't need any change since.
