### ISSUE TITLE
slider invert should invert incrementing or just sliding direction?

### ISSUE THREAD

**Issue by odahcam** [angular/components#9753]
#### Bug, feature request, or proposal:
dicussion, maybe a new feature

#### What is the expected behavior?
Invert the slider should invert the behavior, invert the values, not the just direction of sliding.

#### What is the current behavior?
Inverting the slider only changes the sliding direction, not the values, so the sliders always increase the value as we slide and we cannot invert the behavior to decrease the value.

#### What is the use-case or motivation for changing an existing behavior?
I have a price filter, min price should go from 0 to max value, and max value should go from x to min value, take a look:
![image](https://user-images.githubusercontent.com/3942006/35739466-d40eba1c-0818-11e8-847d-2a0c78b47bbf.png)
I CSS rotated the max slider to create the example.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Mat. 5.1

#### Is there anything else we should know?
Material docs say nothing about inverted sliders, not even in the bidirectionality section, so I truly believe that sliders can have this customization.

**Comment by jelbourn** [comment]
Closing since this feature is likely too niche for general adoption
