### ISSUE TITLE
Feature request: Move material core datetime stuff (adapter, formats, ...) to CDK

### ISSUE THREAD

**Issue by thomaspink** [angular/components#9839]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
As we use the CDK, it would be really helpful, to move the date/time logic located in src/lib/core/datetime/ to the CDK.

#### What is the current behavior?
Date/time adapter and formats only available in Material

#### What is the use-case or motivation for changing an existing behavior?
We are currently working on some components that have some date/time logic in our own lib. We use the CDK (and are really pleased with it) and those adapters exposed there would really benefit us.

Thanks & keep up the great work

**Comment by jelbourn** [comment]
This is something we plan to do eventually but want to make sure it is structured in a way that is as useful to other component libraries

**Comment by jelbourn** [comment]
(revisiting old issues)

I'm going to close this since, while we would like to do something in this area, it's realistically so low priority that it would probably be years before we'd work on it.
