### ISSUE TITLE
Datatable samples have wrong alignment for the numbers 

### ISSUE THREAD

**Issue by psalom** [angular/components#9925]
#### Bug, feature request, or proposal:
Wrong alignment for the numbers in the datatable samples.
Right alignment helps for comparison and calculation.

#### What is the expected behavior?
Right-aligned numeric columns
Left-aligned text columns

#### What is the current behavior?
left-aligned numeric columns
Left-aligned text columns

#### What are the steps to reproduce?
https://material.io/guidelines/components/data-tables.html#data-tables-structure

**Comment by andrewseguin** [comment]
Are you referring to the material.angular.io examples? Or are you hoping that the table does this automatically?

**Comment by psalom** [comment]
Yes I think examples must be aligned with the spec. thx a lot

**Comment by CDDelta** [comment]
@andrewseguin I'm not sure if this is the right place to put it but I think `mat-table` should provide a directive for specifying numeric columns and automatically align the text for us since it is part of the spec.
