### ISSUE TITLE
[Tabs] Horizontal scroll doesn't disappear after removing all tabs

### ISSUE THREAD

**Issue by AbakumovAlexandr** [angular/components#9953]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
After removing all tabs no horizontal scroll should be visible.

#### What is the current behavior?
After removing all tabs horizontal scroll stays visible.

#### What are the steps to reproduce?
StackBlitz: https://stackblitz.com/edit/angular-mat2-tab-scroll-issue
If you close a tab by clicking on [x] button in tab header, horizontal scroll will stay visible.

#### What is the use-case or motivation for changing an existing behavior?
When there is no tabs, tab control shouldn't occupy any space, so no scrolls should be displayed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular, Material 5.2.1.

**Comment by mmalerba** [comment]
Confirmed that this works as expected in v15: https://stackblitz.com/edit/angular-8kcahg
