### ISSUE TITLE
[Table] Docs example doesn't correctly change pages when filtering

### ISSUE THREAD

**Issue by narthur157** [angular/components#9965]
#### Bug, feature request, or proposal:
Bug, or proposal depending on perspective

#### What is the expected behavior?
If paged forward and filtering, we can still use the paginator somehow to get to the first page
Essentially if we are not at page index 0, we should _always_ be able to page backwards to the first page

#### What is the current behavior?
Go to last example here: https://material.angular.io/components/table/examples
Filter by 55, note how there are 3 results
Clear the filter, and page forward a few times
Filter by 55 again
Note how there are no results, and we are unable to change our page

#### What are the steps to reproduce?
See above

#### What is the use-case or motivation for changing an existing behavior?
The UX is confusing, the user can hack around this issue by clearing their filter and re-entering it. Note that the page index _does_ get reset by the filtering, but only after changing the filter _twice_. So if the user does the following:
Page forward twice
Enter 55 in filter (there is now no results in table)
Add another 5 to make it 555 (no results because there are none)
Backspace back to 55
Now there are results! This is confusing behavior

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using whatever version is on the docs right now, on Chrome

**Comment by mmalerba** [comment]
Confirmed that this is working in v15 https://stackblitz.com/run?file=src%2Fapp%2Ftable-overview-example.ts
